### ISSUE TITLE
Feature Request: interface to interface casting and coercing

### ISSUE THREAD

**Issue by leighmcculloch** [vlang/v#10010]
Moving discussion from https://github.com/vlang/v/issues/9755#issuecomment-831669533 here.

I think the issue I'm experiencing is the same as @fieryorc discussed in #9755, but @spaceface777 thinks it is a different issue and [asked me](https://github.com/vlang/v/issues/9755#issuecomment-831765906) to open a new issue.

---

I'm seeing an issue when I've given a function an io.ReaderWriter and that function wants to pass on that io.ReaderWriter as an io.Reader to another function.

This is logically a sane thing to do. After-all, the value inside the io.ReaderWriter implements both io.ReaderWriter and io.Reader since io.Reader is a subset of io.ReaderWriter. Logically, any instantiated io.ReaderWriter implements io.Reader.

The docs say the following about interfaces:
https://github.com/vlang/v/blob/c21df2d44cf49bbc2333e7e33bf400c542835c8b/doc/docs.md#L2218

Upon reading this ☝🏻 my assumption is that the value I'm passing around wrapped in an io.ReaderWriter would coerce to io.Reader since both the value within, and the interface I'm passing, implement io.Reader. An interface is a type, and the interface I'm passing around has an implementation for the interface I'm wanting to cast to.

This is how interfaces work in Go.

I think without this capability it will be difficult to compose using interfaces, which is something that is very easy to do in Go, but difficult in V.

Note that if interface embedding (https://github.com/vlang/v/pull/9935) would fix this specific case since logically io.ReaderWriter could be expressed as the embeds of both io.Reader and io.Writer, I think it should be possible to cast between compatible interfaces regardless of whether the interfaces know of each other through embedding. That's how interfaces work in Go and it is very powerful.

**Comment by mcastorina** [comment]
I fully agree. A type either implements an interface or not, there should be no need for casting / coercing.

**Comment by kahsa** [comment]
Is this still not fixed today?

**Comment by JalonSolov** [comment]
If it is working as it is supposed to work, what is there to fix?

**Comment by kahsa** [comment]
This issue can be closed.
