### ISSUE TITLE
C functions in code disappear when v -prod is used to compile

### ISSUE THREAD

**Issue by pverghese** [vlang/v#1002]
**V version:** 0.1.12
**OS:** Linux

**What did you do?**
Compiled the below code using v -prod
When compiled using normal v, it works correctly but not when using v -prod.

Checked the transpiled C code in .vlang and all references to printf from the code below are not there.

module main()

fn main() {
C.printf('Hello\n')
}

**What did you expect to see?**
Hello
 
**What did you see instead?**
Nothing

**Comment by vertical222** [comment]
Alex mentioned C.printf is removed when compiled with `-prod`, you can only use println temporary

**Comment by pverghese** [comment]
Is it only C.printf or all C functions that we might use?

**Comment by pverghese** [comment]
Ok i checked. Other C functions are fine. Thanks

**Comment by vertical222** [comment]
https://github.com/vlang/v/blob/ebbea9f560c70c94842f12772b483b3de2d8b957/vlib/builtin/builtin.v#L35

For the println formatting, it use printf under the hood and you could write the same formatting as in C like this:
```
pi := 3.1415926
println('pi = ${pi:.3g}') // 3.14
```

**Comment by medvednikov** [comment]
This should remain open until I fix the disappearing printf's :)

I'll do this today, need to remove 2 lines of code.

**Comment by medvednikov** [comment]
Fixed.
