### ISSUE TITLE
Wrong line number in panic messages (another \r\n issue?)

### ISSUE THREAD

**Issue by vitalyster** [vlang/v#1005]
**V version: d47e2f113fb419e8a4309364d4c53e34f26045ed** 
**OS: Windows** 

**What did you do?**

Add `;` to `compiler/parser.v` after `import rand` on line 7

**What did you expect to see?**

Under Linux and Mac I see correct message with 7:
```
panic: parser.v:7
unexpected token `;`
 ```
**What did you see instead?**

Under Windows I see line 11, and it eventually grows with file size, looks like it count \r\n as 2 lines

**Comment by medvednikov** [comment]
I just love \r\n

Good find, thanks.

Should be fixed.

**Comment by vitalyster** [comment]
Verified and confirmed
