### ISSUE TITLE
Not a vlang but discord vlang question

### ISSUE THREAD

**Issue by Ekopalypse** [vlang/v#10054]
As of today I have received information that I need to verify my identity by providing a phone number in order to send messages.
I don't get this from other Discord channels, so I think this is something set up for the vlang server.
Since I don't have a cell phone, I can't fulfill this requirement. 
Is this something I have to live with?

![image](https://user-images.githubusercontent.com/47723516/117544048-c590ad80-b01f-11eb-88fd-3112039b77b4.png)

**Comment by leahlundqvist** [comment]
Unfortunately right now we're experiencing a lot of attacks from bots joining and spamming targeted harassment towards me specifically. Therefore we have taken some steps to tighten the locks on the server for a little while. I've just deployed a bot that *should* deal with the bulk of the spam, we'll see how it performs and decide wether we can lift the phone verification requirement or not. Hopefully they move on to something else soon 🙏

There's also a link between Discord and Matrix now which you could try using. Maybe someone can jump into this thread to explain how to set that up? I haven't used Matrix myself so I have no clue :p

**Comment by Ekopalypse** [comment]
Oh god, if you have to, keep the restriction.
I'm mainly just a reader anyway. 
I hope the nonsense with the bots comes to an end soon and don't let it affect you.
Good luck.

**Comment by ylluminate** [comment]
@Ekopalypse Matrix is now an option to and is bridged with the community. Efforts are being made by Discord, etc. to reduce the bot craziness and hopefully this will melt away soon, but that is an option.

**Comment by JalonSolov** [comment]
https://matrix.org/

**Comment by Ekopalypse** [comment]
Thanks to all - let's see if I can make this work.
