### ISSUE TITLE
docs.md : Missing method redeclaration paragraph

### ISSUE THREAD

**Issue by atorr0** [vlang/v#10057]
Hi,

I think _method re-declarations paragraph_ should be clearly stated at **Methods** section, as I think this is not only a very useful feature, but also it allows people coming from OOP (like Java), feeling more "like home" with V.

I accidentally discovered this feature by reading vweb's init_server() function.

Thank you in advance,

**Comment by mcastorina** [comment]
I agree! PRs welcome :)

**Comment by atorr0** [comment]
I'm not good at documentation, but I'll do my best :)

**Comment by medvednikov** [comment]
Hi @atorr0 

Sorry for the delay.

Can you please explain what you mean by method redeclaration. A simple example?

Is it related to embedded structs?
