### ISSUE TITLE
main fails compile if it returns a value

### ISSUE THREAD

**Issue by alfclement** [vlang/v#1008]
**V version:** V 0.1.12
**OS:** 

**What did you do?**
```
fn main() int
{
        return 0
}
```

**What did you expect to see?**
nothing ;-)
 
**What did you see instead?**
```
/home/alf//.vlang//ex-main.c:3095:13: error: expected ‘;’ before numeric constant
  return   0 0 ;
             ^
V panic: clang error
```

**Comment by elimisteve** [comment]
`main` shouldn't return a value :-) . Why do you want it to?

**Comment by medvednikov** [comment]
Well the language should not allow this. It's a quick fix.

**Comment by vitalyster** [comment]
`main` should return value to inspect return code in scripts, for example

**Comment by medvednikov** [comment]
In V you use `exit(code)` for this

**Comment by vitalyster** [comment]
ok, agreed then

**Comment by medvednikov** [comment]
Fixed:

`fn main must have no arguments and no return values`

**Comment by alfclement** [comment]
ok, agreed. nice for embedded systems
So exit() is/becomes a builtin function? 
args will come via a os module?

Is the plan to get rid of accessing C lib via C.function interface? Or will this stay part of V?
