### ISSUE TITLE
Support default comparison of structs

### ISSUE THREAD

**Issue by hdante** [vlang/v#10082]
$ v
    Welcome to the V REPL (for help with V itself, type `exit`, then run `v help`).
    V 0.2.2 8547762
    Use Ctrl-C or `exit` to exit, or `help` to see other available commands
    >>> struct Struct1 {
    ...  field1 int
    ...  field2 string
    ...  field3 f32
    ...  field4 byte
    ... }
    >>> a := Struct1{}
    >>> b := Struct1{}
    >>> a < b
    error: undefined operation `Struct1` < `Struct1`
       20 | 
       21 | }
       22 | println(a < b)
          |         ~~~~~

Struct comparison might be implemented by default as:

    a < b <=> a.field1 < b.field1 ||                                                                        \
              (a.field1 == b.field1 && a.field2 < b.field2) ||                                              \
              (a.field1 == b.field1 && a.field2 == b.field2 && a.field3 < b.field3) ||                      \
              (a.field1 == b.field1 && a.field2 == b.field2 && a.field3 == b.field3 && a.field4 < b.field4)

**Comment by mcastorina** [comment]
Adding another datapoint - Rust allows you to `derive` the traits necessary for sorting a struct.

> When derived on structs, it will produce a lexicographic ordering based on the top-to-bottom declaration order of the struct’s members.
