### ISSUE TITLE
gg: width of draw_line()

### ISSUE THREAD

**Issue by kahsa** [vlang/v#10080]
Like TextConfig, nice to have PenConfing in `gg`.

**Comment by medvednikov** [comment]
why not just use gg.draw_rect() for that?

**Comment by kahsa** [comment]
Isn't it nice if we have `draw_line(x1, y1, x2, y2, PenConfig{ width: 3, style: dash_dot, color: rgb(0,0,0), .....})` ?

**Comment by kahsa** [comment]
implemented by #10513
