### ISSUE TITLE
println does not print arrays

### ISSUE THREAD

**Issue by alfclement** [vlang/v#1009]
**V version:** V 0.1.12
**OS:** 

**What did you do?**
```
struct U{
      name string
      age  [3]int
  }

fn (u U) println() {
   println('Name:'+u.name)
   println('Age:'+u.age[0].str())
}

fn (u U) str() string { return '{Name $u.name, $u.age[0]}' }

fn main() {

  arr := [1,2,3,5]
  println(arr)
  //println('$arr')

  u:=U{'me',23}
  println(u)
  //println('$u')
  println('$u.name,$u.age')

  for i:=0; i < arr.len; i++ {
     println('$i') // $arr[$i]', $arr[i])   # varargs required!
  }
}
```

**What did you expect to see?**

 
**What did you see instead?**
```
$ ./v run ex-println.v
panic: ex-println.v:12
unhandled sprintf format "[3]int"
```

Several improvements are required to println formatting...
* varargs
* array interpolation for $var
* formatting of structs

**Comment by medvednikov** [comment]
String interpolation doesn't work with indexing yet.

**Comment by cytown** [comment]
Seems V did not support variant variables, which should be supported.

So printf can not be implemented...

**Comment by ntrel** [comment]
Variadic functions is now #1061.

**Comment by tobyjwebb** [comment]
Does anyone know how to initialize a [3]int inside a struct? The Go way doesn't seem to work...

```
struct U{
      age  [3]int
}
fn main() {
  u:=U{[12,34,56]}
}

ERROR: field value #1 `age` has type `[3]int`, got `[]int`
```

**Comment by medvednikov** [comment]
` u:=U{[12,34,56]!!}`

:)

It's a temporary hack.

**Comment by medvednikov** [comment]
Fixed.
