### ISSUE TITLE
Crash when I try to alias map[string]bool

### ISSUE THREAD

**Issue by mark-summerfield** [vlang/v#10094]
$ v doctor
OS: linux, Ubuntu 20.04.2 LTS
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
CC version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

getwd: /home/mark/app/v
vmodules: /home/mark/.vmodules
vroot: /home/mark/opt/v
vexe: /home/mark/opt/v/v
vexe mtime: 2021-05-13 10:15:38
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 c16bb7f.1086b4a

Git version: git version 2.25.1
Git vroot status: weekly.2021.17-178-g1086b4ac
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81

**What did you do?**
v run wordladder.v

Here's the complete source code
```v
import time

const (
	wordfile = '/usr/share/hunspell/en_GB.dic'
	size     = 4 // Must be even
	steps    = size
)

type WordSet = map[string]bool

fn main() {
	words := read_words(wordfile, size)
	start := time.now()
	// TODO
	println('${(time.now() - start).seconds():0.3f}')
}

fn read_words(wordfile string, size int) WordSet {
	mut words := WordSet{}
	// TODO
	return words
}
```

**What did you expect to see?**
Print of a float.
 
**What did you see instead?**
V panic: as cast: cannot cast `v.ast.Map` to `v.ast.Struct`
v hash: 1086b4a
/tmp/v/v2.16054846960059939462.tmp.c:13693: at v_panic: Backtrace
/tmp/v/v2.16054846960059939462.tmp.c:13964: by __as_cast
/tmp/v/v2.16054846960059939462.tmp.c:10158: by v__checker__Checker_struct_init
/tmp/v/v2.16054846960059939462.tmp.c:15945: by v__checker__Checker_expr
/tmp/v/v2.16054846960059939462.tmp.c:13640: by v__checker__Checker_assign_stmt
/tmp/v/v2.16054846960059939462.tmp.c:14390: by v__checker__Checker_stmt
/tmp/v/v2.16054846960059939462.tmp.c:15004: by v__checker__Checker_stmts
/tmp/v/v2.16054846960059939462.tmp.c:19415: by v__checker__Checker_fn_decl
/tmp/v/v2.16054846960059939462.tmp.c:14445: by v__checker__Checker_stmt
/tmp/v/v2.16054846960059939462.tmp.c:9369: by v__checker__Checker_check
/tmp/v/v2.16054846960059939462.tmp.c:9435: by v__checker__Checker_check_files
/tmp/v/v2.16054846960059939462.tmp.c:19656: by v__builder__Builder_middle_stages
/tmp/v/v2.16054846960059939462.tmp.c:19673: by v__builder__Builder_front_and_middle_stages
/tmp/v/v2.16054846960059939462.tmp.c:20107: by v__builder__Builder_gen_c
/tmp/v/v2.16054846960059939462.tmp.c:20137: by v__builder__Builder_build_c
/tmp/v/v2.16054846960059939462.tmp.c:20174: by v__builder__Builder_compile_c
/tmp/v/v2.16054846960059939462.tmp.c:21162: by v__builder__compile
/tmp/v/v2.16054846960059939462.tmp.c:21979: by main__main
/tmp/v/v2.16054846960059939462.tmp.c:22384: by main

**Comment by Kiraub** [comment]
Hi, the error is telling you that you are trying to implicitly convert a struct to a map.
This is due to using the struct declaration syntax when you wanted to do an explicit cast:
```v
type AliasedType = map[string]bool
struct StructType {}

fn some_func() {
  mut aliased_type := AliasedType(map[string]bool)
  mut struct_type := StructType{}
}

Using the type alias `WordSet` requires you to cast a value of type `map[string]bool` to your own aliased type as demonstrated above.

**Comment by mark-summerfield** [comment]
Thank you, I've now done: `mut words := WordSet(map[string]bool)` and that compiles fine.

I don't understand what the purpose of the `StructType` is in your example?

Nor can I find how to print a _type_ rather than a value. For example I'd like to print the type of `words` rather than the map itself.

**Comment by JalonSolov** [comment]
```v
println(typeof(words).name)
```
