### ISSUE TITLE
vfmt removes generics necessary for compilation

### ISSUE THREAD

**Issue by alii** [vlang/v#10098]
I have this (compiling) fn signature for inverting a tree
```vlang
fn invert_tree<T>(node &Node<T>) Node<T>
```
however, format-on-save in VSCode will convert this to 
```vlang
fn invert_tree<T>(node &Node) Node
```
which does _not_ compile.

Example file: https://github.com/alii/hello-v/blob/master/main.v

**Comment by yuyi98** [comment]
Please give a simple complete source codes, the following is ok.

```vlang
struct Node<T> {
mut:
	val T
}

fn invert_tree<T>(node &Node<T>) Node<T> {
	return node
}

fn main() {
	_ = invert_tree(&Node<int>{})
}
```

**Comment by alii** [comment]
Have edited op with link to example file @yuyi98.

**Comment by yuyi98** [comment]
OK, the problem is `import structs { Node }`.

**Comment by serkonda7** [comment]
@yuyi98 the import isn't the problem.
I have some minimal reproduction sample here:
```v
struct Node{}

fn invert_tree<T>(node &Node<T>) Node<T> {
	return Node{}
}
```

**Comment by yuyi98** [comment]
The Node should be generic structs in this sample like `Node<T>{}`.

**Comment by serkonda7** [comment]
So this code shouldn't even compile?
```
struct Node {}

fn x<T>(node &Node<T>) Node<T> {
	return Node{}
}
```
And fmt might remove the generic types automatically.
