### ISSUE TITLE
Cannot iterate over keys & values in a struct.

### ISSUE THREAD

**Issue by alii** [vlang/v#10100]
```
OS: macos, macOS, 11.3.1, 20E241
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
CC version: Apple clang version 12.0.5 (clang-1205.0.22.9)

getwd: /Users/alistair/code/vestock-monitor
vmodules: /Users/alistair/.vmodules
vroot: /Users/alistair/v
vexe: /Users/alistair/v/v
vexe mtime: 2021-05-13 15:12:36
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 c5285e7.a9435f3

Git version: git version 2.30.2
Git vroot status: weekly.2021.19-34-ga9435f3c
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 689c8a02
```
**What did you do?**
Tried to iterate through a struct

**What did you expect to see?**
The keys and values would be iterated through
 
**What did you see instead?**
A compiler error saying
```
a struct must have a `next()` method to be an iterator
```

---

A full example of the error can be seen at this commit [here `alii/vestock-monitor`](https://github.com/alii/vestock-monitor/tree/2702515cfb8a8d158562818b401c568810f40d99). See `util/api.v`, line 21

**Comment by crthpl** [comment]
This is intended behaviour; add a `next()` method if you want to iterate through a struct.
