### ISSUE TITLE
fmt mixes spaces and tabs when formatting structs

### ISSUE THREAD

**Issue by khalyomede** [vlang/v#10120]
**What did you do?**

Formatted a file containing a struct using `v fmt -w src/model/shopping-item.v`:

```v
module model

pub struct Shopping_Items {
pub:
	id               int    [primary; sql: serial]
	slug             string [nonull]
	shopping_list_id int    [nonull]
	bar_code         string [nonull]
	name             string [nonull]
	quantity         int    [nonull]
	image            string [nonull]
}
```

**What did you expect to see?**

Only tabs or spaces

 
**What did you see instead?**

A mix of both (not sure if intended)

![fmt-mixes-space-tabs](https://user-images.githubusercontent.com/15908747/118558863-81ac4f80-b767-11eb-97d2-d21a4e2818ed.png)

Maybe it is easier to go spaces only for formatting (it seems spaces have been used because they looks like handy when it comes to create nicely spaced columns)?

| OS                    | linux, Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020 (WSL 2) |
|-----------------------|---------------------------------------------------------------------------------------------------------------------------------------------|
| Processor             | 12 cpus, 64bit, little endian, AMD Ryzen 5 3600 6-Core Processor                                                                            |
| CC Version            | cc (Alpine 9.3.0) 9.3.0                                                                                                                     |
| getwd                 | /home/alpine                                                                                                                                |
| vmodules              | /root/.vmodule                                                                                                                              |
| vroot                 | /opt/vlang                                                                                                                                  |
| vexe                  | /opt/vlang/v                                                                                                                                |
| vexe mtime            | 2021-05-17 20:54:51                                                                                                                         |
| is vroot writable     | true                                                                                                                                        |
| is vmodules writable  | true                                                                                                                                        |
| V full version        | V 0.2.2 c16bb7f.4c22370                                                                                                                     |
| env VFLAGS            | "-cc gcc"                                                                                                                                   |
| Git version           | git version 2.24.4                                                                                                                          |
| Git vroot status      | weekly.2021.17-200-g4c223706                                                                                                                |
| .git/config present   | true                                                                                                                                        |
| thirdparty/tcc status | thirdparty-linux-amd64 7543de81                                                                                                             |

**Comment by Gladear** [comment]
The mix is intented. Tabs are used for indentation and spaces are used to align the default arguments or attributes.
This is the same behavior as gofmt and will likely be kept.
