### ISSUE TITLE
CGen breaks when passing a V String's .str field to a function with &byte parameters.

### ISSUE THREAD

**Issue by TristanCrawford** [vlang/v#10127]
**V version:** V 0.2.2 75d1b54.9a7acd2
**OS:** windows, Microsoft Windows 10 Pro v19042 64-bit

**What did you do?**

```v
#include "Windows.h"
#flag -luser32

fn C.MessageBoxA(voidptr, &byte, &byte, int)

fn main() {
  C.MessageBoxA(0, "Message".str, "Title".str, C.MB_OK)
}
```

**What did you expect to see?**

A nice little message box, with the appropriate message and title.
 
**What did you see instead?**

```
builder error:
==================
C error. This should never happen.
```

**Comment by TristanCrawford** [comment]
For the record, @JalonSolov advised me to do the following in Discord which works just fine for now:
```v
fn C.MessageBoxA(voidptr, &byte, &byte, int)

fn main() {
	C.MessageBoxA(0, c"Message", c"Title", C.MB_OK)
}
```

I'd be happy to look into this if needed, though I'm not well-versed in compiler development; so I may need a starting point to jump off from :)

**Comment by Gladear** [comment]
Imho, these automatic C string when calling a C function should be removed altogether.
It is less explicit you're passing a C string, prepending `c` isn't much more to type, and it only concerns C interop, which shouldn't be used by most users

**Comment by JalonSolov** [comment]
That would be fine... as long as the compiler told you to add the `c` instead of letting it get to a C compiler error.

**Comment by Gladear** [comment]
With what I had in mind, the compiler would tell something along with "parameters type is u8/charptr, but you're passing a string", basically a classic type error. But I will implement a deprecation warning first, so that code can be updated, and not to break without reason.
