### ISSUE TITLE
Quantum Programming Support

### ISSUE THREAD

**Issue by creepymred** [vlang/v#10126]
Let's start to develop quantum programming features, why? Because it's the future.
And I don't wanna my weapon of choice is not future proof.

**Comment by 54** [comment]
Agreed. Vlang has no future without this support. +1
Rust doesn't  have this yet either, let's forge ahead of the pack.

**Comment by notYuriy** [comment]
V adding support for quantum computing would move it from "not useful at all" to "barely useful for quantum computing"
