### ISSUE TITLE
Updating via "v up" breaks REPL

### ISSUE THREAD

**Issue by thetalmid** [vlang/v#10122]
```
cannot compile `/opt/v/cmd/tools/vrepl.v`:
vlib/builtin/cfns.c.v:19:2: error: non existent integer const trusted while initializing the size of a static array
   17 | fn C.free(ptr voidptr)
   18 |
   19 | [trusted]
      |  ~~~~~~~
   20 | fn C.exit(code int)
   21 |

```

The problem appeared after an attempt to update using `v up` on Ubuntu 20.04.
Can't run any commands at this point (`v outdated`, `v install`, `v doctor`, etc.)

**Comment by Gladear** [comment]
How did you install V ? Was it building from source or using a package manager ?

**Comment by thetalmid** [comment]
Built it from source.

**Comment by Gladear** [comment]
It may have been a temporary problem, can you try again and see if it works now ?

**Comment by thetalmid** [comment]
Yup, it works! Just a hiccup after all.
Thanks!

**Comment by Gladear** [comment]
Nice, it can happen from time to time 🙂 
In this case, either clone the repo again, or do `git pull` and `make` (or `make.bat` on Windows). The first is more likely to succeed !
