### ISSUE TITLE
v install --save (or some other verb) to automatically add the installed package to v.mod dependencies

### ISSUE THREAD

**Issue by adrianvoica** [vlang/v#10153]
Please consider adding
v install --save (or some other verb) to automatically add the installed package to v.mod dependencies (just like npm does, of course).

For instance:
`v install --save nsauzede.vnk `
should add "nsauzede.vnk" to the dependencies array in `v.mod`

...or, is there such an option already?

I just started up with V (few days ago), and it's brilliant. I am in love again.

Keep up the good work!

**Comment by JalonSolov** [comment]
Which v.mod?

If there wasn't one in the local directory, do you want it to create one just so it can add this dependency?

What if your current directory is the main V install dir - we don't want it adding to that one.

If it does add it, should it sort it into the list of dependencies, or just add it... and if adding it, where?

Beginning of the list or end of the list?

It is much simpler and easier if you manually add dependencies exactly where you want them to be.

**Comment by adrianvoica** [comment]
So, ok. As I said, I just started learning / writing V code recently ❤️ ❤️ ❤️ . 

The documentation is a bit scattered at this time, I tried learning V from all the available sources I found: some github links (some of which are a bit outdated or incomplete) from awesome-v, from the official docs, and by studying the sourcecode for the built-in modules and examples), but I still need some more time and practice to chew on the specs to wrap my head around all the constructs and idioms of the language and its tools. 

However, if I'm delving into (e.g.: cloning) a project that is already using, say, 7 custom modules from the VPM, do I need to manually search for the imports in the source code and then install said modules by hand? seems a bit off. Am I missing something here?

Thanks for your patience.

**Comment by JalonSolov** [comment]
V will automatically install modules just from the import statements in the code when you compile.

The only reason to add dependencies to a v.mod file would be if you were creating your own separate module for others to download.  There will be functionality that would auto-import those dependencies when someone installs/imports your module, to speed things up.  However, I don't think that works just yet.

For normal use, just compiling code (especially while learning), you don't need to do anything other than add an import to your code and compile it.

**Comment by adrianvoica** [comment]
That's even more V awesomeness, right there!  Thanks for the explanation! 
Though, I wish the docs were more concise and better prepared for newcomers. 
I might document my learning steps and helpful materials that I'll use along the learning process into a multi-part blog post or something for other newcomers to use. 
The language is really nice and really powerful, the barrier to entry seems very low, but there are (lots of) hidden quirks and tricks that you don't easily read from the documentation alone. 
Thank you!

**Comment by JalonSolov** [comment]
Documentation will be improved over time.  V is still alpha, so more work has gone into stabilizing the compiler and libs than into writing detailed docs.
