### ISSUE TITLE
a bug about array

### ISSUE THREAD

**Issue by hanxiaohuivc** [vlang/v#10160]
**V version: 0.2.2 d5c306c** 
**OS: win10** 

**What did you do?**
 I defined the following function: 
        pub fn (mut pageitem PageItem) addchilren(mut children []Widget)
 When using this function, I defined a Button variable: btn：
        mut child := [btn]
        app.pageitem.addchilren(mut child)

**What did you expect to see?**

 
**What did you see instead?**
Now the error is reported as follows: 
    error: cannot use []&ui.Button as &[]ui.Widget in argument 1 to ‘ui.PageItem.addchilren‘

**Comment by medvednikov** [comment]
Fixed.
