### ISSUE TITLE
Have IntelliJ IDEA support or IntelliJ CLion support?

### ISSUE THREAD

**Issue by zhuxiujia** [vlang/v#1017]
Have IntelliJ IDEA support or IntelliJ CLion support?
A good language needs a game IDE

**Comment by Smartyue** [comment]
Named "V land" or "V Storm" is better😄

**Comment by lppedd** [comment]
Someone that has knowledge of parsers and lexers could init a repository. I could contribute to additional features (code refactoring, usages, go-to, etc).

**Comment by lppedd** [comment]
@medvednikov Hi! Is there somewhere a BNF (or other format) description of the V language?

**Comment by Delta456** [comment]
You can join our discord server for discussions and see vlang.io for description for the language but it is pretty outdated.

**Comment by lppedd** [comment]
@Delta456 I've looked at the vlang site but couldn't find a spec for the language syntax.
I'll join the Discord server tonight, thanks. I'm looking for a spec just to get basic syntax highlight working.

**Comment by donnisnoni95** [comment]
@lppedd Maybe this help https://github.com/0x9ef/vscode-vlang

**Comment by lppedd** [comment]
@donnisnoni95 thank you. That might be useful for the Flex part. Unfortunately I don't think TextMate highlight syntax can be transposed in BNF grammar.

**Comment by donnisnoni95** [comment]
ohhh... sorry I didn't know that  😁

**Comment by lppedd** [comment]
@donnisnoni95 no problem. I'm pretty ignorant about lexers and parsers, so I welcome every help.
I work 99% of the time on IDEA and I contributed to some plug-ins, however I've never done a custom language infrastructure.

**Comment by nedpals** [comment]
General discussion about syntax support and editor in V is in #465
