### ISSUE TITLE
cannot define new methods on non-local type `Key`

### ISSUE THREAD

**Issue by 0x9ef** [vlang/v#1018]
**V version:** 0.1.12
**OS:** win10x64

**What did you do?**

```
type Key voidptr

fn (k mut Key) close() {
    k = 0
}

fn main() {
    k := Key(152)
    k.close()
}
```

**What did you expect to see?**
`program.exe`
 
**What did you see instead?**
```
T.pkg=
pkg=main
panic: test2.v:9
cannot define new methods on non-local type `Key`
```

**Comment by 0x9ef** [comment]
Same error with other modules.

`vlib/registry/registry.v` - self defined.
`cannot define new methods on non-local type Key`

**Comment by medvednikov** [comment]
Fixed.
