### ISSUE TITLE
Unexpected restrictions for identifier names

### ISSUE THREAD

**Issue by MaxGraey** [vlang/v#102]
```go
fn main() {
	short := [1, 2, 3]
	println(short)
}
```
```
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.
```
The same with `float`, `long`, `unsigned`, `signed`, `void`, `inline`, `typedef` and `double`.
The same issue as #101

All of this names are not reserved keywords

But with some reserved keywords like `bool` this works =)
```go
bool := [1, 2, 3]
println(bool)
```
```
[1, 2, 3]
```

**Comment by medvednikov** [comment]
All C keywords and types will result in this.

Not critical, will fix after the release.

**Comment by tobyjwebb** [comment]
@medvednikov Looks like this has been fixed now?

**Comment by medvednikov** [comment]
Indeed :)
