### ISSUE TITLE
Runtime Error on Windows TCC32 with os.symlink() + os.real_path() not working with symlinks

### ISSUE THREAD

**Issue by bstnbuck** [vlang/v#10208]
**V version:** V 0.2.2 cf07375.2abbbcc
**OS:** Windows 10 with TCC 32 bit

**What did you do?**

**UPDATE: #10251 is still a temporary fix, TCC should still be fixed**
**2nd UPDATE: 95cf120e2eed1eca20dd2931a20b2ad9d4ad640c to fix `os.real_path()` on Windows due to failing on symlinks.**

```v
import os
fn main(){
	_ := os.symlink("test", "test1")?
}
```
Compiled with `v .`
>> **See failed test**: https://github.com/vlang/v/pull/10203#issue-652682110

I have run several tests and found that the error occurs on the return.
```v
fn C.CreateSymbolicLinkW(&u16, &u16, u32) int

pub fn symlink(target_path string, symlink_path string) ?bool {
	mut flags := 0
	if is_dir(symlink_path) {
		flags |= 1
	}
	flags |= 2 // SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE
	res := C.CreateSymbolicLinkW(symlink_path.to_wide(), target_path.to_wide(), flags)
	if res == 0 {
		return error(get_error_msg(int(C.GetLastError())))
	}
	if !exists(symlink_path) {
		return error('C.CreateSymbolicLinkW reported success, but symlink still does not exist')
	}
        println("This is printed before Runtime Error")
	return true
}
```
Compiling with `v -prod .` works too

**What did you expect to see?**
Works fine...
 
**What did you see instead?**
Runtime Error with `Unhandled Exception 0xC0000005` and `RUNTIME ERROR: invalid memory access`

**Comment by ChildishGiant** [comment]
For me when running the example code I get a different error. 
V version: V 0.2.2 2abbbcc

```
PS C:\Users\allie\Desktop\test> v run .
V panic: optional not set (C.CreateSymbolicLinkW reported success, but symlink still does not exist)
v hash: 2abbbcc
C:/Users/allie/AppData/Local/Temp/v/test.10285636173476678599.tmp.c:6415: at v_panic: Backtrace
C:/Users/allie/AppData/Local/Temp/v/test.10285636173476678599.tmp.c:6388: by panic_optional_not_set
C:/Users/allie/AppData/Local/Temp/v/test.10285636173476678599.tmp.c:13702: by main__main
C:/Users/allie/AppData/Local/Temp/v/test.10285636173476678599.tmp.c:14100: by wmain
00461f80 : by ???
004620e3 : by ???
7ffc46c77034 : by ???
```
When running with prod I get another error: 

```
PS C:\Users\allie\Desktop\test> v -prod .
PS C:\Users\allie\Desktop\test> .\test.exe
V panic: optional not set (A required privilege is not held by the client.
)
v hash: 2abbbcc
4 : panic_optional_not_set     ?? : address = 0x955b0ec98
3 : wmain                      ?? : address = 0x955b0ec98
2 : __scrt_common_main_seh     d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
1 : BaseThreadInitThunk        ?? : address = 0x955b0ec98
0 : RtlUserThreadStart         ?? : address = 0x955b0ec98
```

**Comment by bstnbuck** [comment]
Under windows you need administrator rights to create symlinks. Open CMD as Admin and run it from there.

**Comment by ChildishGiant** [comment]
For me I get no errors when running as admin

**Comment by bstnbuck** [comment]
Which C-Compiler do you use? With GCC, MSVC and TCC64 it works well.
The error occurs only on Windows with TCC in 32 bit mode. If you want reproduce it you have to install TCC in 32 bit. Means you have to run `make` again with `make.bat -tcc32`. Otherwise the 64bit version is used, which does not give any errors. 
You can find the current TCC version with `v doctor` under thirdparty/tcc. 
Should look like this:
`thirdparty/tcc status: thirdparty-windows-i386 af536d0e`. 

I found this error due to the failed test in my PR.

**Comment by ChildishGiant** [comment]
Yep, I have `thirdparty/tcc status: thirdparty-windows-amd64 40cb2ddb`

**Comment by bstnbuck** [comment]
Yes, this is the wrong TCC version. It must have the ending `i386`, not `amd64`.

**Comment by bstnbuck** [comment]
The produced C code is the same as of the TCC 64bit compiler, which works. Therefore the error seems to be in the TCC 32bit and not in V itself. 
I will release a temporary patch later today.
