### ISSUE TITLE
flappylearning runs strangely on windows

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#10221]
**V version:** 
master

**OS:** 
win10

**What did you do?**
compile flappylearning

**What did you expect to see?**
Compile then run nicely.
 
**What did you see instead?**
Compile, but at runtime

<img width="386" alt="6cf6cf63f644887cd863569637b804a" src="https://user-images.githubusercontent.com/47302112/119827983-51fe0400-bf2c-11eb-852b-37bbec2bcbbe.png">

I don't think this is expected lol

**Comment by leahlundqvist** [comment]
Looks good to me! There are multiple birds as this is an example of machine reinforcement learning with multiple agents (the agents being birds in this case). The weights from the best performing birds are carried over to the next "generation", hence gradually improving their overall performance over time.

**Comment by SleepyRoy** [comment]
@leahlundqvist Great, it makes sense now. I didn't realize it is reinforcement “learning”, instead I thought it was “learning” how to write flappybird lol
