### ISSUE TITLE
MSVC cannot embed files

### ISSUE THREAD

**Issue by kjlaw89** [vlang/v#10244]
V Version: 0.2.2 465860e
OS: Windows 10 (using MSVC compiler)

I'm attempting to do a prod compile with MSVC (stuck with it at the moment) where I'm embedding a file. 

Example files:

```v
module main

pub fn main() {
	file := $embed_file('./embed.txt')
	println(file.to_string())
}
```

embed.txt
```
Testing an embedded file
```

When compiling I receive the following error:

```
C:\......\v\embed_error.13895319604849027706.tmp.c(2383): error C2099: initializer is not a constant
C:\......\v\embed_error.13895319604849027706.tmp.c(2384): error C2099: initializer is not a constant
```

The C code produced:
```c
const v__embed_file__EmbedFileIndexEntry _v_embed_file_index[] = {
	{0, _SLIT("./embed.txt"), _v_embed_blob_0},
	{-1, _SLIT(""), NULL}
};
```

Error:
![image](https://user-images.githubusercontent.com/4183007/120059494-ebf2a900-c01f-11eb-85ec-8589d22f8b62.png)

**Comment by JalonSolov** [comment]
Please do `v up` and try again.  It works fine for me with `V 0.2.2 e4f6369` on both

Windows:
```
PS D:\> v run embed.v
Testing an embedded file

PS D:\>
```
and Linux:
```
jalon@Ripper:~/testing$ v run embed.v
Testing an embedded file

jalon@Ripper:~/testing$
```

**Comment by kjlaw89** [comment]
It's still an issue on the latest version (`V 0.2.2 e4f6369`). It's only an issue when compiling in prod with MSVC: `v -prod -cc msvc .` ... Compiling with tcc or gcc give me a missing header for miniaudio, so I've been working with msvc when I caught this. If you compile without `-prod` it will not produce the error.

**Comment by JalonSolov** [comment]
The missing miniaudio header has nothing to do with this example.

Compiling with `-prod` for me compiles with `gcc` - I don't have msvc.

On Windows:
```
PS D:\> v -prod run embed.v
Testing an embedded file

PS D:\>
```
and on Linux
```
jalon@Ripper:~/testing$ v -prod run embed.v
Testing an embedded file

jalon@Ripper:~/testing$
```
So the problem is strictly with msvc.

**Comment by bstnbuck** [comment]
I can confirm the error. It really only occurs with MSVC and `-prod`.

**Comment by kjlaw89** [comment]
Sorry, didn't mean to imply the headers had anything to do with this... Yes, this is only a msvc error, it works fine for everything else... should have made that more clear.
