### ISSUE TITLE
C error when compiling an already executed program

### ISSUE THREAD

**Issue by bstnbuck** [vlang/v#10241]
**V version:** V 0.2.2 6b683d3.9ea753e
**OS:** Windows 10 (TCC, GCC, MSVC)

**What did you do?**
Compiled an already executed program.

```v
fn main(){
	for { continue }
}
```
**What did you expect to see?**
V error
 
**What did you see instead?**
C error
```
==================
C:/Users/<user>/AppData/Local/Temp/v/test.1222849784580008284.tmp.c:13576: warning: assignment from incompatible pointer type
tcc: error: could not write 'D:\buckt\Desktop\test\test\test.exe': Permission denied
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by JalonSolov** [comment]
That's a Windows problem that V can't do anything about.  And it's long after V has handed control over to the C compiler.

At most, it might be possible for V to capture the output of the C compiler and print a "nicer" message.

**Comment by bstnbuck** [comment]
How about if V checks during the compilation process if the file exists or is writable?

**Comment by JalonSolov** [comment]
It may exist, and be writable.  V would have to check the Windows process table to see if it is running.

**Comment by medvednikov** [comment]
Well GCC solves this somehow, probably at checking if it's writable. We can do the same.

(I can't believe they still haven't fixed this in 2021)

**Comment by bstnbuck** [comment]
Yes, as @JalonSolov wrote, this is a typical Windows problem. It applies not only to Windows GCC but to all Windows C compilers. Linux gets around the problem by keeping the "old" version of the program in RAM or /proc/$PID/smaps among some other places and unlinking the file during the compilation process. After the process is terminated and restarted, the new version is used.

**Comment by JalonSolov** [comment]
Checking if the file is writable won't do any good on Windows.  You also have to check the process table to see if there's a process lock on it.

Linux (all versions of Unix, actually) can do this because the new version of the file has a different inode.  The inode for the original is marked as unused so that any new instances will pick up the new one instead.

**Comment by bstnbuck** [comment]
That's right. Checking whether the file is writable is trivial. The challenge here is checking which process locks the file. After a quick search, we could use the API function LockFile (https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-lockfile) and read the error value. After that we will know if the file is executable or not.
What do you say?

**Comment by JalonSolov** [comment]
Knowing if it's executable doesn't help.  You could be creating a dll or other shared piece of code.  It could also be executable, but not actually running.  Basically, Windows is just a mess.  :-\

**Comment by Zymlex** [comment]
There can be many factors for blocking, ranging from blocking descriptors, access rights, ending with the UAC sandbox (if you have not disabled it and run without full admin rights). To check, it should be enough to try to delete and if file exist - display error.

**Comment by medvednikov** [comment]
Closing, this is a Windows issue.
