### ISSUE TITLE
os.input() sometimes returns <EOF> when compiling with `msvc` and `-prod`.

### ISSUE THREAD

**Issue by bstnbuck** [vlang/v#10267]
**V version:** V 0.2.2 aa861d1
**OS:** Windows 10

**What did you do?**
Sometimes multiple inputs using os.input() is skipped when compiling with `v -cc msvc -prod .` (yes, only `msvc` with `-prod`) and an `<EOF>` is returned. The example here forms this error: https://github.com/bstnbuck/Simple-V-Blockchain. Unfortunately I could not reduce the error to a smaller code with also this error.

**What did you expect to see?**
output: 
```
Welcome to the first Blockchain written in Vlang!
Starting... How much leading hex nulls? 4
How many blocks should be generated? 1
Started: 2021-05-30 16:14:27
...
```
 
**What did you see instead?**
output:
```
Welcome to the first Blockchain written in Vlang!
Starting... How much leading hex nulls? 4
How many blocks should be generated? <EOF>
V panic: optional not set (strconv.atoi: parsing "<EOF>": invalid syntax )
v hash: c67891d
C.CaptureStackBackTrace returned less than 2 frames
```

**Comment by medvednikov** [comment]
Fixed.
