### ISSUE TITLE
No mutable slices of immutable arrays should be allowed

### ISSUE THREAD

**Issue by UweKrueger** [vlang/v#10264]
**V version:** V 0.2.2 5b8402b.ba86d61
**OS:** linux, Ubuntu 20.04.2 LTS

**What did you do?**
```v
fn main() {
    a := [1, 2, 3, 4]
    mut b := a[1..3]
    b[0] = 7
    println(a)
}
```

**What did you expect to see?**
An error for the line `mut b := a[1..3]` like
`cannot create mutable reference to immutable array`
 
**What did you see instead?**
The program compiles and runs giving the output
`[1, 7, 3, 4]`

**Comment by dumblob** [comment]
Hm, currently slices are anyway copy-on-write per doc, correct? So this sounds like a bug to me with the copy-on-write mechanism rather than an issue with `mut`.

Or are they copy-on-write first when `.cap` is overstepped? That'd be pretty weird - one would never know whether she writes to the original array or already to an own copy as this could happen pretty "randomly" (based on how the underlying allocator allocates capacity etc.).

**Comment by UweKrueger** [comment]
> Hm, currently slices are anyway copy-on-write per doc, correct? ...

Not quite. The behaviour is described [here](https://github.com/UweKrueger/v/blob/master/doc/docs.md#array-slices). As long as you do not append elements to the slice or the original you can be sure that they refer to the same elements.

> That'd be pretty weird ...

You are describing Go's behaviour here and that is weird, indeed...
In V, slices are created with a minimal `cap`, so reallocation does not happen *randomly* but in the moment when the first element is appended to the slice. I've called this "copy on grow" in the doc.

**Comment by dumblob** [comment]
> In V, slices are created with a minimal `cap`, so reallocation does not happen _randomly_ but in the moment when the first element is appended to the slice. I've called this "copy on grow" in the doc. My design goal was that appending to one array should never change values in other arrays. (There are exceptions when `.trim()` or `.clear()` are involved.)

Ok, sounds better though still somehow non-explicit. Could we do better? Does `.insert()` also guarantee a copy (if not already copied)? That'd be yet another exception/thing_to_remember (as with `<<` `.trim()` `.clear()`). Does `<<` actually **gurantee** growing it? E.g. appending nothing (`x << []`) will also always make a copy? If not, that'd be an exception in an exception... Not good for a built-in API :cry:.

**Comment by UweKrueger** [comment]
The rule "copy on grow" describes the behviour quite well, I think. The exact rule is "copy on growth *beyond initial size*"- and this also explains the role of `.trim()` and `.clear()`. But I think these are a more a theoretical issue - why would you create a slice and the trim it? Just create it smaller in the first place - or slice it again if you really need to. So, for the answers below I neglect this issue:  

> Does `.insert()` also guarantee a copy (if not already copied)?

Yes - as it involves growth.

> Does `<<` actually **gurantee** growing it?

It's not the operator - it's the growth beyond the initial size that guarantees a copy...

> E.g. appending nothing (`x << []`) will also always make a copy?

... so, no, `x << []`will *never* make a copy, as it involves no growth.

 > Not good for a built-in API 😢.

That's *your* opinion.

**Comment by dumblob** [comment]
Ok, thanks for clarification.

> > Not good for a built-in API cry.
> 
> That's _your_ opinion.

If others (especially systems & game developers who need to know how exactly the memory is managed) do find the current behavior explicit enough, then we definitely need to make all slices always immutable.

**Comment by UweKrueger** [comment]
I close this issue as it has become too much off topic.
