### ISSUE TITLE
autofree: Define proper free method

### ISSUE THREAD

**Issue by IngwiePhoenix** [vlang/v#10277]
Hello!

Short question: When using autofree, I would like my struct to call the apropriate freeing function for whatever it is holding. Is that possible?

Thanks :)

**Comment by spytheman** [comment]
https://github.com/vlang/v/blob/master/doc/docs.md#control

**Comment by IngwiePhoenix** [comment]
Wow. I legitimately didn't find that one because I was looking around the struct documentation. Welp, derp. :) Thank you!
