### ISSUE TITLE
`println('type is: $b.@type')` -> unfinished string literal

### ISSUE THREAD

**Issue by kuche1** [vlang/v#10288]
**V doctor:**
```
OS: linux, "Artix Linux"
Processor: 12 cpus, 64bit, little endian, AMD Ryzen 5 3600 6-Core Processor
CC version: cc (GCC) 11.1.0

getwd: /home/me/coding/v
vmodules: /home/me/.vmodules
vroot: /home/me/Programs/v
vexe: /home/me/Programs/v/v
vexe mtime: 2021-05-31 15:13:35
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 e4f6369.90292ce

Git version: git version 2.31.1
Git vroot status: weekly.2021.21-74-g90292ce9
.git/config present: true
``` 

**What did you do?**
`v -g run test.v`

**What did you expect to see?**
`type is: something`
 
**What did you see instead?**
```
test.v:13:1: error: unfinished string literal
   11 | }
   12 |
```

**Source**
```

struct Some_struct{
	@type string
}

fn main(){
	b := Some_struct{
		@type: 'something'
	}
	println('type is: $b.@type')
}

```

Please correct me if I am missing how `@` works

**Comment by JalonSolov** [comment]
The `@` can be problematic.  It is essentially an escape for a keyword.  It also makes you type an extra character just to use that one word.

Much better to avoid it - use a different name that means the same or similar.  Some possibilities:
```
bracket, breed, category, class, classification, family, genre, genus, group, kind, order, set, sort, species, strain, variety
```

**Comment by lucasrdrgs** [comment]
If you're considering use more than a simple $var string interpolation, I'd highly suggest using ${expression} instead:
```
struct Some_struct{
	@type string
}

fn main() {
	b := Some_struct{
		@type: 'something'
	}
	println('type is: ${b.@type}')
}
```

**Comment by danieldaeschle** [comment]
This is an error anyway, right?

**Comment by lucasrdrgs** [comment]
Seems to be, although I'm not 100% sure as I have no idea of how V handles interpolation with struct fields (although something like `$person.name` does work). `${b.@type}` is a workaround.

**Comment by yuyi98** [comment]
Currently, we must use `${b.@type}`, so it is not an error.
