### ISSUE TITLE
The question of call the C function

### ISSUE THREAD

**Issue by lcddh** [vlang/v#1030]
#flag -lsqlite3

#include "sqlite3.h"

struct C.sqlite3 
struct C.sqlite3_stmt 

fn C.sqlite3_column_int(C.sqlite_stmt, int) int 

fn main() {
	path := 'sqlite3_users.db' 
	db := &C.sqlite3{} 
	C.sqlite3_open(path.cstr(), &db)

	query := 'select count(*) from users' 
	stmt := &C.sqlite3_stmt{} 
	C.sqlite3_prepare_v2(db, query.cstr(), - 1, &stmt, 0)
	C.sqlite3_step(stmt) 
	nr_users := C.sqlite3_column_int(res, 0)
	C.sqlite3_finalize(res)
	println(nr_users) 
} 

Why define this line of 
fn C.sqlite3_column_int (C. sqlite / stmtt, int) int 
instead of C.sqlite3_open, C. sqlite3 _step, C.sqlite3 _finalize

**Comment by aguspiza** [comment]
There is no need for that. Here is a working example:

```
#flag -lsqlite3

#include "sqlite3.h"

struct sqlite3 {}
struct sqlite3stmt {}

const (
    SQLITE_OK = 0
    SQLITE_ROW = 100
)
fn main() {
    path := 'sqlite3_users.db'
    db := &sqlite3{}
    mut rc := int(C.sqlite3_open(path.cstr(), &db))
    if rc == SQLITE_OK {
        query := 'select count(*) from users' 
        stmt := &sqlite3stmt{}
        rc = C.sqlite3_prepare_v2(db, query.cstr(), -1, &stmt, 0)
        if rc == SQLITE_OK {
            rc = C.sqlite3_step(stmt)
            if (rc != SQLITE_ROW) {
                db.print_error('Failed to get data')
            } else {
                nr_users := int(C.sqlite3_column_int( stmt, 0))
                println('$nr_users')
            }
        } else {
            db.print_error('Failed to prepare')
        }
        C.sqlite3_finalize(stmt)
    } else {
        db.print_error('Failed to open')
    }
    C.sqlite3_close(db)   
    exit(0)
}

fn (db &sqlite3) print_error(errstr string) {
    cerr := C.sqlite3_errmsg(db)
    error := tos(cerr, strlen(cerr))
    eprintln('$errstr: $error')
}
```

**Comment by Ivo-Balbaert** [comment]
Please review the sqlite.v example in v\examples
If you have another question, ask it here, otherwise please close the issue.
Thanks!
