### ISSUE TITLE
? operator on map access causes a panic

### ISSUE THREAD

**Issue by rcorre** [vlang/v#10322]
**V doctor:**
```
OS: linux, "Arch Linux"
Processor: 12 cpus, 64bit, little endian, AMD Ryzen 5 5600X 6-Core Processor
CC version: cc (GCC) 11.1.0

getwd: /tmp
vmodules: /home/rcorre/.vmodules
vroot: /home/rcorre/src/v
vexe: /home/rcorre/src/v/v
vexe mtime: 2021-06-02 01:36:45
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 2abbbcc.ce3e71c

Git version: git version 2.31.1
Git vroot status: weekly.2021.22-10-gd8f843ec
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81
```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg thing.v`
```v
fn get() ?int {
	m := map{
		'a': 1
	}
	return m['b'] ?
}

_ := get() ?
println('got i')

```

**What did you expect to see?**

Ideally, `some_map[some_missing_key] ?` would propagate a 'key not found' error.
If not that, `?` on map access should be a compiler error.

Since map access in many languages with optionals (rust and zig come to mind) returns an optional, and since v maps use `or` (which makes it _feel_ like an optional), I had the instinct to think `?` would work.

**What did you see instead?**
```
V panic: optional not set (array index out of range)
v hash: d8f843e
/tmp/v/thing.1386627971623103567.tmp.c:5669: at v_panic: Backtrace
/tmp/v/thing.1386627971623103567.tmp.c:5642: by panic_optional_not_set
/tmp/v/thing.1386627971623103567.tmp.c:10139: by main__main
/tmp/v/thing.1386627971623103567.tmp.c:10529: by main
```

**Comment by mcastorina** [comment]
That panic is from your top level `?`

```v
_ := get() ?
```

Changing the main function to

```v
_ := get() or { println('error: $err') return }
```

yields

```
error: array index out of range
```

So it is working as expected, although perhaps the error message could be improved

**Comment by rcorre** [comment]
Ah, sorry, you're right! Confused myself here.
