### ISSUE TITLE
println(): incorrect new line in thread

### ISSUE THREAD

**Issue by kahsa** [vlang/v#10337]
**V version: 0.2.2 f4486d7** 
**OS: ArchLinux** 

**What did you do?**
```v
import sync

fn f(mut wg sync.WaitGroup, id int){
	defer { wg.done() }
	println('Hello from $id')
}

fn main(){
	n := 5
	mut wg := sync.new_waitgroup()
	wg.add(n)
	for i := 0; i < n; i++ {
		go f(mut wg, i+1)
	}
	wg.wait()
}
```

**What did you expect to see?**

correct new line
 
**What did you see instead?**
randomly incorrect new line
```
Hello from 1Hello from 2

Hello from 3Hello from 4

Hello from 5
```

**Comment by Gladear** [comment]
You can't expect characters to be printed the same way every time you launch a multi-threaded program without explicit synchronization.
This is to be expected, and running the program multiple times will probably give you different results.

**Comment by kahsa** [comment]
I'm not talking about the order, I'm talking about the fact that `println()` doesn't break lines, does that mean that `println()` doesn't work properly in multithreading?

**Comment by Gladear** [comment]
How come it doesn't break lines ? I see 5 like break in your output, two after the first line, two after the second, and one at the end
Isn't that what you expected ?

**Comment by kahsa** [comment]
I edited what I expected.
Is this normal, that this is normal println() behavior, but this is not guaranteed in multithreading?
I don't know enough about multithreading and the println() spec.
