### ISSUE TITLE
problem with string addition

### ISSUE THREAD

**Issue by SurmanPP** [vlang/v#10346]
**What did you do?**
```v
b := ''
mut c := ['a', 'b']
for mut a in c {
 a = a + b
}
```

**What did you expect to see?**
No error
 
**What did you see instead?**
```
error: mismatched types `&string` and `string`
    8 | for mut a in ['a', 'b'] {
    9 |
   10 | a = a + b
      |     ~~~~~
   11 |
   12 | }
```

**Comment by shadowninja55** [comment]
this code can be fixed with `a = *a + b`, but i'm not sure if we want the dereference to be implicit. i'll wait for someone else to take a look.
