### ISSUE TITLE
Question: Why UNICODE is defined in windows cgen only?

### ISSUE THREAD

**Issue by youyuanwu** [vlang/v#10349]
UNICODE is defined in here: https://github.com/vlang/v/blob/9553c5a4e6faf2f2ac19dc7e0200586bde825f7f/vlib/v/gen/c/cheaders.v#L485

Why it is needed?
It is causing c binding problems if c header relies on it. See the hack I did in https://github.com/vlang/v/pull/10336

If it is defined in windows then it should also be defined in linux/mac too. So all c headers have the same behavior across platforms.

**Comment by spytheman** [comment]
I *think* (but I am not sure), that it was done so that printing unicode strings in cmd.exe works.

**Comment by youyuanwu** [comment]
For now mssql binding using undefine works. But in future we might want to fix this and make preprocessor variables consistent across os.
