### ISSUE TITLE
Unused variable in vlib's rand will not allow building with `v -prod`

### ISSUE THREAD

**Issue by lucasrdrgs** [vlang/v#10343]
**V version:** 0.2.2 f4486d7
**OS:** Arch Linux x86_64 5.12.6-arch1-1

**What did you do?**
I imported the rand module and tried to compile my code using the -prod flag.

**What did you expect to see?**
A successful build.
 
**What did you see instead?**
```
vlib/rand/util/util.v:17:13: error: unused variable: `v`
   15 |     mut indices := []int{len: n}
   16 |     // Initialize with all indices
   17 |     for i, mut v in indices {
      |                ^
   18 |         v = i
   19 |     }
```

**Comment by lucasrdrgs** [comment]
Apparently this happens anytime you try to assign a value to x in the following expression: `for i, mut x in my_array`. Compiler doesn't see x as being used.

**Comment by shadowninja55** [comment]
compiles on latest v.
