### ISSUE TITLE
Compilation times

### ISSUE THREAD

**Issue by boeotian** [vlang/v#1035]
Why do you so heavily rely on a metric that hardly matters as a selling-point for your language?

EDIT: To elaborate; 
Even if your language has greased-lightning compilation speeds, it's not gonna matter on any project of decent size or complexity. 
Example: C, C++, C#, & Rust on my build slave. Though the projects I'm building in each language are quite different they are roughly the same LOC & the cyclomatic complexity is +-250 in each language. With a 24 thread, 128GB, GPU accelerated beast it still doesn't have a difference in compilation speed that isn't negligible.

Side-note: Get a better benchmark.
Something like printing the same thing a fuck-ton of times that is easily optimized by the compiler isn't a good way to benchmark the compilation speed of a language.

**Comment by fuzzy** [comment]
Probably for the same reasons go cares about it. Faster build times means more iterations, especially for larger codebases when used with CI/CD pipeline.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by DoctorGester** [comment]
> Even if your language has greased-lightning compilation speeds, it's not gonna matter on any project of decent size or complexity.
Largely disagree. Iteration times on a local machine are extremely important.

> Side-note: Get a better benchmark.
> Something like printing the same thing a fuck-ton of times that is easily optimized by the compiler isn't a good way to benchmark the compilation speed of a language.

Agree.

**Comment by boeotian** [comment]
> Largely disagree. Iteration times on a local machine are extremely important.
I'm probably the only dev you'll meet in 2019 for whom it actually matters anymore (Smartphone CPU in shitty laptop).
Hence my ridiculous build slave.

**Comment by boeotian** [comment]
> Probably for the same reasons go cares about it. Faster build times means more iterations, especially for larger codebases when used with CI/CD pipeline. 

Read the entire post.

**Comment by boeotian** [comment]
> Probably for the same reasons go cares about it. Faster build times means more iterations, especially for larger codebases when used with CI/CD pipeline.

Isn't golang known for being the extreme

**Comment by boeotian** [comment]
Didn't mean to close whoops.

**Comment by medvednikov** [comment]
> Side-note: Get a better benchmark.

There's no benchmark right now.

I don't even know how to answer this question. You don't think spending hours to build software is a problem? :)
