### ISSUE TITLE
Failed on building vls

### ISSUE THREAD

**Issue by ChAoSUnItY** [vlang/v#10362]
![image](https://user-images.githubusercontent.com/43753315/120913380-6dee6c00-c6c9-11eb-9d42-1bd872a6c668.png)

OS: windows, Microsoft Windows 10 Home v19042 64-bit
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
CC version: Error: exec failed (CreateProcess) with code 2: 系統找不到指定的檔案。
 cmd: cc --version

getwd: C:\Users\KYLE\OneDrive\Desktop\github\vls
vmodules: C:\Users\KYLE\.vmodules
vroot: C:\Users\KYLE\OneDrive\Desktop\github\v
vexe: C:\Users\KYLE\OneDrive\Desktop\github\v\v.exe
vexe mtime: 2021-06-06 05:15:08
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 aea93c3

Git version: git version 2.28.0.windows.1
Git vroot status: weekly.2021.22-45-gaea93c3a-dirty
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 40cb2ddb

**Comment by JalonSolov** [comment]
Which version of gcc do you have?  I recommend getting the latest version from https://winlibs.com/ if you don't have it.

**Comment by ChAoSUnItY** [comment]
![image](https://user-images.githubusercontent.com/43753315/121109295-d9f1e100-c83d-11eb-8e89-71d802974450.png)
This happened after manually update to GCC 11.1.0.

**Comment by spaceface777** [comment]
Try `v wipe-cache`.

**Comment by ChAoSUnItY** [comment]
After `v wipe-cache`, it's now working properly, thx
