### ISSUE TITLE
Windows socket implementation

### ISSUE THREAD

**Issue by vegax87** [vlang/v#1036]
**V version: 0.1.12** 
**OS: Windows 10 build 1903** 
**VRoot: C:\v\**

**What did you do?**
I tried to compile this code with the command: **v.exe -o webserver.exe webserver.v**

`import net

fn main() {
    server := net.listen(8080)
    response := 'HTTP/1.1 200 OK\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\nHello World\r\n'

    for {
        connection := server.accept()
        connection.recv(1024)
        connection.send(response.str, response.len)
        connection.close()
    }
}`

**What did you expect to see?**
The compiler should compile it without any issue
 
**What did you see instead?**
I see missing header files in Windows' home directory such as:

C:\Users\Marco//.vlang//webserver.exe.c:76:10: fatal error: sys/socket.h: No such file or directory
 #include <sys/socket.h>
          ^~~~~~~~~~~~~~

**Comment by aguspiza** [comment]
There is no implementation for socket in windows yet
