### ISSUE TITLE
Error on Generic Struct

### ISSUE THREAD

**Issue by salimicali** [vlang/v#10373]
OS: linux, Ubuntu 20.04.2 LTS
Processor: 2 cpus, 64bit, little endian, Intel(R) Pentium(R) CPU G620 @ 2.60GHz
CC version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

vexe mtime: 2021-05-31 17:31:21
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 90292ce

Git version: git version 2.25.1
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false
thirdparty/tcc status: thirdparty-linux-amd64 7543de81

```
struct Node<T> {
	val  T
	name string
}

pub fn (x Node) str()string{
	return 'Value is : ${u16(x.val)}\nName is : ${x.name}'
}
fn main() {
	xx := Node<u16>{
		val: u16(11)
		name: 'man'
	}
	println(xx)
}

```

error on Generic Struct

builder error: 
==================
C error. This should never happen.

**Comment by yuyi98** [comment]
Generic method's receiver type should add parameter, e.g. Node<T>.

```vlang
struct Node<T> {
	val  T
	name string
}

pub fn (x Node<T>) str()string{
	return 'Value is : ${u16(x.val)}\nName is : ${x.name}'
}

fn main() {
	xx := Node<u16>{
		val: u16(11)
		name: 'man'
	}
	println(xx)
}

PS D:\Test\v\tt1> v run .
Node<u16>{
    val: 11
    name: 'man'
}
```
