### ISSUE TITLE
match: nested inline in expression / error: cannot match `X` with `y` condition / error: match must be exhaustive (add `else {}` at the end)

### ISSUE THREAD

**Issue by aheissenberger** [vlang/v#10372]
OS: macos, macOS, 11.4, 20F71
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
CC version: Apple clang version 12.0.5 (clang-1205.0.22.9)

getwd: /Users/ah/SVN-Checkouts/TST/vlang-test
vmodules: /Users/ah/.vmodules
vroot: /usr/local/Cellar/vlang/0.2.2/libexec
vexe: /usr/local/Cellar/vlang/0.2.2/libexec/v
vexe mtime: 2021-06-06 21:30:18
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 f4486d7.114c382

Git version: git version 2.31.1
Git vroot status: weekly.2021.22-52-g114c382c
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 689c8a02

**What did you do?**

Use match function nested  with a sum type which shares the type `Empty{}`.
When I replace `Empty { false }` with `else {false}` the problem goes away.

**What did you expect to see?**

No error 

**What did you see instead?**

```
v run types-match3.v
types-match3.v:16:5: error: cannot match `Empty` with `int` condition
   14 |             match b.x {
   15 |                 int { a.x == b.x }
   16 |                 Empty { false }
      |                 ~~~~~
   17 |             }
   18 |         }
types-match3.v:14:4: error: match must be exhaustive (add `else {}` at the end)
   12 |     res := !(match a.x {
   13 |         int {
   14 |             match b.x {
      |             ~~~~~~~~~~~
   15 |                 int { a.x == b.x }
   16 |                 Empty { false }
```

broken file `types-match3.v`
```v
struct Empty {}

type SumTypeA = Empty | int
type SumTypeB = Empty | string

struct DataStruct {
	x SumTypeA
	y SumTypeB
}

fn isok(a DataStruct, b DataStruct) bool {
	res := !(match a.x {
		int {
			match b.x {
				int { a.x == b.x }
				Empty { false }
			}
		}
		Empty {
			false
		}
	})
	return res
}

a := DataStruct{
	x: 1
	y: Empty{}
}
b := DataStruct{
	x: Empty{}
	y: 'da'
}
res := isok(a, b)

dump(res)

```

working file with `Empty { false }` replaced with `else {false}`:

```v
fn isok(a DataStruct, b DataStruct) bool {
	res := !(match a.x {
		int {
			match b.x {
				int { a.x == b.x }
				else { false }
			}
		}
		Empty {
			false
		}
	})
	return res
}
```

**Comment by aheissenberger** [comment]
Ahhrg :-( what ever I try - any kind of hirachical usage of smar casting is broken:
```v
=== error: `is` can only be used with interfaces and sum types
if mapping_a.source_position is SourcePosition {
		if mapping_b.source_position is SourcePosition {
                    
			xxxxx
	}
}
```

**Comment by aheissenberger** [comment]
or multiple type tests in one line
```v
error: field `source_column` does not exist or have the same type in all sumtype variants
if mapping_a.source_position is SourcePosition && mapping_b.source_position is SourcePosition {
			if !(mapping_a.source_position.source_line != mapping_b.source_position.source_line
				|| mapping_a.source_position.source_column != mapping_b.source_position.source_column) {
				return false
			}
		
	}``

**Comment by spytheman** [comment]
> === error: `is` can only be used with interfaces and sum types
> if mapping_a.source_position is SourcePosition {

What is `source_position` in this context? Please provide a full example.

**Comment by aheissenberger** [comment]
@spytheman I will create new issues with working examples failing
