### ISSUE TITLE
+ HTTP/3 support

### ISSUE THREAD

**Issue by tomByrer** [vlang/v#10387]
Backed by UDP/Quic, is thought of being more secure than HTTP/* & even faster.  Could also save RAM & CPU due to fewer ACK round trips.
[Browser support](https://caniuse.com/http3) is very high, with only Safari not automatically turned on, but still available for testing & power-users behind a flag.

Some research for HTTP/3 in [JustJS is here](https://github.com/just-js/just/issues/14).

**Comment by bstnbuck** [comment]
Hi, I think both http2 and http3 are planned and will be implemented earlier or later.
Both http2 and QUIC (which is needed  for http3) need TLS encryption (QUIC only uses TLS 1.3). Since TLS is not yet implemented in V, such an implementation cannot be thought of. 
Reference: #2066, #10386

**Comment by tomByrer** [comment]
TY for the insights.
Ref 2066 is tagged "Status: After 1.0".  Which means in about 8 years?  (Just getting to v0.2 took much longer than promised.)
I can't wait that long.

**Comment by dumblob** [comment]
@tomByrer just use https://github.com/h2o/h2o as a [library](https://github.com/h2o/h2o/issues/2611 ) from *V* and you should be good to go right now.

**Comment by tomByrer** [comment]
Oh wow thanks @dumblob!  Nice find & good advice.
