### ISSUE TITLE
sumtype, map: compile error when setting sumtype property to default value

### ISSUE THREAD

**Issue by kjlaw89** [vlang/v#10388]
**V version:** V 0.2.2 9a57683.d2bc9ee
**OS:** windows, Microsoft Windows 10 Home v19042 64-bit

I ran into an error with sumtypes and maps with the following code. If the default value for `parent` is removed (so not explicitly set to `T1Empty{}` then everything will compile.

Sample:
```
module main

type T1OrEmpty = T1Empty | T1

struct T1Empty {}

struct T1 {
	id      string     = "ABC123"
	parent  T1OrEmpty  = T1Empty{}  // this default value being set causes the map set to compile-error
}

fn main() {
	t1 := T1{}
	
	mut m := map[string]T1
	m[t1.id] = t1
}
```

Error:
```
C:/Users/.../AppData/Local/Temp/v/sumtype_map_bug.8517207324511055527.tmp.c:10267: error: cannot convert 'struct main__T1Empty' to 'struct main__T1Empty *'
```

**Comment by danieldaeschle** [comment]
Initializing a sum type should be forbidden. also it should be required to initialize the field manually like with interfaces. @medvednikov What do you think?

**Comment by medvednikov** [comment]
@danieldaeschle I agree with both.

**Comment by danieldaeschle** [comment]
`SumTyoe{}` should not work. A cast with the default value should work: `SumType(Default{})`

**Comment by kahsa** [comment]
No error now.
Can be closed.
