### ISSUE TITLE
struct: make [required] the default

### ISSUE THREAD

**Issue by charliemikels** [vlang/v#10383]
I was messing around with structs the other day and I encountered something that I felt went against V's general philosophy.
```V
struct Person {
  first string
  last  string
}

println(Person{ first: 'Fred' })
```

Currently on version V 0.2.2 da88235.3c56532, the above code runs fine and outputs:
```
Person{
    first: 'Fred'
    last: ''
}
```

This surprised me. 
One of V's "things" is that it has no nulls or undefineds. Every normal variable must be initialized. However I never initialized `last` when I created the instance, nor did I give `last` a default value in the definition. I expected an error, but instead it compiled fine and automatically zeroed `last` to `''`. This felt inconsistent since many elements of V are set up to prevent the compiler from guessing what you mean. (eg: Variable := declaration require a value on the other end, and functions that return options must have an `or` block.)

Additionally, V structs already have a `[required]` attribute that enforces this behavior I'm expecting, but I think there's still a problem with that keyword. Many of V's other keywords, like `mut`, `[unsafe]`, and `[manualfree]`, tell the compiler to be less strict. But `[required]` does the opposite and tells the compiler to be *more* strict. 

So, since the automatic zeroing felt inconsistent with normal variable behavior, and since `[required]`'s behavior contrasts with other V keywords, I'd like to make this suggestion:
* Apply the `[required]` attribute by default. (Unless a default value exists, then don't bother)
* Remove the `[required]` attribute.
* Add a `[not_required]` attribute.
  * However this last one is a bit redundant. If `[not_required]` is just going to zero the value anyways, I might as well type ` = 0` or ` = ''` instead.

I think this change would improve the language's consistency while also making code more predictable and understandable, without making it overly verbose. That said, **I am very much not a language architect.** So if there's a good reason for this current behavior, I'd definitely like to hear it out.

> ~~Side note: Technically you could say I *did* initialize the zeroed value when I declared `last` as type `string`, giving it an implied default value. If this is intended behavior, I think the documentation should be updated to better communicate this. A little reminder like, "Struct fields will zero out when if are not initialized," would be helpful.~~
> I'm blind. [It's already in the docs.](https://github.com/vlang/v/blob/master/doc/docs.md#default-field-values)

**Comment by JalonSolov** [comment]
Yes, all variables, struct fields, etc. are zeroed (`0` for integers, `0.0` for floats, `''` for strings, `false` for bools, etc.) if you do not explicitly initialize them.

The docs do say `All struct fields are zeroed by default during the creation of the struct. Array and map fields are allocated.` under `Default field values`.  How much more explicit does it need to be?

**Comment by charliemikels** [comment]
How did I miss that? It was right above the "required" attribute.

Ok I apologize for the docs thing, but I'd still like to discuss the default-ness of `[required]`.

**Comment by JalonSolov** [comment]
The problem with making every field required is that you then have to explicitly initialize them every time.  The simple example of is no big deal.  The problem is when you have a struct with 20... 30... 50... or more fields, and you only need to initialize 1 or 2 to something other than "zero".  That's a _lot_ of extra typing for no useful purpose.
```v
my_struct := Struct{0, 0, '', false, 0, 0, '', '', '', '', false, false, false, my_non_zero_value, 0, 0, 0, 0, 0, 0, 0, 0... ad nauseum}
```

**Comment by charliemikels** [comment]
More specifically, I was suggesting to require an initialization if there was not a default provided by the developer. So something like this:
```V
struct Person {
  first string
  last  string = ''
}
println(Person{ first: 'Fred' })
```
would compile fine, even though in this case `last` is still not given, but since I've given a default value, the compiler knows what to do when I give it nothing. 

That said, the compiler today already knows "what to do" when it zeros the values for me. But it is not stated in the code itself, so later developers have to know this shorthand. Which understandably isn't hard at all, but I wondered if we could improve legibility without needing the docs.

**Comment by JalonSolov** [comment]
What do you think would "improve understandability"?

Yes, it would be explicit to add `= <something>` to every field in the structure definition, but it's simply not necessary, since the docs do state what will happen if you don't have that.  It would also look very cluttered, and it not required by any other language I've used.

Sure, in some of those other languages, this can lead to weird uninitialized value problems... take C for instance, where they're uninitialized unless you explicit initialize... except when you run the code in the debugger, which zeros everything when you start.

V doesn't have that problem, because the compiler makes sure everything is zeroed before you start.

**Comment by charliemikels** [comment]
I think ultimately I was trying to make building structs closer to how you build normal variables. I can't just say `my_int int`, I have to say `my_int := 0` and I always have to give an initial value.

**Comment by JalonSolov** [comment]
I understand.  The difference is that structs are just descriptions of container for other items.  The container doesn't exist until you instantiate an instance of it, at which point it initializes the values _in that instance_.

**Comment by charliemikels** [comment]
I guess that makes sense. I still feel odd about 'leaving' a field empty and simply letting the compiler, in a way, choosing the end value for me, even if it's predictable. 

Side comment: I just found that if the field in question is an interface, and I leave it empty, V crashes with an invalid memory access error. But that'll have to be a different bug report.

**Comment by JalonSolov** [comment]
Yes, it shouldn't crash, it should tell you it couldn't initialize something that doesn't _have_ a "zero" value.

**Comment by charliemikels** [comment]
Yeah...
I think I'll get a solid example of it and then submit a bug report in a bit (if there isn't one already).
In the meantime, I think I get structs and their reasoning a little better now, so I'm going to close this feature request.
