### ISSUE TITLE
json string interpolation c error

### ISSUE THREAD

**Issue by treffner** [vlang/v#10390]
v doctor
OS: linux, Pop!_OS 20.04 LTS
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
CC version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

getwd: /home/acf/a/dev
vmodules: /home/acf/.vmodules
vroot: /home/acf/a/v
vexe: /home/acf/a/v/v
vexe mtime: 2021-06-08 07:05:36
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 5b8402b.d2bc9ee

Git version: git version 2.25.1
Git vroot status: weekly.2021.23-15-gd2bc9ee7
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81

**What did you do?**
Used json string interpolation which worked fine some days/weeks ago.
```v
import json
a := 'a'
println('${json.encode(a)}')
```

**What did you expect to see?**
V run output "a".
 
**What did you see instead?**
V run output a C error:

```
v -cg run j.v
/tmp/v/j.16694677875240254469.tmp.c:10385: error: '}' expected (got ";")
builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by billpcs** [comment]
This is fixed with latest master (V 0.2.2 1e255d3.69f31d8) :heavy_check_mark:
