### ISSUE TITLE
Downloading pdf file from link creates empty file

### ISSUE THREAD

**Issue by thothloki** [vlang/v#10402]
**V version: 0.2.2**
**OS: Linux Mint and Windows 10** 

**What did you do?**
Trying to download pdf files from a few web pages. I am able to download one file from the same site, but the next one comes in as an empty pdf. both are viewable if you click on it

https://www.janusfiresystems.com/downloads/PDF/DS1003_Mv_Series_FM-200_System.pdf downloads fine
https://www.janusfiresystems.com/downloads/PDF/DS1002_Lv%20Series_FM-200_System.pdf does not

method:
`
http.download_file(input, out) or {
 	println('ERROR downloading: ${err.msg}')
        continue
}`

**Comment by JalonSolov** [comment]
Clicking the links in a browser works fine.

I tried a _very_ simple test...
```v
import net.http

http.download_file('https://www.janusfiresystems.com/downloads/PDF/DS1003_Mv_Series_FM-200_System.pdf', '1.pdf') or { println('ERROR downloading: ${err.msg}') }
http.download_file('https://www.janusfiresystems.com/downloads/PDF/DS1002_Lv%20Series_FM-200_System.pdf', '2.pdf') or { println('ERROR downloading: ${err.msg}') }
```
and the first one downloaded fine.  The 2nd, however, only wrote a 226 byte file, so I looked at it...
```
jalon@Ripper:~/testing$ cat 2.pdf
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
jalon@Ripper:~/testing$
```
Bad request?  Exact same request as the first, or at least that's how it appears...

**Comment by medvednikov** [comment]
I suspect it could be due to `%20` in the URL.

Using a space doesn't work either.

**Comment by JalonSolov** [comment]
Right.  I tried both ways.  The `%20` is just the "URL-safe" way to do a space.

**Comment by JalonSolov** [comment]
Oh, and I did get the "Bad request" whether I used space or `%20`.

**Comment by thothloki** [comment]
i tried to replace the `%20` with a space and with an underscore to match the first link
just doing that manually, I get a 404 on the site.

**Comment by JalonSolov** [comment]
Yeah... click on the link you have above to bring it up in a browser and it works fine.  When you see the link in the browser, it is definitely a space, so either space or `%20` _should_ work in the code... but neither one does.

**Comment by thothloki** [comment]
out of curiosity.
Could it be a http vs https thing?

**Comment by shadowninja55** [comment]
tested it against python's `requests.get`; works in python, doesn't work with v's `net.http.get`.

**Comment by thothloki** [comment]
> tested it against python's `requests.get`; works in python, doesn't work with v's `net.http.get`.

I did the same thing. My original script was in python. The issue I had with python is that I would get random failure to downloads. And every time I ran the py script, a different pdf would fail and it was not consistent. I will say, at lease V is being consistent in the files that are not downloading. I have just under 400 links I loop through, so if I know which ones are bad, I can easily go and manually fix it. For my python script, i would have to go through all of the folders and files to see if one got missed.

**Comment by JalonSolov** [comment]
> 
> 
> out of curiosity.
> Could it be a http vs https thing?

Have you checked on which ones failed?  If all the failing ones are https, that would be a big clue.

**Comment by thothloki** [comment]
> > out of curiosity.
> > Could it be a http vs https thing?
> 
> Have you checked on which ones failed? If all the failing ones are https, that would be a big clue.

95% of the links are https. as shown with the two links i provided, both are https but one fails and the other doesnt.
i personally do not see a correlation with http vs https, but i could be wrong

**Comment by shadowninja55** [comment]
> > out of curiosity.
> > Could it be a http vs https thing?
> 
> Have you checked on which ones failed? If all the failing ones are https, that would be a big clue.

this doesn't seem like http vs https to be honest, moreso the %20 in the link. i tried with http and the same issue happened.

**Comment by thothloki** [comment]
Here are a few more examples:
WORKS
https://www.securityandfire.honeywell.com/notifier/en-us/-/media/Files/Notifier/Data-Sheets/DN_60726_pdf.pdf
https://www.securityandfire.honeywell.com/notifier/en-us/-/media/Files/Notifier/Data-Sheets/DN_7060_pdf.pdf

DON'T WORK
https://www.securityandfire.honeywell.com/en/-/media//Files/Notifier/Data%20Sheets/DN_6861_pdf
https://www.securityandfire.honeywell.com/-/media//Files/Notifier/Data%20Sheets/DN_60535_pdf


so I think you guys are onto something with the %20

**Comment by thothloki** [comment]
same issue when i replaced the %20 with a space

**Comment by medvednikov** [comment]
we need an HTTP expert who knows how spaces in urls should be handled :)

**Comment by thothloki** [comment]
agreed

**Comment by shadowninja55** [comment]
maybe the issue is we're not using `application/x-www-form-urlencoded`? (or are we?) as far as i know that's required for %20 to work

**Comment by shadowninja55** [comment]
looks like we use `+` after a GET query with the `application/x-www-form-urlencoded` content-type. otherwise, %20 is valid and in this case %20 should work. ill try manually setting the content-type.

**Comment by JalonSolov** [comment]
`application/x-www-form-urlencoded` is what you set in your Content-Type header to tell the server side that the body of your POST is not binary.  If you're sending binary data, use `multipart/form-data` instead.

However, neither one of these applies.  It is just a URL, with no parameters, and the %20 _is_ the correct thing to send in place of a space.  It's also not a POST, it's a simple GET.

**Comment by shadowninja55** [comment]
> `application/x-www-form-urlencoded` is what you set in your Content-Type header to tell the server side that the body of your POST is not binary. If you're sending binary data, use `multipart/form-data` instead.
> 
> However, neither one of these applies. It is just a URL, with no parameters, and the %20 _is_ the correct thing to send in place of a space. It's also not a POST, it's a simple GET.
> 
> What I would like to see is both the REQUEST and RESPONSE headers for a failing request.
> 
> (Yes, I might know a couple things about HTML, having had to debug issues with sites I maintain...)

i also tried `application/pdf`, which is what curl did, so i really doubt it's that. let me compare the headers good idea

**Comment by JalonSolov** [comment]
`application/pdf` is what you the server should be sending you in the Content-Type header.

**Comment by shadowninja55** [comment]
> `application/pdf` is what you the server should be sending you in the Content-Type header.

i was just about to reply with that lol, but yep you're right. i'll do the comparison now

**Comment by shadowninja55** [comment]
i tried doing a get to https://www.google.com/search?q=vlang%20github and it actually seemed to work (200). perhaps this is an issue more specific than just %20. but if python and curl work then it's an issue nonetheless

**Comment by shadowninja55** [comment]
https://vlang.io/%20 works but https://www.janusfiresystems.com/downloads/PDF/DS1002_Lv%20Series_FM-200_System.pdf doesn't. seems like a specific case with this site and %20 that other libraries somehow avoid.

**Comment by JalonSolov** [comment]
You get the same failure if you use a space or %20, so it's not the %20.

**Comment by shadowninja55** [comment]
> You get the same failure if you use a space or %20, so it's not the %20.
> 
> Do you have the REQUEST/RESPONSE headers from any of these?

i've tried with 0 request headers and it makes no difference, i have the response headers but they really didn't tell anything important

**Comment by JalonSolov** [comment]
Did you try comparing REQUEST header for a successful attempt vs a failed one, and same with RESPONSE headers?

If you can tell me how to see the headers, I can do that here and won't have to keep asking.  :-)

**Comment by shadowninja55** [comment]
> Did you try comparing REQUEST header for a successful attempt vs a failed one, and same with RESPONSE headers?
> 
> If you can tell me how to see the headers, I can do that here and won't have to keep asking. :-)

i manually used `new_request` which afaik has no headers, and it still worked on one and failed on the other

**Comment by JalonSolov** [comment]
Found it!  Now I just have to figure out how to fix it.

The problem is with spaces, all the way, whether you use ' ' or `%20`.

Deep down in the recesses of the code, the `%20` is getting converted to a space before the low-level GET command is sent to the host, but those low-level commands _must_ have the `%20` because it is sent on one line with other space-separated data.

I proved this with a hack... at the bottom of `net/http/request.v`, function `build_request_headers`, I replaced
```v
	return '$method $path $version\r\n' + uheaders.join('') + 'Connection: close\r\n\r\n' + req.data
```
with
```v
	tmp_path := path.replace(' ', '%20')
	return '$method $tmp_path $version\r\n' + uheaders.join('') + 'Connection: close\r\n\r\n' + req.data
```
The difference it makes is:

DOES NOT WORK:
```
> GET /downloads/PDF/DS1002_Lv Series_FM-200_System.pdf HTTP/1.1
```
WORK:
```
> GET /downloads/PDF/DS1002_Lv%20Series_FM-200_System.pdf HTTP/1.1
```
I found out how to get that output... you can add `-d trace_http_request` to see exactly what is sent to the server.

**Comment by spytheman** [comment]
Yes, there are `-d trace_http_request -d trace_http_response` . Sorry, I just read this thread :-| .
