### ISSUE TITLE
mutable iterator of an array of pointers generates bad code

### ISSUE THREAD

**Issue by donpdonp** [vlang/v#10416]
should a mutable iterator of a ptr type be itself a pointer, resulting in a double indirection?

```v
struct Thing {}

struct Bag {
pub mut:
	things []&Thing
}

pub fn main() {
	mut bag := &Bag{}
	bag.things << &Thing{}
	for mut thing in bag.things {
		println(thing) // comment this out to fix
		mut fixed_thing := *thing
		println(fixed_thing)
	}

}
```

```
/tmp/v/for_arr_ptrs.9169643072667496287.tmp.c:10245: error: cannot convert 'struct main__Thing *' to 'struct main__Thing'

        // FOR IN array
        for (int _t742 = 0; _t742 < bag->things.len; ++_t742) {
                main__Thing** thing = ((main__Thing**)bag->things.data) + _t742;
10245:     println(main__Thing_str(*thing));
                main__Thing* fixed_thing = *thing;
                println(str_intp(1, _MOV((StrIntpData[]){{_SLIT("&"), 0xfe10 ,{.d_s=main__Thing_str(*fixed_thing)}}})));
        }

```

$ v doctor
OS: linux, Ubuntu 21.04
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
CC version: cc (Ubuntu 10.3.0-1ubuntu1) 10.3.0

getwd: /home/donp/projects/vbridge
vmodules: /home/donp/.vmodules
vroot: /opt/v/latest
vexe: /opt/v/latest/v
vexe mtime: 2021-06-10 22:38:54
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 7878bad

Git version: git version 2.31.1
Git vroot status: weekly.2021.17-423-g7878bad9
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81

**Comment by shadowninja55** [comment]
yes, it would be a double pointer. when you iterate with `mut foo` of type `T` then foo is `&T`.

**Comment by donpdonp** [comment]
I can see that the implementation of `mut` is to use a ptr. I'd call it an implementation detail that it works that way. In this case, my sense is that the implementation should not use a ptr but the value directly.

**Comment by felipensp** [comment]
This issue has been already fixed. Thanks.
