### ISSUE TITLE
Any command does not work

### ISSUE THREAD

**Issue by Poulpinounette** [vlang/v#10433]
** I can"t do any command. **

**V version:**  V 0.2.2 652e7ba
**OS:** Windows 10 
![image](https://user-images.githubusercontent.com/17411508/121772109-b7c8cd80-cb73-11eb-9d35-5798b9388e2c.png)

**What did you do?**
Simple install.
outpot log :
```
Updating TCC
 > Syncing TCC from https://github.com/vlang/tccbin

Updating vc...
 > Sync with remote https://github.com/vlang/vc

Building V...
 > Attempting to build v_win.c with TCC
 > Compiling with .\v.exe self
 > Clang not found
 > GCC not found
 > Attempting to build v_win.c with MSVC
 > Compiling with .\v.exe self
 > V built successfully
 > To add V to your PATH, run `.\v.exe symlink`.

V version: V 0.2.2 652e7ba
```
and try this code:
```
fn main() {
	areas := ["game", "caca"]

	for area in areas {
		println(area)
	}
}
```

**What did you expect to see?**
A println

 
**What did you see instead?**

```
PS C:\Users\jspqm\Documents\dev\v\try> v -cg .\src\index.v
C:/Users/jspqm/AppData/Local/Temp/v/index.2540502186768392741.tmp.c:401: warning: WINVER redefined
C:/Users/jspqm/AppData/Local/Temp/v/index.2540502186768392741.tmp.c:1812: warning: implicit declaration of function 'array_repeat_to_depth'
C:/Users/jspqm/AppData/Local/Temp/v/index.2540502186768392741.tmp.c:1812: error: '{' expected (got ";")
builder error:
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

PS C:\Users\jspqm\Documents\dev\v\try> v -g .\src\index.v
C:/Users/jspqm/AppData/Local/Temp/v/index.4542346521849931528.tmp.c:401: warning: WINVER redefined
C:/Users/jspqm/AppData/Local/Temp/v/index.4542346521849931528.tmp.c:1812: warning: implicit declaration of function 'array_repeat_to_depth'
C:/Users/jspqm/AppData/Local/Temp/v/index.4542346521849931528.tmp.c:1812: error: '{' expected (got ";")
builder error:
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose
```

**Comment by Gladear** [comment]
It looks like you're V version was too far behind before you updated. Can you try running `make.bat` ?

**Comment by Poulpinounette** [comment]
> My mistake, I misunderstood, it was a fresh clone, right ?

Yep

**Comment by JalonSolov** [comment]
You didn't show your command line/options, but from the output we see it was using MSVC compiler.  First, we need to know why it didn't try TCC (which is installed with V).

2nd, as an alternative, you can install the latest version of GCC from https://winlibs.com/ which I know works (it's what I have).

3rd, we do need to figure out why it isn't working with MSVC, but that will require someone who has MSVC on the V team... not many.  :-\

**Comment by Poulpinounette** [comment]
> You didn't show your command line/options, but from the output we see it was using MSVC compiler. First, we need to know why it didn't try TCC (which is installed with V).
> 
> 2nd, as an alternative, you can install the latest version of GCC from https://winlibs.com/ which I know works (it's what I have).
> 
> 3rd, we do need to figure out why it isn't working with MSVC, but that will require someone who has MSVC on the V team... not many. :-\

Thanks, work by a gcc compiler and clear folder and make a fresh clone with `V version: V 0.2.2 dc1c882`
