### ISSUE TITLE
time.infinite divided by anything should be time.infinite

### ISSUE THREAD

**Issue by mcastorina** [vlang/v#10446]
**V version:** V 0.2.2 3b60458
**OS:** linux

**What did you do?**
```v
time.infinite / time.millisecond
```

**What did you expect to see?**
```
time.infinite
```
 
**What did you see instead?**
```
0
```

**Comment by shadowninja55** [comment]
i'll add some overloads

**Comment by UweKrueger** [comment]
This is an interesting topic and it's not trivial. When you look at `time.infinite` and `time.millisecond` they are both of type `time.Duration`. Now if you divide two durations in real life say _a_ = 5s and _b_ = 100ms:

![formula](https://render.githubusercontent.com/render/math?math=\displaystyle{}x=\frac{a}{b}=\frac{5\\,\mathrm{s}}{100\\,\mathrm{ms}}=\frac{5000\\,\mathrm{ms}}{100\\,\mathrm{ms}}=\frac{5000}{100}=50)

you get _x_ = 50 &ndash; without unit. So the result of dividing two durations is a plain number. And here is the problem: - there is no notation of "infinite" for `int`.

I could imagine an overloaded `/` operator that returns an `f64` &ndash; which could have the value `inf` &ndash; and this is probably the best solution for high-level problems. Actually I've often written
`duration_in_ms :=  f64(sw.elapsed()) / f64(time.millisecond)`
This would become much easier with an overloaded `/` operator that returns an `f64` &ndash; and checks for the numerator being `time.infinite`.

That said there are a lot of Windows functions like `WaitForSingleObject()` that accept an `u32` as timeout with the special value `u32(-1)` as infinite. But this is operating system specific.

My personal favorite would be the following:
- There is already a method `Duration.milliseconds()`. This could be modified to return `-1` if the duration is `-1`. It could then be used for the calculation of Windows timeout parameters, like this:
  `res = C.WaitForSingleObject(handle, u32(timeout.milliseconds()))`
- The `/` operator could be overloaded to return an `f64` that becomes `inf` in this case. This could be used like this:
  `println('The benchmark test took ${sw.elapsed() / time.second:.3f}s.')`

**Comment by UweKrueger** [comment]
There is another point to consider. In V's current `time` module an "infinite" duration is represented as the smallest possible negative number `-1`. That is not really a good choice. Windows timeout values use `u32(-1)` which is `0xffffffff` and the highest positive(!) value that can be represented within the data type.

Using signed values for durations can however make sense for calculations &ndash; since then negative durations can be represented (e.g. for  intermediate results). But this possibility is obstructed by the fact that `time.Duration(-1)` is reserved for infinite.

So another approach could be to define:

```v
// in vlib/time.v

pub const {
    ...
    infinite = Duration(C.INT64_MAX)
}

// and this perhaps exclusively in `time_windows.c.v`:

pub fn (d Duration) sys_milliseconds() u32 {
    if d >= u32(-1) * time.millisecond { // treat 4294967295000000 .. C.INT64_MAX as "infinite"
        return u32(-1)
    } else if d < 0 {
        return 0 // treat negative timeouts as 0 - consistent with Unix behaviour
    } else {
        return u32(d / time.millisecond)
    }
}
```
Then a Windows function could be called like:
`res = C.WaitForSingleObject(handle, timeout.sys_milliseconds())`

**Comment by UweKrueger** [comment]
It turns out that on Unix systems there are functions that accept a timeout in milliseconds, too (`poll()`, `epoll_wait()`). But in this case it's a *signed* `int`. So for these systems a similar function could be placed in `vlib/time/time_nix.c.v`:
```v
pub fn (d Duration) sys_milliseconds() int {
    if d > C.INT_MAX * time.millisecond { // treat 2147483647000001 .. C.INT64_MAX as "infinite"
        return -1
    } else if d <= 0 {
        return 0 // treat negative timeouts as 0 - consistent with Unix behaviour
    } else {
        return int(d / time.millisecond)
    }
}
```

**Comment by JalonSolov** [comment]
The `-1` value was likely chosen because it is logically impossible to have either a negative timeout or a negative duration.  Those would only be possible with time travel, which isn't possible with consumer level equipment.  I make no claims either way about secret government labs.  ;-)

**Comment by shadowninja55** [comment]
i've unassigned myself because overloading an i64 alias does not seem to be working currently and i don't know how else to fix this.
