### ISSUE TITLE
os.read_lines function lost the last character

### ISSUE THREAD

**Issue by kinnergit** [vlang/v#1044]
**V version:*0.1.12* 
**OS:*Mac 10.14.5* 

**What did you do?**
read lines from file for this code: 

// main.v
```
module main
import os

fn main()
{
    filename := 'hello.txt'

    lines := os.read_lines(filename)

    mut i:=1
    for line in lines {
        println(i.str() + ': $line')
        i++
    }
}
```

// hello.txt (Only two lines)
hello kinner!
This is a test file

**What did you expect to see?**
1: hello kinner!
2: This is a test file
 
**What did you see instead?**
1: hello kinner!
2: This is a test fil

**Comment by medvednikov** [comment]
Fixed.
