### ISSUE TITLE
net.AddrFamily not found

### ISSUE THREAD

**Issue by khalyomede** [vlang/v#10448]
**V version:** V 0.2.2 9924f6c
**OS:** linux, Linux version 5.4.72-microsoft-standard-WSL2 (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Oct 28 23:40:43 UTC 2020 (WSL 2)

**What did you do?**

Tried to run this code

```v
import net { AddrFamily }

fn main() {
  print(AddrFamily.ip6)
}
```

**What did you expect to see?**

Something printed on console.
 
**What did you see instead?**

```bash
V panic: new_type: idx must be between 1 & 65535
v hash: 9924f6c
C.backtrace returned less than 2 frames
```

**Notes**

net.AddrFamily vlib documentation: https://modules.vlang.io/net.html#AddrFamily

**Comment by JalonSolov** [comment]
`v up` and try again.  Big changes to the `net` module were just pushed.
