### ISSUE TITLE
Not building on rpi

### ISSUE THREAD

**Issue by marhu98** [vlang/v#10449]
When I follow the install instructions on a raspberry pi model 2 b the make command doesn't work:

```
cd ./vc && git clean -xf && git pull --quiet
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -g -std=gnu99 -w -o ./v ./vc/v.c -lm -lpthread 
./v -o v2.exe  cmd/v
vlib/v/parser/fn.v:515:3: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
  513 |     if rec.typ.idx() == 0 {
  514 |         // error is set in parse_type
  515 |         return none
      |         ~~~~~~~~~~~
  516 |     }
  517 |     rec.type_pos = rec.type_pos.extend(p.prev_tok.position())
vlib/v/parser/fn.v:521:3: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
  519 |         p.error_with_pos('use `(mut f Foo)` or `(f &Foo)` instead of `(mut f &Foo)`',
  520 |             lpar_pos.extend(p.tok.position()))
  521 |         return none
      |         ~~~~~~~~~~~
  522 |     }
  523 |     if is_shared {
vlib/v/checker/checker.v:7378:3: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
 7376 |     if typ == 0 {
 7377 |         c.error('unknown type', pos)
 7378 |         return none
      |         ~~~~~~~~~~~
 7379 |     }
 7380 |     sym := c.table.get_type_symbol(typ)
vlib/v/checker/checker.v:7386:5: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
 7384 |                 c.error(util.new_suggestion(sym.name, c.table.known_type_names()).say('unknown type `$sym.name`'),
 7385 |                     pos)
 7386 |                 return none
      |                 ~~~~~~~~~~~
 7387 |             }
 7388 |         }
vlib/v/checker/checker.v:7399:5: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
 7397 |                 }
 7398 |                 c.error(msg, pos)
 7399 |                 return none
      |                 ~~~~~~~~~~~
 7400 |             }
 7401 |         }
vlib/v/builder/cc.v:48:3: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
   46 | fn (mut v Builder) find_win_cc() ? {
   47 |     $if !windows {
   48 |         return none
      |         ~~~~~~~~~~~
   49 |     }
   50 |     ccompiler_version_res := os.execute('$v.pref.ccompiler -v')
vlib/v/builder/cc.v:66:5: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
   64 |                     println('tcc not found')
   65 |                 }
   66 |                 return none
      |                 ~~~~~~~~~~~
   67 |             }
   68 |             v.pref.ccompiler = thirdparty_tcc
make: *** [Makefile:92: all] Error 1
```

And then, when I run something like ```./v``` I get:

```
Welcome to the V REPL (for help with V itself, type `exit`, then run `v help`).
failed    cmd: "/home/pi/v/v" "/home/pi/v/cmd/tools/vrepl.v"
failed   code: 1
V panic: V panic: failed to open file "/tmp/v/vrepl.3428945763072987245.tmp.c"
v hash: 535dcac
C.backtrace returned less than 2 frames

v hash: 535dcac
C.backtrace returned less than 2 frames
```

**Comment by JalonSolov** [comment]
V must be installed in a directory where you have write permissions in order to work.

For the rest, you may not have the most recent version of V.  Try making the directory writable, then run `v up` to let it update to the lastest commit.

**Comment by marhu98** [comment]
I just downloaded v from the repo, so I guess it does have the last version. And I just have the folder write permission. And I got the same error. So it's not that. Also when I run
```
./v up
```
I get: ```
failed    cmd: "/home/pi/v/v"  -g "/home/pi/v/cmd/tools/vup.v"
failed   code: 255
V panic: 00000000 : at ???: RUNTIME ERROR: invalid memory access
/tmp/v/v2.exe.4077236412069661008.tmp.c:3687: by v__checker__Checker_stmt
/tmp/v/v2.exe.4077236412069661008.tmp.c:65131: by v__checker__Checker_check
/tmp/v/v2.exe.4077236412069661008.tmp.c:65194: by v__checker__Checker_check_files
/tmp/v/v2.exe.4077236412069661008.tmp.c:7600: by v__builder__Builder_middle_stages
/tmp/v/v2.exe.4077236412069661008.tmp.c:7618: by v__builder__Builder_front_and_middle_stages
/tmp/v/v2.exe.4077236412069661008.tmp.c:8006: by v__builder__Builder_gen_c
/tmp/v/v2.exe.4077236412069661008.tmp.c:8023: by v__builder__Builder_build_c
/tmp/v/v2.exe.4077236412069661008.tmp.c:8064: by v__builder__Builder_compile_c
/tmp/v/v2.exe.4077236412069661008.tmp.c:8983: by v__builder__compile
/tmp/v/v2.exe.4077236412069661008.tmp.c:9721: by main__main
/tmp/v/v2.exe.4077236412069661008.tmp.c:10495: by main

v hash: 535dcac
/tmp/v/v2.exe.4077236412069661008.tmp.c:15312: at v_panic: Backtrace
/tmp/v/v2.exe.4077236412069661008.tmp.c:21197: by os__execute_or_panic
/tmp/v/v2.exe.4077236412069661008.tmp.c:31739: by v__util__launch_tool
/tmp/v/v2.exe.4077236412069661008.tmp.c:9668: by main__main
/tmp/v/v2.exe.4077236412069661008.tmp.c:10495: by main
````

Running in sudo doesn't help either.

**Comment by JalonSolov** [comment]
@shadowninja55 ^^

**Comment by shadowninja55** [comment]
try running `git pull`, `make CC=gcc`, then try `v up`

**Comment by marhu98** [comment]
Now i get a different error:
```
make fresh_vc
make[1]: Entering directory '/home/pi/v'
rm -rf ./vc
git clone --depth 1 --quiet --single-branch https://github.com/vlang/vc ./vc
make[1]: Leaving directory '/home/pi/v'
cd ./vc && git clean -xf && git pull --quiet
make fresh_tcc
make[1]: Entering directory '/home/pi/v'
rm -rf ./thirdparty/tcc
git clone --depth 1 --quiet --single-branch --branch thirdparty-linux-arm https://github.com/vlang/tccbin ./thirdparty/tcc
make[1]: Leaving directory '/home/pi/v'
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
gcc  -g -std=gnu99 -w -o ./v ./vc/v.c -lm -lpthread 
./v -o v2.exe  cmd/v
V panic: failed to open file "/tmp/v/v2.exe.3937842947606911904.tmp.c"
v hash: 4614876
C.backtrace returned less than 2 frames
make: *** [Makefile:92: all] Error 1
```

However running this before the make command solved it: ```chmod -R 777 /tmp/v```

But `./v up` is still not working:

failed    cmd: "/home/pi/v/v"  -g "/home/pi/v/cmd/tools/vup.v"
failed   code: 255
V panic: 00000000 : at ???: RUNTIME ERROR: invalid memory access
/tmp/v/v2.exe.7509642196466227241.tmp.c:3687: by v__checker__Checker_stmt
/tmp/v/v2.exe.7509642196466227241.tmp.c:65131: by v__checker__Checker_check
/tmp/v/v2.exe.7509642196466227241.tmp.c:65194: by v__checker__Checker_check_files
/tmp/v/v2.exe.7509642196466227241.tmp.c:7600: by v__builder__Builder_middle_stages
/tmp/v/v2.exe.7509642196466227241.tmp.c:7618: by v__builder__Builder_front_and_middle_stages
/tmp/v/v2.exe.7509642196466227241.tmp.c:8006: by v__builder__Builder_gen_c
/tmp/v/v2.exe.7509642196466227241.tmp.c:8023: by v__builder__Builder_build_c
/tmp/v/v2.exe.7509642196466227241.tmp.c:8064: by v__builder__Builder_compile_c
/tmp/v/v2.exe.7509642196466227241.tmp.c:8983: by v__builder__compile
/tmp/v/v2.exe.7509642196466227241.tmp.c:9721: by main__main
/tmp/v/v2.exe.7509642196466227241.tmp.c:10495: by main

v hash: 4614876
/tmp/v/v2.exe.7509642196466227241.tmp.c:15312: at v_panic: Backtrace
/tmp/v/v2.exe.7509642196466227241.tmp.c:21197: by os__execute_or_panic
/tmp/v/v2.exe.7509642196466227241.tmp.c:31739: by v__util__launch_tool
/tmp/v/v2.exe.7509642196466227241.tmp.c:9668: by main__main
/tmp/v/v2.exe.7509642196466227241.tmp.c:10495: by main
pi@raspberrypi:~/v $ ls -al /home/pi/v/cmd/tools/vup.v```
```

Notice I gave the v folder 777 permission to avoid any problem with that.

**Comment by shadowninja55** [comment]
i'm guessing this is because we didn't set gcc as the default c compiler. add `export VFLAGS='-cc gcc'` somewhere to your shell rc, re-source, and then try to `./v up` again

**Comment by marhu98** [comment]
Didn't help

**Comment by shadowninja55** [comment]
does `v -cc gcc self` work?

**Comment by marhu98** [comment]
Same error

**Comment by shadowninja55** [comment]
i'm not sure then, sorry. if you have discord we may be able to provide better help there in the #help channel

**Comment by UweKrueger** [comment]
The problem are these lines (triggered by `make`):
```
gcc  -g -std=gnu99 -w -o ./v ./vc/v.c -lm -lpthread 
./v -o v2.exe  cmd/v
```
The first line compiles the C file with `gcc` which is ok, but the second line creates the new `v2.exe` with `tcc` which creates a non-working executable that is later moved to `./v`...
All `v` executables have to be compiled with `gcc` on this platform.

You can do the following manually:
```
gcc  -g -std=gnu99 -w -o ./v ./vc/v.c -lm -lpthread
./v -cc gcc -o v2.exe cmd/v
mv v2.exe v
./v -cc gcc -o v2.exe cmd/v
mv v2.exe v
```
Alternatively you can set `VFLAGS` *before* calling `make`:
```
uwe@pi:~ $ rm -rf v
uwe@pi:~ $ git clone https://github.com/vlang/v
Cloning into 'v'...
remote: Enumerating objects: 92547, done.
remote: Counting objects: 100% (1392/1392), done.
remote: Compressing objects: 100% (610/610), done.
remote: Total 92547 (delta 844), reused 1261 (delta 776), pack-reused 91155
Receiving objects: 100% (92547/92547), 37.52 MiB | 7.72 MiB/s, done.
Resolving deltas: 100% (66120/66120), done.
uwe@pi:~ $ cd v
uwe@pi:~/v $ export VFLAGS="-cc gcc"
uwe@pi:~/v $ make
make fresh_vc
make[1]: Entering directory '/home/uwe/v'
rm -rf ./vc
git clone --depth 1 --quiet --single-branch https://github.com/vlang/vc ./vc
make[1]: Leaving directory '/home/uwe/v'
cd ./vc && git clean -xf && git pull --quiet
make fresh_tcc
make[1]: Entering directory '/home/uwe/v'
rm -rf ./thirdparty/tcc
git clone --depth 1 --quiet --single-branch --branch thirdparty-linux-arm https://github.com/vlang/tccbin ./thirdparty/tcc
make[1]: Leaving directory '/home/uwe/v'
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -g -std=gnu99 -w -o ./v ./vc/v.c -lm -lpthread 
./v -o v2.exe -cc gcc cmd/v
mv -f v2.exe v  
V has been successfully built
V 0.2.2 9f6ddb4
```

**Comment by marhu98** [comment]
That works! Thanks. However it takes an abnormally long time to run simple commands like v self or v symlink.

**Comment by JalonSolov** [comment]
gcc is a total sloth compared to tcc when compiling.  `v self` will always be slow, because you are asking it to compile every time.  `v symlink` should only be slow the first time, as it has to compile it on first use, but after that it is already compiled and should just run.

**Comment by marhu98** [comment]
Actually, it's still not working: 
```
 sudo ./v up
Updating V...
V self compiling ...
V built successfully!
recompiling vup.v failed:
00000000 : at ???: RUNTIME ERROR: invalid memory access
/tmp/v/v2.14472744380487247153.tmp.c:4068: by v__checker__Checker_stmt
/tmp/v/v2.14472744380487247153.tmp.c:77: by v__checker__Checker_check
/tmp/v/v2.14472744380487247153.tmp.c:140: by v__checker__Checker_check_files
/tmp/v/v2.14472744380487247153.tmp.c:8091: by v__builder__Builder_middle_stages
/tmp/v/v2.14472744380487247153.tmp.c:8109: by v__builder__Builder_front_and_middle_stages
/tmp/v/v2.14472744380487247153.tmp.c:8497: by v__builder__Builder_gen_c
/tmp/v/v2.14472744380487247153.tmp.c:8514: by v__builder__Builder_build_c
/tmp/v/v2.14472744380487247153.tmp.c:8555: by v__builder__Builder_compile_c
/tmp/v/v2.14472744380487247153.tmp.c:9474: by v__builder__compile
/tmp/v/v2.14472744380487247153.tmp.c:10212: by main__main
/tmp/v/v2.14472744380487247153.tmp.c:10984: by main
```

**Comment by UweKrueger** [comment]
> sudo ./v up

Here is the problem. If you do `sudo` all your environment variables are lost. Try this:
```sh
uwe@ryzen:~$ export XYZ=abc
uwe@ryzen:~$ echo $XYZ
abc
uwe@ryzen:~$ sh -c 'echo $XYZ'
abc
uwe@ryzen:~$ sudo sh -c 'echo $XYZ'

```
Only a blank line is printed for the last command.

In principle something like `sudo sh -c 'export VFLAGS="-cc gcc"; some command'` may work &ndash; or `sudo -s` and do anything in the new `root` shell, but I would really not recommend that.
Why are you trying to compile as `root` in the first place? Just compile as normal user. Only `v symlink` requires root rights.

**Comment by marhu98** [comment]
Now everything is alright. Thanks!

**Comment by marhu98** [comment]
Now it's working fine. Thanks!

**Comment by xloem** [comment]
Hey, this issue is closed, but it could be nice to document somewhere that v will crash on rpi unless VFLAGS is set.
