### ISSUE TITLE
Clang not found error.

### ISSUE THREAD

**Issue by 5elenay** [vlang/v#10459]
**V version:** 0.2.2 (5aa7a98)
**OS:** Windows 10 Pro x64

I downloaded v from [here](https://github.com/vlang/v/releases/latest/download/v_windows.zip) and installed mingw-64. When i run make.bat, it gives me error about `c not found`. I already installed gcc and g++, also added to path. But it still raises the same error. Any idea? 

make.bat result:
```ps1
PS C:\V> make.bat
Updating TCC
 > Syncing TCC from https://github.com/vlang/tccbin

Updating vc...
 > Sync with remote https://github.com/vlang/vc

Building V...
 > Attempting to build v_win.c with TCC
 > Compiling with .\v.exe self
 > Clang not found
 > Attempting to build v_win.c with GCC
 > Compiling with .\v.exe self


Exiting from error
ERROR: please follow the instructions in https://github.com/vlang/v/wiki/Installing-a-C-compiler-on-Windows
```
gcc version (path: `C:\mingw-w64\bin`):
```ps1
PS C:\Users\username> gcc --version
gcc.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
and `v up` output:
```ps1
PS C:\Users\username> v up
failed    cmd: "C:\V\v.exe"  -g "C:\V\cmd\tools\vup.v"
failed   code: 1
V panic: C:\V\vlib\v\pref\pref.v:752:2: notice: use `arm64` instead of `aarch64`
  750 |     // }
  751 |     // $if arm64 { // requires new vc
  752 |     $if aarch64 {
      |     ~~~~~~~~~~~
  753 |         return .arm64
  754 |     }
C:/Users/username/AppData/Local/Temp/v/vup.1849059056253904414.tmp.c:474: warning: WINVER redefined
C:/Users/username/AppData/Local/Temp/v/vup.1849059056253904414.tmp.c:3999: warning: implicit declaration of function 'array_repeat_to_depth'
C:/Users/username/AppData/Local/Temp/v/vup.1849059056253904414.tmp.c:3999: error: '{' expected (got ";")
builder error:
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose
You can also use #help on Discord: https://discord.gg/vlang
v hash: 5aa7a98
print_backtrace_skipping_top_frames_mingw is not implemented
```

**Comment by JalonSolov** [comment]
You need a newer version of gcc.  I suggest downloading from https://winlibs.com - they have v11.1.0.

**Comment by 5elenay** [comment]
> 
> 
> You need a newer version of gcc. I suggest downloading from https://winlibs.com - they have v11.1.0.

Thanks for your comment. i'll try!

**Comment by 5elenay** [comment]
Tried in WSL with gcc 11 again. but now:
```sh
irfan@irfan:/mnt/c/V$ make
cd ./vc && git clean -xf && git pull --quiet
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -g -std=gnu99 -w -o ./v ./vc/v.c -lm -lpthread 
./v -o v2.exe  cmd/v
vlib/v/pref/pref.v:752:2: notice: use `arm64` instead of `aarch64`
  750 |     // }
  751 |     // $if arm64 { // requires new vc
  752 |     $if aarch64 {
      |     ~~~~~~~~~~~
  753 |         return .arm64
  754 |     }
vlib/v/parser/fn.v:513:3: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
  511 |     if rec.typ.idx() == 0 {
  512 |         // error is set in parse_type
  513 |         return none
      |         ~~~~~~~~~~~
  514 |     }
  515 |     rec.type_pos = rec.type_pos.extend(p.prev_tok.position())
vlib/v/parser/fn.v:519:3: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
  517 |         p.error_with_pos('use `(mut f Foo)` or `(f &Foo)` instead of `(mut f &Foo)`',
  518 |             lpar_pos.extend(p.tok.position()))
  519 |         return none
      |         ~~~~~~~~~~~
  520 |     }
  521 |     if is_shared {
vlib/v/checker/checker.v:7341:3: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
 7339 |     if typ == 0 {
 7340 |         c.error('unknown type', pos)
 7341 |         return none
      |         ~~~~~~~~~~~
 7342 |     }
 7343 |     sym := c.table.get_type_symbol(typ)
vlib/v/checker/checker.v:7349:5: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
 7347 |                 c.error(util.new_suggestion(sym.name, c.table.known_type_names()).say('unknown type `$sym.name`'),
 7348 |                     pos)
 7349 |                 return none
      |                 ~~~~~~~~~~~
 7350 |             }
 7351 |         }
vlib/v/checker/checker.v:7362:5: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
 7360 |                 }
 7361 |                 c.error(msg, pos)
 7362 |                 return none
      |                 ~~~~~~~~~~~
 7363 |             }
 7364 |         }
vlib/v/builder/cc.v:48:3: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
   46 | fn (mut v Builder) find_win_cc() ? {
   47 |     $if !windows {
   48 |         return none
      |         ~~~~~~~~~~~
   49 |     }
   50 |     ccompiler_version_res := os.execute('$v.pref.ccompiler -v')
vlib/v/builder/cc.v:66:5: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
   64 |                     println('tcc not found')
   65 |                 }
   66 |                 return none
      |                 ~~~~~~~~~~~
   67 |             }
   68 |             v.pref.ccompiler = thirdparty_tcc
make: *** [Makefile:92: all] Error 1
```
gcc version:
```sh
irfan@irfan:/mnt/c/V$ gcc --version
gcc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by 5elenay** [comment]
> 
> 
> Tried in WSL with gcc 11 again. but now:
> 
> ```shell
> irfan@irfan:/mnt/c/V$ make
> cd ./vc && git clean -xf && git pull --quiet
> cd ./thirdparty/tcc && git clean -xf && git pull --quiet
> cc  -g -std=gnu99 -w -o ./v ./vc/v.c -lm -lpthread 
> ./v -o v2.exe  cmd/v
> vlib/v/pref/pref.v:752:2: notice: use `arm64` instead of `aarch64`
>   750 |     // }
>   751 |     // $if arm64 { // requires new vc
>   752 |     $if aarch64 {
>       |     ~~~~~~~~~~~
>   753 |         return .arm64
>   754 |     }
> vlib/v/parser/fn.v:513:3: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
>   511 |     if rec.typ.idx() == 0 {
>   512 |         // error is set in parse_type
>   513 |         return none
>       |         ~~~~~~~~~~~
>   514 |     }
>   515 |     rec.type_pos = rec.type_pos.extend(p.prev_tok.position())
> vlib/v/parser/fn.v:519:3: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
>   517 |         p.error_with_pos('use `(mut f Foo)` or `(f &Foo)` instead of `(mut f &Foo)`',
>   518 |             lpar_pos.extend(p.tok.position()))
>   519 |         return none
>       |         ~~~~~~~~~~~
>   520 |     }
>   521 |     if is_shared {
> vlib/v/checker/checker.v:7341:3: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
>  7339 |     if typ == 0 {
>  7340 |         c.error('unknown type', pos)
>  7341 |         return none
>       |         ~~~~~~~~~~~
>  7342 |     }
>  7343 |     sym := c.table.get_type_symbol(typ)
> vlib/v/checker/checker.v:7349:5: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
>  7347 |                 c.error(util.new_suggestion(sym.name, c.table.known_type_names()).say('unknown type `$sym.name`'),
>  7348 |                     pos)
>  7349 |                 return none
>       |                 ~~~~~~~~~~~
>  7350 |             }
>  7351 |         }
> vlib/v/checker/checker.v:7362:5: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
>  7360 |                 }
>  7361 |                 c.error(msg, pos)
>  7362 |                 return none
>       |                 ~~~~~~~~~~~
>  7363 |             }
>  7364 |         }
> vlib/v/builder/cc.v:48:3: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
>    46 | fn (mut v Builder) find_win_cc() ? {
>    47 |     $if !windows {
>    48 |         return none
>       |         ~~~~~~~~~~~
>    49 |     }
>    50 |     ccompiler_version_res := os.execute('$v.pref.ccompiler -v')
> vlib/v/builder/cc.v:66:5: error: returning `none` in functions, that have a `?` result type is not allowed anymore, either `return error(message)` or just `return` instead
>    64 |                     println('tcc not found')
>    65 |                 }
>    66 |                 return none
>       |                 ~~~~~~~~~~~
>    67 |             }
>    68 |             v.pref.ccompiler = thirdparty_tcc
> make: *** [Makefile:92: all] Error 1
> ```
> 
> gcc version:
> 
> ```shell
> irfan@irfan:/mnt/c/V$ gcc --version
> gcc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
> Copyright (C) 2021 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```

Also same with windows. it gives `vlib/v/pref/pref.v:752:2: notice: use "arm64" instead of "aarch64" `.

**Comment by araneta** [comment]
this also happen on linux mint 20

**Comment by JalonSolov** [comment]
Yet this is what I see on Ubuntu 20.10 running in WSL2:
```
jalon@Ripper:~/git/v2$ make
cd ./vc && git clean -xf && git pull --quiet
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -g -std=gnu99 -w -o ./v ./vc/v.c -lm -lpthread
./v -o v2.exe  cmd/v
mv -f v2.exe v
V has been successfully built
V 0.2.2 535dcac
jalon@Ripper:~/git/v2$ gcc --version
gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

jalon@Ripper:~/git/v2$
```
and this in Windows 10 Pro x64
```
PS D:\git\v> ./make.bat
Updating TCC
 > Syncing TCC from https://github.com/vlang/tccbin

Updating vc...
 > Sync with remote https://github.com/vlang/vc

Building V...
 > Attempting to build v_win.c with TCC
 > Compiling with .\v.exe self
 > V built successfully
 > To add V to your PATH, run `.\v.exe symlink`.

V version: V 0.2.2 535dcac
PS D:\git\v> gcc --version
gcc.exe (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

PS D:\git\v>
```

**Comment by 5elenay** [comment]
I was re-installed windows yesterday so i tried V again. Downloaded gcc from https://winlibs.com and added to PATH. then downloaded V and executed `./make` and it worked. I don't know why but it works now.

```ps1
PS C:\Users\irfan> v version
V 0.2.2 6736817
```
