### ISSUE TITLE
Better hash function for strings

### ISSUE THREAD

**Issue by eulerkochy** [vlang/v#1047]
The current implementation of hashing of strings is way too trivial. 
```
pub fn (s string) hash() int {
	mut hash := int(0)
	for i := 0; i < s.len; i++ {
		// if key == 'Content-Type' {
		// println('$i) $hash')
		// }
		hash = hash * int(31) + int(s.str[i])
	}
	return hash
}
```
This warrants for a better and secure hash function.

**Comment by alfclement** [comment]
Any proposal?

**Comment by eulerkochy** [comment]
I would tend to go for a variant of `MurMur` Hash. Also, a new file `hash.v` can be made in this retrospect.

**Comment by medvednikov** [comment]
This is the same hash function that's been used by Java for decades. It's battle tested, it's simple, it works:

http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/lang/String.java
