### ISSUE TITLE
os.read_file() doesn't seem to work on files in /proc but os.read_lines() does.

### ISSUE THREAD

**Issue by fuzzy** [vlang/v#1051]
**V version:** V 0.1.12
**OS:** Linux 5.1.8 / amd64

**What did you do?** 
Using os.read_file() on a file in /proc such as /proc/stat fails to return any data, however os.read_lines() works as expected.

```
import os

fn main() {
	content := os.read_file('/proc/stat') or {
		println('error readin in file')
		return error('error reading in file')
	}
	println('first try')
	for line in content.split('\n') {
		println(line)
	}
	println('second try')
	for line in os.read_lines('/proc/stat') {
		println(line)
	}
}
```
To verify I did 'cat /proc/stat > ./stat' and that read fine using both methods, but files under /proc don't seem to read in if you're using os.read_file(). I presume it's because of the nature of the /proc pseudofs.
```
$ ls -l /proc/stat ; file /proc/stat 
-r--r--r-- 1 root root 0 Jun 30 12:54 /proc/stat
/proc/stat: empty
```

**What did you expect to see?**
The contents of the file read out
 
**What did you see instead?**
nothing

```
$ v -o tryit tryit.v
$ ./tryit
first try
second try
cpu  45425249 150339 13913409 492403730 1340984 2372673 1171957 0 5769004 50813
cpu0 11660732 32173 3620382 122549400 376259 611142 256650 0 1439245 7926
...
```

**Comment by fuzzy** [comment]
Looking through the source for read_file() I'm not sure if this is really a bug. It does need to find the file size and proc pseudofs, at least on Linux (I haven't tried any bsd's with linprocfs mounted or anything) doesn't seem to report the 'size' accurately through the vfs layer. Doing a stat() on the file would yield the same results, so I'm not sure that this has a fix. If you need file content from /proc it seems like the best solution is to use read_lines() (it simplifies the code a bit anyway).

I'll leave it up to @medvednikov to decide if this is indeed a bug, but I think at least for the current implimentation, it's probably prescribed behaviour.

**Comment by stappersg** [comment]
I think it is caused by `/proc/stat` being special.
Please compare
```
$ wc /proc/stat
12 839 2076 /proc/stat
$ file /proc/stat
/proc/stat: empty
$ 
```
with
```
$ wc /etc/hosts
 46  101 1099 /etc/hosts
$ file /etc/hosts
/etc/hosts: ASCII text
$ 
````
Program `file` sees an empty `/proc/stat`,   `os.read_file()` seems to see the same (empty) file.

It is not a `v` bug.

**Comment by medvednikov** [comment]
Thanks @stappersg

**Comment by fuzzy** [comment]
Yeah. Thats the conclusion I came to as well after reading the read_file() implementation, I just thought others may be better suited to make the final call. Thanks for taking a look @medvednikov and @stappersg.
