### ISSUE TITLE
Improve compiler warning: const + optional

### ISSUE THREAD

**Issue by jdonnerstag** [vlang/v#10527]
**V version:**   V 0.2.2 5452ba4
**OS:**   Win10  10.0.18363 Build 18363

**What did you do?**
```
const (  
   re_int = regex.regex_opt("[+-]?[0-9]+")? 
) 
```
The compiler crashes

The solution is simlpe 

`const ( re_int = regex.regex_opt("[+-]?[0-9]+") or { panic("Invalid regex") } )` 

but the compiler should not crash.

**What did you expect to see?**
A proper compiler error message
 
**What did you see instead?**
The compiler crashes

**Comment by shadowninja55** [comment]
compiles on latest v.
