### ISSUE TITLE
commit: de8dc4c (Hot code reloading examples) is breaking tests

### ISSUE THREAD

**Issue by pverghese** [vlang/v#1052]
**V version:** 0.12
**OS:** Linux

**What did you do?**
make test

**What did you expect to see?**
All Passed
 
**What did you see instead?**
Failure due to not recognizing new submodule support using dot

**Comment by cytown** [comment]
Any of dot or / should be accepted, but both will cause failure.

**Comment by spytheman** [comment]
Fixed in #1058 .
