### ISSUE TITLE
compiler error message converts __ to . when it shouldn't

### ISSUE THREAD

**Issue by misternode** [vlang/v#1053]
**V version:** 
V 0.1.12

**OS:** 
macOS 10.14.5

**What did you do?**
(intentionally) wrote a function name with double underscore

**What did you expect to see?**
compiler error output:  function names cannot contain double underscores ("__"), use single underscores instead
 
**What did you see instead?**
function names cannot contain double underscores ("."), use single underscores instead

**Notes**
"__" is converted to "." in the parser before sending to scanner.error()

parser.v:691

`    p.scanner.error(s.replace('array_', '[]').replace('__', '.'))`

**Comment by medvednikov** [comment]
Thanks, I've fixed the message for now.

This __ hack will be removed, once I implement a `str()` method for `Type`.
