### ISSUE TITLE
postgresql on windows missing file of 'libpq-fe.h'

### ISSUE THREAD

**Issue by gshields** [vlang/v#10556]
module main

import pg

const dash = '----------------------------------------------------------------'

struct Strings {
  id int
  stringvalue string
  langid string
  state int
  creation string
  modification string
  certified string 
  sectionid int
}

db := pg.connect(pg.Config{
		host: 'localhost' //'127.0.0.1'
		user: 'postgres'
		dbname: 'public'
	}) or {
		println('failed to connect')
		println(err)
		return
	}

	
  cnt := sql db {
    select count from Strings
  }
  println('number of all strings: $cnt')

// Fails with:
//  v .\pg-test.v
// builder error: 'libpq-fe.h' not found
// V 0.2.2 83eb9d5
// window 10 19043.1081
// gcc.exe (GCC) 10.2.0

**Comment by gshields** [comment]
in reading vorum instructions I found that it says to install libpq. I switch to using sqlite  and have had better success. closing this issue since I have a solution

**Comment by enghitalo** [comment]
So try installing libpq-dev or its equivalent for your OS:

For Ubuntu/Debian systems: `sudo apt-get install libpq-dev`
On [Red Hat Linux](http://en.wikipedia.org/wiki/Red_Hat_Linux) (RHEL) systems: `yum install postgresql-devel`
For Mac [Homebrew](https://en.wikipedia.org/wiki/Homebrew_%28package_management_software%29): `brew install postgresql`
For Mac [MacPorts](http://en.wikipedia.org/wiki/MacPorts) PostgreSQL: `gem install pg -- --with-pg-config=/opt/local/lib/postgresql[version number]/bin/pg_config`
For [OpenSuse](https://en.wikipedia.org/wiki/OpenSUSE): `zypper in postgresql-devel`
For [ArchLinux](https://en.wikipedia.org/wiki/Arch_Linux): `pacman -S postgresql-libs`

**Comment by JalonSolov** [comment]
He said "on windows"... windows is always more challenging. Good move to switch to sqlite unless postgres is _really_ needed.
