### ISSUE TITLE
Enum variable with `str` as selected value returns C error

### ISSUE THREAD

**Issue by nedpals** [vlang/v#10578]
**V version:** V 0.2.2 02f4f63
**OS:** linux, Ubuntu 20.04.2 LTS
**Processor:** 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
**CC version:** cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**What did you do?**
```v
enum Kind {
    str
    num
}

kind := Kind.str
println('${kind}')
```

**What did you expect to see?**
```
str
```
 
**What did you see instead?**
C gen error

**Extra Information**
Any enum member/value that has a similar name to the implemented method returns a cgen error. However, this one works:
```
enum Kind {
    str
    num
}

println('${Kind.str}')
```

To further prove my speculation, the same problem also occurs on this code:
```v
enum Kind {
    foo
}

pub fn (k Kind) foo() {}

kind := Kind.foo
println('${kind}')
```

**Comment by shadowninja55** [comment]
seems like we can use `__` before our enum fields to avoid interfering with methods.

**Comment by shadowninja55** [comment]
closed that by accident sorry.
