### ISSUE TITLE
Expect unused label warning

### ISSUE THREAD

**Issue by shadowninja55** [vlang/v#10596]
**V version:** V 0.2.2 f32a76b.ea3983a
**OS:** linux, "Arch Linux"

**What did you do?**

(exact code)
```v
https://vlang.io
```

**What did you expect to see?**

a compiler error.
 
**What did you see instead?**

code compiles. `main__main`:
```c
VV_LOCAL_SYMBOL void main__main(void) {
    https: {}
}
```

**Comment by dumblob** [comment]
`https` becomes a label due to `:`. The rest is just a comment (comments start with `//`).

Generally the shown behavior seems correct to me.

**Comment by crthpl** [comment]
This should have a `unused label` error

**Comment by JalonSolov** [comment]
Labels are only valid in V if they are the target of a `break` or `continue`:  https://github.com/vlang/v/blob/master/doc/docs.md#labelled-break--continue

**Comment by Gladear** [comment]
No, there is `goto` too : <https://github.com/vlang/v/blob/master/doc/docs.md#goto>

**Comment by JalonSolov** [comment]
Oof.  Goto bad... bad doesn't matter.  If the label isn't referenced as a target then it at least needs `unused label` warning/error.

**Comment by medvednikov** [comment]
Fixed:

```
label `mylabel` defined and not used
```
