### ISSUE TITLE
Need  variadic functions(functions with variable number of arguments)

### ISSUE THREAD

**Issue by cytown** [vlang/v#1061]
Just like Go, the following should be supported:

`
fn log(msg string, s ...string) {
    C.printf(msg, s...)
}
`

**Comment by MaD70** [comment]
You mean [variadic functions](https://gobyexample.com/variadic-functions) (functions with variable number of arguments). Please, correct the title of this feature request.

**Comment by cytown** [comment]
There is no TODO for this feature...

**Comment by medvednikov** [comment]
It's partially implemented already: 

```
fn foo(a, b int, ..) {}
foo(2,3,4,5)
```

The values can't be used by the function at the moment.

**Comment by ntrel** [comment]
I was expecting the parameter syntax to be like Go:
https://gobyexample.com/variadic-functions

**Comment by medvednikov** [comment]
Yes, it will be. Right now it's a temporary implementation to make translated C code compile.

**Comment by medvednikov** [comment]
This was implemented a couple of weeks ago.
