### ISSUE TITLE
vlib/os/notify/notify_test.v fils on WSL2

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#10622]
**V version:** latest master :^)
**OS:** Ubuntu 20.04 WSL2

**What did you do?**
`v test vlib/os/notify/notify_test.v`

**What did you expect to see?**
works
 
**What did you see instead?**
```
/home/daniel/Projects/v/vlib/os/notify/notify_test.v:57: ✗ fn test_edge_trigger
   > assert notifier.wait(0).len == 0
     Left value: 0
    Right value: 0
```

There are two errors:
1. Left value is `1` but `0` is displayed.
2. It fails but it shouldn't

If I split it into multiple lines I get this:
```
[os.notify.FdEvent(os.notify.EpollEvent{
    fd: 4
    kind: os.notify.FdEventType{.read}
})]
/home/daniel/Projects/v/vlib/os/notify/notify_test.v:59: ✗ fn test_edge_trigger
   > assert wait.len == 0
     Left value: 1
    Right value: 0
```

@mcastorina Do you know anything?

**Comment by JalonSolov** [comment]
Works with Ubuntu 21.04 in WSL2, and latest V 0.2.2 9d02ca5.
```
jalon@Ripper:~/git/v$ v test vlib/os/notify/notify_test.v
---- Testing... -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 OK     256.052 ms vlib/os/notify/notify_test.v
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Summary for all V _test.v files: 1 passed, 1 total. Runtime: 256 ms.

jalon@Ripper:~/git/v$
```

**Comment by mcastorina** [comment]
That's really strange. I'm able to reproduce it on my WSL2 box too, but the only explanation I can think of is the system call actually behaves diffirently. I wonder if it's a WSL issue or an Ubuntu issue?

The recommended way to use edge trigger mode is to read all available data when receiving the event, so perhaps this code is testing undefined behavior that varies across kernels.
