### ISSUE TITLE
'for_reverse' loop

### ISSUE THREAD

**Issue by JoanaBLate** [vlang/v#10625]
It is like normal 'for' loop except that it goes from the end to the beginning of the array or string.

**Comment by Gladear** [comment]
Two choices:
```v
for i := array.len - 1; i >= 0; i-- {
    item := array[i]
    // your code here
}
```
More efficient memory-wise
or
```v
for item in array.reverse() {
    // your code here
}
```
Easier to write and read, but consumes a bit more memory (can be a lot if the array / string is long)
Also works with strings

**Comment by JoanaBLate** [comment]
@Gladear

Of course, the 2 solutions above work, but

- the solution '1' (classic C 'for') is efficient, but is not as friendly to write and read as the solution '2'

- the solution '2' ('for in' after reversing an array) is not efficient, although very friendly to write and read

That's why I made this proposal: a 'for_reverse' loop would have the advantages of the others without having any disadvantage.

But I understand that  V wants to be small, so this feature may not be worth it.

Thanks for your reply.

**Comment by Gladear** [comment]
Ideally, an iterator could be made out of an array, so you can have `for item in array.iter().reverse()`, and it wouldn't waste any memory allocating a new array
It's not planned afaik, but I really think it could be a great feature, adding a lot of possibilities to arrays

**Comment by JoanaBLate** [comment]
Good Idea!
