### ISSUE TITLE
fix length with variable array initial error

### ISSUE THREAD

**Issue by cytown** [vlang/v#1062]
**V version:** 0.1.12
**OS:** macOS 10.13.6

**What did you do?**
`
fn test() {

  bufsize := 1024

  mut buf := [bufsize]byte

  // mut buf := [1024]byte // this compile fine

  ...

}
`

**What did you expect to see?**
success compile
 
**What did you see instead?**
panic: t.v:14
undefined: `byte`
make: *** [t] Error 1

**Comment by ntrel** [comment]
> mut buf := [bufsize]byte

Use `[byte(0); bufsize]`.

> mut buf := [1024]byte // this compile fine

1024 is a compile time constant. These look like fixed size arrays, but they don't seem to be documented.

**Comment by cytown** [comment]
> > mut buf := [bufsize]byte
> 
> Use `[byte(0); bufsize]`.
> 
> > mut buf := [1024]byte // this compile fine
> 
> 1024 is a compile time constant. These look like fixed size arrays, but they don't seem to be documented.

Hi @ntrel ,

I think `[byte(0); bufsize]` is quite different with [bufsize]byte, not mention it will run bufsize times of memcpy operation...

BTW: `const bufsize=1024` will get the same error.

**Comment by ntrel** [comment]
Yes, `[byte(0); size]` is not a fixed size array, so its size can depend on a runtime variable `size`.

> it will run bufsize times of memcpy operation.

That's an optimization issue, not necessarily a language issue.

> const bufsize=1024 will get the same error

Fixed size arrays seem to be an experimental feature, I think the parser only accepts integer literals ATM.

This Go code behaves as I explained:
https://play.golang.org/p/RVUGg6Vyri0

**Comment by cytown** [comment]
> Yes, `[byte(0); size]` is not a fixed size array, so its size can depend on a runtime variable `size`.
> 
> > it will run bufsize times of memcpy operation.
> 
> That's an optimization issue, not necessarily a language issue.
> 
> > const bufsize=1024 will get the same error
> 
> Fixed size arrays seem to be an experimental feature, I think the parser only accepts integer literals ATM.
> 
> This Go code behaves as I explained:
> https://play.golang.org/p/RVUGg6Vyri0

So, Go will accept const, the issue is V has the bug for const.
p.s. Go can use make to get the similar result.

https://play.golang.org/p/Yt20hOUxAZh

**Comment by ntrel** [comment]
Closing in favour of #762.
