### ISSUE TITLE
Scope of the vlib

### ISSUE THREAD

**Issue by yep84** [vlang/v#1063]
Maybe it could be useful to define what should be included in the vlib and what should be included in extra lib.

My proposition is to have a quite small vlib, focused on essential features and heavily tested. And some other directories which include cool stuff but maybe less useful for everyone.

**Comment by alfclement** [comment]
Would be great, if V and Vlib is targeting embedded devices (small code size, no dynamic features) and can be extended for general purpose on other machines (eg. dynamic memory, gc, etc... )

**Comment by medvednikov** [comment]
It's going to be very similar to Go's standard library.

**Comment by hamad-almamari** [comment]
I agree, I think vlib should be only has core libs. Which written in pure V. 

The extra ones like libs whech use some or depends  of/on c libs like open GL or any gui libs must be in other place.

**Comment by medvednikov** [comment]
gg, ui, glfw, gl, pg etc are not part of vlib and will be moved this week, once user modules are supported.
