### ISSUE TITLE
Has V given up on getting rid of its dependence on glibc?

### ISSUE THREAD

**Issue by willvsimple** [vlang/v#10642]
I saw on V's website earlier that it will not depend on glibc in the future. But now I can't find it.
Does this mean that V will always depend on glibc?
Instead of being able to run independently like go.

I tested the simplest print('hello'), and after compiling it on centos8, it doesn't work on lower versions of systems, it says it needs glibcX.so .

**Comment by Cons-Cat** [comment]
I might be wrong, but I thought that's what the `-freestanding` compiler flag was for.

**Comment by spytheman** [comment]
> I tested the simplest print('hello'), and after compiling it on centos8, it doesn't work on lower versions of systems, it says it needs glibcX.so .

Try compiling with `v -cflags -static file.v`.

**Comment by willvsimple** [comment]
> 
> 
> I might be wrong, but I thought that's what the `-freestanding` compiler flag was for.



> -freestanding

I tried it and I'm very happy it worked! Thank you very much!   : )

**Comment by willvsimple** [comment]
https://github.com/vlang/v/issues/10642#issuecomment-873520054

Thank you for your reply!
It doesn't work, error message:

 v -cflags -static hello.v
==================
tcc: error: library 'c' not found
tcc: error: undefined symbol '__libc_csu_fini'
tcc: error: undefined symbol '__libc_csu_init'
tcc: error: undefined symbol '__libc_start_main'
tcc: error: undefined symbol 'memmove'
tcc: error: undefined symbol 'memset'
tcc: error: undefined symbol 'memcpy'
tcc: error: undefined symbol 'qsort'
tcc: error: undefined symbol 'exit'
tcc: error: undefined symbol 'stdout'
tcc: error: undefined symbol 'fflush'
tcc: error: undefined symbol 'stderr'
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

v -v
V 0.2.2 2f9e03b

**Comment by willvsimple** [comment]
> v -cflags -static
Still not working after the upgrade:
v up
Updating V...
Current V version:
V 0.2.2 972542d, timestamp: 2021-07-05 05:05:37 +0300

v -cflags -static hello.v
==================
tcc: error: library 'c' not found
tcc: error: undefined symbol '__libc_csu_fini'
tcc: error: undefined symbol '__libc_csu_init'
tcc: error: undefined symbol '__libc_start_main'
tcc: error: undefined symbol 'memmove'
tcc: error: undefined symbol 'memset'
tcc: error: undefined symbol 'memcpy'
tcc: error: undefined symbol 'qsort'
tcc: error: undefined symbol 'exit'
tcc: error: undefined symbol 'stdout'
tcc: error: undefined symbol 'fflush'
tcc: error: undefined symbol 'stderr'
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

Maybe it's a problem with the OS?

cat /etc/redhat-release
AlmaLinux release 8.3 (Purple Manul)

**Comment by medvednikov** [comment]
try `v -cc clang -cflags -static`

**Comment by medvednikov** [comment]
Getting rid of libc is only possible on Linux, and will be done, but it's not a priority atm.

**Comment by willvsimple** [comment]
> 
> 
> > I tested the simplest print('hello'), and after compiling it on centos8, it doesn't work on lower versions of systems, it says it needs glibcX.so .
> 
> Try compiling with `v -cflags -static file.v`.

> 
> 
> try `v -cc clang -cflags -static`

Either way works.
It is the problem of my compilation environment, missing glibc-static, after installing it, it worked.

**Comment by willvsimple** [comment]
> 
> 
> Getting rid of libc is only possible on Linux, and will be done, but it's not a priority atm.

That's enough, thank you very much for your great work.
V is a really good programming language and I like V very much. 
I look forward to using V in a production environment.
Thanks again!
