### ISSUE TITLE
v run can not handle child process termination

### ISSUE THREAD

**Issue by ciubotaru** [vlang/v#1064]
**V version:**
latest snapshot of master branch
**OS:** 
Ubuntu 18.04 amd64
**What did you do?**
```
v run program.v #in one terminal
killall program #in a different terminal
```
**What did you expect to see?**
v run exit gracefully
 
**What did you see instead?**
v run continues running quickly eating up memory

**Comment by spytheman** [comment]
Current V does not continue after the child process was killed.

**Comment by spytheman** [comment]
Tested with the following program.v :
```v
import time

fn main(){
  println('start sleeping')
  time.sleep_ms(5*1000*1000)
  println('end sleeping')
}
```
