### ISSUE TITLE
example fireworks bug

### ISSUE THREAD

**Issue by denise-amiga** [vlang/v#10645]
**OS:** linux, "Manjaro Linux"
**Processor:** 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
**CC version:** cc (GCC) 11.1.0

**getwd:** /home/denise
**vmodules:** /home/denise/.vmodules
**vroot:** /home/denise/Temp/v
**vexe:** /home/denise/Temp/v/v
**vexe mtime:** 2021-07-02 09:19:34
**is vroot writable:** true
**is vmodules writable:** true
**V full version:** V 0.2.2 9d02ca5.1486258

**Git version:** git version 2.32.0
**Git vroot status:** weekly.2021.26-31-g14862585-dirty
**.git/config present:** true
**thirdparty/tcc status:** thirdparty-linux-amd64 7543de81
 
**What did you do?**
I change the probability to increase the number of rockets, from 30 to 5

**What did you expect to see?**
greater number of rockets :D
 
**What did you see instead?**
that when they start to explode, instead of drawing "all the particles", the window remains black, as if instead of slowing down due to the number of things that had to be drawn, it did not directly draw anything

**Comment by shadowninja55** [comment]
if there are too many particles it goes black and doesn't draw them it's a known bug. possibles fixes include changing the hardcoded limits of items on the screen at once.

**Comment by denise-amiga** [comment]
ok, thx for info
