### ISSUE TITLE
IError works when return type string is expected

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#10663]
**V doctor:**
```
OS: linux, Ubuntu 20.04.2 LTS (WSL 2)
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
CC version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

getwd: /home/daniel/Projects/v
vmodules: /home/daniel/.vmodules
vroot: /home/daniel/Projects/v
vexe: /home/daniel/Projects/v/v
vexe mtime: 2021-07-04 12:32:05
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 e4d88a5.6a64259

Git version: git version 2.25.1
Git vroot status: weekly.2021.26-42-g6a642595
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81
```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg main.v`
```v
module main

fn is_teen(age int) ?string {
        if age < 0 {
                return error('invalid age provided')
        } else if age >= 13 && age <= 19 {
                return 'teenager'
        } else {
                return 'not teenager'
        }
}

fn main() {
        x := is_teen(-3) or { err }
        println(x)
}

```

**What did you expect to see?**

err is of type IError but the return type of is_teen is of type string which is not the same, it shouldn't work in my opinion.

**What did you see instead?**
```
invalid age provided
```

**Comment by JalonSolov** [comment]
I don't see a problem.  You declared it as returning an _optional_ string.  This means it can be a string _or_ an error.

**Comment by shadowninja55** [comment]
this is intended behavior, your return type was `?string`.

**Comment by danieldaeschle** [comment]
`x` should be a string. The last statement in the or block needs to be the same type as the variable.
e.g. `x := get_int() or { 0 }` is correct but `x := get_int() or { SomeStruct{} }` is not.

Since err is of type `IError` and not of type `string` it wouldn't match the type `string`

`x := is_teen(-3) or { err }` is equivalent to `x := get_string() or { Error{} }` which shouldn't work.

**Comment by shadowninja55** [comment]
ahh i see you're assigning `err` to `x` whoops. yeah that's not allowed afaik good find
