### ISSUE TITLE
Invalid C when using void pointer maps

### ISSUE THREAD

**Issue by AtjonTV** [vlang/v#1067]
**V version:** latest commit
**OS:** eOS 5.0

**What did you do?**
1. Create a map of type `map[string]voidptr`
2. Insert some data
3. Try to read data

**What did you expect to see?**
Data is read
 
**What did you see instead?**
```
$ v app.v 
/home/atjontv//.vlang//app.c:3979:16: error: scalar initializer cannot be empty
voidptr tmp3 = {}; bool tmp4 = map_get( db ->data , key, & tmp3);
               ^~
/home/atjontv//.vlang//app.c:4004:16: error: scalar initializer cannot be empty
voidptr tmp7 = {}; bool tmp8 = map_get( db .data , key, & tmp7);
               ^~
/home/atjontv//.vlang//app.c:4047:17: error: scalar initializer cannot be empty
voidptr tmp14 = {}; bool tmp15 = map_get( db .data , key, & tmp14);
                ^~
3 errors generated.
V panic: clang error
```

----

Have already found the cause, shared it in Discord:

![image](https://user-images.githubusercontent.com/24845056/60929312-1ebb1900-a2b1-11e9-8f4b-fe992e95fb4b.png)
¹ https://github.com/vlang/v/blob/master/compiler/parser.v#L874
² https://github.com/vlang/v/blob/master/compiler/table.v#L536
![image](https://user-images.githubusercontent.com/24845056/60929322-2a0e4480-a2b1-11e9-9986-5b19bd776e0c.png)
¹ https://github.com/vlang/v/blob/master/compiler/parser.v#L1776

**Comment by medvednikov** [comment]
Fixed.
