### ISSUE TITLE
0.1.13 can't build

### ISSUE THREAD

**Issue by longlene** [vlang/v#1069]
**V version:** 
**OS:** 

**What did you do?**
build0.1.13

**What did you expect to see?**

 
**What did you see instead?**
Setting VROOT to "/var/tmp/portage/dev-lang/v-0.1.13/work/v-0.1.13".
panic: parser.v:302
undefined: `DOT`

I search DOT in source tree, only one `DOT` in parser.v

**Comment by cytown** [comment]
I think it's been fixed already in master

**Comment by medvednikov** [comment]
Fixed. `git pull`
