### ISSUE TITLE
Can't handle scientific float format?

### ISSUE THREAD

**Issue by MaxGraey** [vlang/v#107]
```go
fn main() {
  println(1.7014118346046923e+38)
}
```
Output:
```
expected `)` but got `e`
```

**Comment by rab1** [comment]
@MaxGraey  You are right, it doesn't have float properly.

```
println(10.0 / 3.0) 
```

Should return `3.3333333333333335`, and `v` returns `3.333333`

**Comment by MaxGraey** [comment]
@rab1
Just check this:
```go
fn main() {
	a := 0.1 + 0.2
	println(a == 0.1 + 0.2)
}
```
Output: false

**Comment by medvednikov** [comment]
@rab1 `10.0 / 3.0 == 3.333333` in C. In V as well.

Same with `0.1 + 0.2`.

**Comment by MaxGraey** [comment]
@rab1 See this issue: https://github.com/vlang/v/issues/80

**Comment by medvednikov** [comment]
No it isn't:

```
printf("%f\n", 10.0 / 3.0);

3.333333 
```

https://onlinegdb.com/BJNCnl1oV

**Comment by MaxGraey** [comment]
```
printf("%.16f\n", 10.0 / 3.0);
```
Output:
```
3.3333333333333335
```
printf just use rounded formatting by default

**Comment by MaxGraey** [comment]
So `10.0 / 3.0` not equal `3.333333` but equal `3.3333333333333335`

**Comment by medvednikov** [comment]
Again, V works like C.

**Comment by MaxGraey** [comment]
Again, you have pretty bad knowing how works C and its runtime

**Comment by medvednikov** [comment]
You wrote it yourself:

> printf just use rounded formatting by default

**Comment by MaxGraey** [comment]
But I thought you follow Go lang "spec". In Go `10.0 / 3.0` prints `3.3333333333333335`:
https://play.golang.org/p/WkfCRdNtwc7

**Comment by medvednikov** [comment]
What makes you think it follows Go spec when it compiles to C?

Also you say I have "pretty bad knowledge how works C" when it works **exactly** like C:

```println(10.0 / 3.0 == 3.3333333333333335) // true```

```printf("%f\n", 10.0 / 3.0); // 3.333333 ```

**Comment by medvednikov** [comment]
And how is all this even remotely relevant by the way? 

You should never use `==` when comparing floats, you can always specify the amount of digits after dot via formatting.

**Comment by MaxGraey** [comment]
> What makes you think it follows Go spec when it compiles to C?

Because you usually to refer to Go like in this [comment](https://github.com/vlang/v/issues/80#issuecomment-481011073)

**Comment by MaxGraey** [comment]
> You should never use == when comparing floats, you can always specify the amount of digits after dot via formatting.

Usually it's true, but when LHS and RHS totally deterministic like in examples mentioned before that's all are legit.

**Comment by medvednikov** [comment]
scientific float format has been implemented
