### ISSUE TITLE
cant make??

### ISSUE THREAD

**Issue by wangcegithub** [vlang/v#1070]
**V version:** 
**OS:** 
v.c:374:3: error: expected specifier-qualifier-list before ‘_Atomic’
   _Atomic int fn_cnt;
   ^
v.c: In function ‘Fn_str’:
v.c:14381:21: error: unknown field ‘fn_cnt’ specified in initializer
                     .fn_cnt = 0,
                     ^
v.c:14382:21: error: unknown field ‘obfuscate’ specified in initializer
                     .obfuscate = 0};
                     ^
v.c: In function ‘new_table’:
v.c:14400:3: error: unknown field ‘obfuscate’ specified in initializer
   Table *t = ALLOC_INIT(Table, {
   ^
v.c:14400:3: error: unknown field ‘fn_cnt’ specified in initializer
v.c: In function ‘Table_cgen_name’:
v.c:15232:12: error: ‘Table’ has no member named ‘obfuscate’
   if (table->obfuscate && string_ne(f->name, tos2("main")) &&
            ^
v.c:15252:12: error: ‘Table’ has no member named ‘fn_cnt’
       table->fn_cnt++;
            ^
v.c:15253:24: error: ‘Table’ has no member named ‘fn_cnt’
       int tmp67 = table->fn_cnt;
                        ^
v.c:15257:18: error: ‘Table’ has no member named ‘fn_cnt’
       idx = table->fn_cnt;
                  ^

**What did you do?**

**What did you expect to see?**

 
**What did you see instead?**

**Comment by medvednikov** [comment]
Hi

You didn't provide your OS.

**Comment by wangcegithub** [comment]
[root@log360-206 /]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

[root@log360-206 /]# cat /proc/version
Linux version 3.10.0-957.10.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Mon Mar 18 15:06:45 UTC 2019

**Comment by wangcegithub** [comment]
> Hi
> 
> You didn't provide your OS.

[root@log360-206 /]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

[root@log360-206 /]# cat /proc/version
Linux version 3.10.0-957.10.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Mon Mar 18 15:06:45 UTC 2019

**Comment by medvednikov** [comment]
You have a 7 year old version of GCC. Please update.

V will support older C compilers soon.
