### ISSUE TITLE
Inconsistent type checking for mut parameter

### ISSUE THREAD

**Issue by ntrel** [vlang/v#1071]
**V version:** 0.1.12
**OS:** judge0.com

**What did you do?**
```
struct S {
	mut:
	i int
}

fn (s mut S) e() S {
	return s // error in generated C
}

// these 3 functions all compile:
fn (s mut S) f() S {
	return *s
}

fn (s mut S) g() *S {
	return s
}

fn (s mut S) h() *S {
	return &s
}
```
**What did you expect to see?**
1. Only one of `g` or `h` should compile.
2. For consistency with `f`, `h` should be rejected with `expected *S, not **S` - but:
3. Parameter `s` has to be a pointer in the C code generated, but usually in languages with mutable parameters, this pointer is not exposed to the programmer. It might be better to type `s` as `S` not `*S`, and automatically dereference it. In which case `f` and `g` would fail but `e` and `h` would be valid.
 
**What did you see instead?**
V compiles both `g` and `h`, despite them having different expression types.

**Comment by Dialga** [comment]
A different error occurs now when trying your example.
```
issue1071.v:1:8: error: single letter capital names are reserved for generic template types.
    1 | struct S {
      |        ^
    2 |     mut:
    3 |     i int
```

**Comment by remimimimi** [comment]
This code now throws an error in compile time
