### ISSUE TITLE
Error: unknown function: i32

### ISSUE THREAD

**Issue by bumbread** [vlang/v#10715]
**V version:** V 0.2.2 `47bf644`, timestamp: 2021-07-09 03:27:16 +0300
**OS:** Linux, Ubuntu 20.04.2 LTS

**What did you do?**

```
mut a := i32(0x80000000)
println(a)
```

**What did you expect to see?**

The program should compile correctly and output `-2147483648`
 
**What did you see instead?**

```
main.v:6:12: error: unknown function: i32
    4 | {
    5 |   
    6 |   mut a := i32(0x80000000)
      |            ~~~~~~~~~~~~~~~
    7 |   println(a)
    8 |
```

**Comment by nedpals** [comment]
@bumbread `int` is the equivalent of `i32`: https://github.com/vlang/v/blob/master/doc/docs.md#primitive-types

**Comment by shadowninja55** [comment]
as ned said, the correct name is int.
