### ISSUE TITLE
Unchecked character literals for Unicode ranges

### ISSUE THREAD

**Issue by flysand7** [vlang/v#10717]
**V version:** V 0.2.2 `47bf644`, timestamp: 2021-07-09 03:27:16 +0300
**OS:** Linux, Ubuntu 20.04.2 LTS

**What did you do?**

```
mut a := '\uD8FF'
println(a)
```

**What did you expect to see?**

The characters with codepoints in between `U+D800` and `U+DFFF` and above `10FFFF` are invalid. The v compiler does not reports an error upon encountering such characters.
 
**What did you see instead?**

The program successfully compiles and the bytes are blindly written to the terminal, even though they decode an invalid codepoint

**Comment by Delta456** [comment]
I will try to fix this issue
