### ISSUE TITLE
Character hex escape parsing overflow

### ISSUE THREAD

**Issue by bumbread** [vlang/v#10718]
**V version:** V 0.2.2 `47bf644`, timestamp: 2021-07-09 03:27:16 +0300
**OS:** Linux, Ubuntu 20.04.2 LTS

**What did you do?**

```
mut a := '\x1000000061'
println(a)
```

**What did you expect to see?**

An error message about characters literal overflow
 
**What did you see instead?**

The program prints `a` (hex code `61`) to the terminal

**Comment by shadowninja55** [comment]
the 1 at the beginning after `\x` is what's making it overflow.

**Comment by JalonSolov** [comment]
It should only allow AT MOST 4 hex digits after the `x`, as that's the max for UTF-8 characters.

**Comment by bumbread** [comment]
@JalonSolov allowing at most 4 characters will fail for some characters in the range `0x10000`-`0x10ffff`. With `\x` it should allow at most 6 characters in order to make sure it can represent any codepoint in the Unicode range. preferably the RANGE itself is the only thing that has to be checked

**Comment by bumbread** [comment]
@JalonSolov I should add that the UTF-8 encoding takes up to 4 bytes. This has no relation to unicode codepoints which have no relation to the encoding used to encode them. For unicode codepoints, each takes up from 1 to 6 hexadecimal characters. The characters from `10000h-10ffffh` (inclusive) include emoji and some chinese characters and other rarely-used alphabets, that might also be a thing to keep in mind

**Comment by JalonSolov** [comment]
While Unicode codepoints do, indeed, take up to 6 hexadecimal characters, V only supports UTF-8, where the maximum is `U+10FFFF`.  So yes, 6 hexidecimal characters should be allowed, but the maximum should be checked against that value.  Anything over that (`U+11FFFF`, `U+20FFFF`, etc.) should be an error.
