### ISSUE TITLE
On Windows, http.download_file errors before `or {}` block

### ISSUE THREAD

**Issue by BenStigsen** [vlang/v#10726]
**V version: 0.2.2 9e61321** 
**OS: windows, Microsoft Windows 10 Enterprise LTSC v17763 64-bit** 

**What did you do?**
Send a request with `http.get()` and `http.download_file()`.

**What did you expect to see?**
A downloaded file, status 200 or something handled by the `or {}` block. 
 
**What did you see instead?**
```Unhandled Exception 0xC0000005
C:/Users/BENSTI~1/AppData/Local/Temp/v/ccm.11772736471763394746.tmp.c:9507: at print_backtrace_skipping_top_frames_tcc: Backtrace
C:/Users/BENSTI~1/AppData/Local/Temp/v/ccm.11772736471763394746.tmp.c:9474: by print_backtrace_skipping_top_frames
C:/Users/BENSTI~1/AppData/Local/Temp/v/ccm.11772736471763394746.tmp.c:9532: by unhandled_exception_handler
7ffa924dc8b6 : by ???
8f50000000014bfc : by ???
```

**Description:**
So, I was downloading music from FreeMusicArchive with `http.download_file()`

Here's the problem:
```v
// A lot of downloaded links like below
// title := "Some title"

// This works perfectly fine:
http.download_file("https://freemusicarchive.org/track/Broke_For_Free_-_Directionless_EP_-_01_Night_Owl/download", "music/$(title).mp3") or {return}

// This does not:
http.download_file("https://freemusicarchive.org/track/Its_Your_Birthday_1839/download", "music/$(title).mp3") or {return}
```

So I was able to download a lot of files, but with that specific link, it always fails. After receiving help in the Discord, we found out that it probably had something to do with the redirection links. 

**Redirection link for the one that works:**
https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Broke_For_Free/Directionless_EP/Broke_For_Free_-_01_-_Night_Owl.mp3?download=1&name=Broke%20For%20Free%20-%20Night%20Owl.mp3

**Redirection link for the one that errors:**
https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Monk_Turner__Fascinoma/The_New_Birthday_Song_Contest/Monk_Turner__Fascinoma_-_01_-_Its_Your_Birthday.mp3?download=1&name=Monk%20Turner%20%2B%20Fascinoma%20-%20It%27s%20Your%20Birthday%21.mp3

The difference in the redirection links is that the one that doesn't work contains `%21` and `%27` which is the `!` and `'` character.

It was tested by two others (@crthpl and @mcastorina), and it seems to work on Mac and Linux. It never reaches the `or {}` block, so it probably has something to do with the library it self.

**Comment by BenStigsen** [comment]
After taking a look, it's probably in the `urllib` module when escaping the characters it goes wrong. Specifically this match case: https://github.com/vlang/v/blob/44e78a6301a7650ad005430a485fa7534aebf278/vlib/net/urllib/urllib.v#L110-L120

I think it's the same issue as reported with Go here: https://groups.google.com/g/golang-nuts/c/5er6Ud_V0-U

**Comment by danieldaeschle** [comment]
With this code on windows:
```v
import net.http

fn main() {
	// A lot of downloaded links like below
	title := 'Some title'

	// This works perfectly fine:
	http.download_file('https://freemusicarchive.org/track/Broke_For_Free_-_Directionless_EP_-_01_Night_Owl/download', './music/${title}.mp3') ?

	// This does not:
	http.download_file('https://freemusicarchive.org/track/Its_Your_Birthday_1839/download', './music/${title}.mp3') ?
}

```

I get 
```
V panic: optional not set (failed to open file "./music/Some title.mp3")
v hash: fdba360
```

Can't reproduce the error

**Comment by BenStigsen** [comment]
Ah, well then it's not the best example. In my actual code which is quite a bit longer I do:
```v
http.download_file('https://freemusicarchive.org/track/Its_Your_Birthday_1839/download', "music/${title}.mp3") or {return}
```

**Comment by danieldaeschle** [comment]
ah, I had to create the music directory

**Comment by danieldaeschle** [comment]
here is the stacktrace:
```
Unhandled Exception 0xC0000005
29: strnicoll_l                ?? : address = 0x1f51785a260
28: strnicoll_l                ?? : address = 0x1f51785a350
27: strnicoll_l                ?? : address = 0x1f51785a0d0
26: strnlen                    ?? : address = 0x1f517859fe0
25: _p__commode                ?? : address = 0x1f51785a1c0
24: _p__commode                ?? : address = 0x1f517859f90
23: _p__commode                ?? : address = 0x1f517859e50
22: _p__commode                ?? : address = 0x1f517859ea0
21: _p__commode                ?? : address = 0x1f51785a3a0
20: _stdio_common_vsprintf     ?? : address = 0x1f51785a3f0
19: vsnprintf_l                ?? : address = 0x1f51785a030
18: vsprintf_l                 ?? : address = 0x1f517859e00
17: sprintf                    ?? : address = 0x1f51785a710
16: new_tls_context            ?? : address = 0x1f517859f40
15: new_tls_context            ?? : address = 0x1f51785a120
14: net__split_address         ?? : address = 0x1f51785a440
13: net__http__Request_do      ?? : address = 0x1f51785a170
12: net__http__Request_do      ?? : address = 0x1f51785a490
11: net__http__fetch           ?? : address = 0x1f51785a530
10: net__http__url_encode_form_data  ?? : address = 0x1f51785a580
9 : net__http__get             ?? : address = 0x1f51785a5d0
8 : net__http__download_file   ?? : address = 0x1f51785a620
7 : net__http__version_from_str  ?? : address = 0x1f51c3782b0
6 : wmain                      ?? : address = 0x1f51c3784e0
5 : invoke_main                d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:91
4 : __scrt_common_main_seh     d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
3 : __scrt_common_main         d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331
2 : wmainCRTStartup            d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_wmain.cpp:17
1 : BaseThreadInitThunk        ?? : address = 0x1f51c3781c0
0 : RtlUserThreadStart         ?? : address = 0x1f51c377f40
```

**Comment by BenStigsen** [comment]
Yeah neither do I.

**Comment by spytheman** [comment]
hm, that stacktrace looks very weird - `net__split_address` does not call `new_tls_context` .. Can you try the same, but with `-g` or `-cg` added to the V compilation options ?

**Comment by BenStigsen** [comment]
It's way too long to copy paste in here. When I don't use `-cg` or `-g` it keeps infinitely giving errors for ever. But with the flag, I get an error that's more than 130000 characters.

[error.txt](https://github.com/vlang/v/files/6840381/err.txt)

**Comment by BenStigsen** [comment]
I just took at look at the some of the error, it's basically repeating forever but is getting cut off.

**Comment by JalonSolov** [comment]
I just tried the same code on my system, and it worked as expected - no access violations, etc.
```v
PS D:\> cat download.v
import net.http

fn main() {
        // This works perfectly fine
        mut title := 'Directionless'
        http.download_file('https://freemusicarchive.org/track/Broke_For_Free_-_Directionless_EP_-_01_Night_Owl/download', './music/${title}.mp3') ?

        // This does not:
        title = 'Birthday'
        http.download_file('https://freemusicarchive.org/track/Its_Your_Birthday_1839/download', './music/${title}.mp3') ?
}
PS D:\> v run download.v
PS D:\> ls music

    Directory: D:\music

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           7/19/2021    09:37        1156598 Birthday.mp3
-a---           7/19/2021    09:37        8054458 Directionless.mp3

PS D:\>
```
This tells me the problem has either been fixed recently, or is something common to your systems.

**Comment by danieldaeschle** [comment]
> hm, that stacktrace looks very weird - `net__split_address` does not call `new_tls_context` .. Can you try the same, but with `-g` or `-cg` added to the V compilation options ?

```
➜ v git:(master) v -g -cc msvc run main.v
Unhandled Exception 0xC0000005
29: strnicoll_l                ?? : address = 0x20f9b12a270
28: strnicoll_l                ?? : address = 0x20f9b129f00
27: strnicoll_l                ?? : address = 0x20f9b12a310
26: strnlen                    ?? : address = 0x20f9b12a400
25: _p__commode                ?? : address = 0x20f9b12a5e0
24: _p__commode                ?? : address = 0x20f9b12a4a0
23: _p__commode                ?? : address = 0x20f9b12a810
22: _p__commode                ?? : address = 0x20f9b129dc0
21: _p__commode                ?? : address = 0x20f9b12a7c0
20: _stdio_common_vsprintf     ?? : address = 0x20f9b12a450
19: _vsnprintf_l               C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h:1390
18: _vsprintf_l                C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h:1464
17: sprintf                    C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stdio.h:1788
16: https_make_request         C:\Users\Daniel\Projects\v\thirdparty\vschannel\vschannel.c:760
15: request                    C:\Users\Daniel\Projects\v\thirdparty\vschannel\vschannel.c:150
14: net__http__Request_ssl_do  C:\Users\Daniel\Projects\v\vlib\net\http\backend_windows.c.v:21
13: net__http__Request_method_and_url_to_response  C:\Users\Daniel\Projects\v\vlib\net\http\request.v:95    
12: net__http__Request_do      C:\Users\Daniel\Projects\v\vlib\net\http\request.v:57
11: net__http__fetch           C:\Users\Daniel\Projects\v\vlib\net\http\http.v:116
10: net__http__fetch_with_method  C:\Users\Daniel\Projects\v\vlib\net\http\http.v:137
9 : net__http__get             C:\Users\Daniel\Projects\v\vlib\net\http\http.v:43
8 : net__http__download_file   C:\Users\Daniel\Projects\v\vlib\net\http\download.v:9
7 : main__main                 C:\Users\Daniel\Projects\v\main.v:11
6 : wmain                      C:\Users\Daniel\AppData\Local\Temp\v\main.12463362310428250628.tmp.c:1000438
5 : invoke_main                d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:91
4 : __scrt_common_main_seh     d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
3 : __scrt_common_main         d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331
2 : wmainCRTStartup            d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_wmain.cpp:17
1 : BaseThreadInitThunk        ?? : address = 0x20f9fcd96d0
0 : RtlUserThreadStart         ?? : address = 0x20f9fcd9bd0
```

**Comment by BenStigsen** [comment]
What does this tell us?

**Comment by danieldaeschle** [comment]
Just for someone else to further debug it because I have no clue.

**Comment by JalonSolov** [comment]
Unfortunately, the only ones who might be able to debug it will be the ones who are seeing it fail.

I can create a "debug" version of a few files, with extra print statements to try to trace the contents of various values, but you would have to use those file, compile the code, then run it.  And "hope" it fails again so we get useful data.

Sometimes just adding a print statement makes things work, so it may be self-defeating to add them.  However, it is about the only way to narrow down the problem without you giving me remote access to your machine.

**Comment by mcastorina** [comment]
I'll try debugging it. The error reproduces on my Window's machine with the sample program.

**Comment by mcastorina** [comment]
I've narrowed it down to here:

https://github.com/vlang/v/blob/master/thirdparty/vschannel/vschannel.c#L760

I believe this is a format string vulnerability and should be changed to `sprintf(pbMessage, "%s", req)`.

I tested the change locally and it successfully downloads the files.

**Comment by BenStigsen** [comment]
Fixed on my end too. Thank you very much! Now I can finish the rest of my project, this was all that was holding it back.

**Comment by medvednikov** [comment]
Great, thanks @mcastorina
