### ISSUE TITLE
Incorrect printing of `?` token's value

### ISSUE THREAD

**Issue by bumbread** [vlang/v#10720]
**V version:** V 0.2.2 `47bf644`, timestamp: 2021-07-09 03:27:16 +0300
**OS:** Linux, Ubuntu 20.04.2 LTS

**What did you do?**

fn main()
{
	x(?)
}

**What did you expect to see?**

Error message:

```
$ v run main.v
main.v:3:4: error: unexpected token `?`
```
 
**What did you see instead?**

Error message with empty '' pair
```
$ v run main.v
main.v:3:4: error: unexpected token ``
```

**Comment by JalonSolov** [comment]
The position is correct, the only thing wrong is that it didn't put the correct character between the quotes:
```
foo.v:3:3: error: unexpected token ``
    1 | fn main()
    2 | {
    3 | x(?)
      |   ^
    4 | }
```
