### ISSUE TITLE
Calling `main()` from `main` causes "unhandled exception" / Compiler allows recursive call of `main`

### ISSUE THREAD

**Issue by bumbread** [vlang/v#10736]
**V version:** V 0.2.2 44e78a6
**OS:** windows, Microsoft Windows 10 Home Single Language v19042 64-bit

**What did you do?**

```
fn main() {
  mut x := main
  x()
}
```

**What did you expect to see?**

Either a successfully compiled non-terminating program, or a compiler error saying I can not assign `main` function pointer to a variable.
 
**What did you see instead?**

```
$ v run main.v
Unhandled Exception 0xC00000FD
```

**Comment by KeitoTobi1** [comment]
i have same problem.

**Comment by medvednikov** [comment]
This is allowed in other languages, like Go.

No need in complicating the compiler by handling this.
