### ISSUE TITLE
Sum types don't work with function types

### ISSUE THREAD

**Issue by bumbread** [vlang/v#10740]
**V version:** V 0.2.2 44e78a6
**OS:** windows, Microsoft Windows 10 Home Single Language v19042 64-bit

**What did you do?**

```
type F = fn(string)
type T64 = int | F

mut object_list := []T64{}
object_list << 3
object_list << println

dump(object_list)
```

**What did you expect to see?**

An dump of object list containing the number 3 and `println` function (its address)

Or a compiler error explicitly saying that sum types do not support functions.
 
**What did you see instead?**

Silent cryptic error message:

```
main.v:9:16: error: cannot append `println` to `[]T64`
    7 | mut object_list := []T64{}
    8 | object_list << 3
    9 | object_list << println
      |                ~~~~~~~
```

**Comment by yuyi98** [comment]
```vlang
type Func = fn (string)

type T64 = Func | int

fn main() {
	mut object_list := []T64{}
	object_list << 3
	object_list << Func(println)

	dump(object_list)
}

PS D:\Test\v\tt1> v run .
[.\\tt1.v:10] object_list: [T64(3), T64(fn (string))]
```

**Comment by bumbread** [comment]
@yuyi98 so it only doesn't work in script mode, correct?

**Comment by yuyi98** [comment]
I think we should use `Func(println)`.

**Comment by bumbread** [comment]
Ah, I see. I wonder why typechecker doesn't see the type of println as `fn(string)`. It should as far as I know.

**Comment by danieldaeschle** [comment]
`T64` holds `Func` not `fn (string)`
