### ISSUE TITLE
Strange characters in generic syntax?

### ISSUE THREAD

**Issue by mindplay-dk** [vlang/v#1075]
I came across [this](https://vlang.io/docs#generics) section in the docs:

![image](https://user-images.githubusercontent.com/103348/60978161-0559b180-a331-11e9-98a5-ab2ca9358d59.png)

What are these characters? Some sort of unicode symbol?

"For readability"? These characters probably aren't available in the monospace font you're using on the page, and I'm guessing they're not widely available - and they break vertical alignment, which definitely doesn't help readability.

I'm not sure what the point of it is? I don't see any practical reason to get very creative with syntax that is widely used for generics in other languages.

If someone prefers angle brackets with a different look, they can simply use a different font, can't they? 🤷‍♂️

**Comment by medvednikov** [comment]
Agreed, removed.
