### ISSUE TITLE
How do I use runtime reflection with functions?

### ISSUE THREAD

**Issue by elliotchance** [vlang/v#10759]
```v
fn add(a int, b int) int {
	return a + b
}

fn call(f any) {
	// How can I introspect f to pass in
	// args and receive the return value?
}

fn main() {
	println(add(5, 3))
	call(add)
}
```

**Comment by Cons-Cat** [comment]
```v
fn add(a int, b int) int {
	return a + b
}

fn call(f fn (int, int) int) {
	//
}

fn main() {
	println(add(5, 3))
	call(add)
}
```

**Comment by elliotchance** [comment]
I wasn't really clear on my question. `call` should not know the definition of the function, it should be able to introspect it can call it at runtime, like in Go:

```go
package main

import (
	"fmt"
	"reflect"
)

func add(a int, b int) int {
	return a + b
}

func call(f interface{}) {
	// Let's assume we have already checked to see the number of args.
	results := reflect.ValueOf(f).Call([]reflect.Value{
		reflect.ValueOf(5),
		reflect.ValueOf(3),
	})
	fmt.Println(results[0].Interface())
}

func main() {
	fmt.Println(add(5, 3))
	call(add)
}
```

**Comment by JalonSolov** [comment]
V supports compile-time reflection.  It does not support runtime reflection.  Runtime reflection usually requires a runtime (which V does not supply), and it can be quite slow (which V does not want to be).

**Comment by Cons-Cat** [comment]
At least this works, which covers some of the same use case
```v
fn add(a int, b int) int {
	return a + b
}

fn call<T>(f T) {
	results := f(5, 3)
	println(results)
}

fn main() {
	println(add(5, 3))
	call(add)
}
```

**Comment by elliotchance** [comment]
> V supports compile-time reflection. It does not support runtime reflection. Runtime reflection usually requires a runtime (which V does not supply), and it can be quite slow (which V does not want to be).

Is V ever going to support runtime reflection of anything? What about arrays that may contain mixed fundamental types?

**Comment by JalonSolov** [comment]
It is impossible to say whether it will _ever_ support either of those, but for now, neither one is on any roadmap I've seen.
