### ISSUE TITLE
Typedefs appearing in wrong order

### ISSUE THREAD

**Issue by jaddison06** [vlang/v#10758]
**V version:** V 0.2.2 0ac0ab6
**OS:** linux, elementary OS 5.1.7 Hera

I'm using a fixed-size array of `u8`s. Cgen generates this typedef:
`typedef u8 Array_fixed_u8_12 [12];`

However, this comes **before** the typedef for u8, so GCC gives me this error message:
`error: unknown type name ‘u8’`

I think this just needs a reordering.

**Comment by shadowninja55** [comment]
u8 is not a type in v, you are looking for byte.

**Comment by jaddison06** [comment]
my bad!

**Comment by shadowninja55** [comment]
> my bad!

wait...i may be mistaken actually. seems `u8` is a type sorry, you can reopen this.

**Comment by danieldaeschle** [comment]
There is no u8, only i8: https://github.com/vlang/v/blob/master/doc/docs.md#primitive-types
