### ISSUE TITLE
Reflection Else Branch Does Not Evaluate

### ISSUE THREAD

**Issue by Cons-Cat** [vlang/v#10767]
**V version:** V 0.2.2 477d442.9d241f7
**OS:** Void Linux

**What did you do?**
`cat dump.v`
```v
module main

const condition = false

fn main() {
	$if condition {
		println('true')
	} $else {
		println('false')
	}
}
```

**What did you expect to see?**
The program prints out `false`. Or maybe a compiler error.
 
**What did you see instead?**
Nothing is printed out at all. If `condition` is `true`, then it prints out true correctly.

**Comment by yuyi98** [comment]
I think this usage is not support in comptime.

**Comment by Cons-Cat** [comment]
But the `true` branch still works as expected, and in my opinion this is an extremely important feature. A common programming I see in C++ is people have a bunch of global variables that enable or disable different features like compiling with / without networking support or disabling various features to make debugging problems easier. Globally scoped immutable variables that can control conditional compilation would allow zero-cost build configuration.

**Comment by Larpon** [comment]
You can achieve this by passing `-d flag`. And check in code with `$if flag?`.

**Comment by Cons-Cat** [comment]
``

> You can achieve this by passing `-d flag`. And check in code with `$if flag?`.

That's fair enough! I think it would be less friction to have some bools in the main file, but maybe less obvious, so I can see how using compiler flags would make more sense for V. There are other reasons this is useful in C++ for metaprogramming, but I don't think they can be expressed in V anyways right now. Should this be a compiler error instead of a silent bug, though?

**Comment by felipensp** [comment]
```V
	$if condition ? {
		println('true')
	} $else {
		println('false')
	}
```

Works fine.
