### ISSUE TITLE
Array Slices

### ISSUE THREAD

**Issue by r-k-o** [vlang/v#1077]
Hi,
I think array slices would be a perfect feature for this neat language.
an example:

lastname := wholename[10..wholename.len]
somenumbers := numbers[0..10]

thanx

**Comment by medvednikov** [comment]
V already has slices: `.slice(start, end)`, `.left(pos)`, `.right(pos)`.

**Comment by r-k-o** [comment]
.slice(start, end) does not exist and the .. syntax would be nice sugar

**Comment by nedpals** [comment]
@r-k-o You meant that the function is not working? Well it does work.

```golang
nums := [0, 1, 2]
sliced := arr.slice(1, nums.len)

println(sliced.str())
// [1, 2]
```

**Comment by medvednikov** [comment]
I personally find `nums.right(pos)` simpler and more readable than `nums[pos:]`, but it may be just me.

**Comment by iredmail** [comment]
The name “right()” doesn’t indicate the range. Is it from left to right and stops at the position? Or from right to left and stops at the position? Or just the one element in the given position?

[pos:] is very clear in this case because it indicates the range is from pos to the rest of right hand side.

Btw, it’s clear especially to python users.

**Comment by ntrel** [comment]
I found the `right` function confusing, as I expected it to take the number of elements as an argument, not an index. (Visual) Basic has a `Right` function that takes the number of elements:
https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/right-function

`[pos:]` syntax is fine, but unless we overload slice syntax, we'll need generic functions for containers. I'm happy just with functions. I would suggest deprecating `right` at least, and calling them `take`/`drop` instead of `left`/`right`. `take`/`drop` are used by D, Scala, Haskell.

**Comment by medvednikov** [comment]
I agree, `right` and `left` are bad names. I like `take` and `drop`.

**Comment by ntrel** [comment]
@iredmail
Take n characters, drop n characters. Left and right would probably be OK names if they took n characters. Is there a reason why take and drop, each with a `n int` parameter would be confusing? These are common generic function names.

**Comment by iredmail** [comment]
My question is: can you understand what it does by just reading the function name?

You already know some programming languages that use “take” and “drop”, but what about other people they don’t know these programming languages? It’s confused a lot. 

Why not just use a name clearly indicate what the function does? we've been told many times (and tell others) to pick up a clear variable/function/class/... name to make code more readable?

Please focus on the function name itself.

**Comment by Omnuchka** [comment]
What will be if I want take slice between 3 and 8 element, i must use 2 function...

**Comment by iredmail** [comment]
> What will be if I want take slice between 3 and 8 element, i must use 2 function...

I suppose it's `.slice(start, end)`, mentioned in Alex's comment:
https://github.com/vlang/v/issues/1077#issuecomment-510213790

**Comment by Omnuchka** [comment]
.slice(start, end) - cool

**Comment by medvednikov** [comment]
if we remove that, it becomes somewhat verbose:

`numbers.right(5)` => `numbers.slice(5, numbers.len - 1)`

**Comment by iredmail** [comment]
It's not about removing it, but replace it with a better syntax: shorter, clearer, easier to understand.

```
numbers.right(5)
```
vs
```
numbers[5:]
```

**Comment by medvednikov** [comment]
I and many people don't find `numbers[5:]` and `numbers[5:]` easier to parse and understand.

**Comment by Omnuchka** [comment]
> I and many people don't find `numbers[5:]` and `numbers[:5]` easier to parse and understand.
> 
> Can you say within a second which one takes the left part, and which one the right part?

YES, but why not using only : numbers.slice(5, numbers.len - 1)     without=> .right

**Comment by iredmail** [comment]
@medvednikov

> Can you say within a second which one takes the left part, and which one the right part?

The syntax is “numbers[start:end]”, if “start” is omitted or set to 0, it means slice from first element. If “end” is omitted or set to -1, it means slice to the end. This is same as python syntax.

**Comment by joe-conigliaro** [comment]
@medvednikov with array.left() & array.right() I noticed that if the index is out of range it returns the original array. Do you think this is correct or should it return an empty array?

**Comment by medvednikov** [comment]
> I noticed that if the index is out of range it returns the original array. Do you think this is correct or should it return an empty array?

It should panic with `runtime error: slice bounds out of range`, will fix.

The new syntax I'm now considering is

```
numbers[start..end]
numbers[start..]
numbers[..end]
```

Seems to be a bit more readable than with `:`, and we already have `..` ranges in for loops.

What do you think?

**Comment by whoizit** [comment]
@medvednikov this is the same as topic starter

**Comment by medvednikov** [comment]
Indeed :)

**Comment by Omnuchka** [comment]
> @medvednikov this is the same as topic starter

no

**Comment by Omnuchka** [comment]
> > I noticed that if the index is out of range it returns the original array. Do you think this is correct or should it return an empty array?
> 
> It should panic with `runtime error: slice bounds out of range`, will fix.
> 
> The new syntax I'm now considering is
> 
> ```
> numbers[start..end]
> numbers[start..]
> numbers[..end]
> ```
> 
> Seems to be a bit more readable than with `:`, and we already have `..` ranges in for loops.
> 
> What do you think?

best solution, thk

**Comment by iredmail** [comment]
> The new syntax I'm now considering is
> 
> ```
> numbers[start..end]
> numbers[start..]
> numbers[..end]
> ```
> 
> Seems to be a bit more readable than with `:`, and we already have `..` ranges in for loops.
> 
> What do you think?

`..` is ok, the syntax is clear now. Thanks. :)

**Comment by l8atnight** [comment]
My request is exactly as in it is Modula and i am glad that you see the advantages. It is easy to read and easy to comprehend.

**Comment by Richiban** [comment]
I can't find any mention of ranges `..` in the docs; are they currently inclusive or exclusive? I know that this is a bit of a tabs/spaces-style argument from language to language, but I'd like to know whether

```v
for i in 1..5 {
    println(i)
}
```

prints `1 2 3 4` or `1 2 3 4 5`.

Also, how will the `[x..y]` syntax be implemented? Will it only work on arrays or on custom types as well? Would it just be syntax sugar for a `slice` method?

**Comment by Delta456** [comment]
@Richiban 1..5 prints `1 2 3 4`. They aren't in docs because they are outdated with current speed of development.

I think `[x..y]` would be done like `1..5`. I am not sure about the latter one.

**Comment by medvednikov** [comment]
Exclusive, a..b will replace .slice()

**Comment by r-k-o** [comment]
I am glad you do that. it is easier to read and more comprehendable  the find one of n lib functions. After all the syntax of the language should be easy.
