### ISSUE TITLE
v -gc says it uses boehm_full_opt as default GC, but does it really?

### ISSUE THREAD

**Issue by lucasrdrgs** [vlang/v#10783]
If I run `v -gc run`, it shows a list of possible garbage collectors and it says `-gc boehm` is the default GC-mode, "currently boehm_full_opt" (sic).

However, I wrote a library to read large csv files and store them as `[][]string{}`, and if I do not specify -gc (assuming the default one is indeed boehm full opt), RAM usage skyrockets up to 5 GB for a 20000 line csv with two columns: sentences with a maximum length of 280 chars and target which is a single character.

What I'm trying to say is, loading that much stuff into memory does use some space. 20000 * 281 bytes or so, in fact. That's around 5.6 MB. Since I also use some other variables here and there due to being too lazy to optimize the code I'm running, the usage is definitely higher than 5.6 MB but definitely not anywhere close to 5 GB!

**When I do specify -gc boehm_full_opt**, RAM usage only goes up to about 150 MB.

My question is, does V still use boehm_full_opt as the default GC? It doesn't really seem like it. If it's outdated info, please update it! Thanks in advance.

**Comment by danieldaeschle** [comment]
What it means is that `-gc boehm` is equivalent `-gc boehm_full_opt` (`boehm` defaults to `boehm_full_opt`).

If you don't specify any gc nothing is used currently (in future autofree will be used).
