### ISSUE TITLE
Cannot call methods on map literals

### ISSUE THREAD

**Issue by div72** [vlang/v#10780]
**V version:** 0.2.2 02f0a30
**OS:** Arch Linux

**What did you do?**
`v -prod test.v`
```v
fn main() {
	a := 1 in map{
	1: 1
}.keys().map(map{
	1: 1
}[it])
	println(a)
}
```

**What did you expect to see?**
```v
true
```
 
**What did you see instead?**
```
/tmp/v/test.7091847091740794489.tmp.c:10144:39: error: lvalue required as unary ‘&’ operand
10144 |         Array_int _t1_orig = map_keys(&new_map_init(&map_hash_int_4, &map_eq_int_4, &map_clone_int_4, &map_free_nop, 1, sizeof(int), sizeof(int), _MOV((int[1]){1, }), _MOV((int[1]){1, })));
      |                                       ^
...
```

**Comment by JalonSolov** [comment]
Can you give a valid use-case for something so convoluted looking?

Of course, it should give a nice V error instead of a C error, but I'm wondering if it should be allowed at all.

**Comment by div72** [comment]
@JalonSolov That convoluted looking thing is a result of transpiled code that's meant to be map values. Since V lacks a values method for maps, I changed it to use keys with the `array.map` method to simulate `map.values`.

Regardless prohibiting method usage of map literals is both unnecessary check in the checker and goes against one-way rule since other literals doesn't have this problem.

**Comment by yuyi98** [comment]
It can work on win10.

```vlang
fn main() {
	a := 1 in map{
		1: 1
	}.keys().map(map{
		1: 1
	}[it])
	println(a)
}

PS D:\Test\v\tt1> v run .
true
```

**Comment by div72** [comment]
@yuyi98 It works with tcc, not with gcc and clang. Sorry for not clarifying.
