### ISSUE TITLE
mqtt lib request

### ISSUE THREAD

**Issue by xinchou** [vlang/v#10781]
Simple, fast, safe, compiled, Suitable for the Internet of Things.
mqtt lib needed, or please translate a mqtt c  lib to v code.

**Comment by sarjsheff** [comment]
I write nats.io client. Nats may work as mqtt server. [Nats.v](https://github.com/sarjsheff/natsv)

**Comment by medvednikov** [comment]
c2v is out now, can be translated

**Comment by trollkarlen** [comment]
Tried convert paho without success
https://github.com/eclipse/paho.mqtt.c

``` bash
$ v run $HOME/.vmodules/c2v -d trace_verbose paho.mqtt.c/src
C to V translator 0.3.1
"paho.mqtt.c/src" is a directory, processing all C files in it recursively...

  translating ./MQTTProtocolClient.c ... C++ top level
&Node{
    id: '0x7fc2c18c4e98'
    kind_str: 'EmptyDecl'
    location: NodeLocation{
        offset: 19335
        file: ''
        line: 425
        source_file: SourceFile{
            path: './Socket.h'
        }
        spelling_file: SourceFile{
            path: ''
        }
    }
    range: Range{
        begin: Begin{
            spelling_file: SourceFile{
                path: ''
            }
        }
    }
    previous_declaration: ''
    name: ''
    ast_type: AstJsonType{
        desugared_qualified: ''
        qualified: ''
    }
    class_modifier: ''
    tags: ''
    initialization_type: ''
    value: ''
    value_number: 0
    opcode: ''
    ast_argument_type: AstJsonType{
        desugared_qualified: ''
        qualified: ''
    }
    array_filler: []
    declaration_id: ''
    label_id: ''
    is_postfix: false
    ast_line_nr: 0
    inner: []
    ref_declaration: RefDeclarationNode{
        kind_str: ''
        name: ''
        kind: BAD
    }
    kind: BAD
    current_child_id: 0
    is_builtin_type: false
    redeclarations_count: 0
}
```
Added a print because the error messages before this was very very sparse :)

**Comment by JalonSolov** [comment]
For problems with the c2v translation, please open issues in the https://github.com/vlang/c2v repo.

**Comment by trollkarlen** [comment]
I can do that. 
But it needs to be here also because this was closed due to existence of a tool that maybe maybe could solve this, but it could not.

**Comment by JalonSolov** [comment]
While it may be an issue for some, nobody who knows how to do it has stepped up and made such a lib for V.  If one was translated to V using c2v, that would be fine, but it's still a c2v issue, not an issue for V itself.
