### ISSUE TITLE
It is possible to mutate an immutable value through an interface 

### ISSUE THREAD

**Issue by spacesinmotion** [vlang/v#1081]
**V version:0.1.13** 
**OS:linux** 

**What did you do?**
I change a struct member with an immutable function of a mutable variable by using an interface:
```go
struct Int {
pub mut:
  val int
}

fn (ic mut Int) make_truth() {
  ic.val = 42
}

interface TruthMaker {
  make_truth()
}

fn call(vc TruthMaker) {
  vc.make_truth()
}

fn test_interface_with_parameter() {
  ic := Int{0} // immutable 
  call(ic)     // is changed here
  assert ic.val == 42
}
```

**What did you expect to see?**
an compiler error:
``` ic is immutable```
 
**What did you see instead?**
a valid test

**Comment by spacesinmotion** [comment]
I think here is concept missing how to define interface method as mutable or not... something like:

```go
interface TruthMaker {
  mut make_truth()
}
```

**Comment by medvednikov** [comment]
Thanks for your bug reports on interfaces.

They are at a very early stage and need a lot of work. Hopefully I'll be able to fix them this month.

**Comment by alfclement** [comment]
Even easier:

```
fn main() {
	a:=3
	pa:=&a
	println(a)
	println(*pa)
	mut pb := pa
	*pb=4
	println(a)
}
```

**Comment by ntrel** [comment]
@alfclement That's #41, this issue is separate IMO.

**Comment by spytheman** [comment]
> Even easier:
> 
> ```
> fn main() {
> 	a:=3
> 	pa:=&a
> 	println(a)
> 	println(*pa)
> 	mut pb := pa
> 	*pb=4
> 	println(a)
> }
> ```

in newer versions of V, this produces:
```
0[17:17:46]delian@nemesis: /v/pv $ ./v run m.v 
m.v:7:5: error: modifying variables via dereferencing can only be done in `unsafe` blocks
    5 |     println(*pa)
    6 |     mut pb := pa
    7 |     *pb=4
      |        ^
    8 |     println(a)
    9 | }
1[17:17:49]delian@nemesis: /v/pv $
```
