### ISSUE TITLE
rendering persian is wrong

### ISSUE THREAD

**Issue by metif12** [vlang/v#10825]
in persian characters have "Contextual forms".
also persian is right to left so first character goose right not left.
[https://en.wikipedia.org/wiki/Persian_alphabet](https://en.wikipedia.org/wiki/Persian_alphabet)
i think rendering would be wrong in arabic too.
i also open this [issue](https://github.com/vlang/ui/issues/362#issue-946044205) in ui repo but i thinck it is more related to v's gx or freetype or ttf module

**V version:**
OS: linux, Linux version 5.10.46-1-lts (linux-lts@archlinux) (gcc (GCC) 11.1.0, GNU ld (GNU Binutils) 2.36.1) #1 SMP Wed, 23 Jun 2021 16:18:42 +0000
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
CC version: cc (GCC) 11.1.0

getwd: /home/mahdi
vmodules: /home/mahdi/.vmodules
vroot: /home/mahdi/repos/v
vexe: /home/mahdi/repos/v/v
vexe mtime: 2021-07-16 07:36:48
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 cbe4ac7

Git version: git version 2.32.0
Git vroot status: weekly.2021.26-151-gcbe4ac70
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81

**UI version:**
Name: ui
Version: 0.0.4
Description: V UI is a cross-platform UI toolkit for Windows, macOS, Linux, and soon Android, iOS and the web (JS/WASM).
Homepage: https://github.com/vlang/ui
Author: medvednikov
License: GPL3 + commercial
Location: /home/mahdi/.vmodules/ui
Requires: 

**OS:** 
Linux lenovo 5.10.46-1-lts #1 SMP Wed, 23 Jun 2021 16:18:42 +0000 x86_64 GNU/Linux

**What did you do?**
```v
import ui

fn main() {
	ui.message_box('سلام دنیا')
}
```

**What did you expect to see?**
![image](https://user-images.githubusercontent.com/26581685/125911619-416fa1e3-9f14-40a4-b1f4-c1b5ff4a05a4.png)

 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/26581685/125911108-e40ffc36-1c52-467b-abaa-26e8ac2ba878.png)

**Comment by Dialga** [comment]
This will be fixed in vlang/ui, not here.
