### ISSUE TITLE
number type max and min values

### ISSUE THREAD

**Issue by ambye85** [vlang/v#10849]
I was trying to find a handy way to get the max value of a `u32`. However, I couldn't find anything in the GitHub docs or in vlib docs. Does such a utility exist? If not, could we get this added in?

**Comment by JalonSolov** [comment]
A handy trick...
```
println(u32(-1))
```
result is
```
4294967295
```
This works because the max value is the value with all bits set to one, and -1 does that for unsigned values.

**Comment by ambye85** [comment]
Thanks.
