### ISSUE TITLE
$if conditional emits an empty block 

### ISSUE THREAD

**Issue by bbarker** [vlang/v#10846]
OS: linux, Ubuntu 20.04.2 LTS
Processor: 8 cpus, 64bit, little endian, Intel(R) Xeon(R) CPU E5-1630 v4 @ 3.70GHz
CC version: clang version 7.1.0 (tags/RELEASE_710/final)

getwd: /home/brandon/workspace/v
vmodules: /home/brandon/.vmodules
vroot: /home/brandon/workspace/v
vexe: /home/brandon/workspace/v/v
vexe mtime: 2021-07-17 16:52:54
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 fc8a8e3

Git version: git version 2.30.1
Git vroot status: weekly.2021.28-62-gfc8a8e3b-dirty (1 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 333c14de

**What did you do?**

I'm not clear on whether it is expected behavior that this code in `vlib/os/os_nix.c.v`:

```v
$if !haiku {
  #include <sys/ptrace.h>
}    
```

generates the following:

```c
#if !defined(__haiku__)
#endif
```

when doing `./v -os cross -o v.c cmd/v`

The `#include` is missing

**What did you expect to see?**

```c
#if !defined(__haiku__)
  #include <sys/ptrace.h>
#endif
```
 
**What did you see instead?**

```c
#if !defined(__haiku__)
#endif
```

**Comment by bbarker** [comment]
BTW, I found the emitted code difference by running `diff vc/v.c v.c` and seeing:

```
23018a23018,23019
> #if !defined(__haiku__)
> #endif
```

**Comment by LouisSchmieder** [comment]
yeah that's a general thing in compile time here. Because we check if every branch needs to get generated at your current system

**Comment by bbarker** [comment]
@LouisSchmieder Thanks for the reply - since I'm making this change to target a different system from the one I'm working on, what is the suggested way to handle this? The targeted system (Haiku OS) is one that currently seems to have issues building V, which is the reason for me working on changes like this.

**Comment by bbarker** [comment]
Updating with some advice I learned about on discord, thanks Gladear (will check up on this soon):

> Try `-os haiku`.  Also `-os cross` will generate all branches, whatever the OS

**Comment by felipensp** [comment]
Not a bug. Thanks.
