### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by marcelo-antonio-nunes** [vlang/v#10856]
como faço para filtrar so numeros de uma string ex: "8475489y94587587hhh85.lt55666" alguem pode me ajudar, em pytho uso is_numeric, mas em v ta dificil

**Comment by JalonSolov** [comment]
https://modules.vlang.io/index.html#byte.is_digit

```v
s := '8475489y94587587hhh85.lt55666'

for c in s {
        println('${c.ascii_str()}: ' + if c.is_digit() { 'sim' } else { 'não' })
}
```
