### ISSUE TITLE
'OPENSSL_INIT_LOAD_SSL_STRINGS' undeclared

### ISSUE THREAD

**Issue by akin520** [vlang/v#10869]
**V doctor:**
```
OS: linux, Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Mon Oct 19 16:18:59 UTC 2020 (VM)
Processor: 4 cpus, 64bit, little endian, Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
CC version: cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

getwd: /data/code/go-mod/gospider
vmodules: /root/.vmodules
vroot: /data/code/v/v
vexe: /data/code/v/v/v
vexe mtime: 2021-07-19 05:49:12
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 83b0a80

Git version: git version 2.31.0
Git vroot status: weekly.2021.28-76-g83b0a80f (1 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 333c14de
```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg /data/code/v/v/cmd/tools/vpm.v`
See attached file `/data/code/v/v/cmd/tools/vpm.v`

**What did you expect to see?**

**What did you see instead?**
```
==================
/tmp/v/vpm.9245342143351400692.tmp.c:21646: warning: implicit declaration of function 'OPENSSL_init_ssl'
/tmp/v/vpm.9245342143351400692.tmp.c:21646: error: 'OPENSSL_INIT_LOAD_SSL_STRINGS' undeclared
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

**Comment by shadowninja55** [comment]
can you run `openssl version` in terminal?

**Comment by danieldaeschle** [comment]
Is this a similar issue like https://github.com/vlang/v/issues/10845?

**Comment by shadowninja55** [comment]
i'm assuming this is due to outdated openssl

**Comment by spaceface777** [comment]
> Is this a similar issue like https://github.com/vlang/v/issues/10845?

yes, they're duplicates, one of them should be closed.

> i'm assuming this is due to outdated openssl

yes, exactly :)

V requires openssl **1.1.x**; previous versions will not work, so you'll need to install that from you package manager (or build it from source if that's unavailable).

**Comment by danieldaeschle** [comment]
Since when does V requires openssl? I think this dependency should be removed... or be replaced with something internal.

**Comment by medvednikov** [comment]
`net` depends on openssl

writing a tls client is a huge amount of work

This is a 12 year old OS, it has an old version of openssl.
