### ISSUE TITLE
Struct fields in ORM update statements don't work and function order matters

### ISSUE THREAD

**Issue by HankG** [vlang/v#10864]
V full version: V 0.2.2 677ef7b
OS: macos, macOS, 11.4, 20F71
Processor: 8 cpus, 64bit, little endian, Apple M1
CC version: Apple clang version 12.0.5 (clang-1205.0.22.11)

**What did you do?**
Using the ORM update statement with a struct field used on the assignment side as well as the where clause side.

```v
module main

import sqlite

struct User {
	id   int [primary; sql: serial]
	name string
	age  int
}

// Switching the order of these functions allows this to build

fn update_user_cgen_error(db sqlite.DB, user_update User) {
	sql db {
		update User set age = user_update.age where id == user_update.id
	}
}

fn update_user_works(db sqlite.DB, user_update User) {
	new_age := user_update.age
	sql db {
		update User set age = new_age where id == user_update.id
	}
}

fn main() {
	println('Hello World!')
}
```

**What did you expect to see?**
a. Being able to use fields of structs in the Update statement like we can on the Where side 
b. Consistency in compilation regardless of function order 

 
**What did you see instead?**
a. generates a `cgen error: bad sql type=0` error as pasted. 
b. The error can be made to go away if the function order in the file is swapped.

**Comment by HankG** [comment]
There may be more wrong that I originally wrote. The Update method never runs correctly even if I can get it to compile.

This below compiles but at run time it throws a `near ",": syntax error` error prompt but continues on as if it actually did the update (or I have
```v
struct User {
	id   int [primary; sql: serial]
	name string
	age  int
}

... 

fn update_user(db sqlite.DB, user_update User) {
	new_name := user_update.name
	new_age := user_update.age
	sql db {
		update User set name = new_name, age = new_age where id == user_update.id
	}
}
```

If I convert the ORM code to explicitly set those variable like this:
```v
	sql db {
		update User set name = 'Name', age = 35 where id == user_update.id
	}
```
Then I get a compile time error of: `cgen error: bad sql type=0 ident_name="Name"`

**Comment by LouisSchmieder** [comment]
```v
module main

import sqlite

struct User {
	id   int [primary; sql: serial]
	name string
	age  int
}

// Switching the order of these functions allows this to build

fn update_user_cgen_error(db sqlite.DB, user_update User) {
	sql db {
		update User set age = user_update.age, name = user_update.name where id == user_update.id
	}
}

fn main() {
	mut db := sqlite.connect(':memory:') or { panic(err) }
	sql db {
		create table User
	}
	mut user := User{}
	sql db {
		insert user into User
	}
	update_user_cgen_error(db, User{
		name: 'test'
		age: 10
		id: 1
	})
	user = sql db {
		select from User where id == 1
	}
	println(user)
}
```

prints now ```
User{
    id: 1
    name: 'Test'
    age: 10
}
```
