### ISSUE TITLE
Can't used a fixed sized array as a return value

### ISSUE THREAD

**Issue by lancethepants** [vlang/v#10879]
**V version:** 
**OS:** linux - Using C backend

**What did you do?**
Try to use fixed sized array as return type

**What did you expect to see?**
Program compile and run
 
**What did you see instead?**
C compiler error
```
/tmp/v/36cube.18105555941475086726.tmp.c: In function ‘main__main’:
/tmp/v/36cube.18105555941475086726.tmp.c:10169:42: error: lvalue required as unary ‘&’ operand
  memcpy((Array_fixed_int_6*)nums, (byte*)&main__set_value(nums, 0, 1), sizeof(Array_fixed_int_6));
                                          ^
/tmp/v/36cube.18105555941475086726.tmp.c: At top level:
/tmp/v/36cube.18105555941475086726.tmp.c:10173:35: error: ‘main__set_value’ declared as function returning an array
 VV_LOCAL_SYMBOL Array_fixed_int_6 main__set_value(Array_fixed_int_6 nums, int i, int v) {
                                   ^~~~~~~~~~~~~~~
/tmp/v/36cube.18105555941475086726.tmp.c: In function ‘main__set_value’:
/tmp/v/36cube.18105555941475086726.tmp.c:10177:9: warning: returning ‘int *’ from a function with return type ‘int’ makes integer from pointer without a cast [-Wint-conversion]
  return n;
         ^
...
```

So interestingly on x86_64 this compiles and runs with the native backend, albeit it initializes the starting of the array with a bunch of wacky values.  However I am doing embedded development, and with the the C backend I get the above error on different architectures.

Example:
```
fn main() {
        mut nums := [6]int{}
        nums = set_value(nums, 0, 1)
        println(nums)
}

fn set_value(nums [6]int, i int, v int) [6]int {
        mut n := nums
        n[i] = v
        return n
}
```
And understandably fixed sized multidimensional arrays don't compile either.
```
fn main() {
        mut nums := [6][6]int{}
        nums = set_value(nums, 0, 1)
        println(nums)
}

fn set_value(nums [6][6]int, i int, v int) [6][6]int {
        mut n := nums
        n[i][i] = v
        return n
}
```

**Comment by shadowninja55** [comment]
hmm this code compiles and runs for me. what os and c compiler are you using?

**Comment by lancethepants** [comment]
Yes sorry, I am using gcc compiler.
Since I am on embedded linux (arm), I am using GCC-10.3.0 compiler, no tcc available for my particular platform.
I also used Debian 10 using gcc.
`v -cc gcc test.v` or also
`v -prod test.v` will show as well.
So I guess you could say it doesn't work for production builds.

**Comment by JalonSolov** [comment]
Fixed arrays are allocated on the stack, so they can't be returned.

However, you can get a "sort-of-fixed" array by declaring it differently:
```v
mut nums := []int{cap:6}
```
2d arrays are a little trickier...
```v
mut nums := [][]int{cap:6, init:[]int{cap:6}}
```
https://github.com/vlang/v/blob/master/doc/docs.md#array-properties

**Comment by lancethepants** [comment]
Sounds good, I was thinking it either had to be a bug or perhaps is not valid code.
Interesting how tcc will compile and run it though...
Sounds like the V parser should throw an error when encountering this. People may wonder why their code suddenly breaks in production builds.

**Comment by shadowninja55** [comment]
> Sounds good, I was thinking it either had to be a bug or perhaps is not valid code.
> Interesting how tcc will compile and run it though...
> Sounds like the V parser should throw an error when encountering this. People may wonder why their code suddenly breaks in production builds.

good idea, i'll make a pr.
