### ISSUE TITLE
multi string plus memory leak

### ISSUE THREAD

**Issue by wilesun** [vlang/v#10884]
**V version:  V 0.2.2 d41a4ec
**OS: ubuntu

**What did you do?**
hello1.v
```
hello1.v

fn main() {
   a := '1'+'2'+'3'
   println(a)
}
````
hello1.c
```
VV_LOCAL_SYMBOL void main__main(void) {
	string a = string__plus(string__plus(_SLIT("1"), _SLIT("2")), _SLIT("3"));
	println(a);
	string_free(&a); // autofreed var main false
}

```
second string__plus return is not free 

**What did you expect to see?**
string__plus function may support multi parameters, it is snprintf(str,...) style

**What did you see instead?**
```
==19323== LEAK SUMMARY:
==19323==    definitely lost: 3 bytes in 1 blocks
==19323==    indirectly lost: 0 bytes in 0 blocks
==19323==      possibly lost: 0 bytes in 0 blocks
==19323==    still reachable: 0 bytes in 0 blocks
==19323==    suppressed: 0 bytes in 0 blocks
```
this is a v fault bug, vlib has many class use the string__plus,memory leak is very important !!

**Comment by medvednikov** [comment]
Good find.

**Comment by GZGavinZhao** [comment]
This has changed now to:
```c
#define _SLIT(s) ((string){.str=(byteptr)("" s), .len=(sizeof(s)-1), .is_lit=1})

VV_LOCAL_SYMBOL void main__main(void) {
	string a = _SLIT("123");
	println(a);
}
```

I'm not sure if this still leaks memory. @wilesun How did you check for memory leaks?

**Comment by JalonSolov** [comment]
Looks like `valgrind` output.

**Comment by GZGavinZhao** [comment]
Confirmed, no longer leaks V 0.2.4 4fbf3fd
