### ISSUE TITLE
Build failes in table.v

### ISSUE THREAD

**Issue by Viza74** [vlang/v#1088]
**V version:** 0.1.3
**OS:** macos

**What did you do?**
Updated the source code and tried run make

**What did you expect to see?**
v compiler builds
 
**What did you see instead?**

```
rm -f v.c v vprod
curl -Os https://raw.githubusercontent.com/vlang/vc/master/v.c
cc -std=gnu11 -w -o v v.c -lm 
./v -o v compiler
panic: table.v:645
undefined: `math.MaxU8`
make: *** [v] Error 1
```
Up to 0.1.13 the build worked flawlessly

**Comment by medvednikov** [comment]
`git pull`

**Comment by Viza74** [comment]
Hmm, I already did that, but just to make sure:

```
Zoltan-MacBook-Pro:v viza$ git pull
Already up to date.
Zoltan-MacBook-Pro:v viza$ make
rm -f v.c v vprod
curl -Os https://raw.githubusercontent.com/vlang/vc/master/v.c
cc -std=gnu11 -w -o v v.c -lm 
./v -o v compiler
panic: table.v:645
undefined: `math.MaxU8`
make: *** [v] Error 1
```

**Comment by hazohelet** [comment]
I had the same problem.
git clone again after `rm ~/.vlang` worked.
I guess it's a bug around VROOT.

**Comment by medvednikov** [comment]
VROOT will be removed today.

**Comment by Viza74** [comment]
Only deleteing VROOT did not fixed it, but deleting VROOT and cloning again did.👍
