### ISSUE TITLE
Regex: single unmatched `)` at the beginning must be syntax error

### ISSUE THREAD

**Issue by lemoncmd** [vlang/v#10886]
**V version:** V 0.2.2 11a7899
**OS:** Ubuntu 20.04.2 LTS

**What did you do?**
```v
regex(')abc') or { panic(err) }
```

**What did you expect to see?**
```
V panic:
query: )abc
err  : ^
ERROR: err_group_not_balanced
```
 
**What did you see instead?**
It unintentionally compiles.

**Comment by penguindark** [comment]
@lemoncmd can you elaborate why this query is an error for the compiler?
If the group is not opend by a `(` the group simply does not exist.

**Comment by penguindark** [comment]
just an example:
```v
import regex
fn main() {
	pattern := r')\w+'
	src := ')ciao book )table'
	mut re := regex.regex_opt(pattern) or {
		eprintln('err: $err')
		exit(0)
	} 
	res := re.find_all_str(src)
	println(res)
}
```
yield this output:
```
[')ciao', ')table']
```
That in my opinion is full legit.

**Comment by lemoncmd** [comment]
I simply cannot understand why ) in the head is allowed for simplicity ignoring consistency while simple two dots is not allowed

**Comment by penguindark** [comment]
The reason is very simple. v-regex is a very basic regex engine.
It fit in about 3K line of code, adding these features increment complexity without in my opinion add big advantages.

**Comment by lemoncmd** [comment]
Then this feature is waste of code, isn't it.
