### ISSUE TITLE
Regex: syntax error with continuous dots

### ISSUE THREAD

**Issue by lemoncmd** [vlang/v#10885]
**V version:** V 0.2.2 11a7899
**OS:** Ubuntu 20.04.2 LTS

**What did you do?**
```v
regex('..') or { panic(err) }
// 'a..', '..b', 'a..b', '.....', whatever
```

**What did you expect to see?**
Regex compiled with two continuous "any character"s.
 
**What did you see instead?**
```
V panic:
query: ..
err  : ^
ERROR: err_syntax_error
```

**Comment by lemoncmd** [comment]
what's the technical problem allowing multiple dots?

**Comment by penguindark** [comment]
The issue lay in the managing in the state machine the failing of consecutive dots, each dot encountered add a state saved on the stack of states.
They may be converted under the hood with a single dot with quantifier, but this will add code that can introduce errors in case of failing in the middle dots.
Adding this management when the same result can be achivied with quantifiers seems to my eye not a good idea.
