### ISSUE TITLE
str() for Sumtype always prints Sumtype type_name

### ISSUE THREAD

**Issue by jdonnerstag** [vlang/v#10898]
**V version:**     V version: V 0.2.2 be7c396
**OS:**     OS: windows, Microsoft Windows 10 Enterprise v19041 64-bit

**What did you do?**
If the variable is a sumtype, then V will always, not matter what, precede the str() with the sumtype type name.  With normal variables this is not the case.

```
module parser

struct Axx { a int }
pub fn (a Axx) str() string { return "Axx" }

struct Bxx { b int }
pub fn (b Bxx) str() string { return "Bxx" }

type SumAB = Axx | Bxx

struct MyStruct { x SumAB }
pub fn (x MyStruct) str() string { return x.x.str() }

fn test_str() {
	a := Axx{ a: 1 }
	assert a.str() == "Axx"

	x := MyStruct{ x: a }
	assert x.x is Axx
	assert (x.x as Axx).a == 1
	assert x.str() == "Axx"
}
```

**What did you expect to see?**
I expected the assert to pass
 
**What did you see instead?**
```
assert x.str() == 'Axx'
    Left value:
      rosie.parser.SumAB(Axx)
    Right value:
      Axx
```

**Comment by danieldaeschle** [comment]
Try `x.type_name()`

**Comment by jdonnerstag** [comment]
Hi,

I think you misunderstood. According to [Print custom types](
https://github.com/vlang/v/blob/master/doc/docs.md#printing-custom-types)
"If you want to define a custom print value for your type, simply
define a .str()
string method". This works fine, except for Sumtypes. You can define str()
for sumtype, but the generated string will ALWAYS be preceded with the
sumtype's type_name. The expected output is, that it is does not.

As a side note: if people make the effort to create test cases and try to
explain the current and expected behavior, then people also deserve that
core developer at least read it and run the test case, and not just wash it
away with an answer that clearly shows you have not even spend a second to
close it.

Unfortunately I'm not able to re-open the bug.

**Comment by spaceface777** [comment]
@jdonnerstag while you defined `str()` methods on the sumtype *variants*, you never defined a custom `str()` method on the sumtype itself. By default sumtypes (and interfaces, type aliases, etc.) are always printed as a cast, so the behavior you're seeing is working as intended.

As I said, if you do _not_ want the sumtype to be printed as a cast for whatever reason, you need to define a custom `str()` method on the _sumtype itself_. This for example makes your `assert`s pass:
```v
pub fn (s SumAB) str() string {
	return match s {
		Axx { s.str() }
		Bxx { s.str() }
	}
}
```

**Comment by danieldaeschle** [comment]
Try to do `(x.x as Axx).str()` then it works like you expect. Since a sum type is a new type it won't use the methods from it's variants.

**Comment by kahsa** [comment]
This kind of information is too valuable to be buried.
Can't we make it a FAQ by labeling it or something?

**Comment by danieldaeschle** [comment]
@kahsa what do you mean? We could make it clearer in the docs.
