### ISSUE TITLE
String index result as number instead of letter

### ISSUE THREAD

**Issue by 0verse** [vlang/v#10899]
**V version:** 
V 0.2.2 2c9f689

**OS:** 
musl-libc based linux distro 

**What did you do?**
```
fn main() {
    name := 'gandalf'
    println(name[1])
}
```

**What did you expect to see?**
letter a
 
**What did you see instead?**
97

**Comment by JalonSolov** [comment]
`name[1]` returns a byte, not a string, so what you see is correct.

If you want it printed as a letter, you need to call the `.ascii_str()` method, as in
```v
println(name[1].ascii_str())
```
