### ISSUE TITLE
Runtime reflection

### ISSUE THREAD

**Issue by LouisSchmieder** [vlang/v#10892]
Since a year we have compile time reflection, which is very good but we've also had the idea a half a year ago to implement runtime reflection in a small way. This issue should be a place to discuss the requirements and usability of runtime reflection.

I think  @spaceface777 wrote about this in the discord already before.

**Comment by danieldaeschle** [comment]
For discussions we have discussions btw. :)

**Comment by medvednikov** [comment]
Everything should be doable via comptime.
