### ISSUE TITLE
Type system unsound

### ISSUE THREAD

**Issue by tice0-2** [vlang/v#1089]
Essentially this is elevating the code from #1081 to a separate issue.

**V version:** 0.1.12

**OS:** 

https://vlang.ide.judge0.com/

**What did you do?**

I ran the code in #1081 and it compiled:

```go
fn main() {
	a:=3
	pa:=&a
	println(a)
	println(*pa)
	mut pb := pa
	*pb=4
	println(a)
}
```

**What did you expect to see?**

It should enforce non-mutability.
 
**What did you see instead?**

It compiled and ran.

The type-checker needs to be more robust.

**Comment by ntrel** [comment]
This is the same as #41
