### ISSUE TITLE
Early access V binaries will be available today at 17:00 UTC 

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#109]

**Comment by shouji-kazuo** [comment]
I am very much looking forward to it !

**Comment by HedariKun** [comment]
will you release some sort of documentation about the built in libraries or something?

**Comment by medvednikov** [comment]
Yes

**Comment by hellojukay** [comment]
how can i install v language compile ?

**Comment by Melon-Bread** [comment]
> how can i install v language compile ?

By giving him $30 on patreon

**Comment by zeromake** [comment]
@hellojukay 
[patreon](https://www.patreon.com/vlang)
> Premium
> $30 or more per month
>
> Early access: get access to V binaries for macOS and Linux on April 15, two months before public release.
>
> V for Windows on April 18.
