### ISSUE TITLE
net : Interface of recv

### ISSUE THREAD

**Issue by GGBBB2000** [vlang/v#1091]
This is the current implementation of `recv` in `net/socket.v`. 
```
pub fn (s Socket) recv(bufsize int) byteptr {
    buf := malloc(bufsize)
    res := C.recv(s.sockfd, buf, bufsize, 0)
    if res < 0 {
        println('socket: recv failed')
    }
    return buf
}
```

`recv` returns a `byteptr` currently, but this prevents me from checking errors.
I think it should return `?byteptr` instead. 

What do you think?

**Comment by aguspiza** [comment]
I agree, net/socket.v in its current state is useless and it does not work in windows, see my comments:

https://github.com/vlang/v/commit/571410dd48123d2276282390d41670d864656756#comments

https://github.com/vlang/v/commit/859c8ffdb8578da6011c16e5530c465d185dca46

You've better totally skip this API, use C API, or better, make your own C API wrapper for V using V features.

**Comment by justicesuh** [comment]
Windows support was added with [this](https://github.com/vlang/v/pull/1129) PR.

I agree the methods should return optionals.  The optional syntax is a little broken at the moment though.

**Comment by justicesuh** [comment]
Mentioned in the above PR, but since Options are buggy with `byteptr` the temporary workaround for both `send` and `recv` is their return values will be `-1` if the calls fail

**Comment by equal-l2** [comment]
Is this still relevant?

**Comment by spytheman** [comment]
This has nothing to do with V's interface implementation imho, it is just that the term interface (as in API) is used in the issue title.
Besides, the net module was rewritten.
