### ISSUE TITLE
cgen error: could not generate string method pthread_mutex_t_str for type 'pthread_mutex_t'

### ISSUE THREAD

**Issue by kahsa** [vlang/v#10931]
**V version: 0.2.2 698e379** 
**OS: ArchLinux** 

**What did you do?**

```v
fn btn_click(mut b Button, e &MouseEvent, window &Window) {
    println(window)
```

**What did you expect to see?**
print window struct.
 
**What did you see instead?**
`cgen error: could not generate string method pthread_mutex_t_str for type 'pthread_mutex_t'`

**Comment by danieldaeschle** [comment]
Can you sahre your full code please?

**Comment by kahsa** [comment]
https://github.com/vlang/ui/blob/44f11955c0932724a1feb4351861eaeb379e99f3/button.v#L171

or 

```v
import ui

fn main(){
	window := ui.window(
		width: 300
		height: 300
		on_click: click
	)
	ui.run(window)
}

fn click(e ui.MouseEvent, window &ui.Window){
	println(window.width)
	println(window) // cgen error
}
```

**Comment by medvednikov** [comment]
Fixed.
