### ISSUE TITLE
regex: negation of the capture of sequence of chars

### ISSUE THREAD

**Issue by Hunam6** [vlang/v#10945]

**Comment by serkonda7** [comment]
THings like ´[^a-d]´ already work and capture everything except a-d.

**Comment by JalonSolov** [comment]
The issue is that he wants to say "don't capture the sequence `foo`" - in other words, a string, not individual letters.

**Comment by penguindark** [comment]
it is possible only using `not capturing groups`, 
not capturing char class is not provided at the present time and not schduled for future development.
