### ISSUE TITLE
Unexpected token, while initializing field

### ISSUE THREAD

**Issue by LouisSchmieder** [vlang/v#10958]
**V version:** V 0.2.2 016240d.9970776
**OS:** Ubuntu 20.04.2 LTS (VM)

**What did you do?**
```v
module main

struct FooFoo {
pub mut:	
	conn Foo
}

struct Foo {
	host string = '127.0.0.1'
	port u32    = 3306
	username string
	password string
	dbname string
}

fn main() {
	mut sql := FooFoo{}
	sql.conn = Foo{
		username: 'username'
		password: 'abc'
		dbname: 'test'
	}
}

```

**What did you expect to see?**
Compiles fine, no problems
 
**What did you see instead?**
```v
a.v:18:11: error: unexpected token `=`, expecting `{`
   16 | fn main() {
   17 |     mut sql := FooFoo{}
   18 |     sql.conn = Foo{
      |              ^
   19 |         username: 'username'
   20 |         password: 'abc'
```

**Comment by mcastorina** [comment]
For anyone who wants to fix this, the problem comes from naming the variable `sql`. Renaming that to anything else compiles fine.

`sql` is a keyword that cannot be used as a variable name, so this example is correct in erroring, but it needs a better error message.
