### ISSUE TITLE
rename Makefile to GNUmakefile and BSDmakefile to Makefile

### ISSUE THREAD

**Issue by subnut** [vlang/v#10954]
The current Makefile is GNUmake-specific. GNU Make first checks for the name GNUmakefile before Makefile or makefile, but BSD make doesn't check for BSDmakefile. This breaks the `git clone` `cd v` `make` process shown in the README.

Please change the name of the current `Makefile` to `GNUmakefile` and the `BSDmakefile` to `Makefile`.

Thanks.

**Comment by medvednikov** [comment]
That's strange, `make` works for me on FreeBSD. It uses BSDmakefile.

**Comment by subnut** [comment]
It doesn't on OpenBSD.

**Comment by Hunam6** [comment]
This should be closed
