### ISSUE TITLE
[vpm] Ability to install module from other Git repo

### ISSUE THREAD

**Issue by leapofazzam123** [vlang/v#10969]
I need this because I need a V module, which isn't in vpm database. The V module I want to install is [v-llvm](https://github.com/vlang/v-llvm).

**Comment by shadowninja55** [comment]
git clone https://github.com/vlang/v-llvm ~/.vmodules/v-llvm

**Comment by crthpl** [comment]
`v-llvm` won't work, it hasn't been updated in over a year.

**Comment by smartiniOnGitHub** [comment]
With this feature it should be possible to install modules from other branches (for example to test id-development features) or even fixed releases (referring to a tag), right ? 
That would be great !! Thanks a lot.
