### ISSUE TITLE
`gg.update_pixel_data()` not able to take black/white buffer

### ISSUE THREAD

**Issue by BenStigsen** [vlang/v#10965]
**What did you do?**
Create a `[]byte` like 10x10 in size. Containing 0 and 255 values.
`ctx.update_pixel_data(canvas.image, canvas.buffer.data)` _`canvas.image` is the ID as gotten from `new_streaming_image()`_

**What did you expect to see?**
Black and white pixels when using `ctx.draw_image_by_id(canvas.x, canvas.y, canvas.width, canvas.height, canvas.image)`
 
**What did you see instead?**
The image is tiny, but basically something that looks like a night sky with more than just black/white colors.
![image](https://user-images.githubusercontent.com/24865450/126915348-006aa61f-6ddf-4490-8241-b9ad7e24bbef.png)

**Description:**
So first off I should mention that creating an image with `ctx.create_image_from_byte_array(canvas.buffer)` works.
When I create an image I use `ctx.new_streaming_image(width, height, 1)`. The ID from this image is saved and everything seems okay. However, if I use `ctx.update_pixel_data(canvas.image, canvas.buffer.data)` it does not seem to use 1 channel, it uses 3 (RGB) or 4 (RGBA). This tells me that maybe the `nr_channels` is ignored entirely. If I make my buffer 4 times larger, it works perfectly, so this is keeping me from using black/white buffers unless I want to spend 4x the memory on it, which shouldn't be necessary.
https://github.com/vlang/v/blob/master/vlib/gg/image.v#L229-L234

I should also mention, that doing:
```v
mut img := ctx.get_cached_image_by_idx(canvas.image)
img.nr_channels = 1
img.width = canvas.width
img.height = canvas.height
```
Makes no difference.

**Comment by BenStigsen** [comment]
After taking another look at it, this is probably why: https://github.com/vlang/v/blob/master/vlib/gg/image.v#L200
The pixel format does not get set depending on number of channels, the only default and possible option is 4 bytes.

**Comment by BenStigsen** [comment]
After looking more at it, I have two requests with the main one being:
- Allow one to specify pixel_format
- Another possible one would be to add a function for creating an image with a config (would be nice but not necessary).

I do have a question though, am I right to assume that the `r8` pixel format would be black/white, or would that be black/red?

**Comment by spytheman** [comment]
@BenStigsen is 0d12d55 enough for closing this?

**Comment by BenStigsen** [comment]
I would think so. It does take a black/white buffer now, it just doesn't draw it that way because that apparently isn't a thing: https://floooh.github.io/sokol-html5/pixelformats-sapp.html so I'll have to figure out a way to draw a black/red pixel buffer, as a black/white pixel buffer.
