### ISSUE TITLE
String format allows 'printf' format specifier

### ISSUE THREAD

**Issue by spacesinmotion** [vlang/v#1097]
**V version:0.1.13** 
**OS:Linux** 

**What did you do?**
I had a strange assumption:
```
fn main() {
	dummy:= 'some memory dumb pls:'
	println('$dummy %x %x %x %x %x %x')
}
```

**What did you expect to see?**
a lot of '%' symbols in output
 
**What did you see instead?**
output:
```
some memory dumb pls: 5 0 0 b7fb9958 9b1eeab0 9b1f36c5
```
_That is output from the online playground._

**Comment by misternode** [comment]
Indeed it does.

maybe needs some processing on the string to escape printf identifiers

vlib/builtin/builtin.v
`pub fn println(s string) {
	// Should never happen
	if isnil(s.str) {
		panic('println(NIL)')
	}
	C.printf('%.*s\n', s.len, s.str)
}`

**Comment by spacesinmotion** [comment]
@misternode I think this could **not** be fixed in **`vlib`**
It is the compiler that converts '$val' to a `sprintf` statement in **C**. At least I think so.

**Comment by misternode** [comment]
vlib could convert ' %' to ' %%' to escape the % sequences

v_str.v
```
x := '6'

println('x $x %x %x %x %x %x %x')
println('x $x %%x %%x %%x %%x %%x %%x')   // <- escaped version
```

```
============ running v_str ============
x 6 1 0 0 0 5965a01 1
x 6 %x %x %x %x %x %x      
```

**Comment by spacesinmotion** [comment]
@misternode Yeah you are right, but I thing the compiler has to handle this at the moment ...

```go
fn main() {
  x := '6'
  x_s := 'x $x %x %x %x %x %x %x'
  x_s.free()
}
```
is getting:
```C
//...
int main(int argc, char** argv) {
 init_consts();

string x= tos2("6") ;

string x_s= _STR("x %.*s %x %x %x %x %x %x", x.len, x.str) ;

 v_string_free( x_s ) ;
 }
//...
string _STR(const char *fmt, ...) {
        va_list argptr;
        va_start(argptr, fmt);
        size_t len = vsnprintf(0, 0, fmt, argptr) + 1;
        va_end(argptr);
        byte* buf = malloc(len);
        va_start(argptr, fmt);
        vsprintf(buf, fmt, argptr);
        va_end(argptr);
#ifdef DEBUG_ALLOC 
        puts("_STR:");
        puts(buf);
#endif
        return tos2(buf);
}
// ...
```
the format specifier have to be replaced before `vsnprintf` is called ...

**Comment by misternode** [comment]
I see what you mean.

v_str_len.v
```
x := '6'
my_str := '$x %x'
len := C.strlen(my_str.cstr())

println('expecting string len 4: \'6 %s\'')
println('found len: $len')
println('my_str: \'$my_str\'')
```

```
============ running v_str_len ============
expecting string len 4: '6 %s'
found len: 3
my_str: '6 1'
```
