### ISSUE TITLE
Can not load custom dll written in c on windows

### ISSUE THREAD

**Issue by robotcc** [vlang/v#10987]
I'm trying to write a wrap for a third party lib. import has got no error , but the program did not run.
 Is there any log for me to check what's wrong with it?
![QQ图片20210728203321](https://user-images.githubusercontent.com/11989107/127322784-387199ef-9d7e-466a-a462-9b87d40bc34c.png)

**Comment by JalonSolov** [comment]
The `import` in V is for importing V modules, not DLLs or other shared libraries.

You'll need to look at these instructions for an ideas on calling DLL routines:

https://github.com/vlang/v/blob/master/doc/docs.md#calling-c-from-v

You can also look at files with names ending in `_windows.v` and `_windows.c.v` in the `vlib` subdirectories for examples of calling Windows routines from V.

**Comment by robotcc** [comment]
Thanks！But still I haven't got an idea. 
compile is ok, couldn't run

**Comment by robotcc** [comment]
"v run .\test.v " will create an exe in current directory, and the directory should have *.dll inside. 
That's why my test.v can not run.
