### ISSUE TITLE
`map(println(it))` causes C Error: declaration of void object

### ISSUE THREAD

**Issue by inokawazu** [vlang/v#10982]
**V version: V 0.2.2 9f44315** 
**OS: Linux, “Manjaro Linux”** 

**What did you do?**

I ran the following code with `v run`.

```
module main

fn main(){
	array := [1,2,3,4]
	array.map(println(it))
}
```

**What did you expect to see?**
```
1
2
3
4
```

 
**What did you see instead?**

/tmp/v/main.18405178146812643968.tmp.c:10300: error: declaration of void object

**Comment by DevrosTheOne** [comment]
Seems we can't have a variable called ```array```.   Bit like the ```sql``` variable problem from before.

The 'declaration of void object' (error generic and not clear) most likely referring to void returned by the```println()``` function .  ```map( )``` needs to act each item somehow eg```.map( it * 2 )``` and keep the result.

To print in ```map()``` use a lambda/anonymous function or call another function that returns a useful result.
```v
fn main() {
	arr := [1, 2, 3, 4]
	arr.map(fn (it int) int {
		println(it)
		return it
	})
}
```
We don't have an iterator for arrays like Crystal/Ruby ```.each``` method??
