### ISSUE TITLE
'array' variable name fails .map() and .filter() methods

### ISSUE THREAD

**Issue by DevrosTheOne** [vlang/v#10991]
**V version:** 
V full version: V 0.2.2 f48f623.ae05ab8
**OS:** 
OS: macos, macOS, 11.5.1, 20G80
Processor: 8 cpus, 64bit, little endian, Apple M1
CC version: Apple clang version 12.0.5 (clang-1205.0.22.11)

**What did you do?**
Used a variable ```array``` and program fails to compile using ```array.map()``` and ```array.filter()```.  Other methods ```.reduce(), .any(), .all()``` all work as expected.  Changing the variable name fixes the problem with ```.map()``` and ```.filter()```.  Was mentioned in https://github.com/vlang/v/issues/10982
```v
//------------error----------------
	array := [1,2,3,4]
	mut res1 := array.map( it * 3 )
	mut res2 := array.filter( it > 2 )
	println(res1)
	println(res2)

//--------------ok-----------------
	// arr := [1,2,3,4]
	// mut res3 := arr.map( it * 3 )
	// mut res4 := arr.filter( it > 2 )
	// println(res3)
	// println(res4)
```

**What did you expect to see?**
```
[3, 6, 9, 12]
[3, 4]
```
 
**What did you see instead?**
```
/tmp/v/arrerror.6199580445162401129.tmp.c:10209:22: error: expected expression
                        array_push((array*)&_t3, &it); 
                                          ^
2 errors generated.
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.
```

**Comment by LouisSchmieder** [comment]
it happens because array is a keyword

**Comment by JalonSolov** [comment]
V needs to give an error for using keywords as variable names.

**Comment by DevrosTheOne** [comment]
Array is a keyword?  Did not find it in the keyword list or documentation.

Tripped me as other methods have no problems with a variable named ```array```.  

Found a struct called ```array```.  Should have clicked sooner.    

Should we be allowed to use ```array``` as a variable name in the code?  At the moment it's a keyword only under certain conditions and I can't see how we can use it directly.  Am I missing something?

**Comment by LouisSchmieder** [comment]
It's listed afaik in the docs as a keyword because we cast all custom arrays in C to an `array*` and the C compilers interpretation of array there is the variable

**Comment by medvednikov** [comment]
It's not a keyword, this should be fixed.

**Comment by DevrosTheOne** [comment]
We currently can declare builtin struct names as variables.  
If you want to write unreadable/unstable code and really confuse the compiler.  

Bad variable name a quick nonsense example
```v
import math

mut string :=  22  /  7.0
mut close_enough := ( string + 0.005 ) > math.pi  // bool? compiles but don't use the result

// println(close_enough) // error: expected ')' println(close_enough ? _SLIT("true") : _SLIT("false"));
// println(typeof(close_enough).name) // error: passing 'f64' (aka 'double') to parameter of incompatible type 'string'
// if close_enough { println('it worked') } //same error as above??
```
Like the ```array``` problem.
Probably too early in development cycle to deal with this?

**Comment by medvednikov** [comment]
It's a simple problem to solve, we already have the infrastructure :)

Will push a fix tomorrow.

**Comment by danieldaeschle** [comment]
> Will push a fix tomorrow.
;)

**Comment by danieldaeschle** [comment]
What is the solution to this? Then I can implement it.

**Comment by JalonSolov** [comment]
One `fix` is to not allow builtin names to be used as variable names in code.

Another would be to keep track of variable declarations separate from builtin names, and make sure they look different in the generated code.

**Comment by DevrosTheOne** [comment]
How many possible variable name conflicts do we have?  Are we are looking at the ```array``` for now?  I tend to overthink and  complicate things if no parameters given.   

Temporary fixes are a code smell and will need to be refactored.  Other options sound like something to be left when the base and language gets is more statable and bolted down.  A few thoughts (just brain storming)

Possible to live with this problem while in Alpha/Beta?  Kick the problem down the track until things are more clearer? (waiting for inspiration/lazy programmer solution)

List of variables names that are forbidden for now? (non IT manager solution) LOL

Preprocessor to do a sanity check on declared variables.  Just a message saying don't use this name for now.  Slows down the system with more annoyances to the programmer. (ughhh)

Mangle the conflicting user variable names.  More work changing variables from internal and external representation. Debugging names? 

Mangle all user variable names.  Refactoring complicated.  Debugging names? 

Mangling the program variables with extra identifier like underscores ```__array``` an option?  If they are of the form developers can't declare no conflict but may need a lot more refactoring.  Fixed number of variables to deal with.

Keeping the two variable domains in different name spaces?  More refactoring.

**Comment by JalonSolov** [comment]
There are quite a few builtins... array, string, int, u64, etc., etc., etc.

**Comment by DevrosTheOne** [comment]
> There are quite a few builtins... array, string, int, u64, etc., etc., etc.

Only played with ```array ``` and ```string``` don't usually name variables ```u64```.   Early Alpha/Beta, other things more important .

Its all :thumbsup: ( https://github.com/vlang/v/issues/10991#issuecomment-889581301 ) 

All hail language/compiler designer/programming gods :clap:.
