### ISSUE TITLE
Build fails with "unknown type `os.File`"

### ISSUE THREAD

**Issue by ciubotaru** [vlang/v#1101]
**V version:**
Latest snapshot (7f4c3cda4d0c5ed8b645f375a62f18e380fd92e2)

**OS:** 
Ubuntu 18.04 amd64

**What did you do?**
```
> make
```

**What did you expect to see?**
A successful compilation.
 
**What did you see instead?**
```
rm -f v.c v vprod
curl -Os https://raw.githubusercontent.com/vlang/vc/master/v.c
cc -std=gnu11 -w -o v v.c -lm 
./v -o v compiler
get_type() bad type
panic: cgen.v:10
unknown type `os.File`
Makefile:5: recipe for target 'v' failed
make: *** [v] Error 1
```

**Comment by ciubotaru** [comment]
Strangely enough, I can not reproduce it on another machine with same OS and arch.

**Comment by aguspiza** [comment]
Is the filesystem where you are cloning to case sensitive?

**Comment by ciubotaru** [comment]
Solved.

It must have been some stale artifact. The problem disappeared after I removed ~/.vlang and V source tree, and cloned the repo again.
