### ISSUE TITLE
[vweb] App struct user-defined fields don't persist between endpoints

### ISSUE THREAD

**Issue by billpcs** [vlang/v#11010]
**V version:** V 0.2.2 1e255d3.0675079
**OS:** Linux, Ubuntu 18.04.5 LTS

**What did you do?**
I tried to use the 

```v
struct App {
    vweb.Context
}
```
structure to keep some of my local variables inside

However, even though I save `ints []int` in one endpoint, in a different endpoint the field remains empty.

--- 

Here is the simplest example:

- vweb_context.v

```v
module main

import vweb

const (
        port = 8082
)

struct App {
        vweb.Context
mut:
        ints []int
}

fn main() {
        vweb.run(&App{}, port)
}

pub fn (mut app App) index() vweb.Result {
        println(app.ints)
        return $vweb.html()
}

['/test']
pub fn (mut app App) test() vweb.Result {
        app.ints = [1,2,3,4]
        return $vweb.html()
}
```

- index.html

```html
<h1>go to /test to fill in the array</h1>

@for element in app.ints
<h1> @element </h1>
@end
```

- test.html

```html
<meta charset="utf-8">
@for element in app.ints
<h1> @element </h1>
@end

<a href="/">Back</a>
```

---

**What did you expect to see?**
The `index.html` page to display the array, after I visit `/test`
 
**What did you see instead?**
The `index.html` page has no access to the array

In the documentation, it explicitly says 
> To start with vweb, you have to import the module vweb. After the import, define a struct to hold vweb.Context (**and any other variables your program will need**).

I am almost certain that this worked at some point. Has something changed in the language, and you have to fill in the structure field differently now?

(Maybe related to #11004)

**Comment by billpcs** [comment]
One more thing I found out:

By printing

```v
println(voidptr(app))
```

in each endpoint, it seems that after each invocation a different address is printed, even for the same endpoint. 

```
index 23dfab0
test 23e1590
index 23e2a00
index 23e3e70
index 23e52e0
```


So something is wrong, either with my mental model or with the code. I would expect the same reference to `app` to be passed around.

**Comment by billpcs** [comment]
Looking in the `vlib/vweb/vweb.v` file, I see that indeed, there is some copying going on, there is not a single `App` instance:

---
```v
pub fn run<T>(global_app &T, port int) {

...

	for {
		// Create a new app object for each connection, copy global data like db connections
		mut request_app := &T{}

...

		$for field in T.fields {
			if field.is_shared {
				request_app.$(field.name) = global_app.$(field.name)
			}
		}
		request_app.Context = global_app.Context // copy the context ref that contains static files map etc
...

	}
}
```
---

So essentially, each `request_app` struct, that is used by the endpoints, cannot access the `global_app` instance to set values in it.

Am I correct in this statement? 
Also, what sets the value for the `is_shared` field?

**Comment by JalonSolov** [comment]
Field in the App struct can be shared between instances by adding the `shared` keyword between the field name and type.  See `examples/vweb_example.v`.

There used to only be one App structure, but this was found to be too limiting for a site that supported multiple instances.  Especially if your site supports session cookies, etc., which might be stored in the App structure.

**Comment by billpcs** [comment]
OK, then the way to have cross-endpoint values is to use the `shared` keyword, as shown in `examples/vweb/vweb_example.v`

I will close this issue as invalid.
