### ISSUE TITLE
Arithmetic in mutating for loop works on pointers

### ISSUE THREAD

**Issue by edwindj** [vlang/v#11038]
**V version:** V 0.2.2 66bc8bc.0ebad47
**OS:**  OS: linux, "Manjaro Linux"

**What did you do?**

```v
fn main(){
	mut ints_a := [1,2]
	for mut i in ints_a {
		j := 0 + i //NB j:= i + 0, works correctly!
		i = j
	}
	print("$ints_a")
}
```

**What did you expect to see?**

```
[1,2]
```
 
**What did you see instead?**

(array with pointers to ints)
```
[11122432, 11122436]
```

**Comment by edwindj** [comment]
Also: 

**V version:** V 0.2.2 66bc8bc.0ebad47
**OS:**  OS: linux, "Manjaro Linux"

**What did you do?**

```v
fn main(){
	mut ints_a := [1,2]
	for mut i in ints_a {
		i = i*i
	}
	print("$ints_a")
}
```

**What did you expect to see?**

```
[1,4]
```
 
**What did you see instead?**

```sh
error: invalid operator `*` to `&int` and `&int`
```

**Comment by danieldaeschle** [comment]
@UweKrueger This could be for you to take care in your new implementation.

**Comment by ArtemkaKun** [comment]
Actual V (0.3.2) outputs the expected result for code in the first question. The second code still has an issue, but I decided to file it in a separate issue.

**Comment by ArtemkaKun** [comment]
Issue related to multiplication - #17019
