### ISSUE TITLE
wrong code generation for `array.sort`

### ISSUE THREAD

**Issue by Gladear** [vlang/v#11040]
**V version:** V 0.2.2 bd0653a.fd58e9f
**OS:** linux, Ubuntu 20.04.2 LTS (WSL 2)

**What did you do?**
```v
fn ret_array() []int {
        println('hello there')
        return [1, 3, 2]
}
```

ret_array().sort()

**What did you expect to see?**
```
hello there
```
 
**What did you see instead?**
```
hello there
hello there
hello there
```

**Hints**
Here is generated C
```c
qsort(main__ret_array().data, main__ret_array().len, main__ret_array().element_size, (int (*)(const void *, const void *))&compare_ints);
```

A temporary variable must be introduced in `Gen.gen_array_sort` - `vlib/v/gen/c/array.v`.
`Gen.new_ctemp_var_then_gen` can probably be used for that purpose

**Comment by robotcc** [comment]
```v
fn ret_array() []int {
	return [1, 3, 2]
}

mut arr := ret_array()
arr.sort()

println(arr)
```
Is this what you meant? sort() will not work on array without mut

**Comment by Gladear** [comment]
Maybe, maybe not.
Currently the code I provided is allowed and results in unexpected behavior

**Comment by robotcc** [comment]
as above generated C codes, main__ret_array() create array for three times, .data, .len , .element_size comes from different array. 
And those arrays are all temporary, maybe recollected by runtime, which results in unexpected behavior.

**Comment by medvednikov** [comment]
@Gladear, you are correct, it's a bug in the compiler.
