### ISSUE TITLE
Cannot multiply float literal and int

### ISSUE THREAD

**Issue by mcastorina** [vlang/v#11057]
**V version:** V 0.2.2 f591194
**OS:** linux

**What did you do?**
```v
d := 10
f := 1.1 * d
println(f)
```

**What did you expect to see?**
```
11.
```
 
**What did you see instead?**
```
test.v:2:6: error: mismatched types `float literal` and `int`
    1 | d := 10
    2 | f := 1.1 * d
      |      ~~~~~~~
```

**Comment by JalonSolov** [comment]
Seems like V could do better... the 1.1 is obviously a float, and multiplying that by 10 should work fine.

Besides, the docs say `A small primitive type on one side can be automatically promoted if it fits completely into the data range of the type on the other side.`

**Comment by mcastorina** [comment]
This works

```v
d := 10
fl := f64(1.1)
f := fl * d
```

So does this

```v
d := 10
f := f64(1.1) * d
```

If you want to be consistent with Go, the only thing that should work is doing `1.1 * f64(d)`.

Autoconverting to a `f64` seems okay to me. I have no strong opinion on requiring a cast for the integer.
