### ISSUE TITLE
`v self` doesn't pass compiler options

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#11068]
![image](https://user-images.githubusercontent.com/687996/128425050-51343122-0c98-4b4f-b402-36c942b6360e.png)

This command should add -showcc to the executed command.

**Comment by Gladear** [comment]
`-showcc` must be passed before the command
![Screenshot 2021-08-05 235600](https://user-images.githubusercontent.com/6588374/128426393-36a515ca-6107-4ffa-bcfc-91961b2add69.png)

**Comment by brightly-salty** [comment]
Would it be good to allow placing options before or after `self` then? It would be a very easy change

**Comment by medvednikov** [comment]
Yes, `v [verb] -options` makes sense, and that's what many people would expect. That's how it also works in Go.

I think making it work is a pretty big change actually.

Right now everything in V expects options before the verb.

**Comment by brightly-salty** [comment]
At least for this command, it would be very easy. I can look into how the other commands are implemented as well and see if the difficulty is very different

**Comment by brightly-salty** [comment]
Interestingly, pretty much each subcommand has its own way of parsing command-line arguments. Perhaps some unification is in order, although probably out of scope for this issue?
