### ISSUE TITLE
Support fixed-length array argument for dynamic array parameter

### ISSUE THREAD

**Issue by Cons-Cat** [vlang/v#11063]
Currently, this code does not compile:
```v
fn fun(input []int) {
	return
}

fn main() {
	array := [1, 2, 3]!
	fun(array)
}
```
I am assuming this is because dynamic arrays are defined [this way](https://modules.vlang.io/index.html#array), whereas fixed-arrays are probably something lighter. But it feels unintuitive to me while writing code that I cannot trivially use a fixed array argument for a dynamic array parameter. I can't figure out a reasonably simple way of making this conversion myself at call site, because I can't directly mutate the ``data`` field of an array. I have to fill it out with a ``for`` loop. I think it would be a significant improvement to quality of life if this were changed.

**Comment by danieldaeschle** [comment]
```v
fn fun(input []int) {
	return
}

fn main() {
	array := [1, 2, 3]!
	fun(array[1..])
}
```

**Comment by Cons-Cat** [comment]
> ```v
> fn fun(input []int) {
> 	return
> }
> 
> fn main() {
> 	array := [1, 2, 3]!
> 	fun(array[1..])
> }
> ```

Ahh that makes sense! If this is intended to be the only way to do this, I'll close this issue. But I think it may still be reasonable to do this automatically.

**Comment by medvednikov** [comment]
yes, fixed arrays need to be converted to dynamic arrays
