### ISSUE TITLE
Structs initialization in `if` statements throws a syntax error

### ISSUE THREAD

**Issue by Hunam6** [vlang/v#11088]
**V version:** V 0.2.2 ec39e38
**OS:** Windows 11 64-bit

*setup*
```v
struct Foo {
    bar int
}
a := Foo{}
```
*working*
```v
println(a == Foo{})
```
*don't working*
```v
if (a == Foo{}) {
    println(true)
}
```

**Comment by DevrosTheOne** [comment]
No parenthesis for the ```if``` expression in V.
I think we only have ```typeof().name```  to get the string name of the structure for comparison.  Odd that we can do direct comparison using ```==``` but not as part of ```if``` expression.  
```v
struct Foo{
	bar int
}
a := Foo{12}

println( if typeof(a).name == 'Foo' {'Yap it\'s a Foo'} else {'Some other type'} )
// ternary operator would be so nice and clean :)
```
