### ISSUE TITLE
Several errors compiling brand new project to iOS

### ISSUE THREAD

**Issue by rmallof** [vlang/v#11087]
**V version:** V 0.2.2 ec39e38
**OS:** macOS Big Sur 11.5.1

**What did you do?**

- v new test
- cd test
- v -os ios .

*Extra note*:

I asked for #help in Discord and thanks to @spytheman and @spaceface777 I was able to compile after editing **thirdparty/ios/ios.m** to the following:

```
void WrappedNSLog(const char *message,...) {  
    va_list args;  
    va_start(args, message);  
    va_end(args);  
}  
```
**What did you expect to see?** 

A compiler "test" executable for iOS
 
**What did you see instead?**
```
                     ^
/tmp/v/test.7630996033059445783.tmp.c:2388:22: error: conflicting types for 'strconv__is_space'
VV_LOCAL_SYMBOL bool strconv__is_space(byte x) {
                     ^
/tmp/v/test.7630996033059445783.tmp.c:1235:22: note: previous declaration is here
VV_LOCAL_SYMBOL bool strconv__is_space(byte x);
                     ^
/tmp/v/test.7630996033059445783.tmp.c:2392:22: error: conflicting types for 'strconv__is_exp'
VV_LOCAL_SYMBOL bool strconv__is_exp(byte x) {
                     ^
/tmp/v/test.7630996033059445783.tmp.c:1236:22: note: previous declaration is here
VV_LOCAL_SYMBOL bool strconv__is_exp(byte x);
...
```

**Comment by gerald24** [comment]
This also happens when compiling darwin module - eg:
[webapp.zip](https://github.com/vlang/v/files/7799644/webapp.zip)
