### ISSUE TITLE
directly return an unwrapped option

### ISSUE THREAD

**Issue by spacesinmotion** [vlang/v#1108]
### Problem

version: 0.1.14
os: Linux

Maybe there is a bug involved here: I expected the following to work:
```go
fn check_call() ?int {
  return error('Not ok!')
}

fn call(default_value int) int {
  return check_call() or { // unwrap
    return default_value // the 'return' is redundant, but 
                         // I thought it might work
  }
}

fn test_check_call() {
  assert 42 == call(42)
}
```
but I get:
```
panic: interface_order_test.v:7
expected type `int`, but got `Option_int`
```
The workaround would be to use a temporary variable.

### Solution
Nevertheless: I thought about the following syntax:
```go
fn call(default_value int) int {
  return check_call() or default_value
}
```
_It would also be ok if I need to write `or { default_value }`, as it would be more expressive._

**Comment by lutherwenxu** [comment]
This has now been resolved.
It was definitely a bug. :)
