### ISSUE TITLE
Array copied despite being passed as mutable

### ISSUE THREAD

**Issue by jdonnerstag** [vlang/v#11101]
**V version:**   V 0.2.2 1f3f770.be7c396
**OS:** windows, Microsoft Windows 10 Enterprise v19041 64-bit

**What did you do?**
```
fn test_a() {
	mut a := App{}
	a.data << 1
	a.do_something()
	assert a.data.len == 2
}

struct App {
pub mut:
	data []int
}

fn (mut a App) do_something() {
	assert a.data.len == 1
	mut p := Proc{}
	p.make_a(mut a.data)
	assert a.data.len == 2
}

struct Proc {}

fn (mut p Proc) make_a(mut data []int) {
	data << 2
}
```

**What did you expect to see?**
despite everything being mutable, and passed as mutable, the [] int array will be copied. And because of copy-on-write, the update is not visible when back in the upper function.  Instead I expect the test function to pass usccessfully.
 
**What did you see instead?**
```
✗ fn do_something
   > assert a.data.len == 2
     Left value: 1
    Right value: 2
```

**Comment by medvednikov** [comment]
@yuyi98

**Comment by yuyi98** [comment]
Ok, I'll try.

**Comment by yuyi98** [comment]
Just fix this case, there could be other cases, and I'll complete in other pr.
