### ISSUE TITLE
generic implementation of interface causes compiler error

### ISSUE THREAD

**Issue by exp101t** [vlang/v#11103]
**V version:** `V 0.2.2 cc94634.1f3f770`
**OS:** `Windows 10`

**What did you do?**
Tried to compile
```v
interface SomeInterface {
    some_method(arg int) int
}

struct SomeImplementation {}

fn (i SomeImplementation) some_method<T>(arg int) int {
    return arg
}

fn main() {
    i := SomeImplementation {}
    println(i.some_method<int>(1))
}
```

**What did you expect to see?**
Successful compilation
 
**What did you see instead?**
Compiler error:
```
warning: implicit declaration of function 'main__SomeImplementation_some_method'
tcc: error: undefined symbol 'main__SomeImplementation_some_method'
```

**Comment by yuyi98** [comment]
`fn (i SomeImplementation) some_method<T>(arg int) int {
    return arg
}`
I think this generic fn declaration is invalid, we should check it.

**Comment by DevrosTheOne** [comment]
```<T>``` can be any type for the method call ```i.some_method<string>(12)``` will work.  Can't see use case for this.

Even stranger, replace the return type in the method with a type that ```int``` can be promoted up to and it will compile and execute.

```v
fn (i SomeImplementation) some_method<T>(arg int) i64 {
    return arg
}
```

**Comment by exp101t** [comment]
Even without use case this code has no syntax errors and should be compiled. Unused generics in function declaration may throw error or warning before translating to C, but not after.

**Comment by yuyi98** [comment]
```vlang
interface SomeInterface<T> {
	some_method(arg int) int
}

struct SomeImplementation<T> {}

fn (i SomeImplementation<T>) some_method<T>(arg int) int {
	return arg
}

fn main() {
	i := SomeImplementation<int>{}
	println(i.some_method<int>(1))
}

PS D:\Test\v\tt1> v run .
1
```
