### ISSUE TITLE
How do I use a variable which is outside of an anonymous function? is it even possible?

### ISSUE THREAD

**Issue by ppshobi** [vlang/v#11120]
I was trying to refactor a little bit of ORM code in vlang, which is below 

https://github.com/vlang/v/blob/1588fe796712469eb54380699901536d52c9a123/vlib/orm/orm.v#L140-L145

I was trying to modify the code to a little bit readable format. Like following
```
data.fields.map(fn(field string) string, $para {
  return '$para$field$para' // but here the $para is coming from outside of the anonymous function and its not accessible inside, 
}).join(', ') 

```
do we have a way to access the variable inside? example: [ use in PHP  ](https://stackoverflow.com/a/11420541/2693543)

**Comment by JalonSolov** [comment]
It's not possible right now, as closures aren't implemented yet.  You'll have to pass `para` in as a parameter until then.

**Comment by Gladear** [comment]
In you case, you can do `data.fields.map('$para$it$para')`, but that won't work for more complex function.
This will be solved once closures are implemented.

**Comment by medvednikov** [comment]
Closures are being merged right now ;)

**Comment by medvednikov** [comment]
https://github.com/vlang/v/pull/11114

**Comment by ppshobi** [comment]
Wow. super fast 💕

**Comment by JalonSolov** [comment]
No, you're just lucky you asked when you did.  :-)  @Gladear has been working on this for a long time.

**Comment by ppshobi** [comment]
😂 I mean the responses. Thanks to @Gladear
