### ISSUE TITLE
build android .so or ios .a file

### ISSUE THREAD

**Issue by shumtn** [vlang/v#11129]
I want to use vlang to create a gamesdk. I need to export android .so and ios .a files, and then use my sdk for mobile projects. Is there any way to achieve this? in urgent need.

**Comment by Larpon** [comment]
> I want to use vlang to create a gamesdk. I need to export android .so and ios .a files, and then use my sdk for mobile projects. Is there any way to achieve this? in urgent need.

@shumtn you can try and build your v project with [`vab`](https://github.com/vlang/vab) and take a look at the build folder:
`/tmp/vab/build/lib/<arch>`.

You can load those so files with the normal `static { System.loadLibrary("libsomehting"); }` from Java.

I don't know how to do this on iOS, sorry

**Comment by Larpon** [comment]
You can also build a C file manually with `v -os android -apk -o file.c` and then build this file as a shared object with the compilers shipped with the Android NDK
