### ISSUE TITLE
Cannot open output file v.exe: Permission denied

### ISSUE THREAD

**Issue by athif23** [vlang/v#1113]
**V version:** 0.1.14
**OS:** Windows 10

**What did you do?**
I'm trying to compile v like what the instruction tell me,
```bash
# Download the V compiler's source translated to C
curl -O https://raw.githubusercontent.com/vlang/vc/master/v.c
gcc -std=gnu11 -w -o v v.c  # Build it with Clang or GCC
./v -o v compiler          # Use the resulting V binary to build V from V source
```

**What did you expect to see?**
V get compiled.
 
**What did you see instead?**
Every time I run `./v -o v compiler` I get:
```bash
Looks like you are running V for the first time.
Setting VROOT to "E:\atarazat\project\v".
C:/mingw-w64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file v.exe: Permission denied
collect2.exe: error: ld returned 1 exit status
V panic: clang error
```
I have tried to run `v.exe -o v compiler` but I still get the same.
Also, when I'm trying the repl, every time I type some normal code, like `1 + 1` or `'hello'`, it's still get the same error.

**Comment by medvednikov** [comment]
This doesn't work on Windows, use make.bat instead. I've updated the instructions.
