### ISSUE TITLE
array.delete_last() missing from javascript backend

### ISSUE THREAD

**Issue by lancethepants** [vlang/v#11149]
**V version:** V 0.2.2 90adf4d
**OS:** 
Browser

**What did you do?**
https://github.com/lancethepants/36cube-vlang/blob/master/36cube.v
v -o 36cube.js 36cube.v

**What did you expect to see?**
36cube.js, no errors
 
**What did you see instead?**
```
36cube.v:97:15: error: unknown method or field: `[]Tower.delete_last`
   95 |             board[p.row][p.column] = Tower{6 - board_height[p.row][p.column], Color(i), true}
   96 |             freetowers[index] = freetowers[freetowers.len - 1]
   97 |             freetowers.delete_last()
      |                        ~~~~~~~~~~~~~
   98 |             return advance_position(p)
   99 |         }
```

**Comment by JalonSolov** [comment]
Unfortunately, there's a lot of stuff missing from the javascript backend.  @playXE is working on it.  :-)
