### ISSUE TITLE
flag.string_multi() does not work

### ISSUE THREAD

**Issue by Cons-Cat** [vlang/v#11141]
**V version:** V 0.2.2 aca66d5.9995f6c
**OS:** Void Linux

**What did you do?**
``cat dump.v``
```v
import os
import flag

fn main() {
	mut fp := flag.new_flag_parser(os.args)
	vals := fp.string_multi('flag', `f`, '')
	fp.finalize() or { panic(err) }
	println(vals)
}
```
I tried fixing this in vlib myself, but I couldn't get it to work without introducing new bugs that I don't understand.

**What did you expect to see?**

``v run dump.v -f r s n t``
``['r', 's', 'n', 't']``
 
**What did you see instead?**
``['r']``

**Comment by yuyi98** [comment]
From the source code, the usage should be `v run dump.v -f r  -f s  -f n -f t`.
