### ISSUE TITLE
vweb: applications run in watch mode, no content served at runtime

### ISSUE THREAD

**Issue by smartiniOnGitHub** [vlang/v#11165]
**V version:** V 0.2.2 19642a1.a8905e2
**OS:** linux, Ubuntu 20.04.2 LTS

**What did you do?**
cd examples/vweb/
v watch .

**What did you expect to see?**
content served in browser
 
**What did you see instead?**
```
[/opt/vlang_v/cmd/tools/vwatch.v:303] main.scan_timeout_s: 300
2021-08-12 15:32:10.783: "/opt/vlang_v/v" . | pid:  337076 | reload cycle:     0
```
this is ok, and even reload works if source is updated.
But in browser I get no content browsing at http://localhost:8082
Note that in another terminal, running ```netstat -tlpn``` I don't see that port open nor in LISTEN.
Having this working would be a great speed-up even for vweb applications.

Note that if I run normally (not in watch mode) all is fine.

Hope this helps.
Thanks a lot. Bye

**Comment by Dialga** [comment]
```
$ v help watch
v watch [--clear] [--ignore .db] [--add /path/to/a/file.v] [other V options] [run] program.v

Description:
`v watch` collects all .v files needed for a compilation, then when
any of the .v source files changes, it re-runs the compilation.
...
```
Use `v watch run .` to build and run the source file, watch without run will only recompile the file.

**Comment by smartiniOnGitHub** [comment]
ok, thanks for the help and sorry for the noise. Bye
