### ISSUE TITLE
Plan for string interpolation transition

### ISSUE THREAD

**Issue by Gladear** [vlang/v#11162]
**Context**
Current syntax for string interpolation was voted for replacement. It causes too much trouble making a context-free grammar for VLS, and is inconsistent (multiple way to do the same thing, `$` or `${}`; `$` is reserved for compile-time operations).

The plan is to replace it with a bracket-only `{}` syntax.

**Proposal**
The transition cannot be done easily with `v fmt`, there are issues finding whether a string was transitioned to the new syntax or not since `{` is currently a valid character in a string.

To ease the transition, a temporary syntax is going to be introduced: f-strings.
f-string are strings prefixed with the `f` character (e.g. `f'this is a f-string'`). Prefixed string already exist for C-string and raw strings, so this won't introduce a whole new feature just for the sake of this transition.

f-strings will be parsed using the new syntax, while normal string will be parsed using the former syntax.

**Plan**
First step
- introduce the new f-string syntax, supporting bracket-only `{}` interpolation, other string are treated the same way as before
- add a notice when using a the former interpolation syntaxes `$` and `${}`
- make `v fmt` output f-strings only

Some time in
- remove the `$` and `${}` syntaxes from the compiler
- make `v fmt` remove the `f` prefix from f-strings, the bracket-only `{}` syntax becomes the default
- add a notice when prefixing a string with `f`

Then
- remove the `f` prefix

**Comment by penguindark** [comment]
I agree on the plan, only a small note from mine:
having the f in front of the strings can speed up a lot the compiling process, it is a shame lose this advantage.

**Comment by rempas** [comment]
> I agree on the plan, only a small note from mine:
> having the f in front of the strings can speed up a lot the compiling process, it is a shame lose this advantage.

How's that?

**Comment by rempas** [comment]
It's funny because I used to be a guy that will get annoyed for having to add an extra character ($) but funny enough, I know thing that it's more readable. And In any case, I don't think it's very important. A lot of code will need to change which is something to consider when we `change` stuff from the language. Let's see what the developers have to say

**Comment by JalonSolov** [comment]
It would speed up compilation because the compiler would know immediately from the leading `f` that it was a string with interpolation.  V already has leading `r` to mean `raw` strings, and `c` to mean c-style strings.

**Comment by srackham** [comment]
Looks like the bracket-only `{}` syntax has become the default, but I couldn't find any notification of this transition:

**V version:** V 0.3.1 c6158e4
**OS:** linux, Ubuntu 22.04.1 LTS (VM)

**What did you do?** Executed the following code:
```v
s := '{foo}'
println(s)
```

**What did you expect to see?** Should print `{foo}`

**What did you see instead?**
```
$ v run bug.v
bug.v:1:8: error: undefined ident: `foo`
    1 | s := '{foo}'
      |        ~~~
    2 | println(s)
```

**Comment by shove70** [comment]
Mm-hmm. It is string injection. The document should be updated after the problem is fixed

**Comment by medvednikov** [comment]
@srackham it's not the default yet, just a third option.

We'll make it the default one soon.

**Comment by medvednikov** [comment]
Oh, you mean the default without the `f` prefix. Yes, that's true.

**Comment by ArtemkaKun** [comment]
Is this not actual anymore? Since some time ago V only had one interpolation syntax `${}`?

**Comment by JalonSolov** [comment]
Yes, the change was made a while ago.  String interpolation is `${}`.
