### ISSUE TITLE
vlang vs Assembly

### ISSUE THREAD

**Issue by zach83** [vlang/v#11169]
I am curious to see if there is any **documentation** on the relation of Assembly languages with this project. 
As others have previously asked of, it would be cool to really understand just _how_ low-level this language is (or can go).

_Along these things, is there a location where some kind of white-paper/blueprint lies for vlang?_

#95

**Comment by JalonSolov** [comment]
https://github.com/vlang/v/blob/master/doc/docs.md#inline-assembly

These are the current "official" docs.  There are no white-paper/blueprint/etc. files for V.
