### ISSUE TITLE
Assigning to struct violates pointer to immutable field

### ISSUE THREAD

**Issue by ntrel** [vlang/v#1116]
This is related to #41, but here the problem is struct assignment:
```
struct S {
	val int
}

fn main() {
	mut s := S{3}
	//s.val++ // error: can't modify val
	p := &s.val // p points to an immutable int
	//*p = 1 // error: p is immutable
	s = S{7} // this violates immutable *p
	assert *p == 3
}
```
* As `*p` is immutable, struct assignment violates `*p`
* If `*p` was typed as mutable (as a workaround), then `*p = 1` violates immutable `s.val`

I think we should disallow struct assignment when the struct has an immutable field.

**Comment by dcurrie** [comment]
This also highlights an isue I raised on the V forum: the `mut s := x` statement makes both the variable  `s` and the value `x` mutable, which is a very coarse control... these are two very different things. The conflation of these two concepts is what make this struct bug possible.

**Comment by medvednikov** [comment]
I'll take care of this after the release of vweb and generics.

**Comment by nedpals** [comment]
The latest V version now emits an error:

```
main.v:7:4: error: field `val` of struct `Ss` is immutable
    5 | fn main() {
    6 |     mut s := Ss{3}
    7 |     s.val++ // error: can't modify val
      |       ~~~
    8 |     p := &s.val // p points to an immutable int
    9 |     *p = 1 // error: p is immutable
main.v:9:3: error: `p` is immutable, declare it with `mut` to make it mutable
    7 |     s.val++ // error: can't modify val
    8 |     p := &s.val // p points to an immutable int
    9 |     *p = 1 // error: p is immutable
      |      ^
   10 |     s = Ss{7} // this violates immutable *p
   11 |     assert *p == 3
```

**Comment by ntrel** [comment]
@nedpals i think those errors are the same as when i filed this.

Instead, I think I made the wrong assumption. An immutable pointer itself should not change, but what is pointed to can change. So V immutability is not transitive.
