### ISSUE TITLE
Negative literal for u64 parameter accepted by the compiler

### ISSUE THREAD

**Issue by VincentLaisney** [vlang/v#11172]
**V version:** V 0.2.2 bdf11d9, timestamp: 2021-08-26 15:20:54 +0300
**OS:** `linux, Linux version 5.13.6-200.fc34.x86_64 (mockbuild@bkernel02.iad2.fedoraproject.org) (gcc (GCC) 11.1.1 20210531 (Red Hat 11.1.1-3), GNU ld version 2.35.1-41.fc34) #1 SMP Wed Jul 28 15:31:21 UTC 2021 (VM)`

I wrote this test program:
```v
import gmp

fn main() {
        a := gmp.from_str('12345678901234567890')  or {panic('')} // corrected
	mut b := gmp.mul_2exp(a, -48)  // CORRECTED because of the change of the API of gmp-v
        println('${b}')
}
```

The definition of `gmp.mul_2exp` (in module gmp file gmp.v) is
```v
fn C.mpz_mul_2exp (&Bigint, &Bigint, u64)

/// mul_2exp is binding to mpz_mul_2exp
pub fn mul_2exp (mut r Bigint, a Bigint, b u64) {
	C.mpz_mul_2exp (&r, &a, b)
}
```

I compiled it without error message
```
v essai.v
```
By running it I get a system error:
```
./essai 
gmp: overflow in mpz type
7fd36ebfc2a2 : at ???: RUNTIME ERROR: abort() called
```

**What did you expect to see?**
Actualy according to thhe docs the last parameter of `mul_2exp` must be unsigned and a negative number is interpretated by the function as an enormous positive number.
I shoud expect a compilation error because a signed number cannot be converted in a unsigned number.
In this case it gave an enormous unsigned number that caused the overflow system error.
cf. this diagram from the docs:
```
    i8 → i16 → int → i64
                  ↘     ↘
                    f32 → f64
                  ↗     ↗
 byte → u16 → u32 → u64 ⬎
      ↘     ↘     ↘      ptr
   i8 → i16 → int → i64 ⬏
```
 
**What did you see instead?**
No compilation error or warning but later a system fault, an overflow as written above.

**Note**
The bug does not happen (the compiler displays an error lile
```
essai.v:6:27: error: cannot use `int` as `u64` in argument 2 to `gmp.mul_2exp`
```
if: a cast is put around the literal: `i16(-48)`
or a variable is initialized and used, even without explicit type: `c := -1` in this case the preceding error message is diplayed.

**Comment by mcastorina** [comment]
What is `c` in your example? I'm guessing that's the negative number that overflows?

In any case, casting negative values to unsigned types is a feature of V. Perhaps explicit casting should be allowed and implicit disallowed to prevent these sorts of mistakes. In other words:

```v
fn test(_ u32) {}

test(-1)      // not allowed
test(u32(-1)) // allowed
```

**Comment by MCausc78** [comment]
Does not reproduces on latest V:
```
PS D:\Games\Proekti\V\interactions> type test2.v
fn mul_2exp(a string, b u64) {
}

mul_2exp('a', -48)
PS D:\Games\Proekti\V\interactions> v version
V 0.4.4 2a68e2b
PS D:\Games\Proekti\V\interactions> v run test2.v
test2.v:4:15: error: cannot use literal signed integer as `u64` in argument 2 to `mul_2exp`
    2 | }
    3 |
    4 | mul_2exp('a', -48)
      |               ~~~
```
