### ISSUE TITLE
`is` on sumtypes in if doesn't work for following checks

### ISSUE THREAD

**Issue by Le0Developer** [vlang/v#11195]
**V version:** V 0.2.2 b72d1e5.ea4f6fd
**OS:** macos, Mac OS X, 10.15.7, 19H1323

**What did you do?**

```v
struct StructA {
    value int
}

struct StructB {
    value int
    offset int
}

type AB = StructA | StructB

fn main() {
    mut arr := []AB{}
    arr << StructA{0}
    arr << StructB{0, 1}

    for a_or_b in arr {
        if a_or_b is StructB && a_or_b.offset == 1 { // a_or_b.offset does not work here
            println(a_or_b.offset) // works here
        }
    }
}
```

**What did you expect to see?**

Successful compilation and a `1` printed.

 
**What did you see instead?**
```v
test.v:19:34: error: field `offset` does not exist or have the same type in all sumtype variants
   17 | 
   18 |     for a_or_b in arr {
   19 |         if a_or_b is StructB && a_or_b.offset == 1 {
      |                                        ~~~~~~
   20 |             println(a_or_b.offset)
   21 |         }
```

**Comment by thomas-mangin** [comment]
Just a bystander comment: Having the bracket as the boundary for type change is clear and allows to still perform further test without data type conversion. This would not be possible if the conversion was immediate. Keeping things as it, but requesting the developer to add an extra if in this example seems the better solution.

**Comment by medvednikov** [comment]
Yeah I'm not sure if this should be implemented.

It's nice, but it complicates the compiler, the language, and decreases readability a bit.

**Comment by Cons-Cat** [comment]
Maybe this case could have a more clear error message to explain what should be done instead.
