### ISSUE TITLE
.len is temporarily not allowed for security reasons

### ISSUE THREAD

**Issue by ntrel** [vlang/v#112]
Why is `arr.len` a security issue?

**Comment by medvednikov** [comment]
Because it's not private yet, hacker can set it to 99999999, and access memory outside the array, since they are no longer blocked by the bounds check.

**Comment by ntrel** [comment]
Thanks for explaining!

**Comment by mindplay-dk** [comment]
@medvednikov do you have an issue tracker somewhere else for private use? because this really seems like an important issue that ought to be tracked :-)

**Comment by medvednikov** [comment]
@mindplay-dk what do you mean "for private use"?

This is the only issue tracker.

**Comment by mindplay-dk** [comment]
Well, you closed the issue - so I was just wondering if you're tracking it somewhere else. It seems like an important issue that ought to be tracked, is all. Or maybe you fixed it already? :-)

**Comment by medvednikov** [comment]
Ah, no I closed it by mistake. I reopened it almost immediately.

**Comment by medvednikov** [comment]
`arr.len` is finally allowed.

It's no longer possible to modify public readonly fields.

**Comment by ntrel** [comment]
Great, thanks!
