### ISSUE TITLE
Regex logical or (a|b) not working

### ISSUE THREAD

**Issue by sblandford** [vlang/v#11227]
**V version: 0.2.2 c51f83e** 
**OS: linux, KDE neon User Edition 5.22** 

**What did you do?**
```
import regex

date_line := 'Mon Aug  9 09:13:21 UTC 2021'

date_query1 := '^(Mon)'
mut date_re1 := regex.regex_opt(date_query1) or { panic(err) }

date_query2 := '^(Mon|Tue)'
mut date_re2 := regex.regex_opt(date_query2) or { panic(err) }

start1, end1 := date_re1.match_string(date_line)
println('Query: $date_query1, start: $start1, end: $end1')

start2, end2 := date_re2.match_string(date_line)
println('Query: $date_query2, start: $start2, end: $end2')
```

**What did you expect to see?**
```
Query: ^(Mon), start: 0, end: 3
Query: ^(Mon|Tue), start: 0, end: 3
```
 
**What did you see instead?**
```
Query: ^(Mon), start: 0, end: 3
Query: ^(Mon|Tue), start: -1, end: 0
```

**Comment by JalonSolov** [comment]
V's regex is not the PCRE style you are used to using.

https://modules.vlang.io/regex.html
```
| the OR operator acts on tokens, for example abc|ebc is not abc OR ebc. Instead it is evaluated like ab, followed by c OR e, followed by bc, because the token is the base element, not the sequence of symbols.
```
If you need the PCRE style, you can try the libpcre wrapper module, https://github.com/vlang/pcre

**Comment by sblandford** [comment]
OK. Thanks for the clarification and apologies for bringing up expected behaviour as a bug.

**Comment by JalonSolov** [comment]
No problem... if you don't bring things up, you might just assume they're a bug, and think V is "broken".  Better to find out for sure.  :-)
