### ISSUE TITLE
Anonymous structs

### ISSUE THREAD

**Issue by dariotarantini** [vlang/v#1122]
Could you add nested structs?
Eg:
```
struct foo {
  x int
  ee struct {
    y int
  }
}
```

**Comment by vertical222** [comment]
Is these what you refer to?
https://github.com/vlang/v/blob/master/examples/nbody.v#L29

**Comment by medvednikov** [comment]
No they refer to anonymous structs.

**Comment by watzon** [comment]
Anonymous structs would be very useful for JSON (de)serialization

**Comment by medvednikov** [comment]
They will certainly be supported.
