### ISSUE TITLE
After installation -- the compiler doesn't work

### ISSUE THREAD

**Issue by l8atnight** [vlang/v#1126]
**V version:** 
0.1.14
**OS:** 
windows 64
**What did you do?**
install:
  git clone https://github.com/vlang/v
  cd v
  make    --- works with gcc, produces v.exe  (C:\mingw-w64\bin)

  v -o v compiler 

**What did you expect to see?**
a new v.c
 
**What did you see instead?**

_**Looks like you are running V for the first time.
V repo not found. Go to https://vlang.io to download V.zip
or install V from source.**_

v run examples/hello_world.v       **or** 
v run hello_world.v      in examples
also produces

**_Looks like you are running V for the first time.
V repo not found. Go to https://vlang.io to download V.zip
or install V from source._**

**Comment by medvednikov** [comment]
Try removing `C:/Users/youruser/.vlang/VROOT`

This will be fixed today.

**Comment by l8atnight** [comment]
tried, but didn't work

**Comment by medvednikov** [comment]
Do you have spaces in the path to V?

**Comment by l8atnight** [comment]
yes, but i set in a the path in a admin cmd to some other place - without spaces, since i read the post of another user. it did not work then, thats why I posted the bug.

**Comment by l8atnight** [comment]
why don't you put that .vlang into the compilers directory?

**Comment by l8atnight** [comment]
@medvednikov 
hi, is there a solution in sight? I really would like to use the language.

**Comment by medvednikov** [comment]
@l8atnight try moving your `v/` directory to `C:/` and removing `C:/Users/youruser/.vlang/VROOT`

**Comment by l8atnight** [comment]
did  all that. it creates C:/Users/youruser/.vlang -- no VROOT

v -o v compiler     or       v -o b compiler
**Looks like you are running V for the first time.
V repo not found. Go to https://vlang.io to download V.zip
or install V from source.**

bummer

**Comment by medvednikov** [comment]
Ok, I'll push V 0.1.15 today without VROOT.

It should work. I'll let you know once it's live.

**Comment by l8atnight** [comment]
mille grazie!!!!

**Comment by medvednikov** [comment]
Done.

Please try again @l8atnight 

```
git pull
make
```

**Comment by hhrhhr** [comment]
```
> git pull
Already up to date.
> curl -sO https://raw.githubusercontent.com/vlang/vc/master/v.c
> gcc -std=gnu11 -w -o vc.exe v.c
> vc.exe examples\hello_world.v
VROOT=d:\tmp\v\vc.exe
vlib not found. It should be next to V executable.
Go to https://vlang.io to install V.
```
pay attention to this:
VROOT=d:\tmp\v\\**vc.exe** <- !!!

**Comment by medvednikov** [comment]
The Windows separator bug was fixed.

**Comment by medvednikov** [comment]
@hhrhhr @l8atnight 

`No such file or directory` bug was also fixed. Should work fine now.

**Comment by hhrhhr** [comment]
Alas...
```
> vc.exe examples\game_of_life\life.v
VROOT=d:\tmp\v
vlib not found...
```
Because _v.c_ still contains _return attr == os__FILE_ATTRIBUTE_DIRECTORY;_

After fixing this and rebuilding, V only works in the same directory as the source.
```
> vc.exe examples\hello_world.v
VROOT=d:\tmp\v
failed to create C:\Users\adm//.vlang//examples\hello_world.c
gcc: error: C:\Users\adm//.vlang//examples\hello_world.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
V panic: clang error
> cd examples
> ..\vc.exe hello_world.v
VROOT=d:\tmp\v
> hello_world.exe
Hello, World!
```

```
> cd compiler
> ..\vc.exe -prod .
VROOT=d:\tmp\v
failed to create C:\Users\adm//.vlang//d:\tmp\v\compiler.c
gcc: error: C:\Users\adm//.vlang//d:\tmp\v\compiler.c: Invalid argument
gcc: fatal error: no input files
compilation terminated.
V panic: clang error
```

**Comment by medvednikov** [comment]
ok `dir_exists` is broken on Windows.

I wonder why it works for me and in Travis.

Will fix the `dir_exists` function.

**Comment by medvednikov** [comment]
> V only works in the same directory as the source

This was introduced today, will fix asap.

**Comment by medvednikov** [comment]
> After fixing this and rebuilding

@hhrhhr if you fixed `dir_exists` can you paste the fix here pleaes?

**Comment by hhrhhr** [comment]
For Windows, this option works (in v.c):
```
#define os__INVALID_FILE_ATTRIBUTES -1
// skip
DWORD dwAttrib = GetFileAttributes(szPath);
return (dwAttrib != INVALID_FILE_ATTRIBUTES &&  (attr & FILE_ATTRIBUTE_DIRECTORY));
```

> I wonder why it works for me and in Travis.

For example, because your directories do not have "compressed", "not indexed" or "encrypted" flags (FILE_ATTRIBUTE_COMPRESSED (0x800), FILE_ATTRIBUTE_NOT_CONTENT_INDEXED (0x2000), FILE_ATTRIBUTE_ENCRYPTED (0x4000)) ;)

**Comment by medvednikov** [comment]
@hhrhhr 

Thanks. I've pushed a temporary fix, should work now.

**Comment by l8atnight** [comment]
hi,
unfortunatly i get now:

F:\V\examples>..\v hello_world.v
VROOT=F:\V
vlib not found. It should be next to V executable.
Go to https://vlang.io to install V.

**Comment by medvednikov** [comment]
Does it work for you now @l8atnight ?
