### ISSUE TITLE
vlib pkconfig doesn't find some installed packages

### ISSUE THREAD

**Issue by xandro0777** [vlang/v#11266]
On Debian Bullseye 32 bit pkgconfig doesn't find an installed /usr/lib/i386-linux-gnu/pkgconfig/gtk+-3.0.pc  happens for example when compiling ui/examples/webview (see https://github.com/vlang/ui/issues/317 )

Obviously the path isn't in the list of default_paths : is there some way to pass additional paths in enviroment variables?

Seems to me that trying to hardcode all possible paths is not practicable, for each architecture and distribution there can be a few variants.

At least on this system pkg-config can be used to get a list of paths where to search which could be cached in vlib:
```
$ export PKG_CONFIG_DEBUG_SPEW=true
$ pkg-config
PKG_CONFIG_DEBUG_SPEW variable enabling debug spew
Adding directory '/usr/local/lib/i386-linux-gnu/pkgconfig' from PKG_CONFIG_PATH
Adding directory '/usr/local/lib/pkgconfig' from PKG_CONFIG_PATH
Adding directory '/usr/local/share/pkgconfig' from PKG_CONFIG_PATH
Adding directory '/usr/lib/i386-linux-gnu/pkgconfig' from PKG_CONFIG_PATH
Adding directory '/usr/lib/pkgconfig' from PKG_CONFIG_PATH
Adding directory '/usr/share/pkgconfig' from PKG_CONFIG_PATH
Global variable definition 'pc_sysrootdir' = '/'
Global variable definition 'pc_top_builddir' = '$(top_builddir)'
no output option set, defaulting to --exists
Error printing disabled by default due to use of output options --exists, --atleast/exact/max-version, --list-all or no output option at all. Value of --print-errors: 1
Error printing enabled
Adding virtual 'pkg-config' package to list of known packages
Must specify package names on the command line
```

BTW don't know where PKG_CONFIG_PATH is defined, it is not an enviroment variable.

**Comment by Dialga** [comment]
From the docs:
```
The .pc files are looked up into a hardcoded list of default pkg-config paths, the user can add extra paths by using the PKG_CONFIG_PATH environment variable. Multiple modules can be passed.
```

So you can simply run `PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig pkgconfig gtk+-3.0` to add another path.
