### ISSUE TITLE
Compile time if for #include

### ISSUE THREAD

**Issue by justicesuh** [vlang/v#1127]
Does V support compile time Ifs for `#include`

I'm trying to add Windows support to `net.socket` but the compiler is ignoring the `$if` and says `#include <winsock2.h>` does not exist on Linux

**Comment by medvednikov** [comment]
Yes, it's something I've wanted for a long time.

You should youse `socket_win.v` and add includes there for now.

**Comment by medvednikov** [comment]
No, #includes are still supported, this issue is still relevant.

**Comment by Dialga** [comment]
V supports comptime $ifs for detecting the OS now.
See https://github.com/vlang/v/blob/master/doc/docs.md#if-1

**Comment by Gladear** [comment]
```v
$if windows {
    #include <winsock2.h>
}
```
Now works.
