### ISSUE TITLE
left shiftings type returns any_int

### ISSUE THREAD

**Issue by barrack-obama** [vlang/v#11275]
**V version:** 
V 0.2.2 5bd602d.2f6b2dd

**OS:** 
linux, Ubuntu 18.04.5 LTS (VM)

**What did you do?**
```
fn main() {
        println(typeof(1 << 2)) // 4
}
```

**What did you expect to see?**
```int```
 
**What did you see instead?**
```any_int```

I'm not sure if it is supposed to be any_int, because in many other languages, it would return int. I also can't cast it to be int.

**Comment by JalonSolov** [comment]
If you want to see the type, use `typeof().name`, `any_int` is an internal name meaning `it is an integer`, but without specifying size, etc.
```v
println(typeof(1 << 2).name)
```
Output is
```
int literal
```

**Comment by barrack-obama** [comment]
Ah okay, thank you.
