### ISSUE TITLE
Compiler crash with static maps

### ISSUE THREAD

**Issue by Wertzui123** [vlang/v#11299]
**V version:** V 0.2.2 96398ef
**OS:** Windows

**What did you do?**
```v
[unsafe]
fn foo() map[string]int {
	mut static x := map[string]int{}
	return x
}

fn main() {
	unsafe {
		foo()
	}
}
```

**What did you expect to see?**
No compiler crash.
 
**What did you see instead?**
(using -cg)
```
path/to/temp/file.c: warning: WINVER redefined
path/to/temp/file.c: warning: implicit declaration of function 'tcc_backtrace'
path/to/temp/file.c: warning: assignment makes pointer from integer without a cast
path/to/temp/file.c: warning: cast between pointer and integer of different size
path/to/temp/file.c: error: initializer element is not constant
```

**Comment by wilsonk** [comment]
On linux I get this error with the code sample above:

```
==================
/tmp/v/test.6434366002668152560.tmp.c:10321: error: initializer element is not constant
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
.
.
.
```

**Comment by felipensp** [comment]
This is an restriction on the C compilers. Maybe add a checker error?

**Comment by sanjai0py** [comment]
I see that this issue is still open. May I work on it?

**Comment by JalonSolov** [comment]
Anyone can.  Just create a PR with your changes.

See the `Contributing.md` file in the root of the V repo.

**Comment by Delta456** [comment]
> This is an restriction on the C compilers. Maybe add a checker error?

I don't think static maps should be allowed in the first place.

**Comment by felipensp** [comment]
> > This is an restriction on the C compilers. Maybe add a checker error?
> 
> I don't think static maps should be allowed in the first place.

It is a compiler restriction. You can have fixed arrays, but not maps. Só It must be a checker error.
