### ISSUE TITLE
Multi-dimentional array doesn't compile with empty inner array

### ISSUE THREAD

**Issue by Spriithy** [vlang/v#113]
I would expect this

```
fn main() {
	arr := [[0], []]
}
```

to compile, but instead it gives 

```
test.v:2
bad array element type `array_` instead of `array_int` 
```

I would expect the `[]`'s type to be inferred as `[0]`'s, which comes first in the array declaration. 
Today I would otherwise write

```
fn main() {
	arr := [[0], []int]
}
```

which compiles fine (but should it really ?). But this raises some concern in me. `[]int` can be understood as both a type and a value. Go provides us with two options

```go
func main() {
    arr := new([]int)
    arr = []int{}
}
```

Again,

```
fn main() {
	consume( []int)
}

fn consume(arr[]int) {
}
```
This compiles fine in V. Is this a bug ?

**Comment by medvednikov** [comment]
Thanks, @Spriithy. Good finds.

I implemented basic multi-dimentional array support yesterday, it's still very unstable.

Will fix.

` []int` creates an empty int array. I don't like this syntax.

**Comment by medvednikov** [comment]
Fixed.
