### ISSUE TITLE
== function for alias of C.struct leads to incorrect C code.

### ISSUE THREAD

**Issue by VincentLaisney** [vlang/v#11317]
**V version:** V 0.2.2 bdf11d9, timestamp: 2021-08-26 15:20:54 +0300
**OS:** Linux Fedora 34

**What did you do?**
For the type gmp.Bigint I have overridden the == (equals) function:
`pub fn (a Bigint) == (b Bigint) bool {
	return C.mpz_cmp (&a, &b) == 0
}`

And I made the following test:
`fn test_equal () {
	a := gmp.from_u64(438)
	b := gmp.from_f64(438.0)
	assert a == b
}`

**What did you expect to see?**
I expected that the test pass or at least compile correctly.

Actually the functions for less (<) and more (>) run normaly:
`fn test_less () {
	a := gmp.from_u64(437)
	b := gmp.from_f64(438.0)
	assert a < b
}

fn test_more () {
	a := gmp.from_u64(439)
	b := gmp.from_f64(438.0)
	assert a > b
}`
 
**What did you see instead?**

But I got a C compiler bug:
`/tmp/v/gmp_test.16217659946744222943.tmp.c:20808: error: identifier expected
builder error: 
C error. This should never happen.`

And actually the generated C code is as follows:
`	// assert
	if (struct __mpz_struct__eq(a, b)) {`

The definition of the Bigint type is namely:
`type Bigint = C.__mpz_struct`

But for `less` and `more` the naming of the generated function is better:
`	if (gmp__Bigint__lt(a, b)) { `

It seems to be a naming problem of the generated function.

**Comment by nedpals** [comment]
Unofficial answer: 

Operator overloading for C structs won't be permitted so it should have an error message about it. Aliases C structs/typedefs are a different story I think.
![Screen Shot 2021-08-31 at 11 19 18 AM](https://user-images.githubusercontent.com/7358345/131436344-1dd811db-f907-48dd-9489-c7039e7fbee7.png)

**Comment by VincentLaisney** [comment]
The < overload gives correct code.
In this case they are indeed aliases of C struct. The problem is that the compiller treats them as C struct. See the c code I have given in the 'what you see' section

**Comment by medvednikov** [comment]
@nedpals but this is not a C struct?

```

**Comment by medvednikov** [comment]
What's the deinition of `gmp.Bigint`?

**Comment by nedpals** [comment]
@medvednikov `BigInt` is an alias of a C struct as stated.

```
type Bigint = C.__mpz_struct
```

**Comment by medvednikov** [comment]
Ok.

I don't know whether op overloading should be allowed. I guess yes, since we allow functions like `fn plus(a C.Foo, b C.Foo) {}`

**Comment by VincentLaisney** [comment]
All other overloads (+, -, /, *, % and <) function. Why not ==?

**Comment by spytheman** [comment]
Potentially fixed by https://github.com/vlang/v/commit/0b6d585b0710d384206fa5bbc38e883904eb79f8 .
