### ISSUE TITLE
Memory safety: thoughts on not allowing mutable references to array elements?

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#1131]
Hi,

I'm considering removing mutable references to array elements. This code will no longer compile:

```
struct User {
        mut:
        age int
}

mut users := [User{20}, User{30}, User{40}]
mut user := &users[0]
user.age = 21
```

Instead, indexing has to be used:

```
users[0].age = 21
```

So it'll be similar to how  `for` loops already work. The values are immutable, and if we need to modify the array, we must use indexing.

```
for i, user in users {
  if user.age > 18 {
    users[i].can_register = true
  }
}
```

This will greatly simplify memory management during compilation. And from my own experience, I can say that it will make the code more understandable and transparent. There can be no mutable reference that can modify the array at any moment.

**Comment by watzon** [comment]
Sounds good to me

**Comment by medvednikov** [comment]
This means some code will become more verbose. For example, in Vid I have

`views []View` and `cur_view *View`

This will no longer work.

Instead of `view.open_file()` etc I'll have to use `views[view_idx].open_file()`.

So perhaps some syntax sugar can be introduced to make this less verbose and more readable.

**Comment by iredmail** [comment]
Awesome. This is better readability. No more “&”, “*” symbols.

**Comment by joe-conigliaro** [comment]
It can be handy sometimes to have a reference to the element. But for the sake of memory management, and easy to understand code I think it's a good idea!

**Comment by ntrel** [comment]
1. This is very limiting.
2. Will passing arr[i] as a mut argument still work?
3. This doesn't solve the real problem of pointers to mutable data. All the same safety issues still exist for those. Forbidding them just for arrays only makes arrays less useful.

**Comment by medvednikov** [comment]
> Will passing arr[i] as a mut argument still work?

yes

> This doesn't solve the real problem of pointers to mutable data. All the same safety issues still exist for those. Forbidding them just for arrays only makes arrays less useful

This is unrelated. 

How is it limiting and making arrays less useful?

**Comment by ntrel** [comment]
> yes

We need to make sure that the `mut` parameter address don't escape then.

> This is unrelated

It's not. V could track pointer escaping instead. Non-escaping array element pointers don't affect memory safety. Escape tracking would be generally useful, e.g. for tracking struct pointer lifetimes.

> How is it limiting

As you said, code becomes more verbose. If V had local references maybe that would cover that use case.

But also calling C functions that take a `*Elem` won't work.

**Comment by ntrel** [comment]
BTW it's not just verbosity - repeating an array index expression with a mutable index variable is bug prone.

(Also if the index expression is not an identifier, we also have to introduce a temporary variable, which may be accidentally used later in the function).

**Comment by medvednikov** [comment]
Ok, perhaps local non-escaping references can be allowed. I'll think about this.

**Comment by ntrel** [comment]
I'm a bit confused why this issue doesn't suggest disallowing *immutable* references to array data. I assume the idea is to reference-count the number of arrays that point to the heap memory, and when that count falls to zero, free the memory. Is this the plan? If so immutable references allow invalid reads.

I think the principle of not escaping pointers to container owned data is good. We could disallow `&arr[i]` by default, but allow it in an `unsafe` block. It's then up to the programmer not to let that address escape the last array that owns that memory. This allows calling C functions and the `cur_view *View` code to work (inside an `unsafe` block). Then later we can decide whether to support non-escaping references.

**Comment by medvednikov** [comment]
`cur_view *View` is  a field of the global context struct, so it makes compilation time memory management trickier.

**Comment by ntrel** [comment]
OK, I meant a `&arr[i]` address that does not outlive `arr` (or another array that uses the same memory).

**Comment by tealin** [comment]
This will increase the cost of learning programs, and more considerations should be taken into account when writing code.

I think the goal of V is simple. Simplicity should allow the coder to focus on the logical level of the problem, rather than thinking about how to solve the underlying implementation problem.

**Comment by ntrel** [comment]
> I assume the idea is to reference-count the number of arrays that point to the same heap memory

See #1247 for a problem with RC memory safety with mut parameters.

**Comment by ntrel** [comment]
@medvednikov is planning to not allow mutable arguments of primitive type. See #1309 for why that and disallowing mutable references to `arr[i]` is bad for understanding code.

**Comment by medvednikov** [comment]
Mutable references to array elements are going to be allowed as long as they don't escape.

**Comment by ntrel** [comment]
Apparently not if the array element is of primitive type:

> don't allow primitive arguments to be modified.

From 0.1.17 changelog.
