### ISSUE TITLE
Erroneous values when using fixed sized arrays with trailing struct literal syntax

### ISSUE THREAD

**Issue by DEFAULTSAAS** [vlang/v#11325]
**V version:** V 0.2.2 d7490ab
**OS:** Windows 10 x64

**What did you do?**
I created a 'config' struct 'PlayerConfig' for initialising another struct 'Player', with one of the fields, the players location, being a fixed sized array.
I then created a function which accepts the config struct and then returns an initialised version of the main struct.

**What did you expect to see**
The players X and Y locations being zero.

**What did you see instead?**
When calling this function and then running the game, the player was no where to be seen.
After some investigating I found that is was due to their position being set to incorrect values.
I then replaced the fixed sized arrays with normal arrays and the issue no longer occurred.

I also attempted to create a generic function which creates and initialises a fixed sized array manually to fix the issue, but could not get it working. Either there were issues with a template parameter not being able to be used as an array, or the fact that creating a fixed sized array with a function parameter determining its size not being allowed, like how VAR's are not allowed in most C compilers. However, I couldn't find anything which explicitly said that this was not allowed.

I am relatively new to the language, only using it for about 3 - 4 days.
It has been a nice break from programming C++ :)

``` V
struct PlayerConfig {
	local_key_manager &GameKeyManager
	player_char string = 'P'
	player_pos [2]int = [0,0]!
	move_interval f64 = 0.1
}

struct Player {
	mut:
	local_key_manager &GameKeyManager
	input_update_time f64
	move_interval f64

	pub:
	player_char string

	pub mut:
	player_pos [2]int
}

pub fn new_player(in_config PlayerConfig) &Player {
	return &Player {
		local_key_manager : in_config.local_key_manager 
		player_char : in_config.player_char 
		player_pos : in_config.player_pos 
		move_interval : in_config.move_interval }
}

pub fn create_generic_array<T,U>(in_vals ...T) U {
	size := int(in_vals.len)
	mut temp_arr := [size]T{}

	for i := 0; i < temp_arr.len; i++ {
		temp_arr[i] = in_vals[i]
	}

	return temp_arr
}
// error: non-constant array bound 'size' - mut temp_arr := [size]T{}
mut main_player := new_player(PlayerConfig{&key_manager,'P',create_generic_array<int,[2]int>(0,0),0.1})

pub fn create_generic_array<T,U>(in_vals ...T) U {
	mut temp_arr := U{}
	for i := 0; i < temp_arr.len; i++ {
		temp_arr[i] = in_vals[i]
	}

	return temp_arr
}
// error: 'U' has no property 'len' - generic type U does not support indexing...
mut main_player := new_player(PlayerConfig{&key_manager,'P',create_generic_array<int,[2]int>(0,0),0.1})

// main_player.player_pos[0] returns values in the millions instead of 0
mut main_player := new_player(PlayerConfig{&key_manager,'P',[0,0]!,0.1})
```

**Comment by medvednikov** [comment]
As @JalonSolov explained, this works as expected. Dynamic arrays should be used in this example instead of fixed arrays.
