### ISSUE TITLE
SIGSEGV on infinite loop without error message

### ISSUE THREAD

**Issue by Lathanao** [vlang/v#11342]
**V doctor:**
```
OS: linux, "Manjaro Linux"
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
CC version: cc (GCC) 11.1.0

getwd: /var/www/vproject
vmodules: /home/tanguy/.vmodules
vroot: /var/www/vproject/vorigin
vexe: /var/www/vproject/vorigin/v
vexe mtime: 2021-08-30 15:25:56
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 f33f216

Git version: git version 2.32.0
Git vroot status: weekly.2021.33.2-107-gf33f2166
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 333c14de

```
**Context**
I was making a really long method with some resistivity.
I only understand the error when I removed all the logic to get only some few lines of code left.

**What did you do?**
`v -g -o vdbg cmd/v && vdbg /var/www/vproject/scarp/scrap_bug_SIGSEGV.v`
```v
module main

fn main() {
	recursive()
}

fn recursive() {
    recursive()
}
```

**What did you expect to see?**

Maybe an formatted error message saying that the code fall in a infinite loop.

**What did you see instead?**
```
Terminated by signal 139 (SIGSEGV)
```

**Comment by medvednikov** [comment]
That's how it works in other languages. This feature would complicate the compiler.
