### ISSUE TITLE
Inline Block => to simplify blocks with only 1 statament

### ISSUE THREAD

**Issue by cindRoberta** [vlang/v#11345]
Inline Block => to simplify blocks with only 1 statament
```v
// with {}
for nucleotide in dna {
  match nucleotide {
    `A` { rna.write_b(`U`) }
    `T` { rna.write_b(`A`) }
    `C` { rna.write_b(`G`) }
    `G` { rna.write_b(`C`) }
    else { rna.write_b(`?`) }
  }
}

// with =>
for nucleotide in dna =>
  match nucleotide =>
    `A` => rna.write_b(`U`)
    `T` => rna.write_b(`A`)
    `C` => rna.write_b(`G`)
    `G` => rna.write_b(`C`)
    else => rna.write_b(`?`)
```

**Comment by changrui** [comment]
No.

**Comment by zSnails** [comment]
Wouldn't this rely on indentation?

**Comment by medvednikov** [comment]
We don't have single line blocks in `if` or `match` by design.

**Comment by cindRoberta** [comment]
> We don't have single line blocks in `if` or `match` by design.

It's for any block, even function, while and others

**Comment by JalonSolov** [comment]
No single line blocks.  By design.

They're a few characters shorter without adding anything to functionality.

**Comment by cindRoberta** [comment]
> No single line blocks. By design.
> 
> They're a few characters shorter without adding anything to functionality.

@JalonSolov they add readability

**Comment by cindRoberta** [comment]
> Wouldn't this rely on indentation?

@zSnails no, it's similar to C# and Dart
