### ISSUE TITLE
Return type is not checked for mutable method receievers

### ISSUE THREAD

**Issue by Lathanao** [vlang/v#11341]
**V doctor:**
```
OS: linux, "Manjaro Linux"
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
CC version: cc (GCC) 11.1.0

getwd: /var/www/vproject
vmodules: /home/tanguy/.vmodules
vroot: /var/www/vproject/vorigin
vexe: /var/www/vproject/vorigin/v
vexe mtime: 2021-08-30 15:25:56
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 f33f216

Git version: git version 2.32.0
Git vroot status: weekly.2021.33.2-107-gf33f2166
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 333c14de

```
**Context**
I was trying this example. It's working.
https://github.com/vlang/v/blob/master/doc/docs.md#custom-iterators

Then, I modify the return type of next().
Maybe to result is good, but I don't understand it.

**What did you do?**
`v -g -o vdbg cmd/v && vdbg /var/www/vproject/test/struct_next.v`
```v
struct SquareIterator {
	arr []int
mut:
	idx int
}

fn (mut iter SquareIterator) next() ?int {
	if iter.idx >= iter.arr.len {
		return error('')
	}
	defer {
		iter.idx++
	}
	return iter   // Here I modify iter.arr[iter.idx] * iter.arr[iter.idx] by iter
	                      // iter type is SquareIterator, not ?int
}

nums := [1, 2, 3, 4, 5]
iter := SquareIterator{
	arr: nums
}
for squared in iter {
	println(squared)
}
```

**What did you expect to see?**

An error saying the return type of next method is wrong.

**What did you see instead?**
```
-8160
-8160
-8160
-8160
-8160
```

**Comment by mcastorina** [comment]
Great find. It looks like it's not specific to iterators though:

```v
struct Test {}

fn (mut test Test) test() ?int {
	return test
}

mut t := Test{}
dump(t.test() or {})
```

From my experiments:
* it works for any return type (`int` / `string` / `http.Request`)
* the return type must be an optional (otherwise it produces C errors)
* the method receiever must be mutable (`mut test Test`) otherwise it correctly checks the type
