### ISSUE TITLE
cond simplifying and readablying if / else if /else

### ISSUE THREAD

**Issue by cindRoberta** [vlang/v#11346]
```v
// if / else if /else
if false { println('if') }
else if  true { println('else if') }
else { println('else') }

// cond equivalent
cond {
  false { println('if') }
  true { println('else if') }
  else { println('else') }
}
  
// with inline operator
// https://github.com/vlang/rfcs/issues/11
// https://github.com/vlang/v/issues/11345
cond =>
  false => println('if')
  true => println('else if')
  else => println('else')
```

**Comment by crthpl** [comment]
This can be done with `match true`:

```v
match true {
    true { println('if') }
    false { println('else if') }
    else { println('else') }
}
```

V has a "one way" philosophy and is trying to stay as simple as possible.

**Comment by cindRoberta** [comment]
@crthpl I do a PR to add this to documentation: https://github.com/vlang/v/pull/11407

**Comment by JalonSolov** [comment]
`match` is already documented.

https://github.com/vlang/v/blob/master/doc/docs.md#match

**Comment by cindRoberta** [comment]
> `match` is already documented.
> 
> https://github.com/vlang/v/blob/master/doc/docs.md#match

it's good to evidence a particular feature on documentation, can avoid request as I do and asks in forums
