### ISSUE TITLE
glfw3.dll 32/64 bit

### ISSUE THREAD

**Issue by SuperAuguste** [vlang/v#1137]
**V version:** Commit 82ed015
**OS:** Windows 10

**What did you do?**
I attempted to run the Tetris example while following all of the given instructions exactly as written.

**What did you expect to see?**
A successful run of the Tetris example.
 
**What did you see instead?**
```bash
C:\Users\augus\Desktop\Programming\vlang\v/thirdparty/glfw/glfw3.dll: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
V panic: clang error
```

**Comment by medvednikov** [comment]
This is not about file paths. `glfw3.dll` is a 32 bit dll, and you are building a 64 bit binary, or vice versa. 

I'll fix that.

**Comment by aguspiza** [comment]
I think right now V windows version only supports 32bits, so you've better use the 32bits dll

**Comment by medvednikov** [comment]
Glfw dep will be removed anyway, I have unreleased opengl context creation logic in V and some input handling.

The fewer C deps, the better.

**Comment by medvednikov** [comment]
`gg` is going to work with DirectX, Metal, Vulkan. glfw is OpenGL only.

**Comment by deangelo2005** [comment]
Restructure all that can be rebuilt.

**Comment by SuperAuguste** [comment]
Thanks! I’ll wait for the new features.

**Comment by deangelo2005** [comment]
I've shared an item with you:

Creative_Commons_Enterprise_Analytics_Prior_30_Days___Jul_16_2019
https://docs.google.com/spreadsheets/d/1HJSzrFuX-0FLRPdvJcnCCvSlJvTRhMDBoQwaJP6MlGk/edit?usp=sharing&invite=COOvxBY&ts=5d2d7010

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

To the future of biotechnology and small town businesses

**Comment by deangelo2005** [comment]
I've shared an item with you:

Notes from "The Lonesome Gods, An Epic Novel of the California Desert"
https://docs.google.com/document/d/1AIW21BY8tfofWqPhqLW1CRzJNcnFMmGEf49gEfy8olQ/edit?usp=sharing&invite=CPytouwC&ts=5d2d8034

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

https://docs.google.com/document/d/1AIW21BY8tfofWqPhqLW1CRzJNcnFMmGEf49gEfy8olQ/edit?usp=drivesdk(Coventry  
Health  
Care)
