### ISSUE TITLE
Doesn't work with example :) 

### ISSUE THREAD

**Issue by rusmonkey** [vlang/v#114]
const (
        MAX = 15 
)

struct Fib {
        nums []int
}

fn (fib mut Fib) calc(n int) int {
        if n <= 1 {
                return n
        }
        if fib.nums[n] != 0 {
                return fib.nums[n]
        }
        fib.nums[n] = fib.calc(n - 1) + fib.calc(n - 2)
        return fib.nums[n]
}

fn main() {
        mut fib := Fib {
                nums: [0; MAX]
        }
        for i := 0; i < MAX; i++ {
                println(fib.calc(i))
        }
}

**Comment by SirJosh3917** [comment]
the fibonacci + memoization example is broken for me as well

**Comment by medvednikov** [comment]
This was fixed yesterday. 

Once I fix the modules bug I've been stuck with for hours, the fix will be live.

**Comment by medvednikov** [comment]
Fixed.
