### ISSUE TITLE
Bug matching the regular expression \S+

### ISSUE THREAD

**Issue by fxn** [vlang/v#11404]
**v doctor** 
OS: macos, macOS, 11.5.2, 20G95
Processor: 16 cpus, 64bit, little endian, Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
CC version: Apple clang version 12.0.5 (clang-1205.0.22.11)

getwd: /Users/fxn/AoC/2016/12
vmodules: /Users/fxn/.vmodules
vroot: /Users/fxn/v
vexe: /Users/fxn/v/v
vexe mtime: 2021-09-05 16:30:44
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 e1c762a.71f1be5

Git version: git version 2.32.0
Git vroot status: weekly.2021.33.2-144-g71f1be53
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 689c8a02

**What did you do?**

```v
import regex

mut re := regex.regex_opt(r'\S+')?
start, _ := re.match_string('X')
println(start)
```

**What did you expect to see?**

0
 
**What did you see instead?**

-1

**Comment by penguindark** [comment]
@fxn Tnx for the issue :)

**Comment by fxn** [comment]
That was quick! Thank you!
