### ISSUE TITLE
Cannot create alias of alias

### ISSUE THREAD

**Issue by iacore** [vlang/v#11416]
OS: linux, "Arch Linux"
V full version: V 0.2.4 b72a2de

**What did you do?**
```
struct Foo {}

type Bar = Foo

type Baz = Bar
```

**What did you expect to see?**
The above program should compile.
 
**What did you see instead?**
```
test.v:5:12: error: type `Bar` is an alias, use the original alias type `Foo` instead
    3 | type Bar = Foo
    4 | 
    5 | type Baz = Bar
      |            ~~~
```

**Why this feature is needed**
When a module exports an alias, there's no way to create an alias to that if the original type is private
example:
https://github.com/irishgreencitrus/raylib.v/blob/main/raylib.v#L382

**Comment by yuyi98** [comment]
The current rule is that alias of alias is illegal.

**Comment by medvednikov** [comment]
Yeah, we decided not to allow that to keep the language simple.
