### ISSUE TITLE
Regular expression substring does not match

### ISSUE THREAD

**Issue by fxn** [vlang/v#11424]
**V version:** 

```
OS: macos, macOS, 11.5.2, 20G95
Processor: 16 cpus, 64bit, little endian, Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
CC version: Apple clang version 12.0.5 (clang-1205.0.22.11)

getwd: /Users/fxn/tmp
vmodules: /Users/fxn/.vmodules
vroot: /Users/fxn/v
vexe: /Users/fxn/v/v
vexe mtime: 2021-09-07 05:26:44
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 e1c762a.aec016b

Git version: git version 2.32.0
Git vroot status: 0.2.4-55-gaec016bb
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 689c8a02
```

**What did you do?**

```v
import regex

mut re := regex.regex_opt(r'B')?
start, _ := re.match_string('AB')
println(start)
```

**What did you expect to see?**

1
 
**What did you see instead?**

-1

**Comment by penguindark** [comment]
It is working correctly, match performs only the match, it doesn't scan the string.
For your purpose you must use the find functions: https://github.com/vlang/v/tree/master/vlib/regex#find-and-replace

**Comment by fxn** [comment]
What do you mean? How do you define "match"? Do you mean it only matches the start of the string as if there was an implicit `\A` at the beginning?

**Comment by penguindark** [comment]
Yes, for every "sliding" match you must use the find functions.
By the way `\A` is used in V rgex as `matches only an uppercase char [A-Z]` : https://github.com/vlang/v/tree/master/vlib/regex#meta-chars

**Comment by fxn** [comment]
@penguindark Gotcha! I believe the docs could clarify this, since the word "match" is used all over them to mean matching, as in the regular vocabulary "a string matches this regexp" used in the context of regular expressions. Not just PCRE, I believe that verb is the common one, and `find` is not (think Perl or Ruby for example, who do not use PCRE).

Also, I believe it is confusing that `match_string` returns `start`. It you get a `start` you assume it can be something else than 0 and -1, otherwise `end` would be enough information.

**Comment by penguindark** [comment]
I'll think about it, thanks for your feedback. :)

**Comment by JalonSolov** [comment]
Heh... PCRE is based off Perl... the acronym stands for "Perl Compatible Regular Expressions".

**Comment by penguindark** [comment]
@fxn the fact that all the functions has `start, end` as result permit to swap functions between match and find without need to change the code that stay around them.
It was a design choice for simplify use of different functions like find and match and simplify the development of future expansions.

@JalonSolov I don't like Perl :D

**Comment by fxn** [comment]
@JalonSolov Yeah :), but they are not equivalent. As an edge case, Perl regular expressions can execute Perl code. See for example this backtracking embedded in [this regexp of mine](https://github.com/fxn/math-with-regexps/blob/9ddd281c6ba9acf8e059d7f5dde6caf3f0be4708/one-liners.sh#L8) that computes the number of divisors of a positive integer.

@penguindark OK!

**Comment by penguindark** [comment]
@fxn for sure you master the regex-fu :smiley:

**Comment by JalonSolov** [comment]
Oh, I didn't say Perl didn't allow downright nasty things like that.  Wouldn't work too well in other languages to try to execute Perl code, though, which is why that doesn't work in PCRE.   :-)
