### ISSUE TITLE
builtin: maps do not accept shorthand enum as key in declaration

### ISSUE THREAD

**Issue by islonely** [vlang/v#11447]
Maps do not allow shorthand enums during the declaration of the map. This code returns the following error. If you replace the shorthand enum with the full value during the declaration, then the code runs normally.
```v
struct Example {
    keys_down map[gg.KeyCode]bool = {
        .right: false
        .left: false
        .down: false
        .up: false
    }
}
```
the error:
```
error: invalid expression: unexpected token `:`
   12 | 
   13 | .right: false
   14 | .left: false
      |      ^
   15 | .down: false
   16 | .up: false
```

V doctor:
```
OS: linux, LMDE 4 (debbie)
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
CC version: cc (Debian 8.3.0-6) 8.3.0

getwd: /home/adamoates/Documents/weasel
vmodules: /home/adamoates/.vmodules
vroot: /home/adamoates/v
vexe: /home/adamoates/v/v
vexe mtime: 2021-09-05 18:52:13
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 2f6b2dd.71f1be5

Git version: git version 2.20.1
Git vroot status: weekly.2021.15-1493-g71f1be53 (35 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 333c14de
```

**Comment by Larpon** [comment]
Agreed it'd be a nice addition. I just came across this today as well and had to convert the enum to it's string representation as a workaround.

**Comment by medvednikov** [comment]
This has been picked up by Denis G.

**Comment by medvednikov** [comment]
This works:
```
keys_down map[gg.KeyCode]bool = {
        .right: false
}
```
And then V parses `false.left`.

**Comment by islonely** [comment]
Interesting. I came across something similar a while back, but forgot to report it. I think it was something like this. Idk if it was this exactly though. I'd have to test it. It worked correctly after adding commas after each shorthand enum.
```v
if enum_val in [
    .val1
    .val2
    .val3
] {}
```

**Comment by Delta456** [comment]
Works with the latest version of V
