### ISSUE TITLE
Loop on Maps start with minimum 3 items set 

### ISSUE THREAD

**Issue by Lathanao** [vlang/v#11442]
**V doctor:**
```
OS: linux, "Manjaro Linux"
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
CC version: cc (GCC) 11.1.0

getwd: /var/www/vproject
vmodules: /home/tanguy/.vmodules
vroot: /var/www/vproject/vorigin
vexe: /var/www/vproject/vorigin/v
vexe mtime: 2021-09-07 12:13:17
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 aec016b.0b6d585

Git version: git version 2.32.0
Git vroot status: 0.2.4-56-g0b6d585b (7 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 333c14de

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg /var/www/vproject/scarp/scrap_loop_maps_2.v`
```v
import time

fn main() {

	mut dic := map[string]int{}

	dic[time.ticks().str()] = 0

	for k, v in dic {
		dic[time.ticks().str()] = 0
		println("Looop " + k)
		time.sleep(1 * time.second)
	}
}
```

**What did you expect to see?**

I expect to see an infinit loop, because at each loop, the Maps get a new item.

**What did you see instead?**
Only one loop!

```v
scarp/scrap_loop_maps_2.v:14:9: warning: unused variable: `v`
   12 |     dic[time.ticks().str()] = 0
   13 | 
   14 |     for k, v in dic {
      |            ^
   15 |         dic[time.ticks().str()] = 0
   16 |         println("Looop " + k)
Looop 1631089422842
```

**How to fix that**
If you add 2 more item in the map, the loop works well.
I have no idea why I need to add 2 more items.
If I add only 1, it doesn't loop.

```v
import time

fn main() {

	mut dic := map[string]int{}

	dic[time.ticks().str()] = 0

	dic['aaaaaaaaa'] = 0  // add it more
	dic['bbbbbbbbb'] = 0  // add it more

	for k, v in dic {
		dic[time.ticks().str()] = 0
		println("Looop " + k)
		time.sleep(1 * time.second)
	}
}
```

With this modification, the result is :

```v
scarp/scrap_loop_maps_2.v:14:9: warning: unused variable: `v`
   12 |     dic[time.ticks().str()] = 0
   13 | 
   14 |     for k, v in dic {
      |            ^
   15 |         dic[time.ticks().str()] = 0
   16 |         println("Looop " + k)
Looop 1631089781503
Looop aaaaaaaaa
Looop bbbbbbbbb
Looop 1631089782503
Looop 1631089783503
Looop 1631089784503
etc...
```

**Comment by mcastorina** [comment]
You should not be able to modify a map while iterating over it. In my opinion, these examples should fail to compile.

**Comment by Lathanao** [comment]
Probably. But in my use case, it could be really useful to do it. 
Modify a array while iterating over it works well. Why not with map?

**Comment by JalonSolov** [comment]
No, it doesn't work well to modify _anything_ while iterating over it.  You may have just been lucky, so far... it _can_ work, but it can also throw indexes into disorder, or make you reference something you didn't expect... for example, if you delete something out of the middle of the array while iterating, the next index now points to the item _after_ what was deleted.

**Comment by Lathanao** [comment]
@JalonSolov 
Ok, I get it.
Thank you for the great explanation.
Maybe this issue can be closed.
