### ISSUE TITLE
No output from REPL

### ISSUE THREAD

**Issue by plinkplinkfizz** [vlang/v#1144]
I compiled v from source on a Manjaro; gcc 9.1.0.
Tried running something from the REPL.

Code:
`println('Hello World')`

Expected Output:
`Hello World`

Actual Output:
```

(absolutely nothing)
```

The compiled hello_world.v application does produce output though.

**Comment by Glitchfix** [comment]
```sh
>>> println('Hello, World')
Hello, World
>>> 
```

It works on Ubuntu I am not sure what might be the issue could you try to get the latest pull and build it.
I am not sure how different it is on Arch distributions.

**Comment by hazohelet** [comment]
rm ~/.vlang/VROOT might help you out.

**Comment by plinkplinkfizz** [comment]
> ```shell
> >>> println('Hello, World')
> Hello, World
> >>> 
> ```
> 
> It works on Ubuntu I am not sure what might be the issue could you try to get the latest pull and build it.
> I am not sure how different it is on Arch distributions.

I am on the latest code.

**Comment by plinkplinkfizz** [comment]
> `rm ~/.vlang/VROOT` might help you out.

Sorry mate, didn't work

**Comment by hazohelet** [comment]
Can I take a look at the generated C code, `~/.vlang/vrepl.c` ?
Again, can you run println() successfully outside vrepl?

**Comment by plinkplinkfizz** [comment]
Issue resolved with one of the latest commits.
