### ISSUE TITLE
Name Change “goroutines”

### ISSUE THREAD

**Issue by fenginsc** [vlang/v#1145]
“Concurrency
The concurrency model is very similar to Go. To run foo() concurrently, just call it with go foo(). Right now, it launches the function in a new system thread. Soon goroutines and the scheduler will be implemented.“
======================================================
V language is not golang.
goroutines were made by golang himself,Hopefully it can be replaced by coroutine or fiber,call it likes "v foo()",thanks

**Comment by medvednikov** [comment]
I've replaced all goroutines with coroutines on the website.

**Comment by neverix** [comment]
The keyword is still not changed though :/

**Comment by medvednikov** [comment]
The keyword is going to stay the same.

**Comment by ArnCarveris** [comment]
@medvednikov why?

**Comment by medvednikov** [comment]
Why not?

**Comment by joe-conigliaro** [comment]
@ArnCarveris go is a pretty decent name, it just means **go run this coroutine**

**Comment by neverix** [comment]
Yeah, it's not. I was thinking of something like `co` but I guess this could be confusing to some users.

**Comment by zuwa** [comment]
How about instead of goroutines "vein" and instead of go "run" or "flow?

**Comment by neverix** [comment]
Sounds great!
