### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by kahsa** [vlang/v#11458]
**V version:0.2.4 91c6eee** 
**OS:ArchLinux** 

**What did you do?**
```v
pub struct Foo {
	BAR string
}
```

**What did you expect to see?**
Error message such as "Cannot use capital letters.
 
**What did you see instead?**
```
/home/tsukasa/develop/vprojects/mytradetool/other/main.v:3:1: error: expecting type declaration
    1 | pub struct Foo {
    2 |     BAR string
    3 | }
      | ^
```

**Comment by spytheman** [comment]
The reason, is that V parses this as:
```v
pub struct Foo {
    BAR // embedding of another struct named BAR
    string /* field named `string` */  <expected type of the field named `string`>
}
```

**Comment by spytheman** [comment]
I am not sure how it can reliably detect and show a more precise error message, since the ambiguity comes from a valid syntax (struct embedding), and at the time of parsing, it does not know yet whether `BAR` is valid or not (it may be from another .v file from the same module).

**Comment by kahsa** [comment]
oh, I see that is the reason why this error happened while migrating process though.

```
pub struct NewsReuters {
pub:
	host string = 'https://jp.reuters.com'
	jp_archive string = '$host/news/archive'
	WIRE string = '$host/assets/jsonWireNews'
	// FOREX_GLOBAL_MARKET_REPORT string = '$jp_archive/forexGlobalMarketReport'
}
```
```
tcl/nws/news.v:70:2: error: struct embedding must be declared at the beginning of the struct body
   68 |     host string = 'https://jp.reuters.com'
   69 |     jp_archive string = '$host/news/archive'
   70 |     WIRE string = '$host/assets/jsonWireNews'
      |     ~~~~
```

**Comment by JalonSolov** [comment]
Yes, because only structs should start with capital letters, so it thinks you are trying to embed a struct too late.
