### ISSUE TITLE
v Can not run under DragonFlyBSD

### ISSUE THREAD

**Issue by lhmwzy** [vlang/v#1146]
**V version:** 
0.1.14
**OS:** 
DragonFly gxdb 5.6-RELEASE DragonFly v5.6.0.1.g3d5034-RELEASE #0: Tue Jun 18 09:09:55 CST 2019

**What did you do?**
cd /home/lhm/v ; make 

**What did you expect to see?**

 
**What did you see instead?**
rm -f v.c v vprod
curl -Os https://raw.githubusercontent.com/vlang/vc/master/v.c
cc -std=gnu11 -w -o v v.c -lm
./v -o v compiler
cc: warning: '-x objective-c' after last input file has no effect
cc: error: unrecognized command line option '-mmacosx-version-min=10.7'
V panic: clang error
*** Error code 1

Stop.
make: stopped in /home/lhm/v

**Comment by medvednikov** [comment]
I'll add support for all major BSD systems today. It's a quick fix.

**Comment by medvednikov** [comment]
Done.

I've tested on FreeBSD and OpenBSD. The other 2 should work as well.
