### ISSUE TITLE
Provide GMP bindings as V module

### ISSUE THREAD

**Issue by Piruzzolo** [vlang/v#11466]
https://gmplib.org/

Instead or as a complement to #11465

**Comment by Piruzzolo** [comment]
@dumblob thanks! P.S. i'm curious to take a look at those links 😄

**Comment by dumblob** [comment]
See https://github.com/vlang/vsl/issues/65 .

And if you'll be fine with that feel free to rename this issue to "provide GMP bindings as *V* module" or just close it :wink:.

**Comment by Piruzzolo** [comment]
@dumblob sure!
