### ISSUE TITLE
sqlite module does not work with `regexp` operator.

### ISSUE THREAD

**Issue by kahsa** [vlang/v#11470]
**V version:0.2.4 07bd615** 
**OS:ArchLinux** 

**What did you do?**

```v
import sqlite

mut db := sqlite.connect('news.db') or { return }
r, c := db.exec('select * from news where title regexp "^[ab]";')
println(c)
```

**What did you expect to see?**

returns code 101 since the same sql works on shell.

**What did you see instead?**

returns error code 21

**Comment by Dialga** [comment]
The [regexp operator is not defined by default](https://sqlite.org/lang_expr.html#the_like_glob_regexp_and_match_operators) in the sqlite library, it is a [loadable extension](https://sqlite.org/src/file/ext/misc/regexp.c) that you have compile yourself. It is only available in the sqlite shell.

**Comment by kahsa** [comment]
yeah. Could you tell me how to use it with V?

**Comment by JalonSolov** [comment]
You would have to write your own application defined SQL function, in either C or V (with C interop), and call the `sql_create_function` in the sqlite C API to get it added.  At least, that's what I gleaned from skimming the links pasted.
