### ISSUE TITLE
Unwrap optional with `if` statement

### ISSUE THREAD

**Issue by ntrel** [vlang/v#1148]
Here's some real code in `vlib/http/http_win.v`:
```
pos = url.index('/')
if pos > -1 {
	host = url.left(pos)
	...
}
...
```
`string.index` should return an optional int - see #804. But this breaks the flow of the code using `or`:
```
{
	pos := url.index('/') or {goto skip}
	host = url.left(pos)
	...
}
skip:
...
```
(The braces are necessary so that `pos` is not in scope after `skip`).
Instead, we could unwrap optionals with an `if` statement:
```
if pos := url.index('/') {
	host = url.left(pos)
	...
}
...
```
This would lower to:
```
{tmp := url.index('/')
if tmp.ok {
	pos := *(*T)tmp.data
	host = url.left(pos)
	...
}
...
```
The `if` statement can also have an `else` branch where `err` is defined but not `pos`.

**Comment by medvednikov** [comment]
Right, this makes sense and is necessary. I need to think about the syntax. `if pos := ` seems ok, but I'm a bit concerned that it's similar to `if pos ==`.

**Comment by ntrel** [comment]
Another option would be:
`pos := opt and {...} else {...}`. This would also be consistent with `or`.

**Comment by ntrel** [comment]
Looks like this is implemented in https://github.com/vlang/v/commit/5ba354fa2caa060c7c9397eafd00ce453c60b7ee

**Comment by medvednikov** [comment]
Indeed.

Some people suggested that it adds duplicate functionality, and now there are 2 ways to do the same thing basically.

Perhaps this can be used instead:

```
{
	pos := url.index('/') or { break }
	host = url.left(pos)
	...
}
```

**Comment by avitkauskas** [comment]
What if a modified suggestion of @ntrel would be implemented, like this:
```v
pos := opt and {...} or {...}
```
with the `and` part being optional?
Here `and` block would be executed only if Option has value, and `or` block otherwise.

**Comment by ntrel** [comment]
> 	pos := url.index('/') or { break }

It would be confusing if break in an `or` block actually broke out of the current scope instead of breaking a loop or match statement.

**Comment by medvednikov** [comment]
Interesting, I'll think about it.

**Comment by ntrel** [comment]
> pos := opt and {...} or {

`or` would need to be optional when `and` is present. 
This `or` form wouldn't terminate the current scope. I think it it's clearer to use `else`.

**Comment by avitkauskas** [comment]
No, I think `or`is always mandatory - you must always deal with the case of option having no value. But if option has value, in some cases you do not need to do anyhing specific about that, but in some cases you want (like in this url.index() case):
```v
pos := url.index('/') and {host = url.left(pos)} or {continue}
```

**Comment by ntrel** [comment]
> you must always deal with the case of option having no value

You actually don't need to, because the unwrapped value should only be visible in the `and` branch.

**Comment by avitkauskas** [comment]
> > you must always deal with the case of option having no value
> 
> You actually don't need to, because the unwrapped value should only be visible in the `and` branch.

It's tricky.  Even in my example above, what would happen in I try to use `pos` late in the code (after I `continue`)?

**Comment by ntrel** [comment]
> what would happen in I try to use pos later in the code (after I continue)?

Compile error. pos is only declared within the `and` branch. If you don't like this scoping, that's why I asked for the `if` form, which is clearer.

**Comment by medvednikov** [comment]
`if x := opt() {` is going to stay.
