### ISSUE TITLE
Test failure message calls function again

### ISSUE THREAD

**Issue by mcastorina** [vlang/v#11501]
**V version:** V 0.2.4 41fc4c5
**OS:** linux

**What did you do?**
```v
fn fails() []int {
	dump('fails() called')
	return [1]
}

fn test_fails() {
	assert fails().len == 0
}
```

```
v test fails_test.v
```

**What did you expect to see?**
`fails() called` prints only once

**What did you see instead?**
`fails() called` prints twice

**Comment by spytheman** [comment]
Fixed in 0a18690
