### ISSUE TITLE
How to catch any page?

### ISSUE THREAD

**Issue by westtrade** [vlang/v#11514]
https://github.com/vlang/v/blob/c175b4fd486ce8466105ee38b067884be1e46356/vlib/vweb/vweb.v#L507

Hi! I need help - please can you explain how to catch any route, or not_found page?

**Comment by JalonSolov** [comment]
@mcastorina ^^

**Comment by mcastorina** [comment]
You can declare a route using an ellipsis like so

```v
['/:path...']
pub fn (mut app App) catch_all(path string) vweb.Result {
```

or define the `not_found()` method on `App`, overwriting the default one:

```v
pub fn (mut app App) not_found() vweb.Result {
```
The downside of the second approach is you don't get access to the path that was not found.

**Comment by westtrade** [comment]
> You can declare a route using an ellipsis like so
> 
> ```v
> ['/:path...']
> pub fn (mut app App) catch_all(path string) vweb.Result {
> ```
> 
> or define the `not_found()` method on `App`, overwriting the default one:
> 
> ```v
> pub fn (mut app App) not_found() vweb.Result {
> ```
> 
> The downside of the second approach is you don't get access to the path that was not found.

Thank you for explanation!
