### ISSUE TITLE
`a`.is_letter() doesn't work

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#11535]
**V version:** 
latest

**OS:** 
win10

**What did you do?**
```V
`a`.is_letter()
```

**What did you expect to see?**
true
 
**What did you see instead?**
error: unknown method or field: `rune.is_letter`.

**Comment by ChAoSUnItY** [comment]
I guess you'll have to cast `` `a` `` to `byte`? since `is_letter()` is byte's method.

**Comment by JalonSolov** [comment]
Well, what's between the \`\` may not be a single byte.  Since it's a `rune`, it could be up to 4 bytes in size.  It's a lot harder to test whether or not a `rune` is a `letter`, which likely explains why there's no `.is_letter()` method for them.  At least, not yet.

**Comment by medvednikov** [comment]
we should add is_letter to runes
