### ISSUE TITLE
Parameters in 'match' options separated by comma not flagged by compiler

### ISSUE THREAD

**Issue by DevrosTheOne** [vlang/v#11548]
**V version:** 
V full version: V 0.2.4 219a764
**OS:** 
OS: macos, macOS, 11.6, 20G165
Processor: 8 cpus, 64bit, little endian, Apple M1
CC version: Apple clang version 12.0.5 (clang-1205.0.22.11)
**What did you do?**
```v
struct Cat {}

struct Dog {}

type Pet = Cat | Dog

fn (p Pet) pet_type() {
	match p {
		Cat, Dog { println(typeof(p).name) }
		// Dog { println(typeof(p).name) }
	}
}

c := Pet(Cat{})
d := Pet(Dog{})

c.pet_type()
d.pet_type()
```

**What did you expect to see?**
Compiler error on the ```Cat, Dog { println(typeof(p).name) }``` statement,  parameters not of ```enum``` as in documentation example.
 
**What did you see instead?**
Compiled and executed with output
```
Dog)
Dog)
```

**Comment by spytheman** [comment]
Match can be used to match over sumtype variants too, see <https://github.com/vlang/v/blob/master/doc/docs.md#sum-types>

**Comment by DevrosTheOne** [comment]
> Match can be used to match over sumtype variants too, see https://github.com/vlang/v/blob/master/doc/docs.md#sum-types

This should have at least thrown a compilation error instead of a compiled prog with corrupt result ```Dog)```.  

You will get a 'Should not never happen' error if you use the result type from match to call a method.

Snippet example
```v
...
fn (c Cat) hi() {
	println('Hi from Cat')
}
fn (d Dog) hi() {
	println('Hi from Dog')
}

type Pet = Cat | Dog

fn (p Pet) pet_type() {
	match p {
		Cat, Dog { p.hi() }
...
```
```
/tmp/v/sumt.17673905382000386202.tmp.c:10382:16: error: passing 'main__Dog' (aka 'struct main__Dog') to parameter of incompatible type 'main__Cat' (aka 'struct main__Cat')
                main__Cat_hi((*p._main__Dog));
                             ^~~~~~~~~~~~~~~
/tmp/v/sumt.17673905382000386202.tmp.c:10368:45: note: passing argument to parameter 'c' here
VV_LOCAL_SYMBOL void main__Cat_hi(main__Cat c) {
                                            ^
1 error generated.
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.
```
