### ISSUE TITLE
Type inference bug: val2 not inferred as interface type in situations like [MyInterfaceType(val), val2]

### ISSUE THREAD

**Issue by elimisteve** [vlang/v#11542]
```
$ v doctor
OS: linux, Debian GNU/Linux 9.13 (stretch) (VM)
Processor: 2 cpus, 64bit, little endian, Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
CC version: cc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

getwd: /home/user
vmodules: /home/user/.vmodules
vroot: /home/user/django_projects/v
vexe: /home/user/django_projects/v/v
vexe mtime: 2021-09-18 21:34:31
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 e76be4b

Git version: git version 2.11.0
Git vroot status: 0.2.4-154-ge76be4ba
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 333c14de
```

**What did you do?**

```
$ cat iface2-err.v
struct Dog {
	breed string
}

struct Cat {
	breed string
}

fn (d Dog) speak() string {
	return 'woof'
}

fn (c Cat) speak() string {
	return 'meow'
}

interface Speaker {
	breed string
	speak() string
}

dog := Dog{'Leonberger'}
cat := Cat{'Siamese'}

for item in [Speaker(dog), cat] {  // <-- Key line; requires `Speaker(cat)`, but shouldn't
	println(item.speak())
}

$ v run iface2-err.v
```

**What did you expect to see?**

```
$ v run iface2-err.v
woof
meow
```

 
**What did you see instead?**

```
$ v run iface2-err.v
iface2-err.v:25:28: error: invalid array element: expected `Speaker`, not `Cat`
   23 | cat := Cat{'Siamese'}
   24 | 
   25 | for item in [Speaker(dog), cat] {
      |                            ~~~
   26 |     println(item.speak())
   27 | }
```

It makes me do `[Speaker(dog), Speaker(cat)]` but I should only need to do `[Speaker(dog), cat]`, it seems to me.

**Comment by KINGZ1993** [comment]
Inside [. . . . . ] Should be an array of the same type. The interface belongs to the defined type. Your structure and interface cannot be placed in it at the same time. . . . .vlang is correct

**Comment by elimisteve** [comment]
@KINGZ1993 Nope; `cat` does in fact implement the `Speaker` interface. The sort of type inference needed here is nothing more than is utilized when we do

    [byte(1), 2, 3, 4]

or

    type MyString = string
    [MyString("one"), "two", "three"]

That is, just like we don't have to do

    [byte(1), byte(2), byte(3), byte(4)]

nor

    [MyString("one"), MyString("two"), MyString("three")]

we shouldn't have to do

    [Speaker(dog), Speaker(cat)]

Simply typing

    [Speaker(dog), cat]

should suffice, as it does elsewhere.
