### ISSUE TITLE
v: command not found

### ISSUE THREAD

**Issue by procrastinar** [vlang/v#11571]
I'm trying to execute the V command to run an application, but it returns ``v: command not found``.
I only followed the steps at the installation guide. I'm at Debian.

**Comment by JalonSolov** [comment]
Did you run `sudo v symlink` after `make`.

**Comment by JalonSolov** [comment]
You don't have `sudo` permission on the system?

Then the only thing you can do is add the V directory to your PATH environment variable.

**Comment by procrastinar** [comment]
> You don't have `sudo` permission on the system?
> 
> Then the only thing you can do is add the V directory to your PATH environment variable.

Yes, I have. But it says `v: command not found` when I use `sudo v symlink`.

**Comment by nyx-litenite** [comment]
@procrastinar  did you run `make`? if so, are you trying `sudo v symlink` in the directory that you installed v in?

**Comment by procrastinar** [comment]
> @procrastinar did you run `make`? if so, are you trying `sudo v symlink` in the directory that you installed v in?

Yes. I run `make` again and tried `sudo v symlink` at V directory, but won't work.

**Comment by vincenzopalazzo** [comment]
@procrastinar what is your os? can you give more details about your config to try to reproduce your problem?

Another alternative is to use the following command `sudo ln -s /path/to/v/binary`

**Comment by procrastinar** [comment]
> @procrastinar what is your os? can you give more details about your config to try to reproduce your problem?
> 
> Another alternative is to use the following command `sudo ln -s /path/to/v/binary`

My OS is LMDE 4 Debbie. `sudo ln -s /path/to/v/binary` won't worked.

**Comment by procrastinar** [comment]
I can use the V command if I run `export PATH=$PATH:/path/to/v/binary`, but when I close the terminal, doesn't work anymore.

**Comment by JalonSolov** [comment]
Try `sudo ./v symlink` while CD'd into the V directory.

If that doesn't work, add the `export PATH=$PATH:/path/to/v/binary` line into your .profile or .bashrc or whatever file you have that sets up things when you log in.

**Comment by procrastinar** [comment]
> Try `sudo ./v symlink` while CD'd into the V directory.
> 
> If that doesn't work, add the `export PATH=$PATH:/path/to/v/binary` line into your .profile or .bashrc or whatever file you have that sets up things when you log in.

`sudo ./v symlink` worked! Thank you so much!
