### ISSUE TITLE
Added unnecessary casting methods

### ISSUE THREAD

**Issue by 0x9ef** [vlang/v#1162]
**V version:** 0.1.14
**OS:** win10x64

**What did you do?**
```
const (
    SuperVar = u64(0)
    SuperVarTwo = u64(3)
)
```

**What did you expect to see?**
Nothing. test.exe
 
**What did you see instead?**
```
C:\Users\─рэ //.vlang//test.c:2:7: error: expected declaration specifiers or '...' before '(' token
(u64)(u64
```

**Comment by joe-conigliaro** [comment]
This is broken for consts, which is a problem because large numbers (u64) get truncated.

**Comment by joe-conigliaro** [comment]
This still isn't fixed but I created a PR to detect if a number wont fit in a u32 and makes it a u64 by default, so we can have larger numbers in consts: https://github.com/vlang/v/pull/1222
