### ISSUE TITLE
Cannot build unknown platform `freebsd`

### ISSUE THREAD

**Issue by 0x9ef** [vlang/v#1165]
**V version:** 0.1.14
**OS:** win10x64

**What did you do?**
`v -o v2.exe compiler`

**What did you expect to see?**
v2.exe
 

**What did you see instead?**
```
Supported platforms:
["windows", "mac", "linux"]
panic: os.v:458
unknown platform `freebsd`
```

**Comment by medvednikov** [comment]
```
git pull
make

```
