### ISSUE TITLE
V 0.1.15 with *BSD support, hot code reloading, fixed VROOT, defer statement, and more!

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#1169]
## V 0.1.15 
*15 Jul 2019* 
- FreeBSD, OpenBSD, NetBSD, DragonFly support. 
- Hot code reloading now works with graphical applications:  [bounce.v](https://github.com/vlang/v/blob/master/examples/hot_code_reloading/bounce.v) 
- VROOT was removed, the installation process is now much simpler. 
- `defer` statement.
- map.v was re-written. It's now much faster.
- `for key, val in map` syntax. 
- `flag` module for parsing command line arguments. 
- `zip` module. 
- `crypto/sha1` module. 
- Submodules and module aliases (`import encoding.base64 as b64`).

**Comment by changrui** [comment]
Panic：  os_win.v:5， redefination of `os.PathSeparator`, please fix it.

**Comment by medvednikov** [comment]
@changrui make sure you run `git pull` and `make`

**Comment by lhmwzy** [comment]
git pull;make 

rm -f v.c v vprod
curl -Os https://raw.githubusercontent.com/vlang/vc/master/v.c
cc -std=gnu11 -w -o v v.c -lm
./v -o v compiler
*** Signal 11

Stop.
make: stopped in /home/lhm/v

uname -a:
DragonFly gxdb 5.6-RELEASE DragonFly v5.6.0.1.g3d5034-RELEASE #0: Tue Jun 18 09:09:55 CST 2019

**Comment by medvednikov** [comment]
I tested on FreeBSD and OpenBSD only. I assumed it would just work.

I'll install DragonFly and test it there.

**Comment by lhmwzy** [comment]
the core file is here:
https://github.com/lhmwzy/v_error

**Comment by kingofoz** [comment]
Hi @medvednikov Did you fix #1004?

**Comment by medvednikov** [comment]
@lhmwzy can you try again please?

**Comment by ernierasta** [comment]
Hi Alex, 
thank You for implementing sane (POSIG/GNU) `flags` in golang I always have to use non STL `pflag` library.

**Comment by Chiiruno** [comment]
Great work!
Do you plan on adding this release to the releases page on this repo?

**Comment by medvednikov** [comment]
@Chiiruno done

There are no pre-built binaries right now, they have to built from source. But it's very easy to do (git clone + make).

**Comment by JohnAZoidberg** [comment]
Could you please add the notes to the releases in the future?

**Comment by elimisteve** [comment]
@JohnAZoidberg Great idea; seconded :+1:

**Comment by lhmwzy** [comment]
> 
> 
> @lhmwzy can you try again please?

OK now.thks

**Comment by medvednikov** [comment]
> Then the release notes would appear at https://github.com/vlang/v/releases/tag/0.1.15

Ok, will do @elimisteve @JohnAZoidberg
