### ISSUE TITLE
Integer division by 0 always return one???

### ISSUE THREAD

**Issue by MaxGraey** [vlang/v#117]
```go
fn main() {
	println(100 / 0)
}
```
#### Actual output: 
1

#### Expected: 
division by zero exception

**Comment by medvednikov** [comment]
Division by zero leads to undefined behavior in C.

I'm not sure what's the best way to catch it at runtime without causing performance loss.

For now I've added a compilation time check for dividing by zero. Will only work with literals of course.

```
test.v:2
division by zero 
```

**Comment by ntrel** [comment]
> I'm not sure what's the best way to catch it at runtime

I think division/modulus should first assert that the denominator is not zero. Then when compiling a program for release, asserts can be disabled if necessary.
