### ISSUE TITLE
vlib not found in REPL on v0.1.15

### ISSUE THREAD

**Issue by comjun04** [vlang/v#1171]
**V version:** v0.1.15
**OS:** Windows 10 (Version 1803; OS Build 17134.885) x64

**What did you do?**
`v`
`println('aaa')`

**What did you expect to see?**
aaa
VROOT=C:\Users\User\Documents\v
 
**What did you see instead?**
VROOT=C:\Users\User\Documents\v
vlib not found. It should be next to V executable.

In REPL, I see this error.
My `v.exe` is next to `vlib`.

Note: The upper result works fine on Linux. (WSL/Ubuntu)

**Comment by medvednikov** [comment]
Sorry for the delay, this was fixed a couple of days ago.
