### ISSUE TITLE
Can HTTP libraries be like python's requests libraries?

### ISSUE THREAD

**Issue by tealin** [vlang/v#1172]
Python's HTTP library requests are very useful, and hopefully the library of V language is just as useful.

**Comment by tealin** [comment]
http://2.python-requests.org/zh_CN/latest/user/quickstart.html

**Comment by iredmail** [comment]
@tealin Most people here don't know Chinese language, so you'd better post English document instead:
http://python-requests.org

**Comment by medvednikov** [comment]
It looks nice.

V HTTP library is similar to Go and to this library:


```
>>> r = requests.get('https://api.github.com/user', auth=('user', 'pass'))
>>> r.status_code
200
>>> r.headers['content-type']
'application/json; charset=utf8'
>>> r.encoding
'utf-8'
>>> r.text
u'{"type":"User"...'
>>> r.json()
{u'private_gists': 419, u'total_private_repos': 77, ...}
```
V:

```
r := http.get('https://api.github.com/user')
r.status_code
r.body
json.encode(r.body)
```

**Comment by medvednikov** [comment]
There are no default args/function overloading, so we could achieve easy authentication with something like

```
r := http.get_auth('https://api.github.com/user', 'user', 'pass')
```

`r.json()` is also easy to implement.

**Comment by tealin** [comment]
> @tealin这里的大多数人都不懂中文，所以你最好发布英文文件：[http](http://python-requests.org)：
> [//python-requests.org](http://python-requests.org)

ok

**Comment by tealin** [comment]
Great. Will session, Multipart-Encoded File support be added later?
`s = requests.Session()

r = s.get('https://httpbin.org/cookies', cookies={'from-my': 'browser'})
print(r.text)
# '{"cookies": {"from-my": "browser"}}'

r = s.get('https://httpbin.org/cookies')
print(r.text)
# '{"cookies": {}}'`

https://2.python-requests.org/en/master/user/advanced/#session-objects


Requests makes it simple to upload Multipart-encoded files:
`>>> url = 'https://httpbin.org/post'
>>> files = {'file': open('report.xls', 'rb')}

>>> r = requests.post(url, files=files)
>>> r.text
{
  ...
  "files": {
    "file": "<censored...binary...data>"
  },
  ...
}`

https://2.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests

**Comment by medvednikov** [comment]
> Great. Will session, Multipart-Encoded File support be added later?

Yes.

I've already renamed `response.body` to `response.text`.
