### ISSUE TITLE
Name clash: keyword vs. struct member in C library

### ISSUE THREAD

**Issue by Viza74** [vlang/v#1173]
**V version:** 0.1.15
**OS:** macos

**What did you do?**
Trying to use a the C library Raylib.
Raylib has a struct like this:
```
// Camera type, defines a camera position/orientation in 3d space
typedef struct Camera3D {
    Vector3 position;       // Camera position
    Vector3 target;         // Camera target it looks-at
    Vector3 up;             // Camera up vector (rotation over its axis)
    float fovy;             // Camera field-of-view apperture in Y (degrees) in perspective, used as near plane width in orthographic
    int type;               // Camera type, defines projection type: CAMERA_PERSPECTIVE or CAMERA_ORTHOGRAPHIC
} Camera3D;
```
 Whwich I define in my raylib.v as:
```
struct C.Camera3D {
	pub mut:
    position Vector3       // Camera position
    target Vector3         // Camera target it looks-at
    up Vector3             // Camera up vector (rotation over its axis)
    fovy f32             // Camera field-of-view apperture in Y (degrees) in perspective, used as near plane width in orthographic
    type int               // Camera type, defines projection type: CAMERA_PERSPECTIVE or CAMERA_ORTHOGRAPHIC
}
```

**What did you expect to see?**
Be able to use the C library
 
**What did you see instead?**
```
panic: raylib.v:169
expected `.name` but got `type`
```

Since "type" is a keyword in v the parser can't seem to understand it in the C struct

If I rename it in v:
```
struct C.Camera3D {
	pub mut:
    position Vector3       // Camera position
    target Vector3         // Camera target it looks-at
    up Vector3             // Camera up vector (rotation over its axis)
    fovy f32             // Camera field-of-view apperture in Y (degrees) in perspective, used as near plane width in orthographic
    ctype int               // Camera type, defines projection type: CAMERA_PERSPECTIVE or CAMERA_ORTHOGRAPHIC
}
```
then the c compiler can't find it any more:
```
.torus.c:3120:229: error: field designator 'ctype' does not refer to any field in type 'Camera3D' (aka 'struct Camera3D'); did you mean 'type'?
```

Is there a way to make this work without modifying the original C library?

**Comment by medvednikov** [comment]
Hi @Viza74 

It should work if you replace 

```
struct C.Camera3D {
	pub mut:
```

with 

```
struct Camera3D {
	pub mut:

```

The convention is to use `typ`. 

But I might be able to make the compiler accept `type` fields.

**Comment by medvednikov** [comment]
`C.Camera3D` only describes the struct. It tells the compiler it's defined somewhere else.

Let me know if it works.

**Comment by Viza74** [comment]
Hmm, if I just remove the "C." from before the Camera3D struct in raylib.v, it still panics with the same error: ```expected `.name` but got `type` ```

If I then rename the field ```type``` to ```typ``` in raylib.v, that error is gone, but now the compiler can't find the Camera3D struct itself:
```
panic: main.v:14
undefined: `Camera3D`
```
when I try to use it from main.v
```
    camera := Camera3D{ 
        position: Vector3{ x:5.0 y:5.0 z:5.0 }
        target: Vector3{ x:0.0 y:0.0 z:0.0 }
        up: Vector3{ x:0.0 y:1.0 z:0.0 }
        fovy: 45.0
        typ: 0 
    }
```

**Comment by medvednikov** [comment]
undefined: `Camera3D`

This should not happen if you have `struct Camera3D { ... }` in main.v

**Comment by Viza74** [comment]
That not in main.v, but in raylib.v, which is imported to main.v

```
module main

import raylib

fn main() {

    screen_width := 800
    screen_height := 600

    C.InitWindow(screen_width, screen_height, 'raylib from v')
    C.SetTargetFPS(60)


    camera := C.Camera3D{ 
        position: Vector3 { x:5.0 y:5.0 z:5.0 }
        target: Vector3 { x:0.0 y:0.0 z:0.0 }
        up: Vector3 { x:0.0 y:1.0 z:0.0 }
        fovy: 45.0
        typ: 0 
    }

    C.SetCameraMode(camera, raylib.CameraMode.CAMERA_ORBITAL)

}
```

and in raylib.v:
```
module raylib

#flag -I /Users/viza/VizaDocs/raylib/raylib-2.5.0-macOS/include
#flag -framework OpenAL
#flag -framework CoreVideo
#flag -framework IOKit
#flag -framework Cocoa
#flag -framework GLUT
#flag -framework OpenGL
#flag /Users/viza/VizaDocs/raylib/raylib-2.5.0-macOS/lib/libraylib.a
#include"/Users/viza/VizaDocs/raylib/raylib-2.5.0-macOS/include/raylib.h"


...

// // Camera type, defines a camera position/orientation in 3d space
// typedef struct Camera3D {
//     Vector3 position;       // Camera position
//     Vector3 target;         // Camera target it looks-at
//     Vector3 up;             // Camera up vector (rotation over its axis)
//     float fovy;             // Camera field-of-view apperture in Y (degrees) in perspective, used as near plane width in orthographic
//     int type;               // Camera type, defines projection type: CAMERA_PERSPECTIVE or CAMERA_ORTHOGRAPHIC
// } Camera3D;
struct Camera3D {
	pub mut:
    position Vector3       // Camera position
    target Vector3         // Camera target it looks-at
    up Vector3             // Camera up vector (rotation over its axis)
    fovy f32             // Camera field-of-view apperture in Y (degrees) in perspective, used as near plane width in orthographic
    typ int               // Camera type, defines projection type: CAMERA_PERSPECTIVE or CAMERA_ORTHOGRAPHIC
}

// // Camera2D type, defines a 2d camera
// typedef struct Camera2D {
//     Vector2 offset;         // Camera offset (displacement from target)
//     Vector2 target;         // Camera target (rotation and zoom origin)
//     float rotation;         // Camera rotation in degrees
//     float zoom;             // Camera zoom (scaling), should be 1.0f by default
// } Camera2D;
struct C.Camera2D {
	pub mut:
    offset C.Vector2
    target C.Vector2
    rotation f32
    zoom f32
}

...

```
Basically in raylib.v I copied everything from raylib.h, commented out everything, and if I use something from the raylib library from v and the compiler complains about something I "convert" the declaration to v. I don't say I know what I'm doing :) but so far this seemed to mostly work. :)

**Comment by medvednikov** [comment]
ok so you define it `raylib`, so this is how you should use it in main.v:

```
camera := raylib.Camera3D{...}
```


```
    C.SetCameraMode(camera, raylib.CameraMode.CAMERA_ORBITAL)
```

This should be replaced with 

```
    camera.set_mode(raylib.CameraMode.CAMERA_ORBITAL)
```

and the `set_mode` method should call `C.SetCameraMode`

**Comment by medvednikov** [comment]
I've just pushed a fix that allows `type int` fields. But I have a feeling I haven't covered all possible problems.

**Comment by ntrel** [comment]
> The convention is to use typ

In D they would write `type_`. This could even be a V feature - a single trailing underscore gets automatically dropped from an identifier. This would also be useful for `extern` symbols in V when linking to symbols from other languages that use a V keyword as an identifier.

> I've just pushed a fix that allows struct Foo { type int }

I think these kinds of workarounds aren't really practical in all the places an identifer might be a keyword.

**Comment by Viza74** [comment]
A couple of different things:

**1.**

> ok you define it inraylib, so this is how you should use it in main.v

Duh, ok, I forgot that... but there is a reason: I use other things from raylib.v without the "raylib." prefix. For example I use the ```C.Camera2D``` struct from my previous comment in main.v like this without problem:
```
	mut cam := Camera2D {
		offset: Vector2 {
			x:0
			y:0
		}
		target: Vector2 {
			x:0
			y:0
		}
		rotation:0
		zoom: 1
	}
```
The Vector2 structs are also from raylib.v:
```
struct C.Vector2 {
pub mut:
	x f32
	y f32
}
```
I actually like that this is working this way, but probably these are also a bug, and they should be used like raylib.Camera2D and raylib.Vector2?...

**2.**
I tried your fix - it is a step forward, but still not working yet: now it seems to panic on the colon after the word "type"
```
next token = `.integer`
panic: main.v:19
expected `.name` but got `:`
```
BUT it is possible to change the field afterwards like ``` camera.type = 1``` so the problem could be somewhere in the struct initialization format?...

**3.**

>   C.SetCameraMode(camera, raylib.CameraMode.CAMERA_ORBITAL)
This should be replaced with
    camera.set_mode(.orbital)
and the set_mode method should call C.SetCameraMode

I guess that would be the perfect v-like solution, but that would mean I have to rewrite all X hundred functions from raylib, which I don't want to do. :)
I would actually prefer if I don't have to do any "glue" code to use a C library, just use everything as directly as possible. (I don't mind the "C." prefix, that would be prefixed something (longer) anyway...)
The program looks (and compiles and runs) like this now:
```
module main

import raylib

fn main() {

    screen_width := 800
	screen_height := 600

    C.InitWindow(screen_width, screen_height, 'raylib from v')
	C.SetTargetFPS(60)


    mut camera := Camera3D { 
        position: Vector3 { x:5.0 y:5.0 z:5.0 }
        target: Vector3 { x:0.0 y:0.0 z:0.0 }
        up: Vector3 { x:0.0 y:1.0 z:0.0 }
        fovy: 45.0
        // type: 0 
    }
    camera.type = 0

    C.SetCameraMode(camera, raylib.CameraMode.CAMERA_ORBITAL)

    for !C.WindowShouldClose()// Detect window close button or ESC key
	{
        C.UpdateCamera(&camera)

        C.BeginDrawing()
        C.ClearBackground(Color{255,255,255,255})
        C.BeginMode3D(camera)

            C.DrawGrid(10, 1.0)

        C.EndMode3D()
        C.EndDrawing()
    }
}
```

**Comment by medvednikov** [comment]
You can use C.Camera2D because it's an imported C struct.

I'll fix the type initialization bug.

The entire C to V wrapper thing will be much easier later this month once the C to V translator is out.

Then there will be no need in the funky `struct C.foo {` and `import const` etc.

**Comment by medvednikov** [comment]
@Viza74 you can now escape keywords:

```
struct Test {
  @type string
}

test.@type = 'test'
```

**Comment by Viza74** [comment]
Thank you!

I don't know if it is intended or bug, but the ```test.type = 'test'``` format is still accepted by the compiler

**Comment by medvednikov** [comment]
@Viza74 fixed, thanks :)
