### ISSUE TITLE
http_win.v variable names contain uppercase letters `BUF_MAX`

### ISSUE THREAD

**Issue by shawnye** [vlang/v#1178]
**V version:** 
0.1.15
**OS:** 
windows 10.0.17134.765

**What did you do?**
D:\v\examples>v links_scraper.v

**What did you expect to see?**
Compiled OK
 
**What did you see instead?**
<pre>
VROOT=D:\v
panic: http_win.v:124
variable names cannot contain uppercase letters, use snake_case instead
</pre>

I replaced all `BUF_MAX`  to `buf_max`,  then the compile passed.

**Comment by medvednikov** [comment]
Fixed.
