### ISSUE TITLE
Moving cache files to ~/.cache/vlang

### ISSUE THREAD

**Issue by ntilotta** [vlang/v#1183]
I suggest to avoid creating files under ~/.vlang or inside working directory, in this way the compiler makes the directories really dirty of hidden files, so it's better moving all compilation/re-compilation under ~/.cache/vlang

**Comment by medvednikov** [comment]
Nothing is created in ~/.vlang anymore.

**Comment by ntilotta** [comment]
> Nothing is created in ~/.vlang anymore.

Indeed, I wrote "or inside working directory" it's better moving everything under ~/.cache/vlang to me.

**Comment by medvednikov** [comment]
ah sorry missed that.

These files get removed instantly. Using a temp directory complicates things when making packages for Linux and on Windows with its C:/Users/user mess.

**Comment by ntilotta** [comment]
The directories .vrepl and .vrepl_temp should not being created inside working directory, in this way we can launch the repl everywhere without creating those files around, so if possible move those in that location or delete them after exit the repl.
