### ISSUE TITLE
Please compare V with Kotlin

### ISSUE THREAD

**Issue by epabst** [vlang/v#1187]
Here is my understanding of Kotlin using your criteria:

- Fast compilation - Kotlin compiles in about the same time as Java.

- Simplicity & maintainability - Yes. https://kotlinlang.org/docs/reference/faq.html#is-kotlin-hard 

- Great performance on par with C and zero cost C interop - Yes. https://discuss.kotlinlang.org/t/kotlin-performance-by-comparison/9837

- Safety (immutability, no null, option types, free from data races) - Yes.  https://kotlinlang.org/docs/reference/null-safety.html , data classes, etc.

- Easy concurrency - https://kotlinlang.org/docs/reference/coroutines/coroutines-guide.html

- Easy cross compilation - https://kotlinlang.org/docs/reference/multiplatform.html

- Compile time code generation - Yes.

- Small compiler with zero dependencies -  I don't know its size.  gradlew requires zero installation.

- No global state - Global state is frozen by default. 
 https://kotlinlang.org/docs/reference/native/immutability.html

- Hot code reloading - Yes, depending on the platform.

**Comment by epabst** [comment]
Kotlin is ramping up VERY quickly.  It would be great to have you join efforts with them if it is viable for you.

**Comment by null-dev** [comment]
I'm a huge Kotlin fan but unfortunately Kotlin Native is not currently very fast :(. The benchmark you linked refers to the JVM version of Kotlin which isn't really relevant.

Gradle also requires a fair bit of experience to configure and debug properly. It's not very fast either for simple programs (but scales much better for complicated applications).

**Comment by vertical222** [comment]
That about it and benchmark comparison can be found easily on the web where V is on par to C level in term or performance and memory usage except multithreading.

**Comment by vertical222** [comment]
That’s about it and benchmark comparison can be found easily on the web where V is on par to C level in term of performance and memory usage except multithreading.

It’s an odd to compare Kotlin when V is closer to Go like you have compare Java and Scala to Kotlin.

**Comment by di3663** [comment]
I think there are ten years more before v used in real projects, but you can use Kotlin right now. But Kotlin native is nothing as I know and tested.

**Comment by medvednikov** [comment]
V 1.0 release is planned for this year, I really doubt it will take ten years before it's used in "real" projects :)
