### ISSUE TITLE
Hot code reloading example does not work on osx

### ISSUE THREAD

**Issue by dm1try** [vlang/v#1189]
**V version:** V 0.1.15
**OS:** osx Catalina 10.15 Beta (19A501i)

**What did you do?**
`git pull origin master`
`make clean`
`make`

I launched the example with hot code reloading
`./v -live examples/hot_code_reloading/message.v`

**What did you expect to see?**
It should work
 
**What did you see instead?**
It does not work
```
pass=1 fn=``
panic: message.v:9
type names cannot contain `_`
```

the minimum reproducible example:
```
import os
import time

[live]
fn live(){ }
```
`./v -live live.v`
```
check()
next token = `)`
pass=1 fn=``
panic: live.v:5
expected `{` but got `(`
```

It looks like it's related to the parser phase, but I'm not sure that I should check first.
@medvednikov confirmed that the example works on `osx` on his side.

**Comment by dcurrie** [comment]
Is there any description of how to use hot code reloading?

On macOS I get (note: I have the v directory on my PATH so the last example runs):

> v e% ./v -live examples/hot_code_reloading/message.v
> v e% ./v -live examples/hot_code_reloading/bounce.v
> v e% cd examples/hot_code_reloading 
> hot_code_reloading e% v -live bounce.v
> hot_code_reloading e% 

I.e., nothing happens. Yesterday I did see a bouncing square in a window when I ran this, but I had no idea with to do with it. Now, after today's updates, I see nothing.

**Comment by medvednikov** [comment]
It should all work. I have no idea where this comes from: 
```
panic: message.v:9
type names cannot contain `_`
```

Try removing the repository and cloning it again.

> I.e., nothing happens. Yesterday I did see a bouncing square in a window when I ran this, but I had no idea with to do with it. Now, after today's updates, I see nothing.

You modify bounce.v in your editor while the program is running, and the color of the square will change.

**Comment by dm1try** [comment]
> Try removing the repository and cloning it again.

No luck. Thanks, I'll try to debug.

**Comment by webdesq** [comment]
Works fine for me in MacOS 10.14:

./v -live examples/hot_code_reloading/bounce.v
./bounce

Then, if I edit the RGB values in bounce.v and press save, the new color appears in running application in less than a second.

**Comment by dcurrie** [comment]
Thanks, @webdesq -- I did not type `./bounce` expecting `v -live ...` line to automatically run the code. It works for me now on macOS 10.14.5 when I use both commands. It's good to finally have a complete, if minimal, set of instructions on how to use this!

**Comment by dm1try** [comment]
after I found this line https://github.com/vlang/v/blob/251e32948e9e7197b29e82ef37d62331910854e3/compiler/main.v#L384

I checked for `v` in `PATH` and found that I have old version `0.1.0`(`/usr/local/bin/v`) there :(

so removing it and adding `v` source directory to `PATH` fixes the problem.

```
 ./v -live  examples/hot_code_reloading/message.v
sh: v: command not found
```
```
export PATH=/Users/dmitrydedov/projects/v:$PATH
./v -live  examples/hot_code_reloading/message.v
```
```
./examples/hot_code_reloading/message
Hello! Modify this message while the program is running.
Hello Hello! Modify this message while the program is running.
```

**Comment by medvednikov** [comment]
Having an old V in PATH is bad, but should not break this feature.

I'll update it and use `os.args[0]`.
