### ISSUE TITLE
Array append can overwrite sliced (immutable?) data

### ISSUE THREAD

**Issue by ntrel** [vlang/v#119]
Below I'm using `mut` just so I can append, the array data could be immutable (see #41):
```rust
fn main() {
	mut arr := [1, 2]
	mut slice = arr
	slice << 3
	println(slice[2]) // 3
	arr << 4
	println(slice[2]) // 4
}
```
Appending to `arr` overwrites `slice[2]`. If the array data is immutable (with just the array reference mutable), then immutable data can be overwritten.

D prevents this by (IIUC) tracking if the end of a parent array has been sliced (and storing this metadata as part of the array memory allocation*, not the array reference). When this slice happens, appending to either `arr` or `slice` forces a re-allocation (this can be overridden with [`assumeSafeAppend`](https://dlang.org/phobos/object.html#.assumeSafeAppend) if the array element type is not immutable).

I expect this can also happen with `arr.substr`, but I can't test that ATM as it's 'disabled for security reasons'.

\*D also stores the allocation size in the allocated memory (before the array data), so an array reference is only the size of two pointers and can fit in a register for efficient passing as a function argument.

**Comment by medvednikov** [comment]
Good find, thanks.

**Comment by medvednikov** [comment]
V arrays should behave like in Go:

https://play.golang.org/p/rsSnZD61ZQo

**Comment by ntrel** [comment]
@medvednikov 
Go slices have the same problem, slices share the same capacity, overwriting another slice when appending. This can't be allowed in V when the slice element type is immutable:
https://play.golang.org/p/v7FWP30hX1A

Immutable element types are very useful e.g. for strings - appending to `mut([])T` is OK so long as the capacity has not already been used by another slice.

**Comment by medvednikov** [comment]
Indeed, thanks.

**Comment by yuyi98** [comment]
```v
fn main() {
	mut arr := [1, 2]
	mut slice := arr
	slice << 3
	println(slice[2]) // 3
	arr << 4
	println(slice[2]) // 4
}

D:\test\v\tt1>v run .
3
4

D:\test\v\tt1>v -autofree run .
3
3
```

Using `-autofree` can work.

**Comment by ka-weihe** [comment]
This has been fixed, since you are now required to add `.clone()`
