### ISSUE TITLE
The State of V

### ISSUE THREAD

**Issue by mishushakov** [vlang/v#1192]
Hey,
enjoying the Project. Nice work, very oriented, the syntax is clean.

But i have some questions though and i'm sure some people would find them interesting as well.

- Is it "safe" to use V? Should i start learning it?
- Where can i find community resources, is there an awesome list for V?
- As i see you're planning a centralised package management system. Isn't it better to just use Git?
- Which architectures (targets) are supported and can it run on micro controllers?
- Is there a linter or some sort a language guide, or any strict rules on how you actually write your code in V? I see, that examples use 4 Tabs for indentation
- How can i contribute and be involved? Any contribution guide for newcomers?

I think that's pretty much it.

Very excited where it all will go, i'm watching the project ever since you promised to make it happen 😁

Thank you for taking your time.

**Comment by mishushakov** [comment]
+ Do you Plan pre-compiled library and install-script/docker? I'd like to get it running on CI at some point.

**Comment by mishushakov** [comment]
- WebAssembly support?

**Comment by mishushakov** [comment]
- Dynamic Imports? Currently looks like the compiler bundles the whole standard library into my executable

**Comment by mishushakov** [comment]
- Formatter Available? Like `go fmt`

**Comment by elimisteve** [comment]
> * Formatter Available? Like `go fmt`

Yup! As per https://vlang.io/ --

> Even if something does change, vfmt will take care of the automatically.

**Comment by elimisteve** [comment]
> * Where can i find community resources

See https://vlang.io/ for many links to community resources (Discord, etc).

> is there an awesome list for V?

Yes: https://github.com/vlang/awesome-v

**Comment by medvednikov** [comment]
> vfmt will take care of the automatically
oops, typo fixed.

> Dynamic Imports? Currently looks like the compiler bundles the whole standard library into my executable
That's a feature :) Not the whole stdlib by the way, but only `builtin`, which is tiny.

There's a way to link libs dynamically with `#flag -lglfw`, have a look at glfw.v, pg.v, gl.v etc.

> WebAssembly support?

Yes via V => C => WA. Not directly at the moment.

> Do you Plan pre-compiled library and install-script/docker? I'd like to get it running on CI at some point.

I don't have much experience with docker. One of the cool features of V is that it's so tiny and only depends on a C compiler, nothing else. It's super easy to build.

> Which architectures (targets) are supported and can it run on micro controllers?
All of them. Well, if it's supported by C, it's supported by V.

> Is there a linter or some sort a language guide, or any strict rules on how you actually write your code in V? I see, that examples use 4 Tabs for indentation

You don't need to worry about that. `vfmt` takes care of everything.

**Comment by mishushakov** [comment]
Alright, thanks! For now V feels more like TypeScript to JS (like a transpiler rather than standalone language)...

**Comment by medvednikov** [comment]
V produces static binaries that can be run on any platform. The way it's achieved (C, LLVM, machine code generation) is irrelevant to the end user. So it definitely is a standalone language.
