### ISSUE TITLE
rework -c_options

### ISSUE THREAD

**Issue by whoizit** [vlang/v#1193]
1. we should rename `-c_options` to `-cflags`

2. now it works like this (example):
`v -c_options=-fno-caller-saves -c_options=-fno-cse-follow-jumps -c_options=-fno-hoist-adjacent-loads -c_options=-fno-inline-small-functions -c_options=-fno-optimize-sibling-calls -c_options=-fno-peephole2 -fno-reorder-functions -c_options=-fno-rerun-cse-after-loop -c_options=-fno-tree-vrp -c_options=-fno-reorder-blocks -c_options=-fno-tree-vect-loop-version -c_options=-Os v.v`
we should do it like this:
`v -cflags '-fno-caller-saves -fno-cse-follow-jumps -fno-hoist-adjacent-loads -fno-inline-small-functions -fno-optimize-sibling-calls -fno-peephole2 -fno-reorder-functions -fno-rerun-cse-after-loop -fno-tree-vrp -fno-reorder-blocks -fno-tree-vect-loop-version -Os' v.v`

**Comment by spytheman** [comment]
Will do it, if not tomorrow, then the day after tomorrow.
