### ISSUE TITLE
html module can't handle <pre> tag correctly

### ISSUE THREAD

**Issue by ghost** [vlang/v#11942]
**V version:** 
**OS:** 

**What did you do?**
```v
import net.html

fn main(){
	htm := '<html>
	<head></head>
	<body>
 <pre>
Text in a pre element
is displayed in a fixed-width
font, and it preserves
both      spaces and
line breaks
</pre> 	
	</body>
</html>'
	mut dom := html.parse(htm)
	println(dom.get_tag('pre'))
}
```

**What did you expect to see?**
<pre>
`[&lt;pre&gt;
Text in a pre element
is displayed in a fixed-width
font, and it preserves
both      spaces and
line breaks
&lt;/pre&gt;]`
</pre>
 
**What did you see instead?**
`[<pre>Text in a pre elementis displayed in a fixed-widthfont, and it preservesboth      spaces andline breaks</pre>]`

**Comment by Jictyvoo** [comment]
Hello,this problem must be related with how the parser handles each line for multiple function runs as a single HTML file

I will try to work on this issue this month or in the next. Sorry for the delay also.

**Comment by Dialga** [comment]
Fixed by https://github.com/vlang/v/pull/17206 on 3rd Feb 2023.
