### ISSUE TITLE
smartcast should only work for `if mut a is Foo`

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#11954]
**V version:** 
latest

**OS:** 
win10

**What did you do?**
```V
struct Foo { }
struct Bar { }

type Baz = Foo | Bar

fn main() {
	a := Baz(Foo{})
	if a is Foo {
		println(a)
	}
}
```

**What did you expect to see?**
`Baz(Foo{})`
 
**What did you see instead?**
`Foo{}`

**Analysis**
See docs https://github.com/vlang/v/blob/master/doc/docs.md#sum-types.

w has type Mars inside the body of the if statement. This is known as flow-sensitive typing. If w is a mutable identifier, it would be unsafe if the compiler smart casts it without a warning. That's why you have to declare a mut before the is expression.
```V
if mut w is Mars {
	assert typeof(w).name == 'Mars'
	if w.dust_storm() {
		println('bad weather!')
	}
}
```
Otherwise w would keep its original type.

**Comment by medvednikov** [comment]
This is working as expected.

`if a is Foo {` smartcasting is legal in V.

**Comment by SleepyRoy** [comment]
> This is working as expected.
> 
> `if a is Foo {` smartcasting is legal in V.

But `a` is not declared with `mut`, also the code is `if a is Foo` instead of `if mut a is foo`. Should smartcast still work in such case?

**Comment by medvednikov** [comment]
exactly, a is not mut, it gets smart cast to Foo

**Comment by medvednikov** [comment]
why wouldn't it work?

**Comment by SleepyRoy** [comment]
> why wouldn't it work?

Well, the docs say you must have `mut` to enable smartcast. https://github.com/vlang/v/blob/master/doc/docs.md#sum-types:

w has type Mars inside the body of the if statement. This is known as flow-sensitive typing. If w is a mutable identifier, it would be unsafe if the compiler smart casts it without a warning. That's why you have to declare a mut before the is expression.
```V
if mut w is Mars {
	assert typeof(w).name == 'Mars'
	if w.dust_storm() {
		println('bad weather!')
	}
}
```
Otherwise w would keep its original type.

**Comment by Gladear** [comment]
`mut` is only necessary when the smart casted variable is mutable, this behavior is correct.

**Comment by SleepyRoy** [comment]
@Gladear Thanks, that makes sense! Perhaps a summary of when to add `mut` would be helpful.
