### ISSUE TITLE
os.args modifies string arguments

### ISSUE THREAD

**Issue by jdonnerstag** [vlang/v#11966]
**V version:** V 0.2.4 95136cb
**OS:**  windows, Microsoft Windows 10 Enterprise v19041 64-bit

**What did you do?**
The command line `..\v\v.exe run . grep '"e"' v.mod` generates the following `os.args` array: `['C:\source_code\vlang\vlang-rosie\vlang-rosie.exe', 'grep', ''e'', 'v.mod']`.  

**What did you expect to see?**
`[..., '"e"', ...]`
 
**What did you see instead?**
`[..., ''e'', ...]`
As you can see V modifies the *inner* quotes of the string literal parameter. It rather should remove the outer quotes (single or  double) only, but not touch in any way or form, what is in between.

**Comment by JalonSolov** [comment]
This may not be V's doing - it may be your shell.  Are you running this in PowerShell or CMD?  The shell itself can manipulate the command line before your program ever sees it.  To illustrate, here's a _very_ simple test in the 2 shells:

PowerShell:
```
PS C:\> echo '"e"'
"e"
PS C:\>
```

CMD:
```
C:\>echo '"e"'
'"e"'

C:\>
```
Note that PowerShell stripped off the outer quotes, while CMD didn't.

**Comment by JalonSolov** [comment]
However, even though the shell _can_ manipulate the arguments, it is still true that V appears to be changing the quotes.  Here's a short program that illustrates this is indeed happening:
```v
import os

for arg in os.args {
        for c in arg {
                println(c.ascii_str())
        }
}
```
The result in a bash shell on Linux:
```
[jamie@5950x ~]$ v run foo.v '"e"'
e
[jamie@5950x ~]$
```
PowerShell on Windows:
```
PS C:\test> v run foo.v '"e"'
e
PS C:\test>
```
but the kicker is in CMD on Windows:
```
C:\test>v run foo.v '"e"'
'
e
'

C:\test>
```
So both bash and PowerShell are stripping all the quotes before V sees them, where CMD only strips the outer set... but then V changes them from double-quotes to single-quotes.

**Comment by JalonSolov** [comment]
Now that I've thought about it a bit... the only way for V to have consistent behavior across all shells on all platforms is if V itself strips leading/trailing quotes from options.  That would give the same behavior in bash on Linux, PowerShell on Windows, and cmd on Windows... and likely everything else.

**Comment by bakul** [comment]
You may want to check what a C program does. V should do no more. Note that on Unix at least you can pass a `'` or `""` by escaping it with `\` in a arg to a program called from a shell (or from a C program, using `execve()`).

**Comment by jdonnerstag** [comment]
I may work on a pull request, if someone provides me a starting point into V's source code

**Comment by JalonSolov** [comment]
For UNIXy systems, look at https://github.com/vlang/v/blob/7cf9c198fe6d6b38c1888862663d7936968d7fa2/vlib/os/os_nix.c.v#L259, for Windows, look at https://github.com/vlang/v/blob/7cf9c198fe6d6b38c1888862663d7936968d7fa2/vlib/os/os_windows.c.v#L97.  Both would need to be updated so the handling is consistent across the board.

**Comment by jdonnerstag** [comment]
I looked at V's code and didn't see anything suspicous. I even did some test_..() with the functions used, and nothing weird happened. I really had no clue what was happening and reverted to the idea that it must be how CMD, PS, bash etc treat the command line and found a number of enlightning blogs. 

http://www.windowsinspired.com/understanding-the-command-line-string-and-arguments-received-by-a-windows-program/
This first one is great in explaining how CMD works, and double quotes: "Double quote characters in a command line string have no relation to the boundaries between arguments and do not necessarily enclose arguments. Each individual double quote character by itself acts simply as a switch to enable or disable the recognition of space as a divider between arguments.". Which is why  `echo '"a"'` is the same as `echo 'a'` and the same as `echo "'a'"` in CMD.

PS handles single and double quote slightly different, and especially escaping is different.
https://www.yellowbrick.com/docs/5.2/bulk_loading/ybload_escape_quotes_windows.html
https://stackoverflow.com/questions/19862232/escaping-quotes-in-powershell-exe-via-command-prompt
https://stackoverflow.com/questions/6714165/powershell-stripping-double-quotes-from-command-line-arguments

I guess you can close this issue.
