### ISSUE TITLE
Improve BufferedReader read_line()

### ISSUE THREAD

**Issue by jdonnerstag** [vlang/v#11965]
I want to read a file line by line using a io.BufferedReader. The most obvious approach would be if `for line in br.read_line()` would work, but the compiler fails with an error. Conclusion: BufferedReader.read_line() does not implement rules for an iterator (e.g. next() function). 

If that doesn't work, may be what works for if-statements e.g. `if x := my_fn_returning_an_optional()` will do, but for-loops don't support this construct. 

So I wondered how BufferedReader.read_line() is meant to be used, as I can't belief that the approach I came up with below, is really the intended approach. The author for sure had something slicker in mind, and I'm just not able to figure that out. 

I think it might be worth while considering both ideas, and may be decoupled from my use case. 
- improve BufferedReader.read_line() to implement the interator interface. Probably not that difficult. 
- Consider extending for-loops to support `for x := my_fn_returning_an_optional()`.  It might be useful addition to the for-loop variants.

```
fd := os.open_file(file, "r")?
mut br := io.new_buffered_reader(reader: fd)
for {
    if line := br.read_line() {
        println(line)
    } else {
        break
    }
}
```

**Comment by Gladear** [comment]
I agree `for x := my_fn_returning_an_optional()` would be handy.

In the mean time, you can use this:
```v
for {
    line := file.read_line() or { break }
    // ...
}
```

**Comment by jdonnerstag** [comment]
Closed in favor of [a more generic feature request](https://github.com/vlang/v/issues/12029)
