### ISSUE TITLE
Wrong replacing of @ to $ in links in html vweb templates

### ISSUE THREAD

**Issue by Piruzzolo** [vlang/v#11978]
It looks like `@` is a valid character in urls/links. V template engine wrongly replaces it to `$` 
The problem in the code should be somewhere [here](https://github.com/vlang/v/blob/master/vlib/v/parser/tmpl.v).

Here is my bug report:

**V version:** V 0.2.4 d329e1d
**OS:** Win 10

**What did you do?**
Written `<script src="https://unpkg.com/htmx.org@1.5.0"></script>` in a html template. `@` got replaced with `$`

**What did you expect to see?**
```html
<html>
<!-- load htmx lib -->
<script src="https://unpkg.com/htmx.org@1.5.0"></script>
<script src="https://unpkg.com/hyperscript.org@0.8.1"></script>
etc...
```
 
**What did you see instead?**
```html
<html>
<!-- load htmx lib -->
<script src="https://unpkg.com/htmx.org$1.5.0"></script>
<script src="https://unpkg.com/hyperscript.org$0.8.1"></script>
etc...

```

**Comment by vincenzopalazzo** [comment]
HI @Piruzzolo,

Can you add also a small example to reproduce the problem?

Thanks.

**Comment by Piruzzolo** [comment]
> Can you add also a small example to reproduce the problem?

Sure:
```v
module main

import vweb

struct App {
	vweb.Context
}

fn main() {
	mut app := App {}
	vweb.run(app, 8081)
}

['/index']
pub fn (app &App) index() vweb.Result {
	return $vweb.html()
}
```

and in `index.v`:
```html
<html>
    <script src="https://unpkg.com/htmx.org@1.5.0"></script>
    <body>
    </body>
</html>
```

Here the files for convenience (zipped because GitHub doesn't support the file type):
[blog.zip](https://github.com/vlang/v/files/7235866/blog.zip)

**Comment by JalonSolov** [comment]
Use `@@` if you don't want it changed.

Otherwise, you _could_ be doing a template replacement, even in a URL.

**Comment by Piruzzolo** [comment]
@JalonSolov thanks, that's a neat workaroud

**Comment by Piruzzolo** [comment]
I think we shouldn't close it, the problem is still present in the code and a workaround can't be the the definitive solution @JalonSolov

**Comment by JalonSolov** [comment]
Why not?  It's not a workaround, it's the way to escape the @ to get a literal @ instead of a template replacement.

The same as you have to escape other characters in strings, etc.  For example, if you wanted to print a literal `${` in V, you would have to escape the `$` or V will think you're doing string interpolation.  Every language in existence requires escaping something...

**Comment by Piruzzolo** [comment]
Indeed but having to skip it is not what a user would expect I guess. At least I didn't expect it at all

**Comment by JalonSolov** [comment]
Then at the very least, it needs to be documented better.

**Comment by vladimir-light** [comment]
I think it would be nice to have a special template directive, which prevents parsing within `{...}`

Maybe something like

```
@raw {
  <div>@include 'header/base'</div>
}
```
In this case, parser wouldn't try to include './header/base.html' rather just output as is.


Many other template engines provide such functionality. e.G. Twig with `{% verbatim %}` (https://twig.symfony.com/doc/3.x/tags/verbatim.html)

**Comment by Jengro777** [comment]
vweb is no longer supported, this issue should be closed
