### ISSUE TITLE
Performance x10 slower than expected

### ISSUE THREAD

**Issue by GregHib** [vlang/v#11972]
V full version: V 0.2.4 4fbf3fd
OS: windows, Microsoft Windows 10 Home v19043 64-bit

**What did you do?**
Every time I try a new language I port a breadth first search algorithm to get familiar with the language and to also test it's performance.

https://gist.github.com/GregHib/aee695ce1fae41d3d5bb9f01af5f0002

I'm not very good with Rust so there's probably optimisations I'm missing, but I expect I'll be missing the same with V too.

**What did you expect to see?**

Results should be on average in the 200k-800k nanosecond range. For example Rust benchmarks it at around 370k ns and Java anywhere from 220k-440k depending on warmup.
 
**What did you see instead?**

V averages 3150k-4000k ns per flood fill which is x10 slower than expected (and seen in other theoretically slower languages)

**Comment by GZGavinZhao** [comment]
I'm not really familiar with this algorithm, but there is a small [bfs example](https://github.com/vlang/v/blob/master/examples/bfs.v) in the repo though. Perhaps take a look at that one?

**Comment by JalonSolov** [comment]
By default, V compiles with tcc, which doesn't do any optimizations.
If you add the `-prod` switch, it uses gcc or clang (whichever it finds), and turns on full optimizations.  It makes a difference...
```
[jamie@5950x ~]$ v run bfs.v
Took: 3078575119ns total 3078575ns per search
[jamie@5950x ~]$ v -prod run bfs.v
Took: 124029905ns total 124029ns per search
[jamie@5950x ~]$ 
```

**Comment by GregHib** [comment]
> 
> 
> By default, V compiles with tcc, which doesn't do any optimizations.
> If you add the `-prod` switch, it uses gcc or clang (whichever it finds), and turns on full optimizations. It makes a difference...
> 
> ```
> [jamie@5950x ~]$ v run bfs.v
> Took: 3078575119ns total 3078575ns per search
> [jamie@5950x ~]$ v -prod run bfs.v
> Took: 124029905ns total 124029ns per search
> [jamie@5950x ~]$ 
> ```

Thanks I ran with -prod after installing clang (and later gcc) and it now takes 1600k ns
```v
$if tinyc {
    println('tinyc')
} $else $if clang {
    println('clang')
} $else $if gcc {
    println('gcc')
} $else {
    println('different compiler')
}
```
But adding this snippet it says I'm using a "different compiler". Is there a way to specify which compiler/how -prod finds installed compilers? I couldn't find any docs on -prod

I did find -profile which uses tinyc and outputs `360089ns` for main__bfs which is much more like what I'd expected but not quite the 120k you're getting (beefy pc or using linux?)

**Comment by JalonSolov** [comment]
Beefy pc _and_ linux.  :-)

You can specify the compiler with `-cc` option, as in `-cc gcc` or `-cc clang` or whatever.

And you can use that with/without `-prod`... V defaults to tcc for development because it is so _fast_... all the other compilers take much, much longer, even without optimizing.

**Comment by medvednikov** [comment]
on M1 macbook air:


```
Took: 147971375ns total 147971ns per search
```

**Comment by medvednikov** [comment]
-profile slows the program down by 300%-1000%

**Comment by GregHib** [comment]
> You can specify the compiler with `-cc` option, as in `-cc gcc` or `-cc clang` or whatever.
> 
> And you can use that with/without `-prod`... V defaults to tcc for development because it is so _fast_... all the other compilers take much, much longer, even without optimizing.

Perfect thanks I can now get roughly same results ~320k with -profile and all the compilers

> -profile slows the program down by 300%-1000%

If it works it works, `-cc gcc` I'm still getting 1500k prod or not (not convinced it's actually using gcc because it still outputs "different compiler")

And `-cc clang` gives 2500k regular, or a compiler error when used with -prod

```
 C:\Users\Greg\AppData\Local\Temp\bfs-97b971.o : fatal error LNK1107: invalid or corrupt file: cannot read at 0x148DF0
clang: error: linker command failed with exit code 1107 (use -v to see invocation)
builder error:
==================
C error. This should never happen.
```
