### ISSUE TITLE
Function variable

### ISSUE THREAD

**Issue by ntrel** [vlang/v#120]
I see Go doesn't use function pointers, so I tried this:
```rust
fn f(){}

fn main() {
	mut x := f
	x = 3 //compiles!
	x() //unexpected token '('
}
```
Also how do we write function types?
```rust
//expected `NAME` but got `(`
fn g(fun fn()) {
}
```
(It would be nice if there was a way to ask the compiler to print the type of a symbol, in D I can write `pragma(msg, typeof(&main));` and it prints `void function()`).

**Comment by ntrel** [comment]
The inverse also compiles:
```rust
	mut x := 3
	x = f
	println(x) //4239504
```

**Comment by carueda** [comment]
This simply seems to suggest that type checking is just partially implemented at this point.

**Comment by medvednikov** [comment]
> This simply seems to suggest that type checking is just partially implemented at this point.

Type checking is implemented, and it's very strict. I allowed some exceptions to enable pointer arithmetic in standard library, should have implemented `unsafe` for that. 

Will fix.

**Comment by medvednikov** [comment]
Both of these issues have been fixed.
