### ISSUE TITLE
float formatting issues

### ISSUE THREAD

**Issue by lhmwzy** [vlang/v#1200]
**V version:** 
V 0.1.15

**OS:** 
DragonFly gxdb 5.6-RELEASE DragonFly v5.6.0.1.g3d5034-RELEASE

**What did you do?**
fn main() {
        mut sum := f64(1)
        max := 25 
        for i := 1 ; i <= max; i++ {
                sum *= i
                println(sum) 
                println(i)
        }
}

**What did you expect to see?**
1.000000
2
2.000000
3
6.000000
4
24.000000
5
120.000000
6
720.000000
7
5040.000000
8
40320.000000
9
362880.000000
10
3628800.000000
11
39916800.000000
12
479001600.000000
13
6227020800.000000
14
87178291200.000000
15
1307674368000.000000
16
20922789888000.000000
17
355687428096000.000000
18
6402373705728000.000000
19
121645100408832000.000000
20
2432902008176640000.000000
21
51090942171709440000.000000
22
1124000727777607680000.000000
23
25852016738884976640000.000000
24
620448401733239439360000.000000
25
 
**What did you see instead?**
1.000000
1
2.000000
2
6.000000
3
24.000000
4
120.000000
5
720.000000
6
5040.000000
7
40320.000000
8
362880.000000
9
3628800.000000
10
39916800.000000
11
479001600.000000
12
6227020800.000000
13
87178291200.000000
14
1307674368000.000000
15
20922789888000.000000
16
355687428096000.000000
17
6402373705728000.000000
18
121645100408832000.000000
19
2432902008176640000.000000
20
51090942171709440000.000000
21
1124000727777607680000.000000
22
25852016738884978212864.000000
23
620448401733239409999872.000000
24
15511210043330986055303168.000000
25

When i > 22,the result is not right.

**Comment by justicesuh** [comment]
Maybe I'm misunderstanding what you're asking, but the expected and actual outputs are printing the same values.  The formatting of the expected output is just wrong.

**Comment by joe-conigliaro** [comment]
@lhmwzy  Can you try with C.printf('%.10f\n', sum)

**Comment by lhmwzy** [comment]
the right:
2432902008176640000.000000
21
51090942171709440000.000000
22
1124000727777607680000.000000
23
25852016738884976640000.000000
24
620448401733239439360000.000000
25

actual output:
1124000727777607680000.000000
22
25852016738884978212864.000000
23
620448401733239409999872.000000
24
15511210043330986055303168.000000
25

C.printf('%.10f\n', sum) the result is same with above.

**Comment by lhmwzy** [comment]
> 
> 
> Maybe I'm misunderstanding what you're asking, but the expected and actual outputs are printing the same values. The formatting of the expected output is just wrong.

YES,The formatting of the expected output is just wrong.

**Comment by penguindark** [comment]
We choosed the format of float output time ago and it is not 1:1 with `C.printf` that is machine/OS dependent. Have the same format it is possible using the `strconv` utilities functions.
