### ISSUE TITLE
error building on musl libc(without atomic.h  header)

### ISSUE THREAD

**Issue by 0verse** [vlang/v#12026]
**V version:** 
v 8705db5 and vc e59b788
**OS:** 
musl libc based linux distro

**What did you do?**
tried to compile vc through git, the latest master (e59b788)

**What did you expect to see?**
complete compiling the vc binary
 
**What did you see instead?**

> ../vc/v.c:1309:2: error: #error VERROR_MESSAGE Header file <atomic.h>, needed for module `sync` was not found. Please install the corresponding development headers.
>  1309 | #error VERROR_MESSAGE Header file <atomic.h>, needed for module `sync` was not found. Please install the corresponding development headers.
>       |  ^~~~~
> ../vc/v.c:5666:9: error: unknown type name 'atomic_uintptr_t'
>  5666 |         atomic_uintptr_t write_adr;
>       |         ^~~~~~~~~~~~~~~~
> ../vc/v.c:5667:9: error: unknown type name 'atomic_uintptr_t'
>  5667 |         atomic_uintptr_t read_adr;
>       |         ^~~~~~~~~~~~~~~~
> ../vc/v.c:5668:9: error: unknown type name 'atomic_uintptr_t'
>  5668 |         atomic_uintptr_t adr_read;
>       |         ^~~~~~~~~~~~~~~~
> ../vc/v.c:5669:9: error: unknown type name 'atomic_uintptr_t'
>  5669 |         atomic_uintptr_t adr_written;
>       |         ^~~~~~~~~~~~~~~~

**Comment by medvednikov** [comment]
Thanks. Try `-no-parallel` for now as a workaround.

**Comment by 0verse** [comment]
it errors before v is even built. I,m building vc like thıs:

> cc -std=gnu11 -w -o v ../vc/v.c -lm $LDFLAGS

**Comment by 0verse** [comment]
I,ve included '-I ./thirdparty/stdatomic/nix' to the CC line and it compiles fine now. Like this:

> cc -std=gnu11 -w -I ./thirdparty/stdatomic/nix -o v ../vc/v.c -lm $LDFLAGS
