### ISSUE TITLE
Issues with buliding V on non-x86

### ISSUE THREAD

**Issue by lancethepants** [vlang/v#12027]
**V version:**  V 0.2.4 8705db5
**OS:** linux 2.6.36.4 - armv7a

**What did you do?**
`make`
&
`VFLAGS="-prod" make`

**What did you expect to see?**
Successfully built V
 
**What did you see instead?**
When running `make` on my _arm_ platform V tries to build using tcc built for x86.  Obviously on non-x86 platforms tcc will not run.  Previously V would gracefully fail when trying to use tcc on non-x86 and then fallback to the system compiler.  Actually I've noticed over the last year or two this is constantly being broken and then eventually fixed, going back and forth. 

It order to get around this I will do a production build using `VFLAGS="-prod" make`, but this recently gives me a different error now in the 2nd section below.  It sucessfully builds v1.exe but when building v2.exe I get the error `error: unknown type name 'pthread_rwlockattr_t'`.  It's like -lpthread isn't getting passed when compiling v2.exe like it explicitly shows on v1.exe. I haven't run into this issue in the past.  I try adding `LDFLAGS="-lm -lpthread` to that compilation line of code because I know V should honor LDFLAGS (I use it when compiling  programs), but it still refuses to build.

So now I just can't get V to build on my non-x86 platform.

```
root@R7000:~/src/v# make
cd ./vc && git clean -xf && git pull --quiet
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -std=gnu99 -w -I ./thirdparty/stdatomic/nix -o v1.exe ./vc/v.c -lm -lpthread
./v1.exe -no-parallel -o v2.exe  cmd/v
==================
sh: /mmc/src/v/thirdparty/tcc/tcc.exe: not found
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

make: *** [GNUmakefile:94: all] Error 1
```
```
root@R7000:~/src/v# VFLAGS="-prod" make
cd ./vc && git clean -xf && git pull --quiet
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -std=gnu99 -w -I ./thirdparty/stdatomic/nix -o v1.exe ./vc/v.c -lm -lpthread
./v1.exe -no-parallel -o v2.exe -prod cmd/v
==================
      |         ^~~~~~~~~~~~~~~~
/mmc/tmp/v/v2.exe.3592536750096677203.tmp.c:4100:9: error: unknown type name 'pthread_rwlockattr_t'
 4100 |         pthread_rwlockattr_t attr;
      |         ^~~~~~~~~~~~~~~~~~~~
/mmc/tmp/v/v2.exe.3592536750096677203.tmp.c: In function 'ptr_str':
/mmc/tmp/v/v2.exe.3592536750096677203.tmp.c:18268:32: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
18268 |         string buf1 = u64_hex(((u64)(ptr)));
      |                                ^
/mmc/tmp/v/v2.exe.3592536750096677203.tmp.c: In function 'char_str':
/mmc/tmp/v/v2.exe.3592536750096677203.tmp.c:18281:25: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
18281 |         return u64_hex(((u64)(cptr)));
      |                         ^
```

**Comment by lancethepants** [comment]
https://github.com/vlang/v/pull/12236 fixes this issue.

**Comment by Crilum** [comment]
Hello, I still have the tcc.exe error:
```
$ v upgrade
failed    cmd: "/home/pi/src/v/v" -skip-unused "/home/pi/src/v/cmd/tools/vpm.v"
failed   code: 1
failed thirdparty object build cmd:
/home/pi/src/v/thirdparty/tcc/tcc.exe   -std=gnu99 -D_DEFAULT_SOURCE  -fPIC -I "/home/pi/src/v/thirdparty/cJSON" -o "/home/pi/.vmodules/cache/22/22aa021cb02ef6b06e989ef04fa5aa68.o" -c "/home/pi/src/v/thirdparty/cJSON/cJSON.c" 
builder error: sh: 1: /home/pi/src/v/thirdparty/tcc/tcc.exe: not found
```
It also throws the `builder error` whenever I try to install a module with `v install`.

I'm on a Raspberry Pi 4 (armv7l), arm64 kernel, and armhf Raspberry Pi OS.
