### ISSUE TITLE
Using #define macros from C files

### ISSUE THREAD

**Issue by jordan-bonecutter** [vlang/v#12033]
I'm trying to make a port of a C library to V, but one issue im having is that V currently only supports calling C functions. In order to create a V binding properly, I need access to all macros defined in the library (I could copy-paste them but that's a bad solution). Is there a way to do this already or does it need to be added?

**Comment by Larpon** [comment]
If the macro is a value you can use a `const`:
```v
module foo

pub const val = C.VAL
```
If it's a function you should be able to call it if you have a definition for it:
```v
module foo

fn C.call (a int, b int) int
```

If the macro is really tricky you can resort to including your own wrapper/helper functions you then expose to V the normal way (like above)

**Comment by jordan-bonecutter** [comment]
> If the macro is really tricky you can resort to including your own C wrapper/helper functions you then expose to V the normal way:
> 
> wrap.h:
> 
> ```c
> #include "foo.h"
> 
> void helper() {
>     MACRO_CALL()
> }
> ```
> 
> wrap.c.v:
> 
> ```v
> #include @VMODROOT/wrap.h
> 
> fn C.helper()
> ```

I was considering this but thought it kind of hacky, I'll just stick with it for now though. Any technical reason we can't glean some info from h files (coming from a compiler / V noob here so this may be a fabulously stupid question)?

**Comment by spytheman** [comment]
> Any technical reason we can't glean some info from h files (coming from a compiler / V noob here so this may be a fabulously stupid question)?

Yes, that would require a C parser implemented in V (including handling preprocessing), and we do not have that.

**Comment by jordan-bonecutter** [comment]
Yeah made sense. Thanks!
