### ISSUE TITLE
Unable to sort StopWatch.elapsed / sort() does not support functions

### ISSUE THREAD

**Issue by jdonnerstag** [vlang/v#12044]
Like a profiler, my little app collects statistics, include elapsed time. I'm using StopWatch to measure the time elapsed. Again like a profiler, I want to print a histogram sorted by elapsed time, The issue is that StopWatch.elapsed is private and thus not accessible in `sort(a.elapsed > b.elapsed)`. StopWatch has an `elapsed()` function though, but V does not allow functions in sort, such as `sort(a.elapsed() > b.elapsed())`.

The simple solution would be to make elapsed public (and may be that is a quick fix), but that functions are not allowed in sort() is quite a limitation.

**Comment by JalonSolov** [comment]
You can use `sort_with_compare` and put whatever you wish in the compare function.
