### ISSUE TITLE
Escaping for reserved identifiers

### ISSUE THREAD

**Issue by neverix** [vlang/v#1204]
#1173 raises a valid point: some identifiers (like `type`) are reserved keywords. Adding specific workarounds for each keywoard is hacky and there needs to be a general way to do this, as @ntrel pointed out in [his comment](https://github.com/vlang/v/issues/1173#issuecomment-511867729).

There are two ways to do this syntax wise: [like Kotlin does it (backticks surrounding the identifier)](https://kotlinlang.org/docs/reference/java-interop.html#escaping-for-java-identifiers-that-are-keywords-in-kotlin) or [use the D convention (underscore suffix) and integrate it into the compiler](https://github.com/vlang/v/issues/1173#issuecomment-511867729). I prefer the former.

**Comment by medvednikov** [comment]
I agree. My solution with `struct Foo { field type }` is a hack, and will be replaced.

**Comment by medvednikov** [comment]
`type` is such a common name though, perhaps another keyword (like `alias`) should be used.

**Comment by neverix** [comment]
How would this keyword be used?

**Comment by medvednikov** [comment]
right now `type` is only used for aliasing: `type myint int`

**Comment by neverix** [comment]
Oh, you meant replacing `type` with another keyword.

I think that would go against V's goals, namely familiarity, as `type` and similar keywords (e.g. `typedef`) are used in popular programming languages like Go and C which it draws inspiration from.

**Comment by medvednikov** [comment]
`type` is not used in C, but yes that would be moving away from Go's syntax.

**Comment by neverix** [comment]
Yes, but I said `and similar keywords (e.g. typedef)` there.

In my opinion, `alias` would be a bit unclear. Besides, that's a radical change to the syntax that breaks the promise of the language staying more or less the same since the initial release.

**Comment by medvednikov** [comment]
Missed that, you are right :)

**Comment by neverix** [comment]
What's your opinion on identifier escaping syntax? Should we use backticks, underscore suffixes or something else entirely?

**Comment by ntrel** [comment]
> alias would be a bit unclear.

`alias New = Old` seems clear. Keywords with a more general word means they have more ability to be reused in different contexts. D has alias instead of typedef (it doesn't create a new type, only a new symbol that resolves to the old, the symbol can be anything not just types).

> Besides, that's a radical change to the syntax that breaks the promise of the language staying more or less the same since the initial release.

I don't think `type` has been documented.

> Should we use backticks

Backticks are currently used for character literals.

**Comment by neverix** [comment]
> `alias New = Old` seems clear. Keywords with a more general word means they have more ability to be reused in different contexts. D has alias instead of typedef (it doesn't create a new type, only a new symbol that resolves to the old, the symbol can be anything not just types).

IMO this shouldn't be used for V. There are already specialized ways to create aliases for identifiers and having an alias keyword just adds one more way to do things. Adding `alias` would make several removals necessary in order to obey V's principles and will affect the design of the entire language.
 
This is not the point of this discussion. Maybe the `alias` that you described would be fine, maybe not - this is a matter for a different issue.
> I don't think type has been documented.

That's right, but it is still present in the list of keywords.
> Backticks are currently used for character literals.

Yeah, my fault for not noticing! Note that this is not mentioned in the documentation either, I had to manually `grep` the `v` repo.

Backticks are mostly used in the comments for the purpose of quoting identifiers. Real-world usage of single characters is surprisingly low - maybe we can do away with an `ord()` that would also work in runtime? This should be discussed in another issue too.

Could the community suggest some possible syntaxes for identifier escaping and then vote for them? I'm not sure if backticks or underscores will be a good fit for V in its current state. We could look into how other languages solve this issue.

**Comment by medvednikov** [comment]
I think `type_` is fine.

**Comment by medvednikov** [comment]
I'll be updating the documentation this week. I'll everything that's missing (including character literals).

**Comment by neverix** [comment]
> I think `type_` is fine.
Perhaps, but that would be a bit inconsistent with the naming used for comments. Also, just having an underscore could clash with some names in subtle ways, and this does not solve the issue of creating identifiers with arbitrary characters in their names which is an added benefit of using Kotlin's approach.

 My personal preference for this is backticks + `ord()`, YMMV.

**Comment by emily33901** [comment]
If `type_` parses out to `type` then how would i reference a variable that is actually `type_` (through c interop etc...).
I always thought that the C# `@` prefix worked pretty well - where `@this` always becomes `this` in the binary.

> and this does not solve the issue of creating identifiers with arbitrary characters in their names which is an additional benefit of using Kotlin's approach.

Why should we need arbitrary characters?

**Comment by medvednikov** [comment]
Yes, I forgot about C#'s `@this`.

> Why should we need arbitrary characters?

Indeed we don't :)

V doesn't even allow non-ASCII identifiers.

**Comment by iredmail** [comment]
> In my opinion, alias would be a bit unclear. Besides, that's a radical change to the syntax that breaks the promise of the language staying more or less the same since the initial release.

No one is using V in production (except Alex maybe), no need to stay “the same” as the initial 0.1 release or document at this stage. Please just make it right with any necessary changes when we still have time. After 1.0, I guess it too late.

**Comment by neverix** [comment]
> If type_ parses out to type then how would i reference a variable that is actually type_ (through c interop etc...).
I always thought that the C# @ prefix worked pretty well - where @this always becomes this in the binary.

Yes, that would be a good solution too.
> Indeed we don't :)
V doesn't even allow non-ASCII identifiers.

That's the whole point of it; if at any point a user needs to interface with a library which doesn't use V's subset of ASCII, the compiler can be easily modified to support it without breaking existing semantics. I do realize that nobody will probably ever use this.
> No one is using V in production (except Alex maybe), just few users are trying to write some modules for fun in github, no need to stay “the same” as the initial 0.1 release or document at this stage. Please just make it right with any necessary changes when we still have time. After 1.0, I guess it’s too late.

Yes, that was only a side-argument :)

**Comment by medvednikov** [comment]
Just out of curiosity, has anyone ever used a C library with non-ASCII exports? :)

**Comment by neverix** [comment]
IIRC Go's runtime has some non-ASCII characters in identifiers, but I'll have to check that ;)

**Comment by neverix** [comment]
Looks like that was removed

**Comment by medvednikov** [comment]
Fixed:

```
struct Test {
  @type string
}

test.@type = 'test'
```
