### ISSUE TITLE
Mutable variables aren't smart casted

### ISSUE THREAD

**Issue by Wertzui123** [vlang/v#12058]
**V version:** V 0.2.4 a8c2c41
**OS:** Windows

**What did you do?**
```v
interface IExample{
}

struct Example{
	field string
}

fn main(){
	mut example := IExample(Example{field:"test"})
	if example is Example{
		println(example.field)
	}
}
```

**What did you expect to see?**
```
test
```
 
**What did you see instead?**
```
main.v:11:19: error: type `IExample` has no field named `field`
```
I get the correct result when removing the (in this case unnecessary) `mut` keyword.

**Comment by yuyi98** [comment]
```vlang
			// smartcast either if the value is immutable or if the mut argument is explicitly given
			if !is_mut || expr.is_mut {
```

Not sure why?

**Comment by Wertzui123** [comment]
Ah, ok, but: why?

**Comment by Wertzui123** [comment]
Also, there should be a warning if you don'T use the `if mut` I think. It just isn't clear.

**Comment by Wertzui123** [comment]
> 
> 
> ```v
> 			// smartcast either if the value is immutable or if the mut argument is explicitly given
> 			if !is_mut || expr.is_mut {
> ```
> 
> Not sure why? According to this rule, we should use `if mut example is Example {`.

That actually works, thanks.
Maybe this should be converted to a discussion?

**Comment by yuyi98** [comment]
This is best explained in doc.md.

**Comment by Wertzui123** [comment]
> If w is a mutable identifier, it would be unsafe if the compiler smart casts it without a warning

First of all, I don't really see how it's unsafe.
And secondly, the compiler should at least throw a warning, since such a smart cast literally does nothing currently.

**Comment by yuyi98** [comment]
Because V itself has a large number of such cases, there are a large number of warnings or notices if we throw warning or notices.

**Comment by kahsa** [comment]
Isn't this a matter of the `is` behaviour changing with or without `mut`?

```v
interface IExample{
}

struct Example{
	field string
}

fn main(){
	example := IExample(Example{field:"test"})
	if example is Example{
		println(typeof(example).name)
	}
}
```
```
> v run main.v
&Example
```

```v
interface IExample{
}

struct Example{
	field string
}

fn main(){
	mut example := IExample(Example{field:"test"})
	if example is Example{
		println(typeof(example).name)
	}
}
```
```
> v run main.v
IExample
```
