### ISSUE TITLE
Using make.bat, fault.

### ISSUE THREAD

**Issue by alfie-xuww** [vlang/v#1205]
**V version:** V 0.1.16
**OS:** win10 1803

**What did you do?**
I used make.bat to install v, bug got nothing. 
Then run the "gcc -std=gnu11 -w -o v.exe v.c".The error message is "cce1znT0.o:v.c:(.text+0x6e6e): undefined reference to `__imp_gethostname' collect2.exe: error: ld returned 1 exit status.

**What did you expect to see?**
I want to see the v.exe in the file explorer.
 
**What did you see instead?**
Nothing.

**Comment by nedpals** [comment]
Hi @alfie-xuww ! Will be going to fix it later, but you need to modify the following line in make.bat:
Replace this
```
gcc -std=gnu11 -w -o v.exe v.c
```
into this
```
gcc -std=gnu11 -w -o v.exe v.c -lws2_32
```

**Comment by alfie-xuww** [comment]
ok, thinks.

**Comment by medvednikov** [comment]
No longer needed, fixed.
