### ISSUE TITLE
math: more than one definition for each of fns "min","max" and "abs"

### ISSUE THREAD

**Issue by binarygcd** [vlang/v#12070]
**builtin** has fns **f32/64_min/max/abs**
**math** has **min**, **max** and **abs/fabs**
**math.mathutil** has **min**, **max** and **abs**.
**math.util** has **imin/max**, **umin/max**, **fmin/fmax/fabs_32/64**

For arrays,
**arrays** has **max/min** and **idx_min/max**, and they return **?T/int**
**math.stats** has **max/min** and **min/max_index**, and they return **T/int**

Is there a reason for this?

**Comment by spytheman** [comment]
yes - importing a whole module for trivial functions has downsides.
