### ISSUE TITLE
Lots of unused/unrelated code being generated

### ISSUE THREAD

**Issue by AlectronikForge** [vlang/v#12079]
I tried to use V for a toy bare metal project much like in the way you do with vinix. But I got stuck with loads and loads of unrelated imports and code being generated out of very little sample v files. How do you basically tell the compiler to use a freestanding environment?

Sorry I would have liked to ask this question in a chat or forum but couldn't find one.

**Comment by JalonSolov** [comment]
`-skip-unused` flag is WIP, but does work... just not as well as it should, yet.

Discord forums are used... there's a badge on the home page, but here's the URL:  https://discord.gg/vlang
