### ISSUE TITLE
builder error for tuple optional

### ISSUE THREAD

**Issue by ken0x0a** [vlang/v#12095]
OS: macos, macOS, 11.6, 20G165
Processor: 16 cpus, 64bit, little endian, Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
CC version: Apple clang version 13.0.0 (clang-1300.0.29.3)

getwd: /Users/user/code/lang/v/v_issue_tuple_optional
vmodules: /Users/user/.vmodules
vroot: /Users/user/src/v
vexe: /Users/user/src/v/v
vexe mtime: 2021-10-07 00:50:46
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 4333a53.f454d30
env VFLAGS: "-no-parallel"

Git version: git version 2.33.0
Git vroot status: weekly.2021.39.1-73-gf454d303-dirty

**What did you do?**
```sh
fn main() {
	a, b := optional() or {
		optional() ? // this line
	}
	assert a == 1.0
	assert b == 3.0
}

fn optional() ?(f64,f64) {
	return 1, 3
}
```

**What did you expect to see?**
no errors
 
**What did you see instead?**
```
==================
/tmp/v/tuple_optional.13218474538935463638.tmp.c:10393:38: error: assigning to 'multi_return_f64_f64' (aka 'struct multi_return_f64_f64') from incompatible type 'Option_multi_return_f64_f64' (aka 'struct Option_multi_return_f64_f64')
                *(multi_return_f64_f64*) _t1.data =  _t2 /*U*/;
                                                  ^  ~~~
1 error generated.
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.
```

**Comment by nyx-litenite** [comment]
Not that this helps you at all, but it's not a tuple. It looks like them from other langs, but it's just the syntax for multiple returns. Just informing you, so you can more easily convey your meaning on future.

I think  your error is that v's or expects to only return a single val, unless you explicitly tell it otherwise; which is why the latter works.

**Comment by ken0x0a** [comment]
Works already
