### ISSUE TITLE
unions

### ISSUE THREAD

**Issue by l8atnight** [vlang/v#1211]
hi,
will there be unions? if not, please introduce them to the language.
thanx

**Comment by medvednikov** [comment]
Please write a simple example of what you need.

**Comment by l8atnight** [comment]
i hope this shows what i mean

union DummyUnion {
	x int
	z u64
	txt string 
} 

struct IllusionPoint {
	x int
	y int 
	addinfo DummyUnion
} 

struct IllusionPoint0 {
	x int
	y int 
	addinfo DummyUnion
	union addinfo {
		x int
		z u64
		txt string 
  } 
} 

struct IllusionPoint1 {
	x int
	y int 
	addinfo1 IllusionPoint
}

**Comment by medvednikov** [comment]
So like C unions?

They are partly supported already.

**Comment by l8atnight** [comment]
yes, there are many c headers that use them.
how are they done partly now?

**Comment by medvednikov** [comment]
I implemented them for the C to V translated code. I think they can only be used with a flag right now.

Anyway they are not stable yet.

So the answer is yes, C unions will be supported :)

**Comment by l8atnight** [comment]
super!! thanx

**Comment by ntrel** [comment]
C unions are unsafe. Maybe we could have a generic `Union<T1, T2, T3>` struct. That would require variadic template arguments (or making Union built-in to the language). It would track which type was currently assigned or none. It would be type safe. There would be a method `get<T>() ?T` that returns an optional.

**Comment by ntrel** [comment]
Or as a workaround, have Union2, Union3, etc struct templates with the corresponding number of type parameters.

**Comment by nedpals** [comment]
Unions have already been implemented but undocumented.
