### ISSUE TITLE
Can't use json.encode_pretty with struct literal

### ISSUE THREAD

**Issue by jangler** [vlang/v#12118]
**What did you do?**
`v -g -o vdbg cmd/v && vdbg main.v`
```v
import json

struct Test {}

fn main() {
	json.encode_pretty(Test{})
}

```

**What did you expect to see?**

Not a compiler error. The same argument works fine for json.encode, and the documentation indicates that json.encode_pretty has the same signature.

**What did you see instead?**
```
main.v:6:21: error: expression cannot be passed as `voidptr`
    4 | 
    5 | fn main() {
    6 |     json.encode_pretty(Test{})
      |                        ~~~~~~
    7 | }
```

**Comment by enghitalo** [comment]
fixed in x.json2

**Comment by enghitalo** [comment]
try
```v
import x.json2 as json

struct Test {}

fn main() {
	json.encode_pretty(Test{})
}

```

**Comment by spytheman** [comment]
The error is a checker one, not a cgen one + there is a known workaround by just using `x.json2` instead.
