### ISSUE TITLE
Default struct values are ignored by json.decode

### ISSUE THREAD

**Issue by jangler** [vlang/v#12134]
**What did you do?**
`v -g -o vdbg cmd/v && vdbg main.v`
```v
import json

struct Test {
	x int = 1
}

fn main() {
	t := json.decode(Test, '{}') ?
	println(t)
}

```

**What did you expect to see?**

`Test { x: 1 }`, since 1 is the default value for Test.x and no value was supplied in the JSON.

**What did you see instead?**
```
Test{
    x: 0
}
```

**Comment by kahsa** [comment]
```
> v run bug.v
Test{
    x: 1
}
```
already fixed in V 0.3.2 74613bd
