### ISSUE TITLE
Warnings when building V via MSVC

### ISSUE THREAD

**Issue by notvillain** [vlang/v#12160]
**V version:** 
V 0.2.4 a0a0ae8

**OS:**
Windows 11 Enterprise Insider Preview (Build 22454.rs_prerelease.210903-1516)

**What did you do?**
I git cloned V and built it using MSVC.

**What did you expect to see?**
Building with no warnings.
 
**What did you see instead?**
Building with a lot of warnings.

Attached is the build log and the generated `v.c` and `v_win.c` files.
[v_build_log.txt](https://github.com/vlang/v/files/7330979/v_build_log.txt)
[v.c.txt](https://github.com/vlang/v/files/7331118/v.c.txt)
[v_win.c.txt](https://github.com/vlang/v/files/7331078/v_win.c.txt)

**Comment by medvednikov** [comment]
No more warnings with msvc.
