### ISSUE TITLE
v failed to run on win10

### ISSUE THREAD

**Issue by shady7shen** [vlang/v#12165]
**V version:** 0.2.4 or latest weekly build 
**OS:**  Windows10 21H1 (19043.1237)

**What did you do?**
run v.exe in windows cmd.exe
or run helloworld example by : v run hello.v

**What did you expect to see?**
v repl runtime
 
**What did you see instead?**

Error message 

E:\v_windows_weekly\v>v
Welcome to the V REPL (for help with V itself, type  exit , then run  v help ).
  NB: the REPL is highly experimental. For best V experience, use a text editor,
  save your code in a  main.v  file and execute:  v run main.v
V panic: substr(4, 0) out of bounds (len=0)
v hash: 6c6bb08
C:/Users/RUNNER~1/AppData/Local/Temp/v/v2.6932222957723323919.tmp.c:17733: at _v_panic: Backtrace
C:/Users/RUNNER~1/AppData/Local/Temp/v/v2.6932222957723323919.tmp.c:20674: by string_substr
C:/Users/RUNNER~1/AppData/Local/Temp/v/v2.6932222957723323919.tmp.c:28254: by os__real_path
C:/Users/RUNNER~1/AppData/Local/Temp/v/v2.6932222957723323919.tmp.c:33420: by v__pref__vexe_path
C:/Users/RUNNER~1/AppData/Local/Temp/v/v2.6932222957723323919.tmp.c:36331: by v__util__launch_tool
C:/Users/RUNNER~1/AppData/Local/Temp/v/v2.6932222957723323919.tmp.c:25569: by main__main
C:/Users/RUNNER~1/AppData/Local/Temp/v/v2.6932222957723323919.tmp.c:26401: by wmain
00937540 : by ???
009376a3 : by ???
7ffd8e527034 : by ???

**Comment by JalonSolov** [comment]
Works fine here:
```
PS C:\Users\jamie> v
Welcome to the V REPL (for help with V itself, type  exit , then run  v help ).
  NB: the REPL is highly experimental. For best V experience, use a text editor,
  save your code in a  main.v  file and execute:  v run main.v
V 0.2.4 a0a0ae8
Use Ctrl-C or  exit  to exit, or  help  to see other available commands
>>> 3+2
5
>>> exit

PS C:\Users\jamie> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0


PS C:\Users\jamie>
```
