### ISSUE TITLE
or block is inconsistent between the compiler and the runtime

### ISSUE THREAD

**Issue by Wertzui123** [vlang/v#12197]
**V version:** V 0.2.4 dee4ffb
**OS:** Windows

**What did you do?**
```v
println([]string{}[0] or { if true { "a" } else { "b" } })
```

**What did you expect to see?**
So, this is where it gets inconsistent:

The compiler thinks since in all paths there's a last statement, this should work.
But the runtime assumes that the if statement is the last statement and since it doesn't return anything it's `NIL`.

I think this should return `b` since it removes the need for boilerplate code and looks quite intuitive.
 
**What did you see instead?**
```
println(NIL)
```

**Note:** I can't assign myself to this issue, but I want to try to fix this myself as soon as we have decided whether this should compile and print `a` or shouldn't compile at all.

**Comment by spytheman** [comment]
it is a C codegen problem

**Comment by medvednikov** [comment]
This is a bug in the V compiler (cgen).
