### ISSUE TITLE
v-run arbitrary command execution

### ISSUE THREAD

**Issue by czkz** [vlang/v#12206]
**V version:** `V 0.2.4 d329e1d.b62515d`
**OS:** `linux, "Void Linux"`

bug.v:
```v
fn main() {
	println('Hello, World!')
}
```

---

Running `v run bug.v $'abc\nwhoami\nuname'` produces incorrect output:
```
Hello, World!
dek
Linux
```
(whoami and uname are executed)

---

Running `v bug.v && ./bug $'abc\nwhoami\nuname'` produces correct output:
```
Hello, World!
```

---

Running `v run $'abc\nwhoami'` seems to produce correct output:
```
v expects that `abc
whoami` exists, but it does not
```

**Comment by czkz** [comment]
It makes sense that shell treats each line as a separate command, but shell should not be involved in the first place.
`v run` (3rd case) is syntactic sugar for the 2nd case, and should have the same behavior (that is calling ./args directly and not via `sh -c`).

**Comment by czkz** [comment]
Well, using `os.system()` is a terrible way to run a program!
- [OWASP on system() security](https://owasp.org/www-community/attacks/Command_Injection)
- [Why system() is evil](https://www.cplusplus.com/articles/j3wTURfi/)
- [`man 3 system`, sections Caveats, Bugs](https://man7.org/linux/man-pages/man3/system.3.html)
- [SO: alternatives to system()](https://stackoverflow.com/a/28137786)

A better way to execute a program:
```v
import os

fn main() {
	assert os.args.len >= 2
	mut p := os.new_process(os.args[1])
	p.set_args(os.args[2..])
	p.wait()
}
```

**Comment by JalonSolov** [comment]
PRs are always welcome.

**Comment by czkz** [comment]
> PRs are always welcome.

That's nice to hear, hopefully will do it today.

Arguments with linefeeds are indeed used pretty much never, but surprisingly, I managed to discover this bug the hard way.

os.Process [uses](https://github.com/vlang/v/blob/29f068997b7bccdc6c400303e4be910b1231b0c7/vlib/os/process_nix.c.v#L13) os.fork() and os.execve() under the hood, and [man system](https://man7.org/linux/man-pages/man3/system.3.html) says that this is how system() works too, so I assume no performance issues.

A basic benchmark seems to confirm it:

```v
import os
import benchmark

mut b1 := benchmark.start()
for _ in 0 .. 1000 {
	os.system('true')
}
b1.measure('system')

mut b2 := benchmark.start()
for _ in 0 .. 1000 {
	mut p := os.new_process('/usr/bin/true')
	p.wait()
}
b2.measure('Process')

mut b3 := benchmark.start()
for _ in 0 .. 1000 {
	if os.fork() == 0 {
		os.execvp('/usr/bin/true', []) ?
	} else {
		os.wait()
	}
}
b3.measure('fork')
```
```
 SPENT  3559.638 ms in system
 SPENT  1362.702 ms in Process
 SPENT  1345.711 ms in fork
```
