### ISSUE TITLE
call C++ from V

### ISSUE THREAD

**Issue by sh4m2hwz** [vlang/v#12202]
how to call C++ code from V code?
I have such ideas: 
1) it is to use export "C", but on the other hand, if the year is on templates and uses operator and function overloads, then this will not work
2) try how to use golang, but I'm afraid these are different languages, although the C backend for Vlang and for Golang is gc, but the C backend is just an intermediate high-level representation, while gc is a compiler, that is, gcc, if I'm not mistaken :)

**Comment by JalonSolov** [comment]
You can't call C++ from V unless the functions you want to call were declared with `extern "C"`.  Otherwise V will never find the "mangled" names C++ creates.  If they _are_ declared with `extern "C"`, then calling them is no different from calling C code - it works fine.
