### ISSUE TITLE
Who do compile or run vlang under Android?

### ISSUE THREAD

**Issue by changrui** [vlang/v#1220]
`**Installing V from source**
Linux, macOS, Windows, WSL, **Android**, Raspberry Pi

git clone https://github.com/vlang/v

cd v

make

That's it! Now you have a V executable at [path to V repo]/v. [path to V repo] can be anywhere.`

**I don't know how to do it?**

**Comment by hazohelet** [comment]
Termux

**Comment by changrui** [comment]
I know, thanks.
