### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by czkz** [vlang/v#12228]
tldr: Issues in doc/docs.md from a newcomer's PoV

I wrote this a month ago, while reading the docs, with no prior knowledge of V, Go, Rust, Nim, in hopes that it will provide a point of view experienced V developers don't have.
I reviewed the text today and removed all the issues that got fixed, so all the remaining issues/links are still valid (right now 3af53e2 is the latest commit).
_Italic text_ is used for remarks I made today, **with hindsight of using the language for a month**.

There were also a lot of typos, which I separated into #12227.

There are probably better ways to format this, but I'm not aware of any :confused:

---

---

https://github.com/vlang/v/blob/master/doc/docs.md#strings
Missing info on how to convert []byte back to string

_Found this through trial and error, not sure it it's the intended way:_
```v
b := 'abc'.bytes()
s := string(b)
```

---

https://github.com/vlang/v/blob/master/doc/docs.md#fixed-size-arrays
> anums := fnums[0..fnums.len]

fnums[..] is much more compact, and works with anonymous variables (doesn't require a variable to get its .len).
Not sure if this syntax is a bug, but it works with V 0.2.4 5010d18.

_Still works in V 0.2.4 a006090_

---

https://github.com/vlang/v/blob/master/doc/docs.md#fixed-size-arrays
Missing info on how to convert a dynamic array to a fixed array

_Still haven't found a way to do it, maybe I should make a Feature Request? Fixed arrays are very hard to use without it._

---

https://github.com/vlang/v/blob/master/doc/docs.md#type-checks-and-casts
> Mutable variables can change, and doing a cast would be unsafe

DOESN'T MAKE SENSE

_It's not explained why doing a cast would be unsafe, and it's not something obvious; I really don't know why it would be unsafe_

---

https://github.com/vlang/v/blob/master/doc/docs.md#short-struct-literal-syntax
> you can omit the struct name when it's already known

But nothing is omitted

_Still can't figure out what was supposed to be omitted_

---

https://github.com/vlang/v/blob/master/doc/docs.md#mutable-arguments
> Use user.register() or user = register(user) instead of register(mut user).

Misleading into thinking that these are the ways the code above can be used

---

https://github.com/vlang/v/blob/master/doc/docs.md#manage-packages
> Read more:

Missing link

_I now see that it's not a missing link, but refers to "Briefly:" above. This should probably be removed/reworded._

---

https://github.com/vlang/v/blob/master/doc/docs.md#module-options
> Or you can update all your modules:

No info about upgrade command, how it's different from update with no options

---

https://github.com/vlang/v/blob/master/doc/docs.md#publish-package
It's strange that there's language info, then package management, then language info again. Consider relocating the "Modules" section.

---

https://github.com/vlang/v/blob/master/doc/docs.md#interfaces
Would be nice to have questionable design choices explained - no "implement" keyword seems like a bad design choice to me (wouldn't it be tidious to implement large interfaces when you have to manually remember all the fields you have to define?)
If I knew why it was made, or maybe there was some counterpoint to what I thought, it would've made sense but without any of that people might tend to think that it's just objectively bad.

---

https://github.com/vlang/v/blob/master/doc/docs.md#channel-select
> `else` and `> timeout` are mutually exclusive

'>' is a typo or it's unclear what it means

---

https://github.com/vlang/v/blob/master/doc/docs.md#channel-select
This is the first snipped I tried to compile and it failed with "library 'atomic' not found". I assumed it just wasn't implemented yet, but that would be nice to know beforehand, for example in the beginning of the docs.

_Two weeks later I discovered that it actually was implemented, but I had to install libatomic-devel. Which is a huge problem:_
- _The language is very alpha, some features are not implemented now, but some of them are (or might be) in the docs._
- _And it's advertized that V requires (or maybe will require?) no dependencies._
- _And it fails with a very cryptic message (Invalid relocation entry '.rela.debug_info' @ 000004f6...)._
- _So most people will probably think that the language is broken, that docs describe what the language wants to be and not what it is._
- _And, thinking that all those awesome features are not real, they will likely leave._
- _Which is especially sad because the language does have all these features._

_Later I discovered that there were some other libs I had to install in order for V to work; I don't remember them now, but it's a good idea to have a list of things required for V to work at least with built-in features like channels._

---

https://github.com/vlang/v/blob/master/doc/docs.md#memory-management
> Remaining small percentage of objects is freed via reference counting.

But on https://vlang.io it's said: "Remaining small percentage of objects is freed via GC".

_I don't know which one is correct so I can't fix it._

---

https://github.com/vlang/v/blob/master/doc/docs.md#structs-with-reference-fields
> for now data structures <...> understanding that it is unsafe

malformed sentence

_Also it's not explained why an unsafe operation is not wrapped in an unsafe{} block (maybe it should be?)._

---

https://github.com/vlang/v/blob/master/doc/docs.md#embed_file
> Instead, it will be loaded the first time your program calls `f.data()` at runtime...

What is `f.data()`?
The code snippet above doesn't have `f.data()`, nor there are any explanations later in the docs.

---

https://github.com/vlang/v/blob/master/doc/docs.md#compile-time-reflection
Not clear whether get_string and get_int are built-in functions or example functions.
Add something along the lines of
```v
fn get_string(data string, field_name string) string {
    // ...
}
fn get_int(data string, field_name string) string {
    // ...
}
```

_There are probably no global built-in functions in V (except `println()`, etc.), but a newcomer wouldn't know that._

---

https://github.com/vlang/v/blob/master/doc/docs.md#limited-operator-overloading
> Assignment operators <...> are auto generated <...> though they must return the same type.

What does "though they must return the same type" mean - aren't they auto generated?

---

https://github.com/vlang/v/blob/master/doc/docs.md#cross-platform-shell-scripts-in-v
> if files.len > 0 {

Seems redundant, the foreach loop wouldn't run with zero elements anyway

**Comment by JalonSolov** [comment]
> https://github.com/vlang/v/blob/master/doc/docs.md#strings Missing info on how to convert []byte back to string
> 
> _Found this through trial and error, not sure it it's the intended way:_
> 
> ```v
> b := 'abc'.bytes()
> s := string(b)
> ```

That's the simplest way, and yes it's intended.You are casting the array of bytes to a string.

> https://github.com/vlang/v/blob/master/doc/docs.md#fixed-size-arrays
> 
> > anums := fnums[0..fnums.len]
> 
> fnums[..] is much more compact, and works with anonymous variables (doesn't require a variable to get its .len). Not sure if this syntax is a bug, but it works with V 0.2.4 [5010d18](https://github.com/vlang/v/commit/5010d18f27e1ee2dc4cc82a5cab9ffca40d106d6).

The 2nd form is the shorthand for the first.  Both are correct.

> _Still works in V 0.2.4 [a006090](https://github.com/vlang/v/commit/a006090b0884c111e09f8321dc41b9aaa0a6d649)_
> 
> https://github.com/vlang/v/blob/master/doc/docs.md#fixed-size-arrays Missing info on how to convert a dynamic array to a fixed array
> 
> _Still haven't found a way to do it, maybe I should make a Feature Request? Fixed arrays are very hard to use without it._

Why?  Fixed arrays exist for a very specific purpose - to have a guaranteed space that won't get reallocated, and allocated on the stack for speed.  Unless you need those specific features, don't use them.

However, if you really need it, the only way to convert between them is with a for loop.
```v
f := [0, 1, 2]!
mut d := []int{}

for i in f {
        d << i
}

println('$f, $d')
```

> https://github.com/vlang/v/blob/master/doc/docs.md#type-checks-and-casts
> 
> > Mutable variables can change, and doing a cast would be unsafe
> 
> DOESN'T MAKE SENSE
> 
> _It's not explained why doing a cast would be unsafe, and it's not something obvious; I really don't know why it would be unsafe_

It does make sense.  It is talking about casting to a Sum Type, and casting to a Sum Type is unsafe, as a Sum Type could be any of the types, and you might be casting to the wrong one.  Or it may even have changed since you last looked at it.  If you're _sure_ you know what's going to happen, then you can mark it as mutable so the compiler knows not to squawk about it.

> https://github.com/vlang/v/blob/master/doc/docs.md#short-struct-literal-syntax
> 
> > you can omit the struct name when it's already known
> 
> But nothing is omitted
> 
> _Still can't figure out what was supposed to be omitted_

The comment is just in the wrong place.  It's talking about the `assert` statement just after the struct definition.  Instead of having to type
```v
assert Point.p.y == 4
```
you only need
```v
assert p.y == 4
```

> https://github.com/vlang/v/blob/master/doc/docs.md#mutable-arguments
> 
> > Use user.register() or user = register(user) instead of register(mut user).
> 
> Misleading into thinking that these are the ways the code above can be used

It is referring to the prior statement `It is preferable to return values instead of modifying arguments.`

I agree that it is somewhat confusing, since only the first statement will work with the given code.

> https://github.com/vlang/v/blob/master/doc/docs.md#manage-packages
> 
> > Read more:
> 
> Missing link
> 
> _I now see that it's not a missing link, but refers to "Briefly:" above. This should probably be removed/reworded._

Agreed.

> https://github.com/vlang/v/blob/master/doc/docs.md#module-options
> 
> > Or you can update all your modules:
> 
> No info about upgrade command, how it's different from update with no options

It is documented in the `v help` output.  There has been discussion about ways to include the `v help` output with the regular docs, but that hasn't happened, yet.
```
$ v help update
Usage:
  v update [MODULE]...
        Updates each MODULE.

        With no MODULE, ALL installed modules are updated to their latest versions.

Options:
  -help        - Show usage info.
  -v           - Print more details about the update.
  -server-url  - When doing network operations, use this vpm server. Can be given multiple times.

$
```
```
$ v help upgrade
Usage: v upgrade

Upgrade all outdated modules.

Options:
  -help        - Show usage info.
  -v           - Print more details about the upgrade.

$
```

> https://github.com/vlang/v/blob/master/doc/docs.md#publish-package It's strange that there's language info, then package management, then language info again. Consider relocating the "Modules" section.

Agreed.

> https://github.com/vlang/v/blob/master/doc/docs.md#interfaces Would be nice to have questionable design choices explained - no "implement" keyword seems like a bad design choice to me (wouldn't it be tedious to implement large interfaces when you have to manually remember all the fields you have to define?) If I knew why it was made, or maybe there was some counterpoint to what I thought, it would've made sense but without any of that people might tend to think that it's just objectively bad.

I'm not sure how an "implements" keyword would help.  You still need to create all the pieces yourself, so adding "implements" is superfluous.

> https://github.com/vlang/v/blob/master/doc/docs.md#channel-select
> 
> > `else` and `> timeout` are mutually exclusive
> 
> '>' is a typo or it's unclear what it means

Typo.

> https://github.com/vlang/v/blob/master/doc/docs.md#channel-select This is the first snipped I tried to compile and it failed with "library 'atomic' not found". I assumed it just wasn't implemented yet, but that would be nice to know beforehand, for example in the beginning of the docs.
> 
> _Two weeks later I discovered that it actually was implemented, but I had to install libatomic-devel. Which is a huge problem:_
> 
>     * _The language is very alpha, some features are not implemented now, but some of them are (or might be) in the docs._
> 
>     * _And it's advertised that V requires (or maybe will require?) no dependencies._
> 
>     * _And it fails with a very cryptic message (Invalid relocation entry '.rela.debug_info' @ 000004f6...)._
> 
>     * _So most people will probably think that the language is broken, that docs describe what the language wants to be and not what it is._
> 
>     * _And, thinking that all those awesome features are not real, they will likely leave._
> 
>     * _Which is especially sad because the language does have all these features._
> 
> 
> _Later I discovered that there were some other libs I had to install in order for V to work; I don't remember them now, but it's a good idea to have a list of things required for V to work at least with built-in features like channels._

Well, none of them are necessary for base V to work.  They are needed for specific modules or features to work.  Yes, some of it could be handled better, and there have been some changes to help let you know when you need to install something extra, but that hasn't been "back-ported" to all the code since it was added later.  V is still a work-in-progress.
 
> https://github.com/vlang/v/blob/master/doc/docs.md#memory-management
> 
> > Remaining small percentage of objects is freed via reference counting.
> 
> But on https://vlang.io it's said: "Remaining small percentage of objects is freed via GC".
> 
> _I don't know which one is correct so I can't fix it._

They are both correct, as reference counting can be considered as a type of GC.

> https://github.com/vlang/v/blob/master/doc/docs.md#structs-with-reference-fields
> 
> > for now data structures <...> understanding that it is unsafe
> 
> malformed sentence
> 
> _Also it's not explained why an unsafe operation is not wrapped in an unsafe{} block (maybe it should be?)._

As it says just about that, `Zero-value references, or nil pointers, will NOT be supported in the future`.  For now you can, and you don't have to wrap them in unsafe{}, but later you won't be able to use them at all.

> https://github.com/vlang/v/blob/master/doc/docs.md#embed_file
> 
> > Instead, it will be loaded the first time your program calls `f.data()` at runtime...
> 
> What is `f.data()`? The code snippet above doesn't have `f.data()`, nor there are any explanations later in the docs.

Yeah, that needs to be fixed.  It should be `embedded_file.data()` to match the example code.

> https://github.com/vlang/v/blob/master/doc/docs.md#compile-time-reflection Not clear whether get_string and get_int are built-in functions or example functions. Add something along the lines of
> 
> ```v
> fn get_string(data string, field_name string) string {
>     // ...
> }
> fn get_int(data string, field_name string) string {
>     // ...
> }
> ```
> 
> _There are probably no global built-in functions in V (except `println()`, etc.), but a newcomer wouldn't know that._

As it says at the top of that example:
```v
// TODO: not fully implemented
```
There are quite a few builtin functions - look at [modules.vlang.io](https://modules.vlang.io) under `builtin`.

However, you are correct - they aren't global - they're in the builtin module.  It is simply auto-imported for every V program.

> https://github.com/vlang/v/blob/master/doc/docs.md#limited-operator-overloading
> 
> > Assignment operators <...> are auto generated <...> though they must return the same type.
> 
> What does "though they must return the same type" mean - aren't they auto generated?

If you write
```v
a := int(1)
b := f64(3.5)
```
then `a += b` won't work, since `a` and `b` aren't the same type.

It only autogenerates the overloads for things that are the same type.

> https://github.com/vlang/v/blob/master/doc/docs.md#cross-platform-shell-scripts-in-v
> 
> > if files.len > 0 {
> 
> Seems redundant, the foreach loop wouldn't run with zero elements anyway

It's a commented out example, but it is also a safeguard against `files` not having any elements... no reason to even try the `for` loop, then.

**Comment by JalonSolov** [comment]
That is often the case, and has lead to some rather heated debates.

It all comes down to the program cleaning up unused bits & bobs at runtime, no matter how that is achieved.

If it didn't have _something_ like this, you would have to manually add `free()` calls, and nobody really wants to do that.

**Comment by JalonSolov** [comment]
> > In other words, v update will (try to) update all modules if you don't list any, but if you do list some, only those will be updated. It allows you to pick & choose exactly which modules you want updated, in case you want to keep the current version of one while updating others.
> > v upgrade doesn't take any options, so it will always do all of them.
> > Subtle, perhaps, but a very real difference.
> 
> It's clear that `update` behaves differently with arguments. But `upgrade` can only be used without arguments, and it behaves exactly like `update` without arguments. So it looks like `upgrade` is redundant.
> 
> Looking at cmd/tools/vpm.v, `upgrade` calls `update(get_outdated())`, while `update` uses `get_installed_modules()` when passed no arguments. Is there any difference between "updating all modules" vs "updating all modules that can be updated"?

Yes.  `v update` with no parameters will try to update every module you have installed, whether it is already up-to-date or not.  `v upgrade` will only try to update it if what you have isn't up-to-date.
