### ISSUE TITLE
V's binary tree example - how to change a sumtype variable without mut (like Empty -> Node)

### ISSUE THREAD

**Issue by paulocoghi** [vlang/v#12230]
On V's [binary tree example](https://github.com/vlang/v/blob/master/doc/docs.md#sum-types), we have:

```v
// V's binary tree
struct Empty {}

struct Node {
	value f64
	left  Tree
	right Tree
}

type Tree = Empty | Node
```

Is it possible to update a `left`or `right` Tree property on Node structure from `Empty` to `Node`, without using `mut`?

```v
fn main() {
	root := Node{4, Empty{}, Empty{}}

	// How to avoid this assignment? (since this is only valid over a mutable variable)
	root.left = Node{2, Empty{}, Empty{}}
}
```

Or, in other words, how can I manipulate a B Tree like the one provided on the example, like adding news elements, without having to resort to mutable variables.

**Comment by nyx-litenite** [comment]
If you only want to assign the left node, you would do: 
```v
root := Node{4, Node{2, Empty{}, Empty{}}, Empty{}}
```

Now you'll have a tree that you can read from w/ a root node and a left node, but you can't update it in the future.
