### ISSUE TITLE
Method call with propagation in defer block results in segfault

### ISSUE THREAD

**Issue by lemoncmd** [vlang/v#12253]
**V version:** 
**OS:** 

**What did you do?**
```v
struct Foo {}

fn (f Foo) test1() ? {
	return
}

fn test2() ? {
	defer {
		Foo{}.test1() ?
	}
}
```

**What did you expect to see?**
Proper V Error
```
defer.v:9:17: error: error propagation not allowed inside `defer` blocks
    7 | fn test2() ? {
    8 |     defer {
    9 |         Foo{}.test1() ?
      |                       ^
   10 |     }
   11 | }
```

**What did you see instead?**
Segmentation Fault

This issue occurs because of this difference between normal call and method call.
https://github.com/vlang/v/blob/ff02c198277ef73a0479506e83537ce43d0e0665/vlib/v/parser/parser.v#L2463-L2467
https://github.com/vlang/v/blob/ff02c198277ef73a0479506e83537ce43d0e0665/vlib/v/parser/fn.v#L81-L88
Method call lacks propagation check when in defer block. Maybe this work is needed to deal with this kind of bugs.
https://github.com/vlang/v/blob/ff02c198277ef73a0479506e83537ce43d0e0665/vlib/v/parser/parser.v#L2423

**Comment by medvednikov** [comment]
Fixed.
