### ISSUE TITLE
Wrap one C.free, don't call C.free every where

### ISSUE THREAD

**Issue by kitech** [vlang/v#1229]
I understand as @medvednikov mentioned, there will be a memory management soon.
But now let make it usable in real project, I want hook malloc/free to gced malloc/free, but don't want change too much.

**Comment by medvednikov** [comment]
Do you mean not allowing to call `C.free()` but only builtin `free()`?

**Comment by justicesuh** [comment]
@kitech There is a `free` method
https://github.com/vlang/v/blob/d6ddfa124d62d44c1c9e700560cf399212c306f4/vlib/builtin/builtin.v#L92-L94

**Comment by kitech** [comment]
Nice there is one wrap free function.
It nice if other where use this, like places:
https://github.com/vlang/v/blob/d47e2f113fb419e8a4309364d4c53e34f26045ed/vlib/strings/builder.v#L41
https://github.com/vlang/v/blob/b17df207f2cb87981aacb86fb571e7a81d1e6be4/vlib/builtin/array.v#L219

**Comment by medvednikov** [comment]
This was fixed, `C.free()` is no longer allowed. `free()` must be used instead.
