### ISSUE TITLE
how install vlang

### ISSUE THREAD

**Issue by Ultraman95** [vlang/v#123]
where vlang source not examples

**Comment by di3663** [comment]
看下官网,现在捐赠者才有资格,每月30美刀

**Comment by xdray** [comment]
感觉东西很吊，但是不知道实际怎么样。特别是Hot Code Reloading，那个视频里能实时改方块的颜色,吊

**Comment by di3663** [comment]
https://vlang.io/play 这里可以试用,以实物为准,单看介绍是可以秒天秒地.

**Comment by di3663** [comment]
建议关闭issue

**Comment by wenj91** [comment]
不是很看好这个语言

**Comment by Ultraman95** [comment]
每月30刀，看来是牛逼语言

**Comment by Ultraman95** [comment]
目前有点用不起

**Comment by pengshaomin** [comment]
是哪位大佬主导？

**Comment by medvednikov** [comment]
Hi,

Right now you can only use V in the playground.

It will be open sourced in June.

The lag in the hot code reloading you mentioned is an old bug, it was fixed. I need to update the demo.
