### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by andymans** [vlang/v#12339]
Would someone mind adding a section to the docs called "Building your Project" - including the build flags and what the trade-offs are in getting to a tiny executable.

Currently a Hello World in v builds a 340KB executable on Mac OSX. Obviously that should be 50KB absolute maximum; but I don't see any instructions for build, excluding the help (which is not too readable).

**Comment by changrui** [comment]
`v help build`.

**Comment by andymans** [comment]
Hmmm K.
