### ISSUE TITLE
Compilation fails when a u64 map is returned from a function

### ISSUE THREAD

**Issue by l4zy0n3** [vlang/v#1235]
**V version: 0.1.15** 
**OS: Windows** 

**What did you do?**
```
fn return_map( n int) map[string]u64 {
    mut m := map[string]u64{}
    m['n'] = u64(n)
    return m
}

fn main(){
    mut n := return_map( 3)
    println( n['n'])
}
```

**What did you expect to see?**
3
 
**What did you see instead?**
```
..\test1.c: In function 'main':
..\test1.c:3171:12: error: empty scalar initializer
 u64 tmp4 = {}; bool tmp5 = map_get( n , tos2("n"), & tmp4);
            ^
..\test1.c:3171:12: note: (near initialization for 'tmp4')
V panic: clang error
```

**Comment by medvednikov** [comment]
It works for, I just checked the code, it really should work.

Try

```
git pull 
make
```

**Comment by l4zy0n3** [comment]
> It works for me, I just checked the code, it really should work.
> 
> Try
> 
> ```
> git pull 
> make
> ```

I even tried compiling this with a fresh clone of the repo
Still facing the same issue

**Comment by justicesuh** [comment]
@medvednikov can confirm that it doesn't compile on windows

**Comment by M4SSD35TRUCT10N** [comment]
Just compiled under Window 10 1809 with current master.
`mut n := return_map( 3)` gives an compile error because n is never changed. That's okay. Changing this line according to docs/compiler to `n := return_map( 3)` prints out **3**, which the desired result.
