### ISSUE TITLE
Option error when return is pointer

### ISSUE THREAD

**Issue by justicesuh** [vlang/v#1238]
**V version:** 0.1.15
**OS:** Debian

**What did you do?**

Trying to add error handling as explained in #1091 

```
pub fn (s Socket) recv(bufsize int) ?byteptr {
	buf := malloc(bufsize)
	res := C.recv(s.sockfd, buf, bufsize, 0)
	if res < 0 {
		return error('socket: recv failed')
	}
	return buf
}
```

**What did you expect to see?**

Should compile, as the function is either returning `error` or a `byteptr` (from the `malloc`)
 
**What did you see instead?**

expected type `Option_byteptr`, but got `byte`

**Comment by avitkauskas** [comment]
Try `return byteptr(buf)`.

**Comment by justicesuh** [comment]
Late reply, but the explicit cast didn't work

**Comment by emily33901** [comment]
As far as i can tell (adding this to the socket file and running `v test vlib/net`) this compiles now
