### ISSUE TITLE
Undefined reference in Termux

### ISSUE THREAD

**Issue by FedericoLeiva12** [vlang/v#1239]
**OS:** Android 8.1.0 Samsung J7 2016

**What did you do?**
git clone https://github.com/vlang/v
cd v
git pull
make

**What did you expect to see?**
rm -f v.c .v.c v vprod thirdparty/**/*.o
curl -Os https://raw.githubusercontent.com/vlang/vc/master/v.c
cc -std=gnu11 -w -o v v.c -lm
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: /data/data/com.termux/files/usr/tmp/v-41b5dc.o: in function `Table_cgen_name':
v.c:(.text+0xdc9c): undefined reference to `__atomic_load'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: v.c:(.text+0xdce0): undefined reference to `__atomic_load'
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:15: v.c] Error 1

**Comment by ciubotaru** [comment]
Looks same as https://github.com/vlang/v/issues/872.

**Comment by medvednikov** [comment]
Can you try with `cc -march=native ...` ?

**Comment by ciubotaru** [comment]
Termux on Android 5.1 / aarch64 here. I can not reproduce this issue. On the other hand, V compilation fails if I add '-march=native'.

**Comment by medvednikov** [comment]
I don't have much experience with Android. It is it possible to run gcc on it without Termux?

**Comment by ciubotaru** [comment]
AFAIK, there is no builtin terminal in Android, so no command line and no straight way to run CLI applications.

**Comment by FedericoLeiva12** [comment]
> Can you try with `cc -march=native ...` ?

This work, thanks you!

**Comment by gomisc** [comment]
Not compiled yet
