### ISSUE TITLE
'sumtype's inside 'match' statements must be explicitly cast, opposite to what is in the docs.

### ISSUE THREAD

**Issue by maa83** [vlang/v#12394]
**V version:** V 0.2.4
**OS:** Windows 10

**What did you do?**
tried 'match' combination with a sumtype

```
struct Success<T> {
	pub: val T
}

struct Failure {
	pub: msg string
}

type Result<T> = Success<T> | Failure

fn test_func(success bool) Result<f64> {
	if success {
		return Success<f64>{ val: f64(64) }
	}
	else {
		return Failure{ msg: 'lol, failed' }
	}
}

fn main() {
	mut result := test_func(true)
	match result {
		Success<f64> {
			println("Success, Value: $result.val")
		}
		Failure {
			println("Failure, Message: $result.msg")
		}
	}

	result = test_func(true)
	match result {
		Success<f64> {
			success := result as Success<f64>
			println("Success, Value: $success.val")
		}
		Failure {
			fail := result as Failure
			println("Failure, Message: $fail.msg")
		}
	}
}
```

**What did you expect to see?**
That the first scenario works, as good as the second scenario, as also described in the [documentation](https://github.com/vlang/v/blob/master/doc/docs.md#sum-types).
the linked example shows that a field can be accessed without explicit casting, while I don't mind having to cast explicitly, this makes the documentation incorrect.

also, it would be great to have the possibility to cast inside the match statement:
something like:

```
match test_func(true) {
	Success<f64> success {
		println("Success, Value: $success.val")
	}
	Failure fail {
		println("Failure, Message: $fail.msg")
	}
}
```
 
**What did you see instead?**
The first scenario causes a compile error:

![image](https://user-images.githubusercontent.com/9629685/140586392-baa0e96e-fb86-493f-aa4c-ae10b28f4b2b.png)

**Comment by yuyi98** [comment]
It should use `match mut result {` when result is `mut` access mode.
