### ISSUE TITLE
No error message or warning when defining a filter() method on a struct

### ISSUE THREAD

**Issue by jdonnerstag** [vlang/v#12397]
**V version:**  V 0.2.4 52df19e
**OS:**  windows, Microsoft Windows 10 Enterprise v19042 64-bit

**What did you do?**
Create a struct and define a filter() method 

```
struct Xyz {  a int  }

fn (x Xyz) filter(p int) int { .. }
```

**What did you expect to see?**
Either: That the compiler is successful and uses my filter function. Or an error message saying that V predefined filter() method can not be overriden.
 
**What did you see instead?**
V compiler succeeded, but TCC was not able to compile the generated C code. Which basically means: no hint whatsoever, on the underlying issue.  Only when looking at the C code and realising that it is absolutely not what I expected, I eventually guessed the problem.

**Comment by medvednikov** [comment]
The code compiles. `filter()` is defined only on arrays/maps.
