### ISSUE TITLE
Modulus by zero always return 1

### ISSUE THREAD

**Issue by MaxGraey** [vlang/v#124]
```go
fn main() {
	println(100 % 0)
}
```
Output: 1
Expected: division by zero

Why you not fixed this in same time as #117 ?

**Comment by medvednikov** [comment]
> Why you not fixed this in same time as #117 ?

What's wrong with your attitude?

**Comment by MaxGraey** [comment]
If I had positioned my compiler as an educational or pet project then my attitude would be different but you positioned your project as commercial (fremium) and very ambiguous but you don’t pay proper attention to the details, which is very regrettable.

I will not continue the discussion in this vein, everything has already been said here: https://github.com/vlang/v/issues/35

**Comment by ntrel** [comment]
I don't think it's a commercial project. Even with commercial projects, the user is not guaranteed that their bug will even get fixed. Alex is just funding the development by donations, and generously plans to release the language as open source.

**Comment by MaxGraey** [comment]
@ntrel Early access only for sponsors is not commercial?

**Comment by medvednikov** [comment]
The language is free, and will be open sourced in June. If you want to support the development, you can do it on Patreon. One of the supporters suggested adding early access option, and I did.

Your childish attitude in multiple topics is not welcome. Clearly you don't like the language as you stated multiple times, I have no no idea why you waste your time here.

**Comment by ntrel** [comment]
More of an incentive for donors. I don't consider it commercial because (IMO) the project requires more work until it's ready and stable. It's a lot of work, living costs are expensive.

**Comment by MaxGraey** [comment]
> I have no no idea why you waste your time here

If you do not like issues that I find out of pure curiosity, I can stop my research. You don't seem to take criticism very well.

**Comment by medvednikov** [comment]
I take criticism very well.

But when you name your issues "[bug] (again!)" or write "Why you not fixed this?", I have a problem with that.

**Comment by MaxGraey** [comment]
Yes, because most issues is very simple and I wonder how with all of that you have self-hosted compiler and compile doom3 properly. For me it is a very big mystery

**Comment by medvednikov** [comment]
I will publish it this month.

Not catching division by zero does not prevent writing a compiler.
