### ISSUE TITLE
Compiler Bug With Uninitialized Generic Struct Fields

### ISSUE THREAD

**Issue by nelsam** [vlang/v#12400]
**V doctor:**
```
OS: linux, "Gentoo Base System release 2.8"
Processor: 128 cpus, 64bit, little endian, AMD Ryzen Threadripper 3990X 64-Core Processor
CC version: cc (Gentoo 11.2.0 p1) 11.2.0

getwd: /home/valczir/dev/vipar
vmodules: /home/valczir/.vmodules
vroot: /home/valczir/.local/share/v
vexe: /home/valczir/.local/share/v/v
vexe mtime: 2021-11-06 16:05:16
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 8be64ef

Git version: git version 2.33.1
Git vroot status: weekly.2021.44-24-g8be64ef8
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 333c14de

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg default_slice_field.v`
```v
struct Foo<T> {
	foo T
}

struct Bar<T> {
mut:
	foos []Foo<T>
}

fn (mut b Bar<T>) add(v T) {
	b.foos << Foo<T>{
		foo: v
	}
}

fn main() {
	mut bar := Bar<string>{}
	bar.add('bar')
	println(bar)
}

```

**What did you expect to see?**

~A compile-time error telling me that `Bar<string>` cannot be constructed without a value for the `foos` field.  This seems like the most consistent way to deal with the issue, since variables in v can't be initialized without a value - it would make sense to me if the same restriction applied to struct fields.~

^^^ Never mind that, I found the previous discussions about default values on struct fields.

Either the default value for  a slice should be appendable (as in `go`), or I should get a stack trace showing that `foos` was not initialized and cannot be appended to.

**What did you see instead?**
```
==================
/tmp/valczir/v/default_slice_field.1573690348668029940.tmp.c:828: error: ';' expected (got "<")
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

**Comment by nelsam** [comment]
Note: an eerily similar error happens if the slice is initialized in a constructor.  This works:

```v
struct Foo<T> {
	foo T
}

struct Bar<T> {
mut:
	foos []Foo<T>
}

fn (mut b Bar<T>) add(v T) {
	b.foos << Foo<T>{
		foo: v
	}
}

fn main() {
	mut bar := Bar<string>{
		foos: []Foo<string>{}
	}
	bar.add('bar')
	println(bar)
}
```

But when we move the initialization from `main` (where we know the type) to `new` (where we're referencing a generic type), we get the compiler bug again:

```v
struct Foo<T> {
	foo T
}

struct Bar<T> {
mut:
	foos []Foo<T>
}

fn new<T>() Bar<T> {
	return Bar<T>{
		foos: []Foo<T>{}
	}
}

fn (mut b Bar<T>) add(v T) {
	b.foos << Foo<T>{
		foo: v
	}
}

fn main() {
	mut bar := new<string>()
	bar.add('bar')
	println(bar)
}
```

**Comment by DevrosTheOne** [comment]
Could not get it to duplicate the problem when I retyped the code.   

Finally worked out that during testing I created Bar directly with ```mut bar2 := Bar<string>{ []Foo<string>{} }```.   
With this line the program compiles and no issues with creating ```Bar<string>``` using ```new<string>()``` or adding items with ```add()``` function.

Now ```new<string>()``` returns a ```Bar<string>``` but does not work for ```Bar<int>```.  
Need to do an explicit initialisation of the struct ```mut bint1 := Bar<int>{ []Foo<int>{} }``` to able to do a ```mut bint2 := new<int>( )```.
Somehow a successful initialisation changes how ```new<T>()``` works.   

```v
fn main() {
	mut bar := new<string>()
	mut bar2 := Bar<string>{ []Foo<string>{} }  // no errors if this line in code ????
	bar.add('bar')
	println(bar)
}
```
output
```
Bar<string>{
    foos: [Foo<string>{
        foo: 'bar'
    }]
}
```

**Comment by DevrosTheOne** [comment]
Strange thing is that if you create a ```Bar<string>``` in a constructor using ```mut temp := Bar<string>{ foos: []Foo<string>{} }``` the ```new<string>( )``` function complies and returns a ```Bar<string>``` when called.  

You need to have to have a successful instance created before ```new<T>( )``` can create a new instance of that ```<T>```?  

??????? 😖 

```v
fn main() {
	mut temp := Bar<string>{ foos: []Foo<string>{} }
	mut bar := new<string>()  // happy to create a Bar<string> now ???
	bar.add('bar')
	println(bar)
}
```
