### ISSUE TITLE
Calling `os.walk_ext` causes `V repl error: Unhandled Exception 0xC00000FD`

### ISSUE THREAD

**Issue by dumprop** [vlang/v#12412]
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 758c18a
**OS:** windows 11

**What did you do?**
```
>>> import os
>>> os.walk_ext(os.getwd(),'')
V repl error: Unhandled Exception 0xC00000FD
```

**What did you expect to see?**
File in directory
 
**What did you see instead?**
V repl error: Unhandled Exception 0xC00000FD

On small dirs all works well, on large dirs as `C:\WINDOWS\system32` it causes that problem

**Comment by JalonSolov** [comment]
You are exhausting the stack.  That's what that particular error means.

**Comment by ShiJunY** [comment]
I have the same problem

**Comment by medvednikov** [comment]
Works fine with 200k files.
