### ISSUE TITLE
Make sqlite constants public

### ISSUE THREAD

**Issue by khalyomede** [vlang/v#12459]
It would be useful for me to check for error codes using these existing constants instead of creating mine again.

https://github.com/vlang/v/blob/master/vlib/sqlite/sqlite.v#L17-L22

**Comment by kahsa** [comment]
Instead, it is more convenient to use e.g enum, and make it the return value of db.exec().

**Comment by khalyomede** [comment]
I did not fought of enums, but I like the idea!

**Comment by spytheman** [comment]
PRs are welcome :-)

**Comment by khalyomede** [comment]
Can someone reference the PR  https://github.com/vlang/v/pull/12485 please? Before closing this issue

**Comment by medvednikov** [comment]
fixed in #12485
