### ISSUE TITLE
Can call pop() on non-mutable array

### ISSUE THREAD

**Issue by Sidewinder1138** [vlang/v#12456]
v doctor output:
```
OS: windows, Microsoft Windows 10 Pro v19043 64-bit
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: cc --version

getwd: C:\Users\ander\work\learnv
vmodules: C:\Users\ander\.vmodules
vroot: C:\dev\v
vexe: C:\dev\v\v.exe
vexe mtime: 2021-11-13 22:20:22
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 08667c5.61b99e1

Git version: git version 2.33.0.windows.2
Git vroot status: weekly.2021.45-32-g61b99e19
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 0f5168cd
```

**What did you do?**
I ran this code with `v run main.v`:
```
a := [1,2,3]
dump(a)

a.pop()
dump(a)
```

**What did you expect to see?**
An error on `a.pop()` since array `a` is not mutable. 

 
**What did you see instead?**
No error, code code ran with this output:
```
[main.v:3] a: [1, 2, 3]
[main.v:6] a: [1, 2]
```

I tried doing a.insert() for example, and I get the error I would expect: ```error: `a` is immutable, declare it with `mut` to make it mutable```

It's possible I'm just confused, but I was expecting pop() to fail on a non-mutable array...

**Comment by Wertzui123** [comment]
Technically, it is possible to pop a fixed-size array (it just wastes memory).
But I think this shouldn't be allowed.
