### ISSUE TITLE
cgen error: generics error

### ISSUE THREAD

**Issue by barrack-obama** [vlang/v#12461]
**V version:** 
**OS:** 

**What did you do?**
```v
fn print_field_values<T>(s &T) {	
	$for field in T.fields {
		println(typeof(s.$(field.name)).name)
		// x := s.$(field.name) -> this just gives a c error, as the c generatored code becomes: main__Foo x = s->{field_name};
	}
}

fn main() {
	bar := Foo{
		name: "Simon"
		password: "simon1234"
		email: "simon@gmail.com"
		age: 15
	}
	print_field_values<Foo>(bar)
}
```

**What did you expect to see?**
```
string
string
string
int
```
 
**What did you see instead?**
```
Foo
Foo
Foo
Foo
```

**Comment by barrack-obama** [comment]
@yuyi98, maybe you have an idea, where this could be fixed?

**Comment by yuyi98** [comment]
@barrack-obama  Thanks!
The return value type of s. $(field.name) could not be set properly during the Checker phase, so generating code has its own set of problems, I'll fix them.

**Comment by changrui** [comment]
`typeof(field).name` for field type.
