### ISSUE TITLE
system font problemia in Ubuntu localize setups

### ISSUE THREAD

**Issue by GaraSharp** [vlang/v#12476]
Dear sir .

In some Ubuntu localize setup case causes that 'fc-match -v' returns truetype collections font. like as ;
```
$ fc-match
NotoSansCJK-Regular.ttc: "Noto Sans CJK JP" "Regular"
```

and V language does not handle with truetype collection font currently, so, font configuration will success but no typo is displayed .

to avoid this issue, there might these way, I think.

1. use VUI_FONT env var set in User environments
2. V language handles with truetype collection font
3. patch v/vlib/gg/text_rendering.v as ;

```
$ diff v/vlib/gg/text_rendering_b4.v v/vlib/gg/text_rendering.v 
79c79
< 	mut fm := os.execute('fc-match -v')
---
> 	mut fm := os.execute('fc-match -s -v')
83c83
< 			if l.contains('file:') {
---
> 			if l.contains('file:')  && l.contains('.ttf') {
```

thanks !

**Comment by kahsa** [comment]
1) `gg` can handle `.otf` too.
2) we can set `gg.Context.font_path = '/path/to/font_file'`.

So, may be better eliminating `.ttc` from candidates instead.

**Comment by medvednikov** [comment]
Should be fixed @GaraSharp 

Try again please.
