### ISSUE TITLE
Consts are occassionally inserted in the wrong order in the C code

### ISSUE THREAD

**Issue by jdonnerstag** [vlang/v#12497]
**V version:** V 0.2.4 52df19e
**OS:** windows, Microsoft Windows 10 Enterprise v19042 64-bit

**What did you do?**
This is mainly to record the issue. Spytheman may already have fixed it. See the Discord thread https://discord.com/channels/592103645835821068/592294828432424960/910216785960243232 for the details

It requires 2 files !! It works correctly if everything is copied in 1 file. (and I'm on Win10 with tcc)
mytest/mine.v
```
module mytest

$if linux {
    #include "limits.h"
}

pub const uchar_max = C.UCHAR_MAX
```

mytest/v_test.v
```
module mytest

const bits_per_char = 8
const xyz = ((uchar_max / bits_per_char) + 1) // == 32

fn test_knowns() ? {
    assert bits_per_char == 8
    assert uchar_max == 255
    assert xyz == 32
}
```

![grafik](https://user-images.githubusercontent.com/366871/142262228-d2b73924-a8c2-4fbe-9518-7d1e6552ac51.png)

**What did you expect to see?**

 
**What did you see instead?**

**Comment by medvednikov** [comment]
Fixed.
