### ISSUE TITLE
1f029978 : at ???: RUNTIME ERROR: invalid memory access

### ISSUE THREAD

**Issue by nezu-lab** [vlang/v#12528]
**V version: V 0.2.4 82010e7** 
**OS: Debian 10**

**What did you do?**
when i run "sudo ./v symlink" after running make throws this error, also when i run a .v file in examples dir

**What did you expect to see?**
commands would work properly
 
**What did you see instead?**
Terminal throws thid error:

`1f029978 : at ???: RUNTIME ERROR: invalid memory access
/tmp/v_0/../../../../../../tmp/v_0/vsymlink.11876674414196296418.tmp.c:17171: by _vinit
/tmp/v_0/../../../../../../tmp/v_0/vsymlink.11876674414196296418.tmp.c:17184: by main`

**Comment by Ev1lT3rm1nal** [comment]
Maybe try to download the latest release again, sometimes this happens, it's not stable yet

**Comment by nezu-lab** [comment]
> Maybe try to download the latest release again, sometimes this happens, it's not stable yet

I reinstalled it and throws the same error

**Comment by Dialga** [comment]
Try running with `-v`.

**Comment by nezu-lab** [comment]
> Try running with `-v`.

`root@localhost:/home/nezu/v# ./v symlink -v
launch_tool vexe        : /home/nezu/v
launch_tool vroot       : /home/nezu/v
launch_tool tool_source : /home/nezu/v/cmd/tools/vsymlink.v
launch_tool tool_exe    : /home/nezu/v/cmd/tools/vsymlink
launch_tool tool_args   : symlink -v
launch_tool should_compile: false
1f029978 : at ???: RUNTIME ERROR: invalid memory access
/tmp/v_0/../../../../../../tmp/v_0/vsymlink.11378136071375486943.tmp.c:17171: by _vinit
/tmp/v_0/../../../../../../tmp/v_0/vsymlink.11378136071375486943.tmp.c:17184: by main`

**Comment by dumblob** [comment]
Could you please try with `valgrind -v ...`? This is a very strange issue.
