### ISSUE TITLE
Passing function into the closure as an inherited variable causes builder error

### ISSUE THREAD

**Issue by hamletin** [vlang/v#12532]
**V version:** 
V 0.2.4 243e66a, timestamp: 2021-11-20 21:28:11 +0200

**OS:** 
OS: linux, "Manjaro Linux"
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 5800X 8-Core Processor
CC version: cc (GCC) 11.1.0

**What did you do?**
```
type Func = fn(a int) int

fn foo(f Func, x int) {
	fn [f] (y int) {
		println("result: ${f(y)}")
	}(x)
}

fn main() {
	t := fn(a int) int { return a+1 }
	foo(Func(t), 10)
}
```

**What did you expect to see?**
`result: 11`
 
**What did you see instead?**
```
/tmp/v_1000/main.9171615395177553806.tmp.c:1921: warning: implicit declaration of function 'f'
/tmp/v_1000/main.9171615395177553806.tmp.c:10754: error: function pointer expected
builder error: 
==================
C error. This should never happen.
```

**Comment by felipensp** [comment]
Already fixed on newer V version.
