### ISSUE TITLE
Missing defer

### ISSUE THREAD

**Issue by d2verb** [vlang/v#1253]
**V version:** V 0.1.15
**OS:** Xubuntu 18.04 LTS

**What did you do?**
compile following code and execute it
```go
fn main() {
	defer { println('1') }
	defer { println('2') }
	defer { println('3') }
}
```

**What did you expect to see?**
```
3
2
1
```
 
**What did you see instead?**
```
3
```

**Comment by medvednikov** [comment]
Thoughts on allowing only one defer?

When are multiple defers necessary?

**Comment by d2verb** [comment]
How about this sample
(I know there is no read_lines() method for File, but this is just a sample ignore it.)
```go
fn main() {
	flist := open('./file_list.txt') or {
		return error('error')
	}
	defer { flist.close() }

	for fname in file.read_lines() {
		file := open(fname) or {
			return error('error')
		}
		defer { file.close() }

		// do something
	}
	
}
```

**Comment by medvednikov** [comment]
How about calling `defer` at the end of a block, not at the end of a function?

**Comment by d2verb** [comment]
@medvednikov programmer will write multiple `defer`s in a block. So just moving `defer` call from the end of function to the end of a block can't handle this issue.

**Comment by medvednikov** [comment]
Well they won't if it's not allowed :)

Is there a use case for multiple defers in a single block?

**Comment by d2verb** [comment]
@medvednikov 
just open 2 files
```go
fn main() {
	f1 := os.open('./file1.txt') or {
		return error('error')
	}
	defer { f1.close() }

	f2 := os.open('./file2.txt') or {
		return error('error')
	}
	defer { f2.close() }
}
```

**Comment by medvednikov** [comment]
Ok, good point.

It's a quick fix, will push within an hour.

**Comment by Rendims** [comment]
I agree that multiple defers should be allowed. Reading from one file and writing to another seems like a common pattern.
And like defer in Go execute them in reverse order, closing f2 first and then f1.

**Comment by medvednikov** [comment]
Fixed.
