### ISSUE TITLE
Large amount of constant declarations drastically increases compilation time (specifically CHECK stage) 

### ISSUE THREAD

**Issue by hamletina** [vlang/v#12544]
**V version:** 
V 0.2.4 243e66a, timestamp: 2021-11-20 21:28:11 +0200

**OS:** 
OS: linux, "Manjaro Linux"
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 5800X 8-Core Processor
CC version: cc (GCC) 11.1.0

**What did you do?**
```
type GLFlag = int
pub const (
	gl_depth_buffer_bit    = GLFlag(C.GL_DEPTH_BUFFER_BIT)
	gl_stencil_buffer_bit  = GLFlag(C.GL_STENCIL_BUFFER_BIT)
	gl_color_buffer_bit    = GLFlag(C.GL_COLOR_BUFFER_BIT)
	gl_false               = GLFlag(C.GL_FALSE)
	gl_true                = GLFlag(C.GL_TRUE)
	// ... (~2000 constants total)
)
```
Executing with: `v -stats -show-timings main.v`

**What did you expect to see?**
Resonable compilation time
 
**What did you see instead?**

> 21.793   ms Builder.front_stages.parse_files
> 0.097    ms Builder.resolve_deps
> 34.391   ms Builder.parse_imports
> 12.472   ms SCAN
> 38.002   ms PARSE
> 0.001    ms Checker.generic_insts_to_concrete
> **25262.672 ms CHECK**
> 1.527    ms TRANSFORM
> 0.031    ms Table.complete_interface_check
> 0.516    ms Gen.sort_structs
> 0.122    ms Gen.write_init_function
> 11.385   ms C GEN
> 45.911   ms C tcc.exe
> 
> V  source  code size:      15617 lines,     549792 bytes
> generated  target  code size:      15887 lines,     654400 bytes
> compilation took: **25379.459 ms**, compilation speed: **615 vlines/s**

Reducing amout of constants by one order (~200) leads to significantly better compilation times:
> 21.701   ms Builder.front_stages.parse_files
> 0.086    ms Builder.resolve_deps
> 26.544   ms Builder.parse_imports
> 10.456   ms SCAN
> 32.299   ms PARSE
> 0.001    ms Checker.generic_insts_to_concrete
> 27.072   ms CHECK
> 1.455    ms TRANSFORM
> 0.029    ms Table.complete_interface_check
> 0.478    ms Gen.sort_structs
> 0.049    ms Gen.write_init_function
> 7.250    ms C GEN
> 41.978   ms C tcc.exe
> 
> V  source  code size:      15617 lines,     555195 bytes
> generated  target  code size:      12285 lines,     425871 bytes
> compilation took: 127.481 ms, compilation speed: 122504 vlines/s

**Comment by JalonSolov** [comment]
Since you didn't supply an example to test with, I wrote a small program to generate a test file:
```v
import os
import strings

mut str := strings.new_builder(8192)
str.writeln('pub const (')

for i in 0..2000 {
        str.writeln('\tv${i:04d} = $i')
}
str.writeln(')')

os.write_file('lotsa_consts.v', str.str())?
```
Compiling the generated file with the same options you used shows a similar result:
```
[jamie@5950x ~]$ v -stats -show-timings lotsa_consts.v
21.583   ms Builder.front_stages.parse_files
0.053    ms Builder.resolve_deps
18.406   ms Builder.parse_imports
9.642    ms SCAN
29.022   ms PARSE
0.001    ms Checker.generic_insts_to_concrete
21176.606 ms CHECK
1.418    ms TRANSFORM
0.025    ms Table.complete_interface_check
0.339    ms Gen.sort_structs
0.052    ms Gen.write_init_function
8.082    ms C GEN
14.542   ms C tcc.exe
        V  source  code size:      14680 lines,     372589 bytes
generated  target  code size:      13038 lines,     440528 bytes
compilation took: 21241.933 ms, compilation speed: 691 vlines/s
[jamie@5950x ~]$
```

**Comment by medvednikov** [comment]
Should be fixed
```
0.084    ms Builder.resolve_deps
22.186   ms Builder.parse_imports
13.129   ms SCAN
36.785   ms PARSE
0.001    ms Checker.generic_insts_to_concrete
28.041   ms CHECK
0.984    ms TRANSFORM
0.017    ms Table.complete_interface_check
0.342    ms Gen.sort_structs
0.022    ms Gen.write_init_function
7.815    ms C GEN
```
