### ISSUE TITLE
slice() Array out of bounds

### ISSUE THREAD

**Issue by shanghuo** [vlang/v#1254]
**V version: 0.1.15** 
**OS: android** 

**What did you do?**
I tried to write a Chinese reference manual (v-ref.com), so I found the following code may have an array out of bounds vulnerability.

```
fn main(){
    arr := [5,4,3,2,1]
    res := arr.slice(-4,3)
    println(res)
}
```

**What did you expect to see?**

Output `[4,3,2]`, or `error: the parameter needs to be positive`
 
**What did you see instead?**

```
[2059570112, 126, 2059580160, 126, 5, 4, 3]
```

Specific error information, you can refer to [https://v-ref.com/v-ref/builtin.html](https://v-ref.com/v-ref/builtin.html) . I write there in Chinese.

(English is not my native language; please excuse typing errors. And if you speak Chinese, please email/PM me; I may need assistance translating my question.)

**Comment by medvednikov** [comment]
Fixed:

```
V panic: runtime error: slice bounds out of range (-4 < 0)
```
