### ISSUE TITLE
Defer in block can't touch variables in same block

### ISSUE THREAD

**Issue by d2verb** [vlang/v#1259]
**V version:** 
**OS:** 

**What did you do?**
compile following code
```go
import os

fn main() {
	if true {
		f := os.open('file.txt') or {
			return error('error')
		}
		defer { f.close() }
	}
}
```

**What did you expect to see?**
compile successfully
 
**What did you see instead?**
```
.test.c: In function ‘main’:
.test.c:4544:18: error: ‘f’ undeclared (first use in this function)
  os__File_close( f ) ;
                  ^
.test.c:4544:18: note: each undeclared identifier is reported only once for each function it appears in
V panic: clang error
```

**Comment by medvednikov** [comment]
Yeah, I was aware of that.

The easiest way to fix this is to have per block defers.

**Comment by d2verb** [comment]
@medvednikov yes, your idea in my previous issue (#1253) can solve this.

**Comment by medvednikov** [comment]
That would make the behavior very different to Go's defer, which is run when function returns.

But it's already different. `defer { }` vs Go's `defer func() { } ()`

**Comment by teggot-teggot** [comment]
It's not even possible to compile this code, because main cant return anything. Also when i tried to compile this code (I changed `return error('error')` to `return`) after commit [https://github.com/vlang/v/commit/fbc480fbeddc83f9c5933b27fc09d25cd687595e](url) its working just fine.

**Comment by crthpl** [comment]
@medvednikov can this be closed?

**Comment by Larpon** [comment]
This should work now. Please re-open if it's still an issue.
