### ISSUE TITLE
Issue using V from a makefile in Linux

### ISSUE THREAD

**Issue by WilliamBehrens** [vlang/v#12597]
OS: linux, "Void Linux"
Processor: 8 cpus, 64bit, little endian, 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
CC version: cc (GCC) 10.2.1 20201203

getwd: /home/will/Code/willows
vmodules: /home/will/.vmodules
vroot: /home/will/.local/bin/v
vexe: /home/will/.local/bin/v/v
vexe mtime: 2021-11-28 00:47:21
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 e42db5b.1d8ece7

Git version: git version 2.34.1
Git vroot status: weekly.2021.47-33-g1d8ece7a
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 333c14de

**What did you do?**
A simple makefile:
```
V=v
V_FLAGS= 

setup:
    $(V) install

build: setup
    $(V) $(V_FLAGS) test.v
```

**What did you expect to see?**
I expected the commands to run just the same as they would in the command line. I've tested it manually and it works as expected
 
**What did you see instead?**
```
v install 
make: v: Permission denied
make: *** [Makefile:26: setup] Error 127
```

**Comment by te-yd** [comment]
Try with an absolute path to v binary

if your PATH variable has ~/.local/bin then it won't work, because the v binary is in ~/.local/bin/v/v

Add ~/.local/bin/v to your PATH variable.

**Comment by trufae** [comment]
The makefile used is GNUmakefile not Makefile

**Comment by WilliamBehrens** [comment]
When using absolute path it works correctly, V is in my path though because I did `sudo ./v symlink`

**Comment by te-yd** [comment]
symlink manually using `ln -s` to ~/.local/bin
don't use sudo, it is not required to access ~/.local directory
I haven't used ./v symlink myself, I always linked manually.
