### ISSUE TITLE
Compilation speed test generated code is printf focused

### ISSUE THREAD

**Issue by atif1996** [vlang/v#126]
Few applications just sit there and print out lines to stdout.

Perhaps if I wanted a language to write a logger, this would be a useful comparison, but most of my code in a C++17, golang, java project do work.  Some applications are compute intensive where function inlining and FOPS matter (scientific computing/machine learning/engineering computations).  Other applications are network bound, most cloud applications fall into this category. 

I'd recommend having tests that do a more real world comparison between the languages.  A code generator may not be the best way to go.  Could do a simple program, and compile it enough time to get a measurable value to compare between compilers perhaps.  Some may also be interested in the execution speed of the resultant binary.  For performance critical applications, I may have my C++17 application O3, and I'll pay more for compilation but hope to get better runtime performance.

Cool project though.  Love the idea of transpiling a large codebase over from C++

**Comment by medvednikov** [comment]
Agreed, and I mentioned this on the test's page.

If anyone has a better test, I'd be happy to use it instead. Right now I don't have time to work on this.

**Comment by medvednikov** [comment]
Although I wouldn't call it irrelevant, because as the page says, the compilers face the same challenge.

**Comment by lutherwenxu** [comment]
This issue has been closed due to the inactivity.
Please reopen this issue if you want to continue the discussion.
