### ISSUE TITLE
Several questions about V

### ISSUE THREAD

**Issue by Rakete1111** [vlang/v#1261]
I have some questions about V that I haven't seen in the docs. Here they go :)

1. What's the type of literals?

`10` is a `i32` I presume and `3.14` a `f32`? Are there any other literals, like for example `1u32`.

2. How do I print a `$`? Like this: `println('This costs \$something')`? (Note `something` is not a variable!)

3. Why are strings immutable? You write that substring-ing is efficient that way, but that's not true, since even if strings are mutable it is efficient (have a look at how C++ does it). If I do `mut a = 'hello'` do I get a mutable string? If so than you should clarify that with strings you mean `'...'` this and not a variable that you assign it to I guess.

4. Is/Should there (be) any whitespace sensivity? If I write:

```
fn foo() int {
	println('hi')
	return 3
} 

a := 1
-foo()
println(a)
```

Then `a` is `-2`. Is this intended/wanted?

5. This: `expected type 'i32', but got 'int'`. Aren't they supposed to be the same? Or are those strong aliases? If so how do I convert from one to another?

6. `println(m['bad_key']) // "0"`. Ok that makes sense. But what if I have a map of some user defined type? What value is returned there?

7. Are there any implicit conversions? Can I write `if num % 2 { ... }` instead of `if num % 2 != 0 { ... }`?

8. Are switch statements (not match?) required to have a `else`? Can they be expressions too?

9. Embedded structs (why not call this inheritance?) have the same whitespace problem:

```
struct Button {
	Widget       // `Widget title`
	title string   // `string` syntax error
}
```

10. > When naming constants, PascalCase must be used.

Otherwise the compiler rejects the code? IMO I don't like being told how I should name my things.

11.  > The strings don't escape `draw_text`, so they are cleaned up when the function exits. 

I'd expect `'hello '` to be store inside the executable. No allocations necessary :)

> In fact, the first two calls won't result in any allocations at all.

That's impossible. `name1` can be a mutable variable; it is not possible to determine how much memory to allocate for this ahead of time.

>  For more complex cases manual memory management is required. This will be fixed soon. 

Sure, but please don't remove the option to manually deallocate. Or else it is really easy for V to allocate a lot of memory that is deallocated at the very end.

**Comment by medvednikov** [comment]
> 10 is a i32 I presume and 3.14 a f32? Are there any other literals, like for example 1u32.

int and f64. For everything else casting has to be used (`byte(0)`)

> How do I print a $? Like this: println('This costs \$something')? (Note something is not a variable!)

$10 works fine, $name doesn't. Escaping $ will be implemented.

Strings are immutable like in Go, Java, and many other languages. They are immutable values by definition, like integers. There's `strings.Builder` for buildings strings efficiently.

> Is/Should there (be) any whitespace sensivity?

Yes, it'll be implemented like in Go. Newline meaning a `;`. So `a := 1; -foo()` will be possible too.

> This: expected type 'i32', but got 'int'. Aren't they supposed to be the same? 

Yes, this is not implemented yet. I really want to remove i32 and u8, but many people against that.

> But what if I have a map of some user defined type? What value is returned there?

Zero value. Just like with `foo := Foo{}`, each field gets zeroed.

> Are there any implicit conversions? Can I write if num % 2 { ... } instead of if num % 2 != 0 { ... }?

No. I'm considering allowing ints where floats are required for more readable math code.

> Are switch statements (not match?) required to have a else? Can they be expressions too?

Switch statements will be removed soon.

Embedded structs are not implemented yet.

> Otherwise the compiler rejects the code? IMO I don't like being told how I should name my things.

V is a very strict language to ensure one style in all programs.

> I'd expect 'hello ' to be store inside the executable. No allocations necessary :)

And it is. `'hello $name'` needs an allocation.

> Sure, but please don't remove the option to manually deallocate. Or else it is really easy for V to allocate a lot of memory that is deallocated at the very end.

It will be an option. Perhaps under `unsafe`.

**Comment by Rakete1111** [comment]
Cool thanks!

**Comment by medvednikov** [comment]
Let's leave it open for a couple of days.

**Comment by Rendims** [comment]
> $10 works fine, $name doesn't. Escaping $ will be implemented.

When escaping is implementing then maybe it should be enforced as well to avoid confusion.
That is, make `'$10'` and `'$'` invalid and require it to be `'\$10'` and `'\$'`.

**Comment by joe-conigliaro** [comment]
actually sldo u64, I made it detect u64 automatically if a number is too big for a u32

**Comment by Rakete1111** [comment]
> When escaping is implemented then maybe it should be enforced as well to avoid confusion.

Good idea, `printf` also does this - requiring `%%` to print a `%`.

**Comment by joe-conigliaro** [comment]
@medvednikov cant int just be an alias for i32?

**Comment by medvednikov** [comment]
> cant int just be an alias for i32?

Yes, that's what it's supposed to be.

**Comment by 0x9ef** [comment]
Dont remove i32 and u8 . Int must be alias of i32 , byte alias of u8.

**Comment by SuperFola** [comment]
By removing switches you will lose a lot of compiler optimizations and we would have to use jump tables to optimize a long chain of ifs...

**Comment by medvednikov** [comment]
@SuperFola they are replaced by match expressions.

**Comment by SuperFola** [comment]
But a match can costs more than a switch, or do you have an idea to enhance that? 🤔

**Comment by medvednikov** [comment]
This is optimized by C with -O2.

The old switch was already using `if else` because it accepts more complex expressions than C's switch.

**Comment by SuperFola** [comment]
Do you have more details about you're going to implement this match statement?

**Comment by medvednikov** [comment]
It already is, it just can't be used as an expression yet. https://github.com/vlang/v/blob/master/compiler/tests/match_test.v
