### ISSUE TITLE
Regular expressions

### ISSUE THREAD

**Issue by MarisKori** [vlang/v#127]
Are you going to add support of regexp?

I think it should be part of the language.
But it shouldn't increase binary size if not used.

**Comment by ntrel** [comment]
I think with the right general language features, there's not really an advantage to having special syntax for regular expressions in the language. I think raw string support is planned, so `\` won't need escaping.

Also in the future it may be possible to compile a regular expression as a compile time `const` value. Then pass a runtime string to it for matching. (D and Rust can do this).

**Comment by medvednikov** [comment]
@ntrel answered it the same way I would :)
