### ISSUE TITLE
Bug in net.http related to add_custom_header and add_custom

### ISSUE THREAD

**Issue by 7047payloads** [vlang/v#12728]
**V version: V 0.2.4 105d7fc** 
**OS: Arch Linux 5.10.83-1-lts** 

**What did you do?**
```v
import net.http

fn main() {
    mut req := http.Request{
        url: 'http://127.0.0.1:8000'
    }
    req.add_custom_header('Cookie', 'auth=eyJhZG1pbiI6ZmFsc2V9Cg') ?
    req.do() ?
}
```

I compiled the code, spun up netcat like `nc -vlp 8000` and ran the binary.

**What did you expect to see?**
```
Connection from 127.0.0.1:50966
GET / HTTP/1.1
Host: 127.0.0.1
User-Agent: v.http
Connection: close
Cookie: auth=eyJhZG1pbiI6ZmFsc2V9Cg
```
 
**What did you see instead?**
```
Connection from 127.0.0.1:50966
GET / HTTP/1.1
Host: 127.0.0.1
User-Agent: v.http
Connection: close
```

Note that there is no cookie header.

Additional notes:
If I tried this line of code instead
```v
req.add_custom_header('Cookies-mmm', 'auth=eyJhZG1pbiI6ZmFsc2V9Cg') ?
```
netcat would result in
```
Connection from 127.0.0.1:50972
GET / HTTP/1.1
Host: 127.0.0.1
User-Agent: v.http
Cookies-mmm: auth=eyJhZG1pbiI6ZmFsc2V9Cg
Connection: close
```

**Comment by Le0Developer** [comment]
Use the `cookies` map instead of setting the header directly.

```v
req.cookies['auth'] = 'eyJhZG1pbiI6ZmFsc2V9Cg'
```

**Comment by 7047payloads** [comment]
The following block in `net/http/request.v` gets in the way when I'm building a fuzzer. 
```v
if key == CommonHeader.cookie.str() {
      continue
}
```
Thanks, I will use a modified version of it for my implementation.
