### ISSUE TITLE
License of compiled code?

### ISSUE THREAD

**Issue by MK-Alias** [vlang/v#12730]
Does V generated code contain a runtime or something else that inherits the MIT (or any other) license?

For example, if someone would write this hello world program: `hello.v`
```
fn main() {
    println("Hello World!")
}
```
after compiling it: `v hello.v` to `hello.exe`, does hello.exe inherit any license, or is it just plain generated code?

Thanks for any help on this!

**Comment by medvednikov** [comment]
I think it doesn't inherit anything, but the generated code does have parts of vlib which is MIT licenced.

**Comment by MK-Alias** [comment]
Okay, thank you for your reply! What i see a lot of time is that a runtime/default-lib can (and lots of times will) include other third party libs which are all licensed and inherited. Can you - just to be sure - confirm that the default vlib does not include any other third-party libs/code that contain other licenses?

If the answer is no, than my question is satisfied and please feel free to close this ticket!

Thank you!

**Comment by medvednikov** [comment]
Yes, I can confirm there no 3rd party libs in default vlib. There's cjson if you `import json`, but it's going to be removed soon, and it's MIT.

**Comment by MK-Alias** [comment]
Thank You!
