### ISSUE TITLE
Sum type in a match generates error expecting all other branches to be the same type as the first branch type

### ISSUE THREAD

**Issue by DevrosTheOne** [vlang/v#12731]
**V version:** 
V full version: V 0.2.4 2d43fdb.105d7fc
**OS:** 
OS: macos, macOS, 12.0.1, 21A559
Processor: 8 cpus, 64bit, little endian, Apple M1
CC version: Apple clang version 13.0.0 (clang-1300.0.29.3)
**What did you do?**
Using sum type in array to wrap 3 structs.  Loop through the array to extract to recover the attributes and structures using dynamic cast `as`.  Returning the original struct the `match` errors expecting each item in rest of the branches to be the same type as the first brach (in the example `Mouse`).  Works correctly if we use `str()` on the cast item.
```v
struct Cat {
	c_name    string = 'Kitty'
	age int = 3
}

struct Dog {
	d_name    string = 'Doggy'
	age int = 2
}

struct Mouse {
	m_name    string = 'Squeaky'
	age int = 1
}

type Pet = Cat | Dog | Mouse

fn main() {
	mut pets := [Pet(Cat{}), Dog{}, Mouse{}]

	for pet in pets {
		n := match pet {
			Mouse { (pet as Mouse).m_name }
			Cat { (pet as Cat).c_name }
			Dog { (pet as Dog).d_name }
		}
		println(n)
	}
	for pet in pets {
		st := match pet {
			Mouse { (pet as Mouse).str() }
			Cat { (pet as Cat).str() }
			Dog { (pet as Dog).str() }
		}
		println(st)
	}
	// Error match branches expect the first branch type 'Mouse'
	for pet in pets {
		p := match pet {
			Mouse{ pet as Mouse }
			Cat { pet as Cat }
			Dog { pet as Dog }
		}
		println(p.age)
	}
}
```
**What did you expect to see?**
3
2
1
 
**What did you see instead?**
sumerr.v:41:14: error: return type mismatch, it should be `Mouse`
   39 |         p := match pet {
   40 |             Mouse{ pet as Mouse }
   41 |             Cat { pet as Cat }
      |                       ~~
   42 |             Dog { pet as Dog }
   43 |         }
sumerr.v:42:14: error: return type mismatch, it should be `Mouse`
   40 |             Mouse{ pet as Mouse }
   41 |             Cat { pet as Cat }
   42 |             Dog { pet as Dog }
      |                       ~~
   43 |         }
   44 |         println(p.age)

**Comment by yuyi98** [comment]
There is no way to determine what type of value to expect from the context, so we have to rely on the return type of the first branch. 
Is there a good solution?

**Comment by JalonSolov** [comment]
The docs show this example:
```v
if s is Dog {
		println('a $s.breed dog') // `s` is automatically cast to `Dog` (smart cast)
	} else if s is Cat {
		println('a $s.breed cat')
	} else {
		println('something else')
	}
```
Could V support something like
```v
	for pet in pets {
		p := match pet {
			pet is Mouse{ pet as Mouse }
			pet is Cat { pet as Cat }
			pet is Dog { pet as Dog }
		}
		println(p.age)
	}
```
?  Or maybe just `is Mouse` since you already know what is being matched.

**Comment by DevrosTheOne** [comment]
Sorry was not thinking clearly.  
`match` only returns one type.  
The error message was kind of misleading. `return type mismatch, it should be Mouse`.  Jump to the wrong conclusion late at night.

Do I delete the misguided report or is it cleared up later?
