### ISSUE TITLE
Instructions from https://vlang.io/docs#modules seem outdated

### ISSUE THREAD

**Issue by Larpon** [vlang/v#1277]
**V version:**  0.1.15
**OS:** Linux

**What did you do?**
I'm trying to grasp how modules work - in particular how custom modules work.
https://vlang.io/docs#modules explain to use `v -lib <path/to/modules/module_name>`.
Up to this point I haven't been able to use `v -lib ...` successfully.
I always get: 
```
$ v -lib modules/mymodule
Building module mymodule...
V panic: /home/user/Projects/v/vlib/mymodule doesn't exist
```
... this is no matter how I try to reference `mymodule`.

**What did you expect to see?**
A clear way of how I should make my custom modules
 
**What did you see instead?**
```
V panic: /home/user/Projects/v/vlib/mymodule doesn't exist
```

**Comment by joe-conigliaro** [comment]
@Larpon the concept of user modules doesn't exist yet, it's being developed over the next few weeks, this is why it's not in the docs. Only vlib modules at the moment. Once a user module has been defined and implemented it will be added to the docs. Don't worry this is a priority feature.

**Comment by Larpon** [comment]
Ah I see, no problem.

So `v -lib ...` is for core modules?

**Comment by joe-conigliaro** [comment]
@Larpon it did used to work. But it got broken. It will be working again soon though!

**Comment by AtjonTV** [comment]
If you want to compile an App with custom Modules, this is how it works:

```
$ ls
app.v
modulea/
moduleb/

$ cat modulea/module.v
module modulea

pub fn hello() {
  print('Hello ')
}

$ cat moduleb/module.v
module moduleb

pub fn world() {
  println('world!')
}

$ cat app.v
module main
import modulea
import moduleb

fn main() {
  modulea.hello()
  moduleb.world()
}

$ v run app.v
============ running app ============
Hello world!
```

**Comment by Larpon** [comment]
@AtjonTV thanks!

**Comment by joe-conigliaro** [comment]
thanks @AtjonTV :) I didn't even realize that still worked. Just keep in mind this might change at any time. When the new system is implemented it will be announced, hopefully soon :)

**Comment by spytheman** [comment]
Thank you @AtjonTV !

**Comment by lutherwenxu** [comment]
It would seem like it has been updated since then. Closing.
(Reopen if you think it's still out-of-date)
