### ISSUE TITLE
Zero cost rust calling v lang

### ISSUE THREAD

**Issue by superdolt** [vlang/v#12792]
Zero cost rust calling v lang

**Comment by playXE** [comment]
V compiles to C and you can call Rust functions as just regular C functions if they're defined as `extern "C"` on the Rust side. There is nothing to add to V compiler itself. If you mean calling functions with Rust ABI i.e without any `extern "C" fn` then that is impossible, Rust ABI is unstable and thus must not be used.

Read this nomicon page for how to call Rust from C: https://doc.rust-lang.org/nomicon/ffi.html . TL;DR if you would like to call Rust from V you would need something like this:
```rust
#[no_mangle]
pub extern "C" fn foo(x: i32) -> i32 {
    println!("Hello from Rust!");
    return x * 2;
}
```
```v
fn C.foo(x int) int 

fn main() {
    println(foo(42))
}
```

you should compile rust code into dynamic library and link with your V program
