### ISSUE TITLE
Negative number unexpectedly appearing

### ISSUE THREAD

**Issue by zac-garby** [vlang/v#128]
I ran fibonacci example from the playground, except I changed `MAX` to be 100. It outputs the following:

```
0
1
1
2
... etc ...
1134903170
1836311903
-1323752223
512559... [trimmed after 300 characters]
```

The second-last line of the output has a negative sign at the start. My first thought was integer overflow, but that can't be the case firstly because the numbers are so small, but also because the next line is not negative.

**Comment by medvednikov** [comment]
Everything works as expected:

```
31 1346269
32 2178309
33 3524578
34 5702887
35 9227465
36 14930352
37 24157817
38 39088169
39 63245986
40 102334155
41 165580141
42 267914296
43 433494437
44 701408733
45 1134903170
46 1836311903
47 -1323752223
48 512559680
```

https://play.golang.org/p/_DjR1GSKZVz

```
1836311903
-1323752223
512559680
```

**Comment by fuzzthink** [comment]
"Works as expected" may need a little explanation ;)

You're on the right track @zac-garby , thinking "integer overlow". 

This should do (playground won't output due to > 1 sec)

```
fn fib(n int) i64 {
	if n <= 1 {
		return i64(n)
	}
	return fib(n - 1) + fib(n - 2)
}

fn main() {
	println(fib(47))
}
```

**Comment by medvednikov** [comment]
Yes, i32 results in overflows, i64 should be used for large numbers.

**Comment by zac-garby** [comment]
Huh, I really overestimated the maximum value of 32-bit integers.
