### ISSUE TITLE
Compiler bug: Cannot convert struct array into char*

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#12807]
**V version:** 0.2.4
**OS:** Linux

```v
// main.v
module main

#flag linux -I./include
#include "header.h"

fn C.foo(arr &char)

fn main() {
	data := []byte{len: 64}
	C.foo(&char(data))
}
```
```c
// header.h
void foo(const char* arr) {}
```

`/tmp/v_1000/struct_array_char.17219378000027339195.tmp.c:10725: error: cannot convert 'struct array' to 'char *'`

While working with a C library, I wrongly used a conversion from a `byte` array into a `&char` and this error happened.
Guess the V compiler doesn't detect these bad boys yet 👍🏽 

See the attached zip for full repro.

[struct_array_char.zip](https://github.com/vlang/v/files/7698686/struct_array_char.zip)

**Comment by medvednikov** [comment]
Compiles with ` C.foo(&char(data.data))`

Needs a better error.

**Comment by Delta456** [comment]
The above code gives an error now:

```
main.v:11:8: error: cannot cast array `[]byte` to `&char`
    9 | fn main() {
   10 |     data := []byte{len: 64}
   11 |     C.foo(&char(data))
      |           ~~~~~~~~~~~
   12 | }
```
