### ISSUE TITLE
Can't use mutable variables inside a defer statement

### ISSUE THREAD

**Issue by leonardoce** [vlang/v#1281]
**V version:** 0.1.15
**OS:** Mac OS X 10.14.5

**What did you do?**

Compile the following reproducer:

```
fn test_defer(a mut int) {
}

fn main() {
	a := 0
	defer { test_defer(mut a) }
}
```

**What did you expect to see?**

The source to compile successfully
 
**What did you see instead?**

The following generated C code fails to compile:

```c
 int main(int argc, char** argv) {
 init_consts();
 
int a= 0 ;
 
 /*
 {
 test_defer (& /*11 EXP:"int*" GOT:"int" */ a ) ;
 }
 */
  {
 test_defer (& /*11 EXP:"int*" GOT:"int" */ a ) ;
 }
 }
```

The compilation error happens because you can't have block comments inside block comments in C.

```
$ v test_defer.v
.test_defer.c:2962:47: error: extraneous ')' before ';'
 test_defer (& /*11 EXP:"int*" GOT:"int" */ a ) ;
                                              ^~
.test_defer.c:2965:3: error: expected identifier or '('
 */
  ^
.test_defer.c:2972:2: error: extraneous closing brace ('}')
 }
 ^
3 errors generated.
V panic: clang error
```

Thank you for the hard work.

**Comment by avitkauskas** [comment]
Perhaps you should define `a` as mutable in your v code: `mut a := 0`

**Comment by leonardoce** [comment]
Good point. Even if that's true the error should be caught by the V compiler and not by clang.
Anyway, the problem happens even when declaring the variable mutable:

```
fn test_defer(a mut int) {
}

fn main() {
	mut a := 0
	defer { test_defer(mut a) }
}
```

Generated code:

```c
 int main(int argc, char** argv) {
 init_consts();

int a= 0 ;

 /*
 {
 test_defer (& /*11 EXP:"int*" GOT:"int" */ a ) ;
 }
 */
  {
 test_defer (& /*11 EXP:"int*" GOT:"int" */ a ) ;
 }
 }
```
