### ISSUE TITLE
Literal in augmented operators

### ISSUE THREAD

**Issue by mblandr** [vlang/v#12849]
**V version:** 0.2.4 2ce1647
**OS:** Windows 10

**What did you do?**
fn main() {
	mut v := u8(1)
	v +=1
	println(typeof(v).name)
}

**What did you expect to see?**
u8
 
**What did you see instead?**
error: mismatched types `u8` and `int literal`
But with long version 
v = v+1
it's work

**Comment by yuyi98** [comment]
Fixed.
```v
fn main() {
	mut v := u8(1)
	v += 2
	println(typeof(v).name)
	println(v)
}

PS D:\Test\v\tt1> v run .
u8
3
```
