### ISSUE TITLE
`unsafe{ &var }` lost its reference.

### ISSUE THREAD

**Issue by kahsa** [vlang/v#12852]
**V version: 0.2.4 2ce1647** 
**OS: ArchLinux** 

**What did you do?**
It was working a few hours ago, and I seem to remember that the compiler told me to add unsafe there before, so I did...
Not sure if this is a bug or not, but I think at least a warning or error should be given because it makes a serious difference in the outcome which causes a bug that is very hard to find.

```v
struct Con{
	server &Server
}

struct Server{
	backlog int
}

fn (hs Server) accept() Con {
	con := Con{
		server: unsafe{ &hs }
		// server: &hs  // works
	}
	dump(con.server) // OK
	return con
}

fn (hs Server) run(){
	con := hs.accept()
	dump(con.server) // LOST
}

fn main(){
	srv := Server{
		backlog: 128
	}
	srv.run()
}
```

**What did you expect to see?**
```
> v run main2.v
[main2.v:14] con.server: &Server{
    backlog: 128
}
[main2.v:20] con.server: &Server{
    backlog: 128
}
```
**What did you see instead?**
```
> v run main2.v
[main2.v:14] con.server: &Server{
    backlog: 128
}
[main2.v:20] con.server: &Server{
    backlog: 7
}
```

**Comment by kahsa** [comment]
oh, this gives that message.
Has the behavior changed?
```v
fn (hs &Server) accept() Con {
	con := Con{
		// server: unsafe{ hs }
		server: hs  // works
	}
	dump(con.server) // OK
	return con
}
```
```
> v run main2.v
main2.v:12:11: error: `hs` cannot be assigned outside `unsafe` blocks as it might refer to an object stored on stack. Consider declaring `Server` as `[heap]`.
   10 |     con := Con{
   11 |         // server: unsafe{ hs }
   12 |         server: hs  // works
      |                 ~~
   13 |     }
   14 |     dump(con.server) // OK
```

**Comment by kahsa** [comment]
adding `[heap]` like 
```v
[heap]
struct Con{
	server &Server
}

[heap]
struct Server{
	backlog int
}
```
fixes this issue.

**Comment by kahsa** [comment]
if `server: unsafe{ &hs }` is illegal, then compiler should warn it.

**Comment by spytheman** [comment]
> if `server: unsafe{ &hs }` is illegal, then compiler should warn it.

No, it should not - you are explicitly marking it with `unsafe {}`, i.e. you are telling the compiler that you *DO* want that, even though taking the address of something on the stack may not be safe.
