### ISSUE TITLE
Omitting struct names when it's clear from the context

### ISSUE THREAD

**Issue by Zhomart** [vlang/v#12889]
Currently V allows omitting certain type names when assigning values to variables or passing to functions. V should do the same for `struct` too. It will make the language more consistent and also creating and reading struct values simpler. 

It would make instantiating complex structs much simpler, in addition to IDEs autocomplete and type hint visuals. Similar to TypeScript.

Example:

```
struct RequestParams {
	id int
	search string
}

struct Request {
	params RequestParams
}

struct Response {
	code int
}

// 1. CURRENT

fn fetch(req Request) Response {
	println('fetching')
	println(req)
	return Response {
		code: 200
	}
}

req := Request {
	params: RequestParams {
		id: 1,  // We don't do this, the type is extracted from the context:  id: int(1) 
		search: "hello"
	}
}

fetch(req)
fetch(Request{
	params: RequestParams {
		id: 2,
		search: "world"
	}
})

// 2. PROPOSED

fn fetch(req Request) Response {
	println('fetching')
	println(req)
	return {
		code: 200
	}
}

req := Request {
	params: {  // IDEs may show type hint, similar to what Rust, Dart, etc do
		id: 1,
		search: "hello"
	}
}

fetch(req)
fetch({
	params: {   // IDEs may show type hint, similar to what Rust, Dart, etc do
		id: 2,
		search: "world"
	}
})

```

**Comment by kahsa** [comment]
Personally, I don't want too many abbreviations, because I think they make V less readable and maintainable.
I don't want V to become like other languages.

**Comment by Zhomart** [comment]
It looks like simplicity and clarity is the power of V. When writing performant code in Java, C++, Go and so, we  write a lot of verbose code, but looks like V is changing that, it allows us writing fast code with  pleasant syntax.

V already allows omitting struct name when passing to the function as an argument. But we cannot do similar when assigning to the variable with the known type.

**Comment by danieldaeschle** [comment]
We had this once, we removed it because of the one way philosophy.

**Comment by kahsa** [comment]
Let's say you are in a situation where you need to go back and read the code you wrote three years ago. Or in someone else's code.

Would you be able to look at the code, which is so abbreviated, and immediately understand what you have done without comment?

That's what I mean by readability and maintainability of V. 
It is more important to be able to read the code you see for the first time (or almost forgot) without comments than to be able to write the code with fewer characters.

On the other hand, overly verbose expressions are useless.
It's a balance. I think V has a very good balance now.

**Comment by Zhomart** [comment]
Thanks for the detailed replies!
