### ISSUE TITLE
news_fetcher problem

### ISSUE THREAD

**Issue by lcddh** [vlang/v#1288]
**V version:** 0.1.16
**OS:** win10

**What did you do?**
v run news_fetcher.v

**What did you see instead?**
![image](https://user-images.githubusercontent.com/5841609/61765254-e0743c80-ae0e-11e9-87e0-fb5302e3242e.png)

**Comment by medvednikov** [comment]
Fixed.

**Comment by lcddh** [comment]
![image](https://user-images.githubusercontent.com/5841609/61847590-ce150400-aedd-11e9-8dbc-c02678804824.png)
