### ISSUE TITLE
Passing a closure to arr.map gives a compiler error

### ISSUE THREAD

**Issue by alii** [vlang/v#12906]
**V doctor:**
```
OS: macos, macOS, 12.0.1, 21A559
Processor: 8 cpus, 64bit, little endian, Apple M1
CC version: Apple clang version 13.0.0 (clang-1300.0.29.3)

getwd: /Users/ali/code/chvss
vmodules: /Users/ali/.vmodules
vroot: /Users/ali/tools/v
vexe: /Users/ali/tools/v/v
vexe mtime: 2021-12-20 12:39:15
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 e5e3979.f81654e

Git version: git version 2.30.1 (Apple Git-130)
Git vroot status: weekly.2021.50.3-57-gf81654e3
.git/config present: true
thirdparty/tcc status: thirdparty-unknown-unknown de82a130

```

**What did you do?**
Attempted to use a closure as a callback for `[]string.map`
```v
mut i := 0

numbers := structs.letters.map(fn [mut i] (val string) int {
	i++
	return i
})
```

**What did you expect to see?**
The closure would run successfully

**What did you see instead?**
A compiler error:
![image](https://user-images.githubusercontent.com/25351731/146771511-773c922e-05b1-4a61-bfdd-b329a9ced8c1.png)

After asking in the vlang discord, the "fix" was to assign the closure to a variable locally and pass that as the callback:
[link to conversation in discord.gg/vlang](https://canary.discord.com/channels/592103645835821068/592294828432424960/922470490398916618)

![image](https://user-images.githubusercontent.com/25351731/146771566-3effc5af-36b6-4517-91e7-ffd4362273b0.png)

(thank you for the help @spytheman 😄)

**Comment by danieldaeschle** [comment]
@spaceface777

**Comment by apoprotsky** [comment]
There is no compiler error for now but causes segmentation fault as described in #14416

**Comment by Delta456** [comment]
Compiles with the latest version of V

```v

mut i := 0

a := ['str', 'hello']

numbers := a.map(fn [mut i] (val string) int {
	i++
	return i
})

println(numbers)
```
