### ISSUE TITLE
Simple sql query dont compile

### ISSUE THREAD

**Issue by mblandr** [vlang/v#12904]
**V version:** 0.2.4 7c85c2a
**OS:** Windows 10

**What did you do?**
```
import sqlite 

struct Article{
	id int [primary; sql: serial]
	title string
	text string
}

fn main() {
	db := sqlite.connect('database.db') or {panic(err)}
	articles := sql db {
		select from Article
	}
	println(articles)
}
```
**What did you see instead?**
blog.9812286841040080457.tmp.c
E:\Temp\v_0\blog.9812286841040080457.tmp.c(36427): error C2059: syntax error: '}'
builder error: msvc error

**Comment by JalonSolov** [comment]
Compiles clean with latest `V 0.2.4 460f7c6` on Linux.  Possibly an msvc/Windows specific problem?

**Comment by nicks515** [comment]
I had same problem.
I think it's msvc's problem.
vlang compiler generate c99 C codes,
but msvc not support c99 standard perfectly.
try a mingw64.

**Comment by nicks515** [comment]
> **V version:** 0.2.4 7c85c2a **OS:** Windows 10
> 
> **What did you do?**
> 
> ```
> import sqlite 
> 
> struct Article{
> 	id int [primary; sql: serial]
> 	title string
> 	text string
> }
> 
> fn main() {
> 	db := sqlite.connect('database.db') or {panic(err)}
> 	articles := sql db {
> 		select from Article
> 	}
> 	println(articles)
> }
> ```
> 
> **What did you see instead?** blog.9812286841040080457.tmp.c E:\Temp\v_0\blog.9812286841040080457.tmp.c(36427): error C2059: syntax error: '}' builder error: msvc error
