### ISSUE TITLE
Compiler Error -- declaration of void object during map()

### ISSUE THREAD

**Issue by dcuka-foss** [vlang/v#12910]
```
OS: linux, Ubuntu 20.04.3 LTS
Processor: 12 cpus, 64bit, little endian, AMD Ryzen 5 2600 Six-Core Processor
CC version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

getwd: /sda/home/dcuka/git/2021-advent/src/day-12
vmodules: /home/dcuka/.vmodules
vroot: /sda/home/dcuka/git/v
vexe: /sda/home/dcuka/git/v/v
vexe mtime: 2021-12-20 16:17:20
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 5f0160b

Git version: git version 2.25.1
Git vroot status: weekly.2021.50.3-58-g5f0160bf
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 333c14de
```
**What did you do?**
I am trying to use the keys in a MAP to keep track of visited nodes in a Graph since I could not find a SET data structure.  I have to have a value on the map to I am simply mapping to a bool which will be set to true.    At issue is the OR block which I am trying to use to have it create the entry if the entry does not exist while adding all of the child nodes to the horizon list in order to print them too.
```v
struct Graph
{
mut:
        root    Node
        forest  []Node
}

struct Node
{
        name    string
mut:
        kids    map[string][]Node
}

fn (g Graph) pp()
{
        mut visited := map[string]bool{}
        mut horizon := [ g.root ]

        for horizon.len > 0 
        {
                current := horizon.first()
                horizon.delete(0)
                println("$current.name -> ${current.kids.keys()}")
                visited[current.name] = true
                for k,v in current.kids
                {
                        x := visited[k] or { 
                                v.map( horizon << it )
                                true
                                }
                }
                //println("HORIZON = $horizon")
        }
```

**What did you expect to see?**
expecting "x" to have a bool value but I think it is getting void somehow or more likely it is an issue with the call to v.map() which is intended to add each child to the "horizon" data structure. 
 
**What did you see instead?**
```
/tmp/v_1000/day-12.16345542184943475951.tmp.c:15357: error: declaration of void object
builder error: 
==================
C error. This should never happen.
```
Attached are the temporary files generated ...

[void.zip](https://github.com/vlang/v/files/7746722/void.zip)

**Comment by yuyi98** [comment]
`v.map( horizon << it )` is error, the usage is wrong, but we should check the error.

**Comment by Delta456** [comment]
> `v.map( horizon << it )` is error, the usage is wrong, but we should check the error.

Fixed, I will PR soon.

![image](https://user-images.githubusercontent.com/28479139/190900240-7ccef3f5-32e1-43b7-8cb4-ab62091430df.png)
