### ISSUE TITLE
./v symlink panic

### ISSUE THREAD

**Issue by bumbread** [vlang/v#12933]
**V version:** 0.2.4 2b9f993
**OS:** Ubuntu 20.04.3 LTS

Newly cloned v repository:

```
$ ./v symlink
V panic: folder: /usr/local/bin/, error: Permission denied
```

When I run `ls -l /usr/local`, bin directory is not there. In other words there are three bugs in one place

- V crashes when the file /usr/local/bin could not be opened
- The error message is "Permission denied", even though the correct reason is "Directory doesn't exist"
- I believe this is incorrect destination for symlinking

For the latter, I believe you should be using /usr/bin, not /usr/local/bin, because the former is guaranteed to exist and be in $PATH, whereas the latter isn't even listed in FHS.

**Comment by Hunam6** [comment]
You must prepend `sudo`: `sudo ./v symlink`.

**Comment by Larpon** [comment]
V doesn't crash in your example. It panics, correctly.

The error message is a bit off, yes - that could be more precise.

If you don't want it to be in `/usr/local/bin` you can symlink it manually to a destination in your `$PATH`. IIRC `/usr/local/bin` was chosen because it is the most commonly available destination for binaries on most major Linux distros.

**Comment by bumbread** [comment]
Please reopen this issue.

> V doesn't crash in your example. It panics, correctly

This is a weird position. The software should never panic in production code, that's the entire point of panic -- if it fires, the code is incorrect. It's correct when it comes to the fact that panic works, but it is not correct considering this semantic of panic. Perhaps you should rename this panic to some sort of "generic error" if you don't want to bother fixing it otherwise.

> `/usr/local/bin` [is available on] most major Linux distros

That's not correct. In Ubuntu, Debian, Arch this directory does not exist. I think these OSes account for a large enough portion of computers running Linux to consider. If your OS does have that though, most likely it's some third-party program creating this directory. I don't think relying on "most" is a good idea anyways. If you are not sure whether this path exists you should create directory corresponding to it.

I'd appreciate if this behavior was fixed instead of you providing the hack that will make this work. I recommend changing this location to `/usr/bin` because it exists on ALL linux distributions and is basically guaranteed to be in $PATH.

**Comment by bumbread** [comment]
For the lack of good response, I have figured it out myself. The panic message is correct. Apparently the code that does symlinking already was trying to create the `/usr/local/bin` directory. Apparently I also misread it's name when I verified it's presence. I'm not sure about arch, but on Ubuntu it didn't exist, although it was in $PATH.

This leaves the only issue is panicking instead of printing a normal error message.

**Comment by Larpon** [comment]
... did you run `./v symlink` with `sudo` [as the docs describe](https://github.com/vlang/v#symlinking)?

**Comment by bumbread** [comment]
I did and that worked, but that's not the issue. The issue is the behaviour of the compiler without `sudo`

**Comment by Hunam6** [comment]
> I did and that worked, but that's not the issue. The issue is the behaviour of the compiler without `sudo`

As @Larpon just said that's not an issue because you're supposed to use the command like this, as written in the documentation that you're supposed to follow when installing V

**Comment by JalonSolov** [comment]
I would argue that it _is_ a problem in the command line.  It should never crash, regardless of whether or not it is used "correctly."

**Comment by medvednikov** [comment]
```
./v symlink
Failed to create symlink "/usr/local/bin/v". Try again with sudo.
```
