### ISSUE TITLE
`_ := m['a'] or { return }` does not work correctly.

### ISSUE THREAD

**Issue by kahsa** [vlang/v#12942]
**V version: 0.2.4 db1175e** 
**OS: ArchLinux** 

**What did you do?**
```v
fn main(){
	mut m := map[string]int{}
	// a := m['a'] or { return } // works
	_ := m['a'] or { return }
	println('a')
}
```

**What did you expect to see?**

prints nothing.
 
**What did you see instead?**

prints `a`.

**Comment by changrui** [comment]
`It's OK.`
