### ISSUE TITLE
unrecognized command-line option -municode

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#12948]
**V version:** latest
**OS:** Windows 10
gcc: 11.2.0 (Mingw64 cygwin)

**What did you do?**
```v
module main

fn call() {
	panic('test')
}

fn main() {
	call()
}
```

**What did you expect to see?**
A panic, but the program should compile
 
**What did you see instead?**

```
➜  v git:(master) ✗ v -cc gcc run main.v   
==================
gcc: error: unrecognized command-line option ‘-municode’
...
==================
(Use `v -cg` to print the entire error message)
```

**Comment by Ekopalypse** [comment]
But it doesn't look like a V problem.
It looks like your setup has been corrupted somehow.
What do the following commands (executed from the cmd shell) produce?

````
where gcc
gcc --version
gcc --help=target | findstr /C:"municode"
````

**Comment by danieldaeschle** [comment]
It was on windows... it's okay. Will close it.
