### ISSUE TITLE
Command `greet` has no flag `--language`

### ISSUE THREAD

**Issue by NightyLighty** [vlang/v#12958]
I tried using the example from https://github.com/vlang/v/blob/master/examples/cli.v.
I compiled it using `v cli.v`
And, executed `cli greet --language english something`
It returned:
![image](https://user-images.githubusercontent.com/95951289/147352584-633f9dcb-da88-4221-8847-ceb734429b46.png)

**Comment by JalonSolov** [comment]
The `cli` module uses the POSIX standard of only a single `-` in front of options, instead of the GNU standard of `--`.  It works correctly if you just use `-language`, and correctly reports a problem with `--language`.

**Comment by trollkarlen** [comment]
I personally think that the "GNU standard" is a more modern way and should be preferred at least for a programming language developed on this side of the second century. I also think its the most adopted way except for some stone age tools in the linux world.
What was the design decision for this ?
