### ISSUE TITLE
cgen error: could not generate string method charptr_str for type 'charptr'

### ISSUE THREAD

**Issue by trufae** [vlang/v#12959]
**V version:** 
**OS:** 

**What did you do?**

```
$ cat a.v
fn main() {
	ohm := charptr(0)
	println(ohm.str())
}
$
```

**What did you expect to see?**

a working string like "(null)" or the decoded string in case that charptr points to a null terminated string
 
**What did you see instead?**

```
$ v a.v
cgen error: could not generate string method charptr_str for type 'charptr'
```

compiler error without much hints on where the error is (this is a hello world, but i found it in a much larger codebase, so i had to comment stuff until hit the problem).

same problem happens with `voidptr` and such.

**Comment by JalonSolov** [comment]
Both `charptr` and `voidptr` are for C interop.  They should only be used for such.

**Comment by spytheman** [comment]
You can do `println( voidptr(ohm) )` to see the value of the pointer, or use `println( cstring_to_vstring(ohm) )` to see the string itself (although not in this case, since it points to null).

**Comment by danieldaeschle** [comment]
But this should work or give a compiler error. Not a cgen error.
