### ISSUE TITLE
v fmt removes function bodies without warning

### ISSUE THREAD

**Issue by trufae** [vlang/v#12966]
**What did you do?**
**V version:** V full version: V 0.2.4 3528239
**OS:** OS: macos, Mac OS X, 10.15.7, 19H1419

the js backend doesnt error and the `v fmt` "removes" the function body without warning.

```v
$ cat j.v
fn JS.state_is_ready_on_leave(retval int) {
       println('Hooked callback')
}
$ v fmt j.v
fn JS.state_is_ready_on_leave(retval int)
$
```

so using the cgen results in proper error

```v
$ v fmt j.v
j.v:1:42: error: interop functions cannot have a body
    1 | fn C.state_is_ready_on_leave(retval int) {
      |                                          ^
    2 |        println('Hooked callback')
    3 | }

Internal vfmt error while formatting file: j.v.
Encountered a total of: 1 errors.
$ cat j.v
fn C.state_is_ready_on_leave(retval int) {
       println('Hooked callback')
}
$
```

## Test

see above

**What did you expect to see?**

 proper error at format and compile times because it could remove sensitive code by accident

**What did you see instead?**

silence and void

**Comment by JalonSolov** [comment]
More than 1 bug there.  Most obvious without looking further is that it changed `JS.` to `C.`.
