### ISSUE TITLE
Cannot infer integer

### ISSUE THREAD

**Issue by jesseflorig** [vlang/v#1298]
**V version:** 0.1.16
**OS:** MacOS Mojave 10.14.5

**What did you do?**
Declare an inferred integer with `num := 1`

**What did you expect to see?**
```
>>> num
1
```
 
**What did you see instead?**
```
>>> num
undefined `num`
```

**Full output**
```
V 0.1.16
Use Ctrl-C or `exit` to exit
>>> num := 1
>>> num
undefined: `num`
>>> num := int(1)
>>> num
1
>>> 
```

**Comment by medvednikov** [comment]
REPL broke very recently. Will fix.

In the meantime, please use `v file.v`.
