### ISSUE TITLE
http.Request cannot be work

### ISSUE THREAD

**Issue by zhou26192619** [vlang/v#12999]
**V version: V 0.2.4 d421f28, timestamp: 2021-12-29 21:48:23 +0200** 
**OS:Windows 10 专业版 20H2  19042.1415** 

**What did you do?**
I plan to write a test request with JSESSIONID information. like this:
```
import net.http
import time
fn run(ch chan string,mut jsessionid &string) {
	request := new http.Request {
		method:http.Method.get,
		url:"http://localhost:8080/****" // my request url
	}
	request.add_custom_header("JSESSIONID",*jsessionid)
	response:= request.do()or{
		println(err)
		return
	}
	println(response)
}
fn read_channel(ch chan string) {
	for {
		c := <- ch?
		println(c)
	}
}
mut jsessionid:=""
mut count:=0
ch := chan string{}
go read_channel(ch)
for {
	time.sleep(1000000000)
	go run(ch,mut &jsessionid)
}
```

**What did you expect to see?**
It can send a request every second.
 
**What did you see instead?**
I run this vsh and get this:
```
.\autohttp.vsh:6:22: error: expression evaluated but not used
    4 |
    5 | fn run(ch chan string,mut jsessionid &string) {
    6 |     request := new http.Request {
      |                         ~~~~~~~~~
    7 |         method:http.Method.get,
```

**Comment by Lathanao** [comment]
Your run() method contain 3 errors:

```v
fn run(ch chan string,mut jsessionid &string) {

	mut request := http.Request {
		method:http.Method.get,
		url:"http://localhost:8080/****" // my request url
	}

	request.add_custom_header("JSESSIONID",*jsessionid) or { return }

	response:= request.do() or {
		println(err)
		return
	}
	println(response)
}

```

Doing something like compile without error.

**Comment by zhou26192619** [comment]
> Your run() method contains 3 errors:
> 
> ```v
> fn run(ch chan string,mut jsessionid &string) {
> 
> 	mut request := http.Request {
> 		method:http.Method.get,
> 		url:"http://localhost:8080/****" // my request url
> 	}
> 
> 	request.add_custom_header("JSESSIONID",*jsessionid) or { return }
> 
> 	response:= request.do() or {
> 		println(err)
> 		return
> 	}
> 	println(response)
> }
> ```
> 
> Doing something like that compile without error.

thanks
