### ISSUE TITLE
bug of if

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#130]
I just want to know whether vlang if statement will create a new scope or not. then the complier tell me to go here.

Put follow code into this page https://vlang.io/play
```
fn main() {
        if true{
        mut types := ['game', 'web', 'tools', 'GUI']
}else{
types = ['game', 'web', 'tools', 'GUI','b']
}

        for typ in types {
                println('Hello, $typ developers!')
        }
} 
```
Then I got `You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.`

**Comment by medvednikov** [comment]
Thanks for reporting. The scopes are broken.

**Comment by bronze1man** [comment]
What will happen if the `if` statement do not create a scope? 
I hate the `if` statement scope in golang. It force me to define a variable outside the `if` scope.

**Comment by zac-garby** [comment]
The reason that you must defined the variable outside is that if you were allowed to define one inside and then use it after the if-statement has closed, it would potentially not be defined (e.g. if it was only defined in the `if` clause, not the `else`), which would lead to an error.

**Comment by ntrel** [comment]
If V gets function literals (and closures), then `types` can be immutable:
```rust
types := fn {
  if expr {
    return ['game', 'web', 'tools', 'GUI']
  } else {
    return ['some', 'other', 'data']
}()
```

**Comment by bronze1man** [comment]
> it would potentially not be defined (e.g. if it was only defined in the if clause, not the else), which would lead to an error.

So we can add a rule, if the variable is not defined in some branchs, then it will be the zero value in that branch. The zero value of golang struct field is very good for me.

**Comment by bronze1man** [comment]
>  If V gets function literals (and closures), then types can be immutable:

Is there any benefit for the human to defined that variable `types` to be immutable? 
The function literals make it more complex, I need to understand (but it is easy to understand) where the expr variable come from?Is the `expr` pass in by value or by pointer? when will this function literals be called?

**Comment by medvednikov** [comment]
Blocks create scopes in all languages.

Once if expressions are implemented, you will be able to do

```
types :=if expr {
    ['game', 'web', 'tools', 'GUI']
  } else {
    ['some', 'other', 'data']
  }
```

**Comment by bronze1man** [comment]
> Blocks create scopes in all languages.

I do not think so all languages are doing this. But it seems like that the new program language(golang/swift/zig), try to make if statement create a scope.
* In js ,if statement do not create a scope of the variable created by the `var` statement. 
* in php5, if statement do not create a scope either.

For example, I may want write some code like this:
```
func xxx(){
       ...
	if bucket.hasProgress{
		stat, err := f.Stat()
		if err != nil {
			f.Close()
			return 
		}
		fileSize := stat.Size()
	}
	writer,errMsg:=bucket.UploadFromWriterWithFileSize(remotePath,fileSize)
    ...
}
```

But I can only write like this with golang:
```
func xxx(){
       ...
	fileSize:=int64(0)
	if bucket.hasProgress{
		stat, err := f.Stat()
		if err != nil {
			f.Close()
			return `erftfzdauz ` + err.Error()
		}
		fileSize = stat.Size()
	}
	writer,errMsg:=bucket.UploadFromWriterWithFileSize(remotePath,fileSize)
    ...
}
```

**Comment by ntrel** [comment]
> Is there any benefit for the human to defined that variable types to be immutable?

Yes, it's much easier to reason about code, less bug prone, and immutable data can be shared across threads without races.

> The function literals make it more complex

Yes, Alex's `if` expression is a better solution here, but sometimes you need statements in one branch of the `if` construct to calculate the initialization value.

> where the expr variable come from?

It can be any expression.

> Is the expr pass in by value or by pointer?

I expect variable references in a closure would be by pointer (at least by default). Modern optimizers should be able to inline a function literal that is immediately called.

> when will this function literals be called?

Immediately on evaluation of the literal expression, because I wrote `()` after the literal to call it.

> In js ,if statement do not create a scope of the variable created by the var statement

JS and PHP are both dynamically typed languages. But even in JS, they added `let` in 2015, because `var` is too bug prone , unintuitive and imprecise. `let` does use brace scoping.

**Comment by bronze1man** [comment]
> Yes, it's much easier to reason about code, less bug prone, and immutable data can be shared across threads without races.

Inneed. But golang  only have part of it...

> But even in JS, they added let in 2015, because var is too bug prone , unintuitive and imprecise. 

May be I am wrong, if block may be better to reduce error of human.

**Comment by medvednikov** [comment]
This is actually a terrible practice and goes against the philosophy of V, and is not allowed in all non-dynamic languages.

**Comment by bronze1man** [comment]
> This is actually a terrible practice and goes against the philosophy of V, and is not allowed in all non-dynamic languages.

Thanks for your explanation.

**Comment by zac-garby** [comment]
A possible solution might be something like this:

```rust
if (cond) {
    x := some value
    export x // or some other keyword
}

// code using x
```

Here, the `export` keyword is used to inject a variable into the enclosing scope, meaning you are allowed to use that variable outside of the if-block.

This reduces the ambiguity where you might not know if a variable is available outside the block, and also means you have to explicitly ask for the feature, in which case you will have to think about the consequences.

(If `export` should be used for exporting symbols from modules, another option might be `eject` or `up`.)

**Comment by medvednikov** [comment]
This is making the language more complex with no clear benefit. What's wrong with scoped variables?

**Comment by zac-garby** [comment]
The benefit is that you don't have to explicitly define a variable outside of a scope in the case that you will only define its value inside that scope when you want to use that variable after the scope has closed. Admittedly, it's only a small benefit, but it would be useful.

**Comment by medvednikov** [comment]
If you need to use the variable outside a certain scope, then why define it in that scope? :) Just define it in the parent scope.

**Comment by ntrel** [comment]
On the proposed if expression syntax:
```rust
result := if expr {expr2} else {expr3}
```
Those braces seem quite noisy, and they can't contain statements despite looking like a statement block. Avoiding nesting of brackets and braces helps when reading complex code. 

Alternative syntax options:
```rust
result := if expr : expr2 else expr3
result := if (expr) expr2 else expr3
```
Related: https://github.com/vlang/v/issues/129#issuecomment-485256510

**Comment by ntrel** [comment]
Actually this seems more distinctive:
```rust
result := if expr -> expr2 else expr3
result := if x == y -> expr2 else expr3
```

**Comment by medvednikov** [comment]
>  they can't contain statements despite looking like a statement

they can

```
result := if expr {
st()
expr2
} else {
expr3
}
```

**Comment by ntrel** [comment]
Ok, thanks. So I suppose the same goes with #129:
`v := opt or {st(); expr}`

**Comment by medvednikov** [comment]
The bug with the scopes has been fixed.
