### ISSUE TITLE
Invalid fixed length array copy

### ISSUE THREAD

**Issue by 688862** [vlang/v#13009]
module main

fn main() {
	aa := [byte(0), 0xFF, 0xFF]

	mut bufa := [8]byte{}
	copy(bufa[..], aa)
	println(bufa)  //[0, 0, 0, 0, 0, 0, 0, 0]

	mut bufb := []byte{len:8}
	copy(bufb[..], aa)
	println(bufb)  //[`\0`, 0xff, 0xff, `\0`, `\0`, `\0`, `\0`, `\0`]
}

**Comment by ylluminate** [comment]
Please let us know if you have any more trouble @688862

**Comment by spytheman** [comment]
`bufa[..]` should and does create a new dynamic array.
