### ISSUE TITLE
POW without importing modules

### ISSUE THREAD

**Issue by ZaViBiS** [vlang/v#13007]
python:
```python
>>> 10 ** 2.3
199.52623149688787
```
I would like to do the same in V.

* The text may not be accurate because it was translated by a translator. *

**Comment by JalonSolov** [comment]
You want the `.pow()` function without having to import the `math` module.  This has been mentioned a few times in the past, but is not currently supported.

**Comment by yuyi98** [comment]
```vlang
PS D:\v> v
Welcome to the V REPL (for help with V itself, type  exit , then run  v help ).
  NB: the REPL is highly experimental. For best V experience, use a text editor,
  save your code in a  main.v  file and execute:  v run main.v
V 0.2.4 6438512
Use Ctrl-C or  exit  to exit, or  help  to see other available commands
>>> math.pow(10, 2.3)
199.5262314968879
>>>
```

**Comment by ylluminate** [comment]
I kinda like the idea of having `pow` integrated as well... Can you make some more convincing arguments / give additional reasons for this @ZaViBiS?

**Comment by ZaViBiS** [comment]
Other than convenience and getting the square root, I can't find any reason.
```python
>>> 25 ** 0.5
5.0
```

**Comment by JalonSolov** [comment]
Probably the main reason is that most, if not all other languages have it as a standard operator (rather than having to import something extra).  Python, Java, Swift, Rust, Go, JavaScript, etc., etc., etc.  Some languages use `^` while others use `**`.

Since V uses `^` for bitwise XOR, it would need to be something else, but there are definitely times when it could be handy to have without having to import the `math` module.

**Comment by spytheman** [comment]
`import math` is 1 line

**Comment by ZaViBiS** [comment]
and there will be 0 lines

**Comment by Wertzui123** [comment]
> `import math` is 1 line

For which you need to scroll up to the top of your file.

**Comment by JalonSolov** [comment]
... and include a whole, huge module to get a single function.

**Comment by spytheman** [comment]
> and there will be 0 lines

and it will makes certain usages of V harder/more complex, just because you do not like to type 1 single clear line
