### ISSUE TITLE
Build error in WSL.

### ISSUE THREAD

**Issue by zrma** [vlang/v#1300]
**V version: 0.1.16
**OS: WSL on Windows 10(1709 - 16299.1087)
WSL - Ubuntu 18.04.1 LTS

**What did you do?**
~/v$ curl -O https://raw.githubusercontent.com/vlang/vc/master/v.c
~/v$ cc -std=gnu11 -w -o v v.c -lm  # Build it with Clang or GCC
~/v$ ./v -o v compiler
Segmentation fault (core dumped)

**What did you expect to see?**
Compiled success
 
**What did you see instead?**
Segmentation fault

How I get more information of compilation?
Like '-v'  option in golang, example) go get -v (urls) command shows detail informations.

Etc) When I compile v in WSL on windows 10(1803), it succeeded without any trouble.

thanks.

**Comment by zrma** [comment]
It succeed in same environment when I changed output binary file name with compiler.

Like this.
$ ./v -o v_temp compiler

Or, not remove compiler file and try again directly, it's not failed.

Like this.
$ ./v -o v compiler
Segmentation fault (core dumped)

// (try again directly, again and again)
$ ./v -o v compiler 
$ ./v -o v compiler 
$ .....
(all succeed)

thanks.

**Comment by vitalyster** [comment]
There is no reason to support old WSL versions

**Comment by nedpals** [comment]
> There is no reason to support old WSL versions
As long as they can build properly, they should. I'm running WSL1 with Ubuntu 16.04 and the build is perfectly fine.

**Comment by zrma** [comment]
> There is no reason to support old WSL versions

The Windows version is fixed by my company policy. The windows version 1709.
My team want to use V instead of golang to little parts at first, so do research about it.
The version 1709 is released to the public on October 17, 2017, is it too old to support?

**Comment by Delta456** [comment]
@zrma Can you give it a try again?

**Comment by zrma** [comment]
@Delta456 

I tried it again, it still have occured.

```bash
/vlang/v$ ./v_temp --version
V 0.1.21 a280e98
/vlang/v$ ./v_temp -o v_temp compiler
V panic: malloc(<0)
./v_temp(+0x378e)[0x7fd14fe0378e]
./v_temp(+0x38ef)[0x7fd14fe038ef]
./v_temp(+0x6126)[0x7fd14fe06126]
./v_temp(+0xa7dd)[0x7fd14fe0a7dd]
./v_temp(+0x11697)[0x7fd14fe11697]
./v_temp(+0x2b22a)[0x7fd14fe2b22a]
./v_temp(+0x29ffc)[0x7fd14fe29ffc]
./v_temp(+0x62152)[0x7fd14fe62152]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7fd14f281b97]
./v_temp(+0x224a)[0x7fd14fe0224a]
[0x7ffff4f464a8]
Segmentation fault (core dumped)
```

Thank you!

**Comment by vitalyster** [comment]
@zrma V works perfectly in native Windows console, no need to use WSL

**Comment by nedpals** [comment]
Closed. This issue has been fixed in the later versions of V.
