### ISSUE TITLE
High-Order Functions

### ISSUE THREAD

**Issue by KsRyY** [vlang/v#1302]
the syntax like:
``` v
a := fn () {}
```
will create a function named `a` that basicly do nothing.

I thought this syntax is sometimes useful to declare function dynamicly.

**Comment by joe-conigliaro** [comment]
I'm pretty this is going to be implemented in some form

**Comment by medvednikov** [comment]
Absolutely.

**Comment by KsRyY** [comment]
OK, thanks.

**Comment by medvednikov** [comment]
This should be open until it's fixed.

**Comment by Delta456** [comment]
V now has High Order Functions

```v
bar := fn () { println("Hello World from High Order Function") }
bar()
```
