### ISSUE TITLE
string.trim() does not work with unicode correctly

### ISSUE THREAD

**Issue by ghost** [vlang/v#13021]
**V version:0.2.4 4b55800** 
**OS:ArchLinux** 

**What did you do?**
```v
fn main(){
	s := 'あいうえお'
	println(s)
	ts := s.trim('あい')
	println(ts)
}
```

**What did you expect to see?**
```
> v run main3.v
あいうえお
うえお
```
 
**What did you see instead?**
```
> v run main3.v
あいうえお
�えお
```

**Comment by yuyi98** [comment]
> trim strips any of the characters given in `cutset` from the start and end of the string.

so we should use trim_prefix().

```vlang
fn main(){
	s := 'あいうえお'
	println(s)
	ts := s.trim_prefix('あい')
	println(ts)
}

PS D:\Test\v\tt1> v run .
あいうえお
うえお
```

**Comment by kahsa** [comment]
hmm.. Alex said since Go handles it correctly, it should be a bug.
Apparently, the rules for handling strings should be the same as for Go.
