### ISSUE TITLE
os.args reports the launching of the application as an argument.

### ISSUE THREAD

**Issue by JDoawp** [vlang/v#13039]
**V version:** V 0.2.4 ba9aad1
**OS:** linux, "Manjaro Linux"

**What did you do?**
println(os.args)
then launch program with arguments "hello" and "world" (no quotes)

**What did you expect to see?**
['hello', 'world']
 
**What did you see instead?**
['./test', 'hello', 'world'] when it's compiled or ['/run/media/jd/HDD/VLang/projects/test/test', 'hello', 'world'] when compiling and running immediately.

Might not be an actual bug but I don't see why it reports its own path/name when it runs as an os.args. It's trivial to work around but it's also kinda dumb since I don't understand why it does what it do :)

**Comment by JalonSolov** [comment]
args[0] is the invocation path of the program in many compiled languages, from C onward (and probably before that).  Even shell scripts on Unix use this convention, though PowerShell on Windows does not.
