### ISSUE TITLE
deprecate arrays.concat

### ISSUE THREAD

**Issue by jeffmikels** [vlang/v#13046]
Currently `arrays.concat` has a signature like this:

`pub fn concat<T>(a []T, b ...T) []T`

but the comment line says it is for concatenating two arrays. Shouldn't it be this?

`pub fn concat<T>(a []T, b []T) []T`

or is there a reason for the original way?

**Comment by JalonSolov** [comment]
Perhaps the comment just needs to be changed?  Depends on what is supposed to happen.  If it is "concatenate 2 arrays" then yes.  Currently, it will concatenate one or more items onto an array.

**Comment by jeffmikels** [comment]
Perhaps we should remove the concat function altogether? Why have two ways to do the same thing?

**Comment by JalonSolov** [comment]
Well, there's that, too.  And that argument makes the most sense.

However, it's probably there for all the FP folks, who do love their method chains...

**Comment by jeffmikels** [comment]
Okay... I hadn't thought of the FP concerns. Let's leave it in.
