### ISSUE TITLE
Defer optional silent fail

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#13068]
**V version:** 0.2.4
**OS:** Linux

Sample project can be found here
[defer_optional.zip](https://github.com/vlang/v/files/7823639/defer_optional.zip)

**What did you do?**

An anonymous function contains a `defer` statement which includes an optional call.
```v
type Callback = fn () ?

fn test_defer() ? {
	test := fn () ? {
		s := Struct{}
		defer {
			s.foo() ?
		}
	}
	//
	do_test(test)
}

fn do_test(cb Callback) {
	cb() or { return }
}

```

I then run the tests.

**What did you expect to see?**

The test to succeed.
Or if error propagation is not allowed inside defer blocks, the following error:
```
error: error propagation not allowed inside `defer` blocks
 ```

**What did you see instead?**

The test silently fail without warning

**Comment by kahsa** [comment]
```
bug.v:7:12: error: error propagation not allowed inside `defer` blocks
    5 |         s := Struct{}
    6 |         defer {
    7 |             s.foo() ?
      |                     ^
    8 |         }
    9 |     }
```

**Comment by duarteroso** [comment]
Confirmed fixed. Closing 👍🏽
