### ISSUE TITLE
Make everything evaluate to a result and remove the need for return

### ISSUE THREAD

**Issue by rockcat** [vlang/v#1306]
I'd like to second an item in issue #74:

3- return keyword is verbose...

I used to code a lot of C and the concept of everything evaluating to something is very powerful - and in line with many modern functional languages.

It would be great if everything in V evaluated to the last calculation - you could lose the return keyword and also add a nice functional feature

**Comment by vertical222** [comment]
This was discuss and decide the return keyword is essential, it's impossible to remove in Go and V code style when it can get more complex.

http://www.rosettacode.org/wiki/Mian-Chowla_sequence#Go

For example, Ruby uses less indentation and more API to make it readable.

**Comment by rockcat** [comment]
I'm not sure why you think  its impossible to remove or why indentation has anything to do with it?

Anyway there are plenty of complex functional languages which do not require the return keyword, you just return whatever is the result of the last calculation - the compiler can check at compile time that all paths return the correct type.

What does the link have to do with it?

**Comment by medvednikov** [comment]
This was already discussed: https://github.com/vlang/v/issues/263
