### ISSUE TITLE
How to use function as variable or arguments?

### ISSUE THREAD

**Issue by ofunc** [vlang/v#131]
```
fn (f fn(int)) {
	f(0)
}
```

ERROR: expected `)` but got `(`

**Comment by medvednikov** [comment]
This is not implemented yet. Later this month.

**Comment by zac-garby** [comment]
Also, not that it's a huge problem, but shouldn't the error say "expected `)` or `,`, but got `(`", since a comma would be valid in that situation?

**Comment by medvednikov** [comment]
Yes, function args errors are very primitive right now.

**Comment by GordonGgx** [comment]
I hope this grammatical feature can be beautiful and concise. ：）

**Comment by ntrel** [comment]
Related: #120

**Comment by medvednikov** [comment]
Fixed in V 0.0.8

```
fn test(f fn (int) int) {
	f(0)
}
```

**Comment by nachoverdon** [comment]
This fails in the playground:

```
fn add(a int, b int) int {
	return a + b
}

fn adder(a int, f fn (int, int) int) {
	return f(a, a)
}

fn main() {
	println(adder(2, add))
}
```


```
test.v:4
expected `)` but got `,`
```

**Comment by medvednikov** [comment]
@nachoverdon fixed.
