### ISSUE TITLE
map.exists() should be public

### ISSUE THREAD

**Issue by donpdonp** [vlang/v#13147]
V's builtin map module is missing a way to test for existence. The closest option currently is to check if `my_map[key]` returns the default value for the map. This breaks down when the default value is one of the possible values used in this map. For example, a scoreboard of names and ints, `score_board[name] == 0` might be a missing player, or it might be an existing player that hasn't scored yet.

**Comment by spaceface777** [comment]
You can use the syntax `key in my_map` to check if `key` exists in `my_map`. That syntax is implemented via the private `exists()` method, and making that public would go against V's "there should only be one way of doing things" principle.

You could also use the `or {}` block syntax to handle missing keys right at the map access site: 
```v
value := my_map['bad_key'] or {
    println('key not found')
    'custom default value'
}`

Both of these are documented [in the map section of the docs](https://github.com/vlang/v/blob/master/doc/docs.md#maps), although we could move the `in` syntax example so that it is more visible.

**Comment by spytheman** [comment]
I also think that a small change to the documentation is more appropriate.

**Comment by donpdonp** [comment]
`in` works for me. I was looking through the builtin module function reference, so I missed it in the regular documentation.
