### ISSUE TITLE
Ability to declare that `struct` implements `interface`

### ISSUE THREAD

**Issue by ChronosX88** [vlang/v#1314]
The syntax may look like this:
`struct Dog : Speaker {}`
Or:  
`struct Dog impl Speaker {}`

This must up readability of code and give to IDEs ability to autocomplete boilerplate code (functions declaration).

**Comment by mvlootman** [comment]
It is a lot more powerful to allow interaction based on implicit interfaces (when a struct satisfies an interface) than to explicitly having to declare that a struct implements an interface. For instance you can use an interface to even use 3rd party structs fir which you might not even have access to code to/are unable to change. 

Coming from C#, this was something I found  really powerful in Go.

**Comment by medvednikov** [comment]
@mvlootman explained this really well.

And if you want to guarantee your type satisfies an interface:

https://golang.org/doc/faq#guarantee_satisfies_interface

**Comment by ChronosX88** [comment]
but... it may be optional...
