### ISSUE TITLE
`str[0..2] or { panic(err) }` unexpected keyword `or`

### ISSUE THREAD

**Issue by kahsa** [vlang/v#13157]
**V version: 0.2.4 7fbd856** 
**OS: ArchLinux** 

**What did you do?**
```
c := str[0..2] or { panic(err) }
```

**What did you expect to see?**
no error like `str[2] or { panic(err) }`
 
**What did you see instead?**
```
main.v:1:16: error: invalid expression: unexpected keyword `or`
    1 | c := str[0..2] or { panic(err) }
      |                ~~
```

**Comment by trueFireblade** [comment]
there's a pending pr for it #13189 . Tho it only is for strings and not for arrays for now.
