### ISSUE TITLE
Flag to turn linting errors into warnings

### ISSUE THREAD

**Issue by Rendims** [vlang/v#1316]
Linters are great tools to increase code quality and I like that V is reporting unused variables for example. But having them as errors can sometimes get in the way of development, especially during debugging.
It would be helpful in such situations to be able to temporarily relax the rules a bit and turn errors into warnings instead.

For example, lets say I have code like this and it is crashing
``` go
y := bar(x)
foo(y)
```

First I remove the `foo()` call to see if that is causing the crash.
``` go
y := bar(x)
//foo(y)
```
This gives me a compiler error instead and I have to remove `y := `.
Then I think `foo()` crashed because of invalid arguments and I test it with a temporary workaround (after reinserting `y := ` again).

```go
mut y := bar(x)
if y<0 {
    y = 0
}
foo(y)
```

And when I have identified the problem and fixed `bar()` I remove my workaround to test my fix.

```go
mut y := bar(x)
if y<0 {
    //y = 0
}
foo(y)
```

What do I get? Compile error, again.

When everything is fixed and I want to commit & push then its great if I have to clean up my empty `if` and unnecessary `mut` but while working with it I prefer if the compiler can allow me to be a bit messy.
A simple `-lints-as-warnings` flag, or whatever a suitable name is, would fix this annoyance.

**Comment by nedpals** [comment]
Compiler warnings have been enabled for non-production builds. Closed.
