### ISSUE TITLE
$ v compiler errors

### ISSUE THREAD

**Issue by Dialga** [vlang/v#13171]
**V version:** latest git
**OS:** Arch Linux x64

**What did you do?**
v3.v
```
#define v
#define 1
```

**What did you expect to see?**
v error, or no error
 
**What did you see instead?**
```
==================
/tmp/v_1000/v.13875890492266535927.tmp.c:687: error: invalid macro name '1'
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by JalonSolov** [comment]
Even if they're small, and seem related, they may not be.  It's always better to have multiple separate issues, than multiple things in a single issue.

**Comment by Dialga** [comment]
> Even if they're small, and seem related, they may not be. It's always better to have multiple separate issues, than multiple things in a single issue.

Sorry, I've separated them out now.

**Comment by medvednikov** [comment]
#define is no longer allowed in user code
