### ISSUE TITLE
bug of scopes

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#132]
may be same bug as #130 

Put follow code into this page https://vlang.io/play
```
fn main() {
        types := ['game', 'web', 'tools', 'GUI']
        for typ in types {
 types2 := types[0]
                println('Hello, $typ developers!')
        }
                println('Hello, $types2')
} 
```
Then I got `You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.`

**Comment by medvednikov** [comment]
Fixed.
