### ISSUE TITLE
vfmt incorrectly makes `const_abc` prefix in C binding separate parameter

### ISSUE THREAD

**Issue by ChewingBever** [vlang/v#13233]
**V version:** V 0.2.4 758d1f4.a291dca
**OS:**  linux, "EndeavourOS Linux"

**What did you do?**
I tried to write a C binding that required taking in a const struct pointer.

`fn C.archive_entry_copy_stat(&C.archive_entry, const_stat &C.stat)`

**What did you expect to see?**

Nothing, just leave this line as is.
 
**What did you see instead?**

vfmt changed the line to
`fn C.archive_entry_copy_stat(&C.archive_entry, const_stat, &C.stat)`
causing the function to be interpreted as having three arguments instead of two.

**Comment by yuyi98** [comment]
There is no problem now.
