### ISSUE TITLE
Hot code reload not working in ubuntu

### ISSUE THREAD

**Issue by pramonow** [vlang/v#1323]
OS version is Ubuntu 16.04, basically running the code reload and nothing happens, below is taken from my console: 

![Screenshot from 2019-07-27 00-40-02](https://user-images.githubusercontent.com/28787057/61970813-bd60ad00-b007-11e9-9203-93f9b9b20322.png)

Not sure what am i doing wrong

**Comment by spytheman** [comment]
1) You have to compile with (you already did that in the second step):
```
v -live message.v
```

2) You have to run the compiled binary:
```
./message
```

3) When the binary is running, try to change the message.v file in your editor, and save it.

**Comment by pramonow** [comment]
Oh rightt, havent tried that yet, thanks!
