### ISSUE TITLE
V compiler can't run from a directory which has a dollar ($) sign in its path

### ISSUE THREAD

**Issue by lacikawiz** [vlang/v#13239]
**V version:**  V 0.2.4 39f8084.d826317
**OS:**  linux, Linux Mint 20.2 (64 bit)

**What did you do?**
Installed `V` in the following directory:  `/home/user/$TMP/2022-01/v` and try to compile the "hello world" example located at: `/home/user/$TMP/2022-01/hello.v` using the command `v/v hello.v`

**What did you expect to see?**
A successful compilation and the creation of the executable file.

**What did you see instead?**
The following error message:
```
==================
sh: 1: /home/user//2022-01/v/thirdparty/tcc/tcc.exe: not found
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```
**Notes**
The `$TMP` portion of the path was evidently replaced with an empty string. 

While this is not common to have `$` in a path, it could certainly happen and could cause some serious head scratching.

**Comment by Rhymond** [comment]
It looks like that 

```
		println('launch_tool vexe        : $vexe')
		println('launch_tool vroot       : $vroot')
		println('launch_tool tool_source : $tool_source')
		println('launch_tool tool_exe    : $tool_exe')
		println('launch_tool tool_args   : $tool_args')
```

path variables in `pub fn launch_tool` (util.v) are not escaped and it causes `v` execution to fail.

I've named v root directory `$(ls -al)` and it executed the command.

```
ray@Ray:~/$(ls -al)/v$ ./v
Welcome to the V REPL (for help with V itself, type  exit , then run  v help ).
  NB: the REPL is highly experimental. For best V experience, use a text editor,
  save your code in a  main.v  file and execute:  v run main.v
launch_tool vexe        : /home/ray/$(ls -al)/v/v
launch_tool vroot       : /home/ray/$(ls -al)/v
launch_tool tool_source : /home/ray/$(ls -al)/v/cmd/tools/vrepl.v
launch_tool tool_exe    : /home/ray/$(ls -al)/v/cmd/tools/vrepl
launch_tool tool_args   :
launch_tool should_compile: true
Compiling vrepl with: ""/home/ray/$(ls -al)/v/v" -skip-unused "/home/ray/$(ls -al)/v/cmd/tools/vrepl.v""
failed    cmd: "/home/ray/$(ls -al)/v/v" -skip-unused "/home/ray/$(ls -al)/v/cmd/tools/vrepl.v"
failed   code: 2
sh: 1: /home/ray/total 3764
drwxr-xr-x 12 ray ray    4096 Jan 21 20:26 .
drwxr-xr-x  3 ray ray    4096 Jan 21 20:05 ..
-rw-r--r--  1 ray ray    3500 Jan 21 20:05 .cirrus.yml
drwxr-xr-x  2 ray ray    4096 Jan 21 20:05 .ctags.d
-rw-r--r--  1 ray ray     584 Jan 21 20:05 .editorconfig
drwxr-xr-x  8 ray ray    4096 Jan 21 20:05 .git
-rw-r--r--  1 ray ray     170 Jan 21 20:05 .gitattributes
drwxr-xr-x  4 ray ray    4096 Jan 21 20:05 .github
-rw-r--r--  1 ray ray    1155 Jan 21 20:05 .gitignore
-rw-r--r--  1 ray ray   23677 Jan 21 20:05 CHANGELOG.md
-rw-r--r--  1 ray ray      44 Jan 21 20:05 CODE_OF_CONDUCT.md
-rw-r--r--  1 ray ray    8950 Jan 21 20:05 CONTRIBUTING.md
-rw-r--r--  1 ray ray     668 Jan 21 20:05 Dockerfile
-rw-r--r--  1 ray ray     775 Jan 21 20:05 Dockerfile.alpine
-rw-r--r--  1 ray ray     258 Jan 21 20:05 Dockerfile.cross
-rw-r--r--  1 ray ray    3633 Jan 21 20:05 GNUmakefile
```

Is it only `$` which cause this issue? Or is there more characters we need to escape? Same question for Windows?

**Comment by JalonSolov** [comment]
It's more likely the shell trying to replace that part of the path with the value of an environment variable.  For your original example, try creating and environment variable named `TMP` and set the value to `PMT`, and I'll bet the paths in your first example will have `/PMT/` where they currently have `//`.

In other words, it's a bad idea to use shell characters in path names.  We may be able to make V handle it, but you'll still have problems with other programs.

**Comment by JalonSolov** [comment]
As for Windows, it likely depends on which shell you use there, CMD vs PowerShell vs ... whatever.

**Comment by lacikawiz** [comment]
Thanks for taking a look! I am aware that having a dollar sign in the path is not the best idea. But I set up my temp folder that way about 2 years ago and I had surprisingly small amount of issue ever arising from the dollar sign being there. So it stayed that way.

It seems that the vast majority of programs have no problem running in, opening files from this folder, so I thought that ones that fail should be notified about it. It's a rare case but it can happen because Linux, Windows, MacOS has no rule against using the dollar sign in directory and file names.

**Comment by JalonSolov** [comment]
Can you verify that setting an env var named `TMP` to something causes that value to show up in the path?  Just to satisfy my curiosity that it is what is going on.

V can of course be changed to quote/escape/whatever common shell characters like `$`, I just think you'll still have problems with other tools.  It's also "fragile", in that if you try another shell that uses a different character for something special, V and everything else could break even after the change is made.

**Comment by lacikawiz** [comment]
Great! I updated `V` and tested on my `$TMP` and it's working perfectly now!
