### ISSUE TITLE
`v fmt` inserts `.` before const value.

### ISSUE THREAD

**Issue by kahsa** [vlang/v#13243]
**V version: 0.2.4 ffb263c** 
**OS: ArchLinux** 

**What did you do?**
https://github.com/vlang/ui/blob/37673450853a8058f8159506687f670157df39f9/widget_button.v#L351

remove prefix `ui.` from that const.

```
		} else {
			button_border_color
		})
```
then `v fmt -w widget_button.v`

**What did you expect to see?**
No change
```
		} else {
			button_border_color
		})
``` 
**What did you see instead?**
```
		} else {
			.button_border_color
		})
```
`v fmt` inserts `.` before const `button_border_color` then `.button_border_color`.

**Comment by Na-r** [comment]
I'm also on Arch Linux but was unable to reproduce this. Running `v fmt` prefixes the constant with `ui.`, which is intended behavior based off of the [docs](https://github.com/vlang/v/blob/master/doc/docs.md#required-module-prefix).
![image](https://user-images.githubusercontent.com/37783605/150621762-3c840714-d957-411f-a7cd-cdf0ed982eb1.png)

**Comment by kahsa** [comment]
Thanks for testing.

Hmm.. I tried it again and... with `V 0.2.4 ffb263c`
![範囲を選択_039](https://user-images.githubusercontent.com/52106048/150622689-cc3288ce-57b6-45e6-b5ef-c46b50234791.png)

**Comment by kahsa** [comment]
https://github.com/vlang/v/blob/master/doc/docs.md#required-module-pref

Is this specification still alive?
I think they've been changed.

**Comment by JalonSolov** [comment]
It doesn't do that for me on Manjaro Linux
```
[jamie@5950x ~]$ v fmt -w widget_button.v
Already formatted file: /home/jamie/widget_button.v
[jamie@5950x ~]$ v version
V 0.2.4 2b4f7e7
[jamie@5950x ~]$
```
Looking at line 351, it still has the `ui.` prefix, as it should.

**Comment by kahsa** [comment]
Apparently, the cause is that the `ui` was not placed in `.vmodule/`, but was linked elsewhere.

Thank for your testing.
