### ISSUE TITLE
This go statement use case caused a'builder error'

### ISSUE THREAD

**Issue by tzSharing** [vlang/v#13247]
**V version:** 
![20220122142231](https://user-images.githubusercontent.com/90680948/150628102-039c4e3c-1771-4548-851f-11109d28f0ad.jpg)

**What did you do?**
```
const text ='Hello world'
fn main(){
	hex :=text.bytes().hex()
	println(hex)
	
	bytes :=go text.bytes()
	println(bytes.wait())
	
	//hex_go :=go text.bytes().hex()
	//println(hex_go.wait())
}
```
![20220122142701](https://user-images.githubusercontent.com/90680948/150628172-7888086a-f6b9-4a9b-99cc-c63298b7f078.jpg)

```
const text ='Hello world'
fn main(){
	// hex :=text.bytes().hex()
	// println(hex)
	
	// bytes :=go text.bytes()
	// println(bytes.wait())
	
	hex_go :=go text.bytes().hex()
	println(hex_go.wait())
}
```
![20220122142818](https://user-images.githubusercontent.com/90680948/150628246-eec3038e-e6de-4f9a-be05-69be447762ea.jpg)

**What did you expect to see?**
```
const text ='Hello world'
 fn test_hex(){
        hex := text.bytes().hex()
	hex_go :=go text.bytes().hex()
	assert hex == hex_go.wait()
}
```

**Comment by JalonSolov** [comment]
The C output around that line looks like the following, with the problem line in bold.  V seems to be creating a variable name with `[]` embedded?  Definitely a problem.

// END_multi_return_structs


**typedef struct thread_arg_[]byte_hex {**
        Array_byte arg0;
EMPTY_STRUCT_DECLARATION;
} thread_arg_[]byte_hex;
void* []byte_hex_thread_wrapper(thread_arg_[]byte_hex *arg);

**Comment by Delta456** [comment]
Should this be the intended output? @tzSharing, if so then I will PR this later.

![image](https://user-images.githubusercontent.com/28479139/189482554-ed39fa79-7faa-4553-9473-d3f83c62957a.png)
