### ISSUE TITLE
if <error> should work for tuples

### ISSUE THREAD

**Issue by knarkzel** [vlang/v#13249]
Following code fails to compile:
```v
fn create() ?(int, int) {
	return 5, 10
}

fn main() {
	if foo := create() {
		println(foo)
	}
	if foo, bar := create() {
                println(foo)
                println(bar)
	}
}
```
The first one compiles and prints `(5, 10)` while the second one fails to compile with following:
```bash
./bug.v:9:8: error: unexpected token `,`, expecting `{`
    7 |         println(foo)
    8 |     }
    9 |     if foo, bar := create() {
      |           ^
   10 |         println(foo)
   11 |         println(bar)
```

**Comment by spytheman** [comment]
For a function `fn opt2() ?(int, int) {`
`if x := opt2() {` -> should be a compiler error
`if x,y := opt2() {` -> should work (it does not currently)
`if x,y,z := opt2() {` -> should be a compiler error too
