### ISSUE TITLE
Code that cannot be compiled due to a C error

### ISSUE THREAD

**Issue by Hayao0819** [vlang/v#13262]
```
OS: macos, macOS, 12.1, 21C52
Processor: 8 cpus, 64bit, little endian, Apple M1
CC version: Apple clang version 13.0.0 (clang-1300.0.29.30)

getwd: /Users/hayao/Documents/LearnVLang
vmodules: /Users/hayao/.vmodules
vroot: /opt/homebrew/Cellar/vlang/0.2.4/libexec
vexe: /opt/homebrew/Cellar/vlang/0.2.4/libexec/v
vexe mtime: 2022-01-23 15:52:27
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 34f0d44

Git version: git version 2.34.1
Git vroot status: weekly.2022.03-49-g34f0d442 (4 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-macos-arm64 01a49770
```

**What did you do?**
I wrote following code.

Compares the strings variable character by character to the array.
If the character is included, the character is output.

```vlang
mut array := []string{}

array << "e"
mut strings := "hfs"

for mut s in strings.split(""){
	if s in array{
		println("Hello")
	}
}
```

**What did you expect to see?**
V should output nothing.

 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/32128205/150766022-354477a0-677c-414b-b14c-f7a1579b2530.png)

**Comment by Hayao0819** [comment]
Additional Information
It worked by removing the mut in the for statement.
But this error is still strange.

**Comment by stmkza** [comment]
This is a smaller code that produces the same error.
```v
array := ['e']
mut splited := ['h', 'f', 's']

for mut s in splited {
	if s in array {
		println('Hello')
	}
}
```

In generated C source code `main__main` function, `Array_string_contains(Array_string, string*)` is called.
But, `Array_string_contains(Array_string, string)` is defined.
