### ISSUE TITLE
sumtype: cannot cast a map value

### ISSUE THREAD

**Issue by Hunam6** [vlang/v#13297]
```
OS: macos, macOS, 12.1, 21C52
Processor: 8 cpus, 64bit, little endian, Apple M1
CC version: Apple clang version 13.0.0 (clang-1300.0.29.30)

getwd: /Users/hunam/Documents/dev/go2v
vmodules: /Users/hunam/.vmodules
vroot: /Applications/v
vexe: /Applications/v/v
vexe mtime: 2022-01-27 15:11:15
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 36c9ed6.daa5be4

Git version: git version 2.32.0 (Apple Git-132)
Git vroot status: weekly.2022.04-33-gdaa5be4c
.git/config present: true
thirdparty/tcc status: thirdparty-unknown-unknown de82a130
```

**What did you do?**
```v
type Foo = Bar | string

struct Bar {
mut:
	ok int
}

fn main() {
	mut foo := map[string]Foo{}
	foo['b'] = Bar{}
	(foo['b'] as Bar).ok = 1
}
```

**What did you expect to see?**
no error
 
**What did you see instead?**
```v
report2.v:10:12: error: unexpected expression `v.ast.AsCast`
    8 | fn main() {
    9 |     mut foo := map[string]Foo{}
   10 |     (foo['b'] as Bar).ok = 1
      |               ~~
   11 | }
```

**Comment by Hunam6** [comment]
@yuyi98 👀
One last bit ^^

**Comment by yuyi98** [comment]
> (foo['b'] as Bar).ok = 1

That's not the right way to use it.

```vlang
type Foo = Bar | string

struct Bar {
mut:
	ok int
}

fn main() {
	mut foo := map[string]Foo{}
	if ret := foo['b'] {
		if ret is Bar {
			mut a := ret as Bar
			a.ok = 1
		} else {
			println('error')
		}
	}
}

```

**Comment by Hunam6** [comment]
I'm sorry but I don't understand, in your examples foo doesn't change. Maybe I wasn't clear, let me try to explain differently:

First I slightly updated my example, I forgot a line when doing the minimal reproduction example.
I want to do this `foo['b'].ok = 1` but it isn't possible in all sumtype variants as V tells me well.
![Screenshot 2022-01-27 at 17 22 08](https://user-images.githubusercontent.com/38606542/151399941-469ffa90-14b7-4fdb-8ad9-ce0cf736c6cc.png)
so I insert `as` to cast the sumtype into Bar. I do it directly because in the context of my real world usage I know for sure that it will always be Bar.

**Comment by yuyi98** [comment]
Why not directly assign Bar{ok: 1}?

```vlang
type Foo = Bar | string

struct Bar {
mut:
	ok int
}

fn main() {
	mut foo := map[string]Foo{}
	foo['a'] = Bar{ok: 1}
	println(foo)
}
```

**Comment by Hunam6** [comment]
Oh wait I think you're right, sorry for the inconvenience and thank you for your time!
