### ISSUE TITLE
all examples in `docs.md` should work.

### ISSUE THREAD

**Issue by kahsa** [vlang/v#13305]
I want all the examples in `docs.md` to be executable.

The ones that don't work seem to be marked as `oksyntax`, but that should be clear to HTML readers.

**Comment by JalonSolov** [comment]
All _complete_ examples are checked.  Ones marked with `oksyntax` are incomplete, just to show how to do a particular thing, and are not expected to be executable by themselves.

**Comment by kahsa** [comment]
Looks like so.
Then, how about if we put a name or a number (or whatever it's called in English) on all the examples, so that we can see which of the split examples is connected to which?
