### ISSUE TITLE
Static Variables For Functions

### ISSUE THREAD

**Issue by Wajinn** [vlang/v#13356]
Since V doesn't recommend global variables (as is special use), there are situations where functions need to remember values between calls.  Such static variables could only be declared **inside the body** of a function, not outside of them.  This would also reduce the number of situations where global variables are needed and keep the bulk of necessary logic inside of functions without resorting to odd workarounds.

Perhaps static variables could be designated with `sta` in front of it and would automatically be mutable.

**Comment by JalonSolov** [comment]
V supports a `static` keyword, which works exactly the same as the `static` keyword in C.

**Comment by Wajinn** [comment]
> V supports a `static` keyword, which works exactly the same as the `static` keyword in C.

None of the documentation that I have seen shows an example of its usage in V, outside of specifying it as a keyword.  When attempting to use it, it would simply not work.  The variable designated as unsafe and static, didn't remember its value between calls.  

Can you show an example of it working in V?
