### ISSUE TITLE
unused variables should not be allowed

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#134]
Put follow code into this page https://vlang.io/play
```
fn main() {
	types := ['game', 'web', 'tools', 'GUI']
	mut types2 := types[0]
	for typ in types {
		println('Hello, $typ developers!')
	}
}
```
The program run successfully.

I think the compiler should say that `unused variable types2`
If a variable is only defined, but not read, the compiler should report an error to prevent the programer write the wrong variable name. (like golang)

**Comment by medvednikov** [comment]
Agreed. This is a big change, will do this later.

**Comment by medvednikov** [comment]
Fixed:

```
`types2` declared and not used 
```

**Comment by ntrel** [comment]
I think this should be a warning, not an error - compilation should continue. IMO giving an error discourages the programmer from compiling code before it's ready to test. Compiling regularly whilst developing code is a good way to catch errors early. As an error the programmer is forced to comment out code or add a `println` for any unused variables, which is awkward.

**Comment by bronze1man** [comment]
The compiler error `declared and not used` had found a lot of bugs in my golang code.
Some of bugs looks like the code is only code part , and forget to write the remain part. Forget to write some part of the code is always a bug...
The compiler can find more abnormal things, the more bugs may be found because of abnormal things.
It is always good to find bug earlier and by compiler.
If you do not want the code, just comment them out to tell the compiler that you do not need it.

**Comment by ntrel** [comment]
> The compiler error declared and not used had found a lot of bugs in my golang code

A warning (on by default) would find them too.

> If you do not want the code,

I want to see if an expression assigned to an unused variable compiles.

> just comment them out to tell the compiler that you do not need it

Beside my use case above, commenting out that line then likely means another variable becomes unused. It is awkward.
