### ISSUE TITLE
I propose to translate docs.md into Ukrainian and Russian.

### ISSUE THREAD

**Issue by ZaViBiS** [vlang/v#13410]
the title says it all.

**Comment by spytheman** [comment]
On one hand, that will be good for Ukrainians and Russians, that do not know English. 

On the other, that would make maintenance more difficult, especially if there other translations follow too. 
The file docs.md, contains code samples for example, that are currently checked, and several separate translations, will mean having to keep up, several slightly different copies of the same code in sync.

I do not know whether the positives are bigger than the negatives.

**Comment by ZaViBiS** [comment]
What do people who don't know English do?
what is the complexity of maintenance? in any case, there will hardly be more changes to docs.md, so it won't take long to synchronize each language.

@spytheman

**Comment by JalonSolov** [comment]
Actually, there should be quite a few changes to docs.md, hopefully starting soon. See https://github.com/vlang/v/discussions/13378 for the current discussion.  Every change to the English version of doc.md will require changes to every other language version of docs.md, which means the complexity of making any changes goes up with every translation.

It would make more sense to at least wait until the 0.3 release... possibly the 1.0 release... before creating translated versions of the docs.

**Comment by spytheman** [comment]
Option 1 - can not happen; it is very hard to coordinate changes like that
Option 2 - the basic language is English.
Option 3 - more maintenance burden for everyone that has to document anything or restructure things.

**Comment by spytheman** [comment]
@medvednikov what do you think, is it time to freeze `doc/docs.md`, so that it can be translated to other human languages?

**Comment by spytheman** [comment]
> I'd prefer to get at least some of the suggestions from the discussion thread incorporated before "freezing".

me too

**Comment by ArtemkaKun** [comment]
I'm a native of Ukrainian and can help, however, I can't find any sense in translating V or whatever, related to IT, into Ukrainian or another language.

IT - it's a territory of the English language since the English language is international. I see no sense to have different documentation versions even if the documentation is stable. If a person goes into IT and doesn't know English (at least nowadays) - this is like playing Dark Souls on bananas - possible, but very very very hard.

**Comment by ArtemkaKun** [comment]
I think if you want to help V - this will be much more effective to share your feelings about V or create a tutorial post in Ukrainian/Russian in the Ukrainian/Russian part of the Internet.
I know a few of them - Habr, Pikabu, Ebanoje IT, but maybe you know more.

**Comment by JalonSolov** [comment]
Possibly translate the blog posts on https://blog.vlang.io instead.  @hungrybluedev should be able to tell us if an alternate language version of those posts could be put on the same site.

**Comment by hungrybluedev** [comment]
> Possibly translate the blog posts on https://blog.vlang.io instead.  @hungrybluedev should be able to tell us if an alternate language version of those posts could be put on the same site.

They can be. Hugo supports that. But as I've mentioned before on Discord, the main difficulty will be in attracting volunteers who will perform proofreading. We cannot rely on translation software alone. If there's enough interest, I can change the structure of the blog to support multiple languages.
