### ISSUE TITLE
Array prepend

### ISSUE THREAD

**Issue by r-k-o** [vlang/v#1343]
hi, 
it would be very helpful to have an array prepend.
for example from the documentation append:

> mut nums := [1, 2, 3]
> nums << 4
> println(nums) // "[1, 2, 3, 4]

a prepend could be done this way maybe:

> mut nums := [1, 2, 3]
> nums >> 4
> println(nums) // "[4, 1, 2, 3]

thanks

**Comment by medvednikov** [comment]
You can already do that: `nums.prepend(4)`.

There won't be a special operator for this.
