### ISSUE TITLE
`fn foo(mut [a, b, c]){}` should be allowed.

### ISSUE THREAD

**Issue by kahsa** [vlang/v#13448]
**V version: 0.2.4 ae0e90f** 
**OS: ArchLinux** 

**What did you do?**
```v
fn foo(mut arr []int){}

fn main(){
    foo(mut [1,2,3])
}
```
If this is not a but, then feature request.

**What did you expect to see?**
No error.
 
**What did you see instead?**
```
main.v:4:13: error: array literal can not be modified
    2 | 
    3 | fn main(){
    4 |     foo(mut [1,2,3])
      |             ~~~~~~~
    5 | }
```

**Comment by kahsa** [comment]
useful like in this case
```v
interface Widget{
mut:
    init()
}

struct Button{}
fn (mut b Button) init(){}

struct Label{}
fn (mut l Label) init(){}

struct Window{
mut:
    widgets []Widget
}

fn (mut w Window) add_all(mut widgets []Widget){
    for mut wd in widgets{
        wd.init()
        w.widgets << wd
    }
}

fn main(){
    mut win := Window{}
    mut btn := Button{}
    mut lbl := Label{}
    // mut arr := []Widget{}
    // arr << btn
    // arr << lbl
    // win.add_all(mut &arr)
    win.add_all(mut [btn, lbl])
    dump(win)
}
```

**Comment by vincenzopalazzo** [comment]
your code compile

```
fn foo(mut arr []int){}

fn main(){
    mut arr := [1, 2, 3]
    foo(mut arr)
}
```

This is illegal also in C++, and not sure if we need to admit this type of code to be compiled.

**Comment by kahsa** [comment]
You are missing my point.
I know that this works.

	mut arr := []Widget{}
	arr << btn
	arr << lbl
	win.add_all(mut arr)

ok, real code I show to you.

fn main(){
	mut app := &App{
		window: window.new()
		btn: button.new('Button', fn(e &gg.Event, b &button.Button){
			mut app := &App(b.get_state())
			app.num++
			app.tv.set_text(app.num.str())
		})
		tv: textview.new('TextView')
		dd: dropdown.new()
		r: radio.new(fn(index int, value string, r &radio.Radio){
			mut app := &App(r.get_state())
			app.tv.set_text(value)
		},'A', 'B')	
		lv: listview.new()		
	}
	app.window.set_state(app)

	mut ll := layout.linearlayout(.vertical, .fit)
	app.window.add(ll)
	mut lltop := layout.linearlayout(.horizontal, .stay)
	lltop.set_size(300, 20)
	ll.add(lltop)
	lltop.add(app.tv)
	lltop.add(app.btn)
	lltop.add(app.r)
	ll.add(app.dd)
	ll.add(app.lv)

	// lv.set_size_type(.fit)
	for i in 0..10{
		app.lv.add(i.str())
	}
	// app.lv.set_onselect(fn(){
	// })
	
	app.window.run()
}

a lot of ll.add() ll.add() ll.add() ll.add()........... many times.
but add_all() is one time, ll.add_all(mut [btn, lbl, rb, lv.......])
you are code is still require a lot of works.
Nothing has changed, has it?

**Comment by kahsa** [comment]
And what is the reason that you close this?

**Comment by vincenzopalazzo** [comment]
>And what is the reason that you close this?

The main reason you are asking to change the syntax is that your application of V it is a little bit difficult, without any good reason.

>If you want to talk about C++, go to C++.

I go with C++ for sure, but I stay with V too, I can't?

IMO your example shows that V is leaking right now the possibility to declare an array of struct inline, so we don't need to accept your change request, but we need to allow inline declaration!

Reopened, and hope someone will help you

**Comment by spytheman** [comment]
@kahsa, use:
```v
    mut x := [Widget(btn), Widget(lbl)]
    win.add_all(mut x)
```

**Comment by spytheman** [comment]
```v
fn (mut w Window) add_all(widgets []Widget){
    for wd in widgets{
        unsafe { wd.init() }
        w.widgets << wd
    }
}
```
... and later:
```v
 win.add_all([btn, lbl])
 ```
 also works.

**Comment by JalonSolov** [comment]
No, his first example didn't use `unsafe`.  `unsafe` should always be the _last_ choice.

**Comment by kahsa** [comment]
It doesn't matter if it's last or not, as long as I can write convenient way.

**Comment by kahsa** [comment]
Wow! Now I can do favorite "Variable number of arguments"
```v
pub fn (mut cb ContainerBase) add_all(layoutables ...Layoutable){
	for l in layoutables{
		unsafe{ l.set_parent(cb) } // mutを回避する手段
		cb.layoutables << l
	}
}
```
