### ISSUE TITLE
Make an AUR package to install Vlang in arch 

### ISSUE THREAD

**Issue by thisisshub** [vlang/v#1344]
I was thinking of building an AUR package. I am a beginner and I was hoping to learn by PKGBUILD a vlang for easier installation. Any feedback is appreciated.

**Comment by medvednikov** [comment]
There's already a package maintained by @whoizit 

I'll add it to README.

**Comment by thisisshub** [comment]
thanks!

**Comment by medvednikov** [comment]
@thisisshub https://aur.archlinux.org/packages/vlang/

**Comment by thisisshub** [comment]
> @thisisshub https://aur.archlinux.org/packages/vlang/

Thanks a lot. @medvednikov
