### ISSUE TITLE
V Doesn't Give Handle Of File

### ISSUE THREAD

**Issue by Wajinn** [vlang/v#13445]
**What did you do?**

Tried to get handle of file by using:

`os.get_file_handle()`

and by using the below, which is contained in builtin/cfns... 

`C.CreateFile(lpFilename &u16, dwDesiredAccess u32, dwShareMode u32, lpSecurityAttributes &u16, dwCreationDisposition u32, dwFlagsAndAttributes u32, hTemplateFile voidptr) voidptr`

**What did you expect to see?**

The handle to the file
 
**What did you see instead?**

Usage of either results in system errors in the 200 range for the Windows OS (8.1 and 10), often like, "The segment is locked and cannot be reallocated."

It appears the file handle is not being given to the user, and is being used or blocked by V in some way.

**Comment by vincenzopalazzo** [comment]
Can you provide a minimal example to reproduce it easily?

Thanks

**Comment by Wajinn** [comment]
> Can you provide a minimal example to reproduce it easily?
> 
> Thanks

It's a bit simple.  On Windows, we should be getting the handle to the file, instead get a system error in the 200 series.  The int is because os.get_file_handle() gives back the result in hex.

`println(int(os.get_file_handle('X:/Tests/TEST_5.png')))`

error is `212`

**Comment by kahsa** [comment]
Please provide concrete code that actually causes the bug, not just a verbal description.
This is called a minimal reproducible sample.
That way, others can easily reproduce the error you experienced.
Please refer to other bug reports and write them in the same way.

**Comment by Ekopalypse** [comment]
@Wajinn - why do you think this is a bug and the returned value is an error code?
From my point of view, the method does what it is supposed to do BUT I am not sure if it is the method you want/should call in the first place.

**Comment by Wajinn** [comment]
There is nothing else to give.  It's not V crashing, but rather it's not returning a handle, but system error (as I have given what it is).

How about this.  If I'm incorrect, then what should `os.get_file_handle()` be returning?  Has anybody used it?  What did you get in return?

**Comment by Wajinn** [comment]
Thanks for the responses.  The issue is resolved and due to incorrect usage.
