### ISSUE TITLE
Compiler Bug: Using test_ for a function name outside of a test file

### ISSUE THREAD

**Issue by winstonpuckett** [vlang/v#13443]
**V full version: V 0.2.4 4ef7d26** 
**OS: windows, Microsoft Windows 11 Home v22000 64-bit** 

```v
// In main.v
fn main () { }
fn test_any (any_name int) int {
	return 0
}
```

```v
// In any_test.v
module main
fn test_any_name() {}
```

**What did you do?**

Steps to reproduce:
1. Create the main.v file with the above input
2. Create the any_test.v file with the above input
3. Run "v -cg test ."

Description:
While creating an automation program, I tried to name a method test_endpoint, which is not a v test, but a runnable method in the main.v file.

I then proceeded to run the unit tests against it. As I understand it, "module main" is not usually required for a unit test file, but the _test.v file couldn't see the function, so I tried importing it.

Note:
The important parts are
- "module main" in any_test.v
- The fact that test_any has a parameter in main.v

**What did you expect to see?**

Either a nice error message telling me that I cannot name a function "test_" outside of a file named "_test.v" or, in the reproduceable steps, a message that says 1 Passed.
 
**What did you see instead?**
```
$ v -cg test .
---- Testing... ---------------------
 FAIL   540.187 ms C:/*****/*******/source/Repos/vplay/doesntwork/any_test.v
C:/*****/*******/AppData/Local/Temp/v/test_session_108487700/any_test.exe.12831175287143655976.tmp.c:508: warning: WINVER redefined
C:/*****/*******/AppData/Local/Temp/v/test_session_108487700/any_test.exe.12831175287143655976.tmp.c:7146: warning: implicit declaration of function 'tcc_backtrace'
C:/*****/*******/AppData/Local/Temp/v/test_session_108487700/any_test.exe.12831175287143655976.tmp.c:7765: warning: assignment from incompatible pointer type
C:/*****/*******/AppData/Local/Temp/v/test_session_108487700/any_test.exe.12831175287143655976.tmp.c:7765: warning: assignment makes pointer from integer without a cast
C:/*****/*******/AppData/Local/Temp/v/test_session_108487700/any_test.exe.12831175287143655976.tmp.c:7765: warning: cast between pointer and integer of different size
C:/*****/*******/AppData/Local/Temp/v/test_session_108487700/any_test.exe.128311752871436559
C:/*****/*******/AppData/Local/Temp/v/test_session_108487700/any_test.exe.12831175287143655976.tmp.c:16048: warning: assignment from incompatible pointer type
C:/*****/*******/AppData/Local/Temp/v/test_session_108487700/any_test.exe.12831175287143655976.tmp.c:17412: error: too few arguments to functionbuilder error:==================
C error. This should never happen.
This is a compiler bug, please report it using `v bug file.v`.
https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
-------------------------------------Failed command 1:    "C:\*****\*******\v\v.exe" -cg  -o "C:\*****\*******\AppData\Local\Temp\v\test_session_108487700\any_test.exe" "C:\*****\*******\source\Repos\vplay\doesntwork\any_test.v"
Summary for all V _test.v files: 1 failed, 1 total. Runtime: 542 ms, on 1 job.
```

**Comment by spytheman** [comment]
With latest V:
![image](https://user-images.githubusercontent.com/26967/153718582-27a8e538-d677-4f20-b38a-3c33aaef2210.png)

**Comment by winstonpuckett** [comment]
That's very interesting. I had cloned the v repo hours before. Thank you :)

**Comment by spytheman** [comment]
> 0.2.4 is still the latest release. Is there also the main.v file as described with a test_ function which has at least one parameter and a return type?

No, it is not - V uses a weekly release cycle currently, but you can also update your V copy with `v up` (which is highly recommended, if you want to test bug fixes).

**Comment by spytheman** [comment]
> Is there also the main.v file

yes, see: https://github.com/vlang/v/blob/799c95dc4e7588aa3dd8a51515a0f6ef7cfeac34/vlib/v/tests/run_project_folders/issue_13443_test_prefixed_fns_in_normal_v_files/main.v

**Comment by winstonpuckett** [comment]
Oh interesting. Well thank you for the quick response. :)
