### ISSUE TITLE
XML, SOAP, WEB server support

### ISSUE THREAD

**Issue by boumboum** [vlang/v#1349]
Hi,

Great project!
But do you plan to implement native XML support (performant XML parsing and creating) with maybe xpath support?
Same question for SOAP support (as the enterprise world is still heavily using it) for client and server?
And also will there be any (micro or full featured) web server for V (with HTML templates, REST APIs, authentication and authorisation, etc.)?

**Comment by joe-conigliaro** [comment]
hi @boumboum yes a native XML parser is something that is definitely going to be implemented. I have already started work on this.

**Comment by spytheman** [comment]
What do you mean by native XML? A V xml library module, or parsing XML embedded in .v files?

**Comment by joe-conigliaro** [comment]
@spytheman I assumed he means a native implementation with no dependencies

**Comment by boumboum** [comment]
A native V xml module, like you have it for json.
I'm actually using Pythons lxml package, which is really high performance (actually twice as fast as golang's encoding/xml module.
As I've said, V looks very promising but IMHO in order to be accepted by a large community it will need very performant features like:
JSON, 

- CSV, Excel, XML, etc. handling (creating, parsing, searching etc.)
- web server capabilities (see that list: [https://www.techempower.com/benchmarks/](https://www.techempower.com/benchmarks/)
- some numerical and dataframe processing (like Python pandas)
- for me SOAP is very important including base64 handling (encoding/decoding)
- database drivers (PG, mysql, MSSQL, Oracle, sqlite, ...)
- etc.

The goal would be to have a single executable with all those features

**Comment by joe-conigliaro** [comment]
I had a different definition of native, The json module depends on a C lib, so I wouldn't really call it native to v. but that's just me 🐰

**Comment by boumboum** [comment]
Well, as long as it can be linked to the final executable, it doesn't matter...
Of course it would be "nicer" if everything in V would be written in V, but never mind... :-)

**Comment by joe-conigliaro** [comment]
😃

**Comment by joe-conigliaro** [comment]
V is in early stages, but it's moving at a fast pace, new things are getting built every day/week so All those things will come!

**Comment by medvednikov** [comment]
The web server is out.

**Comment by keito940** [comment]
...And TOML And YAML And MsgPack And  [SION](https://dankogai.github.io/SION/) Native Support.

**Comment by dumblob** [comment]
There is a discussion about formats (parsing/serialization/marshalling/...) in https://github.com/vlang/v/issues/1732 .

**Comment by nedpals** [comment]
Duplicate of #1732
