### ISSUE TITLE
Missing documentation how to create n-dimensional array of structs

### ISSUE THREAD

**Issue by StefanSchroeder** [vlang/v#13499]
According to docs.md a three-dimensional array can be created like this:

> mut a := [][][]int{len: 2, init: [][]int{len: 3, init: []int{len: 2}}}
> a[0][1][1] = 2
> println(a) // [[[0, 0], [0, 2], [0, 0]], [[0, 0], [0, 0], [0, 0]]]

That's great.

But how do I create a 3-d matrix of non-integer type?
> struct Dot { 
>    a f64
>    b f64
>  }   
How do you modify this declaration (taken from above), so 
that the next two lines would work?
> mut a := [][][]int{len: 2, init: [][]int{len: 3, init: []int{len: 2}}}
> a[0][1][1] = Dot{ 0.33, 0.66 }
Expected output:
> println(a) // [[[{ 0, 0 }, { 0, 0 }], [{ 0, 0 }, { 0.33, 0.66 }], [{ 0, 0 }, { 0, 0 }]], [[{ 0, 0 }, { 0, 0 }], [{ 0, 0 }, { 0, 0 }], [{ 0, 0 }, { 0, 0 }]]]

If help is offered, I am willing to provide a documentation snippet for the manual! 

TIA
Stefan

**Comment by splace** [comment]
Doesn’t just replacing all “int” with “dot” work?

**Comment by JalonSolov** [comment]
Yup.
```v
struct Dot {
mut:
        a f64
        b f64
}

mut a := [][][]Dot{len: 2, init: [][]Dot{len: 3, init: []Dot{len: 2}}}
a[0][1][1].b = 2
println(a) // [[[0, 0], [0, 2], [0, 0]], [[0, 0], [0, 0], [0, 0]]]
```
```
$ v run foo.v
[[[Dot{
    a: 0
    b: 0
}, Dot{
    a: 0
    b: 0
}], [Dot{
    a: 0
    b: 0
}, Dot{
    a: 0
    b: 2
}], [Dot{
    a: 0
    b: 0
}, Dot{
    a: 0
    b: 0
}]], [[Dot{
    a: 0
    b: 0
}, Dot{
    a: 0
    b: 0
}], [Dot{
    a: 0
    b: 0
}, Dot{
    a: 0
    b: 0
}], [Dot{
    a: 0
    b: 0
}, Dot{
    a: 0
    b: 0
}]]]
$
```

**Comment by StefanSchroeder** [comment]
This does indeed work. Thank you.
