### ISSUE TITLE
Optional explicit declaration of support for an interface

### ISSUE THREAD

**Issue by gcxfd** [vlang/v#13526]
Optional explicit declaration of support for an interface

I found out that the udp interface of vlang now can't get the real port assigned when the port is bound to 0.

Then I looked at the source code and I found that net/tcp.v already has a function like this

```
// address gets the address of a socket
pub fn (s &TcpSocket) address() ?Addr {
  return addr_from_socket_handle(s.handle)
}
```

So I copied the code and submitted a pull request to https://github.com/vlang/v/pull/13524/files
```
// address gets the address of a socket
pub fn (s &UdpSocket) address() ?Addr {
  return addr_from_socket_handle(s.handle)
}
```

I don't like copying code because it goes against the principle of one definition.

The address function is common to both UdpSocket and TcpSocket. There are probably some other functions that are public to them, and it's ugly to implement one and then have to copy it to the other.

But with the current interface implementation, if I define a Socket interface, I have to write Socket(sock.handle).address().
(and handle is private).This is a very unintuitive implementation.

More importantly, it would change the way sock.address() is accessed in the existing tcp and would break call dependencies in other code.

If it were possible to optionally explicitly declare that both UdpSocket and TcpSocket support the Socket interface, and that the explicit declaration automatically owns the socket's address() function, then it would be possible to implement one definition without affecting existing call dependencies.

Of course, this explicit declaration of support for the interface is not mandatory, and existing code is not affected at all.

The syntax can be similar to

```
struct TcpSocket: Socket {

}
```

If multiple interfaces are to be supported, it could be

```
struct TcpSocket: Socket + A + B {

}
```

see also [Ability to declare that struct implements interface](https://github.com/vlang/v/issues/1314)

[ChronosX88](https://github.com/ChronosX88) commented [on 26 Jul 2019](https://github.com/vlang/v/issues/1314#issuecomment-515172561)
> but... it may be optional...

**Comment by kahsa** [comment]
Have you misunderstood how to use the interface?
The way you use interfaces in Java or C# is completely different from the way you use them in Go or V.

**Comment by gcxfd** [comment]
In rust , impl a trait for a struct , then struct.method() can call
I want is like this

**Comment by gcxfd** [comment]
We can imagine a case.

Today, for example, the author wrote an image compression library and implemented a class ImgCompressJpg that compresses images into Jpg.

After a while, the author implements another class, ImgCompressWebp .

ImgCompressJpg and ImgCompressWebp have some public functions such as loadPng, loadBmp, loadTiff that the library author wants to reuse.

According to the existing interface approach, the authors can only replicate these functions once without affecting the way they are used by downstream users.

It would make it easier for authors to write code if they could display a declaration that an interface is supported and automatically integrate the functions in the interface.

If multiple interfaces have functions with the same name, it doesn't hurt that they can be called with something like `class#inferface.method()`, the semantics of # being a reference to the id selector in css.

Finally, after explicitly declaring support for an interface, structs can still define functions in the interface, overriding the implementation of the interface. This way, if multiple interfaces have functions with the same name, the author can directly redefine the function to call the functions with the same name in both interfaces in turn.

**Comment by kahsa** [comment]
I have now confirmed that you have a fundamentally wrong understanding of interfaces.
You should first try to forget Rust and study only V.

**Comment by gcxfd** [comment]
I've read the vlang documentation carefully.
I'm not sure where my understanding is wrong?

In vlang, you use an interface, you have to show the conversion of the object to this interface, and then you can use the functions on this interface.

However, if I am the author of a library, I have already implemented some functions on some structure, for example ImgCompressPng, and it's dependent on many third parties as a library (the calling interface can't be changed at will).

At this point, I need to write a similar structure, like ImgCompressJpg, which has a lot of common functions with the previously implemented ImgCompressPng.

As the vlang interface is written now, I have to change the call writing from xxx.method() to Interface(xxx).method().

I can't force the downstream dependencies to modify their existing code.

So, the only way to do it in vlang now is to copy the code over.

If you could optionally display a declaration of support for an interface in the structure definition, and then automatically have the function for that interface on the structure, then you could avoid these code copies.

**Comment by gcxfd** [comment]
If I'm having trouble understanding the vlang language, can you give a best practice guide for vlang in this realistic scenario (keeping the way the library exposes struct functions to the public unchanged, while reusing certain functions inside the able library without having to copy them)?

**Comment by gcxfd** [comment]
I understand how to this in vlang and create two pull request

https://github.com/vlang/v/pull/13560/files
Make the documentation of Embedded struct clearer

https://github.com/vlang/v/pull/13559/files
socket address DRY
