### ISSUE TITLE
vpm can't login

### ISSUE THREAD

**Issue by gcxfd** [vlang/v#13528]
see video https://www.loom.com/share/561d4e2bcd6141a28c16058cb5ca8cd8

**Comment by gcxfd** [comment]
The vpm site looks so minimalistic that it's easy to get a feeling that the v language is still a toy. I thought I could come and write a new version that looks better.

**Comment by JalonSolov** [comment]
vpm is known to be broken right now.  @Terisback has been working on a replacement.

**Comment by gcxfd** [comment]
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/69608605/154863098-0390be60-9c8b-4ce5-b9f5-d6a78f53c597.png">
i designed a demo page ( image as above , code there https://github.com/rmw-link/vpm )
and dumped the exist mod into database 
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/69608605/154863164-cbc823b7-c10d-4eb6-9fa0-6674b5dcfeaa.png">

**Comment by smartiniOnGitHub** [comment]
Hi all, FYI today I have been able to login in vpm and publish a module ...

**Comment by medvednikov** [comment]
VPM has been updated to work with GitHub's new OAuth API changes, so logging in and adding new modules now works again:
