### ISSUE TITLE
Stability guarantee breakage

### ISSUE THREAD

**Issue by nico-abram** [vlang/v#13533]
**V version:** V full version: V 0.2.4 efdbe9d.67e33bf
**OS:** OS: windows, Microsoft Windows 10 Home v19044 64-bit

**What did you do?**
I wanted to test the stability promise in the readme, so I ran a git blame to find the commit that added it, and then browsed the repository at that point in time (https://github.com/vlang/v/tree/ba38c94a403b72222508a857046ddeb979038de7) and looked at the examples. The first one I tried was this concurrency example: https://github.com/vlang/v/blob/ba38c94a403b72222508a857046ddeb979038de7/examples/concurrency/concurrency.v#L1-L21 which did not work, breaking the stability/backwards compatibility guarantee.

**What did you expect to see?**
I expected the example to compile and work, as promised in the stability guarantee.
 
**What did you see instead?**
```
old.v:5:25: warning: `fn f(x, y Type)` syntax has been deprecated and will soon be removed. Use `fn f(x Type, y Type)` instead. You can run `v fmt -w "old.v"` to automatically fix your code.
    3 |
    4 | // Simulate expensive computing using sleep function
    5 | fn expensive_computing(id, duration int, wg &sync.WaitGroup) {
      |                         ^
    6 |     println('Executing expensive computing task (${id})...')
    7 |     time.sleep_ms(duration)
old.v:7:7: error: unknown function: time.sleep_ms
    5 | fn expensive_computing(id, duration int, wg &sync.WaitGroup) {
    6 |     println('Executing expensive computing task (${id})...')
    7 |     time.sleep_ms(duration)
      |          ~~~~~~~~~~~~~~~~~~
    8 |     println('Finish task ${id} on ${duration} ms')
    9 |     wg.done()
old.v:9:2: error: `wg` is immutable, declare it with `mut` to make it mutable
    7 |     time.sleep_ms(duration)
    8 |     println('Finish task ${id} on ${duration} ms')
    9 |     wg.done()
      |     ~~
   10 | }
   11 |
old.v:14:2: error: `wg` is immutable, declare it with `mut` to make it mutable
   12 | fn main() {
   13 |     wg := sync.new_waitgroup()
   14 |     wg.add(3)
      |     ~~
   15 |     go expensive_computing(1, 100, wg)
   16 |     go expensive_computing(2, 500, wg)
old.v:19:1: error: `wg` is immutable, declare it with `mut` to make it mutable
   17 |     go expensive_computing(3, 1000, wg)
   18 |     // Join all tasks
   19 |     wg.wait()
      | ~~
   20 |     println('All jobs finished!')
   21 | }

```

**Comment by ylluminate** [comment]
The stability guarantee should be interpreted for 1.0+ releases of the language as is stated at the referenced guarantee (https://github.com/vlang/v#stability-guarantee-and-future-changes). I believe it would be reasonable to not expect enormous changes / breakages after the next 0.3 release, but please do keep in mind that things can still change.
