### ISSUE TITLE
V has not officially released a new version for almost a year, should there be a TODO check list and roadmap for the new version?

### ISSUE THREAD

**Issue by gcxfd** [vlang/v#13544]
I really like the V language.

However, it's been almost a year since a new version of the language was officially released. It's time for a clear TODO check list and roadmap for new releases , just like

- [ ] A feature
- [x] B feature
- [x] C feature
- [ ] D feature 

I think that releasing new versions periodically (e.g. every quarter) gives the impression that the project is still progressing steadily.

A year without an official release of the V language would give a bad psychological implication that the project is not maintained.

**Comment by JalonSolov** [comment]
See https://github.com/vlang/v/blob/master/ROADMAP.md
