### ISSUE TITLE
The argument can directly take a returned multiple values

### ISSUE THREAD

**Issue by kahsa** [vlang/v#13546]
```v
fn get() (string, int){
	return 'hello', 3
}

fn say(word string, num int){}

fn main(){
	say(get())
}
```

**Comment by gcxfd** [comment]
I think `foo(...get_size())` maybe better

**Comment by kahsa** [comment]
It is similar to variable number arguments, but with a new syntax, so it will be difficult to implement.

And variable number of arguments is an array.

Instead, the compiler should just check the type and number of arguments and assign them directly.
This would make it easier to modify the compiler.
