### ISSUE TITLE
Compiler crash with index, value in array statement

### ISSUE THREAD

**Issue by Jhynjhiruu** [vlang/v#13561]
**V doctor:**
```
OS: windows, Microsoft Windows 10 Pro v19044 64-bit
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz  

CC version: cc (Rev9, Built by MSYS2 project) 11.2.0

getwd: C:\Users\[]\Documents\v\acta
vmodules: C:\Users\[]\.vmodules
vroot: D:\v
vexe: D:\v\v.exe
vexe mtime: 2022-02-20 16:00:50
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 04654ed

Git version: git version 2.35.1
Git vroot status: weekly.2022.07-55-g04654ed5
.git/config present: true
thirdparty/tcc: N/A

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg src/assembler.v`
See attached file `src/assembler.v`
[assembler.zip](https://github.com/vlang/v/files/8114796/assembler.zip)

**What did you expect to see?**

Successful compilation or a syntax error

**What did you see instead?**

```
================ V panic ================
   module: builtin
 function: __as_cast()
  message: as cast: cannot cast `unknown` to `v.ast.Var`
     file: D:/v/vlib/builtin/builtin.v:39
   v hash: 04654ed
=========================================
print_backtrace_skipping_top_frames is not implemented
```

According to Discord: "It's something it doesn't like with `for index, mut value in s.statements {` [line 395]. `s.statements` is of type `[][]int` - so it might be something with mutability in nested arrays."

**Comment by Larpon** [comment]
Update: I think it's V failing to see that the `s` in `for index, mut value in s.statements {` isn't a valid identifier (there's no `s` in scope in the method - hence the panic).

**Comment by Larpon** [comment]
Here's a more minimal reproduction example of the same panic:
```v
fn main() {
	for index, mut value in s.statements {
		println('Hello')
	}
}
```
