### ISSUE TITLE
Cannot run example tetris.v

### ISSUE THREAD

**Issue by arylee** [vlang/v#1357]
I tried with a laptop with I5 7400 (integrated display card) and a desktop with NVIDIA GeForce GTX 1050. Both machine are running Ubuntu 18.04 with kernel 4.15.0-54-generic (most recently). And I compiled v with gcc 7.4.0, I got below message when running example tetris.v.

create window wnd=0x563f08eb9070 ptr==0x7f9193248a98
#version 330 core
layout (location = 0) in vec4 vertex; // <vec2 pos, vec2 tex>
out vec2 TexCoords;

uniform mat4 projection;

void main()
{
    gl_Position = projection * vec4(vertex.xy, 0.0, 1.0);
    TexCoords = vertex.zw;
}  
double free or corruption (out)
Aborted (core dumped)
double free or corruption (out)
Aborted (core dumped)
failed to run the compiled program

**Comment by spytheman** [comment]
Does the examples/hot_code_reloading/graph.v work for you?

**Comment by Bowero** [comment]
Since this is a user specific issue and the original poster hasn't responded in 28 days, I'll be closing this issue to keep the repository clean. If there is a need reopen the issue, we can still do that.
