### ISSUE TITLE
fmt: return types list ending with comma not supported

### ISSUE THREAD

**Issue by Hunam6** [vlang/v#13592]
```
OS: macos, macOS, 12.1, 21C52
Processor: 8 cpus, 64bit, little endian, Apple M1
CC version: Apple clang version 13.0.0 (clang-1300.0.29.30)

getwd: /Users/hunam/Documents/dev/go2v
vmodules: /Users/hunam/.vmodules
vroot: /Applications/v
vexe: /Applications/v/v
vexe mtime: 2022-02-23 17:36:00
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 36c9ed6.9662b79

Git version: git version 2.32.0 (Apple Git-132)
Git vroot status: weekly.2022.07-77-g9662b796
.git/config present: true
thirdparty/tcc status: thirdparty-unknown-unknown de82a130
```

**What did you do?**
```v
fn ok(a int,) (int, string,) {}
```

**What did you expect to see?**
```v
fn ok(a int) (int, string) {}
``` 
**What did you see instead?**
syntax error

**Note**
As
```v
fn ok(a int,) {}
```
gets formatted to
```v
fn ok(a int) {}
```
return types should be supported too

**Comment by kahsa** [comment]
`fn ok(a int,) {}` compiles.

There is some ambiguity in the handling of this comma, both in the compiler and in the formatter.
I think we need to decide on a detailed specification of what is correct.

**Comment by Hunam6** [comment]
That's strange I think `fn ok(a int,) {}` should compile only once formatted to `fn ok(a int) {}`.

Let the trailing comma job to vfmt.

**Comment by kahsa** [comment]
In my opinion, `fn ok(a int,) {}` should be an error by the compiler.
The formatter should not manipulate commas.
My opinion is that formatters should only manipulate whitespace, tabs, newlines, and should never insert or remove commas, characters, etc.

**Comment by Hunam6** [comment]
I really don't agree, it reminds me of this tweet:
https://twitter.com/_joemag_/status/1490899167446589443
If it can improve developper workflow why not?

**Comment by Hunam6** [comment]
doesn't work for function call as variable value too
`i := int(42,)`

**Comment by JalonSolov** [comment]
`v fmt` is supposed to fix things like this while it formats the code.

**Comment by Hunam6** [comment]
This also doesn't work

```v
module main

fn foo(x int) int {
	return x,
}
```
