### ISSUE TITLE
Compiler didn't generate method used in comptime reflction

### ISSUE THREAD

**Issue by ChAoSUnItY** [vlang/v#13611]
OS: windows, Microsoft Windows 11 Home v22000 64-bit
Processor: 20 cpus, 64bit, little endian, 12th Gen Intel(R) Core(TM) i7-12700  
CC version: Error: exec failed (CreateProcess) with code 2: 系統找不到指定的檔案。
 cmd: cc --version

getwd: C:\Users\chaos\projects\vaker
vmodules: C:\Users\chaos\.vmodules
vroot: C:\Users\chaos\projects\v
vexe: C:\Users\chaos\projects\v\v.exe
vexe mtime: 2022-02-27 07:02:25
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 67e33bf.0fb1eae

Git version: git version 2.35.1.windows.2
Git vroot status: weekly.2022.07-90-g0fb1eaef (1 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 9de1a49e

**What did you do?**
```v
pub fn fake_data<T>(t &T) {
	$if T is $Array {
		len := t.len
		for i in 0 .. len {
			fake_data(&t[i])
		}
		return
	} $else $if T.typ is string {
		unsafe {
			*t = fake_string(10, &vaker.lb_EN)
		}
	} $else {
		$for f in T.fields {
			fake_data(&(t.$(f.name)))
		}
	}
}
```

**What did you expect to see?**
compilation should succeed
 
**What did you see instead?**
```
tcc: error: undefined symbol 'vaker__fake_data_T_string'
```

**Note**
If I add the following code before `$for`, the compilation would succeed instead:
```v
$if f.typ is string {}
```

**Comment by felipensp** [comment]
Can you try again and post a complete reproducible test case?

**Comment by JalonSolov** [comment]
I tried compiling just what is show above, and it succeeds with latest V.
