### ISSUE TITLE
`v run` ctime cache

### ISSUE THREAD

**Issue by whoizit** [vlang/v#1365]
_ctime - time of last modification of file_

V may be preferable for writing scripts if it will cache _ctime_. 
No need to rebuild the script if it has not changed.

When we do `v run ~/bin/hello.v` we can save the binary with same name in `/tmp/.v_run_cache/home/user/bin/hello.v` (example)
We can save _ctime_ of script `~/bin/hello.v` to binary `/tmp/.v_run_cache/home/user/bin/hello.v`

So, every launch `v run` we can check if binary `hello.v` exist in `v_run_cache`, read ctime and compare them for equivalence
 
it may be cheaper to save _ctime_ in the name of a binary file, for example /tmp/.v_run_cache/home/user/bin/hello.v@2147483647

The persistency of this cache is not really important
We can also provide env. variable for this path.

**Comment by medvednikov** [comment]
Fixed in https://github.com/vlang/v/pull/1493
