### ISSUE TITLE
Make not using local tcc, and throwing "undefined symbol 'tcc_backtrace'"

### ISSUE THREAD

**Issue by Kacim62BOBO** [vlang/v#13656]
Hi, 
I cloned v and ran make, but i only have tcc installed and it throwed 'cc' not found (it didn't use my installed tcc).
Could you please tell me what am doing wrong. Thanks !

**V version:** Latest V and vc
**OS:** Linux x86_64 kernel 5.16.11

**What did you do?**
installed tccbin to path
git clone https://github.com/vlang/vc
cd ./vc
tcc -std=gnu99 -w -I/root/v/thirdparty/stdatomic/nix v.c -o v -lm -lpthread -latomic 

**What did you expect to see?**
v compiled successfully
 
**What did you see instead?**
tcc: error: undefined symbol 'tcc_backtrace'

**Comment by Larpon** [comment]
Just confirming a similar situation on an Raspberry PI 4B

**Comment by Larpon** [comment]
I can get it to compile by adding `-bt10` like so:
`tcc -std=gnu99 -w -I/root/v/thirdparty/stdatomic/nix v.c -o v -bt10 -lm -lpthread -latomic`

**Comment by Kacim62BOBO** [comment]
Thanks. But still the same issue.

**Comment by Kacim62BOBO** [comment]
Hi, I tied it, but it ends up with:
/bin/sh: line 1: cc: no such file or directory.
So I tried:
mv /usr/bin/tcc /usr/bin/cc
(btw I ONLY have tcc installed)
But it throws:
1)tcc: error: library 'execinfo' not found (My linux system comes already with execinfo.h)
2)tcc: error: undefined symbol 'tcc_backtrace'
3)tcc: error: undefined symbol '__dso_handle'
4)tcc: error: undefined symbol '__atomic_load_8'
tcc: error: undefined symbol '__atomic_store_8'
tcc: error: undefined symbol '__atomic_compare_exchange_8'
tcc: error: undefined symbol '__atomic_exchange_8'
tcc: error: undefined symbol '__atomic_fetch_add_8'
tcc: error: undefined symbol '__atomic_fetch_sub_8'
tcc: error: undefined symbol '__atomic_load_4'
tcc: error: undefined symbol '__atomic_compare_exchange_4'
tcc: error: undefined symbol '__atomic_fetch_add_4'
tcc: error: undefined symbol '__atomic_load_2'
tcc: error: undefined symbol '__atomic_store_2'
tcc: error: undefined symbol '__atomic_compare_exchange_2'

So I tried modifying the 'Makefile' just to replace '-lexecinfo' with '-latomic':
  $(CC) $(CFLAGS) -std=gnu11 -w -I ./v/thirdparty/stdatomic/nix v.c -o v1 -lm -lpthread -latomic $(LDFLAGS)
Rerunning 'make':
 Issues 1 and 4 disappeared.
 Issues 2 and 3 persisting.

**Comment by Dialga** [comment]
Check out https://github.com/vlang/v/issues/9632#issuecomment-815261371, try `CC=tcc VFLAGS="-cc tcc" LDFLAGS="-lexecinfo -bt" make`, https://www.reddit.com/r/vlang/comments/mlzags/comment/gtqh1sb/?utm_source=reddit might help too if you are using alpine linux.

**Comment by Kacim62BOBO** [comment]
Thank you,
I cloned https://github.com/mikroskeem/libexecinfo, installed it, and built tcc against musl.
It worked, thank you very much!
