### ISSUE TITLE
v.fmt: Automatically discard embedded struct fields' attributes

### ISSUE THREAD

**Issue by ChAoSUnItY** [vlang/v#13657]
OS: windows, Microsoft Windows 11 Home v22000 64-bit
Processor: 20 cpus, 64bit, little endian, 12th Gen Intel(R) Core(TM) i7-12700  
CC version: Error: exec failed (CreateProcess) with code 2: 系統找不到指定的檔案。
 cmd: cc --version

getwd: C:\Users\chaos\projects\vaker
vmodules: C:\Users\chaos\.vmodules
vroot: C:\Users\chaos\projects\v
vexe: C:\Users\chaos\projects\v\v.exe
vexe mtime: 2022-03-03 17:01:31
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 4331d6d.95ecb92

Git version: git version 2.35.1.windows.2
Git vroot status: weekly.2022.09-28-g85bf3b76 (8 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 9de1a49e

**What did you do?**
`main.v`
```v
struct St {
	Bs          ['vaker:skip']
	a    string ['vaker:amount_with_currency']
	lat  f32    ['vaker:lat']
	long f64    ['vaker:long']
}

struct Bs {
	a string ['vaker:skip']
}
```
run command:
```cmd
v fmt . -w
```

**What did you expect to see?**
Source should already be formatted, which means no diff.
 
**What did you see instead?**
The attribute on embedded struct field is discarded by vfmt without any warning, notice, or error.
```v
struct St {
	Bs
	a    string ['vaker:amount_with_currency']
	lat  f32    ['vaker:lat']
	long f64    ['vaker:long']
}

struct Bs {
	a string ['vaker:skip']
}
```

**Comment by tobealive** [comment]
fixed by now, can be closed :+1: 
```
test/bug.v:2:14: error: cannot use attributes on embedded structs
    1 | struct St {
    2 |     Bs          ['vaker:skip']
      |                 ^
    3 |     a    string ['vaker:amount_with_currency']
    4 |     lat  f32    ['vaker:lat']
```

**Comment by ChAoSUnItY** [comment]
I don't think that's how it suppose to work though... Since embedded struct `Bs` still generate a field for struct `St`, so why do we forbid it?

**Comment by tobealive** [comment]
I think so too that would be a nice thing to have. Still, the technical side of the what this issue was about `v.fmt: Automatically discard embedded struct fields' attributes` appeared to be solved.

**Comment by ChAoSUnItY** [comment]
You're right, I'll close this one as vfmt issue is fixed.
