### ISSUE TITLE
V 0.1.17 is out with generics, vweb, and more

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#1366]
It's finally possible to write web apps in V!

https://github.com/vlang/v/tree/master/vlib/vweb

The V forum software has just been open sourced as well:

https://github.com/vlang/vtalk

## V 0.1.17 
*29 Jul 2019* 
- `vweb` module for developing web apps in V. 
- vtalk, open source V forum software. 
- Generics (very limited right now, but they will be gradually improved).  
- Comptime codegen (`foo.$method()` where `method` is a string). 
- @ for escaping keywords (e.g. `struct Foo { @type string }`). 
- Windows Unicode fixes (V can now work with non-ASCII paths etc on Windows). 
- Fix mutable args bugs + don't allow primitive arguments to be modified.  
- Declaring a mutable variable and never modifying it results in a compilation error.
- Interactive debugging support.
- `sync` module for Windows.
- `#!` support on Unix systems (V scripts).
- Lots of Visual Studio fixes.
- `crypto.aes` and `crypto.rc4` modules.
- Internal modules.

**Comment by l8atnight** [comment]
thanx - i love this compiler of yours.
keep on going!
💯

**Comment by ntrel** [comment]
> Generics (very limited right now, but they will be gradually improved).

Is there any test code that shows the progress with generics?

**Comment by LXSMNSYC** [comment]
Generics doesn't seem to work at all, at least, based on my tests. Compiling a very simple generics implementation logs a "check()" message on the terminal (I am compiling V prograns on Windows 10)
