### ISSUE TITLE
native bakcend error: V panic: as cast: cannot cast `v.ast.Ident` to `v.ast.IntegerLiteral`

### ISSUE THREAD

**Issue by rempas** [vlang/v#13678]
**V version:** V 0.2.4 beb1b8
**OS:** linux, "ArcoLinux"

**What did you do?**
I tried to compile the following code using the "native" backend:

```
fn main() {
  n := 500000
  mut first_term := 0
  mut second_term := 1
  mut sum := 0
  mut i := 2

  for i < n {
    sum = first_term + second_term
    first_term = second_term
    second_term = sum
    i += 1
    print("$sum ")
  }
}
```

The code compiles without any problems using "C" backend but it throws an error if I use the "native" backend.

**What did you expect to see?**
I was expecting the code to compile like it happens when I use "C" backend.
 
**What did you see instead?**
The following error message:

```
V panic: as cast: cannot cast `v.ast.Ident` to `v.ast.IntegerLiteral`
v hash: beb1b8c
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:12722: at _v_panic: Backtrace
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:13045: by __as_cast
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:30266: by v__gen__native__Gen_for_stmt
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:30945: by v__gen__native__Gen_stmt
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:30637: by v__gen__native__Gen_stmts
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:30304: by v__gen__native__Gen_fn_decl_amd64
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:30826: by v__gen__native__Gen_fn_decl
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:30936: by v__gen__native__Gen_stmt
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:30637: by v__gen__native__Gen_stmts
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:30560: by v__gen__native__gen
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:57485: by v__builder__nativebuilder__build_native
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:57457: by v__builder__nativebuilder__compile_native
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:57026: by v__builder__compile
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:57452: by v__builder__nativebuilder__start
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:57491: by main__main
/tmp/v_1000/native_builder.5183096116380940638.tmp.c:57957: by main
```

**Comment by JalonSolov** [comment]
@trufae :point_up:

**Comment by trufae** [comment]
I'll check that. Thanks for the heads up

**Comment by rempas** [comment]
> I'll check that. Thanks for the heads up

Thanks for the quick notice! The native backend looks super promising!

**Comment by trufae** [comment]
There are some reasons why this program doesnt compile with the native backend.

* Comparing two variables was not supported (fixed it in a PR)
* Interpolated strings is not supported `print('$sum')`. this requires quite a lot of work still.
* Printing idents doesnt work unless the type is a string. i need to implement atoi() in assembly for that to work `print(sum)`

So for testing purposes i replaced the print with an `exit(sum)` at the end of the loop and compared build+run times:

```
$ time v -native run q.v ; echo $?

real    0m0.007s
user    0m0.002s
sys     0m0.005s
221
$ time v run q.v ; echo $?

real    0m0.296s
user    0m0.253s
sys     0m0.178s
221
```

run time:

```
pancake@wop:~/prg/v$ time ./q ; echo $?

real    0m0.004s
user    0m0.004s
sys     0m0.000s
221
pancake@wop:~/prg/v$ v -native q.v
pancake@wop:~/prg/v$ time ./q ; echo $?

real    0m0.002s
user    0m0.003s
sys     0m0.000s
221
````

**Comment by rempas** [comment]
> There are some reasons why this program doesnt compile with the native backend.
> 
>     * Comparing two variables was not supported (fixed it in a PR)
Thank you! I've seen the RP cause I'm a stalker ;)
Btw, I haven't contributed in any other project and I don't know but is this how you guys work? You fixed it in less than 24 hours. And you don't even get paid. IMPRESSIVE!
> 
>     * Interpolated strings is not supported `print('$sum')`. this requires quite a lot of work still.
> 
>     * Printing idents doesnt work unless the type is a string. i need to implement atoi() in assembly for that to work `print(sum)`
That's interesting! Concatenate strings is slow anyway. And it is also not a good practice imo. Something like formatting the output the way "printf" does it will be the best way to go from every way you see it. Automatically finding the type and convert the value to a string and add it to the `stdout` buffer. Exactly the way rust's "println!" works.

Fun fact: Before re-checking (because I had two times in the past) V, I was trying to create a system library for the D programming language and I tried to do the exact same thing. Well "print" was never fully finished (and I will stick with V as it seems so I will probably never finish it) but I did a part of it and I finished the functions that convert numbers and floats to a string so with a little more work, I could had a version of Rust's `println!` for D that doesn't depend on anything and is super fast. I don't know if we can do this in V cause the last time I checked, there was no way to have variadic arguments of different types (did this changed) so It must be a special built-in function. If you are interested tho, I could give you the source code and while you may not know D, keep in mind that it has been build with a C-like way with the exception of some things like the templated functions and the variadic arguments and for some compile-time checks.

> 
> So for testing purposes i replaced the print with an `exit(sum)` at the end of the loop and compared build+run times:
> 
> ```
> $ time v -native run q.v ; echo $?
> 
> real    0m0.007s
> user    0m0.002s
> sys     0m0.005s
> 221
> $ time v run q.v ; echo $?
> 
> real    0m0.296s
> user    0m0.253s
> sys     0m0.178s
> 221
> ```
> 
> run time:
> 
> ```
> pancake@wop:~/prg/v$ time ./q ; echo $?
> 
> real    0m0.004s
> user    0m0.004s
> sys     0m0.000s
> 221
> pancake@wop:~/prg/v$ v -native q.v
> pancake@wop:~/prg/v$ time ./q ; echo $?
> 
> real    0m0.002s
> user    0m0.003s
> sys     0m0.000s
> 221
> ```

Like I said, the `native` backend seems super promising and the reason I'm sticking with V instead of making my own language which would take a lot of years to make. LLVM and GCC can be used for some specific functions but for the most time, the hundreds of optimizations they do may only give about 5-20% so it's not worth it to increase the compilation times about 30-50 times. Finding a way to combine these two will be awesome. I diffidently want to learn V and start contributing in the native backend. I will also need to learn assembly and how the instructions decode and work in the machine level first but I'm confident and happy for the future! 

P.S. I'm very short in time and I can't re-check what I wrote. Sorry if there are any mistakes.

**Comment by JalonSolov** [comment]
The native backend will support the same as the C backend as far as printing.  There are ways to specify the output format, size, etc. of a variable, but if you don't specify it will simply use the default for the type of the variable listed.

In other words, V's `println` already automatically convert variables to their string representation by default, but you can also have more control.

https://github.com/vlang/v/blob/master/doc/docs.md#string-interpolation

**Comment by rempas** [comment]
> The native backend will support the same as the C backend as far as printing. There are ways to specify the output format, size, etc. of a variable, but if you don't specify it will simply use the default for the type of the variable listed.
> 
> In other words, V's `println` already automatically convert variables to their string representation by default, but you can also have more control.
> 
> https://github.com/vlang/v/blob/master/doc/docs.md#string-interpolation

Thanks for the info! I made the suggestion so we don't have to allocate memory tho and so that the work becomes easier for the native backend. But of course, whatever works should stay and they developers know better than me. Thanks for the great work everyone!
