### ISSUE TITLE
v fmt can't handle inline comments in weird places

### ISSUE THREAD

**Issue by shrumo** [vlang/v#13679]
**V version:** V 0.2.4 beb1b8c
**OS:** linux, Debian GNU/Linux rodete

**What did you do?**

```
$ v fmt tmp.v 
tmp.v:1:3: error: expecting method name
    1 | fn /*main*/main() {
      |   ~~~~~~~~~
    2 |     return
    3 | }

Internal vfmt error while formatting file: tmp.v.
Encountered a total of: 1 errors.
```

**What did you expect to see?**
Nicely formatted V code.
 
**What did you see instead?**
Error.

Note that this comes from the parser handling comments weirdly (as part of the ast), but the solution is not that simple as just changing https://github.com/vlang/v/blob/master/vlib/v/parser/fn.v#L303.

The options I can think of now are:
1. Drop inline comments when they appear in unexpected places when doing `v fmt`.
2. Move the comments around. This would mean accumulating comments in the [Parser](https://github.com/vlang/v/blob/master/vlib/v/parser/parser.v#L17) struct and attach them to the first "good" place. In this specific place the first good place would probably be `*after* the header`. (from [here](https://github.com/vlang/v/blob/master/vlib/v/ast/ast.v#L532))
3. Add more fields to the ast indicating all the possible positions to attach the documentation to.

**Comment by JalonSolov** [comment]
4. Drop inline comments altogether.  They are simply more pain than they are worth, the complicate the scanner/parser/etc., and often just look messy.

**Comment by spytheman** [comment]
Inline comments are convenient for commenting large blocks of code temporarily, without huge diffs.

**Comment by spytheman** [comment]
The preferred solution so far is a combination of 2 and 3, i.e. collect the existing comments while parsing, and then when vfmt-ing, put them in more sane places (like at the end of the lines, not between the statement parts).

(1) is not acceptable - that loses information that the user produced. Even a vfmt/parser error (like now) is better than that.

**Comment by JalonSolov** [comment]
> Inline comments are convenient for commenting large blocks of code temporarily, without huge diffs. They are "only" complicating things when they are _inside_ statements, that do not expect them.

That's why I said drop _inline_ comments.  Yes, `/* */` are useful for exactly the reason you stated.

**Comment by ntrel** [comment]
> 4. Drop inline comments altogether. 

This also causes the same error:

```v
fn // hi
main(){println('hi')}
```

**Comment by JalonSolov** [comment]
Definitely a bug... and just another type of inline comment.  :-\
