### ISSUE TITLE
The "-usecache" flag fails when trying to compile the "calculator" example from the "ui" library. 

### ISSUE THREAD

**Issue by rempas** [vlang/v#13684]
**V version:** V 0.2.4 beb1b8c
**OS:** linux, "ArcoLinux"

**What did you do?**
Similar to #13681. This time I used the "-usecache" flag however. The error message is different.

**What did you expect to see?**
Work I guess....
 
**What did you see instead?**
The following error message (full form):

```
In file included from /tmp/v_1000/test.5760531215180950624.tmp.c:1219:
/home/rempas/Downloads/v/thirdparty/sokol/sokol_app.h:1797:14: fatal error: X11/extensions/XInput2.h: No such file or directory
 1797 |     #include <X11/extensions/XInput2.h>
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**P.S.** Keep in mind that the same message also appears for more files than only `/test.5760531215180950624.tmp.c` but it's the same message, only the name of the file changes so I guess nobody wants that. If you do however, let me know!

**Comment by changrui** [comment]
Read `readme.md` of module `ui` first:
```
To develop [V](https://github.com/vlang/v#installing-v-from-source) UI apps, you need to install V. This takes a couple of seconds.

On some Linux distros you also need a few development dependencies:

Debian/Ubuntu: sudo apt install libxi-dev libxcursor-dev mesa-common-dev
Fedora: sudo dnf install libXi-devel libXcursor-devel mesa-libGL-devel
On ChromeOS Linux/Crostini, install the Debian dependencies listed above followed by this:

sudo apt install freeglut3-dev ([see details](https://github.com/vlang/ui/issues/316))
```

**Comment by rempas** [comment]
Just like the other issue, the build works without the `-usecache` flag and the program executes and works without any problems. So I don't miss any library. Don't worry, I checked the libraries anyway and they are indeed installed ;)

**Comment by rempas** [comment]
This seems to work now!
