### ISSUE TITLE
unknown function

### ISSUE THREAD

**Issue by qingyun5570** [vlang/v#13697]
**V version:** 0.2.4 9a2df04
**OS:** win7

**What did you do?**
E:\demo\b.v
module main

fn add(i int)int{
	return i+2
}

E:\demo\a.v
module main

fn main(){
	println(add(3))
}

**What did you expect to see?**

 print 5
**What did you see instead?**
E:\demo>v run a.v
a.v:4:10: error: unknown function: add
    2 |
    3 | fn main(){
    4 |     println(add(3))
      |             ~~~~~~
    5 | }

**Comment by kahsa** [comment]
use dot this way `v run .` instead of `a.v`

**Comment by qingyun5570** [comment]
ok
