### ISSUE TITLE
string.split() bug - design fault

### ISSUE THREAD

**Issue by kahsa** [vlang/v#13696]
**V version: 0.2.4 3f1e232** 
**OS: ArchLinux** 

**What did you do?**
```v
fn main(){
	s := '\n'
	col := s.trim(' \r\n').split(',')
	println(col)
}
```

**What did you expect to see?**
```
[]
```
 
**What did you see instead?**
```
['']
```

I've written a lot of error workarounds, but never suspected that there was such a serious bug here...
This is like `0 / 1 == 1` lol
This is a design mistake.
Splitting a zero length string should return `[]`.

**Comment by yuyi98** [comment]
It's not a bug.
```vlang
fn main(){
	col := ''.split(',')
	//assert col.len == 0
	println(col)
}

PS D:\Test\v\tt1> v run .
['']
```

**Comment by kahsa** [comment]
This is a bug.
It should return `[]` OR `''`.
zero length array OR zero length STRING should be returned.

If you split the whitespace string in a real-life situation, you can see how this can cause other bugs.

**Comment by kahsa** [comment]
```fn main(){
	mut res := Foo{}
	lines := any_result_text.trim(' \r\n|').split(';')
	for l in lines{
		f := do_something(l) // someting wrong happens here
		res << f  // Unintended consequences are added.
	}
}
```
Returns an array containing one funny value, which should be zero-length.
I have always suffered from this bug.
```
		if l == '' { continue }
```
So every time I've put this in, I've been able to surpass it, but there are cases where this doesn't work around and I'm plagued by this bug.
Essentially, it is intuitive and correct that 'lines.len == 0`.

**Comment by yuyi98** [comment]
Yes, it will return [] in golang.

**Comment by yuyi98** [comment]
Sorry, I'm wrong.
```vlang
package main

import (
	"fmt"
	"strings"
)

func main() {
	a := strings.Split("", ",")
	fmt.Println(a)
	fmt.Println(len(a))
}

D:/Test/go/ttt/ttt.exe  [D:/Test/go/ttt]
[]
1
```

**Comment by fenginsc** [comment]
in javascript
''.split(",")
//return [ '' ]
in python
''.split(",")
//return [ '' ]
This doesn't seem to be a bug.
Different languages behave differently, it's just a design issue

**Comment by changrui** [comment]
oh, NO! `[]string{} != ['']` in vlang.

**Comment by medvednikov** [comment]
In such situations V's stdlib should behave like Go's.
