### ISSUE TITLE
v run directory/ -o output creates the wrong executable

### ISSUE THREAD

**Issue by WilliamBehrens** [vlang/v#13712]
`v doctor`:
OS: linux, Pop!_OS 21.10
Processor: 8 cpus, 64bit, little endian, 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
CC version: cc (Ubuntu 11.2.0-7ubuntu2) 11.2.0

getwd: /home/will/Code/RCBot
vmodules: /home/will/.vmodules
vroot: /home/will/.local/v
vexe: /home/will/.local/v/v
vexe mtime: 2022-03-11 03:57:12
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 3f35103

Git version: git version 2.32.0
Git vroot status: weekly.2022.05-233-g3f351036
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 3654d6a8

**What did you do?**
`v watch run ./subdirectory/ -o ./output`

**What did you expect to see?**
`v watch` to create an executable called `./output` be created and ran
 
**What did you see instead?**
an executable called `./subdirectory/subdirectory` be created and ran

**Comment by spytheman** [comment]
Compiler options should be passed before `run`. Options passed after it are ignored by V, instead they are passed to the executable of the program that will be run.

**Comment by spytheman** [comment]
i.e. the correct invocation is: 
`v watch -o ./output run ./subdirectory/`
