### ISSUE TITLE
There are two bugs with v0.1.17 under windows 10.

### ISSUE THREAD

**Issue by changrui** [vlang/v#1376]
1) Can not compile `compiler` directory, `./vc.exe -o v.exe compiler` directly enter REPL;
2) Type `println(any)` or `exit`, got : `'??>>>`. 
Please check it. thx.

**Comment by changrui** [comment]
Add: it's OK under WSL Ubuntu, but `cd vtalk`, `v .`, got: V panic: C error. This should never happen. Please create a GitHub issue. 
Please check it. thx.

**Comment by changrui** [comment]
`v run news_fetcher.v` under WSL Ubuntu, bot also get V panic: C error.
`V panic: C error. This should never happen. Please create a GitHub issue.`

So I push an issue here.

**Comment by nedpals** [comment]
I'm on under assumption that this has been fixed already. But if it's not, please file a new issue using the version of the compiler. Closed.
