### ISSUE TITLE
Error when making the app on windows

### ISSUE THREAD

**Issue by AnimalStudioOfficial** [vlang/v#13796]
**I run make.bat and get this:** 

Updating TCC
 > Syncing TCC from https://github.com/vlang/tccbin

Updating vc...
 > Sync with remote https://github.com/vlang/vc

Building V...
 > Attempting to build v_win.c with "thirdparty\tcc\tcc.exe"
 > Compiling .\v.exe with itself
vlib/strings/builder.c.v:109:28: error: type `&[]byte` does not support slicing
  107 | pub fn (mut b Builder) cut_last(n int) string {
  108 |     cut_pos := b.len - n
  109 |     x := unsafe { (&[]byte(b))[cut_pos..] }
      |                               ~~~~~~~~~~~
  110 |     res := x.bytestr()
  111 |     b.trim(cut_pos)
vlib/strings/builder.c.v:150:28: error: type `&[]byte` does not support slicing
  148 |         return ''
  149 |     }
  150 |     x := unsafe { (&[]byte(b))[b.len - n..] }
      |                               ~~~~~~~~~~~~~
  151 |     return x.bytestr()
  152 | }
vlib/strings/builder.c.v:160:28: error: type `&[]byte` does not support slicing
  158 |         return ''
  159 |     }
  160 |     x := unsafe { (&[]byte(b))[n..] }
      |                               ~~~~~
  161 |     return x.bytestr()
  162 | }
vlib/v/ast/ast.v:799:12: error: `i` is immutable, declare it with `mut` to make it mutable
  797 |
  798 | pub fn (i &Ident) var_info() IdentVar {
  799 |     match mut i.info {
      |               ^
  800 |         IdentVar {
  801 |             return i.info
vlib/v/ast/table.v:1633:12: error: `ts` is immutable, declare it with `mut` to make it mutable
 1631 |     mut c_nrt := ''
 1632 |     ts := t.sym(typ)
 1633 |     match mut ts.info {
      |               ~~
 1634 |         Array {
 1635 |             mut elem_type := ts.info.elem_type
vlib/v/ast/table.v:1738:12: error: `ts` is immutable, declare it with `mut` to make it mutable
 1736 |         else {}
 1737 |     }
 1738 |     match mut ts.info {
      |               ~~
 1739 |         Struct {
 1740 |             mut info := ts.info
vlib/v/checker/assign.v:161:11: error: `right` is immutable, declare it with `mut` to make it mutable
  159 |         }
  160 |         if right_type.is_ptr() && left_type.is_ptr() {
  161 |             if mut right is ast.Ident {
      |                    ~~~~~
  162 |                 if mut right.obj is ast.Var {
  163 |                     mut obj := unsafe { &right.obj }
vlib/v/checker/assign.v:194:13: error: `left` is immutable, declare it with `mut` to make it mutable
  192 |         }
  193 |         node.left_types << left_type
  194 |         match mut left {
      |                   ~~~~
  195 |             ast.Ident {
  196 |                 if left.kind == .blank_ident {
vlib/v/checker/assign.v:300:12: error: `left` is immutable, declare it with `mut` to make it mutable
  298 |             }
  299 |             else {
  300 |                 if mut left is ast.IndexExpr {
      |                        ~~~~
  301 |                     // eprintln('>>> left.is_setter: ${left.is_setter:10} | left.is_map: ${left.is_map:10} | left.is_array: ${left.is_array:10}')
  302 |                     if left.is_map && left.is_setter {
vlib/v/checker/check_types.v:824:16: error: `arg_sym` is immutable, declare it with `mut` to make it mutable
  822 |                     mut generic_types := []ast.Type{}
  823 |                     mut concrete_types := []ast.Type{}
  824 |                     match mut arg_sym.info {
      |                               ~~~~~~~
  825 |                         ast.Struct, ast.Interface, ast.SumType {
  826 |                             generic_types = arg_sym.info.generic_types
vlib/v/checker/checker.v:529:12: error: `expr` is immutable, declare it with `mut` to make it mutable
  527 |
  528 | fn (mut c Checker) check_div_mod_by_zero(expr ast.Expr, op_kind token.Kind) {
  529 |     match mut expr {
      |               ~~~~
  530 |         ast.FloatLiteral {
  531 |             if expr.val.f64() == 0.0 {
vlib/v/checker/checker.v:1066:12: error: `expr` is immutable, declare it with `mut` to make it mutable
 1064 |     mut pos := token.Pos{} // and its position
 1065 |     mut explicit_lock_needed := false
 1066 |     match mut expr {
      |               ~~~~
 1067 |         ast.CastExpr {
 1068 |             // TODO
vlib/v/checker/checker.v:1820:12: error: `node` is immutable, declare it with `mut` to make it mutable
 1818 |     }
 1819 |     c.expected_type = ast.void_type
 1820 |     match mut node {
      |               ~~~~
 1821 |         ast.EmptyStmt {
 1822 |             if c.pref.is_verbose {
vlib/v/checker/checker.v:2116:12: error: `arg` is immutable, declare it with `mut` to make it mutable
 2114 |
 2115 | fn (mut c Checker) asm_arg(arg ast.AsmArg, stmt ast.AsmStmt, aliases []string) {
 2116 |     match mut arg {
      |               ~~~
 2117 |         ast.AsmAlias {}
 2118 |         ast.AsmAddressing {
vlib/v/checker/checker.v:2401:12: error: `node` is immutable, declare it with `mut` to make it mutable
 2399 |         return ast.void_type
 2400 |     }
 2401 |     match mut node {
      |               ~~~~
 2402 |         ast.NodeError {}
 2403 |         ast.ComptimeType {
vlib/v/checker/checker.v:3033:14: error: `obj` is immutable, declare it with `mut` to make it mutable
 3031 |         }
 3032 |         if obj := node.scope.find(node.name) {
 3033 |             match mut obj {
      |                       ~~~
 3034 |                 ast.GlobalField {
 3035 |                     node.kind = .global
vlib/v/checker/checker.v:3054:18: error: field `expr` of struct `ast.Var` is immutable
 3052 |                     mut typ := if is_sum_type_cast { obj.smartcasts.last() } else { obj.typ }
 3053 |                     if typ == 0 {
 3054 |                         if mut obj.expr is ast.Ident {
      |                                    ~~~~
 3055 |                             if obj.expr.kind == .unresolved {
 3056 |                                 c.error('unresolved variable: `$node.name`', node.pos)
vlib/v/checker/checker.v:3060:18: error: field `expr` of struct `ast.Var` is immutable
 3058 |                             }
 3059 |                         }
 3060 |                         if mut obj.expr is ast.IfGuardExpr {
      |                                    ~~~~
 3061 |                             // new variable from if guard shouldn't have the optional flag for further use
 3062 |                             // a temp variable will be generated which unwraps it
vlib/v/checker/checker.v:3116:14: error: `obj` is immutable, declare it with `mut` to make it mutable
 3114 |         }
 3115 |         if obj := c.file.global_scope.find(name) {
 3116 |             match mut obj {
      |                       ~~~
 3117 |                 ast.ConstField {
 3118 |                     if !(obj.is_pub || obj.mod == c.mod || c.pref.is_test) {
vlib/v/checker/checker.v:3261:11: error: `expr` is immutable, declare it with `mut` to make it mutable
 3259 |             mut is_already_casted := false
 3260 |             mut orig_type := 0
 3261 |             if mut expr.obj is ast.Var {
      |                    ~~~~
 3262 |                 is_mut = expr.obj.is_mut
 3263 |                 smartcasts << expr.obj.smartcasts
vlib/v/checker/for.v:156:27: error: `infix` is immutable, declare it with `mut` to make it mutable
  154 |         if infix.op == .key_is {
  155 |             if infix.right is ast.TypeNode && infix.left in [ast.Ident, ast.SelectorExpr] {
  156 |                 is_variable := if mut infix.left is ast.Ident {
      |                                       ~~~~~
  157 |                     infix.left.kind == .variable
  158 |                 } else {
vlib/v/checker/if.v:302:28: error: `node` is immutable, declare it with `mut` to make it mutable
  300 |                 }
  301 |                 if node.left in [ast.Ident, ast.SelectorExpr] && node.right is ast.TypeNode {
  302 |                     is_variable := if mut node.left is ast.Ident {
      |                                           ~~~~
  303 |                         node.left.kind == .variable
  304 |                     } else {
vlib/v/checker/match.v:226:18: error: `cond_type_sym` is immutable, declare it with `mut` to make it mutable
  224 |                     }
  225 |                 }
  226 |             } else if mut cond_type_sym.info is ast.SumType {
      |                           ~~~~~~~~~~~~~
  227 |                 if expr_type !in cond_type_sym.info.variants {
  228 |                     expr_str := c.table.type_to_str(expr_type)
vlib/v/transformer/transformer.v:404:14: error: `cond` is immutable, declare it with `mut` to make it mutable
  402 |             expr = t.expr(mut expr)
  403 |
  404 |             match mut cond {
      |                       ~~~~
  405 |                 ast.BoolLiteral {
  406 |                     if expr is ast.BoolLiteral {
vlib/v/markused/walker.v:100:12: error: `node` is immutable, declare it with `mut` to make it mutable
   98 |
   99 | pub fn (mut w Walker) stmt(node ast.Stmt) {
  100 |     match mut node {
      |               ~~~~
  101 |         ast.EmptyStmt {}
  102 |         ast.AsmStmt {
vlib/v/markused/walker.v:219:12: error: `node` is immutable, declare it with `mut` to make it mutable
  217 |
  218 | fn (mut w Walker) expr(node ast.Expr) {
  219 |     match mut node {
      |               ~~~~
  220 |         ast.EmptyExpr {
  221 |             // TODO make sure this doesn't happen
vlib/v/gen/c/assert.v:110:12: error: `node` is immutable, declare it with `mut` to make it mutable
  108 |     metasrc := cnewlines(ctoslit(src))
  109 |     g.writeln('\t${metaname}.src = $metasrc;')
  110 |     match mut node.expr {
      |               ~~~~
  111 |         ast.InfixExpr {
  112 |             expr_op_str := ctoslit(node.expr.op.str())
vlib/v/gen/c/assign.v:102:10: error: `left` is immutable, declare it with `mut` to make it mutable
  100 |         }
  101 |         left_sym := g.table.sym(g.unwrap_generic(var_type))
  102 |         if mut left is ast.Ident {
      |                ~~~~
  103 |             ident = left
  104 |             // id_info := ident.var_info()
vlib/v/gen/c/auto_str_methods.v:181:12: error: `sym` is immutable, declare it with `mut` to make it mutable
  179 |         return
  180 |     }
  181 |     match mut sym.info {
      |               ~~~
  182 |         ast.Alias {
  183 |             if sym.info.is_import {
vlib/v/gen/c/cgen.v:1125:12: error: `sym` is immutable, declare it with `mut` to make it mutable
 1123 |     mut styp := sym.cname
 1124 |     // TODO: this needs to be removed; cgen shouldn't resolve generic types (job of checker)
 1125 |     match mut sym.info {
      |               ~~~
 1126 |         ast.Struct, ast.Interface, ast.SumType {
 1127 |             if sym.info.is_generic {
vlib/v/gen/c/cgen.v:2745:12: error: `node` is immutable, declare it with `mut` to make it mutable
 2743 |     }
 2744 |     // NB: please keep the type names in the match here in alphabetical order:
 2745 |     match mut node {
      |               ~~~~
 2746 |         ast.ComptimeType {
 2747 |             g.error('g.expr(): Unhandled ComptimeType', node.pos)
vlib/v/gen/c/cgen.v:3235:14: error: `cast_sym` is immutable, declare it with `mut` to make it mutable
 3233 |                             sum_type_deref_field += ')$dot'
 3234 |                         }
 3235 |                         if mut cast_sym.info is ast.Aggregate {
      |                                ~~~~~~~~
 3236 |                             agg_sym := g.table.sym(cast_sym.info.types[g.aggregate_type_idx])
 3237 |                             sum_type_deref_field += '_$agg_sym.cname'
vlib/v/gen/c/cgen.v:3693:14: error: `cast_sym` is immutable, declare it with `mut` to make it mutable
 3691 |                         }
 3692 |                         dot := if is_ptr || is_auto_heap { '->' } else { '.' }
 3693 |                         if mut cast_sym.info is ast.Aggregate {
      |                                ~~~~~~~~
 3694 |                             sym := g.table.sym(cast_sym.info.types[g.aggregate_type_idx])
 3695 |                             g.write('${dot}_$sym.cname')
vlib/v/gen/c/cgen.v:4553:13: error: `sym` is immutable, declare it with `mut` to make it mutable
 4551 |         // sym := g.table.sym(typ)
 4552 |         mut name := sym.cname
 4553 |         match mut sym.info {
      |                   ~~~
 4554 |             ast.Struct {
 4555 |                 if sym.info.is_generic {
vlib/v/gen/c/cgen.v:4727:13: error: `sym` is immutable, declare it with `mut` to make it mutable
 4725 |         // create list of deps
 4726 |         mut field_deps := []string{}
 4727 |         match mut sym.info {
      |                   ~~~
 4728 |             ast.ArrayFixed {
 4729 |                 dep := g.table.sym(sym.info.elem_type).name
vlib/v/gen/c/cgen.v:5579:16: error: `parent_sym` is immutable, declare it with `mut` to make it mutable
 5577 |                 if inter_info.parent_type.has_flag(.generic) {
 5578 |                     parent_sym := g.table.sym(inter_info.parent_type)
 5579 |                     match mut parent_sym.info {
      |                               ~~~~~~~~~~
 5580 |                         ast.Struct, ast.Interface, ast.SumType {
 5581 |                             name = g.generic_fn_name(parent_sym.info.concrete_types, method.name,
vlib/v/gen/c/fn.v:1343:16: error: `cast_sym` is immutable, declare it with `mut` to make it mutable
 1341 |                                 }
 1342 |                                 dot := if is_ptr { '->' } else { '.' }
 1343 |                                 if mut cast_sym.info is ast.Aggregate {
      |                                        ~~~~~~~~
 1344 |                                     sym := g.table.sym(cast_sym.info.types[g.aggregate_type_idx])
 1345 |                                     g.write('${dot}_$sym.cname')
vlib/v/gen/c/fn.v:1445:15: error: `x` is immutable, declare it with `mut` to make it mutable
 1443 |             // so that it's freed after the call. (Used tmp arg vars are not freed to avoid double frees).
 1444 |             if x := scope.find(t) {
 1445 |                 match mut x {
      |                           ^
 1446 |                     ast.Var { x.is_used = false }
 1447 |                     else {}
vlib/v/gen/c/fn.v:1494:13: error: `obj` is immutable, declare it with `mut` to make it mutable
 1492 |     scope := g.file.scope.innermost(node_pos)
 1493 |     for _, obj in scope.objects {
 1494 |         match mut obj {
      |                   ~~~
 1495 |             ast.Var {
 1496 |                 // if var.typ == 0 {
vlib/v/gen/c/infix_expr.v:376:11: error: `node` is immutable, declare it with `mut` to make it mutable
  374 |     if right.unaliased_sym.kind == .array {
  375 |         if left.sym.kind in [.sum_type, .interface_] {
  376 |             if mut node.right is ast.ArrayInit {
      |                    ~~~~
  377 |                 if node.right.exprs.len > 0 {
  378 |                     mut infix_exprs := []ast.InfixExpr{}
vlib/v/gen/c/infix_expr.v:395:10: error: `node` is immutable, declare it with `mut` to make it mutable
  393 |             }
  394 |         }
  395 |         if mut node.right is ast.ArrayInit {
      |                ~~~~
  396 |             if node.right.exprs.len > 0 {
  397 |                 // `a in [1,2,3]` optimization => `a == 1 || a == 2 || a == 3`
vlib/v/gen/c/infix_expr.v:504:25: error: `node` is immutable, declare it with `mut` to make it mutable
  502 |         g.write('_typ $cmp_op ')
  503 |         // `_Animal_Dog_index`
  504 |         sub_type := match mut node.right {
      |                               ~~~~
  505 |             ast.TypeNode { node.right.typ }
  506 |             ast.None { g.table.type_idxs['None__'] }
vlib/v/gen/c/str_intp.v:203:11: error: `expr` is immutable, declare it with `mut` to make it mutable
  201 |         mut node_ := unsafe { node }
  202 |         for i, expr in node_.exprs {
  203 |             if mut expr is ast.Ident {
      |                    ~~~~
  204 |                 if mut expr.obj is ast.Var {
  205 |                     node_.expr_types[i] = expr.obj.typ
vlib/v/parser/assign.v:155:13: error: `lx` is immutable, declare it with `mut` to make it mutable
  153 |     mut is_volatile := false
  154 |     for i, lx in left {
  155 |         match mut lx {
      |                   ~~
  156 |             ast.Ident {
  157 |                 if op == .decl_assign {
vlib/v/parser/parser.v:3772:13: error: `obj` is immutable, declare it with `mut` to make it mutable
 3770 | pub fn (mut p Parser) mark_var_as_used(varname string) bool {
 3771 |     if obj := p.scope.find(varname) {
 3772 |         match mut obj {
      |                   ~~~
 3773 |             ast.Var {
 3774 |                 obj.is_used = true
 > Clang not found
 > GCC not found
 > Attempting to build v_win.c with MSVC
'cl.exe' is not recognized as an internal or external command,
operable program or batch file.
In some cases, compile errors happen because of the MSVC compiler version
'cl.exe' is not recognized as an internal or external command,
operable program or batch file.

Backend compiler error

Exiting from error
ERROR: please follow the instructions in https://github.com/vlang/v/wiki/Installing-a-C-compiler-on-Windows

**Comment by JalonSolov** [comment]
Did you clone the repo, or download a .zip file?  It is recommended to clone the repo.

**Comment by AnimalStudioOfficial** [comment]
> Did you clone the repo, or download a .zip file? It is recommended to clone the repo.

I downloaded the zip and why does it matter?

**Comment by JalonSolov** [comment]
Because the zip will _always_ be out of date with the latest commits unless you get really lucky on timing.  V is still Alpha, and it changes rapidly.

Yes, of course the zips _should_ work, but at least until V becomes more stable, you should clone the repo instead of using the zips.

**Comment by AnimalStudioOfficial** [comment]
> Because the zip will _always_ be out of date with the latest commits unless you get really lucky on timing. V is still Alpha, and it changes rapidly.
> 
> Yes, of course the zips _should_ work, but at least until V becomes more stable, you should clone the repo instead of using the zips.

Oh ok, I will try to remember to do that next time.
