### ISSUE TITLE
will newline '\n' be treated as end of statement?

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#138]
Will newline '\n' be treated as end of statement?
```
fn main() {
	a := []
	println(a)
}
```

Got 
```
test.v:3
get_type() bad type "println" 
```

Looks like line 2 is connected to line3

**Comment by ntrel** [comment]
It might work by only looking at the next line of the current line isn't a complete expression. So I think this error is correct. `[]` has no valid type. `a := []T` means declare an empty array of type T.

**Comment by medvednikov** [comment]
Indeed, for now new lines are simply skipped. This hasn't been a problem yet, but it may be in the future. Then they will be handled like in Go.

As for this example @ntrel is correct. There's a syntax error, and it's handled correctly.
