### ISSUE TITLE
Time.local() bug

### ISSUE THREAD

**Issue by bukshee** [vlang/v#13828]
```sh
time » v doctor
OS: linux, "Manjaro Linux"
Processor: 12 cpus, 64bit, little endian, AMD Ryzen 5 PRO 4650GE with Radeon Graphics
CC version: cc (GCC) 11.2.0

getwd: /home/adi/code/v/vlib/time
vmodules: /home/adi/.vmodules
vroot: /home/adi/code/v
vexe: /home/adi/code/v/v
vexe mtime: 2022-03-25 21:02:26
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 089c93b.0248349

Git version: git version 2.35.1
Git vroot status: weekly.2022.12-30-g0248349e
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 3654d6a8
```

**What did you do?**

Inside the REPL:
```v
>>> time.now()
2022-03-25 22:02:34
>>> time.now().local()
2022-03-25 23:02:38
>>> time.now().local().local()
2022-03-26 00:02:43
>>> time.now().local().local().local()
2022-03-26 01:02:48
```

**What did you expect to see?**

Time should not increase 1 hr every time I call local().
 
**What did you see instead?**

It increases.

My bet is that in `time_nix.c.v`

```v
fn make_unix_time(t C.tm) i64 {
    return i64(C.timegm(&t))
}
```

`C.timegm()` is expecting UTC input argument. Probably `C.timelocal()` should be used instead?

**Comment by bolshoytoster** [comment]
@bukshee it looks like `.local()` just applies your timezone's offset to the time, so this seems like normal behaviour to me.

How do you think it should work?

**Comment by bukshee** [comment]
@bolshoytoster I'm not all that familiar with how V-time should work, but C-s time management works like this:

We have epoc time (seconds since 1970) stored in `time_t` as an integer and we have `struct tm` which breaks down time_t into days, hours etc. To convert from epoc to C.tm we call `gmtime()` (for UTC) and `localtime()` for local timezone.

For some reason `time.Time` stores both inside the same struct. If I call `Time.local()` it should not modify `Time.unix` field, only the rest: local()'s input is the .unix field, so it should not modify it. This way local() remains consistent even if you call it multiple times.

As a side note V's time module does not have support for C.tzset(), so there is no way to express unix time in timezones other than UTC or local time. Sometimes it could be useful. Maybe it should be a feature request.

**Comment by bolshoytoster** [comment]
@bolshoytoster I probably phrased it wrong, `.local()` doesn't modify the time, it creates a new one and returns that.

Also, what situation would require `time.local().local().local()`?

**Comment by bukshee** [comment]
@bolshoytoster Yes, I understand that. But `.local()` converts from epoc time to struct tm, so it should not modify the .unix field in the newly created Time struct.

No situation would require `time.local().local()` I used it to point out its incinsistent behaviour.

**Comment by bolshoytoster** [comment]
@bolshoytoster I think I've (*sort of) fixed it:
```diff
diff --git a/vlib/time/time_nix.c.v b/vlib/time/time_nix.c.v
index 5d88b6f..405cf98 100644
--- a/vlib/time/time_nix.c.v
+++ b/vlib/time/time_nix.c.v
@@ -31,7 +31,16 @@ fn make_unix_time(t C.tm) i64 {
 pub fn (t Time) local() Time {
        loc_tm := C.tm{}
        C.localtime_r(voidptr(&t.unix), &loc_tm)
-       return convert_ctime(loc_tm, t.microsecond)
+       return Time{
+               year: loc_tm.tm_year + 1900
+               month: loc_tm.tm_mon + 1
+               day: loc_tm.tm_mday
+               hour: loc_tm.tm_hour
+               minute: loc_tm.tm_min
+               second: loc_tm.tm_sec
+               microsecond: t.microsecond
+               unix: t.unix
+       }
 }
 
 // in most systems, these are __quad_t, which is an i64
```
Could you try that?
\* it's probably a hacky fix and llikely breaks other time-related things

**Comment by bukshee** [comment]
@bolshoytoster It is better now. but still not perfect:

```v
>>> time.now()
2022-03-26 17:13:01
>>> time.now().local()
2022-03-26 18:13:05
>>> time.now().local().local()
2022-03-26 18:13:10
```

17:13 is the correct local time at my PC. First call to `local()` shifts +1 hr (this is wrong), but subsequent local() calls do not shift more (this is good).

This is because `linux_now()` has the same problem as `local()` had: assumes local time (this is correct), but converts t.unix from local to utc (wrong). So after `time.now()` t.unix is not consistent with the rest of the Time struct.


The code of time module looks a mess to me. Overly complicated. Why not use the C functions when they work fine? A thin wrapper around C would be fine.

**Comment by bolshoytoster** [comment]
@bukshee does it need `.local()` then if `time.now()` already returns the local time?

**Comment by bukshee** [comment]
@bolshoytoster  Hehe. No. There is no point. But if it is in the module it should work. And again `time.now()` looks incorrect, too: Time.unix is not in line with the rest of the Time struct.

**Comment by vincenzopalazzo** [comment]
Thanks for reporting, this is always a difficult task, and I will try to see careful inside how it is managed

>@bukshee is there any point in having .local() if time.now() already returns the local time?

There are many unuseful things in the programming language, like `time.local().local()` but this doesn't mean that we should allowed non deterministic behavior when the user use some cert API

**Comment by changrui** [comment]
oh, my God, I got this:
```
> >>> t := time.now()
> >>> t
> 2022-03-27 18:10:14
> >>> t.local()
> 2022-03-28 02:10:26
> >>> t.local().local()
> 2022-03-28 10:10:36
> >>> t.local().local().local()
> 2022-03-28 18:10:46
```

**Comment by vincenzopalazzo** [comment]
I don't know if we are all Linux user, but if someone has this error on Windows, please test this PR https://github.com/vlang/v/pull/13861
