### ISSUE TITLE
Segfault on array indexing with type casting

### ISSUE THREAD

**Issue by serg-meus** [vlang/v#13825]
**V version: 0.2.4** 
**OS: Windows 7, Windows 10** 
No issue under Linux

**What did you do?**
i := true
a := [1, 2, 3]
println(a[int(!i)])

**What did you expect to see?**
1
 
**What did you see instead?**

V repl error: Unhandled Exception 0xC0000005
C:/Users/User/AppData/Local/Temp/v_0/.noprefix.01FZ0NT8DYKK1V2APDBXB4AQEE.vrepl.7163209711147813662.tmp.c:8406: at print_backtrace_skipping_top_frames_tcc: Backtrace
C:/Users/User/AppData/Local/Temp/v_0/.noprefix.01FZ0NT8DYKK1V2APDBXB4AQEE.vrepl.7163209711147813662.tmp.c:8373: by print_backtrace_skipping_top_frames
C:/Users/User/AppData/Local/Temp/v_0/.noprefix.01FZ0NT8DYKK1V2APDBXB4AQEE.vrepl.7163209711147813662.tmp.c:8431: by unhandled_exception_handler
7ff8d01a8a4c : by ???
7ff8ce3343ef : at ???: RUNTIME ERROR: invalid memory access
C:/Users/Sery/AppData/Local/Temp/v_0/.noprefix.01FZ0NT8DYKK1V2APDBXB4AQEE.vrepl.7163209711147813662.tmp.c:20897: by wmain
004aadf8 : by ???
004aaf5b : by ???
7ff8cfce7034 : by ???

**Comment by ntrel** [comment]
Weird, this works:
```v
println(a[int(!true)])
```
Also, it works if I compile the generated C code like this:
```
gcc -o "boolindex.tmp" "boolindex.tmp.c" -municode -w
```

**Comment by DevrosTheOne** [comment]
Not issue with M1 Mac as well
`V 0.2.4 114a341.d6c4086`
```
repl
>>> b := true
>>> [1 2 3 4][int(!b)]
1
```
