### ISSUE TITLE
Not all data is being shown from a get request and the returned text has added symbols and isnt in the correct format

### ISSUE THREAD

**Issue by 9xN** [vlang/v#13829]
**V version:** V 0.2.4 dd835ac
**OS:** macos latest

**What did you do?**
`fn main() {

println(http.get_text("https://api.mail.gw/domains"))

}`

**What did you expect to see?**
`{
    "@context": "/contexts/Domain",
    "@id": "/domains",
    "@type": "hydra:Collection",
    "hydra:member": [
        {
            "@id": "/domains/61cc5f56391b539bad0f07d8",
            "@type": "Domain",
            "id": "61cc5f56391b539bad0f07d8",
            "domain": "best-new-casino.com",
            "isActive": true,
            "createdAt": "2022-01-02T00:00:00+00:00",
            "updatedAt": "2022-01-14T00:00:00+00:00"
        }
    ],
    "hydra:totalItems": 1
}`
 
**What did you see instead?**
`{"@context":"\/contexts\/Domain","@id":"\/domains","@type":"hydra:Collection","hydra:member":[{"@id":"\/domains\/61cc5f56391b539bad0f07d8","@type":"Domain","id":"61cc5f56391b539bad0f07d8","domain":"best-new-casino.com","isActive":true,"createdAt":"2022-01-02T00:00:00+00:00","updatedAt":"2022-01-14T00:00:00+00:00"}],"hydra:totalItems":1}`

**Comment by bolshoytoster** [comment]
@9xN
> Not all data is being shown

False

The only difference between the two is that the first example is formatted and the `/`s aren't escaped.

Where did you get the '`What did you expect to see?`' example?

**Comment by 9xN** [comment]
> @9xN
> 
> > Not all data is being shown
> 
> False
> 
> The only difference between the two is that the first example is formatted and the `/`s aren't escaped.
> 
> Where did you get the '`What did you expect to see?`' example?

the example of results i want is also wrong i copy and pasted the wrong thing lmaoooo mb

**Comment by 9xN** [comment]
also i found a work around so ill close this issue now

**Comment by ntrel** [comment]
@9xN what's the workaround? Also if it's wrong that '/' is escaped then we need an open issue.

**Comment by bolshoytoster** [comment]
@ntrel it’s not wrong, that’s how the server sent the request.
