### ISSUE TITLE
unescape() not implemented on Windows

### ISSUE THREAD

**Issue by Niecke** [vlang/v#1383]
**V version: 0.1.17** 
**OS: Windows 10 (64-Bit) Build 18945 (prerelease)** 

**What did you do?**

I tried compile the test app from https://github.com/vlang/v/blob/master/vlib/vweb/tests/test_app.v with `v main.v` (renamed the file to main.v)

**What did you expect to see?**

A new executable to run the sample server. 

**What did you see instead?**

```
PS C:\Users\nieck\git\vweb_test> v .\main.v
pass=2 fn=`parse_form`
panic: vweb.v:187
undefined: `http.unescape`
```

**Comment by medvednikov** [comment]
Windows is not supported by web yet, should probably mention that.

**Comment by Niecke** [comment]
Ah ok. No problem then I will simply switch to linux.

Thanks for the information.

**Comment by changrui** [comment]
oic, but under WSL ubuntu, `v .` got: `V panic: C error. This should never happen. Please create a GitHub issue.`, so I share it here.

**Comment by nedpals** [comment]
@changrui you can try compiling it with `-show_c_cmd`, copy the compiler command, paste it and execute it. then show it here the c compiler's outputs.

**Comment by changrui** [comment]
@nedpals thx.

**Comment by Niecke** [comment]
Hm within WSL 2 it is running, after installing curl.h mentioned in #366.

After some playing around it looks to me like there might be a memory leak when running with many requests.

**Comment by medvednikov** [comment]
@Niecke unescape() now works on Windows.

The leak will be fixed today.
