### ISSUE TITLE
can't slice a multiline string

### ISSUE THREAD

**Issue by JayXon** [vlang/v#13854]
**V version:** latest
**OS:** https://devbits.app/

**What did you do?**
```
fn main() {
	println(r'foo
bar'[0..])
}
```
https://devbits.app/play/STvu6MyS3wJ7

**What did you expect to see?**
prints
```
foo
bar
```
 
**What did you see instead?**
```
main.v:3:5: error: unexpected token `[`, expecting `,`
    1 | fn main() {
    2 |     println(r'foo
    3 | bar'[0..])
      |     ^
    4 | }
```

**Comment by JalonSolov** [comment]
Works fine as long as it's not multiline:
```
fn main() {
 println(r'foo bar'[0..])
}
```
Output is:
```
foo bar
```
as expected.
