### ISSUE TITLE
v run doesn't compile if there is a directory with name of source file but without the extension .v

### ISSUE THREAD

**Issue by TillCoyote** [vlang/v#1386]
**V version: 0.1.17** 
**OS: Linux Mint 19.1 x86_64** 

**What did you do?**
There are a file "test.v" and a directory "test". I tried to run "v run test.v" but it failed with message:
`V panic: C error. This should never happen. Please create a GitHub issue.`

**What did you expect to see?**
I expected that it will just work because I didn't remember that there was "test" directory.
 
**What did you see instead?**
`V panic: C error. This should never happen. Please create a GitHub issue.`

**Comment by TillCoyote** [comment]
Example:
```
$ mkdir test
$ echo "println('hello')" > test.v
$ v run test.v
V panic: C error. This should never happen. Please create a GitHub issue.
```

**Comment by Henrixounez** [comment]
The thing is that you are trying to create a `test` executable but there is already a `test` folder, thus it won't compile because you can't have two things with the same name.

You can either change the name of the folder or specify the output executable name with `-o` option
