### ISSUE TITLE
Eliminate defer

### ISSUE THREAD

**Issue by krolaw** [vlang/v#1387]
Defer seems to be poor man's destruct (see #1325) and catch in Go, where too many things can go wrong (i.e. calling close in loops is really common):
https://blog.learngoprogramming.com/gotchas-of-defer-in-go-1-8d070894cb01
https://blog.learngoprogramming.com/5-gotchas-of-defer-in-go-golang-part-ii-cc550f6ad9aa

I'm not sure if V will throw panics like it does now, but catching with defer seems unnecessarily complicated. I'm not a fan of java's try-catch-final, but it is far more readable (and in order) for this purpose.

Defer breaks visual flow, as in, I'm writing this first so it can be done last. The Go team are continually trying to make defer run faster. I'm just not sure the overheads are worth it for something that takes longer to understand all the gotchas than what it is actually does/used for.

**Comment by medvednikov** [comment]
You make good points.

One thing though: V's defer is much faster than in Go. There's no extra performance cost.

**Comment by krolaw** [comment]
@medvednikov On reflection, I think my issue with defer, is not what it does, but Go's reliance on it for destruction and exception handling, which is a poor fit imo. 

If some other destruction and exception enforcement/handling was offered reducing defers stranglehold, it would appear as just a cool tool to use from time to time (i.e. mutex unlocking, etc). 

Since it is without cost, I no longer want it gone, just desperately want reliance on it reduced.

**Comment by medvednikov** [comment]
Yes, I see this point.

However there are other defer uses, for example:

https://github.com/vlang/v/blob/master/compiler/fn.v#L111

**Comment by krolaw** [comment]
Agreed, that is a great use for defer. I guess my issue is not with defer, it's with destruction and exceptions - I'll focus my efforts there. Thanks.
