### ISSUE TITLE
Error 10057 sending data to server (1) - Error performing handshake.

### ISSUE THREAD

**Issue by JDoawp** [vlang/v#13870]
**V version:** V 0.2.4 0cc6310
**OS:** Windows

**What did you do?** Pinging a couple of websites using:
```
fn ping(url string) bool {
	response := http.get(url) or {
		//println(term.bright_bg_red('Webpage not found') + ' ' + term.bright_red(get_name(url) +
		//	' ' + get_id(url) + ' ' + url))
		return false
	}

	status_code := response.status_code

	if status_code == 200 {
		return true
	}

	return false
}
```
on Linux you get expected output using that.
In windows if it doesn't find the URL or can't ping it'll print out 
```
Error performing handshake
Error 10057 sending data to server (1)
```
Which is annoying cause there doesn't seem to be any way of suppressing it.

**What did you expect to see?**
Nothing.
 
**What did you see instead?**
```
Error performing handshake
Error 10057 sending data to server (1)
```

**Comment by bolshoytoster** [comment]
The error seems to come from here:
https://github.com/vlang/v/blob/76904719d02724975bc255b52d03132a87caf283/thirdparty/vschannel/vschannel.c#L468-L474

It doesn’t look like there’s a way to suppress it unfortunately.

The error code is described [here](https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2) (10057) which I think means `tls_ctx->socket` was not connected to the server.

**Comment by JDoawp** [comment]
> The error seems to come from here:
> 
> https://github.com/vlang/v/blob/76904719d02724975bc255b52d03132a87caf283/thirdparty/vschannel/vschannel.c#L468-L474
> 
> It doesn’t look like there’s a way to suppress it unfortunately.
> 
> The error code is described [here](https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2) (10057) which I think means `tls_ctx->socket` was not connected to the server.

Hm :/ 

What I find weird is that it doesn't output these on linux. Even if I try to compile with -mingw or -gcc (which is what I think is used for x-compile to windows? That's what it has complained about not existing when I tried first at least).

**Comment by bolshoytoster** [comment]
@JDoawp that'll be because windows/linux have to use seperate networking code.
