### ISSUE TITLE
Error on operator overloading for classes with >8 properties.

### ISSUE THREAD

**Issue by bolshoytoster** [vlang/v#13888]
```sh
$ ./v doctor
OS: linux, Ubuntu 20.04.4 LTS
Processor: 8 cpus, 64bit, little endian, 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz
CC version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

getwd: /home/a/Downloads/v
vmodules: /home/a/.vmodules
vroot: /home/a/Downloads/v
vexe: /home/a/Downloads/v/v
vexe mtime: 2022-03-31 21:03:59
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 9c1981a.42a6783

Git version: git version 2.25.1
Git vroot status: weekly.2022.13-6-g42a67831-dirty (21 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 3654d6a8
```

**What did you do?**
Compile this code:
```v
struct Foo {
        one   int
        two   int
        three int
        four  int
        five  int
        six   int
        seven int
        eight int
        nine  int
}

fn (_ Foo) == (_ Foo) bool {
        return true
}
```
**What did you expect to see?**
No error
 
**What did you see instead?**
```v
} expected `Foo` not `Foo` - both operands must be the same type for operator overloading
   11 | }
   12 | 
   13 | fn (_ Foo) == (_ Foo) bool {
      |                  ~~~
   14 |     return true
   15 | }
```
---
Looking into it, the error seems to come from here:
https://github.com/vlang/v/blob/9c1981a3097b14a8027e23acb4bceeafbd0003f0/vlib/v/checker/fn.v#L259-L261

I added a `println` so I could see what `node.receiver.typ` and `node.params[1].typ` were:
Normal:
`node.receiver.typ`: `ast.Type(0x5c = 92)`
`node.params[1].typ`: `ast.Type(0x5c = 92)`
More than 8 properties:
`node.receiver.typ`: `ast.Type(0x1005c = 65628)`
`node.params[1].typ`: `ast.Type(0x5c = 92)`

So it looks like it's just `node.receiver.typ` that's wrong.

So I divided by zero to get a stack trace, then followed it until I eventually found where I think the problem comes from:
https://github.com/vlang/v/blob/9c1981a3097b14a8027e23acb4bceeafbd0003f0/vlib/v/parser/fn.v#L601-L603

It looks like it sets `rec.typ` to a reference of it's class, but the other parameter to the overload is not set to a reference, hence them being different types.

My suspicions were confirmed, because this compiles perfectly fine:
```v
struct Foo {
        one   int
        two   int
        three int
        four  int
        five  int
        six   int
        seven int
        eight int
        nine  int
}

fn (self Foo) == (other &Foo) bool {
        return true
}
```
---
I'm not sure why it's made to be a pointer with >8 properties, but I think the solution to this error is either get rid of this condition or make sure it applies to both parameters to operator overloads.

**Comment by vincenzopalazzo** [comment]
this is strange, I will take a look, thanks!

**Comment by bolshoytoster** [comment]
@vincenzopalazzo I think a simple solution would be to change here:
https://github.com/vlang/v/blob/9c1981a3097b14a8027e23acb4bceeafbd0003f0/vlib/v/checker/fn.v#L259-L261

to a check to see if they are pointers to the same type. Probably something like:
```v
} else if node.receiver.typ & 65535 != node.params[1].typ & 65535 { 
 	c.error('expected `$receiver_sym.name` not `$param_sym.name` - both operands must be the same type for operator overloading', 
 		node.params[1].type_pos) 
```

**Comment by StunxFS** [comment]
maybe the problem is caused by this PR #9268

**Comment by bolshoytoster** [comment]
@StunxFS I think so, I reckon this could be fixed if we applied this to function arguments as well, although that might cause some issues.

**Comment by vincenzopalazzo** [comment]
it is, and also the solution is there

```
		if node.params[0].is_auto_rec {
			styp = styp.trim('&')
		}
```

just curious, what this line means? `node.params[1].typ & 65535`

**Comment by StunxFS** [comment]
The best thing would be to show an error to the user when using a receiver, whose type exceeds 8 fields, by value and not by reference

**Comment by vincenzopalazzo** [comment]
>The best thing would be to show an error to the user when using a receiver, whose type exceeds 8 fields, by value and not by reference

Not sure that I have ever seen a compiler that tries to optimize and after tells the user "sorry the optimization is wrong"

**Comment by vincenzopalazzo** [comment]
@bolshoytoster the https://github.com/vlang/v/pull/13889 should contain the hot-fix!

**Comment by StunxFS** [comment]
@vincenzopalazzo I mean that the compiler makes it the user who optimizes
