### ISSUE TITLE
Add a config_dir() function to os module

### ISSUE THREAD

**Issue by JulienLecoq** [vlang/v#13886]
Programs often depends on configuration files that the user can modify to change the behaviour of his programs.

In Go, you have this function : [UserConfigDir](https://pkg.go.dev/os@go1.18#UserConfigDir) in the os package which makes it very easy to store/retrieve configuration files data. The idea is just to reproduce something similar in V, with for example, a ``config_dir()`` function in the os module.

**Comment by trufae** [comment]
i'm on it. i'll push the PR in few mins

**Comment by trufae** [comment]
Implemented in https://github.com/vlang/v/pull/13893
