### ISSUE TITLE
Wikipedia article prerequisite to TIOBE index listing

### ISSUE THREAD

**Issue by ylluminate** [vlang/v#1388]
I tried today to get the TIOBE index to start tracking V, however I received a reply that a Wikipedia page about the language is a prerequisite for their listing.  We need to flesh out such a page as soon as possible.

**Comment by gslicer** [comment]
there is a minimal draft already: [V (programming language)](https://en.wikipedia.org/wiki/Draft:V_(programming_language))

**Comment by ylluminate** [comment]
Thanks for pointing that out, it appears that @adlesh has started in on it. Curious @adlesh, anything stopping publication of this or should others add some more to it prior to publish?

**Comment by crthpl** [comment]
@medvednikov An article was tried a long time ago and was rejected, could we try again now? (22.8k stars!)

**Comment by ylluminate** [comment]
@crthpl we're awaiting a "scholarly article" requirement that they supposedly have. Lol. It's quite a ludicrous, and upsetting, situation.

**Comment by crthpl** [comment]
@ylluminate so does someone have to write a scholarly article on using V?

**Comment by JalonSolov** [comment]
That's what it means, yes.  I'm going to close this issue.  Everything will happen naturally once V catches enough (positive) attention, but nothing will happen for this until it does.
