### ISSUE TITLE
'lalala'.split('a'), got ["l", "l", "la"], it's probably a bug

### ISSUE THREAD

**Issue by lengduan** [vlang/v#1391]
**V version:** 0.1.17
**OS:** windows10

**What did you do?**
```
   // test.v
   s := 'lalala'
   println( s.split('a')  )
   
   v run test.v
   got: ["l", "l", "la"]
   execpted: ["l", "l", "l"]
```

**What did you expect to see?**
我认为问题出在
i think this problem is
```
// string.v
// pub fn (s string) split_single
// lines 289
if i == s.len - 1 {   // !!!   i think  !a && b   or   !a && i == s.len - 1
   ...
}
```
 
**What did you see instead?**
第一次提交 issues，如有不对和冒犯之处，恳请大家指正，鞠躬。
英文是使用谷歌翻译翻译的，如有不对之处，还请懂英文的帮忙翻译一下，鞠躬感谢。

**Comment by medvednikov** [comment]
Fixed, thanks for reporting this.
