### ISSUE TITLE
Tasks should be done to promote V

### ISSUE THREAD

**Issue by iredmail** [vlang/v#1392]
Dear all,

V is still in early stage, we hereby list some basic work and modules which should be done to help bootstrap and promote V, you're welcome to join V community and feel free to pick up the one you're interested in and reply below to avoid duplicate work. Or reply below if you think something should be listed below.

Feel free to ask in issue tracker, or join the Discord community: https://discord.gg/n7c74HM

If you need to contact the core team:

- @medvednikov: the creator of vlang
- @joe-conigliaro: member of the core team

If you don't need to talk to any team member, then just send the PR. :)

## Documents

* [ ] Getting Start
* Module documents
  - [ ] vweb
  - [ ] pg
  - ...

## Modules

- [x] [vweb](https://github.com/vlang/v/tree/master/vlib/vweb): the web framework in V core. Still a lot work to do, but at least we have a working one.
    - [x] Sample web application: [vorum](https://github.com/vlang/vorum)
- SQL/LDAP drivers:
  - [x] [postgresql](https://github.com/vlang/pg)
  - [ ] mysql
  - [ ] ldap
  - [x] [sqlite](https://github.com/vlang/sqlite)
- [ ] a simple ORM which helps build SQL statement for mysql/postgresql/SQLite
- [ ] email module for construct and parse email message (like Python’s email module)
- [ ] DNS module for basic DNS query and parse

**Comment by leftis** [comment]
@iredmail shall I work on the email module? Will this be integrated inside vlibs or a separate repo? Any specific instructions maybe?

**Comment by iredmail** [comment]
> @iredmail shall I work on the email module?

You're free to pick up the one you're interested in. :)

> Will this be integrated inside vlibs or a separate repo?

I think it's better be a separate repo. If you want to be merged into vlibs, talk to @medvednikov.

> Any specific instructions maybe?

Unfortunately, at this early stage, it's lack of documents and instructions. Feel free to ask in issue tracker and join the Discord community: https://discord.gg/n7c74HM

NOTE: i'm not a member of core team, just trying to do something helpful. :) If you need to contact the core team:

- @medvednikov is the creator of vlang.
- @joe-conigliaro is a member of core team.

btw, you don't need to be a member of core team to contribute, just send the PR. :)
