### ISSUE TITLE
Casting between signed and unsigned

### ISSUE THREAD

**Issue by serg-meus** [vlang/v#13955]
**V version:** 0.2.4
**OS:** Windows 7

**What did you do?**

b := byte(-1) == -1
w := u16(-1) == -1
d := u32(-1) == -1
q := u64(-1) == -1
println('$b, $w, $d, $q')

**What did you expect to see?**

true, true, true, true
 
**What did you see instead?**

false, false, true, true

**Comment by JalonSolov** [comment]
I would've expected `false, false, false, true`.  That needs to be looked into.

The reason is that once you cast to an unsigned, it should never be equal to a negative number - unsigned values are never negative.

**Comment by serg-meus** [comment]
Then why your last expectation is true, u64 is also unsigned. All false values looks more logical, too.

**Comment by serg-meus** [comment]
And compiler error on comparing signed and and unsigned values is also an option

**Comment by serg-meus** [comment]
``

**Comment by JalonSolov** [comment]
You're right, sorry.  I misread the last one.  They should all be false.

**Comment by ntrel** [comment]
This is the C generated:
```c
	bool b = ((byte)(-1)) == -1;
	bool w = ((u16)(-1)) == -1;
	bool d = ((u32)(-1)) == -1;
	bool q = ((u64)(-1)) == -1;
```
`(byte)-1` which is `0xff` is promoted to an int (as byte is smaller than int) and is 255.
`(u16)-1` which is `0xffff` is promoted to an int (as u16 is smaller than int) and is 65535.
`u32` is not smaller than an int so it is not promoted, instead the right hand -1 is cast to `u32`, and they are equal.
`u64` is not smaller than an int so it is not promoted, instead the right hand -1 is cast to `u64`, and they are equal.
This is my understanding of C rules anyway.

**Comment by ntrel** [comment]
> compiler error on comparing signed and and unsigned values 

We need an error for that (at least) when the type widths differ and one of the type widths is less than `sizeof(int)`.

**Comment by serg-meus** [comment]
I think C-way is not best for the subject. For instance, Rust and Go gives compiler error on casting -1 to any unsigned type. I suppose we need some simple rule for that.

**Comment by medvednikov** [comment]
Indeed, like in Go, `u32(-1)` shouldn't compile:

```
cannot convert -1 (untyped int constant) to type uint16
```
