### ISSUE TITLE
invalid expression: unexpected keyword `struct`

### ISSUE THREAD

**Issue by harens** [vlang/v#13950]
**V doctor:**
```
OS: macos, macOS, 12.2.1, 21D62
Processor: 8 cpus, 64bit, little endian, Apple M1 Pro
CC version: Apple clang version 13.1.6 (clang-1316.0.21.2)

getwd: /Users/harensamarasinghe/vlang-devel
vmodules: /Users/harensamarasinghe/.vmodules
vroot: /Users/harensamarasinghe/vlang-devel
vexe: /Users/harensamarasinghe/vlang-devel/v
vexe mtime: 2022-04-05 14:13:40
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 11ccf06

Git version: git version 2.35.1
Git vroot status: weekly.2022.13-64-g11ccf064
.git/config present: true
thirdparty/tcc status: thirdparty-macos-arm64 01a49770

```

`v run ../vlang/test.v`
```v
println('hello')

struct Example {
	name string
}
```

```
../vlang/test.v:3:1: error: invalid expression: unexpected keyword `struct`
    1 | println('hello')
    2 | 
    3 | struct Example {
      | ~~~~~~
    4 |     name string
    5 | }
```

However, these are both fine:

1) Put in a `main` function.

```v
fn main() {
	println('hello')
}

struct Example {
	name string
}
```

2) Put the `println` below the `struct`.

```v
struct Example {
	name string
}

println('hello')
```

**Comment by vincenzopalazzo** [comment]
This is a completely valid behavior, we are running the code line by line, so we would expect that we declare the structure before you use it.

However, the error is super confusing, and we must improve it, I will work on it

**Comment by spytheman** [comment]
> This is a completely valid behavior, we are running the code line by line, so we would expect that we declare the structure before you use it.
> 
> However, the error is super confusing, and we must improve it, I will work on it

We are not running the code line by line - it is read in whole, parsed, then compiled etc.
The problem is that when V encounters println() it assumes that what follows is the body of a script (i.e. like a function body), and V does not support declaring structs in that mode, but only in the outer scope.

**Comment by yuyi98** [comment]
It's ok now.
```v
println('hello')

struct Example {
	name string
}

PS D:\Test\v\tt1> v run tt1.v
tt1.v:1:1: notice: script mode started here
    1 | println('hello')
      | ~~~~~~~
    2 |
    3 | struct Example {
tt1.v:3:1: error: all definitions must occur before code in script mode
    1 | println('hello')
    2 |
    3 | struct Example {
      | ~~~~~~
    4 |     name string
    5 | }
```
