### ISSUE TITLE
array.any/all incorrectly understands question mark syntax

### ISSUE THREAD

**Issue by ChewingBever** [vlang/v#13988]
**V version:** V 0.2.4 6425000.1d33734
**OS:** EndeavourOS Linux

**What did you do?**
Tried to use a function returning `?bool` inside an `array.any` expression.

**What did you expect to see?**
I expected it to compile as expected.
 
**What did you see instead?**

```v
fn test() ?bool {
    return true
}

fn main() {
    l := [1, 2, 3]
    x := l.any(test()?)
}
```

This minimal example causes the following compilation error:

```
test.v:7:13: error: type mismatch, `test` must return a bool
    5 | fn main() {
    6 |     l := [1, 2, 3]
    7 |     x := l.any(test()?)
      |                ~~~~~~
    8 | }
```

**Workaround**

The bug can be avoided by changing the expression to `l.any(test()? == true)`.

**Comment by spytheman** [comment]
Fixed in df30b7997 .
