### ISSUE TITLE
Array: **[1,,3] != [1,0,3]**?

### ISSUE THREAD

**Issue by changrui** [vlang/v#13997]
**V version:** 
**OS:** 

**What did you do?**
```
arr := [1,,3]
println(arr==[1,0,3])
```
**What did you expect to see?**
`true`
 
**What did you see instead?**
```
main.v:1:9: error: invalid expression: unexpected token `,`
    1 | a := [1,,3]
      |         ^
```

**Comment by Hunam6** [comment]
More like a feature request

**Comment by JalonSolov** [comment]
That looks correct.  You didn't supply a value for the middle element.

**Comment by Hunam6** [comment]
I don't think this should be allowed

**Comment by JalonSolov** [comment]
I don't think so either.  It's a single character difference to type the 0, and it is explicit as to what you want to happen.

I suppose V could instead print a "missing value" message instead of "unexpected token", but that's the only change I would make for this.
