### ISSUE TITLE
vfmt: constant is mistaken as enum field

### ISSUE THREAD

**Issue by Wertzui123** [vlang/v#14000]
**V version:** V 0.2.4 a0e7a46
**OS:** Windows

**What did you do?**
Format this file:
https://github.com/Wertzui123/TLSe/blob/main/sslconn.c.v#L53
(the specified line is the one where the bug occurs)

**What did you expect to see?**
Nothing changing.
 
**What did you see instead?**
Even though it says `Already formatted file`, it changes `tls_v12` to `.tls_v12`.

**Comment by Wertzui123** [comment]
Actually, it looks like `vfmt` does interpret it as a constant, but somehow the module prefix is empty, so it looks like an enum field.
A workaround for this is to manually add the module prefix.

**Comment by merlindiavova** [comment]
Another work around, which works in my case is to define consts in their own separate file.

**Comment by yuyi98** [comment]
Fixed.
