### ISSUE TITLE
const declarations should be order independent

### ISSUE THREAD

**Issue by schurhammer** [vlang/v#1400]
**V version:** V 0.1.17
**OS:** manjaro linux

**What did you do?**
```go
const (
	a = b
	b = 1
)

fn main() {
	println(a)
}
```

**What did you expect to see?**
I expected both a and b to be a constant value of 1.
 
**What did you see instead?**
```
pass=2 fn=`main`
panic: test.v:7
Fn "println" wrong arg #1. Expected "string" (s)  but got "void"
```
Note: swapping the order of ```a = b``` and ```b = 1``` works as expected (both are 1). I suggest that constants should be order independent similar to functions.

**Comment by SuperFola** [comment]
Are you suggesting adding lazy evaluation?

**Comment by medvednikov** [comment]
Yes, this should work. Thanks for reporting.

**Comment by schurhammer** [comment]
I've noticed functions and constants are very similar in terms of how they can be defined and accessed. Perhaps they could be unified, either functions are constants that happen to be of a function type, or constants are functions that just return a constant value.
Obviously they would keep their own syntax, but behind the scenes it might make things simpler.

**Comment by M4SSD35TRUCT10N** [comment]
@medvednikov : > Yes, this should work. Thanks for reporting.

Still doesn't w/ actual master:
 
v -os msvc run bug_retest.v

bug_retest.v:7:12: cannot use type `void` as type `string` in first argument to `println()`
    6|  fn main() {

    7|  println(a)
                          ^
    8| }

**Comment by medvednikov** [comment]
It should work but it doesn't. It wasn't worked on.
