### ISSUE TITLE
A sum type with a generic struct raises an error

### ISSUE THREAD

**Issue by khalyomede** [vlang/v#14004]
**V version:** 0.2.4 a0e7a46
**OS:** linux, Linux version 5.13.0-39-generic (buildd@lcy02-amd64-080) (gcc (Ubuntu 9.4.0-1ubuntu1~~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022

**What did you do?**

Ran this script

```v
struct Just<T> {
  value T
}

struct Nothing {}

type Maybe = Nothing | Just
```

**What did you expect to see?**

No errors

 
**What did you see instead?**

```
/tmp/v_0/index.8598377962763286470.tmp.c:886:3: error: unknown type name 'main__Just_T_T'
  886 |   main__Just_T_T* _main__Just;
      |   ^~~~~~~~~~~~~~
```

**Comment by vincenzopalazzo** [comment]
maybe this can be a good way to test this PR ? https://github.com/vlang/v/pull/13974

**Comment by vincenzopalazzo** [comment]
tested and seems unrelated! :/

**Comment by vincenzopalazzo** [comment]
This is a checker error, and this is the workaround

```
struct Just<T> {
  value T
}

struct Nothing<T> {}

type Maybe<T> = Nothing<T> | Just<T>

fn test_fn() {
	val := Maybe<int>(Nothing<int>{})
	println(val)
}
```
