### ISSUE TITLE
vpm: all commands broken

### ISSUE THREAD

**Issue by smartiniOnGitHub** [vlang/v#14009]
**V version:** V 0.2.4 a0e7a46.843ce43
**OS:** linux, Ubuntu 20.04.4 LTS

**What did you do?**
Run one of the commands of vpm: for example `v list`, etc.

**What did you expect to see?**
The command to work and see results.
 
**What did you see instead?**
An error:
```
failed    cmd: '/opt/vlang_v/v' -skip-unused '/opt/vlang_v/cmd/tools/vpm.v'
failed   code: 1
==================
tcc: error: undefined symbol 'cJSON_GetErrorPos'
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.
```
This error occurs since some day, before all was working.

Other info that could be useful:
```
OS: linux, Ubuntu 20.04.4 LTS
CC version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
...
Git version: git version 2.25.1
Git vroot status: weekly.2022.13-113-g843ce430 (1 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 3654d6a8
```

Note that V has been built *not* with tcc.

Tell me if you need more info.
Thanks

**Comment by trufae** [comment]
Is this happening you on a clean checkout?

**Comment by smartiniOnGitHub** [comment]
Hi all, thanks for the suggestions @trufae @medvednikov : 
I had to completely remove the existing folder and redo a fresh clone and full build; now all works as before ... I hope this info will be useful even to others.
Thanks again and sorry for the noise. Bye
