### ISSUE TITLE
json: sum types not handled correctly

### ISSUE THREAD

**Issue by ChewingBever** [vlang/v#14017]
**V version:** V 0.2.4 88c4a64.a154cd6
**OS:** linux, "EndeavourOS Linux"

**What did you do?**
I tried to decode a string into a struct with a sum type as one of its fields.

```v
import json

type Test = string | []string

struct Some {
    t Test
}

fn main() {
    v := json.decode(Some, '{"t": ["string", "string2"]}') ?
    println(v)
}
```

**What did you expect to see?**
I expected v to correctly have a `[]string` type as the value of `t`.
 
**What did you see instead?**
The `println` call gives the output
```
Some{
    t: unknown sum type value
}
```
trying to use match to check the type or `if v.t is string` for example does not work either.

**Comment by changrui** [comment]
Another example:
```
import json

struct User {
	id  string | int
	pay string | f32
}
fn main() {
	str := '{"id":"1", "pay": "123.45"}'
	user := json.decode(User, str) ?
	println(user)
    println(f32(user.pay))	//
}
```
Error：

main.16939929823359497822.tmp.c:12102: **error**: invalid aggregate type for register load

**Comment by spytheman** [comment]
> import json
> 
> struct User {
> 	id  string | int
> 	pay string | f32
> }
> fn main() {
> 	str := '{"id":"1", "pay": "123.45"}'
> 	user := json.decode(User, str) ?
> 	println(user)
>     println(f32(user.pay))	//
> }

That is a separate bug/issue, not directly related to json.decode / sumtypes; if you comment the last line, it will work.
