### ISSUE TITLE
time: wrong result when adding seconds to 2k date

### ISSUE THREAD

**Issue by ChewingBever** [vlang/v#14019]
**V version:** V 0.2.4 88c4a64.a154cd6
**OS:** linux, "EndeavourOS Linux"

**What did you do?**
```v
import time

fn main() {
    t := time.parse('2000-01-01 04:00:00') ?
    t2 := t.add_seconds(60)

    println(t)
    println(t2)
}
```
I added 60 seconds to `2000-01-01 04:00:00`.

**What did you expect to see?**
`2000-01-01 04:01:00`
 
**What did you see instead?**
`1999-12-31 04:01:00`

**Comment by changrui** [comment]
oh, NO, `1999-12-31 23:59:00`.add(60) = `1999-12-31 00:00:00`???

**Comment by DevrosTheOne** [comment]
Looks like just calling add_seconds() triggers the error
```v
t := time.parse('2000-01-01 04:00:00') ?
println(t)
println(t.add_seconds(0))
println(t.add_seconds(1))
```
```
2000-01-01 04:00:00
1999-12-31 04:00:00
1999-12-31 04:00:01
```

**Comment by vincenzopalazzo** [comment]
Fixed by https://github.com/vlang/v/pull/14399/files
