### ISSUE TITLE
web scraping 

### ISSUE THREAD

**Issue by SAVE-POlNT** [vlang/v#14020]
Hello , im looking for a new lang for like 2 months , tried nim , go,d and rust , and then V
the two that are so close ( for me )
are Go and  V , the selling point of V is the integrated ui tool

so im wondering , is there any web scraping and cli creation tool in V ?

**Comment by JalonSolov** [comment]
Simple example scraper:  https://github.com/vlang/v/blob/master/examples/links_scraper.v
Module for CLI:  https://modules.vlang.io/cli.html

You should join the V discord.  Lots of people have been working on these things... such as a more advanced scraper that uses goroutines to scrape in parallel, etc.

**Comment by SAVE-POlNT** [comment]
thank you very much , i will join it i forgot about it
