### ISSUE TITLE
Missing tags in the git repository

### ISSUE THREAD

**Issue by kdabir** [vlang/v#1404]
**V version:** 
54f847a / v0.1.17

**OS:**  
Mac OS

**What did you do?** 
Clone the git repo

**What did you expect to see?** 
All released tags

**What did you see instead?** 
I see tags only up to v0.1.13.

**Comment by sylviot** [comment]
The commit hash 13e1b4edb181e693ecf274be523f2c87b13e93e3 is the v 0.1.15 version.

**Comment by medvednikov** [comment]
`git tag` gives me


```
git tag
0.1.15
0.1.16
0.1.17
v0.1.10
v0.1.11
v0.1.12
v0.1.13
v0.1.3
v0.1.4
v0.1.5
v0.1.6
v0.1.7
v0.1.8
```

They are all there :)

**Comment by kdabir** [comment]
Oops my bad. So the tagging scheme dropped `v` prefix after the 0.1.13 and perhaps I was just searching for tags starting with `v`. Apologies for the false alarm.
