### ISSUE TITLE
error: expected 2 arguments, but got 1 in V 0.2.4, Windows 10

### ISSUE THREAD

**Issue by nkot56297** [vlang/v#14045]
Hi all! Hi community Vlang!

**V version:** V 0.2.4 ae6a25f
**OS:** Windows 10.

**What did you do?**
I was reading how to create a web server in vlang, reference here: [building-web-server-with-vlang](https://www.section.io/engineering-education/building-web-server-with-vlang/).  I followed the tutorial step by step, but the web server does not work. This error appears: ```>index.v:8:10: error: expected 2 arguments, but got 1```

**What did you expect to see?**
I wanted to run the web server on port 8080.
 
**What did you see instead?**
So,  this error appears: ```>index.v:8:10: error: expected 2 arguments, but got 1```

#### 1. error, image
![image](https://user-images.githubusercontent.com/95204402/163591075-5335f943-6f72-4d2f-80ff-c5c5b4c3f978.png)

#### 2. source-code: ```index.v```
```vlang
import vweb

struct App {
    vweb.Context
}

fn main() {
    vweb.run<App>(8080) # error here
}

pub fn (mut app App) index() vweb.Result {
	return app.text('Hello world from vweb!')
}
```

### Notes
1. If anyone can answer this question, I would be happy
2. I'm interested in learning about vlang, I think it's an interesting language

**Comment by StunxFS** [comment]
It should be like that:

```v
vweb.run(&App{}, 8080)
```

For more info: https://github.com/vlang/v/tree/master/vlib/vweb

**Comment by JalonSolov** [comment]
Someone mentioned https://www.section.io/engineering-education/building-web-server-with-vlang/ not too long ago.  The problem is that article is out of date with current V.

**Comment by nkot56297** [comment]
works!
