### ISSUE TITLE
Can't build V 0.1.17 on Windows

### ISSUE THREAD

**Issue by ntrel** [vlang/v#1405]
So I checked out the `0.1.17` branch for `v` and `vc`. I built `vc.exe`, moved it to `v/` then:
```
$ ./vc.exe -o v.exe compiler/
Looks like you are running V for the first time.
Setting VROOT to "C:\git\v".
V panic: C:\git\v/vlib/tmpl doesn't exist
```
Then I tried repeating all this but with git master for each repo, and got:
```
$ ./vc.exe -o v.exe compiler
V 0.1.17
Use Ctrl-C or `exit` to exit
>>>
```
I'm running commands from the git MSYS shell BTW.

Could you please make Windows binaries again?

**Comment by ntrel** [comment]
OK, I wasn't passing the right flags to `gcc`, I tried the ones from `make.bat` then tried building `v` again:
```
$ ./vc.exe compiler/
In file included from .a.out.c:2:0:
.a.out.c: In function 'os__get_file_handle':
.a.out.c:5640:33: error: request for member '_file' in something not a structure or union
 void* _handle= _get_osfhandle ( _fileno ( _fd ) ) ;
                                 ^
V panic: clang error
```

**Comment by vitalyster** [comment]
gcc/mingw version? Git shell does not come with gcc

**Comment by ntrel** [comment]
gcc.exe (MinGW.org GCC-6.3.0-1) 6.3.0

**Comment by vitalyster** [comment]
Where to get this version? mingw.org offers gcc 8.2.0

**Comment by ntrel** [comment]
> mingw.org offers gcc 8.2.0

How do I get that? `mingw-get` only offers 6.3.

**Comment by vitalyster** [comment]
```
vital@DESKTOP-RJ008BC ~
$ mingw-get --version
mingw-get version 0.6.3-pre-20170905-1
Copyright (C) 2009-2013, MinGW.org Project

This is free software; see the product documentation, or source code,
for copying and redistribution conditions.  There is NO WARRANTY; not
even an implied WARRANTY OF MERCHANTABILITY, nor of FITNESS FOR ANY
PARTICULAR PURPOSE.


vital@DESKTOP-RJ008BC ~
$ mingw-get install gcc
install: gcc-8.2.0-4-mingw32-lic.tar.xz
mingw-get.exe: *** ERROR *** package gcc-8.2.0-4-mingw32-lic.tar.xz is already installed
```

**Comment by vitalyster** [comment]
Anyway I can't compile in mingw shell correctly, neither in cmd window with mingw.org gcc in path. While everything going well including tests in mingw64 cmd

**Comment by ntrel** [comment]
```
C:\MinGW\bin>mingw-get --version
mingw-get version 0.6.3-pre-20170905-1
Copyright (C) 2009-2013, MinGW.org Project

This is free software; see the product documentation, or source code,
for copying and redistribution conditions.  There is NO WARRANTY; not
even an implied WARRANTY OF MERCHANTABILITY, nor of FITNESS FOR ANY
PARTICULAR PURPOSE.


C:\MinGW\bin>mingw-get install gcc
install: gcc-6.3.0-1-mingw32-lic.tar.xz
mingw-get: *** ERROR *** package gcc-6.3.0-1-mingw32-lic.tar.xz is already insta
lled
```

**Comment by ntrel** [comment]
I was using the default mingw.org. Apparently I need mingw-w64 [here](https://github.com/vlang/v/wiki/Installing-a-C-compiler-on-Windows).

**Comment by ntrel** [comment]
OK, I can build V now.

**Comment by medvednikov** [comment]
Yes, right now only mingw-w64 is supported.

In the future MinGW will be supported as well.

**Comment by vitalyster** [comment]
@ntrel you only need mingw-w64-install, which install only gcc and nothing more. It will create "run terminal" shortcut which give cmd.exe with gcc in path.

**Comment by ntrel** [comment]
> In the future MinGW will be supported as well

I think it's fine if V requires gcc 8, gcc 6 is quite old.

> mingw-w64-install.exe, which install only gcc and nothing more

On my system it installed:
`/c/mingw-w64/mingw32/opt/lib/python2.7/`
