### ISSUE TITLE
ORM sql statement should return an option type

### ISSUE THREAD

**Issue by LaurentZuijdwijk** [vlang/v#14069]
**V version: V 0.2.4 17c34b0** 
**OS: macos, Mac OS X, 10.15.4, 19E287** 

**What did you do?**
	
`pub struct User {
	id string [primary; sql: serial]
	name string [nonull; unique]
	description string
	created_at string
	modyfied_at string
}
sql s.db {
	insert new_user into User
}` 

When the user already exists, the. sql statement will throw an error without any means of catching it. 

**What did you expect to see?**
the sql statement should return an option type
 
**What did you see instead?**
An error

**Comment by dumblob** [comment]
Instead of an `Option` type (aka `none`) it should IMHO return a `Result` type (aka `error`). See https://github.com/vlang/v/pull/14140 .
