### ISSUE TITLE
error: cannot register alias `byte`, another type with this name exists

### ISSUE THREAD

**Issue by zhihau** [vlang/v#14065]
**V version:** V 0.2.4 6718958
**OS:** Microsoft Windows 10

**What did you do?**
I download v_windows.zip from https://vlang.io/. And I try to execute the command `v run test.v` , it prints the error message. How to fix this error?
### Input file test.v
```
//test.v
fn main() {
    areas := ['game', 'web', 'tools', 'science', 'systems',
              'embedded', 'drivers', 'GUI', 'mobile']
    for area in areas {
        println('Hello, $area developers!')
    }
}
```

**What did you expect to see?**
The output will be:
Hello, game developers!
Hello, web developers!
Hello, tools developers!
...
 
**What did you see instead?**
```
vlib/builtin/int.v:11:6: error: cannot register alias `byte`, another type with this name exists
    9 |
   10 | // type u8 = byte
   11 | type byte = u8
      |      ~~~~
   12 | type i32 = int
   13 |
```

**Comment by changrui** [comment]
@zhihau Update your vlang with `v up` or `git pull &&  make.bat`.

**Comment by StunxFS** [comment]
Make a `git clone` of the repo and then `make.bat`.

**Comment by zhihau** [comment]
> @zhihau Update your vlang with `v up` or `git pull && make.bat`.

Good. It's ready to use. Many thanks.
