### ISSUE TITLE
provide robust command line argument parser in the standard library 

### ISSUE THREAD

**Issue by catastrop** [vlang/v#1406]
It should be robust

**Comment by catastrop** [comment]
??

**Comment by runeimp** [comment]
@catastrop Robust ala Go Cobra, Ruby Commander, Python Click, etc.? I'm very interested in this topic myself and given time would love to jump on a solution. But what defines robust for you?

**Comment by catastrop** [comment]
suitable for any kind of task and can handle any situation

**Comment by runeimp** [comment]
@catastrop So...

* POSIX flags: `-f`
* POSIX flag group parsing: `-abc` is interpreted as `-a -b -c`
* Flag instance count: `-vvvv` is count 4
* GNU Flags: `--version`
* Google Flags `-version`
* Option value list with delimiter specification: `-c 1,2,3,4` can be interpreted as an array of ints for the -c flag.
* Subcommands
    * Subcommands of subcommands
    * Subcommand chaining
* Config expansion: `@filename` adds to or overrides the default config
* Environment Variables as defaults
* System config (Windows Registry & ...?) as defaults
* Required parameters
    * arguments
    * flags
    * good intensions?
* Prompt when a required parameter is not present
* Shell completions
    * BASH completions
    * Zsh completions
    * PowerShell completions
    * All other existing shell completions/special integrations
* Suggestions for bad parameters
* Parsing the intentions of the cosmic overmind
* Ignoring certain parameters on Tuesday

Did I miss anything?

**Comment by medvednikov** [comment]
There's the `flag` module and  https://github.com/nedpals/v-args

I haven't yet used them, can you check if they have some of the things you need?

**Comment by spytheman** [comment]
+ Generating a nicely formatted list of the supported options and short explanations for them, when given --help or -h .
