### ISSUE TITLE
502 Bad Gateway on Forum and Blog

### ISSUE THREAD

**Issue by paulocoghi** [vlang/v#1407]
The Forum and Blog aren't loading. The Nginx in front is returning 502 Bad Gateway

**Comment by paulocoghi** [comment]
The issue is still occurring today, August 2.

**Comment by medvednikov** [comment]
I've removed the links for now. I need to migrate them a new separate server.

Will be done within 24 hours.

**Comment by medvednikov** [comment]
Fixed.

**Comment by ntrel** [comment]
The forum link now redirects to https://vpm.best/
