### ISSUE TITLE
Clone array into immutable array

### ISSUE THREAD

**Issue by serg-meus** [vlang/v#14077]
**V version:** 0.2.4
**OS:** Linux, Windows

**What did you do?**
a := [1, 2, 3]
mut b := []int{}
b = a.clone()
println(b)

**What did you expect to see?**
[1, 2, 3] or compilation error
 
**What did you see instead?**
[]

**Comment by changrui** [comment]
Output is: `[1, 2, 3]`.

**Comment by DevrosTheOne** [comment]
use ```<<``` to append to a mutable array
```v
a := [1, 2, 3]
mut b := []int{}
b << a.clone()  
println(b)
```

**Comment by serg-meus** [comment]
Sorry, didn't test enough
