### ISSUE TITLE
bug of interface

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#141]
```
struct Dog { }
fn (d Dog) speak() string {
	return 'woof'
}

interface Speaker {}

fn (c Speaker) speak() string {
	return 'meow'
}

fn perform(s Speaker) {
	println(s.speak())
}

fn main() {
	dog := Dog{}
	perform(dog)// ==> "woof"
}
```
I got `You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.`

**Comment by GordonGgx** [comment]
There's something wrong with your writing.
interface method should:
```
interface Speaker {
   speak() string
}
```
not
```
interface Speaker {}

fn (c Speaker) speak() string {
	return 'meow'
}
```
because it class method.
I think so.

**Comment by medvednikov** [comment]
@GordonGgx you are correct.

The compiler should handle the incorrect syntax with something like

`invalid receiver type Speaker (Speaker is an interface type)`

**Comment by medvednikov** [comment]
Fixed.

**Comment by bronze1man** [comment]
@GordonGgx
I write the wrong code on purpose to seen vlang compile error message.
