### ISSUE TITLE
Line endings and read_lines issues

### ISSUE THREAD

**Issue by Rendims** [vlang/v#1410]
**V version:** 0.1.17
**OS:** Linux

I see that files are handled differently depending on OS. Won't that cause issues and inconsistencies when reading files created on a different OS?
Most languages I have seen used a single definition of what a line is regardless of OS.

For example: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/BufferedReader.html#readLine()

**What did you do?**

The following behavior confused me a bit when running on a Linux system.

```go
import os

fn main() {
	lines := os.read_lines('out.txt')
	for line in lines {
		println('$line $line.len')
	}
}
```

`> echo -n "Foo\nBar\nBaz" | unix2dos > out.txt && v run main.v`

**What did you expect to see?**
```
Foo 3
Bar 3
Baz 3
```

**What did you see instead?**
```
 4o
 4r
Baz 3
```

**Potential Issue 2**

A file created by `echo -n " " > out.txt` or any other 1 byte file will probably cause an invalid read when it checks for `'\r'` at index `-1`.

**Comment by avitkauskas** [comment]
Thanks @Rendims . Should be fixed with #1412.
