### ISSUE TITLE
Strongly recommended that the colon be removed from the variable declaration

### ISSUE THREAD

**Issue by toop** [vlang/v#1413]
Life is short, need simple, strongly recommended to remove colons(:), in order to improve efficiency, protect fingers, save keyboard, more in line with the simple and efficient! like this：
      name := 'Bob'   ===>  name = 'Bob' 

      name = 'Bob'   (It`s beautiful ！)

**Comment by changrui** [comment]
`Less is more, simple is the best! ` Many func name of vlang are too long, shortage it please.

**Comment by iredmail** [comment]
I argued that before with Alex, but now I prefer current syntax: declare and initialize a variable with `:=` and change it with `=`.
This is an indicator to tell you when it's declared/initialized and when it's changed.

But i vote to switch the constant syntax from `Pi = 3.14` to `Pi := 3.14` to match this syntax and keep it consistent.

**Comment by medvednikov** [comment]
`const (a := b)` is not consitent: you are specifying that it's a declaration twice: `const` and `:=`. `:=` is a shortcut for `var a = b`, which is consistent with `const a = b`.

It's also consistent with literally every language, including languages that use `:=` (Go, Delphi). They all have `const (a = b)`.

@toop Python having no syntax for declarations is a source of millions of bugs. It's very important to be able to define variables and see where they are defined. The syntax is not going to change.
