### ISSUE TITLE
Fixed-size, multi-dimensional arrays corrupt when created as an argument

### ISSUE THREAD

**Issue by Hakunamawatta** [vlang/v#14135]
**V version:** 0.2.4 a2db44b
**OS:** Linux Mint 20.3

**What did you do?**
Duplicated a fixed-size, multi-dimensional array manually and then printed it.
```
fn main() {
    a := [[1, 2]!, [3, 3]!]!
    println([[a[0][0], a[0][1]]!, [a[1][0], a[1][1]]!]!)
}
```

**What did you expect to see?**
[[1, 2], [3, 3]]

 
**What did you see instead?**
A multi-dimensional array with random values.
[[915635328, 915635336], [0, 0]]
or
[[-1014993824, -1014993816], [0, 0]]
or
[[1251308016, 1251308024], [0, 0]]
and so on.
I believe this only happens if the array is created as an argument:
```
fn main() {
    a := [[1, 2]!, [3, 3]!]!
    b := [[a[0][0], a[0][1]]!, [a[1][0], a[1][1]]!]!
    println(a)
    println(b)
    println([[a[0][0], a[0][1]]!, [a[1][0], a[1][1]]!]!)
}
```
This produces:
[[1, 2], [3, 3]]
[[1, 2], [3, 3]]
[[-729214816, -729214808], [0, 0]]

**Comment by changrui** [comment]
This is OK.
```v
fn main() {
    a := [[1, 2], [3, 3]]
    println([[a[0][0], a[0][1]], [a[1][0], a[1][1]]])
}
```
