### ISSUE TITLE
String concatenation with string interpolation

### ISSUE THREAD

**Issue by ArcDrake** [vlang/v#1414]
**V version:** 0.1.17
**OS:** Win 10 and Debian

**What did you do?**

Trying to concatenate two strings with string interpolation

```
fn main() {
    mut full_name := ''
    first_name := 'foo'
    last_name := 'bar'

    // works
    full_name = '$first_name ' + '$last_name'

    // doesn't work - notice the missing blank space in '$first_name'
    // full_name = '$first_name' + '$last_name'

    // A single variable without the blank space works, so I suppose it's not as it should be
    // full_name = '$first_name'

    println(full_name)
}

```
**What did you expect to see?**
>foobar
 
**What did you see instead?**

> D:\vproj\testings\misc>v run concat.v
> string_add( first_name ,
> start_tmp() already started. cur_line=" full_name  = "

I'm not 100% sure this is a bug or could be intended, but I think it is a bug?!

**Comment by medvednikov** [comment]
This is a bug, thanks.

**Comment by ArcDrake** [comment]
You're welcome :)

Have a nice day

**Comment by Henrixounez** [comment]
It has something to do with the first condition making the scanner think the string is ended but it doesn't stop correctly the interpolation of the variable that would have happened in the second one.
I've tried to find ways to fix for a couple of hours but can't find anything that works...

https://github.com/vlang/v/blob/a0c8fa5bbc0a527cdd309072544e30932efb421b/compiler/scanner.v#L265-L275

**Comment by Bowero** [comment]
It works now.

```V
fn main() {
    mut full_name := ''
    first_name := 'foo'
    last_name := 'bar'

    // works
    full_name = '$first_name ' + '$last_name'

    // doesn't work - notice the missing blank space in '$first_name'
    // full_name = '$first_name' + '$last_name'

    // A single variable without the blank space works, so I suppose it's not as it should be
    // full_name = '$first_name'

    println(full_name)
}
```

```
foo bar
```
