### ISSUE TITLE
Help wanted: Getting Go channels to compile

### ISSUE THREAD

**Issue by krolaw** [vlang/v#1415]
Not sure what the correct process is, but I've started added go like channels to my fork.
https://github.com/krolaw/v/tree/master/vlib/sync

However, I can't make it compile and I fear generics may not be far enough along to complete them. But it's probably just me and once I get it working I'll be able to do a pull request.

Thanks.

**Comment by medvednikov** [comment]
Thanks @krolaw 

I just had a quick look. Indeed, generics are not yet far enough for this to work yet.

I'll be spending lots of time on them this week.

**Comment by dcurrie** [comment]
Note that [the documentation](https://vlang.io/docs#generics) still says July... you might want to update that at least.

Here is an example I've coded that I am patiently awaiting generics to test:

```
struct llrbMap<K,V> {
mut: 
    root *llrbNode<K,V>
    size int 
}

struct llrbNode<K,V> {
    key K
mut: 
    val V
    left *llrbNode
    right *llrbNode
    color bool // color of the connection between this node and its parent;
               // the value true means red while false means black
}
```

**Comment by crthpl** [comment]
@medvednikov can this be closed?

**Comment by JalonSolov** [comment]
@crthpl Have you tested to see if the problem is resolved?

@krolaw have you tried again, now that V supports go routines and channels?  And better generics?  :-)
