### ISSUE TITLE
Struct field corruption (?)

### ISSUE THREAD

**Issue by Jah-On** [vlang/v#14153]
V doctor doesn't work for me (likely bc I'm using the git package from AUR) so I am going to use Neofetch's info to fill in the OS info. Sorry if that's not what you need.
**V version:** V 0.2.4 d934472
**OS:** Garuda Linux - 5.17.4-zen1-1-zen - DE: Plasma 5.24.4 - CPU: AMD Ryzen 5 5500U with Radeon Graphics (12) @ 2.1GHz

```v
import gg
import gx

[heap] struct GUI {
mut:
	ctx gg.Context
	bata []int
}

fn main(){
	mut hmm := [0, 1]
	mut s := &GUI{
		ctx : gg.new_context(
			width: 200
			height: 200
			frame_fn: draw_frame
		)
		bata: [0,1]
	}
	s.ctx.user_data = &s
	println(s.bata.len)
	s.ctx.run()
}

fn draw_frame(mut ctx gg.Context){
	mut gui := &GUI(ctx.user_data)
	println(gui.bata.len)
	ctx.begin()
	ctx.end()
	ctx.quit()
}
```

**What did you do?**
I compiled the code using ```v main.v``` and ran it with ```./main```.

**What did you expect to see?**
Output should have been 
```
2
2
```
 
**What did you see instead?**
Instead, I got 
```
2
1
```

Also, when you trying to print the array, the app segfaults.
Or if you use ```s.bata  = [0,1]```, an empty array is printed.

**Comment by Jah-On** [comment]
This is happening with ints too.

**Comment by kahsa** [comment]
```v
import gg

[heap] struct GUI {
mut:
	ctx  gg.Context
	bata []int
}

fn main(){
	mut s := &GUI{
		bata: [0,1]
	}
	ctx := gg.new_context(
		width: 200
		height: 200
		frame_fn: draw_frame
		user_data: s
	)
	s.ctx = ctx
	println(s.bata)
	s.ctx.run()
}

fn draw_frame(mut gui GUI){
	gui.ctx.begin()
	println(gui.bata)
	gui.ctx.end()
	gui.ctx.quit()
}
```

**Comment by Jah-On** [comment]
I see, thank you!
