### ISSUE TITLE
Pre-initialization required on complex structure

### ISSUE THREAD

**Issue by chipnetics** [vlang/v#14174]
**V version:**  V 0.2.4 dce2173
**OS:**  linux, Debian GNU/Linux 11 (bullseye)

I'm tagging this as a "bug" as V advertises pre-initialization to defaults, yet the below does not work as one would intuitively expect.

**What did you do?**

```v
fn main() {
        mut test_map := map[string]Point_map{}
        
        test_map['test1'].points['point3'] << Point{10, 20}
        test_map['test2'].points['point4'] << Point{50, 60}

        println(test_map)
}

struct Point {
mut:
        x int
        y int
}

struct Point_map {
mut:
        points map[string][]Point
}
```

**What did you expect to see?**
```
{'test1': Point_map{
    points: {'point3': [Point{
        x: 10
        y: 20
    }]}
}, 'test2': Point_map{
    points: {'point4': [Point{
        x: 50
        y: 60
    }]}
}}
```
 
**What did you see instead?**
```
{}
```

Instead, to get the desired output, you must manually pre-initialize as such:

```v
fn main() {
        mut test_map := map[string]Point_map{}
        
	test_map['test1'].points = map[string][]Point     // <----- Pre-init
        test_map['test2'].points = map[string][]Point     // <----- Pre-init

        test_map['test1'].points['point3'] << Point{10, 20}
        test_map['test2'].points['point4'] << Point{50, 60}

        println(test_map)
}

struct Point {
mut:
        x int
        y int
}

struct Point_map {
mut:
        points map[string][]Point
}
```

I believe if the pre-init is indeed required as shown above (not a bug); the compiler should at least give a warning as {} would really have no use-cases in most applications.  *Note: in testing how this behaves in Go, it is a panic `panic: assignment to entry in nil map`*

**Comment by rcqls** [comment]
What is weird is the difference in behaviour between 
```v
fn main() {
        mut test_map := map[string]map[string][]Point
        
        test_map['test1']['point3'] << Point{10, 20}
        test_map['test2']['point4'] << Point{50, 60}
        println(test_map)

		mut map_of_map := map[string]map[string]int
		map_of_map["Dog"]["Poodle"] = 5
		println(map_of_map) 
}


struct Point {
mut:
        x int
        y int
}
```

**Comment by chipnetics** [comment]
Yes! Thanks for taking that from the Discord, it's good to highlight the difference in behaviour here.  

A map of a map is all pre-initialized, yet the rules change for the struct example.  =]

**Comment by rcqls** [comment]
I have updated my comment since it is not really map of map that is pre-initialized...
