### ISSUE TITLE
V panic: module "glfw" not found

### ISSUE THREAD

**Issue by littlespex** [vlang/v#1423]
**V version:** 0.1.17
**OS:** macOS Mojave 10.14.5

**What did you do?**
1) Installed V:
    ```
    git clone https://github.com/vlang/v
    cd v
    make
    ```
1) Installed dependencies:
    ```
    brew install glfw freetype curl
    ```
1) Create a symlink 
    ```
    sudo ln -s [path to V repo]/v /usr/local/bin/v
    ```
1) Tried to run the Tetris example:
`v run tetris/tetris.v`

**What did you expect to see?**
The Tetris demo
 
**What did you see instead?**
`V panic: module "glfw" not found`

**Comment by medvednikov** [comment]
Hi

I just moved glfw to vpm, you need to install it:

`v install glfw`

I'll update the docs within 20 minutes.

**Comment by littlespex** [comment]
I still get the same error after installing via `vpm`:

```
v install glfw
-> Installing module glfw...
v run examples/tetris/tetris.v
-> V panic: module "glfw" not found
```

**Comment by medvednikov** [comment]
I've reverted the change, should be fine now. Can you check?

**Comment by littlespex** [comment]
Works now. Thx!
