### ISSUE TITLE
generics: compile error passing anonymous function to method using generic type in parameter

### ISSUE THREAD

**Issue by nelsam** [vlang/v#14239]
**V version:** 0.2.4 ec92d46
**OS:** linux

**What did you do?**

I ran `v up` and then ran tests in a library of mine (`vpar`), which were passing once upon a time.  The code in question is [here](https://git.sr.ht/~nelsam/vpar/tree/main/item/vpar.v).  That code used to compile - but now I get a compile error from the tests that exercise the `after` and `spec` methods.

A more succinct version that still shows the failure:

```v
// foo.v

struct Foo<T> {
}

fn (f Foo<T>) do(name string, d fn(T), v T) {
	println("running "+name)
	d(v)
	println("ran "+name)
}

fn main() {
	f := Foo<string>{}
	f.do("foo", fn(s string) {
		println("s value is "+s)
	}, "bar")
}
``` 

**What did you expect to see?**

Successful test output.  I am not aware of changes to the generic syntax, and more importantly, the `before` function appears make use of generics _for the return type_ just fine.  This bug appears to only be impacting parameter types in anonymous functions passed to methods that use generics.  It is _very specific_.

Side note: I also tried to reproduce with generics in _function_ parameters instead of _method_ parameters, but in _functions_ they work.

So the following _does_ work:

```v
fn do<T>(name string, f fn(T), v T) {
	println("running "+name)
	f(v)
	println("ran "+name)
}

fn main() {
	do("foo", fn (v string) {
		println("v is "+v)
	}, "bar")
}
```
 
**What did you see instead?**

```
valczir@nurgle:~/dev/vpar git:(main*)$ v test .

# output trimmed to just one failure:

vpar_test.v:14:16: error: cannot use `fn (string)` as `fn (T)` in argument 2 to `vpar.Vpar<string>.spec`
   12 |     }
   13 |
   14 |     v.spec('foo', fn (s string) {
      |                   ~~~~~~~~~~~~~~~
   15 |         assert s == ''
   16 |     })
```

Or from the more succinct sample:

```
valczir@nurgle:~/dev$ v run foo.v
foo.v:13:14: error: cannot use `fn (string)` as `fn (T)` in argument 2 to `Foo<string>.do`
   10 | fn main() {
   11 |     f := Foo<string>{}
   12 |     f.do("foo", fn(s string) {
      |                 ~~~~~~~~~~~~~~
   13 |         println("s value is "+s)
   14 |     }, "bar")
```

**Comment by DevrosTheOne** [comment]
specifying the type `string` on the function call `f.do<string>(` works.  🥸  

```v
// foo.v

struct Foo<T> {
}

fn (f Foo<T>) do(name string, d fn(T), v T) {
	println("running "+name)
	d(v)
	println("ran "+name)
}

fn main() {
	f := Foo<string>{}
	f.do<string>("foo", fn(s string) {
		println("s value is "+s)
	}, "bar")
}
```
```
running foo
s value is bar
ran foo
```

**Comment by nelsam** [comment]
Interesting.

I'm still _pretty_ confident that this is a bug - the type `T` is already defined on the receiver, so the method should just be using the already-defined type.

Also, changing the function from `func(T)` to `func() T` makes everything work as I'd expect it to - I can call `do` without re-declaring the generic type.  See:

```v
struct Foo<T> {
}

fn (f Foo<T>) do(name string, d fn() T) T {
	println("running "+name)
	v := d()
	println("ran "+name)
	return v
}

fn main() {
	f := Foo<string>{}
	v := f.do("foo", fn() string {
		return "bar"
	})
	println("got "+v)
}
```

^^^ that works as I would expect it to.

---

Also, taking your example and making a small (and obviously wrong) change gives me a compiler error:

```v

struct Foo<T> {
}

fn (f Foo<T>) do(name string, d fn(T), v T) {
	println("running "+name)
	d(v)
	println("ran "+name)
}

fn main() {
	f := Foo<string>{}
	f.do<int>("foo", fn(v int) {
		println(v)
	}, 1)
}
```

```shell

valczir@nurgle:~/dev$ v run foo.v
==================
/tmp/valczir/v_1000/foo.8000241737375273261.tmp.c:11497: error: cannot convert 'int' to 'struct string'
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by DevrosTheOne** [comment]
Should have done more tests.  So it looks like it does the test but not correctly apply in function.  

Nobody wants to write something like `do_stuff<string, int, f64>(` or `do_stuff<string, int><f64>(` aghhh.

Playing around with some code (not pretty, off the cuff code). 🤓  

We could deduct the type if it's a single generic used.  Using multiple generics gets a bit messy.  Add on top of that methods with generic that do not match the original generic types gets a bit complex (I think)

Last three lines probably the simples example.  
```v
struct Stuff<A,B>{
	a_is A 
	b_is B
}

fn (j Stuff<string,int>) say_hi( ){
	println( j.a_is.to_upper() )
}
fn (j Stuff<int,rune>) say_hi( ){
	println( j.b_is.repeat(3) )
}

fn (j Stuff<int,rune>) say_stuff<S>( func fn( S),  s S){
	func (s)
}

j := Stuff<string,int>{'hallo', 22}
k := Stuff<int,rune>{123, `😇`}

// who am I calling.
k.say_hi( )
j.say_hi( )

//k instance only.  Need the type to satisfy the method call
k.say_stuff<string>(fn( s string ) { println('yada yada $s')}, 'hahahaha')
k.say_stuff<int>(fn( i int ) { println(i * i * i)}, 666)
k.say_stuff<f64>(fn( i f64 ) { println(i * i * i)}, 6.66)
```
```
😇😇😇
HALLO
yada yada hahahaha
295408296
295.408296
```

**Comment by nelsam** [comment]
I'm having issues doing a proper `git bisect` locally, but manually bisecting (kind of) using the weekly releases:

- The last working version: [weekly.2022.12](https://github.com/vlang/v/releases/tag/weekly.2022.12)
  - Using this release, my tests (in `vpar`) pass and the simple example runs normally.
- The first failing version: [weekly.2022.13](https://github.com/vlang/v/releases/tag/weekly.2022.13)
  - Using this release, my tests (in `vpar`) fail to compile and the simple example fails to compile.

I will try to track down the offending commit tomorrow morning (my time), but it appears that it happened between those two releases.

**Comment by nelsam** [comment]
After figuring out `git bisect`, I tracked the regression down to commit 8b072aa962e1c2f16ca80474c433e49d5e0a623e.  I'll see if I can tell what is causing the breakage.

Side note: it would be friendlier for `git bisect` if `vc` was checked out at a version matching the currently checked out version.  I was having troubles because `byte` was deprecated in favor of `u8`, which means that the latest `vc` can no longer compile older versions of `v`.  I can make an issue/PR for that.

**Comment by nelsam** [comment]
I don't really understand how that commit is the offending one (maybe I messed up a step while bisecting) _but_ I believe I've tracked down the logic that needs to change.

In `check_matching_function_symbols`, the type that's passed in still has `T` as its argument type.  Return types are checked with `c.check_basic(got_ret, exp_ret)`, and that appears to understand generic types _somewhat_.  However, for parameter types, there is some [custom matching logic](https://github.com/vlang/v/blob/master/vlib/v/checker/check_types.v#L346-L361) - apparently it's trying to add extra detail about pointer vs non-pointer types.  This custom logic is more strict than `c.check_basic` - which is a good thing most of the time.

With generic types, though, we need to know the concrete type that the generic type must be in order to compile and compare the types to that instead.

I see enough light at the end of the tunnel to believe I'll be able to fix this and submit a PR.  It may take me a bit, though.

**Comment by nelsam** [comment]
Fun story: using the `weekly.2022.12` release, the following compiles and runs (I would expect it not to):

```v
struct Type<T> {}

fn (t Type<T>) do(a fn () T, b fn (T)) {
	v := a()
	b(v)
}

fn main() {
	t := Type<string>{}
	a := fn () string {
		return "foo"
	}
	b := fn (s int) { // note: `int` is the wrong type here
		println('$s')
	}
	t.do(a, b)
}
```

The output: `1978859890`.

I want to _try_ to fix this in `resolve_generic_to_concrete` instead, populating concrete types recursively through function types.  I believe that is probably a more correct solution and would result in a compile error for the above case.

I have a fix (and a corresponding test) to restore the old behavior, but I would much rather fix it the correct way rather than this kind of hacky restoring-naive-logic way.
