### ISSUE TITLE
Clipboard module can't paste from system while using garbage collection.

### ISSUE THREAD

**Issue by Jah-On** [vlang/v#14281]
Version: V 0.2.4 eb03fad
OS: Garuda Linux using linux-zen 5.16.3

```v
import clipboard

fn main(){
	mut c := clipboard.new()
	println(c.paste())
}
```

**What did you do?**
Compiled code above with the ```-gc boehm``` option.

**What did you expect to see?**
What was last copied from a different app.
 
**What did you see instead?**
An empty newline.

**Comment by spytheman** [comment]
It seems that adding `[heap]`, did not help much - I still get an empty new line with `-gc boehm`:
![image](https://user-images.githubusercontent.com/26967/168527363-22d27ee4-458a-4912-a2fb-d16079d1574b.png)

**Comment by spytheman** [comment]
I think it is a timing issue due to a data race somewhere in `vlib/clipboard/x11/clipboard.c.v`. It for example works, when I do this:
![image](https://user-images.githubusercontent.com/26967/168562984-797a88e7-6776-49bd-a809-43017f8b32ba.png)

**Comment by spytheman** [comment]
```v
    for {
+       time.sleep(1 * time.millisecond)
        C.XNextEvent(cb.display, &event)
```
... fixed it for me. @Jah-On please test too with latest V.

**Comment by Jah-On** [comment]
Yes, this appears to fix the issue. Thank you!
