### ISSUE TITLE
Reformate error output to be gcc/clang conform

### ISSUE THREAD

**Issue by spacesinmotion** [vlang/v#1428]
### Situation
Currently the compiler output has a v-custom error format like:
```
panic: v_test.v:5
undefined: `d`
```
I think most IDEs will have to write a parser for that output, which is kind of unneccessary.

### Solution
You could simply reformat that output to:
```
v_test.v:5 panic: undefined: `d`
```
This is almost the same format of **gcc** or **clang** 

I'm currently working with **vim** with that kind of format it would work out of the box without any plugin. If I'm compiling with `:!make` vim would jump to the line were the error occured. `v_test.v:5`

I think IDE integration would be easier.

**Comment by medvednikov** [comment]
Fixed.
