### ISSUE TITLE
os.read_lines not working

### ISSUE THREAD

**Issue by depperm** [vlang/v#14302]
seems to be dup of #981 but (V 0.2.4 ac90a2b)
**The code** (the [file](https://web.archive.org/web/20180611003215/http://www.puzzlers.org/pub/wordlists/unixdict.txt)):
```
fn main() {
    filename := "unixdict.txt" // also tried ./unixdict.txt (this file is in the same dir as the v progarm
    words := os.read_lines(filename) or { panic('FAILED to read file: $filename')}
    println(words)
}
```
**expected**:

An array of words equal to the dict.

**output**
```
V panic: FAILED to read file: unixdict.txt
v hash: ac90a2b
/tmp/v_89343/test.9306359698931642772.tmp.c:7060: at _v_panic: Backtrace
/tmp/v_89343/test.9306359698931642772.tmp.c:15872: by main__main
/tmp/v_89343/test.9306359698931642772.tmp.c:16246: by main
```
doctor
```
OS: linux, "Amazon Linux release 2 (Karoo)" (VM)
Processor: 4 cpus, 64bit, little endian, Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
CC version: cc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-14)

getwd: /home/userid/v
vmodules: /home/userid/.vmodules
vroot: /home/userid/v
vexe: /home/userid/v/v
vexe mtime: 2022-05-04 12:52:09
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 ac90a2b

Git version: git version 2.32.0
Git vroot status: weekly.2022.18-8-gac90a2b5 (2 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 eee03626
```

**Comment by JalonSolov** [comment]
The code works perfectly on my system, using the same version of V.

Here's the end of the output: `..., 'zounds', 'zucchini', 'zurich', 'zygote']`

I _did_ have to add a `import os` at the top - are you running this in the REPL, or in a `.v` file?  I pasted the code into a file, added the import, and it worked.

**Comment by depperm** [comment]
Ok so I think I know what the problem is (sort of). I was running v from the v directory and my file(`.v`) is up one directory

`./v run ../test.v` (doesn't work)
`./v/v run test.v` (does work)

**Comment by JalonSolov** [comment]
The path is calculated relative to the path of the executable.  V creates the executable in the same dir as your source, unless you supply the `-o` option to tell it to put it somewhere else.  At the end, if you used `v run`, it will then delete the executable.

As for your other question, no, there is no (currently working) online repl.  The playground should be put back in operation soon (hopefully).

In any case... V should have give a nice error message, instead of panic'ing.

**Comment by medvednikov** [comment]
Well the developer asked V to panic:

```
  words := os.read_lines(filename) or { panic('FAILED to read file: $filename')}
  ```

**Comment by JalonSolov** [comment]
Doh.  I should read what I'm pasting, I guess.  :-)
