### ISSUE TITLE
vlang project auto generation : v new/init <vProj>

### ISSUE THREAD

**Issue by changrui** [vlang/v#1431]
After run `v new/init <vProj>`, we can get the following project structure:

![vlangStructure](https://user-images.githubusercontent.com/2800955/62356760-634e7300-b544-11e9-9ff3-d62d5438e4aa.png)

Do you think so?

**Comment by 0x9ef** [comment]
This not needed. This should be done by the IDE.

**Comment by medvednikov** [comment]
One of the great benefits of V is it's a simple language. You don't need complicated tools or project structures.

And I don't want V to force a certain layout or GitHub etc.

**Comment by manen** [comment]
Just in case someone's found this:
`v new` and `v init` are a thing now.

**Comment by Gladear** [comment]
> `v new` and `v init` are a thing now.

Just to detail a bit more, they don't initialize a project structure, but templates are considered, see #9117
