### ISSUE TITLE
checker: failed to create own generic collection

### ISSUE THREAD

**Issue by serg-meus** [vlang/v#14311]
**V version:** 0.2.4
**OS:** Linux, Windows

**What did you do?**

```
import datatypes { LinkedList } // or any other generic collection

struct MyNode<T> {
mut:
    data T
    // other stuff
}

struct MyContainer<T> {
mut:
    lst LinkedList<MyNode<T>>
    // other stuff
}

fn (mut c MyContainer<T>) push(data T) {
    node := MyNode<T> { data: data }
    c.lst.push(node) // checker: mismatch types
}

mut c := MyContainer<string> {}
println(c)
```

**What did you expect to see?**

Successful compile
 
**What did you see instead?**

error: cannot use 'MyNode<string> as 'string' in argument 1 to 'datatypes.LinkedList<string>.push'

**Comment by DevrosTheOne** [comment]
Sorry if I misunderstood the objectives in the code.  I will have to make a few assumptions

`mut c := MyContainer<string> ` defines my container as storing `string` type.  However the `lst` in `MyContainer` says it expects `LinkedList<MyNode<T>>`.   

`MyContainer` as `string` example first, `MyNode<T>` sample below
```v
import datatypes { LinkedList } // or any other generic collection

struct MyNode<T> {
mut:
    data T
    // other stuff
}

struct MyContainer<T> {
mut:
    lst LinkedList<T>
    // other stuff
}

fn (mut c MyContainer<T>) push(data T) {
    c.lst.push(data) // checker: mismatch types
}

mut c := MyContainer<string> {}
c.push('data')
println(c)
```
```
MyContainer<string>{
    lst: ['data']
}
```
If the type you wanted to store in `MyContainer` values  `lst LinkedList<MyNode<T>>` then `c := MyContainer` is missing that information.  `

LinkedList<MyNode<T>>` with small changes
```v
import datatypes { LinkedList } // or any other generic collection

struct MyNode<T> {
mut:
    data T
    // other stuff
}

struct MyContainer<T> {
mut:
    lst LinkedList<MyNode<T>>
    // other stuff
}

fn (mut c MyContainer<T>) push(data T) {
    // node := MyNode<string> { data: 'data' }
    // c.lst.push(node) // push local MyNode
       c.lst.push(data) // push the parameter
}

mut c := MyContainer<MyNode<string>> {}
mut i := MyContainer<MyNode<int>>{}
c.push( MyNode<string>{'stop pushing'})
i.push( MyNode<int>{ 42 })
println(c)
println(i)
```
```
MyContainer<MyNode<string>{
    lst: [MyNode<string>{
    data: 'stop pushing'
}]
}
MyContainer<MyNode<int>{
    lst: [MyNode<int>{
    data: 42
}]
}
```

**Comment by serg-meus** [comment]
Thank you for reply. I haven't enough time to figure out what's wrong with my code. My goal is to implement the [LRU Cache](https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_recently_used_(LRU)). I suppose it should have a map and linked list inside. Each map node should contain a reference to list node, each list node should contain a reference to corresponding map node. I failed yet to write working code so I reduced it and put here.

**Comment by serg-meus** [comment]
Everything works fine if I remove all `<T>`. Looks like something is wrong with generics.

```
import datatypes { LinkedList } // or any other generic collection

struct MyNode {
mut:
    data string
    // other stuff
}

struct MyContainer {
mut:
    lst LinkedList<MyNode>
    // other stuff
}

fn (mut c MyContainer) push(data string) {
    node := MyNode { data: data }
    c.lst.push(node) // checker: mismatch types
}

mut c := MyContainer {}
c.push('abc')
println(c)
```
