### ISSUE TITLE
Issue compiling news_fetcher.v example code (curl related)

### ISSUE THREAD

**Issue by DrTexx** [vlang/v#1432]
**V version:** 0.1.17
**OS:** Debian 10 Buster

**What did you do?**
Navigated to examples and then `v run news_fetcher.v`

**What did you expect to see?**
A news-related example
 
**What did you see instead?**
```
.news_fetcher.c:103:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.V panic: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

**Comment by medvednikov** [comment]
https://github.com/vlang/v/blob/master/README.md


If you plan to use the http package, you also need to install libcurl.

macOS:
brew install glfw freetype curl

Ubuntu:
sudo apt install libglfw3 libglfw3-dev libfreetype6-dev libcurl3-dev

Arch:
sudo pacman -S glfw-x11 curl freetype2
glfw and libcurl dependencies will be removed soon.
