### ISSUE TITLE
Strange behavior when working with primitive data types.

### ISSUE THREAD

**Issue by t3mnikov** [vlang/v#1434]
I noticed strange behavior when working with primitive types.

**V version:** 0.1.17
**OS:** ElementaryOS 5 Juno (Linux SM-PC-0014 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)

**What did you do?**
1). i3 := i16(40000)
2)  i4 := u16(65536) 

**What did you expect to see?**
1) -25536
2) -1 ?
 
**What did you see instead?**
1) constant 40000 overflows i16
2) constant 65536 overflows u16

It seems to me that the program should not stop when it overflows.

**Comment by schurhammer** [comment]
I think this is intended. You're not supposed to put a constant into a data type that isn't big enough to hold the value.
The error happens because the constant is too big at compile time, if it happened during runtime it would overflow like you expected.

**Comment by AtjonTV** [comment]
I dont think this is a bug .. why would you make a contant value that overflows its data type at compile time?

If you wanted the negative value, just set it.

Can you explain why you would want that?

And for note, its good that the compiler checks for an overflow issue at compile time ;D

**Comment by t3mnikov** [comment]
Sorry, guys. Perhaps I do not fully understand the work of compiled languages. I write in PHP.

**Comment by medvednikov** [comment]
This is indeed intended.
