### ISSUE TITLE
VWEB bug: find ,/vweb for http server root.

### ISSUE THREAD

**Issue by changrui** [vlang/v#1436]
**V version:** 
       v0.1.17
**OS:** 
      WSL ubuntu under Windows 10

**What did you do?**
    run `v run test_app.v`

**What did you expect to see?**
all are OK.
 
**What did you see instead?**

`Running vweb test on http://localhost:8082
Running vweb app on http://localhost:8082 ...
net.listen(8082)
liisten res = 0
ls() couldnt open dir "./vweb"
accept()
.
numbytes=399`

**Comment by changrui** [comment]
Could't open dir `./vweb`, but it is same of execute file name, so error occurs.

**Comment by edmz** [comment]
BTW, I created a pull request that _kind of_ fixes this #1961 .

**Comment by zkvn** [comment]
Same issue exist in v1.1.20

**Comment by medvednikov** [comment]
The vweb example works fine now.
