### ISSUE TITLE
Quantifiers in regex

### ISSUE THREAD

**Issue by walkingdevel** [vlang/v#14370]
**V version:**  V 0.2.4 cd4fa04
**OS:** macos, macOS, 12.2

**What did you do?**

```v
import regex

git_output := 'refs/remotes/origin/master'

branch_query := r'refs/remotes/origin/(.*)'
mut re := regex.regex_opt(branch_query) or { panic(err) }
re.match_string(git_output)

default_branch := re.get_group_by_id(git_output, 0)

println(default_branch)
```

**What did you expect to see?**
`master`
 
**What did you see instead?**
`maste`

If I change 'r' with another char, for example 'g', group matches right(`refs/remotes/origin/masteg` => `masteg`). As I understand, troubles are only with 'r'.

**Comment by walkingdevel** [comment]
@penguindark, can u check it?

**Comment by penguindark** [comment]
PR on the go for this specific bug,
but Regex need a major redesign, I'll do when I'll have some spare time.
@walkingdevel Tnx for the issue.
