### ISSUE TITLE
[Suggest]: gx.indigo Color is {63, 15, 183}

### ISSUE THREAD

**Issue by hotmanga** [vlang/v#14382]
I find in `vlib/gx/color.v` indigo's Color is Color{**75, 0, 130**}.
I suggest that modify it to Color{**63, 15, 183**} (HEX #3F0FB7).

Because, `gx.indigo` looks like `purple`.

[This is my reference](https://www.color-name.com/indigo-blue.color)

**Comment by hotmanga** [comment]
Maybe, Indigo looks like [Indigo Bunting Color](https://www.color-name.com/indigo-bunting.color). **RGB (0, 108, 169)**

**Comment by JalonSolov** [comment]
V's current value is correct.

https://www.canva.com/colors/color-meanings/indigo/
