### ISSUE TITLE
length of/in 2 dimensional arrays

### ISSUE THREAD

**Issue by l8atnight** [vlang/v#1440]
**V version:** latest
**OS:** win 64

**What did you do?**
declare array [10][10]x
z := x.len
y:= x[].len

**What did you expect to see?**
z=10; y=10
 
**What did you see instead?**
doesn't compile

**Comment by l8atnight** [comment]
Please handle array as string, so that they have a method .len. this would be consistent.

**Comment by joe-conigliaro** [comment]
Multi dimensional arrays are not implemented yet.
Both string and array have the property len, not method.
string.len & array.len.
