### ISSUE TITLE
Compiler bug with in operator and Sum Types

### ISSUE THREAD

**Issue by dedesite** [vlang/v#14439]
**V version:** V 0.2.4 65d9c8f
**OS:** Ubuntu 20.04

**What did you do?**

Try to use the `in` operator with sumtypes like in this example :
```v
type TokenValue = rune | u64

fn main() {
	val := TokenValue(`+`)
	if val in [TokenValue(`+`), TokenValue(`-`)] {
		println("ok")
	}
}
```

**What did you expect to see?**

The program to run correctly and print "ok"
 
**What did you see instead?**
```
/tmp/v_1000/in_operator_bug.8285416656142212473.tmp.c:11634: error: invalid operand types for binary operation
/tmp/v_1000/in_operator_bug.8285416656142212473.tmp.c:11634: error: invalid operand types for binary operation
...

```

**Comment by dedesite** [comment]
Note that there is a variant of the bug, don't know if I should create a separated issue.
Here is the minimum case :
```v
type TokenValue = rune | u64

fn main() {
	// This is another bug
	val := `+`
	if val in [TokenValue(`+`), TokenValue(`-`)] {
		println("ok")
	}
}
```

**Comment by KamkoAmoh** [comment]
> Note that there is a variant of the bug, don't know if I should create a separated issue. Here is the minimum case :
> 
> ```v
> type TokenValue = rune | u64
> 
> fn main() {
> 	// This is another bug
> 	val := `+`
> 	if val in [TokenValue(`+`), TokenValue(`-`)] {
> 		println("ok")
> 	}
> }
> ```
> 
> And the output :
> 
> ```
> /tmp/v_1000/in_operator_bug.14867944870994764656.tmp.c:11646: error: cannot convert 'unsigned int' to 'struct main__TokenValue'
> ```

I thing something is wrong when it try to look in the array after `in`

if you assign it to an variable it works great

```vlang
type TokenValue = rune | u64

fn main() {
	val := TokenValue(`+`)
	arr := [TokenValue(`+`), TokenValue(`-`)]
	if val in arr {
		println("ok")
		break;
	}
}
```

**Comment by dedesite** [comment]
Wow that was fast ! Thanks @yuyi98 !
