### ISSUE TITLE
Output of v --version (Win10) doesn't work anymore

### ISSUE THREAD

**Issue by ArcDrake** [vlang/v#1443]
**V version:** 
0.1.17 (I guess ;))
**OS:** 
Win 10
Output in Debian is correct

**What did you do?**

v --version

**What did you expect to see?**

Version Number of V

**What did you see instead?**

Nothing.

> D:\v>v --version
> 
> D:\v>v  version
> 
> D:\v>v -v
> 

v --help works.
I tried a fresh install with the newest clone, but there is no Version number displayed.

**Comment by emily33901** [comment]
Probably because printfs were smashed - could try again now and see if they got fixed

**Comment by ArcDrake** [comment]
Nope, there is still no output :(

**Comment by medvednikov** [comment]
Make sure you run `v up`

**Comment by ArcDrake** [comment]
OK I did a git pull origin master and make.bat before, i'll try that too:

D:\v>v run up
Updating V...
From https://github.com/vlang/v
 * branch            master     -> FETCH_HEAD
**Already up to date.**
Current branch master is up to date.
D:\v>curl -O https://raw.githubusercontent.com/vlang/vc/master/v.c
Der Befehl "curl" ist entweder falsch geschrieben oder
konnte nicht gefunden werden. **<----- This is german for: curl is mistyped or couldn't be found (I don't get this too, curl is installed it came along with ming64)**

D:\v>gcc -std=gnu11 -DUNICODE -D_UNICODE -w -o v.exe v.c
gcc: error: v.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.

D:\v>del v.c
D:\v\v.c konnte nicht gefunden werden **<----- german for: v.c could not be found**



D:\v>curl
curl: try 'curl --help' for more information

**Comment by ArcDrake** [comment]
BTW I can do this manually. But not with "V up"

D:\v>curl -O https://raw.githubusercontent.com/vlang/vc/master/v.c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  424k  100  424k    0     0   424k      0  0:00:01 --:--:--  0:00:01  971k

D:\v>del v.c

D:\v>v --version





but still no output

**Comment by ArcDrake** [comment]
BTW I can do that manually, but not with "V up"

D:\v>curl -O https://raw.githubusercontent.com/vlang/vc/master/v.c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  424k  100  424k    0     0   424k      0  0:00:01 --:--:--  0:00:01 1511k

D:\v>gcc -std=gnu11 -DUNICODE -D_UNICODE -w -o v.exe v.c

D:\v>del v.c
D:\v>v --version


But still no output

**Comment by ArcDrake** [comment]
I also tried to test the _env_vflags_and_os_args()_ functionality from main.v in a separate project to see if there maybe is a problem with the arguments or the argument parsing, but I think this works well..

```
import os

const (
	MyConst = 'MyConstValue'  
)

fn main() {
   mut args := []string
   vflags := os.getenv('VFLAGS')
   if '' != vflags {
	 println('This never happens, VFLAGS not set yet')
	 
   /*
   args << os.args[0]
   args << vflags.split(' ')
   if os.args.len > 1 {
    args << os.args.right(1)
   }
   */

   }else{
	    args << os.args
   }

   	if '-v' in args || '--version' in args || 'version' in args {
		  println('V $MyConst')
	}
}
```

> D:\vproj\testings\misc\getenv>v getenv.v
> D:\vproj\testings\misc\getenv>getenv.exe -v
> V MyConstValue

**Comment by ArcDrake** [comment]
Looks like I can't even compile a simple HelloWorld now :(

D:\vproj>v run main.v
undefined: `strings.new_builder`

or is it only me?

**Comment by spytheman** [comment]
Try to 
```
import strings 
```
. I am still not sure why, but it helped me in a similar situation when I tried to print a map.

**Comment by spytheman** [comment]
May be it is because strings module is not in the vlib/builtin/ folder.

**Comment by emily33901** [comment]
Have you tried running make.bat

**Comment by ArcDrake** [comment]
I tried git clone, **make.bat** & git clone, **make**
before creating this issue. 

I figured it out thanks to: https://github.com/vlang/v/issues/1451#issuecomment-518100194
v -o v1 compiler
copy v1.exe v.exe

fixxes both, the version output and the string problem!
There is no "v -o v1 compiler" in make.bat and installation doc doesn't notice that too. maybe it should be added?

Actually the "import strings" worked for the stringbuilder problem :)

**Comment by ArcDrake** [comment]
**Summary:**

**Doing the following Steps results in a working v.exe for me:**

git clone https://github.com/vlang/v
cd v
make.bat
v -o v1 compiler
copy v1.exe v.exe

**Trying an "v up" afterwards results in a deleted v.exe**

D:\v>v --version
V 0.1.17

D:\v>v up
Updating V...
From https://github.com/vlang/v
 * branch            master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
D:\v>curl -O https://raw.githubusercontent.com/vlang/vc/master/v.c
Der Befehl "curl" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

D:\v>gcc -std=gnu11 -DUNICODE -D_UNICODE -w -o v.exe v.c
gcc: error: v.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.

D:\v>del v.c
D:\v\v.c konnte nicht gefunden werden

D:\v>v --version
Der Befehl "v" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

**Comment by emily33901** [comment]
Yeah it should rebuild after bootstrapping

**Comment by ArcDrake** [comment]
I reinstalled curl in a different location, works now.

So the solution for "v --version" is: There wasn't really a bug, I just need to do:

> v -o v1 compiler
> copy v1.exe v.exe

after make.bat.
And after my "v up"s

Cool, thanks. I would suggest to add this to make.bat? :)

**Comment by medvednikov** [comment]
> Looks like I can't even compile a simple HelloWorld in Win10 now :(

This was fixed. I had to update v.c

I'll update make.bat and fix `v up` on Windows.

Windows makes it much harder because you can't modify an executable that's already running, like on all other systems.

**Comment by medvednikov** [comment]
I was also experiencing weird issues with curl on Windows.

It was downloading an old version of v.c from GitHub. Caching gone wrong?

It needs to be replaced with PowerShell I think.
