### ISSUE TITLE
unknown function: `join_lines`

### ISSUE THREAD

**Issue by vanceism7** [vlang/v#14443]
**V version:** V 0.2.4 bc397bb.a608516
**OS:** linux, "instantOS" (VM)

**What did you do?**
Im trying to use `join_lines` (found [here]) to combine an array of strings into a string.

A minimal example is to start the v repl and enter the following
```v
some_str := join_lines("hello\nworld!")
```

**What did you expect to see?**
some_str to become some string value
 
**What did you see instead?**
unknown function: `join_lines`

### Other notes
I can see that the version on the module site doesn't match my current version of v. Perhaps the function was moved out of `builtin` into some other module? Not sure, but just wanted to report this in!

Thanks!

[here]: https://modules.vlang.io/index.html#[]string.join_lines

**Comment by changrui** [comment]
```
str_arr := ['hello', ',', 'world.']
println(str_arr.join_lines())
```

**Comment by vanceism7** [comment]
Oh blah! My bad. I thought `join_lines` was a stand-alone function similar to `println`. My functional programming ways are getting me "caught up". Thanks for clarifying!
