### ISSUE TITLE
Error message function main is already defined

### ISSUE THREAD

**Issue by osborngh** [vlang/v#14467]
I know the language has implicit main function but if you declare the main function and you create variables later, you get an error message of function main is already defined. This might be confusing to beginners.

Maybe the message should be like, variables should be declared in the main function.

Today is my first day with v and i'm absolutely loving it. I think the error messages could use some improvement

**Comment by JalonSolov** [comment]
@spytheman Just added a better error message in commit 668d1b0.  No idea why it is gone again, but it is failing with latest V (V 0.2.4 55e7daa):
```v
fn main() {
        println('hi')
}

a := 5
```
output of `v run foo.v` is:
```
foo.v:5:1: warning: unused variable: `a`
    3 | }
    4 | 
    5 | a := 5
      | ^
foo.v:1:1: error: function `main` is already defined
    1 | fn main() {
      | ^
    2 |     println('hi')
    3 | }
```

**Comment by spytheman** [comment]
@JalonSolov this is another (related) problem - my fix was for top level declarations put after script statements, this is for when the `main()` function, had been defined before the script statements (which will introduce *another* implicit main function).
