### ISSUE TITLE
net.http: `Response` struct

### ISSUE THREAD

**Issue by Hunam6** [vlang/v#14477]
```v
pub struct Response {
pub mut:
	text         string
	header       Header
	status_code  int
	status_msg   string
	http_version string
}
```
Why do we have this non-standard `Response.text`, shouldn't be `Response.body`?

ref: https://developer.mozilla.org/en-US/docs/Web/API/Response/body

**Comment by changrui** [comment]
res.bodymay be a `[]u8`.

**Comment by axetroy** [comment]
https://github.com/vlang/v/discussions/12675
