### ISSUE TITLE
Shorthand for assigning fields when variable names match.

### ISSUE THREAD

**Issue by schurhammer** [vlang/v#1447]
I find myself writing things like ```Struct{field1: field1, field2: field2}```, perhaps we could add a shorthand for when the variable names match, ```Struct{field1, field2}```.

**Comment by medvednikov** [comment]
This is something that goes against the "one way" philosophy. It also adds another rule to the language.

All editors support autocompletion (like Vim's `C-n`), so you only need a couple of extra keystrokes.

**Comment by medvednikov** [comment]
By the way, there's already `Struct{field1, field2}` syntax. It works if all fields are initialized in the expression. So in this example it will work if there are 2 fields in `Struct`.
