### ISSUE TITLE
integer suffix

### ISSUE THREAD

**Issue by d2verb** [vlang/v#1448]
Typing `u32(1)` or `u64(1)` every time is so annoying for me.
How about integer suffix for integer literal like
```
1u32
1u64
0x800000000u32
```

**Comment by medvednikov** [comment]
Sorry, there must be only one way to do this, and it's going to be `u64(1)`. It's only 2 extra keystrokes.

**Comment by mvlootman** [comment]
+1 for single way of doing things , and imho it is more readable type(val).

It's 4 extra keystrokes if you count shift keys  😋

Perhaps your ide/code editor could help here. But keep it out of the language

**Comment by medvednikov** [comment]
This is going to be required only for initialization anyway. `myu64var == 0` will soon be compiling without casting `0`.
