### ISSUE TITLE
Bad web performance 

### ISSUE THREAD

**Issue by tinkerbaj** [vlang/v#14482]
V version:  V 0.2.4 a7afb2d
OS:  linux, Ubuntu 20.04.4 LTS (WSL 2)

I try to contribute to one benchmark git repo. But I get so bad performance with Vlang I try 2 frameworks the last one I tried is Vex.
This is the code I create.
```
module main

import nedpals.vex.router
import nedpals.vex.server
import nedpals.vex.ctx



fn main() {
    mut app := router.new()

    app.route(.get, '/', fn (req &ctx.Req, mut res ctx.Resp) {
        res.send_status(200)
    })

    app.route(.get, '/user', fn (req &ctx.Req, mut res ctx.Resp) {
        res.send_status(200)
    })

    app.route(.get, '/user/:id', fn (req &ctx.Req, mut res ctx.Resp) {
        res.send(req.params['id'], 200)
    })

    server.serve(app, 8080)
}
```
I build a file with -prod flag and run it. I check all with wrk using this command: 
`wrk -H 'Connection: keep-alive' -d 10s -c 64 --timeout 8 -t 12 http://localhost:8080`
I get 11625.16 requests per second does anyone know how to make it faster?

**Comment by JalonSolov** [comment]
This should be reported in the `nedpals/vex` project.
