### ISSUE TITLE
Curl support in standard library

### ISSUE THREAD

**Issue by MatusModder** [vlang/v#14510]
Hello there. I just want to suggest if you can support curl in the standard V library. It will be very nice if this feature will be supported since I want to make a source-based Portage-like package manager for Vinix written in V that will pull the Vbuilds from the repository defined by user and it will automatically build from instructions that are in that Vbuild.

**Comment by JalonSolov** [comment]
What do you need that https://modules.vlang.io/net.http.html#fetch doesn't give you?

**Comment by MatusModder** [comment]
@JalonSolov I will check that library out.
