### ISSUE TITLE
Line number of compile error missing

### ISSUE THREAD

**Issue by l8atnight** [vlang/v#1451]
**V version:** lastest
**OS:** win64

**What did you do?**
compile with error

**What did you expect to see?**
line number of error
 
**What did you see instead?**
F:\v\mylib>..\v test.v
unexpected token: `]`

**Comment by joe-conigliaro** [comment]
This will be updated so line number is always shown

**Comment by medvednikov** [comment]
Please paste the code that results in this. 

I get


```
k.v:3 panic: unexpected token: `}`
```

**Comment by l8atnight** [comment]
`fn main() {

   mut matrix := [0.0,0.0][0.5,0.5]
   matrix[0] = 0.5
   matrix[40] = 0.5   //F:\v\mylib>test
                               //  V panic: array index out of range: 40 / 2
                              //without the below line!

  matrix[0][0] = 0.5  //F:\v\mylib>..\v test.v
                               //Cant [] non-array/string/map. Got type "f32"
                               //no line number!!

	println(matrix[40])
}
`

**Comment by medvednikov** [comment]
Strange, I just tested on macOS and Windows, and I get error lines.

You need `[[0.0,0.0], [0.5,0.5]]`, and `[0][0]` syntax doesn't work yet.

**Comment by l8atnight** [comment]
I thought so too. I update always with:

git pull origin master
make

could that be a reason?

**Comment by joe-conigliaro** [comment]
yes can you please try updating

**Comment by l8atnight** [comment]
@joe-conigliaro  i did that

F:\v\mylib>..\v1 test.v
pass=2 fn=`main`
test.v:10 panic: Cant [] non-array/string/map. Got type "f32"

and it works.
