### ISSUE TITLE
Port code documentation to Doxygen

### ISSUE THREAD

**Issue by jxxp9** [vlang/v#14535]
It would be nice to have function documentation in the Doxygen format to have it format in a nice and readable way

**Comment by spytheman** [comment]
V has its own documentation tool: `v doc`

**Comment by jxxp9** [comment]
well yeah but `v doc` syntax is pretty limited, you can't tag function params etc. Doxygen is a standard tool with a well-known syntax, `v doc` should use the same syntax. Look at `v` own code, for example
