### ISSUE TITLE
Is there an easy way to debug V Code?

### ISSUE THREAD

**Issue by ArcDrake** [vlang/v#1453]
Hi,

I would love to debug V Code, to get a better understanding of what is going on.
Is there an easy way to do that already? I can't set breakpoints.
I'm (currently) using VS Code & The nice V Extension.
I tried v -debug but I get 5000 lines of C Code when trying to debug 9 lines of V?

And second question: How to add a question label in GitHub Issues? :-)

Thanks!

**Comment by spytheman** [comment]
At the moment there seems to be a regression for this feature, since all line numbers are 0 for some reason. 

Anyway, the general idea is that you have to pass option -g to V during the compilation. Then, just use gdb under linux, or Visual Studio on Windows, demonstrated in https://github.com/vlang/v/pull/1313 .

**Comment by ArcDrake** [comment]
Awesome!

Thanks for the hint. I will try to get familiar with GDB and play around a bit.
Beeing able to debug would help me a lot in understanding some things and maybe fix some easy bugs.

Thanks!

**Comment by emily33901** [comment]
`-debuggable` should dump `#file` directives all over the code - works well in visual studio and iirc someone said it worked in gdb aswell

**Comment by spytheman** [comment]
@emily33901 it did, but there was a regression in commit 207bab5 . I'll make a PR in a moment to fix it. https://url4e.com/gyazo/images/2da0c089.png

**Comment by emily33901** [comment]
Cool, thanks

**Comment by medvednikov** [comment]
`-debug` flag needs to change, because it does a different thing, and it's confusing, as we can see here. 

Thanks for fixing it @spytheman.
