### ISSUE TITLE
Using ORM select statement returns square box as result.

### ISSUE THREAD

**Issue by Ouri028** [vlang/v#14541]
OS: linux, Ubuntu 20.04 LTS (WSL 2)
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 4800H with Radeon Graphics
CC version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

getwd: /home/sylvester/Github/v-lang/Vidi-Widget/core
vmodules: /home/sylvester/.vmodules
vroot: /home/sylvester/v
vexe: /home/sylvester/v/v
vexe mtime: 2022-05-27 18:19:04
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 55e7daa.a971b9a

Git version: git version 2.25.1
Git vroot status: weekly.2022.21-28-ga971b9a9-dirty
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 eee03626

**What did you do?**

pub fn get_all_roles() ? []entity.Roles {
	mut db := database.db_conn()?
	roles := sql db {
	select from entity.Roles
	}
	return roles
}

**What did you expect to see?**
[
    {
        "id": "1",
        "name": "Admin",
        "value": "ADMIN",
        "created_at": "2022-05-27 00:45:23",
        "updated_at": "2022-05-27 00:45:23"
    },
    {
        "id": "2",
        "name": "Basic",
        "value": "BASIC",
        "created_at": "2022-05-27 00:45:23",
        "updated_at": "2022-05-27 00:45:23"
    }
]
 
**What did you see instead?**

[
    {
        "id":"",
        "name":"",
        "value":"",
        "created_at":"",
        "updated_at":""
    },
    {
        "id":"",
        "name":"",
        "value":"",
        "created_at":"",
        "updated_at":""
    }
]

**Comment by tarasyyyk** [comment]
Looks like the issue in db charset encoding.
What database do you use?

You can execute this statement `SET NAMES 'utf8';` ([for MySql](https://stackoverflow.com/a/2159453/7586883)) before retrieving rows.

**Comment by Ouri028** [comment]
Hey @tarasyyyk ,



Thanks for the reply, I'm using MYSQL V8.

I tried running the SET NAMES query as well as setting the default character set of MYSQL to UTF-8 and also tried UTF8mbf and still getting the same result, but what I find funny is that when running a standard query like:

mut db := database.db_conn()?
roles := db.query("select * from roles;")?
db.close()
maps := roles.maps()
return maps

It works fine, its only when using the ORM functions that the return value gets messed up.


QUERY:

[
    {
        "id": "1",
        "name": "Admin",
        "value": "ADMIN",
        "created_at": "2022-05-28 11:37:18",
        "updated_at": "2022-05-28 11:37:18"
    },
    {
        "id": "2",
        "name": "Basic",
        "value": "BASIC",
        "created_at": "2022-05-28 11:37:18",
        "updated_at": "2022-05-28 11:37:18"
    }
]


ORM:

[
    {
        "id":"",
        "name":"",
        "value":"",
        "created_at":"",
        "updated_at":""
    },
    {
        "id":"",
        "name":"",
        "value":"",
        "created_at":"",
        "updated_at":""
    }
]
