### ISSUE TITLE
Can vlang be compiled into standard DLL files? I want to write DLL with it.

### ISSUE THREAD

**Issue by xiaokentrl** [vlang/v#14567]
Can vlang be compiled into standard DLL files? I want to write DLL with it.

**Comment by changrui** [comment]
@xiaokentrl view https://github.com/vlang/v/tree/master/examples/call_v_from_python please.

**Comment by xiaokentrl** [comment]
> @xiaokentrl view https://github.com/vlang/v/tree/master/examples/call_v_from_python please.

Thank you very much for your reply!

I want to compile to standard DLL, not just Python calls. 
Maybe PHP can also be used, such as private encrypted DLL.

**Comment by JalonSolov** [comment]
There is nothing special about the DLL that's created.  The only thing you need to create DLLs from V is to add the `[export: 'my_custom_c_name']` attributes on things you want to be callable, and compile the code with `-shared`.

Add `-os windows` if you're cross-compiling from another system.

**Comment by xiaokentrl** [comment]
> There is nothing special about the DLL that's created. The only thing you need to create DLLs from V is to add the `[export: 'my_custom_c_name']` attributes on things you want to be callable, and compile the code with `-shared`.
> 
> Add `-os windows` if you're cross-compiling from another system.

@JalonSolov 
Thank you very much for your reply!
