### ISSUE TITLE
signal.h is not included in #ifndef _WIN32 (but is in ifdef _WIN32)

### ISSUE THREAD

**Issue by chipnetics** [vlang/v#14561]
**V version:** V 0.2.4 928dafe
**OS:** Debian Linux

**What did you do?**
v -keepc foo.v
Looked at C output in /tmp/v_1000/

**What did you expect to see?**
`#include <signal.h>` within #ifndef _WIN32
 
**What did you see instead?**
No include for signal.h

This results in an error when using the .c output in tools such as Emscripten as signal is now implicitly defined.

i.e. `Implicit declaration of functional 'signal' is invalid in C99. [-Werror, -Wimplicit-function-declaration]`

**Comment by spytheman** [comment]
With latest V 5a2c271, if you use `-d no_segfault_handler` or `-os wasm32`, signal.h will not be included at all.
