### ISSUE TITLE
v.c compile error under freeBSD 12.0 release.

### ISSUE THREAD

**Issue by changrui** [vlang/v#1457]
**V version:** 
`v0.1.17`

**OS:** 
freeBSD 12.0

**What did you do?**
`gcc -std=gnu11 -w -o v v.c`

**What did you expect to see?**
`compile success.`
 
**What did you see instead?**
v.c:4391:16: error: `array initialized from non-constant array expression.`
      `int mib[4] = (int[]){1,14,12,-1};`
please check it.

**Comment by medvednikov** [comment]
What's your GCC version?

**Comment by spytheman** [comment]
@medvednikov 
I think it boils down to: 
```
int main(){
   int mib[4] = (int[]){1, 14, 12, -1};
   return 0;
}
```
vs 
```
int main(){
   int mib[4] = {1, 14, 12, -1};
   return 0;
}
```
(int[]){1, 14, 12, -1}  compiles fine under clang version 7.0.1, but does not under gcc 5.5 .

**Comment by spytheman** [comment]
I am installing a freebsd image in VirtualBox in order to test their default compiler.

**Comment by spytheman** [comment]
cc --version gives:

FreeBSD clang version 6.0.1 (based on LLVM 6.0.1)
Target: x86_64-unknown-freebsd12.0
Thread model: posix

https://url4e.com/gyazo/images/f159fbff.jpg

**Comment by medvednikov** [comment]
So it's just an old C compiler. I need [1,2,3] to be an expression. Any way to achieve that with old C compilers?

**Comment by spytheman** [comment]
FreeBSD's default clang cc compiler does not mind compiling v.c at all.
I am still downloading the gcc compiler with
```
pkg install gcc
```
which seems that it will install gcc 8.3 .

**Comment by spytheman** [comment]
It seems that even gcc 9.1 (latest from this year), would not accept
int mib[4] = {1, 14, 12, -1};

**Comment by medvednikov** [comment]
Fixed.
