### ISSUE TITLE
suggest to v run command: put middle .c and excute file to /tmp.

### ISSUE THREAD

**Issue by changrui** [vlang/v#1460]
When we run a v program, we may store the middle file `.c`, binary file to /tmp, after program terminate, remove them.

`v run .` ===> /tmp/.main.c, /tmp/main(.exe)

After terminal, `rm /tmp/main.*`

**Comment by spytheman** [comment]
I think too that storing the intermediary files outside the current folder may be a good idea for script execution (v run).

Removing the final executable after it was run, however may prevent #1365 .

**Comment by medvednikov** [comment]
When V was released, there were major issues with `/tmp`. On some systems creating a file there resulted in a segfault :O

**Comment by lutherwenxu** [comment]
It now drops them to a cache folder. Is that better?

**Comment by lutherwenxu** [comment]
It now drops them to a cache folder. Is that better?
