### ISSUE TITLE
typedefs dont work

### ISSUE THREAD

**Issue by emdete** [vlang/v#14707]
for reproducing the bug i made this header

```
struct object_ {
	int id; 
};

typedef struct object_ object;

object* new(int id) {
	object* o = malloc(sizeof(object));
	o->id = id;
	return o; 
}
```

and this V code:

```
#flag -I.
#include "C.h"

fn C.new(int)&C.object
[heap] struct C.object { id int }

fn main() {
	o := C.new(42)
	eprintln("o has id $o.id")
}
```

this generates a C code like this:

```
struct object* o = new(42);
```

which is wrong because `object` is a typedef, not a struct, `object* o = new(42);` would be correct. 

as a workaround i replace `object` with `object_` which works fine.

**Comment by ChAoSUnItY** [comment]
From [doc's attribute section](https://github.com/vlang/v/blob/master/doc/docs.md#attributes).

You probably want to replace `[heap]` attribute with `[typedef]` attribute.

**Comment by emdete** [comment]
yes, you are right: i did not read the doc :/ sorry
