### ISSUE TITLE
Segmentation Fault with pkgconfig

### ISSUE THREAD

**Issue by Schmiddiii** [vlang/v#14714]
**V version:** V 0.2.4 8027919.1d46213
**OS:** linux, "ArcoLinux"

**Minimal Examples**
```vlang
module main

#pkgconfig gtk+-3.0

fn main() {
}
```

```vlang
module main

fn main() {
	$if $pkgconfig('gtk+-3.0') {
	        println('GTK')
	} $else {
	        println('No GTK')
	}
}

```

**What did you do?**

Compile using `v file.v`.

**What did you expect to see?**

Compiled output.
 
**What did you see instead?**

Segmentation fault `zsh: segmentation fault (core dumped)  v file.v`.
This only seems to happen for some libraries, e.g. `alsa` is working fine.

Maybe for completeness, `/usr/lib/pkgconfig/gtk+-3.0.pc`:

```
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include
targets=broadway wayland x11

gtk_binary_version=3.0.0
gtk_host=x86_64-linux

Name: GTK+
Description: GTK+ Graphical UI Library
Version: 3.24.34
Requires: gdk-3.0 atk >= 2.35.1  cairo >= 1.14.0 cairo-gobject >= 1.14.0 gdk-pixbuf-2.0 >= 2.30.0 gio-2.0 >= 2.57.2
Requires.private: atk atk-bridge-2.0 wayland-client >= 1.14.91 xkbcommon >= 0.2.0 wayland-cursor >= 1.14.91 wayland-egl epoxy >= 1.4 fribidi >= 0.19.7 pangoft2 gio-unix-2.0 >= 2.57.2
Libs: -L${libdir} -lgtk-3
Cflags: -I${includedir}/gtk-3.0
```

Let me know if any other information is needed to reproduce.

**Comment by Dialga** [comment]
Fixed by https://github.com/vlang/v/pull/16342.
