### ISSUE TITLE
gzip failed to decompress valid gzip file

### ISSUE THREAD

**Issue by ChAoSUnItY** [vlang/v#14711]
OS: windows, Microsoft Windows 11 Home v22000 64-bit
Processor: 20 cpus, 64bit, little endian, 12th Gen Intel(R) Core(TM) i7-12700
CC version: Error: exec failed (CreateProcess) with code 2: 系統找不到指定的檔案。
 cmd: cc --version

getwd: C:\Users\chaos\projects\v
vmodules: C:\Users\chaos\.vmodules
vroot: C:\Users\chaos\projects\v
vexe: C:\Users\chaos\projects\v\v.exe
vexe mtime: 2022-06-06 16:44:07
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 abf3527.ce26d5b

Git version: git version 2.35.1.windows.2
Git vroot status: weekly.2022.22-61-gabf35270 (1 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 125e21e2

**What did you do?**
`v run nbt.v`

```v
import os
import compress.gzip

fn main() {
	mut bytes := os.read_bytes("./signal_intervals.dat")?
	bytes = gzip.decompress(bytes)?
	println(bytes)
}
```
[signal_intervals.dat](https://paste.c-net.org/EduardDicey)
**What did you expect to see?**
printing decompressed bytes then exits with 0.
 
**What did you see instead?**
```
V panic: optional not set (length verification failed, got 312, expected 939589632)
v hash: ce26d5b
C:/Users/chaos/AppData/Local/Temp/v_0/nbt.7859802426163444827.tmp.c:8558: at _v_panic: Backtrace
C:/Users/chaos/AppData/Local/Temp/v_0/nbt.7859802426163444827.tmp.c:8521: by panic_optional_not_set
C:/Users/chaos/AppData/Local/Temp/v_0/nbt.7859802426163444827.tmp.c:21287: by main__main
C:/Users/chaos/AppData/Local/Temp/v_0/nbt.7859802426163444827.tmp.c:21729: by wmain
004b8358 : by ???
004b84bb : by ???
7fff8e4354e0 : by ???
```

**Additional note:**
`.dat` file is a file extension known to be store NBT (Named Binary Tag) format, and its specification is descripted [here](https://minecraft.fandom.com/wiki/NBT_format#Binary_format). In this case, `station_intervals.dat` is a valid gzip file, it should decompressed without any exception.

**Workaround for gzip file validation:**
`v run nbt.v`
```v
import compress.deflate

fn main() {
	mut bytes := os.read_bytes("./signal_intervals.dat")?[10..]
	bytes = deflate.decompress(bytes)?
	println(bytes)
}
```

**Comment by Le0Developer** [comment]
The gzipped file is not [rfc1952](https://datatracker.ietf.org/doc/html/rfc1952) compliant, because it's missing the 8 byte trailer (which contains the filesize and checksum).

You can use the following code to add the missing trailer:
```v
import compress.deflate
import hash.crc32


fn add_trailer(mut data []u8) {
    decompressed := deflate.decompress(data[10..])?
    checksum := crc32.sum(decompressed)
    length := decompressed.len
    data << [
        u8(checksum >> 24),
        u8(checksum >> 16),
        u8(checksum >> 8),
        u8(checksum),
        u8(length >> 24),
        u8(length >> 16),
        u8(length >> 8),
        u8(length),
    ]
}

```
NB: this assumes the header is 10 bytes. It may be longer if it contains extra flags, filename or a header checksum.
