### ISSUE TITLE
[BUG 🐛]:  `vfmt` removes module name from structs referenced in `sql` statements

### ISSUE THREAD

**Issue by N0tExisting** [vlang/v#14732]
## **V Doctor:** 
**OS:** `windows, Microsoft Windows 10 Home v19044 64-bit`
_Processor:_ `8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz`
_CC version:_ `cc (Rev1, Built by MSYS2 project) 11.3.0`

_getwd:_ `G:\source\Repos\v_blog`
_vmodules:_ `C:\Users\Felix\.vmodules`
_vroot:_ `G:\v`
_vexe:_ `G:\v\v.exe`
_vexe mtime:_ `2022-06-09 11:15:11`
_is vroot writable:_ `true`
_is vmodules writable:_ `true`
**V full version:** `V 0.2.4 d24dce8.39e54a5`

_Git version:_ `git version 2.36.1.windows.1`
_Git vroot status:_ `weekly.2022.20-189-g39e54a50 (4 commit(s) behind V master)`
_.git/config present:_ `true`
_thirdparty/tcc:_ `N/A`

## **What did you do?**
given:
```v
module models

struct User {
	// ...
}
```
```v
// somefile.v
import orm
import models

fn init_db(db orm..Connection) {
	sql db {
		create table models.User
	}
}
```

## **What did you expect to see?**
`models.User` is kept:
```v
// somefile.v
import orm
import models

fn init_db(db orm..Connection) {
	sql db {
		create table models.User
	}
}
```
 
## **What did you see instead?**
instead it formats to:
```v
// somefile.v
import orm
import models

fn init_db(db orm..Connection) {
	sql db {
		//	Error ↴
		create table User
	}
}
```

**Comment by vladimirmyshkovski** [comment]
I have the same error in one place, but in other places there is no error.

**Comment by JalonSolov** [comment]
Although this is not yet fixed, I'd recommend always following this procedure:  If you find a bug with V, immediately do `v up` and try again, in case it has already been fixed.  If you still hit the same error, then report it.

I say this because your version of V is 265 commits behind the current.

In this particular case, it wouldn't have helped, since the problem is still there.

**Comment by KeitoTobi1** [comment]
i have the same error in V Version `10051e0`.
