### ISSUE TITLE
Simpler Map syntax

### ISSUE THREAD

**Issue by maassg** [vlang/v#1475]
Since with maps we use string keys most of the time, I suggest 
- for Map initialization syntax:
  m := { foo: ‘bar’, baz: ‘kek’ }
  m := { ['foo is nice']: 'bar', ... }
  k := 'foo'
  m := { [k] : 'bar', ... }
  k := 99
  m := { [k] : 'bar', ... }

- for Map access syntax:
  m.foo 
  m.foo = 'bar'
  m['foo'] = 'bar'
  k := 'foo'
  m[k] = 'bar'

**Comment by medvednikov** [comment]
This is the strangest request I've seen :)

Sorry, not happening.
