### ISSUE TITLE
Tetris example does not work

### ISSUE THREAD

**Issue by gitboy16** [vlang/v#14765]
Hi
Running the following: `v run examples\tetris\tetris.v` on windows 10.
V version : v 0.2.4 2052210
I did `v up` before running the above.
I got an error message:
Microsoft Visual C++ Runtime Library
Assertion failed!
Program: C:\v\examples\tetris\tetris.exe
File: C:/v/thirdparty/sokol/sokol_app.h
Line: 6048
Expression: _sapp.wgl.arb_pixel_format
Thank you

**Comment by JalonSolov** [comment]
Make sure your video driver is updated, and supports at least OpenGL 3.3+.

**Comment by gitboy16** [comment]
Correct ...opengl issue. Thank you
