### ISSUE TITLE
SumType cast c error

### ISSUE THREAD

**Issue by LouisSchmieder** [vlang/v#14771]
**V version:** 
**OS:** Ubuntu 20.04

Other issue to that: #12110 

**What did you do?**
```v
module main

type Test = int | u32 | f32

fn main() {
    data := Test(12)
    eprintln(int(data))
}
```

**What did you expect to see?**
Error message that you can't cast a sumtype or use the ascast instead
 
**What did you see instead?**`
```v
==================
/tmp/v_1000/a.2857547498310302724.tmp.c:11642: error: cannot convert 'struct main__Test' to 'int'
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang```

**Comment by JalonSolov** [comment]
V should definitely give a better error message, however, I'm not sure casting should be used this way.

This change to the code makes it work as expected:
```v
type Test = int | u32 | f32

fn main() {
    data := Test(12)
    eprintln(data as int)
}
```

**Comment by LouisSchmieder** [comment]
I think this is a better way indeed since our one-way philosophy
