### ISSUE TITLE
string.f64() can not parse `,` 

### ISSUE THREAD

**Issue by kahsa** [vlang/v#14789]
**V version: ArchLinux** 
**OS: 0.2.4 e031096** 

**What did you do?**
```v
fn main() {
	println('1,011'.f64())
	println('1,011'.int())
}
```

**What did you expect to see?**
both `1011`
 
**What did you see instead?**
```
1.
1
```

It is strange that works with `K` but not `,`.
```v
println('1011K'.f64())
```
Also strange that `'1_011'.int()` is possible but  `'1,011'.int()` is not.

**Comment by JalonSolov** [comment]
This is working exactly as documented here:  https://github.com/vlang/v/blob/master/doc/docs.md#numbers

`_` is a recognized number separator, while `,` is not.

The convenience methods of `.f64()` and `.int()` are also documented as only translating digits until the first non-digit is seen.

If you want more control, or just to know if the string you are translating is _only_ digits (or recognize `_` separator), use `strconv` module functions.

**Comment by kahsa** [comment]
@JalonSolov Sorry, I can't find where it says the comma is out of spec, can you point me to it?

**Comment by kahsa** [comment]
@JalonSolov And if it does not parse , it should produce an error.
I think it is dangerous to operate without error or warning, but what do you think?
Shouldn't there at least be an error message?
The same goes for the K prefix.
I do not tolerate this dangerous design specification.

**Comment by kahsa** [comment]
Hence, I identify this as a bug.
If you do not want to include parsing commas in the specification, you must issue an error message.

**Comment by kahsa** [comment]
Do not output `1,011` as `1.`.
It should be an error.
Otherwise, the program will continue to calculate it as `1`, which is a bug in the application.
What do you think? @JalonSolov

**Comment by JalonSolov** [comment]
The `strconv` functions return an optional.  The convenience methods act exactly like C functions of a similar type.
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main () {
   int val;
   char str[20];
   
   strcpy(str, "98993489");
   val = atoi(str);
   printf("String value = %s, Int value = %d\n", str, val);

   return(0);
}
```
Output is
```
1
```

**Comment by kahsa** [comment]
@JalonSolov Thanks for telling me a workaround.

I think this is a matter of philosophy.
Is V a C-language philosophy?
I think no.

If it were a C language, it would be
`('1,000').int() + ('900').int() == 901`.
would also be possible.
But I don't believe V has the philosophy to allow it.

`('1,000').int() + ('900').int() == 1900`
should be.

**Comment by JalonSolov** [comment]
`,` is only valid as an _output_ character, and only if you apply the proper formatting.
