### ISSUE TITLE
string indexing is temporarily disabled on the playground, will be fixed soon 

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#148]
```
fn main() {
	types := 'game'
	println(types[0])
	println('success')
}
```
output:
```
test.v:3
string indexing is temporarily disabled on the playground, will be fixed soon 
```
Wait for len and string indexing function.
Since len and string indexing is disabled on the playground,I can not rewrite my json string parser into vlang to get the feeling of vlang.

**Comment by medvednikov** [comment]
Fixed about a week ago, together with `.len`.
