### ISSUE TITLE
order- or main-related compilation error ?

### ISSUE THREAD

**Issue by lobotony** [vlang/v#1481]
**V version:** 
0.1.17
**OS:** 
MacOS 10.14.6
**What did you do?**
tried to compile the following:
println('hello')

struct User {
    id int 
    name string
} 

struct Repo {
    users []User 
}

**What did you expect to see?**
successful compilation, because it does compile if I put the println() underneath the structs
 
**What did you see instead?**
get_type() bad type
pass=2 fn=`main`
panic: break.v:9
unknown type `User`

After reading some more documentation I was confused about what to expect:
* should the compiler have warned about a missing main()?
* is this supposed to work in the first place?

**Comment by medvednikov** [comment]
this is a bug with `fn main() { }`

yes it's supposed to work
