### ISSUE TITLE
asset_manager.h not found

### ISSUE THREAD

**Issue by buddhhu** [vlang/v#14858]
**V version:** 
**OS: Android 10** 

**What did you do?**
I was trying to install `vlang` in termux by cloning and entering `v` directory and using `make` command.

**What did you expect to see?**
It should show `Successfully Installed`
 
**What did you see instead?**
```cd ./vc && git clean -xf && git pull --quiet
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
The executable './thirdparty/tcc/tcc.exe' does not work.
cc  -std=gnu99 -w -o v1.exe ./vc/v.c -lm -lpthread
./v1.exe -no-parallel -o v2.exe  cmd/v
builder error: Header file <asset_manager.h>, needed for module `os` was not found. Please install the corresponding development headers.
builder error: Header file <asset_manager.h>, needed for module `os` was not found. Please install the corresponding development headers.
make: *** [GNUmakefile:97: all] Error 1```

**Comment by Larpon** [comment]
You need to include the ndk headers from `include/android`

**Comment by Larpon** [comment]
There's now better support for termux via `$if termux { ... }` ...

**Comment by ntrrg** [comment]
Great! it is working now

**Comment by Larpon** [comment]
> Great! it is working now

Credit goes to @spytheman for fixing this 👍🏻
