### ISSUE TITLE
Build vget ONCE, do not compile it every time.

### ISSUE THREAD

**Issue by changrui** [vlang/v#1488]
Now run `v install ...` will cause recompile `vget` again, it's not a good idea. I strongly recommend to make `v/bin` and put execute files to there, such as `vget`, `v`, etc.

**Comment by iredmail** [comment]
Hi @changrui,

Could you help test whether it’s fixed with this commit?
https://github.com/vlang/v/commit/d072178cef7910cc94b26d54b1004f71a834ce8e

**Comment by medvednikov** [comment]
Placing it in v/bin will not solve anything.

What's the problem with running `v run vget.v`? vget.v can change, the latest version must be run.

Compilation takes a couple hundred ms.
