### ISSUE TITLE
Proposal: #lang & GC<t>

### ISSUE THREAD

**Issue by zaoqi** [vlang/v#1489]
It is almost impossible to handle all cases of memory management at compile time and to be compatible with C.for example: [`eval` a string](https://github.com/kyren/luster).

# GC\<t\>

* Most cases are handled at compile time.
* Use ARC to handle the rest cases.
* GC when memory overflows

# #lang

The `#lang` line that starts a file declares the base language of the file.

* `#lang v/sh`: V Script
* `#lang v/base`: the core V language, manual memory management or `GC<t>` are required.
* `#lang v/base/translated`: translated code
* `#lang v`: V

##### related issues
https://github.com/vlang/v/issues/1247
https://github.com/vlang/v/issues/274

**Comment by dcurrie** [comment]
Immutable data structures in which ownership is shared, like immutable trees, are practically impossible without GC. The Rust folks understand this; see this [y-combinator discussion](https://news.ycombinator.com/item?id=16142808). V's focus on immutability therefore makes GC a necessity if it is to meet its potential. I've been ringing the memory management bell for a while in the forum and in the github issues for this reason. Is there an alternative for V that will work? Awaiting the memory management design...
