### ISSUE TITLE
Thoughts on V UI license?

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#1492]
Hello,

V UI will be open-sourced soon.

I'm considering Qt's model to finance V's development. It'd be nice to be able to hire 1 or 2 full-time developers.

Free open source license, and a proprietary license for a reasonable price.

What do you think?

**Comment by Delta456** [comment]
Seems ok with me c:

**Comment by iredmail** [comment]
I don’t prefer this way personally. 

- if most V programmers use v ui, it’s gonna work. But if not, only the v ui users pay for the license and sponsor the v development. The revenue may be not enough to hire full-time employee(s).
- is a consultant company behind V a better choice and most importantly, generate more revenue?
- we may get more web developers, how about moving vweb to a separate repo and charging little fee like $1, $5 (just for example) for vweb instead?

**Comment by medvednikov** [comment]
This model can only be used with the V UI module.

The web framework and the rest of V will always be MIT.

**Comment by iredmail** [comment]
I don’t understand why it cannot be vweb. :(

**Comment by iredmail** [comment]
Another idea:

- develop few non-core modules as a bundle, require a monthly/annually subscription fee or pay once for lifetime license to use them. Note: I mean non core modules, like pg, sqlite, vweb, v ui.

**Comment by joe-conigliaro** [comment]
It would still be open source, you would just need a license for commercial use.
