### ISSUE TITLE
support intellij idea and debug

### ISSUE THREAD

**Issue by zhuxiujia** [vlang/v#14946]
support [intellij idea](https://www.jetbrains.com/idea/) or [clion](https://www.jetbrains.com/clion/) and debug.

This IDE is by far the best experience.

I don't understand the implementation of the debug function, is it compiled into C first and then this breakpoint?

**Comment by nedpals** [comment]
While I understand your concern and indeed having Jetbrains support is a wonderful addition, please do not pollute the issue tracker with multiple instances of the same issue as you have posted previously in #1017 and #3896. You might want to check #465 from time to time instead.

On the other hand, you can also check out our progress in running the language server in IntelliJ: https://github.com/vlang/vls/issues/52
