### ISSUE TITLE
Compiler error-behaviour on return value with sorting

### ISSUE THREAD

**Issue by chipnetics** [vlang/v#14944]
**V version:**  V 0.3.0 eb10cc9.3bdf2f0
**OS:**  Debian GNU/Linux 11 (bullseye)

**What did you do?**

Ran slighlty modified sorting example from the Docs

```v
struct User {
	age  int
	name string
}

fn main() {
	mut users := [User{21, 'Bob'}, User{65, 'Bob'}, User{25, 'Alice'}]
	do_some_sort(mut users)
	println(users)
}

fn do_some_sort(mut users []User) []User {

	custom_sort_fn := fn (a &User, b &User) int {

		if a.name == b.name {
			if a.age < b.age {
				return 1
			}
			if a.age > b.age {
				return -1
			}
			return 0
		}
		if a.name < b.name {
			return -1
		} else if a.name > b.name {
			return 1
		}
		return 0
	}

	return users.sort_with_compare(custom_sort_fn)
}
```

**What did you expect to see?**
No errors
 
**What did you see instead?**
```
scratch99.v:33:2: error: `users.sort_with_compare(custom_sort_fn)` used as value
   31 |     }
   32 | 
   33 |     return users.sort_with_compare(custom_sort_fn)
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   34 | }
```

To bypass the error you instead need to evaluate as two separate statements, as below:

```v
users.sort_with_compare(custom_sort_fn)
return users
```

**Comment by JalonSolov** [comment]
That's because `sort_with_compare` doesn't return anything, so there's nothing for your return to send back.  No value means nothing to return.

`sort_with_compare sorts the array in-place using the results of the given function to determine sort order.`

**Comment by chipnetics** [comment]
I follow... though I would still think that the return should do the in-place sort, and know to return users itself after the in-place sort....

**Comment by chipnetics** [comment]
More I think about it, I do presume that would be rather complicated to implement however
