### ISSUE TITLE
Safe code can create and dereference null via nested zero-initialization

### ISSUE THREAD

**Issue by andersk** [vlang/v#14958]
**V version:** `V 0.3.0 3f3fb5b.819b6f4`
**OS:**  `linux, Linux version 5.18.8 (nixbld@localhost) (gcc (GCC) 11.3.0, GNU ld (GNU Binutils) 2.38) #1-NixOS SMP PREEMPT_DYNAMIC Wed Jun 29 07:04:44 UTC 2022`

Previously, safe code could get a null reference from a zero-initialized array of references (#14914), violating the home page’s claim that V has “No null (allowed in unsafe code)”. A compiler check was added for that case, emitting a warning that will later be turned into an error.

However, that check fails to catch references in fixed-size arrays, or nested within arrays of other types. A recursive check is needed for references at any level. Some examples:

```console
$ cat test1.v
fn main() {
    println([1]&int{})
}

$ ./v run test1.v
signal 11: segmentation fault

$ cat test2.v
fn main() {
    println(*([][1]&int{len: 1}[0][0]))
}

$ ./v run test2.v
signal 11: segmentation fault

$ cat test3.v
struct Foo {
    n &int
}

fn main() {
    println(*[]Foo{len: 1}[0].n)
}

$ ./v run test3.v
signal 11: segmentation fault
```

There are probably other cases too (function pointers? generics?).

Related: #10837 for maps, #14911 for structs.

**Comment by medvednikov** [comment]
The first one is fixed:

```
fixed arrays of references need to be initialized right away (unless inside `unsafe`)
```
