### ISSUE TITLE
net.http download file Error

### ISSUE THREAD

**Issue by AnimalStudioOfficial** [vlang/v#14954]
OS: windows, Microsoft Windows 11 Home v22000 64-bit
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
CC version: cc (Rev10, Built by MSYS2 project) 11.2.0

getwd: C:\Users\Dragon boy\Downloads\c2v-master (2)\c2v-master\tests\ved
vmodules: C:\Users\Dragon boy\.vmodules
vroot: C:\v-master\v-master\v\v-master
vexe: C:\v-master\v-master\v\v-master\v.exe
vexe mtime: 2022-06-27 23:09:03
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 6b2d3a8

Git version: git version 2.24.1.windows.2
Git vroot status: weekly.2022.24-105-g6b2d3a82 (59 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 125e21e2

**What did you do?**
I ran my program `Memory.exe `

**What did you expect to see?**
I wanted to download a file with net.http
 
**What did you see instead?**
An error message: `failed to open file "."`

**Here is the file**
`import net.http`
`fn main() {`
`http.download_file("https://github.com/vlang/v/releases/download/0.3/v_windows.zip",'.') or {println(err)}`
`}`

**Comment by JalonSolov** [comment]
This is a bug in the documentation... what it wants is the _complete_ output path, including the file name, not just the directory to put the file in.

This is the way the current code is written.

It's possible the routine could could be changed to take the last part of the URL as the filename, but that isn't guaranteed to work all the time.

**Comment by AnimalStudioOfficial** [comment]
> This is a bug in the documentation... what it wants is the _complete_ output path, including the file name, not just the directory to put the file in.
> 
> This is the way the current code is written.
> 
> It's possible the routine could could be changed to take the last part of the URL as the filename, but that isn't guaranteed to work all the time.

Oh ok tysm
