### ISSUE TITLE
should implements interface explictly

### ISSUE THREAD

**Issue by Silentdoer** [vlang/v#14953]
**V version:** 
**OS:** 

**What did you do?**
like rust: impl Interface for Struct

**What did you expect to see?**

 
**What did you see instead?**

**Comment by medvednikov** [comment]
It's about explicit vs implicit interfaces.

Both have pros and cons, V uses the Go way. Implicit interfaces.

**Comment by Silentdoer** [comment]
implements interface explictly will be more clear

**Comment by medvednikov** [comment]
On the benefits:

https://old.reddit.com/r/golang/comments/eqcfhz/understanding_the_advantages_of_implicit/

**Comment by Silentdoer** [comment]
Rust's trait seems to be able to achieve the same function and is clearer, and when two third-party library interfaces are introduced with the same function signature list, rust can explicitly specify which one to implement but go cannot?.
