### ISSUE TITLE
C error on [1]&int{}[0]

### ISSUE THREAD

**Issue by andersk** [vlang/v#14959]
**V version:** `V 0.3.0 3f3fb5b.819b6f4`
**OS:**  `linux, Linux version 5.18.8 (nixbld@localhost) (gcc (GCC) 11.3.0, GNU ld (GNU Binutils) 2.38) #1-NixOS SMP PREEMPT_DYNAMIC Wed Jun 29 07:04:44 UTC 2022`

While experimenting with #14958, I noticed that the V code `[1]&int{}[0]` compiles to the invalid C code `{0}[0]`, leading to “C error. This should never happen.”

```console
$ cat test.v
fn main() {
    println([1]&int{}[0])
}
$ ./v -cg run test.v
tcc: error: file 'crt1.o' not found
tcc: error: file 'crti.o' not found
/tmp/v_1000/test.3450692629302334504.tmp.c:12076: error: identifier expected
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by medvednikov** [comment]
There's now an error handling this:

```
fixed arrays of references need to be initialized right away (unless inside `unsafe`)
```

Still results in a C error.
