### ISSUE TITLE
Cannot cast value to inline sumtype

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#14967]
**V doctor:**
```
OS: linux, Ubuntu 20.04.4 LTS (WSL 2)
Processor: 16 cpus, 64bit, little endian, 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
CC version: cc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0

getwd: /home/daniel/Projects/v
vmodules: /home/daniel/.vmodules
vroot: /home/daniel/Projects/v
vexe: /home/daniel/Projects/v/v
vexe mtime: 2022-07-06 13:24:53
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 8b8667d

Git version: git version 2.25.1
Git vroot status: 0.3-32-g8b8667dd-dirty (21 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 827f7452

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg main.v`
```v
module main

fn main() {
	x := (string | none)(none)
	println(x)
}

```

**What did you expect to see?**

(string | none)(none) should be none casted string | none

**What did you see instead?**
```
main.v:4:22: error: expression evaluated but not used
    2 | 
    3 | fn main() {
    4 |     x := (string | none)(none)
      |                         ~~~~~~
    5 |     println(x)
    6 | }
```

**Comment by yuyi98** [comment]
ok, I'll try.

**Comment by danieldaeschle** [comment]
@JalonSolov V supports anonymous sum types.

**Comment by Wajinn** [comment]
> That syntax doesn't look right. It just looks like an error.
> anonymous sumtype which V doesn't support... and I don't know if it should.

Looking at that code, it seems a bit weird, and there isn't clarity about the purpose of it.  This isn't an example of useful usage, more so than a demonstration of it can be done, and then pulling yuyi98 in.  

Anonymous sum types also isn't explained in the documentation.  It would be nice to explain the need and use case of it.

**Comment by danieldaeschle** [comment]
I will explain it in documentation.

The purpose is the lazy assign of a function result.

```
fn foo() string | none {...}


mut x := (string | none)(none)

if y {
    x = foo()
}
```

**Comment by JalonSolov** [comment]
Yes, there are anonymous sumtypes for function returns.  I don't really agree with that, either, but it's there.

Anonymous inline sumtypes, though, is something new.

**Comment by danieldaeschle** [comment]
If you don't agree with the syntax, please give a better Idea instead of complaining about.

Anonymous sum types have their needed use case and this feature is missing.

If you want anonymous sum types removed you should've discussed in the mentioned issues.

**Comment by medvednikov** [comment]
Yeah same, I've been going back and forth on it.

It's useful, but seeing stuff like ` x := (string | none)(none)` makes me think it doesn't belong in a small and simple language like V.

**Comment by danieldaeschle** [comment]
Because using `none` and `IError` are forbidden for named types.

**Comment by yuyi98** [comment]
```v
x := string|none(none)

fn foo() string|none {...}
```
Do they look better?  Treat anonymous SumType as a type body with no Spaces.

**Comment by Wajinn** [comment]
For others that might be following along or come by this, Vlang RFCs (https://github.com/vlang/rfcs).

**Comment by medvednikov** [comment]
> Because using none and IError are forbidden for named types.

@danieldaeschle why?

**Comment by medvednikov** [comment]
Also, now `?!Foo` doesn't seem so complex. Not much more complex than say `[]&Foo`.

**Comment by kahsa** [comment]
Does it mean this will be possible too?
```v
fn foo() string | int{
	return 1
}

fn main() {
	a := foo()
	b := (string | int)(2)
	println(a == b)
}
```

**Comment by danieldaeschle** [comment]
1. Because we decided that. Dunno why
2. Yes!
3. Yes!
