### ISSUE TITLE
error: undefined ident: `termux`

### ISSUE THREAD

**Issue by Rockung** [vlang/v#15007]
**V version: V 0.3.0 ec75860** 
**OS: Linux lebei-Inspiron-7560 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux ** 

**What did you do?**

import os
fn main() {
}

v run foo.v

**What did you expect to see?**

 
**What did you see instead?**
/home/lebei/learning/v/vlib/os/os.v:343:6: error: undefined ident: `termux`
  341 |         return 'android'
  342 |     }
  343 |     $if termux {
      |         ~~~~~~
  344 |         return 'termux'
  345 |     }

**Comment by medvednikov** [comment]
`v up`
