### ISSUE TITLE
unexplainable thread results

### ISSUE THREAD

**Issue by despiegk** [vlang/v#15025]
- latest V

<img width="642" alt="image" src="https://user-images.githubusercontent.com/6021844/178265589-98baf029-31a3-4be5-b14f-07da95208ffe.png">

<img width="1531" alt="image" src="https://user-images.githubusercontent.com/6021844/178265651-e6694f92-2bac-4b2a-b573-6f824fd34604.png">

this should never be the case, a thread is created in which we empty a map (re-initialize), but yet the thread sees it

test script on https://github.com/freeflowuniverse/crystallib/blob/development_refactor/redisclientcore/examples/redis_connect.v

notice the branch: "development_refactor"

**Comment by despiegk** [comment]
is on m.1 osx

**Comment by emily33901** [comment]
> this should never be the case, a thread is created in which we empty a map (re-initialize), but yet the thread sees it

this sounds fine to me, I see no synchronisation between the threads here.

**Comment by despiegk** [comment]
there is a testscript on https://github.com/freeflowuniverse/crystallib/blob/development_refactor/redisclientcore/examples/redis_connect.v

**Comment by despiegk** [comment]
if you remove
```
time.sleep(100 * time.millisecond)
```
from the connection function it will give connection errors on m1 apple

Alexandre told me we have to use a locking construct, I thought when doing a thread and having a new empty variable should be enough??? Because if we do locking it will get an issue and also dangerous, in a thread we should be able to use a new context no?

**Comment by emily33901** [comment]
If the variable is shared across threads you need to lock it. With regards to 'context' im not sure what context you're refering too.

**Comment by despiegk** [comment]
I suggest to close for now, will try to come up with other examples
