### ISSUE TITLE
Review project

### ISSUE THREAD

**Issue by Poulpy** [vlang/v#1503]
I don't know if this is the right to do that, but I want people to review my own [Game of Life](https://github.com/Poulpy/Conway-s-Game-of-Life/blob/master/game_of_life.v). I know there's already a game of life in V (though it's unreadable for me). Since V is a new language I'm not sure if I'm following its philosophy and using correctly its syntax.

*Is my project following V philosophy* ?
*Am I missing usefull syntax or methods* (ie for readability) ?
*What changes are to be made to V*, that is related to my code (array methods, 2D array initialization) ?

Aside from that, I've implemented (struct) array methods that I thought simple and mandatory :
uniq, contains, join, [inter](https://github.com/vlang/v/issues/955), - (array substraction).

Will these methods be in V later on ?

I apologize for the vague questions and thank you for listening to my request.

**Comment by Delta456** [comment]
I think its the wrong place to ask about this. You should better join [V Discord Server](https://discordapp.com/invite/n7c74HM) where every discussion about V takes place. I am sure people will be there for you to help.

**Comment by medvednikov** [comment]
Yes discord is the best place for this.
