### ISSUE TITLE
compile_error and comptime vars

### ISSUE THREAD

**Issue by russo-2025** [vlang/v#15030]
```v
module main

type Value = voidptr

pub fn create<T>(val T) Value {
	$if T is bool {
		return create_value_from_bool(val)
	}
	$else {
		$compile_error(T.name + ' type is not available for func ' + @MOD + '::' + @FN)

		// at the moment, only such a variant of writing is available
		// $compile_error('type is not available')

		panic("error")
	}
}

fn create_value_from_bool(val bool) Value {
	//...
	return Value(voidptr(0))
}

fn main() {
	val1 := create(true) //ok

	val2 := create(123) // error: int type is not available for func main::create
}
```

**Comment by russo-2025** [comment]
if of course it is possible to do it at all

**Comment by hungrybluedev** [comment]
Why not use a sum type to limit the supported types for the create function?

**Comment by russo-2025** [comment]
I'm sorry, I thought that `$if...$else` affects the `compile_error` call, but it's not. it is called anyway

**Comment by ken0x0a** [comment]
@russo-2025 
Is your issue disappear?

I was digging into this, and found out, we need to implement fn to handle `StringInterpolation` and add a field to `v.ast.ComptimeCall` as that's all info the checker have.
But I think it's not too difficult to add feature to handle string in comptime args.

**Comment by russo-2025** [comment]
fact is that "compile_error" is called in any case, regardless of the blocks "$if...$else..."

**Comment by ken0x0a** [comment]
Oh, that's true...
This must be a bug.

That code should compile...

**Comment by ken0x0a** [comment]
At least, that behavior is not intended I think.
