### ISSUE TITLE
Unable to assign attributes to a field with default value

### ISSUE THREAD

**Issue by Terisback** [vlang/v#15044]
**V version:** V 0.3.0 16a6972
**OS:** Arch WSL

**What did you do?**
```v
struct Config {
	root_url string = "http://localhost:8080" [env:"ROOT_URL"]
}
```

**What did you expect to see?**
*Successful compilation*

 
**What did you see instead?**
```sh
./app.v:4:48: error: unexpected token `:`, expecting `]`
    2 |
    3 | struct Config {
    4 |     root_url string = "http://localhost:8080" [env:"ROOT_URL"]
      |                                                   ^
    5 | }
    6 |
    ```

**Comment by spytheman** [comment]
The default value should be last, after the tag:
```v
struct Config {
        root_url string [env:"ROOT_URL"] = "http://localhost:8080"
}
```

The reason for that ordering, is that: 
`struct Abc { x string = y  [z] }` could be ambiguous with: `struct Abc { x string = y[z] }`, where `y` and `z` are consts.
