### ISSUE TITLE
cgen: passing sumtype parameter in sumtype matching results in error

### ISSUE THREAD

**Issue by lemoncmd** [vlang/v#15078]
**V version:** 0.3.0 bfcf5b1
**OS:** arch linux

**What did you do?**
```v
struct Foo{}
fn foo(a Foo|int) {}
fn bar() Foo|f32 {return Foo{}}
fn main() {
	a := bar()
	match a {
		Foo {
			foo(a)
		}
		f32 {}
	}
}
```

**What did you expect to see?**
`a` become `Foo` both in type system and cgen.
 
**What did you see instead?**
`a` is casted correctly to `Foo` in type system, but not in cgen. results in c error.

**Comment by yuyi98** [comment]
Anonymous sumtype will be discarded.

**Comment by lemoncmd** [comment]
No. This issue is not related to anonymous sum type and not fixed.
```
struct Foo{}
type Bar = Foo|int
type Baz = Foo|f32
fn foo(a Bar) {}
fn bar() Baz {return Foo{}}
fn main() {
	a := bar()
	match a {
		Foo {
			foo(a)
		}
		f32 {}
	}
}
```
