### ISSUE TITLE
Using `(int, int)` as field type leads to C error - field 'data' has incomplete type

### ISSUE THREAD

**Issue by Apocryphon-X** [vlang/v#15083]
**V doctor:**
```
OS: linux, Ubuntu 20.04.4 LTS (WSL 2)
Processor: 12 cpus, 64bit, little endian, 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
CC version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

getwd: /home/apocryphon
vmodules: /home/apocryphon/.vmodules
vroot: /home/apocryphon/packages/v
vexe: /home/apocryphon/packages/v/v
vexe mtime: 2022-07-16 17:17:17
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 47b5d20.8d24522

Git version: git version 2.25.1
Git vroot status: weekly.2022.28-18-g8d24522d (8 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 827f7452
```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg .\bug.v`
```v
struct Tuple{
	data (int, int)
}

fn main() {
	x := Tuple{}
	println(x)
}
```

**What did you expect to see?**
```sh
# Maybe something like this
Tuple{
	data: (0, 0)
}
```
I was trying to use tuples as field types (without having to declare another struct to do something similar) - I know this clashes with V's philosophy of having only one way to get things done, but since it is possible to have tuples as return values maybe this could be possible too.

-- In any case, this is a bug so here is the report --

**What did you see instead?**
```
==================
/tmp/v_1000/bug.1145645039064506182.tmp.c:1069: error: field 'data' has incomplete type
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang 
```

**Comment by Apocryphon-X** [comment]
The code above is a minimal example to reproduce the bug. But I got there trying to do something like this:

```v
import datatypes { Queue }

fn main() {
	example := Queue<(int, int)>{}

	example.push({1, 2})
	println(example)

	first, second := example.pop()?

	println(first)
	println(second)
}
```

**Comment by Delta456** [comment]
> > _(It feels like this is related to the bug above so I'm putting this comment here...)_
> 
> Additionally, I found that bug trying to do something like this with generics:
> 
> ```v
> import datatypes { Queue }
> 
> fn main() {
> 	example := Queue<(int, int)>{}
> 	// ... 
> 	first, second := example.pop()?
> 	// ...
> }
> ```
> 
> ```v
> /home/apocryphon/packages/v/vlib/datatypes/linked_list.v:27:9: error: expected 2 arguments, but got 1
>    25 | // first returns the first element of the linked list
>    26 | pub fn (list LinkedList<T>) first() ?T {
>    27 |     return if !list.is_empty() { list.head.data } else { error('Linked list is empty') }
>       |            ~~
>    28 | }
>    29 |
> /home/apocryphon/packages/v/vlib/datatypes/linked_list.v:39:15: error: expected 2 arguments, but got 1
>    37 |             node = node.next
>    38 |         }
>    39 |         return node.data
>       |                     ~~~~
>    40 |     }
>    41 | }
> /home/apocryphon/packages/v/vlib/datatypes/linked_list.v:55:16: error: expected 2 arguments, but got 1
>    53 |         }
>    54 |         if iterations == idx {
>    55 |             return node.data
>       |                         ~~~~
>    56 |         } else {
>    57 |             return error('Index out of bounds')
> ...
> ```

This issue is different from the OP post.

**Comment by Apocryphon-X** [comment]
> This issue is different from the OP post.
Oh, okay. I'll make another issue.
