### ISSUE TITLE
call windows api bug

### ISSUE THREAD

**Issue by lcddh** [vlang/v#15159]
```//fn C.GetCursorPos(point &Point) bool
fn C.WindowFromPoint(point Point) int



fn main() {
	mut p := Point{100,100}
	//C.GetCursorPos(&p)
	hwnd := C.WindowFromPoint(p)
	println(p)
	//println(hwnd)
}

pub struct Point {
	x int
	y int
}```

result :
C:/Users/Administrator/AppData/Local/Temp/v_0/code.5870116502383723988.tmp.c:12209: error: cannot convert 'struct main__Point' to 'struct tagPOINT'

**Comment by bstnbuck** [comment]
Hi @lcddh, 
your code is not correct. `POINT` is a `typedef struct` and must be named as such in `V`. In addition, you need the corresponding `C.` for C calls. The function normally returns a handle `C.HWND`, but for test purposes an int works as well :)

This code works as expected:
```v
fn C.WindowFromPoint(C.POINT) int

[typedef]
pub struct C.POINT {
	x i64
	y i64
}

fn main() {
	mut p := C.POINT{100,100}
	hwnd := C.WindowFromPoint(p)
	println("Point: ${p}")
	println("Handle: ${hwnd}")
}
```
Output:
```
Point: POINT{
    x: 100
    y: 100
}
Handle: 263922
```

**Comment by lcddh** [comment]
Why can't I just define the structure of V struct
```
struct Point {
	x int
	y int
}
```

**Comment by JalonSolov** [comment]
Because it's coming from C, and C structs are different from V structs.

You could define the V struct, and transfer the data between the fields after you get it back, but you can't use it as a V struct directly.

**Comment by JalonSolov** [comment]
Look at @bstnbuck comment.  That's the way you need to do this for it to work.
