### ISSUE TITLE
Allow maps to have an array as value

### ISSUE THREAD

**Issue by mvlootman** [vlang/v#1516]
Allow maps to store an array as value.

e.g. to an array of ints or struct
```
m := map[string][]int{} 
ms := map[string][]MyStruct{}
```

currently this gives a compile error:
check()
next token = `]`
pass=2 fn=`main`
test.v:4 expected `.name` but got `[` compile error:

**Comment by medvednikov** [comment]
Yes, this is a frequently requested feature. Will do this asap.

**Comment by dcurrie** [comment]
Sure, but all these special cases slow down getting to the real answer... Finish generics, and make maps generic on key and value!

**Comment by medvednikov** [comment]
Fixed.

@dcurrie maps, just like V arrays, Go slices, and Go maps, will be implemented without generics to save space.
