### ISSUE TITLE
free memory access

### ISSUE THREAD

**Issue by BlackEspresso** [vlang/v#152]
can read and write to programm memory even with disabled pointer derefernce. just by reassigning a mutable pointer. `mut p := &Point{}`

```
struct Point {
	x u8
}

fn main() {
	p1 := &Point{x: 0}
	mut p2 := &Point{}
	println(p1)
	for i := 0; i < 50; i++ {
		p2 = p1 + i
		if i == 5 {
			p2.x = u8(11)
		}
		println(p2.x)
	}
}

```

**Comment by ntrel** [comment]
> p2 = p1 + i

I think V should be memory safe by default, but allow unsafe operations like pointer arithmetic inside `unsafe` blocks like Rust.

**Comment by medvednikov** [comment]
Yes, pointer arithmetic is allowed, it's used a couple of times in vlib. `unsafe` blocks will be added.

**Comment by medvednikov** [comment]
I've just disabled pointer arithmetic in the playground for security reasons.
