### ISSUE TITLE
c error while there is a `or` on the return line 

### ISSUE THREAD

**Issue by vincenzopalazzo** [vlang/v#15219]
While working on https://github.com/vlang/v/issues/15197 I found another wired bug while I run the following code

```v
gitpod /workspace/v (macros/io.read) $ cat test.v 
fn unwrap_int() ?int {
	return 1
}

fn unwrap_function() !int {
	return unwrap_int() or {error("we are issing the return?")}
}

fn main() {
	x := unwrap_int() or {panic(err)}
	println(x)
}
```

**Comment by JalonSolov** [comment]
Shouldn't
```v
fn unwrap_function() !int {
	return unwrap_int() or {error("we are issing the return?")}
}
```
be this, instead?
```v
fn unwrap_function() !int {
	return unwrap_int() or {none}
}
```

**Comment by vincenzopalazzo** [comment]
mh! 

I think the return type is a result, so or a value (int) or a error, so I make the compiler happy by using the `or {return error("...")}`

**Comment by JalonSolov** [comment]
Well... `?int` is optional return, meaning valid value or error.  `!int` means result return, meaning value value or `none`.  You have `!int` as the return type.

**Comment by StunxFS** [comment]
`?int`: value of type `int` or `none`
`!int`: value of type `int` or error

**Comment by vincenzopalazzo** [comment]
>Well... ?int is optional return, meaning valid value or error. !int means result return, meaning value value or none. You have !int as the return type.

I do not know, I just follow the RFC and he said the opposite for `?int`

**Comment by medvednikov** [comment]
@JalonSolov after the split `none` can only be used with `?Foo`, `error` with `!Foo`.

**Comment by medvednikov** [comment]
But the old code using `none` with `?Foo` will keep working for 2 years.

**Comment by JalonSolov** [comment]
Sorry - had it backwards.  Too much confusion with which punctuation to use when...  :-\
