### ISSUE TITLE
pass fn with error in fn arg error

### ISSUE THREAD

**Issue by StringNick** [vlang/v#15248]
**V version:** 
**OS:** 

**What did you do?**
https://devbits.app/play/7GkzwXRFhnFZ

**What did you expect to see?**
no error
 
**What did you see instead?**
error

**Comment by yuyi98** [comment]
Whether can provide source code in this post? I can't access the link provided here.

**Comment by StringNick** [comment]
> Whether can provide source code in this post? I can't access the link provided here.

```
module main

fn test(f fn()?)? {
    return error('test')
}

fn test1()? {
    return error('test1')
}

fn main() {
    test(test1)
}
```
