### ISSUE TITLE
select chan to _ error

### ISSUE THREAD

**Issue by StringNick** [vlang/v#15268]
**V version:** 
**OS:** 

**What did you do?**
https://devbits.app/play/bYZPuLU5abFe
```module main

import context

fn main() {
    mut ctx := context.todo()
    select {
        _ := <- ctx.done() {}
        else {
        }
    }
}```

**What did you expect to see?**
no error
 
**What did you see instead?**
error

**Comment by emily33901** [comment]
> **V version:** **OS:**
> 
> **What did you do?** https://devbits.app/play/bYZPuLU5abFe
> 
> ```v
> module main
> 
> import context
> 
> fn main() {
>     mut ctx := context.todo()
>     select {
>         _ := <- ctx.done() {}
>         else {
>         }
>     }
> }
> ```
> 
> **What did you expect to see?**
> no error
>  
> **What did you see instead?**
> error
> 

the error being 

```
main.v:9:21: error: channel in `select` key must be predefined
    7 |     done := ctx.done()
    8 |     select {
    9 |         _ := <- ctx.done() {}
      |                     ~~~~~~
   10 |         else {
   11 |         }
```

which suggests to pre-define ctx.done(), which im personally puzzled by but

```v
module main

import context

fn main() {
    mut ctx := context.todo()
    done := ctx.done()
    select {
        _ := <- done {}
        else {
        }
    }
}
```

fixes this

**Comment by einar-hjortdal** [comment]
Ran into this today and I also am confused by this
