### ISSUE TITLE
sum types and autocast

### ISSUE THREAD

**Issue by russo-2025** [vlang/v#15272]
**V version:** V 0.3.0 1be5956
**OS:**  windows, Microsoft Windows 10 Pro v19042 64-bit

**What did you do?**
```v
module main

type Stmt = StmtSt1 | StmtSt2

struct StmtSt1 {
	num int
}

struct StmtSt2 {
	str string
}

struct MyStruct {
mut:
	stmt Stmt
}

fn main() {
	mut st := MyStruct{ stmt: StmtSt1{} }

	match st.stmt {
		StmtSt1 {}
		StmtSt2 { println(st.stmt.str) } // <-- error: field `str` does not exist or have the same type in all sumtype variants
	}
}
```

**What did you expect to see?**

**What did you see instead?**
error

**Comment by JalonSolov** [comment]
Why would you expect that to work?  First, the error message is correct - `str` doesn't exist in both structs.  2nd, you can't initialize with `println` because `println` doesn't return anything at all.

**Comment by russo-2025** [comment]
I don't understand why it shouldn't work
I expected this result:
```v
	match st.stmt {
		StmtSt1 {}
		StmtSt2 { println((st.stmt as StmtSt2).str) }
	}
```

**Comment by russo-2025** [comment]
I hope this example looks better
```v
module main

type Value = Value1 | Value2

struct Value1 {
mut:
	val Value
}

struct Value2 {
	str string
}

struct MyStruct {
mut:
	st_val Value
}

fn foo(mut stmt &Value) {}

fn main() {
	mut st := MyStruct{ st_val: Value1{ val: Value2{} } }

	foo(mut &(st.st_val as Value1).val) //<--- unexpected expression `v.ast.AsCast`
}
```

**Comment by vincenzopalazzo** [comment]
In according with our docs https://github.com/vlang/v/blob/master/doc/docs.md#sum-types this should work, but not sure if we should work also with this internal cast, but a work around can be

```v
module main

type Stmt = StmtSt1 | StmtSt2

struct StmtSt1 {
	num int
}

struct StmtSt2 {
	str string
}

struct MyStruct {
mut:
	stmt Stmt
}

fn main() {
	mut st := MyStruct{ stmt: StmtSt1{} }
	stmt := st.stmt
	match stmt {
		StmtSt1 {}
		StmtSt2 { println(stmt.str) } // <-- error: field `str` does not exist or have the same type in all sumtype variants
	}
}
```

**Comment by vincenzopalazzo** [comment]
Marked as discussion, we can see what the other think too

**Comment by yuyi98** [comment]
If we want to use smartcast, we must use `match mut st.stmt {` because st is mut.

```v
module main

type Stmt = StmtSt1 | StmtSt2

struct StmtSt1 {
	num int
}

struct StmtSt2 {
	str string
}

struct MyStruct {
mut:
	stmt Stmt
}

fn main() {
	mut st := MyStruct{ stmt: StmtSt1{} }

	match mut st.stmt {
		StmtSt1 {}
		StmtSt2 { println(st.stmt.str) }
	}
}
```

**Comment by JalonSolov** [comment]
Someone please explain to me why this line makes _any_ sense?
```v
		StmtSt2 { println(st.stmt.str) }
```
Since `println` doesn't return anything, so how could it be used to initialize a StmtSt2 struct?

**Comment by vincenzopalazzo** [comment]
>If we want to use smartcast, we must use match mut st.stmt { because st is mut.

Maybe we can generate a suggestion at compile time?

>Since println doesn't return anything, so how could it be used to initialize a StmtSt2 struct?

Mh, I think it is not creating the `StmtSt2` but matching on type?

**Comment by russo-2025** [comment]
I have found a solution to this problem.
probably it's worth adding a understandable error message here.

```v
if st.stmt is StmtSt2  { println(st.stmt.str) } // random error
if mut st.stmt is StmtSt2  { println(st.stmt.str) } //ok


match st.stmt {
	StmtSt1 {}
	StmtSt2 { println(st.stmt.str) } // random error
}
match mut st.stmt {
	StmtSt1 {}
	StmtSt2 { println(st.stmt.str) } //ok
}
```

**Comment by JalonSolov** [comment]
> > Since println doesn't return anything, so how could it be used to initialize a StmtSt2 struct?
> 
> Mh, I think it is not creating the `StmtSt2` but matching on type?

V should still be throwing an error for this, regardless of what is matching (or not).

**Comment by felipensp** [comment]
This issue seems already fixed. Can you confirm @russo-2025 ? @JalonSolov ?

**Comment by medvednikov** [comment]
Yes:
> `c.v:23:29: error: field `str` does not exist or have the same type in these sumtype `Stmt` variants: StmtSt1`
