### ISSUE TITLE
V don't build correctly on Cygwin

### ISSUE THREAD

**Issue by Et7f3** [vlang/v#1528]
**V version:** none (but try to get the latest)
**OS:** Windows 10 64 bits , Cygwin 32 bits

**What did you do?**
copy paste the readme

**What did you expect to see?**
V build succefully :)
 
**What did you see instead?**
I had to build by hand. It have the same bug for vid.

**log:**
````
$ git clone https://github.com/vlang/v
Clonage dans 'v'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 5545 (delta 20), reused 22 (delta 9), pack-reused 5503
Réception d'objets: 100% (5545/5545), 2.81 MiB | 4.13 MiB/s, fait.
Résolution des deltas: 100% (3566/3566), fait.
Extraction des fichiers: 100% (279/279), fait.
$ cd v
$ make
curl -o v.0.1.17.c -Ls https://github.com/vlang/vc/raw/0.1.17/v.c
cc -std=gnu11 -w -o v.c.out v.0.1.17.c -lm
./v.c.out -o v compiler
cc: warning: « -x objective-c » n'a pas d'effet après le dernier fichier d'entrée
cc: error: option « -mmacosx-version-min=10.7 » non reconnue sur la ligne de commande
V panic: clang error
make: *** [Makefile:10: v] Error 1
$ ls
azure-pipelines.yml  CHANGELOG.md  compiler  CONDUCT.md  CONTRIBUTING.md  Dockerfile  examples  LICENSE  make.bat  make_tests.bat  Makefile  README.md  test.sh  thirdparty  tools  v.0.1.17.c  v.c.out  vlib
$ ./v.c.out -show_c_cmd -o v compiler

==========
cc  -w -g -o v ".v.c" -mmacosx-version-min=10.7   -x objective-c
cc took 176 ms
=========

cc: warning: « -x objective-c » n'a pas d'effet après le dernier fichier d'entrée
cc: error: option « -mmacosx-version-min=10.7 » non reconnue sur la ligne de commande
V panic: clang error
$ cc  -w -g -o v ".v.c"
$ ls
azure-pipelines.yml  compiler    CONTRIBUTING.md  examples  make.bat        Makefile   test.sh     tools       v.c.out  vlib
CHANGELOG.md         CONDUCT.md  Dockerfile       LICENSE   make_tests.bat  README.md  thirdparty  v.0.1.17.c  v.exe
```

EDIT:
It seem a bug in os detection
https://github.com/vlang/v/blob/master/compiler/main.v#L840

**Comment by vitalyster** [comment]
V is fully native Windows application which you can build with msvc or gcc(mingw), no need in Cygwin

**Comment by Et7f3** [comment]
Found this https://github.com/vlang/vc/blob/master/v.c#L6789 V assume by default it is on macos.

**Comment by BokuNoCode** [comment]
Cygwin 32 bits? have you tried the 64bit one?

**Comment by MaD70** [comment]
@Et7f3: I see [no mention of Cygwin on V site](https://www.google.com/search?q=Cygwin+site%3Avlang.io), so this is hardly surprising: no one is bothering to test a build with Cygwin.

I reiterate what @vitalyster is saying in guise of a question: why do you want to build with the overhead of a POSIX API emulation layer (Cygwin) when V builds natively (MinGW-w64 or MS Visual C)? What are you trying to achieve?

**Comment by medvednikov** [comment]
There's no point in supporting Cygwin, when Windows and WSL are supported.

**Comment by Et7f3** [comment]
Ok it work well with native toolchain you have linked 👍 . Thanks. I was using cygwin because it has already all tools installed.
