### ISSUE TITLE
Single quote for strings?

### ISSUE THREAD

**Issue by 0x9ef** [vlang/v#153]
Why you use single quote for strings but no standart quote "" for strings? In my opinion single quotes should be use for signel unicode charset, but not for multi characters strings. Its looks like PHP :d

**Comment by medvednikov** [comment]
Python as well.

This decision is not final.

In my opinion they look cleaner and don't require shift on most keyboards.

**Comment by zac-garby** [comment]
I think it's useful to have both variants, because I much prefer using double quotes, but I know that a lot of people prefer using single quotes. Also, I mentioned before that it removes some cases where escape sequences would be necessary otherwise.

**Comment by medvednikov** [comment]
Double quotes will be allowed, but converted to single quotes by vfmt for consistency. Unless the string contains `'`.

**Comment by zac-garby** [comment]
I like that idea.

**Comment by whoizit** [comment]
I love single quoted strings. There must be a good reason why strings should be double quoted.

**Comment by PavelVozenilek** [comment]
Certain kind of applications (e.g. webpage generators) would benefit from "natural form of strings" (there are many names for that):

```
s : string = [[[
Whatever is here
is one string which doesn't require noise 
in form of quotes, explicit newlines, string concatenation, etc.
]]]
```


The next step could be string interpolation, feature whose alternatives are clumsy or unusable (as C++ streams):

```
x := 111
y := 222
s : string = [[[
x = $(x), y = $(y)
]]]
```

**Comment by structure-charger** [comment]
There may only one option, which quote style is faster in compile time ,which wins.

**Comment by ntrel** [comment]
One good reason for double quoted strings (besides not escaping apostrophes) is that editor lexer code for C can be reused for V just with a different list of keywords. E.g. cross platform scintilla.org full featured editing component has a configurable C lexer where you can set the keyword list and other things like whether to support raw strings (for recent C++). Geany, notepad++ and many other editors use scintilla.

**Comment by mingodad** [comment]
Also why not allow optional semi colon ?
It would allow share code between languages (C/C++/Java).
Cheers !

**Comment by structure-charger** [comment]
I main which symbol can be handled faster in compile time, which will be prefered.
for example  symbol  ‘  in ascii is  0010 0111  and symbol  "  is  0010 0010 , so in compile time ' is bigger than " in final binary file.
so use more " than ' can be faster in compile time and we may should choose " .
That's my personal opinion. If you think there is any fault in my opinion or you have better solution, please tell me , Thanks a lot.







At 2019-06-23 21:51:40, "Domingo Alvarez Duarte" <notifications@github.com> wrote:


Also why not allow optional semi colon ?
It would allow share code between languages (C/C++/Java).
Cheers !

**Comment by LouCle** [comment]
@structure-changer They take up exactly the same size. They're both a byte
