### ISSUE TITLE
assert: allow for an extra message

### ISSUE THREAD

**Issue by ylluminate** [vlang/v#15315]
As per [Discord message](https://discord.com/channels/592103645835821068/592115457029308427/1003612824171454464) from @elliotchance:
> It would be great if `assert` allowed for an extra message like:
> ```
> assert obj_data == blob_read, 'position = $blob_position'
> ```
> If you're using `assert` in a loop its very hard to debug when it fails if the values themselves don't give enough information about the iteration that fails.

**Comment by elliotchance** [comment]
For example:

```v
i := 123
assert i == 456, 'i = $i'
```

A colon + message appended to the assert line?

```txt
   > assert i == 456: i = 123
     Left value: 123
    Right value: 456
```

**Comment by StunxFS** [comment]
Or a separate line?

```
   > assert i == 456
     Left value: 123
    Right value: 456
    Message: i = 123
```

**Comment by elliotchance** [comment]
Actually I vote for what @StunxFS said. Having it on a separate line will be easier to read when the assert and message is longer.

**Comment by penguindark** [comment]
I've implemented one that I had heavily used during the development here:
https://github.com/vlang/v/blob/42efc383d272ff1f49fdf85f6ff498b69f721e12/vlib/strconv/utilities.v#L8-L14
have it as standard assert should be a good thing

**Comment by spytheman** [comment]
Working draft (only for asserts in normal V programs, not in tests for now):
![image](https://user-images.githubusercontent.com/26967/182346858-ea735066-bedb-4601-bb6f-7ea3a672be00.png)

**Comment by spytheman** [comment]
```v
fn mymessage(i int) string {
	return 'i was: $i'
}

i := 123
assert i == 456, mymessage(i)
```
... also works:
```
#0 12:56:59 ᛋ master /v/vnew❱v -g run aa.v 
aa.v:6: FAIL: fn main.main: assert i == 456, mymessage(i)
   left value: i = 123
  right value: 456
      message: i was: 123
V panic: Assertion failed...
v hash: 857e047
/tmp/v_1000/../../../../../../v/vnew/vlib/builtin/builtin.c.v:104: at _v_panic: Backtrace
/tmp/v_1000/../../../../../../v/vnew/aa.v:6: by main__main
/tmp/v_1000/../../../../../../tmp/v_1000/aa.5554113071173068293.tmp.c:17328: by main
#1 12:57:03 ᛋ master /v/vnew❱
```

**Comment by spytheman** [comment]
Assertions with extra messages in _test.v files also work:
![image](https://user-images.githubusercontent.com/26967/182349215-96e71c03-96c1-4bdf-b854-191a1625609d.png)

I'll make a PR soon.

**Comment by penguindark** [comment]
Great! 💯

**Comment by elliotchance** [comment]
nit: Can you make sure the colons are lined up to the same column for the left, right and message? Like:

```
   Left value: i = 123
  Right value: 456
      Message: i was: 123
```

**Comment by spytheman** [comment]
> nit: Can you make sure the colons are lined up to the same column for the left, right and message? Like:
> 
> ```
>    Left value: i = 123
>   Right value: 456
>       Message: i was: 123
> ```

yep, it is aligned in the PR
