### ISSUE TITLE
net_dial: socket error 56

### ISSUE THREAD

**Issue by StringNick** [vlang/v#15336]
**V version:** 
**OS:** macos

**What did you do?**
i just do multiple dial_tcp, most of dial_tcp, got socket error: 56, if i start with  -d net_blocking_sockets everything work or comment this line https://github.com/vlang/v/blob/master/vlib/net/tcp.v#L349

**What did you expect to see?**
no error on dial_tcp
 
**What did you see instead?**
error Socket is already connected

**Comment by medvednikov** [comment]
You need to post the code to reproduce this.

**Comment by StringNick** [comment]
socket error is because FD_ISSET show false https://github.com/vlang/v/blob/master/vlib/net/common.v#L65
and then we connecting again with same fd, that connected https://github.com/vlang/v/blob/master/vlib/net/tcp.v#L457, that is why we got socket error: 56.
Do we need fd_isset, if we call getsockopt after select?
