### ISSUE TITLE
Is there any inconsistency between the assignment when calling a method to pass parameters and assigning to other variables?

### ISSUE THREAD

**Issue by Silentdoer** [vlang/v#15368]
When I assign foo to foo1, it will copy the value of foo to foo1，for example:
```v
mut foo := Foo{3}
mut foo1 := foo
//foo and foo1 do not point to the same memory
```

But if Foo implements the speak method in the form of mut, then foo1 points to the same memory as foo
```v
// By the way, does this mut make sense in this interface?
interface Speaker {
mut:
	speak()
}

fn (mut foo1 Foo) speak() {
	strconv.v_printf('interface:%p\n', foo1)
	foo1.a = 9
}

mut foo := Foo{3}
foo.speak()
```

But if the speak method is not implemented in the form of mut, then foo and foo1 do not point to the same memory, which feels very inconsistent
```v
fn (foo1 Foo) speak() {
	strconv.v_printf('interface:%p\n', foo1)
}

mut foo := Foo{3}
foo.speak()
```

**Comment by ken0x0a** [comment]
Can you edit to follow issue template?

I tried but works correctly (copied at `mut foo1 := foo`).

**Comment by Silentdoer** [comment]
> Can you edit to follow issue template?
> 
> I tried but works correctly (copied at `mut foo1 := foo`).

yes, copied at `mut foo1 := foo`, but not at foo.speak()

**Comment by ken0x0a** [comment]
I want to understand what exactly you mean, so plz fill the BUG ISSUE TEMPLATE, with the full code you used.

**Comment by ken0x0a** [comment]
What I guess is, your answer will be there, when you try to compile `fn (mut foo1 &Foo) speak() {`.

**Comment by ken0x0a** [comment]
I'm closing this as it works properly.

I might not understand you correctly.
In that case, plz fill BUG TEMPLATE and reopen.

**Comment by Silentdoer** [comment]
> ```v
> mut foo := Foo{3}
> mut foo1 := foo
> ```
please see Question 1 and Question 2
```v
import strconv

interface Speaker {
// Question 1: By the way, does this mut have any use for the speak method? 
// Because regardless of whether there is mut in the interface definition, the parameters that implement speak can have mut
mut:
	speak()
}

struct Foo {
mut:
	a int
}

fn (mut foo2 Foo) speak() {
	strconv.v_printf('interface:%p\n', foo2)
	foo2.a = 9
}

fn main() {
	mut foo := Foo{3}
	// printed 0x14efe5c
	strconv.v_printf('%p\n', foo)
	
	mut foo1 := foo
	// FLAG printed 0x14efe1c, foo and foo1 point to different address spaces, So foo copies a copy of the data to foo1
	strconv.v_printf('%p\n', foo1)
	
	// Question 2: printed interface:0x14efe5c, foo and foo2 point to the same memory space
	//, So why doesn't foo make a copy of the data here as well as above? Is this inconsistent?
	foo.speak()
}
```

**Comment by Silentdoer** [comment]
please see this:https://github.com/vlang/v/issues/15419
