### ISSUE TITLE
if expression prints out IF EXPR

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#1536]
**V version:**  0.1.17
**OS:**  Windows and Linux

**What did you do?**
Execute docs snippet

num := 777
s := if num % 2 == 0 {
	'even'
}
else {
	'odd'
}
println(s)

**What did you expect to see?**
odd

 
**What did you see instead?**
odd
IF EXPR

**Comment by thisisshub** [comment]
The syntax is correct `v file.v && ./file` or just `v run file.v`

**Comment by mvlootman** [comment]
Can confirm the same result on Mac Mojave. I think it was a commit today or yesterday.

**Comment by Ivo-Balbaert** [comment]
The IF EXPR is only printed during compilation.

**Comment by medvednikov** [comment]
Fixed.
