### ISSUE TITLE
shared array: array.last() produces C error

### ISSUE THREAD

**Issue by WoodyAtHome** [vlang/v#15363]
OS: linux, Ubuntu 20.04.4 LTS
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
CC version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

getwd: /home/woody
vmodules: /home/woody/.vmodules
vroot: /home/woody/sources/v/v
vexe: /home/woody/sources/v/v/v
vexe mtime: 2022-08-06 08:41:02
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 372857c.4588bb4

Git version: git version 2.25.1
Git vroot status: weekly.2022.31-20-g4588bb44
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 827f7452

```
module main

fn main() {
	shared a := []int{}
	lock  {
		a << 1
		a << 2
	}
	rlock a {
		println(a.last())
	}
}

```

**What did you expect to see?**
No C error
 
**What did you see instead?**
```
woody@lappi:~/sources/v/bugs$ v shared_last.v
==================
/tmp/v_1000/shared_last.12850093158604570159.tmp.c:17031: error: cannot convert 'struct array *' to 'struct array'
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by medvednikov** [comment]
This has been picked up by Nikolai.
