### ISSUE TITLE
Definition of a type does not work in Windows

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#1537]
**V version:** 0.1.17
**OS:**  10

**What did you do?**
Execute following snippet:

import strings

type TZ int

fn main() {
  println(5)
}

**What did you expect to see?**

 5

as it does on Linux / Playground

**What did you see instead?**

The syntax of the command is incorrect.

**Comment by thisisshub** [comment]
I ran `v run file.v ` containing the snippet and the output was 5

**Comment by Ivo-Balbaert** [comment]
By chance I discovered that the reason for this error: "The syntax of the command is incorrect" was the filename type.v . If this is changed to type_keyword.v, the program executes correctly! I had the same behaviour with a file if.v, which gave the same error, and when renamed worked correctly. This happens only on Windows, on Linux type.v and if.v work correctly. So I close this issue, noting that somehow on Windows a filename may not be a V keyword!
