### ISSUE TITLE
Enum docs example does not compile on Windows

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#1538]
**V version:**  0.1.17
**OS:**  10

**What did you do?**

Tried to compile:  v enums.v

enum Color {
	red green blue 
} 

mut color := Color.red
// V knows that `color` is a `Color`. No need to use `Color.green` here.
color = .green 
println(color)

**What did you expect to see?**

an enums.exe, which at execution prints 1 as on Linux and Playground
 
**What did you see instead?**

There is no compilation output (no enums.exe)

**Comment by thisisshub** [comment]
did you try `v run enums.v`

**Comment by ArcDrake** [comment]
> D:\vproj>v run main.v
> main.v:8 `Color` needs to have method `str() string` to be printable
> 
> D:\vproj>v run main.v
> 1

Can't confirm #1536 and #1537 neither, sorry. For me they work without changes.
Win 10 (1903)

I would try to 

clone again,
cd v
make.bat
v -o v1 compiler
copy v1.exe v.exe

**Comment by Ivo-Balbaert** [comment]
Thanks! After trying what you suggested, I got the error:
enums.v:17 `Color` needs to have method `str() string` to be printable
Which str() method did you use to get the output 1?
What is the effect of these 2 lines:
    v -o v1 compiler
    copy v1.exe v.exe

**Comment by ArcDrake** [comment]
You're welcome :)
I changed your last line of code: println(color) to println(color.str())

v -o v1 compiler <-- that's the bootstrapping process I think (https://en.wikipedia.org/wiki/Bootstrapping_(compilers)) it compiles the C Code (v.c) generated by GCC in make.bat to V Code.
At least that's how I unterstood it.

copy v1.exe v.exe just replaces the file with the bootstrapped v.exe

**Comment by Ivo-Balbaert** [comment]
Thanks again!
