### ISSUE TITLE
no compatible binaries for windows

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [vlang/v#15401]
so i have to compile on my own to run this on windows?
why not the release for windows works on windows?

also when compiling on my own it seems to work but does not....

`
Building V...
 > Attempting to build v_win.c with GCC
 > Compiling .\v.exe with itself
> C compiler cmd: "gcc" "@C:\Users\servidor\AppData\Local\Temp\v_0\v2.exe.tmp.c.rsp"
> C compiler response file "C:\Users\servidor\AppData\Local\Temp\v_0\v2.exe.tmp.c.rsp":
  -std=c99 -D_DEFAULT_SOURCE -g -no-pie -o "G:\\Sources\\v-master\\v2.exe" -Wl,-stack=16777216 -Werror=implicit-function
-declaration -I "G:\\Sources\\v-master\\thirdparty\\stdatomic\\win" "C:\\Users\\servidor\\AppData\\Local\\Temp\\v_0\\v2.
exe.tmp.c" -municode -ldbghelp -ladvapi32 -lshell32
        1 arquivo(s) movido(s).
builder error: Your V installation may be out-of-date. Try removing `thirdparty\tcc\` and running `.\make.bat`
 > V built successfully
 > To add V to your PATH, run `.\v.exe symlink`.
V version: V 0.3.0 1c6366e
G:\Sources\v-master>v
cannot compile `G:\Sources\v-master\cmd\tools\vrepl.v`:
builder error: Your V installation may be out-of-date. Try removing `thirdparty\tcc\` and running `.\make.bat``

**Comment by MyTDT-Mysoft** [comment]
oh trying to compile using tcc instead of gcc causes v.exe to crash

![image](https://user-images.githubusercontent.com/16870416/183964695-86c571f2-29d9-499e-8c21-c6e962353d62.png)

**Comment by medvednikov** [comment]
https://github.com/vlang/v/releases/latest/download/v_windows.zip

**Comment by JalonSolov** [comment]
The world moves on.  Even Microsoft has completely dropped 32-bit support in Windows 11.  Windows 8.1 is the oldest version that Microsoft is supporting with 32-bit, and that ends next year.  Windows 10 supports 32-bit, and support for that ends 2 years later.

That does not mean that V couldn't support 32-bit, it is just not the focus.  It would require someone with a 32-bit version of Windows interested in maintaining that support.

**Comment by medvednikov** [comment]
32 bit only processors are what, 13 years old? Windows is hard to support as it is, we don't have the resources to support 13 year old CPUs on Windows too.

**Comment by MyTDT-Mysoft** [comment]
typical blind view of "linux" people... even 64bit windows support 32bit EVEN on windows 11... so unlike linux where it requires to install half of OS as for 32bit... on windows that shouldnt be the case...
also isnt about being newer or older... is about being goood or bad or usable... at my understanding the language was like that because it wanted to do things right... and DISCRIMINATING over a very capable 32bit that runs EVEN on newest windows 11... IS NOT THE RIGHT THING.

and even if the world was moving one to allow rape... i wouldnt do it... so whatever the world is doing is irrelevant... specially if they are ignorant and only see what marketing poses... not the actual matters, so they dont care... they dont see.. mostly they dont have a choice... because people keep them blind so they wont have a choice... we've been poisioning people with food that way for decades... so... all thise arguments are irrelevant...

but thanks anyway, since the language is just yet another OOP based junk (and worse that try to fool themselves into think otherwise) ... it would be typical that they wouldnt care to anything that matter anyway... 

i will just rip off the support you guys have for android... and make it better than you guys (less dependencies) and then it will be automatically million times better because it will be real.
since at the end i wont have any android functions at all, just yet another OOP gui library.

**Comment by ylluminate** [comment]
@MyTDT-Mysoft please do feel free to contribute to, work on and make PRs for solid 32-bit support. I'd like to see it work across all platforms as well for various reasons, but most of us lack the time to invest in it presently. Definitely no discrimination going on here, just prioritization based on present trends and demands. 😿

**Comment by MyTDT-Mysoft** [comment]
> @MyTDT-Mysoft please do feel free to contribute to, work on and make PRs for solid 32-bit support. I'd like to see it (32-bit) work across all platforms as well for various reasons, but most of us lack the time to invest in it presently. Definitely no discrimination going on here, just prioritization based on present trends and demands. crying_cat_face
> 
> It definitely appears you have some misperceptions going on here, but yeah, if you want it and you feel like you want to invest your time in V - that's wonderful.

well... sure, but i would like to start knowing how i should debug this problem on 32bit because i found nothing wrong (when compiling with GCC... i'm using gcc version 8.1.0 (i686-win32-dwarf-rev0, Built by MinGW-W64 project))

but i know that the make.bat on windows lacks several verifications (like it crashes if it fails to download some of the auto-downloaded components (didnt checked which))
but i tried more than one time... so without any weird messages other than the

"builder error: Your V installation may be out-of-date. Try removing thirdparty\tcc\ and running .\make.bat
V built successfully"
(error or success? :P)

but i know that at some point some part of the toolchain try to change the console into utf-8 and that simple wont work on windows 7... (causes all kinds of bugs), so whatever is trying to change the console into utf-8 shouldnt do it forcefully... like for example on side effect after running "v" is that if i do a "DIR" cmd.exe closes and that happens if i set the console to utf-8 (as that is half backed on win7, so leaving it as the default-code page would probabily be for the best)

if i get used to V, i can even maintain it for windows (all versions / 32bit), but its windows... not linux... and so it shouldnt be expected to behave the same (or forced to use something different just to have an utf-8 console)

but first i need to be able to try it at all hehe

**Comment by JalonSolov** [comment]
The first thing to do is update to a recent version of gcc from https://winlibs.com - get right of the mingw version.
