### ISSUE TITLE
Running as stated in the examples (Call V from Python): v -shared -prod test.v

### ISSUE THREAD

**Issue by hermanslagman** [vlang/v#15424]
**V doctor:**
```
OS: windows, Microsoft Windows 11 Pro v22000 64-bit
Processor: 16 cpus, 64bit, little endian, Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz  

CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.

 cmd: cc --version

getwd: C:\Users\hslag\v\examples\call_v_from_python
vmodules: C:\Users\hslag\.vmodules
vroot: C:\Users\hslag\v
vexe: C:\Users\hslag\v\v.exe
vexe mtime: 2022-08-14 15:44:45
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 9e0bf00.90d9b20

Git version: git version 2.37.1.windows.1
Git vroot status: weekly.2022.32-33-g90d9b200
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 125e21e2

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg test.v`
```v
module test

import math

[export: 'square']
fn square(i int) int {
	return i * i
}

[export: 'sqrt_of_sum_of_squares']
fn sqrt_of_sum_of_squares(x f64, y f64) f64 {
	return math.sqrt(x * x + y * y)
}

```

**What did you expect to see?**

test.v compiled into test.dll

**What did you see instead?**
```
test.v:1:1: error: project must include a `main` module or be a shared library (compile with `v -shared`)
    1 | module test
      | ^
    2 | 
    3 | import math
```
Compiler output:
```
gcc: error: unrecognized command line option '-municode'
```

**Comment by JalonSolov** [comment]
I recommend updating to a recent version of gcc from https://winlibs.com - you likely have the ancient version from the main mingw release.

**Comment by hermanslagman** [comment]
It only gets worse:
PS C:\Users\hslag\v\examples\call_v_from_python> v -shared -prod test.v
==================
                 from C:\Users\hslag\AppData\Local\Temp\v_0\test.4853297428016765196.tmp.so.c:100:
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:35:18: error: expected ';' before 'typedef'
   35 | __MINGW_EXTENSION typedef unsigned __int64 size_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:45:18: error: expected ';' before 'typedef'
   45 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:62:18: error: expected ';' before 'typedef'
   62 | __MINGW_EXTENSION typedef __int64 intptr_t;
      |                  ^~~~~~~~
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

gcc version 12.1.0 (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders)

**Comment by JalonSolov** [comment]
Did you uninstall the mingw version?  Looks like it might be mixing/matching the new with the old.

**Comment by hermanslagman** [comment]
Don't bother, I was just trying to evaluate V, I'm not interested in installing GCC cygwin or other C related stuff.
If it is so complicated (at least for me) I don't have the time or the inclination to bother, shame because V looks interesting
