### ISSUE TITLE
V Panic on open bracket without newline

### ISSUE THREAD

**Issue by Henrixounez** [vlang/v#1542]
**V version:** 0.1.17

**What did you do?**
```
if (1 == 1) {
```

**What did you expect to see?**
```
check()
next token = `.eof`
test.v:2 expected `}` but got `.eof`
```
 
**What did you see instead?**
```
V panic: string index out of range: 13 / 13
```

**Comment by ArcDrake** [comment]
Isn't that normal? That's what I would expect :)
Documentation at vlang website seems out of date 

> Unlike other C-like languages, there are no parentheses surrounding the condition

**Comment by Henrixounez** [comment]
No, V Panic should not happen here. It should instead give an error message like what i expect to see.

**Comment by ArcDrake** [comment]
Okay i got you. { should maybe only throw an error, don't know.

But I think the documentation is a little misleading, maybe it should say "parentheses around the condition are not necessary" or something like that.

**Comment by Henrixounez** [comment]
Well, it's because i'm used to C-like programming, but the parentheses are useful for priorities in conditions.
`if 1 == 1` and `if (1 == 1)` is similar priority, and V can run both of them.
