### ISSUE TITLE
Fixed-length array accesses still not quite right

### ISSUE THREAD

**Issue by Jhynjhiruu** [vlang/v#15422]
**V doctor:**
```
OS: windows, Microsoft Windows 10 Pro v19044 64-bit
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz  

CC version: cc (Rev3, Built by MSYS2 project) 12.1.0

getwd: C:\Users\[redacted]\Documents\v\acta
vmodules: C:\Users\[redacted]\.vmodules
vroot: C:\v
vexe: C:\v\v.exe
vexe mtime: 2022-07-24 15:25:34
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 2d7406a

Git version: git version 2.37.1
Git vroot status: weekly.2022.28-85-g2d7406a8-dirty
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 125e21e2

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg src/assembler2.v`
See attached file `src/assembler2.v`

**What did you expect to see?**

Successful compilation or a useful error message

**What did you see instead?**
```
==================
C:/Users/[redacted]/AppData/Local/Temp/v_0/assembler2.16017823339585623325.tmp.c:17515: warning: assignment from incompatible pointer type
C:/Users/[redacted]/AppData/Local/Temp/v_0/assembler2.16017823339585623325.tmp.c:18044: error: character array initializer must be a literal, optionally enclosed in braces
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

[assembler2.zip](https://github.com/vlang/v/files/9331583/assembler2.zip)
After #15399 was fixed, I tried retyping the `constant_pool` member of the `Parser` struct as `[][2]string` instead of `[][]string` and fixing the writes to it, but that just exposed another bug. As far as I can tell, the bug is in the handling of line 429, `keys := p.constant_pool.map(it[0])`. It seems like the array of arrays of strings isn't quite getting accesses handled properly.

**Comment by Jhynjhiruu** [comment]
I did notice that I wasn't using latest V when I submitted this - I've now updated and the issue persists.

**Comment by medvednikov** [comment]
Source code from the zip file

https://gist.github.com/medvednikov/6f7322cec86d56c9b409ede67fbfc6b9
