### ISSUE TITLE
some crypto tests fail on FreeBSD-13

### ISSUE THREAD

**Issue by bakul** [vlang/v#15444]
This is not the right way to fix this bug but just by doing
```
ln vlib/crypto/rand/rand_linux.c.v vlib/crypto/rand/rand_freebsd.c.v
```
fixes the following tests. The same change may work for other BSDs though I haven't tested. 

**What did you do?**
`v test-self`

**What did you expect to see?**
```
OK [  46/1071]  1119.350 ms vlib/crypto/bcrypt/bcrypt_test.v
OK [  58/1071]  6604.907 ms vlib/crypto/ed25519/internal/ed25519_test.v
OK [  68/1071]  1054.863 ms vlib/crypto/rand/crypto_rand_bytes_test.v

```
 
**What did you see instead?**
```
 FAIL  [  46/1071]  1119.350 ms vlib/crypto/bcrypt/bcrypt_test.v
 FAIL  [  58/1071]  6604.907 ms vlib/crypto/ed25519/internal/ed25519_test.v
 FAIL  [  68/1071]  1054.863 ms vlib/crypto/rand/crypto_rand_bytes_test.v
```

**Comment by j-bm** [comment]
Is fixed in PR #15437 using arc4random not the linux compatible getrandom.

**Comment by medvednikov** [comment]
Thanks @j-bm

**Comment by bakul** [comment]
Thanks, John! Probably same fix applies to other BSDs....
