### ISSUE TITLE
If example from Docs doesn't work on Windows

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#1544]
**V version:** 0.1.17
**OS:**  Windows 10

**What did you do?**
Compiled and run the following code:

fn main() {
	a := 10 
	b := 20 
	if a < b { 
		println('$a < $b') 
	} else if a > b { 
		println('$a > $b') 
	} else { 
		println('$a == $b') 
	} 
}

**What did you expect to see?**

10 < 20, as on Linux and PlayGround
 
**What did you see instead?**
The syntax of the command is incorrect.

**Comment by Ivo-Balbaert** [comment]
When the interpolated strings like '$a < $b' are replaced by real strings like 'smaller', the program compiles but produces no output.

**Comment by ArcDrake** [comment]
I can't reproduce that, no problem here.
Maybe it is still something wrong with your V Installation. 

At the moment I regularly download a fresh clone instead of using "v up"
There was also a change in make.bat in #1574 so the Installation process working for me is now simplified to:

> git clone https://github.com/vlang/v
> cd v
> make.bat

**Comment by Ivo-Balbaert** [comment]
Thanks. When I copy the code from Docs, I get this syntax error. When I type the code in my editor, everything works fine. So it must be a strange character somewhere that caused this. Closing...
