### ISSUE TITLE
c output doesn't link on FreeBSD

### ISSUE THREAD

**Issue by bakul** [vlang/v#15457]
**V version:** 
V 0.3.0 d3307fd

**OS:** 
FreeBSD

**What did you do?**

Also see the closed #12100. Now it is the link stage that fails so technically closing it is correct!

```
$ echo 'fn main() { println("Hello") }' > hello.v
$ v -o hello.c hello.v
$ cc -Ithirdparty/libgc/include hello.c thirdparty/libgc/gc.c
```

**What did you expect to see?**
The linking to succeed and the program run to produce `Hello`. Note that the exact same test succeeds on ubuntu.

 
**What did you see instead?**
```
hello.c:2097:4: warning: expression result unused [-Wunused-value]
  (*(int*)_t1.data);
   ^~~~~~~~~~~~~~~
hello.c:12070:2: warning: implicit declaration of function 'signal' is invalid in C99 [-Wimplicit-function-declaration]
        signal(11, v_segmentation_fault_handler);
        ^
2 warnings generated.
ld: error: undefined symbol: backtrace
>>> referenced by hello.c
>>>               /tmp/hello-c9fe04.o:(print_backtrace_skipping_top_frames_bsd)

ld: error: undefined symbol: backtrace_symbols_fd
>>> referenced by hello.c
>>>               /tmp/hello-c9fe04.o:(print_backtrace_skipping_top_frames_bsd)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by spytheman** [comment]
I do not get it - it is a linker error, because on FreeBSD, you need to add -lexecinfo. V does it for you automatically, but if you do want to compile the generated source code, that is your responsibility 🤔 .

**Comment by bakul** [comment]
My mistake! I was forgetting to add `-lexecinfo` when manually linking!
