### ISSUE TITLE
Unexpected `v.exe` output

### ISSUE THREAD

**Issue by athif23** [vlang/v#1546]
**V version:** 0.1.17 
**OS:** Windows 10

**What did you do?**
- cloned the v repo
- run `cd v` and `make.bat`
- run `v.exe install glfw`
- copy glfw3.dll file to tetris folder
- run `v.exe run tetris.v`
> I'm using Cmder.

**What did you expect to see?**
A window show up.
 
**What did you see instead?**
```shell
'tetris' is not recognized as an internal or external command,
operable program or batch file.
```

It's fine when I run other examples, well except the hot-reloading one. It doesn't show up the above message, it still compile `.exe` file, but doesn't show anything when I run it.

**Comment by spytheman** [comment]
If you try to run `tetris.exe` in Cmder, what error messages do you get?

**Comment by athif23** [comment]
No, for tetris, it doesn't compile the `.exe` file.

**Comment by ArcDrake** [comment]
Same here. No tetris.exe was created.
It was also no ".vmodule" directory created, after running "v.exe install glfw", I think it should?
I copied glfw3.dll from "\thirdparty\glfw\" to "examples\tetris" and tried to compile. Same error when deleting glfw3.dll.

v.exe install glfw -> prints nothing + no .vmodule directory

**Comment by emily33901** [comment]
Yeah it should afaik - when I'm near a Windows install again I'll look into it

**Comment by ArcDrake** [comment]
Cool, ".vmodule" is created now in my home dir and contains some glfw stuff (no dll!?) due to #1572 I think :)
When I copy "\thirdparty\glfw\glfw3.dll" to "examples\tetris" and try to compile I still get

> 'tetris' is not recognized as an internal or external command,
> operable program or batch file.

and in addition: 

> D:\v\examples\tetris>v run tetris.v
> D:\v/thirdparty/glad/glad.o not found, building it...

this file is created too :)

Is this the correct command for installing freetype?
D:\v>v install freetype

Here I can see no difference

**Comment by athif23** [comment]
Yeah, still didn't create `tetris.exe`.

**Comment by ArcDrake** [comment]
Another idea, I tried it with full qualified path:

D:\v>v run D:\v\examples\tetris\tetris.v
failed to create .D:\v\examples\tetris\tetris.c
'tetris' is not recognized as an internal or external command,
operable program or batch file.

The "." in line 2 is irritating me. Could this be the problem?
