### ISSUE TITLE
cgen error when calling function with receiver that returns generic result 

### ISSUE THREAD

**Issue by ChAoSUnItY** [vlang/v#15475]
OS: windows, Microsoft Windows 11 Home v22000 64-bit
Processor: 20 cpus, 64bit, little endian, 12th Gen Intel(R) Core(TM) i7-12700
CC version: Error: exec failed (CreateProcess) with code 2: 系統找不到指定的檔案。
 cmd: cc --version

getwd: C:\Users\chaos\projects\v_test
vmodules: C:\Users\chaos\.vmodules
vroot: C:\Users\chaos\projects\v
vexe: C:\Users\chaos\projects\v\v.exe
vexe mtime: 2022-08-19 20:52:38
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 22a79cf.fa44744

Git version: git version 2.35.1.windows.2
Git vroot status: weekly.2022.33-28-gfa447443 (3 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 125e21e2

**What did you do?**
`v run generic_result.v`

generic_result.v
```v
struct Dummy {}

fn (dummy &Dummy) res<T>() !T {
	$if T is int {
		return 1
	} $else $if T is f32 {
		return dummy.res<int>()! + 1
	} $else {
		return error('exhausted')
	}
}

d := Dummy{}

println(d.res<int>()!)
println(d.res<f32>()!)
```

**What did you expect to see?**
```
1
2.
```
 
**What did you see instead?**
```
==================
C:/Users/chaos/AppData/Local/Temp/v_0/generic_result.7277512356653479659.tmp.c:7400: warning: cast between pointer and integer of different size
C:/Users/chaos/AppData/Local/Temp/v_0/generic_result.7277512356653479659.tmp.c:12312: error: '{' expected (got ";")
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.
```

**Comment by yuyi98** [comment]
`return dummy.res<int>()! + 1` means just return `int` type and T is `f32` now, so this is a contradiction.

**Comment by ChAoSUnItY** [comment]
No, it is not logically wrong due to type promotion, and it's the point of this issue.

See if you remove receiver from the function, it compiles fine, but it causes cgen error right after having receiver.
