### ISSUE TITLE
mysql clang: error 

### ISSUE THREAD

**Issue by Avey777** [vlang/v#15477]
➜  V v run main.v
==================
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

**Comment by enghitalo** [comment]
Where is the code?

**Comment by Avey777** [comment]
> 代码在哪里？

Example mysql code used

I have it working fine in mocos and linux, but not on windows; it should be an environment problem (but I didn't find a solution)
