### ISSUE TITLE
cgen error: could not generate string method `pthread_mutex_t_str` for type `pthread_mutex_t`

### ISSUE THREAD

**Issue by shove70** [vlang/v#15491]
OS: macos, macOS, 12.5.1, 21G83
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
CC version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)

getwd: /Users/shove/Projects/Temp/v/v_test_001
vmodules: /Users/shove/.vmodules
vroot: /usr/local/v
vexe: /usr/local/v/v
vexe mtime: 2022-08-22 01:03:21
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 0d9ac1f

Git version: git version 2.32.1 (Apple Git-133)
Git vroot status: weekly.2022.33-46-g0d9ac1f5
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 46662e20

**What did you do?**
```v
import sync

struct Foo {
	mutex &sync.Mutex
}

// fn (f &Foo) str() string {
// 	return 'Foo'
// }

fn main() {
	foo := Foo{mutex: sync.new_mutex()}
	println(foo)
}

```

**What did you expect to see?**

 
**What did you see instead?**

```
cgen error: could not generate string method `pthread_mutex_t_str` for type `pthread_mutex_t`
```

**Comment by Delta456** [comment]
With the latest V commit, the above code compiles and gives output:

```

**Comment by shove70** [comment]
on macOS, The problem still exists.
on Linux , OK

**Comment by Delta456** [comment]
What is the issue with MacOs?

**Comment by shove70** [comment]
> What is the issue with MacOs?

cgen error: could not generate string method `pthread_mutex_t_str` for type `pthread_mutex_t`

**Comment by Delta456** [comment]
Strange as it works on Linux for me

**Comment by shove70** [comment]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/27794478/191419445-f692c309-afad-457c-aadc-b637b1b21a39.png">

Yes, it's OK on Linux
