### ISSUE TITLE
How to convert C buffers to array

### ISSUE THREAD

**Issue by qtc-de** [vlang/v#15493]
Hi there :wave: 

simple question (but I did not find it within the docs) - I'm trying to wrap a C function that returns a pointer to an allocated `char` buffer and an integer specifying it's size. Is there elegant way to wrap this into a V array? I thought of something like this:

```v
size := usize(0)
buffer := C.some_function(&size)

array := [size]u8(buffer)
```

This results in `error: expression evaluated but not used`. As a workaround it is obviously possible to create an array with the desired capacity and to copy the items from the C buffer manually. I just want to know if there is a more convenient way to do it :shrug: 

Best
Tobias

**Comment by medvednikov** [comment]
Hi

There's no builtin helper function for this yet, but sounds like a good idea to add this.

For now do:

```
mut my_v_array := []u8{len: size}
unsafe { vmemcpy(my_v_array.data, c_buffer, size * sizeof(u8)) }
```
