### ISSUE TITLE
regex err: The regex does not fit correctly: \r\n

### ISSUE THREAD

**Issue by shove70** [vlang/v#15505]
OS: linux, Linux version 5.10.104-linuxkit (root@buildkitsandbox) (gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, GNU ld (GNU Binutils) 2.35.2) #1 SMP Thu Mar 17 17:08:06 UTC 2022 (VM)
Processor: 2 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
CC version: cc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)

getwd: /usr/local/v
vmodules: /root/.vmodules
vroot: /usr/local/v
vexe: /usr/local/v/v
vexe mtime: 2022-08-23 09:48:40
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.0 3c23eeb

Git version: git version 2.18.4
Git vroot status: weekly.2022.34-9-g3c23eebe
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 827f7452

**What did you do?**

```v
import regex

fn main() {
	info := 'First line: 2013-12-27 16:30:00
Second line'

	mut re := regex.regex_opt('First line: (.+)') or { return }
	re.find(info)
	println(re.groups)
	println(info[re.groups[0]..re.groups[1]])
}

```

**What did you expect to see?**
```
[12, 31]
2013-12-27 16:30:00
 ```
**What did you see instead?**
```
[12, 43]
2013-12-27 16:30:00
Second line
```

**Comment by penguindark** [comment]
Hi @shove70 ,
The behaviour of regex is correct,
as you can see in the docs: https://github.com/vlang/v/blob/master/vlib/regex/README.md in the introduction there is a note:
```
Here are the assumptions made during the writing of the implementation, that are valid for all the regex module features:

1. The matching stops at the end of the string, not at newline characters.
```

If you want the match to stop at the end of the line, you can simply modify the query:
`mut re := regex.regex_opt('First line: (.+)\n') or { return }`
adding a `\n` after the group.

Or you can enable the flag for stop the match at the new lines:
```v
import regex

fn main() {
    info := 'First line: 2013-12-27 16:30:00
Second line'

    mut re := regex.regex_opt('First line: (.+)') or { return }
    re.flag = regex.f_nl // stop the matching if found a new line char 
    re.find(info)
    println(re.groups)
    println(info[re.groups[0]..re.groups[1]])
}
```

as documentend here: https://github.com/vlang/v/blob/master/vlib/regex/README.md#flags

For now I'm closing this issue, if you have comments or issues feel free to contact me. :)

**Comment by shove70** [comment]
thanks. I think this design is probably based on lightweight, performance and other factors. which is very good. 

However, it is a little difficult for users who first use it, because ` ` `.+``` The semantics of is to match characters other than ```[\r\n]```
