### ISSUE TITLE
V can't compile cmd/v in prod mode

### ISSUE THREAD

**Issue by ZWORX52** [vlang/v#15522]
**V version:** V 0.3.0 3ad22eb
**OS:** linux, Ubuntu 22.04.1 LTS (VM)

I won't include the code, as this issue arose when compiling cmd/v (from this repo) in prod mode
**What did you do?**
`v -o v -prod cmd/v` was my command.

**What did you expect to see?**
A production version of the v compiler to be compiled.
 
**What did you see instead?**
<details>
<summary>Show command output</summary>
<pre><code>
==================
/tmp/v_1000/v.14539448693407299098.tmp.c: In function ‘indent_Array_v__ast__Expr_str’:
/tmp/v_1000/v.14539448693407299098.tmp.c:10843:71: error: unused parameter ‘indent_count’ [-Werror=unused-parameter]
10843 | static string indent_Array_v__ast__Expr_str(Array_v__ast__Expr a, int indent_count) {
      |                                                                   ~~~~^~~~~~~~~~~~
/tmp/v_1000/v.14539448693407299098.tmp.c: In function ‘indent_Array_v__ast__Attr_str’:
/tmp/v_1000/v.14539448693407299098.tmp.c:10890:71: error: unused parameter ‘indent_count’ [-Werror=unused-parameter]
10890 | static string indent_Array_v__ast__Attr_str(Array_v__ast__Attr a, int indent_count) {
      |                                                                   ~~~~^~~~~~~~~~~~
/tmp/v_1000/v.14539448693407299098.tmp.c: In function ‘indent_Array_rune_str’:
/tmp/v_1000/v.14539448693407299098.tmp.c:10919:55: error: unused parameter ‘indent_count’ [-Werror=unused-parameter]
10919 | static string indent_Array_rune_str(Array_rune a, int indent_count) {
      |                                                   ~~~~^~~~~~~~~~~~
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
</code></pre>
</details>

As a final side note, I can't report a bug that only happens in production mode with the CLI - there is no `v bug -prod` or similar. Perhaps this should be considered, as running only `v -o v cmd/v` works perfectly. fine.

**Comment by JalonSolov** [comment]
Works here on Manjaro...
```
$ v -o v -prod cmd/v
$
```
Note that this is the same as `v self -prod`.

**Comment by ZWORX52** [comment]
Just updated to gcc 12.0.1 (was on 11) and the issue persists. Can give verbose output if necessary

**Comment by medvednikov** [comment]
This is very strange.

Try a clean build.

```
git clone https://github.com/vlang/v
cd v
make
v -o v -prod cmd/v
```

**Comment by ZWORX52** [comment]
I ran it in a new directory called vtesting, all fresh and clean.
`⌂2.55 [zworx52:~/vtesting] $ git clone https://github.com/vlang/v
Cloning into 'v'...
remote: Enumerating objects: 127249, done.
remote: Counting objects: 100% (127249/127249), done.
remote: Compressing objects: 100% (33640/33640), done.
remote: Total 127249 (delta 90849), reused 127129 (delta 90779), pack-reused 0
Receiving objects: 100% (127249/127249), 57.53 MiB | 13.90 MiB/s, done.
Resolving deltas: 100% (90849/90849), done.
⌂2.58 [zworx52:~/vtesting] $ cd v
^[	⌂2.54 [zworx52:~/vtesting/v] master ± make
make fresh_vc
make[1]: Entering directory '/home/zworx52/vtesting/v'
rm -rf ./vc
git clone --depth 1 --quiet --single-branch https://github.com/vlang/vc ./vc
make[1]: Leaving directory '/home/zworx52/vtesting/v'
cd ./vc && git clean -xf && git pull --quiet
make fresh_tcc
make[1]: Entering directory '/home/zworx52/vtesting/v'
rm -rf ./thirdparty/tcc
git clone --depth 1 --quiet --single-branch --branch thirdparty-linux-amd64 https://github.com/vlang/tccbin ./thirdparty/tcc
make[2]: Entering directory '/home/zworx52/vtesting/v'
make[2]: Leaving directory '/home/zworx52/vtesting/v'
make[1]: Leaving directory '/home/zworx52/vtesting/v'
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
gcc -Wall -Werror -Wextra -std=gnu99 -w -o v1.exe ./vc/v.c -lm -lpthread 
./v1.exe -no-parallel -o v2.exe  cmd/v
./v2.exe -o ./v  cmd/v
rm -rf v1.exe v2.exe
Your `tcc` is working. Good - it is much faster at compiling C source code.
V has been successfully built
V 0.3.1 862d91e
⌂2.45 [zworx52:~/vtesting/v] master ± ./v -o v -prod cmd/v
==================
/tmp/v_1000/v.11526146547410607843.tmp.c: In function ‘indent_Array_v__ast__Expr_str’:
/tmp/v_1000/v.11526146547410607843.tmp.c:10846:71: error: unused parameter ‘indent_count’ [-Werror=unused-parameter]
10846 | static string indent_Array_v__ast__Expr_str(Array_v__ast__Expr a, int indent_count) {
      |                                                                   ~~~~^~~~~~~~~~~~
/tmp/v_1000/v.11526146547410607843.tmp.c: In function ‘indent_Array_v__ast__Attr_str’:
/tmp/v_1000/v.11526146547410607843.tmp.c:10894:71: error: unused parameter ‘indent_count’ [-Werror=unused-parameter]
10894 | static string indent_Array_v__ast__Attr_str(Array_v__ast__Attr a, int indent_count) {
      |                                                                   ~~~~^~~~~~~~~~~~
/tmp/v_1000/v.11526146547410607843.tmp.c: In function ‘indent_Array_rune_str’:
/tmp/v_1000/v.11526146547410607843.tmp.c:10923:55: error: unused parameter ‘indent_count’ [-Werror=unused-parameter]
10923 | static string indent_Array_rune_str(Array_rune a, int indent_count) {
      |                                                   ~~~~^~~~~~~~~~~~
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

[zworx52:~/vtesting/v] master 1 ± 
`
