### ISSUE TITLE
Does not compile function Sum types

### ISSUE THREAD

**Issue by kahsa** [vlang/v#15557]
**V version: 0.3.0 70de4e1** 
**OS: ArchLinux** 

**What did you do?**

`v run .`
```v
type Fn = fn() int | fn(int) int
```

**What did you expect to see?**
No error
 
**What did you see instead?**
Build error
```
==================
/usr/lib64/crt1.o: error: Invalid relocation entry [15] '.rela.debug_info' @ 00000504
tcc: error: file 'crt1.o' not found
/tmp/v_1000/bug.7743942395938441458.tmp.c:26: error: ';' expected (got "int_int")
...
==================
```

**Comment by yuyi98** [comment]
This creates ambiguity.  `type Fn = fn() int|fn(int)int`, so it is alias type, not sumtype.

**Comment by kahsa** [comment]
I don't understand what you mean.
Please explain in more detail.

**Comment by yuyi98** [comment]
I think you want `type Fn = (fn() int) | (fn (int) int)`, but it parse to `type Fn = fn() (int | fn (int) int)`.

**Comment by kahsa** [comment]
```v
type FnA = fn() int
type FnB = fn(int) int
type Fn = FnA | FnB
```
This compiles.

**Comment by kahsa** [comment]
Oh, I see.
You are right, what I want is what I wrote above.

**Comment by kahsa** [comment]
It means that function types cannot be used for sum types?
Is this a specification or just not decided yet?

**Comment by yuyi98** [comment]
I thinks it's a bug, we can use fn type in sum types.
