### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by huangguifeng** [vlang/v#1555]
**V version:** 
**OS:** 
[python@python v]$ uname  -ra
Linux python 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

What is the reason for such an error when using source installation?

![image](https://user-images.githubusercontent.com/31758761/62816465-9606f580-bb5a-11e9-86e2-532fa0beb2db.png)

**Comment by iredmail** [comment]
建议在运行 make 之前先运行 “export LC_ALL=C” 将当前的 shell 的语言环境设置为英文，这样得到的错误信息也是英文的，方便复制到这里给 v 开发人员查看，这样他们才能帮忙分析。

**Comment by huangguifeng** [comment]
![image](https://user-images.githubusercontent.com/31758761/62817021-6f4cbd00-bb62-11e9-97ee-a05bf455d792.png)

**Comment by iredmail** [comment]
- 操作系统是哪个 linux 发行版？具体版本号多少？
- 请直接复制文字贴上来，不要截图。图片比文字大多了，浪费其他用户的流量。

**Comment by huangguifeng** [comment]
> * 操作系统是哪个 linux 发行版？具体版本号多少？
    CentOS 7 64位     Linux version 3.10.0-957.el7.x86_64
> * 请直接复制文字贴上来，不要截图。图片比文字大多了，浪费其他用户的流量。
    感谢提醒

不知道楼上大神是否能安装成功  vlang  0.1.17

**Comment by iredmail** [comment]
V 现在处于非常初级的阶段，每天都有修改，并且可能有一些语法层面的不兼容改动，请直接使用最新的 git 版本，不要用标记的 tag 版本。

**Comment by spytheman** [comment]
Probably you have an old compiler.
Try running 
cc --version

**Comment by medvednikov** [comment]
This is definitely an old C compiler issue.

Upgrade your compiler for now.

In the future older C compilers will be supported.
