### ISSUE TITLE
Type defintion using C types does not compile

### ISSUE THREAD

**Issue by qtc-de** [vlang/v#15575]
**V version:** V 0.3.0 90d9b20.06e153d
**OS:** linux, "Manjaro Linux" (VM)

**What did you do?**

Creating a type definition using a C type:

```v
#flag -lsqlite3
#include "sqlite3.h"

fn C.sqlite3_column_int(stmt &C.sqlite3_stmt, n int) int
type Example = fn () C.sqlite3_stmt
```

**What did you expect to see?**

Successful compilation.
 
**What did you see instead?**

Whereas the function definition works without any errors (e.g. when deleting line 5 and compiling), the type definition throws an error:

```
example.v:5:22: error: unknown type `C.sqlite3_stmt`
    3 |
    4 | fn C.sqlite3_column_int(stmt &C.sqlite3_stmt, n int) int
    5 | type Example = fn () C.sqlite3_stmt
```

**Comment by JalonSolov** [comment]
V doesn't process include files itself... would need an entire C pre-processor to do that.

You'll need to define `C.sqlite3_stmt` yourself for it to work.
