### ISSUE TITLE
Basic syntax change

### ISSUE THREAD

**Issue by dm-vev** [vlang/v#15594]
Greetings! I have a rather non-trivial problem. I want to change the syntax of the language a little bit (it's very unusual for me to use such syntax), but I don't quite understand how I can do it? Can someone give me a small example of how to replace mut with var?

I apologize in advance for my English, and for the possibly offtopic question

**Comment by JalonSolov** [comment]
If you do that, the language will no longer be V.  You should make a complete fork and name it something else.

Also, `mut` simply means to mark something as `mutable` (changeable), since variables in V are immutable (unchangeable) by default.  It does NOT mean the same as `var` in other languages.
