### ISSUE TITLE
`[noinit]` does not work if `[heap; noinit]`

### ISSUE THREAD

**Issue by ghost** [vlang/v#15597]
**V version: 0.3.0 72056f3** 
**OS: ArchLinux** 

**What did you do?**

```v
import net.http

fn main(){
	h := http.Header{}
}
```
For example, change `[noinit]` to `[heap; noinit]`
```v
[heap; noinit]
pub struct Header {
```
**What did you expect to see?**
Same error message as for `[noinit]`.
 
**What did you see instead?**
No error

**Comment by felipensp** [comment]
Can you provide a complete test case?

**Comment by felipensp** [comment]
I've tested this one and found that it just check for `[noinit]` as first occurrence on attr syntax. I've fixed this error and checked that multi attr is working right.
