### ISSUE TITLE
Formatter bug

### ISSUE THREAD

**Issue by 0x9ef** [vlang/v#156]
I found bug of source code formatter on https://vlang.io/play . 
This works only with functions.

If you try this code:

```
fn main() 
{
	magic := true
	if (magic)
	{
		println('Hello world.')
	}
        println(magic)
}
```

You will get:
```
fn main() {
	{
		magic := true
		if (magic)
		{
			println('Hello world.')
		}
                println(magic)
	}
}
```

Formatter automatic adding a block `{}` of local visible code.
```
	{
		magic := true
		if (magic)
		{
			println('Hello world.')
		}
                println(magic)
	}

```

**Comment by xywf221** [comment]
I'm not quite sure what you're trying to say, and my understanding is that you think `{}` wraps up the code block, but it executes normally, and I don't think it's a bug: ]

**Comment by 0x9ef** [comment]
> I'm not quite sure what you're trying to say, and my understanding is that you think `{}` wraps up the code block, but it executes normally, and I don't think it's a bug : ]

No, this shold be syntax error without block-code modifiers. See same Golang, this syntax is not correct syntax. Or let the author add support C-style syntax for block of code.

**Comment by medvednikov** [comment]
It's almost fixed. No extra block is being added now.
