### ISSUE TITLE
v should be able to catch the chained call loop by some sort of warning

### ISSUE THREAD

**Issue by vincenzopalazzo** [vlang/v#15613]
```v
fn (self &Parser) is_eof() bool {
	return self.pos >= self.tokens.len || self.take().kind == TokenKind.eof
}

fn (self &Parser) take() &Token {
	assert !self.is_eof()
	return &self.tokens[self.pos]
}
```

I wrote this very bad code, and  I receive a segmentation fault and I was able to find it only by using `valgrind` I think if we add some check this will make the language much better

I do not know if this make a lot of sense because hide a lot of corner case, but have a segmentation fault is frustating

**Comment by JalonSolov** [comment]
To do that would require a runtime, which V doesn't currently have.

You segfault was likely simply running out of stack.

**Comment by Larpon** [comment]
Use the `-trace-calls` flag - that will hint you if you're recursing to infinity somewhere
