### ISSUE TITLE
C error when casting voidptr to generic type

### ISSUE THREAD

**Issue by tr00** [vlang/v#15618]
Hey,

when casting a voidptr to a V struct I am being prompted 'cannot cast voidptr to struct' which is inconsistent with the docs but makes sense. However, when trying to cast a voidptr to a generic type I receive an C error 'cannot convert void* to struct'. I think it is supposed to also throw an V error rather than letting the C compiler detect this.

Here is a small example with all kinds other flaws but my point are the error messages.
```v
struct Foo {
	x int
}

fn unwrap_concrete(ptr voidptr) Foo {
	return Foo(ptr)
}

fn unwrap_generic<T>(ptr voidptr) T {
	return T(ptr)
}

pub fn main() {

	foo1 := unwrap_concrete(voidptr(0))
	// -> cannot cast `voidptr` to struct
	
	foo2 := unwrap_generic<Foo>(voidptr(0)) 
	// -> builder error: cannot convert 'void *' to 'struct main__Foo'

	println(foo1)
	println(foo2)
}
```

I'm unfamiliar with the V compilers source code so I can't pinpoint the origin of this bug. :/
Anyways, hope this can help

**Comment by Delta456** [comment]
I think this should be a V error

**Comment by medvednikov** [comment]
A C error **always** means there's a bug in the V compiler or an unhandled error.
