### ISSUE TITLE
Failed to compile on macOS Catalina, struct v.gen.c.Gen was declared as private to module v.gen.c.

### ISSUE THREAD

**Issue by alwint3r** [vlang/v#15628]
**V version:** V 0.3.1 bc06866
**OS:** macos, Mac OS X, 10.15.7, 19H2026

**What did you do?**

I tried to pull from master and compile the v. Last commit is fef26a0b1932516386f8a92d5614d76123a78e7a.

**What did you expect to see?**

Successful compilation result
 
**What did you see instead?**

```
cd ./vc && git clean -xf && git pull --quiet
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -std=gnu99 -w -o v1.exe ./vc/v.c -lm -lpthread -L/usr/local/opt/ruby/lib
./v1.exe -no-parallel -o v2.exe  cmd/v
vlib/sync/pool/pool.v:143:10: error: struct `v.gen.c.Gen` was declared as private to module `v.gen.c`, so it can not be used inside module `sync.pool`
  141 |     mut res := []&T{cap: pool.results.len}
  142 |     for i in 0 .. pool.results.len {
  143 |         res << &T(pool.results[i])
      |                ~~~~~~~~~~~~~~~~~~~
  144 |     }
  145 |     return res
make: *** [all] Error 1
```

**Comment by alwint3r** [comment]
Adding `pub` keyword to the struct Gen in `cgen.v` solves the issue. Running test now.

**Comment by medvednikov** [comment]
That's weird. Compiles fine on macos for us, and macos ci is green.

**Comment by alwint3r** [comment]
I think it's a false alarm. I was sure I fetched and merged the latest commit from the master. I fetched again and the error disappeared.

Sorry for the trouble.
