### ISSUE TITLE
make.bat triggers Windows Defender

### ISSUE THREAD

**Issue by PopeDCM** [vlang/v#15653]
When running make.bat for initial install, Windows Defender stops it. Specifically Windows catches it as the trojan "Wacatac.B!ml". It says it was triggered by \v\v2.exe

Happens in administrator cmd as well. I wish I could give a version number, but I can't since I cant run V, but it's the most recent version at the time of posting.

**Comment by Wajinn** [comment]
People need to report such false positive issues to Microsoft.

https://www.microsoft.com/en-us/wdsi/filesubmission/

Choose the type of customer you are (home customer, enterprise customer, or software developer) and then sign in.  Clearly indicate the file is a false positive, and Microsoft will often get back to you with test results in 24 hours.

**Comment by PopeDCM** [comment]
Looks like Windows fixed it, both make.bat and symlink is working without Windows Defender being triggered. Closed.
