### ISSUE TITLE
interface error : non-void function 'xxxx' should return a value

### ISSUE THREAD

**Issue by ghost** [vlang/v#15691]
**V version: 0.3.1 21b2a98** 
**OS: ArchLinux** 

**What did you do?**
```v
interface Foo{}

interface Bar{}

pub fn set_foo(mut foo Foo){
    if foo is Bar{
    }
}

fn main(){}
```
`v -o bug.c .`

**What did you expect to see?**

 
**What did you see instead?**
There is a function that does not return boolean value.
```c
static inline bool I_main__Foo_is_I_main__Bar(main__Foo x) {
	return ;
}
```
This function appears only once and does not seem to be used at all, but `vab` makes this an error.

**Comment by kahsa** [comment]
```v
interface Foo{}

interface Bar{}

pub fn set_foo(mut foo Foo){
    if foo is Bar{
    }
}

struct SFoo{}

fn main(){
    mut f := SFoo{}
    set_foo(mut f)
}
```
this generates
```c
static inline bool I_main__Foo_is_I_main__Bar(main__Foo x) {
	return (x._typ == _main__Foo_main__SFoo_index);
}
```

**Comment by spytheman** [comment]
The generated code is invalid with `clang`, but compiles with `tcc`. With `gcc`, it compiles with just a warning.
I.e. for reproduction, we have to use `-cc clang`.
