### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by GuiChangDi** [vlang/v#1569]
**V version:** 
**OS:**  Win10 1803

**What did you do?**
git clone https://github.com/vlang/v
cd v
make

**What did you expect to see?**
should make success
 
**What did you see instead?**
when execuate this cmd error: 

gcc -std=gnu11 -DUNICODE -D_UNICODE -w -o v.exe v.c
v.c: In function 'init_consts':
v.c:21088:28: error: '_O_U8TEXT' undeclared (first use in this function); did you mean 'O_TEXT'?
  _setmode(_fileno(stdout), _O_U8TEXT);
                            ^~~~~~~~~
                            O_TEXT
v.c:21088:28: note: each undeclared identifier is reported only once for each function it appears in

**Comment by emily33901** [comment]
`gcc --version` please

**Comment by GuiChangDi** [comment]
gcc version 8.2.0 (MinGW.org GCC-8.2.0-3)

**Comment by emily33901** [comment]
Okay nice well there's no reason why it shouldn't be able to find that symbol

**Comment by emily33901** [comment]
Should be defined in fcntl.h so you could look and see whether it is

**Comment by emily33901** [comment]
You could also try mingw-w64 which I think has this constant defined

**Comment by GuiChangDi** [comment]
Okay,I try it with Mingw-w64

**Comment by GuiChangDi** [comment]
Build pass with Mingw-w64,error on win32
