### ISSUE TITLE
Captured local variable by inner function does not retain the change when function exits *?*

### ISSUE THREAD

**Issue by DevrosTheOne** [vlang/v#15707]
**V doctor:**
```
OS: macos, macOS, 12.5.1, 21G83
CC version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)

V full version: V 0.3.1 862d91e.1738641

Git version: git version 2.37.3

```

**What did you do?**
Assumption: local mutable var captured by inner function should retain the changes after function ends?

`v -g -o vdbg cmd/v && vdbg capturemutvar.v`
```v
struct Me{
	mut:
	name string
}

fn ( mut org_me Me ) change_me( name string ) Me {
	mut new_me := Me{'noname'}

	name_ch := fn [mut org_me, mut new_me] ( name string ) {  //capture mut org_me and mut new_me 
		new_me.name = name
		org_me.name = name
	}

	name_ch( name )
	return new_me
}

fn main() {
	mut org_me := Me{ 'Srecko' }
	new_me := org_me.change_me( 'Devros' )
	println( org_me.name )
	println( new_me.name )
}
```

**What did you expect to see?**

both structs changed
```
Devros
Devros
```
**What did you see instead?**
```
Devros
noname
```

**Comment by shove70** [comment]
https://github.com/vlang/v/blob/master/doc/docs.md#closures

This is not a problem, please refer to the closure description.

**Comment by DevrosTheOne** [comment]
Thank you.  
Missed the doc line 'If you need the value to be modified outside the function, use a reference.'
