### ISSUE TITLE
how to append a map (dictionary)

### ISSUE THREAD

**Issue by OdaiGH** [vlang/v#15751]
my variable is as follows:
`mut v := map[string]map[string]int{}`

`v["some random value"] = {"test,1}`

now how to append a new value to the same index ?

documentation needs more details to be honest

**Comment by saumil-ventura** [comment]
When you run this code, compiler literally shows you how to do this.
btw here is example code.
`fn main(){
	mut v := map[string]map[string]int{}
	v["name"] = {"Hello":1}
	v["name2"] = {"world":2}
	print(v)
}`

**Comment by spytheman** [comment]
You can also do something like this directly (note the `m['another']['key'] = 999` line):
```v
mut m := map[string]map[string]int{}
m['some random value'] = {
        'test': 1
}
m['some random value']['def'] = 123
m['another']['key'] = 999
println(m)
```

**Comment by OdaiGH** [comment]
> When you run your code, compiler literally shows you how to do this.

this is not what i wanted

@spytheman just replied with the right code
