### ISSUE TITLE
C error while trying conversion from string to char to u8

### ISSUE THREAD

**Issue by nguiard** [vlang/v#15760]
OS: linux, Debian GNU/Linux 11 (bullseye)
Processor: 16 cpus, 64bit, little endian, Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
CC version: cc (Debian 10.2.1-6) 10.2.1 20210110

getwd: /home/nicolas/projects/v-playground/y-compiler
vmodules: /home/nicolas/.vmodules
vroot: /home/nicolas/projects/v-playground/v
vexe: /home/nicolas/projects/v-playground/v/v
vexe mtime: 2022-09-13 03:34:06
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.1 17b54cd.ac61675

Git version: git version 2.30.2
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false
thirdparty/tcc status: thirdparty-linux-amd64 827f7452

I was just fooling around with the V REPL (I'm new) and got this "C error. This should never happen", by typing `u8(char('a'))`:

```
>>> u8(char('a'))
==================
/tmp/v_1000/.noprefix.01GCYF6G4PZ04TW173EQXSFJN2.vrepl_temp.16904690007344088179.tmp.c:21517: error: cannot convert 'struct string' to 'char'
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by JalonSolov** [comment]
The error is correct, but V should have reported the problem, instead of allowing it to get to the C compiler.

This works:
```
>>> u8(char('a'[0]))
97
>>> 
```
You can't convert a string to a char, but you can convert a single character to a char... which is silly, since it already is a char...
```
>>> u8('a'[0])
97
>>> 
```
and V can tell you about _all_ the bytes in a string using the `.bytes()` method
```
>>> 'a'.bytes()
[97]
>>> 
```

**Comment by Delta456** [comment]
I can work on this.

**Comment by shove70** [comment]
> I can work on this.

@Delta456 
Sorry, I didn't notice this assignment :)

**Comment by Delta456** [comment]
No problem
