### ISSUE TITLE
vrepl bug in array methods pop and delete_last

### ISSUE THREAD

**Issue by Sarctiann** [vlang/v#15769]
```v
>>> mut arr := [1, 2, 3]
>>> a.pop()
>>> a
[1, 2, 3]
>>> a.delete_last()
>>> a
[1, 2, 3]
```

**Comment by shove70** [comment]
```
>>> mut a := [1, 2, 3]
>>> b := a.pop()
>>> a
[1, 2]
>>> b
3
>>>
>>>
>>> a.delete_last()
>>> a
[1, 2]
>>>
```

V 0.3.1 ac61675 on windows

**Comment by shove70** [comment]
@Sarctiann, sorry, there is a problem.

```
>>> mut a := [1, 2, 3]
>>> a.delete_last()
>>> a
[1, 2, 3]
>>>
```

**Comment by Sarctiann** [comment]
v doctor info:

OS: linux, KDE neon User - 5.25
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
CC version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

getwd: /home/sarctiann/Documentos/SARCTIANN/srepl
vmodules: /home/sarctiann/.vmodules
vroot: /home/sarctiann/.v
vexe: /home/sarctiann/.v/v
vexe mtime: 2022-09-05 12:28:52
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.1 a6026fd.d0d5f1d

Git version: git version 2.25.1
Git vroot status: 0.3.1-20-gd0d5f1d4 (56 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 827f7452
