### ISSUE TITLE
result or optional type is not handled in `_test.v`

### ISSUE THREAD

**Issue by kahsa** [vlang/v#15780]
**V version:** 
**OS:** 

**What did you do?**
```
.
├── bug.v
├── bug_test.v
└── v.mod
```
bug.v
```v
module main

fn foo() !string{
	return 'abc'
}

fn main(){
	println(foo()!)
}
```
bug_test.v
```v
module main

fn test_1(){
	println(foo()!)
}
```

**What did you expect to see?**
No error as same as `v run bug.v`
 
**What did you see instead?**
```
> v run bug_test.v
bug_test.v:4:15: error: to propagate the call, `test_1` must return an result type
    2 | 
    3 | fn test_1(){
    4 |     println(foo()!)
      |                  ^
    5 | }
```

**Comment by shove70** [comment]
There is no problem here,
"!,?" The meaning of "optional" is to propagate it up, so test_1() need to return an optional.
main() is an exception, because it is already the top of the propagation chain.

**Comment by kahsa** [comment]
Oh! I see, thanks.
But then it should be like this for better
```v
    3 | fn test_1() {
      |            ^
    4 |     println(foo()!)
    5 | }
```
