### ISSUE TITLE
It's probably a bug.

### ISSUE THREAD

**Issue by xywf221** [vlang/v#158]
I'm trying to run the following code
```
fn main() {
        str := '123'
	println()
}
```
output : `test.v:3. Unexpected token: ') '`,I think he should have given me the error. The function parameter is empty

**Comment by ntrel** [comment]
That is the error ;-)

I think it's planned for println to accept multiple arguments. If so probably no arguments could be supported too. (So this would hopefully be a new language feature: variadic function arguments. And println would be a standard library function).

**Comment by ntrel** [comment]
But yes, it would be better for V to print the function signature when the argument types or argument count do not match the function parameter(s).

**Comment by medvednikov** [comment]
Fixed:
```
not enough arguments in call to `println` 
```

**Comment by medvednikov** [comment]
> So this would hopefully be a new language feature: variadic function arguments

Yes, varargs will be supported.
