### ISSUE TITLE
"result type propagate error" does not arise

### ISSUE THREAD

**Issue by kahsa** [vlang/v#15814]
**V version: 0.3.1 d7758b2** 
**OS: ArchLinux** 

**What did you do?**
```v
struct Foo{}

fn new_foo() !Foo{
	return error('')
}

fn (f Foo) foo() int{
	return 1
}

fn test() {  // here needs `!`
	i := new_foo()!.foo()
	println(i)
}

fn main(){
	test()
}
```

**What did you expect to see?**
Error "error: to propagate the optional call, `test` must return an optional"  as optional case does.
 
**What did you see instead?**
No checked and run prints nothing without any error caused.

**Comment by kahsa** [comment]
Maybe the actual bug in this issue (#15780) is this one.

**Comment by spytheman** [comment]
With the latest changes in https://github.com/vlang/v/pull/15813 , it will look like this:
![image](https://user-images.githubusercontent.com/26967/190965482-f1758050-9059-4baa-a8e5-4f6bbadceb3f.png)

**Comment by kahsa** [comment]
yes, pointing to both causes is perfect solution.
