### ISSUE TITLE
fmt removes struct [json] definition for embedded structs

### ISSUE THREAD

**Issue by thomaspeissl** [vlang/v#15848]
OS: linux, Pop!_OS 22.04 LTS
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-8305G CPU @ 2.80GHz
CC version: cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

getwd: /home/loguser002/a/dev
vmodules: /home/loguser002/.vmodules
vroot: /home/loguser002/a/v
vexe: /home/loguser002/a/v/v
vexe mtime: 2022-09-22 14:12:57
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.1 cd31108.5c716af

Git version: git version 2.34.1
Git vroot status: weekly.2022.38-15-g5c716afb
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 827f7452

```v
import json

struct Size {
	width int
}

struct Button {
	Size [json: size] // fmt removes [json: size]
}

fn main() {
	a := Button{}
	println(json.encode(a)) // {"size":{"width":0}}
}
```

**What did you do?**
v fmt -w .

**What did you expect to see?**
Formatting my code.
 
**What did you see instead?**
`fmt` removed `[json: size]` from my code and thus the `json.encode()` will output
`{"Size":{"width":0}}` instead of `{"size":{"width":0}}`.

**Comment by shove70** [comment]
I don't think there is such a grammar. Assuming that the embedded structure has multiple fields, which field is the property you set?

It seems like this:

```v
import json

struct Size {
	width int // fmt removes [json: size]
}

struct Button {
	Size [json: size]
}

fn main() {
	a := Button{}
	println(json.encode(a)) // {"size":{"width":0}}
}
```

**Comment by shove70** [comment]
It seems that there is no such syntax, because it seems from the output ast file that the attributes of the embedded structure have been ignored in the scan and parse phases.

But it may also be parser negligence.

**Comment by shove70** [comment]
After analysis, the original design did not consider it.

```
v.ast.StructDecl{
    attrs: []
    generic_types: []
    fields: []                                             // => Empty, The information of embedded structure is in the following line
    embeds: [v.ast.Embed{
        typ: ast.Type(0x5d = 93)
        pos: v.token.Pos{
            len: 4
            line_nr: 7
            pos: 58
            col: 1
            last_line: 7
        }
        comments: []
    }]
    end_comments: []
    name: 'main.Button'
    pos: v.token.Pos{
        len: 13
        line_nr: 6
        pos: 41
        col: 0
        last_line: 8
    }
    global_pos: -1
    module_pos: -1
    pub_mut_pos: -1
    pub_pos: -1
    mut_pos: -1
    language: v
    is_union: false
    is_pub: false
}
```


The embedded structure is not designed with "[]attrs"

```v
pub struct Embed {
pub:
	typ      Type
	pos      token.Pos
	comments []Comment
}
```

**Comment by spytheman** [comment]
Attributes are for fields, not for embedded structs (they can have multiple fields).
If anything, adding attributes to an embedded struct should be a parser or checker error.

**Comment by Delta456** [comment]
> Attributes are for fields, not for embedded structs (they can have multiple fields).
> If anything, adding attributes to an embedded struct should be a parser or checker error.

I will work on this then

**Comment by shove70** [comment]
When I first saw the issue, I thought that the embedded structure should not have attributes, but should correspond to specific fields.

But the next test is interesting:


```v
import json

struct Size {
	width  int
	height int
}

struct Button {
	Size [json: a_key_size]
}

fn main() {
	a := Button{}
	println(json.encode(a))
}
```

output:
```
{"a_key_size":{"width":0, "height":0}}
```

Look, the key of json is "a_key_size", which contains width, height and two sub keys. This coincides with the user's original intention! This oversight of the inspector has brought an unexpected harvest: embedded structures, like anonymous structures, also realize the corresponding relationship of multi-layer json structures.

So I hesitated for some time on whether to add attributes to the anonymous structure. Should I refuse to set attributes to the embedded structure in the inspector, or should I improve it so that it can work according to the user's intention?

I can't make up my mind, so on the basis of not destroying the overall design of V, I listen to the teachers!！

**Comment by Delta456** [comment]
> When I first saw the issue, I thought that the embedded structure should not have attributes, but should correspond to specific fields.
> 
> But the next test is interesting:
> 
> ```v
> import json
> 
> struct Size {
> 	width  int
> 	height int
> }
> 
I
> struct Button {
> 	Size [json: a_key_size]
> }
> 
> fn main() {
> 	a := Button{}
> 	println(json.encode(a))
> }
> ```
> 
> output:
> 
> ```
> {"a_key_size":{"width":0, "height":0}}
> ```
> 
> Look, the key of json is "a_key_size", which contains width, height and two sub keys. This coincides with the user's original intention! This oversight of the inspector has brought an unexpected harvest: embedded structures, like anonymous structures, also realize the corresponding relationship of multi-layer json structures.
> 
> So I hesitated for some time on whether to add attributes to the embedded structure. Should I refuse to set attributes to the embedded structure in the inspector, or should I improve it so that it can work according to the user's intention?
> 
> I can't make up my mind, so on the basis of not destroying the overall design of V, I listen to the teachers!！

I believe there are far more attributes which will be added in future and cannot be used with embedded structs so restricting it for now seems to be reasonable.

**Comment by shove70** [comment]
Thanks. :)
