### ISSUE TITLE
`make test` failed: .orm_test.c:113:10: fatal error: 'libpq-fe.h' file not found

### ISSUE THREAD

**Issue by iredmail** [vlang/v#1587]
**V version:** latest git version
**OS:** Debian 10

**What did you do?**

```
git clone [v-repo]
cd v/
make test
```

**What did you expect to see?**

Finish without error.
 
**What did you see instead?**

```
.orm_test.c:113:10: fatal error: 'libpq-fe.h' file not found
#include <libpq-fe.h>
         ^~~~~~~~~~~~
1 error generated.V panic: C error. This should never happen. Please create a GitHub issue:
```

**Comment by iredmail** [comment]
Sorry, mistake.

**Comment by gmlewis** [comment]
I'm seeing the same thing on MacOSX - what did you do to fix it?

**Comment by enghitalo** [comment]
So try installing libpq-dev or its equivalent for your OS:

For Ubuntu/Debian systems: `sudo apt-get install libpq-dev`
On [Red Hat Linux](http://en.wikipedia.org/wiki/Red_Hat_Linux) (RHEL) systems: `yum install postgresql-devel`
For Mac [Homebrew](https://en.wikipedia.org/wiki/Homebrew_%28package_management_software%29): `brew install postgresql`
For Mac [MacPorts](http://en.wikipedia.org/wiki/MacPorts) PostgreSQL: `gem install pg -- --with-pg-config=/opt/local/lib/postgresql[version number]/bin/pg_config`
For [OpenSuse](https://en.wikipedia.org/wiki/OpenSUSE): `zypper in postgresql-devel`
For [ArchLinux](https://en.wikipedia.org/wiki/Arch_Linux): `pacman -S postgresql-libs`
