### ISSUE TITLE
implement methods for generic interface failed

### ISSUE THREAD

**Issue by pathologyenigma** [vlang/v#15883]
V full version: V 0.3.1 f557acf.721328e
OS: windows, Microsoft Windows 11 Pro v22622 64-bit

**What did you do?**
```v
//optional.v
struct NonValue{}

pub type Optional<T> = T | NonValue


pub fn(self Optional<T>) is_some<T>() bool {
	return (self is T)
}

pub fn(self Optional<T>) is_none<T>() bool {
	return !self.is_some()
}

pub fn(self Optional<T>) expect<T>(msg string) T {
	if self.is_some() {
		return self as T
	} else {
		panic(msg)
	}
}

pub fn(self Optional<T>) unwrap<T>() T {
	return self.expect("unwrap on a none value")
}

pub fn(self Optional<T>) unwrap_or<T>(default T) T{
	if self.is_some() {
		return self as T
	} else {
		return default
	}
}

pub fn(self Optional<T>) unwrap_or_else<T>(else_fn fn() T) T {
	if self.is_some() {
		return self as T
	} else {
		return else_fn()
	}
}

pub fn some<T>(value T) Optional<T> {
	return Optional<T>(value as T)
}

pub fn null<T>() Optional<T> {
	return Optional<T>(NonValue{})
}
// iter.v
pub interface Iterator<T> {
mut:
	next() Optional<T>
}

pub fn(mut self Iterator<T>) count<T>() int {
	mut count := 0
	for self.next().is_some() {
		count += 1
	}
	return count
}

struct EmptyIter<T> {
	value NonValue
}
fn(mut self EmptyIter<T>) next<T>() Optional<T> {
	return Optional<T>(self.value)
}
// iter_test.v
fn test_empty_iter() {
	mut iter := EmptyIter<u32>{}
	assert iter.next().is_none()
	assert Iterator<u32>(iter).count() == 0
}
```

**What did you expect to see?**
test passed
 
**What did you see instead?**
error: could not infer generic type `T` in interface `app.utils.Iterator`
   11 |     mut iter := EmptyIter<u32>{}
   12 |     assert iter.next().is_none()
   13 |     assert Iterator<u32>(iter).count() == 0
      |            ~~~~~~~~~~~~~~~~~~~
   14 | }

**Comment by shove70** [comment]
```v
struct NonValue{}

pub type Optional<T> = T | NonValue       // => missing `<T>`

pub fn(self Optional) is_some<T>() bool {      // => missing `<T>`
return (self is T)
}

......

```

missed it in a lot of places.

**Comment by pathologyenigma** [comment]
> ```v
> struct NonValue{}
> 
> pub type Optional<T> = T | NonValue       // => missing `<T>`
> 
> pub fn(self Optional) is_some<T>() bool {      // => missing `<T>`
> return (self is T)
> }
> 
> ......
> ```
> 
> missed it in a lot of places.
my code contains that <T>, I don't know why it is missing when I submit it here, now I update it using code block

**Comment by pathologyenigma** [comment]
> ```v
> struct NonValue{}
> 
> pub type Optional<T> = T | NonValue       // => missing `<T>`
> 
> pub fn(self Optional) is_some<T>() bool {      // => missing `<T>`
> return (self is T)
> }
> 
> ......
> ```
> 
> missed it in a lot of places.


I forget to use the code block, it is not a missing of <T>
