### ISSUE TITLE
Multidimensional arrays 

### ISSUE THREAD

**Issue by l8atnight** [vlang/v#1588]
Please implement multidimensional arrays , so we can use matrices.

Thanks

**Comment by schurhammer** [comment]
You can implement matrices with 1d arrays

**Comment by medvednikov** [comment]
They are already partly supported:

matrix [][]int

Check out tetris.v for an example.

**Comment by medvednikov** [comment]
This should stay open, because they are not fully implemented yet.

**Comment by Delta456** [comment]
Fixed
