### ISSUE TITLE
fmt: trailing comma in variadic fn args not removed

### ISSUE THREAD

**Issue by Hunam6** [vlang/v#15889]
```
OS: macos, macOS, 12.6, 21G115
Processor: 8 cpus, 64bit, little endian, Apple M1
CC version: Apple clang version 14.0.0 (clang-1400.0.29.102)

getwd: /Users/hunam/Documents/dev/go2v
vmodules: /Users/hunam/.vmodules
vroot: /Applications/v
vexe: /Applications/v/v
vexe mtime: 2022-09-26 12:24:22
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.1 862d91e.385acb4

Git version: git version 2.37.0 (Apple Git-136)
Git vroot status: weekly.2022.38-39-g385acb44
.git/config present: true
thirdparty/tcc status: thirdparty-macos-arm64 173c526e
```

**What did you do?**
```v
fn abc(a ...T, ) {}
```

**What did you expect to see?**
```v
fn abc(a ...T) {}
```
 
**What did you see instead?**
```v
fn abc(a ...T, ) {}
```

**Comment by shove70** [comment]
In my opinion, it seems that this syntax error should be reported by the "checker" and handed over to the user for processing rather than being removed directly.

Assumptions:

```fn abc(a ...T, b int) {}```

  It seems unreasonable for formater to remove ```, b int``` directly.

**Comment by shove70** [comment]
As for the case of only one "," tail, we can consider whether to optimize

**Comment by JalonSolov** [comment]
He's not asking for `, b int` to be removed, just the trailing `,` in his example.

**Comment by shove70** [comment]
Yes, yes, I know.

The case threw an error in the parsing phase:

```
a.v:1:8: error: cannot use ...(variadic) with non-final parameter a
1 | fn abc(a ...T, ) {}
| ^

Internal vfmt error while formatting file: a.v.
Encountered a total of: 1 errors.
```

It seems that the workload to solve this problem is not small
