### ISSUE TITLE
Error installing v

### ISSUE THREAD

**Issue by muconto** [vlang/v#1589]
**V version:** 
**OS:Fedora 29** 

while installing v had this error
**What did you see instead?**
rm -rf /usr/local/{bin/v,bin/vget,lib/vlang}
./v tools/vget.v
.vget.c:117:10: fatal error: openssl/ssl.h: No such file or directory
 #include <openssl/ssl.h>
          ^~~~~~~~~~~~~~~
compilation terminated.V panic: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
make: *** [Makefile:24: tools/vget] Error 1

**Comment by medvednikov** [comment]
Fixed. `make` no longer requires openssl.

**Comment by muconto** [comment]
Many thanks
