### ISSUE TITLE
compile error without a new line

### ISSUE THREAD

**Issue by tonylinyy** [vlang/v#159]
the code is:
fn main() {
	println('v')
}
get a panic:
V panic: string index out of range: 27 / 27

if I press enter after the },compile will success
fn main() {
	println('v')
}
--here add a new empty line

**Comment by ofunc** [comment]
I can't reproduce this problem.

**Comment by tonylinyy** [comment]
I use v compiler not the web playground

**Comment by di3663** [comment]
> I use v compiler not the web playground

update the compiler perhaps

**Comment by tonylinyy** [comment]
this problem still in my macos,after I upgrade to V0.0.2
I try with sublime text and idea,all the same

**Comment by medvednikov** [comment]
I can't reproduce this, will investigate.

**Comment by medvednikov** [comment]
Fixed. Will be live in 0.0.5.
