### ISSUE TITLE
Comptime $For & $If with Generics / Type Inference

### ISSUE THREAD

**Issue by joe-conigliaro** [vlang/v#15905]
There are a few issues with inferring generic types from inside Comptime $If & $For.

This feature will be useful for lots of things especially encoding/decoding libs, I started a branch to fix it while developing this: https://github.com/vlang/msgpack. You can actually checkout that repo and try and run the examples/basic.v.

My branch (barely) gets it running by manually registering the concrete types for the `$if T is $Array {` and nested `for` in a similar way to how it is done with `$for`: https://github.com/joe-conigliaro/v/tree/comptime_selector_generic_call.
However this will fail in many cases with nested $for or $if, or when trying to infer a non generic type in one of those comptime branches as I'm manually setting the type currently. It does run the current examples/basic.v and quite a few other more complex cases. But it is a big mess and needs to be redone.

There is more to the issues I am forgetting here, I will add in notes as they come to mind.

We need to come up with a solid solution, as it simplifies code and allows much greater flexibility.

Here is a simple stand alone test case:

```go
fn fn_a<T>(data T, depth int, nl bool) {
    for _ in 0..depth {
        print('\t')
    }
    $if T.typ is int {
        print('int: $data')
    } $else $if T.typ is string {
        print('string: $data')
    } $else $if T is $Array {
        println('array: [')
        for i, elem in data {
            fn_a(elem, depth+1, false)
            if i < data.len-1 {
                print(', ')
            }
            println('')
        }
        print(']')
    } $else $if T is $Map {
        println('map: {')
        for key, value in data {
            print('\t(key) ')
            fn_a(key, depth, false)
            print(' -> (value) ')
            fn_a(value, depth, true)
        }
        print('}')
    } $else $if T is $Struct {
        println('struct $T.name: {')
        $for field in T.fields {
            print('\t($field.name) ')
            fn_a(data.$(field.name), depth, true)
            // uncommenting either of these lines will cause a C error in my branch as the type is
            // set manually to the $for field type, it needs to be fixed to infer the type correctly.
            // fn_a([1,2,3,4], depth+1, true)
            // fn_a(0.111, depth+1, true)
        }
        print('}')
    }
    if nl {
        println('')
    }
}

struct StructA {
    field_a int
    field_b string
}

fn main() {
    fn_a(111, 0, true)
    fn_a('hello', 0, true)
    fn_a(['a', 'b', 'c', 'd'], 0, true)
    fn_a({'one': 1, 'two': 2}, 0, true)
    fn_a(StructA{field_a: 111, field_b: 'vlang'}, 0, true)
}
```
Output using my branch listed above (does not compile on master):
```sh
int: 111
string: hello
array: [
	string: a,
	string: b,
	string: c,
	string: d
]
map: {
	(key) string: one -> (value) int: 1
	(key) string: two -> (value) int: 2
}
struct StructA: {
	(field_a) int: 111
	(field_b) string: vlang
}
```
Have you got any ideas about this @yuyi98 ?

Some other notes I would like to add is we have `$if T.typ is int` and also `$if T is $Array` and they are implemented in two different ways. Perhaps we should have `$if T.typ is i16` / `$if T.typ is []u8` and `$if T.kind is (u)integer` / `$if T.kind is array` / `$if T.kind is map`, and they could also share the same implementation, instead of needing two different ones. This is just an idea in either case, whatever the syntax is, it would be nice if the code that handles these situations was merged together.

**Comment by yuyi98** [comment]
@joe-conigliaro  Thanks !  Could you provide an independent testable example?

**Comment by joe-conigliaro** [comment]
Hi @yuyi98,

Thanks for your response. I will make a simple example and post it soon.

In the mean time, if you want to take a look now you can clone the msgpack repo and there is an example in there (which runs with my messy v branch).

**Comment by joe-conigliaro** [comment]
Hi @yuyi98, I have updated the description with a simple stand alone example. This example runs on the branch i listed above.

**Comment by yuyi98** [comment]
@joe-conigliaro   Thanks!  I'll try.

**Comment by joe-conigliaro** [comment]
No problem @yuyi98 , thank you 💪

**Comment by joe-conigliaro** [comment]
Hi @yuyi98, just letting you know I updated the example int he description, so that for array's and maps. it calls the generic function recursively instead of just printing the value.
