### ISSUE TITLE
V does not compile

### ISSUE THREAD

**Issue by t3mnikov** [vlang/v#1590]
**V version:** 0.1.17
**OS:** Elementary OS 5 Juno (Linux t3mnikov 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
)

**What did you do?**
git clone https://github.com/vlang/v
cd v
make

**What did you expect to see?**
end of compilation
 
**What did you see instead?**
#curl -o v.0.1.17.c -LsSf https://github.com/vlang/vc/raw/0.1.17/v.c
curl -o v.0.1.17.c -LsSf https://raw.githubusercontent.com/vlang/vc/master/v.c
cc -std=gnu11 -w -o v.c.out v.0.1.17.c -lm
./v.c.out -o v compiler
./v tools/vget.v
/home/xandr/v/thirdparty/cJSON/cJSON.o not found, building it...

.vget.c:117:10: fatal error: openssl/ssl.h: Нет такого файла или каталога
 #include <openssl/ssl.h>
          ^~~~~~~~~~~~~~~
compilation terminated.V panic: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
Makefile:24: recipe for target 'tools/vget' failed
make: *** [tools/vget] Error 1

**Comment by emily33901** [comment]
Install openssl devel (I think this in the readme now)

**Comment by medvednikov** [comment]
Fixed. `make` no longer requires openssl.
