### ISSUE TITLE
compiler: wrong error code for undefined array return value

### ISSUE THREAD

**Issue by spacesinmotion** [vlang/v#1591]
**V version:0.1.17 _(89d0b75311d9228a7b6fa9f3f9f137f15ffe0d5a)_** 
**OS: Linux _(CentOS Linux release 7.3.1611 (Core))_** 

**What did you do?**
I want to return an empty array in an error case: like:
```go
fn conditional_strings(ok bool) /* missing []string */ {
  if !ok {
    return []string
  }
  return ['a', 'b', 'c']
}

fn test_return_string_array() {
  assert conditional_strings(true).contains('b')
  assert !conditional_strings(false).contains('b')
}
```

**What did you expect to see?**
error: function should not return a value 
 
**What did you see instead?**
```sh
return_array_test.v:4 unreachable code
```

**Comment by medvednikov** [comment]
@schurhammer can you please have a look at this?

**Comment by schurhammer** [comment]
Your function doesn't have the return type declared which is causing this. Should be
```fn conditional_strings(ok bool) []string  { ... }```

**Comment by spacesinmotion** [comment]
@schurhammer 
ok, so the error itself is still wrong, right?

**Comment by schurhammer** [comment]
Yes I suppose it should be a different error.

```
parser:3347
if !p.is_vweb && (p.tok == .name || p.tok == .number || p.tok == .str) { 
	p.error('function `$p.cur_fn.name` should not return a value')
}
``` 
This is the code that should catch it, it doesn't catch array definitions right now.

**Comment by medvednikov** [comment]
Sorry @schurhammer I hadn't woken up yet :)

Should have seen it was an unrelated issue.

**Comment by medvednikov** [comment]
@spacesinmotion will fix, thanks

**Comment by lutherwenxu** [comment]
On V 0.1.27 c4fbae3, the sample code results in:
```
hello.v:3:5: error: too many arguments to return, current function does not return anything 
    1 | fn conditional_strings(ok bool) /* missing []string */ {
    2 |   if !ok {
    3 |     return []string
      |     ~~~~~~~~
    4 |   }
    5 |   return ['a', 'b', 'c']
hello.v:5:3: error: too many arguments to return, current function does not return anything 
    3 |     return []string
    4 |   }
    5 |   return ['a', 'b', 'c']
      |   ~~~~~~~~~~~~~~~~~~~~~~
    6 | }
    7 |
```
Which is correct behavior. Please reopen with another example if the problem persists.
