### ISSUE TITLE
Fix json usage without importing json module

### ISSUE THREAD

**Issue by Danil-Lapirow** [vlang/v#1596]
**V version:** latest master branch 
**OS:** 
Ubuntu 18.04

**What did you do?**
Used json.encode or json.decode without importing json module. 

**What did you expect to see?**
Project shouldn't compile and I should see error report. 
 
**What did you see instead?**
Project is successfully dumped to C, but didn't compiled because of missing cJSON dependency.

**Comment by medvednikov** [comment]
Fixed.
