### ISSUE TITLE
type inference and comma in map

### ISSUE THREAD

**Issue by kahsa** [vlang/v#15965]
**V version: 0.3.1 acbfe88** 
**OS: ArchLinux** 

**What did you do?**
I don't know if this is a bug or spec.
```v
enum Foo{
	a
	b
}

fn main(){
	mp := {
		Foo.a: 'A'  // Foo.a: 'A', Works if comma is there.
		.b: 'B'
	}
	println(mp)
}
```
**What did you expect to see?**
No error.
 
**What did you see instead?**
```
> v run bug.v
bug.v:8:4: error: invalid expression: unexpected token `:`
    6 | const mp = {
    7 |     Foo.a: 'A'
    8 |     .b: 'B'
      |       ^
    9 | }
```

**Comment by JalonSolov** [comment]
Yes, this is because V ignores whitespace, so what you have looks like
```v
Foo.a:'A'.b:'B'
```
without a comma.

**Comment by kahsa** [comment]
The problem of the current specification, which allows for commas or no commas, is apparent.

**Comment by kahsa** [comment]
Personally, I believe that commas should be mandatory.
