### ISSUE TITLE
panic when import standard module 

### ISSUE THREAD

**Issue by tonylinyy** [vlang/v#160]
code is :
module main
import os

fn main(){
    println(os.args)
}

result:
errno=2 err='No such file or directory'
V panic: /Users/alex/code/lang//os doesnt exist
i use the early_v_mac,version is v0.0.1

**Comment by medvednikov** [comment]
Strange. Worked fine when I tested on a clean machine. Will push a fix soon, thanks for reporting.

**Comment by medvednikov** [comment]
0.0.2 is out, please try it.

**Comment by tonylinyy** [comment]
I tried,it works,good job
