### ISSUE TITLE
recent (1-2 weeks) new random seg fault from code reading jpg file.

### ISSUE THREAD

**Issue by splace** [vlang/v#16000]
maybe, just guessing; pre-existing race condition exposed by changes to compiler?

```
OS: linux, Linux version 6.0.0-0.rc7.20220930git987a926c1d8a.51.fc38.x86_64 (mockbuild@3443a1a08e9047859d63d14357d1f72f) (gcc (GCC) 12.2.1 20220819 (Red Hat 12.2.1-2), GNU ld version 2.39-3.fc38) #1 SMP PREEMPT_DYNAMIC Fri Sep 30 14:09:51 UTC 2022
Processor: 2 cpus, 64bit, little endian, Intel(R) Core(TM)2 Duo CPU     E8300  @ 2.83GHz
CC version: cc (GCC) 12.2.1 20220819 (Red Hat 12.2.1-2)
```

**What did you do?**
```
cd examples/sokol/06_obj_viewer
v show_obj
./show_obj
```

(using obj file with jpg textures, no crash when swapped to png textures)

**What did you expect to see?**
3d image in window (as last week)

 
**What did you see instead?**
(randomly, without recompile)

```
.
.
map_Kd = textures/Wood_Tower_Col.jpg
map_Bu = p  textures/Wood_Tower_Nor.jpg
signal 11: segmentation fault
/tmp/v_1000/show_obj.16050823187957602812.tmp.c:10808: at print_backtrace: Backtrace
/tmp/v_1000/show_obj.16050823187957602812.tmp.c:10883: by v_segmentation_fault_handler
7f12179300f0 : by ???
Segmentation fault (core dumped)
```

or  sometimes works, shows scene.

```
.
.
map_Kd = textures/Wood_Tower_Col.jpg
map_Bu = p  textures/Wood_Tower_Nor.jpg
init_render_data DONE!
```

**Comment by Wertzui123** [comment]
This may be related to: https://github.com/vlang/v/commit/07d5612347b408b0933a02c893d6122135f2b374

**Comment by splace** [comment]
timing looks right, i only know it was happening yesterday and wasn't a week or so ago. i will try to revert and see.

**Comment by splace** [comment]
looking more like the culprit, since even though png files dont cause a crash, they and jpg (when they don't segfault) are actually coming out oddly scrambled, looks like channels are not arranged right? which was involved with the commit, (they're gray scale/transparent.)


![image](https://user-images.githubusercontent.com/1234848/194779356-e55ce258-1fda-455d-b516-675f85208aa6.png)

**Comment by splace** [comment]
FYI @locriacyber

@Wertzui123 it does seem to be there...

old

```
flag := C.STBI_rgb_alpha
res.data = C.stbi_load_from_memory(buf, bufsize, &res.width, &res.height, &res.nr_channels,
flag)
```

new

```
res.data = C.stbi_load_from_memory(buf, bufsize, &res.width, &res.height, &res.nr_channels,desired_channels)

```

took a stab; looked odd, so just removed the desired_channels and reverted to the flag. i guess this worked, at all, because the desired_channels just sometimes happens to be valid flag enum. (shame for C's lack of typing.) of course when it isn't anything could happen.

![image](https://user-images.githubusercontent.com/1234848/194780139-fc8ba6a9-e8c1-4cc5-bf35-052c3414243b.png)

**Comment by Wertzui123** [comment]
I wonder why there was the commit in the first place. It already looked pretty weird when I saw it, but I just thought I didn't get the logic behind it.

**Comment by spytheman** [comment]
@splace please test with V after 3c25f50, which reverts the change. Also, can you please upload your example somewhere, so that we could test in the future with it for regressions?

**Comment by splace** [comment]
@spytheman  did, works.

but, as for a test, i'll start new issue, maybe its not that simple.
