### ISSUE TITLE
image comparison for powerful testing.

### ISSUE THREAD

**Issue by splace** [vlang/v#16024]
#16000   notice this wasn't deterministic, sometimes seg-faulted sometimes not, so potentially some hardware might never seg-fault, and the test based on this would always pass. is the seg-fault issue actually for sokol anyway, with the issue in v being how the image looked?

so the most general test would be to compare output images.

on the plus side, i think it would only require a minuscule image, so would not be that slow.

**Comment by splace** [comment]
@spytheman 

i will research whats available in some kind of image characterisation (image perception hashing?) seems like it should exist.

even some sort of simple subdivision then averaging and comparing with a range would have worked #16000

seems like it could work with internal and shader captured images.

**Comment by splace** [comment]
i will ask if can work on this as a side/community project.  i would be learning v, but was intending to start by playing with go2v.

**Comment by spytheman** [comment]
V already has a tool `v gret` that does image comparisons. We just need an example, that is easy to render, and produces a stable picture (no animations preferably).

**Comment by spytheman** [comment]
Perhaps one of the pictures used as textures in your original example would work?

**Comment by spytheman** [comment]
> is the seg-fault issue actually for sokol anyway, with the issue in v being how the image looked?

Probably yes, I have not dig deep enough to find out. I just noticed that many people complained, and it also fails a sokol assertion on macos for the `ui` rectangle example, so I reverted the commit.

**Comment by splace** [comment]
OK cool, i will just check quickly for a small image i own, that causes this.

**Comment by spytheman** [comment]
> OK cool, i will just check quickly for a small image i own, that causes this.

Thanks.

**Comment by splace** [comment]
notice; png format, that never segfaulted, but image was wrong. haven't checked it causes the problem, seems it is really likely and would have to be confirmed by someone else at some point anyway.

![skull](https://user-images.githubusercontent.com/1234848/194871122-00e1a6cf-8d2e-4029-9d13-642e5c58d38a.png)

**Comment by splace** [comment]
remembered this, might be useful, lots of small images in various formats/channels/bit-depths.

[image_zoo.zip](https://github.com/vlang/v/files/9747562/image_zoo.zip)
