### ISSUE TITLE
compile custom module,but nothing happen

### ISSUE THREAD

**Issue by tonylinyy** [vlang/v#161]
here is sample code:
module mymodule

fn add(x,y int) int {
    return x+y
}
then: v ./mymodule.v
but,nothing happen
in main module import mymodule
got a panic:
V panic: /Users/alex/code/lang//mymodule doesnt exist

**Comment by medvednikov** [comment]
After I release 0.0.2 with the panic fixed, try creating `mymodule` dir and then run

`v -lib mymodule`

**Comment by medvednikov** [comment]
0.0.2 is out, please try it.

**Comment by tonylinyy** [comment]
I tried,it works,so exciting...
I found the custom module will be comiled to /var/tmp/lang/vlib,It is ok now
may be we can  set the VPATH in the future,just like GOPATH :)

**Comment by medvednikov** [comment]
Of course, it will be flexible. I literally built this this morning :)
