### ISSUE TITLE
[GLFW] Cannot refer to unexported field

### ISSUE THREAD

**Issue by Poulpy** [vlang/v#1611]
**V version:** 
0.1.17

**OS:** 
Debian 9.8

**What did you do?**
```
import glfw
import gg

fn main() {
	glfw.init()
	mut game := gg.new_context(gg.Cfg {
			width: WinWidth
			height: WinHeight
			use_ortho: true
			create_window: true
			window_title: 'V Tetris'
			window_user_ptr: game
		})
	game.window.set_user_ptr(game)
	println('x ${game.window.get_cursor_pos().x} ; y : ${game.window.get_cursor_pos().y}')
}

```
**What did you expect to see?**
The positions to be printed out.

 
**What did you see instead?**
`cannot refer to unexported field 'x' (type 'glfw.Pos')`

The Pos struct is maybe missing a `pub:` ?

**Comment by Danil-Lapirow** [comment]
@medvednikov, what do you think?

**Comment by medvednikov** [comment]
Fixed.
