### ISSUE TITLE
compiler: generic RAM eater

### ISSUE THREAD

**Issue by esquerbatua** [vlang/v#1612]
**V version:** 
V 0.1.17
at commit: [772c0c3f931e23df7a0d51bbbc6923cbde3129a7](https://github.com/vlang/v/commit/772c0c3f931e23df7a0d51bbbc6923cbde3129a7)
**OS:**
Ubuntu 18.04.3
Linux 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**What did you do?**
compile next code:

```
struct Generic {
	text string
}

pub fn test_generic() {
	generic := create_generic<Test>()
}

pub fn create_generic<T>() Generic<T> {
	return Generic{'generics'}
}

pub fn (g Generic<T>) hello() {
	println(g.text)
	say_hi<T>()
}

pub fn say_hi<T>() {
	println('hi')
}

```

**What did you expect to see?**
Compilation success
 
**What did you see instead?**
V compilator eats all RAM

**Comment:**
Perhaps it is not yet fully implemented?

**Comment by spytheman** [comment]
Strange, I can not reproduce this error:
``` shell
0[09:58:50] /v/v $ cat x.v 
struct Generic {
text string
}

pub fn test_generic() {
generic := create_generic()
}

pub fn create_generic() Generic {
return Generic{'generics'}
}

pub fn (g Generic) hello() {
println(g.text)
say_hi()
}

pub fn say_hi() {
println('hi')
}
0[09:59:51] /v/v $ lsb_release -a 2>/dev/null |grep Description
Description:    Ubuntu 16.04.3 LTS
0[09:58:52] /v/v $ git rev-parse --short  --verify HEAD
772c0c3
0[09:58:56] /v/v $ ./v -o v compiler
0[09:59:01] /v/v $ ./v x.v 
x.v:6 `generic` declared and not used
1[09:59:02] /v/v $ 
```

**Comment by esquerbatua** [comment]
@spytheman Sorry, github eated the code inside 

> <>

**Comment by Rendims** [comment]
Can reproduce the issue with the updated/fixed code now.

I don't know how the parser works but I have identified that this loop gets stuck advancing and reversing the scanner forever (until all RAM is gone).

https://github.com/vlang/v/blob/87216cff63c2381a35cd0f365a448f9f567859af/compiler/fn.v#L351-L383

**Comment by spytheman** [comment]
Yes, this is a problem - I could reproduce it with the updated source code.

**Comment by spytheman** [comment]
A minimum case is:
```
pub fn a() {
  b<Tx>()
}
```

**Comment by medvednikov** [comment]
Fixed.
