### ISSUE TITLE
decomposition of fixed size array does not work

### ISSUE THREAD

**Issue by Uhrbaan** [vlang/v#16139]
V 0.3.1 e863191
Linux 5.15.71-1-MANJARO

I was following the docs, section Function 2/ variable arguments, an tried to decompose a fixed sized array and got an error
~~~v
fn sum(a ...int) int {
    mut total := 0
        for x in 
            total += x
        }
    return total
}
fn main()
{
    arr := [1, 2, 3, 4]!
    sum(...arr)
}
~~~

got error:
~~~
./hello.v:4:9: error: decomposition can only be used on arrays
    2 | {
    3 |     arr := [1, 2, 3, 4]!
    4 |     sum(...arr)
      |            ~~~
    5 | }
    6 |
~~~
I guessed it was unintended behaviour

anyway, first time ever reporting a bug, hope I did it right :)

**Comment by shove70** [comment]
V is not designed to support the decomposition of fixed arrays, so it is not a bug 😄 

But as a ```feature request```, it may be feasible.

**Comment by Delta456** [comment]
I think it is intended for fixed arrays not to be decomposed. You can convert your fixed array into normal array if you want to achieve this.

**Comment by Delta456** [comment]
I am gonna try implementing this.

**Comment by Delta456** [comment]
After having a discussion with @spytheman, we concluded that:
- Implementing this feature will complicate the parser and the performance will drop from implicit conversion,
- The decomposition of fixed size array can be achieved by `sum(...arr[..])` which Is an explicit conversion.
- There will be a checker error for implicit conversion and will suggest converting the fixed array to a dynamic array as stated above.
