### ISSUE TITLE
Possibility to run certain tests from file

### ISSUE THREAD

**Issue by i582** [vlang/v#16137]
## Why

In languages such as Go and PHP, it is possible to run specific tests. This is useful, for example, when we only want to run failed tests from the IDE. Now, in V, there is no such possibility and you can only run entire files, which is inconvenient.

## What

For the `v test` command, add the `-filter` flag, which will accept a regular expression that will filter the tests to be run.

**Comment by JalonSolov** [comment]
It's already there.  Use the `-run-only` option, like so:
```
v test -run-only test_name,test_name_2,test_name_3 file_test.v
```
