### ISSUE TITLE
Compile time $if

### ISSUE THREAD

**Issue by esquerbatua** [vlang/v#1613]
Compile time $if for non -prod builds, for debugging purposes, like put println of variables.

I don't know if that it's planned.

**Comment by medvednikov** [comment]
`$if debug {` ?

**Comment by elimisteve** [comment]
Awesome idea!

**Comment by medvednikov** [comment]
Done. This program will print "hello" if built with `-debug`:

```
fn main() {
  $if debug {
    println('hello')
  }
}
```

**Comment by iredmail** [comment]
Could you document it somewhere?

**Comment by esquerbatua** [comment]
A lot of thanks!!

**Comment by medvednikov** [comment]
Documentation has been updated.
