### ISSUE TITLE
`$tmpl`: single quotes in template files are not handled well (error message confusing for those not knowing how it works)

### ISSUE THREAD

**Issue by bogen85** [vlang/v#16154]
# Environment

OS: linux, "Arch Linux"
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
CC version: cc (GCC) 12.2.0

getwd: /home/shared-development/vlang/v-issue/tmpl
vroot: /home/shared-development/vlang/vlang-fpc-backend
vexe: /home/shared-development/vlang/vlang-fpc-backend/v
vexe mtime: 2022-10-21 20:24:09
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.1 71bff21.8beaee4

Git version: git version 2.38.1
Git vroot status: weekly.2022.42-72-g8beaee48-dirty (8 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

# Minimum code

**What did you do?**

`tmpl_example1.v`
```v
module main

pub struct SomeThing {
pub:
	m map[string]string
}

fn (s SomeThing) someval(what string) string {
	return s.m[what]
}

fn (s SomeThing) template () string {
	return $tmpl('template.in')
}

fn main () {
	mut sm := map[string]string{}
	sm["huh"] = "monkey"
	sm["hah"] = "parrot"

	s := SomeThing {sm}
	println(s.template())
}
```

With `template.in` as:
```text
someval: @{s.someval("huh")}

someotherval: @{s.m["hah"]}
```
It works.

With `template.in` as:
```text
someval: @{s.someval('huh')}

someotherval: @{s.m['hah']}
```
It does not...

**What did you expect to see?**

I expected it to compile and run.
When run I expected to see:

```text
someval: monkey

someotherval: parrot
```
 
**What did you see instead?**
```text
internal_memory:11:16: error: invalid character `\`
```

**Observations and comments**

As an end V programmer (not a V developer) looking at  `@{...}` it is not obvious to what kind of mechanism is used to make that work.

Since V allows for both single and double quoting of strings, then I would expect either to work.

If both are not expected to work, then it needs to be documented as to which one to use, and to have an error message that indicates I used the wrong quoting character.

But, once again, as an end V programmer (not a V developer) I would expect both to just work, and if the documentation said other wise (that only one of the works), I would find that odd.

**Comment by kahsa** [comment]
`$tmpl` is very useful. But it is not yet complete. I hope it will be improved more.

**Comment by bogen85** [comment]
> `$tmpl` is very useful. But it is not yet complete. I hope it will be improved more.
> 
> https://github.com/vlang/v/pull/9052/files The code was originally written for vweb, I didn't know it. No wonder the source code was uncomfortable with the code assuming html.

Agreed. Currently is still very useful and I'll be using it. It is a bit of minefield, agreed.... But as long as one knows what to avoid, it is very powerful, and I'll use it anyways.

But yes, a lot to fix with it. Thanks for cataloging the issues with `$tmpl`.
