### ISSUE TITLE
Builder error caused by variable name of array

### ISSUE THREAD

**Issue by EvgenHi** [vlang/v#16165]
**V doctor:**
```
OS: linux, Pop!_OS 22.04 LTS
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
CC version: cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

getwd: /home/evgen/Desktop/playground
vmodules: /home/evgen/.vmodules
vroot: /home/evgen/Desktop/v
vexe: /home/evgen/Desktop/v/v
vexe mtime: 2022-10-23 11:14:40
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.1 721dbec.3f03520

Git version: git version 2.34.1
Git vroot status: weekly.2022.42-32-g3f035205
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg playground.v`
```v
module main

fn main() {
	array := []int{len: 4, init: it}
	println(array)
}
```

**What did you expect to see?**

[0, 1, 2, 3]

**What did you see instead?**
```
==================
/tmp/v_1000/playground.10460106522849273426.tmp.c:12105: error: lvalue expected
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```
**Additional Information**
It looks like if i literally name a variable "array" (other names don't seem to cause errors) and initialize it like this, i get a builder error

**Comment by EvgenHi** [comment]
Also there would be another error if I make array fixed-size

**Code:**
```
module main

fn main() {
	array := [3]int{init: it}
	println(array)
}
```
**Error:**
```
==================
/tmp/v_1000/playground.9436549357264114873.tmp.c:12103: error: cannot convert 'typedef struct array' to 'int *'
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.
...
```

**Comment by shove70** [comment]
"array" should indeed be a reserved word, and it is easy to fix it, but there are too many test cases that use "array" as the function parameter name, and I don't know whether to fix it.

@spytheman , what's your opinion?  thanks.

**Comment by JalonSolov** [comment]
I vote that it should be fixed.  Seems like an oversight.

**Comment by spytheman** [comment]
> "array" should indeed be a reserved word, and it is easy to fix it, but there are too many test cases that use "array" as the function parameter name, and I don't know whether to fix it.
> 
> @spytheman , what's your opinion? thanks.

Sorry for not answering earlier, I just saw the question.
@yuyi98 already fixed it by escaping.

In general escaping in the output of the backend (or prefixing) is better, since these problems also occur for other common words, like `string`, `int`, `long` etc.

**Comment by shove70** [comment]
Thanks!  😄 

I see! Minimize the reserved word set, leaving users more choices and freedom!
