### ISSUE TITLE
Conversion from []byte to string failed

### ISSUE THREAD

**Issue by Blank-c** [vlang/v#16169]
**V version: V 0.3.1 e863191** 
**OS: windows, Microsoft Windows 10 Pro v19043 64-bit** 

**What did you do?**
Used `.bytestr()` on a function that returned `[]byte`

**What did you expect to see?**
Successful conversion
 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/94945186/197398246-6c464ddf-2649-4978-83d4-370aedb9a0e1.png)

**Comment by JalonSolov** [comment]
Workaround is to change your type to `[]u8]` instead of `[]byte`.  It _should_ work on both, but...

**Comment by Blank-c** [comment]
hmm, would try that
