### ISSUE TITLE
no error given for `!type(expr)` type casr

### ISSUE THREAD

**Issue by Delta456** [vlang/v#16176]
**V version:** 
**OS:** 

**What did you do?**
```v
_ = !bool(true)
```

**What did you expect to see?**
An error saying `casting to result type is forbidden`

 
**What did you see instead?**
 No error

**Comment by shove70** [comment]
Literally, there is a certain ambiguity:

! bool(true)

"!" It seems that it can be understood as ```logical non```, so ```parser``` may understand it as a PrefixExpr,

So the output is ```false```

**Comment by spytheman** [comment]
There is no ambiguity - `!bool(x)` means only cast x to a bool, then invert the result.

Imho `!type` can only be a result type of an expression, and not something used as a cast.

I am not sure it is a good first issue for someone that is not very familiar with the compiler and the language.

**Comment by shove70** [comment]
After looking at the ast file, it is the ```parser``` that understands ```!bool``` as a logical non,
No wonder the cases in ```vlib/v/checker/checker.v``` are not triggered.

```
"right":	[{
	"ast_type":	"PrefixExpr",         // =>  prefix
	"op":	"token:18(!)",                // =>  invert
	"right":	{
		"ast_type":	"CastExpr",
		"typ":	"bool",
		"ityp":	18,
		"typname":	"bool",
		"has_arg":	false,
		"arg":	{
			"ast_type":	"EmptyExpr"
		},
		"expr_type":	null,
		"expr":	{
			"ast_type":	"BoolLiteral",
			"val":	true,
			"pos":	{
				...
			}
		},
		"pos":	{
			...
		}
	},
	"right_type":	null,
	"or_block":	{
		...
	},
	"is_option":	false,
	"pos":	{
		...
	}
}],
"right_types":	[],
"is_static":	false,
"is_volatile":	false,
"is_simple":	false,
"has_cross_var":	false,
"pos":	{
"line_nr":	0,
"last_line":	0,
"pos":	2,
"len":	2
},
"comments":	[],
"end_comments":	[]
}]
```

What do we do 😄

**Comment by Delta456** [comment]
No need to have an error for this.
