### ISSUE TITLE
v-0.1.17 running on windows10 REPL does not work

### ISSUE THREAD

**Issue by fenginsc** [vlang/v#1620]
**V version:v-0.1.17** 
**OS:windows10** 

**What did you do?**
input println('hello world')

**What did you expect to see?**
hello world
 
**What did you see instead?**
nothing

**Comment by Delta456** [comment]
Have you tried using WSL? It works for me

**Comment by fenginsc** [comment]
> Have you tried using WSL? It works for me

no,not using it.The previous v version was available on the CMD

**Comment by vitalyster** [comment]
Already fixed after 0.1.17 release, upgrade to latest master

**Comment by Delta456** [comment]
For WSL follow installation instructions for Ubuntu

**Comment by fenginsc** [comment]
> Already fixed after 0.1.17 release, upgrade to latest master

@vitalyster thanks!Problem solved.just upgrade to the latest master.
