### ISSUE TITLE
smart cast of mutable interface variables does not give checker error

### ISSUE THREAD

**Issue by Trakis196** [vlang/v#16200]
**V version:** V 0.3.1 779cc3382529bc03b0a84ec470a0eca4cfe7ece7
**OS:** Arch Linux

**What did you do?**
```v
import json

interface Foo {
    a int
}

struct Bar {
    a int 
}

fn main() {
    foo := Foo(Bar{})
    if foo is Bar {
        println(json.encode(foo)) // {"a": 0}
    }

    mut foo_mut := Foo(Bar{})
    if foo_mut is Bar {
        println(json.encode(foo_mut)) // cgen error
    }
}
```
**What did you expect to see?**
`error: casting a mutable interface or sum type requires 'if mut x is ...'`
from the docs on sum types
> If `w` is a mutable identifier, it would be unsafe if the compiler smart casts it without a warning. That's why you have to declare a `mut` before the `is` expression.

**What did you see instead?**
`cgen error: json: main.Foo is not struct`

**Comment by kahsa** [comment]
```v
 if mut foo_mut is Bar {
```
works as you expect.
Then in this case checker error should be.

But just my personal opinion.
```v
    mut foo_mut := Foo(Bar{})
    if mut foo_mut is Bar {
```
This feels very weird to me.

**Comment by spytheman** [comment]
I agree, it should have been a checker error; it should not go into cgen.

**Comment by kahsa** [comment]
Suggestion: In this case, since it is obvious that the `mut_foo` variable is mutable, how about making `if foo_mut is Bar {` legal and having the compiler implicitly convert it as `if mut foo_mut is Bar {` behind the scenes?

**Comment by kahsa** [comment]
Ah, well, but it's not impossible to see this as the same thing...
```v
fn foo(mut val string){}

fn main(){
	mut s := 'abc'
	foo(mut s)
}
```
