### ISSUE TITLE
builder error: cannot import module

### ISSUE THREAD

**Issue by jareer12** [vlang/v#16206]
**V version:** 
**OS:** Ubuntu 22.04.1 LTS

**What did you do?**
Create a module

**What did you expect to see?**
Expected the module to import without errors
 
**What did you see instead?**

```v
./vlang.v:3:1: builder error: cannot import module "mymodule" (not found)
    1 | module main
    2 | 
    3 | import mymodule 
      | ~~~~~~~~~~~~~~~
    4 | 
    5 | fn main() {
```

vlang.v
```
module main

import mymodule 

fn main() {
}
```

module.v
```v
module mymodule

pub fn test(){
	println("test")
}
```

**Comment by KevinDaSilvaS** [comment]
Hi
Have you tried to cread a folder named module and then drop your module.v inside that folder?
Example in documentation: https://github.com/vlang/v/blob/master/doc/docs.md#create-modules
