### ISSUE TITLE
A problem in Tetris

### ISSUE THREAD

**Issue by kingofoz** [vlang/v#1622]
**V version: 0.17
**OS: Mac OS X(MacBook Air)

**What did you do?**
Run tetris

**What did you expect to see?**
Tetris should work well.
 
**What did you see instead?**
There is a weird problem in Tetris. Please see the green object in the ellipse. When I press the "UP" arrow button, the green object doesn't change its shape and just attach to the red  middle object.
![1](https://user-images.githubusercontent.com/9476604/63154194-a8919b00-c042-11e9-98cb-c27a35f4936e.png)

**Comment by kingofoz** [comment]
Hi @medvednikov Can you please take a look of this issue?

**Comment by kingofoz** [comment]
Is anybody aware of this issue?

**Comment by medvednikov** [comment]
@kingofoz looks like there's a bug with the collision check.

Should be a quick fix, I don't have  time to work on this right now, sorry.

**Comment by kingofoz** [comment]
Hi @medvednikov No problem. I just report bugs I found. Please fix it when you have time and let me know.

**Comment by kingofoz** [comment]
any update? @medvednikov 
I really like this game. :-)

**Comment by Rhymond** [comment]
@kingofoz is it still a bug?

**Comment by kingofoz** [comment]
@Rhymond Yes.

**Comment by Rhymond** [comment]
@kingofoz could you please explain me how I can replicate this? I tried to do it with no luck.

**Comment by kingofoz** [comment]
@Rhymond Hi buddy, 
After the game starts, you just press "DOWN" arrow button to put some objects in the middle area. After some objects are put, you try to move some new objects in the left area and try to change their shapes. Then you should reproduce the bug.

**Comment by kingofoz** [comment]
Hi @Rhymond,
After the game starts, you just press the "DOWN" arrow button to put some objects in the middle area of the game. After some objects are put, you just move some new objects into the left area of the game and try to change their shapes. Then you should reproduce the bug.

**Comment by medvednikov** [comment]
I think I fixed it. Can you try again?

**Comment by kingofoz** [comment]
Hi @medvednikov,
I get this error with the latest V:
YingjundeMacBook-Air:tetris yingjun$ v tetris.v 
vlib not found, downloading it...
vlib not found. It should be next to the V executable. 
Go to https://vlang.io to install V.

Can you tell me what to do now?

**Comment by bjhanfeng** [comment]
> Hi @medvednikov,
> I get this error with the latest V:
> YingjundeMacBook-Air:tetris yingjun$ v tetris.v
> vlib not found, downloading it...
> vlib not found. It should be next to the V executable.
> Go to https://vlang.io to install V.
> 
> Can you tell me what to do now?

Setting environment variables VEXE

**Comment by kingofoz** [comment]
hi @bjhanfeng,
Thanks buddy. It works. But I find a new bug. @medvednikov 
![屏幕快照 2019-11-15 下午3 55 27](https://user-images.githubusercontent.com/9476604/68926648-ff814a80-07c0-11ea-9616-23c4d1452789.png)
Please see the purple object in the red ellipse, its shape cannot be changed when it is falling. If the purple object is falling in the left side of the game area, its shape can be changed normally.

**Comment by medvednikov** [comment]
I think that’s how it’s supposed to work.

Does anyone have the original tetris game? :D

**Comment by Rhymond** [comment]
Just tried to play couple of different versions of tetris and @medvednikov is right, it's how it's supposed to be. I would expect too that piece should be pushed to the right side, but in reality it's not.
https://www.lumpty.com/amusements/Games/Tetris/tetris.html
^ try it

**Comment by medvednikov** [comment]
Thanks for testing it @Rhymond. My intuition was right. I played lots of Tetris back in the day :)

**Comment by kingofoz** [comment]
I see. Thanks to all. By the way, I don't understand why objects have different transforming behaviors when they are falling in the right side and the left side of the game area.
