### ISSUE TITLE
Make (now) fails unless v is found on $PATH

### ISSUE THREAD

**Issue by nealcrook** [vlang/v#1624]
**V version:** 

54b3c4d2c5186fad68c87cd18dc4327924c5da4b

**OS:** 
Linux/Ubuntu
**What did you do?**
$ git pull
$ make

**What did you expect to see?**
successful build

 
**What did you see instead?**
$ make
curl -o v.c -LsSf https://raw.githubusercontent.com/vlang/vc/master/v.c
cc -std=gnu11 -w -o v v.c -lm
v -o v compiler
make: v: Command not found
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 127

I changed my Makefile from "v -o v compiler" to "./v -o v compiler". The changes to the Makefile seem to assume that v is installed (in which case an old version of v would be used for building the compiler) or that . is on $PATH (historically considered a Bad Thing)

rgds
Neal

**Comment by medvednikov** [comment]
Thanks, fixed
