### ISSUE TITLE
string interpolation can not handle `unsafe{}` inside

### ISSUE THREAD

**Issue by kahsa** [vlang/v#16240]
**V version: 0.3.1 0ca5b1f** 
**OS: ArchLinux** 

**What did you do?**
```v
enum Foo{
	abc
	def
}

fn main(){
	println('Foo = {Foo.def}')
	println('Foo = {unsafe{Foo(1)}}')
}
```

**What did you expect to see?**
No error
 
**What did you see instead?**
```
bug.v:8:24: error: unexpected token `$2`, expecting `{`
    6 | fn main(){
    7 |     println('Foo = {Foo.def}')
    8 |     println('Foo = {unsafe{Foo(1)}}')
      |                           ^
```

**Comment by shove70** [comment]
```v
enum Foo{
	abc
	def
}

fn main(){
	println('Foo = {Foo.def}')
	println('Foo = {unsafe { Foo(1) }}')
                                ^    // => a space is required
}
```

If there is no space, it will be interpreted as interpolation

**Comment by kahsa** [comment]
Thanks for workaround.
Hmm then the error message is not appropriate.

**Comment by kahsa** [comment]
@medvednikov What is new specification in this case?

**Comment by medvednikov** [comment]
Should it be allowed. Is it needed to embed unsafe statements into strings?

I think it's better to use a variable here.

**Comment by JalonSolov** [comment]
The documentation needs to be clarified if _only_ variable names are supposed to be allowed.  However, this conflicts with my example in discord that you said should work:
```v
println('He has {b} book{if b == 1 {''} else {'s'}}.')
```
That's an `if` statement, not a variable, inside the outer `{}`.

And if `if` will be allowed, it seems like pretty much _any_ V code should be allowed.

**Comment by medvednikov** [comment]
That `if` statement is fine @JalonSolov. I just don't like seeing unsafe statements there. Although if we allow one and don't allow the other, it gets complicated.

**Comment by JalonSolov** [comment]
I don't like seeing unsafe anywhere, but... we have it, and it's valid V code.  :man_shrugging:

**Comment by kahsa** [comment]
`println('Foo = ${unsafe{Foo(1)}}')` have worked.
Suddenly it raises an error today.

**Comment by medvednikov** [comment]
@kahsa indeed. Looks like there was no test for it. Will fix.

**Comment by shove70** [comment]
@kahsa sorry, I misunderstood the rules
