### ISSUE TITLE
raw string Map key emits error

### ISSUE THREAD

**Issue by srackham** [vlang/v#16249]
**V version:** V 0.3.1 c6158e4
**OS:** linux, Ubuntu 22.04.1 LTS (VM)

**What did you do?** Executed the following code:
```v
s := {
    r'x': ''
}
println(s)
```

**What did you expect to see?** `{'x': ''}`

 
**What did you see instead?**
```
$ v run bug.v
bug.v:2:6: error: unexpected string `x`, expecting `:`
    1 | mut s := {
    2 |     r'x': ''
      |      ~~~
    3 | }
    4 | println(s)
```

**Comment by Delta456** [comment]
Fixed in https://github.com/vlang/v/commit/5fe4888874beadbdaf3fd17f5bc8bbc7f8766122
