### ISSUE TITLE
return sum types `option/result` in `if/match` statement does not work.

### ISSUE THREAD

**Issue by kahsa** [vlang/v#16255]
**V version: 0.3.1 93d765e** 
**OS: ArchLinux** 

**What did you do?**
```v
type Foo = string | int 

fn foo() !Foo{
	return match true{
		true { 1 }
		else { '' }
	}
}

fn main(){
	f := foo() or { return }
	dump(f)
}
```

**What did you expect to see?**
`f: Foo(1)`
 
**What did you see instead?**
`f: unknown sum type value`

**Comment by DevrosTheOne** [comment]
```return``` has problem with multiple options using match statement.  If you use ```return``` on each branch it works as expected.  

```v
type Foo = int | string

fn foo() !Foo {
	match true {
		true { return 1 }
		else { return '' }
	}
}

fn main() {
	f := foo() or { return }
	dump(f)
}

[/Users/srecko/Project/avlang/w4oct/sumtype2.v:12] f: Foo(1)
```
