### ISSUE TITLE
map.to_array()

### ISSUE THREAD

**Issue by kahsa** [vlang/v#16268]
It would be useful to return it as an array of anonymous structures.

**Comment by ArtemkaKun** [comment]
Hi, accordingly to a 0.3.2 release - `A new maps module, similar to existing arrays. It has generic filter, flatten, invert, to_map, to_array, from_array
functions.`

**Comment by kahsa** [comment]
Wow didn't know that, thanks for letting me know.

**Comment by Wajinn** [comment]
> ...to_map, to_array, from_array functions.
Yes, the features are quite nice.
