### ISSUE TITLE
negative array index should not compile

### ISSUE THREAD

**Issue by astariul** [vlang/v#1628]
V version: **0.1.18**
OS: **Ubuntu 18.04.2 LTS (Bionic Beaver)** 

### What did you do?

```
fn fibo4m(nums mut []int, limit int) []int {
    if nums[-1] > limit {
        return nums
    }
    nums << nums[-2] + nums[-1]
    return fibo4m(mut nums, limit)
}
```

### What did you expect to see?

No error (or not a c error)

 
### What did you see instead?

>.ex2.c: In function ‘fibo4m’:
.ex2.c:3487:9: error: incompatible types when returning type ‘array_int * {aka struct array *}’ but ‘array_int {aka struct array}’ was expected
 return  nums ;
         ^...
(Use `v -debug` to print the entire error message)
>
> V panic: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by AtjonTV** [comment]
When you take in a variable with `mut` it will be a pointer. You would need to de-reference it before returning
```
if nums[-1] > limit {
        return *nums
}
```

**Comment by AtjonTV** [comment]
And fun note: `OS: Debian 18.04.2 LTS (Bionic Beaver)`
Is not a thing, I guess you ment `OS: Ubuntu 18.04.2 LTS (Bionic Beaver)` ;D

(I am on elementaryOS 5.0 which is also based on Ubuntu 18.04 LTS)

**Comment by astariul** [comment]
Thanks for the input. I will try it as soon as possible and close the issue if it's working.

I'm not really at ease with pointers, and I didn't see it mentioned in the documentation. Did I miss it?

**Comment by astariul** [comment]
Also i just saw I can't use negative index ^^

**Comment by medvednikov** [comment]
This is actually a bug. You shouldn't have to dereference `nums` here.

Also negative index should not compile.

**Comment by astariul** [comment]
Here is the full code to reproduce the error :

```
fn fibo4m(nums mut []int, limit int) []int {
    if nums[nums.len - 1] > limit {
        return nums
    }
    nums << nums[nums.len - 2] + nums[nums.len - 1]
    return fibo4m(mut nums, limit)
}

fn main() {
    mut start := [1, 2]
    fibo := fibo4m(mut start, 4000000)
    mut summ := 0
    
    for f in fibo {
        if f % 2 == 0 {
            summ += f
        }
    }
    println('Sum is $summ')
}
```
