### ISSUE TITLE
An error occurred when running 'v up', 'v self' and 'v doctor'

### ISSUE THREAD

**Issue by babybabyCloud** [vlang/v#16297]
**V version:V 0.3.1 c590c82** 
**OS:Linux username 5.10.0-amd64-desktop #20.00.50.29-release SMP Tue Sep 6 14:36:16 CST 2022 x86_64 GNU/Linux** 

**What did you do?**
Execute 'v up'

**What did you expect to see?**
V updates itself successfully and installs the newest version
**What did you see instead?**
An error message like below

```bash
username@username:~/workspace/python/ssq$ v u
cannot compile `/home/username/.v/v/cmd/tools/vup.v`: 
/tmp/v_1000/../../../../../../home/username/.v/v/vlib/builtin/string.v:1088: warning: implicit declaration of function 'opt_ok2'
tcc: error: undefined symbol 'opt_ok2'
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```
**Other information**
cc and GCC version:
```bash
username@username:~/workspace/python/ssq$ cc --version
cc (Uos 8.3.0.9-1+eagle) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

username@username:~/workspace/python/ssq$ gcc --version
gcc (Uos 8.3.0.9-1+eagle) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
````
CPU:
AMD Ryzen 7 3800X 8-Core Processor

PS: The same error message I've gotten when running 'v self' and 'v doctor'

**Comment by JalonSolov** [comment]
First, you have an ancient version of gcc - current is 12.2.0.  Might want to look into updating that.

Second, you don't have the most recent version of V, either.  Which makes sense if you're trying to run `v up`.

I don't know how you installed V originally, but I would suggest starting over, using the preferred install method:  https://github.com/vlang/v#installing-v-from-source

**Comment by babybabyCloud** [comment]
> First, you have an ancient version of gcc - current is 12.2.0. Might want to look into updating that.
> 
> Second, you don't have the most recent version of V, either. Which makes sense if you're trying to run `v up`.
> 
> I don't know how you installed V originally, but I would suggest starting over, using the preferred install method: https://github.com/vlang/v#installing-v-from-source

Thank you so much.
It works now after compiling from the source code.
