### ISSUE TITLE
`v fmt` doesn't know about new interpolation way (after V 0.3.2)

### ISSUE THREAD

**Issue by ArtemkaKun** [vlang/v#16295]
V 0.3.2 release says - `New simplified string interpolation: println("Hello, {name}!"). It will be the only way, old syntax (${name} and name) will be deprecated.`

Original code - `println("\'{key}\': {value}")`

Code after `v fmt -w .` - `println('\'$key\': $value')`

**Comment by yuyi98** [comment]
vfmt for the new string interpolation can not work now.

**Comment by shove70** [comment]
related PR#16308

**Comment by spytheman** [comment]
@ArtemkaKun please try with latest V, I've just merged #16308 .

**Comment by ArtemkaKun** [comment]
> @ArtemkaKun please try with latest V, I've just merged #16308 .

Will do

**Comment by ArtemkaKun** [comment]
Resolved by #16308
