### ISSUE TITLE
Lamdbas

### ISSUE THREAD

**Issue by GordonGgx** [vlang/v#163]
V is a great language. It would be great to have lamdba support. Thanks @medvednikov

**Comment by medvednikov** [comment]
Yes, it will :)

**Comment by GordonGgx** [comment]
That's great.

**Comment by GordonGgx** [comment]
@medvednikov I have an idea. On the type signature system of Haskell with function as parameter
```
fn say(age int) String{
      return 'I am '+age
}
fn call(fun:int->string){
     println(fun(25))
}

fn main(){
    // Now you can do that. 
    call(say)
    call(i -> "This is $i")
}
```
How do you like it?

**Comment by medvednikov** [comment]
Right now this works::

```
fn call(fun fn(int) string){
     println(fun(25))
}

call(say)
```

I haven't thought about lambda syntax yet.

**Comment by GordonGgx** [comment]
> Right now this works::
> 
> ```
> fn call(fun fn(int) string){
>      println(fun(25))
> }
> 
> call(say)
> ```
> 
> I haven't thought about lambda syntax yet.

Supporting anonymous functions?

**Comment by medvednikov** [comment]
I don't understand your question.

**Comment by ntrel** [comment]
I think given we have `if` expression syntax (where the last expression in the block is the result) - lambdas should look similar:
```rust
e := if test {e1} else {e2} // if expression

call(fn i {"This is $i"})
```
Equivalent to:
```rust
fn lambda(i T) {return "This is $i"} // function template
call(lambda)
```
(except T is not visible inside the body of lambda)

**Comment by ntrel** [comment]
Forgot to mention, the signature of `lambda` is inferred by:
1. Looking at the type of the first parameter of `call` to see what type `i` should be.
2. Looking at the body of `lambda` and taking the type R of the expression on the last line.
3. R is the return type of `lambda`.

**Comment by GordonGgx** [comment]
> I don't understand your question.

I just want to use haskell's type signature to describe lamdba.

**Comment by GordonGgx** [comment]
> I think given we have `if` expression syntax (where the last expression in the block is the result) - lambdas should look similar:
> 
> ```rust
> e := if test {e1} else {e2} // if expression
> 
> call(fn i {"This is $i"})
> ```
> 
> Equivalent to:
> 
> ```rust
> fn lambda(i T) R {return "This is $i"} // function template
> call(lambda)
> ```
> 
> (except T is not visible inside the body of lambda)

I think so.

**Comment by lutherwenxu** [comment]
The conversation has been moved to #1066.
