### ISSUE TITLE
V will not compile

### ISSUE THREAD

**Issue by ZWORX52** [vlang/v#16300]
**V version:** V 0.3.2 dddcf42
**OS:** Linux, Ubuntu 22.04.1 LTS (VM)

**What did you do?**
I attempted to run `make` to build and use v.

**What did you expect to see?**
Some make output, and v.
 
**What did you see instead?**
<details><summary>Click to see full output of cloning and build attempt</summary>
<pre><code>
[zworx52:~] $ git clone https://github.com/vlang/v
Cloning into 'v'...
remote: Enumerating objects: 132038, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (131/131), done.
remote: Total 132038 (delta 69), reused 91 (delta 38), pack-reused 131864
Receiving objects: 100% (132038/132038), 61.00 MiB | 19.45 MiB/s, done.
Resolving deltas: 100% (94171/94171), done.
[zworx52:~] $ cd v
[zworx52:~/v] master ± make
make fresh_vc
make[1]: Entering directory '/home/zworx52/v'
rm -rf ./vc
git clone --depth 1 --quiet --single-branch https://github.com/vlang/vc ./vc
make[1]: Leaving directory '/home/zworx52/v'
cd ./vc && git clean -xf && git pull --quiet
make fresh_tcc
make[1]: Entering directory '/home/zworx52/v'
rm -rf ./thirdparty/tcc
git clone --depth 1 --quiet --single-branch --branch thirdparty-linux-amd64 https://github.com/vlang/tccbin ./thirdparty/tcc
make[2]: Entering directory '/home/zworx52/v'
make[2]: Leaving directory '/home/zworx52/v'
make[1]: Leaving directory '/home/zworx52/v'
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
gcc -Wall -Werror -Wextra -std=gnu99 -w -o v1.exe ./vc/v.c -lm -lpthread 
./v1.exe -no-parallel -o v2.exe  cmd/v
==================
/tmp/v_1000/v2.exe.12344923376359998801.tmp.c:15050: error: assignment discards qualifiers from pointer target type
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
\==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

make: *** [GNUmakefile:109: all] Error 1
[zworx52:\~/v] master 2 ± gcc --version
gcc (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[zworx52:~/v] master ± 
</code></pre></details>

Please tell me if I am forgetting critical information. I am happy to give it!

**Comment by spytheman** [comment]
unset `VFLAGS` or remove `-Wall -Werror -Wextra` from it

**Comment by spytheman** [comment]
Another thing you can try is `./v1.exe -cg -no-parallel -o v2.exe  cmd/v` (note the `-cg`)

**Comment by ZWORX52** [comment]
Yes, CFLAGS had `-Wall -Werror -Wextra` -- whoops! Thanks so much!
(Perhaps this should be considered to be fixed, maybe by changing the `Makefile` or by making sure the C code output by V never triggers errors? That might be helpful! Or you could just put this fix in the install instructions, that works too ;) )

**Comment by medvednikov** [comment]
@ZWORX52 it used to be fixed, we even had a CI test for this. Not sure why it has warnings now.

**Comment by medvednikov** [comment]
Will fix.
