### ISSUE TITLE
Parse error of the new string interpolation: println('{s == 'hello'}'

### ISSUE THREAD

**Issue by yuyi98** [vlang/v#16318]
Parse error of the new string interpolation: println('{s == 'hello'}'

```v
fn main() {
	s := 'hello'
	println('{s == 'hello'}')
	println('{s != 'hello'}')

	n := 22
	println('{n >= 10}')
	println('{n <= 10}')
}

PS D:\Test\v\tt1> v run .
./tt1.v:3:18: error: unexpected name `hello`, expecting `,`
    1 | fn main() {
    2 |     s := 'hello'
    3 |     println('{s == 'hello'}')
      |                     ~~~~~
    4 |     println('{s != 'hello'}')
    5 |
```

**Comment by JalonSolov** [comment]
I see 2 things wrong with this.

First, the code between the outer `{}` is perfect valid V code.  Try this example:
```v
s := 'hello'
a := s == 'hello'
println(a)
```
The output is, as expected, `true`.

Second, the error message doesn't make sense.  Why is `,` expected?  `s == ,` is not valid in any case I can recall.

**Comment by yuyi98** [comment]
@JalonSolov  It's new string interpolation, `'{name}'`

**Comment by JalonSolov** [comment]
Sorry, I thought this was a PR, not a bug report.
