### ISSUE TITLE
playground needs to be updated to latest V

### ISSUE THREAD

**Issue by sbgatne** [vlang/v#16315]
**V version:** 
v playground
**OS:** 
win8.1

**What did you do?**
```v
b:=(print(10))
```
**What did you expect to see?**
void initialization not allowed.
 
**What did you see instead?**
```
code.v:1:1: warning: unused variable: `b`
    1 | b:=(print(10))
      | ^
/tmp/v_60000/../../../../../../box/code.v:1: error: declaration of void object
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.
```

**Comment by changrui** [comment]
```main.v:1:3: error: assignment mismatch: 1 variable(s) but `print()` returns 0 value(s)
    1 | a := print(1)
      |   ~~```

**Comment by JalonSolov** [comment]
I've changed the title to reflect the actual issue.

**Comment by medvednikov** [comment]
I've updated the playground, the issue seems to remain.
