### ISSUE TITLE
Some problems of new interpolation

### ISSUE THREAD

**Issue by shove70** [vlang/v#16321]
V 0.3.2 0e8d148

```v
f.mod2syms['{imp.mod.all_after_last('.')}.{sym.name}'] = sym.name
```
```
vlib/v/fmt/fmt.v:95:41: error: unexpected string `)}.`, expecting name
   93 |             f.mod2alias[sym.name] = sym.name
   94 |             f.mod2syms['{imp.mod}.{sym.name}'] = sym.name
   95 |             f.mod2syms['{imp.mod.all_after_last('.')}.{sym.name}'] = sym.name
      |                                                  ~~~~~
   96 |             f.mod2syms[sym.name] = sym.name
   97 |             f.import_syms_used[sym.name] = false
```

---------------------

```v
		ConstDecl {
			fields := node.fields.map(field_to_string)
			return 'const ({fields.join(' ')})'
		}
```
```
  625 |         }
  626 |         ConstDecl {
  627 |             fields := node.fields.map(field_to_string)
      |             ~~~~~~
  628 |             return 'const ({fields.join(' ')})'
  629 |         }
vlib/v/ast/str.v:329:25: error: unreachable code
  327 |             }
  328 |             if fields.len > 0 {
  329 |                 return '[]T{{fields.join(', ')}}'
      |                                     ~~~~~~~~~~
  330 |             } else {
  331 |                 return x.exprs.str()
```

------------------

```v
total_us := 1.2
println('{total_us:2.5f} MB/s')
```
```v run . ``` output:

```
{total_us:2.5f} MB/s
```

-----------------
```v
println('{@LINE}')
```
```v run . ``` output:

```
{@LINE}
```

To be continued

**Comment by shove70** [comment]
@yuyi98 Excuse me,

in scanner.v     Line1258 and Line1287:

```v
for i := s.pos + 1; i < s.text.len; i++ {
	if s.text[i] == `}` || (s.text[i] == `=` && (s.text[i - 1] in [`!`, `>`, `<`]
		|| s.text[i + 1] == `=`)) {
		// No } in this string, so it's not a valid `{x}` interpolation
		// `!=` `>=` `<=` `==`
		break
	}
	if s.text[i] in [`=`, `:`] {         =========>>>>>>  here, colon is excluded
		// We reached the end of the line or string without reaching "}".
		// Also if there's "=", there's no way it's a valid interpolation expression:
		// e.g. `println("{a.b = 42}")` `println('{foo:bar}')`
		is_valid_inter = false
		break
	}
}
```

Have the rules of the ```specifier``` also changed? If not, the logic for excluding ```colon``` may needs to be supplemented. Thank you ❤️ 

```
total_us := 1.2
println('{total_us:2.5f} MB/s')
```

**Comment by JalonSolov** [comment]
That code doesn't look correct.  It should only be looking for the matching `}` to end interpolation _or_ the matching quote to the opening quote for the string to tell that there was no matching `}`.  Looking for other characters won't work, since they could be between the `{}`.

**Comment by shove70** [comment]
@JalonSolov Thank you. I see

**Comment by shove70** [comment]
Then, in this case: ``` println ('{foo:bar}') ```,

Should we strengthen the semantics of ```:``` and give error messages such as "invalid specifier", instead of making println() work and output it as it is?

Otherwise, there may be countless situations that need to be eliminated. I don't know if I'm right


@JalonSolov, what's your opinion?  thanks.

**Comment by shove70** [comment]
Or add ```fn check_specifier() bool ``` to decide whether to exclude ```:```?

**Comment by JalonSolov** [comment]
> Or add `fn check_specifier() bool ` to decide whether to exclude `:`?

Whichever way is cleaner, and catches more problems.
