### ISSUE TITLE
Missing error downcasting from array to voidptr

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#16337]
**V version:** 0.3.2
**OS:** Linux

**What did you do?**
```v
module main

fn main() {
	foo([]i16{len:10, init: 1})
}

fn foo(a []i16) {
	bar(a)
	bar(a.data)
}

fn bar(b voidptr) {
	println(b)
}
```

**What did you expect to see?**
```v
fn foo(a []i16) {
	bar(a) // error: cannot implicitly cast from []i16 to voidptr
	bar(a.data) // ok: data is of type voidptr
}
```
 
**What did you see instead?**
No error was thrown. The result of passing either `bar(a)` or `bar(a.data)` is quite different and should be reported.

**Comment by JalonSolov** [comment]
Why do you think they should give the same value?  Dynamic arrays are `structs`, not simple memory blocks - see https://github.com/vlang/v/blob/master/vlib/builtin/array.v#L12

The pointer to a and the pointer to a.data _are_ very different things.

**Comment by duarteroso** [comment]
You misread the issue. This is not about being the same value, it's about an implicit cast that in my opinion should be reported as an error.

**Comment by spytheman** [comment]
`voidptr` parameters should be able to accept anything. Most of `builtin` relies on that.
