### ISSUE TITLE
cannot convert 'struct array' to 'struct _option_Array_u8'

### ISSUE THREAD

**Issue by eptx** [vlang/v#16339]
**V version:**  https://play.vlang.io/ 
**OS:** https://play.vlang.io/

**What did you do?**
Trying to understand how V handles optional types. Initializing optional types wasn't supported so I tried...
```
struct Result {
    mut:
    	data ?[]u8
}

enum Status {
    empty
    data
}

fn request(status Status) !Result {
    match status {
        .empty {
            mut r := Result {} 
            return r
        }
        .data {
            mut r := Result {}
            r.data = 'abc'.bytes()
            return r
        }
    }
}
mut r := request(.data)!
dump(r)
```

**What did you expect to see?**
A Result from fn request()
 
**What did you see instead?**
```
/tmp/v_60000/../../../../../../box/code.v:19: error: cannot convert 'struct array' to 'struct _option_Array_u8'
builder error: 
==================
C error. This should never happen.
This is a compiler bug, please report it using `v bug file.v`.
https://github.com/vlang/v/issues/new/choose
You can also use #help on Discord: https://discord.gg/vlang
Exited with error status 1
```

**Comment by changrui** [comment]
Why 'data' is '?[]u8'? changing to '[]u8' is OK.

**Comment by eptx** [comment]
It's meant to be an Optional where data returned may be 'none'. Does V only support struct Optional? If so primitives, arrays, etc would need to be wrapped in a struct when an Optional is needed...hope that's not the case. Still a compiler error either way.

**Comment by shove70** [comment]
hm-hmm, Similar to issue #16211, it will be fixed.
