### ISSUE TITLE
`$tmpl()` does not handle bacticks in `<script>` tag. Or feature request.

### ISSUE THREAD

**Issue by ghost** [vlang/v#16350]
**V version: 0.3.2 407bb66** 
**OS: ArchLinux** 

**What did you do?**
```v
fn main(){
	println($tmpl('template.html'))
}
```
template.html
```html
<script>
	n = 3;
	console.log(`n=${n}`);
</script>
```

**What did you expect to see?**
No error, backticks in `<script>` tags are ignored by `$tmpl()`.
 
**What did you see instead?**
```
> v run bug.v
template.html:11:19: error: undefined ident: `n`
```
Perhaps the specifications are vague in this area.

**Comment by yuyi98** [comment]
```v
fn main(){
	n := 3
	println($tmpl('template.html'))
}
```
String interpolation `${n}` using `n` variable, so we should define it.
