### ISSUE TITLE
Structure declaration error

### ISSUE THREAD

**Issue by lcddh** [vlang/v#1636]
**V version:** 
0.1.18
**OS:** 
win10
**What did you do?**
println('hello,world!')

struct User {
    name string
}

u := User {
    name:'donydh'
    }
println(u.name)

**What did you see instead?**
An error occurs when a printed statement is printed before the structure is declared

![image](https://user-images.githubusercontent.com/5841609/63214479-44a6c980-c14b-11e9-8c97-3a8ba9ca6f27.png)

**Comment by iredmail** [comment]
This one works:

```
struct User {
    name string
}

fn main() {
    println('hello,world!')

    u := User{
        name: 'donydh'
    }

    println(u.name)
}
```

Compile and output:

```
# v hello_world.v 
# ./hello_world
hello,world!
donydh
```

**Comment by Delta456** [comment]
Can you format your code if possible?

**Comment by medvednikov** [comment]
This is due to a missing `fn main()`. It's a bug, it should work.

Will fix, thanks.

**Comment by changrui** [comment]
oh, No! it's can running when name is pub.

**Comment by M4SSD35TRUCT10N** [comment]
Works with current master as expected:

> ```
> struct User {
> name string
> }
> 
> u := User {
> name:'donydh'
> }
> println(u.name)
> ```

@medvednikov : **IMHO** this issue can be closed.
