### ISSUE TITLE
function type assignment `mut` and `&` is not checked.

### ISSUE THREAD

**Issue by kahsa** [vlang/v#16372]
**V version: 0.3.2 a07f77a** 
**OS: ArchLinux** 

**What did you do?**
```v
struct Foo{}

type FooFn = fn(mut f Foo) 

struct Server{
	foo_fn FooFn = unsafe{ nil }
}

fn foo(f &Foo) {}

fn main(){
	srv := Server{
		foo_fn: foo // fn(f &Foo) should not be allowed
	}
	dump(isnil(srv.foo_fn))
}
```

**What did you expect to see?**
Error assigning `fn (&Foo)` is not allowed here.

 
**What did you see instead?**
```
[bug.v:13] main.isnil(srv.foo_fn): false
```

**Comment by shove70** [comment]
I think it should not be allowed to assign ```!is_mut``` type parameters to ```is_mut``` type parameters, but on the contrary, it should not be restricted.

It will be fixed.
