### ISSUE TITLE
merge os.exec and os.system

### ISSUE THREAD

**Issue by pznknmtb** [vlang/v#1637]
currently there are two similar signatures:
```
// system starts the specified command, waits for it to complete, and returns its code.
pub fn system(cmd string) int { 
...

// exec starts the specified command, waits for it to complete, and returns its output.
pub fn exec(_cmd string) ?string { 
...
```
having only code or only output is not sufficient (or clumsy) in certain cases.

please create a "unified" version that returns both, output and code (maybe also split output into stdout and stderr).

**Comment by spytheman** [comment]
Their behavior is different. os.system does not buffer stderr nor stdout of cmd, while os.exec does.

**Comment by medvednikov** [comment]
And what do you do when you need both the exit code and output, @spytheman ? :)

They should be merged indeed.

**Comment by spytheman** [comment]
Will something like this work ?

```
pub fn exec_process(_cmd string, stdout_path string, stderr_path string) ?int {
    cmd := '$_cmd 2> "$stderr_path" > "$stdout_path" '
    f := os.popen(cmd)
    if isnil(f) {
        return error('popen $cmd failed')
    }
    return os.pclose(f)/256
}
```

Usage:
```
import os
fn main(){
        ecode := os.exec_process('find /etc/', '/tmp/stdout.log' , '/tmp/stderr.log') or { panic(err) }
        println('Exit code: $ecode ')
        println('Stdout is inside: /tmp/stdout.log ')
        println('Stderr is inside: /tmp/stderr.log ')
}
```

**Comment by spytheman** [comment]
I am not against another more flexible function, I just wish that os.system (or another unbuffered equivalent) remain available in some form.

**Comment by medvednikov** [comment]
Fixed.

`os.exec()` now returns `?Result` with exit code and output.

There's still `os.system()` that only returns exit code.
