### ISSUE TITLE
`!` and `[required]`

### ISSUE THREAD

**Issue by kahsa** [vlang/v#16388]
**V version: 0.3.2 993e21e** 
**OS: ArchLinux** 

**What did you do?**
```v
struct Foo{
	fnc fn()! [required]
}

fn main(){
	f := Foo{}
}
```

**What did you expect to see?**
Error message like `fnc fn() [required]`
```
bug.v:6:7: error: field `Foo.fnc` must be initialized
    4 | 
    5 | fn main(){
    6 |     f := Foo{}
      |          ~~~~~
    7 | }
```
 
**What did you see instead?**
```
bug.v:2:13: error: non-constant array bound `required`
    1 | struct Foo{
    2 |     fnc fn()! [required]
      |                ~~~~~~~~
    3 | }
    4 |
```

**Comment by taggon** [comment]
Not sure if `!` in a function declaration is allowed. No documentation and no example found.
I think the expected result should be an error message about the `!` following a function declaration.

**Comment by kahsa** [comment]
```v
type ResultFn = fn()!

struct Foo{
	fnc ResultFn [required]
}

fn main(){
	f := Foo{}
}
```
