### ISSUE TITLE
Multi-dimensional array printing

### ISSUE THREAD

**Issue by scroot** [vlang/v#1638]
**V version:** 
**OS:** 
mac  10.13.6
**What did you do?**
fn main() {
  a := [[9,1],[6]]
 // println(a[0]  // add this line , Everything OK
  println(a)
}

**What did you expect to see?**
[[9,1],[6]]
 
**What did you see instead?**
.t.c:322:31: error: passing 'int' to parameter of incompatible type 'string' (aka 'struct string')
                strings__Builder_write(&sb, array_int_str( ((array_int *) a.data)[i])); 
            ...
(Use `v -debug` to print the entire error message)

V panic: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by Delta456** [comment]
Multi-dimensional array are still WIP

**Comment by Delta456** [comment]
Fixed
