### ISSUE TITLE
selective import overloads basic type

### ISSUE THREAD

**Issue by debilosaurus** [vlang/v#16395]
[playground](https://play.vlang.io/?query=b492be90b9)

```
import rand { f64 }
type Dot = [3]f64
```

**What did you expect to see?**
```
code.v:3:12: error: unknown type `rand.f64`.
Did you mean `rand.PRNG`?
    1 | import rand { f64 }
    2 | 
    3 | type Dot = [3]f64
      |            ~~~~~~
Exited with error status 1
```
 
**What did you see instead?**
In my opinion an imported function overloads a basic type.
There are two aspects:
a. If this is the desired behaviour, no lib should use keywords of basic types,
b. There are cases, in which you want to use selective imports to have a better overview of your dependencies, maybe to get rid of in a later stage. It would be a better approach to always import everything with prefixes, except the programmer overide this with a keyword.

**Comment by Delta456** [comment]
Shouldn't this be an error because `f64` isn't a symbol when it is a `type`?

**Comment by JalonSolov** [comment]
Yes, it should.  You should not be able to use type names as modules/imports.  Especially not built-in types.
