### ISSUE TITLE
Dose for in not support string?

### ISSUE THREAD

**Issue by tonylinyy** [vlang/v#164]
Dose for in not support string?

**Comment by medvednikov** [comment]
Sorry, don't understand the question.

**Comment by zac-garby** [comment]
I think he means "can a for-loop iterate over the characters in a string?"

**Comment by tonylinyy** [comment]
@zac-garby yes,like this:
for char in string {
	...
}

**Comment by medvednikov** [comment]
Now you can:

```
fn main() {
        s := 'hello'
        for c in s {
                println(c.str())
        }
}
```

UTF-8 is not handled yet, but it will be like Go's `range str` soon.

**Comment by tonylinyy** [comment]
I run your code,here is the error message:
`for in` requires an array but got `string`
