### ISSUE TITLE
Cannot cross-compile for 32 bit windows from linux

### ISSUE THREAD

**Issue by MohammadMD1383** [vlang/v#16416]
**V version:** V 0.3.2 b54f9c2.5a28699
**OS:** linux, Ubuntu 22.10

**What did you do?**
v . -os windows -arch i386

**What did you expect to see?**
an exe with 32 bit architecture
 
**What did you see instead?**
an exe with 64 bit architecture

**Comment by JalonSolov** [comment]
Try `-m32` instead of `-arch i386`...  the `-arch` option may only be available with `-native`.
```
$ v -os windows -m32 hello_world.v 
Cross compiling for Windows...
'/home/jamie/git/vv/examples/hello_world.exe' has been successfully compiled
$ file hello_world.exe
hello_world.exe: PE32 executable (console) Intel 80386, for MS Windows
$
```

**Comment by MohammadMD1383** [comment]
Thanks it's working now.
