### ISSUE TITLE
`[noinit]` in struct's field does not work as default value

### ISSUE THREAD

**Issue by ghost** [vlang/v#16423]
**V version: 0.3.2 1a4d1ae** 
**OS: ArchLinux** 

 
Some specifications have not been determined as to what is the correct behavior, and this would be one of them.
We should make a list of such issues that are left in limbo because the specifications cannot be determined.

**What did you do?**

```
.
├── bug.v
├── mod
│   └── mod.v
└── v.mod
```
bug.v
```v
import mod

struct Bar{
	foo mod.Foo
}

fn main(){
	b := Bar{}
	println(b)
	f := mod.Foo{}
}
```
mod.v
```v
module mod

[noinit]
pub struct Foo{
pub:
	n int
}
```

**What did you expect to see?**
`b := Bar{}` should be an error also.
 
**What did you see instead?**
```
> v run bug.v
bug.v:10:2: warning: unused variable: `f`
    8 |     b := Bar{}
    9 |     println(b)
   10 |     f := mod.Foo{}
      |     ^
   11 | }
bug.v:10:11: error: struct `mod.Foo` is declared with a `[noinit]` attribute, so it cannot be initialized with `mod.Foo{}`
    8 |     b := Bar{}
    9 |     println(b)
   10 |     f := mod.Foo{}
      |              ~~~~~
   11 | }
```

**Comment by kahsa** [comment]
#16400
