### ISSUE TITLE
ORM select does not work with string interpolation

### ISSUE THREAD

**Issue by sdwefredsvgf** [vlang/v#16422]
**V version: V 0.3.2 38555a9** 
**OS: linux, LMDE 5 (elsie)** 

code:
```
import sqlite
import crypto.md5
import os { input }

struct Secret {
	id     int    [primary; sql: serial]
	name   string [nonull]
	pass   string [nonull]
	secret string [nonull]
}

fn main() {
	db := sqlite.connect('secrets.db')!

	sql db {
		create table Secret
	}

	for {
		mut option := input('Menu:\n1 - Show secret\n2- Add Secret\n3 - Exit\n').int()
		if option == 1 {
			show_secret()!
		} else if option == 2 {
			add_secret()!
		} else {
			println('Exiting...')
			exit(1)
		}
	}
}

fn show_secret() ! {
	db := sqlite.connect('secrets.db')!
	name := input('Enter your name: ')
	pass := md5.hexhash(input('Enter your passcode: '))

	secret := sql db {
		select from Secret where name == '$name' && pass == '$pass'
	}

	println(secret)
}

fn add_secret() ! {
	db := sqlite.connect('secrets.db')!
	secret := Secret{
		name: input('Enter your name: ')
		pass: md5.hexhash(input('Enter a passcode: '))
		secret: input('Enter your secret: ')
	}
	sql db {
		insert secret into Secret
	}
}
```
**What did you do?**
v secret.v

**What did you expect to see?**
A compiled program

 
**What did you see instead?**
```
==================
/tmp/v_1000/secret.11953671100383067735.tmp.c:43272: error: identifier expected
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by JalonSolov** [comment]
If you compile with `-g` it shows the V line number where the problem is occurring.

In your case, it is here:
```v
				secret := sql db {
								select from Secret where name == '$name' && pass == '$pass' 
				}  // <-- error is pointing to this line
```
The problem appears to be using string interpolation in the `select`.  Changing that function to the following makes it compile clean:
```v
fn show_secret() ! {
        db := sqlite.connect('secrets.db')!
        n := input('Enter your name: ')
        p := md5.hexhash(input('Enter your passcode: '))

        secret := sql db {
                select from Secret where name == n && pass == p
        }

        println(secret)
}
```

**Comment by sdwefredsvgf** [comment]
> If you compile with `-g` it shows the V line number where the problem is occurring.
> 
> In your case, it is here:
> 
> ```v
> 				secret := sql db {
> 								select from Secret where name == '$name' && pass == '$pass' 
> 				}  // <-- error is pointing to this line
> ```
> 
> The problem appears to be using string interpolation in the `select`. Changing that function to the following makes it compile clean:
> 
> ```v
> fn show_secret() ! {
>         db := sqlite.connect('secrets.db')!
>         n := input('Enter your name: ')
>         p := md5.hexhash(input('Enter your passcode: '))
> 
>         secret := sql db {
>                 select from Secret where name == n && pass == p
>         }
> 
>         println(secret)
> }
> ```
Okay I understand the problem, it's compiling now. Thank you very much for the reply.

**Comment by JalonSolov** [comment]
Let's leave it open - it should work fine with the string interpolation, but at least you have a workaround for now.

**Comment by ishwar00** [comment]
hey @sdwefredsvgf, could you please indent your [code](https://github.com/vlang/v/issues/16422#issue-1447015564) using _tabs_?, just it will make easier to follow and can be viewed without needing to scroll. 

Thanks

**Comment by JalonSolov** [comment]
`v fmt -w <your file>` will take care of that for you.
