### ISSUE TITLE
There is no output with news_fetcher.v on Windows

### ISSUE THREAD

**Issue by lcddh** [vlang/v#1642]
**V version:** 
0.1.18
**OS:** 
win10
**What did you do?**

**What did you expect to see?**

 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/5841609/63219717-a5b1ba00-c1aa-11e9-8a1e-1bd6c1331cd7.png)

**Comment by joe-conigliaro** [comment]
thanks @lcddh will report back soon

**Comment by joe-conigliaro** [comment]
@lcddh seems like it's not waiting at waitgroup.Wait() will need further investigation

**Comment by joe-conigliaro** [comment]
This has been fixed
