### ISSUE TITLE
Return single element from array

### ISSUE THREAD

**Issue by fairking** [vlang/v#16441]
The `single()` function allows to get a single element from the array.

It is useful when querying elements and expecting only one element, so no extra lines of code required to do so.
Eg.:
``` vlang
m := memebrs.filter(it.email == input).single() // will panic if there are more than one element found (also if no elements found)
return m
```
The difference from `first()` is it guarantees that the element we found is unique based on our requirement (email).
`single()` also means that the duplicate is not intended to be in the list by design, so we must break the execution.

Happy to answer any questions.

**Comment by JalonSolov** [comment]
_Getting_ a single element is simple.  _Guaranteeing_ an element is unique is different.

**Comment by spytheman** [comment]
just use m.len
