### ISSUE TITLE
fmt does not format if module is called systools

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#16466]
**V version:** 0.3.2 886abcd
**OS:** Linux

This is an odd one. I have search the git repo but could not find any reserved keyword that could explain the following behavior.

## Working example

```v
// pre fmt
module buggus

const (
	key = 'value'
)

fn main() {
	println(key)
}
```

```v
// post fmt
module buggus

const (
	key = 'value'
)

fn main() {
	println(buggus.key)
}
```

Notice that `println(key)` was correctly change to `println(buggus.key)`

## Broken example
```v
// pre fmt
module systools

const (
	key = 'value'
)

fn main() {
	println(key)
}
```

```v
// post fmt
module systools

const (
	key = 'value'
)

fn main() {
	println(.key)
}
```

Notice that `println(key)` was incorrectly change to `println(.key)`

## Collision?

Is `systools` some kind of reserved internal keyword that would explain why formatting a package named `systools` would fail?

**Comment by JalonSolov** [comment]
No, the string `systools` does not exist anywhere within the V source.

Seems to be working fine, for me.  `V 0.3.2 92be903`  Make sure you've updated to the current V and try it again.

**Comment by duarteroso** [comment]
Here's the sample, in case it helps
[const_fmt_bug.zip](https://github.com/vlang/v/files/10042656/const_fmt_bug.zip)

```v
[duarteroso@fedora const_fmt_bug]$ v up
Updating V...
V is already updated.
Current V version: V 0.3.2 92be903, timestamp: 2022-11-18 12:54:17 +0200
[duarteroso@fedora const_fmt_bug]$ cat const_fmt_bug.v 
module systools

const (
	key = 'value'
)

fn main() {
	println(key)
}
[duarteroso@fedora const_fmt_bug]$ v fmt const_fmt_bug.v 
module systools

const (
	key = 'value'
)

fn main() {
	println(.key)
}
[duarteroso@fedora const_fmt_bug]$ 
```

**Comment by JalonSolov** [comment]
```
[jamie@5950x const_fmt_bug]$ cat const_fmt_bug.v
module systools

const (
        key = 'value'
)

fn main() {
        println(key)
}
[jamie@5950x const_fmt_bug]$ v fmt const_fmt_bug.v
module systools

const (
        key = 'value'
)

fn main() {
        println(systools.key)
}
[jamie@5950x const_fmt_bug]$ 
```

I'd say look for things like a `v.mod` file in a parent dir, make sure you don't have anything odd set in `VFLAGS` env var, etc.

**Comment by duarteroso** [comment]
Indeed, on the mac it works and moving that folder elsewhere on the Linux (where the error first appeared) seems to fix it... odd!
