### ISSUE TITLE
build error `json.encode()` optional field.

### ISSUE THREAD

**Issue by ghost** [vlang/v#16462]
**V version: 0.3.2 ae816b1** 
**OS: ArchLinux** 

**What did you do?**
```v
import json

struct Foo{
	name string
	num  ?int
}

fn main(){
	f := Foo{}
	dump(json.encode(f))
}
```

**What did you expect to see?**
No error.
Ideally, the following results.
`{"name":""}` or `{"name":"","num":null}`
 
**What did you see instead?**
```
==================
/tmp/v_1000/bug.330116750381110337.tmp.c:2155: error: '_result__option_int' undeclared
...
==================
```

**Comment by kahsa** [comment]
https://github.com/vlang/v/issues/16447

**Comment by enghitalo** [comment]
fixed in json2
