### ISSUE TITLE
V 0.1.18 dosen't function on Mac

### ISSUE THREAD

**Issue by N8python** [vlang/v#1646]
**V version: 0.1.18** 
**OS: 14.5.0 Darwin Kernel Version** 

**What did you do?**
First, I tried to build `vid` using `v .`
Then, I opened up the V REPL and declared a variable `x := 3`.

**What did you expect to see?**
I expected vid to build without error, and for the repl to store `x` without trouble.
 
**What did you see instead?**
Instead, I saw the same error both times: `V panic: array.v:80 unreachable code.`

**Comment by medvednikov** [comment]
Are you on the latest commit? Try `v up`.

**Comment by N8python** [comment]
I ran `v up`. The REPL works fine. However, when I tried to build vid with `./vid`, I insead got the error:
`
.vid.c:118:10: fatal error: 'ft2build.h' file not found
#include "ft2build.h"
         ^
1 error generated.V panic: C error. This should never happen
`

**Comment by medvednikov** [comment]
you don't have freetype installed

**Comment by N8python** [comment]
What does `freetype` do? How would I install it?

**Comment by medvednikov** [comment]
https://github.com/vlang/vid#building-from-source
