### ISSUE TITLE
new report format does not label

### ISSUE THREAD

**Issue by kahsa** [vlang/v#16479]
### Describe the bug

bug report does not have a bug tag.

### Expected Behavior

tagged

### Current Behavior

not tag

### Reproduction Steps

-

### V version

-

### Environment details (OS name and version, etc.)

-

**Comment by spytheman** [comment]
@ulises-jeremias is there a solution to this?

**Comment by spytheman** [comment]
@ulises-jeremias sorry for the ping - I think I fixed it in 531c145, ( https://github.com/vlang/v/blob/master/.github/ISSUE_TEMPLATE/bug-report.yml ) .
