### ISSUE TITLE
Setting values inside maps of structs containing maps does not work.

### ISSUE THREAD

**Issue by spytheman** [vlang/v#1647]
**V version:** V 0.1.18
**OS:** Ubuntu 16.04.3 LTS

**What did you do?** I compiled and executed the following program:

```
struct Section {
        description string
        values map[string]string
}

fn (s Section) str() string {
        return 'description: "$s.description" \nvalues: ' + s.values.str()
}
fn (sectionMap map[string]Section) str() string {
        mut res := []string
        res << 'map of sections:'
        for k,v in sectionMap {
                res << 'k: $k | v: ' + v.str()
        }
        return res.join('\n')
}

fn main(){
        mut all := map[string]Section
        all['people'] = Section{ description: 'These are people' }
        all['people'].values['John'] = 'Smith'
        all['people'].values['Diana'] = 'Blanca'
        all['animals'] = Section{ description: 'These are animals' }
        all['animals'].values['cat'] = 'Tom'
        all['animals'].values['mouse'] = 'Jerry'
        println('The mouse is named: ' + all['animals'].values['mouse'] )

        println('All creatures:')
        println(all)
}
```

**What did you expect to see?**
I expected that these lines:
```
        all['animals'].values['mouse'] = 'Jerry'
        println('The mouse is named: ' + all['animals'].values['mouse'] )
```
... to print:
```
The mouse is named: Jerry
```
 
**What did you see instead?**
```
The mouse is named: 
```
i.e. my mouse was still anonymous, even after giving it a name :-) .

**Comment by Danil-Lapirow** [comment]
A piece of generated C code:
```
map_Section all = new_map(1, sizeof(Section));

Section tmp6 = (Section) {.description =  tos2((byte *) "These are people"), .values = new_map(1, sizeof(string))};

map__set(&all, tos2((byte *) "people"), &tmp6); // here you see that we store *tmp6 into all  

Section tmp7 = {0};
bool tmp8 = map_get(all, tos2((byte *) "people"), &tmp7); //error appears here
// we take a pointer to our tmp6 and dereference it => we store copy of tmp6 in the tmp7

string tmp9 = tos2((byte *) "Smith");

map__set(&tmp7.values, tos2((byte *) "John"), &tmp9); // here we are modifying tmp7 while tmp6(which is one that is stored in the "all") is staying unchanged
```

**Comment by spytheman** [comment]
So the problem is that map_get makes a new copy of the found map node, 
instead of returning a pointer to it?

**Comment by Danil-Lapirow** [comment]
Yup

**Comment by medvednikov** [comment]
Yes, this is a very serious limitation. I think there's a way to fix it and use the returned pointer, just like with arrays.

**Comment by Danil-Lapirow** [comment]
@medvednikov, can't we just use pointers when we take map's items? Or there are caveats?

**Comment by medvednikov** [comment]
@Danil-Lapirow I'm working on fixing this right now.

**Comment by medvednikov** [comment]
I've fixed it, the only thing left is handling missing keys.

I'm considering using optionals instead of empty values for missing keys. Thoughts?

**Comment by spytheman** [comment]
> I've fixed it, the only thing left is handling missing keys.
> 
> I'm considering using optionals instead of empty values for missing keys. Thoughts?

@medvednikov yes, it is a good idea to return optionals in this case, so that the caller can decide what should happen in this case without treating one of the possible values as special.

**Comment by spytheman** [comment]
That however will make chained usage like this harder (i.e. when you know that the values are there already):
println( all['animals'].values['mouse'] )

**Comment by spytheman** [comment]
Kotlin supports `bob?.department?.head?.name` syntax 
https://kotlinlang.org/docs/reference/null-safety.html

**Comment by ka-weihe** [comment]
Works in v2.
