### ISSUE TITLE
const in match range

### ISSUE THREAD

**Issue by ytoml** [vlang/v#16480]
### Describe the feature

Hi, I have recently started V writting and it is much fun, but I came up with missing feature which is quite common to other ranguages like Rust.

Currently, we cannot use constant values in match range like:
```v
pub const (
  start = 1
  end = 10
)
fn const_match_ok() int {
	some_int := 10
	ret := 
	match some_int {
		start { 0 }
		end { 10 }
		else { 1000 }
	}
	return ret
}

// compile error
fn const_match_range_ng() int {
	some_int := 10
	ret := 
	match some_int {
		start ... end { 0 }
		else { 1000 }
	}
	return ret
}
```

Moreover, the compile error message is a little bit confusing:
```
./main.v:28:3: error: unexpected keyword `else`, expecting `{`
   26 |     match some_int {
   27 |         start ... end { 0 }
   28 |         else { 1000 }
      |         ~~~~
   29 |     }
   30 |     return ret
```

### Use Case

It makes meaning of range clearer.
For example, when writing CPU emulator:
```v
const (
  mmio_base = u64(0xfee0_0000)
  mmio_base = u64(0xfeef_ffff)
)
struct Bus {
mut:
  dram Dram
  periph PeripheralDevices
}
fn (b Bus) write(addr u64, value u64) {
  match addr {
    mmio_base ... mmio_end { return b.periph.write(addr, value) }
    else { return b.dram.write(addr, value) }
  }
}
```
is readable than:
```v
struct Bus {
mut:
  dram Dram
  periph PeripheralDevices
}
fn (b Bus) write(addr u64, value u64) {
  match addr {
    0xfee0_0000 ... 0xfeef_ffff { return b.periph.write(addr, value) }
    else { return b.dram.write(addr, value) }
  }
}
```

### Version used

V 0.3.2 2d9808b

### Environment details (OS name and version, etc.)

macOS Monterey (MacBook Pro, Apple M1, 2020)

**Comment by ytoml** [comment]
> ### Describe the feature
> Hi, I have recently started V writting and it is much fun, but I came up with missing feature which is quite common to other ranguages like Rust.
> 
> Currently, we cannot use constant values in match range like:
> 
> ```v
> const (
>   start = 1
>   end = 10
> )
> fn const_match_ok() int {
> 	some_int := 10
> 	ret := 
> 	match some_int {
> 		start { 0 }
> 		end { 10 }
> 		else { 1000 }
> 	}
> 	return ret
> }
> 
> // compile error
> fn const_match_range_ng() int {
> 	some_int := 10
> 	ret := 
> 	match some_int {
> 		start ... end { 0 }
> 		else { 1000 }
> 	}
> 	return ret
> }
> ```
> 
> Moreover, the compile error message is a little bit confusing:
> 
> ```
> ./main.v:28:3: error: unexpected keyword `else`, expecting `{`
>    26 |     match some_int {
>    27 |         start ... end { 0 }
>    28 |         else { 1000 }
>       |         ~~~~
>    29 |     }
>    30 |     return ret
> ```
> 
> ### Use Case
> It makes meaning of range clearer. For example, when writing CPU emulator:
> 
> ```v
> const (
>   mmio_base = u64(0xfee0_0000)
>   mmio_base = u64(0xf
> )
> struct Bus {
> mut:
>   dram Dram
>   periph PeripheralDevices
> }
> fn (b Bus) write(addr u64, value u64) {
>   match addr {
>     mmio_base ... mmio_end { return b.periph.write(addr, value) }
>     else { return b.dram.write(addr, value) }
>   }
> }
> ```
> 
> is readable than:
> 
> ```v
> struct Bus {
> mut:
>   dram Dram
>   periph PeripheralDevices
> }
> fn (b Bus) write(addr u64, value u64) {
>   match addr {
>     0xfee0_0000 ... 0xfeef_ffff { return b.periph.write(addr, value) }
>     else { return b.dram.write(addr, value) }
>   }
> }
> ```
> 
> ### Proposed Solution
> _No response_
> 
> ### Other Information
> _No response_
> 
> ### Acknowledgements
> * [ ]  I may be able to implement this feature request
> * [ ]  This feature might incur a breaking change
> 
> ### Version used
> V 0.3.2 2d9808b
> 
> ### Environment details (OS name and version, etc.)
> macOS Monterey (MacBook Pro, Apple M1, 2020)

**Comment by Delta456** [comment]
I believe this should be implemented.

**Comment by shove70** [comment]
Good idea.

**Comment by Delta456** [comment]
![image](https://user-images.githubusercontent.com/28479139/202849533-6880f3b7-017e-491b-88aa-8cab97502cce.png)

As this feature request is accepted, I will be working on it.

**Comment by Delta456** [comment]
Implemented in https://github.com/vlang/v/commit/a9b41d298095cf7814e9597dfb0f6b9abdd1686b

**Comment by ytoml** [comment]
Great, thanks!
