### ISSUE TITLE
 Whether macros will be added or not is necessary in many cases. 

### ISSUE THREAD

**Issue by cjmxp** [vlang/v#165]
Whether macros will be added or not is necessary in many cases.

**Comment by cjmxp** [comment]
I like V very much. He looks like go2 in my dream.

**Comment by medvednikov** [comment]
This decision is not final, but right now I think there shouldn't be macros.

The goal of V is a simple language for building maintainable software. Macros are nice, but they can make large code bases very confusing. Every will developer has an option to extend the language, thus readability suffers.

**Comment by cjmxp** [comment]
I see. Thank you.

**Comment by shiipou** [comment]
> decision is not final, but right now I think there shouldn't be macros.
> 
> The goal of V is a simple language for building maintainable software. Macros are nice, but they can make large code bases very confusing. Every developer has an option to extend the language, thus readability suffers.
@medvednikov 

I'm ok with your decision, but it seems you already done something that look like macro with `vweb` and the `[post]` annotation.
I think it's better to have macro that to have specific annotation for only one usecase hard-codded in the compiler don't you think ?

If I'm wrong, is there any way for us to create this type of annotation for our own modules ?

**Comment by bogen85** [comment]
> I'm ok with your decision, but it seems you already done something that look like macro with `vweb` and the `[post]` annotation. I think it's better to have macro that to have specific annotation for only one usecase hard-codded exception in the compiler don't you think ?
> 
> If I'm wrong, is there any way for us to create this type of annotation for our own modules 

One of the reasons it won't be for V to not have macros is if one gets use to the feature set as provided and uses it to build software, and starts promoting its use, standard V can present a forward facing set of:
1. These are the modules we support
2. These are the languages features we can support.

And any issues with those features as documented and specified can be handled through standard issue tracking and discussions.

So a couple things here. Macro type facilities can burn programmers. Yes, it is there own fault, but peers on same project might not blame the person writing the macros, they may blame V and tell everyone how bad V is. Or an original programmer who had macros working, in a new language like V that, for sake of this discussion, chose to support macro concepts, and some of the how they were to be used changed, and the programmer's code broke, they too may blame V and try to dissuade others.

There is plenty of work as is for V to reach the level of stability it is striving for and what programmers want and need. Throwing macro or other meta programming abilities into the mix at this early of stage would complicate that. So for now, the decision was made no macros. And to present a consistent language and official module front going forward after the language has stabilized, that will likely still be the case.

As you alluded to, underneath the hood in V obviously something similar to those sorts of mechanisms do exist. But even if those cases, they not using the the official forward facing front of V. Opening things like up to allow that for everyone makes presenting a consistent stable front very difficult.

This may sound arbitrary, but the decisions were made passed on developers getting burned by languages with those facilities, and V not wanting to take that path.

**Comment by JalonSolov** [comment]
Yes, V allows you to create your own attributes.  It has for a long time, it simply isn't documented very well.

**Comment by bogen85** [comment]
> If I'm wrong, is there any way for us to create this type of annotation for our own modules ?

You can. The question is, how can you use it?
```v
module main

[shiipou_custom_attribute_A]
fn some_function () {
	println('hello from some function')
}

fn main () {
	some_function()
}
```

```shell
v run main.v 
hello from some function
```

**Comment by JalonSolov** [comment]
`$for method in T.methods { /* method.attrs is now []string of all the attributes */ }`

**Comment by bogen85** [comment]
@shiipou 

> I'm ok with your decision, but it seems you already done something that look like macro with `vweb` and the `[post]` annotation. I think it's better to have macro that to have specific annotation for only one usecase hard-codded exception in the compiler don't you think ?

Official V modules and backends from the official V use the attributes as hints/specifiers to be able to perform the desired functionality.

> If I'm wrong, is there any way for us to create this type of annotation for our own modules ?

Currently being able to use the attributes is not available above the hood of the official V.
And, as Alex noted, may never be (at compile time that is).

As @JalonSolov has noted, at run time they are available.

**Comment by bogen85** [comment]
@shiipou 

```v
module main

struct Custom {}

[shiipou_custom_attribute_A]
fn (c Custom) some_function () {
	println('hello from some function')
}

fn main () {
	$for method in Custom.methods {
		println('Method: ${method}')
		for attr in method.attrs {
			println('  attribute: ${attr}')
		}
	}
}
```

```shell
v run main.v 
Method: FunctionData{
    name: 'some_function'
    attrs: ['shiipou_custom_attribute_A']
    args: []
    return_type: 1
    typ: 0
}
  attribute: shiipou_custom_attribute_A
```

**Comment by shiipou** [comment]
Thanks for all, that'll help me a lot.
