### ISSUE TITLE
"Segmentation fault: 11" when outputting ast file.

### ISSUE THREAD

**Issue by shove70** [vlang/v#16500]
### Describe the bug

```v
struct Foo {}

fn (f Foo) bar() int {
	return 1
}

fn main() {
    foo := Foo{}
	$for method in Foo.methods {
		_ := foo.$method()   // <<< this work.
		var := foo.$method() // <<< this not work.
	}
}
```

```v ast a.v```

### Expected Behavior

output the ```.json``` file.

### Current Behavior

```
Segmentation fault: 11
```

### Reproduction Steps

--

### V version

V full version: V 0.3.2 6cd1723

### Environment details (OS name and version, etc.)

OS: macos, macOS, 13.0.1, 22A400 Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz CC version: Apple clang version 14.0.0 (clang-1400.0.29.202)

**Comment by felipensp** [comment]
It is already working on newer V version. Thanks.
