### ISSUE TITLE
Sum type with struct and function types

### ISSUE THREAD

**Issue by eptx** [vlang/v#16514]
### Describe the bug

Recently discovered that Sum types don't allow Interfaces. Perhaps they don't allow function types either?

```
struct None {}
type Myfn = fn (int) int
type Myfnfact = fn () Myfn
type Maybefnfact = Myfnfact | None

//Myfn
fn abc(i int) int {
    return i
}

fn run(mmff Maybefnfact) {
    match mmff {
        Myfnfact {println('yes fn')}
        None {println('None fn')}
    }
}

//create Myfn
myfnfact := fn () Myfn {
    return abc
}

println(myfnfact()(1))
run(None{})	// works 
run(myfnfact) // no work
```

### Expected Behavior

Expected to see output from run() function.

### Current Behavior

```
/tmp/v_60000/code.16139365580916353913.tmp.c:2072: error: ',' expected (got "x")
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

Exited with error status 1
```

### Reproduction Steps

Run the above code in playground.

### Possible Solution

Expand Sum types to include function types (and interfaces)...if that's the issue. Or give compiler message about the limitation.

### V version

playground

### Environment details (OS name and version, etc.)

playground

**Comment by JalonSolov** [comment]
Interfaces in V aren't "real" - they aren't separate types, etc.  They are more of a "contract" to tie matching structs together.

Functions?  Not sure how that could work...  Could be really, really messy.

**Comment by eptx** [comment]
That was fast...thank you!
