### ISSUE TITLE
Windows builder err ,Linux builder Success

### ISSUE THREAD

**Issue by Avey777** [vlang/v#16522]
### Describe the bug
```
import net.http
import json

fn main(){
	r := request()!
	mut jsonstr := json.encode(r)
	println(jsonstr)
}

fn request() !string {

	get_tk := '193286.281871'
	q := '我是最好的中国人'

	mut req := http.Request{
		method: http.Method.get
		url: 'https://translate.google.com/translate_a/single?client=webapp&sl=zh-CN&tl=en&hl=zh-CN&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=sos&dt=ss&dt=t&otf=2&ssel=0&tsel=0&kc=3&tk=' + get_tk + '&q=' + q
	}

	req.add_custom_header('user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36')!
	req.add_custom_header('referer', 'https://translate.google.cn/')!
	reponse := req.do()!
	// println("打印req:$reponse")
	return reponse.body
}
```
The above code compiles normally in Linux, and compiles panic in win10

### Expected Behavior
```
"[[[\"I am the best Chinese\",\"我是最好的中国人\",null,null,3,null,null,[[null,\"offline\"]],[[[\"b5157301915684a380dbc61ec02b829f\",\"efficient_models_2022q2.md\"]]]],[null,null,null,\"Wǒ shì zuì hǎo de zhōngguó rén\"]],null,\"zh-CN\",null,null,[[\"我是最好的中国人\",null,[[\"I am the best Chinese\",0,true,false,[3],null,[[3]]],[\"I'm the best Chinese\",0,true,false,[8]]],[[0,8]],\"我是最好的中国人\",0,0]],1,[],[[\"zh-CN\"],null,[1],[\"zh-CN\"]]]"
```
### Current Behavior
```
PS E:\Documents\Github\vlang\google_transltate>  v run .\tk_google.v
Error 10057 sending data to server (1)
Error performing handshake
V panic: result not set (response does not start with HTTP/)
v hash: f0a23c8
C:/Users/Administrator/AppData/Local/Temp/v_0/tk_google.6539773912479609559.tmp.c:10660: at _v_panic: Backtrace
C:/Users/Administrator/AppData/Local/Temp/v_0/tk_google.6539773912479609559.tmp.c:10630: by panic_result_not_set
C:/Users/Administrator/AppData/Local/Temp/v_0/tk_google.6539773912479609559.tmp.c:29217: by main__main
C:/Users/Administrator/AppData/Local/Temp/v_0/tk_google.6539773912479609559.tmp.c:29926: by wmain
0050a6c0 : by ???
0050a823 : by ???
7ffce80374b4 : by ???
```
### Reproduction Steps
```
v run bug.v
```

### V version

V 0.3.2 f0a23c8

### Environment details (OS name and version, etc.)

Windows10

**Comment by JalonSolov** [comment]
You really expected it to fail with a panic?

**Comment by Avey777** [comment]
> You really expected it to fail with a panic?

yeah!  It's panic in windows10.

**Comment by JalonSolov** [comment]
I don't understand - why would you ever want your code to panic?  I always expect it to work correctly, with no panic.

With your given output, the expected matches what you saw, so there's no reason to report a problem.

**Comment by Avey777** [comment]
> 

I mean that panic will appear when compiling on my Windows 10 computer, and the same code can be edited normally on my Linux computer

**Comment by JalonSolov** [comment]
Ok, then what you saw on Linux is what you expected to see.  That's what you should have pasted in the issue in the first place.  If you look up, you pasted identical things in both expected and current, which makes no sense.

**Comment by JalonSolov** [comment]
Issue edited to correctly reflect expected vs current.  Extraneous comments deleted.

**Comment by Avey777** [comment]
> 问题已编辑以正确反映预期与当前。删除了无关的评论。

I'm very sorry that this is my mistake. I submitted the issue after failing to review it. Thank you for your help

**Comment by JalonSolov** [comment]
I just wanted to make sure it was correct, so the problem could be better understood.
