### ISSUE TITLE
Builder Error my_script.abignumber.tmp.c not found

### ISSUE THREAD

**Issue by Eliyaan** [vlang/v#16527]
### Describe the bug

![image](https://user-images.githubusercontent.com/103932369/203869187-86fb8e84-6566-4e98-aef6-7aadef7c4f37.png)
The compiler crashed and I went on discord and someone told me to do this issue ^^

### Expected Behavior

I expected the code to compile

### Current Behavior

It does not compile
![image](https://user-images.githubusercontent.com/103932369/203869280-36bc98c3-6264-4fea-8df6-02bbbd1afee8.png)

### Reproduction Steps

```
import time
import math

fn main(){
	time_debut := time.now()
	count := 1000
	mut premiers_liste := []int{cap: count}
	//mut valid := True
	mut rooti := 0.0
	for i in 2..count {
		rooti = math.sqrt(i)
		for premier in premiers_liste {
			if i%premier != 0{
				break
			}
			else if premier > rooti {
				premiers_liste << i
			}
			else if premier == premiers_liste.last(){
				premiers_liste << i
			}
		}
		

	}
	println(time.now() - time_debut)
	println(premiers_liste)
}
```

### V version

 V 0.3.2 dee75fe

### Environment details (OS name and version, etc.)

OS: windows, Microsoft Windows 10 ducation v19045 64 bits Processor: 4 cpus, 64bit, little endian, Intel(R) Pentium(R) Gold 7505 @ 2.00GHz CC version: Error: exec failed (CreateProcess) with code 2: Le fichier spécifié est introuvable.  cmd: cc --version  getwd: C:\Users\PACHECON\_code_v\primalité vmodules: C:\Users\PACHECON\.vmodules vroot: C:\Users\PACHECON\v vexe: C:\Users\PACHECON\v\v.exe vexe mtime: 2022-11-24 11:37:28 is vroot writable: true is vmodules writable: true V full version: V 0.3.2 f0a23c8  Git version: git version 2.33.0.windows.2 Git vroot status: weekly.2022.47-3-gf0a23c8d (2 commit(s) behind V master) .git/config present: true thirdparty/tcc status: thirdparty-windows-amd64 cb89a4fe

**Comment by JalonSolov** [comment]
Please update to latest V and try this again.  With latest V on Linux, I get the following when compiling your code:
```
foo.v:4:16: error: undefined ident: `time`
    2 | 
    3 | fn main(){
    4 |     time_debut := time.now()
      |                   ~~~~
    5 |     count := 1000
    6 |     mut premiers_liste := []int{cap: count}
foo.v:25:10: error: undefined ident: `time`
   23 | 
   24 |     }
   25 |     println(time.now() - time_debut)
      |             ~~~~
   26 |     println(premiers_liste)
   27 | }
```
and after I add `import time` at the top, I get:
```
70.000us
[]
```
