### ISSUE TITLE
mut anonymous struct / expression in function argument, and error messages

### ISSUE THREAD

**Issue by eptx** [vlang/v#16535]
### Describe the bug

Error msg when not using mut says to use mut. Error message when using mut says its unavailable. Not able to create/use mutable anonymous struct as a function argument. Not sure if this is by design or temporarily unavailable. 

### Expected Behavior

Able to use mutable anonymous struct / expression in function argument.

### Current Behavior

Not using mut, error says to use mut..
```
struct MyStruct {}
fn process(mut ms MyStruct) {}
process(MyStruct{})
---
code.v:4:9: warning: automatic referencing/dereferencing is deprecated and will be removed soon (got: 0 references, expected: 1 references)
    2 | struct MyStruct {}
    3 | fn process(mut ms MyStruct) {}
    4 | process(MyStruct{})
      |         ~~~~~~~~~~
code.v:4:9: error: function `process` parameter `ms` is `mut`, so use `mut MyStruct{....}` instead
    2 | struct MyStruct {}
    3 | fn process(mut ms MyStruct) {}
    4 | process(MyStruct{})
      |         ~~~~~~~~~~
Exited with error status 1
```
Using mut, error says can't use mut...
```
struct MyStruct {}
fn process(mut ms MyStruct) {}
process(mut MyStruct{})
---
code.v:4:13: error: cannot pass expression as `mut`
    2 | struct MyStruct {}
    3 | fn process(mut ms MyStruct) {}
    4 | process(mut MyStruct{})
      |             ~~~~~~~~~~
Exited with error status 1
```

### Reproduction Steps

Run in Playground per code above.

### Possible Solution

Should be able to use mut with anonymous struct as function argument. If not, another step with variable creation.

### V version

Playground

### Environment details (OS name and version, etc.)

Playground

**Comment by vincenzopalazzo** [comment]
This works

```v
struct MyStruct {}
fn process(mut ms MyStruct) {}
mut var := MyStruct{}
process(mut var)
```

>Should be able to use mut with anonymous struct as a function argument. If not, another step with variable creation.

I think the message should be more explicative in the case of expression. Making an anonymous mut struct (or whatever we call it) does not make sense to me, because if you do not need to use again the variable you should use a struct method and call `foo.process()`, or if you need to use the variable later you can not use your code because you lost the reference.

But agree the message should be better, let's see what I can do
