### ISSUE TITLE
os.chdir throws error when passing home shortcut (~) on Unix

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#16537]
### Describe the bug

On the unix platforms `chdir` from the `os` package throws an error when the tilda `~` is used as part of the path.
For examle:
`os.chdir('/home/${os.getenv('USER')}' !` changes directory as expected
`os.chdir('~/') !` fails

### Expected Behavior

`os.chdir` should be able to handle the tilda `~` character as part of a unix  path since it is commonly used in the said platform environments.

`os.chdir('~/') !` should not throw an error

### Current Behavior

`os.chdir` fails to change directory if path contains the tilda `~` character

`os.chdir('~/') !` throws an error

### Reproduction Steps

```v
module main

import os

fn main() {
	$if linux || darwin {
		good := '/home/${os.getenv('USER')}'
		os.chdir(good) or { println('Cannot chdr to ${good}') }
		bad := '~/'
		os.chdir(bad) or { println('Cannot chdir to ${bad}') }
	}
}
```

### Possible Solution

Parse the string on Unix platforms, replace `~` with `/home/${os.getenv('USER')}` since both should be equivalent

### Additional Information/Context

Issue only happens on a unix platform (Linux $macOS tested)

### V version

0.3.2

### Environment details (OS name and version, etc.)

Linux version 6.0.8-300.fc37.x86_64

**Comment by thomaspeissl** [comment]
Please use `os.home_dir()`
https://modules.vlang.io/os.html#home_dir

In your example:
```v
os.chdir(os.home_dir()) ...
```

**Comment by duarteroso** [comment]
> Please use `os.home_dir()` https://modules.vlang.io/os.html#home_dir
> 
> In your example:
> 
> ```v
> os.chdir(os.home_dir()) ...
> ```

Nice workaround, thanks @thomaspeissl !
But I still consider it as a workaround; there is no reason why `os.chdir` couldn't handle `~` 🥲

**Comment by JalonSolov** [comment]
Because the shell is what handles `~`, not the libraries.  There is no system call to handle it, so C doesn't, Java doesn't, etc.  Especially since you could change it in your shell (`HOME=/some/odd/dir` on Unix-y systems), and that's what `~` would mean after that change.

**Comment by duarteroso** [comment]
> Because the shell is what handles `~`, not the libraries.  There is no system call to handle it, so C doesn't, Java doesn't, etc.  Especially since you could change it in your shell (`HOME=/some/odd/dir` on Unix-y systems), and that's what `~` would mean after that change.

That makes sense. I understand that parsing the string and replace the ~ with HOME could be out of the scope of chdir... 

Can we somehow have it in the documentation? I fear people might waste some time wondering why chdir threw an error 👍

**Comment by Larpon** [comment]
> Can we somehow have it in the documentation? I fear people might waste some time wondering why chdir threw an error

We could, but what about the many other functions that uses file system paths? Should they also all have the same note? Here's just a few I can think of:
`os.ls`, `os.join_path`, `os.is_dir`, `os.is_file`
... I'm sure there's plenty more. All these does not expand `~`. 🤷🏻‍♂️

**Comment by duarteroso** [comment]
Fair point!
