### ISSUE TITLE
match c generation is wrong

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#16554]
### Describe the bug

match c generation is wrong.

### Expected Behavior

It should print

false
true

### Current Behavior

It prints

false
false

### Reproduction Steps

```
fn main() {
	mut a := true
	b := a && match true {
		true {
			a = false
			true
		}
		false {
			false
		}
	}
	println(a)
	println(b)
}
```

### Possible Solution

Same as here: https://github.com/vlang/v/pull/11182

### V version

0.3.2

### Environment details (OS name and version, etc.)

Windows

**Comment by danieldaeschle** [comment]
@yuyi98

**Comment by yuyi98** [comment]
Thanks ! I'll try.
