### ISSUE TITLE
No error given for `type name` used as `const ident`

### ISSUE THREAD

**Issue by Delta456** [vlang/v#16582]
### Describe the bug

A simple program with code:

```v
const int = 3
```

### Expected Behavior

An error like ``` invalid use of reserved type `int` as a constant name```

### Current Behavior

Successfully compiled

### Reproduction Steps

Same as given.

### Possible Solution

A checker to add the needed check.

### V version

https://github.com/vlang/v/commit/f5d0ba318e6e9fbf1068432442dc8b4ab64e5bea

### Environment details (OS name and version, etc.)

WSL 2 Windows 11

**Comment by changrui** [comment]
`const int = 1.23 println(typeof(int).name)` ---> `float literal`.
