### ISSUE TITLE
V compilation Error

### ISSUE THREAD

**Issue by tsikorksi** [vlang/v#1658]
**V version:** 0.1.18
**OS:** Windows 10 Version	10.0.18362 Build 18362

**What did you do?**
Tried to to compile V

**What did you expect to see?**
No errors
 
**What did you see instead?**
```curl -o v.c -LsSf https://raw.githubusercontent.com/vlang/vc/master/v.c
cc -std=gnu11 -w -o v v.c -lm
./v -o v compiler
cc: error: unrecognized command line option '-mmacosx-version-min=10.7'V panic: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
make: *** [Makefile:8: all] Error 1
```

Attempting to test V leads to :

```
cc: error: unrecognized command line option '-mmacosx-version-min=10.7'V panic: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
./compiler/tests/defer_test.v failed
````

**Comment by emily33901** [comment]
Are you building inside cygwin?

**Comment by medvednikov** [comment]
We should detect cygwin and notify the user that it's not supported and there's no point in using it :)

**Comment by Rendims** [comment]
I think I got the same error when I tried V on MSYS2/mingw64 since its the only C compiler I have on Windows. So if cygwin users are notified then mingw users should also be notified.

**Comment by medvednikov** [comment]
mingw-w64 should work fine

**Comment by Freshia** [comment]
> We should detect cygwin and notify the user that it's not supported and there's no point in using it :)

Yes, this should be documented. I'm getting this error on cygwin

**Comment by medvednikov** [comment]
Cygwin is now detected, an error is printed.
