### ISSUE TITLE
map causes a compiler bug error.

### ISSUE THREAD

**Issue by Sydiepus** [vlang/v#16594]
### Describe the bug

when trying to declare a  map with a key of type string and a value of type datatypes.Stack<int>{}
 program doesn't compile and state that this is a compiler bug.

```v
import datatypes

p := map[string]datatypes.Stack<int>{}
println(p)
```

### Expected Behavior

I expect a map with the specified key value type to be declared.

### Current Behavior

Throws this error and program is not compiled.
 ```
/tmp/v_1000/t.17442098459935223959.tmp.c:2244: warning: implicit declaration of function 'indent_datatypes__Stack_T_int_str'
/tmp/v_1000/t.17442098459935223959.tmp.c:2244: error: cannot convert 'int' to 'struct string'
```

### Reproduction Steps

Try to declare a map with key of type string and value of type `datatypes.Stack<int>` or `datatypes.Queue<int>` 

### Possible Solution

Throw a friendly error if such operation is not possible like when trying to use value of type [void](https://github.com/vlang/v/blob/7e9e2ff45994c3f6c348e8e6b181fd9ea91df209/vlib/v/parser/parse_type.v#L138)

### V version

V 0.3.2 7e9e2ff

### Environment details (OS name and version, etc.)

```
OS: linux, Pop!_OS 22.04 LTS
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
CC version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

getwd: /home/mp/AOC/day2
vmodules: /home/mp/.vmodules
vroot: /home/mp/Downloads/v
vexe: /home/mp/Downloads/v/v
vexe mtime: 2022-12-05 06:59:16
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 ffc73bf

Git version: git version 2.34.1
Git vroot status: Error: fatal: bad revision 'HEAD'
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

**Comment by Delta456** [comment]
This is the program which gives the same error as OP:

```v
import datatypes

p := map[string]datatypes.Stack<int>{}
println(p)
```
