### ISSUE TITLE
Unreachable code on return when not calling from function

### ISSUE THREAD

**Issue by Henrixounez** [vlang/v#1663]
**V version:** 0.1.18

**What did you do?**
```
fn test() string {
  return 'foo'
}
test()
```

**What did you expect to see?**
To compile
 
**What did you see instead?**
`test.v:4 unreachable code`

**Note**
It compiles by wrapping the test call with a main function, for example :
```
fn test() string {
  return 'foo'
}
fn main() {
  test()
}
```

**Comment by xuwenzhi** [comment]
I don't think it's bug. The main function is a commonly concept for many languages. If compiler support wrapping the main function implicitly, it will bring confusing to programmer.  I think the best way is expose it.

Welcome to talk.

**Comment by rustomax** [comment]
Similar example from the "official" v introduction https://vlang.io/docs#methods will result in `unreachable code` compilation error as well:

```
// oop.v:

struct User {
    age int
} 

fn (u User) can_register() bool {
    return u.age > 16
} 

user := User{age: 10}
println(user.can_register()) // ==> "false"

// v oop.v
// oop.v:9:4: unreachable code

```

So this seems to be a bug.

**Comment by gslicer** [comment]
From the official documentation: "fn main() declaration can be skipped in **one file** programs. This is useful when writing small programs, "scripts", or just learning the language." - so it would be a bug accordingly
