### ISSUE TITLE
copying a fixed array passed through a function results in nonsense.

### ISSUE THREAD

**Issue by Uhrbaan** [vlang/v#16640]
### Describe the bug

when copying a fixed size array through a function, it results in corrupting the resulting array
~~~v
// input a = [1, 2]
fn  copy(a [2]int) {
	tmp := a
	println(a) // [1, 2]
	println(tmp) // [-1407365200, 32765]
}
~~~

### Expected Behavior

the last println should also print `[1, 2]`

### Current Behavior

the result of the copied array is something completely different, its values seem random.

### Reproduction Steps

code to reproduce
~~~v
module main

fn print_fixed_arr(a [2]int) {
	tmp := a
	println(a) // [1, 2]
	println(tmp) // [-1407365200, 32765]
}

fn main() {
	arr := [1, 2]!
	tmp := arr
	println(tmp) // [1, 2]
	print_fixed_arr(arr)
}
~~~
output:
~~~
[1, 2]
[1, 2]
[-1407365200, 32765] // this is completely random
~~~

### Possible Solution

the problem (according to my testing) is that in the generated c code, the array that is passed through the function doesn't get dereferenced. When changing the C code to dereference `a`, it works as expected
~~~c
// generated V code
VV_LOCAL_SYMBOL void main__print_fixed_arr(Array_fixed_int_2 a) {
	Array_fixed_int_2 tmp;
	printf("a: %p, tmp: %p", a, tmp);
	printf("[%d, %d]", a[0], a[1]);
	memcpy((Array_fixed_int_2*)tmp, (byte*)&a, sizeof(Array_fixed_int_2));
        //                              ~~~~~~~^~~
	println(Array_fixed_int_2_str(a));
	println(Array_fixed_int_2_str(tmp));
}
~~~
~~~c 
// pure C
void print_fixed_array(int a[2]) {
    int tmp[2];
    memcpy(&tmp, &a, sizeof(int[2]));
    printf("[%d, %d] (%p)\n", a[0], a[1], &a); // [1, 2]
    printf("[%d, %d] (%p)\n", tmp[0], tmp[1], &tmp); // [-1407365200, 32765]
}
~~~

to solve the problem , `a` can be dereferenced
~~~c
void print_fixed_array(int a[2]) {
    int tmp[2];
    memcpy(&tmp, a, sizeof(int[
    // ~~~~~~~~~^~~~~~~~~~~~~
    printf("[%d, %d] (%p)\n", a[0], a[1], &a); // [1, 2]
    printf("[%d, %d] (%p)\n", tmp[0], tmp[1], &tmp); // [1, 2]
}
~~~
the second output the is `[1, 2]` as expected

### Additional Information/Context

this problem doesn't occur with normal arrays (dynamic)

### V version

V 0.3.2 799af2a

### Environment details (OS name and version, etc.)

OS: linux, "Manjaro Linux" Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz CC version: cc (GCC) 12.2.0  getwd: /home/uhrbaan/Documents/code/languages/v/AoC/2022 vmodules: /home/uhrbaan/.vmodules vroot: /home/uhrbaan/vlang/v vexe: /home/uhrbaan/vlang/v/v vexe mtime: 2022-12-10 15:17:01 is vroot writable: true is vmodules writable: true V full version: V 0.3.2 ef5be22.799af2a  Git version: git version 2.38.1 Git vroot status: weekly.2022.49-13-g799af2ad .git/config present: true thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by spytheman** [comment]
Results with latest V 4b2699f:
```
[1, 2]
[1, 2]
[1, 2]
```
