### ISSUE TITLE
Translate sqlite c2v fails

### ISSUE THREAD

**Issue by neimanpinchas** [vlang/v#16647]
### Describe the bug

I am trying to translate sqlite3.c to v, instead of using a wrapper but getting this error,
```
psn@HP-Z420-WORKSTATION ~/.v/sqlite> v -v translate sqlite3.c 
launch_tool vexe        : /home/psn/v/v/v
launch_tool vroot       : /home/psn/v/v
launch_tool tool_source : /home/psn/v/v/cmd/tools/translate.v
launch_tool tool_exe    : /home/psn/v/v/cmd/tools/translate
launch_tool tool_args   : '-v' 'translate' 'sqlite3.c'
launch_tool should_compile: false
C to V translator 0.3.1
  translating sqlite3.c       ... error: unknown argument: '-ast-dump=json'

The file sqlite3.c could not be parsed as a C source file.
C2V command: '/home/psn/.vmodules/c2v/c2v' 'translate' 'sqlite3.c'
C2V failed to translate the C files. Please report it via GitHub.
```

```
launch_tool vexe        : /home/psn/v/v/v
launch_tool vroot       : /home/psn/v/v
launch_tool tool_source : /home/psn/v/v/cmd/tools/translate.v
launch_tool tool_exe    : /home/psn/v/v/cmd/tools/translate
launch_tool tool_args   : '-v' 'translate' 'sqlite3.c'
launch_tool should_compile: false
['/home/psn/.vmodules/c2v/c2v', 'translate', 'sqlite3.c']
C to V translator 0.3.1
  translating sqlite3.c       ... DA CMD
clang -I.   -w -Xclang -ast-dump=json -fsyntax-only -fno-diagnostics-color -c 'sqlite3.c'
EXT=.c out_ast=sqlite3.json
out_ast=sqlite3.json
error: unknown argument: '-ast-dump=json'

The file sqlite3.c could not be parsed as a C source file.
C2V command: '/home/psn/.vmodules/c2v/c2v' 'translate' 'sqlite3.c'
C2V failed to translate the C files. Please report it via GitHub.
```

### Expected Behavior

To compile

### Current Behavior

Some error, seems to be related with clang

### Reproduction Steps

Do i need to upload a clone of my whole disk?

### V version

V 0.3.2 73e886e

### Environment details (OS name and version, etc.)

OS: linux, Linux Mint 19.1 Tessa (VM)
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
CC version: cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

getwd: /home/psn/.vmodules/c2v
vmodules: /home/psn/.vmodules
vroot: /home/psn/v/v
vexe: /home/psn/v/v/v
vexe mtime: 2022-12-11 10:56:22
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 73e886e

Git version: git version 2.17.1
Git vroot status: weekly.2022.49-21-g73e886ea
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by JalonSolov** [comment]
Looks like you need a much later version of clang.  If your cc is a link to clang, this is saying you have v7.5.0... I don't know when the -ast-dump option was added, but must have been after that.

**Comment by medvednikov** [comment]
It was added in late 2018.
