### ISSUE TITLE
C types from imported modules are not recognized

### ISSUE THREAD

**Issue by bbodi** [vlang/v#16650]
### Describe the bug

```v
import markdown


fn main() {
    // Uncomment this line to make it compile
    // _ := C.MD_BLOCK_H_DETAIL{1}
    _ := &C.MD_BLOCK_H_DETAIL(0)
}
```

### Expected Behavior

Should it compile? Shouldn't it be `markdown.MD_BLOCK_H_DETAIL`?

### Current Behavior

```
bug.v:1:8: warning: module 'markdown' is imported but never used
    1 | import markdown
      |        ~~~~~~~~
    2 |
    3 |
bug.v:7:9: error: unknown function: C.MD_BLOCK_H_DETAIL
    5 |     // Uncomment this line to make it compile
    6 |     // _ := C.MD_BLOCK_H_DETAIL{1}
    7 |     _ := &C.MD_BLOCK_H_DETAIL(0)
      |            ~~~~~~~~~~~~~~~~~~~~
    8 | }
```

### Reproduction Steps

Run the code in the description.

### V version

V 0.3.2 675a1be.ad24c22

### Environment details (OS name and version, etc.)

OS: windows, Microsoft Windows 11 Pro v22000 64-bit
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
CC version: tcc version 0.9.27 (x86_64 Windows)

getwd: C:\dev\misc\v
vmodules: C:\Users\sharp\.vmodules
vroot: C:\dev\misc\v
vexe: C:\dev\misc\v\v.exe
vexe mtime: 2022-12-11 14:47:43
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 675a1be.ad24c22

Git version: git version 2.34.1.windows.1
Git vroot status: weekly.2022.49-22-gad24c222
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 cb89a4fe

**Comment by spytheman** [comment]
No, it is a fundamental problem - C symbol names are global, and not subject to the V module system :-( .

It is a problem for other reasons too - you can have several modules that declare the same C symbol with a different declaration, and then your program may or may not get a conflict resulting in a C compilation error, depending on how the 2 modules use those different declarations.

**Comment by spytheman** [comment]
One workaround for some of it is to declare a V type alias for the C type in the module that wraps the C API, then all the rest could use the normal V type name instead, which *is* namespaced unlike the `C.` one.
