### ISSUE TITLE
'v' module shows up twice in stdlib documentation

### ISSUE THREAD

**Issue by tedstoychev** [vlang/v#16656]
### Describe the issue

Just to bring the team's attention to something I noticed - the 'v' module shows up twice in https://modules.vlang.io (See attached video).

Is this a bug?

https://user-images.githubusercontent.com/1466111/207058618-dde8b37e-a335-47ea-985a-35c2bf40c6be.mov

### Links

https://modules.vlang.io

**Comment by JalonSolov** [comment]
This appears to have been fixed at some point... `v` doesn't show up as a top-level thing at all now (and shouldn't have before).
