### ISSUE TITLE
Initializing an array of option type does not work

### ISSUE THREAD

**Issue by bbodi** [vlang/v#16651]
### Describe the bug

Initializing an array of optional type does not work

### Expected Behavior

It should compile

### Current Behavior

```
bug.v:10:11: error: unexpected token `?`
   10 |     _ := []?Cell{len:12}
      |           ^
```

### Reproduction Steps

```
struct Cell {}
fn main() {
    _ := []?Cell{len:12}
}
```

### V version

V 0.3.2 675a1be.ad24c22

### Environment details (OS name and version, etc.)

OS: windows, Microsoft Windows 11 Pro v22000 64-bit
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
CC version: tcc version 0.9.27 (x86_64 Windows)

getwd: C:\dev\misc\v
vmodules: C:\Users\sharp\.vmodules
vroot: C:\dev\misc\v
vexe: C:\dev\misc\v\v.exe
vexe mtime: 2022-12-11 14:47:43
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 675a1be.ad24c22

Git version: git version 2.34.1.windows.1
Git vroot status: weekly.2022.49-22-gad24c222
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 cb89a4fe

**Comment by spytheman** [comment]
Fixed by 1e7208d .
