### ISSUE TITLE
Generics that are not part of the base type are not accepted for their methods

### ISSUE THREAD

**Issue by bbodi** [vlang/v#16668]
### Describe the bug

```v
module main

pub struct Maybe[T] {
    present bool
    val     T
}
pub fn some[T](t T) Maybe[T] {
    return Maybe[T]{true, t}
}

pub fn (me Maybe[T]) map[T, U](f fn(T) U) Maybe[U] {
    if me.present {
        return Maybe[U]{true, f(me.val)}  
        
        // Comment this and the other line out for crashing the compiler
        // return Maybe[T]{true, f(me.val)}
    }
    return Maybe[U]{}
    // return Maybe[T]{}
}

pub fn (o Maybe[T]) get() ?T {
    if o.present {
        return o.val
    } else {
        return none
    }
}

fn main() {
    m := some[int](12)
    dump(m.map[int, string](fn(i int) string {return i.str()}))
}
```

### Expected Behavior

It should compile and dump a Maybe{true, string}`

### Current Behavior

Compiler error:
```
#0 20:25:58 ᛋ master /v/vnew❱v b.v 
b.v:22:11: error: generic type name `U` is not mentioned in fn `get[T]`
   20 | }
   21 | 
   22 | pub fn (o Maybe[T]) get() ?T {
      |           ~~~~~~~~
   23 |     if o.present {
   24 |         return o.val
b.v:7:21: error: generic type name `U` is not mentioned in fn `some[T]`
    5 |     val     T
    6 | }
    7 | pub fn some[T](t T) Maybe[T] {
      |                     ~~~~~~~~
    8 |     return Maybe[T]{true, t}
    9 | }
b.v:8:12: error: cannot use `Maybe[int]` as type `Maybe[]` in return argument
    6 | }
    7 | pub fn some[T](t T) Maybe[T] {
    8 |     return Maybe[T]{true, t}
      |            ~~~~~~~~~~~~~~~~~
    9 | }
   10 |
```

### Reproduction Steps

Try to compile the example with latest V.

### V version

V 0.3.2 675a1be.992621b

### Environment details (OS name and version, etc.)

OS: windows, Microsoft Windows 11 Pro v22000 64-bit
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
CC version: tcc version 0.9.27 (x86_64 Windows)

getwd: C:\dev\misc\v\bug
vmodules: C:\Users\sharp\.vmodules
vroot: C:\dev\misc\v
vexe: C:\dev\misc\v\v.exe
vexe mtime: 2022-12-12 20:24:23
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 675a1be.992621b

Git version: git version 2.34.1.windows.1
Git vroot status: weekly.2022.50 (2 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 cb89a4fe

**Comment by spytheman** [comment]
Note: if I comment pub fn (me Maybe[T]) map[T, U](f fn(T) U) Maybe[U] { and the call for it, it compiles .

**Comment by spytheman** [comment]
Note 2: Replacing the map method with this:
```v
pub fn (me Maybe[T]) map[T, U](f fn(T) U) Maybe[U] {
    if me.present {
        //return Maybe[U]{true, f(me.val)}  
        
        // Comment this and the other line out for crashing the compiler
        return Maybe[T]{true, f(me.val)}
    }
    //return Maybe[U]{}
    return Maybe[T]{}
}
```

leads to a cgen error.

**Comment by spytheman** [comment]
@yuyi98 can you please take a look, when you have time?

**Comment by yuyi98** [comment]
Thanks! I'll try to fix it.
