### ISSUE TITLE
Result/Option breaks execution order in if statements (related #16612)

### ISSUE THREAD

**Issue by yuyi98** [vlang/v#16663]
### Describe the bug

Result/Option breaks execution order in if statements.
```v
module main

fn f1() bool {
    println('f1')
    return true
}

fn f2() bool {
    println('f2')
    return true
}

fn f3() !bool {
    println('f3')
    return false
}

fn test() ! {
    println('test')
    if f1() {
        println('-> 01')
    } else if f2() && f3() ! {
        println('-> 02')
    } else {
        println('-> 03')
    }
}

fn main() { 
    test() or { panic(err) }
}
```

### Expected Behavior

test
f1
-> 01

### Current Behavior

test
f2
f3
f1
-> 01

### Reproduction Steps

```v
module main

fn f1() bool {
    println('f1')
    return true
}

fn f2() bool {
    println('f2')
    return true
}

fn f3() !bool {
    println('f3')
    return false
}

fn test() ! {
    println('test')
    if f1() {
        println('-> 01')
    } else if f2() && f3() ! {
        println('-> 02')
    } else {
        println('-> 03')
    }
}

fn main() { 
    test() or { panic(err) }
}
```

### V version

V 0.3.2 992621b

### Environment details (OS name and version, etc.)

OS: windows, Microsoft Windows 11 ��ͥ���İ� v22000 64 λ
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 6800H with Radeon Graphics
CC version: Error: exec failed (CreateProcess) with code 2: 系统找不到指定的文件。
 cmd: cc --version

getwd: D:\Vlang\v
vmodules: C:\Users\yuyi9\.vmodules
vroot: D:\Vlang\v
vexe: D:\Vlang\v\v.exe
vexe mtime: 2022-12-12 11:24:32
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 992621b

Git version: git version 2.37.3.windows.1
Git vroot status: weekly.2022.49-28-g992621bd
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 cb89a4fe

**Comment by felipensp** [comment]
This is because the actual generated C code is:

```C
VV_LOCAL_SYMBOL _result_void main__test(void) {
	println(_SLIT("test"));
	bool _t1 = (main__f2());
	_result_bool _t2;
	if (_t1) {
		_t2 = main__f3();
		if (_t2.is_error) {
			_result_void _t3;
			memcpy(&_t3, &_t2, sizeof(_result));
			return _t3;
		}
	}
	
 	if (main__f1()) {
		println(_SLIT("-> 01"));
	} else if ( _t1 &&  (*(bool*)_t2.data)) {
		println(_SLIT("-> 02"));
	} else {
		println(_SLIT("-> 03"));
	}
	return (_result_void){0};
}
```
