### ISSUE TITLE
size_t (and ptrdiff_t)

### ISSUE THREAD

**Issue by ntrel** [vlang/v#167]
Can we have something like C's `size_t` as a type alias for the largest unsigned integer supported by the system's hardware? Also `ptrdiff_t` as the type of an expression subtracting a pointer from another. I noticed that underscore isn't supported in type aliases though.

I think these could be defined in a special V module that is implicitly imported by V for all files - is this how `byte` and `int` work?

**Comment by medvednikov** [comment]
> I think these could be defined in a special V module that is implicitly imported by V for all files - is this how byte and int work?

Yes, defined in `builtin.v`. 

As for `size_t` and `ptrdiff_t`, sounds like a good idea, but I'll have to do research.

**Comment by ntrel** [comment]
Great! `size_t` is u64 on 64-bit machines, u32 on 32-bit. This is quite common, we should use it for the result of `some_array.len`.
`ptrdiff_t` is a signed integer, i64 on 64-bit, i32 on 32-bit. This is not used often, but useful sometimes.

**Comment by ntrel** [comment]
BTW Rust calls size_t `usize` and ptrdiff_t `isize`.

**Comment by nedpals** [comment]
Just an update: `size_t` has been implemented 9 days ago (See: https://github.com/vlang/v/commit/c6a15dba50674c660dfa4207e6d8726d45b3d03b)

**Comment by kitech** [comment]
I prefer rust 'usize' and 'isize', if it possible

**Comment by Gladear** [comment]
implemented in cc8ee5f
