### ISSUE TITLE
vlib rand.f32 returns 1.000000 but shouldn't

### ISSUE THREAD

**Issue by j-bm** [vlang/v#16707]
### Describe the bug

Documentation states the results should be between 0.0 (inclusive) and 1.0 (exclusive, that is, never equal to 1).

However this code, which should never complete, returns pretty quickly:

```
import rand

fn main() {
        println(' runcheckf32')
        mut sample := rand.f32()

        for {
                sample = rand.f32()
                if sample == f32(1.0) {
                        println('  sample == 1.00000')
                        break
                }
        }
}

```

### Expected Behavior

The program should _never_ complete.

### Current Behavior

It returns the message that 1.00000 was received from rand.f32().  It takes only a few seconds to return this result.

### Reproduction Steps

run the program.

Alternative test code:

```
import rand.constants

fn main() {

        println(' max u32 ${constants.max_u32}')
        println(' max u32_as_f32 ${constants.max_u32_as_f32}')
        ratio := f32(constants.max_u32) / constants.max_u32_as_f32
        println(' ratio ${ratio:9.7g}')
        println(' f32(1) - ratio ${f32(1.0) - ratio}')
        println(' f64(1) - ratio ${f64(1.0) - ratio}')
}

```

which is very approximately the same code in rand.v (divide a u32 pseudo-random by the constant max_u32_as_f32).

### Possible Solution

There are several possible options:

1) convert to f64, divide by the constant, round from f64 to f32 but check for equality with 1.0000 and restart if true

2) truncate/mask the random u32 to the mantissa size in bits, then divide by the constant.  This would require bit fiddling and a check for IEEE floating point conformance at compile time.   

3) Write the bit fiddler in C, and import that.

The assumption that f32(really_big_u32) == really_big_u32 is wrong and this is the main issue.

### Additional Information/Context

In principle, the f64 result has a similar bug, but only testing with the sample calculation proves it:

```
import rand.constants

fn main() {

        println(' max u64 ${constants.max_u64}')
        println(' max u64_as_f64 ${constants.max_u64_as_f64}')
        ratio := f64(constants.max_u64) / constants.max_u64_as_f64
        println(' ratio = ${ratio}')
        println(' f64(1) - ratio = ${f64(1.0) - ratio}')
}

```

### V version

V 0.3.2 d7c244e

### Environment details (OS name and version, etc.)

OpenBSD recent v self-update.

**Comment by hungrybluedev** [comment]
I'll try to fix this next week.

**Comment by j-bm** [comment]
There are many ways to convert int/uint to floats/doubles: here is one I just tested. The constants come from ieee arithmetic conversions to decimal.  Hopefully these are stable across compilers/platforms.

import rand
import rand.constants

fn main() {
        float_eps := 1.19209290E-07
        doubl_eps := 2.2204460492503131E-16

        println(' minrand f ${float_eps} again ${ 0x1 * float_eps}')
        println(' minrand d ${doubl_eps} again ${ 0x1 * doubl_eps}')

        println(' maxrand f ${f32(float_eps * (constants.max_u32 >> 9))}')
        println(' maxrand d ${doubl_eps * (constants.max_u64 >> 12)}')

}

**Comment by JalonSolov** [comment]
The referenced issue was converted to a discussion:  https://github.com/vlang/v/discussions/16714
