### ISSUE TITLE
generics: error with nested generics

### ISSUE THREAD

**Issue by markus-oberhumer** [vlang/v#16709]
### Describe the bug

First many thanks for your work in #16518 and #16677 !

Here is my continuation of exhaustive generics testing.

V Playground: https://play.vlang.io/?query=b9295476d5

(Working) Go playground version is at https://go.dev/play/p/cznshBdB_yJ

```v
struct Tuple2[A, B] {
	a A
	b B
}

// map to array of Tuple2[int, Tuple2[key, value]] tuples
fn map_to_array_int_kv[K, V](m map[K]V) []Tuple2[int, Tuple2[K, V]] {
	mut r := []Tuple2[int, Tuple2[K, V]]{cap: m.len}
	mut i := 0
	for k, v in m {
		r << Tuple2[int, Tuple2[K, V]]{i, Tuple2[K, V]{k, v}}
		i += 1
	}
	return r
}

// map to array of Tuple2[int, Tuple2[Tuple2[key, value], Tuple2[value, key]]] tuples
fn map_to_array_int_kv_vk[K, V](m map[K]V) []Tuple2[int, Tuple2[Tuple2[K, V], Tuple2[V, K]]] {
	mut r := []Tuple2[int, Tuple2[Tuple2[K, V], Tuple2[V, K]]]{cap: m.len}
	mut i := 0
	for k, v in m {
		r << Tuple2[int, Tuple2[Tuple2[K, V], Tuple2[V, K]]]{i, Tuple2[Tuple2[K, V], Tuple2[V, K]]{Tuple2[K, V]{k, v}, Tuple2[V, K]{v, k}}}
		i += 1
	}
	return r
}

fn main() {
	x := {
		'one': 1
		'two': 2
	}
	y := {
		3: 'three'
		4: 'four'
	}

	println(x)
	println(map_to_array_int_kv(x))
	println(map_to_array_int_kv_vk(x))

	println(y)
	println(map_to_array_int_kv(y))
	println(map_to_array_int_kv_vk(y))
}
```

### Expected Behavior

No compilation error.

### Current Behavior

error: the parameter type name of a generic struct, must be a single capital letter placeholder name,
like T or X, or a non-generic type name like int, string, etc.

### Reproduction Steps

V Playground: https://play.vlang.io/?query=b9295476d5

### V version

V 0.3.2 aad95ac (current git)

### Environment details (OS name and version, etc.)

Linux x86_64

**Comment by yuyi98** [comment]
Yes, this require fundamental changes.

**Comment by spytheman** [comment]
In @yuyi98's hands, even fundamental changes take a day or two 🥳.

**Comment by spytheman** [comment]
I just tested the PR that he made, and with it the example compiles and runs.

**Comment by Larpon** [comment]
@yuyi98 🤯
