### ISSUE TITLE
repl: Pipeline operation is not supported

### ISSUE THREAD

**Issue by smalltalkman** [vlang/v#1670]
**V version:** V 0.1.18
**OS:** MINGW32_NT-6.1-7601 x86_64

**What did you do?**
echo 33 | v

**What did you expect to see?**
33
 
**What did you see instead?**
```
V 0.1.18
Use Ctrl-C or `exit` to exit
>>>
```

**Comment by smalltalkman** [comment]
After using the patch in https://github.com/vlang/v/issues/1645, the pipeline is supported, but there is an error in https://github.com/vlang/v/issues/1669.

**Comment by Henrixounez** [comment]
There's no problem on my side (on linux) :
```
$ echo 33 | ./v
V 0.1.18
Use Ctrl-C or `exit` to exit
>>> 33
>>>
```

**Comment by smalltalkman** [comment]
@Henrixounez error appears on window(mingw-w64, both mingw32 and ming64)

**Comment by smalltalkman** [comment]
Fixed by https://github.com/vlang/v/pull/1733

**Comment by medvednikov** [comment]
Fixed.
