### ISSUE TITLE
Passing object by reference in operator overloader < fails

### ISSUE THREAD

**Issue by brandonpille** [vlang/v#16725]
### Describe the bug

The following piece of code fails to compile and results in builder error:
```
pub fn (a &Resources) < (b &Resources) bool {
    // do some stuff
}
```
It doesn't get the error when I pass the objects by value.

### Expected Behavior

If you cannot pass the objects by reference the compiler should print a suitable message instead of failing to build. 

### Current Behavior

I get this building error message:
```
==================
/tmp/v_1000/farmerbot.4221029893376103648.tmp.c:12192: error: cannot convert 'struct main__Resources' to 'struct main__Resources *'
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

### Reproduction Steps

This code reproduces the error:
```
pub struct Resources {
mut:
    hru u64
	sru u64
    cru u64
    mru u64
}

pub fn (a &Resources) < (b &Resources) bool {
    return a.hru < b.hru && a.sru < b.sru && a.cru < b.cru && a.mru < b.mru
}
```

### Possible Solution

Either show a proper message or allow passing by reference. 

### V version

0.3.2

### Environment details (OS name and version, etc.)

OS: linux, Ubuntu 22.04.1 LTS
Processor: 16 cpus, 64bit, little endian, 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
CC version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

getwd: /work/farmerbot
vmodules: /home/brandon/.vmodules
vroot: /work/v
vexe: /work/v/v
vexe mtime: 2022-12-16 10:16:25
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 f0a252d

Git version: git version 2.34.1
Git vroot status: weekly.2022.50-24-gf0a252d0 (21 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by Delta456** [comment]
I will work on a fix soon. It is also related to https://github.com/vlang/v/issues/15859.
