### ISSUE TITLE
thirdparty/mbedtls/library/aesni.c:131: error: invalid clobber register 'xmm0'

### ISSUE THREAD

**Issue by yonas** [vlang/v#16727]
### Describe the bug

Running examples that use mbedtls results in a `invalid clobber register 'xmm0'` error.

### Expected Behavior

It should not produce this error.

### Current Behavior

```
$ ./v run examples/http_server.v 
failed thirdparty object build cmd:
'/git/v/thirdparty/tcc/tcc.exe'   -std=c99 -D_DEFAULT_SOURCE -D__RUNETYPE_INTERNAL  -fPIC -I "/git/v/thirdparty/mbedtls/library" -I "/git/v/thirdparty/mbedtls/include" -I "/git/v/thirdparty/mbedtls/3rdparty/everest/include" -I "/git/v/thirdparty/mbedtls/3rdparty/everest/include/everest" -I "/git/v/thirdparty/mbedtls/3rdparty/everest/include/everest/kremlib" -o '/home/yonas/.vmodules/cache/2e/2e7eb4ea2c6b6a0e25c14ae65bd960cd.module.net.mbedtls.o' -c '/git/v/thirdparty/mbedtls/library/aesni.c'                                                                                                         
builder error: /git/v/thirdparty/mbedtls/library/aesni.c:131: error: invalid clobber register 'xmm0'    
```

### Reproduction Steps

Run `./v run examples/http_server.v`

### V version

0.3.2 d19c1ef

### Environment details (OS name and version, etc.)

FreeBSD 13.1

`v doctor` did not produce any output.

**Comment by SurmanPP** [comment]
Have you tried compiling with gcc or clang adding `-cc gcc` or `-cc clang` to the command and can you also add your processor architecture to the issue?

This code that fails compiling is some optimized function using inline assembly and Streaming SIMD Extensions(SSE). Which allows the processor to process similar data at once. Maybe tcc on your platform does not support SSE or your platform does not support it.

**Comment by yonas** [comment]
@SurmanPP Thanks! It compiles now.

A second issue - it doesn't actually listen on any ports (it doesn't show up in `sockstat -4`).

**Comment by SurmanPP** [comment]
What happens if you open http://localhost:8080 in your browser(while the program is running)?

**Comment by yonas** [comment]
@SurmanPP 

```
$ xh http://localhost:8080
xh: error: error sending request for url (http://localhost:8080/): error trying to connect: tcp connect error: Connection refused (os error 61)

Caused by:
    0: error trying to connect: tcp connect error: Connection refused (os error 61)
    1: tcp connect error: Connection refused (os error 61)
    2: Connection refused (os error 61)
```

**Comment by JalonSolov** [comment]
Is that `xh` command this: https://github.com/ducaale/xh ?

Can you try with a browser, instead of this tool?

**Comment by yonas** [comment]
> Is that xh command this: https://github.com/ducaale/xh ?

@JalonSolov Yes it is.

> Can you try with a browser, instead of this tool?

No, but I can assure you it's not listening on the port:

```
$ telnet localhost 8080
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
```

**Comment by JalonSolov** [comment]
What do you see when you try to run the example?  This is what I see:
```
$ v run examples/http_server.v
Listening on :8080
```
And did you actually run it, or just compile it?  Your command (`v -cc clang examples/http_server.v`) would only compile.

**Comment by yonas** [comment]
> And did you actually run it, or just compile it? 

I tried both. This is the output:

```
$ http_server
Listening on :8080
```

**Comment by JalonSolov** [comment]
Very strange.  It all works as expected on Linux, so this appears to be FreeBSD specific.

**Comment by yonas** [comment]
Thanks @JalonSolov , I'll close this as completed, and refer to #16826 for the TCP issue.
