### ISSUE TITLE
Division by zero with other u64

### ISSUE THREAD

**Issue by ghost** [vlang/v#1672]
**V version:** 0.1.18
**OS:** Ubuntu 18.04.2 LTS (Bionic Beaver)

**What did you do?**

```
println(u64(4) % u64(0))
```

**What did you expect to see?**

> .vrepl.v:2 division by zero
 
**What did you see instead?**

> Floating point exception (core dumped)

**Comment by baziotis** [comment]
That's not a bug. If the right-hand-side is constant, the compiler aborts the compilation if it is 0.
It was added recently for mod: https://github.com/vlang/v/commit/72a7eb6e3541037ccbf4d1ca56a854f40ec99256

**Comment by medvednikov** [comment]
That fix only works with `0`.

**Comment by Delta456** [comment]
This can now be closed.

**Comment by Delta456** [comment]
It still doesn't give an error even with the new parser.

**Comment by VinWare** [comment]
Confirmed for every integer cast (signed and unsigned). Even `1/int(0)` results in floating point error.

V version 0.1.30
