### ISSUE TITLE
 bug that the compiler allowed init without len

### ISSUE THREAD

**Issue by Eliyaan** [vlang/v#16728]
@hungrybluedev 
### Describe the bug

The compiler allowed init without len

### Expected Behavior

*

### Current Behavior

*

### Reproduction Steps

import rand

const (
    lenn = 100
)

fn main(){
    mut list_elem := [][]f64{init:[0.0, 0.0]}
    mut elem := 0.0
    for i in 0..lenn{
        elem = rand.int_in_range(-100000000, 100000001)!
        list_elem[i] << [elem, elem]
    }
    println(list_elem)
}

### V version

Current V version: V 0.3.2 65a020e, timestamp: 2022-12-16 16:53:04 +0300

### Environment details (OS name and version, etc.)

WIndows 10 education

**Comment by changrui** [comment]
You may try this: `mut  list_elem := [][]f64{}`, then `list_elem << [elem, elem]`.
