### ISSUE TITLE
Impossible to compile most V apps (vpm, ved...)

### ISSUE THREAD

**Issue by Andrflor** [vlang/v#16740]
### Describe the bug

I can compile hello world but I can't compile any complex app.
I also can't compile vpm so v install will fail.

### Expected Behavior

Should compile

### Current Behavior

cannot compile `/opt/v/cmd/tools/vpm.v`: 
failed thirdparty object build cmd:
'/opt/v/thirdparty/tcc/tcc.exe'   -std=gnu99 -D_DEFAULT_SOURCE  -fPIC -I "/opt/v/thirdparty/mbedtls/library" -I "/opt/v/thirdparty/mbedtls/include" -I "/opt/v/thirdparty/mbedtls/3rdparty/everest/include" -I "/opt/v/thirdparty/mbedtls/3rdparty/everest/include/everest" -I "/opt/v/thirdparty/mbedtls/3rdparty/everest/include/everest/kremlib" -o '/home/kensai/.vmodules/cache/e5/e5f5410dacb8fb5612d30a6d72b7f5f3.module.net.mbedtls.o' -c '/opt/v/thirdparty/mbedtls/library/aes.c'
builder error: In file included from /opt/v/thirdparty/mbedtls/library/aes.c:26:
In file included from /opt/v/thirdparty/mbedtls/library/common.h:28:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/include/stdint.h:11:
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/include/stdint-gcc.h:60: error: ';' expected (got "int_least8_t")

### Reproduction Steps

```bash
v install
```

### Possible Solution

It may be a problem with tcc??

### Additional Information/Context

stdint-gcc.h

```h
#ifdef __INT8_TYPE__
typedef __INT8_TYPE__ int8_t;
#endif
#ifdef __INT16_TYPE__
typedef __INT16_TYPE__ int16_t;
#endif
#ifdef __INT32_TYPE__
typedef __INT32_TYPE__ int32_t;
#endif
#ifdef __INT64_TYPE__
typedef __INT64_TYPE__ int64_t;
#endif
#ifdef __UINT8_TYPE__
typedef __UINT8_TYPE__ uint8_t;
#endif
#ifdef __UINT16_TYPE__
typedef __UINT16_TYPE__ uint16_t;
#endif
#ifdef __UINT32_TYPE__
typedef __UINT32_TYPE__ uint32_t;
#endif
#ifdef __UINT64_TYPE__
typedef __UINT64_TYPE__ uint64_t;
#endif

/* 7.8.1.2 Minimum-width integer types */

typedef __INT_LEAST8_TYPE__ int_least8_t;  /*<= This is line 60*/
typedef __INT_LEAST16_TYPE__ int_least16_t;
typedef __INT_LEAST32_TYPE__ int_least32_t;
typedef __INT_LEAST64_TYPE__ int_least64_t;
typedef __UINT_LEAST8_TYPE__ uint_least8_t;
typedef __UINT_LEAST16_TYPE__ uint_least16_t;
typedef __UINT_LEAST32_TYPE__ uint_least32_t;
typedef __UINT_LEAST64_TYPE__ uint_least64_t;
```

### V version

0.3.2 3c5cfa2

### Environment details (OS name and version, etc.)

OS: linux, "Arch Linux"
Processor: 24 cpus, 64bit, little endian, AMD Ryzen 9 3900XT 12-Core Processor
CC version: cc (GCC) 12.2.0

getwd: /home/kensai/project/ved
vmodules: /home/kensai/.vmodules
vroot: /opt/v
vexe: /opt/v/v
vexe mtime: 2022-12-22 06:48:04
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 3c5cfa2

Git version: git version 2.39.0
Git vroot status: weekly.2022.50-55-g3c5cfa22
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by spytheman** [comment]
Try `-cc gcc` as a temporary workaround.

**Comment by JalonSolov** [comment]
Interesting.  I'm on Manjaro (which is essentially Arch), same gcc, same `stdint-gcc.h`, and everything compiles cleanly for me.

**Comment by Andrflor** [comment]
Still having the exact same error with latest ` V 0.3.2 0230395`
Any idea what could cause it?
