### ISSUE TITLE
Cross-compilation to Windows does not work

### ISSUE THREAD

**Issue by apahl** [vlang/v#1674]
**V version:** V 0.1.18  
**OS:** Kubuntu 19.04

**What did you do?**
Compile a minimal program:

```
// hello01.v
module main

fn greet(greet string) {
    println('Hello $greet !')
}

fn main() {
    greet('Axel')
}
```

Compilation on native Linux platform works.  Compilation with `v -os windows .` fails.  
winroot and clang are available.

**What did you expect to see?**
Windows executable
 
**What did you see instead?**
An error message:
```
$ v -os windows .
Cross compiling for Windows...
clang: error: no such file or directory: '/home/pahl//.vmodules//hello01.c'
clang: error: no input files
Cross compilation for Windows failed. Make sure you have clang installed.

$ which clang
/usr/bin/clang

$ pwd
/home/pahl/dev/v/getting_started/hello01
```

Many thanks for your help.  
Kind regards, Axel

**Comment by medvednikov** [comment]
Fixed.
