### ISSUE TITLE
false immutable error?

### ISSUE THREAD

**Issue by mvlootman** [vlang/v#1676]
**V version: 0.1.18** 
**OS: macOS Mojave** 

**What did you do?**
Iterate array of structs, using the struct value as an indexer to modify another array.

result[rec.parent].children << TNode{id: rec.id}        // tree.v:22 `rec` is immutable (can't <<)

complete code:
```
import json

struct TNode {
pub:
        id      int
        children []TNode
}

struct Record{
pub:
        id      int
        parent  int
}

fn build(records []Record) ?TNode{
        if records.len == 0 { return Node{}}

        mut result :=  [TNode{}; records.len]

        for i, rec in records{
                result[rec.id] = TNode{id: rec.id}
                result[rec.parent].children << TNode{id: rec.id}        // tree.v:22 `rec` is immutable (can't <<)
                // result[records[i].parent].children << TNode{id: rec.id}    // does work
                
        }
        return result[0]
}


fn main(){
        mut recs := []Record
        recs << Record{id: 0, parent:0}
        recs << Record{id: 1, parent: 0}
        recs << Record{id: 2, parent: 0}


        n := build(recs) or {
                return
        }
        print_tnode(n)

}

fn print_tnode(tnode TNode){
        println('id:$tnode.id #childs:$tnode.children.len') 
        for cn in tnode.children{
                print_tnode(cn)
        }
}
```
**What did you expect to see?**
No errors about the need of the array to be mutable.
 
**What did you see instead?**
tree.v:22 `rec` is immutable (can't <<)

**Comment by medvednikov** [comment]
https://vlang.io/docs#for

> Note, that the value is read-only. If you need to modify the array while looping, you have to use indexing:

**Comment by medvednikov** [comment]
Oh never mind. It is a bug, thanks.

**Comment by medvednikov** [comment]
`children` field should also be declared with `mut:` inside the struct, but it's unrelated.

**Comment by mvlootman** [comment]
> `children` field should also be declared with `mut:` inside the struct, but it's unrelated.

Indeed, so it should error on that being immutable, not on the readonly variable.

First assigning the readonly value to a mutable variable, and using that to obtain the array index also works but it should not have to be mutable (from the client code perspective).

**Comment by kawa-yoiko** [comment]
I have sent two PRs #1790 and #1791, they will fix this together ^ ^
