### ISSUE TITLE
Modules sub-directory or cache?

### ISSUE THREAD

**Issue by x80486** [vlang/v#16763]
### Describe the issue

I started using `V` and the first thing that I did was to put the `.vmodules` sub-directory in the `XDG_CACHE_HOME` — you might want to consider using the `XDG Base Directory specification` (and friends) by default.

```shell
[[ ! -d "${HOME}/.cache/vmodules/" ]] && mkdir --parents "${HOME}/.cache/vmodules/"

export VMODULES="${HOME}/.cache/vmodules"
```

I noticed there is a `README.md` file created in that location. When I open it, there is a reference to a `VCACHE` environment variable as well.

```markdown
This folder contains cached build artifacts from the V build system.
You can safely delete it, if it is getting too large.
It will be recreated the next time you compile something with V.
You can change its location with the VCACHE environment variable.
```

I wonder if this is outdated and it should be `VMODULES` indeed — which currently works and it's what's [documented](https://github.com/vlang/v/blob/master/doc/docs.md#package-management) in the `V Documentation`, or the other way round?

### Links

N/A

**Comment by JalonSolov** [comment]
Not every system defines the `XDG` variables (especially Windows), so they can't be used by default.

`.vmodules` is where modules are installed BEFORE they are compiled.  `.vmodules/cache` is where built version of the modules are stored, by default.  This is so they don't have to be rebuilt unless you pull down a new version.  You can change the location of the installed modules and the cached versions of same using the 2 variables mentioned.

So the README is correct, as well as the documentation.

**Comment by x80486** [comment]
OK, I get it. I thought it was referring to the same thing.

Regarding the `XDG` business, I understand the `XDG Base Directory specification` is specific to Linux, but Windows and macOS has exactly the same — they are just called something else. For instance, I remember there was a `%USERPROFILE%` and `%LOCALAPPDATA%` in Windows.

My point is, for all those platforms, you can use their respective locations without having to create more sub-directories in the user's home.
