### ISSUE TITLE
checker: error: unknown struct `T`

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#16788]
### Describe the bug

```v
16691.v:8:13: error: unknown struct `T`
    6 | 
    7 | fn main() {
    8 |     func(struct{foo: 'foo'})
      |                ~~~~~~~~~~~~
    9 | }
```

### Expected Behavior

Good Error

### Current Behavior

Bad Error

### Reproduction Steps

```v
fn func[T](arg T) {
	$if T is $Struct {
		println(arg)
	}
}

fn main() {
	func(struct{foo: 'foo'})
}
```

### V version

V 0.3.2 afdb097

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by felipensp** [comment]
The comptime stuff is irrelevant for reproduce it.

```V
fn func[T](arg T) {}

fn main() {
	func(struct{foo: 'foo'})
}
```

**Comment by Delta456** [comment]
I don't think that should work because it is hard to figure out what type to derive for both user and the compiler.
