### ISSUE TITLE
repl: One error, all errors (on windows)

### ISSUE THREAD

**Issue by smalltalkman** [vlang/v#1680]
**V version:** V 0.1.18
**OS:** MINGW32_NT-6.1-7601 x86_64

**What did you do?**
in repl, input `a`, then `33`.

**What did you expect to see?**
```
V 0.1.18
Use Ctrl-C or `exit` to exit
>>> a
.vrepl_temp.v:2 undefined: `a`
>>> 33
33
>>>

```
 
**What did you see instead?**
```
V 0.1.18
Use Ctrl-C or `exit` to exit
>>> a
.vrepl_temp.v:2 undefined: `a`
>>> 33
.vrepl_temp.v:1 undefined: `a`
>>>

```

**Comment by Henrixounez** [comment]
#1657 Should have fixed it, can you please update and try again ?

**Comment by smalltalkman** [comment]
@Henrixounez  
When https://github.com/vlang/v/pull/1657 merged, the problem was solved, but it now appears again on Windows.
When I remove `r.lines << line` from the file `repl.v`, it can be solved.

**Comment by nedpals** [comment]
This error has been fixed already. Closed.
