### ISSUE TITLE
String Formatting

### ISSUE THREAD

**Issue by super-vip** [vlang/v#1681]
formatted string literals
https://docs.python.org/3.6/whatsnew/3.6.html#whatsnew36-pep498

**Comment by medvednikov** [comment]
V already has that:

`float = ${f:%.2f}`

I need to document that.

**Comment by ntrel** [comment]
> ${f:%.2f}

That's a string, right? Shouldn't it be `'${f:%.2f}'`? Also I think V can do better than the trailing char for the type of value to print. C needs it because varargs are untyped. We can infer it from `type(f)`, where `f` is the variable name at the start. Also for `.2`, floating point format could be inferred. For conversions, we could have `'${int(f):4}'`, which would print float f as an int with width 4.

**Comment by super-vip** [comment]
PEP498
This feature of python is very good, I hope to introduce it into v.

**Comment by medvednikov** [comment]
@ntrel yes, it's a string. Updated.

The formatting is ugly, but I want to use something everyone is familiar with. This is the same formatting used in C, C#, Java etc.

**Comment by ntrel** [comment]
Both Rust and the Text Formatting proposal (std::format) for C++20 (now in Committee Draft stage) support "{}" to use type inference on a passed argument. They don't have string interpolation so they have to pass the argument separately.

C# and even Java with MessageFormat support positional parameters with type inference using e.g. "{0}":
https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html

I think V should support formatting interpolated data without having to say what the type of it is, that is the modern way.

**Comment by ntrel** [comment]
And type inference still works when supplying width or precision.

Rust `format!("{:04}", 42);             // => "0042"`:
https://doc.rust-lang.org/std/fmt/#usage
C# `{0,12}` inserts a 12-character string from the first argument supplied:
https://docs.microsoft.com/en-us/dotnet/api/system.string.format?view=netframework-4.8#get-started-with-the-stringformat-method

**Comment by Kamforka** [comment]
How can you format using variables?

Intuitively I would do it like this:
```
name := "John Doe"
width := 20
println("Name: ${name:${width}}")
```
However it errors out:
`error: format specifier may only be one letter`

Then I tried to include it in another string:
```
println("Name: ${name:'${width}'}")
```

Which produced a very weird output:
`John Doe20'}`

Searched the docs but found no reference to this issue.

**Comment by JalonSolov** [comment]
V doesn't support nested interpolation.  And you for got the `s` anyway.  At least V does alert you to the issue now:
```
foo.v:3:23: error: unexpected token `$2`, expecting `,`
    1 | name := "John Doe"
    2 | width := 20
    3 | println("Name: ${name:${width}}")
      |                       ^
```

**Comment by Kamforka** [comment]
@JalonSolov what do you mean by forgot the `s`?

It is fine that at the moment nested interpolation is not supported, but I guess it should be on the roadmap as the language matures because for now this feature is pretty much limited and renders itself useless during advanced formatting.

**Comment by JalonSolov** [comment]
name := "John Doe"
width := 20
println("Name: ${name:${width}**s**}")

Yes, nested interpolation would be good.  There has been talk about changing the current to remove the `$` - always use `{}` instead.  Not there yet...
