### ISSUE TITLE
vlib/io/writer.v: typo in documentation

### ISSUE THREAD

**Issue by rillig** [vlang/v#16839]
### Describe the bug

The documentation contains a typo.

### Expected Behavior

The correct form is:
> can be written to

### Current Behavior

The documentation says 2 times:
> can be wrote to

### Reproduction Steps

Open `writer.v`.

### V version

current

### Environment details (OS name and version, etc.)

any

**Comment by KeitoTobi1** [comment]
Next time, please fix it yourself.
