### ISSUE TITLE
ORM should not hard-code SQL column `id`

### ISSUE THREAD

**Issue by iredmail** [vlang/v#1685]
Not all SQL tables has a column named `id`, so ORM should not expect this and hard-code this column name.

**Comment by spytheman** [comment]
@medvednikov I do not know the motivation behind requiring an `id` column in the ORM ?
It is trivial to remove these checks though.

**Comment by medvednikov** [comment]
It'll be possible to use different names:

```
[orm:MyUser]
struct User {
   id int [orm:user_id]
   ...
}
```

**Comment by iredmail** [comment]
@medvednikov Is this implemented or just an idea?

**Comment by joe-conigliaro** [comment]
You need some column to behave as a key for a ORM to properly handle relationships and joins, as well as other things. Preferably you want to use something which can be indexed well also for performance reasons. Of course it doesn't need to be called `id` or even be assigned a key in the database.

**Comment by iredmail** [comment]
We don’t have id column in many sql tables, but use something like “username” column as primary key.

**Comment by LouisSchmieder** [comment]
we have now an attribute `sql: serial` which sets the field to the type serial and the attribute `primary` which can set a field as primary key, so it's now implemented
