### ISSUE TITLE
cgen?: indexing unreal map key

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#16860]
### Describe the bug

It's returning a default value from a key that doesn't exist yet. I imagine, it will be said that this is the right behavior. But, if it is right, how can I convert a  map value in an optional struct field. How will I know if the value is zero or none?

### Expected Behavior

return none (perfect) or a error

### Current Behavior

return 0

### Reproduction Steps

```v
fn main() {
	mapa := {
		"a": 0
		"b": 1
	}
	dump(mapa['c'])
}
```

### V version

V 0.3.2

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by JalonSolov** [comment]
It is documented this way.  You can check using `if` or `or` block.  Read under https://github.com/vlang/v/blob/master/doc/docs.md#maps
