### ISSUE TITLE
feat: `json` use the same strategy than `x.json2` for encode `none`

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#16868]
### Describe the feature

json encode none as null while json2 don't encode none

```v
import json
import x.json2

struct Foo {
	name string
	num  ?int
}

fn main() {
	f1 := Foo{}

	ret1 := json.encode(f1)
	assert ret1 == '{"name":"","num":null}'

	ret2 := json2.encode(f1)
	assert ret2 == '{"name":""}'
}
```

### Use Case

For example: in a web application, the back-end receive '{"name":"hello","num":null}', the database will create {"name":"hello","num":null} instead of {"name":"hello"} what can do a lot of difference in bussiness logic for mongo applications, for example.
beyond some performance and memory usage issues
relating v none with typescript undefined, for example, you have none and nil as 2 completely different https://basarat.gitbook.io/typescript/recap/null-undefined#json-and-serialization

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.3.2

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by JalonSolov** [comment]
`json` is encoding correctly.  `json2` should be encoding `none` as `null`.

`json2` is currently acting as if the `omitempty` attribute was set on the field.

(I don't know if `omitempty` was ever implemented for V - I suggested it a long, long time ago.  Go has it, and it is very useful.)

**Comment by JalonSolov** [comment]
`null` should also be _decoded_ as `none`, for Option fields.

**Comment by enghitalo** [comment]
Maybe we need a discussion about what is nil and what is none. because, at this point, I no longer see a difference, then. :crying_cat_face: 

Or nil is just for pointer and none is the new type null?

**Comment by enghitalo** [comment]
> 

imho `omitempty` attribute is a error and increase the code complexity.
see: https://www.bennadel.com/blog/4016-consuming-sparse-unpredictable-omitempty-golang-json-payloads-using-null-coalescing-in-lucee-cfml-5-3-7-48.htm

**Comment by JalonSolov** [comment]
That's one case.  There are many others, including just as many where using omitempty is a _good_ thing.  Regardless, it should be available for those who wish to use it.

**Comment by spytheman** [comment]
> `omitempty`

Yes, it was implemented, but it is/was a hack around the lack of option fields, and it acted by comparing the value to the default value for the type, and skipping the field if they were the same.

Now, that we do have option fields, we have to support them, including the case where they are `none`.
