### ISSUE TITLE
builder error: C error - cannot convert 'struct string' to 'void *'

### ISSUE THREAD

**Issue by bjones1** [vlang/v#16863]
### Describe the bug

Given the two source files attached, v produces a builder error. 

### Expected Behavior

I expected a syntax error such as:

```
bug.v:3:16: error: method `[]string.push` is private
    1 | fn foo() {
    2 |     mut regex_strings := []string{}
    3 |     regex_strings.push("b")
      |                   ~~~~~~~~~
    4 | }
```

### Current Behavior

The error is:

```
bjones@gv41y33:/mnt/c/Users/bjones/Documents/git/CodeChat_Editor/server$ v -cg test bug_test.v
---- Testing... -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 FAIL   985.095 ms /mnt/c/Users/bjones/Documents/git/CodeChat_Editor/server/bug_test.v
/tmp/v_1000/tsession_7fd434892b80_36405274451700/bug_test.2450084029028201485.tmp.c:35440: error: cannot convert 'struct string' to 'void *'
builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Failed command 1:    '/home/bjones/tmp/v/v' -cg  -o '/tmp/v_1000/tsession_7fd434892b80_36405274451700/bug_test' '/mnt/c/Users/bjones/Documents/git/CodeChat_Editor/server/bug_test.v'
Summary for all V _test.v files: 1 failed, 1 total. Runtime: 988 ms, on 1 job.
```

### Reproduction Steps

`v test bug_test.v`

The files are attached.
[bug.zip](https://github.com/vlang/v/files/10340328/bug.zip)

For convenience, they are:

#### bug.v
```
fn foo() {
	mut regex_strings := []string{}
	regex_strings.push("b")
}
```

#### bug_test.v
```
module main

fn test_regex_builder() {
	assert true
}
```

### Possible Solution

Report a syntax error instead of attempting to compile the code.

### V version

V 0.3.2 2378b71.0a6fc6d

### Environment details (OS name and version, etc.)

OS: linux, Ubuntu 20.04.5 LTS (WSL 2)
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz
CC version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

getwd: /mnt/c/Users/bjones/Documents/git/CodeChat_Editor/server
vmodules: /home/bjones/.vmodules
vroot: /home/bjones/tmp/v
vexe: /home/bjones/tmp/v/v
vexe mtime: 2023-01-03 23:01:35
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 2378b71.0a6fc6d

Git version: git version 2.25.1
Git vroot status: weekly.2023.01-13-g0a6fc6d2
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by bjones1** [comment]
@JalonSolov, thanks for the quick response and for your help on the project. V is amazing!

**Comment by medvednikov** [comment]
Glad you like it @bjones1 :)

**Comment by Delta456** [comment]
I will look into fixing this.

**Comment by bjones1** [comment]
Thanks, @Delta456!

**Comment by bjones1** [comment]
Looks great, thanks for the quick response on this!
