### ISSUE TITLE
cgen: `$for` wrong casting `T.val` type to `T` type

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#16871]
### Describe the bug

wrong casting T.val type to T type

### Expected Behavior

```bash
Any('string')
true
Any('true')
Any('string')
true
Any('true')
```

### Current Behavior

```bash
16799-3.v:17:12: error: cannot cast `StructType` to `Any`
   15 |             println(Any("string")) // ok
   16 |             println(t.$(field.name)) // ok
   17 |             println(Any(t.$(field.name))) // not ok
      |                     ~~~~~~~~~~~~~~~~~~~~
   18 |         }
   19 |     }
```

### Reproduction Steps

```v
pub type Any = bool | int | map[string]Any | string

struct StructType {
mut:
	val string
}

fn main() {
	struct_to_map_string()
}

fn map_from[T](t T) {
	$if T is $Struct {
		$for field in T.fields {
			println(Any("string")) // ok
			println(t.$(field.name)) // ok
			println(Any(t.$(field.name))) // not ok
		}
	}
}

fn struct_to_map_string() {
	struct_type := StructType{
		val: 'true'
	}
	map_from(struct_type)
}
```

### V version

V 0.3.2 b8571c9

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by enghitalo** [comment]
also

```v
struct StructType {
mut:
	val string
}

fn main() {
	struct_to_map_string()
}

fn map_from[T](t T) {
	$if T is $Struct {
		$for field in T.fields {
			value := t.$(field.name)
			padding := &t.$(field.name)
			println(t.$(field.name)) // ok
			println(value) // ok
			println(padding) // wrong // StructType{val: 'some string'}
		}
	}
}

fn struct_to_map_string() {
	struct_type := StructType{
		val: 'some string'
	}
	map_from(struct_type)
}
```

**Comment by felipensp** [comment]
> also
> 
> ```v
> struct StructType {
> mut:
> 	val string
> }
> 
> fn main() {
> 	struct_to_map_string()
> }
> 
> fn map_from[T](t T) {
> 	$if T is $Struct {
> 		$for field in T.fields {
> 			value := t.$(field.name)
> 			padding := &t.$(field.name)
> 			println(t.$(field.name)) // ok // 'some string'
> 			println(value) // ok // 'some string'
> 			println(padding) // wrong // StructType{val: 'some string'}
> 		}
> 	}
> }
> 
> fn struct_to_map_string() {
> 	struct_type := StructType{
> 		val: 'some string'
> 	}
> 	map_from(struct_type)
> }
> ```

This one is already working on latest V.

**Comment by enghitalo** [comment]
> > also
> > ```v
> > struct StructType {
> > mut:
> > 	val string
> > }
> > 
> > fn main() {
> > 	struct_to_map_string()
> > }
> > 
> > fn map_from[T](t T) {
> > 	$if T is $Struct {
> > 		$for field in T.fields {
> > 			value := t.$(field.name)
> > 			padding := &t.$(field.name)
> > 			println(t.$(field.name)) // ok // 'some string'
> > 			println(value) // ok // 'some string'
> > 			println(padding) // wrong // StructType{val: 'some string'}
> > 		}
> > 	}
> > }
> > 
> > fn struct_to_map_string() {
> > 	struct_type := StructType{
> > 		val: 'some string'
> > 	}
> > 	map_from(struct_type)
> > }
> > ```
> 
> This one is already working on latest V.
@felipensp 
Work but is a wrong value is expected something like `&'some string'`
