### ISSUE TITLE
checker: error: optional type cannot be called directly

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#16885]
### Describe the bug

error

### Expected Behavior

not error

### Current Behavior

```bash
16849.v:23:10: error: optional type cannot be called directly
   21 |         value := val.$(field.name)
   22 |         $if field.is_optional {
   23 |             gg := value.str()
      |                   ~~~~~
   24 |         }
   25 |     }
```

### Reproduction Steps

```v
struct FixedStruct1 {
    a int
    b string
    c ?int
    d ?string
}

fn encode_struct[T](val T) {
	$for field in T.fields {
		value := val.$(field.name)
		$if field.is_optional {
			gg := value.str()
		}
	}
}

fn main() {
    encode_struct(FixedStruct1{})
}
```

### V version

Latest V 0.3.2

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by spytheman** [comment]
That should not be allowed. `none` values should be handled one way or another.

**Comment by enghitalo** [comment]
@spytheman @felipensp. Following this logic. Maybe `value.str() or { return }` can be allowed.
![image](https://user-images.githubusercontent.com/63821277/211146336-a2e60efe-f5b6-4663-a085-0bf50f46d8b5.png)

imo. I thing that specicly `.str()` method can work already that work well
```v
struct FixedStruct1 {
    a int
    b string
    c ?int
    d ?string
}

fn main() {
	fixed := FixedStruct1{}
	gg := "${fixed.c}"
	println(gg)
}
```

**Comment by spytheman** [comment]
What the PR is doing and what this issue is about though, is for allowing not just .str() - it removed the check for all methods over option field values, not just for the autogenerated .str() one.
