### ISSUE TITLE
Compiler: error: cannot convert 'struct main__Game' to 'void *'

### ISSUE THREAD

**Issue by yxqsnz** [vlang/v#16895]
### Describe the bug

When I try to run the source code (Reproduction steps) V fails to generate a correct C Code

### Expected Behavior

Programs build or V Compiler show a correct error message

### Current Behavior

When i try to run the attached source code, compiler throws the following message:
```v
/tmp/v_1000/Main.13098892533799899498.tmp.c:25243: warning: assignment discards qualifiers from pointer target type
/tmp/v_1000/Main.13098892533799899498.tmp.c:27333: error: cannot convert 'struct main__Game' to 'void *'
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

### Reproduction Steps

Paste this code to a file:
```v
module main

import gg
import gx
import time

struct Game {
mut:
	gg               &gg.Context = unsafe { nil }
	delta_time       f64
	total_delta_time f64
}

fn main() {
	mut game := Game{
		delta_time: 0
		total_delta_time: 0
	}

	game.gg = gg.new_context(
		bg_color: gx.rgb(174, 198, 255)
		width: 600
		height: 400
		user_data: game
		window_title: 'Hello'
		frame_fn: frame
	)

	game.gg.run()
}

fn frame(mut game Game) {
	ctx := game.gg
	sw := time.new_stopwatch()
	size := ctx.window_size()
	a, b := size.width / 2, size.height / 2

	ctx.begin()

	ctx.show_fps()
	ctx.draw_circle_filled(a, b, 100, gx.red)

	ctx.end()
	finished := sw.elapsed().seconds()
	game.delta_time = finished
}
```

and run: `v run <source file>`

### V version

V 0.3.2 de2ed74, timestamp: 2023-01-06 15:01:33 +0200

### Environment details (OS name and version, etc.)

OS: linux, Linux version 6.1.3-zen1-1-zen (linux-zen@archlinux) (gcc (GCC) 12.2.0, GNU ld (GNU Binutils) 2.39.0) #1 ZEN SMP PREEMPT_DYNAMIC Wed, 04 Jan 2023 16:28:17 +0000
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
CC version: cc (GCC) 12.2.0

getwd: /home/yx/Projects/V/Orbitate
vmodules: /home/yx/.vmodules
vroot: /home/yx/Projects/V/.Toolchain
vexe: /home/yx/Projects/V/.Toolchain/v
vexe mtime: 2023-01-06 22:14:53
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 de2ed74

Git version: git version 2.39.0
Git vroot status: weekly.2023.01-29-gde2ed749
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by Jocadbz** [comment]
Can confirm it is happening on my machine too.

**Comment by Jocadbz** [comment]
Ok, so apparently, @yxqsnz found the error. It was missing a `&`. Don't know why V's compiler triggered a error.

Changing this:
```diff
-     mut game := Game{
+     mut game := &Game{
```
results in a successful build.

LOL.

**Comment by felipensp** [comment]
Maybe it is related to #13957

**Comment by Jocadbz** [comment]
> Maybe it is related to #13957

Yeah, totally.
