### ISSUE TITLE
os: join_path[_single] ignores path separator in second argument

### ISSUE THREAD

**Issue by yochem** [vlang/v#16917]
### Describe the bug

join_path[_single] appends the `elem` after `base`, using a platform specific path_separator. But if `elem` *starts* with this separator, `join_path_single` blindly adds this to the resulting string.

### Expected Behavior

```v
>>> os.join_path_single('/usr/', '/bin/')
/usr/bin/
>>> os.join_path_single('/usr/', '/bin/') == os.join_path_single('/usr', 'bin/')
true
```

OR, as Python's `pathlib` does:

> Join one or more path segments intelligently. The return value is the concatenation of path and all members of *paths, with exactly one directory separator following each non-empty part except the last. That is, if the last part is empty, the result will end in a separator. **If a segment is an absolute path (which on Windows requires both a drive and a root), then all previous segments are ignored and joining continues from the absolute path segment.**

(highlight mine)

This would also make sense to me. In that case, the the expected behavior would be: 
```v
>>> os.join_path_single('/usr/', '/bin/')
/bin/
```

### Current Behavior

```v
>>> os.join_path_single('/usr/', '/bin/')
/usr//bin/
>>> os.join_path_single('/usr/', '/bin/') == os.join_path_single('/usr', 'bin/')
false
```

### Reproduction Steps

See above.

### Possible Solution

If choosing for approach 1, strip the `os.path_separator` characters from the `elem` or jion the paths and reduce repeating slashes to have only 1.

If choosing approach 2, check if a path starts with a slash and ignore the path parts before it.

### Additional Information/Context

In bash, repeating path separators still work (e.g. `ls ~//Documents` indeed shows the content of the documents folder). So maybe this would be a reason to keep it this way, and let the programmer handle the paths with care if they want to prevent paths with double slashes

### V version

V 0.3.2 2ec6e2b

### Environment details (OS name and version, etc.)

```
OS: macos, macOS, 13.0.1, 22A400
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
CC version: Apple clang version 14.0.0 (clang-1400.0.29.202)

getwd: /Users/yochem/Documents/nv/vlib/pathlib
vmodules: /Users/yochem/.vmodules
vroot: /usr/local/Cellar/vlang/0.2.4/libexec
vexe: /usr/local/Cellar/vlang/0.2.4/libexec/v
vexe mtime: 2023-01-09 10:24:09
is vroot writable: true
is vmodules writable: false
V full version: V 0.3.2 73675dc.2ec6e2b

Git version: git version 2.39.0
Git vroot status: weekly.2023.01-41-g2ec6e2b2
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 46662e20
```

**Comment by yochem** [comment]
I'll work on this. I will go with the second approach: if the `elem` path is an absolute path, the base is ignored and `elem` is returned. I will also trim the path separator of the elem path, as it's good practice and `os.abs_path` does it too (and thus it's easier to compare `elem == os.abs_path(elem)`.

**Comment by yochem** [comment]
Here are some examples on how the function will work:

```v
>>> os.join_path_single('/a/', 'b/')
/a/b
>>> os.join_path_single('/a/', '/b/')
/b
>>> os.join_path_single('a', 'b')
a/b
```

**Comment by yochem** [comment]
Btw, why does `os.join_path_single` even exist when `os.join_path(base, elem)` works just fine?

**Comment by spytheman** [comment]
It is not just bash that can handle paths with repeated separators, try `cd c:\\\\\\Users\\` in cmd.exe on windows - it will work as well.

**Comment by spytheman** [comment]
> I'll work on this. I will go with the second approach

Ok, just do not modify os.join_path or os.join_path_single . Create a new function that does that intelligent appending.

**Comment by spytheman** [comment]
> Btw, why does os.join_path_single even exist when os.join_path(base, elem) works just fine?

Because passing a variadic argument has some non negligible costs, and in some contexts they are significant.

**Comment by spytheman** [comment]
The current behavior of os.join_path is fine.

**Comment by JalonSolov** [comment]
I agree that calling a routine like this really should only keep a single separator between path pieces.  Can't control what someone types, but the code should be more consistent.

**Comment by yochem** [comment]
> I agree that calling a routine like this really should only keep a single separator between path pieces. Can't control what someone types, but the code should be more consistent.

So you would go with the following approach:
```v
>>> os.join_path_single('/a/', '/b/')
'/a/b/'
```
if I understand correctly?

**Comment by yochem** [comment]
I think there should be done *something* about the current behaviour. Another option would be to error when the second argument starts with a `/` (or is absolute). Because the user is doing something wrong if they want to append an absolute path.

**Comment by JalonSolov** [comment]
I don't think of it as joining separate paths, just separate path fragments.  So the 2nd one _can't_ be an absolute path, if you want to join it to the first.

**Comment by yochem** [comment]
> I don't think of it as joining separate paths, just separate path fragments.  So the 2nd one _can't_ be an absolute path, if you want to join it to the first.

I agree. Let's see what @spytheman thinks of this.

**Comment by spytheman** [comment]
I do not care much about duplicating // - they are not a problem on any filesystem I am aware of. 

That said, there can be additional logic, so that there is no duplication of slashes when building the final result in the string builder - *as long as what join_path does remains unchanged* in essence, and that is appending segments using the current platform separator *without* additional "smartness" about what is absolute, what is relative etc.
