### ISSUE TITLE
native chunk function to array

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#16918]
### Describe the feature

```v
fn ( []T ) chunk[T](sub_array_size_limit: int) T[][]
```

### Use Case

```v
[].chunk(10)
```

### Proposed Solution

"pseudocode"
```ts
function chunk<T>(array: T[], chunkSize: number): T[][] {
  const responseArray = [];
  for (let i = 0; i < array.length; i += chunkSize) {
    const chunk = array.slice(i, i + chunkSize);
    responseArray.push(chunk);
  }
  return responseArray;
}

```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.3.2

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by aynh** [comment]
There is [chunk](https://modules.vlang.io/arrays.html#chunk) function in the arrays module.

**Comment by enghitalo** [comment]
> There is [chunk](https://modules.vlang.io/arrays.html#chunk) function in the arrays module.

Thanks!!
