### ISSUE TITLE
http: on windows http.get fails for larger pages (for example github.com homepage).

### ISSUE THREAD

**Issue by spytheman** [vlang/v#1693]
**V version:** 0.1.18
**OS:** Windows 10 

**What did you do?**
v run program.v
```
import http
res :=  http.get('https://github.com/') or { panic(err) }
println( res.text )
```

**What did you expect to see?**
html text of https://github.com/
 
**What did you see instead?**
nothing

It only does fail for larger pages. For example https://github.com/robots.txt works fine.

**Comment by joe-conigliaro** [comment]
This should fix this: https://github.com/vlang/v/pull/1734
