### ISSUE TITLE
vls constantly crash and cannot build from source

### ISSUE THREAD

**Issue by despiegk** [vlang/v#16935]
### Describe the bug

despiegk1@KDSPRO farmerbot % v ls --update --source
> Cloning VLS repo...
> Compiling VLS from source...
v ls error: Cannot compile VLS from source: lsp/log/log.v:9:12: error: cannot register struct `src.lsp.log.LogRecorder`, another type with this name exists
    7 | import strings
    8 |
    9 | pub struct LogRecorder {
      |            ~~~~~~~~~~~
   10 | mut:
   11 |     file        os.File
> Building VLS...
v -g -gc boehm -d use_libbacktrace -cc cc cmd/vls -o /Users/despiegk1/.vls/src/bin/vls
Failed building VLS
 (0)

### Expected Behavior

vls to build

### Current Behavior

despiegk1@KDSPRO farmerbot % v ls
Content-Length: 193

{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":1,"message":"VLS has encountered an error. The error report is saved in /Users/despiegk1/.vls/reports/vls_report_1673326208.md"}}%

the .md file has nothing meaningful in it

### Reproduction Steps

default

### V version

newest

### Environment details (OS name and version, etc.)

m.1 osx

**Comment by despiegk** [comment]
## System Information
### V doctor
```
OS: macos, macOS, 13.1, 22C65
Processor: 10 cpus, 64bit, little endian, Apple M1 Pro
CC version: Apple clang version 14.0.0 (clang-1400.0.29.202)

getwd: /Users/despiegk1/code/github/threefoldtech/farmerbot
vmodules: /Users/despiegk1/.vmodules
vroot: /Users/despiegk1/_code/v
vexe: /Users/despiegk1/_code/v/v
vexe mtime: 2023-01-10 04:46:51
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 e8c0b09.6a32c81

Git version: git version 2.38.1
Git vroot status: weekly.2023.01-48-g6a32c810
.git/config present: true
thirdparty/tcc status: thirdparty-macos-arm64 173c526e
```

### VLS info 
```
vls version: 0.0.1.497563e
vls server arguments: --child --socket --port 5008 --timeout 15
```

## Problem Description



## Expected Output


## Actual Output
N/A

## Steps to Reproduce


## Last Recorded LSP Requests
### Request
```

```
### Response
```

```


vls log

**Comment by JalonSolov** [comment]
Use this instead, now that it's released:  https://blog.vosca.dev/meet-v-analyzer/
