### ISSUE TITLE
$tmpl() does not use const name 

### ISSUE THREAD

**Issue by SaidJerghough** [vlang/v#16941]
### Describe the bug

I tried to use template name as const

### Expected Behavior

error

### Current Behavior

```

embed_file.v:13:1: error: reading from /home/v/tutorial/ failed
   11 |     name := "Test template"
   12 |     return $tmpl('$template_name')
   13 | }
      | ^
   14 | 
   15 | fn main() {
   
   ```

### Reproduction Steps

```
const (
	template_name = 'index.html'
)

fn build_template() string {
	name := 'Template'

	return $tmpl('$template_name')
}

fn main() {
	os.write_file('build.html', build_template())!
}
```

### V version

V 0.3.2

### Environment details (OS name and version, etc.)

Pop!_OS 22.04 LTS

**Comment by archyboy** [comment]
According to the docs I think the compiler automatically insert the extension name  (.html) so try rename the const value from "template_name = 'index.html'" to just "template_name = 'index'"

**Comment by SaidJerghough** [comment]
Thank you for your answer, I will try your suggestion, in doc used 1.txt

From the docs
```
https://github.com/vlang/v/blob/master/doc/docs.md#tmpl-for-embedding-and-parsing-v-template-files
```
