### ISSUE TITLE
V panic: C error.

### ISSUE THREAD

**Issue by alexverkhola** [vlang/v#1694]
**V version:**  0.1.18
**OS:**  Ubuntu 16.04 LTS

**What did you do?** 
declare field named 'register' in the struct.

**What did you expect to see?**
Content of the created struct 
 
**What did you see instead?**
V panic: C error.

`fn main() {`
 `    user := User{}`
 `    println(user)`
`}`

`struct User {`
   ` // The problem is here. The 'register' word crashes a program. `
     `//Any other word beside 'register' does not invoke any mistake.`
` `
    `register bool`
`}`

**Comment by mvlootman** [comment]
Conflicts with storage class register?

**Comment by spytheman** [comment]
The `reason` is that register is a keyword in C. Others are `volatile` or `unsigned` .

In fact any one of these, will cause a problem (but some are already reserved keywords in v too).

```
auto	break	case	char
const	continue	default	do
double	else	enum	extern
float	for	goto	if
int	long	register	return
short	signed	sizeof	static
struct	switch	typedef	union
unsigned	void	volatile	while
```
