### ISSUE TITLE
No compile error when casting non-propagated function result into type alias

### ISSUE THREAD

**Issue by aynh** [vlang/v#16978]
### Describe the bug

As the title said. 

### Expected Behavior

There should be a compile error.

### Current Behavior

```
V panic: malloc_noscan(-239210511 <= 0)
v hash: dbfb9c3
/tmp/v_1000/test.14591577874262077667.tmp.c:6784: at _v_panic: Backtrace
/tmp/v_1000/test.14591577874262077667.tmp.c:7020: by malloc_noscan
/tmp/v_1000/test.14591577874262077667.tmp.c:9581: by string_clone
/tmp/v_1000/test.14591577874262077667.tmp.c:11445: by StrIntpData_process_str_intp_data
/tmp/v_1000/test.14591577874262077667.tmp.c:11878: by str_intp
/tmp/v_1000/test.14591577874262077667.tmp.c:2097: by indent_main__Abc_str
/tmp/v_1000/test.14591577874262077667.tmp.c:2086: by main__Abc_str
/tmp/v_1000/test.14591577874262077667.tmp.c:2076: by indent_main__Alias_str
/tmp/v_1000/test.14591577874262077667.tmp.c:2073: by main__Alias_str
/tmp/v_1000/test.14591577874262077667.tmp.c:12176: by main__main
/tmp/v_1000/test.14591577874262077667.tmp.c:12546: by main
```

### Reproduction Steps

```v
struct Abc {
	a string
}

type Alias = Abc

fn ret_abc_result() !Abc {
	return Abc{'a'}
}

a := Alias(ret_abc_result()) // V didn't complain about this line
// a := Alias(ret_abc_result()!) // it should be like this
println(a) 
```

### V version

V 0.3.2 dbfb9c3

### Environment details (OS name and version, etc.)

OS: linux, "Arch Linux"
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
CC version: cc (GCC) 12.2.0

vexe mtime: 2023-01-14 16:52:07
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 6a179a2.dbfb9c3

Git version: git version 2.39.0
Git vroot status: weekly.2023.02-31-gdbfb9c3a
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by Delta456** [comment]
Fixed. I will PR soon

![image](https://user-images.githubusercontent.com/28479139/212536897-55d2741e-4002-4048-bc29-39695693c8c7.png)
