### ISSUE TITLE
os.mv fails with docker volumes

### ISSUE THREAD

**Issue by thomaspeissl** [vlang/v#16985]
### Describe the bug

The os.mv() function does not work with Docker volumes.

### Expected Behavior

The os.mv() function working with Docker volumes.

### Current Behavior

Error message: failed to rename /app/files/1.txt to /app/moved/moved.txt

### Reproduction Steps

I created this repository for this issue https://github.com/thomaspeissl/vdockermv

### Possible Solution

os.mv could try a combination of os.cp and os.rm if os.mv failed 

### V version

V 0.3.2 ba091a3

### Environment details (OS name and version, etc.)

OS: linux, Ubuntu 22.10 (VM)
Processor: 2 cpus, 64bit, little endian, AMD EPYC 7551 32-Core Processor
CC version: Ubuntu clang version 15.0.2-1

getwd: /home/ubuntu
vmodules: /home/ubuntu/.vmodules
vroot: /home/ubuntu/v
vexe: /home/ubuntu/v/v
vexe mtime: 2023-01-12 19:54:58
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 ef5be22.ba091a3

Git version: git version 2.37.2
Git vroot status: weekly.2022.47-276-gba091a36-dirty (19 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by JalonSolov** [comment]
There is already a `os.mv_by_cp()` function, which does what you're suggesting.

**Comment by thomaspeissl** [comment]
Thank you for pointing that out. I didn't know about this function.

It may sound stupid, but wouldn't it be more "developer friendly" to generally fall back using `os.mv_by_cp()` if `os.mv()` fails?

**Comment by JalonSolov** [comment]
It could be argued either way, I think.  Some might want to handle it themselves, so they would know when they were moving things between different volumes.  Others would want it to happen automatically.

Personally, I'm not sure which way would be best.  The Linux system `mv` command does do what you're suggesting, but similar commands on other systems don't.  :man_shrugging:

**Comment by thomaspeissl** [comment]
I understand. 
It took me like a hour to find out that this was the reason why my program failed.
I would like to add a hint to the `os.mv()` function's comment block.
So that the next developer doesn't waste that hour.
Do you think that is a good idea?

**Comment by Delta456** [comment]
> I understand. 
> It took me like a hour to find out that this was the reason why my program failed.
> I would like to add a hint to the `os.mv()` function's comment block.
> So that the next developer doesn't waste that hour.
> Do you think that is a good idea?

Sure, it is.

**Comment by thomaspeissl** [comment]
See also https://discord.com/channels/592103645835821068/592106336838352923/1065568564519632956 for further discussion.
