### ISSUE TITLE
Overflow of enum as u8 when assigned 0xFF to field

### ISSUE THREAD

**Issue by marcosantos98** [vlang/v#16994]
### Describe the bug

Assigning `0xFF` to an enum that extends u8 throws compiler error.

```v
enum Foo as u8 {
    bar
    baz = 0xFF
}
```

```
foo/bar.v:34:35: error: enum value `0xFF` overflows the enum type `u8`, values of which have to be in [0, 255]
   33 |     baz = 5
   34 |     bar = 0xFF
      |                 ~~~
   35 | }
   36 |
```

### Expected Behavior

Since u8 values extend from 0-255, 0xFF should be allowed.

### Current Behavior

When 0xFF is assign to an enum field the compiler throws an error

### Reproduction Steps

```v
enum Foo as u8 {
    bar
    baz = 0xFF
}
```

`v run foo.v`

### V version

0.3.2

### Environment details (OS name and version, etc.)

OS: linux, Linux version 6.1.5-arch2-1 (linux@archlinux) (gcc (GCC) 12.2.0, GNU ld (GNU Binutils) 2.39.0) #1 SMP PREEMPT_DYNAMIC Thu, 12 Jan 2023 22:42:33 +0000
Processor: 4 cpus, 64bit, little endian, AMD A10-9620P RADEON R5, 10 COMPUTE CORES 4C+6G
CC version: cc (GCC) 12.2.0

getwd: /home/marco
vmodules: /home/marco/.vmodules
vroot: /home/marco/opt/v
vexe: /home/marco/opt/v/v
vexe mtime: 2023-01-16 15:15:03
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 a60f34e.92fd12c

Git version: git version 2.39.0
Git vroot status: weekly.2023.01-103-g92fd12c1
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by JalonSolov** [comment]
Try this, instead:
```v
enum Foo as u8 {
    bar
    baz = u8(0xFF)
}
```
With casting to `u8`, the value is seen as a signed int (the default), and that can overflow a `u8` value.

**Comment by Delta456** [comment]
> 

I feel this is unnecessary because, in the enum declaration, we have already specified `u8` as an explicit type.

To make it work correctly we have to change the condition here.

https://github.com/vlang/v/blob/6bf6a40e0c9b6837050d026fe38e3e8a7da0eb5e/vlib/v/checker/checker.v#LL1559C9-L1559C9

**Comment by JalonSolov** [comment]
That would be fine by me.  I was just suggesting how to make it work with current code.

**Comment by marcosantos98** [comment]
> > Try this, instead:
> > ```v
> > enum Foo as u8 {
> >     bar
> >     baz = u8(0xFF)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Without casting to `u8`, the value is seen as a signed int (the default), and that can overflow a `u8` value.
> 
> I feel this is unnecessary because, in the enum declaration, we have already specified `u8` as an explicit type.
> 
> To make it work correctly we have to change the condition here.
> 
> https://github.com/vlang/v/blob/6bf6a40e0c9b6837050d026fe38e3e8a7da0eb5e/vlib/v/checker/checker.v#LL1559C9-L1559C9

I agree, casting shouldn't be the solution when the value is in range and the enum type is known at compile time.
