### ISSUE TITLE
`in` operator in `const` block uses uninitiliased array (same issue using fn call from `const`)

### ISSUE THREAD

**Issue by DevrosTheOne** [vlang/v#16995]
### Describe the bug

Using an array as data to genrate a `const` array of structures with `init:`.  

The `in` operator evaluates to false as the array has not been finalised (empty array) if declared after the line that references the array. 
 
Compiler makes the array variable accessible out of declaration sequence.

Same problem if `init:` calls a function to generate the structure.

```v
const (
	dat = 'Data tag ,No data'.split(',')
	dd  = []Info{len: 4, init: Info{if it in tag { dat[0] + it.str() } else { dat[1] }}}
	tag = [1, 2]  // in wrong line
)

struct Info {
	val string
}

println(dd)
```

### Expected Behavior

Compile error about accessing variable before it has been initialised/declared.

### Current Behavior

`output`
[Info{
    val: 'No data'
}, Info{
    val: 'No data'
}, Info{
    val: 'No data'
}, Info{
    val: 'No data'
}]

`wanted output`
[Info{
    val: 'No data'
}, Info{
    val: 'Data tag 1'
}, Info{
    val: 'Data tag 2'
}, Info{
    val: 'No data'
}]

### Reproduction Steps

```v
const (
	dat = 'Data tag ,No data'.split(',')
	dd  = []Info{len: 4, init: Info{if it in tag { dat[0] + it.str() } else { dat[1] }}}
	tag = [1, 2]
)

struct Info {
	val string
}

println(dd)
```

### Possible Solution

Should not have access to variable before it has finalised initialisation.  The `in` operator compares against an empty array resulting in `false` condition

### Additional Information/Context

Same problem accurs if we use a function inplace of inline `init:`. 
```v
const (
	data = 'Data tag ,No data'.split(',')
	dd   = []Info{len: 4, init: make_info(it)}
	tag  = [1, 2]
)

struct Info {
	val string
}

fn make_info(it int) Info {
	return Info{
		val: if it in tag {
			data[0] + it.str()
		} else {
			data[1]
		}
	}
}

println(dd)

```

### V version

V 0.3.2 6bf6a40

### Environment details (OS name and version, etc.)

OS: macos, macOS, 13.1, 22C65
Processor: 8 cpus, 64bit, little endian, Apple M2

**Comment by MatejMagat305** [comment]
but swap line work, right?

**Comment by DevrosTheOne** [comment]
Yes, it works as intended when you order the lines in the correct
sequence.

It looks like the compiler parses the definition and then does two
things: wrong
1) allows access to it out of code sequence and
2) uses incomplete initialization of the variable.  In this case it
applies the in operator on an empty array which evaluates to false.

Compiler should have complained about not knowing the array variable and
not generate the code.

Reordered some code I was playing with to make it look neater.  Major pain
to track down the problem.

Sorry for the long email to simple question.
