### ISSUE TITLE
Embedding structs

### ISSUE THREAD

**Issue by tonylinyy** [vlang/v#170]
sample code is:
struct Point {
	x int
	y int
}

struct Point3D {
	Point
	z  int
}
it compile faild,just panic

**Comment by medvednikov** [comment]
Embedding structs is not implemented yet.

**Comment by zaoqi** [comment]
This feature may cause confusion

**Comment by arhen** [comment]
> This feature may cause confusion

Totally Agreed! Need some style to make it happen.

**Comment by 1l0** [comment]
It's one of the specs of Go.

**Comment by zaoqi-unsafe** [comment]
So V is Go++?

**Comment by hamad-almamari** [comment]
What if we have x in both 🤔😶.
confusion
Keeb V simple.

**Comment by medvednikov** [comment]
Embedding works really well in Go and allows to migrate OOP code easier.

The name conflict is handled pretty easily:

https://play.golang.org/p/88nwQIsQIMK

**Comment by di3663** [comment]
> So V is Go++?

of course a better go or better c, but not go++.

**Comment by zaoqi** [comment]
@di3663

`if https://github.com/vlang/v { all other languages will die }` ?

我覺得Clojure這種設計有很多問題的語言都不會因此而死。

**Comment by zaoqi** [comment]
@di3663

Idris這種工業語言更不會死。

**Comment by Bowero** [comment]
```go
struct point {
    x int
    y int
}

struct point3d {
    p point
    z int
}
```

This is now the structure.

**Comment by medvednikov** [comment]
@Bowero embedded structs are not implemented yet.

**Comment by gslicer** [comment]
> 
> 
> Embedding works really well in Go and allows to migrate OOP code easier.
> 
> The name conflict is handled pretty easily:
> 
> https://play.golang.org/p/88nwQIsQIMK

Somehow this example looks wrong and I wonder why it compiles and how the second output value can be "0" (it is never assigned to A), in my view a correct example would look rather like:
https://play.golang.org/p/8Qo6vzWs0px

**Comment by nedpals** [comment]
Struct embedding was (initially) implemented in https://github.com/vlang/v/commit/2c75b1397cbd8b940bdf357ebb74d59660c53f51.
