### ISSUE TITLE
vlib documents: Broken links due to missing READMEs

### ISSUE THREAD

**Issue by km19809** [vlang/v#17003]
### Describe the issue

I can click `db` or `encoding` from the sidebar, but it leads to the same, current page.

![image](https://user-images.githubusercontent.com/20869932/212830491-afb23452-07af-4d0e-b4b9-8e10391d07db.png)
Image: The link refers to the same page.

It is because there is no README in `vlib/db` or `vlib/encoding`.
However, meaningless anchors may interrupt the browsing experience.

I think there are some possible options:
1. Provide READMEs for modules.
2. Eliminate the anchor tag for missing documents.
3. Link the anchor to a default error page.

Which one is the most admirable?
Or, is the issue an intended behavior?

### Links

https://modules.vlang.io/

**Comment by spytheman** [comment]
Fixed by #22636 .
