### ISSUE TITLE
checker: segfault on recursive type definitions

### ISSUE THREAD

**Issue by l1mey112** [vlang/v#17008]
### Describe the bug

A segmentation fault inside the V compiler whenever a recursive type with a specific layout is referenced.

### Expected Behavior

A successful compilation.

### Current Behavior

```
$ v a.v
[1]    453912 segmentation fault (core dumped)  v internals/a.v
```

```
$ v -g self
$ gdb --args v a.v
....
....
Program received signal SIGSEGV, Segmentation fault.
0x000000000065419f in v__checker__Checker_ensure_generic_type_specify_type_names (pos=<error reading variable: value of type `v__token__Pos' requires 18446744073709551615 bytes, which is more than max-value-size>, typ=20, c=0xf84a20) at ....vlib/v/checker/checker.v:4220
4220            sym := c.table.final_sym(typ)
(gdb)
```

### Reproduction Steps

```v
// All cause a segmentation fault

type VTableTyp = map[string]VTableTyp
// type VTableTyp = map[string]&VTableTyp
// type VTableTyp = []VTableTyp
// type VTableTyp = []&VTableTyp

// Use of type here, but I assume this can occur in any context
struct VTable {
	ptr VTableTyp
}
```

### V version

V 0.3.2 7db7951.930e629

### Environment details (OS name and version, etc.)

OS: linux, "Arch Linux"
CC version: cc (GCC) 12.2.0

**Comment by spytheman** [comment]
The segfault is fixed in 75d6cb9c3 , it is now a checker error instead, that should handle other potential segfaults of this sort, due to unlimited recursion:
![image](https://user-images.githubusercontent.com/26967/212884235-15d4decc-c4ea-41b3-ab00-3344d84e528b.png)

I'll push a more specific error/check for it soon too.
