### ISSUE TITLE
V does not catch incompatible type error inside generic functions

### ISSUE THREAD

**Issue by bbodi** [vlang/v#17018]
### Describe the bug

```
v run bug.v
==================
/tmp/v_1000/bug.10536793480215037072.tmp.c:12133: error: cannot convert 'int' to 'struct string'
```

### Expected Behavior

A compile error that int cannot be passed as a string.

### Current Behavior

V compiles it but generates wrong C code.

### Reproduction Steps

```
fn my_fn[T]() {
	mut b := strings.new_builder(16)
	var := T{}
	ptr := &var
	b.write_string(*ptr)
}
fn main() {

	my_fn[int]()
}
```

### V version

V 0.3.2 a22dfe0.5dbdb21

### Environment details (OS name and version, etc.)

OS: linux, Ubuntu 22.10
CC version: cc (Ubuntu 12.2.0-3ubuntu1) 12.2.0

**Comment by MatejMagat305** [comment]
well I m new in vlang but pointer look like "unsafe" and pointer is integer so if you want you could try:
```
import strings

fn my_fn[T]() {
	mut b := strings.new_builder(16)
	var := T{}
	ptr := &var
	unsafe { b.write_string('${*ptr}') }
}

fn main() {
	my_fn[int]()
}

```

**Comment by bbodi** [comment]
It was just a shortened reproduction snippet, not something that needs to be solved. The point is that the error should have caught by the V compiler and not the C backend.

**Comment by MatejMagat305** [comment]
ah, sorry
