### ISSUE TITLE
Returning comptime if gives builder error

### ISSUE THREAD

**Issue by aynh** [vlang/v#17016]
### Describe the bug

.

### Expected Behavior

It should compile.

### Current Behavior

```
/tmp/v_1000/compime_ret.4290671977799971669.tmp.c:12133: error: cannot convert 'struct string' to 'struct _result_string'
builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

### Reproduction Steps

```v
fn comptime_ret_result() !string {
	return $if debug {
		'debug'
	} $else {
		'not debug'
	}
}

println(comptime_ret_result()!)
```

### Additional Information/Context

Returning them inside the if block works.

```v
fn comptime_ret_result() !string {
	$if debug {
		return 'debug'
	} $else {
		return 'not debug'
	}
}

println(comptime_ret_result()!)
```

Running it with `v run file.v` gives the following output:

```
not debug
```

### V version

V 0.3.2 a22dfe0

### Environment details (OS name and version, etc.)

OS: linux, "Arch Linux"
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
CC version: cc (GCC) 12.2.0

vexe mtime: 2023-01-17 15:46:59
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 2034dcb.a22dfe0

Git version: git version 2.39.0
Git vroot status: weekly.2023.03-8-ga22dfe0d
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by MatejMagat305** [comment]
well I m new in Vlang, but "!" mean that you sometime return error the code:
```
fn comptime_ret_result() string {
	return $if debug {
		'debug'
	} $else {
		'not debug'
	}
}

fn main() {
	println(comptime_ret_result())
}
```
 works so I do not know

**Comment by aynh** [comment]
> well I m new in Vlang, but "!" mean that you sometime return error the code:
> 
> ```
> fn comptime_ret_result() string {
> 	return $if debug {
> 		'debug'
> 	} $else {
> 		'not debug'
> 	}
> }
> 
> fn main() {
> 	println(comptime_ret_result())
> }
> ```
> 
> works so I do not know, whether is bug or feature ...

Yeah, it only happen on function that return a result (function with return type that is prefixed with a `!`). From my understanding `!` does not necessarily mean it needs to return an error, it just means it could return an error instead of the return type.
