### ISSUE TITLE
V panic: as cast: cannot cast `v.ast.Alias` to `v.ast.Struct`

### ISSUE THREAD

**Issue by bbodi** [vlang/v#17027]
### Describe the bug

V panic: as cast: cannot cast `v.ast.Alias` to `v.ast.Struct`

### Expected Behavior

I think because the call to `func2` works, the call to the generic one should work too.

### Current Behavior

V panic: as cast: cannot cast `v.ast.Alias` to `v.ast.Struct`

### Reproduction Steps

```
type Int = int
type MyIndex = struct { Int }

fn func[I]() I{
	return I{0}
}

fn func2() MyIndex {
	return MyIndex{0}
}

fn main() {
	println(func2())               // It works
	println(func[MyIndex]()) // Error
}

```

### V version

V 0.3.2 a22dfe0.5dbdb21

### Environment details (OS name and version, etc.)

Linux

**Comment by bbodi** [comment]
An other issue with similar reproduction code is created separately: https://github.com/vlang/v/issues/17028

**Comment by felipensp** [comment]
I can't reproduce it with newer V version.
