### ISSUE TITLE
Can't return a (generic) function from generic function

### ISSUE THREAD

**Issue by aynh** [vlang/v#17035]
### Describe the bug

Only if the function is used more than once (and with different type).

### Expected Behavior

Maybe it should work.

I'm planning to use this kind of function to create an automatic retry function and cached function.

### Current Behavior

```
/tmp/v_1000/test.17551053586904265505.tmp.c:12334: error: 'anon_fn_8ce6aadc8523cb25_t__R_68_T_int_int' undeclared
builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

### Reproduction Steps

```v
fn wrap[T, R](cb fn (T) R) fn (T) R {
	return fn [cb] [T, R](s T) R {
		return cb(s)
	}
}

fn ret1(s string) string {
  return s
}

fn ret2(s int) int {
	return s
}

wrap1 := wrap(ret1)
assert wrap1('1') == '1'
// uncomment either of these and it should work
wrap2 := wrap(ret2)
assert wrap2(2) == 2
```

### Additional Information/Context

I see that assigning a generic function to a variable does not work and gives a compile error, does that mean the method above bypasses the compile error?

Modified code that gives compile error:

```v
fn wrap[T, R](cb fn (T) R) fn (T) R {
	c := fn [cb] [T, R](s T) R {
		return cb(s)
	}

	return c
}

fn ret1(s string) string {
	return s
}

wrap1 := wrap(ret1)
assert wrap1('1') == '1'
```

The error:

```
test.v:2:7: error: cannot assign generic function to a variable
    1 | fn wrap[T, R](cb fn (T) R) fn (T) R {
    2 |     c := fn [cb] [T, R](s T) R {
      |          ~~~~~~~~~~~~~~~~~~~~~~~
    3 |         return cb(s)
    4 |     }
```

### V version

V 0.3.2 269833b

### Environment details (OS name and version, etc.)

OS: linux, "Arch Linux"
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
CC version: cc (GCC) 12.2.1 20230111

getwd: /home/yasser/vlang/wrap_generic_fn
vmodules: /home/yasser/.vmodules
vroot: /home/yasser/.local/vlang
vexe: /home/yasser/.local/vlang/v
vexe mtime: 2023-01-19 09:40:59
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 2034dcb.269833b

Git version: git version 2.39.1
Git vroot status: weekly.2023.03-22-g269833b7
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by DevrosTheOne** [comment]
With the second example I think you wanted a closure.  
That works but fails with the same compiler error when you call the function to return a closure with a different type. 
```v
fn wrap[T, R](cb fn (T) R) fn (T) R {
	return fn [cb] [T, R](s T) R {
		return cb(s)
	}
}

fn ret1(s string) string {
	return s
}

fn ret2(s int) int {
	return s
}

wrap1 := wrap(ret1)
assert wrap1('1') == '1'
wrap11 := wrap(ret1)
assert wrap11('11') == '11'

// wrap2 := wrap(ret2)
// assert wrap2(13) == 13
``` 
error 
`
error: use of undeclared identifier. 
'anon_fn_523d9648030cd6d3_t__R_68_T_int_int'; did you mean 'anon_fn_523d9648030cd6d3_t__R_68_T_string_string'?
`

**Comment by DevrosTheOne** [comment]
Strip down example to demo the error.

You can't return a closure from a generic function where types are different.  The  call to the generic function seems to do a lookup and on the type defined and complains that that new function does not exist? and did you mean to call the previous closure generated.  

```v
module main

fn simple_generic_closure[T](fun fn () T) fn () T {
	return fn [fun] [T]() T {
		return fun()
	}
}

fn get_string_fn() string {
	return 'error'
}

fn get_int_fn() int {
	return 42
}

fn get_int_fn2() int {
	return 1313
}

fn main() {
	fn_int := simple_generic_closure(get_int_fn)
	fn_int2 := simple_generic_closure(get_int_fn2)
	assert fn_int() == 42
	assert fn_int2() == 1313

	// different type in parameter results in 2 warnings and 1 error
	fn_string := simple_generic_closure(get_string_fn)
	assert fn_string() == 'error'
}
```
`
/tmp/v_501/main.650112325527905599.tmp.c:12355:51: error: use of undeclared identifier 'anon_fn_0516dbf3bafa4795___T_90_T_string'; did you mean 'anon_fn_0516dbf3bafa4795___T_90_T_int'?
        anon_fn___string _t1 = (voidptr)__closure_create(anon_fn_0516dbf3bafa4795___T_90_T_string, (struct _V_anon_fn_0516dbf3bafa4795___T_90_Ctx*) memdup_uncollectable(&(struct _V_anon_fn_0516dbf3bafa4795___T_90_Ctx){.fun = fun,
                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                         anon_fn_0516dbf3bafa4795___T_90_T_int
/tmp/v_501/main.650112325527905599.tmp.c:2283:21: note: 'anon_fn_0516dbf3bafa4795___T_90_T_int' declared here
VV_LOCAL_SYMBOL int anon_fn_0516dbf3bafa4795___T_90_T_int(void) {
                    ^
2 warnings and 1 error generated.
`

**Comment by felipensp** [comment]
This already has been fixed. Thanks.
