### ISSUE TITLE
Format code snippets in V-for-Go-developers.md

### ISSUE THREAD

**Issue by ghost** [vlang/v#17030]
### Describe the issue

I would like to suggest formatting the code snippets from the V-fo-Go-developers wiki page:

https://github.com/vlang/v/wiki/V-for-Go-developers

so that they are consistent. Proposed changes:

https://github.com/tedstoychev/v-wiki/commit/a0591d84bf3ef24e9d17183bf6f672d19e4daa24?diff=split

(Alternatively the code snippets could use 4 spaces instead of 2. I don't have a strong opinion about either, as long as they are consistent.)

I can't open a PR for a Wiki page. That's why I'm opening an issue here.

### Links

https://github.com/vlang/v/wiki/V-for-Go-developers

**Comment by JalonSolov** [comment]
Format changes done, as well as adding a header at the top to specify which is Go and which is V (in case it wasn't clear... they are similar syntax).
