### ISSUE TITLE
specify files to convert

### ISSUE THREAD

**Issue by wenq1** [vlang/v#17063]
### Describe the issue

Both below works (in examples/call_v_from_c):

```
$ v -shared -o v_test_math.c v_test_math.v
$ v -shared -o v_test_both.c .
```

But not below
```
$ v -shared -o v_test_math.c v_test_math.v v_test_print.v
Too many targets. Specify just one target: <target.v|target_directory>.
```

Is it possible to specify a list of files to be converted into C, rather than the full directory?

Use case is simple. I have two folders: vsrc_a, and vsrc_b, each containing some v sources. Now if I do:
```
$ vsrc_a$ v -shared -o vsrc_a.c .
$ vsrc_b$ v -shared -o vsrc_b.c .

$ gcc -o test vsrc_a.c  vsrc_b.c
Won't work because vsrc_a.c and vsrc_b.c contain duplicated boilerplate codes.

```

### Links

No link.

**Comment by JalonSolov** [comment]
No, there is no way to do that.  V only accepts a single file to compile, or a directory.

**Comment by wenq1** [comment]
What about in future versions?

**Comment by JalonSolov** [comment]
I don't think so, though @medvednikov makes the final decisions.  V is opinionated on many things, to help the most users have the least amount of stress while developing code.  Supporting something like this could become very messy, very fast, as well as being difficult to document.

As a workaround, it would be simple enough to write a short script to copy only the files you want to convert to a directory in /tmp and then run V on that directory.
