### ISSUE TITLE
unused reference gives a V panic

### ISSUE THREAD

**Issue by mvlootman** [vlang/v#1707]
**V version:0.1.18** 
**OS: Elementary OS 5.0** 

**What did you do?**
```
a := 42
my_ref := &a

// if the println is commented out, we get an error, otherwise no error
//println(my_ref)       // V panic: string index out of range: 385 / 384 
```

**What did you expect to see?**
Unused variable (my_ref)
 
**What did you see instead?**
V panic: string index out of range: 385 / 384

**Comment by gslicer** [comment]
seems like an regression, in  v0.1.12 this example yields:
 `my_ref` declared and not used

**Comment by medvednikov** [comment]
I think it's because of missing `fn main()`

**Comment by mvlootman** [comment]
The error still occured when adding it inside a fn main() function.
It was fixed yesterday/today since now it does work (it gives the correct error that the variable is not used, both with or without fn main() )
