### ISSUE TITLE
Referring to a field and a method with the same name does not work correctly if the field is private

### ISSUE THREAD

**Issue by i582** [vlang/v#17075]
### Describe the bug

Example:

**mod/mod.v**
```v
module mod

pub struct Point {
	x int
	y int
}

pub fn (p Point) x() int {
	return p.x
}
```

**main.v**
```v
module main

import mod

fn main() {
	p := mod.Point{1, 2}
	println(p.x)
        //        ^ error: field `mod.Point.x` is not public
}
```

### Expected Behavior

Since the field is private, the fetch goes to the public method `x` and "fn () int" is printed.

### Current Behavior

error:

```
main.v:7:12: error: field `mod.Point.x` is not public
    5 | fn main() {
    6 |     p := mod.Point{1, 2}
    7 |     println(p.x)
      |               ^
```

### Reproduction Steps

See "Describe the bug"

### V version

V 0.3.2 89aa695.865c0ea

### Environment details (OS name and version, etc.)

```
Processor: 10 cpus, 64bit, little endian, Apple M1 Pro
CC version: Apple clang version 14.0.0 (clang-1400.0.29.202)

getwd: /Users/petrmakhnev/vlang-foundation/specification
vmodules: /Users/petrmakhnev/.vmodules
vroot: /Users/petrmakhnev/v
vexe: /Users/petrmakhnev/v/v
vexe mtime: 2023-01-22 21:48:01
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 89aa695.865c0ea

Git version: git version 2.37.1 (Apple Git-137.1)
Git vroot status: weekly.2022.50-266-g865c0ea8-dirty
.git/config present: true
thirdparty/tcc status: thirdparty-macos-arm64 173c526e
```

**Comment by JalonSolov** [comment]
The current behavior is correct.

You have to make the fields in the struct public, as in
```v
pub struct Point {
pub:
	x int
	y int
}
```

**Comment by i582** [comment]
> The current behavior is correct.
> 
> You have to make the fields in the struct public, as in
> 
> ```v
> pub struct Point {
> pub:
> 	x int
> 	y int
> }
> ```

It's not correct because I want to refer to the method, not the field.

**Comment by JalonSolov** [comment]
Ah, well the problem there is shadowing.  V should not allow any sort of shadowing, so creating a method with the same name as a field should throw an error.  It just needs to be a different error than what you're seeing.

**Comment by i582** [comment]
> aint the method p.x() instead of p.x unless it was a way to access a method like that

here it describes accessing the method, not calling it
