### ISSUE TITLE
Add `trim_indent()` function

### ISSUE THREAD

**Issue by i582** [vlang/v#17086]
### Describe the feature

Imagine we have some html code:

```html
<!doctype html>
<html lang="en">
<head>
</head>
<body>
  Some content
</body>
</html>
```

And we want store it in string variable:

```v
fn main() {
	text := '
	<!doctype html>
	<html lang="en">
	<head>
	</head>
	<body>
	  Some content
	</body>
	</html>
'

	println(text)
}
```

This doesn't work because we get indentation on each line and newlines at the beginning and end.
Of course we can write it this way:

```v
fn main() {
	text := '<!doctype html>
<html lang="en">
<head>
</head>
<body>
	Some content
</body>
</html>'

	println(text)
}
```

But this looks bad, as it reduces readability.

Of course, we can write code like this:

```v
fn main() {
	text := '
	|<!doctype html>
	|<html lang="en">
	|<head>
	|</head>
	|<body>
	|  Some content
	|</body>
	|</html>
'.strip_margin().trim('\n')

	println(text)
}
```

but in this case we need `|` at the beginning of each line, which makes the line itself less editable and readable (it's also very easy to forget to write it on new lines when editing.), and `trim()` will remove all empty lines, even though we only want the first and last.

This is where the `trim_indent()` function comes to the rescue. I took the idea from Kotlin, where it is used very often for multi-line literals.

See specification here: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/trim-indent.html

```v
fn main() {
	text := '
	<!doctype html>
	<html lang="en">
	<head>
	</head>
	<body>
	  Some content
	</body>
	</html>
'.trim_indent()

	println(text)
}
```

And all works!

### Use Case

See above.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.3.2 89aa695.865c0ea

### Environment details (OS name and version, etc.)

```
OS: macos, macOS, 13.0.1, 22A400
Processor: 10 cpus, 64bit, little endian, Apple M1 Pro
CC version: Apple clang version 14.0.0 (clang-1400.0.29.202)

getwd: /Users/petrmakhnev/vlang-foundation/specification
vmodules: /Users/petrmakhnev/.vmodules
vroot: /Users/petrmakhnev/v
vexe: /Users/petrmakhnev/v/v
vexe mtime: 2023-01-22 21:48:01
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 89aa695.865c0ea

Git version: git version 2.37.1 (Apple Git-137.1)
Git vroot status: weekly.2022.50-266-g865c0ea8-dirty
.git/config present: true
thirdparty/tcc status: thirdparty-macos-arm64 173c526e
```

**Comment by Larpon** [comment]
```v
text := '
<html>
  stuff
</html>
'.trim('\n')
println(text)
```
Why is the above not enough?
[trim()](https://modules.vlang.io/index.html#string.trim) only trims from start and end until a non-matching character is met - not characters in between?

**Comment by i582** [comment]
@Larpon what if I want something like this?

```

<html>
  stuff
</html>
```

Note this first empty line.

**Comment by Larpon** [comment]
Then `trim()` doesn't cut it, true
