### ISSUE TITLE
A small poll/discussion on the syntax (mut keyword and access modifiers)

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#171]
Looks like it's not possible to create polls on GitHub, so please just thumbs-up the syntax you prefer.

Feedback and suggestions are welcome.

**update**

`mut` is a clear winner in all channels, and it makes sense given the ideas and the philosophy of the language.

So here's a third option with `mut`:

```
struct User {
    id int
 
  mut:
    email string
  
  pub mut:
    first_name string
    last_name string
    field1, field2, field3, field4 string
}
```

Please thumbs-up this message if you prefer this syntax.

**Comment by medvednikov** [comment]
```
struct User {
    id int

    email mut string
  
    +first_name mut string
    +last_name mut string
    +field1 mut string
    +field2 mut string
    +field3 mut string
    +field4 mut string
}
```

**Comment by medvednikov** [comment]
```
struct User {
    id int
 
  mutable:
    email string
  
  public mutable:
    first_name string
    last_name string
    field1, field2, field3, field4 string
}
```

**Comment by medvednikov** [comment]
`mut x := 0`
`fn (u mut User) register() {`

**Comment by medvednikov** [comment]
`mutable x := 0`
`fn (u mutable User) register() {`

**Comment by andrewda** [comment]
This is a cool app for making GitHub polls: https://app.gh-polls.com/

**Comment by medvednikov** [comment]
Looks nice. Top notch software from tj, as always. Will use it from now on.

**Comment by PavelVozenilek** [comment]
It may be better to offload this functionality to an IDE. Compiler would evaluate, whether the value is modified after initialization, or not, and highlight it accordingly. More usefully, it could show places where it gets modified.


----------------

If some explicit form of immutability is desired, here's an idea for higher level feature: boolean flag.  Quite often boolean variables are used as "one-time-flip-flops", i.e. set initially, and then reset to the opposite and never reverted back.


It may look like:

```
// "flag" is restricted boolean type
foo flag = true // initialization only with literal
...
foo = false // reset, only with the other literal 
...

foo = true // this would be forbidden
foo = my-bool-variable // forbidden
&foo // pointer taking forbidden
```

Unlike mut/non-mut labels it conveys more information about its specific purpose, and is not easily deductible by the compiler.



The compiler may also quietly optimize such flip-flops:

```
foo flag = true 
...
if ... { foo = false } 
...
if ... { foo = false } 
```

would turn into:

```
foo flag = true 
...
if ... { foo = false } 
...
if ... { if (foo != false) foo = false }  // this is the optimization, saves RAM write access
```

**Comment by medvednikov** [comment]
> It may be better to offload this functionality to an IDE. Compiler would evaluate, whether the value is modified after initialization, or not, and highlight it accordingly.

I'm 100% confident this should be done by the user like in Rust, F#, Scala etc.

As for the flag idea, I could see the benefits, but V is a small language, this would add extra complexity.

**Comment by PavelVozenilek** [comment]
I do not see much of value in explicit immutability.  It may look as a great idea, but what advantage does it really bring?  I'd never modified a value just because I could, because it lacked some const label.

In C/C++ const is harmful misfeature, providing very weak sense of security and lot of busywork. Especially in C++, double the effort by providing almost equal const/non-const methods.

C++ provides better tool in this regard: class/struct encapsulation. What is private/protected can be modified only by certain code, and it is relatively easy to find places of modification. Couldn't V use access control as more refined alternative?
