### ISSUE TITLE
checker: could not infer generic type `U` in call to `encode_array`

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#17117]
### Describe the bug

I cannot pass a generic value to a array os generic value

### Expected Behavior

All assert pass

### Current Behavior

```bash
a.v:8:2: error: could not infer generic type `T` in call to `g_array`
    6 | 
    7 | fn encode[U](val U) {
    8 |     g_array(val)
      |     ~~~~~~~~~~~~
    9 | }
   10 |
```

### Reproduction Steps

```v
fn main() {
	encode(true)
	encode([true])
	encode(1)
	encode([1])
	encode('1')
	encode(['1'])
}

fn encode[U](val U) {
	$if U is $Array {
		g_array(val)
	}
}

fn g_array[T](t []T)  {
	println(typeof(t).name)
}
```

### V version

V 0.3.2 86f8c55

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by yuyi98** [comment]
`e.encode_array(val)` cannot be used in generic fn, unless val is concrete type.
This should be `e.encode_array[StructType[string]](val)`.

**Comment by enghitalo** [comment]
> `e.encode_array(val)` cannot be used in generic fn, unless val is concrete type.
> This should be `e.encode_array[StructType[string]](val)`.

Hmmm... This is so strange. but I think it makes sense (in terms of performance) not to have to check the type of the parameter each time it is passed to a new function.

Do you have some workaround for this? I just try this and I had a bug.

**Comment by enghitalo** [comment]
This work well
```v
fn main() {
	encode([1,2,3])
}

fn encode[U](val U) {
	gg_array(unwrap_generic(val))
}

fn unwrap_generic[T](t T) T {
	return t
}

fn gg_array[T](t []T)  {
	println(t)
}
```

**Comment by enghitalo** [comment]
updated using best 'Reproduction Steps'

**Comment by felipensp** [comment]
Just rewrite the code to:

```V
fn main() {
	encode([true])
	encode([1])
	encode(['1'])
}

fn encode[U](val []U) {
	g_array(val)
}

fn g_array[T](t []T)  {
	println(typeof(t).name)
}
```

**Comment by enghitalo** [comment]
> Just rewrite the code to:
> 
> ```v
> fn main() {
> 	encode([true])
> 	encode([1])
> 	encode(['1'])
> }
> 
> fn encode[U](val []U) {
> 	g_array(val)
> }
> 
> fn g_array[T](t []T)  {
> 	println(typeof(t).name)
> }
> ```

@felipensp Thank you. But I need use the `encode` function for `U` and `[]U`. Example.

```v
	encode(true)
	encode([true])
	encode(1)
	encode([1])
	encode('1')
	encode(['1'])
```

**Comment by enghitalo** [comment]
But it is low priority issue for now.
