### ISSUE TITLE
Syntactic sugar for methods

### ISSUE THREAD

**Issue by wenq1** [vlang/v#17124]
### Describe the feature

Instead of

```
struct User {
	age int
}

fn (u User) can_register() bool {
	return u.age > 16
}
```

Is it possible to provide some syntaictic sugar, like what zig does:

```
struct User {
        age int

        fn can_register() bool {
                // how "this" is to be designed is TBD
                return this.age > 16
        }
}
```

### Use Case

It just feels normal to people coming from a Javascript backend.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.3.2 f667600

### Environment details (OS name and version, etc.)

OS: macos, macOS, 12.2, 21D49
Processor: 8 cpus, 64bit, little endian, Apple M1
CC version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)

**Comment by MatejMagat305** [comment]
Honestly, i m not sure that syntax will be more clear then current ...

**Comment by JalonSolov** [comment]
`This.age` is a reference to a struct field.  `This.age()` is a method call.

**Comment by JalonSolov** [comment]
Well, right now he couldn't call it (or even declare it) inside the struct like that.

Go and V do "receiver methods" the same way, so the current syntax is already familiar to a large number of programmers.  It would also violate the "one way" principal of V to create a 2nd way of doing the same thing.

**Comment by JalonSolov** [comment]
Well, it's already built, and no it's not go++.

The target audience is _not_ someone who just wants to do things the same way they've always done them - just use the language you're already familiar with if that's what you want.

V takes some of the best ideas from other languages, and tries to combine them in a reasonable way, while also trying to avoid the mistakes of older languages.

**Comment by wenq1** [comment]
Will it accept “more way” of doing things one day? I know it’s in early days and keeping things simple is a good idea. However as more adoption comes in, the motto might not fit all use cases forever.

**Comment by JalonSolov** [comment]
The "one way" philosophy is a bedrock philosophy for V.  I doubt that will ever change.

This doesn't mean V can't be changed at all, just that there needs to be a good, solid reason that it's a good change, other than just "adding sugar".

**Comment by wenq1** [comment]
Ok.
