### ISSUE TITLE
V panic: C error. It is impossible to store result of void function execution to a variable

### ISSUE THREAD

**Issue by alexverkhola** [vlang/v#1712]
**V version:** 0.1.18
**OS:**  Ubuntu 16.04 LTS

**What did you do?**
I am tried to store result of void function to a variable.

**What did you expect to see?**
Some value which the function returns

    test := message()
    println(test)
 
**What did you see instead?**
error: variable or field ‘test’ declared void

It is impossible to store result of void function execution to a variable if the function doesn't have the type and the return statement.

    fn main() {
        test := message()
        test
    }

    fn message() {
        println('Something wrong')
    }

**Comment by mvlootman** [comment]
@alexverkhola in the first line you don't assign the function to the test variable but you are executing the message function and storing the result of that in test variable.

you could do:
```
fn main() {
    test := message

    // invoking the function through the variable
    test()
}

fn message() {
    println('Something wrong')
}
```

However that doesn't seem to work, that might a bug.
gives: unexpected token: `)`

**Comment by alexverkhola** [comment]
@mvlootman You are right. I do not understand well what I did... I should rewrite the bug description.

**Comment by Danil-Lapirow** [comment]
You cant store `void` to a variable in the C. Also I'm not sure when it's even usable.

**Comment by alexverkhola** [comment]
@Danil-Lapirow There was the message 'V panic: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose ' in the compiler. I did what I was asked.

**Comment by mvlootman** [comment]
> @Danil-Lapirow There was the message 'V panic: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose ' in the compiler. I did what I was asked.

Ok, this is no bug, closing issue.

**Comment by alexverkhola** [comment]
@mwlootman Ok. This is no bug.
