### ISSUE TITLE
Compilation fail using datatypes.Stack with an alias type

### ISSUE THREAD

**Issue by alfaus** [vlang/v#17138]
### Describe the bug

Compilation fails if using an alias type instead of the base type.

### Expected Behavior

Program compiles and print two numbers.

### Current Behavior

Compiler fails with error:

/tmp/v_1000/stack_bug.16901299372558650991.tmp.c:12503: warning: implicit declaration of function 'Array_f64_str'
/tmp/v_1000/stack_bug.16901299372558650991.tmp.c:12503: error: '{' expected (got ";")

### Reproduction Steps

import datatypes

type Value = f64

mut a := datatypes.Stack< Value >{} // with f64 works well

a.push(1.0)
a.push(2.0)

for b in a.array() {
	println(b)
}

### V version

V 0.3.2 d3e4058

### Environment details (OS name and version, etc.)

OS: linux, Ubuntu 22.04.1 LTS
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
CC version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

**Comment by Delta456** [comment]
Works with the latest commit of V.
