### ISSUE TITLE
cgen?: memory effect of gerenics

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#17144]
### Describe the bug

Generic params is getting wrong type

### Expected Behavior

```
[]bool
[]int
[]string
```

### Current Behavior

```
[]string
[]string
[]string
```

### Reproduction Steps

```v
fn main() {
	encode(true)
	encode([true])
	encode(1)
	encode([1])
	encode('1')
	encode(['1'])
}

fn encode[U](val U) {
	$if U is $Array {
		g_array(unwrap_generic(val))
	}
}

fn unwrap_generic[T](t T) T {
	return t
}

fn g_array[T](t []T)  {
	println(typeof(t).name)
}
```

### V version

V 0.3.2 d3e4058

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by felipensp** [comment]
Just fix the code to use:

```V
fn main() {
	encode([true])
	encode([1])
	encode(['1'])
}

fn encode[U](val []U) {
	g_array[U](unwrap_generic(val))
}

fn unwrap_generic[T](t T) T {
	return t
}

fn g_array[T](t []T)  {
	println(typeof(t).name)
}
```

**Comment by enghitalo** [comment]
> ```v
> 	encode(true)
> 	encode([true])
> 	encode(1)
> 	encode([1])
> 	encode('1')
> 	encode(['1'])
> ```

Thank you. But I need use the `encode` function for `U` and `[]U`. Example.

```v
	encode(true)
	encode([true])
	encode(1)
	encode([1])
	encode('1')
	encode(['1'])
```

**Comment by enghitalo** [comment]
But it is low priority issue for now.
