### ISSUE TITLE
VWeb with WebSockets support

### ISSUE THREAD

**Issue by esquerbatua** [vlang/v#1717]
Another possibility to offer a fast communication over server <-> client connections.

**Comment by kyoto44** [comment]
+1 would be great!

**Comment by medvednikov** [comment]
I did some work on the websocket server. Will publish it soon.

**Comment by esquerbatua** [comment]
A lot of thanks!

**Comment by ledao** [comment]
await

**Comment by rclai** [comment]
Is there also websocket client support?

**Comment by officialpiyush** [comment]
Waiting for it 🙃

**Comment by Niek** [comment]
+1 for websocket client support

**Comment by seven1240** [comment]
+1

**Comment by dhonx** [comment]
+1

**Comment by memeone** [comment]
Any updates on this?

**Comment by elimisteve** [comment]
I see https://github.com/vlang/v/pull/3130 but I don't know how complete it is re: full, usable WebSocket support

**Comment by rclai** [comment]
Looks like they did it? https://github.com/vlang/v/tree/3521b7ff8966011e15260c0d5d5c880ffe885708/vlib/net/websocket

**Comment by esquerbatua** [comment]
Implemented ws, closed

**Comment by antonkatz** [comment]
This is only the client, correct? The ws server is not implemented yet?

So, with VWeb is it possible to pass data between client's browser and the V back-end server? (PS. If I butchered the architecture, forgive me, I'm new to V!)

**Comment by JalonSolov** [comment]
The ws server is implemented, just not pushed, yet.  Waiting for another merge to happen first.

**Comment by esquerbatua** [comment]
@antonkatz @JalonSolov ws server it's actually working, needs an little bit more work
https://github.com/helto4real/websocket

**Comment by JalonSolov** [comment]
Right, but it's not pushed to the main v repo.  And as you say, needs a little bit more work.

**Comment by codic12** [comment]
Seems that websockets were removed from the current master branch?
> https://github.com/helto4real/websocket
this repository does not work with the latest version of V sadly

**Comment by JalonSolov** [comment]
It was moved to the `vlib/x/websocket` in the main V code.  It is the complete websockets code, including autobahn tests (in the `tests` subdir).  Just hasn't been moved out of the e`x`perimental stage, yet.

**Comment by codic12** [comment]
Ah great, thank you!

**Comment by s00500** [comment]
Not sure where to look for this, but is there any example on how to make vweb and a net.websocket server work on the same  port muxed together ?

**Comment by timurgordon** [comment]
> Not sure where to look for this, but is there any example on how to make vweb and a net.websocket server work on the same  port muxed together ?

Hi @s00500, were you able to find an answer to this? Trying to do the same.

**Comment by s00500** [comment]
@timurgordon not so far, have not been trying a lot though
