### ISSUE TITLE
v fmt produce bad code

### ISSUE THREAD

**Issue by bokunodev** [vlang/v#17195]
### Describe the bug

`v fmt` produce bad code when formatting multiline comment in function parameters.
what strange is that, it only happen to `fn C.funcname`. it works just fine with normal v function (if reporting a syntax error is normal)

### Expected Behavior

`v fmt -w` correctly format my code or remove my comment or report syntax error explaining that comment in function params is not allowed.

### Current Behavior

it generates bad code

### Reproduction Steps

./src/main.v
```v
module main

fn main() {
	println('Hello World!')
}

fn C.f(/* mut */ buff &char) i64
```

format code above with `v fmt -w` or trough `v ls` language server.

### Additional Information/Context

it also corrupts some random part of the code when that happen. but i can't reliably reproduce this one.

### V version

V 0.3.3 988aed0

### Environment details (OS name and version, etc.)

v doctor:
```
OS: linux, Linux version 6.1.8-artix1-1 (linux@artixlinux) (gcc (GCC) 12.2.1 20230111, GNU ld (GNU Binutils) 2.40) #1 SMP PREEMPT_DYNAMIC Sun, 29 Jan 2023 17:17:21 +0000
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM)2 Quad CPU    Q8400  @ 2.66GHz
CC version: cc (GCC) 12.2.1 20230111

getwd: /tmp/x
vmodules: /home/boku/.vmodules
vroot: /home/boku/Public/v
vexe: /home/boku/Public/v/v
vexe mtime: 2023-02-02 01:16:12
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 865c0ea.988aed0

Git version: git version 2.39.1
Git vroot status: 0.3.3-19-g988aed03-dirty (1 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3-dirty
```

**Comment by paulyelesin** [comment]
I'll pick it up
