### ISSUE TITLE
match don't work for negative cases

### ISSUE THREAD

**Issue by SewerynKaminski** [vlang/v#1719]
**V version:** 0.1.18
**OS:** Ubuntu 18.04 64bit

**What did you do?**
test.v
```
match -1 {
        -1 => println('-1')
}
```

**What did you expect to see?**
-1
 
**What did you see instead?**
test.v:2:6: unexpected token: `=>`

**Comment by mvlootman** [comment]
The code for the switch_statement inside the parser, receives a Token.number for the non-negative numbers. However for e.g. -1 it gets a Token.minus. I am not sure if it should also be a number token for negative numbers. 
Could someone with more experience take a look?

**Comment by Danil-Lapirow** [comment]
The problem is that match is now not usable
Its working only with 1-token arguments

**Comment by Danil-Lapirow** [comment]
https://github.com/vlang/v/issues/1677

**Comment by SewerynKaminski** [comment]
I'm trying to fix the `match` but there is too much problems like negative numbers, enums, lack of case end, else without arrow.

This syntax is valid and work with all cases.
```
match 1 {
   case -1: {0}
   case SOME.ENUM: {1}
   default: {-1}
}
```

To eliminate `case` i replaced it with `;`. I think it could be nice fix but the first case need semicolon before. In last case no semicolon.
```
match 1 {;
   -1 => 0;
   SOME.ENUM => 1;
   else -1
}
```

Maybe semicolon is good thing at the end of each `case`. Is it good direction?
What do you think?

**Comment by Danil-Lapirow** [comment]
Write it to the https://github.com/vlang/v/issues/1677, please.

> I'm trying to fix the `match` but there is too much problems like negative numbers, enums, lack of case end, else without arrow.
> 
> This syntax is valid and work with all cases.
> 
> ```
> match 1 {
>    case -1: {0}
>    case SOME.ENUM: {1}
>    default: {-1}
> }
> ```
> 
> To eliminate `case` I replaced it with `;`. I think it could be nice fix but the first case need semicolon before. In last case no semicolon.
> 
> ```
> match 1 {;
>    -1 => 0;
>    SOME.ENUM => 1;
>    else -1
> }
> ```
> 
> Maybe semicolon is good thing at the end of each `case`. Is it good direction?
> What do you think?

**Comment by SewerynKaminski** [comment]
@Danil-Lapirow here you go :)

**Comment by Danil-Lapirow** [comment]
Thank you

**Comment by medvednikov** [comment]
Fixed.
