### ISSUE TITLE
Unexpected import symbol fmt error

### ISSUE THREAD

**Issue by ChAoSUnItY** [vlang/v#17216]
### Describe the bug

v fmt is replacing existed struct's name with a newly generated name sliced from import alias and original name.

### Expected Behavior

Import alias should not affect struct naming.

### Current Behavior

v fmt modifies original name in several places referenced original struct name.

### Reproduction Steps

- Add import alias `as compr` to `import compress` in `vlib/compress/gzip/gzip.v`
- `v fmt gzip.v -w`
- Type reference in function `validate` and `decompress` to struct `DecompressParams` will be reformatted (rename) into `DecomprParams` and causes error

### V version

~~e79b5ff~~ (in PR #17210, vfmt module hasn't being affected)
V 0.3.3 804065a (This bug has been tested in latest V)

### Environment details (OS name and version, etc.)

OS: windows, Microsoft Windows 11 Home v22000 64-bit
Processor: 20 cpus, 64bit, little endian,
CC version: Error: exec failed (CreateProcess) with code 2: 系統找不到指定的檔案。
 cmd: cc --version

getwd: C:\Users\chaos\projects\v\vlib\compress\gzip
vmodules: C:\Users\chaos\.vmodules
vroot: C:\Users\chaos\projects\v
vexe: C:\Users\chaos\projects\v\v.exe
vexe mtime: 2023-02-03 14:02:55
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 0b7a1cd.e79b5ff

Git version: git version 2.35.1.windows.2
Git vroot status: weekly.2023.05-47-g47990bc1
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 1e6e7c6f

**Comment by spytheman** [comment]
I can confirm that:
```
#148 17:15:01 ᛋ master /v/vnew❱./v fmt -diff vlib/compress/gzip/gzip.v
--- /v/vnew/vlib/compress/gzip/gzip.v   2023-02-04 17:14:16.850830336 +0200
+++ /tmp/v_1000/vfmt_01GREFXG66B99ZSRC8G11WZ4NH_gzip.v  2023-02-04 17:15:02.981259802 +0200
@@ -71,5 +71,5 @@ pub fn compress(data []u8) ![]u8 {
 
 // validate validates the header and returns its details if valid
-pub fn validate(data []u8, params DecompressParams) !GzipHeader {
+pub fn validate(data []u8, params DecomprParams) !GzipHeader {
        if data.len < gzip.min_header_length {
                return error('data is too short, not gzip compressed?')
@@ -136,5 +136,5 @@ pub fn validate(data []u8, params Decomp
 // decompresses an array of bytes using zlib and returns the decompressed bytes in a new array
 // Example: decompressed := gzip.decompress(b)?
-pub fn decompress(data []u8, params DecompressParams) ![]u8 {
+pub fn decompress(data []u8, params DecomprParams) ![]u8 {
        gzip_header := validate(data, params)!
        header_length := gzip_header.length
#0 17:15:03 ᛋ master /v/vnew❱
```
