### ISSUE TITLE
cgen: checker bug; node.left_types.len < node.left.len

### ISSUE THREAD

**Issue by walkingdevel** [vlang/v#17214]
### Describe the bug

After #17205, I thought about what if I add more parenthesis and got this bug.

```v
_ := ((print(10)))
```

### Expected Behavior

```
test.v:1:3: error: assignment mismatch: expected 1 value(s) but `print()` returns 0 value(s)
```

### Current Behavior

```
test.v:1:6: warning: redundant parentheses are used
    1 | _ := ((print(10)))
      |      ~~~~~~~~~~~~~
test.v:1:3: cgen error: checker bug; node.left_types.len < node.left.len
    1 | _ := ((print(10)))
      |   ~~
```

### Reproduction Steps

Run code from `Describe the bug`.

### V version

V 0.3.3 804065a

### Environment details (OS name and version, etc.)

macOS 13.0

**Comment by walkingdevel** [comment]
@Delta456, can you fix it?

**Comment by Delta456** [comment]
> @Delta456, can you fix it?

Yes I will fix this issue. Thanks for enlightening me to this.
