### ISSUE TITLE
can initialize enum like struct i.e. Enum{} 

### ISSUE THREAD

**Issue by Delta456** [vlang/v#17215]
### Describe the bug

I can initialise an enum like a struct and it compiles successfully.

```v
enum Hello {
    aaa
    bbb
    ccc
}

fn main() {
    a := Hello{}
    println(a)
}
```

### Expected Behavior

A compilation error like `cannot initalise an enum directly`

### Current Behavior

```
aaa
```

### Reproduction Steps

Given in `Describe the Bug`

### Possible Solution

A checker error to disallow it.

### V version

Latest

### Environment details (OS name and version, etc.)

Windows 11 WSL 2

**Comment by medvednikov** [comment]
great find
