### ISSUE TITLE
flag module to support combining flags 

### ISSUE THREAD

**Issue by gergelyk** [vlang/v#17255]
### Describe the feature

Regarding [flag](https://modules.vlang.io/flag.html) module. This would be nice if it supported combining flags. See use case below. This is handy and commonly observed in the wild. GNU tar can be one of examples.

### Use Case

instead of:

```sh
myapp -x -y -z myfile.txt
```

we could invoke it as

```sh
myapp -xyz myfile.txt
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

0.3.2 865c0ea

### Environment details (OS name and version, etc.)

MacOS

**Comment by yuyi98** [comment]
implemented.
