### ISSUE TITLE
v file Runtime cache file Not good

### ISSUE THREAD

**Issue by d1y** [vlang/v#1725]
hi.
I run `.v` file and run `REPL` Generated some cache files
![image](https://user-images.githubusercontent.com/45585937/63633971-195c3700-c683-11e9-8592-d63a132e759b.png)
I only have to delete file🌝
Is it possible to automatically mount the cached file under /tmp?
Or has it been implemented in `v`?

Thank you
谢谢

**Comment by gslicer** [comment]
May I ask what Editor you are using? Looks nice with the syntax highlighting, thx

**Comment by Delta456** [comment]
@gslicer It seems to Atom

**Comment by d1y** [comment]
> @gslicer It seems to Atom

vscode

**Comment by d1y** [comment]
> May I ask what Editor you are using? Looks nice with the syntax highlighting, thx

this is vscode editor

color theme: [macos-modern-theme](https://marketplace.visualstudio.com/items?itemName=davidbwaters.macos-modern-theme)

**Comment by gslicer** [comment]
> > May I ask what Editor you are using? Looks nice with the syntax highlighting, thx
> 
> this is vscode editor
> 
> color theme: [macos-modern-theme](https://marketplace.visualstudio.com/items?itemName=davidbwaters.macos-modern-theme)

Really cool, MS provides a Linux build and then I discovered this syntax extension: https://github.com/0x9ef/vscode-vlang/blob/master/README.md

**Comment by d1y** [comment]
> > > May I ask what Editor you are using? Looks nice with the syntax highlighting, thx
> > 
> > 
> > this is vscode editor
> > color theme: [macos-modern-theme](https://marketplace.visualstudio.com/items?itemName=davidbwaters.macos-modern-theme)
> 
> Really cool, MS provides a Linux build and then I discovered this syntax extension: [0x9ef/vscode-vlang:README.md@`master`](https://github.com/0x9ef/vscode-vlang/blob/master/README.md) [](/0x9ef/vscode-vlang/blob/HEAD@{2019-08-24T21:13:12Z}/README.md)

yes

**Comment by nedpals** [comment]
Closed. Generated C files are now stored into the OS's temporary dir.
