### ISSUE TITLE
v fmt strips function attributes

### ISSUE THREAD

**Issue by r-bar** [vlang/v#17264]
### Describe the bug

The `v fmt` command will strip function attributes from formatted output. This is most obvious with the `[params]` attribute since if it is stripped at the target function is called without arguments the program will fail to compile.

Given the following tiny, correct, well formatted V program:
```vlang
// foo.v

[params]
fn hello(person struct { name string }) string {
	if person.name == "" {
		return "Hello World!"
	} else {
		return "Hello ${person.name}"
	}
}


fn main() {
	println(hello())
}
```

### Expected Behavior

Because the given program follows the conventions prescribed by `v fmt` I would expect the input program to remain unchanged. I definitely do not expect running a code formatter to make me unable to build my formerly correct program.

### Current Behavior

The `[params]` attribute is stripped when running `v fmt foo.v`. The same issue appears to affect other attributes like `[inline]`.

### Reproduction Steps

Running `v fmt foo.v` will output:
```
// foo.v

fn hello(person struct { name string }) string {
        if person.name == '' {
                return 'Hello World!'
        } else {
                return 'Hello ${person.name}'
        }
}

fn main() {
        println(hello())
}
```

Notice the `[params]` above `fn hello` have disappeared. Now running `v foo.v` will output the following compilation error.

```
$ v foo.v
foo.v:12:10: error: expected 1 arguments, but got 0
   10 |
   11 | fn main() {
   12 |     println(hello())
      |             ~~~~~~~
   13 | }
```

### V version

V 0.3.3 d1f57ea

### Environment details (OS name and version, etc.)

❯ v doctor
OS: linux, "EndeavourOS Linux"
Processor: 16 cpus, 64bit, little endian, 12th Gen Intel(R) Core(TM) i7-1260P
CC version: cc (GCC) 12.2.1 20230201

getwd: /home/rbar/src/advent22/day12
vmodules: /home/rbar/.vmodules
vroot: /usr/lib/vlang
vexe: /usr/lib/vlang/v
vexe mtime: 2023-02-04 07:52:42
is vroot writable: false
is vmodules writable: true
V full version: V 0.3.3 d1f57ea

**Comment by r-bar** [comment]
Just wanted to say thanks for the project! I have had a great time test driving V! I am willing to try and take on the fix if this an OK first issue to try and tackle and there are no other conflicting initiatives.

**Comment by Larpon** [comment]
> Just wanted to say thanks for the project! I have had a great time test driving V! I am willing to try and take on the fix if this an OK first issue to try and tackle and there are no other conflicting initiatives.

@r-bar it looks like our, fast as lightning, @yuyi98 already took a stab at it. Do not be discouraged, though, there's plenty of other things to work on :sweat_smile:
