### ISSUE TITLE
build error: Error while inserting an account in a table with sqlite

### ISSUE THREAD

**Issue by RIC217** [vlang/v#17275]
### Describe the bug

When I try to compile my code I got a strange error :
```
utils/database.v:12:10: error: cannot use `utils.Account` as `utils.Account`
   10 | pub fn insert(db sqlite.DB, mut account Account) {
   11 |     sql db {
   12 |         insert account into Account
      |                ~~~~~~~
   13 |     }
   14 | }
```

### Expected Behavior

The code to compile.

### Current Behavior

Build error :
```
utils/database.v:12:10: error: cannot use `utils.Account` as `utils.Account`
   10 | pub fn insert(db sqlite.DB, mut account Account) {
   11 |     sql db {
   12 |         insert account into Account
      |                ~~~~~~~
   13 |     }
   14 | }
```

### Reproduction Steps

main.v
```v
module main

import db.sqlite
import utils

fn main() {
	db := sqlite.connect("account.db") or { panic(err) }

	mut account := utils.Account{}
	utils.insert(db, mut account)
}

```

utils/database.v
```v
module utils

import db.sqlite

[table: 'account']
pub struct Account {
	id int [primary; sql: serial]
}

pub fn insert(db sqlite.DB, mut account Account) {
	sql db {
		insert account into Account
	}
}
```

### Additional Information/Context
It happens only if the variable passed to the insert function is mutable.

### V version

V 0.3.3 c003bfd

### Environment details (OS name and version, etc.)

OS: linux, Ubuntu 22.10
Processor: 2 cpus, 64bit, little endian, Intel(R) Celeron(R) N4020 CPU @ 1.10GHz
CC version: cc (Ubuntu 12.2.0-3ubuntu1) 12.2.0

getwd: /home/riccardo
vmodules: /home/riccardo/.vmodules
vroot: /home/riccardo/v
vexe: /home/riccardo/v/v
vexe mtime: 2023-02-10 07:11:49
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 c003bfd

Git version: git version 2.37.2
Git vroot status: weekly.2023.06-17-gc003bfd5 (1 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by walkingdevel** [comment]
Good find. Thank you.
