### ISSUE TITLE
printing a nested struct instance fails

### ISSUE THREAD

**Issue by lobotony** [vlang/v#1727]
**V version:** 0.1.18
**OS:** Mac OS 10.14.6

**What did you do?**

    struct Inner {
        val i32
    }
    struct Outer {
         inner Inner
    }
    p := Outer{Inner{}}
    println(p.inner)

**What did you expect to see?**
successful compilation
 
**What did you see instead?**

    error: expected ')'
    println ( p tos2((byte*)"{ val: $.inner.val }") ) ;
                ^
    note: to match this '('
    println ( p tos2((byte*)"{ val: $.inner.val }") ) ;
            ^
    1 error generated.
    V panic: C error. This should never happen. Please create a GitHub issue:

**Comment by gslicer** [comment]
it seems that the variable was not initialized, this example works:
module main

struct Inner {
    val int
}
struct Outer {
    inner Inner
}

fn (o Outer) str() string {
    return o.inner.val.str()
}

fn main() {
o := Inner{69}  
p := Outer{o}
println(p.str()) // outputs "69"
}

**Comment by M4SSD35TRUCT10N** [comment]
Compiled with current master and it works.
```
struct Inner {
    val int
}
struct Outer {
     inner Inner
}
p := Outer{Inner{}}
println(p.inner)
```
Only thing was to rename `i32` to `int` because BDFL @medvednikov changed `i32` lately to `int` and `u8` to `byte` - this is for the time being final.

The output was:
{
	val: 0
}
