### ISSUE TITLE
Improper formatting of code snippets in documentation.

### ISSUE THREAD

**Issue by vnothkumar** [vlang/v#17285]
### Issues

While using the documentation for the V programming language, it has been noticed that the code snippets within the document are not properly formatted. This makes it difficult for users to understand the code and can lead to confusion.

Expected Result:
Code snippets within the document should be properly formatted and easy to read.

Actual Result:
Code snippets within the document are not properly formatted and difficult to understand.

Impact:
Inadequate formatting of code snippets can negatively impact user understanding and experience, making it difficult for them to learn and utilize the V programming language effectively.

Solution:
The formatting of code snippets within the documentation should be reviewed and improved to ensure that it is clear and easy to understand for users.

### Links

 
https://github.com/vlang/v/blob/master/doc/docs.md

**Comment by spytheman** [comment]
Can you please point out actual examples for improperly formatted snippets in the documentation?

The CI already runs `v check-md .` on every commit, and part of that is ensuring that V blocks of code in the .md files are formatted (unless there is an explicit reason for an example to not be formatted, like demonstrating an error, or invalid code etc).

**Comment by vnothkumar** [comment]
Some built-in function doesn't shows clearly.

**Comment by spytheman** [comment]
I am asking for a concrete example, so that I can understand what you mean, and so that it could be fixed.

Answering "Some built-in function doesn't shows clearly." is not specific. I do not know what exact function you had in mind.

Please either link to, or cite the specific section/block that you think is not properly formatted.
