### ISSUE TITLE
Feature request:  Macro

### ISSUE THREAD

**Issue by zaoqi** [vlang/v#173]
https://docs.racket-lang.org/reference/Macros.html
https://doc.rust-lang.org/book/ch19-06-macros.html
https://small.r7rs.org/attachment/r7rs.pdf
https://elixir-lang.org/getting-started/meta/macros.html
https://en.wikibooks.org/wiki/Introducing_Julia/Metaprogramming#Macros

**Comment by medvednikov** [comment]
https://github.com/vlang/v/issues/165
