### ISSUE TITLE
`defer` in for loop works unexpectedly

### ISSUE THREAD

**Issue by i582** [vlang/v#17310]
### Describe the bug

Code: https://play.vlang.io/p/def2a9db0f

```v
fn main() {
	for i := 0; i < 10; i++ {
		defer {
			println(i)
		}
	}
}

```

### Expected Behavior

Output:

```
9
8
7
6
...
0
```

See also Go implementation and behavior: https://go.dev/play/p/Z6udIdHNKn6

### Current Behavior

Output:

```
10
```

### Reproduction Steps

Run code above

### V version

0.3.3

### Environment details (OS name and version, etc.)

macOS 13

**Comment by JalonSolov** [comment]
`defer` is working as expected (and documented) for V.

First line in the description:  https://github.com/vlang/v/blob/master/doc/docs.md#defer

`A defer statement defers the execution of a block of statements until the surrounding function returns.`

**Comment by Delta456** [comment]
> `defer` is working as expected (and documented) for V.
> 
> First line in the description: https://github.com/vlang/v/blob/master/doc/docs.md#defer
> 
> `A defer statement defers the execution of a block of statements until the surrounding function returns.`
> 
> If you think it should work differently, that would be a feature request.

I believe defer has to work differently for `loops` like it does in Go.
