### ISSUE TITLE
`$for field in User.fields { println(field.name) }` outputs nothing if `User` is interface

### ISSUE THREAD

**Issue by i582** [vlang/v#17346]
### Describe the bug

Code: https://play.vlang.io/p/50ff4268b4

```v
interface User {
	name string
	age  int
}

fn main() {
	$for field in User.fields {
		println(field.name)
	}
	// name
	// age
}
```

### Expected Behavior

```
name
age
```

### Current Behavior

```
<empty output>
```

### Reproduction Steps

Run code above

### V version

0.3.3

### Environment details (OS name and version, etc.)

Playground

**Comment by felipensp** [comment]
It seems is not intended to work like Struct ones. What do you think @medvednikov ?

**Comment by medvednikov** [comment]
Yeah it's a bug.
