### ISSUE TITLE
warning: #warning Need to implement some method to align data here

### ISSUE THREAD

**Issue by MatejMagat305** [vlang/v#17344]
### Describe the bug

I was put doing some experiment and I put C header to other path than V equivalent, source https://github.com/vlang/vsl/pull/150

### Expected Behavior

compile normal

### Current Behavior

```
v . -cg
In file included from /tmp/v_1000/vcl_opencl_fractals_one_argument.16376654300470796700.tmp.c:928:
In file included from /home/matejmag/.vmodules/vsl/vcl/vcl.h:7:
In file included from /usr/include/CL/cl.h:21:
/usr/include/CL/cl_platform.h:543: warning: #warning Need to implement some method to align data here
/tmp/v_1000/vcl_opencl_fractals_one_argument.16376654300470796700.tmp.c:4377: error: ',' expected (got "it")
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

```

### Reproduction Steps

`v . -cg` with my branch as vcl

### V version

V 0.3.3 2382549.e066d1d

### Environment details (OS name and version, etc.)

 v doctor
OS: linux, Kali GNU/Linux Rolling
Processor: 32 cpus, 64bit, little endian, AMD Ryzen 9 5950X 16-Core Processor
CC version: cc (Debian 12.2.0-14) 12.2.0

getwd: /home/matejmag/vsl/examples/vcl_opencl_fractals_one_argument
vmodules: /home/matejmag/.vmodules
vroot: /home/matejmag/Documents/v
vexe: /home/matejmag/Documents/v/v
vexe mtime: 2023-02-17 18:41:55
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 2382549.e066d1d

Git version: git version 2.39.0
Git vroot status: weekly.2023.07-14-ge066d1d3
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by ulises-jeremias** [comment]
The problem was the way that the .h file was included and the headers dir. Not a V issue. Closing this now
