### ISSUE TITLE
Defer not executed in case of panic

### ISSUE THREAD

**Issue by gergelyk** [vlang/v#17356]
### Describe the bug

I'm not sure what is the desired behavior here, but in case of a panic, defer block is not executed in vlang:
```v
module main
fn main() {
    defer{ println("xyz") }
    panic("abc")
}
```

For comparison, golang executes defer in case of panic:

```go
package main
import "fmt"
func main() {
    defer fmt.Println("world")
    panic("abc")
}
```

Third-party crates for rust do the same:

```rust
// https://crates.io/crates/defer
use defer::defer;
fn main() {
    defer(|| println!("xxx") );
    panic!("abc");
}
```
```rust
// https://crates.io/crates/deferrer
use deferrer::defer;
fn main() {
    defer!(|| println!("xxx") );
    panic!("abc");
}
```

### Expected Behavior

Defer block is executed also in case of panic.

### Current Behavior

Defer block is not executed in case of panic.

### Reproduction Steps

```v
module main
fn main() {
    defer{ println("xyz") }
    panic("abc")
}
```

### V version

V 0.3.2 865c0ea

### Environment details (OS name and version, etc.)

MacOS

**Comment by JalonSolov** [comment]
Correct.  `panic` is immediate exit the program, no cleanup, nothing, just exit **_RIGHT NOW_**.

**Comment by gergelyk** [comment]
Thank you for clarification. I'm closing the ticket. It may be good to clarify this in the docs some day.
