### ISSUE TITLE
Can't Install V On Linux

### ISSUE THREAD

**Issue by AvicennaJr** [vlang/v#17369]
### Describe the bug

I am unable to install V on Linux. I have followed [these](https://github.com/vlang/v#installing-v-from-source) instructions.

### Expected Behavior

V language to be installed.

### Current Behavior

I get the following output:

```
make fresh_vc
make[1]: Entering directory '/home/mojo/Downloads/v'
rm -rf ./vc
git clone --filter=blob:none --quiet https://github.com/vlang/vc ./vc
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), 874.79 KiB | 747.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
make[1]: Leaving directory '/home/mojo/Downloads/v'
cd ./vc && git clean -xf && git pull --quiet
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
cc  -std=gnu99 -w -o v1.exe ./vc/v.c -lm -lpthread 
./v1.exe -no-parallel -o v2.exe  cmd/v
vlib/v/gen/c/str_intp.v:29:18: error: cannot initialize enums
   27 |     mut remove_tail_zeros := false
   28 |     fspec := node.fmts[i]
   29 |     mut fmt_type := StrIntpType{}
      |                     ~~~~~~~~~~~~~
   30 |     g.write('/*${fspec} ${sym}*/')
   31 |     // upper cases
make: *** [GNUmakefile:114: all] Error 1
```

### Reproduction Steps

- Download Linux release from [here](https://github.com/vlang/v/releases/download/0.3.3/v_linux.zip)
- Extract zip
- cd into v folder and run `make`

### Possible Solution

Cloning directly works, but the released zip has some issues.

### V version

latest

### Environment details (OS name and version, etc.)

```
MX Linux 21 
Debian
6.0.12-1
x86_64
GNU/Linux
```

**Comment by JalonSolov** [comment]
I've never had a problem installing V on linux, but I always installed by cloning the source.  You say you did that initially, but then in the **Reproduction Steps** section, you say to download the Linux .zip file... which did you actually do?

In any case, if you try the first link (installing from source), it should certainly work for you now.
