### ISSUE TITLE
create special literals for file / function / line etc.

### ISSUE THREAD

**Issue by lobotony** [vlang/v#1737]
It would be really handy for logging / debugging to have special literals that enable you to log where you are in your code. 
E.g. https://docs.swift.org/swift-book/ReferenceManual/Expressions.html#ID390

**Comment by Henrixounez** [comment]
Could that be something like those macros in C ?
https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html

I'm not familiar with Swift, but it seems familiar to that.
I agree that it would be useful for logging purposes like you have hinted.

**Comment by medvednikov** [comment]
looks useful, will do
