### ISSUE TITLE
Option literals for compound types

### ISSUE THREAD

**Issue by lemoncmd** [vlang/v#17398]
### Describe the feature

Option literals for fixed arrays, functions, and references.
While these kinds of type declarations are supported, they aren't for literals.

### Use Case

```
maybe_fixed1 := ?[3]int(none)
maybe_fixed2 := ?[3]int([1, 2, 3]!)

maybe_fn1 := ?fn(int)int(none)
maybe_fn2 := ?fn(int)int(fn(a int)int { return a })

number := 1
maybe_ref1 := ?&int(none)
maybe_ref2 := ?&int(&number)
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.3.3 d3870a0

### Environment details (OS name and version, etc.)

OS: arch linux

**Comment by felipensp** [comment]
Option pointer type are being treated at https://github.com/vlang/v/pull/17397

**Comment by felipensp** [comment]
Option fixed array at https://github.com/vlang/v/pull/17400
