### ISSUE TITLE
single const can hold multi-return values

### ISSUE THREAD

**Issue by Delta456** [vlang/v#17399]
### Describe the bug

A single const valued const can hold multi-return values

```v
fn two() (int, int) {
	return 2, 3
}

const a = two()

println(a)
```

### Expected Behavior

An error

### Current Behavior

`(2, 3)`

### Reproduction Steps

Given

### Possible Solution

A checker error

### V version

Latest

### Environment details (OS name and version, etc.)

Windows 11 WSL 2

**Comment by tobealive** [comment]
I have this finished locally. If it's not a bummer for you @Delta456 i'd submit it as PR. Let me know :+1:

**Comment by Delta456** [comment]
Sure, go ahead.
