### ISSUE TITLE
BigInteger

### ISSUE THREAD

**Issue by zaoqi** [vlang/v#174]
https://docs.racket-lang.org/reference/numbers.html?q=number%3F#%28tech._integer%29
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by ntrel** [comment]
Now that V has numeric operator overloading, BigInt could be a library type. Also a constructor function could take a string literal as a template argument which is parsed at compile time to initialize a long digit BigInt.

**Comment by zaoqi** [comment]
@medvednikov Will this feature be implemented?

**Comment by medvednikov** [comment]
Yes

**Comment by lutherwenxu** [comment]
It's implemented since a44ba0b (on Nov 2019):
https://github.com/vlang/v/tree/master/vlib/bignum
