### ISSUE TITLE
Loop Not Progressing Beyond First Iteration

### ISSUE THREAD

**Issue by CaiNiao-Yi** [vlang/v#17403]
### Describe the bug

Description:

I am facing an issue with my Vlang code where the loop does not progress beyond the first iteration. The code is as follows:

``` vlang
module main

import os

fn main(){
	for i:=0;i<=1;i++{
		println(i)
		os.system("ffmpeg.exe -version")
	}
	println("For End")
}
```
The problem is that the loop does not terminate even after the condition is met. The loop only progresses beyond the first iteration when the os.system() call to run the ffmpeg.exe command is executed.

I am running this code on Windows and using V version 0.3.3 d1f57ea.

I would appreciate any help or advice on how to resolve this issue.

Thank you.

### Expected Behavior

run `ffmpeg.exe -version` twice and then end the program

### Current Behavior

``` bash
v run .\main.v
0
0
```

### Reproduction Steps

v run .\main.v

### V version

0.3.3 d1f57ea

### Environment details (OS name and version, etc.)

OS: windows, Microsoft Windows 11 v22621 64 λ
Processor: 16 cpus, 64bit, little endian,

getwd: C:\Users\caini
vmodules: C:\Users\caini\.vmodules
vroot: C:\Users\caini\scoop\apps\v\0.3.3
vexe: C:\Users\caini\scoop\apps\v\0.3.3\v.exe
vexe mtime: 2023-01-30 09:39:10
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 d1f57ea

Git version: git version 2.39.2.windows.1
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false
thirdparty/tcc: N/A

**Comment by JalonSolov** [comment]
Your version of V is from last month.  I suggest running `v up`... if that doesn't work, cd to the V install dir, and try `git pull` then `.\make.bat`.

The code runs correctly on Linux with latest V.

**Comment by CaiNiao-Yi** [comment]
I upgraded to version 0.3.3 9a8f302, but it still doesn't work.

**Comment by lcddh** [comment]
No problem on my windows machine.

**Comment by CaiNiao-Yi** [comment]
I tried reinstalling ffmpeg, cross-compiled the code in Linux for Windows, but it still doesn't work when I run it on Windows. When I run the program, it constantly creates ffmpeg processes in the background, and eventually, my computer freezes.

**Comment by CaiNiao-Yi** [comment]
I solved the problem. It seems to be an issue with CLion. I was able to run the file successfully by running it outside the CLion project
