### ISSUE TITLE
extend struct fields modifiers declarations

### ISSUE THREAD

**Issue by dmitryuck** [vlang/v#17408]
### Describe the feature

make field declarations like a block in curly brackets

```
struct Foo {
     pub {
         a int
         b int
     }
	
    mut {
        c int
        d string 
    }

    pub mut {
        e int
    }
}
```

allow adding modifier per field

```
struct Boo {
    pub mut a int
    mut b string
    pub c i64
}
```

### Use Case

in my opinion more clear and obvious how blocks scope behavior, more like C syntax way, when mut: is like pascal blocks

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

0.3.3

### Environment details (OS name and version, etc.)

any OS

**Comment by JalonSolov** [comment]
This has been requested before, and rejected before.

Need to think bigger... what if you had a struct with 50 or 100 fields?  You would have to repeat the modifiers 50 or 100 times.

Your first example is also more typing than what actually works, now:
```v
struct Foo {
pub:
    a int
    b int
	
mut:
    c int
    d string 

pub mut:
    e int
}
```

**Comment by dmitryuck** [comment]
yes, agree, the current solution looks perfect
