### ISSUE TITLE
Define a enum, that appears twice in the generated C code

### ISSUE THREAD

**Issue by lcddh** [vlang/v#1741]
![image](https://user-images.githubusercontent.com/5841609/63650749-b81a8d80-c780-11e9-9513-eec66bd39191.png)

**Comment by Bowero** [comment]
Currently, `fn (p mut Parser) parse(pass Pass)` is being run twice. That is the reason that this line is being run twice too:
https://github.com/vlang/v/blob/99c9410cc2bd84fb4dda2e536094c42db25174fd/compiler/parser.v#L218
Currently, I see no easy way to fix this.

**Comment by medvednikov** [comment]
Fixed.

This was actually a very quick fix @Bowero https://github.com/vlang/v/commit/cca85566d32648bd031f8f15242a544f85ae27ba

**Comment by Bowero** [comment]
:(
