### ISSUE TITLE
vfmt: incorrect formatting of `$compile_warn`

### ISSUE THREAD

**Issue by impopular-guy** [vlang/v#17445]
### Describe the bug

incorrect formatting of `$compile_warn`

### Expected Behavior

correct formatting

### Current Behavior

```v
fn main() {
	.$compile_warn(WARN)
}
```

### Reproduction Steps

```v
fn main() {
	$compile_warn('WARN')
}
```

### V version

V 0.3.3 b9a8a21

### Environment details (OS name and version, etc.)

Playground

**Comment by beakash** [comment]
main() {
	$compile_warn(WARN)
}
