### ISSUE TITLE
Playground doesn't work

### ISSUE THREAD

**Issue by adsouza** [vlang/v#1745]
**What did you do?**
Went to https://vlang.io/play

**What did you expect to see?**
A code editor & a button to run it.
 
**What did you see instead?**
The code editor appears but there's no button to run it.

**Comment by Bowero** [comment]
You can use https://vlang.ide.judge0.com/ in the meantime.

**Comment by adsouza** [comment]
Thanks; will do.

**Comment by adsouza** [comment]
This example from the docs does not work: https://vlang.ide.judge0.com/?ACu4_hn35_8GTDqGLUC5mtdiYDcW

Are the docs wrong or is the compiler wrong...?

**Comment by adsouza** [comment]
Another example from the docs that does not work:
https://vlang.ide.judge0.com/?AEWqlXy5ksJnwqW3FyfJPczlI7CQ

**Comment by Bowero** [comment]
I am sorry. Judge0 has not been updated since v0.12 and I didn't notice that before I gave you the link. I strongly recommend you to build V locally then. It compiles within a second and you'll be immediately good to go.

**Comment by gslicer** [comment]
Is anyone able to contact the guy behind judge0 to keep the V playground updated?
He could run scripted `./v up` once a day or so... then it could replace the more rudimentary https://vlang.io/play which seems disabled for now?

@medvednikov after releasing the JS-backend there is still the idea of implementing the Playground using this or would it be rather preferable to partner with jugge0?

**Comment by gslicer** [comment]
All right, at least we have an up-to-date playground by [judge0](https://github.com/judge0/ide/issues/31)

**Comment by gslicer** [comment]
Now V is integrated on the **main page** of https://ide.judge0.com/?moMA

```v
// On the Judge0 IDE, V is automatically
// updated every hour to the latest version.
fn main() {
    println('hello, world')
}
```

**Comment by medvednikov** [comment]
@adsouza https://vlang.io/play is back, and it won't be gone again :)

**Comment by gslicer** [comment]
@adsouza since we have two great playgrounds up and running this ticket might be closed

**Comment by medvednikov** [comment]
I already did :)

**Comment by adsouza** [comment]
Awesome :-D
