### ISSUE TITLE
v help - no longer works

### ISSUE THREAD

**Issue by samlotti** [vlang/v#17455]
### Describe the bug

v help 
doesn't work.

v help  
`v help`: unknown help topic provided. Use `v help` for usage information.
Known help topics: .

### Expected Behavior

should show help information

### Current Behavior

show error explaining to enter when had been already entered.

### Reproduction Steps

type 

v help

### V version

V 0.3.3 15cb18c

### Environment details (OS name and version, etc.)

mac os
12.6.3 (21G419)

**Comment by JalonSolov** [comment]
You have a version of V that is 14,915 commits behind the current version.  Run `v up` to update to the latest and see if this is still a problem.

**Comment by samlotti** [comment]
works with latest.
