### ISSUE TITLE
No way to handle ORM errors/panics

### ISSUE THREAD

**Issue by thlcodes** [vlang/v#17456]
### Describe the bug

When an ORM error/panic occurs, e.g. with
```v
user := sql db {
  select from User where username == username limit 1
}
```
where the according table was deleted or never has been created (as is the case with the template currently create by `v new {name} web)
then where is no way of catching/recovering from this error gracefully.

### Expected Behavior

I would expect sth like 
```v
user := sql db {
  select from User where username == username limit 1
} or {
  eprintln(err)
  return err
}
```
to catch such errors/panic.

### Current Behavior

Currently,
```v
user := sql db {
  select from User where username == username limit 1
} or {
  eprintln(err)
  return err
}
``` 
compiles but has no effect, program still panics e.g. with
```txt
================ V panic ================
   module: main
 function: service_auth()
  message: db.sqlite.SQLError: no such table: products (1) (SELECT `id`, `user_id`, `name`, `created_at` FROM `products` WHERE `user_id` = ?1;); code: 1
     file: src/auth_services.v:37
   v hash: b9a8a21
=========================================
0   dbg                                 0x00000001001523b8 main__App_service_auth + 3512
1   dbg                                 0x000000010014e368 main__App_controller_auth + 104
2   dbg                                 0x0000000100147e89 vweb__handle_conn_T_main__App + 10169
3   dbg                                 0x00000001000b1d61 vweb__handle_conn_T_main__App_thread_wrapper + 113
4   dbg                                 0x000000010016cea8 GC_start_routine + 100
```

### Reproduction Steps

Create a new vweb app via `v new {name} web` and try to run it, create a new user and log in; the fetch will fail and above panic will be printed into the terminal.

### Possible Solution

Allow handling of errors from ORM or allow panics to be recoverd, sth. like Go goes.

### V version

Current V version: V 0.3.3 e2daa84, timestamp: 2023-03-01 21:53:03 +0200

### Environment details (OS name and version, etc.)

OS: macos, macOS, 11.7.4, 20G1120
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
CC version: Apple clang version 13.0.0 (clang-1300.0.29.30)

getwd: /Users/xxx/Projects/v/web
vmodules: /Users/xxx/.vmodules
vroot: /Users/xxx/v
vexe: /Users/xxx/v/v
vexe mtime: 2023-03-01 20:34:22
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 b9a8a21.e2daa84

Git version: git version 2.32.0 (Apple Git-132)
Git vroot status: weekly.2023.09-14-ge2daa84a
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 46662e20

**Comment by medvednikov** [comment]
You're right and we'll fix this soon. Me, @spytheman @i582 and @walkingdevel discussed this and decided to make ORM blocks return Result.

@walkingdevel will most likely implement it this month.

**Comment by medvednikov** [comment]
Fixed.
