### ISSUE TITLE
Cgen `error: field expected` for `if val != none { v := val? }`

### ISSUE THREAD

**Issue by i582** [vlang/v#17464]
### Describe the bug

See code: https://play.vlang.io/p/326df26f0b

```v
fn foo(val ?int) ?int {
	if val != none {
		v := val?
		println(v)
		return v
	}
	
	return val
}

println(foo(100))
```

### Expected Behavior

No error

### Current Behavior

Cgen error:

```
/tmp/v_60000/../../../../../../box/code.v:5: warning: assignment makes pointer from integer without a cast
/tmp/v_60000/../../../../../../box/code.v:5: warning: cast between pointer and integer of different size
/tmp/v_60000/../../../../../../box/code.v:5: error: field expected
builder error: 
```

### Reproduction Steps

Run code above

### V version

0.3.3

### Environment details (OS name and version, etc.)

Playground

**Comment by felipensp** [comment]
I can't reproduce it. Can you test again with a fresh Vversion?

**Comment by i582** [comment]
Already fixed
