### ISSUE TITLE
vweb should stop server immediately.

### ISSUE THREAD

**Issue by l-33ter** [vlang/v#17481]
### Describe the feature

When I start a server with 'vweb' and shut it down for reconfiguration , why I must always confirm it? It gets on my nerves to have to confirm it with Y/N every time. I don't think it happens that often that you don't want to quit the server at all.

![image](https://user-images.githubusercontent.com/77815858/222665324-d487cf26-c0ff-4bda-a2ce-6429f12825de.png)

### Use Case

I know exactly what I'm doing. And even if it is terminated unintentionally, the server is up again very quickly.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.3.3 17000ef

### Environment details (OS name and version, etc.)

OS: windows, Microsoft Windows 11 Enterprise Insider Preview v25300 64-bit
Processor: 32 cpus, 64bit, little endian,
CC version: Error: exec failed (CreateProcess) with code 2: Das System kann die angegebene Datei nicht finden.
 cmd: cc --version

getwd: C:\Users\mrcl\testing\html
vmodules: C:\Users\mrcl\.vmodules
vroot: C:\git\v
vexe: C:\git\v\v.exe
vexe mtime: 2023-03-02 15:04:05
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 d971d93.17000ef

Git version: git version 2.39.1.windows.1
Git vroot status: weekly.2023.09-18-g17000ef7-dirty (3 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 1e6e7c6f

**Comment by medvednikov** [comment]
This seems to be done by Windows or cmd.exe

**Comment by l-33ter** [comment]
Checked every setting in Microsoft.Terminal, twice - but I will look again :) and then I'll get back to you

**Comment by l-33ter** [comment]
Nope... did not found anything... tried in every powershell-version / cmd.exe / different terminals, every time I had to confirm it - then I switched to a linux terminal and there was no confirmation :)

**Comment by JalonSolov** [comment]
Yes, it is a very Windows specific thing.

**Comment by l-33ter** [comment]
Great! :) - thanks for the answer!
already thought it was a mistake on my part - I can live with that.
It's more of a 'nice to have' feature :). My actual application will stay in a docker container anyway!
