### ISSUE TITLE
Cannot compile stage 2

### ISSUE THREAD

**Issue by comcloudway** [vlang/v#17499]
### Describe the bug

I was just trying to build version `0.3.3`, but I get an error when building stage 2.

I build the basic `v` compiler with c: `tcc -std=gnu11 -w -o v1 vc/v.c -bt10 -lm -lexecinfo -lpthread` and then I tried building stage 2 with it:
`./v1 -no-parallel -o v2 -cc tcc cmd/v`

### Expected Behavior

I expected v to produce the stage 2, which I would then use to build the staging version:
`./v2 -o v -cc tcc cmd/v`

### Current Behavior

```
/tmp/v_1000/v2.8241113989093628201.tmp.c: In function 'v__parser__Parser_check_sql_where_expr_has_no_undefined_variables':
/tmp/v_1000/v2.8241113989093628201.tmp.c:101101:121: error: incompatible type for argument 3 of 'v__parser__Parser_check_undefined_variables'
101101 |                         _result_void _t1 = v__parser__Parser_check_undefined_variables(p, unacceptable_variable_names, (*expr->_v__ast__Ident));
       |                                                                                                                        ~^~~~~~~~~~~~~~~~~~~~~~
       |                                                                                                                         |
       |                                                                                                                         v__ast__Ident
/tmp/v_1000/v2.8241113989093628201.tmp.c:91774:113: note: expected 'v__ast__Expr' but argument is of type 'v__ast__Ident'
91774 | _result_void v__parser__Parser_check_undefined_variables(v__parser__Parser* p, Array_string names, v__ast__Expr val) {
      |                                                                                                    ~~~~~~~~~~~~~^~~
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose
```

### Reproduction Steps

```bash
	ln -s /usr/lib/libgc.a thirdparty/tcc/lib/libgc.a

	echo building v using c
	tcc -std=gnu11 -w -o v1 vc/v.c -bt10 -lm -lexecinfo -lpthread
	echo building stage 2
	./v1 -no-parallel -o v2 -cc tcc cmd/v -cg
```

### Additional Information/Context

NOTE: I'm running on alpine Linux and thus had to modify the Makefile

### V version

https://github.com/vlang/v/archive/refs/tags/0.3.3.tar.gz

### Environment details (OS name and version, etc.)

I cannot execute v, but as stated above, I'm running Alpine Linux (edge) on an x86_64 AMD laptop.

**Comment by spytheman** [comment]
The recommended way to install V is from source:
`git clone https://github.com/vlang/v && cd v && make`

V tagged with `0.3.3`, is from `d1f57ea 2023-01-30 18:20`, and that version is not compatible with the current `vc/v.c` anymore. The version of `vc/v.c`, that was used for that V version, is `1f7f024`.

=> If you want to compile it, you will also have to first do:

`git clone --filter=blob:none https://github.com/vlang/vc vc/ ; git -C vc/ checkout 1f7f024`

![image](https://user-images.githubusercontent.com/26967/222894231-ec26d60a-fb96-4e1a-b320-801bfe237e82.png)

**Comment by trollkarlen** [comment]
How do you find out which vc version works with which vlang version ?
Would it not be a good idea to either tag vc with the vlang tags or even use git submodules for proper handling of dependencies ?

**Comment by JalonSolov** [comment]
`vc/v.c` and `vc/v_win.c` are automatically generated on every merge to the main V repo.
