### ISSUE TITLE
`make` doesn't see `tcc` even though it's in PATH.

### ISSUE THREAD

**Issue by elenakrittik** [vlang/v#17493]
### Describe the bug

I (without any reason for that, though) want to compile V with TinyCC, but since i'm using Termux (Android) and don't have root, tcc binary downloaded from `vlang/tccbin` doesn't work. I then cloned the tcc repo (`git://repo.or.cz/tinycc.git`), built it and added the `tcc` binary to the PATH myself, but what i saw is that make doesn't look for `tcc` in PATH at all and only looks for it in `thirdparty/tcc/`. I tried symlinking `tcc` binary to `thirdparty/tcc/tcc`, but when i ran make, it simply nuked the folder and tried to use `tcc` from the `tccbin` repo. Is there any way to tell make to use `tcc` from PATH (or not nuke the folder)?

### Expected Behavior

I expected make to try to use `tcc` in PATH if `tcc` from `tccbin` repo fails.

### Current Behavior

Make doesn't look for `tcc` in PATH at all, and when you try to symlink tcc to `thirdparty/tcc/tcc` make just nukes it and downloads `tcc` from the `tccbin` repo instead.

### Reproduction Steps

```sh
# This script assumes that ~/.local/bin/ is in PATH, all of
# the required TinyCC and V dependencies are installed
# and tcc binary downloaded by make from vlang/tccbin
# repo does not work.
git clone git://repo.or.cz/tinycc.git && cd tinycc
./configure && make && ln -s ./tcc ~/.local/bin/tcc
cd ..

git clone https://github.com/vlang/v && cd v
# See that tcc binary from ~/.local/bin/ is not used
# despite being in PATH.
make

rm -rf ./v ./vc # Nuke to perform a fresh build.

# Try to link executable.
ln -s $(which tcc) ./thirdparty/tcc/tcc
# See that thirdparty/tcc is nuked before the build start.
make
```

### Possible Solution

Allow to specify where the `tcc` binary is located.

### V version

V 0.3.3 3c23a7e

### Environment details (OS name and version, etc.)

OS: **termux, 4.14.186-perf-gec71448d08b7, #1 SMP PREEMPT Tue Jul 19 20:46:44 CST 2022**
Processor: **8 cpus, 64bit, little endian**
CC version: **clang version 15.0.7**

getwd: **/data/data/com.termux/files/home/v**
vmodules: **/data/data/com.termux/files/home/.vmodules**
vroot: **/data/data/com.termux/files/home/v**
vexe: **/data/data/com.termux/files/home/v/v**
vexe mtime: **2023-03-03 17:00:41**
is vroot writeable: **true**
is vmodules writeable: **true**
V full version: **V 0.3.3 5454562.3c23a7e**

Git version: **git version 2.39.2**
Git vroot status: **weekly.2023.09-25-g3c23a7eb**
.git/config present: **true**
thirdparty/tcc status: **thirdparty-unknown-unknown de82a130**

(some additional info i think you might find useful)
Android version: **11 RP1A.200720.011**
Termux version: **0.118.0**

**Comment by JalonSolov** [comment]
Link to `thirdparty/tcc/tcc.exe` instead.

Windows _must_ have the .exe, and nothing else cares, so it's easier to always name it `tcc.exe`.

**Comment by elenakrittik** [comment]
This issue was reported on Android inside a Linux environment. Windows solutions will not work.

**Comment by JalonSolov** [comment]
This is not a Windows solution.  It has nothing to do with Windows.  This is about naming the thing to be called.  V expects the thirdparty version to be named `tcc.exe` no matter which OS you're trying to run on.

For example, this is what I have on Linux, under `thirdparty/tcc`:
```
-rwxr-xr-x 1 jalon jalon 2459032 Nov  5  2022 tcc.exe
```

**Comment by elenakrittik** [comment]
Okay, thanks. I unfortunately cannot verify if the solution works, but if you are sure enough it does say so and i'll re-close as completed.
