### ISSUE TITLE
Formatter adds module name before constants without considering current scope

### ISSUE THREAD

**Issue by ChristoPy** [vlang/v#17504]
### Describe the bug

When running the formatter `v fmt -w .` it adds module names to constants, which is expected.

But it is not aware of the current scope.  
If the scope has a variable name with the same name as the module, it adds the module name but a name clash happens.

### Expected Behavior

In this code, the `my_array` reference should be kept unchanged because `example` does not references the module.
```v
module example

const my_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

pub fn print_all(example string) {
	for item in my_array {
		println(item)
	}
}
```

### Current Behavior

Currently `my_array` becomes `example.my_array`, which not only VLS complains about it but the code does not compile.
```v
module example

const my_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

pub fn print_all(example string) {
	for item in example.my_array {
		println(item)
	}
}
```

### Reproduction Steps

This repo contains a reproducible example:

https://github.com/ChristoPy/v-fmt-bug-reproduction

### Possible Solution

The formatter can be be more aware of the current scope, so it can check if the module name exists inside it and does not apply the module name to the constant.

### V version

V 0.3.3 1a48d08

### Environment details (OS name and version, etc.)

OS: linux, Ubuntu 22.04.2 LTS
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
CC version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

getwd: /home/chris
vmodules: /home/chris/.vmodules
vroot: /home/chris/v
vexe: /home/chris/v/v
vexe mtime: 2023-03-04 15:46:22
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 1a48d08

Git version: git version 2.34.1
Git vroot status: weekly.2023.09-33-g1a48d08d
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by yuyi98** [comment]
```v
			// Force usage of full path to const in the same module:
			// `println(minute)` => `println(time.minute)`
			// This makes it clear that a module const is being used
			// (since V's consts are no longer ALL_CAP).
			// ^^^ except for `main`, where consts are allowed to not have a `main.` prefix.
```

**Comment by JalonSolov** [comment]
@i582 If v-analyzer is complaining about this, it will need to be fixed there.
