### ISSUE TITLE
struct parsing breaks when specifying float literals with an 'f' in constructor

### ISSUE THREAD

**Issue by lobotony** [vlang/v#1750]
**V version:** 0.1.18
**OS:** MacOS 10.14.6

**What did you do?**

    struct test {
        v0 f32
        v1 int 
        v2 u16
        v3 u32
    }
    t := test{1.0f, 13, u16(17), u32(29)}
    println(json.encode(t))

**What did you expect to see?**
successful compilation OR error that floats don't need a trailing 'f' 
 
**What did you see instead?**
compiler error: 'too few values in `test` literal (1 instead of 4)'

**Comment by ntrel** [comment]
Just wondering, does V need to support a `f` prefix - can't people just use `.0` after the last digit?

**Comment by lobotony** [comment]
Pretty sure V doesn't need an additional 'f' there, but it shouldn't break cryptically.

**Comment by medvednikov** [comment]
No `f` is needed, `.0` is used instead.
