### ISSUE TITLE
json.encode doesn't encode u16/u32 correctly

### ISSUE THREAD

**Issue by lobotony** [vlang/v#1751]
**V version:** 0.1.18
**OS:** MacOS 10.14.6

**What did you do?**

    struct test {
        v0 f32
        v1 int 
        v2 u16
        v3 u32
    }
    t := test{1.0, 13, u16(17), u32(29)}
    println(json.encode(t))

**What did you expect to see?**
{"v0":1,"v1":13,"v2":17,"v3":29}
 
**What did you see instead?**
{"v0":1,"v1":13,"v2":{},"v3":{}}

**Comment by Bowero** [comment]
Note that these comments are also part of my own documentation. I am currently working on this.

I was reading the generated C file, when I stumbled upon this ingenious piece of code:

```c
cJSON* json__jsencode_u32(u32 val) {
    cJSON *o = cJSON_CreateObject();
    string res = tos2("");
    return o;
}
```

The question now is where this is generated (and why). It was probably designed to be a temporary fix.
