### ISSUE TITLE
Multiple errors when initializing array of options

### ISSUE THREAD

**Issue by impopular-guy** [vlang/v#17559]
### Describe the bug

1. ```v
	a := [?int(none), 1]
	println(a)
	```
	expected: `[Option(error: none), Option(1)]`
	current:  `[Option(error: none), Option(error: none)]`

2. ```v
	_ := [?int(none), none]
	```
	expected: success
	current:  `builder error: cannot convert 'extern struct IError' to 'unsigned char'`

3. ```v
	a := []?int{len: 2, init: 1}
	println(a)
	```
	expected: `[Option(1), Option(1)]`
	current:  `[Option(error: none), Option(error: none)]`

4. ```v
	a := []?int{len: 2, init: none}
	println(a)
	```
	expected: `[Option(error: none), Option(error: none)]`
	current: `builder error: cannot convert 'extern struct IError' to 'unsigned char'`

### Expected Behavior

see above

### Current Behavior

see above

### Reproduction Steps

see above

https://play.vlang.io/p/68682e3e14

### V version

V 0.3.3 2879afa

### Environment details (OS name and version, etc.)

Playground

**Comment by felipensp** [comment]
Hello. The 3 and 4 points are already fixed in this week.
