### ISSUE TITLE
build error for wasm: unhandled node  v.ast.StringInterLiteral

### ISSUE THREAD

**Issue by alwint3r** [vlang/v#17557]
### Describe the bug

V failed building for wasm from a source code with the following code

```v
fn adder(x int, y int) int {
	return x + y
}

fn main() {
	println('${adder(1, 2)}')

        // this works
	// println(adder(1, 2))
}
```

Error:

```
wasm error: wasm.expr(): unhandled node: v.ast.StringInterLiteral
```

### Expected Behavior

Build success

### Current Behavior

```
wasm error: wasm.expr(): unhandled node: v.ast.StringInterLiteral
```

### Reproduction Steps

Compile the following V code:

```v
fn adder(x int, y int) int {
	return x + y
}

fn main() {
	println('${adder(1, 2)}')
}
```

```
v -b wasm main.v
```

### V version

V 0.3.3 2597efa, timestamp: 2023-03-07 23:53:56 +0300

### Environment details (OS name and version, etc.)

OS: macos, macOS, 12.6.3, 21G419
Processor: 8 cpus, 64bit, little endian, Apple M1 Pro
CC version: Apple clang version 14.0.0 (clang-1400.0.29.202)

**Comment by l1mey112** [comment]
The error message `unhandled node` means that the current node inside the AST is not implemented. String literal interpolation is currently not supported. It is a large task, but when proper memory allocation and more functionality in the standard library it will be possible.

**Comment by alwint3r** [comment]
Alright, thanks!
