### ISSUE TITLE
Closures

### ISSUE THREAD

**Issue by zaoqi** [vlang/v#176]
https://docs.racket-lang.org/reference/lambda.html#(form._((lib._racket%2Fprivate%2Fbase..rkt)._lambda))
https://en.wikipedia.org/wiki/Closure_(computer_programming)

**Comment by medvednikov** [comment]
Closures will be implemented in May.

**Comment by SuperFola** [comment]
Since you're planning to add closure, maybe it's time to think about adding explicit capture for closures

**Comment by zaoqi** [comment]
Closure was implemented in 17 Jul 2019.Not `May`.
