### ISSUE TITLE
Ability to run tests single threaded

### ISSUE THREAD

**Issue by brandonpille** [vlang/v#17620]
### Describe the feature

The tests are executed with multiple threads leading to test failures in case the tests need to be run sequentially. It would be amazing to be able to specify the amount of threads used during execution of the tests.

### Use Case

See description

### Proposed Solution

See description

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

0.3.3

### Environment details (OS name and version, etc.)

OS: linux, Ubuntu 22.04.1 LTS
Processor: 16 cpus, 64bit, little endian, 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
CC version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

getwd: /work/crystallib
vmodules: /home/brandon/.vmodules
vroot: /work/v
vexe: /work/v/v
vexe mtime: 2023-03-13 09:30:27
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 5454562.5cb1f89

Git version: git version 2.34.1
Git vroot status: weekly.2023.09-80-g5cb1f896 (2 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by JalonSolov** [comment]
Try `VJOBS=1 v test ...`

**Comment by brandonpille** [comment]
Nice thank you. It's not documented very well though. Can you fix it?
