### ISSUE TITLE
Cant read a large file at once an have no way to read it line by line

### ISSUE THREAD

**Issue by 137-Trimethylxanthin** [vlang/v#17635]
### Describe the bug

idk if i am just dumb or have not enough ram but when i os.read_lines / .read_file or just gennerally try to read my file "kaonashi.txt" a 10gb password list i get an panic error

### Expected Behavior

should store the file line by line in an array or in an string

### Current Behavior

V panic: int(9753371083) cast results in 1163436491
v hash: 9ad1c2f
/tmp/v_1000/main.17381133286115688069.tmp.c:8146: at _v_panic: Backtrace
/tmp/v_1000/main.17381133286115688069.tmp.c:20299: by main__main
/tmp/v_1000/main.17381133286115688069.tmp.c:20901: by main

### Reproduction Steps

1) download a large file like mine kaonashi.txt (10 gb)
2) try to read that file with v
3) panic

### Possible Solution

maybe if i read the file in chunks or line by line it would work.

### Additional Information/Context

sorry if i have written it badly, i dont usually write an issue and try to fix it myself but i am just completely lost at this point.
thanks for any help

### V version

V 0.3.3 d1f57ea

### Environment details (OS name and version, etc.)

OS: linux, "Arch Linux"
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 3700X 8-Core Processor
CC version: cc (GCC) 12.2.1 20230201

getwd: /home/maxi/IdeaProjects/5word_extractor
vmodules: /home/maxi/.vmodules
vroot: /usr/lib/vlang
vexe: /usr/lib/vlang/v
vexe mtime: 2023-03-13 16:18:40
is vroot writable: false
is vmodules writable: true
V full version: V 0.3.3 d1f57ea

Git version: git version 2.39.2
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false
thirdparty/tcc status: Error: fatal: detected dubious ownership in repository at '/usr/lib/vlang/thirdparty/tcc'
To add an exception for this directory, call:

        git config --global --add safe.directory /usr/lib/vlang/thirdparty/tcc
 Error: fatal: detected dubious ownership in repository at '/usr/lib/vlang/thirdparty/tcc'
To add an exception for this directory, call:

        git config --global --add safe.directory /usr/lib/vlang/thirdparty/tcc

**Comment by JalonSolov** [comment]
You have an old version of V... don't know where or how you got it, but it is 14,788 commits behind the current.

First thing to do is reinstall V using these instructions:  https://github.com/vlang/v#installing-v-from-source

Then, take a look at https://modules.vlang.io/io.html#new_buffered_reader - that's what you'll need to read the file in a bit at a time, instead of all at once.

**Comment by spytheman** [comment]
Try something like this:

```v
import os
import io

file := "kaonashi.txt"
mut f := os.open(file) or { panic(err) }
defer { f.close() }
mut r := io.new_buffered_reader(reader: f, cap: 4096)
for {
        l := r.read_line() or { break }
        println('Line: $l')
}
```

**Comment by 137-Trimethylxanthin** [comment]
Ok i will reinstall it and the buffer reader worked like a charm even on my old v and i install it from the arch repo

**Comment by myastrotong** [comment]
vlang can directly call C codes, so you can use C fgets() function in v:
vlang is fundamentally a better C, so it is not a shame to directlly use C in v! 
below is a demo:
```
#include <stdio.h>

fn main(){
	file_name :="readfile_linebyline.v"	
	fp:=C.fopen(&char(file_name.str),c'rb')
	if 0==fp {
		eprintln('open file err!' )  
	}
	defer{
		C.fclose(fp)
	}
	
	mut line :=''.repeat(1024)	
	for{
		ret :=C.fgets(line.str,1024,fp)
		
		unsafe{
			print(line.str.vstring())
		}
		
		if 0==ret {
			break
		}
	}
}
```

**Comment by JalonSolov** [comment]
The only problem with using direct C calls in V is that it won't work with the other backends... JavaScript, WASM, FP, etc.  May not work with native.

In other words, is you use direct C calls in your code, you are pretty much locking yourself to the C backend.
