### ISSUE TITLE
V is now supported by GitHub!

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#1764]
<img width="686" alt="Screen Shot 2019-08-27 at 19 44 45" src="https://user-images.githubusercontent.com/687996/63794292-58e88480-c90a-11e9-804d-13b4cfec9f2b.png">

<img width="1009" alt="Screen Shot 2019-08-27 at 22 48 57" src="https://user-images.githubusercontent.com/687996/63803147-e339e400-c91c-11e9-8834-fdeaf4e8a9c3.png">

**Comment by thomasb892** [comment]
Well, how do you conclude that it's being supported by GitHub? Have you got any mail from them with appreciation

**Comment by Delta456** [comment]
@thomasb892 There was a new release of github/linguist which has V in it.

**Comment by thomasb892** [comment]
Also this language is in fast-paced development which is great. I would love support for operator overloading, missed it in Java.

**Comment by Delta456** [comment]
@thomasb892 V already has operator overloading.

**Comment by thomasb892** [comment]
@Delta456 thanks i just noticed it. Which parser is used for V lang?

**Comment by medvednikov** [comment]
@thomasb892 I participated in the process.

V uses its own parser.
