### ISSUE TITLE
V => JavaScript translation this week and other future possibilities

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#1767]
I'll be wrapping up the JavaScript backend this week, so that the playground can be implemented using a V compiler running in the browser.

I'm not a fan of JavaScript and I wanted to use WebAssembly instead, but I had to rely on Emscripten, since generating WA from scratch is a lot of work (the entire V compiler has to work well with it). That meant that I also had to run a C compiler via WA, but that could only be done via x86 emulation in the browser... and that's way too complicated and buggy.

The good thing is I made the compiler a lot more extendable, and adding other backends is trivial now, so we'll potentially be able to do V => Java, V => Go, V => C# etc.

And since the plan is to have translators from other languages to V (C/C++, Go, etc), V can become a lingua franca of the programming languages and allow translation between any two languages (e.g. C++ => V => C, Go => V => Java etc). 

What do you think?

@elimisteve @ylluminate you'd probably be interested in this :)

**Comment by spytheman** [comment]
Having multiple backends in general is good. 

I am afraid however that it may be too early for this. 

The language itself is still changing, and supporting each additional backend will cost us development speed. 

(we can already see that with all the msvc related issues/PRs, and that is not another language, just another C compiler...)

**Comment by medvednikov** [comment]
I agree, but I wanted to implement an extra backend early, because otherwise it'd be too hard in the future.

`msvc` issues is just Microsoft being Microsoft :)

**Comment by dumblob** [comment]
For JS/WASM this [C-like arithmetic library](https://github.com/lemire/jstypes ) might come handy.

**Comment by nachoverdon** [comment]
If you do V -> Haxe, you'll basically have V -> C, C++, C#, Java, JavaScript, Python, PHP, ActionScript, Lua, HashLink, HashLink. Might be worth prioritizing V->Haxe and then add native support to translate to those languages directly.

**Comment by ylluminate** [comment]
That is very interesting @nachoverdon. I don't necessarily think Haxe should be a priority over direct WASM since Emscripten is carefully specialized and really fantastic for both WASM + JS generation (also, the bulk of platforms will already be covered without Haxe, but I guess we could / should explore this more: https://www.reddit.com/r/haxe/comments/7l2ehs/haxe_to_webassembly/), but this is definitely interesting...

The thing I fear, and perhaps it's entirely unfounded, is that a Haxe abstraction layer might complicate things a bit more than the current path @medvednikov is pursuing. Ie, with Haxe we'd be looking at `V -> Haxe -> HashLink or Hxcpp -> WASM`.  Hmmm...

**Comment by medvednikov** [comment]
I agree with @ylluminate here

Adding another layer means more complexity, and a dependency on a not very mature application.

I made adding new backends very easy. I'm really excited and can't wait to publish my work.

Adding, say, a new Go backend, will take me about 2 hours in total.

**Comment by elimisteve** [comment]
> I made adding new backends very easy. I'm really excited and can't wait to publish my work.

Excited to see it! Show it :smile: .

**Comment by donnisnoni95** [comment]
That's a very good idea ... it looks rather difficult ... but I believe that all of you can do that ... if I have time ... I will try to help.

**Comment by donnisnoni95** [comment]
@medvednikov  Will it also involve `node c/c++ addons` ??

**Comment by herudi** [comment]
> @medvednikov Will it also involve `node c/c++ addons` ??

Great idea. 
This is the N-Api list : 
- [official](https://github.com/nodejs/node-addon-api) => C/C++.
- [napi-rs](https://napi.rs/) => Rust.
- [napi-nim](https://github.com/andi23rosca/napi-nim) => Nim.
