### ISSUE TITLE
vweb confused by js string interpolation

### ISSUE THREAD

**Issue by xzripper** [vlang/v#17674]
### Describe the bug

I'm trying to create simple test project with VWeb.
But i'm getting this error:
```index.html:29:35: error: undefined ident: `userName```
The code at this line (there is no such line but i think it's here).
```html
    <script>
        function alertName() {
            let userName = document.getElementById("_user_name").value;

            alert(`Your name is ${userName}!`);
        }
    </script>
```
What's wrong!

### Expected Behavior

I expected it to work.

### Current Behavior

Unknown error without any reason.

### Reproduction Steps

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page.</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data" action="/printname">
        <input name="user_name" id="_user_name">
        <input type="submit" value="Print on another page!">
    </form>

    <button onclick="alertName()">Alert my name!</button>

    <script>
        function alertName() {
            let userName = document.getElementById("_user_name").value;

            alert(`Your name is ${userName}!`);
        }
    </script>
</body>
</html>
```

### V version

V 0.3.3 d7a418f

### Environment details (OS name and version, etc.)

```
OS: windows,  Windows 10 Pro v19045 64-bit
Processor: 6 cpus, 64bit, little endian,  
```

**Comment by JalonSolov** [comment]
That looks like a weird mix of JavaScript and V.  That'll never work.

**Comment by medvednikov** [comment]
I think it's just Vweb being confused by JS interpolation which is also ${}.

**Comment by xzripper** [comment]
> That looks like a weird mix of JavaScript and V. That'll never work.

that works, thank
