### ISSUE TITLE
for i, c in string

### ISSUE THREAD

**Issue by aderthecoder** [vlang/v#1768]
**V version:**  0.1.18
**OS:** windows 10 64-bit

**What did you do?**
```
for i, c in a_string {
  println('$i) $c')
}
```

**What did you expect to see?**
it compiles without any error
 
**What did you see instead?**
```
error: unknown type name 'ng'
  ng _ = ((ng *) tmp8 . data)[index];

V panic: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

**Comment by aderthecoder** [comment]
I'm an idiot, you can't iterate a string using for loop. I'll close this issue.

**Comment by medvednikov** [comment]
V should handle this and give an error message.

I'll keep it open until it's fixed.

**Comment by joe-conigliaro** [comment]
@aderthecoder jfyi this is handy
```
for i, c in a_string.bytes() {
}
```
