### ISSUE TITLE
Compiling closure with generics

### ISSUE THREAD

**Issue by gporrata** [vlang/v#17749]
### Describe the bug

V seems to error when compiling a closure with generics.

```vlang
pub fn curry1of2<A, B, Z>(
	predicate fn(arg0 A, arg1 B) Z,
	arg0 A
) fn(B) Z
{
	return fn[predicate, arg0] <B, Z> (arg1 B) Z {
		return predicate(arg0, arg1)
	}
}
```

### Expected Behavior

Expecting it to compile. If I replace all of the generic arguments with int and return type to string, it would compile and run successfully.

### Current Behavior

/tmp/v_1000/tsession_7f85b475f740_1006449250452969/curryN_test.3252417417996628416.tmp.c:2512: error: ';' expected (got "anon_fn_0657ff114496b8f9_b__Z_140_T_int_int_string")

### Reproduction Steps

Copy code to a file named curryN.v. 
```vlang
module test123
pub fn curry1of2<A, B, Z>(
	predicate fn(arg0 A, arg1 B) Z,
	arg0 A
) fn(B) Z
{
	return fn[predicate, arg0] <B, Z> (arg1 B) Z {
		return predicate(arg0, arg1)
	}
}
```
Copy code to a file named curryN_test.v
```vlang
import test123 as t

fn test_curry1of2() {
	existing_fn := fn (arg0 int, arg1 int) string {
		return (arg0 + arg1).str()
	}
	new_fn := t.curry1of2<int, int, string>(existing_fn, 100)
	assert(new_fn(1) == '101')
}
```
Then do
```bash
$ v test .
```

### V version

0.3.3

### Environment details (OS name and version, etc.)

Ubuntu 22 Nuc 11 on Amd

**Comment by felipensp** [comment]
@yuyi98 If you declare the closure as `return fn[predicate, arg0] <B, Z> (arg1 B) Z {`, i.e. using the same number of generic_names than the enclosing function it works.

**Comment by JalonSolov** [comment]
You also need to update your V, if you really only have 0.3.3.

**Comment by gporrata** [comment]
Yup. That works. Thank you.
