### ISSUE TITLE
Compile time reflection for enums

### ISSUE THREAD

**Issue by saturn4er** [vlang/v#17748]
### Describe the feature

It would be nice to have ability to use information about enums for compile time reflections.

### Use Case

Here's example when it will be helpful. 

```v
enum SomeEnum as i8 {
	a
	b
	c
}

fn toSomeEnum(val i8) !SomeEnum {
	$for item in SomeEnum.items {
		if item.value == val {
			return item
		}
	}
	return error("invalid some enum value($val)")
}
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

0.3.3

### Environment details (OS name and version, etc.)

V full version: V 0.3.3 6b5c746
OS: macos, macOS, 13.3, 22E5219e
Processor: 10 cpus, 64bit, little endian, Apple M1 Pro

**Comment by JalonSolov** [comment]
Do `v up`.  The latest commit fixed an issue with comptime enum handling.

**Comment by saturn4er** [comment]
@JalonSolov Is there any example?

**Comment by saturn4er** [comment]
thanks a lot
