### ISSUE TITLE
If a function with an optional return type returns an error instead of `none`, V lets use a return value as a normal struct.

### ISSUE THREAD

**Issue by walkingdevel** [vlang/v#17753]
### Describe the bug

https://play.vlang.io/?query=d8ebaf5fec

```v
fn throw_error() ?string {
	return error('boo')
}

fn main() {
	err_value := throw_error()
	
	println(err_value)
}
```

### Expected Behavior

A compile-time error forces me to change the return type from option to result. 

### Current Behavior

```
Option(error: boo)
```

### Reproduction Steps

Run code from https://play.vlang.io/?query=d8ebaf5fec

### V version

V 0.3.3 ddcc22f

### Environment details (OS name and version, etc.)

macOS 13.0

**Comment by spytheman** [comment]
That is not a bug, just something that in time will become an error (for now, it is still a warning), after we remove the compatibility with the old 3 state `?Type` :
 ```
#0 13:48:53 ᛋ master /v/vnew❱v oo.v 
oo.v:2:2: warning: Option and Result types have been split, use `!Foo` to return errors
    1 | fn throw_error() ?string {
    2 |     return error('boo')
      |     ~~~~~~~~~~~~~~~~~~~
    3 | }
    4 |
#0 13:48:54 ᛋ master /v/vnew❱
```

**Comment by walkingdevel** [comment]
I saw no warnings because I had run it on V Playground which doesn't display warnings. But I think no need to close this issue because it can be a reminder about enabling throwing an error instead of a warning.
