### ISSUE TITLE
Runtime invalid memory access with db.mysql 

### ISSUE THREAD

**Issue by Coachonko** [vlang/v#17754]
### Describe the bug

Trying to work with MySQL prepared statements without relying on the ORM. Lack of documentation and several bugs are making it impossible.

The content of `prep_state.v`
```v
module main

import db.mysql

fn main() {
	mut db_conn := mysql.Connection{
		host: "127.0.0.1"
		port: 3036
		username: 'prepStmtUsr'
		password: 'prepStmtPwd'
		dbname: 'prepStmtDb'
	}
	query := 'GET * FROM cities WHERE name = ?'
	city_name := "Ghent"

	mut stmt := db_conn.init_stmt(query)

	println(stmt.str())
}
```
Running with `v -cflags "-I/usr/include/mysql" run prep_state.v `, because of the bug reported as issue #14952

The following error is produced
```
7facbd66dbdf : at ???: RUNTIME ERROR: invalid memory access
/tmp/v_1000/prep_state.14746691520312832156.tmp.c:16551: by db__mysql__Connection_init_stmt
/tmp/v_1000/prep_state.14746691520312832156.tmp.c:16749: by main__main
/tmp/v_1000/prep_state.14746691520312832156.tmp.c:17238: by main
```

### Expected Behavior

A statement is initialized

### Current Behavior

RUNTIME ERROR: invalid memory access

### Reproduction Steps

1. Install V
2. Install mysql mysql-devel
3. Create a database in a Percona Server container
```sql
  A database is prepared in a Percona Server container:
  CREATE DATABASE prepStmtDb;
  CREATE USER 'prepStmtUsr'@'%' IDENTIFIED BY 'prepStmtPwd';
  GRANT ALL ON prepStmtDb.* TO 'prepStmtUsr'@'%' WITH GRANT OPTION;
  FLUSH PRIVILEGES;
  USE prepStmtDb;
  CREATE TABLE cities (
    id INT,
    name VARCHAR(255) NOT NULL,
    population INT NOT NULL,
    CONSTRAINT `PK_976eeb15-b32a-4428-ab6d-984b7d12aa16` PRIMARY KEY (id)
    );
  INSERT INTO cities (id, name, population) VALUES (0, 'Brussels', 190000);
  INSERT INTO cities (id, name, population) VALUES (1, 'Ghent', 260000);
  INSERT INTO cities (id, name, population) VALUES (2, 'Antwerp', 500000);
  EXIT;
  ```
4. Create `prep_state.v` with the content described above
5. Run the program as described above

### V version

bfb0932

### Environment details (OS name and version, etc.)

V full version: V 0.3.3 ee4150f.bfb0932
OS: linux, Linux version 5.14.0-162.18.1.el9_1.x86_64 (Alex@el9-tmp-x86) (gcc (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2), GNU ld version 2.35.2-24.el9) #1 SMP PREEMPT_DYNAMIC Wed Mar 1 15:55:09 UTC 2023
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz

getwd: /home/coachonko/Documents/projects/vlang
vexe: /home/coachonko/.local/lib64/v/v
vexe mtime: 2023-03-24 09:29:06

vroot: OK, value: /home/coachonko/.local/lib64/v
VMODULES: OK, value: /home/coachonko/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.31.1
Git vroot status: weekly.2023.12-20-gbfb09325
.git/config present: true

CC version: cc (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

### Update

This problem is not limited to init_stmt but it extends to other functions such as `query` and `real_query`

**Comment by walkingdevel** [comment]
Thanks for the bug found. Memory error is not a normal behavior, and it's a bug. But your code also has an error. `db_conn` is not connected to the database. After connecting, the error will disappear. Add `db_conn.connect()!` after connection initialization to get the following code:
```v
mut db_conn := mysql.Connection{
		host: "127.0.0.1"
		port: 3036
		username: 'prepStmtUsr'
		password: 'prepStmtPwd'
		dbname: 'prepStmtDb'
}
db_conn.connect()!
```



Also, you have an error in the SQL query. You should replace `GET` with `SELECT`.

**Comment by Coachonko** [comment]
> Add `db_conn.connect()!` after connection initialization

You are absolutely correct, thank you.
