### ISSUE TITLE
Error in Array compilation

### ISSUE THREAD

**Issue by anonx3247** [vlang/v#17787]
### Describe the bug

All of my code had been working fine, I had created an intermediary type:

```v

struct Tensor {
    data []f64
    len int
}
```

And decided to replace it directly with []f64s, the compiler now returns `error: cannot convert 'void *' to 'struct array'`

### Expected Behavior

For the code to compile

### Current Behavior

```
src/main.v:3:8: warning: module 'ai (src.ai)' is imported but never used
    1 | module main
    2 | 
    3 | import ai
      |        ~~
    4 | 
    5 | fn main() {
==================
/tmp/v_1000/AI.7046668324025237048.tmp.c:25543: error: cannot convert 'void *' to 'struct array'
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

### Reproduction Steps

You can get the code on my repository: https://github.com/neosapien3247/vai

The previous verison compiled without issue: ede4f523382600b6ea1a1005fff6210962683388

However it now no longer compiles

### V version

```bash v --version V 0.3.3 f08b882 ```

### Environment details (OS name and version, etc.)

OS: elementaryOS 7 on an x86_64 architecture

Built on Ubuntu 22.04.2 LTS
Linux 5.19.0-35-generic

**Comment by neosapien3247** [comment]
Okay, I was able to fix the error, I had kept a call to the parameter Tensor.data in a call to arrays.sum.

Replacing it with the name of the array directly solved the issue

**Comment by neosapien3247** [comment]
While the issue is resolved it is still bizarre that the compiler didn't throw an error when I try and access a non-existant field of an array. Throwing type conversion errors

**Comment by neosapien3247** [comment]
I'll reopen the issue for this reason

**Comment by felipensp** [comment]
Please, provide a proper test case for the case where you states it is a missing compiler check. Thanks.

**Comment by neosapien3247** [comment]
Okay, the error comes from a wrong cast:

```v
// test.vsh

import arrays

x := [1.0, 2.0, 3.0, 4.0]

println(arrays.sum[f64](x.data)!)
```

This, instead of returning an error about mismatched types between an []f64 and a voidptr (since the `data` field is a pointer to the array) It returns a `builder error` with a C compilation error:

```bash
==================
/tmp/v_1000/test.16293055329910315485.tmp.c:17714: error: cannot convert 'void *' to 'struct array'
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by neosapien3247** [comment]
Ive narrowed down the problem, the issue doesn't seem to be with the generics, rather it is simply a failure for checking the type of a `voidptr`:

```v
fn main() {
	c := voidptr(10)

	// println(sum[i32](c)!)
	println(test(c))
}

fn test(a []i32) i32 {
	return a[0]
}
```

returns:

```bash
/tmp/v_1000/hello.1476530331192383116.tmp.c:12475: error: cannot convert 'void *' to 'struct array'
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

what do you think could be causing this @felipensp ?

Looking at the definition of the array getter method and its corresponding C translation, I wonder if it might have to do with an implicit cast on the return line:

```v
//vlib/builtin/array.v:443
// Private function. Used to implement x = a[i] or { ... }
fn (a array) get_with_check(i int) voidptr {
	if i < 0 || i >= a.len {
		return 0
	}
	unsafe {
		return &u8(a.data) + u64(i) * u64(a.element_size) // <-- here
	}
}
```
```c
voidptr array_get(array a, int i) {
	#if !defined(CUSTOM_DEFINE_no_bounds_checking)
	{
		if (i < 0 || i >= a.len) {
			panic_debug(435, tos3("/home/neosapien/.local/bin/vlib/builtin/array.v"), tos3("builtin"), tos3("get"),   str_intp(3, _MOV((StrIntpData[]){{_SLIT("array.get: index out of range (i == "), /*100 &int*/0xfe07, {.d_i32 = i}}, {_SLIT(", a.len == "), /*100 &int*/0xfe07, {.d_i32 = a.len}}, {_SLIT(")"), 0, { .d_c = 0 }}})));
			VUNREACHABLE();
		}
	}
	#endif
	{ // Unsafe block
		return ((u8*)(a.data)) + ((u64)(i)) * ((u64)(a.element_size));
	}
	return 0;
}
```
