### ISSUE TITLE
Prevent taking address of `mut` argument data in safe code

### ISSUE THREAD

**Issue by ntrel** [vlang/v#178]
Allocating `var` on the heap if the variable-owning function uses `&var` works to ensure memory safety, you were right for #60. But not here:
```v
struct S1 {
mut:
	i int
}

//s param is mut so is passed by pointer
fn (mut s S1) f() &S1 {
	// &s gives the address of caller's s
	return &s
}

fn main() {
	mut p := &S1{} // just for init
	{
		mut s := S1{i: 4}
		p = s.f() //&s escapes but s is stack allocated
	}
	p.i++
	println(p.i) //garbage
}
```
* `return &s.i` also needs to be prevented.
* `&receiver` could be allowed in an `unsafe` block.
* I think `&immutable_receiver` is safe, because in that case the receiver is owned by the method, so it can be heap allocated (not tested).

**Comment by ntrel** [comment]
> return &s

The judge0 playground doesn't print garbage for me if the above line is `return s` - see #1071. But I still think something weird is happening here, it might work just by chance. Otherwise, how does V know to allocate the `mut s` line on the heap?

**Comment by crthpl** [comment]
is this fixed @ntrel

**Comment by ntrel** [comment]
@crthpl I've now updated the example for recent V - only minor changes. The bug still exists; the code causes an error:

> addrmut.v:10:9: error: cannot use `S1` as type `S1` in return argument

As I mentioned you can use `return s` to trigger the bug. I've now inspected the generated C, and the receiver is not being heap allocated, so this is a memory-safety problem.

**Comment by atorr0** [comment]
Hi,

Current version of V detects this error at compile time, with a clear message:

```
alejandro@hpnegro:/tmp/tmp.RI2HfApKUx
2021-05-08 20:09:26$ v version
V 0.2.2 cbf30bd
alejandro@hpnegro:/tmp/tmp.RI2HfApKUx
2021-05-08 20:09:27$ v example.v 
example.v:9:10: error: `s` cannot be referenced outside `unsafe` blocks as it might be stored on stack. Consider declaring `S1` as `[heap]`.
    7 | fn (mut s S1) f() &S1 {
    8 |     // &s gives the address of caller's s
    9 |     return &s
      |             ^
   10 | }
   11 |
```

**Comment by remimimimi** [comment]
Issue closed, because compiler now throws an error
