### ISSUE TITLE
Cannot compare type aliases obtained from C

### ISSUE THREAD

**Issue by qtc-de** [vlang/v#17819]
### Describe the bug

When a C function returns a typed aliased value (e.g. `C.NTSTATUS`, which is `int`) it cannot be compared to a non typed aliased value (e.g. `int` directly). Not sure whether this is a good description. The code below does probably explain it better.

### Expected Behavior

The mentioned code should compile.

### Current Behavior

```console
$ v example.v
example.v:7:7: error: infix expr: cannot use `int` (right expression) as `C.CUSTOM`
    5 |     success := 0
    6 |
    7 |     if C.get_custom() == success {
      |          ~~~~~~~~~~~~~~~~~~~~~~~
    8 |         println('Should work, or not?')
    9 |     }
```

### Reproduction Steps

1. Create the file `example.v` containing the following code:
```v
#flag -I c
#flag c/custom.o

fn main() {
	success := 0

	if C.get_custom() == success {
		println('Should work, or not?')
	}
}

fn C.get_custom() C.CUSTOM
```

2. Create the file `c/custom.c` containing the following code:
```c
typedef int CUSTOM;

CUSTOM get_custom()
{
    return 0;
}
```

3. Compile via `v example.v`

### Additional Information/Context

This is probably related to #17818

### V version

V full version: V 0.3.3 d60ceb4

### Environment details (OS name and version, etc.)

OS: linux, "Manjaro Linux" (VM)

**Comment by JalonSolov** [comment]
What command did you use to compile the C code?

**Comment by qtc-de** [comment]
I did not precompile it. According to the documentation v autocompiles the C code if the object file is not present.

**Comment by SurmanPP** [comment]
The error is misleading. You just have to cast it. Its also possible to replace the C.CUSTOM with int or similar.

**Comment by qtc-de** [comment]
Ah, good to know that casting works here. The error is indeed misleading.

I originally thought that casting should occur automatically here, because both side are actually the same type. However, now that I look at it again, I have a different view and think that the current behavior is correct :+1:
