### ISSUE TITLE
Issue with 'os.execvp' when there are spaces in path

### ISSUE THREAD

**Issue by Thybar** [vlang/v#17816]
V version: V 0.3.3 6b4fb0f
OS: windows 10 Pro 64-bit

When i run this command:
os.execvp('C:/Program Files (x86)/Mozilla Firefox/firefox.exe', [])!

 Firefox opens 3 tabs:
1 - "https://www.files.com"
2 - "https://www.(x86).com/Mozilla"
3 - "https://www.firefox.com/firefox.exe"

_Originally posted by @Thybar in https://github.com/vlang/v/issues/15866#issuecomment-1486884625_

**Comment by yuyi98** [comment]
？？？
What's the right result?

**Comment by Thybar** [comment]
I was expecting Firefox to open in a single tab with no url.
As with the command:
os.execute('C:/Program Files (x86)/Mozilla Firefox/firefox.exe')

**Comment by Dialga** [comment]
Duplicate of #15866.
