### ISSUE TITLE
V incorrectly auto-casts when an alias is used for voidptr

### ISSUE THREAD

**Issue by qtc-de** [vlang/v#17860]
### Describe the bug

When writing a lot of windows interop, it makes sense to define `type HANDLE = voidptr`. When calling a function that expects a `voidptr` (e.g. `fn example(arg voidptr)`) and passing the `HANDLE` type as argument, v auto-casts (or auto-references) the argument, which should not be correct.

### Expected Behavior

When passing the `HANDLE` type to a function that expects `voidptr`, v should leave the argument as it is.

### Current Behavior

v auto-references the `HANDLE` type and passes the address of the handle as argument to the function.

### Reproduction Steps

Here is some minimal v and c code to reproduce the issue:

**v code**:

```v
#flag -I /home/qtc/c
#flag /home/qtc/c/handle.o

type HANDLE = voidptr

fn example(arg voidptr) {
	println('Handle value in function is: ${arg}')
}

fn main() {
	handle := C.get_handle()

	println('Actual handle value is: ${handle}')
	println('Memory address of handle is: ${&handle}')

	example(handle)
}

fn C.get_handle() HANDLE
```

**c code**

```c
typedef void *HANDLE;

int var = 1;

HANDLE get_handle() {
    return &var;
}
```

Running this code yields:

```console
$ ./example
Actual handle value is: 676008
Memory address of handle is: 7ffc606d92e8
Handle value in function is: 7ffc606d92e8
```

### Possible Solution

The actual result should be:

```console
$ ./example
Actual handle value is: 676008
Memory address of handle is: 7ffc606d92e8
Handle value in function is: 676008
```

### V version

V 0.3.3 d60ceb4

### Environment details (OS name and version, etc.)

linux, "Manjaro Linux" (VM)

**Comment by trollkarlen** [comment]
It works if you change the function:
`fn example(arg voidptr) {`
to
`fn example(arg HANDLE) {`

But i agree both should work or at least the first should give error when compiling if not
