### ISSUE TITLE
`print` does not automatically apply .str()

### ISSUE THREAD

**Issue by avitkauskas** [vlang/v#1786]
**V version:** 
commit 52c2763ee33ba5d5707476e82829ec9b71e66587

**What did you do?**
`print(1)`

**What did you expect to see?**
1
 
**What did you see instead?**
test.v:1:7: Fn "print" wrong arg #1. Expected "string" (s)  but got "int"

**Comments**
`print(1.str())`
test.v:1:10: Fn "print" wrong arg #1. Expected "string" (s)  but got "f32"

```
a := 1
print(a)
```
test.v:2:8: Fn "print" wrong arg #1. Expected "string" (s)  but got "int"

```
a := 1
print(a.str())
```
1

**Comment by medvednikov** [comment]
Fixed.
