### ISSUE TITLE
the checker allows for `a, b := abc()` where `fn abc() ?(int,int)`, but it should require the `none` to be handled instead

### ISSUE THREAD

**Issue by blackshirt** [vlang/v#17874]
### Describe the bug

There are some situation where `Option` type does not handled correctly,  When some function (methods) returns `Option` type and called without proper error propagation, its result in `C error` compiler bug.

### Expected Behavior

error propagation should be handled correctly, similar to `Result` type ..minimal looks like this >
```
code.v:9:10: error: abc() returns an option, so it should have either an `or {}` block, or `?` at the end
    7 | 
    8 | fn main() {
    9 |     a, b := abc(10)
      |             ~~~~~~~
   10 |     dump(a)
   11 |     dump(b)
Exited with error status 1
```

### Current Behavior

```
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

Exited with error status 1
```

### Reproduction Steps

Use this snippet :
```
fn abc(n int) ?(int,int) {
    if n == 5 {
        return 5, 10
    }
    return none
}

fn main() {
    // call function without propagate the error
    a, b := abc(10)
    dump(a)
    dump(b)
}
```

### Possible Solution

I dont know exactly, but, maybe in syntax checker

### V version

```V 0.3.3 6756d28```

### Environment details (OS name and version, etc.)

```
V full version: V 0.3.3 6756d28
OS: linux, Ubuntu 20.04.5 LTS (VM)
Processor: 2 cpus, 64bit, little endian, Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz

getwd: /workspaces/asn1
vexe: /home/codespace/v/v
vexe mtime: 2023-03-29 02:16:58

vroot: OK, value: /home/codespace/v
VMODULES: OK, value: /home/codespace/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.40.0
Git vroot status: weekly.2023.13-9-g6756d285 (35 commit(s) behind V master)
.git/config present: true

CC version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

**Comment by spytheman** [comment]
The current behavior of the sample is to print:
```v
[a.v:11] a: 0
[a.v:12] b: 0
```
which is still wrong, since the `none` was magically transformed into 2 zeros...

It should have been a checker error to call `abc()` without a `?` or an or block.

**Comment by ChAoSUnItY** [comment]
The latest commit seems would not cause c gen error. Instead, the compilation would succeed and print out 0s.

**Comment by steven-mathew** [comment]
Hey, I'd like to take on this issue!
