### ISSUE TITLE
v install glfw on ubuntu does not work

### ISSUE THREAD

**Issue by resch512** [vlang/v#1788]
**V version:** 0.1.18
**OS:** Ubuntu

**What did you do?**
v install glfw

**What did you expect to see?**
successful install of glfw
 
**What did you see instead?**
V error: /home/andreas/v/thirdparty/cJSON/cJSON.o not found, building it...

/home/andreas/v/tools/vget.tmp.c:151:10: fatal error: openssl/ssl.h: Datei oder Verzeichnis nicht gefunden
 #include <openssl/ssl.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by Danil-Lapirow** [comment]
Try installing `libssl-dev`
`sudo apt install libssl-dev -y`

**Comment by medvednikov** [comment]
Indeed, you need openssl, it's mentioned in the docs.
