### ISSUE TITLE
wrong error given when deferencing/mutability a const pointer in `unsafe`

### ISSUE THREAD

**Issue by Delta456** [vlang/v#17919]
### Describe the bug

A wrong error is given when dereferencing/mutating a const pointer inside `unsafe` 

### Expected Behavior

No error. Code compiling as expected.

### Current Behavior

```
code.v:7:3: error: `x` is immutable, declare it with `mut` to make it mutable
    5 | unsafe {
    6 |     x := &ctx_ptr
    7 |     *x = &Context{}
      |      ^
    8 |     _ = x
    9 | }
```

### Reproduction Steps

Write a V program with the given code:

```v
struct Context {}

const ctx_ptr = &Context(unsafe { nil })

unsafe {
	x := &ctx_ptr
	*x = &Context{}
	_ = x
}

```

### Additional Information/Context

Changing `const ctx_ptr = &Context(unsafe { nil })` to `const ctx_ptr = &Context(0)` makes the code compile.

### V version

Latest

### Environment details (OS name and version, etc.)

Windows 11 WSL 2

**Comment by medvednikov** [comment]
I've fixed it, will push once tests pass.

**Comment by medvednikov** [comment]
Fixed.
