### ISSUE TITLE
https://github.com/vlang/v/tree/master/examples/vweb_fullstack won't compile

### ISSUE THREAD

**Issue by kpeters58** [vlang/v#17921]
### Describe the bug

https://github.com/vlang/v/tree/master/examples/vweb_fullstack does not compile, but runs into errors.

### Expected Behavior

To be able to cleanly compile and run the example.

### Current Behavior

user_services.v:47:5: error: invalid expression: unexpected keyword `return`
   45 |     }!
   46 |
   47 |     return results
      |     ~~~~~~
   48 | }

user_services.v:64:5: error: invalid expression: unexpected keyword `return`
   62 |     }!
   63 |
   64 |     return results.first()
      |     ~~~~~~
   65 | }

user_services.v:64:20: error: unknown method or field: `User.first`
   62 |     } // ! kp
   63 |
   64 |     return results.first()

   

### Reproduction Steps

Just compile with 'v . '

### V version

0.3.2

### Environment details (OS name and version, etc.)

Windows 11 Pro

**Comment by JalonSolov** [comment]
You need to update your V.  It compiles fine with the latest.
```
[jalon@7950x vweb_fullstack]$ v version
V 0.3.3 88f89bd
[jalon@7950x vweb_fullstack]$ v .
[jalon@7950x vweb_fullstack]$ 
```
Try `v up`.  If that doesn't work (doesn't always, on Windows), then `git pull` followed by `./make.bat`.

**Comment by kpeters58** [comment]
Thanks - that was it
