### ISSUE TITLE
Can't build V from source on windows 7

### ISSUE THREAD

**Issue by Grabli66** [vlang/v#1792]
Building V
git version 2.14.1.windows.1
Attempting to bootstrap with MSVC
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.11
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27030.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

v_win.c
vc\v_win.c(1918): error C2059: syntax error: '}'
vc\v_win.c(2179): error C2059: syntax error: '}'
vc\v_win.c(2261): error C2059: syntax error: '}'
vc\v_win.c(2317): error C2059: syntax error: '}'
vc\v_win.c(2738): error C2059: syntax error: '}'
vc\v_win.c(3388): error C2059: syntax error: '}'
vc\v_win.c(4687): error C2059: syntax error: '}'
vc\v_win.c(4818): error C2059: syntax error: '}'
vc\v_win.c(4907): error C2059: syntax error: '}'
vc\v_win.c(5419): error C2059: syntax error: '}'
vc\v_win.c(5853): error C2059: syntax error: '}'
vc\v_win.c(5860): error C2059: syntax error: '}'
vc\v_win.c(5963): error C2059: syntax error: '}'
vc\v_win.c(6224): error C2059: syntax error: '}'
vc\v_win.c(8264): error C2059: syntax error: '}'
vc\v_win.c(8292): error C2059: syntax error: '}'
vc\v_win.c(8494): error C2059: syntax error: '}'
vc\v_win.c(8496): error C2059: syntax error: '}'
vc\v_win.c(9219): error C2059: syntax error: '}'
vc\v_win.c(11005): error C2059: syntax error: '}'
vc\v_win.c(11719): error C2059: syntax error: '}'
vc\v_win.c(11813): error C2059: syntax error: '}'
vc\v_win.c(12269): error C2059: syntax error: '}'
vc\v_win.c(12336): error C2059: syntax error: '}'
vc\v_win.c(12604): error C2059: syntax error: '}'
vc\v_win.c(12769): error C2059: syntax error: '}'
vc\v_win.c(13226): error C2059: syntax error: '}'
vc\v_win.c(13232): error C2059: syntax error: '}'
vc\v_win.c(13246): error C2059: syntax error: '}'
vc\v_win.c(14278): error C2059: syntax error: '}'
vc\v_win.c(14459): error C2059: syntax error: '}'
vc\v_win.c(17474): error C2059: syntax error: '}'
vc\v_win.c(17459): fatal error C1054: compiler limit: initializers nested too deeply
cl.exe failed to build V
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error

**Comment by joe-conigliaro** [comment]
Ooos

**Comment by joe-conigliaro** [comment]
This has been fixed
