### ISSUE TITLE
Serial port support

### ISSUE THREAD

**Issue by Grabli66** [vlang/v#1793]

**Comment by medvednikov** [comment]
Please provide more details when requesting a feature.

Explain what it is and why you'd like to have it implemented.

**Comment by Grabli66** [comment]
https://en.wikipedia.org/wiki/Serial_port

I am talking about something like this https://gowalker.org/github.com/bugst/go-serial
But builtin in vlang standard library.
I think serial port support is a must have for developing embedded devices. 
It seems to me that vlang can be a good language for embedded devices.

**Comment by medvednikov** [comment]
This sounds important and easy to implement, especially once the Go => V translator is out.

But I think it should be a separate library, not part of vlib.

**Comment by erdetn** [comment]
@Grabli66 hope you've managed to write/get a serial library in V.
But, just in case, here you have a tiny wrapper written in V and tested on Ubuntu. This is still in progress, and more features and supports need to add.
https://github.com/erdetn/vasyncserial
