### ISSUE TITLE
`re.matches_string` returning incorrect results

### ISSUE THREAD

**Issue by xiusin** [vlang/v#17934]
### Describe the bug

```v
import regex
pattern := 'watch'
mut re := regex.regex_opt('${pattern}') or { panic(err) }

str := '/xxx/vvvv/ddd/watch/dddd/000'


println(re.find_all_str(str)) // ['watch']
println(re.matches_string(str)) // false

```

### Expected Behavior

Obtaining the correct results

### Current Behavior

<img width="867" alt="image" src="https://user-images.githubusercontent.com/36065131/231096095-9570964c-17e7-46d0-9f0d-2df9010558a0.png">

### Reproduction Steps

none

### V version

V 0.3.3 6b4fb0f

### Environment details (OS name and version, etc.)

macos

**Comment by yuyi98** [comment]
I think that the result `false` is right.

**Comment by xiusin** [comment]
@yuyi98 

```v
pub fn (re &RE) matches_string(in_txt string) bool {
	start, _ := re.match_string(in_txt)
	return start != no_match_found
}
```

这不是检查字符串是否匹配的吗，还是我理解有错？
Isn't this a check to see if the string matches?

**Comment by tobealive** [comment]
Hey @xiusin,

It works correctly as far as I can say.
The regex pattern you use just isn't right.

```v
import regex

pattern := '.*(watch).*'
mut re := regex.regex_opt(pattern) or { panic(err) }

str := '/xxx/vvvv/ddd/watch/dddd/000'

println(re.find_all_str(str)) // ['watch']
println(re.matches_string(str)) // true
```

**Comment by xiusin** [comment]
@tobealive Why is it necessary to have wildcards, when it should be OK to have no wildcards? So let me close this issue

**Comment by tobealive** [comment]
It's due to that it's not PCRE. We have the pcre module though :+1: .
