### ISSUE TITLE
TEMPLATES.md missing

### ISSUE THREAD

**Issue by kpeters58** [vlang/v#17961]
### Describe the issue

https://modules.vlang.io/vweb.html
contains a link to 
https://modules.vlang.io/vlib/v/TEMPLATES.md which is missing

### Links

https://modules.vlang.io/vlib/v/TEMPLATES.md

**Comment by JalonSolov** [comment]
It's not missing.  The link is set to work if you open the README.md file in the `vlib/vweb` subdir, and it is not being adjusted on the web site.

`v doc` would need a lot more work to make that adjustment.
