### ISSUE TITLE
`v` package manager Advice

### ISSUE THREAD

**Issue by d1y** [vlang/v#1796]
Hi.

current PM(package manger) is Centralized
but.
![image](https://user-images.githubusercontent.com/45585937/64020620-aa8c4b80-cb64-11e9-8cdb-ad69f2d10e40.png)
Can it be decentralized?
just like it Go

```go
import 'https://github.com/vlang/v'

fn main() {
  pirntln('decentralized')
}
```

**Comment by spytheman** [comment]
What should this do?
git clone the given repo at master branch each time the program is compiled?

**Comment by nedpals** [comment]
shamelessly plug my project here but if you want a decentralized alternative then i suggest to use vpkg or other alternatives.

https://github.com/v-pkg/vpkg

**Comment by d1y** [comment]
> shamelessly plug my project here but if you want a decentralized alternative then i suggest to use vpkg or other alternatives.
> 
> [v-pkg/vpkg](https://github.com/v-pkg/vpkg)

Awesome

**Comment by medvednikov** [comment]
VPM was just brought back.

A good package manager needs versioning, so this data has to be stored somewhere.

Go's dependency management is not the strongest point of the language.

**Comment by KeyWeeUsr** [comment]
@medvednikov Will you open-source the VPM code? It'd be nice to have an option for creating an instance of the package repository/index/nexus in a private network which is not allowed to communicate with the Internet. I'm considering v-pkg for that, however I'm not sure how compatible it'll be in the long run.

Perhaps there's something in common with v-pkg so these codebases could be joined in the long run?

**Comment by medvednikov** [comment]
@KeyWeeUsr yes, in November.
