### ISSUE TITLE
Have match expression as the only conditional?

### ISSUE THREAD

**Issue by Skeepo** [vlang/v#1797]
V is simple. V only has one looping construct, "for", so I was wondering if it could be reasonable to only have one conditional construct. In #1677 @gslicer suggested to drop the match-statement, which I disagree with, but it got me thinking if it would be reasonable to only have one conditional construct. It would be interesting to explore the possibility of only having the match-statement. I know this is quite radical but hear me out.

Instead of this
```V
if a <= b { 
  println('$a <= $b') 
} 
```
You could just do
```V
match a <= b {
  true => println('$a <= $b')
}
```

Instead of this
```V
if a <= b { 
  println('$a <= $b') 
} else {
  println('$a > $b') 
}
```
You could just do
```V
match a <= b {
  true => println('$a <= $b')
  false => println('$a > $b')
}
```
Instead of this
```V
if a < b { 
  println('$a < $b') 
} else if a > b { 
  println('$a > $b') 
} else { 
  println('$a == $b') 
}
```
You could just do
```V
match a < b {
  true => println('$a < $b')
} else match a > b {
  true => println('$a > $b') 
  false =>  println('$a == $b') 
}
```

If the match expression got some minor syntax improvements, I don't see why we would need an if-statement. match looks much nicer to me and is more versatile?

**Comment by gslicer** [comment]
> ```v
> match a <= b {
>    true => println('$a <= $b')
> }
> ```

This is the perfect example why I personally prefer "if" instead if "match" in the current state, => looks to much as an binary operator - but strongly agree, one conditional construct shall be enough.

See also the previous discussion about "match": https://github.com/vlang/v/issues/1677#issuecomment-526079567

**Comment by Skeepo** [comment]
I agree that colon might be better than the fat-arrow, but your example does not show a good alternative to if-elseif, because it requires a lot of nesting.

**Comment by Delta456** [comment]
@Skeepo what's your idea for nesting conditions?

**Comment by Skeepo** [comment]
@Delta456 something like this
```V
match a < b {
  true => println('$a < $b')
} else match a > b {
  true => println('$a > $b') 
  false =>  println('$a == $b') 
}
```
But I do believe that more elegant solutions might exist.

**Comment by Delta456** [comment]
```go
match a % 2 == 0 {
  true => match a > 21{
    println('$a')
} 
  false => println('Value not valid')
```
This is my approach but its seems very complex to me so I think `if-else if` and `else` are better because it would be more readable in my opinion and people coming from other languages won't take much time to adapt.

**Comment by gslicer** [comment]
I believe at some point it was agreed to nest the "right" part anyway by {..}, so my example would rather look like:

```
match a < b {
     true : { println('$a < $b') }
    false : { match a > b {
               true : { println('$a > $b') }
              false : { println('$a == $b') }
             } }
}
```
Usage of "else" might be conflicting with the optional "_" (which is also a kind of "else" in the first match clause).

**Comment by gslicer** [comment]
Let my try tp put @Delta456 's example to "if" construct:
 
```
if a % 2 == 0 {
    if a > 21{ println('$a is even and greater than 21.')
        else println('$a is even only.') }
} else println('Value not valid')
```

Looks even better to me...

**Comment by medvednikov** [comment]
Simplicity doesn't always mean having as little syntax as possible.

100% of developers use `if` statements every day, they are simple and clear. I see no point in removing them.

**Comment by Skeepo** [comment]
@Delta456 and @gslicer both of your examples require nesting. For long "if-else if" statements those would not be a good alternatives, because they would be incredibly nested.

**Comment by Delta456** [comment]
@Skeepo Yeah which will make the code more complex. I think current `if-else if` statements are just fine.
