### ISSUE TITLE
print does not automatically apply str() to struct instances in array

### ISSUE THREAD

**Issue by lobotony** [vlang/v#1798]
**V version:** 0.1.18
**OS:** MacOS 10.14.6

**What did you do?**

	struct Testy {
		a int
	}

	fn main() {
		a := []Testy
		println(a.str())
	}

**What did you expect to see?**

    []

 
**What did you see instead?**

    cant print Testy[], unhandled print of Testy

**Comment by nedpals** [comment]
Closed. Arrays are now handled when printed. 
```
struct Testy {
	a int
}

fn main() {
    a := []Testy{}
	println(a.str())
}
```
```
[]
```
