### ISSUE TITLE
 Standard libraries have dynamic library dependencies? 

### ISSUE THREAD

**Issue by cjmxp** [vlang/v#180]
./tetris
dyld: Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
Referenced from: ~/vlang/./tetris
Reason: image not found
Abort trap: 6

**Comment by medvednikov** [comment]
Right.

Dependencies like glfw and libcurl will be removed in the future. `libfreetype` will be translated to V and compiled statically.

**Comment by medvednikov** [comment]
For now to run tetris you have to install the deps.

macOS:

`brew install glfw freetype`

Ubuntu:

`sudo apt install glfw libglfw3-dev libfreetype6-dev`

**Comment by cjmxp** [comment]
Open source as soon as possible. I feel there is still a lot to be done. Version 1.0 is expected to take a long time.

**Comment by medvednikov** [comment]
It will be open sourced in June.

The language is small, I don't expect 1.0 to take a very long time.
