### ISSUE TITLE
Will not compiler on WIndows

### ISSUE THREAD

**Issue by l8atnight** [vlang/v#1800]
**V version:** 
current
**OS:** 
win 64
**What did you do?**
update fom git to compiler the compiler

**What did you expect to see?**

 
**What did you see instead?**
F:\v>updategit == 

> git pull origin master
> make
> v -o v1 compiler
> del v.exe
> ren v1.exe v.exe
> 

F:\v>git pull origin master
From https://github.com/vlang/v
 * branch            master     -> FETCH_HEAD
Already up to date.

F:\v>make
Building V
git version 2.22.0.windows.1
Attempting to bootstrap with MSVC
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.1.4
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
Line is too long.
Syntaxerror.

**Comment by medvednikov** [comment]
Can you try again @l8atnight

**Comment by l8atnight** [comment]
F:\v>git pull origin master
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Total 40 (delta 30), reused 30 (delta 30), pack-reused 10
Unpacking objects: 100% (40/40), done.
From https://github.com/vlang/v
 * branch            master     -> FETCH_HEAD
   dae4c4b..72363ad  master     -> origin/master
Updating dae4c4b..72363ad
Fast-forward
 .gitattributes                          |   1 +
 compiler/cgen.v                         |  11 ++--
 compiler/cheaders.v                     |   1 -
 compiler/main.v                         |   2 +-
 compiler/msvc.v                         |   7 ++-
 compiler/parser.v                       |  53 ++++++++--------
 compiler/table.v                        |   2 +
 compiler/tests/repl/chained_fields.repl |  78 ++++++++++++++++++++++++
 vlib/builtin/array.v                    |  44 ++++++-------
 vlib/builtin/array_test.v               |   1 +
 vlib/freetype/freetype.v                |   5 +-
 vlib/readline/readline_lin.v            | 105 ++++++++++++++++++++++++++++++++
 vlib/vweb/vweb.v                        |   1 +
 13 files changed, 253 insertions(+), 58 deletions(-)
 create mode 100644 .gitattributes
 create mode 100644 compiler/tests/repl/chained_fields.repl
 create mode 100644 vlib/readline/readline_lin.v

F:\v>make
Building V
git version 2.22.0.windows.1
Attempting to bootstrap with MSVC
line too long.
Syntaxerror.

**Comment by l8atnight** [comment]
F:\v>git pull origin master
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 3), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (7/7), done.
From https://github.com/vlang/v
 * branch            master     -> FETCH_HEAD
   72363ad..b6ecbd8  master     -> origin/master
Updating 72363ad..b6ecbd8
Fast-forward
 compiler/parser.v | 10 +++++-----
 make.bat          |  6 +++---
 2 files changed, 8 insertions(+), 8 deletions(-)

F:\v>make
Building V
git version 2.22.0.windows.1
Attempting to bootstrap with MSVC
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.1.4
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
Microsoft (R) C/C++-Optimierungscompiler Version 19.21.27702.2 für x64
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

v_win.c
vc\v_win.c(3): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "inttypes.h": No such file or directory
cl.exe failed to build V
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error

**Comment by l8atnight** [comment]
F:\v>make -gcc
Building V
git version 2.22.0.windows.1
attempting to bootstrap with GCC
Der Befehl "where" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Attempting to bootstrap with MSVC
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.1.4
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
Microsoft (R) C/C++-Optimierungscompiler Version 19.21.27702.2 für x64
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

v_win.c
vc\v_win.c(3): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "inttypes.h": No such file or directory
cl.exe failed to build V
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error

**Comment by medvednikov** [comment]
Should be fixed now, can you try again please?

**Comment by l8atnight** [comment]
unfortunately not:

F:\v>git pull origin master
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/vlang/v
 * branch            master     -> FETCH_HEAD
   24fdefe..847b43f  master     -> origin/master
Updating 24fdefe..847b43f
Fast-forward
 make.bat | 15 ++++++++-------
 1 file changed, 8 insertions(+), 7 deletions(-)

F:\v>make
Building V
git version 2.22.0.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Der Befehl "where" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Attempting to build v.c  with MSVC...
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.1.4
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
Microsoft (R) C/C++-Optimierungscompiler Version 19.21.27702.2 für x64
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

v_win.c
vc\v_win.c(3): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "inttypes.h": No such file or directory
cl.exe failed to build V
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error

F:\v>make -gcc
Building V
git version 2.22.0.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Der Befehl "where" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Attempting to build v.c  with MSVC...
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.1.4
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
Microsoft (R) C/C++-Optimierungscompiler Version 19.21.27702.2 für x64
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

v_win.c
vc\v_win.c(3): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "inttypes.h": No such file or directory
cl.exe failed to build V
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error

**Comment by medvednikov** [comment]
All right, I fixed the GCC build, but there's an issue with MSVC. Will fix a bit later today.

**Comment by l8atnight** [comment]
Great!

**Comment by l8atnight** [comment]
F:\v>git pull origin master
remote: Enumerating objects: 85, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 59 (delta 50), reused 47 (delta 38), pack-reused 0
Unpacking objects: 100% (59/59), done.
From https://github.com/vlang/v
 * branch            master     -> FETCH_HEAD
   fe3639d..89924c2  master     -> origin/master
Updating fe3639d..89924c2
Fast-forward
 README.md                   |  27 +++-----
 compiler/cgen.v             |  26 ++++++--
 compiler/fn.v               |   6 +-
 compiler/jsgen.v            |   4 +-
 compiler/main.v             |   8 +--
 compiler/modules.v          |  34 +++++-----
 compiler/parser.v           |  30 +++++++--
 compiler/scanner.v          |   2 +-
 compiler/table.v            | 155 ++++++++++----------------------------------
 september.plan              |   5 +-
 vlib/builtin/array.v        |  14 ++++
 vlib/builtin/int.v          |   2 +
 vlib/builtin/int_test.v     |  20 +++---
 vlib/builtin/map.v          |  10 +--
 vlib/builtin/map_test.v     |   8 ---
 vlib/builtin/string.v       |  11 ++--
 vlib/json/json_primitives.v |  23 ++-----
 vlib/os/os.v                |   8 +--
 vlib/time/time.v            |   2 +-
 19 files changed, 162 insertions(+), 233 deletions(-)

F:\v>make
Building V
git version 2.22.0.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Der Befehl "where" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Attempting to build v.c  with MSVC...
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.1.4
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
Microsoft (R) C/C++-Optimierungscompiler Version 19.21.27702.2 für x64
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

v_win.c
vc\v_win.c(3): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "inttypes.h": No such file or directory
cl.exe failed to build V
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error

**Comment by l8atnight** [comment]
F:\v>make -gcc
Building V
git version 2.22.0.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Der Befehl "where" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Attempting to build v.c  with MSVC...
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.1.4
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
Microsoft (R) C/C++-Optimierungscompiler Version 19.21.27702.2 für x64
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

v_win.c
vc\v_win.c(3): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "inttypes.h": No such file or directory
cl.exe failed to build V
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error

F:\v>

**Comment by vitalyster** [comment]
Looks like you did not have Windows SDK component installed

**Comment by l8atnight** [comment]
Is installed, along with VS community ed.

**Comment by l8atnight** [comment]
Still same error

Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!

**Comment by structure-charger** [comment]
I had compile v with vs2017 msvc cl successfully, command is  make.bat -msvc , but the  vs2017 termainal exit without any warning, and v.exe compile may be  successful in some part, because there is many errors accured when I run the examples. This is a big improvement, but we have to fix more.
(hello world,json,rune is OK.)
(nbody.v run successful, but the process not exit after 10 minutes, I manually kill it.)
here are the errors(SOME IN CHINESE):
tetris:
./v.exe run examples/tetris/tetris.v
D:\msys2\opt\project\v/thirdparty/glad/glad.o not found, building it...

D:\msys2\opt\project\v\examples\tetris\tetris.tmp.c:131:10: 致命错误：ft2build.h：No such file or directory
 #include "ft2build.h"
          ^~~~~~~~~~~~
编译中断。
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

log.v
./v.exe run examples/log.v
D:\msys2\opt\project\v\examples\log.tmp.c: 在函数‘os__dir_exists’中:
D:\msys2\opt\project\v\examples\log.tmp.c:5184:15: 错误：‘INVALID_FILE_ATTRIBUTES’未声明(在此函数内第一次使用)
  if ( attr == INVALID_FILE_ATTRIBUTES )...
(Use `v -debug` to print the entire error message)

V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
terminal_control
 ./v.exe run examples/terminal_control.v
D:\msys2\opt\project\v\examples\terminal_control.tmp.c: 在函数‘os__dir_exists’中:
D:\msys2\opt\project\v\examples\terminal_control.tmp.c:5108:15: 错误：‘INVALID_FILE_ATTRIBUTES’未声明(在此函数内第一次使用)
  if ( attr ==...
(Use `v -debug` to print the entire error message)

V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by l8atnight** [comment]
not solved

**Comment by joe-conigliaro** [comment]
It could be a problem with include paths on vs 2015 or maybe for some reason the file is missing from your system.

Could you please verify that inttypes.h exists in this directory: `C:\Program Files (x86)\Windows Kits\10\Include\#version#\ucrt`. I'm not sure what version will be on your system.

**Comment by joe-conigliaro** [comment]
Continued here: https://github.com/vlang/v/issues/1891
