### ISSUE TITLE
Readline module

### ISSUE THREAD

**Issue by Henrixounez** [vlang/v#1801]
Here is a todolist of features for the Readline module.
New features to be added are welcomed and i'm open to discuss here, or on the official Discord.

**Linux (*Macos ?*) :**
- [x] Raw mode switch
- [x] Reading characters
- [x] Reading simple line
- [x] Supporting multiline wrapping for deleting and moving cursor
- [x] Deleting chracters
- [x] Deleting characters right of cursor (Suppr key)
- [x] Moving cursor
- [x] Detecting end of string characters
- [x] Moving cursor to start or end of line (CTRL+A, CTRL+E)
- [x] Moving cursor from word to word (CTRL+LEFT, CTRL+RIGHT)
- [x] Adding new characters mid-line
- [x] Clear screen
- [x] Overwrite
- [x] History
- [ ] Reverse search in History with Ctrl-R and typing a partial match. A second Ctrl-R when already in reverse search mode, should seek to the next matching line from the history. Basically do what readline does.
- [ ] Key bindings (To list)
- [x] Displaying a prompt
- [ ] Deleting word by word (Alt + Backspace)
- [x] Unicode handling
- [x] Suspend (Ctrl + Z)

**If someone can make a windows version, it would be much appreciated**
**Windows :**
/

**How to use it :**
```
import readline
mut rl := readline.Readline{}
rl.enable_raw_mode()
for rl.read_line('') != '' {}
rl.disable_raw_mode()
```

**Comment by dumblob** [comment]
I'd advocate for adding `vi` mode emulation (see https://github.com/antirez/linenoise/pull/92/files ).
