### ISSUE TITLE
Powered by Doki Link points to a 404 Page in VOSCA docs.

### ISSUE THREAD

**Issue by omegaui** [vlang/v#18060]
### Describe the issue

![image](https://user-images.githubusercontent.com/73544069/234543956-a475b1c7-74ac-4861-823b-d5a1cd913f17.png)

Clicking on the **[Doki](https://github.com/vlang-association/doki)** anchor points to a 404 page of GitHub.

![image](https://user-images.githubusercontent.com/73544069/234544207-879b0455-7143-46a0-8320-d1c04f091419.png)

### Links

[VOSCA Dev Module Docs](https://modules.vosca.dev/)

**Comment by i582** [comment]
Hi
Thanks for the report, it's known, Doki hasn't been released yet.

**Comment by i582** [comment]
If there are any problems with the documentation, it is better to create an issue here: https://github.com/vlang-association/docs
