### ISSUE TITLE
cgen: `$if field.indirections == 1 {` not work as expected

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#18064]
### Describe the bug

In the `vlib/v/tests/comptime_field_indirections_test.v` the test pass. But, it is because the comptime `$if {} $else {}` is, probably generating a empty `$if` inside `if`.

So, I write a new test that catch this case in the **Reproduction Steps** section.

### Expected Behavior

test pass

### Current Behavior

test fail

### Reproduction Steps

```v
struct Encoder {}

struct Writer {}

struct StructType[T] {
mut:
	val  &T
	val2 T
}

fn (e &Encoder) encode_struct[U](val U, mut wr Writer) ![]string {
	mut response := []string{}
	$for field in U.fields {
		if field.indirections == 1 {
			value := val.$(field.name)
			assert field.indirections == 1
			$if field.indirections == 1 {
				response << field.name
				assert *value == 'ads'
			} $else {
				response << 'not'
				assert false
			}
		} else {
			response << field.name
			assert field.name == 'val2'
		}
	}
	return response
}

fn test_indirection_checking() {
	e := Encoder{}
	mut sb := Writer{}
	mut string_pointer := 'ads'
	assert e.encode_struct(StructType[string]{ val: &string_pointer }, mut sb)! == ['val', 'val2']
}
```

### V version

latest

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by felipensp** [comment]
This was already spotted and fixed by PR #18043. Thanks.
