### ISSUE TITLE
V build Error

### ISSUE THREAD

**Issue by RNU4** [vlang/v#1810]
@emily33901
**V version:** 
Newest
**OS:** 
Windows 10
**What did you do?**
git clone https://github.com/vlang/v
cd v
make

**What did you expect to see?**
V installed
 
**What did you see instead?**

Building V
git version 2.21.0.windows.1
Attempting to bootstrap with MSVC
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.8.8
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26732.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

v_win.c
vc\v_win.c(3): fatal error C1083: Cannot open include file: 'inttypes.h': No such file or directory
cl.exe failed to build V
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error

**Comment by coderkk** [comment]
do you try ```make -gcc``` . Current make default to msvc.

**Comment by RNU4** [comment]
When I do that I get this error:

Building V
git version 2.21.0.windows.1
attempting to bootstrap with GCC
In file included from vc\v_win.c:6:
vc\v_win.c: In function 'os__get_file_handle':
vc\v_win.c:5000:34: error: request for member '_file' in something not a structure or union
   void *_handle = _get_osfhandle(_fileno(_fd));
                                  ^~~~~~~
vc\v_win.c: In function 'init_consts':
vc\v_win.c:21138:29: error: '_O_U8TEXT' undeclared (first use in this function); did you mean 'O_TEXT'?
   _setmode(_fileno(stdout), _O_U8TEXT);
                             ^~~~~~~~~
                             O_TEXT
vc\v_win.c:21138:29: note: each undeclared identifier is reported only once for each function it appears in
gcc failed to compile - Create an issue at 'https://github.com/vlang'

**Comment by l8atnight** [comment]
F:\v>make -gcc
Building V
git version 2.22.0.windows.1
attempting to bootstrap with GCC
Der Befehl "where" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Attempting to bootstrap with MSVC
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.1.4
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
Microsoft (R) C/C++-Optimierungscompiler Version 19.21.27702.2 für x64
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

v_win.c
vc\v_win.c(3): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "inttypes.h": No such file or directory
cl.exe failed to build V
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error

**Comment by medvednikov** [comment]
Should be fixed now, can you try again please?

**Comment by RNU4** [comment]
Was on vacation, so sorry for the late response.
When i do 
git clone https://github.com/vlang/v
cd v
make
i get this error
In file included from vc\v_win.c:6:
vc\v_win.c: In function 'os__get_file_handle':
vc\v_win.c:4966:34: error: request for member '_file' in something not a structure or union
   void *_handle = _get_osfhandle(_fileno(_fd));
                                  ^~~~~~~
vc\v_win.c: In function 'init_consts':
vc\v_win.c:21606:29: error: '_O_U8TEXT' undeclared (first use in this function); did you mean 'O_TEXT'?
   _setmode(_fileno(stdout), _O_U8TEXT);
                             ^~~~~~~~~
                             O_TEXT
vc\v_win.c:21606:29: note: each undeclared identifier is reported only once for each function it appears in
gcc failed to compile - Create an issue at 'https://github.com/vlang'

**Comment by joe-conigliaro** [comment]
@RNU4 Can you take a look at these two issues:
- https://github.com/vlang/v/issues/1891
- https://github.com/vlang/v/issues/1895
I think one of these should help
