### ISSUE TITLE
No error when passing `shared` object as `mut` in a closure

### ISSUE THREAD

**Issue by Casper64** [vlang/v#18122]
### Describe the bug

When passing a `shared` object to a closure and marking it as `mut` the program runs and no compiler error is thrown.

`v fmt` also converts `shared` to `mut` in closures

### Expected Behavior

I expect to see an error that a shared objects have to be marked as shared in the closure.

### Current Behavior

The code works and no error is thrown. V correctly treats `foo` in the closure as a shared variable and the generated C code verifies this.

```c
// V anon functions:
/*F*/
struct _V_anon_fn_d9036e6bb51bf2e1__98_Ctx {
	__shared__main__Foo* foo;
};

VV_LOCAL_SYMBOL void anon_fn_d9036e6bb51bf2e1__98(void) {
	struct _V_anon_fn_d9036e6bb51bf2e1__98_Ctx* _V_closure_ctx = __CLOSURE_GET_DATA();
	sync__RwMutex_lock(&_V_closure_ctx->foo->mtx);
	/*lock*/ {
		_V_closure_ctx->foo->val.name = _SLIT("hello");
	}
	sync__RwMutex_unlock(&_V_closure_ctx->foo->mtx);;
}
```

### Reproduction Steps

```v
module main

struct Foo {
mut:
	name string
}

fn main() {
	shared foo := Foo{}

	// if you change `mut` to `shared` and run `v fmt`  `shared` gets changed to `mut`
	fn [mut foo] () {
		lock foo {
			foo.name = 'hello'
		}
	}()

	lock foo {
		println(foo.name)
	}
}
```

### Possible Solution

Remove the `v fmt` conversion from `shared` to `mut` and throw a compiler error when a `shared` object is passed as `mut` to a closure.

### V version

V 0.3.4 `4e498b4.b255fef`

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 4e498b4.b255fef
OS: linux, Kali GNU/Linux Rolling (WSL 2)
Processor: 24 cpus, 64bit, little endian, 12th Gen Intel(R) Core(TM) i9-12900K

getwd: /home/casper
vexe: /opt/v/v
vexe mtime: 2023-05-01 13:13:39

vroot: OK, value: /opt/v
VMODULES: OK, value: /home/casper/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.39.2
Git vroot status: 0.3.4-2-gb255fef6 (21 commit(s) behind V master)
.git/config present: true

CC version: cc (Debian 12.2.0-14) 12.2.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by felipensp** [comment]
No idea if the compiler error is needed though. @medvednikov ? I've changed the AnonFn stringfy to do not change `shared` or `atomic` to `mut`.
