### ISSUE TITLE
Default web project not running on Windows

### ISSUE THREAD

**Issue by dmitryuck** [vlang/v#18127]
### Describe the bug

I created a new web project from template by `v new abcd web`

go to project folder and run command `v run .`

and I receive an error sqlite3.c not found in thirdparty

### Expected Behavior

project should run since it is from template

### Current Behavior

PS D:\Projects\abc>  D:\Programs\v\v run .
failed thirdparty object build cmd:
"D:\Programs\v\thirdparty\tcc\tcc.exe"   -std=c99 -D_DEFAULT_SOURCE  -I "D:\Programs\v\thirdparty\sqlite" -L "D:\Programs\v\thirdparty\sqlite" -o "C:\Users\monkg\.vmodules\cache\21\2161dfa238b5b409c340263c48e6f324.module.db.sqlite.o" -c "D:\Programs\v\thirdparty\sqlite\sqlite3.c"
builder error: tcc: error: file 'D:\Programs\v\thirdparty\sqlite\sqlite3.c' not found

### Reproduction Steps

create a new web project, run it, using sqlite3 database by default

### V version

V 0.3.4 046dd54

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 046dd54
OS: windows, Microsoft Windows 11 Home v22000 64-bit
Processor: 6 cpus, 64bit, little endian,

getwd: D:\Projects\abc
vexe: D:\Programs\v\v.exe
vexe mtime: 2023-05-07 06:26:22

vroot: OK, value: D:\Programs\v
VMODULES: OK, value: C:\Users\monkg\.vmodules
VTMP: OK, value: C:\Users\monkg\AppData\Local\Temp\v_0

Git version: git version 2.37.0.windows.1
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false

CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: cc --version
thirdparty/tcc: N/A

**Comment by enghitalo** [comment]
Please, follow the 'install SQLite dependecy' guide
https://github.com/vlang/v/blob/master/vlib/db/sqlite/README.md
