### ISSUE TITLE
C.struct compilation failure

### ISSUE THREAD

**Issue by lobotony** [vlang/v#1814]
**V version:** 0.1.18
**OS:** MacOS 10.14.6

**What did you do?**

in testy.h

        typedef int stbrp_coord;

	struct stbrp_rect
	{
	   stbrp_coord x,y;
	   int id,w,h,was_packed;
	};

in mod/mod.v

	module mod

	#include "testy.h"

	struct C.stbrp_rect
	{
		pub:
		mut:
		x int
		y int
		id int
		w int
		h int
		was_packed int
	}

	pub fn load() {
	    num_codepoints := 12

	    mut rects := []C.stbrp_rect

	    mut i := 0
	    for i < num_codepoints {
	        rects << C.stbrp_rect{}
	    }

	    mut packed := false
	    for !packed {
	        for i=int(0); i<num_codepoints; i++ {
	            rects[i].id = i
	            rects[i].w = 12
	            rects[i].h = 13
	        }

	    	packed = true
	    }
	    println('done')
	}

in main.v

        import mod

	fn main() {
		mod.load()
	}

**What did you expect to see?**
successful compilation and output 'done'
 
**What did you see instead?**
compilation failed:

    error: use of undeclared identifier 'stbrp_rect'
array_stbrp_rect rects=new_array_from_c_array(0, 0, sizeof(stbrp_rect), (stbrp_rect[]) {   0 }) ;

and lots of similar follow up errors

**Comment by medvednikov** [comment]
Works now as long as the C struct is defined in the .h file.
