### ISSUE TITLE
unmutated mutables in modules aren't reported correctly

### ISSUE THREAD

**Issue by lobotony** [vlang/v#1816]
**V version:** 0.1.18
**OS:** MacOS 10.14.6

**What did you do?**

in mod/mod.v

	module mod

	struct A {
		a int
	}

	pub fn load() {
		mut a := []A

		num := 480

		mut i:= 0
		for i < num {
			a << A{}
		}

		println('done')
	}

in main.v

	import mod

	fn main() {
		mod.load()
	}

**What did you expect to see?**
compilation abort: unused variable 'i' in 'load()' in mod.v, 
 
**What did you see instead?**
successful compilation, unterminated loop, segfault due to out-of-memory error

**Comment by avitkauskas** [comment]
Actually, 'i' was used in the code here. 
If we want V to warn or abort compilation of mutable variable was not mutated - that's a separate question.

**Comment by lobotony** [comment]
you're right. I changed the title. It would help to catch errors that lead to nondescript bugs.

**Comment by medvednikov** [comment]
Yes, @avitkauskas  is right. Just tested it in Go, and it doesn't complain.

Might be a good idea to do this in loops.

**Comment by avitkauskas** [comment]
Some languages (don't remember now where I had this) give you a hint on compilation like: "mutable variable `x` was not changed; consider making in immutable".

**Comment by medvednikov** [comment]
Ok I'm being silly.

V already does that but right now it's only enabled in `module main` :)

**Comment by avitkauskas** [comment]
Perhaps I saw that in V :D
