### ISSUE TITLE
error: 'wrong pub keyword usage'

### ISSUE THREAD

**Issue by lobotony** [vlang/v#1818]
**V version:** 0.1.18
**OS:** Mac OS 10.14.6

**What did you do?**

in mod/mod.v

	module mod

	#include <math.h>

	fn C.sqrtf(f32) f32

	struct Vec2 {
	pub:
	    x f32
	    y f32
	}

	pub fn (self Vec2) square_mag() f32 {
	    return self.x*self.x+self.y*self.y
	}

	pub fn (self Vec2) mag() f32 {
	    return C.sqrtf(self.sqaure_mag())
	}

in main.v

	import mod

	fn main() {
		v := mod.Vec2{0.0, 1.0}
		println('hello ${v.mag()}')
	}

**What did you expect to see?**
successful compilation and execution

 
**What did you see instead?**

    wrong pub keyword usage

I don't understand what's wrong here, especially since there is an identical struct in gg that seems to compile.

**Comment by spytheman** [comment]
Hm, placing fn C.sqrtf(f32) f32 below the struct declaration fixes it for me. Strange.

**Comment by avitkauskas** [comment]
Could it be that scanner messes the return type of the C.sqrtf  as `f32 struct Vec2` and takes the struct as the definition of function where `pub` does not fit then? Bold fantasy :)

**Comment by lobotony** [comment]
Does indeed work if I swap the declarations.Found another bug, but I'll file a separate issue for that one (function `` is private because of fn name typo)

**Comment by spytheman** [comment]
> Could it be that scanner messes the return type of the C.sqrtf as `f32 struct Vec2` and takes the struct as the definition of function where `pub` does not fit then? Bold fantasy :)

@avitkauskas , it is possible... Probably `fn C.xx` should become a special case, that does NOT allow for a function definition.

**Comment by medvednikov** [comment]
I'm on it.

By the way, there's `math.sqrt(f64)`

**Comment by medvednikov** [comment]
Fixed. There's still function `` is private, this was introduced yesterday. Will fix it now.
