### ISSUE TITLE
How to accurately reflect the calling of a struct function and receive its return value.

### ISSUE THREAD

**Issue by xiusin** [vlang/v#18182]
### Describe the bug

```

pub struct Test {
	
}

pub fn (mut t Test) app_string() string {
	return "hell"
}

pub fn (mut t Test) app_result_string() !string {
	return "hello"
}

pub fn (mut t Test) app_err() !Test {
	return error('xxx')
}

fn main () {
	t := Test{}
	$for method in Test.methods {
		$if method.return_type is !Test {
			val := t.$method()
			dump(val)
		}
	}
}
```

### Expected Behavior

dump the called value

### Current Behavior

```
code.v:21:29: error: invalid `$if` condition: expected a type
   19 |     t := Test{}
   20 |     $for method in Test.methods {
   21 |         $if method.return_type is !Test {
      |                                   ^
   22 |             val := t.$method()
   23 |             dump(val)
Exited with error status 1
Please try again.
```

### Reproduction Steps

https://vosca.dev/p/0c2ce78471

### V version

V 0.3.4 a7f84e7

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 da153aa.a7f84e7
OS: macos, macOS, 13.3.1, 22E772610a
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz

getwd: /Users/xiusin
vexe: /opt/v/v
vexe mtime: 2023-05-15 08:30:58

vroot: OK, value: /opt/v
VMODULES: OK, value: /Users/xiusin/.vmodules
VTMP: OK, value: /tmp/v_501

Git version: git version 2.23.0
Git vroot status: 0.3.4-53-ga7f84e79
.git/config present: true

CC version: Apple clang version 14.0.0 (clang-1400.0.29.202)
thirdparty/tcc status: thirdparty-macos-amd64 46662e20-dirty

**Comment by JalonSolov** [comment]
Your code is incorrect.

Instead of
```v
		$if method.return_type is !Test {
```
it should be
```v
		$if method.return_type !is Test {
```
With this tiny change, the code works as you expected:
```
[code.v:23] val: hell
[code.v:23] val: hello
```
