### ISSUE TITLE
No deprecation warning for `&byte`

### ISSUE THREAD

**Issue by Wertzui123** [vlang/v#18198]
### Describe the bug

/

### Expected Behavior

Some error message like `byte is deprecated; use u8 instead`.

### Current Behavior

```
main.v:6:6: error: cannot use `&byte` as `&u8` in argument 1 to `foo`
    4 | fn main() {
    5 |     p := &byte(0)
    6 |     foo(p)
      |         ^
    7 | }
```

### Reproduction Steps

```v
fn foo(p &u8) {
}

fn main() {
    p := &byte(0)
    foo(p)
}
```

### V version

V 0.3.4 ddb8e09

### Environment details (OS name and version, etc.)

Windows 10

**Comment by tobealive** [comment]
As far as I can see there are two issues that present themselves here:

1. The code should compile like it does without reference types:

```v
fn foo(p u8) {
}

fn main() {
	p := byte(0)
	foo(p)
}
```

or like the following does:

```v
type Str = string

fn foo(p &string) {
}

fn main() {
	p := &Str('abc')
	foo(p)
}
```

2. There should be a deprecation warning
