### ISSUE TITLE
How to achieve the following results through reflection？

### ISSUE THREAD

**Issue by xiusin** [vlang/v#18200]
### Describe the bug

```v
pub struct App {

}
pub fn (mut app App) app_index() ! {
	return error('hhh')
}


fn main() {
	mut app := App{}
	
	$for method in App.methods {
		$if method.is_pub && method.typ is fn() ! {
			ret := app.$method()
			dump(ret)
		}
	}
}
```

### Expected Behavior

i want get the result `hhh`

### Current Behavior

empty

### Reproduction Steps

playground: https://vosca.dev/p/67fcaec561

### V version

V 0.3.4 ee7d34e

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 da153aa.ee7d34e
OS: macos, macOS, 13.3.1, 22E772610a
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz

getwd: /Users/cb/projects/vlang
vexe: /opt/v/v
vexe mtime: 2023-05-16 05:40:12

vroot: OK, value: /opt/v
VMODULES: OK, value: /Users/cb/.vmodules
VTMP: OK, value: /tmp/v_501

Git version: git version 2.23.0
Git vroot status: weekly.2023.19-20-gee7d34e6
.git/config present: true

CC version: Apple clang version 14.0.0 (clang-1400.0.29.202)
thirdparty/tcc status: thirdparty-macos-amd64 46662e20-dirty

**Comment by felipensp** [comment]
What you is trying to do is:

```V
	mut ret := ''
	app.app_index() or { ret = err.msg() }
	dump(ret)
```

But using comptime features it seems impossible at the moment, because $method() call does not accepts `or-block` yet.
