### ISSUE TITLE
Updated need (perhaps) in Writing documentation

### ISSUE THREAD

**Issue by Mik-TF** [vlang/v#18212]
### Section Writing Documentation might need an update

In the Vlang documentation, in the section [Writing documentation](https://github.com/vlang/v/blob/master/doc/docs.md#writing-documentation), it is written that you need to add a comment with the name of the function/type/conston top to generate the documentation and then run v `doc file_name.v`.

But from what I gather, you only need the function to be public, without needing to add a comment line above, to generate the documentation.

Thus maybe we could write something along those lines:

> To generate documentation for your file, add pub in front of the function, then run `v doc file_name.v`

Or else. Just a draft.

If this isn't relevant I will delete the issue.

Thanks!

### Links

https://github.com/vlang/v/blob/master/doc/docs.md#writing-documentation

**Comment by spytheman** [comment]
The comment should still start with the fn/method name. Consider multiline comments, and that files sometimes start with comment blocks, that explain/describe the file purpose/common ideas, that are not relevant to any single local entity in that file.

**Comment by Mik-TF** [comment]
Thanks @spytheman for the reply.

I understand and agree with the need to still add a comment with the name of the fn/method name.

That being said, do you think it should be stated in the documentation that the fn/method must be public? In other words, that `pub` must be added in front of the fn/method?

Otherwise, it won't be generating the documentation of that fn/method when doing `v doc file_name.v`. Here's a screenshot of what I mean. Only the `pub fn add` is generated in the documentation, not the `fn sub`, as it is not public.

![doc_example_v_doc_call](https://github.com/vlang/v/assets/77026219/f18b0793-a6be-4cbd-b121-5613265d0c4e)

Let me know what you think.

**Comment by JalonSolov** [comment]
Just add the `-all` switch to `v doc`, and you get documentation for all methods, whether they are marked `pub` or not.  It think people just need to look at the available options...
```
$ v help doc
Generates the documentation of a given MODULE, DIRECTORY, or FILE

Usage:
  v doc [options] [MODULE / DIRECTORY / FILE] [symbol name]

Examples:
  v doc os
  v doc os File
  v doc -no-color os
  v doc -o math.html math
  v doc -m -f html vlib/

  Generates the documentation of a given MODULE, DIRECTORY, or FILE
  and prints or saves them to its desired format. It can generate HTML, JSON,
  or Markdown format.

Options:
  -all            Includes private and public functions/methods/structs/consts/enums.
  -f              Specifies the output format to be used.
                  Available formats are:
                  md/markdown, json, text, stdout and html/htm
  -h, -help       Prints this help text.
  -m              Generate docs for modules listed in that folder.
  -o              Specifies the output file/folder path where to store the
                  generated docs.
                  Set it to "stdout" to print the output instead of saving
                  the contents to a file.
  -color          Forces stdout colorize output.
  -no-color       Forces plain text output, without ANSI colors.
  -readme         Include README.md to docs if present.
  -v              Enables verbose logging. For debugging purposes.
  -no-timestamp   Omits the timestamp in the output file.

For HTML mode:
  -inline-assets  Embeds the contents of the CSS and JS assets into the
                  webpage directly.
  -theme-dir      The directory for doc theme template

For plain text mode:
  -l              Shows the locations of the generated signatures.
  -comments       Includes comments in the output.

Note: set the environment variable `VDOC_SORT` to `false`, to avoid sorting the output.

$
```

**Comment by spytheman** [comment]
As @JalonSolov showed, the default for `v doc module` is to display only the public API, but that can be changed.
