### ISSUE TITLE
Orm: cgen error when using orm.Connection

### ISSUE THREAD

**Issue by Casper64** [vlang/v#18227]
### Describe the bug

Trying to pass a database connection to a function which should accept multiple database types results in a cgen error when using `orm.Connection` as the db interface.

### Expected Behavior

The interface contains the select method, so I would expect that the select request succeeds.

### Current Behavior

```
/tmp/v_1000/main.7170100418405177614.tmp.c:47004: error: '{' expected (got ";")
builder error: 
==================
C error. This should never happen.
```

### Reproduction Steps

```v
module main

import orm
import db.pg

fn main() {
	db := pg.connect(user: 'dev', password: 'password', dbname: 'db')!
	do_query(db)!
}

struct MyTable {
	id   int    [primary; sql: serial]
	name string [nonull]
}

fn do_query(db orm.Connection) ! {
	rows := sql db {
		select from MyTable
	}!

	println(rows)
}

```

### Possible Solution

I'm not sure if this is a bug or a feature request, but since the sql syntax is the same for all database modules I would expect that there is support for creating functions for all databases.

For me generics aren't a option, since I use some functions in a vweb app.

### V version

0.3.4 ce0591d

### Environment details (OS name and version, etc.)

Linux
64bit
intel 12th gen

**Comment by walkingdevel** [comment]
Is the error still present? I have tried to reproduce it, and the snippet was built with no errors.
<img width="562" alt="image" src="https://github.com/vlang/v/assets/104449470/7ee96087-14f6-4626-a548-325f428789b5">

**Comment by Casper64** [comment]
> Is the error still present? I have tried to reproduce it, and the snippet was built with no errors.
> 
> <img width="562" alt="image" src="https://github.com/vlang/v/assets/104449470/7ee96087-14f6-4626-a548-325f428789b5">
> 
> 


Hey sorry for the delay, the code works!!

This will open so many possibilities for libraries
