### ISSUE TITLE
assigning anonymous structs to named structs is allowed

### ISSUE THREAD

**Issue by StunxFS** [vlang/v#18239]
### Describe the bug

An anonymous struct can be assigned to a named struct without any problem.

### Expected Behavior

A compiler error indicating that the types are not compatible.

### Current Behavior

Correct compilation.

### Reproduction Steps

```v
// main.v
struct Abc {
	name string
}

mut y := Abc{
	name: 'Abc'
}
println(y)
y = struct {
	name: 'Def'
}
println(y)
```
```bash
$ v run main.v
Abc{
    name: 'Abc'
}
Abc{
    name: 'Def'
}
```

### V version

V 0.3.4 e2f18fc

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 bbfa25a.e2f18fc
OS: linux, Bodhi 6.0.0
Processor: 2 cpus, 64bit, little endian, Intel(R) Pentium(R) 4 CPU 3.06GHz

getwd: /home/jomaca/dev/rivet-world/rivet
vexe: /home/jomaca/dev/v-world/v-repo/v
vexe mtime: 2023-05-22 13:51:33

vroot: OK, value: /home/jomaca/dev/v-world/v-repo
VMODULES: OK, value: /home/jomaca/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.25.1
Git vroot status: e2f18fc9-dirty
.git/config present: true

CC version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by felipensp** [comment]
I'm not sure if it is a bug. Is this an expected behavior @medvednikov ?

**Comment by medvednikov** [comment]
It's a bug. We fixed it, but apparently not entirely.
