### ISSUE TITLE
v fmt breaks syntax of inner anonymous structs if the outer struct is tagged with `[typedef]`

### ISSUE THREAD

**Issue by prantlf** [vlang/v#18233]
### Describe the bug

When `v fmt` encounters a struct tagged with `[typedef]`, if inserts this tag into each inner anonymous struct at such place, that it breaks the valid syntax and the compiler fails.

For example, when running `v fmt test.v` using the following contents of `test.v`:

```v
[typedef]
struct C.some_t {
  @type int
  data struct {}
}
```

The printed output is this:

```v
[typedef]
struct C.some_t {
	@type int
	data [typedef]
	struct {}

}
```

The compiler fails when parsing this code:

```txt
❯ v run .

some.v:18:20: error: non-constant array bound `typedef`
   16 | struct C.some_t {
   17 |     @type int
   18 |     data  [987654321][typedef]_VAnonStruct1
      |                       ~~~~~~~
   19 |
   20 | }
```

### Expected Behavior

The printed output should be this:

```v
[typedef]
struct C.some_t {
	@type int
	data struct {}
}
```

1. No `[typedef]` inserted after `data`.
2. No line break inserted after `data`.
3. No line break inserted before the trailing `}`.

### Current Behavior

The current `v fmt` produces an invalid syntax:

```v
[typedef]
struct C.some_t {
	@type int
	data [typedef]
	struct {}

}
```

### Reproduction Steps

1. Create a file `test.v` with the following contents:

```v
[typedef]
struct C.some_t {
  @type int
  data struct {}
}
```

2. Run the following command:

```sh
v fmt test.v
```

3. Read the output on the console.

### Possible Solution

Recognise that the parsed struct is an anonymous struct located in an outer struct and do not tag it, if the outermost struct is tagged with `[typedef]`.

### Additional Information/Context

The original struct in C:

```c
typedef struct some_s {
  type int;
  struct {
  } data;
} some_t;
```

### V version

V 0.3.4 1be798b

### Environment details (OS name and version, etc.)

```txt
V full version: V 0.3.4 1be798b
OS: macos, macOS, 13.3.1, 22E772610a
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz

getwd: /Users/prantlf/Sources/test
vexe: /usr/local/Cellar/vlang/0.3.4/libexec/v
vexe mtime: 2023-05-22 06:31:12

vroot: OK, value: /usr/local/Cellar/vlang/0.3.4/libexec
VMODULES: OK, value: /Users/prantlf/.vmodules
VTMP: OK, value: /tmp/v_501

Git version: git version 2.40.1
Git vroot status: weekly.2023.19-47-g1be798be
.git/config present: true

CC version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
thirdparty/tcc status: thirdparty-macos-amd64 46662e20
```

**Comment by medvednikov** [comment]
Good find!

I fixed it in https://github.com/medvednikov/v2/commit/ac34c98b46837f58be0ae9bcb2a0f91d45dabd0e

Waiting for CI, will merge soon.

**Comment by prantlf** [comment]
Thank you for the super-quick fix! And thanks to `v up` it's in use already :-)
