### ISSUE TITLE
enum field with value cannot have an attribute (checker error)

### ISSUE THREAD

**Issue by i582** [vlang/v#18242]
### Describe the bug

Code: https://vosca.dev/p/21e77dc39a

```v
enum Color {
	red = 1 [json: 'Red']
}

```

### Expected Behavior

No error

### Current Behavior

Output:

```
code.v:2:15: error: unexpected token `:`, expecting `]`
    1 | enum Color {
    2 |     red = 1 [json: 'Red']
      |                  ^
    3 | }
    4 |
Exited with error status 1
```

### Reproduction Steps

Run code above

### V version

V 0.3.3 fc4c431.e738d67

### Environment details (OS name and version, etc.)

```
V full version: V 0.3.4 fc4c431.e2f18fc
OS: linux, Ubuntu 22.04.2 LTS
Processor: 2 cpus, 64bit, little endian, Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz

getwd: /home/pmakhnev/playground
vexe: /home/pmakhnev/v/v
vexe mtime: 2023-05-22 18:00:10

vroot: OK, value: /home/pmakhnev/v
VMODULES: OK, value: /root/.vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.34.1
Git vroot status: weekly.2023.19-51-ge2f18fc9
.git/config present: true

CC version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

**Comment by i582** [comment]
Perhaps this combination does not make sense, but in this case it is better to add more detailed error message I think

**Comment by joe-conigliaro** [comment]
This is the same issue I have documented here: https://github.com/vlang/v/discussions/17715
I was talking about structs there but it is the same issue.

The best way to fix this will be the attributes syntax change, it wont require any special checks and will work everywhere then.
