### ISSUE TITLE
windows: os.open_file(): The file name is garbled

### ISSUE THREAD

**Issue by Vsirer** [vlang/v#18245]
### Describe the bug

Using os.open_file() to create a Chinese file name will be garbled

### Expected Behavior

Create a file with a Chinese name normally

### Current Behavior

The created file name is garbled

### Reproduction Steps

```
fn main(){
        mut result := os.open_file('中文.txt','w+',0x666) or {	panic(err) }
	result.write_string('test') or { panic(err) }
}
```

### V version

V 0.3.4 6698fe4

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 c4b34c9.6698fe4
OS: windows, Microsoft Windows 11 Home China v22621 64-bit
Processor: 16 cpus, 64bit, little endian,

getwd: C:\Users\V\Desktop\project\bypass\src\test
vexe: C:\Software\v\v.exe
vexe mtime: 2023-05-23 13:49:56

vroot: OK, value: C:\Software\v
VMODULES: OK, value: C:\Users\V\.vmodules
VTMP: OK, value: C:\Users\V\AppData\Local\Temp\v_0

Git version: git version 2.33.0.windows.2
Git vroot status: weekly.2023.21-2-g6698fe4f
.git/config present: true

CC version: Error: exec failed (CreateProcess) with code 2: 系统找不到指定的文件。
 cmd: cc --version
thirdparty/tcc status: thirdparty-windows-amd64 e90c2620

**Comment by tobealive** [comment]
also tested on osx an can confirm normal behaviour.

**Comment by yuyi98** [comment]
The default encoding format of Chinese windows is GBK，and source file's encoding is utf8, so the file name is garbled.

**Comment by Vsirer** [comment]
> Member

Yes, I use Chinese windows, how should I name it correctly
