### ISSUE TITLE
V help menu not working

### ISSUE THREAD

**Issue by nickel-dev** [vlang/v#18252]
### Describe the bug

I use Windows 10 and when I type `v help` into the console it says:

`
v help: unknown help topic provided. Use v help for usage information.                                                                                                                                                                   Known help topics: . 
`

I have also tried going into the v console but it too doesn't work there.

### Expected Behavior

Normally it should just give me the help menu.

### Current Behavior

it says:

'''
`v help`: unknown help topic provided. Use `v help` for usage information.                                                                                                                                                                   Known help topics: . 
'''

### Reproduction Steps

Type `v help` into the `cmd` console.

### V version

V 0.3.4

### Environment details (OS name and version, etc.)

Windows 10

**Comment by felipensp** [comment]
Try a fresh version. I can't reproduce it cloning from repo and building V.

**Comment by nickel-dev** [comment]
> Try a fresh version. I can't reproduce it cloning from repo and building V.

It worked, Thank you!
I downloaded my old build 2 days ago from [vlang.io](https://vlang.io).
