### ISSUE TITLE
Provide a full syntax diagram of V

### ISSUE THREAD

**Issue by gslicer** [vlang/v#1825]
As long we have no up-to date language reference besides of the tutorial, a `=>` [Syntax Diagram](https://en.wikipedia.org/wiki/Syntax_diagram) could possibly help to write V code and keep up with ongoing changes in the V language specs (e.g. recently the signed integer type "i32" has been made an invalid type in favor of its former alias "int").

Ideally this diagram would be build automatically from source and be updated each time one compiles V using the native V-compiler (ASCII-art representation would be more than sufficient for now), and be used to display it on the vlang.io homepage.

What do you think, would this be valuable for people learning V or working with it?

**Comment by medvednikov** [comment]
All new breaking changes will be taken care of by vfmt. User code will be automatically upgraded.

**Comment by gslicer** [comment]
> All new breaking changes will be taken care of by vfmt. User code will be automatically upgraded.

All right, so at least this sounds like backwards-compatibility to older version's source code which is good!

How about the learning aspect of the issue? Perhaps some kind of EBNF would be a good start at least?

**Comment by medvednikov** [comment]
> How about the learning aspect of the issue? Perhaps some kind of EBNF would be a good start at least?

I'm all for it :)

Unfortunately I can't work on it right now. My hands are full.

**Comment by medvednikov** [comment]
Also: https://github.com/vlang/v/issues/288

**Comment by gslicer** [comment]
> Unfortunately I can't work on it right now. My hands are full.

I understand, I will close this in favor of #288 then for now - thx for pointing to it

**Comment by gslicer** [comment]
Just in case someone digs up this issue one day. there is an other example how a language specification could be displayed: https://ziglang.org/documentation/master/#Grammar

**Comment by cristian-ilies-vasile** [comment]
FYI.
Welcome to Railroad Diagram Generator!
https://www.bottlecaps.de/rr/ui

**Comment by hachi8833** [comment]
I prefer to PEG notation for describing V specification! https://github.com/pointlander/peg

**Comment by mingodad** [comment]
See also this https://github.com/vlang/vls/issues/428 `EBNF` grammar to be viewed at https://www.bottlecaps.de/rr/ui
