### ISSUE TITLE
Operator for circular bitwise shifting

### ISSUE THREAD

**Issue by Alhadis** [vlang/v#1826]
[Bitwise rotation](https://en.wikipedia.org/wiki/Bitwise_operation#bit_rotation) is an operation directly supported by most hardware processors, although most higher-level programming languages lack an operator for it. Most compilers understand the following idiom and translate it to a single rotation instruction:

~~~c
unsigned int x = ..., n = ...;
unsigned int y = (x << n) | (x >> (-n & 31));
~~~

Might be time for a language to introduce the `<|<` and `>|>` operators, if you ask me. 😉 The above code could be expressed cleaner with:

~~~c
unsigned int y = x >|> n;
~~~

If you look at the usual logical left/right-shift operators from C-derived languages, they all resemble arrows "pushing" bits left or rightwards:

~~~c
x = a >> 5;
y = b << 2;
z = c >>> 3; /* Sign-propagating right-shift */
~~~

The `|` is meant to indicative of a "wrap-around"; i.e., bits pushed off the right [pop in from the left](https://i.imgflip.com/35h9p4.jpg) (and vice versa).

Bitwise shifts are frequently used in cryptography, and since V supports direct compilation to machine code, it might be an appropriate addition.

**Comment by joe-conigliaro** [comment]
Hey @Alhadis interesting idea that would be cool!
I had added some helers here lilke in go I was using fro crypto: https://github.com/vlang/v/blob/master/vlib/math/bits/bits.v

It might be nice to have a specific syntax for it :)

**Comment by dumblob** [comment]
How I perceive it, V is a simple language and each syntax addition would make it less appealing and less readable for non-experts. I think bit rotation could be easily added as **intrinsic functions** (in the standard library) which would compile directly to the corresponding instructions. This shall be thousand times easier than introducing & implementing new syntax over and over (and also way easier to maintain than "finding patterns in the code which shall get compiled to a specific set of instructions").

**Comment by Alhadis** [comment]
@dumblob Or there's that. 😅

The only reason I thought to bring this up now is that the language is still being developed, so if there was ever a time to get a syntax addition in for a language that plans to make few changes past v1.0, now is that time. 😜

**Comment by Alhadis** [comment]
I just wish there was a damn language out there that supported my idea for an operator that seemed to occur to [nobody](https://stackoverflow.com/questions/32785998/symbol-for-bitwise-circular-shifts) within the past 40+ years, despite being the only obvious representation for it in ASCII punctuation. 😞

**Comment by dumblob** [comment]
>I just wish there was a damn language out there that supported my idea for an operator ...

Then take any language supporting "free form syntax" ([Rebol 3](https://github.com/rebol/rebol ), [Red](https://www.red-lang.org/ ), [Spry](http://sprylang.se/ ), ...) and just define the operator yourself :wink: (the referred langs are actually really good - I admit I'm a fun of them).

**Comment by Alhadis** [comment]
Nah m8, I'll stick to APL. 😁

[![](https://raw.githubusercontent.com/Alhadis/language-apl/master/preview.png)](https://github.com/Alhadis/language-apl)

~~~apl
2 ⌽ 2 0 ⍝ GET A LOAD OF THAT SHIT
~~~

**Comment by ntrel** [comment]
> 2 ⌽ 2 0 ⍝

That just shows boxes on my phone.

For less common operations, we should not have symbolic operators but named operators instead. Much easier to Google and read in code.

**Comment by ntrel** [comment]
> the only obvious representation for it in ASCII punctuation

I don't find it obvious syntax at all.

**Comment by medvednikov** [comment]
Hey @Alhadis 

Good suggestion, didn't know that it's a single rotation instruction.

What do you think about something like `bits.rotate(a, b)`?

**Comment by Alhadis** [comment]
> What do you think about something like `bits.rotate(a, b)`?

I suppose that'd work. :+1:
