### ISSUE TITLE
compile time reflection detect for pointers to structs?

### ISSUE THREAD

**Issue by Dracks** [vlang/v#18275]
### Describe the feature

as commented in discord (https://discord.com/channels/592103645835821068/592294828432424960/1111355476081381397) yesterday using the compiler-time reflection, I needed to check if a field was an struct or not, I used the is $struct, but it happened a problem, as the field itself was a pointer to the struct. the $if field.typ is $struct was always skipping the C generation 

What It will be good, is to have an extra variable that can check if a field is a pointer or not. (At least for my case) 

### Use Case

When you are doing compiler time reflection, you need to skip some code in base if it's a pointer to an struct or not. What happened to me yesterday, was that without the flag, C was generating something like:
```
some_struct.text = voidptr_variable
```

And that provocate a crash compiling C, because the field text was string, but the type of voidptr_variable was void* (If I remember correctly) 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

v 0.3.4

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 838083e.e2f18fc
OS: macos, macOS, 13.3.1, 22E772610a
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

getwd: /Users/singlavalls/Documents/devel/home/vlang/vest
vexe: /Users/singlavalls/Applications/v/v
vexe mtime: 2023-05-22 15:58:15

vroot: OK, value: /Users/singlavalls/Applications/v
VMODULES: OK, value: /Users/singlavalls/.vmodules
VTMP: OK, value: /tmp/v_504

Git version: git version 2.39.2 (Apple Git-143)
Git vroot status: weekly.2023.21 (24 commit(s) behind V master)
.git/config present: true

CC version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
thirdparty/tcc status: thirdparty-macos-amd64 46662e20-dirty

**Comment by felipensp** [comment]
Currently you can do:

```V
struct Test {
	a &int
	b &&int
	c int
}

fn main() {
	$for f in Test.fields {
		$if f.indirections > 0 {
			println('${f.name} is ptr')
		} $else {
			println('${f.name} is not a ptr')
		}
	}
}
```

**Comment by Dracks** [comment]
I didn't know I can do the $if f.indirections >0 ... (That also means that I added a condition in my code that will work fine :) 

I think this can be close.... (but I don't know if the $if field.typ is $struct should be changed, or is fine like it is)
