### ISSUE TITLE
json.decode bug with list of generic types

### ISSUE THREAD

**Issue by darikoko** [vlang/v#18300]
### Describe the bug

Using json.decode with a list of generic type result in a bug. 
In my case I get the following message `cgen error: json: main.Response[main.Car] is not struct
Exited with error status 1`

### Expected Behavior

The excepted output should be a list of struct from the type passed in the generic type

### Current Behavior

In my case I get the following message `cgen error: json: main.Response[main.Car] is not struct
Exited with error status 1`

### Reproduction Steps

Here is the link of the playground https://vosca.dev/p/a9cda06dbe

An example of the bug

```v
import json

struct Response[T]{
	time string
	data []T
}

struct Car{
	brand string
	power int	
}

fn string_to_response[T](text string){
	result:= json.decode([]Response[T],text) or {panic(err)}
	print(result)
}

text := '[
"time":"12ms",
"cars":[
	{"brand":"Ferrari","power":232},
	{"brand":"Lamborghini", "power":345}
],
"time":"12ms",
"cars":[
	{"brand":"Ferrari","power":232},
	{"brand":"Lamborghini", "power":345}
]
]'

string_to_response[Car](text)
```

The error is the following 
`cgen error: json: main.Response[main.Car] is not struct
Exited with error status 1`

### V version

V 0.3.4 43bc85d

### Environment details (OS name and version, etc.)

This error is reproducible on v playground but here is my config 

V full version: V 0.3.4 43bc85d
OS: linux, Linux Mint 21.1
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz

getwd: /home/loic
vexe: /home/loic/.v/v
vexe mtime: 2023-05-27 14:43:28

vroot: OK, value: /home/loic/.v
VMODULES: OK, value: /home/loic/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.34.1
Git vroot status: Error: fatal: ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git
.git/config present: false

CC version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by felipensp** [comment]
@yuyi98 what do you think?

**Comment by franagustin** [comment]
Hi! Just wanted to add some extra info I found while playing a little bit with this code:

The issue seems to be solved by either:
- Adding a return type: https://vosca.dev/p/06bccc8601
- Using `.str()` inside the call to `print`: https://vosca.dev/p/25ddb9ade3

Guess it's some kind of error with the type-guessing.
Note that removing the `print` but leaving no return type, still fails.


Also, the original example is missing some curly braces for each array element (that's no V bug, just forgot to add them)

**Comment by yuyi98** [comment]
Unwrap `[]Response[T]` incorrectly in this case.
