### ISSUE TITLE
Some operators do not work in the V REPL

### ISSUE THREAD

**Issue by sainthasras** [vlang/v#18302]
### Describe the bug

Some operators such as **!=** (not equals), **<=** (less than or equals) and **>=** (greater than or equals) do not work in the V REPL.

<img width="666" alt="bug_v" src="https://github.com/vlang/v/assets/44950825/d08fdc8d-0f43-4922-870a-0ec28ce62422">

### Expected Behavior

I expected the operators to evaluate expressions

### Current Behavior

Most operators work just fine, but the ones mentioned do not work.

### Reproduction Steps

'hello' <= 'Hello'

### V version

0.3.4

### Environment details (OS name and version, etc.)

Windows 11 64-bit

**Comment by JalonSolov** [comment]
It isn't saying they don't work, just that you didn't do anything with them.
```
>>> println(6 != 8)
true
>>> println(7 <= 8)
true
>>> println(10 >= 89)
false
>>> 
```

**Comment by sainthasras** [comment]
Thank you, but other expressions like **6 < 8** work just fine....no println needed.

**Comment by sainthasras** [comment]
Also, I know (from most languages) that with the REPL, you need not explicitly write **println**. That's what the '**P**' in REPL does, isn't it?........ Read Evaluate **_Print_** Loop.

**Comment by JalonSolov** [comment]
Yes, you are correct.  However, I was just pointing out that the operators are working correctly, there is just some odd problem with printing the results.

**Comment by sainthasras** [comment]
Okay, thanks for pointing out. I just hope the odd printing problem is fixed soon. Regards.
