### ISSUE TITLE
os.is_dir() returns true for symlinks instead of directories

### ISSUE THREAD

**Issue by whakapapa** [vlang/v#18313]
### Describe the bug

Traversing a directory tree using os.walk and storing filenames in a []File struct that includes fname (string) and dir (bool). Each entry in the tree is properly captured and stored, also assed via os.is_dir(). When printing the []File array only if dir = true is prints all symlinks, but not directories. In contracts when printing all files the output seems accurate.

### Expected Behavior

Print directories in the tree

### Current Behavior

Prints symlinks in the tree

### Reproduction Steps
```v
import os

struct File {
mut:
	fname string
	dir bool
}

[heap]
struct Dir {
mut:
	files []File
}

fn (mut d Dir) addentry(f string) {
	newentry := File{
		fname: f
		dir: os.is_dir(f)
	}

	d.files << newentry
}

fn main() {
	mypath := os.home_dir() + '\\Documents' // Windows
	// mypath := os.home_dir() + '/Documents'		//Linux

	println(mypath)

	mut dirfiles := Dir{}

	os.walk(mypath, dirfiles.addentry)

	// print dirs only
	for _, v in dirfiles.files {
		if v.dir {
			println(v.fname)
		}
	}

	// println(dirfiles)
}
```
### Possible Solution

Ensure that os.is_dir returns true on directories (no matter if they are symlinks or not)

### V version

V 0.3.4 e2e6c96

### Environment details (OS name and version, etc.)

Windows 11 Pro
22H2
OS Build 22621.1778

**Comment by felipensp** [comment]
The docs says: "walk traverses the given directory path. When **a file** is encountred, it will call the callback f with current file as argument." so this is not a bug.
