### ISSUE TITLE
How to use reflection to dynamically invoke methods with different types of parameters.

### ISSUE THREAD

**Issue by xiusin** [vlang/v#18323]
### Describe the bug

```v
struct Test {
pub mut:
	name string
	age int
}

struct Cfg {
	pub mut:
	cfg string
}

fn (mut t Test) set_name(name string, age int, cfg &Cfg) {
	println('age = ${age}')
	t.name = name
	t.age = age
}

fn (t Test) get_name() string {
	return t.name + ' - ${t.age}'
}

fn main() {
	mut t := Test{}
	$for method in Test.methods {
		dump(method.args)
		if method.args.len > 0 {
			args := ['xiusin',3, Cfg{}] // ERR: invalid array element: expected `string`, not `int literal`
			println('method = ${method.name}')
			t.$method(args) or {println(err)}
			t.$method(...args) or {println(err)}
		}	
	}
	dump(t.get_name())
}

```

### Expected Behavior

success

### Current Behavior

invalid array element: expected `string`, not `int literal`

### Reproduction Steps

https://vosca.dev/p/f38da9eb27

### V version

V 0.3.4 2904c39

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 da153aa.2904c39
OS: macos, macOS, 13.3.1, 22E772610a
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz

getwd: /Users/xiusin
vexe: /opt/v/v
vexe mtime: 2023-05-29 03:39:16

vroot: OK, value: /opt/v
VMODULES: OK, value: /Users/xiusin/.vmodules
VTMP: OK, value: /tmp/v_501

Git version: git version 2.23.0
Git vroot status: weekly.2023.19-93-g2904c399-dirty
.git/config present: true

CC version: Apple clang version 14.0.0 (clang-1400.0.29.202)
thirdparty/tcc status: thirdparty-macos-amd64 46662e20-dirty

**Comment by JalonSolov** [comment]
In V, all array elements must be the same type.  The error message here is correct, as you are trying to create an array with 3 different types:
```v
    args := ['xiusin',3, Cfg{}]
```

**Comment by felipensp** [comment]
For what you are trying to do you'll need to use sum type.

Take a look at this test file https://github.com/felipensp/v/blob/486a635f4d0f6bfa47f29e8a5a8628c60b01dac4/vlib/v/tests/arraydecompose_nonvariadic_test.v it even does use array decompose to pass all parameters received.
