### ISSUE TITLE
python, ruby to V translation 

### ISSUE THREAD

**Issue by lithic** [vlang/v#1833]

**Comment by medvednikov** [comment]
Translating dynamic languages is much harder due to `eval`, `$$var` etc.

But a subset of the language is possible. Similar to what FaceBook did.

**Comment by lithic** [comment]
We want that ``

**Comment by iredmail** [comment]
It's better make V core stable enough first, forget about Python/Ruby at this stage.

**Comment by medvednikov** [comment]
Of course, this would only be worked on after 1.0 :)

**Comment by dumblob** [comment]
Nice quick overview over "simple" optimizations (or rather "what to not forget when writing a traspiler like *V*") when it comes to high-level languages like ruby, python, lua, etc. can be found on https://engineering.shopify.com/blogs/engineering/announcing-go-lua .

**Comment by spytheman** [comment]
> We want that `V` will have this capability.

@lithic , who are `we` ?

**Comment by Delta456** [comment]
@spytheman That seems to refer to V lang community

**Comment by spytheman** [comment]
@Delta456 Thanks ... I guessed so too, but there was a small chance that @lithic is a royalty though :-) ...
