### ISSUE TITLE
Cannot compile program while leaving option else block blank, error '_t1_option_main__Node_T_string_ptr' undeclared'

### ISSUE THREAD

**Issue by jaar23** [vlang/v#18345]
### Describe the bug

```
pub struct List[T] {
mut:
        head ?&Node[T]
        size int
}

pub fn (mut l List[T]) prepend(mut node Node[T]) {
        if head := l.head {
                node.next = head
                l.head = node
                l.size = l.size + 1
        } else {
                l.head = node
                l.size = 1
        }
}

pub fn (mut l List[T]) append(mut node Node[T]) ?int {
        if h := l.head {
                h
        } else {
                l.head = &node
                l.size = 0
                return l.size
        }

        mut curr_node := l.head
        for {
                if curr_node != none {
                        if next_node := curr_node?.next {
                                curr_node = next_node
                        } else {
                                println('expected place')
                                curr_node?.next = &node
                                l.size = l.size + 1
                                break
                        }
                } else {
                        println('unexpected place')  <---- without this line, it won't compile correctly.
                        // curr_node = &node
                        // l.size = l.size + 1
                        // break
                }
        }
        return l.size
}
```
The program won't compile unless leaving one line of code at the else block. 

### Expected Behavior

 I should be able to leaving the `else {...}` empty for option variable evaluation and it should compile without problem.

### Current Behavior

It won't compile unless i write one line of code in the else block.

### Reproduction Steps

The full program code as below: 

`node.v`
```
[heap]
pub struct Node[T] {
mut:
        data T
        next ?&Node[T]
}
```

`main.v`
```
import os { input }

fn main() {
        name := input('Enter your name: ')
        println('Hello, ${name}!')
        mut list := List[string]{}
        list.prepend(mut Node{ data: name })
        list.prepend(mut Node{ data: 'first' })
        list.append(mut Node{ data: 'last' }) or { panic('unable to append linked list') }
        list.append(mut Node{ data: 'very last' }) or { panic('unable to append linked list') }
        dump(list)
        // println(add(1, 2))
}
```

### Possible Solution

1. else must be declare after option variable evaluation
2. else block must have at least one line of code

### V version

V 0.3.4 4e21b2a

### Environment details (OS name and version, etc.)

Linux Fedora 37

**Comment by felipensp** [comment]
One possible workaround is to change the first if branch to.

```V
if h := l.head {
            _ := h
```

**Comment by jaar23** [comment]
it compiled after modify to @felipensp 's workaround and i can safely remove the else block, but i find it hard to understand. Can you explain to me?

**Comment by felipensp** [comment]
> it compiled after modify to @felipensp 's workaround and i can safely remove the else block, but i find it hard to understand. Can you explain to me?

The _t1 prefix on the symbol name on the error is related to such variable being concatenated with the code generated for "mut curr_node := l.head", i.e. it is about if the temporary variable that was created to the block really needs to be there.

**Comment by felipensp** [comment]
This seems fixed, can you test it again?

**Comment by jaar23** [comment]
Thanks, it's fixed. I'll close this issue.
