### ISSUE TITLE
error: Assignment discards qualifiers from pointer target type

### ISSUE THREAD

**Issue by furtidev** [vlang/v#18352]
### Describe the bug

- Supposed to be a compiler bug. (`This is a compiler bug, please report it using v bug file.v`)
I'm trying to make auto-generated Raylib bindings, and it refuses to compile with confusing errors (see below).
I'm not sure if something's wrong with my code or not, the errors aren't helping. 

I've provided a link to my codebase, I'm sorry I couldn't provide a more minimal code example, since I don't really know what could be causing it. 

### Expected Behavior

I expected it to open a simple game window or at least helpful errors. 

### Current Behavior

I'm getting the following errors:
```
/tmp/v_1000/test-vaylib.12716032374781900475.tmp.c:15093: warning: assignment discards qualifiers from pointer target type
/tmp/v_1000/test-vaylib.12716032374781900475.tmp.c:15129: error: ')' expected (got ",")
```

### Reproduction Steps

Please check this: https://github.com/furtidev/vaylib-broken-test/blob/main/src/main.v
Line 2320 contains the `main()` function. Only works on Linux, requires GLFW. 

### Possible Solution

No idea. 

### V version

V 0.3.4 a647a71

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 4dc3388.a647a71
OS: linux, Linux version 6.2.15-200.fc37.x86_64 (mockbuild@bkernel02.iad2.fedoraproject.org) (gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4), GNU ld version 2.38-27.fc37) #1 SMP PREEMPT_DYNAMIC Thu May 11 15:56:33 UTC 2023
Processor: 2 cpus, 64bit, little endian, Intel(R) Celeron(R) CPU 3867U @ 1.80GHz

getwd: /home/furtidev/Programming/test-vaylib
vexe: /home/furtidev/Programming/thirdparty/vlang/v/v
vexe mtime: 2023-06-01 17:15:42

vroot: OK, value: /home/furtidev/Programming/thirdparty/vlang/v
VMODULES: OK, value: /home/furtidev/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.40.1
Git vroot status: weekly.2023.22 (17 commit(s) behind V master)
.git/config present: true

CC version: cc (GCC) 12.3.1 20230508 (Red Hat 12.3.1-1)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by felipensp** [comment]
AudioCallback is a typedef not a C function. See how the callback part of this library is treated in https://github.com/spytheman/raylib.v/blob/main/raylib.v
