### ISSUE TITLE
Enums initialized to unknown value if no zero value provided

### ISSUE THREAD

**Issue by Molochnikov** [vlang/v#18365]
### Describe the bug

No default enum value if zero is missing in enum.

### Expected Behavior

```
TestStruct{
    test: first
}
```

### Current Behavior

```
TestStruct{
    test: unknown enum value
}
```

### Reproduction Steps

```
pub enum TestEnum {
	second = 2
	first = 1
}

pub struct TestStruct {
	test TestEnum
}
fn main() {
	println(TestStruct{})
}
```

### Possible Solution

1. Enums must be initialized to the lowest value available.
2. or
3. Force using [default] attribute on some value if zero value omitted.

### V version

0.3.4 0810e84

### Environment details (OS name and version, etc.)

Windows 11

**Comment by felipensp** [comment]
I have submitted a PR proposing the first enum value as its default value.
