### ISSUE TITLE
Error initializing DoublyLinkedList with reference type

### ISSUE THREAD

**Issue by Yaisis** [vlang/v#18367]
### Describe the bug

Error initializing DoublyLinkedList with reference type:

mut dl := datatypes.DoublyLinkedList[&User]{}   // "C gen error:1"

### Expected Behavior

Creating a List of Values

### Current Behavior

Error output "C gen error:1"

### Reproduction Steps

`
module main

import datatypes

[heap]
struct User {
	name string
}

fn main() {
	mut dl := datatypes.DoublyLinkedList[&User]{}   // "C gen error:1"
	println(dl)
}
`

### V version

V 0.3.4 c06fd55

### Environment details (OS name and version, etc.)

OS: linux, "Manjaro Linux"

**Comment by islonely** [comment]
This is the same issue I reported a while back #14815 
Would definitely like to see that pull request accepted. I've been waiting a while lol

**Comment by Delta456** [comment]
The above bug is fixed and the program successfully compiles with the correct output.

```
[]
```
