### ISSUE TITLE
Wrong notice "reference field must be initialized" when initialize struct with `...other` syntax

### ISSUE THREAD

**Issue by i582** [vlang/v#18390]
### Describe the bug

Code: https://vosca.dev/p/de49930b0e

```v


struct Outer {
	a &int
}

fn main() {
	other := Outer{}
	o := Outer{
		...other
	}
	println(o)
}
```

### Expected Behavior

No notice

### Current Behavior

Build log:

```
code.v:8:11: warning: reference field `Outer.a` must be initialized
    6 | 
    7 | fn main() {
    8 |     other := Outer{}
      |              ~~~~~~~
    9 |     o := Outer{
   10 |         ...other
```

### Reproduction Steps

Run code above

### V version

V 0.3.4 fc4c431.45f16a2

### Environment details (OS name and version, etc.)

```
V full version: V 0.3.4 fc4c431.42db392
OS: linux, Ubuntu 22.04.2 LTS
Processor: 2 cpus, 64bit, little endian, Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz

getwd: /home/pmakhnev/playground
vexe: /home/pmakhnev/v/v
vexe mtime: 2023-06-09 14:49:31

vroot: OK, value: /home/pmakhnev/v
VMODULES: OK, value: /root/.vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.34.1
Git vroot status: weekly.2023.23-20-g42db392e
.git/config present: true

CC version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

**Comment by medvednikov** [comment]
This behavior is correct?

**Comment by i582** [comment]
> This behavior is correct?

I don’t think so, because we create an object from another (like clone AFAIK), it would be strange to specify values for all reference fields separately after `...other`

**Comment by i582** [comment]
ah, sorry, it seem I'm dumb

**Comment by i582** [comment]
well, I messed up with interface fields:

<img width="885" alt="Снимок экрана 2023-06-10 в 23 41 20" src="https://github.com/vlang/v/assets/51853996/bf214a76-9e92-46f4-84ad-427624f1524c">

**Comment by i582** [comment]
Correct code: https://vosca.dev/p/d0230a2022
I'll close this issue and create new one

**Comment by i582** [comment]
Correct one: https://github.com/vlang/v/issues/18407
