### ISSUE TITLE
cann't invoke function pointer

### ISSUE THREAD

**Issue by lcddh** [vlang/v#1840]
![image](https://user-images.githubusercontent.com/5841609/64180033-ac247f00-ce96-11e9-8935-ca9aa0e4d5a9.png)

C:\Users\Administrator\Desktop\Vdemo\demo.v:7:12: expected `)` but got `,`

**Comment by gslicer** [comment]
@lcddh did you try this yet?
`fadd := &add`

Is this a way to create an alias to the function name or for what purpose you need the function's pointer?

**Comment by Danil-Lapirow** [comment]
Paste code instead of screenshot please.  

-------------------
No
> Is this a way to create an alias to the function name or for what purpose you need the function's pointer?

**Comment by Danil-Lapirow** [comment]
We are about to change compiler architecture soon so this will be very easy to fix.

**Comment by mvlootman** [comment]
This works:

```
fn add(x int y int) int {
        return x + y
}

fn exec(a, b int, op fn(int,int)int) int{
        return op(a, b)
}
fn main(){        
        
        println(exec(2, 5, add))
}
```

**Comment by Danil-Lapirow** [comment]
When you write `fadd := add`, fadd is stored as `void*` for some reason.
This is the issue.
