### ISSUE TITLE
compile-time conditions and return type checking in compile-time operations

### ISSUE THREAD

**Issue by dnkdev** [vlang/v#18400]
### Describe the bug

Code: https://vosca.dev/p/faf4053373

```v
struct Struct {
	a int
	txt string
	array []string
}
fn get_string[T](s T) string {
	$for field in T.fields{
		$if field.name == 'txt' {
			return s.$(field.name)
		}
	}
	return ''
}
s := Struct{txt: 'hello'}
println(get_string(s))
```

### Expected Behavior

So this is a feature request as well. 

Now getting compile time error, when trying to return struct field. I see I can get around this error in few cases, for example make `return s.$(field.name).str()`, but only if return type is string like in example, but with maps, arrays, structs- I don't know how to get around this error.
Also, I know I can define straight field name `return s.txt` , but this way code lacks much flexibility, this is not how it needed to be.

I think this piece of code doesn't need to be checked at all, if some comp-time condition did not pass: `$if field.name == 'txt' `. 

### Current Behavior

Output:

```
code.v:9:13: error: cannot use `int` as type `string` in return argument
    7 |     $for field in T.fields{
    8 |         $if field.name == 'txt' {
    9 |             return s.$(field.name)
      |                      ~~~~~~~~~~~~~
   10 |         }
   11 |     }
Exited with error status 1
```

### Reproduction Steps

.

### V version

V 0.3.4 fc4c431.45f16a2

### Environment details (OS name and version, etc.)

```
V full version: V 0.3.4 fc4c431.3e5f254
OS: linux, Ubuntu 22.04.2 LTS
Processor: 2 cpus, 64bit, little endian, Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz

getwd: /home/pmakhnev/playground
vexe: /home/pmakhnev/v/v
vexe mtime: 2023-06-10 00:00:10

vroot: OK, value: /home/pmakhnev/v
VMODULES: OK, value: /root/.vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.34.1
Git vroot status: weekly.2023.23-21-g3e5f2541 (1 commit(s) behind V master)
.git/config present: true

CC version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

**Comment by tobealive** [comment]
you could check the type of the field at comptime.


```v
struct Struct {
	a     int
	txt   string
	array []string
}

fn get_string[T](s T) string {
	$for field in T.fields {
		$if field.typ is string {
			return s.$(field.name)
		}
	}
	return ''
}

s := Struct{
	txt: 'hello'
}
println(get_string(s))
```

**Comment by tobealive** [comment]
if the condition should be limited to the field name, you could add the check after the type is checked.

**Comment by dnkdev** [comment]
Oh, I'd say it's a bit odd for me that the other condition doesn't do the same, but thanks for letting me know that the type condition does what I need. This way really works:
```v
$if field.typ is string {  // field.is_map, field.is_array also
  $if field.name == 'txt' {
    return s.$(field.name)
  }
}
```

**Comment by tobealive** [comment]
👍 
I would describe it that one is just a string comparison, the other is a dynamic type cast. A string comparison is also a bit more expensive, so you are also making a small performance improvement adding the tyepcheck beforehand 😊.

**Comment by dnkdev** [comment]
Yeah, maybe make string comparison more heavier is not necessary. But if it is compile time load... ok, I can't say how it is reflected on performance... Just need to know proper way, thank you for that. I think issue can be closed if no need. :)

**Comment by felipensp** [comment]
Your point makes sense, It can be implemented.
