### ISSUE TITLE
Fmt removes parentheses when it shouldn't

### ISSUE THREAD

**Issue by lspaccatrosi16** [vlang/v#18414]
### Describe the bug

When running fmt on a file, parentheses get removed from a pointers to consts

### Expected Behavior

All other formatting to be applied correctly without changing the meaning of the program 

### Current Behavior

Parentheses deliberately placed around a pointer get removed by the formatter

### Reproduction Steps

From an input of this

```v
module ast

struct MyChar {
	c string
}

const a_char = MyChar{c: 'a'}

fn foo() {
	mut b := &(ast.a_char)
}
```

All gets correctly formatted except for the line when `v fmt` is run

```v
mut b := &ast.a_char
```

Without the parentheses the compiler correctly complains about having a mutable reference to `ast.a_char`

### V version

latest

### Environment details (OS name and version, etc.)

OS: Fedora 36

V full version: V 0.3.4 9dcd95e.83e30a8
OS: linux, Linux version 5.19.15-202.fsync.fc36.x86_64 (mockbuild@d098d9dbc9d84cd0ac52adcd887d4a35) (gcc (GCC) 12.2.1 20220819 (Red Hat 12.2.1-2), GNU ld version 2.37-36.fc36) #1 SMP PREEMPT_DYNAMIC Sat Oct 15 21:34:38 UTC 2022
Processor: 8 cpus, 64bit, little endian, AMD Ryzen 3 3100 4-Core Processor

getwd: /home/luca/dev/vlang/vmonkey
vexe: /home/luca/dev/v/v
vexe mtime: 2023-06-11 13:58:36

vroot: OK, value: /home/luca/dev/v
VMODULES: OK, value: /home/luca/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.40.1
Git vroot status: weekly.2023.23-27-g83e30a81
.git/config present: true

CC version: cc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by medvednikov** [comment]
> Without the parentheses the compiler correctly complains about having a mutable reference to ast.a_char

But it's the same thing. It's actually a bug that the compiler doesn't complain about it.

**Comment by medvednikov** [comment]
@tobealive I think the old behavior is correct. The () are unnecessary, and vfmt removes unnecessary ().

The checker needs to be updated to return the same error for &()

**Comment by tobealive** [comment]
I'll sit with it later today for the actual fix.
