### ISSUE TITLE
match does not work with arrays with reference types

### ISSUE THREAD

**Issue by tobealive** [vlang/v#18429]
### Describe the bug

Trying match an array with reference types will result in not correctly recognizing the type. Instead an unexpected token error is thrown.

### Expected Behavior

Match works just as an dynamic if cast does with the same types.

### Current Behavior

```
sumtypes/array.v:11:10: error: unexpected token `(`, expecting `:`
    9 | match t {
   10 |     []&MyStruct {
   11 |         println("it's a []&MyStruct")
      |                ^
   12 |     }
   13 |     []&string {
```

### Reproduction Steps

```v
type MySumType = []&MyStructA | []&MyStructB

struct MyStructA {
	my_field string
}

struct MyStructB {
	my_field string
}

t := MySumType([&MyStructA{'a'}, &MyStructA{'b'}])

match t {
	[]&MyStructA {
		println("it's &A")
	}
	[]&MyStructB {
		println("it's &B")
	}
}

// Works ↓
if t is []&MyStructA {
	println("it's &A")
} else if t is []&MyStructB {
	println("it's &B")
}
```

### V version

V 0.3.4 7f178d4

### Environment details (OS name and version, etc.)

linux,arch;amd64

**Comment by tobealive** [comment]
Yes, it's a good question. I also was unsure why the declaration of one is working an the other is disallowed. A user could hack around a sumtype with simple reference by using an array containing one reference element.

Naively asked, why are refs not supported with sumtypes?

**Comment by JalonSolov** [comment]
Why do you need the sum type itself to be a reference, when you can always take a reference of the sum type?

In other words, instead of
```v
type MySumType = &MyStructA | &MyStructB
```
use
```v
type MySumType = MyStructA | MyStructB

foo := &MySumType{}
```

**Comment by Delta456** [comment]
I think this should be a checker error.

**Comment by tobealive** [comment]
Thanks @JalonSolov. Maybe even adding this as a hint to the error message. Something like `use &MySumType{} instead`.

Even though it's obvious in retrospect, the hint would have prevented a question as mine a maybe would have even made clear in @Delta456 response that `[]&MyStruct` is not a ref type per se and not compatible with Jalon's solution.

Next question would be why should this be a checker error? There are use cases for an array of ref types and it already works with if casting.
