### ISSUE TITLE
C error: pointer expected

### ISSUE THREAD

**Issue by StroveLight** [vlang/v#18456]
### Describe the bug

I get a C error whle trying to compile my code

### Expected Behavior

A V error if i'm doing things wrongly else for the code to compile

### Current Behavior

`v -cg .` output:
```
C:/Users/Usuario/AppData/Local/Temp/v_0/06.5745926095654516074.tmp.c:502: warning: WINVER redefined
C:/Users/Usuario/AppData/Local/Temp/v_0/06.5745926095654516074.tmp.c:6871: warning: implicit declaration of function 'tcc_backtrace'
C:/Users/Usuario/AppData/Local/Temp/v_0/06.5745926095654516074.tmp.c:7645: warning: assignment from incompatible pointer type
C:/Users/Usuario/AppData/Local/Temp/v_0/06.5745926095654516074.tmp.c:7645: warning: assignment makes pointer from integer without a cast
C:/Users/Usuario/AppData/Local/Temp/v_0/06.5745926095654516074.tmp.c:7645: warning: cast between pointer and integer of different size
C:/Users/Usuario/AppData/Local/Temp/v_0/06.5745926095654516074.tmp.c:12655: error: pointer expected
builder error:
==================
C error. This should never happen.
```

### Reproduction Steps

Compile the following code:
```
struct Node{
	parent    ?&Node
}

fn set_trace(n Node) {
	if n.parent != none{
		set_trace(n.parent)
	}
}

fn main() {
	mut initial_node := Node{
		parent: none
	}
	set_trace(initial_node)
}

```

### Additional Information/Context

It happened while trying to find out what was causing https://github.com/vlang/v/issues/18454

### V version

V 0.3.4 34163ae

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 d8cf65d.34163ae
OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 8 cpus, 64bit, little endian,

getwd: C:\Users\Usuario\Desktop\Universidad\mag\v_test\06
vexe: C:\Program Files\v\v.exe
vexe mtime: 2023-06-15 02:39:11

vroot: contains spaces, value: C:\Program Files\v
VMODULES: OK, value: C:\Users\Usuario\.vmodules
VTMP: OK, value: C:\Users\Usuario\AppData\Local\Temp\v_0

Git version: git version 2.40.1.windows.1
Git vroot status: weekly.2023.24-8-g34163ae4
.git/config present: true

CC version: cc (Rev6, Built by MSYS2 project) 13.1.0
thirdparty/tcc status: thirdparty-windows-amd64 e90c262

**Comment by felipensp** [comment]
Thanks for testing. I've submitted a PR.

The checker must warn about n.parent needing to be unwrapped first.

`set_trace(n.parent or { &Node{} })`
