### ISSUE TITLE
C error: field expected

### ISSUE THREAD

**Issue by StroveLight** [vlang/v#18455]
### Describe the bug

I get a `C error: field expected` when using pointer with Option

### Expected Behavior

I expect an V error if I'm doing things not properly

### Current Behavior

i get a C error when trying to compile. `v -cg .` output:
```
C:/Users/Usuario/AppData/Local/Temp/v_0/05.9304617435245562907.tmp.c:502: warning: WINVER redefined
C:/Users/Usuario/AppData/Local/Temp/v_0/05.9304617435245562907.tmp.c:6871: warning: implicit declaration of function 'tcc_backtrace'
C:/Users/Usuario/AppData/Local/Temp/v_0/05.9304617435245562907.tmp.c:7645: warning: assignment from incompatible pointer type
C:/Users/Usuario/AppData/Local/Temp/v_0/05.9304617435245562907.tmp.c:7645: warning: assignment makes pointer from integer without a cast
C:/Users/Usuario/AppData/Local/Temp/v_0/05.9304617435245562907.tmp.c:7645: warning: cast between pointer and integer of different size
C:/Users/Usuario/AppData/Local/Temp/v_0/05.9304617435245562907.tmp.c:12655: warning: assignment makes integer from pointer without a cast
C:/Users/Usuario/AppData/Local/Temp/v_0/05.9304617435245562907.tmp.c:12655: warning: cast between pointer and integer of different size
C:/Users/Usuario/AppData/Local/Temp/v_0/05.9304617435245562907.tmp.c:12655: error: field expected
builder error:
==================
C error. This should never happen.
```

### Reproduction Steps

Compile the following code (println is included to avoid the warning of unused variable)
```
struct Node{
pub mut:
	parent    ?&Node
	id        int
}

fn main() {
	initial_node := Node{
		parent: none,
		id:		1
	}
	println(initial_node.id)
}
```

### Additional Information/Context

I found it while trying to find out what caused the error in https://github.com/vlang/v/issues/18454
I'm not sure if it is related or not

### V version

V 0.3.4 34163ae

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 d8cf65d.34163ae
OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 8 cpus, 64bit, little endian,

getwd: C:\Users\Usuario\Desktop\Universidad\mag\v_test\05
vexe: C:\Program Files\v\v.exe
vexe mtime: 2023-06-15 02:39:11

vroot: contains spaces, value: C:\Program Files\v
VMODULES: OK, value: C:\Users\Usuario\.vmodules
VTMP: OK, value: C:\Users\Usuario\AppData\Local\Temp\v_0

Git version: git version 2.40.1.windows.1
Git vroot status: weekly.2023.24-8-g34163ae4
.git/config present: true

CC version: cc (Rev6, Built by MSYS2 project) 13.1.0
thirdparty/tcc status: thirdparty-windows-amd64 e90c2620

**Comment by felipensp** [comment]
I can't reproduce it. Try with a newest V version please.

**Comment by StroveLight** [comment]
v version on windows is
V 0.3.4 34163ae

**Comment by felipensp** [comment]
Ah ok, I can reproduce it with clang-17. But I've already fixed such bug in another PR. I'll link it.
