### ISSUE TITLE
Compiler reports error in function only if unrelated println() is present

### ISSUE THREAD

**Issue by scorwin** [vlang/v#18478]
### Describe the bug

1. Whether the compiler reports an error in a function depends on whether an unrelated println() is present.
2. A possible enum-related error; see the MWE below.

### Expected Behavior

I started learning V two days ago, so I can't tell how many problems there are here. Certainly, though, whether the compiler reports an error in the function should not depend on whether an unrelated println() is called.  I'm such a tyro that I can't be certain that the code below, which was modeled on some I found elsewhere, is correct.  If it is, then the function should not be returning the results I see.

### Current Behavior

As described above, the compiler reports an error only if an unrelated line of code is present.

### Reproduction Steps
```v
enum Color {red green blue}

// If the following line is commented out, this compiles, runs, and
// gives incorrect results.  If it is un-commented, the compiler
// errors out, saying that mutable arguments are not allowed here.
//
//println('x')

fn (mut c Color) change() {
  c = match c {
    .red {.blue}
    .green {.red}
    .blue {.green}
  }
}

mut color := Color.red
println(color)  // prints 'red'
color.change()
println(color)  // prints 'green'
color.change()
println(color)  // prints 'green'
```

### V version

V 0.3.3 c4b34c9

### Environment details (OS name and version, etc.)

Windows 11 Pro v22621 64-bit

**Comment by yuyi98** [comment]
If you use single-file script mode, all statements should be placed in the back, not in front of the function declaration.

**Comment by JalonSolov** [comment]
Your version of V is also quite a bit behind the current version.  If you installed any way other than cloning the repo, I recommend deleting what you have, and installing this way:

https://github.com/vlang/v#installing-v-from-source

**Comment by scorwin** [comment]
Thank you.  Freshman mistake.
-------------------------------------
Stephen Corwin
Professor, Mathematics and Statistics Department
Radford University
www.radford.edu/math-web


-------------------------------------

**Comment by scorwin** [comment]
Thanks, I'll do that.
-------------------------------------
Stephen Corwin
Professor, Mathematics and Statistics Department
Radford University
www.radford.edu/math-web


-------------------------------------
