### ISSUE TITLE
*Foo to &Foo regression: expected `name` but got `&`

### ISSUE THREAD

**Issue by lobotony** [vlang/v#1848]
**V version:** 0.1.18
**OS:** 10.14.6

**What did you do?**

	struct Test{
		
	}

	fn C.name(&T)

	fn main() {
		println('hello')
	}

**What did you expect to see?**
succesful compilation
 
**What did you see instead?**

     expected `name` but got `&`

This still compiles if I change & back to *, or if I leave the & and add a parameter name.

**Comment by ntrel** [comment]
C doesn't have references, I really don't think calling a C function should support reference parameters. C is more lax with pointer safety than V can be with references.

**Comment by medvednikov** [comment]
C pointers will still work with `unsafe`

I should remove that warning from C function definitions, good find @lobotony
