### ISSUE TITLE
generic + method call from closures

### ISSUE THREAD

**Issue by russo-2025** [vlang/v#18481]
### Describe the bug

```v
module main

struct MyPlugin {
}

fn (p MyPlugin) on_update() {
	println("[MyPlugin.on_update]")
}

fn foo[T](my_plugin T) {
	println("[foo]")
	println(T.name) // MyPlugin
	println(typeof(my_plugin)) // MyPlugin
	fn[my_plugin](){ my_plugin.on_update() }() // <---- error: unknown method or field: `T.on_update`
}

fn main() {
	foo[MyPlugin](MyPlugin{})
	
	//my_plugin := MyPlugin{}
	//fn[my_plugin](){ my_plugin.on_update() }() // <-------- ok
}
```

### Expected Behavior

ok

### Current Behavior

error

```
main.v:32:28: error: unknown method or field: `T.on_update`
   30 |     println(T.name) // MyPlugin
   31 |     println(typeof(my_plugin)) // MyPlugin
   32 |     fn[my_plugin](){ my_plugin.on_update() }()
      |                               ~~~~~~~~~~~
   33 | }
```

### Reproduction Steps

`v run main.v`

### V version

V 0.3.4 017cc67

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 b2a71ec.017cc67
OS: windows, Microsoft Windows 10 Pro v19042 64-bit
Processor: 16 cpus, 64bit, little endian, 

getwd: C:\Users\russo\Desktop\v-test-events
vexe: D:\_dev\v_lang\v.exe
vexe mtime: 2023-06-18 08:45:42

vroot: OK, value: D:\_dev\v_lang
VMODULES: OK, value: C:\Users\russo\.vmodules
VTMP: OK, value: C:\Users\russo\AppData\Local\Temp\v_0

Git version: git version 2.35.3.windows.1
Git vroot status: weekly.2023.24-24-g017cc673
.git/config present: true

CC version: Error: exec failed (CreateProcess) with code 2: Не удается найти указанный файл.
 cmd: cc --version
thirdparty/tcc status: thirdparty-windows-amd64 e90c2620

**Comment by yuyi98** [comment]
Missing [T] for anon closure fn.
```v
struct MyPlugin {
}

fn (p MyPlugin) on_update() {
	println('[MyPlugin.on_update]')
}

fn foo[T](my_plugin T) {
	println('[foo]')
	println(T.name) // MyPlugin
	println(typeof(my_plugin).name) // MyPlugin
	fn [my_plugin] [T]() {
		my_plugin.on_update()
	}()
}

fn main() {
	foo[MyPlugin](MyPlugin{})
}

PS D:\Test\v\tt1> v run .
[foo]
MyPlugin
MyPlugin
[MyPlugin.on_update]
```
