### ISSUE TITLE
V fails to compile app when used with Zig as C compiler and musl target 

### ISSUE THREAD

**Issue by SebastianMpl** [vlang/v#18493]
### Describe the bug

When I try to compile a v file with zig as a compiler and musl target the compilation fails.

### Expected Behavior

It should compile

### Current Behavior
```
~/Pobrane/v: ./v -prod -cflags '-target x86_64-linux-musl' ./examples/fetch.v
==================
                                                  ^
/tmp/v_1000/fetch.8719524723899142083.tmp.c:11224:12: error: incompatible integer to pointer conversion initializing 'char **' with an expression of type 'int' [-Wint-conversion]
                                char** csymbols = backtrace_symbols(((voidptr)(&buffer[v_fixed_index(skipframes, 100)])), nr_actual_frames);
                                       ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/v_1000/fetch.8719524723899142083.tmp.c:18244:4: warning: expression result unused [-Wunused-value]
  (*(bool*)_t15.data);
   ^~~~~~~~~~~~~~~~~
/tmp/v_1000/fetch.8719524723899142083.tmp.c:18424:4: warning: expression result unused [-Wunused-value]
  (*(string*)_t1.data);
   ^~~~~~~~~~~~~~~~~~
/tmp/v_1000/fetch.8719524723899142083.tmp.c:18533:4: warning: expression result unused [-Wunused-value]
  (*(bool*)_t1.data);
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```
### Reproduction Steps

./v -prod -cflags '-target x86_64-linux-musl' ./examples/fetch.v

Run with zig as cc

### Additional Information/Context

When used with gnu target:
./v -prod -cflags '-target x86_64-linux-gnu' ./examples/fetch.v it compiles (about 40 sec) and works fine

### V version

0.3.4

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 046dd54
OS: linux, "Arch Linux"
Processor: 2 cpus, 64bit, little endian, Intel(R) Core(TM)2 Duo CPU     T7300  @ 2.00GHz

getwd: /home/seba/Pobrane/v
vexe: /home/seba/Pobrane/v/v
vexe mtime: 2023-04-30 22:01:32

vroot: OK, value: /home/seba/Pobrane/v
VMODULES: OK, value: /home/seba/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: Error: sh: line 1: git: command not found

Git vroot status: Error: sh: line 1: git: command not found
.git/config present: false

CC version: clang version 15.0.7 (https://github.com/ziglang/zig-bootstrap a3a6e85f9ec95b1772f5ace363e46df2f336c6b8)
thirdparty/tcc status: Error: sh: line 1: git: command not found
 Error: sh: line 1: git: command not found

**Comment by JalonSolov** [comment]
Try using https://github.com/malisipi/vzcc to pair V with zig.

Looks like you also need to install `git` on your system.

**Comment by SebastianMpl** [comment]
@JalonSolov 
Thank you very much for your hint.
A little bit of configuration but works as expected.
