### ISSUE TITLE
(compiler crash) cannot convert 'struct' to 'unsigned char'

### ISSUE THREAD

**Issue by keiravillekode** [vlang/v#18495]
### Describe the bug

Compiler crashed with message

error: cannot convert 'struct ...' to 'unsigned char'

### Expected Behavior

Compiler should not crash.

### Current Behavior

```
 FAIL ...
: error: cannot convert 'struct main__MyStruct' to 'unsigned char'
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

```

### Reproduction Steps

my_test.v

```
module main

struct MyStruct {
    field int
}

pub type MyOpt = ?MyStruct

fn empty() map[string]MyOpt {
  return {}
}

fn test_empty() {
    expected := {'key': MyOpt(none)}
    assert empty() == expected
}

```

v test my_test.v

### V version

V 0.3.4 c657384 

### Environment details (OS name and version, etc.)

OS: linux, Ubuntu 22.04.2 LTS

**Comment by felipensp** [comment]
Already fixed by PR #18490
