### ISSUE TITLE
match: unreachable code

### ISSUE THREAD

**Issue by lobotony** [vlang/v#1850]
**V version:** 0.1.18
**OS:** MacOS 10.14.6

**What did you do?**

	struct vec4 {
	    pub:
	    x f32
	    y f32
	    z f32
	    w f32
	}

	fn (self vec4) str() string {
		return 'vec4{}'
	}

	struct Mat44 {
	    pub:
	    data [16]f32
	}

	pub fn (self Mat44) get_col(index int) vec4 {
	    match index {
	        0 => { return vec4{self.data[0], self.data[1], self.data[2], self.data[3]} }
	        1 => { return vec4{self.data[4], self.data[5], self.data[6], self.data[7]} }
	    }
	    return vec4{}
	}

	fn main() {
		m := Mat44{}
		c := m.get_col(0)
		println('hello $c')
	}

**What did you expect to see?**
successful compilation
 
**What did you see instead?**

    main.v:18:21: unreachable code

**Comment by gslicer** [comment]
I think this means the same as "variable declared but never used" (you never use the functions and those structures - it's a reasonable error in my opinion

**Comment by lobotony** [comment]
nope, that would be fatal. Unused code should not lead to compilation errors. 
Also, this is not the source of the error. I will adjust the code to use it. Same outcome.

**Comment by kawa-yoiko** [comment]
This seems to call for a few language design choices!

Firstly, code that compile:

```v
pub fn (self Mat44) get_col(index int) vec4 {
    return match index {
        0 => { vec4{self.data[0], self.data[1], self.data[2], self.data[3]} }
        1 => { vec4{self.data[4], self.data[5], self.data[6], self.data[7]} }
        else => { vec4{} }
    }
}

// -- or --

pub fn (self Mat44) get_col(index int) vec4 {
    switch index {
        0 => { return vec4{self.data[0], self.data[1], self.data[2], self.data[3]} }
        1 => { return vec4{self.data[4], self.data[5], self.data[6], self.data[7]} }
        else => { return vec4{} }
    }
}
```

But `switch` is not mentioned in the documentation, and it's unclear how it differs from `match`. Is it desirable to unify the two, or to better document them? Also, [the example for `match` in the docs](https://vlang.io/docs#match) missed surrounding brackets for branches... There probably is still a bit work to be done here 😓

**Comment by gslicer** [comment]
> 
> 
> nope, that would be fatal. Unused code should not lead to compilation errors.
> Also, this is not the source of the error. I will adjust the code to use it. Same outcome.

You could argue about that, since such structures perhaps are using some memory/symbols at least - of course failing to compile/giving an error is maybe a bit exarrogated but a warning at compile time would be still something I would like to see (same goes for the unused var case).

If you really want to keep such blocks (because they are possibly unfinished) there are still means e.g. by using block comments /* */

**Comment by gslicer** [comment]
> But `switch` is not mentioned in the documentation, and it's unclear how it differs from `match`. Is it desirable to unify the two, or to better document them?

I think the intention is to keep just "match", wondering that "switch" is still recognized, but definetly was valid, see: #1132  on 14 Jul "switch will be replaced with match expressions"

> Also, [the example for `match` in the docs](https://vlang.io/docs#match) missed surrounding brackets for branches... There probably is still a bit work to be done here sweat

There was a recent discussion leading to introduction of blocks inside match, see: #1677

**Comment by Yardanico** [comment]
A shorter reproduction code:
```
fn ll(input string) int {
    match input {
        'add' => {return 5}
        else => {return 3}
    }
}

fn main() {
    input := os.get_line()
    println(ll(input))
}
```

**Comment by Danil-Lapirow** [comment]
switch statement has bug, it executes your expression multiple times
