### ISSUE TITLE
Builder error

### ISSUE THREAD

**Issue by jasonpezzimenti** [vlang/v#18517]
### Describe the bug

I am trying to follow along with the tutorial and I keep experiencing the same error:

```
jase@penguin:/mnt/chromeos/MyFiles/Development/V$ v new PROJECTNAME
cannot compile `/v/cmd/tools/vcreate`: 
builder error: folder `/v/cmd/tools/vcreate` is not writable; code: 3
```

when trying to do v init or v new projectname

### Expected Behavior

I expect a new project to be created.

### Current Behavior

Errors out

### Reproduction Steps

Install v using instructions from v readme file on github, and do

v init after sudo ./v symlink

### V version

V 0.3.4 76ae9db

### Environment details (OS name and version, etc.)

Chrome OS Flex

**Comment by JalonSolov** [comment]
Check the permissions on your `/v/cmd/tools` directory, and the `/v/cmd/tools/vcreate` file.  Both _must_ be writable by you.

**Comment by jasonpezzimenti** [comment]
That worked. Thank you so much!
