### ISSUE TITLE
Builder - C error 

### ISSUE THREAD

**Issue by Eliyaan** [vlang/v#18528]
### Describe the bug

The -prod compilation did not work.

### Expected Behavior

It to work and compile

### Current Behavior

```
PS C:\Users\PACHECON\_cv> v -prod "c:\Users\PACHECON\_cv\test_file.v" -cg
C:\Users\PACHECON\AppData\Local\Temp\v_0\test_file.3204872096311188901.tmp.c: In function 'winapi_lasterr_str':
C:\Users\PACHECON\AppData\Local\Temp\v_0\test_file.3204872096311188901.tmp.c:7648:195: warning: passing argument 5 of 'FormatMessageW' from incompatible pointer type [-Wincompatible-pointer-types]
 7648 |         voidptr res = FormatMessage(((FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM) | FORMAT_MESSAGE_IGNORE_INSERTS), NULL, err_msg_id, MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), &msgbuf, 0, NULL);
      |
                                 ^~~~~~~
      |
                                 |
      |
                                 u16 ** {aka short unsigned int **}
In file included from C:/mingw/x86_64-w64-mingw32/include/windows.h:70,
                 from C:\Users\PACHECON\AppData\Local\Temp\v_0\test_file.3204872096311188901.tmp.c:515:
C:/mingw/x86_64-w64-mingw32/include/winbase.h:1441:122: note: expected 'LPWSTR' {aka 'short unsigned int *'} but argument is of type 'u16 **' {aka 'short unsigned int **'}
 1441 |   WINBASEAPI DWORD WINAPI FormatMessageW (DWORD dwFlags, LPCVOID lpSource, DWORD dwMessageId, DWORD dwLanguageId, LPWSTR lpBuffer, DWORD nSize, va_list *Arguments);
      |                                                                                                                   ~~~~~~~^~~~~~~~
C:\Users\PACHECON\AppData\Local\Temp\v_0\test_file.3204872096311188901.tmp.c:7648:23: warning: initialization of 'voidptr' {aka 'void *'} from 'DWORD' {aka 'long unsigned int'} makes pointer from integer without a cast [-Wint-conversion]
 7648 |         voidptr res = FormatMessage(((FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM) | FORMAT_MESSAGE_IGNORE_INSERTS), NULL, err_msg_id, MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), &msgbuf, 0, NULL);
      |                       ^~~~~~~~~~~~~
C:\Users\PACHECON\AppData\Local\Temp\v_0\test_file.3204872096311188901.tmp.c: In function 'main__main':
C:\Users\PACHECON\AppData\Local\Temp\v_0\test_file.3204872096311188901.tmp.c:12658:39: error: lvalue required as unary '&' operand
12658 |         Array_int* pointer_to_slice = &array_slice((*(new_data)), 1, 1);
      |                                       ^
builder error:
==================
C error. This should never happen.
```

### Reproduction Steps

Use v -prod to compile this program: 

```
fn main(){
	new_data := [0, 1]
	pointer_to_slice := &new_data[1..2]
	dump(pointer_to_slice)
}
```

### V version

Current V version: V 0.3.4 9d77fd9, timestamp: 2023-06-22 22:48:15 +0300

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 7de3485.9d77fd9
OS: windows, Microsoft Windows 10 Education v19045 64 bits
Processor: 4 cpus, 64bit, little endian

**Comment by JalonSolov** [comment]
Well, there's at least one definite bug in your program.  A slice of `1..1` is 0 items wide.  If you only want the 2nd element, use `1..`.

Which version of gcc do you have (`gcc --version`)?

**Comment by Eliyaan** [comment]
> Which version of gcc do you have (`gcc --version`)? This code works as expected on Linux using gcc 13.1.1. You can get the Windows version of this version from https://winlibs.com
> 
> ```
> $ gcc --version
> gcc (GCC) 13.1.1 20230429
> Copyright (C) 2023 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> $ cat foo.v
> ```
> 
> ```v
> fn main() {
>         new_data := [0, 1]
>         pointer_to_slice := &new_data[1..1]
>         dump(pointer_to_slice)
> }
> ```
> 
> ```
> $ v run foo.v
> [foo.v:4] pointer_to_slice: &[]
> $ 
> ```

gcc.exe (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders) 13.1.0 
I'll try updating right now, but have you tried V -prod ? because the program works in v run for me too but not with -prod.

**Comment by JalonSolov** [comment]
Ah... with `-prod` I also get an error, though it is shorter than what you're getting (mainly due to the lack of Windows-related warnings):
```
==================
/tmp/v_1000/foo.5738540658298646858.tmp.c: In function ‘main__main’:
/tmp/v_1000/foo.5738540658298646858.tmp.c:12566:39: error: lvalue required as unary ‘&’ operand
12566 |         Array_int* pointer_to_slice = &array_slice((*(new_data)), 1, 1);
      |                                       ^
...
==================
```
