### ISSUE TITLE
error: cannot append `none` to `[]?&int`

### ISSUE THREAD

**Issue by StroveLight** [vlang/v#18523]
### Describe the bug

I'm trying to append none to an array of option type of pointers, but i get the error cannot append `none` to `[]?&int`

### Expected Behavior

i expect the code to work, as the following code does:
```
fn main(){
	mut a := []?&int{}
	a << ?&int(none)
	dump(a[0])
}
```

### Current Behavior

```
main.v:3:7: error: cannot append `none` to `[]?&int`
    1 | fn main(){
    2 |     mut a := []?&int{}
    3 |     a << none
      |          ~~~~
    4 |     dump(a[0])
    5 | }
```

### Reproduction Steps

run the following code:
```
fn main(){
	mut a := []?&int{}
	a << none
	dump(a[0])
}
```

### V version

V 0.3.4 a12e82a

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 34163ae.a12e82a
OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 8 cpus, 64bit, little endian,

getwd: C:\Users\Usuario\Desktop\Universidad\mag\v_test\07
vexe: C:\Program Files\v\v.exe
vexe mtime: 2023-06-22 14:13:17

vroot: contains spaces, value: C:\Program Files\v
VMODULES: OK, value: C:\Users\Usuario\.vmodules
VTMP: OK, value: C:\Users\Usuario\AppData\Local\Temp\v_0

Git version: git version 2.40.1.windows.1
Git vroot status: weekly.2023.24-45-ga12e82aa
.git/config present: true

CC version: cc (Rev6, Built by MSYS2 project) 13.1.0
thirdparty/tcc status: thirdparty-windows-amd64 e90c2620

**Comment by JalonSolov** [comment]
`none` is not a "real" value, it's a state.  That's why you can't append it.  You may be able to get around this by declaring a `?int` var, don't initialize it, then append that to the array.

This would be cheating the system, for no good reason I can think of, but you can try it.
