### ISSUE TITLE
TOML And YAML And MsgPack And SION V Native Support.

### ISSUE THREAD

**Issue by keito940** [vlang/v#1854]
TOML Document:[Here](https://github.com/toml-lang/toml)
YAML Document:[Here](https://yaml.org/spec/1.2/spec.html)
MessagePack Document:[Here](https://github.com/msgpack/msgpack/blob/master/spec.md)
SION Document:[Here](https://dankogai.github.io/SION/)

**Comment by dumblob** [comment]
Duplicate of https://github.com/vlang/v/issues/1732 ?

**Comment by keito940** [comment]
> Duplicate of #1732 ?

No. 
I didn't write it as a copy of # 1732.
I wanted to support serialization other than JSON.

**Comment by keito940** [comment]
XML

**Comment by dumblob** [comment]
>I wanted to support serialization formats other than JSON.

The discussion there is very general - it's about all formats you could imagine. Feel free to join the discussion there and mention all your formats if you wish to give them priority.

**Comment by lithic** [comment]
TOML is easier to use and more understandable than YAML

**Comment by keito940** [comment]
TOML Library Create Base Form https://github.com/cktan/tomlc99
Don't Support Encode.
...But I have send Encode Support Issue.

**Comment by keito940** [comment]
I found that it was impossible with TOMLC99, so I reorganized the code with reference to the code at https://github.com/BurntSushi/toml.

**Comment by keito940** [comment]
As a result of thinking about this, I decided to create a EBNF library and use that EBNF library to build a TOML library.

**Comment by dumblob** [comment]
> I decided to create a EBNF library ...

There are many existing and battle-tested ones - see bison, yacc, lex, flex, etc. Don't duplicate this effort, it would be a time loss.

**Comment by keito940** [comment]
> There are many existing and battle-tested ones - see bison, yacc, lex, flex, etc. Don't duplicate this effort, it would be a time loss.

Okay.

**Comment by nedpals** [comment]
Duplicate of #1732
