### ISSUE TITLE
runtime error, due to `type Abc = !int{}`, result types should be allowed only as function result types

### ISSUE THREAD

**Issue by spytheman** [vlang/v#18552]
**V doctor:**
```
V full version: V 0.3.4 2e9c469.ec35d76
OS: linux, Ubuntu 20.04.5 LTS
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i3-3225 CPU @ 3.30GHz

getwd: /v/vnew
vexe: /v/vnew/v
vexe mtime: 2023-06-25 06:51:54

vroot: OK, value: /v/vnew
VMODULES: OK, value: /home/delian/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.40.0
Git vroot status: weekly.2023.25-35-gec35d765
.git/config present: true

CC version: cc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg /v/misc/2023_06_25__09/a.v`
```v
type Abc = !int{}
dump( Abc(5) )

```

**What did you expect to see?**

A checker error, that I can not make an alias for a result type.
Alternatively, there could be another checker error, telling me, that I can not create a value from that type (they are allowed only as result types of functions, and have to be unwrapped right away, not stored/processed unwrapped).

**What did you see instead?**
```
7f19846f3ca0 : at ???: RUNTIME ERROR: invalid memory access
/tmp/v_1000/a.5584197016960007073.tmp.c:12922: by main
```

**Comment by Delta456** [comment]
I do not understand what is meant by:

> Alternatively, there could be another checker error, telling me, that I can not create a value from that type (they are allowed only as result types of functions, and have to be unwrapped right away, not stored/processed unwrapped).
