### ISSUE TITLE
Compilation in folder containing spaces and non latin characters fails on windows with tcc

### ISSUE THREAD

**Issue by roberto170** [vlang/v#18550]
### Describe the bug

dont compile a simple hello world in win 64

### Expected Behavior

hello world

### Current Behavior
```
==================
C:/Users/rober/AppData/Local/Temp/v_0/teste.10207024543187631367.tmp.c:7629: warning: cast between pointer and integer of different size
tcc: error: could not create 'C:\Users\rober\OneDrive\Área de Trabalho\programacao\vlang\teste.def': No such file or directory
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```
### Reproduction Steps
```v
fn main(){
	println("hello world!")
}
```

### V version

V 0.3.4 958e456

### Environment details (OS name and version, etc.)

Windows 10 Home Single Language
64 bits

**Comment by JalonSolov** [comment]
The default compiler, tcc, has problems with paths that have non-ASCII characters.

Please reinstall V in a path with only ASCII characters (and no spaces, to be sure), and see if this fixes your problem.

**Comment by roberto170** [comment]
v installed in c:\v
no whitespaces os non-ASCII chars

**Comment by roberto170** [comment]
thanks JalonSolov! problem is dir source 
v compile when source is in other dir
