### ISSUE TITLE
no source file or line # on panic

### ISSUE THREAD

**Issue by remdragon** [vlang/v#18562]
### Describe the bug

The following code panics with no source file / line #.

```
struct App{}

fn ( app &App ) myfunc4() {
	println( 'myfunc4' )
}

fn make[T](app &T) {
	$for method in T.methods {
		method.attrs[0]
	}
}

fn main() {
	mut app := App{}
	make( app )
}
```

it's trying to access method.attrs[0] but method.attrs is an empty array:

```
V panic: array.get: index out of range (i == 0, a.len == 0)
v hash: dd24e8a
D:/temp/v_0/no_line_number.8171938880383853888.tmp.c:6929: at _v_panic: Backtrace
D:/temp/v_0/no_line_number.8171938880383853888.tmp.c:6176: by array_get
D:/temp/v_0/no_line_number.8171938880383853888.tmp.c:12659: by main__make_T_main__App
D:/temp/v_0/no_line_number.8171938880383853888.tmp.c:12666: by main__main
D:/temp/v_0/no_line_number.8171938880383853888.tmp.c:13036: by wmain
0046f360 : by ???
0046f4c3 : by ???
7ff88a567614 : by ???
```

### Expected Behavior

report the panic happened at no_line_number.v:9

### Current Behavior

Neither source file nor line # is indicated in panic

### Reproduction Steps

v run no_line_number.v

### Additional Information/Context

I'm experimenting with metaprogramming and wanted to see what would happen if my functions had a variety of different metadata tags on them.

### V version

V 0.3.4 dd24e8a

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 dd24e8a
OS: windows, Microsoft Windows 10 Pro v19044 64-bit
Processor: 16 cpus, 64bit, little endian,

getwd: D:\Dropbox\cvs\gravscriptv
vexe: C:\cvs\v\v.exe
vexe mtime: 2023-06-26 05:17:13

vroot: OK, value: C:\cvs\v
VMODULES: OK, value: C:\Users\royce3\.vmodules
VTMP: OK, value: D:\temp\v_0

env VFLAGS: "-cc tcc"

Git version: git version 2.35.0.windows.1
Git vroot status: weekly.2023.25-36-gdd24e8a6
.git/config present: true

CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: cc --version
thirdparty/tcc status: thirdparty-windows-amd64 e90c2620

**Comment by JalonSolov** [comment]
Add the `-g` option to your V command line.

**Comment by remdragon** [comment]
thanks
