### ISSUE TITLE
redefinition/redeclare inside a module

### ISSUE THREAD

**Issue by esquerbatua** [vlang/v#1857]
**V version:** 0.1.18
**OS:** Ubuntu 18.04

**What did you do?**
v -lib constant/

**What did you expect to see?**
Compilation sucess
 
**What did you see instead?**
/home/x/test/constant/const.v:5:1: redefinition of `constant.URL`

Code:

> constant/const.v

`
module constant

const (
        URL = 'google.es'
)

pub fn main() {
        println(URL)
}
`

Same error with structs: 'constant/const.v:7:13: `constant.Test` redeclared'

'
module constant

struct Test {
        name string
}

pub fn main() {
        test := Test{'one'}
        println(test.name)
}
'

**Referenced issues: #749 #456**

**Comment by Henrixounez** [comment]
Please use `v build module constant/` as per this https://github.com/vlang/v/issues/1736#issuecomment-524615001 
An update on the help could be helpfull though.

**Comment by Danil-Lapirow** [comment]
I'm closing this issue because  `v build module constant/` is working for code in issue.

**Comment by esquerbatua** [comment]
A lot of thanks!

**Comment by esquerbatua** [comment]
Sorry @Henrixounez if you can review the last comment, the error remains.
Unless there is some other way to execute the compilation.
Thank you!

**Comment by Henrixounez** [comment]
Thanks @esquerbatua , indeed the way it worked was changed and `v build constant/` didn't worked but `v build constant` would have.

**Comment by esquerbatua** [comment]
Sorry, but the error remains @Henrixounez @medvednikov 

> constant/const.v:8:1: redefinition of `constant.URL`

**Comment by Henrixounez** [comment]
Have you updated your v ?

**Comment by esquerbatua** [comment]
Yes, and I get the same error with 'v build constant/' and 'v build constant', probably the error it's caused by the fix of the struct order?

**Comment by Henrixounez** [comment]
I have copied your code and put in in `./constant/constant.v` then run `v build constant` and have no errors.

**Comment by esquerbatua** [comment]
@Henrixounez I think he has had a misunderstanding, you tested the code in the first comment, and that with `v build constant` yes it works (now I edit the first comment so there are no errors).
The problem is when you put some import in the file, like in [this comment](https://github.com/vlang/v/issues/1857#issuecomment-528289780)

**Comment by Henrixounez** [comment]
Yes, i have tested this one but have no problems.

**Comment by esquerbatua** [comment]
A lot of thanks! All working.
