### ISSUE TITLE
If expression with different types in branches results in invalid C

### ISSUE THREAD

**Issue by Yardanico** [vlang/v#1862]
**V version:** https://github.com/vlang/v/commit/86d95fcd22b05aa1cd6fdba252da6b9c150277f1
**OS:** Arch Linux

**What did you do?**
Tried to compile
```v
fn main() {
    ch := `\0`
    got := if true {
        'end of line'
    } else {ch}
    println(got)
}
```

**What did you expect to see?**
A proper compiler error message because string and byte are different types
 
**What did you see instead?**
```
dian@pc ~/p/vtest> v -debug run test2.v
C compiler=cc
/home/dian/projects/vtest/test2.tmp.c: In function ‘main’:
/home/dian/projects/vtest/test2.tmp.c:3515:50: error: type mismatch in conditional expression
 3515 | byte got= ( 1 ) ? ( tos2((byte*)"end of line") ) : ( ch ) ;
      |                                                  ^
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

**Comment by Danil-Lapirow** [comment]
Match is better in most cases.
```v
fn main() {
    ch := `\0`
    got := match true {
		true => { 'end of line'}
		else => {ch}
	}
    println(got)
}```
Output:
```
main.v:5:14: expected type `string`, but got `byte`
```

**Comment by Yardanico** [comment]
@Danil-Lapirow well, the point here is that the compiler should always write an error message instead of generating invalid C code and feeding it to the C compiler

**Comment by ntrel** [comment]
> Match is better in most cases

No, binary matching should always use of/else.
