### ISSUE TITLE
Compiler complains about a function with match even if it always returns a value

### ISSUE THREAD

**Issue by Yardanico** [vlang/v#1865]
**V version:**  https://github.com/vlang/v/commit/ec61821bf7fd898f536fd1dd57b11ef40d8d2ce9
**OS:**  Arch Linux

**What did you do?**
Tried to run
```v
fn test(val string) f64 {
    for {
        match val {
            'a' => {return 3}
            else => {return 5} 
        }
    }
}

fn main() {
    test('b')
}
```

I think it's pretty clear here that `return` statement will be ALWAYS executed before the for loops ends, so there's no point in requiring to add another return statement after the endless loop.

**What did you expect to see?**
Program successfully compiled without any output
 
**What did you see instead?**
```
/home/dian/projects/v-mathexpr/tt.v:10:2: test must return "f64"
```

**Comment by ntrel** [comment]
> return statement will be ALWAYS executed before the for loops ends

So why have a for loop?

**Comment by gslicer** [comment]
This (a bit more realistic) example runs only if the comment is uncommented:

```

module main

fn test(val string) f64 {
    for val != '' {
        match val {
            'a' => {return 3}
            else => {return 5} 
        }
    }
    // return 0
}

fn main() {
    print(test('b'))
}
```

So this proofs this issue is a real one in my opinion.

**Comment by Henrixounez** [comment]
In the first example, it could be plausible (Even though the infinite for is not very useful).
For the second example that have been provided in the example, you can have the string `val` being empty by calling `test('')`, therefore you would need a return at the end of the function.

**Comment by serkonda7** [comment]
Works fine with latest V.
The updated snippet:
```v
fn test(val string) f64 {
    for {
        match val {
            'a' {return 3}
            else {return 5}
        }
    }
}

fn main() {
    println(test('b'))
}
```
