### ISSUE TITLE
vweb linux template 20% cpu usage

### ISSUE THREAD

**Issue by teddysasmita** [vlang/v#18695]
### Describe the bug

using v's web project template in Linux. Memory and CPU usage is 15% - 20% in idle.

### Expected Behavior

minimum memory and cpu usage in idle

### Current Behavior

Memory and CPU usage is 15% - 20% in idle.

### Reproduction Steps

$ v new [project-name] web
$ v .
run the executable

### V version

V 0.3.4 02c3825

### Environment details (OS name and version, etc.)

MX Linux 21
XFCE

**Comment by medvednikov** [comment]
No longer an issue for you?

**Comment by teddysasmita** [comment]
It is no longer an issue with V version 0.4. Thanks V development team.
