### ISSUE TITLE
Reactjs style for building GUI app?

### ISSUE THREAD

**Issue by leedstyh** [vlang/v#187]
Hi,

Any plan to support reactjs ( or Flutter ) style for building GUI app?

**Comment by ansarizafar** [comment]
Svelte https://svelte.dev would be much better than React.

**Comment by medvednikov** [comment]
Yes, this would be nice.

A bit tricky to build this on top of native toolkit APIs.

**Comment by hamad-almamari** [comment]
Please keep V away from JAVASCRIPT Madness.

**Comment by medvednikov** [comment]
I'm not a fan of JavaScript myself :) 

This has nothing to do with JavaScript. The question is about using a more modern style for the GUI library.

Native iOS/Android support is coming later this year.

**Comment by ansarizafar** [comment]
Would it be possible to develop a full stack progressive web app with V without using JavaScript like Blazor https://www.youtube.com/watch?v=y7LAbdoNBJA or new rust web frameworks?

**Comment by medvednikov** [comment]
> Would it be possible to develop a full stack progressive web app with V without using JavaScript like Blazor

Yes.

**Comment by ansarizafar** [comment]
Good to hear that. I am excited. A Svelte https://svelte.dev like full stack web framework in V would be a game changer.

**Comment by medvednikov** [comment]
Yes, I'm excited as well. Time to free the world from JavaScript oppression :)

**Comment by medvednikov** [comment]
Apple just released SwiftUI, looks interesting.

I like the declarative approach and will use it in V ui.

**Comment by diamondburned** [comment]
Depends on the approach I'm seeing here. Svelte "compiles" to JavaScript, which the client runs. "Rust web frameworks" are server-side rendered, similar to PHP. Both are different and has different purposes. Personally I'd prefer the "Rust web frameworks" approach.

**Comment by ansarizafar** [comment]
Rust also has this https://github.com/DenisKolodin/yew Server side only framework can't be used for more responsive UIs rich user interactions, client side validation, animations, state management etc.

**Comment by pyros2097** [comment]
If V compiles to wasm then its even easier to rid this world of javascript.

**Comment by ansarizafar** [comment]
I had suggested the same on slack.

**Comment by pyros2097** [comment]
Anyways golang has a really good frontend framework called [vecty](https://github.com/gowasm/vecty) which is a react like framework in golang. I think the first step would be get a framework like this setup after the wasm target is completed. It will help in exploring to build a common UI interface across all platforms.
There is also [ebiten](https://github.com/hajimehoshi/ebiten) which actually works on all platform. The same codebase.
Anyone here want to take a shot at building the wasm target? I think it shouldn't be too difficult.

**Comment by nedpals** [comment]
A proper syntax has been selected for V UI. Closed
