### ISSUE TITLE
C error: cannot convert 'int' to 'struct main__Heap_T_int'

### ISSUE THREAD

**Issue by StroveLight** [vlang/v#18707]
### Describe the bug

I get a compiler error (C error) with my code, it appears only when i define the function insert

### Expected Behavior

Some V error/warning if i did something wrong

### Current Behavior

`v -cg .` output:
```
C:/Users/Usuario/AppData/Local/Temp/v_0/r01.1788485607081336192.tmp.c:502: warning: WINVER redefined
C:/Users/Usuario/AppData/Local/Temp/v_0/r01.1788485607081336192.tmp.c:6938: warning: implicit declaration of function 'tcc_backtrace'
C:/Users/Usuario/AppData/Local/Temp/v_0/r01.1788485607081336192.tmp.c:7712: warning: assignment from incompatible pointer type
C:/Users/Usuario/AppData/Local/Temp/v_0/r01.1788485607081336192.tmp.c:7712: warning: assignment makes pointer from integer without a cast
C:/Users/Usuario/AppData/Local/Temp/v_0/r01.1788485607081336192.tmp.c:7712: warning: cast between pointer and integer of different size
C:/Users/Usuario/AppData/Local/Temp/v_0/r01.1788485607081336192.tmp.c:12721: error: cannot convert 'int' to 'struct main__Heap_T_int'
builder error:
==================
C error. This should never happen.
```

### Reproduction Steps

Both of the following codes cause the problem:

FIrst one (calls the function)
```
pub struct Heap[T] {
mut:
    array []&T
}

fn (mut h Heap[T]) insert(mut element &T, pos int) {
    h[pos] = element
}

fn main(){
    mut h := &Heap[int]{
        array: []&int{cap: 10}
    }
    mut a := 3
    h.insert(mut &a, 0)
    dump(h)
}


```

Second one (only function declaration)
```
pub struct Heap[T] {
mut:
    array []&T
}

fn (mut h Heap[T]) insert(mut element &T, pos int) {
    h[pos] = element
}

fn main(){
    mut h := &Heap[int]{
        array: []&int{cap: 10}
    }
    dump(h)
}

```

### V version

V 0.3.4 499d052

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 34163ae.499d052
OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 8 cpus, 64bit, little endian,

getwd: C:\Users\Usuario\Desktop\Universidad\mag\v_test\r01
vexe: C:\Program Files\v\v.exe
vexe mtime: 2023-06-28 20:04:45

vroot: contains spaces, value: C:\Program Files\v
VMODULES: OK, value: C:\Users\Usuario\.vmodules
VTMP: OK, value: C:\Users\Usuario\AppData\Local\Temp\v_0

Git version: git version 2.40.1.windows.1
Git vroot status: weekly.2023.25-56-g499d0526
.git/config present: true

CC version: cc (Rev6, Built by MSYS2 project) 13.1.0
thirdparty/tcc status: thirdparty-windows-amd64 e90c2620

**Comment by felipensp** [comment]
Why `h[pos]`? Should it not be `h.array[pos]`?

**Comment by JalonSolov** [comment]
You can't use `array` as a variable name, but otherwise yes, it should be `h.<field name>[pos]`.

**Comment by Delta456** [comment]
The above code now gives a proper error with the latest version of V.

```
file.v:7:6: error: type `mut Heap` does not support slicing
    5 | 
    6 | fn (mut h Heap[T]) insert(mut element &T, pos int) {
    7 |     h[pos] = element
      |      ~~~~~
    8 | }
    9 |
```
