### ISSUE TITLE
Command "v -live run ." fails on Windows

### ISSUE THREAD

**Issue by dmitryuck** [vlang/v#18716]
### Describe the bug

when I run this command `v -live run .` on Windows 11, I get an error:

```
recompilation error:
v: unknown command `hirdparty`
Run  v help  for usage.

errors while compiling .
```

looks like it parses incorrect folder name, because I see a typo in  `hirdparty` from message, no t letter at the beginning

### Expected Behavior

should run in live mode with auto-reload the page

### Current Behavior

can not run with current command

### Reproduction Steps

just take any project and try to run on Windows

### V version

V 0.3.5 015ccc2

### Environment details (OS name and version, etc.)

V 0.3.5 015ccc2
PS D:\Projects\Forum\server> v doctor
V full version: V 0.3.5 7ab1109.015ccc2
OS: windows, Microsoft Windows 11 Home v22000 64-bit
Processor: 6 cpus, 64bit, little endian,

getwd: D:\Projects\Forum\server
vexe: D:\Programs\v\v.exe
vexe mtime: 2023-06-30 06:22:53

vroot: OK, value: D:\Programs\v
VMODULES: OK, value: C:\Users\monkg\.vmodules
VTMP: OK, value: C:\Users\monkg\AppData\Local\Temp\v_0

Git version: git version 2.37.0.windows.1
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false

CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: cc --version
thirdparty/tcc: N/A

**Comment by V0idMatr1x** [comment]
> ### Describe the bug
> when I run this command `v -live run .` on Windows 11, I get an error:
> 
> ```
> recompilation error:
> v: unknown command `hirdparty`
> Run  v help  for usage.
> 
> errors while compiling .
> ```
> 
> looks like it parses incorrect folder name, because I see a typo in `hirdparty` from message, no t letter at the beginning
> 
> ### Expected Behavior
> should run in live mode with auto-reload the page
> 
> ### Current Behavior
> can not run with current command
> 
> ### Reproduction Steps
> just take any project and try to run on Windows
> 
> ### Possible Solution
> _No response_
> 
> ### Additional Information/Context
> _No response_
> 
> ### V version
> V 0.3.5 [015ccc2](https://github.com/vlang/v/commit/015ccc2a7f5c42768d34bbf83be136092f5a155f)
> 
> ### Environment details (OS name and version, etc.)
> V 0.3.5 [015ccc2](https://github.com/vlang/v/commit/015ccc2a7f5c42768d34bbf83be136092f5a155f) PS D:\Projects\Forum\server> v doctor V full version: V 0.3.5 [7ab1109](https://github.com/vlang/v/commit/7ab11097be7aa28c4268a08ac59630f1981c88b0).015ccc2 OS: windows, Microsoft Windows 11 Home v22000 64-bit Processor: 6 cpus, 64bit, little endian,
> 
> getwd: D:\Projects\Forum\server vexe: D:\Programs\v\v.exe vexe mtime: 2023-06-30 06:22:53
> 
> vroot: OK, value: D:\Programs\v VMODULES: OK, value: C:\Users\monkg.vmodules VTMP: OK, value: C:\Users\monkg\AppData\Local\Temp\v_0
> 
> Git version: git version 2.37.0.windows.1 Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git .git/config present: false
> 
> CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified. cmd: cc --version thirdparty/tcc: N/A

> I currently have the same error after applying `[live]` to `main()`.

<img width="731" alt="image" src="https://github.com/V0idMatr1x/run_exe/assets/88049272/36444547-e1a5-44b1-a7c2-6eb1a7a103e7">

**Comment by V0idMatr1x** [comment]
After updating V and recompiling, I get this error.

```
Unhandled Exception 0xC0000005
print_backtrace_skipping_top_frames is not implemented
signal 11: segmentation fault
print_backtrace_skipping_top_frames is not implemented
```

**Comment by dmitryuck** [comment]
I see an **args** like this:
```
['-cc', 'D:Programs
', 'hirdparty', 'cc', 'cc.exe', '-sharedlive', '-shared', '-o', 'C:\\Users\\monkg\\.cache/tmp.1..', '.']
```
