### ISSUE TITLE
Explicit error processing

### ISSUE THREAD

**Issue by sirkon** [vlang/v#1872]
In Go usage it turned to be a good practice to wrap errors in some way. Something like

```go
return errors.Wrap(err, "doing something")
```

Thus, it would be nice to have explicit error variable for the same thing. Example:

```
file := os.open('file.name') or err {
     return errors.wrap(err, 'doing something')
}
```

**Comment by spytheman** [comment]
You can already do:
```v
file := os.open('file.name') or {
     return error( 'The error was: $err')
}
```

**Comment by sirkon** [comment]
This should be explicit I believe.

**Comment by dumblob** [comment]
>This should be explicit I believe.

That's a topic for discussion. Explicit is **usually** better (but there are exceptions, as always). On the other hand, if this is the only thing in *V* which will be implicit, then it's not a big issue.

**Comment by sirkon** [comment]
> That's a topic for discussion. Explicit is **usually** better (but there are exceptions, as always). On the other hand, if this is the only thing in _V_ which will be implicit, then it's not a big issue.

The problem is there're options who would look exactly the same.

**Comment by medvednikov** [comment]
Can you explain what you mean by explicit?

Write now strings are used for errors, but they will be replaced with a new type `error`.

**Comment by sirkon** [comment]
> Can you explain what you mean by explicit?
> 
> Write now strings are used for errors, but they will be replaced with a new type `error`.

explicit error value to deal with:

```v
notification(tag, "dest1") or err {
    logger.warning().err(err).msg('failed to notify dest1')
    return
}
```

**Comment by medvednikov** [comment]
So you mean `or err` instead of the magic `err` variable?

There's always only one `err`, so I don't really see the point.

`or err` is also magic.
