### ISSUE TITLE
Comp-time type inference in generic function tries all (non-matching) cases

### ISSUE THREAD

**Issue by phoreverpheebs** [vlang/v#18721]
### Describe the bug

When using a generic function with type `T` and then inferring the type in comp-time `$if` statements, the checker doesn't short-circuit on the first match and attempts to go down all routes.

For example, have a generic that, at compile time, matches the type to a `u64` or `[]u64`. The path `$if value is []u64` should therefore be able to safely access the `.len` attribute of the array when provided a `[]u64` value, but when inputting a `u64` the checker fails to invalidate the `[]u64` path and in later steps of compilation an error is thrown when `.len` is being accessed in a `u64`.

This also has implications when we want to call a `$compile_error` with incorrect input types as the compile error occurs even when a valid type is passed.

### Expected Behavior

No error

### Current Behavior

For the given reproduction code:
```
issue.v:10:18: error: `u64` has no property `len`
    8 |         }
    9 |     } $else $if value is []u64 {
   10 |         if value.len == 0 {
      |                  ~~~
   11 |             'empty u64 array'
   12 |         } else {
```

### Reproduction Steps

```v
fn evaluate[T](value T) string {
    return $if value is u64 {
        if value == 0 {
            'u64 = 0'
        } else {
            'u64 > 0'
        }
    } $else $if value is []u64 {
        if value.len == 0 {
            'empty u64 array'
        } else {
            'u64 array with elements'
        }
    } $else {
        'unhandled'
    }
}

fn main() {
    dump(evaluate(u64(1)))
    dump(evaluate(u64(0)))
}
```

### V version

V 0.3.5 015ccc2

### Environment details (OS name and version, etc.)

```
OS: linux, "Manjaro Linux"
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 9 4900HS with Radeon Graphics
CC version: cc (GCC) 13.1.1 20230429
```

**Comment by phoreverpheebs** [comment]
The issue seems to stem from [vlib/v/checker/comptime.v](https://github.com/vlang/v/blob/master/vlib/v/checker/comptime.v) (starting on line 680), where even though the if block accepts `cond.left` to be `ast.Ident, ast.SelectorExpr, ast.TypeNode`, only `ast.SelectorExpr` is implemented for a `cond.right` of `ast.ComptimeType` (also both cases of `cond.left is ast.TypeNode` are taken care of already).

Please correct me if I'm wrong, but from what I see we just have to add in comparison handlers for both `ast.Ident` cases and one more for `cond.left is ast.SelectorExpr && cond.right is ast.TypeNode`.

I'm willing to work on it if no one else wants to!

**Comment by Delta456** [comment]
Feel free to work on this
