### ISSUE TITLE
u8.ascii_str() does not support Hebrew

### ISSUE THREAD

**Issue by changhz** [vlang/v#18760]
### Describe the bug

u8.ascii_str() does not support Hebrew

### Expected Behavior

display a Hebrew letter

### Current Behavior

displays �

### Reproduction Steps

``` v
fn main() {
  alefbet := 'אבגדהוזחטיכלמנסעפצקרשתםןףץך'
  println(alefbet[0].ascii_str()) // displays �
}
```

### V version

0.4.0 df3c85e

### Environment details (OS name and version, etc.)

macOS, 11.7.7
CC version: Apple clang version 13.0.0 (clang-1300.0.29.30)

**Comment by JalonSolov** [comment]
It's in the name... **ascii**_str... ASCII codes do not cover Hebrew characters.

If you want the Hebrew characters, you need to print `rune`s instead, as in
```v
fn main() {
  alefbet := 'אבגדהוזחטיכלמנסעפצקרשתםןףץך'
  println(alefbet.runes()[0]) // displays א
}
```
(And yes, this is correct, as Hebrew is right-to-left, not left-to-right.)

**Comment by changhz** [comment]
@JalonSolov thank you so much
