### ISSUE TITLE
`fn main() {}` is no longer required in simple one file programs

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#188]
Today I re-wrote all deployment scripts from Bash to V.

I think it could be a common thing, so I decided to make one file programs a bit less verbose. Just like in Python, Swift, and many other languages you can now do

`println('hello world')`

instead of

```
fn main() {
    println('hello world')
}
```

This will only work if there's only one file, so you won't have Python's `if __name__ == "__main__":` :)

This makes learning/playing with the language a bit easier as well.

**Comment by Ivo-Balbaert** [comment]
Doesn't yet work for me in v0.0.7 on Linux: panic: test.v: 1 - unexpected token println

**Comment by medvednikov** [comment]
It'll be live in 0.0.8.

I felt like this was a big change, and wanted to get some feedback. Seems like nobody's against it :)

**Comment by cjmxp** [comment]
I think it's easier to solve one thing in the only way.

**Comment by cjmxp** [comment]
When is the Windows binary version scheduled to be released?

**Comment by medvednikov** [comment]
> When is the Windows binary version scheduled to be released?

Tomorrow. Please use Slack/forum or create new issues for unrelated questions.

**Comment by medvednikov** [comment]
Live in 0.0.8 and in the playground.

**Comment by medvednikov** [comment]
Documentation has been updated. All examples no longer have `fn main() { }`.
