### ISSUE TITLE
Remove rune type and use u32 instead

### ISSUE THREAD

**Issue by dmitryuck** [vlang/v#18808]
### Describe the feature

since we removed a byte type and become using u8 instead
a suggestion is to remove `rune` and use u32 instead
also, add a struct Rune with static methods for converting and other stuff for runes especially

### Use Case

`rocket := `🚀`  // automatically set to u32`

if we want to get data from Rune we would use

`Rune.bytes(rocket) == [u8(0xf0), 0x9f, 0x9a, 0x80]`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.3.5 015ccc2

### Environment details (OS name and version, etc.)

Windows, any OS

**Comment by JalonSolov** [comment]
Runes are UTF-8, which can be anywhere from 1 to 4 bytes.  They are not a fixed u32 in size.  Even if the current implementation may treat them that way, that is not what they are.
