### ISSUE TITLE
make a unified lambda/anonymous/local function definition

### ISSUE THREAD

**Issue by dmitryuck** [vlang/v#18809]
### Describe the feature

since we adding a lambda function definition to v language which looks like

`arr.sort(|a, b| a > b)`

or 

```
arr.sort(|a, b| { 
// some code here
 a > b
})
```

a suggestion to make a definition of lambda/anonymous/local functions provided by one way

instead of

```
func := fn (w string) string {
	return w.to_upper()
}

upper_fn := words.map(func)
```

use

```
func := |w string| string {
	return w.to_upper()
}

upper_fn := words.map(func)
```

```
println(filter('Hello world', |s string| string {
	return s.to_upper()
}))
```

### Use Case

use case provided above

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.3.5 015ccc2

### Environment details (OS name and version, etc.)

Windows, any OS

**Comment by JalonSolov** [comment]
Regular functions are not lambdas, and don't have to look like them.  Their is a very real difference, so should look different.
