### ISSUE TITLE
cannot use `any` type

### ISSUE THREAD

**Issue by Ilir-Liburn** [vlang/v#18815]
### Describe the bug

It is not possible to declare variable of `any` type

 

### Expected Behavior

No error at compile time

### Current Behavior

error: cannot use `any` type here, `any` will be implemented in V 0.4
    1 | v := any(123)
      |      ~~~

### Reproduction Steps

v := any(123)

### Additional Information/Context

V is in v. 0.4, error message is misleading (V 0.5 perhaps)?

### V version

0.4

### Environment details (OS name and version, etc.)

Windows x64

**Comment by JalonSolov** [comment]
Actually, that error message needs to be completely removed.  `any` is not going to be implemented.  This was decided before 0.4 was released, but this particular message was missed.

@medvednikov ^^

**Comment by Ilir-Liburn** [comment]
Hello,

if there is any possibility, please implement any type. As I see it, you have at least two choices:

1.  To use NaN boxing: advantage is that same bytes (8-16 depending on the platform) can be used to store value. Disadvantage is that some platforms are using pointer tagging, requiring some bit shifts (last time I tried to implement it)
2.  To use pointer tagging: this solves NaN boxing issue, but requires memory allocation (pool) for any type other than pointer. Disadvantage is that bytes holding value are always pointers (pointer to some type).

Other ways like using structures, switches, etc. I don't recommend.
