### ISSUE TITLE
Identifier expected when an optional field is present in query (`!= none`)

### ISSUE THREAD

**Issue by CGenie** [vlang/v#18847]
### Describe the bug

I have this code:

```v
import db.pg

struct Item {
	somefield ?f64
}

fn main() {
	db := pg.connect(pg.Config{
		host: 'localhost'
		user: 'user'
		dbname: 'db'
	})!

	defer {
		db.close()
	}

	results := sql db {
		select from Item where somefield != none
	}!

	println('${results}')
}
```

### Expected Behavior

Compile without errors.

### Current Behavior

`v run .` throws this:

```
/tmp/v_1000/bug-2.5404810105065252960.tmp.c:17565: error: identifier expected
```

The `.c` file has these contents:
```c
        if (_t4.is_error) {
                panic_result_not_set(IError_name_table[_t4.err._typ]._method_msg(_t4.err._object));
        }
                        _option_f64 _t8 = (_option_f64){ .state=2, .err=_const_none__, .data={EMPTY_STRUCT_INITIALIZATION} };
                        else {
                Array_Array_orm
```
so an assignment right before the `else` clause.

### Reproduction Steps

`v run .` on the above file.

### V version

V 0.4.0 045adb6

### Environment details (OS name and version, etc.)

V full version: V 0.4.0 045adb6
OS: linux, Ubuntu 23.04
Processor: 8 cpus, 64bit, little endian, AMD Ryzen 7 4700U with Radeon Graphics

getwd: /data/git-work/sourcehut/ICM/2023-point-stat-analysis/bug-2
vexe: /data/git-work/github/VLANG/v/v
vexe mtime: 2023-07-11 17:12:40

vroot: OK, value: /data/git-work/github/VLANG/v
VMODULES: OK, value: /home/przemek/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.39.2
Git vroot status: weekly.2023.28-8-g045adb66
.git/config present: true

CC version: cc (Ubuntu 12.2.0-17ubuntu1) 12.2.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by felipensp** [comment]
Is this is issue yet reproducible with latest version?

**Comment by CGenie** [comment]
Ah, no this compiles fine now, thanks!

**Comment by felipensp** [comment]
Closing. Already fixed. Thanks.
