### ISSUE TITLE
programming microcontroller and SBC

### ISSUE THREAD

**Issue by ghost** [vlang/v#1886]
compiler and standard library support for programming microcontrollera and single board computes.

**Comment by dumblob** [comment]
Duplicate of https://github.com/vlang/v/issues/590 ?

**Comment by lithic** [comment]
@dumblob , i don't think so

**Comment by lithic** [comment]
This is a matter of running program in a resource constraint environment

**Comment by lithic** [comment]
@medvednikov ?

**Comment by lithic** [comment]
@medvednikov ?

**Comment by nedpals** [comment]
Closed. Will be redirecting the issue to #4115 as it has more information than this one.
