### ISSUE TITLE
Method string.int() returns numbers for specific characters (which aren't numbers)

### ISSUE THREAD

**Issue by Spartlink** [vlang/v#18875]
### Describe the bug

It is weird that we can convert letters or other special characters to int without any error occuring or anything else.

Code: https://vosca.dev/p/4ec57834b1

```v
mut ascii_characters := [' ', '!', '\"', '#', '\$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '^', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~']
mut special_characters := [':', ';', '<', '=', '>', '?', '@', 'X', 'Y', 'Z', '[', '\\', ']', '^', '_', '`']
mut c := ":;<=>?@XYZ[\\]^_`"
mut d := '!X'

for i in ascii_characters {
	print(i.int())
}
print('\n')

for i in special_characters {
	print(i.int())
}
print('\n')

println(c.int())
println(d.int())
```

### Expected Behavior

The int method should return 0 for every character that isn't a number or output an error/warning.

### Current Behavior

Output:

```
00000000000000000123456789345678900000000000000000000000123456709000000000000000000000000000000
3456789123456709
2147483647
0
```

The int method treats certain specific characters just like numbers, these characters :
```
:;<=>?@XYZ[\]^`
```
are treated, respectively, as those numbers : 
```
345678912345679
```

These characters are n° 58 to 64 and n°88 to 96 in the ASCII table, except for the underscore which isn't affected by the weird conversion : because of its separator properties, the int method skips it

### Reproduction Steps

Using the int method on any of these special characters will transform them into the corresponding number (Code: https://vosca.dev/p/4ec57834b1)

### Possible Solution

Not really a solution but the highly probable source of the problem :

Looking through the int method in the source code, we found a few clues : 
Lines 110 to 130 of vlib\strconv\atoi.v, the code uses a series of subtractions to convert strings of numbers and letters into integers. 
```
// get the 0-9 digit
c -= 48 // subtract the rune `0`

// check if we are in the superior base rune interval [A..Z]
if c >= base {
	c -= 7
}

// check if we are in the superior base rune interval [a..z]
if c >= base {
	c -= 32 // subtract the `A` - `0` rune to obtain the value of the digit
}
```
By applying the subtractions to the ASCII n° of each special characters, we can find the values obtained before (see attached spreadsheet)

[special_characters.xlsx](https://github.com/vlang/v/files/12061265/special_characters.xlsx)

### V version

V 0.4.0 b06811c

### Environment details (OS name and version, etc.)

Tested on playground and current version (V 0.4.0 b06811c)
```
V full version: V 0.3.3 e738d67 (playground but same bug on V0.4.0 Windows 10 education)
OS: linux, Debian GNU/Linux 11 (bullseye) (VM)
Processor: 1 cpus, 64bit, little endian, Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz

getwd: /home/admin/playground
vexe: /home/admin/v/v
vexe mtime: 2023-04-29 19:43:52

vroot: OK, value: /home/admin/v
VMODULES: OK, value: /.vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.30.2
Git vroot status: Error: fatal: detected dubious ownership in repository at '/home/admin/v'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v
.git/config present: true

CC version: cc (Debian 10.2.1-6) 10.2.1 20210110
thirdparty/tcc status: Error: fatal: detected dubious ownership in repository at '/home/admin/v/thirdparty/tcc'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v/thirdparty/tcc
 Error: fatal: detected dubious ownership in repository at '/home/admin/v/thirdparty/tcc'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v/thirdparty/tcc

```

**Comment by JalonSolov** [comment]
Those `detected dubious ownership in repository` would really concern me...

**Comment by Spartlink** [comment]
> Those `detected dubious ownership in repository` would really concern me... (nothing to do with the reported bug, I know, but definitely concerning)

That is the playground issue auto-fill, when reporting code as a bug from the playground. Let me know if I can help with anything
