### ISSUE TITLE
`net.http` function `read_cookies` and `read_set_cookies` expect wrong parameter.

### ISSUE THREAD

**Issue by Coachonko** [vlang/v#18874]
### Describe the bug

`net.http` function `read_cookies` and `read_set_cookies` expect `map[string][]string`.

`Header` has two `map[string][]string` fields, both are private. This makes it impossible to pass these fields to these functions.

Currently, there is no way for users to parse `Set-Cookie` headers into `http.Cookie`

### Expected Behavior

`net.http` function `read_cookies` and `read_set_cookies` should expect `Header` instead.

### Current Behavior

`net.http` function `read_cookies` and `read_set_cookies` expect `map[string][]string`.

### Reproduction Steps

No reproduction steps necessary

### V version

`Current V version: V 0.4.0 b06811c, timestamp: 2023-07-14 20:44:01 +0300`

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.0 ee4150f.b06811c
OS: linux, Linux version 5.14.0-284.18.1.el9_2.x86_64 (mockbuild@euro.kojibuilder101) (gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4), GNU ld version 2.35.2-37.el9) #1 SMP PREEMPT_DYNAMIC Fri Jun 23 16:35:13 CEST 2023
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz

getwd: /home/coachonko/Documents/projects/vlang/sessions
vexe: /home/coachonko/.local/lib64/v/v
vexe mtime: 2023-07-15 12:50:56

vroot: OK, value: /home/coachonko/.local/lib64/v
VMODULES: OK, value: /home/coachonko/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.39.3
Git vroot status: weekly.2023.27-73-gb06811cb
.git/config present: true

CC version: cc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

**Comment by JalonSolov** [comment]
You could always call the provided [new_header_from_map](https://modules.vlang.io/net.http.html#new_header_from_map) function, since that's what it is for.

**Comment by JalonSolov** [comment]
I'd rather make those functions match the descriptions, than make the Header fields public.  In other words, the first parameter should be changed to `h Header`.

"Breaking" change, perhaps, but better.
