### ISSUE TITLE
or {dump(err)} occurred error: incomplete type 'void' is not assignable

### ISSUE THREAD

**Issue by carpedil** [vlang/v#18870]
### Describe the bug

When practicing custom errors, I wrote the following code according to the instructions in [Tutorial](https://docs.vosca.dev/concepts/error-handling/custom-errors.html).
```v
module main

fn main() {
	try_open('/tmp') or {dump(err)}
}


struct PathError {
	Error 
	path string 
}

fn (pe PathError) msg() string {
	return 'Failed to open path: ${pe.path}'
}

fn try_open(path string) ? {
	return PathError{
		path: path
	}
}
```
 In or block, I used the dump() function and the result was running 'v run .'The error occurred

### Expected Behavior

I thought the dump() function would print more detailed error information.

### Current Behavior
```
➜ v_bugs (master) ✗ v -cg run . 
/tmp/v_502/v_bugs.14950845255838070213.tmp.c:12574:21: error: incomplete type 'void' is not assignable
                *(void*) _t1.data =  _v_dump_expr_IError(_SLIT("./src/main.v"), 4, _SLIT("err"), err);
                ~~~~~~~~~~~~~~~~~ ^
1 error generated.
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```
### Reproduction Steps

`v run .`

### V version

V 0.4.0 b06811c

### Environment details (OS name and version, etc.)

V full version: V 0.4.0 b06811c
OS: macos, macOS, 13.4.1, 22F82
Processor: 8 cpus, 64bit, little endian, Apple M1

getwd: /Users/roo/Desktop/workspace/vlang/v_bugs
vexe: /usr/local/v/v
vexe mtime: 2023-07-14 22:01:36

vroot: OK, value: /usr/local/v
VMODULES: OK, value: /Users/roo/.vmodules
VTMP: OK, value: /tmp/v_502

Git version: git version 2.38.1
Git vroot status: weekly.2023.28-27-gb06811cb
.git/config present: true

CC version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
thirdparty/tcc status: thirdparty-macos-amd64 46662e20

**Comment by yuyi98** [comment]
`fn try_open(path string) ? {` should be `fn try_open(path string) ! {`.

**Comment by carpedil** [comment]
ok,thanks ,but i really want to know why this code `fn try_open(path string) ! {`  works  for  dump(err) without return

**Comment by yuyi98** [comment]
This case is considered a return expression type, these really need to detect errors.
