### ISSUE TITLE
image and video processing

### ISSUE THREAD

**Issue by ghost** [vlang/v#1887]
standard library support for image and video processing

**Comment by gslicer** [comment]
you mean that porting existing c-libs for that matter to v right?

**Comment by Delta456** [comment]
He means to re-write or make them from scratch. A pure V library.

**Comment by lithic** [comment]
@medvednikov ?

**Comment by lithic** [comment]
@medvednikov ?

**Comment by Delta456** [comment]
You should wait for V to get a stable release

**Comment by dumblob** [comment]
and maybe donate (see the button up there in this GitHub repository) to get there quicker.

**Comment by gslicer** [comment]
I think the acceptence for donations via Patreon would significantly increase if all funds would be shared among contributers (perhaps based on the number of accepted commits?) and not go just to the founder himself (who was criticised for that anyway since the beginning)

**Comment by dumblob** [comment]
@glicer I just mentioned it as another/additional option. Nothing more nothing less. I didn't mean starting discussion about donations whatsoever here. I'm pretty sure there are better places than this rather technical tracker for such discussions :wink:.
