### ISSUE TITLE
MSVC doesn't support fixed array of structs as const

### ISSUE THREAD

**Issue by ArtemkaKun** [vlang/v#18892]
### Describe the bug

CI checks for MSVC in #18889 fail. Can anybody on Windows with MSVC confirm this issue and fix it?

### Expected Behavior

No errors

### Current Behavior

```
C:\Users\runneradmin\AppData\Local\Temp\v_0\v_up.exe.tmp.c(10854): error C2099: initializer is not a constant

C:\Users\runneradmin\AppData\Local\Temp\v_0\v_up.exe.tmp.c(10855): error C2099: initializer is not a constant
```

### Reproduction Steps

```v
struct Uint128 {
mut:
	lo u64
	hi u64
}

const zzz_test = [Uint128{1,2}, Uint128{3,4}]!
dump(zzz_test)
```

### Possible Solution

Don't use Windoze + MSVC, use normal OS like Linux with a normal C compiler

### V version

V 0.4.0 7f8749a.8c8d21d

### Environment details (OS name and version, etc.)

not related

**Comment by spytheman** [comment]
`const test = [1, 2, 3]!` is fine

**Comment by ArtemkaKun** [comment]
Thanks for help, will update reproduction steps tomorrow

**Comment by spytheman** [comment]
```v
struct Uint128 {
mut:
	lo u64
	hi u64
}

const zzz_test = [Uint128{1,2}, Uint128{3,4}]!
dump(zzz_test)
```

this fails with msvc, but works with tcc etc

**Comment by spytheman** [comment]
One temporary workaround, is to use:
```v
const x = [fixed]Struct{}

fn init() { 
   local := [....]!
   unsafe{ vmemcpy(&x, &local, sizeof(local)) }
}
```
... i.e. move the actual initialization from comptime to runtime, where msvc accepts it.
