### ISSUE TITLE
Optional raw json field is 'none' when not a string

### ISSUE THREAD

**Issue by jon49** [vlang/v#18895]
### Describe the bug

When decoding json with `json.decode` an optional dto value of `?string [raw]` defaults to `option(none)`  when it is a complex value but works when it is a string value.

### Expected Behavior

It should be able to handle complex values similar to non-optional values.

### Current Behavior

There are currently no errors thrown with this behavior.

### Reproduction Steps

In the file `test.v`:

```v
import json

pub struct Dto {
pub:
    key string [raw]
    data ?string [raw]
    optional ?string [raw]
}

fn main() {
    raw_json := '{
        "key": [1, 2, "test"],
        "data": { "test": 1 },
        "optional": "test"
    }'

    dto := json.decode(Dto, raw_json)!

    println(dto)
}
```

Run the command `v run test.v` which will print:

```
Dto{
    key: '[1,2,"test"]'
    data: Option(none)
    optional: Option('"test"')
}
```

Expected behavior would print:

```
Dto{
    key: '[1,2,"test"]'
    data: Option('{"test":1}')
    optional: Option('"test"')
}
```

### Possible Solution

Use similar code found in parsing non-optional values?

### V version

V 0.4.0 39cfaaf

### Environment details (OS name and version, etc.)

Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy

**Comment by felipensp** [comment]
I think such behavior is a feature request, not a bug. What do you think @spytheman ?

**Comment by jon49** [comment]
This other issue similar to this one was considered a bug - so it seems like it is a bug. [Issue 17894](https://github.com/vlang/v/issues/17894).

**Comment by felipensp** [comment]
> ```v
> { "test": 1 }
> ```

`{ "test": 1 }` is not a string representation, but a struct-like one. I think the automatic complex-to-string serialization is not expected.

**Comment by JalonSolov** [comment]
> This other issue similar to this one was considered a bug - so it seems like it is a bug. [Issue 17894](https://github.com/vlang/v/issues/17894).

That was a completely different issue - it failed completely with `raw`.  Now it returns `none`.

**Comment by jon49** [comment]
So, take this example with `key2` created a raw object:

```
import json

pub struct Dto {
pub:
    key string [raw]
    key2 string [raw]
    data ?string [raw]
    optional ?string [raw]
}

fn main() {
    raw_json := '{
        "key": [1, 2, "test"],
        "key2": { "test": 1 },
        "data": { "test": 1 },
        "optional": "test"
    }'

    dto := json.decode(Dto, raw_json)!

    println(dto)
}
```

Now, the results from this are:

```
Dto{
    key: '[1,2,"test"]'
    key2: '{"test":1}'
    data: Option(none)
    optional: Option('"test"')
}
```

Notice how `key2` outputs the string `'{"test":1}'`. Those are two completely different behaviors depending on if I add an optional `?` to the type. That seems like it is unexpected behavior and a bug since they should have the same behavior but one adds `none` as an option. Why would they have different behaviors just because I want one to be optional?

**Comment by felipensp** [comment]
> So, take this example with `key2` created a raw object:
> 
> ```v
> import json
> 
> pub struct Dto {
> pub:
>     key string [raw]
>     key2 string [raw]
>     data ?string [raw]
>     optional ?string [raw]
> }
> 
> fn main() {
>     raw_json := '{
>         "key": [1, 2, "test"],
>         "key2": { "test": 1 },
>         "data": { "test": 1 },
>         "optional": "test"
>     }'
> 
>     dto := json.decode(Dto, raw_json)!
> 
>     println(dto)
> }
> ```
> 
> Now, the results from this are:
> 
> ```v
> Dto{
>     key: '[1,2,"test"]'
>     key2: '{"test":1}'
>     data: Option(none)
>     optional: Option('"test"')
> }
> ```
> 
> Notice how `key2` outputs the string `'{"test":1}'`. Those are two completely different behaviors depending on if I add an optional `?` to the type. That seems like it is unexpected behavior and a bug since they should have the same behavior but one adds `none` as an option. Why would they have different behaviors just because I want one to be optional?

Now we have a good example to explain the real problem. Thanks
