### ISSUE TITLE
Can it be used as the embedded language of go, otherwise there seems to be no need to change from go to v, because go is more stable than v?

### ISSUE THREAD

**Issue by a97077088** [vlang/v#189]
Can it be used as the embedded language of go, otherwise there seems to be no need to change from go to v, because go is more stable than v?

**Comment by medvednikov** [comment]
V offers lots of improvements over Go, you can read about them here:

https://vlang.io/compare

Not sure what you mean by embedding here. If it's calling V from Go, it's just like calling C from Go.
