### ISSUE TITLE
[coroutines] build error

### ISSUE THREAD

**Issue by lost22git** [vlang/v#18904]
### Describe the bug

- ./v_sleep.v
```v
///usr/bin/env v -cg -gc none -use-coroutines run "$0" "$@" ; exit $?

import os
import time
import coroutines

fn main() {
  mut fiber_count := (os.args[1] or { "1024" }).int()
  if fiber_count <= 0 {
    fiber_count = 1024
  }

  mut threads := []thread { cap: fiber_count }

  sw := time.new_stopwatch()

  for _ in 0 .. fiber_count {
     threads << spawn fn () {
        coroutines.sleep(3 * time.second)
     }()
  }

  _ := threads.wait()

  elapsed := sw.elapsed().milliseconds()
  println('fibers: ${fiber_count}, elapsed: ${elapsed}ms')
}
```

- photonwrapper.so:
```
❯ la /root/code/oss/v/thirdparty/photon/photonwrapper.so
-rw-r--r-- 1 root root 408432 Jul 19 04:59 /root/code/oss/v/thirdparty/photon/photonwrapper.so
```

- run:
```bash
chmod +x ./v_sleep.v
./v_sleep.v
```

- error:
```
/root/code/oss/v/thirdparty/photon/photonwrapper.so: error: /root/code/oss/v/thirdparty/photon/photonwrapper.so: unrecognized file type
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https:discord.gg/vlang

```

### Expected Behavior

build and run successful

### Current Behavior

build and run error

### Reproduction Steps

as description

### V version

V 0.4.0 44d2f2b

### Environment details (OS name and version, etc.)

V full version: V 0.4.0 44d2f2b
OS: linux, Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023 (WSL 2)
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 9 5900HX with Radeon Graphics

getwd: /root
vexe: /root/code/oss/v/v
vexe mtime: 2023-07-18 17:41:47

vroot: OK, value: /root/code/oss/v
VMODULES: OK, value: /root/.vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.39.2
Git vroot status: weekly.2023.28-42-g44d2f2b3
.git/config present: true

CC version: cc (Debian 12.2.0-14) 12.2.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by JalonSolov** [comment]
Even if it liked your version of photonwrapper.so, you wouldn't be doing what you think.

To use coroutines, you have to use `go` instead of `spawn` to start the thread.

You'll also want to check how you downloaded the .so file.  I have the linux version, and it is significantly larger than what you have...
```
-rwxr-xr-x 1 jalon jalon 497168 Jun 28 16:55 photonwrapper.so
```

**Comment by lost22git** [comment]
@JalonSolov  auto download when v build

coroutines .so not found, downloading...
done!
/root/code/oss/v/thirdparty/photon/photonwrapper.so: error: /root/code/oss/v/thirdparty/photon/photonwrapper.so: unrecognized file type
builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

**Comment by lost22git** [comment]
I try to download it from https://github.com/vlang/photonbin/blob/master/photonwrapper_linux_amd64.so

```
❯ la /root/code/oss/v/thirdparty/photon/photonwrapper.so
-rwxr-xr-x 1 root root 497168 Jul 19 09:03 /root/code/oss/v/thirdparty/photon/photonwrapper.so
```

and get another errror: `builder error: 'photonwrapper.h' not found`

**Comment by JalonSolov** [comment]
Ouch.  Neither one of those is a good thing.

@medvednikov :point_up:
