### ISSUE TITLE
Empty interface array silently fails to concat values

### ISSUE THREAD

**Issue by Coachonko** [vlang/v#18906]
### Describe the bug

```V
import arrays

interface Param {}

fn main() {
	mut ar := []Param{}
	// arrays.concat(ar, 'a string', 'another string')
	// this causes an error: cannot use `string` as `Param` in argument 2 to `arrays.concat`

	arrays.concat(ar, Param('a string'), Param('another string')) // This compiles but do not concat
	ar << 'string'
	println(ar) // [Param('string')]
}

```

### Expected Behavior

`[Param('a string'), Param('another string'), Param('string')]`
or
`error: some message`

### Current Behavior

[Param('string')]

### Reproduction Steps

Run the code

### V version

`Current V version: V 0.4.0 1ed0cd9, timestamp: 2023-07-19 13:06:41 +0300`

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.0 ee4150f.1ed0cd9
OS: linux, Linux version 5.14.0-284.18.1.el9_2.x86_64 (mockbuild@euro.kojibuilder101) (gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4), GNU ld version 2.35.2-37.el9) #1 SMP PREEMPT_DYNAMIC Fri Jun 23 16:35:13 CEST 2023
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz

getwd: /home/coachonko/Documents/projects/vlang/peony
vexe: /home/coachonko/.local/lib64/v/v
vexe mtime: 2023-07-19 12:50:20

vroot: OK, value: /home/coachonko/.local/lib64/v
VMODULES: OK, value: /home/coachonko/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.39.3
Git vroot status: weekly.2023.28-43-g1ed0cd9a
.git/config present: true

CC version: cc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

**Comment by yuyi98** [comment]
```v
import arrays

interface Param {}

fn main() {
	mut ar := []Param{}
	ar = arrays.concat(ar, Param('a string'), Param('another string')) // This compiles but do not concat
	ar << 'string'
	println(ar) // [Param('string')]
}

PS D:\Test\v\tt1> v run .
[Param('a string'), Param('another string'), Param('string')]
```

**Comment by Coachonko** [comment]
> ```v
> import arrays
> 
> interface Param {}
> 
> fn main() {
> 	mut ar := []Param{}
> 	ar = arrays.concat(ar, Param('a string'), Param('another string')) // This compiles but do not concat
> 	ar << 'string'
> 	println(ar) // [Param('string')]
> }
> 
> PS D:\Test\v\tt1> v run .
> [Param('a string'), Param('another string'), Param('string')]
> ```

Are you saying it work on Windows?
`Current V version: V 0.4.0 6fef2c2, timestamp: 2023-07-20 02:34:31 +0300`
Still doesn't work on my machine

**Comment by JalonSolov** [comment]
For anyone who missed it... `arrays.concat` returns a new array, it does not modify the array passed in.

The difference between the 2 examples is between

	`arrays.concat(ar, Param('a string'), Param('another string')) // This compiles but do not concat`

and

	**ar =** `arrays.concat(ar, Param('a string'), Param('another string')) // This compiles but do not concat`
