### ISSUE TITLE
Windows compile error

### ISSUE THREAD

**Issue by l8atnight** [vlang/v#1891]
**### compiling doesn't work for the 3 week in the row.**

F:\v>git pull origin master
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 6 (delta 5), reused 4 (delta 4), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/vlang/v
 * branch            master     -> FETCH_HEAD
   570e5f9..e78e284  master     -> origin/master
Updating 570e5f9..e78e284
Fast-forward
 compiler/cc.v       | 20 ++++++++------------
 compiler/cflags.v   |  9 ++++++---
 thirdparty/freetype |  1 +
 3 files changed, 15 insertions(+), 15 deletions(-)
 create mode 160000 thirdparty/freetype

F:\v>make
Building V
git version 2.22.0.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Der Befehl "where" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Attempting to build v.c  with MSVC...
Die eingegebene Zeile ist zu lang.
Syntaxfehler.

**Comment by l8atnight** [comment]
F:\v>make -gcc
Building V
git version 2.22.0.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Der Befehl "where" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Attempting to build v.c  with MSVC...
Die eingegebene Zeile ist zu lang.
Syntaxfehler.

**Comment by l8atnight** [comment]
F:\v>make -msvc
Building V
git version 2.22.0.windows.1
Downloading v.c...
Attempting to build v.c  with MSVC...
Die eingegebene Zeile ist zu lang.
Syntaxfehler.

**Comment by l8atnight** [comment]
VCIDEInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\
VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\
VCToolsInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\
VCToolsRedistDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Redist\MSVC\14.22.27821\
VCToolsVersion=14.22.27905
VisualStudioVersion=16.0
VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\
VS160COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\
VSCMD_ARG_app_plat=Desktop
VSCMD_ARG_HOST_ARCH=x64
VSCMD_ARG_no_logo=1
VSCMD_ARG_TGT_ARCH=x64
VSCMD_VER=16.2.4
VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\
VSSDK150INSTALL=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VSSDK
windir=C:\WINDOWS
WindowsLibPath=References\CommonConfiguration\Neutral
WindowsSDKLibVersion=winv6.3\

**Comment by joe-conigliaro** [comment]
@l8atnight What version of windows are you using?

**Comment by l8atnight** [comment]
WIndoze 64

i tried c:\v  but same result

**Comment by joe-conigliaro** [comment]
Is it windows 10?

**Comment by l8atnight** [comment]
Yes. Sorry.

**Comment by spytheman** [comment]
I wonder whether the German locale may be significant for this bug?
The travis build as well as my VM are I believe in the US locale.

**Comment by spytheman** [comment]
@l8atnight can you paste your PATH variable too?
Also, can you try running cl manually, if it is in your PATH, like this in your v folder:
```shell
git clone --depth 1 --quiet https://github.com/vlang/vc
cl.exe /nologo /w /volatile:ms /D_UNICODE /DUNICODE /Fo.v.c.obj /O2 /MD vc\v_win.c user32.lib kernel32.lib advapi32.lib shell32.lib /link /NOLOGO /OUT:v2.exe /INCREMENTAL:NO
v2.exe -os msvc -o v.exe compiler
```
... and then check whether you have v2.exe and/or v.exe in the v folder ?

**Comment by l8atnight** [comment]
I tried it again:

F:\v>git pull origin master
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 5 (delta 3), reused 5 (delta 3), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/vlang/v
 * branch            master     -> FETCH_HEAD
   ae86626..31c9a2a  master     -> origin/master
Updating ae86626..31c9a2a
Fast-forward
 vlib/bitfield/bitfield_test.v | 70 +++++++++++++++++++++----------------------
 1 file changed, 35 insertions(+), 35 deletions(-)

F:\v>make
Building V
git version 2.22.0.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Der Befehl "where" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Attempting to build v.c  with MSVC...
v_win.c
vc\v_win.c(3): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "inttypes.h": No such file or directory
cl.exe failed to build V
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error


F:\v>make -gcc
Building V
git version 2.22.0.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Der Befehl "where" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Attempting to build v.c  with MSVC...
v_win.c
vc\v_win.c(3): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "inttypes.h": No such file or directory
cl.exe failed to build V
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error

**Comment by l8atnight** [comment]
the path:
PATH=C:\Python27\;C:\Python27\Scripts;y:\Program Files (x86)\Cocktail-1007\bin;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\dotnet\;C:\Users\rko\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\WebStorm 2019.1.2\bin;C:\Program Files\mingw32\bin;C:\Program Files\mingw32\i686-w64-mingw32\bin;C:\Program Files\Git\bin;C:\Program Files\Git\cmd;f:\v;C:\Users\rko\AppData\Roaming\npm

and

F:\v>git clone --depth 1 --quiet https://github.com/vlang/vc
fatal: destination path 'vc' already exists and is not an empty directory.

**Comment by spytheman** [comment]
@l8atnight that is fine - you already have vc/ so it should be good. Try to run the next commands in the script too.

**Comment by l8atnight** [comment]
cl.exe /nologo /w /volatile:ms /D_UNICODE /DUNICODE /Fo.v.c.obj /O2 /MD vc\v_win.c user32.lib kernel32.lib advapi32.lib shell32.lib /link /NOLOGO /OUT:v2.exe /INCREMENTAL:NO
Der Befehl "cl.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

the command "cl.exe" is either written wrong or could not be found.

**Comment by spytheman** [comment]
Hm... 
After running `make -msvc` my PATH gets prefixed with:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;
```

**Comment by spytheman** [comment]
By the way, are you running Power Shell, or the cmd.exe one ?

**Comment by spytheman** [comment]
If in powershell, can you run:
```
$env:Path += ";C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools;"
```

and if in cmd.exe, do:
```
set PATH="%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools;"
```

and after this is done, rerun:
```
cl.exe /nologo /w /volatile:ms /D_UNICODE /DUNICODE /Fo.v.c.obj /O2 /MD vc\v_win.c user32.lib kernel32.lib advapi32.lib shell32.lib /link /NOLOGO /OUT:v2.exe /INCREMENTAL:NO
```
and see if there is a v2.exe produced in your folder.

**Comment by spytheman** [comment]
"%InstallDir%\Common7\Tools\vsdevcmd.bat" which is invoked by the make.bat file, seem to set not only the Path environment variable, but many others too. One of them, that I guess is important for finding the headers is INCLUDE . Can you run make -msvc again and then paste here the content of the INCLUDE environment variable, i.e. the result of
`echo %INCLUDE%` in the same shell where the make was run?

**Comment by l8atnight** [comment]
i set the pathes.

echo %INCLUDE%
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include;

but still get

F:\v>make -msvc
Building V
git version 2.22.0.windows.1
Downloading v.c...
Attempting to build v.c  with MSVC...
v_win.c
vc\v_win.c(3): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "inttypes.h": No such file or directory
cl.exe failed to build V
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error

**Comment by spytheman** [comment]
Can you check whether the header file inttypes.h is in your folder
C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include ?

На нд, 8.09.2019 г., 19:11 l8atnight <notifications@github.com> написа:

**Comment by l8atnight** [comment]
no such file

**Comment by emily33901** [comment]
Do you have the msvc stuff installed?

**Comment by l8atnight** [comment]
yup, the commpunity edition and the sdk. the inttypes.h exist in different includes so, 17 in all.

**Comment by emily33901** [comment]
includes should probably include the ucrt include though - which is where inttypes might be

**Comment by emily33901** [comment]
e.g. ![](https://i.f1ssi0n.com/PublicUnauthorizedNautilus.png)

**Comment by l8atnight** [comment]
my include shows

F:\v>echo %INCLUDE%
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include;

how can i modify it? man i just don't like VS, but the gcc doesn't work either.

**Comment by l8atnight** [comment]
i found 
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt

**Comment by spytheman** [comment]
About gcc, I think its problem is that in your Path, you have 
`C:\Program Files\mingw32\bin;C:\Program Files\mingw32\i686-w64-mingw32\bin;`
i.e. you probably have the 32bit version of it before the 64bit version ... 

You can try:
`set PATH="C:\Program Files\mingw32\i686-w64-mingw32\bin;%PATH%"
and then try running `gcc --version` . It should print something like:
```shell
C:\v>gcc --version
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
```

**Comment by spytheman** [comment]
Hm, my INCLUDE variable, after make -msvc is:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt`

**Comment by l8atnight** [comment]
i added the include with your pathes. that works now.
when compiler  it cant link user32.

**Comment by l8atnight** [comment]
when i do
>make -gcc
Building V
git version 2.22.0.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
the command "where" is either written wrong or
could not be found.
Building v.v...

**Comment by spytheman** [comment]
@l8atnight do you now have v2.exe and/or v.exe ?

**Comment by l8atnight** [comment]
now - yes
08.09.2019  19:49           524.288 v.exe

**Comment by spytheman** [comment]
Oh, nice. 

Well, that is a different unrelated issue - there is no external glfw module (to be more precise, it is in vlib/ instead of in http://vpm.vlang.io/ , so you already have it).

Try to compile & run the hello world example with:
`v.exe -show_c_cmd  -os msvc  run  examples\hello_world.v`

**Comment by l8atnight** [comment]
works - thanx all.

**Comment by joe-conigliaro** [comment]
Thanks everyone, what a good community!

**Comment by l8atnight** [comment]
yes, it's a great community - thank you all.
