### ISSUE TITLE
Question:How to use is Another Character Code

### ISSUE THREAD

**Issue by keito940** [vlang/v#1893]
The project I'm working on needed to convert to another character code. 
How is the character code converted in V language?

**Comment by Delta456** [comment]
Can you elaborate a bit? You can see `parser.v` and `compiler.v` (I don't really remember the actual files).

**Comment by keito940** [comment]
How can I convert a text file written in UTF-8 with V to ShiftJIS?

**Comment by dumblob** [comment]
https://superuser.com/a/313143 :
```sh
iconv -f UTF-8 -t SHIFT-JIS myinfile.txt > newoutfile.txt
```
