### ISSUE TITLE
Add support for generics to Vlang

### ISSUE THREAD

**Issue by vnothkumar** [vlang/v#18940]
### Describe the feature

Vlang is a powerful language, but it lacks support for generics. This makes it difficult to write code that is reusable and type-safe.

Generics would allow Vlang programmers to write code that can be used with any type of data. This would make it easier to write code that is both efficient and maintainable.

For example, a generic function could be written to sort a list of any type of data. This would eliminate the need to write separate functions for sorting lists of integers, strings, and other types of data

### Use Case

The implementation of generics in Vlang would be similar to the implementation of generics in other languages, such as C++ and Java.

The basic idea is to use a type parameter to represent the type of data that the generic function or type will work with. For example, a generic function to sort a list of data could be defined as follows:

func sort<T>(list: []T) {
// ...
}

The T type parameter represents the type of data that the list parameter will contain. For example, the following code would sort a list of integers:

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

0.3.5

### Environment details (OS name and version, etc.)

arch linux

**Comment by JalonSolov** [comment]
Yeah, this has been around for a while (it was added before they version you have): https://github.com/vlang/v/blob/master/doc/docs.md#generics
