### ISSUE TITLE
Provide a v library for async JavaScript

### ISSUE THREAD

**Issue by gslicer** [vlang/v#1894]
I would be nice to be able to build an "full stack" web-application having:

- [ ] a backend written in V
- [ ] using the V built-in ORM library for DB-integration (e.g. Postgres)
- [ ] using V built-in HTTP(S) library (basic web-server) written in V
- [ ] presenting the UI via a web-browsers using async JS/HTML5 frameworks e.g. [iioEngine](https://github.com/sbiermanlytle/iioEngine)

Nice-to-have: ideally one would not be even fiddling with JS-code at all

Not sure what would be missing, are some bindings to JS needed or are there currently even more gaps?

**Comment by dumblob** [comment]
>Nice-to-have: ideally one would not be even fiddling with JS-code at all

This "nice-to-have" in conjunction with:

>presenting the UI via a web-browsers using async JS/HTML5 frameworks e.g. iioEngine

is extremely difficult to achieve (but not impossible). So I would rather say, we shall not aim at this at all. We shall rather aim at having a fully functional and usable (in terms of "acceptable performance & size") JS backend and leave the [UI library](https://github.com/vlang/ui/issues/1 ) solve the rest for us :wink:.

**Comment by gslicer** [comment]
closing in favor of the UI for Web feature request
