### ISSUE TITLE
It can't play wav or mp3 file

### ISSUE THREAD

**Issue by yingshaoxo** [vlang/v#18954]
### Describe the feature

V lang doesn't have a built-in sound library.

So you can't use it to make a music player, a game engine, a video player and so on.

### Use Case

Play sound

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

xx

### Environment details (OS name and version, etc.)

Linux or Windows.

**Comment by JalonSolov** [comment]
You are correct that V doesn't have an audio player in the standard library.

However, others have created various modules you can use, such as

https://github.com/Larpon/miniaudio - for just audio

and

https://github.com/vlang/sdl - a wrapper around libsdl2, the Simple DirectMedia Layer library.

**Comment by Larpon** [comment]
We have sokol audio in vlib https://github.com/vlang/v/blob/master/vlib/sokol/audio/audio.v
See the examples here https://github.com/vlang/v/tree/master/examples/sokol/sounds
