### ISSUE TITLE
Windows compilation error

### ISSUE THREAD

**Issue by JeromSar** [vlang/v#1895]
**V version:** 
**OS:** Windows 10 64-bit

**What did you do?**
run `make.bat`

**What did you expect to see?**
Bootstrapping and compilation
 
**What did you see instead?**
```
C:\Users\Admin\Desktop\v>make
make
Building V
git version 2.10.2.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
In file included from vc\v_win.c:6:0:
vc\v_win.c: In function 'os__get_file_handle':
vc\v_win.c:4970:34: error: request for member '_file' in something not a structure or union
   void *_handle = _get_osfhandle(_fileno(_fd));
                                  ^
vc\v_win.c: In function 'init_consts':
vc\v_win.c:21691:29: error: '_O_U8TEXT' undeclared (first use in this function)
   _setmode(_fileno(stdout), _O_U8TEXT);
                             ^
vc\v_win.c:21691:29: note: each undeclared identifier is reported only once for each function it appears in
gcc failed to compile - Create an issue at 'https://github.com/vlang'
```

**Comment by ArsDankeZik** [comment]
I have the same issue

**Comment by joe-conigliaro** [comment]
@ArsDankeZik This issue is due to the fact in older Mingw64 version in `fcntl.h` the define `_O_U8TEXT` is inside a condition which checks mscvrt version `#if(__MSVCRT_VERSION__ >= 0x0800)`. This check was removed in newer Mingw64 versions.

So updating your Mingw64 to the newest version will fix the issue. You could also just trick it by defining __MSVCRT_VERSION__ to a higher value. But the best thing to do is just update 😄

**Comment by michaeldesu** [comment]
Not sure, but I might have a similar issue (using llvm-mingw compiler).

**V version:**
V 0.1.25 bc3d1ea
 
**OS:** 
Windows 10 64-bit

**What did you do?**
Compiled from source on Windows (used llvm-mingw compiler)
Compilation of v was successful (could get version reported), but compiling hello_world.v failed with errors.

**What did you expect to see?**
hello world
 
**What did you see instead?**
```
use of undeclared identifier '_O_U8TEXT'
 _setmode ( _fileno ( stdout ) ,  _O_U8TEXT ) ;
                                  ^
```
see https://pastebin.com/JWH3dwZR for more details include compile with -cg option

**Comment by michaeldesu** [comment]
FWIW I tried again on a fresh machine from scratch using MSVC, and found it was all good.

**Comment by michaeldesu** [comment]
I think this should be fixed or the docs updated (to not include the non-working compilers), as the current situation is not ideal for newcomers. The exe on the main page should be fixed also.
