### ISSUE TITLE
v fmt add dot to constant name and make its treated like an enum 

### ISSUE THREAD

**Issue by blackshirt** [vlang/v#18970]
### Describe the bug

I dont know, its happen only to me, or just my foolishness, or others have an issue too..but i can reproduce it in my environment.
The bug of v formatter, happen in project tree in `v.mod` mode where run `$v fmt -w .` to format all files, its changes constant name in respective file where they defined by adding dot (.) to the constant name, and make its like an enum. When its happen, its can lead horrible fail of tests or builds.
see attached files for example.

### Expected Behavior

its just format it, or..add the module name in front of constant name.
example: constant `max_hadiah_amount` after ` v fmt` would not change or changes it to `modulename.max_hadiah_amount` ...

### Current Behavior

Its change constant name by adding dot . in front of the name.
similar like this ```max_hadiah_amount``` become ```.max_hadiah_amount```

### Reproduction Steps

make v project folder structure by run `v init` or others.
my `$tree` of simple reproducer 
```tree
├── src
│   ├── aa.v
│   ├── bb.v
│   └── beer.v
└── v.mod
2 directories, 4 files
```

 i'm attach 3 unformatted files as an example how i reproduce its. dont look at the content or logic. its a bull. [src.zip](https://github.com/vlang/v/files/12168061/src.zip)

run `$v fmt -w .` from top level project dir, and see at constant name before and after running `v fmt -w .`
Maybe someone has a similar issues, 

### V version

```$ v version V 0.4.0 5ecbfb7```

### Environment details (OS name and version, etc.)

```$ v doctor
V full version: V 0.4.0 c2dc1ca.5ecbfb7
OS: windows, Microsoft Windows 10 Home Single Language v19045 64-bit
Processor: 2 cpus, 64bit, little endian, 

getwd: C:\msys64\home\reguler\beer
vexe: C:\msys64\home\reguler\github\v\v.exe
vexe mtime: 2023-07-26 04:38:06

vroot: OK, value: C:\msys64\home\reguler\github\v
VMODULES: OK, value: C:\msys64\home\reguler\.vmodules
VTMP: OK, value: C:\msys64\tmp\v_0

Git version: git version 2.37.1
Git vroot status: weekly.2023.28-88-g5ecbfb7b-dirty
.git/config present: true

CC version: cc (Rev3, Built by MSYS2 project) 12.1.0
thirdparty/tcc status: thirdparty-windows-amd64 e90c2620```

**Comment by spytheman** [comment]
I still can not reproduce it locally, using the src.zip:
![image](https://github.com/vlang/v/assets/26967/e39c0ec8-7ea0-42b4-b788-4e7ceff42548)

**Comment by spytheman** [comment]
Even a project with a v.mod file with the same zip seems to work 🤔 : 
![image](https://github.com/vlang/v/assets/26967/a354524b-b809-4bed-8f69-847603b34ab0)

**Comment by spytheman** [comment]
I'll try to test on windows later today.

**Comment by spytheman** [comment]
The issue needs the top level project folder to be named `beer`, i.e. `bb.v` has `module beer` at its start, and the constant renaming happens when the project folder is also `beer`, and not otherwise.

**Comment by blackshirt** [comment]
yeah, i think `v.mod` from previous `v new beer`  or `v init` inside `beer` directory tells what is default folder structure ..`src` folder inside top level `beer` folder.

i think there are issue in module lookup

**Comment by Dracks** [comment]
I had the same problem too today, in one of my projects too.
