### ISSUE TITLE
v fmt . -w makes` import databases` change to ` import diff.src.databases`

### ISSUE THREAD

**Issue by carpedil** [vlang/v#18993]
### Describe the bug

![23072801](https://github.com/vlang/v/assets/12119342/bc627976-66f1-40c0-8303-91a4a2263def)

### Expected Behavior

the imported module name should not be changed

### Current Behavior

after  run `v fmt . -w ` ,  `import databases` change to ` import diff.src.databases`

### Reproduction Steps

v fmt . -w

### V version

V 0.4.0 c7f708e

### Environment details (OS name and version, etc.)

V full version: V 0.4.0 c7f708e
OS: windows, Microsoft Windows 11 Pro v22621 64-bit
Processor: 12 cpus, 64bit, little endian, 

getwd: D:\codespace\vlang\v_study
vexe: C:\Users\cirya\v\v.exe
vexe mtime: 2023-07-28 01:58:28

vroot: OK, value: C:\Users\cirya\v
VMODULES: OK, value: C:\Users\cirya\.vmodules
VTMP: OK, value: C:\Users\cirya\AppData\Local\Temp\v_0

Git version: git version 2.38.1.windows.1
Git vroot status: weekly.2023.30-18-gc7f708e6 (4 commit(s) behind V master)
.git/config present: true

CC version: Error: exec failed (CreateProcess) with code 2: 系统找不到指定的文件。
 cmd: cc --version
thirdparty/tcc status: thirdparty-windows-amd64 e90c2620

**Comment by carpedil** [comment]
> Do you have a `v.mod` file in the same directory as your `main.v` file? V (and `v fmt`) needs the `v.mod` file as an anchor to properly find your submodules.

yes , it dose have the v.mod file at xxx/vlang/v_bugs/src/diff 

├── src
│   ├── diff       
│   │   ├── src
│   │   │   ├── _app
│   │   │   ├── app.db
│   │   │   ├── databases
│   │   │   ├── main.v
│   │   │   └── templates
│   │   └── v.mod
└── v.mod

**Comment by ttytm** [comment]
Should be fixed with latest V. Please let us know when you experience further issues.
