### ISSUE TITLE
Embedded http web server

### ISSUE THREAD

**Issue by bitsnaps** [vlang/v#190]
Hi, will V have an embedded http web server, something like NGINX reactive-ready?

**Comment by medvednikov** [comment]
It already does, the forum is using it:

https://blog.vlang.io/forum

**Comment by medvednikov** [comment]
The entire app including the built in web server is 65 KB.

**Comment by iangudger** [comment]
Where did the web server come from? Is it a C webserver? Is it based on some other web server? Is it a clean room implementation based on the RFCs?

**Comment by medvednikov** [comment]
It's written in pure V. It's very basic at the moment.

**Comment by ggomaeng** [comment]
The link is dead.
