### ISSUE TITLE
windows: os.args is empty

### ISSUE THREAD

**Issue by milen-prg** [vlang/v#19020]
### Describe the bug

Always os.args is empty.

### Expected Behavior

It must contain  command line arguments (see the Documentation).

### Current Behavior

It is empty when run the v file or run the produced exe file.

### Reproduction Steps

Simple example:

```v
import os

fn main() {
	println(os.args)
}
```

### V version

V 0.4.0 81e99a2

### Environment details (OS name and version, etc.)

V full version: V 0.4.0 93b3f1c.81e99a2
OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 4 cpus, 64bit, little endian,

getwd: C:\Users\mlap\Downloads
vexe: C:\v\v.exe
vexe mtime: 2023-07-31 12:33:01

vroot: OK, value: C:\v
VMODULES: OK, value: C:\Users\mlap\.vmodules
VTMP: OK, value: C:\Users\mlap\AppData\Local\Temp\v_0

Git version: git version 2.37.3.windows.1
Git vroot status: weekly.2023.27-174-g81e99a2a
.git/config present: true

CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: cc --version
thirdparty/tcc status: thirdparty-windows-amd64 e90c2620

**Comment by JalonSolov** [comment]
Works as expected on Linux...
```
$ v run args.v
['/home/jalon/args']
$ v run args.v 1 2 3
['/home/jalon/args', '1', '2', '3']
$
```

**Comment by milen-prg** [comment]
I apologize, I try again in the windows terminal, it seems that I have some problem with VSCode output. In the terminal all works fine, when start the v file or the generated exe.
I apologize again and close this issue (if it is possible, please delete it).
