### ISSUE TITLE
[compiler] Duplicate consts when defined in a  _default and _plattform specific file

### ISSUE THREAD

**Issue by sandbankdisperser** [vlang/v#19031]
### Describe the bug

The compiler doesn't seem to exclude the _default file when a plattform specific file is available and refuses to built because of a duplicate const error.

### Expected Behavior

Compiling without any errors

### Current Behavior

Compile and checker refuses to build because of a duplicate const definition.

### Reproduction Steps

1. Define a example_default.v file
2. Define a example_youros.v file
3. Define a const with the same name in both files
4. Compile the files

### Possible Solution

After a quick look at the code we could exclude all _default files in get_builtin_files() and get_user_files() for which we have a os specific file

### V version

V 0.4.0 367e38d

### Environment details (OS name and version, etc.)

Distributor ID:	Fedora
Description:	Fedora release 38 (Thirty Eight)
Release:	38
Codename:	ThirtyEight
Latest updates

**Comment by shove70** [comment]
I cannot reproduce it, it looks normal. Is your variable name conflicting with a const variable name in the vlib module? It is best to provide detailed error information for your code and compiler

**Comment by shove70** [comment]
> example_linux.c.v
> example_default.c.v

.....c.v is a rule designed by V, and only this rule can be used as an extension to distinguish platforms

**Comment by sandbankdisperser** [comment]
Ok, thanks
