### ISSUE TITLE
tcc: error: library 'stdc++' not found

### ISSUE THREAD

**Issue by rleddy** [vlang/v#19034]
### Describe the bug

WASM compiler cannot locate library when running `v -b wasm -os browser mandelbrot.v`

uname -a
Linux **** 5.4.0-153-generic #170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Expected Behavior

v -b wasm -os browser mandelbrot.v

generates wasm file

### Current Behavior
```
v -b wasm -os browser mandelbrot.v

cannot compile `/media/vprojects/v/cmd/tools/builders/wasm_builder.v`: 
==================
tcc: error: library 'stdc++' not found
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

### Reproduction Steps

**v -b wasm -os browser mandelbrot.v**

### Possible Solution

Helpful doc.

### V version

V 0.4.0 2e9f8e6

### Environment details (OS name and version, etc.)

uname -a
Linux **** 5.4.0-153-generic #170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 

../../../v/cmd/tools/install_binaryen.vsh
Downloading archive: /media/vprojects/v/thirdparty/binaryen-version_112.tar.gz, from url: https://github.com/WebAssembly/binaryen/releases/download/version_112/binaryen-version_112-x86_64-linux.tar.gz ...
Extracting `/media/rvprojects/v/thirdparty/binaryen-version_112` to `/media/vprojects/v/thirdparty/binaryen` ...
binaryen-version_112/
binaryen-version_112/lib/
binaryen-version_112/lib/libbinaryen.a
binaryen-version_112/include/
binaryen-version_112/include/binaryen-c.h
binaryen-version_112/include/wasm-delegations.def
binaryen-version_112/bin/
binaryen-version_112/bin/wasm2js
binaryen-version_112/bin/wasm-reduce
binaryen-version_112/bin/wasm-metadce
binaryen-version_112/bin/wasm-emscripten-finalize
binaryen-version_112/bin/wasm-as
binaryen-version_112/bin/wasm-split
binaryen-version_112/bin/wasm-shell
binaryen-version_112/bin/binaryen-unittests
binaryen-version_112/bin/wasm-dis
binaryen-version_112/bin/wasm-opt
binaryen-version_112/bin/wasm-fuzz-types
binaryen-version_112/bin/wasm-ctor-eval
tar -xvf /media/vprojects/v/thirdparty/binaryen-version_112.tar.gz --directory /media/vprojects/v/thirdparty
Moving `/media/vprojects/v/thirdparty/binaryen-version_112` to `/media/vprojects/v/thirdparty/binaryen` ...
Done. You can now use `v -b wasm file.v`

**Comment by ttytm** [comment]
Hey @rleddy, 

I recently encountered the same tcc error on an older machine. Not with wasm, but this doesn't look like it's being caused by the wasm backend rather like a dependency error like it was in my case. Compilation worked with gcc, but not with tcc. tcc started working after I updated the C compilers and the corresponding libraries.

Based on the kernel version, I would assume that the system you are using an older system as well. If you can update your compiler, `libstdc++` and `libstdc++-<ver>-dev`, make sure you recompile your V binary with it before testing again.

For more information, you could post the output of "v doctor" to see more about the system on which the error occurs. If possible, please also provide a fully reproducible case.

**Comment by JalonSolov** [comment]
We already have a reproducible case - he is just compiling `examples/wasm/mandelbrot/mandelbrot.v`

**Comment by spytheman** [comment]
`v -b wasm -os browser ./examples/wasm/mandelbrot/mandelbrot.v` compiles cleanly with latest V, after c422919 from 2023-07-12, the wasm backend is written in pure V, and does not depend on binaryen anymore.

**Comment by spytheman** [comment]
The V from the issue is 2e9f8e6 , which is from 2023-07-03 .
