### ISSUE TITLE
ORM not working correctly

### ISSUE THREAD

**Issue by ashraffouda** [vlang/v#19042]
### Describe the bug

I'm using orm to insert and select data 
in the following example `insert` works while `select` fails with a weird error 
here is the example in the playground 
https://play.vosca.dev/?query=68513fdd0f
produces this error 
```
================ V panic ================
   module: builtin
 function: get()
  message: array.get: index out of range (i == 6, a.len == 5)
     file: /home/pmakhnev/v/vlib/builtin/array.v:435
   v hash: 8ee1667
=======================
```
```
import db.sqlite

struct PhoneOrder {
	id         int    [primary; sql: serial]
	item       string
	quantity   string
	presale_id int
}


struct NodeOrder {
	id         int    [primary; sql: serial]
	item       string
	quantity   string
	presale_id int
}
struct Presale {
	id           int     [primary; sql: serial]
	email        string  [primary; unique]
	phone        string  [unique]
	referal_code string
	phone_orders []PhoneOrder [fkey: 'presale_id']
	node_orders  []NodeOrder  [fkey: 'presale_id']
	reason       string
}
mut db := sqlite.connect('formsdb')!
sql db {
		create table Presale
	}!
	sql db {
		create table PhoneOrder
	}!
		sql db {
		create table NodeOrder
	}!
presale := Presale{
    id: 0
    email: 'foudaa@incubaid.com'
    phone: '01009153127'
    referal_code: 'aaaaa'
    phone_orders: [PhoneOrder{
        id: 0
        item: 'phone1'
        quantity: '2'
        presale_id: 0
    }, PhoneOrder{
        id: 0
        item: 'phone2'
        quantity: '3'
        presale_id: 0
    }]
    node_orders: [NodeOrder{
        id: 0
        item: 'node1'
        quantity: '3'
        presale_id: 0
    }, NodeOrder{
        id: 0
        item: 'node3'
        quantity: '5'
        presale_id: 0
    }]
    reason: 'reason'
}
sql db {
		insert presale into Presale
	} !
node_orders := sql db {
		select from NodeOrder
	} !
println(node_orders)
presales := sql db {
		select from Presale
	} !

println(presales)

```

### Expected Behavior

select should work

### Current Behavior

not working

### Reproduction Steps

run the above code

### V version

V 0.4.0 8ee1667
V 0.4.0 ecca3b1

### Environment details (OS name and version, etc.)

Ubuntu 22.04.2 LTS

**Comment by ashraffouda** [comment]
turned out to be the most weird issue 
because reason is under the foreign key it didn't work

**Comment by ashraffouda** [comment]
another crazy thing is it successfully inserts the data but not getting it back through select 
fa it should be fail  in insert as well

**Comment by ashraffouda** [comment]
another thing to add
after it works the date returned from select is not correct 
it returns the `Presale` object without `phone_orders` and `node_orders`

**Comment by ashraffouda** [comment]
> another thing to add after it works the data returned from select is not correct it returns the `Presale` object without `phone_orders` and `node_orders`
> 
> ```
> {
>     "id": 0,
>     "email": "foudaa@incubaid.com",
>     "phone": "01009153127",
>     "referal_code": "aaaaa",
>     "reason": "reason",
>     "phone_orders": [],
>     "node_orders": []
> }
> ```

figured out why, this is because I have two id and email primary, 
removed primary from email and it works
not sure if it is an issue or not 
but I think it should fail if it is an issue

**Comment by Casper64** [comment]
I will add a checker error for double primary fields in a later pr where I do some cleanup in the ORM module. Output of your code after #19324 :
```v
[NodeOrder{
    id: 1
    item: 'node1'
    quantity: '3'
    presale_id: 1
}, NodeOrder{
    id: 2
    item: 'node3'
    quantity: '5'
    presale_id: 1
}]
[Presale{
    id: 1
    email: 'foudaa@incubaid.com'
    phone: '01009153127'
    referal_code: 'aaaaa'
    phone_orders: [PhoneOrder{
        id: 1
        item: 'phone1'
        quantity: '2'
        presale_id: 1
    }, PhoneOrder{
        id: 2
        item: 'phone2'
        quantity: '3'
        presale_id: 1
    }]
    node_orders: [NodeOrder{
        id: 1
        item: 'node1'
        quantity: '3'
        presale_id: 1
    }, NodeOrder{
        id: 2
        item: 'node3'
        quantity: '5'
        presale_id: 1
    }]
    reason: 'reason'
}]
```
