### ISSUE TITLE
Wrong comptime usage should produce helper message

### ISSUE THREAD

**Issue by ArtemkaKun** [vlang/v#19056]
### Describe the bug

T to interface type check must be done in comptime expression, so using it as a common code must throw a helper message

### Expected Behavior

```
you need to use $if instead of if
```

### Current Behavior

```
Running code...
Can't run code. The server returned an error:
code.v:10:5: error: undefined ident: `T`
    8 | 
    9 | fn check[T]() bool {
   10 |     if T is Checkable {
      |        ^
   11 |         return true
   12 |     } else {
Exited with error status 1
Please try again.
```

### Reproduction Steps

```v
interface Checkable {
	test int
}

struct Test {
	test int
}

fn check[T]() bool {
	if T is Checkable {
		return true
	} else {
		return false
	}
}

println(check[Test]())
```

### V version

V 0.4.0 d91c7f1 

### Environment details (OS name and version, etc.)

Playground

**Comment by shove70** [comment]
```v
fn check[T]() bool {
	$if T is Checkable {
		return true
	} $else {
		return false
	}
}
```
comptime.

**Comment by ArtemkaKun** [comment]
@shove70 Thanks for that, I have 0 experience with comptime. So this is not a bug at all, right?

**Comment by shove70** [comment]
> Thanks for that, I have 0 experience with comptime. So this is not a bug at all, right?

Yes, it's not a bug

**Comment by medvednikov** [comment]
It's not a bug, but since we're making the most friendly language ever, it should catch that and show a hint: `you need to use $if instead of if` here 🙂
