### ISSUE TITLE
db.sqlite Return types

### ISSUE THREAD

**Issue by jacksonmowry** [vlang/v#19084]
### Describe the feature

Making the return types for db.sqlite functions more consistent by always returning a `result` type from a query. 

### Use Case

This would allow consistent handling of responses from querying the database. Currently only some of the functions have `result` return types, with others returning single values or a value and error code. 

### Proposed Solution

Change `db.q_int`, `db.q_string`, and `db.exec` to return `result` types `(!int, !string, and ![]Row` respectively.  The error code would still be accessible from the `code` field of the error. 

### Other Information

The newly added sqlite `exec_param` and `exec_param_many` also return `result` types, along with all other db modules returning `result` types from their queries. This standardization would allow easier switching between sqlite3 and pg.  

We could possibly also consider returning a result type from `exec_none`? This would need to be discussed because it may make sense for a entirely different return type (value vs error) depending on the result code. Although it might make sense to just stick with returning the code itself. 

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### Version used

Current V version: V 0.4.0 320057d, timestamp: 2023-08-07 09:19:54 +0300

### Environment details (OS name and version, etc.)

V full version: V 0.4.0 7e067c5.320057d
OS: linux, Linux version 6.4.2-arch1-1 (linux@archlinux) (gcc (GCC) 13.1.1 20230429, GNU ld (GNU Binutils) 2.40.0) #1 SMP PREEMPT_DYNAMIC Thu, 06 Jul 2023 18:35:54 +0000
Processor: 12 cpus, 64bit, little endian, 12th Gen Intel(R) Core(TM) i5-12400F

getwd: /home/jarch
vexe: /home/jarch/v/v
vexe mtime: 2023-08-07 09:24:31

vroot: OK, value: /home/jarch/v
VMODULES: OK, value: /home/jarch/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.41.0
Git vroot status: weekly.2023.31-17-g320057df
.git/config present: true

CC version: cc (GCC) 13.1.1 20230429
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by spytheman** [comment]
I like your proposal. Please do it.
