### ISSUE TITLE
Function return not string

### ISSUE THREAD

**Issue by spTorin** [vlang/v#191]
```
fn out123() string {
	return '123'
}

fn main() {
	println(out123)
}
```
Will output `0x4012b0` on playground.

If make `println(string(out123))` - "You just found a bug. V can't compile this program, but it should. Please create a GitHub issue."

**Comment by Ivo-Balbaert** [comment]
This output is normal because you print out the function, not the call to the function.
You should write: println(out123())

**Comment by spTorin** [comment]
I see, tnx.
In which cases we can use the function without calling it?

**Comment by medvednikov** [comment]
You can pass functions as arguments, return them, and call them later.

High order functions are still WIP.

**Comment by ntrel** [comment]
Passing a function to println should probably be a compile time error.
