### ISSUE TITLE
Static type methods not recognized when imported from a module

### ISSUE THREAD

**Issue by dospro** [vlang/v#19127]
### Describe the bug

When importing a Struct or Enum from another module that has an associated static type method, the compiler fails to recognize the method.

### Expected Behavior

The compiler should recognize the static type method when imported from another module

### Current Behavior

When you execute `v run .` inside the project folder, you get the following error
```
src/main.v:6:12: error: unknown function: SomeStruct.new
    4 | 
    5 | fn main() {
    6 |     result := SomeStruct.new('Hello world')
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    7 | }
```

### Reproduction Steps

1. Create a new project using command `v new some_project`
2. Inside the src file create a new folder named `my_module`
3. Inside the `my_module` folder copy/paste the following code:
```v
module my_module

pub struct SomeStruct {
	msg string
}

pub fn SomeStruct.new(text string) SomeStruct {
	println('Hello!')
	return SomeStruct {
		msg: text
	}
}
```
4. Now on the `main.v` file that was create with the project copy/paste the following code:
```v
module main

import my_module {SomeStruct}

fn main() {
	result := SomeStruct.new('Hello world')
}

```
5. Try running the code using `v run .`
6. It fails to compile with the following error:
```
src/main.v:6:12: error: unknown function: SomeStruct.new
    4 | 
    5 | fn main() {
    6 |     result := SomeStruct.new('Hello world')
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    7 | }
```

### V version

V 0.4.0 320057d

### Environment details (OS name and version, etc.)

V full version: V 0.4.0 bfaa3de.320057d
OS: macos, macOS, 13.4.1
Processor: 10 cpus, 64bit, little endian, Apple M1 Max

**Comment by shove70** [comment]
I think V does not provide this syntax support:

```v
pub fn SomeStruct.new(text string) SomeStruct {
```

**Comment by JalonSolov** [comment]
It does:  https://github.com/vlang/v/blob/master/doc/docs.md#static-type-methods

**Comment by shove70** [comment]
> It does: https://github.com/vlang/v/blob/master/doc/docs.md#static-type-methods

Oh, yes, thank you
