### ISSUE TITLE
profile timings wrong on windows

### ISSUE THREAD

**Issue by Lenni0451** [vlang/v#19130]
### Describe the bug

When profiling an application using `-profile prof.txt` the times are wrong on windows.

### Expected Behavior

The times are correct as they are when running it on linux (WSL):
```
             6          0.046ms           7688ns new_array_from_c_array 
             2          0.004ms           2070ns new_array_from_c_array_noscan 
             1          0.004ms           4080ns _v_malloc 
             6          0.030ms           4968ns vcalloc 
             2          0.004ms           1820ns vcalloc_noscan 
             1          0.004ms           4360ns memdup 
             1          0.000ms            100ns builtin_init 
             8          0.006ms            704ns vmemcpy 
             1       5000.106ms     5000105972ns time__sleep 
             1       5000.112ms     5000112192ns main__main 
```

### Current Behavior

The time to execute is `50ms` instead of `5000ms`.
```
             6          0.000ms             77ns new_array_from_c_array 
             2          0.000ms             25ns new_array_from_c_array_noscan 
             1          0.000ms             49ns _v_malloc 
             6          0.000ms             53ns vcalloc 
             2          0.000ms             23ns vcalloc_noscan 
             1          0.000ms            111ns memdup 
             1          0.000ms            230ns is_terminal 
             1          0.002ms           1681ns builtin_init 
             1          0.000ms             53ns add_vectored_exception_handler 
             1          0.000ms             55ns add_unhandled_exception_handler 
             8          0.000ms              4ns vmemcpy 
             1          0.000ms             26ns time__portable_timegm 
             1          0.000ms              1ns time__days_from_unix_epoch 
             1          0.000ms             98ns time__make_unix_time 
             1          0.000ms              2ns time__init_win_time_freq 
             1          0.000ms             27ns time__init_win_time_start 
             1          0.006ms           5950ns time__local_as_unix_time 
             1         50.042ms       50042310ns time__sleep 
             1         50.042ms       50042314ns main__main 
```

### Reproduction Steps

I made a small test application which sleeps for 5 seconds and profiled it.
```v
import time

fn main() {
	time.sleep(5 * time.second)
}
```

### V version

V 0.4.0 88d3326

### Environment details (OS name and version, etc.)

V full version: V 0.4.0 df3c85e.88d3326
OS: windows, Microsoft Windows 11 Pro v22621 64-Bit
Processor: 16 cpus, 64bit, little endian,

getwd: C:\Users\User\vlang\test
vexe: C:\Users\User\AppData\Local\Programs\v\v.exe
vexe mtime: 2023-08-13 10:08:12

vroot: OK, value: C:\Users\User\AppData\Local\Programs\v
VMODULES: OK, value: C:\Users\User\.vmodules
VTMP: OK, value: C:\Users\User\AppData\Local\Temp\v_0

Git version: git version 2.41.0.windows.2
Git vroot status: weekly.2023.24-380-g88d3326a (3 commit(s) behind V master)
.git/config present: true

CC version: Error: exec failed (CreateProcess) with code 2: Das System kann die angegebene Datei nicht finden.
 cmd: cc --version
thirdparty/tcc status: thirdparty-windows-amd64 e90c2620

**Comment by spytheman** [comment]
Fixed by #23227 , thanks to @kbkpbot .
