### ISSUE TITLE
cgen: `-cstrict -cc clang` fails for just `println('¯\_(ツ)_/¯')`

### ISSUE THREAD

**Issue by spytheman** [vlang/v#19131]
**V doctor:**
```
V full version: V 0.4.0 bfaa3de.a711e17
OS: linux, Ubuntu 20.04.6 LTS
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i3-3225 CPU @ 3.30GHz

getwd: /v/vnew
vexe: /v/vnew/v
vexe mtime: 2023-08-13 10:27:05

vroot: OK, value: /v/vnew
VMODULES: OK, value: /home/delian/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.41.0
Git vroot status: weekly.2023.32-37-g68eec829-dirty (3 commit(s) behind V master)
.git/config present: true

CC version: cc (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg x.v`
```v
println('¯\_(ツ)_/¯')

```

**What did you expect to see?**

compiled program, even with `-cc clang -cstrict`

**What did you see instead?**
```
¯_(ツ)_/¯
```

With `v -cstrict -cc clang x.v`:
```
#0 14:36:37 ᛋ feature/thirdparty-cpp-compilation /v/vnew❱v -cstrict -cc clang x.v 
==================
/tmp/v_1000/x.8989453521350950899.tmp.c:12461:25: error: unknown escape sequence '\_' [-Werror,-Wunknown-escape-sequence]
        println(_SLIT("\302\257\_(\343\203\204)_/\302\257"));
                               ^~
/tmp/v_1000/x.8989453521350950899.tmp.c:182:46: note: expanded from macro '_SLIT'
#define _SLIT(s) ((string){.str=(byteptr)("" s), .len=(sizeof(s)-1), .is_lit=1})
                                             ^
/tmp/v_1000/x.8989453521350950899.tmp.c:12461:25: error: unknown escape sequence '\_' [-Werror,-Wunknown-escape-sequence]
        println(_SLIT("\302\257\_(\343\203\204)_/\302\257"));
                               ^~
/tmp/v_1000/x.8989453521350950899.tmp.c:182:63: note: expanded from macro '_SLIT'
#define _SLIT(s) ((string){.str=(byteptr)("" s), .len=(sizeof(s)-1), .is_lit=1})
                                                              ^
...
==================
```

**Comment by spytheman** [comment]
Alternatively, `\_` inside a string, should have been a checker/scanner error, instead of allowing it to go into cgen and fail at C compilation time.

**Comment by JalonSolov** [comment]
Inside a string, `\` is an escape character.  It think what's happening now is correct, since `_` doesn't need to be escaped.  You would need to used raw strings to avoid the escape.
```v
println(r'¯\_(ツ)_/¯')
```
outputs
```
¯\_(ツ)_/¯
```

**Comment by spytheman** [comment]
> On Linux, I don't see an error when I compile the example with tcc, gcc, or clang.

Use `v -cstrict -cc clang file.v` and you will see the problem.

**Comment by spytheman** [comment]
>  I think what's happening now is correct, since _ doesn't need to be escaped. 

That is one way to interpret it, and it is valid of course. It will require more complexity in our `cgen`, so that V continues to generate valid C code.

The alternative that is done in @yuyi98's PR is to instead error early in the V scanner, i.e. tell the user that what is written is not supported with a nicer V error, instead of a more surprising C one later (note that it only happens with -cstrict, i.e. the user will get that C error only in some cases, like running tests on a CI, or worse - never, if he does not run tests with -cstrict, instead getting a surprising runtime behaviour sometimes).

**Comment by JalonSolov** [comment]
Will the error only be hit if `-cstrict` is used?  Otherwise, _that_ will be confusing, since it is perfectly valid in a string.

**Comment by spytheman** [comment]
No, currently the error will be triggered always for `\_` .

**Comment by spytheman** [comment]
> Otherwise, that will be confusing, since it is perfectly valid in a string.

I.e. you prefer the error to be fixed in cgen, by ignoring `\` for `\_`, so that C would see only `_` ?

**Comment by JalonSolov** [comment]
Yes.  The alternative to using raw strings would be to escape the escape... `¯\\_(ツ)_/¯` but either way should "work".

**Comment by JalonSolov** [comment]
Interesting... "The C standard requires such "invalid" escape sequences to be diagnosed (i.e., the compiler must print an error message)."

According to that, yuyi's PR does the right thing.

I don't recall ever running into this before... <sigh>

Since it is in the C standard, I suppose it can stay as it is, then.

**Comment by spytheman** [comment]
@yuyi98 can it be fixed in `cescape_nonascii` instead of a scanner error?

**Comment by spytheman** [comment]
> Interesting... "The C standard requires such "invalid" escape sequences to be diagnosed (i.e., the compiler must print an error message)."

Clang/gcc/tcc only do so with `-cstrict`, which is the equivalent of passing `-Wall -Wextra -Werror -Wno-unused-parameter -Wno-unused -Wno-type-limits -Wno-tautological-compare -Wno-shadow -Wno-int-to-pointer-cast -Wno-trigraphs -Wno-missing-braces -Wno-unknown-warning -Wno-unknown-warning-option -Wno-excess-initializers -Wdate-time -Wduplicated-branches -Wduplicated-cond -Winit-self -Winvalid-pch -Wjump-misses-init -Wlogical-op -Wmultichar -Wnested-externs -Wnull-dereference -Wpacked -Wpointer-arith -Werror=implicit-function-declaration` to the C compiler.

Otherwise they produce warnings `warning: unknown escape sequence: '\_'`, but continue.

**Comment by JalonSolov** [comment]
I've accidentally done this in the past, and never saw a warning, either, but it has been a while.

So... basically, if we want to follow the C standard on this, then the checker error/warning is the correct way to handle it.  Otherwise, V's output should be properly escaped so the C compiler doesn't complain about it.

**Comment by yuyi98** [comment]
```v
package main

import (
	"fmt"
)

func main() {
	a := "¯\_(ツ)_/¯"
	fmt.Printf(a)
}

C:/Go/bin/go.exe build [D:/Test/go/ttt]
# ttt
.\main.go:8:11: unknown escape
错误: 进程退出代码 1.
```

**Comment by yuyi98** [comment]
> @yuyi98 can it be fixed in cescape_nonascii instead of a scanner error?

Thanks !
I'll try.

**Comment by JalonSolov** [comment]
It's also an error in current versions of Java:
```
$ javac foo.java
foo.java:5: error: illegal escape character
                System.out.println("¯\_(ツ)_/¯");  
                                      ^
1 error
[jalon@7950x ~]$
```

**Comment by spytheman** [comment]
I think the scanner error is good enough for now, since it will make people get an earlier and easier to understand error, instead of getting unexpected results much later, after a lot of waiting in the CI.

I'll merge the PR, and if a cgen fix is found later, we can relax the constraint in the scanner.
