### ISSUE TITLE
C error when assigning variable to const int_type ptr

### ISSUE THREAD

**Issue by ttytm** [vlang/v#19146]
### Describe the bug

Builder error:
```v
const x = 3

fn main() {
	_ := &x
}
```
Works:
```v
const x = int(3)

fn main() {
	_ := &x
}
```

### Expected Behavior

Both versions work.

### Current Behavior

```
/tmp/v_1000/const_ptr.13403185457188648864.tmp.c:12442: error: lvalue expected
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

### Reproduction Steps

above

### Possible Solution

https://github.com/vlang/v/blob/815439a381b9f6ae1e39d373793c2407e7c4f224/vlib/v/gen/c/cgen.v#L5311-L5319

### V version

0.4.0 815439a

### Environment details (OS name and version, etc.)

OS: linux, Pop!_OS 22.04 LTS
Processor: 16 cpus, 64bit, little endian, 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

getwd: /home/turiiya/Dev/vlang/v
vexe: /home/turiiya/Dev/vlang/v/v
vexe mtime: 2023-08-16 05:27:47

vroot: OK, value: /home/turiiya/Dev/vlang/v
VMODULES: OK, value: /home/turiiya/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.34.1
Git vroot status: weekly.2023.33
.git/config present: true

CC version: cc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by spytheman** [comment]
imho the first case should be a checker error instead. 

`const x = 3` is treated as a literal, and implemented as a C macro. 

It is substituted everywhere it is used at compile time, and thus does not have a specific address.

`const x = int(3)` is implemented as a constant global in C, i.e. it has a single location, and thus an address as well.

**Comment by ttytm** [comment]
For me a proper error would be satisfying enough.
I think this will also be the solution that will be the simplest to implement while covering the most cases at the same time.
