### ISSUE TITLE
*Assign ops don't flag variables as being used

### ISSUE THREAD

**Issue by danipoma** [vlang/v#19154]
### Describe the bug

Hello,

*Assign ops (+=, -=, etc.) don't flag variable as used. When *Assign op occurs in Go, it is flagged as used.

I have prepared script with all variety of ops and put it to [V playground](https://vosca.dev/p/bba685d818) which can be used to prove this issue and also as a testing suite to test whether this issue has been sorted.

Just in case I have also added script content to this issue.
```v
fn main() {
	// Add - The addition operator +
	mut var_add := 10
	var_add = var_add + 1

	// Add one shorthand - The addition assignment operator ++
	mut var_add_shorthand := 10
	var_add_shorthand++

	// AddAssign - The addition assignment operator +=
	mut var_add_assign := 10 // UNUSED VARIABLE
	var_add_assign += 1

	// Sub - The subtraction operator -
	mut var_sub := 10
	var_sub = var_sub - 1

	// Sub one shorthand - The addition assignment operator --
	mut var_sub_shorthand := 10
	var_sub_shorthand--

	// SubAssign - The subtraction assignment operator -=
	mut var_sub_assign := 10 // UNUSED VARIABLE
	var_sub_assign -= 1

	// Div - The division operator /
	mut var_div := 10
	var_div = var_div / 2

	// DivAssign - The division assignment operator /=
	mut var_div_assign := 10 // UNUSED VARIABLE
	var_div_assign /= 2

	// Mul - The multiplication operator *
	mut var_mul := 10
	var_mul = var_mul * 2

	// MulAssign - The multiplication assignment operator *=
	mut var_mul_assign := 10 // UNUSED VARIABLE
	var_mul_assign *= 2

	// Rem - The remainder operator %
	mut var_rem := 10
	var_rem = var_rem % 2

	// RemAssign - The remainder assignment operator %=
	mut var_rem_assign := 10 // UNUSED VARIABLE
	var_rem_assign %= 2

	// Neg - The unary negation operator -
	mut var_neg := 10
	var_neg = -var_neg

	// Not - The unary logical negation operator !
	mut var_not := false
	var_not = !var_not

	// BitAnd - The bitwise AND operator &
	mut var_bit_and := u8(0xFF)
	var_bit_and = var_bit_and & 0xF

	// BitAndAssign - The bitwise AND assignment operator &=
	mut var_bit_and_assign := u8(0xFF) // UNUSED VARIABLE
	var_bit_and_assign &= 0xF

	// BitOr - The bitwise OR operator |
	mut var_bit_or := u8(0x6)
	var_bit_or = var_bit_or | 0xF

	// BitOrAssign - The bitwise OR assignment operator |=
	mut var_bit_or_assign := u8(0x6) // UNUSED VARIABLE
	var_bit_or_assign |= 0xF

	// BitXor - The bitwise XOR operator ^
	mut var_bit_xor := u8(0xFF)
	var_bit_xor = var_bit_xor ^ 0xF

	// BitXorAssign - The bitwise XOR assignment operator ^=
	mut var_bit_xor_assign := u8(0xFF) // UNUSED VARIABLE
	var_bit_xor_assign ^= 0xF

	// Shl - The left shift operator <<
	mut var_shl := u8(0x1)
	var_shl = var_shl << 4

	// ShlAssign - The left shift assignment operator <<=
	mut var_shl_assign := u8(0x1) // UNUSED VARIABLE
	var_shl_assign <<= 4

	// Shr - The right shift operator >>
	mut var_shr := u8(0xFF)
	var_shr = var_shr >> 4

	// ShrAssign - The right shift assignment operator >>=
	mut var_shr_assign := u8(0xFF) // UNUSED VARIABLE
	var_shr_assign >>= 4
}
```

### Expected Behavior

*Assign ops flags variable being used

### Current Behavior

*Assign ops don't flag variable as being used

### Reproduction Steps

[V playground](https://vosca.dev/p/50f4cdcfba)

```v
fn main() {
	// AddAssign - The addition assignment operator +=
	mut var_add_assign := 10 // UNUSED VARIABLE
	var_add_assign += 1
}
```

### V version

V full version: V 0.4.0 8ae962b.d0e6057

### Environment details (OS name and version, etc.)

V full version: V 0.4.0 8ae962b.d0e6057
OS: linux, Ubuntu 22.04.3 LTS (WSL 2)
Processor: 4 cpus, 64bit, little endian, AMD Ryzen 7 4800H with Radeon Graphics

getwd: /home/danipoma
vexe: /home/danipoma/.local/bin/v/v
vexe mtime: 2023-08-16 17:27:55

vroot: OK, value: /home/danipoma/.local/bin/v
VMODULES: OK, value: /home/danipoma/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.34.1
Git vroot status: weekly.2023.32.2-28-gd0e60575
.git/config present: true

CC version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by JalonSolov** [comment]
This is correct behavior.  You assign values, and update values, but you never _used_ those values.  To mark them as used, you actually have to use the values somehow, either adding them to another, assigning them to a struct field, printing the values, etc.

Simply manipulating the value directly does not count as using it, because the value is never "seen" outside the variable itself.
