### ISSUE TITLE
`thread := 5` compiles, but it should not (thread is a reserved type name)

### ISSUE THREAD

**Issue by spytheman** [vlang/v#19161]
**V doctor:**
```
V full version: V 0.4.0 2fec2fa.c5e1c8e
OS: linux, Ubuntu 20.04.6 LTS
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i3-3225 CPU @ 3.30GHz

getwd: /v/vnew
vexe: /v/vnew/v
vexe mtime: 2023-08-17 14:49:06

vroot: OK, value: /v/vnew
VMODULES: OK, value: /home/delian/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.41.0
Git vroot status: weekly.2023.33-5-gc5e1c8ee-dirty
.git/config present: true

CC version: cc (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg i.v`
```v
thread := 1

```

**What did you expect to see?**

a compiler error: invalid use of reserved type `thread` as a variable name

**What did you see instead?**
```
i.v:1:1: warning: unused variable: `thread`
    1 | thread := 1
      | ~~~~~~
```

**Comment by islonely** [comment]
"thread" isn't listed as a keyword here either if whoever fixes the bug is interested in fixing this as well.
https://github.com/vlang/v/blob/master/doc/docs.md#appendix-i-keywords

**Comment by PottierLoic** [comment]
I did a PR on sdl, it was using thread as variable name on some function parameters.
I have the little fix ready to be pushed.
I can make a PR here too, when sdl's PR is merged if it's okay for you.
