### ISSUE TITLE
can't import sqlite on OSX m.1

### ISSUE THREAD

**Issue by despiegk** [vlang/v#19195]
### Describe the bug

```bash
v -cg run /Users/despiegk1/code/github/freeflowuniverse/crystallib/auth/examples/basic_auth/server/app.v
code/github/freeflowuniverse/crystallib/auth/examples/basic_auth/server/app.v:3:1: builder error: cannot import module "sqlite" (not found)
```

while sqlite is installed, 

### Expected Behavior

would expect to import

### Current Behavior

can't load sqlite

### Reproduction Steps

example script

```bash
import sqlite
import main
fn main() {

	db := sqlite.connect('foo.db') or { panic(err) }
	db.synchronization_mode(sqlite.SyncMode.off)
	db.journal_mode(sqlite.JournalMode.memory)
}

```

### V version

Current V version: V 0.4.0 50ed731, timestamp: 2023-08-19 23:57:20 +0300

### Environment details (OS name and version, etc.)

OSX m.1

**Comment by despiegk** [comment]
just checked in python, there it works, commandline sqlite3 also installed

I think it used to work before, so maybe something changed when updating V?

or I broke something?

**Comment by joe-conigliaro** [comment]
Hi @despiegk 

The sqlite module is under `db`. Can you try with `import db.sqlite` ?
There is an example in `examples/database/sqlite.v`

**Comment by spytheman** [comment]
> I think it used to work before, so maybe something changed when updating V?

Yes, it did work before late July this year.

The `sqlite` module was deprecated at the start of the year in 64558df 2023-01-13, and removed in a421e48 2023-07-25 .

It is replaced by the `db.sqlite` module, which has the same API.

**Comment by medvednikov** [comment]
That's why I'm against changes like this.

If we do introduce a change like this, the compiler should catch it and show a hint that the module has been moved and "db.sqlite" should be used instead.

**Comment by JalonSolov** [comment]
The compiler _did_ show that for 6 months.  Even if it was shown for 6 years, unless the old module was _never_ removed, this situation would be hit eventually.
