### ISSUE TITLE
Mutable function arguments will be allowed

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#192]
After a discussion on Slack and re-reading [this older discussion](https://news.ycombinator.com/item?id=19102138) I decided to allow mutable function arguments.

It is simply not possible to implement a predictable optimization that converts functions returning values to functions modifying them in-place.

If such optimization is not implemented, performance will suffer, primarily because of extra allocations.

This optimization would be compiler magic, and it would not be clear to the developer when it takes place and how. V is supposed to be a simple and predictable language.

And it would still be impossible to build the most efficient solutions, like reversing an array in-place:

```
fn reverse(arr mut []int) {
  for i := 0; i < arr.len / 2; i++ {
    swap(arr[i], arr[arr.len - 1 - i])
  }
}
```

Without mutable arguments we can only do

```
fn reverse(arr []int) []int {
        mut res := [0; arr.len]
        for i, val in arr {
                res[arr.len - 1 - i] = val
        }
        return res
}
```

and there's no way to optimize it to remove the extra allocation.

Having immutable arguments is nice, but not possible, unless you go full FP.

F#, Python, and all other languages that support functional style, allow mutating arguments.

This also bring consistency. Before this change it was possible to mutate the receiver, but not the other arguments. But the receiver is an argument.

**Comment by iangudger** [comment]
Couldn't one use a method on a type to do the in-place reversal?

**Comment by medvednikov** [comment]
> Couldn't one use a method on a type to do the in-place reversal?

Yes, you could do

```
fn (r mut Reverser) reverse() {
  for i := 0; i < r.arr.len / 2; i++ {
    swap(r.arr[i], r.arr[r.arr.len - 1 - i])
  }
}

mut arr := [1,2,3]
mut r := Reverser{arr}
r.reverse()
arr = r.arr
```

But this feels very verbose and strange compared to

```
mut arr := [1,2,3]
reverse(mut &arr)
```

**Comment by iangudger** [comment]
> But this feels very verbose and strange

I would argue the same about many functional programming techniques and many people would argue the same about Go in general (especially in relation to error handling), but in both cases there are real benefits.

**Comment by PavelVozenilek** [comment]
It would be useful to have "pure" functions, which do not modify parameters, can call only other pure functions, do not call C code, etc.  



Signature may look like:

```
fn! foo(int x, int y) // fn! means pure function
{
  ...
}
```

and, more importantly, to improve code understanding, pure function should be invoked differently, e.g.:

`foo((10, 20)); // double (()) means pure function
`
or 

`foo!(10, 20); // the ! means pure
`

**Comment by medvednikov** [comment]
V functions are pure by default. Although they can call C code.

**Comment by medvednikov** [comment]
> I would argue the same about many functional programming techniques and many people would argue the same about Go in general (especially in relation to error handling), but in both cases there are real benefits.

True. It can also be simplified:

```
mut arr := [1,2,3]
mut r := Reverser{}
arr = r.reverse(arr)
```

Now there's only one extra line.

**Comment by medvednikov** [comment]
Mutable args have been implemented, the docs have been updated:

https://vlang.io/docs#recvs

Live in 0.0.8 a bit later today.

**Comment by PavelVozenilek** [comment]
If some of the planned optimizations will be implemented, it would be useful to document them very thoroughly in advanced section of the docs. If they become part of the language, it would allow people to use them without fear.

**Comment by medvednikov** [comment]
There will be no hidden magical optimizations, this is one of the benefits of this decision.

**Comment by PavelVozenilek** [comment]
This new direction may have impact on another feature: hot code reloading. With functional language code swapping can be easy to implement and safe. 

Mostly functional language Erlang has excellent support for it, not just as a debugging trick, but as feature to be employed during runtime to attain high availability, even with self-repair capability.

Ordinary languages, as C++, have to use tricks (like DLL reloading), and it is still very brittle and hard to use.

If V retains ability to compile code very fast, then code reloading won't be something very desirable.
