### ISSUE TITLE
union array assignment breaks system & segfault

### ISSUE THREAD

**Issue by nbrugger-tgm** [vlang/v#19239]
### Describe the bug

Its possible to break typesafety using uniontypes which leads to segfauls since you try to read a string from the 8byte reserved for int (as example).

### Reproduction Steps

paste this code into playground or compile locally and run
```v
type Cool = string|int
fn main() {
	mut my_array := [1]int{}
	add_string(mut &my_array)
}
fn add_string(mut arr []Cool){
	arr[0] = "string"
}
```

### Expected Behavior

The compiler errors with something like:
`cannot assign a mutable '[]int' to '[](int|string)' because because '[]string' doesn't implents 'set(int, int)'`
or  some other compile time message

### Current Behavior

the compiler does not complain and the binary crashes at runtime

### Possible Solution

Tightening typechecks for union types on `mut &` references  (this also affects interfaces/structs -> all heap/reference data tyopes)

Alternatively, you could forbid references to mutable unions, since they rarely make sense anyway (there is no type that can validly & safely be assigned to a `[]anyunion` same for `struct { field anyunion }`

Unions are not that easy when mutability is a thing. The problem is looking at both sides it seems to make sense.
1. Of course a `mut &[]string` fits into a `mut &[](string|int)` because `string` fits into `int | string`
2. Of course a `string` can be written into a `mut &[](string | int)` because well its a array with "string" **AND** "ints" 

There are multiple ways to address this.  Maybe look at go how they do it or re-do unions how they are in rust they do not have the problem because of the nature of their "explicitly named unions" called ""enums""

### Additional Information/Context

TS has the exact same issue (except that it doesn't crash because ---- well js
https://github.com/microsoft/TypeScript/issues/55451

### V version

any

### Environment details (OS name and version, etc.)

V full version: V 0.4.0 320057d
OS: linux, Ubuntu 23.04
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7

getwd: /home/.../workspace/priv/vexperiment
vexe: /home/.../workspace/priv/vexperiment/vlang/v
vexe mtime: 2023-08-07 08:40:38

vroot: OK, value: /home/..../workspace/priv/vexperiment/vlang
VMODULES: OK, value: /home/..../.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.39.2
Git vroot status: weekly.2023.31-17-g320057df (121 commit(s) behind V master)
.git/config present: true

CC version: cc (Ubuntu 12.3.0-1ubuntu1~23.04) 12.3.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by shove70** [comment]
Resolved on latest master.
