### ISSUE TITLE
Array initialization using fixed size array gives possible garbage data

### ISSUE THREAD

**Issue by StroveLight** [vlang/v#19244]
### Describe the bug

I initialize the array using `my_array := [foo, bar]`, with foo and bar being arrays of fixed size (tested using size 2).

Currently the array gives values that are neither of foo nor bar. Sometimes the values of the result changes each time I run the code (happens on V playground only)

### Reproduction Steps

The following codes have this issue:
first one:
```
fn main(){
	a := [0.312, 12.0213]!
	b := [0.23, 2131.213]!
	ab := [a, b]
	println(ab)
}
```

second one (b is saved properly):
```
fn main(){
	a := [0.312, 12.0213]!
	b := [0.23, 2131.213]!
	mut ab := [a]
	ab << b
	println(ab)
}
```

third one (similar to first one but using mut and fixed size in `ab`)
```
fn main(){
	a := [0.312, 12.0213]!
	b := [0.23, 2131.213]!
	mut ab := [a,b]!
	println(ab)
}
```

### Expected Behavior

I expect the output to be:
`[[0.312, 12.0213], [0.23, 2131.213]]`

The statement before is the equivalent to expect the code to work the same as the following one:
```
fn main(){
	a := [0.312, 12.0213]!
	b := [0.23, 2131.213]!
	mut ab := [][2]f64{}
	ab << a
	ab << b
	println(ab)
}
```

### Current Behavior

first one:
```
[[2.1888592e+07, 2.1888576e+07], [0.0, 0.0]]
```

second one:
```
[[2.1888592e+07, 0.0], [0.23, 2131.213]]
```

third one:
```
[[2.1888592e+07, 2.1888576e+07], [0.0, 0.0]]
```

### V version

V 0.4.0 55575fd

### Environment details (OS name and version, etc.)

V full version: V 0.4.0 045adb6.55575fd
OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 8 cpus, 64bit, little endian,

getwd: C:\Users\Usuario\Desktop\Universidad\mag\v_test\09b
vexe: C:\Program Files\v\v.exe
vexe mtime: 2023-08-31 01:48:32

vroot: contains spaces, value: C:\Program Files\v
VMODULES: OK, value: C:\Users\Usuario\.vmodules
VTMP: OK, value: C:\Users\Usuario\AppData\Local\Temp\v_0

Git version: git version 2.40.1.windows.1
Git vroot status: weekly.2023.26-410-g55575fd7
.git/config present: true

CC version: cc (Rev6, Built by MSYS2 project) 13.1.0
thirdparty/tcc status: thirdparty-windows-amd64 e90c2620

**Comment by spytheman** [comment]
Perhaps related:
```v
mut ab := [][2]f64{}
ab[0] = [0.312, 12.0213]!
ab[1] = [0.23, 2131.213]!
println(ab)
```
produces a cgen error.

while this works:
```v
ab := [ [0.312, 12.0213]!,  [0.23, 2131.213]! ]
println(ab)
```
