### ISSUE TITLE
Add vlang.io to homebrew-core

### ISSUE THREAD

**Issue by vbrazo** [vlang/v#1925]
The idea is to add the V programming language to Homebrew: https://github.com/Homebrew/homebrew-core/pull/44138 and allow developers to easily install the language by running `brew install vlang`.

I've included the `make` and `v symlink`. 

Let me know your thoughts.

**Comment by vbrazo** [comment]
![QR2koqFXWM](https://user-images.githubusercontent.com/1292556/64686720-f4ffa900-d43d-11e9-98d6-5b63678be830.gif)

**Comment by medvednikov** [comment]
That would be great, thanks @vbrazo

**Comment by crunchtime-ali** [comment]
vlang has landed in homebrew-core two weeks ago with https://github.com/Homebrew/homebrew-core/pull/55763
Therefore this issue can be closed. Happy `brew install vlang`ing :shipit:
