### ISSUE TITLE
C error when getting enum value from string

### ISSUE THREAD

**Issue by wygsh** [vlang/v#19258]
### Describe the bug

Getting the enum value from a string results in a C error

### Reproduction Steps

```v
module main

enum Test {
	one
	two
	three
}

fn main() {
	_ := Test('one')
}
```

### Expected Behavior

Compile

### Current Behavior

/tmp/v_1002/main.3699384588971340413.tmp.c:12471: error: cannot convert 'struct string' to 'enum <anonymous>'
...

### V version

V 0.4.0 5848610

### Environment details (OS name and version, etc.)

V full version: V 0.4.0 52a055b.5848610
OS: linux, Linux version 6.4.12-200.fc38.x86_64 (mockbuild@30894952d3244f1ab967aeda9ed417f6) (gcc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1), GNU ld version 2.39-9.fc38) #1 SMP PREEMPT_DYNAMIC Wed Aug 23 17:46:49 UTC 2023
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz

getwd: /home/user/Projects/v-testing/mineflayer
vexe: /home/user/.local/lib/v/v
vexe mtime: 2023-09-01 21:53:56

vroot: OK, value: /home/user/.local/lib/v
VMODULES: OK, value: /home/user/.vmodules
VTMP: OK, value: /tmp/v_1002

Git version: git version 2.41.0
Git vroot status: weekly.2023.30-233-g58486104
.git/config present: true

CC version: cc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by JalonSolov** [comment]
What your code would be doing (if it was supported), is casting a string to an enum.  However, that isn't valid in V, so you should definitely get an error message, just one from V instead of the C compiler.

If you really want an enum from a string, the proper way to do it is
```v
	_ := Test.from_string('one')
```
