### ISSUE TITLE
bug of scope

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#193]
may be same bug as #130

Put follow code into this page https://vlang.io/play

```
fn main() {
if true{
	types := ['game', 'web', 'tools', 'GUI']
}
	for typ in types {
		println('Hello, $typ developers!')
	}
}
```

Then I got `You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.`

**Comment by medvednikov** [comment]
Fixed.
