### ISSUE TITLE
`net/http/server` get some `error sending response: net: op timed out; code: 9`

### ISSUE THREAD

**Issue by xiusin** [vlang/v#19307]
### Describe the bug

I'm not sure if it's an issue with my web framework or the standard library. Currently, using built-in static resources frequently triggers this error.

<img width="787" alt="image" src="https://github.com/vlang/v/assets/36065131/18148e9c-731e-490b-a144-f7cbbdb1bc4a">

### Reproduction Steps

[`xiusin/very/examples/...` ](https://github.com/xiusin/very/tree/main/examples)

This is a test case.

```
v run build_bin_data.vsh
v . 
./examples
```

### Expected Behavior

success

### Current Behavior

`error sending response: net: op timed out; code: 9`

### V version

V 0.4.1 f18086c

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.1 3a91a5e.f18086c
OS: macos, macOS, 13.5.1, 22G90
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz

getwd: /Users/xiusin/projects/src/github.com/xiusin/very/examples
vexe: /opt/v/v
vexe mtime: 2023-09-07 09:43:43

vroot: OK, value: /opt/v
VMODULES: OK, value: /Users/xiusin/.vmodules
VTMP: OK, value: /tmp/v_501

Git version: git version 2.23.0
Git vroot status: 0.4-421-gf18086cd
.git/config present: true

CC version: Apple clang version 14.0.0 (clang-1400.0.29.202)
thirdparty/tcc status: thirdparty-macos-amd64 46662e20-dirty

```

**Comment by spytheman** [comment]
Try recompiling with `v -d net_blocking_sockets .`, and see if that will help with the timeouts.

**Comment by spytheman** [comment]
Did it work?

**Comment by xiusin** [comment]
@spytheman 
![image](https://github.com/vlang/v/assets/36065131/e98e34bb-6a3c-4df0-8267-ee060ac20f4e)

I tried the method you suggested, and it seems to be working fine now. Thank you.
