### ISSUE TITLE
Complex structs with custom to_toml lead to compile time errors

### ISSUE THREAD

**Issue by qtc-de** [vlang/v#19300]
### Describe the bug

A few weeks ago, a generic `encode` method was added to the `toml` module (https://github.com/vlang/v/commit/1bed0b5e6830cd2dd9f9df265b76e0af3d39ba4e). While this is pretty useful, the implementation is flawed and it is no longer possible to encode complex types that have a custom `to_toml` method. This is caused by the default encoding method being always part of the `encode` method. This method expects types to be *encodeable* and only specific types are allowed (need to be castable to `toml.Any` at some point of time). However, from my point of view, each type should be encodable as long as it defines a `to_toml` method.

### Reproduction Steps

The following code lists a minimal example:

```v
import toml

struct Example {
	array []Problem
}

struct Problem {
}

pub fn (example Example) to_toml() string
{
	return '[This is Valid]'
}

fn main()
{
	example := Example{}
	toml.encode(example)
}
```

### Expected Behavior

The above example should compile, as the `toml.encode` method should return `[This is Valid]`, which is valid *toml* produced by the custom `to_toml` method.

### Current Behavior

The following compile time error is thrown:

```v
v/vlib/toml/toml.v:102:12: error: cannot cast `Problem` to `toml.Any`
  100 |             mut arr := []Any{}
  101 |             for v in value {
  102 |                 arr << Any(v)
      |                        ~~~~~~
  103 |             }
  104 |             mp[field.name] = arr
```

### Possible Solution

The problem is caused by the following function https://github.com/vlang/v/blob/1bed0b5e6830cd2dd9f9df265b76e0af3d39ba4e/vlib/toml/toml.v#L80

```v
pub fn encode[T](typ T) string {
	$for method in T.methods {
		$if method.name == 'to_toml' {
			return typ.$method()
		}
	}

	mp := encode_struct[T](typ)
	return mp.to_toml()
}
```

If a `to_toml` method exists, the compile time statements in the beginning create the proper return value. However, the rest of the function seems to be still evaluated by the type checker and causes the error. The most obvious solution would be to prevent compilation of the latter part, if a `to_toml` method has been found.

I thought about possible implementations, but it seems not that easy. What I could think of is an `$if implements` operator, which could be used to replace the *for loop* with an *if else* condition (after creating an Interface like `CustomEncoder` that requires implementors to define a `to_toml` method). Another possible solution would be something like a `$break` statement, that drops all following definitions within a function once it is hit. No idea if this makes sense or not :shrug: 

### V version

V 0.4.1 3042857.f18086c

### Environment details (OS name and version, etc.)

Not relevant

**Comment by ttytm** [comment]
That's true. We really need to make sure it short circuits after the return without doing the rest of the comptime evaluation. 

Doing some quick tries I can't force it to early return without the comptime evaluation.
Improving the generic encoding function to not run into the type error can fix this as well, but stoping further evaluation after a return would be 💯

**Comment by spytheman** [comment]
@qtc-de can you please confirm if your problem is solved after `v up` (latest v)?

**Comment by spytheman** [comment]
I am closing this, since I think #19338 solved it.

**Comment by qtc-de** [comment]
Sorry for the late response. #19338 indeed solved the edge case given above. However, I only chose this edge case to provide a basic example. My actual problem is related to the `map` type not being handled correctly, which still causes compile time errors in the latest version.

Based on #19338 I just submitted #19408 which catches my edge case and hopefully most others :slightly_smiling_face:
