### ISSUE TITLE
v fmt breaks code

### ISSUE THREAD

**Issue by d-p-y** [vlang/v#19342]
### Describe the bug

I was attempting to format code (part of just released [vpassman](https://github.com/d-p-y/vpassman) project) and I faced problem with one of the v files).

### Reproduction Steps

create file `unit.v` with content
```
module model

[heap]
pub type Unit = struct {}

pub const unit = Unit{}
```

attempt to format it using `v fmt -w unit.v`

### Expected Behavior

File `unit.v` stays unchanged.

### Current Behavior

`v fmt` reformatted it using some strange symbol
```
module model

pub type Unit = _VAnonStruct1

pub const unit = Unit{}
```

### V version

V 0.4.1 5d1f87c

### Environment details (OS name and version, etc.)

V full version: V 0.4.1 5d1f87c
OS: linux, Ubuntu 22.04.3 LTS
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz

getwd: /home/dominik/Projects/vpassman/src-service/model
vexe: /home/dominik/Projects/vlang/v
vexe mtime: 2023-09-13 14:19:29

vroot: OK, value: /home/dominik/Projects/vlang
VMODULES: OK, value: /home/dominik/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.34.1
Git vroot status: weekly.2023.37-4-g5d1f87c5
.git/config present: true

CC version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by StunxFS** [comment]
why are you trying to create an anonymous struct, when you can do the following:
```v
module model

struct Unit { }

pub const unit = Unit{}
```

**Comment by ttytm** [comment]
Also ran into the issue in a few other scenarios. If I remember correctly those were occasions where an anon struct would have made sense. But time was short and I didn't took note. For the re-pro above what @StunxFS is saying is right I think.

V fmt doesn't have to break it, but it could (or should) come with an additional warning with the details explaining to use it like this might be the way to go.

**Comment by d-p-y** [comment]
thanks yuyi98 !
