### ISSUE TITLE
v build module suddenly fails after some executions

### ISSUE THREAD

**Issue by LorenzoPirro** [vlang/v#1934]
V version: 1.18 c66fbd9 
OS: MacOSx Mojave 10.14.6

I've compiled several times a module i'm writing and after many good executions with a correct iter of **v build module** command, the compiler can't find the object file.
<img width="1188" alt="Schermata 2019-09-11 alle 23 23 13" src="https://user-images.githubusercontent.com/17650857/64737195-93e2de80-d4ec-11e9-9bcb-8a9f435442bf.png">

**Comment by joe-conigliaro** [comment]
@LorenzoPirro looks like something is wrong with the paths, do they look like that on a successful compile? `/Users/lorenzopirro//.vmodules/./jsonrpc.o`

**Comment by LorenzoPirro** [comment]
@joe-conigliaro Absolutly i'm working always on the same path. In fact i've created a new 'ok' module and it fails in the same way. I've noted that this problem is appeared after v up command.

**Comment by joe-conigliaro** [comment]
@LorenzoPirro, What I meant was, when compilation succeeds does the path look like that with the multiple `/` in it?
Can you please paste the output of compilation with the `-show_c_cmd` flag: `v -show_c_cmd my.v`

**Comment by medvednikov** [comment]
Was it fixed @LorenzoPirro ?

**Comment by LorenzoPirro** [comment]
@medvednikov this problem no longer appears after some commits, in fact now `file.o.tmp.c` is found instead of `file.o`. Maybe only a writing mistake? But there's a **different point here** now:
<img width="1264" alt="Schermata 2019-09-25 alle 00 28 34" src="https://user-images.githubusercontent.com/17650857/65555013-85081d00-df2b-11e9-8ae3-e42e688cb3f7.png">

And this error should be wrong, since i've only a JrpcClient declaration and there's no an other in others libraries.
