### ISSUE TITLE
FreeBSD - Could not create new socket

### ISSUE THREAD

**Issue by HUSKI3** [vlang/v#19344]
### Describe the bug

Hello all,
I wrote a webserver application in vlang to forward requests to different servers, a balancer of sorts. The original environment for it's development was Ubuntu 20.04 where it works flawlessly, but when I'm trying to build it on FreeBSD I have the following issue:
[Balancer] Start balancing with pivot on server #0
V panic: failed to listen 0 net: socket error: 43; code: 43; could not create new socket

### Reproduction Steps

```v
module lib

import vweb
...
struct App {
	vweb.Context
mut:
	balancer LoadBalancer
}
...
fn new_app(mut balancer LoadBalancer) &App {
	return &App{
		balancer: balancer
	}
}

['/'; post; get]
pub fn (mut app App) generic() vweb.Result {
	println("[Balancer] Got request at root.")
	mut query := app.query.clone()
	app.balancer = new_balancer()
	r := app.balancer.forward(mut ForwardCommon{mut app, mut query, true})
	_ := query // ignore warning
	return r
}
...
// Part where it fails
pub fn (mut balancer LoadBalancer) balance_common() {
	println("[Balancer] Start balancing with pivot on server #${balancer.current}")

	vweb.run_at(new_app(mut balancer), vweb.RunParams{
		port: 8089
	}) or { panic(err) }
}
```

### Expected Behavior

The web server should start on the defined port with no issues and handle requests.

### Current Behavior

logs
```
[Balancer] Start balancing with pivot on server #0
V panic: failed to listen 0 net: socket error: 43; code: 43; could not create new socket
v hash: 4d8b2e9
0x3a7a22 <lib__LoadBalancer_balance_common+0x1b2> at /.../project/project
0x3aa012 <main__main+0x2b2> at /.../project/project
```

Can't provide any more error logs as there are none. I've narrowed it down to the `net__new_tcp_socket(net__AddrFamily family)` failing

### Additional Information/Context

The target system where it should build & work on is running 13.0-STABLE FreeBSD

### V version

Current V version: V 0.4.1 5d1f87c, timestamp: 2023-09-13 15:10:26 +0300

### Environment details (OS name and version, etc.)

V full version: V 0.4.1 5d1f87c
OS: freebsd, 13.0-STABLE, FreeBSD 13.0-STABLE #0 stable/13-n249223-40b816bd4f0: Thu Feb  3 02:45:10 UTC 2022     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC
Processor: 20 cpus, 64bit, little endian

getwd: /usr/home/user/project
vexe: /usr/home/user/v/v
vexe mtime: 2023-09-13 20:22:05

vroot: OK, value: /usr/home/user/v
VMODULES: OK, value: /home/user/.vmodules
VTMP: OK, value: /tmp/v_1002

Git version: git version 2.41.0
Git vroot status: weekly.2023.37-4-g5d1f87c5
.git/config present: true

CC version: FreeBSD clang version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)
thirdparty/tcc: N/A

**Comment by HUSKI3** [comment]
Found the issue!

With a simple but poorly put together C program. It turns out the system doesn't support AF_INET6.... odd bug?

**Comment by HUSKI3** [comment]
Is there any option for vweb to use ipv4 ie AF_NET instead?

**Comment by HUSKI3** [comment]
Fixed :)

**Comment by spytheman** [comment]
> Fixed :)

How did you fix it?

**Comment by HUSKI3** [comment]
@spytheman 

It was an issue with my server. I created a simple C web server to check if it could create a socket. I highly recommend checking the error codes from the socket on: https://man.freebsd.org/cgi/man.cgi?query=errno&sektion=2&manpath=freebsd-release-ports

In my case I just made it so that the application used only ipv4
```
vweb.run_at(new_app(mut balancer), vweb.RunParams{
		family: .ip  // this sets the family to ipv4
		host: '0.0.0.0'
		port: 8089
	}) or { panic(err) }
```
