### ISSUE TITLE
Do Ixy in V

### ISSUE THREAD

**Issue by Immortalin** [vlang/v#1937]
https://github.com/ixy-languages/ixy-languages

**Comment by dumblob** [comment]
This is a very interesting observation. Especially:

>Ixy can already achieve a high performance with relatively low batch sizes of 32-64 because it is a full user space driver. Other user space packet processing frameworks like netmap that rely on a kernel driver need larger batch sizes of 512 and above to amortize the larger overhead of communicating with the driver in the kernel.

Thanks for the pointer @Immortalin.

On the other hand I don't see any connection to *V* - or am I missing something?

**Comment by gslicer** [comment]
@Immortalin as long V emits C code that is beeing compiled, I would expect to perform somehwre between C and Rust - when V is able to compile & optimize to machine-code directly it might be indeed a good benchmark

**Comment by medvednikov** [comment]
> as long V emits C code that is beeing compiled, I would expect to perform somehwre between C and Rust

like the home page says, the performance is always going to be within 3% of C
