### ISSUE TITLE
compiling (boolean expression) ^ (boolean expression) fails

### ISSUE THREAD

**Issue by spytheman** [vlang/v#1938]
**V version:** V 0.1.19 a555b1f
**OS:** Ubuntu 16.04.3 LTS

**What did you do?**
I tried running this program:
```v
b := (1!=0) ^ (3!=0)
println( b )
```
**What did you expect to see?**
a) a type error, because boolean can not be bitwise xored with another boolean
b) booleans on both sides of the ^ be casted to ints, then xored bitwise, and result assigned to b

**What did you see instead?**
```shell
0[09:20:23] /v/v $ vlang run xor_bug.v 
xor_bug.tmp.c: In function ‘main’:
xor_bug.tmp.c:3522:25: error: expected identifier or ‘(’ before numeric constant
  bool b= ( 1 != 0 ) , ( 3 != 0 ) ;
                         ^
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
1[09:22:52] /v/v $ 
```
NB: the `^` produced `,` in the generated C code.

**Comment by medvednikov** [comment]
Fixed: `operator | not defined on bool`

**Comment by medvednikov** [comment]
Same with & and |
