### ISSUE TITLE
Bug: imagine not looking good

### ISSUE THREAD

**Issue by ab7022** [vlang/v#19381]
### Describe the bug

The logo is bigger then its parent element and i can fix it and its not responsive though as you can see in this picture 

### Reproduction Steps

> 

> 
![Screenshot_20230919-030928](https://github.com/vlang/v/assets/76129251/88a2faa3-fc21-4df3-8752-8f738adcbe1b)

### Expected Behavior

It should be within it's parents element size

### Current Behavior

Over sized 

### V version

Don't know 

### Environment details (OS name and version, etc.)

Don't know 
> [!IMPORTANT]
> You can vote for this issue using the 👍 reaction. More votes increase the issue's priority
> for developers.
>
> Take into account that only the 👍 reaction counts as a vote.
> Only reactions to the issue itself will be counted as votes, not comments.

**Comment by medvednikov** [comment]
Should be fixed, can you check?
