### ISSUE TITLE
how to put char \ in string?

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#194]
Put follow code into this page https://vlang.io/play
```
fn main() {
   println('\\')
}
```
Then I got 
```
test.v:6
expected `)` but got `EOF`
```

**Comment by nachoverdon** [comment]
I was playing around with this and if you type this:
```
fn main() {
	mut s := ''
	s = '\\'
	println(s)
}
```

and hit Run, some characters will be append to the code editor

**Comment by medvednikov** [comment]
Fixed.

It was only broken when the string was ending with `\\`.
