### ISSUE TITLE
naming of v source files impacts the compiler behaviour

### ISSUE THREAD

**Issue by schoko123** [vlang/v#1940]
**V version:** V 0.1.19 a555b1f
**OS:** Linux Mint 19.1

**What did you do?**
test.v with content:

import net.urllib
import http

pub fn main() {
        urls := [
                'http://bugurl'
        ]
        for url in urls {
                println('Getting Bugs: $url ')
        }
}

then:

./v compile test.v

and run
./test
with output:
Getting Bugs: http://bugurl

Then renamed the source file test.v into test_test.v
and then a compiler run
./v compile test_test.v

and a execute
./test_test

and no println output nothing at all.

Is there a special meaning with test in the source file name ?

**What did you expect to see?**
The same output
 
**What did you see instead?**

**Comment by medvednikov** [comment]
Fixed.

It should also then show an error message if there are no test_* functions in a file.

@avitkauskas  This has been implemented as well.
