### ISSUE TITLE
weird bug with http module

### ISSUE THREAD

**Issue by silisium** [vlang/v#1942]
**V version:** 0.1.19 b6ebe08
**OS:** 
windows 10
**What did you do?**
```v
import http

struct message {
    txt string
}

println('hello')
```

**What did you expect to see?**
successful compilation
 
**What did you see instead?**
```
get_type() bad type
fn error_msg(message, val string) string {
                        ^
E:\v\vlib\net\urllib\urllib.v:31:25: unknown type `net_dot_urllib.val`
```

**note:**
this has something to do with the struct name `message` and `http` module

changing struct name to other than `message` or removing `import http` work fine

i also noticed from the output error that the function `error_msg` has a parameter called `message` i guess it could be a variable mismatch

**Comment by Bowero** [comment]
Currently, this will result in an error:

```v
[bowero]% v run test.v
test.v:5:16: struct names must be capitalized: use `struct Message`
    4| 

    5| struct message {

                      ^
    6|     txt string

    7| }
```

Resolving this, results in a succesful compilation.

```v
[bowero]% v run test.v
warning: test.v:3:6: the following imports were never used: 
 * http
hello
```

Therefore, this issue is no longer relevant in its current state.
