### ISSUE TITLE
Lambda not working with generics

### ISSUE THREAD

**Issue by prashanth-hegde** [vlang/v#19426]
### Describe the bug

Lambdas are supposed to work for all call sites taking in a function as a param. However, it's not working when there are generics

### Reproduction Steps

```v
import arrays
a := [1, 2, 3, 4]
//b:= arrays.join_to_string(a, '-', fn (it int) string {return it.str()}) // works
b := arrays.join_to_string(a, '-', |x| x.str()) // fails
println(b)
```

### Expected Behavior

Expected to print the following
```
1-2-3-4
```

### Current Behavior

compilation error 

```
error: generic function declaration must specify generic type names
```

### V version

0.4.1 1c9ab77

### Environment details (OS name and version, etc.)

MacOS Ventura 13.4.1
> [!IMPORTANT]
> You can vote for this issue using the 👍 reaction. More votes increase the issue's priority
> for developers.
>
> Take into account that only the 👍 reaction counts as a vote.
> Only reactions to the issue itself will be counted as votes, not comments.

**Comment by heyimtcn** [comment]
on newer versions the error is different, it being
```v
code.v:4:35: error: cannot use `fn (T) string` as `fn (int) string` in argument 3 to `arrays.join_to_string`
    2 | a := [1, 2, 3, 4]
    3 | //b:= arrays.join_to_string(a, '-', fn (it int) string {return it.str()}) // works
    4 | b := arrays.join_to_string(a, '-', |x|  x.str()) // fails
      |                                   ~~~~~~~~~~~~
    5 | println(b)
```
