### ISSUE TITLE
ARM Raspberry pi - "Illegal instruction"

### ISSUE THREAD

**Issue by SewerynKaminski** [vlang/v#19457]
### Describe the bug

`$ cat test.v`
fn main() {
  println ( 'hello wolrd!' )
}

`$ v test.v`
`$ test`
Illegal instruction
`$ file test`
test: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=bf8649fddea99dfa24b3181c9e481ef975b27354, not stripped

### Reproduction Steps

`$ v test.v`
`$ test`

### Expected Behavior

Generate valid binary

### Current Behavior

After executing generated binary got error message "Illegal instruction"

### Possible Solution

`$ v -prod test.v`
`$ test`
hello wolrd!

### V version

V 0.4.1 981f76c

### Environment details (OS name and version, etc.)

$ v doctor 
Illegal instruction
$ uname -a
Linux raspberrypi 5.10.103+ #1529 Tue Mar 8 12:19:18 GMT 2022 armv6l GNU/Linux
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/8/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 8.3.0-6+rpi1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)
> [!NOTE]
> You can vote for this issue using the 👍 reaction. More votes increase the issue's priority for developers.
>
> Take into account that only the 👍 reaction counts as a vote.
> Only reactions to the issue itself will be counted as votes, not comments.

**Comment by JalonSolov** [comment]
Can you get a newer version of gcc?  That one is... quite old.

**Comment by SewerynKaminski** [comment]
```
$ v -showcc test.v
```
```
> C compiler cmd: '/home/pi/vlang/v/thirdparty/tcc/tcc.exe' '@/tmp/v_1001/test.10519296450509670088.tmp.c.rsp'
> C compiler response file "/tmp/v_1001/test.10519296450509670088.tmp.c.rsp":
  -fwrapv -o "/home/seweryn/vlang/test" -D GC_BUILTIN_ATOMIC=1 -D GC_THREADS=1 -I "/home/pi/vlang/v/thirdparty/libgc/include" "/tmp/v_1001/test.10519296450509670088.tmp.c" -std=gnu99 -D_DEFAULT_SOURCE -bt25 "/home/pi/vlang/v/thirdparty/tcc/lib/libgc.a" -ldl -lpthread  
> C compiler cmd: 'cc' '@/tmp/v_1001/test.10519296450509670088.tmp.c.rsp'
> C compiler response file "/tmp/v_1001/test.10519296450509670088.tmp.c.rsp":
 -o "/home/seweryn/vlang/test" -D GC_BUILTIN_ATOMIC=1 -D GC_THREADS=1 -I `"/home/pi/vlang/v/thirdparty/libgc/include" "/tmp/v_1001/test.10519296450509670088.tmp.c" -std=gnu99 -D_DEFAULT_SOURCE "/home/pi/vlang/v/thirdparty/tcc/lib/libgc.a" -ldl -lpthread
```

```
$ ./test
```

```
Illegal instruction
```

**Comment by JalonSolov** [comment]
Yes, but there are other features V uses that weren't added until gcc-9.3, I believe.

Latest version is, of course, 13.2.

**Comment by JalonSolov** [comment]
In both cases, you're using gcc.  The only difference is when the code is optimized, it works.

**Comment by SewerynKaminski** [comment]
But why? Adding -cflags -O3  without prod flag don't work.

**Comment by JalonSolov** [comment]
V adds more than `-O3`.  Add the `-showcc` option on the V command, and it will print the full command it sends to the C compiler.

**Comment by SewerynKaminski** [comment]
It's tcc issue

**Comment by SewerynKaminski** [comment]
Give up

**Comment by SewerynKaminski** [comment]
It's tcc issue.
Give up.

**Comment by JalonSolov** [comment]
If you wish, go ahead, even though you showed it failing with gcc above.
