### ISSUE TITLE
"v install glfw"

### ISSUE THREAD

**Issue by Larpon** [vlang/v#1952]
**V version:** 
0.1.19 8fe46d5
**OS:** 
Kubuntu Linux 18.04

**What did you do?**
`v install glfw`

**What did you expect to see?**
Some kind of success message
 
**What did you see instead?**
```
V error: Creating /home/larpon/.vmodules/ ...
Skipping module "glfw", since it is missing name or url information.`
```

**Comment by Larpon** [comment]
Also note that I have libssl-dev installed as suggested in #1788

**Comment by Larpon** [comment]
I "fixed" this by installing: `sudo apt install libglfw3 libglfw3-dev libfreetype6-dev libssl-dev`
But the README.md gives the impression that you can install it via `v install glfw`.

Leaving issue open as `v install glfw` still gives an error.

**Comment by spytheman** [comment]
This is fixed in https://github.com/vlang/v/commit/079dcd1fffcb9ebe90da6b0669ab702ecfa12080 by cleaning up the README description.
