### ISSUE TITLE
C error from optional reference default value set to `unsafe { nil }`

### ISSUE THREAD

**Issue by islonely** [vlang/v#19538]
### Describe the bug

C error is generated from `field ?&Struct = unsafe { nil }`. Can't imagine why anyone would ever want that. Discovered it on accident when switching some `&Struct` types to `?&Struct`.

### Reproduction Steps

```v
struct View {
	parent ?&View = unsafe { nil }
}

fn main() {
	_ := &View{}
}
```

### Expected Behavior

Expected code to compile

### Current Behavior

```
C:/Users/imado/AppData/Local/Temp/v_0/test.tmp.c:495: warning: WINVER redefined
C:/Users/imado/AppData/Local/Temp/v_0/test.tmp.c:6755: warning: implicit declaration of function 'tcc_backtrace'
C:/Users/imado/AppData/Local/Temp/v_0/test.tmp.c:12677: error: lvalue expected
builder error: 
==================
C error. This should never happen.
```

### V version

V 0.4.2 37e5616

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.2 37e5616
OS: windows, Microsoft Windows 11 Pro v22621 64-bit
Processor: 16 cpus, 64bit, little endian, 

getwd: C:\Users\imado\Documents\GitHub\lena
vexe: C:\Users\imado\v\v.exe
vexe mtime: 2023-10-09 22:29:31

vroot: OK, value: C:\Users\imado\v
VMODULES: OK, value: C:\Users\imado\.vmodules
VTMP: OK, value: C:\Users\imado\AppData\Local\Temp\v_0

Git version: git version 2.33.1.windows.1
Git vroot status: weekly.2023.40.1-50-g37e5616b
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc status: thirdparty-windows-amd64 e90c2620
```
> [!NOTE]
> You can vote for this issue using the 👍 reaction. More votes increase the issue's priority for developers.
>
> Take into account that only the 👍 reaction counts as a vote.
> Only reactions to the issue itself will be counted as votes, not comments.

**Comment by felipensp** [comment]
Should we still allowing assigning `unsafe { nil }` to an option @spytheman ?

**Comment by medvednikov** [comment]
@felipensp I think we shouldn't

**Comment by felipensp** [comment]
> @felipensp I think we shouldn't

Thanks @medvednikov
