### ISSUE TITLE
tranlate c and compilation failed

### ISSUE THREAD

**Issue by zuosixiaoxiongmao** [vlang/v#19557]
### Describe the bug
tranlate c and compilation failed
```

import eventbus {EventBus, EventHandlerFn}

fn on_test_with_receiver(receiver &FakeReceiver, ev &EventData, sender voidptr) {
	println('11111111111')
}

struct FakeReceiver {}



fn send<T>(eb &EventBus<u64>, name u64, data voidptr) {
	eb.publish(name, eb, data)
}

struct NetCom {}

struct EventData {
	
}

mut eb := eventbus.new[u64]()
r := &FakeReceiver{}
eb.subscriber.subscribe_method(1, on_test_with_receiver, r)
eb.publish(1, eb, &EventData{})
send<NetCom>( eb, 1, &EventData{})
```
### Current Behavior

C:/Users/Administrator/AppData/Local/Temp/v_0/event_bus_error.13090158403344912773.tmp.c:507: warning: WINVER redefined
C:/Users/Administrator/AppData/Local/Temp/v_0/event_bus_error.13090158403344912773.tmp.c:1988: error: ',' expected (got "*")
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

### V version

V 0.4.2

### Environment details (OS name and version, etc.)

windows 10
> [!NOTE]
> You can vote for this issue using the 👍 reaction. More votes increase the issue's priority for developers.
>
> Take into account that only the 👍 reaction counts as a vote.
> Only reactions to the issue itself will be counted as votes, not comments.

**Comment by MCausc78** [comment]
Does not reproduces on latest V:
```
PS D:\Games\Proekti\V\interactions> type test2.v    
import eventbus { EventBus }

fn on_test_with_receiver(receiver &FakeReceiver, ev &EventData, sender voidptr) {
        println('11111111111')
}

struct FakeReceiver {}

fn send[T](eb &EventBus[u64], name u64, data voidptr) {
        eb.publish(name, eb, data)
}

struct NetCom {}

struct EventData {
}

mut eb := eventbus.new[u64]()
r := &FakeReceiver{}
eb.subscriber.subscribe_method(1, on_test_with_receiver, r)
eb.publish(1, eb, &EventData{})
send[NetCom](eb, 1, &EventData{})
PS D:\Games\Proekti\V\interactions> v version
V 0.4.4 2a68e2b
PS D:\Games\Proekti\V\interactions> v run test2.v
11111111111
11111111111
```
