### ISSUE TITLE
Build v failed on window10

### ISSUE THREAD

**Issue by luoheng23** [vlang/v#1959]
**V version:** 
0.1.19
**OS:** 
win10
**What did you do?**
git clone https://github.com/vlang/v
cd v
make

**What did you expect to see?**
compile is ok.
 
**What did you see instead?**
Building V
git version 2.18.0.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
cc1.exe: error: unrecognized command line option '-std=gnu11'
gcc failed to compile - Create an issue at 'https://github.com/vlang'

**Comment by Delta456** [comment]
Do you have gcc?

**Comment by luoheng23** [comment]
> Do you have a recent version of gcc?

It seems my gcc version is old. It compiles ok after I update gcc. Thank you.

**Comment by dumblob** [comment]
>It seems my gcc version is old...

Compiler version should be definitely checked by the *V* compiler (by using macros).
