### ISSUE TITLE
Can't use `const` value for fixed array that is a struct's field if `const` was declared below struct declaration

### ISSUE THREAD

**Issue by ArtemkaKun** [vlang/v#19593]
### Describe the bug

If you have a struct with a field of type of fixed array, you must provide the size of the array. If you want to use the `const` value for this, and this `const` is declared below the declaration of this struct, the compiler will output an error.

### Reproduction Steps

```
struct Test {
	posts [max_posts_count]int
}

const max_posts_count = 5
```

### Expected Behavior

Compiled successfully

### Current Behavior

```
code.v:2:9: error: non-constant array bound `max_posts_count`
    1 | struct Test {
    2 |     posts [max_posts_count]int
      |            ~~~~~~~~~~~~~~~
    3 | }
    4 |
```

### Possible Solution

```
const max_posts_count = 5

struct Test {
	posts [max_posts_count]int
}
```

### V version

`V 0.4.2 fae46a8 `

### Environment details (OS name and version, etc.)

Playground
> [!NOTE]
> You can vote for this issue using the 👍 reaction. More votes increase the issue's priority for developers.
>
> Take into account that only the 👍 reaction counts as a vote.
> Only reactions to the issue itself will be counted as votes, not comments.

**Comment by Delta456** [comment]
I feel this is some parse issue.

**Comment by yuyi98** [comment]
It is recommended that const must be defined before use so that the complexity of processing is avoided.

**Comment by medvednikov** [comment]
In V the order shouldn't matter. It's a bug in the const evaluation phase.

**Comment by ttytm** [comment]
Agree @medvednikov. Constants also span files. This makes it impossible to tell if they are defined before use in another file.

Working on this might also be a step towards fixing https://github.com/vlang/v/issues/19149
