### ISSUE TITLE
bug of println

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#196]
Put follow code into this page https://vlang.io/play
```
fn main() {
	println('aa1\x00 00')
}
```
Then I got:
```
aa1
```
Where is '00'?

**Comment by medvednikov** [comment]
Yes the goal is not to rely on printf. V strings are not null terminated.

Float formatting needs to be implemented first.

**Comment by medvednikov** [comment]
Fixed:

`0 character in a string literal`
