### ISSUE TITLE
consts and enums from Nested modules are not seen on FreeBSD

### ISSUE THREAD

**Issue by bakul** [vlang/v#19605]
### Describe the bug

When a module is two levels deep, its pub const and pub enum values are not seen when this module is included. 

### Reproduction Steps

```
mkdir -p foo/bar
cat > foo/bar/bar.v <<EOF
module bar

pub const xyz = 12
EOF
cat > main.v <<EOF
import foo.bar
fn main() {
  println(bar.xyz)
}
EOF
v run main.v

### Expected Behavior

It should print 12

### Current Behavior

On FreeBSD the compilation fails with
```
error: undefined ident: `foo.bar.xyz`
```

It works fine on Ubuntu

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### V version

V 0.4.2 b3d1b04

### Environment details (OS name and version, etc.)

FreeBSD-14.0-STABLE

**Comment by spytheman** [comment]
run `touch v.mod`:
![image](https://github.com/vlang/v/assets/26967/74bec9fa-b6aa-4600-9241-9dc7a480f2c5)

**Comment by spytheman** [comment]
The behavior is consistent with that on Linux:
![image](https://github.com/vlang/v/assets/26967/97d510dd-af8d-4b85-8ef0-3097a9714fb1)

i.e. if you have `v.mod` at the top of your project, module lookup works.
If you do not, module lookup fails.

**Comment by bakul** [comment]
I have a v.mod in the same directory! I removed it and did `touch v.mod` but no such luck. If it matters, v uses clang.

**Comment by bakul** [comment]
The problem turned out to be an old v.mod in the parent directory. [Just documenting this in case someone else runs into it] 

The root cause is module lookup.
