### ISSUE TITLE
Windows 10 Build failed

### ISSUE THREAD

**Issue by Redcxx** [vlang/v#1960]
**V version:** 
**OS:** Windows 10

**What did you do?**
````
git clone https://github.com/vlang/v
cd v
./make
v
````

**What did you expect to see?**
````
V 0.1.x
Use Ctrl-D to exit
````
 
**What did you see instead?**
./make:
````
Building V
git version 2.20.1.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Building v.v...
````
v:
````
v : 无法将“v”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ v
+ ~
    + CategoryInfo          : ObjectNotFound: (v:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
````

Note: I see a 0 byte `v.exe.tmp.c` file in the directory

**Comment by MaD70** [comment]
Same here: I execute `make.bat` in `cmd.exe` (I think the OP is using Windows PowerShell instead).
It ends with no errors but no `v.exe` also and a 0 byte `v.exe.tmp.c` file.

**Comment by joe-conigliaro** [comment]
Can you try again now?. there was an problem at the time this issue was made with the bootstrap C file.

**Comment by Redcxx** [comment]
Yes it is working now

**Comment by joe-conigliaro** [comment]
Excellent!
