### ISSUE TITLE
Generics Struct: lacks body

### ISSUE THREAD

**Issue by Gigaboy-01** [vlang/v#1965]
**V version:** 0.1.19
**OS:** Linux Mint 19

**What did you do?**
Tried to create `struct` with generics inside.

**What did you expect to see?**
Values types inside `struct` defined with generics.
 
**What did you see instead?**
A segfault

![code](https://user-images.githubusercontent.com/31167933/64887574-8f264380-d62e-11e9-8c98-df172745b0f9.png)
![err](https://user-images.githubusercontent.com/31167933/64887575-8f264380-d62e-11e9-850e-60ee97669b19.png)

**Comment by Delta456** [comment]
This works now

```v
struct Node<T> {
mut:
    val T
}

fn main() {
}
```

Output:
(blank)
