### ISSUE TITLE
struct in array and in operator

### ISSUE THREAD

**Issue by SewerynKaminski** [vlang/v#1966]
**V version:** 0.1.19
**OS:** Ubuntu 18.04 64bit

**What did you do?**
```
struct Test {
   a int
   b bool
}

fn (a Test) equal( l Test ) bool {
        return a.a==l.a && a.b==l.b
}

fn (a []Test) contains( r Test ) bool {
        for v in a {
                if v.equal(r) { return true }
        }
        return false
}

fn main () {
        mut t := []Test

        t << Test{a:0, b:true}
        t << Test{a:2, b:false}
        t << Test{a:3, b:false}

        println( Test{a:3, b:false} in t )      // Compile error
        println( (Test{a:3, b:false}) in t )    // Compile fine
}
```
**What did you expect to see?**
No compilation errors
 
**What did you see instead?**
structinarray.tmp.c:3534:68: error: too many arguments provided to function-like macro invocation
 /*opt*/printf ("%d\n", _IN(Test,  (Test) { .a =  3 , .b =  0 } ,  t ) ) ;
                                                                   ^
structinarray.tmp.c:111:9: note: macro '_IN' defined here
#define _IN(typ, val, arr) array_##typ##_contains(arr, val)
        ^
structinarray.tmp.c:3534:25: note: parentheses are required around macro argument containing braced initializer list
 /*opt*/printf ("%d\n", _IN(Test,  (Test) { .a =  3 , .b =  0 } ,  t ) ) ;
                        ^
                                   (                           )
1 error generated.
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by joe-conigliaro** [comment]
`/opt/printf (` whoa that's really weird 🤔

**Comment by Delta456** [comment]
Can you try doing operator overloading for `==`
