### ISSUE TITLE
GC

### ISSUE THREAD

**Issue by zaoqi** [vlang/v#197]
`The right approach to solve this will be figured out in the near future.`

The only right approach to solve this is to add a GC.（But don't need to use it in most cases）

**Comment by medvednikov** [comment]
There will be no GC.

**Comment by zaoqi** [comment]
But even Rust has a gc library.

**Comment by zaoqi** [comment]
It is used to implement interpreters.

**Comment by zaoqi** [comment]
@medvednikov So in the future, in some cases, manual memory management is still required (like Swift and Rust)?
