### ISSUE TITLE
Versioning system for vpm

### ISSUE THREAD

**Issue by ttytm** [vlang/v#19709]
### Describe the feature

Allow specifying a tag during module installation and dependency declarations, via a `@<tag>` suffix.

E.g., installations:
```sh
v install vsl@0.1.50.
# or
v install https://github.com/vlang/vsl@v0.1.50
```
Example of a third-party dependency in a `v.mod` file.
```v
Module {
	// ...
	dependencies: ['ttytm.webview@v0.6.0']
	// or
	dependencies: ['https://github.com/ttytm/webview@v0.6.0']
}
```

### Use Case

Use a dependency version without compatibility issues with latest changes to the dependency.

### Proposed Solution

- The first step would be to install a specified version to the regular module path.
- Following steps should extend this feature to support multiple installed versions, e.g., like go pkg does. This would extend the work from just the vpm module to the module lookup functionality.

### Other Information

It's good to make `v install` more robust at first. Also, cleaning it up will increase its maintainability. The recent changes to the vpm module are made in the context of allowing for such features. So work on this has already started :+1: 

It might be possible without breaking changes. They are not planned at least, but can occur at some step further down the road when extending the package manager like this.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### Version used

v0.4.2

### Environment details (OS name and version, etc.)

\-
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Larpon** [comment]
`vlang/sdl` would benefit from something like this also
