### ISSUE TITLE
typo error in https://github.com/vlang/v/blob/master/changelogs0.x/0.4.md?plain=1

### ISSUE THREAD

**Issue by chinmay7016** [vlang/v#19714]
### Describe the bug

"Generic typeof[T](), sizeof[T](), isreftype[T]() functions." - Change isreftype to isrefType.

### Reproduction Steps

go to https://github.com/vlang/v/blob/master/changelogs0.x/0.4.md?plain=1

### Expected Behavior

 Change isreftype to isrefType.

### Current Behavior

it isreftype instead of isrefType.

### V version

nil

### Environment details (OS name and version, etc.)

macos
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by ArtemkaKun** [comment]
The issues seems to be invalid due to conversation in related PR
