### ISSUE TITLE
Update 0.4.md

### ISSUE THREAD

**Issue by manavb2214** [vlang/v#19712]
### Describe the issue

Found a Typo Error.

"Builtin type names can no longer be used as identifiers."

The word "Builtin" should be "Built-in."

### Links

https://github.com/vlang/v/blob/master/changelogs0.x/0.4.md?plain=1
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by ArtemkaKun** [comment]
The issue should be closed as a result of related PR concersation
