### ISSUE TITLE
about std=11

### ISSUE THREAD

**Issue by qkll** [vlang/v#1972]
**V version:** 
linux 3.9.9

**What did you do?**
println ('hello world')

**What did you expect to see?**

cc1 error, unrecognized std=11
**What did you see instead?**

**Comment by changrui** [comment]
`-std=gnu11` is a gcc option, NOT `std=11`.

**Comment by lithic** [comment]
`std=c11`

**Comment by qkll** [comment]
v make is  successed. when command println  ('hello world'),echo "cc error,not recognize std=gnu11"

**Comment by Delta456** [comment]
@qkll Is this on the REPL or by simply compiling?

**Comment by qkll** [comment]
在./v后，测试println时出现的。

**Comment by ntrel** [comment]
`-std=c11`
