### ISSUE TITLE
Add get_page_size to os module

### ISSUE THREAD

**Issue by hk-none** [vlang/v#19744]
### Describe the feature

Is there any way to add a function to `os` module to return the systems memory page size?

### Use Case

Useful for low level programming

### Proposed Solution

```v
 usize(unsafe { C.syscall(C._SC_PAGESIZE) })
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.4.2 5b1b2cc

### Environment details (OS name and version, etc.)

V full version: V 0.4.2 5b1b2cc
OS: macos, macOS, 14.1, 23B73
Processor: 8 cpus, 64bit, little endian, Apple M1 Pro

Git version: git version 2.39.2
Git vroot status: 4.1.18-37-ga4b4b909 (53627 commit(s) behind V master)
.git/config present: false

CC version: Apple clang version 15.0.0 (clang-1500.0.40.1)
thirdparty/tcc: N/A
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
From a stackoverflow question about this:
```
It is entirely platform dependent which address-ranges are mapped to which page-sizes. Further the pagesize is not system-wide. You can allocate memory from different page-size regions according to the use case. And you can even have platforms without any virtual memory managment.

So, code handling this topic must be platform specific.
```
Especially when you add Windows into the mix.

**Comment by hk-none** [comment]
Yeah, I figured from looking at go's implementation. Is this something we will add to `os`?
