### ISSUE TITLE
cgen error: field expected caused by recursive struct

### ISSUE THREAD

**Issue by Coachonko** [vlang/v#19812]
### Describe the bug

Using a recursive struct caused cgen error

### Reproduction Steps

The problem is found in [this repository](https://github.com/Coachonko/peony)
The problem is caused by line `12` in [this file](https://github.com/Coachonko/peony/blob/eef8fcc5d390db7115e51ffff488c20b7fc6591d/src/models/post_tag.v#L12)

I tried to isolate it, but can't isolate it successfully.

### Expected Behavior

No cgen error

### Current Behavior

cgen error

### V version

`Current V version: V 0.4.2 97f7c3f, timestamp: 2023-11-08 20:43:48 +0200`

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.2 95509cf.97f7c3f
OS: linux, Linux version 5.14.0-284.30.1.el9_2.x86_64 (mockbuild@mj.euro.kojibuilder106) (gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4), GNU ld version 2.35.2-37.el9) #1 SMP PREEMPT_DYNAMIC Fri Sep 15 08:06:33 UTC 2023
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

getwd: /home/coachonko/Documents/projects/vlang/peony
vexe: /home/coachonko/.local/lib64/v/v
vexe mtime: 2023-11-08 21:10:24

vroot: OK, value: /home/coachonko/.local/lib64/v
VMODULES: OK, value: /home/coachonko/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.39.3
Git vroot status: weekly.2023.44-85-g97f7c3f6
.git/config present: true

CC version: cc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by ArtemkaKun** [comment]
Can you provide error message?

**Comment by Coachonko** [comment]
![image](https://github.com/vlang/v/assets/102909397/313c13a0-44a6-4ffa-9ce3-49a1ed86cf1f)

**Comment by Coachonko** [comment]
Ok figured it out, took me hours that I really could have used to work on my program, but here it is: it's related to `json.encode`

```
import json

struct PostTag {
	id string
	parent     ?&PostTag
	visibility string
	created_at string [json: 'createdAt']
	updated_at string [json: 'updatedAt']
	deleted_at string [json: 'deletedAt']
	title      string
	subtitle   string
	content    string
	handle     string
	excerpt    string
	metadata   string [raw]
}

fn main() {
	new_post_tag := PostTag{}
	println(json.encode(new_post_tag))
}
```

**Comment by medvednikov** [comment]
Fixed, thanks for the detailed report.
