### ISSUE TITLE
arch linux v install error

### ISSUE THREAD

**Issue by Radeonares32** [vlang/v#19850]
### Describe the bug

 I get this error while compiling v in Linux

### Reproduction Steps

/home/radeonares/.vmodules/markdown/html_experimental.v:94:55: error: cannot use `u32` as `int` in argument 1 to `char.vstring_with_len`
   92 |         off := unsafe { attr.substr_offsets[i] }
   93 |         size := unsafe { attr.substr_offsets[i + 1] - off }
   94 |         text := unsafe { (attr.text + off).vstring_with_len(size) }
      |                                                             ~~~~
   95 | 
   96 |         match typ {
   

### Expected Behavior

to be loaded properly

### Current Behavior

Using local vc
Using local tcc
cc  -std=gnu99 -w -o v1.exe ./vc/v.c -lm -lpthread 
./v1.exe -no-parallel -o v2.exe -prod cmd/v
./v2.exe -nocache -o ./v -prod cmd/v
rm -rf v1.exe v2.exe
Your `tcc` is working. Good - it is much faster at compiling C source code.
V has been successfully built
V 0.4.2 5b1b2cc
---- Building cmd/tools ... ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 SKIP  [ 1/66]     0.000 ms cmd/tools/builders/wasm_builder.v
 OK    [ 2/66]   168.165 ms cmd/tools/detect_tcc.v
 OK    [ 3/66]   243.454 ms cmd/tools/fast/fast.v
 OK    [ 4/66]   255.914 ms cmd/tools/changelog_helper.v
 OK    [ 5/66]   275.759 ms cmd/tools/bench/wyhash.v
 OK    [ 6/66]   344.721 ms cmd/tools/fast/fast_job.v
 OK    [ 7/66]   377.218 ms cmd/tools/fuzz/map_fuzz.v
 OK    [ 8/66]   330.898 ms cmd/tools/gen1m.v
 OK    [ 9/66]   513.248 ms cmd/tools/oldv.v
 OK    [10/66]   629.394 ms cmd/tools/performance_compare.v
 OK    [11/66]  1273.645 ms cmd/tools/gen_vc.v
 OK    [12/66]  1258.943 ms cmd/tools/measure/parser_speed.v
 OK    [13/66]  1301.858 ms cmd/tools/measure/scanner_speed.v
 OK    [14/66]   671.633 ms cmd/tools/regress.v
 OK    [15/66]  1820.385 ms cmd/tools/builders/interpret_builder.v
 OK    [16/66]   621.272 ms cmd/tools/repeat.v
 OK    [17/66]  1835.399 ms cmd/tools/builders/golang_builder.v
 OK    [18/66]   324.769 ms cmd/tools/report_v_module_folders_without_tests.v
 OK    [19/66]  1960.765 ms cmd/tools/builders/js_builder.v
 OK    [20/66]   512.037 ms cmd/tools/show_ancient_deprecations.v
 OK    [21/66]   506.729 ms cmd/tools/test_os_process.v
 OK    [22/66]   446.633 ms cmd/tools/vbin2v.v
 OK    [23/66]  2305.266 ms cmd/tools/builders/native_builder.v
 OK    [24/66]   671.745 ms cmd/tools/test_if_v_test_system_works.v
 OK    [25/66]   564.495 ms cmd/tools/vbug.v
 OK    [26/66]   642.231 ms cmd/tools/translate.v
 OK    [27/66]  2595.677 ms cmd/tools/check_os_api_parity.v
 OK    [28/66]  2663.457 ms cmd/tools/builders/c_builder.v
 OK    [29/66]   679.207 ms cmd/tools/vbuild-tools.v
 OK    [30/66]   788.582 ms cmd/tools/vbuild-examples.v
 OK    [31/66]   511.983 ms cmd/tools/vbump.v
 OK    [32/66]   406.572 ms cmd/tools/vcomplete.v
 OK    [33/66]   693.150 ms cmd/tools/vbuild-vbinaries.v
 OK    [34/66]   637.063 ms cmd/tools/vcheck-md.v
 OK    [35/66]   452.387 ms cmd/tools/vcompress.v
 OK    [36/66]   427.448 ms cmd/tools/vcreate
 OK    [37/66]   485.874 ms cmd/tools/vdoctor.v
 OK    [38/66]  1424.288 ms cmd/tools/vast
 OK    [39/66]   449.120 ms cmd/tools/vmissdoc.v
 OK    [40/66]   412.649 ms cmd/tools/vself.v
 OK    [41/66]   622.006 ms cmd/tools/vrepl.v
 OK    [42/66]   402.650 ms cmd/tools/vsetup-freetype.v
 FAIL  [43/66]  1086.697 ms cmd/tools/vdoc
/home/radeonares/.vmodules/markdown/html_experimental.v:94:55: error: cannot use `u32` as `int` in argument 1 to `char.vstring_with_len`
   92 |         off := unsafe { attr.substr_offsets[i] }
   93 |         size := unsafe { attr.substr_offsets[i + 1] - off }
   94 |         text := unsafe { (attr.text + off).vstring_with_len(size) }
      |                                                             ~~~~
   95 | 
   96 |         match typ {

 OK    [44/66]  1517.933 ms cmd/tools/vbump_test.v
 OK    [45/66]   914.650 ms cmd/tools/vls.v
 OK    [46/66]  1162.004 ms cmd/tools/vgret.v
 OK    [47/66]  1235.476 ms cmd/tools/vfmt.v
 OK    [48/66]   888.315 ms cmd/tools/vscan.v
 OK    [49/66]  1082.640 ms cmd/tools/vpm.v
 OK    [50/66]   367.046 ms cmd/tools/vsymlink.v
 OK    [51/66]   390.713 ms cmd/tools/vtest-all.v
 OK    [52/66]   483.757 ms cmd/tools/vshould-compile-all.v
 OK    [53/66]   648.229 ms cmd/tools/vtest-cleancode.v
 OK    [54/66]   382.911 ms cmd/tools/vtracev.v
 OK    [55/66]   905.179 ms cmd/tools/vshader.v
 OK    [56/66]   384.416 ms cmd/tools/vup.v
 OK    [57/66]   549.987 ms cmd/tools/vtest.v
 OK    [58/66]   972.880 ms cmd/tools/vshare.v
 OK    [59/66]   702.332 ms cmd/tools/vtest-fmt.v
 OK    [60/66]   597.142 ms cmd/tools/vtest-self.v
 OK    [61/66]   335.395 ms cmd/tools/vwipe-cache.v
 OK    [62/66]   384.051 ms cmd/tools/vwhere
 OK    [63/66]   498.408 ms cmd/tools/vwatch.v
 OK    [64/66]  1041.701 ms cmd/tools/vtest-parser.v
 OK    [65/66]  2622.357 ms cmd/tools/vcomplete_test.v
 OK    [66/66]   967.014 ms cmd/tools/vvet
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Failed command 1:    '/home/radeonares/.cache/yay/vlang/src/v-5b1b2cc7c016290100a0169124200a8fc4a81551/v'   -o '/tmp/v_1000/tsession_7f114aef5740_94592521820153/vdoc' '/home/radeonares/.cache/yay/vlang/src/v-5b1b2cc7c016290100a0169124200a8fc4a81551/cmd/tools/vdoc'
Summary for building cmd/tools: 1 failed, 64 passed, 1 skipped, 66 total. Runtime: 5260 ms, on 11 parallel jobs.

### V version

 0.4.3

### Environment details (OS name and version, etc.)

Arch linux
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by ArtemkaKun** [comment]
Hi. Are you installing V for the first type, or doing `make`, or doing `v up` or what?

**Comment by Radeonares32** [comment]
> Hi. Are you installing V for the first type, or doing `make`, or doing `v up` or what?

I compiled the source code and got this error by doing make. I downloaded it from the arch linux repo and ran makepkg. I still get the same error. I can't v up because the v compiler is not installed.

**Comment by ArtemkaKun** [comment]
You should download source code only from GitHub repo (from here), AUR/other package managers are not official supported for now

**Comment by Radeonares32** [comment]
thank you, i solved it now :)

**Comment by Delta456** [comment]
> You should download source code only from GitHub repo (from here), AUR/other package managers are not official supported for now

We need people to maintain AUR and other package managers. I have thought taking care of nixpkg.

**Comment by Radeonares32** [comment]
I started preparing aur packages for v.

**Comment by ArtemkaKun** [comment]
Share it on Discord server when I will done
