### ISSUE TITLE
V should create tmpfiles in /tmp or current directory

### ISSUE THREAD

**Issue by Chiiruno** [vlang/v#1986]
**V version:**  0.1.19

**OS:**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.14, NixOS, 19.03.173495.7339bd47600 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173495.7339bd47600, nixos-unstable-19.09pre192418.e19054ab3cd"`
 - channels(okina): `"nixos-19.03.173489.af5481e9b77, nixos-unstable-19.09pre192418.e19054ab3cd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**What did you do?**
Attempt to build a V program from examples.
(hello_world.v works fine, since it doesn't need to create a tmpfile it seems)

**What did you expect to see?**
It working.
 
**What did you see instead?**
```
/nix/store/gdm4d6qqq09kcq13ddzx81p3gzk938i5-vlang-0.1.19/bin/v -prod -o lol /nix/store/gdm4d6qqq09kcq13ddzx81p3gzk938i5-vlang-0.1.19/share/examples/tetris/tetris.v
/nix/store/gdm4d6qqq09kcq13ddzx81p3gzk938i5-vlang-0.1.19/lib/thirdparty/glad/glad.o not found, building it...
Assembler messages:
Fatal error: can't create /nix/store/gdm4d6qqq09kcq13ddzx81p3gzk938i5-vlang-0.1.19/lib/thirdparty/glad/glad.o: Read-only file system
gcc: error: /nix/store/gdm4d6qqq09kcq13ddzx81p3gzk938i5-vlang-0.1.19/lib/thirdparty/glad/glad.o: No such file or directory
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```
Same thing happens without `-prod`, of course.

**Comment by spytheman** [comment]
The generated object .o and .obj files in the thirdparty/ folder should be in a known location.

**Comment by Chiiruno** [comment]
```
/nix/store/vycla5rxb8kmbdp7xfhgzr34qh14ha6d-vlang-0.1.21/bin/v run /nix/store/vycla5rxb8kmbdp7xfhgzr34qh14ha6d-vlang-0.1.21/share/examples/hello_world.v
failed to create /nix/store/vycla5rxb8kmbdp7xfhgzr34qh14ha6d-vlang-0.1.21/share/examples/hello_world.tmp.c
zsh: segmentation fault (core dumped)  /nix/store/vycla5rxb8kmbdp7xfhgzr34qh14ha6d-vlang-0.1.21/bin/v run
```

**Comment by Chiiruno** [comment]
`thirdparty` and `thirdparty-release` should probably be re-added to the makefile.

**Comment by Larpon** [comment]
I think this might be fixed with lastest V.
@Chiiruno can you do a `v up` and try again?

**Comment by ka-weihe** [comment]
Closing due to no response. Please reopen the issue if it persists.
