### ISSUE TITLE
<< corrupts original immutable array when mutable copy in modified

### ISSUE THREAD

**Issue by avitkauskas** [vlang/v#1990]
**V version:** V 0.1.19 897db23
**OS:** Mac OS
**What did you do?**
```v
a := [1, 1]
b := [2, 2]
mut c := a
c << b
println(a)
println(b)
println(c)
```
**What did you expect to see?**
```
[1, 1]
[2, 2]
[1, 1, 2, 2]
```
**What did you see instead?**
```
[91, 32]
[2, 2]
[1, 1, 2, 2]
```
**Comments**
It works fine if `a` is `[1]` and `b` is `[2]`. 
Same happens when using `.repeat(x)` when defining the arrays.
Also, it works fine when the length is 1, 5, 6, 7, 8, but does not work when it's 2, 3, 4, 9, 10...

**Comment by medvednikov** [comment]
Thanks @avitkauskas 

This will actually be fixed this week as part of my memory management work.

**Comment by nedpals** [comment]
Closed. The issue has been fixed now. See the [DevBits Link](https://devbits.app/play/9TnGejU2cszQ) for the output.
