### ISSUE TITLE
reflect: sumtype method to get child value.

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#19921]
### Describe the feature

Code request
```v
struct Foo {
	a string
}

type Baz = Foo | string

fn main() {
	x := Baz(Foo{"a"}) 
	assert x.value() == Foo{"a"}
}

```

Code example with generics

```v
struct Foo {
    a string
}

struct Bar {
    b string
}

type Baz = Bar | Foo | bool | int | string

fn encode[T](x T) {
    $if T is $sumtype {
        // x.type_idx()
        // x.type_name()
        if x.type_name() == 'Foo' {
            assert x.value() == Foo{"a"}
        }
        if x.type_name() == 'Bar' {
            assert x.value() == Bar{"b"}
        }
    }
}

fn main() {
    // a := &Foo{"a"}
    // println(a)

    // b := *a
    // println(b)

    x := Baz(Foo{"a"}) // as Foo
    y := Baz(Bar{"b"})
    z := Baz(42)

    encode(x)
    encode(y)
    encode(z)
}
```

When you pass a value to the sumtype, it is already set in the struct created for the sumtype.

```v
// Union sum type main__Baz = 
//          |   96 = main__Bar           
//          |   95 = main__Foo           
//          |   19 = bool                
//          |    8 = int                 
//          |   21 = string              
struct main__Baz {
    union {
        main__Bar* _main__Bar;
        main__Foo* _main__Foo;
        bool* _bool;
        int* _int;
        string* _string;
    };
    int _typ;
};

static inline main__Baz main__Foo_to_sumtype_main__Baz/*KEK*/(main__Foo* x) {
    main__Foo* ptr = memdup(x, sizeof(main__Foo));
    return (main__Baz){ ._main__Foo = ptr, ._typ = 95};
}
```

Then. In theory, when I used the `x.value()` method in V, I would only need to copy the information from the corresponding field in `main__Baz` checking which type is set in `main__Baz._typ` before.

### Use Case

encoding, decoding, reflect, data processing...

### Other Information

conversion_function_call `vlib/v/gen/c/fn.v:1274`
method_call `vlib/v/checker/fn.v:1658`
method check `vlib/v/checker/fn.v:170`
method check test `vlib/v/checker/tests/incorrect_name_sum_type.vv`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.4.3 192d6d2

### Environment details (OS name and version, etc.)

Ubuntu
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
You could to do:

```V
struct Foo {
	a string
}

type Baz = Foo | string

fn main() {
	x := Baz(Foo{"a"}) 
	match x.type_name() {
        'Foo' {
            println(x as Foo)
        }
        else {
            println('its a string')
        }
    }
}
```

**Comment by enghitalo** [comment]
I cannot cast because all this type will be generics in x.json2. I will never know which type I will need cast.

See the example below (). With the comments

```v
import v.reflection

struct FooStruct {
	a string
}

struct Bar {
	b string
}

type BazSumtype = Bar | FooStruct | bool | int | string

// Inside the encoder I will never know which types are above

fn encode[T](unknow_generic_type T) {
	$if T is $sumtype {
		if reflection.get_type_symbol(idx) or { return }.kind == .struct_ {
			e.encode_struct(unknow_generic_type.value())
		}
	}
}

fn encode_struct[T](unknow_generic_type T) {
	$if T is $struct {
		// process as a struct `FooStruct` that was started was a Sumtype `BazSumtype`
	}
}

fn main() {
	x := BazSumtype(FooStruct{'a'})
	assert x.value() == FooStruct{'a'}
}
```

**Comment by felipensp** [comment]
Already handled with PR #20270
