### ISSUE TITLE
Comptime `@[flag]` enum evaluation is wrong

### ISSUE THREAD

**Issue by lemoncmd** [vlang/v#19925]
### Describe the bug

when you declare const enum variable with `@[flag]`, the result of comptime evaluation is wrong.
the behavior changes if you omit the enum name.

### Reproduction Steps

```v
>>> @[flag]enum Foo{a b c}
>>> const aa = Foo.a
>>> aa
Foo{}
>>> const ab = Foo.a | Foo.b
>>> ab
Foo{.a}
>>> const ac = Foo.a | Foo.b | Foo.c
>>> ac
Foo{.a | .b}
>>> const ad = Foo.a | .b | .c
>>> ad
Foo{}
>>> const ae = Foo.a | .b | .c
>>> ae
Foo{}
>>> const af = Foo.a | .b | Foo.c
>>> af
Foo{.b}
>>>
```

### Expected Behavior

```v
>>> @[flag]enum Foo{a b c}
>>> const aa = Foo.a
>>> aa
Foo{.a}
>>> const ab = Foo.a | Foo.b
>>> ab
Foo{.a | .b}
>>> const ac = Foo.a | Foo.b | Foo.c
>>> ac
Foo{.a | .b | .c}
>>> const ad = Foo.a | .b | .c
>>> ad
Foo{.a | .b | .c}
>>> const ae = Foo.a | .b | .c
>>> ae
Foo{.a | .b | .c}
>>> const af = Foo.a | .b | Foo.c
>>> af
Foo{.a | .b | .c}
>>>
```

### Current Behavior

see above

### V version

V 0.4.3 8c8df9e

### Environment details (OS name and version, etc.)

OS: Arch linux
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by lemoncmd** [comment]
Anon enum evaluation is not fixed.
```v
>>> @[flag]enum Foo{a b c}
>>> const aa = Foo.a | Foo.b | Foo.c
>>> aa
Foo{.a | .b | .c}
>>> const ab = Foo.a | .b | .c
>>> ab
Foo{.a}
```

**Comment by felipensp** [comment]
> Anon enum evaluation is not fixed.
> 
> ```v
> >>> @[flag]enum Foo{a b c}
> >>> const aa = Foo.a | Foo.b | Foo.c
> >>> aa
> Foo{.a | .b | .c}
> >>> const ab = Foo.a | .b | .c
> >>> ab
> Foo{.a}
> ```

Thanks, I'll submit a PR fixing right now.

**Comment by spytheman** [comment]
@lemoncmd can you please check again with latest V?
