### ISSUE TITLE
asserts break compilation due to undeclared identifier 'g_test_ok'

### ISSUE THREAD

**Issue by lobotony** [vlang/v#1992]
**V version:** 0.1.19
**OS:** MacOS 10.14.6

**What did you do?**

	fn main() {
		v := 3
		assert v > 0
		println(v)
	}

**What did you expect to see?**
successful compilation
 
**What did you see instead?**
error: use of undeclared identifier 'g_test_ok'

**Comment by medvednikov** [comment]
Right now assert is only allowed in tests, might be a good idea to bring it back for all programs.

**Comment by medvednikov** [comment]
Fixed.
