### ISSUE TITLE
Release 0.1.19 builds but fails to compile trivial program due to implicit declaration of function 'array_repeat_old'

### ISSUE THREAD

**Issue by lobotony** [vlang/v#1993]
**V version:** 0.1.19
**OS:** MacOS 10.14.16

**What did you do?**

Downloaded 0.1.19.zip, make, ./main.v

in main.v

    fn main() {
        v := 3
	assert v > 0
	println(v)
    }

**What did you expect to see?**
successful compilation
 
**What did you see instead?**

	warning: Downloads/v-0.1.19/vlib/builtin/string.v:360: `[0 ; len]` syntax was removed. Use `[0].repeat(len)` instead
	warning: Downloads/v-0.1.19/vlib/builtin/string.v:877: `[0 ; len]` syntax was removed. Use `[0].repeat(len)` instead
	warning: Downloads/v-0.1.19/vlib/builtin/int.v:216: `[0 ; len]` syntax was removed. Use `[0].repeat(len)` instead
	warning: Downloads/v-0.1.19/vlib/builtin/map.v:172: `[0 ; len]` syntax was removed. Use `[0].repeat(len)` instead
	warning: Downloads/v-0.1.19/vlib/strings/similarity.v:6: `[0 ; len]` syntax was removed. Use `[0].repeat(len)` instead
	main.tmp.c:1270:19: error: implicit declaration of function 'array_repeat_old' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
	array_int prefix= array_repeat_old(& (int[]){  0 },  p .len ,...

**Comment by medvednikov** [comment]
V is on a rolled release right now, it should always be compiled from master until 0.2.

**Comment by N8python** [comment]
I tried running the same program, and got a different error:
`
/Users/natebreslow/v/vlib/strings/similarity.v:7:3: bad token `#` (embedding C code is no longer supported)
`

**Comment by medvednikov** [comment]
@N8python are you following instructions from the readme?

git clone ...
cd v
make

**Comment by N8python** [comment]
I ran `v up` to update to version 0.1.19. Do I need to reinstall V entirely?

**Comment by N8python** [comment]
Never mind, it's a problem with my computer.

**Comment by medvednikov** [comment]
Fixed in 0.1.20
