### ISSUE TITLE
Error: name clash

### ISSUE THREAD

**Issue by SewerynKaminski** [vlang/v#1994]
**V version:** 0.1.19
**OS:** Ubuntu 18.04 64bit

**What did you do?**
Try to compile

```
fn main(){
	array_f32 := 1
	array_f64 := 2
	array_bool:= 3
	array_i8  := 4
	array_byte:= 5
	array_i16 := 6
	array_u16 := 7
	array_int := 8	
	array_u32 := 9
	array_string:= 10
	array_rune  :=11

	a_f32 := []f32
	a_f64 := []f64
	a_bool:= []bool
	a_i8  := []i8
	a_byte:= []byte
	a_i16 := []i16
	a_u16 := []u16
	a_int := []int
	a_u32 := []u32
	a_string:=[]string
	a_rune:=[]rune

	println ( a_f32 )
	println ( a_f64 )
	println ( a_bool )
	println ( a_i8 )
	println ( a_byte )
	println ( a_i16 )
	println ( a_u16 )
	println ( a_int )
	println ( a_u32 )
	println ( a_string )
	println ( a_rune )

	println ( array_f32 )
	println ( array_f64 )
	println ( array_bool )
	println ( array_i8 )
	println ( array_byte )
	println ( array_i16 )
	println ( array_u16 )
	println ( array_int )
	println ( array_u32 )
	println ( array_string )
	println ( array_rune )
}
```
This is a few examples of name clash.

**What did you expect to see?**
Compilation without errors
 
**What did you see instead?**
C compiler=cc
nameclash.tmp.c:415:31: error: implicit declaration of function 'i8_str' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                strings__Builder_write(&sb, i8_str( ((i8 *) a.data)[i]));
                                            ^
nameclash.tmp.c:415:31: error: passing 'int' to parameter of incompatible type 'string' (aka 'struct string')
                strings__Builder_write(&sb, i8_str( ((i8 *) a.data)[i]));
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
nameclash.tmp.c:356:57: note: passing argument to parameter 's' here
void strings__Builder_write(strings__Builder* b, string s);
                                                        ^
nameclash.tmp.c:445:31: error: implicit declaration of function 'i16_str' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                strings__Builder_write(&sb, i16_str( ((i16 *) a.data)[i]));
                                            ^
nameclash.tmp.c:445:31: error: passing 'int' to parameter of incompatible type 'string' (aka 'struct string')
                strings__Builder_write(&sb, i16_str( ((i16 *) a.data)[i]));
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
nameclash.tmp.c:356:57: note: passing argument to parameter 's' here
void strings__Builder_write(strings__Builder* b, string s);
                                                        ^
nameclash.tmp.c:460:31: error: implicit declaration of function 'u16_str' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                strings__Builder_write(&sb, u16_str( ((u16 *) a.data)[i]));
                                            ^
nameclash.tmp.c:460:31: error: passing 'int' to parameter of incompatible type 'string' (aka 'struct string')
                strings__Builder_write(&sb, u16_str( ((u16 *) a.data)[i]));
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
nameclash.tmp.c:356:57: note: passing argument to parameter 's' here
void strings__Builder_write(strings__Builder* b, string s);
                                                        ^
nameclash.tmp.c:3669:10: error: expected ';' after expression
array_f32 a_f32=new_array_from_c_array(0, 0, sizeof(f32), (f32[]) {   0 }) ;
         ^
         ;
nameclash.tmp.c:3669:11: error: use of undeclared identifier 'a_f32'
array_f32 a_f32=new_array_from_c_array(0, 0, sizeof(f32), (f32[]) {   0 }) ;
          ^
nameclash.tmp.c:3671:10: error: expected ';' after expression
array_f64 a_f64=new_array_from_c_array(0, 0, sizeof(f64), (f64[]) {   0 }) ;
         ^
         ;
nameclash.tmp.c:3671:11: error: use of undeclared identifier 'a_f64'
array_f64 a_f64=new_array_from_c_array(0, 0, sizeof(f64), (f64[]) {   0 }) ;
          ^
nameclash.tmp.c:3673:11: error: expected ';' after expression
array_bool a_bool=new_array_from_c_array(0, 0, sizeof(bool), (bool[]) {   0 }) ;
          ^
          ;
nameclash.tmp.c:3673:12: error: use of undeclared identifier 'a_bool'
array_bool a_bool=new_array_from_c_array(0, 0, sizeof(bool), (bool[]) {   0 }) ;
           ^
nameclash.tmp.c:3675:9: error: expected ';' after expression
array_i8 a_i8=new_array_from_c_array(0, 0, sizeof(i8), (i8[]) {   0 }) ;
        ^
        ;
nameclash.tmp.c:3675:10: error: use of undeclared identifier 'a_i8'
array_i8 a_i8=new_array_from_c_array(0, 0, sizeof(i8), (i8[]) {   0 }) ;
         ^
nameclash.tmp.c:3677:11: error: expected ';' after expression
array_byte a_byte=new_array_from_c_array(0, 0, sizeof(byte), (byte[]) {   0 }) ;
          ^
          ;
nameclash.tmp.c:3677:12: error: use of undeclared identifier 'a_byte'
array_byte a_byte=new_array_from_c_array(0, 0, sizeof(byte), (byte[]) {   0 }) ;
           ^
nameclash.tmp.c:3679:10: error: expected ';' after expression
array_i16 a_i16=new_array_from_c_array(0, 0, sizeof(i16), (i16[]) {   0 }) ;
         ^
         ;
nameclash.tmp.c:3679:11: error: use of undeclared identifier 'a_i16'
array_i16 a_i16=new_array_from_c_array(0, 0, sizeof(i16), (i16[]) {   0 }) ;
          ^
nameclash.tmp.c:3681:10: error: expected ';' after expression
array_u16 a_u16=new_array_from_c_array(0, 0, sizeof(u16), (u16[]) {   0 }) ;
         ^
         ;
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by benob** [comment]
Just to add the list, naming variables tmp1, tmp2... also clashes with names generated for temporary variables such as indices in for loops. 
There are constraints on struct and variable names (Captialized, and lower-cased), but it would be better to prefix names with a unique prefix to prevent crashes with other C symbols. For example:
```
fn main() {
  printf := 3
  println(printf)
}
```
leads to the ugly error you would expect.

**Comment by serkonda7** [comment]
Error with V V 0.1.29 4774c89 is
```v
/tmp/v/testy.tmp.c:8043:11: error: expected ‘;’ before ‘a_f32’
 8043 |  array_f32 a_f32 = __new_array_with_default(0, 0, sizeof(f32), 0);
      |           ^~~~~~
      |           ;
/tmp/v/testy.tmp.c:8044:2: warning: statement with no effect [-Wunused-value]
 8044 |  array_f64 a_f64 = __new_array_with_default(0, 0, sizeof(f64), 0);
      |  ^~~~~~~~~
/tmp/v/testy.tmp.c:8044:11: error: expected ‘;’ before ‘a_f64’
 8044 |  array_f64 a_f64 = __new_array_with_default(0, 0, sizeof(f64), 0);
      |           ^~~~~~
      |           ;
...

```

**Comment by serkonda7** [comment]
```v
fn main() {
  printf := 3
  println(printf)
}
```
works fine
