### ISSUE TITLE
using -cc clang, compiling v with -cstrict fails

### ISSUE THREAD

**Issue by kimshrier** [vlang/v#19946]
### Describe the bug

I am running on FreeBSD 13.2 on amd64 and using clang as the C compiler.  The v version is `V 0.4.3 0da00cc
`. When running `v test-all` the test for compiling v with itself fails.  It is running `v -o vtmp_werror -cstrict cmd/v`.

The error messages are:
```
/tmp/v_1002/vtmp_werror.619519909005666459.tmp.c:42190:107: error: braces around scalar initializer [-Werror,-Wbraced-scalar-init]
        sync__ManyTimes* many_times = ((sync__ManyTimes*)memdup(&(sync__ManyTimes){.m = (sync__RwMutex){.mutex = {0},},.times = times,.count = 0,}, sizeof(sync__ManyTimes)));
                                                                                                                 ^~~
/tmp/v_1002/vtmp_werror.619519909005666459.tmp.c:42211:86: error: braces around scalar initializer [-Werror,-Wbraced-scalar-init]
        sync__Once* once = ((sync__Once*)memdup(&(sync__Once){.m = (sync__RwMutex){.mutex = {0},},.count = 0,}, sizeof(sync__Once)));
                                                                                            ^~~
2 errors generated.
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose
```
It does appear that the .mutex field should be initialized with `0` instead of `{0}`.

Where should I be looking in the compiler to see where this problem is coming from.  My first guess would be to look in `vlib/v/gen/c` somewhere, but it may be that the problem is earlier in the compiler and that the problem is in the AST that is built before the C generator is executed.

Pointers or suggestions would be helpful.

### Reproduction Steps

With a fresh clone of the master branch of v.
Since I am running on FreeBSD, I need to use gmake instead of make.
I have the directory where I cloned v in my PATH so executing `v` executes the one I just built.
```
$ cd wherever/you/cloned/v
$ export VFLAGS="-cc clang"
$ gmake
...
V has been successfully built
V 0.4.3 0da00cc
$ v test-all
```

### Expected Behavior

I expect v compiling itself with -cstrict to compile without errors.

### Current Behavior

v compiling itself with -cstrict produces the error messages mentioned above and the test fails.

### V version

V 0.4.3 0da00cc

### Environment details (OS name and version, etc.)

FreeBSD 13.2-RELEASE-p5 releng/13.2-n254643-3a088f485f74 GENERIC amd64

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
This is because on OpenBSD it is:

`typedef struct	pthread_rwlock		*pthread_rwlock_t;`

https://github.com/openbsd/src/blob/075cc07cd6bf90b4e36d130b6db9d1a626f5c17e/include/pthread.h#L120C1-L120C50

**Comment by kimshrier** [comment]
I am still confused by the generated `{0}`.  If I'm not mistaken, what is happening is that `.mutex` is being assigned a null pointer value.  I would expect `0` to be generated, not `{0}`.

**Comment by felipensp** [comment]
> I am still confused by the generated `{0}`. If I'm not mistaken, what is happening is that `.mutex` is being assigned a null pointer value. I would expect `0` to be generated, not `{0}`.

On Linux it is not a pointer, that is the point. We'll provide a fix.

**Comment by felipensp** [comment]
> I am still confused by the generated `{0}`. If I'm not mistaken, what is happening is that `.mutex` is being assigned a null pointer value. I would expect `0` to be generated, not `{0}`.

Can you try to build https://github.com/felipensp/v/tree/sync_freebsd ?

**Comment by kimshrier** [comment]
I ran in to a few errors.  The following is from my terminal session:
[make_output.txt](https://github.com/vlang/v/files/13432931/make_output.txt)

**Comment by felipensp** [comment]
> I ran in to a few errors. The following is from my terminal session: [make_output.txt](https://github.com/vlang/v/files/13432931/make_output.txt)

Can you try again?

**Comment by kimshrier** [comment]
You're getting closer.

[make_output_2.txt](https://github.com/vlang/v/files/13443105/make_output_2.txt)

**Comment by felipensp** [comment]
> You're getting closer.
> 
> [make_output_2.txt](https://github.com/vlang/v/files/13443105/make_output_2.txt)

Nice, thanks for your time. Can you test more one more time?

**Comment by kimshrier** [comment]
success!
[make_output_3.txt](https://github.com/vlang/v/files/13445330/make_output_3.txt)

**Comment by felipensp** [comment]
Thanks for testing. Can you run sync tests? `v test vlib/sync`

**Comment by kimshrier** [comment]
There is a problem with some of the sync tests when I use tcc as the C compiler.  clang and gcc work.  This has been true for several weeks at least and is not a new development.  The tests channel_2_test.v, channel_3_test.v, channel_close_test.v, channel_opt_propagate_test.v, channel_push_or_1_test.v, and channel_push_or_2_test.v are failing in the following run with tcc.  They are typically the ones that fail, but not always, and I have to kill the individual test process in order to have the tests continue.  I have not looked into the code generated by tcc to see why these tests just lock up and don't complete.

[sync_test_output.txt](https://github.com/vlang/v/files/13445589/sync_test_output.txt)
