### ISSUE TITLE
Operator precedence is wrong when casted value is left-shifted in if/match expr

### ISSUE THREAD

**Issue by lemoncmd** [vlang/v#19978]
### Describe the bug

I'm so afraid of this bug that I can't even use any expression

### Reproduction Steps

```v
println(u8(1) << 1 | 1)
println(match 0 {
        0 { u8(1) << 1 | 1 }
        else { 0 }
})
println(if 0 == 0 {
        u8(1) << 1 | 1
} else {
        0
})
```

### Expected Behavior

```
3
3
3
```

### Current Behavior

```
3
2
2
```
`u8(1) << (1 | 1)` is calculated instead (why?)

### V version

V 0.4.3 043ebb8

### Environment details (OS name and version, etc.)

OS: Arch Linux
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
Code generated:

```V
VV_LOCAL_SYMBOL void main__main(void) {
        println(u8_str(((((u8)(1)) << 1) | 1)));
        println(u8_str(((0 == (0))? ((((u8)(1)) << 1)) : (0))));
        println(u8_str((true ? ((((u8)(1)) << 1)) : (0))));
}
```

**Comment by lemoncmd** [comment]
```v
a := 1
println(match 0 {
        0 { u8(1) << 1 | a }
        else { 0 }
})
```
generates
```
VV_LOCAL_SYMBOL void main__main(void) {
        int a = 1;
        println(u8_str(((0 == (0))? ((((u8)(1)) << (1 | a))) : (0))));
}
```
so it is about precedence

**Comment by felipensp** [comment]
Ah right. I've checked it with:

```V
fn main() {
	println(if false {
			u8(1) << 1 | 2
	} else {
			0
	})
}
```

Generates:
`println(u8_str((false ? ((((u8)(1)) << 3)) : (0))));`

**Comment by Krchi** [comment]
I have the same problem, I handled it locally, but it still has problem in array
```v
fn test_test() {
	mut arr := [u8(1), 9]
	arr << 3
	t := if true {
		arr[0] << 1 | arr[1]
	} else {
		1
	}
	println(t) // print 0, should be 11
}

```
u8(id) is `CastExpr`, but arr[0] is `IndexExpr`, I cant get what type store in array

**Comment by lemoncmd** [comment]
I found it radically difficult to solve this kind of problem:
```v
a := 1
b := match 0 {
    0 {
        a << 1 | 1 // compiler have to parse it as (a << 1) | 1
    }
    else {
        0
    }
}
```
vs.
```v
mut a := [0]
match 0 {
    0 {
        a << 1 | 1 // compiler have to parse it as a << (1 | 1)
    }
    else {
    }
}
```
This is completely context-sensitive.

**Comment by felipensp** [comment]
> I found it radically difficult to solve this kind of problem:
> 
> ```v
> mut a := [0]
> b := 1
> c := match 0 {
>     0 {
>         a << 1 | 1 // compiler have to parse it as a << (1 | 1)
>         b << 1 | 1 // compiler have to parse it as (b << 1) | 1
>     }
>     else {
>         0
>     }
> }
> ```
> 
> This is completely context-sensitive.

Yes, for Ident it is. But for the CastExpr treated here it is okay for now.
