### ISSUE TITLE
implements and interface, return type not match

### ISSUE THREAD

**Issue by kyubuns** [vlang/v#200]
```
struct Dog {
	a int
}

fn (d Dog) speak() int {
	return 3
}

interface Speaker {
        speak() string
}

fn perform(s Speaker) {
	println(s.speak())
}

fn main() {
	dog := Dog{}
	perform(dog)
}
```

`fn (d Dog) speak() int` is not match `speak() string`.
But the code has build success on 0.0.7.
(error in runtime `V panic: println(NIL)`)

**Comment by M4SSD35TRUCT10N** [comment]
With current master it prints nothing on Windows 10 1809. But the interface was defined with `string` for function `speak` and you implemented it as `int` return value. I think this should result in a compile error.

**Comment by Ivo-Balbaert** [comment]
This code now results in a C compile error on Windows and Playground:

C:\Users\CVO\AppData\Local\Temp\v\test.tmp.c:586:40: warning: initialization of 'void **' from incompatible pointer type 'int (*)(Dog)' {aka 'int (*)(struct Dog)'} [-Wincompatible-pointer-types]
 void...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

Perhaps this is enough to close the issue

**Comment by Ivo-Balbaert** [comment]
This now (V 0.1.27 7963e48)  returns a V error on Windows 10 and on the Playground:

test.v:19:10: error: `Dog` incorrectly implements method `speak` of interface `Speaker`, expected `speak() string`
