### ISSUE TITLE
vfmt's recent automatic const scope unwrapping ruins valuable trailing comments in `vlang/sdl`

### ISSUE THREAD

**Issue by Larpon** [vlang/v#20000]
### Describe the bug

vfmt's recent automatic const scope unwrapping ruins valuable trailing comments in `vlang/sdl`:
![image](https://github.com/vlang/v/assets/768942/6deee72d-5e22-4c04-914c-38713fa55a10)

### Reproduction Steps

Run `v fmt -w ~/.vmodules/sdl/audio.c.v` and see how comments are moved to new lines below the statements and as an extra bonus it will also eat the *last* trailing comment :smile: 

### Expected Behavior

![image](https://github.com/vlang/v/assets/768942/5db4a283-fe3a-4af9-80df-4768c2f0e886)

### Current Behavior

![image](https://github.com/vlang/v/assets/768942/6deee72d-5e22-4c04-914c-38713fa55a10)

### V version

V 0.4.3 b088f43

### Environment details (OS name and version, etc.)

Arch-based EndeavourOS
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
With latest V, it seems to work fine now:
![image](https://github.com/vlang/v/assets/26967/f4d23fb0-5a67-4260-9a1d-fafa34279299)
