### ISSUE TITLE
cgen: wrong array arg cast on methods using `[]T` as parameter

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#20033]
### Describe the bug

Methods using `[]T` as parameter with problem

### Reproduction Steps

```v
module main

struct Decoder {
}

pub fn (mut d Decoder) decode[T](mut val T) {
	d.decode_array[T](mut val)
	decode_array(mut val)
}

fn (mut d Decoder) decode_array[T](mut val []T) {
	println(T.name)
}

fn decode_array[T](mut val []T) {
	println(T.name)
}

fn main() {
	mut arraia := [1]
	mut d := Decoder{}

	d.decode(mut arraia)
}
```

### Expected Behavior

int
int

### Current Behavior

[]int
int

### V version

V 0.4.3 782bf86

### Environment details (OS name and version, etc.)

Linux Ubuntu
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by yuyi98** [comment]
`d.decode_array[T](mut val)` should be `d.decode_array(mut val)`.
```v
struct Decoder {
}

pub fn (mut d Decoder) decode[T](mut val T) {
	d.decode_array(mut val)
	decode_array(mut val)
}

fn (mut d Decoder) decode_array[T](mut val []T) {
	println(T.name)
}

fn decode_array[T](mut val []T) {
	println(T.name)
}

fn main() {
	mut arraia := [1]
	mut d := Decoder{}

	d.decode(mut arraia)
}

PS D:\Test\v\tt1> v run .
int
int
```

**Comment by enghitalo** [comment]
Thank you!!
