### ISSUE TITLE
fmt commented line formatting issue

### ISSUE THREAD

**Issue by dmitryuck** [vlang/v#20069]
### Describe the bug

I have a commented part of the code:

```
/*
	users := sql u.db {
		select from User where id == id && random_id == random_id
	} or { return none }

	if users.len == 0 {
		return none
	}

	return users[0]*/
```

When I click save in my VsCode it increases the space between lines after each save:

```
/*
	users := sql u.db {



		select from User where id == id && random_id == random_id



	} or { return none }







	if users.len == 0 {



		return none



	}







	return users[0]*/
```

### Reproduction Steps

make a multiline comment and click save in VSCode

### Expected Behavior

fmt should not add extra lines in commented code

### Current Behavior

fmt adds extra lines in commented code

### V version

V 0.4.3 782bf86

### Environment details (OS name and version, etc.)

V full version: V 0.4.3 e30af86.782bf86
OS: windows, Microsoft Windows 11 Home v22000 64-bit
Processor: 6 cpus, 64bit, little endian,

getwd: D:\Projects\MegaStor\megastor-server
vexe: D:\Programs\v\v.exe
vexe mtime: 2023-12-01 08:06:53

vroot: OK, value: D:\Programs\v
VMODULES: OK, value: C:\Users\monkg\.vmodules
VTMP: OK, value: C:\Users\monkg\AppData\Local\Temp\v_0

Git version: git version 2.37.0.windows.1
Git vroot status: weekly.2023.48-8-g782bf865-dirty (23 commit(s) behind V master)
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc: N/A
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
Would not be this about v-analyzer? https://github.com/vlang/v-analyzer
