### ISSUE TITLE
time.TimeParseError: Invalid time format code: 0, error: invalid month three letters

### ISSUE THREAD

**Issue by AritraBanik08** [vlang/v#20073]
### Describe the bug

Code: https://vosca.dev/p/742e925f3f

```v
import time

fn main() {
	c := 'Dec 04 2023'
	s := time.parse_format(c, 'MMM DD YYYY') or { panic(err) }
	a := s.str()
	t := time.parse(a) or { panic('failing format: ${a} | err: ${err}') }
	println(t)
}

```

### Reproduction Steps

Run the above code please. Thank you.

### Expected Behavior

```
2023-12-04 00:00:00
```

### Current Behavior

Output:

```
V panic: time.TimeParseError: Invalid time format code: 0, error: invalid month three letters
v hash: cd337e2
/tmp/v_60000/../../../../../../home/admin/v/vlib/builtin/builtin.c.v:119: at _v_panic: Backtrace
/tmp/v_60000/../../../../../../box/code.v:5: by main__main
/tmp/v_60000/../../../../../../tmp/v_60000/code.14312254348786731813.tmp.c:17024: by main
Exited with error status 1
```

### V version

V 0.3.3 e738d67

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.3 cd337e2
OS: linux, Debian GNU/Linux 11 (bullseye) (VM)
Processor: 1 cpus, 64bit, little endian, Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz

getwd: /home/admin/playground
vexe: /home/admin/v/v
vexe mtime: 2023-11-11 13:42:45

vroot: OK, value: /home/admin/v
VMODULES: OK, value: /.vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.30.2
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false

CC version: cc (Debian 10.2.1-6) 10.2.1 20210110
thirdparty/tcc: N/A
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Delta456** [comment]
The snippet given by you is working. Please try with the latest version of V which has to be done locally.

```
2023-12-04 00:00:00
```

**Comment by AritraBanik08** [comment]
I am already using the latest version of Vlang. Please test by running the code on `https://play.vlang.io/`. Thank you.

**Comment by shove70** [comment]
The version at https://play.vlang.io/ is not the latest

The version at https://play.vosca.dev/ will be updated, so test it out here:

<img width="697" alt="image" src="https://github.com/vlang/v/assets/27794478/a5a42b62-0311-43ea-97bd-a210bb5cbc0a">

**Comment by AritraBanik08** [comment]
The V version 0.4.3 4b31092 is not available on github, where can I get it?

**Comment by shove70** [comment]
Can you provide information that is not available?

Please refer to:
https://github.com/vlang/v/blob/master/README.md#installing-v-from-source
