### ISSUE TITLE
multiline comments' internal formatting should be preserved fully by vfmt

### ISSUE THREAD

**Issue by verulian** [vlang/v#20080]
### Describe the bug

@Coachonko observed multiline comments are corrupted by vfmt: https://discord.com/channels/592103645835821068/592106336838352923/1181003477586022560

![chat](https://i.ibb.co/VmgtS7j/multiline-comment-vfmt.png)

### Reproduction Steps

Try:
```
/*
 *
 * BRUH
 *
 */
```

### Expected Behavior

Should remain formated same.

### Current Behavior

Becomes:
```
/*
*
 * BRUH
 *
*/
```

### V version

current

### Environment details (OS name and version, etc.)

N/A
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Coachonko** [comment]
Thank you I am happy now
