### ISSUE TITLE
wrong code generated when returning generic map 

### ISSUE THREAD

**Issue by felipensp** [vlang/v#20106]
### Describe the bug

The cgen is generating wrong code when `map[K]V` is used as return type.

### Reproduction Steps

```V
module main

fn generic[K,V](a map[K]V) {
	t := expect_map(a)
	dump(t)
}

fn expect_map[K, V](a map[K]V) map[K]V {
	return a
}

fn main() {
	a := { 'a': 1 }
	b := { 1: 'a' }
	generic(a)
	generic(b)
}
```

### Expected Behavior

[bug.v:6] t: {'a': 1}
[bug.v:6] t: {1: 'a'}

### Current Behavior

[bug.v:6] t: {'a': 1}
[bug.v:6] t: {'': 6676186}

### V version

master

### Environment details (OS name and version, etc.)

V full version: V 0.4.3 b347f54.55e86fe
OS: linux, Debian GNU/Linux 10 (buster) (VM) (WSL)
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz

getwd: /home/felipe/github/v
vexe: /home/felipe/github/v/v
vexe mtime: 2023-12-06 13:48:44

vroot: OK, value: /home/felipe/github/v
VMODULES: OK, value: /home/felipe/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.20.1
Git vroot status: weekly.2023.27-1067-g55e86feb
.git/config present: true

CC version: cc (Debian 8.3.0-6) 8.3.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by yuyi98** [comment]
```v
fn generic[K, V](a map[K]V) {
	t := expect_map[K, V](a)
	dump(t)
}

fn expect_map[K, V](a map[K]V) map[K]V {
	return a
}

fn main() {
	a := {'a': 1}
	b := {1: 'a'}
	generic(a)
	generic(b)
}

PS D:\Test\v\tt1> v run .
[.\\tt1.v:3] t: {'a': 1}
[.\\tt1.v:3] t: {1: 'a'}
```

**Comment by yuyi98** [comment]
In general, calling other related generic functions in generic functions requires setting the generic type.

**Comment by shove70** [comment]
yuyi is the expert, haha, but he is busy recently, it would be better if he had time to handle.
I'll be looking at that too, as it just so happens that generics related is in my work list
