### ISSUE TITLE
compilation success when call not existed method on struct

### ISSUE THREAD

**Issue by dmitryuck** [vlang/v#20120]
### Describe the bug

I have a simple code:

```
module controller

import vweb
import entity
import usecase { ILanguageUsecase }

pub struct LanguageController {
	vweb.Context
	language_usecase ILanguageUsecase @[vweb_global]
}

@['/'; get]
pub fn (mut m LanguageController) user_index() vweb.Result {
	return m.html('Hello')
}

@['/insert-languages'; get]
pub fn (mut m LanguageController) insert_languages() vweb.Result {
	m.insert_languages()

	return m.html('Insert')
}
```

and it compiles success, but in runtime I got an an error:

**Unhandled Exception 0xC00000FD**

as you see I call a method which not exists on LanguageController struct:

`m.insert_languages()`

but this method exists in ILanguageUsecase interface, so the next code works as expected

`m.language_usecase.insert_languages()`

### Reproduction Steps

copy provided code and compile

### Expected Behavior

should not be compiled, and throw an error, because method not exists in structure

### Current Behavior

compiles success, throw runtime errorthrows

### V version

V 0.4.3 772f114

### Environment details (OS name and version, etc.)

V full version: V 0.4.3 3d0fcfe.772f114
OS: windows, Microsoft Windows 11 Home v22000 64-bit
Processor: 6 cpus, 64bit, little endian,

getwd: D:\Projects\MegaStor\megastor-server
vexe: D:\Programs\v\v.exe
vexe mtime: 2023-12-08 08:46:04

vroot: OK, value: D:\Programs\v
VMODULES: OK, value: C:\Users\monkg\.vmodules
VTMP: OK, value: C:\Users\monkg\AppData\Local\Temp\v_0

Git version: git version 2.37.0.windows.1
Git vroot status: weekly.2023.48-62-g772f1149 (8 commit(s) behind V master)
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc: N/A
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by shove70** [comment]
```v
@['/insert-languages'; get]
pub fn (mut m LanguageController) insert_languages() vweb.Result {
                                        ↑
	m.insert_languages()  --------> ↑

	return m.html('Insert')
}
```

```insert_languages()``` 
calls are recursively made endlessly until the stack is exhausted...
