### ISSUE TITLE
compiler: support for `$for G in field_value.$variants {` and `$if field_value is G {`

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#20176]
### Describe the feature

Discussed on https://discord.com/channels/592103645835821068/592320321995014154/1184528450824970321

### Use Case

```v
module main

type SumTypeValue = SomeStruct | int | string
struct Abc { s SumTypeValue }

fn encode_struct[S](struc S) string {
    $if S is $struct {
        $for field in S.fields {
            field_value := struc.$(field.name)
            $if field_value is $sumtype {
                $for G in field_value.$variants {
                    $if field_value is G {
                        return typeof(field_value).name
                    }
                }
            }
        }
    }
}

assert encode_struct(Abc{SomeStruct{}}) == 'SomeStruct'
assert encode_struct(Abc{1}) == 'int'
assert encode_struct(Abc{'lala'}) == 'string'
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.4.3 964798d

### Environment details (OS name and version, etc.)

Ubuntu
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by enghitalo** [comment]
I don't think this issue can be closed

**Comment by enghitalo** [comment]
@medvednikov, @felipensp I don't think this PR can be closed

```v
type TestSum = int | string
struct Abc { s TestSum }

fn gen[T](struc T) bool {
    $if T is $struct {
        $for field in T.fields {
            field_value := struc.$(field.name)
            $if field_value is $sumtype {
                // What can I but on <???>?
                $for f in <???>.variants {
                    $if field_value is f {
                        println(typeof(field_value).name)
                        println(field_value)
                        return true
                    }
                }
            }
        }
    } 
    return false
}

fn main() {
    a := Abc{TestSum(123)}
    assert gen(a)
}
```

**Comment by spytheman** [comment]
I think we only need this `$if field_value is G {` now @felipensp ?

**Comment by felipensp** [comment]
> I think we only need this `$if field_value is G {` now @felipensp ?
Yes.

It is missing the way to retrieve the sumtype as its current variant type.
