### ISSUE TITLE
pointer stored in a closure changes on its own

### ISSUE THREAD

**Issue by spytheman** [vlang/v#20208]
**V doctor:**
```
V full version: V 0.4.3 c5a6aeb.b44fb15
OS: linux, Ubuntu 20.04.6 LTS
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i3-3225 CPU @ 3.30GHz

getwd: /space/v/oo
vexe: /space/v/oo/v
vexe mtime: 2023-12-17 18:01:31

vroot: OK, value: /space/v/oo
VMODULES: OK, value: /home/delian/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.42.0
Git vroot status: weekly.2023.50-47-g050344ae-dirty
.git/config present: true

CC version: cc (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg p.v`
```v
@[heap]
struct Abc {
	value int
}

@[heap]
struct Container {
	aa &Abc = unsafe { nil }
}

fn (mut c Container) m() fn () {
	mut cr := &c
	dump(voidptr(c.aa))
	dump(voidptr(cr.aa))
	f := fn [mut cr] () {	
		dump(voidptr(cr.aa))
		dump(cr)
	}
	return f
}

mut c := &Container{aa: &Abc{1234}}
dump(voidptr(c))
dump(c)
dump(voidptr(c.aa))
f := c.m()
f()

```

**What did you expect to see?**

The same printed values for c: and for cr: at the end

**What did you see instead?**
```
[p.v:23] voidptr(c): 0x7ffff7f82fd0
[p.v:24] c: &Container{
    aa: &Abc{
        value: 1234
    }
}
[p.v:25] voidptr(c.aa): 0x7ffff7f82fe0
[p.v:13] voidptr(c.aa): 0x7ffff7f82fe0
[p.v:14] voidptr(cr.aa): 0x7ffff7f82fe0
[p.v:16] voidptr(cr.aa): 0x7ffff7f82fa0
[p.v:17] cr: Container{
    aa: &Abc{
        value: -134729760
    }
}
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by DevrosTheOne** [comment]
If you put the assignment `mut cr := &c` in `unsafe{}` block it seems to work ?
```v
fn (mut c Container) m() fn () {
	mut cr := unsafe{ &c }
	dump(voidptr(c.aa))
	dump(voidptr(cr.aa))
	f := fn [mut cr] () {	
		dump(voidptr(cr.aa))
		dump(cr)
	}
	return f
}
```
```
[code.v:23] voidptr(c): 0x15048cbdcfd0
[code.v:24] c: &Container{
    aa: &Abc{
        value: 1234
    }
}
[code.v:25] voidptr(c.aa): 0x15048cbdcfe0
[code.v:13] voidptr(c.aa): 0x15048cbdcfe0
[code.v:14] voidptr(cr.aa): 0x15048cbdcfe0
[code.v:16] voidptr(cr.aa): 0x15048cbdcfe0
[code.v:17] cr: &Container{
    aa: &Abc{
        value: 1234
    }
}
```

**Comment by xjzh123** [comment]
> If you put the assignment `mut cr := &c` in `unsafe{}` block it seems to work ? Tested with Playground and MacOS
> 
> ```v
> fn (mut c Container) m() fn () {
> 	mut cr := unsafe{ &c }
> 	dump(voidptr(c.aa))
> 	dump(voidptr(cr.aa))
> 	f := fn [mut cr] () {	
> 		dump(voidptr(cr.aa))
> 		dump(cr)
> 	}
> 	return f
> }
> ```
> 
> ```
> [code.v:23] voidptr(c): 0x15048cbdcfd0
> [code.v:24] c: &Container{
>     aa: &Abc{
>         value: 1234
>     }
> }
> [code.v:25] voidptr(c.aa): 0x15048cbdcfe0
> [code.v:13] voidptr(c.aa): 0x15048cbdcfe0
> [code.v:14] voidptr(cr.aa): 0x15048cbdcfe0
> [code.v:16] voidptr(cr.aa): 0x15048cbdcfe0
> [code.v:17] cr: &Container{
>     aa: &Abc{
>         value: 1234
>     }
> }
> ```

If `unsafe` is used here, `cr` will just be a same pointer as `c`, but otherwise, `cr` is copied.

**Comment by xjzh123** [comment]
Maybe trivil, but as a newbie I find it notable that `mut cr := &c` and `mut cr := c` is identical. Here `&c` and `&(c)` have different semantic. Anybody know the logic behind this design?
