### ISSUE TITLE
Ternary operator

### ISSUE THREAD

**Issue by Le0X8** [vlang/v#20257]
### Describe the feature

This feature is already implemented in many programming languages, e. g. JavaScript, Java and Dart, but V lacks this feature.

The ternary operator (also often referred as the conditional operator) is a new operator, which can be frequently used as an alternative to an if/else statement.

Syntax: condition ? exprIfTrue : exprIfFalse

```v
// ternary operator
x := true ? 10 : 0

// if/else
if true {
	x := 10
} else {
	x := 0
}
```

### Use Case

This is a feature that can help developers write simpler and cleaner code, also it can save someone lots of LOC to implement something.

Also, this feature is good for parity: new developers will feel better when switching to V because of common features.

I myself am a JavaScript developer switching to V, and I would appreciate an addition of this feature to the V language.

### Other Information

[Ternary operator in JavaScript (MDN)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_operator)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.4.3 c7ce72f

### Environment details (OS name and version, etc.)

V full version: V 0.4.3 2964855.c7ce72f
OS: linux, Debian GNU/Linux 12 (bookworm)
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz

getwd: /home/leo/Documents/ieee754
vexe: /opt/v/v
vexe mtime: 2023-12-23 16:09:23

vroot: OK, value: /opt/v
VMODULES: OK, value: /home/leo/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.39.2
Git vroot status: weekly.2023.51-28-gc7ce72f3
.git/config present: true

CC version: cc (Debian 12.2.0-14) 12.2.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3-dirty
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by penguindark** [comment]
V has already a ternary operator:
```v
x := 2
a := if (x > 1 ) {x} else {0}
// a == 2
```

**Comment by penguindark** [comment]
I'm closing this issue because already implemented.
