### ISSUE TITLE
bool operation is strange

### ISSUE THREAD

**Issue by luoheng23** [vlang/v#2029]
**V version:** 
0.1.20
**OS:** 
win10
**What did you do?**
run the code:
```
if !0 || true {
    println(1)
}
```
**What did you expect to see?**
compile sucessfully and output 1.
 
**What did you see instead?**
compile error:
```
if !0 || true {
              ^
.v:2:15: expected type `int`, but got `bool`
```

The bool operation in v is really strange. Basically, v only receives `bool` type in `if` statement, like `if 1 && 1` won't compile. However, if I use `!` to convert a `int` type or other type to `bool`, then the latter parameters have to be the same type (`int`), other type like `bool` will cause an error.
As a result, `if !0 && 1` will compile, while `if !0 && !0` won't compile.

**Comment by medvednikov** [comment]
This is a bug with `!`, good find.

Ints can't be cast to bools.

**Comment by gslicer** [comment]
@luoheng23 you can cast int by defining your own true/false numeric values, e.g. if I define that 0 and below shall be "false" and everything above 0 "true" the code might look like:

```
module main

/*
cast_int_bool - casts an int into boolean based on my rule
 */
fn cast_int_bool (x int ) bool {
    return x > 0
}

fn main () { 

x := 5 // int
y := -1 // int

bx := cast_int_bool(x)
by := cast_int_bool(y)

if bx { println('$x is "$bx"') } 
else { println('$x is "$bx"') }
// shall print: 5 is "true"

if by { println('$y is "$by"') }
else { println('$y is "$by"') } 
// shall print: -1 is "false"

}
```
