### ISSUE TITLE
Closure IIFE is not called

### ISSUE THREAD

**Issue by xjzh123** [vlang/v#20306]
### Describe the bug

V supports IIFE, which is useful in concurrency. However, similar "closure IIFE" is not called, and it gives no warning or error message. It just did nothing.

### Reproduction Steps

```v
x := 1

fn () {
	println(1)
}()

fn [x] () {
	println(2)
}()
```

### Expected Behavior

```
1
2
```

### Current Behavior

```
1
```

### Possible Solution

handle closure IIFE

### Additional Information/Context

I find this exploring #20208

### V version

V 0.4.3 cd337e2

### Environment details (OS name and version, etc.)

V Playground
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by shove70** [comment]
This is a playground problem:

<img width="1366" alt="image" src="https://github.com/vlang/v/assets/27794478/aa37a5be-bb5b-4df0-8ef1-6996808537ab">
