### ISSUE TITLE
v up abnormal termination with v installed into C:\Program Files

### ISSUE THREAD

**Issue by wh-timme** [vlang/v#2031]
**V version:** 0.1.20 b009223 / mingw-w64 x86_64-8.1.0-posix-seh-rt_v6-rev0
**OS:** Win 10 1809

**What did you do?**
C:\Program Files\V>v up

**What did you expect to see?**
nop, due to at latest version already

**What did you see instead?**
v up terminated abnormally due to the space char between "Program" and "Files" in path.
v.exe is renamed to v_old.exe and command “v" is not executable any more.

**Comment by joe-conigliaro** [comment]
@wh-timme Im fixing this now, thanks for reporting!
