### ISSUE TITLE
cgen error: _ := voidptr(a)

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#20348]
### Describe the bug

https://play.vlang.io/p/51acb00f49

### Reproduction Steps

https://play.vlang.io/p/51acb00f49
```v
a := ''
unsafe {
_ := voidptr(a)
}
```

### Expected Behavior

not cgen error
maybe `voidptr(a) == 0` ?

### Current Behavior

```bash
Running code...
Can't run code. The server returned an error:
/tmp/v_60000/../../../../../../box/code.v:3: error: cannot convert 'struct string' to 'void *'
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

Exited with error status 1
Please try again.
```

### V version

https://play.vlang.io/ version

### Environment details (OS name and version, etc.)

https://play.vlang.io/ OS
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by shove70** [comment]
I think, `string -> voidptr`  Should be disallowed, whether it's in unsafe or not.

**Comment by Delta456** [comment]
A C error is also thrown when `byteptr` and `charptr` casts are used instead.

**Comment by dumblob** [comment]
@Delta456 @JalonSolov did you get any feedback on disallowing cast of `string` to any pointer (`byteptr` `charptr` ...)?

**Comment by Delta456** [comment]
> @Delta456 @JalonSolov did you get any feedback on disallowing cast of `string` to any pointer (`byteptr` `charptr` ...)?

Nope.

**Comment by JalonSolov** [comment]
It shouldn't be allowed, because `string` is a struct.  It's not a `charptr` (which is `char *`) or a `byteptr (which is basically the same thing).  Casting `string.str` to one of these will be fine, but not `string` itself.
