### ISSUE TITLE
Implement `if num in start..end`

### ISSUE THREAD

**Issue by Delta456** [vlang/v#20352]
### Describe the feature

There was a discussion happening on the discord server to implement.

```v
i := 42
if i in 10..100 {
    println('i is in range between 10 and 100')
} else {
    println('i dont know')
}
```

### Use Case

This feature is handy when checking whether a specific int or character is in that range. We also have this in the match but it uses an inclusion i.e. `[start, end]` rather than `[start, end)`. The same has to be implemented but for `[start, end)`.

### Proposed Solution

This is easy to implement. The generated code will just compare whether the num or character is between that range or not. Just like it is implemented for match statements.

### Other Information

Only constants, untyped numbers and characters are allowed to be here. Also check if the given range is valid or not.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V Latest

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.3 c0d7c58.5d75d06
OS: linux, Pop!_OS 22.04 LTS
Processor: 12 cpus, 64bit, little endian, AMD Ryzen 5 5600H with Radeon Graphics

getwd: /home/delta
vexe: /home/delta/Documents/git/v_dev/v
vexe mtime: 2024-01-02 14:27:22

vroot: OK, value: /home/delta/Documents/git/v_dev
VMODULES: OK, value: /home/delta/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.34.1
Git vroot status: weekly.2023.52-54-g6bcb47ef
.git/config present: true

CC version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
@Delta456  are you going to implement it?

**Comment by Delta456** [comment]
> @Delta456  are you going to implement it?

I initially wanted to do it but feel free to go!
