### ISSUE TITLE
support showing help for `v -?`

### ISSUE THREAD

**Issue by spytheman** [vlang/v#20355]
### Describe the feature

Currently `v help` works, `v -help` also works, but `v -?` does not.

### Use Case

Help people accustomed to using `-?` to get help and learn about all the topics that V's help system knows about.

### Proposed Solution

implement support for `-?` in the V's command line arguments parser.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

not relevant

### Environment details (OS name and version, etc.)

not relevant
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by MCausc78** [comment]
@spytheman it was implemented and merged, can you close that issue?

**Comment by spytheman** [comment]
Sorry, I just saw the notification :-| .

Thanks @JalonSolov .
