### ISSUE TITLE
Compiled code does not work

### ISSUE THREAD

**Issue by mig-hub** [vlang/v#2038]
**V version: V 0.1.20 a94c155** 
**OS: osx 10.13.6** 

**What did you do?**
I created a "test.v" file with the simple example on the homepage of vlang.io which only prints a few things to the console:

```
fn main() {
	areas := ['game', 'web', 'tools', 'science', 'systems',
	          'embedded', 'drivers', 'GUI', 'mobile'] 
	for area in areas {
		println('Hello, $area developers!')
	}
}
```

Then I compiled it with `v test.v`. It seemed to work, at least there was no error message. A binary was compiled (around 74KB). But when I run it, nothing happens. There is no output.

I checked the REPL and in the REPL I can use `println` without any problem.

I also noticed it created a folder called "test.dSYM" which contained the structure you normally have in "Contents" when you create a GUI app on OSX.

I installed V using the simple steps on the homepage:

```
git clone https://github.com/vlang/v
cd v
make
```

Classic so I don't think there is any problem on the install, also considering the fact that everything else work. I can ask V for `--help`, `--version`, etc. I can even output the C code instead with `-o test.c`. And if I do this and then compile it with `gcc test.c`, I can run `./a.out` and it works as expected. 

**What did you expect to see?**
I expected to see all the sentences printed on STDOUT when I run `./test`.
 
**What did you see instead?**
Nothing.

**Comment by joe-conigliaro** [comment]
@mig-hub the problem is the file name, files that end with `test` are treated as tests. and tests print no output unless ans assert statement fails.

So rename it and you should be good to go :)

**Comment by mig-hub** [comment]
@joe-conigliaro Oh thank you that worked! I've read about tests, but I thought they had to end with "_test" (including the underscore).

Thank you.

**Comment by avitkauskas** [comment]
No, actually it's weird. Test files do have to end with '_test', and files files named 'test.v' should compile and run normally. And it runs for me normaly (also on Mac OS, tried V versions V 0.1.20 b009223 and V 0.1.20 a94c155) with the file named 'test.v'

So, the problem is not in the name of the file. Perhaps @mig-hub expected the file to be not only compiled but also run. Compilation does not produce any output. You have to run the executable, of course.

**Comment by joe-conigliaro** [comment]
My bad @avitkauskas is totally correct, they do have to end with `_test.v`

**Comment by mig-hub** [comment]
@avitkauskas I do know that it does not run it automatically after the compilation. I did run `./test`. Funny enough, `v run test.v` works fine actually. But the executable produced with `v test.v` definitely fails.

Here is the output when I use `--debug`:

```
C compiler=cc
all .v files:
["/Users/mig/scratchpad/v/vlib/builtin/array.v", "/Users/mig/scratchpad/v/vlib/builtin/string.v", "/Users/mig/scratchpad/v/vlib/builtin/builtin.v", "/Users/mig/scratchpad/v/vlib/builtin/int.v", "/Users/mig/scratchpad/v/vlib/builtin/utf8.v", "/Users/mig/scratchpad/v/vlib/builtin/map.v", "/Users/mig/scratchpad/v/vlib/builtin/option.v", "/Users/mig/scratchpad/v/vlib/strings/builder.v", "/Users/mig/scratchpad/v/vlib/strings/similarity.v", "/Users/mig/scratchpad/v/vlib/strings/strings.v", "test.v"]
```

**Comment by mig-hub** [comment]
As you can see, I do not set `$CC` and therefore it is using plain cc, not gcc or clang. Could it be related to this?

**Comment by mig-hub** [comment]
Nevermind my last comment, I tried with `--cc gcc` and it fails as well.

**Comment by joe-conigliaro** [comment]
Thanks @mig-hub, it's quite strange, I haven't been able to reproduce it yet,
the CC thing should be fine, since you said it works with run, and when the file is named something else?
Could you please try something? Could you copy the file to `working.v` and do `v -o working.c working.v` and also `v -o bad.c test.v`  then if you could do `diff working.c bad.c` and paste the output here?

**Comment by mig-hub** [comment]
@joe-conigliaro Yes I said thank you because changing the file name worked. Very odd. Maybe the way test files are segregated is different when just compiling or using `run`.

**Comment by mig-hub** [comment]
@joe-conigliaro No difference. But this is not surprising because like I mentioned, exporting C and then compiling with gcc works. It is only when compiling through V.

As far as I understand V still exports C and then compiles it (no direct machine code), therefore there must be a difference somewhere. It seems exporting C code or using `run` exports the right C code. But not `v test.c`. I can't help but think the difference is that `v test.v` thinks it is a test file, but not `v run test.v` or `v -o test.c test.v`. 

I did not check the code of the compiler yet, but there must be something like that.

**Comment by mig-hub** [comment]
@joe-conigliaro Here is what I get if I ask to show the C compilation command:

```
cc  -std=gnu11 -w -g -Werror=implicit-function-declaration -o "test" -x objective-c "/Users/mig/scratchpad/v/test.tmp.c" -x none -mmacosx-version-min=10.7
```

**Comment by joe-conigliaro** [comment]
Are you able to run the commands I was asking? To get a diff of the generated  .C files? Or are you saying no `bad.c` file was generated when you did `v -o bad.c test.v`

**Comment by mig-hub** [comment]
@joe-conigliaro Yes, no diff. Same code like I said above. I am thinking now that it could be interfering with the builtin zsh `test` function. Because I can run the bin if I go outside the folder and run `directory/test`. It is strange because I have "." in my $PATH and it still fail if I do `./test`.

But it means there is no problem with the executable at all. There must be something fishy with builtin shell `test`.

Anyway, I am never gonna name a file "test" again. Bad idea.

Thank you guys for your help.

So far I really like V.
I kept bouncing between Go and Rust for different things they had, and V feels like an interesting compromise.

**Comment by avitkauskas** [comment]
@mig-hub naming file `test.v` is perfectly ok, don't be sett-off by that strange case. It's definitelly has something to do with your zsh `test` function then. Are you entering `./test` in your terminal? If you rely on `.` being in the PATH, then it could be that it's later in the path than other `test` or that zsh command `test` takes precedence in some other way.

**Comment by medvednikov** [comment]
Indeed, if you run it with `./test`, it should work fine.
