### ISSUE TITLE
option smartcast

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#20405]
### Describe the feature

This will decrease json2's size, complexity and bugs by half

### Use Case

```v
struct Aa {
	a ?int
}

fn main() {
	mut a := ?int(2)
	// Could be any other syntax. The important is the ideia

	$if is_option(a) {
		if a != none { // smartcast
			assert a == int(2)
		}
	}

	name(Aa{a})
}

fn name[T](val T) {
	$for field in T.fields {
		// Could be any other syntax. The important is the ideia
		$if is_option(a) {
			if a != none { // smartcast
				assert a == int(2)
			}
		}
	}
}
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

latest

### Environment details (OS name and version, etc.)

Ubuntu
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
This already works, except that mutable one does not smartcasts.

```V
struct Aa {
	a ?int
}

fn main() {
	a := ?int(2)
	// Could be any other syntax. The important is the ideia

	$if a is $option {
		if a != none { // smartcast
			assert a == int(2)
		}
	}

	name(Aa{a})
}

fn name[T](val T) {
	$for field in T.fields {
		a := val.$(field.name)
		// Could be any other syntax. The important is the ideia
		$if a is $option {
			if a != none { // smartcast
				assert a == int(2)
			}
		}
	}
}
```
