### ISSUE TITLE
Weird `in` operator behaviour in REPL

### ISSUE THREAD

**Issue by wh-timme** [vlang/v#2042]
**V version:** 0.1.20 b6bb6a5
**OS:** Win 10 1809

**What did you do?**
in operator related REPL

**What did you expect to see?**
```
>>> 1 in [1,2]
true
>>> 2>1
true
>>> 1 in [1,2]
true
```
 
**What did you see instead?**
```
>>> 1 in [1,2]
>>> 2>1
true
>>> 1 in [1,2]
C:\Program Files\v\.vrepl_temp.v:2:2: unexpected token: `>`
```

**Comment by Henrixounez** [comment]
The problem about `1 in [1,2]` not printing anything is discussed here : 
https://github.com/vlang/v/issues/2041#issuecomment-538741221
