### ISSUE TITLE
Auto casting not performed on evaluation of u64 and int

### ISSUE THREAD

**Issue by wh-timme** [vlang/v#2043]
**V version:** 0.1.20 b6bb6a5
**OS:** Win 10 1809

**What did you do?**
Evaluation of large numbers
Result is consistent for both REPL and `v run`

**What did you expect to see?**
```
>>> 10000000000+1
10000000001
```
 
**What did you see instead?**
```
>>> 1000000000+1
1000000001
>>> 10000000000+10000000000
20000000000
>>> 10000000000+1
C:\Program Files\v\.vrepl_temp.v:3:22: expected type `u64`, but got `int`
```

**Comment by medvednikov** [comment]
Fixed.
