### ISSUE TITLE
Inconsistent behaviour for indexing char from string directly or a string type variable

### ISSUE THREAD

**Issue by wh-timme** [vlang/v#2044]
**V version:** 0.1.20 b6bb6a5
**OS:** Win 10 1809

**What did you do?**
char indexing from string
Result is consistent for both REPL and `v run`

**What did you expect to see?**
```
>>> print('ab'[1])
b
```
 
**What did you see instead?**
```
>>> miao:='ab'
>>> print(miao[1])
b
>>> print('ab'[1])
check()
next token = `number`
print_backtrace_skipping_top_frames is not implemented on this platform for now...

C:\Program Files\v\.vrepl.v:2:12: expected `)` but got `[`
```

**Comment by agrukuki** [comment]
What is 'ab'[1]
im confused

**Comment by Delta456** [comment]
@agrukuki `ab` is a string and [1] in `ab` tell the second character of the string ([0] would give out the first character).

**Comment by Ivo-Balbaert** [comment]
Both examples work on Windows 10, also in REPL: V 0.1.27 33a9822

print('ab'[1]) // => b
miao:='ab'
print(miao[1]) // => b
