### ISSUE TITLE
vweb plug-in development

### ISSUE THREAD

**Issue by Avey777** [vlang/v#20450]
### Describe the feature

Does vweb support plug-in development?
When developing many applications, using plug-in development can easily keep the basic system running normally.

### Use Case

For example, wordpress plug-in development

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

v4.3

### Environment details (OS name and version, etc.)

win
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by xiusin** [comment]
This should be language ability rather than module, just like the plugin of Go language, but it's not easy to use

**Comment by Casper64** [comment]
V supports struct embedding.

You can use composition to add more features from other external modules into your code.

**Comment by Casper64** [comment]
Also have a look at vweb's [controller functionality](https://github.com/vlang/v/blob/master/vlib/vweb/README.md#controllers)

You can use this functionality to include external vweb apps into your own app, for example an auth App could handle all routes starting with `/auth`. 

In`x.vweb`, the soon to be new version of vweb, it is possible to use controllers without any of the current restrictions.

**Comment by Avey777** [comment]
> Also have a look at vweb's [controller functionality](https://github.com/vlang/v/blob/master/vlib/vweb/README.md#controllers)
> 
> You can use this functionality to include external vweb apps into your own app, for example an auth App could handle all routes starting with `/auth`.
> 
> In`x.vweb`, the soon to be new version of vweb, it is possible to use controllers without any of the current restrictions.

Are you ready to replace vweb with x.vweb
