### ISSUE TITLE
Globals symbols are dropped (not exported) when -skip-unused is applied

### ISSUE THREAD

**Issue by odiroot** [vlang/v#20477]
**V doctor:**
```
V full version: V 0.4.4 ac2dcc2.4640627
OS: linux, "EndeavourOS Linux"
Processor: 12 cpus, 64bit, little endian, AMD Ryzen 5 PRO 4650U with Radeon Graphics

getwd: /home/odi/Temp/bugs
vexe: /home/odi/Repos/vlang/v
vexe mtime: 2024-01-10 21:23:26

vroot: OK, value: /home/odi/Repos/vlang
VMODULES: OK, value: /home/odi/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.43.0
Git vroot status: 0.4.4-11-g46406277
.git/config present: true

CC version: cc (GCC) 13.2.1 20230801
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

```

**What did you do?**
```
v bug_export.v -enable-globals -skip-unused -shared 
objdump -TC | grep ham
```

```v
const foo = "bar"

__global ham = foo + "qux"

```

**What did you expect to see?**

Symbol "ham" is exported in the shared library.

**What did you see instead?**

No symbol exported.

Running without `-skip-unused` or adding `@[markused]` helps. 
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by odiroot** [comment]
Maybe we could use explicitly exporting non-functions.

**Comment by JalonSolov** [comment]
Hmm... yes, if it's not referenced in the V code, it seems like it should be removed from the output.  So perhaps adding `@[exported]` (or something like that) attribute would be the way to make it stick around.

**Comment by shove70** [comment]
```v
const foo = "bar"

@[markused]
__global ham = foo + "qux"
```
V has a `markused` tag and can be exported.

```
[root@672dc452a866 123]# objdump -TC | grep ham
00000000002af0b0 g    DO .bss	0000000000000010              ham
```

**Comment by JalonSolov** [comment]
It works, but it "feels" wrong.  It's not actually _used_ in the code at all.  And may or may not be _used_ externally.  It just needs to be forced to be in the output.

**Comment by shove70** [comment]
hmm, I think that's what it's for: when we don't actually use it, but we need to explicitly export or output it.

However, in this case "markused" is not as intuitive as "exported", which people might be used to in other languages.

**Comment by odiroot** [comment]
> Someone just asked on discord about exporting a const, which would be similar to exporting a global, so I think we do need something to cover these cases.

It was actually me :) the creator of this issue. My general use case is to export an entry point via `extern const struct ...` (as opposed to just a function). Hence all my related chatter / raised issues.

**Comment by JalonSolov** [comment]
Ah, ok.  Didn't know, since the ids are different.
