### ISSUE TITLE
Single template for binary operator overloading

### ISSUE THREAD

**Issue by ntrel** [vlang/v#205]
Inspired by D's opBinary (but without the function overloading) - V could lower all binary operations for a struct to a single template. The template has a string value for the first argument, not a type. Here's an example for a struct representing a complex number:
```rust
struct Complex {
  real, imag int
}
fn opBinary<op string, B>(a Complex, b B) Complex {
  $if b !is Complex {
    // b is a real number e.g. int
    // Call opBinary<op, Complex>
    return a $op Complex{b,0}
  }
  return Complex{a.real $op b.real, a.imag $op b.imag}
}
```
The above code implements all binary operators for a struct at once. For Complex + Complex, V would call `opBinary<'+', Complex>`. $op turns the op string into a `+` operator token.

It also supports e.g. Complex + int, where the second argument is not of type Complex. This uses compile time `$if` to call opBinary with b converted to a Complex value.

To support e.g. int + Complex  in the same template, the function signature would look like:
```rust
fn Complex.opBinary<op string, A, B>(a A, b B) Complex
```
The `Complex.` prefix is necessary as either a or b may not be of Complex type (but they both can be too).

Edit: Use more V-like syntax, avoid copying b.

**Comment by ntrel** [comment]
Of course, complex multiplication is calculated differently:
```rust
$if op == '*' {panic('not implemented yet')}
```
Using compile time `if ... else` we can select different code for different operations.

**Comment by medvednikov** [comment]
In V, just like in Go and Python, operators require the same types on both sides.

You can't do `mystr + myint`, and so you also shouldn't be able to do `mycomplex + myint`.

As for the single template. Is this complexity worth it to just save several keystrokes? I much prefer

```
fn (a Complex) + (b Complex) Vec { return Complex{a.real + b.real, a.imag + b.imag} }
fn (a Complex) - (b Complex) Vec { return Complex{a.real - b.real, a.imag - b.imag} }
```

V's goal is to be a simple and readable language that can be learned in half an hour. Sometimes it means more typing.

**Comment by maddanio** [comment]
hmm, so you wont allow things linke matrix-vector mult or matrix/vector with scalar mult?
