### ISSUE TITLE
`@[deprecated]` attribute doesn't work on `const` entries.

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#20523]
### Describe the bug

Integer const values in the `math` module were supposed to be deprecated as of December 31st, 2023.  However, the deprecation warning is not being printed.

### Reproduction Steps

```v
import math
println(math.max_u32)
println(math.min_i8)
```

### Expected Behavior

2 deprecation warnings - one for each integer const from the math module.

### Current Behavior

No messages, code works as expected.

### Possible Solution

Make deprecation warnings work for `const`

### V version

V 0.4.4 9560d53

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.4 7008059.9560d53
OS: linux, "Manjaro Linux"
Processor: 32 cpus, 64bit, little endian, AMD Ryzen 9 7950X 16-Core Processor

getwd: /home/jalon
vexe: /home/jalon/git/v/v
vexe mtime: 2024-01-13 13:54:36

vroot: OK, value: /home/jalon/git/v
VMODULES: OK, value: /home/jalon/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.43.0
Git vroot status: 0.4.4-36-g9560d535
.git/config present: true

CC version: cc (GCC) 13.2.1 20230801
thirdparty/tcc status: json2_perf 12f392c3
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by shove70** [comment]
👍  Yes, I was working on a fix, but found another issue:


```v
@[deprecated: 'use built-in constants instead (e.g. min_i8 instead of math.min_i8)']
@[deprecated_after: '2023-12-31']
pub const min_i8 = i8(-128)
pub const max_i8 = i8(127)
pub const min_i16 = i16(-32768)
pub const max_i16 = i16(32767)
pub const min_i32 = i32(-2147483648)
pub const max_i32 = i32(2147483647)
```

Because we removed the const group, the deprecating property now only applies to the first line of definition

**Comment by JalonSolov** [comment]
Notice I used the first const in my example.  I didn't get a message for it, either.

**Comment by shove70** [comment]
I know, I already fixed this locally, but found another issue mentioned above. It might need to be discussed

**Comment by shove70** [comment]
```v
@[deprecated: 'use built-in constants instead (e.g. min_i8 instead of math.min_i8)']
@[deprecated_after: '2023-12-31']
pub const min_i8 = i8(-128)
pub const max_i8 = i8(127)
pub const min_i16 = i16(-32768)
pub const max_i16 = i16(32767)
                                  // <------------  It seems good to use "blank line" as a block for "deprecated"
pub const min_i32 = i32(-2147483648)
pub const max_i32 = i32(2147483647)
```
