### ISSUE TITLE
Picoev weird behave

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#20555]
### Describe the bug

After run `v -prod -cc gcc crun pico` and open `GET /` on browser
![image](https://github.com/vlang/v/assets/63821277/e5b5f448-348a-4f7d-affd-bd835e137896)

After  run `v -prod -cc gcc crun pico` and open `GET /` on browser-> close the server `(Ctrl+c)` -> Init aplication again
![Uploading image.png…]()

### Reproduction Steps

```v
import picoev
import picohttpparser

fn callback(data voidptr, req picohttpparser.Request, mut res picohttpparser.Response) {
	if req.method == 'GET' {
		if req.path == '/' {
			res.http_ok()
		} else if req.path.starts_with('/user/') {
			res.http_ok()
			id := req.path[6..]
			res.body(id)
		}
	}
	if req.method == 'POST' {
		if req.path == '/user' {
			res.http_ok()
		}
	}
	res.end()
}

fn main() {
	println('Starting...')
	mut server := picoev.new(port: 3000, cb: callback)
	server.serve()
}
```

### Expected Behavior

No error, no delay

### Current Behavior

errors, delay

### V version

V 0.4.4 3a66355

### Environment details (OS name and version, etc.)

Ubuntu
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Casper64** [comment]
This error usually occurs when a browser extension, particularly in chrome, doesn't properly handle async responses.
When you stop the server, the extension receives an unexpected response and shows an error in the console.

The error should dissappear if you disable your extensions/maybe use another browser. Other than that the error can be ignored.

**Comment by enghitalo** [comment]
> This error usually occurs when a browser extension, particularly in chrome, doesn't properly handle async responses.
> When you stop the server, the extension receives an unexpected response and shows an error in the console.
> 
> The error should dissappear if you disable your extensions/maybe use another browser. Other than that the error can be ignored.

The second image was more important and not related to the browser, I guess. 😩 I'll try to reproduce it through the postman.
