### ISSUE TITLE
vpm.exe flagged as malware by Windows Defender

### ISSUE THREAD

**Issue by jarildson** [vlang/v#20560]
### Describe the bug

Not quite a bug, but it is an issue. Windows Defender and a couple AV's on virustotal are marking vpm.exe as malware. https://www.virustotal.com/gui/file/74c31e427d0023556264d13a3aa2093cf10f9ee2557488b72e1ad08a16a5013c/behavior

![c0862ae841ce5bdc367d32847338e6a3](https://github.com/vlang/v/assets/9122386/11398893-3f23-4100-a905-6d4d199e71a7)

This is after running the below command in VSCode's terminal on Windows 10:
v install MCausc78.discord

### Reproduction Steps

run in a terminal in new project on Windows 10:
`v install MCausc78.discord`

### Expected Behavior

Installs vpm package

### Current Behavior

windows defender quarantines vpm.exe

### V version

Current V version: V 0.4.4 afd74ad

### Environment details (OS name and version, etc.)

V full version: V 0.4.4 8d5f95d.afd74ad
OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 8 cpus, 64bit, little endian,
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
Yes, and it likely will until we start digitally signing the file.  In the meantime, you should be able to tell Defender to exempt files under the V install dir.

**Comment by MCausc78** [comment]
I think it flags `vpm` as malware since it downloads thing that interacts with Discord, and attackers actively use Discord webhooks for receiving user data. for now just tell to Defender ignore this.
