### ISSUE TITLE
Support installing to home directory as normal user

### ISSUE THREAD

**Issue by nordlow** [vlang/v#20578]
### Describe the feature

Currently there's no way to install vlang other than `/usr/local/`. For instance, the user might want to install to `~/local/vlang/bin/`.

### Use Case

Installing to home is safer.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

master

### Environment details (OS name and version, etc.)

Ubuntu 22.04.
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
I have no idea how you're installing V, but there is _no_ official package for V other than the zip files on github, which you can extract wherever you wish.

Even then, the preferred way to install V is to install by cloning the repo and building it yourself.  You can, of course, make that clone wherever you wish.  See https://github.com/vlang/v#installing-v-from-source

The only thing that is put in /usr/local/bin is a symlink to the V executable when you run `sudo v symlink`.

**Comment by nordlow** [comment]
> I have no idea how you're installing V, but there is _no_ official package for V other than the zip files on github, which you can extract wherever you wish.
> 
> Even then, the preferred way to install V is to install by cloning the repo and building it yourself. You can, of course, make that clone wherever you wish. See https://github.com/vlang/v#installing-v-from-source
> 
> The only thing that is put in /usr/local/bin is a symlink to the V executable when you run `sudo v symlink`.

I just want to try out the v compiler at maximum speed by compiling with -prod switch and install it somewhere in my home directory.

**Comment by JalonSolov** [comment]
If you clone the repo to your home directory, and build V there, you're done.  :-)

Running `sudo v symlink` just makes V available everywhere on the system, without having to type the full path to it every time.

**Comment by nacho00112** [comment]
Do this:
```bash
git clone https://github.com/vlang/v ~/.v
cd ~/.v; make
echo 'PATH+=":$HOME/.v"' >> ~/.bashrc
source ~/.bashrc
```
You'll get v installed on `~/.v`

**Comment by cideric** [comment]
Yeah, I had to install it that way because I don't have access to `/usr/local/bin`

**Comment by nacho00112** [comment]
Yeah, I had to install it that way because I don't have access to `/usr/local/bin`

**Comment by spytheman** [comment]
You can just make a symlink manually to the executable to a folder already on your PATH, or set your PATH to the folder that contains the v executable.

The v executable itself, does not care where it is placed.
