### ISSUE TITLE
make `in` keyword works with enum

### ISSUE THREAD

**Issue by bokunodev** [vlang/v#20589]
### Describe the feature

literally, what the tittle says.
make `in` keyword works with `enum` without intermediate `array` or `map`.
`in` currently only works with `array` and `map`.

### Use Case

i stumble upon this seemingly simple problem.

how to check if a value that come from outside world is part of enum?
```v
module main

struct MyStruct {
pub mut:
	value MyEnum
}

enum MyEnum {
	ab = 1
	cd = 2
}

fn mani() {
	val := MyStruct{}

	// unsafe block, simulating decoding value from json, protobuf, dns query or else.
	unsafe {
		val.value = 99 // invalid value
	}
	//
	// now i want to check if `val`  has a valid value
	//
	// does not work, `in` only woks with array and map
	println(val.value in MyEnum)

	// this works. but why do i have to specify set of valid values? `MyEnum` already has that.
	println(val.value in [MyEnum.ab, MyEnum.cd])

	// does not work, exhaustive match does not allow `else`
	ok := match val.value {
		.ab {
			true
		}
		.cd {
			true
		}
		else {
			false
		}
	}
	println(ok)
}
```

### Proposed Solution

make `in`  works with enum

### Other Information

even if `exhaustive match` does allow for `else` branch, `in` would still be cleaner and shorter.
i did asked this question in discord and verify if this was real problem and its ok to file an issue.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### Version used

V 0.4.4 afd74ad

### Environment details (OS name and version, etc.)

V full version: V 0.4.4 afd74ad
OS: linux, Linux version 6.7.0-arch3-1 (linux@archlinux) (gcc (GCC) 13.2.1 20230801, GNU ld (GNU Binutils) 2.41.0) #1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz

getwd: /home/guest/Documents/v-project/dnse
vexe: /home/guest/Documents/vlang/v
vexe mtime: 2024-01-17 02:17:37

vroot: OK, value: /home/guest/Documents/vlang
VMODULES: OK, value: /home/guest/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.43.0
Git vroot status: weekly.2024.03-4-gafd74ad6-dirty (14 commit(s) behind V master)
.git/config present: true

CC version: cc (GCC) 13.2.1 20230801
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
With the new `.from()` method, your code can now be
```v
val := MyEnum.from(value_from_json) or { println('not a valid enum') }
```
