### ISSUE TITLE
Disable compile time debug statements when compiling for production

### ISSUE THREAD

**Issue by smartiniOnGitHub** [vlang/v#20587]
### Describe the feature

To avoid real applications to be stopped by compile time debug statement (`$dbg`, introduced by [v: $dbg statement - native V debugger REPL #20533 ](https://github.com/vlang/v/pull/20533) ), please evaluate to disable it by default (or not define it) when compiling the code in production mode, using related compiler flag.
In this way even `$dbg` statements present in code or in libraries won't affect code running outside development phases.

### Use Case

When developing/debugging code, this feature could be a great help.
But when when running code in a real server (so compiled with the production flag) I think it would be a risk to have some portion of code (maybe from a library or from some debug code not cleaned) that could interrupt a running application.

### Proposed Solution

Disable or empty the definition of the `$dbg` statement when compile with the production enabled.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.4.4 5310c10 (2024-01-19)

### Environment details (OS name and version, etc.)

V full version: V 0.4.4 0a89f30.5310c10
OS: linux, Ubuntu 22.04.3 LTS
Processor: 8 cpus, 64bit, little endian, 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

getwd: /home/sandro/dev
vexe: /opt/vlang_v/v
vexe mtime: 2024-01-19 14:46:10

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
My opinion:  No, it shouldn't be automatically disabled, for 2 reasons.

1. You may want to debug the code after compiling with `-prod`, especially if there's a bug that only shows up when compiled with `-prod`.

2. It is an "invasive" statement, which is actually added to the source.  It should be removed by the developer when you have finished debugging, not left around to bother you when you're compiling without `-prod`.

**Comment by spytheman** [comment]
`$dbg` is not an assertion.

**Comment by smartiniOnGitHub** [comment]
Hi all and thanks for the feedback. 
My concern is for example to have such calls in external code that you don't control, anyway don't think it's a big deal now, I understand your reasons, thanks the same. Bye
