### ISSUE TITLE
cgen.v:5862:2: error: expression evaluated but not used

### ISSUE THREAD

**Issue by Lycs-D** [vlang/v#20606]
### Describe the bug

![c1834c09-83d3-495a-a609-bf96551d0c2b](https://github.com/vlang/v/assets/139197676/c1834c09-83d3-495a-a609-bf96551d0c2b)

### Reproduction Steps

```
module main

import v.ast
import v.parser
import v.pref
import os

fn main() {
	file := os.join_path(@VEXEROOT, 'vlib/v/gen/c/cgen.v')
	table:= ast.new_table()
	pref_:= pref.new_preferences()
	dump(parser.parse_file(file, table, .parse_comments, pref_))
}
```

### Expected Behavior

no error

### Current Behavior

error: expression evaluated but not used

### V version

V 0.4.4 df3591c

### Environment details (OS name and version, etc.)

V full version: V 0.4.4 d744314.df3591c
OS: windows, Microsoft Windows Server 2022 Datacenter v26010 64 λ
Processor: 8 cpus, 64bit, little endian
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
`cmd/tools/measure/parser_speed.v` uses:

```v
    mut pref_ := pref.new_preferences()
    pref_.is_fmt = true
    pref_.skip_warnings = true
    pref_.output_mode = .silent
```

**Comment by spytheman** [comment]
`is_fmt = true` in particular, makes the parser a lot more relaxed

**Comment by StunxFS** [comment]
Wouldn't it be nice to detect that in the checker?

**Comment by spytheman** [comment]
> Wouldn't it be nice to detect that in the checker?

Yes, it would be nicer, for that error to be in the checker, instead of inside the parser. The current parser has several such places, where ideally, it should not error, but instead the checker should.
