### ISSUE TITLE
cgen error for ` _ = none`

### ISSUE THREAD

**Issue by nacho00112** [vlang/v#20645]
```bash
v run a.v
```
```
==================
/tmp/v_2625/a.01HMWV3D4QDHES1C1B00P00B2E.tmp.c:12858: error: '{' expected (got ";")
...
==================
(Use `v -cg` to print the entire error message)                    
builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```
```bash
cat a.v
```
```v
fn x() ?bool {
        return none
}                                                                  
_ = x() or {
        _ = none
        true
}
```
I have no idea what's happening here, I was experimenting as I'm still learning the language and then it asked me to report.

and I want to leverage this opportunity to ask an off-topic little doubt,
in structs, what `__global:` allows that `pub mut:` doesn't?
I tried them in various forms and both worked fine,
the docs talks about "parent module only" stuff with `pub mut:` but I don't get it they both work no matter what I try.
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by pierrec** [comment]
The offending line is `_ = none` in the or block, removing it fixes the bug.

```
fn x() ?bool {
        return none
}                                                                  
_ = x() or {
        true
}
```
