### ISSUE TITLE
Why using github? It is a proprietary software. 

### ISSUE THREAD

**Issue by lithic** [vlang/v#2064]

**Comment by influx6** [comment]
@lithic Only you care, so why disturb another if he wishes to use such?

**Comment by lithic** [comment]
@influx6 Don't misbehave

**Comment by donnisnoni95** [comment]
Suing Gitlab instead or ??

**Comment by medvednikov** [comment]
Git is decentralized, any hosting can be used, migrating is always easy.

GitHub is a good platform that makes it easy to follow the project and contribute to it, I see no reason to switch just because it's proprietary.
