### ISSUE TITLE
$dbg memory leak

### ISSUE THREAD

**Issue by Eliyaan** [vlang/v#20689]
### Describe the bug

When using $dbg and typing `mem` repeatedly the number grows up.

### Reproduction Steps

```v
fn main() {
    mut a := 3
    $dbg
}
```
then typing mem a few times

### Expected Behavior

the memory to stay constant

### Current Behavior

![image](https://github.com/vlang/v/assets/103932369/3664b9c6-4b82-40fa-9b27-651b04596746)
![image](https://github.com/vlang/v/assets/103932369/8df8b60b-ace0-4140-8320-5b7ee7e49214)
![image](https://github.com/vlang/v/assets/103932369/64f2d0f1-864a-423e-ab70-457b7cc5edbf)

### V version

 V 0.4.4 804a7bd

### Environment details (OS name and version, etc.)

V full version: V 0.4.4 536bf21.804a7bd
OS: windows, Microsoft Windows 10 ducation v19045 64 bits
Processor: 4 cpus, 64bit, little endian, 

getwd: C:\Users\PACHECON\_cv\tests
vexe: C:\Users\PACHECON\v\v.exe
vexe mtime: 2024-01-29 21:25:25

vroot: OK, value: C:\Users\PACHECON\v
VMODULES: OK, value: C:\Users\PACHECON\.vmodules
VTMP: OK, value: C:\Users\PACHECON\AppData\Local\Temp\v_0

Git version: git version 2.42.0.windows.2
Git vroot status: weekly.2024.04-36-g804a7bdd
.git/config present: true

CC version: Error: 'cc' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

thirdparty/tcc status: thirdparty-windows-amd64 e90c2620
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
This is related to memory usage on the debug session itself.

**Comment by spytheman** [comment]
That is not a memory leak, it is a consequence of how the GC works, and that the $dbg repl is just normal V code, also running in the same process, and in the same thread, that executed the `$dbg` statement.

Consider the following program:
```v
import time
import log

fn main() {
    spawn fn() {
        mut l := log.Log{}
        l.set_level(.info)
        l.set_full_logpath('./info.log')
        for i in 0..9999 {
            l.info('i: ${i}')                            
            time.sleep(100*time.millisecond)
        }
    }()
    for x in 0..10 {
        println(x)
        $dbg;
        time.sleep(10*time.millisecond)
    }
    println('done')
}
```
where the main thread is running the $dbg repl, but there is also a background one, that continues to do string interpolations, and to write to a log file, both of which consume memory.

The GC will at some point do a full garbage collection, and free some of it, and the reported memory usage by `mem` will drop.
