### ISSUE TITLE
The JS backend produces a different output for `./v -b js run vlib/v/gen/js/tests/testdata/u32.v`, compared to just `./v run vlib/v/gen/js/tests/testdata/u32.v`

### ISSUE THREAD

**Issue by spytheman** [vlang/v#20686]
**V doctor:**
```
V full version: V 0.4.4 4163faf.aec2a15
OS: linux, Ubuntu 20.04.6 LTS
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i3-3225 CPU @ 3.30GHz

getwd: /space/v/oo
vexe: /space/v/oo/v
vexe mtime: 2024-01-28 17:34:04

vroot: OK, value: /space/v/oo
VMODULES: OK, value: /home/delian/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.42.0
Git vroot status: weekly.2024.04-29-ga327d49e
.git/config present: true

CC version: cc (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg vlib/v/gen/js/tests/testdata/u32.v`
```v
fn main() {
	println(u32(0xFFFFFFFF))
	println(u32(4294967295) + 1)

	println(u32(42) == u32(42))
	println(u32(100000) * 256)
}

```

**What did you expect to see?**

Both these commands should produce the same exact output:
`./v -b c  run vlib/v/gen/js/tests/testdata/u32.v`
`./v -b js run vlib/v/gen/js/tests/testdata/u32.v`

**What did you see instead?**

`./v -b c run vlib/v/gen/js/tests/testdata/u32.v` produces correctly:
```
4294967295
0
true
25600000
```
but:
`./v -b js run vlib/v/gen/js/tests/testdata/u32.v` produces this (note the first -1):
```
-1
0
true
25600000
```

Note: this was not detected and it regressed before, since `vlib/v/gen/js/program_test.v` was marked as a flaky test, and its failures in the CI were ignored.
Now the underlying reason for the flakyness of that test is reduced, and the marking is gone.
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
@GGRei I can not assign it to you for some reason 🤔 .
![image](https://github.com/vlang/v/assets/26967/e245bfc7-7188-4b16-aaee-c0e2cb6d8d22)

**Comment by MCausc78** [comment]
> @GGRei I can not assign it to you for some reason 🤔 . ![image](https://private-user-images.githubusercontent.com/26967/300282858-e245bfc7-7188-4b16-aaee-c0e2cb6d8d22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NjUzNDgsIm5iZiI6MTcwNjQ2NTA0OCwicGF0aCI6Ii8yNjk2Ny8zMDAyODI4NTgtZTI0NWJmYzctNzE4OC00YjE2LWFhZWUtYzBlMmNiNmQ4ZDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDE4MDQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkODFmZTIxMTA2M2UzNTNkYzEyZDQwYzkzMzJjMGQ3ODE5YmM4ZTVjMDY0NDlkMmIzMTczZjk0MDM4MWRhNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3U_gmVIO26XnhI1Y98AcqG5ORKQVEj3QEpa3EbUq5K4)

try typing just `GGRei`

**Comment by spytheman** [comment]
I did, github can not find it either 🤔 .

**Comment by spytheman** [comment]
It offers both me and you, and I can type for example shove, and github finds him too, but not GGRei.

**Comment by spytheman** [comment]
![image](https://github.com/vlang/v/assets/26967/cbb39b56-4dab-479e-a9d3-5d4e33c7e145)

**Comment by felipensp** [comment]
> I did, github can not find it either 🤔 .

This also happened to @enghitalo another day.
