### ISSUE TITLE
V compiler can't compiler raylib wrapper if i used os library

### ISSUE THREAD

**Issue by AmeerAtia** [vlang/v#20684]
### Describe the bug

when i used [irishgreencitrus/raylib.v](https://github.com/irishgreencitrus/raylib.v) it works without any problems but when i use `import os` or `import walkingdevel.vxml as xml` (vxml uses os lib also) my code doesn't work
and when i tried to create a new small wrap for raylib i got the same error

### Reproduction Steps

```v
module main

#include "@VMODROOT/src/raylib/src/raylib.h"

fn C.InitWindow(int, int, &Char)

@[params]
pub struct InitWindowParams {
pub mut:
	width int @[required]
	height int @[required]
	title string @[required]
}

fn init_window(params InitWindowParams) { C.InitWindow(params.width, params.height, params.title.str) }

fn main() {
	init_window(width: 600, height: 400, title: 'hiiiiii')
}
```
or use
```v
module main

import os
import irishgreencitrus.raylibv as r

fn main() {
	r.init_window(600, 400, 'hiii'.str)
	r.set_target_fps(60)
	for !r.window_should_close() {
		r.begin_drawing()
		r.clear_background(r.Color{ r: 245, g: 245, b: 245, a: 255 })
		r.draw_text('Congrats! You created your first window in V!'.str, 190, 200, 20,
			r.Color{
			r: 0
			g: 0
			b: 0
			a: 255
		})
		r.end_drawing()
	}
	r.close_window()
}
```

### Expected Behavior

i think v should catch it before it goes to the C compiler and i should be able to use raylib with any another library

### Current Behavior

i get that error in cmd
```cmd
PS D:\Projects\V> v run d:\Projects\V\dragon.v\src
==================
In file included from C:\Users\ahmad\AppData\Local\Temp\v_0\src.01HN7Y45Q323FX9SCJHTX87CKB.tmp.c:748:
D:\Projects\V\dragon.v/src/raylib/src/raylib.h:237:3: error: 'Rectangle' redeclared as different kind of symbol
  237 | } Rectangle;
      |   ^~~~~~~~~
In file included from C:/apps/mingw32/i686-w64-mingw32/include/windows.h:71,
                 from C:\Users\ahmad\AppData\Local\Temp\v_0\src.01HN7Y45Q323FX9SCJHTX87CKB.tmp.c:507:
C:/apps/mingw32/i686-w64-mingw32/include/wingdi.h:3158:28: note: previous declaration of 'Rectangle' with type 'WINBOOL(struct HDC__ *, int,  int,  int,  int)' {aka 'int(struct HDC__ *, int,  int,  int,  int)'}
 3158 |   WINGDIAPI WINBOOL WINAPI Rectangle(HDC hdc,int left,int top,int right,int bottom);
      |                            ^~~~~~~~~
D:\Projects\V\dragon.v/src/raylib/src/raylib.h:924:12: error: conflicting types for 'CloseWindow'; have 'void(void)'
  924 | RLAPI void CloseWindow(void);                                     // Close window and unload OpenGL context
      |            ^~~~~~~~~~~
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

PS D:\Projects\V>
```

### V version

V full version: V 0.4.4 4163faf.f79dd79

### Environment details (OS name and version, etc.)

OS: windows, Microsoft Windows 11 Home Single Language v22631 64-bit
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
See https://github.com/raysan5/raylib/issues/1217 .
The TLDR is that raysan does not want to change his API and add prefixes, so it will continue to clash. The workaround is to #define WIN32_LEAN_AND_MEAN, before #include <windows.h>
which afaik https://github.com/irishgreencitrus/raylib.v does in https://github.com/irishgreencitrus/raylib.v/blob/2ef075b967ead252501de2ae66194dfbbaf6c439/include/pre.h#L4 , which limits the declarations that windows.h makes

I think that there is no way to solve it in the general case, and it is not V's problem to do it. It can be just worked around.
