### ISSUE TITLE
V can't compile n..n (V can't compile this program, but it should.)

### ISSUE THREAD

**Issue by BlueSlimee** [vlang/v#207]
Hi!
I was trying out V, and I've found a bug.

V can't compile the following code, but it should (I think):
```go
fn main() {
	areas := 1..2
        println(areas)
}
```

**Comment by ntrel** [comment]
> areas := 1..2

What would that mean?

**Comment by medvednikov** [comment]
1..2 is [1]

It was fixed today, playground is down at the moment.

**Comment by ntrel** [comment]
So 0..10000 allocates an array with 10000 elements, each one just an increment of the previous element. That doesn't seem like a good use of memory to me, it would be slow. Why would a programmer want such an array? I would just define it as a special form of `for` `in`.

**Comment by medvednikov** [comment]
If you want an array with 100k elements, you create it. If you don't, you don't.

When you do `for i in 1..100k`, V optimizes it to `for i:=1;i<100k;i++`.

**Comment by ntrel** [comment]
> If you want an array with 100k elements, you create it

Yes, with `[0; 100000]` ;-)

> 1..2 is [1]

Are there any other languages that support this feature?

**Comment by BlueSlimee** [comment]
> Are there any other languages that support this feature?
Kotlin.

**Comment by ntrel** [comment]
&gt; Kotlin

Are you sure that kotlin allocates a whole array for range literals? I don't think it does. It's very rare that a programmer would want that. Instead, it should use an iterator that does no heap allocations but calculates the next element as required.

**Comment by medvednikov** [comment]
You are right, these are progressions/iterators in Kotlin and Rust.

I feel like I should either remove this features completely or only allow it in `for i in start..end {`.

**Comment by medvednikov** [comment]
`..` is now only allowed in for loops to avoid confusion and make the language simpler.
