### ISSUE TITLE
C error / UB when smartcasting a sumtype to a reference of a summed type

### ISSUE THREAD

**Issue by zeozeozeo** [vlang/v#20703]
**V doctor:**
```
V full version: V 0.4.4 5306469.fb0efc0
OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 20 cpus, 64bit, little endian, 

getwd: C:\Users\user\Desktop\Code\leaflang
vexe: C:\Users\user\Desktop\Code\v\v.exe
vexe mtime: 2024-02-01 19:06:51

vroot: OK, value: C:\Users\user\Desktop\Code\v
VMODULES: OK, value: C:\Users\user\.vmodules
VTMP: OK, value: C:\Users\user\AppData\Local\Temp\v_0

Git version: git version 2.42.0.windows.1
Git vroot status: weekly.2024.05-11-gfb0efc0a
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,

operable program or batch file.


thirdparty/tcc status: thirdparty-windows-amd64 a39eb79b

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg test.v`
```v
struct Foo {
	foo i32
}

struct Bar {
	bar f32
}

type Foobar = Foo | Bar

fn match_sum(sum Foobar) {
	match sum {
		Foo {
			sum_foo(sum)
		}
		Bar {
			sum_bar(sum)
		}
	}
}

fn sum_foo(i &Foo) {
	// if Foo were a primitive type (e.g. int), this would be UB (i think?)
	println('foo: ${i}')
}

fn sum_bar(i Bar) {
	println('bar: ${i}')
}

fn main() {
	match_sum(Foo{foo: 5})
}

```

**What did you expect to see?**

Foo printed to stdout

**What did you see instead?**
```
==================
C:/Users/user/AppData/Local/Temp/v_0/test.01HNK135B307WA0WA0D6CDH9GB.tmp.c:6929: warning: implicit declaration of function 'tcc_backtrace'
C:/Users/user/AppData/Local/Temp/v_0/test.01HNK135B307WA0WA0D6CDH9GB.tmp.c:13073: error: cannot convert 'struct main__Foo' to 'struct main__Foo *'
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by GGRei** [comment]
@felipensp In the provided example, during the genC in the context of unions concerning sum types, there's an unnecessary dereference in the call to the function `main__sum_foo(main__Foo* i)`, whereas in the "match", the function call becomes `main__sum_foo((*sum._main__Foo))`.

The signature of this particular function parameter expects a pointer, not a value, which isn't considered during gen. 

I exploring the genC pipeline, unfortunately, even in functions `like fn_call` -> `call_args` -> `ref_or_deref_arg` -> `expr_with_cast` -> `expr` -> `ident`, but I'm not sure this is the right place to check the function signature

I'm not sure at which point in the genC pipeline to intervene, as there could be several ways to approach this problem, but some may be more relevant than others. 

Perhaps it's even necessary to look further upstream in the pipeline in functions like `fn_decl_params`? or in `call_args` by including a check related to the function's signature, 

I don't have enough experience to determine the best place for fix this.

I hope it can help
