### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by agrukuki** [vlang/v#2071]
**V version: Latest I think** 
**OS: Windows 10** 

**What did you do?**
I Followed the steps on https://vlang.io/
sadly, it failed at "make" step

**What did you expect to see?**
I expected to see the build success.
 
**What did you see instead?**
*Image*
![image](https://user-images.githubusercontent.com/20241189/65389561-c8268c80-dd81-11e9-8f6b-08c42be26049.png)

**Comment by medvednikov** [comment]
`gcc -v`

**Comment by joe-conigliaro** [comment]
@agrukuki can you paste the output of `gcc -v` as @medvednikov suggested?

I think you need to upgrade gcc, you should upgrade all your packages (mingw64 or msys, whichever you are using).

**Comment by vitalyster** [comment]
Should be fixed there - https://github.com/vlang/v/pull/2080
However it may still fail if they have no `_setmode` in msvcrt imports

**Comment by medvednikov** [comment]
@agrukuki you are using mingw, not mingw-w64 most likely. Only the latter is supported.

**Comment by dumblob** [comment]
As there seem to be more and more bug reports with unsupported tooling, it would make sense to make `make` first check preconditions (i.e. which gcc it is, which gcc version, which mingw, etc.) and spit out a more readable message instead of the suggestion to report such issue.

**Comment by vitalyster** [comment]
@dumblob mingw-w64 have gcc 8.1, while mingw (from mingw.org) have 8.2 with outdated win32api headers/library definitions. So it is not clear how to detect outdated distribution

**Comment by dumblob** [comment]
@vitalyster `gcc -v`

**Comment by medvednikov** [comment]
@dumblob you are right, mingw needs to be detected.

**Comment by joe-conigliaro** [comment]
mingw hasn't been updates in years as far as i know.
Everyone should be using Mingw64/msys2
