### ISSUE TITLE
C error when accessing other consts' fields in a const fixed array initializer

### ISSUE THREAD

**Issue by zeozeozeo** [vlang/v#20764]
**V doctor:**
```
V full version: V 0.4.4 5306469.f603035
OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 20 cpus, 64bit, little endian, 

getwd: C:\Users\user\Desktop\Code\leaflang
vexe: C:\Users\user\Desktop\Code\v\v.exe
vexe mtime: 2024-02-09 11:28:16

vroot: OK, value: C:\Users\user\Desktop\Code\v
VMODULES: OK, value: C:\Users\user\.vmodules
VTMP: OK, value: C:\Users\user\AppData\Local\Temp\v_0

Git version: git version 2.42.0.windows.1
Git vroot status: weekly.2024.06-25-gf6030357
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,

operable program or batch file.


thirdparty/tcc status: thirdparty-windows-amd64 a39eb79b

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg test.v`
```v
struct Foo {
	index int
}

const foo5 = Foo{
	index: 5
}
const foo2 = Foo{
	index: 2
}

const foos = [foo5.index, foo2.index]! // removing ! fixes the issue

fn main() {
	println(foos)
}

```

**What did you expect to see?**

[5, 2] printed to stdout or compile-time error

**What did you see instead?**
```
==================
C:/Users/user/AppData/Local/Temp/v_0/test.01HP6T0MTEKEA3656WHV9X68WD.tmp.c:493: warning: WINVER redefined
C:/Users/user/AppData/Local/Temp/v_0/test.01HP6T0MTEKEA3656WHV9X68WD.tmp.c:2091: error: initializer element is not constant
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
This is not possible due C compilers.

```C
main__Foo _const_main__foo5; // inited later
main__Foo _const_main__foo2; // inited later
Array_fixed_int_2 _const_main__foos = {_const_main__foo5.index, _const_main__foo2.index}; // fixed array const
```

.index is not even initialized for such operation. We should added a checker error.

**Comment by MCausc78** [comment]
> This is not possible due C compilers.
> 
> ```c
> main__Foo _const_main__foo5; // inited later
> main__Foo _const_main__foo2; // inited later
> Array_fixed_int_2 _const_main__foos = {_const_main__foo5.index, _const_main__foo2.index}; // fixed array const
> ```
> 
> .index is not even initialized for such operation. We should added a checker error.

What about initializing it in `_vinit`?

**Comment by felipensp** [comment]
> > This is not possible due C compilers.
> > ```c
> > main__Foo _const_main__foo5; // inited later
> > main__Foo _const_main__foo2; // inited later
> > Array_fixed_int_2 _const_main__foos = {_const_main__foo5.index, _const_main__foo2.index}; // fixed array const
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > .index is not even initialized for such operation. We should added a checker error.
> 
> What about initializing it in `_vinit`?

Hmm yeah. Maybe could be a solution, we must check It. Thanks.
