### ISSUE TITLE
v remove fails to remove module properly.

### ISSUE THREAD

**Issue by hungrybluedev** [vlang/v#20775]
### Describe the bug

When using `v remove xlsx` to remove this module: https://github.com/hungrybluedev/xlsx, the removal apparently failed and did not provide any additional information. This was causing local test failures while I was trying to develop the xlsx module.

### Reproduction Steps

1. Install xlsx using `v install https://github.com/hungrybluedev/xlsx`
2. Clone https://github.com/hungrybluedev/xlsx in a separate directory. Make changes.
3. Try to run unit tests. They should fail.
4. Try to remove xlsx using `v remove xlsx`.
5. Notice that `xlsx` still exists.

### Expected Behavior

The xlsx module should have been deleted from the module directory. When removal failed, it should have informed that no module was found or removal failed with an error.

### Current Behavior

The removal exits normally with no error messages and the xlsx module is not removed.

### Additional Information/Context

Sample run from when it failed for me:

```
PS C:\Development\Repositories\VProjects\FileFormats\xlsx> v remove xlsx
Removing module "xlsx" ...
PS C:\Development\Repositories\VProjects\FileFormats\xlsx> v test .
---- Testing... --------------------------------------------------------------------------------------------------------------------------------------------
 OK    [1/5] C:  441.6 ms, R:    58.862 ms C:/Development/Repositories/VProjects/FileFormats/xlsx/src/location_test.v
 FAIL  [2/5] C: 1056.8 ms, R:     0.000 ms C:/Development/Repositories/VProjects/FileFormats/xlsx/spec/02_single_column/column_test.v
>> compilation failed:
spec/02_single_column/column_test.v:1:1: builder error: cannot import module "xlsx" (no .v files in "C:\Development\Dependencies\vmodules\xlsx")
    1 | import xlsx
      | ~~~~~~~~~~~
    2 | import os
    3 |

 FAIL  [3/5] C: 1055.7 ms, R:     0.000 ms C:/Development/Repositories/VProjects/FileFormats/xlsx/spec/04_1MB_file/one_mb_test.v
>> compilation failed:
spec/04_1MB_file/one_mb_test.v:1:1: builder error: cannot import module "xlsx" (no .v files in "C:\Development\Dependencies\vmodules\xlsx")
    1 | import xlsx { Location }
      | ~~~~~~~~~~~~~~~~~~~~~~~~
    2 | import os
    3 |

 FAIL  [4/5] C: 1061.0 ms, R:     0.000 ms C:/Development/Repositories/VProjects/FileFormats/xlsx/spec/01_empty_file/empty_test.v
>> compilation failed:
spec/01_empty_file/empty_test.v:1:1: builder error: cannot import module "xlsx" (no .v files in "C:\Development\Dependencies\vmodules\xlsx")
    1 | import xlsx
      | ~~~~~~~~~~~
    2 | import os
    3 |

 FAIL  [5/5] C: 1153.8 ms, R:     0.000 ms C:/Development/Repositories/VProjects/FileFormats/xlsx/spec/03_simple_table/table_test.v
>> compilation failed:
spec/03_simple_table/table_test.v:1:1: builder error: cannot import module "xlsx" (no .v files in "C:\Development\Dependencies\vmodules\xlsx")
    1 | import xlsx { Location }
      | ~~~~~~~~~~~~~~~~~~~~~~~~
    2 | import os
    3 |

------------------------------------------------------------------------------------------------------------------------------------------------------------
Failed command 1:    "C:\Development\Dependencies\v-main\v.exe" -skip-running   -o "C:\Development\scratch\tmp\tsession_22e0_73664400\01HP9BR2JJ52PABF5KHEKGSXDR\column_test.exe" "C:\Development\Repositories\VProjects\FileFormats\xlsx\spec\02_single_column\column_test.v"
Failed command 2:    "C:\Development\Dependencies\v-main\v.exe" -skip-running   -o "C:\Development\scratch\tmp\tsession_22e0_73664400\01HP9BR2JJK00BJK4KCM38N3KN\one_mb_test.exe" "C:\Development\Repositories\VProjects\FileFormats\xlsx\spec\04_1MB_file\one_mb_test.v"
Failed command 3:    "C:\Development\Dependencies\v-main\v.exe" -skip-running   -o "C:\Development\scratch\tmp\tsession_22e0_73664400\01HP9BR2JJGAJETSWFH7YWZRKX\empty_test.exe" "C:\Development\Repositories\VProjects\FileFormats\xlsx\spec\01_empty_file\empty_test.v"
Failed command 4:    "C:\Development\Dependencies\v-main\v.exe" -skip-running   -o "C:\Development\scratch\tmp\tsession_22e0_73664400\01HP9BR2JJ4EB476G34QG07R85\table_test.exe" "C:\Development\Repositories\VProjects\FileFormats\xlsx\spec\03_simple_table\table_test.v"
Summary for all V _test.v files: 4 failed, 1 passed, 5 total. Elapsed time: 1277 ms, on 5 parallel jobs. Comptime: 4768 ms. Runtime: 58 ms.
```

### V version

V 0.4.4 215ab13

### Environment details (OS name and version, etc.)

V full version: V 0.4.4 0fb38ed.215ab13
OS: windows, Microsoft Windows 11 Home v22631 64-bit
Processor: 16 cpus, 64bit, little endian,

getwd: C:\Development\Repositories\VProjects\FileFormats\xlsx
vexe: C:\Development\Dependencies\v-main\v.exe
vexe mtime: 2024-02-10 10:44:08

vroot: OK, value: C:\Development\Dependencies\v-main
VMODULES: OK, value: C:\Development\Dependencies\vmodules
VTMP: OK, value: C:\Development\scratch\tmp

Git version: git version 2.43.0.windows.1
Git vroot status: weekly.2023.45.1-675-g215ab130
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc status: thirdparty-windows-amd64 e90c2620
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
Could this be a cache issue?  If V had already compiled the module, the compiled version would be in the cache.  If `v remove` doesn't removed the cached copy, I could see it still being found...

**Comment by ttytm** [comment]
Not testing on windows, I cannot reproduce this. 

We have some parts where we work around the rm commands not behaving on Windows. 
So to me this looks like it is the same thing here. 

I'll look into it, though I currently only have an ARM machine which makes it barely possible to test this on Windows locally. So I would prepare something with a similar workaround as we already used for Windows, then you can try if it fixes things @hungrybluedev. Alternatively I just add CI for `v remove` that runs on Windows runners as well and see if it covers this.

**Comment by ttytm** [comment]
Okay it's possible to reproduce in CI. And it looks like it really is just the remove command.

Below is enough for a repro

1. `v install https://github.com/hungrybluedev/xlsx`
2. `v remove xlsx`.

On Windows xlsx still exists.
