### ISSUE TITLE
v.reflection does not populate when compiled as a shared library (-shared)

### ISSUE THREAD

**Issue by jcweaver997** [vlang/v#20798]
### Describe the bug

v.reflection does not populate when compiled as a shared library (-shared)

Everything is empty, here is an example:
![image](https://github.com/vlang/v/assets/6415281/145b9ecf-d354-4f22-894e-c6c552536d16)
![image](https://github.com/vlang/v/assets/6415281/2acd51c8-dfa8-4873-8050-73e1661dca5b)

This causes "some" print formatting to fail for gdextension. Simple values like number types work fine, but printing structs does not. All types still have non-zero T.idx's but the reflection tables are empty.

### Reproduction Steps

To produce this, I was working on vgdextension. Godot loads the shared library and calls the entry point function. As this requires you to create a shared library and load it dynamically, its a bit harder to get setup. This can be easily reproduced using the example for jcweaver997/vgdextension, importing v.reflection, and trying to get a type or list the types. String formatting a struct will cause the program to crash.

### Expected Behavior

v.reflection tables to be populated and no crashing when string formatting a struct

### Current Behavior

v.reflection tables are empty and crashes are experienced when string formatting a struct

### V version

V 0.4.4 16574df

### Environment details (OS name and version, etc.)

V full version: V 0.4.4 afd74ad.16574df
OS: windows, Microsoft Windows 11 Pro v26052 64-bit
Processor: 24 cpus, 64bit, little endian, 

getwd: C:\Users\jcwea\Documents\git\jvmmo
vexe: C:\Users\jcwea\Documents\git\v\v.exe
vexe mtime: 2024-02-10 00:25:17

vroot: OK, value: C:\Users\jcwea\Documents\git\v
VMODULES: OK, value: C:\Users\jcwea\.vmodules
VTMP: OK, value: C:\Users\jcwea\AppData\Local\Temp\v_0

Git version: git version 2.40.0.windows.1
Git vroot status: weekly.2024.04-90-g16574df9 (22 commit(s) behind V master)
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc status: thirdparty-windows-amd64 b99a453d
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
For windows we have a `_vinit_caller` fn which is calleld on 
![image](https://github.com/vlang/v/assets/773947/ec3c1839-ac1f-4a12-bcf6-e98ddb7adef5)

It must be called to fill the reflection data as a non-shared one.

**Comment by jcweaver997** [comment]
Thanks @felipensp, that makes sense. Everything appears to work using:
```v
fn C._vinit(int, voidptr)
```

and calling this in the entrypoint:
```v
C._vinit(0, unsafe{nil})
```
