### ISSUE TITLE
Failed to include sys/select.h

### ISSUE THREAD

**Issue by azakharchenko-msol** [vlang/v#20799]
**V doctor:**
```
V full version: V 0.4.4 d585e50.ea2e6e1
OS: linux, Ubuntu 23.10
Processor: 8 cpus, 64bit, little endian, 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz

getwd: /home/az/Projects/test/usbmon
vexe: /home/az/Projects/v/v/v
vexe mtime: 2024-02-12 05:29:53

vroot: OK, value: /home/az/Projects/v/v
VMODULES: OK, value: /home/az/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.40.1
Git vroot status: weekly.2024.06-49-gea2e6e15
.git/config present: true

CC version: cc (Ubuntu 13.2.0-4ubuntu3) 13.2.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg select_test.v`
```v
#include <sys/select.h> 
#flag -I/usr/include -L/usr/lib

pub struct C.fd_set { }
pub struct C.timeval { }
fn C.select(int, &C.fd_set, &C.fd_set, &C.fd_set, &C.timeval) int 

fn main() {
	println ("hello world")
}
```

**What did you expect to see?**

the row fn C.select(int, &C.fd_set, &C.fd_set, &C.fd_set, &C.timeval) int compiles successful

**What did you see instead?**
```
select_test.v:6:6: error: expecting method name
    4 | pub struct C.fd_set { }
    5 | pub struct C.timeval { }
    6 | fn C.select(int, &C.fd_set, &C.fd_set, &C.fd_set, &C.timeval) int 
      |      ~~~~~~
    7 | 
    8 | fn main() {
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Casper64** [comment]
Does the code work if the file doesn't end with `_test` ?

**Comment by azakharchenko-msol** [comment]
No, the `_test` in filename does not affect to anything

**Comment by MCausc78** [comment]
@azakharchenko-msol  you should escape function name with `@`, as `select` is reserved word in V used for communicating with channels

**Comment by azakharchenko-msol** [comment]
@MCausc78 Big thanks! works
