### ISSUE TITLE
global variables in debug mode

### ISSUE THREAD

**Issue by PavelVozenilek** [vlang/v#208]
Global variables may help with defensive coding. 

Example 1: all allocations/deallocations are recorded and at the end of app run leaks are detected.
Example 2: deadlock detection.
Example 3: application specific checks where it is not desirable to clutter the code with additional function parameter(s).

Possible syntax:

```
not-in-release { 
  my-debug-var := 1
}

fn foo()
{
   ...
   not-in-release {
       my-debug-var = my-debug-var + 1
   }
   ...
}

```
Simple statements could omit the `not-in-release`:

```
fn bar()
{
  my-debug-var = my-debug-var + 1 // no-op in release
}
```

These variables and code would exist in in debug mode(s) and when tests are compiled in.

**Comment by diamondburned** [comment]
I am very much against this, as it may seem really hard to convert the code from debugging to release. If no global state is something of a language feature, it shouldn't be allowed in any cases.

**Comment by Bowero** [comment]
Global variables are not a part of V. This is completely intentional.

>Unlike most other languages, V only allows defining variables in functions. Global (module level) variables are not allowed. There's no global state in V.

https://vlang.io/docs#vars
