### ISSUE TITLE
V self compilation and symlink issue

### ISSUE THREAD

**Issue by Lacrimus** [vlang/v#2082]
V version: 0.1.20 69b498d
OS: Windows 10 Home (Build 1903)

What did you do?
Installed Vlang via Git Bash, installed tools via cygwin, ran the makefile and created a symlink
Tried to have v compile itself.
 
What did you see instead?
cc: Error: unknown command line option »-mmacosx-version-min=10.7«
V error: C error. This should never happen. Please create a GitHub issue... (and so on)

Also despite creating the symlink, I can´t run the v command outside the top v directory aswell as in v´s subdirectories (e.g. the "examples folder").

Thanks for taking you time, much appreciated.

**Comment by Delta456** [comment]
Don't you use Cygwin instead use WSL.

**Comment by Lacrimus** [comment]
> 
> 
> Don't you use Cygwin instead use WSL.

Excuse me, but don´t you change the users demands when compatibility doesn´t match them.

**Comment by medvednikov** [comment]
Cygwin is not supported. There's no point in Cygwin since windows is supported natively.

**Comment by Lacrimus** [comment]
I did indeed follow the instructions, there was no indication about it not being supported...  :/

**Comment by medvednikov** [comment]
What does `gcc -v` say?

**Comment by medvednikov** [comment]
According to https://github.com/vlang/v/wiki/Installing-a-C-compiler-on-Windows

It should be mingw-w64

**Comment by spytheman** [comment]
You can modify your PATH variable, instead of creating a symlink @Lacrimus . 

I am not familiar with cygwin anymore (have not used it for over 12 years), but maybe you can put 
`export PATH=$PATH:/your/v/toplevel/folder`
... inside your ~/.bashrc file and try again.

About the -mmacosx-version-min=10.7 thing, for some reason it thinks you are on macos. 
You can try to override that, with adding:
`export VFLAGS="-os windows"` in your ~/.bashrc .

**Comment by spytheman** [comment]
Cygwin is not supported, and you are on your own pretty much though if you encounter bugs... The mingw compiler (or msvc) is much better tested (they even have their own CI builds, so breaking them is quickly fixed).

**Comment by medvednikov** [comment]
These fixes are not going to work. It's much easier to use mingw-w64. 

I'll make it clear in the readme  that cygwin is not supported.

**Comment by Lacrimus** [comment]
Thanks for the clarification!

**Comment by medvednikov** [comment]
I've updated the wiki:

```
Please note that Cygwin is not supported. It's used to run *nix software that doesn't run on Windows. V has full Windows support, so there's no point in Cygwin.
```
