### ISSUE TITLE
v up not working

### ISSUE THREAD

**Issue by schoko123** [vlang/v#2085]
**V version:**  1.19
**OS:** Linx Mint 19.1 cinnamon

**What did you do?**
./v up

**What did you expect to see?**
updated v
 
**What did you see instead?**

./v up
Updating V...
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
make: Entering directory '/home/thomas/v'
rm -rf vc/
git clone --depth 1 --quiet https://github.com/vlang/vc
cc -std=gnu11 -w -o v vc/v.c -lm
./v -o v compiler
warning: /home/thomas/v/vlib/builtin/string.v:360: `[0 ; len]` syntax was removed. Use `[0].repeat(len)` instead
warning: /home/thomas/v/vlib/builtin/string.v:877: `[0 ; len]` syntax was removed. Use `[0].repeat(len)` instead
warning: /home/thomas/v/vlib/builtin/int.v:216: `[0 ; len]` syntax was removed. Use `[0].repeat(len)` instead
warning: /home/thomas/v/vlib/builtin/map.v:172: `[0 ; len]` syntax was removed. Use `[0].repeat(len)` instead
warning: /home/thomas/v/vlib/term/colors.v: the following imports were never used:
 * os
fn (g mut CGen) add_placeholder() int {
                              ^        
/home/thomas/v/compiler/cgen.v:124:31: `g` is declared as mutable, but it was never changed
Makefile:12: recipe for target 'all' failed
make: *** [all] Error 1
make: Leaving directory '/home/thomas/v'

**Comment by medvednikov** [comment]
The message says it all:

error: cannot pull with rebase: You have unstaged changes.

You have changes in the V repo. Commit them or remove them.
