### ISSUE TITLE
error  library 'atomic' not found

### ISSUE THREAD

**Issue by rootoor-dev** [vlang/v#20875]
### Describe the bug

I get this error when I try to run a ved program containing UI code.
Here is the message gotten after trying to run [`ved`](https://github.com/vlang/ved)
I need help please.

```
==================
/tmp/v_1000/ved.01HQ21N46EK1SN0QATZAHQB75V.tmp.c:35532: warning: assignment discards qualifiers from pointer target type
tcc: error: library 'atomic' not found
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

### Reproduction Steps

git clone https://github.com/vlang/ved
cd ved
v .
./ved

### Expected Behavior

run successfully the IDE written in Vlang named **`ved`**.

### Current Behavior

==================
/tmp/v_1000/ved.01HQ21N46EK1SN0QATZAHQB75V.tmp.c:35532: warning: assignment discards qualifiers from pointer target type
tcc: error: library 'atomic' not found
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

### V version

V 0.4.4 c60a869

### Environment details (OS name and version, etc.)

kali linux purple 2024
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
Please, open the issue at https://github.com/vlang/ved/issues
