### ISSUE TITLE
C. type unknown

### ISSUE THREAD

**Issue by antono2** [vlang/v#20887]
### Describe the bug

It seems like a `C.VkInstance` type is changed to just `VkInstance` in the C intermediary and VkInstance can't be found afterwards.

```
error: unknown type name ‘VkInstance’
 2922 | main__VkResult main__create_instance(
    main__VkInstanceCreateInfo* p_create_info, 
    main__VkAllocationCallbacks* p_allocator, 
    VkInstance* p_instance
    );
```
This line in V can be found [here](https://github.com/antono2/tmp/blob/e35846122e600cda3616d6053383da2ef824aac1/src/main.v#L221)

### Reproduction Steps

Not sure if the vulkan SDK is needed to test this, but it can be found at https://vulkan.lunarg.com.
In case it's needed, make sure to add the path to `libvulkan.so.1` or `vulkan-1.dll` to the `LD_LIBRARY_PATH` environment variable, like `export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"`

Then clone the tmp project and run it
`https://github.com/antono2/tmp.git`
`cd tmp`
`v -cc gcc -g run .`

### Expected Behavior

This should fill the `instance` variable

### Current Behavior

Throws errors, because VkInstance cannot be found

### Possible Solution

Check if on the way to the C intermediary the type for `C.VkInstance` is somehow lost.
The reason might be the type definition as an empty struct, as the content is not known and is filled by `create_instance`.

### Additional Information/Context

I've tried a non C.-version, but defining `VkInstance` as a `voidptr` will result in memory errors.

### V version

Current V version: V 0.4.4 1d80cb9

### Environment details (OS name and version, etc.)

V full version: V 0.4.4 46086c0.1d80cb9
OS: linux, Ubuntu 22.04.4 LTS
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

getwd: /home/anton/workspace/tmp
vexe: /home/anton/workspace/v/v
vexe mtime: 2024-02-22 13:56:11

vroot: OK, value: /home/anton/workspace/v
VMODULES: OK, value: /home/anton/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.34.1
Git vroot status: weekly.2024.01.test2-341-g1d80cb91
.git/config present: true

CC version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
[main.v.txt](https://github.com/vlang/v/files/14375291/main.v.txt)
