### ISSUE TITLE
Data corruption when initializing struct with 2-dimensional array of structs as a member

### ISSUE THREAD

**Issue by Renerick** [vlang/v#20895]
### Describe the bug

When initializing a struct's field, which is a multidimensional array of structs, the data in the array is corrupted and not initialized correctly, garbage data is seen instead. The exact amount of corrupted element is not consistent, but currently the observed pattern is that the first array contains garbage data and the rest of arrays contain zeros. This doesn't seem to happen with 1-dimensional arrays of structs.

### Reproduction Steps

```vlang
module main

struct Cell {
	value int
	fvalue f32
mut:
	mut_value int = 10
	mut_fvalue f32
}

struct Grid {
	cells  [4][4]Cell
}

fn main() {
	mut tile_field := [4][4]Cell{}

	b := Grid {
		cells: tile_field
	}

	println("The original:")
	println(tile_field)
	println("==========")
	println("The struct:")
	println(b.cells)
}
```

### Expected Behavior

lots of zeros and some 10's

### Current Behavior

The second print shows that some of the first values contain some arbitrary numbers, whereas the rest are all zeroes.
```
The original:
[[Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}], [Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}], [Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}], [Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 10
    mut_fvalue: 0.0
}]]
==========
The struct:
[[Cell{
    value: 21888352
    fvalue: 2.1888416e+07
    mut_value: 21888480
    mut_fvalue: 2.1888544e+07
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 0
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 0
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 0
    mut_fvalue: 0.0
}], [Cell{
    value: 0
    fvalue: 0.0
    mut_value: 0
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 0
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 0
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 0
    mut_fvalue: 0.0
}], [Cell{
    value: 0
    fvalue: 0.0
    mut_value: 0
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 0
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 0
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 0
    mut_fvalue: 0.0
}], [Cell{
    value: 0
    fvalue: 0.0
    mut_value: 0
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 0
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 0
    mut_fvalue: 0.0
}, Cell{
    value: 0
    fvalue: 0.0
    mut_value: 0
    mut_fvalue: 0.0
}]]
```

### V version

V 0.4.4 27e6fef.0514de7

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.4 27e6fef.0514de7
OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 16 cpus, 64bit, little endian, 

getwd: C:\Users\[REDACTED]\Documents\Dev\vlang\repro
vexe: C:\Users\[REDACTED]\Documents\Dev\vlang\v\v.exe
vexe mtime: 2024-02-23 15:54:22

vroot: OK, value: C:\Users\[REDACTED]\vlang\v
VMODULES: OK, value: C:\Users\[REDACTED]\.vmodules
VTMP: OK, value: C:\Users\[REDACTED]\AppData\Local\Temp\v_0

Git version: git version 2.43.0.windows.1
Git vroot status: weekly.2024.08-12-g0514de75
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc status: thirdparty-windows-amd64 b99a453d
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Renerick** [comment]
This is C code that is roughly equivalent to the code generated by V

```c
#include <stdio.h>

typedef struct Cell Cell;
struct Cell {
	int value;
};

typedef struct Grid Grid;
struct Grid {
    Cell field[4][4];
};

void main() {
    Cell cells[4][4] = {
        { (Cell){.value = 1}, (Cell){.value = 1}, (Cell){.value = 1}, (Cell){.value = 1},  },
        { (Cell){.value = 1}, (Cell){.value = 1}, (Cell){.value = 1}, (Cell){.value = 1},  },
        { (Cell){.value = 1}, (Cell){.value = 1}, (Cell){.value = 3}, (Cell){.value = 1},  },
        { (Cell){.value = 1}, (Cell){.value = 1}, (Cell){.value = 1}, (Cell){.value = 1},  },
    };

    Grid g = {
        .field = { cells[0], cells[1], cells[2], cells[3], }
    };

    for (int i = 0; i < 4; i++) {
        printf("Pointer: %i Value: %i | ", cells[i], cells[i][0].value);
        printf("Pointer: %i Value: %i\n", g.field[i], g.field[i][0].value);
    }
}
```

It also shows similar problem. I believe, the way to fix it would be to generate proper recursive copying on initialization instead of shallow copy which is used right now. I'm not that familiar with inner workings of C array initialization, but it appears the "garbage" data are the actual pointers which are being interpreted as struct values. This also explains inconsistency of the behavior - depending on the size of the struct and amount of pointers, different fraction of struct values is affected.

**Comment by GGRei** [comment]
For me, your analysis is good. I used your V code, which I transpiled into C for the compiler, and then I had fun modifying the code to do some tests (  it is simpler than if the data were dynamic ):

```c
VV_LOCAL_SYMBOL void main__main(void) {
	Array_fixed_Array_fixed_main__Cell_4_4 tile_field = {{(main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}, (main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}, (main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}, (main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}}, {(main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}, (main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}, (main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}, (main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}}, {(main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}, (main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}, (main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}, (main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}}, {(main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}, (main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}, (main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}, (main__Cell){.value = 0,.fvalue = 0,.mut_value = 10,.mut_fvalue = 0,}}};
	main__Grid b;
	memcpy(&b.cells, &tile_field, sizeof(tile_field));
	println(_SLIT("The original:"));
	println(Array_fixed_Array_fixed_main__Cell_4_4_str(tile_field));
	println(_SLIT("=========="));
	println(_SLIT("The struct:"));
	println(Array_fixed_Array_fixed_main__Cell_4_4_str(b.cells));
}
```

This works and solves the initial problem, but I wonder if this is the best way to solve this problem, and here's why:

**memcpy** is very efficient for copying data in memory from one block to another following certain rules to be respected, such as the data type, overlapping in memory etc... But if there are complex data like pointers in a structure, it seems to me that memcpy will copy the addresses of the pointers but not the pointed-to data itself? which can lead to problems in some cases. 

If I am mistaken in my statements, please feel free to correct me.

For solving this problem and taking into account my previous explanation if it is correct, wouldn't it be better to use a method that ensures a deep and safe copy in case of, for example, complex structures containing pointers?

Would a loop copy allow for a safe deep copy ( with malloc if needed ), even in the case of pointers within a structure? 

If someone has an explanation on this matter, I would be personally interested in knowing it. If my reasoning is wrong, please don't hesitate to correct me, it will be educational for me along the way! :)

**Comment by Renerick** [comment]
> memcpy is very efficient for copying data in memory from one block to another following certain rules to be respected, such as the data size, overlapping in memory etc... But if there are complex data like pointers in a structure, it seems to me that memcpy will copy the addresses of the pointers but not the pointed-to data itself? which can lead to problems in some cases.

I suggested memcpy because it seems to be generated by V when doing array assignment. I don't mind what exactly will be used, as long as it's consistent between assignment and initialization. My hunch however is to stick to memcpy for basic shallow copy and leave full deep cloning to be used explicitly when wanted by the user

**Comment by Renerick** [comment]
Fixed 🚀 thanks!
