### ISSUE TITLE
Generic function signatures and template parameter omission

### ISSUE THREAD

**Issue by ntrel** [vlang/v#209]
From https://vlang.io/docs#generics:
```rust
struct Repo<T> {
	db DB
}
// vfmt removes `<T>` to reduce clutter
fn new_repo(db DB) Repo {
	return Repo{db: db}
}
users_repo := new_repo<User>(db)
```
The signature of `new_repo` does not look like a template - but much worse than that, the usage is not clear. Signatures are important because documentation doesn't show the function body (and reading the body too just to know the function arguments and return type can take too long). It returns `Repo`, a struct template. The signature gives no clue that the user needs to supply a template type, and no clue what any supplied type would apply to. Instead, we need to mention T:
```rust
fn new_repo(db DB) Repo<T> // minimal signature
fn new_repo<T>(db DB) Repo<T> // explicit meaning
```
T is not clutter in the return type. (As mentioned [here](https://github.com/vlang/v/issues/147#issuecomment-485134430), single letter type names may be reserved to use as implicit template argument names). So the reader can now see that T is an implicit template argument. For this to work, I think T *only being used in the return type* has to mean that T is a non-inferred template argument that must be manually supplied.

Now the next example:
```rust
fn (r Repo) find_by_id(id int) T? {  
	table_name := T.name
	return r.db.query_one<T>('select * from $table_name where id = ?', id)
}
user := users_repo.find_by_id(1)? 
```
Where does T come from here? According to the rule explained above for `new_repo`, T is only used in the return type of the signature, so it should be an implicit template argument that is *not inferred*. But here that is not what we want. The signature needs to explain where T comes from in order to make sense:
```rust
fn (r Repo<T>) find_by_id(id int) T? // minimal signature
fn (r Repo<T>) find_by_id<T>(id int) T? // explicit meaning
```
This shows that T is a template argument inferred from `r`.

**Comment by medvednikov** [comment]
Yes I agree.

V is an explicit language, `T` should not be hidden at all.

My hate of the `<T>` syntax took over reasoning :)

**Comment by medvednikov** [comment]
I've updated the docs.

**Comment by ntrel** [comment]
Thanks!
