### ISSUE TITLE
Question static linked binary v compiler

### ISSUE THREAD

**Issue by schoko123** [vlang/v#2091]
How can i compile to a static linked binary with the v compiler ?

**Comment by medvednikov** [comment]
Which libraries are you using?

**Comment by schoko123** [comment]
@gslicer is right -> ldd yields "not a dynamic executable" !
so you can copy it anywhere and it will run on the same processor instruction type without any
dependencies on the running host. 
something like 

env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o app

in go

**Comment by medvednikov** [comment]
This is already a case unless you use C libs that are linked with `-lmylib`. They can be easily linked statically as well.

**Comment by gslicer** [comment]
Hmm, are we talking about Linux here?
On my machine a simple program (having no imports at all) compiles like this:

```
[slicer@ideapad Code]$ v/v --verbose prog
...
Done parsing.
flags=
cc() isprod=0 outname=a.out

==========
cc  -std=gnu11 -w -g -Werror=implicit-function-declaration -o "a.out" "/home/slicer/Code/a.out.tmp.c"    -lm -lpthread   -ldl 
cc took 233 ms
=========
```

then the resulting binary looks like this:


```
[slicer@ideapad Code]$ file a.out 
a.out: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=c6d306c909a2e4e0ffac8635eaf940a2027bed63, with debug_info, not stripped

[slicer@ideapad Code]$ ldd a.out 
	linux-vdso.so.1 (0x00007ffdedfab000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f1f21150000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1f2112f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f1f21129000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f1f20f63000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1f212b3000)
```

**Comment by medvednikov** [comment]
All programs that use vlib need libc. Statically linking libc is not possible.

 In the future it'll be possible to use a custom libc like musl.

**Comment by gslicer** [comment]
@medvednikov 
> All programs that use vlib need libc. Statically linking glibc is not possible.

This seems to be true [oops!](https://www.systutorials.com/5217/how-to-statically-link-c-and-c-programs-on-linux-with-gcc/)
