### ISSUE TITLE
documentation generator seems to be off

### ISSUE THREAD

**Issue by despiegk** [vlang/v#20921]
### Describe the bug

<img width="668" alt="image" src="https://github.com/vlang/v/assets/6021844/68f61e4c-223c-4641-8822-3d1a786e083d">

used to produce a code block but now we get 

<img width="1260" alt="image" src="https://github.com/vlang/v/assets/6021844/ba996579-8bca-4619-b729-c817932b7198">

unrelated we also have some double entries

<img width="385" alt="image" src="https://github.com/vlang/v/assets/6021844/f755fbfb-7054-4402-8440-fb7f4eb738d3">

### Reproduction Steps

see https://github.com/freeflowuniverse/crystallib

there is a doc.sh script to generate

### Expected Behavior

code block in the docu

### Current Behavior

see above

### V version

newest

### Environment details (OS name and version, etc.)

m.1 osx
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by ttytm** [comment]
I'll try to look into it asap.
