### ISSUE TITLE
outdated official toml test

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#20933]
### Describe the feature

at `vlib/toml/tests/alexcrichton_toml_rs_test.v` is using the repository `https://github.com/alexcrichton/toml-rs.git` that was archived. 

toml Should use `https://github.com/toml-lang/toml-test.git` now

### Use Case

test

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.4.4 d5370bd

### Environment details (OS name and version, etc.)

all
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
https://github.com/toml-lang/toml-test.git is the successor of the https://github.com/BurntSushi/toml-test.git repo.

The archived, https://github.com/alexcrichton/toml-rs.git is now succeeded by https://github.com/toml-rs/toml, which also has the commit 499e8c4, where the test .toml files, were not still embedded in .rs files.
