### ISSUE TITLE
`println` cannot directly print struct returned from the function

### ISSUE THREAD

**Issue by avitkauskas** [vlang/v#2094]
**V version:** 
V 0.1.20 9a7ffac
**OS:** 
Mac OS

**What did you do?**
```v
struct S {
    x int
}

fn s() S {
    return S{1}
}

println(s())
```

**What did you expect to see?**
`{ x: 1 }`
 
**What did you see instead?**
```
test1.tmp.c:3721:46: error: expected ')'
  println ( s ( tos2((byte*)"{ x: $).x }") ) ;
```

**Comment**
```v
res := s()
println(res)
```
works fine.

**Comment by luoheng23** [comment]
It seems it has been solved. I can't reproduce this bug.
My version is `V 0.1.20 802da8f`.

**Comment by medvednikov** [comment]
Yes, I fixed it yesterday.
