### ISSUE TITLE
vlib: time.Duration and `-` operator leaves spurious ns reminder for a - b < 0 case.

### ISSUE THREAD

**Issue by hholst80** [vlang/v#20965]
### Describe the bug

For a, b : time.Time the `-` operator will floor the components of the time.Duration, except the ns field. 

### Reproduction Steps

```v
import time
fn main() {
  now := time.now()
  yesterday := time.parse("2024-03-04 00:00:00")!
  delta := yesterday - now
  if delta == time.Duration(0) {
    println("we will most likely not see this")
  } else {
    println("delta: $delta")
  }
}
```

### Expected Behavior

time.Duration(0) identically.

### Current Behavior

ns field is nonzero.

### Possible Solution

Floor the ns to identically zero.

### V version

V 0.4.4 cf7dcfe

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.4 cf7dcfe
OS: linux, "Artix Linux"
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz

getwd: /home/root
vexe: /home/root/Apps/v/v
vexe mtime: 2024-02-27 14:30:38

vroot: OK, value: /home/root/Apps/v
VMODULES: OK, value: /home/root/.vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.43.1
Git vroot status: weekly.2024.08-15-gee045eda (35 commit(s) behind V master)
.git/config present: true

CC version: cc (GCC) 13.2.1 20230801
thirdparty/tcc status: thirdparty-linux-amd64 40e5cbb5
```

**Comment by hholst80** [comment]
I think you are correct.  I am probably looking for a Unix timestamp with a second resolution.

However, there seems still to be an issue with the display (to string) method for negative durations.  I am confused at least.

```
    now := time.now()
    then := time.parse("2024-03-06 17:28:00")!
    delta := then - now
    seconds := int(delta.seconds()) // this will be plenty, but ${delta} will only give negative ns fraction
    os.system("echo ETA: ${delta} or ${seconds} seconds | cowsay")

```

```
 ________________________________
ETA: -796ns or -693579 seconds >
 --------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

**Comment by JalonSolov** [comment]
Subtracting one time value from another returns a Duration, which is just an `i64` number of nanoseconds.

You're converting that to an `int`, which is what gives you the crazy number of seconds.

Now... that said, it doesn't appear that the `-` function is working correctly, as it should be a whole lot more nanoseconds than what's being shown.

Here it is without the cast (or shelling out to cowsay...):
```v
import time

now := time.now()
then := time.parse("2024-03-06 17:28:00")!
delta := then - now
println('ETA: ${delta} or ${delta.seconds()} seconds')
```
With that change I get
```
ETA: -924ns or -1.399575694117924e+06 seconds
```
(of course, different numbers every time)

Those numbers hardly look correct.

**Comment by hholst80** [comment]
The somewhat spurious output fromthe string representation made me think that Durations were limited to non-negatives.  I think this was just an error in how they are represented as strings.
