### ISSUE TITLE
About the passing of function arguments, references, and values in vlang.

### ISSUE THREAD

**Issue by ipsfsw** [vlang/v#20993]
### Describe the bug

```v
struct Ht {
mut:
	i int
}

struct Hin {
	time MyTime
mut:
	n  int
	ht Ht
}

fn (mut h Hin) test_fun() int {
	println('h.n = ${h.n}')
	h.n = 1000
	h.ht = Ht{
		i: 1000
	}
	return 0
}

fn chageer_hin(mut h Hin) {
	println('h.n = ${h.n}')
	h.n = -1000
	h.ht = Ht{
		i: -1000
	}
}
fn main() {
	mut h := Hin{
		time: time.now()
		n: 0
		ht: Ht{
			i: 0
		}
	}
	h2 := h	
	println("h = ${h}") //  h = Hin{ time:     MyTime(2024-03-11 03:11:48) n: 0 ht: Ht{ i: 0 } }
	println("h2 = ${h2}") // h2 = Hin{ time:     MyTime(2024-03-11 03:11:48) n: 0 ht: Ht{ i: 0 } }
	chageer_hin(mut h) // h.n = 0
	// h.test_fun()
	println("h = ${h}") // h = Hin{ time:     MyTime(2024-03-11 03:11:48) n: -1000 ht: Ht{ i: -1000 } }
}
```

### Reproduction Steps

```v
struct Ht {
mut:
	i int
}

struct Hin {
	time MyTime
mut:
	n  int
	ht Ht
}

fn (mut h Hin) test_fun() int {
	println('h.n = ${h.n}')
	h.n = 1000
	h.ht = Ht{
		i: 1000
	}
	return 0
}

fn chageer_hin(mut h Hin) {
	println('h.n = ${h.n}')
	h.n = -1000
	h.ht = Ht{
		i: -1000
	}
}
fn main() {
	mut h := Hin{
		time: time.now()
		n: 0
		ht: Ht{
			i: 0
		}
	}
	h2 := h	
	println("h = ${h}") //  h = Hin{ time:     MyTime(2024-03-11 03:11:48) n: 0 ht: Ht{ i: 0 } }
	println("h2 = ${h2}") // h2 = Hin{ time:     MyTime(2024-03-11 03:11:48) n: 0 ht: Ht{ i: 0 } }
	chageer_hin(mut h) // h.n = 0
	// h.test_fun()
	println("h = ${h}") // h = Hin{ time:     MyTime(2024-03-11 03:11:48) n: -1000 ht: Ht{ i: -1000 } }
}
```

### Expected Behavior

Since vlang has a reference (&), the behavior of the value is different from the behavior of the structure, but I pass (mut f struct_type) and the result is a reference, isn't that wrong?
Compiling to c looks like this :
```c
VV_LOCAL_SYMBOL int main__Hin_test_fun(main__Hin* h) {
	println( str_intp(2, _MOV((StrIntpData[]){{_SLIT("h.n = "), /*100 &int*/0xfe07, {.d_i32 = h->n}}, {_SLIT0, 0, { .d_c = 0 }}})));
	h->n = 1000;
	h->ht = ((main__Ht){.i = 1000,});
	int _t1 = 0;
	return _t1;
}
```

VV_LOCAL_SYMBOL void main__chageer_hin(main__Hin* h) {
	println( str_intp(2, _MOV((StrIntpData[]){{_SLIT("h.n = "), /*100 &int*/0xfe07, {.d_i32 = h->n}}, {_SLIT0, 0, { .d_c = 0 }}})));
	h->n = -1000;
	h->ht = ((main__Ht){.i = -1000,});
}
Here's what I think it should be:
VV_LOCAL_SYMBOL int main__Hin_test_fun(main__Hin h) 
VV_LOCAL_SYMBOL void main__chageer_hin(main__Hin h) 

Without passing by reference, the result generated should not be a passing pointer.

### Current Behavior

Compiling to c looks like this :
VV_LOCAL_SYMBOL int main__Hin_test_fun(main__Hin* h) {
	println( str_intp(2, _MOV((StrIntpData[]){{_SLIT("h.n = "), /*100 &int*/0xfe07, {.d_i32 = h->n}}, {_SLIT0, 0, { .d_c = 0 }}})));
	h->n = 1000;
	h->ht = ((main__Ht){.i = 1000,});
	int _t1 = 0;
	return _t1;
}

VV_LOCAL_SYMBOL void main__chageer_hin(main__Hin* h) {
	println( str_intp(2, _MOV((StrIntpData[]){{_SLIT("h.n = "), /*100 &int*/0xfe07, {.d_i32 = h->n}}, {_SLIT0, 0, { .d_c = 0 }}})));
	h->n = -1000;
	h->ht = ((main__Ht){.i = -1000,});
}

### V version

V 0.4.4 60b4fb3

### Environment details (OS name and version, etc.)

windows 11
![PixPin_2024-03-11_03-21-22](https://github.com/vlang/v/assets/109045784/2086bef8-fd5e-4824-a713-7eea4401ded2)
![PixPin_2024-03-11_03-21-55](https://github.com/vlang/v/assets/109045784/65d427bf-eb57-4bed-986d-9fe2828c9a46)
![PixPin_2024-03-11_03-22-17](https://github.com/vlang/v/assets/109045784/8fff50d9-5d9b-478d-a76c-bf72361b106d)

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
See the docs https://github.com/vlang/v/blob/master/doc/docs.md?tab=readme-ov-file#references
