### ISSUE TITLE
VC: _M_ARM64 check missing for endianness

### ISSUE THREAD

**Issue by daddycocoaman** [vlang/v#21003]
### Describe the bug

Hi,

I posted about this (https://github.com/vlang/v/discussions/13768#discussioncomment-8725449) and while updating my V build, I realized that `v_win.c` actually does `_M_ARM64` checks a few times to set some values, but that check isn't defined when it comes to the endianess on line 857. I know V isn't officially supported on Windows ARM64, but I think that check should at least be there based on other checks done in the same file.

Right now, I'm adding this manually when updating V, but this is _**probably**_  a bug. Just not sure where to fix it.

 

### Reproduction Steps

`./make.bat -msvc` on Windows ARM64

### Expected Behavior

Modifying the check in `v_win.c` lets me successfully compile the x64 version of V on Windows ARM64 using MSVC with `./make.bat -msvc --local`:

```
PS v-dev\v> .\make.bat -msvc --local
Building V...
 > Attempting to build "./v_win_bootstrap.exe" (from v_win.c) with MSVC
v_win.c
 > Compiling "./v.exe" with "./v_win_bootstrap.exe"
<OMITTED>

Note: `tcc` was not used, so unless you install it yourself, your backend
C compiler will be `cc`, which is usually either `clang`, `gcc` or `msvc`.

These C compilers, are several times slower at compiling C source code,
compared to `tcc`. They do produce more optimised executables, but that
is done at the cost of compilation speed.

 > V built successfully
 > To add V to your PATH, run `./v.exe symlink`.

V version: V 0.4.4 365bd18
```

### Current Behavior

```
PS v-dev\v> .\make.bat -msvc --local
Building V...
 > Attempting to build "./v_win_bootstrap.exe" (from v_win.c) with MSVC
v_win.c
vc/v_win.c(860): fatal error C1189: #error:  "Unknown architecture endianness"
In some cases, compile errors happen because of the MSVC compiler version
Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33519 for ARM64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

Backend compiler error

Exiting from error
ERROR: please follow the instructions in https://github.com/vlang/v/wiki/Installing-a-C-compiler-on-Windows
```

### Possible Solution

Add the _M_ARM64 check like this, wherever this code gets generated from:

```c
#elif defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__ || defined(__BYTE_ORDER) && __BYTE_ORDER == __LITTLE_ENDIAN || defined(__LITTLE_ENDIAN__) || defined(__ARMEL__) || defined(__THUMBEL__) || defined(__AARCH64EL__) || defined(_MIPSEL) || defined(__MIPSEL) || defined(__MIPSEL__) || defined(_M_AMD64) || defined(_M_X64) || defined(_M_IX86) || **defined(_M_ARM64)**
	#define TARGET_ORDER_IS_LITTLE 1
#else
	#error "Unknown architecture endianness"
#endif
```

### V version

V 0.4.4 f789874.a867ed6

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.4 f789874.a867ed6
OS: windows, Microsoft Windows 11 Enterprise v26058 ARM 64-bit Processor
Processor: 8 cpus, 64bit, little endian,

getwd: C:\Users\*\dev\v-dev\v
vexe: C:\Users\*\dev\v\v.exe
vexe mtime: 2024-03-08 23:45:01

vroot: OK, value: C:\Users\*\dev\v
VMODULES: OK, value: C:\Users\*\.vmodules
VTMP: OK, value: C:\Users\*\AppData\Local\Temp\v_0

Git version: git version 2.43.0.windows.1
Git vroot status: weekly.2024.11-5-g96aa23ff-dirty (5 commit(s) behind V master)
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc: N/A
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
You have to modify vlib/v/gen/c/cheaders.v around line 529, then v.c and v_win.c will be updated automatically after the PR is merged.

**Comment by spytheman** [comment]
You can also test locally with: `./v -o v_win.c -os windows -cc msvc cmd/v`, then inspecting the resulting `v_win.c` file.
