### ISSUE TITLE
cgen error for `pub fn (d &C.Display) str() string {`, where Display is from X11/Xlib.h (incomplete struct)

### ISSUE THREAD

**Issue by spytheman** [vlang/v#21015]
**V doctor:**
```
V full version: V 0.4.4 f789874.74b8c9d
OS: linux, Ubuntu 20.04.6 LTS
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i3-3225 CPU @ 3.30GHz

getwd: /space/v/oo
vexe: /space/v/oo/v
vexe mtime: 2024-03-13 11:19:25

vroot: OK, value: /space/v/oo
VMODULES: OK, value: /home/delian/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.42.0
Git vroot status: weekly.2024.11-19-gc29b64e0
.git/config present: true

CC version: cc (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0
thirdparty/tcc status: thirdparty-linux-amd64 40e5cbb5

```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg /v/misc/2024_03_13__18/c.v`
```v
#include <X11/Xlib.h>

@[typedef]
pub struct C.Display {}

pub fn (d &C.Display) str() string {
	return 'C.Display{}'
}

fn main() {
	x := unsafe { &C.Display(1) }
	println(x)
}

```

**What did you expect to see?**

compiled program with no cgen errors

**What did you see instead?**
```
==================
/tmp/v_1000/c.01HRWD2K94MQ3JFTGA0B33M979.tmp.c:12987: warning: implicit declaration of function 'Display_str'
/tmp/v_1000/c.01HRWD2K94MQ3JFTGA0B33M979.tmp.c:12987: error: type mismatch in conditional expression (have 'struct string' and 'int')
...
==================
(Use `v -cg` to print the entire error message)

```

Note: this should be tested on Linux/FreeBSD, but I think it would affect other cases, where on the C side, we have structs with incomplete definitions in the header files.
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
Is it related to issue #20702 @spytheman ?

**Comment by spytheman** [comment]
I do not know, the one in #20702 was for `type SomeName = C.SomeType` afaik, while here, the str method is defined on the C type itself.
