### ISSUE TITLE
C Builder error

### ISSUE THREAD

**Issue by Eliyaan** [vlang/v#21026]
### Describe the bug

The program outputs a C builder error.

### Reproduction Steps

```v
module main

#flag -I /lib64/libuvc/include/
#flag -luvc
#include <libuvc/libuvc.h>

@[typedef]
struct C.uvc_frame{
}

type FnFrameCB = fn (frame &C.uvc_frame)


fn main() {
	println("Hello?")

}

```

### Expected Behavior

It not to output a C builder error.

### Current Behavior

```
/tmp/v_1000/main.01HRZ3YKKMZ1PNX2QP72SFE0MN.tmp.c:939: error: ',' expected (got "*")
builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

### Additional Information/Context

(using libuvc)

### V version

 V 0.4.4 673a2f4.0a9d1f9

### Environment details (OS name and version, etc.)

V full version: V 0.4.4 673a2f4.0a9d1f9
OS: linux, Linux version 6.6.13-200.fc39.x86_64 (mockbuild@72f11b2996ed4699b0f705186172808f) (gcc (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6), GNU ld version 2.40-13.fc39) #1 SMP PREEMPT_DYNAMIC Sat Jan 20 18:03:28 UTC 2024
Processor: 4 cpus, 64bit, little endian, Intel(R) Pentium(R) Gold 7505 @ 2.00GHz

getwd: /home/nopana/projects/cnn_dataset/movenet
vexe: /home/nopana/v/v
vexe mtime: 2024-03-14 18:35:56

vroot: OK, value: /home/nopana/v
VMODULES: OK, value: /home/nopana/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.43.0
Git vroot status: weekly.2024.09-60-g0a9d1f9d
.git/config present: true

CC version: cc (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6)
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
```v
#flag -luvc
#include <libuvc/libuvc.h>

@[typedef]
struct C.uvc_frame_t {
}

type FnFrameCB = fn (frame &C.uvc_frame_t)

fn main() {
	println('Hello?')
}
```
This compiles cleanly for me, after I installed https://github.com/libuvc/libuvc .

Note the `C.uvc_frame_t`, if you want to use `@[typedef]`.

**Comment by spytheman** [comment]
On the C side:
```c
typedef struct uvc_frame {
...
} uvc_frame_t;
```
(from https://github.com/libuvc/libuvc/blob/master/include/libuvc/libuvc.h#L455)

**Comment by felipensp** [comment]
Can be closed @Eliyaan ?

**Comment by JalonSolov** [comment]
It can figure out that the `C.` name doesn't end with `_t` but `@[typedef]` was used.

However, I don't know if that's a universal rule or not.  If not, then yes, this should simply be closed.  Otherwise, this check should be added.

**Comment by Eliyaan** [comment]
From the C I can see (not much) it is not an universal rule, so I'm closing the issue.
