### ISSUE TITLE
Sumtypes used as C union types not working

### ISSUE THREAD

**Issue by trufae** [vlang/v#21122]
### Describe the bug

I'm trying to do the uing bindings for vlang, but i don't want to cast all the controls to C.uiControl everything those are boxed. So i though that using a sumtype would do the job, but seems like this doesn't play well with C types.

The situation is, that doing

```c
struct C.uiControl {}
type C.uiControl = C.uiButton | C.uiLabel | C.uiBox | C.uiControl
```
i get:
```sh
uing/uing.c.v:54:1: error: sum type `C.uiControl` must begin with capital letter
uing/uing.c.v:54:55: error: sum type cannot hold itself
```

if i defined like this:

```c
struct C.uiControl {}
type CiControl = C.uiButton | C.uiLabel | C.uiBox | C.uiControl
```

i get this
```sh
uing/box.v:12:26: warning: unknown type `C.Control` (all virtual C types must be defined, this will be an error soon).
uing/box.v:14:30: error: cannot cast `C.Control` to `&C.uiControl`
main.v:10:13: error: cannot use `&C.uiLabel` as `C.Control` in argument 1 to `uing.Box.append`
```

### Reproduction Steps

```sh
$ git clone https://github.com/trufae/v-uing.git
$ cd v-uing
$ git checkout sumtype
$ make
```

### Expected Behavior

building and running withuot segfaults

### Current Behavior

```sh
$ make
v -o main .
uing/box.v:12:26: warning: unknown type `C.Control` (all virtual C types must be defined, this will be an error soon).
Did you mean `C.uiControl`?
   10 | }
   11 |
   12 | pub fn (b &Box) append(c &C.Control, pos int) {
      |                          ~~~~~~~~~~
   13 |     C.uiBoxAppend(&C.uiBox(b), &C.uiControl(c), pos)
   14 | }
main.v:10:13: error: cannot use `&C.uiLabel` as `&C.Control` in argument 1 to `uing.Box.append`
    8 |     box := uing.new_vbox()
    9 |     // box.append(&C.uiControl(label), 1)
   10 |     box.append(label, 1)
      |                ~~~~~
   11 |     /*
   12 |     b := uing.new_button('ok')
make: *** [all] Error 1
2$
```

### Possible Solution

Well. for now , i created a branch named "wip" , where i'm just using voidptr, and that makes it work. but i think the language should provide a way to use V sumtypes as an alias for C union types.

### V version

V 0.4.5 f6a00fa

### Environment details (OS name and version, etc.)

```sh
$ v doctor
V full version: V 0.4.5 f6a00fa
OS: macos, macOS, 14.4.1, 23E224
Processor: 10 cpus, 64bit, little endian, Apple M1 Max

getwd: /Users/pancake/prg/v-uing
vexe: /Users/pancake/prg/v/v
vexe mtime: 2024-03-27 16:22:45

vroot: OK, value: /Users/pancake/prg/v
VMODULES: OK, value: /Users/pancake/.vmodules
VTMP: OK, value: /tmp/v_501

Git version: git version 2.39.3 (Apple Git-146)
Git vroot status: weekly.2023.33-1470-gf6a00fa5
.git/config present: true

CC version: Apple clang version 15.0.0 (clang-1500.3.9.4)
thirdparty/tcc status: thirdparty-macos-arm64 5c1d002f
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
Even this example does not works:

```V
#include "@VMODROOT/foo.h"

struct C.Foo {
	a int
}

struct C.Bar {
	a int
}

type Baz = C.Foo | C.Bar

fn main() {
	mut a := Baz{}
	a = C.Foo{a: 1000}
	dump(a)	
}
```

**Comment by spytheman** [comment]
> the language should provide a way to use V sumtypes as an alias for C union types

V sumtypes are not a direct match to C union types.

However, V *union types* are a direct match to C union types:
```v
union MyValue {
    x int
    y f32
    z string
}
v1 := MyValue{ x: 123 }
v2 := MyValue{ y: 3.14 }
v3 := MyValue{ z: 'abc' }
unsafe {
    dump(v1.x)
    dump(v2.y)
    dump(v3.z)
}
```

Note that accessing the fields of an union value is unsafe, since the language has no means to check what the value actually contains.

In contrast a sumtype value, has both a pointer to the actual value, and a type index field in it, and you can determine at runtime what it is.
