### ISSUE TITLE
enum methods don't work anymore?

### ISSUE THREAD

**Issue by lobotony** [vlang/v#2115]
**V version:** V 0.1.20 c069525
**OS:** 10.14.6

**What did you do?**

	enum Format {
	    undefined,
	    a,
	    rgb,
	    rgba
	}

	fn (format Format) bytes_per_pixel() int {
	    if format == .a {
	        return 1
	    } else if format == .rgb {
	        return 3
	    } else if format == .rgba {
	        return 4
	    } else {
	        panic('can\'t derive bpp from format $format')
	    }
	}

	fn maint() {
		v := Format.a
		println(v.bytes_per_pixel())
	}

**What did you expect to see?**
successful compilation

 
**What did you see instead?**
type `Format` has no field or method `bytes_per_pixel

This code used to work probably up to 0.1.19. Not sure if this is a bug or intentional.

**Comment by medvednikov** [comment]
I'm not sure they ever worked @lobotony 

But this is very useful and easy to implement.

**Comment by medvednikov** [comment]
Sorry, of course it worked :)

Will fix asap, thanks.

**Comment by medvednikov** [comment]
Ok it's actually not working because of `fn maint()` but the error is wrong.

**Comment by avitkauskas** [comment]
@medvednikov I think it's related to #2094

**Comment by medvednikov** [comment]
@avitkauskas yes the `.str()` thing needs to be cleaned up.

**Comment by LorenzoPirro** [comment]
moving the main on the top of the code, it works.
<img width="528" alt="Schermata 2019-09-26 alle 16 19 47" src="https://user-images.githubusercontent.com/17650857/65696608-d4f4fa00-e079-11e9-8569-253e2f7b46f1.png">

**Comment by lobotony** [comment]
It seems to be an ordering issue. The following doesn't compile

in bitmap/bitmap.v

    module bitmap


    enum Format {
        rgba
    }

    fn (format Format) bytes_per_pixel() int {
        return 4
    }

    pub fn init() int {
        v := Format.rgba
        return int(v.bytes_per_pixel())
    }

in main.v

	import bitmap

	fn main() {
		b := bitmap.init()
		println(b)
	}

Now, if I move the init() function to the top of the module, it will compile.

**Comment by medvednikov** [comment]
Fixed.
