### ISSUE TITLE
[x.json2] Decoding array type panics

### ISSUE THREAD

**Issue by revosw** [vlang/v#21168]
### Describe the bug

When json decoding an array type, V panics

### Reproduction Steps

```
import x.json2

pub struct Value {
	value string
}

fn main() {
	println(json2.decode[[]Value]('[{"value": "abc"}, {"value": "def"}]')!)
}
```

### Expected Behavior

This is printed
```
[
  Value {
    value: "abc"
  },
  Value {
    value: "def"
  },
]
```

### Current Behavior

```
================ V panic ================
   module: main
 function: main()
  message: The type `[]Value` can't be decoded.
     file: code.v:8
   v hash: a1b6360
=========================================
/tmp/v_60000/../../../../../../home/admin/v/vlib/builtin/builtin.c.v:66: at panic_debug: Backtrace
/tmp/v_60000/../../../../../../box/code.v:10: by main__main
/tmp/v_60000/../../../../../../tmp/v_60000/code.01HTEKB9M24DZTMKFASK5NH047.tmp.c:17052: by main
Exited with error status 1
```

### Possible Solution

Handle array type as type argument

### V version

V 0.4.5 a1b6360

### Environment details (OS name and version, etc.)

V full version: V 0.4.5 4687f8c.a1b6360
OS: windows, Microsoft Windows 11 Pro v22631 64-bit
Processor: 12 cpus, 64bit, little endian, 

getwd: C:\dev\v\winmd
vexe: C:\dev\_tools\v\v.exe
vexe mtime: 2024-04-02 04:56:12

vroot: OK, value: C:\dev\_tools\v
VMODULES: OK, value: C:\Users\simen\.vmodules
VTMP: OK, value: C:\Users\simen\AppData\Local\Temp\v_0

Git version: git version 2.40.0.windows.1
Git vroot status: weekly.2024.13-70-ga1b6360d
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,  
operable program or batch file.

thirdparty/tcc status: thirdparty-windows-amd64 a39eb79b
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by ttytm** [comment]
There are some limitations regarding the `x.json2` module.
Putting it even simpler, this will not work as well atm:
```v
println(json2.decode[[]string]('["value", "abc"]')!)
```
A primitive will have to be wrapped inside an object as a (struct)field to be decoded.

```v
import x.json2

pub struct Value {
	value string
}

pub struct Field {
	vals []Value
}

fn main() {
	println(json2.decode[Field]('{"vals": [{"value": "abc"}]}')!)
}
```
Will give an empty array. So there definitely is open work. Until then the json module might be the right tool.
