### ISSUE TITLE
have a better to way to detect arrays from compile time

### ISSUE THREAD

**Issue by Delta456** [vlang/v#21170]
https://github.com/vlang/v/blob/c086bee5bebb8b9374605fc65469f629d42ae18d/vlib/toml/toml.v#L59-L87

To currently match arrays via compile time, one has to use `typeof(typ.$(field.name)).name ` which is extremely hacky and inconvenient. There needs to be a better way to check the array type.

`typeof(typ.$(field.name))` should be used instead and match with the appropriate type.
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
Actually it is possible to do:

```V
struct Test {
	a []int = [1]
	b []u8 = [u8(2)]
	c []string = ['3']
}

fn main() {
	a := Test{}
	$for f in Test.fields {
		$if f.typ is []int {
			dump(a.$(f.name))
		} $else $if f.typ is []u8 {
			dump(a.$(f.name))
		} $else $if f.typ is []string {
			dump(a.$(f.name))
		}
	}	
}
```

**Comment by Delta456** [comment]
> Actually it is possible to do:
> 
> ```v
> struct Test {
> 	a []int = [1]
> 	b []u8 = [u8(2)]
> 	c []string = ['3']
> }
> 
> fn main() {
> 	a := Test{}
> 	$for f in Test.fields {
> 		$if f.typ is []int {
> 			dump(a.$(f.name))
> 		} $else $if f.typ is []u8 {
> 			dump(a.$(f.name))
> 		} $else $if f.typ is []string {
> 			dump(a.$(f.name))
> 		}
> 	}	
> }
> ```

Is there a way for fixed arrays?
