### ISSUE TITLE
Consider making f(x, ...) and x.f(...) equivalent

### ISSUE THREAD

**Issue by Richiban** [vlang/v#2117]
V essentially has two different syntaxes for declaring functions; one with standard arguments:

```v
fn myFunc(x int, y int) int { return x + y }
```

and another using a _receiver argument_:

```v
fn (x int) myFunc2(y int) { return x + y }
```

These two forms are essentially identical (as far as I can tell the receiver version gets no more functionality than the regular version); the only different is the syntax used to call them:

```v
x := 1
myFunc(1, 2)
// vs
x.myFunc2(2)
```

Wouldn't it be syntactically sweeter and also more useful to have the dot syntax merely be syntactic sugar for a regular function call?

So, `x.f()` would simply be sugar for `f(x)`.

This would allow for chaining functions that might not have been originally written to allow for chaining.

**Comment by M4SSD35TRUCT10N** [comment]
**IMHO** This is something I don't like. `x` is a Variable and not a 'struct` or subtype, so it would bloat the language specification and doesn't help. I see no syntactic sugar in it. It's confusing.

**Comment by medvednikov** [comment]
This was discussed before, can't find the discussion unfortunately.

It goes against the "one way" philosophy. Some people will be using `foo.bar()`, others will be using `bar(foo)`, and how do you have multiple `bar` methods now? :)

**Comment by Richiban** [comment]
@medvednikov I see, so V does not allow

```vlang
fn my_func(f Foo) {}

fn my_func(b Bar) {}
```

But it _does_ allow 

```vlang
fn (f Foo) my_func() {}

fn (b Bar) my_func() {}
```

Is that right?

**Comment by medvednikov** [comment]
Correct, there's no function overloading, but it's not a problem with methods.
