### ISSUE TITLE
Features helping with practical problems

### ISSUE THREAD

**Issue by PavelVozenilek** [vlang/v#212]
This is not a specific proposal or a bug report, rather few ideas written down.

Many proposals here are about nice to have small features. Why not to have closures, for example? Language X has them, and Y does too.  They are poor abstraction (pretending to be a function, but not really), and they could complicate the the implementation a lot. Or lambdas. Nice to have them in some specific cases, but could lead to dangerous complexity. C++ started with simple lambdas, and later it grew up into a monster. _Named lambdas!_ 

The real problem one meets is not lack of fancy _comp-sci_ constructs, but language not helping in understanding, exploring and modifying the code.  

Here are few things I wish to have support for.

1. Here's existing code. I want to understand it completely. Where should I start to read, where should I go next?
2. I want to try something.  I make copy of a source file, do my little change, and then try if this works. Is the language preventing me to do such experiments?
3. Here's someone's library. I want to use very small portion of it.  I do not wish to touch that code at all. I do not want it to interfere accidentally with my own code. Is there an easy way to do it?
4. Rearrangement of a project. How easy is to rename source files a move them around in project  tree? Is the language resisting me?

**Comment by ntrel** [comment]
> [closures] are poor abstraction (pretending to be a function, but not really), 

They are a key abstraction in functional programming, even GNU C supports them. Given that V supports heap allocation just by writing &var, closures fit well conceptually - allocate the captured variables on the heap instead of stack.

> Or lambdas.

Lambdas are just convenient sugar for function templates as I wrote in #163 (they can be closures too).

**Comment by medvednikov** [comment]
I agree with the importance of simplicity and readability. But closures are indeed an integral part of modern programming languages.

**Comment by lutherwenxu** [comment]
This issue has been closed due to the inactivity.
Please reopen this issue if you want to continue the discussion.
