### ISSUE TITLE
typo in module name erroneously reports "import cycle"

### ISSUE THREAD

**Issue by lobotony** [vlang/v#2123]
**V version:** V 0.1.20 fb4f14b
**OS:** MacOS 10.14.6

**What did you do?**

in mod/mod.v

	module mdo

	pub fn init() {
		println('ok')
	}

in main.v

	import mod

	fn main() {
		mod.init()
	}

**What did you expect to see?**
An error indicating that no module "mod" (note the typo in 'module mdo') could be found, maybe some helpful diagnostic about modules were actually found instead. 
 
**What did you see instead?**
V error: Import cycle detected

**Comment by joe-conigliaro** [comment]
Thanks, Ill sort this out

**Comment by joe-conigliaro** [comment]
here is the fix: https://github.com/vlang/v/pull/2166
