### ISSUE TITLE
option inside a result

### ISSUE THREAD

**Issue by demostanis** [vlang/v#21269]
### Describe the bug

I'm trying to have an option inside a result. I first thought I could return a `!?string`, but that didn't work.
I tried to add parenthesis around `?string`, like: `!(?string)`, but it hit me with the following error:
```
==================
/tmp/v_101372/clusters.4438779756418004972.tmp.c: In function 'main__main':
/tmp/v_101372/clusters.4438779756418004972.tmp.c:34174:16: error: '_option_string' has no member named 'is_error'
34174 |         if (_t2.is_error) {
      |                ^
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```
Code:
```v
fn myfn() !(?string) {
     url := ...
 
     mut req := http.Request{url: url}
     req.add_header(http.CommonHeader.x_forwarded_for, ip)
 
     res := req.do()!
     return res.body
}
```

### Reproduction Steps

compile the above code

### Expected Behavior

that it works

### Current Behavior

it didnt work

### V version

V 0.4.4 ac2dcc2 installed with nix

### Environment details (OS name and version, etc.)

V full version: V 0.4.4 ac2dcc2
OS: linux, Ubuntu 20.04.6 LTS (chroot)
Processor: 16 cpus, 64bit, little endian, Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
We cannot have result + option one. It must be a checker error there.

**Comment by JalonSolov** [comment]
1. You need to update your V.  What you have is quite a few commits behind.

2. Please post a complete example.  It's hard to guess exactly what you have that is showing the error.  It doesn't have to be your whole project, just something complete enough to show the problem.

**Comment by demostanis** [comment]
i cannot reproduce on the latest version of v
however, why cant I mix result + option? i have a function that does an http request, returning whether an optional string inside the body. i want to return errors and that optional string. what should i do instead?

**Comment by Delta456** [comment]
> We cannot have result + option one. It must be a checker error there.

It gives an error with the latest V


```
file.v:3:11: error: the fn returns type `!?string`, but type `!string` is a Result alias, you can not mix them
    1 | import net.http
    2 | 
    3 | fn myfn() !(?string) {
      |           ~~~~~~~~~~
    4 |      url := ''
    5 |
file.v:3:11: error: the fn returns type `!?string`, but type `?string` is an Option alias, you can not mix them
    1 | import net.http
    2 | 
    3 | fn myfn() !(?string) {
      |           ~~~~~~~~~~
    4 |      url := ''
    5 |
file.v:7:56: error: undefined ident: `ip`
    5 |  
    6 |      mut req := http.Request{url: url}
    7 |      req.add_header(http.CommonHeader.x_forwarded_for, ip)
      |                                                        ~~
    8 |  
    9 |      res := req.do()!
file.v:7:56: error: `ip` (no value) used as value in argument 2 to `net.http.Request.add_header`
    5 |  
    6 |      mut req := http.Request{url: url}
    7 |      req.add_header(http.CommonHeader.x_forwarded_for, ip)
      |                                                        ~~
    8 |  
    9 |      res := req.do()!
    ```

**Comment by JalonSolov** [comment]
Because they are 2 distinct types.  It would be like trying to return a `string-int`.  There is no such thing.

**Comment by JalonSolov** [comment]
Because a result either returns a concrete value or an error.  An option is not a concrete value because it can _also_ be one of 2 things... a valid value, or `none`.

**Comment by demostanis** [comment]
so there is no way of expressing what i want in V?

**Comment by JalonSolov** [comment]
No, not the way you want.  However, if we knew exactly what you want, perhaps a different way could be suggested.

**Comment by demostanis** [comment]
I have to fetch an API returning JSON. The response might contain a user. I want to return an optional user, while handling any error in the calling function.

**Comment by JalonSolov** [comment]
The simplest thing there would be to decode the JSON to a struct with an optional field.
```v
    user ?string // or whatever...
```
By making the field optional, it will either have the user decoded from the JSON, or it will be `none` if it wasn't passed back.

Then return `!<struct name>` instead of a simple string.

**Comment by demostanis** [comment]
But I only have one field? Do I really have to make a struct..?

**Comment by JalonSolov** [comment]
That's the only way I can think of to get what you want.

You really will only either get a single string with a user name, or nothing at all?  That sounds bizarre...

**Comment by demostanis** [comment]
The API returns what user is logged on a computer, so yes

**Comment by JalonSolov** [comment]
Then it should be even simpler.  Don't bother with a struct, or JSON decoding, or anything else.  Check to see what is returned.  If it is "" (or however it returns something that doesn't exist), then return `error('none')` and check for that in the `or` block in the caller.

**Comment by demostanis** [comment]
whats the point of having an option type we can do error('none') then?

**Comment by JalonSolov** [comment]
That is `'none'` as a string, not `none` the type.

**Comment by JalonSolov** [comment]
It doesn't have to be `error('none')` - it should be whatever makes more sense to you.  Other examples:
```v
error('no user logged in')
error('no such user')
error('n/a')
error('say what??')
error("didn't get nuttin'")
...
```

**Comment by demostanis** [comment]
yes, but it's not an error, it's an optional value..
what i meant is why does V have an option type if an error can be used instead?

**Comment by JalonSolov** [comment]
Because `none` is not always an error.  It might be completely expected.  For example, if you ask for an array of things, and there aren't any, instead of getting back an empty array and checking for that, you can just do an Option return and the `or` will catch the `none`.

**Comment by demostanis** [comment]
well in my code having no user is completly expected, yet i have to use a result.
maybe options inside results should be supported?

**Comment by JalonSolov** [comment]
Option/Result used to be one combined thing.

Then a lot of people complained about having to do extra checks in the `or` block to decide if the return was an error or `none`.  So it was split into 2 separate types.

This is what we have now, and it is unlikely to go back to what it was before.

**Comment by demostanis** [comment]
im not saying results should be options, im saying V should support results inside options or options inside results, just like any other normal type, like a Result<Option<T>> in Rust
