### ISSUE TITLE
Returning a type alias

### ISSUE THREAD

**Issue by ntrel** [vlang/v#213]
I tried a workaround for returning an optional pointer (until `?*T` is supported):
```rust
type P * int

fn f() P?
{
  i:=5
  p:=&i
  return p
}
```
This gives:
> expected type `Option_P`, but got `int`

Changing f to return a `type Int int` gives:
> expected type `Int`, but got `int`

BTW I think using `=` for type aliases `type New = Old` is clearer. (Also ATM vfmt puts a space after the *).

**Comment by medvednikov** [comment]
`type Foo Bar` syntax is consistent with Go. I want the language to be easy to use for Go developers. 

`vfmt` needs a lot of work. So do optionals, and interfaces :)

**Comment by ntrel** [comment]
> type Foo Bar syntax is consistent with Go.

Go doesn't support generics, so we might want a clearer syntax (e.g. type templates `type Ptr<T> = *T`).

> I want the language to be easy to use for Go developers.

So long as valid Go code means the same or produces a clear error, Go developers should be fine. In this case they would get 'expected `=` after identifier `P`'.

> vfmt needs a lot of work. So do optionals, and interfaces :)

Note: This bug is not related to optionals or interfaces ;-)

**Comment by medvednikov** [comment]
> This bug is not related to optionals

Yes it is. You are trying to return a value from a function that returns an optional, and it doesn't work.

**Comment by ntrel** [comment]
I found it when returning an optional, but I then wrote about changing the return type to `Int` - optionals aren't required to trigger the bug:
```rust
type Int int

fn f() Int
{
  return 5
}
```
> expected type `Int`, but got `int`

**Comment by medvednikov** [comment]
Ah, sorry missed the `Changing f to return a type Int int gives`

You are right.

**Comment by ntrel** [comment]
It seems type aliases don't implicitly convert to their aliased type, and vice versa. Writing `return Int(5)` works. So this bug is probably invalid.
