### ISSUE TITLE
"c := chan !string{}"     ->     error: unexpected token `!`, expecting `{`

### ISSUE THREAD

**Issue by Yaisis** [vlang/v#21337]
### Describe the bug

The expression is not compiled:

`c := chan !string{}`

Returns an error:

```
error: unexpected token `!`, expecting `{`
    1 | 
    2 | fn main() {
    3 |     c := chan !string{}
      |               ^

```

### Reproduction Steps

``` v
fn main() {
	c := chan !string{}
	println(c.len)
}
```

### Expected Behavior

a working program

### Current Behavior

```
v run test.v
test.v:3:12: error: unexpected token `!`, expecting `{`
    1 | 
    2 | fn main() {
    3 |     c := chan !string{}
      |               ^
    4 |     println(c.len)
    5 | }

```

### V version

V 0.4.5 f124d03

### Environment details (OS name and version, etc.)

OS: linux, "Manjaro Linux"
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Delta456** [comment]
I don't think result channel types should be working.

**Comment by medvednikov** [comment]
I agree. `!Type` should be handled immediately, not passes over a channel

**Comment by Delta456** [comment]
> Just a clearer error that explains it's not allowed.

Currently, optional channels ain't supported as well

```
file.v:2:12: error: unexpected token `?`, expecting `{`
    1 | fn main() {
    2 |     c := chan ?string{}
      |               ^
    3 |     println(c.len)
    4 | }
```
