### ISSUE TITLE
vweb Form not working when running with `-prod` flag

### ISSUE THREAD

**Issue by bramaudi** [vlang/v#21349]
### Describe the bug

Cannot get form input value in vweb that compiled with `-prod` flag using TCC (default) & GCC but not with clang.

### Reproduction Steps

Using official vweb example: v/examples/vweb/file_upload
These command behaves same:
1. `v -prod run .`
2. `v -cc gcc -prod run .`

### Expected Behavior

After submit a form in browser:
![image](https://github.com/vlang/v/assets/14371119/fe22cf9f-f7bf-4fc5-bfc3-a403aec14a1b)

Result in terminal:
```bash
[Vweb] Running app on http://localhost:8082/
[Vweb] We have 3 workers
[./file_uploading.v:34] app.form: {'content1': 'abc', 'content2': 'xyz'}
```

### Current Behavior

After submit a form in browser:
![image](https://github.com/vlang/v/assets/14371119/ce09ddca-e26d-4241-92c3-c198869fb4a6)

Result in terminal:
```bash
[Vweb] Running app on http://localhost:8082/
[Vweb] We have 3 workers
```

### Additional Information/Context

This did not happen when I was compiling using clang after I newly installed `clang` and `llvm-libs` package in my linux, I'm not sure but I guess my tcc & gcc are missing some libs.

### V version

0.4.5 3b0c620

### Environment details (OS name and version, etc.)

V full version: V 0.4.5 3b0c620
OS: linux, "EndeavourOS Linux"
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz

getwd: /home/user/.v/examples/vweb/file_upload
vexe: /home/user/.v/v
vexe mtime: 2024-04-23 02:11:55

vroot: OK, value: /home/user/.v
VMODULES: OK, value: /home/brama/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.44.0
Git vroot status: Error: fatal: bad revision 'HEAD'
.git/config present: true

CC version: cc (GCC) 13.2.1 20230801
thirdparty/tcc: N/A
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
Try `veb` instead.  `vweb` will likely be kept around for legacy projects (at least for a while), but `veb` is the new, more feature-filled project (used to be `x.vweb`).
