### ISSUE TITLE
Function returning structure is not recognized in the place of structure

### ISSUE THREAD

**Issue by avitkauskas** [vlang/v#2135]
**V version:** V 0.1.20 8cbfd7a
**OS:** Mac OS

**What did you do?**
```
struct st {
    s string
    t string
}

fn new_st(s string) st {
    return st{s: s}
}

fn get_st(s string) st {
    return {new_st(s) | t: "t"}
}

fn main() {
    s := get_st("s")
    println(s)
}
```

**What did you expect to see?**
```
{
	s: s
	t: t
}
```
 
**What did you see instead?**
```
test1.v:11:19: unknown variable `new_st`
```

**Comment by avitkauskas** [comment]
If you change to:
```
fn get_st(s string) st {
    mut r := new_st(s) 
    return {r | t: "t"}
}
```
you get:
```
test1.v:12: `r` declared and not used
test1.v:12:2: `r` is declared as mutable, but it was never changed
```

**Comment by avitkauskas** [comment]
If changed to:
```
fn get_st(s string) st {
    mut r := new_st(s) 
    r = {r | t: "t"}
    return r
}
```
it works fine.

**Comment by avitkauskas** [comment]
The structure is printed as"
```
{
	s: s
	t: t

}
```
Note the extra empty line before the closing `}`

**Comment by medvednikov** [comment]
Thanks @avitkauskas 

This was a recent change. Will fix.

**Comment by medvednikov** [comment]
Regarding the `unknown variable` error. Looks like the assoc operator (`|`) only works with variables, not expressions.

Will fix.

**Comment by avitkauskas** [comment]
Yes, but I think there is a general problem in V copiler: it's quite "simple" without the AST, but that makes type checking and other things non-systemic, ad-hoc, so it's difficult to account for all the different situations and these king of problems and regressions will be only increasing in the future. 
I love V, but I would also want it to be reliable and very well defined. I am not so much into development that I coud do that :) but I am sure you could - if only you slow down a little, look arrond and go "back to the drawing board". 
Please take this as a very friendly comment - I admire what you did so far, but I really think V iplemenmtation should have more structure to become really successful and mainstrem in the future.
You still aim for 1.0 in December, but I stop and say that this December be in 2021 (and that still be _very_ quick). It's better to take some time but come out with the really robust language that be very quick with something that would brake trust in such a nice language.
Sorry, than was was long and a bit unexpected ranting, but this bad feeling grows inside, so I thought I should share it :(

**Comment by medvednikov** [comment]
The parser is simply looking for a variable instead of an expression, this has nothing to do with an AST.

V is a small language, and since its main backend is C, the hardest part of code generation and optimization is done. So 1.0 this year is doable, and I see no reason to delay this by years.

It has already been cleaned up and stabilized a lot, and it's going to be very neat and stable by the end of December.

**Comment by medvednikov** [comment]
I started working on it, and it can't be done without changing `|` to a different token.

What do you think about `with`?

**Comment by avitkauskas** [comment]
In Python `with` is used in some different way (and maybe in some other languages). Like:
```python
with expression [as variable]:
    with-block
```
I don't know if it's really important, but for those coming from (or also working in) Python this usage in V could be a bit strange. But well, it's V, not Python :)

Alternatives:
```v
r = {r  and t: "t"}
```
```v
r = {r  <| t: "t"}
```

Maybe `and` is not very much semantically correct here (maybe confused with logical and?), but V already has `or`as keyword, so perhaps `and` could also have it's place in the language?

**Comment by dumblob** [comment]
`<|` looks the best to me

**Comment by tomByrer** [comment]
> `<|` looks the best to me

Looks too much like a flipped [Pipeline operator](https://github.com/tc39/proposal-pipeline-operator) used in UNIX, JS, F#, OCaml, Elm, etc.  I understand you want to combine results, why not use a verb instead? eg:
```
return {merge(new_st(s), t: "t"})`
```

**Comment by AlexDyukov** [comment]
`v is simple` wont if pipeline operator will extend or changed. Documentation has only one examples for pipeline operator:
```
fn register(u User) User {
	return { u | is_registered: true }
}
user = register(user)
```
Pipeline operator solves the problem when "we want to get struct with some modified properties". Without pipeline operator we have to make mut in struct:
```
struct User {
    name string
mut:
    is_registered bool
}
```
or copy-paste every parameter in new obj:
```
struct User {
    name string
    is_registered bool
}
fn main() {
    u := User{name: "Sam", is_registered: true}
    nu := User{name: "Ellie", is_registered: u.is_registered}
    println(u)
    println(nu)
}
```
Both variants looks bad. First requires mutable parameters, so everyone can modify it and breaks our internal logic. The second could limits performance: create + multiply rewrites unstead of copy+one rewrite with pipeline operator

IMHO let pipeline operator stay in current way (only work with variables):
1) change error to
> test1.v:11:19: unknown variable `new_st(s)`
2) add info to documentation "how it works" or error describe

We wont get an issue with:
```
fn get_st(s string) St {
    nst := new_st(s)
    return {nst | t: "t"}
}
```

**Comment by crthpl** [comment]
With updated code, it now says:
`expression is not an lvalue`.
