### ISSUE TITLE
compiler: Cyclic reference in struct will lead to DGNAC

### ISSUE THREAD

**Issue by l8atnight** [vlang/v#2136]
F:\v\mylib>..\v mexparser.v
warning: mexparser.v:323: `b` declared and not used
warning: mexparser.v: the following imports were never used:
 * strings
**V error: error: cgen.sort_structs() DGNAC.**
please create a new issue here: https://github.com/vlang/v/issues and tag @joe-conigliaro

F:\v\mylib>

**Comment by lutherwenxu** [comment]
Can you please provide the file you tried to compile?

**Comment by l8atnight** [comment]
dink around file
[mexparser.zip](https://github.com/vlang/v/files/3665371/mexparser.zip)

**Comment by lutherwenxu** [comment]
It would seem like it's because in Line 34, you referred to the struct itself. It is not possible to do so as it'll cause a cyclic dependency.
```
 26 struct Rulecont { // use in rules
 27 mut:
 28  connecval Connect
 29  attribute string
 30  confval   f64
 31  valplace  string
 32  funcproc  []string
 33  typplace  types
 34  orplace   Rulecont //<- Here. You cannot use the struct inside of itself.
 35  calccf    f64
 36  rulenum   string
 37 }
```

I do agree that the error message could be done better tho.

**Comment by joe-conigliaro** [comment]
I will think of best way to deal with this!

**Comment by l8atnight** [comment]
please fix it and do the multi dimensional arrays.
