### ISSUE TITLE
Error when UPgrade

### ISSUE THREAD

**Issue by milen-prg** [vlang/v#21381]
### Describe the bug

I regularly update my V (Windows 11 Pro 64 bit), but the last:

C:\v>git pull
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), 849 bytes | 212.00 KiB/s, done.
From https://github.com/vlang/v
   903a585e9..e4bbd73da  master         -> origin/master
 * [new tag]             weekly.2024.18 -> weekly.2024.18
Already up to date.

C:\v>v up
Updating V...
> make.bat failed:
> make output:
Updating TCC
 > Syncing TCC from https://github.com/vlang/tccbin

Updating vc...
 > Sync with remote https://github.com/vlang/vc

Building V...
 > Attempting to build "./v_win_bootstrap.exe" (from v_win.c) with "thirdparty/tcc/tcc.exe"
 > Compiling "./v.exe" with "./v_win_bootstrap.exe"
vlib/v/pref/pref.c.v:405:9: error: undefined ident: `current_args`
  403 |                 if command_pos == -1 {
  404 |                     // Version flags after a command are intended for the command, not for V itself.
  405 |                     if current_args.len > 1 && arg == '-v' {
      |                        ~~~~~~~~~~~~
  406 |                         // With additional args after the `-v` flag, it toggles verbosity, like Clang.
  407 |                         // E.g.: `v -v` VS `v -v run examples/hello_world.v`.
vlib/v/pref/pref.c.v:405:22: error: `current_args` does not return a value
  403 |                 if command_pos == -1 {
  404 |                     // Version flags after a command are intended for the command, not for V itself.
  405 |                     if current_args.len > 1 && arg == '-v' {
      |                                     ~~~
  406 |                         // With additional args after the `-v` flag, it toggles verbosity, like Clang.
  407 |                         // E.g.: `v -v` VS `v -v run examples/hello_world.v`.
vlib/v/pref/pref.c.v:405:22: error: left operand for `&&` is not a boolean
  403 |                 if command_pos == -1 {
  404 |                     // Version flags after a command are intended for the command, not for V itself.
  405 |                     if current_args.len > 1 && arg == '-v' {
      |                                     ~~~~~~~
  406 |                         // With additional args after the `-v` flag, it toggles verbosity, like Clang.
  407 |                         // E.g.: `v -v` VS `v -v run examples/hello_world.v`.
vlib/v/pref/pref.c.v:405:22: error: non-bool type `void` used as if condition
  403 |                 if command_pos == -1 {
  404 |                     // Version flags after a command are intended for the command, not for V itself.
  405 |                     if current_args.len > 1 && arg == '-v' {
      |                                     ~~~~~~~~~~~~~~~~~~~~~~
  406 |                         // With additional args after the `-v` flag, it toggles verbosity, like Clang.
  407 |                         // E.g.: `v -v` VS `v -v run examples/hello_world.v`.
 > Clang not found
 > Attempting to build "./v_win_bootstrap.exe" (from v_win.c) with GCC
./vc/v_win.c:514: No include path in which to find inttypes.h
./vc/v_win.c:527: No include path in which to find stddef.h
./vc/v_win.c:844: No include path in which to find stdio.h
./vc/v_win.c:845: No include path in which to find stdlib.h
./vc/v_win.c:846: No include path in which to find string.h
./vc/v_win.c:848: No include path in which to find stdarg.h
./vc/v_win.c:873: #error "Unknown architecture endianness"
./vc/v_win.c:918: No include path in which to find windows.h
./vc/v_win.c:920: No include path in which to find io.h
./vc/v_win.c:921: No include path in which to find direct.h
./vc/v_win.c:923: No include path in which to find signal.h
./vc/v_win.c:990: No include path in which to find stdint.h
./vc/v_win.c:1135: No include path in which to find float.h
./vc/v_win.c:1150: No include path in which to find time.h
./vc/v_win.c:1165: No include path in which to find time.h
./vc/v_win.c:1191: No include path in which to find stddef.h
./vc/v_win.c:1192: No include path in which to find stdint.h
./vc/v_win.c:1193: No include path in which to find windows.h
./vc/v_win.c:1548: No include path in which to find winsock2.h
./vc/v_win.c:1563: No include path in which to find sys\stat.h
./vc/v_win.c:1568: No include path in which to find errno.h
./vc/v_win.c:1581: No include path in which to find process.h
./vc/v_win.c:1596: No include path in which to find sys\utime.h
./vc/v_win.c:1611: No include path in which to find windows.h
./vc/v_win.c:1626: No include path in which to find signal.h
./vc/v_win.c:1641: No include path in which to find synchapi.h
./vc/v_win.c:1656: No include path in which to find time.h
In most cases, compile errors happen because the version of GCC installed is too old
2.95

Backend compiler error

Exiting from error
ERROR: please follow the instructions in https://github.com/vlang/v/wiki/Installing-a-C-compiler-on-Windows

Current V version: V 0.4.5 903a585, timestamp: 2024-04-25 14:14:45 +0300
Recompiling V *failed*.
Try running `make.bat` .

C:\v>make.bat
Updating TCC
 > Syncing TCC from https://github.com/vlang/tccbin

Updating vc...
 > Sync with remote https://github.com/vlang/vc

Building V...
 > Attempting to build "./v_win_bootstrap.exe" (from v_win.c) with "thirdparty/tcc/tcc.exe"
 > Compiling "./v.exe" with "./v_win_bootstrap.exe"
vlib/v/pref/pref.c.v:405:9: error: undefined ident: `current_args`
  403 |                 if command_pos == -1 {
  404 |                     // Version flags after a command are intended for the command, not for V itself.
  405 |                     if current_args.len > 1 && arg == '-v' {
      |                        ~~~~~~~~~~~~
  406 |                         // With additional args after the `-v` flag, it toggles verbosity, like Clang.
  407 |                         // E.g.: `v -v` VS `v -v run examples/hello_world.v`.
vlib/v/pref/pref.c.v:405:22: error: `current_args` does not return a value
  403 |                 if command_pos == -1 {
  404 |                     // Version flags after a command are intended for the command, not for V itself.
  405 |                     if current_args.len > 1 && arg == '-v' {
      |                                     ~~~
  406 |                         // With additional args after the `-v` flag, it toggles verbosity, like Clang.
  407 |                         // E.g.: `v -v` VS `v -v run examples/hello_world.v`.
vlib/v/pref/pref.c.v:405:22: error: left operand for `&&` is not a boolean
  403 |                 if command_pos == -1 {
  404 |                     // Version flags after a command are intended for the command, not for V itself.
  405 |                     if current_args.len > 1 && arg == '-v' {
      |                                     ~~~~~~~
  406 |                         // With additional args after the `-v` flag, it toggles verbosity, like Clang.
  407 |                         // E.g.: `v -v` VS `v -v run examples/hello_world.v`.
vlib/v/pref/pref.c.v:405:22: error: non-bool type `void` used as if condition
  403 |                 if command_pos == -1 {
  404 |                     // Version flags after a command are intended for the command, not for V itself.
  405 |                     if current_args.len > 1 && arg == '-v' {
      |                                     ~~~~~~~~~~~~~~~~~~~~~~
  406 |                         // With additional args after the `-v` flag, it toggles verbosity, like Clang.
  407 |                         // E.g.: `v -v` VS `v -v run examples/hello_world.v`.
 > Clang not found
 > Attempting to build "./v_win_bootstrap.exe" (from v_win.c) with GCC
./vc/v_win.c:514: No include path in which to find inttypes.h
./vc/v_win.c:527: No include path in which to find stddef.h
./vc/v_win.c:844: No include path in which to find stdio.h
./vc/v_win.c:845: No include path in which to find stdlib.h
./vc/v_win.c:846: No include path in which to find string.h
./vc/v_win.c:848: No include path in which to find stdarg.h
./vc/v_win.c:873: #error "Unknown architecture endianness"
./vc/v_win.c:918: No include path in which to find windows.h
./vc/v_win.c:920: No include path in which to find io.h
./vc/v_win.c:921: No include path in which to find direct.h
./vc/v_win.c:923: No include path in which to find signal.h
./vc/v_win.c:990: No include path in which to find stdint.h
./vc/v_win.c:1135: No include path in which to find float.h
./vc/v_win.c:1150: No include path in which to find time.h
./vc/v_win.c:1165: No include path in which to find time.h
./vc/v_win.c:1191: No include path in which to find stddef.h
./vc/v_win.c:1192: No include path in which to find stdint.h
./vc/v_win.c:1193: No include path in which to find windows.h
./vc/v_win.c:1548: No include path in which to find winsock2.h
./vc/v_win.c:1563: No include path in which to find sys\stat.h
./vc/v_win.c:1568: No include path in which to find errno.h
./vc/v_win.c:1581: No include path in which to find process.h
./vc/v_win.c:1596: No include path in which to find sys\utime.h
./vc/v_win.c:1611: No include path in which to find windows.h
./vc/v_win.c:1626: No include path in which to find signal.h
./vc/v_win.c:1641: No include path in which to find synchapi.h
./vc/v_win.c:1656: No include path in which to find time.h
In most cases, compile errors happen because the version of GCC installed is too old
2.95

Backend compiler error

Exiting from error
ERROR: please follow the instructions in https://github.com/vlang/v/wiki/Installing-a-C-compiler-on-Windows

C:\v>

### Reproduction Steps

Just try:
v up

### Expected Behavior

Regularly the new version installs.

### Current Behavior

Now many errors.

### V version

V 0.4.5 903a585 

### Environment details (OS name and version, etc.)

C:\v>v doctor
V full version: V 0.4.5 e30af86.903a585
OS: windows, Microsoft Windows 11 Pro v22631 64-bit
Processor: 16 cpus, 64bit, little endian,

getwd: C:\v
vexe: C:\v\v.exe
vexe mtime: 2024-04-25 12:18:22

vroot: OK, value: C:\v
VMODULES: OK, value: C:\Users\User\.vmodules
VTMP: OK, value: C:\Users\User\AppData\Local\Temp\v_0

Git version: git version 2.43.0.windows.1
Git vroot status: weekly.2024.18-8-ge4bbd73d
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc status: thirdparty-windows-amd64 b99a453d

C:\v>

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
Try `.\make` in the V dir.  That should get everything working again.

**Comment by milen-prg** [comment]
@JalonSolov , I tried this, all now is OK:

C:\v>git pull
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (44/44), done.
remote: Total 58 (delta 44), reused 44 (delta 44), pack-reused 14
Unpacking objects: 100% (58/58), 13.07 KiB | 123.00 KiB/s, done.
From https://github.com/vlang/v
   e4bbd73da..12ca2f253  master     -> origin/master
Updating e4bbd73da..12ca2f253
Fast-forward
 .github/workflows/bootstrapping_ci.yml |  8 +++-----
 .github/workflows/other_ci.yml         | 22 ++++++++++++++++++----
 cmd/tools/vdoc/tests/vdoc_file_test.v  | 43 ++++++++++++++++++++++++++-----------------
 vlib/v/builder/cc.v                    | 25 +++++++++++--------------
 vlib/v/pref/pref.c.v                   |  2 +-
 vlib/v/pref/pref_test.v                | 11 +++++++++--
 6 files changed, 68 insertions(+), 43 deletions(-)

C:\v>.\make
Updating TCC
 > Syncing TCC from https://github.com/vlang/tccbin

Updating vc...
 > Sync with remote https://github.com/vlang/vc
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
Receiving objects: 100% (2/2), 1.02 MiB | 3.41 MiB/s, done.0Receiving objects: 100% (2/2)

Resolving deltas: 100% (1/1), done.
Updating files: 100% (2/2), done.

Building V...
 > Attempting to build "./v_win_bootstrap.exe" (from v_win.c) with "thirdparty/tcc/tcc.exe"
 > Compiling "./v.exe" with "./v_win_bootstrap.exe"
> C compiler cmd: "thirdparty/tcc/tcc.exe" "@C:\Users\User\AppData\Local\Temp\v_0\v_up.exe.tmp.c.rsp"
> C compiler response file "C:\Users\User\AppData\Local\Temp\v_0\v_up.exe.tmp.c.rsp":
  -Bthirdparty/tcc -fwrapv -g -o "C:\\v\\./v_up.exe" -Wl,-stack=16777216 -Werror=implicit-function-declaration -I "C:\\v\\thirdparty\\stdatomic\\win" "C:\\Users\\User\\AppData\\Local\\Temp\\v_0\\v_up.exe.tmp.c" -std=c99 -D_DEFAULT_SOURCE -municode -bt25 -ldbghelp -lws2_32 -ladvapi32 -lshell32
Your `tcc` is working. Good - it is much faster at compiling C source code.
 > V built successfully
 > To add V to your PATH, run `./v.exe symlink`.

V version: V 0.4.5 12ca2f2

C:\v>

Thank, you!!!

P.S. When update my V, is it necessary to do "git pull"? Seems that the "v up" only does the work, but I want my documentation to be updated too. Can "git pull" before "v up" to break something?

**Comment by JalonSolov** [comment]
`git pull` should be fine every time.  `v up` does do a pull of the source, but it does it differently than a full `git pull`.

It shouldn't be necessary to do - I just got used to it very early on.  :-)
