### ISSUE TITLE
Cannot instantiate interface

### ISSUE THREAD

**Issue by gercinojr** [vlang/v#21420]
### Describe the bug

The program does not compile

### Reproduction Steps

1. Save the below code in a file ./tmp/main.v
2. `cd tmp/`
3. `v run .`

```
interface IFoo {}

fn (a IFoo) show() {
	println('show!')
}

struct SFoo{}

fn (sf SFoo) bla() {
	f := IFoo{}
	f.show()
}

fn main() {
	println('Hello world!')
}
```

### Expected Behavior

The same code works if you replace `interface` with `struct`.
The program output should show `Hello world`.

### Current Behavior

throws the below error
```
main.v:10:7: error: cannot instantiate interface `IFoo`
    8 | 
    9 | fn (sf SFoo) bla() {
   10 |     f := IFoo{}
      |          ~~~~~~
   11 |     f.show()
   12 | }

```

### V version

V 0.4.5 f0abc45

### Environment details (OS name and version, etc.)

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.3
DISTRIB_CODENAME=una
DISTRIB_DESCRIPTION="Linux Mint 20.3 Una"
NAME="Linux Mint"
VERSION="20.3 (Una)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.3"
VERSION_ID="20.3"
VERSION_CODENAME=una
UBUNTU_CODENAME=focal
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
That's because interfaces in V aren't "real" objects.  They are contracts that structs can fulfill.

**Comment by spytheman** [comment]
Doing `f := IFoo( SFoo{} )` for example will avoid the problem, by creating a `SFoo{}` instance, and converting it to an interface value.

**Comment by gercinojr** [comment]
Thanks to you for the explanation.  The error message did not explain to me why the error occurred.  Maybe a more detailed error message in the next versions.  I'm loving this language.  Very simple and powerful.  Thank you again.
