### ISSUE TITLE
Single array int gave error get_type() bad type

### ISSUE THREAD

**Issue by nanangarsyad** [vlang/v#2142]
**V version: 0.1.20 14a8d4a** 
**OS: MacOS 10.13** 

**What did you do?**
Wrote this line of code
```
fn main() {
  mut a := [1]
  a << 2
}
```

**What did you expect to see?**
[1,2]
 
**What did you see instead?**
get_type() bad type

**Comment by lutherwenxu** [comment]
Cannot reproduce on `0.1.20-125-g802da8f` (Commit 802da8f).
Testing code: ```
fn main() {
	mut a := [1]
	a << 2
	println(a)
}
```
Result is as expected: ```
$ v run a.v
[1, 2]
```

**Comment by medvednikov** [comment]
Fixed.
