### ISSUE TITLE
A compilation error is thrown after compiling the Custom Iterators example in the For Loop documentation

### ISSUE THREAD

**Issue by ookami-001** [vlang/v#21486]
### Describe the issue

**Operating System used:** [Linux Mint 21.2 Cinnamon Edition](https://www.linuxmint.com/edition.php?id=305)
**Linux Kernel:** 5.15.0-105-generic
**V Language version installed:** V 0.4.5 6a6d8e0
**Code Editor used:** [Visual Studio Code](https://code.visualstudio.com/) with the [V Programming Language plugin](https://marketplace.visualstudio.com/items?itemName=vlanguage.vscode-vlang) 

The code example was stored on my machine in a file named **main.v**. The contents of the file were as follows:

```v
module main

struct SquareIterator {
	arr []int
mut:
	idx int
}

fn main() {

	fn (mut iter SquareIterator) next() ?int {
		if iter.idx >= iter.arr.len {
			return none
		}
		defer {
			iter.idx++
		}
		return iter.arr[iter.idx] * iter.arr[iter.idx]
	}

	nums := [1, 2, 3, 4, 5]
	
	iter := SquareIterator{
		arr: nums
	}

	for squared in iter {
		println(squared)
	}
	
}
```
After I tried compiling the code above using the following command:

```shell
v run .
```  
I got the following error:

```shell
src/main.v:11:35: error: unexpected token `(` after anonymous function signature, expecting `{`
    9 | fn main() {
   10 | 
   11 |     fn (mut iter SquareIterator) next() ?int {
      |                                      ^
   12 |         if iter.idx >= iter.arr.len {
   13 |             return none
```  

### Links

https://github.com/vlang/v/blob/master/doc/docs.md#custom-iterators
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
Your code does not match the docs, since you have wrapped most of it inside a `fn main`.

The `next()` function must be outside `main`, as it's own function, for this to work.

If you look more closely at the docs, you'll see there's no `main` at all - it is not needed, as this is an example of "script mode" V.

**Comment by ookami-001** [comment]
You are right. After I changed the contents of the **main.v** file to the following:

```v
module main

struct SquareIterator {
	arr []int
mut:
	idx int
}

fn (mut iter SquareIterator) next() ?int {
	if iter.idx >= iter.arr.len {
		return none
	}
	defer {
		iter.idx++
	}
	return iter.arr[iter.idx] * iter.arr[iter.idx]
}

fn main() {

	nums := [1, 2, 3, 4, 5]
	
	iter := SquareIterator{
		arr: nums
	}

	for squared in iter {
		println(squared)
	}
	
}
``` 
the code compiled successfully and produced the expected outcome:

```shell
1
4
9
16
25
``` 
Still, I feel that this will catch many new learners off guard as many will probably do exactly as I did by including the `next() `function inside the `main() `function. I strongly think that example in the documentation needs to be edited to look like the code I posted above to avoid potential confusion from new learners. The more people who fall in love with V the better and clearer documentation is one way of achieving that.

I will look out for more issues like this as I continue my learning of V.

**Comment by JalonSolov** [comment]
The proper edit to add the `main` function would be
```v
module main

struct SquareIterator {
	arr []int
mut:
	idx int
}

fn (mut iter SquareIterator) next() ?int {
	if iter.idx >= iter.arr.len {
		return none
	}
	defer {
		iter.idx++
	}
	return iter.arr[iter.idx] * iter.arr[iter.idx]
}

fn main() {
	nums := [1, 2, 3, 4, 5]
	
	iter := SquareIterator{
		arr: nums
	}

	for squared in iter {
		println(squared)
	}
}
```
as V doesn't allow you to wrap a named function inside another function (hence the error message you received):
```
error: unexpected token `(` after anonymous function signature, expecting `{`
```
Only anonymous functions can be declared inside other functions.

It's a toss-up whether this would make a difference... may people would likely try running the example as-is, rather than adding to it, just to see what it would do.
