### ISSUE TITLE
os.get_raw_line() doesn't consume newline (Win 10)

### ISSUE THREAD

**Issue by luoheng23** [vlang/v#2149]
**V version:** 
V 0.1.20 802da8f
**OS:** 
win10
**What did you do?**
Run the file:
```v
import os

m := os.get_raw_line()
print("m: " + m)
t := os.get_raw_line()
print("t: " + t)
```
**What did you expect to see?**
input `hello` and input `world`, output is
```v
m: hello
t: world
```
**What did you see instead?**
After inputing `hello`, the program directly stopped, and output is
```v
m: hello
t:
```
It seems the `os.get_raw_line()` doesn't consume the newline on win10 (this program works well on linux).
And this leads to a repl problem:
```v
>>> h := 2
>>> >>>
```
The `os.get_raw_line()` will result in double `>>>` in the repl mode.

**Comment by vitalyster** [comment]
Works for me with MSVC build. Do you use GCC?

**Comment by vitalyster** [comment]
Just tested with GCC, confirmed, I see the same as you

**Comment by Ivo-Balbaert** [comment]
This seems the same bug as I get with os_getline (which calls os_get_raw_line) on Windows. The following program:

import os

for {
    s := os.get_line()
    println('***$s***')
    if s ==''  { break }
}

gives as output after one line input abc:

abc
***abc***
******

So after a first successful get_line, it runs automatically (doesn't wait for input) a second time, and then obviously gets an empty input ''.
This error was not present in version 0.1.17.
