### ISSUE TITLE
rename os.getwd -> os.getcwd

### ISSUE THREAD

**Issue by hholst80** [vlang/v#21492]
### Describe the feature

"getwd" is a deprecated C name and "getcwd" will feel much more familiar to users of the standard library.

![image](https://github.com/vlang/v/assets/6200749/abfa148f-784f-45d4-bdf8-090597d5788a)

### Use Case

To support Python and C developers coming to V lang the standard library should follow common conventions.

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

0.4.5

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.5 a1f3624.2e64e28
OS: linux, "Artix Linux"
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz

getwd: /home/root
vexe: /home/root/Apps/v/v
vexe mtime: 2024-05-05 20:51:43

vroot: OK, value: /home/root/Apps/v
VMODULES: OK, value: /home/root/.vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.45.0
Git vroot status: weekly.2024.18.2-13-gc14c803a (67 commit(s) behind V master)
.git/config present: true

CC version: cc (GCC) 13.2.1 20240417
thirdparty/tcc status: thirdparty-linux-amd64 40e5cbb5

```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
It you're going to rename it, it should be renamed to a V name, not a C name.

`get_current_dir` would be more V style.

**Comment by hholst80** [comment]
having a 'style' that is idiomatic to V is ofc most important. 

just as a side note, as these things does not come for free: naming things is the hardest problem in computer science and I see any kind of preexisting naming convention as a gift from God. ;-)

![image](https://github.com/vlang/v/assets/6200749/8d5ed31e-5820-4404-a60f-0a5cedf618c1)

**Comment by medvednikov** [comment]
V uses Go's stdlib as the golden standard:

https://pkg.go.dev/os#Getwd

It should stay os.getwd
