### ISSUE TITLE
Provide a live-chat for V community

### ISSUE THREAD

**Issue by gslicer** [vlang/v#2151]
I think it will give V a bit more drive if V users can talk in real time and exchange their experiences and discuss more interactively (without bloating the issue-tickets with quoted comments)

As long github does not offer a chat on repo-level there could be a chat feature within vlang.io web-site or external resource

Therefore for the time being I've registered an IRC channel:
 `#V` on `irc.abjects.net:9999` (SSL port)

See you there!

**Comment by Delta456** [comment]
There's already a discord server. The link can be found in README.md.

**Comment by medvednikov** [comment]
https://discord.gg/n7c74HM

:)

**Comment by gslicer** [comment]
@medvednikov  "You must verify your identity by phone before you can send messages in this server" - is this a bad Joke?

**Comment by medvednikov** [comment]
Protection against spam bots.
