### ISSUE TITLE
/v/examples/hot_reload/message.tmp.c:4679: undefined reference to `os__file_last_mod_unix'

### ISSUE THREAD

**Issue by Kalimehtar** [vlang/v#2152]
**V version:** 
Last from github
**OS:** 
Linux

**What did you do?**
$ cd v/examples/hot_reload
$ ../../v -live message.v

**What did you expect to see?**
compiled file message
 
**What did you see instead?**
/usr/bin/ld: /tmp/ccQYZybL.o: in function `reload_so':
v/examples/hot_reload/message.tmp.c:4679: undefined reference to `os__file_last_mod_unix'
/usr/bin/ld: /home/monk/Про...
(Use `v -debug` to print the entire error message)

V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by spytheman** [comment]
It is a known bug (hot code reloading uses the os and time modules internally).
A temporary workaround for it, was done in #2121 ( merged as a4cbe78, several minutes ago).
Thanks for reporting it.
