### ISSUE TITLE
Undefined bitfield operation on enum alias

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [vlang/v#21531]
### Describe the bug

When I use an alias to an enum with the @[flag] attribute, I cannot use bitfield operations on the alias.

I'm not sure whether this is supposed to work, but I assumed and couldn't find documentation denying or confirming it.

### Reproduction Steps

```V
fn main() {
	
	enum_container := EnumContainer{
		et: .a | .b  // works
	}

	alias_container := AliasContainer{
		at: .a | .b  // fails
	}
}


@[flag]
enum EnumType {
	a
	b
	c
}

struct EnumContainer {
	et EnumType
}

type AliasType = EnumType

struct AliasContainer {
	at AliasType
}
```

### Expected Behavior

The aliased type should behave like the type it aliases.
So the bitfield operations should work in both cases.

### Current Behavior

Compilation fails with

> flag-test.v:8:7: error: undefined operation `AliasType` | `AliasType`
    6 | 
    7 |     alias_container := AliasContainer{
    8 |         at: .a | .b
      |             ~~~~~~~
    9 |     }
   10 | }

### V version

0.4.5

### Environment details (OS name and version, etc.)

V full version: V 0.4.5 c0afe5d.f33b712
OS: linux, Ubuntu 22.04.4 LTS
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Delta456** [comment]
This should work
