### ISSUE TITLE
gdextension

### ISSUE THREAD

**Issue by MMUTFX2053** [vlang/v#21572]
### Describe the feature

a way to interact with the godot game engine, there are already a couple of languages offering libraries to interact with godot, using gdextension

### Use Case

write code for the godot game engine

### Proposed Solution

an gdextension library that allows writing code in v for godot

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

0.4

### Environment details (OS name and version, etc.)

Solus OS
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Larpon** [comment]
https://github.com/jcweaver997/vgdextension

**Comment by MMUTFX2053** [comment]
> https://github.com/jcweaver997/vgdextension

thnx, didn't know somebody already started working on it
