### ISSUE TITLE
V upgrade and downgrade functions

### ISSUE THREAD

**Issue by Avey777** [vlang/v#21580]
### Describe the feature

`v vpgrade :  v up`
`v downgrade: v down 0.4.5`

### Use Case

flutter upgrade
flutter downgrade 3.19.6

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

0.4.6

### Environment details (OS name and version, etc.)

macos
linux
windows
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
`v up` upgrades to the latest.

Run `v run cmd/tools/oldv.v` to see the options for downgrading.
