### ISSUE TITLE
Support placing API files in different folders

### ISSUE THREAD

**Issue by Avey777** [vlang/v#21581]
### Describe the feature

https://github.com/vlang/v/discussions/21196

![image](https://github.com/vlang/v/assets/35259040/f2d215be-d47a-430e-868e-b1fa181fc996)

### Use Case

If I store all api files in a single folder, as the number of apis increases, the organization and management of the files will become very confusing.

### Proposed Solution

![image](https://github.com/vlang/v/assets/35259040/d62585d8-258e-47ab-b26f-28b400d3fc89)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### Version used

0.4.6

### Environment details (OS name and version, etc.)

macos
linux
windows
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Avey777** [comment]
> This would definitely be a breaking change.
> 
> A fundamental aspect of V is that you cannot create methods on structs in other modules.
> 
> This is why all your api methods on the App struct must be in the same module as the file where your App struct is defined.
> 
> Those api methods _could be_ tiny wrappers that simply call functions in other modules, but the main api method definition must be in the same module.

I understand your concerns, but we can consider other solutions to achieve file organization and management in this way.  For large projects this is very important.  No one wants their code directory to be a mess

**Comment by Avey777** [comment]
![image](https://github.com/vlang/v/assets/35259040/868c5e9d-1b07-437c-8034-e9f3a87e661e)
I imported the App and Context structures in the api module, allowing the code and no error message; but when I access this api it will return “404 Not Found”

**Comment by spytheman** [comment]
> I understand your concerns, but we can consider other solutions to achieve file organization and management in this way. For large projects this is very important. No one wants their code directory to be a mess

I understand your desire to organize your code in that way, but it has many disadvantages, in terms of complexity for the compiler.

**Comment by Avey777** [comment]
> > I understand your concerns, but we can consider other solutions to achieve file organization and management in this way. For large projects this is very important. No one wants their code directory to be a mess
> 
> I understand your desire to organize your code in that way, but it has many disadvantages, in terms of complexity for the compiler.

But I did this and the compiler didn't complain; I think this should be fixed.

**Comment by Avey777** [comment]
@spytheman  
Are there any other roundabout ways to achieve similar code organization and management?

**Comment by medvednikov** [comment]
I think this was suggested before. "Virtual submodules" or something. There was a long discussion on GitHub.

**Comment by medvednikov** [comment]
It can be set up via v.mod. I'm personally not against this feature, but many are against due to complications.

**Comment by Avey777** [comment]
> It can be set up via v.mod. I'm personally not against this feature, but many are against due to complications.

Can you give me an example to show me how to do it

**Comment by Avey777** [comment]
> It can be set up via v.mod. I'm personally not against this feature, but many are against due to complications.

![image](https://github.com/vlang/v/assets/35259040/19855bf6-855f-47b2-a5d8-3ac5765c71ab)
Is it an implementation similar to Rust? Can you give an example?

**Comment by Avey777** [comment]
This is not possible
![image](https://github.com/vlang/v/assets/35259040/74269176-023e-4b8c-b9a2-48eff4623995)
---
This is ok（This is possible, but it still doesn't achieve the purpose of putting V files in different folders）
![image](https://github.com/vlang/v/assets/35259040/66c61a53-8f20-445f-b007-7a8cf8c009af)

**Comment by Avey777** [comment]
![image](https://github.com/vlang/v/assets/35259040/d82b70f9-32b7-4607-aa38-b1111b9d5b03)
Is it possible to encapsulate it in a very concise way like go?

**Comment by Avey777** [comment]
```
@["/1688_form/";post]
pub fn (app &App) pf1688_form(mut ctx Context, offer_id_i64 i64) veb.Result {
	log.info("执行函数:${@METHOD} ${@MOD}.${@FILE_LINE}")

	if offer_id_i64 <= 0 {
		eprintln(offer_id_i64)
		return ctx.json({"code": "100", "msg": "offer_id 必须是整数"})
	}

	sqldata := mall_1688(offer_id_i64) or { return ctx.json({"code": "102", "msg": "数据库链接错误"}) }
	if sqldata.len == 0 {
		return ctx.json({"code": "103", "msg": "数据库查询失败"})
	}

	return ctx.json(sqldata[0])
}

```

Is this type of encapsulated code block still too large, can it be encapsulated the same as the one mentioned above? One line is an API

**Comment by Avey777** [comment]
@JalonSolov

**Comment by nkev** [comment]
This issue is the only reason we don't build website backends and APIs with V. We use Go instead.
It's a fundamental requirement to organize handlers into own logical modules, like we can any other language.

**Comment by medvednikov** [comment]
@nkev V and Go have a very similar modular system. Can you please elaborate what Go allows you to do that V doesn't?

**Comment by nkev** [comment]
@medvednikov Sure. The Go code from Avey777 above shows the issue well with `gt_path.Translation` where`Translation` is the handler and `gt_path` is a **separate** imported Go package. 

It's very convenient to separate all the routes from main.v into a separate package, but I could never do it in vweb when I last tried last year. 

So from main.v I would like to call the package `routes.init_router()` to initialize all routes, like this:

<img width="740" alt="Image" src="https://github.com/user-attachments/assets/9b1bd889-5939-4ccf-945b-24f53df44197" />


If this is possible with `veb` we would love to see an example.

**Comment by medvednikov** [comment]
I see, yes it's now possible in veb using controllers:

```v
    mut api_controller := &other_module.Api{
        db: app.db
    }
    app.register_controller[Api, Context]('/api', mut api_controller)!
    app.use(veb.cors[Context](cors_options))
```
