### ISSUE TITLE
char type - byte(104).str() is not '104'

### ISSUE THREAD

**Issue by ntrel** [vlang/v#216]
```
	mut b := byte(104)
	println(b.str()) // prints 'h'
```
`byte` means 8-bit integer, like `u8`. It is unexpected that `fn (b byte).str()` treats b as a character. Instead, we could have `type char u8` as the type for \`c\` and 'str'[0] and probably remove `byte`.

Then println(\`h\`) could work without having to call `.str()`, which is more efficient.

**Comment by medvednikov** [comment]
Agreed. `string(b)` should be `h`, `b.str()` should be `104`.

**Comment by ntrel** [comment]
Given that byte is just an integer, and integer -> string creates a string with digits only, I think interpreting a byte as a character should be clear in code. If we avoid having `char` because that isn't helpful with UTF-8, then we could use `rune(my_byte).str()`.

Also, why aren't \`c\` character literals of type `rune` to support UTF-8, like Go?

**Comment by M4SSD35TRUCT10N** [comment]
@medvednikov : Is there any progress on that front?

**Comment by bogen85** [comment]
@M4SSD35TRUCT10N, @medvednikov if the following is still the expected behavior:
```
string(b) should be h, b.str() should be 104.
```
Then I will take a look at this

**Comment by JalonSolov** [comment]
Still broken... simple file `foo.v`
```
mut b := byte(104)
println(b.str())
println(string(b))
```
Using current `V 0.1.27 88e6d98`.
```
$ v run foo.v
h
Segmentation fault
$
```

**Comment by medvednikov** [comment]
Fixed, finally!

**Comment by ntrel** [comment]
Great!
