### ISSUE TITLE
regex.regex_opt doesn't handle \x escape codes

### ISSUE THREAD

**Issue by zadeviggers** [vlang/v#21607]
### Describe the bug

regex.regex_opt doesn't handle \x escape codes

### Reproduction Steps

This regex should strip terminal colour codes,
```v
mut remove_colours_re := regex.regex_opt(r'\x1b\\[[0-9;]*[a-zA-Z]') or { panic(err) }
```

### Expected Behavior

The regex works properly and strips the colour codes without erroring

### Current Behavior

It errors at runtime with this message:
```
query: \x1b\\[[0-9;]*[a-zA-Z]
err  : --^
ERROR: err_syntax_error
```

### V version

V 0.4.6 a4afcba

### Environment details (OS name and version, etc.)

V full version: V 0.4.6 6b2d527.a4afcba
OS: macos, macOS, 14.5, 23F79
Processor: 8 cpus, 64bit, little endian, Apple M2

CC version: Apple clang version 15.0.0 (clang-1500.3.9.4)
thirdparty/tcc: N/A
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by penguindark** [comment]
I'll check this in the next days.

**Comment by penguindark** [comment]
I've made a PR with the \x \X implementation, I Hope it will be merged ASAP.
