### ISSUE TITLE
Selective imports are not selective.

### ISSUE THREAD

**Issue by 4kbyte** [vlang/v#21611]
### Describe the bug

The feature currently known as `selective imports` means:

* Import the module: `import module`.
* Allow for specific names to be used without a namespace: `{ Name }`.

The module is still imported. This is understood by the current implementation (see below) but the import is not selective as the entire module is imported.

### Reproduction Steps

```v
// thing.v
module thing

pub struct Thing {}
```

```v
// main.v
import thing { Thing }

fn main() {
        thing := Thing{}
        dump(thing)
}
```

### Expected Behavior

Semantics change across module boundaries. Selectively importing should allow the call site to decide on all symbols outside the set of the imported symbols.

### Current Behavior

```
$ v .
main.v:5:2: error: duplicate of an import symbol `thing`
    3 | 
    4 | fn main() {
    5 |     thing := Thing{}
      |     ~~~~~
    6 |     dump(thing)
    7 | }
```

### Possible Solution

A primary use case is data modeling. Module names are likely similar or identical to structures that they contain (above: `thing.v` models structure `Thing`). The call site that makes use of a model could just as likely prefer a matching name, for example an application `session` variable of type `Session`.

In the current implementation, the programmer must work around V's behavior:

```v
// main.v
import thing { Thing }

fn main() {
        th := Thing{}
        dump(th)
}
```

Selectively importing without importing the module eliminates astonishment and the need for workarounds.

It would then be explicit if the module itself is needed (as in e.g. Python):

```v
import thing
import thing { Thing }
```

If after reviewing this issue, the consensus is to keep the behavior of importing the module when also importing symbols within it, then I humbly request that the V project rename "selective import" to something else.

### Additional Information/Context

#12414 has consensus that module names are not to be shadowed in V.

The behavior of importing the module on selective import is [understood by the current implementation](https://github.com/vlang/v/blob/52dfef1/doc/docs.md?plain=1#L1543).

### V version

V 0.4.6 52dfef1

### Environment details (OS name and version, etc.)

```
CC version: cc (Gentoo 13.2.1_p20240210 p14) 13.2.1 20240210
thirdparty/tcc status: thirdparty-linux-amd64 40e5cbb5
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
The module is still named `thing` even if you only want to include a small part of it.  Since the module is named `thing` and you tried to create a variable with the same name, V correctly complained.

The fact that doing the selective import allows you to use the `Thing` name without the module name prefix does not mean that the module name is "forgotten".

**Comment by ttytm** [comment]
Looks correct to me. You can use a import alias with `as` if you want to use the name of the module then it should not complain anymore.

**Comment by ttytm** [comment]
> `v` will warn about an unused import.

I see, this should not be.

Repro:

```v
import os as vos { Result }

fn main() {
	os := Result{}
	dump(os)
}
```
```
warning: module 'vos (os)' is imported but never used
    1 | import os as vos { Result }
      |        ~~
    2 | 
    3 | fn main() {
```

A use of selective imports when the needs correctly mark the module as used when it has an alias.
