### ISSUE TITLE
Interpolation in double quotes does not work

### ISSUE THREAD

**Issue by lobotony** [vlang/v#2162]
**V version:** V 0.1.20 21f9dc6
**OS:** MacOS 10.14.6

**What did you do?**

	fn main() {
		mut msg := "ola"
		v := 2
		match v {
			0 => { msg = 'hello'}
			else => { msg = "else $v" }
		}
		println(msg)
	}

**What did you expect to see?**
successful compilation
 
**What did you see instead?**

	expected `}` but got `eof`
    8| 	println(msg)
    9| }
         ^

This example compiles, once you exchange the double quotes in the else branch with single quotes.

**Comment by gslicer** [comment]
I think the error message is wrong, it shall be something that " is not expected - could you take a look perhaps @medvednikov ?

The following code works as advertised:
```
fn main() {
	mut msg := 'ola'
	v := 2
	match v {
		0 => { msg = 'hello'}
		else => { msg = 'else $v' }
	}
	println(msg)
}
```

**Comment by avitkauskas** [comment]
I renamed the issue as interpolation in double quotes does not work in general and has to be fixed.

**Comment by Delta456** [comment]
Fixed
