### ISSUE TITLE
pub keyword seems to ignore the visibility attribute

### ISSUE THREAD

**Issue by radare** [vlang/v#2163]
```rust
$ cat g.v
pub fn fun_pub () int {
	return 3
}

fn fun_priv() int {
	return 3
}
$ v g.v
$ rabin2 -E g | grep fun
069 0x00008910 0x100008910 GLOBAL   FUNC    0 _main__fun_priv
070 0x00008900 0x100008900 GLOBAL   FUNC    0 _main__fun_pub
$
```

**Comment by dumblob** [comment]
I can see two things here.

First thing is the semantics of `pub` which if I'm not mistaken just says "can't be used outside of this module" (if there is no `module` keyword, then I don't know the behavior, but would guess `pub` means nothing in that case). In other words, `pub` doesn't affect resulting binary at all, but just constraint checking during compilation.

Second thing is the fact, that if a function/method is not being used and the output is not a library (dll, so, ...) nor REPL, then it could be ignored and not compiled at all. I would call this an optimization and I think *V* is not yet there to optimize such things.

**Comment by medvednikov** [comment]
> I would call this an optimization and I think V is not yet there to optimize such things.

@joe-conigliaro was working on this. It'll be ready soon, not a very complex optimization.

**Comment by joe-conigliaro** [comment]
Indeed I am :)

**Comment by elimisteve** [comment]
I believe this was fixed and merged in already? @joe-conigliaro

**Comment by medvednikov** [comment]
Fixed.
