### ISSUE TITLE
Empty lines after function signature are removed

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [vlang/v#21644]
### Describe the bug

```v fmt ``` removes manually placed empty lines after function signatures.

### Reproduction Steps

Add an empty line after a function signature:

```V
pub fn function_name(x u32, y u32, z u32) {
	
	first_variable := x+ y +z
}
```

### Expected Behavior

The line stays, as in most other places.

### Current Behavior

It vanishes with ````v fmt``:

```V
pub fn function_name(x u32, y u32, z u32) {
	first_variable := x + y + z
}
```

### Additional Information/Context

previously discussed with @medvednikov 

### V version

0.4.6

### Environment details (OS name and version, etc.)

not relevant
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
This is correct, and the way `v fmt` works.  It's not a bug.
