### ISSUE TITLE
Calling V functions from C

### ISSUE THREAD

**Issue by radare** [vlang/v#2165]
**V version:** V 0.1.20 e72fe25
**OS:** macOS 10.14

**What did you do?**

```rust
$ cat g.v ; v g.v ; ./g


pub fn C.radare_plugin_function() int {
	println("init")
	return 3
}

init
$ echo $?
3
```

**What did you expect to see?**

nothing, this program have no `main`. i just want to have a function named `radare_plugin_function`
 
**What did you see instead?**

the code is inlined inside the `main__main` symbol of the binary

```c
 int main(int argc, char** argv) {
   init_consts();

  {

 println ( tos2((byte*)"init") ) ;

return  3 ;

 }
 ;

   return 0;
 }
```

**Comment by luoheng23** [comment]
You can't define a C function in V, but just use it. So your example is  similar to this:
```v
pub fn C.radare_plugin_function() int; // I want to use a C function called radare_plugin_function
// another block
{
    println("init")
    return 3
}
```
Normal function should work well.

**Comment by bjeanes** [comment]
> You can't define a C function in V, but just use it.

Is this going to change? Being able to define C functions would be critical for writing extensions or modules for other libraries and languages.

**Comment by joe-conigliaro** [comment]
@bjeanes Why not just write the function in C then and include it?

**Comment by bjeanes** [comment]
... the reason to write C functions is to that something in C can call MY code.

E.g. an NSS module needs to define a hook, say `_nss_mymodule_gethostbyname4_r(...)`. I can define all the functions I want in C but I still need to expose something at the end of the day which calls _into_ the language I want core logic in (e.g. V)

**Comment by joe-conigliaro** [comment]
so you mean you want to call V functions from C?

**Comment by radare** [comment]
yes i want to call a V function from C, that's why the symbol name should be controlled by the programmer

**Comment by medvednikov** [comment]
I see @radare, I'll think of the best way to do this.

**Comment by radare** [comment]
thanks

**Comment by dumblob** [comment]
@radare could you change the title of this issue to something like **Calling V functions from C** to avoid confusion? Thanks :wink:.

**Comment by radare** [comment]
Done
