### ISSUE TITLE
x &&= y is not implemented

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#21676]
### Describe the bug

`x &&= y` and `x &= y` are needed

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
This works for `x &= y`:
```v
mut x := 5
y := 11
x &= y
dump(x)
```

**Comment by Delta456** [comment]
`||=` is not implemented as well.

**Comment by JalonSolov** [comment]
Just extend it to say _all_ `<bitwise operator>=` needs to be implemented.

**Comment by spytheman** [comment]
```v
mut x := 5
y := 11
x |= y
dump(x)
```
also works; imho only the logical ones are missing
