### ISSUE TITLE
eof  ignored because of <>

### ISSUE THREAD

**Issue by Eliyaan** [vlang/v#21687]
### Describe the issue

`<p>input returns a one-line string from stdin, after printing a prompt. Returns '<EOF>' in case of an error (end of input).</p>`

EOF does not show because of the <>

### Links

https://modules.vlang.io/os.html#input

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Delta456** [comment]
Issue fixed https://modules.vlang.io/os.html#input
