### ISSUE TITLE
Pointer dereferencing ambiguity following expression

### ISSUE THREAD

**Issue by ntrel** [vlang/v#217]
```rust
mut y := 3
mut x := &y
*x = 4
```
Gives:
```
test.v:3
expected type `int`, but got `void`
```
I'm not sure where void comes from. The compiler may be trying to parse `&y * x = 4`. I think there are two solutions:
* Make newline a meaningful grammar token, and only parse an expression past a newline if e.g. the last token on the line is a binary operator, or there is an unclosed `(` or `{` expression.
* Choose a different syntax for dereferencing a pointer. Given that we have `ptr.field` syntax, `*ptr` may be less common, so we could even just have a built-in property like `ptr.deref`. I think it should be postfix, which is also good for chaining in expressions (`some.long.expression.deref = expr`). Zig uses `ptr.*`.

**Comment by medvednikov** [comment]
Fixed.
