### ISSUE TITLE
R2 module

### ISSUE THREAD

**Issue by radare** [vlang/v#2170]
I'm writing an r2pipe-like wrapper API for V, for learning, but a couple of questions popped up into my mind while doing this:

* Is there pkg-config support in v? or this backtick trick is fine?
* It is fine to create an empty struct to handle this type? i was expecting to be able to reuse the C.RCore type in here, but the type seems to be wrapped into 'void' and trying to cast to 'voidptr' or 'byteptr' fails
* it seems a bit overengineered to wrap and unwrap the strings from C to V all the time, it will be good to have better support for native C strings in V
* Can we include this module into standard V? or may i ship it separately?
* Go uses capitalized method names to expose the methods instead of having to use the `pub` keyword. this is probably something to discuss in a separate issue.

At some point it will be good to have a vpm to install modules for 3rd party apis, or have a generic place to have them system wide, so the compiler can take them.

```rust
$ cat vlib/r2/r2.v
module r2

#flag `pkg-config --cflags --libs r_core`

#include <r_core.h>

struct R2 {}

pub fn (core &R2)cmd(s string) string {
	o := C.r_core_cmd_str (core, s.str)
	strs := string(byteptr(o))
	free(o)
	return strs
}

pub fn (core &R2)str() string {
	return i64(core).str()
}

pub fn (core &R2)free() {
	C.r_core_free (core)
}

pub fn new() &R2 {
	return &R2(C.r_core_new ())
}
$
```

**Comment by dumblob** [comment]
An additional question: will the back-tick trick work with hot reload and threading in general?

**Comment by radare** [comment]
And another point: this will not work on windows

**Comment by joe-conigliaro** [comment]
I'm not sure if it's a good idea to automatically install third party deps, I guess if it prompted the user first. The only things is difference systems use different packages management.

**Comment by spytheman** [comment]
@radare you can submit your module to https://vpm.vlang.io , and then people can install it by running `v install radare.yourmodulename`  (the part after radare. can be named anything, it is not necessary to match your github reponame).
The installation happens as a git clone to ~/.vmodules/radare.yourmodulename
and then users can use it in their v programs by:
`import radare.yourmodulename as r2`

**Comment by radare** [comment]
Thank you! i'm closing this issue as long as i have moved the module to my account:

https://github.com/radare/v-r2
