### ISSUE TITLE
v fmt command error!

### ISSUE THREAD

**Issue by ghosttk** [vlang/v#21744]
### Describe the bug

cannot compile `D:\bin\v\cmd\tools\vfmt.v`: 1

### Reproduction Steps

 v fmt .\src\main.v

### Expected Behavior

run without error

### Current Behavior

PS D:\myprojects\v\Gangweijintie> v fmt .\src\main.v
cannot compile `D:\bin\v\cmd\tools\vfmt.v`: 1
vlib/v/pref/pref.v:59:20: error: duplicate method `is_js`
   57 | }
   58 |
   59 | pub fn (b Backend) is_js() bool {
      |                    ~~~~~
   60 |     return b in [
   61 |         .js_node,

### V version

V 0.4.6 98a1ee2

### Environment details (OS name and version, etc.)

PS D:\myprojects\v\Gangweijintie> v doctor
V full version: V 0.4.6 98a1ee2
OS: windows, Microsoft Windows 11 ��ͥ���İ� v22631 64 λ
Processor: 8 cpus, 64bit, little endian,

getwd: D:\myprojects\v\Gangweijintie
vexe: D:\bin\v\v.exe
vexe mtime: 2024-06-25 21:16:21

vroot: OK, value: D:\bin\v
VMODULES: OK, value: C:\Users\ghost\.vmodules
VTMP: OK, value: C:\Users\ghost\AppData\Local\Temp\v_0

Git version: git version 2.44.0.windows.1
Git vroot status: weekly.2024.22-67-g1a685c30-dirty (43 commit(s) behind V master)
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc status: thirdparty-windows-amd64 b425ac82
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
Try:
1) deleting `D:\bin\v`
2) `git clone https://github.com/vlang/v D:\bin\v`
3) `cd d:\bin\v`
4) `.\make.bat`

**Comment by ghosttk** [comment]
> Try:
> 
> 1. deleting `D:\bin\v`
> 2. `git clone https://github.com/vlang/v D:\bin\v`
> 3. `cd d:\bin\v`
> 4. `.\make.bat`

It works ! Thank you!
