### ISSUE TITLE
Add cmdline flag to build as shared library

### ISSUE THREAD

**Issue by radare** [vlang/v#2175]
**V version:** V 0.1.20 7311db6
**OS:** macOS 10.14

**What did you do?**

v -cflags '-shared -fPIC' -o hi.so hi.v

**What did you expect to see?**

a shorter (and portable way) to build V code as shared library
 
**What did you see instead?**

**Comment by spytheman** [comment]
It would pass the -fPIC automatically.

**Comment by spytheman** [comment]
It is used by the hot code reloading, so by now it should be pretty well supported on mac/win/linux at least.

**Comment by radare** [comment]
Its not in h help message. Thats why i didnt used it

**Comment by gslicer** [comment]
Why not use the existing swiitch?

` build <module>    Compile a module into an object file.`

**Comment by radare** [comment]
An object is not a shared library

**Comment by medvednikov** [comment]
I've added it to help.v
