### ISSUE TITLE
Let user specify other directories in `v test v`

### ISSUE THREAD

**Issue by cielavenir** [vlang/v#2176]
Currently we need to be on the v-installation directory when executing `v test v`. However, Homebrew test runs under sandbox-exec and `a.out.tmp.c` cannot be written on `/usr/local/Cellar/vlang/0.1.20/libexec`. We need to run `v test v` on /tmp.

cf https://github.com/Homebrew/homebrew-core/pull/44657

**Comment by medvednikov** [comment]
I just pushed a fix that allows to run it from any directory.

**Comment by cielavenir** [comment]
I tested master as your update is not released as tar yet.

I can see that compiled binaries are created under vlib etc even when I launch `/path/to/v test v` from another directory. On Homebrew, tests are launched using sandbox, so vlib is write-protected.I'd like the binaries created under current directory.

**Comment by cielavenir** [comment]
Is it possible to run `v test v` when vlib and example are write-protected?

**Comment by cielavenir** [comment]
When vlang is system-installed, v test v cannot be executed because it tries to create binaries in system directory, which is write-protected. Do you have any ideas?

**Comment by medvednikov** [comment]
`v test [path]` now works.

**Comment by cielavenir** [comment]
I had an opportunity to revisit this, but this requires all test codes to be copied to that `path`. I would like test binaries to be compiled under `path` using sources from VROOT.
