### ISSUE TITLE
Implement spread operator like in ES6

### ISSUE THREAD

**Issue by radare** [vlang/v#2178]
```
a := ["foo", "bar", "cow"]
fcn_call(...a)
```

will be the same as doing:

```
fcn_call("foo", "bar", "cow")
```

**Comment by dumblob** [comment]
Can't find it right now, but I think there was already some discussion about unwrapping of structs/arrays as function arguments.

**Comment by tomByrer** [comment]
I thought about suggesting this myself, makes working with arrays & objects easier.  [Restructuring](https://exploringjs.com/es6/ch_destructuring.html?TB_iframe=true&width=921.6&height=921.6) is magical though!

**Comment by medvednikov** [comment]
But this is different.

**Comment by joe-conigliaro** [comment]
It's possible, I was going make variadics use arrays, but until I can think of an efficient way to do it, I think its better to stay how it is

**Comment by nedpals** [comment]
Closing this in favor of the more recent #7134.
