### ISSUE TITLE
Alias of a fixed array can't be initialized

### ISSUE THREAD

**Issue by alfaus** [vlang/v#21783]
### Describe the bug

Code: https://play.vlang.io/p/c005d02df9

```v
type MyArray = [10]int

_ := MyArray{}
```

### Reproduction Steps

Run the code provided.

### Expected Behavior

Code compiles.

### Current Behavior

Output:

```
code.v:3:6: error: alias type name: [10]int is not struct type
    1 | type MyArray = [10]int
    2 | 
    3 | _ := MyArray{}
      |      ~~~~~~~~~
Exited with error status 1
```

### V version

V 0.4.6 39f4191

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.6 39f4191
OS: linux, Debian GNU/Linux 11 (bullseye) (VM)
Processor: 1 cpus, 64bit, little endian, Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz

getwd: /home/admin/playground
vexe: /home/admin/v/v
vexe mtime: 2024-07-01 15:25:26

vroot: OK, value: /home/admin/v
VMODULES: OK, value: .vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.30.2
Git vroot status: Error: fatal: detected dubious ownership in repository at '/home/admin/v'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v
.git/config present: true

CC version: cc (Debian 10.2.1-6) 10.2.1 20210110
thirdparty/tcc status: Error: fatal: detected dubious ownership in repository at '/home/admin/v/thirdparty/tcc'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v/thirdparty/tcc
 Error: fatal: detected dubious ownership in repository at '/home/admin/v/thirdparty/tcc'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v/thirdparty/tcc

```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Delta456** [comment]
This works

```v
type MyArray = [4]int

a := MyArray([12, 45, 78, 78]!)
println(a)
```

**Comment by JalonSolov** [comment]
The error message is incorrect, but it shouldn't work.
```v
_ := MyArray{}
```
would be trying to create a 0 length fixed array, which makes no sense at all.  Similar to just declaring
```v
_ = []!
```
V doesn't give a good error message in any case where `[]!` is used.  For my example, it just says "error: expression evaluated but not used".

If you try `println([]!)` it says "error: invalid expression: unexpected token `)`".

Basically, `[]!` is invalid, as you can't have a 0 length fixed array.

**Comment by felipensp** [comment]
> ```v
> [10]int
> ```

But it is not an array to empty array. It is an alias to `[10]int`.
