### ISSUE TITLE
Support Go type aliases

### ISSUE THREAD

**Issue by ntrel** [vlang/v#218]
https://golang.org/ref/spec#Alias_declarations

* In Go, `byte` is a type *alias* for `uint8`, not a distinct type. So a `byte` can be assigned a `uint8` and vice versa, a `byte` can be passed to a `uint8` function parameter etc. Currently V does not allow these implicit conversions.
* In V, `int` should be an alias for `i32`, not a distinct type. ATM `i32` does not convert to `int` and vice versa.
* In Go, `rune` is also an alias, but I really think it should be a distinct type, as it is in V now. Then method `(r rune).str()` interprets `r` as a UTF-8 code point, and `(i int).str()` interprets `i` as a number (see also #216).

A possible way to simplify V would be to remove support for `type New Old` type definitions. I think they are almost the same as making a `struct New` with one field, except for `New(old)` vs `New{old}` syntax [assuming embedding and operator overloading make the struct act like `Old`].

**Comment by Bowero** [comment]
This has actually been done now: https://vlang.io/docs#btypes

**Comment by ntrel** [comment]
@bowero Are you sure, those docs haven't changed. Did you check that int is no longer a distinct type from i32?

**Comment by Bowero** [comment]
You are correct, I am sorry.

```
fn main() {
    a := 32
    b := i32(32)

    println(a == b)
}
```

This returns an error: `expected type 'int', but got `i32`

**Comment by ntrel** [comment]
@bowero OK, please reopen?

**Comment by ntrel** [comment]
@medvednikov please reopen?

**Comment by ntrel** [comment]
Refiled as no one reopened this (with better title).

**Comment by medvednikov** [comment]
@ntrel I've added you to the team, you can now do this yourself :)

**Comment by ntrel** [comment]
Thanks!

**Comment by ntrel** [comment]
Closing this in favour of #983.
