### ISSUE TITLE
os.signal_opt with closure in callback does not compile

### ISSUE THREAD

**Issue by mike-ward** [vlang/v#21819]
### Describe the bug

Calling `os.signal_opt` with closure in callback does not compile stating it is not expecting a comma after the first argument.

### Reproduction Steps

```
fn set_auto_wrap(options Options) {
	if options.no_wrap {
		wrap_off := '\e[?7h'
		wrap_reset := '\e[?7l'

		print(wrap_off) 

		at_exit(fn [wrap_reset] () {
			print(wrap_reset)
		}) or {}

		os.signal_opt(os.Signal.int, fn [wrap_reset] (sig os.Signal) {
			print(wrap_reset)
			exit(0)
		}) or {}
	}
}
```

### Expected Behavior

Should compile

### Current Behavior

```
Mikes-Air➜  lsv : main ✘ :✹ ᐅ  v run .
lsv.v:56:30: error: unexpected token `,`, expecting `(`
   54 |         }) or {}
   55 | 
   56 |         os.signal_opt(os.Signal.int, fn [wrap_reset] (sig os.Signal) {
      |                                    ^
   57 |             print(wrap_reset)
   58 |             exit(0)
Mikes-Air➜  lsv : main ✘ :✹ ᐅ  
```

### Possible Solution

Changing the code as follows compiles

```
fn set_auto_wrap(options Options) {
	if options.no_wrap {
		wrap_off := '\e[?7h'
		wrap_reset := '\e[?7l'

		print(wrap_off)

		at_exit(fn [wrap_reset] () {
			print(wrap_reset)
		}) or {}

		os.signal_opt(os.Signal.int, fn (sig os.Signal) {
			print('\e[?7l')
			exit(0)
		}) or {}
	}
}
```

### V version

V 0.4.6 f6de36d

### Environment details (OS name and version, etc.)

V full version: V 0.4.6 8215f21.f6de36d
OS: macos, macOS, 14.5, 23F79
Processor: 8 cpus, 64bit, little endian, Apple M2

getwd: /Users/mike/Documents/github/lsv/lsv
vexe: /Users/mike/Documents/github/v/v
vexe mtime: 2024-07-07 15:50:01

vroot: OK, value: /Users/mike/Documents/github/v
VMODULES: OK, value: /Users/mike/.vmodules
VTMP: OK, value: /tmp/v_501

Git version: git version 2.45.2
Git vroot status: weekly.2024.27-29-gf6de36db
.git/config present: true

CC version: Apple clang version 15.0.0 (clang-1500.3.9.4)
thirdparty/tcc status: thirdparty-macos-arm64 5c1d002f
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
A smaller complete reproduction is:
```v
import os

x := '\e[?7l'
os.signal_opt(os.Signal.int, fn [x] (sig os.Signal) {
	print(x)
	exit(0)
}) or {}
```

**Comment by manosriram** [comment]
@spytheman can i try this one?

**Comment by spytheman** [comment]
> @spytheman can i try this one?

Try it in what sense? 
If you mean to make a PR for solving it, go ahead.
