### ISSUE TITLE
array.find() / array.index_of()

### ISSUE THREAD

**Issue by lobotony** [vlang/v#2189]
Can we have a function that searches for a given element by value and 
* returns its first index, if found
* or a -1 or error, if not found
?

Basically what "a in b" does for arrays, only returning an int instead of a bool. 
re: naming: 
.find(value) or
.index_of(value) or
.first_index_of(value) or

Docs should make clear that it returns the first index of the element that has the same value as the provided one. 

Thanks.

**Comment by donnisnoni95** [comment]
I think `find` will be better?

**Comment by LorenzoPirro** [comment]
I think it could be like C#, simple and clean. For example:
```
arr := [1,2,3,4]
elem := arr.find(3)? // returns ?int
elem_index := arr.first(predicate)? // returns ?T
elements := arr.find_all(predicate)? // returns ?[]T or []T to check
```
it would be possibile to write a lot of useful and well documented functions

**Comment by Delta456** [comment]
Done https://github.com/vlang/v/commit/68bcf6830cb0a3572b21880cdb949dd187548424
