### ISSUE TITLE
test fails compilation because of module that works in other project

### ISSUE THREAD

**Issue by lobotony** [vlang/v#2192]
**V version:** V 0.1.21 30ca149
**OS:** MacOS 10.14.6

**What did you do?**

in va_test.v

	import lobotony.ldata

	pub fn test_va_parse_name() {
	    println("hello")
	}

tried to run with `v va_test.v`

**What did you expect to see?**
succesful compilation and "hello" on console
 
**What did you see instead?**

	va_test.tmp.c:3934:9: error: unexpected type name 'FILE': expected expression
	int fp= FILE ;
	        ^
	1 error generated.

The file works as intended if I remove the import. 
The module works in another more complex project and setting. 
va_test.v is located in the module that I wanted to test.

**Comment by spytheman** [comment]
Try to do `import os` first.

**Comment by lobotony** [comment]
It was indeed the missing`import os`. Nasty, because it was working all this time for every other case. Should I close this?

**Comment by spytheman** [comment]
I am not sure. It would be nice to have v detect it, but I do not know how could that be implemented.
@joe-conigliaro , @medvednikov what do you think?

**Comment by spytheman** [comment]
Now that I think about it more, maybe the module just needs to do
#include <stdio.h>
at its start, so that its users would not need to care.

**Comment by lobotony** [comment]
yeah, I've been thinking about that: adding imports to get the includes isn't bad in my book, but then the compiler complains about `unused imports`.

Adding just the include is probably fine for standard C headers, but gets murky when it comes to other non-standard modules. 

I guess I'd prefer if we could do something like a `import os @header_only` to document dependencies and intent, but quiet the compiler warnings (please disregard the shitty attempt at new syntax)

**Comment by joe-conigliaro** [comment]
@spytheman hrmmm, shouldn't stdio, be included before everything. Are there any other specific deps on os? or is it just a consequence of os defining:
```
struct C.FILE {}
```
Perhaps this should be defined somewhere else, since it can be used without the os module?

**Comment by spytheman** [comment]
For some reason, when os is not imported, the generated C code is:

`int fp= FILE ;`
... which fails.

When os is imported, it becomes:
`FILE* fp= (FILE*)memdup(&(FILE) { 0 } , sizeof(FILE)) ;`

I think it is because in os, there is:
struct C.FILE { }

so that knowledge changes what v generates.

**Comment by spytheman** [comment]
Oops, sorry, did not read your comment carefully, you already found the culprit :-|  @joe-conigliaro .

**Comment by spytheman** [comment]
It may be better to move this definition in vlib/builtin/builtin.v (which roughly corresponds to compiler/cheaders.v for the generated C code, since it is used for every v program)?

**Comment by spytheman** [comment]
On the other hand, extracting to vlib/builtin/builtin.v would not be useful for the JS backend...

**Comment by spytheman** [comment]
> I guess I'd prefer if we could do something like a `import os @header_only` to document dependencies and intent, but quiet the compiler warnings (please disregard the shitty attempt at new syntax)

PHP has the notion of putting @ before statements to silence their errors (yeah, it is evil, but practical :-) )

**Comment by joe-conigliaro** [comment]
Imo dunno to me it doesn't really seem like a module issue, I think it needs to be thought about some more hrmm. If it was os.File being used it would make more sense. Where should file be defined. Hrmmm

**Comment by joe-conigliaro** [comment]
I actually think it shouldbe os.File, then the os import is mandatory, and it makes sense to me that way

**Comment by lobotony** [comment]
this plopped up again yesterday, even though I had a stdio include in the same file, so I changed the code again to: 

	fn _open(path string, mode string) *C.FILE {
		$if windows {
			return C._wfopen(path.to_wide(), mode.to_wide())
		} $else {
			cpath := path.str
			return C.fopen(cpath, mode.str) 
		}	
	}

	mut fp := _open(path, mode)

This seems to keep working in both the application and test case.

**Comment by medvednikov** [comment]
This has been fixed for a while.
