### ISSUE TITLE
Possible to define a static type method without defining a type

### ISSUE THREAD

**Issue by dadooda** [vlang/v#21969]
### Describe the bug

It's possible to define a static type method, as described in [Static type methods](https://docs.vlang.io/structs.html#static-type-methods), without defining the struct or interface.

### Reproduction Steps

This works:

```v
fn main() {
  Mystery.hey()
}

// No definition of `Mystery` here.

fn Mystery.hey() {
  println('hey, ${@METHOD}')
}
```

### Expected Behavior

I'd expect an error, or a warning at least. Most probably, the developer has mistyped the type name or has left out the implementation somehow.

### Current Behavior

The code compiles and gets executed.

### V version

0.4.7 7baff15

### Environment details (OS name and version, etc.)

Ubuntu 18 under WSL.
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
Bug or feature? :)

**Comment by Delta456** [comment]
> Bug or feature? :)

It is bug
