### ISSUE TITLE
Pls can you make wasm port(Vi framework) like Yew for Rust.

### ISSUE THREAD

**Issue by Omnuchka** [vlang/v#2196]
Yew - https://github.com/yewstack/yew

**Comment by tomByrer** [comment]
VLang can [output C source (hidden in WIKI)](https://github.com/vlang/v/wiki/Troubleshooting).   Have you tried to compile the C code to WASM?

https://dassur.ma/things/c-to-webassembly/
https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm

**Comment by nedpals** [comment]
No clear information and just follow @tomByrer 's advice. Closed.
