### ISSUE TITLE
Access modifier for each field

### ISSUE THREAD

**Issue by oleg-kachan** [vlang/v#2199]
Now V is _forcing_ you to put private immutable fields first followed by other groups, but programmer should be able to decide in what order she wants to order struct fields, for example, to be consistent with database table order (and grouping).

For example, in a database, fields might be like this:

```
id
created
modified
name
description
flag_1
flag_2
```

There is a natural order and natural groupings - id, then dates, then data fields, then flags.

In V, if I need different access modifiers I will not able to preserve the ordering:

```
struct Data {
    flag_1 int // private immutable
pub:
    id int
    created int
mut:
    flag_2 int
pub mut:
    modified int
    name string
    description string
}
```

It looks very unnatural to forcefully break group fields, I think it would be better to  allow to specify modifier for each field:

```
struct Data {
    pub id int
    pub created int
    pub mut modified int
    pub mut name string
    pub mut description string
    flag_1 int
    mut flag_2 int
}
```

Once again - a programmer should be able to specify the order of fields whatever she wants, not the order forced by the language.

**Comment by medvednikov** [comment]
Yes, this is a valid concern, especially in low level programming where the order of the fields is very important.

**Comment by oleg-kachan** [comment]
It seems back in April you had (or thought) of similar syntax: https://github.com/vlang/v/issues/68

**Comment by medvednikov** [comment]
Yes, and it may come back. `vfmt` will take care of the changed syntax for the existing code if that happens.

**Comment by oleg-kachan** [comment]
If so - access modifiers prefix functions, but postfix variables.

Small inconsistency.

**Comment by medvednikov** [comment]
The syntax will stay, it will be possible to specify the order via attributes.
