### ISSUE TITLE
Precision format ignored in string interpolation

### ISSUE THREAD

**Issue by mike-ward** [vlang/v#22028]
### Describe the bug

The precision specifier in string interpolation is sometimes ignored.

### Reproduction Steps

```
╰─ ▶ v
 ____    ____ 
 \   \  /   /  |  Welcome to the V REPL (for help with V itself, type  exit , then run  v help ).
  \   \/   /   |  Note: the REPL is highly experimental. For best V experience, use a text editor, 
   \      /    |  save your code in a  main.v  file and execute:  v run main.v 
    \    /     |  V 0.4.7 3247b98 . Use  list  to see the accumulated program so far.
     \__/      |  Use Ctrl-C or  exit  to exit, or  help  to see other available commands.

>>> x := 2.0
>>> println('${x:.1}')
2
```

### Expected Behavior

Expected `2.0`

### Current Behavior

returns `2`

### V version

V 0.4.7 20a525a

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.7 8215f21.20a525a
OS: macos, macOS, 14.6.1, 23G93
Processor: 8 cpus, 64bit, little endian, Apple M2

getwd: /Users/mike/Documents/github/coreutils/src/numfmt
vexe: /Users/mike/Documents/github/v/v
vexe mtime: 2024-08-11 14:57:33

vroot: OK, value: /Users/mike/Documents/github/v
VMODULES: OK, value: /Users/mike/.vmodules
VTMP: OK, value: /tmp/v_501

Git version: git version 2.46.0
Git vroot status: weekly.2024.30-97-g20a525ae
.git/config present: true

CC version: Apple clang version 15.0.0 (clang-1500.3.9.4)
thirdparty/tcc status: thirdparty-macos-arm64 5c1d002f

```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by yuyi98** [comment]
```v
PS D:\Vlang\v> v
 ____    ____
 \   \  /   /  |  Welcome to the V REPL (for help with V itself, type  exit , then run  v help ).
  \   \/   /   |  Note: the REPL is highly experimental. For best V experience, use a text editor,
   \      /    |  save your code in a  main.v  file and execute:  v run main.v
    \    /     |  V 0.4.7 a6cdc9a . Use  list  to see the accumulated program so far.
     \__/      |  Use Ctrl-C or  exit  to exit, or  help  to see other available commands.

>>> x := 2.0
>>> println('${x:.2f}')
2.00
>>> '${x:.2f}'
2.00
```

**Comment by mike-ward** [comment]
According to the documentation:

> precision: an integer value preceded by a . will guarantee that many digits after the decimal point, if the input variable is a float. Ignored if variable is an integer.

Is this a documentation issue?

**Comment by mike-ward** [comment]
If the wording below is acceptable I'll submit a pull request. 

> precision: an integer value preceded by a . will guarantee that many digits after the decimal point minus any insignificant trailing zeros. If displaying insignificant zero's is desired, append a `f` specifier to the precision value (see examples below). Applies only to float variables and is ignored to for integer variables.

I spent several hours trying to debug an issue where I wanted the insignificant zeros. The "guarantee" in the specification kept tripping me up.

**Comment by spytheman** [comment]
@mike-ward your wording is better.
A PR for it will be much appreciated 🙇🏻‍♂️ .
