### ISSUE TITLE
Provide easier installer like Rust

### ISSUE THREAD

**Issue by thewh1teagle** [vlang/v#22023]
### Describe the feature

Provide easier way to install v. instead of download, extract, add to path - all manually.

### Use Case

I just installed it and it took me a while.

### Proposed Solution

https://www.rust-lang.org/tools/install

We can use similar solution.
For linux - simple curl execution
For Windows - simple bootstrap exe
Auto path insertion

### Other Information

Does v has some system on top of it for managing itself? maybe it can be integrated there

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

0.4

### Environment details (OS name and version, etc.)

macOS
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Delta456** [comment]
I don't see how hard it is to `git clone https://github.com/vlang/v && cd v && make`

**Comment by Cergoo** [comment]
I think the team should focus on the language itself.
`rustup` it was a third party development that became popular and was included in the official tools rust lang.

**Comment by enghitalo** [comment]
Personally, I find V very easy to install. 🤔

**Comment by medvednikov** [comment]
`git clone https://github.com/vlang/v && cd v && make` 

`v up` for updates

as easy as it gets :)

**Comment by thewh1teagle** [comment]
Maybe I should repharse. I proposed enhancing it. I didn't said it was hard.

> I think the team should focus on the language itself. `rustup` it was a third party development that became popular and was included in the official tools rust lang.

That's sounds right. maybe it's not the right time to enhance since it's too new and there's more important featuers. I'll close the issue.
