### ISSUE TITLE
Custom types are not highlighted in VSCode

### ISSUE THREAD

**Issue by oleg-kachan** [vlang/v#2202]
**V version:** 0.1.19
**V VSCode extension:** 0.0.7
**OS:** MacOS 10.14

**What did you do?**
```
struct Node {
mut:
    id int
    adjacent []Node
}

fn (n mut Node) add_adjacent(node Node) {
	n.adjacent << node
}
```

**What did you expect to see?**
Custom types to be highlighted in VSCode 

1. in struct:
`adjacent []**Node**`

2. in method:
`fn (n mut Node) add_adjacent(node **Node**) {`
 
**What did you see instead?**
Custom types are not highlighted

**Comment by mvlootman** [comment]
This is not a bug with the V language. If you are using a vscode extension you should report the bug there.
