### ISSUE TITLE
sum types should have a default 0 value for the first type mentioned in the list of types.

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#22030]
### Describe the bug

sum types do not have a default value.  This can lead to errors if you try something as simple as
```v
x := MyType{}
```
this could be easily fixed if the default was to assign the default 0 value for the first type in the list.  Users could change which type was assigned by changing the order of types in the sum type.

Note that this change has been approved by Alex:  https://discord.com/channels/592103645835821068/592106336838352923/1272226313314242673

### Reproduction Steps

```v
type MyType = int | string

x := MyType{}

println(x)
```

### Expected Behavior

```
0
```

### Current Behavior

```
x.v:3:6: notice: direct sum type init (`x := SumType{}`) will be removed soon
    1 | type MyType = int | string
    2 | 
    3 | x := MyType{}
      |      ~~~~~~~~
    4 | 
    5 | println(x)
unknown sum type value
```

### V version

V 0.4.7 20a525a

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.7 efa98d9.20a525a
OS: linux, "Manjaro Linux"
Processor: 32 cpus, 64bit, little endian, AMD Ryzen 9 7950X 16-Core Processor

getwd: /home/jalon
vexe: /home/jalon/git/v/v
vexe mtime: 2024-08-11 16:45:16

vroot: OK, value: /home/jalon/git/v
VMODULES: OK, value: /home/jalon/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.46.0
Git vroot status: weekly.2024.32-24-g20a525ae
.git/config present: true

CC version: cc (GCC) 14.1.1 20240720
thirdparty/tcc status: thirdparty-linux-amd64 40e5cbb5
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
The same is true for interface values too - they also do not have default values.

**Comment by spytheman** [comment]
One problem that will have to be solved too, when first type gets used for a default value, is that currently `v fmt -w .` will reorder the sumtype variants in alphabetical order, and it should not, since the first type will have a semantic meaning in the future.

**Comment by JalonSolov** [comment]
It could always alphabetize all the types _after_ the first, but that seems like more trouble than it's worth.

Changing the defaults for interfaces may also need it's own separate issue... seems like a much bigger problem than sum types.

**Comment by medvednikov** [comment]
Just wanted to confirm that agree with this notion.
