### ISSUE TITLE
Invalid conversion from camel to snake string with numbers

### ISSUE THREAD

**Issue by Leopotam** [vlang/v#22052]
### Describe the bug

Invalid conversion from pascal/camel to snake string when there are numbers in string.

### Reproduction Steps

```v
println('BeginMode3D'.camel_to_snake())
```

### Expected Behavior

Output should be:
```
begin_mode_3d
```

### Current Behavior

Current output:
```
begin_mode3_d
```

### V version

V 0.4.7 7baff15

### Environment details (OS name and version, etc.)

V full version: V 0.4.7 7baff15
OS: macos, macOS, 14.6.1, 23G93
Processor: 16 cpus, 64bit, little endian, Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz

getwd: /Users/leopotam
vexe: /usr/local/Cellar/vlang/0.4.7/libexec/v
vexe mtime: 2024-07-26 04:41:00

vroot: OK, value: /usr/local/Cellar/vlang/0.4.7/libexec
VMODULES: OK, value: /Users/leopotam/.vmodules
VTMP: OK, value: /tmp/v_501

Git version: git version 2.39.3 (Apple Git-146)
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false

CC version: Apple clang version 15.0.0 (clang-1500.3.9.4)
thirdparty/tcc: N/A
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Cergoo** [comment]
this is not bug

**Comment by Cergoo** [comment]
you shall not pass   :)

**Comment by Leopotam** [comment]
i have much more broken variants :)
```v
fn C.BeginMode2D(camera Camera2D)
pub fn begin_mode2_d(camera Camera2D) {
	C.BeginMode2D(camera)
}

fn C.EndMode2D()
pub fn end_mode2_d() {
	C.EndMode2D()
}

fn C.BeginMode3D(camera Camera3D)
@[inline]
pub fn begin_mode3_d(camera Camera3D) {
	C.BeginMode3D(camera)
}

fn C.EndMode3D()
pub fn end_mode3_d() {
	C.EndMode3D()
}
```

**Comment by Leopotam** [comment]
as fix for both worlds i can only suggest use numbers as non breaking pattern for string parts:
```v
@[direct_array_access]
fn snake_case(s string) string {
	if s.len < 2 {
		return s.to_lower()
	}
	mut sb := strings.new_builder(s.len * 2)
	mut prev_num := true
	for i in 0 .. s.len {
		mut c := s[i]
		if c.is_capital() {
			if !prev_num {
				sb.write_u8(0x5f)
			}
			c += 0x20
		}
		prev_num = c.is_digit()
		sb.write_u8(c)
	}
	return sb.str()
}
```
as result:
```v
assert snake_case('BeginMode3D') == 'begin_mode3d'
assert snake_case('Http2Mode') == 'http2mode'
```

**Comment by Leopotam** [comment]
nevermind
