### ISSUE TITLE
Wrong type of array element in nested structs

### ISSUE THREAD

**Issue by Liikt** [vlang/v#2206]
**V version:** V 0.1.21 5ba354f 
**OS:** Arch Linux 5.3.1-arch1-1-ARCH

**What did you do?**
I created two structs. One holds a value and the other one holds an array of pointers of the first struct. When using a `for` loop with the `in` syntax the compiler compiles to wrong C code.

```
struct Foo {
mut:
    a []&Bar
}

struct Bar {
    b int
}

fn main() {
    mut f := Foo{}
    f.a = [Bar{}].repeat(10)
    for i, x in f.a {
        println(i)
        println(x)
    }
}
```

**What did you expect to see?**

This should compile as it is valid V. If I change the code slightly to 
```
struct Foo {
mut:
    a []int
}

fn main() {
    f := Foo{[1,2,3,4]}
    for i, x in f.a {
        println(i)
        println(x)
    }
}
```

it compiles and results in the expected output.

```c
void main__main() {
	Foo f= (Foo) {new_array_from_c_array(4, 4, sizeof(int), (int[]) {  1 ,  2 ,  3 ,  4  }) } ;
	array_int tmp2 =  f .a;
	for (int i = 0; i < tmp2.len; i++) {
		int x = ((int *) tmp2 . data)[i];
		printf ("%d\n",  i ) ;
		printf ("%d\n",  x ) ;
	};
}
```
This is the compiled C for the correct program. Here `tmp2` is a normal struct thus `tmp2.len` is correct. However for my failing example the main looks as follows:

```c
void main__main() {
	Foo f= (Foo) { .a =  new_array(0, 1, sizeof( Bar* )) } ;
	f .a  =  array_repeat(new_array_from_c_array(1, 1, sizeof(Bar), (Bar[]) {  (Bar) { .b =  0 }  }) , 10 ) ;

	array_Bar* tmp2 =  f .a;
	for (int i = 0; i < tmp2.len; i++) {
		Bar* x = ((Bar* *) tmp2 . data)[i];
		printf ("%d\n",  i ) ;
		printf ("%p\n",  x ) ;
	};
}
```
Here `tmp2` is a pointer to a struct and thus `tmp2.len` is wrong C.

**What did you see instead?**

This should compile and work without warnings.

**Debug output**
```
C compiler=cc
all .v files:
["/usr/lib/vlang/vlib/builtin/array.v", "/usr/lib/vlang/vlib/builtin/string.v", "/usr/lib/vlang/vlib/builtin/builtin.v", "/usr/lib/vlang/vlib/builtin/int.v", "/usr/lib/vlang/vlib/builtin/utf8.v", "/usr/lib/vlang/vlib/builtin/map.v", "/usr/
lib/vlang/vlib/builtin/hashmap.v", "/usr/lib/vlang/vlib/builtin/option.v", "/usr/lib/vlang/vlib/strings/builder.v", "/usr/lib/vlang/vlib/strings/similarity.v", "/usr/lib/vlang/vlib/strings/strings.v", "/usr/lib/vlang/vlib/math/math.v", "te
st.v"]
bad arr array_Bar*
bad arr array_Bar*
<path_to_file>/test.tmp.c: In function ‘main__main’:
<path_to_file>/test.tmp.c:4520:22: error: incompatible types when initializing type ‘array_Bar *’ {aka ‘struct array *’} using type ‘array’ {aka ‘struct array’}
 4520 | Foo f= (Foo) { .a =  new_array(0, 1, sizeof( Bar* )) } ;
      |                      ^~~~~~~~~
<path_to_file>/test.tmp.c:4522:11: error: incompatible types when assigning to type ‘array_Bar *’ {aka ‘struct array *’} from type ‘array’ {aka ‘struct array’}
 4522 |  f .a  =  array_repeat(new_array_from_c_array(1, 1, sizeof(Bar), (Bar[]) {  (Bar) { .b =  0 }  }) , 10 ) ;
      |           ^~~~~~~~~~~~
<path_to_file>/test.tmp.c:4525:26: error: ‘tmp2’ is a pointer; did you mean to use ‘->’?
 4525 |  for (int i = 0; i < tmp2.len; i++) {
      |                          ^
      |                          ->
<path_to_file>/test.tmp.c:4526:26: error: ‘tmp2’ is a pointer; did you mean to use ‘->’?
 4526 |  Bar* x = ((Bar* *) tmp2 . data)[i];
      |                          ^
      |                          ->
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

**Comment by Liikt** [comment]
Oh and on a different note for some reason 
```
println("$i => $x")
```
 instead of
 ```
     println(i)
     println(x)
```
 works in neither version. But I think that should be a different Issue

**Comment by medvednikov** [comment]
@Liikt this has just been fixed.

**Comment by Ivo-Balbaert** [comment]
The code at the top now (V 0.1.27 33a9822) gives the error :
	cannot assign `array_Bar` to variable `f.a` of type `array_Bar_ptr`
which seems logical.
Changing the code to (only adding & to f.a = ): 
struct Foo {
mut:
    a []&Bar
}

struct Bar {
    b int
}

fn main() {
    mut f := Foo{}
    f.a = [&Bar{}].repeat(10)
    for i, x in f.a {
        println("$i => $x")
    }
}
makes the code compile and produce the right output:
0 => &Bar {
    b: 0
}
1 => &Bar {
    b: 0
}
2 => &Bar {
    b: 0
}
3 => &Bar {
    b: 0
}
4 => &Bar {
    b: 0
}
5 => &Bar {
    b: 0
}
6 => &Bar {
    b: 0
}
7 => &Bar {
    b: 0
}
8 => &Bar {
    b: 0
}
9 => &Bar {
    b: 0
}
This is tested both on Windows 10 and Ubuntu Linux 19.10, so I think this issue can be closed?
