### ISSUE TITLE
multi-dimensional array support

### ISSUE THREAD

**Issue by 87Idiot** [vlang/v#2207]
Multi-dimensional array comes in handy in a lot of situation, it should be implemented as soon as possible.

**Comment by l8atnight** [comment]
oh, please, please.
this is needed more then most other addon stuff.

**Comment by medvednikov** [comment]
works for me:

```
fn main() {
        a := [1,2,3]
        b := [[1,2,3], [4,5,6]]
        println(b[1][0])
}
```

**Comment by aderthecoder** [comment]
@medvednikov not the unlucky me:
```
fn main() {

    a := [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
    b := [[1, 2], [3, 4]]

    println(a[0][0][0]) // not working
    println(b[1][0]) //=> 3
}
```
```
main.v:7:22: expected `)` but got `[`
    6|     println(b[0][0])
    7|     println(a[0][0][0])
                            ^
    8| }
```

**Comment by medvednikov** [comment]
Thanks @87Idiot, only 2d arrays seem to work.

Will fix today.

**Comment by 87Idiot** [comment]
It's still not working?

**Comment by netmute** [comment]
I would be nice if this case could be handled as well:
```
mut multi := [][]string
```
This happens often when I want to generate an array of arrays in i.e. a `for` loop.

**Comment by kostya** [comment]
I see in game_of_live example of matrix usage, and set value works `new_field[i] [j] = `. But if i use matrix in struct it not works.
```v
struct Matrix {
mut:
  data [] []f64
}

m.data[x] [y] = v
```

```
a.v:14:17: unexpected token: `=`

   14|   m.data[x] [y] = v

                       ^
```

**Comment by Delta456** [comment]
Fixed
