### ISSUE TITLE
const name shadowing

### ISSUE THREAD

**Issue by Eliyaan** [vlang/v#22072]
### Describe the bug

(I'm not sure if it's called like that)
This code is able to reuse the name of a constant on another unrelated variable, and it can cause some mistakes.

### Reproduction Steps

```v
const item = 24

fn main() {
        for i, item in ["abc", "def"] {
                println(item)
        }
}
```

### Expected Behavior

An error telling me that `item` is already used.

### Current Behavior

It just worked

### V version

V 0.4.7

### Environment details (OS name and version, etc.)

linux
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Delta456** [comment]
This code compiles successfully. 

```v
const item = 24

fn main() {
	item := 34
	println(item)
}
```

**Comment by JalonSolov** [comment]
V doesn't allow shadowing of other things, so I agree that this is a bug that it allows shadowing of a const.

**Comment by larpon** [comment]
Good find @Eliyaan
