### ISSUE TITLE
volt.im (the volt instant messaging platform written in v) doesnt work

### ISSUE THREAD

**Issue by astroLazybones** [vlang/v#22080]
### Describe the bug

https://volt.im is advertised on the v website on the [v builtin section](https://vlang.io/#builtinv), but i tried to make an account + login and neither seemed to work. When i made and account it just sent me back to the home page, and when i tried to log in it had an error about related to my account not existing. I also couldnt find anywhere else to put this issue except the r/vlang reddit where someone told me to put this here

### Reproduction Steps

Try to register/login

### Expected Behavior

You should be able to make an account and log in

### Current Behavior

You can not login or make an account, there is no confirmation email

### Possible Solution

the reason is probably that the site is either abandoned or obtained by someone else

### Additional Information/Context

registering/logging in makes a request which has the password in plain text

![20240820_15h54m14s_grim](https://github.com/user-attachments/assets/d118dbe3-6ebf-4c03-b112-135d1bb004b8)

### V version

0.4.7 7baff15 (not really relevant to this situation though)

### Environment details (OS name and version, etc.)

V full version: V 0.4.7 7baff15
OS: linux, "Arch Linux"
Processor: 12 cpus, 64bit, little endian, 12th Gen Intel(R) Core(TM) i5-12400

getwd: /home/astro
vexe: /usr/lib/vlang/v
vexe mtime: 2024-07-29 06:07:35

vroot: NOT writable, value: /usr/lib/vlang
VMODULES: OK, value: /home/astro/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.46.0
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false

CC version: cc (GCC) 14.2.1 20240805
thirdparty/tcc: N/A
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by medvednikov** [comment]
Fixed
