### ISSUE TITLE
Third party libraries do not support Window

### ISSUE THREAD

**Issue by 87Idiot** [vlang/v#2208]
**V version:** V 0.1.21 5ba354f
**OS:** Window 10 64-bit

**What did you do?**
`/d/v/examples/hot_reload $ v -live bounce.v`
`/d/v/vlib/json $ v json_test.v`

**What did you expect to see?**
An executable generates and no any compiler's complain
 
**What did you see instead?**
```
warning: bounce.v:3:6: the following imports were never used:
 * gx
D:\v\thirdparty\glfw/glfw3.dll: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
```
```
D:\v\thirdparty\cJSON\cJSON.o: file not recognized: File format not recognized
```

**Comment by joe-conigliaro** [comment]
@aderthecoder try deleting `D:\v\thirdparty\cJSON\cJSON.o` and running again
