### ISSUE TITLE
V generates invalid code in voidptr returns resulting in segfaults.

### ISSUE THREAD

**Issue by gabixdev** [vlang/v#2210]
**V version:** 0.1.21 5ba354f
**OS:** Debian GNU/Linux 9

**What did you do?**
```
module main

struct Test {
    val int
}

fn (test Test) return_voidptr() voidptr {
    return voidptr(0)
}

fn main() {
    test := &Test{
        val: 123
    }

    if test.return_voidptr() == 0 {
        println('returned a null pointer, everything seems ok')
    }
}
```

**What did you expect to see?**
The code should work and return a message and exit without errors instead of segfaulting.
 
**What did you see instead?**
The resulting C code tries to dereference the returned pointer (which for some reason is casted to a pointer of pointer of the struct?), causing a segmentation fault.

```
void main__main() {
 
Test* test= (Test*)memdup(&(Test)  { .val =  123 } , sizeof(Test)) ;
 
 if (*(Test**)  Test_return_voidptr(* test ) == 0 ) {
 
 println ( tos2((byte*)"returned a null pointer, everything seems ok") ) ;
 
 }
 ;
 
 }
```

**Comment by medvednikov** [comment]
Fixed.
