### ISSUE TITLE
Failed to compile C2V

### ISSUE THREAD

**Issue by jorgeluismireles** [vlang/v#22116]
### Describe the bug

Error after running `v translate hello.c`

### Reproduction Steps

```
$ v translate hello.w
Compiling c2v ...
src/c2v.v:53:6: error: duplicate of a const name `clang`
   51 | fn find_clang_in_path() string {
   52 |     clangs := ['clang-17', 'clang-14', 'clang-13', 'clang-12', 'clang-11', 'clang-10', 'clang']
   53 |     for clang in clangs {
      |         ~~~~~
   54 |         os.find_abs_path_of_executable(clang) or { continue }
   55 |         return clang

Failed to compile C2V. This should not happen. Please report it via GitHub.
```

### Expected Behavior

Compile c into v

### Current Behavior

Bug in C2V

### V version

V 0.4.7 caa0c46

### Environment details (OS name and version, etc.)

V full version: V 0.4.7 99da572.caa0c46
OS: linux, Ubuntu 18.04.6 LTS
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz

getwd: /home/nuchw/gitlab.com/jmireles/v/can
vexe: /home/nuchw/v/v
vexe mtime: 2024-08-25 18:44:08

vroot: OK, value: /home/nuchw/v
VMODULES: OK, value: /home/nuchw/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.17.1
Git vroot status: weekly.2024.32-103-gcaa0c464
.git/config present: true

CC version: cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
thirdparty/tcc status: thirdparty-linux-amd64 0134e9b9

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
Recent change in V caused this.  It's a conflict with a constant here:

https://github.com/vlang/c2v/blob/e2d8b6d10407011082ce0b0a58e06c2af4c5f6f1/src/c2v.v#L42

The problem was allowing a variable to shadow a constant... and that is not allowed any longer.

**Comment by medvednikov** [comment]
Don't we compile c2v in V's CI?

**Comment by JalonSolov** [comment]
Normally, yes, but it's currently disabled.  Not sure why.  Maybe that macos problem causing it to always fail?

**Comment by JalonSolov** [comment]
c2v compiles cleanly with the PR I did, but it is failing the tests on MacOS only due to some changes in Mac headers (according to Alex).

**Comment by spytheman** [comment]
It broke in https://github.com/vlang/c2v/pull/179 , then I tried to fix it, but could not, and then I disabled the CI in the main V repo in 43baa88f60898108c1bf30babf014143466ce3e3 .

**Comment by spytheman** [comment]
> c2v compiles cleanly with the PR I did, but it is failing the tests on MacOS only due to some changes in Mac headers (according to Alex).

Oh, that is nice. I'll try again then.
