### ISSUE TITLE
compile of tvintris.v failed

### ISSUE THREAD

**Issue by wpeckham** [vlang/v#22122]
**V doctor:**
```
V full version: V 0.4.7 bbbb864.05c7aa2
OS: linux, "Manjaro Linux"
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz

getwd: /home/wpeckham/.vmodules
vexe: /home/wpeckham/v/v
vexe mtime: 2024-08-27 20:23:42

vroot: OK, value: /home/wpeckham/v
VMODULES: OK, value: /home/wpeckham/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.46.0
Git vroot status: weekly.2022.24-4876-g05c7aa2c
.git/config present: true

CC version: cc (GCC) 14.2.1 20240805
thirdparty/tcc status: thirdparty-linux-amd64 a0799a5b

```

**What did you do?**
`./v -g -o vdbg cmd/v && ./vdbg sdl/examples/tvintris/tvintris.v`
See attached file `sdl/examples/tvintris/tvintris.v`

**What did you expect to see?**

successful compile

**What did you see instead?**
```
INFO: compile with `v -live sdl/examples/tvintris/tvintris.v `, if you want to use the @[live] function draw_begin .
================== C compilation error (from tcc): ==============
cc: /tmp/v_1000/tvintris.01J6ASNYWK7ANJFGF8V7KP01E7.tmp.c:2696: error: ';' expected (got "sdl__OSEvent")
=================================================================
(You can pass `-cg`, or `-show-c-output` as well, to print all the C error messages).
builder error: 
==================
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by wpeckham** [comment]
Note that this was the tvintris.v I found after "v install sdl".  
The only outdated module is c2v.  
Am I missing something?

**Comment by JalonSolov** [comment]
sdl and c2v don't have anything to do with each other.  I have confirmed this failure.

**Comment by JalonSolov** [comment]
```
$ sdl2-config --version
2.30.6
$
```

**Comment by medvednikov** [comment]
should also be caught by ci

**Comment by larpon** [comment]
`v install sdl` will install a V wrapper compatible with SDL2 v2.0.8. To use `vlang/sdl` you need to checkout the corresponding branch that matches the SDL2 version installed on your system.

This is all documented in the [README.md](https://github.com/vlang/sdl?tab=readme-ov-file#install). We currently can not automate this process due to how `v install`/vpm currently works - we cannot run code/scripts after install to e.g. determine the user's setup.

If you are on a Unix based system you can run `v ~/.vmodules/sdl/setup.vsh` that will try to determine your system install of SDL2 and checkout the corresponding branch in `vlang/sdl`

@wpeckham please also note that you will highly likely need to pass `-d sdl_memory_no_gc` when building/running SDL2 based applications due to problems with V's garbage collector and SDL's memory allocations. (Also documented in the README.md)

Maybe `vpm` could support showing a user facing message from the module upon install or update that hints what to do since we cannot automate such things with vpm currently.

**Comment by JalonSolov** [comment]
If I run the `setup.vsh` script to get the correct branch, it fails in a different way...
```
[jalon@7950x sdl]$ v run setup.vsh
Your version is 2.30.6
The SDL module officially supports these versions of SDL:
   ['2.0.8', '2.0.10', '2.0.12', '2.0.14', '2.0.16', '2.0.18', '2.0.20', '2.0.22', '2.0.9', '2.24.0', '2.26.0', '2.28.0', '2.30.0']
Setting up the repository to branch 2.30.0, that best matches the system SDL version: 2.30.6 ...
branch '2.30.0' set up to track 'origin/2.30.0'.
Switched to a new branch '2.30.0'
[jalon@7950x sdl]$ v -g run examples/tvintris/
INFO: compile with `v -live examples/tvintris/ `, if you want to use the @[live] function draw_begin .
tVintris -- tribute to venerable Twintris
76c551aec987 : at ???: RUNTIME ERROR: invalid memory access
76c551bb0daf : by ???
76c551bf3c60 : by ???
76c551bf901e : by ???
76c551b1a2d9 : by ???
76c551c11883 : by ???
76c551af0dd8 : by ???
/tmp/v_1000/../../../../../../home/jalon/git/sdl/sdl.c.v:82: by sdl__init
/tmp/v_1000/../../../../../../home/jalon/git/sdl/examples/tvintris/tvintris.v:231: by main__SdlContext_set_sdl_context
/tmp/v_1000/../../../../../../home/jalon/git/sdl/examples/tvintris/tvintris.v:294: by main__main
/tmp/v_1000/../../../../../../tmp/v_1000/tvintris.01J6F3JB7YZKMGN5XTPX0STVJ1.tmp.c:65417: by main
[jalon@7950x sdl]$
```

**Comment by larpon** [comment]
@JalonSolov try with `-d sdl_memory_gc` it is a know bug as I describe above.

**Comment by larpon** [comment]
We have an issue tracking it here <https://github.com/vlang/sdl/issues/744#issuecomment-2169253887>

**Comment by JalonSolov** [comment]
Yes, with that option, it works.

**Comment by wpeckham** [comment]
I could find none of that in my README files here, but using those two commands does allow it to compile and run.  

Thank you!

**Comment by wpeckham** [comment]
This should be documented in the distributed files, but that might be considered a different issue.  We can close this.
To resolve ran "v ~/.vmodules/sdl/setup.vsh"
Then compiled with the option "-d sdl_memory_no_gc"

**Comment by wpeckham** [comment]
Resolved using commands and option described.
