### ISSUE TITLE
struct embedding must be declared at the beginning of the struct body

### ISSUE THREAD

**Issue by jorgeluismireles** [vlang/v#22136]
### Describe the bug

From https://docs.vlang.io/structs.html#embedded-structs code I prepend an embedding struct `Size` with `pub:` and doesn't is accepted. This behaviour forces the embedded struct members to remain as defined `pub` and or `mut` at the definition section, file or module?

### Reproduction Steps

```
struct Size {
mut:
	width  int
	height int
}

fn (s &Size) area() int {
	return s.width * s.height
}

struct Button {
pub: // <-- adding this here 
	Size
	title string
}
```

### Expected Behavior

compile and set the access defined?

### Current Behavior

```
bug.v:15:2: error: struct embedding must be declared at the beginning of the struct body
   13 | struct Button {
   14 | pub:
   15 |     Size
      |     ~~~~
   16 |     title string
   17 | }
```

### V version

V 0.4.7 8ebc288

### Environment details (OS name and version, etc.)

...
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
Their access is as set in the struct you are embedding.  So if you want them to be `pub`, you have to set the fields as `pub` in the original struct.

**Comment by spytheman** [comment]
This is not a bug, it is working as designed.
