### ISSUE TITLE
Binary crashes when compiled with tcc on OpenBSD

### ISSUE THREAD

**Issue by lcheylus** [vlang/v#22156]
### Describe the bug

When building on OpenBSD/amd64 with TCC compiler, the resulting binary crashes during execution.

### Reproduction Steps

- Build Vlang with Clang (version 16.0.6, default C compiler) on OpenBSD/amd64
```bash
$ v version
V 0.4.7 f61a4f1
```
- Install TCC compiler on OpenBSD via `tcc` package: `pkg_add tcc`
```bash
$ which tcc
/usr/local/bin/tcc

$ tcc -v
tcc version 0.9.27 2023-07-05 mob@5b28165 (x86_64 OpenBSD)
```
- Build `detect_tcc` binary with V using TCC compiler
```bash
$ ./v -cc /usr/local/bin/tcc -cg -keepc -showcc -o /tmp/detect_tcc cmd/tools/detect_tcc.v
> C compiler cmd: '/usr/local/bin/tcc' '@/tmp/v_1000/detect_tcc.tmp.c.rsp'
> C compiler response file "/tmp/v_1000/detect_tcc.tmp.c.rsp":
  -g -o "/tmp/detect_tcc" -D GC_BUILTIN_ATOMIC=1 -D GC_THREADS=1 -I "/usr/local/include" "/tmp/v_1000/detect_tcc.tmp.c" -std=c99 -D_DEFAULT_SOURCE -bt25 -rdynamic "/usr/local/lib/libgc.a" -lpthread
```

### Expected Behavior

No crash when exec a binary built with V and TCC compiler

### Current Behavior

The resulting binary built with V and TCC crashes:
```bash
$ file /tmp/detect_tcc
/tmp/detect_tcc: ELF 64-bit LSB shared object, x86-64, version 1

$ /tmp/detect_tcc
detect_tcc:/tmp/detect_tcc: undefined symbol '__data_start'
ld.so: detect_tcc: relocation failed
Killed
```

### Possible Solution

I don't know why there is an `undefined symbol '__data_start'` error for the binary compiled with TCC. Perhaps, on OpenBSD, we have to use specific compiler flags with TCC?

### Additional Information/Context

On OpenBSD, TCC is compiled/packaged using ports. See `Makefile` / compiler flags to package it here => https://github.com/openbsd/ports/blob/master/lang/tcc/Makefile

### V version

V 0.4.7 f61a4f1

### Environment details (OS name and version, etc.)

V full version: V 0.4.7 f61a4f1
OS: openbsd, 7.6, GENERIC.MP#296
Processor: 2 cpus, 64bit, little endian

getwd: /home/fox/dev/vlang.git
vexe: /home/fox/dev/vlang.git/v
vexe mtime: 2024-09-03 12:33:22

vroot: OK, value: /home/fox/dev/vlang.git
VMODULES: OK, value: /home/fox/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.46.0
Git vroot status: weekly.2024.36-3-gf61a4f17-dirty
.git/config present: true

CC version: OpenBSD clang version 16.0.6
thirdparty/tcc status: thirdparty-unknown-unknown de82a130
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by lcheylus** [comment]
No error during exec when using Clang to compile a binary on OpenBSD/amd64.

Compile with Clang and exec `cmd/tools/detect_tcc.v`
```bash
$ clang -v
OpenBSD clang version 16.0.6
Target: amd64-unknown-openbsd7.6
Thread model: posix
InstalledDir: /usr/bin

$ ./v -cc clang -cg -keepc -showcc -o /tmp/detect_tcc cmd/tools/detect_tcc.v
> C compiler cmd: 'clang' '@/tmp/v_1000/detect_tcc.tmp.c.rsp'
> C compiler response file "/tmp/v_1000/detect_tcc.tmp.c.rsp":
  -g -O0 -o "/tmp/detect_tcc" -D GC_BUILTIN_ATOMIC=1 -D GC_THREADS=1 -I "/usr/local/include" "/tmp/v_1000/detect_tcc.tmp.c" -std=c99 -D_DEFAULT_SOURCE -rdynamic "/usr/local/lib/libgc.a" -lpthread

$ /tmp/detect_tcc

Note: `tcc` was not used, so unless you install it yourself, your backend
C compiler will be `cc`, which is usually either `clang`, `gcc` or `msvc`.

These C compilers, are several times slower at compiling C source code,
compared to `tcc`. They do produce more optimised executables, but that
is done at the cost of compilation speed.

```

**Comment by spytheman** [comment]
tcc 5b28165 is from 2023-07-05, and there are 116 commits in the tcc's mob branch since then.

Please try compiling a custom tcc from its most recent commit, with something like this script:
```sh
git clone git://repo.or.cz/tinycc.git
cd tinycc
./configure  --config-bcheck=yes --config-backtrace=yes --debug
make
make install
```

**Comment by spytheman** [comment]
Afaik `__data_start` should come from the garbage collector (i.e. `thirdparty/libgc/gc.c`) 🤔 .

So another thing you could try is making sure that you have libgc installed, then use `-d dynamic_boehm` to force V to link to it:

`./v -d dynamic_boehm -cc /usr/local/bin/tcc -cg -keepc -showcc -o /tmp/detect_tcc cmd/tools/detect_tcc.v`

**Comment by spytheman** [comment]
(the relevant .v file, if you need to change it is `vlib/builtin/builtin_d_gcboehm.c.v`)

**Comment by lcheylus** [comment]
@spytheman Thanks for your analysis :)

With `-d dynamic_boehm`, compilation is OK with TCC on OpenBSD and the resulting binary works as expected :)
```bash
$ ./v -d dynamic_boehm -cc /usr/local/bin/tcc -cg -keepc -showcc -o /tmp/detect_tcc cmd/tools/detect_tcc.v
> C compiler cmd: '/usr/local/bin/tcc' '@/tmp/v_1000/detect_tcc.tmp.c.rsp'
> C compiler response file "/tmp/v_1000/detect_tcc.tmp.c.rsp":
  -g -o "/tmp/detect_tcc" -D GC_THREADS=1 -I "/usr/local/include" -L "/usr/local/lib" "/tmp/v_1000/detect_tcc.tmp.c" -std=c99 -D_DEFAULT_SOURCE -bt25 -rdynamic -lgc -pthread

$ /tmp/detect_tcc
Your `tcc` is working. Good - it is much faster at compiling C source code.
```

I will do some further debug in `vlib/builtin/builtin_d_gcboehm.c.v` to fix the build with TCC on OpenBSD. By default, Boehm-GC is used on OpenBSD for V.
