### ISSUE TITLE
Calling function with struct as return type

### ISSUE THREAD

**Issue by devopsample** [vlang/v#2215]
**V version:** 
0.1.20 918edad

**OS:** 
Windows

**What did you do?**
```
fn C.nk_font_atlas_add_default(nk_font_atlas C.nk_font_atlas, height f32, nk_font_config C.nk_font_config) C.nk_font

font := C.nk_font_atlas_add_default(&atlas, 13, 0)
```

**What did you expect to see?**
No error
 
**What did you see instead?**
```error: variable or field 'font' declared void```

**Comment by adlesh** [comment]
This may an issue, but you may want to specify that's an issue with C structs and not V structs. You can return a V struct no issue. I don't have C code atm to test w/ C structs

**Comment by Delta456** [comment]
The current error now:

```
foo.v:3:1: warning: unused variable: `font`
    1 | fn C.nk_font_atlas_add_default(nk_font_atlas C.nk_font_atlas, height f32, nk_font_config C.nk_font_config) C.nk_font
    2 | 
    3 | font := C.nk_font_atlas_add_default(&atlas, 13, 0)
      | ~~~~
foo.v:3:38: error: undefined ident: `atlas`
    1 | fn C.nk_font_atlas_add_default(nk_font_atlas C.nk_font_atlas, height f32, nk_font_config C.nk_font_config) C.nk_font
    2 | 
    3 | font := C.nk_font_atlas_add_default(&atlas, 13, 0)
      |                                      ~~~~~
```

As `atlas` is not defined then it should be an error and a warning for `font` not being used.

@devopsample Can I close this issue now as it seems to be fixed.
