### ISSUE TITLE
Compiling frontpage example (program that fetches top Hacker News stories) fails on Windows

### ISSUE THREAD

**Issue by phicore** [vlang/v#2219]
V version: 0.1.21 ac7824b
OS: Win 10 x64 1903

What did you do?

What did you expect to see?
Sucessfull compiled program

What did you see instead?

```

check() next token ={
print_backtrace_skipping_top_frames is not implemented on this platform for now...

toto.v:15:18: expected name but got )
14| for _ in 0..8 {
15| go fn() {
^
16| for {
17| lock {

```

**Comment by phicore** [comment]
V version: 0.1.21 ac7824b
OS: Win 10 x64 1903

What did you do?

What did you expect to see?
sucessfull compiled porgram

What did you see instead?
`
check()
next token = `{`
print_backtrace_skipping_top_frames is not implemented on this platform for now...

toto.v:15:18: expected `name` but got `)`
   14|     for _ in 0..8 {
   15|         go fn() {
                        ^
   16|             for {
   17|                 lock { 

`

**Comment by bitcartel** [comment]
This error is reproducible with:
V 0.1.22 a6a233d
x86_64-linux-gnu

**Comment by Ivo-Balbaert** [comment]
It is hard to tell which code failed, this example was probably removed from the website.
Anyhow, news_fetcher.v from examples works just fine in Windows 10, so this item could perhaps be closed.

**Comment by madranet** [comment]
> It is hard to tell which code failed, this example was probably removed from the website.

Nope.  The example is still there:  https://vlang.io/compare

and it fails to compile on OSX too:

```v
ᐅ  v run hnreader.v
next token = `{`
hnreader.v:15:17: syntax error: unexpected `)`, expecting `name`
   13|     mut cursor := 0
   14|     for _ in 0..8 {
   15|         go fn() {
                       ^
   16|             for {
   17|                 lock {
```

I'll have a look at `news_fetcher.v` in the examples, as you suggest.  But meantime someone ought to do a bit of proof-reading up on the website. It doesn't make a good impression on new visitors to a language website, when the provided examples don't compile.

**Comment by madranet** [comment]
UPDATE:

The `news_fetcher.v` from the examples doesn't compile for me either:

```v
v run news_fetcher.v


news_fetcher.v:13:37: unknown type `sync.PoolProcessor`
   11| }
   12|
   13| fn worker_fetch(p &sync.PoolProcessor, cursor int, worker_id int) voidptr {
                                           ^
   14| 	id := p.get_item<int>(cursor)
   15| 	resp := http.get('https://hacker-news.firebaseio.com/v0/item/${id}.json') or {
```
