### ISSUE TITLE
Will V never support dependent types?

### ISSUE THREAD

**Issue by zaoqi** [vlang/v#222]
Because #182

**Comment by medvednikov** [comment]
They are discussed here:

https://github.com/vlang/v/issues/175

I haven't done research on this topic yet.

**Comment by zaoqi** [comment]
@medvednikov

Having the same declaration and assignment syntax will prevent dependent types support.

**Comment by medvednikov** [comment]
Only for arrays.

**Comment by zaoqi** [comment]
@medvednikov

> Only for arrays.

Then it is difficult to add support for dependent types in the future.
