### ISSUE TITLE
Function returning two values cannot be used on the RHS of assigment statement

### ISSUE THREAD

**Issue by avitkauskas** [vlang/v#2227]
**V version:** V 0.1.21 f45d3f0
**OS:** Mac OS

**What did you do?**
```v
fn function_returning_two_values() (int, int) {
    return 1, 2
}

mut one := 0
mut two := 0
one, two = function_returning_two_values()
```

**What did you expect to see?**
`one` assigned 1 and `two` assigned 2
 
**What did you see instead?**
```
test2.v:7:40: expected `:=` but got `=`
    6| mut two := 0
    7| one, two = function_returning_two_values()
```

**Comment by avitkauskas** [comment]
One more thing. If you put the function definition in the end of the code, nothing changes if you leave the assigment `=` statement as is. 
```v
mut one := 0
mut two := 0
one, two := function_returning_two_values()

fn function_returning_two_values() (int, int) {
    return 1, 2
}
```
But if you try to change it to `:=` (as error message "suggests") then you get the following error:
```
test2.v:3:41: undefined: `function_returning_two_values`
    2| mut two := 0
    3| one, two := function_returning_two_values()
```
Though with the function definition on top, you get correct error complaining about the redefinition of `one`:
```
test2.v:7:3: redefinition of `one`
    6| mut two := 0
    7| one, two := function_returning_two_values()
```

**Comment by avitkauskas** [comment]
Things to consider:
- What if I use multiple-return function in a definition statement where some of the variables were defined already and some were not? Could compiler allow for that if the defined variables were mutable?
- we now cannot define some `mut` and some immutable variables when assigning values from the multi-return function:
```
one, two := function_returning_two_values() // both immutable
mut one, two := function_returning_two_values() //both mutable
one, mut two := function_returning_two_values() // Error: expected `name` but got `mut`
```

**Comment by joe-conigliaro** [comment]
I have dont this in https://github.com/vlang/v/pull/2237

It checks the mutability of each existing variable before assignment. I think i have tested every possibility. Maybe I missed something, if so we will find out soon :),

**Comment by avitkauskas** [comment]
Nice! The only thing left is this:
```v
a, mut b := foo()**
```
This does not work now. Should it be allowed?
If I do this:
```v
mut a, mut := foo()
```
both `a` and `b` becomes mutable.

**Comment by joe-conigliaro** [comment]
yeah, Im not sure if that should even be allowed, for cases like that its possible to define the variables first. Would see that @medvednikov things, but personally I dont think its important.

**Comment by medvednikov** [comment]
I think `a, mut b := foo()` should be allowed.

You can't define a variable first here @joe-conigliaro, since `a` will become mutable:

```mut a := 0 
mut b := 0
a, b = foo()
```

But we want `a` to be immutable.

**Comment by medvednikov** [comment]
@joe-conigliaro suggested using 

```v
mut b := 0
a, b := foo()
```

But I find it less readable that `a, mut b := foo()`

And I forgot that V now allows reusing the same variable for definitions, like Go:

```
var err int
a, err := foo()
b, err := foo()
```

What do you think about this @avitkauskas ?

**Comment by avitkauskas** [comment]
I think that
```v
mut b := 0
a, b := foo()
```
is a work-around now, but 
```v
a, mut b := foo()
```
would be fine if it's it not too coplicated to implement.

This proably also has some indirect relation to the former request to let indicate mutability etc. for the stucture members individualy:
```v
struct A {
    mut a int
    b int
    mut c int
    pub mut d int
```

**Comment by medvednikov** [comment]
Yes, we agreed to that.

`a, mut b := foo()` will be implemented.

**Comment by joe-conigliaro** [comment]
Yep I'm onto it, thanks @avitkauskas, thanks @medvednikov

**Comment by joe-conigliaro** [comment]
This was done in https://github.com/vlang/v/pull/2251
