### ISSUE TITLE
llx is not portable, must use PRIx64 from <inttypes.h>

### ISSUE THREAD

**Issue by radare** [vlang/v#2228]
**V version:** V 0.1.21 f45d3f0
**OS:** macOS 10.14

**What did you do?**

git grep llx

**What did you expect to see?**

nothing
 
**What did you see instead?**

```
$ git grep llx
vlib/builtin/int.v:     count := int(C.sprintf(*char(hex), '0x%llx', n))
```

i would suggest to integrate LGTM Ci service to catch those issues, as well as using clang-analyzer

**Comment by medvednikov** [comment]
You are right, just learned about PRIx64 yesterday.

clang-analyzer will be added, good idea.
