### ISSUE TITLE
https://vlang.io/ Site typographical error

### ISSUE THREAD

**Issue by qq892640791** [vlang/v#2235]
![无标题2](https://user-images.githubusercontent.com/28526232/66253387-141dfc00-e79a-11e9-87a9-a93c32bd9e6c.png)
这个应该是正常的吗？
另外我想有二进制文件下载是必要的，在官网和github/release,一些人比如我只是想尝试一下v语言，提供二进制文件是很友好的，为了尝试v去下载visualstudio是很愚蠢的，只使用visualstudio c/c++要超过8GB硬盘
Should this be normal? Also I think there is a binary file download is necessary in the official website and github/release, some people like I just want to try v language, providing the binary file is very friendly, in order to try v to download visualstudio is very stupid, only use visualstudio c/c To more than 8GB hard drive

**Comment by d1y** [comment]
我也好奇为啥官方不`release`二进制文件
I am also curious as the official does not `release` binary file.

**Comment by tomByrer** [comment]
The website repo is https://github.com/vlang/website

I agree that a binary would be nice, but I think this is Alpha stage in development now?

Most developers have to install a C compiler to run node-scss & various other website and programming tools..

**Comment by nedpals** [comment]
alex has pulled out the download links for the prebuilt binaries for now but he's working on it

**Comment by d1y** [comment]
> alex has pulled out the download links for the prebuilt binaries for now but he's working on it

是的, 现在编译的二进制文件只有mac下的, 希望在 `release` 尽快给出 linux 和 win 编译版本文件, 尤其是`windows`, 编译要一堆东西

Yes, now only the compiled binary files are under mac. I hope to give Linux and win compiled version files as soon as `release', especially `windows'. Compiling requires a lot of things.

**Comment by Bowero** [comment]
This thread can be continued in the `website` repository. The corresponding thread is [this one](https://github.com/vlang/website/issues/97)
