### ISSUE TITLE
bug in `return` `match` statement when result/option is involved

### ISSUE THREAD

**Issue by larpon** [vlang/v#22389]
### Describe the bug

C error when compiling/running the code below.

### Reproduction Steps

`v run t.v` where `t.v` is:

```v
fn main() {
	install_command(['github:some/thing'], 1) or { panic(err) }
}

pub fn install_command(args []string, verbosity int) ! {
	if args.len == 0 {
		return error('${@FN} requires an argument')
	}
	component := args[0]
	if component.count(':') == 0 {
		return install_command(['github:${component}'], verbosity)
	}
	source := component.all_before(':')
	if source != 'github' {
		return error('${@FN} unknown source `${source}`')
	}
	unit := component.all_after(':')
	return match source {
		'github' {
			install_from_github(unit, verbosity)! // This may be the source of the bug
		}
		else {
			error('${@FN} unknown source `${source}`')
		}
	}
}

fn install_from_github(unit string, verbosity int) ! {
	dump(unit)
}
```

### Expected Behavior

A dump containing `github:some/thing`

### Current Behavior

```
================== C compilation error (from tcc): ==============
cc: /dev/shm/t.01J96XST9RZXQFCP1MVM8T9YT2.tmp.c:13397: error: declaration of an array of incomplete type elements
=================================================================
(You can pass `-cg`, or `-show-c-output` as well, to print all the C error messages).
builder error: 
==================
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .
```

### V version

V 0.4.8 5e00270

### Environment details (OS name and version, etc.)

Linux / EndeavourOS (Arch-based)
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by jorgeluismireles** [comment]
I've notice compiler c errors, when trying to save to write a lot of `return` and use something like this for options or results:
```v
return match x {
  one { fn_returning_option() }
  two { none }
  three { fn_returning_string() }
}
```
The compiler instead don't present the problem when I use `return` for each case:
```v
match x {
  one { return fn_returning_option() }
  two { return none }
  three { return fn_returning_string() }
}
```
Seems the compiler has no clue in what type **all** cases should return, don't know if the list of cases is checked for the "first" one to get the type as when we use an array specifying the first element:
```v
c := [ u8(1), 2, 3 ]
```
