### ISSUE TITLE
gg text rendering is clunky on Linux

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#2239]
Works great on macOS:

<img src='https://cdn.discordapp.com/attachments/608962858268753920/625880552351858688/Screen_Shot_2019-09-24_at_05.25.18.png'>

But on Linux its's very clunky:

<img src='https://url4e.com/gyazo/images/e5da35c2.png'>

On both systems freetype is used.

I don't have any experience with text rendering, so I obviously messed something up in freetype.v

**Comment by medvednikov** [comment]
Wayland vs xorg maybe?

**Comment by joefiorini** [comment]
Looks blurry, was that rendered in Wayland with HiDPI (retina screen)?

**Comment by gslicer** [comment]
@joefiorini I do not think this has to do with the physical display, rather with some lib-versions or compositor (for me Wayland renders also nicer fonts) or it might be even the gfx-drv being used?

...also it looks like the resolution/font-size is different in the examples given so a direct comparison is not meaningful

**Comment by medvednikov** [comment]
Good point, I'll post a hidpi linux screenshot soon.

**Comment by medvednikov** [comment]
Fixed by using Sokol/fontstash
