### ISSUE TITLE
Any update about release date?

### ISSUE THREAD

**Issue by stefanos82** [vlang/v#224]
@medvednikov You are killing us man...hahaha, 5 more days and we are entering June.

Can't you release it as it is? Don't worry about bugs, we will do our best to help you fix as many as possible.

I really want to get my hands dirty with V!

**Comment by medvednikov** [comment]
I'm working hard to release it asap.

I don't name precise dates, it'll happen in June.

**Comment by medvednikov** [comment]
I guess it's safe to say it'll be before June 20.

**Comment by PavelVozenilek** [comment]
It would be nice, if there's a text file with hints for people who will attempt to read the source. Something like: start here, then go there, and then that. This directory is interesting only if you do X, and so on.

**Comment by stefanos82** [comment]
I agree with you @PavelVozenilek.

Agony is killing me to be honest with you, because I want to use this tool and I have no idea what does what.

Yes, I know Go, but I don't know what things behave differently under V so...indeed we really need a guidance or a pseudo table of contents to fully comprehend this new language.

A few more days left...

**Comment by medvednikov** [comment]
I'll document the source. It's very easy to read though. There are very few files: parser.v, scanner.v, token.v, gen.v, fn.v, and main.v. That's it :)

V is a simple language, it promotes writing software in a simple way.

**Comment by stefanos82** [comment]
I seriously can't wait to try it.

**Comment by PavelVozenilek** [comment]
That file may also contain explanation of abbreviations and acronyms used throughout the code.

**Comment by data-man** [comment]
> There are very few files: parser.v, scanner.v, token.v, gen.v, fn.v, and main.v.

I think the list of stdlib's files is more interesting. ;-)

**Comment by medvednikov** [comment]
@PavelVozenilek as you requested:

https://github.com/vlang/v

:)
