### ISSUE TITLE
check error: wrong unicode character error

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#22427]
### Describe the bug

wrong unicode character error

### Reproduction Steps

```v
	a := "\\u306aefgh"
	
	mut expected := "\\u306a"
	expected += "efgh"
	
 	assert a == expected
 ```

### Expected Behavior

not error

### Current Behavior

```sh
code.v:18:9: error: unicode character exceeds max allowed value of 0x10ffff, consider using a unicode literal (\u####)
   16 | //     println("\\u306ae")
   17 |     
   18 |     a := "\\u306aefgh"
      |            ~~~~~~~~
   19 |     
   20 |     mut expected := "\\u306a"
```

### V version

V 0.4.8 4f9df0d

### Environment details (OS name and version, etc.)

Ubuntu
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by esquerbatua** [comment]
Seems like if you use two `\` tries to parse one more value of the unicode character.
With only one it's working well:
```v
a := "\u306aefgh"

mut expected := "\u306a"
expected += "efgh"

assert a == expected
```
