### ISSUE TITLE
match expressions expecting `Result(SumType)` error on yielding `SumType`'s struct values

### ISSUE THREAD

**Issue by edam** [vlang/v#22435]
### Describe the bug

When
* a match-expression is expecting to yield a `Result(SumType)`, and
* a match clause yields a `Struct` which is one of `SumType`'s types
Then the compiler complains that the value does not meet the requirements of the `Result` interface.

### Reproduction Steps

```
type SumType = int | Struct

struct Struct {}

fn foo(x SumType) !SumType {
	return match x {
		int { 5 }
		else { Struct{} }
	}
}
```

### Expected Behavior

Should cause no error.

### Current Behavior

Error:
```
main.v:6:9: error: `Struct` doesn't implement method `msg` of interface `IError`
    4 |
    5 | fn foo(x SumType) !SumType {
    6 |     return match x {
      |            ~~~~~~~~~
    7 |         int { 5 }
    8 |         else { Struct{} }
main.v:6:9: error: `Struct` doesn't implement method `code` of interface `IError`
    4 |
    5 | fn foo(x SumType) !SumType {
    6 |     return match x {
      |            ~~~~~~~~~
    7 |         int { 5 }
    8 |         else { Struct{} }
```

### Additional Information/Context

Replacing the value in the `else{}` clause with either of the following fixes the error:
* 7
* `SumType(Struct{})`

However, replacing the else clause value with
* `foo()`
Where foo is `fn foo() Struct`

Still fails in the same way.

So it would seem that the error is triggered specifically when using one of the sumtype's struct types.

This is a fairly recent error. This code compile in Feb 2023.

### V version

V 0.4.8 5a33c36

### Environment details (OS name and version, etc.)

MacOS
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by jorgeluismireles** [comment]
I've had found this problem when a single return is used with match and Result/Option. A workaround is to use not a single return but each for every case:
```v
type SumType = int | Struct

struct Struct {}

fn foo(x SumType) !SumType {
	match x {
		int { return 5 }
		else { return Struct{} }
	}
}
```

**Comment by edam** [comment]
Another workaround is to go
``` v
type SumType = int | Struct

struct Struct {}

fn foo(x SumType) !SumType {
	return match x {
		int { 5 }
		else { SumType(Struct{}) }
	}
}
```
