### ISSUE TITLE
unclosed if check

### ISSUE THREAD

**Issue by esquerbatua** [vlang/v#22478]
### Describe the bug

Check of unclosed if don't work as expected

### Reproduction Steps

Run:
```v
fn main() {
    mut index := 0
    if true {
        if true {
        } else {
            if false {
                index++
        }
    } else {
        println("else")
    }
}
```

### Expected Behavior

get a similar error like:
![image](https://github.com/user-attachments/assets/6c5d40c6-786d-403e-acc0-3e560b31d05f)

### Current Behavior

![image](https://github.com/user-attachments/assets/ee73198a-43d2-4507-aab4-99fb41c1c022)

### V version

V full version: V 0.4.8 469b56e.7cdd667

### Environment details (OS name and version, etc.)

V full version: V 0.4.8 469b56e.7cdd667
OS: linux, Ubuntu 24.04.1 LTS
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 7840HS w/ Radeon 780M Graphics

vexe: /home/esquerbatua/git/v/v
vexe mtime: 2024-10-10 14:53:52

vroot: OK, value: /home/esquerbatua/git/v
VMODULES: OK, value: /home/esquerbatua/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.43.0
Git vroot status: weekly.2024.41-4-g7cdd6677
.git/config present: true

CC version: cc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
thirdparty/tcc status: thirdparty-linux-amd64 0134e9b9
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
I think the parser error is correct. Since looks like you are trying to add two `else` part.

**Comment by felipensp** [comment]
Despite the indetation... it looks:
```v
fn main() {
    mut index := 0
    if true {
        if true {
        } else {
            if false {
                index++
        	}
    	} else {
	        println("else")
	    }
}
```

**Comment by esquerbatua** [comment]
> Despite the original indetation... it looks like:
> 
> ```v
> fn main() {
>     mut index := 0
>     if true {
>         if true {
>         } else {
>             if false {
>                 index++
>         	}
>     	} else {
> 			println("else")
> 		}
> }
> ```

Perfect, i close it
