### ISSUE TITLE
Structs wrongly appear as redeclared after their scope of declaration ends

### ISSUE THREAD

**Issue by zeozeozeo** [vlang/v#22482]
### Describe the bug

Structs defined inside non-global scopes are not removed from the global scope after their scope of declaration ends. This makes structs defined in other functions/lower scopes wrongly appear as redeclared.

### Reproduction Steps

```v
fn main() {
	struct Foobar {
		foo int
	}
	fb := Foobar{5}
	assert fb.foo == 5
	x()
}

fn x() {
	struct Foobar {
		baz string
	}
	fb := Foobar{"hello world!"}
	println(fb.baz)
}
```
or just
```v
fn main() {
	{
		struct Foobar {
			foo int
		}
	}
	struct Foobar {
		bar int
	}
}
```

### Expected Behavior

stdout:
```
hello world!
```

### Current Behavior

```
test.v:11:9: error: cannot register struct `Foobar`, another type with this name exists
    9 |
   10 | fn x() {
   11 |     struct Foobar {
      |            ~~~~~~
   12 |         baz string
   13 |     }
```

### Possible Solution

There needs to be a way to have multiple symbols for different scopes for the same struct names, or they should somehow be removed from the table after the parser ends the scope.

### Additional Information/Context

Struct definitions inside functions were added in https://github.com/vlang/v/commit/a2d385aee3f1295966991ab9caf1d98319de479d.
Related issue https://github.com/vlang/v/issues/22437 was fixed in https://github.com/vlang/v/pull/22449, but this issue still persists.

### V version

V 0.4.8 7cdd667

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.8 469b56e.7cdd667
OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 10 cpus, 64bit, little endian,

getwd: C:\Users\user\Downloads
vexe: C:\Users\user\Desktop\Code\v\v.exe
vexe mtime: 2024-10-10 17:23:09

vroot: OK, value: C:\Users\user\Desktop\Code\v
VMODULES: OK, value: C:\Users\user\.vmodules
VTMP: OK, value: C:\Users\user\AppData\Local\Temp\v_0

Git version: git version 2.42.0.windows.1
Git vroot status: 0.4.8-81-g7cdd6677
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc status: thirdparty-windows-amd64 b425ac82
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
Yes, this is a known issue. Currently it is not supposed to work since the symbol names are unique disregarding its scope.
This requires a large changing about symbol resolution (performance drawbacks) related to scope usage.

**Comment by spytheman** [comment]
If you do intend to use that feature for `go2v`, it can not wait until 0.6.

**Comment by spytheman** [comment]
We could add another level of indirection in the struct names, similar to how anonymous structs are implemented (they have an internal name, that is unique).

**Comment by medvednikov** [comment]
Good points.
