### ISSUE TITLE
veb, macOS file write error for large files, `NS_ERROR_NET_PARTIAL_TRANSFER`

### ISSUE THREAD

**Issue by timurgordon** [vlang/v#22489]
### Describe the bug

Writing a large (~11MB) pdf file fails on macOS, works on linux. Digging in, in `handle_write_file`, [`send_string_pointer`](https://github.com/vlang/v/blob/5aa6eaf38b06c956bbb643b4fc4f118ccef023ce/vlib/veb/veb.v#L276) fails. It seems that `C.send()` fails in there, outputting `net: op timed out; code: 9`.

Each request certain amount of bytes are sent before this occurs (sometimes 1-2 MB sometimes hundreds KB).

### Reproduction Steps

```
module main

import veb

pub struct App{}

pub struct Context{
    veb.Context
}

pub fn (app &App) index(mut ctx Context) veb.Result {
    return ctx.file(<path_to_large_file>)
}

pub fn main() {
    mut app := &App{}
    veb.run_at[App, Context](mut app, 8080) or { panic(err) }
}
```

### Expected Behavior

For the file to be served fully successfully.

### Current Behavior

`NS_ERROR_NET_PARTIAL_TRANSFER` Full file isn't being transferred.

### Additional Information/Context

Same code works on OS: linux, Ubuntu 23.10, Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 3800X 8-Core Processor

### V version

 V 0.4.8 11551aa

### Environment details (OS name and version, etc.)

OS: macos, macOS, 14.2.1, 23C71
Processor: 8 cpus, 64bit, little endian, Apple M2
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by martinskou** [comment]
Can confirm this error.

A quick fix is to change the TcpConn instanciation in line 273 in veb.v:
```
		mut conn := &net.TcpConn{
			sock:        net.tcp_socket_from_handle_raw(fd)
			handle:      fd
			is_blocking: false
		}
```

to:

```
		mut conn := &net.TcpConn{
			sock:        net.tcp_socket_from_handle_raw(fd)
			handle:      fd
			is_blocking: false
			write_timeout: 30*time.second // added this timeout
		}
```

You can copy the veb folder to your own src directory and make the modification there. 

Use
```
v wipe-cache
```
to make sure veb is recompiled.

I'm not sure it's the *right* solution though?
