### ISSUE TITLE
Generated match code for sumtypes with embedded members causes C errors

### ISSUE THREAD

**Issue by edam** [vlang/v#22481]
### Describe the bug

When using `match` on a sumtype to access a member present in all variants, but where that member is in an embedded struct in one variant, the C code is generated incorrectly and appends the embedded struct name when accessing *all* variants of the sumtype.

### Reproduction Steps

``` v
type SumType = StructA | StructB

struct StructA {
	member string
}

struct StructB {
	StructA
}

fn get_member(st SumType) string {
	match st {
		StructA, StructB {
			return st.member
		}
	}
}
```

### Expected Behavior

Code should complie

### Current Behavior

Compiler causes C error:

```
================== C compilation error (from cc): ==============
cc: /tmp/v_503/bug-sumtype-embedded-member.01J9VN69CT4FPD3NPZB806NEXK.tmp.c:13452:37: error: no member named 'StructA' in 'struct main__StructA'
cc:                 string _t1 = (*st._main__StructA).StructA.member;
cc:                              ~~~~~~~~~~~~~~~~~~~~ ^
cc: 1 error generated.
================================================================
(You can pass `-cg`, or `-show-c-output` as well, to print all the C error messages).
builder error:
==================
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .
```

### Possible Solution

None

### Additional Information/Context

Generated C code at fault:
``` c
// TypeDecl
VV_LOCAL_SYMBOL string main__get_member(main__SumType st) {
	if (st._typ == 102 /* main.StructA */) {
		string _t1 = (*st._main__StructA).StructA.member; // WRONG -- StructA has no StructA member!
		return _t1;
	}
	else if (st._typ == 103 /* main.StructB */) {
		string _t2 = (*st._main__StructB).StructA.member;
		return _t2;
	}
	
	return (string){.str=(byteptr)"", .is_lit=1};
}
```

### V version

V 0.4.8 51b471b

### Environment details (OS name and version, etc.)

MacOS
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by edam** [comment]
If matches are done separately, e.g.:
```v
	match st {
		StructA {
			return st.member
                 }
                 StructB {
			return st.member
		}
	}
```
then there is no problem.

**Comment by edam** [comment]
It seems that only one `ast.SelectorExpr` is generated for the following code:
```v
	match st {
		StructA, StructB {
			return st.member
		}
	}
```
since there is only one branch. Whereas in the example in the previous comment, there are two generated.

The `SelectorExpr` has a `from_embed_types` field, which is the name(s) of the embedded type (`StructA` in this case). Since this field exists in the `SelectorExpr` then the solution must be one of the following:

* make `from_embed_types` a map of types -> embedded types for each type (so it can be used for all matched types in a match branch)
* detect that the embedded types are different and generate 2 SelectorExpr, 1 for each match type, instead of 1 for the branch

**Comment by edam** [comment]
Fundementaly, `find_field()`, `find_field_from_embeds()`, `fiend_field_with_embeds()`, `find_method()`, `find_method_from_embeds()` and `find_method_with_embeds()` and all incompatible with aggregate types, since aggregate types may have multiple different answers (as is the case here).

I see three implementation solutions, all with drawbacks:
* remove aggregate types
  * Drawback: slightly larger generated AST; one match branch per type. (Are there other places  aggregate types are used?)
* change the above functions to return multiple fields and embed_types and update `ast.SelectorExpr` to handle multiple embed types, rather than just one.
  * Drawback: suboptimal; all calls to the `find_*()` functions above will need to return `[][]Type`, rather than `[]Type`, and selector expressions will have `[][]Type` embedding information, rather than `[]Type`. So higher initialisation overheads, higher memory requirements and more complex/slower data access in code which I presume is hit often during compilation.
* a "hybrid" solution, where the `find_*()` functions above all panic on aggregate types, and special functions when an aggregate type may be present, (e.g.,`find_aggregate_field_from_embeds()` and `find_aggregate_method_from_embeds()`) which handle multiple resu;ts properly and return `([]StructField, [][]Type)`.
  * Drawback: complexity

**Comment by spytheman** [comment]
As discussed previously on Discord, option 1 is preferred.

**Comment by spytheman** [comment]
The previous discussion was here: https://discord.com/channels/592103645835821068/592320321995014154/1294286522329333772 .
