### ISSUE TITLE
WSL1 cannot run veb

### ISSUE THREAD

**Issue by felipensp** [vlang/v#22493]
### Describe the bug

Without commenting out on socket_util.c.v
```v
		// net.socket_error(C.setsockopt(fd, C.IPPROTO_TCP, C.TCP_DEFER_ACCEPT, &config.timeout_secs,
		// 	sizeof(int)))!
		// queue_len := max_queue
		// net.socket_error(C.setsockopt(fd, C.IPPROTO_TCP, C.TCP_FASTOPEN, &queue_len, sizeof(int)))!
```
veb cannot run any example.

### Reproduction Steps

v run examples/veb/veb_example.v

### Expected Behavior

working

### Current Behavior

socket error 92

### V version

master

### Environment details (OS name and version, etc.)

V full version: V 0.4.8 d3b380b.5aa6eaf
OS: linux, Debian GNU/Linux 10 (buster) (VM) (WSL)
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz

getwd: /home/felipe/github/v
vexe: /home/felipe/github/v/v
vexe mtime: 2024-10-11 21:44:26

vroot: OK, value: /home/felipe/github/v
VMODULES: OK, value: /home/felipe/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.20.1
Git vroot status: weekly.2024.41-14-g5aa6eaf3-dirty (1 commit(s) behind V master)
.git/config present: true

CC version: cc (Debian 8.3.0-6) 8.3.0
thirdparty/tcc status: thirdparty-linux-amd64 0134e9b9
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
There is a workaround in ab862c4285c82b04c20b055c4706059e752ad749 . Please check if it works for you on WSL1, with compiling your program with `-d support_wsl1` .

**Comment by felipensp** [comment]
> There is a workaround in [ab862c4](https://github.com/vlang/v/commit/ab862c4285c82b04c20b055c4706059e752ad749) . Please check if it works for you on WSL1, with compiling your program with `-d support_wsl1` .

Yes, it does works. Thanks :)
