### ISSUE TITLE
Type narrowing doesn't work in compound conditionals

### ISSUE THREAD

**Issue by moneppo** [vlang/v#22496]
### Describe the bug

I was expecting type narrowing to occur within compound conditionals, e.g. `if` statements with conditional checks combined using `&&`. These do not work, requiring nested `if` statements to check the types of multiple variables.

### Reproduction Steps

```
type Foo = int | []int
a := Foo([3]) 
if a is []int && a[0] == 3 {
  println("works")
}

error: type `Foo` does not support indexing
   10 | a := Foo([3])
   11 | if a is []int && a[0] == 3 {
      |                   ~~~
   12 |  println("works")
   13 | }
```

### Expected Behavior

Code compiles, and runs as expected.

### Current Behavior

Fails compilation as it doesn't recognize that `a` can only be an of type `[]int` in the second clause of the conditional.

### V version

V 0.4.8 0cf3a44

### Environment details (OS name and version, etc.)

OS: windows, Microsoft Windows 11 Home v22631 64-bit
Processor: 12 cpus, 64bit, little endian
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by jorgeluismireles** [comment]
I think is better the current way:
```v
type Foo = int | []int
a := Foo([3,4]) 
if a is []int {
	if a.len > 1 {
		println('a[1] = ${a[1]}') // a[1] = 4
	}
}
```
Because you have a chance in a clean second block to check array `a` for size before attempting to get an element from it. The line `if a is []int && a[0] == 3`  would fail if `a.len = 0` with *index out of range*. You should do something more complicated like: `if a is []int && a.len > 0 && a[0] == 3`.

**Comment by moneppo** [comment]
I used array access as an example for brevity, but this behavior is
applicable in many other situations, e.g. you want to check the type and
information about the type in a single conditional. I’ve found myself
having many nested if statements and redundant else clauses.

**Comment by medvednikov** [comment]
@moneppo can you please provide the more complex example?
