### ISSUE TITLE
Require non-optional pointer fields to be initialized

### ISSUE THREAD

**Issue by ntrel** [vlang/v#225]
```rust
struct S
{
	data int
	ptr *int
}
fn main() {
	s1 := S{}
	s2 := S{data: 5}
}
```
s1.ptr and s2.ptr above are both null, but `type(S.ptr)` is `*int` not `?*int`.

**Comment by medvednikov** [comment]
Yes, I had the same thought.

**Comment by medvednikov** [comment]
Fixed:

`pointer field `S.ptr` must be initialized`
