### ISSUE TITLE
Error compiling static type method

### ISSUE THREAD

**Issue by gercinojr** [vlang/v#22505]
### Describe the bug

The compiler does not recognize a static type method inside a match structure.

### Reproduction Steps

```v
struct User {}

fn User.is_ok() bool {
	return true
}

match true {
	User.is_ok() {
		println('it is ok')
	}
	else {
		println('it is not ok')
	}
}
```

### Expected Behavior

the code should compile and output "it is ok"

### Current Behavior

[https://play.vlang.io/p/80eca0e13a](https://play.vlang.io/p/80eca0e13a)
```
Running code...
Can't run code. The server returned an error:
code.v:8:6: error: unexpected token `.`, expecting `{`
    6 | 
    7 | match true {
    8 |     User.is_ok() {
      |         ^
    9 |         println('it is ok')
   10 |     }
Exited with error status 1
Please try again.
```

### Possible Solution

I don't know

### Additional Information/Context

The error happened both on the V Playground website and on my local machine.

### V version

local version: V 0.4.5 f0abc45

### Environment details (OS name and version, etc.)

Linux Mint 20.3
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by gercinojr** [comment]
Sorry, the correct v-lang local version is V 0.4.8 0cf3a44

**Comment by jorgeluismireles** [comment]
The workaround to make it work is using parentesis, change this line:
```
8|     User.is_ok() {
```
into
```
8|     (User.is_ok()) {
```

**Comment by medvednikov** [comment]
Great find! Thanks for reporting
