### ISSUE TITLE
Compiler Bug when using the vmon lib

### ISSUE THREAD

**Issue by darikoko** [vlang/v#22514]
### Describe the bug

When I use the vmon lib I get a compiler Bug.
The error is the following :  
================== C compilation error (from cc): ==============
cc:                                                    ^
cc: /tmp/v_501/main.01JA2Y1FC9E5N5HHNN978N7G7X.tmp.c:27074:33: error: incompatible function pointer types passing 'void (vmon__c__WatchID, vmon__Action, charptr, charptr, charptr, vmon__WatchCallBackWrap *)' (aka 'void (dmon_watch_id, vmon__Action, char *, char *, char *, struct vmon__WatchCallBackWrap *)') to parameter of type 'void (*)(dmon_watch_id, dmon_action, const char *, const char *, const char *, void *)' (aka 'void (*)(dmon_watch_id, enum dmon_action_t, const char *, const char *, const char *, void *)') [-Wincompatible-function-pointer-types]
cc:         u32 wid = dmon_watch(path.str, vmon__c_watch_callback_wrap, flags, watch_cb_wrap).id;
cc:                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
cc: /Users/loic/.vmodules/vmon/c/dmon/dmon.h:1606:47: note: passing argument to parameter 'watch_cb' here
cc:                                        void (*watch_cb)(dmon_watch_id watch_id, dmon_action action,
cc:                                               ^
cc: /tmp/v_501/main.01JA2Y1FC9E5N5HHNN978N7G7X.tmp.c:27166:4: warning: expression result unused [-Wunused-value]
cc:   (*(string*)_t3.data);
cc:    ^~~~~~~~~~~~~~~~~~
cc: 15 warnings and 1 error generated.
... (the original output was 59 lines long, and was truncated to 11 lines)
================================================================

### Reproduction Steps

I use a Mac Book pro M3 max.
I installed vmon via 'v install https://github.com/larpon/vmon'
And I run the code in the example folder from vmon

### Expected Behavior

It should compile without error

### Current Behavior

I get a compiler error :  
The error is the following :  
================== C compilation error (from cc): ==============
cc:                                                    ^
cc: /tmp/v_501/main.01JA2Y1FC9E5N5HHNN978N7G7X.tmp.c:27074:33: error: incompatible function pointer types passing 'void (vmon__c__WatchID, vmon__Action, charptr, charptr, charptr, vmon__WatchCallBackWrap *)' (aka 'void (dmon_watch_id, vmon__Action, char *, char *, char *, struct vmon__WatchCallBackWrap *)') to parameter of type 'void (*)(dmon_watch_id, dmon_action, const char *, const char *, const char *, void *)' (aka 'void (*)(dmon_watch_id, enum dmon_action_t, const char *, const char *, const char *, void *)') [-Wincompatible-function-pointer-types]
cc:         u32 wid = dmon_watch(path.str, vmon__c_watch_callback_wrap, flags, watch_cb_wrap).id;
cc:                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
cc: /Users/loic/.vmodules/vmon/c/dmon/dmon.h:1606:47: note: passing argument to parameter 'watch_cb' here
cc:                                        void (*watch_cb)(dmon_watch_id watch_id, dmon_action action,
cc:                                               ^
cc: /tmp/v_501/main.01JA2Y1FC9E5N5HHNN978N7G7X.tmp.c:27166:4: warning: expression result unused [-Wunused-value]
cc:   (*(string*)_t3.data);
cc:    ^~~~~~~~~~~~~~~~~~
cc: 15 warnings and 1 error generated.
... (the original output was 59 lines long, and was truncated to 11 lines)
================================================================

### V version

V 0.4.8 51b471

### Environment details (OS name and version, etc.)

V full version: V 0.4.8 51b471b
OS: macos, macOS, 15.0, 24A335
Processor: 14 cpus, 64bit, little endian, Apple M3 Max

getwd: /Users/loic/Desktop
vexe: /Users/loic/v/v
vexe mtime: 2024-10-10 10:07:45

vroot: OK, value: /Users/loic/v
VMODULES: OK, value: /Users/loic/.vmodules
VTMP: OK, value: /tmp/v_501

Git version: git version 2.39.3 (Apple Git-146)
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false

CC version: Apple clang version 15.0.0 (clang-1500.3.9.4)
thirdparty/tcc: N/A
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
Solved in https://github.com/larpon/vmon/pull/5 .
