### ISSUE TITLE
Function definition after usage does not work in V script

### ISSUE THREAD

**Issue by avitkauskas** [vlang/v#2252]
**V version:** V 0.1.21 8fea517
**OS:** Mac OS

**What did you do?**
```v
x := function()

fn function() int {
    return 1
}

println(x)
```

**What did you expect to see?**
`1`
 
**What did you see instead?**
```
$ v run test2.v
test2.v:1:13: undefined: `function`
    1| x := function()
```

**Comment by changrui** [comment]
yes, this is a bug.

**Comment by kstarzyk** [comment]
related to #2328 

This works as expected
```v
fn main() {
	x := function()
	println(x)
}

fn function() int {
    return 1
}
```

Handling top-level statements in file without `main` function as if they were inside `main` function should resolve that problem (if that is expected design)

**Comment by serkonda7** [comment]
With recent V this gives an proper error
```
testy.v:30:4: error: function declarations in script mode should be before all script statements
   28 | x := function()
   29 | 
   30 | fn function() int {
      |    ~~~~~~~~
   31 |     return 1
   32 | }
```
