### ISSUE TITLE
C compilation error when (incorrectly) attempting to use a map with a regex.RE as a value

### ISSUE THREAD

**Issue by raw-bin** [vlang/v#22521]
### Describe the bug

Here's a working snippet where the map initialization is correct:

```
~/Work/spaces/personal/languages/vlang/experiments | 1
❱ cat check_map_bug/src/main.v
module main

import regex

fn main() {
        mut matchers := map[int]regex.RE{}

        matchers = {
                1 : regex.regex_opt(r'one') or { panic('!') }
                2 : regex.regex_opt(r'two') or { panic('!') }
        }

        start, end := matchers[1].match_string('one')
        println('${start}:${end}')
}
~/Work/spaces/personal/languages/vlang/experiments
❱ ~/Work/repos/vlang/v/v run check_map_bug/src/main.v
0:3
```

Here's a snippet where the map initialization is intentionally wrong (the map's values don't have an `or` block): 
```
~/Work/spaces/personal/languages/vlang/experiments
❱ cat check_map_bug_1/src/main.v
module main

import regex

fn main() {
        mut matchers := map[int]regex.RE{}

        matchers = {
                1 : regex.regex_opt(r'one')
                2 : regex.regex_opt(r'two')
        }

        start, end := matchers[1].match_string('one')
        println('${start}:${end}')
}
~/Work/spaces/personal/languages/vlang/experiments
❱ ~/Work/repos/vlang/v/v run check_map_bug_1/src/main.v
================== C compilation error (from tcc): ==============
cc: /tmp/v_1000/main.01JA64RZH4RT4XFMYFD453BEZ2.tmp.c:16188: error: cannot convert 'struct _result_regex__RE' to 'void *'
=================================================================
(You can pass `-cg`, or `-show-c-output` as well, to print all the C error messages).
builder error:
==================
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .
```

### Reproduction Steps

Please see the description above.

### Expected Behavior

The vlang compiler should have emitted errors for the incorrect map initialization.

### Current Behavior

The C compiler generates an error.

### V version

0.4.8 df4c6ac

### Environment details (OS name and version, etc.)

OS: Garuda Linux Bird of Prey x86_64
Host: Amd Am5 Liquid
Kernel: 6.11.3-zen1-1-zen
Uptime: 10 hours, 16 mins
Packages: 2005 (pacman)
Shell: fish 3.7.1
Resolution: 3840x1080
DE: Plasma 6.2.0
WM: kwin
Theme: Sweet-Dark [GTK2/3]
Icons: breeze-dark [GTK2/3]
Terminal: tmux
CPU: AMD Ryzen 9 7950X3D (32) @ 5.759GHz
GPU: NVIDIA GeForce RTX 4090
GPU: AMD ATI 11:00.0 Raphael
Memory: 10948MiB / 63431MiB
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
Confirmed.
```v
module main

import regex

fn main() {
        mut matchers := map[int]regex.RE{}

        matchers = {
                1 : regex.regex_opt(r'one')
                2 : regex.regex_opt(r'two')
        }

        start, end := matchers[1].match_string('one')
        println('${start}:${end}')
}
```
produces a cgen error with latest V.

**Comment by spytheman** [comment]
I think it should have been a checker error instead, since `f()` has to be `f()!` , but it was not checked completely.
