### ISSUE TITLE
perf: reduce memory allocation in some `[n..m].method()` use cases

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#22542]
### \[(.+?)\.\.(.+?)\]\.trim_space\(\)
```
-> \[(.+?)\.\.(.+?)\]\.(.+?)\(\)
-> \[(.+?)\.\.\]\.(.+?)\(\)
-> \[\.\.(.+?)\]\.(.+?)\(\)
```
In all string method case use `substr_unsafe`

### \[(.+?)\.\.(.+?)\]\.(.+?)\(\)

vlib/crypto/bcrypt/bcrypt.v
```v
// fn (mut h Hashed) decode_cost(sbytes []u8) !int {
	cost := sbytes[0..2].bytestr().int()
```

vlib/veb/veb.v and vlib/x/vweb/vweb.v
```v
// fn handle_read[A, X](mut pv picoev.Picoev, mut params RequestParams, fd int) {
// line 422
		} else if n < bytes_to_read || params.idx[fd] + n < content_length.int() {
			// request is incomplete wait until the socket becomes ready to read again
			params.idx[fd] += n
			// TODO: change this to a memcpy function?
			req.data += buf[0..n].bytestr()
			params.incomplete_requests[fd] = req
			return
		} else {
			// request is complete: n = bytes_to_read
			params.idx[fd] += n
			req.data += buf[0..n].bytestr()
		}
```
vlib/io/buffered_reader.v
```v
// pub fn (mut r BufferedReader) read(mut buf []u8) !int {
// pub fn (mut r BufferedReader) read_line(config BufferedReadLineConfig) !string {
```

### Use Case

improve performance

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.4.8 3326392

### Environment details (OS name and version, etc.)

all
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
substr_unsafe is not safe to use in the general case.
It will produce a V string, that is a "slice" of the original, and it will not have the ending 0, that is needed for calling C APIs later.

**Comment by spytheman** [comment]
The result will also entangle the life times of the 2 strings, so it will conflict with -autofree too.
