### ISSUE TITLE
C interop variable/keyword conflict

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#22570]
### Describe the bug

While binding raylib into V, I came across a conflict between a variable name and a reserved keyword in V.
Is there a way around this? 

### Reproduction Steps

```c
typedef struct AutomationEvent {
    unsigned int frame;             
    unsigned int type;           
    int params[4];               
} AutomationEvent;
```

```v
@[typedef]
struct C.AutomationEvent {
	frame u32
	type u32 // error: unexpected keyword `type`, expecting name
	params [4]int
}
```

### Expected Behavior

A way around the conflict, ideally.

### Current Behavior

Compilation error.

### Possible Solution

Perhaps like the JSON attribute `@[name: 'c_name']`?

### V version

0.4.8

### Environment details (OS name and version, etc.)

% v doctor
V full version: V 0.4.8 2ab1523
OS: macos, macOS, 14.7, 23H124
Processor: 16 cpus, 64bit, little endian, Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz

getwd: /Users/duarteroso
vexe: /usr/local/Cellar/vlang/0.4.8/libexec/v
vexe mtime: 2024-09-28 15:50:00

vroot: OK, value: /usr/local/Cellar/vlang/0.4.8/libexec
VMODULES: OK, value: /Users/duarteroso/.vmodules
VTMP: OK, value: /tmp/v_501

Git version: git version 2.33.0
Git vroot status: Error: fatal: not a git repository (or any of the parent directories): .git
.git/config present: false

CC version: Apple clang version 15.0.0 (clang-1500.3.9.4)
thirdparty/tcc: N/A
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
Recently this keyword issue was fixed. On master it works using `type` as name, on old versions you must use `@type`.

**Comment by duarteroso** [comment]
My bad! 
Brew isn't doesn't seem to be on latest...

Thnaks
