### ISSUE TITLE
Question / Request: A small clarification if possible

### ISSUE THREAD

**Issue by stefanos82** [vlang/v#226]
From readme file we have 

> V can translate your entire C/C++ project and offer you the safety, simplicity, and up to 200x compilation speed up.

and at the very end we read

> V can compile to (human readable) C, so you get the great platform support and optimization of gcc and Clang.

So my question is: if I have an existing, well-written, well-tested C code, why would I want to translate it to V that in turn could emit a newly generated human readable C code?

I'm confused now... :confused:

**Comment by ntrel** [comment]
1. If that code is to be further developed, V is a safer and higher level language than C.
2. Outputting assembly is much faster, so testing and iterative development is faster. Outputting to C allows intensive advanced optimisation when desired.

**Comment by stefanos82** [comment]
The real question is: why emit C code and not directly use the one I already have?

**Comment by kitech** [comment]
I think this can avoid develop on C code base later.

**Comment by medvednikov** [comment]
Good question.

If you have well-written, well-tested C code, then of course you can always simply call this C code from V.

Translating it to V gives you several advantages.

If you plan to develop that code base, you now have everything in one language, which is much safer and easier to develop in that C.

Cross-compilation becomes much easier. You don't have to worry about it at all. No more build flags and include files either.

**Comment by stefanos82** [comment]
Very nice @medvednikov .

Can we clarify this as an extended explanation on README file please?

It would make things a lot clearer to people.

**Comment by medvednikov** [comment]
I've added this info to the docs:

https://vlang.io/docs#cpp
