### ISSUE TITLE
date related picoev improvements:

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#22623]
### Describe the feature

I don't think this will not really improve perfomance. but it will improve the readability and maintenance

### Use Case

picoev

### Proposed Solution

// vlib/picoev/picoev.v
```v
@[heap]
pub struct Picoev {
// ...
	date ?[]u8
// ...
}
```

```v
// update_date updates the date field of the Picoev instance every second for HTTP headers
fn update_date_string(mut pv Picoev) {
	for {
		// get GMT (UTC) time for the HTTP Date header
		time.push_http_header_bytes_to(mut pv.date)
	}
}
```

```v
@[direct_array_access]
fn raw_callback(fd int, events int, context voidptr) {
// ...
	} else if events & picoev_read != 0 {
// ...
		mut res := picohttpparser.Response{
// ...
			date:      &pv.date[0]
		}
// ...
}
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

latest

### Environment details (OS name and version, etc.)

all
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by enghitalo** [comment]
Verify if 

```v
pub struct Response {
pub:
	fd        int
	date      &u8 = unsafe { nil }
	buf_start &u8 = unsafe { nil }
pub mut:
	buf &u8 = unsafe { nil }
}

@[inline]
pub fn (mut r Response) write_string(s string) {
	unsafe {
		vmemcpy(r.buf, s.str, s.len)
		r.buf += s.len
	}
}
```
is not slower than
```v
pub struct Response {
pub:
	fd        int
	date      &u8 = unsafe { nil }
pub mut:
	buf &u8[] = unsafe { nil }
}

@[inline]
@[manualfree]
pub fn (mut r Response) write_string_and_free(s string) {
	unsafe {
		buf.push_many(s.str, s.len)
		s.free()
	}
}
```

**Comment by jorgeluismireles** [comment]
Forgive me for asking here, but I have a question about current `date string` in picoev. Is *updated* inside a spawned function `update_date_string(...)` with an infinite `for` with a time.sleep of 1 second. And is *read* in `update_date_string(...)` to be used to form the `Response`. It shouldn't be "shared" or similar since is written and read in different threads? Thanks in advance.

**Comment by enghitalo** [comment]
> Forgive me for asking here, but I have a question about current `date string` in picoev. Is *updated* inside a spawned function `update_date_string(...)` with an infinite `for` with a time.sleep of 1 second. And is *read* in `update_date_string(...)` to be used to form the `Response`. It shouldn't be "shared" or similar since is written and read in different threads? Thanks in advance.

Possibly, it should.
