### ISSUE TITLE
`!` is not punct char

### ISSUE THREAD

**Issue by AKonia** [vlang/v#22646]
### Describe the bug

Possible bug in `encoding.utf8` `is*punct` functions, `!` recognized as non-punct char. `ispunct` from `libc` returns true for all chars.

### Reproduction Steps

Run Code:

```v
module main
import encoding.utf8 as u8

fn check_char(s &string) int
{
    println("${*s}")
    println("is punct ?")
    for i, ch in s.runes()
    {
         is_p := u8.is_punct(ch.str(), 0)
	 okch := ch.str()
	 println("${if is_p {' is punct'} else {'not punct'}}, ${u8.get_uchar(s, i)}, ${i} ${okch}")
    }
    return 0
}

fn main()
{
    a := "!.,:;"
    println("${typeof(a).name}\n${check_char(a)}\n")
}
```

### Expected Behavior

```
!.,:;
is punct ?
 is punct, 33, 0 !
 is punct, 46, 1 .
 is punct, 44, 2 ,
 is punct, 58, 3 :
 is punct, 59, 4 ;
string
0
```

### Current Behavior

**Output:**

```
!.,:;
is punct ?
not punct, 33, 0 !
 is punct, 46, 1 .
 is punct, 44, 2 ,
 is punct, 58, 3 :
 is punct, 59, 4 ;
string
0
```

### Possible Solution

Not discovered yet.

### V version

4.4, 4.5, 4.8

### Environment details (OS name and version, etc.)

Manjaro linux, kernel 6.4

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFhOTM4ZmYwMmQ4YTAzZmIzM2EwOGMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.4fcuz0wsWy03FVl_DmiswhIxFxSm-WsRlg4OfiN-ZDY">Huly&reg;: <b>V_0.6-21095</b></a></sub>

**Comment by felipensp** [comment]
Good find. :-)
