### ISSUE TITLE
adding element to array of references in method adds by value

### ISSUE THREAD

**Issue by daansystems** [vlang/v#22648]
**V doctor:**
```
V full version: V 0.4.8 5c65e58.f715d49
OS: windows, Microsoft Windows 11 Pro v22631 64-bit
Processor: 24 cpus, 64bit, little endian, 

getwd: D:\vbug2
vexe: C:\v\v.exe
vexe mtime: 2024-10-25 06:20:20

vroot: OK, value: C:\v
VMODULES: OK, value: C:\Users\info\.vmodules
VTMP: OK, value: C:\Users\info\AppData\Local\Temp\v_0

Git version: git version 2.42.0.windows.2
Git vroot status: 0.4.8-201-gf715d491-dirty
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,

operable program or batch file.


thirdparty/tcc status: thirdparty-windows-amd64 b425ac82

```

**What did you do?**
`./v -g -o vdbg cmd/v && ./vdbg main.v`
```v
module main

struct GameObject {
mut:
	name      string
}

fn (gameobject GameObject) add_to_array(mut gameobjects []&GameObject)  {
	gameobjects << &gameobject	
}

fn main() {
	mut gameobjects := []&GameObject{}
	mut foo := GameObject{
		name: 'foo'
	}
	gameobjects << &foo // adds by reference
	foo.add_to_array(mut gameobjects) // adds by value?
	foo.name = 'bar'
	eprintln("gameobjects: ${gameobjects}")
}

```

**What did you expect to see?**

gameobject added by reference in both cases:
```
gameobjects: [&GameObject{
    name: 'bar'
}, &GameObject{
    name: 'bar'
}]
```
**What did you see instead?**
```
gameobjects: [&GameObject{
    name: 'bar'
}, &GameObject{
    name: 'foo'
}]
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by StunxFS** [comment]
@daansystems

```v
module main

struct GameObject {
mut:
	name      string
}

fn (gameobject &GameObject) add_to_array(mut gameobjects []&GameObject)  {
	gameobjects << gameobject	
}

fn main() {
	mut gameobjects := []&GameObject{}
	mut foo := &GameObject{
		name: 'foo'
	}
	gameobjects << foo // fine
	foo.add_to_array(mut gameobjects) // fine
	foo.name = 'bar'
	eprintln("gameobjects: ${gameobjects}")
}
```

I have modified the code a little and it works as expected. 
What I've done is made `GameObject.add_to_array` receive a pointer as a receiver, and in addition to that, I made `foo` be allocated in the heap, therefore, there is no need to do `gameobjects << &foo`, and thus the reference to `foo` is maintained.

The problem with your code is that in `GameObject.add_to_array`, `gameobjects << &gameobject` allocates a copy of `gameobject` to the heap, and therefore no longer references the same value.

**Comment by daansystems** [comment]
@StunxFS  Thank you for your reply. Looking into this a small change makes it also work as I would expect: adding mut to the receiver. I'm not sure this is intuitive. I would expect to have the receiver always as reference?:

```
module main

struct GameObject {
mut:
	name      string
}

fn (mut gameobject GameObject) add_to_array(mut gameobjects []&GameObject)  {
	gameobjects << gameobject	
}

fn main() {
	mut gameobjects := []&GameObject{}
	mut foo := GameObject{
		name: 'foo'
	}
	gameobjects << &foo // fine
	foo.add_to_array(mut gameobjects) // fine
	foo.name = 'bar'
	eprintln("gameobjects: ${gameobjects}")
}
```

**Comment by StunxFS** [comment]
@daansystems Happy to help. Declaring the receiver as `mut` automatically makes it a pointer, so yes, it works the same as making the receiver pass by reference.

**Comment by felipensp** [comment]
Not a bug? @StunxFS  @daansystems

**Comment by StunxFS** [comment]
> Not a bug? @StunxFS  @daansystems 

@felipensp To me, this is a simple logic error on the user side, not the compiler side.

**Comment by StunxFS** [comment]
> Not a bug? @StunxFS  @daansystems 

@felipensp To me, this is a simple logic error on the user side, not the compiler side.

**Comment by djbelishaO** [comment]
✨✨ Here's [an AI-assisted sketch of how you might approach this issue](https://copilot-workspace.githubnext.com/vlang/v/issues/22648?shareId=e2b83cf6-7c16-49a4-a7f5-ffb914256131) saved by @djbelishaO using Copilot Workspace v0.25

**Comment by felipensp** [comment]
Not a bug.
