### ISSUE TITLE
generic checker error

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#22642]
### Describe the bug

generic checker error

### Reproduction Steps

```v
module main

struct Decoder {
	json string
}

pub fn decode[T](val string) !T {
	mut decoder := Decoder{
		json: val
	}

	mut result := T{}
	decoder.decode_value(mut &result)!
	return result
}

fn (mut decoder Decoder) decode_value[T](mut val T) ! {
	$if T.unaliased_typ is $array {
		mut array_element := create_array_element(val)

		decoder.decode_value(mut array_element)!

		val << array_element

		assert val.len == 1
		assert val[0] == array_element
	} $else $if T.unaliased_typ is $map {
		mut map_value := create_map_value(val)

		decoder.decode_value(mut map_value)!

		val['key'] = map_value

		assert val.len == 1
		assert val['key'] == map_value
	}
}

fn create_array_element[T](array []T) T {
	return T{}
}

fn create_map_value[K, V](map_ map[K]V) V {
	return V{}
}

fn test_main() {
	assert decode[[]int]('[1, 2, 3]')! == [0]
	assert decode[[]string]('["1", "2", "3"]')! == ['']
	assert decode[map[string]int]('{"a": 1}')! == {
		'key': 0
	}
	assert decode[map[string]string]('{"val": "2"}')! == {
		'key': ''
	}
}
```

### Expected Behavior

assert pass

### Current Behavior

```sh
>> compilation failed:
vlib/v/tests/generics/generic_fn_param_test.v:23:10: error: cannot append `int` to `T`
   21 |         decoder.decode_value(mut array_element)!
   22 | 
   23 |         val << array_element
      |                ~~~~~~~~~~~~~
   24 | 
   25 |         assert val.len == 1
vlib/v/tests/generics/generic_fn_param_test.v:26:13: error: infix expr: cannot use `int` (right expression) as `string`
   24 | 
   25 |         assert val.len == 1
   26 |         assert val[0] == array_element
      |                   ~~~~~~~~~~~~~~~~~~~~
   27 |     } $else $if T is $map {
   28 |         mut map_value := create_map_value(val)
vlib/v/tests/generics/generic_fn_param_test.v:32:16: error: cannot assign to `val['key']`: expected `string`, not `int`
   30 |         decoder.decode_value(mut map_value)!
   31 | 
   32 |         val['key'] = map_value
      |                      ~~~~~~~~~
   33 | 
   34 |         assert val.len == 1
vlib/v/tests/generics/generic_fn_param_test.v:35:13: error: infix expr: cannot use `int` (right expression) as `string`
   33 | 
   34 |         assert val.len == 1
   35 |         assert val['key'] == map_value
      |                   ~~~~~~~~~~~~~~~~~~~~
   36 |     }
   37 | }
```

### V version

latest

### Environment details (OS name and version, etc.)

ubuntu

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzFhNGFjMWYwMmQ4YTAzZmIzMzYxNTUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.C3mqNSc-rFyAo-QFw41ZrR05C7XdWNV7Pv7elgrRlPs">Huly&reg;: <b>V_0.6-21091</b></a></sub>

**Comment by JalonSolov** [comment]
User error, rather than checker error.  You didn't do anything to "unwrap" the value you tried to use.  Your code compiles clean with 2 simple changes:

change
```v
    $if T is $array {
```
to
```v
    $if val is $array {
```
and change
```v
    } $else $if T is $map {
```
to
```v
    } $else $if val is $map {
```

**Comment by enghitalo** [comment]
> User error, rather than checker error. You didn't do anything to "unwrap" the value you tried to use. Your code compiles clean with 2 simple changes:
> 
> change
> 
> ```v
>     $if T is $array {
> ```
> 
> to
> 
> ```v
>     $if val is $array {
> ```
> 
> and change
> 
> ```v
>     } $else $if T is $map {
> ```
> 
> to
> 
> ```v
>     } $else $if val is $map {
> ```

Thank you! But then I wouldn't be able to use `unaliased_typ` in `T.unaliased_typ is $map` or `T.unaliased_typ is $array`
