### ISSUE TITLE
Array initialization doesn't compile

### ISSUE THREAD

**Issue by SirJosh3917** [vlang/v#227]
```
mut ids := [0 ; 50]
```
doesn't compile. I apologize if this is a repeat of an existing issue.

**Comment by medvednikov** [comment]
It works when wrapped in `main`:

```
fn main() {
     mut ids := [0 ; 50]
     println(ids)
} 
```

This has been fixed in V 0.0.11, I'll update the playground soon.

**Comment by TankhouseAle** [comment]
>Implying you are physically capable of compiling V code, because you have access to an extant V compiler

bruh

**Comment by medvednikov** [comment]
Fixed.
