### ISSUE TITLE
checker error: type `func` does not support indexing

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#22735]
### Describe the bug

checking generic type as map key

### Reproduction Steps

```v
fn func[T](arg string) int {
    println('hello from func')
    return 2
}

fn main() {
    println('dsds')

    mapa := {"la": func}

    assert mapa['la'][string]('ran') == 2

    dump(func[string]('la'))

}
```

### Expected Behavior

assertion pass

### Current Behavior

```sh
╰─ v a.v -o b.c ─╯
a.v:11:15: error: type `func` does not support indexing
    9 |     mapa := {"la": func}
   10 | 
   11 |     mapa['la'][string]('ran')
      |               ~~~~~~~~
   12 | 
   13 |     dump(func[string]('la'))
a.v:11:16: error: undefined ident: `string`
    9 |     mapa := {"la": func}
   10 | 
   11 |     mapa['la'][string]('ran')
      |                ~~~~~~
   12 | 
   13 |     dump(func[string]('la'))
a.v:11:24: error: unknown function: 
    9 |     mapa := {"la": func}
   10 | 
   11 |     mapa['la'][string]('ran')
      |                        ~~~~~
   12 | 
   13 |     dump(func[string]('la'))
If the code of your project is in multiple files, try with `v .` instead of `v a.v`
```

### V version

V 0.4.8 fc6e481

### Environment details (OS name and version, etc.)

Linux

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI1OGI1ZjI3Y2M3NjgxYzYyNWQ3NWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.dkNKlOjmC96JOrCpNXApI_-q6cW3mV6AHlZcO4yyDjI">Huly&reg;: <b>V_0.6-21182</b></a></sub>

**Comment by Delta456** [comment]
This should not work because `func` generic type cannot be runtime so `{"la": func[string]}` should be used instead.

**Comment by felipensp** [comment]
Yes, it also looks confusing to me.

**Comment by Delta456** [comment]
I will work on this

**Comment by felipensp** [comment]
The proper way to do it is:
```v
fn func[T](arg string, mut val T) int {
	return 123
}

fn main() {
	map1 := {"la": func[int]}
	mut a := 123
	assert map1['la']('', mut a) == 123
}
```
In this way the map value type is resolved on map init. 👍🏻

**Comment by felipensp** [comment]
So I think we can close it.

**Comment by Delta456** [comment]
AS #22743 has been merged. The code gives a proper error. The issue can be closed now.
