### ISSUE TITLE
string to_upper() latin (utf8?) characters error

### ISSUE THREAD

**Issue by gercinojr** [vlang/v#22742]
### Describe the bug

Not all characters are capitalized

### Reproduction Steps

'água'.to_upper()  // <= 'áGUA'

### Expected Behavior

'água'.to_upper()  // <= 'ÁGUA'

### Current Behavior

'água'.to_upper()  // <= 'áGUA'

### Possible Solution

I don't know

### V version

V 0.4.8 5d76ee4

### Environment details (OS name and version, etc.)

Linux linux 6.8.0-48-generic

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI2NGMyMzI3Y2M3NjgxYzYyNWZiN2MiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.OcF9fxJ6GQBqenB5XDL50u79WtqW6d1XuCrFRrPtdlI">Huly&reg;: <b>V_0.6-21189</b></a></sub>

**Comment by jorgeluismireles** [comment]
`string.to_lower`,  `is_lower`, `to_upper`, `is_upper` only works for ASCII. We can adapt the code to include the aprox 31 Latin letters with "hats". For example, to convert letter **á** (code 0xc3a1) into letter **Á** (code 0xc381) we update [string.to_upper](https://github.com/vlang/v/blob/master/vlib/builtin/string.v#L1565) as:
```v
@[direct_array_access]
pub fn to_upper_latin(s string) string {
	unsafe {
		mut b := malloc_noscan(s.len + 1)
		for i := 0; i < s.len; i++ { // +
			if s.str[i] >= `a` && s.str[i] <= `z` {
				b[i] = s.str[i] - 32
			} else {
				b[i] = s.str[i]
				if s.str[i] == 0xc3 {
					if s.str[i+1] >= 0xa0 && s.str[i+1] <= 0xbf {
						b[i+1] = s.str[i+1] - 32
					} else {
						b[i+1] = s.str[i+1]
					}
					i++
				}
			}
		}
		b[s.len] = 0
		return tos(b, s.len)
	}
}

const es_lower = 'acá,él,mío,león,música,cigüeña'
const es_upper = 'ACÁ,ÉL,MÍO,LEÓN,MÚSICA,CIGÜEÑA'
fn main() {
	assert to_upper_latin(es_lower) == es_upper
	assert to_upper_latin('÷') == '×' // artifact...
}
```
See https://play.vlang.io/p/a900029c57

A little annoyance is the Latin hat letters group includes ÷ and × also. [Here](https://www.utf8-chartable.de/) is the UTF-8 encoding table I followed.

**Comment by medvednikov** [comment]
We should simply do what Go does: https://cs.opensource.google/go/go/+/refs/tags/go1.23.2:src/unicode/letter.go;l=211

**Comment by jorgeluismireles** [comment]
> We should simply do what Go does: https://cs.opensource.google/go/go/+/refs/tags/go1.23.2:src/unicode/letter.go;l=211

yes, because then will come greek α, Α... and the others.
