### ISSUE TITLE
V Example of connecting to TiDB Serverless

### ISSUE THREAD

**Issue by Avey777** [vlang/v#22744]
### Describe the feature

https://tidbcloud.com/

Because TiDB Serverless needs to be connected via SSL, can you give me a connection example?
This is the same as MySQL's SSL, but I don't know how to use it

### Version used

0.4.8

https://github.com/vlang/v/discussions/22569

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI2YzI0NzI3Y2M3NjgxYzYyNjA5ZTEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.w5a42kXWuouFggzFLfdiGbNdndmbC1_1H7p4wiA3HQQ">Huly&reg;: <b>V_0.6-21191</b></a></sub>

**Comment by daniel-le97** [comment]
I was able to connect to TiDB Serverless with the following example

for me, on macos `mysql-client` version 8.0 needed to be installed

```
brew install mysql-client@8.0
brew link mysql-client@8.0 --force --overwrite
```

```v
// tidb.v
module main

import db.mysql

fn main() {
	mut conn := mysql.connect(
		host:     'localhost.com'
		port:     4000
		username: 'root'
		password: 'pass'
		dbname:   'test'
		flag:     .client_ssl
	)!

	conn.query('
	CREATE TABLE `blog` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    author VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);')!
	// Insert a new blog post
	title := 'My First Blog Post'
	content := 'This is the content of my first blog post.'
	author := 'John Doe'
	insert_query := 'INSERT INTO blog (title, content, author) VALUES (?, ?, ?)'
	conn.exec_param_many(insert_query, [title, content, author])!
	res := conn.query('SELECT * FROM blog')!
	for row in res.rows() {
		println(row.vals.join(', '))
	}
	conn.close()
}

```

from here, if you already have a cluster for [TiDB](https://www.pingcap.com/) and  are signed in, you will see the following

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/33920c13-87d6-4b0e-bcaf-11687b51f4c5">
click on "connect"

which will show your connection parameters

replace the values for `mysql.connect()` with your parameters

* NOTE - if you don't see a password parameter, you will see a button that says "generate password"

# Running

```v
v run tidb.v
```

should expect to see output similar to

```
daniel@Daniels-MacBook-Air tidb-v % v run tidb.v
1, My First Blog Post, This is the content of my first blog post., John Doe, 2024-11-13 00:49:31
```
