### ISSUE TITLE
cgen: `x() in [...]` calls `x()` for every element of array

### ISSUE THREAD

**Issue by zeozeozeo** [vlang/v#22758]
**V doctor:**

```
V full version: V 0.4.8 5c65e58.3108820
OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 10 cpus, 64bit, little endian, 

getwd: C:\Users\user\Downloads
vexe: C:\Users\user\Desktop\Code\v\v.exe
vexe mtime: 2024-11-04 16:24:59

vroot: OK, value: C:\Users\user\Desktop\Code\v
VMODULES: OK, value: C:\Users\user\.vmodules
VTMP: OK, value: C:\Users\user\AppData\Local\Temp\v_0

Git version: git version 2.42.0.windows.1
Git vroot status: weekly.2024.44-37-g3108820d
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,

operable program or batch file.


thirdparty/tcc status: thirdparty-windows-amd64 b425ac82
```

**What did you do?**
`./v -g -o vdbg cmd/v && ./vdbg test.v`

```v
fn test() bool {
	println("i should only be called once")
	return true
}

fn main() {
	println(test() in [false, true])
}
```

**What did you expect to see?**

```
i should only be called once
true
```

**What did you see instead?**

```
i should only be called once
i should only be called once
true
```

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzI4ZjZhYWU3Y2M1YTc4NTQyNzc1YWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.9spoKbUCnRUiwITWOTDhTK1z5RNgUzpx7Au_Zssip9c">Huly&reg;: <b>V_0.6-21205</b></a></sub>

**Comment by HectorPeeters** [comment]
Just took a look at this issue and I think I found the problem.

The problem seems to be in `vliv/v/gen/c/infix.v` in the `infix_expr_in_op` function. As an optimization it tries to replace `x in [a, b, ...]` with `x == a || x == b || ...`. However, this does not take into account that `x` might produce side effects.

Checking if the left node is an `ast.Ident` fixes this issue but this should probably be replaced with proper side effect analysis in the future.

**Comment by spytheman** [comment]
Fixed in https://github.com/vlang/v/pull/22763 .
