### ISSUE TITLE
can not make successfully under DragonFlyBSD

### ISSUE THREAD

**Issue by lhmwzy** [vlang/v#2275]
**V version:** 
`latest`
**OS:** 
`DragonFly gxdb 5.6-RELEASE DragonFly v5.6.0.1.g3d5034-RELEASE #0: Tue Jun 18 09:09:55 CST 2019`

**What did you do?**
gmake

**What did you expect to see?**
build successfully
 
**What did you see instead?**
```
rm -rf vc/
git clone --depth 1 --quiet https://github.com/vlang/vc
cc -std=gnu11 -w -o v vc/v.c -lm
/tmp//cchbElGt.o:v.c:function os__posix_wait4_to_exit_status: error: undefined reference to 'WIFEXITED'
/tmp//cchbElGt.o:v.c:function os__posix_wait4_to_exit_status: error: undefined reference to 'WEXITSTATUS'
/tmp//cchbElGt.o:v.c:function os__posix_wait4_to_exit_status: error: undefined reference to 'WIFSIGNALED'
/tmp//cchbElGt.o:v.c:function os__posix_wait4_to_exit_status: error: undefined reference to 'WTERMSIG'
collect2: error: ld returned 1 exit status
gmake: *** [Makefile:14: all] Error 1
```

**Comment by sunnylcw** [comment]
@lhmwzy Please refer to PR #2267 for FreeBSD.  Can you do a similar PR for DragonFlyBSD?

**Comment by lhmwzy** [comment]
submit a PR [#2276 2278](https://github.com/vlang/v/pull/2278)

**Comment by Delta456** [comment]
Can you look if #2279 is working for you?

**Comment by lhmwzy** [comment]
> 
> 
> Can you look if #2279 is working for you?

YES.
