### ISSUE TITLE
type not exports pub static type methods

### ISSUE THREAD

**Issue by gercinojr** [vlang/v#22773]
### Describe the bug

v is showing an error on new static type method

### Reproduction Steps

two files in the same directory:

- main.v
- mymodule.v

command to run:

```
v run .
```

### Expected Behavior

run without errors

```
// main.v
module main
import mymodule
type MyMod = mymodule.MyModule

fn main() {
    println('Hello from main!')    // -> Hello from main!
    mm := mymodule.MyModule.new()
    mm.hello()                     // -> Hello from MyModule

    mm2 := MyMod.new() 
    mm2.hello()        // -> Hello from MyModule    
}
```

### Current Behavior

```
// mymodule.v
module mymodule

pub struct MyModule{}
pub fn MyModule.new() &MyModule { return &MyModule{} }
pub fn (mm MyModule) hello() { println('Hello from MyModule') }
```

```
// main.v
module main
import mymodule
type MyMod = mymodule.MyModule

fn main() {
    println('Hello from main!')    // -> Hello from main!
    mm := mymodule.MyModule.new()
    mm.hello()                     // -> Hello from MyModule

    mm2 := MyMod.new() // error: unknown function: MyMod.new
    mm2.hello()        // error: assignment mismatch: 1 variable but `MyMod.new()` returns 0 values      
}
```

### Possible Solution

use factory function like `fn new_mymodule() &MyModule {}`

### V version

V 0.4.8 5d76ee4

### Environment details (OS name and version, etc.)

GNU/Linux

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJiNjgxM2U3Y2M1YTc4NTQyOGIxOTIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.M9loaobr1oOOXgKQoibSAf6gLHrpdxIXlqvzOrI0PrE">Huly&reg;: <b>V_0.6-21220</b></a></sub>

**Comment by StunxFS** [comment]
The problem is that the compiler cannot detect that you are trying to access a static method from an alias. This small piece of code fails in the same way:

```v
module main

struct MyStruct {}
fn MyStruct.new() {}

type MyAlias = MyStruct

fn main() {
    MyStruct.new()
	MyAlias.new()   
}
```
