### ISSUE TITLE
Pop!_OS: Compiler error

### ISSUE THREAD

**Issue by HaraldWik** [vlang/v#22821]
### Describe the bug

Idk, just failed to compile: heres the error code?
```
**### Error**
================== C compilation error (from tcc): ==============
cc: /tmp/v_1000/game-engine.01JCBM64AVV8AZW03V4014J5A0.tmp.c:2084: error: ';' expected (got "sdl__OSEvent")
=================================================================
(You can pass `-cg`, or `-show-c-output` as well, to print all the C error messages).
builder error: 
==================
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .
```
My code:
```v
module app

import sdl

pub fn init() {
	sdl.init(sdl.init_video)
	window := sdl.create_window('Hello SDL2'.str, 300, 300, 500, 300, 0)
	renderer := sdl.create_renderer(window, -1, u32(sdl.RendererFlags.accelerated) | u32(sdl.RendererFlags.presentvsync))

	mut should_close := false
	for {
		evt := sdl.Event{}
		for 0 < sdl.poll_event(&evt) {
			match evt.@type {
				.quit { should_close = true }
				else {}
			}
		}
		if should_close {
			break
		}

		sdl.set_render_draw_color(renderer, 255, 55, 55, 255)
		sdl.render_clear(renderer)
		sdl.render_present(renderer)
	}

	sdl.destroy_renderer(renderer)
	sdl.destroy_window(window)
	sdl.quit()
}
```
Probably not a actual error but it said to go here!

### Reproduction Steps

Copy code, try to run code

### Expected Behavior

Make a window using SDL

### Current Behavior

Compilation error

### Possible Solution

idk

### Additional Information/Context

...

### V version

V 0.4.8 3223da6

### Environment details (OS name and version, etc.)
```
OS: Pop!_OS 24.04 LTS x86_64
Host: ROG Zephyrus G14 GA401IU_GA401IU 1.0
Kernel: 6.9.3-76060903-generic
Uptime: 1 day, 5 hours, 37 mins
Packages: 1976 (dpkg), 41 (flatpak)
Shell: bash 5.2.21
Resolution: 1920x1080
DE: COSMIC
Theme: adw-gtk3-dark [GTK3]
Icons: Pop [GTK3]
Terminal: cosmic-term
CPU: AMD Ryzen 7 4800HS with Radeon Graphics (16) @ 2.900GHz
GPU: NVIDIA GeForce GTX 1660 Ti Mobile
GPU: AMD ATI Radeon RX Vega 6
Memory: 8043MiB / 15402MiB
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
What command are you using to compile the code?  The example can't be compiled by itself, as it doesn't nave a `fn main()`.

**Comment by HaraldWik** [comment]
I am using 'v run .' and this function is just running from the main function

```v
module main

import app

fn main() {
	println('Hello World!')

	app.init()
}

```

**Comment by JalonSolov** [comment]
Setting up this structure
```
.
├── app
│   └── app.v
├── main.v
└── v.mod
```
then attempting to run it with latest `V 0.4.8 fdc49dc` and the command `v run .`, this is the only error I see:
```
app/app.v:5:1: error: fn `init` must not be public
    3 | import sdl
    4 | 
    5 | pub fn init() {
      | ~~~~~~~~~~~~~
    6 |     sdl.init(sdl.init_video)
    7 |     window := sdl.create_window('Hello SDL2'.str, 300, 300, 500, 300, 0)
```
... the problem appears to be specific to your system.

The question now is, which version of SDL do you have installed, and did you remember to do a `git checkout` of the appropriate branch in `.vmodules/sdl` to match that version?

**Comment by JalonSolov** [comment]
Note that for me, changing `pub fn init()` to `pub fn app_init()`, then changing the line in `fn main()` from `app.init()` to `app.app_init()` made the code work.

![image](https://github.com/user-attachments/assets/ba61a565-9bd3-4c70-9015-e5a8297652c6)

This particular issue is because V creates a function named `init()` by default, which handles setting up things that need to be handled before your program can run at all.  It should probably tell you that you can't have a function named just `init()` in your code, instead of complaining about it being marked `pub`.

**Comment by HaraldWik** [comment]
Probably not a issue with my sdl2 headers, works just fine in GO 
![image](https://github.com/user-attachments/assets/32cfe95f-67dc-463f-b606-5888217af546)

**Comment by larpon** [comment]
@HaraldWik the error is a symptom that looks like the version of SDL2 installed on your OS does not match the version of `vlang/sdl` checked out. Try [installing via git](https://github.com/vlang/sdl?tab=readme-ov-file#install) and then run `v ~/.vmodules/sdl/setup.vsh`.
Remove the `v install sdl` version, then install from source and run the script that will checkout the right `vlang/sdl` branch for you:
```bash
rm -r ~/.vmodules/sdl
git clone https://github.com/vlang/sdl.git ~/.vmodules/sdl
v ~/.vmodules/sdl/setup.vsh
```

**Comment by HaraldWik** [comment]
Thx @larpon! worked great!

**Comment by larpon** [comment]
Glad to hear. It is unfortunately a well known and reoccurring issue we still have not found any good solutions for
