### ISSUE TITLE
constant arrays shouldn't be allowed to be put under `mut:` struct fields 

### ISSUE THREAD

**Issue by zeozeozeo** [vlang/v#22862]
**V doctor:**

```
V full version: V 0.4.8 5c65e58.df51e84
OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 10 cpus, 64bit, little endian, 

getwd: C:\Users\user\Downloads
vexe: C:\Users\user\Desktop\Code\v\v.exe
vexe mtime: 2024-11-14 18:10:30

vroot: OK, value: C:\Users\user\Desktop\Code\v
VMODULES: OK, value: C:\Users\user\.vmodules
VTMP: OK, value: C:\Users\user\AppData\Local\Temp\v_0

Git version: git version 2.42.0.windows.1
Git vroot status: weekly.2024.45-99-gdf51e840
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,

operable program or batch file.


emcc version: emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.71 (4171ae200b77a6c266b0e1ebb507d61d1ade3501)
thirdparty/tcc status: thirdparty-windows-amd64 b425ac82
```

**What did you do?**
`./v -g -o vdbg cmd/v && ./vdbg vvv.v`

```v
const arr = [1, 2, 3]

struct Muta {
mut:
	a []int
}

fn main() {
	mut muta := Muta{a: arr}
	muta.a[0] = 52
	println(arr) // [52, 2, 3]
}
```

**What did you expect to see?**

compilation error or `[1, 2, 3]` in stdout

**What did you see instead?**

```
[52, 2, 3]
```

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzM2M2UwMWU3Y2M1YTc4NTQyY2VlMWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.PQy6KmJZ0UErwe_UDpDA60TYjnjZkfMIeZGJqqfbgjs">Huly&reg;: <b>V_0.6-21305</b></a></sub>

**Comment by JalonSolov** [comment]
Agreed.  It should be copying the const into the field, rather than just pointing to it.  The current C code being generated is
```c
VV_LOCAL_SYMBOL void main__main(void) {
        main__Muta muta = ((main__Muta){.a = _const_main__arr,});
        array_set(&muta.a, 0, &(int[]) { 52 });
        println(Array_int_str(_const_main__arr));
}
```

**Comment by Delta456** [comment]
The checker needs to raise an error and recommend them to use `arr.copy()`
