### ISSUE TITLE
u8 doesn't overflow

### ISSUE THREAD

**Issue by sug0** [vlang/v#229]
```
fn main() {
	x := u8(255)
	println(x + u8(1))
}
```
This code should be printing 0, but on the playground it prints 256.

**Comment by ntrel** [comment]
I think the expression x + u8(1) gets promoted to int like in C.

**Comment by medvednikov** [comment]
This is a bug with `println`, it has been fixed. I'll close the issue once it's live.

This works as expected:
```
x := u8(255)
a := x + u8(1)
println(a)
```

**Comment by medvednikov** [comment]
By the way, right now this will not compile:

```
x := u8(255)
a := x + 1
```

In the future it will compile without casting the constant (`u8(1)`).

**Comment by medvednikov** [comment]
Fixed.
