### ISSUE TITLE
Formatter removes lines (1 per formatting) after scope block in function body 

### ISSUE THREAD

**Issue by ttytm** [vlang/v#22900]
### Describe the bug

When using a block to encapsulate some logic in a function, v fmt removes the lines after it in an inconsistent way.

### Reproduction Steps

Format below:

```v
fn main() {
	{
		println('(1/3) My first small scope')
		//
	}


	{
		println('(2/3) My second small scope')
		//
	}
	// A line below prevents the line removal

	{
		println('(3/3) My Third small scope')
	}
}
```

v fmt

```diff
fn main() {
	{
		println('(1/3) My first small scope')
		//
	}

-												
 	{
		println('(2/3) My second small scope')
		//
	}
	// A line below prevents the line removal

	{
		println('(3/3) My Third small scope')
	}
}
```

vfmt

```diff
fn main() {
	{
		println('(1/3) My first small scope')
		//
	}
-												
	{
		println('(2/3) My second small scope')
		//
	}
	// A line below prevents the line removal

	{
		println('(3/3) My Third small scope')
	}
}
```

### Expected Behavior

Keep one line after a block when it is followed by multiple empty lines and it's not the end of the function body.

### Current Behavior

above

### V version

v0.4.8

### Environment details (OS name and version, etc.)

linux

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNhZDVlZGU3Y2M1YTc4NTQyZGE3NzAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.qFJ6rwTkGj240TAnrKb3YIeI4IzMwMjhqmqdn9hzudY">Huly&reg;: <b>V_0.6-21343</b></a></sub>

**Comment by spytheman** [comment]
I think that it just collapses multiple empty lines into 1 empty line.

**Comment by spytheman** [comment]
It should stabilize after 1 run though, it should not oscillate or have to be run multiple times in a row.
