### ISSUE TITLE
enum value field is not printed correctly 

### ISSUE THREAD

**Issue by jorgeluismireles** [vlang/v#22938]
### Describe the bug

The enum `value` field is not printed correctly.

Code: https://play.vlang.io/p/d1e5b6c839

```v
enum Nums {
	one = 1
	two = 2
	ten = 10
}

fn main() {
	$for n in Nums.values {
		println('${n.name} ${n.value} ${n.value:d} ${int(n.value)}')
	}
}
```

### Reproduction Steps

The program prints four columns, the first one the enum's name field and the rest the enum's value field.

### Expected Behavior

```
one 1 1 1
two 2 2 2
ten 10 10 10
```

### Current Behavior

Program print four columns:

```
one one 1 1
two two 2 2
ten ten a 10
```

First column (name) is ok.
Second column (value) is wrong. Is not the value numeric but the string name.
Third column (value) is wrong. Now is numeric but seems forced to hexadecimal.
Fourth column (value) is ok until we make the explicit cast `int()`.

### V version

V 0.4.8 58fc4de

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.8 58fc4de
OS: linux, Debian GNU/Linux 12 (bookworm) (VM)
Processor: 2 cpus, 64bit, little endian, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz

getwd: /home/admin/playground
vexe: /home/admin/v/v
vexe mtime: 2024-11-21 19:25:29

vroot: OK, value: /home/admin/v
VMODULES: OK, value: .vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.39.5
Git vroot status: Error: fatal: detected dubious ownership in repository at '/home/admin/v'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v
.git/config present: true

CC version: cc (Debian 12.2.0-14) 12.2.0
emcc version: N/A
thirdparty/tcc status: Error: fatal: detected dubious ownership in repository at '/home/admin/v/thirdparty/tcc'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v/thirdparty/tcc
 Error: fatal: detected dubious ownership in repository at '/home/admin/v/thirdparty/tcc'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v/thirdparty/tcc
```

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNmOWFiMWQyZWY0Y2JjYzQ2Nzk1MmEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.7cFXrwQ7GMWmM2RuXkq5DubXQMzH0nnoRTt7S_IvB00">Huly&reg;: <b>V_0.6-21380</b></a></sub>

**Comment by felipensp** [comment]
The second one is just like doing `${Nums.ten}`, imho it does what was planned.

**Comment by felipensp** [comment]
The third one uses an invalid `d` spec, which makes it turns into a `(void*)` value because the enum type was no acting like an int type, for this I'll push a PR.
PS: For int types you can use: `x`, `X`, `o`, `b` and `c`.

**Comment by jorgeluismireles** [comment]
Thanks for the explanation. I am very happy with V enums and using them a lot as u8. Used them a lot in Java and then unfortunately Golang drop them out.
