### ISSUE TITLE
vfmt: Add imports grouping and sorting

### ISSUE THREAD

**Issue by gechandesu** [vlang/v#22939]
### Describe the feature

I propose adding to vfmt grouping and sorting of imports almost the same as Python isort does. For now vfmt just deletes line breaks between imports.

I found an old feature request https://github.com/vlang/v/issues/9353, here I describe the feature in more detail.

### Use Case

The goal is to make imports more visual and nice looking.

No more:

```v
import markdown
import foobar // local module
import log
import whisker.datamodel
import whisker.template
import net.http
import context
import net.html
import mylocalmod
import io
```

### Groups

It is worth dividing imports into three groups:

1. Modules from vlib
2. Third-party modules, installed via `v install [--git] <module>`
3. Local modules (found in the working directory relative to v.mod)

Groups should be separated by line breaks and follow each other in the above order.

### General sorting

Each group individually must be sorted by type in alphabetical order. For example:

```v
import context
import io
import log
import net.html
import net.http

import markdown
import whisker.datamodel
import whisker.template

import foobar
import mylocalmod
```

### Sorting imports by type

Sorting imports types in this order looks good:

```v
import net            // simple import
import net.http.file  // submodule import
import term.ui as tui // aliased import
import toml { Any }   // selective import
```

### Sorting selective imports

Symbols in selective imports should also be sorted:

```v
import toml { Config, Any } // No
import toml { Any, Config } // Yes
```

For better look, lowercase named symbols must be placed after symbols starting with a capital letter:

```v
import toml { Config, ast_to_any, Any, parse_file } // No
import toml { Any, Config, ast_to_any, parse_file } // Yes
```

### Sorting precedence

The highest priority is sorting by groups. Then each group should be sorted by import type. Alphabetical sorting is performed last.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.4.8 58fc4de

### Environment details (OS name and version, etc.)

Not important.

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNmOWI4N2QyZWY0Y2JjYzQ2Nzk1M2EiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.D5WIvJnLGQXg7IRiVSabBN_k-a3WHLz37koLH_LXbuc">Huly&reg;: <b>V_0.6-21381</b></a></sub>

**Comment by spytheman** [comment]
I prefer vfmt to not sort anything at all. That can lead to subtle bugs, because modules can have init functions with side effects, and the programmer has more information about what he/she prefers, not vfmt.

**Comment by jorgeluismireles** [comment]
> I prefer vfmt to not sort anything at all. That can lead to subtle bugs, because modules can have init functions with side effects, and the programmer has more information about what he/she prefers, not vfmt.

Now I understand that a lot of official V code have not sorted the imports. I though that like in Golang, we can sort the names and later the language will call all the corresponding `init()` correctly. I think our eyes like to see the beginning of any V file as "nice" as possible.

**Comment by spytheman** [comment]
In most cases the order does not matter (the modules are sorted in topological order when there are dependencies), but not in *all* (in the presence of side effects, inside the same file), and forcing vfmt to reorder stuff for aesthetic reasons will break that.
