### ISSUE TITLE
x.json2.decoder2: nested map decode

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#22954]
### Describe the bug

The

```v
fn (mut checker Decoder) check_json_format(val string) ! 
```

is creating a wrong `length` in `ValueInfo` in `LinkedList`

### Reproduction Steps

```v
import x.json2.decoder2 as json

fn test_array_of_strings() {
	// nested map
	assert json.decode[map[string]map[string]string]('{"val": {"val2": "2"}}')! == {"val": {"val2": "2"}}
}
```

### Expected Behavior

decoding

### Current Behavior

```sh
/home/admin/v/vlib/x/json2/decoder2/decode.v:753:15: error: cannot copy map: call `move` or `clone` method (or use a reference)
  751 |             decoder.decode_value(mut map_value)!
  752 | 
  753 |             val[key] = map_value
      |                        ~~~~~~~~~
  754 |         }
  755 |     }
Exited with error status 1
Please try again.
```

### V version

V 0.4.8 e4d24e8

### Environment details (OS name and version, etc.)

Linux

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQyMzA0MWQyZWY0Y2JjYzQ2ODRjYWEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.cak5SnlGB962rWTAPlUGSkbzqGcink32nW64LXVfoyw">Huly&reg;: <b>V_0.6-21396</b></a></sub>

**Comment by felipensp** [comment]
Just do like this one:

![image](https://github.com/user-attachments/assets/633707a3-e326-4f2a-8d61-6ce852f1a2a6)
