### ISSUE TITLE
Wrong behavior of `!(Type, ?Type)` result tuple

### ISSUE THREAD

**Issue by gechandesu** [vlang/v#22951]
### Describe the bug

Subject

### Reproduction Steps

```v
module main

fn foo(f int) !(int, ?int) {
	if f < 0 {
		return error('f is negative')
	}
	if f > 0 {
		return 1, f
	}
	return 0, none
}

fn main() {
	a, b := foo(-1) or { 2, 2 } // since foo arg is negative int, error must occurs
	c := b as int
	assert a == 2
	assert c == 2

	a2, b2 := foo(0) or { 2, 2 }
	c2 := b2 as int
	assert a2 == 0
	assert c2 == 0

	a3, b3 := foo(1) or { 2, 2 }
	c3 := b3 as int
	assert a3 == 1
	assert c3 == 1
}
```

### Expected Behavior

In shot: all assertions must be passed.

Values listed in `or {}` must be applied here since `foo(-1)` raises an error:

```v
a , b := foo(-1) or { 2, 2 }

c := b as int
assert a == 2
assert c == 2
```

In `foo(0)` case `b` must be `Option(none)`:

```v
a , b := foo(0) or { 2, 2 }

c := b as int // Option(none) casts to 0
assert a == 0
assert c == 0
```

Finally:

```v
a , b := foo(1) or { 2, 2 }

c := b as int
assert a == 1
assert c == 1
```

### Current Behavior

```v
a, b := foo(-1) or { 2, 2 } // since foo arg is negative int, error must occurs
println(a) // output: 2
println(b) // output: Option(none) but Option(2) expected
```

### V version

V 0.4.8 393e4ea

### Environment details (OS name and version, etc.)

V full version: V 0.4.8 5ec9bb5.393e4ea
OS: linux, Linux version 6.6.8-arch1-1 (linux@archlinux) (gcc (GCC) 13.2.1 20230801, GNU ld (GNU Binutils) 2.41.0) #1 SMP PREEMPT_DYNAMIC Thu, 21 Dec 2023 19:01:01 +0000
Processor: 16 cpus, 64bit, little endian, 12th Gen Intel(R) Core(TM) i5-1240P

getwd: /home/ge/Code/v/netaddr/issues
vexe: /home/ge/.vlang/v
vexe mtime: 2024-11-23 13:05:19

vroot: OK, value: /home/ge/.vlang
VMODULES: OK, value: /home/ge/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.46.1
Git vroot status: weekly.2024.47-20-g393e4ea8
.git/config present: true

CC version: cc (GCC) 14.2.1 20240910
emcc version: N/A
thirdparty/tcc status: thirdparty-linux-amd64 0134e9b9

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQyMDI3OWQyZWY0Y2JjYzQ2ODQ4M2EiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.lbp89whkozqR-zPkqg92ZbAWTyQ5sq5GriH1Dd7Xf-M">Huly&reg;: <b>V_0.6-21393</b></a></sub>

**Comment by Delta456** [comment]
`!?int` doesn't work in the below code, I don't know if `!(int, ?int)`  should work.

```v
fn foo (f int) !?int {
	return 0
}
```

**Comment by JalonSolov** [comment]
Yes.  Follow the discord discussion here:  https://discord.com/channels/592103645835821068/592114487759470596/1309895826666950699
