### ISSUE TITLE
Method that returns itself and has a mutable receiver does not compile

### ISSUE THREAD

**Issue by scottywz** [vlang/v#230]
```
struct Item {
 thing int
}

fn (i mut Item) do_thing() Item {
 // i.thing += 1  // Edit: does not compile whether or not this is commented out
 return i
}
```

does not compile ("You just found a bug.").  However, these functions (with the same struct definition) do compile:

```
fn (i mut Item) do_thing_2() Item {
 return Item{thing: i.thing + 1}
}

fn (i Item) return_self() Item {
 return i
}
```

**Comment by medvednikov** [comment]
Good find. I think returning a mutable receiver should simply not be allowed.

**Comment by medvednikov** [comment]
This works:

```
struct Item {
 thing int
}

fn (i mut Item) do_thing() Item {
 return *i
}
```

Dereferencing is disabled on the playground at the moment though.

**Comment by scottywz** [comment]
A use case for returning a mutable receiver would be method chaining, especially for large structs where returning a copy would be inefficient, and also for C interop.  Will returning a mutable receiver continue to be allowed through dereferencing?

**Comment by medvednikov** [comment]
Ok it's a useful case, I'll think about the best way to implement this.

**Comment by ntrel** [comment]
Returning a reference is very important for iterators to allow modifying elements. Consider an iterator that supports indexing, index returns a reference:

it := find(container, 7)
it.index(0) = 42

Returning a reference can also cause memory safety violations. The compiler should not allow those functions to return a reference to local variables. See also a more complex example in D when returning the result of another function which itself returns a reference:
https://dlang.org/spec/function.html#return-ref-parameters

**Comment by medvednikov** [comment]
Memory safety is the primary reason I wanted to not allow them.

Iterators make compile time safety harder as well. Go works fine without them, I don't see the advantages of iterators over simple arrays.

**Comment by ntrel** [comment]
&gt; fn (i mut Item) do_thing() Item {
&gt; return *i

Before the return statement, I can write i = Item{}, not *i = Item{}. So it is inconsistent that dereferencing is required in the return expression.

**Comment by ntrel** [comment]
Iterators are needed in generic programming to write algorithms that don't depend on only one container type. Arrays are sometimes inefficient, that's why we also have maps, but we might want a balanced tree or something else.

Iterators don't require supporting modifying elements, they are still very useful without that ability.

**Comment by ntrel** [comment]
&gt; Iterators make compile time safety harder as well

How do you mean?

**Comment by medvednikov** [comment]
You can write any data structure you want without iterators. Using your example above:

Instead of
```
it := find(container, 7)
it.index(0) = 42
```

we can simply have

```
container.set(7, 0, 42)
```

Or if overloading `[]` becomes possible:

```
container[7][0] = 42
```

Having multiple mutable references to the same data complicates compile time memory management.

**Comment by ntrel** [comment]
So you're saying that all containers should have to support your set method. But what about all the other thousands of highly specific algorithms? With iterators you write one of those algorithms once, and it works with every container that supports iterators.

**Comment by medvednikov** [comment]
This should be discussed on Slack to avoid spamming hundreds of people :) It's also not related to the original issue.

**Comment by ntrel** [comment]
I tried slack just now but couldn't understand the Android app. I've made #234 to discuss mutating container elements.

> Having multiple mutable references to the same data complicates compile time memory management.

Yes, but iterators don't require functions returning mutable references.

**Comment by ntrel** [comment]
> Returning a reference can also cause memory safety violations

I think these can be avoided if we only allow methods to return a reference to a receiver field:
```rust
fn (c mut Container) index(i usize) mut
{return c.arr[i]}

c.index(0) += 1
```

**Comment by medvednikov** [comment]
Fixed.

Your example now compiles.
