### ISSUE TITLE
Compiler accept an empty interface as generic type

### ISSUE THREAD

**Issue by jorgeluismireles** [vlang/v#23005]
### Describe the bug

Compiler is accepting an empty interface as generic type

### Reproduction Steps

```v

interface Interface { }

struct Result[T] {
	data []T
}

fn main() {
	println(Result[Interface]{})
}
```

The compiler "accepts" the object Result[Interface]{}:

```
Result[Interface]{
    data: []
}
```

### Expected Behavior

Reject the use of interface as generic type and indicate the code line where the bad code is located.

### Current Behavior

Accepts the interface as generic type.

### Additional Information/Context

First reported here: https://github.com/vlang/v/issues/23000

### V version

V 0.4.8 acad4c2

### Environment details (OS name and version, etc.)

https://play.vlang.io/

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQ4ZmNmNWQyZWY0Y2JjYzQ2YzQ1OTgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.QwQhb4j9W26OddWZYcvO3TG3qcjmunWxnlA4KdS3mYI">Huly&reg;: <b>V_0.6-21446</b></a></sub>

**Comment by felipensp** [comment]
Bug or feature? This looks like a empty interface as Go has for `any` type. @medvednikov something still planned for empty interface?

**Comment by jorgeluismireles** [comment]
I didn't know how flexible is the empty interface. An array of empty interfaces can hold almost everything including copies of itself!
```v
interface Interface { }

fn main() {
	mut i := []Interface{}
	i << 5    // 1
	i << 5.0  // 2
	i << i[0] // 3
	i << i    // 6
	i << i    // 12
	i << i    // 24
	println('${i.len}') // 48
}
```

**Comment by felipensp** [comment]
Not a bug.

**Comment by jorgeluismireles** [comment]
Yes, thanks. In order to append *things* we can use `insert` function instead of `<<` and now we have an array of four things for four operations. Elements can be retrieved with corresponding `match` and updated as references. Seem similar than `SumTypes` but without defining any (ironic).
```v
interface Any { }

fn main() {
	mut a := []Any{}
	a.insert(0, Any(5))
	a.insert(1, Any(5.1))
	a.insert(2, Any(a[0]))
	a.insert(3, Any(a))
	println('${a.len}') // 4 OK
	last := a.last()
	match last {
		[]Any {
			for elem in last {
				match elem {
					int { unsafe { (*elem)++ } }
					else { }
				}
			}
		}
		else {
		}
	}
	println('${a}') // [Any(7), Any(5.1), Any(7), ] OK
}
```
