### ISSUE TITLE
Array of empty interface push array of arrays C error

### ISSUE THREAD

**Issue by jorgeluismireles** [vlang/v#23012]
### Describe the bug

We push an array of arrays to an array of empty interface. Pushing an array of arrays of size 1 are accepted. By pushing an array of arrays of size greater than 1 we got a C error.

### Reproduction Steps

```v
interface Any { }

fn main() {
	mut a := []Any{}
	a << [1] // accepted
	a << [[2]] // accepted
	a << [[[3]]] // accepted
	a << [[4],[5]] // FAILS
	dump('${a}')
}
```

### Expected Behavior

Prevent the compilation of line `a << [[4],[5]]` with an indication or somehow append both `[4]` and `[5]` items.

### Current Behavior

```
Running code...
Can't run code. The server returned an error:
/tmp/v_60000/../../../../../../box/code.v:8: warning: implicit declaration of function 'I_Array_int_to_Interface_main__Any'
/tmp/v_60000/../../../../../../box/code.v:8: warning: assignment makes pointer from integer without a cast
/tmp/v_60000/../../../../../../box/code.v:8: warning: cast between pointer and integer of different size
/home/admin/v/thirdparty/tcc/lib/libgc.a: error: 'GC_noop1_ptr' defined twice
tcc: error: undefined symbol 'I_Array_int_to_Interface_main__Any'
builder error: 
==================
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .
Exited with error status 1
Please try again.
```

### V version

V 0.4.8 f2c281e

### Environment details (OS name and version, etc.)

https://play.vlang.io/p/9240801fb7

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRhN2Y2OWQyZWY0Y2JjYzQ2Y2IxOGQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.HzUB8aSiz9jVHcv-jQuI2ugTJ1Vztg7m1S-F01MYdIs">Huly&reg;: <b>V_0.6-21453</b></a></sub>

**Comment by jorgeluismireles** [comment]
This issue result have changed since new V commits. For V 0.4.8 db49874 for the same code,  the result is no longer a C error but:
```
[code.v:9] '$a': [Any(1), Any([2]), Any([[3]]), Any([4]), Any([5])]
```
I don't know exactly whether is correct to insert 4 and 5 as elements instead of an array o arrays but I wanted to notify the result changed.

**Comment by felipensp** [comment]
The related commit does not seems related to the issue. But it seems working as expected now.
