### ISSUE TITLE
Missing compiling error on `f_expecting_int(  u32_number )`

### ISSUE THREAD

**Issue by archyboy** [vlang/v#23016]
### Describe the bug

It casted it into a negative int  and panics when random e.ntropy is negative

### Reproduction Steps

module main

import rand
import crypto

e := rand.u32()
println(e) // 2608521547
r := rand.bytes(e)!.bytestr()

### Expected Behavior

Compiler throw an error  "cannot use `u32` as `int` in argument 1 to `rand.bytes`"

### Current Behavior

V panic: result not set (can not read < 0 random bytes)
v hash: 602b097
/tmp/v_1000/godrand.01JDYMXS7BFK19509M8VPVGNA3.tmp.c:9131: at _v_panic: Backtrace
/tmp/v_1000/godrand.01JDYMXS7BFK19509M8VPVGNA3.tmp.c:9095: by panic_result_not_set
/tmp/v_1000/godrand.01JDYMXS7BFK19509M8VPVGNA3.tmp.c:23594: by main__main
/tmp/v_1000/godrand.01JDYMXS7BFK19509M8VPVGNA3.tmp.c:23717: by main

### Possible Solution

Quote spytheman
"until we have a 64 bit `int` type, the compiler should check them properly"

### V version

V 0.4.8 602b097

### Environment details (OS name and version, etc.)

Arch Linux

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRiMTgwNmQyZWY0Y2JjYzQ2Y2JhNzMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.5VtDbzLo0u6yVnTc4HvrpgAcPDPmtwaLVxuWhnHVfqU">Huly&reg;: <b>V_0.6-21457</b></a></sub>

**Comment by spytheman** [comment]
The compiler should have prevented the automatic cast of u32 -> int, since it can overflow the int (which is still 32 bit currently). 

https://docs.vlang.io/v-types.html#primitive-types also documents it as such.

**Comment by spytheman** [comment]
A smaller reproduction of the problem is:
```v
fn f(x int) { println(x) }
x := u32(2251797157)
println(x)
f(x)
```
which currently compiles without errors (and it should not), and prints:
```
2251797157
-2043170139
```
which shows that the overflow happened due to the automatic cast.

**Comment by JalonSolov** [comment]
One _could_ argue the code is currently acting in a historically correct manner.  A lot of older C code is written to take advantage of this "feature".

So there are 2 ways to "fix" this issue...

1. document the current behavior.
2. catch and add an error

**Comment by archyboy** [comment]
3. Compiler warning for older C code compatibility ?
