### ISSUE TITLE
add array.count

### ISSUE THREAD

**Issue by Le0Developer** [vlang/v#23028]
### Describe the feature

count() function on array, similar to string.count

### Use Case

counting how often an element is in an array

https://github.com/vlang/adventofcode/blob/b5eabb1722543b45f632e25cba151a89204ebfc1/2024/01/leodev.v#L33

### Proposed Solution

array.count()

### Other Information

workaround is `arr.filter(it == what).len`, but it allocates a new array.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

N/A

### Environment details (OS name and version, etc.)

N/A

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRjMzIwOGQyZWY0Y2JjYzQ2Y2ZkNWMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.9Mlneyz4mtsQodF31GaD8Uf2GicHXaVsDX_GCjFlsAk">Huly&reg;: <b>V_0.6-21469</b></a></sub>

**Comment by felipensp** [comment]
I've submitted a PR to optimize `.len` operation on array.filter() 👍🏻

**Comment by Le0Developer** [comment]
While a nice optimization, I don't think it's intuitive and assumes people know what the cgen is doing.

**Comment by spytheman** [comment]
imho it should be a method, just like s.count()

**Comment by spytheman** [comment]
it is a common enough and general operation, to be in `builtin`

**Comment by medvednikov** [comment]
I'm fine with a new method similar to any(), filter() etc
