### ISSUE TITLE
unary operator on -9223372036854775808 does not invert

### ISSUE THREAD

**Issue by Le0Developer** [vlang/v#23036]
**V doctor:**

```
V full version: V 0.4.8 602b097.94ce64c
OS: macos, macOS, 15.1.1, 24B2091
Processor: 10 cpus, 64bit, little endian, Apple M4

getwd: /Users/leodev/p/v/fast2
vexe: /Users/leodev/p/v/v/v
vexe mtime: 2024-12-01 10:31:00

vroot: OK, value: /Users/leodev/p/v/v
VMODULES: OK, value: /Users/leodev/.vmodules
VTMP: OK, value: /tmp/v_501

Git version: git version 2.47.0
Git vroot status: weekly.2024.48-35-g94ce64c6 (2 commit(s) behind V master)
.git/config present: true

CC version: Apple clang version 16.0.0 (clang-1600.0.26.4)
emcc version: N/A
thirdparty/tcc status: thirdparty-macos-arm64 713692d4
```

**What did you do?**
`./v -g -o vdbg cmd/v && ./vdbg repro.v`

```v
fn main() {
    x := i64(-9223372036854775808)
    dump(x)
    dump(-x)
}
```

**What did you expect to see?**

2nd number should be positive

**What did you see instead?**

```
[repro.v:3] x: -9223372036854775808
[repro.v:4] -x: -9223372036854775808
```

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRjN2VjZWQyZWY0Y2JjYzQ2ZDA0ZWEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Th48So-nTpocxdbP_k-muV-B9sXPouz2fJs_l2knXqs">Huly&reg;: <b>V_0.6-21476</b></a></sub>

**Comment by Delta456** [comment]
I am not sure if this is an issue because Go also outputs the same

Playground Link: https://go.dev/play/p/J5OPWGybdCF

**Comment by Le0Developer** [comment]
I only just realized this is Int64 max + 1. So there indeed is no real solution for this, but its still very unintuitive.

I stumbled upon this because somehow this value made it into a `time.Duration` and `the time.Duration.str()` output `--808ns` (note the double `-`)
