### ISSUE TITLE
V generic function return

### ISSUE THREAD

**Issue by thesombady** [vlang/v#23035]
### Describe the bug

A generic function, that takes a generic function as input, and returns another generic function as return type causes type-checker failure.

### Reproduction Steps

```v
fn vectorize[T](op fn (T) T) fn ([]T) []T {
    return fn [op] [T](values []T) []T {
        // return []T{len: values.len, init: op(values[index])} // Is it more readable?
        mut result := []T{len: values.len}
        for i in 0 .. values.len {
            result[i] = op(values[i])
        }
        return result
    }
}
fn add_one(x f64) f64 {
    return x + 1
}
fn main() {
    vadd := vectorize[f64](add_one)
    v := [1.0, 2, 3, 4]
    assert vadd(v) == [2.0, 3, 4, 5]
}
```

### Expected Behavior

Expected behaviour is a vectorised function in this case.

### Current Behavior

Type-checker complains and produces the following error: `cannot use fn ([]T) []T as type fn ([]f64) []f64 in return argument`

### Possible Solution

Most likely something with the type-checker.

### V version

V 0.4.8 d8021bd

### Environment details (OS name and version, etc.)

V full version: V 0.4.8 c4aaa2e.d8021bd
OS: macos, macOS, 14.5, 23F79
Processor: 8 cpus, 64bit, little endian, Apple M2

getwd: /Users/andreas/dev/vstats
vexe: /Users/andreas/v/v
vexe mtime: 2024-12-01 14:49:51

vroot: OK, value: /Users/andreas/v
VMODULES: OK, value: /Users/andreas/.vmodules
VTMP: OK, value: /tmp/v_501

Git version: git version 2.46.0
Git vroot status: weekly.2024.34-738-gd8021bd4
.git/config present: true

CC version: Apple clang version 15.0.0 (clang-1500.3.9.4)
emcc version: N/A
thirdparty/tcc status: thirdparty-macos-arm64 713692d4

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRjN2FhZWQyZWY0Y2JjYzQ2ZDA0ZDgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.b9YGgSWP828uinhVbsSgS5D5D0LUisfTfTtABgLLxyo">Huly&reg;: <b>V_0.6-21475</b></a></sub>

**Comment by felipensp** [comment]
It seems related to #22011
