### ISSUE TITLE
empty interface value is error in multiple match

### ISSUE THREAD

**Issue by kitech** [vlang/v#23060]
### Describe the bug

Code: https://play.vlang.io/p/25f365b81b

```v

interface  Number2  {}

fn t(v  Number2) {

	match v {
		int, i32, isize, i64 {
			x := isize(v)
			println(x)
		}
		else{}
	}
	
}
t(int(42))
```

### Reproduction Steps

run playground

### Expected Behavior

out should be:
42

### Current Behavior

Output:

```
22645727616992
```

### V version

V 0.4.8 a40df55

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.8 a40df55
OS: linux, Debian GNU/Linux 12 (bookworm) (VM)
Processor: 2 cpus, 64bit, little endian, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz

getwd: /home/admin/playground
vexe: /home/admin/v/v
vexe mtime: 2024-12-04 01:25:28

vroot: OK, value: /home/admin/v
VMODULES: OK, value: .vmodules
VTMP: OK, value: /tmp/v_0

Git version: git version 2.39.5
Git vroot status: Error: fatal: detected dubious ownership in repository at '/home/admin/v'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v
.git/config present: true

CC version: cc (Debian 12.2.0-14) 12.2.0
emcc version: N/A
thirdparty/tcc status: Error: fatal: detected dubious ownership in repository at '/home/admin/v/thirdparty/tcc'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v/thirdparty/tcc
 Error: fatal: detected dubious ownership in repository at '/home/admin/v/thirdparty/tcc'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/admin/v/thirdparty/tcc
```

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRmYjk5M2QyZWY0Y2JjYzQ2ZTAyZjkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.XdhL6KT_2qeZD-DAmy2yqxN4Dvlli1URjcSV62IQdZg">Huly&reg;: <b>V_0.6-21500</b></a></sub>

**Comment by jorgeluismireles** [comment]
Yes, is the empty interface because a sum type like `type Number2 = int | string` has no this problem. Seems the problem is the `x := isize(v)` line which takes a "random address" different every time you run the code:
```v
interface Number2 {}

fn t(v Number2) {
	match v {
		int {
			x := isize(v) // 'random-address'
			println('${v} ${isize(v)} ${x}') // 42 42 'random-address'
		}
		else{}
	}
}
t(42)
```
