### ISSUE TITLE
Failed to compile when a piece of code include `#pkgconfig`

### ISSUE THREAD

**Issue by abc-JYL** [vlang/v#23064]
### Describe the bug

I write a simple piece of code to make a c wrapper for tcl/tk
Code:

```
module tk

#pkgconfig tcl tk

// Define C stuff
```

The `#pkgconfig` line can't find `zlib`

Full error

```
src/lib.v:3:1: error: could not resolve dependency zlib
    1 | module tk
    2 |
    3 | #pkgconfig tcl tk
      | ~~~~~~~~~~~~~~~~~
    4 |
    5 | #include <tcl.h>
```

I found out that the standard `pkg-config` return none when `pkg-config --cflags zlib`

### Reproduction Steps

Write a piece of code that included `#pkgconfig`

### Expected Behavior

It should successfully compile and have zero problems.

### Current Behavior

Currently, the V compile emit a error says: `error: could not resolve dependency zlib`

### Possible Solution

I think there is some problem in the `vlib.pkgconfig` that did not handle the case that is not defined or filter out in the `.pc` files.

### Additional Information/Context

error with `zlib`

```
src/lib.v:3:1: error: Cannot find "zlib" pkgconfig file
    1 | module tk
    2 |
    3 | #pkgconfig zlib
      | ~~~~~~~~~~~~~~~
    4 |
    5 | #include <tcl.h>
```

### V version

Current V version: V 0.4.8 b103ce3, timestamp: 2024-12-04 14:11:21 +0200

### Environment details (OS name and version, etc.)

Macbook Air M2 (2022)
8 GB of RAM
MacOs Version: Sonoma 14.1.1

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzUwNjNlZWQyZWY0Y2JjYzQ2ZTdlMjciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.eqA8Yj10BPCdh-XrTaleIRKkDOmMiHg52RMiMTVVZT8">Huly&reg;: <b>V_0.6-21504</b></a></sub>

**Comment by jorgeluismireles** [comment]
Did you try `#pkgconfig --libs --cflags ...`?

**Comment by abc-JYL** [comment]
> Did you try `#pkgconfig --libs --cflags ...`?

Yes, I did it also emit the same error.

**Comment by jorgeluismireles** [comment]
> I found out that the standard pkg-config return none when pkg-config --cflags zlib
Same here, but next give me results:
```bash
$ pkg-config --modversion zlib
1.2.11
$ pkg-config --libs zlib
-lz
```

**Comment by jorgeluismireles** [comment]
In my system `pkg-config --list-all` did not show any `tcl`. I went to https://www.tcl-lang.org/doc/howto/compile.html#source and download the `tcl 8.6`. Then did `configure`, `make`, `make install`. Now pkg-config has the tcl:
```
$ pkg-config --list-all | grep tcl
tcl                            Tool Command Language - Tcl is a powerful, easy-to-learn dynamic programming language, suitable for a wide range of uses.
$ pkg-config --modversion tcl
8.6.15
$ pkg-config --libs tcl
-L/usr/local/lib -ltcl8.6 -ltclstub8.6
$ pkg-config --cflags tcl
-I/usr/local/include
```

**Comment by abc-JYL** [comment]
> > I found out that the standard pkg-config return none when pkg-config --cflags zlib
> 
> Same here, but next give me results:
> 
> ```shell
> $ pkg-config --modversion zlib
> 1.2.11
> $ pkg-config --libs zlib
> -lz
> ```

But `pkg-confifg --cflags zlib` return none

**Comment by jorgeluismireles** [comment]
> But `pkg-config --cflags zlib` return none

I think `pkg-config` issues so far aren't related to V language until now but maybe a C compiler issue. I am also interested in `tcl/tk`, `tk`was a very decent multi-platform GUI that predated Java and is very underrated in my opinion. Is very easy do small tk apps with python. I'll try to install `tk`and give it a try as a wrapper for `V` and report whatever I get to compare.

**Comment by jorgeluismireles** [comment]
### C version
This is a small TCL interpreter called from C named `tclsh.c`:
```c
# include <tcl.h>

int AppInit(Tcl_Interp *interp) {
	if (Tcl_Init(interp) == TCL_ERROR)
		return TCL_ERROR;
	Tcl_SetVar(interp, "tcl_rcFileName", "~/.wishrc", TCL_GLOBAL_ONLY);
	return TCL_OK;
}

int main(int argc, char *argv[]) {
	Tcl_Main(argc, argv, AppInit);
	return 0;
}
```
With my installation mentioned before compiles with
```bash
$ gcc tclsh.c -o tclsh -ltcl8.6
```
And run and the interpreter is functional (I entered a sum of numbers 1 and 2):
```bash
$ ./tclsh
% expr {1+2}
3
%
```
### V version
Now this is my attemp to convert to V called `tclsh.v`:
```v
module main

#pkgconfig --libs --cflags tcl

#include <tcl.h>

fn C.Tcl_Main(argc int, argv &&char, init &voidptr)

//@[typedef]
struct C.Tcl_Interp{}

fn C.Tcl_Init(interp &C.Tcl_Interp) int

fn C.Tcl_SetVar(&C.Tcl_Interp, &char, &char, int)

fn app_init(interp &C.Tcl_Interp) int {
	if C.Tcl_Init(interp) == C.TCL_ERROR {
		return C.TCL_ERROR
	}
	C.Tcl_SetVar(interp, c'tcl_rcFileName', c'~/.wishrc', C.TCL_GLOBAL_ONLY)

	return C.TCL_OK
}

fn main() {
	C.Tcl_Main(0, g_main_argv, app_init)
}
```
#pkgconfig is accepted **BUT** it doesn't work.

With `tcc` I got this:
```
$ v -show-c-output run tclsh.v
======== Output of the C Compiler (/home/jorge/v/thirdparty/tcc/tcc.exe) ========
/home/jorge/v/thirdparty/tcc/lib/libgc.a: error: 'GC_noop1_ptr' defined twice
=================================================================================
0x74ca7979d7fd: at ???: RUNTIME ERROR: invalid memory access
```
With `gcc` I got this:
```
$ v -cc gcc -show-c-output run tclsh.v
======== Output of the C Compiler (gcc) ========

================================================
signal 11: segmentation fault
                                                        | 0x7e9f1e242520 | /lib/x86_64-linux-gnu/libc.so.6(+0x42520) 
                                                        | 0x7e9f1e39d7fd | /lib/x86_64-linux-gnu/libc.so.6(+0x19d7fd) 
                                                        | 0x7e9f1e65012d | /lib/x86_64-linux-gnu/libtcl8.6.so(Tcl_ExternalToUtfDString+0x16d) 
                                                        | 0x7e9f1e697a96 | /lib/x86_64-linux-gnu/libtcl8.6.so(Tcl_MainEx+0x136) 
                                                        | 0x5a878e2242db | /home/jorge/gitlab.com/jmireles/viva/tcl/extending/tclsh(+0x2e2db) 
                                                        | 0x5a878e2244e0 | /home/jorge/gitlab.com/jmireles/viva/tcl/extending/tclsh(+0x2e4e0) 
                                                        | 0x7e9f1e229d90 | /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) 
                                                        | 0x7e9f1e229e40 | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) 
                                                        | 0x5a878e1f9ed5 | /home/jorge/gitlab.com/jmireles/viva/tcl/extending/tclsh(+0x3ed5)
```
Help wanted.

**Comment by jorgeluismireles** [comment]
After some `v up` for other things, the code above worked. Even I run `v -prod tcl_sh.v` and generated a 175kb working app. So for me the `pkgconfig` issue works I assume after a fresh tcl dev installation in the default folders.

**Comment by jorgeluismireles** [comment]
For completeness here is a `tk` app with a script embed:
```v
module main

#pkgconfig tcl
#pkgconfig tk

#include <tcl.h>
#include <tk.h>

@[typedef]
struct C.Tcl_Interp{}

fn C.Tk_MainEx(argc int, argv &&char, init voidptr, &C.Tcl_Interp)

fn C.Tcl_Init(interp &C.Tcl_Interp) int
fn C.Tk_Init(interp &C.Tcl_Interp) int
fn C.Tcl_Eval(interp &C.Tcl_Interp, script &char) int
fn C.Tcl_EvalFile(interp &C.Tcl_Interp, filename &char) int
fn C.Tcl_CreateInterp() &C.Tcl_Interp

fn app_init(interp &C.Tcl_Interp) int {

    if C.Tcl_Init(interp) == C.TCL_ERROR {
        return C.TCL_ERROR
    }
    if C.Tk_Init(interp) == C.TCL_ERROR {
        return C.TCL_ERROR
    }
    script := [
		'wm title . "Doodle in V"'
		''
		'proc doodle {w {color black}} {'
		'   bind \$w <1>         [list doodle\'start %W %x %y \$color]'
		'   bind \$w <B1-Motion> {doodle\'move %W %x %y}'
		'}'
		'proc doodle\'start {w x y color} {'
		'   set ::_id [\$w create line \$x \$y \$x \$y -fill \$color]'
		'}'
		'proc doodle\'move {w x y} {'
		'	\$w coords \$::_id [concat [\$w coords \$::_id] \$x \$y]'
		'}'
		'pack [canvas .c -bg white] -fill both -expand 1'
		'doodle       .c'
		'bind .c <Double-3> {%W delete all}'
	]
	lines := script.join('\n').str

    C.Tcl_Eval(interp, unsafe { &lines[0] })
    //C.Tcl_EvalFile(interp, c'doodle.tcl')
    return C.TCL_OK
}

fn main() {
	C.Tk_MainEx(g_main_argc, g_main_argv, app_init, C.Tcl_CreateInterp())
}


```
![Screenshot from 2024-12-06 20-02-53](https://github.com/user-attachments/assets/ff2a890b-15fd-4e0f-99a5-51d2a3111d9c)
This is the TCL script which implements the drawing:
```tcl
package require Tk
wm title . Draw

proc doodle {w {color black}} {
   bind $w <1>         [list doodle'start %W %x %y $color]
   bind $w <B1-Motion> {doodle'move %W %x %y}
}
proc doodle'start {w x y color} {
   set ::_id [$w create line $x $y $x $y -fill $color]
}
proc doodle'move {w x y} {
   $w coords $::_id [concat [$w coords $::_id] $x $y]
}
pack [canvas .c -bg white] -fill both -expand 1
doodle       .c
bind .c <Double-3> {%W delete all}
```
Yes, technology from the 90s.

**Comment by abc-JYL** [comment]
Since I installed Linux on my mac so let me try, @jorgeluismireles you since pretty interest in tcl/tk, why not make a tcl/tk wrapper together?

**Comment by abc-JYL** [comment]
I did work on linux maybe their is some env problem on macos

**Comment by abc-JYL** [comment]
Any way @jorgeluismireles I will create a new github repo you are welcome to contribute!

**Comment by jorgeluismireles** [comment]
> Any way @jorgeluismireles I will create a new github repo you are welcome to contribute!

Thanks, you could open a discussion and in there share ideas and findings.

**Comment by abc-JYL** [comment]
> > Any way @jorgeluismireles I will create a new github repo you are welcome to contribute!
> 
> Thanks, you could open a discussion and in there share ideas and findings.

Here is the github repo link: `https://github.com/abc-JYL/tcl`

**Comment by spytheman** [comment]
Please try again with latest V. I've added more brew folders that are searched for .pc files, #pkgconfig zlib and #pkgconfig tk, which depended on it, should work now on macos.

**Comment by abc-JYL** [comment]
Fixed: `export PKG_CONFIG_PATH="/opt/homebrew/opt/zlib/lib/pkgconfig"` to add zlib to pkg-config path
