### ISSUE TITLE
V still supports `<>` in generics, without any warnings, even though `<>` was dropped a long time ago in favor of `[]`

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#23072]
### Describe the bug

`<>` is accepted in generics, and it shouldn't be, or it should at least give a warning/error.

### Reproduction Steps

```v
pub fn what1<A>(params ...A) {
        println(params)
}
```

### Expected Behavior

Warning/error about using `<>` instead of `[]`.

### Current Behavior

No messages at all.  Still works.

### V version

V 0.4.8 3254987

### Environment details (OS name and version, etc.)

```
V full version: V 0.4.8 efa98d9.3254987
OS: linux, "Manjaro Linux"
Processor: 32 cpus, 64bit, little endian, AMD Ryzen 9 7950X 16-Core Processor

getwd: /home/jalon
vexe: /home/jalon/git/v/v
vexe mtime: 2024-12-05 13:58:10

vroot: OK, value: /home/jalon/git/v
VMODULES: OK, value: /home/jalon/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.47.1
Git vroot status: weekly.2024.49-28-g3254987b
.git/config present: true

CC version: cc (GCC) 14.2.1 20240910
emcc version: N/A
thirdparty/tcc status: thirdparty-linux-amd64 0134e9b9
```

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzUyMDdmZGQyZWY0Y2JjYzQ2ZjJkNDIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.aJUYbYmQOpt5rA-NTEwbaIoXXwXD2kqIJk5p1aUmnEM">Huly&reg;: <b>V_0.6-21512</b></a></sub>

**Comment by Delta456** [comment]
I think there's still code which handles `<>` and can break.

**Comment by JalonSolov** [comment]
Then those things need to be fixed.  From the CHANGELOG for V 0.3.3, back in January 2023:

`[]` is now used for generics instead of `<>`.

**Comment by spytheman** [comment]
Yeah, it is time to clean it up.

**Comment by spytheman** [comment]
Same as with `[old]` vs `@[new]` which is from August last year.
