### ISSUE TITLE
Incorrect code compiles

### ISSUE THREAD

**Issue by gechandesu** [vlang/v#23079]
**V doctor:**

```
V full version: V 0.4.8 5ec9bb5.210239f
OS: linux, Linux version 6.6.8-arch1-1 (linux@archlinux) (gcc (GCC) 13.2.1 20230801, GNU ld (GNU Binutils) 2.41.0) #1 SMP PREEMPT_DYNAMIC Thu, 21 Dec 2023 19:01:01 +0000
Processor: 16 cpus, 64bit, little endian, 12th Gen Intel(R) Core(TM) i5-1240P

getwd: /home/ge/Code/v/netaddr/issues
vexe: /home/ge/.vlang/v
vexe mtime: 2024-12-06 14:35:08

vroot: OK, value: /home/ge/.vlang
VMODULES: OK, value: /home/ge/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.47.1
Git vroot status: weekly.2024.49-31-g210239fb
.git/config present: true

CC version: cc (GCC) 14.2.1 20240910
emcc version: N/A
thirdparty/tcc status: thirdparty-linux-amd64 0134e9b9
```

**What did you do?**
`./v -g -o vdbg cmd/v && ./vdbg self_call_fn.vv`

```v
fn foo() bool {
	return !foo()
}

fn main() {
	println(foo())
}
```

**What did you expect to see?**

This code should not compile.

**What did you see instead?**

```
Terminated by signal 11 (SIGSEGV)
```

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzUzMGNiM2QyZWY0Y2JjYzQ2ZjYxNmUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.lv2YHyBjX1yXHqK2JLDSpjFL2UaF-KUpwhQ6kqhbwh4">Huly&reg;: <b>V_0.6-21518</b></a></sub>
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by spytheman** [comment]
This is valid code.
V can not prevent you from doing infinite loops or unlimited recursion, when that is exactly what you wanted.
