### ISSUE TITLE
checker: incorrect cannot use `?time.Duration` as type `?i64` in return argument

### ISSUE THREAD

**Issue by Le0Developer** [vlang/v#23087]
**V doctor:**

```
V full version: V 0.4.8 602b097.e32e9f7
OS: macos, macOS, 15.1.1, 24B2091
Processor: 10 cpus, 64bit, little endian, Apple M4

getwd: /Users/leodev/p/v/fast2
vexe: /Users/leodev/p/v/v/v
vexe mtime: 2024-12-07 11:48:53

vroot: OK, value: /Users/leodev/p/v/v
VMODULES: OK, value: /Users/leodev/.vmodules
VTMP: OK, value: /tmp/v_501

Git version: git version 2.47.0
Git vroot status: weekly.2024.49-33-ge32e9f70
.git/config present: true

CC version: Apple clang version 16.0.0 (clang-1600.0.26.4)
emcc version: N/A
thirdparty/tcc status: thirdparty-macos-arm64 713692d4
```

**What did you do?**
`./v -g -o vdbg cmd/v && ./vdbg repro3.v`

```v
import time

fn test() ?i64 {
	return bar()
}

fn bar() ?time.Duration {
	return time.Duration(0)
}

fn main() {
	test()
}
```

**What did you expect to see?**

Successful compilation

**What did you see instead?**

```
repro3.v:4:9: error: cannot use `?time.Duration` as type `?i64` in return argument
    2 | 
    3 | fn test() ?i64 {
    4 |     return bar()
      |            ~~~~~
    5 | }
    6 |
```

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU0MzZiZWQyZWY0Y2JjYzQ2ZjdhMWYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.HcFNcXGbeWyzNWmFOjTU-EIrnUaFwmi9bBITRASapCg">Huly&reg;: <b>V_0.6-21525</b></a></sub>

**Comment by jorgeluismireles** [comment]
Seems any alias does not work. A workaround inside `test()` method:
```v
type Int = int

fn test() ?int {
	b := bar()?
	return int(b)
}

fn bar() ?Int {
	return Int(0)
}

fn main() {
	test()
}
```
