### ISSUE TITLE
assert stopped working in non-test code

### ISSUE THREAD

**Issue by lobotony** [vlang/v#2308]
**V version:** V 0.1.21 336e82d
**OS:** MacOS 10.15

**What did you do?**

	fn testing(v int) bool {
		assert v < 3
		return true
	}

	fn main() {
		println(testing(1))
	}

**What did you expect to see?**
successful compilation
 
**What did you see instead?**
error: non-void function 'main__testing' should return a value [-Wreturn-type]
  return;

**Comment by medvednikov** [comment]
Fixed.
