### ISSUE TITLE
array of arrays C error after `insert` method array of arrays.

### ISSUE THREAD

**Issue by jorgeluismireles** [vlang/v#23099]
### Describe the bug

We have an array of arrays. With `insert_many` method aka operator `<<` we can insert 1) arrays or insert 2) array of arrays. But with `insert` method (insert at) we can insert 1) arrays but we cannot insert 2) arrays of arrays. Last attempt should be rejected by the compiler.

### Reproduction Steps

```v
fn main() {
	mut arr := [][]int{}
	arr << [1, 2]
	arr << [[3, 4], [5, 6]]
	arr.insert(arr.len, [7, 8]) // <- works as expected
	arr.insert(arr.len, [[9,10]]) // <- not rejected but C error
	println(arr)
}
```

### Expected Behavior

Prevent insert array of arrays in array of arrays.

### Current Behavior

Trying to insert integers `9` and `10` in previous code we got a C error:

```
Running code...
Can't run code. The server returned an error:
/tmp/v_60000/../../../../../../box/code.v:6: warning: implicit declaration of function 'array_insert_many'
/home/admin/v/thirdparty/tcc/lib/libgc.a: error: 'GC_noop1_ptr' defined twice
tcc: error: undefined symbol 'array_insert_many'
builder error: 
==================
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .
Exited with error status 1
Please try again.
```

### Additional Information/Context

Mentioned before at: https://github.com/vlang/v/issues/23090

### V version

V 0.4.8 11dc600

### Environment details (OS name and version, etc.)

https://play.vlang.io/p/f5a3471e1c

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU0Y2M5YWQyZWY0Y2JjYzQ2ZjgxODMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.Ng5LJr8o_UjQLkrMBU5jUVQ0t_0kVKXKn22AtY0HOlo">Huly&reg;: <b>V_0.6-21537</b></a></sub>
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
Already fixed by #23097
