### ISSUE TITLE
Struct which contains a member of the same type does not compile

### ISSUE THREAD

**Issue by scottywz** [vlang/v#231]
```
struct Item {
	other Item?
}
```

does not compile ("You just found a bug.")

**Comment by ntrel** [comment]
This is the same error as when a struct S contains a field of type S. For efficiency, I think `S?` should internally have S as a field, e.g.:
```rust
struct Optional<T>
{
  empty bool
  item T
}
```
Then no heap allocation is required. So your code should get an error message "struct Item contains recursive field `other`".

**Comment by M4SSD35TRUCT10N** [comment]
This compiles:
```
struct Item {
	other &Item
}
```

**Comment by Ivo-Balbaert** [comment]
struct Item {
	other Item
}
now gives a clear error message: 
cannot embed struct `Item` in itself (field `other`)

but:
struct Item {
	other &Item
}
compiles and can be used in code.
So I think this item can be closed.

**Comment by medvednikov** [comment]
Also this compiles now:

```
struct Item {
	other ?Item
}
```
