### ISSUE TITLE
cgen error, for pure V program, overloading `<` for structs, and calling `arrays.distinct` with an array of structs, that sorts them internally

### ISSUE THREAD

**Issue by spytheman** [vlang/v#23120]
**V doctor:**

```
V full version: V 0.4.8 dab25ca.43e27d2
OS: linux, Ubuntu 20.04.6 LTS
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i3-3225 CPU @ 3.30GHz

getwd: /space/v/oo
vexe: /space/v/oo/v
vexe mtime: 2024-12-10 11:52:21

vroot: OK, value: /space/v/oo
VMODULES: OK, value: /home/delian/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.46.0
Git vroot status: weekly.2024.50-3-g43e27d24
.git/config present: true

CC version: cc (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0
emcc version: N/A
thirdparty/tcc status: thirdparty-linux-amd64 0134e9b9
```

**What did you do?**
`./v -g -o vdbg cmd/v && ./vdbg /home/delian/code/misc/2024_12_10__13/cgen_error.v`

```v
import arrays
struct Abc { x int }
fn (s1 Abc) < (s2 Abc) bool { return s1.x < s2.x }
a := [Abc{123}, Abc{42}, Abc{999}, Abc{42}, Abc{123}]
dump(arrays.distinct(a))
```

**What did you expect to see?**

A compiled program

**What did you see instead?**

```
================== C compilation error (from tcc): ==============
cc: /tmp/v_1000/cgen_error.01JER6KR8W4G6C6194G79DHWTH.tmp.c:1623: warning: implicit declaration of function 'main__Abc__lt'
cc: /tmp/v_1000/cgen_error.01JER6KR8W4G6C6194G79DHWTH.tmp.c:1627: error: incompatible types for redefinition of 'main__Abc__lt'
=================================================================
(You can pass `-cg`, or `-show-c-output` as well, to print all the C error messages).
```

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU4MmJmYTFlMDYzMmRkMDhlMmFlYzQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.JJ37d9b26NOY7ptJWHBYhIFiJKKYMUhJItBVY1YcamI">Huly&reg;: <b>V_0.6-21557</b></a></sub>

**Comment by spytheman** [comment]
Note: `main__Abc__lt` is present in the C output, it is just not ordered correctly in the declarations:
```c
VV_LOCAL_SYMBOL  int compare_12871999398803438591_main__Abc(main__Abc* a, main__Abc* b) {
    if (main__Abc__lt(*a, *b)) return -1;
    else return 1;
}

VV_LOCAL_SYMBOL bool main__Abc__lt(main__Abc s1, main__Abc s2);
```

**Comment by pbzdok** [comment]
Thanks for opening this up. I had this issue as well!
