### ISSUE TITLE
Hello World in repl looking for gcc indead of msvc, fails on Windows

### ISSUE THREAD

**Issue by AllNamesRTaken** [vlang/v#2313]
**V version:  0.1.21 85c05b6** 
**OS: Windows 10** 

**What did you do?**
- Installed V.
- enter repl
- println('Hello, developers!')

**What did you expect to see?**
Hello Developers

 
**What did you see instead?**
'gcc' is not recognized as an internal or external command,
operable program or batch file.
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by changrui** [comment]
Install C compiler under Windows: https://github.com/vlang/v/wiki/Installing-a-C-compiler-on-Windows

**Comment by medvednikov** [comment]
No, this is a known issue. Will fix be fixed soon.

**Comment by AllNamesRTaken** [comment]
Same happens with a normal compile:
`
C:\Kod\v>v examples\hello_world.v
'gcc' is not recognized as an internal or external command,
operable program or batch file.
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
`

**Comment by medvednikov** [comment]
Fixed.
