### ISSUE TITLE
Comparator operators overloading on Aliases causes `fatal signal 11`

### ISSUE THREAD

**Issue by jorgeluismireles** [vlang/v#23201]
### Describe the bug

By a compiler message, we know is enough to overload only two comparators:

> cannot overload `!=`, `>`, `<=` and `>=` as they are auto generated from `==` and`<`.

Then we overload `==`and `<` for aliases and we got a `fatal signal 11` error.

### Reproduction Steps

```v
type Byte = u8

pub fn (b1 Byte) == (b2 Byte) bool {
	if b1 == b2 {
		return true
	}
	return false
}

pub fn (b1 Byte) < (b2 Byte) bool {
	if b1 < b2 { 
		return true
	}
	return false
}


fn main() {
	println('${Byte(255) > Byte(1)}')
}
```

### Expected Behavior

```
true
```

### Current Behavior

```
Caught fatal signal 11
```

### Additional Information/Context

Comparators are tricky, since `<` is not possible on complex numbers but only `==` and `!=` as far I recall.

### V version

V 0.4.8 41bb90c

### Environment details (OS name and version, etc.)

https://play.vlang.io/p/3296a2b9b3

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYyZTcwMGYxNDRmNTg1YWU0ZGY0NzEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.7za7A781kXbXD2ffOWXyRPgKEhywufuq39Gy7Wx-YSk">Huly&reg;: <b>V_0.6-21638</b></a></sub>

**Comment by spytheman** [comment]
```v
pub fn (b1 Byte) == (b2 Byte) bool {
	if b1 == b2 {
```
^ that is endless recursion and you get a segfault

**Comment by spytheman** [comment]
try this instead:
```v
pub fn (b1 Byte) == (b2 Byte) bool {
	if u8(b1) == u8(b2) {
```

**Comment by spytheman** [comment]
i.e.:
```v
type Byte = u8

pub fn (b1 Byte) == (b2 Byte) bool {
    if u8(b1) == u8(b2) {
        return true
    }
    return false
}

pub fn (b1 Byte) < (b2 Byte) bool {
    if u8(b1) < u8(b2) {
        return true
    }
    return false
}

fn main() {
    println('${Byte(255) > Byte(1)}')
}
```

prints `true`
