### ISSUE TITLE
JSON decode function return error on null value

### ISSUE THREAD

**Issue by esquerbatua** [vlang/v#23207]
### Describe the bug

module json take as invalid type a field with null value, instead to take the default type value

### Reproduction Steps

```v
import json

struct  Test {
  test string
}

println(json.decode(Test, "{\"test\": null}"))
```

### Expected Behavior

prints: `"{test: ""}"`

### Current Behavior

`failed propagation with error: type mismatch for field 'test', expecting `string` type, got: null`

### Possible Solution

Make the validation omit or set the default type value if value it's null

### V version

V 0.4.8 939d243

### Environment details (OS name and version, etc.)

V full version: V 0.4.8 5f413f4.939d243
OS: linux, Ubuntu 24.04.1 LTS
Processor: 16 cpus, 64bit, little endian, AMD Ryzen 7 7840HS w/ Radeon 780M Graphics

vexe: /home/esquerbatua/git/v/v
vexe mtime: 2024-12-19 17:43:30

vroot: OK, value: /home/esquerbatua/git/v
VMODULES: OK, value: /home/esquerbatua/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.43.0
Git vroot status: weekly.2024.43-466-g939d243b
.git/config present: true

CC version: cc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
emcc version: N/A
thirdparty/tcc status: thirdparty-linux-amd64 0134e9b9
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by jorgeluismireles** [comment]
You could use an option:

```v
import json

struct Test {
	test ?string
}

println(json.decode(Test, '{"test": null}') or {
	panic('${err}')
})
```

```
Test{
    test: Option(none)
}


```

**Comment by felipensp** [comment]
Yes, null is not a string type. So, it should be a ?string for strictness. What do you think @medvednikov @spytheman ?

**Comment by esquerbatua** [comment]
> Yes, null is not a string type. So, it should be a ?string for strictness. What do you think @medvednikov @spytheman ?

the problem it's to handle the optional in all of the sites, maybe add a new attribute to allow a null value?
