### ISSUE TITLE
lambda bug

### ISSUE THREAD

**Issue by lee157953** [vlang/v#23221]
### Describe the bug

```
module main

fn main() {
	my := MyError{
		path: 'err msg'
	}
	p := my.to[string](|m| m.path)
	//p := my.to_str(|m| m.path) //ok
	println(p)
}

struct MyError {
pub:
	path string
}

fn (e &MyError) msg() string {
	return e.path
}

fn (e &MyError) code() int {
	return 1
}

fn (e &MyError) to[T](func fn (MyError) T) T {
	return func(e)
}

fn (e &MyError) to_str(func fn (MyError) string) string {
	return func(e)
}

```

### Reproduction Steps

compile

### Expected Behavior

compile successfully

### Current Behavior

compile failure

### V version

last

### Environment details (OS name and version, etc.)

ubuntu 24.04
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by felipensp** [comment]
`p := my.to(|m| m.path)` also gives checker panic when inferring generic type.
