### ISSUE TITLE
issue with array initialization using index

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#23225]
### Discussed in https://github.com/vlang/v/discussions/23224

<div type='discussions-op-text'>

<sup>Originally posted by **Lord-Vlad** December 20, 2024</sup>
I just started working with V, and while experimenting with arrays I stumbled upon the following.
When you initialize an `i32` array, you can't use index directly, you have to cast to `i32`.
Aren't `int` and `i32` the same thing?
This also applies to unsigned numbers, although I suspect it's due to the lack of promotion? Floating point numbers do work.

```v
array := []i32{len: 3, init: index}

error: expected `i32`, not `int`
```</div>
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by JalonSolov** [comment]
The bug is that `index` should always be the correct type to init the array, not a hard-coded `int`.

**Comment by spytheman** [comment]
That is wrong, consider `[]u8{len: 1_000_000}` - the index should be an int, to be able to represent the indexes of all elements, it can not be `u8`, since that allows only 256 distinct values.
