### ISSUE TITLE
C error (fixed arrays)

### ISSUE THREAD

**Issue by Eliyaan** [vlang/v#23277]
### Describe the bug

The code produces a c error from a pure V code.

### Reproduction Steps

Using `v run` :

```v
fn main() {
}

fn  get_chunkmap_at_coords(mapp []Chunk) [chunk_size][chunk_size]u64 {
                                return mapp[0].id_map
}

const chunk_size = 100

struct Chunk {
        id_map [chunk_size][chunk_size]u64 // [x][y] x++=east y++=south
}
```

### Expected Behavior

To not have a C error

### Current Behavior

```
❯ v run .
================== C compilation error (from tcc): ==============
cc: /tmp/v_1000/notOnlyNots.01JG1XQ3YHDDSTVPJGA5GBTEVT.tmp.c:1047: error: ';' expected (got "Array_fixed_u64_0")
=================================================================
(You can pass `-cg`, or `-show-c-output` as well, to print all the C error messages).
builder error:
==================
C error found. It should never happen, when compiling pure V code.
```

### V version

V full version: V 0.4.9 6ac1d08.f8c9edd

### Environment details (OS name and version, etc.)

OS: linux, "Void Linux"

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZkODk0NmYxNDRmNTg1YWU1MGVmOWUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.0wkKH10Qx6WI2VihGKfDqQTChBFjKsaFUWINkyMhKcQ">Huly&reg;: <b>V_0.6-21711</b></a></sub>

**Comment by felipensp** [comment]
Moving your const declaration makes it works.

```v
fn main() {
}
const chunk_size = 100

fn  get_chunkmap_at_coords(mapp []Chunk) [chunk_size][chunk_size]u64 {
                                return mapp[0].id_map
}

struct Chunk {
        id_map [chunk_size][chunk_size]u64 // [x][y] x++=east y++=south
}
```
