### ISSUE TITLE
Regression: Parameters of functions defined in global scope

### ISSUE THREAD

**Issue by avitkauskas** [vlang/v#2328]
**V version:** V 0.1.21 b1806b5
**OS:** Mac OS

**What did you do?**
```v
fn ident(a string) string {
    return a
}

a := 'abc'
```
 
**What did you see instead?**
```
test3.v:5:1: redefinition of `a`
    4|

    5| a := 'abc'

       ^
```

P.S. Also note there are extra new lines in error output.

**Comment by gslicer** [comment]
There should be no global scope, your example shuld reside in module 'main'

**Comment by avitkauskas** [comment]
No @gslicer, V can be run without the `main()` function as a script. Compiler automatically treats all the "global" code as beeing in `main()` function.

**Comment by gslicer** [comment]
But @avitkauskas, this is exactly what I stated, if no `fn main() { ... }` is defined (somewhere) in a source file, mostly in a single .v file, the scope is always module main - therefore there is no "global" scope, if you put something in global scope intentionally (outside main-function) you will get an error at compile time saying "unreachable code"

**Comment by kstarzyk** [comment]
Based on above comments: if there is no `main` function inside file then all top-level declarations/statements **should** be treated as if they were inside `main`.

If we change snippet to:
```v
fn ident(a string) string {
    return a
}

c := 'abc' # no more name conflict
```
Then program will compile without any warning, however

```v
fn ident(a string) string {
    return a
}
fn main() {
  c := 'abc'
}
```
results in warning `c declared and not used`.

`Compiler automatically treats all the "global" code as being in main() function.` is not necessary true, but as far as I'm concerned is expected.

**Comment by Ivo-Balbaert** [comment]
The program:

fn ident(a string) string {
    return a
}

a := 'abc' # no more name conflict
println(a)  // => abc

now runs without problem on Windows 10 and Linux (V 0.1.27 33a9822)
