### ISSUE TITLE
Reopen bug: net.http: add support '=' in cookie values #23257

### ISSUE THREAD

**Issue by sredrv** [vlang/v#23297]
### Describe the bug

I tested your latest commit to address the issues: [23220](https://github.com/vlang/v/issues/23220) and [23257](https://github.com/vlang/v/issues/23257).

The commit, FAILED to address the issue, originally raised:
The parsed value of the base64 encoded cookie, is expected to retain the string '==' at the end.
But, it is still missing/eaten away.

### Reproduction Steps

You may use the following test, to address the bug

```V
fn test_base64_cookie_patch() {
	mut h := http.new_header()
	h.add(.cookie, 'enctoken=Ln0kBnAaAyYFQ8lH7d5J8Y5w1/iyDRpj6d0nBLTbBUMbtEyPD32rPvpApsvxhLJWlkHuHT3KYL0g/xNBxC9od5tMFAgurLxKdRd5lZ6Pd7W+SllkbsXmUA==; path=/; secure; SameSite=None')
	s := http.read_cookies(h, 'enctoken')
	assert s[0].name == 'enctoken'
	assert s[0].value == 'Ln0kBnAaAyYFQ8lH7d5J8Y5w1/iyDRpj6d0nBLTbBUMbtEyPD32rPvpApsvxhLJWlkHuHT3KYL0g/xNBxC9od5tMFAgurLxKdRd5lZ6Pd7W+SllkbsXmUA=='
}
```

### Expected Behavior

The parsed value of the base64 encoded cookie, is expected to retain the string '==' at the end.

### Current Behavior

It is still missing the '==' string at the end.

### Possible Solution

The following patch,  would help FIX the issue.

```V
diff --git a/vlib/net/http/cookie.v b/vlib/net/http/cookie.v
index aff4c75b4..9b171b442 100644
--- a/vlib/net/http/cookie.v
+++ b/vlib/net/http/cookie.v
@@ -72,7 +72,7 @@ pub fn read_cookies(h Header, filter string) []&Cookie {
                        if part.contains('=') {
                                val_parts := part.split('=')
                                name = val_parts[0]
-                               val = val_parts[1]
+                               val = val_parts[1..].join('=')
                        }
                        if !is_cookie_name_valid(name) {
                                continue
```

### V version

V 0.4.9 b487986

### Environment details (OS name and version, etc.)

Linux, Kernel 6.6.59

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcwMWUwOWYxNDRmNTg1YWU1MTM4ZTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.yaO5HqLik19NCPfOKeZR9aoxmNyW06xgLqE9jz-3vyc">Huly&reg;: <b>V_0.6-21729</b></a></sub>

**Comment by Delta456** [comment]
Can you make a PR with this patch?

**Comment by JalonSolov** [comment]
I don't think this is the correct "fix".  It should take everything up to the next `;`, rather than joining `=`.

**Comment by sredrv** [comment]
The cookie is already parsed with ';' as a delimiter.
While further parsing the cookie , into key=value pair, the code uses  .split('='), which causes the extra '==', at the end to be an array of empty values. So, just use .join('=') would restore the desired value.
Alternatively, do not use .split('=') for parsing. Go with index('=').

**Comment by JalonSolov** [comment]
`split_once('=')` would probably be best.  It will split key=value on the first =, but won't touch the rest.

**Comment by sredrv** [comment]
> Can you make a PR with this patch?

In a couple of weeks time, I will get more experienced in using V. 
I will certainly contribute PRs and possibly a few new packages, that I am working on now.
