### ISSUE TITLE
tcc errors

### ISSUE THREAD

**Issue by bogen85** [vlang/v#2329]
**V version:** 

V 0.1.21 b1806b5

**OS:** 

Linux 5.3.5-arch1-1-ARCH #1 SMP PREEMPT 2019 x86_64 GNU/Linux

**What did you do?**

 v up

**What did you expect to see?**

v to be updated.
 
**What did you see instead?**
`
Updating V...
From https://github.com/vlang/v
 * branch            master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
make: Entering directory '/home/dwight/scratch/v/v'
rm -rf vc/
git clone --depth 1 --quiet https://github.com/vlang/vc
rm -rf /var/tmp/tcc/
git clone --depth 1 --quiet https://github.com/vmisc/tccbin /var/tmp/tcc
cc -std=gnu11 -w -o v vc/v.c -lm
Self rebuild (b1806b5 => 61af044)
tcc: error: file 'crt1.o' not found
tcc: error: file 'crti.o' not found
tcc: error: file 'crtn.o' not found
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
make: *** [Makefile:26: all] Error 1
make: Leaving directory '/home/dwight/scratch/v/v'
`

**Background**

Over the past day I've updated several times.
Normally I got some tcc errors after I went to use after an update.
Doing an `rm -rf /var/tmp/tcc/` after the issues would allow me to use v again.
Now (I've tried it several times), it won't update.

I understand this may be a duplicate, but I could not find this specific tcc error here.

I already had tcc installed on my system and was already using it. I removed it to see if these errors would go away, but they did not. (I've been using v less than 24 hours).

**Comment by spytheman** [comment]
For a temporary workaround, try:
```
export VFLAGS='-cc /your/working/bin/tcc'
```
Please, do tell the result of `locate crt1.o` (the path is important, so that we can build a tcc that works on most distros).

**Comment by spytheman** [comment]
Also, thank you for the bug report.

**Comment by bogen85** [comment]
yeah, well, that update works (with the export)

Updating V...
From https://github.com/vlang/v
 branch            master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
make: Entering directory '/home/dwight/scratch/v/v'
rm -rf vc/
git clone --depth 1 --quiet https://github.com/vlang/vc
rm -rf /var/tmp/tcc/
git clone --depth 1 --quiet https://github.com/vmisc/tccbin /var/tmp/tcc
cc -std=gnu11 -w -o v vc/v.c -lm
Self rebuild (b1806b5 => 61af044)
rm -rf vc/
V has been successfully built
make: Leaving directory '/home/dwight/scratch/v/v'


however, when I go to use it, now I get:

v/vlib/builtin/array.v:183:13: ->cap is immutable
  182| 		if arr.cap == 0 {

  183| 			arr.data = calloc(cap * arr.element_size)

             			   ^
  184| 		}

  185| 		else {


As far as my tcc:

`$ pacman -Qs tcc
local/tcc 0.9.27-3
    Tiny C Compiler
`

and location of crt1.o

`/usr/lib/Mcrt1.o
/usr/lib/Scrt1.o
/usr/lib/crt1.o
/usr/lib/gcrt1.o
/usr/lib/grcrt1.o
/usr/lib/rcrt1.o
/usr/lib32/Mcrt1.o
/usr/lib32/Scrt1.o
/usr/lib32/crt1.o
/usr/lib32/gcrt1.o
/usr/lib32/grcrt1.o
/usr/lib32/rcrt1.o
`

**Comment by bogen85** [comment]
If I export VFLAGS='-cc clang' then I get past that issue, but now I have other issues (array code that was working before is not working now), I'll see if there is another bug report for that.

**Comment by cloutiy** [comment]
Just to confirm, I also get similar issue on arch linux.

The output of running "make":
```
rm -rf vc/
git clone --depth 1 --quiet https://github.com/vlang/vc
rm -rf /var/tmp/tcc/
git clone --depth 1 --quiet https://github.com/vmisc/tccbin /var/tmp/tcc
cc -std=gnu11 -w -o v vc/v.c -lm
Self rebuild (b1806b5 => 61af044)
tcc: error: file 'crt1.o' not found
tcc: error: file 'crti.o' not found
tcc: error: file 'crtn.o' not found
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
make: *** [Makefile:26: all] Error 1
```

**Comment by damontic** [comment]
As this was dependant on a pull request in https://github.com/vmisc/tccbin that was merged 40 minutes ago, it is not happening anymore in my Arch Linux machine. Please confirm @bogen85 @cloutiy

**Comment by cloutiy** [comment]
@damontic All seems fine for me now, thanks!

**Comment by medvednikov** [comment]
Huge thanks to @spytheman for fixing it! What's your `time v compiler`?

For me it's 0.25s :)

**Comment by bogen85** [comment]
@damontic it is fixed for me as well. Thanks!

**Comment by bogen85** [comment]
@medvednikov where is this supposed to be run?
V error: compiler doesn't exist!

real	0m0.018s
user	0m0.008s
sys	0m0.011s

**Comment by medvednikov** [comment]
@bogen85 `v up`

**Comment by bogen85** [comment]
@medvednikov alright... I'm in the directory v is cloned in...

$ v up
Updating V...
From https://github.com/vlang/v
  branch            master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
make: Entering directory '/home/dwight/scratch/v/v'
rm -rf vc/
git clone --depth 1 --quiet https://github.com/vlang/vc
rm -rf /var/tmp/tcc/
git clone --depth 1 --quiet https://github.com/vlang/tccbin /var/tmp/tcc
cc -std=gnu11 -w -o v vc/v.c -lm
rm -rf vc/
V has been successfully built
make: Leaving directory '/home/dwight/scratch/v/v'

$ time v compiler
V error: compiler doesn't exist!

real	0m0.020s
user	0m0.013s
sys	0m0.007s
``

**Comment by medvednikov** [comment]
@bogen85 the command changed:

`v v.v` :)

**Comment by medvednikov** [comment]
I need to update the docs, thanks

**Comment by bogen85** [comment]
@medvednikov 
no problem

$ time v v.v

real	0m0.639s
user	0m0.465s
sys	0m0.137s
