### ISSUE TITLE
found a bug.

### ISSUE THREAD

**Issue by xywf221** [vlang/v#233]
A function with the same name will now prompt this to be a bug, just like
```
fn t1() { 
} 

fn t1(){
}

```

**Comment by xywf221** [comment]
I found a similar bug.
```
struct User {
	id int 
        id int
} 
```
It will also prompt for bugs when it runs.

**Comment by xywf221** [comment]
```
const (
	p = 1
	p = 2
)
fn main() {
	println(p)
}
```
constants should be non-modifiable.

**Comment by xywf221** [comment]
@medvednikov  I'm not so sure V can be released in June.

**Comment by ntrel** [comment]
&gt; I'm not so sure V can be released in June.

These bugs are not show stoppers, they are just invalid code that is currently accepted. Making V source available will help fix bugs. Making a general purpose language is an ambitious undertaking, Alex has done impressive work alone.

**Comment by xywf221** [comment]
> > I'm not so sure V can be released in June.
> 
> These bugs are not show stoppers, they are just invalid code that is currently accepted. Making V source available will help fix bugs. Making a general purpose language is an ambitious undertaking, Alex has done impressive work alone.

I've only been watching this project for months, and I expect him to release beta version.

**Comment by medvednikov** [comment]
All of these have been fixed.

Like @ntrel noted, these are minor bugs. It took me a couple of minutes and a couple of lines of code to fix them.

Things like this will not delay the release of the source this month.

The language is small and simple, that's why I'm confident that 1.0 will happen this year.
