### ISSUE TITLE
String concatenation in maps

### ISSUE THREAD

**Issue by Larpon** [vlang/v#2341]
**V version:** 83b18af6
**OS:** Linux, Kubuntu 18.04

**What did you do?**
I ran this code in my `fn main()`:
```
m := {
        'data': os.executable()+'${os.path_separator}data'
}
```

**What did you expect to see?**
compilation success
 
**What did you see instead?**
I got a compile error:
```
string_add( os__executable ( ) ,
start_tmp() already started. cur_line=""
```

This workaround works:
```
data_dir := '${os.path_separator}data'
m := {
        'data': os.executable()+data_dir
}
```

**Comment by ka-weihe** [comment]
Works in V 0.1.26 50a8373.71a92eb.
