### ISSUE TITLE
Official Icon assets

### ISSUE THREAD

**Issue by KingDarBoja** [vlang/v#2343]
Hi there, just wanted to know if there is any doc or asssets folder to look for the official icon on `svg` format.

I would really appreciate it in order to properly update the icon being used at `vscode-icon` extension (As seen at this [PR](https://github.com/vscode-icons/vscode-icons/pull/2268)).

Cheers! 🍰

**Comment by donnisnoni95** [comment]
https://github.com/vscode-icons/vscode-icons/pull/2268#issuecomment-541788420

**Comment by KingDarBoja** [comment]
> @KingDarBoja [vscode-icons/vscode-icons#2268 (comment)](https://github.com/vscode-icons/vscode-icons/pull/2268#issuecomment-541788420)

I managed to see you message on my email before being deleted (not sure why it was deleted). I really appreciate the source file provided at [your repo](https://github.com/donnisnoni95/v-logo).

Thank you 🍰

**Comment by donnisnoni95** [comment]
Fixed by https://github.com/vscode-icons/vscode-icons/pull/2269

 👌 Sorry... late  🙂

**Comment by KingDarBoja** [comment]
@donnisnoni95 Thank you again for the source code, I will close this issue as it has been resolved.
