### ISSUE TITLE
How to get real/imag part of Complex number ?

### ISSUE THREAD

**Issue by GaraSharp** [vlang/v#2344]
current version (v 0.1.21) , complex structure is NOT pub,
cannot getting real/imag part of complex number.

so, I write such service for my code like as follow ;

```
//  real/imag part of complex number
fn real_(c cmplx.Complex) f64 {
  return c.abs()*math.cos(c.angle())
}
fn imag_(c cmplx.Complex) f64 {
  return c.abs()*math.sin(c.angle())
}
```

this does not returns exact values.
so, I tried to adds these code in v/vlib/math/complex/complex.v.

```
// Complex real/imag part value
pub fn (c Complex) real() f64 {
	return c.re
}
pub fn (c Complex) imag() f64 {
	return c.im
}
```
any idea ? thanks !

**Comment by medvednikov** [comment]
The fields are now public.
