### ISSUE TITLE
Pls give more info about installation in windows.

### ISSUE THREAD

**Issue by vinodvinu** [vlang/v#2345]
Hi,
I love this language at first sight. But I am not sure v is installed properly or not. I did as you said in the installation note. I found an exe file named "v" in my users folder. But I can't run any code(ex: println("hello')) in that cmd window.  Its saying that C:\Users\MyName\ is not recognized as blah blah.
So please give more clarity on this. And please tell me how to check if i installed it correctly. 
Note : I have added the v.exe path to my path. But it is not working. Do i miss something ?

**Comment by donnisnoni95** [comment]
Hai @vinodvinu You can ask for help on discord.... https://discord.gg/n7c74HM

**Comment by spytheman** [comment]
@vinodvinu Please, can you paste a screenshot, or an exact copy of the error message that you get?
Also can you run it with:
`v.exe --version` ?

**Comment by nsauzede** [comment]
I guess that maybe a full command line + exact error message could help to begin with ?
Do you use MSYS2 ? Cygwin ? mingw32 ? MSVC ?

**Comment by Larpon** [comment]
... or WSL?

**Comment by donnisnoni95** [comment]
We need the screenshot and PATH env var

**Comment by vinodvinu** [comment]
![v Cmd window](https://user-images.githubusercontent.com/8840907/66853658-71d1f580-ef9d-11e9-8820-b1e3211613f6.png)
And this is the screenshot of "v.exe" s command window.

**Comment by vinodvinu** [comment]
I am very much impressed about the speedy responses i got from here. Thank you all and sorry for delay in my reply.

**Comment by vinodvinu** [comment]
OMG, i think its my fault. After i edited the path to "C:\Users\Vinod Chandran\v" its worked. Now, i can see the version printed on cmd.
![v Ver](https://user-images.githubusercontent.com/8840907/66854471-0721b980-ef9f-11e9-9d25-e364b5af8e86.png)
This is the result.
But still i cant run code in v.exe's cmd window.

**Comment by Larpon** [comment]
Have you tried running just `v.exe` now that you got it to print the version? You should get a `>>>` prompt where you can write code. Or try writing your code in a `test.v` in same directory as the compiler and compule and run it with `v.exe run test.v`?

**Comment by vitalyster** [comment]
1) v.exe should be in `v` subdirectory, not in your user directory
2) looks like v currently have issues with spaces in working directory, move it to another directory without spaces for now

**Comment by vinodvinu** [comment]
> Have you tried running just `v.exe` now that you got it to print the version? You should get a `>>>` prompt where you can write code. Or try writing your code in a `test.v` in same directory as the compiler and compule and run it with `v.exe run test.v`?

Thanks a lot. Now everything works perfect. Now i want to learn more about V. Please tell me where to start.

**Comment by Larpon** [comment]
No problem.
I started here: https://vlang.io/docs
Good luck ✌

**Comment by vinodvinu** [comment]
Thanks. Bookamrked.
