### ISSUE TITLE
Error when building Vid

### ISSUE THREAD

**Issue by BenTearzz** [vlang/v#2352]
**V version:** 0.1.21 a5d61f6 
**OS:** Windows 10 - Build 18362 

**What did you do?**
```
git clone https://github.com/vlang/vid
cd vid
```

```
git clone --depth=1 https://github.com/ubawurinna/freetype-windows-binaries C:/v/thirdparty/freetype/
```

`v .`

**What did you expect to see?**
Some sort of message saying that Vid got builded successfully.
 
**What did you see instead?**
```
C:\vid>v .
warning: .\vid.v:5:7: the following imports were never used:
 * gx
C:\v\thirdparty\glfw/glfw3.dll: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```
If I check however, the file `glfw3.dll` does exist: 
![image](https://user-images.githubusercontent.com/24865450/66824290-4a9d0900-ef48-11e9-9596-d1cfe75a32ff.png)

Could the error have something to do with the forward slash in the path where it's trying to find `glfw`? `C:\v\thirdparty\glfw/glfw3.dll: file not recognized: File format not recognized`

**Comment by medvednikov** [comment]
try to replace it with a 32 bit glfw3.dll downloaded from their website

https://www.glfw.org

**Comment by Bowero** [comment]
Please refer to the [issue board of `vid`](https://github.com/vlang/vid/issues) for any more issues you have.
