### ISSUE TITLE
Error when building examples/tetris/tetris.v

### ISSUE THREAD

**Issue by b2nil** [vlang/v#2354]
**V version:  0.1.21 a5d61f6** 
**OS: windows 10 build 18362** 

**What did you do?**
After copying `thirdparty/glfw/glfw3.dll` to the `examples\tetris` directory,  I tried to run the `tetris.v` example with: 
```bash
$ v run tetris.v
```

**What did you expect to see?**
Successfully build the example and run as shown in `screenshot.png`.
 
**What did you see instead?**
```bash
PS C:\v\examples\tetris> v run tetris.v
C:\v\thirdparty\glad\glad.o not found, building it...
C:\v\examples\tetris\tetris.tmp.c:158:22: fatal error: ft2build.h: No such file or direc 
#include "ft2build.h"
                    ^
compilation terminated.
V error: C error. This should never happen. Please create a GitHub issue: https://githubv/issues/new/choose
```

**Comment by b2nil** [comment]
Looks like this is caused due to lack of `freetype`. 
After getting `freetype-windows-binaries` by `git clone --depth=1 https://github.com/ubawurinna/freetype-windows-binaries`, this example build successfully.

**Comment by sotoea** [comment]
I ran into this issue as well. After getting freetype-windows-binaries, I had to move the contents inside include to the root folder, so the freetype folder and theft2build.h... After doing this, if I do v .\tetris.v I run into this issue:

```PS D:\v\examples\tetris> v .\tetris.v
tetris.v:13:16: cannot import module "freetype" (no .v files in "D:\v\examples\tetris\freetype")
   12| import math

   13| import freetype

                      ^
   14|

   15| const (
```

Any ideas?
