### ISSUE TITLE
REPL Arrow key / previous command access

### ISSUE THREAD

**Issue by UNIcodeX** [vlang/v#2355]
`version: 0.1.21 69b4594`

Pressing the right or left arrow keys while using the REPL result in keycodes being echoed to the line.

`^[[A^[[B^[[C^[[D`

Expected behavior would be to navigate line entry history for re-execution and / or modification on press of `up` and `down` arrow keys, as well navigation between characters of a line for `left` and `right` arrow keys.

**Comment by UNIcodeX** [comment]
UPDATE:

This works fine in Windows Powershell, but not in shell on linux.

**Comment by Henrixounez** [comment]
Yes, the readline module will soon be implemented inside the REPL to allow using keys.

**Comment by UNIcodeX** [comment]
Good deal.

**Comment by UNIcodeX** [comment]
I just pulled down the latest commit and built and I'm still getting keycodes on arrow key usage.

:scratch head:

**Comment by medvednikov** [comment]
Sorry, it was temporarily reverted. Will be back today.

**Comment by medvednikov** [comment]
Issues on macOS.

**Comment by iambudi** [comment]
Still issue on mac
