### ISSUE TITLE
calling function inside string interpolation is executed twice

### ISSUE THREAD

**Issue by mvlootman** [vlang/v#2360]
**V version: V 0.1.21 69b4594** 
**OS: macOS Catalina** 

**What did you do?**
```

fn main(){
        s := 'a\nb\nc'
        println('org=> ${org(s)}') // <-- this will be called twice

        // outputs:
        //
        // enter org
        // enter org
        // org=> ["a", "b", "c"] 
}

fn org(s string) []string {
        println('enter org')
	mut res := []string
	if s.len == 0 {
		return res
	}
	mut start := 0
	for i := 0; i < s.len; i++ {
		last := i == s.len - 1
		if int(s[i]) == 10 || last {
			if last {
				i++
			}
			line := s.substr(start, i)
			res << line
			start = i + 1
		}
	}
        return res
}
```

**What did you expect to see?**
single execution of function `org`
```
enter org
org=> ["a", "b", "c"] 
```
 
**What did you see instead?**
```
enter org
enter org
org=> ["a", "b", "c"] 
```

**Comment by medvednikov** [comment]
Interesting, thanks.

By the way, it's better to use ```s[i] == `\n` ``` instead of `int(s[i]) == 10 `.

**Comment by medvednikov** [comment]
Good to know it works on macOS Catalina beta.

**Comment by mvlootman** [comment]
> Interesting, thanks.
> 
> By the way, it's better to use `` s[i] == `\n` `` instead of `int(s[i]) == 10 `.

Indeed, the whole function can be replaced with 
```
s.split('\n')
```
That is something I was testing to replace the current implementation of string.split_into_lines in vlib with.

**Comment by mvlootman** [comment]
@viniciuslrangel Good work!
