### ISSUE TITLE
error: 'V_COMMIT_HASH' undeclared

### ISSUE THREAD

**Issue by claudehohl** [vlang/v#2363]
**V version:** 0.1.21 69b4594
**OS:** `cat /etc/debian_version`
10.1

**What did you do?**
`./v -o v2 .`

**What did you expect to see?**
https://vlang.io/img/buildv.mp4
 
**What did you see instead?**
```~/v $ ./v -o v2 .
/home/user/v/v2.tmp.c:16140: error: 'V_COMMIT_HASH' undeclared
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by medvednikov** [comment]
Strange.

Can you try `git pull && make`?

**Comment by claudehohl** [comment]
Sure. Well...

```
~/v $ git pull && make
Already up to date.
rm -rf vc/
git clone --depth 1 --quiet https://github.com/vlang/vc
rm -rf /var/tmp/tcc/
git clone --depth 1 --quiet https://github.com/vlang/tccbin /var/tmp/tcc
cc -std=gnu11 -w -o v vc/v.c -lm
rm -rf vc/
V has been successfully built
~/v $ ./v -o v2 .
/home/me/v/v2.tmp.c:17059: error: 'V_COMMIT_HASH' undeclared
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
~/v $

**Comment by joe-conigliaro** [comment]
@claudehohl This dosent work `v -o v .` you need to do `*v -o v v.v`

**Comment by claudehohl** [comment]
@joe-conigliaro that works.
`./v -o v3 . v.v`

But I did it exactly as in the video (https://vlang.io/img/buildv.mp4) before. If I append "v.v", it seems to work, but now I'm confused. What does the additional "v.v" mean?

**Comment by medvednikov** [comment]
The command changed, it's in the readme.

The video is 6 months old.

**Comment by medvednikov** [comment]
Will do.
