### ISSUE TITLE
A minor parsing bug

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#2366]
```
a := u64(u64(1)<<64(3))
```

```
 expected `)` but got `(`
```

**Comment by amalshaji** [comment]
Shouldn't it be u64(3) ?
`a := u64(u64(1)<<u64(3))`

**Comment by mvlootman** [comment]
Indeed that returns an expected 8.
```
a := u64(u64(1)<<u64(3))  // 8
```

**Comment by amalshaji** [comment]
Shouldn't the error message be focussing on `64(3)` instead of `(` and `)` ?

**Comment by mvlootman** [comment]
my bad. it should return a better error message.

**Comment by Danil-Lapirow** [comment]
Thats because we treat () as call only when we have function before
