### ISSUE TITLE
f32 or f64?

### ISSUE THREAD

**Issue by proyb6** [vlang/v#237]
Code taken from #83 
Would this show in f64?

```
fn main() {
	mut age := f64(20)
	println(age)
	age = f64(21)
	println(age)
}
```

Output:
```
20.000000
21.000000
```

**Comment by proyb6** [comment]
In addition:
```
	mut age := f64(1 << 32 - 1)
```

Output:
```
-2147483648.000000
```

**Comment by medvednikov** [comment]
`f64(1 << 32 - 1)` is broken because V doesn't handle literals' types correctly yet.

It sees two ints on both sides and decides that (1 << 32) is an int, which results in an overflow.

**Comment by proyb6** [comment]
True, will temporary using float values.
