### ISSUE TITLE
No output to stdout under Windows 7

### ISSUE THREAD

**Issue by sunnylcw** [vlang/v#2372]
**V version:** 0.1.21
**OS:** MSYS2 Windows 7 SP1

**What did you do?**
v run hello_world.v

**What did you expect to see?**
Hello, World!
 
**What did you see instead?**
No output to stdout

It can be fixed by commenting out `C._setmode(C._fileno(C.stdout), C._O_U8TEXT)` in builtin.v

Alex M said this was a Windows 7 problem

**Comment by vitalyster** [comment]
Actually it is msvcrt problem, you should take newer mingw which links to msvcr90 or later version

**Comment by vitalyster** [comment]
https://github.com/mstorsjo/llvm-mingw This build uses correct crt version

**Comment by cup** [comment]
https://github.com/vlang/v/issues/3052
