### ISSUE TITLE
'gcc' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Anabar** [vlang/v#2373]
**V version:** V 0.1.21 99e0771
**OS:** Microsoft Windows [Version 10.0.17134.950]

**What did you do?**
V:\Delo\V_lang\v>v
V 0.1.21 99e0771
Use Ctrl-C or `exit` to exit
>>> println('Hello, World!')

**What did you expect to see?**
Hello, World!
 
**What did you see instead?**
'gcc' is not recognized as an internal or external command,
operable program or batch file.
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by webfolderio** [comment]
Duplicate https://github.com/vlang/v/issues/2313

**Comment by Bowero** [comment]
This is indeed a duplicate. Please refer to that thread for help.
