### ISSUE TITLE
Keep map in defined order

### ISSUE THREAD

**Issue by chr-stoev** [vlang/v#2376]
Is it possible to get a `map` implementation where the order keys are defined in will be kept when you loop over them?

**What did you do?**
```
m := {
    'foo': 1
    'bar': 2
    'tar': 3
    'baz': 4
}

for key, val in m {
    println(key + ': ' + val.str())
}
```

**What happened?**
```
foo: 1
bar: 2
baz: 4
tar: 3
```

**What did you expect?**
```
foo: 1
bar: 2
tar: 3
baz: 4
```

**Comment by radare** [comment]
define "order". hashtables by itself dont have any order, they are optimized for accessing the keys not for iterating them. you may sort the keys before iterating them. or create a map that does that, but it is not the default/standard thing

**Comment by chr-stoev** [comment]
> define "order"

As I try to show with the example, the order should be the order I add the entries. If I add `tar` to the map before `baz` then I would expect to get `tar` before `baz` when I iterate over the map.

> hashtables by itself dont have any order, they are optimized for accessing the keys not for iterating them. you may sort the keys before iterating them. or create a map that does that, but it is not the default/standard thing

I know. That is why I am requesting an implementation that has that feature. E.g. look at arrays in PHP.

Also as far as I can tell, `map` in V is currently implemented as a tree structure, not a hash map. But I might be wrong

**Comment by medvednikov** [comment]
Indeed, they are trees right now.

A separate ordered map type will be available, like in C++.

**Comment by nedpals** [comment]
Maps are now ordered. Should we close this?

```
foo: 1
bar: 2
tar: 3
baz: 4
```

Playground: https://devbits.app/play/1Nmf2DTIPGzN

**Comment by radare** [comment]
Why’s that do we have unordered maps somewhere? Performance wise unordered maps are important in many situations

**Comment by ka-weihe** [comment]
@radare We do not have an unordered map, but the map is still a hashmap (O(1) get, set and delete). The map was changed to be ordered for the same reason [python dictionaries are now ordered](https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6). TLDR: it is faster and more memory efficent. But... this is only an implementation detail for now, no one should rely on the order of the map.

**Comment by radare** [comment]
Ok sgtm

**Comment by penguindark** [comment]
the test program worka as exepcted now.
