### ISSUE TITLE
Exporting function to library (dll/so)

### ISSUE THREAD

**Issue by webfolderio** [vlang/v#2379]
Hi,

How could i export V function to call it from C/C++

**Comment by UNIcodeX** [comment]
I would also love to know how to do this.

Also, if it weren't too difficult to add a compiler target for a Python library, that would be amazing! (see https://github.com/yglukhov/nimpy)

**Comment by UNIcodeX** [comment]
Tried to create a module using this

```v
// fibrec.v
module fibrec
pub fn fib(n int) int {
  if n <= 2 {
    return 1
  } else {
    return fib(n-1) + fib(n-2)
  }
}
```

Which seems to build when using the following command:
```bash
v -shared -prod fibrec.v
```

Then I tried to import it:
```python
from ctypes import *
libFibRec = CDLL("./fibrec.so")
print(libFibRec.fib(40))
```

Which gives error:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: ./fibrec.so: undefined symbol: fib
```

So it seems like the symbol name is getting mangled???

**N.B.** -- I know that V does not advertise CFFI interop from V to C / Python, but I'm playing with different things to see what I can already do with it.

When checking the library with `strings | grep fib`, it comes back with `fibrec__fib`, so maybe it's not mangling the name, but it still doesn't seem to be available for use.

**Comment by webfolderio** [comment]
i found a workaround solution. v exports [live functions](https://github.com/vlang/v/blob/master/vlib/compiler/gen_c.v#L78) on windows(msvc) platform.
v might use a new keyword specific to this use case.

**Comment by sdwfrost** [comment]
The name is mangled, but only as `module_function`. The following works for me on Ubuntu/WSL:

```python
print(libFibRec.fibrec__fib(40))
```

Without putting in a module, the function will be callable as `main__fib`.

**Comment by UNIcodeX** [comment]
@sdwfrost Your example worked for me as well.
