### ISSUE TITLE
I have error

### ISSUE THREAD

**Issue by kingofmidas** [vlang/v#2383]
**V version:** 0.1.21
**OS:** Windows

**What did you do?**install vid editor . But it crashed after "./vid" command

**What did you expect to see?**i dont know)

 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/38670030/66958035-0e64c800-f070-11e9-8fd0-211a8514f519.png)

**Comment by nedpals** [comment]
@kingofmidas please post your issue here: https://github.com/vlang/vid/issues

**Comment by Danil-Lapirow** [comment]
You are missing freetype. You can try something like [this link](https://github.com/ubawurinna/freetype-windows-binaries)

**Comment by Bowero** [comment]
`vid` has it's own repository where you can post [issues](https://github.com/vlang/vid/issues).
