### ISSUE TITLE
Was asked to create a GitHub issue

### ISSUE THREAD

**Issue by carefree0910** [vlang/v#2389]
**V version:** V 0.1.21 4932a32
**OS:** Windows

**What did you do?**

```bash
./v v.v
```

**What did you expect to see?**

IDK
 
**What did you see instead?** 

C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot open output file v.exe: Permission deni...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by medvednikov** [comment]
I know what it is. Will fix, thanks.

For now you can do

`./v -o v2.exe v.v`

**Comment by carefree0910** [comment]
Thanks for the quick reply!
