### ISSUE TITLE
single v file without main function  bug

### ISSUE THREAD

**Issue by lydiandy** [vlang/v#2393]
**V version:** 
V 0.1.21 2709344
**OS:** 
macos
**What did you do?**
my code:

```
println('hello world')
my_fn()

fn my_fn() {
	println('from my_fn')
}
```
when I change code like this,it compile sucessfully
```
fn my_fn() {
	println('from my_fn')
}

println('hello world')
my_fn()

```

**What did you expect to see?**

 it should compile sucessfully

**What did you see instead?**
error message :
main.v:2:7: unexpected token: `)`

**Comment by Danil-Lapirow** [comment]
We need to rethink passes in one-file project compilation @medvednikov

**Comment by Bowero** [comment]
V 0.1.21 c18578a

For me, this runs as expected.

**Comment by M4SSD35TRUCT10N** [comment]
On Windows 10 1809 I do get the same error (V 0.1.21 f7c00b8). Unexpected token ')'...

**Comment by gslicer** [comment]
can confirm not working:

```C:\Daten\CODE>v sprog.v
sprog.v:2:8: unexpected token: )
    1| println('hello world')
    2| my_fn()
              ^
    3|
    4| fn my_fn() {

C:\Daten\CODE>v -v
V 0.1.22 d57c0cf

C:\Daten\CODE>ver

Microsoft Windows [Version 6.1.7601]
```

**Comment by Delta456** [comment]
With 1.0.29

```
examples/hello_world.v:4:4: error: unexpected name `my_fn`, expecting `(`
    2 | my_fn()
    3 | 
    4 | fn my_fn() {
      |    ~~~~~
    5 |     println('from my_fn')
    6 | }
```

**Comment by Ivo-Balbaert** [comment]
This now (v 0.2.1) prints:
 error: function declarations in script mode should be before all script statements

which is clear enough.

So this is a question about a feature that is not present, it is not a bug. The issue label should be modified.
As the message says, a one file V program is a script, and in script mode, functions cannot be used before they are declared.

**Comment by medvednikov** [comment]
Thanks @Ivo-Balbaert, this can now be closed.
