### ISSUE TITLE
import as not working in repl

### ISSUE THREAD

**Issue by radare** [vlang/v#2394]
**V version:** V 0.1.21 2709344
**OS:** macOS 10.14

**What did you do?**

```
>>> import math as moth
.vrepl_temp.v:6:14: unexpected token: `as`
```

**What did you expect to see?**

the `as` keyword may work
 
**What did you see instead?**

an error. because this statement works fine in a .v file

**Comment by Delta456** [comment]
This doesn't seems to be documented.

**Comment by adlesh** [comment]
I didn't realize as was supported... I think it was supposed to be removed as being against the easy to read and maintain principle

**Comment by elimisteve** [comment]
Confirmed; as of the latest version (`V 0.1.23 0ebe86f`), this works in V files but not in the REPL.

**Comment by Ivo-Balbaert** [comment]
V 0.1.27 33a9822
Use Ctrl-C or `exit` to exit
>>> import math as moth
>>> moth.pi
3.141592653589793e+00

This now works on Windows 10 and Ubuntu 20. Can't test on mac OS. Can probably be closed?
