### ISSUE TITLE
redefinition of C

### ISSUE THREAD

**Issue by radare** [vlang/v#2395]
**V version:** V 0.1.21 2709344
**OS:** macOS 10.14

**What did you do?**

```
$ cat vrum.v
c := 3
$ v vrum.v
vrum.v:1:2: redefinition of `c`
    1| c := 3

        ^
$
```
**What did you expect to see?**

the program to compile
 
**What did you see instead?**

an error

**Comment by vitalyster** [comment]
Same issue, use` fn main() { ... }` for now

**Comment by Danil-Lapirow** [comment]
I think, that in first pass V registers variable `c` so while second pass V sees that we try to declare variable `c`.

**Comment by joe-conigliaro** [comment]
Yeah this will be fixed soon

**Comment by Beomi** [comment]
Same on me, waiting for fixed version :) 

### V version:V 0.1.21 f7c00b8
### OS: macOS Mojave 10.14.6(18G87) 

**What did you do?**

Wrote & run v file like below(Tutorial):

```v
name := 'Bob'
age := 20
large_number := i64(9999999999)
println(name)
println(age)
println(large_number)
```

**What did you expect to see?**

```v
Bob
20
9999999999
```
 
**What did you see instead?**

```v
06_variables.v:1:4: redefinition of `name`
    1| name := 'Bob'

          ^
    2| age := 20

    3| large_number := i64(9999999999)
```

**Comment by radare** [comment]
right now the error msg is different: (V 0.1.24 ed55778)
```
$ v run f.v
f.v:4:13: cannot use type `void` as type `string` in first argument to `println()`
    2| age := 20
    3| large_number := i64(9999999999)
    4| println(name)
                   ^
    5| println(age)
    6| println(large_number)
$
``

**Comment by Ivo-Balbaert** [comment]
Both cited examples now (V 0.1.27 33a9822) work fine on Windows 10 and Ubuntu 20.
