### ISSUE TITLE
Installing vid returns an unexpected error

### ISSUE THREAD

**Issue by kingofmidas** [vlang/v#2399]
**V version:** 0.1.21
**OS:** windows

**What did you do?**install vid

**What did you expect to see?**vid

 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/38670030/67044041-19812c00-f134-11e9-8b43-ac447fc8f801.png)

**Comment by mrtnpwn** [comment]
vid doesn't want to compile anymore in Windows iirc.
also, it should be `v .-g`, not `v -g`.

**Comment by mrtnpwn** [comment]
vid doesn't want to compile anymore in Windows iirc.
also, it should be `v . -g`, not `v -g`.

**Comment by Bowero** [comment]
Not only does `vid` have it's own repository where you can post [issues](https://github.com/vlang/vid/issues), this is also a [duplicate](https://github.com/vlang/v/issues/2383).
