### ISSUE TITLE
Cause my hardware?

### ISSUE THREAD

**Issue by kingofmidas** [vlang/v#2400]
**V version:** 0.1.21
**OS:** windows

**What did you do?**input "vid" command

**What did you expect to see?**vid ide

 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/38670030/67051991-79cc9980-f145-11e9-9d3e-1f3879cad5bc.png)

**Comment by netmute** [comment]
Hi @kingofmidas

This bug tracker is not a support forum. You can talk with us directly on the [V discord server](https://discord.gg/n7c74HM). Looking forward to see you there!

**Comment by Danil-Lapirow** [comment]
Vid issues should be placed [here](https://github.com/vlang/vid)
closing
