### ISSUE TITLE
variadic problem: only `struct`, value error.

### ISSUE THREAD

**Issue by changrui** [vlang/v#2401]
**V version:** 
**OS:** 
0.1.21
Windows 10

**What did you do?**
Test variadic:
```    struct Int {i int}
   a1:=Int{1}
   a2:=Int{2}
   varprint(a1,a2)

   fn varprint(a ...Int) {
      for aa in a {
         println('${aa.i}'}
      }
   }
```

**What did you expect to see?**
1
2

 
**What did you see instead?**
4265465
0

**Comment by changrui** [comment]
I want to write `varprint(i ...int)` and call `varprint(1,2,3,4,5)` but got: 4, 487632, 0,  4250702 with line feed.

**Comment by medvednikov** [comment]
@changrui works for me:

```
struct Int {
        num int
}

fn varprint(i ...int) {
        for a in i {
                println(a)
        }
}

fn varprint2(i ...Int) {
        for a in i {
                println(a.num)
        }
}


fn main() {
        varprint(1,2,3,4,5,6)
        println('=============')
        varprint2(Int{1},Int{2},Int{3})
}

1
2
3
4
5
6
=============
1
2
3

```
Must be a Windows issue. Do you use msvc or mingw?

**Comment by changrui** [comment]
> Must be a Windows issue. Do you use msvc or mingw?

I am using mingw64, and I'll test it again after 16:00pm.

**Comment by joe-conigliaro** [comment]
It could be something with the string interpolation?

**Comment by avitkauskas** [comment]
I tested it on V 0.1.21 368e8e8 (mac OS). It does demonstrate weird behavours. That's the results:

First, without the `main()` function:

```v
struct Int {
        i int
}

fn varprint(a ...Int) {
    for aa in a {
        println('${aa.i}')
    }
}

a1:=Int{1}
a2:=Int{2}
varprint(a1,a2)
```
Works as expected:
```
1
2
```

If you put main code before the function definition, it does not work:
```v
struct Int {
        i int
}

a1:=Int{1}
a2:=Int{2}
varprint(a1,a2)

fn varprint(a ...Int) {
    for aa in a {
        println('${aa.i}')
    }
}
```
Files without the `main()` are broken - many other issues were reported recently.
```
check()
next token = `a2`
<...skip...>
test.v:7:14: expected `)` but got `,`
    6| a2:=Int{2}
    7| varprint(a1,a2)
                    ^
    8|
    9| // fn main() {
```

Now with the `main()` function:
```v
struct Int {
        i int
}

fn varprint(a ...Int) {
    for aa in a {
        println('${aa.i}')
    }
}

fn main() {
    a1:=Int{1}
    a2:=Int{2}
    varprint(a1,a2)
}
```
Works as expected:
```
1
2
```

Now the weird part - putting `main()` before other function definition matters!
```v
struct Int {
        i int
}

fn main() {
    a1:=Int{1}
    a2:=Int{2}
    varprint(a1,a2)
}

fn varprint(a ...Int) {
    for aa in a {
        println('${aa.i}')
    }
}
```
Result:
```
0
2
```
`0` instead of `1`?

**Comment by joe-conigliaro** [comment]
I think I know whats going on :) thanks @avitkauskas

**Comment by joe-conigliaro** [comment]
@avitkauskas Ive fixed the issue, will push change very soon, hopefully this also fixes @changrui issue

**Comment by joe-conigliaro** [comment]
@avitkauskas & @changrui Would you please be able to test again with latest master?

**Comment by changrui** [comment]
OK. @joe-conigliaro

**Comment by changrui** [comment]
It's working fine after `v up`, thx.

**Comment by joe-conigliaro** [comment]
@changrui Thanks for confirming
