### ISSUE TITLE
Structures/JSON with keyword fields

### ISSUE THREAD

**Issue by blem14** [vlang/v#2403]
**V version:** `0.1.21 4932a32`
**OS:** Windows 10 Enterprise 64bit

**What did you do?**
I am trying to decode string into some structure, but the `type` field is causing error. 
I may have missed something, but I looked into documentation and code, but didn't found similar example.

Example code:
```
module main
import json
struct Error {
    message    string
    type    int
}
struct Message {
    message_type    string
    error    Error  [json:error]
}
fn main(){
    s := '{"error":{"message":"OK","type":0},"message_type":"error"}'
    m := json.decode(Message, s) or { panic(err) }
    println(m.message_type)
    println(m.error.message)
}
```
I tried `_type int [json:type]`, same effect.
How to handle such data?
Changing JSON is not a solution for me.

Also, when I rename the field without adding `[json:type]` or even remove it at all, the code prints empty string to console, meaning json for `error` field was not decoded. I tested reverse logic and message got encoded with `v_error` filled, so I made it `error Error [json:error]`, which worked, but that exception is not documented anywhere

**What did you expect to see?**
Compiled code and data decoded correctly.
 
**What did you see instead?**
Compilation error:
```
check()
next token = `int`
print_backtrace_skipping_top_frames is not implemented on this platform for now...

main.v:5:20: expected `name` but got `type`
    4|     message     string

    5|     type        int

                          ^
    6| }

    7| struct Message {
```
Whole structure skipped for `error` field.

**Comment by Danil-Lapirow** [comment]
You can't use `type` because it's a keyword. Your main example won't work in any case. But renaming using `type` must work. Need to change this behavior.

**Comment by Danil-Lapirow** [comment]
@blem14 You can use strings to escape keywords now.
```v
module main
import json
struct Error {
    message    string
    typ    int [json:'type']
}
struct Message {
    message_type    string
    error    Error  [json:error]
}
fn main(){
    s := '{"error":{"message":"OK","type":0},"message_type":"error"}'
    m := json.decode(Message, s) or { panic(err) }
    println(m.message_type)
    println(m.error.message)
}
```

**Comment by Danil-Lapirow** [comment]
Ill open a new issue about `v_error`
