### ISSUE TITLE
Incorrect flags cause V to think it's an internal C error

### ISSUE THREAD

**Issue by Trivaxy** [vlang/v#2406]
**V version:** 0.1.21-99e0771
**OS:** Windows 10

**What did you do?**
Added an intentionally incorrect flag directive to the top of my file, e.g:
```v
#flag -I
```
Which should fail because I did not specify a path.

**What did you expect to see?**
A proper error message where V recognizes that the problem isn't with its produced C code, but instead with the user's incorrect flag.
 
**What did you see instead?**
V fails with the following error: 
`gcc: error: missing path after '-I'`
`V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose`

V shouldn't complain that it should never happen, because it was gcc's and the user's fault, not a problem with the way V compiles to C code. A better error message should be put instead, e.g
`V error: C error. Incorrect flag "#flag -I"` etc.

**Comment by joe-conigliaro** [comment]
This has been implemented
