### ISSUE TITLE
Playground Error: V can't compile this program

### ISSUE THREAD

**Issue by metaprem** [vlang/v#241]
The following program should display errors but playground gives message:
"You just found a bug. V can't compile this program, but it should. Please create a GitHub issue."

`fn main() {
	a:=0
	b:=0
	a := vals()
	println(a)
	println(b)
	c:=0
	c := vals()
	println(c)
}

fn vals () int {
	return 3
}
`

Compiler error messages in Ubuntu 19.04

var/tmp/vlang0.0.10//bug-20190608.c:279:5: error: redefinition of 'a'
int a= vals ( ) ;
    ^
/var/tmp/vlang0.0.10//bug-20190608.c:275:5: note: previous definition is here
int a= 0 ;
    ^
/var/tmp/vlang0.0.10//bug-20190608.c:287:5: error: redefinition of 'c'
int c= vals ( ) ;
    ^
/var/tmp/vlang0.0.10//bug-20190608.c:285:5: note: previous definition is here
int c= 0 ;
    ^
2 errors generated.
V panic: clang error

**Comment by medvednikov** [comment]
Fixed: 

```
redefinition of `a`
```
