### ISSUE TITLE
../v/examples/news_fetcher.tmp.c:179:10: fatal error: 'openssl/ssl.h' file not found

### ISSUE THREAD

**Issue by KylerKopacz** [vlang/v#2411]
**V version:** 0.1.21 (6890034)
**OS:**
MacOS Catalina
**What did you do?**
tried to run the news_fetcher example in the git repo

**What did you expect to see?**
whatever the news fetcher does
 
**What did you see instead?**
.../v/examples/news_fetcher.tmp.c:179:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^~~~~~~~~~~~~~~
1 error generated.
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

<img width="909" alt="Screen Shot 2019-10-18 at 11 30 28 AM" src="https://user-images.githubusercontent.com/22360752/67107599-c3939f00-f19a-11e9-858f-87704f99c3be.png">

**Comment by medvednikov** [comment]
From readme:

> If you plan to use the http package, you also need to install OpenSSL on non-Windows systems.

> macOS:
> brew install openssl

**Comment by medvednikov** [comment]
I'll make V handle this and print this message if openssl is not installed.
