### ISSUE TITLE
vpm is down

### ISSUE THREAD

**Issue by popzxc** [vlang/v#2413]
I'm not sure if this should be reported here, but `vpm` site (at least by the link provided on the official site) is down:
![image](https://user-images.githubusercontent.com/12111581/67112525-1c395b00-f1e0-11e9-8747-119a8c68a252.png)

`v install` doesn't work either:

```sh
./v install sqlite
V error: Skipping module "sqlite", since https://vpm.best responded with 502 http status code. Please try again later.
```

**Comment by medvednikov** [comment]
Fixed, thanks.

**Comment by popzxc** [comment]
@medvednikov well, I guess it's related so I won't create a new issue:

Following sites (at which https://vlang.io/ has links to) are also down:
https://blog.vlang.io
https://blog.vlang.io/forum

**Comment by medvednikov** [comment]
I removed the links to them.

I guess you refer to "built in V"?

They will be back soon.

**Comment by popzxc** [comment]
Yep, I was talking about "built in V".

Sure, no problem, just wanted to expose the fact :)

**Comment by heycalmdown** [comment]
`vpm` has gone again
