### ISSUE TITLE
Can't create a struct with generic parameters

### ISSUE THREAD

**Issue by popzxc** [vlang/v#2414]
**V version:** V 0.1.21 6890034
**OS:** Linux Mint 19

**What did you do?**
Tried to create a struct with generic parameters as defined in [docs](https://vlang.io/docs#generics)

```v
struct Repo<T> {
mut:
    data string
}

fn main() {
}
```

and then run 

```sh
v example.v
```

**What did you expect to see?**
Compiled program
 
**What did you see instead?**
```sh
v example.v
check()
next token = `T`
collections.v:1:13: expected `{` but got `<`
    1| struct Repo<T> {

                   ^
    2| mut:

    3|  data string
```

**Comment by nedpals** [comment]
generics have been temporarily removed for now

**Comment by popzxc** [comment]
Is there any assumptions when will they be returned?

**Comment by Delta456** [comment]
This program works now

```v
struct Repo<T> {
mut:
    data string
}

fn main() {
}
```

Output:

```

```
