### ISSUE TITLE
`v` creates "a.out.tmp.c" and doesn't remove it if specified build target don't exist

### ISSUE THREAD

**Issue by popzxc** [vlang/v#2415]
**V version:** V 0.1.21 6890034
**OS:** Linux Mint 19

**What did you do?**
Tried to compile a non-existent target (discovered by entering a valid name with an accidental typo, so it's not a hypothetical problem).

```sh
v some_nonexistent_target
```

**What did you expect to see?**
Error and no files created
 
**What did you see instead?**
Error and "a.out.tmp.c" file created

**Comment by LorenzoPirro** [comment]
@popzxc retry pls :) i've tried on MacOSx and Manjaro, the output is only the error. It's been fixed it think

**Comment by popzxc** [comment]
Well, I've tried, but seems that master is currently broken `¯\_(ツ)_/¯`

```sh
vlib/compiler/token.v:263:41: `compiler.TokenKind.plus_assign` is unnecessary, use `.plus_assign`
  261| const (
  262| 	AssignTokens = [
  263| 		TokenKind.assign, TokenKind.plus_assign, TokenKind.minus_assign,
             		                                ^
  264| 		TokenKind.mult_assign, TokenKind.div_assign, TokenKind.xor_assign,
  265| 		TokenKind.mod_assign,
Makefile:25: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by Ivo-Balbaert** [comment]
Now ( ) this gives:

v some_nonexistent_target: unknown command
Run "v help" for usage.

v some_nonexistent_target.v
builder error: some_nonexistent_target.v doesn't exist

No temp.c file is created.
