### ISSUE TITLE
os.getenv returns type byte* instead of type string

### ISSUE THREAD

**Issue by b2nil** [vlang/v#2423]
**V version: v0.1.21 b51b885** 
**OS: windows 10** 

**What did you do?**
Tried to play with shell script using v, and wrote the following code:
```v
# demo.vsh
fn main() {
  println('[+] change directory to temp folder....') 
  chdir(getenv('TEMP'))
  //println(getenv('TEMP'))
}
```
Error occured when running it with the following command:
```
$ v run demo.vsh
```
**What did you expect to see?**
`os.getenv` returns the environment variable as type `string`, rather than type `byte*`.
 
**What did you see instead?**
`os.getenv` obviously returns `byte*` instead of `string` .
```bash
demo.vsh:6:23: cannot use type `byte*` as type `string` in first argument to `os.chdir()`
    5|   chdir(getenv('TEMP'))

                         ^
    6|   println(getenv('TEMP'))

    7|
```

**Comment by Ivo-Balbaert** [comment]
Running as a vsh script without importing os doesn't work, however this works:

import os

fn main() {
  println('[+] change directory to temp folder....') 
  os.chdir(os.getenv('TEMP'))
  println(os.getenv('TEMP'))  // => C:\Users\CVO\AppData\Local\Temp
}

on Windows 10 (V 0.1.27 33a9822)
The reported error now looks fixed. Candidate for closing?

**Comment by b2nil** [comment]
Hi @Ivo-Balbaert, 
Just checked this on the same machine, and it worked as expected.
And I'm closing it now.
