### ISSUE TITLE
Implicit field renaming is json

### ISSUE THREAD

**Issue by teggotic** [vlang/v#2424]
**V version:** b51b8858d65b3167e68f60dae30e076ec77fec8e
**OS:** fedora

**What did you do?**
```v
module main
import json
struct Error {
    message    string
}
struct Message {
    message_type    string
    error    Error
}
fn main(){
    s := '{"error":{"message":"OK"},"message_type":"error"}'
    m := json.decode(Message, s) or { panic(err) }
    println(m.message_type)
    println(m.error.message)
}
```

**What did you expect to see?**
```
error
OK
```
 
**What did you see instead?**
```
error

```

**Problem**
V somewhy uses `v_error` name for message.error field. If i add `[json:error]` then everything works fine
This problem is shown in https://github.com/vlang/v/issues/2403

**Comment by nedpals** [comment]
Closed. Fixed in the latest V version. See: https://devbits.app/play/CTGpUfGICBb5
