### ISSUE TITLE
Performance issues on Ubuntu

### ISSUE THREAD

**Issue by kostya** [vlang/v#2426]
**V version:** 
V 0.1.21 c18578a
**OS:** 
Ubuntu 18.04.3 LTS

i added V to benchmarks here: https://github.com/kostya/benchmarks, performance not quite good as expected. Also there is comparison in OSX, which much better: https://github.com/kostya/benchmarks/pull/183#issuecomment-543948266

**Comment by mvlootman** [comment]
I am currently testing this also on Ubuntu. Perhaps it uses the tcc compiler which would not produce the most efficient / optimized binary.

**Comment by mvlootman** [comment]
Local run:
```
Crystal
-143.5001666666568
5.96s, 63.4Mb
Go
-143.500167
5.78s, 59.1Mb
C
-143.500167
5.82s, 70.0Mb
Rust
-143.5001666666568
5.51s, 70.7Mb
Nim Gcc
-143.50017
5.75s, 72.5Mb
V
-143.500167
35.10s, 70.9Mb
```

When I change the compile option to use the gcc C compiler it runs much better!

```
Crystal
-143.5001666666568
6.32s, 63.4Mb
Go
-143.500167
5.80s, 59.6Mb
C
-143.500167
5.63s, 70.0Mb
Rust
-143.5001666666568
5.62s, 70.7Mb
Nim Gcc
-143.50017
5.86s, 72.5Mb
V
-143.500167
5.91s, 70.3Mb

```

build command:
```
v -cc gcc -prod -o matmul_v matmul.v
```

**Comment by gslicer** [comment]
I tried the bf.v using GCC in -prod mode on my old laptop:

slicer@ideapad ~/Code> time ./bf bench.b 
ZYXWVUTSRQPONMLKJIHGFEDCBA
3.50user 0.00system 0:03.51elapsed 99%CPU (0avgtext+0avgdata 1900maxresident)k
0inputs+0outputs (0major+88minor)pagefaults 0swaps

**Comment by nuald** [comment]
I've confirmed that both `-cc gcc` and `-cc clang` options produce the binaries showing better results. The aforementioned benchmarks will be updated soon. However, I'd recommend to update the FAQ to rephrase "For now V emits C and uses GCC/Clang for optimized production builds." to "For now V emits C and might use GCC/Clang (please see `-cc` flag) for optimized production builds."

**Comment by kostya** [comment]
using gcc and clang fixed it.
