### ISSUE TITLE
Struct example won't compile

### ISSUE THREAD

**Issue by QuentinWidlocher** [vlang/v#2427]
**V version:**  0.1.21 5977fc0
**OS:**  W10 64bits 

**What did you do?**
I tried to use structs and go an error, figured out that even the struct example in the doc throw the same error.

Here is the struct example :

```vlang
struct Point {
	x int
	y int
}

p := Point{
	x: 10
	y: 20
}
println(p.x)
```

**What did you expect to see?**
 The example should print 10
 
**What did you see instead?**
```vlang
Test2.v:6:2: redefinition of `p`
    5|

    6| p := Point{

        ^
    7|     x: 10

    8|     y: 20
```

---

I also tried to put the example in a `fn main()` and the error was different :

```vlang
Test2.v:13:2: unexpected token: `}`
   12|     println(p.x)

   13| }
```

**Comment by Delta456** [comment]
That's known, try to add `fn main()` which will fix this error

**Comment by QuentinWidlocher** [comment]
Thank you for your answer, unfortunately I already tried that as I said 😢 

>I also tried to put the example in a `fn main()` and the error was different :
>```vlang
>Test2.v:13:2: unexpected token: `}`
>  12|     println(p.x)
>
>   13| }
> ```

**Comment by Delta456** [comment]
Can you show your whole code?

**Comment by QuentinWidlocher** [comment]
Here it is :

**Comment by QuentinWidlocher** [comment]
Here it is :
```vlang
fn main() {
    struct Point {
        x int
        y int
    }

    p := Point{
        x: 10
        y: 20
    }

    println(p.x)
}
```

**Comment by Delta456** [comment]
Define your struct globally

**Comment by QuentinWidlocher** [comment]
Oooook sorry !
Since there are no globals in V, I thought structs had to be defined in a scope or a module.
Thanks a lot🙏

**Comment by medvednikov** [comment]
it'll actually be possible to define structs in functions, just not yet.
