### ISSUE TITLE
function parameters with a defaut value

### ISSUE THREAD

**Issue by r-k-o** [vlang/v#2430]
please think about default parameters hat allow for easy calls.

fn (v mut x) dummy(path string, x1 int = 100, y1 int = 200) foo {...}

calls like:

x.dummy("foo")
x.dummy("foo", 500)
x.dummy("foo", 500, 1000)

**Comment by Delta456** [comment]
This goes against the philosophy of V.

**Comment by Nicoco220983** [comment]
> This goes against the philosophy of V.

Why ?

It could also be the occasion to have function kwargs:

dummy("path", y1:300)

After all, there is already this kind of struct  initialiation in V:

s := MyStruct{ b: 6}

**Comment by r-k-o** [comment]
@Nicoco220983  @Delta456 
Nicco - that correct. it is not question of personal feeling, but rather of usability.

**Comment by r-k-o** [comment]
@medvednikov 
please think about it

**Comment by r-k-o** [comment]
@medvednikov have you got an opinion about that yet?

**Comment by thecodrr** [comment]
This has already been discussed here #453. 
Bottomline: default parameters won't be allowed in functions but I believe there are plans to include them in structs. Don't know for sure.

**Comment by medvednikov** [comment]
@r-k-o default struct values have been implemented, so they can be used instead.
