### ISSUE TITLE
variadic args bug

### ISSUE THREAD

**Issue by lydiandy** [vlang/v#2433]
**V version:** 
V 0.1.21 b733876

**OS:** 
macos
**What did you do?**
here is my sample code:
```
fn main() {
    my_fn(1,'abc','d','e','f','g')
}

fn my_fn(i int,s string,others ...string) {
    println(i)
    println(s)
    println(others)
}
```
another sample code,args is different
```
fn main() {
    my_fn('abc','d','e','f','g')
}

fn my_fn(s string,others ...string) {
    println(s)
    println(others)
}
```

**What did you expect to see?**
it should compile successfully
 
**What did you see instead?**
the first sample code reports:
main.v:2:12: unexpected token: `,`
    1| fn main() {

    2|     my_fn(1,'abc','d','e','f','g')

                  ^
    3| }

    4| 

the second sample code reports :
error: passing '_V_FnVargs_main__my_fn *' (aka 'struct _V_FnVargs_main__my_fn *') to parameter of incompatible type 'string' (aka 'struct ...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

Process finished with exit code 1

**Comment by lcddh** [comment]
fn my_fn(s string,others ...string) {
    println(s)
    for s in others{
        println(s)
    }
}
this work

**Comment by joe-conigliaro** [comment]
@lydiandy Thanks for reporting, Im fixing

**Comment by joe-conigliaro** [comment]
@lydiandy The unexpected token error has been fixed.
There is still a problem with printing variadic of type `string` So I will keep this issue open until I fix that also

**Comment by joe-conigliaro** [comment]
you can now print any vargs
