### ISSUE TITLE
How to make modules available?

### ISSUE THREAD

**Issue by jkleiser** [vlang/v#2434]
In the docs I read that "You can create modules anywhere", but how can I make my modules reachable from my main code? The example in the docs have modules in ~/code/modules, but when I try to compile my main code, the module I put in ~/code/modules is not found. It is also unclear to me whether modules should be compiled separately. I have also tried to put the modules folder more close to my main code, but to no avail.

**Comment by changrui** [comment]
hi, @jkleiser It's easy. put a mod to ./mod under your project and write your function as `pub`, and then call it in your main module as `import ( mod ), call as `mod.func(...)`.

**Comment by jkleiser** [comment]
Thanks! That works fine.

**Comment by improveourselves** [comment]
> hi, @jkleiser It's easy. put a mod to ./mod under your project and write your function as `pub`, and then call it in your main module as `import ( mod ), call as `mod.func(...)`.

Hello @changrui I have the same problem, but don't know what you mean by "mod". I've done as jkleiser did, and also built the module. The module is in my vprograms/mymodules folder, which I created to put my modules in. The code is in a v file I named myfirstmodule. I built that, and so I thought it should then be available for my test program, named "moduletest.v", to see. But still, it gives me the error, "cannot import module "myfirstmodule" (not found)". But I built it correctly according to the manual. I am unfamiliar with your "mod" suggestion, so if you could help, and explain that if it fits, then I would greatly appreciate your help.
