### ISSUE TITLE
V generates invalid C code

### ISSUE THREAD

**Issue by netmute** [vlang/v#2436]
**V version:** V 0.1.21 b733876
**OS:** macOS

**What did you do?**
```v
struct Demo { name string }
 
fn main(){
  a:= ['nemesis', 'nerida', 'atlas', 'ganesha']
  d:=Demo{name: "foo"}
  if d in a {
    println('boom')
  }
}
```

**What did you expect to see?**
A friendly compiler error that tells me I compared with `d` instead of `d.name` 😅
 
**What did you see instead?**
```
demo.tmp.c:4873:6: error: implicit declaration of function 'array_Demo_contains' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
 if (_IN(Demo, ( d ),  a ) ) {
     ^
demo.tmp.c:130:28: no...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen.
```

**Comment by gslicer** [comment]
A friendly compiler error ^^

**Comment by code2be** [comment]
Did you try to use `-g` flag ? you'd be getting more from the errors output of C compiling process, clarifying your mistake.

**Comment by kstarzyk** [comment]
**V version**: 0.1.24 526f12f
**OS**: macOS

Probably fixed, running this snippet:

 ```
../2436.v:6:13: bad element type: `Demo` in `[]string`
    4|   a:= ['nemesis', 'nerida', 'atlas', 'ganesha']
    5|   d:=Demo{name: "foo"}
    6|   if d in a {
                   ^
    7|     println('boom')
    8|   }
```

@netmute, seems like `friendly compiler error` now :)

**Comment by netmute** [comment]
@kstarzyk Thanks for the ping!

This is correctly catched by the compiler now.
