### ISSUE TITLE
Changing name v.v to something else breaks the compile

### ISSUE THREAD

**Issue by bakul** [vlang/v#2437]
**V version:** 
v 0.1.21 b733876
**OS:** 
all

**What did you do?**
$ cp v.v x.v
$ ./v x.v

**What did you expect to see?**
successful compile - i just changed the filename!
 
**What did you see instead?**
vlang/v/x.tmp.c:16713: error: 'V_COMMIT_HASH' undeclared

**Comment by medvednikov** [comment]
Well  V needs to know when it's compiling V, right now one of the conditions is the `v.v` file.
