### ISSUE TITLE
Handling optionals isn't being enforced

### ISSUE THREAD

**Issue by netmute** [vlang/v#2438]
**V version:** V 0.1.21 b733876
**OS:** macOS

**What did you do?**
```v
fn foo() ?bool {
  return error("nope")
}

fn main() {
  foo()
}
```
**What did you expect to see?**
The compiler forcing me to handle the error in `foo()` with `foo() or {}`.
 
**What did you see instead?**
Compiles and runs fine.

**Comment by LorenzoPirro** [comment]
It's been fixed some days ago. The result is:
```
t.v:7:1: unhandled option type: `?bool`
    5| fn main() {
    6|   foo()
```

**Comment by netmute** [comment]
👌
