### ISSUE TITLE
Wrong tcc is used for non x86, x86-64 targets

### ISSUE THREAD

**Issue by bakul** [vlang/v#2439]
**V version:** 
V 0.1.21 b733876

**OS:** 
Linux raspberrypi 4.19.79-v7l+

**What did you do?**
./v -o v2 v.v

**What did you expect to see?**
Successful compile
 
**What did you see instead?**
sh: 1: /var/tmp/tcc/bin/tcc: Exec format error

This an x86-64 binary. `apt install tcc` and then `cp -p /usr/bin/tcc /var/tmp/tcc/bin` fixes the problem. But this is a workaround.

**Comment by gslicer** [comment]
V might detect if tcc is already installed on a given environment

**Comment by medvednikov** [comment]
No, it needs the latest version built from source.

**Comment by medvednikov** [comment]
@bakul I'll make a 32 bit v_linux.zip

**Comment by bakul** [comment]
Temporarily it is worse as it downloads fresh tcc every time!

**Comment by lancethepants** [comment]
I've been following vlang development, and have been using the language on my embedded arm system (Netgear R7000 router).  Cloning and compiling vlang now results in my arm cpu trying to run x86_64 tcc code, which it obviously can't.  Using tcc by default seems like not a great idea, or at least it should detect when something not x86(_64) is being used, and don't attempt to use tcc.  I know there is switch to pick which compiler you want.

There is more to the linux world than x86!  Plus I use uclibc-ng, and I can't even compile tcc to work in my specialty system for some reason.  GCC and clang both work great however. (yes, run natively on my router).

**Comment by cstrouse** [comment]
I'm using a Samsung Chromebook Plus which is an ARMv8 machine and it downloaded the correct tcc and everything seems to work fine.

**Comment by medvednikov** [comment]
Fixed.
