### ISSUE TITLE
Issue using http.get() from http module

### ISSUE THREAD

**Issue by iambenkay** [vlang/v#2442]
**V version: 0.1.21 368e8e8** 
**OS: Ubuntu 18.04** 

**What did you do?**
I wrote a basic http client using **http.get()** to GET a particular page.

**What did you expect to see?**
The HTML source in the console output
 
**What did you see instead?**
error: include file 'openssl/ssl.h' not found

**Comment by netmute** [comment]
The http package depends on openssl on non-Windows systems.

macOS:
`brew install openssl`

Debian/Ubuntu:
`sudo apt install libssl-dev`

**Comment by iambenkay** [comment]
Thanks for the solution
