### ISSUE TITLE
Support tcc backend not only on Linux

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#2443]
I notice that a pretty small (2.5M) tcc-based version of V is recently placed on V's site. 
Since now V can only emit C code, the only way to achieve such a small version is using tcc. Will tcc be supported on other platforms (windows, mac, etc)?

**Comment by radare** [comment]
Its not even supported on all archs for linux

**Comment by gslicer** [comment]
there is a tcc for Windows - however tcc is only preliminary to native machine code compilation by V (soon)

**Comment by r-k-o** [comment]
it would be better to use the free "http://www.smorgasbordet.com/pellesc/"

**Comment by Delta456** [comment]
TCC backend supports all now.
