### ISSUE TITLE
Windows: Generics don't work

### ISSUE THREAD

**Issue by Delta456** [vlang/v#2446]
**V version:** 
8a31ee4

**OS:** 
Windows

**What did you do?**
```v
fn plus<T>(a T, b T) T {
    return a+b
}

fn main() {
    println(plus(10,11))
}
```

**What did you expect to see?**
Successful compilation with 21 as output
 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/28479139/67156949-bfa28100-f342-11e9-8bd3-7d74a78b840e.png)

**Comment by medvednikov** [comment]
yes, they are temporarily disabled on windows

**Comment by Delta456** [comment]
I think its good to make an issue because so that people don't make new issues unnecessary 😆

**Comment by Delta456** [comment]
Fixed https://github.com/vlang/v/commit/a52cb315cb757e578b23af4994ca47d909b7387f
