### ISSUE TITLE
Any reason why the older version has been deleted from vc example from 0.1.13

### ISSUE THREAD

**Issue by byteshiva** [vlang/v#2448]
**V version:** 
**OS:**  mxlinux

**What did you do?**
Simple download and install of https://github.com/vlang/vc/archive/v0.1.13.tar.gz

**What did you expect to see?**
installation should have been completed
 
**What did you see instead?**
Failed since the https://github.com/vlang/vc/archive/v0.1.13.tar.gz does not exists.  Any reason why 0.1.13 has been deleted from the archive listing.

noticed v and vc release are not always in sync, some releases are missing in vc, example from 0.1.13 downwards and above 0.1.20

**Comment by medvednikov** [comment]
VC repo doesn't use releases, all versions are available via git.
