### ISSUE TITLE
vweb example fails: explicit type arguments are not allowed; remove `<...>`

### ISSUE THREAD

**Issue by Bowero** [vlang/v#2449]
**V version:** V 0.1.21 8a31ee4
**OS:** Arch Linux 5.3.6-arch1-1-ARCH

**What did you do?**
I tried to run the `vweb` example.

**What did you expect to see?**
I expected the example to run.
 
**What did you see instead?**
The compilation resulted in a v panic: 

```v
test_app.v:16:10: explicit type arguments are not allowed; remove `<...>`
   15| fn main() {

   16| 	vweb.run<App>(Port)

             	  ^
   17| }

   18| 
```

**Comment by changrui** [comment]
oh, i see, generics function error.

**Comment by Bowero** [comment]
Not the first one today.

**Comment by medvednikov** [comment]
Fixed.
