### ISSUE TITLE
Generic return type is not recognized

### ISSUE THREAD

**Issue by avitkauskas** [vlang/v#2450]
**V version:** V 0.1.21 f7c00b8
**OS:** Mac OS

**What did you do?**
```v
fn plus<T>(a T, b int) T {
    return a + T(b)
}

fn main() {
    println(plus(1.0, 1))
}
```

**What did you expect to see?**
2.0
 
**What did you see instead?**
```
test2.v:3:1: expected type `f32`, but got `T`
    2|     return a + T(b)

    3| }

       ^
    4|

    5| fn main() {
```

**Comment by Asaf51** [comment]
Why wrap `b` with `T`? 
You can just do `return a + b`

**Comment by Danil-Lapirow** [comment]
1ac162635781af7069c6490d821d8b05aea87c5b works fine as expected
![image](https://user-images.githubusercontent.com/16068886/67675357-9a87c100-f987-11e9-9fa8-10e82d37ac2f.png)
