### ISSUE TITLE
How to push on arrays inside struct?

### ISSUE THREAD

**Issue by jkleiser** [vlang/v#2453]
When I try this
```
struct Bests {
mut:
  scores []int
  names []string
}

fn (b Bests) add(score int, name string) {
  b.scores << score
  b.names << name
}
```
then I get "`b` is immutable (can't <<)". What must I do to allow `<<` on these struct fields from within my function?

**Comment by medvednikov** [comment]
`b` has to be marked immutable:

`fn (b mut Bests) add(score int, name string) {`
