### ISSUE TITLE
Can't convert string to float (f32)

### ISSUE THREAD

**Issue by KeyWeeUsr** [vlang/v#2457]
**V version:** V 0.1.21 b51b885
**OS:** Linux Mint 19.2 Tina using ``Dockerfile`` from the repo

**What did you do?**

```v
>>> f32("0.5")
```

**What did you expect to see?**

```
0.500000
```

**What did you see instead?**

```
/opt/src/.vrepl_temp.tmp.c:4908: error: invalid aggregate type for register load
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

The same thing happens even with ``v run <file>.v`` and ``v <file>.v``.

**Comment by medvednikov** [comment]
Use `'0.5'.f32()`

**Comment by KeyWeeUsr** [comment]
Amazing! Thank you for your hard work with this language!
