### ISSUE TITLE
Assertion Eror when reading array of cstrings

### ISSUE THREAD

**Issue by JustinRyanH** [vlang/v#2458]
**V version:** 
V 0.1.21 333f0ab
**OS:**
Linux madness 5.0.0-31-generic #33-Ubuntu SMP Mon Sep 30 18:51:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 

**What did you do?**
Compile Following code

``` v
pub fn get_dropped_files() []string {
    mut result := []string
    mut count := 0
    data := C.GetDroppedFiles(&count)
    for i in 0 .. count {
        result << string(byteptr(data[i]))
    }   
    return result
}   
```

For Reference here is the Definition of `C.GetDroppedFiles` from `raylib.h`

``` c
char **GetDroppedFiles(int *count);
```

**did you expect to see?**

Syntax Error if invalid syntax, otherwise successful compilation
 
**What did you see instead?**
``` bash
v -gc core_2d_camera.v
tcc: x86_64-gen.c:435: load: Assertion `((ft & VT_BTYPE) == VT_INT) || ((ft & VT_BTYPE) == VT_LLONG) || ((ft & VT_BTYPE) == VT_PTR) || ((ft & VT_BTYPE) == VT_FUNC)' failed.
Aborted (core dumped)
V error: C error. This should never happen
```

**Comment by JustinRyanH** [comment]
Repo if you want to experiment with it yourself 

https://github.com/MajorHard/vraylib

**Comment by medvednikov** [comment]
Can you try defining `fn C.GetDroppedFiles(*int) **char`?

**Comment by JustinRyanH** [comment]
@medvednikov Elaborate? It's from a 3rd part library, I believe it is an array of cstrings. Is that what you're asking for?
