### ISSUE TITLE
Can't cast int to byte

### ISSUE THREAD

**Issue by lobotony** [vlang/v#2461]
**V version:** V 0.1.21 dfc654f
**OS:** MacOS 10.15

**What did you do?**

	fn main() {
		val := 13
		v3 := byte((val & 0xff000000) >> 24)
		println(v3)
	}

**What did you expect to see?**
successful compilation
 
**What did you see instead?**
 constant `0xff000000` overflows `byte`

This used to work until days or weeks ago.

**Comment by avitkauskas** [comment]
I think this is related #2452

**Comment by gslicer** [comment]
I think this one can be closed, because V as a "safe" language shall not allow such overflows at all, so the error msg seems correct

**Comment by shsr04** [comment]
Yes, not a bug, but a bit unclear. The `byte` cast expects all literals to not exceed the size of a `byte`. Add an inner cast to `u32` to fix the error.

**Comment by penguindark** [comment]
Solved
