### ISSUE TITLE
error : ft2build.h 

### ISSUE THREAD

**Issue by hunylee** [vlang/v#2465]
**V version:** 
 ** V 0.1.21 dfc654f
**OS:** 
** mac os

**What did you do?**
** v/examples/tetris/tetris.tmp.c:167:10: fatal error: 'ft2build.h' file not found

**What did you expect to see?**
** I won't  ft2build.h' 
 
**What did you see instead?**
** ft2build.h is add

**Comment by medvednikov** [comment]
it's mentioned in the readme: `brew install freetype`
