### ISSUE TITLE
array.insert seems buggy, missing tests

### ISSUE THREAD

**Issue by jkleiser** [vlang/v#2470]
**V version:**
V 0.1.21 eef73ee
**OS:**
macOS 10.14.6

**What did you do?**
Try to compile (v arr_insert.v) this:
```
fn main() {
	mut names := ['one', 'two']
	names.insert(1, 'THREE')
	println(names)
	
	mut ints := [1, 2]
	ints.insert(1, 3)
}
```
**What did you expect to see?**
Successful compilation.
 
**What did you see instead?**
```
.../arr_insert.tmp.c:4873:36: error: cannot take the address of an rvalue of type 'string' (aka 'struct string')
 array_insert(& /* ? */ names , 1 ,& /*112 EXP:"void*" GOT:"...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen. ...
```
There should be tests in array_test.v that demonstrates successful insertion of new items, both into []string and []int, and other types of arrays.

**Comment by jkleiser** [comment]
If I replace the line `names.insert(1, 'THREE')` with these two lines
```
n3 := 'THREE'
names.insert(1, n3)
```
then the compilation succeeds.
When I try to run it, however, I get this:
```
["one", "THREE", "two"]
Segmentation fault: 11
```

**Comment by avitkauskas** [comment]
I think this could be also ralated: #1990
Looks like array memory management is still quite raw.
Looking forward to the release of memory management that Alex is working on.

**Comment by Delta456** [comment]
It works fine now

```v
fn test_insert() {

	mut a := [1, 2]

	a.insert(0, 3)

	assert a[0] == 3

	assert a[2] == 2

	assert a.len == 3

	a.insert(1, 4)

	assert a[1] == 4

	assert a[2] == 1

	assert a.len == 4

	a.insert(4, 5)

	assert a[4] == 5

	assert a[3] == 2

	assert a.len == 5

	mut b := []f64{}

	assert b.len == 0

	b.insert(0, f64(1.1))

	assert b.len == 1

	assert b[0] == f64(1.1)

}

fn test_insert_many() {

	mut a := [3, 4]

	a.insert(0, [1, 2])

	assert a == [1,2,3,4]

	b := [5,6]

	a.insert(1, b)

	assert a == [1,5,6,2,3,4]

}
```
