### ISSUE TITLE
Using concurrency generates broken C code

### ISSUE THREAD

**Issue by netmute** [vlang/v#2476]
**V version:** V 0.1.21 7680d9a
**OS:** macOS

**What did you do?**

Example 1:
```v
fn main() {
  d := Demo{}
  for {
    go d.hello('foo')
  }
}

struct Demo {
mut:
  helloed []string
}

fn (d mut Demo) hello(foo string) {
  d.helloed << foo
}
```

Example 2 (Same, but with Demo as pointer):
```v
d := &Demo{}
```

**What did you expect to see?**
A V compiler error in both instances.
 
**What did you see instead?**

Example 1:
```
demo.tmp.c:4883:12: error: assigning to 'Demo *' (aka 'struct Demo *') from incompatible type 'Demo' (aka 'struct Demo'); take the address with &
 tmp2 -> d =  d ;
           ...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen.
```

Example 2:
```
demo(62096,0x70000f58d000) malloc: Double free of object 0x7f9a63402ad0
demo(62096,0x70000f50a000) malloc: Double free of object 0x7f9a63402ad0
demo(62096,0x70000f50a000) malloc: *** set a breakpoint in malloc_error_break to debug
demo(62096,0x70000f58d000) malloc: *** set a breakpoint in malloc_error_break to debug
fish: './demo' terminated by signal SIGABRT (Abort)
```

**Comment by LorenzoPirro** [comment]
@netmute as i've said on discord, the problem is that you need to write `d := &Demo{}`, in fact a mut Demo is trated as pointer to struct when hello is called, and you're define d as a simple struct value instead of a pointer (it's a little subtle).
The secondary problem is given by synchronization. In fact you need to synchronize `d.helloed <<  hello` with a mutex, or you'll obtain a double free error because multiple thread will try to write on the same location and free the old value potentially at the same time.

**Comment by medvednikov** [comment]
Indeed `d := &Demo{}` needs to be used for a heap allocation, V will detect this and return an error.

**Comment by medvednikov** [comment]
Modifying values concurrently without synchronization also will not be allowed.

**Comment by netmute** [comment]
@LorenzoPirro I understand both problems. The bug is here because the compiler produces a C error in the first instance, and unsafe memory handling in the second.

Both are bugs in V.

**Comment by elimisteve** [comment]
> Modifying values concurrently without synchronization also will not be allowed.

Sounds perfect! How can this be achieved in a way that doesn't require the user/programmer to jump through a bunch of hoops?

**Comment by crthpl** [comment]
This now has an error:
```
file.v:4:8: error: method in `go` statement cannot have non-reference mutable receiver
    2 |   mut d := Demo{}
    3 |   for {
    4 |     go d.hello('foo')
      |        ^
    5 |   }
    6 | }
```
