### ISSUE TITLE
Is int really 32bit (int32_t) or just the default C int?

### ISSUE THREAD

**Issue by KeyWeeUsr** [vlang/v#2480]
I have found include for [``inttypes.h``](https://github.com/vlang/v/blob/fdfa564865331a2bda077164d804d6dc90b83498/vlib/compiler/cheaders.v#L11) and [``typedef``s for almost every type](https://github.com/vlang/v/blob/fdfa564865331a2bda077164d804d6dc90b83498/vlib/compiler/cheaders.v#L107) in V **except** ``int``. Am I right to suspect ``int`` it therefore an ordinary C ``int`` type and only [``u32``](https://github.com/vlang/v/blob/fdfa564865331a2bda077164d804d6dc90b83498/vlib/compiler/cheaders.v#L113) is properly defined as an unsigned int always with size of 32 bits?

If that's the case, I've read about [``int`` not always being 32-bit](https://stackoverflow.com/a/1231456/5994041) which brings a question - shouldn't we use ``typedef int32_t i32`` or ``typedef int32_t int`` instead? See [``khrplatform.h``](https://github.com/vlang/v/blob/35b15b94810c08b74a438138b8e2554089b9bd95/thirdparty/glad/KHR/khrplatform.h#L150) for ensuring always having 32-bit int size.

**Comment by gslicer** [comment]
I just ried it:

V-code
```v
fn main() {
a := 539
print(a.str())
}
```
C-code
```c
void main__main() {
int a= 539 ;
print ( int_str( a ) ) ;
 }
```

**Comment by Bowero** [comment]
The C source file is indeed huge and we are aware of that. It is on our roadmap to fix that soon.

As @KeyWeeUsr points out, `int` is indeed just `int` and therefore we can't guarantee the size of that data type. This should be fixed.

**Comment by medvednikov** [comment]
@gslicer there are 2.5k lines of vlib in that C file, that's not a lot. It will be cached anyway.

@KeyWeeUsr indeed, `int32_t` should be used.

**Comment by KeyWeeUsr** [comment]
Same applies for [``bool`` using plain ``int``](https://github.com/vlang/v/blob/2f5a742f3e66aa4cf7735e56e9f24273c048a01d/vlib/compiler/cheaders.v#L132) and other ``int`` derived types imho otherwise it might kick back hard. However once we are limiting the design to fixed sizes instead of relative/range sizes we're lowering the portability of the language.

**Comment by gslicer** [comment]
for bool 'int' is overkill (even the amallest) 'byte' (i8) should be suffivient

**Comment by KeyWeeUsr** [comment]
@gslicer while I agree totally, it'll break the compatibility for all previous versions in case someone played with the container in an unsafe manner. It might also kill off the compiler since a brief github search shows just `bool` and not `C.bool` everywhere.

So to ensure having the interface with C there'd either need to be `C.bool` and other `C.<type>` alternatives or keeping `bool` at the max and **stable** size of all implementations available by default if we want to go the way of having fixed-size types instead of C-like range types.

**Comment by bogen85** [comment]
Indirectly related to this are #2684  #2876 as they deal with what integer size to associate with integer literals.

**Comment by penguindark** [comment]
from the v-doc: **Please note that unlike C and Go, `int` is always a 32 bit integer.**
