### ISSUE TITLE
Can't call function with the same name as a variable

### ISSUE THREAD

**Issue by lenaing** [vlang/v#2481]
Hello !

**V version**: V 0.1.21 a29c80c
**OS** : Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

**What did you do ?**
I tried to set a variable by calling a function named with the same name.
```v
fn main() {
    test := test()
    println(test)
}

fn test() int {
    return 0
}
```

**What did you expect to see?**
```bash
$ v run test.v 
0
```
**What did you see instead?**
```
$ v run test.v 
test.v:2:18: unexpected token: `)`
    1| fn main() {

    2|     test := test()

                        ^
    3|     println(test)

    4| }


```

**Comment by Sag-Dev** [comment]
Why would someone try to do that? I don't really think this is a bug, you can't do it on C++ either. Actually, I believe it's a good thing you can't, it protects you against bad naming decisions and avoids unnecesary shadowing.

**Comment by lenaing** [comment]
Well,
Guess I did not hit that behavior since I started C programming until today ! 😄 
And, actually, it depends of the language. As an example, in Rust :

```rust
$ cargo new testing
     Created binary (application) `testing` package
$ cat > testing/src/main.rs <<EOF
fn main() {
    let test = test();
    println!("Hello {}", test);
}

fn test() -> u32 {
  0
}
EOF
$ cd testing/
~/testing$ cargo run
   Compiling testing v0.1.0 (/home/egirondel/testing)
    Finished dev [unoptimized + debuginfo] target(s) in 0.62s
     Running `target/debug/testing`
Hello 0
```

**Comment by Sag-Dev** [comment]
In most languages, as soon as you declare the variable, it replaces the method with the same name in the current scope, so I find it understandable you are unable to call 'test()' in the assignment of the variable 'test', since assignation goes after declaration.

I do not believe 'fixing' this in V would do any good, but you got a nice point anyway :smile:

**Comment by medvednikov** [comment]
Yes, that'd be against V's philosophy. It doesn't even allow variable shadowing.

**Comment by medvednikov** [comment]
The error message needs to be a lot better than `unexpected token: )`
