### ISSUE TITLE
Failed to build V on Windows

### ISSUE THREAD

**Issue by DJonesCode** [vlang/v#2483]
**V version:** 
0.1.21

**OS:** 
Windows 10

**What did you do?**
Attempted to install V using the git commands from the Read Me.

**What did you expect to see?**
I expected the Command Line to display that V had been installed successfully.
 
**What did you see instead?**
The source failed to compile.
"Attempting to build v.c with MSVC...
v_win.c
vc\v_win.c(6): fatal error C1083: Cannot open include file: 'inttypes.h': No such file or directory cl.exe failed to build V
Failed to compile - Create an issue"

@emily33901

**Comment by DJonesCode** [comment]
MSVC uses stdint.h instead of inttypes.h. 
Changing line 6 of v_win.c should fix the issue, but the Make command redownloads the files.

**Comment by asampal** [comment]
Just want to note that I'm able to build successfully at the latest commit, fdfa564865331a2bda077164d804d6dc90b83498, using the MS compiler. I do have the environment variable VFLAGS defined as `-cc msvc` as advised by @spytheman.

**Comment by vitalyster** [comment]
vc2015-2019 definitely have inttypes.h, older vc compilers are not tested

**Comment by DJonesCode** [comment]
I'm using VS 2019. I found inttypes.h in the Windows Kits folders as its mentioned in #1891 .
I tried adding the Environment Variable VFLAGS for "-cc msvc" but I still get the same result.

When I do "echo %INCLUDE%" in the cmd console, Its only showing the MSVC folder under Visual Studio. Windows Kits isn't there.

**Comment by medvednikov** [comment]
V now uses `stdint.h` with MSVC.
