### ISSUE TITLE
unhandled option type: `?net.Socket` even after using or block

### ISSUE THREAD

**Issue by iambenkay** [vlang/v#2485]
**V version: 0.1.21 fb89c12** 
**OS: Ubuntu 18.04** 

**What did you do?**
```go
connection := socket.accept() or {
			println(err)
			return
		}
```

**What did you expect to see?**
I expected the code to run fine since I handled the option type

 
**What did you see instead?**
unhandled option type: `?net.Socket`

**Comment by netmute** [comment]
The error is probably thrown when you create `socket`. Do you have an `or` block there as well?

**Comment by iambenkay** [comment]
Okay that worked. Thanks
