### ISSUE TITLE
`v v.v` is an error under Windows 10.

### ISSUE THREAD

**Issue by changrui** [vlang/v#2488]
**V version:** 
V 0.1.21
**OS:** 
Windows 10 build 19002.
**What did you do?**
v v.v ---> v.exe

**What did you expect to see?**
Error: `cannot open output file v.exe: Permission denied`

so the correct way is `v -o vv.exe v.v` and rename or copy it to `v.exe`.

 
**What did you see instead?**

**Comment by medvednikov** [comment]
Fixed.
