### ISSUE TITLE
Doesnt compile on windows

### ISSUE THREAD

**Issue by r4jk3** [vlang/v#2489]
D:\>cd v

D:\v>make.bat
Building V
git version 2.22.0.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
In file included from vc\v_win.c:82:
c:\mingw\include\shellapi.h:332:35: error: unknown type name 'REFIID'; did you mean 'REFGUID'?
 HRESULT WINAPI SHGetImageList(int,REFIID,void**);
                                   ^~~~~~
                                   REFGUID
vc\v_win.c: In function 'builtin__init':
vc\v_win.c:2529:30: error: '_O_U16TEXT' undeclared (first use in this function); did you mean 'O_TEXT'?
     _setmode(_fileno(stdin), _O_U16TEXT);
                              ^~~~~~~~~~
                              O_TEXT
vc\v_win.c:2529:30: note: each undeclared identifier is reported only once for each function it appears in
vc\v_win.c:2533:30: error: '_O_U8TEXT' undeclared (first use in this function); did you mean 'O_TEXT'?
     _setmode(_fileno(stdin), _O_U8TEXT);
                              ^~~~~~~~~
                              O_TEXT
gcc failed to compile - Create an issue at 'https://github.com/vlang'

D:\v>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/8.2.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-8.2.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --target=mingw32 --prefix=/mingw --disable-win32-registry --with-arch=i586 --with-tune=generic --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-8.2.0-5' --with-gmp=/mingw --with-mpfr=/mingw --with-mpc=/mingw --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --with-isl=/mingw --enable-libgomp --disable-libvtv --enable-nls --disable-build-format-warnings
Thread model: win32
gcc version 8.2.0 (MinGW.org GCC-8.2.0-5)

**Comment by vitalyster** [comment]
-D__MSVCRT_VERSION=0x0900 will help, but you need to link msvcr90.dll or later using custom gcc specs. Use mingw-w64 or llwm-mingw with newer msvcrt out of the box.

**Comment by medvednikov** [comment]
mingw is not supported, only mingw-w64

I'll add mingw detection and an error message to handle it.
