### ISSUE TITLE
'Declared mut but never changed' is not detected correctly

### ISSUE THREAD

**Issue by avitkauskas** [vlang/v#2491]
**V version:** 
**OS:** 

**What did you do?**
```v
fn main(){
  mut a := [1,2,3]
  println( a.str() )
  println( a.len )
}
```

**What did you expect to see?**
```
test.v:2:7: `a` is declared as mutable, but it was never changed
```
 
**What did you see instead?**
Compiled without an error.

Though
```v
fn main(){
  mut a := [1,2,3]
  println( a.len )
}
```
gives compile error.

Looks like compiler thinks that `.str()` mutates the receiver.

**Comment by LorenzoPirro** [comment]
@avitkauskas i've found the related problem. Compiler looks as "used" whatever mutable variable on which a method is called (that modifies or not the content). In fact this works without error or warning:
```
struct Foo {
mut: a int
}

fn (f Foo) foo () int {
	return f.a
}

fn main(){
	mut a := Foo{a:5}
	println( a.foo() )
}
```

**Comment by darenliang** [comment]
It looks like the problem goes pretty deep. From what I see, all methods called mark the variable as changed regardless if the variable was mutated or not.

Example:
```v
fn main() {
  mut a := [1, 2, 3]
  println(a.index(2))
}
```
compiles. However, `.index()` doesn't mutate the receiver array.

**Comment by medvednikov** [comment]
Fixed. It was a one line fix :)

**Comment by medvednikov** [comment]
Lots of tests had to be fixed. It's good to find and fix such things early on.

Thanks @avitkauskas.
