### ISSUE TITLE
Error in the documentation (Arrays section)

### ISSUE THREAD

**Issue by Sag-Dev** [vlang/v#2493]
I found an error while reading the documentation. In the arrays section the code states:

```
// We can also preallocate a certain amount of elements.
nr_ids := 50
ids := [0].repeat(50) // This creates an array with 50 zeros
```

The variable `nr_ids` is declared but never used, I guess it should be passed to the `repeat` function instead of `50`.

**Comment by medvednikov** [comment]
Fixed, thanks.
