### ISSUE TITLE
'v -os linux' produces macOS binaries

### ISSUE THREAD

**Issue by netmute** [vlang/v#2494]
**V version:** V 0.1.21 eeea257
**OS:** macOS

**What did you do?**
Try to cross-compile any file:
```
v -os linux file.v
```

**What did you expect to see?**
A linux binary.
 
**What did you see instead?**
A macOS binary.

**Comment by vitalyster** [comment]
You can try to add `-cc x86_64-linux-gnu-gcc` option but if it does not work then:
```
v -os linux -o file.c file.v
x86_64-linux-gnu-gcc file.c
```
This should be a workaround

**Comment by netmute** [comment]
Thank you.

I have Linux machines available, just leaving the bug here for documentation’s sake 😉

**Comment by serkonda7** [comment]
Could you please try again with latest V.

**Comment by netmute** [comment]
I haven't used V in quite some time. If someone else could try, that would be fantastic 👍

**Comment by medvednikov** [comment]
It works now.
