### ISSUE TITLE
V compiler should warn users if their entry point is not in `module main`

### ISSUE THREAD

**Issue by Trivaxy** [vlang/v#2495]
V currently allows `fn main` to be defined in any module, but V only calls `main` as an entrypoint if it is inside `module main`, and ignores any `main` function in other modules (doesn't treat them as an entrypoint, only like normal functions).

This can confuse new users coming from languages that allow entrypoints in non-main "modules".
The V compiler also doesn't give any hints or warnings to users if `main` isn't inside `module main`.

The compiler should instead warn users that they have no proper entry point if:
1. They have a `module main` with no `fn main()` **or**
2. They have only one `fn main`, but in any other module other than `module main`.

with a warning message such as `warning: no entry point 'fn main()' present in 'module main'`.

However, the compiler shouldn't warn users if they have multiple `main` functions across multiple modules because the user would either know what they are doing or they are just naming their functions `main` for other reasons than entry point.

Discord discussion link: https://discordapp.com/channels/592103645835821068/592294828432424960/636240610680111117

**Comment by gslicer** [comment]
I think this check can be reduces to:
If no `fn main()` defined in `module main` >> compiler error

Entry point should always be `main.main()`

**Comment by Trivaxy** [comment]
> I think this check can be reduces to:
> If no `fn main()` defined in `module main` >> compiler error (`module main` always exists, even when not explicitely declared e.g. single file .v programs)
> 
> Entry point should always be `main.main()`

The idea here is to warn users they have no valid entrypoint, so your suggestion probably works.

**Comment by Danil-Lapirow** [comment]
You can have no module main and compile your program properly. You can even skip `fn main()` in your code. Im not sure when you want V to show such a warning.

**Comment by Trivaxy** [comment]
@Danil-Lapirow Yes. We know.
The point is that V never warns users if they have no entrypoint if they're developing an application. 
If you have, for example, a `module main` with no `fn main()` and you're developing an application instead of a library there should be a warning emitted by the compiler about not having a valid entrypoint.

**Comment by medvednikov** [comment]
Fixed @Trivaxy
