### ISSUE TITLE
"make" doesn't build version 0.1.21 correctly

### ISSUE THREAD

**Issue by Keith-S-Thompson** [vlang/v#2497]
**V version:**  0.1.21
**OS:** Ubuntu 18.04.3 LTS (bionic)

**What did you do?**
- Clone repo
- Checkout tag 0.1.21
- `make`

**What did you expect to see?**
A working `v` compiler

 
**What did you see instead?**
A non-working `v` compiler

The `Makefile` checks out the latest version of the `vc` repo, regardless of which commit of the `v` repo is checked out. Running `make` builds a `v` compiler, but it uses the checked out version of `vlib`.

In this particular case, the result is a `v` compiler that fails with an error message in `vlib/builtin/array.v`.

See the attached `v-bug` test script and `v-bug.out` output file contained in `v-bug.tar.gz`.

Suggestion: Perhaps the `Makefile` could have a `bootstrap` target that would build a known working version and then use it to bootstrap the currently checked out sources. Or perhaps `vc` should be incorporated into the `v` repo, either directly or as a submodule.

Also, the `vc` repo has a commit updated from the `v` tag `0.1.21`, but it has no tag associated with it.

[v-bug.tar.gz](https://github.com/vlang/v/files/3757611/v-bug.tar.gz)

**Comment by medvednikov** [comment]
`make` only works with the latest commit right now.

V is changing so rapidly at this stage, there's no point in using version tags. This will calm down by the time of the 0.2 release.
