### ISSUE TITLE
Array appending sometimes gives strange results

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#250]
For example, 
```
fn main() {
	mut a := [1, 2, 3]
	mut b := a
	a << 4
	b << 5
	println(a)  // => [1,2,3,5] √
	println(b)  // => [1,2,3,5] √
	b << 6
	b << 7
	mut c := b
	c << 8
	c << 9
	println(a)  // => [0,0,3,5] ?
	println(b)  // => [0,0,3,5,6,7] ?
	println(c)  // => [1,2,3,5,6,7,8,9] √
}
```
And if I delete the first println(a) and println(b), the results will be correct.
```
fn main() {
	mut a := [1, 2, 3]
	mut b := a
	a << 4
	b << 5
	b << 6
	b << 7
	mut c := b
	c << 8
	c << 9
	println(a)  // => [1,2,3,5] √
	println(b)  // => [1,2,3,5,6,7] √
	println(c)  // => [1,2,3,5,6,7,8,9] √
}
```

**Comment by dcurrie** [comment]
```
fn main() {
	mut a := [1, 2, 3]
	mut b := a
	a << 4
	b << 5
	println(a)  // => [1,2,3,5] √
	println(b)  // => [1,2,3,5] √
```

Why is this ok? Where did the `4` go?

As I understand it, arrays are copied by reference when using `:=` not by value, so `a` and `b` reference the same mutable array. Two values are appended to that array, `4` and `5`, but only one is shown

**Comment by SleepyRoy** [comment]
@dcurrie 
Yeah, to begin with I also understand arrays like this (and this is a typical Python style/understanding of arrays). But after some experiments I infer that the mechanism of arrays in V is probably:
a := [1, 2, 3]
b := a    //  There's only copy in memory. b points from 1 to 3, so b is [1,2,3] 
a << 4   //  Append 4 to a, so a is [1,2,3,4]. But b still points from 1 to 3.
b << 5   //  Append 5 to b, so the coming 5 will overwrite 4.
Finally, we actually have [1,2,3,5] in memory. And both a and b points from the first element to the fourth, thus they're both [1,2,3,5].

**Comment by medvednikov** [comment]
Related: https://github.com/vlang/v/issues/119

Array copies/references need a lot of work. I've used them zero times in my code (V, Volt etc).

**Comment by SleepyRoy** [comment]
@medvednikov 
I totally understand. This is a very good way to help programmers to explore and understand the mechanism of a language. Differentiating between locations and values is always a challenge for language learners. One important reason is that many languages even do not have clear description of it. I hope V would be a clear and definite language : )

**Comment by data-man** [comment]
@medvednikov 
Can be `<<` replaced to `add` or `append` in future?
In first glance it like as left shift.
Also in future can be added `insert` and `delete` for arrays.

**Comment by medvednikov** [comment]
> One important reason is that many languages even do not have clear description of it. I hope V would be a clear and definite language : )

For sure, that's one of the main goals. It'll be made clear.

> Can be << replaced to add or append in future?

`<<` is going to stay. It's a much shorter and cleaner alternative to `array = append(array, val)`.

> Also in future can be added insert and delete for arrays.

They are already implemented: `array.insert(i, val)`, `array.delete(i)`. Should make them public, so that they appear in module docs.

**Comment by Bowero** [comment]
See #119 for the conversation on this.
