### ISSUE TITLE
can't build vid

### ISSUE THREAD

**Issue by jemand2001** [vlang/v#2501]
**V version:just pulled (10/22/19 23:00 EST)** 
**OS: Linux** 

**What did you do?**
I cloned vid (also latest), navigated to the cloned directory, ran `v .`

**What did you expect to see?**
whatever output V produces on successful compilation
 
**What did you see instead?**
an error message (see attached image).
![image](https://user-images.githubusercontent.com/24275520/67336826-482d4700-f526-11e9-8619-150d04faaede.png)

**Comment by jemand2001** [comment]
if this belongs on the vid github, i will glaadly post it there instead too, but the error message directed me here, so i posted it here

**Comment by medvednikov** [comment]
You have to install freetype, it's in the readme.

**Comment by jemand2001** [comment]
oh, sorry. maybe i should actually read those
