### ISSUE TITLE
Launching a thread with an high order function fails

### ISSUE THREAD

**Issue by Metalymph** [vlang/v#2502]
**V version:*latest* 
**OS:*MacOS Catalina* 

**What did you do?**
High order functions work well, but if you call it with `go`, it fails. For example:
```
fn main() {
	go foo(ok)
}

fn foo(ok fn()) {
	ok()
}

fn ok() {
	println('ok')
}
```

**What did you expect to see?**
That works like a normal high order function
 
**What did you see instead?**
Output is:
```
t.tmp.c:475:42: error: type name requires a specifier or qualifier
typedef struct  thread_arg_main__foo   { fn () ok ;} thread_arg_main__foo ;
                                         ^
t.tmp.c:475:47...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

**Comment by Ivo-Balbaert** [comment]
The original code on Windows 10 in v 0.1.27 gives the V error in line  ok():
 error: ambiguous call to: `ok`, may refer to fn `ok` or variable `ok` 
    4 | 


When changing to:

fn main() {
	go foo(ok)
}

fn foo(test fn()) {
  test()
}

fn ok() {
	println('ok')
}

I get:

[Running] v run "e:\Vlang\tests\test.v"
==================
<command-line>: note: this is the location of the previous definition
C:\Users\CVO\AppData\Local\Temp\v\test.tmp.c:1181:2: error: expected specifier-qualifier-list before 'ok'
  ok arg1;
  ^~
C:\Users\CVO\AppData\Local\Temp\v\test.tmp.c: In function 'foo_thread_wrapper':
C:\Users\CVO\AppData\Local\Temp\v\test.tmp.c:1194:9: error: 'thread_arg_foo' {aka 'struct thread_arg_foo'} has no member named 'arg1'
  foo(arg->arg1);
         ^~
C:\Users\CVO\AppData\Local\Temp\v\test.tmp.c: In function '_STR':
C:\Users\CVO\AppData\Local\Temp\v\test.tmp.c:1303:14: warning: pointer targets in passing argument 1 of 'tos2' differ in signedness [-Wpointer-sign]
  return tos2(buf);
              ^~~
...
==================
(Use `v -cg` to print the entire error message)

builder error: C error.

Please make sure that:
- You have all V dependencies installed.
- You did not declare a C function that was not included. (Try commenting your code that involves C interop)
- You are running the latest version of V. (Try running `v up` and rerunning your command)

If you're confident that all of the above is true, please try running V with the `-cg` option which enables more debugging capabilities.


[Done] exited with code=1 in 0.947 seconds

**Comment by crthpl** [comment]
This still results in:
```
/tmp/v/a.12783495417555964281.tmp.c:1053:2: error: unknown type name 'main__ok_fun'
        main__ok_fun arg1;
        ^
1 error generated.
builder error:
==================
C error. This should never happen.
```

**Comment by spytheman** [comment]
A variant of the above works:
```v
type Fn = fn()

fn main() {
    x := go foo(Fn(ok))
    x.wait()
}

fn foo(x Fn) {
    x()
}

fn ok() {
    println('ok')
}
```
When `x := go foo(Fn(ok))` is changed to just `x := go foo(ok)`, then there is a cgen compilation error again.

**Comment by medvednikov** [comment]
Fixed.
