### ISSUE TITLE
anonymous function 

### ISSUE THREAD

**Issue by Delta456** [vlang/v#2503]
Like Go, V should also have anonymous functions.

```v
fn main() {
  fn(foo string) {
   println(foo)
  }('foo')
}
```

**Comment by nedpals** [comment]
would be a cool thing too to be stored in variables

**Comment by Delta456** [comment]
@nedpals That might not be called anonymous anymore IMO.

**Comment by BafS** [comment]
See https://github.com/vlang/v/issues/1066

**Comment by lutherwenxu** [comment]
> See #1066 

This issue is a duplicate so I'm closing it. :smiley:
