### ISSUE TITLE
panic segfaults on alpine

### ISSUE THREAD

**Issue by bogen85** [vlang/v#2508]
**V version:** 
``` V 0.1.21 fcead2f ```

**OS:** 
```
$ uname -a
Linux aplineoct19 4.19.78-1-virt #2-Alpine SMP Wed Oct 9 08:49:48 UTC 2019 x86_64 Linux

$ cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11_alpha20190925
PRETTY_NAME="Alpine Linux edge"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**What did you do?**

Wrote the following test program:

```v
fn main() {
	panic("yikes")
}
```

**What did you expect to see?**

What I get on archlinux:
```
$ v yikes.v 
$ ./yikes 
V panic: yikes
$
```
 
**What did you see instead?**
When I compile and run it I got a segfault:
```
$ v -cc clang -cflags -lexecinfo yikes.v
$ ./yikes 
V panic: yikes
Segmentation fault

$ v -cc tcc -cflags -lexecinfo yikes.v
$ ./yikes 
V panic: yikes
Segmentation fault
```

**For reference, a sample v program that does not segfault on exit on my alpine install**

Given the following:
```v
fn main() {
	println("hello")
}
```
When I compile and run it, it does not segfault:
```
$ v -cc tcc -cflags -lexecinfo hello.v
$ ./hello 
hello
$ cat hello.v 
fn main() {
	println("hello")
}
$ v -cc clang -cflags -lexecinfo hello.v
$ ./hello 
hello
```

**Comment by bogen85** [comment]
This seems to indirectly related to the libexecinfo issues already reported for v on apline.
The following does not segfault (only difference between the real v panic is the commented out backtrace line)

```v
pub fn panic2(s string) {
	println('V panic: $s')
	//print_backtrace()
	C.exit(1)
}


fn main() {
	panic2("yikes")
}
```

**Comment by bogen85** [comment]
Alright, I found the segfaulting line of code, I'll dive more into this later...

It is in print_backtrace_skipping_top_frames from vlib/builtin/builtin.v

```v
pub fn print_backtrace_skipping_top_frames(skipframes int) {
	$if mac {
		buffer := [100]byteptr
		nr_ptrs := C.backtrace(*voidptr(buffer), 100)
		C.backtrace_symbols_fd(*voidptr(&buffer[skipframes]), nr_ptrs-skipframes, 1)
		return
	}
	$if linux {
		$if !android {
			// backtrace is not available on Android.
			if C.backtrace_symbols_fd != 0 {
				buffer := [100]byteptr
				nr_ptrs := C.backtrace(*voidptr(buffer), 100)
```

```nr_ptrs := C.backtrace(*voidptr(buffer), 100)``` is the line it segfaults on

**Comment by bogen85** [comment]
libexecinfo appears to be broken on alpine... even the C example from 'man backtrace' segfaults on alpine linux (and does not on archlinux)

However, libunwind works fine on alpine ( I tried the following example: https://github.com/cslarsen/libunwind-examples/blob/master/backtrace.cpp and it produced a nice backtrace and did not segfault )

```
$ apk info libexecinfo
libexecinfo-1.1-r1 description:
A quick-n-dirty BSD licensed clone of the GNU libc backtrace facility.
```
*quick and dirty?...*

**Comment by bogen85** [comment]
Oh, great..... (not...)
The apline package at https://pkgs.alpinelinux.org/package/edge/main/x86/libexecinfo
refers to: https://www.freshports.org/devel/libexecinfo/
Which has not been updated in over two years...
```
There is no maintainer for this port.
...
No installation instructions: this port has been deleted.
The package name of this deleted port was:
PKGNAME: libexecinfo
...
port deleted on 2017-09-22
REASON: Is present in the base system of all supported releases
```
I need to file a bug report on alpine.
I checked here: https://git.alpinelinux.org/aports/tree/main/libexecinfo/APKBUILD
And downloaded the indicated source tarball for the current version.
It is dated July 19, 2004.
The APKBUILD package contains a recent patch against, but the libexecinfo project does not seem as well behaved as the **libunwind** package.

**Comment by bogen85** [comment]
I filed a bug report with alpine linux.

https://gitlab.alpinelinux.org/alpine/aports/issues/10896

**Comment by spytheman** [comment]
Alpine uses musl, and if I remember correctly, musl's maintainer refuses to fix/implement backtrace in musl (https://www.openwall.com/lists/musl/2015/04/09/3)

**Comment by bogen85** [comment]
Yeah, which I guess is why libexecinfo must be used for the equivalent backtrace function.

**Comment by bogen85** [comment]
As I noted earlier, using the backtrace functionality from libunwind works fine in alpinelinux.

**Comment by bogen85** [comment]
This does not only occur on alpine edge. It occurs on alpine stable as well.

I tested this on stable and updated https://gitlab.alpinelinux.org/alpine/aports/issues/10896

**Comment by medvednikov** [comment]
Fixed. V now works with musl and Alpine.
