### ISSUE TITLE
Add support for multiple statements in single line

### ISSUE THREAD

**Issue by m5ome** [vlang/v#2509]
```v
fn main() {
    println('...'); println('...')
}

**Comment by changrui** [comment]
oh， separate  every statement with `space` only.

**Comment by medvednikov** [comment]
The way the parser works, you can already do 

```
    println('...') println('...')
```

In the future, a semicolon will be introduced for this, but it will be removed by vfmt anyway, like in Go.

**Comment by AlekTheSixth** [comment]
I would like to use semicolon optionally, actually.
As a polyglot developer I constantly put `;` in the end of each line just because it's a habit I have.
