### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by xdk78** [vlang/v#251]
Every modern language has its own coding style for writing clean and understandable code.

What do you think?

1. comments:
  `/// for docs`
2. spaces or tabs?
  2 spaces
3. naming convention
  - consts, structs:  PascalCase
  - vars, modules: camelCase or snake_case?
  - files: snake_case

**Comment by medvednikov** [comment]
V automatically updates your code with vfmt once you compile it. You don't even need to use an external tool (like gofmt).

If you try to use PascalCase for a function name, V will complain: `function names cannot contain uppercase letters, use snake_case instead`

So there's no need to worry about that :)

**Comment by Psylocybit** [comment]
Sorry to nudge a closed issue, but I am curious as to why uppercase letters are not allowed? I think that's highly restrictive and without cause personally.
