### ISSUE TITLE
map consts and map[string]map[string]fn() not supported

### ISSUE THREAD

**Issue by iambenkay** [vlang/v#2510]
**V version: 0.1.21 27e254c** 
**OS: Ubuntu 18.04** 

**What did you do?**
I tried to run *** v run index.v *** a program I wrote

**What did you expect to see?**
The program actually running
 
**What did you see instead?**
start_tmp() already started. cur_line=""

**Comment by medvednikov** [comment]
Does `v index.v && ./index` work?

**Comment by iambenkay** [comment]
No it doesn't. It doesn't successfully build index.v

**Comment by medvednikov** [comment]
Then I'm going to need the source. Looks like there's a bug in the compiler triggered by some of your code.

**Comment by iambenkay** [comment]
Okay then. Here is the source https://gist.github.com/iambenkay/3d63f83e2b329c5367920869ff0a910b

**Comment by medvednikov** [comment]
Thanks. 2 bugs in V cause this: map consts  and `map[string]map[string]fn()` not being supported yet.


There's no need in the final `main()` by the way.

**Comment by iambenkay** [comment]
Do only those two bugs cause the error because I am still facing the bug and I eliminated all the maps in the source code. Check this [gist](https://gist.github.com/iambenkay/3d63f83e2b329c5367920869ff0a910b) for updated code

**Comment by Danil-Lapirow** [comment]
> Do only those two bugs cause the error because I am still facing the bug and I eliminated all the maps in the source code. Check this [gist](https://gist.github.com/iambenkay/3d63f83e2b329c5367920869ff0a910b) for updated code

tmp in tmp

**Comment by Danil-Lapirow** [comment]
I think that we should rename it to `tmp is already started` issue. `map` of `map`s is an unsupported feature.

**Comment by Danil-Lapirow** [comment]
> Do only those two bugs cause the error because I am still facing the bug and I eliminated all the maps in the source code. Check this [gist](https://gist.github.com/iambenkay/3d63f83e2b329c5367920869ff0a910b) for updated code

My PR will let your changed code run
