### ISSUE TITLE
Can not build V on Windows (x64)

### ISSUE THREAD

**Issue by berbun** [vlang/v#2516]
**V version:** latest git (f14425ec1829041deae5bcc4c9649126ea292f75)
**OS:** Windows x64.

**What did you do?**
![screenshot](https://user-images.githubusercontent.com/34973365/67452333-24036000-f623-11e9-8ef8-86ae14b39cfa.png)
(I have VS2019 [full C++ workload] installed and MINGW64 and also Cygwin.)
But... Apparently there is something wrong.

**What did you expect to see?**
/
 
**What did you see instead?**
See the screenshot above.

**Comment by berbun** [comment]
Building V
git version 2.23.0.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
INFO: Could not find files for the given pattern(s).
Attempting to build v.c  with MSVC...
v_win.c
rebuild from source (twice, in case of C definitions changes)
'v3.exe' is not recognized as an internal or external command,
operable program or batch file.
V failed to build itself
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error

**Comment by berbun** [comment]
@emily33901 See above.

**Comment by changrui** [comment]
only `v up`.

**Comment by berbun** [comment]
> only `v up`.

I can't compile `v`...
> 'v' is not recognized as an internal or external command, operable program or batch file.

What do you mean ?

**Comment by changrui** [comment]
From `0` on:
1, git clone --depth=1 https://github.com/vlang/v vlang    # git.exe must be installed.
2, cd vlang; git clone --depth=1 https://github.com/vlang/vc
3, gcc -std=c99 -w -o vc.exe vc/v_win.c                                 # mingw64 is needed.
4, ./vc.exe -o vv.exe v.v
5, ./vv.exe -prod -o v.exe v.v
`The End.`

**Comment by berbun** [comment]
> From `0` on:
> 1, git clone --depth=1 https://github.com/vlang/v vlang # git.exe must be installed.
> 2, cd vlang; git clone --depth=1 https://github.com/vlang/vc
> 3, gcc -std=c99 -w -o vc.exe vc/v_win.c # mingw64 is needed.
> 4, ./vc.exe -o vv.exe v.v
> 5, ./vv.exe -prod -o v.exe v.v
> `The End.`

Thank you! These instructions worked flawlessly.
Somebody please update the `make.bat` to reflect these commands.

**Comment by medvednikov** [comment]
I'm pretty sure that's what make.bat is doing, I'll have a look.

Thanks

**Comment by gslicer** [comment]
@medvednikov I've noticed that V is building win-binaries without the .exe file-name extension - thus make.bat will build a v and 'v up' will build a vup utility which cannot be executed until renemed

**Comment by vitalyster** [comment]
@gslicer  I've noticed that it is llvm-mingw issue only, gcc and msvc add .exe automatically, maybe we need to raise issue in llvm-mingw project

**Comment by vitalyster** [comment]
https://github.com/mstorsjo/llvm-mingw/issues/60

**Comment by wojoeraf** [comment]
Besides that mingw issue, I have the same problem as the thread opener and at the time I was executing the Make.bat I had not even mingw installed. So all was going over visual studio.
