### ISSUE TITLE
Maybe try shorter syntax?

### ISSUE THREAD

**Issue by alexeypetrushin** [vlang/v#252]
Saw this code

```
fn abs(a f64) f64 {
	if a < 0 {
		return -a
	}
	return a
}
```

Would  be nice to be able to write that shorted, for example in Julia it could be written as

```
abs(a::Float64) = a < 0 ? -a : a
```

**Comment by medvednikov** [comment]
V's goal is not to achieve as few lines of code as possible, but to be a readable and predictable language with only one way of doing things (in most cases).

**Comment by ntrel** [comment]
V does have if expressions BTW.

**Comment by medvednikov** [comment]
Indeed, so it could be rewritten as 

```
fn abs(a f64) f64 {
	return if a < 0 { -a } else { a }
}
```

I think current version is ok.

**Comment by PavelVozenilek** [comment]
One liners are not very common in real world applications. 

However, there's point in brevity. The expression

`if a < 0 { -a } else { a }
`

would be written in C as

` a < 0 ? -a : a;
`

which is 9 non-space characters. In V it has 16 characters. And this kind of expression is very, very common.

If it was up to me, I would add it to the language, even if it is redundant. I'd not allow to nest `?:` expressions or to use code above certain (arbitrarily chosen) complexity, to keep the thing looking simple.

**Comment by ntrel** [comment]
C's ternary operator is bug prone, there are several precedence issues with it. V's syntax has none of these issues, and allows multiple statements in each branch. 
Minimizing typing at the cost of clarity is the wrong trade off.

**Comment by alexeypetrushin** [comment]
> One liners are not very common in real world applications.
True for Java, C, etc. 
Not true for Ruby.

**Comment by data-man** [comment]
Nice, compact and clean way! :)
```C++
using namespace std; 
  
int main() 
{ 
    cout << "Execute expression using "
    << "ternary operator: "; 
    int a = 4 > 3 ? 2 > 4 ? 2 : 4 : 3; 
    cout << a << endl; 
      
    cout << "Execute expression using "
    << "if else statement: "; 
    if ( 4 > 3 ) 
        if ( 2 > 4 ) 
            cout << "2"; 
        else
            cout << "4"; 
    else
        cout << "3"; 
    return 0; 
} 
```
