### ISSUE TITLE
vjs:  undefined: `tos_clone`

### ISSUE THREAD

**Issue by takanotume24** [vlang/v#2520]
**V version:** 
V 0.1.21 baf49b2

**OS:** 
Linux takuya-CF-MX3YG1CS 4.15.0-65-generic #74~16.04.1-Ubuntu SMP Wed Sep 18 09:51:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**What did you do?**
I try to compile example/json.v to json.js.

**What did you expect to see?**
converted javascript file.
 
**What did you see instead?**
```
takuya@takuya-CF-MX3YG1CS:~/v/examples$ v -o json.js json.v
/home/takuya/v/vlib/json/json_primitives.v:97:17: undefined: `tos_clone`
   96| 	// return tos(root.valuestring, _strlen(root.valuestring))
   97| 	return tos_clone(root.valuestring)// , _strlen(root.valuestring))
             	         ^
   98| }
   99| 

```

**Comment by Delta456** [comment]
Its still a WIP. Not high priority atm.

**Comment by medvednikov** [comment]
Fixed in the new JS backend.
