### ISSUE TITLE
error: parameter 1 ('e') has incomplete type

### ISSUE THREAD

**Issue by zlianon** [vlang/v#2527]
**V version:** 3d6bdc2
**OS:** Ubuntu 18.04

**What did you do?**
```v
type CurlError C.CURLcode

pub fn (e CurlError) error() string {...}
```

**What did you expect to see?**
For now, successful compilation
 
**What did you see instead?**
error: parameter 1 ('e') has incomplete type

**Comment by JalonSolov** [comment]
The latest version of V now gives this error message:
```
foo.v:3:38: error: invalid expression: unexpected token `...`
    1 | type CurlError=C.CURLcode
    2 |
    3 | pub fn (e CurlError) error() string {...}
      |                                      ~~~
    4 |
```

Closing this issue.

**Comment by zlianon** [comment]
@JalonSolov ```{ ... }``` just indicates some code inside block
