### ISSUE TITLE
generics not working in external modules

### ISSUE THREAD

**Issue by amalshaji** [vlang/v#2528]
**V version:** `V 0.1.21 753fe32`
**OS:** 
`Distributor ID: Ubuntu`
`Description:    Ubuntu 18.04.3 LTS`
`Codename:       bionic`

**What did you do?**
Wrote a sorting function using generics. Worked fine. Made the same function into a module and builds fine. Returns funny error when using the library 

**What did you expect to see?**
Correct Output.
 
**What did you see instead?**
<code>test.v:6:24: unexpected token: `,`</code>
<code>    5| fn main() {</code>
<code>    6|     nums := [1, 7, 0, 5, 6, 3] </code>
![Capture](https://user-images.githubusercontent.com/18011385/67498434-15598f00-f69d-11e9-918c-aea88ed1a6ed.PNG)

**Comment by Delta456** [comment]
Can you show the whole code?

**Comment by amalshaji** [comment]
Working Code: [bubble_generic.v](https://github.com/amalshaji/sorty/blob/master/sorty/bubble.v)
Module Code : [bubble_generic_module.v](https://github.com/amalshaji/sorty/blob/master/examples/bubble.v)

**Comment by medvednikov** [comment]
works for me

```
$ v run bu.v
[0, 1, 3, 5, 6, 7]
```

Though it shouldn't, the array has to be marked as mutable.

**Comment by amalshaji** [comment]
Module is working fine?

**Comment by avitkauskas** [comment]
@medvednikov It works only with all code in single file. Try to compile with the module.
```v
import sorty

fn main() {
	mut nums := [1, 7, 0, 5, 6, 3]
	sorty.bubble(nums)
	println(nums)
}
```
This gives an error:
```
test1.v:6:19: unexpected token: `,`
    5| fn main() {
    6| 	mut nums := [1, 7, 0, 5, 6, 3]
             	           ^
    7| 	sorty.bubble(nums)
    8| 	println(nums)
```

**Comment by avitkauskas** [comment]
Concerning the mutability of the immutable array  - this works because of the line in the function `bubble<T>(nums []T)`
```v
mut var := nums
```
And then modifying `var` also modifies `nums` - but should not, because `nums` was not declared `mut`.

**Comment by avitkauskas** [comment]
Another interesting note. I put the module code in the file `sorty/sorty.v` accidentally missing `module` in the compile comand. And that's what I got:
```
code/v % v build sorty
V error: function `main` is not declared in the main module
```
I did not do anything with module `main`, file `sorty.v` starts with`module sorty`.

**Comment by medvednikov** [comment]
Fixed.
