### ISSUE TITLE
V compiles in 0.6s?

### ISSUE THREAD

**Issue by mr-del** [vlang/v#253]
How could V compiles in 0.6s if the code generate an error syntax? Was it 0.6s because of an error?
https://vlang.io/compilation_speed

https://github.com/vlang/v/blob/e2a19cccd013cd1f35daa7eb9a89037d22ff8a93/website/compilation_speed_test_gen.v#L69

test.v:2
unexpected token: `;`
```
fn main() { mut a := 0 
a = 0; println(a);
a = 1; println(a);
a = 2; println(a);
a = 3; println(a);
.
.
.
}
```

**Comment by MaxUNof** [comment]
Vlang doesn't support ;
Correct gen_v():
```
fn gen_v() {
	println('fn main() { mut a := 0 ')
	for i := 0; i < N * 1000; i++ {
		println('a = $i\nprintln(a)')
	}
	println('}')
}
```
```

**Comment by mr-del** [comment]
How long does it took to compile in your test and what is your machine specification?

**Comment by medvednikov** [comment]
As discussed here the test is not very good and useful: https://github.com/vlang/v/issues/126

I'll update it as soon as the language is open-sourced.
