### ISSUE TITLE
Change `switch` to `match` please.

### ISSUE THREAD

**Issue by changrui** [vlang/v#2533]
**V version:**   v 0.1.21
**OS:**             Windows 10

**What did you do?**
`os_windows.v` 129:15:  switch  ...

**What did you expect to see?**
-
 
**What did you see instead?**
error, change to `match ... {}`.

**Comment by medvednikov** [comment]
it's  a warning, not an error :)

**Comment by M4SSD35TRUCT10N** [comment]
@changrui Could you provide the message? Even if it's a warning, v should avoid misleading language. `switch` is often a keyword in programming languages which v doesn't use at all (thank's @medvednikov ).

**Comment by rpi4iot** [comment]
similar issue happen on raspbain / raspberry pi
build failed,  "Segmentation fault"
0 byte .tmp.c 

pi@raspberrypi:~/vlang/v/examples/vweb $ ../../v --version
V 0.1.21 e80cf18

pi@raspberrypi:~/vlang/v/examples/vweb $ ../../v -g -debug -cc gcc test_vweb_app.v
C compiler=gcc
all .v files:
["/home/pi/vlang/v/vlib/builtin/array.v", "/home/pi/vlang/v/vlib/builtin/builtin.v", "/home/pi/vlang/v/vlib/builtin/cfns.v", "/home/pi/vlang/v/vlib/builtin/float.v", "/home/pi/vlang/v/vlib/builtin/hashmap.v", "/home/pi/vlang/v/vlib/builtin/int.v", "/home/pi/vlang/v/vlib/builtin/map.v", "/home/pi/vlang/v/vlib/builtin/option.v", "/home/pi/vlang/v/vlib/builtin/string.v", "/home/pi/vlang/v/vlib/builtin/utf8.v", "/home/pi/vlang/v/vlib/strings/builder_c.v", "/home/pi/vlang/v/vlib/strings/similarity.v", "/home/pi/vlang/v/vlib/strings/strings.v", "/home/pi/vlang/v/vlib/strconv/atoi.v", "/home/pi/vlang/v/vlib/os/const.v", "/home/pi/vlang/v/vlib/os/os.v", "/home/pi/vlang/v/vlib/os/os_nix.v", "/home/pi/vlang/v/vlib/net/urllib/urllib.v", "/home/pi/vlang/v/vlib/net/urllib/values.v", "/home/pi/vlang/v/vlib/http/chunked/dechunk.v", "/home/pi/vlang/v/vlib/net/init_nix.v", "/home/pi/vlang/v/vlib/net/net.v", "/home/pi/vlang/v/vlib/net/socket.v", "/home/pi/vlang/v/vlib/http/backend_nix.v", "/home/pi/vlang/v/vlib/http/download_nix.v", "/home/pi/vlang/v/vlib/http/http.v", "/home/pi/vlang/v/vlib/http/http_client.v", "/home/pi/vlang/v/vlib/vweb/vweb.v", "test_vweb_app.v"]
warning: /home/pi/vlang/v/vlib/net/urllib/urllib.v:117:8: `switch` statement has been deprecated, use `match` instead:
https://vlang.io/docs#match
warning: /home/pi/vlang/v/vlib/net/urllib/urllib.v:156:8: `switch` statement has been deprecated, use `match` instead:
https://vlang.io/docs#match
warning: /home/pi/vlang/v/vlib/net/urllib/urllib.v:210:8: `switch` statement has been deprecated, use `match` instead:
https://vlang.io/docs#match
warning: /home/pi/vlang/v/vlib/net/urllib/urllib.v:697:8: `switch` statement has been deprecated, use `match` instead:
https://vlang.io/docs#match
warning: /home/pi/vlang/v/vlib/net/urllib/urllib.v:917:8: `switch` statement has been deprecated, use `match` instead:
https://vlang.io/docs#match
warning: /home/pi/vlang/v/vlib/net/urllib/urllib.v:1072:8: `switch` statement has been deprecated, use `match` instead:
https://vlang.io/docs#match
check()
next token = `eof`
Segmentation fault
pi@raspberrypi:~/vlang/v/examples/vweb $ ls -al
total 20
drwxr-xr-x 2 pi pi 4096 Oct 27 06:10 .
drwxr-xr-x 9 pi pi 4096 Oct 27 06:09 ..
-rw-r--r-- 1 pi pi    9 Oct 27 05:10 .gitignore
-rw-r--r-- 1 pi pi   28 Oct 27 05:10 index.html
-rw-r--r-- 1 pi pi    0 Oct 27 06:18 test_vweb_app.tmp.c
-rw-r--r-- 1 pi pi  625 Oct 27 05:10 test_vweb_app.v
pi@raspberrypi:~/vlang/v/examples/vweb $

**Comment by medvednikov** [comment]
switch was replaced everywhere
