### ISSUE TITLE
Can't use none / or in enum

### ISSUE THREAD

**Issue by r-k-o** [vlang/v#2544]
**V version:** 
V 0.1.21
**OS:** 
win64
**What did you do?**
enum types {
	string
	cf
	none
}

**What did you expect to see?**
none is usable in enum
 
**What did you see instead?**
expected `}` but got `none`
  187|  none
  188| }

**Comment by medvednikov** [comment]
`none` is a keyword right now. Not sure if that should be changed.

**Comment by r-k-o** [comment]
well, the keyword "string" works in an enum. i think you should change it, since it is used as types.none.

**Comment by medvednikov** [comment]
string is a type, not a keyword

**Comment by medvednikov** [comment]
yeah I'll most likely make `none` a special variable like `it` and `err`

**Comment by r-k-o** [comment]
i think maybe you should allow any word in an enum, as long as it is called with 'enumname.'. 
always hated like modula or others could not distinguish the enum content even when a 'enumname.' was in front, for ex. the none, of it. there was no way to use none or 'or' etc. in more then one enum, but the compiler accepted in an enum all words.

**Comment by medvednikov** [comment]
you can use `@keyword` for names

not sure if it's worth complicating the language like that

**Comment by medvednikov** [comment]
`none` needs to stay a keyword.
