### ISSUE TITLE
error: public generic methods not works

### ISSUE THREAD

**Issue by m5ome** [vlang/v#2547]
**V version:** b6fa252
**OS:** Ubuntu 18.04

**What did you do?**
```v
...

// Not works
pub fn (curl_easy &CurlEasy) setopt<T>(option int, parameter T) {}

// Works
fn (curl_easy &CurlEasy) setopt<T>(option int, parameter T) {}

...

fn main() {
    ch := curl.easy_init()
    ch.setopt(curl.OPT_URL, 'https://www.google.com')
}
```

**What did you expect to see?**
cURL response - successful compilation
 
**What did you see instead?**
check()
next token = `eof`
segmentation fault (core dumped)

**Comment by amalshaji** [comment]
Similar issue [Generics not working in modules](https://github.com/vlang/v/issues/2528)

**Comment by medvednikov** [comment]
Does it work for you now @m5ome ?
