### ISSUE TITLE
string interpolation doesn't work with "

### ISSUE THREAD

**Issue by ssharish** [vlang/v#2550]
**V version:** 
V 0.1.21 cba12d0
**OS:** 
OSX High Sierra

**What did you do?**
```
fn main() {
  aa := 12
  ak := 18

  println("Is AA major? ${aa >= 18}")
  println('Is AK major? ${ak >= 18}')

}
```

**What did you expect to see?**
```
Is AA major? 0
Is AK major? 1
```
 
**What did you see instead?**
```
Is AA major? 0)
  println('Is AK major? 1
```

**Comment by medvednikov** [comment]
String interpolation is broken in "" strings right now.

**Comment by medvednikov** [comment]
Duplicate: https://github.com/vlang/v/issues/2479
