### ISSUE TITLE
OS lib does not remove file (dir rm also not working) - Windows

### ISSUE THREAD

**Issue by aliczin** [vlang/v#2557]
**V version:** master
**OS:** Windows 10 Pro 10.0.18362
**Compiler:** MSVC (VS2019 Preview)

**What did you do?**

```
import os

fn test_must_check_purge_file() {
    tempfile := '.${os.path_separator}thisatmp.file'
    os.create(tempfile)
    os.rm(tempfile)
    file_exist := os.file_exists(created_file)
    assert file_exist == false
}
```

**What did you expect to see?**

* green test ;-)  - and removed temp file
 
**What did you see instead?**

> FAILED: main__test_must_check_purge_base_dir()
> FAIL   312 ms |  1 assert  | test_must_check_purge_base_dir()

File is exist and does not removed

**Comment by joe-conigliaro** [comment]
Hi @aliczin 

The reason your example dosent work is becasue the file handle was never closed, here is a working example:
```
fn test_must_check_purge_file() {
    tempfile := '.${os.path_separator}thisatmp.file'
    file := os.create(tempfile) or {
        panic('error creating file')
    }
    file.close()
    os.rm(tempfile)
    file_exist := os.file_exists(tempfile)
    assert file_exist == false
}
```

**Comment by medvednikov** [comment]
Yes it should @joe-conigliaro

**Comment by aliczin** [comment]
@joe-conigliaro yes - this is fix my test. 

should i create new issue for feature request option return ?
