### ISSUE TITLE
compile error when $ char in used inside string

### ISSUE THREAD

**Issue by metaprem** [vlang/v#256]
Following two programs show **compile error when $ is mentioned in string declaration**.

**compiling Program 1 shows msg:**
test.v:2
unexpected token: ':'

**Program 1**
`

fn main() {
	ss_var := '$:USD'
	println(' Vlang : $ inside string')
	println('ss_var = $ss_var')
}
`

**compiling Program 2 shows msg:**

test.v:3
unhandled sprintf format "void" 

**Program 2**
`
const (
	SS      = 'SS = $SS'
)

fn main() {
	println(' Vlang : Const example')
	println('SS = $SS')
}
`

**Comment by medvednikov** [comment]
Fixed.
