### ISSUE TITLE
Question: AOP Support for Vlib

### ISSUE THREAD

**Issue by keito940** [vlang/v#2563]
Do you create an aspect-oriented domain in the V?

**Comment by nedpals** [comment]
Can you show us some examples of libraries and codes in an aspect-oriented programming? Seems interesting

**Comment by keito940** [comment]
https://www.eclipse.org/aspectj/

**Comment by medvednikov** [comment]
@keito940 this page doesn't have any examples, only this:

```
a seamless aspect-oriented extension to the Javatm programming language
Java platform compatible
easy to learn and use
```

**Comment by keito940** [comment]
Maybe this?
https://www.journaldev.com/2583/spring-aop-example-tutorial-aspect-advice-pointcut-joinpoint-annotations

**Comment by medvednikov** [comment]
I think that's what V tries to avoid: pages and pages of text, XML, classes etc to document a single features, and I still have no clue what it's for.

**Comment by gslicer** [comment]
Looks very hi-lvl and not sure about advantges in non OOP languages, see also:
https://en.wikipedia.org/wiki/Aspect-oriented_programming#Criticism
