### ISSUE TITLE
improve Time resolution (add milliseconds)

### ISSUE THREAD

**Issue by pznknmtb** [vlang/v#2586]
currently Time resolution is 1 second. adding fractional seconds (e.g. milliseconds) would be useful. logging as example could benefit from this enhancement.

**Comment by changrui** [comment]
How about `time.ticks()`?

**Comment by dumblob** [comment]
I'll reuse this issue for tracking the progress on this front. Currently @helto4real works on higher resolution, leap seconds, and maybe daylight saving times, and maybe timezones. For details see:

https://github.com/vlang/v/commit/9c8769503fdd41e8cbcc7a250594f8cdb8794f63#r39743265

Just to cross-reference, there is one timezone-related ticket: https://github.com/vlang/v/issues/3654 from @keito940 which could get addressed by the above-mentioned changes.

**Comment by penguindark** [comment]
Done
