### ISSUE TITLE
C Error when building

### ISSUE THREAD

**Issue by DJonesCode** [vlang/v#2588]
**V version:** 
1.22
**OS:** 
Windows 10 64-bit

**What did you do?**
V failed to compile itself or run the example code

**What did you expect to see?**
"Hello world"
 
**What did you see instead?**

C:\Users\Userl\v>v v.v
Saving the resulting V executable in `./v2`
Use `v -o v v.v` if you want to replace current V executable.
'gcc' is not recognized as an internal or external command,
operable program or batch file.
V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

C:\Users\User\v>v v.v
Saving the resulting V executable in `./v2`
Use `v -o v v.v` if you want to replace current V executable.
'gcc' is not recognized as an internal or external command,
operable program or batch file.
V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

C:\Users\User\v>$ v
'$' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\User\v>v
V 0.1.22 ee6ec3f
Use Ctrl-C or `exit` to exit
>>> println('hello world')
'gcc' is not recognized as an internal or external command,
operable program or batch file.
V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
>>>

**Comment by DJonesCode** [comment]
Yes. I have Visual Studio installed.

**Comment by vitalyster** [comment]
`set VFLAGS=-cc msvc`

**Comment by medvednikov** [comment]
Fixed, V now uses msvc if it fails to find gcc.
