### ISSUE TITLE
Changelog: synchronise GitHub "releases" with "CHANGELOG.md"

### ISSUE THREAD

**Issue by gslicer** [vlang/v#2590]
At the moment of writing of this issue, the file [CHANGELOG.md](https://github.com/vlang/v/blob/master/CHANGELOG.md) and the GitHub [releases-overview](https://github.com/vlang/v/releases) are not in-sync

CHANGELOG.md shall contain the same information as the releases overview (and may even point to the URL on the top of the doc)

**Comment by TheBeachMaster** [comment]
This is a really good idea.


What would be the cost of adding a tool like  :

1. [gren](https://github.com/github-tools/github-release-notes#installation)
