### ISSUE TITLE
Array functions insert() and prepend() do not always work

### ISSUE THREAD

**Issue by avitkauskas** [vlang/v#2599]
Functions `insert()` and `prepend()` do not work and never did, they just were never used and tested. Now tests are added for that but commented out as solution should be implemented in compiler.

The problem is that `insert(`) (and `prepend()` as it's using the former) cannot be called with the literals or any primitive type variables as they cannot be converted to `voidptr`. Similar functions `push()` and `set()` work only because they are not used directly, but are transpiled into C in a special way by compiler implementations of `<<` and `array[] =` assigment, by transforming the argument to `voidptr` in a special way.

Currently `insert()` and `prepend()` would work only if called this way:
```v
a := [1, 2]
n := 3
arr.insert(0, &n)
```
```v
a := [1.1, 2.1]
n := 3.1
a.insert(0, &n)
```
but not
```v
a := [1.1, 2.1]
arr.insert(0, 3.1)
```
```
array_test.tmp.c:8230:33: error: cannot take the address of an rvalue of type 'double'
 array_insert (& /* ? */ a , 0 ,& /*112 EXP:"void*" GOT:"f32" */ 3.1 ) ;
```
As discussed in https://github.com/vlang/v/pull/2596, compiler should be checking for the `voidptr` required by the function parameter and should preformat the argument to convert it to `voidptr` using technique like `&(int[]){ val }` or similar.

**Comment by LorenzoPirro** [comment]
@medvednikov here, i think `insert` isn't buggy, but you need to call it in this way: `insert(0, voidptr(&f))` because C compiler doesn't care about this. In fact:
```
mut vedia := [1.1, 2.1]
f := 3.1
vedia.insert(0, voidptr(&f))
println(vedia)
```
print: ```
➜  nv git:(master) ✗ v run ~/Desktop/coding/ex.v         
[3.100000, 1.100000, 2.100000]
```
