### ISSUE TITLE
Implement assert_panic

### ISSUE THREAD

**Issue by avitkauskas** [vlang/v#2600]
We need a way to check in tests that function panics as designed in some cases.
So it would be good to have keyword (or function) `assert_panic` that would allow to check that in tests.

**Comment by gslicer** [comment]
Would it not be better that assert would return TRUE/FALSE? Then you would just check the result instead need to define another keyword?

**Comment by medvednikov** [comment]
assert already returns `bool`

this is about checking for panics, we can use `assert panic` for that.

**Comment by gslicer** [comment]
No, I meant when assert returns 'false' then you can invoke a panic by yourself or not?

**Comment by medvednikov** [comment]
This is about checking that something panics, not returns false.

**Comment by gslicer** [comment]
ok, I was mistaken then... thanks
