### ISSUE TITLE
Will there be Russian letters in the names of variables and functions?

### ISSUE THREAD

**Issue by Keyn1** [vlang/v#2608]
Задумка шикарная у вас. 
Будет ли русский язык в именах переменных и функций? И русские аналоги ключевых слов?

**Comment by Danil-Lapirow** [comment]
Why do you want to have such a feature?

**Comment by Keyn1** [comment]
потому что удобно писать на своем родном языке. Особенно когда делаешь узко-специализированную разработку (используется внутри твоей страны), и в этой разработке используются профессиональные термины (например медицинские, или нефтегазовая промышленность) Не надо переводить на английский. В языке golang так можно)

because it is convenient to write in your native language. Especially when you do a narrowly specialized development (used within your country), and in this development professional terms are used (for example, medical, or oil and gas industry) Do not need to be translated into English. In the golang language)

**Comment by aliczin** [comment]
@Keyn1 врядли добавят. Подобный функционал в исходно-янглоязычных языках почти никогда не добавляют. Если вы хотите кодить на русском - то вам скорее всего вот сюда http://oscript.io/ (https://github.com/EvilBeaver/OneScript) Там правда C#/Mono. 
Подобную задачу уже пытались решить в balerina-lang - у них была идея кодить на тайском и индийском, но ее также забросили https://ballerina.io/

**Comment by Keyn1** [comment]
Наверное. Просто, как я понял vlang делается на Си. А в Си нет такого. Сложно будет кодировку utf8 прикручивать. А еще программисты Си всю жизнь на ангийском пишут и не видят преимуществ писать все на русском например.

**Comment by medvednikov** [comment]
V  will not support non-ASCII characters in names.

**Comment by medvednikov** [comment]
As for keywords in Russian. Do you really want another 1C? :)

```
Процедура ОбновитьПараметрыОбработчикаОжидания(ПараметрыОбработчикаОжидания) Экспорт
	
	ПараметрыОбработчикаОжидания.ТекущийИнтервал = ПараметрыОбработчикаОжидания.ТекущийИнтервал * ПараметрыОбработчикаОжидания.КоэффициентУвеличенияИнтервала;
	Если ПараметрыОбработчикаОжидания.ТекущийИнтервал > ПараметрыОбработчикаОжидания.МаксимальныйИнтервал Тогда
		ПараметрыОбработчикаОжидания.ТекущийИнтервал = ПараметрыОбработчикаОжидания.МаксимальныйИнтервал;
	КонецЕсли;
		
КонецПроцедуры

```

**Comment by Keyn1** [comment]
Мой первый язык с++ Делали с другом для развлечения базу данных на подобие foxpro на C++Builder. Потом пришлось пересесть на 1С. Сначала было непривычно – все на русском, но позже осознал, что это  очень удобно, и это реально круто   К тому же вы таким свойством можете привлечь к своему языку людей, которые не знают английский, но хотят программировать.   Вообще, ищу язык, на котором можно было бы делать убийцу 1С )) – платформу и конфигурации. 1С написана на с++ и в нее встроен бейсико-подобный язык. Но я думаю, что новая платформа должна быть написана на легком языке типа go или v. И внутренний язык платформы должен быть таким же, на каком написана платформа, этим мы добьемся скорости. Горячая перезагрузка кода,  а вместе с ней много поточность из коробки, эти фичи дадут опять же скорость и гибкость решения. Так же вы отгадали с устранением зависимостей. Работать с базой данных из языка это очень приятно, а работать с графикой из языка это очень круто, и при этом не надо ничего качать. Все есть сразу.               Поэтому да, реально хочу другую 1с. Понравился ваш язык. Удачи)  01.11.2019, 12:34, "Alexander Medvednikov" <notifications@github.com>:As for keywords in Russian. Do you really want another 1C? :)Процедура ОбновитьПараметрыОбработчикаОжидания(ПараметрыОбработчикаОжидания) Экспорт
	
	ПараметрыОбработчикаОжидания.ТекущийИнтервал = ПараметрыОбработчикаОжидания.ТекущийИнтервал * ПараметрыОбработчикаОжидания.КоэффициентУвеличенияИнтервала;
	Если ПараметрыОбработчикаОжидания.ТекущийИнтервал > ПараметрыОбработчикаОжидания.МаксимальныйИнтервал Тогда
		ПараметрыОбработчикаОжидания.ТекущийИнтервал = ПараметрыОбработчикаОжидания.МаксимальныйИнтервал;
	КонецЕсли;
		
КонецПроцедуры

**Comment by salifm** [comment]
@medvednikov 

Can I suggest [transliterating](https://en.wikipedia.org/wiki/Romanization_of_Russian)? It would be really useful. This feature is so underrated in most languages. It can make Vlang more popular.

For example the following V code:

```
Процедура ОбновитьПараметрыОбработчикаОжидания(ПараметрыОбработчикаОжидания) Экспорт
	
	ПараметрыОбработчикаОжидания.ТекущийИнтервал = ПараметрыОбработчикаОжидания.ТекущийИнтервал * ПараметрыОбработчикаОжидания.КоэффициентУвеличенияИнтервала;
	Если ПараметрыОбработчикаОжидания.ТекущийИнтервал > ПараметрыОбработчикаОжидания.МаксимальныйИнтервал Тогда
		ПараметрыОбработчикаОжидания.ТекущийИнтервал = ПараметрыОбработчикаОжидания.МаксимальныйИнтервал;
	КонецЕсли;
		
КонецПроцедуры
```

could be compiled to this, but in C:

```
Procedura ObnovitParametryObrabotchikaOzhidanija(ParametryObrabotchikaOzhidanija) Jeksport
	
	ParametryObrabotchikaOzhidanija.TekushhijInterval = ParametryObrabotchikaOzhidanija.TekushhijInterval * ParametryObrabotchikaOzhidanija.KojefficientUvelichenijaIntervala;
	Esli ParametryObrabotchikaOzhidanija.TekushhijInterval > ParametryObrabotchikaOzhidanija.MaksimalnyjInterval Togda
		ParametryObrabotchikaOzhidanija.TekushhijInterval = ParametryObrabotchikaOzhidanija.MaksimalnyjInterval;
	KonecEsli;
		
KonecProcedury
```
