### ISSUE TITLE
Bootstrapping V on Windows 7 using MinGW fails

### ISSUE THREAD

**Issue by gslicer** [vlang/v#2612]
![v_mingw_gcc_fail](https://user-images.githubusercontent.com/54360532/68019877-332a8380-fc9d-11e9-99e2-3d66e30a9895.png)
**V version:** v0.1.22
**OS:** Win7 Pro

**What did you do?**
make.bat

**What did you expect to see?**
V successfully built
 
**What did you see instead?**
gcc failed to compile

**Comment by gslicer** [comment]
Tried to Workaround by patching v_win.c with:
#define _O_U16TEXT "0x00020000"
#define _O_U8TEXT "0x00040000"

but no luck, v2.exe is giving me:
```
V error: '????????????' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by vitalyster** [comment]
use mingw64 or llvm-mingw, older mingw is not supported

**Comment by gslicer** [comment]
OK, my bad, but not another issue.... (added -v for verbose to the make.bat)
![build_fail](https://user-images.githubusercontent.com/54360532/68033931-0a1bea00-fcc1-11e9-9f3c-87457b2bb78d.png)

**Comment by vitalyster** [comment]
<img width="1291" alt="Screenshot 2019-11-01 at 23 01 13" src="https://user-images.githubusercontent.com/1052407/68052964-ddd18f00-fcfb-11e9-85ab-139c2a698309.png">
Can not reproduce

**Comment by vitalyster** [comment]
```
C:\Users\User\Documents\v>gcc --version
clang version 9.0.0 (https://github.com/llvm/llvm-project.git 0399d5a9682b3cef71
c653373e38890c63c4c365)
Target: i686-w64-windows-gnu
Thread model: posix
InstalledDir: c:\llvm-mingw\bin
```

**Comment by vitalyster** [comment]
https://github.com/mstorsjo/llvm-mingw :)

**Comment by gslicer** [comment]
![grafik](https://user-images.githubusercontent.com/54360532/68383000-18508700-0155-11ea-87e9-fcb9372ec573.png)

Worked! Just needed to Edit one single line in the `make.bat`

`x86_64-w64-mingw32-c99 -v -w -o v2.exe vc\v_win.c`
