### ISSUE TITLE
4 fail of totals of `v test v`.

### ISSUE THREAD

**Issue by changrui** [vlang/v#2615]
**V version:**   v 0.1.22
**OS:** 
Windows 10.
**What did you do?**
`v test v`

**What did you expect to see?**
`21 ok`.
 
**What did you see instead?**
` ok, fail, total =    17,     4,    21`.

**Comment by amalshaji** [comment]
It works fine for me. Please, could you show a detailed report?

**Comment by M4SSD35TRUCT10N** [comment]
@changrui Please provide some kind of log.
E.g. on Windows Commandline with `testvsuite.bat` (you have to set it up by yourself I'm using MSVC):
```
echo Run the whole v test suite...
v -cc msvc test v > test.log
echo Finished! Check log file.
timeout 7
```
And attach log file to this issue. Thanks in advance, your friendly issue janitor.
