### ISSUE TITLE
Can't compile V without interwebs

### ISSUE THREAD

**Issue by radare** [vlang/v#2616]
**V version:** V 0.1.22 7b1993b
**OS:** macOS 10.15

**What did you do?**

```
$ make
rm -rf vc/
git clone --depth 1 --quiet https://github.com/vlang/vc
fatal: unable to access 'https://github.com/vlang/vc/': Could not resolve host: github.com
make: *** [fresh_vc] Error 128
$
```

**What did you expect to see?**

```
V has been successfully built
``` 

**What did you see instead?**
```
make: *** [fresh_vc] Error 128

```

**Comment by Bowero** [comment]
This is correct. During compilation, the original `C` file has to be downloaded. This is maintained in another repository, and therefore needs its own download.

**Comment by medvednikov** [comment]
Don't see a way around it. Even with a git submodule, the clone command has to be changed.

If you need to build it without the Internet, just clone the vc repo.
