### ISSUE TITLE
0 character in a string literal error

### ISSUE THREAD

**Issue by arg2das** [vlang/v#2617]
**V version:** 0.1.22
**OS:** Linux

**What did you do?** Try to print a color that bash understands

**What did you expect to see?** The next text printed in that color

 
**What did you see instead?** This error "0 character in a string literal"

**Comment by medvednikov** [comment]
Can you provide your code?

**Comment by medvednikov** [comment]
Can you provide your code?

**Comment by arg2das** [comment]
here it is

> **println("\033[30;1m")**

**Comment by mvlootman** [comment]
you can take a look at the term module.

```
import term

fn main() {
	println(term.red('red message'))
}
```

**Comment by medvednikov** [comment]
While that definitely works, there's a bug with the 0 char thing that has to be fixed.

**Comment by arg2das** [comment]
ok thanks!

**Comment by medvednikov** [comment]
Fixed.
