### ISSUE TITLE
Temp files being created

### ISSUE THREAD

**Issue by JesterOrNot** [vlang/v#2618]
**V version:** 
Docker image based on debian
and Termux on chrome os
**What did you do?**
started the repl
**What did you expect to see?**

 no new files being added
**What did you see instead?**
![image](https://user-images.githubusercontent.com/50386709/68063626-84a83200-fce0-11e9-9120-7137b1270ea1.png)
![image](https://user-images.githubusercontent.com/50386709/69024486-80d70980-0988-11ea-97ae-46a2ce493149.png)

**Comment by elimisteve** [comment]
Agreed; would be nice to get rid of this :+1:

**Comment by spytheman** [comment]
Fixed in recent builds (after #2778 ).
