### ISSUE TITLE
Automatic formatting mangles up code

### ISSUE THREAD

**Issue by metaprem** [vlang/v#262]
In playground, automatic formatting mangles up code:

Following program gets mangled:

```
const (
	A = 1
	/*B = 2*/
)

fn main() {
	println(A)
}
```

and after compiler auto formats the source code becomes:
```
 const (
	A         = 1
	/*B = 2*/ = fn main() {
	println   =A)	
)
```
![image](https://user-images.githubusercontent.com/18365/59621488-0db53700-914d-11e9-9f11-db34edda2271.png)

**Comment by Bowero** [comment]
We took the Playground offline. You're welcome.
