### ISSUE TITLE
LLVM Backend

### ISSUE THREAD

**Issue by superblaubeere27** [vlang/v#2626]
I don't think there is much to describe. LLVM would be a great backend because it has safe and very good optimizations + safe Assembly generation for every modern CPU. I know that this would kill the lightweight aspect of V, but it also speeds up the compiltation process.

**Comment by medvednikov** [comment]
Compilation won't be sped up, but I'm open to an additional LLVM backend. The C backend will always stay.

**Comment by superblaubeere27** [comment]
For sure the overall compiltation time is less when you do V -> LLVM -> Assembly instead of V -> CLang -> LLVM -> Assembly.
If you want I can try to make a such a backend. The only thing I need to know is how the code suppose to be implemented and where I can add it

**Comment by medvednikov** [comment]
I think it's best to wait for an AST.  @joe-conigliaro did some research, it's at an early stage.

Right now the tokens are stored in a simple array, and C/JS code is generated on the fly.

You could add a new object `Parser.llvm` (similar to `Parser.cgen`), create methods like `llvm.gen_if()` etc, and add them to `Parser.if_statement()` etc.

Of course, the C LLVM wrapper has to be used.

Calling C functions from V is trivial: `C.foo(1, 2)`.

**Comment by medvednikov** [comment]
Don't worry about the performance. V can skip functions, so these new llvm functions won't be called when llvm backend is not used.

**Comment by superblaubeere27** [comment]
Ok. I will wait for AST. Is there a way to see the progress on AST?

**Comment by medvednikov** [comment]
There's no progress yet, @joe-conigliaro just started some tinkering, so it can take weeks or even months.

You can use the current non-AST model using the approach I described.

**Comment by martindecker** [comment]
I like V also because its highly connected to C. 
The C "Platform" including GCC, MsVC is more relevant than LLVM:   
http://sotagtrends.com/?tags=[c,llvm]

For me, V -> C  -> gcc -> Assembly, V -> C  -> msvc -> Assembly and V -> CLang -> LLVM -> Assembly is better than V -> LLVM -> Assembly.  
So just my opinion is:  I do not need a LLVM backed, better make the C translation perfect. 

On the other hand, everyone can do any project with V.

**Comment by joe-conigliaro** [comment]
This is something I'm passionate about, although my reasoning is to simplify the C backend, and see the performance implications, so its a bit of an experiment at the moment. Adding any backed should be easier with and AST model. Time willing I will work on it when I can, and once some features of V are finalised it will make things easier

**Comment by medvednikov** [comment]
@martindecker I  also prefer the C backend, that's why I picked  it in the first place.

Easy bootstrapping, runs on anything, works with existing tools (Valgrind, -Wall -pedantic, PVS, etc).

The C backend will always be there, but I think it's good for the language to have multiple implementations.

Again, I won't be working on this at all, so the primary backend won't suffer.

**Comment by superblaubeere27** [comment]
@martinecker It is possible to use the CLang API to compile header files and check the arguments of C-Calls with the generated Bitcode or with the CLang API itself.

**Comment by superblaubeere27** [comment]
Btw, is there a possibility to derive enums fromd C or to define this Enum? It is imporant that the fields have the same value.
```Cpp
 
 typedef enum {
   LLVMIntEQ = 32, /**< equal */
   LLVMIntNE,      /**< not equal */
   LLVMIntUGT,     /**< unsigned greater than */
   LLVMIntUGE,     /**< unsigned greater or equal */
   LLVMIntULT,     /**< unsigned less than */
   LLVMIntULE,     /**< unsigned less or equal */
   LLVMIntSGT,     /**< signed greater than */
   LLVMIntSGE,     /**< signed greater or equal */
   LLVMIntSLT,     /**< signed less than */
   LLVMIntSLE      /**< signed less or equal */
 } LLVMIntPredicate;
 
```

**Comment by medvednikov** [comment]
@superblaubeere27 if you define your own enum in V, I don't think you can pass it to C functions since they expect LLVMIntPredicate?

**Comment by superblaubeere27** [comment]
@medvednikov yes but is there an alternative?

**Comment by medvednikov** [comment]
@superblaubeere27 I just tested this, and actually it's allowed.

We can define our custom enum type, add the function definition using that type, link, and it'll work:

```
module llvm

enum IntPredicate {
  eq
  ne
  ugt
  ...
}

fn llvm_function(IntPredicate)

...

llvm_function(.eq)
```

Now I just need to implement

```
enum IntPredicate {
  eq = 32
  ...
}
```

**Comment by medvednikov** [comment]
In fact this allows me to get rid of the C. hack entirely.

**Comment by superblaubeere27** [comment]
@medvednikov In the best case it doesn't rely on any headers anymore ;D But now I will have to use just int values or constants to implement it :/ When do you think this is finished?

**Comment by medvednikov** [comment]
@superblaubeere27 I'm working on it right now, so today.

No more #includes, no more C.structs.

Everything will be defined in V.

As for initial enum values, they'll be live within an hour.

**Comment by medvednikov** [comment]
@superblaubeere27 I've just added support for `C.enum { }`

And it turns out @spytheman already implemented custom enum values, I completely forgot about it :)

I didn't manage to remove #include/C.XXX for now, so you'd have to do the following:

```
enum C.IntPredicate {
  eq
  ne
  ugt
  ...
}

fn C.llvm_function(C.IntPredicate)

...

C.llvm_function(.eq)
```

**Comment by gslicer** [comment]
For Windows there is https://github.com/mstorsjo/llvm-mingw/releases

**Comment by superblaubeere27** [comment]
@gslicer So what? What do you mean?

**Comment by gslicer** [comment]
@superblaubeere27 
> So what? What do you mean?
Isn't it using LLVM backend for C code? At least for Windows this option is available right now
> ...but it also speeds up the compiltation process.
how so?

**Comment by superblaubeere27** [comment]
@gslicer First of all using MinGW for LLVM doesn't make sense, you can just download it from https://llvm.org And yes it would speed the whole thing up because the C Backend and the CC Frontend would be skipped

**Comment by gslicer** [comment]
@superblaubeere27 excuse me, now do I understand you correctly that V should generate "intermediate representation" code directly for LLVM?

**Comment by superblaubeere27** [comment]
@gslicer You are damn right

**Comment by medvednikov** [comment]
The development of the llvm backend is now taking place in github.com/vlang/v-llvm
