### ISSUE TITLE
Out of source build of V based projects

### ISSUE THREAD

**Issue by Tembocs** [vlang/v#2629]
Is there a way to do an out of source build using V? I mean having the build artifacts, e.g. executables, written in build directory outside the source directory.

**Comment by adlesh** [comment]
Do you mean like `v -o bin/my_exec src/*.v`? That works for me on linux at least. I can then run the executable using `./bin/my_exec`. It will even build bin/ for you. Although, you only end up w/ a single executable in the end.
![bash output for the above](https://user-images.githubusercontent.com/36427090/68088621-f1314700-fe2e-11e9-884e-a4af56a1fa66.png)

**Comment by Tembocs** [comment]
Thank you so much.
