### ISSUE TITLE
Ctrl-Z doesn't suspend V REPL

### ISSUE THREAD

**Issue by darenliang** [vlang/v#2638]
**V version:** 1.0.22 [b5d457b](https://github.com/vlang/v/commit/b5d457b5cec33412a2d052e355720a514767364b)
**OS:** Fedora 31 (Linux 5.3.7-301.fc31.x86_64)

**What did you do?**
Pressing CTRL-Z in V REPL.

I believe that CTRL-Z works before commit [b5d457b](https://github.com/vlang/v/commit/b5d457b5cec33412a2d052e355720a514767364b), however, it seems like `suspend` is not called from `analyse` in file `readline_linux.v`.

```v
fn (r Readline) analyse(c int) Action {
  match c {
    ...
    26    { return .suspend } // CTRL + Z, SUB
    ...
  }
}
```

```v
fn (r mut Readline) suspend() {
  C.raise(C.SIGSTOP)
  r.refresh_line()
}
```

**What did you expect to see?**
I expect the REPL process to be suspended.
 
**What did you see instead?**
The REPL process hangs and doesn't suspend.

**Comment by sereg1k** [comment]
**V version:** 0.1.22 [b4e8989](https://github.com/vlang/v/commit/b4e8989bd1544048931cec25c40656c75f9f63dc)
**OS:** Slackware 14.2 x86_64

I confirm the problem. The console hangs and does not respond to keystrokes.

**Comment by Henrixounez** [comment]
Yes, it was broken when the SIGINT (^C , Ctrl-C) has been added back.

The suspend function is called, but the raise with `SIGSTOP` or `SIGTSTP` is blocked by the terminal with the `C.ISIG` argument in the `tcsetattr` in `enable_raw_mode` (`man 3 tcsetattr`)

The weird thing is that the suspend works great when launching directly the REPL by hand : `./tools/vrepl v` in terminal.
It is probably a problem with calling the REPL through a `os.system` call in the main v program (As REPL is now a program on its own as a tool).

Having made slight changes like that in the file have kind of improved the thing (Tap twice ^Z and it suspends well), but need to investigate more...

In `vlib/readline/readline_linux.v`
Changed all `C.TCSADRAIN` to `C.TCSANOW` and modified suspend function :
```
fn (r mut Readline) suspend() {
  r.disable_raw_mode()
  C.raise(C.SIGSTOP)
  r.enable_raw_mode()
  r.refresh_line()
}
```
