### ISSUE TITLE
The online playground is back!

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#2649]
https://vlang.io/play

<img width="770" alt="Screen Shot 2019-11-04 at 23 44 58" src="https://user-images.githubusercontent.com/687996/68169229-6b231680-ff7c-11e9-9ecb-713106152f8b.png">

**Comment by sikim0726** [comment]
Nice work!

**Comment by ouuan** [comment]
It seems that the online IDE doesn't support tab indent.

**Comment by medvednikov** [comment]
@ouuan 

> It seems that the online IDE doesn't support tab indent.

Fixed.

**Comment by blueway** [comment]
Maybe it's better to highlight the grammar

**Comment by medvednikov** [comment]
@blueway agreed, but this will take some time to implement. Not a priority right now.

**Comment by Rhymond** [comment]
@medvednikov thanks for the playground!
@blueway I submitted PR for vlang syntax highlighting to highlight.js
https://github.com/highlightjs/highlight.js/pull/2267

If it gets accepted and merged we can use it later in playground.

**Comment by medvednikov** [comment]
Nice, thanks @Rhymond
