### ISSUE TITLE
Casting from int, float, string to bool gives strange results or bugs

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#2653]
**V version:** 
V Playground.

**OS:** 
N/A

**What did you do?**
```V
fn main() {
    a := 10.2
    println(bool(a))
}
```

**What did you expect to see?**
1 (true)
 
**What did you see instead?**
10

What's more, defining a := 10 and then converting it to bool give "10". Defining a := "hello" and then converting it to bool give "You just found a bug. V can't compile this program, but it should. Please create a GitHub issue".

**Comment by medvednikov** [comment]
Fixed:

```
cannot cast a number to `bool`
```

**Comment by medvednikov** [comment]
In fact, nothing can be cast to `bool` now.
