### ISSUE TITLE
Operation "int % float" gives bugs 

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#2662]
**V version:** 
V playground

**OS:** 
N/A

**What did you do?**
```V
fn main() {
    println(3%1.2)
} 
```

**What did you expect to see?**
An error
Or a result (eg, in Python)
 
**What did you see instead?**
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

**Comment by LorenzoPirro** [comment]
@SleepyRoy actually for floating-point remainder you need `math.fmod(3, 1.2)`.

**Comment by SleepyRoy** [comment]
@LorenzoPirro Thanks. So I think "3%1.2" should simply gives an error (actually "1.2%3" is handled correctly). Also it might be better that the compiler suggests turning to the math module to do this. @medvednikov

**Comment by LorenzoPirro** [comment]
@SleepyRoy you're welcome! Yes could be useful

**Comment by avitkauskas** [comment]
Yes, that has to be fixed. I noticed the error is not cought by V compiler only when you use the literal of the right-hand side. If you assign it to the variable first then try `%` it gives you an error as expected. Somebody will fix it. Thanks for the issue.

**Comment by medvednikov** [comment]
Fixed.
