### ISSUE TITLE
"%=" cannot correctly handle types other than int 

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#2666]
**V version:** 
V playground

**OS:** 
N/A

**What did you do?**
```V
fn main() {
    mut a := 10.5
    a %= 3
    println(a)
} 
```

**What did you expect to see?**
An error because non-int is involved in %=
 
**What did you see instead?**
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

**What's more, seems that any "type_a %= type_b" where at least one type is not int gives this bug.**

**Comment by darenliang** [comment]
The mod assign operator %= should be used for integers only.

You would need to use the `fmod` function from the `math` module to find the mod of floats.

```v
import math

fn main() {
    mut a := 10.5
    a = math.fmod(a, 3)
    println(a)
} 
```

**Comment by avitkauskas** [comment]
Exactly, @darenliang. That's why @SleepyRoy reports the issue that V compiler does not catch this wrong usage of % and does not report an error, but passes it to C compiler which refuses to compile the code.

**Comment by darenliang** [comment]
Oh my bad, I've misread the question. I see the problem now.

Yeah, the compiler should catch the error.

**Comment by SleepyRoy** [comment]
@avitkauskas Yes, that's exactly my point.
@darenliang My fault. I didn't make it clear.

**Comment by gslicer** [comment]
what happens is that we get a correct err-msg from the C compiler:
```
prog.tmp.c:5148:5: error: invalid operands to binary expression ('f32' (aka 'float') and 'int')
 a  =  3 ;
 ~  ^   ~
1 error generated.
````

**Comment by SleepyRoy** [comment]
BTW, just tested some cases on playground and seems this has been fixed.
@darenliang Thanks for your work!
