### ISSUE TITLE
Many illegal operations between two strings are not correctly handled

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#2667]
**V version:** 
V Playground

**OS:** 
N/A

**What did you do?**
```V
fn main() {
    println("hello"-"world")
} 
```

**What did you expect to see?**
An error.
 
**What did you see instead?**
You just found a bug. V should either compile this program or return an error. Please create a GitHub issue.

** This issue also applies to many other operators, such as *, /, &&, ||, &, |, ^, ...

**Comment by medvednikov** [comment]
Fixed.

**Comment by SleepyRoy** [comment]
@medvednikov Nice! But just tried and seems that "str*str" and "str/str" still give a bug.
