### ISSUE TITLE
Bitwise operators (&, |, ^) do not correctly handle floats

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#2668]
**V version:** 
V playground

**OS:** 
N/A

**What did you do?**
```V
fn main() {
    println(1 & 0.5)
} 
```

**What did you expect to see?**
An error. Bitwise operators cannot process non-ints.
 
**What did you see instead?**
You just found a bug.

I'm like a "boring" bug finder who only cares about these trivial things :P. 
But I do think eliminating these elementary bugs is necessary.

**Comment by LorenzoPirro** [comment]
@SleepyRoy on this i disagree. In fact you could do `11 & 12` for example, that is `8` (and bit-to-bit), useful in some contexts.

**Comment by medvednikov** [comment]
Fixed.

> I'm like a "boring" bug finder who only cares about these trivial things :P.
> But I do think eliminating these elementary bugs is necessary.

No, this is important. Thanks for reporting these.

**Comment by SleepyRoy** [comment]
@medvednikov & and | have been fixed, but ^ not.
