### ISSUE TITLE
using 0.8 gives error : malformed octal constant

### ISSUE THREAD

**Issue by metaprem** [vlang/v#267]
using 0.8 gives error : malformed octal constant

```
const (
	F1 = 0.8
)

fn main() {
	println(F1)
}
```

output:
```
test.v:2
malformed octal constant
```

![image](https://user-images.githubusercontent.com/18365/59709938-88518580-9225-11e9-81ae-4e57f42c5d21.png)

**Comment by medvednikov** [comment]
Fixed.
