### ISSUE TITLE
Crash when converting parsed URL to string

### ISSUE THREAD

**Issue by thecodrr** [vlang/v#2670]
**V version:** 
V 0.1.22 425c9ce

**OS:** 
Manjaro Linux 

**What did you do?**
Ran this code:

```v
import net.urllib
fn main(){
	url := urllib.parse("https://en.wikipedia.org/wiki/Brazil_(1985_film)") or {
		panic("unable to parse URL")
	}
	println(url.str())
}
```

**What did you expect to see?**
The program should output escaped string
 
**What did you see instead?**
The program crashed with `Terminated by signal 139 (SIGSEGV)`

**Comment by medvednikov** [comment]
Fixed.
