### ISSUE TITLE
Should we restrict "goto" in V? 

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#2683]
I believe goto as a controversial reserved word in languages deserves some discussion. 

My opinion is keeping it as sometimes it's really necessary and elegant, eg jumping out from multiple loops - Python doesn't have it so I had to use other ugly ways to achieve that.
```Python
# Not very elegant code, but it's the most elegant way I know in Python
def func():
    for i in range(10):
        for j in range(10):
            if condition:
                return i, j
pos1, pos2 = func()
```

The focus of debates about goto is that some programmers consider it a potentially abused/misused word, although I never see real programmers do that. 

**Anyway, should we restrict goto? And if so, to what extent? For example, one idea is to only allow goto jumping backwards. See the following examples.**
```V
// Nice use eg 1: Jumping backwards
for i in 0..10{
    for j in 0..10{
        if condition {goto label}
    }
}
label:

// Nice use eg 2: Jumping backwards
if condition_1 {goto cleanup}
...
if condition_2 {goto cleanup}
...
if condition_n {goto cleanup}
cleanup:

// Bad use eg: Jumping forwards
label:
for i in 0..10{
    for j in 0..10{
        if condition {goto label}
    }
}

```

**Comment by thecodrr** [comment]
Why not simply `break` out of loops and use `else/if` for conditions? using `goto` makes the code much less predictable; readability and execution wise.

While `goto` seems convenient, it can quickly become a headache as the code base becomes more complicated.

**Comment by medvednikov** [comment]
There are some low level cases where goto is necessary. It was also added for compatibility with C (when I was working on translating DOOM).

**Comment by SleepyRoy** [comment]
@thecodrr Yes, combining "break" and "if" is a common way to deal with multiple jumping-outs. But in my opinion this style is not very elegant - The programmer must read and understand the additional "if" code and logic. In contrast, using goto gives a very explicit and easy-understanding signal.
So I think the best way is placing some restrictions on goto rather than completely forbidding it.

**Comment by SleepyRoy** [comment]
@medvednikov I also think goto is necessary, but some restrictions on it may facilitate a good programming style. Do you think my idea of just allowing backwards goto jumps is a possible solution?

**Comment by servusDei2018** [comment]
Goto, despite its criticisms, is still a useful statement nonetheless. Like any statement, it can be over-used or used improperly, but a language shouldn't impose a particular programming style on its users.
