### ISSUE TITLE
Mixed output on printing long numbers

### ISSUE THREAD

**Issue by Waqar144** [vlang/v#2684]
**V version:** 0.1.22 d279ec
**OS:** Linux 64 bit

**What did you do?**
I am looking into porting zip lib to V, and was testing a few things. Got this:
```
 fn a (a u64) {
	println(a) 
}
fn main() {
	x := 0xFFFFFFFF
	println(x) //output -1
	println(0xFFFFFFFF) //output  -1
	a(0xFFFFFFFF) //output  4294967295

       println(0xFFFFFFFFFF) // output 1099511627775
	y := 0xFFFFFFFFFF
	println(y) //output 1099511627775

       println(4294967295) //output -1
       println(4294967294) //output -2
       println(42949672951) //output 42949672951

}
```

**What did you expect to see?**
```
x := 0xFFFFFFFF
println(x) // output 4294967295
println(0xFFFFFFFF) // output 4294967295
```
 
**What did you see instead?**
```
x := 0xFFFFFFFF
println(x) // output -1
println(0xFFFFFFFF) // output -1
```

**Comment by thecodrr** [comment]
This seems due to wrong type inference of numbers at compile time.

**Comment by bogen85** [comment]
Need to know the what the rules are for determining the integer sizes at compile time. How this issue addressed should also affect how some of the remainder of #2876 is addressed.

**Comment by nedpals** [comment]
Closed. The above code now requires to be explicitly casted to `i64`. Otherwise, the compiler will emit an error. The output (with `i64` casted) now returns the right result. See: https://devbits.app/play/KmmvDSj59JkM
