### ISSUE TITLE
Poll: syntax for appending an element to an array

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#269]
Right now V uses Ruby's `<<` for appending an element to an array. Some people think it goes against the design of the language.

Which one do you prefer?

https://twitter.com/v_language/status/1141054110843715584

*edit*

This used to have a gh-polls.com poll, but it allows voting multiple times, so I replaced it with a Twitter poll.

**Comment by metaprem** [comment]
.append is missing from the poll

.push sounds stackish, like pushing on top of stack. 

 .push, .pop works for stack and queue structures

.append seems more natural compared to .push

**Comment by medvednikov** [comment]
Twitter only allows 4 options...

**Comment by data-man** [comment]
I haven't Twitter's account so `array.append(value)` +1

**Comment by joe-conigliaro** [comment]
I think push, add, or append. But would prefer as a method on array, eg array.append(item) rather than append(array, item). I didnt mind the << syntax either but it does look like a bitwise operator.

**Comment by whoizit** [comment]
actually `array.add(val)` seems like the best choice for me

**Comment by boomlinde** [comment]
If it is a method, I don't see any issues with using a method-like syntax. If it's not a method, it shouldn't look like a method.

**Comment by ntrel** [comment]
&gt; array.add(val)

That could mean add val to each element in the array. It also doesn't imply where val will be put, front or back.

**Comment by proyb6** [comment]
A clearer method could be written:
.push_left
.push_right
.pop_left
.pop_right

**Comment by ntrel** [comment]
Re: concatenation, D uses `~` and `~=` for append. But given that concat is O(n) (and always allocates), I'd go with a variadic function `join(s1, s2, s3)`. Using functions for this and append also avoids having to implement operator overloading.

**Comment by ntrel** [comment]
Another advantage for append as a method instead of an operator is that it can accept multiple arguments, like Go `append`. This is more efficient as it can pre-allocate.

**Comment by whoizit** [comment]
```
.rpush()
.lpush()
```
https://redis.io/commands/rpush

**Comment by dcurrie** [comment]
> Another advantage for append as a method instead of an operator is that it can accept multiple arguments, like Go `append`. This is more efficient as it can pre-allocate.

The expression parser (disclaimer: I haven't seen it) should be able to recognize a sequence of append or concatenate operators and combine them into one allocation.

**Comment by ntrel** [comment]
> recognize a sequence of append or concatenate operators and combine them into one allocation

That works for arrays, but for structs with overloaded append, concat operators it would have to lower the operations to a variadic method.

**Comment by SleepyRoy** [comment]
In this case of single element operation I prefer methods to operators. According to V's documentation, "(for operator overloading) Both arguments must have the same type (just like with all operators in V)". Clearly using operators here violates this rule.
The names of methods are not very important to me. Different people have their preferred names of methods. If we decide a "proper" name for every method, it may cost several years (LOL). I wouldn't mind compromising on a specific name. So, "array.append(val)" is OK. I also like the idea of .lpush, .lpop, .rpush, .rpop, because when inserting or deleting an element at end you're indeed using arrays as stacks or queues. Here "push" and "pop" words help programmers to imagine the process.

**Comment by joe-conigliaro** [comment]
> Another advantage for append as a method instead of an operator is that it can accept multiple arguments, like Go `append`. This is more efficient as it can pre-allocate.

I agree it should accept multiple arguments

**Comment by MaxUNof** [comment]
`array << val or array += val` +1

**Comment by garf** [comment]
`<<` looks like byte operator. If everywhere is used `.`-notation, better to keep it consistent, so not to guess how to use anything. `<<` can be added as a syntactic sugar maybe.
