### ISSUE TITLE
Ability to call variadic functions without any arguments

### ISSUE THREAD

**Issue by thecodrr** [vlang/v#2698]
Currently if you call a variadic function without any arguments, it results in quite a verbose error.
e.g.
```v
fn variadic(args ...string){}
fn main(){
   variadic() //error
}
```
Either this should be handled properly i.e. output a proper error that you cannot call a variadic function without arguments or **vargs should be treated as an array** and should default to an empty array in case there are no arguments.

**Comment by medvednikov** [comment]
Indeed, your example should work.

**Comment by medvednikov** [comment]
Fixed.
