### ISSUE TITLE
Any plans on reducing the C dependency from vlib?

### ISSUE THREAD

**Issue by thecodrr** [vlang/v#2699]
While looking through the `vlib` code I see `C interop` in almost every module. Even `println` basically calls `C.printf`. I just wanted to ask if there were any plans in the future to make `V` fully independent or at least partially (in)dependent.

Just curious.

I think [dlang](https://dlang.org/) already does something like this:

> D compiles naturally to efficient native code.
D is designed such that most "obvious" code is fast and safe. On occasion a function might need to escape the confines of type safety for ultimate speed and control. For such rare cases D offers native pointers, type casts, access to any C function without any intervening translation, manual memory management, custom allocators and even inline assembly code.

Again, just curious : )

**Comment by medvednikov** [comment]
You can't avoid libc on on non-Linux systems, since it's their only official API   :)

**Comment by medvednikov** [comment]
Everything that uses unstable/private syscalls is going to keep using libc, things like `sprintf` will be replaced with native V code.

**Comment by thecodrr** [comment]
Okay great!
