### ISSUE TITLE
Bug with compile-time if

### ISSUE THREAD

**Issue by servusDei2018** [vlang/v#2704]
**V version:** V Playground

**OS:** V Playground

**What did you do?**
Code:
 ```v
$if windows {
	println('Windows')
}
$if linux {
	println('Linux')
}
$if mac {
	println('macOS')
}

$if debug {
	println('debugging')
}
```

**What did you expect to see?**
A compilation.
 
**What did you see instead?**
```
You just found a bug. V should either compile this program or return an error. 

Please create a GitHub issue.

This program has been saved, and the bug will be fixed asap.
```

**Comment by darenliang** [comment]
This indeed throws a C error and needs to be fixed.

However, if the code is embedded into a main() function, there is no error.

```v
fn main() {
	$if windows {
		println('Windows')
	}
	$if linux {
		println('Linux')
	}
	$if mac {
		println('macOS')
	}
	$if debug {
	println('debugging')
	}
}
```

**Comment by outersky** [comment]
I compiled with:

`v -debug test.v`

but it cannot print 'debugging'

**Comment by outersky** [comment]
> I compiled with:
> 
> `v -debug test.v`
> 
> but it cannot print 'debugging'

Sorry，I was misleaded by the document: 
`Compile time if starts with a $. Right now it can only be used to detect an OS or a -debug compilation option.`

`-debug` should be `-g`

**Comment by medvednikov** [comment]
This due to the fn main bug. Duplicate.
