### ISSUE TITLE
Interfaces don't work at all

### ISSUE THREAD

**Issue by thecodrr** [vlang/v#2706]
Some issues regarding interfaces: #354 #2377 #1914

Consider this code for future reference:
```v
interface Speaker{
speak() string
}
struct Dog{}
struct Cat{}
// Dog & Cat implement Speaker
```

To summarize:

1. Interfaces don't work with arrays so doing this doesn't work:
```v
mut speakers := Speaker[]
speakers << Dog{}
```
2. Functions where return type is an interface results in compile error:
```v
fn get_speaker(sound string) Speaker {
   if (sound == "meow"){return Cat{})
   return Dog{}
}
```
3. Interfaces can't be used in `map`s:
```v
mut speakers := map[string]Speaker
speakers["meow"] = Cat{}
speakers["woof"] = Dog{}
```
4. Interfaces don't work in structs:
```v
struct MasterSpeaker{
    mut:
    speaker Speaker
}
mut master_speaker := MasterSpeaker{}
master_speaker.speaker = Cat{}
```

Interfaces currently only work in `function` arguments.

**Comment by medvednikov** [comment]
Yes, this is WIP @thecodrr.

I'm re-writing interfaces and adding features. You can track the progress in interface_test.v.

**Comment by toonsevrin** [comment]
Seconded, please close this issue once they work again :)

**Comment by nedpals** [comment]
2020 Update: 1 and 2 now works while the rest are still not working.
