### ISSUE TITLE
Support bare metal target

### ISSUE THREAD

**Issue by Towtow10** [vlang/v#2708]
I think v would be a well suited language for bare metal development.
The target would simply need to produce c code that does not utilize any OS dependent things such as the hosted parts of the standard library.
The non-hosted parts or "freestanding" parts include, <float.h>, <iso646.h>, <limits.h>, <stdalign.h>, <stdarg.h>, <stdbool.h>, <stddef.h>, <stdint.h>, and <stdnoreturn.h>.
The c code could then be compiled to the desired architecture by defining a particular c cross-compiler.

**Comment by medvednikov** [comment]
Yes, there will be `-novlib` and `-nolibc` flags.

**Comment by medvednikov** [comment]
Done:

https://github.com/vlang/v/issues/2761
