### ISSUE TITLE
Bad/missing error message when trying to instantiate interfaces

### ISSUE THREAD

**Issue by omermizr** [vlang/v#2709]
**V version:** V playground
**OS:** V playground

**What did you do?**
I tried to declare and initialize a variable as an interface - which is not a valid code:
```v
interface Helloer{
	hello() string
}
z := Helloer{}
```

**What did you expect to see?**
I expected to see a clear error saying that I can't instantiate an interface.
 
**What did you see instead?**
- Without a `main` function, I got this message: `redefinition of 'z'`
- With a `main` function, I got this message: `You just found a bug. V should either compile this program or return an error. 
`

**Comment by Ivo-Balbaert** [comment]
In the Playground, this now gives the error message:

error: cannot instantiate interface `Helloer` 

so that is good.

However in Windows 10 the same code compiles without error in v 0.1.27

**Comment by spytheman** [comment]
The checker produces this error on all systems now:
```
ii.v:4:6: error: cannot instantiate interface `Helloer`
```
