### ISSUE TITLE
playground: JSON example fails

### ISSUE THREAD

**Issue by whilei** [vlang/v#2721]
**What did you do?**
Go to https://vlang.io/play, run `JSON encoding/decoding` example.

**What did you expect to see?**
Working output.

 
**What did you see instead?**
![Screenshot_20191110_103431](https://user-images.githubusercontent.com/10228550/68546591-d8cca980-03a5-11ea-9850-076c091d2381.png)

**Comment by medvednikov** [comment]
Fixed.
