### ISSUE TITLE
defer doesn't work with optionals

### ISSUE THREAD

**Issue by Delta456** [vlang/v#2722]
**V version:https://github.com/vlang/v/commit/73bd82e70642eb6f6098342dea11454a1031a3b0** 
**OS: Linux** 

**What did you do?**
```go
fn foo(str int) ?bool {
   
  if (str == 1){
    println('yay')
    return true
 }
  else {
  return error('why?')
}

}


fn main() {
println('test')

defer {

 foo(-1) or {panic(err)}
}
	
} 
```

**What did you expect to see?**
Successful compilation
 
**What did you see instead?**
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

**Comment by LorenzoPirro** [comment]
@Delta456 it works on MacOS 10.15.1, i've tried in many ways

**Comment by Delta456** [comment]
@LorenzoPirro can you show?

**Comment by LorenzoPirro** [comment]
of course. Instead of panic, try to print a message (for example `println('err checked')`, my output with your code is: 
```
nv git:(master) ✗ v run ~/Desktop/coding/my.v                               
test
err checked
```
The same is if you call a function inside `or` block.

**Comment by Delta456** [comment]
Can you compile https://github.com/vlang/v/pull/2718 with changes suggested by @spytheman and try if repl is working for you?

**Comment by Ivo-Balbaert** [comment]
The code now (v 0.1.27) compiles and works as expected on Windows 10 and Ubuntu 20:

fn foo(str int) ?bool {
	if str == 1 {
		println('yay')
		return true
	} else {
		return error('why?')
	}
}

fn main() {
	println('test')
	defer {
		foo(-1) or {
			panic(err)
		}
	}
}

test
V panic: why?

With
print_backtrace_skipping_top_frames_mingw is not implemented  on Windows 10

and a backtrace on Ubuntu.

However the Playground still shows:
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.
What version is Playground, perhaps update to v.0.1.27
Then this issue can be closed I think.
