### ISSUE TITLE
how to cast string to integer?

### ISSUE THREAD

**Issue by fauzipadlaw** [vlang/v#273]
I tried this
```
fn main() {
	a := '1'
	b := '2'
	println(int(a) + int(b))
}
```
Output: `You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.`

**Comment by medvednikov** [comment]
`a.to_i() + b.to_i()`

**Comment by nikeee** [comment]
It seems that it's now `a.int()`:
https://github.com/vlang/v/commit/48d65d6881833a001cb4416e259319ce856460b0

`to_i` doesn't seem to exist any more.

**Comment by medvednikov** [comment]
indeed

**Comment by dadooda** [comment]
Hi guys. Is there a way to convert with an optional `Result` in case format is incorrect? Say,

```v
'10'.int()    // 10
''.int()      // error('bad format or something')
```

**Comment by JalonSolov** [comment]
Try `strconv.atoi()`
