### ISSUE TITLE
tests_assertions.v doesn't exist

### ISSUE THREAD

**Issue by thecodrr** [vlang/v#2738]
**V version:** 

**OS:** 
Manjaro Linux

**What did you do?**
`v module_test.v`

**What did you expect to see?**
Tests should run and show result.
 
**What did you see instead?**
`V error: /home/thecodrr/Sources/Repos/v/vlib/compiler/preludes/tests_assertions.v doesn't exist`

The file exists at the path and opens in VSCode without any issues.

**Comment by spytheman** [comment]
Please update v to latest version, and try to reproduce it. Does it happen always?

**Comment by medvednikov** [comment]
Fixed, finally.

Thanks @spytheman

**Comment by thanhngch** [comment]
I've got this error. I don't found folder `compiler` in `vlib` folder.

**Comment by medvednikov** [comment]
@thanhngch I see, the prebuilt packages don't have `vlib/compiler`. Will fix today.
