### ISSUE TITLE
Expand memory management documentation

### ISSUE THREAD

**Issue by boomlinde** [vlang/v#274]
Memory management in the documentation is illustrated by an example which shows a case where no manual memory management is necessary. The other is an example of an array, which is freed by a free method.

There is no other information on how the programmer can differentiate between cases where manual memory management is necessary and where it isn't, other than that leaks will be reported at run-time.

For example, can you put a struct on the heap (outside an array) and then free it with a function? Will interpolated strings have to be freed if they are much larger than the ones in the example? Is the "sum" of two strings a new string that can end up on the heap?

In general, I wonder what the long term plans for heap memory management are. I'd prefer manual memory management with optional automatic reference counting. That would set it apart from Go (memory management through GC) and Rust (memory management through complex lifetime policy and optional reference counting).

The less I have to think of special cases like that in the interpolated string example, the better.

**Comment by medvednikov** [comment]
Yes, it will be well documented. It's at a very early stage right now.

> The less I have to think of special cases like that in the interpolated string example, the better.

That's one of the main goals. Never make developers think about things like this.
