### ISSUE TITLE
V Test suite fails

### ISSUE THREAD

**Issue by M4SSD35TRUCT10N** [vlang/v#2742]
**V version:** 
**OS:** Windows 10 1809

**What did you do?**
v -cc msvc test v

**What did you expect to see?**
All test marked ok.
 
**What did you see instead?**
V panic: V tool "e:\Program Files\vlang\v\tools\vtest.v" could not be compiled
`Files\vlang\v\tools\vtest.v` does not exist
print_backtrace_skipping_top_frames is not implemented on this platform for now...

It seems that a recently fixed problem with paths with spaces reoccurred (#1847).

EDIT: I added @joe-conigliaro because he fixed it the last time.

**Comment by joe-conigliaro** [comment]
Thanks will check this out!
