### ISSUE TITLE
REPL breaks on 'unexpected token'

### ISSUE THREAD

**Issue by SilvanCodes** [vlang/v#2746]
**V version:** 
V 0.1.22 10b0432
**OS:** 
Ubuntu 18.04.3 LTS

**What did you do?**
Entering `println(if 3*8 % 32 == 0 { 0 } else { 1 })` into the REPL.
Then continuing to use it.

**What did you expect to see?**
I expected the output of my expression (1 in that case) which I got.
 
**What did you see instead?**
Subsequent calls to he REPL errored with```.vrepl_temp.v:2:1: unexpected token: `}` ```

**Comment by LorenzoPirro** [comment]
On MacOS 10.15 it works. Output:
```
>>> println(if 3*8 % 32 == 0 { 0 } else { 1 })
1
```

**Comment by SilvanCodes** [comment]
@LorenzoPirro Could you still use the REPL afterwards? The initial call succeeds as stated in the description. But for me it is not possible to continue using the REPL.

**Comment by LorenzoPirro** [comment]
@SilvanCodes ok, maybe i've found the problem. The repl read all the `println` and it stops itself at `1`. So when you write an other command, whatever it is, it will fail. I've tested also other commands

**Comment by nedpals** [comment]
Closed. It works now on the latest version of V, on Ubuntu 20.04:

```
For usage information, quit V REPL and run `v help`
V 0.1.28 c0a0949
Use Ctrl-C or `exit` to exit
>>> println(if 3*8 % 32 == 0 { 0 } else { 1 })
1
```
