### ISSUE TITLE
enum example does not work?

### ISSUE THREAD

**Issue by lcddh** [vlang/v#2757]
**V version:** 
V 0.1.22 5166352
**OS:** 
win10
**What did you do?**
```
enum Color {
	red green blue
}
fn main() {
	mut color := .red
	println('why')
}
```

**What did you see instead?**
![image](https://user-images.githubusercontent.com/5841609/68788784-099b3000-067f-11ea-958b-97e766851732.png)

**Comment by medvednikov** [comment]
You need to use the full name when declaring an enum. It's actually in the example:

```
mut color := Color.red
assert color == .red
```

I'll make the error better.

**Comment by lcddh** [comment]
println(color) // "1"  TODO: print "green"? 
this code seems does not work
