### ISSUE TITLE
V now runs on bare metal!

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#2761]
No libc or vlib.

From now on V can be used for embedded, kernel development, etc.

<img width="592" alt="Screen Shot 2019-11-14 at 11 28 49" src="https://user-images.githubusercontent.com/687996/68841087-ffa41c00-06d4-11ea-9167-cc91c3b2fb22.png">

**Comment by dumblob** [comment]
I recently came about the utter need for `volatile` in *V*. @medvednikov is there any chance of supporting it somehow?

There are still few ways (e.g. `&` and `*`) in *V* how one can do pointer arithmetic in *V* (**even outside of `unsafe{}` block** :cry:), so getting an address of a register mapped to memory on an embedded device should be pretty straightforward, but how to specify it's a register (i.e. volatile) to avoid caching in any cache?

**Comment by medvednikov** [comment]
@dumblob a new keyword can be added just for this, similar to `static`. Search for `key_static`, it's very easy to implement.

**Comment by dumblob** [comment]
`volatile` became part of *V* - see https://github.com/vlang/v/pull/11940 . Thanks!
