### ISSUE TITLE
Can not use bitwise OR on enum

### ISSUE THREAD

**Issue by Towtow10** [vlang/v#2762]
**V version: 0.1.22 34c4565** 
**OS: Linux** 

**What did you do?**
Tried using a bitwise OR on two enum values

**What did you expect to see?**
The two enum values would have a logical inclusive OR done on them
  
**What did you see instead?**
An error stating that | is reserved for integers:
`operator | is defined only on integer types`

**Comment by medvednikov** [comment]
Enum fields have to be explicitly cast to `int`, like in Rust:

```
enum Foo {
bar, baz
}

int(Foo.bar) | int(Foo.baz)
```
