### ISSUE TITLE
`No write(...) defined` while test bare!

### ISSUE THREAD

**Issue by changrui** [vlang/v#2765]
**V version:** 
V 0.1.22

**OS:** 
`Windows 10`

**What did you do?**
`test bare`.
`write(1, c'Hello!\n', 7)`.

**What did you expect to see?**
`Hello!`
 
**What did you see instead?**
undefined: `write`.

**Comment by medvednikov** [comment]
It only works on Linux for now.

**Comment by changrui** [comment]
oh, No! wsl under Windows 10, not Windows 10.

**Comment by medvednikov** [comment]
WSL should be fine. Make sure you use `v -bare foo.v`

**Comment by changrui** [comment]
OK, thanks. @medvednikov

**Comment by changrui** [comment]
It's running well, thx.
