### ISSUE TITLE
Bitness

### ISSUE THREAD

**Issue by ciubotaru** [vlang/v#2766]
At this stage the language makes it possible to write platform-dependent code (using compile-time $if and platform identifier). However, it is still bitness-agnostic (and endianness-agnostic, but that would be a separate feature request).

As the author of the 'bitfield' module, I would appreciate being able to optimize my code for different processor word sizes (primarily, 64 bit). Specifically, it should be possible to create type aliases pointing to u32 or u64, depending on system bitness.

**Comment by medvednikov** [comment]
How would the syntax look like? `if x64 {` ?

**Comment by ciubotaru** [comment]
Currently, none of the following snippets compile:

````
$if x64 {
    type foo u64
} else {
   type foo u32
}
...
struct foo {
    $if x64 {
        field []u64
    } else {
        field []u32
   }
}
...
$if x64 {
    struct foo {
        field []u64
    }
} else {
    struct foo {
        field []u32
    }
}
````
Is it intended? If so, what would be the correct usage of `$if x64`?

**Comment by Delta456** [comment]
@ciubotaru what's the output of your code?

**Comment by ciubotaru** [comment]
> what's the output of your code?

First snippet (architecture-dependent type alias) fails with this:
````
$> unexpected token: `type`
$if x64 {
    type foo u64
         ^
````
Second snippet (architecture-dependent structure element):
````
$> expected `name` but got `$`
struct foo {
    $if x64 {
      ^
        field []u64
````
Third snippet  (architecture-dependent structure):
````
$> unexpected token: `struct`
$if x64 {
    struct foo {
            ^
````
