### ISSUE TITLE
cli: v run arguments handled as command

### ISSUE THREAD

**Issue by timbasel** [vlang/v#2770]
**V version:** 0.1.22 e577b40
**OS:** Arch Linux 5.3.8

**What did you do?**
Executing a v script using `v run` with arguments that match other `v` commands

```v
// main.v
module main
import os
fn main() {
  println(os.args[1])
}
```
```bash
v run ./main.v version
```

**What did you expect to see?**
```
version
```
 
**What did you see instead?**
```
V 0.1.22 e577b40
```

Looking at `v.v` I think arguments should not be handled with an `in` statement but sequentially and passing all further aguments to the handling function after a match.

**Comment by medvednikov** [comment]
You are right, the flags module has to be used instead.

**Comment by timbasel** [comment]
Shall I take a shot at fixing this?

**Comment by medvednikov** [comment]
That'd be great.

**Comment by timbasel** [comment]
I have taken a look at the flag module and I think in the current form that would not fix the issue. It still looks at all arguments when parsing a flag and would therefore also handle arguments that should be passed to the script.
I could write a quick fix (see example below) or we should think about extending the flag module to also handle command-like arguments first.

```v  
fn main() {
  args := os.args
  for i, arg in args.right(1) {
    match arg {
    '-v', '--version', 'version' {
      println('V $compiler.Version')
      return
    }
    'run' {
      mut v := compiler.new_v(args.right(i+2))
      v.compile()
      v.run_compiled_executable_and_exit()
    }
  }
}
```

**Comment by serkonda7** [comment]
Works fine with latest V.
