### ISSUE TITLE
os.mkdir: *nix implementation of mkdir not recursive

### ISSUE THREAD

**Issue by Cheapskate01** [vlang/v#2771]
**V version:** 0.1.22
**OS:** Linux (untested on mac, but willing to bet it does the same)

**What did you do?**
`os.mkdir('pdirectory/subdirectory')`

**What did you expect to see?**
Expected recursive creation of nonexistent parent directory followed by subdirectory, as windows has.
 
**What did you see instead?**
No directory was created at all, no error thrown.

**Comment by LorenzoPirro** [comment]
@Cheapskate01 use `mkdir_all`. Actually on unix `mkdir` doesn't work

**Comment by M4SSD35TRUCT10N** [comment]
`os.mkdir()` should simply work on all platforms.

**Comment by Larpon** [comment]
`os.mkdir(path)` = `mkdir path`
`os.mkdir_all(path)` = `mkdir -p path`
Just re-open if this is still relevant 🙂
