### ISSUE TITLE
The V community started working on vOS!

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#2775]
https://github.com/vlang/vos

If you are interested, join the development :)

This is not  another toy OS project. vOS will be fully compatible with Linux with its great hardware and software support.

Planned key features:

- Unix-like microkernel
- [V](https://github.com/vlang/v) is the primary language
- Full compatibility with Linux (syscalls, drivers, binaries etc)
- Compiles in <1 second
- Stable syscall API
- x64
- ELF binary format
- Official GUI toolkit in V UI
- pacman package manager

Brainstorming started on November 15 2019.

Join the [Discord chat](https://discordapp.com/invite/n7c74HM) (`#v-os` channel).

**Comment by motss** [comment]
What's the main goal of the project?

**Comment by dumblob** [comment]
This kind of reminds me of [TempleOS](https://en.wikipedia.org/wiki/TempleOS ) (in a good sense). TempleOS is actually quite an [interesting system](https://templeos.org/ ) - [latest release](https://github.com/minexew/TempleOS ) - written in [HolyC](https://rosettacode.org/wiki/Category:HolyC ), but there seem to be no use for such system except of course fun :wink:.

**Comment by lutherwenxu** [comment]
This issue has been closed due to the inactivity.
Please reopen this issue if you want to continue the discussion.
