### ISSUE TITLE
Calling higher order functions in structs

### ISSUE THREAD

**Issue by timbasel** [vlang/v#2779]
**V version:** 0.1.22 e577b40
**OS:** Arch Linux 5.3.8

**What did you do?**
Call a higher order function stored in a struct
```v
module main

struct Test {
	func fn()
}

fn main() {
	test := Test{print_func}
	test.func()
}

fn print_func() {
	println('Hello World')
}
```

**What did you expect to see?**
```bash
Hello World
```

**What did you see instead?**
```
test.v:9:20: unexpected token: `)`
    7| fn main() {
    8|  test := Test{print_func}
    9|  test.func()
                  ^
   10| }
```

The problem only happens when you call the function directly from the struct. If you store the higher order function in a local variable it is callable.

```v
fn main() {
	test := Test{print_func}
	op := test.func
	op('Hello World')
}
```
```bash
> v -o main main.v && ./main
Hello World
```

If the higher order function takes variables there is no compile time error but the function does not get called.

**Comment by LorenzoPirro** [comment]
@timbasel maybe it's correct, because if `test.func()` was possibile, defining a `func()` method would give your same error and it would be unacceptable. Define a struct field of function type should be used only for store it, i think

**Comment by timbasel** [comment]
I don't see why function shadowing would be a problem in this case. I my mind the stored function can only every be called together with `test.` in front of it. So if you define a `func()` method there is nothing to shadow. But it could be that I'm missing a point.

And if so, the bug is in the descriptive error message.

**Comment by Ivo-Balbaert** [comment]
The top code example now (V 0.1.27 33a9822) works on Windows 10 and Ubuntu 20, outputting:
Hello World
