### ISSUE TITLE
would be nice to have arrays, string interpolation, and concatenation working with standalone (aka bare)

### ISSUE THREAD

**Issue by bogen85** [vlang/v#2789]
Currently array and string support is limited with standalone (no libc, syscalls only).

The underlying component that seems to be missing for these is a memory allocater.

musl-malloc and TLSF were mentioned as possible code references.

**Comment by bogen85** [comment]
http://man7.org/linux/man-pages/man2/mmap.2.html
mmap with MAP_ANONYMOUS can be used for allocations in page sized chunks.

https://stackoverflow.com/questions/34042915/what-is-the-purpose-of-map-anonymous-flag-in-mmap-system-call

**Comment by bogen85** [comment]
I ran into problems with the musl-malloc as I had to modify too much of the source to get it build.
I ended up going with https://github.com/mjansson/rpmalloc

I still need to add a few missing functions and test it.

**Comment by bogen85** [comment]
I got mjansson/rpmalloc working in standalone mode (only modification to sources was that I disable TLS)
https://github.com/bogen85/vector-box
I've still got some more tests to add and I need to test it from V as well.

**Comment by bogen85** [comment]
my standalone malloc/free are debugged and tested. I have a test program that makes sure allocations don't overlap and that every page gets mapped in correctly.

**Comment by penguindark** [comment]
Memory management in progress.
Obsolete issue.
