### ISSUE TITLE
optional return with only error

### ISSUE THREAD

**Issue by jtkirkpatrick** [vlang/v#2793]
**V version:** vlang.io playground 
**OS:** android

**What did you do?**
```v
fn thing() ?int {
       return error('no')
}

fn main() {
        x := thing()?
        println('ok')
} 
```

**What did you expect to see?**
Panic with 'no'. 
 
**What did you see instead?**
V can't compile this program, but it should.

**Comment by donnisnoni95** [comment]
Works fine on me... it successfully compiled... And of course, it will automatically call `panic('no')`

**Comment by donnisnoni95** [comment]
Maybe it would be better to place it here [vlang/wesbsite](https://github.com/vlang/website)

**Comment by medvednikov** [comment]
It works locally, seems to be a playground issue.

**Comment by Ivo-Balbaert** [comment]
The following program compiles but doesn't print anything, also no panic exit

fn thing() ?int {
       return error('no')
}

fn main() {
        x := thing()?
				println(x)
        println('ok')
} 

On the Playground it compiles, also prints nothing:

**Comment by nedpals** [comment]
Closing this as the old playground has been retired.
