### ISSUE TITLE
Implement low-level locks eg: for bare-metal/freestanding

### ISSUE THREAD

**Issue by nsauzede** [vlang/v#2802]
Writing an OS in V requires (obviously) low-level locks, ie: not based off pthread lib, like sync.Mutex.

Several ideas have been proposed :
1. First idea
```
lock {
foo()
bar()
}
```
=> but it's tricky
to figure out on which group of vars to lock

2. a `lock <function declaration> { }` and `lock { vars... }` and `lock { <multiple vars/ functions> }` would be nice
the lock would be asserted each time any of the locked block's members are accessed.

=> but tricky to implement
because you can have a combined access
in different blocks

3. name the locks
`lock my_lock {    }`
so any time something inside the lock is used you'd acquire `my_lock`
and it's also more flexible than having unnamed locks

4. an even better idea would be having the `lock` keyword as a modifier and being able to use it on single variables (would just create a lock named after the variable, like `x_lock` for instance (dumb example)) but most importantly you could use `lock` on structs and that would act the same way as we were saying before
with the advantage that the lock itself does not have to be named, it would be a hidden element of the struct itself which the compiler acquires and releases whenever said struct's element are accessed
with special caution when it comes to a function within the struct accessing or calling other parts of the struct

**Comment by adlesh** [comment]
I really like #3 👍 I think #4 is interesting, but I feel #3 is more achievable w/ current system.

**Comment by dumblob** [comment]
Partially related: https://github.com/vlang/v/issues/2761#issuecomment-621329529

**Comment by penguindark** [comment]
At the present time are implemented in `sync` module:
- channels
- semaphore
- wait groups
- mutexes
