### ISSUE TITLE
Interface method name `register` gets renamed to `v_register`

### ISSUE THREAD

**Issue by tundrax** [vlang/v#2805]
**V version:** V 0.1.22 94b3625
**OS:** macOS 10.14.6 Mojave

**What did you do?**
Created an interface with a method named `register`. Implemented method in a struct.

**What did you expect to see?**
Successful compilation.
 
**What did you see instead?**
Interface method gets renamed to `v_register` and compiler complains about not satisfying the interface.

**Comment by medvednikov** [comment]
Fixed.
