### ISSUE TITLE
Error accessing arguments of array of references

### ISSUE THREAD

**Issue by timbasel** [vlang/v#2809]
**V version:** 0.1.22 e577b40
**OS:** Arch Linux 5.3.8

**What did you do?**
I tried creating an array of references and accessing it's length. 
e.g.
```v
module main

import os

struct Test {
mut:
	array []&Test
}

fn main() {
	mut obj0 := Test{}
	obj1 := Test{}
	obj0.array << &obj1
	println(obj0.array.len)
}

```

**What did you expect to see?**
Get the number of items (number of stored references) in the array

**What did you see instead?**
```
bad arr array_Test*
bad arr array_Test*
example.v:14:23: dot(): cannot find type `[]Test*`
   12|  obj1 := Test{}
   13|  obj0.array << &obj1
   14|  println(obj0.array.len)
                               ^
   15| }
```

I don't know if it should be possible to create an array like that (not only storing references to struct of the same type, but in general), but for the current way I implemented the `vlib/cli` 
WIP version it would necessary to work correctly.

**Comment by donnisnoni95** [comment]
```v
module main

struct Test {
mut:
	array []Test
}

fn main() {
	mut obj0 := Test{}
	obj1 := &Test{}
	obj0.array << *obj1
	println(obj0.array.len)
}
```

**Comment by timbasel** [comment]
yes I have, but unfortunately that changes the references. In `vlib/cli` I need the reference to the subcommand that was originally added, so that any changes (adding flags and args) can also accessed there.

**Comment by timbasel** [comment]
Here is a stripped down version of the current `vlib/cli`. The problem is that the arguments do not get set on the subcommand outside the execute function. It is not a complete dealbreaker but it makes writing test rather complicated and is in my mind just unclean. What I try to achieve is to store a reference to the original command instead of creating a new one. But changing the code in that way results in the above mentioned error. :cry: 

```v
module main

pub struct Command {
pub mut:
	name string
	execute fn(cmd Command)

	parent &Command
	subcommands []Command
	args []string
}

pub fn (cmd mut Command) add_command(command Command) {
	cmd.subcommands << command
}

pub fn (cmd mut Command) parse(args []string) {
	cmd.args = args.right(1)
	for i := 0; i < cmd.subcommands.len; i++ {
		cmd.subcommands[i].parent = &cmd
	}

	for i := 0; i < cmd.args.len; i++ {
		arg := cmd.args[i]
		for j := 0; j < cmd.subcommands.len; j++ {
			mut subcommand := cmd.subcommands[j]
			if subcommand.name == arg {
				subcommand.parse(cmd.args.right(i))
				return
			}
		}
	}

	// if no further command was found execute current command
	if int(cmd.execute) != 0 {
		execute := cmd.execute
		execute(cmd)
	}
}

fn main() {
	mut cmd := Command{name: 'example'}
	subcmd := Command{name: 'subcommand', execute: subcommand_func}
	cmd.add_command(subcmd)

	cmd.parse(['example', 'subcommand', 'arg0', 'arg1'])

	println('Outside func: ${subcmd.args} (ref: ${&subcmd})')
}

fn subcommand_func(subcmd Command) {
	println('Inside func: ${subcmd.args} (ref: ${&subcmd})')
}
```

**Comment by Ivo-Balbaert** [comment]
The top code example given works now (V 0.1.27 33a9822) on Windows 10, Playground and Ubuntu 20, outputting 1.

module main and import os are redundant.

it also works with:
struct Test {
mut:
	array []Test
}
