### ISSUE TITLE
Add VPATH and improve the way how modules work.

### ISSUE THREAD

**Issue by gabixdev** [vlang/v#2813]
As the title says - add VPATH variable (and preferably a command line options to use in environments where we can't set them).

- VPATH should be looked first - looking up global module directory would break projects horribly.
- there MUST be an option to disable global directory lookup
- having ability to specify multiple directories would be nice (separated by `:` or `;` on Windows)

How it would work?
`import module` should import all .v files from `$VPATH/module`, if multiple directories were specified, it should look up them in from first to last one specified and the compilation should fail if no such directory was found or there were no .v files in it.

I'm not sure about name enforcement of modules.
1. `module <name>` in all source files could differ from directory name but they MUST be consistent across all .v files
2. same as above, except the directory name would be enforced as well.

**Comment by changrui** [comment]
All module not all .v files will be loaded when `import <mod>`.

**Comment by medvednikov** [comment]
@gabixdev good to close this now?

**Comment by gabixdev** [comment]
Yeah
