### ISSUE TITLE
Struct reference lost during interface call

### ISSUE THREAD

**Issue by htmue** [vlang/v#2814]
**V version:** 0.1.22
**OS:** macOS, Apple LLVM version 10.0.1 (clang-1001.0.46.4)

**What did you do?**
```v
struct Int {
    value int
}
fn (i Int) get() int {
    return i.value
}
interface Getter {
    get() int
}
fn get_value(g Getter) int {
    return g.get()
}

i := Int { value: 1 }
println(i.get() == 1)
println(get_value(i) == 1)
```

**What did you expect to see?**
```
% v run example.v
true
true
```
 
**What did you see instead?**
```
% v run example.v
true
false
```

**Solution:**

In the generated C code I found this:
```c
void* (* Getter_name_table[][1]) = { {Int_get},  }; 

int
Int_get (Int i)
{
  return i.value;
}

int
main__get_value (Getter g)
{
  return   ( ((int (*)())(Getter_name_table[g._interface_idx][0]))(g._object) ) ;
}
```
This cannot work. `int Int_get(Int i)` is cast into `int Int_get()` without argument and nothing is passed to it at all.

It works with a helper function in the vtable, for example like this:
```c
int
Int_get_ptr (Int *i)
{
  return Int_get (*i);
}

void *(*Getter_name_table[][1])(void *) = { {Int_get_ptr}, };

int
Int_get (Int i)
{
  return i.value;
}

int
main__get_value (Getter g)
{
  return (((int (*)(void *)) (Getter_name_table[g._interface_idx][0])) (g._object));
}
```
This code leads to the expected result.

I don't have the time to go through the compiler to change it accordingly, hope this helps anyway.

I like this language and would like to use it!

**Comment by cloudsong** [comment]
temp solution: 
change 
```
fn (i Int) get() int {
    return i.value
}
```

to 

```
fn (i &Int) get() int {
    return i.value
}
```

interface-call all will pass reference of receiver

```
return (((int (*)(void *)) (Getter_name_table[g._interface_idx][0])) (g._object));
```

int (*)(void *)  is a cdecl call, caller will push all params into stack and pop it after call
and all func's call-type is cdecl by default
so, the above statement works temporarily

**Comment by htmue** [comment]
This works, thanks! The docs say "You no longer need to remember whether you should pass the struct by value or by reference." , though. So it will be fixed, I guess (you call it a "temp solution")?

**Comment by htmue** [comment]
Hm, it still doesn't work as described in the docs. Don't know why the bug is closed. Will you leave interfaces as a case where the programmer *has* to remember to pass a struct by reference?
