### ISSUE TITLE
compile error when using match

### ISSUE THREAD

**Issue by arylee** [vlang/v#2818]
**V version:**  V 0.1.22 26fb7e0
**OS:** Ubuntu 19.10

**What did you do?** compiling below code
```v
fn main() {
       number := 0
        s := match number {
                1    { 'one' }
                2    { 'two' }
                else {
                        println('this works too')
                        'many'
                }
        }
        println(s)
}
```

**What did you expect to see?**
Nothing, which means compile successful.

 
**What did you see instead?**
```bash
match.v:16:9: expected type `string`, but got `void`
   14| 		else {
   15| 			println('this works too')
   16| 			'many'
             		^
   17| 		}
   18| 	}
```

**Comment by Ivo-Balbaert** [comment]
Same on Windows 10 with latest v

**Comment by Jictyvoo** [comment]
For me this is a logic error, because you are using match like a ternary operator. So, compiler os taking first line in else, and comparing It return type, which ia void.

**Comment by Ivo-Balbaert** [comment]
Yes, this indeed seems how it is computed right now, causing this error. But the else code block should be computed entirely.

**Comment by takkyuuplayer** [comment]
```v
// foo.v
fn main() {
    s := match 1 {
        1 {
            println(1)
            "one"
        }
        else { "other" }
    }
}
```

$ v run foo.v

```
foo.v:6:9: syntax error: unexpected `'one'`, expecting `}`
    4|             println(1)
    5|             "one"
    6|         }
               ^
    7|         else { "other" }
    8|     }
next token = `}`
```

If I remove assignment, `s := `, it compiles successfully

**Comment by nedpals** [comment]
I believe its more of a logical error than a syntax one. A helpful compiler message will do and little bit of adjustment in the way `match` is explained inside the docs (which must be reported to [vlang/website](https://github.com/vlang/website) in this case).

**Comment by ka-weihe** [comment]
Works in V 0.1.26 50a8373
