### ISSUE TITLE
V doesn't handle missing external C dependencies

### ISSUE THREAD

**Issue by lkesteloot** [vlang/v#2819]
**V version:** 0.1.22 01dc267
**OS:** macOS 10.14.6

**What did you do?**

* `git clone git@github.com:vlang/v.git`
* `cd v`
* `make`
* `./v run examples/tetris/tetris.v`

**What did you expect to see?**

Successful compilation or normal error due to missing dependency.
 
**What did you see instead?**

```
/private/var/folders/62/ccpssrcd4fn8c99z3wjb9m9c0000gn/T/v/tetris.tmp.c:196:10: fatal error: 'ft2build.h' file not found
#include "ft2build.h"
         ^~~~~~~~~~~~
1 error generated.
V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

It might be because I've not installed the graphics dependencies (freetype?), but then the bug is that the compiler says "This should never happen". Instead it should recommend installing a dependency. Or just say that a file is missing. But don't imply an internal compiler error.

**Comment by medvednikov** [comment]
The readme says that freetype has to be installed with `brew install freetype`.

You are right, this error should be handled by V.

**Comment by lkesteloot** [comment]
Also, note that users (like myself) will follow the README top to bottom, and the instructions about freetype come _after_ the command to run Tetris. So one of the first things I saw when experimenting with V was an internal compiler error. Maybe move the freetype instructions above the tetris command to avoid this impression that V is broken.

**Comment by smichea** [comment]
exact same error on windows
```
builder error: Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28610.4 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-mwindows'
tetris.tmp.c
C:\Users\owner\AppData\Local\Temp\v\tetris.tmp.c(568): fatal error C1083: Cannot open include file: 'ft2build.h': No such file or directory
````

**Comment by medvednikov** [comment]
This should be fixed now.

Make sure you use the latest build from source.

**Comment by smichea** [comment]
Yes thank you !
had to run  "v setup-freetype" though.

**Comment by medvednikov** [comment]
freetype is no longer used on Windows, will double check.
