### ISSUE TITLE
Is V depending on a C compiler?

### ISSUE THREAD

**Issue by ofunc** [vlang/v#282]

**Comment by medvednikov** [comment]
V can emit both C code and machine code directly, as explained on the home page.

Right now emitting C code is a lot more stable, so that's what is used by default. Emitting machine code directly will be available later this summer.

**Comment by YevhenKap** [comment]
@medvednikov emitting directly machine code is great future, so I and perhaps others will wait for stability in compiling to machine code. You are doing great job! Hope the language will be famous)
