### ISSUE TITLE
structs are in fn main() by default in vlang.io/play causing this error

### ISSUE THREAD

**Issue by dps910** [vlang/v#2820]
**V version:** 
0.1

**OS:** 
browser

**What did you do?**
Clicked run on https://vlang.io/docs#mod in methods, and got this error `unexpected token: 'struct'
    1| fn main() {`

**What did you expect to see?**
struct not being in a function
 
**What did you see instead?**
struct in a function

**Comment by Ivo-Balbaert** [comment]
The example cited in the link now probably is:

struct User {
    age int
}

fn (u User) can_register() bool {
    return u.age > 16
}

user := User{age: 10}
println(user.can_register()) // "false"

user2 := User{age: 20}
println(user2.can_register()) // "true"

This code now(V 0.1.27 33a9822) works both in the Playground and locally.
