### ISSUE TITLE
Building to js fails with segmentation fault

### ISSUE THREAD

**Issue by benob** [vlang/v#2828]
**V version:** 
8e32ef3

**OS:** 
linux

**What did you do?**
`$ v -o test.js test.v`
(with a trivial test.v)

**What did you expect to see?**
test.js shall be generated

 
**What did you see instead?**
```
$ v -o test.js test.v
failed to create /v/test.js.tmp.c
Segmentation fault (core dumped)
```

**Workaround**
It seems that os.tmpdir() generates a bad filename when targeting js. A fix consists in setting TMPDIR before compiling.
`$ TMPDIR=/tmp v -o test.js test.v`

**Comment by serkonda7** [comment]
works fine with recent V.
