### ISSUE TITLE
Hot Reload Issue

### ISSUE THREAD

**Issue by lego3708** [vlang/v#2837]
**V version:** V 0.1.22 8e32ef3
**OS:** Windows 10 64-bit

**What did you do?**
I tried to run a file with `v -live hotreload.v`

**What did you expect to see?**
I expected it to run
 
**What did you see instead?**
```
warning: hotreload.v:1:6: the following imports were never used:
 * time
compiling shared library took 625 ms
=========

C:\Users\*****\AppData\Local\Temp\v\hotreload.tmp.c: In function 'main':
C:\Users\*****\AppData\Local\Temp\v\hotreload.tmp.c:3889:12: warning: pointer targets in passing argument 1 of 'load_so' differ...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

**Comment by emily33901** [comment]
Can you test this again and maybe use `-g` - not sure whether that is a warning or an error or both?

**Comment by lego3708** [comment]
> Can you test this again and maybe use `-g` - not sure whether that is a warning or an error or both?

It's an error, because it says `C Error`, and the code didn't run

**Comment by emily33901** [comment]
Well the C error appears to be a warning (`C:\Users\*****\AppData\Local\Temp\v\hotreload.tmp.c:3889:12: warning:`) but its possible that there is more than 1 thing in that `...` in the warning so either way it would be useful

**Comment by emily33901** [comment]
Unless someone knows otherwise im closing this for being probably out of date.
