### ISSUE TITLE
How to skip update checking?

### ISSUE THREAD

**Issue by choleraehyq** [vlang/v#284]
```
➜  v_macos ./v --help
Checking for updates... (soon this will only be done once per day)
^C
➜  v_macos ./v --version
Checking for updates... (soon this will only be done once per day)
Sorry, an Internet connection is required
```
Without internet connection, I can't do anything about v, including reading its version info... It's a little bit ridiculous.

**Comment by flfy** [comment]
This also slows down program compilation time, checking for an updating and waiting for it to update in the case if it being out of date slows everything down. Please add an option to completely disable it.

**Comment by medvednikov** [comment]
I'll fix this in about an hour. It will only check for updates once per day.

**Comment by medvednikov** [comment]
The build has been pulled. It'll be released with the source on June 22: https://github.com/vlang/v/issues/287

But for those 850 of you who downloaded V for macOS and don't want to be bothered by the update check, here's a secret hack to remove it:

`touch /var/tmp/alex`

But don't tell anyone!
