### ISSUE TITLE
/./'" not working

### ISSUE THREAD

**Issue by ghost** [vlang/v#2844]
https://vlang.io/play : The V Playground
Windows 10

![Bug](https://user-images.githubusercontent.com/56685150/69419269-6bf9cd80-0d1c-11ea-8bdf-8ac276c7870d.JPG)

Expected Output:
`Hello, Steve."` 
 `Hi, Steve."`
 `Good morning, Steve."`

**Comment by AlexDyukov** [comment]
There is an error only with `println("\"")`
![Untitled](https://user-images.githubusercontent.com/21895986/69429075-cce8cc00-0d43-11ea-8aba-b42ff2ceb057.png)

**Comment by gslicer** [comment]
I'm a bit confused what the playground is telling to the user:

```
You just found a bug. V should either compile this program or return an error. 

!?!?!!?!? Please create a GitHub issue. !!?!?!!?!?!?!?

This program has been saved, and the bug will be fixed asap.
```

So, in such case it shall be sufficient that this faulty program has been saved and shall land in some testing vault, it shall be not necessary for the user to report the problem manually as an GH-Issue in addition to this.

**Comment by penguindark** [comment]
Solved
