### ISSUE TITLE
Delete in map and in operator

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#2847]
**V version:** V 0.1.22 c11025f (latest Nov 22)
**OS:** 
Windows 10, Linux and PlayGround

**What did you do?**
Run the following code:
```
fn main() {
    mut m := map[string]int
    m['one'] = 1
    m['two'] = 2
    println(m['two']) // => "2"  
    m.delete('two')
    println(m['two']) // => 0
    println('two' in m) // => true, on Linux  and Windows  <-- wrong !
}
```

**What did you expect to see?**
The output of println('two' in m) should be false, because the key 'two' has been deleted
 
**What did you see instead?**
The output of println('two' in m) is true

**Comment by medvednikov** [comment]
Fixed.
