### ISSUE TITLE
Is is possible to include prebuilt library in v package?

### ISSUE THREAD

**Issue by hanabi1224** [vlang/v#2848]
e.g. If I want to create a package that binds to lz4 c library, is it possible to ship prebuilt (dynamically linked) .dll / .so / .dylib files along with the package? Or is there way to include c source code and cross compile? Thanks!

**Comment by thecodrr** [comment]
@hanabi1224 V combines all the C headers and other files that are included and used in a project so there's no need for .o or .dll etc. The output is a single binary which can be run anywhere.

**Comment by hanabi1224** [comment]
@thecodrr Thanks!  Is there any example on how to reference c source file? The document shows examples of referencing .h file which I thought was to link to system library

**Comment by thecodrr** [comment]
You'd include it like you include it in any C project.
`#include "file.c"`

**Comment by hanabi1224** [comment]
@thecodrr How does V search for the file?  I tried to place .c file next to .v one but it complains .c file not found

**Comment by thecodrr** [comment]
It is relative to the main.v file.

**Comment by hanabi1224** [comment]
@thecodrr Just flat directory (created via v create), everything is in the same folder

**Comment by donnisnoni95** [comment]
@hanabi1224 add `c flag to your module`
```v
#flag -I @PWD/path_to_c_folder
```
 `path_to_c_folder` is the relative path to the folder where you put your c files
`@PWD` is  ENV variable, its a path to the current working directory

**Comment by hanabi1224** [comment]
@donnisnoni95 Thanks!

**Comment by donnisnoni95** [comment]
@hanabi1224 But it's not the best option. user must build it before they using it

**Comment by hanabi1224** [comment]
@donnisnoni95 Since vlang uses C as backend, it works as a glue language by nature, it will be great to have detailed documentation on how to build a V lib with existing C source code and how to expose C APIs from vlang for other VM based languages to invoke

**Comment by hanabi1224** [comment]
In rust, it's very easy to build a lib from existing C code / make extensions with safe rust code / expose C api to other VM based launguages.
e.g. https://github.com/bozaro/lz4-rs  which builds a rust lz4 library from official C code

**Comment by donnisnoni95** [comment]
Try to look at this https://github.com/nsauzede/vsdl2
