### ISSUE TITLE
is_dir vs dir_exists

### ISSUE THREAD

**Issue by radare** [vlang/v#2853]
**V version:** V 0.1.22 57fbf0b
**OS:** macOS 10.15

**What did you do?**

cleanup the os api

**What did you expect to see?**

an api change decission
 
**What did you see instead?**

Imho we should keep is_dir and kill dir_exists. also i miss other methods like is_file or is_symlink, iis there any decision on that?

```
$ git grep os.is_dir|wc -l
      14
$ git grep os.dir_exists|wc -l
      27
$
```
<img width="802" alt="Screenshot 2019-11-23 at 02 26 49" src="https://user-images.githubusercontent.com/917142/69470749-f97b0300-0d98-11ea-8d32-d19aaee9dfce.png">

**Comment by medvednikov** [comment]
Yes, I agree. One of them must go.

I'll think about it.

**Comment by radare** [comment]
imho we should just keep is_dir(), and add is_file() is_symlink() ...

**Comment by gslicer** [comment]
I think "is directory?" >> "directory exists?", if a file is a directory then it must exist at the same time, so dir_exists can entirely be replaced by the other.

**Comment by medvednikov** [comment]
Then file_exists should be renamed to is_file, but I prefer file_exists.

**Comment by medvednikov** [comment]
I've removed dir_exists, renamed file_exists to exists, and added is_link().

**Comment by gslicer** [comment]
Simple question, should is_link() differentiate between hard- and symbolic-links?
