### ISSUE TITLE
cannot import module "compiler"

### ISSUE THREAD

**Issue by ricardoboss** [vlang/v#2861]
**V version:** - (trying to compile from master)
**OS:** Windows 10 Pro (1909)

**What did you do?**
Executed `v up` from cmd.

**What did you expect to see?**
v.exe compiled successfully.
 
**What did you see instead?**
```
(git update log)
Current branch master is up to date.
Building V
git version 2.24.0.windows.2
Downloading v.c...
Attempting to build v.c with GCC...
Now using V to build V...
v.v:8:10: cannot import module "compiler" (no .v files in "S:\repos\vlang\v\compiler")
    6|
    7| import (
    8|  compiler
                  ^
    9|  benchmark
   10|  os
Der Befehl "v3.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
v.exe failed to compile itself - Create an issue at 'https://github.com/vlang'
```

**Comment by ricardoboss** [comment]
Had to reclone the v repository.

**Comment by medvednikov** [comment]
@ricardoboss this was actually a legit bug. You'd get this error if you had old `compiler/` directory in the root.

I've fixed it in the makefile.
