### ISSUE TITLE
Slicing strings

### ISSUE THREAD

**Issue by radare** [vlang/v#2862]
**V version:** V 0.1.22 57fbf0b
**OS:** macOS 10.15

**What did you do?**

try to slice a string inistead of using substr()

**What did you expect to see?**

```
$ v
V 0.1.22 57fbf0b
Use Ctrl-C or `exit` to exit
>>> println("foobar"[2:4])
ob
>>>
```

**What did you see instead?**

```go
$ v
V 0.1.22 57fbf0b
Use Ctrl-C or `exit` to exit
>>> a:="foobar"
>>> a[2:4]
check()
next token = `4`
expected `]` but got `:`
>>> a.substr(2,4)
>>> println(a.substr(2,4))
ob
>>>
```

**Comment by nedpals** [comment]
The syntax for slicing strings is now `'foobar'[2..4]`.

**Comment by thecodrr** [comment]
@radare Please close this if the solution provided works.

**Comment by radare** [comment]
``
$ v
V 0.1.22 1f93bb5
Use Ctrl-C or `exit` to exit
>>> "foobar"[2..4]
expected `)` but got `[`
check()
next token = `2`
>>> 'foobar'[2..4]
expected `)` but got `[`
check()
next token = `2`
>>> a:='foobar'
>>> a[2..4]
ob
```

**Comment by radare** [comment]
please reopen , the issue s there, the [..] syntax only works on variables, not literal strings

**Comment by radare** [comment]
actually there are some more funny errors when doing oneliners in V:
```
>>> "1,2,3".split(",")[1]
expected `name` but got `1`
check()
next token = `]`
>>> string("1,2,3").split(",")[1]
cannot cast `string` to `string`
>>>
```

**Comment by thecodrr** [comment]
You should make a separate issue for each or make this a general issue that deals with all the issues with strings.
