### ISSUE TITLE
Default value/Optional arguments

### ISSUE THREAD

**Issue by radare** [vlang/v#2863]
**V version:** V 0.1.22 3a6ccf7
**OS:** macOS 10.15

**What did you do?**

```go
fn opt(foo int = 3) {
        println(foo)
}

fn main() {
        opt()
        opt(4)
}
```
**What did you expect to see?**

```
3
4
```
 
**What did you see instead?**

```
$ v match.v
check()
next token = `3`
match.v:1:18: expected `name` but got `=`
    1| fn opt(foo int = 3) {
                        ^
    2| 	println(foo)
    3| }
```

**Comment by nedpals** [comment]
Default argument values for functions are not implemented.

**Comment by radare** [comment]
it is planned?

**Comment by nedpals** [comment]
I believe it's not. See: vlang/v#453

Alex suggests that you should use structs instead if you are going to put default values to functions.
