### ISSUE TITLE
Array of references does not work

### ISSUE THREAD

**Issue by ka-weihe** [vlang/v#2864]
**V version:** 
V 0.1.22 956c605

**OS:** 
Windows 10 (WSL)

**What did you do?**
```V
struct Point {
    x int
    y int
}

fn main() {
    p1 := Point { x: 0, y: 1  }
    println(&p1)
    points := [&p1]
    println(points[0])
}
```

**What did you expect to see?**
Compile and run
 
**What did you see instead?**
bad arr array_Point*
/tmp/v/try.tmp.c: In function ‘main__main’:
/tmp/v/try.tmp.c:3213:1: error: unknown type name ‘array_Point’; did you mean ‘array_int’?
 array_Point* points=new_array_from_c_array(1, 1, sizeof(Point*),...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by medvednikov** [comment]
Fixed.
