### ISSUE TITLE
I decided to release the binaries together with the source on June 22

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#287]
Hello,

Sorry, releasing the binaries 2 days earlier without the source code was a bad idea.

I wanted people to have an earlier access to the language, but now I realize that downloading and running a binary blob without access to its code is not reasonable.

I've just removed the macOS build after it being up for ~7 hours.

I need 2 days to clean everything up and document. 

On June 22 you will be able to compile V with a C compiler (V emits readable C code) and then use that build to compile V directly from the source.

-Alex

**Comment by joe-conigliaro** [comment]
We don't want you to rush, it's a big job for one person, hopefully we cal all help when the code is released.

**Comment by ConsoleTVs** [comment]
Sorry to bother but, what's the point of hiding the source code from the community till a certain date?

You need to clean stuff, right, so what? This makes me wonder what will happen between language versions. 1 Commit to change from V1 to V2 because u dont want to share progress? What about community integrating stuff? Fixing bugs?

This seems to be a free language, rather than an open source one. (In case this is not a scam tbh)

**Comment by medvednikov** [comment]
Once it's open sourced, all my work will be published right away.

**Comment by medvednikov** [comment]
https://blog.vlang.io/post/13/Why-isn't-everything-already-open-source?

**Comment by fahmiirsyadk** [comment]
i've already play a little bit with v , and its cool  ✨ . hopefully the json module docs will posted soon ❤️.

**Comment by ylluminate** [comment]
This is not a scam. As a supporter of @medvednikov's work and watching his effort, I can 100% guarantee you this is no scam. He may have missed some (minor and unimportant) deadlines, but he's not pulling the wool over anyone. 

Come on folks, be supportive of a guy who's really quite literally working to make the world a better place!

**Comment by benjaminrsherman** [comment]
> Once it's open sourced, all my work will be published right away.

If this is the case, why will the `x64/` directory not be available immediately?

**Comment by medvednikov** [comment]
>> Once it's open sourced, all my work will be published right away.
> If this is the case, why will the x64/ directory not be available immediately?

What I mean to say, once a project is open-sourced, changes to this project will be published right away. This was an answer to this question:

> This makes me wonder what will happen between language versions. 1 Commit to change from V1 to V2 because u dont want to share progress? What about community integrating stuff? Fixing bugs?

I have lots of WIP projects that are not open-sourced yet: x64, vweb, vtalk, generics, vid editor. Cut me some slack :) I'm doing lots of work on V, and all of it will be open-source.

**Comment by 1XiaSheng** [comment]
very nice

**Comment by tellizardy** [comment]
Wahoo

**Comment by ylluminate** [comment]
You know @medvednikov I just want you to know that some of us applaud you for staying even keeled and not losing your mind (or cool; all things considered) with all of the ridiculous insanity. Thank you for your hard work and I know many of us are looking forward to seeing the fruition of your hard work and sacrifice.

**Comment by greencopper** [comment]
Where is it?

**Comment by ylluminate** [comment]
@greencopper, from https://github.com/vlang/v :
> V is going to be released on June 22, 2019 at **18:00 UTC**.

![release](https://user-images.githubusercontent.com/248440/59957098-267e5f00-9463-11e9-9dc8-ed1a0247f815.png)

**Comment by nadiahub** [comment]
Let's find out why the chosen date on *June 22*  signify a special date for V:
V is the 22nd letter in the alphabet
V is also one of the symmetrical letters
June is mid year
18:00 UTC = 6 p.m.
