### ISSUE TITLE
Adding support for Haiku Operating System

### ISSUE THREAD

**Issue by M4SSD35TRUCT10N** [vlang/v#2870]
Adding support for the Haiku operating system.

**Comment by M4SSD35TRUCT10N** [comment]
#2872 first part of it in the master waiting for #2875 to branch off for second part. Now the Compiler should know about

`const (
	supported_platforms = ['windows', 'mac', 'linux', 'freebsd', 'openbsd',
		'netbsd', 'dragonfly', 'android', 'js', 'solaris', 'haiku']
) `

**and**

`enum OS {
	mac
	linux
	windows
	freebsd
	openbsd
	netbsd
	dragonfly
	js   // TODO
	android
	solaris
	haiku
} `

**Comment by M4SSD35TRUCT10N** [comment]
Second part committed but currently there's a problem when compiling it under up-to-date Haiku Beta 1. Investigating. Basically done.

**Comment by medvednikov** [comment]
@M4SSD35TRUCT10N can I close this now?

**Comment by M4SSD35TRUCT10N** [comment]
Seems to be a library issue on Haiku. Since I am the only one bothering with it, yes I'll close this one. Maybe open another issue when there is a real problem with the port or the generated code.
