### ISSUE TITLE
-prod affects WaitingGroup

### ISSUE THREAD

**Issue by radare** [vlang/v#2874]
**V version:** V 0.1.22 19b4cf6
**OS:** macOS 10.15

**What did you do?**

```go
$ cat match.v
import sync
import time

fn sub(wg mut sync.WaitGroup) {
	time.sleep(1)
	wg.done()
}

fn main() {
	mut wg := sync.new_waitgroup()
	wg.add(3)
	go sub(&wg)
	go sub(&wg)
	go sub(&wg)
	wg.wait()
}
```

**What did you expect to see?**

```
$ v -prod match.v
$ time ./match
./match  0.99s user 0.01s system 99% cpu 1.014 total
$
```
 
**What did you see instead?**

when using -prod i get undefined behaviour (sometimes ends quickly, sometimes never ends) related to WaitingGroup. it seems to be more consistent without release builds

```
$ time ./match
^C
./match  0.00s user 0.00s system 0% cpu 14.333 total
$
$ v -prod match.v
$ time ./match
./match  0.00s user 0.00s system 56% cpu 0.005 total
$ time ./match
./match  0.00s user 0.00s system 0% cpu 8.208 total
$ v match.v
$ time ./match
./match  1.00s user 0.00s system 73% cpu 1.369 total
$
```

**Comment by spytheman** [comment]
It happens on linux too.

**Comment by spytheman** [comment]
Passing -O1 (or -O2 or -O3) to the C backend induces this bug. Not sure what the cause is yet.

**Comment by radare** [comment]
Found the bug.. the compiler is optimizing this empty loop. imho V should forbid empty loops.

```
pub fn (wg mut WaitGroup) wait() {
println('wait0')
        for wg.active > 0 {
println('wait1')
                // time.sleep(1)
                // waiting
        }
println('wait2')
}

```

if you uncomment this time.sleep(1) line then the bug appears actually you can add any other statement inside the for loop and the bug disapears.

**Comment by radare** [comment]
not to mention this infinite loop should be using a mutex

**Comment by dumblob** [comment]
@medvednikov wanted to completely reimplement go routines (see e.g. https://github.com/vlang/v/issues/1868 ), so I wouldn't expect the current implementation to behave nicely (but just correctly).

**Comment by medvednikov** [comment]
Fixed.

**Comment by radare** [comment]
thank you <3
