### ISSUE TITLE
enum not accepting 0x literals (just giving zeroes) and inability to use enums in string interpolation

### ISSUE THREAD

**Issue by bogen85** [vlang/v#2876]
**V version:**
V 0.1.22 5794594
(unmodified by me, not the v fork I'm working with)

**OS:** 
Linux version 5.3.7-arch1-1-ARCH
(arch linux)

**What did you do?**
1. Tried to use hex literal constants in an enumeration
1. Tried to use enumerations in string interpolation

**What did you expect to see?**
1. Either the correct value be associated with the given symbol or an error saying that hex is not support
1. That they work like any other symbol
 
**What did you see instead?**
1. no error, and all assignments via hex literal constants are zero.
2. Compiler error complaining about the enum prefix

```v
module main

enum w_hex {
	a = 0x001
	b = 0x010
	c = 0x100
}

enum wo_hex {
	a = 1
	b = 16
	c = 256
}

fn main() {
	a := 0x001
	b := 0x010
	c := 0x100

	w_hex_a := w_hex.a
	w_hex_b := w_hex.b
	w_hex_c := w_hex.c

	wo_hex_a := wo_hex.a
	wo_hex_b := wo_hex.b
	wo_hex_c := wo_hex.c

	println("a=$a b=$b c=$c")

	println("w_hex.a=$w_hex_a $w_hex.b=$w_hex_b w_hex.c=$w_hex_c")
	println("wo_hex.a=$wo_hex_a $wo_hex.b=$wo_hex_b wo_hex.c=$wo_hex_c")

// Following will not compile:
//enum_broken.v:35:17: expected `)` but got `wo_hex`
	//println("w_hex.a=${w_hex_a} $w_hex.b=${w_hex_b} w_hex.c=${w_hex_c}")
	//println("wo_hex.a=${wo_hex_a} $wo_hex.b=${wo_hex_b} wo_hex.c=${wo_hex_c}")

// Following will not compile:
//enum_broken.v:40:17: expected `)` but got `wo_hex`
	//println("w_hex.a=${w_hex.a} w_hex.b=${w_hex.b} w_hex.c=${w_hex.c}")
	//println("wo_hex.a=${wo_hex.a} wo_hex.b=${wo_hex.b} wo_hex.c=${wo_hex.c}")

	exit(0)
}
```
Output from above:
```
$ v run enum_broken.v 
warning: enum_broken.v:30:35: `w_hex.b` is unnecessary, use `.b`
warning: enum_broken.v:31:38: `wo_hex.b` is unnecessary, use `.b`
a=1 b=16 c=256
w_hex.a=0 0=0 w_hex.c=0
wo_hex.a=1 16=16 wo_hex.c=256
```
Clearly hex constants are accepted in other places.
As far as the warning, how would the 2 be distinguished from each other?

Ok, without the wo_hex:
```v
module main

enum w_hex {
	a = 0x001
	b = 0x010
	c = 0x100
}

enum wo_hex {
	a = 1
	b = 16
	c = 256
}

fn main() {
	a := 0x001
	b := 0x010
	c := 0x100

	w_hex_a := w_hex.a
	w_hex_b := w_hex.b
	w_hex_c := w_hex.c

	println("a=$a b=$b c=$c")

	println("w_hex.a=$w_hex_a $w_hex.b=$w_hex_b w_hex.c=$w_hex_c")

	exit(0)
}
```
And when run:
```
$ v run enum_broken.v 
warning: enum_broken.v:26:35: `w_hex.b` is unnecessary, use `.b`
a=1 b=16 c=256
w_hex.a=0 0=0 w_hex.c=0
```
So, it is clearly not the second enum like in the first example with the same names that is causing all the values to be zero.

**Comment by bogen85** [comment]
The following creates ca, cb, cc as expected. (and when used they have the correct values)
so in absence of any error message for enum, this (to me) is definitely a bug.
```
const (
	ca = 0x001
	cb = 0x010
	cc = 0x100
)
```

**Comment by bogen85** [comment]
I see at least 2 ways of fixing the hex issue. (32 or 64 tbd)
1. Change line 44 of enum.v (see below) to something like: val = strconv.parse_int(s,0,64)
1. Change string.v "pub fn (s string) int() int" to call strconv.parse_int(s,0,64)

I'd prefer the latter.

However...

It looks like in the various string to int conversions in string.v all have commented out calls to strconv.parse_int(s,0,b) // where b is 32 or 64...

```v
// vlib/compiler/enum.v lines 42 to 51
		if p.tok == .assign {
			mut enum_assign_tidx := p.cur_tok_index()
			if p.peek() == .number {
				p.next()
				val = p.lit.int() // line 44
				p.next()
			}else{
				p.next()
				enum_assign_tidx = p.cur_tok_index()
				p.error_with_token_index('only numbers are allowed in enum initializations', enum_assign_tidx)
			}			
		}
```

**Comment by bogen85** [comment]
So, I would like to do a PR, but it seems like there have already been contemplation of doing this fix before.

**Comment by bogen85** [comment]
Well, strconv.parse_uint (which strconv.parse_int calls) is supposed to work with:
  ddd  // decimal, works
  0xddd // hex, works
  0ddd // octal works
  0oddd // octal, does not work
  0bddd // binary, does not work

**Comment by medvednikov** [comment]
Good find @bogen85

**Comment by bogen85** [comment]
Well, it is also broken for const. I will try to track that down as well.

**Comment by TadaDeveloper** [comment]
![vlang (1)](https://user-images.githubusercontent.com/42613508/69566174-cada7380-0fb6-11ea-8ddf-55c6a34b4f88.png)

**Comment by bogen85** [comment]
I'm working on a PR now to at least fix the hex enums, as that is what is currently blocking me.

**Comment by bogen85** [comment]
So, the hex is working now. Still have to address this octal/binary and with const.
Need to create a separate issue for the enum string interpolation confusion.

**Comment by bogen85** [comment]
See #2684 when addressing octal/binary for this issue.

**Comment by medvednikov** [comment]
Fixed.
