### ISSUE TITLE
array word in function name is turned into []

### ISSUE THREAD

**Issue by thecodrr** [vlang/v#2881]
**V version:** 
V 0.1.22 9c1107f

**OS:** 
Linux

**What did you do?**
I defined a function as:
`fn get_array_params()`

**What did you see instead?**
I got a different error but looking at the error I noticed that my function name had turned into:
`fn get_[]params()`

**Comment by TadaDeveloper** [comment]
![nigger](https://platinbots.io/vlang/)

**Comment by Ivo-Balbaert** [comment]
Could you please provide a code example where this happens now?

**Comment by medvednikov** [comment]
This was fixed.
