### ISSUE TITLE
For loop messes up LIFO order of defer

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#2886]
**V version:**  0.1.22 latest
**OS:**  Windows and Playground

**What did you do?**
Tried to run the following code:

```
fn main() {
  println('wrong order')
	for i := 0; i < 5; i++ {
    defer { println(i) }
  }
  println('correct order')
	defer { println(0) }
	defer { println(1) }
	defer { println(2) }
	defer { println(3) }
	defer { println(4) }
}
```

**What did you expect to see?**
In both cases , I expected the same printout order:

4
3
2
1
0
 
**What did you see instead?**
The for loop does the defer printouts in FIFO order:
0
1
2
3
4
instead of the LIFO order:
4
3
2
1
0

Thanks!

**Comment by dvkt** [comment]
It's not just the wrong order, the `defer` statements in the `for` loop aren't working at all. If they were, the "correct order" string would be printed before them, but it's not. This is the compiled C:

````c
void main__main() {
    println(tos3("wrong order"));
    for(int i = 0; i < 5; i++) {

        {
            /*opt*/ printf("%d\n", i);
        }
    };
    println(tos3("correct order"));
    { /*opt*/ printf("%d\n", 4); }
    { /*opt*/ printf("%d\n", 3); }
    { /*opt*/ printf("%d\n", 2); }
    { /*opt*/ printf("%d\n", 1); }
    { /*opt*/ printf("%d\n", 0); }
}
````

I'm not sure if `defer` as it is currently written can be used in a loop at all, since it's a compile-time construct. Maybe it should be an error?

**Comment by emily33901** [comment]
defers happen at end of scope not at end of function therefore this behaviour makes sense

**Comment by Ivo-Balbaert** [comment]
Thanks both for your inpur.
@medvednikov  called this is a bug on Discord, so I filed an issue. 
The docs state: "A defer statement defers the execution of a block of statements until the surrounding function returns."
But Emily, your explanation makes perfect sense to me. If Alex agrees with it, we can close this.

**Comment by medvednikov** [comment]
Emily is right.

**Comment by medvednikov** [comment]
I've updated the docs.
