### ISSUE TITLE
`rune` instances are not printable

### ISSUE THREAD

**Issue by Undumendil** [vlang/v#289]
Input: 
``` 
fn main(){
    a := rune('1')
    println(a)
}
```
Expected output: 
`1` 
Output: 
``` 
`rune` needs to have method `str() string` to be printable
```

**Comment by xacrimon** [comment]
inb4 this gets deleted because the dev is salty.

**Comment by Bowero** [comment]
Even without printing, the assignment gives a compile error:

/home/bowero//.vlang//test.c:3585:27: error: operand of type 'string' (aka 'struct string') where arithmetic or pointer type is required
rune a= (/*casttt*/ (rune)( /*77*/ tos2("1") ) ) ;

**Comment by RiordanIX** [comment]
This issue is closed.  Can it be moved to completed in the kanban?

**Comment by lutherwenxu** [comment]
@RiordanIX Done.
