### ISSUE TITLE
I tried to register vpm, but I can't log in.

### ISSUE THREAD

**Issue by keito940** [vlang/v#2890]
**V version:** 0.1.22
**OS:** Windows 10

**What did you do?**
I'm trying to register a yacc package, but I can't log in for some reason.

**Comment by nedpals** [comment]
Can you explain it in full detail? After you logged in, is there a message displayed? Are there any HTTP errors occurred afterwards?

In the meantime, I added your module into the [vpkg registry](https://github.com/vpkg-project/registry).

**Comment by keito940** [comment]
I will go to Login Via Github, but after that I get an HTTP error and can't proceed.

**Comment by medvednikov** [comment]
Works for me, I'll have a look at the logs.

**Comment by keito940** [comment]
Don't Submit,`yacc` package.
