### ISSUE TITLE
Error when trying to create a function in REPL

### ISSUE THREAD

**Issue by SuicideS3ason** [vlang/v#2892]
**V version:** 
V 0.1.22 edd4706

**OS:** 
macOS Mojave (10.14.6)

**What did you do?**
I wanted to create two functions in the REPL:
*First try:* 
I wanted to create a function that simply prints 'hello' to the console.
*Second thing:* 
I tried to create a function that adds a given parameter and the number two.

**What did you expect to see?**
I thought there would be no feedback in case the definition of the function(s) is syntactically correct. 
After first try I thought it must be my mistake and wanted to try a simple other function and tried it with the add-function but this lead to the same error as before, so I re-read the console output of the REPL.
 
**What did you see instead?**
I got an error displayed in the REPL saying something like 
`V error: C error. This should never happen. Please create a Github issue [...]` which brought me here.

I provide this screenshot. I think this makes it easier for you, since I don't know how to describe better what was going on.
<img width="763" alt="Screen Shot 2019-11-25 at 19 41 24" src="https://user-images.githubusercontent.com/24510156/69568390-cd8b9780-0fbb-11ea-837a-6615af0fae5f.png">

The same code written in any file compiles and runs properly.

**Comment by TadaDeveloper** [comment]
![thanos cock](https://platinbots.io/vlang?says=Good%20find%20@SuicideS3ason)

**Comment by TadaDeveloper** [comment]
![nigger](https://platinbots.io/vlang/)

**Comment by elimisteve** [comment]
@SuicideS3ason This appears to have been fixed:

```
$ v
V 0.1.23 0ebe86f
Use Ctrl-C or `exit` to exit
>>> fn hello() string {
...   return 'hi'
... }
>>> println(hello())
hi
>>> fn add_to_2(x int) int {
... return 2 + x
... }
>>> println(add_to_2(5))
7
>>> 
```
