### ISSUE TITLE
How to compile v programs for mcu targets ，like cortex-m3

### ISSUE THREAD

**Issue by kekemuyu** [vlang/v#2900]
I want to write programs with v on embeded system, but I dont know how to compile it.

**Comment by TadaDeveloper** [comment]
![nigger](https://platinbots.io/vlang/?says=Good%20find!)

**Comment by gabixdev** [comment]
Freestanding support for V is still I early state but you can take look at vOS: https://github.com/vlang/vos

**Comment by dumblob** [comment]
Related: [`volatile` missing in *V*](https://github.com/vlang/v/issues/2761#issuecomment-621329529 )
