### ISSUE TITLE
isnil() does not work for byteptr arguments

### ISSUE THREAD

**Issue by spytheman** [vlang/v#2905]
**V version:** V 0.1.22 dbaa37e
**OS:** MacOS X

**What did you do?** `v isnil_test.v` , where  isnil_test.v is:
```v
fn test_isnil_byteptr(){
        pb := byteptr(0)
        assert isnil( pb )
}

fn test_isnil_voidptr(){
        pv := voidptr(0)
        assert isnil( pv )
}

fn test_isnil_charptr(){
        pc := &char(0)
        assert isnil( pc )
}

fn test_isnil_intptr(){
        pi := &int(0)
        assert isnil( pi )
}
```

**What did you expect to see?**
tests pass
 
**What did you see instead?**
```shell
0[16:08:35]delian@tokmac /opt/vlang $ ./v ~/isnil_test.v
/Users/delian/isnil_test.v:4: FAILED assertion
Function: test_isnil_byteptr()
Source  :       assert isnil( pb )
1[16:08:39]delian@tokmac /opt/vlang $
```

For some reason, when the argument to isnil is byteptr, the generated C code is:
```c
 bool tmp1 =  isnil (& /*112 e="void*" g="byteptr" */ pb ) ;
```
while in other cases it is just:
```c
 bool tmp2 =  isnil ( pv ) ;
...
 bool tmp3 =  isnil ( pc ) ;
...
 bool tmp4 =  isnil ( pi ) ;
```

**Comment by bogen85** [comment]
This seems related to https://github.com/vlang/v/pull/2841
in that case a deference was being done on a cast
in this case the address of operator is being added when it should not be
#2841 addressed a voidptr case
Off hand I suspect a spectific byteptr cast is involved with causing this issue

**Comment by spytheman** [comment]
Thanks @bogen85 !!!
