### ISSUE TITLE
Appending values to array in function argument causes error

### ISSUE THREAD

**Issue by hatoo** [vlang/v#291]
Hi
I played playground and found a behavior could be a bug.

Program:
```
fn f(x mut []int) {
	x << 1
}

fn main() {
	mut arr := [1, 2, 3]
	f(mut arr)
	println(arr)
}
```

Expected output:
`[1, 2, 3, 1]`

Actual output:
exit with `realloc(): invalid pointer` or silently

**Comment by medvednikov** [comment]
Fixed.
