### ISSUE TITLE
Printing integers on Windows

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#2911]
**V version:** V 0.1.22 52d2533
**OS:**  Windows 10

**What did you do?**
Run the following program:
```v
fn main() {
    b := i8(0)
    println(b) 
    c := i16(7)
    println(c) 
    d := u16(6)
    println(d) 
}
```

(the other integer formats are ok)

**What did you expect to see?**
0
7
6

as it does on Linux
 
**What did you see instead?**
`i8` needs to have method `str() string` to be printable
`i16` needs to have method `str() string` to be printable
`u16` needs to have method `str() string` to be printable

**Comment by medvednikov** [comment]
Interesting find @Ivo-Balbaert 

I've added your code to CI, and indeed MSVC is failing. No idea why, will fix today.

**Comment by medvednikov** [comment]
Fixed.
