### ISSUE TITLE
I've just published detailed information on V's code structure

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#292]
https://github.com/vlang/v

Like many people requested.

This should help understand the upcoming code release better.

**Comment by andrewrk** [comment]
The read me says: 
> Creates a parser object for each file and runs parse() on them (this
> should work concurrently in the future).

But the website says:
> V compiles ≈1.2 million lines of code per second per CPU core.

The readme says:
> x64/ is the directory with all the machine code generation logic. It
> will be available in early July.

But you said[1]
> Once it's open sourced, all my work will be published right away. 
[1]: https://github.com/vlang/v/issues/287#issuecomment-503943736

**Comment by joe-conigliaro** [comment]
😆

**Comment by cnlisea** [comment]
😆

**Comment by joe-conigliaro** [comment]
He obviously doesn't want to release something he isn't happy with yet. He obviously hasn't reached his goal where he feels the code is up to par or its generally useful for people to use before releasing it. Not to mention having pull requests coming in before he has even taken to a point he is happy.  The fact he is open sourcing it is irrelevant. It's his project.

**Comment by createmap** [comment]
@joe-conigliaro Agreed.

@medvednikov Please consider my suggestion I have DM you in Slack. Codename: SpaceshipV

**Comment by medvednikov** [comment]
@andrewrk not going to communicate with you after this slander:

> This guy is a complete fraud. He's collecting $927/month on Patreon by deceiving generous and hopeful programmers. The claims on the web page are outright lies.
> 
> README.txt: Right now there are several dependencies that you need to install: clang, glfw, freetype, libcurl.
> web page claim: 400 KB compiler with zero dependencies
> Furthermore it's really shady to release only closed source builds 2 days before a source release. Why the sudden change of mind? https://twitter.com/v_language/status/1137750611389288450
> 
> README.txt: Missing features that will be available soon: hot code reloading
> 
> web page claim: Hot code reloading. Get your changes instantly without recompiling.
> 
> README.txt: Missing features that will be available soon: REPL
> 
> web page claim: V has a REPL
> 
> README.txt: Missing features that will be available soon: cross compiling
> 
> web page claim: Easy cross compilation. To cross compile your software simply run v -os windows . or v -os linux . No extra steps required, even for GUI and graphical apps!

> I'm all on board with friendly competition, but this is pretty hostile behavior to the open-source community. Be honest about what your software can and cannot do. And release source or GTFO.
> 
> He's up to 56% of the income I make on Patreon for Zig, and I've been busting my ass for years, working on solving a lot of the same problems, except it's been open source the whole time, and I only ever put claims on ziglang.org that describe actual status quo available software. It's really disheartening that such dishonest tactics are so effective.

https://news.ycombinator.com/item?id=20230351

If you think that the compiler, a console application, needs a dependency on glfw, an OpenGL context creation library, and freetype, a text rendering library, and call me a fraud based on this assumption, then you are simply inadequate. 

glfw and freetype are needed to run the examples that use the graphics library, which is not even part of the standard library. If that can't be clear to you in your blind lust for slander of me and my project, I can't take any of your claims seriously. 

Same goes for the "suspicious" early access release 2 days before releasing open source that has always been marked "coming in June" since February, when the site went live. Definitely so shady, willing to let the fans of the language play with it 2 days early.

Hot code reloading will be available on June 22, same with REPL.

Cross compiling already works, there's a demo of the language compiling itself on macOS for Windows, and you saw it. How can you claim it's a lie? 

And like @joe-conigliaro mentioned, I have valid reasons not to open-source things I'm not satisfied with yet. That's why the language was not open-sourced back in February.

**Comment by joe-conigliaro** [comment]
@andrewrk you sound like a busy guy, I don't know why your wasting your time creating posts like that. Looks like @medvednikov  is trying to create something good, and people are donating because they believe in his goals, don't get salty about it. Your getting upset because his software doesn't do everything it says on the website yet, that doesn't mean it's a scam. You should wait for actual proof before you post things like that.

**Comment by medvednikov** [comment]
He's been doing this on Twitter, Hacker News, Reddit, and now GitHub.

**Comment by andrewrk** [comment]
> because his software doesn't do everything it says on the website yet, that doesn't mean it's a scam.

It actually does. Here's the [legal definition of **fraud**](https://legal-dictionary.thefreedictionary.com/Fraud):

> A false representation of a matter of fact—whether by words or by conduct, by false or misleading allegations, or by concealment of what should have been disclosed—that deceives and is intended to deceive another so that the individual will act upon it to her or his legal injury.

> Fraud must be proved by showing that the defendant's actions involved five separate elements: 
> 1. a false statement of a material fact,
> 2. knowledge on the part of the defendant that the statement is untrue,
> 3. intent on the part of the defendant to deceive the alleged victim,
> 4. justifiable reliance by the alleged victim on the statement, and 
> 5. injury to the alleged victim as a result.

Note that "injury" in this case includes loss of money, e.g. by donating on Patreon.

I'd much rather ignore this project, but I have compassion for the victims of fraud, so that's why I'm donating some of my time here.

**Comment by joe-conigliaro** [comment]
> He's been doing this on Twitter, Hacker News, Reddit, and now GitHub.

Really! wow, he should be working on zig instead of wasting his time. This negativity is a shame.

**Comment by joe-conigliaro** [comment]
> > because his software doesn't do everything it says on the website yet, that doesn't mean it's a scam.
> 
> It actually does. Here's the [legal definition of **fraud**](https://legal-dictionary.thefreedictionary.com/Fraud):
> 
> > A false representation of a matter of fact—whether by words or by conduct, by false or misleading allegations, or by concealment of what should have been disclosed—that deceives and is intended to deceive another so that the individual will act upon it to her or his legal injury.
> 
> > Fraud must be proved by showing that the defendant's actions involved five separate elements:
> > 
> > 1. a false statement of a material fact,
> > 2. knowledge on the part of the defendant that the statement is untrue,
> > 3. intent on the part of the defendant to deceive the alleged victim,
> > 4. justifiable reliance by the alleged victim on the statement, and
> > 5. injury to the alleged victim as a result.
> 
> Note that "injury" in this case includes loss of money, e.g. by donating on Patreon.
> 
> I'd much rather ignore this project, but I have compassion for the victims of fraud, so that's why I'm donating some of my time here.

If he was selling people a product he claimed did things it actually didn't then what your saying would be correct. But he is getting patreon donations to create something which does not exist, or is't complete yet. They are funding the creation of it. I don't know what is so hard to understand about it.

**Comment by andrewda** [comment]
> > Fraud must be proved by showing that the defendant's actions involved five separate elements:
> > 
> > 1. a false statement of a material fact,
> > 2. knowledge on the part of the defendant that the statement is untrue,
> > 3. intent on the part of the defendant to deceive the alleged victim,
> > 4. justifiable reliance by the alleged victim on the statement, and
> > 5. injury to the alleged victim as a result.
> 
> Note that "injury" in this case includes loss of money, e.g. by donating on Patreon.

Oh man, you can't be serious...

I guess I'll keep this in mind next time I donate to a Kickstarter that doesn't _immediately_ live up to its promises, or God forbid I donate to an open-source project that's in active development and isn't yet perfect, or even usable.

In all seriousness, though, people who have donated to @medvednikov on Patreon aren't purchasing a product, they are simply funding the development of an ongoing project out of their own generosity (I'd donate too if I weren't a broke student).

In addition, part of your own definition of fraud is that it must be "intended to deceive another." I see absolutely no evidence that @medvednikov is trying to deceive anyone -- he's simply got a list of project requirements he's holding himself too and expects to eventually deliver.

**Comment by SleepyRoy** [comment]
@medvednikov is really passionate about the new language and has been devoting a lot of time and effort to it. I don't understand why some people are so mean.

**Comment by aveao** [comment]
I like how Alex is pulling the victim card here.

**Comment by bendmorris** [comment]
Hey @medvednikov - from the outside this looks like a scam to rake in Patreon money. I hope I'm wrong about that!

Here are my unsolicited tips to make it look less like a scam:

1. Just release the source and develop in the open. There's no reason not to or to set arbitrary future dates - just do it now. No one expects a work in progress to be perfect, and people probably want to help. They also want to see it and verify. The *most likely reason* you aren't releasing the source is that it doesn't live up to what you're claiming, which leads me to my next point:
2. Don't make claims about the language that aren't true yet, even if they're planned. If it can't compile concurrently or hot reload, don't say it can - say those features are coming soon.
3. No one is acting in bad faith here - the criticism you're getting here is legitimate, because *you are acting very much like a scammer.* Fix points 1 and 2, and the critcism will stop!

**Comment by dotshift** [comment]
How did Odin, Zig and Kit lang (Netflix) creators get curiosity on V? We bet some sort of childish defectors provoked them with shitty reasons.

**Comment by aveao** [comment]
![](https://elixi.re/i/mdhf8vtp.png)

lol.

**Comment by andrewrk** [comment]
Now that the website has the "WIP" label to communicate which features are not available, and the source is released, I no longer consider this project to be fraudulent. The information is available to everyone, and people who donate on Patreon are making an informed choice.

I'm genuinely glad it turned out this way. Good luck on your endeavor, and welcome to the programming languages club.

**Comment by uael** [comment]
Did github become a social network :thinking:
