### ISSUE TITLE
Unable to compile/run  vweb example

### ISSUE THREAD

**Issue by jvijay-work** [vlang/v#2920]
**V version:** 
V 0.1.21 368e8e8

**OS:** 
Ubuntu 18.04.3 LTS (Bionic Beaver)

**What did you do?**
v run examples/vweb/test_app.v

**What did you expect to see?**
a web app
 
**What did you see instead?**

V panic: string index out of range: 0 / 0
??:0:                                         | v(+0x1dd90) [0x560ad45b0d90]
??:0:                                         | v(+0x1e7ed) [0x560ad45b17ed]
??:0:                                         | v(+0x28cb8) [0x560ad45bbcb8]
??:0:                                         | v(+0x2c586) [0x560ad45bf586]
??:0:                                         | v(+0x2bf3d) [0x560ad45bef3d]
??:0:                                         | v(+0x483f4) [0x560ad45db3f4]
??:0:                                         | v(+0x3370d) [0x560ad45c670d]
??:0:                                         | v(+0x39a18) [0x560ad45cca18]
??:0:                                         | v(+0x3fc39) [0x560ad45d2c39]
??:0:                                         | v(+0x4e19) [0x560ad4597e19]
??:0:                                         | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f162987cb97]
??:0:                                         | v(+0x4eca) [0x560ad4597eca]

**Comment by medvednikov** [comment]
Please install the latest V 0.1.22.

I'll update the prebuilt package.
