### ISSUE TITLE
Net module doesn't expose AF_INET and friends

### ISSUE THREAD

**Issue by ckiee** [vlang/v#2921]
**V version:V 0.1.22 52d2533** 
**OS: Arch Linux** 

**What did you do?**
I tried to use the net module.

**What did you expect to see?**
AF_INET and friends exposed as consts
 
**What did you see instead?**
AF_INET and friends not exposed at all and only available via `C.`

**Comment by medvednikov** [comment]
I think this should be an internal const, why do you need it outside `net`?

**Comment by ronthecookie** [comment]
In #2912 I wanted to have a Socket object before it started listening. ([here](https://github.com/vlang/v/pull/2912/files#diff-100a0fe7bfed4cb9e9d927bea20e8dd8R59))

**Comment by danieldaeschle** [comment]
There is `net.AddFamily.ip` now
