### ISSUE TITLE
"v up" error (os__get_raw_line)

### ISSUE THREAD

**Issue by ArcDrake** [vlang/v#2925]
**V version:** 
V 0.1.22 431568f

**OS:**
Windows 10

**What did you do?**
v up

**What did you expect to see?**
successful update
 
**What did you see instead?**
D:\v>v up
Updating V...
From https://github.com/vlang/v
 * branch            master     -> FETCH_HEAD
   431568f..82d4a73  master     -> origin/master
Updating 431568f..82d4a73
Fast-forward
 vlib/builtin/utf8_util.v      | 855 ++++++++++++++++++++++++++++++++++++++++++
 vlib/builtin/utf8_util_test.v |   7 +
 2 files changed, 862 insertions(+)
 create mode 100644 vlib/builtin/utf8_util.v
 create mode 100644 vlib/builtin/utf8_util_test.v
Current branch master is up to date.
Building V
git version 2.19.1.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Now using V to build V...
C:\Users\ArcDrake\AppData\Local\Temp\v\v.exe.tmp.c: In function 'os__get_raw_line':
C:\Users\ArcDrake\AppData\Local\Temp\v\v.exe.tmp.c:5928:14: warning: initialization of 'int' from 'HANDLE' {aka 'void *'...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
v.exe failed to compile itself - Create an issue at 'https://github.com/vlang'

**Comment by kdmult** [comment]
It is a regression caused by recent changes in [tools/vup.v](https://github.com/vlang/v/commit/a620e66af500d3e7172c509a7ea6c83b772406bd#diff-4fc08ca6d866f2dcf6c6a314af2cf363) by @spytheman, namely
```diff
-		os.mv('$vroot/v.exe', v_backup_file)
+		os.mv_by_cp('$vroot/v.exe', v_backup_file)
```

`os.mv_by_cp` copies the new file then calls `_wremove` for the old one and fails because of its requirement that all handles to the file must be closed before it can be deleted. 

`os.mv` on the other hand calls `_wrename` which has no such a requirement.

**Comment by thebigsmileXD** [comment]
I can confirm this on Version 1903 (Build 18362.476), `V 0.1.23 d323b48`
@ArcDrake What works for me is to run make.bat after that error, this causes it to be built just fine

**Comment by ArcDrake** [comment]
@thebigsmileXD 

Thanks for the hint, this works. Running "git pull origin master" + "make" works fine for me too.

@kdmult 

This sounded plausible to me. "os.mv_by_cp" calls "os.rm" which calls "_wremove" (to be exact).
I tried the following:

I commented out the calls of "os.rm" in "os.mv_by_cp" and in "vup.v".
Then I re-compiled my local copy of V and ran "v up".

(I also removed the --rebase command in "vup.v" otherweise I get: "cannot pull with rebase: You have unstaged changes.")

In my opinion _wremove shouldn't be called anymore now, but I still get the Error.

Can this still be the reason?

**Comment by alexesprit** [comment]
@ArcDrake Is this still an issue? There were at least two PRs that fixed bugs in `v up`. I'm on Windows 10, and `v up` works for me fine (v is latest from master).

**Comment by thebigsmileXD** [comment]
For me it works fine now, but i had to manually `git pull` before (See #3276). I have tested this on Windows 10 1903, Parrot OS 4.4 (iirc) and WSL

**Comment by ArcDrake** [comment]
Hi,

I installed a fresh clone and I'm on V 0.1.24 67f397f now.
I will test `v up` later when updates are available :)

Happy new Year everybody

**Comment by ArcDrake** [comment]
V build OK!
V 0.1.24 aeda48d

@alexesprit works perfectly now :-)
