### ISSUE TITLE
Prebuilt binaries for all 3 major systems are here!

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#2930]
Prebuilt V binaries for Linux, macOS, and Windows can now be downloaded from the home page.

They will be updated every couple of days.

<img width="323" alt="Screen Shot 2019-11-29 at 19 23 39" src="https://user-images.githubusercontent.com/687996/69896973-76d4e380-1356-11ea-8215-a468ea568381.png">

**Comment by donnisnoni95** [comment]
Is it updated every commit or every version release ??

**Comment by medvednikov** [comment]
Every couple of days right now, every hour in the future.
