### ISSUE TITLE
increment map[string]int with += 1 does not work

### ISSUE THREAD

**Issue by mvlootman** [vlang/v#2931]
**V version: 0.1.23 d71532b ** 
**OS: Ubuntu 18.04.3 LTS** 

**What did you do?**
fn main(){
	mut word_count := map[string]int
	
	words := ['aa', 'bb', 'aa', 'cc']
	for w in words {
		word_count[w] += 1
	}
}

**What did you expect to see?**
no errors
 
**What did you see instead?**
map_feature_request.v: In function ‘main__main’:
map_feature_request.v:9:42: error: incompatible types when initializing type ‘int’ using type ‘map_int {aka struct map}’
   word_count[w] += 1
                                          ^         
map_feature_request.v:9:58: error: invalid operands to binary + (have ‘string {aka struct string}’ and ‘int’)
   word_count[w] += 1
 
A workaround is:
```
fn main(){
	mut word_count := map[string]int
	
	words := ['aa', 'bb', 'aa', 'cc']
	for w in words {
		word_count[w]++
		// or word_count[w] = word_count[w]  + 1 
	}
}
```

**Comment by medvednikov** [comment]
Map lookups are going to return optionals like in Rust and Swift soon, this will never work unfortunately.

**Comment by medvednikov** [comment]
It's a very common operation, so I'm thinking about doing something like `map.inc(key string)?`

**Comment by mvlootman** [comment]
Yes having a method that handles this would be very nice as this is a very common thing to do.
