### ISSUE TITLE
Is it possible to call v lib from other languages via FFI

### ISSUE THREAD

**Issue by hanabi1224** [vlang/v#2933]
e.g. mark v function as no mangle and expose C api for FFI (with dynamically linked library built from v). Thanks!

**Comment by medvednikov** [comment]
Yes: `module__fn_name()`.

V functions are just like C functions, except the module name is prepended.

**Comment by hanabi1224** [comment]
@medvednikov  Thanks! Is the naming convention supposed to be stable? Is it documented somewhere?

**Comment by medvednikov** [comment]
100% stable, never going to change, not documented yet.

**Comment by lygstate** [comment]
> Yes: `module__fn_name()`.
> 
> V functions are just like C functions, except the module name is prepended.

Do you means
`${module_name}__fn_${fn_name}`

**Comment by medvednikov** [comment]
`mod__fname`
`mod_submod__fname`

**Comment by crthpl** [comment]
This is answered.
