### ISSUE TITLE
V development plan in the description and README

### ISSUE THREAD

**Issue by Paul-Stern** [vlang/v#2935]
V repo docs seem to me not quite clear and I hope this issue could help make them better ones. The case is the following.
V repo description states stable version 0.2 is going to be released in early December while README.md ([Key Features](https://github.com/vlang/v#key-features-of-v)) tells us version 1.0 'is planned for December'. Aren't these statements contradictory, are they? Or is it meant version 1.0 doesn't have strict deadlines for now?

**Comment by medvednikov** [comment]
Fixed, thanks.
