### ISSUE TITLE
New string.index() make error

### ISSUE THREAD

**Issue by spTorin** [vlang/v#2939]
**V version:** 
V 0.1.23 d323b48

**OS:** 
Ubuntu 18.04

**What did you do?**
```
fn main() {
        a := 'asdf'
        println(a.index('s'))
}
```

**What did you expect to see?**
```
1
```
 
**What did you see instead?**
```
string.v:3:22: unhandled option type: `?int`
    1| fn main() {
    2| 	a := 'asdf'
    3| 	println(a.index('s'))
             	              ^
    4| }
```

`println(a.index_old('s'))` - works good

**Comment by medvednikov** [comment]
It now returns an ?int, you have to unwrap it.

**Comment by medvednikov** [comment]
```a.index('s') or { return }```
