### ISSUE TITLE
`v build module` does not work as documented

### ISSUE THREAD

**Issue by nevrome** [vlang/v#2945]
**V version:** V 0.1.23 ec15bfb
**OS:** Ubuntu 16.04.6 LTS (travis)

**Problem**
I use travis-ci to test my module [vconrand](https://github.com/nevrome/vconrand). When I use the syntax mentioned in the [documentation](https://vlang.io/docs#modules) to build the module I get the following error:

```
v build module vconrand
```
```
Building module "vconrand" (dir="vconrand")...
V error: vconrand doesn't exist
```

Following a  suggestion by @spytheman on discord I changed to the absolute path when calling v build module. I get another error then:

```
v build module $PWD/vconrand
```
```
Building module "vconrand" (dir="/home/clemens/agora/vconrand")...
vlib/rand/pcg32.v:1:10: bad module definition: /home/clemens/agora/v/vlib/rand/pcg32.v imports module "rand" but /home/clemens/agora/v/vlib/rand/pcg32.v is defined as module `vconrand`
    1| module rand
                ^
    2| 
    3| // Ported from http://www.pcg-random.org/download.html
```

@spytheman suggested here to switch to the .v-file instead of the module folder. This seems to work at first glance:

```
v build module $PWD/vconrand/vconrand.v
```
```
Building module "vconrand.v" (dir="/home/clemens/agora/vconrand/vconrand.v")...



Generating a V header file for module `/home/clemens/agora/vconrand/vconrand.v`
/home/clemens/agora/v//home/clemens/agora/vconrand/vconrand.v
Building /home/clemens/.vmodules//home/clemens/agora/vconrand/vconrand.v.o...
```

Unfortunately the module does not seem to be copied correctly to `~/.vmodules` with this setting. I believe this causes the error I see [on travis now](https://www.travis-ci.org/nevrome/vconrand/builds/619232556) when running my test code:

```
v run test/test.v
```
```
test/test.v:1:14: cannot import module "vconrand" (not found)
    1| import vconrand
                    ^
    2| import rand
    3| import time
```

Probably there is an error in the implementation of `v build module` or the documentation of said function.

Please let me know if I missed something or how I could help to fix this issue.

**Comment by taojy123** [comment]
I have meet the same problem

**Comment by penguindark** [comment]
from the doc `v build module` is no more supported
