### ISSUE TITLE
Two Errors, and the third is preference

### ISSUE THREAD

**Issue by alhabshi3k** [vlang/v#2946]
**V version: 0.1.23** 
**OS: windows 10 x64** 
**backend Compiler: Clang x86_64-w64-windows-gnu**

I was trying to compile the following v code into a dynamic linked library (DLL)

```
// filename test.v
fn add(x f32,y f32) f32 {        
    return x + y    
    }
```
 > `v -shared test.v`

and then I got the following errors:

 First:
`V error: function 'main' is not declared in the main module`
I added `fn main(){}` to 'test.v',  tried to compile it to DLL and then the next error

 Second:
`clang-9: error: unsupported option '-fPIC' for target 'x86_64-w64-windows-gnu`
I fixed the compiler/cc.v lines 125
from `a << '-shared  -fPIC '//  -Wl,-z,defs'` to `a << '-shared '//  -fPIC -Wl,-z,defs'`
recompiled v `v -prod v.v`, then tried to compile 'test.v' to DLL and the produced files : test.lib and test.so .

The desired preferences: 

- When the os in windows, the shared library file should have the extension ".dll" instead ".so"
- The expected exported functions in the dll (or .so) should be the same function name. However, I investigated the test.so file to see 'add' function, it was renamed to 'main__add'. Also, I found this in the generated C code. I tried to change the name to 'summer', and was generated as 'main__summer'. I suggest that the compiler should notify the programmer that it changed the names of some functions to resolve the conflict of similar names with other used libraries.

**Comment by danieldaeschle** [comment]
Errors no longer appear.
To get the desired behavior write this:
```v
[export: 'add']
pub fn add(x f32,y f32) f32 {
	return x + y
}
```

**Comment by alhabshi3k** [comment]
Thank Daniel, it was long time. I will look at the new updates.
