### ISSUE TITLE
Add -flto on production builds

### ISSUE THREAD

**Issue by radare** [vlang/v#2948]
```
$ v -prod -cflags -flto foo.v
$ du -hs foo
 12K	foo
$ v -prod foo.v
$ du -hs foo
 72K	foo
$
```

**Comment by spytheman** [comment]
As a workaround, you can pass explicitly -cc clang or -cc gcc , in which case -flto will be added with -prod .
The reason is that by default, v uses cc, and v does not know at the moment what exactly cc is on each platform, and if cc supports the -flto flag.

**Comment by radare** [comment]
makes sense, but it will be nice if `cc` default could autodetect the compiler

**Comment by spytheman** [comment]
I agree. When doing -prod, the additional time to autodetect/parse cc --version first will not be a problem.
