### ISSUE TITLE
string() on slice does not honor slice

### ISSUE THREAD

**Issue by mvlootman** [vlang/v#2949]
**V version: 0.1.23 d323b48** 
**OS: Ubuntu 18.04.3 LTS** 

**What did you do?**
Call string() on a slice of array.

**What did you expect to see?**
Only the slice portion of the array converted to a string.
 
**What did you see instead?**
The whole array was converted to a string.

Code example:
```v
fn main(){
	x := [byte(65),66,67]
	b := x[0..1]
	println(b)		         // [A]
	println(string(b))	//ABC   (expected "A")
}
```

**Comment by medvednikov** [comment]
`println(b.str())` works and `string(b)` shouldn't even compile, not sure why it does.

**Comment by lcddh** [comment]
Because b and x are the same memory address.
```
(tos2((byte *) b .data )
```
string(b) Convert the whole array to a string.

**Comment by medvednikov** [comment]
Ok I see, `string(b)` should work correctly, but `tos2([]byte.data)` doesn't limit the data.

**Comment by mvlootman** [comment]
fixed! 

```V
fn main() {
	x := [byte(65), 66, 67]
	b := x[0..1]
	println(b)		// [A] (correct)
	println(b.str())	// [A] (correct)
	println('$b')		// [A] (correct)

	y := ['apple', 'banana', 'coconut']
	slice_of_y := y[0..1]
	println(slice_of_y) 		// ['apple'] (correct)
	println(slice_of_y.str())	// ['apple'] (correct)
	println('$slice_of_y')  	// ['apple'] (correct)
}
```
