### ISSUE TITLE
os module is not has args?

### ISSUE THREAD

**Issue by zeromake** [vlang/v#295]

**Comment by medvednikov** [comment]
vdoc doesn't process consts yet.

**Comment by zeromake** [comment]
@medvednikov 
reply is so fast.

**Comment by Ivo-Balbaert** [comment]
Command-line arguments:	these are given by os.args, which is of type []string; 
for example:	 os.args[1] is the first command-line parameter.

import os

fn main() {
    for ix, arg in os.args {
      println('$ix: $arg')                  
    }    
} 

/* When called as:  os_args A 1 Hello          This prints out:
E:\Vlang\The_Way_to_V\Chapter_9_Modules>os_args A 1 Hello
0: os_args
1: A
2: 1
3: Hello
*/
