### ISSUE TITLE
Cast from voidptr to a C struct fails to compile

### ISSUE THREAD

**Issue by prime31** [vlang/v#2950]
**V version:**
V 0.1.23 850788c

**OS:**
macOS

**What did you do?**
Casting from a voidptr to any C struct. The compiler confuses the C struct for a C method that it fails to find because it doesnt exist.

This fails:

```c
struct C.Thing {}

arr := **C.Thing(ptr)
```

Typedefing the C struct to one that does not include `C.` works around the issue:

```c
type TempThing C.Thing

arr := **TempThing(ptr)
```

**What did you expect to see?**
No compile error. Casting a C struct should work the same as a non-C struct
 
**What did you see instead?**
Attached is a very simple repro. The following error:

```
bug.v:17:4: undefined C function `Thing`
define it with `fn C.Thing([args]) [return_type]`
   15| 	
   16| 	arr := **TempThing(ptr)
```

[bug.zip](https://github.com/vlang/v/files/3908890/bug.zip)

**Comment by donnisnoni95** [comment]
@prime31 Instead using `C.TempThing(ptr)` use `&TempThing(ptr)`. I hope it works because it works on me.  😊

**Comment by prime31** [comment]
Omitting the `C.` from the struct name does seem to work for me as well. Oddly enough, I can omit the `C.` from other places as well. My understanding was that it was required but perhaps it isnt supposed to be required to use the `C.` prefix...

**Comment by Ivo-Balbaert** [comment]
The suggested workaround now gives:
bug.v:14:11: error: unknown function: Thing 
   12 |

**Comment by danieldaeschle** [comment]
Currently this results in 
```
main.v:7:13: error: cannot cast `voidptr` to struct
    5 | 
    6 |     // this does not work
    7 |     arr := **C.Thing(ptr)
      |                ~~~~~~~~~~
    8 | 
    9 |     // this will work
```

Is it the correct behaviour? @spytheman

**Comment by medvednikov** [comment]
Fixed.
