### ISSUE TITLE
news_fetcher.v never quits

### ISSUE THREAD

**Issue by logTom** [vlang/v#2961]
**0.1.23:** 
**Linux Solus** 

**v run news_fetcher.v**

**10 news items being displayed and then the program quits.**

 
**10 news items being displayed and the programm running endless with 100 % cpu utilization on 1 core.**

**Comment by spytheman** [comment]
Possible duplicate of #2874 .

**Comment by medvednikov** [comment]
Should work fine now @logTom

**Comment by logTom** [comment]
Thanks, can confirm that it works now.

**Comment by medvednikov** [comment]
Thanks @spytheman 

Looks like it was optimized without even -O2
