### ISSUE TITLE
JSON encode/decode example in playground 

### ISSUE THREAD

**Issue by defond0** [vlang/v#297]
Running the JSON encoding/decoding example in the playground yields 
```
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.
```
![json_encoding_decoding](https://user-images.githubusercontent.com/3068808/59938476-efc82a80-9409-11e9-96f3-c078b7f28e7f.PNG)

**Comment by Undumendil** [comment]
A smaller example of the bug:
```
import json
struct Test {
    s string
}
user := json.decode(Test, '{"s": "Frodo"}') or { return }
println(user.s)
```
Output:
```
`` needs to return ``
```

**Comment by Bowero** [comment]
Since the playground has been closed and the imports have been fixed, I will close this issue.
