### ISSUE TITLE
Error printing an enum on Windows

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#2980]
**V version:** 0.1.23
**OS:**  Windows 10

**What did you do?**
Tried to compile the following program:

```v
enum Color {
	red green blue
}

fn main() {
        mut color := Color.red 
        color = .green
        println(color)                    
}
```

**What did you expect to see?**
1 , as is the output on Linux
 
**What did you see instead?**
`Color` needs to have method `str() string` to be printable

Perhaps this should not be considered a bug, and it should be the developer who should supply a str() method for a specific enum. But I report it because the behavior is different in Linux, at least there should be a uniform behavior among platforms.

**Comment by darenliang** [comment]
As you mentioned, this should not be considered a bug.

C doesn't provide a built-in way to get a string value of a specific enum and I don't think V should be any different in this case.

As for implementing a str() method, I think it would add unwanted overhead.

**Comment by medvednikov** [comment]
It should print `1`, it does so on Linux and in the playground.

If this doesn't work on Windows, it should be open.

**Comment by medvednikov** [comment]
I'll add a test to CI

**Comment by Ivo-Balbaert** [comment]
Ok , reopened. On Windows it still says:
 `Color` needs to have method `str() string` to be printable
instead of printing 1

**Comment by lcddh** [comment]
I am on windows 10,the result is 1

**Comment by medvednikov** [comment]
@Ivo-Balbaert I've added a CI test, all good.

Seems to be a local problem. Are you on the latest commit?

**Comment by Ivo-Balbaert** [comment]
I've installed the latest from source, and I get the same output as on Linux, no error anymore.
Thanks!
