### ISSUE TITLE
mkdtemp proposal

### ISSUE THREAD

**Issue by radare** [vlang/v#2983]
**V version:** V 0.1.23 fb546f3
**OS:** macOS 10.15

**What did you do?**

make a temporal directory, im opening this issue to discuss namings and apis to implement in vlib, we have tmpdir() but this just returns the path to the temporal directory, doesnt creates any temporal file or directory. about creating temporal files, the posix C api returns an fd, which we may probably wrap it into an os.File{cfile:fd}

**What did you expect to see?**

no C apis involved from v-land 

**What did you see instead?**

```
import os
import filepath


fn C.mkdtemp(template charptr) byteptr

fn mktmpdir(template string) string {
        tp := if template == '' {
                'temp.XXXXXX'
        } else {
                template
        }
        dir := filepath.join(os.tmpdir(),tp)
        res := C.mkdtemp(dir.str)
        return tos_clone(res)
}

fn main() {
        d := mktmpdir('')
        println(d)
}
```

**Comment by dumblob** [comment]
Be careful here, because e.g. POSIX defines directory creation as an **atomic operation** (i.e. if it succeeded, it's guaranteed that such directory didn't exist yet and no harm/overwrite/lie has been done) **unlike** file creation.

**Comment by radare** [comment]
yep we may want to document/provide a stable/consistent api for all this kind of common operations

**Comment by spytheman** [comment]
It should be `fn mktmpdir(template string) ?string {` ?

**Comment by spytheman** [comment]
I am not sure if os.tmpdir should be called inside the implementation.
According to my mkdtemp man page:
```
       The  mkdtemp() function generates a uniquely named temporary directory from template.  The last six characters of template must be XXXXXX and these
       are replaced with a string that makes the directory name unique.  The directory is then created with permissions 0700.  Since it will be  modified,
       template must not be a string constant, but should be declared as a character array.

RETURN VALUE
       The mkdtemp() function returns a pointer to the modified template string on success, and NULL on failure, in which case errno is set appropriately.

ERRORS
       EINVAL The last six characters of template were not XXXXXX.  Now template is unchanged.
```

**Comment by Larpon** [comment]
In latest V, temporary files and directories can be made using `io.util` [(`temp_file()` and `temp_dir()`)](https://github.com/vlang/v/blob/931882d72072a0c2895daf7f878e265db8e6dff7/vlib/io/util/util.v#L18)
