### ISSUE TITLE
The State and Scope of vlib

### ISSUE THREAD

**Issue by prime31** [vlang/v#2987]
vlib is and always will be the first place new and seasoned V coders go to for best practices implementing modules, API design, etc. I realize V is still just an infant, but the state of vlib code is pretty awful. I won't go into details but just a cursory look through it and you'll find piles of commented out code, API design that is all over the place, bad practices in wrapping C APIs, etc, etc, etc. Just look at the `gl`, `gg`, `sdl2` and `freetype` for some examples. Some are massively incomplete, wrapping a C API but implementing only 5% of it. Others just flat out don't run on macOS. Some have examples embedded in the module, others don't. It's all over the place.

I think it would be massively beneficial to V as a whole if when people dove into vlib it contained some semblance of quality and a standard that is a cut above. Getting these modules out of vlib and into external packages or just tossing them entirely if they aren't going to be properly written, documented and maintained would only help to keep the V repo and codebase clear and consistent.

I would hate to see people get scared away because they looked at any of these modules and thought that they represented the code quality of V as a whole.

**Comment by medvednikov** [comment]
Not sure what this issue is for.

Create actual issues with things that need implementation/improvements and/or submit pull requests.

Of course vlib is going to be cleaned up/improved as the language matures.
