### ISSUE TITLE
Multiple return types do not work with enums

### ISSUE THREAD

**Issue by emily33901** [vlang/v#2988]
**V version: V 0.1.23 850788c** 
**OS: Windows GCC** 

**What did you do?**
Make a function that returned `(string, enum)`

**What did you expect to see?**
no errors (e.g. successful compile)
 
**What did you see instead?**
in the case of an `(enum, string)` ret type:
![](https://i.f1ssi0n.com/ProminentYellowClumber.png)

Also doesnt work with `(?string, bool)` or similar.

**Comment by Delta456** [comment]
This issue is fixed with the latest V:

Test program

```v
enum Int {
	one
	two
}

fn foo() (Int, int) {
	return Int.one, 1
}
fn main() {
	println(foo())
}
```
