### ISSUE TITLE
Union and struct do not produce expected results

### ISSUE THREAD

**Issue by FemtoEmacs** [vlang/v#2989]
**V version:** 
› v --version
V 0.1.23 79b26b1
**OS:** 
› sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.1
BuildVersion:	19B88

**What did you do?**
```bash
› cat structpanic.v
```
```v
union Block {
    x int
    str string
}

struct Sexpr {
  car Block
  cdr Block
}

fn main() {
   q := Sexpr{car: Block{str: 'Rose'}, cdr: Block{x: 42}}
   println(q.car.str)
   println('Here it is: $q.cdr.x')
}
```

=== Compiling ==========
~/wrk/v› v -o structpanic.x structpanic.v

**What did you expect to see?**
› ./structpanic.x
Rosa
42
 
**What did you see instead?**
~/wrk/v› ./structpanic.x

Here it is: 248927702

**Comment by Ivo-Balbaert** [comment]
Same on Windows 10 with v 0.1.27:
Output:    Here it is: 4329705

**Comment by penguindark** [comment]
Now it works
```v
union Block {
    x int
    str string
}

struct Sexpr {
  car Block
  cdr Block
}

fn main() {
	unsafe {
		 q := Sexpr{car: Block{str: 'Rose'}, cdr: Block{x: 42}}
		 println(q.car.str)
		 println('Here it is: $q.cdr.x')
	}
}
```
