### ISSUE TITLE
or block does not accept a default value under some circumstances

### ISSUE THREAD

**Issue by emily33901** [vlang/v#2994]
**V version: V 0.1.23 55f32fc** 
**OS: Windows 10 GCC** 

**What did you do?**
```v
	lit := p.consume_lit() or {
		report_error('Expected literal in option statement')
		'' // appease compiler
	}
```

**What did you expect to see?**
no error
 
**What did you see instead?**
```
vproto/main.v:560:28: `or` block must provide a default value or return/exit/continue/break/panic
  558|  p.consume_whitespace()
  559|
  560|  lit := p.consume_lit() or {
                                    ^
  561|          report_error('Expected literal in option statement')
  562|          '' // appease compiler
```

Further notes: compiler accepts a `panic()` in this case just not a default value. Either way I want a way to specify that this `report_error` function will never return and therefore can be a substitute for a panic function.

**Comment by emily33901** [comment]
Actually this is a type checking bug because lit is not of type string therefore this shouldnt have worked in the first place so I would be expecting a type mismatch error.

**Comment by Ivo-Balbaert** [comment]
It is not easy to test this issue without a complete code sample. Could you please provide one if this issue is still relevant? Thanks

**Comment by emily33901** [comment]
No idea whether it's still relevent but it was just the case of trying to assign to a value using an `or` block but it would not accept an empty string literal - the side note was just that I would have liked a way to specify that report_error never returns and therefore is a substitute for `panic`

**Comment by Ivo-Balbaert** [comment]
Looking at the docs:
" `or` block must end with `return`, `break`, or `continue` "
it doesn't specify anymore that an or block can accept or return a default value.

**Comment by emily33901** [comment]
![](https://i.f1ssi0n.com/LateWesternWorm.png) as far as i know it accepts a value default aswell (it would be kinda dumb if it didnt). This issue was probably a problem with the old parser and isnt a problem anymore - you could check out [vproto](https://github.com/emily33901/vproto) and [proto-v](https://github.com/emily33901/protoc-v) which attempted to make extensive use of this but were thwarted by this problem.

**Comment by Ivo-Balbaert** [comment]
Yes of course you're right Emily, thanks.
The following code now works and as you can see x gets the value ' ':

fn f() ?string {
	return error('nope')
}

fn report_error(s string) {
	println(s)
}

x := f() or { 
	report_error('Error being reported')
	' ' 
}

println('***' + x + '***') // => *** ***

Would you consider your issue to be solved now?

**Comment by emily33901** [comment]
yeah if that works now then there isnt an issue anymore. Thanks Ivo!
