### ISSUE TITLE
link to vblog and vforum on vlang.io do not work

### ISSUE THREAD

**Issue by sachinbhutani** [vlang/v#2995]
I get an HTTP 502 error with links to vForum and vBlog on http://vlang.io
![image](https://user-images.githubusercontent.com/6120010/70346052-4091db00-1812-11ea-9c5f-714bea5e5b19.png)

**Comment by emily33901** [comment]
Yeah its been like this for a while...

**Comment by medvednikov** [comment]
Fixed.

The forum is back: forum.vlang.io

**Comment by sachinbhutani** [comment]
Still same error 
![SmartSelect_20191208-173508_Chrome](https://user-images.githubusercontent.com/6120010/70400720-2a864500-19e1-11ea-8e54-9b77f02a1031.jpg)
