### ISSUE TITLE
String interpolation with more than one set of braces

### ISSUE THREAD

**Issue by benob** [vlang/v#2998]
**V version:** 5a8c07d

**OS:** Linux

**What did you do?**

v run test.v

fn main() {
  a := 1
  b := 2
  println("${a} ${b}")
}

**What did you expect to see?**

should compile
 
**What did you see instead?**

next token = `eof`
test.v:8:1: syntax error: unexpected `eof`, expecting `)`
    6| }

**Comment by medvednikov** [comment]
This is happening only with `""` strings, thanks for reporting.

**Comment by medvednikov** [comment]
Fixed.
