### ISSUE TITLE
Substring error in compiler on if c := fn() != x {}

### ISSUE THREAD

**Issue by emily33901** [vlang/v#2999]
**V version: V 0.1.23 55f32fc** 
**OS:Windows 10 GCC** 

**What did you do?**
```v
if c := p.consume_char() != `;` { report_error('Expected `;` after enum field') }
```

Note: `p.consume_char()` returns a `byte` not an optional type.

**What did you expect to see?**
Either a well defined V error or successful compilation
 
**What did you see instead?**
```
V panic: substr(7, 4) out of bounds (len=4)
TODO: print_backtrace_skipping_top_frames_mingw(2)
print_backtrace_skipping_top_frames is not implemented on this platform for now...
```

**Comment by medvednikov** [comment]
Fixed: ```opt.v:2:12: `if x := opt() {` syntax requires a function that returns an optional value```
