### ISSUE TITLE
V > struct & func> mut

### ISSUE THREAD

**Issue by han2015** [vlang/v#300]
Here is part doc copy from `Pure functions by default`
```
V is not a pure functional language however. It is possible to modify function arguments by using the same keyword mut:

struct User {
	is_registered bool 
} 

fn (u mut User) register() {
	u.is_registered = true 
} 

mut user := User{} 
println(user.is_registered) // ==> "false"  
user.register() 
println(user.is_registered) // ==> "true"  
In this example, the receiver (which is simply the first argument) is marked as mutable, so register() can change the user object. The same works with non-receiver arguments:

fn multiply_by_2(arr mut []int) {
	for i := 0; i < arr.len; i++ {
		arr[i] *= 2
	}
}

mut nums := [1, 2, 3]
multiply_by_2(mut nums)
println(nums) // ==> "[2, 4, 6]"
Note, that you have to add mut before nums when calling this function. This makes it clear that the function being called will modify the value.
```

Since reading this, I'm very confused about how to use `mut` confidently.
As the doc says, struct could has `mut`,`pub mut`,`pub mut mut`,`pub` types of fields so that they has many R&W rules. 

1: But here, `fn (u mut User) register()` could change a immutable `is_registered`, that means this breaks the rule defined on the struct fields.

2: `fn multiply_by_2(arr mut []int) `, what will be if I call this with a immutable struct's array?

Now I feel so many `mut` calling in my head...

**Comment by medvednikov** [comment]
Thanks for reporting this. The docs haven't been updated everywhere after the introduction of access modifiers. Fixed.

> 2: fn multiply_by_2(arr mut []int) , what will be if I call this with a immutable struct's array?

It won't compile.

**Comment by han2015** [comment]
@medvednikov an urgent issue:
![image](https://user-images.githubusercontent.com/10386227/59963903-0070c180-952c-11e9-9882-26786eaddd01.png)

**Comment by han2015** [comment]
well, Just find a  comment  at here. https://github.com/vlang/v/issues/296
