### ISSUE TITLE
Array of struct does not work with constants

### ISSUE THREAD

**Issue by benob** [vlang/v#3002]
**V version:** cc834dd
**OS:** linux

**What did you do?**

```v
struct Data {
  field int
}

const (
  x = Data{1}
  y = Data{2}
)

fn main() {
  a := [x, y]
  println(a[1].field)
}
```

**What did you expect to see?**

Should compile fine.
 
**What did you see instead?**

```
test.v:11:9: bad fixed size array const `x`
    9| 
   10| fn main() {
   11|   a := [x, y]
               ^
   12|   println(a[1].field)
   13| }
```

Note that `a := [Data{1}, Data{2}]` and `a:= [Data{1}, y]` both work

**Comment by Ivo-Balbaert** [comment]
The code now (V 0.1.27 c9f3a05) works (output 2) on Windows 10, Linux Ubuntu 20 and the Playground.
