### ISSUE TITLE
os.system returns the exit status of a system command instead of its output

### ISSUE THREAD

**Issue by mhusmann** [vlang/v#3004]
I'd like to get the systems output result in a variable for further processing

**Comment by medvednikov** [comment]
there's os.exec()` for that

they may be merged in the future

**Comment by mhusmann** [comment]
Thanks a lot
Kind regards
Michael

Am Sa., 7. Dez. 2019 um 16:23 Uhr schrieb Alexander Medvednikov <
notifications@github.com>:

**Comment by mhusmann** [comment]
Alexander,

just tried it, but getting an error: "unhandled option type: ?os.Result"
when trying to print the output.

Any hint?
Michael

Am Sa., 7. Dez. 2019 um 16:24 Uhr schrieb Michael Husmann <
michaelhusmann@gmail.com>:

**Comment by medvednikov** [comment]
`res := os.exec('xxx') or { panic(err) }`

See optionals section in the docs.

**Comment by mhusmann** [comment]
got it. Thanks
Michael

Am Sa., 7. Dez. 2019 um 17:00 Uhr schrieb Alexander Medvednikov <
notifications@github.com>:

**Comment by mhusmann** [comment]
Hi Alexander,

is there any formatting possible when using print or println?

Kind regards
Michael

Am So., 8. Dez. 2019 um 09:38 Uhr schrieb Michael Husmann <
michaelhusmann@gmail.com>:

**Comment by medvednikov** [comment]
`println('${number:02d}')`

**Comment by mhusmann** [comment]
great.
Works fine

thanks a lot
Michael

Am Mo., 9. Dez. 2019 um 12:04 Uhr schrieb Alexander Medvednikov <
notifications@github.com>:

**Comment by mhusmann** [comment]
go routines are nice.
Will you implement also channels?

Am Mo., 9. Dez. 2019 um 12:12 Uhr schrieb Michael Husmann <
michaelhusmann@gmail.com>:

**Comment by mhusmann** [comment]
Hi Alexander,

sorry. Next question. How do I append a struct to an array.
Example tried in the repl:

>>> struct Egal {
... x int
... y int
... }
>>> struct Egstack {
... stack []Egal
... }
>>> mut s := Egstack{}
>>> s << Egal{1,2}
cannot use shift operator on non-integer type `Egstack`

Regards
Michael


Am Mo., 9. Dez. 2019 um 12:18 Uhr schrieb Michael Husmann <
michaelhusmann@gmail.com>:

**Comment by medvednikov** [comment]
You should  use #help chat on Discord for such questions.
```
mut s := Egstack{}
s.stack << Egal{1,2}```
