### ISSUE TITLE
So many warnings in V 0.1.23.1 631c3c0!

### ISSUE THREAD

**Issue by changrui** [vlang/v#3005]
Attempting to build v.c with GCC...
Now using V to build V...
warning: vlib\os\os.v:410:28: casting `int` to `int` is not needed
warning: vlib\os\os.v:782:51: casting `int` to `int` is not needed
warning: vlib\os\os_windows.v:81:76: casting `voidptr*` to `voidptr*` is not needed
warning: vlib\os\os_windows.v:163:23: casting `int` to `int` is not needed
warning: vlib\os\os.v:410:28: casting `int` to `int` is not needed
warning: vlib\os\os.v:782:51: casting `int` to `int` is not needed
warning: vlib\os\os_windows.v:81:76: casting `voidptr*` to `voidptr*` is not needed
warning: vlib\os\os_windows.v:163:23: casting `int` to `int` is not needed
C:\Users\ADMINI~1\AppData\Local\Temp\v\v.exe.tmp.c: In function 'compiler__find_windows_kit_internal':
C:\Users\ADMINI~1\AppData\Local\Temp\v\v.exe.tmp.c:14259:85: warning: passing argument 6 of 'Reg...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
v.exe failed to compile itself - Create an issue at 'https://github.com/vlang'

**Comment by medvednikov** [comment]
I've fixed some of these, most of these will be fixed within a couple of days.

**Comment by changrui** [comment]
All are solved at `v 0.1.23.1 8b0de95`.
