### ISSUE TITLE
Call function on reference to struct result of a function  

### ISSUE THREAD

**Issue by benob** [vlang/v#3012]
**V version:** 1c6f718
**OS:** linux

**What did you do?**
```
struct Data {
  x int
}

fn (d &Data) f() {
}

fn g() Data {
  return Data{1}
}
    
fn main() {
  g().f()
}
```
Note the reference to a Data struct in f. This happens in vlib when calling `time.now().calc_unix()`

**What did you expect to see?**
Should compile. Using a temporary variable works:
```
d := g()
d.f()
```
 
**What did you see instead?**

C compiler fails because it can't take a reference of the result of a function.
```
/tmp/v/test.tmp.c:3290:10: error: lvalue required as unary ‘&’ operand
 3290 |  Data_f (& /* ? */ main__g ( ) ) ;
```

**Comment by Ivo-Balbaert** [comment]
The code works if omitting the reference in:

fn (d Data) f() {
}

That way f() works on a Data struct itself, which is what g() returns.

If you want it to work on a &Date, you must write:

fn (d &Data) f() {
}

fn g() &Data {
  return &Data{1}
}

Then the code also compiles.

I think the error arises from the inconsistency in the original code, and that this issue can be closed?
