### ISSUE TITLE
support for == between structs

### ISSUE THREAD

**Issue by benob** [vlang/v#3014]
**V version:** 1c6f718
**OS:** linux

**What did you do?**
This is both a bug report (as generated C code is invalid) and a feature request. Content comparison with == should work with structs, or at least be overloadable.

```
struct Data {
  x int
}

fn main() {
  a := Data{1}
  b := Data{1}
  if(a == b) {
    println("Yes")
  }
}
```
**What did you expect to see?**
Should print "Yes"
 
**What did you see instead?**
```
/tmp/v/test.tmp.c:3285:11: error: invalid operands to binary == (have ‘Data’ {aka ‘struct Data’} and ‘Data’ {aka ‘struct Data’})
 3285 |  if ( ( a == b ) )...
```

**Comment by medvednikov** [comment]
Yes, `==` will work for structs.

**Comment by Delta456** [comment]
You need to overload `==` for your struct.

**Comment by benob** [comment]
I tried to overload == using examples from the documentation without success.

**Comment by Delta456** [comment]
This does not work 

```v
struct Data {
  x int
}

fn (d Data) eq (d2 Data) bool {

   return d.x == d2.x
}

fn main() {
	a := Data{2}
	b := Data{4}
	println(a == b) 
}
```

**Comment by Delta456** [comment]
Duplicate of #4365
