### ISSUE TITLE
Leibniz test

### ISSUE THREAD

**Issue by proyb6** [vlang/v#302]
```
fn main() {
	mut x := f64(1.0)
	mut pi := f64(1.0)
	for i in 2 .. 1000002 {
		x *= -1.0
		pi += x / (2 * i - 1)
	}
	pi *= 4
	println('$pi')

//Go and Ruby returns 3.1415936535887745
//V returns 3.141594
}


```

**Comment by kostya** [comment]
`C.printf('%.15f\n', pi)` => 3.141593653588775

**Comment by proyb6** [comment]
Thank @kostya, will try when V is release.

**Comment by medvednikov** [comment]
V uses C's default formatting, which has 6 digit precision. There will be a way to change that without using `C.printf`.

**Comment by proyb6** [comment]
Could V detects which data type when we assigned at the beginning?

**Comment by proyb6** [comment]
I guess V could print based on the declared data types?

**Comment by medvednikov** [comment]
> I guess V could print based on the declared data types?
Yes, good idea.
