### ISSUE TITLE
Web server crash

### ISSUE THREAD

**Issue by davtur19** [vlang/v#3022]
**V version:**
V 0.1.23 b2207c3
**OS:**
raspbian (debian)

**What did you do?**
Hosting [vorum](https://github.com/vlang/vorum)
I sent a tcp request with nmap and it crashed: `nmap -sT -p 8080 192.168.1.5`
192.168.1.2 => client
192.168.1.5 => server (vorum)
![image](https://user-images.githubusercontent.com/13476215/70433681-a5ec0300-1a82-11ea-8d36-8750f8f764e6.png)

**What did you expect to see?**
A working server

 
**What did you see instead?** 
The program closes
![image](https://user-images.githubusercontent.com/13476215/70433503-370eaa00-1a82-11ea-9329-55197ea303a9.png)

with `nmap -sV -p 8080 192.168.1.5` i see this:
![image](https://user-images.githubusercontent.com/13476215/70433813-e8addb00-1a82-11ea-80b4-35d64cc553f7.png)

**Comment by medvednikov** [comment]
Fixed.
