### ISSUE TITLE
Add a module for crossplatform colored console output

### ISSUE THREAD

**Issue by XVilka** [vlang/v#3023]
Like python's [colorama](https://pypi.org/project/colorama/) or Rust's [termion](https://docs.rs/termion/1.5.4/termion/). It might be useful to add other low-level functions too.

Since we live in 2019 it makes sense to start from the True Colors right from the start: https://github.com/termstandard/colors/

**Comment by medvednikov** [comment]
Have you checked out `vlib/term`?

**Comment by XVilka** [comment]
Ouch, sorry for the noise, you can delete the issue to prevent the clutter.
