### ISSUE TITLE
`user1` declared and not used

### ISSUE THREAD

**Issue by AGulev** [vlang/v#303]
```
struct User {
	name string
	age  int
}

fn main() {
	user1 := User{'Bob', 20}
	user2 := {user1 | name: 'Peter'}
	println(user2.name)
	println(user2.age)
}
```
Error in example "An updated copy of a struct" from site: https://vlang.io/play

**Comment by proyb6** [comment]
In addition, `You just found a bug` error.
```
user1 := User{'Bob', 20} 
	user2 := user1 | 'Peter'
	println(user2.name) 
	println(user2.age)
} 
```

**Comment by medvednikov** [comment]
Fixed.

@proyb6 you have a syntax error: you need the `{}`. I'll update the compiler to return an error instead of the bug message.
