### ISSUE TITLE
How to check if a module is installed

### ISSUE THREAD

**Issue by radare** [vlang/v#3030]
**V version:** V 0.1.23 0650d58
**OS:** macOS 10.15

**What did you do?**

check if a module is found or not, also the only way i know to update a dependency is by removing the ~/.vmodules directory 

```
$ v update
TODO: v update
$
```

**What did you expect to see?**

a simple way (maybe with v -e 'expr') to check if a module exists or needs to be updated, etc or maybe

```
$ v search r2
TODO: v search
$
```
 
**What did you see instead?**

v repl doesnt drops the return code to the shell

```
$ echo 'import radare.r22' | v
V 0.1.23 0650d58
Use Ctrl-C or `exit` to exit
>>> cannot import module "radare.r22" (not found)
>>> %   
 $ echo $?
0
$ echo 'import radare.r2' | v
V 0.1.23 0650d58
Use Ctrl-C or `exit` to exit
>>> >>> %  
$ echo $?
0
$
```

**Comment by spytheman** [comment]
`v list` shows the currently installed modules, and `v search r2` shows the available remote modules, matching r2.
