### ISSUE TITLE
Playground reports runtime panic as a compilation error

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#3032]
**V version:** 
**OS:** 
https://vlang.io/play

**What did you do?**
```
const (
        MAX = -10 
)

struct Fib {
        nums []int
}

fn (fib mut Fib) calc(n int) int {
        if n <= 1 {
                return n
        }
        if fib.nums[n] != 0 {
                return fib.nums[n]
        }
        fib.nums[n] = fib.calc(n - 1) + fib.calc(n - 2)
        return fib.nums[n]
}

fn main() {
        mut fib := Fib {
                nums: [0].repeat(MAX)
        }
        for i := 0; i < MAX; i++ {
                println(fib.calc(i))
        }
}
```
with message:
```
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.
```

**Comment by mrgaturus** [comment]
maybe using recursions on methods bugs the compiler

**Comment by lutherwenxu** [comment]
It panics because it's attempting to create an array with a negative length. Specifically, this line here:
```
                nums: [0].repeat(MAX)
```

**Comment by Ivo-Balbaert** [comment]
To make the code run now (v 0.1.27) it has to be changed as follows:

const (
        MAX = -10 
)

struct Fib {
mut:
    nums []int
}

fn (mut fib Fib) calc(n int) int {
        if n <= 1 {
                return n
        }
        if fib.nums[n] != 0 {
                return fib.nums[n]
        }
        fib.nums[n] = fib.calc(n - 1) + fib.calc(n - 2)
        return fib.nums[n]
}

fn main() {
        mut fib := Fib {
                nums: [0].repeat(MAX)
        }
        for i := 0; i < MAX; i++ {
                println(fib.calc(i))
        }
}

Windows 10 returns:  V panic: array.repeat: count is negative: -10
Playground still returns: You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

**Comment by penguindark** [comment]
Now work with:
```v
const (
        MAX = 10 
)

struct Fib {
mut:
        nums []int
}

fn (fib mut Fib) calc(n int) int {
        if n <= 1 {
                return n
        }
        if fib.nums[n] != 0 {
                return fib.nums[n]
        }
        fib.nums[n] = fib.calc(n - 1) + fib.calc(n - 2)
        return fib.nums[n]
}

fn main() {
        mut fib := Fib {
                nums: []int{len: MAX}
        }
        for i := 0; i < MAX; i++ {
                println(fib.calc(i))
        }
}
```
