### ISSUE TITLE
Compiler allows const to use itself in the declaration

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#3034]
**V version:** 
**OS:** 
https://vlang.io/play
**What did you do?**
```
const (
cl = [cl,cl]
)

fn main() {
  println("a")
}  
```

**Comment by Ivo-Balbaert** [comment]
This code now (v 0.1.27) gives a clear error message on Windows 10 and in the Playground:

error: cycle in constant `cl` 
    1 | const (
    2 | cl = [cl,cl]
      |       ~~
    3 | )
