### ISSUE TITLE
can an enum be defined inside a function?

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#3043]
**V version:** 
**OS:** 
https://vlang.io/play
**What did you do?**
```
fn main() {
enum Color {
	red green blue
}

mut color := Color.red
// V knows that `color` is a `Color`. No need to use `color = Color.green` here.
color = .green
println(color) // "1"  TODO: print "green"? 

}
```
errorMessage:
```
unexpected token: `}`
    9| println(color) // "1"  TODO: print "green"? 
```

**Comment by vuhg** [comment]
Following code works, the cause is `enum Color` that is declared in `fn main`
```v
enum Color {
  red green blue
}

fn main() {
  mut color := Color.red
  // V knows that `color` is a `Color`. No need to use `color = Color.green` here.
  color = .green
  println(color) // "1"  TODO: print "green"? 
}
```

**Comment by bronze1man** [comment]
@vuhg so it is bad error message. I do not know why it is not working...

**Comment by M4SSD35TRUCT10N** [comment]
@medvednikov The above screened behavior seems a bit odd. It's not documented that enums have to be declared outside of functions. I tried some other stuff and declared some enums within a bunch of functions (this time not within main) and get a similar error. Although I did this (declaring them 'standalone') naturally and never thought about this, they are just some kinds of variables aren't they? So one should be able to do the above declaration style. That would limit their scope too - besides pub enum declaration.

I personally think it's a documentation issue to clarify the use of them.

**Comment by Ivo-Balbaert** [comment]
The title of this issue is incorrect. The docs example works perfect now:

enum Color {
  	red green blue
	}

mut color := Color.red
// V knows that `color` is a `Color`. No need to use `color = Color.green` here.
color = .green
println(color) // => green

The remaining question is whether an enum can be defined inside a function or not.

**Comment by Ivo-Balbaert** [comment]
If it is not at the moment, the issue can be closed.

**Comment by nedpals** [comment]
Closed. The error reports to the right position:
```
main.v:2:1: error: expr(): bad token `enum`
    1 | fn main() {
    2 | enum Color {
      | ~~~~
    3 |     red green blue
    4 | }
```
