### ISSUE TITLE
Get character of string error

### ISSUE THREAD

**Issue by thanhngch** [vlang/v#3045]
I run string example https://vlang.io/docs#strings
**V version:** V 0.1.23 eb20dd3
**OS:** Ubuntu 18.04

**What did you do?**
```js
fn main() {
    a := "aloha!"[0]
    println(a)
}
```
**What did you expect to see?**
`97` or `syntax error`
 
**What did you see instead?**
`aloha!`

**Comment by mvlootman** [comment]
That is unexpected indeed. 
I would expect the first byte, so your output would give 97. As a string is an array of bytes.

**Comment by Quentie** [comment]
assert 'aloha!'[0] == `a` also fails

**Comment by medvednikov** [comment]
Fixed in the new parser :)

It will be the default soon.

**Comment by alexesprit** [comment]
Closed as fixed. :)
