### ISSUE TITLE
Pointers could be dereference twice

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#3047]
**V version:** 
**OS:** 
https://vlang.io/play
**What did you do?**
```
fn main() {
	a := '1'
	b := &a
	println(**b)
}
```
with error message
```
You just found a bug. V should either compile this program or return an error. 

Please create a GitHub issue.

This program has been saved, and the bug will be fixed asap.
```

**Comment by Henrixounez** [comment]
A non pointer can't be dereferenced it current version of V, (And *kind of* on the playground though, which is still on a version from September 2020).
If the problem is still here for you, feel free to reopen and add more details.
