### ISSUE TITLE
${name.len<5} equals '1'?

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#3049]
**V version:** 
**OS:** 
https://vlang.io/play
**What did you do?**
```
fn main() {
name := 'Bob'
println('Hello, $name! ${name.len<5}') 
}
```
get result out:
```
Hello, Bob! 1
```

**Comment by medvednikov** [comment]
In this case `true` is printed as `1`. Good find.

**Comment by emily33901** [comment]
> 
> 
> In this case `true` is printed as `1`. Good find.

true/ false are always printed as 1 and 0 for me...

**Comment by medvednikov** [comment]
This was changed recently:

```
>>> println(true)
true
>>>
```

**Comment by medvednikov** [comment]
Yea not sure why I didn't close it back in December :)
