### ISSUE TITLE
vweb server will be blocking while a post request without any form data

### ISSUE THREAD

**Issue by taojy123** [vlang/v#3050]
**V version:** 0.1.23 
**OS:**  mac

**What did you do?**  
```
v run vweb_example.v
```

then send a post request with not any form data, such as:
```
curl -X POST http://127.0.0.1:8082/text/
```

**What did you expect to see?**
see the response with 200 status code
 
**What did you see instead?**
server is blocking, nothing output.

**Comment by taojy123** [comment]
Anthoer case by V code:

```
>>> import http
>>> http.get('http://127.0.0.1:8082/text/') or {}  // no problem
>>> http.post('http://127.0.0.1:8082/text/', "a=123") or {}  // no problem
>>> http.post('http://127.0.0.1:8082/text/', '') or {} // blocking!
```

**Comment by medvednikov** [comment]
http.post with empty data doesn't block for me

**Comment by spytheman** [comment]
https://github.com/vlang/v/pull/3051 fixed this.
