### ISSUE TITLE
Does the program generated after compiling on Windows display nothing?

### ISSUE THREAD

**Issue by FrankLIKE** [vlang/v#3052]
On Windows 7 x64,
git clone v
Open the cmd, run the make.bat,then see the 'V Build Ok'.
But, v run examples\hello_world.v
You will get nothing to see!
Why?

**Comment by FrankLIKE** [comment]
v0.1.20  Display Ok!

**Comment by emily33901** [comment]
could you try run `v -g -o hello.exe examples\hello_world.v`

**Comment by FrankLIKE** [comment]
Still showing nothing.

**Comment by vitalyster** [comment]
What is your C compiler version? MinGW?

**Comment by sunnylcw** [comment]
Believe it is similar to #2372 which can be resolved by using https://github.com/mstorsjo/llvm-mingw

**Comment by FrankLIKE** [comment]
download the MinGW:llvm-mingw-20190920-x86_64.zip,v-master.zip, on windows 7.
set Path=c:\llvm_mingw\llvm-mingw-20190920-x86_64\llvm-mingw\bin
run the make.bat
At last :get the v.exe
Then run:
  v examples\hello_world.v
but get the file:hello_world,no extension '.exe' 
Then modify the file name hello_world to hello_world.exe,
Then Ok.

**Comment by remixer-dec** [comment]
Similar issue here.
  
**V version:** 0.1.24
**OS:** Windows 8.1

**What did you do?**
I downloaded latest binary from the official site and tried to compile hello_world.v with it

**What did you expect to see?**
An error message that a c compiler is not installed or is outdated
 
**What did you see instead?**
Nothing (empty line)

There is no information about the c compiler requirement in the official website. Only in README file, you can save time for someone by adding it.  After successfully setting up the compiler, I noticed that version command still doesn't work. All `v.exe --version` and `-v` and `version` output an empty line.
  
P.S.  
I'm not sure why you decided to drop cygwin support. The point of using cygwin, if it's already installed, is to not waste extra ~600mb of storage for mingw installation. I managed to run v.exe with gcc compiler under cygwin. All .v files in examples folder (except for sqlite) do compile and run successfully. 
To configure cygwin+gcc you need to  
1) Run cygwin's setup-x86_64.exe  
2) On package selection stage, select full filter, type 'gcc', select mingw64-x86_64-gcc-core (for 64-bit OS) and select the version that'll be installed, install it  
3) In cygwin type `export VFLAGS="-cc x86_64-w64-mingw32-gcc.exe"`  
That's it!

**Comment by cup** [comment]
As was mentioned, V requires:

https://github.com/mstorsjo/llvm-mingw

Example:

~~~
$ PATH=llvm-mingw/bin v_windows/v

Use Ctrl-C or `exit` to exit
>>>
~~~

and without you just get nothing:

~~~
$ v_windows/v
~~~

that pretty bad user experience, it should print a warning if the C backend is
not found.

**Comment by Ekopalypse** [comment]
I assume this one can be closed.

~~~
D:\ProgramData\Compiler\v>del examples\hello_world.exe && v -cc tcc examples\hello_world.v && dir examples\hello_world.exe | findstr /C:"hello_world.exe"
27.03.2021  16:21           441.856 hello_world.exe

D:\ProgramData\Compiler\v>del examples\hello_world.exe && v -cc gcc examples\hello_world.v && dir examples\hello_world.exe | findstr /C:"hello_world.exe"
27.03.2021  16:21           252.661 hello_world.exe

D:\ProgramData\Compiler\v>del examples\hello_world.exe && v -cc msvc examples\hello_world.v && dir examples\hello_world.exe | findstr /C:"hello_world.exe"
27.03.2021  16:21           294.912 hello_world.exe


D:\ProgramData\Compiler\v>v -cc tcc run examples\hello_world.v
Hello, World!

D:\ProgramData\Compiler\v>v -cc gcc run examples\hello_world.v
Hello, World!

D:\ProgramData\Compiler\v>v -cc msvc run examples\hello_world.v
Hello, World!
~~~
