### ISSUE TITLE
function return a function

### ISSUE THREAD

**Issue by thanhngch** [vlang/v#3053]
```js
fn sqr(n int) int {
    return n * n
}

fn run() (fn (int) int) {
    return sqr
}

fn main()  {
    println(run(5)) // "25"
}
```
I want to build success but it show an error: expected type `_V_MulRet_fn (int) int`, but got `fn (int) int`

**Comment by medvednikov** [comment]
Try

```
fn run() fn (int) int {
    return sqr
}
```

**Comment by medvednikov** [comment]
Never mind, it seems not to be supported yet. Will be fixed this month.

**Comment by thanhngch** [comment]
I think it will support closure like Go.

**Comment by eyelash** [comment]
This works now with V 0.1.27 if you change the main function to
```
fn main()  {
    s := run()
    println(s(5)) // "25"
}
```

**Comment by VinWare** [comment]
As an improvement to this, would like to suggestd
```println(run()(5))```
should work too. It should give
```25```
Currently it gives
```error.v:11:14: error: unexpected `(`, expecting `,`
    9 | s := run()
   10 | println(s(5))
   11 | println(run()(5))
      |              ^```

**Comment by penguindark** [comment]
this is the working version at the moment:
```v
fn sqr(n int) int {
  return n * n
}

fn run() (fn (int) int) {
  return sqr
}

fn main()  {
  a := run()
  println(a(5)) // "25"
}
```

**Comment by eyelash** [comment]
At least on the playground `run()(5)` still doesn't work. Is this supposed to work or is there an issue to track this?

**Comment by Gladear** [comment]
There is #10117
