### ISSUE TITLE
Misleading compilation error

### ISSUE THREAD

**Issue by m00nshake** [vlang/v#3055]
V 0.1.23 28f76f1
Linux Swifty 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Playing with a trimmed down version of tetris.v, I got the following compilation error:
```
/home/seb/Dev/vlang/font/font.v: In function ‘main__main’:
/home/seb/Dev/vlang/font/font.v:56:12: error: incompatible types when assigning to type ‘Game {aka struct Game}’ from type ‘Game * {aka struct Game *}’
  game.gg.window.onkeydown(key_down)
            ^
V error: C error. This should never happen. 
```

In reality the problem is tied with mutable game usage.
Replacing
`fn (g Game) run() {`
by
```
fn (g mut Game) run() {
  g.state = .running
```
made it work.

[font.v.txt](https://github.com/vlang/v/files/3951597/font.v.txt)

**Comment by medvednikov** [comment]
I'm getting the correct ```
 `g` is immutable
```

**Comment by medvednikov** [comment]
Can you paste the entire code?

**Comment by m00nshake** [comment]
Sorry for the delay.
The code was attached in the font.v.txt link above.
There's still a C error currently, not sure why :
```
/home/pi/.cache/v/font.tmp.c: In function ‘main__main’:
/home/pi/.cache/v/font.tmp.c:10136:12: error: incompatible types when assigning to type ‘Game’ {aka ‘struct Game’} from type ‘Game *’ {aka ‘struct Game *’}
  tmp1 -> g =  game ;
```

**Comment by medvednikov** [comment]
Fixed in the new backend.
