### ISSUE TITLE
Enums arent js encoded properly

### ISSUE THREAD

**Issue by emily33901** [vlang/v#3056]
**V versionV 0.1.23 28f76f1:** 
**OS:Windows 10 GCC** 

**What did you do?**
```v
import json

enum x {
    a, b, c
}

struct Test {
    f x
}

fn main() {
    o := Test{f: .a}
    println('${json.encode(o)}')
}
```

**What did you expect to see?**
`{"f": 0}`
 
**What did you see instead?**
`{"f": {}}`

Other notes:
Mostly becuase the jsencode for enum types doesnt do anything
![](https://i.f1ssi0n.com/TraumaticQuenchingPupfish.png)

**Comment by nedpals** [comment]
Closed. See: https://devbits.app/play/2JGcERfvXTGG

**Comment by medvednikov** [comment]
Fixed.
