### ISSUE TITLE
snake-case variable & function naming

### ISSUE THREAD

**Issue by ramtg** [vlang/v#3057]
Hi, Alex:

Suggestion:  It'd be nice if snake-cased variable & function names could be supported .
But not sure whether this would be feasible.

Thank you
Ram

**Comment by medvednikov** [comment]
That would be cool, but it'd make V whitespace sensitive (`a-b` vs `a - b`)

**Comment by ramtg** [comment]
Would requiring a white-space around operators  make it feasible though ?
Thank you.
