### ISSUE TITLE
Compilation js backend not working

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#3063]
**V version:** 0.1.23 575518d
**OS:**  Windows 10 and Ubuntu 19

**What did you do?**
Tried to compile:  v -o hi.js hi.v

with hi.v:
fn main() {
        for i := 0; i < 3; i++ {
                println('Hello from V.js')
        }
}

**What did you expect to see?**
Succesfull compilation
 
**What did you see instead?**
V.js compiler not found, building...
c:\v\vlib\compiler\expression.v:372:37: type `compiler.Parser` has no field or method `gen_handle_question_suffix`
  370|  if p.tok == .question {
  371|          // `files := os.ls('.')?`
  372|          return p.gen_handle_question_suffix(f, fn_call_ph)
                                                    ^
  373|  }
  374|  else if !p.is_var_decl && is_or_else {
Failed.

The error is the same on both Windows 10 and Linux. I understand that this is a WIP

**Comment by medvednikov** [comment]
Yeah, I've removed it from readme.

It'll be fixed, just not a priority right now.

**Comment by medvednikov** [comment]
Fixed with the new JS backend.
