### ISSUE TITLE
Cannot convert Option to map

### ISSUE THREAD

**Issue by Iaiao** [vlang/v#3065]
**V version:** V 0.1.23 b8f7285
**OS:** Windows 10

**What did you do?**
```v
fn test(a bool) ?map[string]string {
    if a {
        return map[string]string
    }
    else {
        return error("1")
    }
}
```

**What did you expect to see?**
Successful compilation
 
**What did you see instead?**
```
test.v:7:5: cannot convert `Option` to `map_string`
    5|     else {
    6|         return error("1")
    7|     }
           ^
```

**Comment by Ivo-Balbaert** [comment]
The code above now (V 0.1.27 c9f3a05) compiles and runs on Windows 10 and in the Playground:

fn test(a bool) ?map[string]string {
    if a {
        return map[string]string
    }
    else {
        return error("1")
    }
}

mut t := test(true) or { return }
println(t) // => {}
t = test(false) or { return }
println(t) // =>
