### ISSUE TITLE
default arguments for function

### ISSUE THREAD

**Issue by taojy123** [vlang/v#3068]
That will be exciting if a function has default arguments.
such as:
```go
fn foo(bar string, count int =1) {
    for _ in [..count] {
        print(bar)
    }
}

foo('hello') // -> hello
foo('hello', 3) // -> hellohellohello
```
Thankyou!

**Comment by Kamori** [comment]
I'm new here, but this might go against the Safety Values

https://vlang.io/
> Safety
No null
No global variables
No undefined values
No undefined behavior
No variable shadowing
Bounds checking
Option/Result types
Generics
Immutable variables by default
Pure functions by default
Immutable structs by default


--- 
Having said this. I love and miss this feature from python. I would accept it in any language :+1:

**Comment by medvednikov** [comment]
V will have no function overloading/default arguments, but it will have
`foo({bar:10})`

where `foo` is `fn foo(struct {bar int, baz int  = 10})`

**Comment by taojy123** [comment]
ok， got it！
