### ISSUE TITLE
Remove libcurl dependency from the http module

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#307]
I think an OpenSSL dependency is fine and unavoidable.

**Comment by Xiphin** [comment]
OpenSSL

**Comment by MoAlyousef** [comment]
Dlang also has a libcurl dependency if you want to use the std.net module. So it's ok to use a well-tested battle-proven library and provide an interface to it in V.

**Comment by Chiiruno** [comment]
This might be more of a philosophical argument, but as much of the library should be in V as possible, and there should always be work to move away from 3rd party libraries even if it's not easy.
That said, for crypto, it's pretty hard to beat battle tested libraries like OpenSSL and NaCl.
We're still in >1.0 though, so until then it should be fine to use third party, but the above should apply after IMO.

**Comment by medvednikov** [comment]
libcurl dependency was removed.
