### ISSUE TITLE
Segmentation fault (core dumped) & array updated but length always 1 or 0

### ISSUE THREAD

**Issue by Jictyvoo** [vlang/v#3075]
**V version:** https://github.com/vlang/v/tree/fb3da327d682ecf9b42bc3eac414f74f914d2c86
**OS:** Ubuntu 18

**What did you do?**
A [V HTML Parser](https://github.com/Jictyvoo/v_html/tree/e8be463aabedbb396097a15ac0f80f7b28df5eb9) (yes, after updating stack code, error doesn't appear, so for testing need to be this tree) and tested it with [v github html page](https://pastebin.com/tLAzPWTM)

**What did you expect to see?**
V array alocation working and no segfault
 
**What did you see instead?**
`Segmentation fault (core dumped)`
And on [debug.log](https://pastebin.com/J74Jxcec) file I see some type of pointer management error, because after adding 5 objects (tag nodes) to an array inside a struct, the array length is always 1. And after it, array length returns to 0 (depending on scope).

**Comment by Jictyvoo** [comment]
In this example, segfault appears in function tag.str(), line 28 of tag.v file `if value.len > 0 { to_return += "=" + "${tag.attributes[key]}" }`

Other weird thing is on line 106 of dom.v file, if copy it and paste it again (like `temp_tag.add_child(tag) temp_tag.add_child(tag)`), segfault appers while printing first file line

**Comment by danieldaeschle** [comment]
Could you add a minimal example please?

**Comment by Jictyvoo** [comment]
This issue is too old, and right now I can't make a full test on it, I think is better to close it.

But you can test using the code in link on issue description with given HTML page (on pastebin)
