### ISSUE TITLE
Can't access C enum

### ISSUE THREAD

**Issue by prime31** [vlang/v#3077]
**V version:** V 0.1.23 fc64238
**OS:** macOS 10.15.2 (19C57)

**What did you do?**
```c
// C enum
enum Thing {
	First,
	Second
}
```

```c
// V declaration
enum C.Thing { First, Second }
```

Attempting to access a C enum results in type undefined compiler errors.

**What did you expect to see?**
I expected to be able to define and access the C enum
 
**What did you see instead?**
Missing type errors on compile

**Comment by Zymlex** [comment]
Same problem.
