### ISSUE TITLE
C function pointers cant be used as parameters

### ISSUE THREAD

**Issue by prime31** [vlang/v#3078]
**V version:** V 0.1.23 fc64238
**OS:** macOS 10.15.2 (19C57)

A function pointer declared with `type` cant be used as a parameter to a function. The compiler throws a `cannot use type...` error.

Example code below:

```c
// C typedef of a function pointer
typedef FMOD_RESULT (F_CALL *FMOD_FILE_OPEN_CALLBACK)       (const char *name, unsigned int *filesize, void **handle, void *userdata);
```

```c
// V declaration of the type
pub type FileOpenCallback fn(name byteptr, filesize &u32, handle &voidptr, userdata voidptr) int

// V function that uses the type
pub fn set_file_system(useropen FileOpenCallback) {}

fn file_open_cb(name byteptr, filesize &u32, handle &voidptr, userdata voidptr) int {}
```

**What did you do?**
Using `FileOpenCallback` as a function parameter then trying to call that function results in an error

**What did you expect to see?**
No errors and compilation succeded.
 
**What did you see instead?**
`cannot use type `fn (byte*,u32*,voidptr*,void*) int` as type `FileOpenCallback` in first argument to `set_file_system()``

**Comment by danieldaeschle** [comment]
cannot reproduce, reopen if needed
