### ISSUE TITLE
Neither -bare nor -freestanding work

### ISSUE THREAD

**Issue by elimisteve** [vlang/v#3086]
**V version:** V 0.1.23 1cd5fab
**OS:** Debian

**What did you do?**

I ran

    $ v run -bare bare.v

where bare.v's source is:

```
fn syscall5(number int, arg1 int, arg2 string, arg3 u64, arg4 u64, arg5 voidptr) int 

fn write(fd int, data string, nbytes u64) int {
	return syscall5(1, fd, data, nbytes, 0, 0) 
} 

fn main() {
	write(1, "Hello from V running on bare metal!\n", 37)
}
```

Then I ran

    v run -freestanding bare.v

**What did you expect to see?**

Nothing; should compile successfully as it did a week ago :-).

 
**What did you see instead?**

When using `-bare` I got

```
V error: use -freestanding instead of -bare
```

But when I tried using `-freestanding` as recommended, I (somewhat humorously) got

```
V error: -freestanding doesn't exist
```

despite a supposed fix from https://github.com/vlang/v/issues/2846 .

**Comment by medvednikov** [comment]
Can you try

v -freestanding bare.v

**Comment by emily33901** [comment]
Yeah was gonna say that the compiler args go before the command and those go before the filename

**Comment by bogen85** [comment]
oh, that example should be updated, as I removed syscall5.
sys_call5 could work (if it were not private to vlib/builtin/bare/linuxsys_bare.v), but sys_write, print, and println are already in pace for freestanding.
```v
fn main() {
	sys_write(1, "Hello from V running on bare metal!\n".str, 37)
}
```
works with "v -freestanding bare.v"

println also works:
```v
fn main() {
	println("Hello from V running without libc!")
}
```

**Comment by bogen85** [comment]
From a v git checkout the following works:
```
v -freestanding run examples/x64/hello_world.v
```
-freestanding still uses intermediate c though.

**Comment by ConnectedSystems** [comment]
I have a related issue when trying V out.

I couldn't get V to work under Windows 10 (I can open a separate issue for this, but it seems the compiler expects V to be under the User directories?) so I'm using Windows Subsystem for Linux to try it out.

```bash
v -freestanding prod.v
cc: error: /mnt/c/programs/v-0.1.24-linux/vlib/os/bare/bare.S: No such file or directory
V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

There is indeed no bare.S file under the indicated directory. Looking at the git repository, it seems it was removed.

**Comment by bogen85** [comment]
@ConnectedSystems  I removed bare.S several weeks ago as it is no longer used.
Let me check the most recent v.

**Comment by bogen85** [comment]
I installed the most recent v (alpine Linux).
```sh
cd v/vlib/builtin/bare/.checks
v run checks.v
```

**Comment by ConnectedSystems** [comment]
@bogen85 perhaps I should clarify that I'm using the pre-built package for Linux.

I've forked the project and compiled it following the instructions. Using the freshly compiled V with the `-g` flag, I now get this message:

```bash
$ ./v -freestanding -g ../simple-lang-comparison/v/prod.v
C compiler=cc
/mnt/c/programs/ownCloud/projects/simple-lang-comparison/v/prod.v: In function ‘main__main’:
/mnt/c/programs/ownCloud/projects/simple-lang-comparison/v/prod.v:16:9: error: implicit declaration of function ‘printf’; did you mean ‘print’? [-Werror=implicit-function-declaration]
  print(result)
         ^~~~~~
         print
cc1: some warnings being treated as errors
V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

The code I'm trying out is below:

```V
fn main() {
	a := 10
	mut result := 1

	for n:=1; n <= 10000000; n++ {
		result = 1
		for i := 1; i <= a; i++ {
			result = result + (a - i) + n
		}
	}

	print(result)
}
```

Please also note that the [provided example](https://twitter.com/v_language/status/1194895149249236992) also does not compile but I do understand this was for an earlier version of V.

**Comment by bogen85** [comment]
-freestanding is work in progress and does not support printing of non string variables yet.
print in -freestanding only works with string variables and literals.

Have you tried it without -freestanding? (linked against libc whch does have printf) ?

I tried your example without -freestanding and it works. With -freestanding I get the same error message.

**Comment by bogen85** [comment]
@ConnectedSystems, see #3228

**Comment by bogen85** [comment]
@ConnectedSystems, for now you can use i64_str (see #3228)

**Comment by ConnectedSystems** [comment]
Thanks @bogen85 much appreciated.

I get an `undefined: i64_str` error when trying to use it. Do I have to import anything? (I had a quick look through the documentation and nothing stuck out). 

Yes, it does work without `-freestanding`. What I'm trying to do however is get a feel for the language and show my colleagues differences in language purpose, performance and file sizes, and syntactic readability across various languages (they mostly work with R, Python and Matlab). I'm using (or hopefully will be using rather) V as an example of a "modern" compiled language in conjunction with Go and maybe Rust.

Thanks for all your assistance.

**Comment by elimisteve** [comment]
This now works! And probably has for a while.
