### ISSUE TITLE
Remove cJSON dependency from the json module

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#309]
Write a JSON parser in V.

**Comment by ntrel** [comment]
IMO it's fine to depend on C libraries for non-core functionality like JSON, networking, graphics etc. Using existing libraries helps with stability.

**Comment by nedpals** [comment]
I'll just leave a link here just in case everyone is wondering about this:
[https://modules.vlang.io/x.json2.html](https://modules.vlang.io/x.json2.html)

**Comment by nedpals** [comment]
Closed in favor of #7032 .
