### ISSUE TITLE
how to use 2e5 in const int?

### ISSUE THREAD

**Issue by bronze1man** [vlang/v#3093]
**V version:** 
**OS:** 
https://vlang.io/play
**What did you do?**
```
const (
    msgCount = 2e5
)

fn main() {
    for i:=0;i<msgCount;i++{
    }
}
```
with error message
```
syntax error: unexpected `)`, expecting `=`
    3| )
```

**Comment by penguindark** [comment]
try this: 
```v
const (
    msgCount = int("2e5".f64())
)

fn main() {
    for i:=0;i<msgCount;i++{
    }
}
```

**Comment by Ivo-Balbaert** [comment]
The notation in the top code now (v 0.1.27) works also (tested in Windows 10 and Playground):

const (
    msgCount = 2e4
)

fn main() {
	  mut sum := 0
    for i:=0;i<msgCount;i++{
			sum += i
    }
		println(sum) // => 199990000
}
