### ISSUE TITLE
Generic methods with with pointer type params get generated with invalid names

### ISSUE THREAD

**Issue by prime31** [vlang/v#3101]
**V version:** V 0.1.23 2e23592
**OS:** macos

**What did you do?**
A generic method with a pointer parameter declaration like below ends up with an invalid generated C method name.

```c
fn column<T>(t &T) {}
```

Error: 

```
error: variable has incomplete type 'void'
void main__column_T_Pos*(Pos** t);
```

**Comment by nedpals** [comment]
Closed. Fixed in the latest V version: https://devbits.app/play/647m6pm6oxkq
