### ISSUE TITLE
Operator overloading fails to compile when an operator is overloaded with different operands

### ISSUE THREAD

**Issue by prime31** [vlang/v#3103]
**V version:** V 0.1.23 9dd86a2
**OS:** macos

**What did you do?**
I defined an overload for Mat4*Mat4. Alone, that worked fine. I next defined an overload for Mat4*Vec3. This is where the failure came from.

```c
pub fn (self Mat4) * (other Mat4) Mat4
pub fn (self Mat4) * (other Vec3) Vec3
```

**What did you expect to see?**
Succesful compilation.
 
**What did you see instead?**
> redefinition of method `prime31_dot_math.Mat4.*`

**Comment by spytheman** [comment]
Operators can not have operands of different types on purpose:
https://vlang.io/docs#op
> - Both arguments must have the same type (just like with all operators in V).

**Comment by medvednikov** [comment]
This is correct.

I've improved the errors to handle this case:
> operator overloading methods must have only 1 argument
> operators must have the same types on both sides
