### ISSUE TITLE
Faulty C code generation of nested inline ifs

### ISSUE THREAD

**Issue by Liikt** [vlang/v#3105]
**V version:** V 0.1.23 9dd86a2
**OS:** Linux 5.4.3-arch1-1

**What did you do?**
The following V code produces faulty C code.
```
command := if true { if true { 'a' } else { 'b' } } else { 'c' }
```

**What did you expect to see?**
That `command` now holds the value `a`
 
**What did you see instead?**
```
/tmp/v/.vrepl_temp.tmp.c: In function ‘main’:
/tmp/v/.vrepl_temp.tmp.c:3457:69: error: expected ‘)’ before ‘;’ token
 3457 |   (( 1 ) ? ( (( 1 ) ? ( tos3("a") ) : ( tos3("b") )) ) : ( tos3("c") 
```

**Comment by medvednikov** [comment]
Fixed.
