### ISSUE TITLE
Allow `let` to align code, easier to read

### ISSUE THREAD

**Issue by RUSshy** [vlang/v#311]
Just so we can align stuff correctly, easier to read

```go
mut user_a := User{} // mutable
let user_b := User{} // immutable
```

**Comment by medvednikov** [comment]
There are a lot of reasons current syntax has been chosen. 

I'll make a blog post about it.

**Comment by medvednikov** [comment]
To give you one argument for this example:

It's much better to have immutable variables by default.

**Comment by RUSshy** [comment]
Yes i also agree, immutability should be default, but that should exclude let to be optional keyword to align the code when reading it
