### ISSUE TITLE
Fail to submit a module to vpm

### ISSUE THREAD

**Issue by taojy123** [vlang/v#3111]
**V version:**  0.1.23
**OS:** mac
**What did you do?**
I visit https://vpm.best/new then click `Log in via GitHub` 
The page redirect to https://vpm.best/oauth_cb?code=dc449d6dd36dec256xxx
But not logged in at all, Page also as same as before.

-------

I want to submit my module `valval`

It's a web framework the improved by vweb

The home page of valval is https://valval.cool

And the github project address is https://github.com/taojy123/valval

Hope to accept my module, Thankyou!

**Comment by nedpals** [comment]
Hmmm... you seem to have the same issue with #2890 . I have added your module in the [vpkg registry](https://github.com/vpkg-project/registry) in the meantime.

**Comment by taojy123** [comment]
@nedpals , thankyou~

I see your also write a web framework (vex). 👍

I think we have a lot to do before our frameworks(including vweb) is complete 😂
