### ISSUE TITLE
Variable naming rules too strict

### ISSUE THREAD

**Issue by hillerstorm** [vlang/v#3114]
**V version:** 0.1.23 d308fef
**OS:** macos

**What did you do?**
Tried to name a variable anything >11 chars, like `instructions`, `permutations`, `registrations` etc.

**What did you expect to see?**
No error because the name is not multi-word. Having to name them `instructs`, `perms` or `regs` does not really improve readability.
 
**What did you see instead?**
> test.v:20:0: bad variable name `permutations`
looks like you have a multi-word name without separating them with `_`
for example, use `registration_date` instead of `registrationdate`

**Comment by medvednikov** [comment]
Agreed, I've set it to 15.
