### ISSUE TITLE
Calling a function pointer on struct field generates incorrect C

### ISSUE THREAD

**Issue by prime31** [vlang/v#3116]
**V version:** V 0.1.23 1071855
**OS:** macos

**What did you do?**
Attempted to store a function pointer in a struct then call it.

```v
struct Thing {
mut:
    opt fn(f32)
}

fn main() {
    mut t := Thing{}
    t.opt = tick
    t.opt(1)
}

fn tick(dt f32) {
	println('tick=$dt')
}
```

outputs C with function call on two lines:
```c
 t .opt  =  main__tick ;
 t .opt ;
 ( 1 ) ;
```

**Comment by kitech** [comment]
The same problem here. Need assign to a temporary var currently.

**Comment by medvednikov** [comment]
I think this was fixed yesterday.

Try with the latest V>

**Comment by Ivo-Balbaert** [comment]
The code above works in v 0.1.27 with result tick=1 on bith Windows 10 and the Playground.
