### ISSUE TITLE
Segfault setting the value of an optional int

### ISSUE THREAD

**Issue by prime31** [vlang/v#3117]
**V version:** V 0.1.23 1071855
**OS:** macOS

**What did you do?**

```c
struct Thing {
mut:
    opt ?int
}

fn main() {
    mut t := Thing{}
    t.opt = 5
}
```

**What did you expect to see?**
t.opt should have a value of 5
 
**What did you see instead?**
a segfault

**Comment by medvednikov** [comment]
Fixed.
