### ISSUE TITLE
2d array generation doesn't give the expected result

### ISSUE THREAD

**Issue by progamateur** [vlang/v#3118]
**V version:**  V 0.1.23 e7856a1
**OS:**  Windows 10 (1909)

**What did you do?**
Execute after compiling the folowing code:

fn main() { 
	arr_1d     := [0].repeat(2)			// 2 cols  1d array
	mut arr_2d := [arr_1d , arr_1d]	// 2 rows, 2 cols  2d array
					
	println(arr_2d)
	arr_2d[0][0] = 1
	arr_2d[0][1] = 2
	arr_2d[1][0] = 3
	arr_2d[1][1] = 4
	println(arr_2d)
}
**What did you expect to see?**

[[0, 0], [0, 0]]
[[1, 2], [3, 4]]
 
**What did you see instead?**

[[0, 0], [0, 0]]
[[3, 4], [3, 4]]

// mut arr_2d := [arr_1d , arr_1d.clone()]
//  or
// mut arr_2d := [[0].repeat(2) , [0].repeat(2)]
// gives the expected result

**Comment by hillerstorm** [comment]
Hmm... I don't personally see this as unexpected behaviour.
It's basically an array with two references to the same sub-array.
There's something to be said for the `mut` keyword allowing modification of that sub-array though, but that's another issue :)

**Comment by progamateur** [comment]
@hillerstorm,
It seems you are right but:
-  why the following  2d-array  is not referenced  to variable 'a':
       mut a := 1
       mut b := [a, a]
       println(b)    //  displays [1, 1]
       a[0]= 2
       println(b)    //  still displays [1, 1]

- 2d-array with reference to mutable sub-arrays  should be declared as mutable but there are no compilation errors for the following code:
       mut a := [1, 2]
       b := [a, a]   // should be  mut b := [a, a]
       println(b)   // displays [[1, 2], [1, 2]]
       a[0] = 3
       println(b)  //  displays [[3, 2], [3, 2]]

**Comment by medvednikov** [comment]
Your first example doesn't compile (a is an int).

In your second example, array b is not modified, it still has two same references, they are modified independently.

**Comment by progamateur** [comment]
- The first example was tested with REPL but has an error:
V 0.1.23 37add98
Use Ctrl-C or `exit` to exit
>>> mut a := 1
>>> mut b := [a, a]
>>> println(b)
[1, 1]
>>> a = 3   // a[0] = 3 was an error
>>> println(b)
[1, 1]
>>>

-  the corrected first example (with b not mutable) compiles  now:

fn main() {
	mut a := 1
	b := [a, a]
	println(b) 
	a = 3
	println(b) 
}

displays:
[1, 1]
[1, 1]

- for the second exemple: for me the first element value of b array is modified:

fn main() {
	mut a := [1, 2]
	b := [a, a]  // should be mut b := [a, a]
	println(b)  // displays [[1, 2], [1, 2]]
	a[0] = 3
	println(b)  // displays [[3, 2], [3, 2]]
}

displays :
[[1, 2], [1, 2]      // initial values of b elements
[[3, 2], [3, 2]]     // new  values of b elements after changing the first element of a => b is modified (?)
