### ISSUE TITLE
Question to low level developers (embedded, gamedev, drivers etc): are there cases where globals are required to achieve the best performance?

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#313]
I have a feeling that's the case.

Right now there are a couple of cases in V compiler where I can't think of a way to replace globals. For example, tracking and counting allocated memory.

**Comment by joe-conigliaro** [comment]
once channels are implemented couldn't they be used?

**Comment by kvinwang** [comment]
There are some C library that require the userside to maintain some global states. So there would be some trouble when interop with such c libraries.

**Comment by medvednikov** [comment]
> There are some C library that require the userside to maintain some global states. So there would be some trouble when interop with such c libraries.

Yeah, for that there will be something like

```
__global C.SomeGlobal int

unsafe fn foo() {
  C.SomeGlobal++
}
```

**Comment by kprotty** [comment]
What does the unsafe keyword do?

**Comment by zac-garby** [comment]
How could you be _required_ to maintain global state?

**Comment by ntrel** [comment]
> unsafe fn foo() {C.SomeGlobal++

Reading mutable global state is not pure, and any functions that call a function that accesses such state are themselves not pure. So impurity is infectious.

Memory safety is not necessarily infectious. You can have unsafe operations wrapped in a safe interface. Rust has unsafe blocks that are allowed inside safe functions. I don't think memory safety and purity should be mixed into one.

**Comment by kvinwang** [comment]
> How could you be _required_ to maintain global state?

for example:
```c
#include <somevoip.h>

int on_incoming_call(int account_id, int call_id) {
     // without global states, we can not do our business here.

     // for example, we need to create a new service for this new incoming call.
     // this need to be stored some where.
     service_t* service = new_service_instance(); 
}

int on_media_data(int call_id, void *data, int size) {
     // here, we need to retrieve the service instance created in on_incoming_call.
}

int main(int argc, char*argv[]) {
    voip_init(on_incoming_call, on_media_data);
    config_with_some_accounts();
    voip_eventloop();
}
```

**Comment by Restioson** [comment]
@kvinwang doesn't necessarily need to be global. See how Actix does it: https://actix.rs

**Comment by termhn** [comment]
@Restioson the point wasn't that it's the only way to do it, the point was that some (many) existing C libraries do it with globals and so not being able to do so would prevent interop with those libraries.

**Comment by Restioson** [comment]
I thought the question was:
> "are there cases where globals are required to achieve the best performance?"
as in the title

**Comment by PavelVozenilek** [comment]
IMHO it is mostly laziness to use globals to improve performance. However, I proposed long ago (#208) to allow them in debug mode only, e.g. to keep track of allocations and for other debugging purposes. If these things are passed as parameters, they would complicate the design way too much.

If a real need for global arises, the language may expand their use.



I am not aware of C library explicitly requiring user defined global variable.

----------

One related feature is to have "single global state", some structure which is invisibly and automatically passed into all functions which use it. (Jai should have it.)


E.g. if structure named `app` is defined in the main function, the compiler would take it as the default global state, and anyone could use it.

This feature, however, makes testing harder, and it also requires conditional compilation (depending on what the global state contains).

**Comment by joe-conigliaro** [comment]
@medvednikov instead of global, couldn't you do something like this?
```
struct StorageStruct
{
    int a;
    char data[256];
};

struct StorageStruct* getStorage()
{
    static struct A *instance = NULL;

    if(instance == NULL) {
        instance = malloc(sizeof(*instance));
    }

    return instance;
};
```

**Comment by medvednikov** [comment]
C's static variables are pretty much globals :) @joe-conigliaro

**Comment by joe-conigliaro** [comment]
@medvednikov true hehe
