### ISSUE TITLE
REPL output sometimes duplicated

### ISSUE THREAD

**Issue by elimisteve** [vlang/v#3136]
**V version:** V 0.1.23 0ebe86f
**OS:** Debian 9.11

**What did you do?**

I typed a simple for-loop into the V REPL twice:

```
$ v
V 0.1.23 0ebe86f
Use Ctrl-C or `exit` to exit
>>> for n in 0..5 { println(n) }
0
1
2
3
4
>>> for n in 0..5 { println(n) }
0
1
2
3
4
0
1
2
3
4
```

**What did you expect to see?**

The second time I ran the for-loop, I expected to just see numbers 0 through 4 printed once, not twice.
 
**What did you see instead?**

0-4 printed twice

Perhaps the REPL caches/memoizes the output some place, and that is not being cleared?

**Comment by elimisteve** [comment]
This issue is still there in version `V 0.1.24 51222ba`, FYI.

**Comment by Ivo-Balbaert** [comment]
This now produces the following error on Windows 10:

V 0.1.27 c9f3a05
Use Ctrl-C or `exit` to exit
>>> for n in 0..5 { println(n) }
error: expr(): bad token `for`
    1 |
    2 | println(for n in 0..5 {
      |         ~~~
    3 |  println(n)
    4 | })

**Comment by nedpals** [comment]
Closed. It has been fixed on the latest version of V.

**Comment by elimisteve** [comment]
@nedpals Thanks for solving the issue that @Ivo-Balbaert and others were having, but problem that this GitHub issue was created to talk about is still there.

**Comment by nedpals** [comment]
@elimisteve Hmm right I forgot sorry. Will fix it in a minute
