### ISSUE TITLE
Why the concurrency doesn't work?

### ISSUE THREAD

**Issue by marlock9** [vlang/v#3139]
**V version:** 0.1.23 9e11de4
**OS:** Linux

**What did you do?**
```
module main

import http

fn main() {
    for _ in 0..10 {
        go get_google()
    }
}

fn get_google() {
    resp := http.get('https://google.com') or {
	println(err)
	return
    }
    println(resp.status_code)
}
```

**What did you expect to see?**
10 x 200
 
**What did you see instead?**
../v/v -g run .
C compiler=cc
Terminated by signal 139 (SIGSEGV)

**Comment by Ivo-Balbaert** [comment]
This is not a bug, it conforms to the typical Go behavior that, when not paused long enough, the main thread ends and kills all coroutines before they can do print any output
This variant prints out 10 x 200:

import time

fn main() {
    for _ in 0..10 {
        go get_google()
    }
		time.sleep(5)
}

**Comment by marlock9** [comment]
> This is not a bug, it conforms to the typical Go behavior that, when not paused long enough, the main thread ends and kills all coroutines before they can do print any output
> This variant prints out 10 x 200:
> 
> import time
> 
> fn main() {
> for _ in 0..10 {
> go get_google()
> }
> time.sleep(5)
> }

Thank you! That works.

But it's still an issue that in documentation (https://vlang.io/docs#concurrency) there is almost nothing about concurrency. So I think maybe to not close this issue until concurrency is being well documented.

**Comment by Ivo-Balbaert** [comment]
Concurrency in V is still very much in development and a work in progress, so I think we'll have to wait for documentation about it until it has been developed and tested. You can't document something until it exists. Meanwhile the current issue, as it is not a bug, should be closed.

**Comment by marlock9** [comment]
Okay, I'm closing issue. But I think there should be at least a comment in documentation that warns about
> Concurrency in V is still very much in development and a work in progress
