### ISSUE TITLE
Single License for every file

### ISSUE THREAD

**Issue by Delta456** [vlang/v#3140]
Every `.v` file in `vlib/` should use one type of license instead of multiples as seen in https://github.com/vlang/v/blob/master/vlib/strconv/atof.v https://github.com/vlang/v/blob/master/vlib/encoding/utf8/utf8_util.v and https://github.com/vlang/v/blob/master/vlib/encoding/base64/base64.v even some files don't have any License. 

I suggest using something like how Go does it i.e. `// Copyright 2011 The Go Authors and Contributors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.`
 and have a separate file `CONTRIBUTORS.md` for list of contributors.

What you guys think?

**Comment by medvednikov** [comment]
sounds good

**Comment by medvednikov** [comment]
Actually let's leave it as it is for now, we'll take care of this later.

**Comment by Delta456** [comment]
Ok, I will open it again when more progress is done.
