### ISSUE TITLE
C symbol redefinition between two module

### ISSUE THREAD

**Issue by kitech** [vlang/v#3143]
**V version:** V 0.1.23
**OS:** linux x64

**What did you do?**
in mod1, declare a C symbol:
     `C.memcpy(voidptr, voidptr, int) voidptr`
in mod2, declare the same C symbol:
     `C.memcpy(voidptr, voidptr, int) voidptr`

**What did you expect to see?**
compile ok
 
**What did you see instead?**
redefinition of `memcpy`

**Comment by danieldaeschle** [comment]
Works in latest V
