### ISSUE TITLE
`v run .`, `v .`, `v <file>.v`, `v run <file>.v` have different result.

### ISSUE THREAD

**Issue by changrui** [vlang/v#3146]
**V version:** 
*v 0.1.23*
**OS:** 
*Windows10*, *Ubuntu 20.04*

**What did you do?**
    `v run .`
    `v run file.v`
     `v .`
     `v file.v`
     `v -prod .`
     `v -prod file.v`

**What did you expect to see?**
     *running or compiling well.*
 
**What did you see instead?**
    *VCasino.v* as an example:
         `v run VCasino.v` is OK.
          `v run .`  got:  .\VCasino.v:1:10: syntax error: unexpected `import`, expecting `module`;
          `v .` as `v run`;
          `v -prod .`: as `v run .`;
          `v VCasino.v`: OK!
           `v -prod VCasino.v`: OK.

*I think `module main* is needed.*

**Comment by zhylmzr** [comment]
If you specify a file name, `v` will be compiled in script mode. At this time, you can omit the `module main` declaration.

**Comment by nedpals** [comment]
This should be documented as a head's up for users.

**Comment by serkonda7** [comment]
Works fine with recent V.
