### ISSUE TITLE
`mut` declaration assignment doesn't copy

### ISSUE THREAD

**Issue by zhylmzr** [vlang/v#3147]
**V version:** V 0.1.23 37add98
**OS:** macOS 10.14.5

**What did you do?**
When `mut` declaration assigning complex types, v does not make duplicate copies, which may cause the following problems:
```v
fn main() {
	a := [1, 2, 3, 4, 5]
	mut b := a

	b << 6	// b.data maybe realloc
	println('$a a.data: $a.data')
	println('$b b.data: $b.data')
}
```
`a` and `b` have the same value at the bottom, but if new elements of `b` may cause the underlying array pointer `.data` to be `realloc`, `realloc` may cause the original memory space to be invalid While allocating new memory

**What did you expect to see?**
Consider copying assignments like `go`.
```go
package main

import "fmt"

func main() {
	a := [...]int{1, 2, 3}
	b := a
	b[0] = 0
	fmt.Println(a, b) // [1 2 3] [0 2 3]
}
```
 
**What did you see instead?**
The `a` array may be corrupted.

See also #3102

**Comment by danieldaeschle** [comment]
The current output is:
```
[1, 2, 3, 4, 5] a.data: 32866864
[1, 2, 3, 4, 5, 6] b.data: 32866864
```

is this good for you?

**Comment by Ivo-Balbaert** [comment]
To illustrate what zhylmzr meant:  if you add the line:  	b << [101,102,103,104,105,106]

then the output becomes:

[91, 32, 32, 32, 32] a.data: 000000000002EF80
[1, 2, 3, 4, 5, 6, 101, 102, 103, 104, 105, 106] b.data: 0000000000022A50

We see reallocation of b with correct data, but a is totally corrupted.

**Comment by Ivo-Balbaert** [comment]
If however we change the code (as was done in #3102) to:

        a := [1, 2, 3, 4, 5]
	mut b := a.clone()

	b << 6	// b.data maybe realloc
	b << [101,102,103,104,105,106]
	println('$a a.data: $a.data')
	println('$b b.data: $b.data')

[1, 2, 3, 4, 5] a.data: 0000000000D0EF80
[1, 2, 3, 4, 5, 6, 101, 102, 103, 104, 105, 106] b.data: 0000000000D02A30

So if you want a real copy, use the clone() method.  This should be documented.
SInce the argument to use clone() was used to close #3102, this issue can then be closed as well.
