### ISSUE TITLE
Optional returns by reference doesn't compile

### ISSUE THREAD

**Issue by prime31** [vlang/v#3151]
**V version:** V 0.1.23 aa0ad9d
**OS:** Mac OS

**What did you do?**
The following code will fail to compile due to the optional ref return.

```v
struct Pos { 
	x int
}

fn make() ?&Pos {
	return none
}
```

**What did you expect to see?**
Compilation to succeed.
 
**What did you see instead?**
A C error due to the generate method having a `*` in the name.

**Comment by ka-weihe** [comment]
Works in V 0.1.26 50a8373.
