### ISSUE TITLE
Add SystemZ, PowerPC and AArch8 builds to CI

### ISSUE THREAD

**Issue by XVilka** [vlang/v#3152]
For more information see [Multiarchitecture support](https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support) and [Build your open source projects on IBM Power and IBM Z CPU architecture](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) blog posts from Travis CI.

**Comment by medvednikov** [comment]
All these architectures are automatically supported.

**Comment by XVilka** [comment]
@medvednikov but there is no CI for them, that's what I am talking about.
