### ISSUE TITLE
Assign a const to another not working

### ISSUE THREAD

**Issue by kitech** [vlang/v#3159]
**V version:** V 0.1.23 a81c6f4
**OS:** linux x64

**What did you do?**
```v
const (
	s2 = s1
)
const (
	s1 = 'foo'
)
fn main() {
	println(s2)
}
```

**What did you expect to see?**
`foo`
 
**What did you see instead?**
empty

Something already known:
if swap the definition order, it works.
if put two constant definition in two file, the final value is not sure which one.

**Comment by ka-weihe** [comment]
Works in V 0.1.26 50a8373.
