### ISSUE TITLE
REPL can not running at freeBSD 12.1: no method `read_line`.

### ISSUE THREAD

**Issue by changrui** [vlang/v#3165]
**V version:** 
       V 0.1.23 fbd9fed
**OS:** 
       freeBSD 12.1
**What did you do?**
      ./v

**What did you expect to see?**
      v 0.1.23
      >>>
 
**What did you see instead?**
     vrepl.v:  `readline.Readline` has no field or method `read_line`,

**Comment by medvednikov** [comment]
Fixed.
