### ISSUE TITLE
Struct initializers with array elements throws errors

### ISSUE THREAD

**Issue by prime31** [vlang/v#3168]
**V version:** V 0.1.23 f7c1b78
**OS:** macos

**What did you do?**
Attempted to initialize a struct with a fixed array.
```
struct Pos { 
	x int
	arr [4]int
}


fn main() {
	pos := Pos{
		x: 6
		arr[0]: 5
	}
}
```

**What did you expect to see?**
Successful compilation
 
**What did you see instead?**
```next token = `0`

bug.v:12:7: syntax error: unexpected `[`, expecting `:` 10| pos := Pos{ 11| x: 6 12| arr[0]: 5 ^ 13| } 14| }
```

**Comment by Ivo-Balbaert** [comment]
I don't think you can initialize an array field in a struct like that, but I can't come up with a valid initialization that compiles.

**Comment by ntrel** [comment]
> arr[0]: 5

This is invalid, V doesn't support partial fixed array initialization. 

You can initialize it like this:
```v
arr: [4]int{} //does nothing
```
```v
arr: [4]int{init: 7} //recent, sets all elements to 7
```
You can also use a fixed array literal, but the syntax for that is only temporary:
```v
arr: [1,2,3,4]!!
```

**Comment by Ivo-Balbaert** [comment]
So this issue can be closed, because V doesn't support partial fixed array initialization.
