### ISSUE TITLE
Why struct.str() must be declared as *public*?

### ISSUE THREAD

**Issue by changrui** [vlang/v#3172]
**V version:** 
`v 0.1.23`
**OS:** 
`Windows 10`

**What did you do?**

print struct using self defined function `str()`.
`struct Person {name string age int}
p := Person{'Joe', 25}
println(p.str())               // println(p) not running when redefined str()

fn (p *Person) str() string { return 'name: $p.name, age: $p.age\.' }
`

**What did you expect to see?**
*name: Joe, age: 26*
 
**What did you see instead?**
*  .str() must be declared as *public*.

**Comment by cliserkad** [comment]
I think you need to prepend `pub` to the function declaration

**Comment by alexesprit** [comment]
I'm not sure if this is an actual issue, as `pub` is used to distinguish public and private functions (in this particular case public and private methods (struct functions)). Also, the correct example is:

<details>
  <summary>Example 1 (Click to expand)</summary>

```v
struct Person {
	name string
	age int
}

// No asterisk symbol or `mut` keyword
pub fn (p Person) str() string {
	// No dot symbol at the end of string, as it produces a bug
	// in string interpolation (at least for me)
	return 'name: $p.name, age: $p.age'
}

fn main() {
	p := Person{ 'Joe', 25 }
	println(p.str())
}
```
</details>


Also, an example where public and private functions are together:
<details>
  <summary>Example 2 (Click to expand)</summary>

```v
struct Person {
	name string
	age int
}

// The function is private and can't be called directly
fn (p Person) str_internal() string {
	return 'name: $p.name, age: $p.age'
}

pub fn (p Person) str() string {
	// But it can be called inside public or private function
	return p.str_internal()
}

fn main() {
	p := Person{ 'Joe', 25 }
	println(p.str())
}
```
</details>

**Comment by medvednikov** [comment]
It needs to be public so that it can be called from other modules.
