### ISSUE TITLE
`filepath` and `os` have the same function

### ISSUE THREAD

**Issue by alexesprit** [vlang/v#3179]
I was writing a test file for `filepath` module, and noticed `filepath` and `os` modules contains `ext` function. The function is exactly the same in both modules, the code is slighty different, though.

I'm definetely sure there should be only one function, but I'm not sure where to keep it.

I think it should be placed in `filepath` module, and be removed from `os` module. Also, some functions related to work with file paths should be moved in `filepath` module; something similar is done in Node.js and Python (`os`/`fs` module for file manipulations, `path` module for working with file paths).

What do you think?

**Upd**: sorry for wrong issue type. I'm not sure if this is a bug, but it's not a feature request too.

**Comment by medvednikov** [comment]
Good find.

You are right :)
