### ISSUE TITLE
Add operator overloading for `|`, at least in .vsh files, so we can pipe shit together

### ISSUE THREAD

**Issue by elimisteve** [vlang/v#3191]
Imagine being able to create more Bash-like .vsh scripts that do things like

    xz -cd data.tar.xz | tar -xvf -

but in V:

    exec('xz -cd data.tar.xz') | exec('tar -xvf -')

This may be overkill, but... kind of a fun idea!

**Comment by elimisteve** [comment]
...or maybe a simple function built into `os` would be plenty good enough:

    pipe('xz -cd data.tar.xz', 'tar -xvf -')

**Comment by dumblob** [comment]
I think the pipe operator could be "overloaded" at some point for channels (between go routines) - for more information (incl. go routine reentrancy) see https://github.com/vlang/v/issues/1868 .

**Comment by elimisteve** [comment]
Good point @dumblob :+1:

Closing the idea above as this is unnecessarily complexity; an `os.pipe` function or similar would be better.

**Comment by ofabricio** [comment]
Like Built-in ORM:

```mysql
customers := sql db {
    select count from Customer
}
```

What do you think about a built-in sh? Say:

```sh
output_value := shell {
    cat sample.txt | head -7 | tail -5
}
```

I'll suggest this in the proper topic too.

**Comment by dumblob** [comment]
@ofabricio that has one major downside - it's not compatible with the rest of the V ecosystem. So users would require more and more functionality in such a dedicated block and we would end up with a reimplemented [`nushell`](https://www.nushell.sh/book/ ).
