### ISSUE TITLE
make clean: v binary was removed!  

### ISSUE THREAD

**Issue by changrui** [vlang/v#3194]
**V version:**                 `v 0.1.13`
**OS:**                           `ubuntu 20.04 daily`

**What did you do?**
make clean

**What did you expect to see?**
remove temporary files. 
 
**What did you see instead?**
`v` was removed.

**Comment by vitalyster** [comment]
`make clean` usually remove executables - https://www.gnu.org/software/make/manual/html_node/Cleanup.html
