### ISSUE TITLE
typeof

### ISSUE THREAD

**Issue by r-k-o** [vlang/v#3199]
hi,
please implement typeof or similar. it should work with regular and generics.
thank you

**Comment by nedpals** [comment]
Currently trying to implement this one by auto-generating a `typ` struct field as what I've seen here: [https://vlang.io/docs#codegen](https://vlang.io/docs#codegen).

Compile-time reflection is a complex thing to implement but small things like these can be feasible.

**Comment by nedpals** [comment]
Closed. You made a similar issue regarding this feature request: #2850
