### ISSUE TITLE
Error when compiling tetris on Windows

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#3204]
**V version:** V 0.1.23 411a83e
**OS:**  Windows 10

**What did you do?**
Tried to compile tetris:     v tetris.v

**What did you expect to see?**
Successful compilation
 
**What did you see instead?** with v -g tetris.v
C compiler=gcc
In file included from c:\v\thirdparty\stb_image/stb_image.h:547,
                 from E:\Vlang\The_Way_to_V\Chapter_13_Standard_Library_vlib\tetris\tetris.v:545:
c:\v\thirdparty\stb_image/stb_image.h: In function 'stbi__shiftsigned':
c:\v\thirdparty\stb_image/stb_image.h:5116:18: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
    STBI_ASSERT(v >= 0 && v < 256);
                  ^~
c:\v\thirdparty\stb_image/stb_image.h:5116:4: note: in expansion of macro 'STBI_ASSERT'
    STBI_ASSERT(v >= 0 && v < 256);
    ^~~~~~~~~~~
E:\Vlang\The_Way_to_V\Chapter_13_Standard_Library_vlib\tetris\tetris.v: At top level:
E:\Vlang\The_Way_to_V\Chapter_13_Standard_Library_vlib\tetris\tetris.v:548:10: fatal error: ft2build.h: No such file or directory
compilation terminated.
V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

Same error when compiling empty_gg_freetype.v
On Ubuntu, both files compile correctly.

**Comment by vitalyster** [comment]
From the README:
```
In order to build Tetris and anything else using the graphics module, you will need to install glfw and freetype libraries.

...
Windows:
git clone --depth=1 https://github.com/ubawurinna/freetype-windows-binaries [path to v repo]/thirdparty/freetype/
```

**Comment by Ivo-Balbaert** [comment]
Thanks, stupid error. Had previously done so, but had forgotten to do it after a new installation.

**Comment by sq16** [comment]
There is a mention of needing the glfw library for Windows but not of a freetype library here: https://github.com/vlang/v/tree/master/examples/tetris

**Comment by afonichev** [comment]
The same thing

**V version:** V 0.1.23 3a7f1db
**OS:** Windows 10

![image](https://user-images.githubusercontent.com/15726637/71594639-b5beaa80-2b49-11ea-968a-cd44d8730c07.png)
