### ISSUE TITLE
Experimental thirdparty GC integeration, just show the possibility

### ISSUE THREAD

**Issue by kitech** [vlang/v#3210]
Thanks vlang's nice C compatibility, integeration GC into vlang is possible now.

With this solution, now can write vlang code without think too much about memory, for vlang currently lack of complete memory management.

Such as the often used types, like string, array, map, don't need write string.free, array.free, map.free everywhere. For custom struct type, it's sill works fine, not need definition a free method any more.

And also for now, program wrote by vlang can run long time without memory problem, such as days, weeks or even more.

Minimal change sets:
https://github.com/kitech/v/blob/mine/gctool/replace_malloc.sh
https://github.com/kitech/v/blob/mine/vlib/builtin/builtin_bdwgc.v

Note: only tested on linux

**Comment by varuzam** [comment]
Integration GC to V will make its yet another Golang :-)

**Comment by penguindark** [comment]
gs support added as option.
