### ISSUE TITLE
Fixed size multi-dimensional arrays are not accessible or editable

### ISSUE THREAD

**Issue by prime31** [vlang/v#3226]
**V version:** 
**OS:** 

**What did you do?**

```c
struct Thing { 
	arr [5][10]int
}

fn main() {
	mut x := &Thing{}
	x.arr[0][0] = 6
}
```

**What did you expect to see?**
I expected to be able to set the value of `arr[0][0]`
 
**What did you see instead?**
The following error:
> unexpected token: `=`
7| fn main() {
8| mut x := &Thing{}
9| x.arr[0][0] = 6 ^
10| }

**Comment by ka-weihe** [comment]
Works in V 0.1.26 50a8373. The field `arr` has to be mutable though:
```
struct Thing { 
mut:
	arr [5][10]int
}

fn main() {
	mut x := &Thing{}
	x.arr[0][0] = 6
}
```
