### ISSUE TITLE
Missing compiler source

### ISSUE THREAD

**Issue by qookei** [vlang/v#323]
The translated compiler source code which should be at https://vlang.io/v.c does not exist. This prevents anyone from building a compiler for V.

**Comment by Bowero** [comment]
I'm certain he's working on it. Let's stop creating issues now.

**Comment by qookei** [comment]
The language was already released late, he should've prepared for the release instead of making people actually interested in it wait.

**Comment by edgeyboy** [comment]
Out now

https://vlang.io/v.c

**Comment by Restioson** [comment]
Great! Gonna spin up a docker container and check it out :)
