### ISSUE TITLE
run crash in windows 10:v 0.1.23

### ISSUE THREAD

**Issue by funnywwh** [vlang/v#3234]
D:\v_windows>v
print_backtrace_skipping_top_frames is not implemented on this platform for now...

D:\v_windows>ver

Microsoft Windows [版本 10.0.18362.535]

v -v 
show nothing

**Comment by funnywwh** [comment]
complie all .v file crash

**Comment by sq16** [comment]
Seems to be same issue as I had. 
Windows binary in the site is outdated. So, build V yourself with:
   git clone https://github.com/vlang/v
   cd v
   make
The v.exe generated then runs OK :-)
