### ISSUE TITLE
V always crashing in W10 1909

### ISSUE THREAD

**Issue by sq16** [vlang/v#3235]
**V version: latest; v -v does not work** 
**OS: Windows 10 1909** 

**What did you do?**
Running v withpout parameters gives:
print_backtrace_skipping_top_frames is not implemented on this platform for now...
The only thing working is: v -h
When I try to compile anything with any cmdline options, v crashes and generates a Windows application error.

**What did you expect to see?**
Compilation messages and results and an exe file.
 
**What did you see instead?**
No messages whatsoever. Instead this Window application error:
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-12-27T09:51:30.069824100Z" /> 
  <EventRecordID>5258</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>HP</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>v.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>00000000</Data> 
  <Data>v.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>00000000</Data> 
  <Data>c0000005</Data> 
  <Data>000000000006a635</Data> 
  <Data>269c</Data> 
  <Data>01d5bc9b36975220</Data> 
  <Data>E:\Programs\V\v.exe</Data> 
  <Data>E:\Programs\V\v.exe</Data> 
  <Data>e22d3aa5-72d7-4f89-ac50-cef48d6a88cc</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by vitalyster** [comment]
Please build latest git version, website version is outdated

**Comment by sq16** [comment]
Built from source. Issue appears to be solved. 
Culprit is outdated binary for Windows on the website ...
Thx!
