### ISSUE TITLE
Critical V errors when compiling tetris.v on Windows 10

### ISSUE THREAD

**Issue by sq16** [vlang/v#3236]
**V version: V 0.1.23 c9be519** 
**OS: Windows 10 1909** 

**What did you do?**
v tetris.v

**What did you expect to see?**
Normal compilation result.
 
**What did you see instead?**
E:\Programming\v\src\tetris>v tetris.v
E:\Programming\V\vbuild\v\thirdparty\glad\glad.o not found, building it...

C:\WINDOWS\TEMP\v\tetris.tmp.c:147:0: warning: "UNICODE" redefined
 #define UNICODE

<command-line>:0:0: note: this is the location of the previous definition
In file included from E:\Programming...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

E:\Programming\v\src\tetris>v -g tetris.v
C compiler=gcc
E:\Programming\v\src\tetris\tetris.v:544:0: warning: "UNICODE" redefined
<command-line>:0:0: note: this is the location of the previous definition
In file included from E:\Programming\V\vbuild\v\thirdparty\stb_image/stb_image.h:547:0,
                 from E:\Programming\v\src\tetris\tetris.v:544:
E:\Programming\V\vbuild\v\thirdparty\stb_image/stb_image.h: In function 'stbi__shiftsigned':
E:\Programming\V\vbuild\v\thirdparty\stb_image/stb_image.h:5116:18: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
    STBI_ASSERT(v >= 0 && v < 256);
                  ^
E:\Programming\V\vbuild\v\thirdparty\stb_image/stb_image.h:5116:4: note: in expansion of macro 'STBI_ASSERT'
    STBI_ASSERT(v >= 0 && v < 256);
    ^~~~~~~~~~~
E:\Programming\v\src\tetris\tetris.v: At top level:
E:\Programming\v\src\tetris\tetris.v:547:22: fatal error: ft2build.h: No such file or directory
compilation terminated.
V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by vitalyster** [comment]
https://github.com/vlang/v/issues/3204

**Comment by afonichev** [comment]
The same thing

**V version:** V 0.1.23 3a7f1db
**OS:** Windows 10

![image](https://user-images.githubusercontent.com/15726637/71594808-64fb8180-2b4a-11ea-9c01-f53c427d94b1.png)
