### ISSUE TITLE
Function inside a function

### ISSUE THREAD

**Issue by zaoqi** [vlang/v#3247]
```vlang
fn double(i int) int{
 fn g(n int) int {
  return n+i
 }
 return g(i)
}
fn main() {
 println(double(1))
}
```
I want to build success but it showed
```
unexpected token: `fn`
    1| fn double(i int) int{
```

**Comment by r-k-o** [comment]
yes, yes, i really wished we could have that!

**Comment by nedpals** [comment]
Might as well be perfect to just have anonymous functions assigned to a variable

**Comment by donnisnoni95** [comment]
agree with @nedpals  ☝️

**Comment by r-k-o** [comment]
Take as look at "https://en.wikipedia.org/wiki/Nested_function". It provides for elegant programs and less global variables.

**Comment by medvednikov** [comment]
This will work like in Go and like @nedpals suggested: anonymous functions assigned to a variable.

**Comment by nedpals** [comment]
Look, we aren't trying to duplicate what Javascript and other programming languages did with multiple ways of writing a function inside a function and it makes so much sense to this:
```v
fn double(i int) int{
 g := fn (n int) int {
  return n+i
 }
 return g(i)
}
fn main() {
 println(double(1))
}
```
than the example you have suggested. It's clear and easier to parse both by the user and v compiler.

**Comment by mokafolio** [comment]
I agree with @nedpals. This would reduce redundancy and might also be a clear answer to https://github.com/vlang/v/issues/163 . I personally think that having anonymous functions is good enough for both of these things.

**Comment by lutherwenxu** [comment]
As mentioned above, the way to do it in V would to be assigning a lambda to a variable.
