### ISSUE TITLE
Build a shared library: function `main` is not declared in the main module

### ISSUE THREAD

**Issue by dreamsxin** [vlang/v#3248]
**V version:** V 0.1.23 0bdf9bb
**OS:** Ubuntu 16.04

**What did you do?**
```shell
v -shared code/modules/mytext/mytext.v
```

**Comment by r-k-o** [comment]
that would be  very useful!

**Comment by Ivo-Balbaert** [comment]
This error is not given anymore (v 0.1.27).
On Ubuntu 20 a test.so is generated.
So this issue can probably be closed. However, on Windows 10 also a test.so is generated, this should probably be called test.dll
