### ISSUE TITLE
FTP structure has to be public

### ISSUE THREAD

**Issue by sha0coder** [vlang/v#3251]
for any reason in the tests the structure can be created ok, but not on an external app.
Like socket struct ftp struct has to be public

->struct FTP
+>pub struct FTP

**Comment by thecodrr** [comment]
Why? You have `net.ftp.new()`

**Comment by sha0coder** [comment]
you are right, also it't possible:
```
module main

import net.ftp

fn main() {
  ftp := ftp.new()
}
```
