### ISSUE TITLE
Support else blocks in or statements

### ISSUE THREAD

**Issue by radare** [vlang/v#3255]
**V version:** V 0.1.23 b5fe406
**OS:** macos 10.15

**What did you do?**

<img width="572" alt="Screenshot 2019-12-28 at 23 41 43" src="https://user-images.githubusercontent.com/917142/71550398-a9164700-29cf-11ea-9996-2b759817819b.png">

**What did you expect to see?**

the else block statement to be supported there, this way we can save some returns and make the flow more logic in some non-fatal cases 

**What did you see instead?**

compile error. syntax not supported

**Comment by nedpals** [comment]
This isn't a bug. The `or` block was meant to be what you have proposed right now. Or else you can do like this:
```
if dir := os.ls(db_path) {
  // executes here if there are contents in db_path
} else {
  // fails
}
```
