### ISSUE TITLE
Can't properly set a default value to an enum field of a struct

### ISSUE THREAD

**Issue by nsauzede** [vlang/v#3267]
**V version:** V 0.1.23 2d2e030
**OS:** ClearLinux

**What did you do?**
I try to set a default value to an enum field of a struct,  but get strange behaviour :

~/perso/git/realist/rtiow$ cat bug.v 
module main
enum MType {
	lambertian
	metal
}
struct MLambertian {
	mtype MType = MType.lambertian
}
struct MMetal {
	mtype MType = MType.metal
}
fn main(){}
~/perso/git/realist/rtiow$ v bug.v
warning: bug.v:10:26: `MType.metal` is unnecessary, use `.metal`
warning: bug.v:7:31: `MType.lambertian` is unnecessary, use `.lambertian`
warning: bug.v:10:26: `MType.metal` is unnecessary, use `.metal`

=> so I follow the compiler instructions and now do :

~/perso/git/realist/rtiow$ cat bug.v 
module main
enum MType {
	lambertian
	metal
}
struct MLambertian {
	mtype MType = .lambertian
}
struct MMetal {
	mtype MType = .metal
}
fn main(){}
~/perso/git/realist/rtiow$ v bug.v
bug.v:7:16: unknown enum: ``
    5| }
    6| struct MLambertian {
    7| 	mtype MType = .lambertian
             	        ^
    8| }
    9| struct MMetal {

**What did you expect to see?**

I expected to see :

~/perso/git/realist/rtiow$ cat bug.v 
module main
enum MType {
	lambertian
	metal
}
struct MLambertian {
	mtype MType = .lambertian
}
struct MMetal {
	mtype MType = .metal
}
fn main(){}
~/perso/git/realist/rtiow$ v bug.v

 
**What did you see instead?**
see above

**Comment by ka-weihe** [comment]
Works in V 0.1.26 50a8373
