### ISSUE TITLE
Not possible to append an element to a mutable array if it is inside a function

### ISSUE THREAD

**Issue by hfont** [vlang/v#3272]
**V version:** 0.1.23 b5fe406
**OS:** Linux archlinux 5.4.6-zen1-1-zen

**What did you do?**

I was passing a dynamic matrix to a function with the intention of adding elements

**What did you expect to see?**

I hoped from the moment I had the matrix set to "mut" that he could modify the elements as well as add using realloc 

**What did you see instead?**

I got this error message "for now it's not possible to append an element to a mutable array argument `vec`"
```v
fn fun(vec mut []int) {
	for i := 0; i < 1000; i++ {
		vec << i
		// println('len = ${vec.len} cap = ${vec.cap}')
	}
}
```
```v
fn main() {	
	mut vec := []int
	fun(mut vec)
	println(vec)
}
```

**Comment by zhylmzr** [comment]
You can use this way:
```v
fn fun() []int {
	mut vec := []int
	for i := 0; i < 1000; i++ {
		vec << i
	}
	return vec
}

fn main() {	
	vec := fun()
	println(vec)
}
```

**Comment by hfont** [comment]
@zhylmzr 

Thanks for answering

I was aware that way but that would not generate a cost to copy the array?

I used to do this in C

```c
int fun(int** arr) {
    // *arr
    // malloc(x);
    // relloc(x);
}

int main() {
    int** arr = NULL:
    fun(&arr);
    return 0;
}
```

**Comment by serkonda7** [comment]
Works fine with V 0.1.29 4774c89
