### ISSUE TITLE
can we define the syntax?

### ISSUE THREAD

**Issue by wanjochan** [vlang/v#3277]
Dear author, though vlang is very cool, I'm just wondering can we custom the language syntax? for example, keyword-less or js-like ?

**Comment by Bowero** [comment]
This is not possible in any other way than forking the repository and changing it to your likings.

**Comment by nedpals** [comment]
V that is customizable like macros is insanely complex. You might wanna fork the language just like others do.

**Comment by wanjochan** [comment]
Thanks bros, and do you know any one of the forks and give some links? Thanks very much!

**Comment by nedpals** [comment]
There are many forks of V, but most of them just adds functionality (add GC support) or to support a VM/runtime like CLR. If there are any new links, we will post them here.

**Comment by zaoqi** [comment]
You might want to write a preprocessor
