### ISSUE TITLE
Calling a method via string in a generic that doesnt exist fails

### ISSUE THREAD

**Issue by prime31** [vlang/v#3278]
**V version:** V 0.1.23 3a7f1db
**OS:** ubuntu

**What did you do?**
When attempting to call a method with a string that doesnt exist an error occurs. With the example below just delete the "do_it" method to see the error.

```c
pub struct Holder {
mut:
	t int
}

fn main() {
	h := Holder{}
	test(mut h)
}

// bug: comment out this method: error: ‘else’ without a previous ‘if’
fn (h &Holder) do_it() {
	println('do_it')
}

fn test<T>(ctx mut T) {
	action := 'do_it'
	ctx.$action() or {
		println('doesnt exist asshole')
	}

	ctx.t = 6
}
```

**What did you expect to see?**
Runs correctly
 
**What did you see instead?**
 error: ‘else’ without a previous ‘if’

**Comment by nedpals** [comment]
Closed. In the latest version of V, comp-time method invocation works properly. With the addition of compile-time method checking so an OrBlock would not be needed anymore for example:
```
main.v:8:11: error: `h` is immutable, declare it with `mut` to make it mutable
    6 | fn main() {
    7 |     h := Holder{}
    8 |     test(mut h)
      |              ^
    9 | }
   10 |
main.v:18:10: error: could not find method `nope`
   16 | fn test<T>(mut ctx T) {
   17 |     action := 'nope'
   18 |     ctx.$action()
      |          ~~~~~~
   19 | 
   20 |     ctx.t = 6
```
DevBits: https://devbits.app/play/0vmaIVrgVpgK
