### ISSUE TITLE
Calling a method by a string does not work for non-mut variables

### ISSUE THREAD

**Issue by prime31** [vlang/v#3279]
**V version:** V 0.1.23 3a7f1db
**OS:** ubuntu

**What did you do?**
The following will only work if the struct passed to "test_broke" is mutable.
```c
pub struct Holder {
mut:
	t int
}

fn main() {
	h := Holder{}
	test_broke(h)
}

// bug 2: comment out this method: error: ‘else’ without a previous ‘if’
fn (h &Holder) do_it() {
	println('do_it')
}

fn test_broke<T>(ctx &T) {
	action := 'do_it'
	ctx.$action() or {}
}
```

**What did you expect to see?**
The program should compile and run.
 
**What did you see instead?**
"`ctx` needs to be a reference" error

**Comment by Ivo-Balbaert** [comment]
The error is now (v 0.1.27):

test.v:18:6: error: unexpected `$`, expecting `name` 
   16 | fn test_broke<T>(ctx &T) {
   17 |     action := 'do_it'
   18 |     ctx.$action() or {}
      |         ^
   19 | }

which is correct: the $ can only be used inside a string. You cannot construct a function name like this and then call that function.

This doesn't work either:  error: bad token $

fn add(x, y int) int {
    return x + y
}


fn main() {
    do_it := 'add'
    a := $do_it(1, 2)
    println(a)
}
