### ISSUE TITLE
Implement rand

### ISSUE THREAD

**Issue by edgeyboy** [vlang/v#328]
https://github.com/vlang/v/blob/d32e538073e55c603992b5b65ebc837b01c28576/rand/rand.v#L10-L13

literally https://www.xkcd.com/221/

![](https://imgs.xkcd.com/comics/random_number.png)

**Comment by jgouly** [comment]
I think the lines starting with # are emitted as C code, so I think this will produce a random number.

**Comment by edgeyboy** [comment]
Good point, they do do that.

Then it should be implemented, yeah.

**Comment by edgeyboy** [comment]
Why did you close this?

**Comment by nico-abram** [comment]
This looks like a valid issue to me?

**Comment by Restioson** [comment]
@nico-abram it is implemented, just in C

**Comment by dumblob** [comment]
An improvement to the `next()` routine to avoid the slow modulo operation: https://github.com/lemire/fastrange .
