### ISSUE TITLE
Undefined: `os.rmdir_recursive` (in module `os`) 

### ISSUE THREAD

**Issue by Tembocs** [vlang/v#3281]
**V version:** 
V 0.1.23 349576b
**OS:** 
Window 10 build 19041.1

**What did you do?**
Build a V source file with a line ```os.rmdir_recursive(some_directory)```

**What did you expect to see?**
Successful compilation.
 
**What did you see instead?**
Error message: ```Undefined: `os.rmdir_recursive` (in module `os`)```

**Comment by spytheman** [comment]
This was introduced in 4f173c8900eb98f89e1368cd292a7a206614fae8 . Please update your v installation with `v up` or make a fresh v clone.
