### ISSUE TITLE
How to write a function `printf(fmt ...charptr)` to call C.printf(...)?

### ISSUE THREAD

**Issue by changrui** [vlang/v#3286]
// printf print something with format
`#include <stdio.h>`
`fn printf(fmt ...charptr) {`
    `C.printf(fmt)`
`}`
`printf(c'%5.2f',12.3)`

#Want `    12.30` but get nothing.

**Comment by vitalyster** [comment]
It will work on non-Windows but strongly prohibited on Windows because of stdout is switched to UTF-16 mode while `printf` uses ANSI encoding. It is strongly recommended to format output with V's println, e.g. `println("$var:5.2f")`

**Comment by changrui** [comment]
@vitalyster oh, i see, thank you very much.
