### ISSUE TITLE
Fail to  building-a-simple-web-blog-with-vweb

### ISSUE THREAD

**Issue by shawnye** [vlang/v#3289]
**V version:** 
V 0.1.24 51222ba

**OS:** 
windows 10

**What did you do?**
`v blog.v`

**What did you expect to see?**
build ok.
 
**What did you see instead?**
<pre>
D:\v\tutorials\code\blog>v blog.v
warning: D:\v\vlib\vweb\vweb.v:388:1: the following imports were never used:
 * http (net.http)
warning: D:\v\vlib\vweb\vweb.v:140:13: type `App` is private
D:\v\vlib\vweb\vweb.v:285:10: type `App` has no field or method `reset`
  283|  }
  284|  conn.close() or {}
  285|  app.reset()
                  ^
  286| }
  287|
</pre>

**Comment by TheBlueFireFox** [comment]
same error on the Linux version

(side note happy new year)

**Comment by xavierdej** [comment]
And for what it is worth ... also on mac.

**Comment by fredericosilva** [comment]
It seems that a `pub fn (app mut App) reset() {}` is required

**Comment by shawnye** [comment]
Built 32bit ok with `V 0.1.25 ea9961a`.
