### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ghost** [vlang/v#3296]
Using Windows 0.1.23.1, I get this with CMD:

~~~
C:\Users\Steven\Desktop\v_windows\examples> ..\v hello_world.v
v.exe has stopped working
~~~

and this with Cygwin:

~~~
$ ../v hello_world.v
Segmentation fault
~~~

**Comment by nedpals** [comment]
Seems like you are using on an old version of V. Can you try updating it using `v up`?

**Comment by cup** [comment]
@nedpals `v up` fails as well

**Comment by nedpals** [comment]
@cup Try `git pull` inside the v compiler folder then execute `make`.

**Comment by cup** [comment]
Sorry I am not interested in advanced troubleshooting. I just wanted it to be known that Windows build is currently broken. Good luck.

**Comment by nedpals** [comment]
@cup  I have downloaded the Windows build and it does fail but not the error as you have mentioned. Cloning and building it manually on the other hand works properly without any problems at all so you might wanna try that.

**Comment by cup** [comment]
I will wait until release unless a CI artifact is available

**Comment by nedpals** [comment]
Okay then. Thanks for reporting.

**Comment by nedpals** [comment]
The newer package of V for Windows has been working without any problems. Closed.
