### ISSUE TITLE
Ranges: Inclusive and exclusive operators

### ISSUE THREAD

**Issue by Gundolf68** [vlang/v#3302]
```v
for i in 1..5 {
   println(i)
}
// incl (..): will print 1, 2, 3, 4, 5

for i in 1...5 {
   println(i)
}
// excl (...): will print 1, 2, 3, 4
```

**Comment by SleepyRoy** [comment]
I agree with having the two operators, but propose the different syntax below.
```
for i in 1..5 {
     println(i)   // 1,2,3,4,5
}

for i in 1<..5 {
    println(i)  // 2,3,4,5
}

for i in 1..<5 {
    println(i)  // 1,2,3,4
}

for i in 1<..<5 {
    println(i)  // 2,3,4
}
```
The advantage of this syntax is that you don't need to "count" how many dots are there (which I think is error-prone).

**Comment by SleepyRoy** [comment]
And similarly maybe we could consider this...
```
arr := [0,1,2,3,4,5]
println(arr[1..4])  // [1,2,3,4]
println(arr[1<..4])  // [2,3,4]
println(arr[1..<4])  // [1,2,3]
println(arr[1<..<4])  // [2,3]
```

**Comment by Delta456** [comment]
We already have this

```v
for i in 1..5 {
   println(i)
}
```

**Comment by SleepyRoy** [comment]
@Delta456 Yes. Since V has a philosophy of "unique way", maybe keeping the current syntax (a..b means [a,b) ) is not bad.

**Comment by lammel** [comment]
I probably missed the discussion around the current range operator, but I find a mix of inclusive and exclusive rather unintuitive.

I would have expected that a loop over 1 to 3 does include 3:

```vlang
for i in 1..3 {
   println(i)
}
```

Output:

```
1
2
3
```

I would prefer to have the default as a intuitive as possible. And advanced syntax is usually not needed if math operators will do the trick.

In case the code below is working, I guess no additional sytnax is required.

```
for i in 1..len(mylist)-1 {
   println(i)
}

**Comment by fclm1000** [comment]
A '1..5' range not including '5' although completely counterintuitive at first sight, makes sense about zero base arrays:

```
for i in 0 .. my_array.len { my_array[i] = some_value } // not bad!
```

MAYBE a new language derived from V  (just the one base arrays part) could work fine.

**Comment by fclm1000** [comment]
```
for x in [1,2,3,4,5] { print(x) } // 12345 // inclusive
           
for x in 1..5        { print(x) } // 1234  // exclusive
```
I have no proposal about this.
A just want to point how counterintuitive this range design is.

**Comment by Gundolf68** [comment]
> I have no proposal about this.
> A just want to point how counterintuitive this range design is
> 

Yes: Take a look at "wren" http://wren.io/values.html#ranges - i think 
they do it right.

**Comment by fclm1000** [comment]
@Gundolf68 


Don't get me wrong.
If I had the power to decide about V:
- only base one arrays (indexing) would exist
- for i in 1..5 // would mean 12345
- the operator '...' would not exist


As the decision is not for me, I try to understand what are the reasons of Alex Medvednikov.

I think he wants a language where C programmers feel at home.
Probably the language design is in part driven by marketing (culture).

That is why I said I had no proposal, because I fear that some features that I love have no match with strategy/culture/market of V.
