### ISSUE TITLE
Casting syntax "int(string)" or "float(string)" doesn't work

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#3303]
**V version:** 
playground

**OS:** 

**What did you do?**
```v
fn main() {
    a := int("5")  // Changing int to f64, f32, or bool gives the same error.
    println(a)
} 
```

**What did you expect to see?**
5
 
**What did you see instead?**
You just found a bug.

The following alternative works.
```v
fn main() {
    a := "5".int() 
    println(a)  // print 5 as expected
} 
```

**Comment by changrui** [comment]
oh, no. it may be `'5'.int()' or *'5'.f32()*.

**Comment by medvednikov** [comment]
`int(string)` should result in an error and a `use int.str()` message.

**Comment by spytheman** [comment]
Now the message in this situation is:
```
cannot cast `string` to `int`, use `string.int()` instead
```
