### ISSUE TITLE
Escape characters \" not working

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#3305]
**V version:** 
playground

**OS:** 

**What did you do?**
```v
fn main() {
    println("\"V\" is awesome")
} 
```
**What did you expect to see?**
"V" is awesome
 
**What did you see instead?**
You just found a bug.

**Workaround:**
```v
fn main() {
    println('"V" is awesome')  // print "V" is awesome as expected
} 
```

**Comment by alexesprit** [comment]
Closed as a duplicate of #2216.
