### ISSUE TITLE
goroutine style to create a new thread?

### ISSUE THREAD

**Issue by thesby** [vlang/v#3307]
Golang is easy to create a new goroutine (light thread), is it possible for vlang to implement it?

**Comment by Miaourt** [comment]
> The concurrency model is very similar to Go. To run foo() concurrently, just call it with go foo(). Right now, it launches the function in a new system thread. Soon coroutines and the scheduler will be implemented.

https://vlang.io/docs#concurrency

**Comment by dumblob** [comment]
See also https://github.com/vlang/v/issues/1868 (not to be confused with https://github.com/vlang/v/issues/1839 ).

**Comment by lutherwenxu** [comment]
As mentioned in the comment, it's already planned (and in the docs).
