### ISSUE TITLE
Immutability controls can be trivially circumvented

### ISSUE THREAD

**Issue by Richiban** [vlang/v#3310]
**V version:** 
**OS:** 
https://vlang.io/play

**What did you do?**

Created a mutable copy of supposedly immutable data structure:

```v
fn f(data []int) {
    mut copy := data // This doesn't give an error. Why!?
    copy[0] = 9         
}

fn main() { 
	data := [1, 2, 3]

	f(data)

	println(data) // Data has been silently mutated.
                      // prints [9, 2, 3]
}
```

**What did you expect to see?**

I expected to see an error raised at this point:

```v
mut copy := data
```

In a language with mutability controls it shouldn't be allowed to create a mutable reference to an immutable object.
 
**What did you see instead?**

No error.

**Comment by medvednikov** [comment]
Fixed.
