### ISSUE TITLE
C error

### ISSUE THREAD

**Issue by wjfiyhl** [vlang/v#3316]
**V version:** V 0.1.24 4389526
**OS:** windows

**What did you do?**
v -o v v.v

**What did you expect to see?**
success
 
**What did you see instead?**
V error: C error. This should never happen.

**Comment by dhonx** [comment]
Hi @wjfiyhl, Can you try running this command  `v -show_c_cmd -g -o v v.v` ??

**Comment by Ivo-Balbaert** [comment]
v -o v path_to_v\cmd\v\v.v

Should this command still work? It now compiles v successfully, but when v is started it gives the error:

cannot compile `c:\v\cmd\v\cmd\tools\vrepl.v`:
builder error: `builtin/` not included on module lookup path.
Did you forget to add vlib to the path? (Use @vlib for default vlib)

**Comment by penguindark** [comment]
no reply from the user
