### ISSUE TITLE
Cannot istantiate a fixed length array

### ISSUE THREAD

**Issue by djoodle** [vlang/v#3317]
**V version:** V 0.1.24 4389526

**OS:** Ubuntu 19.04

**What did you do?**
```v
mut x := [100]int
```

**What did you expect to see?**
Get a fixed sized array
 
**What did you see instead?**
```v
>>> mut x := [100]int
undefined: `int`
```

**Comment by djoodle** [comment]
Not sure why the tests in https://github.com/vlang/v/blob/320174bd5b4d438805b221fa89e6449646c4b52a/vlib/builtin/array_test.v#L309-319 wouldn't have caught this

**Comment by ka-weihe** [comment]
Works in V REPL 0.1.26 50a8373.
