### ISSUE TITLE
V panic since f9cc419 / ARMv7- 2.6.36.4 kernel 

### ISSUE THREAD

**Issue by lancethepants** [vlang/v#3320]
The V compiler has been broken for me since f9cc419dbaa9c468ef4613ded867baff787b413f

```
V panic: V tool "/mmc/src/v/tools/vrepl.v" could not be compiled
*** stack smashing detected ***: /mmc/src/v/v terminated
Killed
*** stack smashing detected ***: v terminated
Killed
```

armv7 (Netgear R7000 Router)
kernel 2.6.36.4
gcc-9.2.0

I traced it back to this commit the in vc repo
https://github.com/vlang/vc/commit/4ebc906f6519fac4d38e620d06541e244fcd7016
Which points to the commit I listed at the top.

**Comment by lutherwenxu** [comment]
Does it work with the latest version?
It seems like it was just the `vrepl.v` being invalid V code which should not be the case now.

**Comment by lancethepants** [comment]
Yes, it now appears to be working. Thanks!
