### ISSUE TITLE
os.get_line() in REPL

### ISSUE THREAD

**Issue by tankf33der** [vlang/v#3325]
**V version:** V 0.1.24 2061394
**OS:** Linux lambda 4.19.91-1-MANJARO #1 SMP Sat Dec 21 11:18:44 UTC 2019 x86_64 GNU/Linux

**What did you do?**
```
$ v
V 0.1.24 2061394
Use Ctrl-C or `exit` to exit
>>> import os
>>> s := os.get_line()
mike<press Enter>
>>> s
<hang forever><press Enter>
>>> println(s)
<hang forever><press Enter>
>>>
```

**What did you expect to see?**
Code above works in compile mode, even for numbers. :)

**Comment by serkonda7** [comment]
Same behaviour with V 0.1.29 4774c89

**Comment by Delta456** [comment]
Reproducible with the latest V.

**Comment by medvednikov** [comment]
Fixed.
