### ISSUE TITLE
vlang.io/play Playground example error - JSON encode/decode example

### ISSUE THREAD

**Issue by machshev** [vlang/v#3327]
**V version:** V playground

**OS:** Fedora Linux, https://vlang.io/play via chromium

**What did you do?**

Tried to run the JSON encode/decode example

```v
import json

struct User {
	name          string
	age           int
mut: 
	is_registered bool
}

fn main() {
	s := '[{ "name":"Frodo", "age":25}, {"name":"Bobby", "age":10}]'
	mut users := json.decode( []User, s) or {
		eprintln('Failed to parse json')
		return 
	}
	for user in users {
		println('$user.name: $user.age')
	}
	println('')
	for i, user in users {
		println('$i) $user.name')
		if !user.can_register() {
			println('Cannot register $user.name, they are too young')
			continue 
		}
		users[i].register() // `user` is immutable, we have to modify the array 
	}
	// Let's encode users again just for fun
	println('')
	println(json.encode(users))
}

fn (u User) can_register() bool {
        return u.age >= 16
}

fn (u mut User) register() {
        u.is_registered = true
}
```

**What did you expect to see?**

Result
 
**What did you see instead?**
```
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.
```

**Comment by ricardobeat** [comment]
Works fine locally with master, playground must be broken.

Is play.vlang.io not published on GitHub?

**Comment by Kurtoid** [comment]
Confirmed, Windows 10, Firefox Nightly

**Comment by machshev** [comment]
Still broken, but with a different error message.
```
Warning: 'v' is a directory
addr2line: Warning: 'v' is a directory
```

**Comment by jwenjian** [comment]
still broken, Win7, Microsoft edge on chromium， see below screenshot:

![Snipaste_2020-01-17_11-43-42](https://user-images.githubusercontent.com/25657798/72582753-cda27680-391e-11ea-8606-790000ab2d5d.png)

**Comment by dhonx** [comment]
https://devbits.app/play/tHDOscbTGf8W

**Comment by machshev** [comment]
> https://devbits.app/play/tHDOscbTGf8W

Yes, it works there... and locally. Still not on the main site V playground https://vlang.io/play

**Comment by elimisteve** [comment]
@ricardobeat Yes the V playground is on GitHub: https://github.com/vlang/website/blob/master/play.html

**Comment by johandalabacka** [comment]
Locally it gives an error

```v
json.v:37:7: warning: use `(mut f Foo)` instead of `(f mut Foo)`
   35 | }
   36 |
   37 | fn (u mut User) register() {
      |       ~~~
   38 |         u.is_registered = true
   39 | }
```
but after changing line 37 to `fn (mut u User) register() {` does it work

**Comment by Ivo-Balbaert** [comment]
Playground still showing: You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

**Comment by leahlundqvist** [comment]
Closing this as the old playground has been retired.
