### ISSUE TITLE
default compiler directory

### ISSUE THREAD

**Issue by bitsnaps** [vlang/v#333]
I guess the compiler still need to be in `~/code` for now, otherwise line N°7445 need to be updated:
```
  string lang_dir = string_add(os__home_dir(), tos2("/code/v/"));
```
even though I got `Segmentation fault: 11` after compiling from `~/code` on a Mac.

**Comment by hello2dj** [comment]
![image](https://user-images.githubusercontent.com/10645383/59967773-a1c63a80-9561-11e9-93d7-1b6b0cbb2525.png)

**Comment by medvednikov** [comment]
https://github.com/vlang/v/issues/329
