### ISSUE TITLE
Module rand in vlib not working

### ISSUE THREAD

**Issue by cliserkad** [vlang/v#3340]
**V version:** 0.1.24 126289c
**OS:** Windows 10

**What did you do?**
Attempted to import _rand_ from vlib and use it to generate an int from 0 to 99 on each execution of the .exe
Code used:
```
import rand

fn main() {
	println(rand.next(99))
}
```
Commands used:
```
>v -prod random.v
>random
```

**What did you expect to see?** 
A random integer on each subsequent run

 
**What did you see instead?** 
41 on every run

**Comment by changrui** [comment]
call function `rand.seed(time.now().unix)` first.

**Comment by cliserkad** [comment]
Thanks, I'll see if I can add that to the library as the default seed used.

**Comment by cliserkad** [comment]
This works, although it is terribly predictable.

**Comment by dumblob** [comment]
@cliserkad don't use `rand`, but `pcg32` (see `vlib/rand/pcg32_test.v`) which is one of the best PRNGs under the sun (but it's somewhat slower).
