### ISSUE TITLE
Generating same C file for MSVC and GNU GCC/clang

### ISSUE THREAD

**Issue by lygstate** [vlang/v#3342]
**V version:** 
**OS:** 

**What did you do?**

**What did you expect to see?**

 
**What did you see instead?**

**Comment by lygstate** [comment]
@dhonx Refer to https://github.com/vlang/vc, merge v.c and v_win.c,

**Comment by emily33901** [comment]
The reason there are 2 files is that on windows we cannot have the `println` optimization that happens on Linux because `printf` cannot output to a widestring terminal buffer. Unfortunately it doesn't work anyway which is why there are a bunch of `printf`s in `v_win.v` when there shouldn't be.

**Comment by emily33901** [comment]
Mingw is very lax about this and let's it slide but the vc++ runtime won't have any of it

**Comment by lygstate** [comment]
Then consider implement printf in V lang,

**Comment by emily33901** [comment]
Easier said than done. It was just the first example of things that are
built into binaries that are built on a nix platform and do not work on
windows. Ill look into why the 2 files aren't actually different at some
point.
