### ISSUE TITLE
v-0.23.1 repl not work on windows 10

### ISSUE THREAD

**Issue by fenginsc** [vlang/v#3343]
**V version: 0.23.1** 
**OS: Windows 10** 

**What did you do?**
open vlang repl

**What did you expect to see?**
print_backtrace_skipping_top_frames is not implemented on this platform for now.
 
**What did you see instead?**
repl

**Comment by changrui** [comment]
This issue also occurs under `freeBSD`.

**Comment by medvednikov** [comment]
Fixed.

**Comment by fenginsc** [comment]
> Fixed.

thank you.
v-0.1.24 now it works normally.
