### ISSUE TITLE
Examples throws an error for the interface

### ISSUE THREAD

**Issue by muraray** [vlang/v#3346]
**V version:** 
V 0.1.24 c949e9e

**OS:** 
Debian GNU/Linux 9 (stretch)

**What did you do?**
I was try on the examples shared on the vlang website, while running the interfaces example
https://vlang.io/docs#interfaces

**What did you expect to see?**
I expected to example would return an 2 print statements instead
 
**What did you see instead?**

`
root@a98277977ce1:/code/docs# v run 15_interfaces.v -g
C compiler=cc
/code/docs/15_interfaces.v: In function 'main__perform':
/code/docs/15_interfaces.v:21:72: error: expected ';' before ')' token
  println(s.speak())
                                                                        ^
/code/docs/15_interfaces.v:21:72: error: expected statement before ')' token
/code/docs/15_interfaces.v: In function 'main':
/code/docs/15_interfaces.v:99:37: warning: excess elements in struct initializer
/code/docs/15_interfaces.v:24:18: note: in expansion of macro 'EMPTY_STRUCT_INITIALIZATION'
 dog := Dog{}
                  ^
/code/docs/15_interfaces.v:99:37: note: (near initialization for '(anonymous)')
/code/docs/15_interfaces.v:24:18: note: in expansion of macro 'EMPTY_STRUCT_INITIALIZATION'
 dog := Dog{}
                  ^
/code/docs/15_interfaces.v:99:37: warning: excess elements in struct initializer
/code/docs/15_interfaces.v:26:18: note: in expansion of macro 'EMPTY_STRUCT_INITIALIZATION'
                 
 ^
/code/docs/15_interfaces.v:99:37: note: (near initialization for '(anonymous)')
`

Please let me know if am doing something wrong here?

**Comment by emily33901** [comment]
Can you run with `-cg` instead of `-g` and repaste the error please

**Comment by muraray** [comment]
Thanks for looking into this issue, ran with -cg args

```
root@a98277977ce1:/code/docs# v run 15_interfaces.v -cg
C compiler=cc
/tmp/v/15_interfaces.tmp.c: In function 'main__main':
/tmp/v/15_interfaces.tmp.c:115:37: warning: excess elements in struct initializer
 #define EMPTY_STRUCT_INITIALIZATION 0
                                     ^
/tmp/v/15_interfaces.tmp.c:3950:18: note: in expansion of macro 'EMPTY_STRUCT_INITIALIZATION'
 Dog dog= (Dog) { EMPTY_STRUCT_INITIALIZATION } ;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/v/15_interfaces.tmp.c:115:37: note: (near initialization for '(anonymous)')
 #define EMPTY_STRUCT_INITIALIZATION 0
                                     ^
/tmp/v/15_interfaces.tmp.c:3950:18: note: in expansion of macro 'EMPTY_STRUCT_INITIALIZATION'
 Dog dog= (Dog) { EMPTY_STRUCT_INITIALIZATION } ;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/v/15_interfaces.tmp.c:115:37: warning: excess elements in struct initializer
 #define EMPTY_STRUCT_INITIALIZATION 0
                                     ^
/tmp/v/15_interfaces.tmp.c:3951:18: note: in expansion of macro 'EMPTY_STRUCT_INITIALIZATION'
 Cat cat= (Cat) { EMPTY_STRUCT_INITIALIZATION } ;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/v/15_interfaces.tmp.c:115:37: note: (near initialization for '(anonymous)')
 #define EMPTY_STRUCT_INITIALIZATION 0
                                     ^
/tmp/v/15_interfaces.tmp.c:3951:18: note: in expansion of macro 'EMPTY_STRUCT_INITIALIZATION'
 Cat cat= (Cat) { EMPTY_STRUCT_INITIALIZATION } ;
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/v/15_interfaces.tmp.c: In function 'main__perform':
/tmp/v/15_interfaces.tmp.c:3962:72: error: expected ';' before ')' token
  ((string (*)())(Speaker_name_table[s._interface_idx][0]))(s._object ) ) ;
                                                                        ^
/tmp/v/15_interfaces.tmp.c:3962:72: error: expected statement before ')' token
V error: C error. This should never happen. 
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
root@a98277977ce1:/code/docs# 

```

**Comment by muraray** [comment]
> Can you run with `-cg` instead of `-g` and repaste the error please

Thanks for looking into the issue, have replied as a seperate comment, however i noticed this one may be because of the empty struct initialization

```
module main
struct Dog {}
struct Cat {}

interface Speaker {
	speak() string
}

fn main() {
	dog := Dog{}
	addr_s  := &dog
	str_addr_s := ptr_str(addr_s)

	println(!isnil(addr_s)) // true
	println(str_addr_s) //  0x7fffd2694cd8
}
```

**Comment by dhonx** [comment]
@muraray Thanks for reporting the issue. This issue has been a long time and many have reported ... It will be fixed as soon as possible. 🙂
As the current workaround is the following way:
```v
struct Dog {}
struct Cat {}

fn (d Dog) speak() string {
    return 'woof'
}

fn (c Cat) speak() string {
    return 'meow' 
}

interface Speaker {
    speak() string
}

fn perform(s Speaker) {
    _s := s.speak()
    println(_s)
}

dog := Dog{}
cat := Cat{}
perform(dog) // "woof" 
perform(cat)
```
BTW... You can play with it on https://devbits.app/play/oc0vfbS3yqnJ 🙂

**Comment by muraray** [comment]
> @muraray Thanks for reporting the issue. This issue has been a long time and many have reported ... It will be fixed as soon as possible. 🙂
> As the current workaround is the following way:
> 
> ```v
> struct Dog {}
> struct Cat {}
> 
> fn (d Dog) speak() string {
>     return 'woof'
> }
> 
> fn (c Cat) speak() string {
>     return 'meow' 
> }
> 
> interface Speaker {
>     speak() string
> }
> 
> fn perform(s Speaker) {
>     _s := s.speak()
>     println(_s)
> }
> 
> dog := Dog{}
> cat := Cat{}
> perform(dog) // "woof" 
> perform(cat)
> ```
> 
> BTW... You can play with it on https://devbits.app/play/oc0vfbS3yqnJ 🙂

Thanks for the quick response...
