### ISSUE TITLE
vc: bootstrapping issues on linux x86

### ISSUE THREAD

**Issue by KlemensWinter** [vlang/v#3349]
Hi,

I'm unable to bootstrap vc on linux x86.
The syscalls which are used (https://github.com/vlang/vc/blob/master/v.c) are for x86_64.
e.g.:
os__sys_mkdir: 83 (should: 39 [1])
os__sys_creat: 85 (should: 8 [1])

You can compile it successful, but when the functions are getting used it panics:
``
./vc -o v2 v2.v                                                                                                                                                    
V panic: Bad address
```

[1] https://gist.github.com/yamnikov-oleg/454f48c3c45b735631f2

**Comment by danieldaeschle** [comment]
Is this still valid? Reopen if needed. Please add more info to reproduce. E.g. OS, commands, etc.
