### ISSUE TITLE
`for item in array` mutability issue

### ISSUE THREAD

**Issue by prime31** [vlang/v#3350]
**V version:** V 0.1.24 126289c
**OS:** macos

**What did you do?**
```c
	mut verts := [0, 1, 2, 3]!
	
	for vert in verts {
		vert = 5
	}
```

**What did you expect to see?**
I would expect all elements in the array to have a value of 5
 
**What did you see instead?**
The error: "`vert` is immutable"

**Comment by medvednikov** [comment]
https://vlang.io/docs#for

> Note, that the value is read-only. If you need to modify the array while looping, you have to use indexing:

**Comment by prime31** [comment]
Oops. Apparently I’m still learning how to read ;)
