### ISSUE TITLE
For loop scope

### ISSUE THREAD

**Issue by Contextualist** [vlang/v#3351]
**V version:** 0.1.24 8c59232
**OS:** CentOS 7.6.1810 (gcc 6.3.0)

**What did you do?**
```vlang
fn main() {
        a := [0]
        mut ans := [[]int]
        ans.delete(0)
        for i := 0; i < 3; i++ {
                mut b := a // <- b should be a distinct copy for each loop
                b << i
                ans << b
        }
        println(ans)
}
```

**What did you expect to see?**
```
[[0, 0], [0, 1], [0, 2]]
```
 
**What did you see instead?**
```
[[0, 2], [0, 2], [0, 2]]
```

**Comment by Contextualist** [comment]
Related #119

**Comment by emily33901** [comment]
`mut b := a.clone()` for right now probably

**Comment by Contextualist** [comment]
@emily33901 This is a reasonable solution, but I think that the default here is somehow counterintuitive. Either

1. Default to copy when making a mutable reference to an immutable. (Not exactly the same, but in Go, `b := a` always copy)
2. Or ask user to make a copy explicitly. In Rust `let mut b = a` defaults to move, and it will fail to compile in this case because in a loop move occurs more than once (User should explicitly state `let mut b = a.clone()`).

**Comment by medvednikov** [comment]
This particular case will work like in Rust.

**Comment by Ivo-Balbaert** [comment]
In current version the following error is shown:
error: use `array2 = array1.clone()` instead of `array2 = array1` (or use `unsafe`)
when using .clone() the output is as expected: [[0, 0], [0, 1], [0, 2]]
when using unsafe block: the output is [[0, 2], [0, 2], [0, 2]]
I think the issue can be closed when (or use `unsafe`) is removed from the error message @medvednikov?

**Comment by medvednikov** [comment]
Thanks, this can be closed indeed.

`unsafe` assumes that the developer knows what they are doing and that they are modifying the original.
