### ISSUE TITLE
Solutions to some build problems

### ISSUE THREAD

**Issue by zac-garby** [vlang/v#336]
To use V on Mac, I had to:

 - Move the `v` directory into `~/code`
 - To print something in the REPL, I had to use `println`, which crashed it (couldn't find stdio.h). Then, I had to manually build the temporary REPL file in the filesystem with clang to make it work

**Comment by zac-garby** [comment]
Also, when trying to import something, I get `unexpected token: import`. Making me think that the reason importing isn't allowed in the playground isn't due to security problems.

**Comment by Undumendil** [comment]
You also need to create `/var/tmp/vlang0.0.12/` directory

**Comment by zac-garby** [comment]
In my case, it was created for me.

**Comment by Hamzantal** [comment]
i got a segmentation fault when it was in ~/code
```
32350@2022-32350.local:/Users/32350/code/v/compiler git:(master*) $ ./vc -o v .
[1]    11900 segmentation fault  ./vc -o v .
```

**Comment by Bowero** [comment]
> You also need to create `/var/tmp/vlang0.0.12/` directory

This creates a new error for me:

```
sh: /var/tmp/vlang0.0.12//vrepl: No such file or directory
```

**Comment by AurelienFT** [comment]
Should be correct since 0.1 version. Try to `git pull` and rebuild the compiler.
