### ISSUE TITLE
Cant compile on windows 7 using vs 2019

### ISSUE THREAD

**Issue by nico-abram** [vlang/v#337]
https://i.imgur.com/U0CBNxU.png

**Comment by 0x9ef** [comment]
Same error. You must manual download `dirent.h` from here https://github.com/tronkko/dirent . I know you must include `execinfo.h` and `feautures.h`, but i found only `execinfo.h`, `feautures.h` contains in GNU Lib C , but not for Visual Studio. Author must add some extra links to download C headers dependency.

**Comment by medvednikov** [comment]
Like the readme says, building with VS is not possible right now.

**Comment by nico-abram** [comment]
When I opened this issue it did not say that, and it gave a list of instructions to build (Which I followed)

**Comment by Bowero** [comment]
The information has been updated now.
