### ISSUE TITLE
Playground doesn't work (warning: v is a directory)

### ISSUE THREAD

**Issue by Jacalz** [vlang/v#3371]
**V version:** The one online I expect?

**What did you do?**
tried to run anything from the playground.

**What did you expect to see?**
A fully working playground.
 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/25466657/71993899-29db0b80-3238-11ea-9814-17d8f13bce4d.png)

**Comment by medvednikov** [comment]
Fixed.
