### ISSUE TITLE
Incorrect operator precedence in if statement

### ISSUE THREAD

**Issue by penguindark** [vlang/v#3376]
**V version:** 
V 0.1.24 c1cc203
**OS:**
Ubuntu 18.04

**What did you do?**
```v
fn main() {

	a := 2
	b := 2
	c := a & b
	println(c)
	if a & b > 0 { println("OK") } else {println("ERROR")}
} 
```
**What did you expect to see?**
```
2
OK
 ```
**What did you see instead?**
```
2
ERROR
```
**Workaround**
```v
if (a & b) > 0 { println("OK") } else {println("ERROR")}
```
**NOTE**
Very strange that using values with bit 0 different from 1 cause the bug (just to be clear: every even number)
My guess is that the condition of the if `a & b` is tested only against the first bit instead using all the bit of value.
Probably somewhere the compiler believe that `a & b` is of `bool` type.

**Comment by alexesprit** [comment]
There's a similar example, where a bitwise "OR" operator has a lower priority:
```v
fn main() {
	a := 1
	b := 2

	println(a | b)
	println((a | b) > 4)
	println(a | b > 4)

	if a | b > 4 {
		println("Should not be visible")
	} else {
		println("Should be visible")
	}
}
```
**Expected output:**
```
3
false
true
Should be visible
```
**Actual output:**
```
3
false
true
Should not be visible
```

**Comment by kprotty** [comment]
Might be the lack of operator precedence in the compiler (no AST or IR). What could be happening is the result of how C handles booleans: there aren't any, only integers. 0 is false and anything else is true. Conditions generally evaluate to 1 (true) or 0 (false). If this is the case, it would make the generated code evaluate as such:

@penguindark `a & b > 0` -> `2 & 2 > 0` -> `2 & (2 > 0)` -> `2 & (true)` -> `2 & 1` -> `0` -> `false`

@alexesprit `a | b > 4` -> `1 | 2 > 4` -> `1 | (2 > 4)` -> `1 | (false)` -> `1 | 0` -> `1` -> `true`

**Comment by penguindark** [comment]
I'm thinking that during check of boolean conditions, the compiler only test bit number 0.
This can explain why the bug is present only in even numbers.

**Comment by alexesprit** [comment]
> I'm thinking that during check of boolean conditions, the compiler only test bit number 0.
This can explain why the bug is present only in even numbers.

Currently the compiler forces precendence of bitwise AND in case when it's compared using equality operators. Other cases are not processed.

https://github.com/vlang/v/blob/f7f5f43c4827aba166b94c2cd4d96c60eb79dac3/vlib/compiler/expression.v#L631-L647

It can be extended to cover other cases:
```v
// Force higher precendence of bitwise operators
is_bitwise := tok_op in [.pipe, .amp, .xor]
open := is_bitwise && p.tok in [.eq, .gt, .lt, .le, .ge, .ne]
```

Also, I wrote a test file to check if operator precendence is correct:
<details>
  <summary>bitwise_precendence_test.v (Click to expand)</summary>

```v
const (
	Value1 = 0x1
	Value2 = 0x2
	Value3 = 0x4
)

fn test_and() {
	mask := Value1 | Value2

	assert mask & Value3 == 0
	assert mask & Value3 >= 0
	assert mask & Value3 <= 0
	assert (mask & Value3 != 0) == false
	assert (mask & Value3 < 0) == false
	assert (mask & Value3 > 0) == false
}

fn test_or() {
	mask := 0
	new_mask := mask | Value1

	assert mask | Value1 == new_mask
	assert mask | Value1 >= 0
	assert mask | Value1 > 0

	assert (mask | Value1 != new_mask) == false
	assert (mask | Value1 <= 0) == false
	assert (mask | Value1 < 0) == false
}

fn test_xor() {
	mask := Value1
	new_mask := mask & ~Value1

	assert new_mask & Value1 == 0
	assert new_mask & Value1 >= 0
	assert new_mask & Value1 <= 0
	assert (new_mask & Value1 != 0) == false
	assert (new_mask & Value1 < 0) == false
	assert (new_mask & Value1 > 0) == false
}
```
</details>

Currently, this test is not passed, but it's passed with changes applied.

**Comment by medvednikov** [comment]
This will be fixed in the new AST based parser.

**Comment by penguindark** [comment]
ok, I'll wait, meanwhile I'll use bracket for sure in the ifs ;)

**Comment by medvednikov** [comment]
Fixed.
