### ISSUE TITLE
voidptr vararg doesnt compile

### ISSUE THREAD

**Issue by prime31** [vlang/v#3377]
**V version:** V 0.1.24 29564ed
**OS:** macos

**What did you do?**
Declared a function with a vararg voidptr:

`fn test(first int, second int, rest ...voidptr)`

**What did you expect to see?**
Succesful compilation.
 
**What did you see instead?**
```
error: expected ';' after top level declarator
typedef struct varg_void* varg_void*;
```

**Comment by alexesprit** [comment]
Seems like it's fixed in a new backend.
