### ISSUE TITLE
Failed to compile empty_gg_freetype.v on Ubuntu

### ISSUE THREAD

**Issue by kellnerp** [vlang/v#3379]
**V version:** 
V 0.1.24 760448a
**OS:** 
Ubuntu 16.04 LTS
4.15.0-74-generic
**What did you do?**
~/Downloads/v/examples$ v -g empty_gg_freetype.v

**What did you expect to see?**
Not sure
 
**What did you see instead?**
C compiler=cc
warning: empty_gg_freetype.v:32:2: reference field `Context*.ft` must be initialized
warning: empty_gg_freetype.v:42:2: reference field `gg.Cfg.window_user_ptr` must be initialized
In file included from /home/pbk/Downloads/v/thirdparty/stb_image/stb_image.h:547:0,
                 from /home/pbk/Downloads/v/examples/empty_gg_freetype.v:140:
/home/pbk/Downloads/v/thirdparty/stb_image/stb_image.h: In function ‘stbi__shiftsigned’:
/home/pbk/Downloads/v/thirdparty/stb_image/stb_image.h:5116:18: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
    STBI_ASSERT(v >= 0 && v < 256);
                  ^
/home/pbk/Downloads/v/thirdparty/stb_image/stb_image.h:5116:4: note: in expansion of macro ‘STBI_ASSERT’
    STBI_ASSERT(v >= 0 && v < 256);
    ^
In file included from /home/pbk/Downloads/v/examples/empty_gg_freetype.v:150:0:
/home/pbk/Downloads/v/thirdparty/glfw/GLFW/glfw3.h: At top level:
/home/pbk/Downloads/v/thirdparty/glfw/GLFW/glfw3.h:202:21: fatal error: GL/gl.h: No such file or directory
compilation terminated.
V error: C error. This should never happen.

**Comment by vitalyster** [comment]
From the README
```
Debian/Ubuntu:
sudo apt install libglfw3 libglfw3-dev libfreetype6-dev libssl-dev
```
