### ISSUE TITLE
sqlite.v crashes on Ubuntu

### ISSUE THREAD

**Issue by kellnerp** [vlang/v#3380]
**V version:** 
V 0.1.24 760448a
**OS:** 
Ubuntu 16.04 LTS
4.15.0-74-generic

**What did you do?**
time v -g run sqlite.v

**What did you expect to see?**

 
**What did you see instead?**
C compiler=cc
/home/pbk/Downloads/v/examples/sqlite.v:46:21: fatal error: sqlite3.h: No such file or directory
compilation terminated.
V error: C error. This should never happen.

**Comment by changrui** [comment]
Install `libsqlite3-devel` first.

**Comment by kellnerp** [comment]
That solved the problem. TX
