### ISSUE TITLE
Message is not clear when neither mingw64 nor msvc installed on windows 

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#3381]
**V version:** 
0.1.24

**OS:** 
win10 1909

**What did you do?**
download prebuilt package from vlang.io, set the PATH, open cmd, simply type "v" and enter.

**What did you expect to see?**
some introduction of v commands?
 
**What did you see instead?**
"print_backtrace_skipping_top_frames is not implemented on this platform for now ..."

**Comment by vitalyster** [comment]
You should have `gcc` in PATH too, or have MSVC installed

**Comment by SleepyRoy** [comment]
@vitalyster Thanks. Previously I had mingw installed. Changing it to mingw64 fixes this problem.
But should V give a clear "please install ming64 or MSVC first" message in such cases?

**Comment by medvednikov** [comment]
Yes it should it.

I thought it already did. Will fix.

**Comment by SleepyRoy** [comment]
Update:
Just tried typing `v` on win10 with prebuilt 0.1.27 but no MSVC or mingw64. 
```
cannot compile VPATH\vrepl.v:
builder error: Cannot find MSVC on this OS
```

`v hello_world.v` gave similar 
```
builder error: Cannot find MSVC on this OS
```

So basically solved, although I think `Cannot find MSVC or mingw64` is better.

**Comment by JalonSolov** [comment]
Current V for windows will download and use TCC if it can't find either MSVC or GCC, so this should be a non-issue altogether.  If once of those compilers is installed after V is up & running, it will start to use that instead of TCC.
