### ISSUE TITLE
Tetris Example UNICODE/ft2build.h error on Windows 7

### ISSUE THREAD

**Issue by coruscateor** [vlang/v#3385]
V 0.1.24 8412c6f
OS: Windows 7 x64

What did you do?
Run: v -g run tetris.v in examples/tetris/

What did you expect to see?
The build complete successfully

What did you see instead?
C:\Users\........\AppData\Local\Temp\v\tetris.tmp.c:147:9: warning: 'UNICODE' macro redefined [-Wmacro-redefined]
#define UNICODE
        ^
<command line>:1:9: note: previous definition is here
#defin...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

With: ...\v\examples\tetris>v -g tetris.v
C compiler=gcc
...\v\examples\tetris\tetris.v:543:9: warning: 'UNICODE' macro redefined [-Wmacro-redefined]
#define UNICODE
        ^
<command line>:1:9: note: previous definition is here
#define UNICODE 1
        ^
...\v\examples\tetris\tetris.v:550:10: fatal error: 'ft2build.h' file not found
#include "ft2build.h"
         ^~~~~~~~~~~~
1 warning and 1 error generated.
V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by changrui** [comment]
? `freetype` hasn't installed?`

**Comment by changrui** [comment]
from readme.md:
```
git clone --depth=1 https://github.com/ubawurinna/freetype-windows-binaries [path to v repo]/thirdparty/freetype/
```

**Comment by coruscateor** [comment]
Thanks, this detail should also be put in the readme of the example itself.
