### ISSUE TITLE
-autofree crash in windows

### ISSUE THREAD

**Issue by funnywwh** [vlang/v#3393]
**V version:** 
V 0.1.24 8412c6f
**OS:** 
Microsoft Windows [版本 10.0.18362.535]
**What did you do?**
module main

fn main() {
        println('Hello World !')
}

**What did you expect to see?**
'Hello World !'
 
**What did you see instead?**
crash

**Comment by vitalyster** [comment]
C compiler version?

**Comment by funnywwh** [comment]
Reading specs from d:/winbuilds/bin/../lib64/gcc/x86_64-w64-mingw32/4.8.3/specs
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=d:/winbuilds/bin/../libexec/gcc/x86_64-w64-mingw32/4.8.3/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-4.8.3/configure --prefix=/opt/windows_64 --with-sysroot=/opt/windows_64 --libdir=/opt/windows_64/lib64 --mandir=/opt/windows_64/man --infodir=/opt/windows_64/info --enable-shared --disable-bootstrap --disable-multilib --enable-threads=posix --enable-languages=c,c++ --enable-checking=release --enable-libgomp --with-system-zlib --with-python-dir=/lib64/python2.7/site-packages --disable-libunwind-exceptions --enable-__cxa_atexit --enable-libssp --with-gnu-ld --verbose --enable-java-home --with-java-home=/opt/windows_64/lib64/jvm/jre --with-jvm-root-dir=/opt/windows_64/lib64/jvm --with-jvm-jar-dir=/opt/windows_64/lib64/jvm/jvm-exports --with-arch-directory=amd64 --with-antlr-jar='/home/adrien/projects/win-builds-1.5/slackware64-current/d/gcc/antlr-*.jar' --disable-java-awt --disable-gtktest --build=x86_64-slackware-linux --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32
Thread model: posix
gcc version 4.8.3 (GCC)

cl.exe
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.24.28314 版

v build by msvc

**Comment by lutherwenxu** [comment]
Auto-free isn't really in a state to be used at the moment.
I'll keep this issue open until auto-free is implemented however.

**Comment by lutherwenxu** [comment]
This is no longer valid in V 0.1.27 c4fbae3.
