### ISSUE TITLE
Transpiled C code for v_panic will not free memory (with -autofree)

### ISSUE THREAD

**Issue by funnywwh** [vlang/v#3396]
**V version:** 0.1.24 8412c6f
**OS:** Windows 10 (Build 10.0.18362.535)

**What did you do?**
v -autofree -o 1.c .

main.v:
```
module main

fn main() {
        panic('Hello World !')
}
```
1.c:
```
...
void v_panic (string s) {
printf( "V panic: %.*s\n", s.len, s.str ) ;
 print_backtrace ( ) ;
 exit ( 1 ) ;
 v_string_free (s); // close_scope free
 }
...
```
`v_string_free(s)` should be before `exit(1)`
**What did you see instead?**
`v_string_free(s)` was after `exit(1)`.

Moderator Note: The formatting was fixed and missing information was retrieved from his other issue (#3393)

**Comment by lutherwenxu** [comment]
I don't really see how this is a problem? By exiting gracefully (through exit), the OS should reclaim all memory regardless if it was freed.

**Comment by lutherwenxu** [comment]
Closing due to lack of reply. Please reopen this issue if you think it's still relevant.
