### ISSUE TITLE
Maybe fix the rand module just being notexistent

### ISSUE THREAD

**Issue by xacrimon** [vlang/v#340]

**Comment by xacrimon** [comment]
Pls fix @medvednikov before you make blatant claims about a glorious language.

**Comment by xacrimon** [comment]
And if you don't have common sense don't accept almost $1k a month.

**Comment by medvednikov** [comment]
What do you mean "notexistent"?

There are 2 functions `seed()` and `next()`. That's all I needed.

**Comment by xacrimon** [comment]
Alright.```fn next(max int) int {
	# return  rand() % max;
	return 0
}```

**Comment by xacrimon** [comment]
Lets start here. A infinite amount of 0's doesnt have much entropy does it?
