### ISSUE TITLE
panic on mutable assignment of arrays from it's own iterator

### ISSUE THREAD

**Issue by sachinbhutani** [vlang/v#3403]
**V version:** V 0.1.24 f7f5f43
**OS:** Mac OSX Catalina

**What did you do?**
run this code 

```
fn main() {
	mut words := ["it's","only","words"]
	words = words.map(it.to_upper())
	println(words)
} 
```

**What did you expect to see?**
a compile time error, or output ["IT'S", "ONLY", "WORDS"]
 
**What did you see instead?**
compiler panic 

V panic: substr(0, 10) out of bounds (len=0)
0   v                                   0x00000001096c9b30 v_panic + 48
1   v                                   0x00000001096ce677 string_substr + 119
2   v                                   0x00000001096d041c string_substr2 + 76
3   v                                   0x000000010971c058 compiler__CGen_set_placeholder + 328
4   v                                   0x000000010971a897 compiler__Parser_gen_array_map + 967
5   v                                   0x00000001097187d7 compiler__Parser_dot + 775
6   v                                   0x000000010970e9aa compiler__Parser_var_expr + 1962
7   v                                   0x000000010970db49 compiler__Parser_get_var_type + 473
8   v                                   0x0000000109733009 compiler__Parser_name_expr + 3193
9   v                                   0x0000000109738090 compiler__Parser_factor + 2240
10  v                                   0x0000000109737719 compiler__Parser_unary + 393
11  v                                   0x000000010971d129 compiler__Parser_term + 57
12  v                                   0x000000010971cbfb compiler__Parser_indot_expr + 43
13  v                                   0x00000001096fa919 compiler__Parser_expression + 57
14  v                                   0x00000001097312fb compiler__Parser_bterm + 43
15  v                                   0x0000000109702b90 compiler__Parser_bool_expression + 80
16  v                                   0x000000010970949e compiler__Parser_assign_statement + 1710
17  v                                   0x000000010971497e compiler__Parser_index_expr + 5518
18  v                                   0x000000010970ec5c compiler__Parser_var_expr + 2652
19  v                                   0x000000010970db49 compiler__Parser_get_var_type + 473
20  v                                   0x0000000109733009 compiler__Parser_name_expr + 3193
21  v                                   0x0000000109738090 compiler__Parser_factor + 2240
22  v                                   0x0000000109737719 compiler__Parser_unary + 393
23  v                                   0x000000010971d129 compiler__Parser_term + 57
24  v                                   0x000000010971cbfb compiler__Parser_indot_expr + 43
25  v                                   0x00000001096fa919 compiler__Parser_expression + 57
26  v                                   0x00000001097312fb compiler__Parser_bterm + 43
27  v                                   0x0000000109702b90 compiler__Parser_bool_expression + 80
28  v                                   0x00000001096f928d compiler__Parser_statement + 797
29  v                                   0x00000001096ebd10 compiler__Parser_statements_no_rcbr + 112
30  v                                   0x00000001096f0ae9 compiler__Parser_fn_decl + 10937
31  v                                   0x00000001096ec697 compiler__Parser_parse + 2215
32  v                                   0x000000010973fe44 compiler__V_parse + 308
33  v                                   0x0000000109740bc1 compiler__V_compile + 3377
34  v                                   0x0000000109764bf0 main__main + 1856
35  v                                   0x000000010976754e main + 78
36  libdyld.dylib                       0x00007fff6369c7fd start + 1

**Comment by Ivo-Balbaert** [comment]
The output is now (V 0.1.27 b5af6d4) on Windows 10 and the Playground:

['IT'S', 'ONLY', 'WORDS']
