### ISSUE TITLE
orm: insert, fails with no feedback

### ISSUE THREAD

**Issue by fredericosilva** [vlang/v#3411]
**V version:** 
V 0.1.24 938f27e

**OS:** 
macosx

**What did you do?**

Tried to run [blog tutorial](https://github.com/vlang/v/tree/master/tutorials/code/blog)

`db.insert(article)` does not insert, no error is reported.

If I replace with `db.exec_param2('insert into articles (title, text) values ($1,$2)', article.title, article.text)` works fine

**What did you expect to see?**

new article inserted
 
**What did you see instead?**

no article was inserted

**Comment by JalonSolov** [comment]
The ORM syntax has changed significantly since you tried your example.  I would suggest trying to recreate it with the new syntax, and see if you are still seeing a problem.

**Comment by medvednikov** [comment]
inserts work fine now
