### ISSUE TITLE
Multi value declaration/assignment support

### ISSUE THREAD

**Issue by mokafolio** [vlang/v#3415]
If functions can have multiple return values, i.e. like this:

```
fn foo() (int, int)
{
    return 1, 2
}

a, b := foo()
```

Shouldn't the following code work, too?:

```
a, b := 1, 2
```

and plain multi value assignment (if the variables are already declared)

```
a, b = 1, 2
```
Not sure if I missed an issue that's already open for this.

**Comment by changrui** [comment]
`a, b = b, a` ?

**Comment by cliserkad** [comment]
I think it's one of those syntactic sugar things that v is trying to avoid. Using variable shadowing and overloading are both not allowed, even though they reduce how much thinking a developer must do when naming things. The "1 way to do things" standard won't work with this proposal. I think the current ```a, b := foo()` is to make memoization easier.
```
a := 1
b := 2
```

**Comment by medvednikov** [comment]
That's absolutely correct @cliserkad
