### ISSUE TITLE
enum compilation error: unexpected token 'enum'

### ISSUE THREAD

**Issue by improveourselves** [vlang/v#3416]
Hi Alex, 

**V version:** 
V 0.1.24 f7f5f43

**OS:** 
Ubuntu 18.04 LTS (PopOS)

**What did you do?**
I'm going through the vlang.io/docs, and about halfway through the samples, I'm having trouble compiling the  "enum Colors" example in the "match" section. 
I wrote the code exactly as in the example, named it enums.v, then to compile just like I always do for all the other samples, I simply typed: 
`v enums.v`
but I get the error: 
"unexpected token: 'enum'"
which I paste for you below. 

**What did you expect to see?**
I expected a slight pause, then another prompt, meaning that it successfully compiled, so that I know that I can use that code in my programs. 
 
**What did you see instead?**
enums.v:2:5: unexpected token: `enum`
    1| fn main () {
    2| 	enum Color {
           ^
    3| 		red
    4| 		blue

I usually am able to troubleshoot and modify the docs samples to get them to work when there are minor errors, but I can't seem to fix this one on my own yet. Can you please tell me, is 'enum' no longer a command? Has it changed to something else? 

Thanks and respectfully,
John

**Comment by Ivo-Balbaert** [comment]
I think enums in V should be defined outside fn main () like this:

enum Color {
	red green blue
}

fn main() {
        mut color := Color.red 
        color = .green
        println(color)               // => 1 
        println(Color.blue)          // => 2
        println(color in [.blue, .green, .red]) // =>  true
}

**Comment by improveourselves** [comment]
Ah. Thanks Ivo! 
Ok, so I put them outside main, then put a main at bottom to call it. 
The above parts compile fine now, but the main call does not. 
In the main part, I simply put: 
`fn main () {
q1 : = is_red_or_blue('blue')
println(q1)
}`
but get the errors "cannot use type 'string' as type 'Color' in the first argument to 'is_red_or_blue'" and the same when I tried using an integer it says cannot use type 'integer' either. So, so I can test this, please suggest, what test value can I put in there to make it work? 

Here is the entire program: 
`enum Color {
        red
        blue
        green
}
fn is_red_or_blue(c Color) bool {
        return match c {
                .red { true }
                .blue { true }
                else { false }
        }
}
fn main () {
        q1 := is_red_or_blue('blue')
        println(q1)
}`

(oops, sorry that the lines are not spaced in the backticked sections. Please tell me, how do i make carraige returns show up properly in the code quotes?

**Comment by improveourselves** [comment]
Ah, sorry Ivo. I just read your reply more closely. Success! 
Here is my new program, incorporating your suggestions: 
`enum Color {  
        red  
        blue  
        green  
}  
fn is_red_or_blue(c Color) bool {  
        return match c {  
                .red { true }  
                .blue { true }  
                else { false }  
        }  
}  
fn main () {  
        mut color := Color.red  
        color = .blue  
        q1 := is_red_or_blue(color)  
        println(q1)  
}'  
And the results for value of color as "green" is "false", and for value of color as "blue" is "true". 
Thank you so much for your help, Ivo! :)
-John
