### ISSUE TITLE
V panic: v translated: unknown command

### ISSUE THREAD

**Issue by funnywwh** [vlang/v#3418]
**V version:** 
V 0.1.24 6733b12
**OS:** 
Linux version 4.15.0-74-generic (buildd@lcy01-amd64-022) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019
**What did you do?**
 v -lib translated p_enemy.v 

**What did you expect to see?**
V panic: v translated: unknown command
Run "v help" for usage.
addr2line: 'v': No such file
v(+0x2e7e) [0x55e8ea919e7e]
addr2line: 'v': No such file
v(+0x91a66) [0x55e8ea9a8a66]
addr2line: 'v': No such file
v(+0x90f23) [0x55e8ea9a7f23]
addr2line: 'v': No such file
v(+0x93a2a) [0x55e8ea9aaa2a]
                                               | 0x7f7fed7cab97 | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) 
addr2line: 'v': No such file
v(+0x194a) [0x55e8ea91894a]
 
**What did you see instead?**
no crash

**Comment by spytheman** [comment]
Running the same with recent V produces:

```shell
0[21:21:56]delian@nemesis: /v/nv $ ./v -lib translated p_enemy.v
v translated: unknown command
Run "v help" for usage.
1[21:22:07]delian@nemesis: /v/nv $
```

I consider this solved.
