### ISSUE TITLE
vlib: remove sdl dependencies

### ISSUE THREAD

**Issue by 87Idiot** [vlang/v#3419]
Not every developer on Windows use MSYS. I think we should put SDL dependencies in the thirdparty folder.

**Comment by emily33901** [comment]
Yeah this is a problem for me aswell - but it becomes a massive nightmare trying to include all the dependencies for all compilers and platforms that are supported. I would suggest just being able to point V at an `include` directory and a `lib` directory or maybe having it find those itself.

**Comment by alexesprit** [comment]
> I think we should put SDL dependencies in the thirdparty folder.

It's already done. SDL dependencies can be downloaded to the `thirdparty` directory via a `windows-install-sdl.bat` script.

**Comment by emily33901** [comment]
i still think that there should be a vcpkg integration for V that "just works" on windows or similar - never ygot around to doing it though
