### ISSUE TITLE
V has been open sourced, some notes about the alpha release

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#343]
Hello,

First of all, sorry for the 20 minute delay. I had serious Git issues and I had to destroy and re-create the repository twice.

That's also why README.md had old instructions, and it was not possible to build V right away.

The instructions are now correct.

This is the first public alpha release. While the compiler itself has been cleaned up, the modules haven't been. Many things were written back in May of 2018 when the language was a couple months old and were never touched again. The worst offenders are `os`, `gg`, `http`.

I decided to release everything for transparency, and no longer delay the release.

There are lots of hacks I'm really embarrassed about, like using `os.system()` instead of native API calls, especially on Windows. There's a lot of ugly C code with `#`, which I regret adding at all.

All of these will be quickly cleaned up in the coming weeks.

Someone also raised a concern about missing implementations for Linux. In many cases, code for macOS and Linux is the same, so if V sees there's a `_mac.v` file, but no `_lin.v` file, it uses that file for Linux builds.

**Comment by Hamzantal** [comment]
even with the update, I'm getting segmentation faults on build:
```
32350@2022-32350.local:/Users/32350/code/v/compiler git:(master*) $ ./vc -o v .
[1]    11900 segmentation fault  ./vc -o v .
```

**Comment by UditDey** [comment]
Add inline bash scripting

**Comment by iwasaki-kenta** [comment]
Compiled just fine for me on Ubuntu.

![image](https://user-images.githubusercontent.com/8392982/59968056-5403ff00-956e-11e9-8d01-d19bc59b1404.png)

Compiled the V compiler using `cc` with all of V's files cloned in directories `/var/tmp/vlang0.0.12/` and `~/code/v/` if that helps anyone.

**Comment by Wurdlack** [comment]
@UditDey You missed the platform son, this is not facebook

**Comment by Bleser** [comment]
`clang v.c -o vc`
work for me

**Comment by Bowero** [comment]
> `clang v.c -o vc`
> work for me on ubuntu

confirming this works on arch linux too

**Comment by UditDey** [comment]
@Wurdlack oh shit I just realised haha I had both the tabs open and got mixed up

**Comment by bentxt** [comment]
Thanks for great work!

**Comment by Immortalin** [comment]
@medvednikov do a Show HN?
