### ISSUE TITLE
Some struct default values not taken into account

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#3431]
**V version:** V 0.1.14 9b5e998
**OS:** Linux x64 (Fedora 31)

**What did you do?**
Ran tests in a module.

**What did you expect to see?**
Struct member has a default value. After creating an instance I expected the member to have the default value instead of the zero-value for the type. 
After running the tests, I was expecting the failed line to be shown.

**What did you see instead?**
Struct member had a zero-value instead of default value.
Source of failure was showing the incorrect line.

**
I have attached a sample module to see the problem, with the output from running the tests.
To run the tests, I simply ran "v test ."
[default_bug.zip](https://github.com/vlang/v/files/4055757/default_bug.zip)

**Comment by emily33901** [comment]
Appears to atleast just be on enum fields - I havent tested with strings or structs etc.

**Comment by duarteroso** [comment]
My guess is any default value according to me testing.
The attached files show it for int and enum (in a struct)

**Comment by duarteroso** [comment]
Only happens when running unit test (v test .)

**Comment by nedpals** [comment]
Closed. Fixed in the latest V version.

**Comment by aswin2575** [comment]
Guys I got a bug here
![Screenshot from 2024-05-19 00-10-44](https://github.com/vlang/v/assets/151365468/0c6be5ef-e0ed-490d-8685-5b67cac859b9)

Intermediate code on compiling my own vala binding from c using vapi. At creation time it is initializing but later it gets replaced by zeros on calling Test() constructor.

```
Gelabi.Test t = Gelabi.Test();
print("%d: %d\n", t.a, t.c);
```

**Comment by AnsifDev** [comment]
I got a bug guys
I am testing the manual vala binding using vapi.

My own c code
```
typedef struct {
    int a;
    int b;
    int c;
} test;

#define TEST_INIT { 2, 4, 8 }
```

My vapi file
