### ISSUE TITLE
JSON decoding/encoding

### ISSUE THREAD

**Issue by Arthurdw** [vlang/v#3432]
**V version:** 
**OS:**  idk its on website.

**What did you do?**
I ran the JSON decoding/encoding example code.

**What did you expect to see?**
Some basic json encode or decode magic.
 
**What did you see instead?**
"You just found a bug. V can't compile this program, but it should. Please create a GitHub issue."

**Comment by ZoleeHUN** [comment]
Duplicate of #3327

Seems like some of the examples on the main V lang playground website are still broken

**Comment by Arthurdw** [comment]
Close because of duplicate.
Thx @ZoleeHUN
