### ISSUE TITLE
Vui conn't running well under macOS 10.15.1.

### ISSUE THREAD

**Issue by changrui** [vlang/v#3435]
**V version:** 
v 0.1.24
**OS:** 
macOS 10.15.1

**What did you do?**
run `v run vlang/vlib/ui/examples/users/`.

**What did you expect to see?**
show `v ui demo` window.
 
**What did you see instead?
**failed to create a glfw window, make sure you have a GPU driver installed
create window wnd=0x0 ptr==0x0
Failed to initialize glad OpenGL context

**Comment by vitalyster** [comment]
MacOS VM? There are no VMs with GPU QE/CI support, so it is not possible to initialize GL there

**Comment by medvednikov** [comment]
It's better to use V UI's repo for this.
