### ISSUE TITLE
Generic syntax limitations

### ISSUE THREAD

**Issue by mokafolio** [vlang/v#3438]
Please correct me if I am wrong, but looking at the generic syntax right now and as far as I can tell there appear to be some limitations.

Let's say I have a generic struct `Foo<T>` and I want to have a free function that only operates on `Foo<T>`'s. Is there a syntax to do this? I could only make a fully generic function, but none that only worked on Foo's, i.e.:

```v
struct Foo<T>
{
    bar T
}

//this works, but compiles for any type, not just Foo
fn print_foo<T>(f T)
{
    println(f)
} 

//this does not compile
fn print_foo2<T>(f Foo<T>)
{
    println(f)
} 

//what if I want a signature that only accepts a specific Foo type? (also does not work afaik)
fn print_foo3(f Foo<f32>)
{
    println(f)
} 

fn main()
{
    f := Foo<f32>{
        bar: 2.5
    }
    print_foo(f)
    print_foo2(f)
    print_foo3(f)
}
```

Another thing that would be amazing is if you could specify methods that only work on certain instantiations of Foo, i.e.:

```v
fn (f Foo<f32>)  foo_f32_method()
{
    //...
}
```

of course with the existing generic method syntax that won't really work as there is no way to disambiguate it from:
```v
fn (f Foo<T>)  foo_f32_method()
{
    //...
}
```

maybe using a prefix such as `?` or `$` for the generic template parameters could be a way to allow that in the future, i.e.:
```v
fn (f Foo<?T>)  foo_generic_method()
{
    //...
}
```

I am just blurting this out after toying around with the current system. Please correct me if I missed something and share your thoughts. Thanks!

**Comment by emily33901** [comment]
Yeah generic function calling is kinda eh - I would probably wait for the new compiler which should fix most of this stuff

**Comment by mokafolio** [comment]
@emily33901 Sounds good! I think a thread to discuss what needs to be better is worth it though. The ideas posted above are some of my initial thoughts of what I think could be useful additions.

**Comment by yuyi98** [comment]
Fixed.

```v
struct Foo<T>
{
    bar T
}

//this works, but compiles for any type, not just Foo
fn print_foo<T>(f T)
{
    println(f)
} 

//this does not compile
fn print_foo2<T>(f Foo<T>)
{
    println(f)
} 

//what if I want a signature that only accepts a specific Foo type? (also does not work afaik)
fn print_foo3(f Foo<f32>)
{
    println(f)
} 

fn main()
{
    f := Foo<f32>{
        bar: 2.5
    }
    print_foo(f)
    print_foo2(f)
    print_foo3(f)
}

PS D:\Test\v\tt1> v run .
Foo<f32>{
    bar: 2.5
}
Foo<f32>{
    bar: 2.5
}
Foo<f32>{
    bar: 2.5
}
```
