### ISSUE TITLE
REPL compilation fails on OpenBSD

### ISSUE THREAD

**Issue by refacto** [vlang/v#3440]
**V version:** 25e7ceeef06a86f6fe3b056091ff4f4506034f46
**OS:** OpenBSD -current

**What did you do?**
After successfully compiling V, executing it results in:

```
V panic: V tool "/home/azarus/dev/v/tools/vrepl.v" could not be compiled
tools/vrepl.v:97:32: type `readline.Readline` has no field or method `read_line`
   95|                  prompt = '... '
   96|          }
   97|          mut line := readline.read_line(prompt) or {
                                               ^
   98|                  break
   99|          }
print_backtrace_skipping_top_frames is not implemented on this platform for now...
```

**What did you expect to see?**
Successful REPL execution.
 
**What did you see instead?**
Failure to compile the REPL.

**Comment by changrui** [comment]
Same as `freeBSD 12.1`.

**Comment by spytheman** [comment]
Please try to copy vlib/readline/readline_darwin.v to vlib/readline/readline_freebsd.v and see if that will work @changrui ?

**Comment by jiayeZhu** [comment]
> Please try to copy vlib/readline/readline_darwin.v to vlib/readline/readline_freebsd.v and see if that will work @changrui ?

It workes for me. I'm running freebsd 11.3

**Comment by mndrix** [comment]
> Please try to copy vlib/readline/readline_darwin.v to vlib/readline/readline_freebsd.v and see if that will work

That works for me on OpenBSD as well.

**Comment by medvednikov** [comment]
Fixed.
