### ISSUE TITLE
Add a test suite

### ISSUE THREAD

**Issue by watzon** [vlang/v#3451]
Currently we have access to one "test method" as far as I can tell, and that's `assert`. It's nice to have, but there's only so much you can do with it. It would be nice to have a more fully featured test suite built in so that we could do things like:

```v
assert_eq(foo, bar)
assert_panics(im_broken())
assert_not_empty(some_array)
// etc etc
```

This would be *extremely* helpful, especially when it comes to debugging tests since currently `assert` doesn't actually tell you what the value was that made the assertion failed. It just panics and tells you the line.

**Comment by medvednikov** [comment]
assert_eq is already here (assert)
assert_non_empty is just assert some_array.len == 0

assert_panics I agree with.

**Comment by medvednikov** [comment]
> doesn't actually tell you what the value was that made the assertion failed.

this will be fixed soon

**Comment by watzon** [comment]
> > doesn't actually tell you what the value was that made the assertion failed.
> 
> this will be fixed soon

I just figured something like this would require an `assert_eq` type function, unless it's all compiler magic. Either way that's the main thing I want. Saves a lot of debugging time.

**Comment by medvednikov** [comment]
Yes, this will be compiler magic :)

Assert is a builtin keyword.

**Comment by watzon** [comment]
> Yes, this will be compiler magic :)
> 
> Assert is a builtin keyword.

I figured as much. Any reason to not keep assert but also have a test suite built on top of it that's a little more flexible and easy to modify? Compiler internals are a little harder to contribute to, especially for newcommers.

**Comment by lutherwenxu** [comment]
This feature request is a duplicate of #9.
