### ISSUE TITLE
Build v from source

### ISSUE THREAD

**Issue by zoulincheng** [vlang/v#3456]
**V version:** lastest v source code
**OS:** win10

I build v from lastest source code, when I use "make" under v source folder, build failed.

$ make
cd /tmp/vc && git clean -xf && git pull --quiet
cd /var/tmp/tcc && git clean -xf && git pull --quiet
cc  -std=c99 -municode -w -o v2.exe /tmp/vc/v_win.c
make: cc: Command not found
make: *** [all] Error 127

Because " C:\mingw-w64\bin" has no cc program.

I use  " gcc  -std=c99 -municode -w -o v2.exe ./vc/v_win.c   " build from v source succsessful

**Comment by vitalyster** [comment]
You can call `make CC=gcc` without changes to Makefile.
Note, you can also build V with make.bat from plain command prompt without MSYS shell
