### ISSUE TITLE
Build vid from source code failed

### ISSUE THREAD

**Issue by zoulincheng** [vlang/v#3457]
**V version:** v2 
**OS:** win10

I build "vid" from source code ,failed.

I build "vid" ,First step "git clone https://github.com/vlang/vid" and then "git clone --depth=1 https://github.com/ubawurinna/freetype-windows-binaries [path to v repo]/thirdparty/freetype/",
This two step is succsessful, But when I done "cd vid
v .
./vid"

build failed, display this message:
"
$ v2 -g .
warning: .\vid.v:1820:1: the following imports were never used:
 * uiold
D:\gitsource\v_lang\vid\zquery.v:346: warning: "UNICODE" redefined
<command-line>: note: this is the location of the previous definition
In file included from D:\gitsource\v_lang\v\thirdparty\stb_image/stb_image.h:547,
                 from D:\gitsource\v_lang\vid\zquery.v:370:
D:\gitsource\v_lang\v\thirdparty\stb_image/stb_image.h: In function 'stbi__shiftsigned':
D:\gitsource\v_lang\v\thirdparty\stb_image/stb_image.h:5116:18: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
    STBI_ASSERT(v >= 0 && v < 256);
                  ^~
D:\gitsource\v_lang\v\thirdparty\stb_image/stb_image.h:5116:4: note: in expansion of macro 'STBI_ASSERT'
    STBI_ASSERT(v >= 0 && v < 256);
    ^~~~~~~~~~~
D:\gitsource\v_lang\vid\zquery.v: At top level:
D:\gitsource\v_lang\vid\zquery.v:373:10: fatal error: ft2build.h: No such file or directory
compilation terminated.
C compiler=gcc
V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
"

**Comment by changrui** [comment]
my compile result is: 
```
.\timer.v:155:61: wrong number of arguments in call to `gg.GG*.draw_line(f32, f32, f32, f32)`
  153|                          '${hour:02d}', time_cfg)
  154|          }
  155|          t.gg.draw_line(hour_x, hour_y, hour_x + hour_width, hour_y, gx.gray)
                                                                            ^
  156|  }
  157|  // Large left vertical line

```

**Comment by nedpals** [comment]
Closed. Issues about Vid should be filed in  [vlang/vid](https://github.com/vlang/vid) repo instead.
