### ISSUE TITLE
Using '_' instead of  'else' in match just like rust

### ISSUE THREAD

**Issue by yuyi98** [vlang/v#3459]
Using '_' is concise in match just like rust!

**Comment by Delta456** [comment]
What you mean? `_` should replace `else`?

**Comment by iredmail** [comment]
I suggested this before. :)

**Comment by yuyi98** [comment]
Yes, use '_' to replace 'else' in match.

**Comment by emily33901** [comment]
`_` doesnt quite have the same semantics in V that would make this make much more sense like it does in rust

**Comment by medvednikov** [comment]
V matches use `{}, so `else { }` is the same syntax as in `if`.

It's simple and predictable.

No need to introduce another syntax rule.
