### ISSUE TITLE
Add support for arrays in generics

### ISSUE THREAD

**Issue by zlianon** [vlang/v#3461]
```v
fn test<T>(a T) {
    println(a[0])
}

fn main() {
    mut arr := []string

    arr << "V"

    test(arr) // Expected result: V, but i get error: incompatible type for argument 1
}

**Comment by ntrel** [comment]
BTW it works in the playground if you change the function declaration to:
```v
fn test<T>(a []T)
```
But I think this issue needs to be fixed for truly generic functions. ISTM this is a bug not a feature request (but I haven't been following V lately).

**Comment by sheerun** [comment]
Yes, please change it to bug. For example following doesn't work as well:

```
fn identity<T>(id []T) []T {
  return id
}

fn main() {
  a := identity<int>([1,2,3])
  println(a)
}
```

it results with:

```
cgen error: could not generate string method T_str for type 'T'
```

**Comment by Delta456** [comment]
This works under latest V.
