### ISSUE TITLE
vlang.io/play Playground example error - Advanced consts AND Basic Operator Overloading example

### ISSUE THREAD

**Issue by kokizzu** [vlang/v#3462]
**V version:** 0.1.24 0d93eeb probably
**OS:** not sure what server vlang.io use

**What did you do?**
https://vlang.io/play

**What did you expect to see?**
```
[1, 2, 3]
{255, 0, 0}
{0, 0, 255}
```
 
**What did you see instead?**
```
.str() methods must be declared as public
    7| }
```

**Comment by dhonx** [comment]
Hi @kokizzu  🙂
Can we know the code from the example you are trying to run there ??

**Comment by dhonx** [comment]
Oh, is this?
```v
struct Color {
        r int
        g int
        b int
}

fn (c Color) str() string { return '{$c.r, $c.g, $c.b}' }

fn rgb(r, g, b int) Color { return Color{r: r, g: g, b: b} }

const (
        numbers = [1, 2, 3]

        red  = Color{r: 255, g: 0, b: 0}
        blue = rgb(0, 0, 255)
)

println(numbers)
println(red)
println(blue)
```

**Comment by requnix** [comment]
To get it to run change the line
```
fn (c Color) str() string {
```
to
```
pub fn (c Color) str() string {
```

A similar approach fixes some of the other examples too.

**Comment by alexesprit** [comment]
Fixed in https://github.com/vlang/website/commit/fdbe6ab12a40717a0b4a1320453c381fb4aed63b.
