### ISSUE TITLE
V can't import module with dashes but vpm use github username

### ISSUE THREAD

**Issue by etienne-napoleone** [vlang/v#3467]
**V version:** V 0.1.24 1e98a22
**OS:** 64bit Mac OS X 10.14.6 18G2022

**What did you do?**

Tried using my module:
`$ v install etienne-napoleone.chalk`
`$ v`
```v
>>> import etienne-napoleone.chalk
cannot import module "etienne" (not found)
```
Removing the dash in `~/.vmodules/etienne-napoleone` fixes it.

**What did you expect to see?**
No error, module imported
 
**What did you see instead?**
An error because `-` is probably an illegal character in imports.
As vpm uses github usernames, it doesn't make sense to block all people having a dash in their username to issue v packages.
The two ways that comes to mind to solve this are:
- accept `-` in imports
- trim the `-` in vpm (but then you can have username collision)

**Comment by spytheman** [comment]
For the moment, vpm requires manual intervention to fix such names. That will be done automatically soon (+ allowing editing of the username. part, without allowing duplicates with already existing names).

**Comment by Serkonda** [comment]
Fixed by https://github.com/vlang/v/pull/5583
