### ISSUE TITLE
Where are the tests?

### ISSUE THREAD

**Issue by zenwarr** [vlang/v#347]
You said there are some tests (https://github.com/vlang/v/issues/296#issuecomment-504663767), but source code has not a single test. You should create some, dude.

**Comment by medvednikov** [comment]
I was experiencing major Git problems, lots of files (including all tests) are missing.

**Comment by medvednikov** [comment]
They will be published asap.

**Comment by UditDey** [comment]
The only test here is that of our patience

**Comment by Wurdlack** [comment]
@UditDey Your patience? Really? Someone owes you something?

**Comment by UditDey** [comment]
@Wurdlack I was promised a dream lang that would make me cum gallons

**Comment by Bowero** [comment]
There are multiple tests now, even automated with Continuous Integration.
