### ISSUE TITLE
C error while compiling Tetris example

### ISSUE THREAD

**Issue by orangezyx** [vlang/v#3470]
v run tetris/tetris.v
/Users/zhangyuxin/v/thirdparty/glad/glad.o not found, building it...

/var/folders/lf/m1pygbn91vb_lm1xj2y35_f00000gn/T/v/tetris.tmp.c:3964:7: warning: incompatible integer to pointer conversion initializing 'void *' with an expression of type 'int' [-Wint-conversion]
vo...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by lutherwenxu** [comment]
Can you run the build with `v -cg run tetris/tetris.v`?

**Comment by orangezyx** [comment]
Thanks a lot, I have resolve this issue, I just forgot to install the glfw lib.
