### ISSUE TITLE
missing comma generating varargs with a struct before the varargs

### ISSUE THREAD

**Issue by prime31** [vlang/v#3475]
**V version:** V 0.1.24 ccf6134
**OS:** macos

**What did you do?**
the method definition is like this:
`pub fn (sb mut SpriteBatch) add_q(quad &math.Quad, args...f32)`

calling the method like this:
`state.batch.add_q(q, 0.0, (f32(i) + 1.0) * 32.0)`

It seems the comma after the first param is omitted when the C is generated.

**What did you expect to see?**
Successful compilation.
 
**What did you see instead?**
```
spritebatch_tester.v:32:68: error: invalid operands to binary expression ('via_dot_math__Quad *' (aka 'struct via_dot_math__Quad *') and 'varg_f32' (aka 'struct varg_f32'))
 via_dot_graphics__SpriteBatch_add_q ( state ->batch , & /*114*/ q &(varg_f32){.len=2,.args={ 0.0, ( ((f32)( i ) ) + 1.0 ) * 32.0}} ) ;
                                                       ~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by alexesprit** [comment]
Seems like it's fixed in v2 backend. Could someone else confirm it's fixed?

**Comment by alexesprit** [comment]
Works fine for me using this example:
```
struct Object {
}

struct Arg {
}

pub fn (this Object) varg(arg &Arg, args... f32) {
	println(args.len)
}

fn main() {
	obj := Object{}
	obj.varg(Arg{})
	obj.varg(Arg{}, 3.0, 4.2)
}
```

**Comment by alexesprit** [comment]
Closed as fixed.
