### ISSUE TITLE
Function name not checked while compiling

### ISSUE THREAD

**Issue by sbgatne** [vlang/v#3481]
**V version:**  i don't know
**OS:** windows8.1

```v
fn main() { 
	areas := ['game', 'web', 'tools', 'science', 'systems', 'GUI', 'mobile']

        for area in areas {
                print(toupper('$area'))
        }
} 
//above does not compile
```.

**Comment by kokizzu** [comment]
tested on playground, yes, the compile result is:
```
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.
```

**Comment by lutherwenxu** [comment]
I think you meant this instead:
```
fn main() {
areas := ['game', 'web', 'tools', 'science', 'systems', 'GUI', 'mobile']

    for area in areas {
            print(area.to_upper())
    }
}
```

Although I agree V not checking function name is problematic.

**Comment by spytheman** [comment]
That is because there is already a C function named toupper ...

**Comment by spytheman** [comment]
The problem seems to be that currently the V compiler does not check whether the types of the parameters passed to C functions match their declarations, leaving this job to the backend C compiler.

**Comment by Ivo-Balbaert** [comment]
The top program now (v 0.1.27 7963e48) and in the Playground gives the V error:

test.v:5:23: error: unknown function: toupper 

which solves the issue.
