### ISSUE TITLE
recompiling the compiler: Segmentation fault: 11

### ISSUE THREAD

**Issue by bentxt** [vlang/v#349]
doing as described in the readme:

the 'vc' compiler segfaults

```
mkdir -p ~/code && cd ~/code  # ~/code directory has to be used (it's a temporary limitation)
git clone https://github.com/vlang/v
cd v/compiler
wget https://vlang.io/v.c # Download the V compiler's source translated to C
cc -w -o vc v.c           # Build it with Clang or GCC
./vc -o v .               # Use the resulting V binary to build V from V source
```
Segmentation fault: 11

-----
this is on mac os
$ cc -v
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by zac-garby** [comment]
what happens if you type `clang v.c`

**Comment by cheslip** [comment]
see #345

**Comment by jgouly** [comment]
You need to `mkdir /var/tmp/vlang0.0.12/`

**Comment by Bowero** [comment]
> what happens if you type `clang v.c`

resolved my issue.

**Comment by bentxt** [comment]
clang v.c -o vc
./vc
V 0.0.12
>>> println('hello')
Segmentation fault: 11

**Comment by CryZe** [comment]
@bentxt you need mkdir /var/tmp/vlang0.0.12/

**Comment by bentxt** [comment]
yes thanks 

mkdir /var/tmp/vlang0.0.12/

solved my issue, while using 'clang' didnt' make a difference

**Comment by bentxt** [comment]
thanks for super fast (realtime) help
