### ISSUE TITLE
vlang.io/play Playground example error

### ISSUE THREAD

**Issue by andorxornot** [vlang/v#3493]
**V version:** 0.1.24 probably
**OS:** not sure what server vlang.io use

**What did you do?**
open https://vlang.io/play and try to compile json example

**What did you expect to see?**
normal output
 
**What did you see instead?**
`You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.`

`import json` bring this error

**Comment by ZoleeHUN** [comment]
Duplicate of #3327 
The main site playground is still broken, use https://devbits.app/play/tHDOscbTGf8W

**Comment by alexesprit** [comment]
Closed as a duplicate.
