### ISSUE TITLE
Struct fields: could not find method

### ISSUE THREAD

**Issue by najlot** [vlang/v#3494]
**V version:** 
V 0.1.24 8c1b03c

**OS:** 
Windows 10

**What did you do?**
I've written some simple code and tried to run it.
`
struct Toaster {
pub mut:
  a int
  b int = 10
}

ttt := Toaster{}

println("Toaster: $ttt.b")
`

**What did you expect to see?**
No compilation errors and "Toaster: 10" after I run the exe.
 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/38798099/72670708-0fc3d900-3a41-11ea-85ce-5dac3a7be397.png)

---

The example at https://vlang.io/docs#structs does not work, too:
![image](https://user-images.githubusercontent.com/38798099/72670762-b6a87500-3a41-11ea-8c8f-64df940a499b.png)

**Comment by najlot** [comment]
Looks like I need to use the struct in a function, because following code works:
`
struct Toaster {
pub mut:
  a int
  b int = 10
}

fn (u Toaster) can_toast() bool {
	return u.a > 0
}

mut ttt := Toaster{}
ttt.b = 5

println('Toaster: $ttt.b')
`

**Comment by alexesprit** [comment]
The latest V produces the expected output. The example is a different a little, as `main` function is required.
```
struct Toaster {
pub mut:
	a int
	b int = 10
}

fn main() {
	ttt := Toaster{}
	println('Toaster: $ttt.b')
}
```
```
$ vrun test.v 
Toaster: 10
```
