### ISSUE TITLE
File wiped at sub-block exit ?

### ISSUE THREAD

**Issue by nsauzede** [vlang/v#3495]
**V version:** 
V 0.1.24 8c1b03c

**OS:** 
ClearLinux

**What did you do?**
```v
import os
fn test_file(fnameout string) {
  mut fout := os.File{cfile: 0}
  if fnameout != '' {
    fout = os.create(fnameout) or {exit}
    println(fout)
  }
  println(fout)
}
fn main() {
  test_file('test.tmp')
}
```

**What did you expect to see?**
```shell
$ v run A.v 
{
	cfile: 0x5556729f4520
	fd: 0
	opened: 1
}
{
	cfile: 0x5556729f4520
	fd: 0
	opened: 1
}
```
 
**What did you see instead?**
```shell
$ v run A.v 
{
	cfile: 0x5556729f4520
	fd: 0
	opened: 1
}
{
	cfile: (nil)
	fd: 0
	opened: 0
}
```

**Comment by spytheman** [comment]
NB: this however works:
```v
import os

fn test_file(fnameout string) {
        mut fout := os.File{cfile: 0}
        if fnameout != '' {
                t := os.create(fnameout) or { panic(err) }
                fout = t
                println('This is valid fout after create:')
                println(fout)
        }
        println('This is fout at the end')
        println(fout)
}
fn main() {
        test_file('test.tmp')
}
```

The problem occurs only when the optional is assigned to an already existing variable.

**Comment by nsauzede** [comment]
You're right, it works, thanks !
And is better than creating the file blindly before testing if the name is empty
I'll use thi workaround until the big is fixed
I bet (hope) this bug will be automagically fixed with the AST compiler
fingers crossed

**Comment by spytheman** [comment]
I hope so too. It is a problem in the generated C code for optionals, and the code generation will benefit most from having a nice AST.

**Comment by Ivo-Balbaert** [comment]
The top code example with or {exit} changed in or { panic(err) } now (V 0.1.27 7963e48) works on Windows 10 with output:

os.File {
    cfile: -620627312
    fd: 3
    opened: true
}
os.File {
    cfile: -620627312
    fd: 3
    opened: true
}
