### ISSUE TITLE
Assigning the values of a method with multiple return fails when one is a struct member

### ISSUE THREAD

**Issue by prime31** [vlang/v#3496]
**V version:** V 0.1.24 b1602c7
**OS:** macos

**What did you do?**
The following example shows when a method with multiple return values is called the values cant be assigned to struct members. The second call to the method is successful when there is no struct members involved.

```c
pub struct State {
pub mut:
    value int
}

fn main() {
	s := State{}
	
	// does not work
	s.value, other = return_two()
	
	// does work
	first, second := return_two()
}


fn return_two() (int, int) {
	return 1, 2
}
```

**What did you expect to see?**
Both calls to the method should compile
 
**What did you see instead?**
```
bug.v:12:9: unexpected token: `,`
   10| 	
   11| 	// does not work
   12| 	s.value, other = return_two()
             	 ^
   13| 	
   14| 	// does work
```

**Comment by Ivo-Balbaert** [comment]
This now gives the error:  V panic: as cast: cannot cast 212 to 153

**Comment by joe-conigliaro** [comment]
I'm closing this issue as it is fixed, the example abolve will still not work since you can't assign to a struct field using the deceleration assignment syntax `:=`, you need to use `=`. The following example works:
```go
module main

struct State {
pub mut:
    value int
}

fn main() {
	mut s := State{}
	mut other := 1

	s.value, other = return_two()
	println(s.value)
	println(other)
}


fn return_two() (int, int) {
	return 1, 2
}
```
