### ISSUE TITLE
FreeBSD/Clang  - ld: error: undefined symbol: backtrace referenced by v.c

### ISSUE THREAD

**Issue by XVilka** [vlang/v#3500]
**V version:** https://github.com/vlang/v/commit/cf1fd6e9500401a78ef0ecd5ce103d630f0b0f5d commit
**OS:**  FreeBSD

**What did you do?**

The sources are located here The sources are located here: https://github.com/radareorg/radare2/tree/master/test/src

Compile V

**What did you expect to see?**

Compiled V
 
**What did you see instead?**

See the https://builds.sr.ht/~xvilka/job/139590#task-install-481 for the full build log, it is caused by the following SourceHut configuration: https://github.com/radareorg/radare2/blob/92a494a4bac7c581cc2161f99f2cab77d3990147/.builds/freebsd.yml

```
gmake -C v
gmake[2]: Entering directory '/usr/home/build/radare2/test/src/v'
gmake fresh_vc
gmake[3]: Entering directory '/usr/home/build/radare2/test/src/v'
rm -rf /tmp/vc
git clone --depth 1 --quiet https://github.com/vlang/vc /tmp/vc
gmake[3]: Leaving directory '/usr/home/build/radare2/test/src/v'
cd /tmp/vc && git clean -xf && git pull --quiet
gmake fresh_tcc
gmake[3]: Entering directory '/usr/home/build/radare2/test/src/v'
rm -rf /var/tmp/tcc
git clone --depth 1 --quiet https://github.com/vlang/tccbin /var/tmp/tcc
gmake[3]: Leaving directory '/usr/home/build/radare2/test/src/v'
cd /var/tmp/tcc && git clean -xf && git pull --quiet
clang  -std=gnu11 -w -o v /tmp/vc/v.c  -lm
ld: error: undefined symbol: backtrace
>>> referenced by v.c
>>>               /tmp/v-39df08.o:(print_backtrace_skipping_top_frames_freebsd)

ld: error: undefined symbol: backtrace_symbols_fd
>>> referenced by v.c
>>>               /tmp/v-39df08.o:(print_backtrace_skipping_top_frames_freebsd)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by devnexen** [comment]
`-lexecinfo` needs to be passed, unlike Linux not a part of libc.

**Comment by spytheman** [comment]
There is a separate makefile for BSDs that has -lexecinfo. 

If you insist to use gmake instead of bsd make, then please edit Makefile and add BSD detection logic.

**Comment by radare** [comment]
this bsdmakefile doesnt works on openbsd, and imho its a bad idea to have multiple makefiles. gmake works fine on *BSD

**Comment by radare** [comment]
fixed in https://github.com/vlang/v/pull/3710
