### ISSUE TITLE
UTF-8 string with accents not uppercased correctly

### ISSUE THREAD

**Issue by LRjunior** [vlang/v#3505]
**V version:** V 0.1.24 bfaf2a4
**OS:** Windows 10

**What did you do?**
```v
fn main() {
	words := ['ďateľ', 'páv']
	upper := words.map(it.to_upper())
	print(upper)
}
```

**What did you expect to see?**
`["ĎATEĽ", "PÁV"]`
 
**What did you see instead?**
`["ďATEľ", "PáV"]`

**Comment by LRjunior** [comment]
I have found a solution:

```v
import encoding.utf8

fn main() {
	words := ['ďateľ', 'páv']
	upper := words.map(utf8.to_upper(it))
	print(upper)
}
```

**Comment by medvednikov** [comment]
Yes, utf8 tables increase the size of the binary a lot, so they are not used by string.to_upper().

I'll add a warning in case there's a non ascii character in a string that's being uppercased.

**Comment by penguindark** [comment]
@medvednikov `string.to_upper` is mean to be a quick function, add a test for each string can slow a lot the program.
`utf8.to_upper` work quite well but is slow.
Can be better only document this feature instead add controls in a code that is written for speed like `string.to_upper`?

**Comment by medvednikov** [comment]
Yes @penguindark that's what I'll do.
