### ISSUE TITLE
Hot code reloading.

### ISSUE THREAD

**Issue by markgraydev** [vlang/v#351]
> Get your changes instantly without recompiling.
> Since you also don't have to get to the state you are working on after every compilation, this can > save a lot of precious minutes of your development time."

How can I test hot code reloading?

**Comment by binkiklou** [comment]
I doubt you can.

**Comment by Aearnus** [comment]
Should be able to do it with [this](https://linux.die.net/man/1/watch), considering how fast V can compile code.

**Comment by lemon-sherbet** [comment]
coming 2021

**Comment by AurelienFT** [comment]
According to the documentation you can't test it right now.

**Comment by hubyhuby** [comment]
Starts to work now ;)
https://github.com/vlang/v/tree/master/examples/hot_reload
![image](https://user-images.githubusercontent.com/26340942/139523036-3dd70c1b-75d8-435c-8379-6c7e722f9369.png)
