### ISSUE TITLE
模块导入需求

### ISSUE THREAD

**Issue by Febby315** [vlang/v#3510]
模块导入 为解决文件名较长 建议使用as 关键字 设置别名

**Comment by changrui** [comment]
已经有了这个功能。

**Comment by alexesprit** [comment]
```v
import mymodulelongname as shortname

fn main() {
    shortname.func()
}
```

Does it work for you?

Please, submit issues in English only, so non-Chinese speakers can participate too.

**Comment by Febby315** [comment]
> 已经有了这个功能。



> 已经有了这个功能。

Thank you, I look at the site said the document did not mention
