### ISSUE TITLE
build fails with windows10 and Visual Studio 2019

### ISSUE THREAD

**Issue by gshields** [vlang/v#3511]
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.4.3
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28315 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools>cd e:
E:\

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools>e:

E:\>cd p-tools\v

E:\p-tools\v>make.bat
Building V
git version 2.25.0.windows.1
Downloading v.c...
Attempting to build v.c  with MSVC...
v_win.c
vc\v_win.c(5): fatal error C1083: Cannot open include file: 'inttypes.h': No such file or directory
cl.exe failed to build V
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error
@emily33901

**Comment by vitalyster** [comment]
I had the same issue with broken msvc installation, try to repair it from visual studio installer

**Comment by gshields** [comment]
I ended up going back to Mingw to compile, visual studio is not something I
want to install as too much disk.
I prefer vscode
There was an update to git recently that fixed the repl feature of v
(thanks!)
The reason I tried the command line ms compiler was the missing
repl feature and I thought a different compile would have different results.
I also tried the LLVM compile to see how that compile worked,  but it was
missing the ms header (they are included with Mingw)
Thanks

**Comment by lutherwenxu** [comment]
I'm assuming this has already been resolved?
Feel free to reopen this issue if it hasn't.

**Comment by aggsol** [comment]
I still have this issue with current master

```
Building V
git version 2.22.0.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
INFORMATION: Es konnten keine Dateien mit dem angegebenen
Muster gefunden werden.
Attempting to build v.c  with MSVC...
v_win.c
vc\v_win.c(463): fatal error C1083: Cannot open include file: 'inttypes.h': No such file or directory
cl.exe failed to build V
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error
```

**Comment by vitalyster** [comment]
@aggsol have you tried visual studio repair from installer?
