### ISSUE TITLE
runtime in-source builds conflicts with .deb packaging

### ISSUE THREAD

**Issue by qzmfranklin** [vlang/v#3512]
**V version:** 
**OS:** 

Ubuntu 18.04.3
v commit:`53b06048d2d41f183698a560a82f70042e3fcd8e`

**What did you do?**

1. Package the whole repo (fresh git clone) into a .deb package and install the .deb file.

The .deb file installs to `/opt/v/v`.

2. Run `/opt/v/v` to start the REPL:

```bash
/opt/v/v
```

**What did you expect to see?**

The REPL starts properly.
 
**What did you see instead?**

```text
V panic: V tool "/opt/v/com_github_vlang_v/tools/vrepl.v" could not be compiled
denied
collect2: error: ld returned 1 exit statusV error: C error. This should never happen. 
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
                                               | 0x7f0ad0db2b97 | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) 
                                               |       0x21e02a | v() 
```

I then `chown`ed the `/opt/v directory from `root:root` to `zhongming:zhongming`. Then it works.

I noticed that `v` compiles the libraries as needed and put the generated files in the **same** directory as the source files. This behavior conflicts with the root-0644 owner-mode of files installed by .deb files.

I'd still want to install vlang as a .deb package (already did) and make it work.

Not sure what the plan here is to support such use cases.

**Comment by dumblob** [comment]
As a package maintainer, I'd say you could patch the *V* source to use e.g. an env variable `V_WORKING_DIR` as a general directory to be used for all new files and dirs. If none given *V* would then create one in `/tmp` on unix-based systems and properly chown it to disallow others reading its content. Users are then free to use e.g. `$XDG_CACHE_HOME` (or maybe even `$XDG_DATA_HOME`) as `$V_WORKING_DIR` if they like.

**Comment by spytheman** [comment]
@qzmfranklin ,

You can build the tools/*.v files before you make the .deb package.

V checks if the timestamp of the tools/name is older than the timestamp of the main v executable and is it older than the timestamp of tools/name.v . If it is not, it assumes the tool is recent enough and will not recompile it.

You can use the following script to do it:
```shell
./v build-tools
./v build-examples
/v -prod -d vfmt tools/vfmt.v
```

Running the above will compile all the examples and all the tools with the proper options. 
After that, you can package the results.

**Comment by qzmfranklin** [comment]
@spytheman 

Gotcha. It sounds like a pretty approachable and maintainable solution to a package maintainer like me. Thanks!

**Comment by Ivo-Balbaert** [comment]
@qzmfranklin did it work out correctly? If so, can the issue be closed?

**Comment by qzmfranklin** [comment]
@Ivo-Balbaert 

Thanks for checking in. I was not able to find a good time to try it out, due to priority and deadlines recently. But that sounds like a pretty plausible approach. I'd think we can close this issue for now. If I do run into this issue in the future I'll reopen it.

Thanks for the help and patience!
