### ISSUE TITLE
V can't compile this program, but it should.

### ISSUE THREAD

**Issue by KhaledSharif** [vlang/v#352]
## How to recreate

Go to https://vlang.io/play
Try to compile "JSON decoding/encoding"

## Expected result

Code compiles and runs

## Actual result

"You just found a bug. V can't compile this program, but it should. Please create a GitHub issue."

**Comment by musou1500** [comment]
@KhaledSharif I think it's a same problem as https://github.com/vlang/v/issues/361
PR is already created. "JSON decoding/encoding" will work if PR is merged.

**Comment by Bowero** [comment]
This has been resolved.
