### ISSUE TITLE
Hash algorithm (for hashmap, strings, etc.)

### ISSUE THREAD

**Issue by dumblob** [vlang/v#3521]
There was a [request](https://github.com/vlang/v/issues/1047 ) to use a better hash function for strings. I don't think it's necessary, but for a hashmap, it already matters a lot. There are also other possible use cases in *V* as well as just having a high quality (passes [SMHasher](https://github.com/rurban/smhasher/ ) and other tests) hash function standalone in *V* lib (maybe a template for strings, ints, floats, and arrays of all these primitive types).

I was waiting with this request for half a year to let the best known hash function (which passes all the quality criteria incl. speed) mature. I think time came, so let me introduce [wyhash v4](https://github.com/wangyi-fudan/wyhash ). I'm not sure though how the *V* variant will perform as if there won't be any [intrinsics](https://github.com/vlang/v/issues/1839#issuecomment-559733328 ) used (e.g. through conditional compilation `$if ! js { /* let's use intrinsics */ }`), the speed will unnecessarily degrade.

**Comment by medvednikov** [comment]
It uses Java's hash function, which is pretty battle tested :)

**Comment by dumblob** [comment]
>It uses Java's hash function, which is pretty battle tested :)

I suppose you're referring to `string`. I'm OK with `string` using the simple hash (even though it's slower than the proposed `wyhash` and has way lower quality). My proposal is about a universal hash in *V* stdlib. Such hash shall be crossplatform-stable (i.e. on little/big endian, on x86/ARM, etc. always the same results) and very fast (both for very short inputs as well as for very long inputs - though short inputs are slightly more important).

As I wrote, I'd also like to see `wyhash` in the *V* hashmap. Speaking about Java, it [uses it's built-in `hash()`](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/HashMap.java ) function which is JRE-specific and has very bad quality (see how it's [implemented e.g. in OpenJDK](https://srvaroa.github.io/jvm/java/openjdk/biased-locking/2017/01/30/hashCode.html )) - therefore also proposal [JEP draft: Better hash codes](https://openjdk.java.net/jeps/8201462 ) proposing actually still worse hash functions than `wyhash` (but way better than the current `hash()` and than the hash used for string hashing: `for i := 0; i < s.len; i++ { hash = hash * int(31) + int(s.str[i]) }`).

**Comment by ka-weihe** [comment]
We have be working on putting wyhash in the hashmap. It currently uses FNV1a, but if wyhash provides an improvement it will naturally be the hash-function in the hashmap. And I agree, dbj2 hash (the current string hash) should not used. It has a lot of collisions and biased hashes.

**Comment by ka-weihe** [comment]
The hashmap is now using wyhash4 as the default hash-function a14a5fbf95f0dd0182366d2008ad874ca2f87d4c.

This issue can be closed.

**Comment by joe-conigliaro** [comment]
https://github.com/vlang/v/commit/a14a5fbf95f0dd0182366d2008ad874ca2f87d4c

**Comment by dumblob** [comment]
One small change from the hash author making it few percent faster: https://github.com/rurban/smhasher/issues/96#issuecomment-581212742

**Comment by dumblob** [comment]
Feel free to update wyhash as the newest version solves one potential security issue and is even a tiny bit faster than the previous versions :wink:.

**Comment by ka-weihe** [comment]
We are working on it :slightly_smiling_face:

**Comment by dumblob** [comment]
No need to hurry - it's just a reminder to not forget about it before next release.

**Comment by dumblob** [comment]
New version of wyhash got released (it shall fix the bad seeds issue and couple of others).

See also https://github.com/vlang/v/issues/9553#issuecomment-1299875573 and https://github.com/rurban/smhasher/issues/243 .
