### ISSUE TITLE
Compiler cannot compile itself

### ISSUE THREAD

**Issue by vtereshkov** [vlang/v#3523]
**V version:** 0.1.24
**OS:** Windows 7

**What did you do?**
Run make.bat: `c:\Users\vtereshkov\Desktop\v-0.1.24>make`

**What did you expect to see?**
Successful bootstrapping
 
**What did you see instead?**
```
Building V
git version 2.22.0.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Now using V to build V...
eptr* argv) {
               ^~~~~~~~~~~~~~~~~~~~~V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
'v3.exe' is not recognized as an internal or external command,
operable program or batch file.
v.exe failed to compile itself - Create an issue at 'https://github.com/vlang'
```

**Comment by lutherwenxu** [comment]
The CI test have been passing recently and one of the things tested is building on Windows.
Is your issue still present?

**Comment by vtereshkov** [comment]
Now everything seems to be OK. But this problem was intermittent, so I cannot say for sure that it will never come back.
