### ISSUE TITLE
Can't create a struct with an array of map field

### ISSUE THREAD

**Issue by augustoccesar** [vlang/v#3525]
**V version:**  V 0.1.24 64a9f43
**OS:** Ubuntu 18.04.3 LTS (Bionic Beaver)

**What did you do?**
```
>>> struct SomeStruct {
...     content []map[string]string
... }
>>> val := SomeStruct {content: [{"key": "val"}]}
```

**What did you expect to see?**
A created `SomeStruct`
 
**What did you see instead?**
```
cannot convert `[]map_string` to `map_string`
```

**Comment by alexesprit** [comment]
Works fine on latest V.
![image](https://user-images.githubusercontent.com/1119267/80910306-1e57a700-8d37-11ea-9932-ce2afd78227b.png)
