### ISSUE TITLE
Issues when compiling on linux

### ISSUE THREAD

**Issue by mingodad** [vlang/v#353]
Hello !
Trying to compile on linux 64bits I found this issues:
- Need to include "#include <string.h>" and "#include <ctype.h>"
- Double definition of "#define MAX 1000" and "#define MAX 5000"
- Redefinition of "EOF" to 0 but in linux it's -1
- In "string i64_hex(i64 n)" the recommended placeholder is "0x%lx"
- Hard coded path "string lang_dir = string_add(os__home_dir(), tos2("/code/v/"));"
- Unrecognized escape "(c == '\`')"

And after fixing all of it we get segfault.

**Comment by kitech** [comment]
Did u try `clang -w -o vc v.c`? it works for me, but gcc not.

**Comment by mingodad** [comment]
It compiles but doesn't work.
You need to add -Wall to see the issues pointed here.
```
clang -Wall -o vc v.c
```
Cheers !

**Comment by Oxylibrium** [comment]
@mingodad can you run `clang -v` / `gcc -v` on your system and retest with the latest `v.c`? Unable to reporoduce on my local machine.

**Comment by Bowero** [comment]
Using the latest version of `clang` works without a doubt, but many of these problems have been fixed already. Please refer to the other issues if necessary.
