### ISSUE TITLE
OpenBSD - unable to pass LLVM bit-code files to linkerV error: C error. This should never happen. 

### ISSUE THREAD

**Issue by XVilka** [vlang/v#3530]
**V version:**  https://github.com/vlang/v/commit/cf1fd6e9500401a78ef0ecd5ce103d630f0b0f5d commit
**OS:** OpenBSD

**What did you do?**

The sources are located here: https://github.com/radareorg/radare2/tree/master/test/src
```
v/v -prod r2r.v
```

**What did you expect to see?**

Successfully compiled program
 
**What did you see instead?**

See the https://builds.sr.ht/~xvilka/job/140599#task-install-684 for the full build log, it is caused by the following SourceHut configuration: https://github.com/radareorg/radare2/blob/c9020e32e62c0bd083096e68318554096578ba0b/.builds/openbsd.yml#L24

```
Installing module "radare.r2" from https://github.com/radare/v-r2.git to /home/build/.vmodules/radare/r2 ...
v/v -prod r2r.v
warning: r2r.v:35:17: reference field `R2R.r2` must be initialized
warning: r2r.v:35:17: reference field `R2R.wg` must be initialized
6.6': unable to pass LLVM bit-code files to linkerV error: C error. This should never happen. 
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
gmake[1]: *** [Makefile:9: all] Error 1
```

**Comment by spytheman** [comment]
You can pass `-show_c_cmd -cg` to v, in order to see the full backend C compilation log.

**Comment by spytheman** [comment]
Not sure that is a V bug actually, but I do not have access to an OpenBSD system to test.

An OpenBSD oddity however that may affect v compilation is that on OpenBSD, os.executable is not implemented properly (see vlib/os/os.v around line 901). That makes v to default to using os.args[0] to guess the v executable location, which may not be very reliable if it was launched with a relative path. A possible solution is to `export VEXE=/abs/path/to/v` or to launch v with its absolute path.

**Comment by Ivo-Balbaert** [comment]
@XVilka is this still an open issue for you?

**Comment by XVilka** [comment]
@Ivo-Balbaert we don't use V in radare2 anymore, sorry. Setting up your own *BSD CI will help: https://github.com/vlang/v/issues/2974
