### ISSUE TITLE
V error: C error. This should never happen.

### ISSUE THREAD

**Issue by FlashChaser** [vlang/v#3532]
**V version: V 0.1.24 136c469** 
**OS: Windows 10** 

**What did you do?**
Took this code to calculate prime numbers (compiles and runs fine):
https://pastebin.com/BfpMTCVE

Changed it to this to play around with concurrency (first time testing):
https://pastebin.com/NDKMTJbf

**What did you expect to see?**
It to compile or have a meaningful error.
 
**What did you see instead?**
Full error message.
https://pastebin.com/GcB7z6Z6

```
from type 'array_bool {aka struct array}'
  tmp4 -> list =
               ^
V error: C error. This should never happen.
```

**Comment by changrui** [comment]
`Segmentation fault (core dumped)` on playground.

**Comment by changrui** [comment]
https://devbits.app/play/ADSMV3TNlw0i

**Comment by Ivo-Balbaert** [comment]
The second version with concurrency now ( ) works fine on Windows 10 after the following syntax changes:

mut list := []bool{}
go multiple_thread(i, &list)
fn multiple_thread(i int, mut list []bool) {

For example, for total = 100:
[0, 1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
