### ISSUE TITLE
Using map according to docs/doc.md: tmV error: C error. This should never happen.

### ISSUE THREAD

**Issue by ralvgh** [vlang/v#3538]
**V version:**  0.1.24 5c6032d

**OS:** `Linux 5.4.11_1 #1 SMP PREEMPT  i686 GNU/Linux; voidlinux (glibc)`

**What did you do?** Run the code from docs/doc.md line 309-312 in a fresh repl:

    mut m := map[string]int 
    m['one'] = 1
    m['two'] = 2
    println(m['one']) 

**What did you expect to see?**

    1
 
**What did you see instead?**

    tmV error: C error. This should never happen.
    Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

FWIW: Compiled and ran  `vlib/builtin/map_test.v` without problems.

**Comment by ka-weihe** [comment]
This is a repl bug, not map.

**Comment by alexesprit** [comment]
Works fine on latest V.
