### ISSUE TITLE
split_nth should return rest of string as last element

### ISSUE THREAD

**Issue by kazarmy** [vlang/v#3551]
**V version:**  V 0.1.24 2897bac
**OS:** Linux

**What did you do?**
```
fn main() {
	line := 'CMD=eprintln(phase=1)'
	kv := line.split_nth('=', 2)
	eprintln('kv.len: ${kv.len}')
	eprintln('kv[0]: ${kv[0]}')
	eprintln('kv[1]: ${kv[1]}')
}
```

**What did you expect to see?**
```
kv.len: 2
kv[0]: CMD
kv[1]: eprintln(phase=1)
```

**What did you see instead?**
```
kv.len: 2
kv[0]: CMD
kv[1]: eprintln(phase
```

Actual motivating case is [here](https://github.com/radareorg/radare2/pull/15890#discussion_r370621473).

**Comment by spytheman** [comment]
Would not that make `line.split_nth('=', 1)` return the whole string, i.e. make it meaningless?

**Comment by spytheman** [comment]
What should these return for the above example string?
a) line.split_nth('=', 0)
b) line.split_nth('=', 1)
c) line.split_nth('=', 2)
d) line.split_nth('=', 3)
?

**Comment by spytheman** [comment]
The current behavior seem logical - it always returns N parts of the string, that are separated by the delimiter. Why should it return all of a sudden a part that *contain* the delimiter string?
I do not see the logic in that...

**Comment by kazarmy** [comment]
> Would not that make line.split_nth('=', 1) return the whole string, i.e. make it meaningless?

Yes, as the most simple case.

> What should these return for the above example string?
> a) line.split_nth('=', 0)

`['CMD', 'eprintln(phase', '1)']`

> b) line.split_nth('=', 1)

`['CMD=eprintln(phase=1)']`

> c) line.split_nth('=', 2)

`['CMD', 'eprintln(phase=1)']`

> d) line.split_nth('=', 3)

`['CMD', 'eprintln(phase', '1)']`

> The current behavior seem logical - it always returns N parts of the string, that are separated by the delimiter. Why should it return all of a sudden a part that contain the delimiter string?

For convenience. Current functionality will not be lost -- to obtain the first N parts, use `split_nth(.., N+1)` and take the first N elements.

Perhaps it would be better to propose a new `split_n()` function for this instead.

**Comment by spytheman** [comment]
I have a patched version that for this program:
```v
fn main() {
  line := 'CMD=eprintln(phase=1)'
  println('line:')
  println(line)
  for n in [0,1,2,3] {
    println('i: ${n:3d} | res: ' + line.split_nth('=', n).str() )
  }
}
```
prints:
```
line:
CMD=eprintln(phase=1)
i:   0 | res: ["CMD", "eprintln(phase", "1)"]
i:   1 | res: ["CMD=eprintln(phase=1)"]
i:   2 | res: ["CMD", "eprintln(phase=1)"]
i:   3 | res: ["CMD", "eprintln(phase", "1)"]
```

It would definitely need more tests though, so that we can avoid future regressions. Currently the only tests for split_nth check only the length of the returned array, not the actual values.

**Comment by kazarmy** [comment]
Thanks!
