### ISSUE TITLE
centos6 centos7 can not compile v with vc

### ISSUE THREAD

**Issue by di3663** [vlang/v#356]
```
~/code/v/compiler # ./vc -o v .
Segmentation fault
```

**Comment by vktec** [comment]
Getting the same issue on Solus, gcc version 8.3.1

**Comment by Undumendil** [comment]
Should be fixed now. Update your repos and try again.

**Comment by di3663** [comment]
> Should be fixed now. Update your repos and try again.

Not yet. I will try later. 

ps:
```
test system: clean centos6 / centos7 x64 with devtoolset-8-gcc
```
even gcc4.8 can not compile v.c so I choose devtoolset-8-gcc instead

**Comment by vktec** [comment]
No segfault any more, but I don't get a binary either. `strace` indicates that vc is looking for `/usr/local/Cellar/llvm/8.0.0/bin/clang` which indicates to me it thinks it's running on macOS.

**Comment by di3663** [comment]
works now.
