### ISSUE TITLE
Creating a struct with "C." prefix results in a different struct declaration than without it

### ISSUE THREAD

**Issue by prime31** [vlang/v#3561]
**V version:** V 0.1.24 edc4499
**OS:** linux

**What did you do?**
Attempted to create a struct with and without the "C." prefix.
```
import sokol.gfx

fn main() {
	first := sg_pass_action{}
	second := C.sg_pass_action{}
}
```

**What did you expect to see?**
I expected the program to compile
 
**What did you see instead?**
A C compilation error because the generated C code was not correct:

```
void main__main()
{
    sg_pass_action first = (sg_pass_action){._start_canary = 0, ._end_canary = 0};
    struct /*c struct init*/ sg_pass_action second;
}
```

**Comment by alexesprit** [comment]
It was fixed. C structs w/o a `C` prefix aren't allowed.
