### ISSUE TITLE
Question: potential and ETA for meta?

### ISSUE THREAD

**Issue by Kreyren** [vlang/v#3567]
Referencing https://github.com/RXT0112/Zernit/issues/30 i am currently doing research for programming language for my new project and i would appreciate some info that would help me with a decision.

Currently i am using rustlang for most of my projects where based on my test results it's the most efficient programming language where efficient i consider: 

"""
Programming language that can manage available system resources in relation to time better then the alternative without sacrificing the security with methods to make development easier being preferred.
"""

Could you elaborate on the issues that i've found for vlang in comparison to rustlang?

These issues being:
[removed - tracking in mensioned issue above]

I'm currently having hard time verifying this info and if these issues are valid is there any tracking for them so that i could switch on vlang if it becomes superior to rustlang?

Also can V work on non-root system? i.e https://github.com/gitpod-io/workspace-images/pull/153

Thanks a lot for any info!

**Comment by Uniminin** [comment]
V should work on non-root system

**Comment by Kreyren** [comment]
> V should work on non-root system

but is it sane to run this way in terms of security?

**Comment by medvednikov** [comment]
> V should work on non-root system
It does.

> it's not possible to contribute in their documentation
Not true: https://github.com/vlang/v/blob/master/doc/docs.md

> Still in development 
Well... yeah :)

> Runtime is comparable to C lang or slower 
No, performance is the same.

> Doesn't have working IDE (what about the one mensioned on the website then?)
VSCode and Vim extensions that are linked work well.

> Leaks memory
Yes, this is being worked on right now.

**Comment by Kreyren** [comment]
> No, performance is the same.

Are there any benchmarks that i could get on my system and verify this without the need to write a test programs?

> Yes, this is being worked on right now.

Is there any tracking for this for me to follow until this is resolved?

---

Updated finding in https://github.com/RXT0112/Zernit/issues/30 and removed questions in OP to avoid confusion and false info

---

Are there any other issues that i should know about? I'm currently looking for something more efficient then rustlang.

**Comment by medvednikov** [comment]
There were some benchmarks, in one of them V was actually faster for some reason.

Everywhere else within 3%.

I'll try to find them and add them to the website and to the main repo.

**Comment by Kreyren** [comment]
@medvednikov thanks, ideally i would like to test the performance on my system i.e using https://github.com/kostya/benchmarks so that it's executed all from one reliable environment for monitoring in between releases

**Comment by medvednikov** [comment]
You can, it already has V implementations, although some of them have issues.

The brainfuck one is 3 times slower than the C/Go implementation, there's definitely a bug in the stdlib somewhere.
