### ISSUE TITLE
[flag] doesnt work on public enums

### ISSUE THREAD

**Issue by prime31** [vlang/v#3568]
**V version:** V 0.1.24 71b50ae
**OS:** macos

**What did you do?**
```
[flag]
pub enum WindowFlags {
	fullscreen = 1
	opengl = 2
}
```

**What did you expect to see?**
I expect this to compile.
 
**What did you see instead?**
Compilation error. If the `pub` is removed it works though.

**Comment by joe-conigliaro** [comment]
Thanks for reporting @prime31, this is fixed in #3599
