### ISSUE TITLE
this literally does not work

### ISSUE THREAD

**Issue by flfy** [vlang/v#357]
ive tried compiling the compiler and my own programs, literally doesnt compile. segfault after segfault, completely misleading marketing

**Comment by Hamzantal** [comment]
did u even try to read the readme

**Comment by flfy** [comment]
i sure did!

**Comment by NotNite** [comment]
same

**Comment by BriannaFoxwell** [comment]
Have you tried turning it off and on again?

**Comment by flfy** [comment]
ye thanks for the tips tho i did try, even restarted my whole internet and turned the bedroom power breaker off to make sure the computer turned off completely

**Comment by iwasaki-kenta** [comment]
https://github.com/vlang/v/pull/345/files

**Comment by flfy** [comment]
i am not on a mac

**Comment by Hamzantal** [comment]
are you on linux? try it anyways

**Comment by binkiklou** [comment]
You're not the only one getting thoses problems

**Comment by flfy** [comment]
i already did jesus

**Comment by flfy** [comment]
literally nothing NOTHING will compile

**Comment by Hamzantal** [comment]
do `sudo chmod +rw /var/tmp/vlang0.0.12`

**Comment by Hamzantal** [comment]
did it work?

**Comment by flfy** [comment]
my friend
what do you not get about the statement
"i already did jesus"

**Comment by flfy** [comment]
vaybe vi veed vo vestart vy vomputer vo vun vlang

**Comment by Hamzantal** [comment]
why are you being so cuntish? We're trying to hlep you here.

**Comment by Draycia** [comment]
I'd suggest answering the question of which OS you're running.

I doubt many people will continue to try to help if you're withholding information, ignoring people, and responding in such ways.

**Comment by nico-abram** [comment]
Does not work on windows either

**Comment by medvednikov** [comment]
Should work now with the new vlang.io/v.c

**Comment by flfy** [comment]
> why are you being so cuntish? We're trying to hlep you here.

no need to call me a cunt but ok
