### ISSUE TITLE
plus equal operator evaluates twice the array index

### ISSUE THREAD

**Issue by ilmanzo** [vlang/v#3575]
**V version:** latest in web playground
**OS:** web playground

**What did you do?**
```
fn index() int {
  println("index func")
  return 1
}

fn main() {
	mut counts:=[0,0,0,0,0]
        counts[index()]+=5
        println(counts)
} 
```

**What did you expect to see?**
only one execution of index function, e.g.
```
index func
[0, 5, 0, 0, 0]
``` 
**What did you see instead?**
two executions of index function:
```
index func
index func
[0, 5, 0, 0, 0]
```

**Comment by penguindark** [comment]
`counts[index()]+=5` is unrolled as: `counts[index()] = counts[index()] + 5`
this explain the two calls.

**Comment by medvednikov** [comment]
Will be fixed in the new parser soon.

**Comment by Delta456** [comment]
It is still reproducable with the latest V.

**Comment by Delta456** [comment]
Works with the latest V.
