### ISSUE TITLE
vfmt parsing it as correct, but syntax is invalid and bad code is generated

### ISSUE THREAD

**Issue by radare** [vlang/v#3585]
**V version:** 
**OS:** 

**What did you do?**

```
struct Foo {
        foo [string]string
}

fn main() {}
```

**What did you expect to see?**

Error: missing "map" keyword before [
 
**What did you see instead?**

```
tring ];
                     ^
1 error generated.V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

**Comment by radare** [comment]
To avoid opening more issues ill just mention what happens if theres a .str applied to this struct that isnt properly formatted

```
$ v run f.v
:6:2: unhandled sprintf format "[string]string"
    4| return
    5| '{
    6| 	foo: $a.foo
}'
        ^
    7| }
    8|
$ cat f.v
struct Foo {
	foo [string]string
}

fn main() {
	foo := Foo{}
	println(foo)
}
```

**Comment by radare** [comment]
I wonder if we want to make `map` implicit for such cases

**Comment by alexesprit** [comment]
The new formatter returns a parser error instead:
```
$ v fmt test4.v
test4.v:2:14: error: unexpected `name`, expecting `]`
    1 | struct Foo {
    2 |         foo [string]string
      |              ~~~~~~
    3 | }
    4 |
vfmt error while formatting file: test4.v .
```

**Comment by Ivo-Balbaert** [comment]
The same parser error given by vfmt is also returned when compiling with v or doing v run.
I think this is the appropriate behavior for vfmt, first parsing the code.
Perhaps this issue can be closed now?
