### ISSUE TITLE
Does it work for anyone ? 

### ISSUE THREAD

**Issue by binkiklou** [vlang/v#359]
Hello, I've seen that a lot of people say, trying to compile the V compiler doesn't' work. So I have this question, does it work for anyone? Did anyone manage to get it working yet?

**Comment by zac-garby** [comment]
I kind of got it working. Enough to compile a basic hello world program.

**Comment by Bleser** [comment]
#329

**Comment by cdunn2001** [comment]
Yes, V compiles itself on my Mac (in `~/code/v/`)

**Comment by jrenner** [comment]
works for me on linux

**Comment by lutherwenxu** [comment]
@binkiklou The segfaults most people are reporting has been fixed in 0.1.0. Please close the issue if you've received your answer, it helps clean up the massive amount of issues we're receiving. :)
