### ISSUE TITLE
vweb error

### ISSUE THREAD

**Issue by didik78** [vlang/v#3593]
**V version:**
V 0.1.24 a14a5fb
**OS:** 
macOS Catalina Version 10.15.2

**What did you do?**
module main

import (
    vweb
)

pub struct App {
    mut:
    vweb vweb.Context
}

fn main() {
    vweb.run<App>(8080)
}

fn (app mut App) index() {
    app.vweb.text('Hello, world from v!')
}

pub fn (app &App) init() {}
pub fn (app &App) reset() {}

**What did you expect to see?**
server started at 8080

 
**What did you see instead?**
v % v run main.v
ssl.h>
         ^~~~~~~~~~~~~~~
1 error generated.V error: C error. This should never happen. 
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by changrui** [comment]
install `openssl` first.

**Comment by MichalKalita** [comment]
On Ubuntu I already have `openssl`, I need to install `libssl-dev`
