### ISSUE TITLE
Error recovery

### ISSUE THREAD

**Issue by cthackers** [vlang/v#3601]
Can there be a method to recover from an error ? Not all errors should exit the function (with return)
Perhaps something like:

```
f := os.open('some file') or { 
   recover os.open('some other file') // which assignes f
}

**Comment by joe-conigliaro** [comment]
@cthackers Some other current alternatives are:
```
// 1) use alternative optional syntax
if f2 := os.open('a.txt') {
	// do something with a.txt
}
else {
	if f2 := os.open('b.txt') {
		// do something with b.txt
	} else {
		println('could not open a.txt or b.txt')
	}
}

// 2) provide default value
mut f1 := os.open('a.txt') or {
	os.File{}
}
if !f1.opened {
	f1 = os.open('b.txt') or {
		panic('could not open a.txt or b.txt')
	}
}
```

**Comment by dumblob** [comment]
This confusion/question seems to originate from the (IMHO unfortunate) [dualism](https://github.com/vlang/v/issues/2030 ).

The solutions @joe-conigliaro outlined above should be preferred nearly everywhere and `panic()`s actually rather discouraged.
