### ISSUE TITLE
http not found

### ISSUE THREAD

**Issue by elbashery** [vlang/v#3604]
**V version:** 0.1.24 
**OS: ** Linux

**What did you do?** import http

**What did you expect to see?** ok

 
**What did you see instead?**  http not found

$ ls
CHANGELOG.md  CODE_OF_CONDUCT.md  CONTRIBUTING.md  doc  examples  LICENSE  README.md  thirdparty  tools  tutorials  v  v2.v  vlib  v.win.c
[fedora@localhost ~/.v] 
$ v
V 0.1.24 0d93eeb
Use Ctrl-C or `exit` to exit
>>> import http
cannot import module "http" (not found)
>>>

**Comment by changrui** [comment]
`import net.http`.

**Comment by elbashery** [comment]
thank u so much
