### ISSUE TITLE
optional multiple returns

### ISSUE THREAD

**Issue by radare** [vlang/v#3605]
**V version:** V 0.1.24 ed55778
**OS:** macOS 10.15

**What did you do?**

failing compilation:
```go
 33 fn kv(s string) ?(string, string) {
 34         kw := s.split_nth(':', 2)
 35         if kw.len != 2 {
 36                 return error('invalid token')
 37         }
 38         return kw[0].trim_space(), kw[1].trim_space()
 39 }
```

workaround
```go
 33 fn kv(s string) (string, string) {
 34         kw := s.split_nth(':', 2)
 35         if kw.len != 2 {
 36                 return '', ''
 37         }
 38         return kw[0].trim_space(), kw[1].trim_space()
 39 }
```

**What did you expect to see?**

being able to use optional multiple returns
 
**What did you see instead?**

invalid syntax error with confusing message:

```
v build .
./suite.v:33:24: unexpected token `string`
   31| }
   32|
   33| fn kv(s string) ?(string, string) {
                              ^
   34| 	kw := s.split_nth(':', 2)
   35| 	if kw.len != 2 {
```

**Comment by joe-conigliaro** [comment]
Thanks @radare,
This is a know limitaiton as support for this was never added. 
@medvednikov I think we discussed it a while back, if I remember correctly.
What are your thoughts about this?

**Comment by radare** [comment]
If its a known limitation it will be good to have a meaningful error message instead of a weird syntax one. But i think it should be supported

**Comment by joe-conigliaro** [comment]
@radare I have added optional support for multiple returns, I will push soon

**Comment by radare** [comment]
Thank you
