### ISSUE TITLE
C Error with net.http.get with a simple use case

### ISSUE THREAD

**Issue by real34** [vlang/v#3608]
**V version:** V 0.1.24 80d936a
**OS:** NixOS (gcc: (GCC) 9.2.0)

**What did you do?**
Ran the program below:
```v
module main

import net.http

fn main() {
	response := http.get('https://vlang.io') or {
		panic('ERR')
	}
	println(response.text)
}
```

**What did you expect to see?**
The page response.
 
**What did you see instead?**
The following error:

> |          ^~~~~~~~~~~~~~~
> compilation terminated.V error: C error. This should never happen. 
> Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

I am new to the language, so there may be an obvious error (and this issue could be closed in favor of #3600) but I cannot see what's wrong with the code.
Please let me know if I can provide more information.

**Comment by penguindark** [comment]
please, remove the line "module main" :)

**Comment by real34** [comment]
Thanks for your comment. I tried but it does not change anything.

I also tried the following and got the same error with [examples/links_scraper.v](https://github.com/vlang/v/blob/aa625bc22c7e5c9318081ffacd9f5ae488e20909/examples/links_scraper.v):
```
cd /tmp/ && git clone https://github.com/vlang/v && cd v && make && ./v run examples/links_scraper.v
```

**Comment by real34** [comment]
I found the error after using `run -g` to get further information:

> ./v run -g examples/links_scraper.v                                                                                                                                                                                   /tmp/v
> C compiler=cc
> /tmp/v/examples/links_scraper.v:94:10: fatal error: openssl/ssl.h: No such file or directory

In NixOS I had to run the program from a shell with the corrects OpenSSL environment variables: `nix-shell -p openssl` (see https://nixos.wiki/wiki/FAQ/I_installed_a_library_but_my_compiler_is_not_finding_it._Why%3F for further information).

It then worked like a charm!
