### ISSUE TITLE
Error running `/examples/news_fetcher.v`

### ISSUE THREAD

**Issue by phil-r** [vlang/v#361]
I'm trying to run `~/code/v/examples# v run news_fetcher.v`

Result is: 

```
pass=2 fn=`json__jsencode_string`
panic: json_primitives.v:47
cannot refer to unexported field `str` (type `string`)
exit():
```

**Comment by phil-r** [comment]
Same issue trying to run JSON example from https://vlang.io/play

**Comment by cdunn2001** [comment]
Caused by #369, I think.

**Comment by musou1500** [comment]
following Pull-Requests will fix it.
https://github.com/vlang/v/pull/375
https://github.com/vlang/v/pull/378
