### ISSUE TITLE
Array delete that replaces deleted element with last element and subtracts len by 1

### ISSUE THREAD

**Issue by wanton7** [vlang/v#3611]
Add another array delete that doesn't to need use C.memmov if you don't care about order of items. That replaces deleted element with last element and subtracts len by 1. I seen this used in Go. Maybe named `delete_unordered` or `unordered_delete`?

**Comment by elimisteve** [comment]
But arrays are ordered by definition. What do you mean?

**Comment by wanton7** [comment]
If you don't care about order of elements in array you can delete faster.

**Comment by wanton7** [comment]
Maybe something like `last_swap_delete` would better name. If unordered part of a name it's hard to understand what it does.

**Comment by dumblob** [comment]
This will have limited use, but maybe for sets or similar structures it could be used as backend optimization.

**Comment by wanton7** [comment]
If not this then array needs to have way to set array **len** to less than current length to achieve this without separate method.

**Comment by dumblob** [comment]
>If not this then array needs to have way to set array len to less than current length to achieve this without separate method.

Sounds like an optimization of array shrinking - which is being done automatically behind the scenes. Do you have any specific use cases for manual shrinking (especially inefficiently by just very few or even by just one element)?

**Comment by wanton7** [comment]
Now you can't replace deleted element with last value and shrink array **len** by one. So I can't do delete like I did in Go quite often. I did explain it but I'll explain it again. If you have array with 1000 elements and you want to delete element in position 0. You take element in position 999 and put it to position 0 and shrink array by one. No need to do **memcpy** for 999 elements if you don't care what order elements are in array.

**Comment by dumblob** [comment]
Ok, if it's about porting optimized Go code efficiently, then yes, that's definitely a good use case. Your last example sounds though quite differently than the previous ones. The previous example(s) would lead to >1 noncontiguous pieces of memory which doesn't make sense for array/list/vector (it does make sense for unordered structures like sets).

This last example of yours though just "cuts off" the element from left (or right) which preserving the contiguity of the data. I have to admit it would really surprise me if Go supported noncontiguous arrays - feel free to prove me wrong, maybe I'll learn something new about Go.

I think it does make sense to hold pointer to the beginning of the data in addition to holding the pointer to the allocated buffer itself. The current code doesn't do that:
```v
// array.delete deletes array element at the given index
pub fn (a mut array) delete(i int) {
	if i < 0 || i >= a.len {
		panic('array.delete: index out of range (i == $i, a.len == $a.len)')
	}
	size := a.element_size
	C.memmove(a.data + i * size, a.data + (i + 1) * size, (a.len - i) * size)
	a.len--
}
```
On the other hand, `memmove()` is highly optimized, so unless you're doing very, but very high throughput operations, you're more than good to go with os-level optimizations (`memmove()` internally doesn't move the memory, but just does exactly the above-mentioned optimization if in the same allocated page if page boundary wasn't crossed - so a subsequent `prepend()` operation wouldn't lead to any actual memory move nor reallocation if it again fits the same page). Just do a benchmark yourself to see how surprisingly efficient `memmove()` actually is.

**Comment by medvednikov** [comment]
@wanton7 can you paste the Go code you use for this?

**Comment by wanton7** [comment]
"Delete without preserving order" from https://github.com/golang/go/wiki/SliceTricks

```go
a[i] = a[len(a)-1] 
a = a[:len(a)-1]
```

**Comment by lutherwenxu** [comment]
The equivalent example in V would be to do this:
```
    a[i] = a[a.len-1]
    a = a[..a.len-1]
```
I've placed it in a playground for your convenience: https://devbits.app/play/iJpKETQ9wbGn

**Comment by wanton7** [comment]
Code is not equivalent to Go because in Go slices share capacity or original slice unlike in V. If you try to add 1 new element to `a` in your code V will need to create new array but same code in Go doesn't need to create new array.

**Comment by wanton7** [comment]
Maybe I could have explain it better. In Go slices are actual sliced to array. Basically slice points array with capacity, then slice is offset and length into that existing array. If you extend slice in Go it extends in limits of original array. In V when you slice it slices array and slices it to new array. You can't extend "slices" in V without reallocating.

**Comment by lutherwenxu** [comment]
Sorry. Am I missing something?
https://github.com/vlang/v/tree/9332a83c/vlib/builtin/array.v#L203

**Comment by wanton7** [comment]
Yes your are. `fn (a array) slice(start, _end int)` creates new array with len and capacity set to same. In Go capacity would be to set to end of array not to length of slice.

Check this StackOverflow questions first answer https://stackoverflow.com/questions/46628683/extend-slice-length-on-the-left

Copy & pasted important part here

*But you are allowed to reslice to include that data again after the len up to cap, which is a little odd:*
>// This is beyond the length of b, you can't index those, 
>// but you can access them by reslicing 
>c := b[:5]

**Comment by wanton7** [comment]
Now that https://github.com/vlang/v/commit/a2838ae6f3cb2ea5954ef79ce73802e251c227da added `trim` function for array, it is enough for me. This is can be closed as far as I'm concerned.
