### ISSUE TITLE
import error openssl/ssl.h: No such file or directory

### ISSUE THREAD

**Issue by elbashery** [vlang/v#3614]
**V version:** 0.1.24
**OS:**  linux fedora workstation

**What did you do?** import net.http

**What did you expect to see?** ok

 
**What did you see instead?**  

fatal error: openssl/ssl.h: No such file or directory
  268 | #include <openssl/ssl.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
V error: C error. This should never happen. 
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by memeone** [comment]
Make sure you have openssl installed

**Comment by elbashery** [comment]
> Make sure you have openssl installed

as a program ? yes.
 did you means openssl as a library?

**Comment by memeone** [comment]
Yes excuse me, the library

**Comment by elbashery** [comment]
Package openssl-libs-1:1.1.1d-2.fc31.x86_64    is already installed on my os
I looked for it in the VPM, but I did not find it

**Comment by changrui** [comment]
`sudo apt install -y libssl-dev`.

**Comment by elbashery** [comment]
> `sudo apt install -y libssl-dev`.

every lib with ssl character is alredy installed on my os.  The error still exists

**Comment by elbashery** [comment]
The problem is solved by this line:
dnf install openssl-devel
thank you all
