### ISSUE TITLE
dont know. first attempt .. 

### ISSUE THREAD

**Issue by agraeper** [vlang/v#3623]
**V version:**    ??? git clone 20200201:2000 
**OS:** xubuntu 

**What did you do?** make and cp -r v, vlib, tools to /usr/local/bin 

**What did you expect to see?**
v (without argument/script) -> repl. exit. (looked good so far) 
i tried some examples in script (.v) which use println() but no output (no error) 
now calling v (starting repl) fails: 
  v panic 
  tools/vrepl.v could not be compiled. denied. 
  addr2line: 'v' no such file 

good luck 
 
**What did you see instead?** ( i did not see this line when writing .., sorry. )

**Comment by agraeper** [comment]
sorry. i did not see the scripts got compiled and running them actually prints, what is expected. but repl does not start as mentioned.

**Comment by memeone** [comment]
If you want to run it directly you can do `v run script.v`

**Comment by agraeper** [comment]
thanks. that works.
maybe i have not correctly installed v.
i copied v and vlib to /usr/local/bin. later the directory tools/ too.
when i call v from git-clone-directory, where v was made, the repl works as
before.

Am Sa., 1. Feb. 2020 um 20:45 Uhr schrieb Leah Lundqvist <
notifications@github.com>:

**Comment by memeone** [comment]
Copying the entire V directory to bin seems a bit unnecessary. Just make a symlink to v_install_dir/v or add v_install_dir to $path
