### ISSUE TITLE
2d array assignment sets all rows to set a column instead of one (array.repeat bug)

### ISSUE THREAD

**Issue by sveri** [vlang/v#3628]
**V version:** 
V 0.1.25 05374e1

**OS:** 
Ubuntu / playground

**What did you do?**
    mut dp := [[0].repeat(3)].repeat(3)
    dp[0][1] = 1
    println(dp)

**What did you expect to see?**
[[0, 1, 0], [0, 0, 0], [0, 0, 0]]
 
**What did you see instead?**
[[0, 1, 0], [0, 1, 0], [0, 1, 0]]

**Comment by medvednikov** [comment]
This is a bug with `repeat`.

This works:

```
mut dp := [[0,0,0], [0,0,0], [0,0,0]]
println(dp)
dp[0][1] = 1
println(dp)
```

**Comment by medvednikov** [comment]
Fixed.
