### ISSUE TITLE
time: `parse` and `parse_iso` return different result on invalid time strings

### ISSUE THREAD

**Issue by alexesprit** [vlang/v#3629]
`time.parse_iso` returns an empty `Time` struct, whereas `time.parse` returns current time. I think they both should have the same behavior, but I don't know what we should return for invalid time strings.

As a alternative way, we can make return value optional.

What do you think?

**Comment by spytheman** [comment]
Parsing of anything in general can fail. I think it should return an optional.

**Comment by medvednikov** [comment]
Yes, optionals in case of an error.

**Comment by alexesprit** [comment]
Thanks for comments. I'll make a PR with optional Time as return value for `parse` and `parse_iso`.
