### ISSUE TITLE
REPL - example: https://vlang.io/utc_now

### ISSUE THREAD

**Issue by mantielero** [vlang/v#363]
In the example from https://vlang.io I get nothing:
```
>>> data := http.get('https://vlang.io/utc_now')
>>> data
>>> 
```

Keep on it mate!

**Comment by Cynosphere** [comment]
did you try `println(data)`?

**Comment by mantielero** [comment]
I get:
```
>>> data := http.get('https://vlang.io/utc_now')
>>> println(data)
V panic: "/home/jose//code/v//builtin/array.v" doesnt exist
```

**Comment by diamondburned** [comment]
I'm pretty sure `get` calls the `do` method which is a noop

**Comment by Bowero** [comment]
This works, but imports don't work correctly in REPL. The http import works however:

```go
import http

fn main() {
    data := http.get('https://vlang.io/utc_now')
    println(data)
}
```

**Comment by JohnAZoidberg** [comment]
Then should the example be updated?

**Comment by Bowero** [comment]
Sure, but that's not part of this repository. The function works as intended.
