### ISSUE TITLE
levenshtein_distance returns wrong distances 

### ISSUE THREAD

**Issue by sveri** [vlang/v#3630]
**V version:** 
V 0.1.25 05374e1

**OS:** 
Ubuntu 

**What did you do?**
Added tests:

	println(strings.levenshtein_distance('', ''))
	println(strings.levenshtein_distance('', 'dog'))
	println(strings.levenshtein_distance('cats', ''))
	println(strings.levenshtein_distance('aa', 'aa'))
	println(strings.levenshtein_distance('flomax', 'volmax'))

**What did you expect to see?**
0
3
4
0
3
 
**What did you see instead?**
0
0
4
0
2

**Comment by sveri** [comment]
I wrote some tests:

	fn test_levenshtein_distance() {
		assert strings.levenshtein_distance('', '') == 0
		assert strings.levenshtein_distance('', 'dog') == 3
		assert strings.levenshtein_distance('cats', '') == 4
		assert strings.levenshtein_distance('aa', 'aa') == 0
		// println(strings.levenshtein_distance('aa', 'ab'))
		assert strings.levenshtein_distance('aa', 'ab') == 1
		assert strings.levenshtein_distance('aa', 'adf') == 2
		assert strings.levenshtein_distance('flomax', 'volmax') == 3
	}
That can be used once it's fixed.

I also had a shot at a correct implementation:

	pub fn levenshtein_distance(a, b string) int {
		if(a.len == 0) { return b.len }
			
		if(b.len == 0) { return a.len }

		mut dp := [[0].repeat(b.len + 1)].repeat(a.len + 1)
		for i := 0; i <= a.len; i++ {
			for j:= 0; j <= b.len; j++ {
				if i == 0 {
					println('i0' + i.str())
					dp[i][j] = j
				}
				else if j == 0 {
					println('j0' + j.str())
					dp[i][j] = i
				}
				else {
					dp[i][j] = min_three(dp[i - 1][j - 1] + cost_of_substitution(a[i - 1], b[j - 1]),
					dp[i - 1][j] + 1,
					dp[i][j - 1] + 1)
				}
				println(dp)
			}
		}
			
		// mut f := [0].repeat(b.len + 1)
		// for ca in a {
		// 	mut j := 1
		// 	mut fj1 := f[0]
		// 	f[0]++
		// 	for cb in b {
		// 		mut mn := if f[j] + 1 <= f[j - 1] + 1 { f[j] + 1 } else { f[j - 1] + 1 }
		// 		if cb != ca {
		// 			mn = if mn <= fj1 + 1 { mn } else { fj1 + 1 }
		// 		}
		// 		else {
		// 			mn = if mn <= fj1 { mn } else { fj1 }
		// 		}
		// 		fj1 = f[j]
		// 		f[j] = mn
		// 		j++
		// 	}
		// }
		// return f[f.len - 1]
		// println(dp)
		// println(a.len)
		// println(b.len)
		return dp[a.len][b.len]
	}

	pub fn cost_of_substitution(a, b byte) int {
		if a == b { return 0 }
		return 1
	}

	pub fn min_three(a, b, c int) int {
		if a < b && a < c {
			return a
		}
		if b < c && b < a {
			return b
		}
		return c
	}

But due to #3628 I cannot fix it right now.

**Comment by dumblob** [comment]
In the meantime you can use Dice coefficient (used by *V* compiler btw.) - it yields significantly better results than Levenshtein distance.

**Comment by sveri** [comment]
@dumblob Thanks, actually I don't really need it, I was just looking for a way to contribute.

**Comment by joe-conigliaro** [comment]
@sveri good spot!
I have fixed the issue here #3645 and added some tests
