### ISSUE TITLE
vlang.io/v.c has been updated

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#364]
All those, who couldn't build V, could you please try again?

**Comment by binkiklou** [comment]
yes master medvedikov

**Comment by CryZe** [comment]
nope, still segfaults

**Comment by alkorgun** [comment]
It won't build with GCC anyway.

**Comment by binkiklou** [comment]
I managed to build v.c but couldn't build the V compiler. It threw a segmentation fault.

**Comment by mantielero** [comment]
For me is working, but I already did:
```
$ mkdir -p /var/tmp/vlang0.0.12
```
and unzip all the source code under `~/code/v`.

It works when I do:
```
$ cc v.c -o vc
$ vc
V 0.0.12
Use Ctrl-D to exit
For now you have to use println() to print values, this will be fixed soon

>>> println('Hola')
Hola
>>>
```
The same applies if I do:
```
$ clang v.c -o vclang
```
And I manage to build the compiler with both versions:
```
$ ./vc .
$ ./vclang .
```
Both create the file `compiler` that I just rename to `v`.

**Comment by Cynosphere** [comment]
Couple of MinGW (Windows) specific issues that can be fixed:
`#include <execinfo.h>`: add `#ifdef _linux_` around this include

`v.c:3958:3: error: too many arguments to function 'mkdir'`:
```
#ifdef _linux_
    mkdir(string_cstr(path), 511);
  #else
    mkdir(string_cstr(path));
  #endif
```

`C:\msys64\tmp\ccz5dlgf.o:v.c:(.text+0x7bca): undefined reference to `getline'`: `os__get_line()` needs to be linux specific
`C:\msys64\tmp\ccz5dlgf.o:v.c:(.text+0x810f): undefined reference to `backtrace'` and `C:\msys64\tmp\ccz5dlgf.o:v.c:(.text+0x8141): undefined reference to `backtrace_symbols_fd'`: `os__print_backtrace()` needs to be linux specific

**Comment by medvednikov** [comment]
Yes, there was another issue I fixed, it should really work for everyone.

> Both create the file compiler that I just rename to v.
You can use `v -o file file.v`
