### ISSUE TITLE
Missing include member openssl/ssl.h> when executing : v install ui in Kubuntu 

### ISSUE THREAD

**Issue by sq16** [vlang/v#3641]
This can be solved by executing this command:
```sh
$ sudo apt install libssl-dev
```
This should be mentioned under "Dependencies" on page https://github.com/vlang/ui

**Comment by dhonx** [comment]
This should be reported on [vlang/ui](https://github.com/vlang/ui)

**Comment by medvednikov** [comment]
Will update the readme.
