### ISSUE TITLE
vweb: `@header` is always being rendered

### ISSUE THREAD

**Issue by exastencil** [vlang/v#3642]
**V version:** V 0.1.25 b6a62cf
**OS:** macOS Catalina 10.15.2

**What did you do?**
Created a new vweb project with the following files:

```v
// main.v
module main

import (
	vweb
)

const (
	port = 8092
)

pub struct App {
pub mut:
	vweb vweb.Context
}

fn main() {
	println('Running app on http://localhost:$port')
	vweb.run<App>(port)
}

pub fn (app mut App) init() {
}

pub fn (app mut App) reset() {
}

pub fn (app mut App) index() {
	title := 'Modified Title'
	$vweb.html()
}
```

```html
<!-- header.html -->
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>@title</title>
</head>
```

```html
<!-- index.html -->
<body>
  <h1>Just something to show...</h1>
</body>
</html>
```

**What did you expect to see?**

When hitting `http://localhost:8092` I expect to see the following since `@header` isn't in the template (index.html):

```
<body>
  <h1>Just something to show...</h1>
</body>
</html>
```
 
**What did you see instead?**

Not only is the header included, but interpolation in it occurs such as:

```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Modified Title</title>
</head>
<body>
  <h1>Just something to show...</h1>
</body>
</html>
```

It seems like vweb is always rendering `header.html` if it exists, **regardless of whether** `@header` **is being called** in the template.

**Comment by medvednikov** [comment]
Should be fixed, can you try again?

**Comment by exastencil** [comment]
Yup, that's fixed it.
