### ISSUE TITLE
Cannot find type []f32

### ISSUE THREAD

**Issue by fhornung** [vlang/v#3653]
**V version:**
V 0.1.25 e09447d
 
**OS:** 
linux debian

**What did you do?**
```v
fn pick(ns [][]f64) {
    println(ns.len)

    println(ns[0].len)
}
```

**What did you expect to see?**
```v
that [][]f64 is recognized
```
 
**What did you see instead?**
```v
test.v:5:21: dot(): cannot find type `[]f64`
    3|     println(ns.len)
    4| 
    5|     println(ns[0].len)
                           ^
    6| }
    7|
```            

```
v -cg test.v
C compiler=cc
pass=2 fn=`main__pick`
```
Segmentation fault (core dumped)

**Comment by gslicer** [comment]
the following compiles and runs fine:
```v
x := [[f64(1),2],[f64(3),4]]

pick(x)

fn pick(ns [][]f64) {

println(ns.len)

println(ns[0].len)

}
```

**Comment by fhornung** [comment]
fn pick(ns [][]f32, ms [][]f32) {
  if ns.len != ms[0].len {
     println("test")
  }

  println(ns.len)

  println(ns[0].len)
  println(ms.len)
  println(ms[0].len)
}

fn main() {
  x := [[f32(1),2],[f32(3),4]]
  y := [[f32(5),6],[f32(5),6]]

  pick(x, y)
}

test.v:2:24: dot(): cannot find type `[]f32`
    1| fn pick(ns [][]f32, ms [][]f32) {
    2|   if ns.len != ms[0].len {
                              ^
    3|      println("test")
    4|   }

Tested with the latest build. 
V 0.1.25 479d5d6

**Comment by Ivo-Balbaert** [comment]
The above complete code now works on Windows 10 and Ubuntu 20 and in the Playground, output:

2
2
2
2
