### ISSUE TITLE
Function should be able to "throw" an error even if no value is returned.

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#3656]
Example:
```v
// dosth doesn't return anything
fn dosth() {
    // write sth to database or filesystem which causes an error
    // return / throw error when it happens, otherwise return nothing.
}
```

In this case a good solution could be to have a `void` or `nothing` type.

```v
fn dosth() nothing {
}
// is the same like (but it's against the one-way philosophy)
fn dosth() {
}
// the you can decalre it like this to make it returning an error
fn dosth() ?nothing {
}
```

to support the one-way philosophy omitting the `nothing` type and just put a `?` as the return type without a regular type which indicates that it doesn't return anything but maybe an error.

**Comment by medvednikov** [comment]
Yes, this has been requested a lot. Will be available in the new parser this week :)

**Comment by danieldaeschle** [comment]
I think this is fixed
