### ISSUE TITLE
If a `*Config` struct is passed empty as `{}` all its default values are ignored

### ISSUE THREAD

**Issue by prime31** [vlang/v#3660]
**V version:** 
**OS:** macos

**What did you do?**
```c
pub struct DrawConfig {
pub mut:
	sx f32 = 1.0
	sy f32 = 1.0
	color math.Color = math.Color{}
}

pub fn draw_circle(x, y, radius f32, segments int, config DrawConfig)

// calling code. This fails:
draw_circle(10, 20, 55, 10, {})

// this succeeds:
draw_circle(10, 20, 55, 10, {sx:1})
```
The code above results in an empty DrawConfig struct being received by the `draw_circle` method.

**What did you expect to see?**
I expected to see the default values from the DrawConfig struct present in the `draw_circle` method.
 
**What did you see instead?**
An empty DrawConfig struct

**Comment by changrui** [comment]
draw_circle(10, 20, 55, 10, `DrawConfig`{})?

**Comment by Ivo-Balbaert** [comment]
Working with v 0.1.27 and with a few simple changes to the code:

struct DrawConfig {
pub mut:
	sx f32 = 1.0
	sy f32 = 1.0
}

fn draw_circle(x, y, radius f32, segments int, config DrawConfig) {
    println(config)
}

// calling code. This fails:
draw_circle(10, 20, 55, 10, DrawConfig{})

// this succeeds:
draw_circle(10, 20, 55, 10, {sx:1})

The code compiles and outputs:

DrawConfig {
    sx: 1
    sy: 1
}
DrawConfig {
    sx: 1
    sy: 1
}

So the code no longer fails and the default values are used in both cases.
