### ISSUE TITLE
voidptr default values for pointers only works when the type is in a module

### ISSUE THREAD

**Issue by prime31** [vlang/v#3661]
**V version:** V 0.1.25 1618596
**OS:** macos

**What did you do?**
The following struct declarations are outside of the module and then inside the module:
```c
// outside of the module: This works.
struct Graphics1 {
	batch &graphics.TriangleBatch = &graphics.TriangleBatch(0)
}

// inside the module. This fails.
struct Graphics2 {
	tri_batch &TriangleBatch = &TriangleBatch(0)
}
```

**What did you expect to see?**
I would expect both cases to compile correctly
 
**What did you see instead?**
For the case of the struct being in the same module as its member field:
`expected `via.graphics.TriangleBatch*` but got `void``

**Comment by danieldaeschle** [comment]
Need more info to reproduce it
