### ISSUE TITLE
Support for REPL help and N-D arrays

### ISSUE THREAD

**Issue by espetro** [vlang/v#3664]
Hey there!

I am trying to reproduce [a simple quantum simulator](https://github.com/adamisntdead/QuSimPy) in V, as to both learn the language and possibly try out the concurrency model.

So far, I've had 2 pitfalls that are possibly missing in the docs:

1. There is no command for getting `help` for a function or module: e.g. `help(rand)` to get information about the `rand` module, or `help(rand.next)` to get info. about the `next` method.
3. There is no built-in support for matrices / multidimensional arrays: or at least is not specified in the docs.
    + Do they have a different type?  (e.g. `array_array_f64` for 2D float arrays)
    + Are arithmetic operators supported for nd arrays? If not, can them be overloaded?

Thanks for your time in advance! 😄

**Comment by nedpals** [comment]
@espetro Hi! Sorry for making your issue sitting here with no response for two months. I'm gonna try my best to answer your questions:

1. There is no REPL help function. Instead, you can use the `v doc [module name]` command. Currently, it only outputs function/method signatures so its best to just dive in the `vlib/` instead.

2. As for matrices/multidimensional arrays, they are already supported (`[][]int` for example) but undocumented as of this moment. There are some bugs regarding about it but they will be fixed on a new compiler.

Hopefully I answered all of your questions properly. :))
