### ISSUE TITLE
 V can't compile  the following code on V playground .Displays message that you just found a bug in V language

### ISSUE THREAD

**Issue by sanath-usk** [vlang/v#3670]
**V version:** Version deployed on V playground as on 07-Feb-2020
**OS:** 

**What did you do?**
Ran the following code on V playground(https://vlang.io/play). Got error message 
```v
fn main() {
    name := 'Bob'
    println('Hello, $name !')  /// `$` is used for string interpolation
    println(name.len)

    mut bobby := name +'' // + is used to concatenate strings
    println(bobby) // "Bobby" 
    bobby =''
    println(bobby[1..3]) // "ob" 
    mut s := 'hello '
    s += 'world' // `+=` is used to append to a string
    println(s) // "hello world" 
}
```
**What did you expect to see?**
The program to run successfully
 
**What did you see instead?**
Got  a message with following text :
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.
![v-bug](https://user-images.githubusercontent.com/19380158/74002379-e7bafc00-4994-11ea-9b07-35751764f906.png)

**Comment by dhonx** [comment]
Hi, @sanath-usk I think that because of the `bobby` variable is now an empty string:
```v
    bobby = ''
    println(bobby[..3]) // "ob" 
```
You can remove that to make it works
https://devbits.app/play/g712xz2eLZOU

**Comment by sanath-usk** [comment]
Works well now .when the same code is used throws a more meaningful error V panic: substr(0, 3) out of bounds (len=0) instead of the earlier message that stated: "You just found a bug.V can't compile this program but should."
