### ISSUE TITLE
Find an easy way to operate strings containing non-ascii

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#3671]
Now V supports (storing) strings containing non-ascii, but doing operations on them seems not easy. This is mainly because a non-ascii uses more than one byte, e.g., "你好,世界" use 4*3+1 = 13 bytes. See this example please.

``` V
fn main() {
        s1 := "hello,world"
	s2 := s1[3..] // e.g., we want to drop 3 letters in head. Nice way. 
	println(s2 == "lo,world") // true

	s3 := "你好,世界" // non-ascii string meaning "hello,world"
	s4 := s3[7..] // e.g., we want to keep "world" only (i.e. "世界").  note that "s3[3..]" is wrong.
	println(s4 == "世界") // true
}
```

**Comment by penguindark** [comment]
have you had a look at `ustring` and the `encoding.utf8` functions?

**Comment by SleepyRoy** [comment]
@penguindark Thanks a lot!
