### ISSUE TITLE
Compile error and warnings

### ISSUE THREAD

**Issue by fhornung** [vlang/v#3676]
**V version:** 
V 0.1.25 9d46fb9

**OS:** 
debian

**What did you do?**
struct Dog {}
struct Cat {}

fn (d Dog) speak() string {
	return 'woof'
}

fn (c Cat) speak() string {
	return 'meow'
}

interface Speaker {
	speak() string
}

fn perform(s Speaker) {
	println(s.speak())
}

fn main() {
  dog := Dog{}
  cat := Cat{}
  perform(dog) // "woof"
  perform(cat) // "meow"
}

**What did you expect to see?**
console output:
woof
meow
 
**What did you see instead?**
==================
expected statement before ')' token
 4255 |  ((string (*)())(Speaker_name_table[s._interface_idx][0]))(s._object ) ) ;
      |                        
...
==================
(Use `v -cg` to print the entire error message)

V error: C error.

Please make sure that:
- You have all V dependencies installed.
- You did not declare a C function that was not included. (Try commenting your code that involves C interop)
- You are running the latest version of V. (Try running `v up` and rerunning your command)

If you're confident that all of the above is true, please try running V with the `-cg` option which enables more debugging capabilities.

=== process finished

**Comment by alexesprit** [comment]
Was fixed recently. Now this example produces the expected output:
```
$ vrun test.v
woof
meow
```
