### ISSUE TITLE
os.args not populated correctly when doing `v run myprogram.v -myarg`

### ISSUE THREAD

**Issue by elimisteve** [vlang/v#3679]
In this scenario, '-myarg' is not in `os.args`, even though it should be.

When doing `v build myprogram.v && ./myprogram -myarg`, '-myarg' then _does_ show up in `os.args`.

**Comment by exastencil** [comment]
Out of curiosity, is this one of those things where you have to add `--` before the args, so the build command knows to pass the arguments on, like `v run myprogram.v -- -myarg`? I sometimes need that when installing a dependency and passing args to the installed program instead of the installer.

**Comment by elimisteve** [comment]
Interesting thought but that doesn't appear to work!

**Comment by spytheman** [comment]
This program
```v
import os
fn main(){
    println('os.args: $os.args')
}
```
... produces:
```shell
0[08:18:15]delian@nemesis: /v/nv $ ./v run x.v a b c -myarg
os.args: ["/v/nv/x", "a", "b", "c", "-myarg"]
```

Do you have a small example that reproduces your issue?

**Comment by elimisteve** [comment]
@spytheman Looks like this has been fixed some time in the last month. Closing :+1: .
