### ISSUE TITLE
Failure when `fn main()` is not present

### ISSUE THREAD

**Issue by mantielero** [vlang/v#368]
The [Hello World section](https://vlang.io/docs#hello) states:

> fn main() declaration can be skipped in one file programs. This is useful when writing small programs, "scripts", or just learning the language. For brevity, fn main() will be skipped in this tutorial.

But when I create `ex03.v`:
```v
name := 'Bob'
println(name)
```
and run:
```
$ ./v run ex03.v
name
println

0
pass=1 fn=``
panic: ex03.v:2
Fn "println" wrong arg #1. Expected "string" (s)  but got "void"
exit():  
```

**Comment by medvednikov** [comment]
Fixed
