### ISSUE TITLE
Compiler bug: unnecessary "specify array type: `[]typ` instead of `[]`"

### ISSUE THREAD

**Issue by elimisteve** [vlang/v#3681]
**V version:** V 0.1.25 ea9961a
**OS:** Debian 9.11 x86_64

**What did you do?**

```v
module main

const (
	which_brief = [[0, 1], [2], [0, 1], [], [0, 2]]
)

fn main() {
	for q in which_brief {
		println(q)
	}
}
```

**What did you expect to see?**

```
[0, 1]
[2]
[0, 1]
[]
[0, 2]
```
 
**What did you see instead?**

```
map_bugs4.v:4:40: specify array type: `[]typ` instead of `[]`
    2| 
    3| const (
    4| 	which_brief = [[0, 1], [2], [0, 1], [], [0, 2]]
             	                                ^
    5| )
    6|
```

Note that the `^` points to the array (`[0, 2]`) just after the one it was trying to point to (`[]`).

When I _do_ change `[]` to `[]int` as requested, it says this:

```
warning: map_bugs4.v:4:42: no need to specify the full array type here, use `[]` instead of `[]int`
```

**Comment by Ivo-Balbaert** [comment]
Changing [] to []int{} in the declaration of which_brief makes the code compile and give the expected output in v 0.1.27 on Windows 10 and in the Playground.
An empty array must be typed in V.
