### ISSUE TITLE
Some casting using "as" doesn't work

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#3683]
**V version:** 
playground

**What did you do?**
```V 
fn main() {
	a := 1
	b := a as string 
	println(b)
} 
```

**What did you expect to see?**
1, or an error?
 
**What did you see instead?**
You just found a bug.

**Plus, for the following three syntaxes for type conversion, what's the difference?**
a) Type_B(Type_A_Var), e.g.  `string(a)`
b) Type_A_Var.Type_B( ), e.g. `a.str( )`
c) Type_A_Var as Type_B, e.g. `a as string`

**Comment by alexesprit** [comment]
Duplicate of #3287.

Also `as` casting is removed for basic types (see d66bc24e7fa676ae44452682d6cc6c63578ce1f6), so, probably, both issues should be closed.
