### ISSUE TITLE
Example program in playground not working

### ISSUE THREAD

**Issue by onlinejudge95** [vlang/v#3694]
**V version:** 
**OS:** Chrome(Playground for V)

**What did you do?**
I was trying out certain examples from [here](https://vlang.io/play) with JSON decoding/encoding snippet.

**What did you expect to see?**
I expected the program to compile and encode/decode the example json.
 
**What did you see instead?**
> You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

**Comment by memeone** [comment]
The examples in the playground are out of date. This will be fixed with the new site.

**Comment by dhonx** [comment]
@onlinejudge95 https://devbits.app/x/27/decode-json-in-v
