### ISSUE TITLE
"V can't compile this program" - immutable interface variable

### ISSUE THREAD

**Issue by mverleg** [vlang/v#3714]
Sorry if this isn't a bug. But I couldn't figure out a reason why it wouldn't work, and the website told me to create an issue, so...

**V version:** / **OS:**: online playground

**What did you do?**

    struct Dog { mut: woof_count int }
    struct Cat { mut: meow_count int }
    
    fn (d mut Dog) speak() string {
        d.woof_count++
        return 'woof'
    }
    
    fn new_dog() &Speaker {
        return &Dog { woof_count: 0 }
    }
    
    fn (c mut Cat) speak() string {
        c.meow_count++
        return 'meow' 
    }
    
    fn new_cat() &Speaker {
        return &Cat { meow_count: 0 }
    }
    
    interface Speaker {
        speak() string
    }
    
    fn main() {
        for i in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] {
            a := if i % 3 == 1 {
                new_dog()
            } else {
                new_cat()
            }
            print(a.speak())
        }
    }

**What did you expect to see?**

I guess it should compile. I get a clear error if I make 'a' mutable.

**What did you see instead?**

"You just found a bug. V can't compile this program, but it should. Please create a GitHub issue."

**Comment by alexesprit** [comment]
The example still does not work, but produces the following errors:
```
test2.v:10:12: error: cannot use `Dog` as type `Speaker` in return argument
    8 |
    9 | fn new_dog() &Speaker {
   10 |     return &Dog { woof_count: 0 }
      |            ^
   11 | }
   12 |
test2.v:19:12: error: cannot use `Cat` as type `Speaker` in return argument
   17 |
   18 | fn new_cat() &Speaker {
   19 |     return &Cat { meow_count: 0 }
      |            ^
   20 | }
   21 |
```

**Comment by spytheman** [comment]
Works with latest V 4f986cc, produces:
`woofmeowmeowwoofmeowmeowwoofmeowmeowwoof`
