### ISSUE TITLE
Can we version vlang.io/v.c?

### ISSUE THREAD

**Issue by cglong** [vlang/v#372]
To create reproducible builds (e.g. to submit V to Homebrew), all compile-time dependencies need to be versioned. Would it be possible to change https://vlang.io/v.c to a `HTTP 302 Found` that redirects to a versioned resource (e.g. https://vlang.io/v-0.0.12b.c)?

For reference, this is how https://yarnpkg.com/latest.msi works.

**Comment by LouCle** [comment]
Or instead just provide a nightly build service from the master branch. `v.c` is only used for bootstrapping, and will be deprecated soon/in the future, from my understanding.

**Comment by medvednikov** [comment]
Some people prefer to build the software from source, so it will always be an option.

I'll implement what you suggested @cglong.

**Comment by lutherwenxu** [comment]
It'll be done in https://github.com/vlang/vc in the near future. This issue will be kept open until the repo is actually complete.

**Comment by Bowero** [comment]
It is complete: https://github.com/vlang/vc
