### ISSUE TITLE
question:how to wrap a C function that use variadic argument

### ISSUE THREAD

**Issue by lydiandy** [vlang/v#3720]
in V, we have v variadic argument,like this:

```v
fn add(i int , other ...int) int {
  //some code
}
```

but if we went to wrap a C function that also uses C variadic argument, like this

```v
fn C.xxx(i int, ...) int {}
fn add(i int,i  other...int) int {
     C.xxx(i,other)  //it does not work,because v compile will generate a variadic argument struct
}
```

how to pass the V variadic argument to C variadic argument?

**Comment by joe-conigliaro** [comment]
@lydiandy there is currently no way to do this
