### ISSUE TITLE
Windows: os.home_dir() works incorrectly in some (roaming?) environments

### ISSUE THREAD

**Issue by Puzomor** [vlang/v#3726]
**V version:** Can't build V, pulled latest commit (f00ab07) from master
**OS:** Windows 10

**What did you do?**

- opened up a command prompt
- cloned v repo
- ran `Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat`
- ran `set VFLAGS=-cc msvc`
- ran `make.bat -msvc`

**What did you expect to see?**
No errors
 
**What did you see instead?**
```
Building V
git version 2.11.0.windows.1
Downloading v.c...
Attempting to build v.c  with MSVC...
v_win.c
rebuild from source (twice, in case of C definitions changes)
V panic: mkdir failed for "Z:\.vmodules", because CreateDirectory returned The system cannot find the path specified.

SymFromAddr failure: 487 = Attempt to access invalid address (Verify that you have the .pdb file in the right folder.)
SymFromAddr failure: 487 = Attempt to access invalid address (Verify that you have the .pdb file in the right folder.)
SymFromAddr failure: 487 = Attempt to access invalid address (Verify that you have the .pdb file in the right folder.)
SymFromAddr failure: 487 = Attempt to access invalid address (Verify that you have the .pdb file in the right folder.)
SymFromAddr failure: 487 = Attempt to access invalid address (Verify that you have the .pdb file in the right folder.)
1 : BaseThreadInitThunk         ?? : address= 000000B2543BEF28
0 : RtlUserThreadStart          ?? : address= 000000B2543BEF30
'v3.exe' is not recognized as an internal or external command,
operable program or batch file.
V failed to build itself with error 9009
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error
```

@emily33901

**Comment by vitalyster** [comment]
1) you no need to set environment if you have vs build tools installed, V detects installed vs tools automatically.
2) try prebuilt V from vlang.io and show `import os` and `print(os.home_dir())` output, there should not be `Z:`

**Comment by Puzomor** [comment]
Prebuilt v prints
`print_backtrace_skipping_top_frames is not implemented on this platform for now...`
no matter what I run, except for `v -v` where it prints nothing and `v --help` which works fine.

`os.home_dir()` got me thinking and I went to check my environment variables through command line. Running `set` shows that `HOMEDRIVE` is set to `Z:`. I've contacted my system administrator who will check if this can be disabled for my workstation. I'll post an update as soon as possible.

**Comment by Puzomor** [comment]
Since I'm unable to influence `HOMEDRIVE` and `HOMEPATH`, I was able to build v using these changes (actually I had to apply appropriate changes to `vc` subdirectory as well, and disable deleting and cloning of the `vc` repo in `make.bat`):

```
diff --git a/vlib/os/os.v b/vlib/os/os.v
index ec9d3fbe..1190fbaa 100644
--- a/vlib/os/os.v
+++ b/vlib/os/os.v
@@ -787,15 +787,18 @@ pub fn user_os() string {
 pub fn home_dir() string {
        mut home := os.getenv('HOME')
        $if windows {
-               home = os.getenv('HOMEDRIVE')
+               home = os.getenv('USERPROFILE')
                if home.len == 0 {
-                       home = os.getenv('SYSTEMDRIVE')
-               }
-               mut homepath := os.getenv('HOMEPATH')
-               if homepath.len == 0 {
-                       homepath = '\\Users\\' + os.getenv('USERNAME')
+                       home = os.getenv('HOMEDRIVE')
+                       if home.len == 0 {
+                               home = os.getenv('SYSTEMDRIVE')
+                       }
+                       mut homepath := os.getenv('HOMEPATH')
+                       if homepath.len == 0 {
+                               homepath = '\\Users\\' + os.getenv('USERNAME')
+                       }
+                       home += homepath
                }
-               home += homepath
        }
        home += path_separator
        return home
```

**Comment by Puzomor** [comment]
`os.home_dir()` may not be a problem here. My PC is just set up in a way that "home" directory is claimed to be in `Z:\`. `os.home_dir()` reports this correctly.

Only the question whether or not `%HOMEDRIVE%%HOMEPATH%` is "more correct" for the "home" directory than `%USERPROFILE%` remains, and if those two should be different functions or if they even serve the same purpose.

No matter what the answer to the question is, `vpm` should prefer `%USERPROFILE%` to `%HOMEDRIVE%%HOMEPATH%` when deciding the location of `.vmodules` directory, in my opinion.

I feel like `%USERPROFILE%` is windows equivalent to `$XDG_CONFIG_HOME`, which is the preferable location for `.vmodules` directory. Nobody likes a littered home directory, anyways.
