### ISSUE TITLE
Add support for 32-bit systems

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#3728]
It seems that now V only supports 64-bit systems (?).

**Comment by vitalyster** [comment]
V with C backend supports any architecture which is supported by underlying C compiler, what is your problem exactly?

**Comment by SleepyRoy** [comment]
@vitalyster Actually I'm using 64-bit win10 and V+mingw64 so there's no problem. I'm just "imagining" whether this set works on a 32-bit system.

**Comment by vitalyster** [comment]
mingw64 have both 32 (i686-w64-mingw32-gcc) and 64 (x86_64-w64-mingw32-gcc) C compilers and both are supported by V
