### ISSUE TITLE
[DOCUMENTATION] The functionality of `@` is undocumented

### ISSUE THREAD

**Issue by RealKC** [vlang/v#373]
I was looking at the source code of the stdlib of V, and found `@` used in some places, such as [here](https://github.com/vlang/v/issues/271). However, as far as I could tell, what `@` does is not documented at all.

**Comment by medvednikov** [comment]
It's a temporary hack, it will be removed in a couple of days.

**Comment by medvednikov** [comment]
It was implemented before `C.function` and `C.struct`.

**Comment by lutherwenxu** [comment]
The @ syntax has been removed in commit a401b5e . It's a temporary hack that has been removed.
