### ISSUE TITLE
Compiler bug?

### ISSUE THREAD

**Issue by RNU4** [vlang/v#3732]
**V version:** 
V 0.1.25 8dd905a
**OS:** 
Windows
**What did you do?**
it happens randomly when modifying the file and running it.
The file contains C functions.

The only way to fix it is to rename the file

**What did you expect to see?**
The program running
 
**What did you see instead?**
   
    ==================
    ld returned 1 exit status
    ...
    ==================

    Use `v -cg` to print the entire error message

    V error: C error.

    Please make sure that:
    - You have all V dependencies installed.
    - You did not declare a C function that was not included. (Try commenting your code that involves C interop)
    - You are running the latest version of V. (Try running `v up` and rerunning your command)

    If you're confident that all of the above is true, please try running V with the `-cg` option which enables more debugging capabilities.

**Comment by dhonx** [comment]
You need to declare the C function first.
https://github.com/vlang/v/blob/master/doc/docs.md#calling-c-functions-from-v

**Comment by RNU4** [comment]
> You need to declare the C function first.
> https://github.com/vlang/v/blob/master/doc/docs.md#calling-c-functions-from-v

Yes i know. 
fn C.kbhit() int
fn C.getch() int

But it is something that happens randomly when modifying the file and when you rename
the file from "test1.v" to "test2.v" it works again.
After the bug happens while using the example "test1.v" you can never use the file name again even if it only contains an empty main function.

**Comment by penguindark** [comment]
no user feedback
