### ISSUE TITLE
prebuilt 0.1.24 failed to bootstrap on win10

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#3736]
**V version:** 
prebuilt 0.1.24 (with mingw64)

**OS:** 
win10 1909

**What did you do?**
v -o v cmd/v

**What did you expect to see?**
successful bootstrap
 
**What did you see instead?**
print_backtrace_skipping_top_frames is not implemented on this platform for now...

![image](https://user-images.githubusercontent.com/47302112/74507320-fd9d6380-4f36-11ea-9d3c-40167b085f66.png)

**Comment by alexesprit** [comment]
Where did you downloaded it? Or did you build it by yourself?

I have the 0.1.24 prebuilt binary downloaded from GitHub releases, and I'm able to compile V tagged 0.1.24 with that binary, but not able to compile V from latest master (tested on a a2838ae6f3cb2ea5).

**Comment by SleepyRoy** [comment]
@alexesprit I downloaded it from the Release page. Since it's a prebuilt, I simply set the PATH and then tried to run "v -o v cmd/v" in cmd.

**Comment by SleepyRoy** [comment]
@alexesprit BTW I just tried the latest 0.1.25 ecb0af3. This time there's no prebuilt so I built it by myself with MSVC. Building process (i.e. running make) was successful, but then "v -o v cmd/v" gave a LINK error...

![image](https://user-images.githubusercontent.com/47302112/74707832-e53e8900-5255-11ea-89b5-fab2d0d7a7dc.png)

**Comment by vitalyster** [comment]
@SleepyRoy linker can not overwrite running v.exe, you should output to different file, e.g. `-o v2`.

**Comment by SleepyRoy** [comment]
@vitalyster Thanks! Just tried and it worked. So the lastest 0.1.25 built by myself is able to bootstrap, but prebuilt 0.1.24 couldn't (still the print_backtrace_skipping_top_frames problem).

**Comment by alexesprit** [comment]
> So the lastest 0.1.25 built by myself is able to bootstrap, but prebuilt 0.1.24 couldn't (still the print_backtrace_skipping_top_frames problem).

I think it's due to incomatible changes made after 0.1.24.

**Comment by SleepyRoy** [comment]
@alexesprit So I'll test again when new prebuilt is out. Will close this issue if it works.

**Comment by aurelVZ** [comment]
alexesprit  or SleepyRoy....anyone of you can give me a link to compiled version of V,no mather which version..thanks ...email aurelw.wiz@gmail.com
all best
Or explain how to exactly compile from source ..i use win7_32bit

**Comment by medvednikov** [comment]
@aurelVZ 

```
git clone https://github.com/vlang/v
make.bat
```

**Comment by SleepyRoy** [comment]
@aurelVZ 
As far as I know there're two ways so choose the one you like.
a. Download and directly use prebuilt 0.1.24 binary. Latest is 0.1.26 but an official prebuilt for it hasn't be made and released. https://github.com/vlang/v/releases/download/0.1.24/v_windows.zip
b. Like Alex above said, simply `git clone and make` if you have git installed. By this you can experience the latest (nightly build) V with many newly updated features.
If you really want to experience nightly V but do not have git, read my PR #3781. But please note it's just a personal workaround, not an official solution.

**Comment by aurelVZ** [comment]
Thanks for reply , i download from link 0,1.24 and same problm with my
C gcc compiler on windows ,lot of errors with win api declaration,also
with types.
v.exe is compiled as 64bit ,so cannot be used with 32bit systems.
I understand that V is a young and primary is for Linux but you must
know that most
people in world still use Windows and many of them 32bit too.

2020-04-28 6:24 GMT+02:00, Ruofan XU <notifications@github.com>:

**Comment by aurelVZ** [comment]
I found only one version:

yeah i found it ,it is called joe-conigliaro
github.com/vlang/vc

this one compile with a lot of warnnings..but just with 4 errors...

so this one should be good to fixing this 4 errors and exit with compiled .exe

2020-05-03 9:30 GMT+02:00, ruben Devel <ruben.code@gmail.com>:

**Comment by SleepyRoy** [comment]
@aurelVZ Thanks for reporting these.
About prebuilt V, yeah it's experimental and very young so there must be a lot of bugs. I'm sure things will go better in the next version. I agree a 32-bit prebuilt should be released in the future. I suggest you open an issue about this 32-bit prebuilt request (and select `feature request`) so that more people can discuss about it.
About your experience with `vlang/vc`, now V mainly emits C and that's exactly the emitted C code. It should be compiled by a C compiler without any errors (and that's exactly what's happening on my 64-bit Windows). So I think it may also due to the 32-bit platform. I also suggest you open an issue about this (and select `bug report`) so that members and other contributors may try reproducing and fixing it.

**Comment by SleepyRoy** [comment]
Update:
I noticed that 0.1.27 prebuilt was recently released so just tried its bootstrap (still, on win10).
Although there're lots of improvement, unfortunately bootstrap still failed.

Try1:
`v self`
Result1:
```
V self compiling ...
cannot compile to C:\VLANG's PATH
No input .v files
```
  
Try2:
`v -o v2 cmd/v`
Result2:
`No input .v files`

**Comment by alexesprit** [comment]
There're no files to build in `cmd\v` in prebuilt zipballs.

**Comment by SleepyRoy** [comment]
@alexesprit Thanks. Then is there's a way to prove prebuilt can bootstrap?

**Comment by alexesprit** [comment]
@SleepyRoy the only way I see is to copy files from the `cmd/v` directory to the directory where prebuilt V was extracted. In this case make sure you copy the `cmd/v` directory from the same repository tree (e.g. from `0.1.27` tag in this case).

I don't know why you need to "prove" we can bootstrap. If you want just to *test* if this is possible, then it's redundant, as it's already tested on each commit.

**Comment by SleepyRoy** [comment]
@alexesprit Thanks, just added `v.v` from source and bootstrap worked for both 64-bit and 32-bit prebuilt 0.1.27. 
The previous prebuilt 0.1.24 is strangely different from built 0.1.24  (e.g. prebuilt couldn't bootstrap whereas built one could.) So I want to use bootstrap as an example to see whether such differences still exist.

**Comment by SleepyRoy** [comment]
Solved. Close this.
