### ISSUE TITLE
what does whitespace mean for v?

### ISSUE THREAD

**Issue by bokunodev** [vlang/v#3738]
**V: 0.1.25** 
**OS: linux** 

**What did you do?**
run this code
```
struct Point {x int y int}
fn main(){
//    a := '12345678910'
//    b := [1,2,3,4,5,6,7,8,9,0]
    p := Point{x:10 y:20}
    println(
    p           
    .
    x)}
```
**What did you expect to see?**
error
 
**What did you see instead?**
10 printed on the screen

**Comment by alexesprit** [comment]
Is it an issue? Other languages have the same behavior.

**Comment by bokunodev** [comment]
actually no, it should be a question and not a bug.
so can I write everything in one line of code?

**Comment by alexesprit** [comment]
Yes, you can write code in one line as long as it is syntactically correct.
