### ISSUE TITLE
Noticeable delays on V commands observed on win10

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#3739]
**V version:** 
prebuilt 0.1.24 (with mingw64)

**OS:** 
win10 1909

**What did you do?**
compile hello_world and test REPL 

**What did you expect to see?**
very fast response to easy operations (immediate compilation of hello_world.v, immediate showing of results after entering a number in REPL)
 
**What did you see instead?**
All worked, but noticeable delays were observed (~1 sec for each command). I don't know whether this is a bug or designed on purpose.

**Comment by vitalyster** [comment]
you can try `v test-compiler` to see timings and compare with different C compilers. For example V built with Visual Studio works much faster. Speeding up mingw compiler is out of scope for V project

**Comment by SleepyRoy** [comment]
@vitalyster Thanks. I'm not sure whether the delay stems from mingw or V itself, but I do think such delays are strange. For example, on my computer, after simply entering a number 1 in V REPL, it takes ~1 sec to see the result (1), which I think is too slow for a REPL. So, the point is, is such length of delay normal (for most computers) and in expectation?

**Comment by vitalyster** [comment]
V call C compiler when you entering number in REPL and compile current line. It is expected to see ~1-2 seconds for mingw and ~0.3-0.4 seconds for msvc.

**Comment by SleepyRoy** [comment]
@vitalyster I see. Thanks for telling the rationale behind REPL.
