### ISSUE TITLE
Trailling comma gives syntax error when declaring a map

### ISSUE THREAD

**Issue by thiagojobson** [vlang/v#3741]
**V version:**  I used the v playground.

**What did you do?**
There is an example in the `Map` docs with the following code. I tried to run it, but got a syntax error. It works when removing the last comma. Is this intended?

```v
fn main() { 
    numbers := {
	'one': 1,
	'two': 2, // <-- remove this comma to compile
    }
    println(numbers.keys())
}
```

**What did you expect to see?**
```
["one", "two"]
```
 
**What did you see instead?**
```
syntax error: unexpected `}`, expecting `STR`
    4| 	'two': 2, 
```

**Comment by bokunodev** [comment]
You don't even need to use any commas
```
fn main() { 
    numbers := {
	'one': 1
	'two': 2
    }
    println(numbers.keys())
}
```

**Comment by thiagojobson** [comment]
Oh nice, I didn't know that.

**Comment by nedpals** [comment]
@medvednikov  will vfmt cover this situation?

**Comment by alexesprit** [comment]
Works fine on latest V; vfmt removes all commas, as they aren't required.
