### ISSUE TITLE
Methods on user-defined (non struct) types not working, except `str()` method

### ISSUE THREAD

**Issue by hachi8833** [vlang/v#3742]
**V version:** : V 0.1.25 c2c6260
**OS:** macOS Catalina

**What did you do?**

```v
module main

type integer i64
type float f64

fn (i integer) name() {
  println("Integer: $i")
}

fn (f float) name() {
  println("Float: $f")
}

fn main() {
  i := integer(42)
  i.name()          //=> type `integer` has no field or method `name`
  f := float(3.14)
  f.name()
}
```

**What did you expect to see?**

```
Integer:  42
Float:  3.14
```
 
**What did you see instead?**

```
ducker.v:16:8: type `integer` has no field or method `name`
   14| fn main() {
   15|   i := integer(42)  //=> type `integer` has no field or method `name`
   16|   i.name()
              ^
   17|   f := float(3.14)
   18|   f.name()
```

FYI: the equivalent Go code works:

```go
package main

import (
  "fmt"
)

type integer int64
type float float64

func (i integer) name() {
  fmt.Println("Integer: ", i)
}

func (f float) name() {
  fmt.Println("Float: ", f)
}

func main() {
  i := integer(42)
  i.name()
  f := float(3.14)
  f.name()
}
```

> Well, you cannot create methods on builtin types such as `int` even in Go.

-----------

As far as I see, only `str()` method can be added to user-defined types:

```v
// works
module main

type integer i64

pub fn (i integer) str() {
  println("Integer: $i")
}

fn main() {
  i := integer(42)
  i.str()
}
```
or

```v
// works
module main

type integer i64

pub fn (i integer) str() string {
  return "${int(i)}"
}

fn main() {
  i := integer(42)
  println(i)
}
```

In the case, you have to specify `pub` and return `string` as you define `str()` for structs.

-----------

I guess that creating methods in V is implicitly assumed only on `struct`. In other words, user-defined types cannot be used as a receiver of methods.

I think it's a bug, but wonder if this might be an intentional behavior.

**Comment by joe-conigliaro** [comment]
@hachi8833 type alias's were never fully implemented. They will be in the new compiler which should be ready soon

**Comment by hachi8833** [comment]
Thank you!

**Comment by Ivo-Balbaert** [comment]
The code now (V 0.1.27 2eac2a5 ) almost works as expected:

type Integer i64
type Float f64

fn (i Integer) name() {
  println("Integer: $i")
}

fn (f Float) name() {
  println("Float: $f")
}

fn main() {
  i := Integer(42)
  i.name()          // => Integer: 42
  f := Float(3.14)
  f.name()          // => Float: 1374389535
}

The only strange thing is the output of Float(3.14)

**Comment by Ivo-Balbaert** [comment]
The strange output of Float(3.14) is resolved when a str() method is defined for the Float type:

type Integer i64
type Float f64

fn (i Integer) name() {
  println("Integer: $i")
}

fn (f Float) name() {
  println("Float: $f")
}

fn (i Integer) str() string {
  return "${int(i)}"
}

fn (f Float) str() string {
   return "${f64(f)}"
}

fn main() {
  i := Integer(42)
  i.name()          // => Integer: 42
  println(i)        // => 42
  f := Float(3.14)
  f.name()          // => Float: 3.14
  println(f)        // => 3.14
}

This works on Windows 10 and the Playground.
