### ISSUE TITLE
freebsd 12.1 , clang9.0 , v compiles but does not seems to work

### ISSUE THREAD

**Issue by devosalain** [vlang/v#3743]
**V version:**  
V 0.1.25 c2c6260
**OS:** 
 FreeBSD 12.1-RELEASE-p1
**What did you do?**
compile v , with clang9.0 no error
compile v with v , no error
1) Start v --->
No prompt but error :
V panic: V tool "/usr/home/x/vlang/v/cmd/tools/vrepl.v" could not be compiled
cmd/tools/vrepl.v:100:32: type `readline.Readline` has no field or method `read_line`
   98| 			prompt = '... '
   99| 		}
  100| 		mut line := readline.read_line(prompt) or {
             		                       ^
  101| 			break
  102| 		}

2) Running hello world with prints nothing on the screen

**Comment by medvednikov** [comment]
Fixed.
