### ISSUE TITLE
V panic: Read-only file system

### ISSUE THREAD

**Issue by hemantasapkota** [vlang/v#3745]
**V version:** 0.1.24 0d93eeb
**OS:**  Amazon Linux AMI

**What did you do?**
```v run /tmp/hello.v```

**What did you expect to see?**
Successful compilation and execution of the source file.

 
**What did you see instead?**
```
V panic: Read-only file system
| 0x55e01903c48c | /opt/bin/v(+0x248c) 
| 0x7fae766d0575 | /lib64/libc.so.6(__libc_start_main+0xf5) 
| 0x55e01903c54a | /opt/bin/v(+0x254a)
```

**Comment by changrui** [comment]
Why put your program to `/tmp` directory? ` run ./hello.v` will be OK?

**Comment by hemantasapkota** [comment]
@changrui Why does it panic when running from /tmp directory? Are there any workarounds?

**Comment by bokunodev** [comment]
@hemantasapkota
 I cannot reproduce the same error.
Where is your V executable located?

**Comment by hemantasapkota** [comment]
@bokunodev /opt/bin . thirdparty, tools and vlib are also installed there.

**Comment by bokunodev** [comment]
@hemantasapkota 
put V in a writable directory.
somewhere under the $HOME directory.
then add the directory to the $PATH environment variable
or just symlink the v executable to /opt/bin

**Comment by hemantasapkota** [comment]
@bokunodev ok will try that.
