### ISSUE TITLE
Cannot define some non-ascii strings in REPL 

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#3749]
**V version:** 
prebuilt 0.1.24 (with MSVC)

**OS:** 
win10

**What did you do?**
(In REPL)
``` V
a := "哈" // a Chinese character meaning haha, LOL, etc.
a
b := "哈哈"
b
c := "哈哈哈" 
c
d := "哈哈哈哈"
e
e := "哈哈哈哈哈"
e
```

**What did you expect to see?**
successfully define and print all strings
 
**What did you see instead?**
Interestingly, only strings with **even** number of characters are defined and printed (see below)

![image](https://user-images.githubusercontent.com/47302112/74600469-28212500-50cd-11ea-96d5-adecd75681b1.png)

**Comment by changrui** [comment]
`invalid character ``

**Comment by vitalyster** [comment]
Can not reproduce this issue.
I'm using copy/paste that character into terminal without issues. Does it work for you?
Will try to add Chinese keyboard layout to test

**Comment by vitalyster** [comment]
Let me know how to enter this character with Microsoft Pinyin keyboard

**Comment by vitalyster** [comment]
Successfully entered "ha", "haha", "hahaha" with Pinyin keyboard and it was converted to series of 哈 and it works in V strings. Let me know if you are using some different keyboard input method (third-party maybe?)

**Comment by SleepyRoy** [comment]
@vitalyster Clever! You can type 哈 through entering "ha".
Strange, I tested all strings exactly through the official Microsoft Pinyin keyboard. 

BTW I justed built the latest 0.1.25 ecb0af3 and had the same tests. This time I still got the error but nicely with some feedback, though unfortunately I don't know why such feedback couldn't be correctly printed on my screen. 

Conclusion:
1. There're still some functional problems in prebuilt 0.1.24, for example it couldn't give the error feedback. Latest 0.1.25 seems functionally OK, but with some encoding problems (?), otherwise the error feedback should be correctly printed.
2. This bug is not limited to 哈. Strangely, some Chinese strings, e.g. 一二三 meaning "one, two, three" entered through "yi" "er" "san", doesn't give this bug. However, 你好啊 meaning "hello, there" entered through "ni" "hao" "a"  gives this bug. I guess this bug stems from some encoding problems.

![image](https://user-images.githubusercontent.com/47302112/74709688-c1ca0d00-525a-11ea-9ef6-5b5358109401.png)

**Comment by SleepyRoy** [comment]
@vitalyster BTW I just tried 0.1.24 built by myself. Unlike prebuilt version, at least it could give error feedback. This indicates prebuilt losts some function.

**Comment by vitalyster** [comment]
@SleepyRoy do you use cmd.exe or some third-party terminal? I pretty sure something different in our setups

**Comment by SleepyRoy** [comment]
@vitalyster I used cmd. The only difference might be I'm using a Chinese-lang version windows? I guess you're using the English version.

**Comment by spytheman** [comment]
@SleepyRoy , not sure if it is related, but the prebuilt versions are built with mingw64, and you are using MSVC by the look of the screenshot.

**Comment by SleepyRoy** [comment]
@spytheman Maybe that's the case for prebuilt, but the latest master built by MSVC also gives this bug.

**Comment by SleepyRoy** [comment]
So I'll wait to see if there's any one able to reproduce this issue. If not in several days, I'll close it.

**Comment by SleepyRoy** [comment]
Seem that no one reproduced it so close this issue
