### ISSUE TITLE
Large numbers are not well handled in REPL

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#3751]
**V version:** 
prebuilt 0.1.24 (with MSVC)

**OS:** 
win10

**What did you do?**
(In REPL)
``` V
a := 123456789123456789123456789
a
```

**What did you expect to see?**
Maybe, one way is, the number is truncated and saved in an int variable, giving an overflow warning.
(Having supports for large numbers is much better. I believe scientific computing really needs them.)

**What did you see instead?**
undefined: `a`

What's more, on playground the same code gives 17502027875430457109. I think this is the truncated result (i.e. 123456789123456789123456789 & 0xffffffffffffffff)

**Comment by serkonda7** [comment]
In V 0.1.29 4774c89 this number is still too large (for i64), but for normal int you get an overflow error:
```
error: overflow in implicit type `int`, use explicit type casting instead
    5 | import math
    6 | 
    7 | a := 123456789123456789123456789
      |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Casting to `i64`:
```v
>>> a := i64(123456789123456789123456789)
>>> a
-944716198279094507
```

**Comment by medvednikov** [comment]
Fixed. You get an overflow error now.
