### ISSUE TITLE
Question: How to use msvc and MinGW depending on the situation?

### ISSUE THREAD

**Issue by keito940** [vlang/v#3757]
In my environment, there are binaries that only work with MSVC and binaries that do not work with MinGW.

**Comment by vitalyster** [comment]
use `--cc msvc` or `--cc gcc`?

**Comment by didik78** [comment]
PS C:\Users\dik\Documents\v\lat> v version
PS C:\Users\dik\Documents\v\lat> v up
Updating V...
fatal: not a git repository (or any of the parent directories): .git
V panic: exec failed (CreateProcess): The system cannot find the file specified.

TODO: print_backtrace_skipping_top_frames_mingw(2)
print_backtrace_skipping_top_frames is not implemented on this platform for now...

**Comment by vitalyster** [comment]
@didik78 it looks like you did not have git installed, `v up` uses git to update. Please create separate issue next time
