### ISSUE TITLE
the variadic argument method report an error 

### ISSUE THREAD

**Issue by lydiandy** [vlang/v#3766]
**V version:** 
V 0.1.25 ed01ab7
**OS:** 
Host OS: MacOS
Target OS: MacOS

**What did you do?**
here is the example code:

module main

struct Point {
	a int
}

fn (p &Point) add(key string, vals ...string) {
	println(key)
	for v in vals {
		println(v)
	}
}
fn main() {
	x:=Point{a:1}
	x.add('mylist','a','b','c')
}

**What did you expect to see?**
It should be compiled
 
**What did you see instead?**
reports an error:
/private/var/folders/lk/k709921d2gl4jrh31mt8_ktm0000gn/T/v/test.tmp.c:4304:43: error: invalid operands to binary expression ('string' (aka 'struct string') and 'varg_string' (aka 'struct varg_string'))
 Point_add (& /* ? */ x ,  tos3("mylist") &(varg_string){.len=3,.args={ tos3("a"), tos3("b"), tos3("c")}} ) ;
                           ~~~~ ^~~~~~~~~~~~~
2 warnings and 1 error generated.

**Comment by lydiandy** [comment]
I check the C code,It lost a comma : tos3("mylist") &(varg_string)

**Comment by joe-conigliaro** [comment]
there is many bugs with current variadic implementation that are not getting fixed, they will be fixed in the new compiler

**Comment by lydiandy** [comment]
ok

**Comment by joe-conigliaro** [comment]
this bug is little and easy to fix, but I meant it has much bigger problems also

**Comment by medvednikov2** [comment]
Fixed.

**Comment by medvednikov** [comment]
Fixed.
