### ISSUE TITLE
Declare variables in one file program with main skipped

### ISSUE THREAD

**Issue by MrHate** [vlang/v#3778]
**V version:**  V 0.1.25 f91bded
**OS:**  macOS Catalina 10.15.2

**What did you do?**
Just try to declare variables in a one-file program without `fn main`:
```
a := 1
b := 2
c := a + b

println(a)
println(c)
```

**What did you expect to see?**
Maybe a compilation error, or something else.
I try this just because official documentation doesn't mention it.
 
**What did you see instead?**
```
onefile.v:5:7: operator + not defined on `void`
    3| c := a + b
    4|
    5| println(a)
             ^
    6| println(c)
```
------------

- First, here we've got a error from compiler's output for wrong locating.
- Second, when I just declare the first two lines, compilation does succeed. After the following 4 lines appended, I saw what we got here.

It's confusing that such a simple behavior not being mentioned in official documentation.
So according to vlang's design, what should this be?

**Comment by Ivo-Balbaert** [comment]
This now (V 0.1.27 2eac2a5) works correctly on Windows 10, Playground and Ubuntu 20:

a := 1
b := 2
c := a + b

println(a)  //  =>1
println(c)  //  => 3
