### ISSUE TITLE
JSON example from the web playground fails

### ISSUE THREAD

**Issue by mike239x** [vlang/v#3780]
**V version:** 
The one from the [website playground](https://vlang.io/play) (tested on 19th Feb 2020)
**OS:**  
Ubuntu 18.04 (but I assume it is runs remotely so my OS shouldn't matter much here)

**What did you do?** 
Try the examples one by one. The one named "JSON decoding/encoding" failed.

**What did you expect to see?** 
Some normal output.

**What did you see instead?** 
"You just found a bug. V can't compile this program, but it should. Please create a GitHub issue."

**Comments**
Just in case I also fetch latest version of v lang from master to test if it would fail locally, but on my PC this example works, so it is something about the web version.

**Comment by alexesprit** [comment]
Closed as a duplicate of #3327.
