### ISSUE TITLE
Recursive generic functions do not work

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#3782]
**V version:** 
latest master (built by MSVC)

**OS:** 
win10 1909

**What did you do?**
compile the following code
```V
fn func<T>(n int) {
    if n==0 {return}
    println('called')
    func<T>(n-1)
}

fn main() {
    func<int>(5)
}
```

**What did you expect to see?**
successful compilation
 
**What did you see instead?**
next token = `eof`
V panic: array.get: index out of range (i == -1, a.len == 0)
SymFromAddr failure: 487 = Attempt to access invalid address (Verify that you have the .pdb file in the right folder)
...
... (a lot of same lines as above)
...
SymFromAddr failure: 487 = Attempt to access invalid address (Verify that you have the .pdb file in the right folder)
1 : BaseThreadInitTrunk    ?? : address = 000000D17D1AEA10
0 : RtlUserThreadStart       ?? : address = 000000D17D1AEA18

**Clue: By removing either the recursive part or the generics part this bug disappears (see code below).** 
```V
// generics removed - no bug
fn func(n int) {
    if n==0 {return}
    println('called')
    func(n-1)
}

fn main() {
    func(5)
}
```
``` V
// recursive removed - no bug
fn func<T>(n int) {
    if n==0 {return}
    println('called')
}

fn main() {
    func<int>(5)
}
```

**Comment by SleepyRoy** [comment]
And I just tested all code on playground, the first piece gave
`Warning: 'v' is a directory`
`addr2line: Warning: 'v' is a directory`
The second and third (i.e. generic removed/recursive removed) gave correct results.

**Comment by SleepyRoy** [comment]
Interestingly this works
```V
fn func<T>(n int) {
    if n==0 {return}
    println('called')
    func<int>(n-1)  // (difference is here : T->int)
}

fn main() {
    func<int>(5)
}
```
So I guess the problem is that current generics implementation doesn't process type for recursive calling.

**Comment by SleepyRoy** [comment]
My fault. Should be written like this
```V
fn func<T>(n int) {
    if n==0 {return}
    println('called')
    func<T>(n-1) 
}

fn main() {
    func<T>(5)
}
```

**Comment by medvednikov** [comment]
No, you found a bug, this should remain open till it's fixed.

This should work:

```
fn func<T>(n int) {
    if n==0 {return}
    println('called')
    func<T>(n-1) 
}

fn main() {
    func<int>(5)
}
```

**Comment by SleepyRoy** [comment]
@medvednikov Thanks for explanation. Actually I did more experiments and re-confirmed this bug. Let me record it here to help future fixing.
As I said, I closed this issue because I (wrongly) assumed `func<T>(5)` was right instead of `func<int>(5)`. However, I found code below didn't work no matter which style I used.
```V
fn func<T>(arr []T, n int) {
    if n==0 {return}
    a := arr[n]  // should give a warning, but still able to compile
    func<T>(arr, n-1) 
}

fn main() {
    func<T>([0,1,2,3,4], 4) // func<T> and func<int> both failed
}
```
The point is exactly the ` a := arr[n]` (array accessing syntax). Without it, style `func<int>` fails, but `func<T>` is OK.

**Comment by SleepyRoy** [comment]
Just tested latest V and it's fixed.

**Comment by Jonatino** [comment]
I'm trying this in V 0.1.29 995a5fe and it's not working for me.

```
fn parse_json<T>(file string, mut array []T)  {
	data := os.read_file(file) or {
		panic('error reading file $file')
		return
	}
	decoded_data := json.decode([]T, data) or {
		eprintln('Failed to parse item spawns')
		return
	}
	for d in decoded_data {
		array << d
	}
}

fn walk<T>(path string, mut array []T) {
	if !os.is_dir(path) {
		return
	}
	files := os.ls(path) or {
		return
	}
	for file in files {
		p := path + os.path_separator + file
		if os.is_dir(p) && !os.is_link(p) {
			walk<T>(p, mut array)
		}
		else if os.exists(p) {
			parse_json<T>(p, mut array)
		}
	}
}
```

**Comment by Jonatino** [comment]
Tried the above in V 0.1.29 9b0ef78 and it still doesnt work.

```
PS E:\Sync\Insignia\game-api> v run gameapi.v
V panic: array.get: index out of range (i == 0, a.len == 0)
print_backtrace_skipping_top_frames is not implemented
```

**Comment by Jonatino** [comment]
Created a new issue #6222
