### ISSUE TITLE
ui.IWidgeter, UI Segmentation fault 

### ISSUE THREAD

**Issue by gshields** [vlang/v#3784]
v version
V 0.1.25 e30bd04
windows 10 v1909
gcc --version
gcc (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0

.vmodules\ui\examples>v -cg  users.v
C compiler=
warning: E:\p-tools\v\vlib\os\os.v:689:15: you are calling an unsafe function outside of an unsafe block
warning: E:\p-tools\v\vlib\os\os_windows.v:211:26: you are calling an unsafe function outside of an unsafe block
warning: E:\p-tools\v\vlib\glm\glm.v:280:26: you are calling an unsafe function outside of an unsafe block
warning: users.v:51:2: reference field `App*.window` must be initialized
warning: users.v:145:5: reference field `ui.PictureConfig.ref` must be initialized

C:\Users\ghs\.vmodules\ui\examples>users.exe
create window wnd=00000000007BC270 ptr==0000000000000000
Trying to load font from C:\Windows\Fonts\arial.ttf

Screen appears and then crashed, I checked c:\windows\fonts and arial is installed

**Comment by didik78** [comment]
Building V
git version 2.25.1.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Now using V to build V...
warning: vlib\os\os.v:689:15: you are calling an unsafe function outside of an unsafe block
warning: vlib\os\os_windows.v:211:26: you are calling an unsafe function outside of an unsafe block
warning: vlib\compiler\msvc.v:44:27: you are calling an unsafe function outside of an unsafe block
warning: vlib\os\os.v:689:15: you are calling an unsafe function outside of an unsafe block
warning: vlib\os\os_windows.v:211:26: you are calling an unsafe function outside of an unsafe block
warning: vlib\compiler\msvc.v:44:27: you are calling an unsafe function outside of an unsafe block
V build OK!
V 0.1.25 296e736

**Comment by yuyi98** [comment]
It's not cause of the font.
```
import ui

struct App {
mut:
	window  &ui.Window
}

fn main() {
	mut app := &App{}

	window := ui.window({
		width: 650
		height: 450
		title: 'test'
		user_ptr: app
	}, [])
	app.window = &window

	ui.run(window)
}
```

Above program can work, but it's only a window.

**Comment by gshields** [comment]
I tried some other examples it looks to be a Segmentation fault with in the UI.
Message.v works (just the hello program) here is a list of some that are failing:
$ v users.v
warning: users.v:51:2: reference field `App*.window` must be initialized
warning: users.v:145:5: reference field `ui.PictureConfig.ref` must be initialized

$ ./users.exe
create window wnd=00000000034DEBD0 ptr==0000000000000000
Trying to load font from C:\Windows\Fonts\arial.ttf
Segmentation fault

$ ./slider.exe
create window wnd=000000000067BA80 ptr==0000000000000000
Trying to load font from C:\Windows\Fonts\arial.ttf
Segmentation fault

$ ./timer.exe
create window wnd=0000000000682970 ptr==0000000000000000
Trying to load font from C:\Windows\Fonts\arial.ttf
Segmentation fault

$ ./calculator.exe
create window wnd=00000000033AC300 ptr==0000000000000000
Trying to load font from C:\Windows\Fonts\arial.ttf
Segmentation fault

 v -cg switch.v
C compiler=
warning: switch.v:14:18: reference field `App*.window` must be initialized

 ./switch.exe
create window wnd=00000000025FB200 ptr==0000000000000000
Trying to load font from C:\Windows\Fonts\arial.ttf
Segmentation fault

**Comment by yuyi98** [comment]
I think the problem is in vlang's `interface`, it can not work correctly.

**Comment by medvednikov** [comment]
Fixed.
