### ISSUE TITLE
Some wrong definitions are not well handled

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#3823]
**V version:** 
latest master (MSVC)

**OS:** 
win10 1909

**What did you do?**
run **any line** of these in REPL (or compile)
```V
a := 0xfff@
b := 100@
c := ..
d := 1..
e := 2 3
f := f
```

**What did you expect to see?**
All these are wrong definitions so each should give an error
 
**What did you see instead?**
They give different results, but none is satisfactory - 
`0xfff@`, `100@`: V panic, substr out of bounds
`..`, `1..`: V panic, string index out of range
`2 3`: wrongly read as `2`
`f := f`: f is wrongly defined as a voidptr

**Comment by SleepyRoy** [comment]
Update: Just tested latest v2. All cases except for `e := 2 3` have been fixed. Will close this issue when all fixed.

**Comment by Ivo-Balbaert** [comment]
Verified for v 0.1.27, only e := 2 3 remains; this assigns the value 2 to e, without giving a warning or error.

**Comment by SleepyRoy** [comment]
Close this issue as the remaining unfixed bug `e := 2 3` is just a special case in issue #5056.
