### ISSUE TITLE
Cross Compilation (v -os windows .) from *nix/wsl Dosen't Work. Missing windows.h

### ISSUE THREAD

**Issue by joe-conigliaro** [vlang/v#383]
I build V with WSL, then I tried to use that to build V for windows but I get:
/home/ko//.vlang0.0.12//compiler.c:3:23: fatal error: windows.h: No such file or directory
compilation terminated.
V panic: clang error

Edit: Ohh yeah i remembered there is only C generation a the moment, no machine code genration (x64 backend)

**Comment by kingofoz** [comment]
I am running into the same problem: 'windows.h' file not found. I am doing cross compilation from Ubuntu 18.04.2.

**Comment by joe-conigliaro** [comment]
> I am running into the same problem: 'windows.h' file not found. I am doing cross compilation from Ubuntu 18.04.2.

I don't think it can work because at the moment V is generating C code. Linux gcc/clang cant compile it because it cant find the windows headers. even if it had access to the windows.h i doubt it would compile on linux. 

We can probably take the geenrated C code which the V compiler puts in ~/.vlang0.0.12 and then compile that with MSVC

**Comment by kingofoz** [comment]
> 
> 
> > I am running into the same problem: 'windows.h' file not found. I am doing cross compilation from Ubuntu 18.04.2.
> 
> I don't think it can work because at the moment V is generating C code. Linux gcc/clang cant compile it because it cant find the windows headers. even if it had access to the windows.h i doubt it would compile on linux.
> 
> We can probably take the geenrated C code which the V compiler puts in ~/.vlang0.0.12 and then compile that with MSVC

Please try it. And tell me if it works.

**Comment by superwhiskers** [comment]
you don't need to use msvc. the only issue is the fact that it requires `execinfo.h` which is glibc-exclusive. i tried to compile it with mingw and that's the issue i came across
#397 proves this as they didn't have the `windows.h` missing error

**Comment by joe-conigliaro** [comment]
> you don't need to use msvc. the only issue is the fact that it requires `execinfo.h` which is glibc-exclusive. i tried to compile it with mingw and that's the issue i came across
> #397 proves this as they didn't have the `windows.h` missing error

I was just using msvc as example. mingw gcc should work also

**Comment by superwhiskers** [comment]
it won't compile at all regardless of how you compile it as v uses a header that's exclusive to glibc and a few other c stdlibs

**Comment by joe-conigliaro** [comment]
> it won't compile at all regardless of how you compile it as v uses a header that's exclusive to glibc and a Yeah that too.
I was able to compile it by adding my own version of getline

**Comment by liov** [comment]
same error，I don't want to build on WSL

**Comment by superwhiskers** [comment]
you can just download a c compiler and edit the v source code

**Comment by superwhiskers** [comment]
you don't need wsl

**Comment by joe-conigliaro** [comment]
> > > I am running into the same problem: 'windows.h' file not found. I am doing cross compilation from Ubuntu 18.04.2.
> > 
> > 
> > I don't think it can work because at the moment V is generating C code. Linux gcc/clang cant compile it because it cant find the windows headers. even if it had access to the windows.h i doubt it would compile on linux.
> > We can probably take the geenrated C code which the V compiler puts in ~/.vlang0.0.12 and then compile that with MSVC
> 
> Please try it. And tell me if it works.

Yes i was able to get it to compile on windows with gcc, now I have a working windows build

**Comment by joe-conigliaro** [comment]
@kingofoz here is how I got it to compile on windows: https://github.com/vlang/v/issues/413
