### ISSUE TITLE
b := (a++) is not forbidden

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#3834]
**V version:** 
latest master (MSVC)

**OS:** 
win10 1909

**What did you do?**
```V
mut a := 10
b := (a++)
```

**What did you expect to see?**
Give an error. (I think) in V `a++` is not a value and cannot be assigned to a variable.
 
**What did you see instead?**
No error occurred.

**Comment by t1ra** [comment]
On macOS, `b` is `10` and `a` is `11`, and the same behaviour occurs with `b := a++`. This behaviour is debatably "wrong", but I don't think it should be allowed.

**Comment by SleepyRoy** [comment]
@t1ra Exactly. The point is whether such syntax should be allowed in V.

**Comment by medvednikov** [comment]
No, `++` is a statement, not an expression, just like in Go.

**Comment by SleepyRoy** [comment]
@medvednikov Thanks. So I'll keep this issue open.
