### ISSUE TITLE
How to compile vid without complaints of compiler ?

### ISSUE THREAD

**Issue by dschinn1001** [vlang/v#3837]
V 0.1.25 f6c2b3a

Solus Linux 4.1

I have resolved all package dependencies, before I am now getting these
complaints of compiler.

I expected that compiling would now finish smooth and proper.

**What did you see instead?**

I have output as follows here : 

linux@$user ~/Downloads/V-language/v $ gcc --version
gcc (Solus) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
Dies ist freie Software; die Kopierbedingungen stehen in den Quellen. Es
gibt KEINE Garantie; auch nicht für MARKTGÄNGIGKEIT oder FÜR SPEZIELLE ZWECKE.

$user@unix ~/Downloads/V-language/v $ ~/Downloads/V-language/v/./v . -cg ~/Downloads/V-language/v/vid
C compiler=
warning: vid/vid.v:1819:1: the following imports were never used: 
 * uiold
/home/$user/.cache/v/vid.tmp.c: In Funktion »print_backtrace_skipping_top_frames_$user«:
/home/$user/.cache/v/vid.tmp.c:2515:18: Warnung: Zeigerziele bei Übergabe des Arguments 1 von »fgets« unterscheiden sich im Vorzeichenbesitz [-Wpointer-sign]
 2515 |  while ( fgets ( buf ,  1000 ,  f ) != 0 ) {
      |                  ^~~
      |                  |
      |                  byte * {alias unsigned char *}
In Datei, eingebunden von /home/$user/.cache/v/vid.tmp.c:48:
/usr/include/stdio.h:564:14: Anmerkung: »char * restrict« erwartet, aber Argument hat Typ »byte *« {alias »unsigned char *«}
  564 | extern char *fgets (char *__restrict __s, int __n, FILE *__restrict __stream)
      |              ^~~~~
/home/$user/.cache/v/vid.tmp.c: In Funktion »i64_hex«:
/home/$user/.cache/v/vid.tmp.c:2777:40: Warnung: Format »%x« erwartet Argumenttyp »unsigned int«, aber Argument 3 hat Typ »i64« {alias »long int«} [-Wformat=]
 2777 | int count= sprintf ((char*) hex ,  "0x%x" ,  n ) ;
      |                                       ~^     ~
      |                                        |     |
      |                                        |     i64 {alias long int}
      |                                        unsigned int
      |                                       %lx
/home/$user/.cache/v/vid.tmp.c: In Funktion »u64_hex«:
/home/$user/.cache/v/vid.tmp.c:2781:15: Warnung: Vergleich eines vorzeichenlosen Ausdrucks >= 0 ist stets »wahr« [-Wtype-limits]
 2781 | int len= (( n >= 0 ) ? ( u64_str ( n ) .len + 3 ) : ( 19 )) ;
      |               ^~
/home/$user/.cache/v/vid.tmp.c: In Funktion »map_rehash«:
/home/$user/.cache/v/vid.tmp.c:2929:28: Warnung: Vergleich von Ganzzahlausdrücken, von denen nur einer ein Vorzeichen hat: »int« und »u32« {alias »unsigned int«} [-Wsign-compare]
 2929 | for (int tmp4 = tmp3; tmp4 <  ( old_range_cap + 1 ); tmp4++) {
      |                            ^
/home/$user/.cache/v/vid.tmp.c: In Funktion »map_cached_rehash«:
/home/$user/.cache/v/vid.tmp.c:2986:28: Warnung: Vergleich von Ganzzahlausdrücken, von denen nur einer ein Vorzeichen hat: »int« und »u32« {alias »unsigned int«} [-Wsign-compare]
 2986 | for (int tmp6 = tmp5; tmp6 <  ( old_range_cap + 1 ); tmp6++) {
      |                            ^
/home/$user/.cache/v/vid.tmp.c: In Funktion »map_keys«:
/home/$user/.cache/v/vid.tmp.c:3131:28: Warnung: Vergleich von Ganzzahlausdrücken, von denen nur einer ein Vorzeichen hat: »int« und »u32« {alias »unsigned int«} [-Wsign-compare]
 3131 | for (int tmp8 = tmp7; tmp8 <  ( m ->range_cap + 1 ); tmp8++) {
      |                            ^
/home/$user/.cache/v/vid.tmp.c: In Funktion »stbi__load_from_memory«:
/home/$user/.cache/v/vid.tmp.c:6466:39: Warnung: Zeigerziele bei Übergabe des Arguments 1 von »stbi_load_from_memory« unterscheiden sich im Vorzeichenbesitz [-Wpointer-sign]
 6466 |  res .data  =  stbi_load_from_memory ((char*) buf ,  3812 ,  & res .width ,  & res .height ,  & res .nr_channels ,  flag ) ;
      |                                       ^~~~~~~~~~~
      |                                       |
      |                                       char *
In Datei, eingebunden von /home/$user/.cache/v/vid.tmp.c:401:
/home/$user/Downloads/V-language/v/thirdparty/stb_image/stb_image.h:375:18: Anmerkung: »const stbi_uc *« {alias »const unsigned char *«} erwartet, aber Argument hat Typ »char *«
  375 | STBIDEF stbi_uc *stbi_load_from_memory   (stbi_uc           const *buffer, int len   , int *x, int *y, int *channels_in_file, int desired_channels);
      |                  ^~~~~~~~~~~~~~~~~~~~~
/home/$user/.cache/v/vid.tmp.c: In Funktion »os__get_raw_line«:
/home/$user/.cache/v/vid.tmp.c:7289:25: Warnung: Übergabe des Arguments 1 von »getline« von inkompatiblem Zeigertyp [-Wincompatible-pointer-types]
 7289 | int nr_chars= getline ( & buf ,  & max ,  stdin ) ;
      |                         ^~~~~
      |                         |
      |                         unsigned char **
In Datei, eingebunden von /home/$user/.cache/v/vid.tmp.c:48:
/usr/include/stdio.h:616:45: Anmerkung: »char ** restrict« erwartet, aber Argument hat Typ »unsigned char **«
  616 | extern __ssize_t getline (char **__restrict __lineptr,
      |                           ~~~~~~~~~~~~~~~~~~^~~~~~~~~
/home/$user/.cache/v/vid.tmp.c: In Funktion »glm__identity2«:
/home/$user/.cache/v/vid.tmp.c:8022:31: Warnung: Zuweisung an »f32 *« {alias »float *«} von »int« wandelt eine Zahl in einen Zeiger um, ohne explizite Typkonvertierung [-Wint-conversion]
 8022 |  res [/*ptr!*/ 0 ]/*rf32 1*/  =  1 ;
      |                               ^
/home/$user/.cache/v/vid.tmp.c:8023:31: Warnung: Zuweisung an »f32 *« {alias »float *«} von »int« wandelt eine Zahl in einen Zeiger um, ohne explizite Typkonvertierung [-Wint-conversion]
 8023 |  res [/*ptr!*/ 5 ]/*rf32 1*/  =  1 ;
      |                               ^
/home/$user/.cache/v/vid.tmp.c:8024:32: Warnung: Zuweisung an »f32 *« {alias »float *«} von »int« wandelt eine Zahl in einen Zeiger um, ohne explizite Typkonvertierung [-Wint-conversion]
 8024 |  res [/*ptr!*/ 10 ]/*rf32 1*/  =  1 ;
      |                                ^
/home/$user/.cache/v/vid.tmp.c:8025:32: Warnung: Zuweisung an »f32 *« {alias »float *«} von »int« wandelt eine Zahl in einen Zeiger um, ohne explizite Typkonvertierung [-Wint-conversion]
 8025 |  res [/*ptr!*/ 15 ]/*rf32 1*/  =  1 ;
      |                                ^
/home/$user/.cache/v/vid.tmp.c: In Funktion »gl__new_shader«:
/home/$user/.cache/v/vid.tmp.c:8065:8: Warnung: Variable »dir« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
 8065 | string dir= tos3("") ;
      |        ^~~
/home/$user/.cache/v/vid.tmp.c: In Funktion »gl__init_glad«:
/home/$user/.cache/v/vid.tmp.c:8133:11: Warnung: Initialisierung von »void *« von »int« wandelt eine Zahl in einen Zeiger um, ohne explizite Typkonvertierung [-Wint-conversion]
 8133 | void* ok= gladLoadGL ( ) ;
      |           ^~~~~~~~~~
/home/$user/.cache/v/vid.tmp.c: In Funktion »gl__shader_source«:
/home/$user/.cache/v/vid.tmp.c:8156:34: Warnung: Übergabe des Arguments 3 von »glad_glShaderSource« von inkompatiblem Zeigertyp [-Wincompatible-pointer-types]
 8156 |  glShaderSource ( shader ,  a ,  & source .str ,  b ) ;
      |                                  ^~~~~~~~~~~~~
      |                                  |
      |                                  byte ** {alias unsigned char **}
/home/$user/.cache/v/vid.tmp.c:8156:34: Anmerkung: »const GLchar * const*« {alias »const char * const*«} erwartet, aber Argument hat Typ »byte **« {alias »unsigned char **«}
/home/$user/.cache/v/vid.tmp.c:8156:51: Warnung: Übergabe des Arguments 4 von »glad_glShaderSource« wandelt eine Zahl in einen Zeiger um, ohne explizite Typkonvertierung [-Wint-conversion]
 8156 |  glShaderSource ( shader ,  a ,  & source .str ,  b ) ;
      |                                                   ^
      |                                                   |
      |                                                   int
/home/$user/.cache/v/vid.tmp.c:8156:51: Anmerkung: »const GLint *« {alias »const int *«} erwartet, aber Argument hat Typ »int«
/home/$user/.cache/v/vid.tmp.c: In Funktion »gl__shader_info_log«:
/home/$user/.cache/v/vid.tmp.c:8182:45: Warnung: Zeigerziele bei Übergabe des Arguments 4 von »glad_glGetShaderInfoLog« unterscheiden sich im Vorzeichenbesitz [-Wpointer-sign]
 8182 |  glGetShaderInfoLog ( shader ,  512 ,  0 ,  info_log ) ;
      |                                             ^~~~~~~~
      |                                             |
      |                                             byte * {alias unsigned char *}
/home/$user/.cache/v/vid.tmp.c:8182:45: Anmerkung: »GLchar *« {alias »char *«} erwartet, aber Argument hat Typ »byte *« {alias »unsigned char *«}
/home/$user/.cache/v/vid.tmp.c: In Funktion »gl__get_program_info_log«:
/home/$user/.cache/v/vid.tmp.c:8187:48: Warnung: Zeigerziele bei Übergabe des Arguments 4 von »glad_glGetProgramInfoLog« unterscheiden sich im Vorzeichenbesitz [-Wpointer-sign]
 8187 |  glGetProgramInfoLog ( program ,  1024 ,  0 ,  info_log ) ;
      |                                                ^~~~~~~~
      |                                                |
      |                                                byte * {alias unsigned char *}
/home/$user/.cache/v/vid.tmp.c:8187:48: Anmerkung: »GLchar *« {alias »char *«} erwartet, aber Argument hat Typ »byte *« {alias »unsigned char *«}
/home/$user/.cache/v/vid.tmp.c: In Funktion »gl__draw_elements«:
/home/$user/.cache/v/vid.tmp.c:8233:43: Warnung: Übergabe des Arguments 4 von »glad_glDrawElements« wandelt eine Zahl in einen Zeiger um, ohne explizite Typkonvertierung [-Wint-conversion]
 8233 |  glDrawElements ( mode ,  count ,  typ ,  indices ) ;
      |                                           ^~~~~~~
      |                                           |
      |                                           int
/home/$user/.cache/v/vid.tmp.c:8233:43: Anmerkung: »const void *« erwartet, aber Argument hat Typ »int«
/home/$user/.cache/v/vid.tmp.c: In Funktion »gl__vertex_attrib_pointer«:
/home/$user/.cache/v/vid.tmp.c:8259:74: Warnung: Übergabe des Arguments 6 von »glad_glVertexAttribPointer« wandelt eine Zahl in einen Zeiger um, ohne explizite Typkonvertierung [-Wint-conversion]
 8259 |  glVertexAttribPointer ( index ,  size ,  typ ,  normalized ,  stride ,  ptr ) ;
      |                                                                          ^~~
      |                                                                          |
      |                                                                          int
/home/$user/.cache/v/vid.tmp.c:8259:74: Anmerkung: »const void *« erwartet, aber Argument hat Typ »int«
In Datei, eingebunden von /home/$user/.cache/v/vid.tmp.c:415:
/home/$user/.cache/v/vid.tmp.c: In Funktion »glfw__set_cursor«:
/home/$user/Downloads/V-language/v/thirdparty/glfw/GLFW/glfw3.h:1051:37: Warnung: Übergabe des Arguments 2 von »glfwSetCursor« wandelt eine Zahl in einen Zeiger um, ohne explizite Typkonvertierung [-Wint-conversion]
 1051 | #define GLFW_IBEAM_CURSOR           0x00036002
      |                                     ^~~~~~~~~~
      |                                     |
      |                                     int
/home/$user/.cache/v/vid.tmp.c:8394:23: Anmerkung: bei Substitution des Makros »GLFW_IBEAM_CURSOR«
 8394 |  glfwSetCursor ( 0 ,  GLFW_IBEAM_CURSOR ) ;
      |                       ^~~~~~~~~~~~~~~~~
In Datei, eingebunden von /home/$user/.cache/v/vid.tmp.c:415:
/home/$user/Downloads/V-language/v/thirdparty/glfw/GLFW/glfw3.h:4329:60: Anmerkung: »GLFWcursor *« {alias »struct GLFWcursor *«} erwartet, aber Argument hat Typ »int«
 4329 | GLFWAPI void glfwSetCursor(GLFWwindow* window, GLFWcursor* cursor);
      |                                                ~~~~~~~~~~~~^~~~~~
In Datei, eingebunden von /home/$user/.cache/v/vid.tmp.c:415:
/home/$user/.cache/v/vid.tmp.c: In Funktion »glfw__Window_set_cursor«:
/home/$user/Downloads/V-language/v/thirdparty/glfw/GLFW/glfw3.h:1051:37: Warnung: Übergabe des Arguments 2 von »glfwSetCursor« wandelt eine Zahl in einen Zeiger um, ohne explizite Typkonvertierung [-Wint-conversion]
 1051 | #define GLFW_IBEAM_CURSOR           0x00036002
      |                                     ^~~~~~~~~~
      |                                     |
      |                                     int
/home/$user/.cache/v/vid.tmp.c:8397:30: Anmerkung: bei Substitution des Makros »GLFW_IBEAM_CURSOR«
 8397 |  glfwSetCursor ( w ->data ,  GLFW_IBEAM_CURSOR ) ;
      |                              ^~~~~~~~~~~~~~~~~
In Datei, eingebunden von /home/$user/.cache/v/vid.tmp.c:415:
/home/$user/Downloads/V-language/v/thirdparty/glfw/GLFW/glfw3.h:4329:60: Anmerkung: »GLFWcursor *« {alias »struct GLFWcursor *«} erwartet, aber Argument hat Typ »int«
 4329 | GLFWAPI void glfwSetCursor(GLFWwindow* window, GLFWcursor* cursor);
      |                                                ~~~~~~~~~~~~^~~~~~
/home/$user/.cache/v/vid.tmp.c: In Funktion »glfw__get_monitor_size«:
/home/$user/.cache/v/vid.tmp.c:8406:20: Warnung: Initialisierung streicht Qualifizierer »const« von Zeiger-Zieltyp [-Wdiscarded-qualifiers]
 8406 | GLFWvidmode* mode= glfwGetVideoMode ( glfwGetPrimaryMonitor ( ) ) ;
      |                    ^~~~~~~~~~~~~~~~
/home/$user/.cache/v/vid.tmp.c: In Funktion »freetype__ft_load_char«:
/home/$user/.cache/v/vid.tmp.c:8776:23: Warnung: Zeigerziele bei Übergabe des Arguments 2 von »glad_glGenTextures« unterscheiden sich im Vorzeichenbesitz [-Wpointer-sign]
 8776 |  glGenTextures ( 1 ,  & texture ) ;
      |                       ^~~~~~~~~
      |                       |
      |                       int *
/home/$user/.cache/v/vid.tmp.c:8776:23: Anmerkung: »GLuint *« {alias »unsigned int *«} erwartet, aber Argument hat Typ »int *«
/home/$user/.cache/v/vid.tmp.c: In Funktion »freetype__new_context«:
/home/$user/.cache/v/vid.tmp.c:8803:12: Warnung: Initialisierung von »void *« von »FT_Error« {alias »int«} wandelt eine Zahl in einen Zeiger um, ohne explizite Typkonvertierung [-Wint-conversion]
 8803 | void* ret= FT_Init_FreeType ( & ft ) ;
      |            ^~~~~~~~~~~~~~~~
/home/$user/.cache/v/vid.tmp.c:8826:7: Warnung: Zuweisung an »void *« von »int« wandelt eine Zahl in einen Zeiger um, ohne explizite Typkonvertierung [-Wint-conversion]
 8826 |  ret  =  ((int)( FT_New_Face ( ft , (char*) font_path .str ,  0 ,  & face ) ) ) ;
      |       ^
/home/$user/.cache/v/vid.tmp.c: In Funktion »freetype__FreeType_private_draw_text«:
/home/$user/.cache/v/vid.tmp.c:8891:11: Warnung: Vergleich ist durch beschränkten Wertebereich des Datentyps stets »unwahr« [-Wtype-limits]
 8891 |  if ( idx < 0  ||  idx >= ctx ->chars .len ) {
      |           ^
/home/$user/.cache/v/vid.tmp.c: In Funktion »freetype__FreeType_text_size«:
/home/$user/.cache/v/vid.tmp.c:8978:11: Warnung: Vergleich ist durch beschränkten Wertebereich des Datentyps stets »unwahr« [-Wtype-limits]
 8978 |  if ( idx < 0  ||  idx >= ctx ->chars .len ) {
      |           ^
/home/$user/.cache/v/vid.tmp.c: In Funktion »os__ext«:
/home/$user/.cache/v/vid.tmp.c:7266:2: Warnung: Kontrollfluss erreicht Ende von Nicht-void-Funktion [-Wreturn-type]
 7266 |  }
      |  ^
/home/$user/.cache/v/vid.tmp.c: In Funktion »os__dir«:
/home/$user/.cache/v/vid.tmp.c:7269:2: Warnung: Kontrollfluss erreicht Ende von Nicht-void-Funktion [-Wreturn-type]
 7269 |  }
      |  ^
/home/$user/.cache/v/vid.tmp.c: In Funktion »os__basedir«:
/home/$user/.cache/v/vid.tmp.c:7272:2: Warnung: Kontrollfluss erreicht Ende von Nicht-void-Funktion [-Wreturn-type]
 7272 |  }
      |  ^
/home/$user/.cache/v/vid.tmp.c: In Funktion »os__filename«:
/home/$user/.cache/v/vid.tmp.c:7275:2: Warnung: Kontrollfluss erreicht Ende von Nicht-void-Funktion [-Wreturn-type]
 7275 |  }
      |  ^
/home/$user/.cache/v/vid.tmp.c: In Funktion »os__join«:
/home/$user/.cache/v/vid.tmp.c:7657:2: Warnung: Kontrollfluss erreicht Ende von Nicht-void-Funktion [-Wreturn-type]
 7657 |  }
      |  ^
/usr/bin/ld: cannot find -lglfw
collect2: Fehler: ld gab 1 als Ende-Status zurück
V error: 
==================
C error. This should never happen.

V compiler version: V 0.1.25 f6c2b3a
Host OS: $user
Target OS: $user

**Comment by medvednikov** [comment]
You have to install glfw.

**Comment by dschinn1001** [comment]
Hello Alexander,

glfw was installed.
(with glfw-devel?).

Greetz.
Val.

Alexander Medvednikov <notifications@github.com> schrieb am Do., 27. Feb.
2020, 16:41:

**Comment by medvednikov** [comment]
well it says `cannot find -lglfw` so it's not installed correctly

**Comment by dschinn1001** [comment]
I will look after.

Tommorrow I know more.

Here it is bedtime.

Good night.

Alexander Medvednikov <notifications@github.com> schrieb am Do., 27. Feb.
2020, 21:13:

**Comment by dschinn1001** [comment]
Yes.
Here is Solus Linux.
The thing was glfw is already installed, but
glfw-devel was not installed. So I settled it.

Compilation apparently without complaint.

V version is 0.1.25 6855c74

When
./vid

At first time there was Window visible under 1 second.
Then it crashed.

Error message is :

create window wnd=0x1126f40 ptr==0x1125e80
Trying to load font from RobotoMono-Regular.ttf
Memory access error

???

I try now again with actual vid files of today.



Carl-Valentin Schmitt <cv.schmitt@gmail.com> schrieb am Do., 27. Feb. 2020,
21:43:

**Comment by dschinn1001** [comment]
In which directory should files of /vid
be?

Carl-Valentin Schmitt <cv.schmitt@gmail.com> schrieb am Fr., 28. Feb. 2020,
22:14:

**Comment by medvednikov** [comment]
Any directory. Try `./vid file.txt`

This should be in github.com/vlang/vid

**Comment by dschinn1001** [comment]
Is memory declared correctly for this program?

Or do I need to reserve some memory myself?

Alexander Medvednikov <notifications@github.com> schrieb am Sa., 29. Feb.
2020, 00:28:
