### ISSUE TITLE
Establish way to automate testing of builds on different platforms/environments

### ISSUE THREAD

**Issue by jrenner** [vlang/v#384]
It would be nice to have easy ways to test that building the language succeeds on different platforms. I have created a docker image (https://github.com/jrenner/vlang-docker) for testing building the V language from scratch on the latest Ubuntu. It can also serve as a local sandbox for people who want to try out the language. Perhaps this could eventually be integrated into a CI solution to make sure there are no breaking changes.

**Comment by LouCle** [comment]
We're aware of this, and have been looking at CI solutions
