### ISSUE TITLE
Allow interfaces to include struct fields, not just methods

### ISSUE THREAD

**Issue by elimisteve** [vlang/v#3868]
## What and Why

At present, V's interfaces are limited like Go's in that they require unnecessary boilerplate code to be written.

The following feature request proposes to solve this problem by allowing interfaces to be defined not only in terms of methods, like

```v
interface Namer {
    my_name() string
}
```

but also in terms of struct fields, like

```v
interface Namer {
    name string  // struct field, not a method!
}
```

## Examples

Here is a modified version of the interface example from https://vlang.io/docs#interfaces --

```v
struct Dog { name string }
struct Cat { name string }

fn (d Dog) my_name() string {
    return d.name  // we shouldn't have to do this
}

fn (c Cat) my_name() string {
    return d.name  // ...more boilerplate...
}

interface Namer {
    my_name() string
}

fn intro(n Namer) string {
    return 'Hi, my name is $n.my_name()'
}

dog := Dog{name: 'woof'}
cat := Cat{name: 'meow'}
println(intro(dog)) // "Hi, my name is woof"
println(intro(cat)) // "Hi, my name is meow"
```

As in Go, we see we need to create additional boilerplate in the form of a `my_name` methods on `Cat`s and `Dog`s. But we can do better!

Here is the solution under this proposal:

```v
struct Dog { name string }
struct Cat { name string }

interface Namer {
    name string  // this is a struct field, not a method!
}

fn intro(n Namer) string {
    return 'Hi, my name is $n.name'
}

dog := Dog{name: 'woof'}
cat := Cat{name: 'meow'}
println(intro(dog)) // "Hi, my name is woof"
println(intro(cat)) // "Hi, my name is meow"
```

Plus, note how elegantly this can be combined with V's generic structs:

```v
struct Node<T> {
    val T
    name string
    created time.Time
}

// Notice that every particular Node<T> (e.g., Node<int>,
// Node<string>, etc) will naturally implement the
// 'NameTimer' interface(!), _and_ everything else with
// a `name string` and a `created time.Time` will, too

interface NameTimer {
    name string
    created time.Time
}

struct User {
    id i64
    name string
    email string
    created time.Time
    modified time.Time
}

fn node_namer(n NameTimer) string {
    return 'I am "$n.name", created at $n.created, and of type ' + typeof(n)
}

fn main() {
    int_node := Node<int>{1, 'one', time.now()}
    str_node := Node<string>{'2', 'two', time.now()}
    user := User{id: i64(3), name: 'Alex', email: 'v@vlang.io', created: time.now()}

    println(node_namer(int_node))  // 'I am "one", created at 2020-02-27 21:15:08, and of type Node<int>'
    println(node_namer(str_node))  // 'I am "two", created at 2020-02-27 21:15:08, and of type Node<str>'
    println(node_namer(user))  // 'I am "Alex", created at 2020-02-27 21:15:08, and of type User'
}
```

## More Benefits

By eliminating needless boilerplate code that only complicates the writing of V code, we can make V more fun and more powerful _without_ making it significantly more complex.

I have taught Go to several people, and they all expected interfaces to support this functionality, and they don't, forcing them to write 1-line wrapper methods. Plus, adding this feature will allow us to translate from V to TypeScript much more easily, since this is basically a simplified subset of TypeScript interfaces.

## Structs Only

This proposal indeed means that non-struct-based types cannot implement interfaces that contain fields. But 99% of user-specified types are struct-based anyway, and it would be odd for a user to want something like `type MyInt int` to implement an interface meant for completely different kinds of objects anyway.

## Conclusion

Given that this proposal solves a real problem, complies with [this comment](https://github.com/vlang/v/issues/2711#issuecomment-553670278) from @BlackjackZ94 that @medvednikov said he agrees with the spirit of (just below that comment itself), uses familiar syntax, and given that this feature is very much in the spirit of V, I urge Alex to accept this feature request!

Thank you.

**Comment by Delta456** [comment]
I remember Alex  giving this a while back in the discord server and also why to allow only `struct`? Couldn't types like `int`, `float`, `byte` also be added to fields?

**Comment by medvednikov** [comment]
Yes, this will be implemented, like in TypeScript.

**Comment by spytheman** [comment]
@Delta456 the proposed feature means that the type that implements the interface will have to have all of the fields of the interface, or it will not satisfy the interface.
Primitive types like int, f32 and so on do not have fields => they will not satisfy such interfaces.

**Comment by Delta456** [comment]
@spytheman Oh I meant that ` using the primitives in the interface fields themselves` and thanks for answering really grateful!

**Comment by kahsa** [comment]
Here are my impressions of using this feature.

Interface fields seem to be useful, but I found a pitfall.
It is useful when it is a _property_, not a field.

Kotlin and C# have properties, and Interface has properties.
Go and Rust, on the other hand, do not have properties, and there are no fields in Interface.
I don't think this is a coincidence.

It is true that Interface properties are useful.
So, my suggestion is to introduce properties for V as well.

**Comment by dumblob** [comment]
@kahsa why properties? Do you want to do more checks before assigning new values to the fields? If so, then *V* has a different philosophy IMHO and identical problem exists on many other places in *V* and *V* offers solutions to all of them. So this particular reason doesn't sound like an argument.

Or do you have other use cases? Could you write a motivational example comparing the current implementation with your vision?
