### ISSUE TITLE
failed to compile v.c on macOS

### ISSUE THREAD

**Issue by iredmail** [vlang/v#388]
macOS: 10.14.5 (18F132)

```
$ cc -w -o vc v.c           # Build it with Clang or GCC
In file included from v.c:3:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/include/inttypes.h:30:15: fatal error: 
      'inttypes.h' file not found
#include_next <inttypes.h>
              ^~~~~~~~~~~~
1 error generated.
```

## Solution

```
xcode-select --install    # install command line tools and headers.
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```

**Comment by scroot** [comment]
I'm all OK   
macOS 10.13.6

**Comment by iredmail** [comment]
I'm running macOS 10.14.5 (18F132).

**Comment by proyb6** [comment]
I'm on 10.14.5, I remember someone mentioned the need to installed additional headers on Mojave.

Do you have an includes folder?
```ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/```

**Comment by iredmail** [comment]
Both files exist on my macOS 10.14.5:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/include/inttypes.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/inttypes.h
```

**Comment by proyb6** [comment]
I tested to reproduce with compile error, it tried to looks for the missing header in ```/usr/include/inttypes.h```

I think this discussion may help:
https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave

**Comment by proyb6** [comment]
I've reproduce with compile error, it tried to look for the missing header in ```/usr/include/inttypes.h```

I think this discussion may help:
https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave

**Comment by iredmail** [comment]
Fixed with steps below:

1. Run `xcode-select --install` to install command line tools and headers.
1. Run `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`

This better be mentioned on V installation tutorial (for macOS part). :)

**Comment by AurelienFT** [comment]
@iredmail Can you do a pull request for this please ?

**Comment by iredmail** [comment]
Someone already created one: #436
https://github.com/vlang/v/pull/436

**Comment by Tyuzu** [comment]
I am getting the same error on windows 8.1 mingw-64. Should I create a new issue?
`
me@Thor MINGW64 /f/v (master)
$ gcc -std=gnu11 -w -o v.exe v.c
v.c:3:10: fatal error: inttypes.h: No such file or directory
 #include <inttypes.h> // int64_t etc
          ^~~~~~~~~~~~
compilation terminated.

me@Thor MINGW64 /f/v (master)
$
`

**Comment by iredmail** [comment]
Yes please. This issue title is about “macOS” :(
