### ISSUE TITLE
Cannot assign to map

### ISSUE THREAD

**Issue by cup** [vlang/v#3885]
Using this:

<https://github.com/vlang/v/releases/download/0.1.24/v_windows.zip>

and this page:

<https://vlang.io/docs#maps>

an example like this works fine:

~~~v
m1 := map[string]int
m2 := {'sun': 10, 'mon': 11}
println("Sunday")
~~~

but these both fail to compile:

~~~v
m1 := map[string]int
m1['sun'] = 10
println("Sunday")
~~~

~~~v
m1 := {'sun': 10, 'mon': 11}
m1['tue'] = 12
println("Sunday")
~~~

**Comment by Delta456** [comment]
Does wrapping this inside `fn main() {}` works?

**Comment by cup** [comment]
@Delta456 problem continues even with `main`.

PS, is V able to emit warnings? Whenever I compile, if something goes wrong it just exits with no output at all.

**Comment by Delta456** [comment]
You forgot to mutable i.e. `mut` them.

**Comment by cup** [comment]
This works, I will post the other problem as a separate issue:

~~~v
fn main() {
   // example 1
   mut m1 := map[string]int
   m1['sun'] = 10
   // example 2
   mut m2 := {'sun': 10, 'mon': 11}
   m2['tue'] = 12
   // print
   println("Sunday")
}
~~~
