### ISSUE TITLE
[Question] A few quick questions. 

### ISSUE THREAD

**Issue by MostHated** [vlang/v#389]
Hey there,  
First and foremost, I know things are insanely busy right now, so feel free to disregard this until things have calmed down. 

That said, awesome job and thanks for releasing this! Based on all I have read so far, this sounds great. I had a few questions, though. I see that a lot of emphasis is on the C/C++ aspect, such as the speed, interoperability, etc (which is great), but there are a lot of Go aspects involved with it as well, it seems. 

I see the syntax is quite similar, it was even mentioned that you will soon be able to run actual goroutines using the scheduler, and the compiler was originally written in Go? So does this mean that you could take current Go code/libraries and make the syntax adjustments necessary and it would essentially take what would have been a Go application and it would now be as fast as a C application as well as have access to the mentioned graphical libraries, but also be able to directly communicate with C (and soon to be C++) networking and other libraries as a V application? If so, is it also capable of importing/converting and interoperability with Go?

I ask because over the last many weeks I have been working on learning Go heavily, and it feels too good to be true that I could take what I have learned so far and simply change syntax a bit and then applications I make now would have the speed as well as the graphical and networking libraries of C/C++ available? 

I realize there is a bit more too it than that, considering there is no garbage collector and things of that nature, but overall do I have this information correct that I could essentially write modified Go in place of having to deal with the syntax and nuances of C, yet have the same performance outcome, or am I just aboard a self hype train that is moving fast enough that I can't properly read the signs as they pass by?

Thanks again,
-MH

**Comment by medvednikov** [comment]
Hi

Sorry for the delay.

Indeed, the language is similar to Go, and it would be really cool to have a Go to V translator. See the discussion here: https://github.com/vlang/v/issues/527

The major problems are Go assembly and GC. But I think it's possible to imitate Go's runtime and to translate, say, `net/http` to V.

**Comment by MostHated** [comment]
No worries, most of these got answered by my chatting with other folks in several of the other threads. I appreciate you taking the time to answer though.
