### ISSUE TITLE
Syntactic sugar for regex

### ISSUE THREAD

**Issue by noorwachid** [vlang/v#3898]
I know the creators take aim for performance, but it would be nice if we can do this:

```v
import regex

names := 'Elsa, Alexa, Sarah, James, Andrew'

// match
matched := /alexa/gi in names // return bool
matched  = true

// search
found := /(A\w+)/g from names // return []string
found  = ['Alexa', 'Andrew']

// replace 
newnames := /(Alexa)/\1nder/g from names // return string
newnames  = 'Elsa, Alexander, Sarah, James, Andrew'

```

**Comment by dumblob** [comment]
This is a huge problem for one simple reason - syntax of the language is the only **absolutely** stable thing in the whole life (tens of years) of a language, but API and modules (including regex syntax) change over time way quicker.

So I'm actually against this proposal. Tying inherently different things together won't have the desired effects. It would also unnecessarily extend the *V* parser (see the current regex parser to understand what I mean) and create yet another place for weird bugs and misunderstandings (it would need to have some limitations anyway compared to e.g. raw strings).

What is actually the main purpose of having regex syntax "built in"? It won't have any performance benefit. The only thing is, that some (by far not all) things could be checked in compile time (though this could be done later in the regex module as well once the new *V* compiler gets released as it has the capability of compile time interpretation of *V* itself - think of a constrained "eval").

Note also, that *V* as it stands (and there seem to be currently no plans to change it) doesn't even offer [arbitrary operator overloading](https://vlang.io/docs#op ) and [cool things actually helping to avoid syntax clutter and increase code safety](https://github.com/vlang/v/pull/1962#discussion_r324333188 ) were not implemented to keep *V* as simple as possible.
