### ISSUE TITLE
Remove test release

### ISSUE THREAD

**Issue by diegobernardes** [vlang/v#3916]
There is any reason for the `test` release? Is it a mistake?

![image](https://user-images.githubusercontent.com/14483/75771521-0c12ba00-5d42-11ea-9dea-1aa8fbadb460.png)

![image](https://user-images.githubusercontent.com/14483/75771579-28165b80-5d42-11ea-8ce4-15bea45714e9.png)

https://github.com/vlang/v/releases/tag/mytest

**Comment by medvednikov** [comment]
Removed.
