### ISSUE TITLE
Missing licenses for font files

### ISSUE THREAD

**Issue by salifm** [vlang/v#3934]
Hi, I think you should include license files for fonts that you distribute: 
`examples/tetris/RobotoMono-Regular.ttf`, 
`vlib/sdl/examples/tvintris/fonts/RobotoMono-Regular.ttf`, 
`examples/sokol_examples/assets/DroidSerif-Regular.ttf`, 
`examples/sokol_examples/assets/ProggyTiny.ttf`

As far as I know Roboto Mono and Droid Serif are licensed under Apache license 2.0.

**Comment by alexesprit** [comment]
ProggyTiny font is licensed under the MIT License. Refs:
- https://github.com/bluescan/proggyfonts
- https://github.com/chrissimpkins/codeface/tree/master/fonts/proggy-tiny

**Comment by alexesprit** [comment]
I added licenses, and can make a PR that closes this issue, but it depends on #3941.
