### ISSUE TITLE
[Suggestion] Use proper abbreviations

### ISSUE THREAD

**Issue by LakeVilladom** [vlang/v#395]
比如Modules中的`gg`、`gl`、`glm`、`gx`等，太过简略，不能让人一目了然，再比如`time`下的`time_lin.v`，如果不是在特定情况下，很难联想到lin即指linux。
对于缩写，应该更多借鉴Go，而非Rust，首先在清楚无歧义的情况下其次考虑适当简写。

英文大牛帮忙翻译，[抱拳]

**Comment by jrenner** [comment]
He is suggesting that abbreviations don't make clear what they are talking about, and he didn't associate time_lin with time_linux, for example

**Comment by MapleCCC** [comment]
Whole-text translation of PM:

[Suggestion] Use proper abbreviations

Some abbreviations are not informative enough to understand what it's referring to at first sight. E.g., gg, gl, glm, gx modules. Another example is that random people might not be able to properly understand the "lin" in "time_lin.v" is referring to "linux".

I suggest our choice of word abbreviation to get more inspiration from Go-style and against Rust-style, i.e., coin appropriate abbreviation only when ambiguity is not significantly impacting.

**Comment by jackey** [comment]
agree 👍

**Comment by Bowero** [comment]
This is a very important discussion and it is important that this is being talked about, but please keep the discussion in English.

**Comment by WuYanZhong** [comment]
agree

**Comment by gslicer** [comment]
abbreviation are OK so far, what is missing is the proper documentation at this stage perhaps?
so e.g in a file named time_lin.v I would expect thet the first lines will be something like:
```v
/* time_lin.v - time routines for the GNU/Linux OS platform 
Bla bla some explainatory prosa
*/
```

**Comment by medvednikov** [comment]
Many abbreviations were removed

lin => linux
win => windows

Module names need to be short.
