### ISSUE TITLE
Build failed with Mingw-w64.

### ISSUE THREAD

**Issue by ofunc** [vlang/v#397]
```
$ cc --version
cc.exe (Rev1, Built by MSYS2 project) 9.1.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
$ cc -w -o vc v.c
v.c:65:10: fatal error: execinfo.h: No such file or directory
   65 | #include <execinfo.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```

**Comment by ofunc** [comment]
Build succeed on WSL.

**Comment by joe-conigliaro** [comment]
@ofunc I was able to get it to compile on windows, but there were a couple of  things I had to do, I might make another issue explaining

**Comment by joe-conigliaro** [comment]
@ofunc here is how I got it to compile for windows: https://github.com/vlang/v/issues/413

**Comment by nedpals** [comment]
@ofunc How did you able to compile it in WSL? I was able to remove the error by putting an `#ifdef` around the `#include <execinfo.h>`. I am stuck at these messages:

```bash
/tmp/v-7c6724.o:(.text+0x9100): undefined reference to `getline'
/tmp/v-7c6724.o:(.text+0x9632): undefined reference to `backtrace'
/tmp/v-7c6724.o:(.text+0x965c): undefined reference to `backtrace_symbols_fd'
```

I'm using WCLANG btw

**Comment by Bowero** [comment]
Please refer to #413. We have too many Windows issues otherwise. Thanks for your understanding.
