### ISSUE TITLE
glfw: Crashed after calling a method of the window user pointer

### ISSUE THREAD

**Issue by ZeroX-DG** [vlang/v#3975]
**V version:** 0.1.25 5142747
**OS:**  Ubuntu 18.10

**What did you do?**
I created a simple app that used `glfw` to create the window and render with `gl` which it works. I then added a keydown handler to test if the window can receive the key press and it did. However, I then invoke a method of the main struct that I get via `glfw.get_window_user_pointer` and the app crashed with this error:

```
Segmentation fault (core dumped)
```

**What did you expect to see?**
The method would invoke without any problem
 
**What did you see instead?**
The app crashed and the error was
```
Segmentation fault (core dumped)
```

**Comment by ZeroX-DG** [comment]
A workaround for this is by using:
```
set_user_ptr
```

**Comment by spytheman** [comment]
Can you post a small example of your source code that segfaulted?

**Comment by ZeroX-DG** [comment]
This is a small example that cause the problem:
```v
module main

import glfw
import gg
import gx
import time

struct App {
  mut:
  gg   &gg.GG
  data Data
}

struct Data {
  value string
}

fn main() {
  glfw.init_glfw()
  mut app := &App {
    gg: gg.new_context(gg.Cfg {
      width: 300
      height: 200
      use_ortho: true
      create_window: true
      window_title: 'test'
      window_user_ptr: app
    })
    data: {
      value: 'hello'
    }
  }

  // uncomment the line bellow to fix the problem
  // app.gg.window.set_user_ptr(app)
  app.gg.window.onkeydown(key_down)

  for {
    gg.clear(gx.hex(0xffffff))
    app.gg.render()
    if app.gg.window.should_close() {
      app.gg.window.destroy()
      return
    }
    time.sleep_ms(1000 / 60) // 60 fps
  }
}

fn (app App) method() {
  println(app.data.value)
}

fn key_down(wnd &glfw.Window, key, code, action, mods int) {
  mut app := &App(glfw.get_window_user_pointer(wnd))

  match key {
    glfw.KeyUp {
      app.method()
    }
    else {}
  }
}
```

**Comment by yuyi98** [comment]
This is your usage error.
`app` variable sits not yet created, and you use it in `window_user_ptr: app`.

**Comment by ZeroX-DG** [comment]
Yes I thought so too, that seem to be the problem. Even though I think `v` should have a warning about using uninitialized variable, I reckon this problem will be fixed in the future because of this cooment:
 https://github.com/vlang/v/blob/876b73f92ca2fa098d4cb4eeeb2c19b1e1722283/examples/tetris/tetris.v#L156

I'll close this issue.
