### ISSUE TITLE
enum from/to string

### ISSUE THREAD

**Issue by radare** [vlang/v#3983]
**V version:** V 0.1.25 876b73f
**OS:** macOS 10.15

**What did you do?**

enum foo {bar}
eprintln(foo.bar.str)

**What did you expect to see?**

all enum types should provide a compiler helper to resolve an enum type by string or get the string representation of the enum type. it is so tedious to do that in GLIB programs for example, as well as in C, and i think V should provide such helpers otu of the box to avoid the ugly spaguetti in vlib/compiler/main.v - os_from_string(os string) pref.OS
 
**What did you see instead?**

**Comment by medvednikov** [comment]
Yes, this will be implemented.

**Comment by RiordanIX** [comment]
https://github.com/vlang/v/pull/4180 implemented this, did it not? If so, this can be closed.

**Comment by medvednikov** [comment]
This issue is also about the opposite: string to enum.
