### ISSUE TITLE
v can't compile, due to circular import: os & filepath

### ISSUE THREAD

**Issue by xucs007** [vlang/v#3985]
Newest code on github on 2020/3/10:

$ make
rm -rf vc/
git clone --depth 1 --quiet https://github.com/vlang/vc
#cp fns.h vc/fns.h
rm -rf /var/tmp/tcc/
git clone --depth 1 --quiet https://github.com/vlang/tccbin /var/tmp/tcc
cc -std=gnu11 -w -o v vc/v.c  -lm
Self rebuild (0d45d21 => 7959965b)
HINT: The V compiler is now located in `cmd/v`.
      `v.v` is no longer the correct path to compile if you are intending to do so.
V error: import cycle detected between the following modules: 

 * os -> filepath
 * filepath -> os

Makefile:30: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by medvednikov** [comment]
Use `make` to build the latest version, after that use `v self`.

**Comment by medvednikov** [comment]
`filepath` module was removed recently, make sure your repo is up-to-date.
