### ISSUE TITLE
`vlib` increases ui module level and put `gg,gx,gl,glfw,sdl,sokol...` in it.

### ISSUE THREAD

**Issue by yuyi98** [vlang/v#3987]
`vlib` have too many graphical interfaces to handle related modules, and it seems a bit messy to put other modules at the same level, so I think we can increases ui module level and put `gg,gx,gl,glfw,sdl,sokol...` in it.

**Comment by nedpals** [comment]
Some of the modules will be removed soon in favor of `sokol`.
@medvednikov What's your take on this?
