### ISSUE TITLE
Problem With time.now().format() 

### ISSUE THREAD

**Issue by madranet** [vlang/v#3991]
**V version:** 
V 0.1.25 7309be5
**OS:** 
OSX 10,14,4

I've got an existing script which I'm trying to convert to V. 

It causes my RaspberryPi to take a photo with the Pi's camera module, saves it with a filename formatted `yyyy-mm-dd-hh-mm-ss.jpg` and then uploads to Google Drive.

The version I'm porting was written in Nim and the code to generate the filename is very simple:

```nim
#build filename from datestamp
let timestamp = (now().format("yyyy-MM-dd-HH-mm-ss") & ".jpg")
```

Trying to do the same thing in V is proving quite a headache.  

Apart from the lack of documentation --let's take that as read [or should that be 'unread'?]-- the source code I'm perusing for the [v/vlib/time/format.v](https://github.com/vlang/v/blob/master/vlib/time/format.v) functions doesn't seem to be doing what I expect. Could be that I'm interpreting it wrongly, but here goes:

I try the simple version first:

```v
//build filename from datestamp
timestamp := time.now().format()+".jpg"

$> v run snapper.v

DEBUG: filename ==> 2020-03-11 14:50.jpg
```

Two problems there:

1: there's a space in the filename between date and time.

2: The time uses `:` which is a filepath separator on OSX, so should never be part of a filename.

So I'm going to have to do some formatting.  The date is easy enough. In fact the default is fine. But, if I want to be verbose about it. From the source:

```v
// get_fmt_time_str returns a date string with specified
// FormatDelimiter and FormatDate type.
pub fn (t Time) get_fmt_date_str(fmt_dlmtr FormatDelimiter, fmt_date FormatDate)
```

So I use:

```v
timestamp := time.now().get_fmt_date_str(.hyphen,.yyyymmdd)+".jpg"
println("DEBUG: filename ==> " + timestamp)
```

which works fine:

```v
$> v run snapper.v

DEBUG: filename ==> 2020-03-11.jpg
```

Now to try the same with the time.  Again the source looks fairly straightforward. This function looks like it handles both the date and time:

```v
// get_fmt_str returns a date string with specified FormatDelimiter,
// FormatTime type, and FormatDate type.
pub fn (t Time) get_fmt_str(fmt_dlmtr FormatDelimiter, fmt_time FormatTime, fmt_date FormatDate)
```

Let's try that:

```v
timestamp := time.now().get_fmt_str(.hyphen,.hhmmss24,.yyyymmdd)+".jpg"
println("DEBUG: filename ==> " + timestamp)
```
Hmmm... 

```v
$> v run snapper.v

DEBUG: filename ==> 2020-03-11 15:01:53.jpg
```

Several things puzzling me here:

1: V seems to have only applied my chosen delimiter to the date, not the time

2: There is still a space between date and time. Why wasn't the delimiter used?

3: The function returns the elements in the order `date > time` [That's actually the order I want in this case, but it's a bit confusing because the function is passed those parameters in the order `time > date`

In the interests of scientific research, I tried reversing the order of the parameters, just to see what would break:

```v
timestamp := time.now().get_fmt_str(.hyphen,.yyyymmdd,.hhmmss24)+".jpg"
println("DEBUG: filename ==> " + timestamp)
```

 and got a rather confused compiler error message:

```v
$> v run snapper.v

snapper.v:18:54: enum `time.FormatTime` does not have value `yyyymmdd`
   18| timestamp := time.now().get_fmt_str(.hyphen,.yyyymmdd,.hhmmss24)+".jpg"
                                                            ^
   19| println("DEBUG: filename ==> " + timestamp)
```

which, although technically correct does seem a bit confusing as the parameter `.yyyymmdd` is a valid one for the formatting function, It's just been passed in the wrong order.

So, after all that rambling, my question basically comes down to the following:

1: Am I using the `time.format()` options correctly, or am I missing some easier way to achieve what I want?

2: If I am using `time.format()` correctly, does that mean the only way to format a safe [ie. no spaces or fancy characters] `date-time.jpg` filename is to build it from some convoluted formula like running a `str_replace` on the result of something like `time.now().get_fmt_str(.hyphen,.hhmmss24,.yyyymmdd)` to replace the spaces and colons?

Surely not?  When something along the Nim lines like `time.now.format("yyyy-mm-dd-hh-mm-ss")` would be so much less painful.

**Comment by medvednikov** [comment]
Hi

The time module has different format enums: FormatTime and FormatDate. When you try to use `yyyymmdd` as a FormatTime, you get the error.

Regarding the delimiter, looks like an easy to fix bug in the time module. I'll have a look soon, or someone else will.

Thanks.

**Comment by madranet** [comment]
Cheers!

Meantime I came up with this slightly  'less than elegant' solution:

```v
import time

fn main() {
filename := (time.now().str()+".jpg").replace(" ", "-").replace(":","-")
println("DEBUG: filename ==> $filename")
} 
```

```
ᐅ  v run test.v
DEBUG: filename ==> 2020-03-15-10-53-37.jpg
```
