### ISSUE TITLE
Import directly from a file

### ISSUE THREAD

**Issue by hazae41** [vlang/v#4022]
I find the module system too complex and too rigid.

How about imports like in JavaScript?

```typescript
import utils from "utils.v"
```

Or even, as a top level variable:

```v
utils := import("utils.v")
```

Then:

```v
utils.something()
```

**Comment by hazae41** [comment]
We could even import from web

```v
utils := import("https://mycdn.org/utils.v")
```

**Comment by Puzomor** [comment]
Modules can be locally imported
```
└───your_project
    │   main.v
    │   some_other_file.v
    └───modules
        └───module_name
                module_file_1.v
                module_file_2.v
```

only requirement is to have files in a `./modules/module_name` directory.

**Comment by medvednikov** [comment]
How is it complex and rigid?

Local modules are already supported.

`import utils` is much easier than `utils := import("utils.v")` and does not rely on file names.
