### ISSUE TITLE
Array of functions [](fn(voidptr) voidptr) throws syntax error

### ISSUE THREAD

**Issue by hazae41** [vlang/v#4023]
**V version:**  V 0.1.25 cc338df
**OS:** Windows 10

**What did you do?**
```v
struct EventEmitter {
	listeners [](fn(voidptr) voidptr)
}
```

**What did you expect to see?**
No syntax error
 
**What did you see instead?**
syntax error: unexpected `fn`, expecting `name`

**Comment by Ivo-Balbaert** [comment]
This code now ( V 0.1.27 2eac2a5 ) compiles without syntax error on Windows 10.
