### ISSUE TITLE
vfmt2: number literal truncated to i32

### ISSUE THREAD

**Issue by Goodwine** [vlang/v#4026]
**V version:** V 0.1.25 8bfa7f0

**What did you do?**
```vlang
fn main() {
  x := 9999999999
}
```
I ran `v fmt -2 -diff` on that file
**What did you expect to see?**
`Already formatted file: main.v`
 
**What did you see instead?**
```diff
@@ -1,3 +1,3 @@
 fn main() {
-       x := 9999999999
+       x := 2147483647
 }
```

**Comment by RiordanIX** [comment]
I think the correct thing would be to pick one of the following:

- All ints are i64 if not otherwise specified
- Wrap the number in i64(...) if greater then i32 MAX
- Not change any number literals within vfmt2. Let the compiler decide what the number is.

What would be best here?

**Comment by Goodwine** [comment]
vfmt should leave my literals alone, let the compiler fail
