### ISSUE TITLE
make.bat error when compiling con windows

### ISSUE THREAD

**Issue by mp81ss** [vlang/v#4035]
**V version:** 
**OS:** 

Windows 7 64 bit (Probably all windows versions)

**What did you do?**

git clone https://github.com/vlang/v v-master
cd v-master
make.bat

**What did you expect to see?**

Building V
git version 2.25.1.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Now using V to build V...
V build OK!
V 0.1.25 0f16070
 
**What did you see instead?**

Building V
git version 2.25.1.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Now using V to build V...
'v3.exe' is not recognized as an internal or external command,
operable program or batch file.
v.exe failed to compile itself - Create an issue at 'https://github.com/vlang'

**Solution**
The file _make.bat_ contains something like:
```bat
echo Now using V to build V...
v2.exe -o v3.exe cmd/v
v3.exe -o v.exe -prod cmd/v
```
But changing it to:
```bat
echo Now using V to build V...
v2.exe -o v3.exe cmd\v
v3.exe -o v.exe -prod cmd\v
```

Everything went OK

**Comment by vitalyster** [comment]
Looks like it already fixed in master with new self-compile options
