### ISSUE TITLE
json decode error

### ISSUE THREAD

**Issue by daheige** [vlang/v#404]
struct User {
	name string
	age  int
}
 
fn main() {
	data := '{"name":"Frodo","age": 25 }'
	user := json.decode(User, data) or {
		eprintln('Failed to decode json')
		return
	}
	println(user.name)
	println(user.age)
}

$ v run json.v 
!! age 0
/home/heige//.vlang0.0.12//json.c:276:28: error: unknown type name ‘cJSON’
 Option json__jsdecode_User(cJSON* root, User* res) {
                            ^~~~~
/home/heige//.vlang0.0.12//json.c:291:1: error: unknown type name ‘cJSON’
 cJSON* json__jsencode_User(User val) {
 ^~~~~
/home/heige//.vlang0.0.12//json.c: In function ‘json__jsencode_User’:
/home/heige//.vlang0.0.12//json.c:292:1: error: unknown type name ‘cJSON’
 cJSON *o = cJSON_CreateObject();
 ^~~~~
/home/heige//.vlang0.0.12//json.c: In function ‘main’:
/home/heige//.vlang0.0.12//json.c:3750:1: error: unknown type name ‘cJSON’
 cJSON* tmp3 = json__json_parse( data);
 ^~~~~
/home/heige//.vlang0.0.12//json.c:3752:21: error: invalid initializer
 Option_User tmp4 =  json__jsdecode_User(tmp3, &tmp2); cJSON_Delete(tmp3); ; if (!tmp4 .ok) {
                     ^~~~~~~~~~~~~~~~~~~
V panic: clang error

**Comment by musou1500** [comment]
I think https://github.com/vlang/v/pull/412 resolves this issue.
can you try this ?

**Comment by AurelienFT** [comment]
Just need to add `import json` at the start of your code because it's a module not builtin.
