### ISSUE TITLE
cloning specific commits for dependencies

### ISSUE THREAD

**Issue by radare** [vlang/v#4041]
**V version:** V 0.1.25 66adf7a
**OS:** macOS 10.15

**What did you do?**

```
git clone --depth 1 --quiet https://github.com/vlang/vc /tmp/vc
gmake[3]: Leaving directory '/home/build/radare2/test/src/v'
cd /tmp/vc && git clean -xf && git pull --quiet
gmake fresh_tcc
gmake[3]: Entering directory '/home/build/radare2/test/src/v'
rm -rf /var/tmp/tcc
git clone --depth 1 --quiet https://github.com/vlang/tccbin /var/tmp/tcc
gmake[3]: Leaving directory '/home/build/radare2/test/src/v'
cd /var/tmp/tcc && git clean -xf && git pull --quiet
clang  -std=gnu11 -w -o v /tmp/vc/v.c  -lm
./v self
```

**What did you expect to see?**

cloning a specific commit 

**What did you see instead?**

taking vc and tccbin from git is not the right way to handle dependencies because checking out an old commit will not work because the inconsistent versions between each repo

it should use submodules

**Comment by lberrymage** [comment]
It's worth noting that this prevents compilation of many previous versions of `v`, simply because the latest commit of `vc` isn't compatible with said version of `v`. This is a bit of a problem for packagers since the release tarballs won't compile without patching.

**Comment by medvednikov** [comment]
This can now be achieved with the `oldv` tool.
