### ISSUE TITLE
Cannot run v fmt on modules in a directory with different name from the module

### ISSUE THREAD

**Issue by bombsimon** [vlang/v#4047]
**V version:** `V 0.1.25 cff6f4a`
**OS:** macOS 10.15.3

**What did you do?**
Ran `v fmt`.

**What did you expect to see?**
The file to be formatted.
 
**What did you see instead?**
`cannot import module` error

Given the same setup as in #4043 where the `.v` files is in the project root, I cannot run `v fmt` on `my_module.v`.

<details><summary>Click for copy/pate of how to re-create</summary>

```sh
$ mkdir v-test && cd v-test

$ cat > my_module.v <<-EOF
module my_module

fn add(a, b int) int {
	return a + b
}
EOF

$ v -w fmt my_module.v
```
</details>

```sh
$ v -w fmt my_module.v
/var/folders/q3/bf76j42160j2nt4s2tz1_fd40000gn/T/vfmt_tmp_my_module_program.v:1:15: cannot import module "my_module" (not found)
module "my_module" not found in ["/private/var/folders/q3/bf76j42160j2nt4s2tz1_fd40000gn/T", "/private/var/folders/q3/bf76j42160j2nt4s2tz1_fd40000gn/T/modules", "/tmp", "/path/to/v/vlib", "@vmodule"]
    1| import my_module
                     ^
    2| fn main(){}
vfmt error while formatting file: my_module.v .
Encountered a total of: 1 errors.
```

This is resolved by moving the file to a sub directory with the same name as the module.

```sh
$ mkdir -p my_module && mv *.v my_module
$ v -w fmt my_module/my_module.v
Already formatted file: /tmp/v-test/my_module/my_module.v
```

**Comment by RiordanIX** [comment]
I have a fix for this, but do we want an error message printed instead?

**Comment by spytheman** [comment]
A module and the folder that contains it, has to have the *same* name.
In your example, your module is named `my_module` (from the `module my_module` line).
The folder in which it is located, is named `v-test` (from the mkdir && cd line above).

**Comment by spytheman** [comment]
The name of the module file is irrelevant in this case, in fact you can have many .v files in a module folder, and all of them will be part of the same module.
Only the `module XYZ` line at their top, and the folder name matter for the naming of the module.

**Comment by spytheman** [comment]
The current vfmt relies on compiling a mini program, so module resolution has to work, which has the side effect, that your file has to be compilable, and follow the module naming rules.

The new vfmt, which you can try with `v -2 -w fmt yourfile.v` does not have this limitation, and can format arbitrary files in any folder. They would not work when compiling if the module name is != the name of the folder later, but they would be able to be formatted.

**Comment by spytheman** [comment]
Example: 
![vfmt vs vfmt2](https://url4e.com/gyazo/images/fbc415df.png)

**Comment by bombsimon** [comment]
Will try that out, thanks!

Regarding naming, what's the proposed project layout? It seems like a huge limitation to be forced to name the project root (and thus the repository) to the module name. Should the module be placed in a module folder in the project? If I do the latter like this: `v-test/my_module/*.v`, I will not be able to clone that repository and use as a module in another project. Will that be solved with some kind of package management instead?

Regarding compiling, in the current state `v test ./` works but maybe that's going away?

**Comment by spytheman** [comment]
You can name a project however you want. The naming restriction is just for modules.

**Comment by spytheman** [comment]
There will be v.mod (and vpm) support for naming stuff in a different way, but currently, if you want to provide a library as an easily installable module, the names have to match.

**Comment by bombsimon** [comment]
Thank you! I'll name my projects like the module name for third party libraries or use your suggestion with `-2` for code formatting and keep an eye open for proper module support in the future.
