### ISSUE TITLE
Compiler crashes with array on toplevel

### ISSUE THREAD

**Issue by rhysd** [vlang/v#405]
## Repro

Code:

```
a := [1]
println(a[0])
```

1. Save above code as `foo.v`
2. Run `v foo.v`

## Expected

Successfully generates binary which prints `1`

## Actual

`v foo.v` hangs up

## Environment

- macOS 10.12
- V ac66d49 or 889d564

EDIT: Confirmed with 889d564

**Comment by spy16** [comment]
Working as expected for me.

**Comment by rhysd** [comment]
It still occurs with the latest commit 889d564 for me.

**Comment by superwhiskers** [comment]
spams out this when i run it
https://i-got.banned.today/4rF5Y3t.png
i run linux

**Comment by rhysd** [comment]
With optimized build, it just hangs up. But with non-optimized build, it conitnues to dump a lot to stdout.

I took screencast:

![demo](https://user-images.githubusercontent.com/823277/59971794-221a8900-95be-11e9-8671-b472e3b469e0.gif)

**Comment by superwhiskers** [comment]
^ verified this just now

**Comment by spy16** [comment]
Verified this. Weird parsing issue:

With following code i get the above issue: 
```
a := [1]
println(a[0])
```

But if i indent like below:
```
     a := [1]
     println(a[0])
```

i get the following parsing error:

```
a
println

0
pass=1 fn=``
panic: foo.v:2
Fn "println" wrong arg #1. Expected "string" (s)  but got "void"
exit():
```

**Comment by Bowero** [comment]
This works now.
