### ISSUE TITLE
Compile error: cannot convert `string` to `byte`

### ISSUE THREAD

**Issue by keito940** [vlang/v#4052]
**V version:** 0.1.24
**OS:** Windows 10

**What did you do?**

I am trying to define a labeled loop in V(#4005).

**What did you expect to see?**

Compile passes.
 
**What did you see instead?**

Building V
git version 2.25.1.windows.1
Downloading v.c...
Attempting to build v.c with GCC...
Now using V to build V...
vlib\v\parser\parser.v:326:32: cannot convert `string` to `byte`
  324|                                  last := labels.len
  325|                                  if name == labels {
  326|                                          for labels[last] != name {
                                                                           ^
  327|                                                  labels.delete(last)
  328|                                          }
'v3.exe' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
v.exe failed to compile itself - Create an issue at 'https://github.com/vlang'

**Comment by hazohelet** [comment]
This is a valid error message.

In your code, 
`p.loop_label_list` is of type `[]string`
`labels` is of type `string`
`labels[last]` is of type `byte`
`name` is of type `string`

 In V, type `string` is not compatible with type `byte`
