### ISSUE TITLE
Comparison with zig

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [vlang/v#4059]
https://www.reddit.com/r/vlang/comments/atws2u/compare_with_zig_lang/

> Is it possible to add a comparison with Zig Lang (https://ziglang.org/)

> volt_dev
> 4 points ·
> 1 year ago
> 
> I will!
> It'll be on https://vlang.io/compare in a couple of days.

https://vlang.io/compare does not mention zig.

Thanks.

**Comment by milrope** [comment]
zig peoples aren't nice. they ban account for just creating feature request issue. they don't value community.
@andrewk am i right.

**Comment by keito940** [comment]
The biggest disadvantage of the [Zen](https://www.zen-lang.org/)  derived from the Zig is [Binary distribution is charged (Japanese)](https://www.zen-lang.org/ja-JP/blog/2020-08-20/).

**Comment by andrewk** [comment]
> @andrewk am I right?

Suck it.

**Comment by fidergo-stephane-gourichon** [comment]
What a strange conversation. ¯\_(ツ)_/¯

**Comment by ERnsTL** [comment]
Greetings, the comparison with Zig -- also Nim -- would be highly appreciated! Let's get this going again.

**Comment by felixf4xu** [comment]
Although this thread was hijacked by some off-topic messages, the original title is still valid.

`Zig` is claimed to be a "Modern Alternative to the C", but `vlang` might go in the same direction? or maybe no?

**Comment by JalonSolov** [comment]
If you want to learn them both well enough to do a comparison, I'm sure someone would still be interested.  Otherwise, this issue has been closed for a long time.
