### ISSUE TITLE
vweb get request data,sometimes failed

### ISSUE THREAD

**Issue by zhou26192619** [vlang/v#4065]
**V version:** 
V 0.1.25 ac0b235
**OS:** 
manjaro
**What did you do?**
pub fn (app mut App) add_table() {
	app.vweb.add_header('Access-Control-Allow-Origin' , '*')
	println('add_table start == ' + json.encode(app.vweb.form))
	mut table:=json.decode(Table,app.vweb.form['data']) or{
		app.vweb.text('shibai')
		return
	}
	table.sql_name=base64.encode(table.name)
	for i,col in table.detail {
		table.detail[i].sql_name=base64.encode(col.name)
	}
	println('add_table == '+json.encode(table))
	insert_custom_table(table)
	app.vweb.text('jieshu')
}

**What did you expect to see?**

 
**What did you see instead?**
firstline="POST /add_table HTTP/1.1
"
body="{"data":"{\"name\":\"员工2\",\"detail\":[{\"name\":\"姓名\",\"mold\":\"text\",\"mode\":\"input\",\"parent\":\"\",\"parentName\":\"\"},{\"name\":\"住址\",\"mold\":\"text\",\"mode\":\"input\",\"parent\":\"\",\"parentName\":\"\"},{\"name\":\"所属片区\",\"mold\":\"text\",\"mode\":\"input\",\"parent\":\"\",\"parentName\":\"\"}]}"}"
add_table start == {}

i use client post json and urlencoded data,both failed,app. vweb.form has no data .but i post shorter data, successed.

**Comment by zhou26192619** [comment]
urlencoded mode:
firstline="POST /add_table HTTP/1.1
"
body="data=%7B%22name%22%3A%22%E5%91%98%E5%B7%A52%22%2C%22detail%22%3A%5B%7B%22name%22%3A%22%E5%A7%93%E5%90%8D%22%2C%22mold%22%3A%22text%22%2C%22mode%22%3A%22input%22%2C%22parent%22%3A%22%22%2C%22parentName%22%3A%22%22%7D%2C%7B%22name%22%3A%22%E5%B9%B4%E9%BE%84%22%2C%22mold%22%3A%22text%22%2C%22mode%22%3A%22input%22%2C%22parent%22%3A%22%22%2C%22parentName%22%3A%22%22%7D%2C%7B%22name%22%3A%22%E6%89%80%E
5%B1%9E%E5%9C%B0%E5%8C%BA%22%2C%22mold%22%3A%22text%22%2C%22mode%22%3A%22select%22%2C%22parent%22%3A%225YiG5Yy6%22%2C%22parentName%22%3A%22%E5%88%86%E5%8C%BA%22%7D%5D%7D"
add_table start == {}

**Comment by cyclecraze** [comment]
See https://github.com/vlang/v/pull/6270#issuecomment-736180846. This issue seems to be fixed when tested with V 0.1.30 ed39d15.fc8200a.

**Comment by Dialga** [comment]
This can be closed if fixed?
