### ISSUE TITLE
Syntax int_literal..str() has theoretical ambiguity

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#4067]
Please consider the following specific code, what should be the print?
```V
fn str() int { return 10 }
for i in 5..str() {
    println(i)
} 
```
```
// If 5..str() is interpreted as a range, it makes sense:
5 
6 
7
8
9
```
or
```
// If 5..str() in interpreted as float 5. calling .str(), we get a string '5.e+00', so it also makes sense:
5
.
e
+
0
0
```
The problem here is `for i in range` and `for i in string` are both allowed in V. That is to say, the syntax is suffering from ambiguity and a solution must be found.
PR and discussion related: #4049

**Comment by spytheman** [comment]
It already prints what it should print.

**Comment by SleepyRoy** [comment]
I think I should give an update about this issue. 
#4049 has been merged and everything except for this `5..str()` case is nicely solved. But good news is, that PR implemented a not bad solution to it - `5..str()` still means a range from `5` to `str()` as before and if you really want `5.` calling `str()`, use `5.0.str()` as a workaround.
Please comment here if you have a better idea : )

**Comment by crthpl** [comment]
`5..str()` to me looks a lot more like `5 .. str()`, than `(5.).str()`. In this case you should really do `5.0.str()`. Also, you should not have a `str` function - they should always be methods that stringify the reciever.

**Comment by danieldaeschle** [comment]
Can this be closed?
