### ISSUE TITLE
Problems with structs str()

### ISSUE THREAD

**Issue by Naheel-Azawy** [vlang/v#4074]
**V version: V 0.1.25 97fbbac** 
**OS: 5.5.7-arch1-1** 

**Structs**
```v
struct Thing {
    i int
    j int
}
struct Something {
    k int
    l Thing
}
```

**Main 1**
```v
fn main() {
    x := Thing{
        i: 2,
        j: 3
    }
    y := Something {
        k: 1,
        l: x
    }
    println(y)
}
```

**Main 2**
```v
fn main() {
    x := Thing{
        i: 2,
        j: 3
    }
    a := x.str()
    y := Something {
        k: 1,
        l: x
    }
    println(y)
}
```

**Main 3**
```v
fn main() {
    x := Thing{
        i: 2,
        j: 3
    }
    b := '$x'
    a := x.str()
    y := Something {
        k: 1,
        l: x
    }
    println(y)
}
```

**What did you do?**
Tried all of the above `main`s.

**What did you expect to see?**
```
Something {
  k: 1
  l: Thing {
  i: 2
  j: 3
}
}
```
 
**What did you see instead?**
Main 1 and 2 failed complaining that `Thing` has no `str()` and main 3 gave the correct output.
I guess this is because V assumed `str()` was only needed for the directly printed `Something` and not the inner structs of it. Also, it didn't notice that `str()` was needed in main 2 even when it was called.

**Comment by nedpals** [comment]
Closed. Bug has been fixed.
Proof: https://devbits.app/play/iAnjGz7fZa8o
