### ISSUE TITLE
warning: v/vlib/net/http/http.v:170:2: `req` is declared as mutable, but it was never changed

### ISSUE THREAD

**Issue by ianmjones** [vlang/v#4075]
**V version:** V 0.1.25 f37b9d9
**OS:** NixOS (Linux)

**What did you do?**

Compiled app that uses `vweb` module.

**What did you expect to see?**

No warnings.
 
**What did you see instead?**
```
warning: v/vlib/net/http/http.v:170:2: `req` is declared as mutable, but it was never changed
warning: v/vlib/net/http/http.v:175:3: `resp` is declared as mutable, but it was never changed
```

If you use `-prod` during compile it becomes a real problem...

```
v/vlib/net/http/http.v:170:2: `req` is declared as mutable, but it was never changed
  168| }
  169|
  170| fn (resp mut Response) free() {
        ^
  171|  resp.headers.free()
  172| }
```

This started happening a few days ago. As a guess, it's like the compiler was changed to not recognise that freeing a struct member is akin to modifying the struct?

**Comment by serkonda7** [comment]
Works fine with V V 0.1.29 4774c89
