### ISSUE TITLE
What is V Compiler Debuging?

### ISSUE THREAD

**Issue by keito940** [vlang/v#4076]

**Comment by spytheman** [comment]
What do you mean?
You can use gdb to debug v itself, as well as v programs:
`./v -csource keep -cg -o v cmd/v` (if you are on unix, you can use just: `make selfcompile`).
=> this will produce a compiler executable that has more debug information in it.
then you can do:
`gdb --args v yourfile.v`
and so on.
Especially useful for debugging v itself when it panics is placing breakpoints for `v_panic` and `panic_debug` .

**Comment by keito940** [comment]
Thanks. I am using `panic()` debugging
