### ISSUE TITLE
Support local functions

### ISSUE THREAD

**Issue by radare** [vlang/v#4087]
**V version:** V 0.1.25 c12985d
**OS:** macOS 10.15

**What did you do?**

```
$ cat test_local_function.v
fn main() {
	fn local() {
		println('hello world')
	}
	local()
}
$ v run test_local_function.v
```

**What did you expect to see?**

hello world
 
**What did you see instead?**

```
$ v run test_local_function.v
test_local_function.v:2:3: unexpected token: `fn`
    1| fn main() {
    2| 	fn local() {
         ^
    3| 		println('hello world')
    4| 	}
``

**Comment by changrui** [comment]
oh, no! You can use inline functions instead.

**Comment by radare** [comment]
inline functions dont have access to the local variables and the scope is global, so it's not a solution. also this inline attribute doesn't work for local functions either

```
$ v run test_local_function.v
test_local_function.v:2:8: undefined: `inline`
    1| fn main() {
    2| 	[inline]
             	^
    3| 	fn local() {
    4| 		println('hello world')
```

**Comment by r-k-o** [comment]
I asked for that many times and i think it should be implemented.

**Comment by medvednikov** [comment]
it's actually almost completely implemented in the new parser

the syntax is

```
local := fn() {
		println('hello world')
	}
```

**Comment by radare** [comment]
$ v run test_local_function.v
next token = `{`
test_local_function.v:2:16: syntax error: unexpected `)`, expecting `name`
    1| fn main() {
    2| 	local := fn() {
             	        ^
    3| 		println('hello world')
    4| 	}

**Comment by nedpals** [comment]
@radare Like @medvednikov said, it's almost completely implemented so you cannot use it right now (as your error message suggests)

**Comment by radare** [comment]
ok thank you :) let me know when i can help/test.

**Comment by RiordanIX** [comment]
Update: Anonymous functions are in. They don't have local scope, pretty sure that is planned though.
