### ISSUE TITLE
v run hello_world.v              # This runs the program, but doesn't create the executable?

### ISSUE THREAD

**Issue by blueway** [vlang/v#409]
My test result , it generates  `hello_world` file.

**Comment by superwhiskers** [comment]
`hello_world` *is* the executable (`v run <file>` shouldn't create an executable, but it does)

**Comment by superwhiskers** [comment]
if you run linux, you can execute it by running `./hello_world`

**Comment by catastrop** [comment]
This command should compile and run the program. it shouldn't create an executable.

**Comment by superwhiskers** [comment]
yes, but it does for some reason

**Comment by medvednikov** [comment]
Indeed, it does.

But I just thought, it might not be a bad idea. Very often developers might want to quickly run something, but still have the executable.

But then there should a way to run it without generating an executable.

**Comment by catastrop** [comment]
@medvednikov, like

```sh
v test <filename>
```

**Comment by medvednikov** [comment]
Updated readme and help.
