### ISSUE TITLE
Caret (^) used in error indication doesn't respect code indented with tabs

### ISSUE THREAD

**Issue by Anthony-Gaudino** [vlang/v#4095]
**V version:** 0.1.25 79077b0
**OS:** Ubuntu x86_64

When a syntax error occurs a message is displayed and a caret `^` character should be placed under the token related to the error, for example a missing closing `)`.

It seems that by default the caret `^` indentation uses only spaces, if the code is indented with tabs the caret may be placed way before it should appear, see example bellow with a code highly indented with tabs:

```
redefinition of `b`
   17| 		b := 3
   18| 	{
   19| 							b := 1
             	^
   20| 		println(a + b)
   21| 	}
```

Now the same code indented with spaces:
```
redefinition of `b`
   17| 		b := 3
   18| 	{
   19|                             b := 1
                                   ^
   20| 		println(a + b)
   21| 	}
```
 
If the code is indented with tabs the caret must also be indented with tabs to align to the correct token.

**Comment by dumblob** [comment]
Shouldn't `vfmt` solve this?

**Comment by alexesprit** [comment]
It's fixed, but V assumes a tab size always equals 4.

**Comment by medvednikov** [comment]
When printing errors, we can replace tabs with 4 spaces.
