### ISSUE TITLE
optimized v build does not show help message when `help` is passed as an argument

### ISSUE THREAD

**Issue by superwhiskers** [vlang/v#410]
# reproduction
compile v like this
```
v -prod -o v .
```
then run
```
./v help
```
congratulations! you should not see the help message
# specs
os: linux
distro: arch
architecture: amd64
v commit: 889d564f43927dc4fbe15ee8f67cb720776aaf63
# screenshot
![screenshot depicting issue](https://i-got.banned.today/3pp2VTA.png)

**Comment by catastrop** [comment]
does the optimization remove documentation ?

**Comment by superwhiskers** [comment]
potentially, i haven't looked into it though

**Comment by cdunn2001** [comment]
Same as #279. `-prod` suppresses `printf`, which might be related.

**Comment by superwhiskers** [comment]
that sounds like a "feature" that acts like a bug

**Comment by superwhiskers** [comment]
verified
```
	if '-h' in args || '--help' in args || 'help' in args {

		println(HelpText)

		return

	}
```
can this feature be removed as it causes more issues than it could ever fix (please?)

**Comment by medvednikov** [comment]
Yes, I'll fix this "feature" asap.

**Comment by superwhiskers** [comment]
thank you. if i may ask, why was it added in the first place?

**Comment by medvednikov** [comment]
I used lots of println's for debugging.

Fixed.
