### ISSUE TITLE
print_backtrace_skipping_top_frames is not implemented on this platform for now...

### ISSUE THREAD

**Issue by yilmazdurmaz** [vlang/v#4108]
**V version:** 
0.1.24
0.1.23.1
0.1.23

**OS:** 
Windows 10 64bit

**What did you do?**
trying to run even once.
```
v
v install something
v hello.v
v run hello.v
```

**What did you expect to see?**
REPL starts OR prints hello OR install packages OR compiles
 
**What did you see instead?**
1- if source code is fine,  then there is only few seconds of waiting with blinking caret, and just exits with no printing.  no error show, yet does not show life signs either.
2- repl or vpm commands show "print_backtrace_skipping_top_frames is not implemented on this platform for now..."

assuming you have tested your zipped windows version, it should be running in windows but just not supporting everything.
but seeing this error, it is pretty obvious, it either does not work simply which should not be the case, or then you are forgetting to tell which library extras needed to run it.

note: it can export to C code though.

question: is V a language and compiler independent of C compilers? or an interface for C/C++ compilers that has some better dialect than them? because, if second, it means I took the motto wrong.

**Comment by vitalyster** [comment]
V have different backends, when using C backend (most stable) you should have C compiler in %PATH%. Other backend (js, x64) are WIP and mostly not supported on Windows yet
