### ISSUE TITLE
pg orm: How to specify model/struct name, if table name has underscore?

### ISSUE THREAD

**Issue by xucs007** [vlang/v#4118]
It seems current pg orm, doesn't allow to specify model/struct name with underscore,
then how to handle db table name with underscore? Odoo has many table names with underscore, like: product_template, stock_warehouse etc.

**Comment by nedpals** [comment]
@xucs007 Can you share your code or an example code for that situation?

**Comment by xucs007** [comment]
Follow v/examples/database/pg/customer.v, 
but if I write:

struct Stock_Warehouse {
        id int
        name string
}

db.select reports unable to handle underscore.

If I write:
struct StockWarehouse {
        id int
        name string
}

db.select reports unable to find table "stockwarehouse", but odoo in fact 
uses table name: stock_warehouse

**Comment by LouisSchmieder** [comment]
you can add now an attribute to StockWarehouse with the name `tablename` where the arg is the table name e.g.
```
[tablename: 'stock_warehouse']
struct StockWarehouse {...
```
