### ISSUE TITLE
Do not raise a parser error for use of undeclared variable in unused function

### ISSUE THREAD

**Issue by Anthony-Gaudino** [vlang/v#4133]
Executing the following code:

```V
fn main() {                                                                      
    exit(0)                                                                      
}                                                                                
                                                                                 
fn never_called() {                                                              
    println(x)                                                                   
}
```

Causes a parser error even if the function is never used:
```
undefined: `x`
    4| 
    5| fn never_called() {
    6| 	println(x)
             	  ^
    7| }
```

A similar problem occurs bellow:

```V
struct A {
	mut: a byte
}

fn main() {
	exit(0)
}

fn never_called() {
	a := A { a: 1 }
	println(a.b)
}
```

```
type `A` has no field or method `b`
   10| fn never_called() {
   11| 	a := A { a: 1 }
   12| 	println(a.b)
             	    ^
   13| }
```

I think the compiler should be smart enough to not raise a parser error in these cases. Instead it should raise a warning indicating that the function is declare but not used and maybe another warning for the use of the undeclared variable.

I also looked for a compiler option to ignore these kinds of error but didn't find any.

**Comment by spytheman** [comment]
Why should the compiler not complain loudly about that? 
A function that is ill defined because of missing variable definitions *should be an error* in my opinion. V's current behavior in this case is right, and that is NOT a bug, but a feature.

**Comment by medvednikov** [comment]
@Anthony-Gaudino you probably use dynamic languages :)

That's the feature of compiled languages: catch type errors at compilation time.

**Comment by Anthony-Gaudino** [comment]
@spytheman Yes, this would be a feature, I created this issue as a feature request, I don't know why the tag wasn't added to the issue.

-------------

@medvednikov I disagree that in this case this should result in an error.

I know that in most compiled languages this results in an error, but doesn't it seems more interesting that if the function where there is an error like this should just throw a warning since the function will never be executed anyway, continue and finish the compilation so the program could be executed and tested?

Lets see an example of why having a warning instead of an error is a good idea in this case:

```V
// Large 1000 line source file

const (
    MyConst = 100
    ....  // Other constants
)

fn main() {
    do_a();
    do_a();
    do_a();
    do_a();
    do_a();
}
```

**Comment by dumblob** [comment]
@Anthony-Gaudino I think this why *V* has `-prod` and non`-prod` builds. In a `-prod` build this is definitely a compile time error. In a non`-prod` build this could be a warning (pretty much as a warning, that the function is not being used, i.e. is a dead code).

**Comment by Anthony-Gaudino** [comment]
@dumblob This is exactly how I think it should work, but running `v run myprogram.v` which I believe is the `dev` option still produces the error.

I really think this should work like when a variable is declared but not used as in the documentation:

> ```V
> fn main() {
>     age := 21
> }
> ```
> 
> In development mode this code will result in an "unused variable" warning. In production mode (v -prod foo.v) it will not compile at all, like in Go.

So it should only throw an error in `-prod` mode.
As I said this would be very useful during development.
