### ISSUE TITLE
How to print the target file in binary form? 

### ISSUE THREAD

**Issue by TraderChinese** [vlang/v#4135]
0101 kind

**Comment by memeone** [comment]
Can you clarify what you mean by “target file”? Like, do you want to read a binary file in V and output it’s contents represented in base 2?

**Comment by TraderChinese** [comment]
> Can you clarify what you mean by “target file”? Like, do you want to read a binary file in V and output it’s contents represented in base 2?

Yeah.
Doesn't it say that all files on a computer are 0's and 1's? 
![QQ截图22](https://user-images.githubusercontent.com/62389667/77823809-e0b09e80-7138-11ea-8cd3-565e37f82386.png)

**Comment by bokunodev** [comment]
```vlang
fn main(){
	mut number:= 253
	mut bit := 0 
	mut result := []int
	for number > 0 {
		bit    = number % 2 
		number = number / 2 
		result << bit
	}
	println(result)
}
```

**Comment by memeone** [comment]
Another solution using a simple bitshift (like you can do in every other language pretty much). Also this is big-endian fyi, to get little-endian simply reverse the for loop.
```v
import os

fn main() {
	bytes := os.read_bytes('./hello.txt') or { []byte }
	for b in bytes {
		mut i := 7
		for i >= 0 {
			print((b >> i--) & 1)
		}
		println("")
	}
}
```

Other than the [forum](https://forum.vlang.io/) @bokunodev mentioned, you can also join our discord chat at [discord.gg/vlang](https://discord.gg/vlang)

**Comment by TraderChinese** [comment]
> @TraderChinese
> I think its better to ask this question in the [forum](https://forum.vlang.io) instead of github issue
> 
> ```v
> fn main(){
> 	mut number:= 253
> 	mut bit := 0 
> 	mut result := []int
> 	for number > 0 {
> 		bit    = number % 2 
> 		number = number / 2 
> 		result << bit
> 	}
> 	println(result)
> }
> ```

Thank you.

![QQ截图20200329124752](https://user-images.githubusercontent.com/62389667/77840576-aa683300-71bb-11ea-8fde-0b1eabec577f.png)

**Comment by TraderChinese** [comment]
> Another solution using a simple bitshift (like you can do in every other language pretty much). Also this is big-endian fyi, to get little-endian simply reverse the for loop.
> 
> ```v
> import os
> 
> fn main() {
> 	bytes := os.read_bytes('./hello.txt') or { []byte }
> 	for b in bytes {
> 		mut i := 7
> 		for i >= 0 {
> 			print((b >> i--) & 1)
> 		}
> 		println("")
> 	}
> }
> ```
> 
> Other than the [forum](https://forum.vlang.io/) @bokunodev mentioned, you can also join our discord chat at [discord.gg/vlang](https://discord.gg/vlang)

Actually I didn't get it, hahaha, but thanks for the answer.
![QQ截图20200329125643](https://user-images.githubusercontent.com/62389667/77840727-2747dc80-71bd-11ea-8b8c-43a4b8c9d5b4.png)

**Comment by spytheman** [comment]
@TraderChinese what OS and C compiler are you using? It seems to me that print does not work properly for you. Can you try it on win10 with msvc or on linux?

You can also try a modified version of the program that @memeone suggested (it works on my phone): 
```v
import os
fn main() {
        bytes := os.read_bytes('./hello.txt') or { []byte }
        for b in bytes {
                mut i := 7  
                mut line := ''           
                for i >= 0 {
                        line = line + int((b >> i--) & 1).str()
                }
                println(line)
        }                                                  
}
```
