### ISSUE TITLE
Who can give a demonstration of getting JSON from the website?

### ISSUE THREAD

**Issue by TraderChinese** [vlang/v#4136]
https://public-dns.info/nameserver/hk.json

Can JSON get all IP addresses? Is this how it is used?

**Comment by nedpals** [comment]
```v
import json
import http
struct Nameserver {
   ip string
   name string
   country_id string
   city string
   version string
   dnssec bool
   reliability f32
   checked_at string
   created_at string
}

fn main() {
    resp := http.get('https://public-dns.info/nameserver/hk.json')?
    list := json.decode([]Nameserver, resp.text)?
    println(list)
}
```

Please read the [documentation](https://vlang.io/docs#json) for more details.

**Comment by TraderChinese** [comment]
> ```v
> import json
> import http
> struct Nameserver {
>    ip string
>    name string
>    country_id string
>    city string
>    version string
>    dnssec bool
>    reliability f32
>    checked_at string
>    created_at string
> }
> 
> fn main() {
>     resp := http.get('https://public-dns.info/nameserver/hk.json')?
>     list := json.decode([]Nameserver, resp.text)?
>     println(list)
> }
> ```
> 
> Please read the [documentation](https://vlang.io/docs#json) for more details.

//
V 0.1.25 f101e9b
//
import json
import net.http
struct Nameserver {
   ip string
   name string
   country_id string
   city string
   version string
   dnssec bool
   reliability f32
   checked_at string
   created_at string
}

fn main() {
    resp := http.get('https://public-dns.info/nameserver/hk.json')?
    list := json.decode([]Nameserver, resp.text)?
    println(list)
}
//

warning: vlib\net\http\backend_windows.v:18:19: you are calling an unsafe function outside of an unsafe block
warning: vlib\net\http\http.v:170:2: `req` is declared as mutable, but it was never changed
warning: vlib\net\http\http.v:175:3: `resp` is declared as mutable, but it was never changed
12.v:17:49: unexpected token: `?`
   15| fn main() {
   16|     resp := http.get('https://public-dns.info/nameserver/hk.json')?
   17|     list := json.decode([]Nameserver, resp.text)?
                                                       ^
   18|     println(list)

**Comment by TraderChinese** [comment]
Thanks for the answer.
![QQ截图20200329131120](https://user-images.githubusercontent.com/62389667/77840926-f5377a00-71be-11ea-91c7-761f1800f3d0.png)
