### ISSUE TITLE
Win7 often fails to run exe

### ISSUE THREAD

**Issue by TraderChinese** [vlang/v#4137]
**V version:** 
V 0.1.25
**OS:** 
win7 win10
**What did you do?**

Exe compiled on win10

**What did you expect to see?**
run
 
**What did you see instead?**
Win7 often fails to run exe, Win7 doesn't show colors

**Comment by nedpals** [comment]
@TraderChinese  Please state how did you get the result and show the actual output so we can reproduce it.

**Comment by TraderChinese** [comment]
![QQ截图11](https://user-images.githubusercontent.com/62389667/77823489-7b5bae00-7136-11ea-96e9-614fbb3e7dfb.png)

import term
import time
fn main(){
t:=term.rgb(188, 18,8, 'hahahaha')
println(t)
time.sleep(120)
main()
}

**Comment by TraderChinese** [comment]
> @TraderChinese 请说明你是如何得到结果并显示实际产出我们可以复制它。

![](https://user-images.githubusercontent.com/62389667/77823489-7b5bae00-7136-11ea-96e9-614fbb3e7dfb.png)

import term
import time
fn main(){
t:=term.rgb(188, 18,8, 'hahahaha')
println(t)
time.sleep(120)
main()
}

**Comment by nedpals** [comment]
@TraderChinese ANSI color handling is not supported before Windows 10.

See: https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling

**Comment by elbashery** [comment]
Please close this.
