### ISSUE TITLE
v.c generation failed

### ISSUE THREAD

**Issue by yanghao** [vlang/v#4156]
when running the command `./v -o t.c cmd/v/v.v` to translate v to c, it failed. Is this the correct command line?

latest vc repository I guess the generated v.c corresponds to commit  c9eed0b in v repository
```
#define V_COMMIT_HASH "c9eed0b"
#ifndef V_COMMIT_HASH
#define V_COMMIT_HASH "e09447d"
#endif
#include <inttypes.h>

//#include <inttypes.h>  // int64_t etc
//#include <stdint.h>  // int64_t etc

//================================== 1TYPEDEFS
```

I checked out the v repo with commit c9eed0b, build the v compiler, and then translate:

```
make
./v -o t.c cmd/v/v.v
```

But it failed with message:

```
warning: vlib/compiler/main.v:36:14: struct names must have more than one character ("V", len=1, 0)
warning: vlib/compiler/main.v:36:14: struct names must have more than one character ("V", len=1, 0)
cmd/v/v.v:29:51: undefined: `parse_flags`
   27| fn main() {
   28| 	prefs := flag.MainCmdPreferences{}
   29| 	values := flag.parse_main_cmd(os.args, parse_flags, prefs) or {
             	                                           ^
   30| 		println('V Error: An error has occurred while parsing flags: ')
   31| 		println(err)
```

Thanks.

**Comment by bokunodev** [comment]
``./v -o t.c cmd/v/`` 
work fine

**Comment by yanghao** [comment]
Thanks and indeed this worked perfectly fine.

**Comment by medvednikov** [comment]
Also I recommend using the new backend @yanghao 

Results in much nicer C.

`./v -b v2-o t.c cmd/v`

**Comment by yanghao** [comment]
Thanks @medvednikov , the new backend works fine despite the following error during the translation. the code compiles and links.

on the current HEAD (7785583b):

$ ./v -b v2 -o t.c cmd/v
compile2()
build_c(/home/yanghao/.cache/v/t.c.tmp.c)
g_m2_buf
g_m2_ptr
total_m
nr_mallocs
g_ustring_runes
assoc var p typ=0
assoc var v typ=90
assoc var b typ=0
assoc var field typ=0
assoc var f typ=0
assoc var typ typ=157
assoc var typ typ=157
PARSE: 244ms
CHECK: 51ms
cgen.expr(): bad node v_dot_ast__Expr
cgen.expr(): bad node v_dot_ast__Expr
cgen.expr(): bad node v_dot_ast__Expr
C GEN: 106ms
cgen done
