### ISSUE TITLE
Hint: build V with `-prod` for a ~20-40% speed improvement

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#416]
`v -prod -o v .`

This command produces an optimized binary.

**Comment by bitsnaps** [comment]
same result with `vc -prod -o v .` ?

**Comment by medvednikov** [comment]
Yes

**Comment by bitsnaps** [comment]
however the repl doesn't work and no error msg to debug.

**Comment by lnyaa** [comment]
I believe that happens because prod builds skip `println`?

It's a TODO on the compiler to remove that behavior (in theory..? wording is weird around it)

[here's the source for the TODO](https://github.com/vlang/v/blob/d71410dff52a0be1cd26d2129b909419cabe42b3/compiler/main.v#L85)

**Comment by medvednikov** [comment]
> however the repl doesn't work and no error msg to debug.

That was fixed. `git pull`
