### ISSUE TITLE
unable to install on windows10

### ISSUE THREAD

**Issue by sasuke007** [vlang/v#4160]
**V version:**  
**OS:** Windows 10

**What did you do?**
I cloned the repo then ran make.bat 

**What did you expect to see?**
according to instructions, this should install v in my system
 
**What did you see instead?**
but instead, it's showing this error:
GCC: error: unrecognized command line option -municode

This is the full error and command I ran
make -msvc -cg
Building V
git version 2.22.0.windows.1
Downloading v.c...
Attempting to build v.c  with MSVC...
v_win.c
rebuild from source (twice, in case of C definitions changes)
V panic: V tool "E:\Github.com\v\cmd\tools\vself.v" could not be compiled
==================
gcc: error: unrecognized command line option '-municode'
...
==================
(Use `v -cg` to print the entire error message)

V error: C error.

Please make sure that:
- You have all V dependencies installed.
- You did not declare a C function that was not included. (Try commenting your code that involves C interop)
- You are running the latest version of V. (Try running `v up` and rerunning your command)

If you're confident that all of the above is true, please try running V with the `-cg` option which enables more debugging capabilities.
SymFromAddr failure: 487 = Attempt to access invalid address (Verify that you have the .pdb file in the right folder.)
SymFromAddr failure: 487 = Attempt to access invalid address (Verify that you have the .pdb file in the right folder.)
SymFromAddr failure: 487 = Attempt to access invalid address (Verify that you have the .pdb file in the right folder.)
SymFromAddr failure: 487 = Attempt to access invalid address (Verify that you have the .pdb file in the right folder.)
1 : BaseThreadInitThunk         ?? : address= 0000005E3C0FE890
0 : RtlUserThreadStart          ?? : address= 0000005E3C0FE898
I also ran it with option -msvc but then it's showing 
V failed to build itself with error 1
Could Not Find E:\Github.com\v\v.pdb
Could Not Find E:\Github.com\v\v3.ilk
Could Not Find E:\Github.com\v\v3.pdb
Could Not Find E:\Github.com\v\vc140.pdb
Failed to compile - Create an issue at 'https://github.com/vlang' and tag '@emily33901'!
Exiting from error

@emily33901  Please Help

**Comment by keito940** [comment]
I think the cause and remedies are the same as #4188

**Comment by emily33901** [comment]
whats your gcc version?

**Comment by sasuke007** [comment]
no it didnt get fixed
same error again

**Comment by sasuke007** [comment]
@emily33901 my gcc version is 6.3.0

**Comment by sasuke007** [comment]
gcc: error: unrecognized command line option '-municode'
i dont think my gcc has a -municode flag 
i also tried to update it but after that also didnt work

**Comment by medvednikov** [comment]
You should install the latest mingw, there's a link in the readme.

6.3.0 is 4 years old, V works with old GCC versions, but not on Windows.

**Comment by sasuke007** [comment]
It worked Thanks!..
