### ISSUE TITLE
Documentation Run/Copy issues and Play Example issue

### ISSUE THREAD

**Issue by Indribell** [vlang/v#4163]
**1.  https://vlang.io/play**

Example ( JSON decoding/encoding ):

Returns:
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

Solution: ?

**2. https://vlang.io/docs**

`fn main() {
	age = 21
}`

Using Run works perfectly.

But all other examples like Strings, ...

`name := 'Bob'
println('Hello, $name!')  // `$` is used for string interpolation
println(name.len)
bobby := name + 'by' // + is used to concatenate strings
println(bobby) // "Bobby" 
println(bobby[1..3]) // "ob" 
mut s := 'hello '
s += 'world' // `+=` is used to append to a string
println(s) // "hello world" 
`
Will fail because of the lacking "fn main() {}" is not automatically applied.

Solution: Remove the few "fn main() {" from the first documentation examples and automatically add "fn main(){ // CODE// }" to the Javascript that copies the code to the Play section.

**Comment by nedpals** [comment]
Please report this issue to [vlang/website](https://github.com/vlang/website). Thank you.

**Comment by nedpals** [comment]
Oops, nevermind. There is a dedicated issue tag for playground. Apologies.

**Comment by Serkonda** [comment]
I think this can be closed as the playground was exchanged with the wasm-based one.

**Comment by JalonSolov** [comment]
You are correct, the old playground has been closed, and the https://vlang.io/play link now redirects to the wasm playground.
