### ISSUE TITLE
"GOT ARR" printed when using "<-" instead of "in"

### ISSUE THREAD

**Issue by HKGx** [vlang/v#4172]
**V version:** V 0.1.25 5b99007
**OS:** 
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363

**What did you do?**
```v
fn main() {
    for val <- [1, 2, 3, 4] {
        println(val)
    }
}
```

**What did you expect to see?**
```
1
2
3
4
```
 
**What did you see instead?**
```
GOT ARR
1
2
3
4
```

**Comment by HKGx** [comment]
https://github.com/vlang/v/blob/master/vlib/compiler/scanner.v#L687 
Faulty uncommented println.

Though should this syntax be even allowed?

**Comment by SleepyRoy** [comment]
Interesting. I even didn't know the existence of `<-` in V before seeing this.

**Comment by medvednikov** [comment]
This was an experimental syntax. Will be removed today. :)

**Comment by medvednikov** [comment]
Done.
