### ISSUE TITLE
SIGSEGV error on printing mut array

### ISSUE THREAD

**Issue by shubhsherl** [vlang/v#4178]
**V version:** V 0.1.25 e3713de2
**OS:** Arch Linux x86_64
It's weird that if I change an element of the array and then print it, I am getting SIGSEGV error. Instead of printing `arr`, if I print `arr[1]` it works fine. 
**What did you do?**
```
fn main() {
	mut arr := [1,2,3,4,5,6,7,8,9,10]
	arr[1] = 0
	println(arr)
}
```

**What did you expect to see?**
```
[1,0,3,4,5,6,7,8,9,10]
```
 
**What did you see instead?**
```
Terminated by signal 139 (SIGSEGV)
```

**Comment by Anthony-Gaudino** [comment]
**V version:** V 0.1.25 050ec5d
**OS:** Ubuntu x86_64

Also happens with me.

Seems to work in web sandbox.

**Comment by shubhsherl** [comment]
The problem seems in the case when printing of array with zero in it. The following works fine
```
fn main() {
	mut arr := [1,2,3,4,5,6,7,8,9,10]
	arr[1] = 4
	println(arr)
}
```

**Comment by medvednikov** [comment]
Fixed, thanks.
