### ISSUE TITLE
Collision in enum not catched during compilation

### ISSUE THREAD

**Issue by Anthony-Gaudino** [vlang/v#4183]
**V version:** V 0.1.25 050ec5d
**OS:** Ubuntu x86_64

**What did you do?**
Executed this code:
```V
enum Color {
    red,
    green,
    blue = 1
}

fn main() {
    println(Color.red)
    println(Color.green)
    println(Color.blue)
}
```

**What did you expect to see?**
`Error: Collision with previous enumerator!` or `discriminant value '1' already exists` like in [Rust,](https://doc.rust-lang.org/reference/items/enumerations.html#custom-discriminant-values-for-field-less-enumerations) or something similar as enumerators can't have the same value.
 
**What did you see instead?**
```
0
1
1
```

--------------

Example in Rust:

```Rust
enum Color {
    Red,
    Green,
    Blue = 1
}
```

```
error[E0081]: discriminant value `1` already exists
 --> src/lib.rs:4:12
  |
3 |     Green,
  |     ----- first use of `1`
4 |     Blue = 1
  |            ^ enum already has `1`

error: aborting due to previous error
```

**Comment by Ivo-Balbaert** [comment]
This now (v 0.1.27) returns a C error:

C:\Users\CVO\AppData\Local\Temp\v\test.tmp.c: In function 'Color_str':
C:\Users\CVO\AppData\Local\Temp\v\test.tmp.c:1243:3: error: duplicate case value
   case Color_blue: return tos_lit("blue");
   ^~~~
C:\Users\CVO\AppData\Local\Temp\v\test.tmp.c:1242:3: note: previously used here
   case Color_green: return tos_lit("green");
   ^~~~

Capturing this at the V level would solve the issue.
