### ISSUE TITLE
Can't compile news_fetcher example

### ISSUE THREAD

**Issue by AurelienFT** [vlang/v#419]
I'm on fedora and i compile `v news_fetcher.v` and i get this error:
```
cc: error: mac: No such file or directory
V panic: clang error
```

**Comment by medvednikov** [comment]
Can you run it with `v -show_c_cmd news_fetcher.v` please?

**Comment by CoenSchutte** [comment]
I get another error when trying to compile news_fetcher on ubuntu
 `pass=2 fn=`fetch`
panic: news_fetcher.v:36
Fn "exit" wrong arg #1. Expected "int" (code)  but got "string"`

**Comment by AurelienFT** [comment]
@medvednikov 
```
==========
cc -I. -w -g -o news_fetcher /home/afoucault//.vlang0.0.12//news_fetcher.c -lcurl -I$HOME/code/v/thirdpaty/cJSON mac -I$HOME/code/v/thirdpaty/cJSON  -lm -ldl -lpthread
=========

cc: error: mac: No such file or directory
V panic: clang error
```
There is a `mac` in the command mhh

**Comment by kcorey** [comment]
I tried to make a pull request, but couldn't push to the repo.

In json/json_primitives.v, line 8 & 9 should be:
#flag -Dlinux -I$HOME/code/v/thirdparty/cJSON
#flag -Dmac -I$HOME/code/v/thirdparty/cJSON

**Comment by AurelienFT** [comment]
It works but my output with `v -show_c_cmd news_fetcher.v` is:
```
cc -I. -w -g -o news_fetcher /home/afoucault//.vlang0.0.12//news_fetcher.c -lcurl -I$HOME/code/v/thirdparty/cJSON -Dmac -I$HOME/code/v/thirdparty/cJSON  -lm -ldl -lpthread
```
I think is not normal

**Comment by kcorey** [comment]
Well, not sure why you're getting the -I twice on your machine (my output is below), but I don't think it's a show stopper.  It gives the cJSON path to the compiler twice, so when the compiler searches for the .h file it would have two chances to find it.

My output (Mac Mojave, Apple's cc 10.0.1) looks like this:
v -show_c_cmd news_fetcher.v

==========
cc -I. -w -g -o news_fetcher /Users/kcorey//.vlang0.0.12//news_fetcher.c -mmacosx-version-min=10.7 -lcurl -Dmac -I$HOME/code/v/thirdparty/cJSON  -x objective-c
=========

**Comment by AurelienFT** [comment]
Yes but I don't think have two times the link it's a excepted behavior

**Comment by medvednikov** [comment]
Just pushed a fix.

**Comment by AurelienFT** [comment]
The https://github.com/vlang/v/commit/6a28cbdd6ee316e3854a0f654e9f83286b50cef4 fixed it.
I close. Ty @medvednikov

**Comment by medvednikov** [comment]
Perfect, thanks for your input.
