### ISSUE TITLE
V REPL does not seem to work 

### ISSUE THREAD

**Issue by Symmetria** [vlang/v#4193]
**V version: V 0.1.26 1178bfa.unknown** 
**OS: Void GNU/Linux (Project-Trident)** 

**What did you do?**
$ v

**What did you expect to see?**
the V REPL
 
**What did you see instead?**
Running REPL as no arguments are provided.
For usage information, quit V REPL using `exit` and use `v help`.
V panic: V tool "/usr/home/symmetria/v/cmd/tools/vrepl.v" could not be compiled
cgen.expr(): bad node unknown v.ast.Expr
==================
      |                ~~~~~~~^
/usr/home/symmetria/.cache/v/vrepl.tmp.c:8887:24: error: incompatible type for argument 1 of 'array_get'
 8887 |  if ((*(int*)array_get(out, 0)) == screen_columns) {
      |                        ^~~
      |                        |
      |                        array_int * {aka struct array *}
/usr/home/symmetria/.cache/v/vrepl.tmp.c:1629:25: note: expected 'array' {aka 'struct array'} but argument is of type 'array_int *' {aka 'struct array *'}
 1629 | voidptr array_get(array a, int i) {
      |                   ~~~~~~^
/usr/home/symmetria/.cache/v/vrepl.tmp.c:8888:13: warning: passing argument 1 of 'array_set' from incompatible pointer type [-Wincompatible-pointer-types]
 8888 |   array_set(&out, 0, &(int[]) { 0 });
      |             ^~~~
...
==================
(Use `v -cg` to print the entire error message)

V error: C error.

Please make sure that:
- You have all V dependencies installed.
- You did not declare a C function that was not included. (Try commenting your code that involves C interop)
- You are running the latest version of V. (Try running `v up` and rerunning your command)

If you're confident that all of the above is true, please try running V with the `-cg` option which enables more debugging capabilities.
addr2line: Warning: 'v' is a directory
v(+0x4f32) [0x5582ecf9ef32]
addr2line: Warning: 'v' is a directory
v(+0xf9da) [0x5582ecfa99da]
addr2line: Warning: 'v' is a directory
v(+0xfe64) [0x5582ecfa9e64]
                                               | 0x7f5d5c517deb | /usr/lib/libc.so.6(__libc_start_main+0xeb) 
addr2line: Warning: 'v' is a directory
v(+0x26da) [0x5582ecf9c6da]

**Comment by medvednikov** [comment]
Fixed.
