### ISSUE TITLE
println can't print information

### ISSUE THREAD

**Issue by fxqy** [vlang/v#4194]
**V 0.1.24:** 
**OS:window10** 

**What did you do?**
I wantto try vlang on windows, but I have a problem println can't print information

fn main() {
	println('hello world')
}

**What did you expect to see?**
hello world
 
**What did you see instead?**
C:\Users\Dong\Desktop\vlangtest>v helloworld.v

C:\Users\Dong\Desktop\vlangtest>v
print_backtrace_skipping_top_frames is not implemented on this platform for now...

![1111](https://user-images.githubusercontent.com/42601163/78250601-a709da00-7522-11ea-93d3-9fd78d93e763.jpg)

**Comment by krischerven** [comment]
Doesn't occur on Linux (Pop!_OS 19.10)

**Comment by bokunodev** [comment]
command **v hello_world.v** produces a binary file, you must execute the binary file to see the results.

if you want to compile and run it directly use ``v run filename.v``
```v run hello_world.v```

**Comment by Bowero** [comment]
The correct way to execute this, is by running `v run helloworld.v` or by running `v helloworld.v`, after which you run `./helloworld`.

**Comment by fxqy** [comment]
v run helloworld.v
OR
v helloworld.v    ./helloworld

Still can't print information


![8716](https://user-images.githubusercontent.com/42601163/78362146-2c0cf600-75ec-11ea-934b-531cfabb4f7d.jpg)

**Comment by medvednikov** [comment]
You have to build it from source on Windows for now.

**Comment by medvednikov** [comment]
it's as simple as

```git clone --depth 1 https://github.com/vlang/v
make
```

**Comment by fxqy** [comment]
I also had problems compiling, I've cloned it from github, why make still execute git clone
![44346](https://user-images.githubusercontent.com/42601163/78419999-d41ecf80-767d-11ea-8c25-c723efeb469c.jpg)

**Comment by fxqy** [comment]
I executed pacman -S git after the problem seems to solve, and then came a parameter -municode's fault
![7385](https://user-images.githubusercontent.com/42601163/78420265-147f4d00-7680-11ea-8086-4474a13c05e1.jpg)

**Comment by fxqy** [comment]
When I run ‘make’ in mingw64.exe, and i'm done compiling, I can try hello world next.
![3011](https://user-images.githubusercontent.com/42601163/78420474-18ac6a00-7682-11ea-82db-9c53c59e8ad6.jpg)

**Comment by fxqy** [comment]
closed #4194
