### ISSUE TITLE
`#flag linux -I$HOME/code/v/thirdpaty/cJSON #flag mac -I$HOME/code/v/thirdpaty/cJSON`

### ISSUE THREAD

**Issue by blueway** [vlang/v#420]
`thirdpaty` is wrong in file `json/json_primitives.v`, I think the PR should be tested

**Comment by AurelienFT** [comment]
@medvednikov @blueway  https://github.com/vlang/v/commit/6a28cbdd6ee316e3854a0f654e9f83286b50cef4 commit fixed it. You can close it.
