### ISSUE TITLE
importable module redefinition

### ISSUE THREAD

**Issue by Chank1e** [vlang/v#4201]
**V version:** V 0.1.25 050ec5d
**OS:** Linux alexp-pc 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**What did you do?**
import module, for example, `somemodule`. in `main()` redefine it like `somemodule := 'hello world'`
you'll lose somemodule)
![works fine](https://user-images.githubusercontent.com/14954252/78260849-1e317500-7507-11ea-9298-e5e019259999.png)
![wokrs not very nice](https://user-images.githubusercontent.com/14954252/78261009-5638b800-7507-11ea-8a89-b63a72abd693.png)

**What did you expect to see?**
error, like `You can't redefine imported module`
 
**What did you see instead?**
depends on what you put in `somemodule`. If string -> 
![image](https://user-images.githubusercontent.com/14954252/78260996-51740400-7507-11ea-8fa4-27132af0c676.png)

**Comment by memeone** [comment]
Yeah this needs to be fixed. It has screwed me over a couple of times :/

**Comment by medvednikov** [comment]
Hm this is actually module shadowing and it's allowed in V, just like in Go.

I can make the error message clearer.
