### ISSUE TITLE
Regarding the new issues with the compiler

### ISSUE THREAD

**Issue by nedpals** [vlang/v#4209]
As what you have seen in the README, the old backend of the V compiler was removed yesterday in order to give way for the new backend (aka `v2`) which would result in more robust and more cleaner emitted code. Since then, things have been shaky and if you have pulled the new updates, you have seen that there are now lots of errors compared to the old one.

Alex (@medvednikov) and all the other contributors are working hard to stabilize it again on or before the 4th of April and we asked for your patience. You can still submit your issues but keep in mind that what are you using now is the new backend which is being worked on.

If you want to revert to the old backend, please use the prebuilt binaries found at https://vlang.io which includes the source code for the last release.

If you want to know the last commit before the old backend was removed, [here it is](https://github.com/vlang/v/commit/30f306dc1a3c9b0c324b97902fec4048b87efec5).

Thank you.

**Comment by spytheman** [comment]
If you want to see how close v is to full feature parity (at least passing test) with older v, you can run: `v test-fixed` which will print something like:
`ok, fail, skip, total =   101,     0,    46,   147`
Help with making skipped tests pass is highly appreciated. Thanks!

**Comment by madranet** [comment]
> If you want to see how close v is to full feature parity (at least in passing tests) with older v, you can run: `v test-fixed` which will print something like:
> `ok, fail, skip, total = 101, 0, 46, 147`

Am I doing something wrong? I ran `v up` then `v test-fixed` and none of the tests passed.  Am I meant to run `v test-fixed` from a particular directory? I just ran it from `~/`

```
     332 ms <=== total time spent testing all fixed tests
                 ok, fail, skip, total =     0,   105,    43,   147
V panic:
WARNING: failed 105 times.
```

**Comment by spytheman** [comment]
run it in the main v folder @madranet

**Comment by madranet** [comment]
> edit: you can now run it from arbitrary starting folder, it will chdir itself to the correct one before starting the tests.

That's more like it!

```
  28821 ms <=== total time spent testing all fixed tests
                 ok, fail, skip, total =   106,     0,    42,   148
```
