### ISSUE TITLE
Naming variable "char" causes c compiler error

### ISSUE THREAD

**Issue by kizerkizer** [vlang/v#4223]
**V version: V 0.1.24 0d93eeb** 
**OS: macOS** 

**What did you do?**
char := ...

**What did you expect to see?**
Normal program functionality
 
**What did you see instead?**
`V error: C error. This should never happen. 
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
Alexs-iMac:vhll-v $ v -g main.v
C compiler=cc
/Users/Desktop/projects/vhll-v/main.v:10:2: warning: expression result unused [-Wunused-value]
 v_exit ;
 ^~~~~~
/Users/Desktop/projects/vhll-v/main.v:12:7: error: cannot combine with previous 'type-name' declaration specifier
 byte char = tmp2.str[tmp3];
      ^
/Users/Desktop/projects/vhll-v/main.v:12:12: error: expected identifier or '('
 byte char = tmp2.str[tmp3];
           ^
/Users/Desktop/projects/vhll-v/main.v:14:26: error: use of undeclared identifier 'v_char'
 /*opt*/printf ("%d\n",  v_char ) ;
                         ^
1 warning and 3 errors generated.
V error: C error. This should never happen. `

**Comment by fxqy** [comment]
There are 20 basic types in the V language, as follows:

Boolean
bool

String (String)
String

Integer
Signed integers: i8, i16, i32, i64
Unsigned integers: u8, u16, u32, u64
Alias: byte (u8), int (i32), rune (i32, for Unicode code points)

Floats
f32, f64
Please note that, unlike C and Go, int is always a 32-bit integer in the V language.

**Comment by krischerven** [comment]
Doesn't occur on Linux (Pop!_OS 19.10).

**Comment by alexesprit** [comment]
Seems like it was fixed. It works fine for me on V 0.1.26 83289d7. You use a old version.
