### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by vimanuelt** [vlang/v#423]
clang -w -o vc v.c
ld: error: undefined symbol: backtrace
>>> referenced by v.c
>>>               /tmp/v-25b2b3.o:(os__print_backtrace)

ld: error: undefined symbol: backtrace_symbols_fd
>>> referenced by v.c
>>>               /tmp/v-25b2b3.o:(os__print_backtrace)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by joe-conigliaro** [comment]
@vimanuelt? which os?

**Comment by vxlcxn** [comment]
Try compile with ``clang -lexecinfo -w -o vc v.c``.

I assume you're on Freebsd?

**Comment by vimanuelt** [comment]
clang -v -w -o vc v.c
FreeBSD clang version 7.0.1 (branches/release_70 348686) (based on LLVM 7.0.1)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin
 "/usr/bin/clang" -cc1 -triple x86_64-unknown-freebsd13.0 -emit-obj -mrelax-all -disable-free -main-file-name v.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -resource-dir /usr/lib/clang/7.0.1 -w -fdebug-compilation-dir /usr/home/vt/code/v/compiler -ferror-limit 19 -fmessage-length 114 -fobjc-runtime=gnustep -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/v-25898f.o -x c v.c -faddrsig
clang -cc1 version 7.0.1 based upon LLVM 7.0.1 default target x86_64-unknown-freebsd13.0
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/clang/7.0.1/include
 /usr/include
End of search list.
 "/usr/bin/ld" --eh-frame-hdr -dynamic-linker /libexec/ld-elf.so.1 --hash-style=both --enable-new-dtags -o vc /usr/lib/crt1.o /usr/lib/crti.o /usr/lib/crtbegin.o -L/usr/lib /tmp/v-25898f.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/crtend.o /usr/lib/crtn.o
ld: error: undefined symbol: backtrace
>>> referenced by v.c
>>>               /tmp/v-25898f.o:(os__print_backtrace)

ld: error: undefined symbol: backtrace_symbols_fd
>>> referenced by v.c
>>>               /tmp/v-25898f.o:(os__print_backtrace)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by vimanuelt** [comment]
Executing this resolved the issue: clang -lexecinfo -w -o vc v.c
Thank you.

**Comment by vxlcxn** [comment]
I had the same issue, only difference is that I'm on FreeBSD 12-STABLE. You need to explicitly link the ``execinfo`` library whilst compiling V. As posted above:

``clang -lexecinfo -w -o vc v.c``

Theoretically it should hopefully work now.

**Comment by vimanuelt** [comment]
It works fine. Thank you very much.

**Comment by vxlcxn** [comment]
Oh right, awesome. No problem. You may aswell close this issue.

**Comment by vimanuelt** [comment]
Issue was resolve by using: clang -lexecinfo -w -o vc v.c
