### ISSUE TITLE
New array init syntax allowing to set cap and len

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#4230]
```
x := []int{ len: 5, cap: 100, init: 7 }

assert x == [7,7,7,7,7]
assert x.cap == 100
```

**Comment by dumblob** [comment]
1. Is something like this meant to be used also for other built-in structures (e.g. `map`)?

1. Is something like this meant to be used also for *custom* structures (instead_of/complementary_to a `new()` method for efficiency)?

**Comment by medvednikov** [comment]
1. yes
2. no
