### ISSUE TITLE
error: use of undeclared identifier in map

### ISSUE THREAD

**Issue by planmac** [vlang/v#4233]
**V version:** V 0.1.24 0d93eeb
**OS:** MACOS 10.15.3

**What did you do?**
% v -g
V 0.1.24 0d93eeb
Use Ctrl-C or `exit` to exit
>>> mut em := map[string]int
>>> em['one'] = 1
>>> em['two'] = 2
>>> println(em['one'])

**What did you expect to see?**
1
 
**What did you see instead?**
/private/var/folders/5x/kl6v0fx11vn58hhv9drnqby80000gn/T/v/.vrepl.tmp.c:3884:53: error: use of undeclared identifier 'em'
 int tmp1 = 0; bool tmp2 = map_get(/*.vrepl.v : 3*/ em , tos3("one"), & tmp1);...
(Use `v -g` to print the entire error message)

V error: C error. This should never happen.
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by medvednikov** [comment]
Use fn main 

```
fn main() {
mut em := map[string]int
em['one'] = 1
em['two'] = 2
println(em['one'])
}
```

There's another issue about fn main
