### ISSUE TITLE
v.c doesn't compile on Android since glibc specific functions

### ISSUE THREAD

**Issue by daquexian** [vlang/v#425]
Error message:

```
$ cc -w -o vc v.c
v.c:65:10: fatal error: 'execinfo.h' file not found
#include <execinfo.h>
         ^~~~~~~~~~~~
1 error generated.
```

The libc on Android doesn't provide execinfo.h

**Comment by kcorey** [comment]
On Android?  Now that _is_ interesting!

**Comment by mingodad** [comment]
I've got it to build on android with termux commenting out "#include <execinfo.h>" and "backtrace*" in os/mac.v and v.c 
Cheers !

**Comment by medvednikov** [comment]
Good to know it builds on Android, thanks @mingodad 

I'll fix the execinfo.h dependency.

**Comment by medvednikov** [comment]
Fixed.
