### ISSUE TITLE
Home page should mention C -> V translation is not coming until 0.3.

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#4252]
One of the things that got me "excited" about V was the block on the home page talking about C -> V translation.

So I pulled down the project, built it, played with it a bit, then tried to translate a .c file... and got the message that this is coming in 0.3.

I can wait, but it would have been nice to know up front that it wouldn't be available for a while.

**Comment by Vineet-Sharma29** [comment]
@lutherwenxu would like to work on this

**Comment by medvednikov** [comment]
0.3 is out with `v translate`
