### ISSUE TITLE
The UI module could not complete the installation under MINGW64

### ISSUE THREAD

**Issue by fxqy** [vlang/v#4256]
**V version:** 
V 0.1.26 4e01bf4

**OS:** 
win10
MINGW64

**What did you do?**
v up
v install ui

**What did you expect to see?**
ui installed successfully！
 
**What did you see instead?**
# v install ui
V panic: V tool "C:\v\cmd\tools\vpm.v" could not be compiled
["strings", "strconv.ftoa", "strings", "hash.wyhash", "strconv", "net.http", "os", "os.cmdline", "json", "vhelp", "math.bits", "os", "net.urllib", "net.http.chunked"]
vlib\net\http\http.v:230:0: error: unknown module `net_dot_urllib`
TODO: print_backtrace_skipping_top_frames_mingw(2)
print_backtrace_skipping_top_frames is not implemented on this platform for now...

![20200406101304433](https://user-images.githubusercontent.com/42601163/78517396-aa85b580-77ef-11ea-8e0e-465fcde3e6f9.jpg)

**Comment by memeone** [comment]
https://github.com/vlang/v/issues/4209

**Comment by fxqy** [comment]
![20200411195554993](https://user-images.githubusercontent.com/42601163/79042978-a95cea00-7c2e-11ea-939f-cccc9130efdf.jpg)

**Comment by fxqy** [comment]
![20200412100442270](https://user-images.githubusercontent.com/42601163/79058811-26c34180-7ca5-11ea-81b4-39fd7b30a6f1.jpg)

**Comment by leahlundqvist** [comment]
For now you can clone the vlang/ui to ~/.vmodules for now

**Comment by fxqy** [comment]
> For now you can clone the vlang/ui to ~/.vmodules for now

vlang/ui clone to the local how to manually install, I put on the ~/.vmodules can not use

**Comment by fxqy** [comment]
![20200414103543](https://user-images.githubusercontent.com/42601163/79180133-b995e480-7e3b-11ea-8df4-e5109f206306.jpg)

**Comment by fxqy** [comment]
![20200415100325](https://user-images.githubusercontent.com/42601163/79291114-6043b900-7f00-11ea-9ab2-d745f1298fac.jpg)

**Comment by evilcloud** [comment]
Same here.

OS: macOS Catalinа 10.15.3

**Comment by fxqy** [comment]
![20200417104820](https://user-images.githubusercontent.com/42601163/79526959-04606800-8099-11ea-97ab-f4cba29b0b92.jpg)

**Comment by medvednikov** [comment]
Fixed.
