### ISSUE TITLE
[vlib/time] Unix timestamps are 32-bit

### ISSUE THREAD

**Issue by oxy** [vlang/v#4258]
**V version:** master
**OS:** any

**What did you do?**
Read sources of vlib/time/time.v

**What did you expect to see?**
64-bit UNIX timestamps, to avoid the Y2038 bug.
 
**What did you see instead?**
the Time struct uses a 32 bit signed integer time stamp - 32 bit signed integers can only hold timestamps up until the year 2038, and then break afterwards.

**Comment by danieldaeschle** [comment]
u64 should be enough, right?
