### ISSUE TITLE
Cannot compile it on win7_32bit

### ISSUE THREAD

**Issue by aurelVZ** [vlang/v#4260]
**V version:** 
**OS:** 

**What did you do?**
i try compile it on win7 32 bit .-> 530 warnings,540 errors ??

**What did you expect to see?**
I expect to see it sompiled into native pE32 executable file that i can connect my own editor with V
 
**What did you see instead?**

**Comment by vitalyster** [comment]
See https://github.com/vlang/v/issues/4209
