### ISSUE TITLE
Regression: v -cc msvc test-compiler produces errors

### ISSUE THREAD

**Issue by M4SSD35TRUCT10N** [vlang/v#4270]
**V version:** V 0.1.26 4e01bf4.7b41eaf 
**OS:** Windows 10 1909

**What did you do?**
v -cc msvc test-compiler > test.log

**What did you expect to see?**
No errors in the log file.
 
**What did you see instead?**
[test.log](https://github.com/vlang/v/files/4440564/test.log)

**Comment by medvednikov** [comment]
Fixed.
