### ISSUE TITLE
compile error using crypto library hashes?

### ISSUE THREAD

**Issue by bstnbuck** [vlang/v#4281]
**V version:** V 0.1.26 4e01bf4.3c6a4de
**OS:** Ubuntu 19.04

**What did you do?** 
v -cg run sha512_test.v
v -cg run testmd5.v

**What did you expect to see?**
Hex SHA512 Hash 
 
**What did you see instead?**
builder error: C error
--> see attached file

Same error under Windows 10 and with other hash algorithms
I am a complete beginner in V and I regularly develop in Go. Sorry if it's a mistake on my part.
[v_crypto_bugreport.txt](https://github.com/vlang/v/files/4444635/v_crypto_bugreport.txt)

**Comment by alexesprit** [comment]
These tests (and modules) were fixed recently. Now tests are passed.
