### ISSUE TITLE
"v up" builds when it doesn't need to

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#4285]
"v up" will build v whether anything was updated or not.

While it doesn't take long to build it is still "wasting cycles" to build when nothing has changed.

$ v up
Updating V...
From https://github.com/vlang/v
 * branch              master     -> FETCH_HEAD
   7cf9b327..900a18f9  master     -> origin/master
Updating 7cf9b327..900a18f9
Fast-forward
 .editorconfig                               |   3 +
 .github/workflows/ci.yml                    |  18 +--
 cmd/tools/vcreate.v                         |   5 +-
 cmd/tools/vtest-fixed.v                     | 222 ++++++++++------------------
 cmd/v/internal/help/default.txt             |   3 +-
 cmd/v/v.v                                   |   2 +-
 vlib/builtin/string.v                       |  12 +-
 vlib/v/ast/ast.v                            |   1 +
 vlib/v/checker/checker.v                    |  30 ++--
 vlib/v/fmt/fmt.v                            |  54 ++++---
 vlib/v/gen/cgen.v                           |  64 ++++----
 vlib/v/parser/parser.v                      |  21 ++-
 vlib/v/table/table.v                        |  24 +--
 vlib/v/tests/module_test.v                  |  12 +-
 vlib/v/tests/prod/assoc.prod.v.expected.txt |   2 +-
 15 files changed, 221 insertions(+), 252 deletions(-)
Current branch master is up to date.
cd /tmp/vc && git clean -xf && git pull --quiet
cd /var/tmp/tcc && git clean -xf && git pull --quiet
cc  -std=gnu11 -w -o v /tmp/vc/v.c  -lm
./v self
V self compiling...
make modules
make[1]: Entering directory '/home/xxxxx/git/v'
#./v build module vlib/builtin > /dev/null
#./v build module vlib/strings > /dev/null
#./v build module vlib/strconv > /dev/null
make[1]: Leaving directory '/home/xxxxx/git/v'
V has been successfully built
$ v up
Updating V...
From https://github.com/vlang/v
 * branch              master     -> FETCH_HEAD
**Already up to date.
Current branch master is up to date.**
cd /tmp/vc && git clean -xf && git pull --quiet
cd /var/tmp/tcc && git clean -xf && git pull --quiet
cc  -std=gnu11 -w -o v /tmp/vc/v.c  -lm
./v self
V self compiling...
make modules
make[1]: Entering directory '/home/xxxxx/git/v'
#./v build module vlib/builtin > /dev/null
#./v build module vlib/strings > /dev/null
#./v build module vlib/strconv > /dev/null
make[1]: Leaving directory '/home/xxxxx/git/v'
V has been successfully built
$

**Comment by danieldaeschle** [comment]
PR welcome

**Comment by JalonSolov** [comment]
After everything settles down, perhaps.

**Comment by Immortalin** [comment]
This issue can be closed now.

**Comment by JalonSolov** [comment]
Don't know if this will reopen or not, but...
It _was_ working perfectly for the last couple of days, but now it is back to building every time, even though nothing has changed.

```
$ v up
Updating V...
From https://github.com/vlang/v
 * branch              master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
make fresh_vc
make[1]: Entering directory '/home/jamie/git/v'
rm -rf /tmp/vc
git clone --depth 1 --quiet https://github.com/vlang/vc /tmp/vc
make[1]: Leaving directory '/home/jamie/git/v'
cd /tmp/vc && git clean -xf && git pull --quiet
cd /var/tmp/tcc && git clean -xf && git pull --quiet
cc  -std=gnu11 -w -o v /tmp/vc/v.c  -lm
./v self
V self compiling...
make modules
make[1]: Entering directory '/home/jamie/git/v'
#./v build module vlib/builtin > /dev/null
#./v build module vlib/strings > /dev/null
#./v build module vlib/strconv > /dev/null
make[1]: Leaving directory '/home/jamie/git/v'
V has been successfully built
$ v version
V 0.1.26 e1a2a4f
$ v up
Updating V...
From https://github.com/vlang/v
 * branch              master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
cd /tmp/vc && git clean -xf && git pull --quiet
cd /var/tmp/tcc && git clean -xf && git pull --quiet
cc  -std=gnu11 -w -o v /tmp/vc/v.c  -lm
./v self
V self compiling...
make modules
make[1]: Entering directory '/home/jamie/git/v'
#./v build module vlib/builtin > /dev/null
#./v build module vlib/strings > /dev/null
#./v build module vlib/strconv > /dev/null
make[1]: Leaving directory '/home/jamie/git/v'
V has been successfully built
$ v version
V 0.1.26 e1a2a4f
$
```
