### ISSUE TITLE
[FreeBSD] V panic: clang error

### ISSUE THREAD

**Issue by vimanuelt** [vlang/v#431]
When running the following command on FreeBSD, I received a V panic message.

./vc -o v .
ld: error: undefined symbol: backtrace
>>> referenced by v.c:5258 (/home/vt//.vlang0.0.12/v.c:5258)
>>>               /tmp/v-1e603f.o:(os__print_backtrace)

ld: error: undefined symbol: backtrace_symbols_fd
>>> referenced by v.c:5262 (/home/vt//.vlang0.0.12/v.c:5262)
>>>               /tmp/v-1e603f.o:(os__print_backtrace)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
V panic: clang error

**Comment by vxlcxn** [comment]
Related to: #423. You're able build the V compiler from ``v.c``, however unable to use that binary to build V - there's no FreeBSD support. This is an issue that needs to be resolved with ``v.c`` itself, ideally to emit the ``-lexecinfo`` flag when it detects that the host is FreeBSD. 

Similarly, this support would need to be added to V (as above, the preliminary flags omitted to the build flags). I've looked into the code and how it detects the OS and is really hacky. I wouldn't mind providing a patch to offer support, but until things mature I don't really want to touch the codebase.

**Comment by vimanuelt** [comment]
Understood. Thank you.

**Comment by vxlcxn** [comment]
It would be a case of adding FreeBSD (plus all the needed files) and then doing something similar to this: https://github.com/vlang/v/blob/master/compiler/main.v#L472 - but instead ommit the necessary flags (one being ``-lexecinfo``) and only if the host is FreeBSD.

If you want to test V in a Linux environment, you could alternatively setup a Linux VM with the FreeBSD hypervisor ``bhyve`` to play around with until native support is added. Which is what I've been doing, and works great.

**Comment by vimanuelt** [comment]
Thank you for the advice. I'll endeavor towards native FreeBSD support.

**Comment by Elronnd** [comment]
It might be easier to run it in the linuxulator than spinning up a whole vm.

**Comment by Bowero** [comment]
So much has changed with the installation procedure, that I would recommend to try it over completely. If it still does not work, please comment so I can reopen the issue.
