### ISSUE TITLE
question: is the ./v test-compiler supposed to have many failures?

### ISSUE THREAD

**Issue by yanghao** [vlang/v#4316]
Just out of curiosity as I saw many testing are failing on my machine ... do I miss something or this is expected?

**Comment by krischerven** [comment]
Right now the new compiler is failing on a number of tests @yanghao

**Comment by spytheman** [comment]
Yes. It is expected. We are working on fixing all of them, for now you can use `v test-fixed` to see what is already fixed, and what is still skipped.

**Comment by yanghao** [comment]
Thanks @spytheman , this is what I am looking for, a set of test that is passing.
