### ISSUE TITLE
abc.v:14:6: error: unexpected { 

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#4320]
**V version:** V 0.1.26 4e01bf4.320fad4
**OS:** Fedora 31

**What did you do?**
```
module main

enum Kind { name }

struct TOptions {
	a int
}

fn t(options TOptions) {}

fn main() {
	t({ 1 })
}
```

**What did you expect to see?**
no error
 
**What did you see instead?**
```
abc.v:14:6: error: unexpected { 
   12| 
   13| fn main() {
   14|     t({ 1 })
               ^
   15| }
```

**Comment by medvednikov** [comment]
you have to use `{key: val}` syntax with short struct syntax.

**Comment by danieldaeschle** [comment]
ok, but the error is wrong then.. i will fix it.
