### ISSUE TITLE
Missing explicit return not an error

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#4344]
**V version:** 0.1.26

Should no explicit return value be allowed in V?
I know C/C++ will do some kind of magic by returning whatever is the last variable of the same type as the return type defined in the function signature (see below), but sounds like a C hack and an open door to debugging headaches.

# V code
```
module main

pub struct MyStruct {
	pub mut:
	i int
}

pub fn create_struct() &MyStruct {
	m := &MyStruct { i: 14 }
        // No return here
}

fn main() {
	st := create_struct()
	println(st.i)
}
// Outputs '14'
```
**create_struct** does not return anything, yet not only there is no error but it seems st is valid.

# Magic C code for create_struct function
```
MyStruct* create_struct() {
	MyStruct* m = (MyStruct*)memdup(&(MyStruct){	.i = 14,
	}, sizeof(MyStruct));
       // No return magic
}
```

**Comment by medvednikov** [comment]
Fixed.


```
missing return at end of function `create_struct`
```
