### ISSUE TITLE
Allow importing from the REPL.

### ISSUE THREAD

**Issue by zac-garby** [vlang/v#435]
<img width="816" alt="Screenshot 2019-06-23 at 11 33 53" src="https://user-images.githubusercontent.com/19708658/59974991-cd214780-95aa-11e9-9201-0d02ef0b003f.png">

On a brand new install. I get a parse error when trying to import something, saying that it didn't expect the token "import". I presume this is only an issue in the REPL, but is it intentional?

**Comment by medvednikov** [comment]
No. Will fix today.

**Comment by zac-garby** [comment]
Cool, thanks

**Comment by saevarb** [comment]
This is the code that drives his REPL: https://github.com/vlang/v/blob/99c781bf07884424975ba2030eb50cf545adf99f/compiler/main.v#L798

It's literally just doing copy/paste-like string manipulation to write the code to a file and build it on the fly. His approach is so naive that it will be impossible for him to extend it in any meaningful way without it becoming an even bigger mess. I wouldn't get your hopes up.

**Comment by ntrel** [comment]
@zac-garby unless Alex has said otherwise, I think it's best to leave issues open until they're actually fixed.

**Comment by zac-garby** [comment]
Good point

**Comment by medvednikov** [comment]
Fixed
