### ISSUE TITLE
string interpolation has weird behaviour

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#4363]
**V version:** 0.1.26
**OS:** Fedora 31

**What did you do?**
```v
test := 'hello'
hello := 'world'
println('%.*s$hello$test')
```

**What did you expect to see?**
`%.*sworldhello`
 
**What did you see instead?**
`<�rldhello�`

**Comment by yuyi98** [comment]
`%.*s` conflict with formatted placeholders used in c internally.

**Comment by danieldaeschle** [comment]
yes, but it should be fixed either... with an escape
