### ISSUE TITLE
Operator Overloading for all relationship operators

### ISSUE THREAD

**Issue by Delta456** [vlang/v#4365]
As we now have support for all mathematical operators i.e. `+` , `-`, `%`, `*` and `/`. I feel that we should also have support for relationship operators. It will be more easier to conduct tests between `struct` and usually in Scientific areas comparison is a lot needed. There are `<`, `>`, `==`, `!=` overloaded for string so we can use make these public.

**Syntax** 
```v
struct Point {
   x int
   y int
}

(p Point) eq (p2 Point) bool {
    return p.x == p2.y && p.y == p2.y 
}

(p Point) nq (p2 Point) bool {
    return !(p == p2)
}

... // Other operators etc

fn test() {
assert Point{3, 5} == Point{3, 5}
assert Point{7, 4} != Point{3, 2}
assert Point{2, 5} < Point{3, 5}
assert Point{4, 3} > Point{5, 7}
}
```

What do you guys think?

**Comment by spytheman** [comment]
What does Point{2, 5} < Point{3, 5} mean? 
Can 2d points be ordered?

**Comment by Delta456** [comment]
@spytheman I am comparing them on the basis of [Distance Formula](https://www.chilimath.com/lessons/intermediate-algebra/distance-formula/).

**Comment by Delta456** [comment]
@spytheman It just compares `p.x < p2.x` and `p.y < p2.y`.

**Comment by medvednikov** [comment]
I'm a bit hesitant to do `struct1 == struct2` overloading, because unlike `+, -` etc, `==` works out of the box. So the behavior of `==` is not going to consistent and predictable.

**Comment by RiordanIX** [comment]
@Delta456 shouldn't it be `p.x * p.x + p.y * p.y < p2.x * p2.x + p2.y * p2.y`? (Note: no need for sqrts when |x| > 1 and |y| > 1)

So for two structs, does `==` compare every field in the struct already by default?

**Comment by Delta456** [comment]
@RiordanIX I just gave an example like that and yeah this can be possible to compare.

**Comment by medvednikov** [comment]
> So for two structs, does == compare every field in the struct already by default?

Not yet, but it will. I think it worked in V1.

**Comment by x0r19x91** [comment]
I agree with @Delta456

**Comment by milrope** [comment]
i don't understand
>assert Point{2, 5} < Point{3, 5}
assert Point{4, 3} > Point{5, 7}

what does it mean?
(5, -2) and (5, 2) have same distance form origin (0,0). but your proposal will make one smaller than other.

**Comment by Delta456** [comment]
> 
> 
> i don't understand
> 
> > assert Point{2, 5} < Point{3, 5}
> > assert Point{4, 3} > Point{5, 7}
> 
> what does it mean?
> (5, -2) and (5, 2) have same distance form origin (0,0). but your proposal will make one smaller than other.

I just gave an example of how overloaded operators will work not thinking about the actual logic. I will edit the main post so that people wouldn't say anything .

**Comment by Delta456** [comment]
Now `==` and `!=` are implemented in  https://github.com/vlang/v/pull/7639

I think I will work on implementing the rest 🙂

**Comment by Delta456** [comment]
`<` and `>` are also now implemented in https://github.com/vlang/v/commit/24b18f05c4e7e55b5fba174bd58db5b19dc73d48.
