### ISSUE TITLE
Regression: arithmetic assignment ops on unsuitable types should give error 

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#4392]
**V version:** 
latest master - 0.1.26 a6100be (with mingw64)

**OS:** 
win10

**What did you do?**
Test some arithmetic assignment ops on unsuitable types, e.g. `bool += bool`.

**What did you expect to see?**
Give an error.
 
**What did you see instead?**
No error.

**NB** In V1 only the following are allowed.
1. `+=`, `-=`, `*=`, `/=` on two numeric types (and `+=` on two strings as an exception)
2. `%=`, `<<=`, `>>=`, `&=`, `|=`, `^=` on two integer types

**Comment by medvednikov** [comment]
Fixed:

```
bool types only have the following operators defined: `==`, `!=`, `||`, and `&&`
```

Still need to do a couple of other checks.
