### ISSUE TITLE
webassembly

### ISSUE THREAD

**Issue by HedariKun** [vlang/V#44]
will it be able to compile to webassembly?

**Comment by medvednikov** [comment]
Yes, hopefully this year.

**Comment by medvednikov** [comment]
For now it's possible to compile V => C => WebAssembly.

**Comment by syrusakbary** [comment]
Any updates on this? :)

**Comment by medvednikov** [comment]
It's definitely not a priority, so not before 1.0 release @syrusakbary, unless someone is willing to work on this.

**Comment by syrusakbary** [comment]
No worries, thanks for the update!
