### ISSUE TITLE
All examples, including V Tetris now work!

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#440]
Thanks to everyone for their contributions.

<img width="352" alt="Screen Shot 2019-06-23 at 13 20 50" src="https://user-images.githubusercontent.com/687996/59975578-d36af000-95b9-11e9-8b69-77897f4adccc.png">

**Comment by bitsnaps** [comment]
Great! couldn't compile tetris, I think some thirdparties need to be included: `KHR/khrplatform.h"`, `ft2build.h`, `ftheader.h`, freetype2 lib... (couldn't find any of them on mac at `/usr/local/`)

**Comment by medvednikov** [comment]
@bitsnaps 
https://github.com/vlang/v#running-the-examples


```
Ubuntu:
sudo apt install glfw libglfw3-dev libfreetype6-dev libcurl3-dev

macOS:
brew install glfw freetype curl
```

I'll fix the KHR thing.

**Comment by galvez** [comment]
```
$ v run tetris.v
In file included from /Users/jonas//.vlang0.0.12//tetris.c:61:
/Users/jonas/code/v/thirdparty/glad/glad.h:89:10: fatal error: 'KHR/khrplatform.h' file not found
#include "KHR/khrplatform.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
V panic: clang error
```

**Comment by MostHated** [comment]
```
sudo apt install glfw
```
This didn't work for me on Ubuntu. Said not found. I had to use:

```
sudo apt install libglfw3 libglfw3-dev 
```

**Comment by 1l0** [comment]
Error on macOS Mojave:
```sh
$ v run tetris.v
In file included from /Users/res//.vlang0.0.12//tetris.c:61:
/Users/res/code/v/thirdparty/glad/glad.h:89:10: fatal error: 'KHR/khrplatform.h' file not found
#include "KHR/khrplatform.h" 
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
V panic: clang error
```

**Comment by S-YOU** [comment]
Confirmed that current master can compile seamlessly on OSX for Tetris.

https://github.com/vlang/v/issues/393

**Comment by lixia9** [comment]
Error on macOS:

`lixiaolong:tetris lixiaolong$ v run tetris.v
/Users/lixiaolong//.vlang//tetris.c:76:10: fatal error: 'glad.h' file not found
#include "glad.h"
         ^~~~~~~~
1 error generated.
V panic: clang error`

**Comment by lixia9** [comment]
Error on macOS :

`lixiaolong:tetris lixiaolong$ v run tetris.v
/Users/lixiaolong//.vlang//tetris.c:76:10: fatal error: 'glad.h' file not found
#include "glad.h"
         ^~~~~~~~
1 error generated.
V panic: clang error`

**Comment by nedpals** [comment]
@lixia9 try `git pull` again

**Comment by since2014** [comment]
Found error on macOS same as @lixia9

**Comment by lixia9** [comment]
git pull  ----->   error  no change
![image](https://user-images.githubusercontent.com/5379668/60078598-d18e6180-975e-11e9-8e74-3775d954f5f8.png)

**Comment by Chamberlain91** [comment]
I can confirm that `tetris.v` ran with WSL 2 on software mesa rendering and vcxsrv :)

**Comment by amcquade** [comment]
Tetris still not compiling on macOS Mojave:

`[~/v/examples/tetris] aaron *master ?* v run tetris.v `
`/Users/aaron//.vlang//tetris.c:79:10: fatal error: 'ft2build.h' file not found`
`#include "ft2build.h"`
        ` ^~~~~~~~~~~~`
`1 error generated.`
`V panic: clang error`

**Comment by bitsnaps** [comment]
> `#include "ft2build.h"`
@amcquade make sure you've installed glfw:
`brew install glfw freetype curl`

**Comment by amcquade** [comment]
@bitsnaps same error even after reinstalling

**Comment by medvednikov** [comment]
I'll release `v up` tool today to make updating V easier.
