### ISSUE TITLE
Where is UI library?

### ISSUE THREAD

**Issue by zenith391** [vlang/v#442]

**Comment by medvednikov** [comment]
It's in a separate repo, not released yet.

https://github.com/vlang/v/ui

**Comment by medvednikov** [comment]
I'll release it in a couple of days.

**Comment by zenith391** [comment]
Ok thanks you

**Comment by jozanza** [comment]
I'm really excited for this lib :)

**Comment by MostHated** [comment]
I would be interest to see if anything might be able to be done with V and this. https://ultralig.ht/

**Comment by zenith391** [comment]
Actually maybe i will create a _ALTERNATIVE_ UI library, looking more like Swing/JavaFX for Java (same design for all platforms)
