### ISSUE TITLE
why you are using left shift operator for appending to a vector

### ISSUE THREAD

**Issue by mobop** [vlang/v#4426]
that is not a good idea. it misuses the symbol.

**Comment by sudo-nice** [comment]
An operator meaning can change, depending on the operands:
```v
1 + 1 = 2
'1' + '1' = '11'
```
IMO, nothing weird with using `<<` to append an item into array. Some other languages (Ruby, Crystal) do the same.

**Comment by aggsol** [comment]
What would be the correct use of the symbol then?

**Comment by nedpals** [comment]
Hi @mobop, can you elaborate your reasons for disliking this syntax? Like the other people have commented in this thread, this type of syntax is not new (was used originally in Ruby) and haven't heard any issues about it.

**Comment by mobop** [comment]
closing. i don't want to impose my personal thought on a language design. He are doing great. He will decide what to do.
@medvednikov what's your opinion.

**Comment by mobop** [comment]
reopened to discuss

**Comment by varuzam** [comment]
Ruby has very specific syntax. I would prefer more common syntax like v.append(1, 2,..) or v.add(3,4,..)

**Comment by mobop** [comment]
yay , i think so

**Comment by medvednikov** [comment]
The reason for a separate operator is because it's a very frequently used operation, much more frequent than % and probably even /, which are operators.

Arrays are builtins in V, like ints and strings, so using an operator is natural.

I think it's much cleaner:

```
users << User{
  name: name
  age: age
}

users.push(User{
  name: name
  age: age
})
```

**Comment by varuzam** [comment]
1. The operator is used as bitwise left shift. Using it for appending in a
vector may confuse. Imho it decreases readability a code.
Example:
If V is defined farly from appending.
V.append(1) is definitely says that V is an vector or a container.
V << 1, hmm, is the V a vector or something else? Looking for the place
where it is initialized.
More efforts than above to understand the code.

2. In our multilanguage world, when a developer uses many languages it is
more convinient to have more  common syntax. I, personally, writes a little
code but  reads a lot (c/c++, go, java, php, python, bash, even Ruby ,
which seems to me as klingone language   after the first ones)

**Comment by mobop** [comment]
@medvednikov i don't want to convince you

**Comment by aggsol** [comment]
> 
> 1. The operator is used as bitwise left shift. Using it for appending in a vector may confuse. Imho it decreases readability a code. Example: If V is defined farly from appending. V.append(1) is definitely says that V is an vector or a container. V << 1, hmm, is the V a vector or something else? Looking for the place where it is initialized. More efforts than above to understand the code. 2. In our multilanguage world, when a developer uses many languages it is more convinient to have more common syntax. I, personally, writes a little code but reads a lot (c/c++, go, java, php, python, bash, even Ruby , which seems to me as klingone language after the first ones)

If I were designing a language for myself, I would drop everything and would it make good for me. I assume that is were @medvednikov started. There is no need to build on the languages before, there are so many of them already. IMHO a programming language needs to work for the coder first.

**Comment by mobop** [comment]
ok
