### ISSUE TITLE
Remove hardcoding from compiler

### ISSUE THREAD

**Issue by protonesso** [vlang/v#443]
Hi, I was interested in your project. I saw the source of your compiler.

Excuse me, but this https://github.com/vlang/v/blob/master/compiler/main.v#L495 is stupid. Why there is a hardcoding for clang and dynamic linker? Okay, it can find clang binary automatically, but how can I use your compiler on musl systems for example? Clang can automatically detect Linc, their crts and etc.

**Comment by medvednikov** [comment]
Please be respectful. That code is ugly, but it's only supposed to work on my machine. I'll fix cross compiling for everyone by tomorrow.

**Comment by protonesso** [comment]
Thanks
