### ISSUE TITLE
Can you clarify this line please?

### ISSUE THREAD

**Issue by stefanos82** [vlang/v#444]
https://github.com/vlang/v/blob/56ceccfea5d7ee29caee7328583a981a81f73546/os/os.v#L383

Is this aforementioned line using the system's `unzip` command?

If yes, what makes you think that all UNIX-like operating systems have it installed by default?

Debian for instance does not and you have to install it yourself.

Also, why are you deploying such dangerously insecure practices? I don't get it...

**Comment by medvednikov** [comment]
Yes, it's a terrible decision, it will be removed.

**Comment by medvednikov** [comment]
Removed.
