### ISSUE TITLE
"v up" back to compiling every time.

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#4441]
Reported in #4285, it was fixed 3 days ago, but back to original behavior starting last night.

**Comment by alexesprit** [comment]
> but back to original behavior starting last night.

It wasn't fixed properly, I think.

`v up` works fine, if V is built via `make`. When v is self updated via `v self` and has two different hashes in its version (e.g. `V 0.1.26 182108f.051cc73`) `v up` runs `make` for update anyway.

**Comment by alexesprit** [comment]
@JalonSolov how is your remote named? Mine is `upstream` for this repo, so, probably that's why I have the same issue, but it's hard to reproduce for me.

**Comment by JalonSolov** [comment]
$ git remote show origin
* remote origin
  Fetch URL: https://github.com/vlang/v
  Push  URL: https://github.com/vlang/v
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
$

**Comment by alexesprit** [comment]
Looks like `vup` executable isn't rebuilt on `v up` command, so `util.githash` used in `vup` returns outdated commit hash.

**Comment by JalonSolov** [comment]
Of course, it would be _really_ nice if it only rebuilt on code changes.  For example, the most recent commit only modified docs/docs.md, which doesn't really require rebuilding v.

However, v rebuilds so fast it really doesn't matter.  :-)

**Comment by alexesprit** [comment]
It's still an issue for Windows users, where almost every `v up` commands executes `make.bat` (even if V is up-to-date), so it takes about 30-60 depends on hardware.

**Comment by JalonSolov** [comment]
It's still an issue for me on Linux with fast hardware.  Not horrendous, but still quite a bit slower than the advertised "<1 second"...

```
$ time v up
Updating V...
From https://github.com/vlang/v
 * branch              master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
cd /tmp/vc && git clean -xf && git pull --quiet
cd /var/tmp/tcc && git clean -xf && git pull --quiet
cc  -std=gnu11 -w -o v /tmp/vc/v.c  -lm
./v self
V self compiling...
warning: import cycle detected between the following modules:

 * v.table -> v.ast
 * v.ast -> v.table
make modules
make[1]: Entering directory 'v'
#./v build module vlib/builtin > /dev/null
#./v build module vlib/strings > /dev/null
#./v build module vlib/strconv > /dev/null
make[1]: Leaving directory 'v'
V has been successfully built

real    0m4.699s
user    0m3.587s
sys     0m0.096s
$
```

I know, I know... "[First World Problems](https://www.youtube.com/watch?v=bwvlbJ0h35A)".  :-)

**Comment by spytheman** [comment]
> still quite a bit slower than the advertised "<1 second"...
The 'Compiles itself in <1s with zero dependencies' claim is just for self compilation, i.e. `./v self`.
`v up`, does several more things, some of which require network operations and thus they can take much longer, which is something that is not under v's control.

**Comment by JalonSolov** [comment]
Understood, and yes, I realized the timing thing after I entered that comment, which was unfair to v.
