### ISSUE TITLE
I have an issue

### ISSUE THREAD

**Issue by VioletasTheThird** [vlang/v#445]
Lol can you stop banning people from the discord? We aren't "trolls", we are pointing out actual flaws in your language and you need to accept there are flaws and fix them instead of shutting us down if you want your language to improve in any way.

**Comment by LouCle** [comment]
@medvednikov

**Comment by medvednikov** [comment]
When you post things like "LMAO what kind of language is this" and lies like saying I've kept delaying the release of the language, when I've delayed it once by 2 days, you get banned, sorry.
