### ISSUE TITLE
Test count still off somewhere.

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#4475]
Commit eb923b4995dde8cef72d2a1033f3c4d9fe274837 has a comment that says it fixed the test count, however, running 'v test-fixed' ends with this:

```
OK    3507 ms [147/157] vlib/v/parser/parser_test.v
OK     966 ms [148/157] vlib/os/cmdline/cmdline_test.v
OK    1226 ms [149/157] vlib/math/complex/complex_test.v
OK    6736 ms [150/157] vlib/v/tests/inout/compiler_test.v
--------------------------------------------------------------------------------------------------------------------------------
    6742 ms <=== total time spent testing all fixed tests
                 ok, fail, skip, total =   126,     0,    31,   157
```

So... where are the other 7?

There were actually only 150 lines of output, and only 28 of them show as "SKIPPED", so somehow the totals are still being calculated incorrectly.

**Comment by RiordanIX** [comment]
This is what I get. Do you have the latest V? If not, what is the V version? (`v -v`)
```
OK    1442 ms [152/157] vlib/os/inode_test.v
SKIP     0 ms [153/157] vlib/regex/regex_test.v
OK    1422 ms [154/157] vlib/os/cmdline/cmdline_test.v
OK    1525 ms [155/157] vlib/os/os_test.v
OK    1328 ms [156/157] vlib/os/environment_test.v
OK    1319 ms [157/157] vlib/sync/pool_test.v
----------------------------------------------
   55981 ms <=== total time spent testing all fixed tests
                 ok, fail, skip, total =   126,     0,    31,   157
```
Your machine is way faster than mine

**Comment by JalonSolov** [comment]
$ v -v
V 0.1.26 eb923b4
$

AMD Threadripper Gen 1 with lots of RAM, running this on Ubuntu Linux in WSL 2 on Windows.

**Comment by RiordanIX** [comment]
Thats the same version I've got too. What happens when you do `v self`, then try it again?

I'm on an X220, kind of slow and old but super comfortable.

**Comment by bokunodev** [comment]
i didn't understand what the issue here ?
I have tried redirect the output to a text file and open it with a text editor.
![Screenshot_2020-04-18_20-40-10](https://user-images.githubusercontent.com/54968427/79639331-775f0100-81b5-11ea-8975-79551cb6d2f2.png)

**Comment by RiordanIX** [comment]
@bokunodev I don't understand what you mean with that screenshot. Showing that it works for you? It's not showing up for @JalonSolov , it's possible it's some strange bug with threading on AMD systems.
Is it consistently only showing 150 tests @JalonSolov ? or do the numbers change?

**Comment by JalonSolov** [comment]
@RiordanIX I get the same output after 'v self'.

@bokunodev the issue is that when I run 'v test-fixed', it only shows 150 tests, with 28 of them skipped, but the totals at the end show 157 tests with 31 skipped.

**Comment by bokunodev** [comment]
@JalonSolov 
maybe running the "v up" command can help.

**Comment by RiordanIX** [comment]
hmm. Here's the list of all the tests alphabetized. When you run it, which tests are missing and are the same tests consistently missing? Thanks!
[tests.txt](https://github.com/vlang/v/files/4496725/tests.txt)

**Comment by JalonSolov** [comment]
I run 'v up' every time I see there's been a change.  I have run it more than once this morning, even though there haven't been any changes recently, just to be sure.

@RiordanIX actually, I take that back.  After a fresh 'v up', it has been consistently 150.  After the 'v self', the number has be fluctuating. between 148 and 156, just running 'v test-fixed' multiple times in a row, but the totals at the bottom have been the same every time.

**Comment by RiordanIX** [comment]
I think I see the problem, haven't tested a fix for it yet though. in the function
`fn worker_trunner(p mut sync.PoolProcessor, idx int, thread_id int) voidptr {`
there are a few times a message is appended to the messages in the TestMessageHandler:
`ts.message_handler.messages << tls_bench.step_message_fail(relative_file)`
Since my machine is so slow, it'd be rare to have this race-condition, but of course a faster machine could see it more regularly. I'll write a fix and could you apply a patch if I send it to you @JalonSolov ?

**Comment by RiordanIX** [comment]
I just added a method with a lock. Can you tell me if this works?
[test_lock_fix_patch.txt](https://github.com/vlang/v/files/4496792/test_lock_fix_patch.txt)
I had to make it a .txt file because github won't let me upload patches.
All you should have to do is put that in the `v` directory and do `git apply test_lock_fix_patch.txt`.

**Comment by JalonSolov** [comment]
That fixed it for me.  I show 157 tests every time with that fix.

**Comment by RiordanIX** [comment]
Excellent! I'll make a PR with this. You'll want to `git checkout -- cmd/tools/modules/testing/common.v`, I'm going to make a couple more changes and you'll git a conflict when it gets merged.
Thanks for the Report and helping test!

**Comment by JalonSolov** [comment]
Any time!  I want to get more involved, but am waiting until things settle down - the code keeps changing before I can get a handle on it.  :-)

**Comment by RiordanIX** [comment]
Yeah, it's still kind of a moving target right now. It's fun to be here in still early days though. If you find any more issues or have any fixes we'd love to have them!

**Comment by JalonSolov** [comment]
I've been adding issues and commenting on others for a few days, at least.  :-)

Never heard of discord before this project.  Only brought it up in the browser once, but I may take a closer look.

**Comment by medvednikov** [comment]
Should be fixed now.

**Comment by JalonSolov** [comment]
It is.  Thanks!
