### ISSUE TITLE
Provide a good scanner/parser/checker api

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#4477]
The api of scanner, parser and checker are a little bit complicated right now.
They should be simple to use and don't print something to stdout. Instead they should return warnings and errors that third party tools like a language server or vfmt can do something with them.

**Comment by nedpals** [comment]
Closed. #4807 fixes the issue by storing problems to the parser and use it for later.

In my opinion, it's better to study the usage of it instead since designing a better API for outside is hard and there are situations that it needs the extensive configurability to get the desired result :)
