### ISSUE TITLE
String interpolation formatting has unexpected behavior

### ISSUE THREAD

**Issue by RiordanIX** [vlang/v#4481]
**V version:** V 0.1.26 182108f.eb923b4
**OS:** Debian 10

**What did you do?**
```v
import math
fn main() {
	f := 5
	println("${f:3d}")
	println(f)

	println("${math.sqrt(f)}")
	println("${f:f}")
	println("$f")
}
```

**What did you expect to see?**
```
  5
5
2.23607
    5
5
 ```
**What did you see instead?**
```
  5
5
2.23607
2.236068
5
```

For some reason, interpolation where `:` is followed by a variable displays some other value, usually one that was computed previously.

**Comment by sambeckingham** [comment]
V 0.1.26 bc4a576
Windows 10

Running the above code for me now returns
```
  5
5
2.23607
0.000000
5
```

Is there documentation on the formatting strings and their intended behaviour anywhere?

**Comment by RiordanIX** [comment]
f is an integer, but should we be able to have variable padding? I also tried `"${f:${f}d}"` which you would expect would work, but gives
```
error: unexpected `$2`, expecting `,` 
    1| fn main() {
    2|     f := 5
    3|     println("${f:${f}d}")
                        ^
    4| }
```
something's not working correctly at the very least. if `f` is an invalid formatting tag I don't think it should compile. Anyways, there should be some way of having variable formatting instead of hard-coded formatting. Maybe this will come from the `printf` implementation coming.

**Comment by UweKrueger** [comment]
The test program is not valid. You cannot print an integer with an `f` format specifier. If you do so (and this is possible in C) the bits of the integer value are interpreted as sign, exponent and mantissa. The current compiler version (acd80f0) will complain:
```
illegal format specifier f for type int`
```
The correct line 8 would be:
```
println("${f32(f):f}")
```
which gives the output `5` (or maybe `5.000000`).
