### ISSUE TITLE
cannot append element to array using << in REPL

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#4485]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
```V
mut a := [1, 2]
a << 3
```

**What did you expect to see?**
no error and `a` should be `[1,2,3]`
 
**What did you see instead?**
cgen error: could not generate string method for type 'void'

**Comment by alexesprit** [comment]
Is this issue in REPL only?

**Comment by RNU4** [comment]
it works for me, maybe try ```v up``` in cmd, to update **V**

**Comment by SleepyRoy** [comment]
@alexesprit Yes, REPL only.

**Comment by SleepyRoy** [comment]
@RNU4 Sorry I forgot to mention this is a REPL-only issue.
