### ISSUE TITLE
[mac] V panic: clang error 

### ISSUE THREAD

**Issue by kanth989** [vlang/v#449]
trying to run the make command.

```
panic: cgen.v:79
Fn "exit" wrong arg #1. Expected "string" (reason)  but got "int"
exit():  
make: *** [v] Error 1
```
It still generated `vc` file.

**Comment by medvednikov** [comment]
Try `git pull`

**Comment by kanth989** [comment]
Hi, 
I did try git pull but still facing the same issue.

**Comment by Bowero** [comment]
This has been resolved. The codebase is notably different than back then. If you still have issues, please make a new issue.
