### ISSUE TITLE
Reserved words as names are not forbidden

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#4504]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
For example, `int := 1` works. This leads to many potential issues, try this example.
```V
fn main () {
	for int in 1..10 {
		println(int)
	}
}
```

**What did you expect to see?**
Error. Using reserved words as names should not be allowed.
 
**What did you see instead?**
`int := 1` works. And the example code below it gives C error.

**Comment by JalonSolov** [comment]
No more C error... it runs and prints
1
2
3
4
5
6
7
8
9

... which is still very wrong, as it is using a keyword as a variable name.

**Comment by medvednikov** [comment]
Indeed, it's been fixed.

`int` is not a keyword, this is a valid program, like in Go.
