### ISSUE TITLE
Why does vfmt remove trailing end of line?

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#4515]
Some think it is a useless extra character, true.

However, several tools (including git, diff, patch, etc.) can have problems if there is no EOL at the end of a file.

It is also against the POSIX standard, which describes a line that doesn't end with EOL as an "incomplete line".  A "line" is a sequence of characters followed by a newline (EOL, LF, linefeed, whatever you want to call it).

If you left the last EOL out of a text file, and try to cat that together with another file, the last line of the file without EOL and the first line of the next file would look like a single line.

If you cat a file (on some systems) without EOL at the command line, the prompt shows up as if it is the end of the last line of that file.

Etc., etc.  There are many reasons to have the EOL, and only one to remove it... to save a single byte of space in each file.

I would suggest it would be better for vfmt to ADD an EOL if the last line doesn't have one, than for it to REMOVE it if it is there.

**Comment by medvednikov** [comment]
Will be fixed of course, it's a bug.

EOL FTW.

**Comment by medvednikov** [comment]
Fixed.
