### ISSUE TITLE
Creating new project does not work.

### ISSUE THREAD

**Issue by Tembocs** [vlang/v#4517]
**V version:** 
0.1.26 78cbb77

**OS:** 
Windows 10 x64

**What did you do?**
Tried to call the following commands ```v new``` or ```v new create``` or ```v init create``` or ```v create```.

**What did you expect to see?**
A few questions regarding creating  new v project, and finally project created.
 
**What did you see instead?**
Error message: 
```
cannot compile ‘C:\Tools\v\cmd\tools\vcreate.v:
builder error: C:\Tools\v\cmd\tools\vcreate.v doesn't exist‘
```

**Comment by RNU4** [comment]
You just make a file and call it something with the .v prefix for example test.v
Then use:
`v run filepath`
For example
`v run test.v`
Make sure that the path to the file is right

I dont know if you have, but try to read through the documentation before starting to code, it will help you understand V's syntax

**Comment by Tembocs** [comment]
@RNU4 you are right that is the way to compile a v file, but that is not the problem I'm describing here. The problem is that V has a way to create new project with some few things set up. To do that you need to call ```v new create``` for example. Now this is what is not working, and what I described in the problem statement above. I actually talked to the developers at V's Discord channel and their advice was to file this as a bug. Otherwise I can compile a V file quite fine as you described.

**Comment by spytheman** [comment]
yeah - it works on linux, but now fails on windows for some reason
![v new](https://url4e.com/gyazo/images/9a5aecef.png)

**Comment by Tembocs** [comment]
@spytheman I'm currently on Ubuntu 20.04 beta. ```v new``` gives me the same error as on Windows 10.

**Comment by spytheman** [comment]
> @spytheman I'm currently on Ubuntu 20.04 beta. ```v new``` gives me the same error as on Windows 10.

Strange... Please, try `v -v new` and paste the result.

**Comment by Tembocs** [comment]
Running ```v -v new``` gave me this.
```
setting pref.path to ""
command = "new"
V 0.1.26 d5eafe7
launch_tool vexe        : ~/Tools/v
launch_tool vroot       : ~/Tools/v
launch_tool tool_args   : -v new
launch_tool tool_command: "~/Tools/v/cmd/tools/vcreate" -v new
launch_tool should_compile: true
Compiling vcreate with: ""~/Tools/v/v" "~/Tools/v/cmd/tools/vcreate.v""
cannot compile ‘~/Tools/v/cmd/tools/vcreate.v: 
builder error: ~/Tools/v/cmd/tools/vcreate.v doesn't exist‘
```
