### ISSUE TITLE
Return type not checked in op overloading

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#4538]
For example,

```V
struct Vec {
	x int
	y int
}

// It returns int instead of Vec.
fn (a Vec) + (b Vec) int {
	return a.x+b.x+a.y+b.y
}

fn main() {
	a := Vec{1,2} + Vec{3,4}
	println(a)
}
```

The code causes C error. 
**a. If overloaded op must return argument's type, V should give an error. (update: According to Alex's reply this should be the case.)** 
b. If there's no such a rule, V should compile it.

**Comment by medvednikov** [comment]
Yes it will be required.

**Comment by medvednikov** [comment]
@lutherwenxu it should be open until it's fixed

**Comment by Delta456** [comment]
I cannot figure this out. Someone else can try this.

**Comment by nedpals** [comment]
Closed. Fixed on the latest version of V: https://devbits.app/play/jy7aqBa8A2qG

**Comment by Delta456** [comment]
This compiles successfully and as per the discussion the return type should not be same as receiver type. 

Closing this.
