### ISSUE TITLE
Interface Example Failing

### ISSUE THREAD

**Issue by Zohvek** [vlang/v#4543]
**V version:** 
/play version

Was perusing the documentation and running examples.
**OS:** 
macOS 10.15.4

**What did you do?**
Tried to run the following snippet in the vlang.io/play

```
struct Dog {}
struct Cat {}

fn (d Dog) speak() string {
	return 'woof'
}

fn (c Cat) speak() string {
	return 'meow' 
}

interface Speaker {
	speak() string
}

fn perform(s Speaker) {
	println(s.speak())
}

dog := Dog{}
cat := Cat{}
perform(dog) // "woof" 
perform(cat) // "meow" 
```

 
**What did you see instead?**
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

**Comment by medvednikov** [comment]
Works with 

```
fn main() {
dog := Dog{}
cat := Cat{}
perform(dog) // "woof"
perform(cat) // "meow"
}
```

There is another issue for fn main. Will update the example.
