### ISSUE TITLE
Can't print float

### ISSUE THREAD

**Issue by bokunodev** [vlang/v#4548]
**V version:** v playground
**OS:** v playground

**What did you do?**
```v
fn main() {
	println(5.0.str())
}
```

**What did you expect to see?**
``5.000000``
 
**What did you see instead?**
``too many decimal points in number``

**workaround**
```v
fn main() {
	println((5.).str())
}
```

**Comment by krischerven** [comment]
This works for me, have you tried it on the latest version of V?

**Comment by bokunodev** [comment]
yes, but not on playground.

**Comment by krischerven** [comment]
I don't think the playground is up to date right now.

**Comment by JalonSolov** [comment]
Latest v does run this, but the output is not what I would expect.

Expected:  5.0

Saw:  5.e+00

Note this is running from command line.  Playground has not been updated.

**Comment by serkonda7** [comment]
With V 0.2.2 4feb09f repl output is `5.`
But the playground fails with `TypeError: 5.str is not a function`

**Comment by medvednikov** [comment]
Fixed.
