### ISSUE TITLE
builder error: C error.

### ISSUE THREAD

**Issue by RNU4** [vlang/v#4549]
**V version:** 
V compiler version: V 0.1.26 de182d5
**OS:** 
Host OS: Windows
Target OS: Windows
**What did you do?**
Use my struct in a function

```
struct Token {
mut:
	data   []string
	tokens []Token
}
fn (tokenizer Tokenizer) tokenization() []Token {
        //This is what causes the error
	mut temp_token := []Token // []Token and Token doesn't compile
        //This is what causes the error
	return temp_token
}
```
**What did you expect to see?**
It compiling
 
**What did you see instead?**
[https://pastebin.com/6v406wH1](https://pastebin.com/6v406wH1)

**Comment by RNU4** [comment]
Found the problem, I was printing the return longer down and that was causing the error.
Should I close the issue, or keep it open as it still generated wrong C code?

**Comment by medvednikov** [comment]
Should be open.

**Comment by aurelVZ** [comment]
And do you fix it ,and finaly create working executable?

**Comment by RNU4** [comment]
> And do you fix it ,and finaly create working executable?

As I mentioned above the thing that was causing the wrong C code generation was that I printed the return, so when I removed it, it compiled.

**Comment by Delta456** [comment]
This compiles with the latest V:

```
struct Token {
mut:
	data   []string
	tokens []Token
}
fn (tokenizer Token) tokenization() []Token {
        //This is what causes the error
	mut temp_token := []Token{} // []Token and Token doesn't compile
        //This is what causes the error
	return temp_token
}
```
