### ISSUE TITLE
V Naming Conventions

### ISSUE THREAD

**Issue by yuyi98** [vlang/v#4558]
Please unify the vlang language specification.
- `var` and `mut` unified into one.
- Can const type name be specified to uppercase?
- `struct` `union` `enum` names use capital mode and field name use snake mode.
```v
fn (mut p Parser) fn_decl() ast.FnDecl {...}
fn (var p Parser) fn_decl() ast.FnDecl {...}
fn (p mut Parser) fn_decl() ast.FnDecl {...}
```
......
- Add specification in doc and check in compiler.

**Comment by lutherwenxu** [comment]
1. It's now `mut` only.
2. No. (Note that `C.` overrides all checks to allow any arbitrary C variable name)
3. `struct`, `union`, `enum` are all types. Types are in PascalCase while everything else is in snake_case.

I hope this answers your question.

**Comment by yuyi98** [comment]
Sorry, I don't quite understand why the keyword `var` is added, whether it's for back-end JS?

**Comment by nedpals** [comment]
@yuyi98 `mut` was initially replaced with `var` because of semantics.
