### ISSUE TITLE
Failed to compile v file importing http package

### ISSUE THREAD

**Issue by wzhliang** [vlang/v#4560]
**V version:** 
V 0.1.26 fb97c2e
**OS:** 
MacOS

**What did you do?**
v get.v

Content of get.v
import net.http

fn main() {
	resp := http.get("http://httpbin.org")
	println(resp.body)
}

**What did you expect to see?**
binary file generated
 
**What did you see instead?**
v/vlib/net/http/cookie.v:75:12: error: redefinition of `_`

**Comment by spytheman** [comment]
Fixed in 7e400124e8f3505733e41aa55e69163a2c836c4c .
Code should be:
```v
import net.http
fn main() {
        resp := http.get("http://httpbin.org") or { panic(err) }
        println(resp.text)
}
```
