### ISSUE TITLE
V panic array.get: index out of range (i == 0, a.len == 0)

### ISSUE THREAD

**Issue by Zohvek** [vlang/v#4566]
**V version:** 
**OS:** 
macOS 10.15.4
**What did you do?**
ran v up from terminal / zsh

**What did you expect to see?**
Successful update
 
**What did you see instead?**
V panic: array.get: index out of range (i == 0, a.len == 0)
print_backtrace_skipping_top_frames is not implemented

the update completely broke v. Any command results in the above error.

**Comment by JalonSolov** [comment]
Might want to try again.  I just tried and 'v up' worked fine.

Before 'v up':  V 0.1.26 4f45675
After 'v up': V 0.1.26 6b31ebe

Worst case try 'git pull' to update to latest, then 'make' to rebuild v.

**Comment by Zohvek** [comment]
Good idea @JalonSolov . That did indeed work. Prior to that, any and all v commands resulte in:

V panic: array.get: index out of range (i == 0, a.len == 0)
print_backtrace_skipping_top_frames is not implemented

**Comment by JalonSolov** [comment]
Excellent.  I would suggest closing this issue, since the problem has apparently already been fixed in the code.  That will help by reducing the number of open issues, which is always good thing.  ;-)
