### ISSUE TITLE
implement auto op overload for +=, etc when +, etc overloaded

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#4571]
**What do you want?**
I propose `+=` op should be automatically overloaded by compiler when `+` has been overloaded. The behavior of `A += B` should be automatically defined as `A = A + B`.
And the same should be applied to other arithmetic ops (`-=, *=, /=, %=`).

**Why do you want this?**
1. Compatible with other rules in V. V places many restrictions on op overloading. Now V requires in op overloading both arguments must have the same type. Alex also said in #4538 that the returned type should also be the same as arguments. This makes this proposal possible - `A + B` always return A's type (also B's type).

2. Useful. Overloading on `+=` etc is commonly used in areas such as scientific computing. 

3. Saving time. This is obvious - use `+=` directly.

4. Safe and natural. `A += B` should do `A = A + B`. Imagine a piece of code defining behavior of `+=` not like this, I believe other programmers will complain about it.

**Comment by medvednikov** [comment]
Yes I think this will be supported.

**Comment by Delta456** [comment]
As this is accepted so I will be working on this.

**Comment by Delta456** [comment]
For the cases of argument operators the return must be same as receiver type so the users will have to return the same type in case of `+`, `*`, `/`, `-` and `%` for this to work.

**Comment by SleepyRoy** [comment]
@Delta456 awesome! looking forward to your work!
