### ISSUE TITLE
module eventbus error  

### ISSUE THREAD

**Issue by wilesun** [vlang/v#4574]
**V version:0.1.26** 
**OS:ubuntu** 

**What did you do?**
I want to use eventbus module,but the demo is failure.
`import eventbus

fn main() {
	eb:=eventbus.new()
	eb.has_subscriber('test')
}
`
cgen error: cgen: SelectorExpr typ=0 field=receiver
**What did you expect to see?**
 
**What did you see instead?**

**Comment by alexesprit** [comment]
Was fixed in 51da32446513a0253cc062f1cad2d98e080b2d5e.
