### ISSUE TITLE
Suggestion:  Until 0.2, change playground message

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#4578]
Currently, users are hitting lots of problems on the V playground.

Until V stabilizes again, it might be a good idea to change the current message telling users to open an issue on github, to instead tell them that V is currently undergoing changes, and apologies while things are in flux.

I would personally prefer to see that type of message than to see the one about creating an issue, creating it, and then being told "Oh, V isn't stable right now."  :-\

**Comment by medvednikov** [comment]
Can you give examples of such problems?

**Comment by JalonSolov** [comment]
In the last few days...#4543 and #4548

**Comment by aurelVZ** [comment]
HI,I would like to ask is there any older version of V which we can compile and run under windows .
I am using win7_32 bit so i am interested in that , even if the version is very old i don't worry 
i need it that compile without errors.

**Comment by JalonSolov** [comment]
Just now, #4623
