### ISSUE TITLE
'mut' can be used on arguments with unsuitable type

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#4585]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
```V
fn foo (a mut int) {

}

fn main() {

}
```
**What did you expect to see?**
An error: cannot modify int typed argument
 (In docs "_V doesn't allow to modify primitive args like integers, only complex types like arrays and maps._")

**What did you see instead?**
It compiled.

**Comment by medvednikov** [comment]
Fixed.
