### ISSUE TITLE
Can't compile V with make. mach/mach_time.h  error

### ISSUE THREAD

**Issue by asvvvad** [vlang/v#4592]
**V version:** Latest master (commit: #b7e5be4)
**OS:**  elementary OS 5.1.3 Hera x86_64, Built on Ubuntu 18.04.3 LTS & Linux 5.3.0-46-generic

**What did you do?**
I cloned the git repository from master and ran `sudo make` in it

**What did you expect to see?**
V to compile like it did before
 
**What did you see instead?**
```
$ sudo make
cd /tmp/vc && git clean -xf && git pull --quiet
cd /var/tmp/tcc && git clean -xf && git pull --quiet
cc  -g -std=gnu11 -w -o v /tmp/vc/v.c  -lm
/tmp/vc/v.c:832:10: fatal error: mach/mach_time.h: No such file or directory
 #include <mach/mach_time.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:51: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by JalonSolov** [comment]
I'm seeing the same thing, same version, just doing a 'v up'.

**Comment by medvednikov** [comment]
Fixed.
