### ISSUE TITLE
Maps are mutable by default.

### ISSUE THREAD

**Issue by Tembocs** [vlang/v#4596]
**V version:** V 0.1.26 cd27300
**OS:**  Windows 10 x64

**What did you do?**
```
module main

fn main() {
    my_map := {"one": 1, "two": 2, "three": 3, "four": 4}
    my_map["five"] = 5
    my_map['six'] = 6
    println(my_map)
}
```

**What did you expect to see?**
Error during compilation as ```my_map``` should not be mutable by default.
 
**What did you see instead?**
Compilation succeeded without error with the output below.
```
map_string_int{one: 1, two: 2, three: 3, four: 4, five: 5, six: 6}
```

**Comment by medvednikov** [comment]
Fixed.
