### ISSUE TITLE
no error for duplicate parameter name

### ISSUE THREAD

**Issue by eyelash** [vlang/v#4604]
**V version:** V 0.1.26 2705660
**OS:** Linux

**What did you do?**
I tried to compile the following program:
```
fn foo(n int, n int) {

}
```

**What did you expect to see?**
I expected to see an error message from the V compiler.
 
**What did you see instead?**
The following error from the C compiler:

<pre>==================
/home/elias/.cache/v/sandbox.tmp.c: At top level:
/home/elias/.cache/v/sandbox.tmp.c:7287:21: <font color="#CC0000">error:</font> redefinition of parameter ‘n’
 7287 | void foo(int n, int n) {
      |                 ~~~~^
/home/elias/.cache/v/sandbox.tmp.c:7287:14: note: previous definition of ‘n’ was here
 7287 | void foo(int n, int n) {
      |          ~~~~^
/home/elias/.cache/v/sandbox.tmp.c: In function ‘_vinit’:
/home/elias/.cache/v/sandbox.tmp.c:7317:38: warning: integer constant is so large that it is unsigned
 7317 |  _const_math__bits__max_u64 = ((u64)(18446744073709551615));
      |                                      ^~~~~~~~~~~~~~~~~~~~
/home/elias/.cache/v/sandbox.tmp.c:7339:409: warning: integer constant is so large that it is unsigned
...
==================
(Use `v -cg` to print the entire error message)

<font color="#CC0000"><b>builder error</b></font>: C error.</pre>

**Comment by medvednikov** [comment]
Fixed.
