### ISSUE TITLE
support recursive anonymous function

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#4611]
**Update: A preliminary decision is to accept this. Syntax suggestions are wanted and welcome!**

Local functions are very useful. Thanks to the recently implemented anonymous function, we can now write, e.g.,
```V
fn func() {
    local := fn() {
        println('hello world')
    }
    local()
}
```
However, sometimes local functions need to be recursive, so please consider implementing recursive anonymous function. Here's a possible syntax.
```V
fn func() {
    local := fn(n int) {
        if n>1 {
            fn(n-1)
        }
        println('hello world')
    }
    local(10)
}
```
A more real example:
```V
// example: a binary tree
struct Empty {}
struct Node {value int  left Tree  right Tree}
Type Tree = Empty | Node 

get_size_of_tree := fn (tree Tree) int {
	return match tree {
		Empty { 0 }
		Node { 1 + fn(tree.left) + fn(tree.right) }
	}
}
size := get_size_of_tree(tree)
```

**Comment by ntrel** [comment]
V doesn't allow local fn declarations, but in this case it would be better for the parser than `fn(n-1)`:
```v
    fn local(n int) {
        if n>1 {
            local(n-1)
        }
        println('hello world')
    }
```

**Comment by SleepyRoy** [comment]
@ntrel but I remember local fn declaration examples like this worked...
```V
fn func() {
    local := fn() {
        println('hello world')
    }
    local()
}
```

**Comment by ntrel** [comment]
>     local := fn() {

That works (I meant you can't have named function declarations inside a function). In the body of the anonymous function above, you can't use the name `local` because it hasn't been defined yet. Anyway, another solution would be to have a special name like `self`: `self(n-1)`.

**Comment by SleepyRoy** [comment]
@ntrel yes that makes sense. I think we could simply use `fn` as such a special name.

**Comment by ntrel** [comment]
`fn(ident)` looks like a function type. It's best to avoid syntax that requires special tests to tell the difference.

**Comment by SleepyRoy** [comment]
**Update: A preliminary decision is to accept this. Syntax suggestions are wanted and welcome!**

**Comment by mindplay-dk** [comment]
Having calls like `fn(x)` is not very semantic.

And what happens if you have functions within functions and need to call the outermost `fn`?

My suggestion would be an optional means of declaring a symbol, e.g.:

```
// example: a binary tree
struct Empty {}
struct Node {value int  left Tree  right Tree}
Type Tree = Empty | Node 

get_size_of_tree := fn count_nodes(tree Tree) int {
	return match tree {
		Empty { 0 }
		Node { 1 + count_nodes(tree.left) + count_nodes(tree.right) }
	}
}
size := get_size_of_tree(tree)
```

The symbol `count_nodes` in this example would be locally scoped, and calls like `count_nodes(tree.left)` actually look and sound like what they are.

> `fn(ident)` looks like a function type to the parser.

It also looks ambiguous to a person.

Recursive functions in other langs typically need a name, e.g. in JavaScript - so this wouldn't be surprising to most people.

This seems more consistent with function syntax/semantics in general.
