### ISSUE TITLE
cannot define recursive struct (eg binary tree's node)

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#4612]
For example, a leaf node of binary tree should store its left and right nodes as 'empty'.
```V
struct Node {
	value int
	left &Node
	right &Node
}
```
In C we use `NULL`, in CPP we use `NULL` or `nullptr`, in go we use `nil`. How about V?

**Comment by medvednikov** [comment]
`?Node` and `none`

**Comment by SleepyRoy** [comment]
@medvednikov Thanks. Like this? 
```V
struct Node {
	value int
	left ?&Node
	right ?&Node
}
fn main() {
	tree := Node{value: 10, left: none, right: none}
	println(tree.left == none)  // should print true?
}
```
But it gives C error. 😂

**Comment by medvednikov** [comment]
```
struct Node {
	value int
	left ?Node
	right ?Node
}
```

**Comment by SleepyRoy** [comment]
@medvednikov 
It gives `cgen error: cgen.sort_structs(): the following structs form a dependency cycle: * Node -> Node`.

**Comment by medvednikov** [comment]
Will have to fix this compiler bug.

**Comment by spytheman** [comment]
You can try:
```v
struct Node {
        value int
        left &Node
        right &Node
}

fn (n &Node) str() string {
        return 'Node {\n' +
    '   value: $n.value\n' +
    '   left: 0x${ptr_str(n.left)}\n' +
    '   right: 0x${ptr_str(n.right)}\n' +
    '}'
}

fn main(){
        x := &Node{ value:123 left: &Node(0) right: &Node(0)}
        y := &Node{ value:456 left: x right: &Node(0)}
        z := &Node{ value:456 left: y right: x}
        eprintln('node x: $x.str()')
        eprintln('node y: $y.str()')
        eprintln('node z: $z.str()')
}
```
... which produces:
```
0[20:56:14] /v/nv LINUX $ ./v run node.v
node x: Node {
   value: 123
   left: 0x0
   right: 0x0
}
node y: Node {
   value: 456
   left: 0x625050
   right: 0x0
}
node z: Node {
   value: 456
   left: 0x625070
   right: 0x625050
}
0[20:56:15] /v/nv LINUX $
```

**Comment by SleepyRoy** [comment]
@spytheman Thanks. It does work, but assigning `0` to `&Node` is somewhat like C's `ptr = 0`, which I guess is not a good style in V. Maybe V should have a keyword doing this (e.g. like C++'s `nullptr`)?

**Comment by dumblob** [comment]
>which I guess is not a good style in V.

I think this is still an open question - see https://github.com/vlang/v/commit/153ac230ec69bdd068512d59ef79aa20e8f38876#r38768546 . @medvednikov thoughts?

**Comment by SleepyRoy** [comment]
@dumblob I just read that discussion and support your view. Playing with addresses should only be allowed in `unsafe`.

**Comment by dumblob** [comment]
I actually find the solution from @Alfex4936 (`left &Tree = &Tree(0)`) explicit and clear unlike "playing with zeros or nulls or stuff".

**Comment by JalonSolov** [comment]
I prefer `?Name` to solve this.  It is more V than `&Tree(0)` (regardless of backend implementation).

**Comment by MarcTCruz** [comment]
> I prefer `?Name` to solve this. It is more V than `&Tree(0)` (regardless of back end implementation).

**This is currently the only clear way to do it I can think about, because if the struct is a generic type you can't use 0 to initialize it, you need to use the correct type.**

I'm coding a generic map, but it's hard without a none type, also it's initialized with a vector of 2 ^16 to be used like hash.

The result is that, without none, it's needed to start 2 ^16 structs(of only one hard coded type[defeating the generic purpose] or some sort of thing I'm about to think yet) wasting memory(it would be around (2 ^16) * 6 with vector to pointer and length, but to achieve the thing in the code it's using  (2 ^16) * ((10 + T value bytes + index_bytes[~4]) * 2), and hardly all positions in the vector will be used in basic scenarios.

It'd be needed some checks without none to know what kind of generic value it takes to pre-initialize it, which will impact readability a lot, also if the way to do it is without datatypes, it's gonna be bad to have a clean code where the type is not really assured.

**Comment by dumblob** [comment]
@MarcTCruz do I understand your justification correctly in that you'd like to mix ordinary **value** (e.g. pointer to NULL in C backend and "undefined" in JS backend) into a **type**? That's really a bad idea.

Why not to introduce a V-wide compile time constant `SINGLETON_REFERENCE_VALUE` to be used as the default value for any such reference?

After all the only two requirements are first that the value of such reference (not the value the reference is referring to) must not interfere with any reference you could get with `&` in **V code** and second that this value is comparable by (in)equality operators. V compiler would then (depending on the backend - might be `NULL` or `undefined` or whatever) assign a fitting value to this constant in compile time and **no** new syntax would be needed and everything would be well defined and clear with no surprises. Just KISS.

Btw. `left ?Tree` feels utmost confusing as it'd encourage one to think optionals can be reified and second it'd anyway require yet another way/syntax to check against this special case.

**Comment by medvednikov** [comment]
What's confusing about optionals? They just ensure that the user checks the value, which has to be done anyway ( left != null)

**Comment by dumblob** [comment]
>What's confusing about optionals? They just ensure that the user checks the value, which has to be done anyway ( left != null)

First, you're right, that the syntax `or { ... }` does not necessarily need to be changed - that was an oversight on my side and I'm sorry for that.

Anyway optionals currently do not have proper "value" semantics (syntax is such, that they can't be assigned to anything). But **defining** a struct to contain an "ephemeral" value which can't be assigned to anything sounds really like a pure schizophrenia and kind of a brainfuck.

Second (and probably more importantly) optionals are **slow** for defining any building blocks like data structures (a tree is just a grain in the desert). I think this might be optimized away under the hood, but that doesn't sound like a good idea either as that'd completely change the explicitness (which *V* strives for) of structs as suddenly the struct wouldn't contain an optional and one couldn't be sure any more how a particular struct is being laid out etc. in memory (or there'd need to be lots of hacks like attributes over attributes to cancel some specific behavior for that given struct etc. - again directly against the basic idea of *V* to keep things simple and explicit and do one thing in just one way).

Or alternatively *V* would introduce another kind of optionals (maybe called "ephemeral" optionals?) which would guarantee they'll be never reified. This ephemeral optionals would be then **the** optionals in structs (i.e. the struct would actually not contain any optional, but an optional in that sense would just be a pure (sum)type attribute (applicable **only to references** - at least for the beginning) for compile-time checking for `or { ... }` at any place it's being used).

Btw. I like that with optionals there wouldn't be a way to "forget" about handling the speciall "null" case. But if by `left &Tree` you all actually meant the "other kind" of optionals I outlined above, then I'm sorry for misunderstanding and beg for making this crystal clear in *V* doc.

**Comment by medvednikov** [comment]
> syntax is such, that they can't be assigned to anything

ok, that's true and a valid point

this will be fixed soon, it's on the roadmap

**Comment by dumblob** [comment]
>this will be fixed soon, it's on the roadmap

May I ask what's the desired "fix" (I couldn't find anything in the tracker nor in [0.3_roadmap.txt](https://github.com/vlang/v/blob/master/0.3_roadmap.txt ))?

I wouldn't even say it's a bug - from my point of view, I'd rather have another "emphemeral" kind of optionals usable only for references and only in structs (and properly documented) than to introduce assigning of an optional to variable (which is a huge can of worms!).

**Comment by medvednikov** [comment]
This example works now with `unsafe{nil}`.

**Comment by tambapps** [comment]
Hello @medvednikov, could you provide a full example please? I tried the below code
```v
enum FileType as u8 {
  file
  directory
}

struct File {
  parent ?File = none
  t FileType
  name string
  size int
mut:
  children []File = []File{}
}
```

but got the following error
```
% v run solution.v
solution.v:8:8: error: invalid recursive struct `File`
    6 | }
    7 | 
    8 | struct File {
      |        ~~~~
    9 |   parent ?File = none
   10 |   t FileType
```

Running on macOS Ventura 13.0.1
