### ISSUE TITLE
Official example at https://vlang.io/play doesnt compile

### ISSUE THREAD

**Issue by ExcpOccured** [vlang/v#4623]
Hello, but unfortunately the JSON decoding/encoding example doesn't work and the server returns an error that the file can't be compiled.

### Steps for reproduce:
1) Open the page of the playground
2) Select JSON Encoding/Decoding
3) Press Run!

![image](https://user-images.githubusercontent.com/55463070/80404541-02cd4600-88ca-11ea-8ffa-743440814ed6.png)

**Comment by lutherwenxu** [comment]
Duplicate of #4273.
