### ISSUE TITLE
no error when many returns in same scope

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#4635]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
```V
fn foo() int {
	return 0
	return 0
}
fn main() {
}
```

**What did you expect to see?**
error: more than one return in same scope
 
**What did you see instead?**
no error

**Comment by jm-duro** [comment]
In many cases you may need many returns in the same scope, as for example when you return on error. You might have many checks in a function with one possible return by check.
This issue is not a bug and should not be considered a bug.

**Comment by jm-duro** [comment]
This could lead to a warning instead of an error if many returns are in the same block of instructions:

"WARNING: instructions following return will never be executed!"

**Comment by SleepyRoy** [comment]
@jm-duro Yeah, this is better.
