### ISSUE TITLE
Define V syntax for multiple editors simultaneously...

### ISSUE THREAD

**Issue by ylluminate** [vlang/v#465]
It could be useful if someone reworked [v-vscode](https://github.com/monarrk/v-vscode) to incorporate multiple editors by using this handy tool: https://eeyo.io/iro/

Introductory article: https://medium.com/@model_train/creating-universal-syntax-highlighters-with-iro-549501698fd2

**Comment by MostHated** [comment]
Id love to have a plugin for GoLand.

**Comment by ylluminate** [comment]
The [Microsoft Language Server Protocol](https://microsoft.github.io/language-server-protocol/) would also be very useful to define. Existing language implementations (would be good exposure for V): https://microsoft.github.io/language-server-protocol/implementors/servers/

**Comment by AurelienFT** [comment]
https://github.com/0x9ef/vscode-vlang define it for VSCode but it's TextMate. You can transfer it to others IDE like Atom for example with : https://flight-manual.atom.io/hacking-atom/sections/converting-from-textmate/

**Comment by ylluminate** [comment]
Yes, but I think conversion from TextMate to others is a manual process. The reason I thought using Iro might be the *best* option is because we'd essentially only have one grammar to maintain so as to update the others...

I agree that converting from TextMate to Iro seems like extra work, but to get the additional languages which would seem to give us all of the major editors (including emacs I believe) seems worth the effort...

**Comment by ylluminate** [comment]
By the way @MostHated from what I can tell GoLand will also work with the TextMate grammar that will come from this.  See [PhpStorm help re: TextMate](https://www.jetbrains.com/help/phpstorm/textmate.html) and since PhpStorm pretty much is GoLand (same with all JetBrains editors), then this extends over. Also [GoLand help.](https://www.jetbrains.com/help/go/textmate-bundles.html)

**Comment by AurelienFT** [comment]
@ylluminate I've started it : https://gist.github.com/AurelienFT/49ffe2b04d80e7e8694be1488c4b0aec

**Comment by ylluminate** [comment]
Adding V support to GitHub is relevant to this @AurelienFT: https://github.com/github/linguist/pull/4564

**Comment by joe-conigliaro** [comment]
What about this? https://github.com/0x9ef/vscode-vlang/blob/master/syntaxes/v.tmLanguage.json

**Comment by ylluminate** [comment]
@joe-conigliaro that is what @AurelienFT is working back from. Once we get it defined in `iro` we'll have one source for updating the grammar so that TM and all the others are autogenerated and thus we should, in theory, support most editors pretty easily. Even `emacs` can use the `pygments` output...

**Comment by joe-conigliaro** [comment]
@ylluminate Cool that sounds good

**Comment by lutherwenxu** [comment]
This issue has been closed due to the inactivity.
Please reopen this issue if you want to continue the discussion.

**Comment by VarunBatraIT** [comment]
Once we have this - I am assuming that we will have VIM integration as well right?

**Comment by HTG-YT** [comment]
> Id love to have a plugin for GoLand.

Or rather the IntelliJ Platform.

**Comment by nedpals** [comment]
for those interested, you can use this plugin i wrote as a starting point (PRs are welcome!): https://github.com/nedpals/intellij-vlang

**Comment by i582** [comment]
V plugin for JetBrains IDEs is here:
https://intellij-v.github.io

**Comment by pepa65** [comment]
I made a request for `nano` editor support at https://github.com/scopatz/nanorc

**Comment by ArtemkaKun** [comment]
@i582 does your new language server cover this issue?

**Comment by i582** [comment]
> @i582 does your new language server cover this issue?

This is already the case, thanks to tree-sitter we already have highlighting in many editors, VS Code and Sublime Text already have it through plugins.

v-analyzer will only bring IDE features.

**Comment by ArtemkaKun** [comment]
So maybe we should close this issue when your work will be out of beta

**Comment by ArtemkaKun** [comment]
v-analyzer VLS was released and it added a V LS support for bunch of editors, that are using LSP. So I think this issue can be closed

**Comment by pepa65** [comment]
> I made a request for `nano` editor support at https://github.com/scopatz/nanorc

@Harxi made a nano syntax file: https://github.com/Harxi/vlang-nanorc
