### ISSUE TITLE
C generation error on variable declaration or assignment with multiple names

### ISSUE THREAD

**Issue by Henrixounez** [vlang/v#4654]
**V version:** V 0.1.26 50a8373.54d1a29
**OS:** Linux (Fedora 29

**What did you do?**
```
a a a a a a a a a := 0
```
```
mut a := 1
a a a a a a a a a = 0
```

**What did you expect to see?**
Compilation error
 
**What did you see instead?**
C Error with this C generation:
```
int main(int ___argc, char** ___argv) {
	_vinit();
	a;
	a;
	a;
	a;
	a;
	a;
	a;
	a;
	int a = 0;
	return 0;
}
```
```
int main(int ___argc, char** ___argv) {
	_vinit();
	int a = 1;
	a;
	a;
	a;
	a;
	a;
	a;
	a;
	a;
	a = 0;
	return 0;
}
```

**Comment by SleepyRoy** [comment]
Similar bug : `a := 2 3` also doesn't result in an error. After it's fixed, #3823 could be closed.
