### ISSUE TITLE
Documentation - List all public functions

### ISSUE THREAD

**Issue by jm-duro** [vlang/v#4660]
This is not a real Feature Request. It is just information.

I'm building an OpenOffice Sheet providing a list of all available functions of V with following fields:
import | option | usable | name | description | tags | redundant | declared here | comment

Here is an example of a record:
bitfield | instance mut BitField | Yes | clearall() | clears (sets to zero) all bits in the array. | bits | FALSE | bitfield/bitfield.v:115 |  

I allready noticed many duplicate functions. I hope to get the sheet completed by the end of this week.

**Comment by medvednikov** [comment]
you can use `v doc bitfield` to list all types and functions

**Comment by nedpals** [comment]
There is a dedicated tag for questions. Please don't use the "Feature Request" next time.
