### ISSUE TITLE
Unable to use anonymous functions as struct fields

### ISSUE THREAD

**Issue by imnsho** [vlang/v#4668]
**V version:** 
0.1.26 50a8373.6b08cbc
**OS:** 
Linux
**What did you do?**
```
struct X {
  f fn(p int) int
}
fn main() {}
```
**What did you expect to see?**
Compiled binary. 
**What did you see instead?**
```
/..../.cache/v/main.tmp.c:495:2: error: unknown type name ‘anon_fn_7_7’
  495 |  anon_fn_7_7 f;
      |  ^~~~~~~~~~~
/..../.cache/v/main.tmp.c: In function ‘strconv__ftoa__f32_to_str’:
/..../.cache/v/main.tmp.c:1920:8: warning: initialized field overwritten [-Woverride-init]
 1920 |   .u = 0,
      |        ^
/..../.cache/v/main.tmp.c:1920:8: note: (near initialization for ‘(anonymous).u’)
/..../.cache/v/main.tmp.c: In function ‘strconv__ftoa__f32_to_str_pad’:
/..../.cache/v/main.tmp.c:1942:8: warning: initialized field overwritten [-Woverride-init]
 1942 |   .u = 0,
      |        ^
```

I got the impression maybe a week ago that the anonymous functions were supposed to be fixed in V2, I apologize if that's not the case - I didn't manage to quite keep up with discord and git log.

**Comment by nedpals** [comment]
@imnsho It's better to alias your function type like this:
```v
type IntFunc = fn (p int) int
struct X {
   f IntFunc
}
```

Although, this shouldn't be the expected generated code, but it's better to alias function type to avoid unnecessary pitfalls.

**Comment by imnsho** [comment]
Yeah, that compiles, thanks. Not sure if I always want to create a type alias but at least it works as a workaround.

**Comment by nedpals** [comment]
Not sure why the compiler treats it as a function when is used on struct declaration but using the function type directly works fine if you used it as a function parameter.

**Comment by nedpals** [comment]
Closed. Bug has been fixed in the latest V version.
