### ISSUE TITLE
A little thank you, Alexander Medvednikov

### ISSUE THREAD

**Issue by lolin9** [vlang/v#4673]
I know this is very irrelevant and unprofessional to do it here but I won't be able to say thank you in person. I've been following your journey since the inception of the language and I've seen the vicious attacks and negativity especially on HN and Reddit towards you from the very beginning despite you doing this tremendous amount of work and expecting nothing in return. Anybody else would have quit if faced so much attacks (and the author of Rust's Actix understandably quit for so much less). The journey is still at its beginning but Vlang already passed the hardest times.

So this is a little thank you, Alexander Medvednikov

**Comment by logTom** [comment]
V is really incredible. I'm using it since december last year and it has really reignited my love for developing/programming stuff.
You can call me insane, but I'm currently developing a very big program/middleware with it and it's such a pleasure to do it in v. Thank you from the ground of my rusty heart!

**Comment by elimisteve** [comment]
V is the best-designed programming language of all time -- period.

**Comment by medvednikov** [comment]
Thank you for the kind words.

I have a good vision about the language, and some silly criticism from in Hacker News comments (like V compiler depending on GLFW and OpenGL 😂) won't stop me from achieving my goals :)

I received lots of support and help,  and I'm super excited about the positive changes V can bring to our industry in terms of simplicity, fast compilation, and performance.

**Comment by dalisoft** [comment]
I found this language recently (really, 5 minute ago). I will try, i see a you did a lot of work, so thank you.
I wish this project more popularity than now.
