### ISSUE TITLE
interpolation: i64/u64 error

### ISSUE THREAD

**Issue by yuyi98** [vlang/v#4679]
**V version:** 
V 0.1.26 50a8373.06d533b
**OS:** 
Win10 1909
**gcc:**
gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)

**What did you do?**
```v
fn main() {
	a := i64(4)
	println('$a')
}
```

**What did you expect to see?**
4
 
**What did you see instead?**
4526808625615732740

**generate c code**
```v
int wmain(int ___argc, wchar_t* ___argv[], wchar_t* ___envp[]){
	_vinit();
i64 a = ((i64)(4));
println(_STR("%"PRId64"\000", 2, a));
	return 0;
}
```

**Related errors**
```v
FAIL [ 42/165]  1385.051 ms vlib\math\fractions\fraction_test.v
C:\Users\yuyi9\v\vlib\math\fractions\fraction_test.v:8: failed assert in test_fraction_creation()
Source  : assert f1.str().eq('4/8')

FAIL [149/165]  1355.719 ms vlib\v\tests\string_interpolation_test.v
vlib\v\tests\string_interpolation_test.v:99:2: warning: unused variable: `e`
   97 |     assert '$a $st $m' == 'à-côté Sträßle 10€'
   98 |     assert '>${a:10}< >${st:-8}< >${m:5}<-' == '>    à-côté< >Sträßle < >  10€<-'
   99 |     e := '\u20AC' // Eurosign
      |     ^
  100 |     // TODO: this fails with MSVC and tcc
  101 |     // assert '100.00 $e' == '100.00 €'
C:\Users\yuyi9\v\vlib\v\tests\string_interpolation_test.v:88: failed assert in test_inttypes_string_interpolation()
Source  : assert '$l $ul' == '-7694555558525237396 17234006112912956370'
------------------------------------------------------------------------------------------
               132901.311 ms <=== total time spent testing all fixed tests
                 ok, fail, skip, total =   151,     2,    12,   165
```

**Comment by medvednikov** [comment]
@UweKrueger can you have a look?

**Comment by UweKrueger** [comment]
Hmm, I can't reproduce this problem on my Platform (Ubuntu 20.04, gcc-9.3.0, x86_64)
@yuyi98 can you try changes to the intermediate C-Source like
`println(_STR("%"PRId64"\000", 1, a));` or
`println(_STR("%"PRId64"\000\000", 2, a));`
`println(_STR("%lld\000", 2, a));`
`println(_STR("%lld", 1, a));`
and post the outputs of these versions on your platform?

**Comment by yuyi98** [comment]
OK, I'll try it.

**Comment by yuyi98** [comment]
```v
println(_STR("%"PRId64"\000", 1, a)); 
println(_STR("%"PRId64"\000\000", 2, a));
```
4526808625615732740

```v
println(_STR("%lld\000", 2, a));
println(_STR("%lld", 1, a));
```
4

**Comment by UweKrueger** [comment]
That's strange! Can you find out what `PRId64` expands to? Try `gcc -E myfile.c >processed.i` and find the `println()`-line in the output file.
You can also have a look into the header file `...\include\inttypes.h` and find the definition.

> Is the gcc version too low?

I don't know. However, it might at least be worth trying a more recent version (8.4 or 9.3 - yesterday 10.1 has been released... ;-)

> Why not use type.str() directly?

This is done for data types that `printf()` can't handle. However `printf()` can handle format specifiers like `"%04x"` or `"%9.2f"` whereas the `.str()` method only generates the default representation.

**Comment by yuyi98** [comment]
gcc -E tt1.c >processed.i

```v
int wmain(int ___argc, wchar_t* ___argv[], wchar_t* ___envp[]){
 _vinit();
i64 a = ((i64)(4));
println(_STR("%"
# 9384 "tt1.c" 3
               "I64d"
# 9384 "tt1.c"
                     "\000", 1, a));
 return 0;
}
```

**Comment by UweKrueger** [comment]
Well this explains a lot... From the file `.\mingw-w64-headers\crt\inttypes.h`:
```
/* 7.8.1 Macros for format specifiers
 * 
 * MS runtime does not yet understand C9x standard "ll"
 * length specifier. It appears to treat "ll" as "l".
 * The non-standard I64 length specifier causes warning in GCC,
 * but understood by MS runtime functions.
 */
#if defined(_UCRT) || __USE_MINGW_ANSI_STDIO
#define PRId64 "lld"
#define PRIi64 "lli"
#define PRIo64 "llo"
#define PRIu64 "llu"
#define PRIx64 "llx"
#define PRIX64 "llX"
#else
#define PRId64 "I64d"
#define PRIi64 "I64i"
#define PRIo64 "I64o"
#define PRIu64 "I64u"
#define PRIx64 "I64x"
#define PRIX64 "I64X"
#endif
```
These non-standard `"I64*"`-Specifiers are for versions of `ctrdll.dll` thar don't handle `"ll*`" correctly. Actually that should only be a problem on 32-bit platforms since for 64-bit `long` and `long long` are identical.
There are three possible solutions:
- Call the C-compiler with the flag `-D__USE_MINGW_ANSI_STDIO` on that platform. I'm not sure what other side effects that may cause
- make `cgen.v` emit `"ll*"` for 64-bit Integers regardless what `PRI*64` is. C11 guaranties that `long long` is at least 64-bit, however there may come up platforms where "long long" will mean 128-bit...
- put something like this in the generated C-file after the includes:
```
#if defined(__MINGW32__) || defined(__MINGW64__)
#undef PRId64
#undef PRIi64
#undef PRIo64
#undef PRIu64
#undef PRIx64
#undef PRIX64
#define PRId64 "lld"
#define PRIi64 "lli"
#define PRIo64 "llo"
#define PRIu64 "llu"
#define PRIx64 "llx"
#define PRIX64 "llX"
#endif
```
@medvednikov what do you think is suitable?
