### ISSUE TITLE
Modules documentation

### ISSUE THREAD

**Issue by jm-duro** [vlang/v#4701]
It is still a work in progress but here is a temporary help file for V modules while awaiting official documentation:

http://jean-marc.duro.pagesperso-orange.fr/vlang.htm

Regards

Jean-Marc

**Comment by dhonx** [comment]
Great work @jm-duro  :+1:

**Comment by nedpals** [comment]
@jm-duro Let us know if your work is finished so we can improve it and integrate changes to `vdoc` :)

**Comment by jm-duro** [comment]
Is is still in progress. I need about one week to finish it.

**Comment by nedpals** [comment]
@jm-duro No pressure. Take your time 😄

**Comment by jm-duro** [comment]
I have updated the function list ODS sheet and the help file. All non-graphical and non-internally-used functions have been listed. They are available on my personal home page:

http://jean-marc.duro.pagesperso-orange.fr/

I will now look into graphical functions. I wonder if it is a good idea to document internally-used functions: those under vlib/v.

**Comment by jm-duro** [comment]
I have finished the job. The files are now ready for use at

http://jean-marc.duro.pagesperso-orange.fr/
