### ISSUE TITLE
v install ui failed

### ISSUE THREAD

**Issue by cctse** [vlang/v#4706]
**V version: V 0.1.26 50a8373.0e24116** 
**OS: MacOs** 

**What did you do?**
v install ui

**What did you expect to see?**
succeed
 
**What did you see instead?**
```
❯ v install ui
cannot compile ‘/Users/cc/v/cmd/tools/vpm.v:
js.decode t=Mod
==================
^
/private/var/folders/20/5c9pj_4n21n_157qq7t10lv00000gp/T/v/vpm.tmp.c:13378:26: error: unexpected type name 'Mod': expected expression
                Mod mod = json__decode(Mod, s);
                                       ^
```

[ui issue #102](https://github.com/vlang/ui/issues/102)

**Comment by nedpals** [comment]
Closed. Duplicate or #4256.
