### ISSUE TITLE
Access Modifiers are broken

### ISSUE THREAD

**Issue by hungrybluedev** [vlang/v#4709]
**V version:** 0.1.26 50a8373.c112b3a
**OS:** Confirmed on Windows, Linux, and MacOS

**What did you do?**

I performed the following steps:
1. Create a fresh new project (empty directory).
2. Create files: `main.v` and `matrix/matrix.v`
3. Copy and paste the code below for each of these files.
4. Run `v run main.v`

_main.v_
```v
import matrix

fn main() {
    array := [1, 2, 3]
    a := matrix.IntMatrix{
        data: array
        rows: 1
        cols: 3
    }
    println(a.data)
    println(a.rows)
    println(a.cols)
}
```

_matrix/matrix.v_
```v
module matrix

struct IntMatrix {
    data []int
    rows int
    cols int
}
```

**What did you expect to see?**

A compilation error. `struct`s not prefixed with `pub` should not be accessible outside the module. Same for the members of the struct: we do not define them under `pub:` so they should not be accessible.
 
**What did you see instead?**

The code compiles and runs correctly. The output is:
```
[1, 2, 3]
1
3
```

**Why is this bug peculiar?**

This is a bug that _does not break_ existing code. Instead, it allows broken code (according to the Documentation) to be compiled.

After the issue is fixed, there should be a test to check that invalid code does not compile. It is easy for this error to fly under the radar.

**Edit**: This bug also applies to `const`s.

**Comment by medvednikov** [comment]
> A compilation error. structs not prefixed with pub should not be accessible outside the module.

Fixed.

Fields still need to be fixed.

**Comment by medvednikov** [comment]
Fixed.
