### ISSUE TITLE
Detect duplicate const literals in match

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#4712]
Expected behavior:

```
a := 0
switch a {
case 0.0:
case 0:
}
./prog.go:12:6: duplicate case 0 in switch
```

**Comment by Delta456** [comment]
This now gives an error `cannot match `float literal` with `int` condition`. I am not sure if `0.0` should implicitly cast to `int`.

**Comment by dumblob** [comment]
>I am not sure if `0.0` should implicitly cast to `int`.

It should **not** (because it's an **approximate** zero and thus **not an integer exact zero**).

**Comment by serkonda7** [comment]
@dumblob if the value that is matched (here `a`) is an int, `0.0` should be cast.

**Comment by dumblob** [comment]
>@dumblob if the value that is matched (here a) is an int, 0.0 should be cast to an int.

Generally yes, but only for compatible types. In *V* it must **not** be possible to do:
```v
mut x := 1.5
x = 0.0
assert x == 0
```
The correct way would be:
```v
mut x := 1.5
x = 0.0
assert int( x ) == 0
```

**Comment by serkonda7** [comment]
Therefore we have rules for automatic type promotions. You can look them up in the docs

**Comment by dumblob** [comment]
>Therefore we have rules for automatic type promotions. You can look them up in the docs

Type promotions are in flux for quite some time already (https://github.com/vlang/v/pull/7801#issuecomment-754097589 , https://github.com/vlang/v/issues/8601 , https://github.com/vlang/v/issues/7692 , https://github.com/vlang/v/issues/6251 ) and they converge to **guarantee** no information loss which in this case is not possible (it's possible to silently promote int to f64, but not any float to int).

**Comment by medvednikov** [comment]
Fixed.
