### ISSUE TITLE
function returns null

### ISSUE THREAD

**Issue by tim-st** [vlang/v#4713]
**V version:** 
`V 0.1.26 50a8373.9aa1a65`
**OS:** 
linux amd64

**What did you do?**
```v
fn a() string {
	"""same with this code
	match 1 {
		1 {

		}
		else {
			return ""
		}
	}
	"""
	if false {
		return "a"
	}
}


fn main() {
	a_null := a()
	println(a_null)
}
```

**What did you expect to see?**
compiler error: "error: missing return at end of function `a`"
 
**What did you see instead?**
(null)

**Comment by medvednikov** [comment]
yeah it results in an error in simple cases like

```
fn a() string {}
```

**Comment by medvednikov** [comment]
The full analysis was implemented in V1, so it should be trivial to bring it back.

**Comment by medvednikov** [comment]
Doing this will break lots of existing coce.

**Comment by tim-st** [comment]
Ok, then for now you could just set a default string of `""` as return value for this case, I think that wouldnt break code.

**Comment by JalonSolov** [comment]
Now is a good time to break code this way.  Lots of other things have been broken along the way from V1 to V2, so better to break this now than carry that technical debt into the future.
