### ISSUE TITLE
string(1) creates sigsegv

### ISSUE THREAD

**Issue by tim-st** [vlang/v#4714]
**V version:**
V 0.1.26 50a8373.9aa1a65
**OS:** 
linux amd64

**What did you do?**
```v
fn a() string {
	return string(1)
}

fn main() {
	v := a()
	println(v)
}
```

**What did you expect to see?**
`1`

 
**What did you see instead?**
`Terminated by signal 139 (SIGSEGV)`

**Comment by yuyi98** [comment]
You should use `1.str()` instead of casting type conversion.

**Comment by medvednikov** [comment]
V should return an error, like in V1.

**Comment by tim-st** [comment]
According to the docs my code is valid:
>The variable's type is inferred from the value on the right hand side. To force a different type, use type conversion: the expression `T(v)` converts the value `v` to the type `T`.

<https://github.com/vlang/v/blob/master/doc/docs.md#consts--variables>

**Comment by medvednikov** [comment]
You can't cast an int to a string, you need to convert it, which requires CPU resources.

**Comment by tim-st** [comment]
>You can't cast an int to a string, you need to **convert** it

Excactly, that's what I wanted to do with the syntax and according to the docs

>To force a different type, use **type conversion**: the expression `T(v)` **converts** the value `v` to the type `T`

so I assumed this works.

**Comment by medvednikov** [comment]
Fixed:
```
error: use `number.str()` instead of `string(number)`
```

**Comment by tim-st** [comment]
The following still crashes
```v
fn a() string {
	return string("")
}

fn main() {
	v := a()
	println(v)
}
```

It should work for all types.
