### ISSUE TITLE
Spaces in file path breaks vfmt

### ISSUE THREAD

**Issue by hungrybluedev** [vlang/v#4718]
**V version:** 0.1.26 50a8373.a4b6c3f
**OS:** Problem replicated on Windows, Linux, and MacOS

**What did you do?**

I performed the following steps:
1. Create a new project (empty directory) with the name `Spaced Path`. Can be anything else that contains a space in the name.
2. Create a file `test.v`. There is no need to type anything inside it.
3. Run `v fmt test.v` from inside the directory.

**What did you expect to see?**

Formatting info, or no error output at all.
 
**What did you see instead?**

```
scanner error: /[path/to]/Spaced doesn't exist
vfmt error while formatting file: test.v .
Encountered a total of: 1 errors.
```

**What could be the potential problem?**

vfmt cannot process paths containing spaces. It treats one path name as two arguments.

**Comment by spytheman** [comment]
Should be fixed in 74005b43624b0c145840164768189cbb0ec3da80
