### ISSUE TITLE
interface array push please check  node.right_type != info.elem_type

### ISSUE THREAD

**Issue by wilesun** [vlang/v#4721]
**V version:0.1.26** 
**OS:ubuntu** 

**What did you do?**
	elem_type_str := g.typ(info.elem_type)
			g.write('array_push(&')
			g.expr(node.left)
			g.write(', &($elem_type_str[]){ ')
			elem_sym := g.table.get_type_symbol(info.elem_type)
			if elem_sym.kind == .interface_ && node.right_type != info.elem_type {
				g.interface_call(node.right_type, info.elem_type)
			}
			g.expr_with_cast(node.right, node.right_type, info.elem_type)
			if elem_sym.kind == .interface_  && node.right_type != info.elem_type {
				g.write(')')
			}

**What did you expect to see?**
 
**What did you see instead?**

**Comment by wilesun** [comment]
Methods wrapper for interface,don't use memdup the object,so keep interface object is same object address
`interface_index_name := '_${interface_name}_${cctype}_index'
			cast_functions.writeln('
_Interface I_${cctype}_to_Interface_${interface_name}(${cctype}* x) {
	return (_Interface) {
		._object = (void*) (x),
		._interface_idx = ${interface_index_name}
	};
}')`

**Comment by spytheman** [comment]
It is not clear what this is supposed to demonstrate.
