### ISSUE TITLE
freestanding is not freestanding

### ISSUE THREAD

**Issue by alula** [vlang/v#4724]
Basically the problem is that current `-freestanding` target works actually more like `linux-amd64-static`.
`freestanding` (or `bare metal`) means the application is FREE-STANDING - it DOES NOT depend on underlying operating system, runs on bare hardware, manages it's resources itself.

Currently the only way to build a freestanding program using V is specifying custom `vlib` which is still pretty hacky due to frequent changes to V and unnecessary headers/defines in prelude added by compiler - just look at [vOS](https://github.com/vlang/vos).

- V's "freestanding" target includes Linux/amd64 syscall wrappers - not only completely missing the point of "freestanding" but the functions are also public which pollutes global scope: https://github.com/vlang/v/blob/5664cbd3d06e9238d46fa957d9c3d59f6c20577b/vlib/builtin/bare/linuxsys_bare.v
- V's "freestanding" target relies on underlying operating system (Linux/amd64) for memory management, what's worser - doesn't even use own memory allocator to allow efficient usage of that memory - each `malloc()` call just allocates an enough amount pages (which is not only inefficient on small `malloc()`s but the page size is also HARDCODED and not necessarily 4k bytes long): https://github.com/vlang/v/blob/5664cbd3d06e9238d46fa957d9c3d59f6c20577b/vlib/builtin/bare/mm_bare.v 
- V's "freestanding" target expects that the program is able to exit - but how if there's no operating system and no concept of process, thread of even lifetime? https://github.com/vlang/v/blob/5664cbd3d06e9238d46fa957d9c3d59f6c20577b/vlib/builtin/bare/builtin_bare.v#L23

**Comment by dumblob** [comment]
Partially related: https://github.com/vlang/v/issues/2761#issuecomment-621329529

**Comment by crthpl** [comment]
Fixed by #9624
