### ISSUE TITLE
returning `none` is allowed for non-optionals

### ISSUE THREAD

**Issue by tim-st** [vlang/v#4728]
**V version:** 
V 0.1.26 50a8373.f9fe5b6
**OS:** 
linux amd64

**What did you do?**
```v
fn a() string {
  return none
}


fn main() {
    v := a()
    println(v)
}
```
See <https://github.com/vlang/v/commit/869444cec6aa1925bf72f11909efc048a239f849>

**What did you expect to see?**
Compiler error: expected type string, got type Optional[string]
 
**What did you see instead?**
compiler crash

**Comment by tim-st** [comment]
Related (likely the other side) https://github.com/vlang/v/issues/4713

**Comment by medvednikov** [comment]
Fixed:

```
error: cannot use `none` as type `string` in return argument
````
