### ISSUE TITLE
Can't install V Lang

### ISSUE THREAD

**Issue by joao2391** [vlang/v#4731]
**V version:** 0.1.24 
**OS:** Windows 10 Home 

**What did you do?**
Downloaded the Zip file from [V Lang website](https://vlang.io/) and extract it.
After that, I try to run the "v.exe" as adm but nothing happens.

**What did you expect to see?**
A successful message (?)
 
**What did you see instead?**
print_back_trace_skipping_top_frames is not implemented on this platform for now...

**Comment by medvednikov** [comment]
I'll update the binaries today and let you know once they are live.

**Comment by joao2391** [comment]
@medvednikov OK, thank you.

**Comment by logTom** [comment]
@joao2391 In case you missed it, the 0.1.27 release for windows can be downloaded here:
https://github.com/vlang/v/releases/download/0.1.27/v_windows.zip

**Comment by joao2391** [comment]
@logTom Thank you!

**Comment by medvednikov** [comment]
Yeah, I forgot to write an update here :)
