### ISSUE TITLE
Can I declare multiple variables at once in V?

### ISSUE THREAD

**Issue by fuyutarow** [vlang/v#474]
I can declare multiple variables at once in Go.
```go
x, y := "Hello", 10
```
Now I cannot in V. Will V provide define syntax for multiple variables?

**Comment by whoizit** [comment]
I do not think that it is well read. It seems beautiful, but it is hard to read. Better way is write it - line by line.
```
x := "Hello"
y := 10
```

**Comment by fuyutarow** [comment]
I do not think that it is well read. 
```
inputs := os.get_line().split(' ') // '2019 6 20' as a standard input
a := inputs[0].to_i()
b := inputs[1].to_i()
c := inputs[2].to_i()
```
This way is cool.
```
a, b, c := os.get_line().split(' ')
```
or
```
a, b, c := os.get_line().split(' ').map(int) // future
``` 
Is this still a bad idea?

**Comment by whoizit** [comment]
Now it's not bad idea, but if  only one `inputs` you get?

**Comment by fuyutarow** [comment]
Just idea.
```
$ a := os.get_line().split(' ') // 'hello' as a standard input
$ println(a)
['hello']
```
```
$ a, _ := os.get_line().split(' ') // 'hello' as a standard input
$ println(a)
'hello'
```

**Comment by DoctorGester** [comment]
What you are talking about is destructuring, not just multiple variable declaration.

**Comment by medvednikov** [comment]
Destructuring will be supported.

**Comment by nedpals** [comment]
**Update**:
Declaring multiple variables at once now works with the new backend.
> a, mut b, c := 'v', 'is', 'vood'
