### ISSUE TITLE
Android standalone App support?

### ISSUE THREAD

**Issue by xandro0777** [vlang/v#4740]
Hi,

I see it can be used in termux - will creation of standalone apps also be supported? GUI?

**Comment by medvednikov** [comment]
Yes and yes

**Comment by radare** [comment]
it's easier to do that for iOS

**Comment by leahlundqvist** [comment]
@radare but possible on both :)

**Comment by alula** [comment]
nothing stops you from generating C code and building it into JNI library

**Comment by xandro0777** [comment]
On May 8, 2020 4:16:53 AM GMT+02:00, "Julia K." <notifications@github.com> wrote:
>nothing stops you from generating C code and building it into JNI
>library

true, many people could do that and would end up repeatedly wiritng lots of almost identical boilerplate code and making incompatible design decissios.

Did anyone think about the design decissions yet?
* should apps handle save/suspend/resume by low-level code, should there be some abstraction or should it be possible to write completely portable code for Linux/Windows/Android without worrying  or even knowing about this issue?
* should the Linux GUI be used for Android (easy and quick start) or native Android GUI?
* how about the manifest file etc?

I know a lot more about Android than IOS but thinking similar concepts should work on both platforms?

**Comment by dumblob** [comment]
Maybe this could be enough: https://github.com/cnlohr/rawdrawandroid

**Comment by Larpon** [comment]
We now have [vab](https://github.com/Larpon/vab).
