### ISSUE TITLE
Uppercase letters not checked within interfaces

### ISSUE THREAD

**Issue by tim-st** [vlang/v#4745]
**V version:** V 0.1.27 b627bb9
**OS:** linux amd64

**What did you do?**
```v
module io

pub interface Reader {
    Read(p mut []byte) ?int
}

pub interface Writer {
    Write(p []byte) ?int
}

pub fn copy(dst Writer, src Reader) ?i64 {
    return i64(0)
}

```

**What did you expect to see?**
Since function names are not allowed to contain uppercase letters, interface methods containing uppercase letters could never be fulfilled.
I expect the same error message there like in function definition.

**What did you see instead?**
Compiles.

**Comment by medvednikov** [comment]
Fixed.
