### ISSUE TITLE
Funny undefined behaviour

### ISSUE THREAD

**Issue by radare** [vlang/v#4781]
**V version:** V 0.1.27 8866773
**OS:** macOS 10.15

**What did you do?**

```go
$ cat ub.v
struct Foo {
	foo string
}

fn db() &Foo {
	a := &Foo{}
	return a
}

fn ub() &Foo {
	a := Foo{}
	return &a
}

fn main() {
	a := db()
	b := ub()
	println('db $a')
	println('ub $b')
}
```

**What did you expect to see?**

A compile time error because local vars shuolkdnt be returned as a reference, or the heaped struct to be allocaed before returning

**What did you see instead?**

this weird thing

```go
$ v run ub.v
db &Foo {
    foo: ''
}
ub &Foo {
    foo: 'db &Foo {
    foo: ''
}'
}
```

**Comment by Delta456** [comment]
Still reproducible with the latest V.

**Comment by danieldaeschle** [comment]
Does this still happen under macos? under wsl2 everything works fine! Reopen if not.

**Comment by radare** [comment]
yep its fixed now
