### ISSUE TITLE
Better error message in v install

### ISSUE THREAD

**Issue by radare** [vlang/v#4784]
**V version:** V 0.1.27 847a103
**OS:** macOS 10.5

**What did you do?**

```
$ v install toxml
```

**What did you expect to see?**

afaik all v modules  require a dot in its name to separate the author from the library name. I would expect a better error like:

`Please specify the author. before the module name. Did you mean v search $1` 

**What did you see instead?**

```
$ v install toxml
Errors while retrieving meta data for module toxml:
Invalid json data
404...
Invalid json data
<style>
body {
  margin: 0; }

* {
  font-family: "Roboto", "Helvetica Neue";
  line-height: 1.5;
} ...
```

**Comment by dhonx** [comment]
I think `vpm` must respond it with HTTP status code `404` instead of return 200 with `404` text.

**Comment by spytheman** [comment]
@dhonx you are right. A proper status code would be better in that situation.

**Comment by radare** [comment]
Agree
