### ISSUE TITLE
CSV read fails on empty line in a multiline field

### ISSUE THREAD

**Issue by jm-duro** [vlang/v#4797]
**V version:** V 0.1.27 1c8d2c2
**OS:** Linux Debian 10 AMD64

**What did you do?**

import os
import encoding.csv

fn main() {
    data := os.read_file("test_csv.csv") or {
                eprintln('File "test_csv.csv" could not be read')
                return
        }
    mut csv_reader := csv.new_reader(data)
    csv_reader.delimiter = `;`

    mut row_count := 0
    for {
        row := csv_reader.read() or {
            break
        }
        row_count++
        println("[${row_count:2d}] ${row}")
    }
}

Content of test_csv.csv:

"<builtin>";"s string";"Yes";"strip_margin_custom(del byte) string";;;FAUX;"builtin/string.v:1330";""
"<builtin>";"s string";"Yes";"strip_margin() string";"Allows multi-line strings to be formatted in a way that removes white-space
before a delimeter. by default `|` is used.
Note: the delimiter has to be a byte at this time. That means surrounding
the value in ``.

Example:
st := 'Hello there,
      |this is a string,
      |    Everything before the first | is removed'.strip_margin()
Returns:
Hello there,
this is a string,
    Everything before the first | is removed";;FAUX;"builtin/string.v:1327";""
"<builtin>";;"Yes";"strlen(s byteptr) int";;;FAUX;"builtin/bare/string_bare.v:9";""

**What did you expect to see?**

All lines displayed
 
**What did you see instead?**

[ 1] ['<builtin>', 's string', 'Yes', 'strip_margin_custom(del byte) string', '', '', 'FAUX', 'builtin/string.v:1330', '']
[ 2] ['<builtin>', 's string', 'Yes', 'strip_margin() string']
[ 3] ['before a delimeter. by default `|` is used.']
[ 4] ['Note: the delimiter has to be a byte at this time. That means surrounding']
[ 5] ['the value in ``.']
V panic: string index out of range: 0 / 0
                                               | 0x5607af23f92c | /home/duro/Data/Vlang/test_csv(+0x1592c) 
                                               | 0x5607af245392 | /home/duro/Data/Vlang/test_csv(+0x1b392) 
                                               | 0x5607af244fd3 | /home/duro/Data/Vlang/test_csv(+0x1afd3) 
                                               | 0x5607af24dabe | /home/duro/Data/Vlang/test_csv(+0x23abe) 
                                               | 0x7fbf7e7e709b | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) 
                                               | 0x5607af22c44a | /home/duro/Data/Vlang/test_csv(+0x244a)

**Comment by jm-duro** [comment]
Also it should not affect a multi-line field to different records. The CSV test file has only 3 records.

**Comment by yuyi98** [comment]
Can you provide a complete example of a mistake?

**Comment by jm-duro** [comment]
Sorry, but I don't understand. The example is complete: v source, csv file and debug log.

**Comment by yuyi98** [comment]
OK, I've reproduced this mistake.
