### ISSUE TITLE
implement `context.Context`

### ISSUE THREAD

**Issue by si3nloong** [vlang/v#4798]
It's pretty common`context.Context` is practicing inside`golang`, and I hope this should be implemented in v lang as well

**Comment by thearchitect** [comment]
`context.Context` of Golang is a great lifecycle management tool. Do you have any plans to implement such concept in V?

**Comment by nedpals** [comment]
Closed. Context support is already implemented. See the module docs for more details:
https://modules.vlang.io/context.html
