### ISSUE TITLE
Error on REPL

### ISSUE THREAD

**Issue by buttercrab** [vlang/v#4802]
**V version: 0.1.27** 
**OS: MacOS 10.15** 

**What did you do?**
I opened v repl and typed:

```v
For usage information, quit V REPL using `exit` and use `v help`
V 0.1.27 3eeef62
Use Ctrl-C or `exit` to exit
>>> fn main() {}
>>> main()
error: redefinition of function `main`
    3 | }
    4 |
    5 | main()
      |   ^
```

**What did you expect to see?**
no output without error
 
**What did you see instead?**
error

**Comment by medvednikov** [comment]
there's already fn main in REPL, so you are defining a second main, it's an error, and it's expected

**Comment by buttercrab** [comment]
@medvednikov Then, should be the error on `fn main(){}` line? That's where the `main()` function declared.
