### ISSUE TITLE
for-in reverse order

### ISSUE THREAD

**Issue by dumblob** [vlang/v#4809]
Any way how to iterate over ordered iterables (map, array, ...) in reverse order?

(without explicitly reversing them beforehand as that's way too slow)

**Comment by nedpals** [comment]
I would say C-style loops would suffice but thats just my opinion.

```v
module main

fn main() {
    names := ['Abby', 'Bob', 'Carl']
    
    for i := names.len-1; i >= 0; i-- {
        println(names[i])
    }
}
```

**Comment by Delta456** [comment]
Just use reverse method and then iterate?

```v
names = ['Tom', 'Jack', 'Peter']
for name in names.reverse() {
      ... // do stuff
}
```

**Comment by nedpals** [comment]
@Delta456 He said "without explicitly reversing them beforehand as that's way too slow" so `.reverse()` is the way to go forward.

**Comment by nedpals** [comment]
@Delta456 He said "without explicitly reversing them beforehand as that's way too slow" so `.reverse()` is not the way to go forward.

**Comment by sudo-nice** [comment]
Using `.reverse()` seems to be pretty fast.

```v
// straight.v
fn main() {
  mut names := []int{}
  for i in 0..100000 {
    names << i
  }
  for i in names {
    i + 1
  }
}
```

```v
// reverse.v
fn main() {
  mut names := []int{}
  for i in 0..100000 {
    names << i
  }
  for i in names.reverse() {
    i + 1
  }
}
```

```
$ hyperfine ./reverse ./straight                                                                 mtime⮝
Benchmark #1: ./reverse
  Time (mean ± σ):       1.6 ms ±   0.3 ms    [User: 1.2 ms, System: 0.3 ms]
  Range (min … max):     0.6 ms …   3.0 ms    1794 runs

  Warning: Command took less than 5 ms to complete. Results might be inaccurate.

Benchmark #2: ./straight
  Time (mean ± σ):       1.6 ms ±   0.3 ms    [User: 1.2 ms, System: 0.3 ms]
  Range (min … max):     0.6 ms …   2.7 ms    1393 runs

  Warning: Command took less than 5 ms to complete. Results might be inaccurate.

Summary
  './straight' ran
    1.02 ± 0.28 times faster than './reverse'
```

**Comment by medvednikov** [comment]
Yeah, if you need speed, use a C style for loop, otherwise `.reverse()`.

We might optimize this in the future.

No need to complicate the language.

**Comment by dumblob** [comment]
I'm looking for a solution for **all** ordered iterables, not just `array` (that's what I explicitly asked in the initial post). Also as @nedpals correctly pointed out, I'm explicitly **not** looking for a solution with an ahead-of-time reversal. Let's assume at least `map` (because `array` is too specific as it allows lots of ways to iterate over and whole bunch of optimizations).

@sudo-nice btw benchmarks on regular computers with non-realtime os being less than 10 seconds don't have absolutely any value. More so if it's just primitive types (like `int` in your example) and/or types with fixed width or even types with their size known in compile-time. Last but not least, please never use any constants in any benchmarks as compiles are extremely, but I mean really extremely clever nowadays. So always pass any such options as arguments to a compiled binary (in your case it's `0`, `100000`, `1`).

**Comment by medvednikov** [comment]
@dumblob you were given a solution, a `for ;;` loop. Maps are not ordered in V.

**Comment by sudo-nice** [comment]
@dumblob good points, thank you.

**Comment by dumblob** [comment]
>Maps are not ordered in V.

Correct, the **default** built-in map is not ordered (btw I predict, that at some point it will become ordered - judging based on basically any other high-level language which got enough widespread because it's enormously useful and corresponding algorithms perform close to those of high-quality unordered maps).

Should an ordered reversed iteration of an arbitrary ordered iterable be always done with a counted for or while loop (I know *V* has no `while` but I refer to the concept, not to the keyword)? I.e. by using `.next()` and `.prev()` methods?

Are there really no plans for any dedicated syntax or at least reserved method names (e.g. `.next()`, `.prev()`, `.begin()`, `.end()`) and some standardized way for iteration (like [ranges](https://en.wikipedia.org/wiki/Range_(computer_programming)#Range_as_an_alternative_to_iterator ) instead of [iterators](https://en.wikipedia.org/wiki/Iterator ) because ranges can be indexed and have length - thus can be iterated in reverse order - unlike iterators)?
