### ISSUE TITLE
pub mut access modifier not working

### ISSUE THREAD

**Issue by Viza74** [vlang/v#481]
I tried to create a simple vector2 module.

If I define the struct as:
```
struct Vec2 {
    pub mut:
	x float
	y float
}
```

I get the error:

```
check()
next token = `:`
pass=1 fn=``
panic: vec2.v:6
expected `:` but got `mut`
```

If I define as:
```
struct Vec2 {
    pub:
	x float
	y float
}
```

I get the error
```
pass=2 fn=`main`
panic: vec2test.v:10
cannot modify public immutable field `x` (type `vec2.Vec2`)
```
when I try to modify x

If I define as:
```
struct Vec2 {
    mut:
	x float
	y float
}
```

I get the error
```
pass=2 fn=`main`
panic: vec2test.v:10
cannot refer to unexported field `x` (type `vec2.Vec2`)
```
when I try to modify x

Is this a bug, or am I doing something wrong?

**Comment by zenith391** [comment]
I think it's not a bug as it is on the [documentation](https://vlang.io/docs#mod). i hope it get fixed soon as i need it

**Comment by LouCle** [comment]
:rocket: Thanks @Henrixounez!

**Comment by Viza74** [comment]
Thanks!
