### ISSUE TITLE
lambda and anonymous function

### ISSUE THREAD

**Issue by sina-carbon** [vlang/v#4810]
What is the syntax of the lambda and anonymous function?

**Comment by nedpals** [comment]
@sina-carbon same as you declare a function. Take note that you **can't** use variables of the parent function.

```v
fn main() {
    an := fn () {
         return 1+1
    }
}
```

**Comment by sina-carbon** [comment]
@nedpals 
ok , and lambda ?

**Comment by nedpals** [comment]
@sina-carbon AFAIK they're the same.

**Comment by sina-carbon** [comment]
@nedpals thanks
