### ISSUE TITLE
Windows Line Endings

### ISSUE THREAD

**Issue by joe-conigliaro** [vlang/v#482]
Hi @medvednikov, the line ending issue is still happening on windows, I just rebuild v from the newest source and if i use the repl the temporary vrepl.v file it creates has windows line endings and i get this error:
```
(char code=0) pos=36 len=38
panic: vrepl.v:3
invalid character ``
```
The same thing happend if i try compile any other .v file, if i make sure the file has unix line endings it compiles properly no issues.
Note: All the v lib files also need unix line endings

**Comment by medvednikov** [comment]
Hi

Can you try `v any_v_program.v` instead?

**Comment by medvednikov** [comment]
Ah sorry, missed it. You already did it.

**Comment by joe-conigliaro** [comment]
Yeah thay works, and if i open up the vrepl.v and change the line endings to unix then run v.exe vrepl.v it works fine, so its definitely the line endings

**Comment by joe-conigliaro** [comment]
Weird, I'm guessing this is the part of the parser on line 309, it looks right:
```
	case `\r`:
		if nextc == `\n` {
			s.pos++
			return scan_res(NL, '')
		}
```

**Comment by joe-conigliaro** [comment]
@medvednikov I had originally built vc.exe from v.c then used that to build v.exe from the latest source.
That v.exe is the v version I have been testing with, but I just realised I cannot build v again with this version, and the c code it generates looks a lot different that what vc.exe generated. So I dunno whats going on

**Comment by joe-conigliaro** [comment]
@medvednikov I just realised that the reason whats going on:
I first built the compiler with: vc.exe v v/compiler
which gives working v.exe.
then if i try: v.exe vnew v/compiler
I get: No input .v files
So i was trying with: : v.exe vnew v/compiler/*.v
However that dosen't work (seems to only compile token.v)
