### ISSUE TITLE
Warn if wider types are being coerced into narrower ones

### ISSUE THREAD

**Issue by hungrybluedev** [vlang/v#4829]
I faced some difficulty while trying to implement rational arithmetic for `math.fractions`. I was experiencing overflows while testing in cases where `i64`s should not have overflowed. It turns out that the problem was the type of an intermediate variable being set to `int` inadvertently, instead of `i64`.

My suggestion is to:

_Warn the user if results of wider types (eg `i64`) are being assigned to variables or return expressions of narrower type (eg `int`)_

**Comment by medvednikov** [comment]
It should return an error. Can you paste the code that didn't?

**Comment by hungrybluedev** [comment]
demo.v

```v
module main

fn main() {
	// These are i64s that we want to assign to n
	u1 := i64(0x80000000)
	u2 := i64(0x10000000)
	v1 := i64(0x20000000)
	v2 := i64(0x40000000)
	// n1 is i64, n2 is int
	mut n1 := i64(0)
	mut n2 := 0
	n1 = u1 * v2 - u2 * v1
	n2 = u1 * v2 - u2 * v1
	println('${n1:x}')
	println('${n2:x}')
}
```

Output:

```
1e00000000000000
0
```

Here `n1` is correct, but `n2` overflows.

**Comment by medvednikov** [comment]
Thanks, this definitely wouldn't compile with the old backend. Will fix.

**Comment by hungrybluedev** [comment]
Currently, this example does not compile, which is the intended behaviour:
```
foo.v:13:7: error: cannot assign to `n2`: expected `int`, not `i64`
   11 |     mut n2 := 0
   12 |     n1 = u1 * v2 - u2 * v1
   13 |     n2 = u1 * v2 - u2 * v1
      |          ~~~~~~~~~~~~~~~~~
   14 |     println('${n1:x}')
   15 |     println('${n2:x}')
```
