### ISSUE TITLE
/usr/bin/ld: cannot open output file test: Is a directory

### ISSUE THREAD

**Issue by whoizit** [vlang/v#483]
if dir with `<name>` exist and file with `<name>.v` exist  I getting this error

```
$ touch rambo.v
$ mkdir rambo
$ v rambo.v 
Generating main()...
/usr/bin/ld: cannot open output file rambo: Is a directory
collect2: error: ld returned 1 exit status
V panic: clang error
```
```
$ rmdir rambo
$ v rambo.v 
Generating main()...
```

**Comment by AurelienFT** [comment]
@whoizit It's not a bug. When V want to create a binary and you didn't specify the name, he will create it by the name of the file. So he can't create it because it's already a folder.

If you understand and have no more things to addyou can close the issue.
