### ISSUE TITLE
Compiling graphical program with mingw

### ISSUE THREAD

**Issue by thisisleobro** [vlang/v#4854]
I have V 0.1.27 compiled with gcc version 7.3.0 (i686-posix-dwarf-rev0, Built by MinGW-W64 project) on win10

The compilation went okay but i cant get to compile tetris or any other graphical program.
I followed to steps to install freetype bu i believe mingw is not supported for graphical programming since the statics libs for glfw and freetype are on msvc abi compatible only format (.lib)

What are your suggestions in order to run these examples. I would pull the dependencies myself if v can link to .a libs. What the name of  the folder i should place the .a files. i see that .libs are inside a folder callesd msvc

Sorry about my english

EDIT: it actualy says "fatal error: ft2build.h: No such file or directory" even tho i see that this file exists. I even tried adding the -I flag to add include folder bu still doesnt work

**Comment by yuyi98** [comment]
`freetype` must be installed in thirdparty.
You can use the command-line tool `v setup-freetype`.

**Comment by thisisleobro** [comment]
> It can run normally under MINGW.
> `freetype` must be installed in thirdparty.
> You can use the command-line tool `v setup-freetype`.

Have you tried compiling with mingw?
I did all that and indeed there is freetype folder in thirdyparty but it has a .lib file which is a visual studio only static library

**Comment by yuyi98** [comment]
gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)
```
C:\Users\yuyi9\v>make
Building V
Downloading v.c...
Attempting to build v.c with GCC...
V self compiling ...
V build OK!
V 0.1.27 712fd38.1c8e14c
```

Compiler
```
C:\Users\yuyi9\v\examples\tetris>v run tetris.v
tetris.v:192:6: warning: unused variable: `i`
  190 |     g.field = [] // TODO: g.field = [][]int
  191 |     // Generate the field, fill it with 0's, add -1's on each edge
  192 |     for i in 0..FieldHeight + 2 {
      |         ^
  193 |         mut row := [0].repeat(FieldWidth + 2)
  194 |         row[0] = - 1
```

Snapshot
![tetris](https://user-images.githubusercontent.com/6949593/81628662-d837cd00-9433-11ea-997b-2797f033e336.png)

**Comment by nedpals** [comment]
@thisisleobro I suggest you use the appropriate version of MinGW since the libraries are compatible for x86 MinGW and not i686 MinGW.

**Comment by yuyi98** [comment]
Yes, the problem should be here.

In vlib/freetype/freetype.v:
> #flag windows -L @VROOT/thirdparty/freetype/win64

It only use win64 version of freetype.

**Comment by thisisleobro** [comment]
> Yes, the problem should be here.
> 
> In vlib/freetype/freetype.v:
> > #flag windows -L @VROOT/thirdparty/freetype/win64
> 
> It only use win64 version of freetype.

Could you share your folder structure please? I'll try setting the appropriate version of freetype. Maybe it could work

**Comment by yuyi98** [comment]
I think you should setup x64 version mingw.
`gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)`

**Comment by thisisleobro** [comment]
> I think you should setup x64 version mingw.

I have a 32 bit OS

**Comment by nedpals** [comment]
@thisisleobro Not sure if 32-bit is supported but still you need to use `x86_64` to able to compile the libraries.

**Comment by thisisleobro** [comment]
@nedpals i dont quite get what libraries needed to be compiled with x64. Shouldnt they be compiled with the same compiler i used to build v?

**Comment by nedpals** [comment]
@thisisleobro They should be. However you're using a version of MinGW that cannot compile with the 64-bit versions of the GLFW and FreeType library. Try download the 32-bit versions of the two libraries, copy it to their respective folders, then try compiling it again. :)

FreeType: https://github.com/ubawurinna/freetype-windows-binaries
GLFW: https://www.glfw.org/download.html

We still strongly advise that you run the examples on an appropriate system to prevent further problems.

**Comment by thisisleobro** [comment]
@nedpals i dont have a 64bit pc. Its not like i dont want to use the 64bit version. I already built the 32 bit version of freetype. I just dont know where to put the libs since i dont know where v will search for them

**Comment by nedpals** [comment]
@nedpals I see. In this case, just go to the folder where the V compiler is installed and go to the `thirdparty/` folder then paste the libs to its resepective folders.

**Comment by JalonSolov** [comment]
v doesn't look for the dlls, only the binary you create will look for them.

You can either paste a copy in every directory where they might be needed, or just add the thirdparty/ directories where they are to your path.

**Comment by emily33901** [comment]
> v doesn't look for the dlls
I know that it used to... (only becuase mingw lets you use one as input instead of a .a that specifies a shared lib)

**Comment by thisisleobro** [comment]
> v doesn't look for the dlls, only the binary you create will look for them.

yes. but i still need to link to the .dll.a
 
> You can either paste a copy of the dlls everywhere they might be needed, or add the directories where the dlls are to your path so they can be found.

thats not really the problem since i am not even able to compile the binary

**Comment by JalonSolov** [comment]
glfw is no longer used.  Update to the latest version of v to get the changes.

**Comment by thisisleobro** [comment]
> glfw is no longer used. Update to the latest version of v to get the changes.

That is really nice to know
