### ISSUE TITLE
compile with -prod errors out on unused variable

### ISSUE THREAD

**Issue by gshields** [vlang/v#4862]
with :
clang --version
clang version 10.0.0-4ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
uname -a
Linux 6540 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
V has been successfully built
V 0.1.27 712fd38
nbody.v:127:5: error: unused variable: `i` 
  125 | 
  126 | println('${energy(sys):.9f}')  //-0.169075164
  127 | for i in 0..50000000 {
      |     ^
  128 |     advance(mut sys, 0.01)
  129 | }
tetris.v:192:6: error: unused variable: `i` 
  190 |     g.field = [] // TODO: g.field = [][]int
  191 |     // Generate the field, fill it with 0's, add -1's on each edge
  192 |     for i in 0..FieldHeight + 2 {
      |         ^
  193 |         mut row := [0].repeat(FieldWidth + 2)
  194 |         row[0] = - 1
```

**Comment by JalonSolov** [comment]
That is a feature of the language.  Unused variables are a warning in regular builds, error in -prod builds.

Since you are not using the variable, replace it with underscore, `_`
