### ISSUE TITLE
Make v.c C89 compatible

### ISSUE THREAD

**Issue by lygstate** [vlang/v#4867]
We can force V.c genearting C89 compatiable code for broader usage.
Bring V to old Compiler and OS.

**Comment by medvednikov** [comment]
Yeah should be easy. Just checked it's only `inline` and `for (int i...`

**Comment by lygstate** [comment]
inline we could use macro __v_inline instead. two thing need fix for (int i and // comment

**Comment by lygstate** [comment]
And also need place all variable decl at the very begnning

**Comment by lygstate** [comment]
My target is to support as old as GCC 2.9.x and VC 6.0

**Comment by dumblob** [comment]
@lygstate I hope *V* will use [`restrict`](https://github.com/vlang/v/issues/1839 ) at some point, so keep that in mind.

Btw. would be cool to have *V* on such old systems!

**Comment by spytheman** [comment]
I am curious, who uses such old compilers these days?

**Comment by lygstate** [comment]
Think about COBOL. and FORTRON

**Comment by lutherwenxu** [comment]
This is more of a request than a bug so I'm switching to that.
(It doesn't break any promised behavior.)

**Comment by lygstate** [comment]
Yeap, C is genearted code, so we have no need to use C99 or even C11.

**Comment by dumblob** [comment]
@lygstate see e.g. https://github.com/vlang/v/issues/4867#issuecomment-628249610 above (`restrict` was introduced in C99) and there are also other, usually performance related reasons to use C11 or newer.

**Comment by lygstate** [comment]
It's OK for restrict , we can define it to none for C89

**Comment by lygstate** [comment]
#define restrict 
is enough for C89 compiler.

**Comment by medvednikov** [comment]
V uses too many new features now, this would be too much work for unclear gains.
