### ISSUE TITLE
[bug] - vlang.io archive not the same of Github archive

### ISSUE THREAD

**Issue by Olyno** [vlang/v#4875]
**V version:** V 0.1.27 5f7a8df
**OS:** Windows 10

**What did you do?**

I tried to use vlang from release archive.

**What did you expect to see?**

I expected to see V work.
 
**What did you see instead?**

Some commands are missing, are not working fine.

**Comment by Olyno** [comment]
Website's archive is not the same of Github archive. That's the reason why it doesn't work fine.

**Comment by JalonSolov** [comment]
Version from the downloaded .zip is out of date

```
PS X:\v_windows> v -v
V 0.1.26 50a8373
PS X:\v_windows>
```

**Comment by JalonSolov** [comment]
The path is wrong for the "Download for Windows" button.  It is pointing to

https://github.com/vlang/v/releases/download/0.1.24/v_windows.zip

**Comment by JalonSolov** [comment]
Last thing... new releases are not being built every time.  The /releases page currently says
```
0.1.27

@medvednikov medvednikov released this yesterday · 145 commits to master since this release
```

**Comment by medvednikov** [comment]
This is not entirely true. Github is using tags for releases, but I built these yesterday, so it's not 145 commits behind.

**Comment by medvednikov** [comment]
Also, the path is now going to always point to the latest release.
