### ISSUE TITLE
Implement a cross-platform snprintf in V for platform consistence.

### ISSUE THREAD

**Issue by lygstate** [vlang/v#4876]
https://github.com/weiss/c99-snprintf/blob/master/snprintf.c
for V, we called it as v_snprintf

**Comment by lygstate** [comment]
we can restrict the sematics, such as 
%d %l are 32bit
%lld are 64bit.
%i32d and 32bit
%*s are string with length. We can used a fixed standard across platform and don't care
about the target-platform we used.
C/Js would be consistence.

**Comment by JalonSolov** [comment]
There is a v_sprintf as of end of April.  v_snprintf should be a minor modification of that, just to limit the output length.

**Comment by lygstate** [comment]
see that, seems lack of %*s and intptr support

**Comment by JalonSolov** [comment]
Add them, and you'll have it for both.  :-)

**Comment by lygstate** [comment]
Yeap, I have the intension

**Comment by penguindark** [comment]
@lygstate v_sprintf work near as you wrote :) 
`*s` is supported but not documented, but you can find it in the tests in `v/vlib/strconv/format_test.v`.
About the size of the format for decimals please have a look at documentation in `v/vlib/strconv/format.md`
Any new help is very welcome :)

**Comment by lygstate** [comment]
Gocha, then this is not an issue anymore:) May the issue comes to be remove all snprintf usage in v.c

**Comment by lygstate** [comment]
Is there any thing to printf intptr_t? It's seems v doesn't have intptr_t at all? and also the uintptr_t
size_t I think are equal to uintptr_t

**Comment by penguindark** [comment]
I think that user `%p` with a cast like `voidptr(your_ptr)` can be suffice.
`v_sprintf("%p",voidptr(your_pointer))`

**Comment by lygstate** [comment]
does voidptr are integer? i think %p are hex. but intptr are integer:)

**Comment by penguindark** [comment]
if you want an integer do simply: `u64(your_ptr)` and use o print it like an int :)
`v_sprintf("%ld",u64(your_ptr))`
C is under the hood of V, all pointers are u64 or u32 in 32bit platforms

**Comment by lygstate** [comment]
good idea, wonderfull:)

**Comment by lygstate** [comment]
So if I wanna to do address calc, always using i64:)
