### ISSUE TITLE
vfmt removes `len` and `default` from array declaration

### ISSUE THREAD

**Issue by hungrybluedev** [vlang/v#4881]
**V version:** 0.1.27 478ebed
**OS:** Linux

**What did you do?**

Run `vfmt` on

```v
module main
fn main() {
    a := []int{len:10}
    println('$a')
}
```

**What did you expect to see?**

The source remain unaffected.
 
**What did you see instead?**

The length specifier is removed.

```v
module main
fn main() {
    a := []int{}
    println('$a')
}
```

The same thing happens for `default`.

**Comment by medvednikov** [comment]
Fixed
