### ISSUE TITLE
Unknown error in https://vlang.io/play "JSON decoding/encoding"

### ISSUE THREAD

**Issue by andreabravetti** [vlang/v#4892]
**What did you do?**
Run "JSON decoding/encoding" in https://vlang.io/play 

**What did you expect to see?**
A result
 
**What did you see instead?**
It print "You just found a bug. V can't compile this program, but it should. Please create a GitHub issue."

It may be related to #4779.

**Comment by dhonx** [comment]
Thanks for reporting @andreabravetti... If you want to play around with V, I recommend using https://devbits.app/play for now

**Comment by JalonSolov** [comment]
Looks like the only issue is the playground is calling an "old" version of v to run the code.

The json example is (almost... a space here or there...) identical to examples/json.v, which runs fine with the current version of v.

**Comment by medvednikov** [comment]
I've updated it to the latest V.

The problem is with the sandbox, it doesn't have permissions to build cJSON.o

**Comment by JalonSolov** [comment]
Doh.  Can you put one in place for it to use, or does it need to rebuild it often/every time?

**Comment by medvednikov** [comment]
Only once. I'm just at sysadmin stuff and linux accounts. Will figure it out.

**Comment by leahlundqvist** [comment]
Closing this as the old playground has been retired.
