### ISSUE TITLE
Make v an array programming language, like fortran/R/lua-torch handles array

### ISSUE THREAD

**Issue by mrharmonies** [vlang/v#4913]
array programming refers to solutions which allow the application of operations to an entire set of values at once. Such solutions are commonly used in scientific and engineering settings. eg:
```
> a:=[1,2,3]
> println(a*2)
    [2,4,6]
```

**Comment by nedpals** [comment]
@mrharmonies What's the difference between this and doing `a.map(it * 2)`? Just curious

**Comment by nedpals** [comment]
Function-wise, its against the one-way philosophy and we want to make array manipulation as array value mapping/manipulation as flexible as possible hence with the `array.map` and `array.filter` methods

**Comment by mrharmonies** [comment]
Wow i am not aware of these function exist. V is now one of my favorite language. Cant wait for v to mature. Thanks!

**Comment by medvednikov** [comment]
Glad you like the language @mrharmonies 

map/filter are documented here:

https://github.com/vlang/v/blob/master/doc/docs.md#arrays

**Comment by mrharmonies** [comment]
By the way, is there a way to do matrix multiplication in v without using loops?
