### ISSUE TITLE
REPL: cannot cast character to integer

### ISSUE THREAD

**Issue by Serkonda** [vlang/v#4920]
**V version:** latest master
**OS:** Linux

**What did you do?**
I opened up V REPL and typed the following:
```v
a := 'A'
b := int(a)
```

**What did you expect to see?**
No error
 
**What did you see instead?**
```v
home/lukas/.cache/v/.noprefix.vrepl_temp.tmp.c: In function ‘main’:
/home/lukas/.cache/v/.noprefix.vrepl_temp.tmp.c:9654:1: error: aggregate value used where an integer was expected
 9654 | int b = ((int)(a));
      | ^~~
/home/lukas/.cache/v/.noprefix.vrepl_temp.tmp.c: In function ‘vcalloc’:
/home/lukas/.cache/v/.noprefix.vrepl_temp.tmp.c:4668:1: warning: control reaches end of non-void function [-Wreturn-type]
 4668 | }
      | ^
/home/lukas/.cache/v/.noprefix.vrepl_temp.tmp.c: In function ‘byte_is_white’:
/home/lukas/.cache/v/.noprefix.vrepl_temp.tmp.c:7419:1: warning: control reaches end of non-void function [-Wreturn-type]
 7419 | }
      |
```

**Comment by medvednikov** [comment]
It should be

```
a := `A`
b := int(a)
```

Compiler needs to handle this.

**Comment by Serkonda** [comment]
Should it present an error or use like this?
```v
a := 'A'
b := int(a[0])
```

**Comment by Serkonda** [comment]
@medvednikov if I could get some short guiding (I do not know the V source that good), I would work on this.

**Comment by JalonSolov** [comment]
Automatically handling it doesn't seem correct.  What if it was
```
a := 'some string much longer than a single character'
b := int(a)
```
That's obviously an error.  However, it should be a V error rather than waiting for the C compiler to complain.

As for where to look in the code... I'm far from an expert, but I would start looking in `vlib/v/parser` and `vlib/v/checker`.

**Comment by medvednikov** [comment]
Fixed:

```
error: cannot cast a string, for denoting characters use `A` instead of 'A'
```
