### ISSUE TITLE
Are functions really pure by default?

### ISSUE THREAD

**Issue by zac-garby** [vlang/v#4930]
The docs claim "V functions are pure by default, meaning that their return values are a function of their arguments only, and their evaluation has no side effects." I'm not entirely convinced of this, though.

This is an impure function:

```v
fn do_something() {
    println("this is not pure")
    println("i could write to a file here. in fact, i am")
}
```

This has the side effect of writing to the `stdout` file, meaning it's not pure. I suppose what the docs mean is that they're pure in terms of not mutating their arguments, but "pure" has a specific meaning which could easily confuse people.

**Comment by medvednikov** [comment]
Yes printing to stdout is the only possible side effect.

Any suggestions on what I should name such functions? Or add an asterisk and say "except printing to stdout"?

**Comment by medvednikov** [comment]
On the other hand:

```
t's not, and we don't. Input to, and output from, the program as a whole can be simply regarded as arguments and results from treating the entire program as one large pure function. As long as it prints the same thing to stdout if you feed it the same thing from stdin, it's still a pure function. In fact, before introducing monadic IO, Haskell used a stream-based I/O system that used pure lazy streams for input and output. It dropped it because it was apparently a pain to use, which may give you some idea of why you haven't heard of anything like this. :]
```
https://softwareengineering.stackexchange.com/questions/108531/stdout-and-its-impurity

**Comment by zac-garby** [comment]
Fair point about looking at impure programs as pure functions. But still, if I’m not mistaken, can’t a function also perform file IO to, say “hello.txt”? And then read that back? If so, it would allow for “global variables” and therefore impurity.

But yeah, I reckon an asterisk to make it more clear should be alright. I’d probably refer to these kinds of functions as “non-mutating”, in terms of their arguments. Rust has a similar mechanism, I can’t remember what they call it though.

**Comment by spytheman** [comment]
Pure functions are abstractions, and in practice they do not exist, just like mathematical points do not exist in reality. They are just sometimes useful thought tools.
In practice, any function in any language, if nothing else, takes at least some time when executed, no?

**Comment by zac-garby** [comment]
Sure, a function takes some time to execute. A pure function is one that has the same return value when given the same arguments, and has no side effects. Is taking time to execute really a side effect?

Wikipedia defines a side effect as an operation that has an effect on an external state. Taking time to execute *does* effect an external state (i.e. the time since the beginning of the program), but no (pure) function would be able to access this state (because that would violate the first rule I mentioned earlier about what a pure function is.)

**Comment by medvednikov** [comment]
> But still, if I’m not mistaken, can’t a function also perform file IO to, say “hello.txt”?

No, it can't. Only print to stdout.

I agree with the point from the softwareengineering.stackexchange.com, and I'll add this info to the home page.
