### ISSUE TITLE
BUG Memory leak

### ISSUE THREAD

**Issue by RNU4** [vlang/v#4944]
**V version:** 
V 0.1.27 857276e.9a237c3
**OS:** 
windows
**What did you do?**
```
fn main(){
for true {
	println("WDAWD")
}
}
```

**What did you expect to see?**
stable memory usage
 
**What did you see instead?**
increasing memory usage in the task manager

**Comment by spytheman** [comment]
Try compiling with `v -autofree yourprogram.v`, does it still leak?
On ubuntu at least, I left it running for several minutes, and it seems that it does not.

**Comment by RNU4** [comment]
v -autofree doesn't help, but it makes sense that it works on Linux as the way of printing is different on Linux
```
pub fn print(s string) {
	$if windows {
		output_handle := C.GetStdHandle(C.STD_OUTPUT_HANDLE)
		mut bytes_written := 0
		if is_atty(1) > 0 {
			wide_str := s.to_wide()
			wide_len := C.wcslen(wide_str)
			C.WriteConsole(output_handle, wide_str, wide_len, &bytes_written, 0)
		} else {
			C.WriteFile(output_handle, s.str, s.len, &bytes_written, 0)
		}
	} $else {
		C.printf('%.*s', s.len, s.str)
	}
}
```
The easy way to fix it is to just use
```
pub fn print(s string) {
	C.printf('%.*s', s.len, s.str)
}
```
as it works on windows too, but there is probably a reason for it to be different

**Comment by RNU4** [comment]
It seems that it is possible to create a memory leak in printf too, i have not tested this on Linux so I'm not sure if its windows only.
The `prt` function is a copy of the linux version 

```
fn prt(s string){
	C.printf('%.*s', s.len, s.str)
}

fn main(){
	for true{
	mut a:=""
	for i:=0; i<10; i++{
		a=a+"d".repeat(20)+"\n"
	}
	prt(a)
	}
}
```

**Comment by spytheman** [comment]
> as it works on windows too, but there is probably a reason for it to be different
I think there were problems when printf is used in a cmd, that was initialized to use wide characters (unicode characters would not be printed, or could not be inserted, not sure)

**Comment by spytheman** [comment]
Yes, this:
```v
fn main(){
   for true {
     mut a:=""
     for i:=0; i<10; i++{
        a=a+"d".repeat(20)+"\n"
     }
     println(a)
   }
}
```
... leaks memory, due to the concatenation, println is irelevant. Hmm...

**Comment by RNU4** [comment]
yeah

```
fn main(){
	for true{
	mut a:=""
	for i:=0; i<10; i++{
		a=a+"d".repeat(20)+"\n"
	}
	}
}
```
leaks memory on windows too

**Comment by alexesprit** [comment]
On Windows, `string.to_wide` and `from_wide` don't free allocated memory.

> The easy way to fix it is to just use

It's not a proper fix, as it breaks Unicode support. That's why we use `MultiByteToWideChar` and `WideCharToMultiByte` functions, but not plain `printf`.

**Comment by alexesprit** [comment]
@RNU4  in your last example memory won't free automatically because V inserts code blocks that actually free memory in the end of function. But the `main` function never reaches the end.

**Comment by spytheman** [comment]
I think the windows leak can be fixed by just calling free manually for the wide strings after they are no longer needed. The concatenation leak would be trickier.

**Comment by spytheman** [comment]
Println mem leak is fixed in: 88fa9353769671f0f2a908b5c4ac895758cb8507
@RNU4 can you test and verify that the original program from this issue:
```v
fn main(){
for true {
	println("WDAWD")
}
}
```
... does not leak anymore, when compiled with -autofree ?
I've tested by running it for 2 minutes, it stays at ~0.3MB:
![mleak no more](https://url4e.com/gyazo/images/2ab545ad.png)

**Comment by RNU4** [comment]
it works now, its stable at 0.4 mb

**Comment by RNU4** [comment]
should i open it again as there is still the concatenation leak? or would it be better to make a new issue for the concatenation  leak?
