### ISSUE TITLE
cgen error: json parsing floats

### ISSUE THREAD

**Issue by amoyyy** [vlang/v#4948]
```
import json

struct Point {
    x f64
    y f64
}

fn main() {
    data := '{"x": 1, "y": 1}'
    p := json.decode(Point, data) or {
        eprintln('Failed to decode json')
        return
    }
    println(p.x)
    println(p.y)
}
```

cgen error: json: f64 is not `struct`

**Comment by nedpals** [comment]
Closed. Fixed in the latest V version: https://devbits.app/play/pDPN8mbM6dtY

(While the behavior is correct, the issue with printing must be created as a separate one.)
