### ISSUE TITLE
Fibonacci & memoization on playground not working

### ISSUE THREAD

**Issue by johandalabacka** [vlang/v#4955]
**What did you do?**
Tried running Fibonacci & memoization on playground (https://vlang.io/play)

**What did you expect to see?**
```
0
1
1
2
3
5
8
13
... and so on
```
 
**What did you see instead?**
```
error: field `nums` of struct `&Fib` is immutable 
   14 |                 return fib.nums[n]
```

Can be fixed by changing definition of struct to contain mutable field

```
struct Fib {
        mut:
		nums []int
}
```

**Comment by serkonda7** [comment]
The old playground was replaced with one that actually works.
The fibonacci example is here: https://v-wasm.now.sh/?url:examples/fibonacci.v
