### ISSUE TITLE
swapping two variables fails

### ISSUE THREAD

**Issue by mvlootman** [vlang/v#4961]
**V version:0.1.27 0d3f133** 
**OS:Macos** 

**What did you do?**
```
fn main() {
	left_hand := 'apple'
	right_hand  := 'empty'
	println('left-hand:$left_hand  and right-hand:$right_hand ')

	println('swap')
	left_hand , right_hand  = right_hand , left_hand 

	println('left-hand:$left_hand  and right-hand:$right_hand ')
}
```

**What did you expect to see?**
the values of the two variables to be swapped.
left-hand:apple  and right-hand:empty 
swap
left-hand:empty  and right-hand:apple 
 
Did used to work before.

**What did you see instead?**
left-hand:apple  and right-hand:empty 
swap
**left-hand:empty  and right-hand:empty**

**Comment by JalonSolov** [comment]
Declare them as mutable.  Can't swap if they're immutable.
```
	mut left_hand := 'apple'
	mut right_hand  := 'empty'
```
Making that change works as expected...
```
jalon@Ripper:~/git/v$ v run foo.v
left-hand:apple  and right-hand:empty
swap
left-hand:empty  and right-hand:empty
jalon@Ripper:~/git/v$
```

**Comment by JalonSolov** [comment]
Yes, overwrite problem.  You can get around it with something like this:
```
fn main() {
        mut left_hand := 'apple'
        mut right_hand  := 'empty'
        println('left-hand:$left_hand and right-hand:$right_hand')

        println('swap')
        left_hand, right_hand = swap(left_hand, right_hand)

        println('left-hand:$left_hand and right-hand:$right_hand')
}

fn swap(a, b string) (string, string) {
        return b, a
}
```
which then gives
```
left-hand:apple and right-hand:empty
swap
left-hand:empty and right-hand:apple
```

**Comment by mvlootman** [comment]
Yes they should have been declared mutable.
But even declaring them mutable still doesn't work. It is something that has worked with the old backend. Of course the workarounds are easy but I think this still is a bug.

**Comment by JalonSolov** [comment]
I agree.  It should either work, or it should give an error message saying it can't.  It shouldn't silently seem to work, but get it wrong.
