### ISSUE TITLE
Still, request add v_snprintf in align with v_printf/v_sprintf

### ISSUE THREAD

**Issue by lygstate** [vlang/v#4966]
The advantage of v_snprintf is that we have no memory allocation inside the function.
That very usefull in bare-metal environment. Or MCU

**Comment by penguindark** [comment]
This is not fully true, you need always extra memory to manage the formats internally, all on the stack, but they are used.
If you want write in a byte buffer, this doesn't require a big change in the code code.
But I don't see the use of it in V when you use the V's strings, can you give me more details?

**Comment by lygstate** [comment]
I am considerating targeting v to MCU such as STM32 and alike things. They have short memory such as 20KB, so memory are precious things. And have no  dynamic memory allocation at all.

**Comment by penguindark** [comment]
Please, have a look to the source code of the v_sprintf, it use less memory it is possible and full stack allocated.
In the first release I made, there was a thing similar to snprintf, but it wasn't so useful with the V strings.
I wrote it having in my mind the embedded systems where, as you write, memory is precious.

**Comment by lygstate** [comment]
Do you means strings.new_builder are alloca on stack?

**Comment by lygstate** [comment]
https://github.com/vlang/v/blob/b8c028c7270b790d52239df6a36473e427208edc/vlib/strconv/format.v#L220

**Comment by lygstate** [comment]
```
int
rpl_vasprintf(char **ret, const char *format, va_list ap)
{
	size_t size;
	int len;
	va_list aq;

	VA_COPY(aq, ap);
	len = vsnprintf(NULL, 0, format, aq);
	VA_END_COPY(aq);
	if (len < 0 || (*ret = malloc(size = len + 1)) == NULL)
		return -1;
	return vsnprintf(*ret, size, format, ap);
}
```
look at this, vsnprintf(NULL, 0, format, aq) can pre-calculate the length of the output buffer
then malloc the size and print into it.

**Comment by penguindark** [comment]
`strings.new_builder` is used because the "string" is returned and the builder is the method chosen to do it.
otherwise as I wrote in a previous comment, pass a buffer is not complicated.
`v_sprintf` is a compromise speed/memory, run two time only to calculate the size, is not in the design of it.
If some else ask for it we can think to do it. :)
Aside this, let me remember that v_sprintf is here only for compatibility, in V you can use string interpolation that is a way more efficent than the printf.

**Comment by lygstate** [comment]
Here is another vsnprintf impl, https://github.com/weiss/c99-snprintf/blob/master/snprintf.c

**Comment by penguindark** [comment]
I know well that version, I studied it.
It has a lot of flaw in the float conversion and a lot of roundign errors, it use tricks to do it, not the result we are trying to achieve :)
not my cup of tea.
Can you help us to achieve what you are asking for? An help is always welcome :)
