### ISSUE TITLE
compilation fatal: can't access const struct fileds 

### ISSUE THREAD

**Issue by amoyyy** [vlang/v#4969]
**V version:** 
V 0.1.27 e137fbb
**OS:** 
Ubuntu

**What did you do?**
here is the example code:
```
struct Color {
        r int
        g int
        b int
}
 
fn (c Color) str() string { return '{$c.r, $c.g, $c.b}' }
 
fn rgb(r, g, b int) Color { return Color{r: r, g: g, b: b} }
 
const (
        Red  = Color{r: 255, g: 0, b: 0}
        Blue = rgb(0, 0, 255)
)
 
fn main() {
        println(Red.r)
        println(Blue.b)
} 
```

**What did you expect to see?**
expected output:   255
                              255

**What did you see instead?**
error: not an enum (name=Red) (type_idx=0)
          not an enum (name=Red) (type_idx=0)

Correct results can be obtained when I checked the **typeof(Red)**.
But when I tried to access the struct fields, it lead to compilation error. 
So I wonder if there is a mismatch between the **type** judge and **const** definition.

**Comment by yuyi98** [comment]
const field name cannot capitalise.
```v
const (
        red  = Color{r: 255, g: 0, b: 0}
        blue = rgb(0, 0, 255)
)
```
And it will work.

**Comment by amoyyy** [comment]
I got it, thanks a lot.
