### ISSUE TITLE
Plan 9 support?

### ISSUE THREAD

**Issue by asvvvad** [vlang/v#4979]
I don't use Plan 9 just wondering if there is support for it

**Comment by Serkonda** [comment]
What exactly is Plan 9?

**Comment by asvvvad** [comment]
"Plan 9 from Bell Labs is a free software distributed operating system. It was made for research purposes as the successor to UNIX by the Computing Sciences Research Center at Bell Labs during the late 1980s. Plan 9 is currently used as a hobbyist's operating system, and in certain experimental fields, where the highly distributed nature of the operating system is valued. Plan 9 has novel features such as the 9P protocol for accessing local and remote resources as files, union mounts, an improved proc file system, and native unicode support throughout the system. In Plan 9, all system interfaces, including those required for networking and the user interface, are represented through the file system rather than specialized interfaces."

Go has support for it and that's why Go is popular among the Plan 9 community
https://github.com/golang/go/wiki/Plan9

**Comment by leahlundqvist** [comment]
V compiles to C so as long as there’s a C compiler for Plan 9 it should be possible

**Comment by medvednikov** [comment]
Yes, adding support for it is trivial, just like for Haiku.
