### ISSUE TITLE
mingw GCC fails to recognize -municode

### ISSUE THREAD

**Issue by kpeters58** [vlang/v#4985]
Just downloaded the 0.1.27 ZIP for Win and tried to run 'v up' ....

```
D:\v>v up
cannot compile `D:\v\cmd\tools\vup.v`:
==================
gcc: error: unrecognized command line option '-municode'
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

D:\v>ls -al
'ls' is not recognized as an internal or external command,
operable program or batch file.

D:\v>dir
 Volume in drive D is Evo500
 Volume Serial Number is 9E1A-B498

 Directory of D:\v

21.05.2020  08:07 PM    <DIR>          .
21.05.2020  08:07 PM    <DIR>          ..
11.05.2020  07:35 PM            16,616 CHANGELOG.md
21.05.2020  08:06 PM    <DIR>          cmd
21.05.2020  08:06 PM    <DIR>          doc
21.05.2020  08:06 PM    <DIR>          examples
17.02.2020  02:32 PM             1,083 LICENSE
11.05.2020  07:35 PM             5,136 README.md
21.05.2020  08:06 PM    <DIR>          thirdparty
21.05.2020  08:06 PM    <DIR>          tutorials
22.05.2020  12:06 AM           942,224 v
22.05.2020  12:15 AM           713,216 v.exe
21.05.2020  11:14 PM               105 v.mod
21.05.2020  08:07 PM    <DIR>          vlib
               6 File(s)      1,678,380 bytes
               8 Dir(s)  482,636,771,328 bytes free

D:\v>
```

**Comment by medvednikov** [comment]
Did you follow the instructions and install mingw from the link?

**Comment by medvednikov** [comment]
Oh, right you used a prebuilt binary. There's no instruction there unless you open README.md

**Comment by kpeters58** [comment]
Just uninstalled & then re-installed it as per your README - things got worse:

D:\v>gcc --version
gcc (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


D:\v>v up
Updating V...
V panic: exec failed (CreateProcess): The system cannot find the file specified.
 cmd: git pull --rebase origin master
print_backtrace_skipping_top_frames_mingw is not implemented

D:\v>

**Comment by emily33901** [comment]
im assuming GCC is in your path variable?
you could also try a new cmd window since they dont update environment variables on the fly

**Comment by kpeters58** [comment]
When you look at my latest  code snippet, you'll see that the first thing I do there, is demonstrate that Gcc is in my path by invoking it without absolute path as  'gcc --version' .....

**Comment by JalonSolov** [comment]
You have the 32-bit compiler.  If your OS is 64-bit, you need to get the 64-bit compiler, or make sure it's in the path before the 32-bit one if you already have it.

The 64-bit version looks like this:

`gcc.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0`

**Comment by vitalyster** [comment]
It should work with 32-bit compiler too, it looks like multiple gcc copies including old ones are in path...

**Comment by JalonSolov** [comment]
Perhaps it should, but it didn't for me.  Only worked for me when I made sure I had 64-bit compiler on my 64-bit Windows.

**Comment by slier81** [comment]
hii..

whats the status on this? i also having this same issue

Output of `gcc --version`

```
gcc.exe (MinGW.org GCC Build-20200227-1) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by leahlundqvist** [comment]
Closing. If you're still facing this issue, update your gcc to v10 or above
