### ISSUE TITLE
Not work in Android 9 aarch6(using termux)

### ISSUE THREAD

**Issue by ouening** [vlang/v#499]
I tried using v in Android with termux but failed.
After chmod a+x v and run ./v it said 'exec format error', parameters of my hardware lists below:
`$ neofetch
OS: Android 9 aarch6
Host: Xiaomi MI 8
Kernel: 4.9.112-perf
Packages: 196 (dpkg)
Shell: zsh 5.7.1
CPU: Qualcomm SDM845
Memory: 4709MiB / 5600MiB
`

**Comment by Undumendil** [comment]
Executing a x86-64 binary on other architecture device is usually impossible unless qemu is used. You should compile V on that device instead. You may need to remove execinfo.h imports and backtrace_* calls both in .v and .c code.

**Comment by ouening** [comment]
Yeah, I'll leave this issue open until I solve it.

**Comment by medvednikov** [comment]
No, v.c should be buildable on Android.

**Comment by ouening** [comment]
I don't know how to fix the error bellow:
`compiler clang -w -o vc v.c
v.c:65:10: fatal error: 'execinfo.h' file not found
#include <execinfo.h>
         ^~~~~~~~~~~~
1 error generated.`

**Comment by medvednikov** [comment]
You have to `git pull`

**Comment by ouening** [comment]
Thank you! Successfully compiled in android using termux.

**Comment by medvednikov** [comment]
Thanks for letting me know! Enjoy V on Android :)
