### ISSUE TITLE
How to use module installed from vpm?

### ISSUE THREAD

**Issue by UedaTakeyuki** [vlang/v#4991]
**V version:** 
V 0.1.27 ac396ea

**OS:** 
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux

**What did you do?**
1. Install **Iaiao.jsonmap** as follow:

```bash:
pi@raspberrypi:~ $ v install Iaiao.jsonmap
Creating /home/pi/.vmodules/ ...
Installing module "Iaiao.jsonmap" from https://github.com/Iaiao/jsonmap to /home/pi/.vmodules/Iaiao/jsonmap ...
```

Also, confirmed that the installation is succeeded as follow:

```
pi@raspberrypi:~ $ ls .vmodules/Iaiao/jsonmap/
jsonmap.v  LICENSE  README.md  test.json
```

2. make *j.v* file as same as [sample code](https://github.com/Iaiao/jsonmap#code) of jsonmap:

```v:j.v
import iaiao.jsonmap
import os

fn main() {
	file := os.read_file("test.json")?
	mut parser := jsonmap.default_parser()
	m := parser.parse(file)
	println(m)
}
```

3. compile j.v as follow:

```
v j.v
```

**What did you expect to see?**

The compilation will be succeeded.
 
**What did you see instead?**
The compile error as follows:

```bash:
pi@raspberrypi:~ $ v j.v
builder error: cannot import module "iaiao.jsonmap" (not found)
```

**Comment by JalonSolov** [comment]
You installed "Iaiao.jsonmap" but tried to import "iaiao.jsonmap".  Change the `i` to `I` and it makes the import work.

However, that module has a LOT of problems... it was written before the major changes in V over the last few months, so it shows a lot of failures and warnings.

**Comment by UedaTakeyuki** [comment]
Thanks, JalonSolov.

I've fixed it and tried again, then I've seen LOT of error as you noticed...
I will wait for version 0.2. Thank you!
