### ISSUE TITLE
"error: unknown function: rune" 

### ISSUE THREAD

**Issue by hachi8833** [vlang/v#4996]
**V version:** V 0.1.27 801bca1
**OS:** macOS Catalina

**What did you do?**

Launch `v` REPL and execute `grinning_face := rune(0xf09f9880)`

**What did you expect to see?**

This should work as fixed in https://github.com/vlang/v/pull/865.
 
**What did you see instead?**

```
>>> grinning_face := rune(0xf09f9880)
error: unknown function: rune
    1 |
    2 | grinning_face := rune(0xf09f9880)
      |                  ~~~~~~~~~~~~~~~~
>>>
```

**Comment by JalonSolov** [comment]
examples/rune.v fails with the same error.

**Comment by danieldaeschle** [comment]
works now
