### ISSUE TITLE
Variadic function does not receive correct values

### ISSUE THREAD

**Issue by mvlootman** [vlang/v#4999]
**V version: V 0.1.27 0d3f133.4608898** 
**OS: macOS ** 

**What did you do?**
```v
fn main() {
	min_num := min(1, 4, 76, 1, -1, 6)
	println('result:$min_num')
}

fn min(n ...int) int {
	if n.len == 0 {
		return 0
	}
	mut min_num := n[0]
	for v in n {
		println(v)
		if v < min_num {
			min_num = v
			println('v:$v min_num:$min_num')
		}
	}
	return min_num
}
```

**What did you expect to see?**
arguments to be passed to variadic function and return -1
 
**What did you see instead?**
random numbers (uninitialised array?)
output:
```
0
-467884400
v:-467884400 min_num:-467884400
32766
195345706
1
0
result:-467884400
```

**Comment by yuyi98** [comment]
```v
struct varg_int {
	int len;
	int args[0];
};

int min_num = fmin((varg_int){.len=6,.args={1, 4, 76, 1, -1, 6}});
```
I think the initialization of varg_init can not be handled this way, must be malloc memory.

**Comment by mvlootman** [comment]
@spytheman noted in the Discord channel:
https://discordapp.com/channels/592103645835821068/592114487759470596/713972619585519627

"the underlying reason for the variadic problem is that fn main is treated in a special way, you can workaround that for now by calling the variadic function in another function, that in turn is called by main. It (and other main weirdness issues), would be solved, when the main module functions are prefixed again with main__, and main is not so special any more"

Calling the variadic function from outside fn main() works.

**Comment by mvlootman** [comment]
This works as expected in the latest version.
