### ISSUE TITLE
Waiting for few (third-party) modules/frameworks

### ISSUE THREAD

**Issue by iredmail** [vlang/V#50]
- ldap
- mysql
- postgresql
- a web framework like Rails/Django/...

Any plan? Or maybe already have them in development?

**Comment by HedariKun** [comment]
well, i think the question is how we can make one, is like go packages system? or something like rust ?

**Comment by medvednikov** [comment]
Hi @iredmail 

It's of course too early for third party modules since the language is not released yet.

The things I worked on: postgres driver (very basic right now), hardware accelerated graphics library (2D, 3D, text rendering), sqlite, glfw.

**Comment by medvednikov** [comment]
There will be a centralized package manager. Similar to ruby gems.

**Comment by kibumh** [comment]
A quote from  https://blog.golang.org/modules2019:
> One of the most important parts of the original design for go get was that it was decentralized: we believed then—and we still believe today—that anyone should be able to publish their code on any server, in contrast to central registries such as Perl’s CPAN, Java’s Maven, or Node’s NPM. Placing domain names at the start of the go get import space reused an existing decentralized system and avoided needing to solve anew the problems of deciding who can use which names. 

V has taken lots of good ideas from several languages including Go. I hope V takes a Go's approach about package management.
