### ISSUE TITLE
High Order Functions doesn't work in REPL

### ISSUE THREAD

**Issue by Delta456** [vlang/v#5006]
**V version:** 
0.1.27 https://github.com/vlang/v/commit/b4eadb903013a4a59a41c5554c2eaa2fdab88cc2

**OS:** 
Windows 10 WSL

**What did you do?**

```
>>> bar := fn() { println("ee") }
>>> bar()

```

**What did you expect to see?**

`ee`
 
**What did you see instead?**

```
error: unknown function: bar 
    1 |
    2 | bar()
      | ~~~~~
``

**Comment by dhonx** [comment]
@Delta456 Please specify the V version

**Comment by Delta456** [comment]
@dhonx done

**Comment by nedpals** [comment]
@Delta456 does it work on a regular v file without `main`?

**Comment by Delta456** [comment]
@nedpals Yes, it works
