### ISSUE TITLE
Lots of timing issues on Windows and Linux running `v test-fixed`

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#5008]
**V version:** V 0.1.27 1754ba1
**OS:** Windows 10 Pro, Ubuntu 20.04, on same hardware

**What did you do?**

`v test-fixed` on both machines.

**What did you expect to see?**

Similar number of tests, and similar execution times.
 
**What did you see instead?**

Windows - notice the last test run was #176, yet the total says 175:
```
OK   [175/176] 56436.492 ms vlib\v\tests\pointers_test.v
OK   [176/176] 56439.127 ms vlib\v\tests\repl\repl_test.v
------------------------------------------------------------------------------------------------------------------------------------
               102136.288 ms <=== total time spent testing all fixed tests
                 ok, fail, skip, total =   174,     0,     1,   175
```

Linux:
```
OK   [177/178] 13368.784 ms vlib/v/tests/inout/compiler_test.v
OK   [178/178] 19789.664 ms vlib/v/checker/checker_test.v
------------------------------------------------------------------------------------------------------------------------------------
               19791.143 ms <=== total time spent testing all fixed tests
                 ok, fail, skip, total =   176,     0,     2,   178
```

I see several problems with the above.   First, the total time spent should be very close between the 2 platforms, not 5X slower in Windows.

Next, if the time for the last 2 tests run by Linux is 33158.448, how can the total time spent be only 19791.143?  Especially since the previous 176 tests took a bit of time each, as well.

**Comment by spytheman** [comment]
Can you try
`VJOBS=1 ./v test-fixed` on linux ?

**Comment by JalonSolov** [comment]
That definitely makes a difference... far more than it should, really.

Without the VJOBS=1, most of the tests said they were taking ~ 1400 ms.  Now most of them say they take ~ 800 - 1100 ms.  Some though, take _much_ longer than before.

The overall time is a heckuva lot slower, as well:
```
...
OK   [178/181]   867.977 ms vlib/os/os_test.v
OK   [179/181]   810.955 ms vlib/os/cmdline/cmdline_test.v
OK   [180/181]   805.415 ms vlib/os/environment_test.v
OK   [181/181]   968.370 ms vlib/regex/regex_test.v
------------------------------------------------------------------------------------------------------------------------------------
               218017.395 ms <=== total time spent testing all fixed tests
                 ok, fail, skip, total =   180,     0,     1,   181
```

**Comment by JalonSolov** [comment]
After more experimentation... yes, that's exactly what's going on.  My machine is fast enough that the overall time spent is only ~1.5ms longer than the longest running test.
