### ISSUE TITLE
Descending range does not work

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#5014]
**V version:** V 0.1.27 4189190
**OS:** Ubuntu 20.04

**What did you do?**
```
for i in 9..-1 {
	println(i)
}
```
**What did you expect to see?**

9
8
7
6
5
4
3
2
1
0

**What did you see instead?**

Nothing.  Just came back to a prompt.  It should either work, or give an error message.

**Comment by x0r19x91** [comment]
ranges should be upward, not downward

**Comment by medvednikov** [comment]
`..` range works just like in Rust, it goes from a to b, increasing.

Making `10..0` work might look reasonable, but what do we do when we have variables? `a..b`, now the logic depends on the value of the variables, this can cause bugs and is not readable.
