### ISSUE TITLE
c error: conflicting types for 'link'

### ISSUE THREAD

**Issue by Serkonda** [vlang/v#5023]
**V version:** V 0.1.27 bc3e29e
**OS:** Manjaro Linux

**What did you do?**
```v
fn link() {
}
```

**What did you expect to see?**
Compile without errors
 
**What did you see instead?**
```
/home/lukas/.cache/v/path_util.tmp.c:1459:13: error: conflicting types for ‘link’
 1459 | static void link(string origin);
      |             ^~~~
In file included from /home/lukas/.cache/v/path_util.tmp.c:210:
/usr/include/unistd.h:789:12: note: previous declaration of ‘link’ was here
  789 | extern int link (const char *__from, const char *__to)
      |            ^~~~
```

**Comment by JalonSolov** [comment]
Simplest fix is to add link to the `c_reserved` array in `cgen.v` but that may not be the best "fix" for this.  There are a lot of other routines in the c standard libraries/headers which can run into the same issues.

A better fix may be to simply prefix all v names (functions, structs, variables, etc., etc.) with `v_` so we don't have to keep adding things to `c_reserved`, but that could wind up breaking things as well.

**Comment by Serkonda** [comment]
I tried prefixing anything with `_v` but this gives a lot of errors too that would need to be inspected.
IMO it's easier to just expand `c_reserved`
