### ISSUE TITLE
warning: const names cannot contain uppercase letters, use snake_case instead

### ISSUE THREAD

**Issue by Soulsbane** [vlang/v#5033]
I understand wanting to be consistent, which is fine. I use uppercase with snake case. Example: FILE_NAME. Unless I'm wrong the error is saying that vriables lile fileName are not currently allowed. So my question is will FILE_NAME continue to be disallowed or was it just an oversight? 

Thanks!

**Comment by JalonSolov** [comment]
No firm decision has been made.  The code currently expects const names in lower_snake_case, but there has been discussion about changing that back to UPPER_SNAKE_CASE.

**Comment by Soulsbane** [comment]
Thanks for the reply! I will of course put my vote for UPPER_SNAKE_CASE :) Thanks again!

**Comment by medvednikov** [comment]
Variables cannot have capital letters that will stay.


Consts are still being figured out.

**Comment by Soulsbane** [comment]
I'll roll with whatever becomes the norm. I'm really loving the language and this was a relatively minor complaint. Thanks for all the work you put in this. I'll go ahead an close this! Thanks again!
