### ISSUE TITLE
'v help' not working

### ISSUE THREAD

**Issue by kpeters58** [vlang/v#5034]
D:\v>v help
V Error: Unknown help topic provided. Use `v help` for usage information.

D:\v>

Now that's almost funny ....

**Comment by dhonx** [comment]
Can you tell your operating system and the V version you are running with?

**Comment by medvednikov** [comment]
Works for me on macos and linux

**Comment by kpeters58** [comment]
The current Windows binary download on Win 10

**Comment by iperov** [comment]
same on windows 7

**Comment by yuyi98** [comment]
This is a problem with the installation package，unpackaged help files in help directory.

**Comment by Ivo-Balbaert** [comment]
Works for me on Windows 10 after v up with V 0.1.27 2eac2a5

**Comment by yuyi98** [comment]
@medvednikov   This is not a program problem, it's a problem with the installation package. I downloaded `v_windows.zip` `v_linux.zip` and `v_macos.zip`, and I found all the `cmd/v/help/` is empty, just `help.v`, missing help files `default.txt` `test.txt` ...

**Comment by medvednikov** [comment]
Will fix today, thanks.

**Comment by iwzoo** [comment]
v help not working on MacOS 
V 0.1.28 e666209

**Comment by olliephillips** [comment]
> v help not working on MacOS
> V 0.1.28 [e666209](https://github.com/vlang/v/commit/e666209fe2556a1b4092e4d4cf0237239804c1cf)

Came here for the same. Seems there are no files in the `cmd/v/help` folder other than `help.v`. We can probably fix by looking to an earlier commit and including them in our local src tree? That's what I'm going to try.

**Comment by olliephillips** [comment]
> We can probably fix by looking to an earlier commit and including them in our local src tree? That's what I'm going to try.

This works. They're just `.txt` files

**Comment by Larpon** [comment]
Is this still relevant? 🙂

**Comment by kpeters58** [comment]
D:\v>v version

V 0.1.28 bbaf6e3

D:\v>v help

V Error: Unknown help topic provided. Use `v help` for usage information.

D:\v>

I would say so, looking at today's test of the issue!

Kind regards,
KP

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Larpon** [comment]
@kpeters58 thanks for testing!
Can you please update V to the latest by either running `v up` (which might not work) or get a more recent version from [releases](https://github.com/vlang/v/releases/tag/latest-commit).

When that is installed you could try the [symlink](https://github.com/vlang/v#symlinking) section for Windows - hopefully it should work after that. 🤞

**Comment by medvednikov** [comment]
This is fixed in the latest V (built from git).

Releases will be updated soon.
