### ISSUE TITLE
Unable to build tetris example on Windows

### ISSUE THREAD

**Issue by iperov** [vlang/v#5036]
**V version: 0.1.27** 
**OS: Windows 7** 

**What did you do?**

1) Downloaded windows build.
2) v examples\tetris\tetris.v

**What did you expect to see?**

expected to build the example
 
**What did you see instead?**

errors:

```
cl : Command line warning D9002 : ignoring unknown option '-mwindows'
tetris.tmp.c

LINK : fatal error LNK1104: cannot open file 'glfw3.lib'
```

so where is zero dependency?

**Comment by taaehk** [comment]
> **V version: 0.1.27**
> **OS: Windows 7**
> 
> **What did you do?**
> 
> 1. Downloaded windows build.
> 2. v examples\tetris\tetris.v
> 
> **What did you expect to see?**
> 
> expected to build the example
> 
> **What did you see instead?**
> 
> errors:
> 
> ```
> cl : Command line warning D9002 : ignoring unknown option '-mwindows'
> tetris.tmp.c
> 
> LINK : fatal error LNK1104: cannot open file 'glfw3.lib'
> ```
> 
> so where is zero dependency?

NO READER FOR VLANG YET I THINK
should create the .dll and .rd?

**Comment by iperov** [comment]
Thanks, but I don't want to create anything or manage the dependencies.

Screenshot from the site:

![firefox_2020-05-26_11-54-47](https://user-images.githubusercontent.com/8076202/82874884-b5cfa480-9f47-11ea-9f68-e9e5c1c30f6a.jpg)

**Comment by taaehk** [comment]
> Thanks, but I don't want to create anything or manage the dependencies.
> 
> Screenshot from the site:
> 
> ![firefox_2020-05-26_11-54-47](https://user-images.githubusercontent.com/8076202/82874884-b5cfa480-9f47-11ea-9f68-e9e5c1c30f6a.jpg)

https://github.com/vlang/v/issues/5037

**Comment by taaehk** [comment]
> Thanks, but I don't want to create anything or manage the dependencies.
> 
> Screenshot from the site:
> 
> ![firefox_2020-05-26_11-54-47](https://user-images.githubusercontent.com/8076202/82874884-b5cfa480-9f47-11ea-9f68-e9e5c1c30f6a.jpg)

https://github.com/taaehk/IRIS/blob/master/IRIS.zip

try, download, unzip, start exe...and you understand....

**Comment by iperov** [comment]
@taaehk what is this shit? visual basic? WTF ?

**Comment by iperov** [comment]
@medvednikov seems like @taaehk is a bot. Can you ban him?

**Comment by taaehk** [comment]
> @taaehk what is this shit? visual basic? WTF ?

try... one of the important things you need for create new languages
https://alumniuitm.uitm.edu.my/read-blog/7   <<example...

**Comment by taaehk** [comment]
> @taaehk what is this shit? visual basic? WTF ?

thumbs up please? lol

**Comment by taaehk** [comment]
> @medvednikov seems like @taaehk is a bot. Can you ban him?

https://www.facebook.com/alexander.absp/videos/149683649996845/
better thumbs up dude...thnks!
