### ISSUE TITLE
Or block generation crashes compiler if left is not an ast.Ident

### ISSUE THREAD

**Issue by emily33901** [vlang/v#5039]
**V version:** V 0.1.27 bd4f9d8
**OS:** Windows/Playground

**What did you do?**
```v
struct Test {
mut:
	a []string
}

fn test() ?[]string {
	return ['a', 'b']
}

fn main() {
	mut a := Test{}

	a.a = test() or {
		[]string{}
	}
} 
```

**What did you expect to see?**
No error
 
**What did you see instead?**
as cast: cannot cast 190 to 138

**Notes:**

[This as cast is the issue](https://github.com/vlang/v/blob/master/vlib/v/gen/cgen.v#L1561)

**Comment by nedpals** [comment]
Closed. Fixed in the latest version of V: https://devbits.app/play/bkX1DqhHU13Q
