### ISSUE TITLE
Flutter GUI

### ISSUE THREAD

**Issue by ghost** [vlang/v#504]
https://dart.dev/server/c-interop-native-extensions#wrapping-the-c-function

Flutter gives us the same code for gUI on web, desktop, mobile.

**Comment by MostHated** [comment]
Plus it looks great. :+1:

**Comment by Kriyszig** [comment]
Its a great way to go about <https://github.com/vlang/ui>

**Comment by nedpals** [comment]
Closed in favor of #2065
