### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file 'glfw3.lib'

### ISSUE THREAD

**Issue by iperov** [vlang/v#5042]
I recreated the issue, because https://github.com/vlang/v/issues/5036 was flooded by spam bot.

**V version: 0.1.27** 
**OS: Windows 7** 

**What did you do?**

1) Downloaded windows build.
2) v examples\tetris\tetris.v

**What did you expect to see?**

expected to build the example
 
**What did you see instead?**

errors:

```
cl : Command line warning D9002 : ignoring unknown option '-mwindows'
tetris.tmp.c

LINK : fatal error LNK1104: cannot open file 'glfw3.lib'
```

so where is zero dependency or easy dependency manager paradigm?

**Comment by JalonSolov** [comment]
The download package is a bit too far out of date.  Do a `v up` to catch up to the latest.

Then make sure the directories with 'glfw3.dll' and 'freetype.dll' are in your path, or copy both of them to the tetris directory, if you want it to run after you build it.

**Comment by iperov** [comment]
```
C:\Users\Administrator\Desktop\v>v up
Updating V...
fatal: not a git repository (or any of the parent directories): .git
```
Nothing working :D

and as user I don't know what is 'glfw3.dll' and 'freetype.dll'
You declare easy dependency manager paradigm. 
So where is it?

**Comment by iperov** [comment]
also you(VLang) declared full static linking of libraries. So why I should care of .dlls ?

Seems like the product is very raw. Should I wait new release?

**Comment by JalonSolov** [comment]
At this point, waiting for a new release might be the best idea.

To get this working, you have to do several manual steps that are not written out in the instructions, so it's hard to know what to do.  :-\

The goal is definitely to have full static linking, but as you have observed, there are still some raw edges.

**Comment by spytheman** [comment]
@iperov unfortunately, there is no "make everything ok" button in v either ;-) .

For the time being, you are better of just cloning https://github.com/vlang/v/ in a folder, then running make in it, after that `v up` would work for you.

**Comment by spytheman** [comment]
As for the original topic, the tetris example currently depends on freetype for font rendering. 
You can install it with `v setup-freetype`, which is clearly described in the README file:
![freetype](https://url4e.com/gyazo/images/7fa36952.png)

**Comment by iperov** [comment]
I installed freetype.
How about glfw for windows :)

**Comment by iperov** [comment]
> there is no "make everything ok" button 

haha, but I would like to see that.

**Comment by spytheman** [comment]
glfw is already bundled in the thirdparty folder (it is much smaller than freetype), and should work .
Check if you have thirdparty/glfw/msvc/glfw3.lib if you are using msvc, and thirdparty/glfw/glfw3.dll .

**Comment by iperov** [comment]
```
D:\DevelopUnsync\v>make
Building V
Cloning vc...
Attempting to build v.c with GCC...
INFO: Could not find files for the given pattern(s).
Attempting to build v.c  with MSVC...
Using x86 Build Tools...
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
You do not appear to have a GCC installation on your PATH and also do not have a
n MSVC installation
 - this means that you cannot bootstrap a V installation at this time...
```

**Comment by iperov** [comment]
also my processor is x64
why it is using x86?

```
>echo %PROCESSOR_ARCHITECTURE%
x86
```

**Comment by iperov** [comment]
I removed theese strings from make.bat
```
if "%PROCESSOR_ARCHITECTURE%" == "x86" (
	echo Using x86 Build Tools...
	set VsWhereDir=%ProgramFiles%
	set HostArch=x86
)
```
Build ok.

Build tetris ok.
But still no static linking.
![FreeCommander_2020-05-26_23-11-27](https://user-images.githubusercontent.com/8076202/82940689-3f15c400-9fa6-11ea-85b8-35b95ff5ddfd.jpg)

**Comment by medvednikov** [comment]
As the readme says, dynamically linked glfw is a temporary dependency. It will be removed once migration to Sokol is complete.

Freetype also won't be needed as stb_truetype will be supported.

**Comment by vitalyster** [comment]
@iperov in order to link glfw statically you need to have static version of its `lib`, and you need to rebuild it from source (and all of its dependencies) because they don't provide static version in binary releases.

**Comment by iperov** [comment]
@vitalyster 

> and you need to rebuild it from source

seriously?
Look at the main page.

![firefox_2020-05-27_10-23-59](https://user-images.githubusercontent.com/8076202/82984970-33f18100-a004-11ea-9696-5fa0d14cba0f.jpg)

**Comment by medvednikov** [comment]
Glfw is not a V project.
