### ISSUE TITLE
Runtime crash because arrays dont understand what a pointer is

### ISSUE THREAD

**Issue by emily33901** [vlang/v#5043]
**V version:** V 0.1.27 bd4f9d8
**OS:** MSVC Windows

**What did you do?**
Initialise an struct with default initialised arrays and attempt to push onto it

**What did you expect to see?**
no crash!
 
**What did you see instead?**
crash! It *looks* like none of the arrays are properly initialised even though I know that code works fine (see notes)... ![](https://i.f1ssi0n.com/MaximumWisedFlea.png)

**Notes:**
CGen is generating bad code afaik. The array of `&File` has `element_size` of `0xC8` which is not a pointer size. `array_push` then attempts to copy memory way past the actual size of the pointer (which should crash but its probably valid readable heap memory so the program just goes with it). 

Then theres `array_get`
```c
compiler__File* compiler__Parser_current_file(compiler__Parser* p) {
	return &(*(compiler__File**)array_get(p->files, p->files.len - 1));
}
```

Which returns a pointer but actually returns a pointer to pointer.
```c
	if (string_ne(compiler__Parser_next_full_ident(p), tos_lit("syntax"))) {
		compiler__File* f = compiler__Parser_current_file(p);
		f->syntax = compiler__ProtoSyntax_proto2;
		return ;
	}
```
The code after this function then just uses it like a regular pointer (which wont crash becuase array_push allocated enough space for it) but hasnt been initialised properly becuase its supposed to be a pointer to pointer not a pointer.

**Comment by emily33901** [comment]
This was actually probably my own fault 🤦‍♀️ 
My V code was 
```v
fn (p &Parser) current_file() &File {
	return &p.files[p.files.len-1]
}
```

which shouldnt be accepted but the pointer to pointer was coerced into a regular pointer - causing the crash.

**Comment by medvednikov** [comment]
Yeah V2 type checker temporarily ignores pointers in such expressions, will be fixed.

**Comment by emily33901** [comment]
Still An issue actually @medvednikov because it still thinks that its array holds a real type and not a pointer to a type which is still wrong!
