### ISSUE TITLE
Ambiguous call to a function which name collides with a variable name

### ISSUE THREAD

**Issue by sudo-nice** [vlang/v#5046]
**V version:** V 0.1.27 7585483
**OS:** Debian GNU/Linux 10 (buster)

**What did you do?**

```v
fn main() {
	foo := foo()
	println(foo)
}

fn foo() string {
	return 'foo'
}
```

**What did you expect to see?**
Printing `foo` string.

**What did you see instead?**
```
main.v:2:9: error: ambiguous call to: `foo`, may refer to fn `foo` or variable `foo`
1 | fn main() {
  2 |     foo := foo()
    |            ~~~~~
    3 |     println(foo)
    4 | }
```

**Comment by alexesprit** [comment]
Why is this an issue?

**Comment by sudo-nice** [comment]
Because there is no real ambiguity here. The line `foo := foo()` should be parsed correctly as:
1. Call function `foo()` - *we know it's a function, because of the parentheses.*
2. Assign the value to the variable `foo` - *we know it's a variable and not a function, because of no parentheses.*

**Comment by alexesprit** [comment]
`foo` could also refer to a function itself, so using `foo` as a variable name could shadow it.

This check was added intentionally in 0afaef58189a0e7e6153bb8e424cfb5491f6ad3a.

**Comment by sudo-nice** [comment]
>`foo` could also refer to a function itself

Oh, I didn't know that, sorry.
