### ISSUE TITLE
sometimes REPL exits unexpectedly on windows

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5052]
**V version:** 
latest master with mingw64

**OS:** 
win10 (other OS not confirmed)

**What did you do?**
Sometimes V REPL just exits unexpectedly after successfully running some code. The frequency is relatively low but it did happen several times during me running REPL.
For now I haven't recognized what code pattern always triggers this - None is reproducible.
Have you ever faced this issue?

**Comment by spytheman** [comment]
hm, that is strange ... I have not experienced it, if it happens again, please add a screenshot/paste of the last few lines.

**Comment by SleepyRoy** [comment]
@spytheman I finally found a relatively reproducible "pattern" on my computer.
```V
// In REPL run these lines one by one, REPL exits at last.
a := 1 
a
1+2
```
What's more, you can also try changing above variable name, the numbers, plus to mul, etc. Bug exists as long as keeping the same pattern.

**Comment by SleepyRoy** [comment]
![image](https://user-images.githubusercontent.com/47302112/83142832-9db47c80-a123-11ea-9ba4-78e2428b3239.png)

**Comment by JalonSolov** [comment]
Seems to be working fine now.
```
PS D:\git\v> v
For usage information, quit V REPL using `exit` and use `v help`
V 0.1.27 905f844.bb9d268
Use Ctrl-C or `exit` to exit
>>> a := 1
>>> a
1
>>> 1+2
3
>>> a
1
>>> println('$a')
1
>>>
```

**Comment by SleepyRoy** [comment]
@JalonSolov Thanks I just confirmed this. Close this issue.
