### ISSUE TITLE
redundant expressions don't result in error

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5056]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
According to Alex's reply in #5051, both unevaluated expressions and evaluated but not used expressions should result in error. So for example consider the following cases
```V
fn main() {
    'hello'  // evaluated but not used
}
```
```V
fn main() {
    1111  // evaluated but not used
}
```
```V
fn main() {
    a := 10
    `b`  // evaluated but not used
    println(a)
}
```
```V
fn main() {
    a := 1
    b := 2
    a+b  // unevaluated
    println(a*b)
}
```

**What did you expect to see?**
All give error.
 
**What did you see instead?**
All compiled.

**Comment by spytheman** [comment]
In my opinion, that is not a bug - you are asking v to evaluate expressions (literals in this case), and do nothing with the result, and it does just what you asked it to do.

**Comment by spytheman** [comment]
Try for example:
2 + 2
=> that will also work, i.e. not produce an error.

**Comment by SleepyRoy** [comment]
@spytheman I've updated this issue according to Alex's reply in #5051 : )
