### ISSUE TITLE
Failure to properly parse escape chars

### ISSUE THREAD

**Issue by LorenDB** [vlang/v#5059]
**V version:** 0.1.27
**OS:** Kubuntu 19.10

**What did you do?**
I entered a string with the escape character `\"` into my V program.

**What did you expect to see?**
The program should have accepted this.
 
**What did you see instead?**
I got a C compiler error. Below is the complete output from V:
```
==================
/home/loren/.cache/v/l.tmp.c: In function ‘main’:
/home/loren/.cache/v/l.tmp.c:9739:34: error: expected ‘)’ before ‘string’
 9739 | string s = tos_lit("this is a \\"string");
      |                                  ^~~~~~
      |                                  )
/home/loren/.cache/v/l.tmp.c:9739:40: warning: missing terminating " character
 9739 | string s = tos_lit("this is a \\"string");
      |                                        ^
/home/loren/.cache/v/l.tmp.c:9739:40: error: missing terminating " character
 9739 | string s = tos_lit("this is a \\"string");
      |                                        ^~~
/home/loren/.cache/v/l.tmp.c:9742:1: error: expected ‘,’ or ‘;’ before ‘}’ token
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

Attached is the temporary C file and the code that caused the fail. If you comment the declaration of s in main() and uncomment the other version of s, you will get a working compilation but it segfaults.
[Failed.tar.gz](https://github.com/vlang/v/files/4685601/Failed.tar.gz)

**Comment by nedpals** [comment]
Weird. Using raw string literals as an alternative works. (`r'this is a "string'` instead of `'this is a \"string'`)

**Comment by LorenDB** [comment]
Using the raw string literal also causes a segfault.

**Comment by medvednikov** [comment]
can you provide a minimal working example ?

**Comment by LorenDB** [comment]
[example.tar.gz](https://github.com/vlang/v/files/4688721/example.tar.gz)
The segfault only happens when the `interpreter` module is used from the source code attached in my first post. In this program, the commented out lines about "s" will provide the error.

**Comment by Delta456** [comment]
This works with the latest V with output as `this is a "string`.
