### ISSUE TITLE
flag.finalize() shouldn't return program name

### ISSUE THREAD

**Issue by radare** [vlang/v#5063]
**V version:** V 0.1.27 ebbf42d
**OS:** macOS 10.15

**What did you do?**

```go
module main

import os
import flag

fn main() {
        mut fp := flag.new_flag_parser(os.args)
        fp.string('aaa', `a`, 'foo', 'aaaah')
        optarg := fp.finalize() or {
                eprintln(err)
                return
        }
        eprintln('$optarg')
        assert(optarg.len == 0)
}
```

**What did you expect to see?**

According to the help message in the finalize() function it should be returning the arguments passed to the program but it is returning an array of strings containing all the arguments (except the ones starting with a dash).

Imho it shouldn't be returning the program name in [0]. Actually .finalize() returns the same as `fp.args`
 
**What did you see instead?**

```
$ ./f a b -a c d
['./f', 'a', 'b', 'd']
f.v:14: FAIL: fn main(): assert optarg.len == 0
$ ./f
['./f']
f.v:14: FAIL: fn main(): assert optarg.len == 0
$
```

**Comment by spytheman** [comment]
It is true that fp.finalize() does return the same as `fp.args`, but it also first checks for errors.

**Comment by spytheman** [comment]
flag.new_flag_parser(os.args) may become `flag.new_flag_parser(os.args[1..])` if you do not want the program name in the result of finalize.
Another option, if you want to pass os.args, is to call: `fp.skip_executable()` before the `fp.finalize()` call.

**Comment by radare** [comment]
Thanks!
