### ISSUE TITLE
CONST modified as mutable receiver.

### ISSUE THREAD

**Issue by amoyyy** [vlang/v#5082]
**V version:** 
V 0.1.27 ae8cc2f
**OS:** 
ubuntu 

**What did you do?**
```
const (
    foo_ = [1, 2, 3]
)

fn (mut a []int) add(b int) {
    for i:=0; i<a.len;i++{
    	a[i] += b
    }
}

fn main() {
    foo_.add(100)
    println(foo_)    
}
```

**What did you expect to see?**
error: cannot assign to constant `foo_`
 
**What did you see instead?**
[101, 102, 103]

It seems there still exist ways to bypass the const protection.

**Comment by medvednikov** [comment]
Fixed: `cannot define methods on types from other modules`
