### ISSUE TITLE
pref.path noise

### ISSUE THREAD

**Issue by radare** [vlang/v#5093]
**V version:** V 0.1.27 c7501e2
**OS:** macOS 10.15

**What did you do?**

```
$ v -v
```

**What did you expect to see?**

```
$ v -v
V 0.1.27 c7501e2
```

**What did you see instead?**

```
$ v -v
setting pref.path to ""
V 0.1.27 c7501e2
```

**Comment by spytheman** [comment]
Fixed in d70cd81
