### ISSUE TITLE
Function constructor attribute

### ISSUE THREAD

**Issue by radare** [vlang/v#5094]
**V version:** V 0.1.27 c7501e2
**OS:** macOS 10.15

**What did you do?**

As long as V needs to call _vinit() before main to work. we should allow shared libs to work too.

So i see different solutions to this problem:

* [ ] Add the ability to set __constructor__ attribute (and destructor) to any V function, the problem here is that those attributes don't work on Android, global variables are forbidden there, so global state is meaningless
* [ ] improve the support for state-less global variables like `__global pub const ()`
* [ ] Ensure V is initialized at the begining of all the public functions

**Comment by spytheman** [comment]
v does not call _vinit before main, but *inside* the generated C main, *before* the V main (the soon to be again `main__main` )

**Comment by danieldaeschle** [comment]
Is this still an issue?
