### ISSUE TITLE
put v.c on repository

### ISSUE THREAD

**Issue by musou1500** [vlang/v#510]
I think it's better to put it on GitHub repository.
If it's available on this repository,  contributors can....
* use old versions(when latest version not works)
* create PR
* check change history easily

**Comment by LouCle** [comment]
iirc v.c is going to be deprecated soon, so I really don't see the point

**Comment by musou1500** [comment]
@LouCle Where did you get that information?
> iirc v.c is going to be deprecated soon

even if it's a fact, being able to see commit log is a big advantage for contributors.
additionally, I often faced compiler(v.c) issues during the last few days.
so, I think It will take a while to v.c is stabilized.

**Comment by medvednikov** [comment]
v.c is not going to be deprecated.

I'll create a separate repo for this to avoid polluting history here with hundreds of thousands of lines.

**Comment by musou1500** [comment]
@medvednikov I got it! this issue can be closed.
can I close it?

**Comment by medvednikov** [comment]
well it should be closed once there's that repo. so not yet

**Comment by musou1500** [comment]
ok. thank you.

**Comment by Chiiruno** [comment]
This will be great for packaging on package management systems like NixOS and GuixSD.

**Comment by AurelienFT** [comment]
https://github.com/vlang/v/pull/522/ shound resolve this.

**Comment by whoizit** [comment]
@AurelienFT how to compile it how? should be git submodule in `v/compiler/vc` i guess

**Comment by musou1500** [comment]
@whoizit 
> how to compile it now? 

`vlang/v.c` is not created yet.
but, as far as I saw the PR, it seems that Makefile clone `v.c`.

> should be git submodule in v/compiler/vc i guess

may be. but in the PR, `v.c` is not a submodule. just external repository.

**Comment by whoizit** [comment]
@musou1500 http://github.com/vlang/vc

**Comment by AurelienFT** [comment]
I don't think it should be submodule because it needed to build the basic project. I saw submodule for "extra features"

**Comment by musou1500** [comment]
@whoizit oh....sorry. I missed it.

**Comment by whoizit** [comment]
@AurelienFT I guess label is 0.2.0, not 0.0.2

**Comment by whoizit** [comment]
I mean 0.2

**Comment by AurelienFT** [comment]
@whoizit I just put the project name. I think add label + project name is overkill

**Comment by medvednikov** [comment]
Done: github.com/vlang/vc
