### ISSUE TITLE
Change newline break from 80 characters to none

### ISSUE THREAD

**Issue by sheerun** [vlang/v#5106]
It is difficult to edit text files if line length is hard-cored to 80 characters, like in `CONTRIBUTING.md`... Could you maybe consider relaxing it and letting editors to choose when to break lines? This style is hard to maintain which is evident even by `CONTRIBUTING.md` itself. For example line 15 (https://github.com/vlang/v/blame/master/CONTRIBUTING.md#L15) is longer than other lines.

**Comment by milrope** [comment]
80 chars makes reading and writing on a text editor easy.
and that line needs to be fixed.

**Comment by milrope** [comment]
PR to make it 80 chars / line https://github.com/vlang/v/pull/5108

**Comment by spytheman** [comment]
@sheerun The reason for the 80 chars limit, is that documentation is written once, but read many times, by different people using different tools. It makes sense to format the documentation for easy consumption in various mediums, including the terminal or editors that lack word wrap capabilities.

**Comment by sheerun** [comment]
I often have less than 80 characters as terminal with because I split window in half, this results in something like this: https://imgur.com/a/xOLVT6L But ok

**Comment by sheerun** [comment]
btw. I don't know any editors that lack word wrap capabilities :)
