### ISSUE TITLE
Improve standard library in ruby-fashion

### ISSUE THREAD

**Issue by sheerun** [vlang/v#5107]
I'm polyglot programmer (including Go) and there is no doubt in my mind that Ruby has the best standard library (you're free to disagree :). Would you consider accepting PRs that introduce methods from Ruby? Some examples:

- https://ruby-doc.org/core-2.6/String.html
- https://ruby-doc.org/core-2.7.1/Enumerable.html
- https://ruby-doc.org/core-2.7.0/Array.html
- https://ruby-doc.org/core-2.7.0/Hash.html
- https://ruby-doc.org/stdlib-2.7.1/libdoc/set/rdoc/Set.html

**Comment by sheerun** [comment]
By the way, convention of using `!` suffix for mutable methods, and `?` suffix for methods that return booleans is also worth considering, in my opinion

**Comment by sudo-nice** [comment]
IMO, Ruby follows a different principle of *being able to do the same thing in many ways*, which contradicts to V's *there is only one way to do a thing*.

Also, a bang in Ruby is not meant to designate a mutable method. As Matz [said]:

> The bang (!) does not mean “destructive” nor lack of it mean non destructive either. The bang sign means “the bang version is more dangerous than its non bang counterpart; handle with care”. Since Ruby has a lot of “destructive” methods, if bang signs follow your opinion, every Ruby program would be full of bangs, thus ugly.

[said]: https://www.ruby-forum.com/t/conventions-in-ruby-and-the-principle-of-least-surprise/158706/2

**Comment by sheerun** [comment]
I'm against duplicating functions as well. It just would be nice to write `[1,2,3].max()` in v

**Comment by sudo-nice** [comment]
@sheerun Once we have `.max()`, we would definitely want to have `.max_by()` too, and more, and more. And if we go down that road, where should we stop?
On the other hand, it's really easy to implement those methods manually, on demand. And one can write the methods so they work in the most controllable and efficient way.

**Comment by milrope** [comment]
this things should be implemented in Go fashion.

**Comment by xandro0777** [comment]
Ruby libs definitively have some charm and judging by myself vlang has a great appeal for programmers who like ruby. So having ruby-lib like functionality would be a great advantage but it could also be an extra library.. and even a guide v-for-RUby-devs could do.

**Comment by sheerun** [comment]
By the way if you look for static-typed-friendly version of ruby lib then there's crystal:

https://crystal-lang.org/api/0.34.0/
