### ISSUE TITLE
doc: v fmt style guide

### ISSUE THREAD

**Issue by milrope** [vlang/v#5109]
document formatting style  used by `v fmt`

**Comment by nedpals** [comment]
You mean specification used by vfmt to style a V file?

**Comment by sudo-nice** [comment]
Cons:
1. The doc has to be kept synchronized with changes to the formatter.
2. Going through the doc seems to be harder than simply running the formatter and observing the changes.

Pros:
???

IMO, the formatter is self-documented in the most efficient way and there is no need to maintain a separate doc.

**Comment by medvednikov** [comment]
Agreed.
