### ISSUE TITLE
V 0.1.0 is out: if you were experiencing segfaults on Linux when building it, please try again

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#511]
It should work fine now.

The instructions are the same:

```
git clone https://github.com/vlang/v ~/code/v
cd ~/code/v/compiler
make
```

**Comment by mrhdias** [comment]
Thanks, good job, it works on ArchLinux :-)

**Comment by zhengshuxin** [comment]
It can't work on Centos7.1 with gcc version 4.8.5 yet.

**Comment by medvednikov** [comment]
Thanks for letting me know, @mrhdias !

@zhengshuxin, GCC 4.8.5 is 4 years old. Please consider upgrading it.

In the future I'll make sure V can be compiled with older C compilers, but I can't do that right now, sorry.

**Comment by zhengshuxin** [comment]
Thank you very much and wish V will be more powerful.

**Comment by Hamzantal** [comment]
next goal should be to stop the limitation of the sources to be in ~/code/v!
@medvednikov when do you think this will be fixed :slightly_smiling_face:

**Comment by medvednikov** [comment]
@Hamzantal today, there was a discussion about this here.

**Comment by musou1500** [comment]
@medvednikov @Hamzantal 
actually, I implemented it experimentally.
https://github.com/vlang/v/issues/457#issuecomment-505009320

You can try it. I would like to get your feedback.
https://github.com/musou1500/v/tree/impl-exp-custom-location

**Comment by zhengshuxin** [comment]
> 
> 
> Thanks for letting me know, @mrhdias !
> 
> @zhengshuxin, GCC 4.8.5 is 4 years old. Please consider upgrading it.
> 
> In the future I'll make sure V can be compiled with older C compilers, but I can't do that right now, sorry.

I've compiled V compilter successfuly on Centos7.x with gcc9.1.0 after I upgraded the gcc.

**Comment by medvednikov** [comment]
It should also build on musl distors now.

**Comment by megatux** [comment]
Works here, elementary OS Juno, clang v6.0 :tada:

**Comment by nuqz** [comment]
Just FYI: works fine with GCC 6.3 (released December 21, 2016).

**Comment by bmallred** [comment]
Verified compiled on VoidLinux with musl
