### ISSUE TITLE
 Process consumes 99% (16GB) of memory

### ISSUE THREAD

**Issue by jiuker** [vlang/v#5116]
**V version:** 
V 0.1.27 4189190
**OS:** 
ubuntu 20.04
**What did you do?**
when I try use V to replication to redis
(edit by spytheman: the compilable code is in the comments below)

**What did you expect to see?**
Process consumes very little memory
 
**What did you see instead?**
Process consumes 99% (16GB) of memory

**Comment by jiuker** [comment]
import net
import cmd
import strconv
fn main(){
	source_url:= "127.0.0.1"
	source_port := 6379
	source_conn := net.dial(source_url,source_port)?
	set_port_rsp:= cmd.cmd_to_resp_first_line(source_conn,["replconf", "listening-port", "8083"])?
	println("${set_port_rsp}")
	source_conn.write(cmd.cmd_to_string(["psync","?","-1"]))?
	header := source_conn.read_line().split(" ")
	println('$header')
	rdb_size_str:=source_conn.read_line().replace("$","").replace("\r\n","")
	rdb_size:=strconv.parse_uint(rdb_size_str,10,64)
	println('-$rdb_size_str--$rdb_size-')
	mut read_count:=0
	for read_count<rdb_size{
		_,read_count_c:=source_conn.recv(rdb_size)
		read_count+=read_count_c
	}
	for{
		line:=source_conn.read_line()
		println('$line')
	}
}

**Comment by jiuker** [comment]
module cmd
import net
pub fn cmd_to_string(cmd []string) string{
	mut rsl := '*${cmd.len}\r\n'
	for cmd_ in cmd {
		rsl = '${rsl}$${cmd_.len}\r\n${cmd_}\r\n'
	}
	return rsl
}
pub fn cmd_to_resp_first_line(conn net.Socket,cmd []string) ?string{
    conn.write(cmd_to_string(cmd))?
    return conn.read_line()
}

**Comment by radare** [comment]
Please edit the issue and use proper triple backtick-go to make it readable

**Comment by jiuker** [comment]
thx,It's very kind of you!

**Comment by emily33901** [comment]
You are never calling `free()` on the `recv`'d memory so it will never free the allocation and leak it

**Comment by jiuker** [comment]
> You are never calling `free()` on the `recv`'d memory so it will never free the allocation and leak it

you mean I need call line.free()?

**Comment by emily33901** [comment]
```go
unsafe {
  free(line)
}
```

is probably what you need

**Comment by medvednikov** [comment]
The developer shouldn't call free here, V will do it for them.

**Comment by emily33901** [comment]
that might be whats supposed to happen but it apparently isnt...

**Comment by medvednikov** [comment]
That's why I wrote `will`

**Comment by emily33901** [comment]
ah fair enough

**Comment by medvednikov** [comment]
Fixed when using `-gc boehm`, will also work with `-autofree` and by default in the future.
