### ISSUE TITLE
support musl libc based linux distros

### ISSUE THREAD

**Issue by 0verse** [vlang/v#512]
What works:

`cc -lexecinfo -std=gnu11 -w -o vc v.c`

However, this doesn't work:

`./vc -o v .`

Error message:

> /bin/ld: /tmp/cclJckpJ.o: in function `os__print_backtrace':
> /home/0verse//.vlang//v.c:5243: undefined reference to `backtrace'
> /bin/ld: /home/0verse//.vlang//v.c:5247: undefined reference to `backtrace_symbols_fd'
> collect2: error: ld returned 1 exit status
> V panic: clang error

**Comment by whoizit** [comment]
do you use ~/code/v path? it's hardcoded

**Comment by 0verse** [comment]
I am well aware of that, musl libc doesn't include execinfo.h and this is why there is a linker flag added during compile time.

**Comment by whoizit** [comment]
you should use `~/code/v` path as is in #486

**Comment by 0verse** [comment]
it's not about ~/code/v, which I use, this is about execinfo.h

**Comment by medvednikov** [comment]
@0verse I've removed it for now, try again please.

**Comment by 0verse** [comment]
@medvednikov awesome work!!!  The source compiles and the compiler runs well :)

**Comment by lutherwenxu** [comment]
Glad it works for you now! Closing as indicated as fixed by author.
