### ISSUE TITLE
Invalid syntax is compiled (foo "bar")

### ISSUE THREAD

**Issue by sheerun** [vlang/v#5127]
**V version:** V 0.1.27 2f171bf
**OS:**  MacOS

**What did you do?**

```
fn foo() int {
  return 42
}


fn main() {
  foo "asda"
}
```

**What did you expect to see?**

Some kind of error that I forgot parenthesis, or something
 
**What did you see instead?**

It compiles and runs (does nothing)

**Comment by yuyi98** [comment]
Fixed.

```v
D:\test\v\tt1>v run .
.\tt1.v:7:3: error: expression evaluated but not used 
    5 | 
    6 | fn main() {
    7 |   foo "asda"
      |   ~~~
    8 | }
```
