### ISSUE TITLE
maybe a bug in interface type as function return

### ISSUE THREAD

**Issue by lydiandy** [vlang/v#5135]
**V version:** 
lastest:V 0.1.27 b74e1bb
**OS:** 
macos
**What did you do?**
here is the example code:
```
module main

fn main() {

}

interface Driver {
	exec()
}

struct DriverType {
}

pub fn (d DriverType) exec() {
	
}

fn new() Driver {
	d := DriverType{}
	return d
}

```

**What did you expect to see?**
the struct DriverType implements the interface Driver,
it should be compiled
**What did you see instead?**
error: cannot use `DriverType` as type `Driver` in return argument

**Comment by radare** [comment]
imho this is a TODO, because interfaces should be supported on return too, not just arguments as the documentation explains

The current error is the following:
```go
$ v run a.v
a.v:21:9: error: cannot use `DriverType` as type `Driver` in return argument
   19 | fn new() Driver {
   20 |     d := DriverType{}
   21 |     return d
      |            ^
   22 | }
   23 |
```

Changing the `return d` into `return Driver(d)` results in a compiler error (which shouldnt happen):

```
a.tmp.c:7893:10: error: used type 'Driver' (aka '_Interface') where arithmetic or pointer type is required
        return ((Driver)(d));
                ^       ~~~
```

**Comment by medvednikov** [comment]
Fixed in https://github.com/vlang/v/commit/1ca7a607d3915f7fe8ef276a009b6a24fc48f80d
