### ISSUE TITLE
generate the same C function

### ISSUE THREAD

**Issue by lydiandy** [vlang/v#5138]
**V version:** 
lastest:V 0.1.27 04744a5.905f844
**OS:** 
macos
**What did you do?**
here is the generated C code:
```
// NR interfaced types= 2
int _database__sql__driver__Driver_database__pg__Driver_index = 0;
int _database__sql__driver__Driver_database__pg__Driver_index = 1;

// Methods wrapper for interface "database__sql__driver__Driver"
static inline Option_string database__pg__Driver_ping_method_wrapper(database__pg__Driver* d) {
	return database__pg__Driver_ping(*d);
}

static inline Option_string database__pg__Driver_ping_method_wrapper(database__pg__Driver* d) {
	return database__pg__Driver_ping(*d);
}
```

**What did you expect to see?**
the code can be compiled
 
**What did you see instead?**
here is the error msg:
```
private/var/folders/lk/k709921d2gl4jrh31mt8_ktm0000gn/T/v/demo.tmp.c:1694:5: error: redefinition of '_database__sql__driver__Driver_database__pg__Driver_index'
int _database__sql__driver__Driver_database__pg__Driver_index = 1;
    ^
/private/var/folders/lk/k709921d2gl4jrh31mt8_ktm0000gn/T/v/demo.tmp.c:1693:5: note: previous definition is here
int _database__sql__driver__Driver_database__pg__Driver_index = 0;
    ^
/private/var/folders/lk/k709921d2gl4jrh31mt8_ktm0000gn/T/v/demo.tmp.c:1712:29: error: redefinition of 'database__pg__Driver_ping_method_wrapper'
static inline Option_string database__pg__Driver_ping_method_wrapper(database__pg__Driver* d) {
                            ^
/private/var/folders/lk/k709921d2gl4jrh31mt8_ktm0000gn/T/v/demo.tmp.c:1697:29: note: previous definition is here
static inline Option_string database__pg__Driver_ping_method_wrapper(database__pg__Driver* d) {
```
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

**Comment by lydiandy** [comment]
I follow the v compiler code,and found why it generate the same C function:

here is the Driver interface AST info,the types array have two element:
the type of 65590 is &pg.Driver, and the type of 54 is pg.Driver,
and it will generate the C function  twice for &pg.Driver and pg.Driver.
but it should not, it is a bug of v compiler
```
v.table.Interface {
   //the type of 65590 is &pg.Driver,and the type of 54 is pg.Driver
    types: [v__table__Type(65590), v__table__Type(54)]  
}
```

**Comment by elimisteve** [comment]
@lydiandy Please include the original V code that your generated C code is based on

**Comment by spytheman** [comment]
I think that was fixed, but it is hard to check without the original V source. Closing for now.
