### ISSUE TITLE
The chicken-and-egg problem: Which was first?

### ISSUE THREAD

**Issue by IngwiePhoenix** [vlang/v#5139]
Hey there!

I only now came across V and I am rather intrigued by it - but, also curious. Basically: When compiling V, you provide a pre-generated `v.c` (and `v_win.c`). But how is that one generated?

I saw this "confusion" before too, on the D language: You'd need an older D compiler which was written entirely in C/C++ to then compile a more modern D compiler to then compile the most modern D compiler.

What would the path be if I wanted to compile V from source from the very start instead of using a pre-generated `v.c`?

**Comment by medvednikov** [comment]
Since V compiles to C, and not to machine code, the bootstrapping chain was not maintained to save time. And there were about 100 iterations with breaking changes. So no, it's not possible :)

**Comment by medvednikov** [comment]
For this purpose you can think of v.c as written by a human, it is actually very clean and readable.
