### ISSUE TITLE
Unify verbose flags

### ISSUE THREAD

**Issue by Serkonda** [vlang/v#5148]
Showing more verbose feedback in CLI is handled very different.
For example we have `v build file.v -v` but also `v update -verbose`.

_Actually using `v update -v` works too but has different output._

I would suggest to follow the one-way-philosophy and choose one verbosity style for all cli options.

**Comment by medvednikov** [comment]
Good catch. It should be `-v` everywhere.

**Comment by TheBeachMaster** [comment]
Seems fixed by [#5153](https://github.com/vlang/v/pull/5153)

**Comment by medvednikov** [comment]
No that's just help text.
