### ISSUE TITLE
`strconv.format_dec` is public but `BF_param` not

### ISSUE THREAD

**Issue by shnorbluk** [vlang/v#5152]
**V version:** V 0.1.27 3042581
**OS:** Android 10 (under Termux)

**What did you do?** 
Compile  the code
```go
s:=strconv.format_dec(42, {pad_ch:`0`, len0:5})
println(s)
```

**What did you expect to see?**
Compilation successful
 
**What did you see instead?**
`error: type strconv.BF_param is private`
If I set 
**pub** struct BF_param {
in `vlib/strconv/format.v`, it compiles and works nicely. I think you should set the struct BF_param public.

**Comment by spytheman** [comment]
Fixed in 845084c

**Comment by shnorbluk** [comment]
Thank you.
