### ISSUE TITLE
Support HMAC

### ISSUE THREAD

**Issue by 54m** [vlang/v#5166]
https://github.com/golang/go/tree/master/src/crypto/hmac

**Comment by Delta456** [comment]
Can you please elaborate?

**Comment by JalonSolov** [comment]
Could mean https://en.wikipedia.org/wiki/HMAC

**Comment by 54m** [comment]
@Delta456 
If HMAC is implemented, you can also implement JWT authentication etc.

**Comment by 54m** [comment]
[https://github.com/golang/go/tree/master/src/crypto/hmac](https://github.com/golang/go/tree/master/src/crypto/hmac)
like this

**Comment by Ekopalypse** [comment]
@54m - I assume this can be closed, correct?
https://github.com/vlang/v/tree/master/vlib/crypto/hmac
