### ISSUE TITLE
vdoc: segfaults on some modules

### ISSUE THREAD

**Issue by nedpals** [vlang/v#5172]
**V version: V 0.1.27 b99ba21** 
**OS: Ubuntu 20.04** 

**What did you do?**
Tried to generate docs on modules outside `vlib`:
```
v doc -s ./nedpals/vex/server
```

**What did you expect to see?**
Browser opens.
**What did you see instead?**
Segfaults

**Comment by spytheman** [comment]
For me (ubuntu 16.04, V 0.1.27 1386c5d), that works and opens a browser.
Can you try compiling vdoc with `-keepc -cg ` then trying it again (it should print more info on panics, or when run with gdb ) ?

**Comment by JalonSolov** [comment]
The current `v doc` doesn't seem to work at all for me on Ubuntu 20.04, `V 0.1.27 93c44a2`.

`v doc` used to print out a list of modules.  Now it prints usage.  `v doc builtin` used to print the info for the builtin module.  Now it just segfaults.
```
jalon@Ripper:~/git/v$ v doc
Usage:
  v doc [flags] module_name output_file[.json|.md|.html]
  v doc [flags] path_to_source.v output_file[.json|.md|.html]
  v doc [flags] ./directory output_file[.json|.md|.html]
  v doc [flags] . output_file[.json|.md|.html]

Generates the documentation of a given directory, module, or V source file
and prints or saves them to its desired format. It can generate HTML, JSON,
or Markdown format.

Options:
  -all    Includes private and public functions/methods/structs/consts/enums.
  -loc    Show the locations of the generated signatures. (For plaintext only)
  -m      Generate docs for modules listed in that folder.
  -s      Serve HTML-generated docs via HTTP.
  -r      Include README.md to docs if present.
jalon@Ripper:~/git/v$ v doc builtin

Segmentation fault
jalon@Ripper:~/git/v$
```

**Comment by spytheman** [comment]
Is this issue still happening for you with latest V @nedpals ?

**Comment by nedpals** [comment]
@spytheman , It works now :+1: 
@JalonSolov tried reproducing your issue, but it worked without segfaults :+1:

**Comment by JalonSolov** [comment]
Agreed.  This issue is resolved.
