### ISSUE TITLE
-o should detect when the output file is the same as the source .v file and print an error message

### ISSUE THREAD

**Issue by trufae** [vlang/v#5178]
**V version:** V 0.1.27 4e51867
**OS:** macOS 10.15

**What did you do?**

```
$ v -o a.v a.v
```

**What did you expect to see?**

An error saying that the output cant be any of the files passed as input
 
**What did you see instead?**

my a.v trashed out

**Comment by JalonSolov** [comment]
Trashed, or overwritten by the executable?

**Comment by JalonSolov** [comment]
So it was overwritten with the executable?  At least it behaved correctly with the given input.

I agree that it is probably better to help prevent people from losing their source.

Although I am sure there will be someone who likes it just the way it is.  Darwinian.  ;-)

**Comment by spytheman** [comment]
It should print an error (although the current behaviour is indeed a good stimulus to save your source often, and use version control).

**Comment by trufae** [comment]
Just to clarify i didnt had any accident on this

Also, i want to state that this can be also a good stimulous for the user to pick a different language ;)

**Comment by medvednikov** [comment]
Can you give an example of languages that handle this? Just tried Go, and it overwrote the file.

**Comment by spytheman** [comment]
It is implementation dependent. gcc 9.2 for example errors with:
```
gcc: fatal error: input file ‘x.c’ is the same as output file
compilation terminated.
```
clang and tcc overwrite the source file with the binary without complaining

**Comment by medvednikov** [comment]
Fixed

```
Cannot save output binary in a .v file.
```
