### ISSUE TITLE
More consistent variable declaration

### ISSUE THREAD

**Issue by sheerun** [vlang/v#5198]
Hello,

V is not yet stable, so I'd like to pitch alternative variable declaration syntax. Currently there can be immutable and mutable variables. They are initialized as follows, and assigned as follows:

```
thirteen := 13
mut twelve := 12
twelve = 12
```

Such syntax makes mutable variables to have different "level" than immutable ones and on top of this we also have two "assignment" operators. The reason we need `:=` is specifically to distinguish between assigning to immutable variable and initializing it (we can distinguish between assigning and initializing mutable variable because of `mut` which is used only for initializing)

I think better approach would be to always use keyword for initializing variables and ditch `:=` as so:

```
let thirteen = 13
mut twelve = 12
twelve = 12
```

This is very similar to how Rust or Scala does it. I personally prefer it from Go syntax

Now "thirteen" and "twelve" are on the same level and we don't need to think whether to use `:=`

I won't be offended if you close this, I'd just like to know your opinion :)

**Comment by sudo-nice** [comment]
I'm in favor of the current implementation, because it makes apart two concepts:
- `:=` denotes the fact of initialization (and it's the only way)
- `mut` denotes mutability of the variable

Otherwise it gets semantically mixed up:
- `let` denotes initialization of an immutable variable
- `mut` denotes initialization of a mutable variable

**Comment by Delta456** [comment]
I totally agree with @sudo-nice!

**Comment by sheerun** [comment]
> := denotes the fact of initialization (and it's the only way)
> mut denotes mutability of the variable

Not entirely, there's for example there's already `for` keyword which can initialize mutable variable

```
fn main() {
  for i := 0; i < 10; i++ {
    i = 20
    println("$i")
  }
}
```

I think let/mut reads better in mind:

- with `let foo = 12` you think "initialize immutable -> foo -> 12"
- with `mut foo = 12` you think "initialize mutable -> foo -> 12"
- with `foo := 12` you need to think "foo -> initialize -> 12"
- with `mut foo := 12` you need to think "mutable -> foo -> initialize -> 12"

**Comment by sheerun** [comment]
Oh, and there is also `for x in y` which initializes immutable variable:

```
fn main() {
  for x in [1,2,3] {
    x = 4 // complains that x is immutable
    println(x)
  }
}
```

If you'd really want to follow "there is only way to do something" philosophy then you'd need to:

- ditch `for x; y; z` syntax because it initializes mutable variable without `mut` (which I encourage you to do, because it's easy to create infinite loops and off-by-one errors with this syntax)
- drop `for x in y` syntax because it initializes variable without `:=` in lieu of `for x := range y`, just like Go (which I don't encourage, because `in` looks really nice)

**Comment by sheerun** [comment]
I think I have nothing more to add so I'll close this issue and let authors of V create follow-up issues if they like some ideas here

**Comment by sudo-nice** [comment]
I agree with some of the points you made and must admit the topic is quite delicate.

**Comment by sheerun** [comment]
Yes indeed it's pretty delicate. Also congratulations on syntax in general, I like it very very much

**Comment by medvednikov** [comment]
This has been suggested several times, it's very important to have mutability by default, using let vs mut doesn't achieve that.

**Comment by sheerun** [comment]
@medvednikov In such case maybe I'd suggest:

a) 

changing

```
const (
  foo = "bar"
)
```

syntax to just `foo := "bar"` (const are immutable)

b) deprecating `for x; y; z` (it uses mutability) syntax and encouraging for x in y..z (immutable)
