### ISSUE TITLE
Found a bug while running JSON decoding/encoding in V Lang Playground

### ISSUE THREAD

**Issue by AlenJoseph** [vlang/v#5219]
**V version:** The version running on  lang playground
![image](https://user-images.githubusercontent.com/15855278/83849793-91d14780-a72d-11ea-83cc-02d6b1be4260.png)

**OS:** 
Ubuntu 
**What did you do?**
Just run the example program on the browser

**What did you expect to see?**

 parsed JSON
**What did you see instead?**
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

**Comment by sudo-nice** [comment]
Duplicate? https://github.com/vlang/v/issues/5057
