### ISSUE TITLE
C error. This should never happen.

### ISSUE THREAD

**Issue by patrickpissurno** [vlang/v#5238]
**V version:** V 0.1.27 e5f12ad
**OS:** macOS Sierra 10.12.6

**What did you do?**
Ran `v -cg test .` to execute my [module's](https://github.com/patrickpissurno/vredis) tests.

**What did you expect to see?**
It working, as it used to do a month or so ago.
 
**What did you see instead?**
`C error. This should never happen.`

I've attached the full logs. The file `err.txt` is the output of stderr and `out.txt` is the output of the stdout.

Attached files:
[err.txt](https://github.com/vlang/v/files/4740092/err.txt)
[out.txt](https://github.com/vlang/v/files/4740093/out.txt)

Thanks!

**Comment by danieldaeschle** [comment]
Does it work now? Could you add a **minimal** example of your error? Otherwise I will close it.
