### ISSUE TITLE
cannot append int to Abc

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#5239]
**V version:** latest
**OS:** Ubuntu

**What did you do?**
```v
type Abc = int | string

fn main() {
	mut abc := []Abc{}
	abc << 1
}
```

**What did you expect to see?**
works
 
**What did you see instead?**
```
main.v:5:9: error: cannot append `any_int` to `[]Abc` 
    3 | fn main() {
    4 |     mut abc := []Abc{}
    5 |     abc << 1
      |            ^
    6 | }
```

`abc << Abc(1)` works.

**Comment by yuyi98** [comment]
`abc << int(1)` can work.
`1` parse to `any_int`.

**Comment by danieldaeschle** [comment]
jup, but my example should work either. Discuess wtih Alex.

**Comment by danieldaeschle** [comment]
related to https://github.com/vlang/v/issues/6575
close because it's a duplicate
