### ISSUE TITLE
Bad navigation on constants section

### ISSUE THREAD

**Issue by dhonx** [vlang/v#5248]
**V version:** 0.1.27 0aadde2
**OS:** Linux

**What did you do?**
![v programming language](https://user-images.githubusercontent.com/17797740/83952239-07423280-a86a-11ea-9887-a407e55d0afe.png)
Try to click `constants` section 2.

**What did you expect to see?**
The `constants` section should have unique `id` property to it. So the navigation is not broken. I expect it navigate me to `constants` section 2, not `constants` section 1. 
 
**What did you see instead?**
It navigate me to `constants` section 1.

**Comment by danieldaeschle** [comment]
@dhonx do you have a test site with two Constant sections?
