### ISSUE TITLE
[BUG] Invalid generated code while using a string object without variable

### ISSUE THREAD

**Issue by newenclave** [vlang/v#525]
#### V version:
V 0.0.12
upd: V 0.1.0 is also affected

#### OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

#### C COMPILER:
clang

#### Description:
Invalid output is generated after using object without a variable binding  

#### Example:
```go
V 0.0.12
Use Ctrl-D to exit
For now you have to use println() to print values, this will be fixed soon

>>> println('test'.starts_with('test'))

```

#### Actual Result:
Compiler error:
```
/home/hidden//.vlang0.0.12//vrepl.c: In function ‘main’:
/home/hidden//.vlang0.0.12//vrepl.c:3703:31: error: too many arguments to function ‘println’
  string_stbool_str(arts_with( println ( tos2("test") , tos2("test") ) ) ) ;
                               ^~~~~~~
/home/hidden//.vlang0.0.12//vrepl.c:2220:7: note: declared here
  void println(string s) {
       ^~~~~~~
/home/hidden//.vlang0.0.12//vrepl.c:3703:31: error: invalid use of void expression
  string_stbool_str(arts_with( println ( tos2("test") , tos2("test") ) ) ) ;
                               ^~~~~~~
V panic: clang error
```

#### Expected Result:
output: `true`

#### Additional.
It works as expected if using a variable
```go
>>> a:='test'
>>> println(a.starts_with('test'))
true
```

The method len also does work as expected without variable.
```
>>> println('test'.len)
4
```

**Comment by Henrixounez** [comment]
I inspected the code, it seems that the problem is when `set_placeholder` in cgen.v concatenates strings, the result is tangled bits of code : 
```C
//Expected : 
 println (bool_str( string_starts_with( tos2("test") , tos2("test") ) ) ) ;

//Actual : 
 string_stbool_str(arts_with( println ( tos2("test") , tos2("test") ) ) ) ;
```
The problem is the variable `amp_ph` given by `fn_call_args` having wrong value for this case.
I understand the parser too much so definitively can't give a fix.

**Comment by Bowero** [comment]
Information can be found here: https://github.com/vlang/v/issues/272.
