### ISSUE TITLE
[bug] - os.join_path should accept relative

### ISSUE THREAD

**Issue by Olyno** [vlang/v#5253]
**V version:** V 0.1.27 caa25a3
**OS:** Windows 10

**What did you do?**

I tried to come back in the directory using relative path things, so here ``..``:

```v
module main

import os

fn main() {
	println(os.join_path(os.getwd(), '..', 'test'))
}
```

**What did you expect to see?**

Simply the path resolved and joined, or simply get an error about not existing path.

**What did you see instead?**

```
Unhandled Exception 0xC0000005
print_backtrace_skipping_top_frames_mingw is not implemented
```

**Comment by shadowninja55** [comment]
seems to work on latest v
