### ISSUE TITLE
[bug] - os.cp should work when it's another disk

### ISSUE THREAD

**Issue by Olyno** [vlang/v#5254]
**V version:** V 0.1.27 caa25a3
**OS:** Windows 10

**What did you do?**

I simply try to copy a file to a dir which is in another disk (here from ``D:/`` to  ``C:/``):

```v
module main

import os

fn main() {
	mut desktop := os.real_path('C:/Users/WIN10/Desktop/test.exe')
	os.cp(os.real_path('test.exe'), desktop)
}
```

**What did you expect to see?**

Simply copy and paste my exe file in the another disk location
 
**What did you see instead?**

I don't get my exe file where I want, so in this example it should be in the Desktop. Works fine when we target a folder in the same disk.

**Comment by nedpals** [comment]
AFAIK `os.real_path('test.exe')` returns the `test.exe` itself. The workaround was to add a dot and a slash/backslash before the filename (like `./test.exe`) which will return the current location including the filename in the end.

**Comment by spytheman** [comment]
I think real_path should be fixed then - it should always try to return the absolute path of the argument if it can, probably by calling `return os.real_path(os.join_path( os.getwd(), filename))` if it detects that the given filename does not contain `os.path_separator` .

**Comment by danieldaeschle** [comment]
Should be fixed in https://github.com/vlang/v/pull/10251
