### ISSUE TITLE
document translation for Chinese

### ISSUE THREAD

**Issue by RealLau** [vlang/v#526]

**Comment by Kriyszig** [comment]
The translation to mandarin is going on here - > <https://github.com/vlang-cc> afaik from #501

**Comment by cypress-zh** [comment]
@Kriyszig OK thanks.

**Comment by Bowero** [comment]
I don't speak Chinese, but it seems like this is being worked on (#501)

**Comment by chai2010** [comment]
中文文档已经翻译完成（ https://github.com/vlang/v/issues/396 ）：https://vlang-zh.cn/
