### ISSUE TITLE
many cases of division by zero don't give error

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5261]
**V version:** 
Latest master with mingw64

**OS:** 
win10

**What did you do?**
```V
    a := 0
    println(1/a)
```
```V
    a := 0x0
    println(1/a)
```
```V
    println(1/0b0)
```
...etc (Basically every case except for literal “1/0”, which is handled.

**What did you expect to see?**
all give error
 
**What did you see instead?**
all successfully compiled

**Comment by spytheman** [comment]
Nobody can solve the halting problem in the general case.
