### ISSUE TITLE
"a := 100." wrongly gives error

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5262]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
```V
fn main() {
	a := 100.
}
```

**What did you expect to see?**
(give me an unused variable warning but still) compile it
 
**What did you see instead?**
error: unexpected `}`, expecting `name`

**Comment by Gladear** [comment]
The error, even if a bit misleading, is rightly given. V doesn't allow trailing point, you have to write `100.0`.

**Comment by spytheman** [comment]
Can we change the wording for that situation?

**Comment by Gladear** [comment]
It will be pretty hard to change the error message, given that V completely ignores whitespaces.
If we could detect them, it would be easy to give an error like `expected floating number or method call`, but I have no idea if it's possible :confused:

**Comment by medvednikov** [comment]
100. should be legal, like in C, Go etc

**Comment by medvednikov** [comment]
it's should be a short way of writing `x := f64(100)`
