### ISSUE TITLE
floats without fractional parts are printed like integers in REPL

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5263]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
In REPL run
```V
    100.
```
```V
    100.0
```
```V
    1e2
```

**What did you expect to see?**
all print 100.0 
 
**What did you see instead?**
all print 100

**Comment by JalonSolov** [comment]
The first 2 should print `100.0`.  The 3rd one is just `100`, since it doesn't have a fractional part, and you didn't specify it should be float.

**Comment by SleepyRoy** [comment]
@JalonSolov Thanks I got your point, but isn't any number literal with `e` or `E` treated as float in V? Try this in REPL
typeof(1e2) // print 'any_float'

**Comment by JalonSolov** [comment]
If it is treated as float just because of the `e` or `E`, I would say that is incorrect.  `e` just means `a power of 10`, not anything to do with fractions (floats).  Even something like `1.25e2` is still actually an integer, since it is the same as `125`.

That, however, is a very interesting parsing problem.

**Comment by SleepyRoy** [comment]
@JalonSolov 
Yeah, but that would result in a harder-to-remember rule - num literals with `e` or `E` are not always floats, you have to judge their types by yourself. For example, 1.23456e5 is an integer whereas 1.23456e4 is a float. 
Is this a good rule? I guess not.

**Comment by Delta456** [comment]
I suppose we can do this by counting the number of digits after `.` then checking if `e` has same number of digits or not. If it has then its `int` else `float`.

**Comment by JalonSolov** [comment]
That would be the simplest check.

**Comment by Delta456** [comment]
Yes.

**Comment by ArtemkaKun** [comment]
I think we should do next 2 actions:
- add Status: Confirmed label to this issue, since it's still exists
- rename the title of issue, since this problem exists not only for REPL, but also for print/println methods (because a bug in f32/f64.str())

What do you think, @JalonSolov ?

**Comment by ArtemkaKun** [comment]
@spytheman will ping you also

**Comment by spytheman** [comment]
the behavior is still there, but I do not have an opinion whether it is a bug or not

**Comment by JalonSolov** [comment]
I see it as one bug (printing 100 when either 100. or 100.0 is given - it should print 100.0 in both cases instead of 100), and one discussion point:  Should V treat numbers with an exponents as floats even if they resolve to ints?
