### ISSUE TITLE
Cannot pass dynamic functions to map

### ISSUE THREAD

**Issue by sheerun** [vlang/v#5264]
**V version:** V 0.1.27 013bfc7
**OS:** MacOS

**What did you do?**

```
fn custom_map(arr []int, op fn(int) int) []int {
  return arr.map(op)
}

fn main() {
  a := custom_map([1,2,3], fn (i int) int {
    return i + 1
  })
  println(a)
}
```

**What did you expect to see?**

[2, 3, 4]
 
**What did you see instead?**

[239545744, 239545744, 239545744]

**Notes:**

If I use `arr.map(op(it))`, then it works correctly

**Comment by spytheman** [comment]
I am not sure that is a bug, since you can call for example:
`[1,2,3].map(456)`, and it will produce `[456,456,456]` .
If you do not pass op(it), then it just uses the address of the function callback as a constant, and repeats it.

**Comment by sheerun** [comment]
I'd vote it is. I cannot do also the following, which looks natural way of passing function to map:

```vlang
fn main() {
  a := [1,2,3].map(fn (i int) int {
    return i + 1
  })
  println(a)
}
```

After all here is no way to generalize higher order functions without feature like this.

**Comment by sheerun** [comment]
Even more weirdly following works properly even it should be the same as above given "everything is immutable" philosophy

```
fn mapper(i int) int {
    return i + 1
}

fn main() {
  a := [1,2,3].map(mapper)
  println(a)
}
```
