### ISSUE TITLE
interfaces: Can not assign interface member to struct

### ISSUE THREAD

**Issue by helto4real** [vlang/v#5267]
**V version:** 
V 0.1.27 9c87695
**OS:** 
Ubuntu 20.04
**What did you do?**

```v
interface HelloSayer {
    hello()
}

struct Man {

}

struct HasHelloSayers {
    pub:
    sayer HelloSayer
}

fn (m Man) hello() {
    println("hello from man")
}

fn this_should_work() {
    x := HasHelloSayers {
    sayer: Man{}
    }

    x.sayer.hello()
}
```

**What did you expect to see?**
Expected it would be possible to assign interfaces to structs
 
**What did you see instead?**
got 
```
main.v:26:2: error: cannot assign `Man` as `HelloSayer` for field `sayer` 
   24 | fn this_should_work() {
   25 |     x := HasHelloSayers {
   26 |     sayer: Man{}
      |     ~~~~~~~~~~~~
   27 |     }
```

**Comment by spytheman** [comment]
Adding a helper function:
`fn man2sayer(m Man) HelloSayer { return m }`

, then using: `x := HasHelloSayers { sayer: man2sayer(Man{}) }`
serves as a temporary workaround.

**Comment by helto4real** [comment]
Ahh thanks for sharing. Will use that for now.
