### ISSUE TITLE
Error with 'assert false'

### ISSUE THREAD

**Issue by smartiniOnGitHub** [vlang/v#5293]
**V version:** latest (from updated sources)
**OS:** Linux

**What did you do?**
Write in a short way a false assertion:
```
assert false
```

**What did you expect to see?**
Current test failure.
 
**What did you see instead?**
```
V panic: string.eq(): nil string
...
```

I know this is a short way to write failing assertions, but in some cases it's useful to have.
If assertions would check on the boolean result (instead of two parts of test expression) maybe they could be used in a more general way.

If  not a bug maybe this could be seen as an improvement.

Thanks.

**Comment by Ivo-Balbaert** [comment]
With most recent v (V 0.1.27 b3fc462) I get:
             test.v:1: FAIL: fn main: assert false
             V panic: string.eq(): nil string
on both Windows 10 and Ubuntu 20. However on Ubuntu only when the code is run with 'v run', when compiling and executing, nothing is shown.

**Comment by nedpals** [comment]
Fixed. See: https://devbits.app/play/XE7Hjm1Z6Fw4

**Comment by smartiniOnGitHub** [comment]
@nedpals Hi, thanks for the fix but just re-tried with the link you posted and got segfault again ...

main.v:1: FAIL: fn main.main: assert false
V panic: Assertion failed...
                                               | 0x5590f16ef23a | /tmp/v110351719/main(+0x1823a) 
                                               | 0x5590f16f6ef7 | /tmp/v110351719/main(+0x1fef7) 
                                               | 0x7f9a4bf18bf7 | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) 
                                               | 0x5590f16d7dba | /tmp/v110351719/main(+0xdba) 
Segmentation fault (core dumped)

**Comment by nedpals** [comment]
@smartiniOnGitHub It's the correct behavior although I'm not sure why `panic`-ing (in general) segfaults but it should be in a separate issue instead.
