### ISSUE TITLE
Compiler sizes

### ISSUE THREAD

**Issue by konsumlamm** [vlang/v#5302]
The [website](https://vlang.io/) claims the following:

### Small and easy to build compiler

The entire language and its standard library are less than 2 MB. V can be bootstrapped in under a second by compiling its code translated to C with a simple

cc v.c

No libraries or dependencies needed.

For comparison: 

  | Space required | Build time
-- | -- | --
Go | 525 MB | 1m 33s
Rust | 30 GB | 45m
GCC | 8 GB | 50m
Clang | 90 GB | 60m
Swift | 70 GB | 90m
V | < 2 MB | <1s

I wanted to check these claims so I downloaded the source of the (latest version of the) respective compilers. To measure the space, i used `du -hs`. First of all, the website claims that the V source is 1.9 MB, while it is 2 MB (though that is just bikeshedding I suppose). However, that is for the compressed source, which I think is pretty unfair, especially since different compression algorithms might compress things differently. So I used the decompressed sizes for my measurements. The comparison with GCC also is a bit unfair, since it's a compiler collection, not a single compiler. Here is what I got;

|  | Space | Version
-- | -- | --
Go | 188 MB | 1.14.4
Rust | 1.8 GB | 1.44.0
GCC | 1.7 GB | 10.1.0
Clang | 318 MB | 10.0.0
Swift | 297 MB | 5.2.4
V | 14 MB | 0.1.27

As you can see, our numbers are massively different, so I'm curious how you got your numbers. Maybe you measured something different, in that case you should make that clear on the website.

**Comment by medvednikov** [comment]
There are references on the website. These are numbers required to build Swift, Clang, etc.

I'll update space required to < 10 MB.

**Comment by medvednikov** [comment]
For example

https://github.com/apple/swift#getting-started

> These instructions give the most direct path to a working Swift development environment. To build from source you will need about 2 GB of disk space for the source code and up to 70 GB of disk space for the build artifacts with full debugging. Depending on your machine, a clean build can take a few minutes to several hours.

**Comment by medvednikov** [comment]
Actually scratch that, <2 MB is correct.

This is a section about bootstrapping compilers, and for V it's just `cc v.c`, v.c is 1.3 MB.

**Comment by konsumlamm** [comment]
The 70 GB for Swift for example include build artifacts, while your <2 MB for V only include the source code (translated to C). Don't you think this is an unfair comparison? Furthermore, wouldn't bootstrapping mean that you build the V source code (written in V) instead of the translated C code (which effectively skips a step)?

**Comment by konsumlamm** [comment]
> There are references on the website. These are numbers required to build Swift, Clang, etc.

For Clang, Swift and (now) V, yes, but not for Go, Rust and GCC.

**Comment by medvednikov** [comment]
With build artefacts it's still <2 MB. No, bootstrapping means building it with something that you can build with, not a non-existant V compiler.

**Comment by konsumlamm** [comment]
So the <2 MB only apply to the original compiler used to bootstrap?
