### ISSUE TITLE
vfmt fills compile time pseudo variables

### ISSUE THREAD

**Issue by Serkonda** [vlang/v#5308]
**V version:** V 0.1.27 3664bea
**OS:** Manjaro Linux

**What did you do?**
`v fmt -w myfile.v` where the file makes use of `@VMOD_FILE`.

**What did you expect to see?**
Format the file but leave `@VMOD_FILE` as it is.
 
**What did you see instead?**
`@VMOD_FILE` was filled with the contents of `v.mod`.
For normal compilation this is correct but later changes to `v.mod` would then not be respected.

**Comment by nedpals** [comment]
On the scanner stage, all the pseudo compile-time variables are being replaced with their real values like the case with `VMOD_FILE` shown below:

![image](https://user-images.githubusercontent.com/7358345/84213090-539fa380-aaf2-11ea-8540-3ef68ec1e3c3.png)
