### ISSUE TITLE
Unable to build a vweb app with production mode

### ISSUE THREAD

**Issue by smartiniOnGitHub** [vlang/v#5318]
**V version:** latest sources
**OS:** Ubuntu 20.04 LTS

**What did you do?**
A minimal vweb app; all works when running in normal mode.

**What did you expect to see?**
When I compile for production, I expect the build to generate the optimized binary file.
 
**What did you see instead?**
```
>>> compiling vweb HTML template "index.html"
:65:1138: error: unused variable: `tmpl_res_index`
```

Thanks

**Comment by smartiniOnGitHub** [comment]
Sorry, would it be possible to comment out println statements in vweb (some is already under $if debug) ? To start do some benchmarks for example ...

**Comment by medvednikov** [comment]
I've removed all debug prints.

**Comment by medvednikov** [comment]
The warning fixed as well.

**Comment by smartiniOnGitHub** [comment]
@medvednikov after the fix, just to give some info: 
in Linux for a minimal vweb app (that reply only an hello world in json) is:
source: 836 bytes (with many comments inside)
binary normal: 357KB
binary (with production mode, using only the "-prod" flag): 52 KB
so this looks great !!
Thank you very much for all this.

**Comment by medvednikov** [comment]
Yeah, I'm super excited :)
