### ISSUE TITLE
Add the ability to include files in vweb templates

### ISSUE THREAD

**Issue by smartiniOnGitHub** [vlang/v#5320]
Hi all,
in some cases it would be useful to split template files in smaller/reusable parts, usually by include other templates and/or static page fragments, with a tag "@include <file_path_and_name>" and file path relative to current template (and no absolute paths, safer).
In this way even current solution to always include an header page if present could be dropped for example, with this (more general) solution.
Note that in many template frameworks it's an available option.

Tell me if you need more info.

Thanks a lot.

**Comment by medvednikov** [comment]
Yes, this will be implemented.

**Comment by joe-conigliaro** [comment]
https://github.com/vlang/v/pull/5351

**Comment by danieldaeschle** [comment]
paths will be relative absolute :D

**Comment by joe-conigliaro** [comment]
@danieldaeschle relative absolue :smile:

**Comment by danieldaeschle** [comment]
Absolute beginning from templates/

**Comment by smartiniOnGitHub** [comment]
To simplify things, maybe in the initial version include only static files ... include templates required nested processing etc so could be more complex; just as idea.

**Comment by fnetX** [comment]
Can this be closed or is the current implementation still incomplete?
