### ISSUE TITLE
Is 'a += 1', 'a -= 1' allowed?

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5323]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
```V
fn main() {
	mut a := 10
	a += 1
}
```

Now the above is able to be compiled. But I remember it used to give error in old V.

**Comment by prooxeydev** [comment]
it's planned afaik that a++ and a-- will be removed, so just use a += 1/a -= 1

**Comment by medvednikov** [comment]
No, ++ will stay and will be enforced for consistency, like in V1

**Comment by Serkonda** [comment]
I would say removing ++ would be a lot more consistent if we keep  `a += 2/ a -= 2`

**Comment by JalonSolov** [comment]
Hrm.  In looking at it written out, I tend to agree with Serkonda.  It seems arbitrary to allow `+=` and `-=` with every integer _except_ 1.

**Comment by Serkonda** [comment]
@medvednikov I still have to say ++/-- should not be allowed.
You now have two ways for adding integers: one that only works for 1
and the other way for all the other ints.

One-way-philosophy??

**Comment by medvednikov** [comment]
++ is awesome

**Comment by Serkonda** [comment]
@medvednikov I agree that ++ is awesome, but imo it's a second way of doing things
You could do the same with += which still exists but we are not allowed to.

I'm not happy that it gives an error, maybe a warning that use is not recommended,
but why forbid an existing way of addition/substraction (for 1) to force another?

**Comment by medvednikov** [comment]
> it's a second way of doing things

that's exactly why V enforces ++, not += 1

**Comment by Serkonda** [comment]
The problem is that the += way still exists for any other integer
