### ISSUE TITLE
vweb   error: unexpected `name`, expecting `if`

### ISSUE THREAD

**Issue by zhuxiujia** [vlang/v#5325]
**V version:*last* 
**OS:**  windows

**What did you do?**
v  run vweb_example.v

```v 
.\vweb_example.v:30:3: error: unexpected `name`, expecting `if`
   28 | pub fn (mut app App) index() {
   29 |     app.cnt++
   30 |     $vweb.html()
      |      ~~~~
   31 | }
   32 |
```

**Comment by mcastorina** [comment]
vweb_example.v works (both compiling and running).

OS: windows, Microsoft Windows 10 Pro v19041 64-bit
V full version: V 0.2.2 9e06af8

This issue can be closed
