### ISSUE TITLE
should disallow assigning main to variables

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5333]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
```V
fn main() {
	a := main
}
```

**What did you expect to see?**
V error
 
**What did you see instead?**
C error

**Comment by JalonSolov** [comment]
No longer gives a C error, but no V error, either.
```
jalon@Ripper:~/git/v$ v foo.v

fn main() {
foo.v:2:2: warning: unused variable: `a`
    1 | fn main() {
    2 |     a := main
      |     ^
    3 | }
    4 |
jalon@Ripper:~/git/v$
```

**Comment by medvednikov** [comment]
Copy-pasting my reply:

I feel like this is adding too much logic/checks for something that's going to be done in 1 out of 1 million programs.

Having a quick compiler means avoiding checks like this.

Have you ever seen the main function assigned to a variable?

This works in Go, I see no reason to implement this.
