### ISSUE TITLE
should disallow multiple [inline] on one function

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5334]
**V version:** 
latest master with mingw64

**OS:** 
win10 

**What did you do?**
```V
[inline] [inline] 
fn foo() {

}
```

**What did you expect to see?**
error
 
**What did you see instead?**
compiled

Please call me strange-person-good-at-finding-strange-bugs : )

**Comment by joe-conigliaro** [comment]
It should syntax error

**Comment by joe-conigliaro** [comment]
I think multiple attributes are currently separated with a semicolon: `[one; two]`

**Comment by yuyi98** [comment]
map.v
```v
[inline]
[unsafe_fn]
fn new_dense_array(value_bytes int) DenseArray {
	return DenseArray{
		value_bytes: value_bytes
		cap: 8
		size: 0
		deletes: 0
		keys: &string(malloc(int(8 * sizeof(string))))
		values: malloc(8 * value_bytes)
	}
}
```
Not sure how `attributes` rules are defined?

**Comment by SleepyRoy** [comment]
@medvednikov Seems there're now two ways giving multiple attributes - `[one] [two]` and `[one; two]`? Should we allow only one style?

**Comment by JalonSolov** [comment]
It should only allow one style (to match the v philosophy of "only one way"), and it should definitely at least warn if the same attribute is given twice.

**Comment by medvednikov** [comment]
```
[inline]
[unsafe_fn]
fn new_dense_array {}
```
should be the only way

**Comment by medvednikov** [comment]
I don't remember implementing `[x;y]`, if someone else did, it should be reverted.

**Comment by joe-conigliaro** [comment]
I dunno I was just going by the code :)

**Comment by joe-conigliaro** [comment]
Wait a min thats so weird, look loke there is two methods for parsing attributs and they both behave differently (attribtes and attrs) hrmm I wll sort this issue out
