### ISSUE TITLE
The second run of ```fmt``` throws an error in the following case

### ISSUE THREAD

**Issue by fylimas** [vlang/v#5342]
**V version: 0.1.27 6081e0d.895c762** 
**OS: macOS** 

**What did you do?**
The content of test.v file is
```v
struct Version { // some comment
mut:
	file string
}
```
Run command ```v fmt -w test.v``` 2 times
**What did you expect to see?**
First run of v fmt -w test.v gives
```Reformatted file:/path/to/file.v```
The reformatted file is
```v
struct Version {
mut: // some comment
	file string
}
```
_Second run of v fmt -w test.v **should** give_
```Already formatted file:/path/to/file.v```
 
**What did you see instead?**

_**But** the second run throws an error:_
```
test.v:2:7: error: unexpected `// comment`, expecting `name` 
    1 | struct Version {
    2 | mut: // some comment
      |       ~~~~~~~~~~~~~~
    3 |     file string
    4 | }
vfmt error while formatting file: test.v .
Encountered a total of: 1 errors.
```

**Comment by nedpals** [comment]
@fylimas This is more like a parser issue. As of now, we're still trying to figure out the best way to parse and store the comments metadata.

**Comment by serkonda7** [comment]
Fixed in newer versions of V.
