### ISSUE TITLE
redundant braces don't result in error

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5344]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
e.g.
```V
fn main() {
    { }
}
```
```V
fn main() {
    for { 
        { }
    }
}
```
```V
fn main() {
}
{  }
```

**What did you expect to see?**
all give error
 
**What did you see instead?**
all compiled

**Comment by medvednikov** [comment]
And it shouldn't. It's just an empty block. Go, for example: https://play.golang.org/p/7psFFdskDUh
