### ISSUE TITLE
Improve syntax for anonymous functions

### ISSUE THREAD

**Issue by sheerun** [vlang/v#5356]
I've noticed that when mapping arrays with anonymous function, the declarations on anonymous functions are superfluous as they can be computed from function code and mapped thing. For example following:

```v
a := [1,2,3].map(fn (i int) bool {
  return i > 5
})
```

could be written as:

```v
a := [1,2,3].map(fn (i) { return i > 5 })
```

also the "return" and "fn" seems unnecesary so we're left with:

```v
a := [1,2,3].map((i) { i > 5 })
```

This syntax has few nice properties:

1. Contrary to current `it > 5` or `[5]` or `5`, it's easy to generalize (i.e. allow for programmers to define custom higher-order functions that can accept short anonymous function) as it's clear from syntax itself that we are passing function to another function, instead of some value. Current implementation hardcores this information in name of higher-order functon (only `map` and `filter` support them)
2. It can easily support multiple arguments by default, for example: 

```v
[1,2,3].reduce((sum, e) { sum + e }, 0)
```

For course it would require improvements in department of generic functions, but currently it would be possible to implement this function as:

```v
fn (arr []int) reduce(fn func(int, int) int, start int) int {
  mut x := start
  for e in arr {
    x = func(x, e)
  }
  return x
}
```

3. As seen above, the variable can be nicely named, improving readability of code. Current implementations forces `it` name.

**Comment by sheerun** [comment]
A question one could as is how to differentiate  function returning something from function returning nothing. The answer is that this information would be encoded in definition of higher-order function. For example there could be two higher-order functions:

```v
// rejects elements if function returns true
fn (a []<T>) reject(fn (T) bool) []T
```

```v
// prints elements if function returns true
fn (a []<T>) printif(fn (T)) []T
```

they could be used as follows:

```v
[1,2,3].reject((i) { i < 2 })
```

```v
[1,2,3].printif((i) { i < 2 })
```

The first one would generate function with return argument, and second one would generate one without return argument, even though the call syntax is the same.

**Comment by sheerun** [comment]
The `it` syntax can stay of course as shorthand that doesn't support naming arguments or multiple arguments, so they could be called as:

```y
[1,2,3].reject(it < 2)
[1,2,3].printif(it < 2)
```

**Comment by leahlundqvist** [comment]
Closing this as it contrasts against V's "one-way policy" and will most likely not be implemented
