### ISSUE TITLE
bare '[if true {1} else {2}]' doesn't work

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5358]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
```V
fn main() {
	[if true {1} else {2}]
}
```

**What did you expect to see?**
compile (correction: should give unused error once #5056 is fixed) 
 
**What did you see instead?**
C error

Interestingly some variants work e.g.
```V
fn main() {
	a := [if true {1} else {2}]
}
```

**Comment by Delta456** [comment]
Why should this be compiled?

**Comment by SleepyRoy** [comment]
@Delta456 `[if true {1} else {2}]` should be compiled as long as `[1]` is allowed and compiled.

**Comment by Delta456** [comment]
It's not been used though. It should give a specific error imo.

**Comment by SleepyRoy** [comment]
@Delta456 Yeah, it should give unused error once #5056 is fixed. I think we can keep this issue open and see whether it could be closed after #5056 is fixed.

**Comment by medvednikov** [comment]
good find, it should definitely compile

**Comment by SleepyRoy** [comment]
Confirmed: followed by merge of #5395, this case now correctly gives `evaluated but not used` error.
Close it.
