### ISSUE TITLE
v tetris.v -> tetris.tmp.c -> LINK : fatal error LNK1104: cannot open file 'freetype.lib'

### ISSUE THREAD

**Issue by THX1188** [vlang/v#5367]
Hi all,
My System is Windows 10, Visual Studio 19 installed
- cloned the v- reporsitory
- build the compiler with make (make.bat)
- successfully build
- set Path Vailable to v directory
- restarted cmd.exe

- cd to examples/tetris
- **v tetris.v** failes as the freetype.lib is missing

could you support?
I also was on freetype source page but did not see an option to buld the library with Visualstudio 

Kind regards
THX1188

**Comment by JalonSolov** [comment]
You also need to add the thirdparty/freetype/win32 or thirdparty/freetype/win64 to match your OS.

**Comment by THX1188** [comment]
Thank you for the tip!
how should I build the files? or do you know some prebuild versions to download for Windows 10?
With VC19 it will not work. Its not suported

**Comment by THX1188** [comment]
I found a pre-compiled version : https://github.com/ubawurinna/freetype-windows-binaries/blob/master/win64/freetype.lib
- copied freetype.lib in directory  <VHOME>/thirdparty/freetype/win64 
- cd to examples/tetris
- compiled v tetris.v ...

> 13/06/2020  18:17           769.024 tetris.exe
> 13/06/2020  18:17         1.139.416 tetris.ilk
> 13/06/2020  18:17         1.224.704 tetris.pdb
> 13/06/2020  16:25             9.796 tetris.v
>                4 File(s)      3.142.940 bytes
>                0 Dir(s)  329.425.457.152 bytes free
> 
works!

Thanks
/THX1188

**Comment by medvednikov** [comment]
freetype should no longer be used on windows, will check once i get a windows vm back

**Comment by THX1188** [comment]
yes that would be nice , thank you!

**Comment by rpherman** [comment]
I have the same error today after building v just cloned today. Do I copy the file from the link above, or has this been resolved by getting rid of freelib dependency on Windows? Thanks!

**Comment by rpherman** [comment]
If I copy freetype.lib to the above directory tetris.v compiles, but it then opens a blank screen minus any pieces, and closes immediately.

**Comment by JalonSolov** [comment]
freetype is still required as of V 0.1.28 db05e5b.

**Comment by ChildishGiant** [comment]
Repro'd on V 0.1.28 bbaf6e3a1cd8486411ae9237711e5c01373e023e on Windows 10 v 1909 (OS Build 18363.959)

**Comment by shiMusa** [comment]
Was just trying it, doesn't work. The folder "freetype/" doesn't even exist...
How do I get this running? 
Thanks for any help

**Comment by ubershmekel** [comment]
Still the case with Microsoft Windows [Version 10.0.19041.630]

```
D:\1stuff\dev\2020\vgame\v\examples\hot_reload>v run bounce.v
INFO: compile with `v -live bounce.v `, if you want to use the [live] function frame .
INFO: compile with `v -live bounce.v `, if you want to use the [live] function update_model .
builder error: Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27031.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

bounce.tmp.c
LINK : fatal error LNK1104: cannot open file 'freetype.lib'

D:\1stuff\dev\2020\vgame\v\examples\hot_reload>
```

**Comment by penguindark** [comment]
tested on windows, now ok.
