### ISSUE TITLE
Direct x64 machine code generation - considerations for implementation for macOS and Windows

### ISSUE THREAD

**Issue by ylluminate** [vlang/v#5374]
As we all know, x64 code generation is currently only available for Linux.  The purpose of this issue is to track, discuss and collaborate on efforts to get this also implemented for macOS and Windows (or to branch out into other issues to get more specific for each).

**Comment by sheerun** [comment]
Here are some resources for MacOS Mach-O format and assembler:

- http://www.idryman.org/blog/2014/12/02/writing-64-bit-assembly-on-mac-os-x/
- https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/Assembler/000-Introduction/introduction.html#//apple_ref/doc/uid/TP30000851-CH211-SW1
- https://github.com/aidansteele/osx-abi-macho-file-format-reference

**Comment by ylluminate** [comment]
Due to Apple's stance on static bins, could parts of [Darling](https://www.darlinghq.org/) ([GitHub](https://github.com/darlinghq/darling) & [other associated repos](https://github.com/darlinghq?q=&type=&language=) be used to help accomplish this?

**Comment by bjorn3** [comment]
Linux is one of the few systems that has a stable syscall interface. On all other systems you **must** use the system libraries to interface with the kernel. For macOS cross compilation there seems to be https://github.com/tpoechtrager/osxcross. For Windows cross compilation you can use mingw.

**Comment by medvednikov** [comment]
Exactly. V is going to be able to generate dynamically linked binaries.

For now it's Linux/static only.

**Comment by ylluminate** [comment]
For Windows @nord501 noted that it should be pe.v and asks whether or not we should use kernel32 or ntdll.lib...

**Comment by sheerun** [comment]
For sure little-endianness of mach-o and big-endianness of elf is big change. We can't use the same Gen class for handling both, I don't want as I don't want to put 1000s of if-elses there. I think we need to split code into `v/gen/x64/elf` and `v/gen/x64/macho` directories and put helper shared helper functions in `v/gen/x64`

**Comment by ylluminate** [comment]
@nord501 is putting forth a valiant and successful effort with Windows implementation and [noted this last night](https://discordapp.com/channels/592103645835821068/648394572501876746/723384231736246303) that he now has a working `hello world` and is digging into V's x64 gen for integration. Source: 
https://github.com/nord501/pe.v/blob/master/pe.v

**Comment by ylluminate** [comment]
macOS 11 (Big Sur) updates: https://gist.github.com/FiloSottile/7125822#gistcomment-3578065
