### ISSUE TITLE
error while loading shared libraries: ?: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by fxqy** [vlang/v#5375]
**V version:** V 0.1.27 471c931
**OS:** win10 mingw-w64-x86_64

**What did you do?**
v run users.v

**What did you expect to see?**
ui show
 
**What did you see instead?**
C:/v/v.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

![20200614115237384](https://user-images.githubusercontent.com/42601163/84584333-95ec1c00-ae35-11ea-9c60-76e70c357f37.jpg)

**Comment by bashery** [comment]
hi.
this is linux not windows.
the command : "v install package" is not working.
you can download ui package, and run : 
**v run paht/to/user.v**

**Comment by dhonx** [comment]
Yeah... As alternative, you can try https://vpkg-project.github.io. Simply `vpkg get ui`
