### ISSUE TITLE
v install <package> does not work

### ISSUE THREAD

**Issue by bashery** [vlang/v#5376]
**V version:** 
V 0.1.27 471c931

**OS:**
 Linux

**What did you do?**
v install pkg

**What did you expect to see?**
installation complete.
 
**What did you see instead?**
The installation did not complete, and there is no error or warning that the operation was unsuccessful

**Comment by prooxeydev** [comment]
there is no module `pkg`
![error](https://user-images.githubusercontent.com/49022854/84592812-9e018700-ae48-11ea-8083-2b591bc3b6aa.png)
and that's what come out

**Comment by JalonSolov** [comment]
The problem there is that it should have stopped after notifying there was no such package.

**Comment by bashery** [comment]
I means that command do nothing with any pkg
e.g:  v install ui

**Comment by spytheman** [comment]
Can you try again with latest v @bashery ?

**Comment by jerejacobson** [comment]
I am having the same issue on windows 10.


PS C:\Users\bullf> v up
Updating V...
Current V version:
V 0.1.27 730f485
PS C:\Users\bullf> v install ui
Updating module "ui"...
Failed updating module "ui".

**Comment by bashery** [comment]
The problem exists even with the latest version.
$ v up
Updating V...
Current V version:
V 0.1.27 fb5cae7

$ v install ui
Updating module "ui"...

[fedora@localhost ~/v] 
$ ls ui
ls: cannot access 'ui': No such file or directory
[fedora@localhost ~/v] 
$ ls vlib/ui
ls: cannot access 'vlib/ui': No such file or directory
[fedora@localhost ~/v]

**Comment by JalonSolov** [comment]
It installs modules to `~/.vmodules`, not your current directory or under `vlib`.

**Comment by bashery** [comment]
There was no problem. But I just imagined a problem. Thanks everyone for the help.
Thanks JalonSolov for the clarification.
