### ISSUE TITLE
Weird behavior in condition with two compare_string

### ISSUE THREAD

**Issue by thomas-senechal** [vlang/v#538]
**V version:** 
0.1.0
**OS:** 
Linux - Fedora 30
**C compiler version:** 
clang version 8.0.0 (Fedora 8.0.0-1.fc30)

**What did you do?**
I tried to compare 3 strings in an 'if' like this:
`if !compare_strings(a, b) || !compare_strings(b, c) {`

**What did you expect to see?**
I thought the program would compile.
 
**What did you see instead?**
`v bug.v 
pass=2 fn=`main`
panic: bug.v:5
expected type `int`, but got `bool`
`
And if I add parentheses around one of the two comparisons like this : 
`if (!compare_strings(a, b)) || !compare_strings(b, c) {`
It compile.

I found that if I remove the '!' the error changes into: 
pass=2 fn=`main`
panic: bug.v:5
expected type `bool`, but got `int`
But the parentheses "fix" doesn't work without parentheses.

Not knowing if it was planned in any way, I prefer to post it here.

Example : 
```
fn main() {
    a := 'azert'
    b := 'yuiop'
    c := 'treza'
    if !compare_strings(a, b) || !compare_strings(b, c) {
        println('OK')
    }
}
```

**Comment by Bowero** [comment]
The function `compare_strings(a string, b string)` returns an integer:

+ -1: `a` is smaller than `b`
+ 0: the strings are equal
+ 1: `a` is bigger than `b`

It does not check if two strings are equal. Because there are 3 options, we can't return a boolean.

**Comment by lutherwenxu** [comment]
The intended way to do it is to use `!=` as in `a != b`.

**Comment by Bowero** [comment]
```
fn main() {
    test :=     'test'
    test2 :=    'test'
    result :=   test == test2

    println(result)
}
```

This works if you want to compare strings indeed. If you want to sort them, you can use `compare_strings(a string, b string)`. I assume this resolves the issue.
