### ISSUE TITLE
[ORM] error: unexpected `select`, expecting `name`

### ISSUE THREAD

**Issue by granbestiapop** [vlang/v#5390]
**V version:** V 0.1.27 a69d8c6
**OS:**  macOS, Linux Debian 10

**What did you do?**
```
v run examples/database/pg/customer.v
```

**What did you expect to see?**
Compile and run example
 
**What did you see instead?**
```
examples/database/pg/customer.v:23:21: error: unexpected `select`, expecting `name`
   21 |     }
   22 |
   23 |     nr_customers := db.select count from Customer
      |                        ~~~~~~
   24 |     println('Total customers: $nr_customers')
   25 |
```
ORM example doesn't compile, tested on Debian 10 and MacOS Catalina.

**Comment by medvednikov** [comment]
I'm working on this right now :)

**Comment by Serkonda** [comment]
I think this is fixed

**Comment by LouisSchmieder** [comment]
yeah there is now a new syntax
