### ISSUE TITLE
is_lower() and is_upper() produces incorrect results

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [vlang/v#5393]
**V version:** V 0.1.27 015d0c5
**OS:** Linux

**What did you do?**
I tried to check if a single-character string was lowercase and got the wrong bool value.
`'.'.is_lower()`

**What did you expect to see?**
It should produce false because a period is not a lowercase letter.
 
**What did you see instead?**
The result was `true` because `is_lower()` only checks if the string in question is NOT uppercase rather than if each character in the string is actually in the range a-z.
The same occurs for `is_upper()` except it only checks that each character is NOT lowercase rather than if each character is actually in the range A-Z.

**Comment by THX1188** [comment]
Hi OpenSourceAnarchist, what would you expect for 'name.firstname'.is_lower()
cheers

**Comment by sudo-nice** [comment]
It's meaningless to apply `.to_upper()` or `.to_lower()` to a punctuation mark and expect a definite result. Consider this:

 ```v
fn main() {
	str := '.'
	assert str.to_lower() == str // which means, the string was in lower case, so `.is_lower()` should be `true`
	assert str.to_upper() == str // which means the string was in upper case, so `.is_upper()` should be `true`
}
```

**Comment by OpenSourceAnarchist** [comment]
@THX1188 Rather than changing the behavior of the methods, it may be useful to introduce a simple `is_letter()` check which could be used in conjunction with these methods. That would allow you to choose the behavior of these methods on a string like 'name.firstname'.
@sudo-nice I would argue that these checks only make sense if the character/string is only composed of letters. It seems odd to say that '6' or '!' are both uppercase and lowercase. If the default behavior should not be changed, then a simple `is_letter()` method should allow for the functionality I'm thinking of.

**Comment by THX1188** [comment]
@OpenSourceAnarchistIs a separation compulsion really necessary?
'The.Times'.is_upper()  // false 
'THE.TIMES'.is_upper() // true 

would be fine for me
It's just need an internal ignore list, and for a '.' let me say it that way an '.'.is_upper() should be _undefined_
but _undefined_ is not an option for the v-lang?

**Comment by OpenSourceAnarchist** [comment]
@THX1188 V has option types, but I think it would be silly to have `is_lower()` and `is_upper()` return bool options. I agree that it should be undefined, as in my program I expected both methods to return false for non-alpha characters, while it seems Python's default is the current behavior, where any non-alpha character is ignored. I can do a simple check in my program to get the functionality I want, but I guess the discussion is really: 1) Should `is_lower()` and `is_upper()` simply ignore non-alpha characters, and 2) If no, should a method checking if the string contains only alphabetic characters be added?

**Comment by THX1188** [comment]
@OpenSourceAnarchist 

> as in my program I expected both methods to return false for non-alpha characters

That's the point the expectation. During the discussion I asked myself against what rule our expectations are based; Basically an is_upper(), is_lower() should be logically connected to the transforming functions to_upper() and to_lower() function. 
Now a '.'.to_upper() == '.'.to_lower() == '.' 
means for me the current implementation of is_upper() / is_lower() is consistent to the transformation functions to_upper()/to_lower() which is fine so far. 
So far :)

**Comment by OpenSourceAnarchist** [comment]
@THX1188 I understand your point and I agree that it should be consistent. I can close the issue and write two versions of the methods that I was expecting. So long as the current version is documented, I don't see that as being a problem. However, I do think it is reasonable to think that `is_lower()` and `is_upper()` could have different functionality than their counterparts if the expectation is that non-alpha characters should not be considered as lowercase/uppercase. Then, `to_lower()` and `to_upper()` would actually be consistent with the expectation since non-alpha characters would be ignored in the conversion but known to not be actually lowercase/uppercase.

But I think you're right about consistency, so I'll just close the issue unless someone thinks an `is_alpha()` method is a good idea or if the behavior of these two methods should be altered.
