### ISSUE TITLE
[BUG] vlang playground can't compile any examples

### ISSUE THREAD

**Issue by yanniskatsaros** [vlang/v#5396]
Hello,

I attempted to run a few of the examples in the v-lang playground but was getting this issue for any of the examples I tried
![image](https://user-images.githubusercontent.com/32942328/84787220-58ad9880-afb3-11ea-81f7-15271c6f43a2.png)

I understand the playground is in alpha, but I wanted to make you aware of this issue. Thanks!

**Comment by Serkonda** [comment]
The playground is not usable atm, try to paste the example in https://devbits.app/play

**Comment by medvednikov** [comment]
The wasm playground is now used instead.

**Comment by Zireael07** [comment]
The wasm playground is now broken too :(

**Comment by medvednikov** [comment]
@Zireael07 https://play.vlang.io/ works fine

**Comment by JalonSolov** [comment]
The wasm playground is no longer used, and hasn't been updated (as far as I'm aware) in a long time.  Use the link @medvednikov gave you.

**Comment by Zireael07** [comment]
@JalonSolov If it isn't used, the link to it from the homepage (under JS heading) should be removed

**Comment by JalonSolov** [comment]
The link at the top of the home page was changed quite a while ago.  Do you know of anywhere else that hasn't been changed?

**Comment by Zireael07** [comment]
<img width="1133" height="729" alt="Image" src="https://github.com/user-attachments/assets/ff05a814-943a-4793-bf8f-38da6225581a" />

**Comment by JalonSolov** [comment]
@medvednikov will have to change that.
