### ISSUE TITLE
make on Windows 10 fails and shows partial print of path

### ISSUE THREAD

**Issue by rpherman** [vlang/v#5399]
**V version:** latest master as of 2020/06/16
**OS:** Windows 10

**What did you do?** cloned v directory from x64 Native Tools Command Prompt for Windows VS 2019; cd v; make -msvc

**What did you expect to see?** compiling messages and return to command prompt

 
**What did you see instead?** Attempting to build v.c with MSVC... Then it stops at a partial print out of my path with this at the end of the path: 

```
"=="" was unexpected at this time.

```
It then returns to the c:\users\me\v prompt.

**Comment by JalonSolov** [comment]
Try with just `make` instead of `make -msvc`... v will try different compilers.

If that still doesn't work, mingw version of gcc works fine (I just tried it - no error).  Download and install the correct version for your machine (32-bit vs 64-bit), and try `make` again.

**Comment by spytheman** [comment]
You can also try `make.bat -msvc` explicitly. 
I think that doing just `make` may fail, if you have a make.exe in your path.

**Comment by M4SSD35TRUCT10N** [comment]
Nope. Doesn't work. I have to set skip_path="" in another script in order to have make.bat run successfully. This script does some git and backup stuff beforehand and afterwards.

**Comment by Ekopalypse** [comment]
@rpherman, I assume this can be closed as the current versions seems to work as expected.

~~~
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.29
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

D:\ProgramData\Microsoft Visual Studio\2017\Community>cd \

D:\>cd temp

D:\temp>git clone https://github.com/vlang/v.git v
Cloning into 'v'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 81869 (delta 18), reused 23 (delta 9), pack-reused 81810R
Receiving objects: 100% (81869/81869), 31.98 MiB | 6.37 MiB/s, done.
Resolving deltas: 100% (58668/58668), done.

D:\temp>cd v && make -msvc
Bootstraping TCC...
 > TCC not found
 > Downloading TCC64 from https://github.com/vlang/tccbin

Cloning vc...
 > Cloning from remote https://github.com/vlang/vc

Building V...
 > Attempting to build v_win.c with MSVC
 > Compiling with .\v.exe self
 > V built successfully
 > To add V to your PATH, run `.\v.exe symlink`.

V version: V 0.2.2 3b166d8

D:\temp\v>dir v.exe
...

27.03.2021  17:38         3.163.648 v.exe
~~~

Note: I have verified with procmon that the binary was created with cl.exe.
