### ISSUE TITLE
Provide high level road maps for the project

### ISSUE THREAD

**Issue by crides** [vlang/v#5405]
I know this project is in very early stage, and a lot of features aren't implemented yet, so please put a high level road map/todo list specifying what features are implemented and what are not. For now, it's very confusing for ... everyone. You can't have 1.2Mloc/s of compile speed *and* have null pointers:

```v
fn main() {
    _ := *byteptr(0)
}
```

If you (and the other contributers) have the time to put up a very detailed tutorial, this shouldn't take that much time. But this will make sure new comers don't have conflicting expectations.

**Comment by spytheman** [comment]
@crides there is https://github.com/vlang/v/blob/master/0.2_roadmap.txt .

**Comment by crides** [comment]
Yes but that does not include the roadmap for the language. For example, I can't find any mentioning of null or memory management in it.

**Comment by JalonSolov** [comment]
From the home page (https://vlang.io/):

Safety

- No null
- No global variables
- No undefined values
- No undefined behavior
- No variable shadowing
- Bounds checking
- Option/Result types
- Generics
- Immutable variables by default
- Pure functions by default
- Immutable structs by default

Later on the same page, it talks about hot code reloading.

Why have a separate roadmap mentioning these?

**Comment by crides** [comment]
Because null pointers are definitely a thing in the language, but that's not listed anywhere. You can only derive that yourself by reading a lot of the documentation. That's the same for other features as well. My point is not that there needs to be a place that lists all the features, but rather a simple description of the progress on each one.

**Comment by medvednikov** [comment]
Null pointers are only used for C interop, that usage is documented, and `unsafe{}` will be required soon.

**Comment by medvednikov** [comment]
Hot code reloading has been available for a year now, not sure why you need a roadmap for it.
