### ISSUE TITLE
gg: Find font location

### ISSUE THREAD

**Issue by JohnAZoidberg** [vlang/v#542]
**V version:** 0.1.0

**What did you do?**
Buildt and ran tetris.

**What did you expect to see?**
See it running and find the font.
 
**What did you see instead?**
```
$ ./tetris
[...]
failed to load RobotoMono-Regular.ttf
```

**Suggestion**
The path to the font is hardcoded to the current directory or `/var/tmp/RobotoMono-Regular.ttf` in https://github.com/vlang/v/blob/master/gg/gg.v#L345.
It would be cool if it could properly figure out where the font file is.
Probably the easiest way is to do it at build-time: https://stackoverflow.com/a/23245604/5932056

Feel free to move this issue to the new repo once you have the code there.

**Comment by medvednikov** [comment]
No, this will be fixed sooner :)

**Comment by Bowero** [comment]
This looks like it has been fixed. If this is not the case: please comment and I will reopen the same issue.

**Comment by JohnAZoidberg** [comment]
Why do you think it has been fixed? Can you point me to a commit?
Since the line I mentioned hasn't changed and I cannot find a commit with a message mentioning fonts, I assume it hasn't been fixed.

**Comment by Bowero** [comment]
I assumed it was because I had the same error and that disappeared after the changes that have been made over the latest dozens of commits. Could you please do `make clean`, `make` and then recompile `tetris.v`? If it still doesn't work, I will simply reopen the issue.
