### ISSUE TITLE
panic on array value re-assignment

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#5427]
**V version:** V 0.1.28 0338d41
**OS:** Ubuntu 20.04

**What did you do?**

mut arr := [1, 1]
arr[0] := 2

**What did you expect to see?**

`[1, 1]`

**What did you see instead?**

`V panic: get_type_symbol: invalid type (typ=0 idx=0). Compiler bug. This should never happen`

If the 2nd line is changed to `arr[0] = 2` the code works as expected.

**Comment by JalonSolov** [comment]
noctib reported this in https://discord.com/channels/592103645835821068/592114487759470596/723610118360662106 and I confirmed it.

**Comment by medvednikov** [comment]
It's because of using `:=`, will fix
