### ISSUE TITLE
Add some topic labels for V

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#543]
Many languages have their topic labels. For example, 
![image](https://user-images.githubusercontent.com/47302112/60057741-86803a00-96dd-11e9-97a2-dcfe1e0abdfc.png)
Labels may facilitate people finding and knowing V.

**Comment by AurelienFT** [comment]
https://github.com/vlang/v/issues/513 duplicate

**Comment by medvednikov** [comment]
Done. Can't add tag "V" :(

**Comment by ntilotta** [comment]
I can suggest to add those tags too: c, c-plus-plus, repl, go, golang, and rust.
V do not has a GC, but it keeps Go-ish syntax, and it could achieve some kind of Rust' safety.
Last but not least, the organization https://github.com/vlang should add those information:

Name: 
The V Programming Language (this should help SEO)

Description: 
Simple, fast, safe, compiled language for developing maintainable software. It supports translation from C and C++ (this to match the GitHub's topic: https://github.com/github/explore/pull/812)

Website: https://vlang.io

**Comment by ntilotta** [comment]
@medvednikov can I suggest to add those tags too?: c, c-plus-plus, repl, go, golang, and rust.
V do not has a GC, but it keeps Go-ish syntax, and it could achieve some kind of Rust' safety.
Last but not least, the organization https://github.com/vlang should has those information:

Name:
The V Programming Language

Description:
Simple, fast, safe, compiled language for developing maintainable software. It supports translation from C and C++ (this to match the GitHub's topic: github/explore#812)
Or same as the website: Simple, fast, safe, compiled language for developing maintainable software.

Website: https://vlang.io
