### ISSUE TITLE
calling outer function argument from lambda fails compilation with C error

### ISSUE THREAD

**Issue by zamfofex** [vlang/v#5430]
~~~V
fn f(g fn ()) {
	h := fn [g] () { g() }
	h()
}
~~~

**Comment by ArtemkaKun** [comment]
Hi @zamfofex,
the problem still exists, but can you please modify your example code, since the actual code requires a bit more stuff to make closures work.

```v
fn f(g fn ()) {
	h := fn [g] () {
		g()
	}

	h()
}
```
@spytheman the issue is still here, can you add a badge **Status: Confirmed** to it?

**Comment by medvednikov** [comment]
Fixed.
