### ISSUE TITLE
https://vlang.io/play websites's V-language examples are not working.

### ISSUE THREAD

**Issue by Aakash-Panchal27** [vlang/v#5441]
Just see the message in the image below:
![Screenshot (301)_LI](https://user-images.githubusercontent.com/51417248/85223118-f226e100-b3dd-11ea-9801-8469c94ff6c6.jpg)

**Comment by nedpals** [comment]
@Aakash-Panchal27 hello! Thanks for reporting it. Our new playground should be in this new URL: https://v-wasm.now.sh/

@medvednikov The playground page is still accessible. Can we redirect it to the new one?

**Comment by jeremydouglass** [comment]
This should perhaps not be closed until it is actually resolved!

Right now this main example -- https://vlang.io/play -- linked from the language homepage -- https://vlang.io/ -- is still broken. Is there a separate website repository where it should be reported?

**Comment by JalonSolov** [comment]
You may need to refresh your browser.  The only link to a playground on the homepage is at the top, and is named "Wasm Playground", which takes you to the new (fully functional) one.  It doesn't have all the examples from the old one, yet, but they will be added.

**Comment by jeremydouglass** [comment]
Steps to reproduce:

1. Go to https://vlang.io/

<img width="557" alt="Screen Shot 2020-06-23 at 6 07 45 PM" src="https://user-images.githubusercontent.com/798570/85484887-8fb81700-b57c-11ea-9d60-a6d82f07ad92.png">

2. click "Run" on the big hero box in the middle of the page.

3. Hit Run on https://vlang.io/play

4. "You just found a bug. V can't compile this program, but it should. Please create a GitHub issue."

**Comment by JalonSolov** [comment]
Ah, thank you.  This is a different spot, and it needs to be fixed to point to the new playground instead of the old one.

**Comment by medvednikov** [comment]
I've added a redirect.
