### ISSUE TITLE
I can't download it

### ISSUE THREAD

**Issue by vacanacom** [vlang/v#5446]
**V version:** 0.1.28
**OS:** 

**What did you do?**
I'm trying to download V. And I'm downloading it by following readme.md steps. Everything was going well, but when I wrote "make" (last step), it got an error.

**What did you expect to see?**
I was wanting to download it.
 
**What did you see instead?**
"Failed to compile - Create an issue at 'https://github.com/vlang'. Exiting from error."
![v-crash](https://user-images.githubusercontent.com/67207789/85233856-e6d4b500-b3df-11ea-8c0c-6d44d7e2c413.PNG)

**Comment by okureta** [comment]
Install GCC or MSVC. lol?

**Comment by vacanacom** [comment]
Thanks, i installed GCC.
