### ISSUE TITLE
Possible write_file() failure. Suggested catchable version.

### ISSUE THREAD

**Issue by scurty-labs** [vlang/v#5447]
`write_file()` could fail in some circumstances, it does handle it behind the scenes but doesn't give an option result so we could catch the resulting failure whether the path doesn't exist, or maybe a hardware issue. Instead of appending `?bool` to `write_file()` (Causing breakage) Could we add a `write_file_safe() ?bool` or something similar?

**Comment by medvednikov** [comment]
write_file() now returns an optional
