### ISSUE TITLE
v install does not function

### ISSUE THREAD

**Issue by gshields** [vlang/v#5448]
V 0.1.28 e65879d
OS is  w10 v 2004
 gcc.exe (x86_64-win32-sjlj-rev0, Built by MinGW-W64 project) 8.1.0
 
 v install ui
Error 10057 sending data to server (1)
Error performing handshake
Unhandled Exception 0xC0000005
print_backtrace_skipping_top_frames is not implemented

I also tried v install vrobot, vpkg install ui, vpkg install vrobot

**Comment by spytheman** [comment]
@gshields , please try running: `v -v install ui` and paste the results.

**Comment by gshields** [comment]
v -v install ui
launch_tool vexe        : E:\s-tools\v
launch_tool vroot       : E:\s-tools\v
launch_tool tool_args   : -v install ui
launch_tool tool_command: "E:\s-tools\v\cmd\tools\vpm.exe" -v install ui
launch_tool should_compile: false
launch_tool running tool command: "E:\s-tools\v\cmd\tools\vpm.exe" -v install ui ...
cli params: ['install', 'ui']
Retrieving module metadata from: https://vpm.best/jsmod/ui ...
Error 10057 sending data to server (1)
Error performing handshake
Unhandled Exception 0xC0000005

**Comment by spytheman** [comment]
@gshields , seems like it is a network problem to me. Could you try running this small v program too, with `v -cg -keepc run x.v`:
```v
import net.http
fn main(){
    x := http.get('https://vpm.best/jsmod/ui')?
    println(x)
}
```
Thanks in advance.

**Comment by gshields** [comment]
Delyan,
I copied the code provided and then ran the program with parameters, here
is the results.

v -cg -keepc run x.v
Error 10057 sending data to server (1)
Error performing handshake
Unhandled Exception 0xC0000005
print_backtrace_skipping_top_frames is not implemented

**Comment by gshields** [comment]
This was with:
 v version
V 0.1.28 cff2874
gcc --version
gcc.exe (x86_64-win32-sjlj-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Running on window 10 version 2004

**Comment by gshields** [comment]
I changed the program to
import net.http
fn main(){
    x := http.get('http://google.com')?
    println(x)
}

and ran it and got this:

 v run "e:\p-tools\v_src\x.v"
net.http.Response {
    text: '<!doctype html><html itemscope="" itemtype="
http://schema.org/WebPage" lang="en"><head><meta content="Search{
document.documentElement.addEventListener("submit",function(b){var
a;if(a=b.target){var c=a.getAttribute("data-submitfa;
var a=window.location,b=a.href.indexOf("#");if(0<=b){var
c=a.href.substring(b+1);/(^|&)q=/.test(c)&&-1==c.indexOf("#")&}
</style><style>body,td,a,p,.h{font-family:arial,sans-serif}body{margin:0;overflow-y:scroll}#gog{padding:3px
8px 0}td{li}
if
(!iesg){document.f&&document.f.q.focus();document.gbqf&&document.gbqf.q.focus();}
}
})();</script><div id="mngb"> <div id=gbar><nobr><b class=gb1>Search</b> <a
class=gb1 href="http://www.google.com/imghp}
else top.location='/doodles/';};})();</script><input
value="AINFCbYAAAAAXvJt9bqle-fSyUw36vgIPuleHhbzQ-78" name="iflsig";
setTimeout(function(){var b=document;var
a="SCRIPT";"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());a=
b.cr}
function _F_installCss(c){}
(function(){google.jl={dw:false,em:[],emw:false,lls:'default',pdt:0,snet:true,uwp:true};})();(function(){var
pmc='{\x22'
    headers: {'Date': 'Tue, 23 Jun 2020 20:02:45 GMT', 'Expires': '-1',
'Cache-Control': 'private, max-age=0', 'Content}
    lheaders: {'date': 'Tue, 23 Jun 2020 20:02:45 GMT', 'expires': '-1',
'cache-control': 'private, max-age=0', 'conten}
    cookies: {'1P_JAR': '2020-06-23-20; expires', 'NID': '204'}
    status_code: 200
}

Looks to me it is the https function that is not working, since http does
work
Hope this helps

George

**Comment by gshields** [comment]
Running with the program you gave me with http rather than https still
fails with Error 10057 sending data to server (1)
Error performing handshake
Unhandled Exception 0xC0000005
print_backtrace_skipping_top_frames is not implemented

Could http://vpm.best be blacklisted?

**Comment by gshields** [comment]
ping www.vpm.best

Pinging www.vpm.best [104.27.139.98] with 32 bytes of data:
Reply from 104.27.139.98: bytes=32 time=14ms TTL=56
Reply from 104.27.139.98: bytes=32 time=13ms TTL=56
Reply from 104.27.139.98: bytes=32 time=8ms TTL=56
Reply from 104.27.139.98: bytes=32 time=6ms TTL=56

**Comment by gshields** [comment]
tracert www.vpm.best

Tracing route to www.vpm.best [104.27.139.98]
over a maximum of 30 hops:

  1     3 ms     2 ms     2 ms  gateway.home [192.168.254.254]
  2     5 ms     6 ms     6 ms  fdr01.bvtn.or.nwestnet.net [50.46.181.56]
  3    12 ms     4 ms     4 ms  50.46.176.76
  4     4 ms     4 ms     4 ms  ae2---0.cor01.bvtn.or.nwestnet.net
[50.46.176.0]
  5     4 ms     4 ms     4 ms  ae0---0.cor02.bvtn.or.nwestnet.net
[50.46.176.5]
  6     6 ms     4 ms     4 ms  cr2-bvtnorxb-a-be100.bb.as20055.net
[204.194.220.5]
  7     4 ms     5 ms     5 ms  cr2-hlboornf-be11.bb.as20055.net
[107.191.236.28]
  8     9 ms     5 ms     6 ms  cloudflare.nwax.net [198.32.195.95]
  9     5 ms     4 ms     4 ms  104.27.139.98

**Comment by nedpals** [comment]
Just a guess but I guess it is something to do with OpenSSL?

**Comment by gshields** [comment]
Deleted old version and reinstalled, now a new error
on  v version
V 0.1.28 73da3c9
windows 10 2004
...............................................
 v install ui
Creating C:\Users\ghs\.vmodules/ ...
Error 10057 sending data to server (1)
Error performing handshake
Unhandled Exception 0xC0000005
C:/Users/ghs/AppData/Local/Temp/v/vpm.tmp.c:6204: at
print_backtrace_skipping_top_frames_tcc: Backtrace
C:/Users/ghs/AppData/Local/Temp/v/vpm.tmp.c:6165: by
print_backtrace_skipping_top_frames
C:/Users/ghs/AppData/Local/Temp/v/vpm.tmp.c:6227: by
unhandled_exception_handler
7ffb01da7f4c : by ???
7ffb01d75e16 : at ???: RUNTIME ERROR: invalid memory access

**Comment by Hareis** [comment]
Yes, I also encountered this problem (0.1.28)
