### ISSUE TITLE
Freeing strings crashes

### ISSUE THREAD

**Issue by Henrixounez** [vlang/v#545]
**V version:** 
V 0.1.0

**What did you do?**
Freed a string
```
fn main()
{
  var := 'test'
  var.free()
}
```

**What did you see ?**
It crashes : 
```
munmap_chunk(): invalid pointer
sh: line 1: 32059 Aborted                 (core dumped) ./test2 2>&1
munmap_chunk(): invalid pointer
ret not 0, exiting
```

**Comment by Henrixounez** [comment]
The problem here are **String Literals**, those strings in C can't be bothered in any way, they will prompt segmentation fault when modified and aborts when freed.
The **solution** here would be to do something like a **strdup** of this string with tos2 or else a new function.

The generated code looks like that :

```C
void v_string_free(string s)
{
	free(s.str);
}

string tos(byte* s, int len)
{
  if (isnil(s)) {
		v_panic(tos2("tos(): nil string"));
	};
 	return (string){ .str = s, .len = len};
}

string tos2(byte* s)
{
	if (isnil(s)) {
		v_panic(tos2("tos2: nil string"));
		return (string){.str = 0, .len = 0};
	};
	int len = strlen(s);
	string res = tos(s, len);
	return res;
}

int main(int argc, char** argv)
{
	init_consts();
	string var = tos2("one");
	v_string_free(var);
}
```

**Comment by Henrixounez** [comment]
One error case would be for example changing a string based on user input: it would always crash except if the user gives `concat` to the program

```C
import os

fn main() {
    mut str := 'hello'
    if os.args.len > 1 && os.args[1] == 'concat' {
        str += 'world'
    }
    println(str)
    str.free()
}
```

**Comment by AurelienFT** [comment]
I think there is two ways :

- Stay with this behavior as C and let the Dev manage his string allocatiob (on stack or heap) and he know when he need to free

- Make the behavior common and each time a string is declared in RO the `clone()` function is called

I think @medvednikov is the greatest person to choose this

**Comment by medvednikov** [comment]
Strings are now cleaned up at compilation. `string.free()` will be made private.
