### ISSUE TITLE
Printing a function's result makes a weird C error

### ISSUE THREAD

**Issue by TheBrainScrambler** [vlang/v#5453]
**V version:** V 0.1.28 d9dd967
**OS:** Arch Linux

**What did you do?**
`println(os.ls('.'))`
Compile that program with `v -cg program.v` (I added -cg for the logs, it also errors without it)

**What did you expect to see?**
I wanted the program to compile and work ?
 
**What did you see instead?**
http://0x0.st/i49x.log (that's just the C error, I also have the message which tells me that this is a C error, report it on Discord etc ...)

**Comment by LouisSchmieder** [comment]
Should panic like that but `os.ls` is an optional so you have to declare it in a variable first and then write it

**Comment by TheBrainScrambler** [comment]
"Should panic like that" Wait no ? And let me try to test it on a function that returns a normal value

**Comment by LouisSchmieder** [comment]
Sry my fault wanted to write shouldn't panic like this should write a V error
