### ISSUE TITLE
C error with function predecence

### ISSUE THREAD

**Issue by TheBrainScrambler** [vlang/v#5454]
**V version:** V 0.1.28 d9dd967
**OS:** Arch Linux

Yes I know I'm very active today lol. I know the title isn't very explicit but let me explain.
Let's consider this code: http://0x0.st/i49k.v. It totally works isn't it ? Yeah.
Now look at this one: http://0x0.st/i49n.v

And enjoy the C error spam at http://0x0.st/i49R.log ...

**Comment by nedpals** [comment]
Closed. The latest version of the V compiler will now throw an error: https://devbits.app/play/oNegscBjdcgK
