### ISSUE TITLE
`v fmt -w` is broken

### ISSUE THREAD

**Issue by sudo-nice** [vlang/v#5455]
**V version:** V 0.1.28 cf4dc93
**OS:** Linux

**What did you do?**
1. Created a file containing `fn main() { println('hello') }`
2. Ran `v fmt -w file.v`

**What did you expect to see?**
No output. The file should be reformatted in place.
 
**What did you see instead?**
The reformatted content was printed to stdout, the input file stayed intact.

**Comment by medvednikov** [comment]
It's temporarily disabled until @UweKrueger fixes the wrapping.

**Comment by sudo-nice** [comment]
I see, thank you.
