### ISSUE TITLE
string.replace with int parameter -> C error

### ISSUE THREAD

**Issue by TheBrainScrambler** [vlang/v#5456]
**V version:** V 0.1.28 5a6d440.d9dd967
**OS:** Arch Linux

**What did you do?**
http://0x0.st/i4pw.v

**What did you expect to see?**
Some V error saying that you can't pass an int as a string parameter
OR
Nothing, because V automatically converted the int to string
 
**What did you see instead?**
http://0x0.st/i4pv.log

**Comment by medvednikov** [comment]
Fixed in https://github.com/vlang/v/commit/cff287460878f8b69a0c857ad46a8925ae01af98
