### ISSUE TITLE
Sudo privilege elevation in V

### ISSUE THREAD

**Issue by TheBrainScrambler** [vlang/v#5457]
I actually need to copy a file from one directory to another. But the destination directory isn't writable by the user. Here I could do `os.system('sudo cp file /some/dir')` as a workaround, but it would be nice to have some pure V for this.
Problems I'm seeing:
- It only works for UNIX like platforms. Maybe implement also this for Windows by requesting admin right ?
- We either have to write a "sudo function" for each `os` function, or write some generic function which could be complicated

What do you think about that ?

**Comment by sudo-nice** [comment]
I think, V has nothing to do with `sudo`. It should be user's responsibility to call the compiled program with `sudo`.

**Comment by medvednikov** [comment]
I agree with @sudo-nice
