### ISSUE TITLE
Hardcoded path ~/code/v has been removed. V 0.1.1 can now be installed anywhere.

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#546]
This also fixes Azure CI.

**Comment by Chiiruno** [comment]
Yay!
Think you could release this as a hotfix release?
Thanks!

**Comment by medvednikov** [comment]
Of course, I'll release 0.1.1 within 15 minutes.

**Comment by medvednikov** [comment]
Done, 0.1.1 is live.

**Comment by Chiiruno** [comment]
Could we update the releases page and the v.c repo to 0.1.1 please?

**Comment by ntilotta** [comment]
In my case I've installed it under ~/.vlang, however V generates *.c files inside that directory, it could be nice to have those files generated inside ~/.vlang/cache or ~/.vlang/codegen to keep its directory clean.

**Comment by nathanKramer** [comment]
One thing I noticed is that there are still platform specific third party includes with this hardcoded path, e.g:

https://github.com/vlang/v/blob/353a6edb7c2389d5d10cb0b68ff9504dd54cf392/stbi/stbi.v#L10

When I was setting up the language (very cool by the way!) I had to manually copy some of these thirdparty libraries into my OS' includes directory to get things running, I didn't realise that there was supposed to be an automatic way for this to happen.

Perhaps `VROOT` can be configured as an env variable, and these includes can be rewritten as `#flag darwin -I$VROOT/thirdparty/stb_image`

**Comment by medvednikov** [comment]
This was fixed.
