### ISSUE TITLE
generate string method anon_str for type anon

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#5466]
**V version:** latest
**OS:** Ubuntu

**What did you do?**
```v
module main

fn main() {
	a := fn() string {
		return "test"
	}
	b := a()
	println(a)
}
```

**What did you expect to see?**
another error
 
**What did you see instead?**
```
main.v:7:2: warning: unused variable: `b` 
    5 |         return "test"
    6 |     }
    7 |     b := a()
      |     ^
    8 |     println(a)
    9 | }
cgen error: could not generate string method anon_65__18_str for type 'anon_65__18'
```

**Comment by JalonSolov** [comment]
The `unused` warning is correct.  The `cgen error` should be a regular v error.

**Comment by yuyi98** [comment]
If you're going to `println(b)`, that is correct.
I'm not sure what the issue is. is the need to print out the anonymous function correctly?

**Comment by Delta456** [comment]
I think he means it should not give this error `cgen error: could not generate string method anon_65__18_str for type 'anon_65__18'` as it has names like `anon_65__18_str ` and `anon_65__18 `. It should probably have better names so that the error message is more clear.

**Comment by JalonSolov** [comment]
Yes, that is what I meant.  Those names mean nothing to me if I don't comb through the C source code output by V.  It would be better if any names were the V names, not the mangled C names.

**Comment by Delta456** [comment]
It should probably behave like this https://play.golang.org/p/MpSIdyAeJVu

**Comment by JalonSolov** [comment]
@spytheman made some changes recently to improve this type of message.  See line 1274 in checker.v.

**Comment by danieldaeschle** [comment]
this works now!
