### ISSUE TITLE
run anon functions directly

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#5467]
**V version:** latest
**OS:** Ubuntu

**What did you do?**
```
fn main() {
    a := fn() string {
        return "test"
    }()
}
```

**What did you expect to see?**
a to be `test`
 
**What did you see instead?**
```
main.v:6:4: error: expr(): bad token `)` 
    4 |     a := fn() string {
    5 |         return "test"
    6 |     }()
      |       ^
    7 | }
```

**Comment by JalonSolov** [comment]
If you include the `string` missing from your example (but shown in your error output), change the `a` to `_` to avoid the `unused` warning, and remove the `()` after the closing `}` for the function, your example compiles clean.
```
fn main() {
        _ := fn() string {
                return "test"
        }
}
```

**Comment by danieldaeschle** [comment]
i want a to have the value `"test"`, running the function directly.

**Comment by danieldaeschle** [comment]
this works now.
