### ISSUE TITLE
generic type parsing from json leads to cgen error

### ISSUE THREAD

**Issue by amoyyy** [vlang/v#5475]
```
import json

struct Node {
    id int
}

fn parse<T>(data string) ?T{
    object := json.decode(T, data) or {
        return error('Failed to decode typeof(T)')
    }
    return object
}

fn main(){
    data := '{"a":1}'
    n := parse<Node>(data) or {
        panic("exit")
    }
    println(n)
}
```
When I try to complie the code above, it suggests **cgen error: json: T is not struct**
Is there an existing method to enable generic json parsing ? or could it be a feature request ?

**Comment by amoyyy** [comment]
By the way, user-declaring generic struct still compiles **lack body**
the link is https://github.com/vlang/v/issues/4337#issue-598001830
Can't wait to use the stable release, really appreciate you guys' work.

**Comment by nedpals** [comment]
@amoyyy Joe-C is working on generic structs. just keep an eye on the releases :smiley:

**Comment by amoyyy** [comment]
fine, patience makes perfect @nedpals

**Comment by nedpals** [comment]
Closed. Fixed in the latest V version: https://devbits.app/play/DkG29lGhtqN1
