### ISSUE TITLE
Array join function

### ISSUE THREAD

**Issue by Cyklan** [vlang/v#5478]
It would be great to have an `array.join(seperator)` function, like the one in [JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join) or in [C#](https://docs.microsoft.com/en-us/dotnet/api/system.string.join?view=netcore-3.1).

In my mind it would work somewhat like this:

```v
nums := [1, 2, 3]
println(nums.join("-")) // 1-2-3
```

**Comment by nedpals** [comment]
@Cyklan currently `join` only works on array of strings, so the workaround you have to do right now is to convert the values into strings and invoke `.join('-')`
```
>>> nums.map(it.str()).join('-')
1-2-3
>>> 
```

**Comment by medvednikov** [comment]
Yeah I think it should stay `nums.map(it.str()).join('-')`

It's easier and more explicit.

**Comment by nedpals** [comment]
Closed. `[]int.join` won't be implemented.

**Comment by vsyrovat** [comment]
`join` method is not documented here: https://github.com/vlang/v/blob/master/doc/docs.md#array-methods
