### ISSUE TITLE
0.1.1 v.c runtime error on windows 7 cmd

### ISSUE THREAD

**Issue by l1t1** [vlang/v#548]
i build the 0.1.1 v.c  with mingw, but it has runtime error 
**V version:** 0.11
**OS:**  windows 7 
**C compiler version:** 
MinGW-W64 project) 8.1.0
**What did you do?**
i saved https://vlang.io/v.c to d:\ (suggest add a version comment in the file)
I modified the getline to fgets in the file
(int nr_chars = getline(&/*vvar*/ buf, &/*vvar*/ max, stdin);
to int nr_chars = fgets(/*vvar*/ buf, /*vvar*/ max, stdin); // it seems both & are wrong type, so i delete them)
, and run following code in cmd
gcc -w -Dwindows -o v.exe v.c
it buld v.exe without problem, and the v.exe show following msg
D:\>v
V 0.1.1
Use Ctrl-D to exit
For now you have to use println() to print values, this will be fixed soon

>>> println('Hello!')

**What did you expect to see?**
it print Hello in the screen
 
**What did you see instead?**
when i run println('Hello!') in it, it hangs and abort

**Comment by l1t1** [comment]
and want to use v.exe to copile hw.c
```
// Copyright (c) 2019 Alexander Medvednikov. All rights reserved.
// Use of this source code is governed by an MIT license
// that can be found in the LICENSE file.

println('Hello!')
```
it shows
```
D:\>v hw.v
Looks like you are running V for the first time.
Please do it from "v/compiler" directory.
```
I change the directory, the same problem is there
```
D:\>cd D:\v\compiler

D:\v\compiler>d:\v d:\hw.v
Looks like you are running V for the first time.
Please do it from "v/compiler" directory.
```

**Comment by shawnye** [comment]
Me too.

I  copy <code>getline </code> function from [here](https://stackoverflow.com/questions/27369580/codeblocks-and-c-undefined-reference-to-getline)

and compile ok.

But when run `vc -o v .` under dir `E:\WORK\DEV\v\v\compiler` , error occurred:

Looks like you are running V for the first time.
Please do it from "v/compiler" directory.

**Comment by l1t1** [comment]
an manual of getline and gets
http://www.gnu.org/software/libc/manual/html_node/Line-Input.html

**Comment by shawnye** [comment]
Workaround:

copy all dir except compiler into `v\compiler`  : builtin, os, time ,etc
then you can run `vc -o v .` under dir  `v\compiler`

**Comment by l1t1** [comment]
i used the getline @shawnye supply, and it donot hang now,  but still output following msg
```
D:\>vc
V 0.1.1
Use Ctrl-D to exit
For now you have to use println() to print values, this will be fixed soon

>>> 1
>>> 3
>>> println("hello")
Looks like you are running V for the first time.
Please do it from "v/compiler" directory.
```

**Comment by l1t1** [comment]
@shawnye i did as you say, but stll ..
```
D:\v\compiler>vc -o v .
Looks like you are running V for the first time.
Setting VROOT to "D:\v\compiler".

D:\v\compiler>set VROOT=D:\v\compiler

D:\v\compiler>vc -o v .
Looks like you are running V for the first time.
Setting VROOT to "D:\v\compiler".
```

**Comment by shawnye** [comment]
You can search `v/compiler` in source v.c,  and found the workaround.

**Comment by medvednikov** [comment]
This was fixed a long time ago.
