### ISSUE TITLE
Inconsistent fn args behaviour

### ISSUE THREAD

**Issue by Tarang11** [vlang/v#5486]
**V version:** latest
**OS:** Mac OS

**What did you do?**
fn test(param) {}

fn main() {
	test(0)
}

**What did you expect to see?**
error: unexpected `{`, expecting `,` 
    1 | fn test(param1, param2) {}
      |                         ^
    2 | 
    3 | fn main() {
 
**What did you see instead?**
error: unknown type `param` 
    1 | fn test(param) {}
      | ~~~~~~~~~~~~~~
    2 | 
    3 | fn main() {
error: cannot use type `any_int` as type `param` in argument 1 to `test` 
    2 | 
    3 | fn main() {
    4 |     test(0)
      |     ~~~~~~~
    5 | }

**Comment by spytheman** [comment]
Fixed in b6e6cde
