### ISSUE TITLE
v fmt stomps on orm syntax

### ISSUE THREAD

**Issue by fuzzy** [vlang/v#5492]
**V version:** 
0.1.28 67d9d94
**OS:** 
FreeBSD 12-STABLE

**What did you do?**
made a file: vorm.v
```
module main

import sqlite

struct User {
pub mut:
	id    int
	fname string
	lname string
}

fn main() {
	mut db := sqlite.connect('./test.db') or {
		panic('$err')
	}
	cnt := sql orm { select count from User }
	println('count=$cnt')
}
```
v fmt -diff vorm.v

**What did you expect to see?**
my orm sql statements would be formatted
 
**What did you see instead?**
my orm sql statements were simply removed

```
--- /usr/home/fuzzy/work/devel/vlang/replicate/vorm.v	2020-06-24 18:44:11.731916000 -0700
+++ /home/fuzzy/.cache/vfmt_vorm.v	2020-06-24 18:46:47.471533000 -0700
@@ -14,5 +14,5 @@ fn main() {
 		panic('$err')
 	}
-	cnt := sql orm { select count from User }
+	cnt := 
 	println('count=$cnt')
 }
```

**Comment by fuzzy** [comment]
V 0.1.28 bdecbc1 is confirmed to work the same

**Comment by LouisSchmieder** [comment]
Is fixed now ```v
module main

import sqlite

struct User {
pub mut:
        id    int
        fname string
        lname string
}

fn main() {
        mut db := sqlite.connect('./test.db') or {
                panic('$err')
        }
        cnt := sql orm {
                select count from User 
        }
        println('count=$cnt')
}
``` got this after fmt
