### ISSUE TITLE
vweb, unable to get text and json responses

### ISSUE THREAD

**Issue by smartiniOnGitHub** [vlang/v#5498]
**V version:** Latest, from sources
**OS:** Ubuntu Linux 20.04 LTS; the same apply even in Windows 10

**What did you do?**
Let vweb reply with a text responses; even for json responses is the same.

**What did you expect to see?**
Response data.
 
**What did you see instead?**
Nothing, page empty and the following error: ERR_EMPTY_RESPONSE

Note that this is visible in `vweb_example.v` and in any other example.

Tell me if you need more info. Thanks

**Comment by smartiniOnGitHub** [comment]
In `vweb_example`, I can do a PR to perform a small update on the `index.html` to clarify content and add a section with links to exposed routes (to simplify user tests), tell me ...

Last, to test calls to exposed URLs (in general), there is some facility in v test framework ?
In other frameworks I've been able to let the test run the server application, run tests on it and then stop the server.

**Comment by medvednikov** [comment]
> In other frameworks I've been able to let the test run the server application, run tests on it and then stop the server.

This is planned, not possible yet

**Comment by medvednikov** [comment]
Fixed.
`vweb_example.v` works now

**Comment by smartiniOnGitHub** [comment]
Perfect, thank you very much. Bye


Il sab 27 giu 2020, 13:57 Alexander Medvednikov <notifications@github.com>
ha scritto:
