### ISSUE TITLE
modules in subdirs cannot be imported

### ISSUE THREAD

**Issue by amoyyy** [vlang/v#5499]
**V version:**  0.1.28 a8b0dfb
**OS:**  ubuntu

**What did you do?**
I tried to compile a project in a directory like this:
```
     mymodule
          |__submodule1
               |__submodule1.v
          |__submodule2
               |__submodule2.v
          |__mymodule.v      
     test.v
```
in **mymodule.v**, submodules are imported :
```
module mymodule
import submodule1
import submodule2

pub fn test(){
    submodule1.test()
    submodule2.test()
} 
```
and **test.v** defines the main entry and call the **mymodule.test()**

**What did you expect to see?**
test() called correctly 
 
**What did you see instead?**
A builder error suggests that cannot import module "submodule1" (not found)

**Comment by spaceface777** [comment]
> ```
> import submodule1
> import submodule2
> ```

Shouldn't it be this instead?
```
import mymodule.submodule1
import mymodule.submodule2
       ~~~~~~~~
```

**Comment by JalonSolov** [comment]
Right.  In general, it is "import <module>.<submodule>" and imports always start at the base of the modules even if you're inside the module tree.  At least that is my understanding.

**Comment by amoyyy** [comment]
@spaceface777 I see, that solves the problem. In my understanding, when compiling **mymodule.v** the root dir is changed which is not the case.

**Comment by spaceface777** [comment]
No, @JalonSolov is right, module lookup starts at the top level (or wherever you have a `v.mod`)
