### ISSUE TITLE
Add PQclear to vlib/pg.v

### ISSUE THREAD

**Issue by jhuntos** [vlang/v#5503]
While stress testing an alteret picoev.v with Pg support I found a memory leek, fixed by adding this to vlib/pg.v 

`fn C.PQclear(voidptr) voidptr`

fn res_to_rows(res voidptr) []Row {  
~~
        }
        `C.PQclear(res)`
        return rows  
}

**Comment by medvednikov** [comment]
Can you submit a PR?

**Comment by jhuntos** [comment]
Submitted a PR
