### ISSUE TITLE
online vdoc: deprecated functions are not marked as deprecated

### ISSUE THREAD

**Issue by serkonda7** [vlang/v#5513]
**V version:** online vdoc

**What did you do?**
Open the vlib online docs and look after rmdir_recursive

**What did you expect to see?**
Some mark like `[deprecated]` as it is in the source code too.
 
**What did you see instead?**
![Screenshot_20200626_143339](https://user-images.githubusercontent.com/40118727/85857401-14dc3f80-b7ba-11ea-9b42-12eda3ad7d12.png)

**Comment by Serkonda** [comment]
See #5514
