### ISSUE TITLE
online vdoc: ? return type is not shown

### ISSUE THREAD

**Issue by serkonda7** [vlang/v#5514]
**V version:** online module docs

**What did you expect to see?**
Return type of `?` for functions like `os.rm`.
 
**What did you see instead?**
No return type is specified.

**Comment by nedpals** [comment]
The latest version of vdocs supports this. It's just that the modules hasn't been updated for a while.

**Comment by Serkonda** [comment]
I already read in Discord that the online docs are generated manually at the moment.
