### ISSUE TITLE
Cannot import modules from authors with `-` in their name

### ISSUE THREAD

**Issue by Serkonda** [vlang/v#5515]
**V version:** V 0.1.28 f703ddf
**OS:** Manjaro Linux

**What did you do?**
Installed vpm module `etienne-napoleone.chalk`
```v
// test.v

import etienne-napoleone.chalk as chalk
```

**What did you expect to see?**
No error and a usable module.
 
**What did you see instead?**
```
test.v:1:15: error: module syntax error, please use `x.y.z` 
    1 | import etienne-napoleone.chalk
      |
```

**Possible solutions:**
1. Handle packages similar to vpkg. It only works with the package name and ignores the author.
2. Update vpm to allow `-` in the author name.
3. Replace any `-` with `_` for the folder. Then do `import etienne_napoleone.chalk`

**Comment by yuyi98** [comment]
Is it possible to use `_` instead of `-`? 

```v
import etienne_napoleone.chalk
```

**Comment by Serkonda** [comment]
It gives no syntax error, but vpm would have to be updated to replace `-` with `_` for the folder.
