### ISSUE TITLE
Printing u64/i64 using `println` broken; only prints equivalent of trailing 32 bits

### ISSUE THREAD

**Issue by Smartyue** [vlang/v#552]
```rust
fn main() {
    sum := u64(4294967296)
    println(sum) // 0
    println(int(sum)) // 0
    println(i64(sum)) //4294967296
}
```

**Comment by LouCle** [comment]
What is the error here?

**Comment by Kriyszig** [comment]
I guess the error here is `u64` in V should work like `unsigned long long int` - 8 bytes in C. The upper limit of which is 
`18,446,744,073,709,551,615` but this behaves like `unsigned int` - 4 bytes. It overflows after `4294967295` and hence it results to 0 for `4294967296` as the last 32 bits are all 0.

**Comment by LouCle** [comment]
Oh crap, yes I see.

**Comment by LouCle** [comment]
It seems from the transpiled C that it's by default typecasted to `int` unless specified otherwise. This is why `sum` and `int(sum)` overflows. The other two functions still work as intended.

**Comment by LouCle** [comment]
This raises the question though @medvednikov, should we have a general purpose itoa function for this?

**Comment by gaoxinge** [comment]
The code is the same as the c code:

```c
#include <stdio.h>
#include <stdint.h>
#include <limits.h>
#include <inttypes.h>

int main() {
    uint64_t sum = 4294967296;
    printf("%d\n", sum);   // 0
    printf("%d\n", (int) sum);  // 0
    printf("%" PRId64 "\n", (int64_t) sum);  // 4294967296
    // printf("%d\n", INT_MAX);
    return 0;
}
```

**Comment by medvednikov** [comment]
Fixed.
