### ISSUE TITLE
win32,compile error

### ISSUE THREAD

**Issue by fqbqrr** [vlang/v#5523]
**V version:** 
latest
**OS:** 
win32
**What did you do?**
make.bat

**What did you expect to see?**

 
**What did you see instead?**
“函数”: 无法从“VectoredExceptionHandler”转换为“PVECTORED_EXCEPTION_HANDLER”

compile error

**Comment by JalonSolov** [comment]
Did you download the latest release archive, or use `git clone` to get the sources?

**Comment by Ekopalypse** [comment]
see https://discord.com/channels/592103645835821068/592106336838352923/758819164382691369.

u32 needs to be replaced to int [here](https://github.com/vlang/v/blob/master/vlib/builtin/builtin_windows.c.v#L202)  and [here](https://github.com/vlang/v/blob/master/vlib/builtin/builtin_windows.c.v#L210)

definition from winnt.h
~~~c
typedef LONG (NTAPI *PVECTORED_EXCEPTION_HANDLER)(
    struct _EXCEPTION_POINTERS *ExceptionInfo
    );
~~~

**Comment by Ekopalypse** [comment]
This seems to happen only if one build v with GCC but other executable with MSVC.
Once v is build by running make.bat -msvc this error doesn't show up anymore.
