### ISSUE TITLE
Rare assert error with string memory pointers for struct arrays

### ISSUE THREAD

**Issue by serkonda7** [vlang/v#5529]
**V version:** V 0.1.28 58763ff
**OS:** Manajro Linux

**What did you do?**
```v
// some_test.v

struct MyStruct {
	val1 string
	val2 string
}

fn test_a() {
	mut a := ''
	a += 'a'
	a += '1'

	orig := [
		MyStruct{
			val1: 'fixed'
			val2: a
		}
	]

    assert orig == [
		MyStruct{
			val1: 'fixed'
			val2: 'a1'
		}
	]
}
```

**What did you expect to see?**
Both sides are identical so the test should pass.
 

**What did you see instead?**
But I get this error:
```
Source  : orig == [unhandled expr type v.ast.ArrayInit]
   left value: orig = [MyStruct {
    val1: 'fixed'
    val2: 'a1'
}]
  right value: [unhandled expr type v.ast.ArrayInit] = [MyStruct {
    val1: 'fixed'
    val2: 'a1'
}]
```

**The Problem:** (thanks @spytheman)
![Memory](https://url4e.com/gyazo/images/bd7a8906.png)
> Note: the code above slightly differs from the image because I minified it more to the problems core.

The memory is compared directly but the `.str` pointers of the string structures are different.
The error happens because `val2` is computed and not a static string.

> Note 2: for the full conversation see the [Discord](https://discordapp.com/channels/592103645835821068/592294828432424960/726388607585353788) from here

**Workaround:**
Cast both sides of the assert to a string:
```v
assert orig.str() == [
	MyStruct{
		val1: 'fixed'
		val2: 'a1'
	}
].str()
```

**Comment by danieldaeschle** [comment]
works now
