### ISSUE TITLE
error: no known default format for type interface

### ISSUE THREAD

**Issue by trufae** [vlang/v#5540]
**V version:** V 0.1.28 288ea18
**OS:** macOS 10.15

**What did you do?**

```
$ cat q.v
interface Foo {
	foo()
}

struct Bar {

}

fn (b Bar)foo() {
	println('$b')
}

fn get_foo() Foo {
	return Bar{}
}

fn main() {
	a := get_foo()
	assert('$a' == 'Foo')
}
```

**What did you expect to see?**

working program, not asserting
 
**What did you see instead?**

```
q.v:19:11: error: no known default format for type `Foo`
   17 | fn main() {
   18 |     a := get_foo()
   19 |     assert('$a' == 'Foo')
      |              ^
   20 | }
```

I opened a PR but didnt managed to fix the test see:
* https://github.com/vlang/v/pull/5182

**Comment by nedpals** [comment]
Closed. Fixed in the latest version of V: https://devbits.app/play/kZy7uqESKYp0 
(Just changed the string text on the right hand side since converting interface to string has a different output)
