### ISSUE TITLE
net.http response header keys are not case insensitive!

### ISSUE THREAD

**Issue by blacklyger** [vlang/v#5541]
An improvement would be to make the http response header "dict" keys case insensitive.

**Comment by LouisSchmieder** [comment]
We already have case insensitive response headers https://github.com/vlang/v/blob/master/vlib/net/http/http.v#L45

**Comment by blacklyger** [comment]
That's not what I mean by case insensitivity. Currently there are two header "fields/dicts". What I mean is that you (only) have one headers "field/dict" and (e.g.) "Content-Type" and "content-type" or "Content-type" and "content-Type" all work. Regardless of how your input is, it works (considering the pattern, of course). Why is there a second headers (lheaders, in this case) field, only with lowercase keys? The keys in headers and lheaders are the same, aren't they? To my mind that does not make sense and it seems unnecessary to me. That's the reason I suggest only one headers field with case insensitive keys, so you do not need a second one with the same keys!

**Comment by LouisSchmieder** [comment]
https://github.com/vlang/v/pull/5265 we had discussed it here

**Comment by mcastorina** [comment]
`net.http` now has a custom `Header` struct that allows for both case-insensitive (default) and case-sensitive querying (see `v doc net.http Header` for more info).

This issue can be closed.
