### ISSUE TITLE
vsh: os is not global

### ISSUE THREAD

**Issue by Serkonda** [vlang/v#5552]
**V version:** V 0.1.28 219ecd1
**OS:** Manjaro

**What did you do?**
Run the following script after making it executable with chmod.
```v
#!/usr/local/bin/v run

files := ls('.')  or { panic(err) }
println(files)
```

**What did you expect to see?**
See all files printed.
 
**What did you see instead?**
```
./install.vsh:3:10: error: unknown function: ls 
    1 | #!/usr/local/bin/v run
    2 | 
    3 | files := ls('.')
      |          ~~~~~~~
    4 | println(files)
```

It only works if I manually import `os` and call `os.ls()`.

**Comment by Serkonda** [comment]
After a [small converstion on Discord](https://discordapp.com/channels/592103645835821068/592106336838352923/727050775590731787)I would suggest removing it from website, docs first and later from v.v too.
`vsh` has no real benefits and instead just complicates the code base.

If anyone misses the functionality they could do the same with plain v.

@medvednikov your opinion?

**Comment by ElienayNathan** [comment]
I think you need to type "os.ls". I did it with mine and it worked.
![issue-answer1](https://user-images.githubusercontent.com/52963443/86520229-6e76e680-be18-11ea-8513-1fe8a38dd4d0.PNG)
![issue-answer1-2](https://user-images.githubusercontent.com/52963443/86520230-6f0f7d00-be18-11ea-831b-998bcb0c7a15.PNG)

**Comment by JalonSolov** [comment]
He reported that that does work at the end of his initial message.

From the documentation:
```
Use the .vsh file extension. It will make all functions in the os module global (so that you can use ls() instead of os.ls(), for example).
```

I confirm this is not working as documented.

**Comment by medvednikov** [comment]
Fixed.
