### ISSUE TITLE
make install target in compiler/Makefile

### ISSUE THREAD

**Issue by equal-l2** [vlang/v#557]
`make install` target would ease package maintainers.
(I'm currently working on vlang formula on Homebrew btw)

**Comment by Chamberlain91** [comment]
It probably wouldn't take much
```make
install:
    ln -s ./compiler/v /usr/local/bin/v
    ln -s ./compiler/vfmt /usr/local/bin/vfmt
    # ... whatever else
```
Or something like that for the current way its distributed.
Am I missing something obvious?

**Comment by equal-l2** [comment]
`make install` should copy the executables and dependencies, instead of symlinking.
