### ISSUE TITLE
OPENSSL fails on windows 10 ver. 2004

### ISSUE THREAD

**Issue by gshields** [vlang/v#5574]
On windows 10 ver. 2004
installed v with tcc
v version is V 0.1.28 73da3c9
expected to compiled nbody and run in about 6 sec (which has been the same since v1.26)
Both normal and -prod take HUGE amounts it time (I gave up after 40 seconds)

Tried again with
v -v install nbody.exe
launch_tool vexe        : E:\p-tools\v
launch_tool vroot       : E:\p-tools\v
launch_tool tool_args   : -v install nbody.exe
launch_tool tool_command: "E:\p-tools\v\cmd\tools\vpm.exe" -v install nbody.exe
launch_tool should_compile: true
Compiling vpm with: ""E:\p-tools\v\v.exe" "E:\p-tools\v\cmd\tools\vpm.v""
launch_tool running tool command: "E:\p-tools\v\cmd\tools\vpm.exe" -v install nbody.exe ...
cli params: ['install', 'nbody.exe']
Retrieving module metadata from: https://vpm.best/jsmod/nbody.exe ...
**Error 10057 sending data to server (1)**
Error performing handshake
Unhandled Exception 0xC0000005
C:/Users/ghs/AppData/Local/Temp/v/vpm.tmp.c:6204: at print_backtrace_skipping_top_frames_tcc: Backtrace
C:/Users/ghs/AppData/Local/Temp/v/vpm.tmp.c:6165: by print_backtrace_skipping_top_frames
C:/Users/ghs/AppData/Local/Temp/v/vpm.tmp.c:6227: by unhandled_exception_handler
7ffb01da7f4c : by ???
7ffb01d75e16 : at ???: RUNTIME ERROR: invalid memory access
....................................
This looks related to the open ssl problem I reported 6 days ago with v install ui
There is no networking code in the source file only "import math"
question 1. Is the standard library calling  https://github.com/lobotony/v-lmath?
if so this is a problem for those trying to run programs off the net.

question 2. Why is this binary phoning home to https://vpm.best/jsmod/nbody.exe?
If this is logging to a server for install count this could be a big problem for those behind corp firewalls.

question 3. How can I disable the phone home feature and have a binary that only references source on my machine?

**Comment by Zymlex** [comment]
https://github.com/vlang/vpm/issues/9
https://github.com/vlang/ui/issues/164

**Comment by vitalyster** [comment]
1. 2. 3. `vpm` tool is a package manager which phoning home, it is not a part of standard library, you can download and install packages without it

**Comment by gshields** [comment]
vpm <https://github.com/yue-best-practices/vpm> - The V language package
management tool written in V, so that is not correct.

if you meant to say vpkg
 E:\p-tools\v_src\vpkg\vpkg.exe install ui
Installing packages
0 package was installed successfully.
