### ISSUE TITLE
The formatter strips <T> from a generic struct

### ISSUE THREAD

**Issue by sudo-nice** [vlang/v#5576]
**V version:** V 0.1.28 a3086a2
**OS:** Linux

**What did you do?**
`v fmt -diff main.v`, where
```v
//main.v
struct Zone<T> {
  val T
}
```

**What did you expect to see?**
Nothing.

**What did you see instead?**
```
-struct Zone<T> {
+struct Zone {
```

**Comment by Delta456** [comment]
It is not implemented yet.

**Comment by serkonda7** [comment]
Works fine in newer versions of V.
