### ISSUE TITLE
cannot swap struct members through 'a, b = b, a'

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5594]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
```V
struct Foo {
mut:
	a int
	b int
}

fn main() {
	mut x := Foo{a:1, b:2}
	x.a, x.b = x.b, x.a
	println(x)
}
```

**What did you expect to see?**
Foo {a:2, b:1}
 
**What did you see instead?**
Foo {a:2, b:2}

**Comment by medvednikov** [comment]
Should be fixed now.

**Comment by SleepyRoy** [comment]
@medvednikov Just tried and it's not fixed.

**Comment by medvednikov** [comment]
Right, it was explicitly for IndexExpr only.
