### ISSUE TITLE
Automatic builtin imports in REPL

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#5597]
It's really useful being able to just
```
v
>>> time.now().add_days(100)
2020-10-09 11:25:53
```

without `import time`

Basic modules should either be pre-imported by REPL, or imported on use.

**Comment by Glitchfix** [comment]
@medvednikov 
I was just thinking if it is a good idea to consider this people using custom package with the same name might find it conflicting. I would like to know your views.

**Comment by medvednikov** [comment]
Well people shouldn't use module names that conflict with stdlib, like `time` or `os` anyway @Glitchfix

**Comment by Delta456** [comment]
Do we want all built-in modules to be automatically imported?

**Comment by elimisteve** [comment]
Wow, fixed in https://github.com/vlang/v/pull/5643 ! Hadn't realized that. Thanks, @yuyi98 :smiley: 

Would be easy to add more to that array of pre-imported modules...
