### ISSUE TITLE
`compare_strings` with non-reference strings gives c error

### ISSUE THREAD

**Issue by m-242** [vlang/v#5598]
**V version:** 
**OS:** Ubuntu 20.04 LTS

**What did you do?**
While trying to compare two strings I created a `test_compare.v` as following:
```v
module main

fn main() {
	println(compare_strings("a", "a"))
}
```
and then ran the command `v run test_compare.v`.

**What did you expect to see?**
`0`
 
**What did you see instead?**
```
==================
/home/m242/.cache/v/test_compare.tmp.c: In function ‘main__main’:
/home/m242/.cache/v/test_compare.tmp.c:7604:43: error: lvalue required as unary ‘&’ operand
 7604 |  println(int_str(compare_strings((voidptr)&/*qq*/tos_lit("a"), (voidptr)&/*qq*/tos_lit("a"))));
      |                                           ^
/home/m242/.cache/v/test_compare.tmp.c:7604:73: error: lvalue required as unary ‘&’ operand
 7604 |  println(int_str(compare_strings((voidptr)&/*qq*/tos_lit("a"), (voidptr)&/*qq*/tos_lit("a"))));
      |                                                                         ^
/home/m242/.cache/v/test_compare.tmp.c: In function ‘_vinit’:
/home/m242/.cache/v/test_compare.tmp.c:7629:38: warning: integer constant is so large that it is unsigned
 7629 |  _const_math__bits__max_u64 = ((u64)(18446744073709551615));
      |                                      ^~~~~~~~~~~~~~~~~~~~
/home/m242/.cache/v/test_compare.tmp.c:7650:407: warning: integer constant is so large that it is unsigned
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by m-242** [comment]
BTW, the documentation link to this function sources points to [line 933](https://github.com/vlang/v/blob/master/vlib/builtin/string.v#L933), when it should be pointing to [line 944](https://github.com/vlang/v/blob/7386adfc99e44e714012c7d9022dfc70a6561573/vlib/builtin/string.v#L944)

**Comment by JalonSolov** [comment]
I think this definitely needs both some documentation, as well as a "cleaner" error message if used in this fashion.

The `compare_strings` method appears to be meant to be used as a comparator on string array elements, such as using `array.sort_with_compare(compare_strings)`, rather than as a plain string comparator.

For plain strings, the simpler `=`, `<`, `>`, `<=`, etc. operators work as expected.

**Comment by serkonda7** [comment]
This code works:
```v
fn main() {
    a := 'a'
    b := 'a'
    println(compare_strings(&a, &b))
}
```
`compare_strings` works with string references and not direct values. But it shouldn't give a c error.

**Comment by shadowninja55** [comment]
compiles on latest v and outputs 0.
