### ISSUE TITLE
Add -static support

### ISSUE THREAD

**Issue by trufae** [vlang/v#5601]
**V version:** V 0.1.28 78e1127
**OS:** macOS 10.15

**What did you do?**

v -static a.v

**What did you expect to see?**

a statically linked executable 

**What did you see instead?**

a dynamically linked executable

**Comment by ryan-willis** [comment]
FWIW: https://developer.apple.com/library/archive/qa/qa1118/_index.html

**Comment by medvednikov** [comment]
Can be done with a cflag.
