### ISSUE TITLE
`import const` is position related

### ISSUE THREAD

**Issue by kitech** [vlang/v#563]
**V version:**  0.1.1
**OS:** linux
**C compiler version:**  gcc

**What did you do?**
import const (
   CURLOPT_VERBOSE
)

**What did you expect to see?**
Want put on file bottom.
 
**What did you see instead?**

panic: curl.v:23
expected `=` but got `CURLOPT_SSL_VERIFYPEER`

But put file top is fine.

**Comment by Hamzantal** [comment]
Are consts able to he defined ar the bottom?

**Comment by kitech** [comment]
Thinking functions are not order related, it's possible but not sure, depends on language spec and also acceptable if not support.

**Comment by Ivo-Balbaert** [comment]
import const is not conform the V syntax.
consts can be defined at the end of a program, if you choose to do so:

fn main() {
println(pi)
println(inch_to_cm )
println(greek_greeting)
println(asian_greeting)
println(input)
} 

const (
	pi = 3.1415
  inch_to_cm  = 2.54
	greek_greeting = 'Καλημέρα κόσμε' 
	asian_greeting = 'こんにちは 世界'
	input = '{ "name": "Frodo", "age": 25 }'
) 

Output:
3.141500
2.540000
Καλημέρα κόσμε
こんにちは 世界
{ "name": "Frodo", "age": 25 }
