### ISSUE TITLE
V release based compilation should be accompanied by a corresponding vc release as well

### ISSUE THREAD

**Issue by sumeetchhetri** [vlang/v#5635]
This is a huge problem when a new release is made, the earlier releases still pull the latest vc codebase for compilation of v code. The vc change in most cases ends up breaking earlier releases. So if i go and checkout a previous version it may/may not compile as the vc code is latest master. In order to fix this, the vc repository should also follow a release cycle as v does.

**Comment by medvednikov** [comment]
This can now be done with the `oldv` tool.
