### ISSUE TITLE
'println(bool)' leads to unexpected REPL exit

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5636]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
In REPL run
```V
println(true)
```

**What did you expect to see?**
print true and then wait for next line 
 
**What did you see instead?**
print true but then exit

**Comment by yuyi98** [comment]
No problem.

```v
C:\Users\yuyi9>v
For usage information, quit V REPL using `exit` and use `v help`
V 0.1.28 b7175b5
Use Ctrl-C or `exit` to exit
>>> println(true)
true
>>>
```

**Comment by SleepyRoy** [comment]
@yuyi98 Thanks. Just tried latest and it's OK.
