### ISSUE TITLE
cannot insert elements to array inside function

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5649]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
```V
fn foo(mut a []int) {
	a << 3
}

fn main() {
	mut a := [1,2]
	foo(mut a)
	println(a)
}
```

**What did you expect to see?**
[1,2,3]
 
**What did you see instead?**
[1,2]

**Comment by bashery** [comment]
same problem in linux
