### ISSUE TITLE
fatal error: 'glad.h' file not found

### ISSUE THREAD

**Issue by nzlov** [vlang/v#565]
**V version:** 
```
V 0.1.1
```
**OS:** 
```
macos 10.14.3
```
**C compiler version:** 
```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
**What did you do?**
```
$ cd examples/tetris
$ v run  tetris.v
```

**What did you expect to see?**
```
running
 ```
**What did you see instead?**
```
/Users/nzlov//.vlang//tetris.c:76:10: fatal error: 'glad.h' file not found
#include "glad.h"
         ^~~~~~~~
1 error generated.
V panic: clang error
```

**Comment by nathanKramer** [comment]
I had this issue too.

Something like this will fix it: https://github.com/vlang/v/pull/559 

If you want to get things working in the short term, put the libraries that are in the thirdparty folder in your includes directory.

**Comment by wkcn** [comment]
It seems that v compiler doesn't find the third-party heaers.
A simple and temporary solution:
Enter `v/examples/tetris` directory
```
cp ../../thirdparty/glad/glad.h ./
cp ../../thirdparty/glad/glad.c ./
cp ../../thirdparty/stb_image/stb_image.h ./

```

**Comment by nzlov** [comment]
@nathanKramer @wkcn Thanks.
