### ISSUE TITLE
got an error: Terminated by signal 10 (unknown)

### ISSUE THREAD

**Issue by lydiandy** [vlang/v#5653]
**V version:** 
latest:V 0.1.28 9569655

**OS:** 
macos

**What did you do?**
here is the sample code:
```
module main

struct Table {
pub mut:
	name string
}

fn (mut t Table) rename() {
	t.name = 'abc'
}

// type MyFn = fn (mut t Table) //with mut,output is right:'abc'

type MyFn = fn (t Table) // without mut,output: Terminated by signal 10 (unknown)

fn sum(myfn MyFn) {
	mut t := Table{}
	myfn(t)
	// myfn(mut t)
}

fn main() {
	sum(fn (mut t Table) {
		t.rename()
		println(t.name)
	})
}
```

**What did you expect to see?**
reports an error:Terminated by signal 10 (unknown)
**What did you see instead?**
the output content is very strange,event I use v -cg run main.v, it still the same output
maybe it can be fixed or output a better content

**Comment by spytheman** [comment]
Fixed in db4a9d6 . Now this program produces a checker error:
![checker error for not matching argument types](https://url4e.com/gyazo/images/957e14c3.png)
