### ISSUE TITLE
"v help" command is not working

### ISSUE THREAD

**Issue by enesgur** [vlang/v#5658]
**V version:** V 0.1.28 e666209 
**OS:** Mac OS

**What did you do?**
I ran `v help` command. 

**What did you expect to see?**
I expected that list of v commands.
 
**What did you see instead?**
`V Error: Unknown help topic provided. Use "v help" for usage information.`

**Comment by Delta456** [comment]
Please update to latest commit.

**Comment by enesgur** [comment]
> Please update to latest commit.

fbfd92a commit works, thanks! I think, need new release.
