### ISSUE TITLE
REPL exits when removing spaces between array elements as the first input

### ISSUE THREAD

**Issue by robotee** [vlang/v#5665]
**V version:**V 0.1.28 67e85fa
**OS:** Windows 10

**What did you do?**
Declare an array on REPL like this (as the first input)
`a := ['a','b','c'] // no spaces after commas`

**What did you expect to see?**
 REPL to continue asking for input

**What did you see instead?**
REPL exits

This seems to happen only if declaring the array was the first input in REPL

**Comment by div72** [comment]
Can't reproduce, can you try it on the latest V? (Your commit hash is a day old.)

**Comment by robotee** [comment]
> 
> 
> Can't reproduce, can you try it on the latest V? (Your commit hash is a day old.)

After updating to the latest V the issue is gone and I can't reproduce when writing the array directly to the CMD. However,  when the array is pasted with CTRL+V the same issue happens again.

**Comment by robotee** [comment]
For some reason I can reproduce now when the array size is more than 3 elements.

**Comment by JalonSolov** [comment]
Working fine here
```
PS D:\git\v> v
For usage information, quit V REPL using `exit` and use `v help`
V 0.1.28 11866fb
Use Ctrl-C or `exit` to exit
>>> a := ['a','b','c']
>>> exit

PS D:\git\v> v
For usage information, quit V REPL using `exit` and use `v help`
V 0.1.28 11866fb
Use Ctrl-C or `exit` to exit
>>> a := ['a','b','c','d','e','f','g','h','i','j','k','l','m']
>>> exit

PS D:\git\v>
```

**Comment by robotee** [comment]
> 
> 
> Working fine here
> 
> ```
> PS D:\git\v> v
> For usage information, quit V REPL using `exit` and use `v help`
> V 0.1.28 11866fb
> Use Ctrl-C or `exit` to exit
> >>> a := ['a','b','c']
> >>> exit
> 
> PS D:\git\v> v
> For usage information, quit V REPL using `exit` and use `v help`
> V 0.1.28 11866fb
> Use Ctrl-C or `exit` to exit
> >>> a := ['a','b','c','d','e','f','g','h','i','j','k','l','m']
> >>> exit
> 
> PS D:\git\v>
> ```

In my case if the array is of type int and has more than three elements REPL exit right away. As for string it will exit when the size of the array is 2 even if there are spaces between elements.

These are some of the values that will make REPL exits:
`
a := ['a','b','c']
a := [1,2,3,4] // more than 3 elements (integers)

`

**Comment by JalonSolov** [comment]
```
PS D:\git\v> v
For usage information, quit V REPL using `exit` and use `v help`
V 0.1.28 11866fb
Use Ctrl-C or `exit` to exit
>>> a := [0,1,2,3,4,5,6,7,8,9]
>>> exit

PS D:\git\v>
```
Note that I'm using the very latest v as of this moment.

**Comment by robotee** [comment]
> 
> 
> ```
> PS D:\git\v> v
> For usage information, quit V REPL using `exit` and use `v help`
> V 0.1.28 11866fb
> Use Ctrl-C or `exit` to exit
> >>> a := [0,1,2,3,4,5,6,7,8,9]
> >>> exit
> 
> PS D:\git\v>
> ```
> 
> Note that I'm using the very latest v as of this moment.

It's absolutely an issue in my CMD maybe a code page setting or something. Thanks for the reply.

**Comment by JalonSolov** [comment]
It does appear to be something unique to your system.  I just tried in CMD shell (I used PowerShell the other times) and it still works here:
```
D:\git\v>v.exe
For usage information, quit V REPL using `exit` and use `v help`
V 0.1.28 11866fb
Use Ctrl-C or `exit` to exit
>>> a := [0,1,2,3,4,5,6,7,8,9]
>>> exit


D:\git\v>
```
