### ISSUE TITLE
Unexpected output for "in" operator

### ISSUE THREAD

**Issue by enesgur** [vlang/v#5670]
**V version:** V 0.1.28 fbfd92a
**OS:** Mac OS

**What did you do?**
I executed following code
```vlang
foo := "V Language"

println("" in foo) // Should be "false"
```

**What did you expect to see?**
The output should be false but it returned "true". I'm not sure but is my expectation wrong? 
 
**What did you see instead?**
`true`

**Comment by div72** [comment]
Disagreed, should return `true` in my opinion, there is an infinite amount of `""`s in that string.

**Comment by enesgur** [comment]
> Disagreed, should return `true` in my opinion, there is an infinite amount of `""`s in that string.

if there is an infinite amount of `""`, in that case following code should return `true` too  but didn't. 
```vlang
println("" in ["V", "Language"]) // false
```

**Comment by medvednikov** [comment]
Current behavior is correct.

There's an infinite amount of empty strings in any strings.

```"" in ["V", "Language"]``` is false because the array doesn't contain an empty string.

In Go, for example, this returns true.
```strings.Contains("xx", "")```
