### ISSUE TITLE
vfmt scanner doesn't escape amparsands in file path

### ISSUE THREAD

**Issue by charliemikels** [vlang/v#5671]
(on Manjaro Linux,) If the pwd of a file includes an ampersand (eg: `"~/Documents/examples&tests/v_tests/hello_world.v"`), `v fmt hello_world.v` tries to find two files and returns this error:
```
scanner error: /home/username/Documents/examples doesn't exist
sh: tests/v_tests/hello_world.v: No such file or directory

Encountered a total of: 1 errors.
```
However, `v run hello_world.v` works just fine.

Similar errors appear when given the full path:
```
$ v fmt /home/username/Documents/examples\&tests/v_tests/hello_world.v 

sh: tests/v_tests/hello_world.v: No such file or directory
vfmt error: v fmt can only be used on .v files.
Offending file: "/home/username/Documents/examples"
```

**Comment by Dialga** [comment]
The underlying issue is still not resolved, weird filenames like ;.v '.v ".v |.v still can't be formatted. Perhaps escape all non ascii symbols?
