### ISSUE TITLE
Unused variable errors bypassing in for loops

### ISSUE THREAD

**Issue by robotee** [vlang/v#5672]
**V version:** V 0.1.28 11866fb
**OS:** Windows 10

When an identifier is just a single underscore in a for loop it is ignored. 
So code like:
```
mut chars := [`a`, `b`, `c`]
for c in chars {
	println('Hi')
}
```
1) Will emit a WARNING 'warning: unused variable: `c`' (development mode)
2) Won’t compile (production mode)

So we need to replace c with _ (underscore) to make the code compile with no WARNING/ERROR. However, the problem is when we replace the variable c with something like _c
```
for _c in chars {
	println("Hi")
}
```

This will create a variable _c and also will bypass the V parser!!
**What did you expect to see?**
warning: unused variable: `_c`
 
**What did you see instead?**
Compile with no errors

**Comment by medvednikov** [comment]
Variable names cannot start with `_`, but it's not checked for loop variables.

**Comment by robotee** [comment]
> 
> 
> Variable names cannot start with `_`, but it's not checked for loop variables.
Is there a reason why it's not checked in a loop ?

**Comment by medvednikov** [comment]
It's not because it's not checked. It's a bug.

**Comment by robotee** [comment]
> It's not because it's not checked. It's a bug.

I honestly thought _c is a valid variable. Anyway, you're doing a great job here I love V ❤

**Comment by medvednikov** [comment]
Thanks :) Glad you like it.
