### ISSUE TITLE
REPL : Incomprehensible behavior with os.input ()

### ISSUE THREAD

**Issue by baxiry** [vlang/v#5678]
**V version:** 
0.1.28 0fb28eb

**OS:** 
linux

**What did you do?**
Set a variable with  os.input in REPL 

**What did you expect to see?**
Get the variable

**What did you see instead?**
Strange behavior. I cannot assign a value to a variable or enter anything.

**Comment by JalonSolov** [comment]
There are definitely issues using os.input() in REPL.  For one, it is not flushing the output before trying to get the input.  For another, it appears to be setting the variable to the prompt, rather than the input.
```
jalon@Ripper:~/git/v$ v
For usage information, quit V REPL using `exit` and use `v help`
V 0.1.28 271786b
Use Ctrl-C or `exit` to exit
>>> s := os.input('?: ')
asdf
?:
>>> s

?:
>>> g
error: undefined ident: `g`
    6 |
    7 | s := os.input('?: ')
    8 | println(g)
      |         ^
>>>
```

**Comment by ArtemkaKun** [comment]
Seems this is only a problem when creating a variable. Next calls of variable works as expected
```v
>>> s := os.input('?: ')
asdf
?:
>>> s
asdf
?: asdf
>>> s
ggrr
?: ggrr
>>>
```
