### ISSUE TITLE
inconsistent v.c

### ISSUE THREAD

**Issue by pznknmtb** [vlang/v#568]
**V version:**  N/A
**OS:** Ubuntu 18.04.2
**C compiler version:** N/A 

**What did you do?**

```
$ wget -q -O- https://vlang.io/v.c | md5sum
e6969177dce6b18d69d5ec81466933fe  -
$ wget -q -O- https://raw.githubusercontent.com/vlang/vc/master/v.c | md5sum
93bd742d595164bec462d2063a2f702a  -
```
two sources lead to inconsistency, maybe there should be only one.

**Comment by medvednikov** [comment]
vlang.io/v.c will be gone today

**Comment by Chiiruno** [comment]
Oh so that's what's going on.
What's the plan? I'm very interested in this.
Is v.c going to be deprecated and moved into the main source as a bootstrap hook, or do you mean it'll just be migrated to the vc repo instead?

**Comment by Oxylibrium** [comment]
https://vlang.io/v.c now redirects to the GitHub repo, closing.
