### ISSUE TITLE
`str` not called in string interpolation on native type alias

### ISSUE THREAD

**Issue by Gladear** [vlang/v#5683]
**V version:** V 0.1.28 4e66728
**OS:** 5.4.44-1-MANJARO

**What did you do?**
```v
type Byte = byte

fn (b Byte) str() string {
        return 'hello'
}

b := Byte(`a`)
println(b)
println(b.str())
println('$b')
```

**What did you expect to see?**
```bash
$ v run test.v
hello
hello
hello
```

**What did you see instead?**
```bash
$ v run test.v
hello
hello
97
```

**Further details**
When I tried to alias `Byte` to another type and redefine `str`, it worked as expected.
This occurs for the following types : i8, i16, int, i64, byte, u16, u32, u64, f32, f64, string.

**Comment by yuyi98** [comment]
The processing of `alias` in `interpolation` is `alias's parent_type`, so that's what happens. 
I do not know which is more appropriate?

**Comment by Gladear** [comment]
I don't know, but it must at least be consistent, and I would expect it to use the redefined `str` method.
I must add that when aliasing either `f32` and `f64`, the result was very weird... It was like it tried to print it as an integer.

**Comment by JalonSolov** [comment]
This looks very similar to #216 , where Alex said:

`Agreed. string(b) should be h, b.str() should be 104.`

**Comment by Gladear** [comment]
Not exactly, here I redefined the `str` method on the alias type, so I expect it to be called.

**Comment by Gladear** [comment]
Update: now prints
```
$ v run alias.v
97
hello
97
```
