### ISSUE TITLE
Mutating values behind references without specifying mutability.

### ISSUE THREAD

**Issue by KrisChambers** [vlang/v#5685]
According to the documentation on [References](https://github.com/vlang/v/blob/master/doc/docs.md#references), to mutate a struct you must use the `mut` keyword (ex: `mut foo Foo`) and not pass it by reference (i.e not `mut foo &Foo`).

**V version:**
V 0.1.28 33c5f6a
**OS:**
Manjaro Lysia 20.0.3

**What did you do?**
```
fn main() {
	thing := Thing {
		x: 0
	}
	println("$thing.x")
	
	foo(thing)

	println("$thing.x")
}

struct Thing {
mut:
	x int	= 0
}

fn foo(thing &Thing) {
	(*thing).x++
}
```

**What did you expect to see?**
Expected an error relating to the mutability of the parameter `thing` in the method foo. Similar to how pointer arithmetic needs to be wrapped in an unsafe block.

**What did you see instead?**
printed to screen:
```
0
1
```

**Comment by danieldaeschle** [comment]
Behaves correctly now!
