### ISSUE TITLE
don't use .io TLD for vlang's website

### ISSUE THREAD

**Issue by qlcom** [vlang/v#5686]
reference - https://yarmo.eu/post/no-io-yes-xyz

**Comment by qlcom** [comment]
@medvednikov what's your opinion?

**Comment by medvednikov** [comment]
The entire domain system is shady, even .org:

https://news.ycombinator.com/item?id=21611677

**Comment by qlcom** [comment]
> The entire domain system is shady, even .org:
> 
> https://news.ycombinator.com/item?id=21611677

@medvednikov it may be. But i think using .io TLD is a stupid idea for this project.

**Comment by JalonSolov** [comment]
Using words such as "stupid" is not conducive to a rational argument, or indeed any reason to give credence to your viewpoint.

Regardless of your feelings, vlang.io has existed for over a year, I believe, and you have not given a compelling reason to change it.

The negative impact is everyone who knows how to find it now would no longer be able to do so, unless vlang.io was retained by name with forwarding to the new name, which would incur extra expense.
