### ISSUE TITLE
sumtype casting bug

### ISSUE THREAD

**Issue by LouisSchmieder** [vlang/v#5689]
**V version:** V 0.1.28 bdecbc1.1416c70

**OS:** Manjaro

**What did you do?**
```v
type Abc = int | string

fn main() {
    b := 1
    a := Abc(b)

    match a {
        int {
            println(a)
        }
        else {}
    }
}
```

**What did you expect to see?**
`1`
 
**What did you see instead?**
`55febec874f0`

**Comment by elimisteve** [comment]
If `println(a)` is replaced with `println(*a)` then it prints `1` as expected, therefore it seems like a pointer value is being printed rather than the underlying value being pointed to.

**Comment by yuyi98** [comment]
`it` or `a` is indeed a pointer, if used directly requires adding `*` to dereference.

```v
	main__Abc a = /* sum type cast */ (main__Abc) {.obj = memdup(&(int[]) {b}, sizeof(int)), .typ = 7 /* int */};
	if (a.typ == 7 /* int */) {
		int* it = (int*)a.obj; // ST it
		int* a = it;
		println(ptr_str(a));
	} else {
	};
```

**Comment by nedpals** [comment]
Closed. Fixed in the latest V version: https://devbits.app/play/EWmdPUx1BNtv
