### ISSUE TITLE
Very slow compilation

### ISSUE THREAD

**Issue by SimpleVar** [vlang/v#5706]
**V version:** 0.1.28
**OS:** Windows 10 

**What did you do?**
Compiled the source file in [x.zip](https://github.com/vlang/v/files/4880039/x.zip) with the command `v x.v`
The source has ~1000 lines of code, all in the main() function.

**What did you expect to see?**
fast compilation
 
**What did you see instead?**
compiling takes 8 seconds to finish, for 1k lines of code

**Comment by JalonSolov** [comment]
Interesting.  Looks like a good attempt to prove something is slow.

The time it takes depends on quite a few factors.  I tried your code on my machine, and it took 2.5 seconds, using `V 0.1.28 cfa8e0a` and `gcc.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0` on my fairly beefy machine:
```
PS D:\git\v> Measure-Command {v x.v}

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 2
Milliseconds      : 550
Ticks             : 25507493
TotalDays         : 2.95225613425926E-05
TotalHours        : 0.000708541472222222
TotalMinutes      : 0.0425124883333333
TotalSeconds      : 2.5507493
TotalMilliseconds : 2550.7493


PS D:\git\v>
```
Of course, if you are really just after compilation speed, you can use TCC instead:
```
PS D:\git\v> Measure-Command {v -cc tcc x.v}

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 31
Ticks             : 313851
TotalDays         : 3.63253472222222E-07
TotalHours        : 8.71808333333333E-06
TotalMinutes      : 0.000523085
TotalSeconds      : 0.0313851
TotalMilliseconds : 31.3851


PS D:\git\v>
```
31 milliseconds isn't too bad.

**Comment by medvednikov** [comment]
```
time v x.v
v x.v  0.58s user 0.06s system 98% cpu 0.640 total
```

0.6 seconds on my 2017 machine with clang.
0.55 seconds if V itself is built with -prod

gcc is just very slow, we'll be switching to clang on windows by default

**Comment by SimpleVar** [comment]
```
> Measure-Command {v -cc tcc x.v}

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 5
Milliseconds      : 992
Ticks             : 59923289
TotalDays         : 6.93556585648148E-05
TotalHours        : 0.00166453580555556
TotalMinutes      : 0.0998721483333333
TotalSeconds      : 5.9923289
TotalMilliseconds : 5992.3289
```
Small improvement there.. still seems ridiculous for 1k lines of code.
Maybe the nature of the processing is somehow a problem? the size of a single function? I don't know.
Any practical tips on how to get fast compilation for ACTUALLY large code? (like 100k lines of sequential processing, similar to the example)

**Comment by medvednikov** [comment]
Something is wrong with your machine or setup.

**Comment by JalonSolov** [comment]
You need to look at several things, to start.

What _exact_ version of V are you running?  `v version` will tell you.

What C compiler (and version thereof) are you using?  `gcc --version` if you're using gcc, etc.

What CPU?

How much RAM?

What's the RAM speed?

Etc., etc.

**Comment by SimpleVar** [comment]
@medvednikov It sure feels like it, how can I find out where the issue is?

**Exact version:** V 0.1.28 9a4d989
I don't have gcc installed, only **msvc** (from either VS2017 or VS2019). Is that ok?
Running on a Lenovo Legion Y720
**CPU:** Intel i7-7700HQ 2.80GHz
**RAM:** 16 GB

**Comment by medvednikov** [comment]
also try timing `gcc v.c` (download from https://github.com/vlang/vc/raw/master/v.c)

**Comment by JalonSolov** [comment]
Hardware looks fine.  I'd suggest a different C compiler.

And you should be able to use `v up` to get to the latest commit of V.

**Comment by SimpleVar** [comment]
Installed gcc, reran `make` on v now that gcc is found, and also updated with `v up`.
```
> Measure-Command {v x.v}

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 49
Ticks             : 494050
TotalDays         : 5.7181712962963E-07
TotalHours        : 1.37236111111111E-05
TotalMinutes      : 0.000823416666666667
TotalSeconds      : 0.049405
TotalMilliseconds : 49.405
```
Works like a charm now :)
Thanks everyone!
