### ISSUE TITLE
UI users.v does not run w/ 

### ISSUE THREAD

**Issue by gshields** [vlang/v#5707]
window 10 ver 2004
 gcc --version
gcc.exe (x86_64-win32-sjlj-rev0, Built by MinGW-W64 project) 8.1.0
clean install of v
V 0.1.28 cfa8e0a
Expected compile of users.v to run as in previous compiles

...............
v -cg -keepc run users.v
-keepc is deprecated. V always keeps the generated .tmp.c files now.
C:\Users\ghs\.vmodules\ui\window.v:5:8: warning: module 'ft (gg.ft)' is imported but never used
    3 | // that can be found in the LICENSE file.
    4 | module ui
    5 |
      |
    6 | import gx
    7 | //import oldgg as gg
C:\Users\ghs\.vmodules\ui\window.v:85:2: warning: unused variable: `fpath`
   83 |     //window.ui.ticks_since_refresh = 0
   84 |     /*
   85 |     if e.typ == .key_down {
      |     ~~~~~
   86 |         game.key_down(e.key_code)
   87 |     }
C:\Users\ghs\.vmodules\ui\window.v:112:2: warning: unused variable: `scale`
  110 |
  111 |     gcontext := gg.new_context({
  112 |         width: cfg.width
      |     ~~~~~
  113 |         height: cfg.height
  114 |         use_ortho: true // This is needed for 2D drawing
ui.init()
V UI: icon file "" not found
The alternate text will be used.
V UI: icon file "" not found
The alternate text will be used.
window()
end of window()
g.scale=1 is_high_dpi=false fb_w=700 fb_h=385
Unhandled Exception 0xC0000005
print_backtrace_skipping_top_frames is not implemented

**Comment by medvednikov** [comment]
Fixed, there was a major backend change. Text is ugly atm, but that's a different issue.
