### ISSUE TITLE
data types should be reserved words

### ISSUE THREAD

**Issue by robotee** [vlang/v#5708]
**V version:** V 0.1.28 c3614c0
**OS:** 

This is similar to #2783 but more confusing and unexpected

**What did you do?**
```
fn main() {
	byte := 33
	println(sizeof(byte))
}
```
**What did you expect to see?**
1
 
**What did you see instead?**
4

If prohibiting this can slow down the parser I would suggest to do data type check first only in sizeof (if possible) or preventing passing data type in sizeof in the first place? or creating a new function for that purpose.

**Comment by medvednikov** [comment]
This is allowed in both Go and Rust, I don't think we should slow down the compiler with this check.
