### ISSUE TITLE
valgrind check out the memory leak

### ISSUE THREAD

**Issue by zeromake** [vlang/v#571]
**V version: 0.1.1** 
**OS: docker ubuntu 18** 
**C compiler version: clang 6.0.0** 

**build and run a hello world**

`hello_world.v`
``` go
fn main() {
    println('Hello World!')
}
```
build and use valgrind run
``` bash
v ./hello_world.v
valgrind ./hello_world
```
out
``` bash
root@0e235887bf93:~/code/v/examples# ./hello_world
Hello World!
root@0e235887bf93:~/code/v/examples# valgrind ./hello_world
==5481== Memcheck, a memory error detector
==5481== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==5481== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==5481== Command: ./hello_world
==5481==
Hello World!
==5481==
==5481== HEAP SUMMARY:
==5481==     in use at exit: 1,000 bytes in 1 blocks
==5481==   total heap usage: 2 allocs, 1 frees, 2,024 bytes allocated
==5481==
==5481== LEAK SUMMARY:
==5481==    definitely lost: 0 bytes in 0 blocks
==5481==    indirectly lost: 0 bytes in 0 blocks
==5481==      possibly lost: 0 bytes in 0 blocks
==5481==    still reachable: 1,000 bytes in 1 blocks
==5481==         suppressed: 0 bytes in 0 blocks
==5481== Rerun with --leak-check=full to see details of leaked memory
==5481==
==5481== For counts of detected and suppressed errors, rerun with: -v
==5481== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
If I'm going to use valgrind to handle a memory leak, it's going to make it difficult for me to troubleshoot.

The above from [v-vaporware](https://christine.website/blog/v-vaporware-2019-06-23)

**Comment by SuperFola** [comment]
Maybe a problem when the compiler is generating the strings? Something like a free(string) seems to be missing according to me

**Comment by AurelienFT** [comment]
No it's the init_consts function that you can see on the C code generated by the V compiler. It malloc 1000 and never free it

**Comment by SuperFola** [comment]
Sounds interesting 🤔 
Why should it allocate 1000B for const, when const are never the same? (I mean, each program will have its own bundle of const and stuff)

**Comment by LouCle** [comment]
Refer to Alex's comment in #514
