### ISSUE TITLE
V compiler panics when file does not end with newline

### ISSUE THREAD

**Issue by mallvielfrass** [vlang/v#573]
**V version:*V 0.1.1* 
**OS:*Arch Linux* 
**C compiler version:* gcc version 9.1.0 (GCC)* 

if after function main to write more than ten comments. an error occurs: "V panic: string index out of range:525 / 525"
```
fn main(){

    println('hello')
}
//1
//2
//3
//4
//5
//6
//7
//8
//9
//10
//11
```

**Comment by Oxylibrium** [comment]
Also on Arch Linux, code compiles and runs just fine though -
```
[oxy@lithium Code]$ cat test.v
fn main(){

    println('hello')
}
//1
//2
//3
//4
//5
//6
//7
//8
//9
//10
//11

[oxy@lithium Code]$ v/compiler/v test.v
[oxy@lithium Code]$ ./test 
hello
```

**Comment by Bowero** [comment]
I am also using Arch Linux, but it does not work for me.

```bowero@bow-pc:[~/D/vt]:cat pa.v
fn main(){

    println('hello')
}
//1
//2
//3
//4
//5
//6
//7
//8
//9
//10
//11%                                                                                                                                                                                                     bowero@bow-pc:[~/D/vt]:v pa.v
V panic: string index out of range: 80 / 80
```

**Comment by whoizit** [comment]
works for me in any cases on ArchLinux and r135

**Comment by AurelienFT** [comment]
On fedora it fails with only this
```
fn main(){
    println('hello')
}
//1
```

**Comment by AurelienFT** [comment]
It happen if you don't have a newline at the end of the file

**Comment by Bowero** [comment]
> It happen if you don't have a newline at the end of the file

I can confirm this. Good catch.

**Comment by Viza74** [comment]
It somewhat seems to be depend on what is the last line. I run into this when tried to create a module for a c library
 if the last line is:
```
fn C.GetMouseX() int
```
and no newline it panics with string index out of range.
I there *is* a newline, or the file ends with for example this :
```
struct C.Vector2 {
pub:
	x float
	y float
}
```
even without a newline, everything is fine.
