### ISSUE TITLE
'a, b += foo()' doesn't result in an error

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5735]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
```V
fn foo() (int,int) {
	return 10, 10
}

fn main() {
	mut a, mut b := foo()
	a, b += foo() 
	println(a)
	println(b)
}
```

**What did you expect to see?**
compile error

**What did you see instead?**
10, 10

_And the same applies to -=, *=, /=, ..._

**Comment by medvednikov** [comment]
it shouldn't compile:

```
syntax error: unexpected +=, expecting := or = or comma
```

**Comment by SleepyRoy** [comment]
@medvednikov Then how to write code to achieve `a, b += foo()`?

**Comment by medvednikov** [comment]
a += foo()
b += foo()

**Comment by SleepyRoy** [comment]
@medvednikov 
But that would result in assignment mismatch error. foo() returns two values while lhs only has one variable.

**Comment by medvednikov** [comment]
x, y := foo()
a += x
b += y

**Comment by SleepyRoy** [comment]
@medvednikov Yes it works, but isn't that kind of verbose? Why not allowing `a, b += foo()`?

**Comment by yuyi98** [comment]
The syntax itself is not very reasonable, we must first give up some special needs.

**Comment by Delta456** [comment]
@medvednikov is right. You can't do this in languages which have multiple assignments.

Go:
```go
package main

import (
	"fmt"
)

func r() (int, int) {
	return 12, 12
}

func main() {
	var a, b = 2, 3
	a, b += r()
	fmt.Println("Hello, playground")
}
```

Output: `syntax error: unexpected +=, expecting := or = or comma`


Python:
```python
def foo()
   return 12, 12

a, b = 2, 3
a, b += foo()
```

Output: `SyntaxError: illegal expression for augmented assignment`

**Comment by SleepyRoy** [comment]
@Delta456 Thanks for the info! I'm just thinking about why. Is it due to ambiguity? But I didn't come up with such a example.

**Comment by Delta456** [comment]
@SleepyRoy I think it is because you have multiple assignment for declaration and changing values only but not for declare assignments. This works.

```v
>>> mut a, mut b := 2, 3
>>> a, b = a+2, b+2

>>> a
4
>>> b
5
>>> 
```

**Comment by SleepyRoy** [comment]
@Delta456 Thanks. But I still don't understand why `a, b += foo()` shouldn't be allowed.

**Comment by medvednikov** [comment]
Because it's complicated and confusing, and I've never seen a use case for it.

In very rare situations when you need to do this, just use temp vars.

**Comment by medvednikov** [comment]
Actually should keep it open until it results in an error.
