### ISSUE TITLE
vfmt reads comments in `or` block as bad tokens

### ISSUE THREAD

**Issue by robotee** [vlang/v#5740]
**V version:** V 0.1.28 317b2dc
**OS:** 

**What did you do?**
```v
fn foo(a bool) ?bool {
	if a {
		return true
	}
	return error('Error')
}

fn main() {
	foo(false) or {
		 print(err)
		return // comment
	}
}
```

**What did you expect to see?**
 vfmt works with no errors

**What did you see instead?**
```
first.v:20:2: error: expr(): bad token `}`
   18 |          print(err)
   19 |         return // comment
   20 |     }
      |     ^
   21 | }
```

This seems only happens if a comment is placed after `return`

**Comment by serkonda7** [comment]
Works fine in the latest version of V.
