### ISSUE TITLE
'let' syntax

### ISSUE THREAD

**Issue by bettafish04** [vlang/v#5743]
# Reason
As writing ':=' is not very ergonomic to type, because both characters are typed with the pinky, I would propose an optional 'let' syntax like in Rust.

# Example

```
let x = 5
```

**Comment by Delta456** [comment]
`:=` is shorthand for `var name int`. I don't think this will be done.

**Comment by bettafish04** [comment]
Oh, i didn't know about that, could you give an example on how to use ```var name int```?

**Comment by Delta456** [comment]
You can't use this but like Go `:=` means the same thing as it goes against one way philosophy.

**Comment by bettafish04** [comment]
What about the c-like ```u8 x = 5```?

**Comment by Delta456** [comment]
You can do it like this `x := u8(5)` which is more simpler.

**Comment by bettafish04** [comment]
I dont think it is simpler because of the colon

**Comment by bashery** [comment]
This post may be useful
[https://blog.golang.org/declaration-syntax](Go's Declaration Syntax)

**Comment by medvednikov** [comment]
The := syntax is not going to change. The linked article explains the benefits well.

**Comment by bettafish04** [comment]
and what is the big difference between ```x := 5``` and ```let x = 5``` that prevents it?
it is easier to type the ```let``` version tbh

**Comment by Delta456** [comment]
@bashery `let` just introduces a new keyword and it is long to type as compared to `x := 5`.

**Comment by bettafish04** [comment]
but more ergonomic

(sorry if i'm annoying)

**Comment by JalonSolov** [comment]
Ergonomic?  How?  It's still not going to change, but I'm wondering how it can be considered "ergonomic" if it requires more typing, which adds stress to the carpals, increasing the likelihood of carpal tunnel syndrome.  That seems anti-ergonomic, to me.

**Comment by bettafish04** [comment]
@JalonSolov you don't have to:
- press shift
- use your pinky twice in a row
but instead just have to:
- type 'let'

**Comment by medvednikov** [comment]
So the amount of time is approximately the same, but the code is read a lot more than its typed (90/10), and `x := 0` is a lot more concise and readable than `let x = 0`.

Especially `mut x := 0` vs `let mut x = 0`
