### ISSUE TITLE
fn names shouldn't be allowed on lhs 

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5758]
**V version:** 
latest master with mingw64

**OS:** 
win10

**What did you do?**
```V
fn foo() {}

fn main() {
	foo = 1
}
```

**What did you expect to see?**
error
 
**What did you see instead?**
V panic: Ident.var_info(): info is not IdentVar variant
print_backtrace_skipping_top_frames is not implemented

**Comment by Delta456** [comment]
It is fixed with latest V.
