### ISSUE TITLE
Windows/MSVC support

### ISSUE THREAD

**Issue by vitalyster** [vlang/v#576]
1. v.c is not compatible with VC compiler
2. Makefiles are not compatible with NMake
3. Win32 ANSI APIs should not be used at all (WCHAR parameters should be converted to internal string representation automatically)
4. C stdio API should also not be used (for example, `printf` assume input string in OEM charset, `wprintf` or `WriteFileW` should be used there) - see http://utf8everywhere.org/#windows for details

**Comment by medvednikov** [comment]
V runs successfully on Windows. It can be built with MinGW-w64 or Clang. There's no goal to support Microsoft's outdated C compiler.
