### ISSUE TITLE
Support for any type

### ISSUE THREAD

**Issue by StunxFS** [vlang/v#5761]
Good! The idea that I show below is for the any type, which I think is not fully implemented.

As we know, in C we can use a void * to save the address of any value that is in memory, which allows us to use generics there, and, to use the value that that void * contains, we must use: `` (*(type*)val_voidptr)``, so based on that my idea is as follows:

When an any will be created as a field in a struct, a void* would be created in C, and a table for that field would be created in the compiler, in which the type of value it contains is stored (to avoid unwanted castings).
So, if in our code we do:
```v
name := "Stunx"
mut mianystruct := AnyStruct {
    anyval: &name
}
```
the value 'string' would be recorded in the anyval table, which is the type it currently contains.

And, when I will use that variable in a function that, for example, receives a string as a parameter, check that the current type that contains the any is the same required, and casting would be done in C.

```v
struct AnyStruct {
    anyval any
}

fn receiver(name string) {
    println(name)
}

fn main() {
    name := "Stunx" 
    mut mianystruct := AnyStruct {
         anyval: &name
    }
    receiver(mianystruct.anyval)
}
```
The casting would be: 
```c
receiver( ( *(string*)mianystruct.anyval)  );
```

**Comment by Delta456** [comment]
`any` is planned.
