### ISSUE TITLE
support multiple relation operations in one expression 

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5771]
**Background**
Sometimes we want to write e.g.
```V
abc.def_ghi_jkl_mno() == abcdefghi.len &&  ab.def_ghi_jkl_mno() == abcdefghi.len && a.def_ghi_jkl_mno() == abcdefghi.len
abcdefghi > abcdefghij && abcdefghij > abcdefghijk && abcdefghijk > abcdefghijkl
```
which is really verbose when names are pretty long.

**Proposal**
So I propose supporting multiple relation operations in one expression, which is already there in some languages such as Python. Here're some examples.
```V
a == b == c  // true iff a == b && b == c 
a > b > c  // true iff a > b && b > c
1 != 2 < 3  // true, because 1 != 2 && 2 < 3
100 > 0 < 5  // true, because 100 > 0 && 0 < 5
```
As you see reading such expressions is pretty easy, just from left to right one-by-one. You could imagine this feature is very useful in areas having a lot of relation ops such as scientific computing.

With this feature, the verbose code in the beginning would become much cleaner.
```V
abc.def_ghi_jkl_mno() == ab.def_ghi_jkl_mno() == a.def_ghi_jkl_mno() == abcdefghi.len
abcdefghi > abcdefghij > abcdefghijk > abcdefghijkl 
```

**Comment by bashery** [comment]
How do you express this ?
```
a := 1
b := 2
c := 3
d := 0
a > b || b > c || c > d // true
```

**Comment by medvednikov** [comment]
This was suggested a year ago, but it was decided not to do this, to keep things simple and to also follow the "one way" rule.

**Comment by medvednikov** [comment]
Found it:

https://github.com/vlang/v/pull/1198

**Comment by SleepyRoy** [comment]
@bashery The proposed syntax couldn't express logics with `or`s, but it solving situations with `and`s is still very useful.

**Comment by SleepyRoy** [comment]
@medvednikov Yeah I know, but like what's said in that issue, it makes code cleaner. One possible solution is V compiler automatically detects `a < b && b < c` and requires changing it to `a < b < c`.
But eventually it's up to you Alex. You may either disallow this feature and close this issue, or put it here for a while to let the community discuss more. : )

**Comment by bashery** [comment]
Yes `a> b> c` is beautiful.
Don't you think that partial solutions help create many dialects within the language?
Personally, I still think `a <b && b <c` is easier to read than `a> b> c`
Because it authorizes the logical process and displays it in front of the reader. You have the right to syntax this verbose. But it is also effective.
one syntax  covers all cases.

**Comment by medvednikov** [comment]
This was discussed on HN recently and agree with these comments:

https://news.ycombinator.com/item?id=23050421

> I honestly don't think being able to write 'a < b < c' is worth making the language bigger and causing weirdness and gotchas like this. 'a < b && b < c' isn't that much longer and is instantly and unambiguously readable to programmers coming from hundreds of other languages.

Covers the frequently requested negative indexing as well:

> I don't like it either when languages get too helpful. I was recently doing some python and getting some very odd results. Turned out the index I was using to pull stuff from the list had gone negative (off by one error) so it was getting stuff from the end of the list rather than excepting as most languages would.
