### ISSUE TITLE
Wrong line number warning reporting

### ISSUE THREAD

**Issue by mp81ss** [vlang/v#5785]
**V version:**
V 0.1.27 - 5 may 2020

**OS:** 
Windows

**What did you do?**

```
print('H') // string
println("ello") // string
assert "Hello"[0] == `H` // char/byte as backtick

age := 20 // (the only way to declare variables)
mut age2 := 0 // (variables must always have a starting value)
age2 = 1 // (the only way to modify a variable)
eq := age == age2
assert eq == false

mut sizes := []int{ len: 5, init: -1 } // { -1, -1, -1, -1, -1 }
```

**What did you expect to see?**
bug.v:11:5: warning: unused variable: `sizes`
 
**What did you see instead?**
bug.v:5:5: warning: unused variable: `sizes`
    3 | assert "Hello"[0] == `H` // char/byte as backtick
    4 |
    5 | age := 20 // (the only way to declare variables)
      |     ~~~~~
    6 | mut age2 := 0 // (variables must always have a starting value)
    7 | age2 = 1 // (the only way to modify a variable)

**Comment by AeroStun** [comment]
Unable to reproduce on V 0.1.28; please upgrade your compiler
![image](https://user-images.githubusercontent.com/24841307/87145918-6f8d9500-c2aa-11ea-80a9-d6927eed62ee.png)

**Comment by robotee** [comment]
Do you have `vfmt` automatically runs on every save ? if yes then this may be because `vfmt` . Try compile twice and see if something changes

**Comment by mp81ss** [comment]
I downloaded the windows package 2 hours ago, but I reported the first line of the changelog file.

The way I'm trying is:
```
v run ex.v
```

**Comment by Delta456** [comment]
I think this is a Windows exclusive error.

**Comment by mp81ss** [comment]
Even errors seems to have wrong reporting

**Comment by medvednikov** [comment]
V 0.1.27 - 5 may 2020 is an ancient version, there's 0.1.28.1 available, but it's also recommended to use the latest version from git.

**Comment by serkonda7** [comment]
Works fine in newer versions:
```
testy.v:11:5: warning: unused variable: `sizes`
    9 | assert eq == false
   10 | 
   11 | mut sizes := []int{ len: 5, init: -1 } // { -1, -1, -1, -1, -1 }
      |     ~~~~~
Hello
```
