### ISSUE TITLE
Extend the in operator for enum too

### ISSUE THREAD

**Issue by mp81ss** [vlang/v#5787]
Something like:

```
enum Color {
    red
    green
    blue
}

col := Color.red

// ALLOW THESE:
assert red in col
assert red in Color
```

**Comment by ntrel** [comment]
> assert red in col

assert col == .red

> assert red in Color

Why? How does V know what `red` is?

**Comment by mp81ss** [comment]
assert col == .red
is nonsense, col could be green, but red still belong to Color

**Comment by Gladear** [comment]
I think there's a misunderstanding. What would this feature do ?
> assert red in Color

`red` will always be in `Color`, as will `green` and `blue`, and you can't use another value, it would result in a compilation error.
> assert red in col

Can you explain when could this check fail ?

**Comment by mp81ss** [comment]
You're right, I was thinking somethng like (if blank in Color) { ... } where blank is an item of another enum.
In this case, if body should not be taken. I like reflection and I found it very usefull. Anyway, if it is contrary to the philosophy of the language, no problem at all. The most important thing is to continue keeping the language standard as simple as possible.
