### ISSUE TITLE
Duplicated method in interface

### ISSUE THREAD

**Issue by trufae** [vlang/v#5791]
**V version:** 
**OS:** 

**What did you do?**

```go
module main

interface Base {
        fun() string
}

fn (b Base) fun() string {
        return 'foo'
}

fn main() {
}
```

**What did you expect to see?**

intterfaces cannot have methods implemented, so i expect a meaningful error here. 

**What did you see instead?**

```
error: duplicate method `fun`
    5 | }
    6 |
    7 | fn (b Base) fun() string {
      |                ^
    8 |     return 'foo'
    9 | }
```

**Comment by bashery** [comment]
I think this is not a bug
You have already installed the method.
Interfaces also cannot be used like this.

**Comment by trufae** [comment]
The error message is misleading
