### ISSUE TITLE
return values, but without return in them should produce checker errors

### ISSUE THREAD

**Issue by trufae** [vlang/v#5792]
**V version:** 
**OS:** macOS 10.15

**What did you do?**

reproducer 1

```go
module main

fn fun() string {
}

fn main() {
	eprintln(fun())
}
```

2nd reproducer

```go
module main

interface Base {
	fun() string
}

fn (b BaseHolder) fun() string {
}

struct BaseHolder {
	a Base
}

fn main() {
	a := BaseHolder{}
	eprintln(a.fun())
}
```

**What did you expect to see?**

"Missing return statement in fun method"
 
**What did you see instead?**

```
$ v run soon.v
й���
```

**Comment by spytheman** [comment]
That is a bug with the checking of function return values - it should have produced an error for `fn fun() string {}` . Interfaces are not related imho.
