### ISSUE TITLE
C error on optional struct field

### ISSUE THREAD

**Issue by Tarang11** [vlang/v#5796]
**V version:** latest
**OS:**  Mac OS

**What did you do?**
struct User {
    pub:
    	name ?string 
}

a := User{name: "username"}

println(a)

**What did you expect to see?**
Initialised struct
 
**What did you see instead?**

`builder error: 
==================
C error. This should never happen.`

**Comment by Serkonda** [comment]
@Tarang11 could you please add the full error

**Comment by schoko123** [comment]
with V 0.1.29 818db91

this output is generated:


/tmp/v/st.tmp.c: In function ‘main__main’:
/tmp/v/st.tmp.c:7824:38: error: incompatible types when initializing type ‘int’ using type ‘string {aka struct string}’
  main__User a = (main__User){.name = tos_lit("username"),};
                                      ^~~~~~~
/tmp/v/st.tmp.c: In function ‘_vinit’:
/tmp/v/st.tmp.c:7851:38: warning: integer constant is so large that it is unsigned
  _const_math__bits__max_u64 = ((u64)(18446744073709551615));
                                      ^~~~~~~~~~~~~~~~~~~~
/tmp/v/st.tmp.c:7878:409: warning: integer constant is so large that it is unsigned
   ((u64)(1)), ((u64)(10)), ((u64)(100)), ((u64)(1000)), ((u64)(10000)), ((u64)(100000)), ((u64)(1000000)), ((u64)(10000000)), ((u64)(100000000)), ((u64)(1000000000)), ((u64)(10000000000)), ((u64)(100000000000)), ((u64)(1000000000000)), ((u64)(10000000000000)), ((u64)(100000000000000)), ((u64)(1000000000000000)), ((u64)(10000000000000000)), ((u64)(100000000000000000)), ((u64)(1000000000000000000)), ((u64)(10000000000000000000))}));

**Comment by medvednikov** [comment]
Fixed.
