### ISSUE TITLE
ld reports undefined reference to `D3D11CreateDeviceAndSwapChain'

### ISSUE THREAD

**Issue by gshields** [vlang/v#5805]
gcc.exe (x86_64-win32-sjlj-rev0, Built by MinGW-W64 project) 8.1.0
V 0.1.28 1c682d7
window 10 version 2004
Expected tetris.v to compile got this:
```
C:\Users\ghs\AppData\Local\Temp\ccl9uvog.o: In function `_sapp_d3d11_create_device_and_swapchain':
E:/p-tools/v/thirdparty/sokol/sokol_app.h:3763: undefined reference to `D3D11CreateDeviceAndSwapChain'
C:\Users\ghs\AppData\Local\Temp\ccl9uvog.o:tetris.tmp.c:(.rdata$.refptr.IID_ID3D11Texture2D[.refptr.IID_ID3D11Texture2D'
collect2.exe: error: ld returned 1 exit status
builder error:
==================
C error. This should never happen.
```

**Comment by nedpals** [comment]
Hello @gshields, please remove the unnecessary parts of your error log so that the devs won't waste time scrolling the backtraces (and it keeps crashing the Github app as well). Thanks :)

**Comment by medvednikov** [comment]
You should also use triple backticks for code blocks.

**Comment by JalonSolov** [comment]
Should work fine with latest V.  Do a `v up` to get the latest.

**Comment by gshields** [comment]
using newer version of mingw (gcc.exe (GCC) 10.2.0)  which works, closing this since I have a solution
