### ISSUE TITLE
Isolate kernel functions

### ISSUE THREAD

**Issue by jm-duro** [vlang/v#5811]
An ever growing Vlang is more difficult to stabilize than a Vlang kernel with additional libraries. Please isolate essential kernel functions.

I have been able to compile such a kernel on Linux Debian 10 AMD64 by moving test files and following subfolders out of the vlib_folder:
cli, crypto, dl, eventbus, fontstash, glm, live, orm, pg, picohttpparser, readline, sokol, stbi, clipboard, darwin, encoding, flag, gg, gx, mysql, os2, picoev, rand, regex, sqlite, sync
Resulting V kernel self compiles and is 30% smaller than original one.
$ ls -lh v v2 v_old | awk -F " " '{print $9 "\t" $5}'
v       1020K
v2      1020K
v_old   1,5M
$ v run ../hello.v
Hello

Regards

Jean-Marc

**Comment by bashery** [comment]
Sounds like a great idea

**Comment by JalonSolov** [comment]
Alex has said for a while that a good bit of the code under vlib would move to external modules at a later time.  It doesn't make sense to separate these pieces until at least 0.2, and possibly later.

In the meantime, if you are worried about he size, compile v with the `-prod` option to remove debugging info, etc.

**Comment by medvednikov** [comment]
@jm-duro I've just recently removed 8k lines of code from vlib. Most of the modules you listed will be removed as well.

Not tests or crypto though.
