### ISSUE TITLE
Nested cast fail

### ISSUE THREAD

**Issue by ka-weihe** [vlang/v#5821]
**V version:** 
V 0.1.28 c363c11

**OS:** 
Arch

**What did you do?**
```
fn main() {
  a := &int(int(0))
  println(a)
}
```
**What did you expect to see?**
print 0
 
**What did you see instead?**
```
tmp.c:9087:30: error: expected ‘,’ or ‘;’ before ‘)’ token
 9087 |  int* a = ((int*)((int*)(0))));
```

**Comment by nedpals** [comment]
Closed. Fixed in the latest V version: https://devbits.app/play/IcUwTi3cLpMF
