### ISSUE TITLE
Sum type `if`, `match` syntax, declaring a variable

### ISSUE THREAD

**Issue by ntrel** [vlang/v#5826]
## match
The docs for `match` on a sum type instance say:
> Note: shadowing only works when the match expression is a variable. It will not work on **struct fields, arrays indexing, or map key lookup**.

For those, we can use the `match sum as var` form. But `as` is also used for casting a sum type instance to one of its elements, so it is overloaded to have 2 meanings. Instead it would be more consistent with V declarations to use:
```v
match var := sum {
```

### Current syntax
In git we have:
```v
if stmt is AssertStmt | AssignStmt {
```
That syntax literally means *if stmt is one of these types* - that doesn't suggest that the type of `stmt` will change in the following block, because `sum is T` is a valid bool expression. I think it would be clearer if we use `as`:
```v
if stmt as AssertStmt | AssignStmt {
```
Literally: *if stmt as one of these types* (is valid). The type of `stmt` changing in the following block is less unexpected, because an `as` expression outside an `if` test produces a value of the given type.

Not convinced? What about when `stmt` is a struct field, array index expression, or a map key lookup - we need to declare a variable here:

### Using a named variable
```v
if val := sum as T {
  // here val is of type T
```
If we were using `if val := sum is T`, it would look like `val` was a `bool`, because `is` outside an `if` test produces a `bool`. Using `as` makes it clear and natural.

**Comment by medvednikov** [comment]
`if x is Foo {` is used in Kotlin and I remember seeing the very same syntax somewhere else.

I find it quite readable, and more grammatically correct than `if x as Foo {`

**Comment by ntrel** [comment]
@medvednikov Can we have syntax for declaring a variable with the `if` form please?

**Comment by ntrel** [comment]
I suppose we could use `as` just for the variable form:
```v
if sum is T {
  // Shadow sum
  ...
}
if val := obj.sum as T {
  ...
}
```

**Comment by ntrel** [comment]
@danieldaeschle told me it's already implemented with `if sum is T as var`:
```v
type Sum = S1 | S2

struct Wrap {
	sum Sum
}
s := Wrap{S1{}}
if s.sum is S1 as var {
```
This is consistent with `match sum as var`. I'd prefer `:=` syntax for both, but OK.
