### ISSUE TITLE
Os.input doesn't work with a string argument in REPL

### ISSUE THREAD

**Issue by snow-blade** [vlang/v#5832]
**V version:** 
V 0.1.28 df45488
**OS:** 
Ubuntu 18.04

**What did you do?**
I'm trying to get familiar with vlang so i was testing out the os module, i then launched v in cli mode:
```v
$ v
>>> import os
>>> works := os.input(" ") // this works when os.input contains an empty string
lol
>>>print(works)
lol
```
Then i tried to use it with an actual argument inside os.input
```v
>>> import os
>>> doesn't_work := os.input("hi ") // this does not work when we add a string inside os.input
```
I then double taped the enter key then i got this weird bug:
```v
>>> vc :=os.input("hello ")


 hello 
>>> 

```

**What did you expect to see?**
I expected to see a prompt that says hi then i should enter the value
 
**What did you see instead?**
Nothing, just that after i typed enter 2 times i got the string inside os.input then nothing, i just moved on to the next line

PS: this actually works when this code is inside  a .v file

**Comment by medvednikov** [comment]
Good, find, it’s a must have in REPL.

**Comment by bashery** [comment]
#5678

**Comment by JalonSolov** [comment]
Closed as duplicate.
