### ISSUE TITLE
Classic for loop gives no error for wrong statement order

### ISSUE THREAD

**Issue by Serkonda** [vlang/v#5846]
**V version:** V 0.1.28 6245876
**OS:** Manjaro

**What did you do?**
```v
mut sum := 0
for i := 0; i++; i < 100 {
	sum++
}
println(sum)
```

**What did you expect to see?**
Either an error or output of `100`.
 
**What did you see instead?**
Output `0`

**Comment by bashery** [comment]
On Fedora I got this error
t.v:3:6: error: redefinition of `i` .

There is a similar error:
```
for i := 1; i++; i < 100 {
    println(i)
}
```
output:
...
0
1
2 ...
260127
260128
260129
260130...

**Comment by Serkonda** [comment]
Oh, sorry I have written the for loop in my example twice... I corrected it

**Comment by Serkonda** [comment]
@medvednikov I'm working on a fix rn. Should this order be allowed or give an error?

**Comment by Delta456** [comment]
@Serkonda Like Go it should also give an error.

`syntax error: i++ used as value`
