### ISSUE TITLE
Cross-platform shell scripts in V / Support for shebang?

### ISSUE THREAD

**Issue by aurora** [vlang/v#585]
The possibility for cross-platform shell scripting mentioned in the documentation looks somehow promising. Under UNIX it would however be useful to have an executable using a shebang in the form of eg.: `#!/usr/bin/v` or `#!/usr/bin/env v` rather than having to run the script using eg. `v run deploy.v` - especially as you advertise it as alternative to traditional shell (bash) scripting.

Are there any plans to support this?

**Comment by medvednikov** [comment]
Sure. This will be available together with the V script feature.

**Comment by medvednikov** [comment]
Fixed. https://github.com/vlang/v/pull/1304

**Comment by ylluminate** [comment]
@medvednikov good read, although I think the approach could be refined: [Using Go instead of bash for scripts ](https://presstige.io/p/Using-Go-instead-of-bash-for-scripts-6b51885c1f6940aeb40476000d0eb0fc)
