### ISSUE TITLE
V in interactive mode crashes on CTRL+Z

### ISSUE THREAD

**Issue by SanoHD** [vlang/v#5859]
**V version:** V 0.1.28 55989b3
**OS:** Linux Mint (20)

**What did you do?**
Pressing CTRL-Z

**What did you expect to see?**
The V-interactive-shell closing
 
**What did you see instead?**
The whole terminal crashed, I had to fully close it and restart the terminal and V

**Comment by JalonSolov** [comment]
On latest V, Ubuntu 20.04, I don't see a crash, but the terminal does "freeze"... nothing I type shows up, etc.
