### ISSUE TITLE
Missing support for generics on methods-on-types

### ISSUE THREAD

**Issue by mp81ss** [vlang/v#5862]
**V version:** 
V 0.1.28 f6947d1

**OS:** 
Windows

**What did you do?**
```
struct Abc<T> {
    value T
}

fn (s Abc<T>) print_value() {
    println(s.value)
}

fn main() {
    s := Abc<string>{'hello'}
    s.print_value()
}
```

**What did you expect to see?**
hello
 
**What did you see instead?**
error: unknown method: `Abc<string>.print_value`

**Comment by Delta456** [comment]
It is being worked on.
