### ISSUE TITLE
Generic functions on interfaces don't work.

### ISSUE THREAD

**Issue by StunxFS** [vlang/v#5867]
**V version:** V 0.1.28 042add0
**OS:** Linux Mint 19.3

**What did you do?**
I tried to make use of a generic function in an interface but it didn't work for me.
```v
interface Object {
    name() string
    value<T>() T
}
```

**What did you expect to see?**
Let this work.
 
**What did you see instead?**
```
main.v:3:10: error: unexpected `<`, expecting `(` 
    1 | interface Object {
    2 |     name() string
    3 |     value<T>() T
      |          ^
    4 | }
    5 |
```

**Comment by Delta456** [comment]
This isn't fixed.

**Comment by yuyi98** [comment]
The generic interface has been implemented.
