### ISSUE TITLE
Cannot build program that imports external modules with sudo

### ISSUE THREAD

**Issue by Serkonda** [vlang/v#5877]
**V version:** V 0.1.28 1114fd2
**OS:** Manjaro

**What did you do?**
Run `sudo v symlinker.v` to build my program that imports `etienne_napoleone.chalk`.
Same behaviour is with any other module installed from vpm.

**What did you expect to see?**
Successful build
 
**What did you see instead?**
`builder error: cannot import module "etienne_napoleone.chalk" (not found)`

**Comment by Gladear** [comment]
It does work, however the module must be installed using `sudo` too. The user directory when using `sudo` is `/root` by default, thus modules must be installed in `/root/.vmodules`.
