### ISSUE TITLE
v/checker: Ban `var in [single_element]`

### ISSUE THREAD

**Issue by ntrel** [vlang/v#5879]
V should not allow using an `in` expression on an array literal with only a single element. It should require using `var == single_element` instead.

This is used in V with this pattern: `some_ident.mod !in ['builtin']`, where `ast.Ident::mod` is a string.

**Comment by Gladear** [comment]
Sounds like a good idea to me, but I wouldn't make a it compiler warning. Maybe automatically change it in `v fmt`, or report it in `v vet` ?

**Comment by Delta456** [comment]
@Gladear I think it should both report in `v vet` and change it in `v fmt`.
