### ISSUE TITLE
Tetris fails to build

### ISSUE THREAD

**Issue by Avokadoen** [vlang/v#5881]
**V version:** 0.1.28 1114fd2
**OS:** windows 10 Education 1803

**What did you do?**
v run tetris.v

**What did you expect to see?**
tetris start in a new window context
 
**What did you see instead?**
builder error: Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27034 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl -w /we4013 /volatile:ms /Fo"C:\Users\avokado\AppData\Local\Temp\v\tetris.tmp.c.obj" /MDd "C:\Users\avokado\AppData\Local\Temp\v\tetris.tmp.c" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt" -I "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared" -I "C:\repositories\v\thirdparty\sokol" -I "C:\repositories\v\thirdparty\sokol\util" -I "C:\repositories\v\thirdparty\freetype\include" -I "C:\repositories\v\thirdparty\fontstash" kernel32.lib user32.lib advapi32.lib dbghelp.lib ws2_32.lib gdi32.lib freetype.lib /link /NOLOGO /OUT:"C:\repositories\v\examples\tetris\tetris.exe" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.16299.0\ucrt\X64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.16299.0\um\X64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\X64" /DEBUG:FULL /LIBPATH:"C:\repositories\v\thirdparty\freetype\win64" /LIBPATH:"C:\repositories\v\thirdparty\freetype\win64\msvc"

tetris.tmp.c
C:\repositories\v\thirdparty\sokol\sokol_app.h(912): fatal error C1189: #error: ("sokol_app.h: unknown 3D API selected for Win32, must be SOKOL_D3D11 or SOKOL_GLCORE33")

**Comment by Avokadoen** [comment]
Updated msvc and ensured to download required packages in vs. Still got the same error:
 v run tetris/tetris.v
builder error: Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28806 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl -w /we4013 /volatile:ms /Fo"C:\Users\avokado\AppData\Local\Temp\v\tetris.tmp.c.obj" /MDd "C:\Users\avokado\AppData\Local\Temp\v\tetris.tmp.c" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt" -I "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared" -I "C:\repositories\v\thirdparty\sokol" -I "C:\repositories\v\thirdparty\sokol\util" -I "C:\repositories\v\thirdparty\freetype\include" -I "C:\repositories\v\thirdparty\fontstash" kernel32.lib user32.lib advapi32.lib dbghelp.lib ws2_32.lib gdi32.lib freetype.lib /link /NOLOGO /OUT:"C:\repositories\v\examples\tetris\tetris.exe" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\ucrt\X64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\X64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\lib\X64" /DEBUG:FULL /LIBPATH:"C:\repositories\v\thirdparty\freetype\win64" /LIBPATH:"C:\repositories\v\thirdparty\freetype\win64\msvc"

tetris.tmp.c
C:\repositories\v\thirdparty\sokol\sokol_app.h(912): fatal error C1189: #error: ("sokol_app.h: unknown 3D API selected for Win32, must be SOKOL_D3D11 or SOKOL_GLCORE33")

**Comment by SleepyRoy** [comment]
I just tried mingw64 and building Tetris also failed.

**Comment by SleepyRoy** [comment]
I remember this used to work around 1 month ago. Building of examples should be added to CI job to prevent such regression.

**Comment by Avokadoen** [comment]
Seems like other examples also fail, although I would have to confirm tomorrow.

**Comment by Avokadoen** [comment]
Works fine on ubuntu

**Comment by JalonSolov** [comment]
Fixed for Windows with PR #6155
