### ISSUE TITLE
cannot get element of array of fns

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5885]
**V version:** 
latest with mingw64

**OS:** 
win10

**What did you do?**
```V
fn foo(a string) int { 
	return 10
}

fn main() {
	a := [foo]
	b := a[0]('hello')
	println(b)
}
```

**What did you expect to see?**
10
 
**What did you see instead?**
C error

**Comment by wilesun** [comment]
This bug is also exists.
