### ISSUE TITLE
[Question]: Runtime and kernel development

### ISSUE THREAD

**Issue by Chiiruno** [vlang/v#590]
Will the runtime be removed by 1.0, or will we still have a runtime?
If the latter, perhaps rely on the runtime the least amount as possible for the core standard library?
It would be very nice to be able to make say, a kernel from V easily without having to reprogram the entire runtime for the new kernel.

**Comment by Immortalin** [comment]
One way can be to stub out the core runtime subroutines and reduce the required code as much as possible so embedded dev would be easier. E.g. perhaps 20 functions to recreate in assembly, basically the I/O ones and memory management functions.

**Comment by medvednikov** [comment]
V now has -freestanding that allows developing kernels.
