### ISSUE TITLE
os.get_lines() is broken on Windows

### ISSUE THREAD

**Issue by MattiaFailla** [vlang/v#5900]
**V version:** V 0.1.28 53e7cb1
**OS:** Windows 10

**What did you do?**
A simple program to read from the stdin:
```
import os
mut data := os.get_lines()
println(data)
```
Which is launched in this way:
`v test.v`
`tree . | test.exe`

**What did you expect to see?**
The whole output of the `tree` command
 
**What did you see instead?**
Only the first line of the command

Please note that `tree` is just an example, the bug is replicable with every command with a multi-line output.

**Comment by yaskhan** [comment]
What C compiler you use?

**Comment by yaskhan** [comment]
https://stackoverflow.com/questions/6736536/c-input-and-output-to-the-console-window-at-the-same-time

**Comment by danieldaeschle** [comment]
@spytheman what do you think, should this work like now or does it need to be changed?
