### ISSUE TITLE
enum casting dependent on file order

### ISSUE THREAD

**Issue by ChaseBrand** [vlang/v#5907]
**V version:** V 0.1.28 6dbc143
**OS:** Ubuntu 20.04 LTS

**What did you do?**
Create file **a.v** and file **e.v** with the following contents:

**a.v**
```v
module main

fn main() {
	x := 2
	y := Abc(x)
	println('x: $x | y: $y')
}
```
**e.v**
```v
module main

enum Abc {
	x = 1
	y = 2
	z
}
```

**v run .** inside the directory with the files.

**What did you expect to see?**
`x: 2 | y: y`

**What did you see instead?**
```v
./a.v:5:7: error: unknown function: Abc 
    3 | fn main() {
    4 |     x := 2
    5 |     y := Abc(x)
      |          ~~~~~~
    6 | 
    7 |     println('x: $x | y: $y')
```

This works, however, if you change the name of **e.v** to **1_e.v** or similar, as long as it comes _before_ **a.v**.

**Comment by danieldaeschle** [comment]
works now
