### ISSUE TITLE
Comments inside of sum type decl breaks vdoc comment parsing

### ISSUE THREAD

**Issue by emily33901** [vlang/v#5908]
**V version:** 8f23accc4eae8df81d12f2f95cfab7943584b96c
**OS:** msvc

**What did you do?**
`v doc callback.v`

exerpt from callback.v:
```v
// Callback represents all the possible callbacks
pub type Callback = 
	// SteamClient
	ConnectedCallback | DisconnectedCallback |

	// SteamUser
	LoggedOnCallback | LoggedOffCallback
```

**What did you expect to see?**
No error
 
**What did you see instead?**
Unexpected top level statement

@spytheman commented that this is because it only expects comments between top level statements and not inside of them - which this exerpt does have so it complains.

**Comment by ArtemkaKun** [comment]
Hi @emily33901, 
can you confirm an error with the latest V?

On Linux I have an error 
```
internal_memory:1:17: error: invalid character ``
```

**Comment by medvednikov** [comment]
Still an issue.
