### ISSUE TITLE
type of array or map with fns should be clear

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5909]
**V version:** 
latest with mingw64

**OS:** 
win10

**What did you do?**
```V
fn foo(a string) int {return 10}

fn main() {
	a := [foo]
	println(typeof(a))
	b := {'one':foo}
	println(typeof(b))
}
```

**What did you expect to see?**
(maybe)
array_fn_string_ret_int
map_string_fn_string_ret_int 

**What did you see instead?**
array_foo
map_string_foo

**Comment by SleepyRoy** [comment]
Update: with latest V I got
```
[]foo
map[string]foo
```
which are not nice and I expect 
```
[]fn(string) int
map[string]fn(string) int
```

**Comment by yuyi98** [comment]
Whether this has been fixed?

```vlang
fn foo(a string) int {return 10}

fn main() {
	a := [foo]
	println(typeof(a).name)
	b := {'one': foo}
	println(typeof(b).name)
}

PS D:\Test\v\tt1> v run .
[]fn (string) int
map[string]fn (string) int
```

**Comment by SleepyRoy** [comment]
@yuyi98 Yes seems it's also solved by your work, amazing! 
I opened a PR to add it to tests.
