### ISSUE TITLE
type bounds not honored at compile time

### ISSUE THREAD

**Issue by trufae** [vlang/v#5914]
**V version:** V 0.1.28 e1eb9c4
**OS:** macOS 10.15

**What did you do?**

<img width="312" alt="Screenshot 2020-07-21 at 15 29 27" src="https://user-images.githubusercontent.com/6431515/88060796-f83be900-cb66-11ea-9e1c-06a21a8bb212.png">

in C this generates:

```c
byte a = ((byte)(300));
```

**What did you expect to see?**

compile time error complaining about invalid value for given type like it happens if you do `a := string(123)`
 
**What did you see instead?**

a is 44 :D

**Comment by ntrel** [comment]
Pretty sure this is by design. `byte()` is a type conversion, not a byte literal.

**Comment by ntrel** [comment]
We could add a check that integer literals are within the bounds of the requested type conversion. So `byte(12)` could be a de-facto byte literal.

**Comment by medvednikov** [comment]
Still an issue.

**Comment by pierrec** [comment]
I would like to work on this to improve my understanding of the compiler. However after looking around, I cannot find an entry point to fix this. Any pointer?
