### ISSUE TITLE
error position becomes incorrect

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#5919]
**V version:** 
latest with mingw64

**OS:** 
win10

**What did you do?**
encountered this several times recently, here just give two examples
```V
fn foo(a string) int {
	return 10 + a.len
}
fn bar(a []foo) {  // although I think it should be `[ ]fn(string) int`
	b := a[0]
	c := b('hello')
	println(c)
}

fn main() {
	a := [foo]
	bar(a)
}
```

```V
fn foo(a string) int {
	return 10 + a.len
}

fn main(){
	a := [foo]
	b := a[0]('hello')    // workaround: temp := a[0]  b := temp('hello')
	println(b)
}
```
**What did you expect to see?**
(let's ignore whether code should be correct or not)
error position should be correct
 
**What did you see instead?**
the first one reported unknown function `b` error, but positioning at `a[0]`.
the second one reported expression evaluated but note used error, but positioning at `fn foo`.

**Comment by jiuker** [comment]
I think there have a temp variable to do this work;
In rust , that should be like 
 ```
    b_fun := a.get(0)?
    b:=b_fun('hello')
 ```
if not, when to drop the the variable which is just for runtime(I know it doesn't exist,but alaways have role do like it)

**Comment by SleepyRoy** [comment]
This is solved by latest V.
