### ISSUE TITLE
Serve static files

### ISSUE THREAD

**Issue by kethan** [vlang/v#5920]
**V version:** V 0.1.28 e666209

**OS:**  Linux

**What did you do?**
```
module main

import vweb

const (
	port = 8082
)

struct App {
pub mut:
	vweb vweb.Context // TODO embed
	cnt int
}

fn main() {
	println('vweb example')
	vweb.run<App>(port)
}

pub fn (mut app App) init_once() {
	app.vweb.handle_static('.')
}

pub fn (mut app App) init() {
}

```
```html
<script type="module">
	import { observable, html } from "https://unpkg.com/sinuous?module";

	const counter = observable(0);
	const view = () => html` <div>Counter ${counter}</div> `;

	document.body.append(view());
	setInterval(() => counter(counter() + 1), 1000);
</script>

```
**What did you expect to see?**

I expect to serve static files.
 
**What did you see instead?**

index.html:17:361: error: undefined ident: `counter`

**Comment by JalonSolov** [comment]
You are mixing 2 different things.  vweb and node.js style modules.  vweb doesn't handle node.js style modules, so it is correctly complaining that it doesn't understand what you have in the file.

**Comment by kethan** [comment]
So is there a way i can serve only static files?

**Comment by JalonSolov** [comment]
Look at the `vweb.serve_static()` function.

**Comment by chovy** [comment]
This doesn't seem to work for me either.

` 32   app.handle_static('public')`

inside `./public` i have `./index.html` and some folders. I just get 404 on them.
