### ISSUE TITLE
Compile error in example program for array in doc/docs.md

### ISSUE THREAD

**Issue by Nishikoh** [vlang/v#5925]
**V version:**  V 0.1.28
**OS:**  macOS 10.15

**What did you do?**
Tried to compile example program for array in doc/docs.md .
```V
numbers := []int{ cap: 1000 }
// Now adding new elements is as efficient as setting them directly
for i in 0 .. 1000 {
    numbers << i
    // same as
    // numbers[i] = i
}
```

**What did you expect to see?**
Success the compile
 
**What did you see instead?**
Got compile error
```
exampleArray.v:4:5: error: `numbers` is immutable, declare it with `mut` to make it mutable
    2 | // Now adding new elements is as efficient as setting them directly
    3 | for i in 0 .. 1000 {
    4 |     numbers << i
      |     ~~~~~~~
    5 |     // same as
    6 |     // numbers[i] = i 
```

**Comment by jiuker** [comment]
mut numbers := []int{ cap: 1000 }

**Comment by ntrel** [comment]
> // Now adding new elements is as efficient as setting them directly

Technically this is not true, because the length keeps getting updated after each append. Would be good to change to something like `// Now no reallocations are made`.

**Comment by Nishikoh** [comment]
> > // Now adding new elements is as efficient as setting them directly
> 
> Technically this is not true, because the length keeps getting updated after each append. Would be good to change to something like `// Now no reallocations are made`.

Good! I'll post new PR :D
