### ISSUE TITLE
String format in multiline string literals adds undesired character

### ISSUE THREAD

**Issue by Zarokka** [vlang/v#5930]
**V version:** 
0.1.28 6d09842
**OS:** 
Windows 10

**What did you do?**
```
        f := 42.0
	f2 := 33.3
	f3 := 21.21

	mut s := 'line 1: $f
line 2: $f2
line 3: $f3'

	println(s)
```

**What did you expect to see?**
line 1: 42
line 2: 33.3
line 3: 21.21
 
**What did you see instead?**
line 1: 42
line 2: �33.3
line 3: �21.21

an additional character seems to be added if something is placed into the string with $ in lines after the first

while this works as expected
```
	mut s := 'line 1: $f\nline 2: $f2\nline 3: $f3\n'
	println(s)
```

**Comment by nedpals** [comment]
Closed. Fixed in the latest V version: https://devbits.app/play/kerS1Sm1fMe2
