### ISSUE TITLE
suggestion: clea(n|r)er for loop syntax instead of classic C style one

### ISSUE THREAD

**Issue by jalelegenda** [vlang/v#5944]
I feel a for loop with the following syntax:
```
    for i in [1..30] 2 {
        println(i)
    }
```

- looks cleaner

- is more readable

- involves less typing

than the archaic C-style for loop.

few more examples:
```
    // counter decrement
    for i in [44..22] -2 {
        println(i)
    }

    // step omitted
    for i in [1..100] {
        println(i)
    }

    // side-by-side
    for i in [1..30] 2 {
        println(i)
    }

    for i := 1; i < 30; i += 2 {
        println(i)
    }
    // it took me 24 minutes just to type the above loop
```

**Comment by Delta456** [comment]
```
for i in [1..30] 2 {
        println(i)
    }
```

This doesn't make sense at all.

**Comment by ntrel** [comment]
>     for i := 1; i < 30; i += 2 {
>    // it took me 24 minutes just to type the above loop

But in that time you learned a useful V programming construct ;-)

**Comment by Gladear** [comment]
`for i in 0..30` already works, and extended range are already discussed in #4933 (but, to be honest, it's most unlikely that they will be implemented in the language)

**Comment by Delta456** [comment]
If you want these types of ranges then just my range library https://github.com/Delta456/range

**Comment by ntrel** [comment]
I've made #5949 to document range for.

**Comment by jalelegenda** [comment]
> ```
> for i in [1..30] 2 {
>         println(i)
>     }
> ```
> 
> This doesn't make sense at all.

In what way does it not make sense, please elaborate?

**Comment by Delta456** [comment]
@jalelegenda `[1..30]` in V is array slicing and `2` after that is `step` but it seems to be unreadable.

**Comment by ryan-willis** [comment]
@jalelegenda 
In what way is a C-style `for` loop unclear? It's clearer to me than your suggestion.

If you're concerned about typing less, you should make use of a text editor that supports creating snippets.
