### ISSUE TITLE
Problem Installing V on MacOSmake: wget: No such file or directory 

### ISSUE THREAD

**Issue by Sebastian-Schuchmann** [vlang/v#595]
MacOS: 10.14.5

I cloned the repo and then went into the v/compiler directory but when trying make it throws an error.  
```
$ make
wget https://vlang.io/v.c
make: wget: No such file or directory
make: *** [v.c] Error 1
```

**Comment by vitalyster** [comment]
You can replace wget with `curl -O` call, `curl` is the part of macOS/Xcode developer tools :)

**Comment by medvednikov** [comment]
you should install wget:

`brew install wget`

**Comment by medvednikov** [comment]
You can also download a prebuilt binary from the website now.
