### ISSUE TITLE
>>> 'a . . . .:'.split('. .')     V panic: substr(5, 4) out of bounds (len=10)

### ISSUE THREAD

**Issue by xucs007** [vlang/v#5951]
V version:  V 0.1.28 0af415f
OS:  Ubuntu 18.04

<pre>
>>> 'a . . . .:'.split('. .')
V panic: substr(5, 4) out of bounds (len=10)
</pre>

**Comment by spytheman** [comment]
This now produces: `['a ', ' ', ':']` since a2ec52b .

**Comment by Delta456** [comment]
Fixed
