### ISSUE TITLE
Vlang Archs

### ISSUE THREAD

**Issue by jcampbell05** [vlang/v#5955]
IS there any details on what Archs vlang supports ? If I want to compile it for use on a OS running on a Mips arch something I can do with Clang and C is this possible ?

**Comment by medvednikov** [comment]
It compiles to C, so any arch GCC/Clang support, so pretty much all of them.

**Comment by jcampbell05** [comment]
Awesome will this support continue in the future or will vlang move to its own compiler

**Comment by JalonSolov** [comment]
From the home page:

"Emitting C will always be an option, even after direct machine code generation matures."

Right now, V already has a full JavaScript backend, and a minimal direct x64 backend, in addition to the C backend.
