### ISSUE TITLE
struct field attributes don't work if there's a default value

### ISSUE THREAD

**Issue by vlangcoder** [vlang/v#5961]
**V version:** V 0.1.28 d204c92
**OS:** Ubuntu 20.04

**What did you do?**
const (
	currency_id = 'b7d2554b0ce847cd82f3ac9bd1c0dfca' // €
)
struct Price {
	currency_id string='$currency_id' [json:currencyId]
}

**What did you expect to see?**
In V 0.1.25 30f306d this code compiles.
Price.currency_id gets the value of [json:currencyId]. 
If [json:currencyId] is not set it gets the value from the const.
At least this is what I hoped it would do.
 
**What did you see instead?**
Compile error:
x.v:193:52: error: unexpected `]`, expecting `name` 
  193 |     currency_id string='$currency_id' [json:currencyId]
      |                                                       ^
  195 | }

**Comment by ArtemkaKun** [comment]
Hi @treffner, can you please update and error message? For a fresh V (master branch from 20.01.2022) it looks like next:
```
./main.v:6:40: error: unexpected token `:`, expecting `]`
4 |
5 | struct Price {
6 | currency_id string='$currency_id' [json:currencyId]
|                                        ^
7 | }
8 |
```

**Comment by treffner** [comment]
Hi, thank you for looking into this.

Example code:
```v
module main

import json

const (
	currency_id = 'cconst'
)
struct Price {
	net f64
	currency_id string='$currency_id' [json:currencyId]
}

fn main() {
	data := '[{"net":1},{"net":2,"currencyId":"cjson"}]'
	prices := json.decode([]Price, data) or { panic(err) }
	println(prices)
}
```

Expected outcome:
```bash
[Price{
    net: 1
    currency_id: 'cconst'
}, Price{
    net: 2
    currency_id: 'cjson'
}]
```

Current error:
```bash
v run .
./1.v:10:41: error: unexpected token `:`, expecting `]`
8 | struct Price {
9 |     net f64
10 |     currency_id string='$currency_id' [json:currencyId]
	|                                            ^
11 | }
12 |
```
