### ISSUE TITLE
raw strings do not work with trailing backslash

### ISSUE THREAD

**Issue by serkonda7** [vlang/v#5964]
**V version:** V 0.1.29 0ba5544
**OS:** Manjaro

**What did you do?**
```v
s := r'\'
println(s)
```

**What did you expect to see?**
Output of `\`
 
**What did you see instead?**
```
testy.v:3:1: error: unfinished string literal
    1 | s := r'\'
    2 | println(s)
```

**Comment by JalonSolov** [comment]
Did you try it with \`\\\\\` ?

**Comment by Serkonda** [comment]
It works but it's only a workaround.

**Comment by JalonSolov** [comment]
Actually, it does "fix it".  If doubling the backslash works, it means that "raw" strings still pay attention to escaped characters, and your original is just eating the trailing backslash.  Doubling the backslash just gives a single backslash in the output, which is what you wanted.

So this becomes a matter of clarifying whether "raw" strings are supposed to be truly "raw" (as in no manipulation, no escaping AT ALL), or whether minimal manipulation (such as handling escaped characters) is expected.

**Comment by Delta456** [comment]
I think this should given an error as it expected EOL while scanning. What you guys think?

**Comment by JalonSolov** [comment]
I think we need to clarify how raw strings are supposed to work, first.

**Comment by JalonSolov** [comment]
Ok, clarification from the docs:
```
For raw strings, prepend r. Raw strings are not escaped:

s := r'hello\nworld'
println(s) // "hello\nworld"
```
So this issue is a bug report - it should be printing a backslash instead of failing as it does now.

**Comment by danieldaeschle** [comment]
Duplication of #3243
