### ISSUE TITLE
$for/in and $if/is type checks needed

### ISSUE THREAD

**Issue by ntrel** [vlang/v#5971]
The new compile-time reflection added in #5957 is great work. There are some things that need tweaking though:
* `method.@type` is not clear that it means the method *return* type only.
* `$for method in Blah.methods` compiles even if `Blah` does not exist.
* `$if method.@type is Blah` compiles even if `Blah` does not exist.

**Comment by ntrel** [comment]
Also I don't know why methods or fields with attributes are iterated after those without attributes. It seems it would be better to use the declaration order instead.

**Comment by LouisSchmieder** [comment]
Oh shiiiit I forgot to check the types oops

**Comment by LouisSchmieder** [comment]
I haven't changed the order because it was already implemented but you're right we can change this

**Comment by LouisSchmieder** [comment]
everything should be fixed here, this issue will be closed
