### ISSUE TITLE
`$if field.@type is T`: `field.@type` is always an int instance

### ISSUE THREAD

**Issue by ntrel** [vlang/v#5972]
The new compile-time reflection added in #5957 is great work, but there is a conceptual problem with if/is type checks e.g. `field.@type is T`:
```v
struct S1 {
	b bool
}

mut i := 4 // int
$for field in S1.fields {
	i = field.@type // int instance
	$if field.@type is bool { // `int_instance is bool` is surely false?
		println(field.name)
	}
}
```
`sym is T` should be true only when `sym` is an instance of type `T`. Above, `field.@type` is an instance of `int`, not `bool`, yet the code prints 'b'.

Ideally, we would use `field.Type is T` where `field.Type` is an actual type, not an integer field of the builtin `FieldData` struct. Perhaps for now we can make `field.Type` only valid as the left side of an `is T` test. In the long term, it would be good to allow a type alias as a member of a struct, so `field.Type` can actually be used e.g. in a cast.

Edit: The same is true for `method.@type` from `$for method in Struct.methods`.

**Comment by LouisSchmieder** [comment]
should be @type be instead a `table.Type`?

**Comment by medvednikov** [comment]
This was fixed.
