### ISSUE TITLE
f32 & f64 precision & .str()

### ISSUE THREAD

**Issue by esquerbatua** [vlang/v#5984]
**V version:** V 0.1.28 88345d7
**OS:** Ubuntu 20.04

**What did you do?**
```
fn main() {
	f := f32(3.141516)
	println(f)
	fa := 3.141516//f64
	println(fa)
	faf == 3.141592653589793238
	println(faf == 3.141592653589793238)
	println(faf == 3.14159265358979323)
	println(faf == 3.1415926535897932)
	println(faf == 3.141592653589793)
	println(faf == 3.14159265358979)
}
```

**What did you expect to see?**
3.141516
3.141516
true
false
false
false
false
 
**What did you see instead?**
3.1415159702301025
3.141516
true
true
true
true
false

**Comment by Gladear** [comment]
This isn't directly related to V, but to the way floating point numbers are represented in a computer. Computers use the norm [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754) to represent numbers. Their is really nothing that can be done about it, apart from reinventing how processors work.

As for `println('${1/9}') // 0`, this is the normal way for integer division to work. If you want the result to be a float, use `println('${1.0/9.0}') // 0.111111`
