### ISSUE TITLE
v fmt removes codes

### ISSUE THREAD

**Issue by alai04** [vlang/v#5989]
**V version:** V 0.1.28 e666209
**OS:** macOS 10.15.6

**What did you do?**
I followed the tutorial of [blog](https://github.com/vlang/v/blob/master/tutorials/building-a-simple-web-blog-with-vweb.md). Make the `article.v` as:
```
module main

struct Article {
	id    int
	title string
	text  string
}

pub fn (app &App) find_all_articles() []Article {
	return sql app.db {
		select from Article
	}
}
```
Then I run `v fmt -w article.v`

**What did you expect to see?**
A formated file
 
**What did you see instead?**
But `v fmt` removes  some codes, it outputs:
```
module main

struct Article {
	id    int
	title string
	text  string
}

pub fn (app &App) find_all_articles() []Article {
	return 
}
```
Why `v fmt` do this?

**Comment by Delta456** [comment]
`vfmt` doesn't support `sql` right now.

**Comment by Delta456** [comment]
This issue should be kept open until its fixed.

**Comment by Gladear** [comment]
Formatting sql expression now works, but your version of V is one month old. Just `v up` !
