### ISSUE TITLE
Implement autoreconnect in websocket.close

### ISSUE THREAD

**Issue by Compro-Prasad** [vlang/v#5991]
I am opening this issue because I want to know why do we need to implement autoreconnect in close function and possibly what will be the usage. I am very new to this project and want to contribute some code.

https://github.com/vlang/v/blob/master/vlib/net/websocket/ws.v#L238

**Comment by helto4real** [comment]
I can not answer what the original author was referring to. I am doing some rework on the websocket implementation. In that version it is not implemented yet ether but if I would implement it I would make it as a feature to turn to reconnect if closed as an option. If the server is disconnecting it will try to reconnect and if fail wait a configurable time to retry again. This logic is very common in websocket clients. It would be beneficial to have it as feature. Also it will trigger the connect callback when reconnecting too so the user can do itś initialization logic there. Does that make sense @Compro-Prasad ?

**Comment by Compro-Prasad** [comment]
That was fast. I understand the explaination. But does the close method get called automatically when the server refuses/unable to connect? IMO the close method sould be called explicitly.

**Comment by helto4real** [comment]
I am not thinking of implementing it in the close function but more as a setting on the client to reconnect if closed. The user can choose to use or not. The default behavior fill be off. The correct close frame will be sent to do correct closure according to RFC ofc. The new implementation passes the autobahn tests.

**Comment by helto4real** [comment]
Can we close this @Compro-Prasad ?
