### ISSUE TITLE
Prevent address of local variables escaping

### ISSUE THREAD

**Issue by ntrel** [vlang/v#60]
To enforce memory safety, V could prevent the following:
```rust
fn f() *int {
	i := 7
	return &i // should error
}
fn g(i int) *int {
	return &i // should error
}
```
Escaping via a receiver field could also be prevented:
```rust
struct S {
	p *int
}
fn (s mut S) f() {
	i := 5
	s.p = &i // should error
}
```
When the address is stored in a local pointer, the analysis is more difficult. The local pointer would need to be flagged as containing an address to local data:
```rust
fn f() *int {
	i := 7
	p := &i
	return p // should error
}
```

**Comment by medvednikov** [comment]
I prefer Go's behavior: allocate `i` on heap instead of an error.

**Comment by ntrel** [comment]
I haven't used Go, only read a bit about it. (I found [a stack or heap FAQ](https://golang.org/doc/faq#stack_or_heap)). I think it's best to make heap allocation clear to the user, because it is a lot slower than stack allocation. Also it would be great if you could write a bit about what you're planning for memory management in V. I would guess that automatic memory management without GC or reference counting might need to be even clearer to the user when heap allocations occur.

**Comment by medvednikov** [comment]
Yes, it's a very common problem with Go: it's often unclear when things escape to the heap. 

In V only objects declared with `&` do.

**Comment by medvednikov** [comment]
For consistency and simplicity it's going to behave like Go:

https://play.golang.org/p/M9nDcsX1gCD
