### ISSUE TITLE
`(` in directory name disables functionality

### ISSUE THREAD

**Issue by LucasLarson** [vlang/v#6000]
**V version:** 0.1.28
**OS:** macOS 11.0 Beta (20A5323l)

**What did you do?**
1. Downloaded [macOS binary](https://github.com/vlang/v/releases/latest/download/v_macos.zip) <sup>([archive from today](https://web.archive.org/web/20200727212526id_/github.com/vlang/v/releases/latest/download/v_macos.zip))</sup> to a local folder called `~/Dropbox/My Mac (LBook.local)/Downloads` (resulting path after unzipping `~/Dropbox/My Mac (LBook.local)/Downloads/v`)
1. `cd ~/Dropbox/My\ Mac\ \(LBook.local\)/Downloads/v` # you have to escape spaces and parentheses
1. `pwd` with output `~/Dropbox/My Mac (LBook.local)/Downloads/v`
1. `./v up`

**What did you expect to see?**
`you’ve been updated to the latest version of V`
 
**What did you see instead?**
```shell
Updating V...
sh: ./v: No such file or directory

v self failed, running make...
/Applications/Xcode-beta.app/Contents/Developer/usr/bin/make fresh_vc
git clone --depth 1 --quiet https://github.com/vlang/vc ./vc
cd ./vc && git clean -xf && git pull --quiet
cc  -g -std=gnu11 -w -o v ./vc/v.c  -lm -lpthread
./v self
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `~/Dropbox/My Mac (LBook.local)/Downloads/v/v -o v2  cmd/v 2>&1'
V self compiling ...
cannot compile to `~/Dropbox/My Mac (LBook.local)/Downloads/v`:

make: *** [all] Error 1

Current V version:
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `~/Dropbox/My Mac (LBook.local)/Downloads/v/v version'
```

**Comment by danieldaeschle** [comment]
Works now (at least on windows)

reopen if needed.

**Comment by LucasLarson** [comment]
- [x] confirmed working on macOS, too – thank you
