### ISSUE TITLE
vfmt should not unwrap lines by default

### ISSUE THREAD

**Issue by ntrel** [vlang/v#6005]
vfmt wrapping lines is a useful feature, but it's not easy for a programmer to predict when a line needs to be broken. It should be possible to learn the style vfmt uses so that running the formatter causes minimal changes. We don't want programmers to have to keep checking the column position so that they know where to add a line break. Instead, please make line wrapping an option that is off by default.

Breaking lines also causes a lot of changes to code that hasn't been run through vfmt, creating a big diff.

**Comment by Gladear** [comment]
One of the purpose of vfmt is to have code that looks exactly the same on every V program. This means that there certainly won't be any option.

Ideally, you should format your file before each commits, so you don't have to worry about the changes vfmt brings in the VCS history.

Also, as a side note, I've never seen a formatter that propose not to wrap lines.

**Comment by ntrel** [comment]
> I've never seen a formatter that propose not to wrap lines.

I'm not proposing that, I'm asking for it to allow shorter lines when the programmer writes them instead of making lines longer! 
The programmer has the best idea of when to break a line for readability, not a simple algorithm.
I'd rather not have to run the formatter every time I modify my git branch, that's an unreasonable expectation. I'd like to be able to write code in the correct style so formatting isn't necessary.

**Comment by JalonSolov** [comment]
I agree with ntrel.  If I had to make a really long line, or a deeply indented line, it would just look weird to me to have it wrapped by vfmt.

I just tried a 201 character comment in go fmt, and it didn't touch the line:
```
// this is a very long comment line that I am contriving to make just to see if it will actually get formatted for line length by go fmt since there could very well be an issue with really long lines.
```
but when I tried the same thing with `v fmt`, it gave me this:
```
// this is a very long comment line that I am contriving to make just to see if it will actually get formatted for line.
```
... in other words, it threw away most of my comment.

**Comment by Gladear** [comment]
@ntrel Editors supporting V will eventually format your files on save. It's not mandatory using vfmt to format your files, just highly recommended :smile: 

@JalonSolov IMO comments should be the exception, they shouldn't be modified. Anyway, whether they will be splitted in multiple lines or kept untouched, the behavior you've shown clearly is a bug that will eventually be fixed.

**Comment by serkonda7** [comment]
fmt is very opinionated, so it will never have options to disable some features.
The user choice is already respected up to some degree.

Therefore I'm going to close this now. 
Nevertheless if you have specific code pieces that could be better formatted, please feel free to open new issues with them.
