### ISSUE TITLE
element pointer dereference after array realloc

### ISSUE THREAD

**Issue by oconnor663** [vlang/v#6007]
The readme mentions that "no undefined behavior" is a key feature of V. Does the following program demonstrate undefined behavior?

```v
// Make an array of numbers.
mut nums := [0, 1, 2, 3]

// Take a reference to the last element.
x := &nums[3]

// Read the reference and print it. Prints 3.
println(*x)

// Add a new element to the array.
nums << 4

// Read the reference and print it again.
// Expected: Either prints 3 again, or a bounds check fails, or a compiler error.
// Actual: Prints some other number, a different value each time.
println(*x)
```

It looks like inserting an element causes the array to be reallocated, which invalidates the reference. Valgrind confirms that this is an "Invalid read of size 4". (Edit: Confirmed this in the generated C code [below](https://github.com/vlang/v/issues/6007#issuecomment-667160535).)

Does V consider this to be undefined behavior? If so, is there a plan to catch dangling pointer reads like the one above at compile time? If not, what is V's definition of undefined behavior?

**Comment by yunree** [comment]
![6007](https://user-images.githubusercontent.com/17256443/88979750-93009a00-d2c2-11ea-9a63-cccc88773d7a.png)

Hello! 
I can't replicate this issue. Is it fixed now?

Thank you for reading this, and sorry in advance, I am new to V. 🙇‍♀️

<details>
<summary>Details</summary>

**OS:** macOS Catalina 10.15.5, Hackintosh (iMac15,1)
**Shell:** fish shell, version 3.1.2
**V**: 0.1.28 91c9c0c

</details>

**Comment by Ivo-Balbaert** [comment]
On Windows 10 and V version V 0.1.28 eb47ce1, the second println(*x) always prints 0, whereas the expected value is 3.

**Comment by oconnor663** [comment]
If I understand the underlying issue correctly, the result is going to vary a lot depending on compiler settings and what the rest of the program is doing. We're trying to read old memory that's been freed, and the original value might still be there, or it might not. If it's not there, it might get overwritten by something consistent, or it might be random-looking.

**Comment by oconnor663** [comment]
We can see what's going on in the transpiled C code like this:

```
❯ cat test.v
mut nums := [0, 1, 2, 3]
x := &nums[3]
println(*x)
nums << 4
println(*x)

❯ TMPDIR=. v test.v

❯ tree
.
├── test
├── test.v
└── v
    ├── test.tmp.c
    └── test.tmp.c.rsp
```

Now if we look in `test.tmp.c`, we see these functions:

```c
static void main__main() {
	array_int nums = new_array_from_c_array(4, 4, sizeof(int), _MOV((int[4]){0, 1, 2, 3}));
	int* x = &(*(int*)array_get(nums, 3));
	println(int_str(*x));
	array_push(&nums, _MOV((int[]){ 4 }));
	println(int_str(*x));
}
```

```c
static void array_push(array* a, voidptr val) {
	array_ensure_cap(a, a->len + 1);
	{ // Unsafe block
		memcpy(((byteptr)(a->data)) + a->element_size * a->len, val, a->element_size);
	}
	a->len++;
}
```

```c
inline static void array_ensure_cap(array* a, int required) {
	if (required <= a->cap) {
		return;
	}
	int cap = (a->cap == 0 ? (2) : (a->cap * 2));
	while (required > cap) {
		cap *= 2;
	}
	if (a->cap == 0) {
		a->data = vcalloc(cap * a->element_size);
	} else {
		a->data = v_realloc(a->data, ((u32)(cap * a->element_size)));
	}
	a->cap = cap;
}
```

This is the expected problem. `array_get` obtains a pointer into the array buffer, but `array_push` calls `array_ensure_cap` which calls `realloc`, invalidating that pointer.

**Comment by JalonSolov** [comment]
Bottom line:  As soon as you start messing with pointers and references, it is far too easy to cause undefined behavior.  In fact, this particular type of thing should not be allowed outside an `unsafe` block, for that very reason.

**Comment by medvednikov** [comment]
This is an old bug, and this will be fixed. *x will always have `3`

**Comment by oconnor663** [comment]
@medvednikov is the plan to keep the backing array alive as long as there are still pointers to it, like Go does? Will that require some kind of GC?

**Comment by Ivo-Balbaert** [comment]
Please solve this issue before v 0.2 is released.

**Comment by oconnor663** [comment]
I just retested the example code above with today's 0.2 release. Now it's a compiler error:

```
test.v:5:11: error: cannot take the address of mutable array elements outside unsafe blocks
    3 | 
    4 | // Take a reference to the last element.
    5 | x := &nums[3]
      |           ~~~
```

However, we can modify the example to reproduce the original memory safety issue. In this new version we alias the mutable array by taking a slice of it:

```
// Make an array of numbers.
mut nums := [0, 1, 2, 3]

// Alias the array with a slice.
slice := nums[0..]

// Take a reference to the last element.
x := &slice[3]

// Read the reference and print it. Prints 3.
println("x is ${*x}")

// Add a new element to the array.
nums << 4

// Read the reference and print it again.
// Expected: Either prints 3 again, or a compiler error.
// Actual: Prints some other number. (On my machine right now, it prints 0.)
println("x is ${*x}")
```

This new version compiles cleanly under 0.2, but running it under `valgrind` still reports an "Invalid read of size 4".

**Comment by ntrel** [comment]
@oconnor663 thanks for the update. Could you file the slice bug as a separate issue (if not already there) please?

**Comment by oconnor663** [comment]
Done. Maybe close this one?
