### ISSUE TITLE
Readme.md is broken

### ISSUE THREAD

**Issue by WortWal** [vlang/v#6030]
**V version:** 
**OS:** 

**What did you do?**

**What did you expect to see?**
the full readme
 
**What did you see instead?**
only the image

**Comment by JalonSolov** [comment]
Which readme?  How did you try to view it?

**Comment by nedpals** [comment]
@WortWal where did you read the readme file

**Comment by WortWal** [comment]
Sorry im dunmp

**Comment by WortWal** [comment]
Sorry I'm dump its ok.
