### ISSUE TITLE
.js.v -- unknown host OS

### ISSUE THREAD

**Issue by antonkatz** [vlang/v#6033]
**V version:** 0.1.28 0fb8074
**OS:** Arch linux 5.6.5-arch3-1

**What did you do?**
I have a file `hello.js.v` with a single `println` in it. 
I ran `v -b js hello.js.v` and `v hello.js.v`

**What did you expect to see?**
Both commands execute without error
 
**What did you see instead?**
`v -b js hello.js.v` executes just fine
`v hello.js.v` gives the following

`
V panic: unknown host OS
print_backtrace_skipping_top_frames is not implemented. skipframes: 4
Terminated by signal 139 (SIGSEGV)
`

**Additional info**
Running `v hello.v` executes just fine for me, however running `v -os linux hello.v` gives `v expects that `-os` exists, but it does not`. I compiled v from source.

**Comment by leahlundqvist** [comment]
Is this still reproducible?

**Comment by Delta456** [comment]
Fixed in https://github.com/vlang/v/pull/6777
