### ISSUE TITLE
wrap Unix fork() and exec() as run fn()

### ISSUE THREAD

**Issue by cristian-ilies-vasile** [vlang/v#6041]
I am thinking how to wrap fork() => exec() Unix functions to create a child process, however, running in a separate address space we need a 2 way communication channel like anonymous pipes or named pipes.
The syntax in V could be something like:
`run fn1(chanel_name string, other_details string)        // run = fork & execute `         

V compiler should perform following actions: 
a) compile fn1() as a separate program aka fn1.exe on the same folder with main V code.
b)  chanel_name -> will became  the name of a Unix/Windows named pipe
c) insert proper C code aka fork() -> exec(fn1)  on main transpiled  *.C file

However fn1() should be able to exchange data with the parent using named pipe defined at point b)

**Comment by penguindark** [comment]
Having the right channels this can be a good solution for me, speaking of parallelism :)

**Comment by dumblob** [comment]
I actually don't think a built-in syntax is a good idea for processes. I think the language should stay small and stick to "there is only one way of doing things". For parallelism there are `go routines` and `Channel`s. I don't see any reason to have another form of parallelism in the language.

Note also, there are **fundamental** difficulties with os processes - first of all, there is no `fork()` in non-unix world (and there is an initiative ongoing for many years to get rid of `fork()` on unices as well - see e.g. the modern paper [A fork() in the road](https://www.microsoft.com/en-us/research/uploads/prod/2019/04/fork-hotos19.pdf )). Second, os processes need an operating system (obviously). But *V* **must be** os agnostic and run e.g. on real-time embedded operating systems (which typically do not have any processes, but only some sort of thread primitives) or even bare metal.

All in all, I think a high-level API (i.e. **not syntax**) maybe similar to Python's `subprocess.run(args, *, stdin=None, input=None, stdout=None, stderr=None, capture_output=False, shell=False, cwd=None, timeout=None, check=False, encoding=None, errors=None, text=None, env=None, universal_newlines=None, **other_popen_kwargs)` would be best and shall satisfy all our needs.

**Comment by spytheman** [comment]
There is now `os.new_process`, see  https://github.com/vlang/v/blob/master/vlib/os/process_test.v .
