### ISSUE TITLE
Questions regarding statically linked binaries

### ISSUE THREAD

**Issue by aibhstin** [vlang/v#6053]
I've been learning V and really enjoying it and I saw that the website says:

> You get a single statically linked binary that is guaranteed to work on all operating systems (provided you cross compile) without any dependencies.

Yet when I compile executables, I find that they are dynamically linked.

```
> ldd 01_hello_world
        linux-vdso.so.1 (0x00007fffd99c6000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fca25649000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fca25457000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fca256b8000)
```

My question is, am I doing something wrong? I have tried using -static and -bare and gotten the same results.

**Comment by JalonSolov** [comment]
You saw your answer on Discord, I hope.

You have to add `-cflags -static` to get a statically linked binary.
