### ISSUE TITLE
Single line if is broken?

### ISSUE THREAD

**Issue by Viza74** [vlang/v#606]
**V version:** 
0.1.3

**OS:** 
macos

**C compiler version:** 

**What did you do?**
Nothing, this worked in the previous version, and not builds after updating to the new version.

```
fn (a Vec2) angle(b Vec2) float {
	mut res := math.atan2(b.y - a.y, b.x - a.x)*(180.0/math.Pi)
    if res < 0 { res += 360.0 }
    return res
}

// Rotate vector
fn (a Vec2) rotate(rotation float) Vec2 {
```

**What did you expect to see?**
Build normally
 
**What did you see instead?**

```
PREV=}
NEXT=(
pass=2 fn=`angle`
panic: vec2.v:134
unexpected token: `fn`
```
The line 134 in the error is the``` fn (a Vec2) rotate(rotation float) Vec2 {``` line but the real reason seems to be the line ```if res < 0 { res += 360.0 }```
If change that to
```
    if res < 0 {
		res += 360.0
	}
```
it builds again

**Comment by medvednikov** [comment]
Thanks for reporting this, I know the reason.

**Comment by ntrel** [comment]
Closing this in favour of #929, that has a clearer title ;-)

**Comment by medvednikov** [comment]
It's fixed.
