### ISSUE TITLE
Anonymous and function return

### ISSUE THREAD

**Issue by kethan** [vlang/v#6065]
V version: V 0.1.28

OS: Linux

**What did you do?**
```
fn c() fn() {
return fn(){println("anon")}
}

fn main() {
  a:=c()
  a()
}
```

**What did you expect to see?**

I expect to call anon function. The same thing is working in the GO
 
**What did you see instead?**
main.v:4:11: error: unexpected `)`, expecting `name` 
    2 | 
    3 | 
    4 | fn c() fn() {
      |           ^
    5 | return fn(){println("anon")}
    6 | }

**Comment by Delta456** [comment]
These aren't implemented yet.

**Comment by 0-8-15** [comment]
Completely new to`v` I ran into this too.  For me this - not having anonymous lambda's - is a show stopper --- while I **really** like the rest of it.

Would this be hard to implement?  What would it take?  I feel ready to spent some time on trying.  (But so far I know too little about the code base to get me started.)

**Comment by spaceface777** [comment]
That code snippet compiles and runs successfully with the latest V (0.1.29 99e607d at the time of writing).
Note that closures are not yet implemented, however.
