### ISSUE TITLE
dangling pointer when returning address of string

### ISSUE THREAD

**Issue by dabba39** [vlang/v#6067]
**V version: 0.1.28 f331f63** 
**OS: linux** 

**What did you do?**
```
fn foo() &string {
   bar := "bar"
   return &bar
}
fn main() {
   println(*foo())
}  
```

**What did you expect to see?**

`bar`

 
**What did you see instead?**
`Segmentation fault (core dumped)`

**Comment by dabba39** [comment]
In Go, that works: https://play.golang.org/p/d-qELAOBl09
```
package main

import (
	"fmt"
)

func foo() *string {
   bar := "bar"
   return &bar
}

func main() {
   fmt.Println(*foo())
}
```

**Comment by vtereshkov** [comment]
Local variables are generally allocated on the stack. However, the Go compiler automatically performs "escape analysis" to determine whether a variable is to be allocated on the stack or on the heap. If a reference to a local variable is returned from a function, the variable must be on the heap. I wonder if V performs such kind of analysis.

**Comment by danieldaeschle** [comment]
works now
