### ISSUE TITLE
Use of getrandom linux syscall limits usage to linux >= 3.17

### ISSUE THREAD

**Issue by lancethepants** [vlang/v#6075]
**V version:** 
V 0.1.28 09f1362

**OS:** 
Linux 2.6.36.4
Linux 2.6.22.19

**What did you do?**
Try to compile example program vpwgen.v

**What did you expect to see?**
successfully compile program
 
**What did you see instead?**
/mmc/tmp/v/vpwgen.tmp.c: In function 'crypto__rand__getrandom':
/mmc/tmp/v/vpwgen.tmp.c:9642:17: error: 'SYS_getrandom' undeclared (first use in this function)
 9642 |  return syscall(SYS_getrandom, buffer, bytes_needed, 0);

Linux only has the getrandom syscall function since linux 3.17 which released in 2014.  I've been using V for embedded development, but run kernels as old as 2.6.22.19.  This is an old kernel, but I would have V could at least run on kernels as old as 2.6.32 which is Redhat Linux 6.

**Comment by ArtemkaKun** [comment]
Hi @lancethepants,
can you confirm that the error still exists?

Also, if you are not in V's Discord community - we have created a separate **embedded** channel, maybe you will find more help there.

**Comment by lancethepants** [comment]
Yes, I just tried again and there isn't any fallback for systems that lack the `getrandom` syscall.
I'll check out the discord for sure. V I think can be an amazing language for embeded devices.

**Comment by medvednikov** [comment]
@lancethepants what should be used instead?

**Comment by lancethepants** [comment]
I'm now thinking this is really more of a libc issue. I was using uclibc-ng for a bunch of stuff, and they just don't have the getrandom syscall wrapper implemented, but they need to.  musl is planning a fallback to their getrandom wrapper for kernels that are too old to have the syscall.
If someone felt inclined they could program a fallback in V, I guess just doing what was done before getrandom landed in the kernel, probably from /dev/urandom. Otherwise you can close this issue.
