### ISSUE TITLE
Variable size multidimensional arrays - shorter declaration

### ISSUE THREAD

**Issue by mobarski** [vlang/v#6077]
Currently we can declare variable size multidim arrays like this:

```v
// 2d
mut a := [][]int{len:2, init: []int{len:3}}

// 3d
mut a := [][][]int{len:2, init: [][]int{len:3, init: []int{len:2}}}

// ...
```

Because arrays are frequently used we should have additional shorter syntax for declaring them (Alex M. agrees).

The exact syntax is open for discussion.

My proposal:
- basic use: `[][][]int{len:[2,3,2]}`
- advanced use `[][][]int{len:[2,3,2], init:1, cap:[10,20,10]}`

**Comment by ntrel** [comment]
I'm not sure this is common enough to have special syntax. We could have a generic function that does the same thing:
```v
a := md_array<[][]int>(len: [2, 3])
```
While that function can't be implemented ATM, V's compile-time abilities should be extended to support it.

Also, `init` should be an array too.
