### ISSUE TITLE
Issue with Discord server.

### ISSUE THREAD

**Issue by Jackojc** [vlang/v#608]
A lot of people are being banned from the Discord server purely for disagreement. You're making yourself look bad.

**Comment by JeppeSRC** [comment]
Yeah that ain't good at all.

**Comment by raresica1234** [comment]
Censorship won't help the server nor the language advance.

**Comment by medvednikov** [comment]
I don't ban for disagreement. I ban for posts like "LMAO this language is a joke". Those don't add anything to the discussion and only waste time.

**Comment by Jackojc** [comment]
Yeah which is strange because I did none of those.

**Comment by raresica1234** [comment]
Also the guy who agreed with Jack got banned.

**Comment by Jackojc** [comment]
I simply called you out on basically replying to everything with "If you want it to be fixed, contribute".

**Comment by medvednikov** [comment]
> I simply called you out on basically replying to everything with "If you want it to be fixed, contribute".

That is such a complete lie :) I never said that.

**Comment by qookei** [comment]
What about me getting banned? I pointed out issues with the language, and said that using the release date as a excuse was not valid since the language is much older than 3 days.

**Comment by JeppeSRC** [comment]
Some people just can't take critique no matter if it's too help you out or just to be a bitch.
