### ISSUE TITLE
vweb, return a given HTTP status code

### ISSUE THREAD

**Issue by smartiniOnGitHub** [vlang/v#6085]
Hi all,
in some cases it would be useful to specify an HTTP code for the reply, usually to specify (in the application) a specific HTTP error to return and maybe a custom message.
By default, status code would be 200 (HTTP OK), unless a different value is set by calling this function (`set_status` ?); so inside application code if I need to send a reply with a custom error message (and select the right mime type to use) I can use normal (already existing) functions.
Last, a check on the given code (to be in the range 100-600) would be good, as seen [here](http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml).

What do you think ?

I'd try to raise a PR with a draft implementation (during next days), but before I'd like to discuss if you like my proposal.

Thanks

**Comment by LouisSchmieder** [comment]
I think it would be useful to have a function to set the status, this should be enough and the custom message can be send via `vweb.text()`

**Comment by smartiniOnGitHub** [comment]
All done, thanks to all for the feedback.
For method chaining, let's see later. Bye
