### ISSUE TITLE
Wrong cgen with `go fn(){}()`

### ISSUE THREAD

**Issue by archyboy** [vlang/v#6088]
**V version:** 
0.1.29 664c26a

**OS:** 
Endeavouros / Arch Linux in VirtualBox VM on Windows 10 Pro
**What did you do?**

// hello.v
fn main() {
	go fn() {
		for {
			println("Hello V!")
		}
	}()
}

v run hello.v

**What did you expect to see?**
Hello V!
Hello V!
Hello V!
Hello V!
Hello V!
....... infinite loop
 
**What did you see instead?**
builder error: 
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

**Comment by ntrel** [comment]
I get:
```
C:\Users\CZASTK~1\AppData\Local\Temp\v\goerr.tmp.c: In function '_thread_wrapper':
C:\Users\CZASTK~1\AppData\Local\Temp\v\goerr.tmp.c:1803:3: error: expected expression before ')' token
  ();
   ^
```
