### ISSUE TITLE
Document the term module in standard library

### ISSUE THREAD

**Issue by snow-blade** [vlang/v#6091]
This is not really a feature request as it's me who wants to implement the feature; i want to document the term standard library so i would like to know if anyone is working on it so that i won't work for nothing.
Thanks

**Comment by Delta456** [comment]
Nobody is working on it right now. Feel free to work on it 😄

**Comment by snow-blade** [comment]
Thanks, i'm gonna start working on it tomorrow

**Comment by Delta456** [comment]
@snow-blade Good luck 😃

**Comment by snow-blade** [comment]
Thanks, i really love to document stuff

**Comment by Delta456** [comment]
Done in https://github.com/vlang/v/commit/fa11e124ddf01ce2af52ec57101a99ad0199e3b0

Thanks @snow-blade
