### ISSUE TITLE
Multipart Request Processing (vweb)

### ISSUE THREAD

**Issue by cyclecraze** [vlang/v#6094]
A webserver basic. Thank you!

**Comment by Olprog59** [comment]
Please!! I try send multipart file but without effects.

**Comment by cyclecraze** [comment]
It was working in October... have not checked today

`module main

// 10/10/20
// replaced with caddy plugin 
// keep for reference

import vweb
import time
import os

struct App {
pub mut:
	vweb vweb.Context
}

fn main() {
	vweb.run<App>(8080)
}

pub fn (mut app App) index() vweb.Result {
	app.vweb.add_header("Content-Type","text/html; charset=utf-8")
	println(time.now().format())
	app.vweb.text(time.now().format())
	return vweb.Result{}
}

pub fn (mut app App) init() {

}
pub fn (mut app App) init_once() {
	// do nothing

}

pub fn (mut app App) new() vweb.Result {
	return $vweb.html()
}

[post]
['/upload']
pub fn(mut app App) upload() vweb.Result {
	//println(app.vweb)
	app.vweb.text("ok dude")
	return vweb.Result{}	
}

// vweb.Result is mandatory
[post]
['/save']
pub fn(mut app App) save_schedule() vweb.Result {
	app.vweb.add_header("Access-Control-Allow-Origin", "*")
	app.vweb.add_header("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE")
	app.vweb.add_header("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")
	app.vweb.add_header("Content-Type","text/plain; charset=utf-8")
	//println(app.vweb.form)

        // more than one form parameter with same name, 'json_file'
	for json_file, payload in app.vweb.form {
		//todo: ensure such file exists
		mut file := os.open_file("public${json_file}", "a+", 0o666) or { panic(err)} // overwrite
		file.writeln(payload)
		file.flush()
		file.close()
	}
		
	app.vweb.text("ok")
	//app.vweb.redirect('/new') // connection reset of this line missing
	return vweb.Result{}
}



`

**Comment by smartiniOnGitHub** [comment]
I think PR #8160 should implement it ...

**Comment by smartiniOnGitHub** [comment]
@LouisSchmieder in your implementation of file upload (thanks for the PR !) will it be possible to specify a max file size (if needed, different than default one) ? Usually a max buffer size (not too big) is set by default, for example look [here](https://khalidabuhakmeh.com/increase-file-upload-limit-for-aspdotnet). 
All this to avoid attacks trying to crash the webapp (consuming too much memory) with huge files.
Thanks. bye

**Comment by LouisSchmieder** [comment]
I've to look for now because I want to get it first running with autofree maybe after it
