### ISSUE TITLE
os.args always empty

### ISSUE THREAD

**Issue by maassg** [vlang/v#610]
version 0.1.2

v run script.v  1, 2, 3
V panic: 3 doesn't exist

**Comment by medvednikov** [comment]
os.args don't work with `v run` right now

`v script.v && ./script.v`

**Comment by maassg** [comment]
It seems that os.args does not work at all for the moment!

**Comment by Henrixounez** [comment]
Everything works fine if you do a `make clean` then a `make` to update your V @maassg

**Comment by Henrixounez** [comment]
You can now use `v run file.v arg1 arg2 ...`

**Comment by maassg** [comment]
It works with entry point fn main() as expected, otherwise it does not.

Even this way:

import os

fn foo(){
   for arg in os.args {
     println( arg )
  }  
}

fn main(){
  foo()  
}

**Comment by spytheman** [comment]
Minimal fail case (it always prints []):
```
import os
println(os.args)
```

When there is main, it works fine:
```
import os
fn main(){
  println(os.args)
}
```
