### ISSUE TITLE
Built In Microservices

### ISSUE THREAD

**Issue by supanadit** [vlang/v#6106]
It sound amazing when i saw this programming language has built in ORM and Web Framework, but it could be fantastic and the complete solution for everyone if this programming language has built in Micro Services.

And if the micro services is included i will suggest my company use this programming language, and of course as software architect i have control to give some new technology become more popular by using it, and share it to the employee to learn it.

**Comment by JalonSolov** [comment]
You should check into vweb.  It has the pieces you need to create a microservice.

Tutorial:  https://github.com/vlang/v/blob/master/tutorials/building-a-simple-web-blog-with-vweb.md
Large project that uses it:  https://github.com/vlang/gitly
Examples: https://github.com/smartiniOnGitHub/vweb-example
