### ISSUE TITLE
Post Request types not working

### ISSUE THREAD

**Issue by Danushka96** [vlang/v#6123]
**V version: V 0.1.29 64e8125** 
**OS: Ubuntu** 

**What did you do?**
I created an application according to this guide on V [vweb_example](https://github.com/vlang/v/blob/master/tutorials/building-a-simple-web-blog-with-vweb.md)
In this, there's a function that accepts form submit as a POST request type.

```
pub fn (mut app App) new_article() vweb.Result {
        println('inside the new Article')
	title := app.vweb.form['title']
	text := app.vweb.form['text']
	if title == '' || text == ''  {
		app.vweb.text('Empty text/title')
		return vweb.Result{}
	}
	article := Article{
		title: title
		text: text
	}
	println(article)
	sql app.db {
		insert article into Article
	}
	app.vweb.redirect('/')
	return vweb.Result{}
}
```

**What did you expect to see?**
Save new Article in the DB and redirect back to the home page
 
**What did you see instead?**
404 Not Found for post request
Not even the 'inside the new Article' is printing.
But when it's a GET request it shows 'Empty text/title' line,

**Comment by JalonSolov** [comment]
Try adding the `[post]` attribute above the routine, like so:
```
[post]
pub fn (mut app App) new_article() vweb.Result {
...
```

**Comment by Danushka96** [comment]
@JalonSolov Thank you for the reply, But it's not working,

**Comment by medvednikov** [comment]
I need to update the code of the tutorial and add it to CI

**Comment by pavi2410** [comment]
I'm trying out vweb. So far, I'm quite positive about it 👍 

There's an issue that `[post]` doesn't work as expected.

```
[post]
['/nacho/:banana']
pub fn (mut app App) json_endpoint(yes string) vweb.Result {
	return app.vweb.json('{"a": 3,"yes":"$yes"}')
}
```

Using `V 0.1.30 89ef316` on Win 10

**Comment by mcastorina** [comment]
Using V 0.2.2 6e589e2 works as expected.
