### ISSUE TITLE
size_t lacks basic functionality

### ISSUE THREAD

**Issue by ntrel** [vlang/v#6139]
**V version:** git master
**OS:** Windows 8

**What did you do?**
```
>>> s := size_t(1)
>>> s
cgen error: could not generate string method size_t_str for type 'size_t'
>>> s != 0
error: infix expr: cannot use `any_int` (right expression) as `size_t`
    6 |
    7 | s := size_t(1)
    8 | s != 0
      |   ~~
>>>
```

**What did you expect to see?**
```
1
true
```
**Other problems**
c6a15dba50674c660dfa4207e6d8726d45b3d03b inserted `size_t` to `table.Kind` but it didn't update most of the other type indexing code in `atypes.v` so I think it gets treated as a bool sometimes:
```diff
 	char
+	size_t
 	bool
```
**Proposal**
Perhaps we could use e.g. `$if x64` to define `size_t` as a type alias, avoiding having to handle it in the compiler.

**Comment by Gladear** [comment]
fixed in cc8ee5f, use `usize` instead
