### ISSUE TITLE
Support closures

### ISSUE THREAD

**Issue by oscarryz** [vlang/v#6148]
It would be nice if V supported closures, that way an anonymous functions could access the scope where they're defined.

e.g 
```v
i:=1
fn(){
    println(i)
}()
``` 
Currently this code breaks the compiler (see #6147)

Examples of closures in action: [Go](https://play.golang.org/p/ZgC62VCDSI3) and [Rust](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e4f401f5f3d8e6a75e6baecba08edf2e)

**Comment by Gladear** [comment]
Closures will be supported, see issue #4753 for tracking implementation (although it's not a priority right now)
