### ISSUE TITLE
Bootstrapped V compiler panics in non-standard environment

### ISSUE THREAD

**Issue by Chiiruno** [vlang/v#615]
**V version:**  0.1.3
**OS:** NixOS
**C compiler version:** GCC 7.4.0

**What did you do?**
Attempt at making a package for V in nixpkgs.

**What did you expect to see?**
Successful V bootstrapped compiler compiling the new compiler.
 
**What did you see instead?**
```
Looks like you are running V for the first time.
Setting VROOT to "/build/source".
time__ticks
0
pass=2 fn=`time__ticks`
panic: time_lin.v:9
undefined: `double`
```

Doesn't happen locally, tested with success, however this didn't happen with the nix build environment before 0.1.3 AFAIK.
See: https://github.com/NixOS/nixpkgs/commit/175f555f06784ddceebc7b7c36eb62037e63731e

**Comment by fabulousduck** [comment]
I've experienced this bug too trying to build this. As this might happen to a few of people now, I'm gonna make #616 the main issue thread for this bug. please refer to #616
