### ISSUE TITLE
Regression: Cannot use backticks in #flag

### ISSUE THREAD

**Issue by trufae** [vlang/v#6150]
**V version:** V 0.1.29 0c7d73c
**OS:** macOS 10.15

**What did you do?**

```go
$ cat jjjj.v
#flag `echo -O3`
// #flag -O3

fn main() {
    eprintln('Works')
}
$
```

**What did you expect to see?**

 the program compiled with -O3

**What did you see instead?**

Compile time error because backticked-expressions are not evaluated.

This was working few weeks ago and it's specially problematic when trying to use pkg-config or python-config. I have been trying to find out which commit introduced the regression, but it doesnt seems to be possible to build non-master commits of V.

**Comment by medvednikov** [comment]
There's a big security problem with evaluating it without any filtering.

```
#flag `rm -rf ...`
```

**Comment by trufae** [comment]
Bold way to call a feature. Maybe we can filter that string to restrict to some commands and forbid ; and other shell problematic chars

**Comment by medvednikov** [comment]
Yeah

**Comment by trufae** [comment]
Any proposal for this? I think its quite important to support pkgconfig.

**Comment by trufae** [comment]
The GTK module is also affected: https://github.com/vgtk/vgtk3/blob/master/gtk/gtk3_nix.v

Btw, I'm writing a pkg-config module that could be integrated into the V compiler, so we cn have a #pkgconfig directive that uses this API instead of depending on executing any external program. This way it will be safer.

For sdl-config we can just use #pkgconfig sdl

I would appreciate some feedback on the API as well as if anyone is willing to integrate that into the compiler

**Comment by Larpon** [comment]
Also seen usage of `sdl-config` more than 1 place

**Comment by trufae** [comment]
I have updated my pkg-config implementation in V, it is now ready for 3rd party usage, iw ill probably make it 100% compatible along this week. (missing commandline flags) but at API level we should be good with the current state.

**Comment by Larpon** [comment]
@trufae I'll close this as solved. I hope that's ok with you - otherwise just reopen 🙂

**Comment by trufae** [comment]
Yep! solved :)
