### ISSUE TITLE
V compiler fails to build

### ISSUE THREAD

**Issue by fabulousduck** [vlang/v#616]
**V version: 0.1.2** 
**OS: Linux 18.16 Ubuntu 18.04** 
**C compiler version: 7..40** 

**What did you do?**
Try to build the compiler with `make`.

**What did you expect to see?**
A message that i have successfully built the compiler
 
**What did you see instead?**
```
cc -std=gnu11 -w -o v v.c
./v -o v .
time__ticks
0
pass=2 fn=`time__ticks`
panic: time_lin.v:9
undefined: `double`
Makefile:4: recipe for target 'v' failed
make: *** [v] Error 1
```

**Comment by fabulousduck** [comment]
c545bc62a78fdb8a6b375bcf1a8b0652d74b2d83 should be a fix

**Comment by Chiiruno** [comment]
Looks like it.
Should probably bump to 0.1.4.

**Comment by fabulousduck** [comment]
So my problem was that i had a old symlink to `0.1.2` which the make file was using to build the new version. Are you trying to build the compiler a second time somewhere else @chai2010 
?

**Comment by medvednikov** [comment]
I've added information about what to do when this happens:

https://github.com/vlang/v/commit/6a2afa1cfe17bb21896793f86d269e478e40ede0

This hint will be shown every time V can't be compiled.

**Comment by MostHated** [comment]
I was using this as of yesterday:

```
git pull origin master
cc -w -o vc v.c 
./vc -o v .
```
But today it gave me: 

```
V panic: "/home/mosthated//code/v//builtin/smap.v" doesnt exist
```

**Comment by Bowero** [comment]
This has been resolved. Thanks everyone for helping.
