### ISSUE TITLE
Appending to struct member array doesn't work

### ISSUE THREAD

**Issue by ntrel** [vlang/v#6165]
**V version:** git master
**OS:** Windows 8

**What did you do?**
```v
struct S1 {
mut:
	a []int = [7]
}

fn main() {
	mut s := S1{}
	b := [s]
	assert b[0].a == [7]
	s.a << 8
	assert b[0].a == [7,8] //fails
	assert b[0].a == [7] //passes!
}
```

**What did you expect to see?**
no assert failure

**Comments**
Same happens even without using default field initializer.

**Comment by Alfex4936** [comment]
Hello!

<code>mut s := S1{}</code> will give you <code>S1 {    a: [7] }</code>

and b is initialized as <code>[S1 {    a: [7] }]</code>, 

so if you wanna append value 8 and assert b[0].a,


Did you try this? (<code>b[0].a << 8</code> rather than <code>s.a << 8</code>)

```v
fn main() {
	mut s := S1{}
	mut b := [s]
	assert b[0].a == [7]
	b[0].a << 8
	assert b[0].a == [7,8]  // now it passes
}
```

**Comment by ntrel** [comment]
@Alfex4936 you're right, thanks
