### ISSUE TITLE
Problem with CMD window when runing .exe - how to turn of the cmd?

### ISSUE THREAD

**Issue by ManPython** [vlang/v#6181]
**V version:** V 0.1.29 eabc2da
**OS:** W7x64 Sp..

**What did you do?**
I compiled example tetris.v

**What did you expect to see?**
I expect tetris.exe as app only
 
**What did you see instead?**
With this app and other always have cmd window with logs. How to turn of?
As reported other example by @serkonda7 this is not spoted on W10 and LNX, but I have this constant on W7
https://github.com/vlang/ui/issues/195#issuecomment-676516288
Is required in V compilation some parameters aditionaly as external or internal changes?

Instead of cmd log it can be nice to log cmd output to file with flush.
https://github.com/vlang/ui/issues/205
Eg. exe is crashed, cmd closed, but logs can be in txt in other way we must run .exe in some external console conected to cmd terminal maybe..

**Comment by pavi2410** [comment]
I do not see the cmd window using `v calculator.v`, while there is a cmd window when using `-prod` flag.

```
C:\...\ui\examples>v doctor
OS: windows, Microsoft Windows 10 Home Single Language v19042 64-bit
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
CC version: N/A

getwd: C:\...\ui\examples
vmodules: C:\Users\Pavitra\.vmodules
vroot: C:\v
vexe: C:\v\v.exe
vexe mtime: 2021-02-02 06:41:27
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 9a2820f

Git version: git version 2.28.0.windows.1
Git vroot status: weekly.2021.5-21-g9a2820fa (33 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 2919963a
```

**Comment by danieldaeschle** [comment]
Should be fixed now.
