### ISSUE TITLE
Compiler panic when returning a generic struct

### ISSUE THREAD

**Issue by Noctember** [vlang/v#6183]
**V version:** 0.1.29 9b171b7
**OS:** Windows 10 v2004

**What did you do?**
```
struct St<T> {
}

fn main() {
	_ := new<int>()
}

fn new<T>() St<T> {
	return St<T>{}
}
```

**What did you expect to see?**
Nothing, this should compiler and run
 
**What did you see instead?**
The compiler panicked (see https://im.farfrom.world/dvzekithsj.png)

**Comment by nedpals** [comment]
Closed. Fixed in the latest version of V: https://devbits.app/play/kdSbpNHMpK6r
