### ISSUE TITLE
v help causes "Unknown help topic"

### ISSUE THREAD

**Issue by ChildishGiant** [vlang/v#6186]
**V version:** V 0.1.29 ce4ee2b 
**OS:** Manjaro Linux x86_64 

**What did you do?**
v help

**What did you expect to see?**
help text
 
**What did you see instead?**
```[allie@allie-manjaro dimmer]$ v help
V Error: Unknown help topic provided. Use `v help` for usage information.
```

**Comment by medvednikov** [comment]
Fixed.
