### ISSUE TITLE
[GitHub]: Don't delete old releases if possible

### ISSUE THREAD

**Issue by Chiiruno** [vlang/v#619]
It breaks packages that use the release archives instead of the global git revision, including any related release files.

**Comment by medvednikov** [comment]
Sorry, what do you mean by "use release archives"?

**Comment by ndac-todoroki** [comment]
I am maintaining the V plugin for asdf version manager (https://github.com/ndac-todoroki/asdf-v/), and the default way to install a certain version of V is to specify a name of the release.

```
asdf list-all v
```
will parse the releases page and list the released tags. Then,
```
asdf install v 0.1.2
```
will download the tar.gz (and the corresponding v.c from the vc repo), and compiles it.
This way users can have multiple V versions available on their machines.
Having multiple V versions on their computers is useful, when trying new versions, or relying on old releases on old projects.

To achieve this the releases should be not deleted (if not critical, such as a wrong release). While users can do `asdf install v ref:commit_hash`, it will not appear on the list-all command, and s/he should know the exact commit hash from the vlang/v git repo (and vc repo).

**Comment by prologic** [comment]
> Sorry, what do you mean by "use release archives"?

He means [this page](https://github.com/vlang/v/releases) -- So far you've managed to delete every single previous rebased versions.

Please keep them -- Tools will break if you continue to do this going forward :)

**Comment by SleepyRoy** [comment]
@medvednikov 
This feature request is nice and should be considered. In the future some software or tools might depend on specific versions of V and it's necessary to make them available. Old versions have bugs, but this doesn't mean they're completely useless.
For example, now the latest version is 0.1.3, but a tool which doesn't update frequently may depend on 0.1.2.

**Comment by medvednikov** [comment]
V is on a rolling release right now. It's being changed dramatically every day.

Things are not going to work with old versions of V.

Once things stabilize  by 0.2, I'll keep old releases. By the way, the vc repo has the entire history: https://github.com/vlang/vc/commits/master

**Comment by medvednikov** [comment]
Also the GitHub releases you referenced didn't work at all. They were broken, that's why there was no link to them on the home page.

I'll keep all GitHub releases from now on.

**Comment by Chiiruno** [comment]
That's what I wanted! Thanks!
