### ISSUE TITLE
JSON syntax

### ISSUE THREAD

**Issue by ntrel** [vlang/v#62]
I suggest the current syntax:
`json.decode(User, data)`
changes to:
`json.decode<User>(data)`

This is more consistent, as types cannot be values in V AFAIK. It also allows for the possibility that V will be able to implement `json.decode` as a generic function, with some future features.

**Comment by ntrel** [comment]
As an example of `decode<T>` in V:
V already supports compile-time function execution. That could generate a string which could be turned into code (see [D string mixins](https://tour.dlang.org/tour/en/gems/string-mixins)). The function would need a way of getting field names and types from a `struct`, and getting the element type of an array. This would all be slower to compile than implementing `decode` in the compiler, but these features are more flexible and powerful. It also means any other vendor implementing a V compiler doesn't need to implement `decode` if they include a library function instead (which might already exist by the V community).

**Comment by medvednikov** [comment]
I'm not sure which syntax I prefer yet.

But I agree, that it should not be part of the compiler. Everyone will be able to write such code executed at compilation time.

**Comment by medvednikov** [comment]
As of 0.0.5 `json.decode<User>(data)` syntax is used.

**Comment by ntrel** [comment]
Great!
