### ISSUE TITLE
Can't run v up

### ISSUE THREAD

**Issue by ChildishGiant** [vlang/v#6200]
**V version:** V 0.1.28 bbaf6e3 (Installed from latest release)
**OS:** Windows 10 N v 2004

**What did you do?**
`v up`

**What did you expect to see?**
V to update successfully 
 
**What did you see instead?**
```
PS F:\code\vlog> v up
Updating V...
Building V
Cloning vc...

Attempting to build v.c with GCC...
 > GCC not found

Attempting to build v.c with MSVC...


Failed to compile - Create an issue at 'https://github.com/vlang/v' with the following info:

v_win.c
vc\v_win.c(234): fatal error C1083: Cannot open include file: 'inttypes.h': No such file or directory

Exiting from error
V panic: exec failed (CreateProcess): The system cannot find the file specified.
 cmd: v cmd/tools/vup.v
C:/Users/allie/AppData/Local/Temp/v/vup.tmp.c:6036: at print_backtrace_skipping_top_frames_tcc: Backtrace
C:/Users/allie/AppData/Local/Temp/v/vup.tmp.c:5997: by print_backtrace_skipping_top_frames
C:/Users/allie/AppData/Local/Temp/v/vup.tmp.c:5785: by print_backtrace
C:/Users/allie/AppData/Local/Temp/v/vup.tmp.c:5803: by v_panic
C:/Users/allie/AppData/Local/Temp/v/vup.tmp.c:15689: by wmain
00461178 : by ???
004612db : by ???
7ffd67426fd4 : by ???
Unhandled Exception 0xC0000005
C:/Users/allie/AppData/Local/Temp/v/vup.tmp.c:6036: at print_backtrace_skipping_top_frames_tcc: Backtrace
C:/Users/allie/AppData/Local/Temp/v/vup.tmp.c:5997: by print_backtrace_skipping_top_frames
C:/Users/allie/AppData/Local/Temp/v/vup.tmp.c:6059: by unhandled_exception_handler
7ffd67fc802c : by ???
The system cannot find the path specified.
```

It says vup can't be found but it's there in the v install
![image](https://user-images.githubusercontent.com/13716824/90982938-81797d80-e562-11ea-9e78-19b5b951404b.png)

**Comment by JalonSolov** [comment]
Is there a vup.exe (the compiled version)?

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/90990597-a4278880-e59a-11ea-9dd4-830d083fc606.png)
Nope, no compiled files.

**Comment by JalonSolov** [comment]
0.1.29 is the latest release, not 0.1.28.  It has the compiled files in it.

**Comment by ChildishGiant** [comment]
Just downloaded from https://github.com/vlang/v/releases/latest/download/v_windows.zip and it still seems to not have them.
![image](https://user-images.githubusercontent.com/13716824/90992295-a2fc5880-e5a6-11ea-919c-5a416c733bf0.png)

**Comment by bashery** [comment]
Is GCC installed ?? The error indicates that it is not installed.

**Comment by ChildishGiant** [comment]
GCC isn't but MSVC is

**Comment by medvednikov** [comment]
https://github.com/vlang/v/issues/6928
