### ISSUE TITLE
git error on V compilation.

### ISSUE THREAD

**Issue by AqilCont** [vlang/v#6207]
**V version:** 702a80f
**OS:** Win 10 2004

**What did you do?**
Run `make`

**What did you expect to see?**
It successfully compile.
 
**What did you see instead?**
This:
![image](https://user-images.githubusercontent.com/32044067/90995814-185a3000-e58b-11ea-9a69-4a0fb73abc49.png)

You should probably fix this xd

P.S. New comp so I don't have GCC yet(I'm such a noob ;-;) but just wanted to report this error

**Comment by JalonSolov** [comment]
Looks like Windows.  Try `.\make.bat -tcc` - that should install the tcc compiler for you.

**Comment by AqilCont** [comment]
Oh I installed GCC afterwards but just pointing out that its failing to download TCC.

**Comment by JalonSolov** [comment]
Hmm... I didn't work on that... not sure if the Windows version is supposed to download tcc automatically, or if you have to specify the switch.  Someone will check into it for sure.
