### ISSUE TITLE
Duplicate method when import module in two places

### ISSUE THREAD

**Issue by Perkovec** [vlang/v#6210]
**V version:** 0.1.29
**OS:** Ubuntu 18.04

**What did you do?**
I'm trying to compile project with local version of https://github.com/nedpals/vex. Example workspace https://github.com/Perkovec/vlang-bug

**What did you expect to see?**
It successfully compile.
 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/7426664/91020553-424b3b00-e5fb-11ea-9911-e07964732033.png)
When I delete line with `import vex.ctx` (and related code to this import in `main.v`) it succesfully compile. Looks like this error caused because `cxt` is imported in `vex.server` module too

**Comment by Larpon** [comment]
Could be related to #6289 

Attached reproducible [double_import.zip](https://github.com/vlang/v/files/5377741/double_import.zip)
CC @spaceface777

**Comment by ArtemkaKun** [comment]
Hi @Perkovec ,

any ideas on how I can reproduce that bug with fresh vex and V?
For your example repo I have an error

```
[🔴] × v run .
./main.v:7:18: error: unknown function: nedpals.vex.server.new
5 |
6 | fn main() {
7 |     mut s := server.new()
  |                     ~~~~~
8 |
9 |     s.get('/', fn (req ctx.Req, mut res ctx.Resp) {
```

**Comment by medvednikov** [comment]
Fixed.
