### ISSUE TITLE
Handle memory allocation failures

### ISSUE THREAD

**Issue by Undumendil** [vlang/v#622]
https://github.com/vlang/v/blob/master/builtin/builtin.v#L78
https://github.com/vlang/v/blob/master/builtin/builtin.v#L87
https://github.com/vlang/v/blob/master/builtin/array.v#L167

Panics/segfaults/leaks because of temporary memory issues should be avoided; at least in builtin modules. Keeping some pre-allocated memory may solve most of such cases.

**Comment by medvednikov** [comment]
If there's an out of memory error, the application should exit. That's how it works right now.
