### ISSUE TITLE
How can I build my module for 32 bit architecture?

### ISSUE THREAD

**Issue by devlexanderxyz** [vlang/v#6220]
I have my makefile configured like so.

```make
default: build

build:
	v -shared -prod samp.v
```

I would like to know how I can build this shared object for 32 bit architectures.
Thank you.

**Comment by JalonSolov** [comment]
Should only require installing a 32-bit C compiler and telling V to use that.

**Comment by devlexanderxyz** [comment]
Yes, I figured it out. Thank you.
`v -cflags -m32`.
