### ISSUE TITLE
Cannot use aliased string in function signature

### ISSUE THREAD

**Issue by Noctember** [vlang/v#6226]
**V version:** Win 10 2004
**OS:** 0.1.29 7879510

**What did you do?**
```
type Alias string

struct App {
	alias Alias
}

fn main() {
	app := App { "5" }
	app.alias.print()
}

fn (a Alias) print() {
	println(a)
}
```

**What did you expect to see?**
A working excecutable printing 5
 
**What did you see instead?**
`cgen error: could not generate string method for type 'main__Alias'`

**Comment by Delta456** [comment]
Fixed with the latest V

```v
type Alias = string

struct App {
	alias Alias
}

fn main() {
	app := App { "5" }
	app.alias.print()
}

fn (a Alias) print() {
	println(a)
}
```
