### ISSUE TITLE
[JSON] JSON method 'encode' has ambiguity

### ISSUE THREAD

**Issue by lhy0403** [vlang/v#625]
the JSON processor currently has methods named `*encode*`

I, Personally, suggest those to be renamed to `stringify` or `serialize` like what C# (`Newtosoft.Json` [Here](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonConvert.cs#L527)) or Javascript (`JSON.stringify`) does.

For me, `encode` is kind of converting an object to byte array, like UTF encode schemes.

Code at: https://github.com/vlang/v/blob/master/json/json_primitives.v#L93

**Comment by ndac-todoroki** [comment]
Go uses `Decode/Encode`, Rust uses `from_string/to_string`, Python uses `dumps/loads`, Ruby uses `parse/generate`, Swift uses `encode/decode`. I think `encode` is popular as well as `serialize`?

**Comment by lhy0403** [comment]
Ah, then it seems `encode` and `decode` is quite reasonable. Thanks, it must be my misunderstanding of those words.
