### ISSUE TITLE
cannot move files with mv ,directory is empty after running code

### ISSUE THREAD

**Issue by codeitlikemiley** [vlang/v#6255]
hey ive check this

https://github.com/vlang/v/blob/master/doc/docs.md#cross-platform-shell-scripts-in-v

so i tried to create a simple script 
i created a test.xt file

and a script deploy.vsh
```
#!/usr/bin/v run

mkdir('build')
mv('test.txt','build/')
```

im running it on my arch with this command

./deploy.vsh && ./deploy

ive check the build directory no file test.txt

looks like the os module is still not working properly for basic scripting....

i would love to try porting all my script to vlang but with this situation its impossible

**Comment by ylluminate** [comment]
As per Discord chat, @Larpon I agree, this should behave like a Unix `mv` since that would seem most universally predictable.

**Comment by Larpon** [comment]
@ylluminate - super. PR #6300 is ready

**Comment by ylluminate** [comment]
@codeitlikemiley let us know if you have any more trouble!
