### ISSUE TITLE
Question: Performance: within 3% of C meaning...

### ISSUE THREAD

**Issue by codeitlikemiley** [vlang/v#6256]
What do you mean by within 3% of C

this is a dumb quesiton but the statement is i dont know somewhat misleading or confusing
 
is it 3% of C when it comes to performance  (SLOW)

or 

97% of C when it comes to performance (FAST)

thanks in advance for the answer

**Comment by JalonSolov** [comment]
What would you think it meant if someone said "There's a gas leak within 5 kilometers of your house."  Would you think that meant it was more than 5 kilometers away?  Or no further than 5 kilometers away... or maybe even right in your house?

**Comment by JalonSolov** [comment]
Also see  #6229
