### ISSUE TITLE
Unexpected error from v fmt with sql identifier

### ISSUE THREAD

**Issue by donaldcallen** [vlang/v#6258]
**V version:**
V 0.1.29 d88e8bb 
**OS:**
64-bit Arch Linux, up-to-date as of this writing 

**What did you do?**
Tried to run v fmt on code I'm writing.

**What did you expect to see?**
Properly formatted code

 
**What did you see instead?**
dca@franz:~/Software/v_test$ ../v/v fmt lib.v > /tmp/lib.v
```
lib.v:49:9: error: expr(): bad token `:=`
   47 |         count = count + 1
   48 |     }
   49 |     sql := 'select a${count - 1}.guid from${from_clause[1..]} where ${where_clause[5..]}'
      |         ~~
   50 |     statement := &C.sqlite3_stmt(0)
   51 |     C.sqlite3_prepare_v2(db, sql.str, -1, &statement, 0)

vfmt error while formatting file: lib.v .
Encountered a total of: 1 errors.
```
This error makes no sense, at least to me.
[lib.v.gz](https://github.com/vlang/v/files/5145638/lib.v.gz)

**Comment by spaceface777** [comment]
`sql` is a keyword in V, so you cannot use it as a variable name.
Perhaps we should make the error message a little clearer.

**Comment by donaldcallen** [comment]
That would be helpful. It is also not listed in Appendix I: Keywords  in the documentation and should be.
