### ISSUE TITLE
Future of the build tooling

### ISSUE THREAD

**Issue by darkoverlordofdata** [vlang/v#626]
Currently v is using c as an il, it reminds me something of vala. I like that - using c as an il makes it simple to divert the build into an emscripten or android app. But can we count on this in the future? Is v planned to at some point to compile directly to native machine code rather than c?

**Comment by MostHated** [comment]
From the site: https://vlang.io/

```
Direct machine code generation is at a very early stage. Right now only x64/Mach-O is supported. This means that for now emitting C has to be used. By the end of this year x64 generation should be stable enough.
```

**Comment by darkoverlordofdata** [comment]
My question is will we be able to count on emitted c code in the future, or will it go away.

**Comment by MostHated** [comment]
Ohh, my bad.

**Comment by medvednikov** [comment]
Good question. I've updated the website:

```
Emitting C will always be an option, even after direct machine code generation matures.
```

https://vlang.io/
