### ISSUE TITLE
"Expression evaluated but never used"???

### ISSUE THREAD

**Issue by donaldcallen** [vlang/v#6268]
**V version:** 
V 0.1.29 5d3d14d
**OS:**
64-bit Arch Linux, up-to-date 

**What did you do?**
I wrote what I believe is a correct program.

**What did you expect to see?**
An executable.

 
**What did you see instead?**
```
dca@franz:~/Software/v_unscienfic$ ../v/v main.v
main.v:69:9: error: expression evaluated but not used
   67 |
   68 | fn main() {
   69 |     mut tree Tree := Tree {
      |         ~~~~
   70 |         none
   71 |     }
```
[main.v.gz](https://github.com/vlang/v/files/5146763/main.v.gz)

**Comment by JalonSolov** [comment]
Should be
```
mut tree := Tree {
    none
}
```
It is complaining because of the extra 'Tree' on the line before the `:=`.

**Comment by donaldcallen** [comment]
Yes. Thank you. I've written too much code in languages like Rust where types may optionally be specified when declaring a variable, which is apparently not the case in V.

I am going to leave this open, because the error message is completely unhelpful, not at all descriptive of what the problem was.

**Comment by ntrel** [comment]
The error could be `expected :=`, not `Tree`.
Doesn't Rust use `let mut name: Type`?

**Comment by donaldcallen** [comment]
The error message you propose would be a big improvement.

You have the Rust declaration right, where 'mut' is optional (immutable by default) and the type is optional. Also Rust variables
don't have to be initialized (you can make it mutable and set it after declaring), but the compiler will complain if you attempt to reference an uninitialized variable.

**Comment by medvednikov** [comment]
Fixed:
```
error: expecting `:=` (e.g. `mut x :=`)
    6 |
    7 | fn main() {
    8 |     mut test Test := Test{}
      |              ~~~~
    9 |     test.n=10
   10 | }
```
