### ISSUE TITLE
Is this async/await feature possible?

### ISSUE THREAD

**Issue by czlbaiyi** [vlang/v#627]
Is this async/await feature possible?
Do not like asynchronous callbacks。
thanks for yours reply。

**Comment by Immortalin** [comment]
It suffers from the red/blue problem, i.e. all your code becomes infected and forced to be async. 

http://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/

Perhaps we can find another way?

**Comment by czlbaiyi** [comment]
I need to think more about the article。thanks

**Comment by Immortalin** [comment]
Keep it open though, so there can perhaps be a discussion about it.

**Comment by aguspiza** [comment]
https://nim-lang.org/docs/asyncdispatch.html#multisync.m%2Cuntyped

**Comment by Bowero** [comment]
I will reopen the discussion and mark it accordingly. I want to inform you about this:
https://github.com/vlang/v/blob/c7e2c4a3536e1ae746e30b0eb546242f73c3ed44/compiler/fn.v#L430

**Comment by medvednikov** [comment]
V uses Go's approach to fix concurrency, not async/await.
