### ISSUE TITLE
vsh files have GLSL as associated language on GitHub

### ISSUE THREAD

**Issue by serkonda7** [vlang/v#6272]
**What did you do**
Language overview of https://github.com/serkonda7/v-sololearn-coding-challenges looks like this:
![image](https://user-images.githubusercontent.com/40118727/91668802-caf03c80-eb0f-11ea-8d2c-173fc0b3eae4.png)

**What did you expect to see**
Either 100% V or the small part being `vsh`

**What did you see instead**
The vsh file counts as `GLSL`

**Comment by leahlundqvist** [comment]
This seems like an issue more suited for [github/linguist](https://github.com/github/linguist)

**Comment by serkonda7** [comment]
Moved to https://github.com/github/linguist/issues/5039
