### ISSUE TITLE
Directive #include skipped if module not imported

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#6284]
**V version:** 
0.1.29

In the example attached:
`modb` has `#include <AL/al.h>`
`app` calls a function under `modb.submodb` module
`app.temp.c` is missing the `#include <AL/al.h>`
(I assume the `#flag` directive would also be ignored due to the same problem?)
[import_bug.zip](https://github.com/vlang/v/files/5152727/import_bug.zip)

Why is this a problem? A real example below
[test.tmp.c.txt](https://github.com/vlang/v/files/5152713/test.tmp.c.txt)
`ALCdevice` is defined but the respective header `Al/alc.h` wasn't included due to this bug.

**Comment by duarteroso** [comment]
Unless the include should be in every file that uses that C code. In that case it's fine, makes perfect C-ense, but the documentation isn't clear 👌

**Comment by spaceface777** [comment]
As far as I can see:
- You have a `module foo` with `#include`s a C header and wraps it.
- You have a separate, nested `module foo.bar`
- In your code, you only `import foo.bar`, but *do not* `import foo`

In that case, the current behavior is correct. `foo` is never imported, so the `#include`s in it are not included.   
A nested submodule does not automatically import its parent modules, they are completely independent.

To fix this, you would either need to:
1. `import foo` as well in your code
1. `import foo` inside `module foo.bar` (saves you an extra import in your code)
1. Combine the two modules into a single `module foo` / `module foo.bar`

*Note: I may have misunderstood your issue. If that's the case, please correct me.*

**Comment by duarteroso** [comment]
No that sounds like the issue I'm having.
But then [this](https://github.com/vlang/v/issues/6291) happens, I doubt it is the intended behaviour :)

**Comment by duarteroso** [comment]
Unless a submodule can have its own `fn init() {}` ? In which case I would be using modules in the wrong way 👍🏽

**Comment by spaceface777** [comment]
> Unless a submodule can have its own `fn init() {}` ?
They can as far as I know, if that doesn't work, *that*'s a bug. 

TL,DR: A submodule is completely independent from it's parent(s), so any `init`s / `#include`s in the parent module will not be included if you only import a child.

**Comment by duarteroso** [comment]
Can the documentation be more specific please? 👍🏽

**Comment by duarteroso** [comment]
@spaceface777 What about the `#flag` macro? Does it have to be declared in *every single* submodule?

**Comment by spaceface777** [comment]
It works the exact same way: it needs to be defined in *at least one* module that you import.
As I mentioned earlier, you could define it just once inside the present module and import that in every submodule.
