### ISSUE TITLE
Use `v fmt` by default on all code in `vlang/v`

### ISSUE THREAD

**Issue by pavel-kolesnikov** [vlang/v#6285]
Please use `v fmt` on the `vlang/v` itself.

**V version:** 35cbca9

**What did you do?**
`v fmt vlib\v\builder\cc.v`

**What did you expect to see?**
No changes.
 
**What did you see instead?**
File reformatted.

**Comment by serkonda7** [comment]
Some files formatting is already verified by CI. The remaining files will be formatted and verified part by part.

**Comment by ntrel** [comment]
There are bugs in vfmt that need fixing first.

**Comment by pavel-kolesnikov** [comment]
lets close this till vfmt ready.
/close
