### ISSUE TITLE
Module init not called

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#6291]
**V version:** 
0.1.29

It seems it is possible to skip the module initialisation function `fn init() {...}` completely.
[init_bug.zip](https://github.com/vlang/v/files/5158888/init_bug.zip)

Repro steps:
1) Create module with an `init` function
2) Create sub module
3) Create app that only calls the sub module functionality
4) You can have erroneous code in the `init` function, it will still happily compile and run

**Comment by spaceface777** [comment]
See #6284.
