### ISSUE TITLE
Build error OS X El Capitan

### ISSUE THREAD

**Issue by TheTechRobo** [vlang/v#6292]
When running `./v`...

https://pastebin.com/wYj1cKzT

Compiler version: 

```
$ cc --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Probable solution (by discord user spaceface):

>seems like the current monotonic clock implemetation will not work on macOS < 10.12: https://stackoverflow.com/a/5167506

On a related note:  
I tried `./v -cg` but it says `V error: unknown command`  
When I type `./v help` it says `V Error: Unknown help topic provided. Use 'v help' for usage information.`

**Comment by medvednikov** [comment]
That's unfortunate. Also hard to test, since I have the latest macOS, and it's impossible for me to install El Cap on my machine.
