### ISSUE TITLE
ORM C.backtrace error

### ISSUE THREAD

**Issue by amoyyy** [vlang/v#6295]
**V version:**  0.1.29 fe8286c
**OS:**  ubuntu20.04

**What did you do?**
```
import sqlite

struct User{
    id int
    age int
    name string
    salary f64
}

fn main(){
    for {
        db := sqlite.connect('users.db') or { panic(err) }
        db.exec("drop table if exists User")
	C.sqlite3_close(&db)
    }
}
```
**What did you expect to see?**
A running process with acceptable memory use.
 
**What did you see instead?**
V panic: sqlite db error
C.backtrace returned less than 2 frames
Segmentation fault

Is there a limitation on max ptr num in use?

**Comment by LouisSchmieder** [comment]
```v
import sqlite

struct User{
    id int
    age int
    name string
    salary f64
}

fn main(){
    for {
        mut db := sqlite.connect('users.db') or { panic(err) }
        db.exec("drop table if exists User")
        db.close() or { panic(err) }
    }
}
```
this code is now working so there shouldn't be a problem anymore. And no there is not limit for pointers
