### ISSUE TITLE
raii

### ISSUE THREAD

**Issue by zhuxiujia** [vlang/v#630]
for  more complex situations, use Rust/C++ RAII Instead of manual .free().
it can It prevents a lot of problems？

**Comment by superwhiskers** [comment]
please describe what you would like specifically. thanks

**Comment by zhuxiujia** [comment]
> please describe what you would like specifically. thanks

for more complex situations, use Rust/C++ RAII Instead of manual .free().
it can It prevents a lot of problems？

**Comment by ntrel** [comment]
RAII essentially means a struct can have a destructor function that is called automatically by V when a stack instance of that struct goes out of scope. It is very useful for automatic memory management of struct fields.

@zhuxiujia I suggest renaming this issue struct destructors.

**Comment by lutherwenxu** [comment]
Struct destructors are being discussed in #1325.
