### ISSUE TITLE
C:\v\vlib\builtin\array.v:374:11: error: please use `[unsafe]` instead

### ISSUE THREAD

**Issue by ChildishGiant** [vlang/v#6305]
**V version:** V 0.1.29 b015033
**OS:** Windows 10

**What did you do?**
Any v command, including building, v up and REPL

**What did you expect to see?**
Well that depends on the command 😉 
 
**What did you see instead?**
```
PS C:\Users\allie\Downloads> v 
For usage information, quit V REPL and run `v help`
cannot compile `C:\v\cmd\tools\vrepl.v`: 
C:\v\vlib\builtin\array.v:374:11: error: please use `[unsafe]` instead
  372 |
  373 | // pub fn (a []int) free() {
  374 | [unsafe_fn]
      |           ^
  375 | pub fn (a &array) free() {
  376 |     // if a.is_slice {
```

**Comment by Delta456** [comment]
@ChildishGiant Can you try doing a fresh clone and run it again because it seems to be fine here https://github.com/vlang/v/blob/master/vlib/builtin/array.v#L465

**Comment by ChildishGiant** [comment]
Huh that worked. I just reinstalled before running into this error but I guess that solves it.
