### ISSUE TITLE
cannot print recursive struct

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#6307]
**V version:** 
latest master

**OS:** 
win10

**What did you do?**
```V
struct Foo {
	bar &Foo
	baz int
}

fn main() {
	a := Foo{bar: &Foo{bar: 0, baz: 1}, baz: 2}
	println(a)
}
```

**What did you expect to see?**
a is printed
 
**What did you see instead?**
C error: implicit declaration of function 'indent_'

**Comment by nedpals** [comment]
Closed. Fixed in the latest V version: https://devbits.app/play/4WG3pWhQxHH4
