### ISSUE TITLE
V Language Mascot ?

### ISSUE THREAD

**Issue by batara666** [vlang/v#6309]

**Comment by nedpals** [comment]
This is something to be discussed in the future once all the goals have been accomplished

**Comment by Dialga** [comment]
Check out the new mascot, Veasel.

https://github.com/vlang/v-mascot

![veasel](/../../../../vlang/v-mascot/blob/main/veasel.svg?raw=true)

**Comment by FObersteiner** [comment]
`V` feels like go and Rust had a baby, so an [otter](https://en.wikipedia.org/wiki/Eurasian_otter) would have been more adequate, no? ^^

Great language btw., I'm very excited to see it grow further :)
