### ISSUE TITLE
`import const` assumes that all imported c constants are integers, regardless of type specified

### ISSUE THREAD

**Issue by superwhiskers** [vlang/v#631]
**V version:** gb00a47be
**OS:** linux
**C compiler version:** gcc 9.1.0

**What did you do?**
`main.v`
```vlang
module main

#include <stdio.h>

// hack to define the version variable at compile time
#ifndef VERSION
#define VERSION "unknown"
#endif
import const (
	VERSION string
)

fn main() {

	//C.printf('%s', VERSION) // <-- uncomment this line and comment the following to fix it
	println('$VERSION')

}
```
`Makefile`
```makefile
# get git commit information
VERSION := $(shell git describe --tags --match "v[0-9]*" --abbrev=8)

.PHONY: all
all: v

.PHONY: test
test:
        @find .. -name '*_test.v' | xargs v {}

.PHONY: clean
clean:
        @rm -f v v.c

v: #v.c
        @echo "" # @cc -std=gnu11 -w -o v v.c
        @v -o v .
        @cc -std=gnu11 -DVERSION="\"$(VERSION)\"" -w -o v ~/.vlang/v.c

v.c:
        @wget https://raw.githubusercontent.com/vlang/vc/master/v.c
```
run `make` in the directory with both of those files

**What did you expect to see?**
`v0.1.3-22-gb00a47be` (output of `git describe --tags --match "v[0-9]*" --abbrev=8`)
 
**What did you see instead?**
`-1949070991` (pointer address. it changes with each run, but it isn't the string i expect)

**Notes**
this requires a modified v compiler from #629 to build

**Comment by Bowero** [comment]
The `#` will be deprecated soon, so I wonder how much effort we should put into this.

**Comment by superwhiskers** [comment]
@Bowero `#` has nothing to do with the underlying issue

**Comment by Bowero** [comment]
```
/home/bowero/Documents/v_tests/test.v:8:0: bad token `#` (embedding C code is no longer supported)
```

It does change the issue now.

**Comment by medvednikov** [comment]
`import const` was removed from the language.

**Comment by superwhiskers** [comment]
@Bowero it didn't, it had nothing to do with `#`, i just used it that way

**Comment by superwhiskers** [comment]
you could import a c library and import constants from it. that doesn't require `#`
