### ISSUE TITLE
Unhandled Exception 0xC00000FD when compiling

### ISSUE THREAD

**Issue by vmcrash** [vlang/v#6310]
**V version:** V 0.1.29 4d2c8a4
**OS:** Windows 10

**What did you do?**
Ran "v main.v" on the attached file.

**What did you expect to see?**
A compiled file.
 
**What did you see instead?**
Unhandled Exception 0xC00000FD
Unhandled Exception 0xC0000005

[main.v.zip](https://github.com/vlang/v/files/5179261/main.v.zip)

**Comment by Gladear** [comment]
The 2 errors you have in you code are the following :
- you must replace `name String` by `name string`
- and `file_path := os.join_path(dir, file_path)` by `file_path := os.join_path(dir, file_name)`

Don't close the issue yet, as there is still a bug in the compiler 🙂

For v-devs:
I remember a solution was implemented for simple assignments (for example, `a := a` results in "error: undefined variable: `a`"), but a more generic solution that covers every case.

Example of other cases result in this exception:
```v
struct Coords { x int y int }
fn main() {
	c := Coords{c, c}
}
```

```v
fn func(a int) { return a }
fn main() {
	c := func(c)
}
```

```v
fn main() {
	c := int(c)
}
```

**Comment by vmcrash** [comment]
Thanks. I've already found out the problems with my code and was now in the mood to revise this bug about the essential part of the problem - but you were faster. :)

**Comment by danieldaeschle** [comment]
@Gladear your second example is fixed now. For the other examples there is this: https://github.com/vlang/v/issues/5535

because the initial bug report works now I will close this.
