### ISSUE TITLE
base64.v doesn't compile

### ISSUE THREAD

**Issue by coolreader18** [vlang/v#632]
**V version:** 0.1.3
**OS:** Linux Mint
**C compiler version:**  n/a

**What did you do?**
Run `make test` in `compiler/`

**What did you expect to see?**
Tests passing
 
**What did you see instead?**
`base64.v` didn't build, giving me this:
```
➜ make test
find .. -name '*_test.v' | xargs v {}
PREV==
NEXT=NAME
pass=2 fn=`base64__decode`

====================
It looks like you are building V. It is being frequently updated every day. Most likely there was a change that lead to this error. 
Try to run `git pull`, that will most likely fix it.
If `git pull` doesn't help, re-install V from source or download a precompiled binary from https://vlang.io
====================

panic: base64.v:28
unexpected token: `for`
Makefile:11: recipe for target 'test' failed
make: *** [test] Error 123
```
I'm not sure what's happening here, it seems like a weird compiler syntax bug.

I've pulled the compiler, yadda yadda yadda, and `v` itself builds fine.

**Comment by kostya** [comment]
`i += 4` not compiled in line `for i := 0; i < L; i += 4 {`, parser bug?
