### ISSUE TITLE
File read API: pass byte array to read_bytes_at?

### ISSUE THREAD

**Issue by tmssngr** [vlang/v#6322]
Right now the API of reading files byte-wise as a block is
```
fn (f &File) read_bytes(size int) []byte
fn (f &File) read_bytes_at(size, pos int) []byte
```
That way, an array always needs to be created for each method invocation. Why not pass the array:
```
fn (f &File) read_bytes(mut []byte) int
fn (f &File) read_bytes_at(mut []byte, pos int) int
```
?

**Comment by ntrel** [comment]
Good idea. I'd also swap the parameter order: `pos int, mut buf []byte`. Because `pos` is needed first before `buf`.

**Comment by tmssngr** [comment]
My suggestion is based on the [Java `InputStream.read` API](https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html), where the number of read bytes is returned. IMHO it makes sense to stick with well-known and proven API.

**Comment by Delta456** [comment]
We trend to follow Go's style.
