### ISSUE TITLE
returnning ?void doesn't enforces or block

### ISSUE THREAD

**Issue by trufae** [vlang/v#6330]
**V version:** V 0.1.29 2cb711e
**OS:** macOS 10.15

**What did you do?**

```
$ cat bum.v
fn foo() ? {
}

fn main() {
	foo()
}
$ v run bum.v
$
```

also hwen ssigning it to a variable:

```go
$ cat bum.v
fn foo() ? {
}

fn main() {
	a := foo()
}
$ v run bum.v
bum.v:5:2: warning: unused variable: `a`
    3 |
    4 | fn main() {
    5 |     a := foo()
      |     ^
    6 | }
bum.v:5:7: error: foo() returns an option, but you missed to add an `or {}` block to it
    3 |
    4 | fn main() {
    5 |     a := foo()
      |          ~~~~~
    6 | }
$
```

so it is possible to write buggy code like this:

```go
$ cat bum.v
fn foo() ? {
	return error('unhandled')
}

fn main() {
	foo()
}
$ v run bum.v
$
```

**What did you expect to see?**

 an error about missign or block

**What did you see instead?**

no error, so invalid c

**Comment by Gladear** [comment]
This seems to be voluntary (the line causing the issue is the following: https://github.com/vlang/v/blob/master/vlib/v/checker/checker.v#L1443)
@medvednikov Were they any reason not to enforce handling optionals in statements ?

**Comment by spaceface777** [comment]
This has been fixed.
