### ISSUE TITLE
Reconsider method overloading

### ISSUE THREAD

**Issue by tmssngr** [vlang/v#6333]
I'm coming from Java background and I'm used to overload methods that belong together, e.g. `string.indexOf(char)`, `string.indexOf(char, int)`, `string.indexOf(String)` and `string.indexOf(String, int)` (see [Java String API](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html)) That way I just need to remember one method name (`indexOf`) instead of 4 method names. With the current restriction of not being able to overload, the method names only get longer, not necessarily more precise, because lazy developers then rather tend to add numbers, e.g. `index_of`, `index_of2`, `index_of3` just for making the compiler happy. Things that just are done to work a limitation of the compiler should be avoided.

Or consider the typical methods `max(int, int)`, `max(byte, byte)`, `max(float, float)`, ...

I'm working with Java now for >20 years and as long as I remember method overloading never caused any trouble for us.

**Comment by ntrel** [comment]
> max(int, int), max(byte, byte), max(float, float)

max<int>, max<byte>, max<float>

> method overloading never caused any trouble 

It complicates tooling. 
It can interact with implicit conversions with unpredictable results. In V there aren't many implicit conversions ATM though, but strict encapsulation is planned.
It affects what features you can have with functions, e.g. return type inference.

**Comment by medvednikov** [comment]
Sorry @tmssngr I know how useful overloaded functions can be, but it is one the fundamental parts of V's design.

Just like in C and Go.
