### ISSUE TITLE
Integer literal overflow not reported

### ISSUE THREAD

**Issue by tmssngr** [vlang/v#6334]
**V version:** 26971da
**OS:** Win10

**What did you do?**
Run following code
```
fn main() {
	a := 1000000000000
	println(a)
}
```

**What did you expect to see?**
I expect to either get an error on compilation or the value `1000000000000` been printed.
 
**What did you see instead?**
```
C:\v-test>v run test.v
-727379968
```

**Comment by medvednikov** [comment]
Good find. It should print 1000000000000 and assign a correct type, like in Go.

**Comment by Gladear** [comment]
Just an idea: it could compile but print a warning saying that the number was implicitly converted to `i64`/`u64` (whatever type) and ask the user to do the cast explicitly ?

**Comment by Delta456** [comment]
Yeah I agree with @Gladear and it will also increase readability.

**Comment by tmssngr** [comment]
In Java such literals will result in a compiler error unless you add the suffix `l` (or better `L`) for *long* numbers.

**Comment by medvednikov** [comment]
Yeah, explicit is good. We don't have suffixes, we use `i64(100....)` instead.

**Comment by medvednikov** [comment]
It's easier this way, suffixes is another thing to learn and remember.

**Comment by SleepyRoy** [comment]
I remember this behavior is on purpose - an integer number is always `int` unless you explicitly give another type.

**Comment by dumblob** [comment]
Please reopen:
```v
fn main(){
  println(1000000000000)
  println( 1000_000_000_000_000_000_000_000_000 )
  println( 1000_000_000_000_000_000_000_000_000.0 )
}

```
prints:
```
1000000000000
-6930898827444486144
1.e+27
```

**Comment by dumblob** [comment]
Please reopen:
```v
master 0$ ./v run ../test01.v 
../test01.v:2:25: error: integer literal 1000000000000000000000000000 overflows int
    1 | fn main(){
    2 |   println( i64( 1000_000_000_000_000_000_000_000_000 ) )
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    3 | }
```
(with latest *V* from git)

**Comment by dumblob** [comment]
Another issue is this:

```v
fn main(){
  println( i64(            9_223_372_036_854_775_807 ) )
  println( i64(            9_223_372_036_854_775_808 ) )
}
```
```
master 0$ ./v run ../test01.v 
9223372036854775807

master 0$
```
