### ISSUE TITLE
New playground is available at https://vlang.ide.judge0.com

### ISSUE THREAD

**Issue by hermanzdosilovic** [vlang/v#634]
Hi @medvednikov,

I am the author of [Judge0](https://github.com/judge0) and I have deployed free alternative playground for V programming language. It is available at https://vlang.ide.judge0.com. Here is an [example code](https://vlang.ide.judge0.com/?AAo8MLnm1PxbjyBpfu6DJb4db42G) from your website that you can run.

Take a look at my [release notes](https://github.com/judge0/api/releases/tag/v1.2.0-vlang0.1.3) that describe my current plan with maintaining this. Let me know what you think.

Thank you very much for your work on V!

Best regards,
Herman

**Comment by blueway** [comment]
Slow running speed and no normal output, output:
```
{
    "readyState": 0,
    "status": 0,
    "statusText": "error"
}
```

**Comment by whoizit** [comment]
not accessible to me from Russia

**Comment by medvednikov** [comment]
Looks cool, add a link to it for now. Thanks

**Comment by medvednikov** [comment]
Done.

**Comment by ntrel** [comment]
@hermanzdosilovic This is really great. BTW could you make it default to the highest version of V that is in the drop down menu? It seems to default to 0.1.5 for me when it has 0.1.8.

**Comment by hermanzdosilovic** [comment]
Hey @ntrel. Playground now opens to the highest version of V that is in the drop down menu. Enjoy. :smiley:

**Comment by medvednikov** [comment]
The playground is back: https://vlang.io/play
