### ISSUE TITLE
[Enhancement] json module can not decode on some case on array.

### ISSUE THREAD

**Issue by koji-k** [vlang/v#6344]
There are following structs.

```v
struct Tag {
    title string
}

struct User {
    name string
    age int
    tags []Tag
}
```

I want to decode the json string to User struct.

It is no problem.

```v
json.decode(User, '{"name": "Koji", "age": 35, "tags": [{"title": "A"}, {"title": "B"}]}')
```

But compiler show panic when `tags` key does not exist in JSON string.

```v
json.decode(User, '{"name": "Koji", "age": 35)
```

Then following error when i execute `v run`

```
V panic: tos2: nil string
   | 0x561f212fe851 | /home/koji/code/v/json_sample(+0x13851) 
   | 0x561f212ec6de | /home/koji/code/v/json_sample(+0x16de) 
   | 0x561f212ecab0 | /home/koji/code/v/json_sample(+0x1ab0) 
   | 0x561f213041f5 | /home/koji/code/v/json_sample(+0x191f5) 
   | 0x561f2130464e | /home/koji/code/v/json_sample(+0x1964e) 
   | 0x561f2130c33b | /home/koji/code/v/json_sample(+0x2133b) 
   | 0x7f8f21ea6b97 | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) 
   | 0x561f212ebfaa | /home/koji/code/v/json_sample(+0xfaa) 
Segmentation fault (core dumped)
```

When i specifiy the name/key and empty array in JSON, then it is no problem.

```v
// This is OK.
json.decode (User, '{"name": "Koji", "age": 35, "tags": []}')
```

Is this behavior expected?
I think, if a property of struct is array and does not exist that name/key in JSON, that value have to become empty array after `json.decode.`
So ideally the following codes should return the same result.

```v
json.decode(User, '{"name": "Koji", "age": 35')
json.decode(User, '{"name": "Koji", "age": 35, "tags": []}')
```

**Comment by dumblob** [comment]
I think the current behavior is "kind of" correct.

a) First, the expectation to match a JSON with a missing key (`tags` in your example) with a V struct which **requires** this field is false. So this should be an error or panic (currently it's the latter though I myself would prefer it to be an `error()`).

b) But if you had declared the V struct **with a default value** for the `tags` field, then your JSON with missing `tags` key must be accepted by V.

**Comment by JalonSolov** [comment]
Don't forget the error in the first example...
```v
json.decode(User, '{"name": "Koji", "age": 35')
```
is missing the closing '}'.  Should be
```v
json.decode(User, '{"name": "Koji", "age": 35}')
```
which may have been the actual cause of the panic.

**Comment by Naheel-Azawy** [comment]
Quick update, seems like the issue here has been resolved somehow. But it still fails for `map`s as shown in https://github.com/vlang/v/issues/6632. This can be seen here if `tags` type is a `map`.

```v
struct User {
    name string
    age int
    tags map[string]Tag
}
```

and then

```v
json.decode(User, '{"name": "Koji", "age": 35}')
```

**Comment by kahsa** [comment]
still problem?
```
bug.v:12:1: error: unfinished string literal
   10 | 
   11 | json.decode(User, '{"name": "Koji", "age": 35)
```

**Comment by enghitalo** [comment]
```bash
V panic: result not set (The type of `tags` can't be decoded. Please open an issue at https://github.com/vlang/v/issues/new/choose)
v hash: 1ba1f99
/tmp/v_1000/v_bug.16656380555407490405.tmp.c:8062: at _v_panic: Backtrace
/tmp/v_1000/v_bug.16656380555407490405.tmp.c:8032: by panic_result_not_set
/tmp/v_1000/v_bug.16656380555407490405.tmp.c:17602: by main__main
/tmp/v_1000/v_bug.16656380555407490405.tmp.c:18043: by main
```

**Comment by yuyi98** [comment]
Fixed.
```v
import json

struct Tag {
    title string
}

struct User {
    name string
    age int
    tags []Tag
}

fn main() {
	ret := json.decode(User, '{"name": "Koji", "age": 35}')!
	println(ret)
}

PS D:\Test\v\tt1> v run .
User{
    name: 'Koji'
    age: 35
    tags: []
}
```
