### ISSUE TITLE
cross compile on Ubuntu to window binary missing openlibm.o

### ISSUE THREAD

**Issue by gshields** [vlang/v#6350]
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
V 0.1.29 96c22a2
5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

v -os windows users.v
/home/ghs/v/thirdparty/tcc/lib/openlibm.o not found, building it...
exec failed for thirdparty object build cmd:
x86_64-w64-mingw32-gcc   -fPIC  -c -o "/home/ghs/v/thirdparty/tcc/lib/openlibm.o" "/home/ghs/v/thirdparty/tcc/lib/openlibm.c" 
builder error: sh: 1: x86_64-w64-mingw32-gcc: not found

**Comment by JalonSolov** [comment]
You have to install mingw-w64 package on your system.

Docs should be updated to state this, just hasn't been done, yet.

**Comment by gshields** [comment]
*Install apt*
x86_64-w64-mingw32-g++ --version
x86_64-w64-mingw32-g++ (GCC) 9.3-win32 20200320

*Still errors*
v -os windows nbody.v
/home/ghs/v/thirdparty/tcc/lib/openlibm.o not found, building it...
failed thirdparty object build cmd:
x86_64-w64-mingw32-gcc   -fPIC  -c -o
"/home/ghs/v/thirdparty/tcc/lib/openlibm.o"
"/home/ghs/v/thirdparty/tcc/lib/openlibm.c"
builder error: x86_64-w64-mingw32-gcc: error:
/home/ghs/v/thirdparty/tcc/lib/openlibm.c: No such file or directory
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.

**Comment by JalonSolov** [comment]
This appears to be a problem of where tcc gets installed.  On Windows, it is installed to `<v dir>/thirdparty/tcc`, but on Linux, it is installed to `/var/tmp/tcc`.  When cross-compiling, it is looking for it where Windows would have put it.

I know there has been discussion about consolidating, and making it always install tcc to `thirdparty/tcc` but that hasn't happened so far.

I think we'll have to leave this one open until that issue has been resolved, which may take care of this one as a side-effect.

**Comment by jabcross** [comment]
Arrived at the same problem by trying to compile from WSL into a Windows binary. Is there a workaround at the moment?

**Comment by JalonSolov** [comment]
Yes, V has changed a lot since then.  Now all versions install tcc to thirdparty/tcc, and use it as the default compiler.

Cross-compiling from Linux -> Windows works fine now.

**Comment by jabcross** [comment]
I tried this yesterday, though. It didn't work

**Comment by medvednikov** [comment]
Did you run `sudo apt install mingw-w64` as the compiler instructed?

**Comment by jabcross** [comment]
Yes, I did.

![image](https://user-images.githubusercontent.com/6402237/102695008-847c3600-4203-11eb-9024-dc62bdab4794.png)

**Comment by JalonSolov** [comment]
At least one problem you're going to have, unless you have wine or something similar installed, is that the Windows executable isn't going to run on Linux.

I hit the same problem compiling tetris with tcc, but it works fine with gcc:
```
jalon@Ripper:~/git/vv$ v -os windows examples/tetris
/home/jalon/git/v/thirdparty/tcc/lib/openlibm.o not found, building it in /home/jalon/.vmodules/cache/44/44f4cd28d9e625eafa793a8c2aa3ac4e.o ...
failed thirdparty object build cmd:
x86_64-w64-mingw32-gcc   -fPIC  -o "/home/jalon/.vmodules/cache/44/44f4cd28d9e625eafa793a8c2aa3ac4e.o" -c "/home/jalon/git/v/thirdparty/tcc/lib/openlibm.c"
builder error: x86_64-w64-mingw32-gcc: error: /home/jalon/git/v/thirdparty/tcc/lib/openlibm.c: No such file or directory
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.

jalon@Ripper:~/git/vv$ v -os windows -cc gcc examples/tetris
/home/jalon/git/v/thirdparty/stb_image/stbi.o not found, building it in /home/jalon/.vmodules/cache/dc/dc2219c8b105127f741a82e4dead6e37.o ...

Cross compiling for Windows...
/home/jalon/git/vv/examples/tetris/tetris.exe has been successfully compiled
jalon@Ripper:~/git/vv$
```
That makes this an issue with tcc, not V.

**Comment by jabcross** [comment]
It's WSL. It runs both kinds of executable. Using GCC like that did work,
though. Thank you!

**Comment by medvednikov** [comment]
no it actually is a problem with V

it should use mingw w64 when cross compiling

I'm surprised it doesn't work for you, since we have a CI job that tests just that

**Comment by jabcross** [comment]
For some reason, it's not downloading openlibm.c. At what step should it be downloaded?

**Comment by spaceface777** [comment]
It shouldn't; the fact that V tries to use it when cross compiling is a bug that needs to be fixed, as openlibm.o is tcc-for-windows specific.
