### ISSUE TITLE
windows 10 virus engine marks V as threat

### ISSUE THREAD

**Issue by gshields** [vlang/v#6351]
V 0.1.29
windows 10 (19041.508)
 reports  v.exe as having:

Behavior:Win32/DefenseEvasion.GT!ml

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/92989483-a0699080-f4cc-11ea-8664-ef7593b3df18.png)

![image](https://user-images.githubusercontent.com/13716824/92989490-a5c6db00-f4cc-11ea-88bf-3d347b5d12fb.png)

Got this after updating to 0.1.29 99a46c8. This stuff is why I think there should be a stable branch.

**Comment by leahlundqvist** [comment]
Which antivirus software do you use? Or is this just pure windows defender?

**Comment by gshields** [comment]
pure windows defender

**Comment by JalonSolov** [comment]
Odd.  I've only got Windows Defender on my system, and I've never seen that message pop up for V.

**Comment by Delta456** [comment]
Same as @JalonSolov

**Comment by ChildishGiant** [comment]
~~I'm happy to try and help since I have the same issue.~~ I just tried to reproduce and it seems that windows defender has updated and added an exception. @gshields can you still reproduce the issue?

**Comment by gshields** [comment]
This can be closed. I update virus engine and it is working fine. Thank you.
