### ISSUE TITLE
Cross compile on windows fails

### ISSUE THREAD

**Issue by gshields** [vlang/v#6361]
*using*
V 0.1.29 bffa100
gcc (x86_64-win32-sjlj-rev0, Built by MinGW-W64 project) 8.1.0
windows 10 version 2004(build 19041.508)

*tried*
First I had to add mingw include folder to path to find math.h in first failure
Got further in the process
Error now is v is looking for CC not gcc

*log*
C:\tools\v\examples>v -os linux -cg nbody.v
Cross compilation for Linux failed (first step, cc). Make sure you have clang installed.
builder error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: cc -fPIC -w -c -target x86_64-linux-gnu -c -o C:\Users\ghs\AppData\Local\Temp\v\nbody.tmp.c.o C:\Users\ghs\AppDat

**Comment by dodgez** [comment]
I ran into this issue today and found the specific lines responsible:

https://github.com/vlang/v/blob/530b981765b96e5837fcf8bbb2e41f8f2b5b8968/vlib/v/builder/cc.v#L765

and

https://github.com/vlang/v/blob/530b981765b96e5837fcf8bbb2e41f8f2b5b8968/vlib/v/builder/cc.v#L781

I got the cross compiling working with changing the first line to:

```cc_cmd := 'clang ' + cc_args.join(' ')```

and the second line to:

```linker_cmd := 'ld.lld.exe ' + linker_args.join(' ')```

It appears the default options were not cutting it.  I am very new to vlang, clang, ld, etc... but I wonder if these lines are specific to osx.  In fact, when I looked at the default linker executable, I get the following output:

```
$ file ~/.vmodules/linuxroot/ld.lld
.vmodules/linuxroot/ld.lld: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE|HAS_TLV_DESCRIPTORS>
```

For the record, I tested my executable in WSL (and double checked the executable type was indeed ELF 64-bit) and it worked fine after making these changes to my local installation of v.

Side note: it was so cool to be able to mess around with these lines of code and _quickly_ run `v self` to test them within seconds (the actual compile was <1s).  This was extremely helpful to diagnose and test solutions to this issue.  The quick compilation is very neat!

**Comment by dodgez** [comment]
I forgot to mention, but the default output had an extension `.exe` on it despite the target architecture of `linux`.  Not a big issue since I could just specify the output file but I figured it may be worth pointing out this default behavior.

**Comment by gshields** [comment]
found developing in windows is prefer since window platform is a larger target, closing this since I have a solution
