### ISSUE TITLE
Translating V to JavaScript/TypeScript

### ISSUE THREAD

**Issue by wond12** [vlang/v#637]
Is it possible to translate V to JavaScript/TypeScript, so that v could be called by other JS code.

**Comment by YevhenKap** [comment]
The author doesn’t complete compilation to machine code yet. But this is the main advantage of the language, as described in README. I think transpiling to JS/TS isn’t so necessary now. Maybe in future... Maybe not.

**Comment by Bowero** [comment]
This discussion is already a thing: https://github.com/vlang/v/issues/172
