### ISSUE TITLE
error when cloning a map ( in the repl )

### ISSUE THREAD

**Issue by Asc2011** [vlang/v#6374]
**V version: V 0.1.29 01b28ef** 
**OS: macOS** 

**What did you do?**
Have map defined. Then tried to cloned that map.

in the V-repl
```
mut a := { "one" : 1, "two" : 2}
{'one': 1, 'two': 2}
mut b := a.clone()
```
**What did you expect to see?**
A copy of map a.

**What did you see instead?**
A C-Error

> /private/var/folders/1r/fgrg1x_937g4pm31qgchvl040000gn/T/v/.noprefix.vrepl_temp.tmp.c:11183:21: error: implicit declaration of function 'map_string_int_clone' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        map_string_int b = map_string_int_clone(&a);
                           ^
/private/var/folders/1r/fgrg1x_937g4pm31qgchvl040000gn/T/v/.noprefix.vrepl_temp.tmp.c:11183:17: error: initializing 'map_string_int' (aka 'struct map') with an expression of incompatible type 'int'
        map_string_int b = map_string_int_clone(&a);
                       ^   ~~~~~~~~~~~~~~~~~~~~~~~~
> 18 warnings and 2 errors generated.

> ==================
> C error. This should never happen.

**Comment by Delta456** [comment]
Fixed with the latest V

![image](https://user-images.githubusercontent.com/28479139/110932017-ee166700-8350-11eb-93c8-a6cf2eed1616.png)
