### ISSUE TITLE
make install support

### ISSUE THREAD

**Issue by yetkinozturk** [vlang/v#6380]
adding complete repository to the system path or manual symbolic linking is not the best user experience.
`make install` can install required components to proper locations, after that `v up` it can be updated.

**Comment by spaceface777** [comment]
`v symlink` will already handle that for you.

**Comment by yetkinozturk** [comment]
Ah ok, I missed that [point](https://github.com/vlang/v#symlinking) I thought manual symlinking is required.

**Comment by medvednikov** [comment]
I've personally never been a fan of `make install`. I don't like moving things to `/usr/....` Then there's no way to cleanly remove them, unless you use something like checkinstall.

I think `v symlink` is a pretty clean solution.

**Comment by yetkinozturk** [comment]
Thanks for clarification, before the answer of @spaceface777  I thought you are refering to `ln -s` like manual symlinking but apparently you have a cleaner alternative.
