### ISSUE TITLE
Info: interpolation in raw strings

### ISSUE THREAD

**Issue by lkppo** [vlang/v#6386]
Hello,

It's a question, not a feature request.

Is the interpolation supposed to apply even on raw strings?

```
fn main() {
	name := 'Bob'
	println(r'Hello, $name!\n')  // `$` is used for string interpolation
}
```

returns

`Hello, Bob!`

Regards,

**Comment by ntrel** [comment]
A raw string is there to avoid having to escape special characters. If interpolation was allowed then there would be no way to escape a `$` character, so I don't think it should be supported. It would break the principle of least astonishment.

**Comment by lkppo** [comment]
The interpolation takes place on this raw string. So, shouldn't it? Or is that correct?

**Comment by yuyi98** [comment]
It's correct when using raw string.
