### ISSUE TITLE
Reserve the keyword it

### ISSUE THREAD

**Issue by lkppo** [vlang/v#6387]
Hello,

In a .map() context the `it` builtin variable can overlap an `it` variable at the function scope.

Wouldn't `it` be better to reserve the word it to avoid this?

Regards,

**Comment by ntrel** [comment]
That wouldn't solve the problem completely - there could be a `map` call nested inside another `map` call. It would be better if we could name the parameter for each `map`.

**Comment by lkppo** [comment]
Hum, right. That adds more syntax sugar. And if .map() receive an anonymous function where the first parameter is the value of it?

**Comment by lkppo** [comment]
The interpolation takes place on this raw string. So, shouldn't it? Or is that correct?
