### ISSUE TITLE
Implicit value from last statement in a block problem with prefix expression

### ISSUE THREAD

**Issue by ntrel** [vlang/v#6388]
```v
_ = if false {
    println('')
    -1
} else {1}
```
The above produces an error:
```
ifexpr.v:3:5: error: mismatched types `void` and `any_int`
```
This is parsed with `println` as a function call expression, which is the left operand to a infix minus expression with `1` as the right operand. The same problem can occur when dereferencing a pointer as the last statement `*p`.
Can we make this nicer for the user?
* Writing `(-1)` is a workaround. But what if the last statement of every `if` expression branch/`or` block had to be a parenthesis expression? That would make the produced value stand out more, even when there's no prefix expression, e.g. `(some_var)`.
* Alternatively we could require that the *op* token for an infix expression is on the same line as the left operand.
* Another option is to require a space after the `op` token to parse as an infix expression.

**Comment by ntrel** [comment]
> what if the last statement of every if expression branch/or block had to be a parenthesis expression? 

I think this would work even if the preceding expression is callable `f = func_name`, because I think the opening `(` has to be on the same line. The downside is that it requires updating all implicit expression values!

> the op token for an infix expression is on the same line as the left operand.

This seems a good requirement but it would break any code that currently has the infix op on the next line. There is precedent for this requirement in other languages IIRC.

> require a space after the op token to parse as an infix expression.

This would break code that doesn't use spaces either side `x+1`.

Another idea is to detect if there's more indentation on the next line, suggesting it continues the previous line. A downside of this is that indentation changes can be ambiguous if the user uses four spaces for one indent and a tab only for two indents - Vs pure tab or pure spaces.

**Comment by medvednikov** [comment]
I think this will be solved once we have "virtual" `;` like in Go.

**Comment by ntrel** [comment]
OK, I found: https://golang.org/doc/effective_go.html#semicolons

> “if the newline comes after a token that could end a statement, insert a semicolon”

So this would mean the op for an infix expression would have to be on the same line as the left operand - sounds good.

> you cannot put the opening brace of a control structure (if, for, switch, or select) on the next line.

I think that should be allowed - it would be an error otherwise so there wouldn't be any ambiguity. V should appeal to programmers from C and other similar languages, which often have code with Allman-style braces (braces on a separate line).

Go can also reject code that puts a closing bracket on its own line:
```go
func f(i int) int {return i+1}

func g() int {
	x := 3
	return f(
		x           // ./prog.go:8: syntax error: unexpected newline, expecting comma or )
	)
}
```
I think that could be easily allowed too.
