### ISSUE TITLE
[Bug] It seems "v up" isn't successfully updating V or the version number isn't changing.

### ISSUE THREAD

**Issue by AqilCont** [vlang/v#6396]
### V version:

> 6+ total tries, time zone: EST.

![image](https://user-images.githubusercontent.com/32044067/93409192-4d912f80-f864-11ea-8309-c49c2fc17189.png)
![image](https://user-images.githubusercontent.com/32044067/93409248-74e7fc80-f864-11ea-880f-d61ae400284a.png)

**OS:** Win10 2004

### What did you do?
Run `v up` to update V.

### What did you expect to see?
It displaying the last commit ID as the version number.
 
### What did you see instead?
(listed in above image)

**Comment by medvednikov** [comment]
v up works fine now.

**Comment by AqilCont** [comment]
Oh thanks!
