### ISSUE TITLE
0 character error in raw string

### ISSUE THREAD

**Issue by VinWare** [vlang/v#6426]
**V version:**
V 0.1.29 4121ba9
**OS:** 
Windows 10 OS Build 19041.508
**What did you do?**
Opened V REPL and ran
`>>> print(r'Hey\0')`

**What did you expect to see?**
`Hey\0`
on the next line
 
**What did you see instead?**

```
.vrepl.v:7:13: error: 0 character in a string literal
    5 | import math
    6 |
    7 | print(r'Hey\0')
      |             ^
```

**Comment by VinWare** [comment]
On a related note, some other errors which seem to indicate that the raw strings are being parsed like normal strings have cropped up. Perhaps this is the direction to look to fix?

**Comment by Delta456** [comment]
You need to add a condition for raw strings like how its done for normal strings https://github.com/vlang/v/pull/6404/files
