### ISSUE TITLE
OR || operation not returning first non-zero operation with integers

### ISSUE THREAD

**Issue by Henrixounez** [vlang/v#6438]
**V version:** V 0.1.29 0f1c484

**OS:** Linux

**What did you do?**
```
println(2 || 1)
```

**What did you expect to see?**
```
2
```
 
**What did you see instead?**
```
1
```

**Note**
The output is 1 due to how C works, it returns a boolean on these operations, (`0` == `false`, `1` == `true`):
`0 || 0` => `0`
`2 || 0` => `1`
`0 || 3` => `1`
`2 || 3` => `1`

`0 && 0` => `0`
`2 && 0` => `0`
`0 && 3` => `0`
`2 && 3` => `1`

**Comment by Delta456** [comment]
Go and Rust disallow this. The question should if V should allow this or not.

- Go
`./prog.go:10:16: invalid operation: a || b (operator || not defined on int)`

- Rust

```
error[E0308]: mismatched types
 --> src/main.rs:2:20
  |
2 |     println!("{}", 3 || 4)
  |                    ^ expected `bool`, found integer

error[E0308]: mismatched types
 --> src/main.rs:2:25
  |
2 |     println!("{}", 3 || 4)
  |                         ^ expected `bool`, found integer
```

**Comment by Delta456** [comment]
Even `3 && 4` give `1` but ideally it should give `4` or an error!?

Even in this case, Go and Rust throws an error.

- Go
`./prog.go:10:16: invalid operation: a && b (operator && not defined on int)`

- Rust

```
error[E0308]: mismatched types
 --> src/main.rs:2:20
  |
2 |     println!("{}", 3 && 4)
  |                    ^ expected `bool`, found integer

error[E0308]: mismatched types
 --> src/main.rs:2:25
  |
2 |     println!("{}", 3 && 4)
  |                         ^ expected `bool`, found integer
```

**Comment by JalonSolov** [comment]
I vote for error.  Logical operators should only work with booleans.  Bitwise operators with ints (and variants, such as u32, i64, etc.).
