### ISSUE TITLE
v install ui failed

### ISSUE THREAD

**Issue by jalmmor** [vlang/v#6440]
Running `v install ui` throws an error:
``V error: `vget.v` does not exist``

V 0.1.19 79a98d7
OS: Archlinux

**Comment by JalonSolov** [comment]
Most recent version of V is `V 0.1.29 a9ef7d1`.

Did you install from AUR?  If so, that would explain how you got such an ancient version.

Please just clone from the repo to get the most recent version.

**Comment by Bowero** [comment]
If you use the AUR, at least use the `vlang-git` version please.

_On a whole other note: someone should adopt this package. [The maintainer clearly is done with it.](https://aur.archlinux.org/packages/vlang-git/#comment-756908)_ I think I will take over the AUR package.

**Comment by jalmmor** [comment]
The package vlang-git has pinned this comment:
`The only way I was able to make it run, was to grant 777 recursively on /usr/lib/vlang/cmd, which is a potential security risk. Use at your own risk.`

Is the same in others linux distributions?

**Comment by JalonSolov** [comment]
I don't know of any other linux distributions that have an installable package.  Not sure why anyone made one so early.

Most everyone else clones the repo to a user-writable area, and everything works fine.

**Comment by leahlundqvist** [comment]
I think this issue can be closed, although, we should look into this AUR deal some more. At the moment unmaintained installable packages like this are just harmful to the language as a whole. I'm also counting the binary on the website into this, V is itterating far too quickly for the precompiled binaries to keep up. You pretty much need to update V every day.
