### ISSUE TITLE
can we call v from python or vice versa? 

### ISSUE THREAD

**Issue by nittvikas** [vlang/v#6485]
since python is interpreted language. v has very much like python.  So is there any option to call python -> <- v from each other ?

**Comment by Ekopalypse** [comment]
> v has very much like python.

How so?

> So is there any option to call python -> <- v from each other ?

If you mean you mean from native coding like
~~~py
import v_modules  # from python or
import python_modules // from v
~~~

then no.

If you want to be able to run a Python script from v, you must embed the Python interpreter in a v program
or call the Python program directly from v.
If you want to call the v library from Python, you must load the compiled v library with ctypes/cffi ...
If you want to run an v executable , you can use the Python subprocess module.

**Comment by leahlundqvist** [comment]
Since V outputs C code by default you can create a python wrapper for it using this method [docs.python.org/3/extending/extending.html](https://docs.python.org/3/extending/extending.html). Although the best option in my opinion is probably to just call the executables directly.
