### ISSUE TITLE
Better error message needed

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#65]
The following program correctly indicates there is a bug:

fn main() {
	mut a := 42
	a = 44
	println(a)
	{
		mut b := 67
		println(b)
	}
        b = 9
}

because b is undefined, but it should say that in the error message

**Comment by shouji-kazuo** [comment]
I got output as below (in Vlang playground):

```
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.
```

**Comment by medvednikov** [comment]
Fixed a couple of days ago:

```
undefined: `b`
```

**Comment by gsbhasin123** [comment]
Why is it in backticks and not in quotes (single or double), @medvednikov?
