### ISSUE TITLE
Passing mutable variable to functions

### ISSUE THREAD

**Issue by Henrixounez** [vlang/v#652]
**V version:** 
0.1.3

**What did you do?**
```
fn multiply_by_2(num mut int) {
    num = num * 2
}

fn main() {
    num := 1
    multiply_by_2(mut num)
    println(num)
}
```

**What did you expect to see?**
``` 2 ```
 
**What did you see instead?**
```
/home/Henrixounez//.vlang//test2.c: In function ‘multiply_by_2’:
/home/Henrixounez//.vlang//test2.c:3577:14: error: invalid operands to binary * (have ‘int *’ and ‘int’)
  num  =  num * 2 ;
              ^
V panic: clang error
```

This issue is a follow up of the problem discussed in comments of #549 and #581

**Comment by Bowero** [comment]
The code that is being generated in `C` is this:
```
 void multiply_by_2(int* num) {
 num  =  num * 2 ;
 }
```

If we want it to work, it should be this:
```
 void multiply_by_2(int* num) {
 *num  =  *num * 2 ;
 }
```

**Comment by gaoxinge** [comment]
@Bowero  The code is here:

https://github.com/vlang/v/blob/2a3cf0bec94b1312ac2ffdaa2ca4090a34c8b450/compiler/fn.v#L611-L614

It says if argument is mut, pass by pointer; if not, pass by copy.
