### ISSUE TITLE
Help displayed when a Command has no execute function

### ISSUE THREAD

**Issue by shnorbluk** [vlang/v#6530]
**V version:** V 0.1.29 d96f1bf
**OS:** Linux aarch 64

**What did you do?**
Compile this program
```go
// mycmd.v
import cli { Command, Flag }
import os
mut cmd := Command{}
cmd.add_flag(Flag{
       flag: .string
       required: true
       name: 'value'
}) 
cmd.parse(os.args)
value := cmd.flags.get_string('value')?                                     
println('value=$value')
```

Run it with
```go
./mycmd --value foo
```

**What did you expect to see?**
```
value=foo
```
 
**What did you see instead?**
```
Usage:  [flags] [commands]

Flags:
  -h  --help          Prints help information.
  -l  --value         (required)

Commands:
  help                Prints help information.
value=toto
```

**Comment by shnorbluk** [comment]
The problem is in `v/vlib/cli/command.v` file, in the function `parse_commands`. The following block
```go
if int(cmd.execute) == 0 {
        if !cmd.disable_help {
            cmd.execute_help()
        }
```
displays help if `cmd.execute` was not defined. However, program arguments were perfectly correct, so there is no reason to display help.
I suggest, as a fix, to move the `if int(cmd.execute) == 0` check before the `cmd.execute(*cmd)` block, and remove `cmd.execute_help`.
I can do a pull request if you wish. I just wanted your opinion before. 
Thank you.

**Comment by Gladear** [comment]
I think this change makes sense, the current behaviour definitely isn't expected 🙂
Feel free to open a PR !
