### ISSUE TITLE
Reduce shorthand to increment error to warning in case of dev compile

### ISSUE THREAD

**Issue by VinWare** [vlang/v#6549]
Currently, the line

`a += 1`

Gives an error saying 

`error: use '++' instead of '+= 1'`

As this statement may be a valid line of code during development (where the literal 1 may be changed later or replaced by a constant or variable entirely), it would be helpful to reduce it to a warning during dev compiles. Prod builds should still show it as an error.

**Comment by ntrel** [comment]
Personally I think it should only be a warning for `v vet`, as it is perfectly clear. In fact it is actually clearer for people not used to C syntax.

**Comment by serkonda7** [comment]
Both syntaxes are allowed now.
