### ISSUE TITLE
Formatting infix expressions with `if` duplicates the content of the file

### ISSUE THREAD

**Issue by Gladear** [vlang/v#6553]
**V doctor:** 
OS: linux, "Manjaro Linux"
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
CC version: cc (GCC) 10.2.0

vroot: /home/gladear/workspace/v
vexe: /home/gladear/workspace/v/v
vexe mtime: 2020-10-03 17:32:04
is vroot writable: true
V full version: V 0.1.29 a9da4dd.d93b0f0

Git version: git version 2.28.0
Git vroot status: 0.1.29-506-gd93b0f04
.git/config present: true
/var/tmp/tcc status: master 5e73982e
thirdparty/tcc: N/A

**What did you do?**
Format the following code:
```v
fn x(){
    return if 2==2 { 'xxx' } else { 'yyy' } + if 3==3 { 'aaa' } else { 'bbb' }
}
```

**What did you expect to see?**
The code formatted.
 
**What did you see instead?**
The content of the file duplicated and the code incorrectly formatted.

**Comment by serkonda7** [comment]
Somewhat related to #5765

**Comment by serkonda7** [comment]
@medvednikov should this code even be formattable by fmt as it contains some really bad compilation errors?
