### ISSUE TITLE
os.setenv does not create environment variable

### ISSUE THREAD

**Issue by Ekopalypse** [vlang/v#6559]
On windows os.setenv doesn't create an environment variable if overwrite is set to false.

OS: windows, Microsoft Windows 7 Professional v7601 64-bit
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
CC version: N/A

vroot: D:\Repositories\eko\v
vexe: D:\Repositories\eko\v\v.exe
vexe mtime: 2020-10-04 14:28:23
is vroot writable: true
V full version: V 0.1.29 0c17410

Git version: git version 2.19.1.windows.1
Git vroot status: 0.1.29-514-g0c174104-dirty
.git/config present: true
thirdparty/tcc status: master 17d18c13

**What did you do?**
>>> import os
>>> foo := os.setenv('foo', 'bar', false)
>>> os.getenv('foo')

**What did you expect to see?**
bar
 
**What did you see instead?**
nothing

**Comment by JalonSolov** [comment]
Definitely a bug, as it does not work as documented.  In fact, the code as a an explicit `$if windows` section, where it does `if overwite putenv else return -1`
