### ISSUE TITLE
Playground page is offline

### ISSUE THREAD

**Issue by hakkikonu** [vlang/v#656]
https://vlang.io/play page says:

> The playground is temporarily offline. It will be back on June 25. 
> In the meantime you can install V on your machine in a couple of seconds.

But now 12:08:16 UTC Wednesday, 26 June 2019

**Comment by Bowero** [comment]
Correct. For now, you can look at https://vlang.ide.judge0.com as #634.

**Comment by hakkikonu** [comment]
Thanks I did not know this page. Could you update https://vlang.io/play page for this new page. Newcomers can not experience without playground.
