### ISSUE TITLE
Fixing appending to a slice (also helps for reference counting slices)

### ISSUE THREAD

**Issue by ntrel** [vlang/v#6569]
#3352 has an example where appending to a slice that doesn't start at the first element of the original array will call `realloc` with an invalid address.
```v
mut arr := [1,2,3]
arr = arr[1..]
arr << 4
```
I think we can fix this by adding a private field to `array`: `start voidptr`. Then when appending to a slice, V could compare this to the `data` field, as if this code was written:
```v
arr = arr[1..]
if arr.data == arr.start {
  // realloc arr.data
} else {
  // allocate a copy of arr.data
}
arr.start = arr.data
```
Adding another field makes the array struct bigger, which means it becomes even harder to fit in a register e.g. for fast passing to functions. But, it actually is far more useful than the `cap` field. We can store `cap` before the start of the array elements, in the same memory allocation. (We can also use this trick to store a reference count before the elements too for safe array memory sharing.) Storing `cap` in allocated memory could also be very useful for solving #119.

Possibly this field could be avoided with a clever custom allocator that can quickly tell if a memory address is within one of the allocations it owns. I don't know how to write that in an efficient way though ;-) It could be implemented later if necessary.

Having a way to get the start address is also important if we want to reference count data for array slices.

**Comment by spytheman** [comment]
That would not solve the situation, where you have 2 or more slices, and append to 1 of them, or when you append to the original array, after you have made the slices.
After the reallocation, some of the slices will be invalid.

**Comment by ntrel** [comment]
Copying from the other issue:

> I would use a reference count (stored in allocated memory just before the elements). Slicing is very common for strings and arrays so reference counting is a good strategy (except where the compiler can prove it doesn't escape the original owner variable). Allocating copies is expensive, this avoids that. When memory is exhausted, orig would only use realloc if the reference count is 1 and orig.start == orig.data.
So slice is never changed by appending to orig.

**Comment by spytheman** [comment]
I am closing this, to centralize the discussion in the other issue https://github.com/vlang/v/issues/8149 .
