### ISSUE TITLE
json needs attribute like Go's `omitempty`

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#6571]
When encoding a struct to JSON, YAML, XML, or whatever, the `omitempty` flag in Go tells it's encoders to leave that field out completely if it is empty, instead of cluttering up the encoded string with "" and 0 values.

This would be a good addition to V.

**Comment by Gladear** [comment]
Instead of a flag, that could be the default behaviour for optional field (if and once they are implemented) ?

**Comment by JalonSolov** [comment]
We need a flag, attribute, or some other method to mark individual structures.  There will be times where you _must_ supply all the fields whether they are empty or not.  And it may be down to individual fields within a structure.

**Comment by Gladear** [comment]
Well, if you must supply them, don't mark them as optional ?
I'm not sure my idea was clearly understood, here's an example:
```v
struct Country {
    population u32 // will be included even if the value is `0`
    surface ?f32 // will only be included if the value isn't `none`
}
```
This would obviously only work if optional struct fields are decided as part of the language !

**Comment by JalonSolov** [comment]
I see what you mean.  Not sure if it would fill exactly the same need, though.  Would have to see 1) if optional fields are implemented, and 2) how they would affect things like json.

**Comment by elimisteve** [comment]
`[skip]` already does this, doesn't it? https://github.com/vlang/v/blob/master/doc/docs.md#decoding-json

**Comment by elimisteve** [comment]
Ah `[skip]` always skips, not only if the value is empty/the zero value; nevermind.

**Comment by medvednikov** [comment]
yeah just need `[omitifempty]` :)

**Comment by anzellai** [comment]
Small correction, the Go's tag referring to omitting the field value if empty is `omitempty`, not `omitifempty` if that makes it more consistent between **v** and **go** :-).

**Comment by JalonSolov** [comment]
You are correct - `omitempty` is what Go uses.  I didn't look it up before entering this issue.  :-\

**Comment by medvednikov** [comment]
Fixed.
