### ISSUE TITLE
Crash when using generic from submodule

### ISSUE THREAD

**Issue by Larpon** [vlang/v#6572]
```
==> generic_mod_type_bug/bug/bug.v <==
module bug

pub fn take<T>(a bool, b, c T) T {
        if a { return b }
        return c
}

==> generic_mod_type_bug/main.v <==
module main

import bug

fn main() {
        choosen := bug.take(true,10,20)
        println(choosen)
}

```
Running this will cause
```
v run main.v
V panic: array.get: index out of range (i == 0, a.len == 0)
```
Reproducible example (same code as above):
[generic_mod_type_bug.zip](https://github.com/vlang/v/files/5340856/generic_mod_type_bug.zip)

This may or may not be related to #5507 and #5508 which I can't test easily at the time of writing.

**V version:** 
**OS:** 

**What did you do?**

**What did you expect to see?**

 
**What did you see instead?**

**Comment by danieldaeschle** [comment]
Was fixed in https://github.com/vlang/v/pull/6921

**Comment by joe-conigliaro** [comment]
This has been fixed in https://github.com/vlang/v/commit/4f658ec2924dfd3bc90f6db243b43c6785925824
