### ISSUE TITLE
Sum type bug: getting "cannot cast non sum type `Var` using `as`" when Var _is_ a sum type

### ISSUE THREAD

**Issue by elimisteve** [vlang/v#6578]
**V version:** V 0.1.29 35a8346.30588e4
**OS:** linux, Debian GNU/Linux 9.13 (stretch) (VM)

**What did you do?**

```
$ cat microkanren-buggy6.v
module main

type Var = int | string

fn main() {
	println(is_num(int(5) as Var))
}

fn is_num(v Var) bool {
	match v {
		int { return true }
		else { return false }
	}
}

$ v run microkanren-buggy6.v
```

**What did you expect to see?**

```
true
```
 
**What did you see instead?**

```
$ v run microkanren-buggy6.v
microkanren-buggy6.v:6:24: error: cannot cast non sum type `Var` using `as`
    4 | 
    5 | fn main() {
    6 |     println(is_num(int(5) as Var))
      |                           ~~
    7 |     // println(is_num(int(5)))
    8 | }
```

Maybe it meant to say `int(5)` is what's not a sum type?

**Comment by ntrel** [comment]
Yes, it should say something like "`int` is not a sum type, cannot cast to `Var` using `as` - use e.g. `Var(some_int)` instead`". 

Note: I heard `as` can now be used for interface casting as well, so in that case the message should be different.
