### ISSUE TITLE
Builtin function copy doesn't work

### ISSUE THREAD

**Issue by Ekopalypse** [vlang/v#6592]
**V version:** 
**OS:** 

OS: windows, Microsoft Windows 7 Professional v7601 64-bit
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
CC version: N/A

vroot: D:\ProgramData\Compiler\v
vexe: D:\ProgramData\Compiler\v\v.exe
vexe mtime: 2020-10-09 21:03:07
is vroot writable: true
V full version: V 0.1.29 e862fad

Git version: git version 2.19.1.windows.1
Git vroot status: 0.1.29-553-ge862fad9
.git/config present: true
thirdparty/tcc: N/A

**What did you do?**
Running the following code

```
fn main() {
	mut x:=[]byte{}
	mut y:=[byte(1),2,3,4,5]
	println(copy(x,y))
	println('${x} ${y}')
	println(copy(y, x))
	println('${x} ${y}')
}
```

**What did you expect to see?**
That items from one array are copied to the other
 
**What did you see instead?**

```
0
[] [0x01, 0x02, 0x03, 0x04, 0x05]
0
[] [0x01, 0x02, 0x03, 0x04, 0x05]

```

**Comment by Gladear** [comment]
As stated in the docs : *The number of the elements copied is the minimum of the length of both arrays.*.
The length of `x` is `0` in you case, so no elements are copied !
You must declare `x` using `[]byte{len: 5}` if you want all the elements from `b` to be copied in `a`.

**Comment by Ekopalypse** [comment]
For whatever reason I thought that this should apply to fixed arrays, but if this also applies to dynamic arrays it makes sense.
