### ISSUE TITLE
Memory is not released after reading a file

### ISSUE THREAD

**Issue by ax1** [vlang/v#6600]
**V:** 

version: V 0.1.29 c84848c

**OS:** 

Ubuntu 20.04 Desktop

**What did you do?**

- write a program to read a big file, then perform other actions
- compile with `v -prod main.v` or `v -prod -autofree main.v`
- run

```
import time { sleep }
import os {open}

fn main() {
	bytes := test('ISS') // 11.9MB file
	println(bytes)
	sleep(100) // i.e.: doing other taks
}

fn test(path string) int {
	mut f := open(path) or { panic(err)	}
	defer { f.close() }
	bytes := f.read_bytes(10000000) // any read operation in file
	return bytes.len
}
```

**What did you expect to see?**

after reading the file, the memory related to test should be released
 
**What did you see instead?**

memory at the main.sleep() is still +10MB

**Comment by JalonSolov** [comment]
Do you mean size of the file + 10MB?  Or just the 10MB you read?  You've read it into a buffer, and printed the buffer, but never free'd it, so I would expect it to still have the 10MB allocated.  It won't be free'd until your program exits, or you free it yourself.

**Comment by medvednikov** [comment]
It will be freed with `-autofree`

**Comment by fantassin** [comment]
static int main__test(string path) {
        // autofree_call()
        /*AF opt*/Option_os__File _t393 = os__open(path);
        if (!_t393.ok) {
                string err = _t393.v_error;
                int errcode = _t393.ecode;
                // autofree_call()
                v_panic(err);
        }/*=============ret*/
        os__File f = *(os__File*)_t393.data/*FF*/;
        // autofree_call()
        array_byte bytes = os__File_read_bytes(&f, 10000000);
        // Defer begin
        // autofree_call()
        os__File_close(&f);
        // Defer end
        // ast.Return free
        **return bytes.len**;
// autofree_scope_vars(176)
        array_free(&bytes); // autofreed var
}

**Comment by ax1** [comment]
@JalonSolov : I meant the  usage of RAM, after reading a big file, the RAM should be released after exit test(). Even if there is a performance penalty on doing that because there is no GC, this would allow programs to run always with the lowest memory and having them alive at a lower expense than other languages with JIT runtime (java or node always spent 30M+ even on running small daemons).

@medvednikov : ok, '-autofree'  flag has that intention. I compiled the program with that flag but same return, the 10MB are not released after exiting test(). It is not a 'file' problem because same test with `bytes := []byte{ cap: 10000000 }` and same result. updated v to latest commit V 0.1.29 230e986.

@fantassin : exactly, that should be the problem. If compiled as `v -autofree -o main.c  main.v`, the c code also shows the same (freeing bytes array *after* return statement)

**Comment by JalonSolov** [comment]
You assign the 10MB block to bytes, which does not go out of scope until the end of main.

True, the compiler should be "smart" enough to free it automatically after last use, and perhaps that is what @medvednikov was referring to when he said autofree would free it.

However, memory management isn't quite finished, yet.  So you can expect to see some things like this until it is.

**Comment by fantassin** [comment]
> You assign the 10MB block to bytes, which does not go out of scope until the end of main.
>
No, you misunderstood the code which is written in a confusing way. The variable 'bytes' inside the function 'test()' is a buffer but the function returns bytes.len which is then assigned to a variable also named 'bytes' in 'main()' but it's just an int and not an array.

**Comment by ax1** [comment]
yes, the big array is not touching the main() method.

This is a refactored example to test/discard: 1- file handling is not the problem (we can edit the issue title later) and 2- state that the array []bytes is always internal to test() an nothing to do with parent main().

The result is the same, the free() statement is added after the return one, and therefore not released.

```
import time { sleep }

fn main() {
	len := test()
	println(len)
	sleep(100)
}

fn test() int {
	bytes := []byte{ cap: 10000000, len: 10000000, init: 3}
	len := bytes.len
	return len
}
```
and then after compiling with `v -autofree -o main.c main.v`, the C-generated test() method is:

```c
static int main__test() {
	array_byte bytes = __new_array_with_default(10000000, 10000000, sizeof(byte), &(byte[]){3});
	int len = bytes.len;
	// ast.Return free
	return len;
// autofree_scope_vars(96)
	array_free(&bytes); // autofreed var
}
```

**Comment by ax1** [comment]
Results with latest version `V 0.2.2 63f835c`:

- `v -autofree main.v && ./main` does free the array. So test is now **OK**. 
- `v -autofree -o main.c main.v` still has a spare array_free() at the end of test() method (though not a problem).

Since the leakage is gone, I close the issue. As stated in documentation, when version reaches 0.3, autofree flag will not be necessary, it will be the default, and that is nice because in programs running continuously (daemons, apps, etc)  only a small part of RAM is taken (also use the `-prod` flag), while on programs to be executed from time to time ( e,g: CLI commands), you can compile them disabling autofree to allow  much faster executions.  

Note: I keep the generated C code, in case anyone can review how the test() method has evolved . The generated C code is now bigger and a bit harder to read but this only affects to debugging experience, not to runtime.

```c
VV_LOCAL_SYMBOL int main__test(void) {
	Array_byte bytes = __new_array_with_default(10000000, 10000000, sizeof(byte), &(byte[]){3});
	int len = bytes.len;
	// autofree_scope_vars(pos=185 line_nr=11 scope.pos=97 scope.end_pos=197)
	// var "bytes" var.pos=111 var.line_nr=9
		array_free(&bytes); // autofreed var main false
	// var "len" var.pos=168 var.line_nr=10
	// skipping returned var
	// af parent scope:
	// af parent scope:
	return len;
// autofree_scope_vars(pos=116 line_nr=9 scope.pos=97 scope.end_pos=197)
// var "bytes" var.pos=111 var.line_nr=9
	array_free(&bytes); // autofreed var main false
// var "len" var.pos=168 var.line_nr=10
// skipping returned var
}
```
