### ISSUE TITLE
C error starting V on macOS older than 10.12 due to clock_gettime missing

### ISSUE THREAD

**Issue by ssb22** [vlang/v#6605]
Hi, I don't know if you want to support macOS earlier than 10.12.  If you don't, perhaps the easiest way to make this issue go away is to declare that the macOS version of V requires 10.12 or higher.

Versions of macOS before 10.12 don't have `clock_gettime`, you had to use a workaround like https://gist.github.com/jbenet/1087739 so when I downloaded V for macOS version 0.1.28 from vlang.io and tried it on an older Mac Mini running Mac OS X 10.7.5 I got this:

    mac:/tmp$ unzip v_macos.zip
    ...
    mac:/tmp$ cd v
    mac:/tmp/v$ ./v
    For usage information, quit V REPL and run `v help`
    cannot compile `/private/tmp/v/cmd/tools/vrepl.v`:
    ==================
                                                                        ^
    /var/folders/ng/l1tjl5bx13ncfqq6h_6h7qy40000gn/T/v/vrepl.tmp.c:11319:2: error: implicit declaration of function 'clock_gettime' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        clock_gettime(CLOCK_MONOTONIC, &ts);
        ^
    /var/folders/ng/l1tjl5bx13ncfqq6h_6h7qy40000gn/T/v/vrepl.tmp.c:11319:16: error: use of undeclared identifier 'CLOCK_MONOTONIC'
        clock_gettime(CLOCK_MONOTONIC, &ts);
                      ^
    /var/folders/ng/l1tjl5bx13ncfqq6h_6h7qy40000gn/T/v/vrepl.tmp.c:11333:16: error: use of undeclared identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, &ts);
                      ^
    /var/folders/ng/l1tjl5bx13ncfqq6h_6h7qy40000gn/T/v/vrepl.tmp.c:12952:83: warning: missing field 'c_oflag' initializer [-Wmissing-field-initializers]
        readline__Readline readline = (readline__Readline){.is_raw = 0,.orig_termios = {0},.current = {0},.cursor = 0,.overwrite = 0,.cursor_row_offset = 0,.prompt = (string){.str=(byteptr)""},.prompt_offset = 0,.previous_lines = __new_array(0, 1, sizeof(ustring)),.search_index = 0,.is_tty = 0,};
    ...
    ==================
    (Use `v -cg` to print the entire error message)
    
    builder error:
    ==================
    C error. This should never happen.
    
    If you were not working with C interop, please raise an issue on GitHub:
    
    https://github.com/vlang/v/issues/new/choose
    
    You can also use #help on Discord: https://discord.gg/vlang

Thanks.

**Comment by ArtemkaKun** [comment]
Hi @ssb22 ,

can you confirm that a problem still exists on a fresh V (0.2.4)?

**Comment by ssb22** [comment]
Thanks, this is no longer an issue with the current download (V 0.2.4 4ef7d26).

**Comment by ArtemkaKun** [comment]
Got it

**Comment by medvednikov** [comment]
@harens I saw you patched this for macports.

We don't have a machine with an old macos version, perhaps you could submit a PR into vlang/v?

**Comment by harens** [comment]
Maybe, it would be tricky but it's possible. It would involve building the [macports legacy support](https://github.com/macports/macports-legacy-support) libraries on older macOS versions, and then linking V to it.
