### ISSUE TITLE
Multiple problems in TOC on modules.vlang.io

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#6606]
OS: linux, Ubuntu 20.04.1 LTS (WSL)
Processor: 32 cpus, 64bit, little endian, AMD Ryzen Threadripper 1950X 16-Core Processor
CC version: cc (Ubuntu 9.3.0-10ubuntu2) 9.3.0

vroot: /home/jalon/git/v
vexe: /home/jalon/git/v/v
vexe mtime: 2020-10-12 13:53:48
is vroot writable: true
V full version: V 0.1.29 d93b0f0.93bb756

Git version: git version 2.25.1
Git vroot status: 0.1.29-568-g93bb7564
.git/config present: true
/var/tmp/tcc status: master 5e73982e
thirdparty/tcc: N/A

**What did you do?**

Browse to https://modules.vlang.io/

**What did you expect to see?**

Lists of modules, with TOC in sorted order, and no duplicates.
 
**What did you see instead?**

As shown in this image of the TOC for `builtin`, a lot of the TOC entries are duplicated  This is only showing a fraction.  It is very cumbersome to try to scroll past all the duplicates to find what you may be interested in.

It is also a visual problem that the upper-level entries are not in sorted order.  You either have to spend a lot of time scrolling back & forth to find what you want, or you are forced to hit Ctrl-F and hope you spell things correctly.

![image](https://user-images.githubusercontent.com/37967083/95755337-4ba76a00-0c72-11eb-8931-a8717c6a142d.png)

**Comment by nedpals** [comment]
Working on that fix :smiley:

**Comment by nedpals** [comment]
Closed. Fixed on #6659.
