### ISSUE TITLE
Issue with embedded structs

### ISSUE THREAD

**Issue by edgeadjei** [vlang/v#6618]
I'm having some issues when trying to embed a struct. I'm sure its user error but just wanted some input.

**V version:** 0.1.29 393889a.a45481b
**OS:** macos, Mac OS X, 10.15.7, 19H2

**What did you do?**
```v
module main

struct Schema{
	collection string
	model T
}
struct UsersSchema {
	first_name string
	last_name string
}
fn main(){
	user := UsersSchema{first_name: "sam", last_name: "wilson"}
	schema := Schema{collection: "my_schema", model: user}
	println(user)
	println(schema)
}
```

**What did you expect to see?**
Since i assigned a generic type definition for model, i expected model to contain the user of type UsersSchema.
 
**What did you see instead?**
```console
./_demo.v:13:44: error: cannot assign struct `UsersSchema` as `T` for field `schema`
   11 | fn main(){
   12 |     user := UsersSchema{first_name: "sam", last_name: "wilson"}
   13 |     schema := Schema{collection: "my_schema", schema: user}
      |                                               ~~~~~~~~~~~~
   14 |     println(user)
   15 |     println(schema)
```

I made change to include the `UsersSchema` as the model type
```v
struct Schema{
	collection string
	model UsersSchema
}
```
but receiving the error below
```console
V panic: get_type_symbol: invalid type (typ=0 idx=0). Compiler bug. This should never happen
0   v                                   0x0000000101b2ce80 v__table__Table_get_type_symbol + 128
1   v                                   0x0000000101ba87c5 v__gen__Gen_cc_type + 53
2   v                                   0x0000000101ba8395 v__gen__Gen_base_type + 69
3   v                                   0x0000000101b84b7b v__gen__Gen_typ + 27
4   v                                   0x0000000101be4894 v__gen__Gen_write_types + 1748
5   v                                   0x0000000101b83bfd v__gen__Gen_write_sorted_types + 557
6   v                                   0x0000000101b7f441 v__gen__Gen_init + 705
7   v                                   0x0000000101b7e416 v__gen__cgen + 2374
8   v                                   0x0000000101b8e4f5 v__builder__Builder_gen_c + 501
9   v                                   0x0000000101b8f377 v__builder__Builder_build_c + 295
10  v                                   0x0000000101b8f728 v__builder__Builder_compile_c + 760
11  v                                   0x0000000101b957eb v__builder__compile + 331
12  v                                   0x0000000101bf5dc6 main__main + 2982
13  v                                   0x0000000101b9c0be main + 78
14  v                                   0x0000000101af16b4 start + 52
15  ???                                 0x0000000000000003 0x0 + 3
Segmentation fault: 11
```

lastly per the documentation, i added the `UsersSchema` directly 
```v
struct Schema{
	UsersSchema
	collection string
}
```
but receiving the error below
```console
./_demo.v:6:1: error: bad type syntax
    4 |     collection string
    5 |     UsersSchema
    6 | }
      | ^
    7 | struct UsersSchema {
    8 |     first_name string
```

Any assistance would be much appreciated. Thanks in advance

**Comment by JalonSolov** [comment]
The first example is an attempt at generics, which are still partially WIP.

Embedded structs are also WIP.  PR #6506 was opened to try to correct this.

**Comment by Larpon** [comment]
Hi @edgeadjei,

Embedded structs are work progress (#6506) and not merged yet.

Using `T` is refering to use of generics in V.

You can try the struct embedding as soon as it gets merged or by checking out the pull request and building it yourself.

However the compiler shouldn't error on this so I'll leave this open.

**Comment by Larpon** [comment]
@JalonSolov was faster, sorry 😄

**Comment by JalonSolov** [comment]
At least we said (basically) the same thing.  :-)

**Comment by edgeadjei** [comment]
Thank you both for the quick response.
I proceeded under the impression that everything in the [docs](https://github.com/vlang/v/blob/master/doc/docs.md#generics) was already implemented. 

It might be a good idea to have some kind of annotation for WIP features in the docs.

Either way i'll wait for (#6506) to be merged and keep an eye out for when generics is complete.

I'm loving this language as it addresses some of the sort comings of golang i.e verbose error handling, module system and concise design.

I'm sure to run into more issues as i put it through its paces so thanks again.

**Comment by medvednikov** [comment]
It says `TODO: this will be implemented later` in the docs.

**Comment by edgeadjei** [comment]
I saw that but since the code sample is incomplete(missing the Widget struct/new_button function) along with the comment being a part of the code, it lead me to think that maybe it was referring to the code sample and not the actual topic at hand.

My comment about annotation could be something like as seen below. So its clear to new comers like myself that the feature is a work in progress.

### Embedded structs `In progress`
V doesn't allow subclassing, but it supports embedded structs:

...

### Generics `Todo`

@medvednikov i'm excited to see where this language goes as its one of the languages i'm most excited about at the moment. Keep up the good work

**Comment by ntrel** [comment]
```v
struct Schema{
	collection string
	model T
}
```
I don't think that having `T` inferred is a good idea at least for now. (I don't think the docs show this). The order of struct fields has to change sometimes if you want to add/change `pub` or private fields. That means the type parameter order will change too. If V allows providing explicit type parameters then that can break code.

**Comment by ntrel** [comment]
I've made a pull explaining some limitations of generics: https://github.com/vlang/v/pull/6674

**Comment by edgeadjei** [comment]
`V 0.1.30 97855ec` - Embedded structs are working as expected.
The below code executes without any errors
```v
module main

struct Schema{
	collection string
	model UsersSchema // Assign user schema to model
}
struct UsersSchema {
	first_name string
	last_name string
}
fn main(){
	user := UsersSchema{first_name: "sam", last_name: "wilson"}
	schema := Schema{collection: "my_schema", model: user}
	println(schema)
}
```

But there seems to be an unexpected error when inheriting from UsersSchema directly.
The code compiles without the print statement.

```v
module main

struct Schema{
	collection string
	UsersSchema // Inherit from user schema
}
struct UsersSchema {
	mut:
		first_name string
		last_name string
}
fn main(){
	mut schema := Schema{
		collection: "my_schema"
	}
	schema.first_name = "sam"
	schema.last_name = "wilson"
	println(schema) // Errors out here 
}
```

```console
/var/folders/7b/pl7lfn355338_rt7ccg18fsc0000gn/T/v/_demo.18208446648297774836.tmp.c:1487:15: error: no member named 'first_name' in 'struct main__Schema'
                indents, it.first_name,
                         ~~ ^
/var/folders/7b/pl7lfn355338_rt7ccg18fsc0000gn/T/v/_demo.18208446648297774836.tmp.c:1488:15: error: no member named 'last_name' in 'struct main__Schema'
                indents, it.last_name,
                         ~~ ^
2 errors generated.
builder error: 
==================
```

This seems like a bug so figured i'd raise the issue here.
Thanks in advance.

**Comment by danieldaeschle** [comment]
this works
```
module main

struct Schema<T>{
	collection string
	model T
}
struct UsersSchema {
	first_name string
	last_name string
}
fn main(){
	user := UsersSchema{first_name: "sam", last_name: "wilson"}
	schema := Schema<UsersSchema>{collection: "my_schema", model: user}
	println(user)
	println(schema)
}
```

**Comment by danieldaeschle** [comment]
```v
module main

struct Schema{
	UsersSchema
	collection string
}
struct UsersSchema {
	first_name string
	last_name string
}
fn main(){
	user := UsersSchema{first_name: "sam", last_name: "wilson"}
	schema := Schema{collection: "my_schema", UsersSchema: user}
	println(user)
	println(schema)
}
```
this as well
