### ISSUE TITLE
'sudo ./v symlink' fails, when 'usr/local/bin' doesn't exist

### ISSUE THREAD

**Issue by ChrisTeister** [vlang/v#6619]
V version: 0.1.29 ce4ee2b
OS: Ubuntu 18.04.5 LTS 64bit

**What did you do?**
I ran 'sudo ./v symlink' to add the symlink as described here: https://github.com/vlang/v/blob/master/README.md#symlinking

**What did you expect to see?**
I expected that the symlink would be created.

**What did you see instead?**
This error: "Failed to create symlink 'usr/local/bin'. Try again with sudo."

The bin folder was missing on my machine.
I created the folder manually and ran the command again, which worked then.
The command should automatically create the folder, when it doesn't exist.

https://github.com/vlang/v/blob/3795aaab5c032c211d8d469a02ffbef67f90c210/cmd/tools/vsymlink.v#L22

**Comment by Larpon** [comment]
@ChrisTeister - out of curiosity, that might help us a bit - where does your system usually keep userland executables?

**Comment by ChrisTeister** [comment]
@Larpon On my machine Go is here '/usr/local/go/' and ioquake3 here '/usr/local/games/ioquake3' for example.

@medvednikov Thanks for the fix :)
