### ISSUE TITLE
Trying to print `none` results in cgen error

### ISSUE THREAD

**Issue by Anthony-Gaudino** [vlang/v#6626]
**V version:** V 0.1.29 c3626bf.a4cc1ab
**OS:** linux, Ubuntu 20.04.1 LTS

**What did you do?**
Executed:
```V
println(none)
```

**What did you expect to see?**
```
none
```

 
**What did you see instead?**
```
cgen error: could not generate string method none_str for type 'none'
```

**Comment by Delta456** [comment]
This works with the latest V.
