### ISSUE TITLE
Variable number of arguments bug

### ISSUE THREAD

**Issue by Joe23232** [vlang/v#6634]
I already ran `v up` on Windows and I got the latest version of `v`.

https://github.com/vlang/v/blob/master/doc/docs.md#variable-number-of-arguments

Based on this part of the tutorial I made a similar script.

```
fn sum(a ...int)
{
    println(a) // Outputs [2, 1]
    println('$a') // Outputs 6552944
}
fn main()
{
    sum(2, 1)
}
```

Strangely this line `println('$a')` outputs `6552944` which doesn't make anysense and I believe this is a bug.

**Comment by bashery** [comment]
on fedor:

```println(a)``  // outputs [2, 1]
```println('$a')``` // outputs 2

**Comment by Joe23232** [comment]
_fedor_ Is this an OS?

**Comment by bashery** [comment]
@Joe23232 Yes,  fedora linux os

**Comment by Joe23232** [comment]
Ah I see, strange, maybe this is a Windows specific bug?

**Comment by bashery** [comment]
Even the outputs on Linux are unexpected.

**Comment by Joe23232** [comment]
Yes indeed, and when i use `tcc` it shows 

```
[2, 1]
1375712
```

But when I use `gcc` it shows this:

```
[2, 1]
6552928
```

**Comment by Joe23232** [comment]
Is your code exactly the same as mine?

**Comment by ntrel** [comment]
This is the C code generated on my Windows PC:
```c
static void main__sum(varg_int a) {
 println(varg_int_str(a));
 println(_STR("%d", 1, a));
}
```
The 2nd line should be:
```v
println(_STR("%.*s", 1, varg_int_str(a)));
```

**Comment by Joe23232** [comment]
Oh I see, so yeah there is a bug here then.
