### ISSUE TITLE
Can't return function from anonymous function

### ISSUE THREAD

**Issue by Anthony-Gaudino** [vlang/v#6644]
**V version:** 0.1.29 c3626bf.0d31b39
**OS:** linux, Ubuntu 20.04.1 LTS

This works if not in anonymous function: https://github.com/vlang/v/blob/73296e486a5c4b6f6d5163bf45c168606fa60e41/vlib/v/tests/fn_test.v#L148

**What did you do?**
```V
func_selector := fn(n int) fn() int {
	return fn(n int) int {
		return n + n
	}
}
```

**What did you expect to see?**
Program compiled successfully

 
**What did you see instead?**
```
error: cannot use `anon_80_7_7` as type `int` in return argument
    1 | func_selector := fn(n int) fn() int {
    2 |     return fn(n int) int {
      |            ~~
    3 |         return n + n
    4 |     }
```

**Comment by medvednikov** [comment]
Good find.
