### ISSUE TITLE
Invalid characters are reported incoreclty in error message

### ISSUE THREAD

**Issue by Anthony-Gaudino** [vlang/v#6645]
**V version:** 0.1.29 c3626bf.0d31b39
**OS:** linux, Ubuntu 20.04.1 LTS

**What did you do?**
Executed these 2:
```V
コンピュータ = 1
```
```V
ã = 1
```

**What did you expect to see?**
```
error: invalid character `コ`
    1 | コンピュータ := 1
      | ^
```
```
error: invalid character `ã`
    1 | ã := 1
      | ^
```
 
**What did you see instead?**
```
error: invalid character `ã`
    1 | コンピュータ := 1
      | ^
```
```
error: invalid character `Ã`
    1 | ã := 1
      | ^
```

Also I would suggest having a more complete error message. Since V only allows ASCII alphanumeric characters as names the error should contain this information, this would make the message much more clear. Example:
```
error: invalid character `コ`. Names must be formed only by ASCII alphanumeric characters and `_`.
    1 | コンピュータ = 1
      | ^
```

**Comment by danieldaeschle** [comment]
this works now
