### ISSUE TITLE
gg.init function is broken

### ISSUE THREAD

**Issue by ShellBear** [vlang/v#665]
**V version:** 
0.1.3

**What did you do?**
```go
import gg

fn main() {
    gg.init()
}
```

**What did you expect to see?**
Just compile
 
**What did you see instead?**
```
pass=2 fn=`gg__init`
panic: gg.v:52
function `gl.init_glad` is private
```

The issue appears because `gl.init_glad()` function is [called](https://github.com/vlang/v/blob/master/gg/gg.v#L52) in `gg.init()` but it's [declared as private](https://github.com/vlang/v/blob/master/gl/gl.v#L23) in the `gl` module.

**Comment by Bowero** [comment]
Has been fixed by making the function public. See: https://github.com/vlang/v/commit/b87e61aa4e6008756bd8876eb1106f1d7662f551
