### ISSUE TITLE
bug of the method chain call

### ISSUE THREAD

**Issue by lydiandy** [vlang/v#6658]
**V version: the newest V 0.1.29 6161115
**OS:mac

**What did you do?**
here is the sample code:
```
module main

struct Point {
mut:
	x int
}

fn (mut p Point) f1() &Point {
	println('f1')
	p.x = 1
	return p
}

fn (mut p Point) f2() &Point {
	println('f2')
	p.x = 2
	return p
}

fn (mut p Point) f3() &Point {
	println('f3')
	p.x = 3
	return p
}

fn main() {
	mut pp := Point{}
	pp.f1().f2().f3() //the method chain call
}

```

**What did you expect to see?**
it should be compiled
 
**What did you see instead?**
got the following error:
```
main.v:28:5: error: cannot use function call as mut
   26 | fn main() {
   27 |     mut pp := Point{}
   28 |     pp.f1().f2().f3()
      |        ~~~~
   29 | }
```

**Comment by lydiandy** [comment]
the following code can be compiled:
it need another mutable p2,
but why we need p2?
```
module main

struct Point {
mut:
    x int
}

fn (p &Point) f1() &Point {
    println('f1')
    mut p2 := p
    p2.x = 1
    return &p2
}

fn (p &Point) f2() &Point {
    println('f2')
    mut p2 := p
    p2.x = 2
    return &p2
}

fn (p &Point) f3() &Point {
    println('f3')
    mut p2 := p
    p2.x = 3
    return &p2
}

fn main() {
    mut pp := Point{}
    pp.f1().f2().f3()
}
```

**Comment by lydiandy** [comment]
in discord, spytheman found:
if I do: //              c.error('cannot use function call as mut', expr.pos)
in the checker, the code compiles and works
I am also not sure what was the purpose
perhaps to disallow something like:
fn (x &Abc) &Abc { return x }

**Comment by rolfschmidt** [comment]
Hi @lydiandy 

> the following code can be compiled:
> it need another mutable p2,
> but why we need p2?
> 
> ```
> module main
> 
> struct Point {
> mut:
>     x int
> }
> 
> fn (p &Point) f1() &Point {
>     println('f1')
>     mut p2 := p
>     p2.x = 1
>     return &p2
> }
> 
> fn (p &Point) f2() &Point {
>     println('f2')
>     mut p2 := p
>     p2.x = 2
>     return &p2
> }
> 
> fn (p &Point) f3() &Point {
>     println('f3')
>     mut p2 := p
>     p2.x = 3
>     return &p2
> }
> 
> fn main() {
>     mut pp := Point{}
>     pp.f1().f2().f3()
> }
> ```

does this still work for you? i get segment fault:
```
# v run .
f1
f2
Segmentation fault (core dumped)
```

**Comment by lydiandy** [comment]
@rolfschmidt,I just tried the code in newest V(V 0.1.29 b712178),it still works.

**Comment by rolfschmidt** [comment]
```v
module main

struct Point {
mut:
    x int
}

fn (p &Point) f1() &Point {
    println('f1')
    mut p2 := p
    p2.x = 1
    return p2
}

fn (p &Point) f2() &Point {
    println('f2')
    mut p2 := p
    p2.x = 2
    return p2
}

fn (p &Point) f3() &Point {
    println('f3')
    mut p2 := p
    p2.x = 3
    return p2
}

fn main() {
    mut pp := Point{}
    pp.f1().f2().f3()
}

```

this example works for me (without & in the return). Btw thanks for your workaround @lydiandy.

**Comment by medvednikov** [comment]
Yes, this is a known bug, it will work as expected.

**Comment by lydiandy** [comment]
this issue has been fixed.
