### ISSUE TITLE
Printing a function results in cgen error

### ISSUE THREAD

**Issue by Anthony-Gaudino** [vlang/v#6661]
**V version:** V 0.1.29 c3626bf.0d31b39
**OS:** linux, Ubuntu 20.04.1 LTS

**What did you do?**
Executed:
```V
fn my_func() fn() int {
    return fn() int {
		return 1
    }
}

println(my_func())
```

Or simply:
```V
println(fn())
```

**What did you expect to see?**
An error message informing that functions can't be printed, or something useful related to the function is printed.

 
**What did you see instead?**
```
cgen error: could not generate string method anon_fn__7_str for type 'anon_fn__7'
```

**Comment by Delta456** [comment]
With the latest V, it successfully outputs `fn () int`.
