### ISSUE TITLE
Allow prepending `+` on numeric values

### ISSUE THREAD

**Issue by Anthony-Gaudino** [vlang/v#6663]
**V version:** V 0.1.29 c3626bf.0d31b39
**OS:** linux, Ubuntu 20.04.1 LTS

In many languages, like C, it's OK to prepend a numeric value with a `+`. Examples:

```C
#include <stdio.h>

int main()
{
    int i = +1;
    printf("%d", +i);

    return 0;
}
```
```C
#include <stdio.h>

int main()
{
    int i = +-1;
    printf("%d", +-i);

    return 0;
}
```

It's also possible to put a sequence of `+` and `-` operators, in this case if you have an even number of `-` it's positive, and negative if odd:
```C
#include <stdio.h>

int main()
{
    int i = -+-+1;
    printf("%d", -+-+i);

    return 0;
}
```

All these will print `1`.
This is kind of redundant, but is valid mathematically.

Please note that bellow the result is `-1` since we apply a decrement:

```C
#include <stdio.h>

int main()
{
    int i = +-+-2;
    printf("%d", +-+--i);

    return 0;
}
```

**In V currently:**
```V
v := +1

println(+v)
}
```

Or:
```V
v := 1

println(+v)
```
Results in:
```
error: expr(): bad token `+`
    5 | }
    6 | 
    7 | v := +1
      |      ^
```

**Comment by elimisteve** [comment]
Hi @Anthony-Gaudino , thanks for your interest in V!

What is a compelling reason to allow a `+` prefix in front of numbers?

**Comment by elimisteve** [comment]
Allowing

```v
v := 1
println(-v)
```

may make some sense, but why permit `+v`?

**Comment by medvednikov** [comment]
This really goes against V's one way philosophy.

`-i` already works. No point in `-+-+i`.

@Delta456 has a simple 5 line PR for this, if we change our mind, we can always use it.
