### ISSUE TITLE
cgen creates two main__main function

### ISSUE THREAD

**Issue by Ekopalypse** [vlang/v#6667]
**V version:** 
**OS:** 
OS: windows, Microsoft Windows 7 Professional v7601 64-bit
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
CC version: N/A

vroot: D:\ProgramData\Compiler\v
vexe: D:\ProgramData\Compiler\v\v.exe
vexe mtime: 2020-10-22 21:26:36
is vroot writable: true
V full version: V 0.1.29 230e986.8ffbcdc

Git version: git version 2.19.1.windows.1
Git vroot status: latest-commit-98-g8ffbcdc5
.git/config present: true
thirdparty/tcc: N/A

**What did you do?**
create two files
~~~
// file test.v
import config

fn main() {
    //
}

// file default_config.v
module config

default_config := {
    'a': 1
}
~~~
and run v -w test.v
**What did you expect to see?**
build runs without error
 
**What did you see instead?**
~~~
...\test.tmp.c: At top level:
...\test.tmp.c:8061:13: error: redefinition of 'main__main'
 8061 | static void main__main() {
      |             ^~~~~~~~~~
...\test.tmp.c:8057:13: note: previous definition of 'main__main' was here
 8057 | static void main__main() {
      |             ^~~~~~~~~~
~~~

**Comment by ntrel** [comment]
V doesn't support global variables like that. By declaring a variable at top-level scope, you are creating a program. So yes, there are two main functions generated. Perhaps you want a `const` declaration?

**Comment by Ekopalypse** [comment]
Thx, no, I was not looking for a const, but I understand your point. If it is not expected/allowed to create such code, I think we can close the problem.

**Comment by medvednikov** [comment]
If there's a C error it means there's a bug in the compiler. It needs to be open until there's a V error.

**Comment by yuyi98** [comment]
Win10 21H2
V 0.1.30 e3fab7e

```v
PS D:\Test\v\tt1> v run .
.\default_config.v:3:1: error: bad top level statement name "default_config"
    1 | module config
    2 |
    3 | default_config := {
      | ~~~~~~~~~~~~~~
    4 |     'a': 1
    5 | }
```
Global variables cannot compile, it will be incorrect as above.

**Comment by Ekopalypse** [comment]
I guess this can be closed as it isn't throwing an C error anymore.
