### ISSUE TITLE
Call V functions from Go?

### ISSUE THREAD

**Issue by finomeng** [vlang/v#6668]
hello everyone! 

Anyone tried to embedded a V code/lib into Golang executable?  
I searched a little but not get a noodle yet. 

my thinking is to replace CGO, write some small hotspot functions in V, especially non-safe code, 
where GC's stop the world is not acceptable. (then, hand managed, dynamic memory allocation is acceptable). 

similar idea with this: 
https://blog.filippo.io/rustgo/
RUSTGO: CALLING RUST FROM GO WITH NEAR-ZERO OVERHEAD

BR fino

**Comment by finomeng** [comment]
want to label it as "question" but cannot found a way.  If this is not the right way to ask questions or discuss, forgive me !

**Comment by medvednikov** [comment]
Sorry for the delay.

V compiles to C, so calling V functions is as easy as calling C functions via cgo.

You can compile V to a .h file, and then include it via cgo.

**Comment by danieldaeschle** [comment]
Can be closed?

**Comment by ouvaa** [comment]
@medvednikov can you show a very very basic example? best if like a http hello world kind of thing where the parser etc uses v backend
