### ISSUE TITLE
gg default font list cause error on V UI (V panic: failed to init the font)

### ISSUE THREAD

**Issue by eviluser7** [vlang/v#6671]
**V version:** V 0.1.29 8ffbcdc
**OS:** Arch Linux

**What did you do?**
I executed example calculator from the V UI repository. This was done on an Arch without any ttf fonts installed.
However, the issue was resolved by installing i.e. noto-fonts.

In the v-lang discord (#v-ui-chat) they mentioned RobotoMono-Regular.ttf being shipped with V installing, however, all V UI examples failed in my Arch.

**What did you expect to see?**
I expected to see the calculator example.
 
**What did you see instead?**
```
V panic: failed to init the font
                                               | 0x55e23222a0e9 | ./calculator(+0x610e9) 
                                               | 0x55e23223a300 | ./calculator(+0x71300) 
                                               | 0x55e23223c5c7 | ./calculator(+0x735c7) 
                                               | 0x55e232245f23 | ./calculator(+0x7cf23) 
                                               | 0x7fea80b12152 | /usr/lib/libc.so.6(__libc_start_main+0xf2) 
                                               | 0x55e2321d024e | ./calculator(+0x724e) 
Segmentation fault (core dumped)
```
The discord chat mentioned making the error "prettier", such as mentioning what fonts should be installed rather than looking in the code.

**Comment by medvednikov** [comment]
Fixed.
