### ISSUE TITLE
Add V to Wikipedia

### ISSUE THREAD

**Issue by jabbalaci** [vlang/v#6682]
Add V to this page: https://en.wikipedia.org/wiki/List_of_programming_languages , and create a wikipedia entry for the language.

**Comment by jabbalaci** [comment]
@nedpals OK. When will 1.0 come out approximately?

**Comment by JalonSolov** [comment]
Considering 0.2 hasn't been released, and 0.3 is planned, it will likely be a while.  No firm dates on anything.

**Comment by medvednikov** [comment]
https://github.com/vlang/v/issues/1388
