### ISSUE TITLE
v fmt is overzealous with multiline comments

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#6684]
> Single line comments are already fixed

v fmt turns
```
/////////////////////////////////////////////////////////////
```
into
```
// ///////////////////////////////////////////////////////////
```
I would prefer one extra check in that logic... only insert a space if the 3rd char is alphanumeric.

This would also apply on
```
/*******************
```
In other words, leave my "ASCII gfx" alone.

Mentioned on Discord, and several others agree.

**Comment by serkonda7** [comment]
What about symbols like? 
```
+ { } `
```

**Comment by JalonSolov** [comment]
Only insert a space if the 3rd character is Alphanumeric.  How's that?

**Comment by serkonda7** [comment]
You mean `//asd` --> `// asd` and `// / ` with a space between will stay as is?

I was asking because the upper symbols (and more) are often the first commented char if existing code is commented.
Also I saw usage of `-` for lists:
```v
// - first comment
// - second item
// - ...
```

**Comment by JalonSolov** [comment]
Yes, if there's a space there already, leave it alone.

I am not talking about REMOVING spaces, I am talking about that fact that `vfmt` currently FORCES the 3rd character to be a space.  I don't want it to force the 3rd character as a space unless the current 3rd character is alphanumeric.

Examples:

Currently `/// -> // /`, should STAY `///`
Currently `//a -> // a` , good.  Keep this.
Currently `//--- -> // ---`, should STAY `//---`

Your last 3 examples should stay exactly as they are.

**Comment by JalonSolov** [comment]
Same thing with multiline comments.

`/**` is changed to `/* *`, should STAY `/**`

**Comment by serkonda7** [comment]
Single line comments are in the PR.
I still struggle with multiline, as I cannot find a convenient way to detect if there currently is a newline after `/*` or not.

**Comment by serkonda7** [comment]
I couldn't create an easy solution for multiline comments even with my updates from #7414.
It seems that for comments only the text is taken as token, so in the parser I don't know where `/*` and `*/` were positioned.

**Comment by serkonda7** [comment]
@JalonSolov what do you think about the formatting of `// (abc)` to `//(abc)`?
I think, fmt should look further than the first character for alphanumeric. Maybe even at the whole line.

**Comment by JalonSolov** [comment]
I think `// (abc)` should stay that way.  If there's already a space, leave it alone.

This issue was about vfmt _adding_ spaces.  Removing them could be bad for intended formatting.

For example, suppose I have this as my comment - I would want it to look _exactly_ the same after vfmt was run:
```
/**************************************
            the_ultimate_function

This function will do literally everything.
You don't need to write anything else

It can:
    - make breakfast
    - wash your clothes
    - write a cryptominer
    - write award-winning music
    - and everything else you can
       possibly imagine!
**************************************/
```

For single-line comments, similar idea:
```
// This comment is...              da bomb!
```

**Comment by JalonSolov** [comment]
If you mean `//(abc)` then no, it shouldn't insert a space there either.  As mentioned, it could be some sort of ASCII art, or who knows what.  You can only be "certain" about alphanumerics.

**Comment by serkonda7** [comment]
Next I will explore how to keep
```v
/****
***
*/
and 
```v
/*
***
****/
