### ISSUE TITLE
Suggestion for V language to cancel colon

### ISSUE THREAD

**Issue by WuZhenXing** [vlang/v#669]
`
areas := ['game', 'web', 'tools', 'science', 'systems', 'GUI', 'mobile']
`
Why can't we use the equal sign directly?
`
areas = ['game', 'web', 'tools', 'science', 'systems', 'GUI', 'mobile']
`

**Comment by Bowero** [comment]
This is an intentional feature.

> Variables are declared and initialized with :=. This is the only way to declare variables in V. This means that variables always have an initial value.

More information can be found here: https://vlang.io/docs#vars
