### ISSUE TITLE
所有权  

### ISSUE THREAD

**Issue by Avey777** [vlang/v#6696]
对比go  最有吸引力的 所有权  实现了吗？   没有实现rust的内存管理机制， 其实没什么吸引力的。
![image](https://user-images.githubusercontent.com/35259040/97581594-b822b700-1a2f-11eb-856b-6369bcd38f5f.png)

**Comment by nedpals** [comment]
Translated using machine translation:
> Has the most attractive ownership of comparison go realized? The memory management mechanism of Rust is not implemented, which is actually not attractive.

**Comment by takase1121** [comment]
Rough translation (I speak Chinese):
> Is Ownership (Probably referring to rust's ownership system) implemented yet? (OP is comparing V to golang) Without Rust's memory management mechanism, this language is not attractive at all.

**Comment by JalonSolov** [comment]
No, V does not do Ownership similar to Rust.  If that is the major criterion as a deciding factor of using a language, then I wish Avey777 much happiness with Rust, since Rust is the _only_ language that implements that type of ownership.
