### ISSUE TITLE
Can't assign `int` to `int?`; `?T` optional type syntax

### ISSUE THREAD

**Issue by ntrel** [vlang/v#67]
This program gives a compile error:
```rust
fn f() int? {
	return 5
}

fn main() {
	mut o := f()
	o = 4 // line 7
}
```
```
test.v:7
cannot use type `int` as type `Option_int` in assignment
```
(BTW, shouldn't optional types be written `?T` instead of `T?`, so it reads *optional T* left to right like Go type modifier philosophy, not *T optional*? `?T` [is how Zig](https://ziglang.org/documentation/master/#Optionals) writes them).

*Edit:* Clarify last sentence.

**Comment by medvednikov** [comment]
This error is correct.

You need to unwrap an optional with `or`.

**Comment by medvednikov** [comment]
```
fn f() int? {
	a := 5
	return a
}

fn main() {
	mut o := f() or {
		return
	}
	o = 4
}
```

**Comment by medvednikov** [comment]
`T?` is the syntax used by Swift and C#, two very popular languages.

**Comment by ntrel** [comment]
> ```mut o := f() or {```

@medvednikov No, I want `o` to be an optional. Optionals should allow assignment from their value type.

**Comment by ntrel** [comment]
> T? is the syntax used by Swift, C#, Kotlin. I think there are more.

Yes, but those languages don't use Go syntax for types (read left to right), they read right to left.

**Comment by medvednikov** [comment]
Swift and Kotlin do.

**Comment by medvednikov** [comment]
> Optionals should allow assignment from their value type.

Indeed. This is not implemented yet.

**Comment by ntrel** [comment]
I tried to find pointer and array syntax in Swift and Kotlin, in what I saw they don't seem to use Go `*T`, `[]T` type syntax, but it was hard to find clear documentation. But another argument is with optional pointers:
```rust
fn f() *int?
```
Does `f` return a pointer to an optional int, or an optional pointer to an int? With `?T` syntax, it's clear:
```rust
?*int // optional pointer to int
*?int // pointer to optional int
```

**Comment by medvednikov** [comment]
I don't think pointer optionals are going to be allowed.

Pointers in general should be rarely used in V.

**Comment by ntrel** [comment]
> I don't think pointer optionals are going to be allowed.

How should we model pointers that can be null then? This is a key motivation for optional types, replacing null. How will we port programs from other languages to V?

> Pointers in general should be rarely used in V.

Reference types are a crucial feature to refer to heap allocated data, or the same data from multiple places, what will we use instead of pointers?

**Comment by medvednikov** [comment]
Right now there's `isnil` builtin function to handle C nil pointers, but using optionals sounds like a better idea.

Then it makes sense to use `?*int` syntax.

**Comment by ntrel** [comment]
Great! When the source is available, I might be able to update the compiler to use `?T` instead of `T?`. Let me know if you want me to update the docs and examples if you decide to implement the change.

**Comment by medvednikov** [comment]
This particular problem has just been fixed, although optionals still need lots of work.

`?T` syntax has been implemented to replace `T?`

`opt_int = 5` is now allowed.

**Comment by ntrel** [comment]
> ?T syntax has been implemented to replace T?
> opt_int = 5 is now allowed.

Great, thanks. I filed the other issues you mentioned as part of #261.
