### ISSUE TITLE
bad formatting of struct in return match

### ISSUE THREAD

**Issue by serkonda7** [vlang/v#6702]
**V version:** V 0.1.29 db59585
**OS:** Manjaro

**What did you do?**
vfmt this:
```v
return match style {
	.grid { Border{} }
	.plain {Border{style: .plain}}
}
```

**What did you expect to see?**
Something like this, but at least no tab issues.
```v
return match style {
	.grid { Border{} }
	.plain { Border{ style: .plain } }
}
```
 
**What did you see instead?**
```v
return match style {
	.grid { Border{} }
	.plain { Border{
			style: .plain
		} }
}
```

**Comment by danieldaeschle** [comment]
shouldn't it be at least:
```v
return match style {
	.grid { Border{} }
	.plain { Border{
		style: .plain
	} }
}
```
if more fields are there and it's too long for one line.

**Comment by danieldaeschle** [comment]
two things to fix:
one line up to one field
and indent to fix.

**Comment by serkonda7** [comment]
Yeah, you're right.
