### ISSUE TITLE
Being able to know the type of a generic

### ISSUE THREAD

**Issue by StunxFS** [vlang/v#6704]
Good! Time without going through here.
Congratulations on the support of embedded structs.

I wanted to ask for the support (if it is not planned) of being able to know the type of a generic.
V currently, when using a `typeof(T)`, it returns a 'T' and not the type of the generic, it should return the type of the generic.

The use of type 'T' should also be allowed within the function code. Which V does not currently allow to do, except to be used in the parameters and as a return type.

_V is life, V is love._

**Comment by medvednikov** [comment]
yes, `typeof(T)` will return the actual type

**Comment by ntrel** [comment]
T already represents a type so `typeof(T)` is an error just like `typeof(int)`.
I've now implemented `typeof(expr)` where expr has generic type T.

**Comment by ntrel** [comment]
> type 'T' should also be allowed within the function code

It is supported for a few use cases, but others need fixing. Please file a separate issue with specific use cases.

**Comment by StunxFS** [comment]
> It is supported for a few use cases, but others need fixing. Please file a separate issue with specific use cases.

Just give me 72 hours to think what things could be done with this (?)

**Comment by ntrel** [comment]
`T.name` now works too #6783.
