### ISSUE TITLE
Compound Assignment Operators on for loops

### ISSUE THREAD

**Issue by Henrixounez** [vlang/v#671]
**V version:**
V 0.1.4

**What did you do?**
```
fn main() {
  for i := 0; i < 10; i += 4 {
    println(i)
  }
}
```

**What did you expect to see?**
```
0
4
8
```
 
**What did you see instead?**
```
panic: test.v:2
unexpected token: `for`
```

Previously mentionned in #632

**Comment by medvednikov** [comment]
Yes, this was introduced today. Very interesting bug.
