### ISSUE TITLE
Example news_fetcher.v error

### ISSUE THREAD

**Issue by elastica9999** [vlang/v#672]
V version 0.1.4
OS   --> linux ubuntu 16.04 64bits
doing -->  v run news_fetcher.v

error --> 
pass=2 fn=`fetch`
panic: news_fetcher.v:28
function `lock` is private

**Comment by medvednikov** [comment]
Fixed.

`git pull`

**Comment by elastica9999** [comment]
Waa.. fixed.. as speed as vlang
