### ISSUE TITLE
infix expr: cannot use `map_string_string` (right expression) as `x.json2.decode`

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#6722]
**V version:** V 0.1.29 aecdfb0
**OS:** Windows 10 WSL2 Ubuntu 20.04

**What did you do?**
```v
import x.json2

fn main() {
	test := '{}'
	a := json2.decode<map[string]string>(test)
}
```

**What did you expect to see?**
works
 
**What did you see instead?**
```
test.v:5:19: error: infix expr: cannot use `map_string_string` (right expression) as `x.json2.decode`
    3 | fn main() {
    4 |     test := '{}'
    5 |     a := json2.decode<map[string]string>(test)
      |                      ^
    6 | }
```

**Comment by Delta456** [comment]
the error now:

```
main.v:5:2: warning: unused variable: `a`
    3 | fn main() {
    4 |     test := '{}'
    5 |     a := json2.decode<map[string]string>(test)
      |     ^
    6 | }
/code/root/v/vlib/x/json2/json2.v:30:6: error: unknown method: `map[string]string.from_json`
   28 |     }
   29 |     mut typ := T{}
   30 |     typ.from_json(res)
      |         ~~~~~~~~~~~~~~
   31 |     return typ
   32 | }
```

**Comment by danieldaeschle** [comment]
@nedpals can we make this work without `from_json`?

**Comment by nedpals** [comment]
> @nedpals can we make this work without `from_json`?

I'm working on a codegen right now. I'll be posting the draft PR later.

**Comment by danieldaeschle** [comment]
Can you do it without compiler magic? Doing it with `$for` `$if` would be awesome!

**Comment by nedpals** [comment]
Thats my first idea but then there are lots of limitations when using $if and $for. No worries though, the codegen will be the same as the enum flag where it adds additional V code at the end.

**Comment by nedpals** [comment]
I'll be switching to comptime for and if similar to the docs once they're OK to use now

**Comment by danieldaeschle** [comment]
List what we need in comptime, then we implement that first. Otherwise we have to refactor everytime.

**Comment by nedpals** [comment]
True. I'll be writing a separate issue for this to address the issues.

**Comment by danieldaeschle** [comment]
```v
import x.json2

fn main() {
	test := '{}'
	a := json2.decode<map[string]string>(test) or { map[string]string{} }
}
```

```
vlib/x/json2/json2.v:31:6: error: unknown method or field: `map[string]string.from_json`
   29 |     res := raw_decode(src) ?
   30 |     mut typ := T{}
   31 |     typ.from_json(res)
      |         ~~~~~~~~~~~~~~
   32 |     return typ
   33 | }
```

**Comment by Delta456** [comment]
There is still an error.

```
/v/vlib/x/json2/json2.v:24:6: error: unknown method or field: `map[string]string.from_json`
   22 |     res := raw_decode(src)!
   23 |     mut typ := T{}
   24 |     typ.from_json(res)
      |         ~~~~~~~~~~~~~~
   25 |     return typ
   26 | }
```

**Comment by JalonSolov** [comment]
The original example works now, with a warning.  If you add a `println(a)`, it works and prints `{}`.

**Comment by Delta456** [comment]
> The original example works now, with a warning about `unused variable a`. If you add `println(a)`, it works and prints `{}`.
> 
> This is with `V 0.3.2 5fc7b6d`

Oh yes, it does. Closing the issue.
