### ISSUE TITLE
cannot print optional type

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#6724]
**V version:** V 0.1.29 aecdfb0
**OS:** Windows 10 WSL2 Ubuntu 20.04

**What did you do?**
```v
fn test() ?string {
	return none
}

fn main() {
	println(test())
}
```

**What did you expect to see?**
output like:
`?none` or `Optional(none)` or `none`
 
**What did you see instead?**
```
test.v:6:10: error: cannot print optional type
    4 | 
    5 | fn main() {
    6 |     println(test())
      |             ~~~~~~
    7 | }
```

**Comment by danieldaeschle** [comment]
@medvednikov what should it print?

**Comment by StunxFS** [comment]
I think it should print this:
https://github.com/vlang/v/blob/9d5be12517e6fde00b60d30500e1622f35ae034e/vlib/builtin/option.v#L26-L34
