### ISSUE TITLE
REPL stops to work

### ISSUE THREAD

**Issue by 7urkm3n** [vlang/v#673]
**V version:** 0.1.3
**OS:**  OSX 10.14.5

Once starting `V` repl, Typing 2-3 times enter kicks from repl (actually stops).

```
x := "x" (enter)
(enter)
(repl stopped)
```

or 

```
x := "x" (enter)
println(x) (enter)
// empty log (enter)
(repl stops)
```

**Comment by Bowero** [comment]
In `main.v`, this line can be found:

https://github.com/vlang/v/blob/2ca6859982303d11335a85aaa583064cd09443c7/compiler/main.v#L861-L863

This shows that this is intended behavior. Unless your bug report is about the having to press enter multiple times, there is no bug here.

**Comment by 7urkm3n** [comment]
@Bowero Probably, i will work on that line as a feature to able to hit `enter` multiple times.
