### ISSUE TITLE
vfmt adds braces for trailing struct literal argument

### ISSUE THREAD

**Issue by ntrel** [vlang/v#6730]
**V version:** recent git
**OS:** Windows 8

**What did you do?**
ran vfmt on code in #6716.

**What did you expect to see?**
code unchanged
 
**What did you see instead?**
```diff
-				sig := c.table.fn_signature(imethod, skip_receiver: true)
+				sig := c.table.fn_signature(imethod, {
+					skip_receiver: true
+				})
```

**Comments**
Probably vfmt should always use trailing syntax.

**Comment by serkonda7** [comment]
I invested a huge amount of time into a fix, just to get the result that this bug will persist for functions from different files. 
Otherwise it would break sumtypes.

**Comment by serkonda7** [comment]
**TODO**
- [ ] update parser to include relevant information
- [ ] Create followup on https://github.com/vlang/v/pull/7072
