### ISSUE TITLE
Single line if

### ISSUE THREAD

**Issue by ejtizado** [vlang/v#6738]
Because V force the use of {} I think it could permit the single line of if as Ruby

```
x = n if x == 0
```
instead
```
if x == 0 {
 x = n
}
```

**Comment by StunxFS** [comment]
This is not the same as: ``x = if x == 0 { n }``?
In Vala/C/C++/C# they use: ``x = (x == 0)? n : x;``

**Comment by danieldaeschle** [comment]
i will always for `{}`. You can do `if x == 0 {} else {}` in one line

**Comment by medvednikov** [comment]
Thanks for the suggestion, but no. This goes against the "one way" philosophy, and is worse for readability, because it violates the expected "if => then" flow. The if condition will not be visible in complex cases.

It fits in Ruby, but not not in V.

**Comment by medvednikov** [comment]
V is not about saving keystrokes. We type quickly, code readability has a much higher priority.
