### ISSUE TITLE
libui gui library using ?

### ISSUE THREAD

**Issue by elastica9999** [vlang/v#674]
Why not using "https://github.com/andlabs/libui" (win, mac , linux multi-library) to quick implement ui and gui functions to vlang ?

Congratulations for your work

**Comment by ernierasta** [comment]
Hi, this was also my idea. While libui is in alpha version (for long time), it is actively developed and very promissing. IMHO it is very usable in current state for simplier gui's. There are problems, and usualy it is good idea to tests visualy programs on platforms You target, but it is best option if You need small multiplatform ui library. And IMO API is very good.

**Comment by medvednikov** [comment]
Thanks, I'll think about it.

**Comment by Niek** [comment]
Another +1 for libui bindings

**Comment by hamad-almamari** [comment]
I dont think this lib should added as core lib into vlib!!!

Are we going just keep piling c libraries into v !! If anyone want to use this library he can easily bind it. No need to be including in the main source code.

**Comment by medvednikov** [comment]
`ui` is not part of vlib.

**Comment by medvednikov** [comment]
I gave it a thought and decided to only use my ui module written 100% in V.
