### ISSUE TITLE
print of reference type misses & in output

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#6743]
**V version:** V 0.1.29 518da92
**OS:** Windows 10 WSL2 Ubuntu 20.04

**What did you do?**
```v
struct Bar {}

fn main() {
	x := &Bar{}
	println(x)
}
```

**What did you expect to see?**
`&Bar{}`
 
**What did you see instead?**
`Bar{}`

**Comment by Larpon** [comment]
This would be handy to have indeed.

**Comment by yuyi98** [comment]
Fixed.
