### ISSUE TITLE
Embedded struct's fields do not initialized properly.

### ISSUE THREAD

**Issue by Tembocs** [vlang/v#6752]
**V version: 0.1.29 6229965** 
**OS:  windows, Microsoft Windows 10 Pro v19042 64-bit** 

**What did you do?**
Had this V code run with ```v run main.v```:
```v
module main

struct Person {
    name string
    age int
}

struct Officer {
    Person
    title string
    location string
}

fn main() {
    // Embededed
    data_clerk := Officer {
        name: 'Steven Paul'
        age: 37
        title: 'Chief Data Clerk'
        location: 'Michigan'
    }

    // Without embedding
    person := Person {
        name: 'Staut Tyra'
        age: 40
    }

    println('Embedded structs ...')
    println(data_clerk.name)
    println(data_clerk.age)
    println(data_clerk.title)

    println('\nWithout embedding ...')
    println(person.name)
    println(person.age)
}
```

**What did you expect to see?**
All embedded struct fields initialized properly.
 
**What did you see instead?**
All embedded struct fields were not initialized properly as seen in the below output:
```
Embedded structs ...

0
Chief Data Clerk

Without embedding ...
Staut Tyra
40
```

As you can see, the first embedded struct field was initialized as empty instead of ```Steven Paul``` and the second with 0 instead of 37.

**Comment by danieldaeschle** [comment]
Currently it's needed to do it like this:

```v
  data_clerk := Officer {
        Person: Person {
                name: 'Steven Paul'
                age: 37
        }
        title: 'Chief Data Clerk'
        location: 'Michigan'
  }
```

**Comment by mcastorina** [comment]
The original example now (V 0.2.2 c03798e) produces a compile-time error (unknown field)
 which prevents confusion on how to properly initialize an embedded struct. I think this issue can be closed now.
