### ISSUE TITLE
vfmt adds invalid module prefix to fn aliases

### ISSUE THREAD

**Issue by serkonda7** [vlang/v#6764]
> I haven't looked over #6755 if this particular problem is mentioned there, due to the huge amount of problems reported at once.

**V version:** V 0.1.29 3e5871f
**OS:** Manjaro

**What did you do?**
`fmt -w vlib/v/tests/fn_test.v`:
```v
mut arr := []MyFn{}
arr << MyFn(test)
```

**What did you see instead?**
The fn aliases are prefixed with main, which breaks compilation.
```v
mut arr := []main.MyFn{}
arr << main.MyFn(test)
```

**Comment by spytheman** [comment]
Fixed in 338f3af, the regression test is in vlib/v/fmt/tests/fntype_alias_array_keep.vv : 
```v
type MyFn = fn (int) int

mut arr := []MyFn{}
arr << MyFn(test)
```
