### ISSUE TITLE
want TODO() like kotlin

### ISSUE THREAD

**Issue by kahsa** [vlang/v#6784]
and scope funtions apply().

**Comment by serkonda7** [comment]
Could you please add some more details for people like me that don't know Kotlin.

**Comment by kahsa** [comment]
When you have a function which return somethig, it must be implemented to compile, but not soon need to be implemented,  you write TODO() in that funtion body without return statement, then you can compile it.

When run the program, and if that not implemented function should be called, raise NotImplementedException, but when not called no problem occurs.

https://blog.frankel.ch/make-life-easier-kotlin-stdlib/

**Comment by kahsa** [comment]
It is especially useful for skeleton.

**Comment by ntrel** [comment]
> TODO() in that funtion body without return statement

You could use `panic('not implemented!')` instead?

**Comment by ntrel** [comment]
Re: `apply` from the link:
```kotlin
fun createCountriesCombo() = ComboBox<String>("Country").apply {
    setItems("Switzerland", "France", "Germany", "Austria")
    isEmptySelectionAllowed = false
    placeholder = "Choose your country"
    addValueChangeListener {
        bus.post(CountryChangeEvent(value))
    }
}
```
In V this might be something like:
```v
countries := {
	mut cb := ComboBox<String>{
		label: "Country", 
		isEmptySelectionAllowed: false,
		placeholder: "Choose your country"
	}
	cb.setItems("Switzerland", "France", "Germany", "Austria")
	cb.addValueChangeListener(fn() {
		bus.post(CountryChangeEvent{value})
	})
	cb
}
```
Assignment from a block is not implemented yet, but it's planned.

**Comment by kahsa** [comment]
> > TODO() in that funtion body without return statement
> 
> You could use `panic('not implemented!')` instead?

That's it!
Thank you.

**Comment by Delta456** [comment]
I am now closing this then.
