### ISSUE TITLE
Sum Type Mess.

### ISSUE THREAD

**Issue by amoyyy** [vlang/v#6788]
```
struct Foo {
pub mut:
    a int
}

fn (mut foo Foo) set(){
    foo.a = 505
}

struct Bar {
pub mut:
    a int
}

type Sum = Foo | Bar

fn new_sumtype(para string) Sum{
    match para {
        "foo" { return Foo{} }
        "bar" { return Bar{} }
        else { panic("$para not found!") }
    }
}

fn (a Sum) set(){
    match a {
        Foo { a.set()}
        Bar { }
    }
}

fn (a Sum) get_a() int{
    match a {
        Foo { a.a}
        Bar { a.a}
    }
}

mut foo := new_sumtype("foo")
mut bar := new_sumtype("bar")
foo.set()
println(foo.get_a())
println(bar.get_a())
```
It gives error: `a` is immutable, declare it with `mut` to make it mutable.
Tried many times , with & or not, I still can't modify the sumtype object which I actually needed.
The result is really annoying, makes it nearly impossible for me to make further progress.
how soon could either Sum or Generic be stable enough?

**Comment by medvednikov** [comment]
But the error is very clear: declare a with `mut`:

```
fn (mut a Sum) set(){
    match mut a {
        Foo { a.set()}
        Bar { }
    }
}
```

**Comment by amoyyy** [comment]
@medvednikov I have made such attempt already. It did pass the compilation. But the object `foo` isn't modified as expectation. Other attempts including using `*` or `&` leads to the `0 0` output or a compile error. 
Thanks for the team work, I'm really fancinated with V language. I've spent lots of time exploring the usage of V modules, wishing to build fast and stable codes based on V.

**Comment by medvednikov** [comment]
Your program found several bugs in the language. `get_a` needs a return, the compiler doesn't catch that. Once I add a return there, there's a reference error.

Will fix, thanks for reporting.

**Comment by ntrel** [comment]
I do (now) get an error:
```
sumerr.v:32:1: error: missing return at end of function `get_a`
   30 | }
   31 |
   32 | fn (a Sum) get_a() int{
      | ~~~~~~~~~~~~~~~~~~~~~~
   33 |     match a {
   34 |         Foo { a.a}
```
Adding returns, I then get the correct output:
```
505
0
```
