### ISSUE TITLE
js: cast not working

### ISSUE THREAD

**Issue by trufae** [vlang/v#6796]
**V version:** V 0.1.29 6271798
**OS:** macOS 10.15

**What did you do?**
```
fn main() {
	a := 3.123
	b := int(a)
	println('$a $b')
}
```

in C: `3.123 3`
in JS: `3.123 3.123`

by using ` b := int(a) | 0` the "cast" works. and `int` is required because f64+or doesnt passes the checker. But in JS the way to cast from float to int is by using the |0 (as it was defined in asm.js)

**What did you expect to see?**

same behaviour on both backends
 
**What did you see instead?**

wrong behaviour in the js backend

**Comment by leahlundqvist** [comment]
This is dependant on #7056
