### ISSUE TITLE
Prebuilt binary for Windows fails to execute properly

### ISSUE THREAD

**Issue by HugoFlorentino** [vlang/v#6806]
**V version:** 0.1.29 46c5a2c
**OS:** Windows 10.0.18362.30

**What did you do?**
First I extracted TCC 0.9.27 in C:\tcc\ and added the folder as first entry in the PATH variable, and verified tcc executes perfectly.
Then I decompressed the contents of Windows folder from latest V prebuilt binary zipfile in C:\v\
Then I tried to execute these commands from C:\v\
v
v up
v symlink
v doctor

**What did you expect to see?**
a proper output in each case

 
**What did you see instead?**
v:
For usage information, quit V REPL and run `v help`
cannot compile `C:\v\cmd\tools\vrepl.v`:
C compilation failed.
builder error: exec failed (CreateProcess) with code 2: El sistema no puede encontrar el archivo especificado.
 cmd: gcc @C:\Users\Usuario\AppData\Local\Temp\v\vrepl.tmp.c.rsp
(translation: OS couldn't find specified file)

v up:
cannot compile `C:\v\cmd\tools\vup.v`:
C compilation failed.
builder error: exec failed (CreateProcess) with code 2: El sistema no puede encontrar el archivo especificado.
 cmd: gcc @C:\Users\Usuario\AppData\Local\Temp\v\vup.tmp.c.rsp

v symlink:
cannot compile `C:\v\cmd\tools\vsymlink.v`:
C compilation failed.
builder error: exec failed (CreateProcess) with code 2: El sistema no puede encontrar el archivo especificado.
 cmd: gcc @C:\Users\Usuario\AppData\Local\Temp\v\vsymlink.tmp.c.rsp

v doctor:
cannot compile `C:\v\cmd\tools\vdoctor.v`:
cmd\tools\vdoctor.v:2:8: warning: module 'term' is imported but never used
    1 | import os
    2 | import term
      |        ~~~~
    3 | import time
    4 | import v.util
C compilation failed.
builder error: exec failed (CreateProcess) with code 2: El sistema no puede encontrar el archivo especificado.
 cmd: gcc @C:\Users\Usuario\AppData\Local\Temp\v\vdoctor.tmp.c.rsp

**Comment by JalonSolov** [comment]
Right now, it is better to clone the repo and build it yourself (using `make.bat`).  At least until the download is updated to a newer version.

You can also install an updated copy of tcc for V to use by running `make.bat -tcc`.  If you do that, though, you should remove the one you've installed in C:\tcc... depending on where you installed that from, it could be very much out of date.

**Comment by HugoFlorentino** [comment]
> 
> 
> Right now, it is better to clone the repo and build it yourself (using `make.bat`). At least until the download is updated to a newer version.
> 

Actually I can't build V with my installed copy of TCC:

C:\v>make
Building V
Updating vc...

Attempting to build v.c with GCC...
 > GCC not found

Attempting to build v.c with MSVC...


Failed to compile - Create an issue at 'https://github.com/vlang/v' with the following info:

"cl.exe" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Exiting from error


> You can also install an updated copy of tcc for V to use by running `make.bat -tcc`. If you do that, though, you should remove the one you've installed in C:\tcc... depending on where you installed that from, it could be very much out of date.

This doesn't work either:

C:\v>make
Building V
Updating vc...

Attempting to build v.c with GCC...
 > GCC not found

Attempting to build v.c with MSVC...


Failed to compile - Create an issue at 'https://github.com/vlang/v' with the following info:

"cl.exe" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Exiting from error

**Comment by JalonSolov** [comment]
Very strange.  :-\

If you want to install GCC, you can get it from https://winlibs.com - just scroll down a bit to the download links, and you can usually find the latest version of gcc, in a windows version.

**Comment by ntrel** [comment]
Perhaps you need to remove the old tcc first. Or you could try:
`git clone https://github.com/vlang/tccbin_win thirdparty/tcc` from inside your v git folder and then `make.bat -tcc`

**Comment by HugoFlorentino** [comment]
> 
> 
> Very strange. :-\
> 
> If you want to install GCC, you can get it from https://winlibs.com - just scroll down a bit to the download links, and you can usually find the latest version of gcc, in a windows version.

Thanks, only after installing GCC would V compile using TCC.
Quite odd, since both the one I had in C:\tcc and the one in thirdparty directoy of freshly compiled V, report the same version.

**Comment by Ekopalypse** [comment]
I assume it can be closed as the weekly prebuild binaries are much more up to date these days.
