### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by h5rdly** [vlang/v#683]
Hi,

Cheers on this prject, I'm looking forward to tinkering with V.

I see that Linux and MacOS binaries are released. Can the same be done for Windows?

You don't always choose Windows, but sometimes Windows chooses you... 

Cheers

**Comment by medvednikov** [comment]
Yes. Today :)

**Comment by guileen** [comment]
As I read the compiler code. Currently the compiler compile v code to c code, then use a C compiler to compile the translated C code. It means that C compiler is always required even the prebuilt windows binary is provide.

Is that true? Actually I want a prebuilt windows binary without MSVC and MingW required.

**Comment by kingofoz** [comment]
Hi Alex, as I know, many people, like me, are waiting for the Windows binary. :)

**Comment by liov** [comment]
yesterday say taday

**Comment by Tembocs** [comment]
Hi Alex, no Windows binaries yet? Can't see any from download page. I've tried to build it my self from source on Windows 10 x64. Neither Visual Studio 2019 nor MinGW-x64 succeeds.

**Comment by ntrel** [comment]
> It means that C compiler is always required even the prebuilt windows binary is provide.

Good point, but for now I think that's OK. Ideally V frontend hooked up to LLVM or GCC backend as an option would avoid this and give the best optimization. (Outputting C is really great for portability so that should be kept too).

**Comment by medvednikov** [comment]
This was fixed. You can get the binary from the main page, or build it from source in seconds.

**Comment by atoroc** [comment]
Hi Alex. Congratulations for V, i'd like to give a try.
Please can you provide me with the windows binary link ?
Best Regards.

**Comment by douglas1** [comment]
> 
> 
> This was fixed. You can get the binary from the main page, or build it from source in seconds.

Where are the binaries???
