### ISSUE TITLE
fmt removes fn argument names in C bindings

### ISSUE THREAD

**Issue by christopherzimmerman** [vlang/v#6833]
V full version: V 0.1.29 6271798.b96a024

Calling `v fmt` on:

```v
struct C.bar{}
fn C.foo(cb fn(c C.bar, d voidptr))
```

Produces:

```v
struct C.bar {
}

fn C.foo(cb fn (C.bar, voidptr))
```

When an argument of the callback is a C struct, this fails to compile with:

```
debug.v:4:18: error: bad type syntax
    2 | }
    3 | 
    4 | fn C.foo(cb fn (C.bar, voidptr))
      |    
```

Not sure if the formatter needs to leave the argument name, or if V needs to recognize the latter as valid code.

**Comment by serkonda7** [comment]
With latest V, the code compiles fine afterwards.
