### ISSUE TITLE
c error: incomplete universal character name \u

### ISSUE THREAD

**Issue by serkonda7** [vlang/v#6849]
**V version:** V 0.1.29 0c54ebd
**OS:** Manjaro

**What did you do?**
```v
println('\u')
```

**What did you expect to see?**
Either print nothing or give a compiler error.
 
**What did you see instead?**
```
/tmp/v/testy.15165163179236975449.tmp.c: In function ‘main__main’:
/tmp/v/testy.15165163179236975449.tmp.c:8048:22: error: incomplete universal character name \u
 8048 |  println(tos_lit("\u"));
      |
...
```

**Comment by JalonSolov** [comment]
The error message needs work as well.  "incomplete unicode character code" or something like that would be better.
