### ISSUE TITLE
Question to those with experience with Azure CI

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#685]
Hello,

Travis has been successfully set up, there's one things left to fix with Azure.

I added `sudo apt install ...` line, and it stopped working:

```
      - script: |
        sudo apt install libglfw3 libglfw3-dev libfreetype6-dev libcurl3-dev
        displayName: 'Install Dependencies'
```

I tried without `sudo` as well.

https://github.com/vlang/v/blob/master/azure-pipelines.yml

```
Cannot create and populate list type Microsoft.TeamFoundation.DistributedTask.Pipelines.PipelineValidationErrors. Path 'errors', line 1, position 11.
```

**Comment by CristianHenzel** [comment]
Try apt install **-y**

**Comment by medvednikov** [comment]
Now I'm getting

```
/azure-pipelines.yml: (Line: 9, Col: 9, Idx: 217) - (Line: 9, Col: 9, Idx: 217): While scanning a simple key, could not find expected ':'.
```

**Comment by CristianHenzel** [comment]
Since you're using single commands, you could put them on the same line. If you want to keep them on separate lines try indenting them. See https://github.com/microsoft/azure-pipelines-yaml/blob/382716debe8c3923240f77aa7516237cb320307d/templates/empty.yml for an example.

**Comment by medvednikov** [comment]
Thanks a lot, that fixed it @CristianHenzel
