### ISSUE TITLE
any type

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#6853]
This issue is to collect all ways to implement the `any` type.

## Does `any` needs to be a keyword or can it be a type alias?
```v
// type alias
type any = voidptr
```
Since `any` is supposed to work with all types. We also have to check which type it currently is, like with sumtypes.
> Should `any` to work like TypeScripts `unknown`? https://stackoverflow.com/questions/51439843/unknown-vs-any

## `any` implementation
If we go the old way of sumtypes with the `void* _object`, then we have the problem like with the sumtypes of smartcasting.
Then the new implementation of sumtypes has the problem with `any` that all types must be known.
> `any` is nothing other than a sum type with all available types?

Is it possible to compile `any` as a sum type with all known types at compiletime?
How does this behave with modules? Cached modules?

### Checks
This should be possible and works like sum types.
```v
fn foo(var1 any) {
    if var1 is string {
        // smartcasted
    }
}
```

_Let's discuss a bit!_

**Comment by Terisback** [comment]
Agree

**Comment by danieldaeschle** [comment]
A hint: we also have to take care that `any` works also with functions. Not only structs, string, int etc.

**Comment by danieldaeschle** [comment]
@medvednikov i thought about that a lot. i don't think we need it. we have sum types and generics. if we would introduce an any type it would result in a more weak type system.

**Comment by medvednikov** [comment]
Yeah, I agree. With generics, interfaces, sum types it's unlikely to be needed.

My original idea was to make it behave like Go's `interface{}`. But `interface{}` has to be used in Go because there are no generics/sum types.

**Comment by yutotakano** [comment]
Sum types are definitely cool and useful, but JSON decoding with sum types as field values is unfortunately not possible right now.

This means that the following:

```vlang
struct ... {stuff here} 

type MessageTypes = NotFoundErrorMessage | ServerErrorMessage | ClientErrorMessage
struct Response {
  messages []MessageTypes
}
json.decode(Response, "{messages: [{"specifickeyforthiserror": true}, {"notfoundspecifickey": 123}]}"
```
will not compile, throwing a "json: MessageTypes is not struct" error.

This makes `any` quite useful, or at least necessary unless sum types are supported in JSON decoding.

**Comment by danieldaeschle** [comment]
Yeah, it will work in future. But it's not related to this issue. It's a bug. If we have no issue for it create a new one.
