### ISSUE TITLE
Proposal: release plan

### ISSUE THREAD

**Issue by axetroy** [vlang/v#6854]
I found that V does not have a release plan.

Currently, If the user wants to upgrade V, only `v up` command to do that.

And there are some doubts here:

- Changelog
- Github Release
- `v up` command
- website documentation

**This leads users to be very confused about this**

1. The changelog is a few months ago and is no longer updated
2. current changelog is `0.1.27` but the latest release is `0.1.29`
3. documentation(vlib) haven't updated for a long time

**This prevents new users from getting started from V**

So I think it would be great if you can make a release plan.

It can be automated easily.

1. Create a new pull request to update the version and [changelog](https://github.com/conventional-changelog/conventional-changelog)
2. Merge this pull request
3. Create a new version tag (eg. `git tag v0.1.30`) and push it to Github (`git push --tags`)
4. Compile V and test in Github Action
5. Publish a new release via Github Action (eg. [softprops/action-gh-release](https://github.com/softprops/action-gh-release))
6. Generate new documentation for vlib and deploy to server

There should be a release plan. Maybe release every two weeks or a month. Let developers use the latest results and new documents as soon as possible.

I think @medvednikov should consider this opinion. I would be happy to help.

Thanks to V developers

ref: #6685 #6099

**Comment by medvednikov** [comment]
Yes you are right, and all this will be handled and automated this week, long overdue.

Right now the best way to build the latest V is `git clone && make`, luckily that only takes a couple of seconds.

**Comment by medvednikov** [comment]
The changelog will be updated right away, with every commit.

**Comment by leahlundqvist** [comment]
I have a semi-working GitHub workflow that compiles new binaries when you push a tag. I'll see if I have time to finish it this week.

**Comment by axetroy** [comment]
close since #7005
