### ISSUE TITLE
Allow overloading of ^ and % operators

### ISSUE THREAD

**Issue by Undumendil** [vlang/v#686]

**Comment by elimisteve** [comment]
@Undumendil Examples/use cases would help make this more compelling :-D

**Comment by Undumendil** [comment]
Here they are:
``` 
fn (a bigi) ^ (b bigi) { ... } // power
fn (a bigi) % (b bigi) { ... } // modulo
fn (a bin_data) ^ (b bin_data) { ... } // xor 
fn (a some_data) % (b some_data) { ... } // take a, reset everything defined in b (not literally), return
```

**Comment by ntrel** [comment]
Operator overloading should not be used to change the meaning of the operators. I agree that all numeric operators should be overloadable for all kinds of structs representing numerical data.

**Comment by Serkonda** [comment]
Operator overloading is usually used to work with custom types but I can't see use cases where you would need overloaded ^ and %.

**Comment by ntrel** [comment]
@Serkonda For a BigInteger type, that doesn't have a fixed maximum value. The use case is the same as for any fixed size integer.

**Comment by Delta456** [comment]
There's `%` overloading now

**Comment by VinWare** [comment]
The `^` operator is already used for XOR, so I don't think it would be overloaded for power. Should this issue be closed now?

**Comment by Delta456** [comment]
`^` won't available to overload so closing this.

**Comment by ntrel** [comment]
> The ^ operator is already used for XOR, so I don't think it would be overloaded for power

It shouldn't be overloaded for power, but it is useful for BigInteger bitwise XOR, just like with built-in integers. @Delta456 what was the reasoning for disallowing bitwise operator overloading?

**Comment by Delta456** [comment]
It has been said many times. Only `+, -, *, /, %` would be allowed as they are most used ones. Even @medvednikov also agrees with it.
