### ISSUE TITLE
Parse error when calling generic function with module-prefixed type

### ISSUE THREAD

**Issue by ntrel** [vlang/v#6867]
**V version:** recent git
**OS:** Windows 10

**What did you do?**
```v
import flag

fn name<T>() string {
	return T.name
}

s := name<flag.Flag>()
println(s)
```

**What did you expect to see?**
Successful compilation.
 
**What did you see instead?**
```
genmodfn.v:7:22: error: expr(): bad token `)`
    5 | }
    6 |
    7 | s := name<flag.Flag>()
      |                      ^
    8 | println(s)
```

**Comments**
This is tricky to parse as we only have a few tokens to look ahead (`name` could be a variable followed by a less than operator). Maybe it could be done by checking if `flag` is a known module name and assuming the next tokens resolve to a type.

**Comment by ntrel** [comment]
> if flag is a known module name and assuming the next tokens resolve to a type

Actually that assumption would be wrong because it could be `var < mod.func()`. It seems we need a lot more token lookahead to parse this correctly.

**Comment by ntrel** [comment]
> I think the parser can tell if var is in scope.

That wouldn't work if `var` is a `const` or `__global` that hasn't been defined yet. Unless we require those to be forward declared?

**Comment by Delta456** [comment]
This now compiles with the latest V.
