### ISSUE TITLE
Original Go code

### ISSUE THREAD

**Issue by Happy-Ferret** [vlang/v#687]
Curious.

I read the original implementation was written in Go. Any chance of open-sourcing that version, for research purposes?

**Comment by medvednikov** [comment]
Ok, I might find and release at a bit later. The language is very different.

**Comment by Happy-Ferret** [comment]
That would be great.

Right now I'm dabbling with https://github.com/Lebonesco/go-compiler.
Some weird choices in that one. Would love to see how your initial implementation compares.

**Comment by SirWindfield** [comment]
I would love to see the original code as well! I wanted to create a simple language and would love to see how you actually started on writing the whole thing!

Keep up the great work!
