### ISSUE TITLE
main.v: new V compiler doesn't work on Windows due to mv/getwd

### ISSUE THREAD

**Issue by MrOnlineCoder** [vlang/v#688]
**V version: 0.1.4** 
**OS: Windows 7** 
**C compiler version: v.c compiled under mingw32-gcc 6.3.0 (MinGW.org GCC-6.3.0-1)** 

**What did you do?**
Built v.exe from v.c.
Tried to compile v/compiler

**What did you expect to see?**
Working V environment
 
**What did you see instead?**
1. [main.v:797 line that moves initial v binary into v/compiler](https://github.com/vlang/v/blob/master/compiler/main.v#L797) doesn't work on Windows, because binary exectuables have .exe extension on Windows. Probably an additional `if` is needed to check the platform.
2. Because os.getwd() is not implemented, [this if](https://github.com/vlang/v/blob/master/compiler/main.v#L793) body never executes. Therefore, finishing V compilation on Windows with MinGW is not possible. 

Regards.

**Comment by changrui** [comment]
Now, we can compile new edit V  with V v0.1.2, such as "**v -o v .**".

**Comment by Ian321** [comment]
I managed to build it using clang on windows. Just had to:

- [patch](https://github.com/vlang/v/files/3334967/v.patch.txt) v.c a bit
- vcpkg install dirent
- use a [getline.c](https://stackoverflow.com/a/47229318/5852818) implementation

```powershell
clang.exe v.c getline.c -I %VCPKG_ROOT%\installed\%VCPKG_DEFAULT_TRIPLET%\include
```

Doesn't work 100% tho'

**Comment by medvednikov** [comment]
Fixed.
