### ISSUE TITLE
vfmt: should allow empty lines

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#6885]
**V version:** always the latest
**OS:** Windows 10 WSL2 Ubuntu 20.04

**What did you do?**
```v
fn main() {
	mut x := 0
	if x == 0 {
		println(true)
	}

	println(x)
}
```
```
v fmt file.v
```

**What did you expect to see?**
no difference, v fmt should keep empty lines
 
**What did you see instead?**
```
fn main() {
        mut x := 0
        if x == 0 {
                println(true)
        }
        println(x)
}
```

## Explanation
As example, in my company we have a rule keep an empty line after each `for`, `if`, `while` block etc.
Some dudes do this for better code readability. So we should provide that option for the developers. Beeing too strict may result in rejection.

**Comment by JalonSolov** [comment]
Allow one empty line.  Compress multiple empty lines into one.

**Comment by ntrel** [comment]
Looks like #3917

**Comment by medvednikov** [comment]
Indeed, a duplicate.
