### ISSUE TITLE
Smart cast doesn't work for if option type

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#6900]
**What did you do?**
```
pub fn (s &Scope) find_var(name string) ?&Var {
	if obj := s.find(name) {
		match union obj {
			Var { return obj }
			else {}
		}
	}
	return none
}
```

**What did you expect to see?**
😄 
 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/30751516/99874410-159dc400-2be8-11eb-8477-20497ff918f5.png)

The problem here is, that obj is a Option type and the local variable is the unwrapped.

Either try to use the local variable or save `obj` in a temp var and assign `obj` with the correct one.

**Comment by danieldaeschle** [comment]
https://github.com/vlang/v/issues/6905

**Comment by ntrel** [comment]
I think it's best to keep this open until it's fixed. (You can put `Fixes #6900` in the pull request description or commit to auto close this).

**Comment by danieldaeschle** [comment]
but it's a duplicate, isn't it?

**Comment by danieldaeschle** [comment]
https://github.com/vlang/v/pull/6903 this fixed it, sry.
