### ISSUE TITLE
c error: calling filter() on a string

### ISSUE THREAD

**Issue by bstromquist** [vlang/v#6902]
OS: windows, Microsoft Windows 7 Professional v7601 64-bit
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz
CC version: N/A

vroot: C:\v
vexe: C:\v\v.exe
vexe mtime: 2020-11-15 19:42:21
is vroot writable: true
V full version: V 0.1.29 6ad5ecf.20bec81

Git version: git version 2.25.0.windows.1
Git vroot status: latest-commit-347-g155aa6da
.git/config present: true
thirdparty/tcc: N/A

**What did you do?**
```v
fn main() {
	str := 'abc'
	str.filter(it == `a`)
}
```

**What did you expect to see?**
running code or a proper error.
 
**What did you see instead?**
```
==================
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27039 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl -w /we4013 /volatile:ms /Fo"C:\Users\brian\AppData\Local\Temp\v\tmp.10519926342954220763.tmp.c.obj" /MDd "C:\Users\brian\AppData\Local\Temp\v\tmp.10519926342954220763.tmp.c" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt" -I "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared" kernel32.lib user32.lib advapi32.lib dbghelp.lib /link /NOLOGO /OUT:"C:\v\tmp.exe" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\X64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\X64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\X64" /DEBUG:FULL

tmp.10519926342954220763.tmp.c
C:\Users\brian\AppData\Local\Temp\v\tmp.10519926342954220763.tmp.c(8187): error C2065: 'it': undeclared identifier
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by Delta456** [comment]
Can you update to the latest commit and try again?

**Comment by Delta456** [comment]
Also you will have to use `string.filter` like this:

```v
fn test_string_filter() {
	foo := 'V is awesome!!!!'.filter(fn (b byte) bool {
		return b != `!`
	})
	assert foo == 'V is awesome'
	assert 'Alexander'.filter(filter) == 'Alexnder'
}

fn filter(b byte) bool {
	return b != `a`
}
```

**Comment by bstromquist** [comment]
Thanks for the fast response Swastik. I was trying out v for the first time today. I don't know what happened but I get errors when I run 'v up'. See the output attached. I have run it successfully before but not today (even before your commit).


-- Brian

________________________________

**Comment by medvednikov** [comment]
That's very strange @bstromquist 

`v up` should work. Must be a Windows issue.

Try re-cloning the repo and running `make.bat`

**Comment by Delta456** [comment]
After some testing, if any struct, type inference or sum type has a method named either `map` or `filter` and uses `it` as a var without declaring it then it will give the same error as the above.

**Comment by bstromquist** [comment]
Re-cloning and running make.bat solved my 'v up' issue. 

`C:\v>v up
Updating V...
V self compiling ...
Current V version:
V 0.1.29 311b5e8, commited at 2020-11-22 13:45:12 +0100`

But I still get a c error when running my str.filter code:

tmp.1896312498738725393.tmp.c
C:\Users\brian\AppData\Local\Temp\v\tmp.1896312498738725393.tmp.c(8186): error C2065: 'it': undeclared identifier
...
