### ISSUE TITLE
implement io.Writer to strings.Builder 

### ISSUE THREAD

**Issue by zakuro9715** [vlang/v#6915]
Golang's strings.Builder implements io.Writer.

strings.Builder has `write(string)` but io.Writer has `write([]byte)`. It is confusing

So we should implement same as golang.

**Comment by zakuro9715** [comment]
But it is breaking change

**Comment by nedpals** [comment]
Closed. Implemented in https://github.com/vlang/v/commit/c113abe1a4c4f8ba758727caddd33d0c4c06b706
