### ISSUE TITLE
Copy with update operator

### ISSUE THREAD

**Issue by nkev** [vlang/v#692]
I love this language. It is what Go should have been at the start!

Re. the `|` operator, as in:

```GO
user1 := User{'Bob', 20} 
user2 := { user1 | name: 'Peter' } 
```
Do you think using `with` instead of `|` is more semantic?

```GO
user1 := User{'Bob', 20} 
user2 := { user1 with name: 'Peter' } 
```

**Comment by nzlov** [comment]
Why not is `&`

**Comment by nkev** [comment]
Yes, `&` is also more readable than `|` but I think `user1 with name: 'Peter'` is extremely semantic, when you read it out loud :)

**Comment by elimisteve** [comment]
We are all used to `|` sometimes meaning `or`, so makes sense to me. Maybe

```golang
user1 := User{'Bob', 20} 
user2 := user1 | { name: 'Peter' }
```

would make even more sense, but what is there now seems good to me.

**Comment by medvednikov** [comment]
Thanks for the kind words @nkev 

The `|` syntax was recommended by someone, and I liked it. I think it's used in Elm and maybe a couple of other languages.

I like your `with` idea. I'll think about it :)

**Comment by ntrel** [comment]
> user1 | { name: 'Peter' }

This is better syntax because it's clearer. Consider `{some_var | field: init}` - this looks like `some_var` is being bit-ORed with `field: init`. When the `|` is outside the `{` brace, the programmer sees quicker that it can't be a bit-OR operation.

(Also I proposed this before independently, so it seems an intuitive change).

**Comment by elimisteve** [comment]
@ntrel :+1: Also, it seems to me that the compiler could internally transform

```
user2 := user1 | { name: 'Peter' }
```

into

```
user2 := user1 | User{ name: 'Peter' }
```

then reuse operator overriding code to basically generate

```
fn (user1 User) | (user2 User) User {
    mut new_user := User{}
    for field in user1.fields {
        new_user.$field = user1.$field
    }
    for field in user2.fields {  // or perhaps 'for field, value in user2'?
        new_user.$field = user2.$field
    }
    return new_user
}
```

except without copying over `user2`'s unpopulated fields somehow.

**Comment by nkev** [comment]
I do like @elimisteve's example above of operator overloading, but this is different to what I had in mind. 

To me, `user2 := { user1 with name: 'Peter' } ` does not involve allocation. It does not mean `a COPY of user1 with 'Name' changed to 'Peter'`. The syntax `user2 := user1 | { name: 'Peter' }` is perfect for this (implication of bitwise OR).

 `user2 := { user1 with name: 'Peter' } ` simply means a `pointer to user1 with 'Name' set to 'Peter'`,  where the property `Name` is stored like an additional extension/overlay, as part of user2, something like, `[pointerToUser1, {Name: "Peter"}]`. The original value of `user1.Name` is retained, allowing comparison later. 

My reasoning is, we have an opportunity with V to do new things and when you work with complex structs, it's nicer and more efficient to not have to copy them if you don't need to. 

Perhaps, both syntaxes would be useful.

**Comment by nkev** [comment]
It might be extreme, but you could also use this idea like a "one-off-inheritance". Consider struct:

```Go
struct Person {
	age int 
mut:
       name string
} 
```

You could then do:
```GO
person1 := Person{ name: 'Peter', age: 18 }
user1 := person1 with {username: 'peter2001', password: 'abc' }
```

**Comment by lutherwenxu** [comment]
And this is now a valid syntax! Sample code:
```
struct Something {
    a int
    b int
}

fn main() {
    c := Something{ a: 10 }
    d := Something{ c | b: 5 }
    println(c, d)
}
```
