### ISSUE TITLE
v up does not work with prebuilt binary releases

### ISSUE THREAD

**Issue by despiegk** [vlang/v#6928]
![image](https://user-images.githubusercontent.com/6021844/100054904-44ec4500-2e23-11eb-8433-852316e9fd81.png)

after doing ```v up``` the v binary got removed,then have to reinstall

![image](https://user-images.githubusercontent.com/6021844/100054969-61887d00-2e23-11eb-8791-71898eb1a87a.png)

after re-install back in business

**Comment by Larpon** [comment]
@despiegk - does the same thing happen if you [symlink](https://github.com/vlang/v#symlinking) your `v` binary?
Also, when things go wrong - depending on how the homebrew tap is setup you may want to try to run `make` in the root v directory (don't know where homebrew put it)

**Comment by despiegk** [comment]
I can get it to work I guess, e.g. doing from source, but just wanted to inform that a novice user will get stuck by following the instructions for updating V, will check it later today

**Comment by Larpon** [comment]
How package maintainers choose to setup V is beyond our control - so until we have some sort official support - users will have to use the current recommended way which is to clone it from github and build it from source. This will of course be improved upon in the future.

Maybe it'd help all parties if you file a bug with the tap maintainer?

**Comment by medvednikov** [comment]
@despiegk brew has a very old (~3 months) version. In V world that's eternity :)

In any case, `v up` doesn't work right now with prebuilt binaries, that's a very important issue to fix, since most users will be using them, not building from source.

It should stay open until it's fixed.

**Comment by despiegk** [comment]
or decide not to support v up when prebuilt, and just tell the user that this is not supported like this
good for now I guess.

**Comment by whitetigle** [comment]
> I can get it to work I guess, e.g. doing from source, but just wanted to inform that a novice user will get stuck by following the instructions for updating V, will check it later today

Thanks. I wondered why I had the following problem on windows:

 ```
v up
Updating V...
V panic: exec failed (CreateProcess): The system cannot find the file specified.
 cmd: git init
8 : v_panic                    ?? : address = 0xe9491be6f8
7 : v__util__ensure_modules_for_all_tools_are_installed  ?? : address = 0xe9491be6f8
6 : wmain                      ?? : address = 0xe9491be6f8
5 : invoke_main                d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:91
4 : __scrt_common_main_seh     d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
3 : __scrt_common_main         d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331
2 : wmainCRTStartup            d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_wmain.cpp:17
1 : BaseThreadInitThunk        ?? : address = 0xe9491be6f8
0 : RtlUserThreadStart         ?? : address = 0xe9491be6f8
```

Also, I don't know if that's linked but, on windows
- it seems standard libs are missing (hence the panic on modules?)
- using [live] does not seem to do anything

Do you want me to open a new issue or post anywhere else?

**Comment by medvednikov** [comment]
@whitetigle this is an issue about `v up` with prebuilt releases.

Everything else should be in separate issues.

There's no way standard libs are missing. Use `git clone` and `make` for now.

**Comment by ChildishGiant** [comment]
> How package maintainers choose to setup V is beyond our control

This is about the prebuilts from github, not third party packages, no?

**Comment by Larpon** [comment]
> > How package maintainers choose to setup V is beyond our control
> 
> This is about the prebuilts from github, not third party packages, no?

@ChildishGiant OPs screenshot shows homebrew in operation.

**Comment by ArtemkaKun** [comment]
Hi @despiegk ,

can you confirm that a problem still exists on a fresh V (0.2.4)?
