### ISSUE TITLE
mut attribute of variable isn't passed to argument of function

### ISSUE THREAD

**Issue by gaoxinge** [vlang/v#693]
**What did you do?**

```
fn mulb(arr []int){
  for i:=0;i<arr.len;i++{
     arr[i]=arr[i]*2
  }
}

fn main(){
   nums:=[1,2,3]
   mulb(nums)
   println(nums) // [2, 4, 6]
}
```

that the mut attribute of nums isn't passed to the argument arr of function mulb should also be discussed.

**What did you expect to see?**

- compiler raises `nums is immutable` error 

**What did you see instead?**

- code run successfully, and print `[2 ,4, 6]`

**Comment by medvednikov** [comment]
Fixed, thanks.
