### ISSUE TITLE
json parser not reporting syntax errors

### ISSUE THREAD

**Issue by despiegk** [vlang/v#6932]
```vlang
module mymodule
import json

struct ContactItem {
	description string
	telnr string
}

struct User {
    name string
    age  int
    // contact1 struct ContactItem [skip]
    contact2 ContactItem

}

pub fn json_test() {
	data := '{ 
				"name": "Frodo", 
				"age": 25 
				"contact2": {
					"description": "descr",
					"telnr": "+32333"
				}
			}'
	user := json.decode(User, data) or {
		eprintln('Failed to decode json')
		eprintln(err)
		return
	}
	println(user)
}
```

```
v run test.v
Failed to decode json
"contact2": {
					"description": "descr",
					"telnr": "+32333"
				}
			}
```

- the [skip] didn't work, so commented
- when trying to decode this gives the error but not really clear why

it could well be ofcourse I just don't know how to do it

if this works do list of subobjects work as well?

**Comment by Larpon** [comment]
the current `json` module is going to be replaced by `x.json2` which is written in V.
You could try using that by doing `import x.json2 as json`
The new json module has some more details in it's [README](https://github.com/vlang/v/blob/master/vlib/x/json2/README.md) that might be of more help

**Comment by medvednikov** [comment]
@Larpon current `json` is fine, I've used it to parse literally millions of lines of complex json without problems.

This particular problem is due to a missing comma after `"age": 25`. Need to print the location of the error.

**Comment by nedpals** [comment]
> This particular problem is due to a missing comma after "age": 25. Need to print the location of the error.

With `x.json2`, the parser will give you an (atleast) helpful error message and position of the error included:

```
Failed to decode json
[json] unknown token 'contact2' when decoding object. (4:14)
```

**Comment by despiegk** [comment]
oeps that was really stupid, sorry for that

**Comment by medvednikov** [comment]
@despiegk typos happen, and it's easy to miss a comma in JSON. This should stay open until JSON errors are reported well.

I just realised that V actually printed everything after the position of the parsing error.

**Comment by Dialga** [comment]
This runs now, but produces no output.

**Comment by ArtemkaKun** [comment]
With the following code

```v
import json

struct ContactItem {
	description string
	telnr       string
}

struct User {
	name string
	age  int
	// contact1 struct ContactItem [skip]
	contact2 ContactItem
}

pub fn json_test() {
	data := '{ 
				"name": "Frodo", 
				"age": 25,
				"contact2": {
					"description": "descr",
					"telnr": "+32333"
				}
			}'
	user := json.decode(User, data) or {
		eprintln('Failed to decode json')
		eprintln(err)
		return
	}
	println(user)
}

fn main() {
	json_test()
}
```

I have the following output in the console

```bash
User {
   name: 'Frodo'
   age: 25
   contact2: ContactItem{
      description: 'descr'
      telnr: '+32333'
   }
}
```

@despiegk is this was an expected output?

**Comment by ArtemkaKun** [comment]
I will close the issue since the author didn't respond, and code produce expected output

**Comment by ArtemkaKun** [comment]
Ah, I'm so dumb, forgive me. I read the thread one more time and realised where the problem is

**Comment by ArtemkaKun** [comment]
WIth the last V (0.2.4; actual for 06.05.2022) error output is still unclear
```
Failed to decode json
"age": 25
"contact2":
```

**Comment by despiegk** [comment]
indeed is just a reporting issue if there is a format issue

**Comment by enghitalo** [comment]
```bash
Failed to decode json
x.json2.UnknownTokenError: [x.json2] unknown token '[99, 111, 110, 116, 97, 99, 116, 50]' when decoding object. (13:17)
```

**Comment by pierrec** [comment]
Would the following error be good enough? This is an easy fix.

> x.json2.InvalidTokenError: [x.json2] invalid token `str_`, expecting `comma` (13:17)

**Comment by enghitalo** [comment]
> Would the following error be good enough? This is an easy fix.
> 
> > x.json2.InvalidTokenError: [x.json2] invalid token `str_`, expecting `comma` (13:17)

Looks better
