### ISSUE TITLE
Web server in V

### ISSUE THREAD

**Issue by ansarizafar** [vlang/v#695]
We can use https://lwan.ws as a high-performance & scalable web server for V.

**Comment by musou1500** [comment]
For what it's worth, `vweb` is working in progress.
please refer "Powerful built-in web framework" section on https://vlang.io/

**Comment by nkev** [comment]
Does anyone know when `vweb` will be open sourced? @medvednikov?

**Comment by medvednikov** [comment]
Does anyone know when vweb will be open sourced? @medvednikov?

@nkev early July.

**Comment by Niecke** [comment]
Will there be any announcement when vweb is released?

**Comment by medvednikov** [comment]
https://github.com/vlang/v/tree/master/vlib/vweb
