### ISSUE TITLE
Pointer indexing should error outside unsafe, not just warn

### ISSUE THREAD

**Issue by k1attila12** [vlang/v#6960]
**V version:** 
**OS:**  win10

**What did you do?**
```v
mut a:=[1,2,3]

mut p:=a
```
or
```v
mut p:=&a
```
This modify oroginal array in both cases :
```v
p[1]=100
```

**What did you expect to see?**

Don't modify array "a" `if mut p:=a`. It modify even without mut before "a"  
 
**What did you see instead?**

**Comment by Delta456** [comment]
Can you be clear as what you expected it to be?

**Comment by k1attila12** [comment]
Hi !

a:=[1,2,3]

mut p:=a

println(p)
unsafe{p[1]=100}
println(p)
println(a)   --->>>>  this should be : [1,2,3]  because 'a' isn't mutable and 'p' isn't refence to 'a'

**Comment by medvednikov** [comment]
Well the name `unsafe` is pretty telling. There are no checks there. Here be dragons.

**Comment by Delta456** [comment]
Even without `unsafe` the above code has the same output.

**Comment by medvednikov** [comment]
That will be fixed.

**Comment by k1attila12** [comment]
Thank you.

**Comment by danieldaeschle** [comment]
i think
```
mut p := a // this should be a copy
```

**Comment by axetroy** [comment]
> i think
> 
> ```
> mut p := a // this should be a copy
> ```

you are right.

Shouldn't a variable be declared here to reallocate memory? After all, p is not a pointer to a

**Comment by ntrel** [comment]
I renamed the title to describe the issue. But I'm not sure that unsafe checks need to be more than a warning, because warnings are errors with `-prod` anyway. The advantage is that whilst working on a change users don't have to add `unsafe{}` until they get the code working and they're ready to commit.

Users can use `v -W` to turn warnings into errors without `-prod`.

**Comment by danieldaeschle** [comment]
@spytheman Could we fix this somehow?

**Comment by medvednikov** [comment]
Fixed.
