### ISSUE TITLE
what is the address of struct ?

### ISSUE THREAD

**Issue by k1attila12** [vlang/v#6962]
**V version:** 
**OS:** win10

**What did you do?**
```v
struct Mo {mut: x int}

fn main() {

mut w:=Mo{1}

println(&w) //this doesn't work
println(&(w.x)) //this work
}
```

**What did you expect to see?**
the address of w
 
**What did you see instead?**

**Comment by danieldaeschle** [comment]
the second example shows you the address of `x`. but it shouldn't. We won't print addresses. the first println is correct but a missing `&` in front.

**Comment by k1attila12** [comment]
Hi
I don't understand.
The second println OK, because it print the address of w.x
The first one doesn't print the adress of w.

**Comment by danieldaeschle** [comment]
it should never print the address imo

**Comment by k1attila12** [comment]
I know
I think it should print : &{1}    //in Go it is the result  

but in V : Mo{ x:1 }

Is it OK ?

**Comment by danieldaeschle** [comment]
yep, see https://github.com/vlang/v/issues/6743

**Comment by EPonyA** [comment]
Why should V not print addresses? That makes cave man debugging much harder.

**Comment by danieldaeschle** [comment]
@medvednikov should decide

**Comment by danieldaeschle** [comment]
https://play.golang.org/p/YkWAS1KZvk-

**Comment by ntrel** [comment]
> Why should V not print addresses? That makes cave man debugging much harder.

You can print `voidptr` addresses:
```v
println(voidptr(&w)) // 13fe8c
```

**Comment by k1attila12** [comment]
OK. Thank you Sir.

**Comment by danieldaeschle** [comment]
> > Why should V not print addresses? That makes cave man debugging much harder.
> 
> You can print `voidptr` addresses:
> 
> ```v
> println(voidptr(&w)) // 13fe8c
> ```

will this be the official way to print addresses?

**Comment by spaceface777** [comment]
There is a builtin `ptr_str` function, that (afaik) does the same thing but is more explicit:
```v
println(ptr_str(&w)) // 7ffee5210888
```

**Comment by shadowninja55** [comment]
this prints the correct information on latest v
