### ISSUE TITLE
libfirm - an alternative compilation backend

### ISSUE THREAD

**Issue by dumblob** [vlang/v#6964]
I recently discovered [libfirm](https://github.com/libfirm/libfirm ) ([homepage](https://pp.ipd.kit.edu/firm/Projects.html )) and thought it might provide an interesting alternative to "raw" x86 or to tcc backend as it shall be moderately fast (in terms of compilation time) and produce quite optimized binaries (almost as good as LLVM or GCC or sometimes even better - it depends as it uses a different internal representation than LLVM/GCC and thus the results might vary wildly).

I think it might be worth taking a look at as it also offers compilation for ARM (which could be a huge plus for V if libfirm proved almost as fast as TCC or raw x86 backends).

There is also a C "frontend" for libfirm acting as pure C99 compiler, so the first step might be just to try to compile V and all its libs with this libfirm frontend and do some measurements.

**Comment by danieldaeschle** [comment]
Quality over quantity.

**Comment by JalonSolov** [comment]
I saw 'darwin' mentioned, which implies Mac support, but the only thing I found which might be about Windows is a mention of 'mingw' as a target.  And it says it should compile with Cygwin.

If you need mingw or cygwin anyway, why do you need this?

**Comment by JalonSolov** [comment]
Ok, the mingw/cygwin thing is to compile libfirm in the first place.  And it might be a good replacement for TCC if it is as fast.

However, the "worst" problem with libfirm that I saw is:

"libFirm has very good IA32 and SPARC backends. libFirms ARM and AMD64 backends are still in very early phases and often fail or don’t produce good code yet."

So basically, no (reliable) 64-bit support. Bzzt!  No, thank you.

**Comment by medvednikov** [comment]
Yeah there's really little point in using that. We already have a stable C backend for targeting all platforms, and the native x64/arm64 backend has to be as fast, clean, and lean as possible. So relying on an experimental 3rd party backend is not an option.

We can of course use some of its techniques and decisions in our own backend.

**Comment by dumblob** [comment]
>>"libFirm has very good IA32 and SPARC backends. libFirms ARM and AMD64 backends are still in very early phases and often fail or don’t produce good code yet."
>
>So basically, no (reliable) 64-bit support. Bzzt! No, thank you.

Well, from what I know the web page is not up to date. Second, the AMD64 backend is pretty good and able to compile really complex stuff (maybe there is some Linux binary compiled with that). Regarding ARM I don't have much information, but I'd guess it's not that bad either.

>We can of course use some of its techniques and decisions in our own backend.

That'd be very valuable.

**Comment by coffeenotfound** [comment]
Also note that libFirm is LGPL licensed...
