### ISSUE TITLE
println and eprintln function doesn't show anything in the terminal when importing gg, using msvc

### ISSUE THREAD

**Issue by MangelMaxime** [vlang/v#6966]
**V version:** V 0.1.29 5e59718
**OS:** Windows 10

**What did you do?**

```v
module main

import gg

fn main() {
	println('Hello! Modify this message while the program is running.')
}
```

**What did you expect to see?**

 The message should be reported in the console.

**What did you see instead?**

Nothing was shown in the console. If I remove the `import gg` then everything works fine.

----

This is causing problems because we can't use `println` for debug and also when trying to use `draw_text` function from gg no warning/error is reported in the console.

https://github.com/vlang/v/blob/master/vlib/gg/text_rendering.v#L111-L114

**Comment by Delta456** [comment]
Should we make `draw_text` return an optional in this case?

**Comment by MangelMaxime** [comment]
I just discovered that with V 0.1.30 c5cd53c and when using `gcc` the function does show their result in the terminal.

```
> C:\llvm-mingw\bin\gcc.exe --version
clang version 11.0.0 (https://github.com/llvm/llvm-project.git 176249bd6732a8044d457092ed932768724a6f06)
Target: x86_64-w64-windows-gnu

>  v -cc C:\llvm-mingw\bin\gcc.exe -g run .\repo.v
.\repo.v:5:8: warning: module 'gg' is imported but never used
    3 | module main
    4 |
    5 | import gg
      |        ~~
    6 |
    7 | fn main() {
Hello! Modify this message while the program is running.
```

So, I think this is a problem caused when using `msvc`

**Comment by blem14** [comment]
It also causes problems with debuging anything else in your code, cause if you run your code with even obvious error, you won't get any runtime errors to the console (got me wondering a few times already).

As an example, this code run on V 0.2.1 2f7a663 produces only unused import warning
```v
import gg


fn main(){
	a := []int{len:0}
	println(a[1])
}
```
```
main.v:1:8: warning: module 'gg' is imported but never used
    1 | import gg
      |        ~~
    2 |
    3 |
```

If the import is removed, we get actual errors:
```
V panic: array.get: index out of range (i == 1, a.len == 0)
C:/Users/blem14/AppData/Local/Temp/v/main.1694084012453595985.tmp.c:5118: at v_panic: Backtrace
C:/Users/blem14/AppData/Local/Temp/v/main.1694084012453595985.tmp.c:4637: by array_get
C:/Users/blem14/AppData/Local/Temp/v/main.1694084012453595985.tmp.c:8482: by main__main
C:/Users/blem14/AppData/Local/Temp/v/main.1694084012453595985.tmp.c:8563: by wmain
0043a490 : by ???
0043a5f3 : by ???
7ffe7b877034 : by ???
```

**Comment by shadowninja55** [comment]
the [console] attribute can be used with latest v.
