### ISSUE TITLE
Invalid typeof output for pointers

### ISSUE THREAD

**Issue by k1attila12** [vlang/v#6970]
**V version:** 
**OS:**  Win10

I don't know it is bug, or not, but i think.

**What did you do?**
```
struct Point {
x int
y int
}
p := &Point{10, 10}
println(typeof(p))
```
**What did you expect to see?**
```
&Point
```
 
**What did you see instead?**
```
Point
```

**Comment by k1attila12** [comment]
struct Mo {mut: x int
                y int  }

fn main() {
  mut w:=Mo{1,2}
  mut z:=&Mo{1,2}
  println(typeof(w))
  println(typeof(z))
}

in this example typeof(w) => Mo  and typeof(z) =>Mo , too.

**Comment by kahsa** [comment]
You can use  ```  surrounding code like 
```
fn main(){
    println('Hello!')
}
```

**Comment by danieldaeschle** [comment]
Please use proper code formatting in your Issues. It would be very helpful. Use markdown ``` tags for that.

**Comment by shadowninja55** [comment]
works on latest v
