### ISSUE TITLE
Documentation bug in ORM example

### ISSUE THREAD

**Issue by kpeters58** [vlang/v#6974]
https://github.com/vlang/v/blob/master/doc/docs.md#orm

Doc states that struct and table names must be the same and then proceeds to ignore that rule ('customer' vs. 'customers'):

`import sqlite
struct Customer { // struct name has to be the same as the table name (for now)
    id int // a field named `id` of integer type must be the first field
    name string
    nr_orders int
    country string
}
db := sqlite.connect('customers.db')?`

**Comment by JalonSolov** [comment]
The name of the database does NOT have to match the struct, and that is what you are looking at here.  The database is named 'customers.db', but the table that is added is named 'customer' to match the struct.

You can see that the table is named customer by this statement:
```v
nr_customers := sql db { select count from Customer }
```
