### ISSUE TITLE
vfmt: Not very nice to UI modules

### ISSUE THREAD

**Issue by nyx-litenite** [vlang/v#6981]
Most recently tested in WSL Ubuntu

> OS: linux, Ubuntu 20.04.1 LTS (WSL)
> Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
> CC version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

> vroot: /home/lite/v
> vexe: /home/lite/v/v
> vexe mtime: 2020-11-27 17:05:15
> is vroot writable: true
> V full version: V 0.1.29 bbea7fb.1dfdc97

> Git version: git version 2.25.1
> Git vroot status: latest-commit-418-g1dfdc972
> .git/config present: true
> /var/tmp/tcc status: master 5e73982e
> thirdparty/tcc: N/A

**What did you do?**
` v fmt -w vyper.v `

**What did you expect to see?**
Code to merely be formatted
 
**What did you see instead?**
in several places, anything ending in `ui` is renamed to `ui`; i.e `termui` or `tui` becomes `ui`

# before vfmt
![bodypart_before_vfmt](https://user-images.githubusercontent.com/50533436/100472395-2b106380-30aa-11eb-9799-cbf43fe61f02.PNG)
![event_before_vfmt](https://user-images.githubusercontent.com/50533436/100472409-2f3c8100-30aa-11eb-8662-c9bf8cb7dd80.PNG)
![rat_before_vfmt](https://user-images.githubusercontent.com/50533436/100472417-33689e80-30aa-11eb-93e4-535a0d6366a6.PNG)

# after vfmt
![app_after_vfmt](https://user-images.githubusercontent.com/50533436/100472434-395e7f80-30aa-11eb-9bab-46bfc77e3c55.PNG)
![bodypart_after_vfmt](https://user-images.githubusercontent.com/50533436/100472439-3c597000-30aa-11eb-9673-dd32d8fe83cb.PNG)
![event_after_vfmt](https://user-images.githubusercontent.com/50533436/100472445-3f546080-30aa-11eb-8f99-c7b54468cad2.PNG)
![rat_after_vfmt](https://user-images.githubusercontent.com/50533436/100472460-47ac9b80-30aa-11eb-8e24-548bbb99a8a7.PNG)

Note: It mainly seems to occur when the *ui appears in a declaration, as not all instances of *ui are replaced. the import works as expected as do occurrences with *ui being used as a field `app.termui.set_color(red)`

**Comment by Larpon** [comment]
I have oberserved this behaviour as well. Thanks for reporting it!

**Comment by serkonda7** [comment]
This does not happen anymore in newer versions of V.

> Also please do not include screenshots but actual code blocks in future issues, this makes testing and fixing the issue a lot easier :heart:
