### ISSUE TITLE
Release C2V translator

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#6985]

**Comment by abrandoned** [comment]
any update on ETA here? 

https://twitter.com/v_language/status/1345074628176334849

**Comment by annymosse** [comment]
we (almost it's me) wish you release it soon as possible as you can even it's not stable at least the forks can help and contribute by it's acknowledgments and possibilities to make v more rich and more reachable to the C language communities which make it progress more quick to be stable enough to translate other libraries and projects such as Lua language and HAproxy and much much more, we're curious and so excited for his language to be a real production player like Rust and Zig (on the way).

**Comment by Corallus-Caninus** [comment]
pls can I has sauce

**Comment by Ev1lT3rm1nal** [comment]
Is there any update on this?

**Comment by medvednikov** [comment]
Yes, we're about to release it.

https://github.com/vlang/doom
