### ISSUE TITLE
Finish the language server and integrate it into vscode

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#6986]

**Comment by danieldaeschle** [comment]
What is viscose?

**Comment by danieldaeschle** [comment]
I would like to help there.

**Comment by medvednikov** [comment]
That's macOS being helpful and autocompleting things :)

vscode

**Comment by danieldaeschle** [comment]
https://github.com/vlang/v/pull/7043

**Comment by danieldaeschle** [comment]
I think this can be closed since this issue is too big and the project management moved to the vlang/vls repository
