### ISSUE TITLE
Finish tcc integration for dependency free compiler packages

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#6987]

**Comment by spytheman** [comment]
TODO:
   Ensure that it works on latest macos, so it can be enabled by default there too.

On older macos 10.12.5, it can be used for the most, although these tests fail with runtime errors:
 vlib/vweb/tests/vweb_test.v
 vlib/v/tests/struct_allow_both_field_defaults_and_skip_flag_test.v
 vlib/json/json_test.v
 vlib/v/tests/for_loops_2_test.v
 vlib/v/checker/tests/missing_c_lib_header_1.vv (that can be fixed easily by turning off the verbose message about defaulting to cc)
 vlib/v/checker/tests/missing_c_lib_header_with_explanation_2.vv - same
