### ISSUE TITLE
Cannot compile and run the program that contains array of struct

### ISSUE THREAD

**Issue by shouji-kazuo** [vlang/v#70]
When I implemented the program as below on playground, I got a bug.

```
type User struct {
    id string
    name string
}

fn main() {
    users := [
        User{id: '01', name: 'john'},
        User{id: '02', name: 'ami'},
    ]
    for user in users {
        println(user)
    }
}
```

Output:
`You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.`

This is just a short note to inform you.

----
More info:

I removed `for` statement, I got same output.
```
type User struct {
    id string
    name string
}

fn main() {
    users := [
        User{id: '01', name: 'john'},
        User{id: '02', name: 'ami'},
    ]
//    for user in users {
//        println(user)
//    }
}
```

-> `You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.`

**Comment by ntrel** [comment]
It seems an array of structs can't be initialized, these also fail:
```rust
users := [User{}] //can't compile
```
```rust
u := User{id: '01', name: 'john'}
users := [u] //can't compile
```

**Comment by medvednikov** [comment]
There are 2 bugs here.

1) `[]` intialization syntax doesn't work when combined with struct initialization syntax.
2) I broke certain kinds of array type registrations yesterday.

`users := [a,b,c]` compiled yesterday, but not today.

I'll fix this asap.

**Comment by ntrel** [comment]
@medvednikov:
> users := [a,b,c] compiled yesterday, but not today

Do you have a test suite for V? It would be good to have small V files to make sure nothing gets broken when updating the compiler. Maybe I could help out turning code from issues into V test files.

**Comment by medvednikov** [comment]
I do have lots of tests, just haven't been running them before deploying the playground.

Might be a good idea :)

**Comment by medvednikov** [comment]
Fixed.
