### ISSUE TITLE
function `time.sleep_ms` is private

### ISSUE THREAD

**Issue by retsyo** [vlang/v#700]
when I compile code, for example, examples\game_of_life\life.v, I get 
`function `time.sleep_ms` is private`
then compiler stops

why?

**Comment by retsyo** [comment]
this can be fixed easily by add `pub ` before all the functions

**Comment by ofunc** [comment]
It has been fixed. Please update to the latest code.

**Comment by retsyo** [comment]
what are your developers doing? https://github.com/vlang/v/commit/978ec58fe300929555786fdf58cae1969ea317ba has restored the file to the wrong one

**Comment by medvednikov** [comment]
This was fixed.
