### ISSUE TITLE
Make the vweb http server multithreaded + epoll/kqueue. Move it to net/http/server.v

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#7000]

**Comment by danieldaeschle** [comment]
`http/server`? not just `web`? :)

**Comment by medvednikov** [comment]
Not sure what you are asking.

The server is in the vweb.v right now, it has to be moved to http/server.v, `http` module.

**Comment by JalonSolov** [comment]
There's  already a `net/http` module.  He was asking if you were talking about creating a new `http` module at the same level as `net`, or if the server should go under `net/http/server`.

**Comment by medvednikov** [comment]
Again,  it has to be moved to http/server.v, http module.

I think I made it very clear.

http module doesn't have the server.

**Comment by JalonSolov** [comment]
So it will be `net/http/server.v` since `net/http` is the existing `http` module.

**Comment by medvednikov** [comment]
Correct.

**Comment by spytheman** [comment]
Moving it into net.http will burden all http clients with a web server implementation too.
I think it would be better in `net.http.server`

**Comment by danieldaeschle** [comment]
@spytheman you said the same thing we already did. Did you misspelled something?

**Comment by JalonSolov** [comment]
No... The previous discussions was to put it in `net/http/server.v`.  @spytheman is suggesting putting it in `net/http/server/server.v` - extra level of directory, so that you do NOT get that code if you just want `net.http` module.  You would have to import `net.http.server` separately.

**Comment by danieldaeschle** [comment]
Hmm `net/web` would also be an option? or `net/http/web`.

**Comment by medvednikov** [comment]
V's stdlib imitates Go's stdlib, which is now a standard. In Go, it's all in one module `net.http`. I don't see how having both client and server code for the protocol in one module can burden anything.

https://golang.org/src/net/http/

**Comment by JalonSolov** [comment]
The only effect is having unused code in the final executable.  If you're just writing a client, you don't need (and will never call) the server code.

Perhaps this will be optimized out, perhaps not.  Depends on the backend.

**Comment by medvednikov** [comment]
Unused functions will not be added to the final executable. @joe-conigliaro did some work on that and will wrap it up at some point soon.

**Comment by JalonSolov** [comment]
Very nice.  Will it be done before backend is called, so it applies to all?

**Comment by medvednikov** [comment]
Yes.

**Comment by medvednikov** [comment]
veb is now based on pico.v, this can be closed
