### ISSUE TITLE
Problems with string.right()

### ISSUE THREAD

**Issue by HugoFlorentino** [vlang/v#7007]
**V version:** V 0.1.30 23c9563.a6f1667
**OS:** Microsoft Windows 10 Pro for Workstations v18362 64 bits

**What did you do?**
fn main() {
  print('hello'.right(2))
}

**What did you expect to see?**
'llo'
 
**What did you see instead?**
V panic: array.get: index out of range (i == 79, a.len == 79)
print_backtrace_skipping_top_frames is not implemented

**Comment by HugoFlorentino** [comment]
Also:

fn main() {
  h := 'hello'
  print(h.right(2))
}

right.v:3:11: error: method `string.right` is private
    1 | fn main() {
    2 |   h := 'hello'
    3 |   println(h.right(2))
      |           ~~~~~~~~
    4 | }

**Comment by nedpals** [comment]
@HugoFlorentino You might wanna use string slices instead.
```
fn main() {
   print('hello'[2..]) // llo
}
```

**Comment by danieldaeschle** [comment]
Can this be closed then?
