### ISSUE TITLE
builder error - C error: too many arguments to function

### ISSUE THREAD

**Issue by Ekopalypse** [vlang/v#7017]
**V version:** 
**OS:** 
OS: windows, Microsoft Windows 7 Professional v7601 64-bit
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
CC version: N/A

vroot: D:\ProgramData\Compiler\v
vexe: D:\ProgramData\Compiler\v\v.exe
vexe mtime: 2020-11-29 13:49:37
is vroot writable: true
V full version: V 0.1.30 e0d6490.9772306

Git version: git version 2.19.1.windows.1
Git vroot status: latest-commit-447-g9772306a (1 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: master 17d18c13

**What did you do?**

```
struct FuncItem {
	x int
}

mut func_items := [1]FuncItem{}
func_items[0] = FuncItem{1}
println(func_items)
```

**What did you expect to see?**
string representation of struct array
 
**What did you see instead?**
build error too many arguments to function

**Comment by Delta456** [comment]
This works with the latest V.

```
[FuncItem{
    x: 1
}]
```
