### ISSUE TITLE
str generation is too complex

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#7018]
**Currently** our string generation is like this:
![str_gen](https://user-images.githubusercontent.com/30751516/100544013-56828200-3253-11eb-93a4-551a3579b53e.png)

**My suggestion** is to simplify and unify it like this:
![new_str_gen](https://user-images.githubusercontent.com/30751516/100544029-65693480-3253-11eb-840b-1d03bd737ead.png)

`gen_str`: returns simple strings like or existing string methods
`auto_str_gen`: generates str methods if they doesn't exist

**Comment by medvednikov** [comment]
Looks good.
