### ISSUE TITLE
c error: Mutable receiver reassignment with spread operator

### ISSUE THREAD

**Issue by nedpals** [vlang/v#7033]
**OS:** linux, Ubuntu 20.04 LTS
**Processor:** 8 cpus, 64bit, little endian, Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
**CC version:** cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**vexe mtime:** 2020-11-30 06:51:51
**is vroot writable:** true
**V full version:** V 0.1.30 aae5812

**Git version:** git version 2.25.1
**.git/config present:** true
**thirdparty/tcc status:** thirdparty-linux-amd64 7543de81

**What did you do?**
```
module main

struct Person {
	name string
}

fn (mut p Person) change(name string) {
	p = { p | name: name }
}

fn main() {
	mut p := Person{'bob'}
        p.change('tom')
}
```

**What did you expect to see?**
Compiler error (??)
 
**What did you see instead?**
C compiler error:
```
recompilation with tcc failed; retrying with cc ...
==================
/tmp/v/test.9566610808835751915.tmp.c: In function ‘main__Person_change’:
/tmp/v/test.9566610808835751915.tmp.c:8066:3: error: field name not in record or union initializer
 8066 |   .name = name,
      |   ^
/tmp/v/test.9566610808835751915.tmp.c:8066:3: note: (near initialization for ‘(anonymous)’)
/tmp/v/test.9566610808835751915.tmp.c:8066:11: error: incompatible types when initializing type ‘main__Person *’ {aka ‘struct main__Person *’} using type ‘string’ {aka ‘struct string’}
 8066 |   .name = name,
      |           ^~~~
/tmp/v/test.9566610808835751915.tmp.c:8063:56: warning: parameter ‘p’ set but not used [-Wunused-but-set-parameter]
 8063 | VV_LOCAL_SYMBOL void main__Person_change(main__Person* p, string name) {
      |                                          ~~~~~~~~~~~~~~^
...
```

**Comment by ArtemkaKun** [comment]
Hi @nedpals,

on the fresh V 0.2.4 I have the following error
```
./main.v:9:3: error: invalid operator `|` to `&Person` and `string`
 7 | fn (mut p Person) change(name string) {
 8 |     p = {
 9 |         p | name: name
   |         ~~~~~~~~
10 |     }
11 | }
```
Is this what you expected to see?

**Comment by nedpals** [comment]
> Hi @nedpals,
> 
> on the fresh V 0.2.4 I have the following error
> ```
> ./main.v:9:3: error: invalid operator `|` to `&Person` and `string`
>  7 | fn (mut p Person) change(name string) {
>  8 |     p = {
>  9 |         p | name: name
>    |         ~~~~~~~~
> 10 |     }
> 11 | }
> ```
> Is this what you expected to see?

Not really. I know that the struct pipe spread operator (aka |) has been replaced by a ellipsis spread operator. 

The problem described here is the reassignment of a mutable receiver variable with an old value mixed with a new one hence the use or the spread op.

**Comment by ArtemkaKun** [comment]
Sorry, but I don't understand any word 😅 Probably somebody smart need to look at this issue
