### ISSUE TITLE
builder error: gcc: error: D:\vlang\thirdparty\sqlite\sqlite3.c: No such file or directory

### ISSUE THREAD

**Issue by sanrentai** [vlang/v#7034]
**V version:** 0.1.30
**OS:**  windows 10 

**What did you do?**
I follow the tutorials

https://github.com/vlang/v/blob/master/tutorials/code/blog/blog.v

v run .

**What did you expect to see?**

 
**What did you see instead?**
'''
.\blog.v:19:2: warning: unused variable: `articles`
   17 |
   18 | pub fn (mut app App) index() vweb.Result {
   19 |     articles := app.find_all_articles()
      |     ~~~~~~~~
   20 |     return $vweb.html()
   21 | }
D:\vlang\thirdparty\sqlite\sqlite3.o not found, building it in C:\Users\sanre\.vmodules\cache\8b\8b6496cfb81927431e25e20e5ef43878.o ...
failed thirdparty object build cmd:
gcc   -I "D:\vlang\thirdparty\sqlite" -L "D:\vlang\thirdparty\sqlite" -o "C:\Users\sanre\.vmodules\cache\8b\8b6496cfb81927431e25e20e5ef43878.o" -c "D:\vlang\thirdparty\sqlite\sqlite3.c"
builder error: gcc: error: D:\vlang\thirdparty\sqlite\sqlite3.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
'''

**Comment by serkonda7** [comment]
You need to have sqlite installed on your system.

**Comment by nedpals** [comment]
Closed. Please see #3619 .

**Comment by sanrentai** [comment]
I download the Source Code of sqlite. 
I put them into thirdparty\sqlite . 
The blog run is running success.
Thanks for you help.
