### ISSUE TITLE
executable code in module

### ISSUE THREAD

**Issue by retsyo** [vlang/v#704]
in python code, we can add
```python
if __name__ == '__main__':
    do_something()
```
in a python file, for example, `my_module.py`

when `my_module.py` is imported as module by other code, `do_something()` will not run; but if we execute `my_module.py` directly, `do_something()` will run. This is a good idea to supply some demo with module. Will V have something like it?

**Comment by decadedelta** [comment]
Considering modules could even "run" without a `main()` function, there is no reason to have "initializing code" because there is no global state to initialize.

Remember that V is a compiled language.

**Comment by retsyo** [comment]
nim has similaiar
```
when isMainModule:
    do_something()
```

**Comment by retsyo** [comment]
as I have stated, this is not only for "executing testing/demo code", but also for "ignoring testing/demo code"

**Comment by decadedelta** [comment]
Oh, I understand now.

Now you could have a main function in your module which would never be called unless it's being executed (at least not on purpose), but I'm not sure how it'd play when it's imported.

**Comment by medvednikov** [comment]
You need `fn main() {`, it works like Python's `if __name__ == '__main__':`

`fn main()` can be skipped in one file programs only.
