### ISSUE TITLE
smartcast on for-loop

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#7040]
Smartcast should work on for like on if or match:

```v
for mut x is MyType {
    // x is of type MyType
}
```

it needs to be declared with `mut`, otherwise it's an endless loop. Add a check for this case.

@medvednikov Is this okay to implement?

**Comment by elimisteve** [comment]
That for-loop should act like a `while (true) { ... }` in C, you're saying? Considering that creating a for-loop, making a variable mutable, and checking the underlying type of a variable are 3 different things, I personally think it's best that those can't all happen on the same line of code, for the sake of simplicity. (I'm still not sure I understand what that first line is trying to do.)

**Comment by danieldaeschle** [comment]
it's like:
```
while x is of type MyType {
  // smartcast it
}
```

the is check should already work. This issue is only for the smartcast funcitonality.

**Comment by medvednikov** [comment]
I also don't understand why this is necessary.

**Comment by danieldaeschle** [comment]
it's just an extension like if and match has it. Since the code already exists it's not much work to support `for` as well.

**Comment by danieldaeschle** [comment]
There is also one case in v where it can be used.

**Comment by medvednikov** [comment]
Can you provide an example where this can be useful?

**Comment by danieldaeschle** [comment]
https://github.com/vlang/v/blob/e68a2c95bf00dd874c8897d024b7a6a7e76f6254/vlib/v/ast/ast.v#L124

**Comment by medvednikov** [comment]
Ok, thanks. Makes sense.
