### ISSUE TITLE
js: implement basic builtin types

### ISSUE THREAD

**Issue by leahlundqvist** [vlang/v#7056]
To make any meaningful further progress on the JS backend, the builtin types need to be implemented. This also means converting all strings to custom string objects created by V etc.

**Comment by spaceface777** [comment]
I'd like to help with this as well.

**Comment by leahlundqvist** [comment]
@spaceface777 make a list with which ones you could implement and we'll split it up like that. We'll also need to figure out how to represent pointers in JS, got any ideas?

**Comment by medvednikov** [comment]
Done.
