### ISSUE TITLE
Replace Parser.expr_mod with a cleaner solution

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#7066]
`expr_mod` is an ugly workaround for generics https://github.com/vlang/v/blob/master/vlib/v/parser/parser.v#L43
It would be good to remove it and replace it with a cleaner solution.

**Comment by joe-conigliaro** [comment]
@danieldaeschle expr_mod is not for generics, its just for module prefix of types etc, it can be replaced by using a selector expr everywhere I have a working example of this

**Comment by danieldaeschle** [comment]
ok :)
yeah, i didn't know the context. It was a hack by Alex, it should be replaced with a better solution.
