### ISSUE TITLE
Remove tos_lit

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#7075]
Replace `tos_lit` with `_SLIT`: https://github.com/vlang/v/commit/d3deaa1f591c97380040daffc476ddca63835283#commitcomment-44700586

**Comment by spytheman** [comment]
why this, instead of the opposite?
_SLIT is less well behaved - it is a C macro, and evaluates its argument twice.

**Comment by danieldaeschle** [comment]
isn't SLIT faster?

**Comment by spytheman** [comment]
It is a macro that expands everywhere in place.
The speed argument is moot, because it does call strlen(s) inside, so it will either dwarf the 1 saved function call, or will be optimized out, depending on the C compiler optimization setting. Unless you benchmark it, you would not know.
Also I think that using a normal function will be better for maintenance.

**Comment by danieldaeschle** [comment]
Alex should say which one to remove, it doesn't bother me. Just clean it up.

**Comment by JalonSolov** [comment]
The C macro is less portable to other backends (js, x64, wasm...).

**Comment by medvednikov** [comment]
It doesn't really matter, we just need to use one of those, for consistency.

SLIT doesn't set `is_lit` to 1 by the way, so it's broken.

Since it works with tos_lit already, let's just use that everywhere and remove SLIT.

**Comment by medvednikov** [comment]
By the way, calling strlen on string literals is silly, and I'm pretty sure C compilers should optimize `strlen("aa")` to `2`.

But we can do that in V since we know the length of the literal during compilation: `_SLIT("aa", 2)`

**Comment by JalonSolov** [comment]
You can optimize the strlen away completely for string literals.

**Comment by danieldaeschle** [comment]
What now? keeping _SLIT or tos_lit? :D
Or removing both and inventing something new? 🤷‍♂️

**Comment by medvednikov** [comment]
I would say the best way is to do `_SLIT2("foo", 3)`, then once everything is migrated, rename `_SLIT2` to `_SLIT`.

Using a macro in cgen instead of a function will have no impact on JS and other backends.

**Comment by danieldaeschle** [comment]
i think yuyi migrated tos_lit to SLIT: https://github.com/vlang/v/blob/84fc9cec4ba2a704751453c8ab50d958d22addc6/vlib/builtin/string.v#L133

Should we remove that deprecated function?
