### ISSUE TITLE
array push is by value, by reference expected

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#7082]
**V version:** latest and greatest
**OS:** sometimes windows, sometimes linux, mostly WSL2 with Ubuntu 20.04

**What did you do?**
```v
struct Person {
mut:
    name string
}

fn main() {
    last_person := Person{}
    mut persons := [Person{}]
    persons << last_person
    persons[1].name = 'test'
    println(persons[1].name) //> 'test'
    println(last_person.name) //> ''
}
```

**What did you expect to see?**
That last_person changed as well. `<<` is for me like adding exactly THAT element to an array, not a copy of it.
 
**What did you see instead?**
it's copied when adding.

**Comment by spytheman** [comment]
That is expected behaviour.
