### ISSUE TITLE
Do you mind if I ported V to other platforms and add some experimental features to it?

### ISSUE THREAD

**Issue by 3442853561** [vlang/v#709]
# Background
Some people think that V should be used for Unity development, and I think so. https://github.com/vlang/v/issues/638  
We also want to use V for development in other specific domains.  

# Action
Rewrite a V implementation, and add some experimental features to it.  
In order to avoid confusion, the implementation of rewriting may not be called V.

# Why
We think V is awesome.  
If the new grammar is not good enough, this will not pollute the current V.    
We need some specialized syntax to be more compatible with C#.

# Promise
We will open source this implementation.  
If we have more income, I will donate some money to V on our behalf.

**Comment by medvednikov** [comment]
Of course :) You can do whatever you want.

**Comment by medvednikov** [comment]
Just of curiosity, what features do you miss? Perhaps they can be included in the language.

**Comment by 3442853561** [comment]
@medvednikov I am really sorry, I am too busy these two days. So replying to your message is late.

First, in order to develop Unity(https://github.com/vlang/v/issues/638), classes and inheritance are required. I don't think inheritance is still necessary for modern programming languages. However, in order to use the V language for Unity development, this is necessary. It is not necessary to add stale features to the V language just to develop Unity. So I think I should write a separate version for Unity development. (To avoid confusion, we can call it "V with class" or "V++" just like C and C++ for the time being)

Second, in order to use it for Unity development, it has to be ported to the Mono virtual machine. This makes memory management forced to follow the Mono virtual machine instead of the V language. This made us have to make some compromises in memory management. However, we can guarantee that it is still very fast except for the memory management part, just like V.

Finally, the most fascinating part of the V language is its ease of learning. Compared to other features, we hope that the V language will save Unity developers from the power of C#.

**Comment by medvednikov** [comment]
Sounds interesting, thanks @3442853561 

Since I started working on the C to V translator, I had to add many missing features to V. Some of them are hidden behind a flag.

Perhaps we can do something similar, we'll see.
