### ISSUE TITLE
builder error: '/home/daniel/Projects/v/vlib' is a directory

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#7096]
**What did you do?**
```
cmd -o vlib cmd/v
```

**What did you expect to see?**
it works
 
**What did you see instead?**
```
builder error: '/home/daniel/Projects/v/vlib' is a directory
```

output to vlib is not a practical example. but it should work either and i know it worked once. I have that problem in vls where i have a directory called vls and the output should be vls as well.

**Comment by spaceface777** [comment]
You can't have a file with the same name as a directory: https://unix.stackexchange.com/q/22447z

**Comment by JalonSolov** [comment]
`-o directory` used to work to make V put output files in that directory.

**Comment by danieldaeschle** [comment]
ah okay :O
