### ISSUE TITLE
x.websocket: Move x.websocket to net.websocket

### ISSUE THREAD

**Issue by helto4real** [vlang/v#7098]
Since x.net was moved to net it is time to make the new x.websocket implementations a part of net.websocket.

Following suggested items:
- [ ] Move to correct module
- [ ] Fix examples, tests, autobahn tests to use correct module
- [ ]  Refactor naming and clean up code

**Comment by JalonSolov** [comment]
Any ideas when you might get to this one?  :-)

**Comment by helto4real** [comment]
I have vacation in two weeks so then I will have some time doing it :)

**Comment by helto4real** [comment]
Done as of #10648
