### ISSUE TITLE
Declaration with type needed?

### ISSUE THREAD

**Issue by ntrel** [vlang/v#71]
I've found some problems with declaring variables:
1. How to declare an empty array
2. How to declare an empty optional value
3. How to declare an optional value with a value

These are all for mutable variables. There are workarounds for 2 and 3 - make functions that return optionals (see #15) and call them as variable initializers. For 1, I tried:
```rust
fn int_array() []int {return []}
```
At the moment that doesn't work (maybe `[]` isn't understood). With `[]` and generics, functions can work to solve 1-3, but it might be better if we just allowed variable declarations to optionally specify a type:
```rust
mut opt1 : int? = none
mut opt2 : int? // same, no initializer needed for optionals
mut opt3 : int? = 5
mut arr1 : []int = []
mut arr2 : []int // same, no initializer needed for arrays
```
There may be other times where it's better to just write the type in the declaration too.

**Comment by medvednikov** [comment]
Support for optionals is very limited right now.

I implemented them for error handling, so they can only be returned from functions at the moment. Full support will be implemented after the language is open-sourced.

An empty array can be declared with

`a := []int`

**Comment by medvednikov** [comment]
> it might be better if we just allowed variable declarations to optionally specify a type

This will never happen. There is and always will be only one way to declare variables.

**Comment by medvednikov** [comment]
I'm closing this, since declaration is not going to change.

I've created a separate issue for optionals:

https://github.com/vlang/v/issues/75

**Comment by ntrel** [comment]
@medvednikov Ok, then we solve the problem with cast expressions instead.
> An empty array can be declared with a := []int

Can we please change this to `[]int()`, because that is an expression instead of a type, so it can be passed as a function argument.
That would then be consistent with optional declarations, which can be `T?()` and `T?(val)`.

**Comment by ntrel** [comment]
I just found that `[]int` can be passed to a function. So perhaps empty optional initialization could be `opt := T?`.
