### ISSUE TITLE
expected `io.Reader`, not `os.File`

### ISSUE THREAD

**Issue by cromega** [vlang/v#7100]
I really don't understand why this doesn't work. As far as I can tell `os.File` implements the `io.Reader` interface.

**V version:** 
V 0.1.30 ca7692c

**OS:** 
linux, Linux Mint 20

**What did you do?**
```
  mut f := os.open('file.txt') or { panic(err) }
  defer { f.close() }

  mut reader := io.new_buffered_reader(reader: f)
```

**What did you expect to see?**
That it works.
 
**What did you see instead?**
```
nums.v:8:40: error: cannot assign to field `reader`: expected `io.Reader`, not `os.File`
    6 |   defer { f.close() }
    7 | 
    8 |   mut reader := io.new_buffered_reader(reader: f)
      |                                        ~~~~~~~~~
```

**Comment by zakuro9715** [comment]
Use `io.make_reader`
```
io.new_buffered_reader(reader: io.make_reader(f))
```

https://github.com/vlang/v/blob/master/vlib/io/reader.v#L12-L16

But i don't understand this too. I think it's better to work without make_reader

**Comment by danieldaeschle** [comment]
works now
