### ISSUE TITLE
v panic: the end of file `internal_memory` has been reached 50 times already

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#7102]
![image](https://user-images.githubusercontent.com/30751516/100927522-4aadee80-34e5-11eb-8e84-955aa3940a8d.png)

**Comment by spytheman** [comment]
That check/panic is deliberate - it is a protection against infinite loops in the parser.
In this case, the loop is in parser's fn_args in vlib/v/parser/fn.v

**Comment by danieldaeschle** [comment]
why closed? is this fixed?
