### ISSUE TITLE
is net.html GPL3 ?

### ISSUE THREAD

**Issue by zakuro9715** [vlang/v#7106]
https://github.com/vlang/v/blob/c5a7c51dfd4821d51d8ef4fa0b34ee4f1dd959f7/vlib/net/html/README.md#license

README.md of net.html says license is GPL3. But no license file exists

**Comment by medvednikov** [comment]
My bad, missed that one. All vlib files should be MIT.

@Jictyvoo can you relicense it under MIT? Thanks.

**Comment by Jictyvoo** [comment]
> My bad, missed that one. All vlib files should be MIT.
> 
> @Jictyvoo can you relicense it under MIT? Thanks.

Yes I can, I will do it now
