### ISSUE TITLE
Release 0.1.30 changed directory format and is not executable

### ISSUE THREAD

**Issue by leighmcculloch** [vlang/v#7107]
**V version:** 0.1.30
**OS:** Linux (Debian)

**What did you do?**
I downloaded the .zip file for 0.1.30 and proceeded to unzip the files and run the `v` executable.

**What did you expect to see?**
I expected to see `v` execute and run.

```
$ ls -lah ./v/v
-rwxr-xr-x 1 leighmcculloch leighmcculloch 810K Aug  6 11:13 ./v/v
```

**What did you see instead?**
It looks like starting with 0.1.30 the directory structure of what is inside the .zip file has changed.

In versions prior inside the .zip file was a `v` directory, and inside the `v` directory was a `v` executable that already had executable permissions.

In version 0.1.30 the directory has changed from `v` to `linux`, and the `v` executable no longer has executable permissions.

```
$ ls -lah ./linux/v
-rw-r--r-- 1 leighmcculloch leighmcculloch 3.3M Nov 29 13:16 ./linux/v
```

**Comment by spytheman** [comment]
This is fixed in 2f6757b . There will be a new release soon.

**Comment by spytheman** [comment]
Can you try again @leighmcculloch ?
The most recent https://github.com/vlang/v/releases/latest/download/v_linux.zip should now have an executable `v` file, when unpacked, and does not have the top level linux/ folder anymore.

**Comment by spytheman** [comment]
```
0[16:37:04]delian@nemesis: /v/pv $ rm -rf v_linux/
0[16:37:20]delian@nemesis: /v/pv $ aunpack v_linux.zip > /dev/null 
v_linux.zip: extracted to `v_linux' (multiple files in root)
0[16:37:31]delian@nemesis: /v/pv $ ls -lart v_linux/
total 1168
drwxr-xr-x  4 delian delian    4096 дек  3 16:19 cmd
-rw-r--r--  1 delian delian   16554 дек  3 16:19 CHANGELOG.md
-rw-r--r--  1 delian delian     183 дек  3 16:19 BSDmakefile
-rw-r--r--  1 delian delian     850 дек  3 16:19 0.3_roadmap.txt
-rw-r--r--  1 delian delian     228 дек  3 16:19 Dockerfile.cross
-rw-r--r--  1 delian delian     546 дек  3 16:19 Dockerfile.alpine
-rw-r--r--  1 delian delian     434 дек  3 16:19 Dockerfile
drwxr-xr-x  2 delian delian    4096 дек  3 16:19 doc
-rw-r--r--  1 delian delian    6855 дек  3 16:19 CONTRIBUTING.md
-rw-r--r--  1 delian delian      44 дек  3 16:19 CODE_OF_CONDUCT.md
drwxr-xr-x 15 delian delian    4096 дек  3 16:19 thirdparty
-rw-r--r--  1 delian delian    1336 дек  3 16:19 TESTS.md
-rw-r--r--  1 delian delian    7776 дек  3 16:19 README.md
-rw-r--r--  1 delian delian    2312 дек  3 16:19 Makefile
-rw-r--r--  1 delian delian   10396 дек  3 16:19 make.bat
-rw-r--r--  1 delian delian    1083 дек  3 16:19 LICENSE
drwxr-xr-x 22 delian delian    4096 дек  3 16:19 examples
-rw-r--r--  1 delian delian     159 дек  3 16:19 v.mod
drwxr-xr-x 49 delian delian    4096 дек  3 16:19 vlib
-rwxr-xr-x  1 delian delian 1072512 дек  3 16:19 v
drwxr-xr-x  4 delian delian    4096 дек  3 16:19 tutorials
drwx------  8 delian delian    4096 дек  3 16:37 .
drwxrwxr-x 18 delian delian    4096 дек  3 16:37 ..
0[16:37:35]delian@nemesis: /v/pv $ v_linux/v version
V 0.1.30 110c7e6
0[16:37:43]delian@nemesis: /v/pv $ 
```

**Comment by leighmcculloch** [comment]
Thanks for the quick response to the issue!

It looks like the `v` is now executable.

However, the directory structure is still inconsistent with the previous releases. The previous releases had a single `v` directory within the ZIP. The latest `weekly.2020.49.2` release has a `v_linux` directory. If the directory structure needs to change that's fine, but it makes it harder for those of us who have automatic or CI install scripts if the folder structure within the ZIP keeps changing because we have to have different install steps for different versions.

**Comment by medvednikov** [comment]
That's a good point. @spytheman the directory should stay `v`.

Go packages work the same way:

https://golang.org/dl/go1.15.5.linux-amd64.tar.gz

This unpacks into `go`

**Comment by leighmcculloch** [comment]
It appears this is fixed in `weekly.2020.49.5`. Thank you.
