### ISSUE TITLE
vfmt: Should it format empty structure in single line?

### ISSUE THREAD

**Issue by MangelMaxime** [vlang/v#7117]
**V version:** Windows 10
**OS:** V 0.1.30 9b6a155

**What did you do?**

Run `v fmt` against:

```v
struct C.LPCWSTR {}
```

**What did you expect to see?**

```v
struct C.LPCWSTR {}
```
 
**What did you see instead?**

```v
struct C.LPCWSTR {
}
```

-----

In the documentation, there are places where it is initialized on a singe line and sometines with line break. 

![image](https://user-images.githubusercontent.com/4760796/101080835-90cc8600-35a9-11eb-9a9b-366e73055c02.png)

![image](https://user-images.githubusercontent.com/4760796/101081019-cffad700-35a9-11eb-9dae-dd03d219f1a2.png)

Should it be single line or with the line break? 

Depending on the decision, I can send a PR to the documentation or send a fix `v fmt`. I have a working fix locally but I needs to add tests etc.

**Comment by JalonSolov** [comment]
More of a style decision.  Shorter if it stays on one line, but more "standard" if it includes the line break... so structs have the same placement for `}` whether  they are empty or not.

🤷‍♂️

**Comment by MangelMaxime** [comment]
Indeed, it's just that when declaring `C.StructInterop` it takes a "lot" of places. 

I just don't know if we always declare them empty or not.

Still learning V.

**Comment by medvednikov** [comment]
I  agree, it should take one line `struct C.Foo {}`

gofmt is a bit more flexible, it respects the choice of the developer.

If the developer used a single line, it's going to stay a single line.

**Comment by MangelMaxime** [comment]
>If the developer used a single line, it's going to stay a single line. We can do that as well.

Do we have the information on how the developer formatted their code in the current implementation? 

I am asking because it would also help fix another issues that interest me https://github.com/vlang/v/issues/3917

**Comment by medvednikov** [comment]
You are right, these are related.

No, we don't have that yet. It's planned.

**Comment by serkonda7** [comment]
Btw, I started working on an update for `check-md.v` to also check formatting.
