### ISSUE TITLE
tcc.exe do not have executable permissions

### ISSUE THREAD

**Issue by zhaoyilun** [vlang/v#7124]
**V version:**  v0.1.30
**OS:** Manjaro 20

**What did you do?**
`v self  `
`v install ui`

**What did you expect to see?**
compiling...
 
**What did you see instead?**
V self compiling ...
recompilation with tcc failed; retrying with cc ...

** When I type `v install ui`, I see:
cannot compile `/home/zyl/Downloads/v_linux/v/cmd/tools/vpm.v`: 
/home/zyl/Downloads/v_linux/v/thirdparty/cJSON/cJSON.o not found, building it in /home/zyl/.vmodules/cache/d6/d651f9750b1969f61c6a83b7fd5d5076.o ...
failed thirdparty object build cmd:
/home/zyl/Downloads/v_linux/v/thirdparty/tcc/tcc.exe   -fPIC -I "/home/zyl/Downloads/v_linux/v/thirdparty/cJSON" -o "/home/zyl/.vmodules/cache/d6/d651f9750b1969f61c6a83b7fd5d5076.o" -c "/home/zyl/Downloads/v_linux/v/thirdparty/cJSON/cJSON.c" 
builder error: sh: /home/zyl/Downloads/v_linux/v/thirdparty/tcc/tcc.exe: 权限不够

“权限不够”means permission denied.

Then I cd to dir, and type `chmod +x tcc.exe`,if fixed.

**Comment by spytheman** [comment]
The latest prebuilt v archive (generated from d60f148) has tcc.exe executable too.
