### ISSUE TITLE
Syntax enhancement for array decomposition to varargs (spread operator)

### ISSUE THREAD

**Issue by lammel** [vlang/v#7134]
V supports variadic parameters for functions, but there is currently no way to decompose an array into varargs to allow to pass it to those functions matching the type.

The suggested syntax is to use the postfix dot dot dot syntax `array...`.
This syntax complements the already available `...type` syntax used for varargs in function definitions in V.

An example of using this syntax is here:

```v
fn sum(i ...int) int {
    mut s := 0
    for a in i { s += a }
    return s
}

a := [2,3,4]
println(sum(a...))  // <-- Using postfix ... here
```

The same syntax is also available in Go.
This is a functional example of the above V code in Go:

```go
func Sum(nums ...int) int {
  s := 0
  for _, a := range nums {
   s += a
  }
  return s
}

func main() {
  a := []int{2, 3, 4}
  fmt.Println(Sum(a...)) // 17
}
```

**Comment by medvednikov** [comment]
Sounds good.

**Comment by dedesite** [comment]
Good idea, in js it is called the "spread operator" and it's at the left of the variable name :
https://exploringjs.com/es6/ch_core-features.html#sec_from-apply-to-spread
Seems better to put it at the right to be consistent with Go syntax, as V is closer to Go than to JS.
