### ISSUE TITLE
Make` v -usecache` work with modules with C deps (eg. gg)

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#7155]

**Comment by medvednikov** [comment]
Right now `v -usecache tetris.v` fails.

**Comment by joe-conigliaro** [comment]
A temporary fix was added here: https://github.com/vlang/v/commit/78a6795319c202670ebe74da4c5305e4cd7937b2
however it only works on linux, osx complains and about duplicate symbols.

I have done some research & testing on this, in cases where we do not control the C lib (eg we cannot define functions as static without editing the headers) we are limited in the ways we can solve the duplicate symbol issue.

One solution is to build a module and its submodules as a single .o file.
