### ISSUE TITLE
Release notes for new versions

### ISSUE THREAD

**Issue by International** [vlang/v#717]
Hi Alexander,
would it be possible for you to post release notes when you release a new version? This way, we would know what has changed since the previous one.
Thanks!

**Comment by medvednikov** [comment]
Hi

Sure. I'll be doing that. I have to push minor releases so that people downloading binary builds have working compilers.

Every bigger release (released every 2/3 days) will have a changelog.

**Comment by aguspiza** [comment]
For the time being, you can go to https://github.com/vlang/v/releases and click "xx commits"

**Comment by International** [comment]
Nice. Thanks!

**Comment by medvednikov** [comment]
@International https://github.com/vlang/v/blob/master/Changelog.md
