### ISSUE TITLE
Suggest that interpolation should adopt unique expression syntax `${xxx}`

### ISSUE THREAD

**Issue by yuyi98** [vlang/v#7173]
Suggest that interpolation should adopt unique expression syntax `${xxx}`.

- To avoid confusion.
- Reduce compile analysis complexity.
- In line with Vlang's unique expression style.

**Comment by medvednikov** [comment]
Yeah I agree, it would be nice and reasonable.

I just find `a = $a` very readable and clean.

**Comment by medvednikov** [comment]
Yeah I agree, it would be nice and reasonable.

I just find `a = $a` very readable and clean.
