### ISSUE TITLE
update vlib documentation automatically

### ISSUE THREAD

**Issue by axetroy** [vlang/v#7183]
The vlib documentation has fallen behind a lot

Currently, I want to view the latest vlib documentation

The only way is to view the vlib source code, or manually generate the documentation

```bash
$ cd $(which v)
$ v doc -m -f html vlib/
```

I searched the vlang org, but I didn’t found where to store the vlib documentation.

This document should also be updated automatically.

The static files are stored in Github, and the domain name is bound by CNAME

Automatically update documents via Github Action.

**Comment by medvednikov** [comment]
Good idea
