### ISSUE TITLE
Hanoi.v example bug

### ISSUE THREAD

**Issue by kpeters58** [vlang/v#7198]
I believe the backslash should be removed...

D:\v\examples>\v\v hanoi.v
hanoi.v:11:31: warning: unknown escape sequence \46
```
    9 |
   10 | fn move(n int, a string, b string) int {
   11 |     println('Disc $n from $a to $b\...')
      |                                  ^
   12 |     return 0
   13 | }
```

D:\v\examples>

**Comment by medvednikov** [comment]
Indeed, you can submit a quick PR with `to ${b}...`

**Comment by kpeters58** [comment]
Issue no longer present
