### ISSUE TITLE
Cast int to string returns error

### ISSUE THREAD

**Issue by bitsnaps** [vlang/v#72]
I was playing with playground compiler, I got the error `You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.` trying to cast a simple `int` to a `string`:
```
fn main() {
	i := 1
	println(string(i))
}
```
trying to make `i` mutable didn't change anything.

**Comment by medvednikov** [comment]
Thanks for reporting this. V should give an error, since you can' cast an int to string like this.

Use `'$i'` or `i.str()` instead.

**Comment by medvednikov** [comment]
Fixed:

```
cannot convert `int` to `string` 
```
