### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by k1attila12** [vlang/v#7207]
How can i handle this type of exception ?
```v
fn main() {
  mut i:=2.0
  for {
    i=i*i
    println(i)
  }
}
```
or
```v
s:=""
for {
  s= s+"aaa'
}
```

**Comment by k1attila12** [comment]
in c 
setjmp longjmp

other higher level languages
try
except .....

**Comment by dumblob** [comment]
Support for floating point operations and the overall floating point ecosystem is **very immature** in *V* - see https://github.com/vlang/v/issues/5180#issuecomment-675732199 and https://github.com/vlang/vtl/issues/2 .

**Comment by k1attila12** [comment]
I think
It is not about floating point.
It is about how to handle for  without try except end
