### ISSUE TITLE
test_iso8601_parse_utc() error.

### ISSUE THREAD

**Issue by yuyi98** [vlang/v#7213]
```v
FAIL [108/291]   564.035 ms vlib\time\parse_test.v
C:\\Users\\yuyi9\\v\\vlib\\time\\parse_test.v:66: failed assert in function test_iso8601_parse_utc
Source  : `t.hour == tt[3]`
         left value: 23 <= `t.hour`
        right value: *unknown value* <= `tt[3]`
```
I'm in China, I think it's the time zone problem caused by calling `to_local_time()` in `parse_iso8601()`.

**Comment by spytheman** [comment]
Fixed in https://github.com/vlang/v/commit/ada02d44980a0c111343ae7c73bade8edf353c06

**Comment by spytheman** [comment]
You are right - I am in Easter Europe, and it failed for me too.
