### ISSUE TITLE
Runtime exception after compiling with -autofree

### ISSUE THREAD

**Issue by HugoFlorentino** [vlang/v#7228]
**V version:** 0.1.30 3b6b5b8.a38fe4f
**OS:** Microsoft Windows 10 Pro for Workstations v18362 64 bits

**What did you do?**
import os
fn main() {
  progarg := os.args[1..]
  println('Arguments: ' + progarg.len.str())
}

C:\prj\v -autofree progarg.v
C:\prj>progarg abc def

**What did you expect to see?**
C:\prj>progarg abc def
Arguments: 2
 
**What did you see instead?**
C:\prj>progarg abc def
Arguments: 2
Unhandled Exception 0xC0000374
C:/Users/Usuario/AppData/Local/Temp/v/progarg.10649071685082044206.tmp.c:6755: at print_backtrace_skipping_top_frames_tcc: Backtrace
C:/Users/Usuario/AppData/Local/Temp/v/progarg.10649071685082044206.tmp.c:6723: by print_backtrace_skipping_top_frames
C:/Users/Usuario/AppData/Local/Temp/v/progarg.10649071685082044206.tmp.c:6777: by unhandled_exception_handler
7ffd042185d6 : by ???

**Comment by HugoFlorentino** [comment]
V 0.1.30 1f95233 seems to have fixed this.

**Comment by nachoverdon** [comment]
This happened to me again.

It a simple program that looks for a new file on a folder every 5 seconds. After a few loops (between 2-10), it crashes. Also, the memory usage increases with each loop, so it also leaks memory still. This used to work without crashing before, even with the memory leaks still present.

`v -prod -autofree replay_watcher.v`

```
Unhandled Exception 0xC0000374
print_backtrace_skipping_top_frames is not implemented
```

```
λ v doctor

OS: windows, Microsoft Windows 10 Pro v19042 64-bit
Processor: 12 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: cc --version

getwd: C:\projects\ghprofile\nachoverdon\replay_watcher
vmodules: C:\Users\bazoo\.vmodules
vroot: C:\Vlang
vexe: C:\Vlang\v.exe
vexe mtime: 2021-07-08 14:02:34
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 fb9b2e8

Git version: git version 2.21.0.windows.1
Git vroot status: weekly.2021.27-19-gfb9b2e87
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 9fa4d4b6
```
