### ISSUE TITLE
NetBSD support

### ISSUE THREAD

**Issue by krytarowski** [vlang/v#723]
Please add.

**Comment by medvednikov** [comment]
It should be buildable from source.

**Comment by krytarowski** [comment]
Was the support added? If not it doesn't work as there are switches for lin/mac/win only.

**Comment by vitalyster** [comment]
try "Mac", it should work

**Comment by krytarowski** [comment]
How to try mac? Actually the current code fallbacks to mac for me and it breaks as it passes some `-fspacial-mac-only-flags` and breaks.

**Comment by medvednikov** [comment]
You are, that's a quick fix. I'll let you know once it's supported.

**Comment by medvednikov** [comment]
NetBSD has been supported since mid July.
