### ISSUE TITLE
module keyword breaks C function import

### ISSUE THREAD

**Issue by justicesuh** [vlang/v#724]
**V version:** 0.1.6
**OS:** Debian
**C compiler version:** gcc 6.3.0

I originally left this as a comment on #476 but after a little more digging figured it warranted it's own issue

**What did you do?**

I'm trying to create a socket module.  I get a compilation error with the following code

```
module socket

#include <sys/socket.h>

pub fn socket(domain int, _type int, proto int) {
        sockfd := C.socket(domain, _type, proto)
}
```

> check()
> next token = domain
> pass=2 fn socket__socket
> panic: socket.v:6
> expected . but got (

**What did you expect to see?**

If I comment out the `module socket` statement from the beginning the program compiles just fine

**Comment by AtjonTV** [comment]
I thinks it's time to close this issue now as with 0.1.7 the '`#` syntax for embedding C code has been removed.'?

**Comment by justicesuh** [comment]
The `#` embedded syntax refers to using inline C code.  An old example from `rand` would be

```
# srand((unsigned) time(&t));
```

I believe `#include` and `#define` are still supported
