### ISSUE TITLE
Filter returns incorrect result when compiling with -autofree

### ISSUE THREAD

**Issue by HugoFlorentino** [vlang/v#7260]
**V version:** V 0.1.30 aedd1d1.8823430
**OS:** Microsoft Windows 10 Pro for Workstations v18362 64 bits

**What did you do?**
fn main() {
  println('qwe'.split('').filter(it !in '012345678'))
}

**What did you expect to see?**
['q', 'w', 'e']
 
**What did you see instead?**
[]

**Comment by HugoFlorentino** [comment]
Negation isn't the problem:

fn main() {
  println('ab'.split('').filter(it in '012345678'))
}

should produce:
[]

But produces:
['a', 'b']

**Comment by HugoFlorentino** [comment]
Chaining is also not the problem:

const (
  a = ['a', 'b']
  b = '012345678'
)

fn main() {
  println(a.filter(it in b))
}

should produce:
[]

But produces:
['a', 'b']

**Comment by joe-conigliaro** [comment]
thanks @HugoFlorentino I see the issue its with optionals

**Comment by HugoFlorentino** [comment]
But it only happens when compiling with -autofree

**Comment by joe-conigliaro** [comment]
> But it only happens when compiling with -autofree

yes thats correct

**Comment by yuyi98** [comment]
It can work with -autofree now.
```vlang
fn main() {
	println('qwe'.split('').filter(it !in '012345678'))
}

PS D:\Test\v\tt1> v run .
['q', 'w', 'e']
PS D:\Test\v\tt1> v -autofree run .
['q', 'w', 'e']
```
