### ISSUE TITLE
Can define var with syntax `mut a = 1` or `mut a == 1`, not just `mut a := 1`

### ISSUE THREAD

**Issue by elimisteve** [vlang/v#729]
**V version:** 0.1.7
**OS:** Linux
**C compiler version:** gcc 6.3.0

**What did you do?**

```
>>> mut a = 1
>>> a *= 2
>>> a
>>> println(a)
2
>>> mut b == 2
>>> b
>>> println(b)
2
```

**What did you expect to see?**

Only variable creations of the form `mut a := 1` should work, not `mut a = 1` nor `mut a == 1`. But all 3 forms _do_ work.
 
**What did you see instead?**

Variable declarations worked that shouldn't have.

**Comment by elimisteve** [comment]
This is not just a REPL issue:

```
module main

fn main() {
        mut a := 1  // Correct
        // mut a = 1  // Should not work, but does
        // mut a == 1  // Should also not work, but does
        println(a)
}
```

**Comment by elimisteve** [comment]
And yes, the `mut` _is_ necessary for this bug to show up; `a = 1` and `a == 1` do not allow one to define and initialize a variable.

**Comment by medvednikov** [comment]
Fixed.
