### ISSUE TITLE
Allow array.map with explicit anonymous function types to return a different type

### ISSUE THREAD

**Issue by lilenvy** [vlang/v#7299]
Hello, when using `[].map` I can either use the magic word `it` or an anonymous function like: `[1].map(fn(a int) int { return a }}`

Example:
```v
fn main() {
	a := [1, 2, 3]
	println(a.map(it * 2))  // same type "it" OK
	println(a.map(fn (a int) int {  // same type anon fn OK
		return a * 2
	}))

	println(a.map(it.str())) // OK
	// error: type mismatch, should use `fn(a int) int {...}`
	println(a.map(fn (a int) string {
		return a.str()
	}))
}
```

There are discussions as to whether lambda functions should be used for `[].map` and `[].array`, leaving those discussions aside, could the compiler allow using different type of anon fn for them?

**Comment by medvednikov** [comment]
It's a bug, good find.

**Comment by lilenvy** [comment]
Cool, I have  a PR ready, I'll send it over in a second
