### ISSUE TITLE
2D arrays in structs

### ISSUE THREAD

**Issue by siuolf** [vlang/v#730]
**V version:** 0.1.3
**OS:** Linux
**C compiler version:** GCC 7.4.0

**What did you do?**
```
struct Matrix {
mut:
    elmnts [][]int
}

fn main() {
    mut mat := Matrix {
        elmnts: [[0; 10]; 10]
    }
    mat.elmnts[0][0] = 10
    println(mat.elmnts[0][0])
}
```

**What did you expect to see?**
No compiler error
 
**What did you see instead?**
```
PREV=]
NEXT=INT
pass=2 fn=`main`
panic: vArrTest.v:10
unexpected token: `=`
```

**Additional info**
I already tried with 2D arrays not in structs and 1D arrays in structs and both worked perfectly fine.

**Comment by medvednikov** [comment]
Yes, right now you have to use `[]array_int`

Will fix this asap.

**Comment by medvednikov** [comment]
Fixed.
