### ISSUE TITLE
v 0.1.7 can't run on my ubuntu 16.04

### ISSUE THREAD

**Issue by miepian** [vlang/v#731]
**V version:** 
0.1.7

**OS:**
Ubuntu 16.04.6 LTS \n \l
 
**C compiler version:** 
cc (Ubuntu 8.1.0-9ubuntu1~16.04.york1) 8.1.0

**What did you do?**
run v and println('aa')

**What did you expect to see?**
aa
 
**What did you see instead?**
V 0.1.7
Use Ctrl-D to exit
For now you have to use println() to print values, this will be fixed soon

>>> println('aa')

=========================
It looks like you are building V. It is being frequently updated every day.
If you didn't modify the compiler's code, most likely there was a change that
lead to this error.

Try to run `git pull && make clean && make`, that will most likely fix it.

If this doesn't help, re-install V from source or download a precompiled binary from
https://vlang.io.
=========================

panic: string.v:490
bad token `#` (embedding C code is no longer supported)

**Comment by thisisshub** [comment]
did you type `run v and println('aa')` as a whole command?
because that will fetch an error for now
if you want to print "`aa"` directly then just use simple println('aa') subtracting the `run v and`

**Comment by miepian** [comment]
@thisisshub I just exec v from shell,in the REPL,I input println('aa') and enter.

**Comment by thisisshub** [comment]
> @thisisshub I just exec v from shell,in the REPL,I input println('aa') and enter.

and that works?

**Comment by miepian** [comment]
@thisisshub No. the output is in my issue report

**Comment by thisisshub** [comment]
alright let's just re install everything with,
```
git clone https://github.com/vlang/v.git
cd v/compiler 
make
```

**Comment by miepian** [comment]
@thisisshub It's work! thx.
