### ISSUE TITLE
[0.1.7] build panic

### ISSUE THREAD

**Issue by nzlov** [vlang/v#732]
**V version:** 
`v0.1.7`
**OS:** 
`macos 10.14.3`
**C compiler version:** 
```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
**What did you do?**
```
$ git checkout v0.1.7
$ cd compiler
$ rm v
$ make
```
**What did you expect to see?**
```
build v
```
 
**What did you see instead?**
```
cc -std=gnu11 -w -o v v.c
./v -o v .
pass=2 fn=`ustring`
panic: string.v:637
.global is only allowed in translated code
make: *** [v] Error 1
```

**Comment by AtjonTV** [comment]
Try to delete v.c also before compile:

```bash
$ rm v v.c
$ make
```

**Comment by AtjonTV** [comment]
Just saw that the error message is the same on #716.

**Comment by shamofu** [comment]
As you can see from [CI status](https://dev.azure.com/alexander0785/vlang/_build/results?buildId=166), v0.1.7 will cause build error. Could you try `git pull` and rebuilding?

**Comment by nzlov** [comment]
Must remove `v.c`,`vc` and rebuild. It's work.
