### ISSUE TITLE
could you include the v.c in your source zip file

### ISSUE THREAD

**Issue by l1t1** [vlang/v#733]
I cannot visit https://raw.githubusercontent.com/vlang/vc/master/v.c

**Comment by nzlov** [comment]
Try clone [https://github.com/vlang/vc](https://github.com/vlang/vc)

**Comment by l1t1** [comment]
thanks
complie https://github.com/vlang/vc/blob/master/v.c 2 new errors
:v2.c:(.text+0x66ff): undefined reference to `setenv'
:v2.c:(.text+0x674a): undefined reference to `unsetenv'
:v2.c:(.text+0x6bed): undefined reference to `getline'  <---- already known

**Comment by l1t1** [comment]
i found their description at http://man7.org/linux/man-pages/man3/setenv.3.html but no source.

**Comment by medvednikov** [comment]
Hi

If you follow installation instructions in README.me, everything should work.
