### ISSUE TITLE
result should be true, with autofree result is false

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#7337]
**What did you do?**
```v
fn main() {
	mut a := true
	b := a && if true {
		a = false
		true
	} else {
		false
	}
	println(b)
}
```

**What did you expect to see?**
`true`
 
**What did you see instead?**
```
➜  v git:(master) ✗ v run main.v
true
➜  v git:(master) ✗ v -autofree run main.v
false
```

**Comment by danieldaeschle** [comment]
Related to: https://github.com/vlang/v/issues/4401

**Comment by danieldaeschle** [comment]
This might be a solution:
```c
#include <stdio.h>

#define bool int
#define false 0
#define true 1

int main(int argc, char argv[]) {
    bool a = true;
    bool _tmp_a = a;
    bool _tmp_c;
    if (true) {
        a = false;
        _tmp_c = true;
    } else {
        _tmp_c = false;
    }
    bool b = _tmp_a && _tmp_c;
    printf("%s\n", b ? "true" : "false");
    return 0;
}
```

**Comment by danieldaeschle** [comment]
@yuyi98 Do you want to solve this? We also can get rid of the ternary generation completely if this works.

**Comment by yuyi98** [comment]
@danieldaeschle  Thanks! I'll try.  But we cannot get rid of the ternary generation completely, because temporary variables generated before the if_expr statement can sometimes cause logic errors.

**Comment by danieldaeschle** [comment]
The ternary stuff is not able to handle all cases, so we need to get rid of it. I think there are solutions to the temporary variable stuff but it's very hard to implement.

**Comment by yuyi98** [comment]
@danieldaeschle  The solution you give will be logic error in the following cases.
```vlang
fn main() {
	mut a := true
	b := if true {
		a = false
		true
	} else {
		false
	} && a
	println(b)
}
```

**Comment by yuyi98** [comment]
But this is really an effective idea that needs to be perfected.

**Comment by yuyi98** [comment]
@danieldaeschle  Can we disable this usage? 
if_expr (is_expr) can only be used in a single statement.

**Comment by danieldaeschle** [comment]
To me, disabling this usage would be a bad solution because in other languages it works.

**Comment by yuyi98** [comment]
Ok, I see.

**Comment by yuyi98** [comment]
@danieldaeschle  Your solution can work for it.

```vlang
#include <stdio.h>

#define bool int
#define false 0
#define true 1

int main(int argc, char argv[]) {
    bool a = true;
    bool _tmp_c;
    if (true) {
        a = false;
        _tmp_c = true;
    } else {
        _tmp_c = false;
    }
    bool _tmp_a = a;
    bool b =  _tmp_c && _tmp_a;
    printf("%s\n", b ? "true" : "false");
    return 0;
}
```

**Comment by danieldaeschle** [comment]
Yes, but this needs a lot of forelooking
