### ISSUE TITLE
Crashes with plain exmaples

### ISSUE THREAD

**Issue by Glitchfix** [vlang/v#734]
**V version:** 
V 0.1.4

**OS:** 
Ubuntu 18.04

**C compiler version:** 
gcc version 7.4.0

**What did you do?**
println('hello')

**What did you expect to see?**
hello
 
**What did you see instead?**

=========================
It looks like you are building V. It is being frequently updated every day.
If you didn't modify the compiler's code, most likely there was a change that 
lead to this error.

Try to run `git pull && make clean && make`, that will most likely fix it.

If this doesn't help, re-install V from source or download a precompiled binary from
https://vlang.io.
=========================

panic: string.v:637
.global is only allowed in translated code

**Comment by Glitchfix** [comment]
When I do a `make test` it passes all the test case though it is confusing. 

And when trying to build the `hello_world.v` example

I get this error:

> check()
> next token = `(`
> pass=0 fn=``
> panic: hello_world.v:1
> expected `module` but got `println`

**Comment by thisisshub** [comment]
can you switch to version 0.1.7 and give it a try once again?
update with this `git pull && make clean && make`

**Comment by Glitchfix** [comment]
Still the same issue

**Comment by medvednikov** [comment]
Fixed in 0.1.8
