### ISSUE TITLE
invalid operands to binary

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#7354]
**What did you do?**
```v
type DocUri = string

fn main() {
	uri := DocUri('test')
	println(uri == 'test')
}
```

**What did you expect to see?**
`true`
 
**What did you see instead?**
```
/tmp/v/main.177491193706691818.tmp.c:8101:14: error: invalid operands to binary == (have ‘main__DocUri’ {aka ‘struct string’} and ‘string’ {aka ‘struct string’})
 8101 |  println(uri == _SLIT("test") ? _SLIT("true") : _SLIT("false"));
      |              ^~
```

**Comment by Delta456** [comment]
This should work because `DocUri` and `string` ain't the same anymore. This should be a V error.

**Comment by danieldaeschle** [comment]
Rly? In Kotlin this works: https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS40LjIwIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsImpzQ29kZSI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiLyoqXG4gKiBZb3UgY2FuIGVkaXQsIHJ1biwgYW5kIHNoYXJlIHRoaXMgY29kZS4gXG4gKiBwbGF5LmtvdGxpbmxhbmcub3JnIFxuICovXG5cbmRhdGEgY2xhc3MgVGVzdCAodmFsIHg6IEFueSlcblxudHlwZWFsaWFzIERvY1VyaSA9IFN0cmluZ1xuXG5mdW4gbWFpbigpIHtcbiAgICB2YXIgZCA9IFwidGVzdFwiIGFzIERvY1VyaVxuICAgIHByaW50bG4oZCA9PSBcInRlc3RcIilcbn0ifQ==

**Comment by danieldaeschle** [comment]
0 and table.Type (which is an alias for int) are also comparable.
