### ISSUE TITLE
range for high .. low support

### ISSUE THREAD

**Issue by kahsa** [vlang/v#7358]
high .. low
```v
for i in 5 .. 0 {
	print(i)
}
```
isn't it handy than
`for i := 5; i>=0; i--{}`?

```v
for i in arr.len .. 0 {
    println(arr[i])
}
```

**Comment by SleepyRoy** [comment]
This feature is indeed useful and should be implemented. However, making ascending and descending ranges syntax same IMO is not nice. A better choice for descending could be eg `10..0..-1` or `10..0..rev`.

**Comment by JalonSolov** [comment]
If you want different ranges, you should check out https://github.com/Delta456/range

This has been discussed before, and I believe the consensus was that it would not likely be implemented in V itself.  You start getting into all sorts of issues, not least of which is which end of the range should be inclusive?  And how do those decisions fit into the overall core V ideas?

The module linked duplicates Python's range support, which should give you what you want.

**Comment by kahsa** [comment]
That make sense.

mainly for array.
for just numbers, something like this can be enough
```v
fn range(start int, end int) []int {
	mut res := []int{}
	for i := start; i <= end; i++ {
		res << i
	}
	return res
}

for i in range(10,0) {}
```

So main target is HUGE array.
e.g. `rev` keyword like
```v
for a in arr rev{
    println(a)
}
```
I know number of keywords kept to be minimam though.

**Comment by medvednikov** [comment]
This won't be implemented for the same reason negative indexing doesn't work like in Python.

Too bug prone.

If you accidentally have a lower value on the right, the program does the opposite of what you want.
