### ISSUE TITLE
Consider to native support for WASI and Webassembly？

### ISSUE THREAD

**Issue by JermineHu** [vlang/v#737]
Reference to the following two items: 

https://github.com/fastly/lucet

https://github.com/wasmerio/wasmer

**Comment by andreabravetti** [comment]
It wuold be usefull to have full GUI support with wasm inside a browser

**Comment by syrusakbary** [comment]
I would love to see V supporting WebAssembly/WASI as a target, with first class support in @wasmerio.
Let us know if we can help in any way! :)

**Comment by medvednikov** [comment]
Yes, that would be great.

**Comment by tomByrer** [comment]
Any progress on WASM output please?

**Comment by sanath-usk** [comment]
I would love to see V lang support web assembly.

**Comment by richardanaya** [comment]
Hey all, I work on a library specifically for enabling WebAssembly languages to communicate with javascript. 

http://wasm.js.org/

It might be a way to help accelerate efforts in V to expose more of the host.
