### ISSUE TITLE
Undefined reference to __chkstk

### ISSUE THREAD

**Issue by nailuj29gaming** [vlang/v#7392]
**V version:** V 0.1.30 a26e1e6
**OS:** windows, Microsoft Windows 10 Home v19042 64-bit

**What did you do?**
Tried to build the 2048 example (and others).

**What did you expect to see?**
The program building properly
 
**What did you see instead?**
The console being spammed with ``<command line>:(.text+'hex'): undefined reference to `__chkstk'``

**Comment by JalonSolov** [comment]
`v doctor` output?

**Comment by nailuj29gaming** [comment]
I actually just fixed it myself. I needed `-cc msvc`. V was trying to use MinGW.

**Comment by JalonSolov** [comment]
Should be able to fix that by making sure msvc is in your path before mingw.  Then you don't need the `-cc msvc`.

**Comment by nailuj29gaming** [comment]
MinGW is last in my path, but `cl.exe` isn't on the windows path by default. Its location changes every time I update visual studio, so it's not worth the trouble of updting my PATH every time I update Visual Studio. Possibly making `-cc msvc` the default on Windows could be helpful? In my testing MSVC was the only compiler that worked for me.

**Comment by JalonSolov** [comment]
I don't have msvc installed (gcc works fine for me), so that would hurt me more than help.

The other thing you can do is set the environment variable `VFLAGS` to `-cc msvc`, so you don't have to type it every time.
