### ISSUE TITLE
suggestions for syntax & improvements

### ISSUE THREAD

**Issue by bitsnaps** [vlang/v#74]
I've seen recent languages and I confirm V is different in the way of making things simple concise and readable, I really like the "one way of doing things", just curious if some keywords can decrease learning curve and make things more readable:
1- `mut` keyword is not very common, w've seen `var` the most probably used one, or even `def` is a good candidat, I found `var` more significant to the variable meaning. However if you make the default behavior of mutable variable we wont need a keyword for mutable variables, and then we could refer to `val` (or `const`) for immutable ones.
2- `fn` some others use `fun` for functions which makes writing code fun, but I've found the return type for functions and nothing for `void` replacement was more readable and less verbose:
```
int add(x int, y int){ return x+y }
show(msg){ println(msg) }
```
3- `return` keyword is verbose and this is way most languages make it optional, and to keep "one way of doing things" I believe removing it would be more readable and concise code.
4- I'm not sure why variable name comes before type, I found this little weird since it's not very common syntax.
wait to see more features, functional programming, struct inheritance, closures support... keeping things concise and readable without inventing new keywords so developers can learn faster. Hope you best of luck.

**Comment by medvednikov** [comment]
Hi @bitsnaps 

Thanks for your input.

Actually most languages use `[name] [type]` syntax: Pascal, Go, Rust, Swift, etc. C and related languages are an exception.

You can read about the advantages of this approach here:

https://golang.org/doc/faq#declarations_backwards

Regarding everything else, these things are not going to change.

**Comment by bitsnaps** [comment]
The last thing I would talk about is about escaping chars, some languages use different style of strings, string declared with double quote "" is string interpolation, whereas simple quote used to espace special characters:
```
s := 'simple string containing $ sign'
mut s2 := "$s interpolation"
```
This way makes easy to use `$` in your string without need to escape it.

**Comment by medvednikov** [comment]
`$` is normally not used before letters. `$123` doesn't need escaping.

**Comment by medvednikov** [comment]
Most likely I'll add `"` for denoting raw string literals.

**Comment by rockcat** [comment]
I'd like to second:
_3- return keyword is verbose and this is way most languages make it optional, and to keep "one way of doing things" I believe removing it would be more readable and concise code._

I used to code a lot of C and the concept of everything evaluating to something is very powerful - and in line with many modern functional languages.

It would be great if everything in V evaluated to the last calculation - you could lose the return keyword and also add a nice functional feature

**Comment by ciubotaru** [comment]
<return keyword is verbose> Let's say I have a function with a series of conditions ("if ... else if ... else", or "switch case", or "for (...) if...", or whatever). Depending on the evaluation (true or false), the function either exits or continues to the next condition. How can exit such a function without "return" or "goto"?

**Comment by bitsnaps** [comment]
@ciubotaru usually the return statement is optional at the end of methods in many languages, so you still need to include `return` explicitly in some cases, check [this](https://stackoverflow.com/questions/12925713/groovys-optional-return-semantics) case of Groovy.

**Comment by ciubotaru** [comment]
OK, so it is not "optional", it is "optional under certain conditions".

I would like to have a strictly defined language where you either have to write a keyword or have to omit it. There might be more than one way to do things, but these should be clearly _different_ ways.
