### ISSUE TITLE
update C interoperability example in documentation with unsafe around code accessing pointers by index

### ISSUE THREAD

**Issue by saasira** [vlang/v#7400]
**V version:**  V 0.1.30 7e1e247
**OS:**   windows, Microsoft Windows 10 Home Single Language v19041 64-bit

**What did you do?**
compiled sqlite demo showcasing C interoperability

**What did you expect to see?**
smooth compilation and running of the given example for C interop with V 
 
**What did you see instead?**
compilation error

> v xdb.v
xdb.v:32:39: warning: pointer indexing is only allowed in `unsafe` blocks
   31 |     for i in 0 .. howmany {
   32 |         print('| ${cstring_to_vstring(cnames[i])}: ${cstring_to_vstring(cvalues[i]):20} ')
      |                                             ~~~
   33 |     }
   34 |     println('|')
xdb.v:32:74: warning: pointer indexing is only allowed in `unsafe` blocks
   30 | fn my_callback(arg voidptr, howmany int, cvalues &charptr, cnames &charptr) int {
   31 |     for i in 0 .. howmany {
   32 |         print('| ${cstring_to_vstring(cnames[i])}: ${cstring_to_vstring(cvalues[i]):20} ')
      |                                                                                ~~~
   33 |     }
   34 |     println('|')
Compilation with tcc failed. Retrying with gcc ...
==================
C:/MSYS64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\saasira\AppData\Local\'
collect2.exe: error: ld returned 1 exit status
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

Expected Fix : 
update documentation to surround lines having cnames[i] and cvalues[i] with unsafe

**Comment by spytheman** [comment]
Fixed in b61a936
