### ISSUE TITLE
generic array is to str is wrong

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#7403]
**What did you do?**
```

struct Gen<T> {
	foo T
}

struct Foo {

}

fn main() {
	g := Gen<[]Foo>{

	}
	println(g)
}
```

**What did you expect to see?**
```
Gen<[]Foo>{
    foo: []
}
```
 
**What did you see instead?**
```
Gen<array, Foo>{
    foo: []
}
```

**Comment by nedpals** [comment]
I believe this was intentional and will be fixed in the updated implementation of generics: https://github.com/vlang/v/pull/7324
