### ISSUE TITLE
modules.vlang.io search to be more useful

### ISSUE THREAD

**Issue by kahsa** [vlang/v#7404]
currently just module names, enhance to function names and docs.

**Comment by nedpals** [comment]
@danieldaeschle What do you think?

**Comment by danieldaeschle** [comment]
I wanted to implement a search on the right nav as well. Or do you mean searching on the left sidebar?

**Comment by kahsa** [comment]
yes. but anything useful improvements are welcome of course.

**Comment by JalonSolov** [comment]
One search bar should search for all different types of things.  You shouldn't have to accidentally pick the correct module before you can find a function in it.

**Comment by danieldaeschle** [comment]
hmm, i will think about it how it can work. It's not easy.

**Comment by lilenvy** [comment]
I imagine implementing a client-side only can be heavy in the amount of symbols, but i can imagine this being something that could run server side given a fixed size list of module.symbol.subsymbol

**Comment by danieldaeschle** [comment]
currently there is no server. it's static html.

**Comment by danieldaeschle** [comment]
I've made a prototype how the search could look like:
https://tailwind.run/hxJwJt/1
![image](https://user-images.githubusercontent.com/30751516/103153471-fd920500-4790-11eb-93d0-611b5a025264.png)
What do you think?

**Comment by JalonSolov** [comment]
Very nice!  Better to see the doc immediately than just see the name.

**Comment by danieldaeschle** [comment]
**Technical implementation:**
when building the static site, we generate a javascript file which contains a list of ALL definitions.
when searching we going through that definitions and display it dynamically. The javascript file will be fetched at the end of the static html (body).

**Comment by JalonSolov** [comment]
Probably cleaner to only show first line of docs for things.  Can always click on it to see the whole thing.  Otherwise your `find` box might only show one or 2 items if they're docs are long.

**Comment by danieldaeschle** [comment]
yep, ok.

**Comment by nedpals** [comment]
Looks good to me 👍

**Comment by JalonSolov** [comment]
And copying the idea over here from Discord...
```
Leah
Today at 11:54 AM
Just do a JSON file and use the async web fetch api instead
```
I agree with this idea.

**Comment by danieldaeschle** [comment]
This does not work on local files. And alex wants as less javascript as possible.

**Comment by danieldaeschle** [comment]
https://github.com/vlang/v/pull/7630
