### ISSUE TITLE
Array compilation error: invalid initializer

### ISSUE THREAD

**Issue by Ekopalypse** [vlang/v#7417]
**V version:** 
V 0.1.30 8278af4
**OS:** 
Windows 7 x64

**What did you do?**

```
fn main() {
	mut x := [2]int{}
	x[0] = 1
	x[1] = 2
	
	y := x
	println(y)
}

```
**What did you expect to see?**
[1,2]
 
**What did you see instead?**
error: invalid initializer
 8411 |  array_fixed_int_2 y = x;

**Comment by infernalfire72** [comment]
Aren't you supposed to use
`mut x := []int{len: 2}`?

**Comment by Ekopalypse** [comment]
Not that I know of, but if this is the case, then a v error is expected instead of a compilation error. Personally, I would like to see only ONE way of doing things, but that seems hard to realize.

**Comment by joe-conigliaro** [comment]
@infernalfire72 They are 2 different things, `[2]int{}` is a fixed array `[]int{len: 2}` is a dynamic v array.
@Ekopalypse I have fixed the issue It will be merged soon
