### ISSUE TITLE
V panic: get_type_symbol: invalid type (typ=0 idx=0). Compiler bug.

### ISSUE THREAD

**Issue by pbennyjoseph** [vlang/v#7445]
**V version**: V 0.1.30 7590305
**OS**: linux, Ubuntu 20.04.1 LTS
I've just seen the syntax for Golang and V for 30 mins before writing this code; and this is my first contribution.
I have appended the following code in arrays.v in vlib/arrays seeing the example for passing function as a parameter
```
// merge two arrays using some compare function
[direct_array_access]
pub fn merge_func<T>(a []T, b []T, compare fn (x T, y T) bool) [] T {
	mut m:= []T{len: a.len + b.len}
	mut ia := 0
	mut ib := 0
	mut j := 0
	for ia < a.len && ib < b.len {
		if compare(a[ia], b[ib]) {
			m[j] = a[ia]
			++ia
		} else {
			m[j] = b[ib]
			++ib
		}
		++j
	}

	for ia < a.len {
		m[j] = a[ia]
		ia++
		j++
	}

	for ib < b.len {
		m[j] = b[ib]
		ib++
		j++
	}
}

```
I then ran v arrays.v  but the compiler said to compile with '-shared' argument.
So I ran v -shared arrays.v

**What did you expect to see?**
Some compilation error or successful compilation
 
**What did you see instead?**
V panic: get_type_symbol: invalid type (typ=0 idx=0). Compiler bug. This should never happen. Please create a GitHub issue.

/tmp/v/v2.2671087745854714639.tmp.c:10721: at v_panic: Backtrace
/tmp/v/v2.2671087745854714639.tmp.c:22913: by v__table__Table_get_type_symbol
/tmp/v/v2.2671087745854714639.tmp.c:37500: by v__gen__Gen_cc_type
/tmp/v/v2.2671087745854714639.tmp.c:37417: by v__gen__Gen_base_type
/tmp/v/v2.2671087745854714639.tmp.c:37408: by v__gen__Gen_typ
/tmp/v/v2.2671087745854714639.tmp.c:37580: by v__gen__Gen_write_fn_typesymbol_declaration
/tmp/v/v2.2671087745854714639.tmp.c:37555: by v__gen__Gen_write_typedef_types
/tmp/v/v2.2671087745854714639.tmp.c:37319: by v__gen__Gen_init
/tmp/v/v2.2671087745854714639.tmp.c:37162: by v__gen__cgen
/tmp/v/v2.2671087745854714639.tmp.c:47925: by v__builder__Builder_gen_c
/tmp/v/v2.2671087745854714639.tmp.c:47934: by v__builder__Builder_build_c
/tmp/v/v2.2671087745854714639.tmp.c:47968: by v__builder__Builder_compile_c
/tmp/v/v2.2671087745854714639.tmp.c:48840: by v__builder__compile
/tmp/v/v2.2671087745854714639.tmp.c:49543: by main__main
/tmp/v/v2.2671087745854714639.tmp.c:49807: by main

**Comment by khalyomede** [comment]
Minimal reproducible code which produce the same error message:

```v
struct Parameters {}

fn foo(parameters Parameters) string {
  return ""
}

fn main() {
  foo(map{})
}
```
