### ISSUE TITLE
GUI toolkits: Support wasm/WebAssembly inside a browser with GUI

### ISSUE THREAD

**Issue by andreabravetti** [vlang/v#745]
It wuold be usefull to have full GUI support with wasm inside a browser, like Qt 5.13 can do but with V native GUI toolkits.

It should require also working input (mouse/keyboard) and working clipboard in this scenario to be usefull.

**Comment by elimisteve** [comment]
@andreabravetti Agreed! FYI https://github.com/vlang/ui/ now exists, though I assume it won't support wasm for a while.

**Comment by memeone** [comment]
WASM support really shouldn’t be that hard once we switch over to Sokol for rendering iirc

**Comment by lutherwenxu** [comment]
This should be discussed in https://github.com/vlang/ui/ instead.
It is currently being tracked in vlang/ui#1 .
