### ISSUE TITLE
General discussion about safety in v's language design

### ISSUE THREAD

**Issue by Narice** [vlang/v#7455]
To begin with, I'd like to say that I'm very surprised by the quality of this language and that it is in my opinion almost perfect.
The thing that makes me say that v is not the perfect language is in regards to safety.

## Background
A little bit of background first. I have coded multiple projects in [Elm](elm-lang.org). Elm is a web front-end language that has the following mantra: "no runtime exceptions" and this holds true for every program you write in Elm. If it compiles, it just works.

This is something I'm pursuing in application programming languages and I did not find any language other than elm that has this premise. V could be a really really good candidate for such a thing.

## Panics
First of all, panics. I strongly agree with the points given by @dumblob in #2030. panics are less powerful and controlled than errors. This is in my opinion the next 1 million dollars mistake. It is very tempting to implement an exception style approach as it is at first way easier, but it means more work for the user overall and the code is far less expressive than without them.
Elm is a proof of the fact that one can build software without panics and only with Result/Option return values.
They must be treated by the main program and thus the program never produce any exceptions whatsoever.
This eliminates a lot of headaches for the programmer as he doesn't have to treat all sorts of exceptions implicitly thrown by packages that he includes in his work.
He doesn't have to look at documentation, only the return type of the function he calls is important.

## Mutation, Concurrency and Channels
My second point would be on mutating elements on threads. This should not be allowed is safe code IMHO.
Channels are very easy to work with and provide the same functionality: passing data from one thread to another, but without any of the risks of standard mutable data shared between thread and also without all the mutex complexity and potential problems it may generate.

## Mutable arguments in functions
Thirdly, functions with `mut` arguments seem to not be a good idea except in methods to modify the instance. and this is something that you state as well on the documentation:

> Use `user.register()` or `user = register(user)` instead of `register(mut user)`.

> It is preferable to return values instead of modifying arguments. Modifying arguments should only be done in performance-critical parts of your application to reduce allocations and copying.

Making `register(mut user)` an unsafe expression seems like a good idea as the documentation implies in the first place that it is such an expression (not recommended, used only for performance-critical parts), and I agree with it if it was the intention.

## Conclusion
A possible implementation could be at first a `-safer` flag passed to the compiler for additional check if these particular features are not agreed upon by everyone.
I however think that these changes would greatly improve this beautiful language and would benefit applications made in v as the language would be more resilient.

**Comment by StunxFS** [comment]
Wouldn't it have been better to create this in the Discussions section (https://github.com/vlang/v/discussions)?

**Comment by Narice** [comment]
oh woaw, I didn't know this existed @StunxFS, is this a new feature of GitHub or is it just not used in the majority of repos?
Also, what should I do now? should I close this issue and port it to discussions?

**Comment by StunxFS** [comment]
> oh woaw, I didn't know this existed @StunxFS, is this a new feature of GitHub or is it just not used in the majority of repos?
> Also, what should I do now? should I close this issue and port it to discussions?

Yes, it is a new feature that they implemented days ago, and some repositories may or may not show it freely. I would say close this and move it to discussions, for better organization.

**Comment by Narice** [comment]
ok I'll do that then

**Comment by Narice** [comment]
here is the discussion for later reference: https://github.com/vlang/v/discussions/7457
