### ISSUE TITLE
Makefile: C-based V compiler should have different name/target

### ISSUE THREAD

**Issue by vitalyster** [vlang/v#746]
Using the same `v` target for bootstrapping compiler and a real compiler breaks `make` flow: it should recompile only changed files when I type `make` and it should not require `make clean` each time, that is the purpose of make, if you does not care then you can just build with shell script.
`miniv` compiler name (same as `miniperl`) should be ok :)

**Comment by JalonSolov** [comment]
These days `make` is only used for bootstrapping V on first install, or sometimes for recovering from breaking changes since last update.
