### ISSUE TITLE
update fails on windows 10 cmd

### ISSUE THREAD

**Issue by animesh** [vlang/v#7468]
"v up" failed with following error:

```
c:\v\v.exe
Welcome to the V REPL (for help with V itself, type `exit`, then run `v help`).
cannot compile `C:\v\cmd\tools\vrepl.v`:
Compilation with tcc failed. Retrying with gcc ...
==================
C:\Temp\v\vrepl.13400883252248338624.tmp.c: In function 'string_trim':
C:\Temp\v\vrepl.13400883252248338624.tmp.c:9469:3: error: implicit declaration of function 'array_byte_contains' [-Werror=implicit-function-declaration]
C:\Temp\v\vrepl.13400883252248338624.tmp.c: In function 'string_all_before':
C:\Temp\v\vrepl.13400883252248338624.tmp.c:9808:7: warning: declaration of 'errcode' shadows a global declaration [-Wshadow]
C:\Temp\v\vrepl.13400883252248338624.tmp.c: In function 'string_all_before_last':
C:\Temp\v\vrepl.13400883252248338624.tmp.c:9819:7: warning: declaration of 'errcode' shadows a global declaration [-Wshadow]
C:\Temp\v\vrepl.13400883252248338624.tmp.c: In function 'string_all_after':
C:\Temp\v\vrepl.13400883252248338624.tmp.c:9830:7: warning: declaration of 'errcode' shadows a global declaration [-Wshadow]
C:\Temp\v\vrepl.13400883252248338624.tmp.c: In function 'string_all_after_last':
C:\Temp\v\vrepl.13400883252248338624.tmp.c:9841:7: warning: declaration of 'errcode' shadows a global declaration [-Wshadow]
C:\Temp\v\vrepl.13400883252248338624.tmp.c: In function 'os__args_after':
C:\Temp\v\vrepl.13400883252248338624.tmp.c:10236:2: error: implicit declaration of function 'array_string_contains' [-Werror=implicit-function-declaration]
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**fresh install and update**

**Comment by ChildishGiant** [comment]
v up didn't work for me, as always. Just cloned again to workaround. I've given up reporting each time v up fails since the answer is always "oh well, just clone it"

**Comment by medvednikov** [comment]
@ChildishGiant are you on Windows as well?

We recently added a `v up` test to Linux CI, will do the same on Windows.

This problem is being fixed.

**Comment by LuccaPrado** [comment]
I don't know if is related, but, I tried v up like @animesh and received error too, but, I noticed that Vmmem still spawned after running, even without any v command running (like on my print). 
![image](https://user-images.githubusercontent.com/8813731/103098783-cc77d000-45ea-11eb-824c-77b20b902251.png)

and curiously the cpu and memory usage are going up and down like if it was running something.
![image](https://user-images.githubusercontent.com/8813731/103099280-9e938b00-45ec-11eb-9632-c2b9e551273d.png)

**Comment by JalonSolov** [comment]
That looks like something related to a Virtual Machine, not V.

**Comment by LuccaPrado** [comment]
> That looks like something related to a Virtual Machine, not V.

First I thought it too, but, this process as blocking me to delete the v dir. So I guess that is related to v.

**Comment by JalonSolov** [comment]
"The vmmem process is a virtual process that the system synthesizes to represent the memory and CPU resources consumed by your virtual machines. In other words, if you see vmmem consuming a lot of memory and CPU resources, then that means your virtual machines are consuming a lot of memory and CPU resources."

**Comment by LuccaPrado** [comment]
Thanks for explanation @JalonSolov !

**Comment by yutotakano** [comment]
Not only does `v up` fail, but after one failure of `v up`, all commands related to `v` fail, including a plain `v hello.v`, the V REPL, and more.

**Comment by ChildishGiant** [comment]
Yep, that's been my experience using v up since starting with v. Maybe I'll write a script to wipe my v install, clone source and make the symlink and use that instead

**Comment by danieldaeschle** [comment]
Is this still a problem?

**Comment by JalonSolov** [comment]
If it is... pretend `v up` doesn't exist - use `git pull && ./make.bat` instead.  Should be no need to completely wipe and re-clone.

**Comment by danieldaeschle** [comment]
reopen if needed ^^
