### ISSUE TITLE
v symlink doesn't recognise Admin access on Windows

### ISSUE THREAD

**Issue by pavi2410** [vlang/v#7478]
**V version:** 0.2 e4f94b6
**OS:** Windows 10 20H2

**What did you do?**
Installing prebuilt V 0.2. Ran `v symlink`.

**What did you expect to see?**
I expected not to see this line in the output

```
Unable to set registry value for "Path", are you running as an Administrator?
```
 
**What did you see instead?**
I saw the aforementioned line in spite of running it as admin.

![image](https://user-images.githubusercontent.com/28837746/102932175-c76d3080-44c5-11eb-88e7-c35f065ac76a.png)

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/103320117-136f2680-4a2c-11eb-9284-c3ba708206c6.png)
Also having this issue

**Comment by Ekopalypse** [comment]
Should be fixed with newer versions, there have been several PRs added since then regarding this
and tested it, it works for me.
