### ISSUE TITLE
V doesn't wrap long lines in Windows Terminal

### ISSUE THREAD

**Issue by pavi2410** [vlang/v#7479]
**V version:** 0.2
**OS:** Windows 10 20H2

**What did you do?**
x | V | Python
--- | --- | ---
Command Prompt | ![image](https://user-images.githubusercontent.com/28837746/102934097-82e39400-44c9-11eb-9b03-d38b46da25d0.png) | ![image](https://user-images.githubusercontent.com/28837746/102934123-955dcd80-44c9-11eb-9e42-912180c5e6d9.png)
Windows Terminal | ![image](https://user-images.githubusercontent.com/28837746/102933375-2a5fc700-44c8-11eb-9914-42d2fb00f488.png) | ![image](https://user-images.githubusercontent.com/28837746/102933391-2f247b00-44c8-11eb-8180-47e021989eb5.png)

From this table, it is clear that running V in Windows Terminal prints the wrong output.

**What did you expect to see?**
It should wrap long lines.
 
**What did you see instead?**
It prints only the characters which are visible on the line.

Edit: Same happens with compiled apps.

**Comment by Delta456** [comment]
This has been fixed in the latest V. Can you please check again?

**Comment by pavi2410** [comment]
I can't update V

```
C:\v>.\v.exe up
cannot compile `C:\v\cmd\tools\vup.v`:
vlib\builtin\cfns.c.v:19:2: error: non existent integer const trusted while initializing the size of a static array
   17 | fn C.free(ptr voidptr)
   18 |
   19 | [trusted]
      |  ~~~~~~~
   20 | fn C.exit(code int)
   21 |
```

**Comment by Delta456** [comment]
Now do `\make.bat`

**Comment by pavi2410** [comment]
I checked it and it does hard wrapping on long lines.
