### ISSUE TITLE
Operator `*` for string type

### ISSUE THREAD

**Issue by StunxFS** [vlang/v#7480]
The string type contains a method called `repeat` that allows repeating a string the number of times that have been passed as a parameter to the method.

```v
"d".repeat(4) // output: dddd
```

My idea is to implement the `*` operator, as a shortcut to the method, as well as the Python `str` type:

```v
fn (str string) * (count int) string {
    return str.repeat(count)
}

"dd" * 4 // output: dddd
```

You could also avoid using a function for the operator, replacing the operator with the repeat function in code generation:

```v
println("dd" * 4)
```
to C:
```c
println(string__repeat(_STRLIT("dd"), 4));
```

What do you think?

**Comment by medvednikov** [comment]
For simplicity, readability, and maintainability V operators have a simple rule: both sides must have the same type.

Operator overloading is very dangerous and has to be used carefully.

**Comment by StunxFS** [comment]
Okay, sorry, I'm still getting used to this wonderful language. I had forgotten that detail. Again, sorry.

**Comment by medvednikov** [comment]
No need to be sorry ;) A valid question.
