### ISSUE TITLE
return is not required in anonymous functions?

### ISSUE THREAD

**Issue by chrisseto** [vlang/v#7482]
**V version:**  0.2-7-gf4c28821
**OS:** WASM playground / debian docker container

**What did you do?**
I ran the following code in the v WASM playground:
```
println([1,2,3].filter(fn (n int) bool {
	true
}))
```

**What did you expect to see?**
I expected to see 1, 2, 3 printed out or I expected to see a compiler error about the lack of a `return` statement.
 
**What did you see instead?**
Nothing is printed (an empty array is printed).

It seems that by not returning a value in this closure, the zero value of the return type is implicitly returned?

**Comment by StunxFS** [comment]
The same thing happens when compiling with the C backend. The output in C is this:

```c
VV_LOCAL_SYMBOL void main__main() {
array_int _t73_orig = new_array_from_c_array(3, 3, sizeof(int), _MOV((int[3]){1, 2, 3}));
	int _t73_len = _t73_orig.len;array_int _t73 = __new_array(0, _t73_len, sizeof(int));
	for (int _t74 = 0; _t74 < _t73_len; ++_t74) {
	  int it = ((int*) _t73_orig.data)[_t74];
	if (	anon_68_7_16(it)) array_push(&_t73, &it); 
 }
		println(array_int_str( _t73));
}
```

The anonymous function is generated to:

```c
VV_LOCAL_SYMBOL bool anon_68_7_16(int n) {
		true;
		return 0;
	}
```

If the `return` is used, this is generated:

```c
VV_LOCAL_SYMBOL bool anon_68_7_16(int n) {
		return true;
	}
```

> It seems that by not returning a value in this closure, the zero value of the return type is implicitly returned?

Because the anonymous function does not return a true value, nothing is added to the array, and therefore it is printed empty.

**Comment by Delta456** [comment]
`return` must be required
