### ISSUE TITLE
-lib argument does not work

### ISSUE THREAD

**Issue by vitalyster** [vlang/v#749]
**V version: 0.1.8** 
**OS: Linux** 
**C compiler version: 6.3.0** 

**What did you do?**
`-lib` argument is documented in vdoom repo. While it does not present in `--help` it still works but throw error
```
v -lib hello.v
```
**What did you expect to see?**
expecting `hello.o`
 
**What did you see instead?**
```
Building module hello.v...
Cross compiling /home/me//.vlang//vlib//hello.v.o
V panic: "/home/me//.vlang//vlib/builtin/array.vh" doesn't exist
```

**Comment by AtjonTV** [comment]
Issue has the same compile error as #456.
PR #621 has a working fix for this exact compile error.

**Comment by vitalyster** [comment]
I see, thanks
