### ISSUE TITLE
Unable to initialize struct with reference fields

### ISSUE THREAD

**Issue by lilenvy** [vlang/v#7492]
**V version:** 0.2 70c1364
**OS:** Ubuntu 20.10

**What did you do?**
```v
struct Node {
  value int
  next &Node
}

fn new_node() Node {
  return Node{value: 123}
}
```

**What did you expect to see?**
A Node, note that this is documented on the docs.md file
 
**What did you see instead?**
reference field `Node.next` must be initialized

**Comment by lilenvy** [comment]
I'm trying to use a workaround now with:
```v
mut p := unsafe { malloc(2) }
```
but it'd be awesome to get more info on how to solve this issue on the compiler error

**Comment by lilenvy** [comment]
Another workaround:
```v
empty := []&Node{len: 1}[0]
Node{123, empty}
```

**Comment by nedpals** [comment]
@lilenvy  Can you try setting the field to zero? Like this:

```v
struct Node {
  value int
  next &Node = 0
}
```

**Comment by lilenvy** [comment]
It does work like this!
Alternatively if I don't want to initialize it as zero by default, I can assign  an initial value like:
```v
n := &Node{123, 0}
```

Could this be documented?
Is the "References" section on the documentation the best place for this?

**Comment by ulises-jeremias** [comment]
You can set the default value as `voidptr(0)` in the struct definition too

**Comment by lilenvy** [comment]
I will send a PR with:

1. Update error message so it's easier to know how to handle this.
2. Update documentation on references so the examples match the current behavior if intended.
