### ISSUE TITLE
Incorrect results in integer multiplication

### ISSUE THREAD

**Issue by Joetib** [vlang/v#7497]
**V version:** 
**OS:** Windows 10 x64

**What did you do?**
I fired up the terminal after upgrading to V 0.2 
I tried multiplying two integers: 
```
12345678900000000000 * 1234567890000000
```

**What did you expect to see?**
The expected answer should have been
`15241578750190521000000000000000000`
 
**What did you see instead?**
`2164266905463160832`

This seem to happen only for big numbers.

**Comment by spytheman** [comment]
V does not use bignums by default and multiplying these overflows u64.
This V program will work for this case:
```v
import math.big
println( (big.from_u64(12345678900000000000) * big.from_u64(1234567890000000)).str() )
```

**Comment by Joetib** [comment]
Hmm, I guess I think too much in higher level languages

**Comment by Ekopalypse** [comment]
@spytheman 
>V does not use bignums by default

Is it planned to do so? If not, I assume this issue can be closed.

**Comment by JalonSolov** [comment]
No, there are no current plans for V to use bignums by default.
