### ISSUE TITLE
Better support of optionals

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#75]
Create them outside of optional functions, `None`, assign values, etc.

**Comment by ntrel** [comment]
It should also be possible to compare optionals with `none` or with a value:
```
mut opt := int? // possible syntax to create empty optional
assert opt == none
opt = 5
assert opt == 5
assert opt != 'hi' // error, cannot compare int? and string
```
BTW as `none` is not a type I don't think it should be Capitalized.

Initializing an optional from a value could be done with a built-in constructor function for type inference: `mut opt := optional(5)`. `opt` would be of type `int?`. (I've used existing `T?` syntax here, but see https://github.com/vlang/v/issues/67#issuecomment-480364217 for why we should change to `?T`).
