### ISSUE TITLE
aliasing a mutable array with a slice leads to undefined behavior

### ISSUE THREAD

**Issue by oconnor663** [vlang/v#7508]
This is an adapted version of the example from https://github.com/vlang/v/issues/6007, modified to work under V 0.2. @ntrel suggested filing it separately.

```
// Make an array of numbers.
mut nums := [0, 1, 2, 3]

// Alias the array with a slice.
slice := nums[0..]

// Take a reference to the last element.
x := &slice[3]

// Read the reference and print it. Prints 3.
println("x is ${*x}")

// Add a new element to the array.
nums << 4

// Read the reference and print it again.
// Expected: Either prints 3 again, or a compiler error.
// Actual: Prints some other number. (On my machine right now, it prints 0.)
println("x is ${*x}")
```

I can't figure out how to inspect the intermediate C source files in this version to see exactly what it's doing -- looks like they get cleaned up automatically now, and I need to find the flag to turn that off -- but running that code under valgrind reports an "Invalid read of size 4", so it seems like the effect is the same as in https://github.com/vlang/v/issues/6007.

**Comment by danieldaeschle** [comment]
```
x is 3
x is 3
```

as you wanted :)
it works now!

**Comment by oconnor663** [comment]
@danieldaeschle to make sure I understand correctly, does it work today because the memory referred to by `slice` is leaked by default?

**Comment by danieldaeschle** [comment]
I have no clue about this. Maybe @spytheman can answer this?
