### ISSUE TITLE
builder error: Header file <openssl/rand.h>, needed for module `net.openssl` was not found. Please install OpenSSL development headers.

### ISSUE THREAD

**Issue by anishkny** [vlang/v#7519]
**V version:** V 0.2 e4f94b6
**OS:** Mac OS Catalina 10.15.6 (19G2021)

**What did you do?** Execute `v run examples/links_scraper.v`

**What did you expect to see?** Correct output
 
**What did you see instead?**
```
$ git clone https://github.com/vlang/v
$ cd v/examples
$ cat ./links_scraper.v
import net.http

fn main() {
	html := http.get_text('https://news.ycombinator.com')
	mut pos := 0
	for {
		pos = html.index_after('https://', pos + 1)
		if pos == -1 {
			break
		}
		end := html.index_after('"', pos)
		println(html[pos..end])
	}
}

$ v run ./links_scraper.v
builder error: Header file <openssl/rand.h>, needed for module `net.openssl` was not found. Please install OpenSSL development headers.
```

**Comment by spaceface777** [comment]
I think this error is fairly straightforward: you need to install the `openssl` development headers for the `net.openssl` ( which is used by the `net.http` module) to work.

On macOS, `brew install openssl` should install it.

**Comment by spaceface777** [comment]
Plus, apart from that error message, the `openssl` requirement is also documented in the V README:

> If you plan to use the http package, you also need to install OpenSSL on non-Windows systems.
> ```
> macOS:
> brew install openssl
> ```

**Comment by Martengg** [comment]
Sorry if my qustion is dumb, but what about Windows? In the readme there are no further information on how to install openssl on windows. I am getting the same error when compiling the websocket example. I already tried to install openssl-win64 but I don't know were to include the header files so vlang can use them.

Thank you in advance
