### ISSUE TITLE
Regex module doesn't match $ in groups

### ISSUE THREAD

**Issue by jacopo-j** [vlang/v#7522]
**V version:** V 0.2 e4f94b6
**OS:** macos, Mac OS X, 10.14.6, 18G7016

**What did you do?**
```v
mut re := regex.regex_opt(r'\d(\s|$)') or { panic(err) }
start, _ := re.find('3')
```

**What did you expect to see?**
The string `3` should match the regex `\d(\s|$)`, so `start` should be equal to `0`.
 
**What did you see instead?**
The string isn't matched, `start` is equal to `-1`.

**Comment by penguindark** [comment]
in V regex `|$` is matched as a char:
your pattern in v Regex says: match a digit followed by a space or a $ char and puth the last OR token in a group.
As written in the header of the documentation: https://github.com/vlang/v/tree/master/vlib/regex#basic-assumption
The basic element of this regex engine is the token and thus is not fully compatible with the PCRE syntax for the queries.
If you can show the complete snippet of code and what you want achieve we can help you.
Otherwise there is a PCRE C module that you can use.

**Comment by jacopo-j** [comment]
I see. What I would like to achieve is "match a digit followed by either a whitespace character, or nothing at all". Examples of strings where I would like to match the number `3`:

* `Lorem ipsum dolor 3 sit amet`
* `Lorem ipsum dolor sit amet 3`

But I do **not** want to match `3` it in:

* `Lorem ipsum dolor 34 sit amet`
* `Lorem ipsum dolor sit amet 34`
* `Lorem ipsum dolor 3a sit amet`

I hope you get the idea. At the moment I have added a trailing space to the strings as an ugly workaround, so that `\d\s` works. If you know any better way to do this with V regex, I would be glad to hear it.

**Comment by penguindark** [comment]
```v
import regex
fn main() {
	query := r'(\s+(3)\s)|(\s(3)[^\w])'
	txt_list := [
		// positive
		'Lorem ipsum dolor 3 sit amet',
		'Lorem ipsum dolor sit amet 3',
		// negative
		'Lorem ipsum dolor 34 sit amet',
		'Lorem ipsum dolor sit amet 34',
		'Lorem ipsum dolor 3a sit amet'
	]
	mut re := regex.regex_opt(query) or { panic(err) }
	for count, txt in txt_list {
		start, end := re.find(txt)
		if start >= 0 {
			println("#$count [$start,$end] [${txt[start..end].trim_space()}]")
		} else {
			println("#$count Not Found!")
		}
	}
}
```
semplice semplice ;)
The v_regex module is not for heavy or complicated regex, for that there is PCRE C module.

**Comment by penguindark** [comment]
In reality you don't need the nested group if you don't want make use of the `replace_by_fn` function.
The query can be more simple: `r'(\s+3\s)!(\s+3[^\w])'`

**Comment by jacopo-j** [comment]
That's not very pretty, but I'll consider taking the C PCRE route as you suggested. Thanks :) 
I'll close this issue since at the moment this is the intended behaviour.

**Comment by penguindark** [comment]
If you have more question please join the Discord channel, we'll be happy to answer to your questions :)
https://discord.com/channels/592103645835821068/592294828432424960
by the way, if you want only the "3" find is overkilling, a more simple and quick code is:
```v
query := r'.*(3)[^\w]'
mut re := regex.regex_opt(query) or { panic(err) }
for count, txt in txt_list {
  start, end := re.match_string(txt)
  if start >= 0 {
    println("#$count [$start,$end] [${re.get_group_by_id(txt,0)}]")
  } else {
    println("#$count Not Found!")
  } 
}
```
