### ISSUE TITLE
vfmt unsafe block with single statement

### ISSUE THREAD

**Issue by ntrel** [vlang/v#7535]
**V version:** recent git
**OS:** Windows 10

**What did you do?**
Ran vfmt on:
```v
unsafe {
	C.memcpy(res.metas, m.metas, metasize)
}
```
**What did you expect to see?**
No change. Below vfmt is treating the whole construct as an expression, when it is deliberately formatted as a statement. This makes it awkward to add more statements to the block.
 
**What did you see instead?**
```v
	unsafe { C.memcpy(res.metas, m.metas, metasize) }
```

**Comment by serkonda7** [comment]
Right now we allow single line `or { ... }` because they often contain only one stmt and do not change frequently.
But we force if expression on multiple lines (unless it's an assign) because their stmts change more often.

@ntrel how often do statements inside unsafe change and how many stmts do they contain most times?

**Comment by ntrel** [comment]
@serkonda7 Formatting it all on one line makes it look like an expression, when it is a statement because the result is not used (in general). This is confusing. If it was implicitly used as the last line of an if or match branch, then formatting as an expression is correct.

> we force if expression on multiple lines (unless it's an assign) because their stmts change more often

Rather than guess how often statements in different constructs change, it would be best for vfmt to trust the programmer's formatting rather than make unnecessary 'fixes' of already correctly formatted code.

**Comment by serkonda7** [comment]
Later today I can make a change to leave the linebreaks as is.
