### ISSUE TITLE
modules.vlang.io still not sorted "properly"

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#7539]
The list down the right side of the page has improved from initial attempts, but is still not as I would expect.

I can understand why it is the way it is, but my contention is that it should be sorted for _humans_ to read, and almost every human simply wants to see a case-insensitive alphabetical list, _ignoring_ leading special characters.

For example, the very first list you see is for the `builtins` module, and the top looks fine... but when you scroll down...
```
vstrlen
[]byte
    bytestr
    clone
    hex
    index
[]char
    index
[]int
    sort
```
Why is there something starting with `b` (ignoring the `[]`) after `vstrlen`?  Scroll down further...
```
[]string
    eq
    index
    join
    join_lines
    sort
    sort_by_len
    sort_ignore_case
    str
any_float
    str
any_int
    str
```
Now we have something that starts with `a` all the way down here??  Why wasn't it at the TOP of the list?

Yes, I know they are being sorted by type, but if I am looking for something by name, and don't already _know_ the type, that means a lot of scrolling, or using the browser's `Find` function, instead of just seeing a nice, simple, alphabetical list.

**Comment by nedpals** [comment]
@JalonSolov I'll sort them by name only for now but it'll be added back once there are additional UI elements that will distinguish the classifications

**Comment by JalonSolov** [comment]
That will be fine.  Keep them sorted by alpha, but mark them as different types visually.

**Comment by danieldaeschle** [comment]
Sorting by kind is recommended from me.

Maybe we should do it like go?
![image](https://user-images.githubusercontent.com/30751516/103137351-8c871a80-46c8-11eb-8355-19244bb9b86a.png)

Declaring the kind. (func or type)

**Comment by danieldaeschle** [comment]
That `any_float` is after `[]string` is just a bug. We should sort it better.

**Comment by JalonSolov** [comment]
That works, too.  The problem with what we have right now is that there's no differentiation.  It just looks partially sorted instead of properly sorted.
