### ISSUE TITLE
Dual assignments cause errors in C style for loops

### ISSUE THREAD

**Issue by Irratix** [vlang/v#7546]
**V version:** 0.2
**OS:** Linux
(This code has been tested on the website code.golf, These are the version number and OS as told to me by the administrator of that website.)

**What did you do?**
V has just been added to code.golf and I was experimenting with for loops. Specifically, putting dual assignments/declarations in a C style for loop iterator and initialization.
Examples:
`for a,b := 0,1; a < 10; a++ {...}`

```
mut b := 1
for a := 0; a < 9e5; a,b=b,a+b {...} 
```

**What did you expect to see?**
In either case, I expected either an error clearly expressing this for loop syntax does not support dual assignments, or that dual assignments are simple handled as working expectedly.
 
**What did you see instead?**
The first example returned this error:
```
/tmp/code.v:1:9: error: unexpected `:=`, expecting `in`
1 | for a,b := 0,1; a < 10; a++ {println('a')}
| ~~
exit status 1
```

The second example returned this error:
```
Compilation with tcc failed. Retrying with cc ...
builder error: sh: 1: cc: not found
 
exit status 1
```

I asked the administrator of the website for the compiler error of the second example, and it looks like this:
```
/tmp/v/foo.10321316910180452392.tmp.c: In function ‘main__main’:
/tmp/v/foo.10321316910180452392.tmp.c:8265:27: error: expected expression before ‘int’
 8265 |  for (int a = 0; a < 9e5; int _var_24 = a;
      |                           ^~~
```

**Comment by Delta456** [comment]
Dual assignment loops ain't allowed unlike C.

**Comment by medvednikov** [comment]
Good find @Irratix 

This will be fixed.
