### ISSUE TITLE
Merry Christmas to you all, I wish you good health and good luck!

### ISSUE THREAD

**Issue by yuyi98** [vlang/v#7553]

**Comment by medvednikov** [comment]
Merry Christmas @yuyi98 !

**Comment by Larpon** [comment]
Merry Christmas @yuyi98 ! Thanks for all your contributions!

**Comment by spytheman** [comment]
Merry Christmas @yuyi98 !

**Comment by nedpals** [comment]
Merry Christmas @yuyi98! Wishing you the same as well 😃

**Comment by penguindark** [comment]
@yuyi98 Merry Christmas and a good and healthy new year! :smiley:

**Comment by Delta456** [comment]
Merry Christmas @yuyi98! I hope you a good life and a happy new year! ☃️🌲

**Comment by JalonSolov** [comment]
"May your worst tomorrows be better than your best yesterdays."

**Comment by Ekopalypse** [comment]
Maybe it's time to close this one, or should it stay open for next Christmas? ;-)

**Comment by JalonSolov** [comment]
Let's start a new one then.  :-)
