### ISSUE TITLE
`in` operator doc is inconsistent with maps

### ISSUE THREAD

**Issue by lkppo** [vlang/v#7554]
`in` operator search in values for arrays and keys  for maps. It's inconsistent in doc because .  It could search for values only, and a new operator in_keys could search in indices/keys.

**Comment by serkonda7** [comment]
Could you please link to the exact line in docs.

**Comment by lkppo** [comment]
https://github.com/vlang/v/blob/master/doc/docs.md#in-operator

**Comment by ntrel** [comment]
>  It could search for values only

Maps are not designed to lookup a value efficiently (although in practice our implementation can do linear search but with minimum 50% efficiency when there are deleted items). Maps are designed to look up keys efficiently (better than linear performance).

**Comment by lkppo** [comment]
Le 28/12/2020 20:35, Nick Treleaven a écrit :

> It could search for values only 
> 
> Maps are not designed to lookup a value efficiently (although in practice our implementation can do linear search but with minimum 50% efficiency when there are deleted items). Maps are designed to look up keys efficiently (better than linear performance).

I'm only talking about functionality and consistency of the language.
The performance of the operation does not matter and should not be the
reason why the IN operator is not symmetrical. If the language does not
offer both operations, it will be up to the user to plug the holes. And
if it is not symmetrical it will be surprising and a source of
frustration.

-- 
Stéphane Aulery
