### ISSUE TITLE
regex giving me issues, example:

### ISSUE THREAD

**Issue by despiegk** [vlang/v#7559]
```vlang
import regex

fn main() {

	mut text := '
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
        ignorecase = true
        precomposeunicode = true
[remote "origin"]
        url = https://github.com/crystaluniverse/crystaltools
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master

'


	query := r'url *= *https:.*'
	mut re := regex.regex_opt(query) or { panic(err) }

	mut gi := 0
	all := re.find_all(text)
	println(all)
	for gi < all.len {
		println("RESULT:")
		println('${text[all[gi]..all[gi + 1]]}')
		gi += 2
	}
	
	println('OTHER TEST')

	//OTHER TEST
	start, end := re.match_string(text)
	if start >= 0 {
		println("[$start,$end] [${re.get_group_by_id(text,0)}]")
	} else {
		println("# Not Found!")
	} 

}
```

result

```bash
bash-3.2$ ./v run examples_tests/regextest3.v
[206, 224]
RESULT:
url = https://gith
OTHER TEST
[0,238] []
```

regex test on https://regex101.com/r/w6TxKT/1

I tried with CPRE C module as well, but no better luck

thanks for helping

Kristof

**Comment by penguindark** [comment]
Can you please elaborate the problem? It seems correct on what you write in the regex query.
What do you want to achieve?

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/103164708-f27dba00-480e-11eb-9db8-d2e03443800d.png)

on regex101 can see that my query should work

its a very generic one

but the result returned from code is not same

```
url = https://gith
```

it stops too early? why

**Comment by penguindark** [comment]
I'll investigate the issue, meanwhile you can try with: `r'url *= *https?://[\w./]+'`
Please rember that V-regex **is not PCRE compliant**, have a look at the documentation: https://github.com/vlang/v/tree/master/vlib/regex
If you want have a PCRE syntax compatibility please use the PCRE module: https://vpm.vlang.io/mod/spytheman.regex

**Comment by penguindark** [comment]
I made a PR with a fix, please wait until the merge.
But remember that the V-regex will capture all the chars it finds **until the end of the string** not until the `\n` like the PCRE.
If you want stop the find you need to modify the pattern writing this: `pattern := r'url *= *https://.*'+'\n'` (but it capture the new line!)
As alternative you can use a more fitted pattern like: `r'url *= *https://[^\s]+'`

**Comment by despiegk** [comment]
fyi the prcre one didn't do it either, other issues
will wait for the merge & try again

many thanks

**Comment by penguindark** [comment]
the PR is merged :), about the PCRE it is a direct mapping on C PCRE module,
I've no idead on its internal mechanisms.
@spytheman Are you the mainteiner of the module? Any Idea?

**Comment by penguindark** [comment]
@despiegk Can we close this issue?
