### ISSUE TITLE
f32 or f64 to sqlite real

### ISSUE THREAD

**Issue by Olprog59** [vlang/v#7570]
**V full version: V 0.2 7507403** 
**OS: macos, macOS, 11.1, 20C69** 

**What did you do?**
I wanted to insert a struct with float number in sqlite : 
```
struct Movie {
    ...
    backdrop_path string
    popularity f32
    vote_count int
    ...
}

sql d.db {
    insert movie into Movie
} 
```

**What did you expect to see?**
I wanted to have in popularity: 8.9
 
**What did you see instead?**
I have a null in sqlite

**Comment by dumblob** [comment]
Have you tried `f64`? Sqlite supports only 64bit floats (and thus nothing else than `f64` can be retrieved from sqlite DB). I agree though, that this probably should be a compile-time error (or in worst case a runtime error) instead of silently storing/withdrawing `null`.

**Comment by ArtemkaKun** [comment]
Hi @Olprog59,
can you confirm that this error still exists on the fresh version of V (0.2.4+) on macOS?

**Comment by walkingdevel** [comment]
It was fixed in 2021. I tried to reproduce this behavior. Now it's okay: https://vosca.dev/p/3566b65ee5
