### ISSUE TITLE
String interpolation does not work for pointers

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#758]
**V version:**
V 0.1.8
**OS:** 
Ubuntu 19
**What did you do?**
I tried to compile the following program pointer.v with the command v pointer.v

fn main() {
	i := 100
	ptr := &i
	println(ptr) // 0x7ffd82de0f5c
        println('An integer: $i, its location in memory: $ptr\n')
}

**What did you expect to see?**
The last println line should have stated:
An integer: 100, its location in memory: 0x7ffd82de0f5c
 
**What did you see instead?**
pass = 2 fn = 'main'
panic: pointer.v: 8
unhandled sprintf format "int*"

**Comment by medvednikov** [comment]
Fixed.

**Comment by Ivo-Balbaert** [comment]
Wow, this is astonishing, I never saw a fix as quick as that in my entire career!
