### ISSUE TITLE
Check version of installed v module

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#7580]
We need a way to get the current version of the installed V module.

like
```
v version mymod
```

**Comment by danieldaeschle** [comment]
and a check if a newer version is available would be nice. as well as an update command.

**Comment by spytheman** [comment]
`v update modname` works, as well as `v install modname` when the module is already installed.

**Comment by spytheman** [comment]
Also just `v update` updates everything.

**Comment by spytheman** [comment]
There is `v outdated` that checks if some modules have newer versions.
For more details, see cmd/tools/vpm.v .

**Comment by spytheman** [comment]
Extending `v version mymod` to show the version of `mymod` would be nice indeed.

**Comment by danieldaeschle** [comment]
> `v update modname` works, as well as `v install modname` when the module is already installed.

strange that both have the same behaviour. could we clean that up?

**Comment by spytheman** [comment]
That is expected behaviour, not a bug - `update` only updates, while `install` can install and update, depending on whether the module is present.

**Comment by danieldaeschle** [comment]
What is the `update` for when `install` does both? Any use case?

**Comment by donnisnoni** [comment]
i prefer `upgrade` over `update`

**Comment by Delta456** [comment]
Or we can have `v install -u`  where `-u` means to update if needed.

**Comment by JalonSolov** [comment]
`v install` already does that without the extra switch.

**Comment by spytheman** [comment]
`v update package` will not install a package, if it is not already installed. `v install package` will. Both are useful.

**Comment by danieldaeschle** [comment]
`v show <module>` shows the version.
