### ISSUE TITLE
Match with string const case doesn't work

### ISSUE THREAD

**Issue by dexbyte** [vlang/v#7585]
**V version:** V 0.2 b16052d.e4f94b6
**OS:** macos, Mac OS X, 10.15.7, 19H15

**What did you do?**
```
const (
  one = 'one'
)


match one {
  one {
    println("Works")
  }
  else {
    println("Doesn't work")
  }
}
```

**What did you expect to see?**
```
Works
```
 
**What did you see instead?**
```
================ V panic ================
   module: builtin
 function: __as_cast()
  message: as cast: cannot cast 200 to 221
```
string const as a match expression works but doesn't work as a case

**Comment by kitech** [comment]
match with integer const also not work

**Comment by danieldaeschle** [comment]
integer const works for me

**Comment by danieldaeschle** [comment]
please provide an example or a new issue
