### ISSUE TITLE
Inherited methods from embedded structs fails to compile when instance is created on the heap.

### ISSUE THREAD

**Issue by jasper-lyons** [vlang/v#7586]
**V version:** V 0.2 9a5bbc3.13b14ec
**OS:** linux, "Manjaro Linux"

**What did you do?**
I attempted to call a method defined on an embedded struct (Parent) on a reference to an instance of the struct with Parent embedded in it (Child). 

**What did you expect to see?**
The program successfully compiled and the method successfully called or a specific error message if this behavior is not allowed / supported.
 
**What did you see instead?**
The v cli program attempted to compile the program with tcc, failed and fell back to cc and errors out as direct property access is used on a pointer to a struct rather than indirect access. The error message follows:

```
>>> v inherited-functions-bug.v                                       [130]
Compilation with tcc failed. Retrying with cc ...
==================
/tmp/v/inherited-functions-bug.1280952972127319486.tmp.c:8264:1: note: (near initialization for ‘(anonymous)’)
/tmp/v/inherited-functions-bug.1280952972127319486.tmp.c:8267:30: error: ‘child’ is a pointer; did you mean to use ‘->’?
 8267 |  main__Parent_inherited(child.Parent);
      |                              ^
      |                              ->
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.
```

**Notes**
* This error does not occur if the child instances created in the reference code is done so on the stack, rather than the heap e.g. `child := Child{}` vs `child := &Child{}`.

**Reference code which causes the error**
```v
struct Parent {}

fn (p &Parent) inherited() {}

struct Child { Parent }

fn main() {
  child := &Child{}
  child.inherited()
}
```

**Comment by danieldaeschle** [comment]
works now
