### ISSUE TITLE
Array of Array/Map easily leads to runtime error (invalid memory address)

### ISSUE THREAD

**Issue by lilenvy** [vlang/v#7597]
**V version:** V 0.2 70c1364.1383771
**OS:** Ubuntu 20.10

**What did you do?**
Array of Array
```v
fn main() {
	mut x := [][]int{len: 10}
	println(x) // OK
	x[3] << 123 // RTE
	println(x)
}
```
Array of Map
```v
fn main() {
	mut x := []map[string]int{len: 10}
	println(x) // OK
	x[3]['123'] = 123 // RTE
	println(x)
}
```

**What did you expect to see?**
- For Array of array: appending values with `<<` should automatically initialize the array
- For Array of map: assigning a value to a key through `m[k]=v` should automatically initialize the map
 
**What did you see instead?**

Runtime error due to invalid memory address.

**Note:** I understand I can always set the `init` property, but it feels like I shouldn't need to do it. Or at least it is not obvious

**Comment by div72** [comment]
Arrays and map should not be automatically created imo, although the error messages could be better.
