### ISSUE TITLE
Setting a value to a map of a map results in no action if the outer map key wasn't initialized

### ISSUE THREAD

**Issue by lilenvy** [vlang/v#7598]
V version: V 0.2 70c1364.1383771
OS: Ubuntu 20.10

**What did you do?**
```v
fn main() {
	mut x := map[string]map[string]int{}
	println(x) // {} - OK
	x['123'] = map[string]int{}
	x['123']['123'] = 123 // OK
	x['456']['456'] = 456 // Does not work, but does not throw an error
	println(x) // {123: {123: 123}} - NOT OK, missing 456
}
```

**What did you expect to see?**
The final result should have been `{'123': {'123': 123}, '456': {'456': 456}}`, but was instead `{123: {123: 123}}`
 
**What did you see instead?**
Possibly related to #7597, maps are not supposed to be uninitialized, but maps inside other structures like structs, maps, or arrays seem to be some kind of nil pointer.

Unlike #7597, this case does not error out, but instead does nothing when setting the value for `'456'`.
If I initialize the value before (like I do in the example with `'123'`) then it works, so the issue comes from my expectation that the uninitialized map should have been auto-initialized when assigning the first k/v pair.

**Comment by lilenvy** [comment]
p.s. Also unlike #7597, a map of array seems to work as intended.

```v
fn main() {
	mut x := map[string][]int{}
	println(x) // {} - OK
	x['123'] << 123
	println(x) // {'123': [123]} - OK
}
```

**Comment by yuyi98** [comment]
It's right.
x['456'] return default zero value, so x['456']['456'] = 456 cannot insert into x.

**Comment by lilenvy** [comment]
> return default zero value

Isn't V supposed to not have "zero" arrays or maps tho? See: #7597
Given this my expectation remains in that it should be either auto-initialized or return an error value that I could handle with `or{}` or bubble with `?`

**Comment by yuyi98** [comment]
Fixed.
```vlang
fn main() {
	mut x := map[string]map[string]int{}
	println(x) // {} - OK
	x['123'] = map[string]int{}
	x['123']['123'] = 123 // OK
	x['456']['456'] = 456 // Does not work, but does not throw an error
	println(x) // {123: {123: 123}} - NOT OK, missing 456
}

PS D:\Test\v\tt1> v run .
{}
{'123': {'123': 123}, '456': {'456': 456}}
```
