### ISSUE TITLE
manual Free() not work properly ?

### ISSUE THREAD

**Issue by k1attila12** [vlang/v#7602]
**V version:**  0.2
**OS:** win10

**What did you do?**
```v
struct Alma {
   mut:
      ax  int
      bx  int
   }
mut x:=&Alma{}
x.ax=100
x.bx=200
free(x)
println(x.ax)
println(x.bx)
```
**What did you expect to see?**

 runtime error or compiling error ?

**What did you see instead?**

100
200

**Comment by Delta456** [comment]
`autofree` isn't enabled by default yet.

**Comment by k1attila12** [comment]
Thank you, but i wanted to try manual memory management. (free(x))
After free() , i can access to the struct variable x.ax

**Comment by kitech** [comment]
Maybe change title to `manual free() not work`

**Comment by dumblob** [comment]
>Maybe change title to `manual free() not work`

I'd distinguish the following 2 things:

1. if compiling **without** `-autofree`, then `free()` seems to have some issues
2. if compiling **with** `-autofree` then `free()` has basically none or very limited interoperation with the automated freeing

Regarding (2) I'm not sure what's the plan as currently *V* doesn't seem to provide any way to express "I'll track memory of this particular variable myself, so compiler, don't get in my way."

**Comment by danieldaeschle** [comment]
works now
```
main.v:9:1: warning: function `free` must be called from an `unsafe` block
    7 | x.ax=100
    8 | x.bx=200
    9 | free(x)
      | ~~~~~~~
   10 | println(x.ax)
   11 | println(x.bx)
0
0
```
