### ISSUE TITLE
use `in` operator to check if character is in string

### ISSUE THREAD

**Issue by davekch** [vlang/v#761]
In the documentation you state 

> In V, a string is a read-only array of bytes

so it would be intuitive to use the `in` operator on strings.

Right now, 

```
fn main(){
    mystr := 'abcd'
    if 'a' in mystr {
        println('a is in $mystr')               
    }
}
```
results in 
```
pass=2 fn=`main`
panic: substring.v:3
`in` requires an array
```

**Comment by ntrel** [comment]
First, 'a' is a string, use backticks for characters (it ought to produce runes instead though).

`in` is an O(n) operator, so a function would make this clearer. If we keep `in`, it needs to be overloadable for structs so the string struct can support it. Even then it can't find both a substring and a byte/rune unless the method takes a generic type.

**Comment by alexesprit** [comment]
The `in` operator now can be used for strings.
