### ISSUE TITLE
Can not use a constant to set the size of a byte array

### ISSUE THREAD

**Issue by aguspiza** [vlang/v#762]
**V version: 0.1.6** 
**OS: linux** 
**C compiler version: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)  ** 

**What did you do?**

```
const( Arrlen = 16)

fn test_arrconst() {
    //mut arr := [ byte(0) ; Arrlen]
    //mut arr := [16]byte
    mut arr := [Arrlen]u8
    str := tos(arr, Arrlen)
	assert str.len == Arrlen 
} 
```

**What did you expect to see?**
I expected to compile and pass the test
 
**What did you see instead?**
Compiler error:

test_arrconst
0
pass=2 fn=`test_arrconst`
panic: os_test.v:6
undefined: `u8`

**Comment by ntrel** [comment]
`tos` takes a `byteptr`, not a `[]byte`:

> pub fn tos(s byteptr, len int) string {

This code works:
```
    mut arr := [ byte(0) ; Arrlen]
    str := tos(arr.data, Arrlen)
```
>    //mut arr := [16]byte
>    //mut arr := [Arrlen]u8

See #1062 for fixed size arrays. Closing this in favour of that one as it already contains discussion.

**Comment by ntrel** [comment]
Note: Go does support using a compile-time constant for fixed-size arrays:
https://play.golang.org/p/3t1y4TzFieN

**Comment by medvednikov** [comment]
> str := tos(arr.data, Arrlen)

This is a better way: `str := string(arr)`

`tos` will be made private soon, just like `tos2` was.

**Comment by medvednikov** [comment]
@aguspiza  Fixed.
