### ISSUE TITLE
typeof 

### ISSUE THREAD

**Issue by k1attila12** [vlang/v#7626]
**V version:** 0.2
**OS:**  win10

**What did you do?**

struct Alma {}
k:=&Alma{}
println(typeof(k))

**What did you expect to see?**

&Alma
 
**What did you see instead?**

Alma

similar problem here :

i:=5
j:=&i

println(typeof(i))
println(typeof(j))

int
int  //here must be : &int

**Comment by jrpalma** [comment]
1. This problem stems from the C generator which uses the table module: https://github.com/vlang/v/blob/master/vlib/v/gen/cgen.v#L2762
2. However, the table module documentation states that a pointer resolves to just the symbol: https://github.com/vlang/v/blob/master/vlib/v/table/types.v#L28

The question is: Is this the correct behavior and should this be documented in the typeof function?

**Comment by SleepyRoy** [comment]
@medvednikov @spytheman what are your opinions on this?

**Comment by joe-conigliaro** [comment]
imo it would be good to show if it is a reference or not, it's easy to implement. But if its the job of typeof I'm not sure? I think perhaps the original purpose of typeof was to show the base type?

**Comment by Larpon** [comment]
Maybe add an `isref()` ?

**Comment by joe-conigliaro** [comment]
Yeah I think it should show the reference info personally

**Comment by Delta456** [comment]
Yes

**Comment by ntrel** [comment]
This is a clear bug, and it's fixed if you use `typeof(k).name`. There is recently a deprecation message for using typeof without `.name`.
