### ISSUE TITLE
vfmt import correction: old 'import()' style to 'import x' style

### ISSUE THREAD

**Issue by RiordanIX** [vlang/v#7656]
**V version:** V 0.2 ef6011b.4783503
**OS:** Fedora 31

**What did you do?**
`v fmt file.v`

**What did you expect to see?**
properly formatted file
 
**What did you see instead?**
```
file.v:3:8: error: `import()` has been deprecated, use `import x` instead
    1 | module sphere
    2 | 
    3 | import (
      |        ^
    4 |     math
    5 | )
```

This looks like something that should be handled by fmt instead of just throwing an error.

**Comment by joe-conigliaro** [comment]
It looks like the old import parsing code was removed from parser so now its not possible to parse the old style without adding it back

**Comment by serkonda7** [comment]
I will close this because the benefits are not worth readding legacy code.
