### ISSUE TITLE
v fmt: struct type declaration from 'x, y, z f64' not fixed

### ISSUE THREAD

**Issue by RiordanIX** [vlang/v#7657]
**V version:** V 0.2 ef6011b.32091dd
**OS:** Fedora 31

**What did you do?**
`v fmt sphere.v`

**What did you expect to see?**
A properly formatted file
 
**What did you see instead?**
```
sphere.v:6:3: error: expecting type declaration
    4 | 
    5 | pub struct Vector3 {
    6 |     x,y,z f64
      |      ^
    7 | }
    8 |
```
I think `v fmt` go ahead and change the file to:
```
pub struct Vector3 {
    x f64
    y f64
    z f64
}
```

**Comment by serkonda7** [comment]
This struct field declaration syntax was never allowed. _(see https://discord.com/channels/592103645835821068/700746775962714232/798531730818465813)_
So I don't see this as a correction, that should be done by fmt.
