### ISSUE TITLE
Appending an element to an array.

### ISSUE THREAD

**Issue by darxkies** [vlang/v#768]
On twitter there was a poll related to appending an element to an array. 54% were in favour of using a method called push to achieve that.

In the vlib code I saw that there is a public method called _push. Can that be renamed to push?

That would be overall a better fit than <<. Another advantage of the method call is that it would play nicely with autocompletion.

**Comment by medvednikov** [comment]
The results were close, I think they would be even close if there were only two options.

Anyway, I gave this a lot of thought and decided to leave `<<`.

First, it's already implemented and it works. Second, this is a very frequently used operation, and it is a bit more readable and clean:

```
users.push(User{
  name: 'Bob'
  age: 20
})

users << User{
  name: 'Bob'
  age: 20
}
```

**Comment by darxkies** [comment]
Have you considered using actually both? Let the user choose what to use?

**Comment by medvednikov** [comment]
That goes against one of V's main rules: only one way of doing things :)

**Comment by haselkern** [comment]
I don't think `<<` is an apt operator for appending to an array.

You introduced an extra operator just for appending to an array, which goes (from what I find) against the design philosophy of V.  While arrays are very cool and one of the fundamental data structures, I do not think that they deserve their own operator.

This also introduces inconsistencies. Why to I have to `<<` to push to an array, but `delete()` elements from it?

--------------------------------------

> The results were close, I think they would be even closer if there were only two options.

Sorry, but that is not true[¹](https://twitter.com/v_language/status/1141054110843715584):

![image](https://user-images.githubusercontent.com/7420740/61470824-f8b50900-a981-11e9-89f6-b110674c289e.png)

`push` has the absolute majority there, if you were to combine all other answers they wouldn't be as popular as `push`.

-------------------------------------

I have to admit that this was a bit of a rant, but I do think that `push` would be beneficial for V's future! I think V has enormous potential and want you to at least reconsider your decision.

**Comment by darxkies** [comment]
Thank you.
