### ISSUE TITLE
Add a `set_executable` function to the `os` module

### ISSUE THREAD

**Issue by pavi2410** [vlang/v#7691]
Sets executable permission bit for the file. No-op on Windows.

**Comment by dumblob** [comment]
>No-op on Windows.

Doesn't sound right to me. Making something executable means that a default "run" operation (e.g. double click triggered manually by the user) would execute it. If I double click anything on Windows which doesn't end with `.exe`, then it won't execute no matter what.

So if we want to have this function, it has to **ensure** executability in platform-specific way on all supported platforms if the given platform supports a "run" operation (e.g. bare metal doesn't).

**Comment by pavi2410** [comment]
I meant for it to complement [`os.is_executable`](https://modules.vlang.io/os.html#is_executable) function, which on Windows, checks if a file ends with `.exe`. Of course, we cannot simply append `.exe` to any arbitrary file. That's why I wrote "No-op on Windows."

**Comment by dumblob** [comment]
>Of course, we cannot simply append .exe to any arbitrary file. That's why I wrote "No-op on Windows."

In that case I'm against `set_executable()`, but I'm OK with `set_posix_exe_bit()`. On the other hand, why not try to append `.exe` - it could then really be named `set_executable()` as a complementary function to `is_executable()`.

**Comment by pavi2410** [comment]
`set_posix_exe_bit` function sounds good to me

**Comment by JalonSolov** [comment]
> 
> 
> > No-op on Windows.
> 
> Doesn't sound right to me. Making something executable means that a default "run" operation (e.g. double click triggered manually by the user) would execute it. If I double click anything on Windows which doesn't end with `.exe`, then it won't execute no matter what.

This is incorrect.  Windows has a way to associate file extensions with programs, such that double-clicking will "run" them.  Yes, the program you associate something with can run something... you could associate ".v" with "v run <file>" and ".go" with "go run <file>", etc.

**Comment by dumblob** [comment]
>This is incorrect. Windows has a way to associate file extensions with programs, such that double-clicking will "run" them. Yes, the program you associate something with can run something... you could associate ".v" with "v run " and ".go" with "go run ", etc.

Hm, I literally wrote and meant **default** "run" operation, not user-adjusted behavior in certain cases.

**Comment by spytheman** [comment]
.bat and .com files have default run operation associated
