### ISSUE TITLE
v run deletes target file even when it's not generated by compiler

### ISSUE THREAD

**Issue by ilmanzo** [vlang/v#7705]
**V version:** V 0.2.1 eef73ed
**OS:** linux, Ubuntu 20.10

**What did you do?**
```
$ echo "some important data" > hello
$ cat hello.v
fn main() {
	println('hello world')
}
$ v run hello.v 
hello world
$ cat hello
cat: hello: No such file or directory

```

**What did you expect to see?**
- compilation and run should happen in a separate, temporary folder 
- compilation should fail or at least warn if target file already exists and it's not an executable 

**What did you see instead?**
target file is overwritten and deleted

**Comment by Delta456** [comment]
You can use `v build` for having the executable. `v run` runs the program then deleting the executable.

**Comment by ilmanzo** [comment]
ok, I'm aware of `v build`,  but I think that `v run` should not delete my data without any warning...

**Comment by Delta456** [comment]
Its the generic behavior of any language which has that.

**Comment by ilmanzo** [comment]
Other languages'  `"run" `option does not overwrite existing files, because they compile and run in a separate temp/cache folder; for example in Go:

```
$ echo "my important data" > hello

$ cat hello.go
package main

import "fmt"

func main() {
    fmt.Println("Hello from Go");
}
 
 
$ go run hello.go
Hello from Go
andrea@box:test$ cat hello
my important data

```

or Crystal: 

```
$ echo "my important data" > hello
$ cat hello.cr
puts "Hello, World"
$ crystal run hello.cr
Hello, World
$ cat hello
my important data

```
it's a dangerous behavior to overwrite and delete user files without any warning.

**Comment by JalonSolov** [comment]
This has been discussed many times.  The current behavior of deleting the executable was put in place because people complained that V was leaving executables around after `v run`.

The reason it builds in the directory it does instead of temp space is due to how V code accesses assets, etc., so building in `tmp` would make the code fail.

**Comment by danieldaeschle** [comment]
as far that I know it builds it in tmp now, right? That means this can be fixed.
