### ISSUE TITLE
vfmt can not uncomment

### ISSUE THREAD

**Issue by kahsa** [vlang/v#7707]
**V version:0.2.1 eef73ed** 
**OS:archlinux** 

**What did you do?**
uncomment the line
```v
fn main() {
	/* a := 1 */
}
```

**What did you expect to see?**
```v
fn main() {
	a := 1
}
```
 
**What did you see instead?**
```v
fn main() {
	// /* a := 1 */
}
```

**Comment by JalonSolov** [comment]
I hope `vfmt` does NOT start removing comment markers.  That could be very, very bad.

It was incorrect of it to add the extra `//` in front of a perfectly good existing comment, though.  At best, it could have changed the line to just
```v
// a := 1
```
since it is only a single line.

**Comment by kahsa** [comment]
It is just as a minmal sample of this bug,
In the first place, vfmt formatted this way

```v
ui.column({},[
    tb1,
    tb2,
    tb3,
    bt4
])
```

to

`/* ui.column({},[ */ /* tb1, */ /* tb2, */ /* tb3, */ /* bt4 */ /* ]) */`

And while uncomment this, the posted 2nd bug happend.

I could not reproduce whole quickly then posted only 2nd part of problem.

**Comment by serkonda7** [comment]
As @JalonSolov  already said, vfmt should never uncomment or create comments on it's own.
Changing block to line comments is fine tho. (Btw, `/* */` were always removed when doing this.)

You reported your core problem aleady in another issue, so I'm going to close this.
