### ISSUE TITLE
sqlite: Execute multiple statements

### ISSUE THREAD

**Issue by fnetX** [vlang/v#7709]
**V version:** V 0.2.1 eef73ed
**OS:**  linux, Debian GNU/Linux 10 (buster)

**What did you do?**
run something like
```
import sqlite
fn main() {
	mut db := sqlite.connect(name+'.db') or {panic(err)}
	db.exec("CREATE TABLE users (id integer primary key, name text default '');INSERT INTO users (id,name) values (1,'Sam');")
}
```

**What did you expect to see?**
See a created table with one data row
 
**What did you see instead?**
Only the created table (sqlite exec only runs one query at a time). 

I'd like it to run the full provided query or find a reference in the docs on how to run multiple statements at once. Especially useful when using transactions etc ...

**Comment by blackshirt** [comment]
i think you can wrap the statements in transaction, i can insert multiple exec query.. see #8266

**Comment by fnetX** [comment]
The actual code uses a `BEGIN TRANSATION` and a `COMMIT` as far as I recall. The issue is that I want to execute all statements with a single call to `db.exec` because they are a string / file I want to import. 
I'm currently splitting the statements manually, but I'd prefer not to depend on workarounds.

**Comment by JalonSolov** [comment]
sqlite is supposed to accept multiple commands in a single line, separated by semi-colons.  All the examples I've seen also include a space after the semi-colon, which you don't have.  It may also not be possible to have both a create and an insert at the same time... it may be sqlite stops processing after the create.

In any case, V has no control over what is or is not accepted by individual databases.  That is something you will need to deal with yourself.  Perhaps in the future, V could have a higher level interface to sqlite that would give more functionality, or perhaps even a native V version of sqlite that would open more possibilities.  Until that time, this is not a bug in V, it is simply something to do with sqlite, which is out of V's control.
