### ISSUE TITLE
How to split code between files in an app?

### ISSUE THREAD

**Issue by matteoturini** [vlang/v#7711]
I didn't see this in the documentation, and when declaring a module, it tells me "project must include a `main` module or be a shared library (compile with `v -shared`)". How do I split code between files?

**Comment by fnetX** [comment]
What do you want to achieve? You want to develop your projects with multiple files or do you need to create different modules?

The first one: You can simply create multiple files in your directory and let them be in the same module (e.g. start each file with `module main`). Then you build or run your project with `v .` or `v run .` respectively.

**Comment by matteoturini** [comment]
Yes, but the VLang extension (vscode) complains about a main function.

**Comment by fnetX** [comment]
Structuring V is really interesting. I'm just struggling right now to split my apps code into folders. I wanted them all to be in the main module, but the code in a folder (which is for a part of the app) can't access the functions in the app's root. Defining it as a module makes other functions inaccessible. Quite tricky.

There's really a lack of documentation on how to properly layout V projects. Most languages (or build systems) do so.

**Comment by matteoturini** [comment]
V is a really cool language with a lot of potential but some documentation is lacking, and IDE support is very poor, although going in the right direction.

**Comment by JalonSolov** [comment]
V is still only 0.2.  It _barely_ has syntax highlighting for editor support.  A full IDE will have to wait until someone interested enough to work on one does so, or `vls` is completed enough that an existing IDE can use it.

Same with all the documentation, etc.  It is being improved, it just needs more work.

In other words, it is sill very early.  Give it time.

**Comment by fnetX** [comment]
Also note that syntax support is hard for a language which has no fixed syntax yet.

Back to your problem: What do you want to achieve? Is your issue only about vscode complaining (so compilation works as you expect) or do you still need help with splitting your code?

**Comment by matteoturini** [comment]
Both. I have no idea how it is recommended to split code. Apparently, VLS
fixed this issue, and now checks symbols in other files.

Em seg., 8 de fev. de 2021 às 08:28, fnetX (aka fralix) <
notifications@github.com> escreveu:

**Comment by matteoturini** [comment]
But I still don't know how to split my code.

Em sex., 12 de fev. de 2021 às 08:02, Matteo Leullier <
matteo.leullier@gmail.com> escreveu:

**Comment by JalonSolov** [comment]
Splitting your code is entirely up to you, which is why there is no recommendation on how to do this.

Some people like to create a single large file with everything in it.

Others prefer to create a separate file for each "functional block"... like all the file reading/writing stuff in one file, all the user stuff in another, etc.

Still others prefer to create entirely separate modules, whatever number of files are in them, so they can re-use code between projects.

There is no single "right way" to do this.  It depends on your use-case, as well your programming style, what you want to achieve, whether or not you'll want to use pieces of the code in other projects, and how (just copy it in, or put it in a module you import), etc., etc., etc.

**Comment by matteoturini** [comment]
Yeah I know the logic, but what about the technical part? How do I use the
functions from other files?

Em sex., 12 de fev. de 2021 às 14:14, JalonSolov <notifications@github.com>
escreveu:

**Comment by fnetX** [comment]
Using functions from other files is straightforward. Everything in one folder // one module is basically the same as if you have everything in a single file (except imports, they are only in the file that actually uses them).

So you can have foo.v
```
module example // optional, default is main
fn foo () { /// }
```

and call this from app.v
```
module example
fn main () {
    foo ()
}
```

If you also want to split parts of your app into different modules to reuse their code later or to write separate tests etc, just create different folders with different modules and import them
example/foo.v
```
module example
pub fn foo () { /// }
```
main.v
```
import example
fn main () {
    example.foo()
}
```

Hope I made no typos :-)

I suppose the question can be closed now? If you still have questions, you can always ask here (subscribers will receive updates) or in the discussions.

Have a nice day!

**Comment by fnetX** [comment]
Oh, I just noticed you wrote about the main module ... well, you compile your project from within the main module (which is the default so you should be able to omit it). Everything is pulled into it, but obviously you cannot name your main app module `something`.

Which is, by the way, not explicitly stated in the docs as far as I could see!

**Comment by fnetX** [comment]
@matteoturini does this answer your question? Can this be closed?

**Comment by matteoturini** [comment]
Yes.

Em sáb., 13 de mar. de 2021 09:17, fnetX (aka fralix) <
***@***.***> escreveu:
