### ISSUE TITLE
pointer and mut

### ISSUE THREAD

**Issue by k1attila12** [vlang/v#7718]
**V version:** 02.
**OS:** win10

**What did you do?**
```v
j:=1111
mut i := &int(&j)
unsafe {
*i =2222
}
println(i)
println(typeof(i))
println(j)
println(typeof(j))
```

**What did you expect to see?**

i can't modify j, because it is immutable

 
**What did you see instead?**

in this small example i can modify j even it is immutable.
if i change this line :
```v
mut i := &int(&j)
```
to
```v
mut i := &j
```

compiler can't compile it (very correctly) because of "j is immutable"

**Comment by danieldaeschle** [comment]
please use markdown formatting for your code in future. It helps us alot.

**Comment by danieldaeschle** [comment]
good find anyway.

**Comment by k1attila12** [comment]
OK. and

j:=1111               

mut i := &string(&j)

this is possible too  : j int       and        i &string(&j)

**Comment by danieldaeschle** [comment]
code formatting!

**Comment by joe-conigliaro** [comment]
I tested a fix for this it seems to work well.. but there is a bit of code in vlib that needs updating so I will push it after I do that

**Comment by shadowninja55** [comment]
this is now only allowed in unsafe blocks.
