### ISSUE TITLE
Weird behaviour returning and appending to an int array recursively

### ISSUE THREAD

**Issue by ChrisYeomans** [vlang/v#773]
**V version:** 0.1.8 
**OS:** Linux Mint

**What did you do?**
I wrote the following recursive function to get a list collatz numbers:
```v
fn get_collatz_list_rec(n int) mut []int {
	mut m := n
	if m == 1 {
		out := [1]
		return out
	} else if m%2 == 1 {
		return get_collatz_list_rec(3*m + 1) << m 
	} else {
		return get_collatz_list_rec(m/2) << m 
	}
}
```

**What did you expect to see?**
I should have ran and not given a compiler error
 
**What did you see instead?**
It gave the following compiler error:
```
pass=2 fn=`get_collatz_list_rec`
panic: collatz.v:16
expected type `[]int`, but got `void`
```

**Comment by medvednikov** [comment]
remove `mut` from fn declaration:

`fn get_collatz_list_rec(n int) []int {`

**Comment by medvednikov** [comment]
also

`arr << val`` appends an item to an array, but doesn't return it.

```
mut res := get_collatz_list_rec(3*m + 1)
res << m
return res
```

Making it an expression might be a good idea.

**Comment by medvednikov** [comment]
Yeah definitely, `get_collatz_list_rec(3*m + 1) << m ` should work as an expression, will fix :)

**Comment by Ivo-Balbaert** [comment]
This version works:

fn get_collatz_list_rec(n int) []int {
	m := n
	mut res := []int
	if m == 1 {
		out := [1]
		return out
	} else if m%2 == 1 {
		res = get_collatz_list_rec(3*m + 1)
	} else {
		res = get_collatz_list_rec(m/2)
	}
	res << m
	return res
}

println(get_collatz_list_rec(10)) // [1, 2, 4, 8, 16, 5, 10]

**Comment by medvednikov** [comment]
To keep things simple, `<<` is going to stay the same, like `void push_back()` in C++ and `fn push()` in Rust.
