### ISSUE TITLE
Cant compile on windows, panic: array.v:228

### ISSUE THREAD

**Issue by 0x9ef** [vlang/v#774]
**V version** 0.1.8
**OS: Windows** 8.1

**What did you do?**
Trying to compile 
`fn main() {
	areas := ['game', 'web', 'tools', 'science', 'systems',
	          'embedded', 'GUI', 'mobile'] 
	for area in areas {
		println('Hello, $area developers!')
	}
}` under windows 8.1

**What did you expect to see?**
Hello game developers!
Hello web developers!
etc...
 
**What did you see instead?**
Looks like you are running V for the first time.
Setting VROOT to "E:\vscode-vlang\v".
(char code=0) pos=4717 len=4942
panic: array.v:226
invalid character ``

**Comment by changrui** [comment]
But I can not compiler v.exe itself, I got an error :  v.c: In function 'os__getexepath':
v.c:3601:22: error: invalid type argument of unary '*' (have 'DWORD {aka long unsigned int}')
   return tos(result, *GetModuleFileName(0, result, os__MAX_PATH));

**Comment by SleepyRoy** [comment]
@changrui 
I got the same result.

**Comment by aguspiza** [comment]
Sorry my fault, #776 will fix it but after that v.c nees to be updated

**Comment by ntrel** [comment]
Apparently the panic might be due to Windows line endings in source files.

**Comment by medvednikov** [comment]
Fixed.
