### ISSUE TITLE
Happy new year V-ers!

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#7741]
Many people say 2020 is special and unbelievable, in terms of covid, unemployment, recession, stay-at-home, etc. But to V-ers the group, also the birth of V2.
Wish V and everyone a good 2021 : )

**Comment by medvednikov** [comment]
Happy new year!

**Comment by Delta456** [comment]
Happy New Year!

**Comment by joe-conigliaro** [comment]
🎆  Happy new year! 🎆

**Comment by Larpon** [comment]
Happy new year! 🥳

**Comment by penguindark** [comment]
Happy new year :rocket:

**Comment by helto4real** [comment]
Happy new year :)

**Comment by ckqee** [comment]
Happy New Year!
