### ISSUE TITLE
make compilation for pelles c possible

### ISSUE THREAD

**Issue by r-k-o** [vlang/v#7746]
hi,

please enable pelles c  "http://www.smorgasbordet.com/pellesc/". it is small complete and doesn't need the huge VS of microsoft.

thanks

**Comment by JalonSolov** [comment]
According to the web site, it supports C99 spec, so it should work fine with V.  Have you tried it?

**Comment by r-k-o** [comment]
no, haven't tried it yet. but it would be nice if it would be integrated just as tcc and would be move to the make process.

**Comment by JalonSolov** [comment]
PRs are always welcome, if you can make V work with Pelles C.
