### ISSUE TITLE
add support for android

### ISSUE THREAD

**Issue by l1t1** [vlang/v#775]
i can compile the compilerin termux, but it didnt work
$ gcc -w v.c -o v
$ gcc -v
clang version 8.0.0 (tags/RELEASE_800/final)
Target: aarch64-unknown-linux-android
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
$ ./v
V 0.1.8
Use Ctrl-D to exit
For now you have to use println() to print values, this will be fixed soon

>>> println('a')
Looks like you are running V for the first time.
V repo not found. Cloning...
failed to clone github.com/vlang/v
$ ls
v.bin  v.c
$ ls -l
total 616
-rwx------    1 u0_a131  u0_a131     305664 Jun 29 05:42 v.bin
-rw-------    1 u0_a131  u0_a131     320863 Jun 29 05:40 v.c

**Comment by l1t1** [comment]
panic: array.v:78
dereferencing requires a pointer, but got `int`
make: *** [Makefile:5: v] Error 1
$ cc
clang-8: error: no input files
$ cc -w -o v v.c
$ ./v -o v .
name="a", t=array*
pass=2 fn=`insert`

=========================
It looks like you are building V. It is being frequently updated every day.
If you didn't modify the compiler's code, most likely there was a change that
lead to this error.

Run `git pull && make`, that will most likely fix it.

If this doesn't help, please create a GitHub issue.
=========================

panic: array.v:78
dereferencing requires

**Comment by l1t1** [comment]
I RUN
git pull && make
same result

**Comment by changrui** [comment]
git clone https://github.com/vlang/v first, then 'make', git pull for update v sources.

**Comment by AtjonTV** [comment]
I tested with V 0.1.2 and 0.1.8 on my Huawei Nova, and it works fine!

```
Make: HUAWEI
Model: Nova (CAN-L01)
CPU: Snapdragon 625 (ARM Cortex-A53)
Linux: 3.18.31 (armv8l)
Android: 7.0 (API 21)
Termux: 0.72.72
GCC: 8.0.0
```

How did I get V 0.1.2?

```
$ git clone https://github.com/vlang/v
$ cd v/Compiler
$ make
```

How did I update from 0.1.2 to 0.1.8?

```
$ cd v/compiler
$ make clean
$ git pull
$ make
```

**Comment by l1t1** [comment]
thanks  it works  on my phone now
cd ..
$ git pull
Already up to date.
$ ls
CHANGELOG.md         azure-pipelines.yml
CONDUCT.md           compiler
CodeStructure.md     examples
LICENSE              thirdparty
Makefile             vlib
README.md
$ make
rm -f v.c v vprod
curl -Os https://raw.githubusercontent.com/vlang/vc/master/v.c
cc -std=gnu11 -w -o v v.c
./v -o v compiler
rm v.c
V has been successfully built
$ ls
CHANGELOG.md         azure-pipelines.yml
CONDUCT.md           compiler
CodeStructure.md     examples
LICENSE              thirdparty
Makefile             v
README.md            vlib
$ ./v
V 0.1.10
Use Ctrl-D or `exit` to exit
For now you have to use println() to print values, this will be fixed soon

>>> println(123)
123

**Comment by l1t1** [comment]
it need to run make at v, not v/compiler on my phone

**Comment by AtjonTV** [comment]
Thats because the folder structure just changed in V 0.1.9 :D

**Comment by l1t1** [comment]
can run v run hello_world.v but failed to cpmplietetris.c 

../../v tetris.v
/data/data/com.termux/files/home//.vlang//tetris.c:76:10: fatal error: 'ft2build.h' file not found
#include "ft2build.h"
         ^~~~~~~~~~~~
1 error generated.
V panic: clang error
$ cd ..
$ ls
VCasino          log.v
game_of_life     news_fetcher.v
hello_world.v    tetris
json.v           word_counter
links_scraper.v
$ ../v run hello_world.v
============ running hello_world ============
Hello, World!

**Comment by l1t1** [comment]
compile hello_work.v  and run it is ok too

$ ../v hello_world.v
$ ls
VCasino          links_scraper.v
game_of_life     log.v
hello_world      news_fetcher.v
hello_world.v    tetris
json.v           word_counter
$ ./hello_world
Hello, World!

**Comment by AtjonTV** [comment]
For Tetris you will need `libfreetypeX-dev`.

Just search for `libfreetype` with `pkg` or `apt`, install it and try again :smile:

**Comment by l1t1** [comment]
make test fail and a typo of couldnt
pwd
/data/data/com.termux/files/home/v/v/examples
$ cd ..
$ make test
curl -Os https://raw.githubusercontent.com/vlang/vc/master/v.c
cc -std=gnu11 -w -o v v.c
./v -o v compiler
rm v.c
./v -prod -o vprod compiler # Test prod build
echo "Running V tests..."
Running V tests...
find . -name '*_test.v' -print0 | xargs -0 -n1 ./v
coudlnt create file "/var/tmp/fmt.v"
xargs: './v' terminated by signal 11
make: *** [Makefile:15: test] Error 125

**Comment by Delta456** [comment]
This can be closed now.

**Comment by medvednikov** [comment]
Fixed today.
