### ISSUE TITLE
V rune literal generates multi-byte C char literal

### ISSUE THREAD

**Issue by ntrel** [vlang/v#7758]
**V version:** recent git
**OS:** Windows 8

**What did you do?**
```v
r := `🌎`
println(r)
println('🌎')
```

**What did you expect to see?**
```
🌎
🌎
```
 
**What did you see instead?**
```
▒
🌎
```
This is with `gcc`, which generates a warning. With `clang` I think it causes a compile error.
V generates a C char literal `'🌎'`. `sizeof(char)` is 1 on my machine with `gcc`.

**Comment by clubby789** [comment]
The problem seems to be in
```v
pub fn utf32_to_str_no_malloc(code u32, buf voidptr) string {
    icode := int(code) // Prevents doing casts everywhere
    mut res := ''
    unsafe {
        mut buffer := byteptr(buf)
        if icode <= 127 { /* 0x7F */
            buffer[0] = byte(icode)
            res = tos(buffer, 1)
        }
```
Before the cast, the code is `4294967182` - afterwards it is `-114`. This makes it hit the `if icode <= 127` block, which prints a single byte.

**Comment by clubby789** [comment]
Haven't been able to track down where it's emitted, but the generated code for ```r :=`🌍` ```  is `mov    eax, 0xffffff8e` which is definitely not right.

**Comment by clubby789** [comment]
Turns out I was way overthinking this, C compilers can do the work for me 🙂

**Comment by ntrel** [comment]
Thanks @clubby789.

I see that the Windows tests passed, but for some reason it fails on my Windows setup with MSYS:
```
$ ./v.exe vlib/builtin/utf8_test.v
1

vlib/builtin/utf8_test.v:12: failed assert in function test_utf8_wide_char
Source  : `'${val[0]:x}${val[1]:x}${val[2]:x}${val[3]:x}' == 'f09f8c8e'`
         left value: edbc8e0
        right value: f09f8c8e
```

**Comment by ntrel** [comment]
I can confirm that this fixes printing a 3-byte Utf-8 character: `println(`€`)`
