### ISSUE TITLE
possibility to use dll's written in another language

### ISSUE THREAD

**Issue by r-k-o** [vlang/v#7762]
Please add the possibility to use dll's written in f.ex. in fortran that have a lib, but no c header.
thanks

**Comment by JalonSolov** [comment]
As long as it has a C-compatible interface, it should work.  You just have to write your own header equivalents, and you can do that in V.

**Comment by r-k-o** [comment]
After trying all possible combination from the DOCs, - it does have the wright path, the lib is correctly in the compiler call, but it will not link the lib.

The dir F:\v\makelib contains:
screens.dll, screens.lib

the test file is:
fn C.OpenWindow_(WindowID i64, x i64, y i64, InnerWidth i64, InnerHeight i64, Title string, Flags i64, ParentWindowID i64) int

fn openwindow(WindowID int, x int, y int, InnerWidth int, InnerHeight int, Title string, Flags int, ParentWindowID int) int {
  return C.OpenWindow_(WindowID, x, y, InnerWidth, InnerHeight, Title.str, Flags, ParentWindowID)
}

fn main() {
	mut reti := i64(0)
	ttt := "PureBasic Window"
	mut quit := int(0)
	reti = openwindow(0, 100, 200, 495, 460, ttt, window_systemmenu | window_minimizegadget |	window_maximizegadget, 0)
}


it gives the following error:

cl -w /we4013 /volatile:ms /Fo"Y:\TMP\v\scr.15428971508405367826.tmp.c.obj" /MDd /D_DEBUG /Zi /Fd"Y:\TMP\v\scr.15428971508405367826.tmp.c.pdb" "Y:\TMP\v\scr.15428971508405367826.tmp.c" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt" -I "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared" kernel32.lib user32.lib advapi32.lib dbghelp.lib screens.lib /link /NOLOGO /OUT:"F:\v\makelib\scr.exe" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\ucrt\X64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\X64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\lib\X64" /DEBUG:FULL /LIBPATH:"F:\v\makelib" /LIBPATH:"F:\v\makelib\msvc"

scr.15428971508405367826.tmp.c
Y:\TMP\v\scr.15428971508405367826.tmp.c(8733): error C4013: "OpenWindow_" undefiniert; Annahme: extern mit Rückgabetyp int

builder error:
==================
C error. This should never happen.

**Comment by JalonSolov** [comment]
Using 3 backticks around code and output makes it easier to read.  I've added the backticks on your comment.  Edit to see what I changed.

German, I see.  It says that `OpenWindow_` is undefined.  To fix that, you probably need to tell the C compiler where the files are, using `#flag` directives, documented here:  https://github.com/vlang/v/blob/master/doc/docs.md#flag

**Comment by r-k-o** [comment]
ok, thanx and yup german.

#flag windows -L@VROOT/makelib
#flag windows -lscreens

is at the top of the file and the result shows (compiler):

F:\v\makelib>..\v scr.v
==================
Microsoft (R) C/C++-Optimierungscompiler Version 19.28.29335 für x64
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

cl -w /we4013 /volatile:ms /Fo"Y:\TMP\v\scr.1039820538788463948.tmp.c.obj" /MDd /D_DEBUG "Y:\TMP\v\scr.1039820538788463948.tmp.c" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt" -I "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared" kernel32.lib user32.lib advapi32.lib dbghelp.lib screens.lib /link /NOLOGO /OUT:"F:\v\makelib\scr.exe" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\ucrt\X64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\X64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\lib\X64" /DEBUG:FULL /LIBPATH:"F:\v\makelib" /LIBPATH:"F:\v\makelib\msvc"

**Comment by JalonSolov** [comment]
Hmm... `F:\v\makelib\msvc` at the end implies it wants to find the files in a `msvc` subdir under `makelib`.  Not sure, though.

I haven't used msvc in years, so we are already passing the boundaries of my knowledge.  :-\  Perhaps someone else with more recent msvc knowledge can help further.

If you want to try with gcc, you can download the latest version from winlibs.com.

**Comment by r-k-o** [comment]
Thanks for your analysis.
I'd rather use Pelles C. It works and it is a small compiler, that is used by many people to avoid msvc.

**Comment by JalonSolov** [comment]
PRs are always welcome, if you can make V work with Pelles C.
