### ISSUE TITLE
Cannot cast byteptr to &byte

### ISSUE THREAD

**Issue by ntrel** [vlang/v#7777]
**V version:** 
**OS:** 

**What did you do?**
```v
_ = &byte(''.str)
_ = &byte(byteptr(0))
```

**What did you expect to see?**
Successful compilation.
 
**What did you see instead?**
```
byteptr.v:1:6: error: cannot cast type `byteptr` to `byte`
```

**Comment by Delta456** [comment]
@ntrel I get 
```
>>> &byte(byteptr(0))
/tmp/v/.noprefix.vrepl_temp.8424372375959642661.tmp.c:12830: at main__main: RUNTIME ERROR: invalid memory access
/tmp/v/.noprefix.vrepl_temp.8424372375959642661.tmp.c:12957: by main

**Comment by ntrel** [comment]
> if to_type_sym.kind == .byte 

This looks like the problem. I want to cast to the type `&byte`, yet the diff you posted treats it the same as casting to just byte.

Ignoring V pointers and only testing the TypeSymbol is a widespread problem in the compiler, but I'm pretty sure this issue used to work a few months ago.

**Comment by Delta456** [comment]
What was the expected output?

**Comment by ntrel** [comment]
@Delta456 A byteptr is technically the same as a `&byte`, and is identical in generated C. 
```v
fn f(bp byteptr) {
    p := &byte(bp)
    assert bp == p
}
```
I don't know why byteptr exists, but as long as it does it doesn't make sense not to allow conversions between the two.

**Comment by Delta456** [comment]
@medvednikov What do you think?

**Comment by medvednikov** [comment]
It should probably simply be removed.

**Comment by ntrel** [comment]
Sounds good. And charptr?

**Comment by Delta456** [comment]
Closing this issue as `charptr` and `byteptr` have been deprecated and `&char` and `&byte` should be used instead.
