### ISSUE TITLE
error 'unknown field' when compiling a program with embedded structures

### ISSUE THREAD

**Issue by Mintormo** [vlang/v#7787]
**V version:**
0.2.1 24b18f0

**OS:** 
Microsoft Windows 7 Professional v7601 64-bit

**C++ compiler with which V is built**
MSVC 2019 16.8.3
C++ compiler version: 19.28.29335 amd64

**What did you do?**
1. Updated the V compiler with the commands
`git pull origin master`
`make.bat -msvc`

2. Assembled the [program](https://pastebin.com/WC3C6XcW) using the commands
`v -cg -cc msvc s.v`

**What did you expect to see?**
1. Program assembled successfully
 
**What did you see instead?**
1. The V compiler aborted the process with an error 'unknown field `a` in struct literal of type `Du`'

![struct_error](https://user-images.githubusercontent.com/2286710/103442315-1a817900-4c66-11eb-8cee-c35ea9490a7e.png)

**Comment by danieldaeschle** [comment]
you have no example but i think this should work since some commits :)
