### ISSUE TITLE
@css directive in tmpl.v is not working

### ISSUE THREAD

**Issue by enghitalo** [vlang/v#7788]
**V version: 2.1 ** 
**OS:Windows 10** 

**What did you do?**
@css 'frontend/styles.css'

**What did you expect to see?**
html stylezed
 
**What did you see instead?**
html without style

**Possible ugly solution**

`<link rel="stylesheet" href="frontend/styles.css">` is not working
but `<style>example {background-color: grey;}</style>` is working

so we can change in https://github.com/vlang/v/blob/master/vlib/vweb/tmpl/tmpl.v

> if line.contains('@css ') {
> 			pos := line.index('@css') or { continue }
> 			s.write('<link href="')
> 			s.write(line[pos + 6..line.len - 1])
> 			s.writeln('" rel="stylesheet" type="text/css">')

to something like:

> if line.contains('@css ') {
>                         mut csss :=os.read_file(line[pos + 6..line.len - 1]) or {err}
> 			pos := line.index('@css') or { continue }
> 			s.write('<style>')
> 			s.write(csss)
> 			s.writeln('</style>')

**Comment by Dialga** [comment]
Possibly related to #7370.

**Comment by LouisSchmieder** [comment]
do you handle the file static with `handle_static`?

**Comment by enghitalo** [comment]
> do you handle the file static with `handle_static`?

Hmmm. I get it.

I was following the vweb example. Now I understand it.
I PR #8090 to be more clear

**Comment by Dialga** [comment]
You can close this if it's fixed.
