### ISSUE TITLE
Abbreviated keywords

### ISSUE THREAD

**Issue by mindplay-dk** [vlang/v#78]
I know you shouldn’t quibble too much about syntax (everyone has different opinions) but I find that abbreviated keywords are a bit harmful to the overall readability of the language.

A “mut” is a dog.

I can’t even pronounce “fn”. fun? fnuh? The word “function” actually registers as a word to the human eye, whereas the letters “fn” register as, nothing, really. Looks more like a bad choice of variable name than a keyword.

I wonder why these abbreviations have become popular? Faster to type? An editor could easily expand “fn” to “function” automatically.

You probably made these choices mostly out of personal preference, and it’s your language, so I won’t argue any more on the subject, I just find this doesn’t help readability at all.

Either way, I really like where this language is going :-)

If you don’t know Skew, you might want to take a look at that also - you seem to have many of the same ideas about the syntax and features of the language itself, might find some inspiration there :-)

Really looking forward to the first release!

**Comment by medvednikov** [comment]
Hej

It's a thing of preference. Personally I don't think `fn` is confusing, especially in a language that has like a dozen keywords. 

We use abbreviations in different fields all the time: `f(x) = √x`. Rust has `fn` and `mut`, Go has `func`, Python has `def` etc. So I don't think many developers find abbreviations confusing. This just has to be balanced (looking at you, Perl).

> An editor could easily expand “fn” to “function” automatically.

V is a minimalistic 400 KB language that should be easy to use without an editor.

> Either way, I really like where this language is going :-)
> Really looking forward to the first release!

Thanks!

**Comment by mindplay-dk** [comment]
Note that I never said "confusing", I said "harmful to readability".

"func" and "def" at least are sounds you can pronounce... not that "funk" and "deaf" make much sense in the context of programming ;-)

Anyhow, your language, your call :-)

**Comment by medvednikov** [comment]
I actually put it to vote:

https://twitter.com/vlang_io/status/1099687714042114049

Not very large sample, but still :)

**Comment by mindplay-dk** [comment]
Huh. It seems the fashion is to just abbreviate more and more.

I wonder if you had offered an option `f()`, would most people prefer that? ;-)

As someone [pointed out](https://twitter.com/jadbox/status/1099699320515751937), you might even consider having no keyword for functions at all.

This may seem controversial of me, but I'm actually *more* comfortable with *no* keywords than I am with abbreviated keywords. For example, I am quite comfortable with Javascript's `() => {}` and `class { foo() {}; }` and so on.

What I find distracting is just keywords that aren't *words*.

Anyhow, you don't need to humor me and keep debating this, I'm sure you have more important things :-)

**Comment by ntrel** [comment]
When Rust first adopted `fn` I thought it looked ugly. After a while I got used to it and prefer it to no keyword in C or Go `func`. As it's short, I would even like it in lambdas: `fn a1,a2 => expr`. Keywords make code easier to read (with syntax highlighting), particularly in a complicated expression.

**Comment by ntrel** [comment]
Same with `println` or `writeln`, looks weird at first, but it's very common so you get used to it. The ln gets pronounced lin, fn gets pronounced fun. Flickr gets pronounced flicker.

**Comment by mindplay-dk** [comment]
> As it's short, I would even like it in lambdas

In deeply nested lambdas, I find a keyword makes it less readable - the `->` makes a fine visual cue, I read it out as "becomes", which makes complex nested lambdas quite easy to read out loud.

This was just proposed as alternative closure syntax for PHP, and a whole of bunch of people are quite unhappy with this syntax - it seems unnecessarily noisy compared with JS closure syntax.

Closures are typically *short*, and often many are used in succession or in nested constructions - so, to me, this tends to be more about being succint and creating as little unnecessary noise as possible.

> I think interface functions should start with fn too

Agree, consistency is a must here - though, for me, this is mostly a concern because it makes it easier to refactor between classes and interfaces. (Refactoring and diffing is something I think is critical and often somewhat overlooked in language syntax design... things like allowing extra trailing commas in array literals and function-calls is something that only more recently made its way into mainstream languages.)

**Comment by mindplay-dk** [comment]
[Skew](http://skew-lang.org/) allows you to pick syntax:

```
# all equivalent:
var zero2 = () => 0
var zero3 = () int => 0
var zero4 = () int => { return 0 }

# both equivalent:
var add1 = (x int, y int) => x + y
var add2 fn(int, int) int = (x, y) => x + y
```

Rationale from the manual:

> Lambda types are specified using the "fn" keyword. The syntax is similar to the syntax for defining a function except argument names are not included (only argument types) and parentheses are required.

So this should resonate with you.

However:

> **Since packaging up and manipulating little bits of code is so convenient, there are several shortcuts for creating more concise lambda expressions.** The argument and/or return types can be omitted when they can be inferred from context.

I think these are really good points and even complex Skew code reads just beautifully.

I'm generally all for *one* clean syntax - but willing to make exemptions to better fit different use-cases: methods, stand-alone functions and inline lambdas serve very different purposes, and inline lambdas is where I prefer to have as little noise as possible.
