### ISSUE TITLE
BOM header s not been treated correctly

### ISSUE THREAD

**Issue by retsyo** [vlang/v#781]
on windows, some editor will save a utf8 encoded file with BOM header, which is actually 3 characters 0xefbbbf at the very beginning of file

but it seems that V can't read this kind of file correctly
```
(char code=239) pos=0 len=142
panic: a.v:1
invalid character `▒`
```

**Comment by retsyo** [comment]
btw, gcc can treat it without problem

**Comment by medvednikov** [comment]
Fixed.
