### ISSUE TITLE
Imported Module deceleration order (gg module import is broken)

### ISSUE THREAD

**Issue by Yarila682** [vlang/v#782]
**V version:** 0.1.8
**OS:** Linux Mint 18.2

**What did you do?**
```Go

module main

import gg
fn main(){

}
```

**What did you expect to see?** 

Normal compilation process without errors

 
**What did you see instead?** 

/home/yarila//.vlang//import_gg.c:173:12: error: field ‘shader’ has incomplete type
 gl__Shader shader;
            ^
V panic: clang error

****
import_gg.c file has struct named "gl__Shader". But it is placed after declaration of "gg__GG' struct. So if I change the order of declarations everything compiles normally.

**Comment by Viza74** [comment]
It's not just the gg module, but seems to be a problem with import ordering generally.

I got a breakout.v with:
```
module main

import sphys
import vec2
...
```

sphys.v imports and uses vec2:
```
module sphys

import vec2

struct CollisionResponse {
	pub mut:
	collided bool
	penetration vec2.Vec2
	normal   vec2.Vec2
}
...
```
 but if I try to compile this, I got a bunch of errors like this:
```
.breakout.c:138:12: error: field has incomplete type 'vec2__Vec2' (aka 'struct vec2__Vec2')
vec2__Vec2 penetration;
```
Checking out .breakout.c, the declaration ordering is wrong:
```
struct sphys__CollisionResponse {
bool collided;
vec2__Vec2 penetration;
vec2__Vec2 normal;
}; 
struct vec2__Vec2 {
f32 x;
f32 y;
}; 
```
If I switch around the import order in breakout.v, it compiles without problem:
```
module main

import vec2
import sphys
```
but it definitely should compile without this ordering too

**Comment by medvednikov** [comment]
Hi

This was broken recently with the introduction of submodules. Will be fixed asap.

**Comment by joe-conigliaro** [comment]
I'll take a look at this real soon

**Comment by joe-conigliaro** [comment]
I'm trying to work out a solution to this issue

**Comment by joe-conigliaro** [comment]
This should hopefully fix the issue: https://github.com/vlang/v/pull/1232
