### ISSUE TITLE
(Porting) Teach V about a new platform (os/arch)

### ISSUE THREAD

**Issue by IngwiePhoenix** [vlang/v#7822]
I would love to use V for my PlayStation Vita homebrew stuff - but, in order to have it recognize it as a platform - OS and architecture - I'd have to tell V what it is running under.

I could do without it, sure, but I'd love to be able to take advantage of the `_$os.v` naming scheme in my project to possibly use the same kind of application across multiple platforms by just splitting similiar functions into their OS-dependant files/folders.

What would I have to modify?
OS should be `vita` and arch should be `arm-vita` (because the chipset and instruction set support a few additional features that aren't quite as available in the default ARM set). The toolchain (VitaSDK) outputs this on the prepared GCC:
```
$ /usr/local/vitasdk-1/bin/arm-vita-eabi-gcc --version
arm-vita-eabi-gcc (GNU Tools for ARM Embedded Processors) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
(this build is, in fact, very outdated. Turns out I forgot to upgrade my toolchain on this laptop...whoops?)

**Comment by medvednikov** [comment]
Adding support for new archs is very easy. Literally a couple of lines.

Check out how it was done for Haiku and Serenity for example.
