### ISSUE TITLE
Cross compilation not work

### ISSUE THREAD

**Issue by jesse996** [vlang/v#784]
**V version:** 
0.18

**OS:** 
manjrao

**What did you do?**

 ' v -os windows a.v '

**What did you expect to see?**
'a.exe'
 
**What did you see instead?**
 'a'

**Comment by jesse996** [comment]
'a.v' is just a simple HELLOWORLD

**Comment by aguspiza** [comment]
PR #858 Should fix cross compilation from linux

**Comment by jesse996** [comment]
close

**Comment by medvednikov** [comment]
It works for you now?
