### ISSUE TITLE
Rename "string" to "str" or vice versa

### ISSUE THREAD

**Issue by olegmisar** [vlang/v#785]
There is a `string` type and an `str` method on an array struct(and in future on user-defined structs). I think it would be better to rename either of them to be more consistent. I lean towards `str` because it is shorter(like `int` is shortened from `integer`). 

Example:
```v
fn concat(a, b str) str {
    return a + b
}
```

**Comment by ntrel** [comment]
Given that string is actually a struct with accessible fields, I think it should be capitalized.

**Comment by medvednikov** [comment]
One of V's goals is to make the transition from C/C++ and Go simple. Go has `string` and C++ has `std::string`.

**Comment by ntrel** [comment]
C++ uses lowercase for struct names e.g. std::vector, V uses capitalised struct names. This is inconsistent.
