### ISSUE TITLE
"for" expressions

### ISSUE THREAD

**Issue by olegmisar** [vlang/v#787]
The original idea of `for` expressions comes from here: https://github.com/vlang/v/issues/283#issuecomment-506862823

There are already `if` expressions and it would be great to have `for` expressions (instead of `filter` and `map`) as well.

## Syntax

```v
result := for item in array { /* body */ }
```

The last expression of the body of the `for` expression is evaluated and appended to the resulting array.

## `for` expressions as `array.map`

`for` expressions are primarily used to transform an array. 

The following code doubles all numbers.

```v
numbers := [1, 2, 3, 4, 5, 6]
result := for num in numbers {
    num * 2
}
// result == [1, 4, 9, 16, 25, 36]
```

## `for` expressions as `array.filter`

The last `if` block inside the `for` expression becomes an expression too.

The following code filters out all odd numbers.

```v
numbers := [1, 2, 3, 4, 5, 6]
result := for num in numbers {
    if (num ℅ 2 == 0) {
        num
    }
}
// result == [2, 4, 6]
```
## `for` expressions as `array.map` with `array.filter`

It is possible to transform an array item in an `if` expression. 

The following code doubles all even numbers and triples all odd numbers.

```v
numbers := [1, 2, 3, 4, 5, 6]
result := for num in numbers {
    if (num ℅ 2 == 0) {
        num * 2
    } else {
        num * 3
    }
}
// result == [1, 2, 9, 8, 15, 12]
```

## Behavior of `continue` and `break`

`continue` could be used to skip an iteration and/or to produce a value early.

`break` does the same thing as `continue` but immediately leaves a `for` loop.

**Comment by retsyo** [comment]
this is what python does
```python
numbers = [1, 2, 3, 4, 5, 6]
result = [num*2 for num in numbers]
```

on the other hand
```
result := for num in numbers {
 num*2 
}
```
looks so weird because 
```
for num in numbers {
 num*2 
}
```
only produces one result. What is the reason
```
result := for num in numbers {
 num*2 
}
```
should be an array?

**Comment by retsyo** [comment]
for me, it is more reasonable
```
result := for num in numbers {
  num*2
}

//result = 12
```

**Comment by olegmisar** [comment]
You are probably right. A `for` could return only the last value.
```v
numbers = [1, 2, 3, 4, 5, 6]
result := for num in numbers {
  num*2
}

//result == 12
```

Or with a `break`.
```v
numbers = [1, 2, 3, 4, 5, 6]
result := for num in numbers {
  num*2
  break
  // or 
  break num*2
}

//result == 2
```

But how useful could it be if it produces only one value? It'd be possible only to search a value.

On the other hand, if `for` expression returns an array, the application area will expand to mapping, filtering, or both simultaneously.

By the way, python's `num*2 for num in numbers` without square brackets produces a generator, which is more similar to `for` expressions proposed by me, than by you.

**Comment by ntrel** [comment]
This is essentially just python list comprehensions, and has all the same downsides.

* It allocates a new array and eagerly evaluates the result elements. Map and filter can return iterators that calculate the next element as requested.
* It only works for arrays.
* It is inflexible. With functional style we use different specialised functions (and lambdas). For example, what if you want more than one element added to the output on encountering a certain input element? This can be efficiently handled with a container.each(fn if \elem == 2 {out.append(4, 6)}).

**Comment by olegmisar** [comment]
Yeah, you are right. `for` expressions (if they are included in the language) should produce only the last value. 

But since there is neither `null` nor `undefined` in V default value **must** be set. It could be an `else` clause. In this case, `break` is mandatory.
```v
numbers = [1, 2, 3, 4, 5, 6]
result := for num in numbers {
  if num == 6 {
    // yields 6
    break num
  }
} else {
  0 // this is default value
}
// result == 6

// If no number satisfies the 
// condition use the default value

numbers = [1, 2, 3, 4, 5, 6]
result := for num in numbers {
  // there isn't a number which satisfies this condition 
  if num == 7 {
    // so this code is never evaluated
    break num
  }
} else {
  And the default value is used
  0 // this is default value
}
// result == 0
```
 What do you think about this syntax?

**Comment by haselkern** [comment]
I think it adds an unnecessary layer of complexity to the language. It [was already confirmed](https://github.com/vlang/v/issues/163#issuecomment-485722210) that V will have lambdas. With them, you could easily do something like this:

~~~V
a := [1, 2, 3, 4, 5]
b := a.apply(x -> x*2)
// b is [2, 4, 6, 8, 10]
c := a.filter (x -> x % 2 == 0)
// c is [2, 4]
~~~

`apply`, `filter`, and the lambda syntax are not in the language (yet) but I think they provide a more readable and more consistent way to do these operations.

Higher order functions are already implemented, so you could already define your own list type and pass function references:

```
fn main() {
    mut a := List{[1, 2, 3, 4, 5]}
    println(a) // [1, 2, 3, 4, 5]
    a.apply(triple)
    println(a) // [3, 6, 9, 12, 15]
    a.filter(is_even)
    println(a) // [6, 12]
}

fn triple(x int) int {
    return x * 3
}

fn is_even(x int) bool {
    return x % 2 == 0
}
```
[Full code here.](https://gist.github.com/haselkern/79910e54ae7c6f54511333d4ac279819)

**Comment by medvednikov** [comment]
There will be no for expressions. @ntrel covered this well.
