### ISSUE TITLE
# Are there plans to support jetbrains plugins?

### ISSUE THREAD

**Issue by xzyan** [vlang/v#7876]
有计划支持jetbrains插件吗？

**Comment by JalonSolov** [comment]
Someone was working on one, but a real plugin needs to wait for `vls` to be completed.

https://github.com/vlang/vls

**Comment by nedpals** [comment]
We will be supporting other clients, just keep track of this issue:
https://github.com/vlang/vls/issues/52

**Comment by xzyan** [comment]
That's great, look forward to it!
