### ISSUE TITLE
mut embed struct field compile error

### ISSUE THREAD

**Issue by kitech** [vlang/v#7891]
**V version:** V 0.2.1 3dae44d
**OS:**  Linux x64

**What did you do?**
```
struct Foo1 {
    mut:
    x int
}
struct Foo2 {
    mut:
    Foo1
}
fn main() {}
```

**What did you expect to see?**
compile ok
 
**What did you see instead?**
```
t.v:9:1: error: expecting type declaration
    7 |     mut:
    8 |     Foo1
    9 | }
      | ^
   10 | fn main() {}

```

Without `mut:` it works.
1. maybe need a proper error
2. does it's should works with 'mut:' like normal field?

**Comment by danieldaeschle** [comment]
thanks for the issue

**Comment by donnisnoni** [comment]
@danieldaeschle I found the same thing earlier but I thought this is intended.

**Comment by danieldaeschle** [comment]
it is. but the error is unclear.
