### ISSUE TITLE
Can't compile structs with string fields

### ISSUE THREAD

**Issue by MaxGraey** [vlang/v#79]
```go
struct Foo {
  s string
}

fn main() {
  foo := Foo {
    s: `foo` 
  }
}
```
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

**Comment by mrtnpwn** [comment]
You used a back tick instead of a single quote symbol, replacing these
should make it to compile correctly.

```v
struct Foo {

  s string
}

fn main() {
  foo := Foo {
    s: 'foo'
  }
}

```

**Comment by mrtnpwn** [comment]
You used a back tick instead of `'`.

**Comment by mrtnpwn** [comment]
This compiles correctly:

```v
struct Foo {
  s string
}

fn main() {
  foo := Foo {
    s: `foo` 
  }
}
```

**Comment by MaxGraey** [comment]
Yes, but this should support.
```go
fn main() {
	a := `foo`
}
```
This compiles so why `Foo { s: `foo` }` not compiled?

**Comment by medvednikov** [comment]
` is used for characters. `foo` should not compile, I'll fix it today.

**Comment by medvednikov** [comment]
Fixed:

`invalid character literal (more than one character)`
