### ISSUE TITLE
Third-party libraries

### ISSUE THREAD

**Issue by zenith391** [vlang/v#790]
Currently there is no way to import libraries/modules outside from VROOT. A first good step for your planned package system would be importing libraries from outside VROOT
Example:
Here is the file structure:
```
- v-program
 -- swang
  --- swang_library.v
 -- v_test.v
```
In current V, when v_test.v will import swang, it will just fail compilation due to not finding it, a good thing first would be to allow importing from program directory, so the case below would work

**Comment by zenith391** [comment]
Ok i found out, it's possible with `v -lib (PATH)`

**Comment by zenith391** [comment]
Nevermind found out `v -lib (PATH)` is broken and search for vlib inside `~/.vlang/vlib` instdead of VROOT

**Comment by AtjonTV** [comment]
Similar Issue: #456 

Very similar if not the same idea path: https://github.com/vlang/v/issues/456#issuecomment-506612211
