### ISSUE TITLE
Reimplement Cached Modules (fully independent module technique)

### ISSUE THREAD

**Issue by joe-conigliaro** [vlang/v#7908]
Reimplement Cached Modules
- Fully independent module technique
- Smaller OBJ files (own module code only)
- No need to bundling some modules into `main.c`
- No duplicate symbols, static functions or types
- Many more benefits

**Comment by kitech** [comment]
does this means one generated `.c` file per module?

**Comment by joe-conigliaro** [comment]
Yes, a .c and .h file that way the modules will be fully independent and and can call fns/use types from other modules. This will greatly decrease the size of the obj files and it will mean we don't need to include all the types/uses fns in each module. And a bunch of other benefits. I have already started implementing this.

**Comment by kitech** [comment]
What would included in .h file, the V pub methods should be already mangled to  `modname__structname__methodname`.
