### ISSUE TITLE
v fmt removes pub from struct fields

### ISSUE THREAD

**Issue by fnetX** [vlang/v#7909]
I guess this might be a dupe, as there are many issues about v fmt, but I couldn't keep track about all of them, and it's obviously not fixed yet, so ...

**V version:** V 0.2.1 a9ab79d
**OS:** Debian GNU/Linux Buster

**What did you do?**
Run v fmt on this:
```
module main

struct StructA {
	x int
	y int
}

struct StructB {
	StructA
mut:
	z string
}

fn main() {
	mut b := StructB{
		StructA: StructA{
			x: 1
			y: 2
		}
	}
	b.z = 'hey'
}
```

**What did you expect to see?**
Actually nothing at all, because I think that it's already pretty well formatted :wink: 
 
**What did you see instead?**
v fmt removes the mut: in front of StructB.z which makes the example fail to run.

**Comment by spaceface777** [comment]
This was fixed recently, run `v up` to get the latest changes.

**Comment by fnetX** [comment]
Oh, I'm actually monitoring the changes in V closely, as there are more issues we're struggling with ... must have missed that. Indeed, seems to work now, thank you.
