### ISSUE TITLE
Virus & threat proteciton

### ISSUE THREAD

**Issue by guizhenwei** [vlang/v#7917]
**V from master branch** 
**OS: Windows 10 Pro** 

**What did you do?**
`v.exe run file_name.v`

**What did you expect to see?**
Correctly running or print the results.
 
**What did you see instead?**
Windows OS blocks the execution immediately, then take up to 10 seconds to scan and delete executable file, with the following notification:

![image](https://user-images.githubusercontent.com/12146658/103750493-d4e7f600-5041-11eb-876e-a1a14a82082e.png)

**Comment by IngwiePhoenix** [comment]
You can declare safe folders in Windows Defender.
It very often doesn't like self-compiled binaries as they are not signed, thus not trusted...

I recommend declaring your work folder a safe folder and do your work there. Kinda annoying but...That's kinda what Windows does. ;)

**Comment by danieldaeschle** [comment]
is it self compiled or downloaded?

**Comment by guizhenwei** [comment]
> You can declare safe folders in Windows Defender.
> It very often doesn't like self-compiled binaries as they are not signed, thus not trusted...
> 
> I recommend declaring your work folder a safe folder and do your work there. Kinda annoying but...That's kinda what Windows does. ;)

It works! Thanks for your help.

**Comment by guizhenwei** [comment]
> is it self compiled or downloaded?

It is self compiled V binary.
Git clone from the master branch, then make by tcc.
