### ISSUE TITLE
vweb: every second request is slow (> 200ms)

### ISSUE THREAD

**Issue by MohammadAliChraghi** [vlang/v#7935]
**Valang** has a very fast speed! But the **Vweb** library is very slow to respond
What is the cause? Why does **express** respond in 6ms but **Vweb** in 300ms?
**Sorry For Bad English**

**Comment by danieldaeschle** [comment]
Please provie an example and how you messured it.

**Comment by danieldaeschle** [comment]
Ok, i tested it as well and it was even 500ms (prod mode)

**Comment by MohammadAliChraghi** [comment]
> Please provie an example and how you messured it.

In Chrome HTML Document Response Time

**Comment by danieldaeschle** [comment]
![image](https://user-images.githubusercontent.com/30751516/103885705-b5ec7100-50e0-11eb-965b-1604f2322403.png)

**Comment by danieldaeschle** [comment]
seems pretty fast:
```v
import vweb

struct App {
	vweb.Context
}

fn (mut app App) index() vweb.Result {
	return app.text('Hello World!')
}

fn main() {
	vweb.run<App>(8080)
}
```

**Comment by MohammadAliChraghi** [comment]
See This
`module main

import vweb

const (
	port = 8082
)

struct App {
	vweb.Context
mut:
	cnt int
}

fn main() {
	println('vweb example')
	vweb.run<App>(port)
}

pub fn (mut app App) init_once() {
	app.handle_static('.')
}

pub fn (mut app App) json_endpoint() vweb.Result {
	return app.json('{"a": 3}')
}

pub fn (mut app App) index() vweb.Result {
	app.cnt++
	show := true
	// app.text('Hello world from vweb')
	hello := 'Hello world from vweb'
	numbers := [1, 2, 3]
	return $vweb.html()
}

pub fn (mut app App) show_text() vweb.Result {
	return app.text('Hello world from vweb')
}

pub fn (mut app App) cookie() vweb.Result {
	app.set_cookie(name: 'cookie', value: 'test')
	return app.text('Headers: $app.headers')
}`
![Screenshot 2021-01-07 144738](https://user-images.githubusercontent.com/63465728/103886914-78471280-50f7-11eb-88fc-842be8b19032.png)

**Comment by danieldaeschle** [comment]
Can you try with a better benchmarktool than chrome?

**Comment by MohammadAliChraghi** [comment]
Benchmarking is not a problem My argument is that when I send a request to the server, it takes 300ms to see the response

**Comment by JalonSolov** [comment]
What URL did you use?

**Comment by MohammadAliChraghi** [comment]
> What URL did you use?

**localhost**

**Comment by JalonSolov** [comment]
So you just typed 'localhost' into the browser?  Not going to hit vweb code that way.

Let's assume for a moment that you were diligent enough to actually type at least `localhost:8082'.  Is that all you did, or was there something else on the line?

**Comment by MohammadAliChraghi** [comment]
> So you just typed 'localhost' into the browser? Not going to hit vweb code that way.
> 
> Let's assume for a moment that you were diligent enough to actually type at least `localhost:8082'. Is that all you did, or was there something else on the line?

No bro, I have been programming for two years. Rest assured, I understand enough that I wrote a issue
I do not know much about V, but I like this language very much
And I really like building a website with vWeb.
I hope you forgive me if you are upset
Anyway, I want this language to improve

**Comment by danieldaeschle** [comment]
@MohammadAliChraghi He just wanted to know if you provided any URL path behind `localhost:8082`

**Comment by JalonSolov** [comment]
@danieldaeschle is correct.  Your code has several route points, including a `json_endpoint`.  Which one was used can affect the response time.  That's why I asked for the URL.

**Comment by MohammadAliChraghi** [comment]
Of course, I have already done this with a simple answer and the result was like this
Please do this test yourself (I know this is not a good method)

**Comment by JalonSolov** [comment]
I am trying to help you, but you are not supplying all info required.

For example, when I tried to run the example you pasted above, I got this error:
```
vweb_test.v:35:1: error: vweb HTML template "/templates/index.html" not found
```
So what are you using for index.html?  The contents of this file can definitely affect the response speed.

It is also less than useful to just say "it's too slow" without giving all the details, including the URL you used, etc., since the endpoint you tested can make a big difference in the response speed.

**Comment by danieldaeschle** [comment]
I think he uses `examples/vweb_example.v`

**Comment by MohammadAliChraghi** [comment]
I copied this code from vweb examples myself and encountered this error and just created a blank html file in templates / index.html
Like I said, this problem has nothing to do with my code

 If you tried the code and did not have a low response speed
So most likely the problem is my system

**Comment by danieldaeschle** [comment]
![image](https://user-images.githubusercontent.com/30751516/103911751-b39d0d80-5106-11eb-814d-e25535af46ec.png)
every second request is slow.

**Comment by JalonSolov** [comment]
I'm saw 14ms response on my machine on the first request, using the vweb example project.  Each time after that I saw 5~6ms response.

**Comment by MohammadAliChraghi** [comment]
> I'm saw 14ms response on my machine on the first request, using the vweb example project. Each time after that I saw 5~6ms response.

How?

**Comment by danieldaeschle** [comment]
I tested on Windows, which OSes are you using?

**Comment by JalonSolov** [comment]
Linux to run the example, Firefox on Windows to access the URL.

**Comment by MohammadAliChraghi** [comment]
> I tested on Windows, which OSes are you using?

I did the same in Windows
then, this is a bug specific to Windows

**Comment by JalonSolov** [comment]
Still specific to your machines, or something else.  I started it on Windows, and used Firefox on Windows, and saw 0ms most of the time, with an ocassional spike to 10ms.

When I ran it before, it was in Linux under WSL2, so that might account for the _very_ slightly higher response times I saw then.

**Comment by medvednikov** [comment]
@MohammadAliChraghi that's why we have a github issue template that shouldn't be ignored. Saves time.

**Comment by MohammadAliChraghi** [comment]
I'm really confused!

**Comment by JalonSolov** [comment]
As @medvednikov said, the issue template could have made this go much faster.  Not knowing which system you tried this on had me trying it on something different.

The OS itself, the revision, the patch level, the version of V, etc., etc., etc. can _all_ affect things like this.  That's why the template asks for OS and V version, but also says you can use `v doctor` output there.

The usual first response if your version of V isn't the most current is to ask you to run `v up` and try again.  Since you have said which version of V you have, and I didn't think to ask up front, that could be a large part of the problem here as well.  I'm using the very latest version after running `v up`.

**Comment by MohammadAliChraghi** [comment]
> @MohammadAliChraghi that's why we have a github issue template that shouldn't be ignored. Saves time.

You are right
I can continue with Skype  live:.CID.d2fe48dadb52ab16

**Comment by danieldaeschle** [comment]
We have a discord server

**Comment by MohammadAliChraghi** [comment]
> We have a discord server

Very good
Can you give his address?

**Comment by Delta456** [comment]
Here https://discord.gg/vlang

It's in the `README.md` too. 🙂

**Comment by MohammadAliChraghi** [comment]
I think this error is the cause of the problem!
The first line failed
(Why doesn't anyone come to Discord?)

**Comment by MohammadAliChraghi** [comment]
> We have a discord server

**Comment by danieldaeschle** [comment]
Why closing this? This i not fixed!

**Comment by medvednikov** [comment]
A new issue was created.
