### ISSUE TITLE
Sumtype match with array type

### ISSUE THREAD

**Issue by avillega** [vlang/v#7948]
For some applications supporting sum types of the form type `MySum = []MySum | int` is very useful.
currently the compiler let's you define such type, however it is not possible to match agains such type, for example
```
type MySum = []MySum | int

fn sumtype_recursive() {
	my_sum_array := [MySum(0)]
	my_sum := MySum(my_sum_array)
	match my_sum {
		[]MySum {
			println('[]MySum')
		}
		int {
		        println('int')
		}
	}
}
```
The compiler fails, it gets confused when parsing the branch `[]MySum` and is expecting and array or map initialization.

**Comment by Delta456** [comment]
It is getting fixed in https://github.com/vlang/v/pull/7939
