### ISSUE TITLE
vweb: failed first_line" error

### ISSUE THREAD

**Issue by alic110** [vlang/v#7950]
**V version:** 0.2.1 21d5db4
**OS:** Windows 10 Pro 19042 64x

Code :
`v run examples/vweb/vweb_assets/vweb_assets.v`

I often get a **"Failed first_line"** error after every request to the server, and as far as I can see, the server responds to more than 300ms only when I get this error.

I searched a bit and found the line that gives me this error [Line 258](https://github.com/vlang/v/blob/master/vlib/vweb/vweb.v)

**Comment by medvednikov** [comment]
This is most likely an antivirus issue.

**Comment by LouisSchmieder** [comment]
No we found out this is an chromium thing, because chromium sends 2 requests but the second one is empty

**Comment by MohammadAliChraghi** [comment]
> No we found out this is an chromium thing, because chromium sends 2 requests but the second one is empty

Louis, I'm MohammadAliChraghi In Discord
