### ISSUE TITLE
Webv specific import fails with gcc compilation error

### ISSUE THREAD

**Issue by Polydynamical** [vlang/v#7958]
**V version**: latest

**OS**: Windows

I was learning about the v web framework using the following code: 
```v
// blog.v
module main

import vweb

struct App {
	vweb.Context
}

fn main() {
	vweb.run<App>(8081)
}

pub fn (mut app App) index() vweb.Result {
	return app.text('Hello world from vweb!')
}

pub fn (app &App) init() {
}

pub fn (app &App) init_once() {
}
```

This worked perfectly. However, I wanted to try some specific imports and changed the code to the following:

```v
// blog.v
module main

import vweb { Context, run, Result}

struct App {
	Context
}

fn main() {
	run<App>(8081)
}

pub fn (mut app App) index() Result {
	return app.text('Hello world from vweb!')
}

pub fn (app &App) init() {
}

pub fn (app &App) init_once() {
}
```

**What did you expect to see?**
I expected everything to be the same as I am pretty sure that is the way in which specific imports work.
 
**What did you see instead?**

However, I got the following error:
```
C compilation failed.
builder error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: gcc @C:\Users\andre\AppData\Local\Temp\v\blog.17546630936874958489.tmp.c.rsp      
```

Note: I use tcc instead of gcc...

**Comment by cbracketdash** [comment]
Anyone?

**Comment by jon49** [comment]
Did you ever get an answer for this anywhere else? I'm running into the same problem when I try to import sqlite.

**Comment by JalonSolov** [comment]
I just tried your 2nd example, and got this:
```
undefined reference to `vweb__run_T_main__App'
```

**Comment by JalonSolov** [comment]
However, it turns out that it fails because your code is incorrect.  Change your `fn main` to this:
```v
fn main() {
	mut app := App{}
	vweb.run_app<App>(mut app, 8081)
}
```
and it works fine.

This is definitely an error that needs to be fixed - V should have a least given a nice V error instead of you hitting a C error.
