### ISSUE TITLE
# as comment for shebangs

### ISSUE THREAD

**Issue by zenith391** [vlang/v#796]
As i saw that you planned making V scripts, i thought that making `#` a one-line comment type (only at start of file if you don't want it to be used for actual code) so that V scripts could be launched by Linux parsing their shebangs, so using `./myscript.v` instdead of `v run myscript.v`.

This would make V scripts feel more natural, and have a way of launching similar to *sh, which is its purpose

**Comment by proyb6** [comment]
https://github.com/vlang/v/issues/585

**Comment by zenith391** [comment]
ok didn't saw
