### ISSUE TITLE
Not having correct functions/types in custom builtin results in builder error

### ISSUE THREAD

**Issue by crthpl** [vlang/v#7973]
**V version:** 
V 0.2.1 dff36a9
**OS:** 
MacOS Big Sur 11.1
**What did you do?**
Specify custom path `-path my-vlib/` where the file hierarchy is
```
my-vlib/
-builtin/
--(no files in here)
```
**What did you expect to see?**
`string` not defined, `map` not defined, etc.

 
**What did you see instead?**
```
==================
        ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.9492119035314922906.tmp.c:502:9: error: unknown type name 'map'
typedef map map;
        ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.9492119035314922906.tmp.c:516:1: error: unknown type name 'string'
string _STR(const char*, int, ...);
^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.9492119035314922906.tmp.c:517:1: error: unknown type name 'string'
string _STR_TMP(const char*, ...);
^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.9492119035314922906.tmp.c:519:58: error: unknown type name 'string'
VV_LOCAL_SYMBOL int main__syscall5(int number, int arg1, string arg2, u64 arg3, u64 arg4, voidptr arg5);
...
==================
builder error:
==================
C error. This should never happen.
```

<details>
<summary>Full Error</summary>
<pre>
<code>
 /var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:502:9: error: unknown type name 'array'
typedef array array;
        ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:503:9: error: unknown type name 'map'
typedef map map;
        ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:517:1: error: unknown type name 'string'
string _STR(const char*, int, ...);
^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:518:1: error: unknown type name 'string'
string _STR_TMP(const char*, ...);
^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:520:42: error: unknown type name 'string'
int main__syscall5(int number, int arg1, string arg2, u64 arg3, u64 arg4, voidptr arg5);
                                         ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:521:25: error: unknown type name 'string'
int main__write(int fd, string data, u64 nbytes);
                        ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:560:1: error: unknown type name 'string'
string _STR(const char *fmt, int nfmts, ...) {
^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:592:5: error: use of undeclared identifier 'string'
                                string s = va_arg(argptr, string);
                                ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:596:26: error: implicit declaration of function 'utf8_str_visible_length' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                                                fwidth -= (s.len - utf8_str_visible_length(s));
                                                                   ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:596:50: error: use of undeclared identifier 's'
                                                fwidth -= (s.len - utf8_str_visible_length(s));
                                                                                           ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:596:18: error: use of undeclared identifier 's'
                                                fwidth -= (s.len - utf8_str_visible_length(s));
                                                           ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:598:50: error: use of undeclared identifier 's'
                                                fwidth += (s.len - utf8_str_visible_length(s));
                                                                                           ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:598:18: error: use of undeclared identifier 's'
                                                fwidth += (s.len - utf8_str_visible_length(s));
                                                           ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:599:53: error: use of undeclared identifier 's'
                                        _STR_PRINT_ARG(fmt, &buf, &nbytes, &memsize, k+s.len-4, fwidth, s.len, s.str);
                                                                                       ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:599:70: error: use of undeclared identifier 's'
                                        _STR_PRINT_ARG(fmt, &buf, &nbytes, &memsize, k+s.len-4, fwidth, s.len, s.str);
                                                                                                        ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:599:77: error: use of undeclared identifier 's'
                                        _STR_PRINT_ARG(fmt, &buf, &nbytes, &memsize, k+s.len-4, fwidth, s.len, s.str);
                                                                                                               ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:601:53: error: use of undeclared identifier 's'
                                        _STR_PRINT_ARG(fmt, &buf, &nbytes, &memsize, k+s.len-4, s.len, s.str);
                                                                                       ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:601:62: error: use of undeclared identifier 's'
                                        _STR_PRINT_ARG(fmt, &buf, &nbytes, &memsize, k+s.len-4, s.len, s.str);
                                                                                                ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:601:69: error: use of undeclared identifier 's'
                                        _STR_PRINT_ARG(fmt, &buf, &nbytes, &memsize, k+s.len-4, s.len, s.str);
                                                                                                       ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:621:9: error: implicit declaration of function 'tos2' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        return tos2((byteptr)buf);
               ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:624:1: error: unknown type name 'string'
string _STR_TMP(const char *fmt, ...) {
^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:637:2: error: use of undeclared identifier 'string'
        string res = tos(g_str_buf,  len);
        ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:638:2: error: use of undeclared identifier 'res'
        res.is_lit = 1;
        ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:639:9: error: use of undeclared identifier 'res'
        return res;
               ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:644:42: error: unknown type name 'string'
int main__syscall5(int number, int arg1, string arg2, u64 arg3, u64 arg4, voidptr arg5);
                                         ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:646:25: error: unknown type name 'string'
int main__write(int fd, string data, u64 nbytes) {
                        ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:647:57: error: cannot take the address of an rvalue of type 'int'
        return main__syscall5(1, fd, data, nbytes, 0, (voidptr)&/*qq*/0);
                                                               ^      ~
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:651:17: error: use of undeclared identifier 'string'
        main__write(1, _SLIT("Hello from V running on bare metal!\n"), 37);
                       ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:330:20: note: expanded from macro '_SLIT'
#define _SLIT(s) ((string){.str=(byteptr)("" s), .len=(sizeof(s)-1), .is_lit=1})
                   ^
/var/folders/tk/5cj2yz0d6mn9dmpl9fncfv1c0000gq/T/v/main.1470116359064166250.tmp.c:655:2: error: implicit declaration of function 'builtin_init' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        builtin_init();
        ^
29 errors generated.
builder error:
==================
C error. This should never happen.
</code>
</details>

**Comment by medvednikov** [comment]
`builtin` is very low level and intertwined with the compiler.

This is a rare case where a C error is fine.
