### ISSUE TITLE
Imprecise double arithmetics?

### ISSUE THREAD

**Issue by MaxGraey** [vlang/v#80]
```go
fn main() {
	t := 0.1 + 0.2
	println(t == 0.30000000000000004)
}
```
Output: `false`
Expected: `true`

**Comment by medvednikov** [comment]
https://play.golang.org/p/NAFwcLhTQK0

**Comment by MaxGraey** [comment]
In Go: `0.1 + 0.2 == 0.3` and it's true. Btw it's wrong! In all languages this will be false
1. [Go](https://play.golang.org/p/PV4m3XXFpkv) `true`
2. [Rust](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d46367b55fc872b7560a6b7c380e1aa3) `false`

But in your case even `0.1 + 0.2 == 0.3` is false:
```go
fn main() {
	t := 0.1 + 0.2
	println(t == 0.3)
}
```
Output: `false`

How you explain this?

**Comment by medvednikov** [comment]
V running in the playground compiles to C, that's how it works there.

**Comment by MaxGraey** [comment]
@medvednikov 
Same as Rust:
https://onlinegdb.com/BkdNxHYtV

**Comment by medvednikov** [comment]
Right now floating-point constants default to `f32`, instead of `f64`. Will be fixed today.

**Comment by medvednikov** [comment]
I changed it to `f64`, the comparison still doesn't work because it doesn't work in C (and in C++).

Comparing floats like this is a bad idea:

https://www.cs.technion.ac.il/users/yechiel/c++-faq/floating-point-arith.html

https://www.boost.org/doc/libs/1_61_0/libs/math/doc/html/math_toolkit/float_comparison.html

**Comment by medvednikov** [comment]
Actually ` 0.1 + 0.2  == 0.30000000000000004` works now. `0.1 + 0.2 == 0.3` doesn't.

**Comment by MaxGraey** [comment]
> the comparison still doesn't work because it doesn't work in C (and in C++).

comparison `0.1 + 0.2 == 0.30000000000000004` should works exactly in C/C++:
<img width="688" alt="c" src="https://user-images.githubusercontent.com/1301959/56710590-9906e300-672f-11e9-821b-6ee93f6d1682.png">

Current in V:
```
fn main() {
	t := 0.1 + 0.2
	println(t == 0.30000000000000004)
}
```
Output:
```
false
```

It still not fixed!

**Comment by MaxGraey** [comment]
[In Rust](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=25993ba012c7c674c6f1dafd468077af):

<img width="932" alt="Rust" src="https://user-images.githubusercontent.com/1301959/56710727-33ffbd00-6730-11e9-9214-a49162d8d63d.png">

**Comment by MaxGraey** [comment]
[In Go](https://play.golang.org/p/ai_DzUMSYt4):

<img width="562" alt="Go" src="https://user-images.githubusercontent.com/1301959/56711592-1d5b6500-6734-11e9-8c1d-625f240d4d76.png">

**Comment by medvednikov** [comment]
Forgot to deploy the playground after the fix:

```
t := 0.1 + 0.2
println(t == 0.30000000000000004)
```

Now it works like C/C++.

**Comment by proyb6** [comment]
I tried to run on playground today, output as ```false```

```
t := 0.1 + 0.2
println(t == 0.30000000000000004)
// t is 0.300000
```

**Comment by MaxGraey** [comment]
Can confirm. This issue still not fixed!

**Comment by whoizit** [comment]
it should be open, because this is not fixed

**Comment by medvednikov** [comment]
@whoizit fixed again.

`t == 0.30000000000000004`

**Comment by megatux** [comment]
Just for completion, https://0.30000000000000004.com/
