### ISSUE TITLE
match const not work when named upper case

### ISSUE THREAD

**Issue by kitech** [vlang/v#8005]
**V version:** V 0.2.1 9593ad2
**OS:** linux x64

**What did you do?**
```
const FOO = 123

fn main () {
    val := int(123)
    match val {
        FOO {}
        else{}
    }
}
```

**What did you expect to see?**
compile ok
 
**What did you see instead?**
```
t.v:1:7: warning: const names cannot contain uppercase letters, use snake_case instead
    1 | const FOO = 123
      |       ~~~
    2 | 
    3 | fn main () {
t.v:6:9: error: cannot match `FOO` with `int` condition
    4 |     val := int(123)
    5 |     match val {
    6 |         FOO {}
      |         ~~~
    7 |         else{}
    8 |     }

```

known case: when named lower case, it works

**Comment by serkonda7** [comment]
As you might see from the error, this is no bug but a language constraint.
In V only snake_case is allowed.

**Comment by kitech** [comment]
but it works in these cases: as parameter, assign to another var:
```
println(FOO)
somefunc(FOO)
val := FOO
```

**Comment by serkonda7** [comment]
Yes, but it still gives the warning and an error with `-prod`
