### ISSUE TITLE
simple way to add windows support in some files

### ISSUE THREAD

**Issue by retsyo** [vlang/v#801]
# common solution
since you have said we can use mingw64 to compile v, it is easy to add windows support in some files. Why I do not make my own commit? I don't know why I can't commit even I modify my forked code.

for `vlib\gl\gl.v`, add
```
#flag windows -I @VROOT/thirdparty/glad
```

for `vlib\stbi\stbi.v`, add
```
#flag windows -I @VROOT/thirdparty/stb_image
``` 

# user-specified solution
furthermore, if we want to compile `examples\tetris\tetris.v`, we have to modify 2 more files. Although it reads as `/mingw64` in msys2, but I have to use the user-specified directory:
for `vlib\glfw\glfw.v`, add
```
#flag windows -I/E:/msys64/mingw64/include
#flag windows -lglfw3
```
here, I can't use
```
#flag windows -I/mingw64/include
#flag windows -lglfw3
```

for `lib\gg\gg.v`, add
```
#flag windows 	-IE:/msys64/mingw64/include/freetype2
```

**Comment by medvednikov** [comment]
Thanks, I've just released v.exe, I'll now make sure `gg` and `gl` work out of the box.

**Comment by aguspiza** [comment]
I have integrated this solutions in PR #817. Windows builds in travis and passes most tests!
Thanks!

**Comment by medvednikov** [comment]
This was fixed.
