### ISSUE TITLE
MSVC compiler error TOS problem

### ISSUE THREAD

**Issue by penguindark** [vlang/v#8013]
found a strange error in the compiler:
```v
fn (mut tf TTF_File) get_string(length int) string {
  tmp_pos := tf.pos
  tf.pos += u32(length)
  unsafe{
    return tos(&tf.buf.data[tmp_pos], length)
  }
}
```
began in C:
```c
string ttf__TTF_File_get_string(ttf__TTF_File* tf, int length) {
  u32 tmp_pos = tf->pos;
  tf->pos += ((u32)(length));
  { // Unsafe block
    return tos(&tf->buf.data[tmp_pos], length);
  }
  return (string){.str=(byteptr)""};
}
```
**and crash the MSVC compiler!!**
With gcc and tcc no problem!
It seems a problem with the `tos` function!

**Comment by penguindark** [comment]
Workarond:
```v
fn (mut tf TTF_File) get_string(length int) string {
	tmp_pos := tf.pos
	mut tmp_txt := strings.new_builder(length)
	for _ in 0..length {
		tmp_txt.write_b(tf.get_u8())
	}
	res_txt := tmp_txt.str()
	tf.pos = tmp_pos + u32(length)
	return res_txt
}
```

**Comment by emily33901** [comment]
@penguindark you probably want to use `tos_clone()`

**Comment by penguindark** [comment]
@emily33901 No it is the clone that I want to avoid ;)

**Comment by emily33901** [comment]
its the lack of clone that probably crashes it though - that was one of the issues that I had with my protobuf runtime
see https://github.com/emily33901/vproto/blob/master/encoding.v#L487

```v
fn string_unpack(buf []byte) (int,string) {
	size_len, str_len := uint32_unpack(buf)
	if str_len == 0 {
		return size_len, ''
	}
	// Clone here to make sure the string is 0 terminated
	return int(str_len) + size_len, tos(&buf[size_len], int(str_len)).clone()
}

fn bytes_unpack(buf []byte) (int,[]byte) {
	size_len, bytes_len := uint32_unpack(buf)
	return int(bytes_len) + size_len, buf[size_len..(int(bytes_len)+size_len)].clone()
}```

**Comment by penguindark** [comment]
Strange because with the other compiler (gcc,tcc) and -prod I've no problems.
The string is only read, all that buffer is read only.
I was trying to optimize in order to avoid to create copies of the strings

**Comment by medvednikov** [comment]
msvc can detect memory bugs other compilers failed to detect. Happened before.

I'd suggest using clone() for now, mark it as TODO, and return to it once it works with -autofree.

**Comment by emily33901** [comment]
Yep I think that is almost certainly the reason why I used it here. Either that or because of the needing 0 termination even though we have a length Variable

**Comment by ntrel** [comment]
@penguindark to find out why MSVC is crashing, can you try commenting out lines of `ttf__TTF_File_get_string` until you isolate the line causing the problem? (I don't have MSVC installed on my machine). Maybe try using a variable: `byteptr ptr = &tf->buf.data[tmp_pos];` and passing `ptr`?

**Comment by penguindark** [comment]
@ntrel using your suggestion give the same error :
```
test_ttf.8544015277558333485.tmp.c
C:\Users\Dario\AppData\Local\Temp\v\test_ttf.8544015277558333485.tmp.c(17307): error C2036: 'voidptr': unknown size
C:\Users\Dario\AppData\Local\Temp\v\test_ttf.8544015277558333485.tmp.c(17316): error C2036: 'voidptr': unknown size
```
`tos_clone` instead work well, but not solve the problem that i don't want a copy.

**Comment by ntrel** [comment]
@penguindark So MSVC doesn't crash, but it thinks there is wrong usage of voidptr. Can you post the two C lines that give that error?

**Comment by penguindark** [comment]
The code is in the first post of this issue: https://github.com/vlang/v/issues/8013#issue-782851904

**Comment by ntrel** [comment]
> &tf->buf.data[tmp_pos]

The problem is that the data field is a voidptr and cannot be indexed. V should error too, I thought I implemented that but maybe it's an edge case. gcc allows void* indexing, treating it like a byte pointer but that's not standard C. 
Try `&byte(tf.pos.data) + tmp_pos`.

**Comment by ntrel** [comment]
> field is a voidptr and cannot be indexed. V should error too

https://github.com/vlang/v/pull/8109

**Comment by penguindark** [comment]
@ntrel @spytheman @medvednikov 
I did some tests and the problem persist, for example the following code compile and work well on gcc and tcc without problems but fail on MSVC:
```v
fn (mut tf TTF_File) get_string(length int) string {
	tmp_pos := byteptr(tf.pos)
	tf.pos += u32(length)
	unsafe{
		mut tmp := byteptr(tf.buf.data)
		tmp += byteptr(tmp_pos)
		return tos(tmp, length)
	}
}
```
Same error, but `tmp` is not a `voidptr` but a `byteptr`
```
C:\Users\Dario\AppData\Local\Temp\v\test_ttf.16496075321267200700.tmp.c(17307): error C2036: 'voidptr': unknown size
C:\Users\Dario\AppData\Local\Temp\v\test_ttf.16496075321267200700.tmp.c(17316): error C2036: 'voidptr': unknown size
```

The problem lies in V that convert `byteptr` to `voidptr` for not known reason to me.
This is the code generated by V:
```c
VV_LOCAL_SYMBOL string ttf__TTF_File_get_string(ttf__TTF_File* tf, int length) {
	u32 tmp_pos = tf->pos;
	tf->pos += ((u32)(length));
	{ // Unsafe block
		voidptr* ptr = &tf->buf.data[tmp_pos];
		return tos(ptr, length);
	}
	return (string){.str=(byteptr)""};
} // this is the row 17307 of the MSCV error
```

**Comment by penguindark** [comment]
The bug happen only if you compile on windows.
This source code:
```v
fn (mut tf TTF_File) get_string(length int) string {
	tmp_pos := byteptr(tf.pos)
	tf.pos += u32(length)
	unsafe{
		mut tmp := byteptr(tf.buf.data)
		tmp += byteptr(tmp_pos)
		return tos(tmp, length)
	}
}
```
produce **two** function and I don't know why: :sob: 
```c
VV_LOCAL_SYMBOL string ttf__TTF_File_get_string(ttf__TTF_File* tf, int length) {
	u32 tmp_pos = tf->pos;
	tf->pos += ((u32)(length));
	{ // Unsafe block
		voidptr* ptr = &tf->buf.data[tmp_pos];
		return tos(ptr, length);
	}
	return (string){.str=(byteptr)""};
}

VV_LOCAL_SYMBOL string ttf__TTF_File_get_string1(ttf__TTF_File* tf, int length) {
	u32 tmp_pos = tf->pos;
	tf->pos += ((u32)(length));
	{ // Unsafe block
		return tos(&tf->buf.data[tmp_pos], length);
	}
	return (string){.str=(byteptr)""};
}
```

**Comment by ntrel** [comment]
@penguindark You do not need these casts:
>     tmp_pos := byteptr(tf.pos)

>		tmp += byteptr(tmp_pos)

C does not allow you to add two pointers together, only to add an integer to a pointer. V allows this ATM probably because of implicit conversions.

```v
	tmp_pos := tf.pos
	tf.pos += u32(length)
	unsafe{
		mut tmp := byteptr(tf.buf.data)
		tmp += tmp_pos
		return tos(tmp, length)
	}
```

> 		voidptr* ptr = &tf->buf.data[tmp_pos];

Are you sure that's the generated code? It would be very weird if V generated that. On my Windows system with gcc the C code looks as it should.

**Comment by spytheman** [comment]
For me, it generates:
`byteptr tmp = ((byteptr)(tf->buf.data));` 
but I tried only on linux and with `-os windows -o x.c -cc msvc` so far. I will test in a VM soon.

**Comment by penguindark** [comment]
@ntrel 
Ok found a solution: :smile: 
```v
fn (mut tf TTF_File) get_string(length int) string {
	tmp_pos := tf.pos
	tf.pos += u32(length)
	unsafe{
		return tos(byteptr(u32(tf.buf.data)+u32(tmp_pos)), length)
	}
}
```
that yield in C:
```c
VV_LOCAL_SYMBOL string x__ttf__TTF_File_get_string(x__ttf__TTF_File* tf, int length) {
	u32 tmp_pos = tf->pos;
	tf->pos += ((u32)(length));
	{ // Unsafe block
		return tos(((byteptr)(((u32)(tf->buf.data)) + ((u32)(tmp_pos)))), length);
	}
	return (string){.str=(byteptr)""};
}
```

**Comment by ntrel** [comment]
> 		return tos(byteptr(u32(tf.buf.data)+u32(tmp_pos)), length)

Why do you need to cast a pointer to u32? That is a serious bug on 64-bit systems. What's wrong with:

    return tos(byteptr(tf.buf.data)+u32(tmp_pos), length)

But I don't think that even that u32 cast should be needed.

**Comment by penguindark** [comment]
@ntrel  I changed it to u64 in the last sommit:
```v
fn (mut tf TTF_File) get_string(length int) string {
	tmp_pos := tf.pos
	tf.pos += u32(length)
	return unsafe{ tos(byteptr(u64(tf.buf.data)+u64(tmp_pos)), length) }
}
```
that lead to:
```c
VV_LOCAL_SYMBOL string x__ttf__TTF_File_get_string(x__ttf__TTF_File* tf, int length) {
	u32 tmp_pos = tf->pos;
	tf->pos += ((u32)(length));
	return tos(((byteptr)(((u64)(tf->buf.data)) + ((u64)(tmp_pos)))), length);
}
```

**Comment by penguindark** [comment]
@ntrel without cast to `u64` it lead to a MSVC error:
```
v\vlib\x\ttf\ttf.v:563:36: error: `+` cannot be used with `voidptr`
  561 |     tmp_pos := tf.pos
  562 |     tf.pos += u32(length)
  563 |     return unsafe{ tos(byteptr(tf.buf.data+tmp_pos), length) }
      |                                       ~~~~
  564 | }
  565 |
```

**Comment by ntrel** [comment]
> byteptr(tf.buf.data+

That is not what I suggested, you can't use + with a voidptr. The byteptr cast should only go around tf.buf.data

**Comment by penguindark** [comment]
you are right, MSVC is very strict on this, other compilers manage `voidptr` as `byte` pointer. 
About the two `u64` cast  I prefer be sure to make a manual cast on easch term of the sum avoiding auto cast in this case.
