### ISSUE TITLE
Chinese characters are not supported

### ISSUE THREAD

**Issue by scroot** [vlang/v#8014]
**V version:** 
v version
V 0.2.1 a1c6723

**OS:** 
uname -a
Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**What did you do?**
open:  v/examples/xamples/ttf_font/example_ttf.v
jump to line 68
modify:  

block_txt := "hello 中国!
Tommorow I'm not so sure :(
Frame: $app.frame_c
But Vwill prevail for sure, V is the way!!
òàèì@ò!£$%&
"

**What did you expect to see?**
normal

**What did you see instead?**

TrueTypeFont file [/home/scroot/devEnv/vlang/v/examples/ttf_font/Imprima-Regular.ttf] len: 23188
Unit per EM: 1000
TrueTypeFont file [/home/scroot/devEnv/vlang/v/examples/ttf_font/Graduate-Regular.ttf] len: 21292
Unit per EM: 1000
Using font /usr/share/fonts/truetype/freefont/FreeSans.ttf
font file "" does not exist, the system font was used instead.
V panic: array.get: index out of range (i == 57784, a.len == 21292)
/tmp/v/e.3354620427661911235.tmp.c:7236: at v_panic: Backtrace
/tmp/v/e.3354620427661911235.tmp.c:6755: by array_get
/tmp/v/e.3354620427661911235.tmp.c:17006: by x__ttf__TTF_File_get_u16
/tmp/v/e.3354620427661911235.tmp.c:17016: by x__ttf__TTF_File_get_i16
/tmp/v/e.3354620427661911235.tmp.c:17020: by x__ttf__TTF_File_get_fword
/tmp/v/e.3354620427661911235.tmp.c:16633: by x__ttf__TTF_File_get_horizontal_metrics
/tmp/v/e.3354620427661911235.tmp.c:16235: by x__ttf__BitMap_draw_text
/tmp/v/e.3354620427661911235.tmp.c:16549: by x__ttf__BitMap_draw_text_block
/tmp/v/e.3354620427661911235.tmp.c:16429: by x__ttf__TTF_render_Sokol_create_text_block
/tmp/v/e.3354620427661911235.tmp.c:17647: by main__draw_frame
/tmp/v/e.3354620427661911235.tmp.c:14789: by gg__gg_frame_fn
/home/scroot/devEnv/vlang/v/thirdparty/sokol/sokol_app.h:2244: by _sapp_call_frame
/home/scroot/devEnv/vlang/v/thirdparty/sokol/sokol_app.h:2375: by _sapp_frame
/home/scroot/devEnv/vlang/v/thirdparty/sokol/sokol_app.h:9281: by _sapp_linux_run
/home/scroot/devEnv/vlang/v/thirdparty/sokol/sokol_app.h:9325: by sapp_run
/tmp/v/e.3354620427661911235.tmp.c:14289: by sokol__sapp__run
/tmp/v/e.3354620427661911235.tmp.c:14906: by gg__Context_run
/tmp/v/e.3354620427661911235.tmp.c:17732: by main__main
/tmp/v/e.3354620427661911235.tmp.c:17888: by main

**Comment by rhzs** [comment]
@scroot You may open 100+ issues for other 100+ languages.

**Comment by changrui** [comment]
No font file.

**Comment by finomeng** [comment]
this is strange. UTF-8 should support Chinese very well.

use Chinese character as var and func name is a nice feature.

**Comment by penguindark** [comment]
Imprima and Regular does not support chinese chars, for the demo we used teh small latin fonts we found.

**Comment by medvednikov** [comment]
You have to use a chinese font to render chinese characters.

**Comment by cbracketdash** [comment]
Google's Noto font supports all languages. However, it is 1 GB so it might be wise to specify which languages the user needs before installation.
