### ISSUE TITLE
optional return function without return statement gives no error

### ISSUE THREAD

**Issue by kahsa** [vlang/v#8017]
**V version:0.2.1 a1c6723** 
**OS:archlinux** 

**What did you do?**
```v
fn foo() ?int {

}

fn main() {
    f := foo() or { return }
}
```

**What did you expect to see?**
compiler error or warning.
 
**What did you see instead?**
Compiled with no error nor warning.

**Comment by ntrel** [comment]
On Windows with today's git I get:
```
error: missing return at end of function `foo`
```

**Comment by zakuro9715** [comment]
Fixed on https://github.com/vlang/v/commit/3289dff7ff848d65fa2cace84af5fa1a08a7c100

@danieldaeschle Could you close this?
