### ISSUE TITLE
vweb gets slow with request body

### ISSUE THREAD

**Issue by fnetX** [vlang/v#8039]
**V version:** V 0.2.1 7231797
**OS:** Debian GNU/Linux

**What did you do?** 
Build a simple vweb project. I can give you access to the code, but it seems to be unrelated to the code itself. We used a time.StopWatch to measure our functions execution time in microseconds (~200), then removed all our logic ... It is reproducible even when querying URLs that return a 404, like /random_something

So what we actually do? We provide a HTTP request body to POST requests (also works for GET requests actually).

**What did you expect to see?**
Get a vweb response immediately, or at least after our logic executed ... ideally < 1ms, may be <10ms, even <100ms would be "somewhat okay".

 
**What did you see instead?**
When transferring an empty body, the response is there in <1ms, when having a response body / form, it is slow. 
It is as simple as querying a URL with "something" as a body.

I assume this is related to vweb parsing the form data, but we don't know how to profile this in detail.

**Comment by MohammadAliChraghi** [comment]
This problem is only for Chrome and will be solved soon

**Comment by fnetX** [comment]
The problem occurs with Firefox Browser and is also present in our test API calls made from V itself. Unless V also does double requests when using net.http.post, this is unrelated.

**Comment by JalonSolov** [comment]
Please add example code.  I have been testing various reports of slowness in vweb, and have been unable to reproduce them.  It may be related to your environment, which version of which V you have, which version of which C compiler you have, etc., etc.

**Comment by fnetX** [comment]
Thank you for the interest. I stripped it down to a really minimal example. And really: every POST request with body fails: https://codeberg.org/eventbike/vlang_plg/src/branch/main/2021-01-slow-vweb

Running `v test .` results in:
```
----------------------------------- Testing... ---------------------------------
FAIL 2438.796 ms server_test.v
Running a Vweb app on http://localhost:9080

/media/fralix/Daten/Dokumente/Projekte/eventbike_zero/vlang_plg/2021-01-slow-vweb/server_test.v:23: failed assert in function test_speed_body
Source  : `stopwatch.elapsed().milliseconds() < 200`
	 left value: 1001
	right value: 200


--------------------------------------------------------------------------------
     2439.215 ms <=== total time spent running V _test.v files
                 ok, fail, skip, total =     0,     1,     0,     1
```

Compiling with -prod and running manually doesn't work here. I'm glad if I can help with additional information. Just tell me what you want to know.

**Comment by JalonSolov** [comment]
Ok then.  I can definitely confirm this.  I tried both running your `server_test.v` and just running `curl` commands at the prompt, and it is definitely a problem either ways.

@emily33901 ??

**Comment by JalonSolov** [comment]
I don't know which revision solved this issue, but it works fine in the most recent `V 0.2.2 053d687`.

With your test file:
```
jalon@Ripper:~/aoc/server$ v test .
------------------------------------------------------------------------------------------- Testing... -----------------------------------------------------------------------------------------
 OK     281.225 ms server_test.v
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Summary for all V _test.v files: 1 passed, 1 total. Runtime: 281 ms.

jalon@Ripper:~/aoc/server$
```
With curl:
```
jalon@Ripper:~$ curl -X POST -d '' localhost:9080/test -w 'Total: %{time_total}s\n'
heyTotal: 0.000715s
jalon@Ripper:~$ curl -X POST -d 'body' localhost:9080/test -w 'Total: %{time_total}s\n'
heyTotal: 0.000768s
jalon@Ripper:~$
```

**Comment by fnetX** [comment]
It'd still be nice if someone could check that the issue that caused a high delay or a huge amount of computation time is actually resolved and not because concurrency was enabled in vweb (which as the point that dropped the big delay).

**Comment by emily33901** [comment]
> It'd still be nice if someone could check that the issue that caused a high delay or a huge amount of computation time is actually resolved and not because concurrency was enabled in vweb (which was the point that dropped the big delay).

Yeah thats probably something to do with io.read_all that I have been meaning to fix for a while. Just haven't found the time yet.
