### ISSUE TITLE
vdoc header module documentation is missing

### ISSUE THREAD

**Issue by mp81ss** [vlang/v#8044]
**V version:** 
v0.2.1 7231797

**OS:** 
Linux and windows

**What did you do?**
// this is my module documentation
module rec

pub fn ...
pub fn...
...

**What did you expect to see?**
_this is my module documentation_ in the generated html of module header
 
**What did you see instead?**
All functions documentation but not the modulo header one

**Command issued**
v doc -o doc rec.v

**Comment by Delta456** [comment]
Can you show a screenshot so it can be better to debug?

**Comment by donnisnoni** [comment]
@mp81ss You need to show the `rec.v` code

**Comment by mp81ss** [comment]
Should be more clear now:

``
// v doc -f html -o doc rec.v (rec should be an empty folder)
// I would like to see these 2 lines in HTML-generated header documentation
module rec

// fib Calculates the recursive fibonacci series
// `n` is the rank to pass to function
// I See these 3 lines only
pub fn fib(n int) int
{
    return if n < 2 { n } else { fib(n - 1) + fib(n - 2) }
}
``

**Comment by Larpon** [comment]
I think vdoc skips text above module in some cases since that's where the copyright headers normally is. If you include a README.md in the module root it will show up. (It might still be a bug)

**Comment by ArtemkaKun** [comment]
Hi,

still valid for the latest V (0.2.4, actual for 06.05.2022)
