### ISSUE TITLE
No-Format syntax

### ISSUE THREAD

**Issue by kahsa** [vlang/v#8045]
Determine a area where is not te be formated by vfmt.
For example
```v
/--
not edited area by vfmt
--/

```

At least for immaturity of vfmt

**Comment by JalonSolov** [comment]
I vote no on this.  If `vfmt` doesn't work on something, it needs to be reported and fixed, not ignored.

**Comment by kahsa** [comment]
@ JalonSolov  what is your answer to #8041

**Comment by kahsa** [comment]
I reported.
AND I WANT to keep it NOW.

**Comment by kahsa** [comment]
How do you achieve it NOW to keep it.

**Comment by kahsa** [comment]
Let me know your temporary soution JalonSolov

**Comment by JalonSolov** [comment]
The temporary solution is:  don't run `vfmt`.  As quickly as things get fixed, it shouldn't be a long delay.

**Comment by kahsa** [comment]
" don't run vfmt."???
And How to find immaturity and report it?
How can I do that?

**Comment by kahsa** [comment]
Show me you decent solution.

**Comment by kahsa** [comment]
I run and report it.
Not ignored.
Don't run??
Are you kiddign?

**Comment by JalonSolov** [comment]
Run `vfmt` manually to find the problem.  Report the problem in an issue on Github.  Don't run `vfmt` again until the issue is fixed.

**Comment by kahsa** [comment]
:man_shrugging

**Comment by kahsa** [comment]
🤷‍♂️

**Comment by kahsa** [comment]
I sugested partially avoiding formatting.
A man who formats other part, do you think eternally let it alone???
He WILL check it many times as if were fixed!

**Comment by serkonda7** [comment]
Allowing code parts where formatting is ignored would destroy one of the main benefits of V (and vfmt): consistent look of source code everywhere.
So the feature you request here, WILL NOT be implemented.

For now you have to go with the temporary solution by @JalonSolov.
But vfmt already respects user choice of newlines in a few areas and more will follow.

**Comment by kahsa** [comment]
OK, then I understand formatting issue can be reported as a bag.
