### ISSUE TITLE
vdoc doesn't display deprecation attributes in generated documentation

### ISSUE THREAD

**Issue by andogq** [vlang/v#8049]
vdoc doesn't reflect attributes within the generated documentation.

For example, [`os.cp_r`](https://github.com/vlang/v/blob/master/vlib/os/os.v#L27) has the `[deprecated]` attribute, but in the [generated documentation](https://modules.vlang.io/os.html#cp_r) there isn't any sign of this.

What the documentation currently looks like: 
![image](https://user-images.githubusercontent.com/63131525/104243782-37fbe180-54b5-11eb-996b-3f3377f80a33.png)

**Comment by nyx-litenite** [comment]
currently, working on this [here](https://github.com/nyx-litenite/v/tree/vdoc).

**Comment by danieldaeschle** [comment]
It does now
