### ISSUE TITLE
Reimplement Optionals & underlying compiler issues. Fixes: Interface with Optionals / Declaration Order issues | Struct with recursive optional field type | Unforeseeable Quirky Issues

### ISSUE THREAD

**Issue by joe-conigliaro** [vlang/v#8052]
### Reimplement Optionals
- Simplify
- Use the actual type for the `data` field.. not an array
- Sort / Fix Declaration Order Issues
---
### Interface with Optional
_reported by @hamdy_
```go
interface Executor {
 exec(cmd string) ?string
 file_write(path string, text string) ?
 file_read(path string) ?string
 file_exists(path string) bool
 remove(path string) ?
 download(source string, dest string) ?string
 upload(source string, dest string) ?string
 info() map[string]string
 environ_get() ?map[string]string
 ssh_shell(port int)?
}
```
> The issue was originally going to be fixed separately, but I decided to wait for this. **I didn't even specifically fix this issue in my branch, it just worked automatically**. Thats why it was the best option. I knew the other fix would work most of the time, but would still fail in many cases because of the underlying issues.

---
### Struct with recursive optional field type
_reported by @danieldaeschle_ 
```go
struct Human {
	child ?Human
}
```
This allows the struct type to be used in it's own field type if is an Optional

---

I think I'm missing some things here, either way I'm quite sure this will fix many other quirky issues.

**Comment by kahsa** [comment]
Super welcome fixing interface issue, have been longing for!

**Comment by joe-conigliaro** [comment]
> Super welcome fixing interface issue, have been longing for!
Fabtas


ic! In `qqqq=q`

**Comment by joe-conigliaro** [comment]
> Super welcome fixing interface issue, have been longing for!

Fantastic! I will have it sorted out soon

**Comment by ntrel** [comment]
> struct Human {
	child ?Human
}

Ideally `?Type` would be a value type that doesn't use heap allocation (is it?). If it's a value type then a field of type `?Human` should be treated similarly to one of `Human`, i.e. not compile because it is recursive.

**Comment by danieldaeschle** [comment]
> > struct Human {
> > child ?Human
> > }
> 
> Ideally `?Type` would be a value type that doesn't use heap allocation. If it's a value type then a field of type `?Human` should be treated similarly to one of `Human`, i.e. not compile because it is recursive.

currently it's exactly like that but it will be changed.... i don't understand why tbh.

**Comment by ArtemkaKun** [comment]
Since optional fields for structs were implemented and language (version - commit ba091a36dd722cf47b426f5716d07a35beb5331f) supports optional fields in interfaces as well, I will move the `Struct with recursive optional field type` to a separate issue

**Comment by dumblob** [comment]
@ArtemkaKun could you link the new issues you created? Thanks!

**Comment by ArtemkaKun** [comment]
New issue for recursive optional field #16959
@dumblob Done 👍
