### ISSUE TITLE
Pass by value vs pass by reference

### ISSUE THREAD

**Issue by haifenghuang** [vlang/v#8055]
In the `v/token.v`, the `can_start_type` is marked with reference `(tok &Token)`:

```v
pub fn (tok &Token) can_start_type(builtin_type_names []string) bool {
	match tok.kind {
		.name { return tok.lit[0].is_capital() || tok.lit in builtin_type_names }
		// Note: return type (T1, T2) should be handled elsewhere
		.amp, .key_fn, .lsbr, .question { return true }
		else {}
	}
	return false
}
```

The documents said:

```
You can ensure that the struct is always passed by reference by adding &.
```

So I'm confused about using reference?  why `can_start_type` use reference?

Could you please explain more about `reference` usage? 
when should I use `reference`?
And What is the advantage of using `reference` over value(non reference)?

**Comment by ntrel** [comment]
> why can_start_type use reference?

To avoid passing the receiver by value. A receiver is just the first argument to the C function which V generates for a method. If a struct is bigger than a pointer type, it *may* be more efficient to pass it by reference. But that depends how it is used:

https://stackoverflow.com/a/26552687/11653112

I recently raised the difficulty of deciding automatically (which V doesn't do yet but Alex plans it):

(from https://github.com/vlang/v/pull/7872#discussion_r554121958):

> That optimisation probably shouldn't be done on size alone. Usage inside the function can effect whether a reference or value is best. Is the compiler really going to analyse all the factors? Will there be a way to override the compilers choice?

**Comment by ntrel** [comment]
> pub fn (tok &Token) can_start_type(builtin_type_names []string) bool {

Just for anyone wondering about this method I added recently, it should probably be removed - I have a pull open that avoids its only current use.

**Comment by haifenghuang** [comment]
I understand what you're saying. And still can not fully understand some codes. For example, in [vorum](https://github.com/vlang/vorum) repo, the `post.v` file has code as below:

```v
fn (app &App) inc_post_views(post_id int) bool {
	app.db.exec('update posts set nr_views=nr_views+1 where id=$post_id')
	return true
	//db := app.db
	//db.update Post set nr_views = nr_views + 1 where id = post_id
}

fn (app App) find_comments(post_id int) []Comment {
	rows := app.db.exec('select * from comments where post_id=$post_id order by id')
	mut comments := []Comment
	for row in rows {
	         text := row.vals[2]
	         name := row.vals[3]
		comments << Comment {
			name: name
			text: text
			time: time.unix(row.vals[5].int()).clean()
		}
	}
	return comments
}

fn (app App) retrieve_post(post_id int) ?Post {
	db := app.db
	return db.select from Post where id == post_id limit 1
}

```

Why only `inc_post_views` function is using reference, and the other two functions `find_comments` and `retrieve_post` are using values?

**Comment by ntrel** [comment]
> Why only inc_post_views function is using reference, and the other two functions find_comments and retrieve_post are using values?

Because IIRC the docs say that V will automatically make a parameter a reference type if that is faster. That is not implemented, so without `&` it is just pass by value. My argument is that the automatic feature is not simple and may make the wrong choice. So I always write a reference if I think V should use a reference, I don't rely on the automatic feature being implemented perfectly in the future.

**Comment by haifenghuang** [comment]
Now I'm a bit understand. I also think that's a complicate thing for the V to automatically decide what to use. Thanks a lot for your explanation.
