### ISSUE TITLE
vlib depends on libc

### ISSUE THREAD

**Issue by vktec** [vlang/v#807]
On the [homepage](https://vlang.io) it is implied that V's only current dependency is a C compiler. However, from quick inspection of vlib (specifically os/os_mac.v) it appears that there is also a dependency on libc.

In future, I would hope that V is able to work without a C library, like how Go is.
For now, it might be worth adding to the homepage that V requires linking against a C library.

**Comment by medvednikov** [comment]
Hi

As of Go 1.12, Go links to libc on macOS, Windows, Solaris, and maybe more. libc is the stable API on these systems, it's always present there, there's nothing wrong with using it. I wouldn't count it as a dependency on these systems.

In the future V will allow building Linux/*BSD programs without libc.

**Comment by vktec** [comment]
Go only links to libc when cgo is enabled, as far as I know

**Comment by vktec** [comment]
Oh, I misread your comment. I suppose on systems with less stable syscall interfaces, using libc makes sense.
