### ISSUE TITLE
Debugger support

### ISSUE THREAD

**Issue by haifenghuang** [vlang/v#8080]
It seems that `V` has no debugger. I'm now using VS code for editing `V` source code, and installed the `V` extension for VS code,
but it is incomplete. e.g. When the cursor is on a `struct` name or a function call, I want to jump to the definition of the symbol, but just cannot  do it. And further,  if no debugger is available, then I think that will limit `V`'s  promotion.

**Comment by kahsa** [comment]
You can get more latest imfomation about that here https://discord.com/channels/592103645835821068/784039809459027979

**Comment by kahsa** [comment]
And here https://github.com/vlang/vscode-vlang/releases

**Comment by kahsa** [comment]
This may help you https://github.com/vlang/vscode-vlang/issues/172

**Comment by kahsa** [comment]
And vls is now highly unstable since it is alpha stage yet.
So I reccomend to use 0.1.4 whish is relatively well work with break point support.
For more infomation, ask for in dicord.

**Comment by kahsa** [comment]
Debugging infomation can be found here now.
https://github.com/vlang/v/blob/master/doc/docs.md#debugging-generated-c-code

**Comment by haifenghuang** [comment]
Thanks a lot for the information. I'll have a try.

**Comment by danieldaeschle** [comment]
> And vls is for now highly unstable since it is alpha stage yet.
> https://github.com/vlang/vls
> So I personally reccomend to use 0.1.4 which is _relatively_ well work with break point support and almost without vls which is so buggy for now.
> https://github.com/vlang/vscode-vlang/releases

you don't need to enable vls. You can use 0.1.7.

**Comment by kahsa** [comment]
0.1.7 tell me `There is no formatter for 'v' files installed.`

**Comment by danieldaeschle** [comment]
ah ok yes. because the formatter is in vls integrated.

**Comment by danieldaeschle** [comment]
there will be feature flags in vls soon, then you can use the formatter only.
