### ISSUE TITLE
Array "_push" operator weird behavior

### ISSUE THREAD

**Issue by Yarila682** [vlang/v#809]
**V version:** 
0.1.9
**OS:** 
Linux Mint 18.2

**What did you do?**
```Go

fn main(){

  mut arr := [f32(50),50,100]

  mut x:= f32(50)

  arr._push(x)
  println('arr._push(x) passed')

  arr << 50
  println('arr << 50 passed')

  arr._push(50)   //<== Segmentation fault here. 
}

```

**What did you expect to see?**

Same behavior for all three cases. 
 
**What did you see instead?**

Segmentation fault

**Comment by medvednikov** [comment]
Thank you for reporting this. `_push` is supposed to be private and not called by the user. Fixed.
