### ISSUE TITLE
silent mode fuzzing fails with removed trailing whitespace in regex example

### ISSUE THREAD

**Issue by serkonda7** [vlang/v#8099]
**V version:** V 0.2.1 8a8978f

**What did you do?**
I saved `regex_example.v` with two trailing tabs in the lines 59, 62 and 65 removed.

**What did you expect to see?**
No fails.
 
**What did you see instead?**
The silent mode fuzzing job fails.

**Comment by JalonSolov** [comment]
Can you test this again with current V, to see if it still fails?

**Comment by serkonda7** [comment]
It no longer fails.
