### ISSUE TITLE
Returning modified version of object -- syntax

### ISSUE THREAD

**Issue by cdunn2001** [vlang/v#81]
> Another way to modify an object is simply to return a modified version
```go
// TODO: this syntax is not implemented yet  
fn register(u User) User { 
	return { u, is_registered: true } 
}
```
I think "u," should use something other than comma, for readability. Maybe `{u | is_registered: true}`, which looks like math, "u such that ...".

**Comment by medvednikov** [comment]
Yes, I don't like the comma either. `|` looks nice.

**Comment by medvednikov** [comment]
`|` will be used instead of `,`. Docs have been updated.

**Comment by mindplay-dk** [comment]
It's supposed to look like a union? Probably this makes more sense:

    return u | { is_registered: true }

That is, it's an operation (a union) of `u` and additional property-set `{ is_registered: true }`.

You probably referenced Elm records for this syntax? It surprised me there, too - placing the operator *inside* one of the operands seems like somewhat of an odd choice.

I couldn't find an example, but I seem to recall Scala looking more like that...?

Alternatively maybe spreads like in Javascript?

    return { ...u, is_registered: true }

This would potentially allow (now or in the future) for multiple operands as well:

    return { ...a, ...b, foo: 'bar' }

**Comment by mindplay-dk** [comment]
> This would potentially allow (now or in the future) for multiple operands

Well, strike that, it of course doesn't make sense with objects of the same type - never mind! ;-)

**Comment by ntrel** [comment]
> `u | { is_registered: true }`

+1, this reads less ambiguously. This syntax could also allow omitting field names: `u | {5}`. {u | 5} could be just a programmer mistake where they meant to use integer bitwise `|` to initialise the first field.

**Comment by mindplay-dk** [comment]
> This syntax could also allow omitting field names: `u | {5}`

I don't understand, what would that mean?

How would it know what to do with the value `5`?

**Comment by ntrel** [comment]
I meant a different struct, not `User`, sorry:
```rust
struct S {
  i1 int
  i2 int
}
s := S{3,4}
```
Then `s | {5}` would equal `S{5,4}`. With the existing syntax, `{s | 5}` is less clear, it requires the reviewer to know `s` is a struct to understand the code. If `s` was an integer the syntax would also be valid, but it wouldn't mean struct modification. With your syntax, the coder can infer that `s` must be a struct (for the code to be valid).
