### ISSUE TITLE
checker reports `missing main fn error` on wrong file

### ISSUE THREAD

**Issue by nedpals** [vlang/v#8103]
**V version:** Latest V
**OS:** Ubuntu 20.04

**What did you do?**
Wrote a simple code for the reproduction of a bug:
```v
// test.v
module main

import nedpals.vex.ctx

// fn main() {}
```

**What did you expect to see?**
Report the error on the `test.v` file
 
**What did you see instead?**
Reported on the first file of the imported module
![image](https://user-images.githubusercontent.com/7358345/104564375-cc1ca300-5685-11eb-92fe-65877518cdbc.png)

**Comment by danieldaeschle** [comment]
I can't reproduce this anymore
