### ISSUE TITLE
Need Better Documentation

### ISSUE THREAD

**Issue by darkoverlordofdata** [vlang/v#811]
What doesn't, right? But in the FAQ:

    Is V going to change a lot before v1.0?
    No. The things you can learn from documentation today are going to stay the same...
    
The problem is, there isn't much documentation to learn from. So I learn from reading the existing code. And so today, after refreshing v, I get 'bad token `#` (embedding C code is no longer supported)'. I agree, technically that isn't covered in the documentation. But - there isn't much documentation to learn from. Catch-22.

**Comment by medvednikov** [comment]
`#` is not in the language, that's why it's not documented :)

If you can remember something else missing, I'll update the docs.

**Comment by darkoverlordofdata** [comment]
I understand, but there is nothing in the docs about how to do c interop.

**Comment by medvednikov** [comment]
https://vlang.io/docs#calling_c

**Comment by darkoverlordofdata** [comment]
Doh! I see it now. Sorry. I missed that.
