### ISSUE TITLE
compile-time type test: $if T is SomeType

### ISSUE THREAD

**Issue by amoyyy** [vlang/v#8115]
will example below  or `match` on generic type be possible in future? At present, I can realize similar function using sumtype, I wonder if there are better realizations now or in future? Thanks for any suggestions provided.
```
fn get_array<T>() []T{
	mut res := []T{}
	$if T is string {
		res << T("simple string")
	}$else $if T is f64 {
		res << T(1.0)
	}$else $if T is int {
		res << T(1)
	}$else { 
		// warning or nothing
	}
	return res
}
```

**Comment by medvednikov** [comment]
Yes, this will be possible.

**Comment by amoyyy** [comment]
Really looking forward to it!
