### ISSUE TITLE
Can't compile a simple v file on Windows

### ISSUE THREAD

**Issue by Tembocs** [vlang/v#813]
I have compiled v successful on Windows 10 x64 using MinGW-w64. I then placed in ```C:\tools\v``` directory and set the path to this directory. Calling ```v version``` successful gives version number. I then tried to compile a simple v file with content as seen below:

```
fn main() {
	println('Hello World!')
}
```
Calling ```v run somefile.v``` give the message below
```
Looks like you are running V for the first time.
V repo not found.
Go to https://vlang.io to download V.zip or install V from source.
```
My understanding is that v is a compiler, and therefore nothing more is needed to be able to compile a v file. What am I missing? How should one compile a v file?

**Comment by medvednikov** [comment]
Should work fine with V 0.1.10.

You can download it from the home page.

**Comment by Tembocs** [comment]
@medvednikov, thanks, this works.
