### ISSUE TITLE
vfmt: if condition wrap unreadable

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#8130]
**What did you do?**
```v
fn main() {
    this_is_very_long := true
    another_very_long_thing_which_will_get_wrapped := false
    blahaaaaaaaaa := false
    if this_is_very_long && another_very_long_thing_which_will_get_wrapped && true && false && blahaaaaaaaaa {
        println('true')
    }
}
```

**What did you expect to see?**
either this:
![image](https://user-images.githubusercontent.com/30751516/104729835-51ad5b00-5739-11eb-8ea7-7237d07ef72f.png)
or this:
![image](https://user-images.githubusercontent.com/30751516/104729846-5540e200-5739-11eb-8c7a-8c0c069a24fc.png)

 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/30751516/104729854-583bd280-5739-11eb-954e-eabeb6333484.png)

since `blahaaaa` and `println` are on the same indent it looks like that `blahaaa` is a stmt in the body of `if`.

**Comment by danieldaeschle** [comment]
it should be:
```v
if foo &&
    bar
{
    kek()
}
```

**Comment by JalonSolov** [comment]
Yet another reason I always preferred the curly brace on the next line (BSD-style) instead of at the end of the line.  However, V only supports curly brace at the end of the line, so your last example _can't_ work.

**Comment by ntrel** [comment]
> V only supports curly brace at the end of the line

You mean vfmt, v does support separate line opening brace.

**Comment by JalonSolov** [comment]
> 
> 
> > V only supports curly brace at the end of the line
> 
> You mean vfmt, v does support separate line opening brace.

Yes, but it is recommended that you run vfmt early and often.  It is required that you run it before a PR can be merged, since it is a CI check.

**Comment by danieldaeschle** [comment]
> Yet another reason I always preferred the curly brace on the next line (BSD-style) instead of at the end of the line. However, V only supports curly brace at the end of the line, so your last example _can't_ work.

it works, see my PR. it's the one Alex wants.
