### ISSUE TITLE
Compiling hello_world.v on win10 with v0.1.10 still failed

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#814]
**V version:**
0.1.10 

**OS:** 
win10

**What did you do?**
Download v from homepage, store files to C:\vlang, and set the path
Copy hello_world.v to C:\vlang and then compile it.

**What did you expect to see?**
Successful compilation
 
**What did you see instead?**
See the picture.

![image](https://user-images.githubusercontent.com/47302112/60389167-f8c59580-9ab4-11e9-975f-ef44adc4864c.png)

**Comment by SleepyRoy** [comment]
@medvednikov

**Comment by medvednikov** [comment]
That's very strange. Works for me and other people. Can you copy paste the contents of  `C:/vlang` and `C:/vlang/vlib/builtin`?

**Comment by SleepyRoy** [comment]
I had another try. I downloaded the latest clone and manually compiled v.c by mingw64.
This time compiling hello_world.v succeeded.
But I got the same problem as #815 when adding "run".

**Comment by medvednikov** [comment]
If you manually build it again, `run` will work.

I'll add a "makefile" for Windows soon, so that manual compilation is easier.

**Comment by SleepyRoy** [comment]
Great. 
BTW, just now I tried "v -o v compiler" to bootstrap, but failed.

![image](https://user-images.githubusercontent.com/47302112/60390105-8eb5ec00-9ac6-11e9-9900-70956262d166.png)

**Comment by medvednikov** [comment]
Yeah, this one I'm getting as well. Will be fixed asap.

**Comment by SleepyRoy** [comment]
Thanks. It's still very happy to successfully build my first v program on windows!
And now I'm curious about why the v binary downloaded didn't work...

**Comment by SleepyRoy** [comment]
Tried again. Got same results.
V binary manually built from v.c works, but the downloaded one doesn't and the error is the same.

**Comment by changrui** [comment]
my situations: extract v.zip to d:\vlang, set VROOT and PATH to it, then `v run hello_world`, i got `Looks like you are running V for the first time.
V repo not found. Go to https://vlang.io to download V.zip
or install V from source.`  It is same as v0.1.9. why?

**Comment by medvednikov** [comment]
I'll update the binary, and it will be fixed.

**Comment by aguspiza** [comment]
PR #817 should fix windows newline problems

**Comment by medvednikov** [comment]
Yes, all fixed now.
