### ISSUE TITLE
[0.1.10 / Windows] "$ v run <file>" compiles it, but doesn't run it

### ISSUE THREAD

**Issue by MrOnlineCoder** [vlang/v#815]
**V version: 0.1.10** 
**OS: Windows 7** 

**What did you do?**
Build V.
```
$ v run examples/hello_world.v
```

**What did you expect to see?**
Executed Hello World program.
 
**What did you see instead?**
hello_world.exe has been successfully compiled and was in folder, but V failed to run it because of including Unix './' in path ([main.v:380](https://github.com/vlang/v/blob/master/compiler/main.v#L380)).

Console output:
```
# v run hello_world.v 
============ running hello_world ============
"." is not recognized as an internal or external command, operable program or batch file problem.
"." is not recognized as an internal or external command, operable program or batch file problem.
ret not 0, exiting
```

**Comment by medvednikov** [comment]
Fixed.
