### ISSUE TITLE
A command line flag to print AST

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#8158]
A simple tool that just calls str() on each node.

`v -print-ast file.v`

```
Module {
 ....
}
```

**Comment by helto4real** [comment]
Yes this would be very useful!

**Comment by spytheman** [comment]
`vast` - https://github.com/lydiandy/vast/ already does something like this

**Comment by nedpals** [comment]
Closed. Implemented in https://github.com/vlang/v/commit/e09f0234ea629e4219cd2d88ff066231fbb91e73
