### ISSUE TITLE
smartcast doesn't check mutability

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#8162]
**V version:** 
master

**OS:** 
win10

**What did you do?**
```V
struct Empty {}

struct Node {
	value f64
	left  Tree
	right Tree
}

type Tree = Empty | Node

fn main() {
	tree := Tree(Empty{})
        println(typeof(tree).name)
	if tree is Empty {
		println(typeof(tree).name)
	}
}
```

**What did you expect to see?**
```
Tree
Tree
```
`tree` is immutable so smartcast shouldn't work here.
 
**What did you see instead?**
```
Tree
Empty
```

**Comment by danieldaeschle** [comment]
@ntrel

**Comment by yuyi98** [comment]
> // smartcast either if the value is immutable or if the mut argument is explicitly given
`			if (!is_mut || expr.is_mut) && !is_already_casted {
`

Why use `if the value is immutable`?

**Comment by danieldaeschle** [comment]
only immutable values can be smartcastet. Otherwise it would be unsafe.

**Comment by Gladear** [comment]
As far as I see, this works correctly.
Can the issue be closed ?

**Comment by yuyi98** [comment]
It's right according to this logic, so I also agree to close this issue.
