### ISSUE TITLE
C error. This should never happen.

### ISSUE THREAD

**Issue by jacobsalmela** [vlang/v#8175]
```
vexe mtime: 2021-01-17 20:45:06
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.1 84de462.fafd949

Git version: git version 2.28.0
Git vroot status: 0.2-513-gfafd9497
.git/config present: true
thirdparty/tcc status: thirdparty-macos-amd64 689c8a02
```

**What did you do?**
Wrote some V, then: `v run myapp.v`

**What did you expect to see?**
I knew I had bad syntax as I'm just learning this, so I didn't expect anything in particular.  

The line that breaks this is the comma after 'Goodbye'.

```
match stdin {
	'exit' { println('Goodbye.'), exit(0) }
	else { println('vvvvvvvvvvvv') }
}
```
**What did you see instead?**
```
==================
             ^
/var/folders/27/05tmmh9n7wg2yzk4t7n87rk80000gn/T/v/v.14372769432667815202.tmp.c:990:7: error: field has incomplete type 'void'
        void arg1;
             ^
2 errors generated.
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by kruzus** [comment]
Hello, 

Was this your first compile error as you ran your first V program? If so, delete the `./v.exe` if you're on WIN or just `v` binary on linux/mac. Remove it, and run `./make.bat` this will create a `v` binary. Proceed with running from the V root folder `./v.exe symlink` (now this is assuming you're on WIN and have clang, gcc, or visual studio.). This will add `v` to PATH. 


I had a similar issue when I just wanted to try "hello world" but I got similar error msg to yours. I did the steps as I mentioned to you and it worked! 

Good luck, tag me here if you need help we can figure something out! Cheers!

**Comment by jacobsalmela** [comment]
Thanks.  I'll close this for now.
