### ISSUE TITLE
make or branch in array/map-access for non-exist key-value pair work

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#8183]
**V version:**
master
 
**OS:** 
win10

**What did you do?**
```V
fn main() {
	m := map[string]int
	println(m['hi'])
}
```

**What did you expect to see?**
V error: no such key in map
 
**What did you see instead?**
`0`

**Comment by Delta456** [comment]
Map keys in V are zero-ed value by default.

**Comment by SleepyRoy** [comment]
@Delta456 But here I was accessing a non-exist key, shouldn't this give error?

**Comment by Delta456** [comment]
It should be working like that only, like how its in [`Go`](https://play.golang.org/p/EybwxanA7jo).

**Comment by SleepyRoy** [comment]
@Delta456 Interesting. Then how can I write code to know if a key exists?

**Comment by Delta456** [comment]
You just need to do `key in map` :)

**Comment by smartiniOnGitHub** [comment]
Hi all, otherwise wouldn't it be possible to use/add a get method that returns an optional ?

**Comment by SleepyRoy** [comment]
@smartiniOnGitHub I like this idea.

**Comment by smartiniOnGitHub** [comment]
@SleepyRoy as a sample, take a look at [Scala Maps](https://docs.scala-lang.org/overviews/collections-2.13/maps.html) (always a great source of inspiration) :-) . Bye

**Comment by Delta456** [comment]
> 
> 
> Hi all, otherwise wouldn't it be possible to use/add a get method that returns an optional ?

I think we will have `m['get'] or {}` and @UweKrueger is working on it.

**Comment by UweKrueger** [comment]
Not in particular - but it's a good idea. Actually @medvednikov has already implemented this syntax for the parser in 1f74f83, however the `or` branch seems to be ignored in the code generation, for now.
