### ISSUE TITLE
Compiling problems on Win7

### ISSUE THREAD

**Issue by kingofoz** [vlang/v#819]
**V version:** 
**OS: windows 7 x64

**What did you do?**
compiling hello world.

**What did you expect to see?**
compiling should be no errors.
 
**What did you see instead?**
several errors.
![win7](https://user-images.githubusercontent.com/9476604/60390668-0c511a80-9b0e-11e9-87ff-908c22d67edb.png)

**Comment by shanghuo** [comment]
Emm... I also encountered the same problem, I wonder if the landlord has solved it.

my os is "windows 7 x64"

i want runing:

> fn main() {
    println('hello')
}

but...

> Looks like you are running V for the first time.
Setting VROOT to "C:\vlang".
check()
next token = `EOF`
pass=0 fn=``
panic: main.v:1
expected `module` but got `EOF`

(English is not my native language; please excuse typing errors. And if you speak Chinese, please email/PM me; I may need assistance translating my question.)

**Comment by SuperFola** [comment]
Must be related to #834

**Comment by medvednikov** [comment]
This was fixed.
