### ISSUE TITLE
`net.dial_tcp()` doesn't work on Androd.

### ISSUE THREAD

**Issue by kahsa** [vlang/v#8196]
**V version: 0.2.1 5ddb709** 
**OS: Linux** 

**What did you do?**
```v
import net
import io
import gg
import gx

struct App {
mut:
	gg &gg.Context
}

fn main() {
	mut app := &App{
		gg: 0
	}
	app.gg = gg.new_context(
		width: 600
		height: 300
		use_ortho: true
		create_window: true
		frame_fn: frame
		user_data: app
	)
	test()
	app.gg.run()
}

fn frame(app &App) {
	app.gg.begin()
	app.gg.draw_rect(10, 10, 100, 30, gx.blue)
	app.gg.end()
}

fn test() {
	println('start')
	mut c := net.dial_tcp('192.168.11.2:12345') or { panic(err) }
	println('connected')
	c.write_str('Hello!\n')
	mut reader := io.new_buffered_reader(reader: io.make_reader(c))
	res := reader.read_line() or { panic(err) }
	println(res)
	c.close()
}
```
Sever on ArchLinx `nc -l -p 12345` runs which IP is 192.168.11.2

1) Client `nc 192.168.11.2 12345` from the same machine works.

2) On Android device's termux `nc 192.168.11.2 12345` works correctly.

2) Above gg code works on ArchLinux.

**What did you expect to see?**
**What did you see instead?**

4) But on Android device, loops below and doesn't reach to "connected".

```
01-19 13:30:42.696 28598 28598 I v_test_app: start
01-19 13:30:42.697 28598 28598 I v_test_app: print_backtrace_skipping_top_frames is not implemented. skipframes: 3
```

**Comment by Larpon** [comment]
@kahsa - you can try setting:
```xml
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```
Like so:
![image](https://user-images.githubusercontent.com/768942/105018714-9bea5100-5a45-11eb-85e4-b07af26f6a9e.png)

In the AndroidManifest.xml found in `vab/platforms/android/` and then build the app again (use the `-nocache` flag for now if you have an old build of the app already)

**Comment by kahsa** [comment]
Oh, Thanks! Larpon.
It worked!
It's been a while and might misunderstood the manifest I copied from with my own setting works.
