### ISSUE TITLE
msgpack.decode()

### ISSUE THREAD

**Issue by cdunn2001** [vlang/v#82]
We already have `json.decode()`. After the early release, I'd volunteer to add `msgpack.decode()` to the language in the same way as you've already implemented `json`.

**msgpack** is much easier to parse than **json**, so it's hardly any extra bloat. It's practically 1:1 with **json**, and it's quicker to parse and to encode. Its integer compression is almost as good as protobuf, and it's faster.

**Comment by medvednikov** [comment]
json decoding being part of the compiler is a temporary thing.

V will have strong compilation time capabilities soon after open-source release.

So everyone will be able to implement their favorite protocol :)

**Comment by cdunn2001** [comment]
Good. Not like Go, where the intrinsic datastructures are very efficient but user-defined containers suffer.
