### ISSUE TITLE
JSON encode erroneous

### ISSUE THREAD

**Issue by ozanmuyes** [vlang/v#8206]
Hello and thank you for the language. I stumbled upon this repository, read a bit, loved it's mantra and started to learn the language. While I was reading the documentation I thought to myself why not do a non-trivial (yet silly) program which gets one information from stdin and save to a file as JSON. I think I'm importing the `json` module from the standard library (vlib right?) - so no C binding / interop. Below what I wanted to achieve and instead, what I've encountered with.

Addendum: I've installed V compiler [from source](https://github.com/vlang/v#linux-macos-windows-bsd-solaris-wsl-android-raspbian). And after getting the error, while creating the issue I saw and did `v up`;

```sh
> v up             
Updating V...
V self compiling ...
V built successfully!
Current V version:
V 0.2.1 b3a4f74, timestamp: 2021-01-19 20:47:09 +0200
```

**V version: V 0.2.1 6c87c25.b3a4f74** 
**OS: macos, macOS, 11.0.1, 20B29** 

**What did you do?**

I ran `v run name2json.v` on the following file;

<details>
  <summary>name2json.v</summary>

  ```v
  // name2json.v

  import readline
  import json

  struct Person {
    first_name string [json: firstName]
    last_name string [json: lastName]
    age int
  }

  fn create_person_from_stdin() &Person {
    mut rl := readline.Readline{}

    first_name := rl.read_line('Name: ') or {
      panic(err)
    }
    last_name := rl.read_line('Surname: ') or {
      panic("oh no")
    }
    age_str := rl.read_line('Age: ') or { '123' }
    age := age_str.int()

    p := &Person{
      first_name: first_name
      last_name: last_name
      age: age
    }

    return p
  }

  fn main() {
    p := create_person_from_stdin()
    json := json.encode(p)

    // TODO
  }
  ```
</details>

**What did you expect to see?**

I was expecting no any output at all, no error and such, just the program exit with 0.
 
**What did you see instead?**

```sh
name2json.v:33:3: warning: unused variable: `json`
   31 | fn main() {
   32 |   p := create_person_from_stdin()
   33 |   json := json.encode(p)
      |   ~~~~
   34 | 
   35 |   // TODO
==================
                                       ^
/var/folders/x1/r7q13kt92b362j_6ywg43qtw0000gn/T/v/name2json.12886075929167356249.tmp.c:1172:47: error: expected ';' after top level declarator
Option_main__Person* json__decode_main__Person*(cJSON* root);
                                              ^
                                              ;
/var/folders/x1/r7q13kt92b362j_6ywg43qtw0000gn/T/v/name2json.12886075929167356249.tmp.c:1987:1: error: unknown type name 'Option_main__Person'; did you mean 'Option_main__Person_ptr'?
Option_main__Person* json__decode_main__Person*(cJSON* root) {
^~~~~~~~~~~~~~~~~~~
Option_main__Person_ptr
/var/folders/x1/r7q13kt92b362j_6ywg43qtw0000gn/T/v/name2json.12886075929167356249.tmp.c:81:40: note: 'Option_main__Person_ptr' declared here
typedef struct Option_main__Person_ptr Option_main__Person_ptr;
                                       ^
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

So as I was not working with C interop I thought I should create an issue.

**Appendix A**

Aforementioned file is at [here](https://gist.github.com/ozanmuyes/465c81354ba8d4ba1e68bcecdec168a5).

**Appendix B**

`v -cg` command isn't working;

```sh
> v -cg
v : unknown command
Run "v help" for usage.
```

**Comment by changrui** [comment]
Got it : change to value not pointer: `j := json.encode(*p)` is OK.

**Comment by changrui** [comment]
```
Name: aaa
Surname: hhh
Age: 23
{"firstName":"aaa\n","lastName":"hhh\n","age":23}
```

**Comment by changrui** [comment]
?user.surname.trimspace()?

**Comment by cedriking** [comment]
> Got it : change encode parameter to value not pointer: `j := json.encode(*p)` is OK.

Thanks! That worked for an issue similar to yours!

**Comment by Dialga** [comment]
This no longer produces a C compiler error.

```
$ v i8206.v
i8206.v:35:3: warning: unused variable: `json`
   33 | fn main() {
   34 |   p := create_person_from_stdin()
   35 |   json := json.encode(p)
      |   ~~~~
   36 |
   37 |   // TODO
```
With that fixed (change `json` to `_`) and there is no output or error anymore.

**Comment by Dialga** [comment]
Fixed by a commit in https://github.com/vlang/v/pull/10844.
