### ISSUE TITLE
V just doesn't work

### ISSUE THREAD

**Issue by cmd410** [vlang/v#8249]
**V version: V 0.2 30c0659** 
**OS: Windows 10** 

I decided to try V out following [this tutorial](https://github.com/vlang/v/blob/master/tutorials/building-a-simple-web-blog-with-vweb.md). So I created a file `blog.v` with this content:
```v
// blog.v
module main

import vweb

struct App {
	vweb.Context
}

fn main() {
	vweb.run<App>(8081)
}

pub fn (mut app App) index() vweb.Result {
	return app.text('Hello world from vweb!')
}

pub fn (app &App) init() {
}

pub fn (app &App) init_once() {
}
```
Then entered command `v run blog.v`

Theoretically, it should compile and run the program, right?
Instead it printed the following error:
```
C:\bin\v\vlib\strconv\number_to_base.v:3:1: error: const declaration is missing parentheses `( ... )`
    1 | module strconv
    2 |
    3 | const base_digits = '0123456789abcdefghijklmnopqrstuvwxyz'
      | ~~~~~
    4 |
    5 | // format_int returns the string representation of the number n in base `radix`
```
Seems like some kind of syntax error in standard library, strange.
My first guess was to __update v__, so i typed `v up` and pressed enter, and here it is again:
```
cannot compile `C:\bin\v\cmd\tools\vup.v`:
C:\bin\v\vlib\strconv\number_to_base.v:3:1: error: const declaration is missing parentheses `( ... )`
    1 | module strconv
    2 |
    3 | const base_digits = '0123456789abcdefghijklmnopqrstuvwxyz'
      | ~~~~~
    4 |
    5 | // format_int returns the string representation of the number n in base `radix`
```
Okay then... guess I have to do it by hand. And I went to vlang.io and donwloaded the latest version(V 0.2 30c0659).
And... I still get the same errors, on pretty much every command, it just cannot compile anything.
Well then, I tried to fix this syntax error myself replacing:
```v
const base_digits = '0123456789abcdefghijklmnopqrstuvwxyz'
```
with 
```v
const (base_digits = '0123456789abcdefghijklmnopqrstuvwxyz')
```
in `vlib\strconv\number_to_base.v`
in hopes that it will actually make it work, but it didn't..(
Instead I got another error:
```
C:\bin\v\vlib\time\operator.v:5:18: error: unexpected `==`, expecting `(`
    3 | // operator `==` returns true if provided time is equal to time
    4 | [inline]
    5 | pub fn (t1 Time) == (t2 Time) bool {
      |                  ~~
    6 |     if t1.unix == t2.unix && t1.microsecond == t2.microsecond {
    7 |         return true
```
__It seems like vlib is full of code that cannot compile__ and I just don't know what to do about it. Even running `v doctor` to fill in version and os in this issue failed with the same errors.
I also tried installing V from source.
Unfortunatelly build also errored, here's [the output](https://pastebin.com/cA83W3B9).
It just doesn't work.

**Comment by Delta456** [comment]
Its because there are some bootstrapping problems from that release. its weird that it cannot download TCC from the repository. I think we should do a new release now. What you think? @medvednikov

**Comment by spaceface777** [comment]
run `.\make.bat -tcc`, that should make V compile properly.

**Comment by cmd410** [comment]
> run `.\make.bat -tcc`, that should make V compile properly.

it also results in error:
```
PS C:\bin\v> .\make.bat -tcc
Updating TCC
 > Syncing TCC from https://github.com/vlang/tccbin
File not found

Updating vc...
 > Sync with remote https://github.com/vlang/vc

Building V...
 > Attempting to build v_win.c with TCC


Exiting from error
```

**Comment by danieldaeschle** [comment]
@spytheman what does File not found mean?

**Comment by serkonda7** [comment]
@Delta456 we already have the 0.2.1 release that should fix bootstrapping, but it is obviously not on the website.

**Comment by Delta456** [comment]
But then operator overloading was implemented in 0.2.2.

**Comment by spytheman** [comment]
That was already fixed. @cmd410 install V from source.

**Comment by cmd410** [comment]
Well... yeah I found a working version(v0.2.1) in github releases, which wierdly enough still considers itself v 0.2. And kinda works. Right until you do `v up`, then I guess it "updates" to broken version 0.2 and messes up the whole v installation. Plus broken v0.2 is on vlang.io... It doesn't really feel like a proper fix :/


Btw, code from tutorial doesn't compile with 0.2.1:
```v
// blog.v
module main

import vweb

struct App {
	vweb.Context
}

fn main() {
	vweb.run<App>(8081)
}

pub fn (mut app App) index() vweb.Result {
	return app.text('Hello world from vweb!')
}

pub fn (app &App) init() {
}

pub fn (app &App) init_once() {
}
```
with a little bit of guesswork I managed to correct it:
```v
// blog.v
module main

import vweb

struct App {
        // fix errors from vweb field not being public and mutable
	pub mut:
		vweb vweb.Context
}

fn main() {
	vweb.run<App>(8081)
}

pub fn (mut app App) index() vweb.Result {
        // fix app not having .text
	return app.vweb.text('Hello world from vweb!')
}

pub fn (app &App) init() {
}

pub fn (app &App) init_once() {
}
```
I suspect tutorial code is kinda.. outdated, not quite sure.
