### ISSUE TITLE
map doesn't support type alias as keys

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#8261]
**What did you do?**
```v
type Type = int

fn main() {
	x := map[Type]string
}
```

**What did you expect to see?**
works
 
**What did you see instead?**
```
main.v:4:15: error: maps only support string, integer, rune or voidptr keys for now (not `Type`)
    2 | 
    3 | fn main() {
    4 |     x := map[Type]string
      |                  ^
    5 | }
 ```

**Comment by ntrel** [comment]
Maybe we should make Table.get_type_symbol handle aliases like Table.get_final_type_symbol?

**Comment by danieldaeschle** [comment]
@spytheman should get_type_symbol have the same behaviour as get_final_type_symbol?

**Comment by Delta456** [comment]
No, `get_final` should be only for type aliases.
