### ISSUE TITLE
bad value when omit function body

### ISSUE THREAD

**Issue by danieldaeschle** [vlang/v#8262]
**What did you do?**
```v
type Type = int | string

fn test(a ...Type)

fn main() {
	test(1, 'test', 4)
}
```

**What did you expect to see?**
Checker or parser error
 
**What did you see instead?**
```
/usr/bin/ld: final link failed: bad value
```

**Comment by ntrel** [comment]
> works

It can't work. What are forward declarations of V functions for, libraries? (I understand we need them for extern C functions).

**Comment by Delta456** [comment]
This should be an error when using the function without having its body.

**Comment by ntrel** [comment]
I think we should make calling a function without a body require `unsafe`, because the forward declaration could use a wrong signature e.g. that allows mutating an immutable argument.

**Comment by shadowninja55** [comment]
the proper error is raised on latest v.
