### ISSUE TITLE
struct fields and sqlite string interpolation

### ISSUE THREAD

**Issue by blackshirt** [vlang/v#8266]
**V version:** 
```
V 0.2.1 a569dc1
getwd: /home/green/vexper
vmodules: /home/green/.vmodules
vroot: /home/green/v
vexe: /home/green/v/v
vexe mtime: 2021-01-22 02:28:46
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.1 a569dc1

Git version: git version 2.25.1
Git vroot status: 0.2-581-ga569dc17
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81
```

**OS:** 
```
OS: linux, Ubuntu 20.04.1 LTS (WSL)
Processor: 2 cpus, 64bit, little endian, AMD A4-9125 RADEON R3, 4 COMPUTE CORES 2C+2G
CC version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
```

**What did you do?**
I'm doing a little experiment with sqlite in V.  i'm attaching the sql and simple v programs here:

```
create table if not exists satker(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    kode TEXT NOT NULL UNIQUE,
    nama TEXT NOT NULL UNIQUE
);
```

Here the simple programs in v
```
import sqlite

struct Satker {
	mut:
	kode_satker string
	nama_satker string
}

struct CPool {
	sqlite.DB
}

fn (c CPool) save_satker(s []Satker) {
	c.exec("BEGIN TRANSACTION")
	for i in s {
		println(i)
		q := "insert into satker(kode, nama) values($i.kode_satker, $i.nama_satker)"
		println(q)
		_, code := c.exec(q)
		println(code)
	}
	c.exec("COMMIT")
}

fn main() {
	mut samples_data := []Satker{}
	for i in 0 .. 5 {
		mut stk := Satker{}
		stk.kode_satker = '1101$i'
		stk.nama_satker = 'Bahlul$i'
		samples_data << stk
	}
	// println(samples)
	db := sqlite.connect('db.sqlite3') or { panic(err) }
	c := CPool{db}
	c.save_satker(samples_data)
}
```

**What did you expect to see?**
five items in `samples_data` was inserted successfully in sqlite3 database

 
**What did you see instead?**
```$ v run exp.v
Satker{
    kode_satker: '11010'
    nama_satker: 'Bahlul0'
}
insert into satker(kode, nama) values(11010, Bahlul0)
21
Satker{
    kode_satker: '11011'
    nama_satker: 'Bahlul1'
}
insert into satker(kode, nama) values(11011, Bahlul1)
21
Satker{
    kode_satker: '11012'
    nama_satker: 'Bahlul2'
}
insert into satker(kode, nama) values(11012, Bahlul2)
21
Satker{
    kode_satker: '11013'
    nama_satker: 'Bahlul3'
}
insert into satker(kode, nama) values(11013, Bahlul3)
21
Satker{
    kode_satker: '11014'
    nama_satker: 'Bahlul4'
}
insert into satker(kode, nama) values(11014, Bahlul4)
21
```
as we can see in the output console, the result code from `exec` was 21, (21) SQLITE_MISUSE [https://www.sqlite.org/rescode.html#misuse](url).
if i update the query parts (add single quotes to mark values)
```
q := "insert into satker(kode, nama) values($i.kode_satker, $i.nama_satker)"
```
to form
```
q := "insert into satker(kode, nama) values('$i.kode_satker', '$i.nama_satker')"
```
i get the result
```
Satker{
    kode_satker: '11010'
    nama_satker: 'Bahlul0'
}
insert into satker(kode, nama) values('11010', '$i.nama_satker')
101
Satker{
    kode_satker: '11011'
    nama_satker: 'Bahlul1'
}
insert into satker(kode, nama) values('11011', '$i.nama_satker')
19
Satker{
    kode_satker: '11012'
    nama_satker: 'Bahlul2'
}
insert into satker(kode, nama) values('11012', '$i.nama_satker')
19
Satker{
    kode_satker: '11013'
    nama_satker: 'Bahlul3'
}
insert into satker(kode, nama) values('11013', '$i.nama_satker')
19
Satker{
    kode_satker: '11014'
    nama_satker: 'Bahlul4'
}
insert into satker(kode, nama) values('11014', '$i.nama_satker')
19
```
as we can see from the ouput, only the first item get succesfully inserted to sqlite database, and the four item failed with result code, 19, aka (19) SQLITE_CONSTRAINT [https://www.sqlite.org/rescode.html#constraint](url), because of the second values was not succesfully interpolated and makes violation constraint (UNIQUE constaint in sql structures above) occured after first item inserted.
Check the sqlite console
```
$ sqlite3 db.sqlite3
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> select * from satker;
1|11010|$i.nama_satker
sqlite> 
```

**Updated**
if i change fields of the `Satker` struct to simple name (without underscore, even its a valid vars in vlang), it's can interpolate the values part, and successfully inserted to database. 
```
struct Satker {
	mut:
	kode string
	nama string
}
```
Result output
```
Satker{
    kode: '11010'
    nama: 'Bahlul0'
}
insert into satker(kode, nama) values('11010', 'Bahlul0')
101
Satker{
    kode: '11011'
    nama: 'Bahlul1'
}
insert into satker(kode, nama) values('11011', 'Bahlul1')
101
Satker{
    kode: '11012'
    nama: 'Bahlul2'
}
insert into satker(kode, nama) values('11012', 'Bahlul2')
101
Satker{
    kode: '11013'
    nama: 'Bahlul3'
}
insert into satker(kode, nama) values('11013', 'Bahlul3')
101
Satker{
    kode: '11014'
    nama: 'Bahlul4'
}
insert into satker(kode, nama) values('11014', 'Bahlul4')
101
```
and i can verify its succesfully inserted.
```
$ sqlite3 db.sqlite3
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> select * from satker;
1|11010|Bahlul0
2|11011|Bahlul1
3|11012|Bahlul2
4|11013|Bahlul3
5|11014|Bahlul4
sqlite> 
```

Sorry for the long post here, i hope its can make clear the problems.
Thanks for response
nb: i can't make the suite title for this, so pleasu update accordingly to the best wish

**Comment by amoyyy** [comment]
@blackshirt using below instead will pass, 
 `q := "insert into satker(kode, nama) values('${i.kode_satker}', '${i.nama_satker}')"`

for  `q := "insert into satker(kode, nama) values('$i.kode_satker', '$i.nama_satker')"`
cgen gives `string q = _STR("insert into satker(kode, nama) values('%.*s\000', '$i.nama_satker')", 2, i.kode_satker);`
nama_satker won't be excuted.

**Comment by blackshirt** [comment]
> @blackshirt using below instead will pass,
> `q := "insert into satker(kode, nama) values('${i.kode_satker}', '${i.nama_satker}')"`
> 
> for `q := "insert into satker(kode, nama) values('$i.kode_satker', '$i.nama_satker')"`
> cgen gives `string q = _STR("insert into satker(kode, nama) values('%.*s\000', '$i.nama_satker')", 2, i.kode_satker);`
> nama_satker won't be excuted.

i would try that.
other question,
1. is `'$i.kode_satker'` or `'$i.nama_satker'` really complex expression to be placed inside { } ? i dont think its a complex expression.
2. if cgen result like you mentioned above, nama_satker wouldn't be executed, why when i change the field from `nama_satker` to more mnemonic form ex `name` it would be executed  ... what's really the bug ?
3. and the last thing, i think the form of`q := "insert into satker(kode, nama) values('$i.kode_satker', '$i.nama_satker')"` are really simple to grasp (i dont mention prepared statemen or sql injection here for simplicity) for commonly usage.

**Comment by amoyyy** [comment]
I agree with the first and third comment.@blackshirt
And for question 2, it's because field's name `nama_satker` end with the LETTER `r` that caused the problem.

**Comment by JalonSolov** [comment]
The letter `r` should not have anything to do with this.  It only represents a raw string if it is _before the quotes, like

`r'this is a raw string'`

**Comment by amoyyy** [comment]
@JalonSolov It may be irrelevant with the raw string parsing, but when the last letter `r` in field name is changed, the problem disappears.

**Comment by blackshirt** [comment]
omg...i think this is a `catastrophic' behaviour in the sense of raw string literal.

**Comment by Dialga** [comment]
> @JalonSolov It may be irrelevant with the raw string parsing, but when the last letter `r` in field name is changed, the problem disappears.
> 
> example:
> 
> ```
> struct Test {
>     rr string
>     kk string
> }
> 
> fn main() {
>     t := Test{"you will see it", "you will not see it"}
>     q := "('$t.rr', '$t.kk')"
>     println(q)
> }
> ```
> 
> output:
> `('you will see it', '$t.kk')`

```
('you will see it', 'you will not see it')
$ v -v
V 0.2.2 9995f6c
```
Your example outputs correctly now.

**Comment by Dialga** [comment]
Your example compiles now if you quote the string when inserting.
```
-	q := "insert into satker(kode, nama) values($i.kode_satker, $i.nama_satker)"
+	q := "insert into satker(kode, nama) values($i.kode_satker, '$i.nama_satker')"
```
Use `error_message()` next time to pick this up earlier.
```
-	println(code);
+       println(c.error_message(code, q));
...
sqlite.SQLError: no such column: Bahlul0 (21) (insert into satker(kode, nama) values(11010, Bahlul0))
```
Otherwise sqlite will insert the `values(11010, Bahlul0)` as if Bahlul0 was a column not a string as you intended.

(19) SQLITE_CONSTRAINT was occurring because you were inserting the same values into your UNIQUE column table with existing data. Remove db.sqlite3 or empty the table before trying again.

**Comment by Dialga** [comment]
Closing as fixed.
