### ISSUE TITLE
Why overload operators? V would be a second C++ ? Will V still be simple?

### ISSUE THREAD

**Issue by willvsimple** [vlang/v#8267]
CHANGELOG.md
V 0.2.2
Overloading of >, <, !=, ==, <= and >= operators.

I think this is a feature that would make the code look confusing.
When looking at other people's code it can make people wonder what "==" means now and if it has been overloaded.
The first word in the introduction of V is "simple", I hope it really is a simple language and not getting more and more complicated and finally becoming C++.

**Comment by Delta456** [comment]
It is only allowed for structs and type aliases. Operator overloading in V is very limited and restricted, you have to return `bool` when using these operators.

**Comment by nedpals** [comment]
Should be moved to discussion instead.
