### ISSUE TITLE
please do thorough test before any release!!!

### ISSUE THREAD

**Issue by retsyo** [vlang/v#827]
the so-said 'V alpha 0.1.10' supplies v.exe for windows, but https://github.com/vlang/v/issues/819

the latest breaks examples/tetris/tetris.v ( https://github.com/vlang/v/issues/825 ) which can be compiled yesterday

Why does V perfer to broadcast news, do release in such a hasty way? What can V benefit from it? I think it is enormous waste-of-time for users. 

At least, I will NOT check V any more till the end of this year. Good luck to you, the rash V.

**Comment by Xunius** [comment]
Wow what a heroic act of @retsyo

**Comment by AtjonTV** [comment]
Do you know what a `0.x` release means?

SemVer
```
Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
```

With other words: Expect V to may break as it's in early development and not to consider stable.

This is not hate speak against you, it's just that you can't await a early stage software to work 100%. With and without Testing on ALL PLATFORMS. (Microsoft does/did the same in Windows, end users where test users)

**Comment by liov** [comment]
> Do you know what a `0.x` release means?
> 
> SemVer
> 
> ```
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
> ```
> 
> With other words: Expect V to may break as it's in early development and not to consider stable.
> 
> This is not hate speak against you, it's just that you can't await a early stage software to work 100%. With and without Testing on ALL PLATFORMS. (Microsoft does/did the same in Windows, end users where test users)

You may have misunderstood 0.x release，api unstable doesn't mean it can't work。

**Comment by liov** [comment]
use gcc compile v.c

**Comment by AtjonTV** [comment]
I did. I used Clang 6 and GCC 7.4 on my PC and GCC 8 on my Phone and it just works to compile.

(Tetris compile on Android but does not run)

**Comment by aguspiza** [comment]
This is in very alpha stage, specially the windows part. It is a one man project. We can help writing tests and fixing things #817 ...

**Comment by medvednikov** [comment]
Things will get a lot more stable by V 0.2.

**Comment by kingofoz** [comment]
@medvednikov hello_world works now. Keep going, Alex. We are looking forward to seeing a better V.
