### ISSUE TITLE
Link error using != on struct

### ISSUE THREAD

**Issue by ntrel** [vlang/v#8271]
**V version:** recent git
**OS:** Windows 10

**What did you do?**
```v
struct S1 {
	i int
}

fn (l S1) == (r S1) bool {
	return l.i == r.i
}

s := S1{}
_ = s != s
```

**What did you expect to see?**
Either error about not defining operator `!=` or successful compilation, where V calls something like `!main__S1__eq(s, s)`. The latter would be better.
 
**What did you see instead?**
Link error:
```
C:\Users\ntrel\AppData\Local\Temp\ccRglQUt.o:opeq.12337819671197674814.tmp.c:(.text+0x1aa0d): undefined reference to `main__S1__ne'
```

**Comment by Delta456** [comment]
This should use the auto generated `!=` for structs if its not defined. Good find!

**Comment by ntrel** [comment]
> This should use the auto generated != for structs 

That would be unexpected if `==` is overloaded. Why not call the overloaded function with a `!` prefix expression?

**Comment by Delta456** [comment]
We should give the user the freedom of using both of them separately and be not so restrictive.

**Comment by ntrel** [comment]
If `==` is overloaded then an auto-generated `!=` is not going to work correctly.

**Comment by Delta456** [comment]
So you mean to give an error if the user hasn't defined `!=` if `==` is defined by the user?

**Comment by hungrybluedev** [comment]
> If `==` is overloaded then an auto-generated `!=` is not going to work correctly.

I think the user should be allowed to implement both `==` and `!=` if they want. But generally, negating the result of `==` should suffice. Can you give me an example when it does not work correctly?

**Comment by JalonSolov** [comment]
If neither `==` nor `!=` is defined by the user, auto-generate both.

If `==` is defined by the user but `!=` is not, then call `==` and negate the result for `!=` use.

If `==` is not defined by the user, but `!=` is, then call `!=` and negate the result for `==` use.

That's really the only viable way to handle this.

It will allow the user to override one or both, but still give consistent results.

**Comment by ntrel** [comment]
> the user should be allowed to implement both == and != 

Why? I don't think it's really more efficient to do this, the optimizer can take care of any redundant `!` operations. Why allow overriding `!=` at all?

**Comment by JalonSolov** [comment]
It would only shorten my given case by a small amount.  Why allow it?  Because if you can allow one to be overridden, why not both?  "One way" doesn't mean "you can only do half of what you expect".

Besides, although I can't think of a specific case at the moment, I'm sure I've running into something in the past where simply negating the `==` case would NOT work properly for `!=` case.  In that case, I would want to override both.
