### ISSUE TITLE
Iterate Struct

### ISSUE THREAD

**Issue by deftclaw** [vlang/v#8284]
**V version:** V 0.2.2 e06e8b1
**OS:** linux, Ubuntu 20.04.1 LTS

**What did you do?**
Defined an Item struct with string properties (and an array of strings)
Defined an Items struct and embeded Item struct.
Attempt to iterate through Items generating string output into html header2 to populate the web page.

```v
import json
import os
import vweb

struct App{
	vweb.Context
}

struct Items{
	item Item
}

struct Item {
	name string
	link string
	tags []string
}

pub fn (i &Items) next() ?Item {
	return i.item
}

pub fn (mut app App) index() vweb.Result {
	text := os.read_file('app.db') or { panic(err) }
	items := json.decode(Items, text) or { panic(err) }
	println(items)
	return $vweb.html()
}
```

[stack.v.txt](https://github.com/vlang/v/files/5859667/stack.v.txt)
[index.html.txt](https://github.com/vlang/v/files/5859669/index.html.txt)
[app.db.txt](https://github.com/vlang/v/files/5859679/app.db.txt)

**What did you expect to see?**
<h2> Samuel L. Jackson</h2>
<h2>https://www.imdb.com/name/nm0000168/</h2>
<h2> duck tree rock</h2>
 
**What did you see instead?**
```
/tmp/v/stack.16100106560093484381.tmp.c:18196:76: error: ‘main__Items’ {aka ‘struct main__Items’} has no member named ‘data’
18196 |    Option_main__Item _t830 = main__Items_next(&/*opt*/(*(main__Items*)items.data));
      |                                                                            ^
builder error: 
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:
```

**Comment by danieldaeschle** [comment]
It happens only in Vweb. It's a vweb template bug.

**Comment by mcastorina** [comment]
Tested and is working as expected with V 0.2.2 db9b523

**stack.v** needed some modifications for proper app logic:

```v
#!/usr/bin/env v

import json
import os
import vweb

struct App {
	vweb.Context
}

struct Items {
	item Item
mut:
	iter_index int
}

struct Item {
	name string
	link string
	tags []string
}

pub fn (mut i Items) next() ?Item {
	if i.iter_index > 0 {
		i.iter_index = 0
		return none
	}
	i.iter_index++
	return i.item
}

pub fn (mut app App) index() vweb.Result {
	text := os.read_file('app.db') or { panic(err) }
	items := Items{
		item: json.decode(Item, text) or { panic(err) }
	}
	println(items)
	return $vweb.html()
}

fn main() {
	vweb.run<App>(8082)
}
```

This issue can be closed.
