### ISSUE TITLE
vfmt desn't insert a space after //

### ISSUE THREAD

**Issue by kahsa** [vlang/v#8287]
**V version:0.2.2 c2d501e** 
**OS:ArchLinux** 

**What did you do?**
fmt
```v
fn main() {
	//abc
	//漢字
	//(abc)
}
```

**What did you expect to see?**
```v
fn main() {
	// abc
	// 漢字
	// (abc)
}
```
 
**What did you see instead?**
```v
fn main() {
	// abc
	//漢字
	//(abc)
}
```

**Comment by serkonda7** [comment]
This is expected behaviour. A space is only inserted if the first char is alphanumeric to allow for ascii art like `//--------//`, etc.

**Comment by serkonda7** [comment]
Regarding the CJK chars, I have no idea how they could be detected in a safe matter.

**Comment by kahsa** [comment]
> This is expected behaviour. A space is only inserted if the first char is alphanumeric to allow for ascii art like `//--------//`, etc.
> #6684

makes sense.

**Comment by serkonda7** [comment]
But the `// (abc)` is still valid in my eyes. It's no ascii art.
I will close this issue and and this to the discussion in #6684
