### ISSUE TITLE
vfmt removes newline. Is it a comment or function doc?

### ISSUE THREAD

**Issue by kahsa** [vlang/v#8288]
**V version:0.2.2 8b61891** 
**OS:ArchLinux** 

**What did you do?**
```v
fn foo() {}

// This is just a comment not a function description.

fn bar() {}
```

**What did you expect to see?**
As it is.
 
**What did you see instead?**
```v
fn foo() {}

// This is just a comment not a function description.
fn bar() {}
```

**Comment by JalonSolov** [comment]
This should have been fixed in PR #8189 merged as commit 129eee3 = @timbasel ?
