### ISSUE TITLE
Typo in math.fractions, divive

### ISSUE THREAD

**Issue by jkleiser** [vlang/v#8297]
**V version:** V 0.2.2 74115fe
**OS:** macos, Mac OS X, 10.14.6, 18G7016

**What did you do?**
`import math.fractions as fr`
then trying fraction 1/0

**What did you expect to see?**
error message: `V panic: Cannot divide by zero`
 
**What did you see instead?**
error message: `V panic: Cannot divive by zero`

**Comment by chovy** [comment]
for those who missed it there's a typo: `V panic: Cannot divive by zero` says `divive`

**Comment by jkleiser** [comment]
I now did a `v up` and recompiled my program. The typo seems to be fixed now. Thanks.
