### ISSUE TITLE
V can't compile this program, but it should?

### ISSUE THREAD

**Issue by jkleiser** [vlang/v#83]
I tried this in vlang.io/play ...
```
fn main() {
  mut age := f32(20)
  println(age)
  age = f32(21)
  println(age)
}
```
and got "You just found a bug. V can't compile this program, but it should. Please create a GitHub issue."

This, however, works fine:
```
fn main() {
  mut age := float(20)
  println(age)
  age = float(21)
  println(age)
}
```

**Comment by medvednikov** [comment]
Yes, I need to clean up the type casts. Quick fix, will do today.

**Comment by jkleiser** [comment]
I still get that message in vlang.io/play. ;-)

**Comment by medvednikov** [comment]
Fixed.
