### ISSUE TITLE
spawned fn should not need sync.WaitGroup parameter

### ISSUE THREAD

**Issue by ntrel** [vlang/v#8301]
```v
// no sync.WaitGroup
fn task(id int, duration int) {
	println('task $id begin')
	time.sleep_ms(duration)
	println('task $id end')
}
mut wg := sync.new_waitgroup()
// append syntax or similar
wg << go task(1, 500)
wg << go task(2, 900)
wg << go task(3, 100)
wg.wait()
```
Instead of `<<` syntax to append a `gohandle` result, it could be done manually (but this is more awkward):
```v
h1 := go task(1, 500)
wg.append(h1)
```
A simple way to implement WaitGroup.wait() would be to just call `.wait()` on each `gohandle` value.

There could be a way of getting the return types of the spawned functions too. Perhaps each function spawned would need to return the same type (or no result).

**Comment by dumblob** [comment]
@UweKrueger thoughts?

**Comment by UweKrueger** [comment]
What about this?
```v
fn task(id int, duration int) result.Type { ... }

mut wg := []thread result.Type{cap: 3}
wg << go task(1, 500)
wg << go task(2, 900)
wg << go task(3, 100)
results := wg.wait()
println(typeof(results).name) // -> `[]result.Type`
```
For void `task()` functions it would be just `mut wg := []thread{...}` and `wg.wait()` without `results`.
