### ISSUE TITLE
alsa/asoundlib.h not found

### ISSUE THREAD

**Issue by jordan-bonecutter** [vlang/v#8309]
**V version: 0.2.2
**OS: Ubuntu 20.04

**What did you do?**
`v run examples/sokol/sounds/melody.v`

**What did you expect to see?**
I expected no errors.
 
**What did you see instead?**
```
In file included from /tmp/v/melody.12758695860157545504.tmp.c:579:
/home/jordan/Desktop/Programming/Vtest/v/thirdparty/sokol/sokol_audio.h:506:14: fatal error: alsa/asoundlib.h: No such file or directory
  506 |     #include <alsa/asoundlib.h>
      |              ^~~~~~~~~~~~~~~~~~
compilation terminated.
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

**Comment by SleepyRoy** [comment]
What C backend did you use?

**Comment by Larpon** [comment]
You migt need to install ALSA development headers:
`apt install libasound2-dev`

**Comment by jordan-bonecutter** [comment]
In terms of the C backend I was using, I'm not sure. I did get it to work with apt install but fidgeted is submit the issue since that error message popped up.

**Comment by JalonSolov** [comment]
We have a way to warn about this instead of hitting that C error, just need to get the example file updated.

**Comment by danieldaeschle** [comment]
it's a better error now: `builder error: 'alsa/asoundlib.h' not found`
@Larpon s answer is correct.
