### ISSUE TITLE
Segmentation fault (core dumped) when compiling software in Docker container

### ISSUE THREAD

**Issue by fnetX** [vlang/v#8315]
**V version:** V 0.2.2 749d613
**OS:** Alpine Linux 3.13 in Docker

**What did you do?**
The container automagically pulls a software, compiles and runs it. Since a certain commit, the compilation of the software segfaults, no matter what we do. `v test .` works, compiling other software and our software before a certain commit works too. Building the software locally (Debian Buster) works too.

**What did you expect to see?**
Have the software compile and run fine. 
 
**What did you see instead?**
`Segmentation fault (core dumped)`
I tried a bit with gdb, I didn't debug segfaults before so please tell me if I can provide you with further information.
I'll also gladly provide someone with the core dump, the source code or even access to the docker container,  feel free to reach out.
```
Reading symbols from /tmp/vbuild/v...
[New LWP 118]
Core was generated by `v .'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  v__gen__Gen_comp_for (g=0x7ffd8ec2e630, node=...) at /tmp/v/v2.5646204959240263065.tmp.c:47424
47424					string key = /*key*/ *(string*)DenseArray_key(&_t2154.key_values, _t2153);
```
```
(gdb) list
47419				v__gen__Gen_writeln(g, _SLIT(""));
47420				// FOR IN map
47421				map_string_v__table__Type _t2154 = g->comptime_var_type_map;
47422				for (int _t2153 = 0; _t2153 < _t2154.key_values.len; ++_t2153) {
47423					if (!DenseArray_has_index(&_t2154.key_values, _t2153)) {continue;}
47424					string key = /*key*/ *(string*)DenseArray_key(&_t2154.key_values, _t2153);
47425					key = string_clone(key);
47426					if (string_starts_with(key, node.val_var)) {
47427						map_delete(&g->comptime_var_type_map, key);
47428					}
```
```
(gdb) print &_t2154
$1 = (map_string_v__table__Type *) 0x7ffd8ec2c750
(gdb) print &_t2154.key_values
$2 = (DenseArray *) 0x7ffd8ec2c760
(gdb) print _t2153
$3 = 33
(gdb) print _t2154
$4 = {key_bytes = 16, value_bytes = 4, even_index = 30, cached_hashbits = 16 '\020', shift = 5 '\005', key_values = {key_bytes = 16, value_bytes = 4, slot_bytes = 20, 
    cap = 37, len = 34, deletes = 32, all_deleted = 0x7f8818cd2150 '\001' <repeats 33 times>, data = 0x7f8818cbb020 <error: Cannot access memory at address 0x7f8818cbb020>}, 
  metas = 0x7f88191376f0, extra_metas = 4, has_string_keys = 1, hash_fn = 0x437246 <map_hash_string>, key_eq_fn = 0x437310 <map_eq_string>, 
  clone_fn = 0x4373d3 <map_clone_string>, free_fn = 0x437488 <map_free_string>, len = 2}
(gdb) 
```

Thank you a lot.

**Comment by helto4real** [comment]
You may checkout <https://github.com/vlang/docker> there are official builds of docker containers there that handles V.

**Comment by fnetX** [comment]
Well now it works with the latest compiler AND with updated code to match the new os... optional requirements. I'm not sure if the actual issue was fixed, since it was obviously an issue with a specific input code that made the compiler segfault. 
I'm happy it works now and don't want to bother diving too deep into this, I'll leave it open for a while so if anyone's interested in getting more details I'm glad to help, otherwise I'll close this some day and hope no one will ever encounter this problem again.

**Comment by helto4real** [comment]
I would suggest we close and file a new issue if the problem resurface

**Comment by fnetX** [comment]
...
