### ISSUE TITLE
problem with const naming in multi file modules

### ISSUE THREAD

**Issue by serkonda7** [vlang/v#8326]
**V version:** V 0.2.2 2e695a8
**OS:** Manjaro

**What did you do?**
Run vfmt on these files:
```v
// first.v
module main

const (
	foobar = 42
)

fn x() {
	println(foobar)
}
```
```v
// second.v
module main

fn y() {
	println(foobar)
}
```

**What did you expect to see?**
`foobar` --> `main.foobar` in both.
 
**What did you see instead?**
It is not changed in the file where the const is not declared.

**Comment by danieldaeschle** [comment]
Seems to work now
