### ISSUE TITLE
Focus on language itself, not on speed, framework, and etc.

### ISSUE THREAD

**Issue by changrui** [vlang/v#835]
Mr. Alex and your team, please focus on **v** self and basic functions, such as `bigfix`, basic `net` module, `http` module, and soon on,.

**Comment by nedpals** [comment]
> v self and basic functions

The V language continues to evolve everyday and these "basic functions" are constantly being added and improved for it to be used in developing modules and etc.

> basic net module, http module, and soon on,.

There are now people who are in the process of building the necessary modules for the `vlib` standard library. This includes the modules you have mentioned.
