### ISSUE TITLE
Require brackets for data.$field.name compile-time string field access

### ISSUE THREAD

**Issue by ntrel** [vlang/v#8367]
`data.$(field.name)` is supported and is needed e.g. for when the field is a struct and you want to access a field of that struct:
```v
struct Data {s string}

fn f<T>(data T) string {
    $for field in T.fields {
        return data.$field.name.s // huh, field.name is a string, strings don't have a field `s`
        return data.$(field.name).s // OK
    }
}
```
It could also be useful in future if you want to modify the field name: `data.$(field.name + '_extra')`.

Even when the field is not a struct, allowing `data.$field.name` without brackets seems less clear than `data.$(field.name)`. Why not require brackets always? It's also easier to see how the field name (`s`) is evaluated.

And finally, you might want to call a method on a non-struct field: `data.$(field.name).repeat(3)` (repeat `data.s` 3 times).

**Comment by danieldaeschle** [comment]
Should methods work the same? `data.$(method.name)()` (currently it works different, but it should be changed)

**Comment by ntrel** [comment]
Also conceptually, `$(expr)` can be used instead of an identifier. We might not want to allow that everywhere, but we should design consistent syntax without special cases.
