### ISSUE TITLE
Compile v.c with another tinycc : #github.com/rui314/chibicc# please. 

### ISSUE THREAD

**Issue by changrui** [vlang/v#8374]
`*chibicc` is yet another small C compiler that implements most C11 features. Even though it still probably falls into the "toy compilers" category just like other small compilers do, chibicc can compile several real-world programs, including Git, SQLite, libpng and chibicc itself, without making modifications to the compiled programs. Generated executables of these programs pass their corresponding test suites. So, chibicc actually supports a wide variety of C11 features and is able to compile hundreds of thousands of lines of real-world C code correctly.

Who test to compile `v.c` with this tinycc.

**Comment by JalonSolov** [comment]
You should be able to test it yourself using the `-cc` option.

**Comment by changrui** [comment]
`vc/v.c:606: #define ADDR(type, expr) (&((type[]){expr}[0]))`
                                                                                      ^ expected ')'

**Comment by danieldaeschle** [comment]
> `vc/v.c:606: #define ADDR(type, expr) (&((type[]){expr}[0]))`
> ^ expected ')'

looks like doesn't work then 🤷🏼‍♂️

**Comment by SleepyRoy** [comment]
To act as V's backend, a C compiler should be robust enough to give no error on `v.c`, except for, you know, header files not found, undefined symbol etc.

**Comment by JalonSolov** [comment]
There should be any header files not found, because is all in one file.  Same with undefined symbol - there shouldn't be any.

Basically, yes, it has to be able to compile `v.c` with no errors (though there are still some warnings).

If you want to use a different compiler, you are welcome to submit a PR with any changes needed to make it work with V.

**Comment by danieldaeschle** [comment]
Can be closed?

**Comment by SleepyRoy** [comment]
@danieldaeschle I guess yes.
@changrui welcome open a PR if later you make this compiler able to compile V!

**Comment by ntrel** [comment]
> you are welcome to submit a PR with any changes needed to make it work with V

Maybe not a good idea. This could be an ongoing burden on V developers if that compiler doesn't support the C standard well enough. What's the advantage of supporting another compiler? We have tcc for speed, gcc and clang for optimization and msvc for Windows integration. There has to be a good reason if we are going to limit the C features we can use.

**Comment by medvednikov** [comment]
Yes, there's no need to support anything else.
