### ISSUE TITLE
V not Compiling - const declaration error

### ISSUE THREAD

**Issue by AldrinMathew** [vlang/v#8377]
**V version:** V 0.2 30c0659
**OS:** Windows 10

**What did you do?**

I just upgraded V to the version mentioned above.

**What did you expect to see?**

Run and compile V apps without any issues.

 
**What did you see instead?**

`v doctor` and `v up` commands are not working (I just upgraded V a few minutes ago). I will have to manually upgrade v in the future if this problem persists.
The V compiler giving the following error:

```
C:\src\v\vlib\strconv\number_to_base.v:3:1: error: const declaration is missing parentheses `( ... )`
    1 | module strconv
    2 |
    3 | const base_digits = '0123456789abcdefghijklmnopqrstuvwxyz'
      | ~~~~~
    4 |
    5 | // format_int returns the string representation of the number n in base `radix`
```
Keep in mind that my V source directory is C:\src\v

**Comment by changrui** [comment]
do `v up` because this issue has been changed, and running well.

**Comment by AldrinMathew** [comment]
@changrui
`v up` is not running because of this issue. I will have to clone V repo again.

**Comment by changrui** [comment]
```

> git clone --depth=1 https://github.com/vlang/v
> cd v
> make

```

**Comment by JalonSolov** [comment]
Definitely need to do something like that.  Current version of V at this time is `V 0.2.2 fccd4f9`

**Comment by AldrinMathew** [comment]
@changrui
I tried.
```
Bootstraping TCC...
 > TCC not found
 > Downloading TCC from https://github.com/vlang/tccbin

Cloning vc...
 > Cloning from remote https://github.com/vlang/vc

Building V...
 > Attempting to build v_win.c with Clang


Exiting from error
```

**Comment by AldrinMathew** [comment]
@changrui
I checked the master branch and the error is not fixed in the file. I made changes to the file and made a Pull Request right after reporting this issue.

**Comment by spytheman** [comment]
You have an older V from a month ago, cut just a few commits before the one line const support.
The latest one from master supports it.
Upgrade errors are out of scope for this issue.
