### ISSUE TITLE
fn main(args []string) int { ... }

### ISSUE THREAD

**Issue by mw1164** [vlang/v#838]
would be **nice** to have an enhanced version of the fn main() { ... }
**fn main(args []string) int { ... }**

```
fn main(args []string) int {
    for i,a in args {
       println(i.str() +' : '+ a)                  
    }   
    return 0   
}
```
Not yet supported 
_**compiler output:**_ 
pass=1 fn=``
panic:   ....
**fn main must have no arguments and no return values**

yes, meanwhile we can of course use this 

```
import os

fn main() {

   args := os.args         
           
    for i,a in args {
       println(i.str() +' : '+ a)                  
    }    
}  
```

**Comment by medvednikov** [comment]
Why do you want 2 ways of doing the same thing? :)

That's against V's philosophy.

`os.args` works fine.
