### ISSUE TITLE
Infinite recursion crash 

### ISSUE THREAD

**Issue by trufae** [vlang/v#8400]
**V version:** V 0.2.2 1be7cc1
**OS:** macOS 10.15

**What did you do?**

```
$ cat optdefer.v
import os

fn wtfer() int {
	defer {
		os.rm('') or {
			return 123
		}
	}
	return 0
}

fn main () {
	a := wtfer()
	eprintln('$a')
}
```

**What did you expect to see?**

123 

**What did you see instead?**

```
$ v optdefer.v
Segmentation fault
```

lldb see this:

![image](https://user-images.githubusercontent.com/6431515/106196812-33704200-61b2-11eb-8e22-350bc4fa4c4b.png)

**Comment by trufae** [comment]
The following code works as expected. Maybe we should forbid the use of return in defer blocks?

```v
$ cat optdefer.v
import os

fn wtfer() int {
	mut a := 0
	defer {
		os.rm('') or {
			a = 123
		}
	}
	return a
}

fn main () {
	a := wtfer()
	eprintln('$a')
}
```

**Comment by shadowninja55** [comment]
defer is no longer allowed in return.
