### ISSUE TITLE
make `v up` independent of git, or automatically install it if nonexist

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#8406]
Right now running `v up` on win10 without git installed would give
```
Updating V...
================ V panic ================
   module: main
 function: git_command()
  message: exec failed (CreateProcess) with code 2: 系统找不到指定的文件。(cannot find intended file)
 cmd: git init
     file: C:/OtherProgram/vlang/cmd/tools/vup.v
     line: 118
=========================================
C:/Users/Roy/AppData/Local/Temp/v/../../../../../..C:\OtherProgram\vlang\vlib\builtin\builtin.c.v:38: at panic_debug: Backtrace
C:/Users/Roy/AppData/Local/Temp/v/../../../../../..C:\OtherProgram\vlang\cmd\tools\vup.v:118: by main__App_git_command
C:/Users/Roy/AppData/Local/Temp/v/../../../../../..C:\OtherProgram\vlang\cmd\tools\vup.v:56: by main__App_update_from_master
C:/Users/Roy/AppData/Local/Temp/v/../../../../../..C:\OtherProgram\vlang\cmd\tools\vup.v:29: by main__main
C:/Users/Roy/AppData/Local/Temp/v/../../../../../..C:\Users\Roy\AppData\Local\Temp\v\vup.1127052962677288271.tmp.c:17110: by wmain
0048b760 : by ???
0048b8c3 : by ???
7ffe91677034 : by ???
```

So I guess there're two choices.
```
a. remove git dependency
b. preserve git dependency, but prompt user to (automatically) install and set it if nonexist
```
This would get more and more important as V spreads among programmers with different levels, because some of them may just want to use V with fewest steps (release version).

**Comment by EPonyA** [comment]
The other day, I installed V on a Windows machine that didn't have a C compiler. The automatic TCC download was super convenient. That computer happened to have Git already, but if it didn't, I surely would have appreciated this similar convenience.

**Comment by medvednikov** [comment]
If prebuilt binaries are used, `v up` won't need git. It'll download the zips instead.

**Comment by JalonSolov** [comment]
That's not done right now because to be effective right now, a new zip would have to be created for every commit, and people were complaining bitterly about being bombed by notifications when that was turned on.  :-\

After 1.0, this will be a good idea.
