### ISSUE TITLE
Segmentation Fault when reading Int from Map

### ISSUE THREAD

**Issue by AtjonTV** [vlang/v#841]
**V version:** 0.1.10 (latest commit)
**OS:** eOS 5.0 (Linux 5.1.15)

**What did you do?**
I created a Map containing string and int values.

I then tried to read a int from the map like this:

```go
println('Get Port')
key := 'port'
value := -1 // output variable to pass as pointer
map.get(key, value)
println(value)
```

**What did you expect to see?**
```
Get Port
8080
```
 
**What did you see instead?**

```
Get Port
segmentation fault
```

**Workaround**

Read as string and use `.int()` to make a int out of the string.

**Comment by AtjonTV** [comment]
I now get a seg fault on `_set()`.

It did work before, now it doesnt ..

**Comment by skasyn** [comment]
Hello. You are not supposed to use `get` method since it is not a public method.

To read an int from your map, simply use `map[key]`.

**Comment by medvednikov** [comment]
`set` and `get` are private methods. Use `map[key]` as @skasyn suggested.
