### ISSUE TITLE
vweb: vweb app built in production mode goes in segfault after some requests

### ISSUE THREAD

**Issue by smartiniOnGitHub** [vlang/v#8419]
Hi all,
this is my dev environment:
```
OS: linux, Ubuntu 20.04.2 LTS
Processor: 8 cpus, 64bit, little endian, 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
CC version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

getwd: /home/sandro/work/temp
vmodules: /home/sandro/.vmodules
vroot: /opt/vlang_v
vexe: /opt/vlang_v/v
vexe mtime: 2021-01-29 15:12:10
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 94b5e47.26c06a5

Git version: git version 2.25.1
Git vroot status: 0.2.2-139-g26c06a56
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81
```

**What did you do?**
Build a vweb application (for example the `vweb/vweb_example.v`, but it's the same even with others) in production mode (using the `-prod` flag).
**Note that `-autofree` is not used here**; if used I get the following error at first request:
```
V panic: array.last: array is empty
```
but let's speak about this in another issue ...

**What did you expect to see?**
To browse its pages/routes at http://localhost:8082 (for vweb_example).
 
**What did you see instead?**
Browsing in normal way works, but if I run a load test (for example using 'ab' (part of Apache2 Web Server), it goes in segfault (in the message I see core dump created, but where ?) after some (1 to 9) hundred requests to its home page; note that since some week all this has been working.
**Important: without the '-prod' flag, all works without problems.**
Build command:
```
$ v -prod vweb_example.v
```
and then run it:
```
$ vweb example
Running a Vweb app on http://localhost:8082
```
And in another terminal, send the sample test command and its output:
```
$ ab -n 100000 -c 8 http://localhost:8082/
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
apr_socket_recv: Connection reset by peer (104)
Total of 299 requests completed
```

Tell me if you need more info; or a hint on how I can provide more.
Thanks for now. Bye

**Comment by mcastorina** [comment]
I did some investigation and it's definitely a race condition in `vlib/vweb/vweb.v`. I'm not familiar enough with the code to identify the critical sections, but removing the `go` from this line prevents the crash.

```v
go handle_conn<T>(mut conn, mut app)
```

Btw, this happens for both `-prod` and non-prod compilations.

Honestly, it's quite obvious there would be a race condition seeing how the code is concurrently handling mutable references to `conn` and `app`.

**Comment by smartiniOnGitHub** [comment]
@mcastorina thanks for your changes, after the merge (`V 0.2.2 7e08e84`) my tests in production mode restarted to work (even in temporarily no more in multi-threaded mode) and results are good enough for now.

Just for info:
- my tests (using different combinations of parameters) with ApacheBench, like `ab -n 100000 -c 8 http://localhost:8000/` now works well; the only strange things is that at the end of each test session the memory usage is very high (approx. 5.3 GB); but even Valgrind tell me that there are no more memory leaks ...
- if I do similar tests with another utility (wrk) the strange thing is that after some time the process is killed by the OS due to too much memory usage (more than 10 GB on my PC); just for example: `wrk -t8 -c320 -d10s --latency http://127.0.0.1:8000/`

Anyway thanks a lot for current fixes :-) .

**Comment by mcastorina** [comment]
Thanks for the info! I think V is still working on `-autofree` so it makes sense that memory continues to grow, but I'll keep that in mind when refactoring.
