### ISSUE TITLE
Execute other programs from V?

### ISSUE THREAD

**Issue by bstnbuck** [vlang/v#8427]
I would like to start an exe from V. So far I have called the C function system() from V. Is there a way to do this similar to Go's exec.Command() or C with system()?
Unfortunately I have not found anything yet. Thanks!

**Comment by Larpon** [comment]
@bstnbuck you have a few options that all serve slightly different usecases:
`os.exec` as found [here](https://modules.vlang.io/os.html#exec)
`os.system` as found [here](https://modules.vlang.io/os.html#system)
And the more advanced:
`os.Process` from [here](https://modules.vlang.io/os.html#new_process)

**Comment by bstnbuck** [comment]
@Larpon thank you!
