### ISSUE TITLE
vfmt: No need to change to block comment in multi line array

### ISSUE THREAD

**Issue by kahsa** [vlang/v#8437]
**V version:ArchLinux** 
**OS:0.2.2 974cac2** 

**What did you do?**
```v
arr := [
	// 1,
	// 2,
	// 3,
]
```

**What did you expect to see?**
As it is

**What did you see instead?**
```v
arr := [
	/* 1, */
	/* 2, */
	/* 3, */
]
```
Sorry but I don't see the reason that line comment have to be changed to block comment.

**Comment by kahsa** [comment]
I'm useing vscode, if those lines are line comment, it's easy to toggle back.

For just a test, comment out some lines and do some tests and toogle back them manytimes.
But if these are block comments, each line should be toggle back separately, not one action.
Line comment can be back by _one_ acition.
So, these line comments should be left as line comments.

result of toggle block comment on them
```v
arr := [
	/* 1,/*  */
	/* 2, */
	/* 3, */ */
]
```

**Comment by serkonda7** [comment]
It is intended that fmt forces block comments inside arrays as otherwise problems might arise, when the array is wrapped in a single line.

Btw I use VS Code too and just have on shortcut `ctrl-#` to toggle line comments and `ctrl-shift-#` to toggle block comments.

**Comment by kahsa** [comment]
What's the problems arise?

**Comment by kahsa** [comment]
select all lines and toggle block comment result in 
```v
arr := [
	/* 1, */
	/* 2, */
	/* 3, */
]
```
```v
arr := [
/* 	/* 1, */
	/* 2, */
	/* 3, */ */
]
```
How do you workaround this in one action?

**Comment by serkonda7** [comment]
Imagine this code
```v
arr := [
    1,
    // 2,
    3,
]
```
It might get wrapped into a single line
`arr := [1, // 2, 3]`
and cause a compilation error.

Regarding the comment toggle, you have to do it for each line individually.

**Comment by serkonda7** [comment]
But maybe fmt is mature enough now to distinguish between single and multiline arrays.
@spytheman I would look into improving this, if you give the okay.

**Comment by kahsa** [comment]
Since vfrm has been improved recently, I think such a big problem will not arise.
And in that case, when wraped into a single line, and then change to block comment.
No need to change when multi lines.

**Comment by kahsa** [comment]
vfrmt doesn't remove newlines now?
Then what's the problems like that arise?
That issue was past.

**Comment by serkonda7** [comment]
As you might see, I already reopened this, removed the `Won't fix` and assigned myself, so I will look into this issue.

**Comment by kahsa** [comment]
thanks

**Comment by spytheman** [comment]
Indeed, vfmt improved very much, so hopefully that restriction can be lifted now. 

It was a stop gap measure, that I did not like, but was necessary at the time...

**Comment by serkonda7** [comment]
@kahsa I started with the implementation, but I have to do some updates to array parsing and the wrapping logic first.

**Comment by kahsa** [comment]
No need to rush. Thanks for good work.
