### ISSUE TITLE
os.ls() implementation on Windows return empty array

### ISSUE THREAD

**Issue by Tembocs** [vlang/v#844]
**V version: 0.1.10** 
**OS: Windows 10 x64** 

**What did you do?**
Tried the following.
```files = os.ls('C:\\Users\\UserName\\Desktop')```

**What did you expect to see?**
Expected array of files, and ```files.len``` should be more than 0.
 
**What did you see instead?**
```files``` is an empty array and ```files.len``` return 0.

Looking into ```v/vlib/os/os_win.v``` the function does nothing.

**Comment by aguspiza** [comment]
os.ls() is not implemented in windows, PR #817 will add implementation

**Comment by medvednikov** [comment]
Fixed.

```
git pull
make
```
