### ISSUE TITLE
Hosting V binary  for linux-arm64 arch

### ISSUE THREAD

**Issue by sanathusk** [vlang/v#8448]
Linux machines based on arm64 arch like pinebook pro has started to gain popularity.Providing ready to download V binaries would be helpful for users on such platform to get started quickly.

**Comment by medvednikov** [comment]
I agree, same with arm64 macs.

**Comment by odidev** [comment]
@medvednikov 
I have raised a PR to release Linux/ARM64 zip archive via workflows, using QEMU utility.
Please find the PR below:
<https://github.com/vlang/v/pull/8698>
Kindly review and provide your suggestions on this PR.
