### ISSUE TITLE
Tetris core dump

### ISSUE THREAD

**Issue by JasonHonor** [vlang/v#845]
**V version:** 
0.1.10  

**OS:** 
CentOS 7.6.1810  

**What did you do?**  
yum install mesa-libGL-devel  
yum install glfw-devel  
yum install freetype-devel  

After installed depency, It compile successfully.  
I run it using command "v run tetris.v"，then I got the following exception.  

**What did you expect to see?**

 
**What did you see instead?**

============ running tetris ============
failed to credate glfw  window
create window wnd=(nil) ptr==0x12e2820
tetris: /builddir/build/BUILD/glfw-3.2.1/src/window.c:774: glfwSetWindowUserPointer: Assertion `window != ((void *)0)' failed.
sh: \u884c 1: 58068 \u5df2\u653e\u5f03               (\u5410\u6838)./tetris 2>&1
tetris: /builddir/build/BUILD/glfw-3.2.1/src/window.c:774: glfwSetWindowUserPointer: Assertion `window != ((void *)0)' failed.
failed to credate glfw  window
create window wnd=(nil) ptr==0x1b6e820
failed to run the compiled program, this should never happen
please submit a GitHub issue

**Comment by medvednikov** [comment]
Driver issue most likely.

Can you create an empty Windows with GLFW/C?

https://www.glfw.org/docs/latest/quick.html
