### ISSUE TITLE
Casted interface `is Type` test doesn't work

### ISSUE THREAD

**Issue by ntrel** [vlang/v#8465]
**V version:** recent git
**OS:** Windows 8

**What did you do?**
```v
struct Cat {}

interface Adoptable {}

fn main() {
	cat := Cat{}
	a := Adoptable(cat)
	if a is Cat {
		println('hi')
		println(typeof(a).name)
	}
}
```

**What did you expect to see?**
```
hi
Cat
```
 
**What did you see instead?**
Nothing

**Comment by ntrel** [comment]
The cast causes the problem. If I do this it works:
```v
fn new() Adoptable {
	return Cat{}
}

fn main() {
	a := new()
```

**Comment by spaceface777** [comment]
Manually casting things to interfaces always generates invalid C code currently, afaik.
