### ISSUE TITLE
cannot have multiple `_` parameters in function

### ISSUE THREAD

**Issue by Gladear** [vlang/v#8467]
**V version:** V 0.2.2 7eb7d04
**OS:** linux, Ubuntu 20.04.1 LTS (WSL 2)

**What did you do?**
```v
fn my_fn(_ int, _ f32) { println('I don\'t use those pesky params') }
my_fn(1, 1.2)
```

**What did you expect to see?**
> I don't use those pesky params
 
**What did you see instead?**
```
==================
      |                                  ~~~~^
/tmp/v/fn.8540435567263175054.tmp.c:8472:45: error: conflicting types for ‘_’
 8472 | VV_LOCAL_SYMBOL void main__my_fn(int _, f32 _) {
      |                                         ~~~~^
/tmp/v/fn.8540435567263175054.tmp.c:8472:38: note: previous definition of ‘_’ was here
 8472 | VV_LOCAL_SYMBOL void main__my_fn(int _, f32 _) {
      |                                  ~~~~^
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Rationale**
Some implementation of the same method (when implementing an interface for example) may or may not use all the parameters. There are examples in vlib too, where an OS would use all params, and another only some of them.
So the solution isn't to just forbid using `_` in parameters in my opinion.

**Comment by Delta456** [comment]
I think if the parameter name is `_` then we can generate temporary variables with `g.temp_var` method.
