### ISSUE TITLE
id []typ? so ugly! Is `id []kind` ok? 

### ISSUE THREAD

**Issue by changrui** [vlang/v#847]

**Comment by nedpals** [comment]
Please explain in full detail.

**Comment by medvednikov** [comment]
I think they refer to the usage of `typ` in the code? `type` can't be used because it's a keyword.

**Comment by changrui** [comment]
@Alex, I also suggest that `field.typ`  may change to `field.kind` in reflect. DO you think so?

**Comment by SuperFola** [comment]
No, absolutely not.
A type isn't a kind.
Kinds are types of type, not just "types".
