### ISSUE TITLE
Struct casting to struct implemented wrongly

### ISSUE THREAD

**Issue by ntrel** [vlang/v#8470]
**V version:** recent git
**OS:** Windows 8

**What did you do?**
```v
struct Abc {
	i int
	name string
}

struct Xyz {
	name string
	i int
}

fn main() {
	abc := Abc{}
	mut xyz := Xyz(abc)
}
```

**What did you expect to see?**
cgen something like:
```c
Xyz xyz;
xyz.name = abc.name;
xyz.i = abc.i;
```
 
**What did you see instead?**
```c
struct main__Abc {
	int i;
	string name;
};

struct main__Xyz {
	string name;
	int i;
};

//...

VV_LOCAL_SYMBOL void main__main() {
	main__Abc abc = (main__Abc){.i = 0,.name = (string){.str=(byteptr)""},};
	main__Xyz xyz = *((main__Xyz *)(&abc));
}
```
Just using a pointer cast is not going to work as the fields are in a different order.

**Comments**
I think we should consider whether to remove the feature - see here:
https://discord.com/channels/592103645835821068/592320321995014154/805390573430243349

**Comment by ntrel** [comment]
BTW the consensus on Discord is to change the syntax:

> If we want to support converting between structs, I think this existing syntax for same struct type could be extended:
`Xyz{...abc}`. That would also allow to specify any missing fields when the two structs are similar but not identical:
`
Xyz{
    ...abc 
    extra_field: expr
}
`

**Comment by ntrel** [comment]
Also the current checking allows uninitialized fields in the destination struct that don't appear in the source struct. That will work correctly in the new struct init implementation. Pull almost ready.

**Comment by JalonSolov** [comment]
You know what this is, right?

A re-implementation of good old "MOVE CORRESPONDING" from COBOL.  :-)

**Comment by medvednikov** [comment]
lol, V gaining features from the giants of the industry ;)
