### ISSUE TITLE
os.ls() can't open dir

### ISSUE THREAD

**Issue by JasonHonor** [vlang/v#848]
**V version:**   
0.1.10  
**OS:**   
CentOS 7.6.1810   

**What did you do?**  
using os.ls() to list files of the current directory.  
```
import os

fn main()
{
    //get the type of os
    ostype:=os.user_os()
    println('OsType:$ostype')

    hostname:=os.exec('hostname')
    println('Hostname:$hostname')

    //get home dir of current user
    home:=os.home_dir()
    println('HomeDir:$home')

    //get the current executable file path.
    exepath:=os.getexepath()
    println('ExePath:$exepath')

    pwd:=os.exec('pwd')
    println('CurrentDir:$pwd')

    //execute a command and fetch result string.
    uname:=os.exec('uname -ra')
    println('Uname:$uname')

    println(os.ls(pwd))
}
```
**What did you expect to see?**  
[user@centos os_info]$ ls  
os_info  os_info.v  
 
**What did you see instead?**  
[user@centos os_info]$ v run os_info.v |more  
OsType:linux  
Hostname:centos  
HomeDir:/home/user/  
ExePath:/home/user/code/v/examples/os_info/os_info  
CurrentDir:/home/user/code/v/examples/os_info  
Uname:Linux centos 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux  
ls() couldnt open dir "/home/user/code/v/examples/os_info"  
[]  
============ running os_info ============

**Comment by medvednikov** [comment]
Can you run `ls /home/user/code/v/examples/os_info` in your terminal?

**Comment by JasonHonor** [comment]
yes, the result as following:
```
[user@centos os_info]$ ls /home/user/code/v/examples/os_info
os_info  os_info.v

```

**Comment by medvednikov** [comment]
And now try 

```
import os
fn main() {
  files := os.ls('/home/user/code/v/examples/os_info')
  println(files)
}
```

**Comment by JasonHonor** [comment]
Successfully it run.

```
[user@centos os_info]$ v run os_try.v
============ running os_try ============
["os_info.v", "os_info", "os_try.v", "os_try"]

```

**Comment by medvednikov** [comment]
Ok I think I know what it is:

```
pwd:=os.exec('pwd')
```

You need to call .trim_space()

But it's much better to use a function:

```
pwd:=os.getwd()
```

**Comment by JasonHonor** [comment]
ok, thanks.
