### ISSUE TITLE
`chan` inside `struct` is not automatically initialized

### ISSUE THREAD

**Issue by UweKrueger** [vlang/v#8498]
**V version:** V 0.2.2 a008c82.51f2eb8
**OS:** Ubuntu 20.04.2 LTS

**What did you do?**
```v
struct St {
	ch chan int
}

fn f(st St) {
	st.ch <- 5
}

fn main() {
	st := St{}
	go f(st)
	i := <-st.ch
	println(i)
}
```

**What did you expect to see?**
`5`
 
**What did you see instead?**
`Segmentation fault`

**Analysis**
The channel inside the `struct` is not initialized. A workaround would be
```
    st := St{ ch: chan int{} }
```
But the compiler should create a default initializer (with `cap: 0`) when none is given.

**Comment by changrui** [comment]
Yes, Tested.
