### ISSUE TITLE
Calculating Fibonacci imperatively

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#85]
I can't find anything wrong with the following program and the PlayGround also reports:
You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.

const (
    MAX = 10
)

fn main() {
	mut fibs := [0; MAX]
	fibs[0] = 1
	fibs[1] = 1
	
	for i:= 2; i < MAX; i++ {
		fibs[i] = fibs[i-1] + fibs[i-2]
	}
	
	for j:=0; j < MAX; j++ {
		println('The $j-th Fibonacci number is: ${fibs[j]}')
	}
}

**Comment by medvednikov** [comment]
Bug with string interpolation.

This works:

```
const (
        MAX = 10
)

fn main() {
        mut fibs := [0; MAX]
        fibs[0] = 1
        fibs[1] = 1
        for i := 2; i < MAX; i++ {
                fibs[i] = fibs[i - 1] + fibs[i - 2]
        }
        for j := 0; j < MAX; j++ {
                num := fibs[j]
                println('The $j-th Fibonacci number is: $num')
        }
}

```

Will fix, thanks.

**Comment by mvlootman** [comment]
> I can't find anything wrong with the following program and the PlayGround also reports:
> You just found a bug. V can't compile this program, but it should. Please create a GitHub issue.
> 
> const (
> MAX = 10
> )
> 
> fn main() {
> mut fibs := [0; MAX]
> fibs[0] = 1
> fibs[1] = 1
> 
> ```
> for i:= 2; i < MAX; i++ {
> 	fibs[i] = fibs[i-1] + fibs[i-2]
> }
> 
> for j:=0; j < MAX; j++ {
> 	println('The $j-th Fibonacci number is: ${fibs[j]}')
> }
> ```
> 
> }

Just ran the code and it works now with the latest version.

output:

The 0-th Fibonacci number is: 1
The 1-th Fibonacci number is: 1
The 2-th Fibonacci number is: 2
The 3-th Fibonacci number is: 3
The 4-th Fibonacci number is: 5
The 5-th Fibonacci number is: 8
The 6-th Fibonacci number is: 13
The 7-th Fibonacci number is: 21
The 8-th Fibonacci number is: 34
The 9-th Fibonacci number is: 55
