### ISSUE TITLE
process module segfault

### ISSUE THREAD

**Issue by despiegk** [vlang/v#8505]
```v
import os
import time

mut p := os.new_process("bash")
p.set_redirect_stdio()

p.run()

time.sleep(100 * time.millisecond)
p.stdin_write("find /\n")
for _ in 0..100000{
	println(p.stdout_read())
	time.sleep(100 * time.millisecond)
}

p.wait()
```

we should also document this module just a little better, its super difficult to know whats going on, had to read the source code.

I was testing on osx, v is most recent release

**Comment by despiegk** [comment]
in case interesting to someone i've made a module process which wraps a lot of the low level logic

https://github.com/crystaluniverse/vlang_tools/blob/development/vlang_tools/process/process.v

**Comment by danieldaeschle** [comment]
I cannot reproduce this anymore, can you?

**Comment by danieldaeschle** [comment]
@medvednikov can you try this on macos?

**Comment by medvednikov** [comment]
Fixed.
