### ISSUE TITLE
Override value in struct

### ISSUE THREAD

**Issue by vertical22** [vlang/v#852]
**V version:** 0.1.10
**OS:** macOS Mojave

**What did you do?**
```
mut basket := Fruits{
        v: [Inventory {apple: 1, orange: 1}]
}

basket.v[0].apple = 12
```

**What did you expect to see?**
Can we override value in `apple`?
 
**What did you see instead?**
```
PREV=NAME
NEXT=INT
pass=2 fn=`main`
panic: ########
unexpected token: `=`
```

**Comment by medvednikov** [comment]
Yes, indexing is broken with multiple levels. Will fix asap.

**Comment by vertical22** [comment]
What is the maximum depth of nested struct could be link before it hit the limit?

Is there a possible denial of service of out of memory if we do not preallocate the fixed amount of array or length of each data types?

I think nested struct is a useful topic for your presentation.

**Comment by medvednikov** [comment]
Fixed.

> Is there a possible denial of service or out of memory if we do not preallocate the fixed amount of array or length of each data types?

Not sure what you mean by DoS. Automatic initialization allocates 0 elements.
