### ISSUE TITLE
getting wrong results from big.Number

### ISSUE THREAD

**Issue by hanabi1224** [vlang/v#8532]
Hey, i'm trying big.Number with pidigits benchmark game but found it behaves strange.
when I use some negative numbers, it gives wrong result since 14th digit, when I use only positive numbers, it gets wrong since 47th digit, could you plz help point out what i'm doing wrong here and how to correct the code, thanks!

```vlang
{
	// This gives wrong output since 14th digit
	// 3141592653      :10
	// 589261942971            :14
	 to_add := u * ten_neg * d
	 n1 = n1 * ten + to_add
	 n2 = n2 * ten + to_add
}
```
```vlang
{
	// This gives wrong output since 47th digit, supposed to be 3 instead of 5
	// 3141592653      :10
	// 5897932384      :20
	// 6264338327      :30
	// 9502884197      :40
	// 1693995            :47
	to_minus := u * ten * d
	n1 = n1 * ten - to_minus
	n2 = n2 * ten - to_minus
}
```

Here's full code
```vlang
module main

import math.big
import os
import strconv

fn main() {
	mut n := 27
	if os.args.len > 1 {
		n = strconv.atoi(os.args[1]) or { 0 }
	}

	digits_to_print := n
	mut digits_printed := 0
	mut k := big.from_int(1)
	mut n1 := big.from_int(4)
	mut n2 := big.from_int(3)
	mut d := big.from_int(1)
	mut u := big.new()
	mut v := big.new()
	mut w := big.from_int(0)
	one := big.from_int(1)
	two := big.from_int(2)
	ten := big.from_int(10)
	ten_neg := big.from_int(-10)

	for {
		u = n1 / d
		v = n2 / d
		u_int := u.int()
		v_int := v.int()

		if u_int == v_int {
			print(u_int)
			digits_printed++
			digits_printed_mod_ten := digits_printed % 10
			if digits_printed_mod_ten == 0 {
				println('\t:$digits_printed')
			}

			if digits_printed >= digits_to_print {
				if digits_printed_mod_ten > 0 {
					for _ in 0 .. (10 - digits_printed_mod_ten) {
						print(' ')
					}
					println('\t:$digits_printed')
				}
				return
			}

			{
				// This gives wrong output since 14th digit
				// 3141592653      :10
				// 589261942971            :14
				// to_add := u * ten_neg * d
				// n1 = n1 * ten + to_add
				// n2 = n2 * ten + to_add
			}
			{
				// This gives wrong output since 47th digit
				// 3141592653      :10
				// 5897932384      :20
				// 6264338327      :30
				// 9502884197      :40
				// 1693995         :47
				to_minus := u * ten * d
				n1 = n1 * ten - to_minus
				n2 = n2 * ten - to_minus
			}
		} else {
			k2 := k * two
			u = n1 * (k2 - one)
			v = n2 * two
			w = n1 * (k - one)
			n1 = u + v
			u = n2 * (k + two)
			n2 = w + u
			d = d * (k2 + one)
			k += one
		}
	}
}

```

**Comment by pznknmtb** [comment]
I once stepped into bigint problems with V and found out that the implementation (wrapper over tiny-bignum-c ) has a hard limit of 128 byte. The sad story is not only the limit (which is _not_ the expected behavior for bigint) but also the fact the beyond this limit the code simply deliver wrong results. I would at least except an exit with "limit exceeded".

**Comment by hanabi1224** [comment]
@pznknmtb Thanks for the information.  I built a basic bit integer module in pure vlang and finally get this pidigits program work correctly.   https://github.com/hanabi1224/vlang-big-integer

**Comment by JalonSolov** [comment]
Would you be willing to open a PR to modify the main lib functions?  Everyone would get the benefits then, without the extra module.

**Comment by hanabi1224** [comment]
@JalonSolov It's functioning properly but not benchmarked yet, I think it's more approapriate to make a math lib efficient enough before getting it into std, what do you think?

**Comment by Delta456** [comment]
@hanabi1224 Your module looks great and if you are on discord then we can talk how we can improve it further 😄

**Comment by hanabi1224** [comment]
@Delta456 Yeah just get on it, which channel is for such discussion?

**Comment by Delta456** [comment]
We can talk in `#v-chat` channel.

**Comment by JalonSolov** [comment]
Functioning but not benchmarked is still better than broken, which is what's in the std lib now.  That's why I suggested the PR.

**Comment by hanabi1224** [comment]
@JalonSolov @Delta456  Before putting it on a PR, I tried some basic benchmarks but found it consumes a lot of memory. ~2G for pidigits 4000.  valgrind says it leaks memory, how can I fix it? Haven't found memory management APIs in V doc tho

```
==476== HEAP SUMMARY:
==476==     in use at exit: 99,874,328 bytes in 89,634 blocks
==476==   total heap usage: 89,805 allocs, 171 frees, 100,044,352 bytes allocated
==476==
==476== LEAK SUMMARY:
==476==    definitely lost: 98,410,988 bytes in 89,089 blocks
==476==    indirectly lost: 1,452,636 bytes in 535 blocks
==476==      possibly lost: 10,396 bytes in 3 blocks
==476==    still reachable: 308 bytes in 7 blocks
==476==         suppressed: 0 bytes in 0 blocks
==476== Rerun with --leak-check=full to see details of leaked memory
```

**Comment by JalonSolov** [comment]
First, try with the `-autofree` switch.  It's not enabled by default, yet.

If there are still problems, you can try adding `.free()` methods to things you allocate.  `-autofree` will call those.

**Comment by JalonSolov** [comment]
As for memory... I have no idea how much space 4000 pidigits should take, so I don't know if 2G is too large or not.

**Comment by hanabi1224** [comment]
@JalonSolov It doesn't build with -autofree flag :(   to get an idea of memory consumption, check out [this](https://benchmarksgame-team.pages.debian.net/benchmarksgame/performance/pidigits.html) or [the one](https://another-benchmarks-game.vercel.app/problem/pidigits) I built myself.  For your reference golang takes ~10MB, rust takes ~3MB

**Comment by JalonSolov** [comment]
Ouch.  Sounds like an issue to open against "Memory Management".

If `-autofree` doesn't work, the only other option right now it is do manual memory management... allocate things yourself, _and_ free them yourself- just like you have to do in C.

**Comment by hanabi1224** [comment]
Update:  It compiles with -prod -autofree now !  However, it still leaks memory, should I create another issue on the mem leak?

code:  [pidigits.v](https://github.com/hanabi1224/vlang-big-integer/blob/main/examples/pidigits.v)
```valgrind --leak-check=full --show-leak-kinds=definite -- ./pidigits 100```

```
==3047== LEAK SUMMARY:
==3047==    definitely lost: 946,504 bytes in 10,510 blocks
==3047==    indirectly lost: 180 bytes in 2 blocks
==3047==      possibly lost: 0 bytes in 0 blocks
==3047==    still reachable: 44 bytes in 6 blocks
==3047==         suppressed: 0 bytes in 0 blocks
==3047== Reachable blocks (those to which a pointer was found) are not shown.
==3047== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```

**Comment by danieldaeschle** [comment]
Is the original report still an issue? I can't find the expected/current output in your description.
