### ISSUE TITLE
"V for Cpp developers" wiki page uses crappy C++

### ISSUE THREAD

**Issue by jwakely** [vlang/v#8533]
Your hello world is unnecessarily verbose, there's no need to use `endl` or return explicitly from `main`:
```
#include <iostream>
int main() {
  std::cout << "Hello World!\n";
}
```

Your vector initialization could use class template argument deduction:

```
std::vector numbers = {1, 2, 3, 4};
```

Your code to print a vector is wrong, it prints chars not ints, and I assume it needs a newline to be equivalent to `println(numbers)`:

```
std::copy(numbers.begin(), numbers.end(), std::ostream_iterator<int>(std::cout, " "));
std::cout << '\n';
```

You could use `ranges::copy` instead, for a range-based `for` loop. The filtering example could use `ranges::copy_if`.

Your file reading example doesn't compile, and using exceptions with iostreams is not idiomatic. You're making it unnecessarily complicated. Writing `endl` flushes the stream which is redundant on `cerr`. The idiomatic solution would be:

```
  std::ifstream f("path");
  std::string text;
  text.assign(std::istreambuf_iterator<char>(f), {});
  if (!f)
    std::cerr << "error reading from file\n";
```

I think using idiomatic C++ makes for a better comparison.

Finally, why does the page title say "Cpp"? It's called C++.

**Comment by Delta456** [comment]
Some of the code you have shown are in C++ 20 and it isn't released yet. Though it needs to be updated 👍 

Thanks!

**Comment by Delta456** [comment]
I have done the changes but the title doesn't accepts symbols like `++` so I had to use `CPP` instead of `C++`.

Thanks for reaching out to us! 😃

**Comment by jwakely** [comment]
C++20 is the current standard: https://www.iso.org/standard/79358.html

Ah, I thought github wiki pages did allow '+' in the titles, but looks like I was wrong, sorry about that.

**Comment by Delta456** [comment]
Many C++ Compiler don't completely support C++ 20 so I think this change can be done later.

**Comment by spytheman** [comment]
Hm, it is a wiki for a reason. It can be edited easily.
I do not understand, what is the point of making an issue first?

**Comment by jwakely** [comment]
> Hm, it is a wiki for a reason. It can be edited easily.

Only by admins of the repo.

**Comment by jwakely** [comment]
@Delta456 I see you've changed the first example to `std::cout << "Hello World!" << "\n";` but why two separate output operations?

    std::cout << "Hello World!\n";

**Comment by spytheman** [comment]
It should have used http://www.cplusplus.com/reference/ostream/endl/ .
Many tutorials advocate for its usage.

**Comment by jwakely** [comment]
Bad tutorials, maybe (which includes cplusplus.com)

http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rio-endl

**Comment by medvednikov** [comment]
Indeed. I remember wasting half a day debugging an issue due to missing output. It was unflushed because of not using endl.

**Comment by jwakely** [comment]
The V `println` function doesn't flush, it just writes a `'\n'` character to the standard output stream, and relies on that being line buffered to flush on the `'\n'`, so why is that not also appropriate for the C++ example?

This will flush on the newline:

    std::cout << "Hello, world!\n";

And the stream will be flushed and closed after returning from `main` anyway. There's a reason the class Hello World in K&R C doesn't bother to do `fflush(stdout)` and using `endl` is not needed in the C++ equivalent either. Flushing is needed for files and other non-interactive devices, using it for the standard output stream is typically unnecessary.

But nevermind, the main point of this issue was that the `ostream_iterator<char>` and `istreambuf_iterator` examples didn't even work.
