### ISSUE TITLE
怎么调用win32 api呢？

### ISSUE THREAD

**Issue by sonwnja** [vlang/v#8545]
golang 可以使用syscall模块调用kernel32.dll里的函数，V语言可以吗？

**Comment by SleepyRoy** [comment]
Translation:
```
How can I call win32 api?
Golang can call functions from kernel32.dll through syscall module. Can V achieve it?
```

**Comment by JalonSolov** [comment]
Yes, it already does.  Look for files with names that end in `_windows.c.v` in the V source.

Also look for `$if windows` in regular `.v` files.

**Comment by sonwnja** [comment]
我现在想调用VirtualProtect函数如何写代码呢?有例子吗？

**Comment by sonwnja** [comment]
> Yes, it already does. Look for files with names that end in `_windows.c.v` in the V source.
> 
> Also look for `$if windows` in regular `.v` files.

我现在想调用VirtualProtect函数如何写代码呢?有例子吗？

**Comment by JalonSolov** [comment]
Trying a Google translation...

我没有看到调用VirtualProtect的示例。调用任何win32 api函数应该类似于源代码中已经存在的函数。

There are no examples of calling VirtualProtect that I have seen.  Calling any win32 api function should be similar to those already in the source.

**Comment by sonwnja** [comment]
> Trying a Google translation...
> 
> 我没有看到调用VirtualProtect的示例。调用任何win32 api函数应该类似于源代码中已经存在的函数。
> 
> There are no examples of calling VirtualProtect that I have seen. Calling any win32 api function should be similar to those already in the source.

抱歉，打扰了，我想调用WinExec或者MesaageBox,你说的例子我看到了，我根据例子试了一下，但是失败了，可不可以告诉我怎么写才是对的，

**Comment by JalonSolov** [comment]
ui模块中有一个调用MessageBox函数的示例。看到这个文件：https://github.com/vlang/ui/blob/master/ui_windows.c.v

There is an example of calling MessageBox function in the ui module.  See this file:  https://github.com/vlang/ui/blob/master/ui_windows.c.v

**Comment by sonwnja** [comment]
> ui模块中有一个调用MessageBox函数的示例。看到这个文件：https://github.com/vlang/ui/blob/master/ui_windows.c.v
> 
> There is an example of calling MessageBox function in the ui module. See this file: https://github.com/vlang/ui/blob/master/ui_windows.c.v

我参照这个得到了如下错误：
![image](https://user-images.githubusercontent.com/15842446/106977714-d538f580-6795-11eb-9f47-07e5b4763715.png)

**Comment by JalonSolov** [comment]
You forgot the error message.

Also, please post code between
\`\`\`v

\`\`\`

markers, instead of screenshots.  That makes it simple to copy the code to test locally.

When I copy the code and try to run it, it just doesn't do anything.  No errors or warnings, just... nothing at all.

**Comment by sonwnja** [comment]
> You forgot the error message.
> 
> Also, please post code between
> ```v
> 
> ```
> 
> markers, instead of screenshots. That makes it simple to copy the code to test locally.
> 
> When I copy the code and try to run it, it just doesn't do anything. No errors or warnings, just... nothing at all.
好的，我这样写的
```v
module main

fn C.MessageBox(h voidptr, text charptr, caption charptr, kind u32) int

fn main(){
	title := ''
	content := 'hello,world'
	C.MessageBox(0, content.to_wide(), title.to_wide(), C.MB_OK)
}
```

**Comment by JalonSolov** [comment]
That is what I tried.  It didn't have any errors, it just didn't work.

I'm really not a Windows programmer, so you will likely need to get further help from someone else.  The problem _appears_ to be the first parameter of 0 - that is not a valid HWND (window handle), so the dialog box has nothing to attach to.  At least that is what seems logical.  However, you will need to find someone who really does Windows programming to be certain.

**Comment by sonwnja** [comment]
> That is what I tried. It didn't have any errors, it just didn't work.
> 
> I'm really not a Windows programmer, so you will likely need to get further help from someone else. The problem _appears_ to be the first parameter of 0 - that is not a valid HWND (window handle), so the dialog box has nothing to attach to. At least that is what seems logical. However, you will need to find someone who really does Windows programming to be certain.

好的，谢谢你

**Comment by JalonSolov** [comment]
If you can, I suggest joining the Discord server for V (link is on the home page - the gray box with 'Discord' under the row of icons).  The main channels use English as that is known by most, but there are several Chinese speakers on the server, and a channel specifically for Chinese - someone there may be able to help you further.
