### ISSUE TITLE
`mut` variable in `for` loop reads as address

### ISSUE THREAD

**Issue by UweKrueger** [vlang/v#8548]
**V version:** V 0.2.2 a008c82.a976876
**OS:** Ubuntu 20.04.2 LTS

**What did you do?**
```v
fn main() {
    mut indices := []int{len: 3}

    for i, mut v in indices {
        v = i
        a := v
        println('$i $v $a')
    }
}
```

**What did you expect to see?**
0 0 0
1 1 1
2 2 2

**What did you see instead?**
0 14440160 14440160
1 14440164 14440164
2 14440168 14440168

**Analysis**
Obviously `a` is initialized with the *address* of `v` rather than with the *value* - and this address is also printed with `'$v'`. One step of de-referencing is missing, when v is accessed.

**Comment by changrui** [comment]
So `for loop vars` can't be `mutable`.

**Comment by spytheman** [comment]
No, They can be mutable. It is just that when using their values, V should automatically de-reference them @changrui .

**Comment by UweKrueger** [comment]
It turns out that there is a similar issue concerning `mut` function parameters:
```v
struct St {
mut:
    n int
}

fn f(mut x St) {
    mut y := St{n: 2}
    a := x
    b := y
    x.n = 3
    y.n = 4
    println('$a.n $b.n')
}

fn main() {
    mut x := St{ n: 1 }
    f(mut x)
}
```
Here the output of function `f()` is `3 2` while the expected output would be `1 2`. The `mut` argument `x` should behave the same way as the `mut` function body variable `y`.
If the function argument is intended to behave like a reference it can still be defined as
```v
fn f(x &St) { ... }
```

**Comment by SleepyRoy** [comment]
@UweKrueger You just pointed out an important issue. Here's what V docs say.
```
If a function argument is immutable (like foo in the examples above) V can pass it either by value or by reference. The compiler will decide, and the developer doesn't need to think about it.

You no longer need to remember whether you should pass the struct by value or by reference.

You can ensure that the struct is always passed by reference by adding &.
```
Your example includes mutable arguments, which according to above docs are always passed by reference. That's why you got such results.
So I have two questions about this part in V.
1. Since mutable arguments are always passed by reference, how to create a copy (not reference) of a mutable variable inside function?
2. How does programmer know if an immutable argument in a specific function is passed by value or by reference? If not clear, programmers can't know `foo := immut_agrument` inside function is creating a reference or a value.

**Comment by SleepyRoy** [comment]
@medvednikov @spytheman any thoughts on my questions?

**Comment by UweKrueger** [comment]
> Your example includes mutable arguments, which according to above docs (I guess) are always passed by reference. That's why you got such results.

@SleepyRoy Of cause that's why I got such results but that's an internal aspect. The question is: What visible behaviour should the compiler expose to the programmer?
The problem with the `mut` case is the inconsistency (as in the `for` example above in the first post). The following illustrates the inconsistency - both assignments are copies:
```v
fn f(mut x St) {
    y := St{n: 2}
    a := *x  // x has to be explicitly de-referenced
    x = y    // x is automatically de-referenced by the compiler (C/Go would use `*x = y`, here)
}
```
In the same way the `for` loop example can be "fixed" in this way:
```v
for i, mut v in indices {
    v = i    // v is automatically de-referenced by the compiler
    a := *v  // v has to be explicitly de-referenced
}
```
But this seems inconsistent to me, too.

> 1. Since mutable arguments are always passed by reference, how to create a copy (not reference) of a mutable argument inside function?

At the moment, you can do `a := *x` as in the examples, here. I would like to change this to `a := x` because of the inconsistency.

> 2. Since compiler makes decision, how does programmers know if an immutable argument in a specific function is passed by value or by reference? If not clear, programmers can't know `foo := immut_argument` inside function is creating a reference or a value.

Concerning non-mut arguments things are clear: The programmer does not need to know! The program should always behave as if it's a value and being a reference might be an internal optimization that is not visible to the programmer. So here is no issue.

**Comment by medvednikov** [comment]
> But this seems inconsistent to me, too.

True, it's a bug. 

```v
    a := *x  // x has to be explicitly de-referenced
```

This should work without de-referencing.

**Comment by SleepyRoy** [comment]
@UweKrueger Thanks it's clear now. I agree with you and Alex's idea, `foo := argument` should always do automatic deref (if needed) and thus get a value copy, making behavior consistent in V.
I opened another issue #8560 recording this bug.
