### ISSUE TITLE
Maps don't accept variable or const as key or value

### ISSUE THREAD

**Issue by alic110** [vlang/v#8551]
**V version:** V 0.2.2 a73c209
**OS:** Linux Fedora 33
 Im Created A `map` and trying to add a map
 ```v
 struct Base {
mut:
    data    map[string]map[string]string
}

fn add_base(name string, value string) {
    mut sess := Base{}
    sess.data['123'] = {name: value} // <====================================
    println(sess)
}

fn main (){
    set_base('Name','Value')
}
 ```
i expect to see 
```v
Base{
  data: {'123': {'Name': 'Value'}}
}
```
But i Cannot See The `Name` and `Value` In Output
```v
Base{
  data: {'123': {}}
}
```
I mentioned this in Discord and @Delta456 said that the reason for this problem is the Maps don't accept variable or const as key or value yet

**Comment by ntrel** [comment]
Once https://github.com/vlang/v/pull/8608 is merged, it works with the new syntax:
```v
   sess.data['123'] = map{name: value}
```
After that pull's merged I need to deprecate allowing assigning a struct literal to a map before we can close this issue.
