### ISSUE TITLE
V does not request a name for a method

### ISSUE THREAD

**Issue by StunxFS** [vlang/v#8558]
**V version:** V 0.2.2 fafd949.5eef730
**OS:** Linux Mint 20

**What did you do?**
I was writing a little program, when I accidentally forgot to name a method. When running V with the program, I didn't get any errors and it ran as normal.

```v
module main

struct Struct {}

fn (_ &Struct) () {
}

fn main() {
}
```

**What did you expect to see?**
An error from V saying that the method has no name.
 
**What did you see instead?**
A most normal execution.

**Comment by medvednikov** [comment]
haha good find!

**Comment by medvednikov** [comment]
Fixed.
