### ISSUE TITLE
mutable array arguments aren't auto dereferenced inside function

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#8564]
**V version:** 
master

**OS:** 
win10

**What did you do?**
```V
fn main() {
	mut a := [1]
	foo(mut a)
}

fn foo(mut a []int) {
	unsafe{
		a2 := a
		a[0] = 100
		println(a)
		println(a2)
	}
}
```

**What did you expect to see?**
```
[100]
[1]
```
 
**What did you see instead?**
```
[100]
&[100]
```

**Analysis**
Mutable arguments are always passed by reference and inside function they're treated as references (not auto derefed when it's used), so in above example `a2 := a` actually gives a reference instead of a value. But as discussed in #8548 and agreed by Alex, mutable arguments should always be auto derefed if needed (so here `a2` should be a value, not a ref), making behavior consistent (with immutable arguments) in V.

**Comment by yuyi98** [comment]
It is used reference for a2, so it's right.
```vlang
fn main() {
	mut a := [1]
	foo(mut a)
}

fn foo(mut a []int) {
	unsafe{
		a2 := a
		a[0] = 100
		println(a)
		println(a2)
	}
}

PS D:\Test\v\tt1> v run .
[100]
[100]
```
