### ISSUE TITLE
There is a problem with the dl module

### ISSUE THREAD

**Issue by sonwnja** [vlang/v#8571]
V version: V 0.2.2 5a183d2

OS: win10

I want to use the WinExec function of kerenl32.dll to pop up the calculator

I tried the WinExec function of kerenl32.dll to pop up the calculator, but the calculator did not pop up and there was no error message. My code is as follows:
 
```V
module main

import dl

type Exec = fn (string, int) int

fn main() {
	h := dl.open('kernel32', dl.rtld_now)
	mut proc := &Exec(0)
	proc = dl.sym(h, 'WinExec')
	res := proc("calc.exe",2)
	println(res)
}
```
Results of the:
![image](https://user-images.githubusercontent.com/15842446/107007886-15b46580-67ce-11eb-86c4-75fd23981e34.png)

**Comment by JalonSolov** [comment]
Closing in favor of #8573
