### ISSUE TITLE
FAQ missing hyperlink to Bare-Metal V source code

### ISSUE THREAD

**Issue by Brainz456** [vlang/v#8592]
**V version:** 0.2
**OS:**  Windows

**What did you do?**
Visited the FAQ on the github wiki.

**What did you expect to see?**
A hyperlink at the end of the text:
"Does V run on bare metal? Yes! Simply run with -freestanding to exclude libc and vlib. See an example here."
 
**What did you see instead?**
There is no hyperlink to the suggested example

**Comment by spytheman** [comment]
I've updated the wiki entry.
