### ISSUE TITLE
[Discuss] Current Makefile problems and their solutions

### ISSUE THREAD

**Issue by Compro-Prasad** [vlang/v#860]
I don't like  some things about the current `Makefile`.
1. It always runs `clean`.
2. It removes `v.c` after building
3. The original stable C build is replaced by current V build which may or may not have any bugs. This causes re-builds of the same C code again and again.
4. `.github/PULL_REQUEST_TEMPLATE` mentions that `v` can compile itself. But this isn't taken care in the `Makefile`.

So, I propose the following Makefile to fix the above issues:
```
all: v

# We can always rely on vc being stable and we don't need to re-build it
v: vc
    ./vc -o v compiler

# Preventing re-builds of vc will prevent re-downloads of v.c
vc: v.c
    cc -std=gnu11 -w -o vc v.c

# Changes to Makefile should re-build everything from scratch
v.c: Makefile
    curl -Os https://raw.githubusercontent.com/vlang/vc/master/v.c

# Check if v can build itself
buildtwice: v
    ./v -o v compiler
    ./v -o v compiler

install: v
    # Install

test: buildtwice
    # Test

clean:
    -rm -f v vc v.c
```

**Comment by nedpals** [comment]
Closed. The makefile has been undergone several changes and now solves a lot of issues addressed in this issue.
