### ISSUE TITLE
'fix_array2 := fixed_array1' should only be allowed in unsafe block

### ISSUE THREAD

**Issue by SleepyRoy** [vlang/v#8603]
**V version:** 
master

**OS:** 
win10

**What did you do?**
```V
fn main() {
	mut a := [1]!
	mut b := a
	a[0] = 100
	println(a)
	println(b)
}
```
```V
fn main() {
	unsafe{
		mut a := [1]!
		mut b := a
		a[0] = 100
		println(a)
		println(b)
	}
}
```

**What did you expect to see?**
Only the second should compile and give
```
[100]
[1]
```
The first shouldn't, just like when you do the same to array or map.

**What did you see instead?**
Both compiled and gave expected results.

**Comment by ntrel** [comment]
> The first shouldn't, just like when you do the same to array or map.

A fixed-size array is a value type, a dynamic array and map are reference types. When you assign a fixed array to another, the elements are copied. So it depends on the element type whether the copying is memory-safe or not. E.g. for `int` as in your example, that is safe.
