### ISSUE TITLE
Compile error when relying on a default instantiation on a sum type variable

### ISSUE THREAD

**Issue by Nomy1** [vlang/v#8616]
**V version:** V 0.2.2 57258c2
**OS:** macos, Mac OS X, 10.15.5, 19F101

**What did you do?**
This is almost the same code copied from the documentation but with an default initializer
```
struct MyStruct { x int }
struct MyStruct2 { x int }
type MySumType = MyStruct | MyStruct2
struct Abc {
    bar MySumType = MyStruct { x: 0 }
}
x := Abc {}
```

**What did you expect to see?**
Compiles correctly. 
 
**What did you see instead?**
compilation error
```
// error: initializing 'main__MyStruct *' (aka 'struct main__MyStruct *') with an expression of incompatible type 'main__MyStruct' (aka 'struct main__MyStruct'); take the address with &main__Abc x = (main__Abc){.bar = (main__MyStruct){.x = 0,},};
```

**Comment by serkonda7** [comment]
You have to cast the default value like this
```v
struct Abc {
    bar MySumType = MySumType(MyStruct { x: 0 })
}
```

**Comment by serkonda7** [comment]
It's still an c error, that should not happen. I'm working on it.

**Comment by serkonda7** [comment]
@Nomy1 actually, I fixed the code generation for this code. 
So after the PR is merged, you should be able to remove the cast.
