### ISSUE TITLE
struct embedding with enums

### ISSUE THREAD

**Issue by mvlootman** [vlang/v#8624]
**V version:V 0.2.2 41cc72e.46f8e68** 
**OS: macos, macOS, 11.2, 20D64** 

**What did you do?**
I am trying to see what V's equivalent of Rust's enums (with data) would be by using V's Sum Types + struct embedding.
However I hit an issue creating the embedded struct.

```
enum States {
	alabamba
	alaska
}

enum CoinType {
	penny
	nickle
	dime
	quarter // special type quarter(state)
}

struct Coin {
	coin CoinType
}

struct Special {
	Coin
	state States
}

type Coins = Coin | Special

fn main() {
	coin := Coin{.nickle}
	special_coin := Special{.quarter, .alaska}	// error: expected type is not an enum (`Coin`)
	println(coin)
	println(special_coin)
}

```

**What did you expect to see?**
no compile errors :-)
 
**What did you see instead?**
```
error: expected type is not an enum (`Coin`)
   24 | fn main() {
   25 |     coin := Coin{.nickle}
   26 |     special_coin := Special{.quarter, .alaska}    // error: unknown field `coin` in struct literal of type `Special`
      |                             ~~~~~~~~
   27 |     println(coin)
   28 |     println(special_coin)
```

**Comment by JalonSolov** [comment]
Saw this somewhere... `enum is Rust's keyword for a "tagged union" or "sum type"`

So I would say yes, if you want something similar to Rust's "enum" you should use a sum type.

**Comment by serkonda7** [comment]
This is not a bug, like @mcastorina already said.

I will open a new feature request instead.
