### ISSUE TITLE
More `init()`s in one module cause C error

### ISSUE THREAD

**Issue by KeepZen** [vlang/v#8626]
**V version:** V 0.2.2 46f8e68
**OS:** windows, Microsoft Windows 10

**What did you do?**
In one module say `m`, there are more the one files say hello.v and world.v,
every file should put `module m` on the first line of the file, because I want 
they are in some module and to see they are imported  so I also put `init()` in every file.
In hello.v
`
fn init(){
println("file m/hello.v")
}
`
Int world.v
`
fn init(){
println("file m/world.v")
}
` 
V did't say anything, but there will be a **c error**, likes:
`
 error C2084: function “void m__init()” have exits 
`

**What did you expect to see?**
Now I know that, in one module there should be just  one `init()` function.
But if the C function have the different name, like include the  file name of the v source
to the c function name, the C error will not happened.
For example, For hello.v , generate `m_hello_init()`; for world.v, generator `m_world_init()`.

Or just make the one file to the module's enter point, like `mod.v` and `fn init()` can only put in this file.
If the dir have a file name as `mod.v`, other v files in this dir will not to default to `main` module.
 
**What did you see instead?**
A C error.

**Comment by JalonSolov** [comment]
Interesting - I never tried that, but yes, V should handle this more gracefully.

It should either give an error message about multiple init functions, or it should make them work.

**Comment by Delta456** [comment]
It should be an error imo though It should had given an error like `duplicate function init` but it didn't 🤔

**Comment by JalonSolov** [comment]
It could be argued either way, but the simplest fix would be to give an error on duplicate `init` functions in the same module.

**Comment by changrui** [comment]
In a file.v, I get the following error message:
```
> ==================
> /tmp/v/main.4722897730248830022.tmp.c:8470:22: error: redefinition of 'main__init'
>  VV_LOCAL_SYMBOL void main__init() {
>                       ^~~~~~~~~~
> /tmp/v/main.4722897730248830022.tmp.c:8465:22: note: previous definition of 'main__init' was here
>  VV_LOCAL_SYMBOL void main__init() {
>                       ^~~~~~~~~~
> ...
> ==================
> (Use `v -cg` to print the entire error message)

```

**Comment by KeepZen** [comment]
> In a file.v, I get the following error message:
> 
> ```
> > ==================
> > /tmp/v/main.4722897730248830022.tmp.c:8470:22: error: redefinition of 'main__init'
> >  VV_LOCAL_SYMBOL void main__init() {
> >                       ^~~~~~~~~~
> > /tmp/v/main.4722897730248830022.tmp.c:8465:22: note: previous definition of 'main__init' was here
> >  VV_LOCAL_SYMBOL void main__init() {
> >                       ^~~~~~~~~~
> > ...
> > ==================
> > (Use `v -cg` to print the entire error message)
> ```

This is because the `fn init()`s spot in different files.
In my case every file in the module `m`. 
In this case, I guess, this is not special the module, so they are in default module `main`.

**Comment by asnt** [comment]
Seems the same as #8152.
This seems to happen with any function name defined multiple times, even inside a single file:
```v
// demo1.v
module demo

pub fn demo() {
        println('demo 1')
}

pub fn demo() {
        println('demo 1')
}

// demo.v
module main

import demo

fn main() {
        demo.demo()
}
```
```bash
$ v .
==================
/tmp/v/demo.3998030366520350658.tmp.c:8551: error: redefinition of 'demo__demo'
[...]
```

**Comment by Delta456** [comment]
Basically duplication of functions isn't checked at all.

```
==================
/tmp/v/main.16481018684597822900.tmp.c:8550: error: redefinition of 'main__foo'
...
==================
(Use `v -cg` to print the entire error message)
```

**Comment by yuyi98** [comment]
Fixed.
