### ISSUE TITLE
cannot use symlink on windows 10. FIXED

### ISSUE THREAD

**Issue by StaTicDKK17** [vlang/v#8635]
**V version:** V 0.2.2 03d5bfb
**OS:** Windows 10 Pro 10.0.18363

**What did you do?**
I tried to run symlink after compiling make.bat with msvc

**What did you expect to see?**
a correct result
 
**What did you see instead?**
a compiler issue as shown in the picture
![image](https://user-images.githubusercontent.com/24255840/107193470-2db6ff80-69ef-11eb-8411-aea1f3d5e416.png)

**Comment by Delta456** [comment]
Have you used `v up` first?

**Comment by StaTicDKK17** [comment]
gives me exactly the same message

**Comment by StaTicDKK17** [comment]
my V is located on another drive than C, could that cause the problem?

**Comment by Delta456** [comment]
Closing, as fixed.
