### ISSUE TITLE
Better organization and labels

### ISSUE THREAD

**Issue by ntilotta** [vlang/v#864]
I suggest to add those tags too: c, c-plus-plus, repl, go, golang, and rust.
V do not has a GC, but it keeps Go-ish syntax, and it could achieve some kind of Rust' safety.
Last but not least, add this information to the organization at https://github.com/vlang

Name:
The V Programming Language

Description:
 Simple, fast, safe, compiled language for developing maintainable software

Website: https://vlang.io

**Comment by medvednikov** [comment]
I've updated the profile, thanks.

Lots of new tags were added as well.
