### ISSUE TITLE
It there *any* functions for type ***any***?

### ISSUE THREAD

**Issue by changrui** [vlang/v#8656]
**V version:** 
`V 0.2.2 6de78ec`
**OS:** 
`Ubuntu 20.04`
**What did you do?**
```
mut x := []any{}

x << 1
x << 'a'
x << 3.15

println(x.len)

for a in x {
    println(a)
}
```

**What did you expect to see?**
Print out `any` data.
 
**What did you see instead?**
```
cgen error: could not generate string method any_str for type 'any'
```

**Comment by changrui** [comment]
I add `pub fn (a any) str() string {}` to `builtin` module, get the following errors:
```
tmp/v/any.2546944105752431533.tmp.c:1122:16: error: **_unknown type name ‘any’_**
 1122 | string any_str(any a);
```

**Comment by Delta456** [comment]
`any` isn't implemented yet.

**Comment by shadowninja55** [comment]
`any` will not be a part of v afaik.
