### ISSUE TITLE
use of a ';' at the end of each statement

### ISSUE THREAD

**Issue by StunxFS** [vlang/v#8665]
Hi all.
I come to propose the use of a `;` at the end of each sentence. **Why?** To make it easier for the compiler to know when one sentence ends and when another ends.

Here's an example, decide which one looks better:

```v
import os

fn main() {
    var := os.read_file('unknown.txt')?
    println(var)
}
```

**vs**

```v
import os;

fn main() {
    var := os.read_file('unknown.txt')?;
    println(var);
}
```

I say to use `;` It's much better, I like it a lot, I don't care having to write this every time I finish a sentence. What do you think?

PD: Nice examples I have used, is that I could not think of anything better.

**Comment by cbracketdash** [comment]
V is designed to be simple as simple as possible for the user. They probably will not add this feature.
