### ISSUE TITLE
Backtick on Raw Strings

### ISSUE THREAD

**Issue by cbracketdash** [vlang/v#8674]
Hello, this is not a bug nor a feature request. 

I was wondering in a raw string in V, is there a way to type the character ` ?

**Comment by JalonSolov** [comment]
Raw _strings_ in V are strings with an `r` in front of them, and the contents of the string are not interpolated nor otherwise changed.
```v
r'This is a raw string, which can have ` and \n and they come out as ` and \n not translated to anything else'
```

If you're talking about bytes, then `\\`` works.

**Comment by cbracketdash** [comment]
Ah I see, thank you for the info
