### ISSUE TITLE
Excepted type u32, but got int

### ISSUE THREAD

**Issue by 0x9ef** [vlang/v#868]
**V version:** 0.1.10
**OS:** Windows 10 x64

**What did you do?**

```
fn get(mode u32) ?string {
    if mode != 0 {
        return error('undefined file mode')
    }
    return 'true file mode'
}

fn main() {
    val := get(u32(1)) or {
        println(err)
    }
}

```
**What did you expect to see?** `undefined file mode` 
 
**What did you see instead?**
```
pass=2 fn=`get`
panic: test.v:5
expected type `u32`, but got `int`
```

**Comment by medvednikov** [comment]
Right now consts have to be explicitly typed:

`if mode != u32(0)`

this will be fixed soon.

**Comment by medvednikov** [comment]
Fixed.

**Comment by medvednikov** [comment]
`val := get(1)` instead of `val := get(u32(1))` works as well.
