### ISSUE TITLE
Cannot run production build in docker scratch image

### ISSUE THREAD

**Issue by muuvmuuv** [vlang/v#8682]
**V version:** latest
**OS:** none

**What did you do?**

I want to create a tiny container from our V program to run as a microservice. Because there are no official `vlang` images I created one myself and compiled our program with the `-prod` flag. After that I am using a `scratch` image to pull in the compiled binary. But running the image returns an error (see below). Googling that errors just tells me line-endings might be wrong, but I don't think that is the case for a binary.

```dockerfile
FROM debian:latest AS build

WORKDIR /

RUN apt update -y

RUN apt install -y git
RUN mkdir /v
RUN git clone https://github.com/vlang/v.git /v

RUN apt install -y build-essential
RUN cd /v && make

RUN mkdir /app
RUN echo "fn main() {\nprintln('hello world')\n}" > /app/main.v
RUN cd /app && /v/v -prod main.v

FROM scratch

COPY --from=build /app/main /

CMD ["./main"]
```

You can test this by:

1. pasting the above into a `Dockerfile`
2. running `docker build --tag=smol:v .`
3. running `docker run --rm smol:v`

**What did you expect to see?**

No errors, program output.
 
**What did you see instead?**

```
standard_init_linux.go:219: exec user process caused: no such file or directory
```

**Comment by JalonSolov** [comment]
There actually is an official docker image.. https://hub.docker.com/r/thevlang/vlang

**Comment by muuvmuuv** [comment]
Good to know ^^ will test if the problem persists. They really should mention that somewhere, add a logo and description. I just thought it's not official.

**Comment by muuvmuuv** [comment]
Same error... 😞

**Comment by steve-kaufman** [comment]
Hi @muuvmuuv ,

The Dockerfile above won't work because your final binary will always depend on some kind of shared object. Very simple applications, such as hello world, will only depend on ld :

(If you're using the image `gladmo/vlang` from Dockerhub, which is based on Alpine, ld is located at 
`/lib/ld-musl-x86_64.so.1`. On Debian, it's located at `/lib64/ld-linux-x86-64.so.2`)

For more complicated apps, you can use the `ldd` command in the builder image to print out all it's shared object dependencies.

For example:

```Dockerfile
FROM gladmo/vlang AS builder

WORKDIR /app

COPY . .

RUN v -o app -prod .

CMD [ "ldd /app/app" ]
```

Which will output something like:

```
/lib/ld-musl-x86_64.so.1 (0x7f984c688000)
libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f984c688000)
```

So, with that in mind, the final docker image will look like this:

```Dockerfile
# Builder
FROM gladmo/vlang AS builder

WORKDIR /app

COPY . .

RUN v -o app -prod .


# Final image
FROM scratch

# Executable
COPY --from=builder /app/app /bin/
# C Lib
COPY --from=builder /lib/ld-musl-x86_64.so.1 /lib/

CMD [ "app" ]
```

Note that even if there's a library in `/usr/lib` or `/lib64` on the builder image, you can just copy it into regular `/lib` in scratch.

**Comment by muuvmuuv** [comment]
Makes sense. Tested it with `gladmo/vlang` which works (thanks!), but it does not with the official docker image. Cannot tell where the differences are, but the official has dependencies (with a simple hello world):

```
        linux-vdso.so.1 (0x00007ffc79373000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0c49e0c000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0c49deb000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0c49de6000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0c49c25000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0c49f95000)
```

**Comment by steve-kaufman** [comment]
That's bizarre. Is it a super old version of V? The only reason I was using `gladmo/vlang` is because it's way smaller.

**Comment by muuvmuuv** [comment]
Yeah, the size of the build image does not matter in that case ^^. Seems this here is the official version which uses the latest git master: https://github.com/vlang/docker/blob/master/docker/vlang/Dockerfile.buster

**Comment by muuvmuuv** [comment]
OK, wow. I got it working. So first, I am now using the `thevlang/vlang:alpine` for my build step. Then I had to set the `-cc gcc` flag because it always tried to use some exe lib (why whatsoever). After that I just realized a weird error when using the install command, and... yes since the official image is removing GIT... it works after installing it again haha. 

Here is the working copy:

```Dockerfile
FROM thevlang/vlang:alpine AS build

WORKDIR /app

COPY . .

ENV VFLAGS="-cc gcc"

RUN apk add --no-cache git

RUN v install
RUN v -prod main.v

RUN v version
RUN ldd main

FROM scratch

COPY --from=build /lib/ld-musl-x86_64.so.1 /lib/

COPY --from=build /app/main /bin/

EXPOSE 6789

CMD ["main"]
```

**Comment by steve-kaufman** [comment]
I think something about using the alpine suite of build tools, i.e. musl-libc/musl-gcc instead of the standard glibc/gcc, generates fewer shared object dependencies, which is why the official image prints out more .so dependencies.

I got the same `ld` result on my development machine, which is Debian WSL.

**Comment by muuvmuuv** [comment]
I will close this as it is now working as expected.

**Comment by DBJDBJ** [comment]
OK, can we have this as the base of the  Overview, published on: [https://hub.docker.com/r/thevlang/vlang](https://hub.docker.com/r/thevlang/vlang), please?

**Comment by vincenzopalazzo** [comment]
There is nothing wrong with this error.

Try to do `v help install`
