### ISSUE TITLE
Partial application of function parameters

### ISSUE THREAD

**Issue by jamesw201** [vlang/v#8687]
Partial application is a very useful feature in any language. It could complement vlang's current capabilities and allow for more functional application designs.

For instance:
You might partially apply functions with any dependencies they might need at the top of the application so that you can mock every side effect in the application from the main entry file.

Question: is there any way that a workaround could be achieved using existing features of the language? Perhaps using reflection?

**Comment by cbracketdash** [comment]
I apologize if I am mistaken, but when you refer to a partial function application, are you asking about specifying the number of parameters allowed in a function?

**Comment by JalonSolov** [comment]
Are you talking about this?
```
Partial function application refers to calling a multiple parameter function with less than its total number of parameters. This results in a new function taking the remaining number of parameters.
```
No, V doesn't have anything like that, and V doesn't do reflection (too slow).

You can write a variadic function, a generic function, etc.  You may be able to get what you need with those.

**Comment by jamesw201** [comment]
apologies @cbracketdash I could have been more specific, @JalonSolov has it right with that definition. 

I imagined it might work something like this:
```
fn multi_param(first int, second int) int {
    return first + second
}
partially_applied := multi_param(3)

print(partially_applied(2))
// 5
```

I think it comes into its own where you have a function that accepts an async dependency like an http client:
```
fn get_user_client(http_client http, user_id int) []User {
    data := http_client.get('https://domain.com/users/$user_id')?
    return data
}
```
This can be imported in main.v and partially applied with the `http` dependency and fed into another application component:
```
import net.http
get_user = get_user_client(http)

fn main() {
    send_out_emails(get_user)
}
```
which no longer needs to know about the dependency when it calls our function:
```
users := get_user(user_id)
```
The result is that you can push all side-effect causing dependencies to main.v where they can be easily mocked, so all of your code can be tested from a unit test at the top of the application. I think this would nicely complement the already strong functional foundation that V has.

Either way I appreciate your responding, this project look great and judging by your responses the community is great too so I look forward to using it.

**Comment by mcastorina** [comment]
I like the idea of partials, but automatically creating one for a function that is called with not enough parameters is not explicit enough for my taste. I would prefer either a new keyword, or a module that can be imported.

**Comment by dumblob** [comment]
The use cases of partial application might be in most cases covered with [closures](https://github.com/vlang/v/issues/7740 ) (unfortunately not yet implemented in V).
