### ISSUE TITLE
multi-returns can have their own methods

### ISSUE THREAD

**Issue by StunxFS** [vlang/v#8691]
**V version:** V 0.2.2 3164e29
**OS:** Linux Mint 20

**What did you do?**
I made methods for a multi-return (`(string, string)`):

```v
module main

fn (mr (string, string)) str() string {
	return "Mr, mR"
}

fn (mr (string, string)) other_method() {
	println(@METHOD)
}

fn do_print() (string, string) {
	return "Super", "Cool"
}

fn main() {
	println(do_print())
	do_print().other_method()
}
```

**What did you expect to see?**
An error message from V saying that multi-returns cannot have methods.
 
**What did you see instead?**
```bash
stunxfs@stunxfs-pc:~/Escritorio$ v run mr_str.v 
Mr, mR
(string, string).other_method
stunxfs@stunxfs-pc:~/Escritorio$
```

**Comment by Delta456** [comment]
To think that will actually work 😮

**Comment by StunxFS** [comment]
Little details that escape 😆
