### ISSUE TITLE
C error instead of syntax error on incorrect use of << operator

### ISSUE THREAD

**Issue by vsczpv** [vlang/v#8693]
**V version:** V 0.2.2 3164e29.67c6f24
**OS:** linux, KDE neon User Edition 5.20

So, I'm very new to vlang and I'm still learning it, I eventually tried to use the << operator to append numbers to an array.
Instead of a successful compile or an syntax error I got a C error instead.

**What did you do?**
Tried to append multiple values to array incorrectly with:

        fn main() {

                mut array := [1, 2, 3]

                array << 4, 5

                println(array.str())

        }

Instead of:
`array << [4, 5]`

**What did you expect to see?**
Syntax error
 
**What did you see instead?**

        ==================
        /tmp/v/a.14911027766088884744.tmp.c: In function ‘main__main’:
        /tmp/v/a.14911027766088884744.tmp.c:8505:40: error: void value not ignored as it ought to be
         8505 |  (multi_return_void_int_literal){.arg0=array_push(&array, _MOV((int[]){ 4 })),.arg1=5};
              |                                        ^~~~~~~~~~
        ...
        ==================

**Comment by changrui** [comment]
`array << [4,5]` is right.

**Comment by cbracketdash** [comment]
> `array << [4,5]` is right.

The OP's point is that V does not produce a syntax error but rather, C does

**Comment by JalonSolov** [comment]
Yes, this should be a syntax error in V.  All C errors need to be fixed.
