### ISSUE TITLE
Bitwise & bug

### ISSUE THREAD

**Issue by ntrel** [vlang/v#87]
```rust
const (
	foo = 1
	bar = 2
)

fn main() {
	println(foo | bar)// 3
	println(foo &bar)// BUG: 0
	//println(foo ^2)
}
```
It seems V supports C `| & || &&` operators. Above, `foo & bar` should print 1, not 0. The same happens with literals `1 & 2`. (Also, `foo &bar` is auto-formatted without a space after `&`).

(It might be useful to keep unimplemented xor `^` token available for other syntax instead, and it's a rare operation so it could just have a `math.xor<T>(a,b T)` function instead).

**Comment by medvednikov** [comment]
It was a bad idea to use `&` for both referencing and `AND`. 

But I need to make the language consistent with C/C++, Go, Java, Rust etc. That's why `^` has the same function. (Only `^=` works for now.)

`println(foo &bar)`

This is a parser bug, will fix, thanks.

**Comment by medvednikov** [comment]
Actually it runs correctly:

https://play.golang.org/p/4AZ5omk6_gH

**Comment by ntrel** [comment]
Sorry, stupid mistake, of course b10 & b01 is 0.
