### ISSUE TITLE
Map literals not working

### ISSUE THREAD

**Issue by cjdenio** [vlang/v#8705]
**V version:** 0.2.2
**OS:** macOS 11.2.1

**What did you do?**

I tried running this program, slightly modified from the one in the docs:
```v
fn main() {
	numbers := map{
		'one': 'one'
		'two': 'two'
	}
	println(numbers)
}
```

**What did you expect to see?**

I expected it to print out the map.

 
**What did you see instead?**

This strange build error:
```
main.v:3:3: error: unexpected `string`, expecting `name`
    1 | fn main() {
    2 |     numbers := map{
    3 |         'one': 'one'
      |         ~~~~~
    4 |         'two': 'two'
    5 |     }
```

**Comment by Delta456** [comment]
Make sure you are on the latest V as it is working [here](https://devbits.app/play/ezP3fo0Q4RrD)

**Comment by cjdenio** [comment]
That was it; thank you! I supposed the Homebrew build is slightly out of date 🤔
