### ISSUE TITLE
REPL does not work on Windows yet, sorry!

### ISSUE THREAD

**Issue by hjdhnx** [vlang/v#871]
**V version:** 
0.1.10
**OS:** 
windows10
**What did you do?**
I input "v -v" in cmd,it shows me "V 0.1.10".
However I input "v" in cmd,but it doesn't work.
it shows me "REPL does not work on Windows yet, sorry!"

**What did you expect to see?**

 I expect it works as linux.
**What did you see instead?**
"REPL does not work on Windows yet, sorry!"

**Comment by RoderickAdriance** [comment]
I have the same problem as you. 
V version v0.1.10

**Comment by Kogam22** [comment]
@hjdhnx Yup works on Linux
V 0.1.11

**Comment by medvednikov** [comment]
Fixed.
