### ISSUE TITLE
submodule error.  builder error: bad module definition

### ISSUE THREAD

**Issue by shvilek** [vlang/v#8724]
**V version:** 
V 0.2.2 835b3b2
**OS:** 
linux, Linux Mint 19.1 Tessa
**What did you do?**
I try to  call submodule

```go
module main

import deck.util

fn main() {
	util.print_123()
}
```
current folder structure
./main.v
./deck/util/util.v

util.v
```go
module util
pub fn print_123() {
	println("hello!")
}
```

**What did you expect to see?**
fn print_123() should be called
 
**What did you see instead?**
```bash
main.v:3:1: builder error: bad module definition: v imports module "deck.util" but /home/shvilek/v_projects/tutorial/deck/util/util.v is defined as module `util`
    1 | module main
    2 | 
    3 | import deck.util
      | ~~~~~~~~~~~~~~~~
    4 | 
    5 | fn main() {
```

**Comment by TheBoringDude** [comment]
You need to have a `v.mod` file in your root project directory.

This can be done easily by running
```bash
v init
```
in your project directory.

**Comment by shvilek** [comment]
Thanks a lot! At last it works!
