### ISSUE TITLE
No need build files/dirs in v run

### ISSUE THREAD

**Issue by cytown** [vlang/v#873]
If the devs need the compiled build files or dirs, they can just run v build -o ..., but when the devs use v run xxx.v, it means they don't need the build files right now, so you can just put the built files/dirs in temp dirs, then later the system will automatically clean up.

Also, I don't know why v need create a dSYM dir in running dir, is it for log tracer?  It's better to put in tmp dir as default and add the special flag for output them in target place.

**Comment by cytown** [comment]
My env is mac os 10.13.6, just for your reference.

**Comment by nedpals** [comment]
Unclear about the issue you have with the compiler. Closed.
