### ISSUE TITLE
Missing "Bare Metal" Wiki FAQ Example (Link)

### ISSUE THREAD

**Issue by F1nx** [vlang/v#8740]
Whether the example has already been produced or not for showing how `v` can run "bare metal", I did want you to know that the link is missing at _"See an example here"_.

https://github.com/vlang/v/wiki/FAQ
> **Does V run on bare metal?** Yes! Simply run with -freestanding to exclude libc and vlib. See an example here.

Simple problem, simple solution. :)

**Comment by spytheman** [comment]
I've updated the wiki entry.
