### ISSUE TITLE
a bug of sumtype and generic function

### ISSUE THREAD

**Issue by lydiandy** [vlang/v#8751]
**V version:** 
V 0.2.2 82650ee

**OS:** 
macos

**What did you do?**
here is the sample code:
```
module main

type MySumtype = int | string | bool 

fn myfn<T>(arg T) {
	mut x:=MySumtype{}
	x = arg
	match x {
		int {
		}
		string {

		}
		bool {

		}
	}
}

fn myfn2<T>(args []T) {
	for a in args {
	mut x:=MySumtype{}
	x = a
	match x {
		int {
		}
		string {

		}
		bool {

		}
	}
	}
	
}

fn main() {
	a:=1
	myfn(a)
	b:='abc'
	myfn(b)
	c:=true
	myfn(c)

	myfn2([1,2,3])
}
```

**What did you expect to see?**
should be compiled
 
**What did you see instead?**

/var/folders/lk/k709921d2gl4jrh31mt8_ktm0000gn/T/v/main.511093695143261210.tmp.c:8515:4: error: assigning to 'main__MySumtype' (aka 'struct main__MySumtype') from incompatible type 'string' (aka 'struct string')
        x = arg;
          ^ ~~~
/var/folders/lk/k709921d2gl4jrh31mt8_ktm0000gn/T/v/main.511093695143261210.tmp.c:8530:4: error: assigning to 'main__MySumtype' (aka 'struct main__MySumtype') from incompatible type 'bool' (aka 'int')
        x = arg;
          ^ ~~~
/var/folders/lk/k709921d2gl4jrh31mt8_ktm0000gn/T/v/main.511093695143261210.tmp.c:8550:5: error: assigning to 'main__MySumtype' (aka 'struct main__MySumtype') from incompatible type 'int'
                x = a;
                  ^ ~
4 errors generated.

==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

**Comment by Delta456** [comment]
This should not compile, it should be a checker error.

**Comment by yuyi98** [comment]
It's ok now.
```vlang
type MySumtype = bool | int | string

fn myfn<T>(arg T) {
	mut x := MySumtype{}
	x = arg
	match x {
		int {}
		string {}
		bool {}
	}
}

fn myfn2<T>(args []T) {
	for a in args {
		mut x := MySumtype{}
		x = a
		match x {
			int {}
			string {}
			bool {}
		}
	}
}

fn main() {
	a := 1
	myfn(a)
	b := 'abc'
	myfn(b)
	c := true
	myfn(c)

	myfn2([1, 2, 3])
}

PS D:\Test\v\tt1> v run .
.\tt1.v:4:11: notice: direct sum type init (`x := SumType{}`) will be removed soon
    2 |
    3 | fn myfn<T>(arg T) {
    4 |     mut x := MySumtype{}
      |              ~~~~~~~~~~~
    5 |     x = arg
    6 |     match x {
.\tt1.v:15:12: notice: direct sum type init (`x := SumType{}`) will be removed soon
   13 | fn myfn2<T>(args []T) {
   14 |     for a in args {
   15 |         mut x := MySumtype{}
      |                  ~~~~~~~~~~~
   16 |         x = a
   17 |         match x {
```
