### ISSUE TITLE
string.len breaks translation to js

### ISSUE THREAD

**Issue by kajuberdut** [vlang/v#8753]
OS: windows, Microsoft Windows 10 Pro v18363 64-bit
V full version: V 0.2.2 3d29f81.82650ee

**What did you do?**
Create jstest.v as:
`'bob'.len`

Then run
`v -o jstest.js jstest.v`

**What did you expect to see?**
js should be like 
`"bob".length`
 
**What did you see instead?**
```
.\jstest.v:1:7: error: `string` is not a struct
    1 | 'bob'.len
      |       ~~~
```

The same can be seen in playground, just add .len to the string in the hello world example. (Image attached)
![image](https://user-images.githubusercontent.com/8014746/107882718-e5d92200-6e9f-11eb-8400-54a0c1259406.png)

**Comment by JalonSolov** [comment]
Does not fail with current V.
