### ISSUE TITLE
V lang on bare metal?

### ISSUE THREAD

**Issue by MarkuBu** [vlang/v#8754]
Hi, is it possible to compile V for bare metal embedded systems like Cortex-M microcontroller?

**Comment by nyx-litenite** [comment]
You can always use `v -o new_file_name.c v_file_name.v` to produce a c file that can be used with an existing C compiler for your platform. There was (it still exists, but needs updating iirc) a `-freestanding` flag that produced a minimal library that could be used as well.

**Comment by crackedmind** [comment]
> You can always use `v -o new_file_name.c v_file_name.v` to produce a c file that can be used with an existing C compiler for your platform. There was (it still exists, but needs updating iirc) a `-freestanding` flag that produced a minimal library that could be used as well.

It will not help a lot, you also need some .s & .ld files for this platform, eg. stm32

But i am most concerned about a lot of mallocs under the hood.

**Comment by nyx-litenite** [comment]
>It will not help a lot, you also need some .s & .ld files for this platform, eg. stm32
>
> But i am most concerned about a lot of mallocs under the hood.

Ya, it sounds like the `freestanding` flag would be more what you were looking for. As I said, it did/will remove almost all of the v overhead, no libc linked to by default, and requires the dev to manage memory themselves.

[old changelog post](https://github.com/vlang/v/blob/82482167ce33a77ce8d63ee4cfd0e88774b5101d/CHANGELOG.md#v-0123)

**Comment by MarkuBu** [comment]
This makes V-Lang rather uninteresting for me. Rust has a clear advantage here.

**Comment by medvednikov** [comment]
Can you elaborate @MarkuBu ?

The plan is to make V a first class citizen for embedded.

**Comment by MarkuBu** [comment]
V has to go a long way to become mature. This way is too long for me. I want to be able to write software for Cortex-M or even AVR Microcontroller. Even Rust has to go a long way, but I can use it now. I don't want to start at zero.

I wish you good luck, but currently V-lang is not interesting for me, but I will follow the development of V-lang

**Comment by fermarsan** [comment]
There is a beta project named "Aixt" that implements a subset of V syntax for microcontrollers, including some ARM-based.

[https://github.com/fermarsan/aixt](https://github.com/fermarsan/aixt)
