### ISSUE TITLE
Wrong result in performance test as well as bad performance

### ISSUE THREAD

**Issue by cytown** [vlang/v#876]
**V version:** 0.1.10
**OS:** mac os 10.13.6

**What did you do?**
run v test.v

```
fn main() {
    mut element := 0
    mut iteration := 0
    mut iterations := 1
    mut innerloop := 0
    mut sum := f64(0.0)
    arraylength := 100000000
    mut array := []f64 // no fixed array here???
    println('iterations $iterations')
    for element = 0; element < arraylength; element++ {
        array << f64(element)
    }
    for iteration = 0; iteration < iterations; iteration++ {
        for innerloop = 0; innerloop < 1000000000; innerloop++ {
            sum += array[(iteration + innerloop) % arraylength]
        }
    }
    println('sum $sum')
    //free(array)
}
```

**What did you expect to see?**
Go run the same code in 2.7s, v should run in similar time.
============ running test ============
iterations 1
sum 50000000000000000.000000
 
**What did you see instead?**
v run in about 10s, 5 times to Go.  Besides, Go will return the correct result: 5.000000E+16
============ running test ============
iterations 1
sum 49999999094761600.000000

**Comment by medvednikov** [comment]
Please post the Go code. I'm certain that you don't call `array = append(array, element)` there.

You can pre-allocate in V:

`mut array := [0.0 ; arraylength]`

**Comment by cytown** [comment]
Please check the Go code.

`package main
import "os"
import "fmt"
import "strconv"
func main() {
    var (
        element int = 0
        iteration int = 0
        iterations int = 0
        innerloop int = 0
        sum float64 = 0.0
        array_length int = 100000000
        array []float64 = make([]float64, array_length)
    )
    if len(os.Args) > 1 {
        iterations,_ = strconv.Atoi(os.Args[1])
    }
    fmt.Printf("iterations %d\n", iterations)
    for element = 0; element < array_length; element++ {
        array[element] = float64(element)
    }
    for iteration = 0; iteration < iterations; iteration++ {
        for innerloop = 0; innerloop < 1000000000; innerloop++ {
            sum += array[(iteration + innerloop) % array_length]
        }
    }
    fmt.Printf("sum %E\n", sum)
    array = nil
}
`

**Comment by cytown** [comment]
> Please post the Go code. I'm certain that you don't call `array = append(array, element)` there.
> 
> You can pre-allocate in V:
> 
> `mut array := [0.0 ; arraylength]`
I did as your codes:
`mut array := [0.0 ; arraylength]
    for element = 0; element < arraylength; element++ {
        array[element] = f64(element)
        //println(array[element])
    }`

But it has compile error: 
`/Users/xxx//.vlang//test.c:4221:10: error: expected ';' after expression
array_f32 array= array_repeat(&tmp10,  arraylength , sizeof(f32) ) ;
         ^
         ;
/Users/xxx//.vlang//test.c:4221:1: error: use of undeclared identifier 'array_f32'; did you mean 'array_set'?
array_f32 array= array_repeat(&tmp10,  arraylength , sizeof(f32) ) ;
^~~~~~~~~
array_set
/Users/xxx//.vlang//test.c:594:7: note: 'array_set' declared here
 void array_set(array* a, int idx, void* val) {
      ^
/Users/xxx//.vlang//test.c:4221:16: error: expected identifier or '('
array_f32 array= array_repeat(&tmp10,  arraylength , sizeof(f32) ) ;
               ^
/Users/xxx//.vlang//test.c:4227:18: error: unexpected type name 'array': expected expression
array_set(&/*q*/ array , element , & tmp12) ;
                 ^
/Users/xxx//.vlang//test.c:4240:38: error: unexpected type name 'array': expected expression
 sum  =  sum + ( *(f32*) array__get( array , (/*lpar*/ iteration + innerloop ) % arraylength) ) ;
                                     ^
5 errors generated.
V panic: clang error`

Also tried: `mut array := [f64(0.0) ; arraylength]`, same result, just replace with `array_f64 array= array_repeat(&tmp10,  arraylength , sizeof(f64) ) ;`

**Comment by cytown** [comment]
BTW: I have upgraded to v.0.1.11

**Comment by deangelo2005** [comment]
Thanks for all you do

**Comment by cytown** [comment]
Sorry, maybe the result is fine, the i64 result should be 49999999500000000, so it's OK for f64.

But the performance is bad, need to improve.

**Comment by cytown** [comment]
Besides, the i64 works fine with` array := [0: arraylength]`, but performance same.

**Comment by cytown** [comment]
I got the reason, the default v compile is debug version and with lot of extra info which lag the program, if use `v -prod test.v`, the result should be `./test 1  1.58s user 0.30s system 99% cpu 1.886 total`, which is much comparable to Go.

So the key point is how to improve the performance when it has debug info. (If run as a service, it's a must to have the debug info.)

**Comment by proyb6** [comment]
Tested your working code, I have an error with : in
```
mut array := [0: arraylength]
```

Mind to repost full code example?

**Comment by cytown** [comment]
> Tested your working code, I have an error with : in
> 
> ```
> mut array := [0: arraylength]
> ```
> 
> Mind to repost full code example?

Sorry, my typo, it's `mut array := [0; arraylength]`

**Comment by medvednikov** [comment]
So the bad performance was fixed by using a preallocated array and `-prod`.

**Comment by proyb6** [comment]
I should note both has different type

Allocate f64, compile fine
```
mut array := []f64
```

Allocate Int, compile error and reported line off by 1
```
mut array := [0: arraylength]
```

pass=2 fn=`main`
panic: test.v:17
expected type `int`, but got `f64`
```
fn main() {
    mut i := 0
    mut iteration := 0
    mut iterations := 1
    mut innerloop := 0
    mut sum := f64(0.0)
    arraylength := 100000000

    mut varray := [0; arraylength]
    //mut varray := []f64


    println('iterations $iterations')

    for i = 0; i < arraylength; i++ {
        varray << f64(i)
    }

    for iteration = 0; iteration < iterations; iteration++ {
        for innerloop = 0; innerloop < 1000000000; innerloop++ {
            sum += varray[(iteration + innerloop) % arraylength]
        }
    }
    println('sum $sum')
}
```

**Comment by cytown** [comment]
@proyb6 `mut array := [0: arraylength]` is typo, please try `mut array := [0; arraylength]`

@medvednikov preallocate for float(f32/f64) is not allowed, it must be a bug.  Detail output please check previous post.

**Comment by cytown** [comment]
@medvednikov the compile error was because array_f32/array_f64 not declared.
