### ISSUE TITLE
C functions are skipped in the checker

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#8763]
```v
fn C.foo(x int)


fn main() {
        C.foo('sdf')
}
```

This passes the checker, but it shouldn't.

**Comment by zakuro9715** [comment]
I try to check c calls by remove this.
https://github.com/vlang/v/blob/230372df09053a95f1137da4c7b309f8610229c6/vlib/v/checker/checker.v#L1909-L1924

There are problems to fix

- In many places, C functions called with invalid type.
- Some C functions have wrong signature(arguments is omitted)

**Comment by Delta456** [comment]
Fixed in https://github.com/vlang/v/commit/2d73411396295ed1c65384019666477bf94ecc1d
