### ISSUE TITLE
Confusion in documentation regarding automatic type promotion of int to f32

### ISSUE THREAD

**Issue by abhishek-nigam** [vlang/v#8764]
Hi team at V,

Thanks for making this awesome language. I had just begun learning V and was going though the learning doc at https://github.com/vlang/v/blob/master/doc/docs.md. Here, I found the following explanation in "Primitive Types" section:

> An int value for example can be automatically promoted to f64 or i64 but not to f32 or u32. (f32 would mean precision loss for large values and u32 would mean loss of the sign for negative values).

But the diagram just before this is slightly confusion, since from it appears that int can be automatically promoted to f32:
<img width="282" alt="Screenshot 2021-02-15 at 11 58 33 AM" src="https://user-images.githubusercontent.com/21065165/107912774-2363ab00-6f85-11eb-8098-6f650b013140.png">

I think many learners can incorrectly infer from it that int can be automatically promoted to f32, where in actuality I think it can't be.

**Comment by JalonSolov** [comment]
It can be, but you may lose precision (depending on the value of the int).  That distinction needs to be documented.

**Comment by StunxFS** [comment]
Possible duplication of #8601
