### ISSUE TITLE
Import Via Link

### ISSUE THREAD

**Issue by F1nx** [vlang/v#8773]
Something that I believe would also give a push for V's effectiveness is if there was the ability to import modules/libraries through links just as [Deno](https://deno.land/) can. Upon building or running a program, all the dependencies would be installed into the file.

_Thoughts?_

**Comment by JalonSolov** [comment]
Already planned to support links.

V already "installs all the dependencies into the file" as it's normal operation.  In fact, it has been installing more than necessary, which is what the new `-skip-unused` flag is all about.  It will become the default once we're sure it's working the way we want.

**Comment by F1nx** [comment]
Awesome!
