### ISSUE TITLE
V keeps exiting the repl after the first line on Windows Terminal.

### ISSUE THREAD

**Issue by Gebriel** [vlang/v#8781]
**V version:** 0.2.2
**OS:** Windows 10

**What did you do?**
Tried to run V on Windows Terminal

**What did you expect to see?**
To try V on the reply
 
**What did you see instead?**
It keeps exiting after the first line
![v](https://user-images.githubusercontent.com/4125761/108057692-02be5280-7064-11eb-9d8d-3ed004a1f0ce.png)
 but works fine on CMD.

**Comment by Delta456** [comment]
It is working for me. Are you sure that you are on the latest commit?

**Comment by Gebriel** [comment]
> It is working fine for me. Are you sure that you are on the latest commit or latest Windows Terminal Version?

Yes I am. as you can see on the screenshot.

**Comment by JalonSolov** [comment]
V changes almost daily.  This is with the most recent version as of this morning, in Windows Terminal.
```
PS D:\> v
Welcome to the V REPL (for help with V itself, type `exit`, then run `v help`).
V 0.2.2 982e359
Use Ctrl-C or `exit` to exit, or `help` to see other available commands
>>> name := 'bob'
>>> println(name)
bob
>>> 5+5
10
>>>
^C
PS D:\>
```

**Comment by Gebriel** [comment]
> V changes almost daily. This is with the most recent version as of this morning, in Windows Terminal.
> 
> ```
> PS D:\> v
> Welcome to the V REPL (for help with V itself, type `exit`, then run `v help`).
> V 0.2.2 982e359
> Use Ctrl-C or `exit` to exit, or `help` to see other available commands
> >>> name := 'bob'
> >>> println(name)
> bob
> >>> 5+5
> 10
> >>>
> ^C
> PS D:\>
> ```

I am sure I am on the latest version of V.

**Comment by JalonSolov** [comment]
The version of V shown in your post was a day old when I posted mine.  You were already behind at that time.

**Comment by Gebriel** [comment]
> The version of V shown in your post was a day old when I posted mine. You were already behind at that time.
Actually, I was not, the one I posted first and the current latest version are the same.

**Comment by JalonSolov** [comment]
Your commit shown in first post:  c057b45
Commit shown in my post:  982e359
```
jalon@Ripper:~/git/v$ git rev-list 982e359 ^c057b45 --count
9
jalon@Ripper:~/git/v$
```
So, 9 commits after what you had at that time.

Now?  Even further away...
```
jalon@Ripper:~/git/v$ git rev-list HEAD ^c057b45 --count
25
jalon@Ripper:~/git/v$
```
You may have had the latest ZIP file or something, but that was not the latest version of V.

Recommended action:  Delete your current V directory, use `git clone` to get the current source, and build it with `.\make.bat`.

Then whenever you run into a problem in the future, first do `v up` then try again.  If it still fails, open an issue.

V is still changing rapidly enough that cloning the source and using `v up` to stay up-to-date is the best way to do things.

**Comment by Gebriel** [comment]
> Your commit shown in first post: [c057b45](https://github.com/vlang/v/commit/c057b45bb1e1159bbbd914990c3f4bfa4690427a)
> Commit shown in my post: [982e359](https://github.com/vlang/v/commit/982e35909d29b342a192b7d877b88f4a4b6dddfb)
> 
> ```
> jalon@Ripper:~/git/v$ git rev-list 982e359 ^c057b45 --count
> 9
> jalon@Ripper:~/git/v$
> ```
> 
> So, 9 commits after what you had at that time.
> 
> Now? Even further away...
> 
> ```
> jalon@Ripper:~/git/v$ git rev-list HEAD ^c057b45 --count
> 25
> jalon@Ripper:~/git/v$
> ```
> 
> You may have had the latest ZIP file or something, but that was not the latest version of V.
> 
> Recommended action: Delete your current V directory, use `git clone` to get the current source, and build it with `.\make.bat`.
> 
> Then whenever you run into a problem in the future, first do `v up` then try again. If it still fails, open an issue.
> 
> V is still changing rapidly enough that cloning the source and using `v up` to stay up-to-date is the best way to do things.

Yes, after the screenshot I have been updating every time before I post here. I used both v up and deleting and downloading the zip file. The result is the same. It just exits after the first line. If you want next time I will record my screen and post it here for you.

**Comment by Gebriel** [comment]
Ok I just updated if for the 7th time or something, now it is working.
