### ISSUE TITLE
Compilation on Windows 10 with - json.v

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#879]
**V version:**
0.1.10 - obtained by compiling source Jul 1 with Mingw

**OS:**
Windows 10

**What did you do?**
v run json.v
A problem with compiling json.c occurred.

**What did you expect to see?**
Normal output from json example program as on Linux/macOS

 
**What did you see instead?**
C:\Users\CVO//.vlang//json.c:71:11: fatal error: cJSON.c: No such file or directory
  #include "cJSON.c"
           ^~~~~~~~~
compilation terminated.
V panic: clang error

**Comment by Ivo-Balbaert** [comment]
In v 0.1.14 the message is:
C:\Users\CVO//.vlang//json.c:78:10: fatal error: cJSON.h: No such file or directory
 #include "cJSON.h"
          ^~~~~~~~~
compilation terminated.
V panic: clang error

When the file cJSON.h is copied to .vlang, the compilation succeeds and the program runs.

**Comment by medvednikov** [comment]
Fixed.
