### ISSUE TITLE
inconsistent way of syntax to updating variable

### ISSUE THREAD

**Issue by arhen** [vlang/v#88]
In the variable section of docs, u said:
> To change the value of the variable use =. In V variables are immutable by default. To be able to change the value of the variable, you have to declare it with mut.

but later in the loop section, specially at 'traditional' loop style,
`for i := 0; i < 10; i++ {`
`println(i)`
`}`

Why var 'i' can be changed without declaring it with 'mut'?

**Comment by medvednikov** [comment]
Good question.

I decided not to require `mut` here because the counter is always going to be mutable by definition.

**Comment by arhen** [comment]
Okay. I agree to this. looks simpler.

but u need it to explain this on docs. 

> simplifying something requires consistency and explanation

just random thought from me after read the docs.

**Comment by medvednikov** [comment]
Agreed, I’ll update the docs.

**Comment by medvednikov** [comment]
Done:

https://vlang.io/docs#for

**Comment by arhen** [comment]
Hell fast!, nice.
I have some random things about 'style' that i want to ask it to you. I'll postpone until there is no main bug. it's not necessary i think.

but maybe u want some brainstorming? lol.
keep working on. this cool stuff will be huge soon!
