### ISSUE TITLE
Compilation failed on Windows 10 - links_scraper.v

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#880]
**V version:**
0.1.10 - obtained by compiling source Jul 1 with Mingw

**OS:** 
Windows 10

**What did you do?**
v run links_scraper.v
(same problem with news_fetcher/v)

**What did you expect to see?**
Normal output from program

 
**What did you see instead?**
pass=1 fn=``
panic: download_win.v:10
redefinition of `http.download_file_with_progress`

**Comment by Ivo-Balbaert** [comment]
In 0.1.13, different message:

[Running] v run links_scraper.v
panic: http_win.v:228
undefined: `time`

**Comment by ntrel** [comment]
> undefined: time

Also reported in #798.

**Comment by ntrel** [comment]
> undefined: time

Fixed in master:
https://github.com/vlang/v/commits/master/vlib/http/http_win.v

But I'm not sure where to get `urlmon.h` from with Mingw.

**Comment by Ivo-Balbaert** [comment]
I can confirm that it works with master, nice!
