### ISSUE TITLE
V should automatically add [console] to fn main in GUI Windows apps that use println

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#8800]

**Comment by dumblob** [comment]
How will that work under the hood?

I'd actually say if no `[console]` nor `[gui]` is present, then for compilation target "Windows", the default should be seamless support for **both** GUI and console apps **by default** (e.g. by using [ansipipe](https://github.com/robhagemans/ansipipe ) as suggested in https://github.com/vlang/v/pull/7721#issuecomment-753127523 ). If the programmer wrote explicitly `[console]`, then it'll be compiled with **no regard** of anything GUI-related. And vice versa if the programmer wrote explicitly `[gui]`, then it'll be compiled with **no regard** of anything console-related.

But if the V community will not like this (for whatever reason), then please at least do **not** add any `[console]` to `main()` automatically without telling the user. And instead just issue a warning in case the target platform is Windows saying that any input & output will not work unless `[console]` is added.

**Comment by dumblob** [comment]
@pavi2410 thoughts?

**Comment by pavi2410** [comment]
Sorry! I am new to native development using C/C++/V. My opinion would be of no significance.
