### ISSUE TITLE
gg.draw_empty_poly does not consider ctx.scale

### ISSUE THREAD

**Issue by rpsrosario** [vlang/v#8807]
**V version:** V 0.2.2 b07f373.21bf8fe
**OS:** windows, Microsoft Windows 10 Home v19042 64-bit

**What did you do?**
Tried drawing a triangle through both `gg.draw_triangle` and `gg.draw_empty_poly` on a device with a DPI scale different from `1.0`.

**What did you expect to see?**
The triangle being drawn in the same location.
 
**What did you see instead?**
When the triangle was drawn through `gg,draw_triangle` it was in the expected position, but not when drawn through `gg.draw_empty_poly`.

Looking at the source code I can see that the `gg.Context.scale` is initialized to the `dpi_scale()`, which isn't `1.0` in my device. Furthermore, the code for `gg.draw_triangle` multiplies each coordinate by the `ctx.scale` while the code for the `gg.draw_empty_poly` does not. Pre-multiplying the coordinates supplied to the polygon version of the drawing by the context scale renders the triangle in the expected location.

**Comment by BenStigsen** [comment]
I'm still new to `git` 🤡, which is why you see this issue mentioned twice.
