### ISSUE TITLE
Compilation failed on Windows 10 - tetris.v

### ISSUE THREAD

**Issue by Ivo-Balbaert** [vlang/v#881]
**V version:** 
0.1.10 - Obtained from compiling source on Jul 1

**OS:** 
Windows 10

**What did you do?**
v run tetris.v

(same problem for word_counter.v / VCasino.v)

**What did you expect to see?**
Tetris game screen
 
**What did you see instead?**
pass=1 fn=``
panic: types_win.v:35
unexpected token `*`

But on the positive side:
Successful build on Windows 10 - hello_world.v / log.v / life.v all compile and run. Congratulations!

**Comment by rsrini7** [comment]
For me hello_word.v itself fails

D:\DevTools\v>v examples\hello_world.v
Looks like you are running V for the first time.
Setting VROOT to "D:\DevTools\v".
coudlnt create file "C:\Users\rsrini//.vlang//examples\hello_world.c"
check()
next token = `EOF`
pass=1 fn=``
panic: array.v:1
expected `module` but got `EOF`

**Comment by stappersg** [comment]
In #995  is `v` version v0.1.22 used and they report other errors.

Please retry   tetris.v compilation with a newer version of  V   (and report back)

**Comment by Ivo-Balbaert** [comment]
In v 0.1.13 on Windows 10, different message:
[Running] v run tetris.v
C:\Users\CVO//.vlang//tetris.c:77:10: fatal error: glad.h: No such file or directory
 #include "glad.h"
          ^~~~~~~~
compilation terminated.
V panic: clang error

**Comment by medvednikov** [comment]
Fixed.
