### ISSUE TITLE
Compile fails if pointer not specified  (demonstrated using gg library)

### ISSUE THREAD

**Issue by Ben-Fields** [vlang/v#8812]
**V version:** V 0.2.2 e4a67de
**OS:** Windows 10 64-bit

**What did you do?**
Omitted preceding `&` to a variable that should be a pointer.
Can be demonstrated with the Tetris example (2020-02-17):
Change `mut game := &Game{` to `mut game := Game{` (line 159).
Comment out `go game.run()` (line 175).

**What did you expect to see?**
The program compiles (auto-conversion to pointer as in docs), or the compiler gives the relevant error.
 
**What did you see instead?**
The program does not compile, and the compiler does not finish executing to give a relevant error.
Output: `builder error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: gcc "@C:\Path\To\AppData\Local\Temp\v\tetris.xxxxxx.tmp.c.rsp"`

**Comment by alic110** [comment]
Unfortunately, I also faced this problem, but I tried very hard and could not solve it. And finally I had to go back to Linux
I think everyone should see this

**Comment by Ben-Fields** [comment]
> Unfortunately, I also faced this problem, but I tried very hard and could not solve it. And finally I had to go back to Linux
> I think everyone should see this

Whether this is platform-specific or not, the workaround is in the title: be explicit about pointer types. The `tetris.v` example works just fine without the modifications listed in the report.

**Comment by spytheman** [comment]
A minimal example for this problem is:
```v
struct Abc { data voidptr }
struct Xyz { x int }
fn main() {
    a := Abc{ data: Xyz{} }
    println(a)
}
```

**Comment by scroot** [comment]
Reference document:

**Comment by felipensp** [comment]
> ```v
> struct Abc { data voidptr }
> struct Xyz { x int }
> fn main() {
>     a := Abc{ data: Xyz{} }
>     println(a)
> }
> ```

Currently the checker reports:

```
bug.v:4:15: error: allocate `Xyz` on the heap for use in other functions
    2 | struct Xyz { x int }
    3 | fn main() {
    4 |     a := Abc{ data: Xyz{} }
      |               ~~~~~~~~~~~
    5 |     println(a)
    6 | }
bug.v:4:15: error: cannot assign to field `data`: expected a pointer `voidptr`, but got `Xyz`
    2 | struct Xyz { x int }
    3 | fn main() {
    4 |     a := Abc{ data: Xyz{} }
      |               ~~~~~~~~~~~
    5 |     println(a)
    6 | }
```
