### ISSUE TITLE
Unicode support in Character Literals

### ISSUE THREAD

**Issue by spy16** [vlang/v#882]
**V version:** V 0.1.10
**OS:** macOS Version 10.13.6

**What did you do?**
Try to print a non ASCII character literal `∂`.

```
fn main() {
    println(`∂`)
}
```

**What did you expect to see?**

Program should be compiled successfully and print when run.
 
**What did you see instead?**

```
panic: main.v:2
invalid character literal (more than one character: 3)
```

Note: This also happens for characters like `ß`, `è`

**Comment by Ivo-Balbaert** [comment]
The program now compiles, it gives 14846082 as output on Playground.

**Comment by spy16** [comment]
That doesn't seem right. Unicode value for `∂` is `0x2202` (Dec 8706)..

**Comment by crthpl** [comment]
`rune.str()` now works and casting to int properly shows `8706`, can close.
