### ISSUE TITLE
Not able to build V from source

### ISSUE THREAD

**Issue by archanpatkar** [vlang/v#883]
**V version:** 
0.2

**OS:** 
MacOS

**What did you do?**
```make```

**What did you expect to see?**
To be built successfully 
 
**What did you see instead?**
```
rm -f v.c v vprod
curl -Os https://raw.githubusercontent.com/vlang/vc/master/v.c
cc -march=native -std=gnu11 -w -o v v.c
./v -o v compiler
pass=2 fn=`ustring_tmp`
panic: string.v:640
expected type `[]int`, but got `int`
make: *** [v] Error 1
```

**Comment by medvednikov** [comment]
git pull

**Comment by archanpatkar** [comment]
`git pull`
```
Already up to date.
```

**Comment by medvednikov** [comment]
It should work. Delete the repository, and clone it again :)

**Comment by archanpatkar** [comment]
It worked thanks, might have been some cache problem?

**Comment by nachoverdon** [comment]
I had the same problem and pointed it out on Discord. 

[12:00 PM] bazoo: does curl -sO https://raw.githubusercontent.com/vlang/vc/master/v.c cache the file or something? I tried several times, but kept downloading the old file
[12:00 PM] bazoo: had to replace the content manually, lol
[12:00 PM] bazoo: hope that's not an issue with travis etc

**Comment by medvednikov** [comment]
@nachoverdon no, curl doesn't cache the file. That's very strange.

**Comment by medvednikov** [comment]
It's not an issue with Travis, it does a completely clean build every time.
