### ISSUE TITLE
Nested option unwrap does not work

### ISSUE THREAD

**Issue by mcastorina** [vlang/v#8885]
**V version:** `V 0.2.2 10de905.1a838b1`
**OS:** `linux, Linux version 5.10.16-arch1-1 (linux@archlinux) (gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.36) #1 SMP PREEMPT Sat, 13 Feb 2021 20:50:18 +0000`

**What did you do?**

```v
fn maybe() ?int {
	return 1
}
fn test(i int) {
	println('i: $i')
}

fn main() {
	test(maybe()?)
}
```

```
v run test.v
```

**What did you expect to see?**
```
i: 1
```
 
**What did you see instead?**
Compilation error: cannot convert `Option_int` to `int`

**Comment by spaceface777** [comment]
Fixed in #9021.
