### ISSUE TITLE
fmt:a bug when format the following code

### ISSUE THREAD

**Issue by lydiandy** [vlang/v#8893]
**V version:** 
V 0.2.2 f18adf7
**OS:** 
mac

**What did you do?**
here is the sample code:
```
module main

fn main() {
	//rune key unicode
	mut m3 := {
		`!`: 2 	//this is comment
		`%`: 3
	}
	println(m3)
}

```

**What did you expect to see?**
The bug is caused by the comment

main.v:7:3: error: unexpected char `%`, expecting `:`
    5 |     mut m3 := {
    6 |         `!`: 2     //this is comment
    7 |         `%`: 3
      |         ~~~
    8 |     }
    9 |     println(m3)

vfmt error while formatting file: main.v .
 
**What did you see instead?**

**Comment by changrui** [comment]
I have test it, and running well, output : `{`!`: 2, `%`: 3}`.

**Comment by lydiandy** [comment]
@changrui,run the samle code is passed, but when you format the code  will fail.
