### ISSUE TITLE
Unable to perform struct embedding in a interface

### ISSUE THREAD

**Issue by smartiniOnGitHub** [vlang/v#8902]
Hi all,
to reduce the manual duplication (and keep aligned) of fields in an interface (fields already defined in a struct), I'm trying to use struct embedding, but at the moment it seems not working with interfaces.

**V version:** V 0.2.2 9a7ecf2.2516c07
**OS:** linux, Ubuntu 20.04.2 LTS

**What did you do?**
Embed a struct inside an interface, it's useful to reduce the clutter on fields to have even in the interface.
For example:
```
struct PluginBase {
	name         string [required]
	version      string
	dependencies []string = []
	cfg          voidptr
mut:
        info         map[string]string
}

pub interface Sample {
	// name         string // ok
        // etc ...
        // instead, get some common fields via struct embedding (if possible)
	PluginBase // error
        // my_prop string // add other specific fields ...
	// load() // ok
}
```
Hope you find useful this ability.

**What did you expect to see?**
Compilation success.
 
**What did you see instead?**
Compiler (parser ?) error:
```
error: expecting type declaration
```

Not sure it's bug or a completion of a feature (struct embedding).

Thanks

**Comment by smartiniOnGitHub** [comment]
Maybe this is is some way related to [issue#9032](https://github.com/vlang/v/issues/9032), just resolved; but still current issue is not resolved ... let's see if my syntax for struct embedding in an interface (the same used for struct embedding in structs) it worth the effort.
Otherwise be free to drop this issue. Thanks.

**Comment by galman33** [comment]
Fixing this issue would be great!

**Comment by spaceface777** [comment]
This should be possible soon.

**Comment by smartiniOnGitHub** [comment]
Hi all, 
@spaceface777 thanks a lot for the fix :-) .

**Comment by nedpals** [comment]
@smartiniOnGitHub Sure thing :smile:

**Comment by smartiniOnGitHub** [comment]
See similar [issue#9918](https://github.com/vlang/v/issues/9918) (soon to be fixed).

**Comment by JalonSolov** [comment]
Why embed a struct in an interface??  An interface is supposed to just be a description of properties.  A struct is a more concrete object.  Embedding a struct in an interface makes it just another struct.

**Comment by smartiniOnGitHub** [comment]
Hi @JalonSolov , the only reason is to to reduce the manual duplication (and keep aligned) of fields in an interface (using fields already defined in a struct), but I understand your concern ... maybe a better solution would be to define fields in an interface and embed in my interface, what do you think ?
