### ISSUE TITLE
Struct fields default seems to not be set in some cases

### ISSUE THREAD

**Issue by skrtdev** [vlang/v#8910]
**V version:** 0.2.2 d1cebcb
**OS:** macOS

**What did you do?**
```
struct Example {
	var string = 'hello'
mut:
	numbers []int = [12]
}

var := Example{'hi'}
```

**What did you expect to see?**
I expected to see numbers field set to his default value
 
**What did you see instead?**
```
repr.v:7:8: error: too few fields in `Example` literal (expecting 2, got 1)
    5 | }
    6 | 
    7 | var := Example{'hi'}
```

**Comment by skrtdev** [comment]
it happens even without `mut:`

**Comment by serkonda7** [comment]
Try `var := Example{var: 'hi'}`.
You have to specify each field in short struct init syntax or name them.

**Comment by skrtdev** [comment]
Why can't it work with short syntax? It's literally the same, but using positional arguments instead of named arguments

**Comment by serkonda7** [comment]
But you miss a position. It's like a function call with a missing parameter. The compiler cannot know what field you assign the value to or what parameter you left out.

**Comment by skrtdev** [comment]
He can know it by checking types (joking). But it works without any parameter. Can't it just assign fields according to position?

**Comment by serkonda7** [comment]
Each field that is not set on initialization will get a default value. Either the one you provided or an empty value (e.g. 0 for ints, empty string, ...)

**Comment by skrtdev** [comment]
Yeah but why can't it just assign that string to var field, and let numbers field be default?

**Comment by serkonda7** [comment]
As I already said, the compiler has no idea what field you want to assign the value to.

**Comment by skrtdev** [comment]
Yes but numbers fields is not set to default. Why, if it successfully set var even if I use it as a positional argument? (In fact it says: "expecting 2, got 1")

**Comment by serkonda7** [comment]
positional arguments are only allowed for less than three fields and follow the principle all or none.

You cannot leave out some fields when using positional arguments.

**Comment by skrtdev** [comment]
Ok I understand, but I think that compiler can know what fields I am setting. However, thanks for your explanation

**Comment by serkonda7** [comment]
No problem, I'm happy to help :) 

In your case it may be fine, but a struct could also have three integer fields for example.
