### ISSUE TITLE
Compiletime code generation

### ISSUE THREAD

**Issue by zakuro9715** [vlang/v#8915]
I want compiletime code generation like this.

gen/fn_names.v:

```v
import os
import v.pref
import v.parser
import v.table
import v.ast

path := os.args[1]
mut prefs := &pref.Preferences{ path: path, only_check_syntax: true }
prefs.fill_with_defaults()
file := parser.parse_file(path, table.new_table(), .skip_comments, prefs, &ast.Scope { parent: 0 })
println('fn func_names() []string {')
println('\treturn [')
for stmt in file.stmts {
	if stmt is ast.FnDecl {
		name := stmt.name.trim_prefix('${file.mod.short_name}.')
		println("\t\t'$name',")
	}
}
println('\t]')
println('}')
```

file.v:

```v
module mymodule

fn foo() {}
fn bar() {}

$generate('v', 'run', 'gen/fn_names.v', @FILE)
```

it will be

```v
module mymodule

fn foo() {}
fn bar() {}

fn func_names() []string {
        return [
                'foo',
                'bar',
        ]
}
```

How do you guys think about this?

**Comment by ntrel** [comment]
I think this would break potentially any time we restructure code in the compiler. Instead, enhance and use compile-time reflection.

> $generate('v', 'run', 'gen/fn_names.v', @FILE)

I think this is a security risk that can inject malicious code. We should not rely on `v` being the V compiler.

**Comment by zakuro9715** [comment]
How about add v generate command like 'go:generate'?

I want to auto code generation

@spytheman @medvednikov @JalonSolov

**Comment by medvednikov** [comment]
we tend to solve this without generation, for example, generics, $embed_file, etc

or do you need for something like macros?

**Comment by JalonSolov** [comment]
We should be able to solve things like this within V, instead of having to have V + Python + text file + ... whatever else.

**Comment by elimisteve** [comment]
@zakuro9715 Seems like `$embed_file()` is pretty perfect for your situation. @medvednikov Maybe at compile time we could let people operate on the `[]byte` returned by `$embed_file()` 

    strs := $fn() []string {
        return $embed_file('data.txt').str().split_into_lines()
    }()

or at least

    strs := $embed_file('data.txt').str().split_into_lines()

**Comment by elimisteve** [comment]
Or even

```v
strs := $fn() []string {
    data := $embed_file('data.txt')
    if data.len == 0 {
        panic("data.txt must exist and be non-empty")
    }
    return data.str().split_into_lines()
}()
```

**Comment by elimisteve** [comment]
Of course, permitting totally arbitrary V code within this imagined `$fn` block would be dangerous because one should be able to compile V code without arbitrary side effects.

Obviously it's simpler to not allow any of this, but as always, if we can find a simple way to do it... Could be worth it.

**Comment by elimisteve** [comment]
@zakuro9715 You could also just add a line to your build process :slightly_smiling_face: . Or a git hook.

**Comment by d1y** [comment]
> How about add v generate command like 'go:generate'?
> 
> 
> 
> I want to auto code generation
> 
> 
> 
> @vlang/v-devs 

the command is bad

v not is go

**Comment by zakuro9715** [comment]
OK. I like go:generate but 'v not is go' is completely right. V members seems to like it. so I close this.

elimisteve's way seems to be good enough for me
