### ISSUE TITLE
Compiler Enforced Prefix for Methods That Require a Mutable Receiver

### ISSUE THREAD

**Issue by human154** [vlang/v#8916]
With this proposal all methods that require a mutable receiver would follow a compiler enforced naming convention.  These methods would be required to start with "mut_".   As in:

`list.mut_sort()`

Benefits:

1. This proposal would make code easier to understand. It would make all methods easier to understand!  Increased understandability is one of the great and underrated benefits of immutable code and this is a chance to take advantage of that increased understandability!  **With this proposal, someone reading V can read `list.sort()` and immediately and confidently know what is happening with that code, i.e. that `sort()` is going to be returning a new value (rather than mutating the list.) We would get that increased understandability for free for methods that don't mutate!**  By for free I mean: with no extra typing for non-mutating methods.  It would be immediately clear which one of the two possibilities is happening!  Likewise one would know that `list.mut_sort()` could be mutating a list instead of just returning a new sorted list.  I think **the extra effort of writing "mut_" once in a while is worth it to make all method calls so much easier to understand!**

2. With the proposed change, the language will have greater consistency.  There is an existing requirement to write the "mut" keyword before a mutable function argument. Why would we have that feature and not do the same for method calls?  **Lets make the language more consistent across functions and method calls!**

3. Admittedly, the required "mut_" prefix is one more thing to learn and may require extra typing if you don't already need to make the mut/non-mut naming distinction.  However, these will be offset by relatively significant ongoing benefits forever after. The time taken to learn this extra feature and the extra typing is easily offset by the time saved with generally easier to understand method calls. We will save the time it would otherwise take to know if code like `list.sort()` is mutating or not. If code is read more than it is written, then this benefit should be given priority.  For those new to the language, learning this (proposed) feature and its syntax won't take much more time than trying to understand why it isn't part of the language (i.e. why must mutability be identified in function calls but not in method calls?") Finally, by avoiding silent mutation and making mutability more obvious we get clearer code. **With clearer code we would gain more maintainable code**.

4. **The mutating and non-mutating versions of `list.sort()` need to be named differently anyway.**  This proposal would result in this important distinction having **a consistent naming convention** across all V code! 

5. This proposal would be consistent with, **encourage and emphasize "immutability by default"** by making immutability a little more convenient than mutation and by avoiding silent mutation.
The proposal makes undecorated methods clearly identifiable as not mutating the receiver and (incidentally) a little easier to use than mutating methods which would require typing the prefix.  That carries a message that is consistent with the theme of "immutability by default".

6. Searching for methods and code completion could be enhanced with the extra information of this (enforced) naming convention.  Since one would know in advance if they are searching for mutating or non-mutating methods, the naming convention can make it easier and **faster to search and select the desired methods** and exclude the undesired.

**Comment by human154** [comment]
This proposal, without further changes, would result in definitions where the word "mut" must be written twice in mutable method signatures...

Currently, without this proposal, we have this for a mutating method definition:

fn (mut u User) register() {
	...
}

If we change the method naming as per this proposal we have:

fn (mut u User) mut_register() {        // redundant "mut"
	...
}

However, if we do go with this proposal, the first "mut" could be inferred from the "mut_" prefix in the method name, so this could be simplified to:

fn (u User) mut_register() {      // its implied that User is "mut"
	...
}

( Which I think actually is actually nice to read for what its worth. )

**Comment by serkonda7** [comment]
Just my personal opinion:
- In general I dislike enforced identifier prefixes. (There were a lot of discussions around `c_name` for consts too)

General things:
- The prefix might lead to confusion as the methods seems to be mutable, not the receiver.
- Internally a methods receiver is handled as a parameter. So `fn (mut f Foo) mymethod(param int)` is treated as `fn mymethod(mut f Foo, param int)`. Therefore it's a lot more consistent right now (your 2. point).

My questions:
- What to do with pointers? Force  `fn (f &Foo) method()` to be `fn (f Foo) ptr_method()`? 
- What order when the receiver is `mut f &Foo`?

Finally, you're free to use `mut_` prefixes in your own code.

**Comment by human154** [comment]
Thanks for taking the time to share your thoughts @serkonda7.  Its good to at least know the reason of a down vote! :)

**Comment by human154** [comment]
I've learned that a receiver.sort!() (which I like a lot as well) has been proposed and rejected.
In light of that, I'm going to close this and propose receiver!sort().

**Comment by medvednikov** [comment]
@human154 this can stay open, I'm still seriously considering it.

It would be consistent with mutable args and safer than current hidden mutable receivers.

**Comment by medvednikov** [comment]
I'm referring to `arr.sort!()`

**Comment by medvednikov** [comment]
The need to write `!` can be take care of by vfmt.

**Comment by medvednikov** [comment]
There was a poll, and more people were in favor:

https://twitter.com/v_language/status/1269205056118816768

**Comment by ntrel** [comment]
@medvednikov 
> this can stay open, I'm still seriously considering it.
> I'm referring to arr.sort!()

That is covered by the new issue, so closing this: https://github.com/vlang/v/issues/9013
