### ISSUE TITLE
`f64 += 1`:  No need and can not change to `f64++`, please review it.

### ISSUE THREAD

**Issue by changrui** [vlang/v#8919]
**V version:** 
`v 0.2.2 977a625`
**OS:** 
`Windows 10 Build 21318`
**What did you do?**
`mut f := 1.1; f +=1`
**What did you expect to see?**
`running well` 
**What did you see instead?**
```
main.v:3:3: error: use `++` instead of `+= 1`
    1 | mut f := 1.1
    2 | 
    3 | f += 1
      |   ~~
```

**Comment by changrui** [comment]
oh, no, `f64++` is correct in v.

**Comment by Gladear** [comment]
Can we agree that this issue can be closed ?

**Comment by UweKrueger** [comment]
Using `++` for `f64` looks weired, indeed. But it's possible to do
```v
mut f := 1.1
f += 1.
```

**Comment by dumblob** [comment]
Indeed, this is weird (though well defined I'd say). Let's see what others think. I have no strong feelings about this at this point. But maybe there is something I'm missing.
