### ISSUE TITLE
V 0.1.11 with cross compilation for Windows is out!

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#892]
Cross compiling for Windows is as simple as 

```
v -os windows hello_world.v
v -o vwin.exe -os windows compiler
```

As you can see, it's even possible to cross compile V itself. In fact, that's what I'm doing for the pre-built V binaries.

This works on Linux and macOS. You will need to install Clang and LLD linker and download a 41 MB file with Windows files.

V will give you the link to download this file.

Lots of Windows issues were fixed, but not all of them. V will soon work very well on Windows.

**Comment by r-k-o** [comment]
downloaded, from:  https://vlang.io
Download V alpha 0.1.11
includes binaries for 3 systems

extracted, set path to f:\v

results in:

F:\V>v_windows -o examples/tetris/tetris.v
ATTR =8208
Looks like you are running V for the first time.
ATTR =8208
V repo not found. Go to https://vlang.io to download V.zip
or install V from source.

**Comment by medvednikov** [comment]
The command you are using is incorrect: 

`v_windows -o examples/tetris/tetris.v`

it should be 

`v_windows -o tetris.exe examples/tetris/tetris.v`

V can't compile Tetris yet. Also try moving it to your primary disk (C:/ ?), the one where Windows is installed.

**Comment by r-k-o** [comment]
Ok - true.
F:\V>v_windows -o tetris.exe examples/tetris/tetris.v
ATTR =8208
Looks like you are running V for the first time.
ATTR =8208
V repo not found. Go to https://vlang.io to download V.zip
or install V from source.

no change for c:

C:\V>v_windows -o xxx.exe xxx.v
ATTR =8208
Looks like you are running V for the first time.
ATTR =8208
V repo not found. Go to https://vlang.io to download V.zip
or install V from source.
