### ISSUE TITLE
Positional parameter does not work even with only one parameter

### ISSUE THREAD

**Issue by skrtdev** [vlang/v#8921]
**V version:** 0.2.2 d1cebcb.977a625
**OS:** macOS

**What did you do?**
```
struct Example {
	var []int = [12]
}

pub fn func(e Example) &Example {
	return &e
}

fn test_useless() {
	func(var: [12]) // this works
	func([12]) // this causes error
}
```

**What did you expect to see?**
nothing
 
**What did you see instead?**
```
repr_test.v:11:7: error: cannot use `[]int` as `Example` in argument 1 to `func`
    9 | fn test_useless() {
   10 |     func(var: [12]) // this works
   11 |     func([12]) // this causes error
      |          ~~~~
   12 | }
```

**Comment by changrui** [comment]
Yes, it should be.

**Comment by skrtdev** [comment]
Is it the right behaviour?

**Comment by StunxFS** [comment]
> Is it the right behaviour?

Yes, it is the correct behavior.
The `func` function receives a parameter of type `Example`, therefore the compiler will expect the type `Example`.

**Comment by skrtdev** [comment]
ok thanks
