### ISSUE TITLE
Struct variable access issue when appending

### ISSUE THREAD

**Issue by SurmanPP** [vlang/v#8923]
**V version:** 
**OS:** 
OS: linux, Pop!_OS 20.10
Processor: 24 cpus, 64bit, little endian, AMD Ryzen 9 3900XT 12-Core Processor
CC version: cc (Ubuntu 10.2.0-13ubuntu1) 10.2.0
vexe mtime: 2021-02-23 08:19:32
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 4e2418e.977a625
Git version: git version 2.27.0
Git vroot status: weekly.2021.6-237-g977a625a
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81
**What did you do?**
I created a new struct for vweb to run and added an string array to store data
```
struct App {
vweb.Context
array []string
}

```
Then I wrote to the array and tried to read it's content.
```
app.array = ["test"]
println(app.array)
```

**What did you expect to see?**
The program printing the array
 
**What did you see instead?**
This error
7fd9d72a51f2 : at ???: RUNTIME ERROR: invalid memory access
/tmp/v/vlay.12822605627721114474.tmp.c:19789: by main__App_index
/tmp/v/vlay.12822605627721114474.tmp.c:19387: by vweb__handle_conn_T_main__App
/tmp/v/vlay.12822605627721114474.tmp.c:3503: by vweb__handle_conn_T_main__App_thread_wrapper
7fd9d7107590 : by ???

**Comment by changrui** [comment]
Maybe `app.array << 'text'`.

**Comment by JalonSolov** [comment]
Since this is an incomplete example, I can't test it.  However, my first suggestion is to add the `mut:' specifier in your struct:
```v
struct App {
mut:
    vweb.Context
    array []string
}
```

**Comment by SurmanPP** [comment]
The code thats throwing that error is:
```vlang
struct App {
vweb.Context
mut:
array []string
}

fn main() {
vweb.run<App>(8081)
}
pub fn (mut app App) index() vweb.Result{
app.array = ["test"]
println(app.array)
}
```
It's only happening when using the vweb struct

**Comment by mcastorina** [comment]
Try updating your V version `v up`. Your example works (with minor modifications) for me (on version V 0.2.2 d1cebcb). Full example I'm running:

```v
import vweb

struct App {
        vweb.Context
mut:
        array []string
}

fn main() {
        vweb.run<App>(8081)
}
pub fn (mut app App) index() vweb.Result {
        app.array = ['test']
        println(app.array)
        return app.text('hello')
}
```

```
» v run test.v
[Vweb] Running app on http://localhost:8081
['test']
```

```
» curl localhost:8081
hello
```

**Comment by SurmanPP** [comment]
it works now mhh

**Comment by SurmanPP** [comment]
It happens when appending
```vlang
app.array << ["test"]
println(app.array)
```
Does not work
```vlang
app.array = ["test"]
println(app.array)
```

**Comment by JalonSolov** [comment]
Ah, that makes sense.  In the failure case, you haven't initialized the array in the struct, only told it what type it would be.

In the success case, you are initializing the struct, so all is well.

V does need an error message for this... maybe something explicit like
```
error:  cannot append to uninitialized array
```

**Comment by JalonSolov** [comment]
Need to leave this open until V either has a better error message, or arrays in structs get auto-initialized.

**Comment by spaceface777** [comment]
#8932 was opened instead, to track the root issue here :)
