### ISSUE TITLE
Pass generic type down to callstack

### ISSUE THREAD

**Issue by AndriiDidkivsky** [vlang/v#8934]
**V version:**  V 0.2.2 977a625
**OS:** Ubuntu 20.04.2 LTS

**What did you do?** 
Tried to play with generics and x.json2

```
module main
import x.json2

fn main () {
	test := TestJSON2{
		token: 'tok123',
		endpoint: 'end123'
	}
	s := encode(test)
	println(s)
}

pub struct TestJSON2 {
	pub: 
	    token string 
	    endpoint string
}


pub fn (p TestJSON2) to_json() string {
    mut obj := map[string]json2.Any
    obj['token'] = p.token
    obj['endpoint'] = p.endpoint
    return obj.str()
}

pub fn encode<T>(data T) string {
	return json2.encode(data)
}
```

if I convert without passing generic down to encode function it works 
```
module main
import x.json2

fn main () {
	test := TestJSON2{
		token: 'tok123',
		endpoint: 'end123'
	}
	s := json2.encode(test)
	println(s)
}
```
**What did you expect to see?**
'{"token":"tok123","endpoint":"end123"}'

 
**What did you see instead?**
V panic: array.get: index out of range (i == 0, a.len == 0)
/tmp/v/v2.8109746763836712870.tmp.c:11613: at v_panic: Backtrace
/tmp/v/v2.8109746763836712870.tmp.c:11115: by array_get
/tmp/v/v2.8109746763836712870.tmp.c:47985: by v__gen__c__Gen_return_statement
/tmp/v/v2.8109746763836712870.tmp.c:44674: by v__gen__c__Gen_stmt
/tmp/v/v2.8109746763836712870.tmp.c:44418: by v__gen__c__Gen_stmts_with_tmp_var
/tmp/v/v2.8109746763836712870.tmp.c:44401: by v__gen__c__Gen_stmts
/tmp/v/v2.8109746763836712870.tmp.c:50574: by v__gen__c__Gen_gen_fn_decl
/tmp/v/v2.8109746763836712870.tmp.c:50414: by v__gen__c__Gen_gen_fn_decl
/tmp/v/v2.8109746763836712870.tmp.c:50358: by v__gen__c__Gen_process_fn_decl
/tmp/v/v2.8109746763836712870.tmp.c:44553: by v__gen__c__Gen_stmt
/tmp/v/v2.8109746763836712870.tmp.c:44418: by v__gen__c__Gen_stmts_with_tmp_var
/tmp/v/v2.8109746763836712870.tmp.c:44401: by v__gen__c__Gen_stmts
/tmp/v/v2.8109746763836712870.tmp.c:43755: by v__gen__c__gen
/tmp/v/v2.8109746763836712870.tmp.c:56217: by v__builder__Builder_gen_c
/tmp/v/v2.8109746763836712870.tmp.c:56226: by v__builder__Builder_build_c
/tmp/v/v2.8109746763836712870.tmp.c:56268: by v__builder__Builder_compile_c
/tmp/v/v2.8109746763836712870.tmp.c:57309: by v__builder__compile
/tmp/v/v2.8109746763836712870.tmp.c:58098: by main__main
/tmp/v/v2.8109746763836712870.tmp.c:58466: by main

**Comment by yuyi98** [comment]
Fixed.

```vlang
module main

import x.json2

fn main() {
	test := TestJSON2{
		token: 'tok123'
		endpoint: 'end123'
	}
	s := encode(test)
	println(s)
}

pub struct TestJSON2 {
pub:
	token    string
	endpoint string
}

pub fn (p TestJSON2) to_json() string {
	mut obj := map[string]json2.Any{}
	obj['token'] = p.token
	obj['endpoint'] = p.endpoint
	return obj.str()
}

pub fn encode<T>(data T) string {
	return json2.encode(data)
}

PS D:\Test\v\tt1> v run .
{"token":"tok123","endpoint":"end123"}
```
