### ISSUE TITLE
net: dial_tcp does not report connection error

### ISSUE THREAD

**Issue by maxux** [vlang/v#8940]
**V version:** V 0.2.2 66c85aa
**OS:** Linux (Gentoo)

**What did you do?**
Trying to connect a port not listening:
```v
conn := net.dial_tcp("127.0.0.1:1234") or { panic(err) }
println(conn)
```
I can confirm it's not listening:
```sh
$ nc 127.0.0.1 1234
nc: connect to 127.0.0.1 port 1234 (tcp) failed: Connection refused

```

**What did you expect to see?**
Any error returned (panic in this case).
 
**What did you see instead?**
```
&TcpConn{ write_deadline: 0000-00-00 00:00:00, read_deadline: 0000-00-00 00:00:00, read_timeout: -64771072, write_timeout: -64771072, sock: net.TcpSocket{   handle: 3 } }
```

It's only when trying to send data to the socket, the error comes:
```
V panic: net: socket error: 111
---
ECONNREFUSED    111     /* Connection refused */
```

**Comment by medvednikov** [comment]
Fixed. Results in an error now.
