### ISSUE TITLE
Can't compile net.html

### ISSUE THREAD

**Issue by AndriiDidkivsky** [vlang/v#8942]
**V version:** V 0.2.2 977a625
**OS:** linux, Ubuntu 20.04.2 LTS 

**What did you do?**
Play with net.html module

```
module main

import net.html

fn main () {
}
```

**What did you expect to see?**
compiled without errors

 
**What did you see instead?**
compile time error 

```
v/vlib/net/html/dom.v:28:19: error: writeln() returns an option, so it should have either an `or {}` block, or `?` at the end
   26 |     $if debug {
   27 |         if data.len > 0 {
   28 |             dom.debug_file.writeln(data)
      |                            ~~~~~~~~~~~~~
   29 |         }
   30 |     }
v/vlib/net/html/parser.v:56:22: error: writeln() returns an option, so it should have either an `or {}` block, or `?` at the end
   54 |     $if debug {
   55 |         if data.len > 0 {
   56 |             parser.debug_file.writeln(data)
      |                               ~~~~~~~~~~~~~
   57 |         }
   58 |     }
```

**Comment by spytheman** [comment]
Weird ... This triggers only for `-g` and `-cg`.

**Comment by spaceface777** [comment]
well, the erroring code is wrapped in an `$if debug {}` block, which is only checked if `-g` / `-cg` is passsed :)

**Comment by AndriiDidkivsky** [comment]
oh, yeah. It's my mistake ) I ran with -cg while to get more detailed error messages. Sorry guys )

**Comment by JalonSolov** [comment]
Not a mistake.  It shouldn't have failed just because you used a different option on the command line.
