### ISSUE TITLE
Panic in string.v; expected type '[]int', to 'int'

### ISSUE THREAD

**Issue by Tembocs** [vlang/v#895]
**V version: 0.1.11** 
**OS: Windows 10 x64** 

**What did you do?**
Tried to compile hello_world.v example.

**What did you expect to see?**
'Hello World!' printed on the console.
 
**What did you see instead?**
```ATTR =16
ATTR =16
ATTR =16
ATTR =16
pass=2 fn=`ustring_tmp`
panic: string.v:640
expected type `[]int`, but got `int` ```

**Comment by archanpatkar** [comment]
Try to delete the repo and clone it again then try to build and compile. I faced the same issue and it was resolved
