### ISSUE TITLE
using vstring literal as argument to c interop function passes as c string literal

### ISSUE THREAD

**Issue by shadowninja55** [vlang/v#8955]
**V version:** V 0.2.2 8e69d36.57d1b5b
**OS:** windows, Microsoft Windows 10 Pro v19042 64-bit

**What did you do?**

err = C.mciSendString("play song wait".to_wide(), C.NULL, 0, 0)

**What did you expect to see?**

generated c: don't know exactly, but "play song wait" should be a vstring here,  not a c string literal
 
**What did you see instead?**

generated c: `err = mciSendString(string_to_wide("play song wait"), NULL, 0, 0);`

**Comment by StunxFS** [comment]
```v
// passing a string literal to a C function call results in a C string, not a V string
C.sqlite3_open('users.db', &db)
```
from: [docs](https://github.com/vlang/v/blob/master/doc/docs.md#calling-c-functions-from-v)

**Comment by spaceface777** [comment]
yeah, but that should not be happening if you're also calling a method on that literal :)
