### ISSUE TITLE
`type Fn = fn (mut Type)` fails

### ISSUE THREAD

**Issue by StunxFS** [vlang/v#8956]
**V version:** V 0.2.2 57d1b5b
**OS:** Ubuntu 20.04

**What did you do?**
I have tried creating an alias for a type of function that receives a mutable parameter:
```v
type Fn = fn (mut Type)
```

**What did you expect to see?**
That this will work
 
**What did you see instead?**
```v
builder.v:13:29: error: expecting type declaration
   11 | }
   12 | 
   13 | type RunFn = fn (mut Builder)
      |                             ^
   14 | 
   15 | pub fn new_builder() Builder {
```

The same happens if it is declared in the parameter of a function:

```v
builder.v:17:51: error: expecting type declaration
   15 | }
   16 | 
   17 | pub fn (mut b Builder) run(run_fun fn (mut Builder)) {
      |                                                   ^
   18 |     run_fun(b)
   19 | }
```

**Comment by Gladear** [comment]
I think this is a known bug. If you need a workaround, you can name the parameter (`fn (mut builder Builder)`) 🙂

**Comment by shadowninja55** [comment]
this works on latest v
