### ISSUE TITLE
Cannot base64 encode data containing a 0 byte

### ISSUE THREAD

**Issue by mcastorina** [vlang/v#8958]
**V version:** V 0.2.2 10de905.0fa2f6d
**OS:** linux, Linux version 5.11.1-arch1-1 (linux@archlinux) (gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.36.1) #1 SMP PREEMPT Tue, 23 Feb 2021 14:05:30 +0000

**What did you do?**
```v
import encoding.base64

data := [byte(0x41), 0x00, 0x41]
enc := base64.encode(string(data))
println(enc)
```

```
v run test.v | base64 -d | hexdump
```

**What did you expect to see?**
```
0000000 0041 0041
```
 
**What did you see instead?**
```
0000000 0041
```

**Comment by mcastorina** [comment]
The problem is that `base64.encode` operates on strings which truncates the data.

**Comment by yuyi98** [comment]
I think the API is wrong, it should be `base64.encode(src []byte) string`.

**Comment by mcastorina** [comment]
I've since learned that V strings *can* contain null bytes, however we are still going to change the signatures to use `[]byte`.

**Comment by JalonSolov** [comment]
With that PR merged, the default methods take `[]byte` but there are new ones that can take `string`.  So you can use whichever makes the most sense for your code, without having to convert.
