### ISSUE TITLE
Can't add anonymous function to map of functions

### ISSUE THREAD

**Issue by Terisback** [vlang/v#8965]
**V version:** V 0.2.2 9e06af8.3362d7e
**OS:** linux, Ubuntu 20.04.1 LTS (WSL 2)

Problem from #6601 issue

**What did you do?**
```v
fn main()
{
	mut woop := map{
		'what': fn(){
			println("whoopity whoop")
		}
	}
	// Works!
	woop['what']()

	woop['shat'] = fn() {
		println("shoopity shoop")
	}
	// Doesn't work
	woop['shat']()
}
```

**What did you expect to see?**
```v
whoopity whoop
shoopity shoop
```
 
**What did you see instead?**
```v
whoopity whoop
RUNTIME ERROR: invalid memory access
```

**Comment by Delta456** [comment]
This happens because `woop['shat'] = fn() { println("shoopity shoop" }` doesn't work.
