### ISSUE TITLE
C compilation errors do not show on Windows 10

### ISSUE THREAD

**Issue by Cthutu** [vlang/v#8966]
**V version:** V 0.2.2 3362d7e
**OS:** Window 10

**What did you do?**
I compiled with a misspelt C constant.  That is, typed `C.CS_OWND` instead of `C.CS_OWNDC`.  This caused an error in C compilation.

**What did you expect to see?**
I expected to see the C compiler error during compilation.
 
**What did you see instead?**
I saw no errors.  I had to add the command line `-no-retry-compilation` to see them.  I do not have `gcc` or `clang` installed on my system.  Only MSVC and tcc.  I think V was using the TCC backend.

**Comment by spytheman** [comment]
Fixed in 77b3440 .
