### ISSUE TITLE
V UP did not work on Windows 10

### ISSUE THREAD

**Issue by Cthutu** [vlang/v#8967]
**V version:** V 0.2.2 f67a4c3
**OS:** Windows 10

**What did you do?**
I had a previous version of V and typed `v up`.  This did show a message saying "Updating V..." but I don't think the version changed.  I had to `git pull` and `make` to actually update it properly to version `V 0.2.2 3362d7e`.

**What did you expect to see?**
The new version when typing `v version`
 
**What did you see instead?**
An old version.

**Comment by Zerotask** [comment]
I just tried it (on my Windows 10) and it succesfully updated V to the latest commit.
