### ISSUE TITLE
Support thread handles for functions returning optionals

### ISSUE THREAD

**Issue by ken0x0a** [vlang/v#8973]
OS: macos, macOS, 11.2, 20D64
Processor: 16 cpus, 64bit, little endian, Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
CC version: Apple clang version 12.0.0 (clang-1200.0.32.29)
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 977a625.c7587c0

Git version: git version 2.30.1
Git vroot status: weekly.2021.8-60-gc7587c07-dirty
.git/config present: true

**What did you do?**
replace following https://github.com/vlang/v/blob/c7587c0760d347c9731ad1a4577520af5cb35fa8/examples/websocket/client-server/client.v#L11 with
```vlang
	mut ws := start_client() ?

	mut threads := []thread{}
	threads << go ws.listen() or { println(term.red('error on listen $err')) }
```

and
```sh
v run client.v
```

**What did you expect to see?**

success build
 
**What did you see instead?**

```
client.v:14:16: error: cannot append `thread void` to `[]thread`
   12 | 
   13 |     mut threads := []thread{}
   14 |     threads << go ws.listen() or { println(term.red('error on listen $err')) }
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   15 | 
   16 |     println(term.green('client $ws.id ready'))
```

Might related: https://github.com/vlang/v/pull/8913 (I'm using latest version of Vlang, and this commit is included)

**Comment by ken0x0a** [comment]
I could avoid this error by writing wrapper function as follows

```vlang
fn listen_ws(mut ws websocket.Client) {
	ws.listen() or {
		println(term.red('error on listen $err'))
		panic(err)
	}
}

fn main() {
  // ...
	mut ws := start_client() ?

	mut threads := []thread{}
	threads << go listen_ws(mut ws)
}
```

So, this must be caused by return type `?`

Do you have any thought?
Could you help? @UweKrueger

**Comment by UweKrueger** [comment]
Yeah, thread handles for functions returning optionals are not supported, yet. I make this issue a feature request.
Once this is implemented, the syntax to declare an array for thread handles for functions returning optionals will then be something like:
```v
mut thr_arr1 := []thread ?{}     // for `fn f() ? { ... }`
mut thr_arr2 := []thread ?f64{} // for `fn g() ?f64 { ... }`
```

**Comment by UweKrueger** [comment]
It will probably only be possible to call `wait()` with `or` block on single handles. So, to handle error values returned from thread arrays you'll have to iterate over them:
```v
fn f(n int) ? { ... }
fn g() ?f64 { ... }

fn main() {
    th1 := []thread ?{}
    for i in 0 .. 10 {
        th1 << go f(i)
    }
    th2 := go g()
    // ...
    x := th2.wait() or {
        println('Error: $err')
        1.0
    }
    println('result: $x')
    for i, t in th1 {
        t.wait() or {
            println('Error in thread #$i: $err')
        }
    }
}
```

**Comment by ken0x0a** [comment]
Oh, I think I understand.
Thank you so much!

So this is not a bug.

**Comment by Terisback** [comment]
@ken0x0a issue resolved?

**Comment by ken0x0a** [comment]
@Terisback 
I opened this issue as a "bug report", and then
this issue becomes "feature request (`[]thread ?{}` is not allowed yet)" now.

So as I understand, this issue is not resolved.

**Comment by UweKrueger** [comment]
> So as I understand, this issue is not resolved.

Right! I have changed the title and the issue class and have assigned myself to this since I want to work on it and keep this as a reminder what to work on. So, please leave it open. It will be closed automatically when a suitable implementation is merged.
