### ISSUE TITLE
Local variable is not visible inside callback function

### ISSUE THREAD

**Issue by ken0x0a** [vlang/v#8981]
Current V version:
V 0.2.2 1a8ff9d, timestamp: 2021-02-26 10:22:35 +0200

**V version:** 
**OS:** 

**What did you do?**
Trying to use local variable in callback function.

```vlang
	mut variable := []string{}
	// on new messages from other clients, display them in blue text
	ws.on_message(fn (mut ws websocket.Client, msg &websocket.Message) ? {
		if msg.payload.len > 0 {
			message := msg.payload.bytestr()
			println(term.blue('$message'))
			variable << message
		}
	})
```

**What did you expect to see?**
Run without error
 
**What did you see instead?**
Got following compile error (**undefined ident: `variable`**)
```
client.v:43:6: warning: unused variable: `variable`
   41 |     })
   42 | 
   43 |     mut variable := []string{}
      |         ~~~~~~~~
   44 |     // on new messages from other clients, display them in blue text
   45 |     ws.on_message(fn (mut ws websocket.Client, msg &websocket.Message) ? {
client.v:49:4: error: undefined ident: `variable`
   47 |             message := msg.payload.bytestr()
   48 |             println(term.blue('$message'))
   49 |             variable << message
      |             ~~~~~~~~
   50 |         }
   51 |     })
```

If we cannot pass local variable, how can we pass state (instance of struct, e.t.c,..).
Is there any workaround?

**Comment by Terisback** [comment]
Closures are not yet implemented, you can pass an array as an argument

**Comment by ken0x0a** [comment]
@Terisback 
Yes, I understand that.
But unfortunately, I'm trying to use callback for `x.websocket` module, and I have no control for the arguments.

**Comment by ken0x0a** [comment]
@Terisback 
The pasted code is almost from https://github.com/vlang/v/blob/master/examples/websocket/client-server/client.v .
I don't know how to use `x.websocket` without passing local variable.
Do you have any idea?

**Comment by Terisback** [comment]
You can use on_message_ref
https://modules.vlang.io/x.websocket.html#Client.on_message_ref
it accepts function that can handle third argument
https://modules.vlang.io/x.websocket.html#SocketMessageFn2

**Comment by ken0x0a** [comment]
@Terisback 
Thank you for the suggestion!

But sadly, I couldn't pass `mut` reference, so I couldn't change state from `Client.on_message_ref`.
I tried to access unsafe way (which Vlang allowed to compile successfully), but process killed by `Terminated by signal 11 (SIGSEGV)`

Do you have any suggestion?

**Comment by ken0x0a** [comment]
@Terisback Oh, I was wrong.
Your suggestion actually worked!!
Thank you so much!!
