### ISSUE TITLE
Global map causing unhandled exception

### ISSUE THREAD

**Issue by gardc** [vlang/v#8982]
**V version: V 0.2.2 1dd1be4** 
**OS: windows, Microsoft Windows 10 Pro v19041 64-bit** 

**What did you do?**
Ran following code:
```
fn init() int {
    modules_buffer = map[string][]byte{}
    return 1
}
__global ( modules_buffer map[string][]byte )

fn main() {
	println("global map test ${modules_buffer['test']}")
}
```

**What did you expect to see?**
0 or "not found" since the key is not present in the empty map.
 
**What did you see instead?**
Using MSVC compiler, this is the output:
```
Unhandled Exception 0xC0000005
C.CaptureStackBackTrace returned less than 2 frames
```
Output using GCC: 
```
Unhandled Exception 0xC0000005
C:/Users/dev/AppData/Local/Temp/v/test.9440100699043542244.tmp.c:5504: at print_backtrace_skipping_top_frames_tcc: Backtrace
C:/Users/dev/AppData/Local/Temp/v/test.9440100699043542244.tmp.c:5467: by print_backtrace_skipping_top_frames
C:/Users/dev/AppData/Local/Temp/v/test.9440100699043542244.tmp.c:5529: by unhandled_exception_handler
7fffef8885cc : by ???
RUNTIME ERROR: invalid memory access
```

**Comment by ntrel** [comment]
> fn init() int {

It works if you remove `int`. I have a pull almost ready to warn about that.

**Comment by JalonSolov** [comment]
Question:  Isn't it illegal syntax anyway?  I thought all non-fn declarations were supposed to be done before any fns.  Which would mean V should be complaining about the map being declared after `fn init()`

**Comment by ntrel** [comment]
>  I thought all non-fn declarations were supposed to be done before any fns.

If the example order was changed, this bug would still occur.

**Comment by spytheman** [comment]
@JalonSolov you have a valid point - that should be a separate error too.
