### ISSUE TITLE
unable to handling error on some syntax 

### ISSUE THREAD

**Issue by arhen** [vlang/v#90]
I've found several case.

1)
```
 fn main() {
 	age := 9
 	mut r =
 	println(age)
 }
```

output : bug found message

2)

```
 fn main() {
 	age := 9
 	mut _
 	println(age)
 }
```

output : nothing.
expected: error handling on syntax

**Comment by medvednikov** [comment]
#1 is fixed, #2 is a bit trickier.

**Comment by arhen** [comment]
when compiling, u must set #2 case as error syntax.

**Comment by medvednikov** [comment]
Fixed.
