### ISSUE TITLE
interface is private

### ISSUE THREAD

**Issue by alfclement** [vlang/v#900]
**V version:** V 0.1.11
**OS:** Linux bto 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

**What did you do?**
Example from manual , I already tried to add "pub:"

struct Dog {}
struct Cat {}

fn (d Dog) speak() string {
        return 'woof'
}

fn (c Cat) speak() string {
        return 'meow'
}

interface Speaker {
**pub:**
        speak() string
}

fn perform(s Speaker) {
        println(s.speak())
}

fn main() {
    dog := Dog{}
    cat := Cat{}
    perform(dog) // ==> "woof"
    perform(cat) // ==> "meow"
}

**What did you expect to see?**
compiles and works
 
**What did you see instead?**
alf@bto:~/V/v/ex$ ../v ex-interface.v
is interface. field=speak run=1
is interface. field=speak run=2
pass=2 fn=`perform`
panic: ex-interface.v:18
function `speak` is private

**Comment by AtjonTV** [comment]
Is this the same as #354 ?

**Comment by alfclement** [comment]
Yup.

**Comment by alfclement** [comment]
Closed.
