### ISSUE TITLE
Prioritize A Rust Interface As A Core Language Feature

### ISSUE THREAD

**Issue by human154** [vlang/v#9003]
This feature request proposes that Rust interop should be a primary language focus.

Rust is popular and its libraries are at a new level of quality for general industry software.  Rust is not as easy to develop in or understand as V would be, but in terms of the results, it's hard to imagine doing much better.  Rust is setting the new standard:
 - ultra-fast
 - safe(r)
 - concurrent 
 
 The "resulting in top quality software" aspect can hardly be overstated, it's (in my opinion) why Rust is succeeding and why it will continue to succeed.

It's startling, but in a sense, Rust is well on its way to becoming the new C. I know replacing C is basically inconceivable... but this could be especially true in the sense that it is likely that for some time most new C level software projects will use Rust. Of course, right now old C software projects are also being converted to Rust and thereby improving concurrency and safety  (or plain adding them in the first place). Rust is already in the top 20 languages and rising. It's more or less plainly superior to C so it's only direct competitor in the top 20 is C++. C++ is anything but new and shiny, so Rust will go much farther than it already has.  

There is a lot to be gained. Rust's large community has had 6 years since reaching 1.0 to build top quality libraries and since their numbers are currently greater than those using V, they will continue to develop and refine at a faster rate than V developers for some time. The V community could leverage these great new libraries. Since V has (some) similar goals to Rust, we should actually be betting on Rust, not against it. And we are, in a way, underestimating Rust if we only provide a C FFI.

If V doesn't surpass Rust in community size, having great interoperability with Rust will be an even more important advantage.

Imagine contemplating the task of duplicating some massive Rust project/library in V without the possibility of seeing any performance, safety or concurrency gains!  That would be extremely un-motivating! Most developers faced with that choice would decide to go with Rust. So not having great rust interop could be a long term drain on the V community.

(It should be said, by the way, that Rust is extremely good at package management and combining libraries.)

As Rust continues to become the new standard, it seems likely that someday a language that only provides a C FFI, with no Rust FFI, would be judged as doing things "the old, less safe way."

Conversely, people will be (even more) attracted to a new language that has a really great Rust interop story. There wouldn't be many competing languages that could make that claim! I think there is a missing language in the ecosystem that has great Rust interoperability, runs fast, and doesn't get in your way when developing.  Everyone that is using Rust who just wants to build an application or something quick without Rust's pain points slowing them down must be looking for that language.  Maybe it could be V!

**Comment by JalonSolov** [comment]
Since it appears the interface to Rust is the same as C, V already has it.

If you have any better info on calling Rust from other languages, please add links.

**Comment by medvednikov** [comment]
Indeed, it should "just work", since calling C is supported.

**Comment by human154** [comment]
I'll research it a bit.  If anyone has any other insights, please do share them.

**Comment by human154** [comment]
I guess if the C FFI is good enough for the core maintainers then this issue has been addressed as far as I am concerned.
