### ISSUE TITLE
Invalid parameters can be passed to declared C functions

### ISSUE THREAD

**Issue by Cthutu** [vlang/v#9006]
**V version:** V 0.2.2 7e08e84
**OS:** Windows 10

**What did you do?**
Supplied this code:
```
pub type HWND = voidptr

[typedef] struct C.MSG {
	message int
}

fn C.GetMessage (mut msg &C.MSG, hwnd HWND, msg_filter_min u32, msg_filter_max u32) int

pub fn get_message (mut msg &C.MSG, hwnd HWND, msg_filter_min u32, msg_filter_max u32) int {
	return C.GetMessage(&msg, hwnd, msg_filter_min, msg_filter_max)
}
```

**What did you expect to see?**
I expected to see an error in the `return C.GetMessage(...)` line because `&msg` was passed instead of `msg`
 
**What did you see instead?**
No compiler error was forthcoming.

**Comment by ntrel** [comment]
Duplicate of #8763.
