### ISSUE TITLE
manual example: struct color does not work

### ISSUE THREAD

**Issue by alfclement** [vlang/v#901]
**V version:** 
**OS:** 

**What did you do?**
Example from manual:
struct Color {
        r int
        g int
        b int
}

fn (c Color) str() string { return '{$c.r, $c.g, $c.b}' }

fn rgb(r, g, b int) Color { return Color{r: r, g: g, b: b} }

const (
        Numbers = [1, 2, 3]

        Red  = Color{r: 255, g: 0, b: 0}
        Blue = rgb(0, 0, 255)
)

**//fn main() {**
println(Numbers)
println(Red)
println(Blue)
**//}**

**What did you expect to see?**
Correct output.
 
**What did you see instead?**
alf@bto:~/V/v/ex$ ./ex-color  # compiled w/o **fn main()**
[]
{0, 0, 0}
{0, 0, 0}

Works with fn main()

**Comment by Kogam22** [comment]
@alfclement can you properly format your code in the comment. It's not formatted properly.

**Comment by alfclement** [comment]
Thanks @Kogam22 for confirming and formatting ;-) I have to learn this...

**Comment by medvednikov** [comment]
Fixed.
