### ISSUE TITLE
Multiple module imports (with a single import keyword)

### ISSUE THREAD

**Issue by Zerotask** [vlang/v#9012]
Similar to the options you have with [const](https://github.com/vlang/v/blob/master/doc/docs.md#constants), it would be good to have the option to define multiple module imports with a single `import` keyword.

### Currently:
```v
import vweb
import json
import pdf
import os
import crypto.sha256
import time
```

### Feature request
```v
import (
    vweb
    json
    pdf
    os
    crypto.sha256
    time
)
```

**Comment by ntrel** [comment]
We used to have this, it was removed - e.g. #7656.
