### ISSUE TITLE
reference example does not work

### ISSUE THREAD

**Issue by alfclement** [vlang/v#902]
**V version:** V 0.1.11
**OS:** Linux bto 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

**What did you do?**
Example from manual:

alf@bto:~/V/v/ex$ more ./ex-referenv.v
fn multiply_by_2(arr mut []int) {
        for i := 0; i < arr.len; i++ {
                arr[i] *= 2
        }
}

mut nums := [1, 2, 3]
multiply_by_2(mut nums)
println(nums) // ==> "[2, 4, 6]"

**What did you expect to see?**
Correct output
 
**What did you see instead?**
lf@bto:~/V/v/ex$ ../v ex-referenv.v
/home/alf//.vlang//ex-referenv.c: In function ‘multiply_by_2’:
/home/alf//.vlang//ex-referenv.c:3181:35: error: incompatible type for argument 1 of ‘array__get’
 int tmp4 =  ( *(int*) array__get( arr , i) ) * 2;
                                   ^~~
/home/alf//.vlang//ex-referenv.c:374:8: note: expected ‘array {aka struct array}’ but argument is of type ‘array_int * {aka struct array *}’
  void* array__get(array a, int i) {
        ^~~~~~~~~~
V panic: clang error

**Comment by medvednikov** [comment]
Fixed.
