### ISSUE TITLE
intptr problems

### ISSUE THREAD

**Issue by Yarila682** [vlang/v#903]
**V version:** 
0.1.11
**OS:** 
Linux Mint 18.2

**What did you do?**
```Go
module main

import os

fn main(){

    a:=5

    do_smth(&a)
}
fn do_smth(ptr intptr){ //in main.v we have typedef int* intptr;

    b:= *ptr    

    println('"${b}"')
}
/*fn do_smth(ptr *int){

      b:= *ptr    

    println('"${b}"')
}*/
```

**What did you expect to see?**
I think *int and intptr should be the same or "intptr" should'n be public as it is  not described in docs.  

Commented out code works as I expect and prints "5". 
 
**What did you see instead?**

Fn "do_smth" wrong arg #1. Expected "intptr" (ptr)  but got "int*"

**Comment by serkonda7** [comment]
With latest V it will give you
``` error: unknown type `intptr` ```

You could use this code to create a Intptr type alias:
```v
type Intptr = &int

fn main(){

    a:=5

    do_smth(&a)
}
fn do_smth(ptr &Intptr){

    b:= *ptr

    println('"${b}"')
}
```
