### ISSUE TITLE
`.free()` should produce a compiler warning without `[unsafe]`

### ISSUE THREAD

**Issue by Ben-Fields** [vlang/v#9037]
**V version:** V 0.2.2 e44120f

**What did you do?**
```v
fn (data &MyType) free() {
	// ...
}
```
```v
my_var := MyType{}
my_var.free()
```

**What did you expect to see?**
A compiler warning in development mode, an error in production mode (`-prod`).
 
**What did you see instead?**
`.free()` executes normally without warnings/errors. This leads to multiple calls to `.free()` when `-autofree` is enabled.

**Comment by medvednikov** [comment]
Fixed.
