### ISSUE TITLE
I have got issues while installing ved on Bodhi linux (Ubuntu 18.04)

### ISSUE THREAD

**Issue by harshmangalam** [vlang/v#9047]
warning: function `utf32_to_str_no_malloc` must be called from an `unsafe` block
  648 |     }
  649 |     buf := [0, 0, 0, 0, 0]
  650 |     s := utf32_to_str_no_malloc(code, buf) // .data)
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  651 |     // s := utf32_to_str(code)
  652 |     // println('s="$s" code="$code"')

warning: assignment from incompatible pointer type
tcc: error: library 'GL' not found

**Comment by medvednikov** [comment]
Should be fine now.
