### ISSUE TITLE
uninitialized variables in structs

### ISSUE THREAD

**Issue by alfclement** [vlang/v#905]
**V version:** V 0.1.11
**OS:** 

**What did you do?**
This example:
struct User {
    age int
    name string
}

fn (u User) can_register() bool {
    return u.age > 16
}

user := User{age: 10, name: 'me'}
println(user.can_register()) // ==> "false"
println(user.name)

user2 := User{age: 20}
println(user2.can_register()) // ==> "true"
println(user2.name)

user3 := User{}
println(user3.age) // not initialized!!

**What did you expect to see?**
compile error : user3 not initialized
 

- Do we want to force all variables to be initialized?? 

- Can structs get default initialized values

- Do we want to use **User{age: 10, name: 'me'}** or **User(age: 10, name: 'me')** as in other languages? I prefer the 2nd style.

**What did you see instead?**
alf@bto:~/V/v/ex$ ./ex-method
false
me
true

0

**Comment by medvednikov** [comment]
Uninitialized struct fields are zeroed.
