### ISSUE TITLE
how to debug vlang

### ISSUE THREAD

**Issue by fastfading** [vlang/v#9079]
I search all google ,  did not find a  way to debug it.  
could you add some tutorial about debug?
it is the very basic function of a programming language

**Comment by JalonSolov** [comment]
Just use gdb or any other debugger you like.

If you compile your code with `-g` option, it will add V symbol names so you can follow the code better.

**Comment by fastfading** [comment]
v -g a.v
gdb a
GNU gdb (GDB) 10.1
(gdb) l
Line number 1000064 out of range;
/var/folders/g4/b17y14y9753bsx3_f_03ggh80000gn/T/v/a.7972220902694899663.tmp.c
has 16479 lines.

as you see ,  it shows  c code which can not be list

macos big sur
v version
V 0.2.2 46cdf4f

JalonSolov <notifications@github.com> 于2021年3月3日周三 上午11:39写道：

**Comment by kahsa** [comment]
If you are using vscode
https://github.com/vlang/vscode-vlang/issues/172

**Comment by kahsa** [comment]
I agree to that step by step debuging tutorial for newcomers to be provided.
This is the second time I've seen this kind of issue.
