### ISSUE TITLE
Nested comments won't compile

### ISSUE THREAD

**Issue by yep84** [vlang/v#908]
**V version:** 0.1.11 
**OS:** Linux

**What did you do?**
// This is a single line comment.

/* This is a multiline comment.
   /* It can be nested. */
*/

fn main() {
    println('hello v')
}

**What did you expect to see?**
hello v
 
**What did you see instead?**
pass=2 fn=`main`
panic: simple.v:5
undefined: ``

**Comment by medvednikov** [comment]
Fixed.
