### ISSUE TITLE
cannot convert 'struct map' to 'unsigned char *' 

### ISSUE THREAD

**Issue by ChildishGiant** [vlang/v#9088]
OS: linux, elementary OS 5.1.7 Hera
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
CC version: cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

V full version: V 0.2.2 db9b523.822d20d

## Minimum reproduction:
```v
import x.json2

fn main() {

	test := json2.raw_decode('{"a":1}') ?
	print(string(test.as_map()))

}
```

## Causes
```
/tmp/v/test.7479478658034554934.tmp.c:9771: error: cannot convert 'struct map' to 'unsigned char *'
builder error: 
==================
C error. This should never happen.
```

**Comment by Delta456** [comment]
What is the intended behavior? If the error needs to be a V error then ok as I don't think `string(test.as_map())` should work.

**Comment by ChildishGiant** [comment]
Yea just needs to be a v error, not c

**Comment by Delta456** [comment]
I will do this tomorrow then.

**Comment by Dialga** [comment]
Fixed by commit "checker: add more string(x) checks, with more detailed replacement suggestions" f5d283721eafd94db9523aad7e19f14e4f5417cf on 1 Dec 2021.
