### ISSUE TITLE
GitHub, Slack, Twitter, Reddit icons misplaced

### ISSUE THREAD

**Issue by jkleiser** [vlang/v#91]
For certain browser window sizes, the icons linking to GitHub, Slack, Twitter and Reddit on vlang.io shows up more or less vertically in the middle of the window, on top of "The V Programming Language". See attachment. I'm using Safari on macOS, and the problematic window width is 1230px.
![Screenshot](https://user-images.githubusercontent.com/107986/55863492-eb1a0700-5b7a-11e9-8f95-cc0e12d40d56.png)
![window-width](https://user-images.githubusercontent.com/107986/55863510-f10fe800-5b7a-11e9-87bd-a6df2bee9481.png)

**Comment by medvednikov** [comment]
Sorry for the delay.

Should be fine now, can you check?

**Comment by jkleiser** [comment]
It's a little better, but not perfect. See new screen shot below. The same in Safari and Chrome on Mac.
![vlang-icons](https://user-images.githubusercontent.com/107986/56096913-3e2ee980-5eee-11e9-8c36-bc7151cc95ff.png)

**Comment by medvednikov** [comment]
Strange, works fine for me on Safari.

<img width="1004" alt="Screen Shot 2019-04-15 at 04 28 44" src="https://user-images.githubusercontent.com/687996/56104181-08fab980-5f37-11e9-8bc7-89e13aac9f18.png">

**Comment by jkleiser** [comment]
I can no longer reproduce this problem, so it's probably fixed.
