### ISSUE TITLE
voidptr to int conversion problems

### ISSUE THREAD

**Issue by Yarila682** [vlang/v#911]
**V version:** 
0.1.11
**OS:** 
Linux Mint 18.2

**What did you do?**
```Go
module main

import os

fn main(){

    a:=5
    do_smth(&a)
}


fn do_smth(ptr voidptr){

       // c:= intptr(ptr)

      //  b:= *c

        b:= *(intptr(ptr)) //error here

    println('"${b}"')
}
```

**What did you expect to see?**
I know about #298 this, but here we probably have syntax problem. 

Commented out code works as I expect and prints "5"
 
**What did you see instead?**

pass=2 fn=`do_smth`
panic: write_bytes.v:28
undefined: ``

**Comment by serkonda7** [comment]
`intptr` does not exist as type.
Conversion to int works just fine:
```v
fn main(){
    a := 5
    do_smth(&a)
}

fn do_smth(ptr &voidptr){
	b := int(*ptr)
    println('"${b}"')
}
```
