### ISSUE TITLE
Error message improvements

### ISSUE THREAD

**Issue by Zerotask** [vlang/v#9115]
Here are some suggestions to improve the error messages, so people know better how to fix their code.

**Example:**
```v
 ['/calculators/add/:value1/:value2']
 pub (mut app App) add_two_values(value1 int, value2 int) vweb.Result {
	 result := value1 + value2
	 return app.json(result.str())
 }
```

Current error message: `error: wrong pub keyword usage`
Suggestion: `error: wrong pub keyword usage. Did you mean:  pub fn (mut app App) add_two_values(value1 int, value2 int) vweb.Result {` (or: Possible solution: ...; or just give a hint, that there could be the `fn` keyword missing)

---

**Example:**
```v
 ['/calculators/add/:value1/:value2']
 pub fn (mut app App) add_two_values(value1 int, value2 int) vweb.Result {
	 result := value + value2
	 return app.json(result.str())
 }
```

Current error message: `error: undefined ident: value`
Suggestion: `error: undefined ident: value. Did you mean value1?` (value1 and value2 are the only possible options here and value2 is used, so there is just 1 unused param here)

---

**Example:**
```v
 ['/calculators/add/:value1/:value2']
 pub fn (mut app App) add_two_values(value1 int, value2 int) vweb.Result {
	 result := value1 + value2
	 return app.json(result)
 }
```

Current error message: error: cannot use `int` as `string` in argument 1 to `App.json`
Suggestion: error: cannot use `int` as `string` in argument 1 to `App.json`. Possible solution: use `return app.json(result.str())` (or: use result.str() instead of result or something like that)

---

**Example:**
```v
fn add(value1 int, value2 int) {
	return value1 + value2
}
```

Current error message: `unexpected argument, current function does not return anything`
Suggestion: add a hint, that this could be resolved by adding `int`.

**Comment by JalonSolov** [comment]
Personally, I prefer brief error messages.  In my experience, most people simply start ignoring messages if they are too long.

**Comment by Zerotask** [comment]
The vlang.io website says
![image](https://user-images.githubusercontent.com/20150243/110023083-0670fb00-7d2d-11eb-89a4-ec59b1d7c9ae.png)

and personally I like that. This was also something a friend of mine noticed and we liked it, how V provides actual useful information to resolve it.
And here we're talking about 1 additional line. So I wouldn't say this would flood the user's console output.

**Comment by JalonSolov** [comment]
I didn't say it wasn't useful, just expressing an opinion.  The first example you show definitely needs something else.

I'm just saying don't get carried away with making messages too verbose.  Short and _clear_ is much better than reprinting docs.md.  :-\

**Comment by Zerotask** [comment]
That's fine. I'm also just expressing my opinion and I think it would fit to the simplicity of V.
My first post isn't meant as a finished solution, more like a starting point to discuss about how to improve it. Feel free to add alternative improvements. I just thought it would be a good idea since this is something V is showing on its website.
