### ISSUE TITLE
os.write_file() add a new line at the end

### ISSUE THREAD

**Issue by yep84** [vlang/v#912]
**V version:** 0.1.11
**OS:** Linux

Why os.write_file() add a new line at the end of the file?

Is it a desired feature? If not you'll find my path in a few minutes.

**What did you do?**
```
import os

fn main() {
    os.write_file('./out.txt', 'bla bla bla')
}
```

**What did you expect to see?**
````
bla bla bla
````
 
**What did you see instead?**
````
bla bla bla

````

**Comment by esquerbatua** [comment]
I can't replicate it.

With that code not make a new line at the end.

**Comment by aguspiza** [comment]
I may break windows compiler and code but here there goes...

**Comment by medvednikov** [comment]
Fixed.
