### ISSUE TITLE
Compiler misinterpreting empty array

### ISSUE THREAD

**Issue by jaddison06** [vlang/v#9131]
**V version:** V 0.2.2 09cff69
**OS:** linux, Pop!_OS 20.10

Checking if an array is empty with this code:
```v
fn (mut stack ColourStack) pop_fg(col tui.Color) {
	// ...
	if fg != [] {
		stack.ctx.set_color(stack.fg.pop())
	} else {
		stack.ctx.reset_color()
	}
}
```
Compiler gives this warning, I don't understand why it expects a ":"
./colour_stack.v:24:8: error: unexpected `.`, expecting `:`
   22 | fn (mut stack ColourStack) pop_fg(col tui.Color) {
   23 |     if stack.fg != [] {
   24 |         stack.ctx.set_color(stack.fg.pop())
      |              ^
   25 |     } else {
   26 |         stack.ctx.reset_color()

**Comment by jaddison06** [comment]
Figured out that if I put ```if fg != []{}``` then it works. If I'm comparing two arrays like this, I think that you shouldn't need this - the compiler can already infer the type, as it doesn't tell me to put ```if fg != []{tui.Color}```. It'd be more intuitive to go with the array initialisation syntax ```[values...]```.

**Comment by joe-conigliaro** [comment]
@jaddison06 what is `fg` in `if fg != []`, did you mean `if stack.fg != []`?

**Comment by jaddison06** [comment]
No, it's a variable that I initialized earlier. It's quite a long function - I abbreviated it here.

**Comment by joe-conigliaro** [comment]
can you show the definition of `fg` please

**Comment by jaddison06** [comment]
```fg := stack.fg.last()```

**Comment by joe-conigliaro** [comment]
thanks @jaddison06

**Comment by joe-conigliaro** [comment]
@jaddison06 can you try in latest v it should be fixed now

**Comment by jaddison06** [comment]
@joe-conigliaro working perfectly, thanks!

**Comment by joe-conigliaro** [comment]
Excellent! np
