### ISSUE TITLE
C modules are not working anymore

### ISSUE THREAD

**Issue by waotzi** [vlang/v#9138]
**V version: > 2.1.0** 
**OS: tried with windows and linux, both failed** 

**What did you do?**
tried to run a program that uses a v.mod file

**What did you expect to see?**
the program running fine

 
**What did you see instead?**
an error that does not happen in 2.1.0

trying to run the example projects in v's repository 
v/vlib/v/tests/project_with_c_code with v run main.v

gives the error

```
main.v:3:1: builder error: bad module definition: v imports module "mod1" but /home/wolfi/src/v/vlib/v/tests/project_with_c_code/mod1/wrapper.v is defined as module `v.tests.project_with_c_code.mod1`
    1 | module main
    2 | 
    3 | import mod1
      | ~~~~~~~~~~~
    4 | 
    5 | fn main() {
   ```

**Comment by JalonSolov** [comment]
This has nothing to do with it being a C module.  Module imports of any type are hitting problems right now.

I just tried with the most recent version of V, and get a similar (though slightly different) message:
```
project_with_c_code/main.v:3:1: builder error: bad module definition: project_with_c_code/v imports module "" but /home/jalon/git/v/vlib/v/tests/project_with_c_code/v is defined as module `main`
    1 | module main
    2 |
    3 | import mod1
      | ~~~~~~~~~~~
    4 |
    5 | fn main() {
```
@joe-conigliaro

**Comment by joe-conigliaro** [comment]
Ouch Ill take a look, cheers!

**Comment by joe-conigliaro** [comment]
Hello, this issue should now be fixed
