### ISSUE TITLE
Structure embedding: No field for structure at n+2

### ISSUE THREAD

**Issue by Lathanao** [vlang/v#9147]
V full version: V 0.2.2 f4c03e8
OS: linux, "Manjaro Linux"

**What did you do?**
```
module main

struct Animal{
    Duck 
    id int
}

struct Duck{
    RedDuck
    action string
}

struct RedDuck{
    color string
}

d := Animal{Duck{RedDuck{'red'}, 'fly'}, 1}

println(d.id)
println(d.action)
println(d.color)
```

**What did you expect to see?**
```
1
fly
red
```
 
**What did you see instead?**
```
test/struct_embedding_duck.v:25:11: error: type `Animal` has no field or method `color`.
2 possibilities: `Duck`, `id`.
   20 | println(d.id)
   21 | println(d.action)
   22 | println(d.color)
```

**Comment by TheBoringDude** [comment]
I think struct embedding in `v` is different from `go`.

`RedDuck` is embedded under `Duck`, you can't access it from `Animal`
This works: 
```v
println(d.Duck.color)
```

**Comment by Lathanao** [comment]
Yes, this is what I understand.
In fact, it's not really a bug, let say there is no specification about.
However, when I tried it, my expectation was to get access to the color.

**Comment by dumblob** [comment]
Hm, I think this is still not decided - see the whole discussion https://github.com/vlang/v/discussions/7568 .

**Comment by kahsa** [comment]
This works now.
Can be closed.
