### ISSUE TITLE
Improvements for command v doc

### ISSUE THREAD

**Issue by Zerotask** [vlang/v#9155]
It would be great if the `v doc` command could generate a standalone HTML documentation.
Here is an example from JSDoc 3: https://jsdoc.app/about-getting-started.html

This could be done with an optional argument `-generate`.

---
**Update**
Summary of my suggestions:

- add alternatives for `v doc help`: `v doc --help` and `v doc -h`
- show available output formats
- change `-f` to a better understandable option, e. g. `-format`, `-output-format`, `-of`

**Comment by JalonSolov** [comment]
What do you mean by "standalone HTML documentation"?

https://modules.vlang.io/ is currently generated by the `v doc` command.

**Comment by Zerotask** [comment]
> What do you mean by "standalone HTML documentation"?

standalone means that is doesn't rely on other things. Just a small website with its own content, styles etc.
The mentioned JSDoc 3 is creating a new folder with a complete HTML website you can open, deploy etc.

Maybe I misunderstand the v doc command, but it says `Generate the documentation for a V module.`.
If I create a new project folder with `v new` and add modules to it. Then I though that `v doc` is generating a documentation. It seems that it doesn't really generate a documentation, it just outputs content of a vlib module I specify, e. g. `v doc vweb`.

It would be better to change the verb `generate` with `show` to make it more clear what this command does.

Besides that, it would be great to have a builtin tool to actually generate a documentation of his own project.

**Comment by JalonSolov** [comment]
`v doc` used to have a built-in HTML server, but it was removed - too problematic.

`v doc` _does_ generate documentation... in several different formats, depending on the command line options you use.  The files it "just outputs" didn't exist in that form before you ran the command, therefore they were generated.  What it doesn't "generate" is a server.

`v doc` generates documentations for it's own project - see https://modules.vlang.io/, as I mentioned before.

**Comment by Zerotask** [comment]
> in several different formats, depending on the command line options you use

This point wasn't clear for me. I tried `v doc --help` and `v doc -h` which are common options for accessing help information. Now I figured out that the command is `v doc help`. Although the `-f` option doesn't provide the actual formats. I had to look it up / try formats.
The help should show the available options. 
My suggestion is to change the help text to:
`Specifies the output format to be used. Available formats are: markdown, json, text and html`

Additionally I suggest changing `-f` (which is mostly related to file / file path in such a context) to `-t` (for type), `-format`, `output-format` or something else which is better understandable.

Besides that `-f html` was acutally something I was look for. Thank you!

> v doc generates documentation for it's own project - see https://modules.vlang.io/, as I mentioned before.

Yes, this was the result, but the page alone doesn't show me how to generate that.


But it seems that all the things are just for vlib modules, right? Because I thought this would also generate a documentation for your own projects. If that's not the case, I'd create a new, more specific issue requesting this feature.

**Comment by JalonSolov** [comment]
The fact that your command didn't work appears to be a bug, as the help says that should work.

According to `v help doc`, it says:
```
Generates the documentation of a given directory, module, or V source file
and prints or saves them to its desired format. It can generate HTML, JSON,
or Markdown format.
```
There is no mention of only working for vlib, and there shouldn't be.  You should be able to generate docs for your own code.

**Comment by Zerotask** [comment]
I just created a new project with `v new test`. This created me a test.v. I added an additional function. Then I tried to create a documentation with: `v doc -filename test.v -f html -o docs`.

And it doesn't generate the expected documentation. It just shows me:
![image](https://user-images.githubusercontent.com/20150243/110218470-3c8fb580-7eba-11eb-9d16-c1364d16ed59.png)

There are more vlib modules listed. So yes, there is a mention of those vlib modules.

If I run `v doc -f html -o docs -m` it created a folder `_docs` (not `docs` what I passed) and it consists of a documentation of all vlib modules). So this doesn't seem to work as I expect. 
Can you create a new project and create a documentation of this newly created project? If so, please tell me which command you've used.

and regarding -h and -help the help page lists:
![image](https://user-images.githubusercontent.com/20150243/110218557-a7d98780-7eba-11eb-890f-29b0654045e1.png)

![image](https://user-images.githubusercontent.com/20150243/110218530-8b3d4f80-7eba-11eb-94ad-8c3041509e32.png)
![image](https://user-images.githubusercontent.com/20150243/110218539-93958a80-7eba-11eb-9cc9-a42eb7bf0e80.png)

**Comment by JalonSolov** [comment]
There is no mention of only doing vlib in the _help_ for the command.  Yes, the "error" mention shows all the modules it can find, which are mainly the vlib modules.

You need to open a `bug` issue.

**Comment by Zerotask** [comment]
Well, that is quibble now. I just showed you how it looks for me and for me the output always says vlib modules.

If my provided command should generate a documentation of my project (and that was my intention for this issue), then yes, this is a bug.

**Comment by JalonSolov** [comment]
That is exactly what I am saying.  It should be generating doc for your project.

The help does not say anything about only generating doc for vlib modules.  It says (repeated here, though I posted it earlier):
```
Generates the documentation of a given directory, module, or V source file
and prints or saves them to its desired format. It can generate HTML, JSON,
or Markdown format.
```
The fact that it shows you the vlib modules when it didn't do what you wanted is it just trying to be helpful.  However, it should have printed the docs for your project, if it could.

**Comment by Zerotask** [comment]
Yes, and (to repeat myself) I just showed you how this command works for me. Since I didn't understand the command properly at the beginning there could also be the case that I just used it wrong. That's why I asked you, how do you use this command.
Besides that, it could also be possible that the output is correct (and it's not just a hint but a (new) limitation) and the help page is outdated.

But since it's now clear that it's a bug, there's no need to continue this discussion. I already created the bug issue #9170
