### ISSUE TITLE
"json: any is not struct" how to get a like Go's "map[string]interface{}"

### ISSUE THREAD

**Issue by xiusin** [vlang/v#9157]
**V version:** 
**OS:** 

**What did you do?**
```
// example1
 mut rest := map[string]any{   "int": 15,"float": 12.12,"str": "hello world"}

// example2
 mut rest := map[string]any{  }
rest["int"] = 12
 rest['float'] = 12.12

json.encode(rest)
```

**What did you expect to see?**
```
success 
```
 
**What did you see instead?**
```

// example1: 
  error: `}` expected; explicit `map` initialization does not support parameters
   41 |     }
   42 | 
   43 |  mut rest := map[string]any{   "int": 15,"float": 12.12,"str": "hello world"}

// example2:
json: any is not struct
```

**Comment by Delta456** [comment]
`any` will be removed iirc as we already have generics and sum types.

**Comment by JalonSolov** [comment]
Check `x.json2` `raw_decode` method.

**Comment by xiusin** [comment]
@JalonSolov 
i define a Resp struct , `result` to want to receive any type
```
pub struct Resp {
    code int 
    message string
    result json2.Any
}
```
but, the result is not satisfactory.

it cant receive `map[string]string`, '[]map[string]json2.Any'

example: 
```
    mut roles := []json2.Any{}
    helper.json(mut res, helper.Resp{
            code: 0
            message: "success login"
            result: json2.Any({
                "roles": json2.Any([{"aaa":json2.Any("asdads")}])
            })
    })
```
Or it's too difficult to use.

sorry, my english. Most of them come from machine translation😭

**Comment by JalonSolov** [comment]
@nedpals ^^

**Comment by Terisback** [comment]
> it cant receive map[string]string，[]map[string]json2.Any

you can, json2.Any has two methods arr() and as_map(), you can do many things with them
like if you want to retrieve `map[string]string` after you've done with json2.decode, just `data := obj.as_map() // map[string]json.Any`, and iterate over it
or `[]map[string]json2.Any`,
```v
data := obj.arr() // []json2.Any
for v in data {
  m_obj := v.as_map() // map[string]json2.Any
} // []map[string]json2.Any
```

@xiusin
