### ISSUE TITLE
Weird type inference in an array

### ISSUE THREAD

**Issue by jaddison06** [vlang/v#9163]
**V version:** V 0.2.2 818be80
**OS:** linux, Pop!_OS 20.10

I'm trying to initialize a struct with a list of items. Code looks like this:
```v
app.show_menu({
		title: {
			text: "Test menu"
		},
		lines: [
			{
				title: {
					text: "Normal text 1"
				}
			},
			{
				title: {
					text: "Normal text 2"
				}
			},
			{
				title: {
					text: "Normal text 3"
				}
			},
		]
	})
```
For some reason the compiler doesn't like this - it interprets the third one as a string.
./frame.v:42:5: error: unknown field `title` in struct literal of type `string`
   40 |             },
   41 |             {
   42 |                 title: {
      |                 ~~~~~~~~
   43 |                     text: "Normal text 3"
   44 |                 }

There's no error if I take away that third one - this code compiles fine:
```v
app.show_menu({
		title: {
			text: "Test menu"
		},
		lines: [
			{
				title: {
					text: "Normal text 1"
				}
			},
			{
				title: {
					text: "Normal text 2"
				}
			},
		]
	})
```

And if I initialize it explicitly like this, everything works:
```v
app.show_menu({
		title: {
			text: "Test menu"
		},
		lines: [
			{
				title: {
					text: "Normal text 1"
				}
			},
			{
				title: {
					text: "Normal text 2"
				}
			},
			MenuItem{
				title: {
					text: "Normal text 2"
				}
			},
		]
	})
```
No idea what's going on!

**Comment by nedpals** [comment]
@jaddison06 Array type is inferred on the first item of the array. In the case of the structs, the struct name should be explicitly declared on each item (e.g `[Foo{...}, Foo{...}]` u get the point). 

What's weird to me is that two of these works: https://devbits.app/play/CxFtW8QTQC0y and https://devbits.app/play/oKYGtESrlYWF (I'm not sure if this is a feature, but the short syntax init is only used inside the function arguments).

**Comment by jaddison06** [comment]
@nedpals Yeah - I don't know what the intended behaviour is, but the inconsistency is strange

**Comment by medvednikov** [comment]
Fixed, now `Foo{}` is required for struct init.
