### ISSUE TITLE
V fmt issue with JSON tags

### ISSUE THREAD

**Issue by a1730** [vlang/v#9167]
**V version:** V full version: V 0.2.2 15896be.043c29c
**OS:** linux, N/A
**CC:** CC version: cc (Debian 8.3.0-6) 8.3.0
**Vexe:** vexe mtime: 2021-03-06 18:52:53
**Git:** Git vroot status: weekly.2021.8-207-g043c29cf
**TCC:** thirdparty/tcc status: thirdparty-linux-amd64 7543de81

**What did you do?**
v fmt -w botched.v
`struct Botched {
        oid string [json: '\$oid']
}`
[botched.txt](https://github.com/vlang/v/files/6095906/botched.txt)

**What did you expect to see?**
`struct Botched {
        oid string [json: '\$oid']
}`

**What did you see instead?**
`struct Botched {
        oid string [json: '\\$oid']
}`

V fmt doubled up the `\` on the json tag thus creating compilation errors. We are skipping V fmt step in our workflow for now.
Thank you for the very productive language.

**Comment by spytheman** [comment]
@a1730 , thank you for the very good bug report.

**Comment by a1730** [comment]
It works now. Thank you!
