### ISSUE TITLE
Does V allow [required] tag on JSON structs?

### ISSUE THREAD

**Issue by a1730** [vlang/v#9177]
**V version:** V 0.2.2 15896be.f1c4e96
**OS:**  linux, N/A
**CC:** CC version: cc (Debian 8.3.0-6) 8.3.0
**Vexe:** vexe mtime: 2021-03-07 12:15:29
**Git:** Git version: git version 2.20.1
**Git:** Git vroot status: weekly.2021.8-220-gf1c4e962
**Tcc:** thirdparty/tcc status: thirdparty-linux-amd64 7543de81

**What did you do?**
I created a very simple struct
`struct FAData {
        display_name    string   [required] [json: displayName]
}`
[json_required.txt](https://github.com/vlang/v/files/6097137/json_required.txt)
**What did you expect to see?**
No compilation error
 
**What did you see instead?**
> required.v:2:45: error: unexpected token `[`, expecting name
    1 | struct FAData {
    2 |         display_name    string   [required] [json: displayName]
       |                                             ^
    3 | }
    4 |

Does V disallow using bot attributes on a struct member, or is there a magic invocation that we are missing. We have tried to switch the attributes `[json: displayName] [required]` but no luck.
Thank you for provding this productive development environment.

**Comment by spaceface777** [comment]
I think the proper syntax here is `[required; json: displayName]`.

**Comment by a1730** [comment]
Yes, you are right. That worked.
Thank you.
