### ISSUE TITLE
Unable to read csv containing quotes

### ISSUE THREAD

**Issue by championjared** [vlang/v#9185]
**V version:** V full version: V 0.2.2 5d653a3
**OS:** OS: windows, Microsoft Windows 10 Home v19042 64-bit

**What did you do?**
I am unable to read a csv file that includes quote character `"` in the line. I have run the test function `encoding.csv.reader_test.test_encoding_csv_reader()` which succeeds, but adding quotes in the input file fails 

**What did you expect to see?**
I expect to see these rows be ingested
 
**What did you see instead?**
I see the code silently break the parser loop and not read the file data at the point it reached the quotes

**Sample Code**
```
import encoding.csv
import os

fn main() {
    data := os.read_file('./test/test.csv') ?
    println(data)
    mut parser := csv.new_reader(data)
     for {
            line := parser.read() or { break }
            println(line)
     }
}
```

**Sample Input test/test.csv**
```
some,rows,names,junk
A,B,C,D
E,F,"G",H
I,J,K,L
```

**output**
```
some,rows,names,junk
A,B,C,D
E,F,"G",H
I,J,K,L

['some', 'rows', 'names', 'junk']
['A', 'B', 'C', 'D']
```

**Comment by mcastorina** [comment]
Thanks for reporting. I did some investigation in the encoding.csv library and the problem is it only checks the first character of a line for quotes. https://github.com/vlang/v/blob/master/vlib/encoding/csv/reader.v#L124-L134

**Comment by championjared** [comment]
Thanks for fixing and merging so swiftly!
