### ISSUE TITLE
http request for localhost url result in "Terminated by signal 13 (SIGPIPE)"

### ISSUE THREAD

**Issue by ken0x0a** [vlang/v#9196]
**V version:** V 0.2.2 db9b523.98a12fd
**OS:** OS: macos, macOS, 11.2.2, 20D80

**What did you do?**

http request to local endpoint.

```vlang
import net.http

fn main() {
	res := http.get('http://localhost:6789')  or { // Terminated by signal 13 (SIGPIPE)
		eprintln(err.msg)
		exit(1)
	}
	res := http.get('http://127.0.0.1') ? // => Terminated by signal 13 (SIGPIPE)
	res := http.get('http://0.0.0.0') ? // Terminated by signal 13 (SIGPIPE)
	// res := http.get('https://localhost') ? // no crash if "https"
}
```

**What did you expect to see?**
```
cannot connect the endpoint
```
 
**What did you see instead?**
```
Terminated by signal 13 (SIGPIPE)
```

**Comment by changrui** [comment]
for me, panic: `net: socket error: 111`.

**Comment by ken0x0a** [comment]
@changrui Are you using latest version of Vlang, and macOS?

**Comment by shadowninja55** [comment]
i get the proper error now, are you able to test this again on macos? i'm on linux.

**Comment by shadowninja55** [comment]
> @shadowninja55 Yes me too on macos. Thank you!

perfect, thanks for checking
