### ISSUE TITLE
mastermind behind handling '$'

### ISSUE THREAD

**Issue by arhen** [vlang/v#92]
i just playing around $ syntax. 
it's weird for me for some case.

#First case. (Spacing)

```
fn main() {
        a := 'test'
	println('$ a')
}
```
>output: 'test'

#Second case. (just $)

```
fn main() {
	a := 'test'
	println('$')
}
```
>output : '$'

if we combine both case, 
```
fn main() {
        a := 'test'
	println('$ $a')
}

```
>output: unexpected token: `DOLLAR` 

there is what I mean a 'weird' logic.
it should be 
>expected output: '$ test'

what is this mean at all?

**Comment by medvednikov** [comment]
Good find! Fixed.
