### ISSUE TITLE
cross compilation for Windows failed

### ISSUE THREAD

**Issue by yar999** [vlang/v#920]
**V version:**  V 0.1.11
**OS:** windows 10 ubuntu 18.04

**What did you do?**

It's case-sensitive under linux, too many header files in ~/.vlang/winroot/include directory are case-insensitive, leading to compilation failure

```
v -os windows t.v
Cross compiling for Windows...
In file included from /root//.vlang//t.c:21:
In file included from /root//.vlang//winroot/include/windows.h:208:
In file included from /root//.vlang//winroot/include/winscard.h:30:
/root//.vlang//winroot/include/wtypes.h:39:10: fatal error: 'wtypesbase.h' file
      not found
#include "wtypesbase.h"
```

```
root@u18 yst
λ ls ~/.vlang/winroot/include/WTypesbase.h
/root/.vlang/winroot/include/WTypesbase.h
root@u18 yst
λ ls ~/.vlang/winroot/include/wtypesbase.h
ls: cannot access '/root/.vlang/winroot/include/wtypesbase.h': No such file or directory
```

**What did you expect to see?**

 
**What did you see instead?**

**Comment by deangelo2005** [comment]
Help with QTCM

**Comment by joe-conigliaro** [comment]
Ahh yes because by default OSX HFS+ volumes are case insensitive

**Comment by vitalyster** [comment]
Currently cross-compilation should work with mingw64 distributions out of the box without "winroot.zip"
