### ISSUE TITLE
Array append error: declaration of void object

### ISSUE THREAD

**Issue by mcastorina** [vlang/v#9241]
**V version:** V 0.2.2 6a7ef4f
**OS:** linux

**What did you do?**
```v
mut nums := [1 2 3]
x := nums << 4
```

**What did you expect to see?**
Checker / compiler error; should not be able to assign void expressions
 
**What did you see instead?**
Builder error: `error: declaration of void object`

**Comment by mcastorina** [comment]
Related: https://github.com/vlang/v/issues/7545

**Comment by JalonSolov** [comment]
It could be argued that `x` should have been made a copy of `nums << 4` instead of giving a message about a void object.

**Comment by mcastorina** [comment]
Hmm. In my opinion that's not obvious and detracts from V's simplicity, but it *is* similar to `j := i++`, which I'm surprised is valid in V actually.

**Comment by ntrel** [comment]
> j := i++, which I'm surprised is valid in V actually.

This is supposed to error and it does for e.g. `f(i++)`, `arr[i++]`.

**Comment by ntrel** [comment]
> It could be argued that x should have been made a copy of nums << 4

V no longer allows implicit copies of arrays, because the memory allocation should be explicit.
