### ISSUE TITLE
Setting environmental var VMODULES installs correctly but doesn't source correctly 

### ISSUE THREAD

**Issue by 0b1kn00b** [vlang/v#9246]
OS: linux, Ubuntu 20.04.2 LTS
Processor: 4 cpus, 64bit, little endian, Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
CC version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

getwd: /mnt/dat/prj/vanguardia/server
vmodules: /mnt/dat/prj/vanguardia/server/lib/v
vroot: /mnt/dat/prj/vanguardia/server/vendor/v
vexe: /mnt/dat/prj/vanguardia/server/vendor/v/v
vexe mtime: 2021-03-11 07:46:54
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 6a7ef4f

Git version: git version 2.25.1
Git vroot status: weekly.2021.10-34-g6a7ef4f5
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81

**What did you do?**

installed v in `vendor/v`, used a `direnv` to add a `PATH` to `$PRJ_DIR/vendor/v`, put `.vsh` files in `$PRJ_PATH/.bin` and set `VMODULES` to `$PRJ_DIR/lib/v`. 
installed `nedpals.vargs` via `v install`

**What did you expect to see?**  

Calling `import os` works as expected `import vargs` does not

 
**What did you see instead?**
``` fish
.bin/hello_world.vsh:5:1: builder error: cannot import module "vargs" (not found)
    3 | import environment
    4 | import os
    5 | import vargs
      | ~~~~~~~~~~~~
    6 | 
    7 | //execute("git rev-parse --show-toplevel")
```

**Comment by Zerotask** [comment]
It has to be `import nedpals.vargs` instead of `import vargs`.

**Comment by zakuro9715** [comment]
use `import nadpals.varags`. user module via vpm always has username prefix.

**Comment by 0b1kn00b** [comment]
```
dayz@run /m/d/p/v/server (master) [1]> echo $VMODULES
/mnt/dat/prj/vanguardia/server/lib/v
dayz@run /m/d/p/v/server (master)> ls $VMODULES/nedpals/vargs/
LICENSE  README.md  vargs_test.v  vargs.v  v.mod
dayz@run /m/d/p/v/server (master)> v .bin/hello_world.v
.bin/hello_world.v:3:8: warning: module 'varags (nedpals.varags)' is imported but never used
    1 | #!/usr/bin/env -S v run
    2 | 
    3 | import nedpals.varags
      |        ~~~~~~~~~~~~~~
    4 | fn main(){
    5 |     println("hello world!")
.bin/hello_world.v:3:1: builder error: cannot import module "nedpals.varags" (not found)
    1 | #!/usr/bin/env -S v run
    2 | 
    3 | import nedpals.varags
      | ~~~~~~~~~~~~~~~~~~~~~
    4 | fn main(){
    5 |     println("hello world!")
dayz@run /m/d/p/v/server (master) [1]> 
```

**Comment by 0b1kn00b** [comment]
I ought to add that this is done through `envdir`.

**Comment by Terisback** [comment]
`import nedpals.vargs` (You typed it wrong.)

**Comment by 0b1kn00b** [comment]
ah woops. I was that sure. thank you.
