### ISSUE TITLE
Option_string needs str()

### ISSUE THREAD

**Issue by yep84** [vlang/v#925]
**V version:** 0.1.11
**OS:** Linux

**What did you do?**
```
import os

fn main() {
    data := os.read_file('./file.txt')
    println(data)
}   
```

**What did you expect to see?**
My data
 
**What did you see instead?**
pass=2 fn=`main`
panic: http.v:6
`Option_string` needs to have method `str() string` to be printable

So I try to add it to init.v
```
pub fn (s ?string) str() string {
	if s.ok {
		buf := malloc(C.strlen(s.data))// ISSUE: return 1 even if the file contains data
		C.sprintf(buf, '%s', s.data)
		return tos(buf, _strlen(buf))
	} else {
		return 'error'
	}
}
```
But it seams that C.strlen(s.data) always return me 1. What am I doing wrong

**Comment by cytown** [comment]
In macos, it's fine, maybe you can check vlib/os/os_test.v for reproduce.

**Comment by yep84** [comment]
@cytown Thanks for your answer.

You're right the next piece of code is working:
```
import os

fn main() {
    filename := './file.txt'

    read_hello := os.read_file(filename) or {
        panic('error reading file $filename')
        return
    }
    println(read_hello)
}
```
