### ISSUE TITLE
Comparing 2 arrays of a sumtype type ends in a C error.

### ISSUE THREAD

**Issue by StunxFS** [vlang/v#9264]
**V version:** V 0.2.2 d63b7bc
**OS:** Ubuntu MATE 20.04

**What did you do?**
Long ago, when I was bored, I started developing a simple virtual machine. Everything was fine, until I had trouble trying to compare an array of a sumtype with another of the same type. Here is a reproduction I made in the REPL:

```v
>>> type Obj = string | int | []Obj
>>> a := Obj([Obj("Str"), 2])
>>> b := Obj([Obj("Rock"), 777])
>>> if a is []Obj {
... if b is []Obj {
... println(a == b)
... }
... }
```

**What did you expect to see?**
`false`
 
**What did you see instead?**
A C error. The TCC output doesn't help much, so I'll show the error that GCC gives:

```c
/tmp/v/rakad_vm.6813495867899739112.tmp.c: In function ‘Array_main__Object_arr_eq’:
/tmp/v/rakad_vm.6813495867899739112.tmp.c:1678:60: error: invalid operands to binary != (have ‘main__Object’ {aka ‘struct main__Object’} and ‘main__Object’ {aka ‘struct main__Object’})
 1678 |   if (*((main__Object*)((byte*)a.data+(i*a.element_size))) != *((main__Object*)((byte*)b.data+(i*b.element_size)))) {
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       |                                                       |
      |       main__Object {aka struct main__Object}                  main__Object {aka struct main__Object}
```

**Comment by Henrixounez** [comment]
Seems to be working for me now, it returns correctly  `false`. I am closing for now.
If the problem still persists on your side, feel free to reopen.
