### ISSUE TITLE
Internal module support similar to Go

### ISSUE THREAD

**Issue by Insanenotfromthisworld** [vlang/v#9283]
Also, maybe be better not give this opportunity, because we have **one way** ideology.

**Comment by Larpon** [comment]
Can you please specify what "folder will special opportunity" technically does in Go?

**Comment by Insanenotfromthisworld** [comment]
@Larpon [godock](https://golang.org/doc/go1.4#internalpackages)

**Comment by Larpon** [comment]
Thanks for specifying 👍

**Comment by Larpon** [comment]
As I understand it there's currently no plans for this feature.
