### ISSUE TITLE
Const, variable, mutable declaration

### ISSUE THREAD

**Issue by npc51082** [vlang/v#93]
Hi, first of all let me say that this project looks very promising. Good job.

Now, I've seen the docs, and there are (at least) 3 ways of declaring stuff:

```
const (
  PI = 3.14
)

fn main() {
  x := 1
  mut y := 2
}
```

So PI, x and y are what I'm calling "stuff" (constants and variables). And they are declared in very different ways.

I understand the reasoning behind this, as it is inspired by Go. But have you considered using a more "uniform" (in my opinion) syntax:

```
const PI = 3.14

fn main() {
  let x = 1 // x is immutable
  mut y = 2 // y is mutable; could also be var y = 2
}
```

This way every declaration (of variables, constants and functions) would be exactly the same: a keyword (let/mut/const/fn) followed by the name.

Just my thoughts...

**Comment by medvednikov** [comment]
Thanks for your suggestion, but the syntax is final.

**Comment by ntrel** [comment]
`mut` is not just for variable declarations. It will likely be used for struct fields next to the field type. Hopefully mut will be a type modifier, used anywhere a type can be written.

I also think it's good to have `:=` for initialization rather than reusing `=`.
