### ISSUE TITLE
TCP read/write block

### ISSUE THREAD

**Issue by jiuker** [vlang/v#9318]
**V version:** 
**OS:** 
V 0.2.2 fbc02cb
**What did you do?**
shared with TCP;
when i want to write,it will blocked by read;
if nothing to read, it will block always!
**What did you expect to see?**
a way to do with read/write without shared
 
**What did you see instead?**
block always!

**Comment by ZargorNET** [comment]
Can you provide a code example?

**Comment by jiuker** [comment]
`module conn
import cmd
import strconv
import time
pub struct SourceConn{
	addr string
	mut:
		conn Conn
		inc_offset u64
}
pub fn (shared c SourceConn)pre_to_start()?{
	lock c{
		set_port_rsp:=c.conn.cmd_to_resp_first_line(["replconf", "listening-port", "8083"])?
		println("${set_port_rsp}")
		c.conn.write(cmd.cmd_to_string(["psync","?","-1"]))?
		header:=c.conn.read_line().split(" ")
		println('$header')
		rdb_size_str:=c.conn.read_line().replace("$","").replace("\r\n","")
		rdb_size:=strconv.parse_uint(rdb_size_str,10,64)
		println('-$rdb_size_str--$rdb_size-')

		mut rdb_read_count:=u64(0)
		println("start rdb data $rdb_size")
		for rdb_read_count<rdb_size{
			_,read_count_c:=c.conn.recv(int(rdb_size-rdb_read_count))
			rdb_read_count+=u64(read_count_c)
			println("got $rdb_read_count")
		}
		println("rdb done")
		c.inc_offset+=rdb_size
	}
	return
}
pub fn (shared c SourceConn)recv(len int) (string,int){
	lock c {
		return c.conn.recv(len)
	}
	return "",0
}

pub fn (shared c SourceConn)report_offset(){
	for{
		time.sleep(1)
		rlock c {
			println('now offset $c.inc_offset')
		}
		lock c{
			c.conn.write(cmd.cmd_to_string(["replconf", "ack",'$c.inc_offset'])) or {
				println(err)
			}
		}
	}
}
pub fn (shared c SourceConn)add_offset(offset u64){
	lock c{
		c.inc_offset+=offset
	}
}

pub fn (shared c SourceConn)read_line() string{
	lock c{
		return c.conn.read_line()
	}
	return ""
}


pub fn new_source_conn(addr string) ?SourceConn{
	return SourceConn{
		addr:addr,
		conn:dial(addr)?
	}
}`
like this；
when i try to report offset to source，it will block by read_line() or recv() when long time it get nothing!
