### ISSUE TITLE
unsafe { my_immutable_int++ } silently fails to do anything

### ISSUE THREAD

**Issue by elimisteve** [vlang/v#9320]
```shell
$ v doctor
OS: linux, Debian GNU/Linux 9.13 (stretch) (VM)
Processor: 2 cpus, 64bit, little endian, Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
CC version: cc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

getwd: /home/user/django_projects/v/examples/elimisteve
vmodules: /home/user/.vmodules
vroot: /home/user/django_projects/v
vexe: /home/user/django_projects/v/v
vexe mtime: 2021-03-16 03:44:33
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 25c07c2.138da8e

Git version: git version 2.11.0
Git vroot status: weekly.2021.11-13-g138da8e1
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81
```

**What did you do?**

Ran this:

```v
mut numbers := [0, 1, 2]

for num in numbers {
	unsafe {
		num++
	}
}

println(numbers) // should allegedly be [1, 2, 3]
```

**What did you expect to see?**

Either a compiler error or `[1, 2, 3]`.  I think it'd be best to not allow integers to be invisibly made into references at all like we have now with `for mut num in numbers`, but that's another story.

This is mostly confusing because the mutation works here:

```v
mut numbers := [0, 1, 2]

for mut num in numbers {
	num++  // Why is this allowed to change the values in `numbers`?
}

println(numbers) // [1, 2, 3]
```

**What did you see instead?**

`[0, 1, 2]`

**Comment by mcastorina** [comment]
I think this is expected behavior because `num` is a copy of the element. If you print `num` in the immutable for loop you'll get `1 2 3`. When you do `for mut num` it then iterates over the numbers by reference.

If that makes sense.

This might just be the case with basic types. Maybe iterating over structs is different.
