### ISSUE TITLE
Calling generic variadic with array gives C errors instead of compiler error

### ISSUE THREAD

**Issue by Gladear** [vlang/v#9335]
**V version:** V 0.2.2 1753445
**OS:** linux, Ubuntu 20.04.2 LTS (WSL 2)

**What did you do?**
```v
fn max<T>(a ...T) T {
        mut max := a[0]
        for item in a[1..] {
                if max < item {
                        max = item
                }
        }
        return max
}

fn main() {
        // notice the wrong call
        max([1, 2, 3, 4])
}
```

**What did you expect to see?**
An error message telling me the argument is incorrect
 
**What did you see instead?**
A C error

**Comment by skrtdev** [comment]
Maybe it's better to give c error too
