### ISSUE TITLE
Compile-time option doesn't work correctly

### ISSUE THREAD

**Issue by bstnbuck** [vlang/v#9338]
**V version:** V 0.2.2 b4f7a97
**OS:** Debian 10 (**32bit**)

**What did you do?**
```v
fn main() {
	$if x64 {
		println('64 bit')
	} $else {
		println('Maybe 32 bit')
	}
}
```

**What did you expect to see?**
* Output on 32 bit machine: "Maybe 32 bit"
* Output on 64 bit machine: "64 bit"
 
**What did you see instead?**
* "" (nothing) on 32 bit machine
* "64 bit" on 64bit machine

**Comment by spytheman** [comment]
I do not have a 32bit machine right now, but 
`v -gc none -m32 run bb.v`
produces:
`Maybe 32 bit`

**Comment by bstnbuck** [comment]
Seems to be fixed. However, I could only test this with the workaround described here #15447
