### ISSUE TITLE
Byte array not convert in string

### ISSUE THREAD

**Issue by Bleser** [vlang/v#934]
V version: 0.1.11
OS: Ubuntu 18.04

If this error is similar to #766, then I will close this.

Added function to vlib that reads from socket.

```
pub fn (s Socket) read() string {
	mut buf := [1024]byte{}
	r := C.read(s.sockfd, buf, 1024)
	return string(buf)
}
```

I wanted to get the contents of the request.

 
In place of this, I got an error.
```
/home/bleser//.vlang//main.c: In function ‘net__Socket_read’:
/home/bleser//.vlang//main.c:3323:2: error: conversion to non-scalar type requested
  return  ((string)( buf ) ) ;
  ^~~~~~
V panic: clang error
```

**Comment by aguspiza** [comment]
Ha!, no, that is the way is supposed to work. Try removing the {}

**Comment by Bleser** [comment]
@aguspiza Error has not changed

**Comment by medvednikov** [comment]
Indeed `string()` doesn't work with fixed size byte arrays.

**Comment by aguspiza** [comment]
oh, sorry i did not read your code properly. This should work (the tos function instead of string)
```
pub fn (s Socket) read() string {
	mut buf := [1024]byte
	r := C.read(s.sockfd, buf, 1024)
	return tos(buf, 1024)
}
```
I do not know if you should use r instead of 1024 as second parameter though.

**Comment by medvednikov** [comment]
`tos` function will be replaced with `string()`, just like `tos2`.

**Comment by medvednikov** [comment]
Fixed. `string(buf)` now works.
