### ISSUE TITLE
Merge os.exec/os.system/os.system2

### ISSUE THREAD

**Issue by Niek** [vlang/v#935]
Right now there are a couple of ways to execute a command:
* ``os.exec``: execute commands and returns output as string
* ``os.system``: execute commands and returns exit code as int
* ``os.system2``: already removed from the codebase?

It would be nice if these could be merged in 1 method that returns an option type.

**Comment by medvednikov** [comment]
`system2` was removed, yes. `exec` and `system` will be merged once it's possible to return multiple args.

**Comment by medvednikov** [comment]
https://github.com/vlang/v/issues/1637
