### ISSUE TITLE
Using -skip-unused with shared library results in unexported functions

### ISSUE THREAD

**Issue by Ekopalypse** [vlang/v#9360]
V full version: V 0.2.2 6cfc2c2.7222ee4
OS: windows, Microsoft Windows 7 Professional v7601 64-bit

**What did you do?**
Compiled shared library with -skip-unused flag

**What did you expect to see?**
An exported functions called DllMain
 
**What did you see instead?**
no exported functions at all

Here a minimal example

~~~
[windows_stdcall]
[export: DllMain]
fn main(hinst voidptr, fdw_reason int, lp_reserved voidptr) bool{
	// https://docs.microsoft.com/en-us/windows/win32/dlls/dllmain
	// Perform actions based on the reason for calling.
	match fdw_reason {
		// Initialize once for each new process.
		// Return FALSE to fail DLL load.
		C.DLL_PROCESS_ATTACH {
			/*
				Unlike executables, libraries, at least on Windows do not call vinit, 
				hence this hack, workaround, or perhaps it is expected to do so(?). 
				I have no idea, but it seems to do the job.
			*/
			C._vinit(0, 0)
		}
		// Do thread-specific initialization.
		C.DLL_THREAD_ATTACH {}
		// Do thread-specific cleanup.
		C.DLL_THREAD_DETACH {}
		// Perform any necessary cleanup.
		C.DLL_PROCESS_DETACH {}
		else { return false }  // is this correct??
	}
	return true	 // Successful DLL_PROCESS_ATTACH.
}
~~~

**Comment by Ekopalypse** [comment]
Side note: Using TCC and GCC to compile this code behaves differently than using MSVC in terms of exported functions.
If -skip-unused is not used, all three create a DLL with exactly one exported function named DllMain.
When -skip-unused is used, MSVC creates a DLL without any exported functions, where TCC and GCC export all V-internal functions but not DllMain.

**Comment by spytheman** [comment]
This should be fixed in 8193efb .
@Ekopalypse can you please test on windows (I have no easy way to do it right now :-| )?

**Comment by spytheman** [comment]
Note that the function should be `pub` in this case; `export` just adds a wrapper around it with the custom C name.

**Comment by Ekopalypse** [comment]
@spytheman, thanks - yes, the pr fixes the problem and tcc, gcc and msvc produce the same number of exported functions. One difference is that when using -skip-unused only public functions with the export attribute are exported, while without -skip-unused all functions with the export attribute are exported.
