### ISSUE TITLE
Add custom error types to the standard library

### ISSUE THREAD

**Issue by spaceface777** [vlang/v#9367]
Now that custom error types have been implemented into the language (see #8924 and #9043), the next step is to actually *use* these in the standard library.

For example:
 - the e.g. `return error('file `$file` not found')` calls inside the `os` module can be replaced with a new `FileNotFoundError` type
 - the generic `error_with_code` calls in `vlib/net/errors.v` should be replaced with a proper dedicated type for each error code
 - etc., etc.

It might be a good idea to implement these in batches (e.g. one PR could add proper errors to the `net` module, another could document part of `os`...)

**Comment by spaceface777** [comment]
Please note that not every `return error('')` call in vlib needs to be replaced with a custom error type instance. The default error implementation exists for a reason, and is good enough for many cases. Custom errors are most useful in functions that can fail in several different ways, and figuring out what actually caused the error is important.

**Comment by atakanyenel** [comment]
Hello, I had been following V for a while and this indeed looks like a "Good First issue". I want to take a look at this, and if I can, create the first batch of corrections. Feel free to assign this to me, and I will unassign myself, if I can't contribute to this by the end of this week.

**Comment by medvednikov** [comment]
Good luck and thanks @atakanyenel

**Comment by atakanyenel** [comment]
I came up with this example but I'm not sure. Can you give me an approval before I start changing the code base ?
```
pub struct FileNotFound {
	msg  string = 'FileNotFound'
	code int
}

pub struct Unknown {
	msg  string = 'Unknown'
	code int
}

pub fn some_error(n int) ? {
	if n > 5 {
		return IError(FileNotFound{})
	} else {
		return IError(Unknown{})
	}
}

fn main() {
	some_error(10) or {
		match err {
			FileNotFound {
				println(err.msg)
			}
			else {
				println('else')
			}
		}
	}

	some_error(1) or {
		match err {
			Unknown {
				println(err.msg)
			}
			else {
				println('else')
			}
		}
	}
}
``` 
Creating the struct is fine but I'm not sure about the IError(FileNotFound{}) conversion.

**Comment by spaceface777** [comment]
I think you may need `IError(&FileNotFound{})` (due to a current compiler limitation), but it looks good to me otherwise.

Good luck! :)

**Comment by atakanyenel** [comment]
I went through all the modules and did the ones where an operation failed in multiple ways/was small enough component to not change big chunks of code. With this in my mind, only the remaining components remain:
- net
- os
- pg
- szip 
- v
- x
     - openssl
     - websocket

I will stop here for now(unassign myself) because there was a discussion about removing `err.code` from the error struct and I don't want program for a interface that might go away. Once that is finalized, I can implement that for errors.
