### ISSUE TITLE
error with mutable interface

### ISSUE THREAD

**Issue by waotzi** [vlang/v#9377]
**V version: V 0.2.2 00651c8** 
**OS: Manjoro linux** 

when trying to use a mutable interface, the memory access seems to be broken?

in this small gist i made, i try to output a speed number inside a Dog struct method speak, which is used in an interface called Mob.

in the first function it outputs the correct number,
in the second function i get a strange value or 0

https://gist.github.com/waotzi/64d5a56732698782ed36c6bec181ad4e

as spytheman mentions on discord

```
    self.mob = &Dog{}
```
works around the issue

**Comment by Dialga** [comment]
The linked gist no longer exists.

**Comment by ArtemkaKun** [comment]
Hi @waotzi ,

can you share the code one more time?

**Comment by waotzi** [comment]
@ArtemkaKun hi sorry i don't have the gist available anymore, this was a long time ago. i think the problem was solved back on discord.
