### ISSUE TITLE
[docs] Possible misleading 'maps' section of documentation

### ISSUE THREAD

**Issue by anakimluke** [vlang/v#9392]
I have a suggestion regarding the [Maps](https://github.com/vlang/v/blob/master/doc/docs.md#maps) section of the documentation.

The section starts by setting some values for `m`:

    m['one'] = 1
    m['two'] = 2 

Later, it demonstrates how there's more than one way of initializing the values of a map:

    numbers := map{
	    1: 'one'
	    2: 'two'
    }

The problem is that the reader may be misled into believing the syntax for initializing maps is `<value>:<key>`, and not `<key>:<value>`.

I suggest modifying the section to initialize `numbers` as

    numbers := map{
	    'one': 1
	    'two': 2
    }

instead, or using other unrelated key/values.

**Comment by JalonSolov** [comment]
Actually, there's no reason both won't work fine.  Keys can be almost any type, and values can be anything at all.

However, I agree it does seem like it might be a bit ambiguous, rather than explicit which part is the key, and which is the value.
