### ISSUE TITLE
a bug about bdwgc

### ISSUE THREAD

**Issue by lydiandy** [vlang/v#9400]
**V version:** 
latest: V 0.2.2 4d77f38
**OS:**  
macos
**What did you do?**
When I try to use bdwgc on macos, here is the simple code:
```
fn main() {
    println('from main')
    $if gcboehm {
        println('boehm')
    }
}
```
error 1:
builder error: Header file <gc.h>, needed for module `builtin` was not found. Please install the corresponding development headers
fixed by add this in  builtin_d_gcboehm.v
```
$if macos {
	#flag -I@VROOT/thirdparty/bdwgc/include
	#flag -L@VROOT/thirdparty/bdwgc
}
```
error 2:
when run without -gc boehm 

raise an error:
```
main.v:3:9: error: undefined ident: `gcboehm`
    1 | fn main() {
    2 |     println('from main')
    3 |     $if gcboehm {
      |         ~~~~~~~
    4 |         println('boehm')
    5 |     }
```

**What did you expect to see?**

should be compiled
 
**What did you see instead?**

**Comment by medvednikov** [comment]
Fixed.
