### ISSUE TITLE
replace_each incorrect with overlapping keys

### ISSUE THREAD

**Issue by mcastorina** [vlang/v#9411]
**V version:** V 0.2.2 c5bc349
**OS:** linux

**What did you do?**
```v
s := 'hello_world hello'
println(s.replace_each(['hello_world', 'aaa', 'hello', 'bbb']))
```

**What did you expect to see?**
```
aaa bbb
```

**What did you see instead?**
```
aaa h
```

**Comment by changrui** [comment]
? `str.replace(map[string]string)` ?

**Comment by mcastorina** [comment]
```v
fn (s string) replace_each(vals []string) string
```

It's used like `'string'.replace_each(['key1' 'value1' 'key2' 'value2'])`

**Comment by medvednikov** [comment]
wow, good find
