### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by frankmoshe** [vlang/v#9412]
"SQLite Readme" link is broken in "Install SQLite development dependency" section.

**Comment by JalonSolov** [comment]
How is it broken?  That is the correct link, and clicking on that link takes you to the right place.

**Comment by frankmoshe** [comment]
When reading here: https://github.com/vlang/v/tree/master/tutorials/building_a_simple_web_blog_with_vweb
And clicking on "sqlite README" the link sent me to https://github.com/vlang/v/blob/master/tutorials/vlib/sqlite/README.md

**Comment by JalonSolov** [comment]
Thanks for reporting this.  I thought you meant the actual sqlite readme, but once you linked to the tutorial, it was easy to find.
