### ISSUE TITLE
C Error / Sokol Error. Implicit declaration of function 'XIQueryVersion' && XIEventMask Undeclared.

### ISSUE THREAD

**Issue by CoryMConway** [vlang/v#9422]
**V version:** 
**OS:** 
OS: linux, elementary OS 5.1.7 Hera
CC version: cc (Homebrew GCC 5.5.0_7) 5.5.0
V full version: V 0.2.2 c76c69e.a00c80b
thirdparty/tcc status: thirdparty-linux-amd64 7543de81

**What did you do?**
cd to v/examples/2048. 
v run 2048.v

There were problems

I ran:
cd /usr/include/X11/extensions
sudo ln -s XI.h XInput.h
sudo ln -s XI2.h XInput2.h
mkdir /usr/include/X11/Xcursor
Then I copied the code from https://code.woboq.org/gtk/include/X11/Xcursor/Xcursor.h.html and pasted it into /usr/include/X11/Xcursor
Then I was missing GL/gl.h
So I searched for it using: apt-file search "gl.h"
Then saw mesa-common-dev is what I needed so I ran
sudo apt install mesa-common-dev

**What did you expect to see?**
I expected the 2048.v graphical game to pop up.

 
**What did you see instead?**

In file included from /tmp/v/2048.4254372944621190437.tmp.c:780:
/home/cory/Libraries/v/thirdparty/sokol/sokol_app.h:8386: warning: implicit declaration of function 'XIQueryVersion'
In file included from /tmp/v/2048.4254372944621190437.tmp.c:780:
/home/cory/Libraries/v/thirdparty/sokol/sokol_app.h:8768: error: 'XIEventMask' undeclared
builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

**Comment by CoryMConway** [comment]
I ran apt-file search XInput2.h and it came up with libxi-dev

Running this command fixed it.
sudo apt install libxi-dev

**Comment by CoryMConway** [comment]
I ran apt-file search XInput2.h and it came up with libxi-dev

Running this command fixed it.
sudo apt install libxi-dev

**Comment by Larpon** [comment]
Thanks for keeping us updated so others can benefit from your time spent with this!

**Comment by CoryMConway** [comment]
> Thanks for keeping us updated so others can benefit from your time spent with this!

No problem! This language is super cool and I look forward to contributing more.

**Comment by medvednikov** [comment]
This is actually documented in readme.md

> NB: In order to build Tetris or 2048 (or anything else using sokol or gg graphics modules) on some Linux systems, you need to install libxi-dev and libxcursor-dev .
