### ISSUE TITLE
Go/V wiki page

### ISSUE THREAD

**Issue by xxxserxxx** [vlang/v#9424]
The ["Hello World!" example](https://github.com/vlang/v/wiki/V-for-Go-developers) for Go *could* be:

```
package main
func main() {
    println("Hello World!")
}
```

Just like V, Go has built-in "print" and "println" primatives.  Using the `fmt` package in this example is unnecessary and could appear to be trying to make the Go version seem longer (compared to V) than it needs to be.

An example using `Printf()` would better demonstrate the differences between the languages and would require the `fmt` package.  E.g.,

```
package main
import "fmt"
func main() {
    pi := 3.14159
    fmt.Printf("Hello Pi (%3.3f)\n", pi)
}
```
and V
```
pi := 3.14159
println('${pi:3.3f}')
```

**Comment by medvednikov** [comment]
using println is officially not recommended by the Go team, and it will likely be removed soon
