### ISSUE TITLE
ошибка при работе с кириллицей

### ISSUE THREAD

**Issue by MDagaev** [vlang/v#9430]
Не правильно выводит длину строки в кириллице

`text:= 'ПриветКатя'`
`println(text.len) // выдает что длина строки 20 вместо 10`

Не правильно выводит слайсы

`text:= 'ПриветКатя'`
`println(text[1..3]) // выдает �� вместо 'ри'`

**Comment by medvednikov** [comment]
This behavior is expected, works like in Go.

Strings are arrays of bytes, not codepoints.

`[]rune` will be used for this in the future, for now there's `ustring`.

`text.ustring().len` // 10

**Comment by MDagaev** [comment]
А со слайсами тогда как тоже в Go документацию смотреть???

**Comment by tandr** [comment]
@MDagaev 

https://play.golang.org/p/QYNR1mHC6Pl

**Comment by hungrybluedev** [comment]
Runes have been implemented now:

```
fn main() {
	text:= 'ПриветКатя' 
	println(text.len)            // 20 bytes
	println(text.runes().len)    // 10 runes
	println(text.runes()[1..3])  // [`р`, `и`]
}
```

**Comment by MDagaev** [comment]
Вот вы с рунами "запарились"
Выскажу свое мнение 
Если выводит строку в массивах байтов, так и надо было явно указывать что вывод строки в байтах (а оно  у вас по умолчанию стоит)
А вот вывод строки в кодовых символах надо было по умолчанию установить. И тогда геморроя с рунами не было.
Текст кода был бы проще и короче

**Comment by medvednikov** [comment]
@MDagaev   Использование кодовых символов по умолчанию для всех строк очень затратно по производительности.

Строки - базовый примитив, в большинстве случаев вычисление unicode codepoints не нужно.

Здесь мы полностью копируем подход Go, за исключением лишь `for x in string {`, тут проход тоже идёт по байтам, для рун надо использовать явное `for x in str.runes() {`.

**Comment by tandr** [comment]
@medvednikov (sorry, I don't  have Russian keyboard here)
Couple of out-of-there ideas

1. (drastic) Add string.bytes(), and drop string.len and iterators from string (declare obsolete, drop later). This way user have to specify over what is he iterating - bytes or runes - forcing to think each time what is "1 unit of string" for each case.
2.  (less drastic) Add string.bytes(), and everywhere in documentation where len() or iteration is used, say that it is expanded to string.bytes() call. I hope that would cause less confusion than a current semi-implicit "it is cast (viewed) as array of bytes".
3. (very drastic) Make string.len and iteration over string as an iteration over runes. String is logically an aggregation of runes after all, and byte is just a storage unit. (IMHO, Go does it wrong - it exposes iteration as storage-oriented, not logic one). Java and .NET has it that way - when you are iterating over string, you are iterating over characters, not bytes. And V is not Go, right ;) ?

> Постоянно надо держать в голове что длина строки в байтах длиннее строки в символах в 2 раза. что не совсем гууд
Well, I might suspect it is not always 2 bytes. UTF-8 symbol could be encoded from 1 to 7( or 6?) bytes. Try to use Chinese or any other multibyte, and I think it will end up with much less predictable length of string. https://play.golang.org/p/MJIMUnFHYyG

**Comment by JalonSolov** [comment]
"The maximum number of bytes per character is 4 according to RFC3629 which limited the character table to U+10FFFF."

**Comment by tandr** [comment]
Yes, you are right, it looks like it is limited to 4 bytes max.
