### ISSUE TITLE
Discord invite doesn't work

### ISSUE THREAD

**Issue by pibuxd** [vlang/v#9450]
Unable to accept the invite (I'm not banned). Maybe you can update a Discord invite.

**Comment by AliChraghi** [comment]
are you tried [this](https://discord.com/invite/vlang)?

**Comment by pibuxd** [comment]
yes, this invite doesn't work for me

**Comment by pibuxd** [comment]
![image](https://user-images.githubusercontent.com/60739485/112332547-1e97c280-8cba-11eb-8033-dcdfb300c991.png)

I've tried on the different accounts; still nothing :/

**Comment by AliChraghi** [comment]
try this https://discord.gg/fS5YbEBg

**Comment by AliChraghi** [comment]
Ali C#0468

**Comment by pibuxd** [comment]
weird, the same error ://///

**Comment by AliChraghi** [comment]
reinstall discord, relogin and ...

**Comment by pibuxd** [comment]
I am banned :/, how?

**Comment by pibuxd** [comment]
Just saw that I got banned

**Comment by AliChraghi** [comment]
what's your name in discord?

**Comment by pibuxd** [comment]
Bobik#4810

**Comment by pibuxd** [comment]
But in other accounts I can't also join

**Comment by AliChraghi** [comment]
what?

**Comment by pibuxd** [comment]
Can you check if I'm banned?

**Comment by AliChraghi** [comment]
do you ever joined with other accounts?

**Comment by pibuxd** [comment]
no, but I have the same errors

**Comment by pibuxd** [comment]
do you have permission to check if I've been banned?

**Comment by AliChraghi** [comment]
> Can you check if I'm banned?

wait...

**Comment by AliChraghi** [comment]
> do you have any permission to check if I've been banned?

no, i have't but tell to moderators

**Comment by AliChraghi** [comment]
please wait, here time is 0:01
i follow your problem tomorrow
