### ISSUE TITLE
Tuple leak in custom iterators

### ISSUE THREAD

**Issue by mcastorina** [vlang/v#9459]
**V version:** V 0.2.2 8b7085e
**OS:** linux

**What did you do?**
```v
struct TestStruct {}
fn (t TestStruct) next() ?(string, string) {
    return 'foo', 'bar'
}

t := TestStruct{}
for x in t {
    println(x) // ('foo', 'bar')
    break
}
```

**What did you expect to see?**
Compilation error
 
**What did you see instead?**
```
('foo', 'bar')
```

**Comment by Gladear** [comment]
Why would you want an error here ? This seems pretty correct to me

**Comment by mcastorina** [comment]
Tuple's aren't a supported type in V. You can't do anything with that variable besides print it.

That's why I called this bug a "leak"

**Comment by zakuro9715** [comment]
Yes. V don't have tuple. multi-return is not tuple. So I Agree too this is bug

**Comment by jfontan** [comment]
There's an example in the documentation that also shows this behavior that should be changed.

https://github.com/vlang/v/blob/master/doc/docs.md#array-method-chaining
