### ISSUE TITLE
Different output with different compiler backends

### ISSUE THREAD

**Issue by hanabi1224** [vlang/v#9463]
**V version:**  V 0.2.2 03d5686
**OS:**  windows sub linux ubuntu 20.04

**What did you do?**
``` bash
v install hanabi1224.biginteger
v -cc clang run $HOME/.vmodules/hanabi1224/biginteger/examples/pidigits.v 30 | md5sum
# output: 4f219d6d3dc126278adfda767eddff4c
v -cc clang -prod run $HOME/.vmodules/hanabi1224/biginteger/examples/pidigits.v 30 | md5sum
# output: 31d3c210d6cd62b082b2493cbbf81591
v -cc gcc run $HOME/.vmodules/hanabi1224/biginteger/examples/pidigits.v 30 | md5sum
# output: 31d3c210d6cd62b082b2493cbbf81591
v -cc gcc -prod run $HOME/.vmodules/hanabi1224/biginteger/examples/pidigits.v 30 | md5sum
# output: 31d3c210d6cd62b082b2493cbbf81591
```

**What did you expect to see?**
clang backend without -prod should produce the same output
 
**What did you see instead?**
clang backend produces different output from with -prod or gcc with/without -prod

**Comment by RiordanIX** [comment]
I would expect them to be different with the `-prod` flag given. What's weird is that GCC has the same output with or without the `-prod` flag.

**Comment by JalonSolov** [comment]
Agreed.  Different output is expected (but not guaranteed), based on optimizations done, etc.

What really amazes me is that `clang -prod`, `gcc`, and `gcc -prod` all produced the same output... or at least output that generated the same md5sum.
