### ISSUE TITLE
v wrapper: unknown command

### ISSUE THREAD

**Issue by skrtdev** [vlang/v#9465]
v wrapper command seems to not exist

**Comment by AliChraghi** [comment]
because V don't have `wrapper` command

**Comment by Gladear** [comment]
The command will likely eventually exist, but there is no release plan currently.
Where did you see it @skrtdev ?

**Comment by skrtdev** [comment]
https://github.com/vlang/v/blob/master/doc/docs.md#translating-c-to-v

**Comment by AliChraghi** [comment]
this feature is in progress...

**Comment by medvednikov** [comment]
`c2v wrapper file.v`
