### ISSUE TITLE
Improve "-skip-unused"

### ISSUE THREAD

**Issue by IngwiePhoenix** [vlang/v#9470]
After talking about it in #9446 , I went and made a very very simple test:

```v
C.printf(c'hello')
```

And compiled it: `v build test.v -o test.c -skip-unused && gcc test.c -o test -Os`
Then I wrote the exact same in C and compiled that. The difference is impressive.

```
 wc -c test c-test
75664 test
16608 c-test
```

Looking at the V generated output, there is a lot of functions that will all never be called by `main__main()`. Well that, and many `const`s are not used, either.

So, here is a feature request to improve `-skip-unused`! :)

**Comment by JalonSolov** [comment]
We don't need a feature request for this, as it is already known and being worked on.
