### ISSUE TITLE
Struct that was returned via optional not accessible in template

### ISSUE THREAD

**Issue by fnetX** [vlang/v#9480]
**V version:** V 0.2.2 f29ca6b.7620369
**OS:** GNU Linux / Debian Bullseye (testing)

**What did you do?**
~~~
pub fn (mut app Campaign) question_view(id int, show_thanks bool) vweb.Result {
	question2 := get_question(app.db, id) or { return app.error_404("") }
	question := Question {
		id: 1
	}
	return $vweb.html()
}
fn get_question(db sqlite.DB, id int) ?Question {
	question_query := sql db {
		select from Question where id == id
	}
	if question_query.id == id {
		return question_query
	} else {
		return error ("Question not found")
	}
}
~~~
I have this in a file and try to access `@question2` from a template.

**What did you expect to see?**
I get the content of `@question2`

 
**What did you see instead?**
`error: unexpected argument, current function does not return anything`
But it works for `@question`

**Comment by fnetX** [comment]
This works:
~~~
question_workaround := get_question(app.db, id) or { return app.error_404("") }
question := question_workaround
~~~

**Comment by fnetX** [comment]
Furthermore it would be cool to handle optionals directly in the template. Currently, I can't see a way to use functions or fields with optionals in templates.

**Comment by timurgordon** [comment]
Found another solution @fnetX , not sure if it was added later on, do you think this solves the issue? It would be nicer if the optional could be unwrapped in the template with an if statement but this seems to do the trick.
```
@optional != none
    optional?.prop
@end
```

**Comment by jacksonmowry** [comment]
I believe this has been solved and I have created a minimal reproduction.
```v
module main

import vweb

struct App {
	vweb.Context
}

struct Question {
	id int
}

fn main() {
	vweb.run(&App{}, 8080)
}

@['/']
pub fn (mut app App) question_view() vweb.Result {
	question2 := get_question() or { return app.not_found() }
	question := Question{
		id: 1
	}
	return $vweb.html('view.html')
}

fn get_question() !Question {
	return Question{}
}
```
The route responds with:
```html
<div>
  Question{
    id: 0
}
</div>
<div>
  Question{
    id: 1
}
</div>
```
