### ISSUE TITLE
Improve mutable to reference assignment error

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#9481]
**V version:** 0.2.2
**OS:** Linux

Assigning a reference to a mutable didn't throw any v error, but instead threw a C error.
Would be nice to have this check part of V 👍🏽 

### Code
```v
module main 

struct MyType{}

pub fn foo(mut a MyType, b &MyType) {
	unsafe { a = b }
}

fn main(){
}
```

### Error
```
/tmp/v/warnings.9873847696466107722.tmp.c:9206: error: cannot convert 'struct main__MyType *' to 'struct main__MyType'
...
==================
(Use `v -cg` to print the entire error message)
```

**Comment by duarteroso** [comment]
Check still missing

**Comment by duarteroso** [comment]
I've updated the snippet with an `unsafe` block. Check still missing tho.

**Comment by medvednikov** [comment]
Fixed.
