### ISSUE TITLE
 error: cannot convert 'void' to 'int'

### ISSUE THREAD

**Issue by Dialga** [vlang/v#9488]
**V version:** Latest git
**OS:** Arch Linux x64

**What did you do?**
`int(print(42))`
and
`string(print(42))`

**What did you expect to see?**
error msg
 
**What did you see instead?**
```
>>> int(print(42))
==================
/tmp/v/.noprefix.01F1T522PCPTCWQ9EDHB8J5XRA.vrepl_temp.11281618594918424963.tmp.c:14786: error: cannot convert 'void' to 'int'
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by Dialga** [comment]
Unrelated, but also an issue:
```
>>> print(""[0])
V panic: string index out of range: 0 / 0
/tmp/v/.noprefix.01F1T5P6Q4P42ZNY00ZD862XG9.vrepl.3266298568202043825.tmp.c:6360: at v_panic: Backtrace
/tmp/v/.noprefix.01F1T5P6Q4P42ZNY00ZD862XG9.vrepl.3266298568202043825.tmp.c:9494: by string_at
/tmp/v/.noprefix.01F1T5P6Q4P42ZNY00ZD862XG9.vrepl.3266298568202043825.tmp.c:14792: by main__main
/tmp/v/.noprefix.01F1T5P6Q4P42ZNY00ZD862XG9.vrepl.3266298568202043825.tmp.c:14915: by main
```

**Comment by spaceface777** [comment]
> Unrelated, but also an issue:
> 
> ```
> >>> print(""[0])
> V panic: string index out of range: 0 / 0
> ```

imho, this one is *not* an issue - you're getting a runtime panic since you're accessing an out-of-bounds index of a string.

**Comment by JalonSolov** [comment]
Well, V should have warned that print doesn't return anything, so there was nothing to cast.

**Comment by Dialga** [comment]
> > Unrelated, but also an issue:
> > ```
> > >>> print(""[0])
> > V panic: string index out of range: 0 / 0
> > ```
> 
> imho, this one is _not_ an issue - you're getting a runtime panic since you're accessing an out-of-bounds index of a string.

Oh you're right, deleting
