### ISSUE TITLE
Types between `<>` are not checked

### ISSUE THREAD

**Issue by crthpl** [vlang/v#9492]
**V version:** 
V 0.2.2 76dc4cf
**OS:** 
any
**What did you do?**
```v
fn a<T>(b T) {
    println(b) // true!
}

fn main() {
    a<bool>(1) // setting this to 0 causes it to print false
}
```

**What did you expect to see?**
`error: 1 is not a bool`
 
**What did you see instead?**
`true` (false if `0`)

This can be used just like unions

**Comment by ZargorNET** [comment]
This only works because a `1` or `0`is interpreted as a boolean in C. 
When using a `"string"` instead of the 1, you actually get a C compiler error
```
==================
/tmp/v/test2.8045241377885168911.tmp.c:9215: error: cannot convert 'struct string' to 'unsigned char'
...
==================
(Use `v -cg` to print the entire error message)
```

**Comment by dumblob** [comment]
@ZargorNET it shouldn't work as `int` is not castable to `bool` in *V*.
