### ISSUE TITLE
Compiler error when asserting net.Addr

### ISSUE THREAD

**Issue by inxomnyaa** [vlang/v#9505]
**V version: 0.2.2** 
**OS: Windows 10 20H2** 

**What did you do?**
I created a struct that holds a `net.Addr` and some other values. See https://github.com/WolvesFortress/VRakLib/blob/rewrite/open_connection_request2.v

After that i tried to assert 2 OpenConnectionRequest2 structs and got a compiler error.

**What did you expect to see?**
Assert failing or passing (i compared 127.0.0.1:54132 to 128.255.255.244:54132 because my address decode was asymmetrical)

 
**What did you see instead?**
The generated C code created an additional `struct` in the sockaddr compare function
```c
static bool struct sockaddr_struct_eq(struct sockaddr a, struct sockaddrb) {
if (a.sa_family != b.sa_family) {
return false;
}
return true;
}
```

**Comment by felipensp** [comment]
Is this still an issue?

**Comment by inxomnyaa** [comment]
I actually have no clue, i've moved on from working with this language due to all these minor annoyances

**Comment by felipensp** [comment]
You can help us make V better. V has been improved on every day. So each bug report is important to increate V consistency base through its tests.

I'm closing this report due no real reproducible test case provided. If you still having the real code which triggers the bug, feel free to post here.

Thanks.

**Comment by medvednikov** [comment]
It's definitely not an issue anymore.
