### ISSUE TITLE
Error when using an array of a struct in an intreface

### ISSUE THREAD

**Issue by waotzi** [vlang/v#9511]
**V version: V 0.2.2 c1d4074** 
**OS: Manjaro Linux** 

**What did you do?**
I tried running this code
```
struct Room {}


interface House {
    rooms []Room 
    
}
```

**What did you expect to see?**
no error
 
**What did you see instead?**
this error
```
/tmp/v/main.1947781590065766840.tmp.c:719: error: ';' expected (got "Array_main__Room")
```

**Comment by medvednikov** [comment]
Good find. This was only happening for arrays. @Henrixounez has just fixed it.
