### ISSUE TITLE
os.ls() 

### ISSUE THREAD

**Issue by anaisabelamr** [vlang/v#953]
**V version:** 0.1.10
**OS:** Windows 10

**What did you do?**
files = os.ls('C:\Users\UserName\Desktop')

**What did you expect to see?**
The array files filled with file names.
 
**What did you see instead?**
Empty array.

**Comment by benjione** [comment]
See pull request #951. I think this pull request would solve your issue.

**Comment by medvednikov** [comment]
Fixed.
