### ISSUE TITLE
map.delete() error

### ISSUE THREAD

**Issue by hxhgzz** [vlang/v#9530]
**V version:** V 0.2.2 3ced970
**OS:** Linux  5.11.6-1-MANJARO  x86_64 GNU/Linux

**What did you do?**
doc:
```
mut m2 := map{
  1: 'one'
  2: 'two'
}
println(m2[1])	// one
m2.delete(1)	// error
```

**What did you expect to see?**
no error
 
**What did you see instead?**
error: cannot use `int literal` as `string` in argument 1 to `map[int]string.delete`

**Comment by ZargorNET** [comment]
There is only one `delete` method for map defined which only accepts a string. 
So use for now ``m2.delete("1")`` this works

**Comment by hxhgzz** [comment]
@ZargorNET Thank you for your reply. but `m2.delete("1") `It doesn't work,unless the key is a string

**Comment by ZargorNET** [comment]
> @ZargorNET Thank you for your reply. but `m2.delete("1") `It doesn't work,unless the key is a string

For me it works 
![image](https://user-images.githubusercontent.com/15694339/113406988-bc6f4980-93ac-11eb-96c4-c05f8869bc47.png)

**Comment by hxhgzz** [comment]
> > @ZargorNET 谢谢您的答复。 但 `m2.delete("1") `除非键是字符串，否则它不起作用
> 
> 对我来说有效
> ![图像](https://user-images.githubusercontent.com/15694339/113406988-bc6f4980-93ac-11eb-96c4-c05f8869bc47.png)

try `println(m2)` after delete
