### ISSUE TITLE
Cannot assign struct function to struct member map

### ISSUE THREAD

**Issue by Ekopalypse** [vlang/v#9532]
V 0.2.2 15d9f50, timestamp: 2021-03-30 11:40:23 +0200 
OS: windows, Microsoft Windows 7 Professional v7601 64-bit

**What did you do?**
~~~
module main

struct Application {
mut:
	shortcuts map[int]fn()
}

fn (a Application) test() {
	println('test called')
}

fn main() {
	mut app := Application{}
	app.shortcuts = map{1: app.test}
	app.shortcuts[1]()
}

~~~

**What did you expect to see?**
printing the line `test called`
 
**What did you see instead?**
error: type `Application` has no field or method `test`.

**Comment by Delta456** [comment]
With latest V version and code edit. The following example compiles:

```v
module main

struct Application {
mut:
	shortcuts map[int]fn()
}

fn (a Application) test() {
	println('test called')
}

fn main() {
	mut app := Application{}
	app.shortcuts = {1: app.test}
	app.shortcuts[1]()
}
```

Output:
```
test called
```
