### ISSUE TITLE
error: unknown type name 'Array_fixed_byte_512'

### ISSUE THREAD

**Issue by AlbertoGP** [vlang/v#9537]
V full version: V 0.2.2 c1d4074
OS: linux, "Void Linux"
Processor: 32 cpus, 64bit, little endian, ppc64le
CC version: cc (GCC) 10.2.1 20201203

`array_fixed_byte.v` is:
```v
type Block = [512]byte
```

Result is:
```
$ v -cg array_fixed_byte.v 
/tmp/v/array_fixed_byte.17656917884316645732.tmp.c:721:9: error: unknown type name 'Array_fixed_byte_512'
  721 | typedef Array_fixed_byte_512 main__Block;
      |         ^~~~~~~~~~~~~~~~~~~~
builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please raise an issue on GitHub:
...
```

Expected result is that `Block` is a new type name for a block of 512 bytes.
If there is something I can do to help solve this please let me know. I’m in Discord too.

**Comment by AlbertoGP** [comment]
The generated C with `v -o out.c array_fixed_byte.v` includes the following:
```c
... (at line 715)
typedef Array_fixed_byte_512 main__Block;
... (at line 802)
typedef byte Array_fixed_byte_512 [512];
...
```

However, the file `/tmp/v/array_fixed_byte.17656917884316645732.tmp.c` mentioned in the error message above,has:
```c
... (at line 721)
typedef Array_fixed_byte_512 main__Block;
... (at line 808)
typedef byte Array_fixed_byte_512 [512];
... 
```

**Comment by medvednikov** [comment]
Good find, thanks.
