### ISSUE TITLE
val := get_optional()? doesn't compile; meaning

### ISSUE THREAD

**Issue by ntrel** [vlang/v#954]
Last I tried the syntax doesn't compile. It's needed ATM for #948.

I'm also not sure how it's supposed to work. First the docs say: 
```
resp := http.get(url)?
```
*the error is propagated to the calling function or in case of main leads to a panic*

But then:
*Basically the code above is a shorter version of*
```
resp := http.get(url) or {
	panic(err)
}
```
But if the current function returns an optional, would it be better to expand to:
```
resp := http.get(url) or {
	return err
}
```
So propagating err to the caller. Perhaps this was intended.

**Comment by decadedelta** [comment]
It's supposed to only panic if you propagate it from the main function, so it should be equivalent to the second variant.

**Comment by Ivo-Balbaert** [comment]
Now this syntax does compile:
	resp := http.get('https://hacker-news.firebaseio.com/v0/topstories.json')?

tested in news_fetcher.v on Windows and Ubuntu.
