### ISSUE TITLE
linux_or_macos defined incorrectly

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#9545]
**V version:** 0.2.2
**OS:** Linux

#### Description

Trying to use a builtin option is throwing a C error. 
Because it is a builtin I should not need to `v -d <option>`, nevertheless using it also fails

```v
module main

fn main(){
	$if linux_or_macos {
		println('linux_or_macos')
	}
	$else {
		println('som\' else')
	}
}
```

#### Command

* `v file.v`
* `v -d linux_or_macos file.v`

#### Results

`/tmp/v/###.tmp.c:9215: error: identifier expected`

#### Generated C

```c	
#if defined()
{
}
#elif defined(_WIN32)
{
}
#else
{
    return (Option_vidirectory__Directory){.state=2, .err=v_error(_SLIT("Platform not supported")) };
}
#endif
```

**Comment by JalonSolov** [comment]
This problem doesn't have anything to do with conditional optionals, or anything of that nature.

The root cause is that the comptime variable `linux_or_macos` returns an empty string, so there is no identifier to be defined.

**Comment by spytheman** [comment]
Thanks for the investigation - in c16d491, that is deprecated in favor of `$if linux || macos {` .

**Comment by duarteroso** [comment]
> This problem doesn't have anything to do with conditional optionals, or anything of that nature.
> 
> The root cause is that the comptime variable `linux_or_macos` returns an empty string, so there is no identifier to be defined.

You say it has nothing to do with conditional.
Shouldn't `v -d linux_or_macos file.v` make that code worth tho? Yet it didn't (haven't tried the new version)
