### ISSUE TITLE
Return value from main

### ISSUE THREAD

**Issue by duselguy** [vlang/v#9558]
Unfortunately, in this area Vlang follows Golang (not C) - exit(value) instead of return(value).
The code:
`fn main() {
  ...
  exit(1)
}`
Result (_vcleanup is **not** called, because we are exiting in main__main via exit):
`int main(int ___argc, char** ___argv){
	_vinit(___argc, (voidptr)___argv);
	main__main();
	_vcleanup();
	return 0;
}`

**Comment by dumblob** [comment]
Potentially related discussion: https://github.com/vlang/v/issues/9388

**Comment by medvednikov** [comment]
Why unfortunately? This is much cleaner and simpler.

_vcleanup bug is simple to fix.

**Comment by duselguy** [comment]
Exit means immediately leave of the program passing the control to the system.
Return may have a lot of the code under the hood.
A simple fix (for example, add the call of _vcleanup to v_exit) looks incorrect, because nothing with its own behavior should precede the real exit.
Also, exit and return from main have different behavior, but it is another story.

**Comment by tandr** [comment]
(Disclaimer: I am not a V specialist)

from what it looks like from  - `exit(1)` should be invoking all required cleanup, and something like `abort(1)` (if it exists) should not. (and if `abort()` does not exist, maybe it should be added?...)

**Comment by JalonSolov** [comment]
`panic()` is the "exit immediately with no cleanup" routine.  `exit()` is just... an exit.

**Comment by dumblob** [comment]
@tandr see the comment https://github.com/vlang/v/issues/9558#issuecomment-812918260 above (i.e. please read the discussion https://github.com/vlang/v/issues/9388 ).
