### ISSUE TITLE
Failed to compile with weird error when struct as argument during function type declaration

### ISSUE THREAD

**Issue by fiatjaf** [vlang/v#9564]
**V version:** V 0.2.2 205fb88.fb302c6
**OS:** linux, Linux version 5.7.11-arch1-1 (linux@archlinux) (gcc version 10.1.0 (GCC), GNU ld (GNU Binutils) 2.34.0) #1 SMP PREEMPT Wed, 29 Jul 2020 21:38:21 +0000

**What did you do?**
Tried to compile this:
```v
struct Xx {
	a map[string]fn (Xx, int)
}

fn main() {}
```

**What did you expect to see?**
I expected it to format the file.
 
**What did you see instead?**
```
./main.v:2:26: error: expecting type declaration
    1 | struct Xx {
    2 |     a map[string]fn (Xx, int)
      |                             ^
    3 | }
    4 |
```

Any struct I pass as an argument to that function there will cause this error to appear, but if I replace `Xx` for any primitive type then it will work.

**Comment by billpcs** [comment]
Using the new, non-deprecated syntax now works:

```v
struct Xx {
        a map[string] fn(x Xx, y int)
}

fn main() {}
```

**Comment by fiatjaf** [comment]
The difference being that you have to put a name on arguments?

**Comment by billpcs** [comment]
Yes!

**Comment by fiatjaf** [comment]
Thank you!
