### ISSUE TITLE
operator - not defined on `rune`

### ISSUE THREAD

**Issue by 0x9ef** [vlang/v#958]
**V version:** 0.1.11
**OS:** win 10 x64

**What did you do?**
```
const (
	R = rune(0x9e8f)
)

fn main() {
	r := R - rune(0x0)
}
```

**What did you expect to see?**
Nothing. R declarated but not used. 
 
**What did you see instead?**
operator - not defined on `rune`

**Comment by ntrel** [comment]
Can you give a good use case for allowing arithmetic on runes? I accept arithmetic on ASCII bytes, but UTF-32 runes are a bit different.

**Comment by 0x9ef** [comment]
Rune is alias of `i32`. See as implemented in golang https://golang.org/doc/go1#rune .
I have not seen anywhere that the author wrote the concept of runes. If author wants to bring the runes just like unicode codepoint without any arithmetic on runes. Let him. But im used to rune like as alias with any arithmethic operation. If rune be used without any arithmetic operation, we just pass the output data in function as rune.

**Comment by ntrel** [comment]
> Rune is alias of i32

In Go it is, in V it's a distinct type that doesn't convert to i32. rune should stay distinct because it should print differently from i32, and it has a different range of valid values for UTF-32.

**Comment by crthpl** [comment]
can this be closed?

**Comment by ka-weihe** [comment]
This works in V 0.2.2 f8f74d8
