### ISSUE TITLE
cannot register struct `time.Time`

### ISSUE THREAD

**Issue by ghosttk** [vlang/v#9583]
_**Running v command from windows7 , I got these messages:**_

Welcome to the V REPL (for help with V itself, type `exit`, then run `v help`).
failed    cmd: "E:\bin\v\v.exe" "E:\bin\v\cmd\tools\vrepl.v"
failed   code: 1
V panic: E:\bin\v\vlib\time\time.v:41:12: error: cannot register struct `time.Time`, another type with this name exists
   39 |
   40 | // Time contains various time units for a point in time.
   41 | pub struct Time {
      |            ~~~~
   42 | pub:
   43 |     year        int
C:/Users/RUNNER~1/AppData/Local/Temp/v/v2.13548946643011722082.tmp.c:13087: at v_panic: Backtrace
C:/Users/RUNNER~1/AppData/Local/Temp/v/v2.13548946643011722082.tmp.c:17961: by os__execute_or_panic
C:/Users/RUNNER~1/AppData/Local/Temp/v/v2.13548946643011722082.tmp.c:28790: by v__util__launch_tool
C:/Users/RUNNER~1/AppData/Local/Temp/v/v2.13548946643011722082.tmp.c:14025: by main__main
C:/Users/RUNNER~1/AppData/Local/Temp/v/v2.13548946643011722082.tmp.c:14496: by wmain
006caf78 : by ???
006cb0db : by ???

**Comment by mcastorina** [comment]
What version of V are you running?

**Comment by ghosttk** [comment]
V 0.2.2

**Comment by JalonSolov** [comment]
The commit version makes a big difference as well, so please always post the full output of `v version`.

With latest commit, I don't get the error you saw, but it doesn't work correctly for me, either.  It just exits immediately with no error
```
PS D:\> v
Welcome to the V REPL (for help with V itself, type `exit`, then run `v help`).
V 0.2.2 46e7e27
Use Ctrl-C or `exit` to exit, or `help` to see other available commands
>>>
PS D:\>
```

**Comment by ghosttk** [comment]
PS C:\Users\Administrator> v version
V 0.2.2 7664964

**Comment by ghosttk** [comment]
_**This version failed too.**_

PS C:\Users\Administrator> v version
V 0.2.2 a4fb851

**Comment by JalonSolov** [comment]
The is working fine for me with `V 0.2.2 8c95f07` - 26 commits beyond what you have.

V is still a very fast moving project.  If you see a problem, do `v up` then try it again - it may already be fixed.

**Comment by ghosttk** [comment]
Thank you，but running 'v up' get the same errors.

**Comment by JalonSolov** [comment]
You may have to do what I do... `git pull` then `./make.bat` instead of `v up`.

**Comment by ghosttk** [comment]
After building the latest version ,this error dissappears, thank you very much!

**Comment by JalonSolov** [comment]
Welcome.  Thanks for sticking with it.  :-)
