### ISSUE TITLE
Passing functions as arguments to functions

### ISSUE THREAD

**Issue by ThreadedStream** [vlang/v#9586]
Does vlang support passing functions as arguments to other functions? Likewise, does it support higher-order functions? I might be wrong, since I didn't do enough research to find an answer. But there was no any information on how to achieve this in docs, and I haven't found any related issues. If it really doesn't, it would be great to include this feature for the sake of flexibility. I guess there exists a heuristic for actually passing callbacks as voidptrs, and then use them in C functions.

**Comment by nedpals** [comment]
@ThreadedStream yes you can.
```v
fn execute_cb(input string, callback fn (input string) bool) {
    val := callback(input)
    println(val)
}

fn main() {
    execute_cb('test', fn (input string) bool {
        if input == 'test' {
            return true
        } else {
            return false
        }
    })
}
```

**Comment by ThreadedStream** [comment]
@nedpals, thank you very much. I should have done more research prior to posting it in issues.

**Comment by nedpals** [comment]
@ThreadedStream the docs have covered that: https://github.com/vlang/v/blob/master/doc/docs.md#anonymous--high-order-functions
