### ISSUE TITLE
Translation of V module into C file

### ISSUE THREAD

**Issue by nedimf** [vlang/v#9589]
**V version:** V 0.2.2 1a32467
**OS:**  macos, macOS, 11.1, 20C69

**What did you do?**
Run```v -o file.c file.v -shared vlib``` 
Check for occurrences of your module methods ```while read line;do echo "$line";done<file.c | grep vex ```
**What did you expect to see?**
```
f64 vex_absolute_value(f64 a); 
```
 
**What did you see instead?**
```
f64 __vex_absolute_value(f64 a);
```
Module code:
```v
module vex

import math 
import strings

pub fn vex_absolute_value(a f64) f64{
	return math.abs(a)
}
fn init(){
	println("Vex module has been called")
}

```

**Comment by spaceface777** [comment]
in the generated C, functions are named in the format `${module}__${fn_name}` (e.g. `math__log`) by design.

If you want to export them under a different name, you can use the `export` attribute:
```v
[export: 'SomeOtherName']
pub fn foo(a f64) f64{
	return math.abs(a)
}
```

**Comment by nedimf** [comment]
This is very helpful, thank you.
