### ISSUE TITLE
VLang does not compile using TCC under Alpine linux (Musl based)

### ISSUE THREAD

**Issue by axgdev** [vlang/v#9632]
**V version:** Revision 8caabf0e9ee53f43c6c76fde02f2cfc0f47f4f87 (latest commit in master)
**OS:** Alpine linux 3.13.4

**What did you do?**
Add needed packages to Alpine:

`apk add musl-dev make tcc libexecinfo-dev git`

Follow vlang documentation to build from source with a modification in the last step to build with TCC: https://github.com/vlang/v/blob/master/doc/docs.md#linux-macos-freebsd-etc

```
git clone https://github.com/vlang/v
cd v
CC=tcc VFLAGS="-cc tcc" LDFLAGS="-lexecinfo" make
```

**What did you expect to see?**
I expected it to compile
 
**What did you see instead?**
```
cd ./vc && git clean -xf && git pull --quiet
cd ./thirdparty/tcc && git clean -xf && git pull --quiet
tcc  -g -std=gnu99 -w -o ./v ./vc/v.c -lm -lpthread -lexecinfo
tcc: error: undefined symbol 'tcc_backtrace'
make: *** [Makefile:86: all] Error 1
```

**Comment by axgdev** [comment]
A bit of an update. I managed to run it doing the following:

1. Add -bt to compile flags: `CC=tcc VFLAGS="-cc tcc" LDFLAGS="-lexecinfo -bt" make`
2. Replace thirdparty/tcc/tcc.exe with the Alpine one: `cp /usr/local/bin/tcc thirdparty/tcc/tcc.exe`
3. It compiled!

By the looks of it, it seems tcc compilation was meant to work only for windows, hence the tcc.exe requirement?

**Comment by axgdev** [comment]
Second update it is possible to build the newest version of tcc using tcc, to remove the gcc dependency by doing:

1. `apk add tcc`
2. `git pull https://github.com/TinyCC/tinycc.git`
3. `cd tinycc`
4. `./configure --config-musl --cc=tcc`
5. `make`
6. `make test`
7. `apk del tcc`
8. `make install`

`apk add tcc`

**Comment by axgdev** [comment]
Update 3: The steps above to use only tcc do not work unfortunately, as the compiled tcc version for alpine is too old so make test do not pass. I do not know where to find compiled versions of tcc, so in the meantime I guess using gcc is the only way to get tcc compiled properly

**Comment by axgdev** [comment]
Ah now I understand why it says that tcc.exe could not be found, that happens because it was compiled for glibc instead of musl. That's why replacing tcc.exe with one compiled for alpine makes it work.

**Comment by medvednikov** [comment]
V runs fine on Alpine now (tested by CI)
