### ISSUE TITLE
unable to handle submodules

### ISSUE THREAD

**Issue by esquerbatua** [vlang/v#9639]
**OS:** linux, Ubuntu 20.04.2 LTS
**V version:** 𝗩 0.2.2 7c79e9b

**What did you do?**
Create an empty new project with a module and a submodule

**What did you expect to see?**
test init
subtest init
test
test.Module{
    a: 'a'
}
subtest.Module{
    a: 'a'
}
(**maybe not in that order**)
 
**What did you see instead?**
./main.v:4:1: builder error: bad module definition: ./v imports module "test.subtest" but ./test/subtest/subtest.v is defined as module `subtest`
    2 | 
    3 | import test
    4 | import test.subtest
      | ~~~~~~~~~~~~~~~~~~~
    5 | 
    6 | fn main() {

Project files:
[test.tar.gz](https://github.com/vlang/v/files/6277804/test.tar.gz)

**Comment by esquerbatua** [comment]
Solution purposed: https://github.com/vlang/v/pull/9640

**Comment by takkyuuplayer** [comment]
https://github.com/vlang/v/tree/master/examples/submodule example also doesn't work

```
$ cd example/submodule
$ v run main.v
main.v:1:1: builder error: bad module definition: v imports module "mymodules" but <REPO_DIR>/examples/submodule/mymodules/main_functions.v is defined as module `mymodule`
    1 | import mymodules { add_xy }
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 | import mymodules.submodule { sub_xy }
    3 |
```

**Comment by esquerbatua** [comment]
> https://github.com/vlang/v/tree/master/examples/submodule example also doesn't work
> 
> ```
> $ cd example/submodule
> $ v run main.v
> main.v:1:1: builder error: bad module definition: v imports module "mymodules" but <REPO_DIR>/examples/submodule/mymodules/main_functions.v is defined as module `mymodule`
>     1 | import mymodules { add_xy }
>       | ~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     2 | import mymodules.submodule { sub_xy }
>     3 |
> ```

Yes, I created the example to test it and show that it's not working.

**Comment by tehando** [comment]
Same for me, more feedback

- If you rename "mymodules" folder to "mymodule" and the following lines in main.v, submodule example works. 
```
 import mymodules { add_xy }
 import mymodules.submodule { sub_xy }
```
to
```
import mymodule { add_xy }
import mymodule.submodule { sub_xy }
```
- If you change  the module definition 'mymodule' to 'mymodules' in main_functions.v, v gives the following error
> v run main.v 
> main.v:2:30: error: module `mymodules.submodule` has no constant or function `sub_xy`
>     1 | import mymodules { add_xy }
>     2 | import mymodules.submodule { sub_xy }
>       |                              ~~~~~~
>     3 | 
>     4 | fn main() {
> main.v:6:10: error: unknown function: mymodules.submodule.sub_xy .
> 1 possibility: `mymodules.add_xy`.
>     4 | fn main() {
>     5 |     println(add_xy(2, 3)) // expected: 5
>     6 |     println(sub_xy(10, 7)) // expected: 3

**Comment by felipensp** [comment]
Any update on this report @esquerbatua ?

**Comment by esquerbatua** [comment]
> Any update on this report @esquerbatua ?

I close it, seem that now it's working
