### ISSUE TITLE
Error int vs i64 when calling gcf()

### ISSUE THREAD

**Issue by Niek** [vlang/v#965]
**V version:** latest git HEAD

Calling ``gcf()`` results in this error:

```
pass=2 fn=`gcf`
panic: fraction.v:86
expected type `int`, but got `i64`
```

This is because ``gcd()`` returns i64 and not int.

It was introduced in this commit: https://github.com/vlang/v/commit/ffb4da791d9b52f6bf60da3856535f224a6a8f5a

*Edit*: I see there is an open PR now with fixes: https://github.com/vlang/v/pull/966

**Comment by archanpatkar** [comment]
@Niek This issue is being tackled in #963, as mentioned in #960 it is adopting the fraction struct and methods(with name changes) to support i64

**Comment by medvednikov** [comment]
Fixed. `git pull && make`
