### ISSUE TITLE
Unknown method for generic types returned from function

### ISSUE THREAD

**Issue by mcastorina** [vlang/v#9659]
**V version:** V 0.2.2 bf6a2f8
**OS:** linux

**What did you do?**
```v
struct Iterator<T> {
	data []T
}

pub fn (mut i Iterator<T>) next<T>() ?T {
	return i.data[0]
}

pub fn iter<T>(data []T) Iterator<T> {
	return Iterator<T>{ data: data }
}

fn main() {
	// mut it := Iterator<int>{data: [1 2 3]}
	mut it := iter<int>([1 2 3])
	println(it.next())
}
```

**What did you expect to see?**
```
Option(1)
```
 
**What did you see instead?**
```
error: unknown method: `Iterator<int>.next`
```

**Addendum**
Initializing the `Iterator` struct directly works fine (see the commented line).

**Comment by mcastorina** [comment]
@yuyi98 you are awesome!

**Comment by yuyi98** [comment]
@mcastorina   Thanks! There are many other problems with generics.

**Comment by mcastorina** [comment]
I'm excited to see it come together.. once generics in interfaces is working I think I can rewrite my 60k line (generated) module :)
