### ISSUE TITLE
 error: invalid expression: unexpected token `+`

### ISSUE THREAD

**Issue by Dialga** [vlang/v#9660]
**V version:** Latest git
**OS:** Arch Linux x64

**What did you do?**
`println(+1)`

**What did you expect to see?**
1
 
**What did you see instead?**
```
Welcome to the V REPL (for help with V itself, type `exit`, then run `v help`).
V 0.2.2 bf6a2f8
Use Ctrl-C or `exit` to exit, or `help` to see other available commands
>>> println(+1)
.vrepl.v:7:9: error: invalid expression: unexpected token `+`
```

println(-1) is allowed but not +1? In C this is allowed.

**Comment by Delta456** [comment]
`+`1 isn't valid because it means the same as `1` which goes against one way philosophy. Read https://github.com/vlang/v/issues/6663 for more information.
