### ISSUE TITLE
Termux 0.108 fdroid no v output

### ISSUE THREAD

**Issue by treffner** [vlang/v#9662]
I removed all modules with this command.
rm -rf .vmodules/
I also ran all the other commands.

**V version:** 0.2.2 f0a67a481
**OS:** Android 10 Termux 0.108 from fdroid

**What did you do?**
v version

**What did you expect to see?**
Something like 0.2.2
 
**What did you see instead?**
No output from v. See attached screenshot.
![Screenshot_20210409-220411](https://user-images.githubusercontent.com/17121556/114263594-cb767d00-99e6-11eb-8de5-fb2c42dc73ee.png)

**Comment by treffner** [comment]
I found out that it works if I comment out 2 lines in the Makefile.

```
else
	$(CC) $(CFLAGS) -g -std=gnu99 -w -o $(V) $(VC)/$(VCFILE) -lm -lpthread $(LDFLAGS)
#	$(V) -o v2.exe cmd/v
#	mv -f v2.exe v  
endif
```

So it has something to do with v compiling itself. Also v self breaks it.

**Comment by jusger** [comment]
I can also confirm this similar behavior, though running an older phone with an old version of Android with most recent Termux.

Most recent pull will let you build with make now, but v still doesn't run an interactive session, just hangs with no prompts (can ctrl-c out). If building with clang directly, I can get an interactive session to semi-run, but I can enter maybe half a line of commands before text no longer appears in the prompt. Oddly, typing exit even without seeing the output will exit the program. So perhaps it's running just fine, but it's a termux issue?

Happy to investigate further if anyone needs additional info, I'm not sure what else to look at / what would be helpful.

**Comment by treffner** [comment]
This is now partly resolved.
Normal output works, but not error output. I will close this for now and look into fixing error output as well.
