### ISSUE TITLE
UI code out of date

### ISSUE THREAD

**Issue by gshields** [vlang/v#9671]
Tried to compile UI code, UI library is using old code syntax
Code use to compile but is now out of sync with compiler
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
gcc.exe (Rev2, Built by MSYS2 project) 9.3.0
V 0.2.2 78c6e35

Getting this 
error: cannot use `&u16` as `&char` in argument 2 to `C.MessageBox`

for these programs in UI
android_window.v
calculator.v
calculator_resizable.v
change_title.v
counter.v
dropdown.v
dropdown2.v
dynamic_layout.v
grid.v
group.v
group2.v
group2_resizable.v
message.v
rectangles.v
rectangles_resizable.v
resizable_window.v
rgb_color.v
rgb_color_sync.v
slider.v
slider_textbox.v
switch.v
temperature.v
timer.v
transitions.v
users.v
users_resizable.v

**Comment by nedpals** [comment]
This should submitted in https://github.com/vlang/ui instead.

**Comment by gshields** [comment]
Ok thanks
