### ISSUE TITLE
Consider contributing to josevalim/nested-data-structure-traversal

### ISSUE THREAD

**Issue by sthagen** [vlang/v#9675]
I searched for the term `nested` in the open issues and skimmed over existing contributions at [josevalim/nested-data-structure-traversal](https://github.com/josevalim/nested-data-structure-traversal) but did not find a v-lang example.

Would it make sense to contribute an approach in v for traversal of nested data structures?

I could give it a try, but first wanted to ask here where the source of v is ...

**Comment by dumblob** [comment]
Sounds useful :+1:

**Comment by sthagen** [comment]
So, I went ahead and spent my first hour with v and submitted josevalim/nested-data-structure-traversal#110

It really reminds me a lot of go ... and I hope some members of the V community can provide feedback and enhance
the presumably one way to go.

I do not expect that version to be "idiomatic v".

Thanks for reading and hoping for feedback,
Stefan

**Comment by sthagen** [comment]
I close this issue, as josevalim/nested-data-structure-traversal#110 has been merged after I received feedback from @nedpals to not have a too stupid beginner version for v among all these shiny solutions in other languages.

Thanks a lot for the support,
Stefan
