### ISSUE TITLE
Something with fixed arrays appears broken, V reports a compiler bug

### ISSUE THREAD

**Issue by gastrodon** [vlang/v#9690]
**V version:** 
**OS:** 
```
OS: linux, "Arch Linux"
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz
CC version: cc (GCC) 10.2.0

getwd: /storage/home/zero/Documents/programming/vemulator
vmodules: /home/zero/.vmodules
vroot: /usr/lib/vlang
vexe: /usr/lib/vlang/v
vexe mtime: 2021-04-12 00:34:59
is vroot writable: false
is vmodules writable: true
V full version: V 0.2.2 a2a18ef.67d8639

Git version: git version 2.31.1
Git vroot status: weekly.2021.14-47-g67d86399
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81-dirty

```

**What did you do?**

In the project's root, `v run .`

**What did you expect to see?**

A really pretty state of my emulator
 
**What did you see instead?**

```
--- v run .
==================
/tmp/v/vemulator.3629162394894766644.tmp.c:9232: error: character array initializer must be a literal, optionally enclosed in braces
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

The code in question is my project at [this commit], and has no C interop. (https://github.com/gastrodon/vemulator/tree/2309f77a28b467ea12061fffa11c580c4935af6d).
I don't know a ton about compilers / V / C, but if I had to guess what's going on it looks like
V is having trouble when I assign a variable to a fixed sized array in a struct

The code in question works with the following diff

```diff
diff --git a/main.v b/main.v
index 6527cea..5e23afb 100644
--- a/main.v
+++ b/main.v
@@ -45,17 +45,17 @@ fn (mut state State) load(rom []byte) ?u16 {
 }
 
 fn (mut state State) execute() {
-       rom := state.rom
+       // rom := state.rom
 
        mut pc := 0
        for pc != 0xffff {
-               match rom[pc] {
+               match state.rom[pc] {
                        // NOP
                        0x00, 0x08, 0x10, 0x18, 0x20, 0x28, 0x30, 0x38 {}
                        // LXI B d16
                        0x01 {
-                               state.b = rom[pc + 2]
-                               state.c = rom[pc + 1]
+                               state.b = state.rom[pc + 2]
+                               state.c = state.rom[pc + 1]
                                pc += 2
                        }
                        // STAX B
@@ -74,13 +74,13 @@ fn (mut state State) execute() {
                        }
                        // STA a16
                        0x32 {
-                               address := u16(rom[pc + 2]) << 8 | u16(rom[pc + 1])
+                               address := u16(state.rom[pc + 2]) << 8 | u16(state.rom[pc + 1])
                                state.ram[address] = byte(state.a)
                                pc += 2
                        }
                        // LDA a16
                        0x3a {
-                               state.a = state.ram[int(rom[pc + 2]) << 8 | int(rom[pc + 1])]
+                               state.a = state.ram[int(state.rom[pc + 2]) << 8 | int(state.rom[pc + 1])]
                                pc += 2
                        }
                        // INR A

```

**Comment by JalonSolov** [comment]
You should use `u16` in your `LDA a16` block as well, or you could end up with a negative address... which would definitely cause problems.

**Comment by gastrodon** [comment]
`state.rom[<address>]` is always a byte since `state.rom = [0xffff]byte`, so overflowing an int _should_ be impossible. While I appreciate the advice, I don't know that it's quite relevant to this issue.

**Comment by JalonSolov** [comment]
Whether that's a problem or not, the issue with compiling is what it says in the error message:
```
error: character array initializer must be a literal, optionally enclosed in braces
```
and that is being caused by the code in your `load` function.

**Comment by gastrodon** [comment]
I don't really see how `load` is causing that error, especially since the compiler states that this should never happen.
If that were the case, wouldn't I just get a compilation error?

It references `state.rom`, which is in this struct

```v
struct State {
mut:
	ram [255]byte
	rom [65535]byte
...
}
```

That array is written to in another function
```v
fn (mut state State) load(rom []byte) ?u16 {
	if rom.len > 0xFFFF {
		println('ROM must be indexable by u16')
		return none
	}

	mut index := u16(0)
	mut buffer := [0xffff]byte{}
	for code in rom {
		buffer[index] = code
		index++
	}

	state.rom = buffer
	return index
}
```

**Comment by JalonSolov** [comment]
If you check the C output and look for the line number reported, it is basically the last thing that happens before the `return index` in your `load` function.

**Comment by gastrodon** [comment]
Yes, I see that this is a bug in the generated c. Though as far as I'm concerned with, the v code that I wrote should be valid.

**Comment by splace** [comment]
so fixed length arrays are just broken.

this bug report was helpful...

since it was the only way to find out why all my code was producing this meaningless error message.

**Comment by JalonSolov** [comment]
They are not broken.  Fixed arrays are allocated on the stack, which means you _cannot_ reliably use them outside the scope of the current function.  They will be overwritten on the next function call after the current one returns.

If you want something usable outside the current function, you need to get an array allocated on the heap.

**Comment by splace** [comment]
thanks,

duh, i remember reading that now.

i have a modelling scenario that is fixed for an invocation, that is, same length for a very large amount of computation, i thought using fixed length would probably be optimal, range checked at compile time? but haven't been able to test, i guess i could now.

might it be worth chunking a slice into many fixed length arrays, was thinking of doing this anyway for multi-threading.

**Comment by JalonSolov** [comment]
There has been talk about automatically cloning fixed arrays to heap if they're returned from a function, but there are problems with that... everything from getting it done correctly, to the unexpected performance hit ("Why did my code slow down, and take more memory, just from returning an array?").

**Comment by splace** [comment]
i can see the advantages of doing it this way, fixed length are mostly going to be small. i'm only doing this for optimisation, but then large arrays are going to be the first place you do optimisation.

but since the compiler knows when this happens (extra-fn use), could it just substitute a slice throughout all the time, just making it look like a fixed array, so no cloning stutter. the chunking optimisation maybe should be explicit/in a library.

i can test performance, now i get-it.

**Comment by dumblob** [comment]
@splace maybe this is the moment when one would turn to `unsafe{}` and constructed a safe API wrapping such `unsafe{}` use?

**Comment by medvednikov** [comment]
Fixed.
