### ISSUE TITLE
Different log format on console and in file ( v/vlib/log/log.v )

### ISSUE THREAD

**Issue by duselguy** [vlang/v#9692]
**V version:** 
V 0.2.2 205fb88

**OS:** 
OS: linux, Ubuntu 20.04.2 LTS

**What did you do?**
Check logging into console. Check logging into file. 

**What did you expect to see?**
The output in the same format.
 
**What did you see instead?**
Console (with colored INFO, WARN, etc.):
[INFO  2021-04-12 04:07:49] info
[WARN  2021-04-12 04:07:49] warn
[ERROR 2021-04-12 04:07:49] error
File:
2021-04-12 03:11:31 [INFO ] info
2021-04-12 03:11:31 [WARN ] warn
2021-04-12 03:11:31 [ERROR] error

The **same** format (as in file, colors as an option) is preferable in both cases.

**Comment by JalonSolov** [comment]
Agreed.  date/time should always be first.
