### ISSUE TITLE
Allow vweb to handle uppercase in URL

### ISSUE THREAD

**Issue by fnetX** [vlang/v#9694]
Vweb currently does not appear to support upper case letters in the URL (at least they do not appear if for example matched via
~~~
['/request/:key']
pub fn (mut app App) request(key string) vweb.Result {
    return app.text(key)
}
~~~
(key will always be lowercase)). This is likely due to https://github.com/vlang/v/blob/master/vlib/vweb/vweb.v#L358 or line 500 (only had a quick glimpse, but it's apparently on purpose to make the request lowercase).

This is usually fine, but breaks use cases that rely on upper case requests for some reason - e. g. user provided file names or probably the most common: base64 and similar encoding.

It'd be nice if you could pass the request as-is to the app.
Thank you.

**Comment by Dialga** [comment]
Can this be closed if it is fixed?
