### ISSUE TITLE
V forum is live

### ISSUE THREAD

**Issue by medvednikov** [vlang/v#97]
https://forum.vlang.io

Initially I was going to set up a Discourse instance, but it turned out to be way too bloated for my liking. 

This simple forum/blog software is written in V and will be open sourced after the language is.

It's very minimalistic, but it gets the job done. There's not a single line of JavaScript :)

**Comment by wangyghy** [comment]
There's not a single line of JavaScript :)

I like it

**Comment by medvednikov** [comment]
The entire web app is a single 65 KB binary file, so deployments and maintenance are going to be pretty easy.

<img width="311" src="https://user-images.githubusercontent.com/687996/55998309-0b9eaa00-5cbe-11e9-9752-c644b7893470.png">

**Comment by stefanos82** [comment]
I think it would be more than handy for us curious to get a read-only access to the language so we can take an idea how the language is implemented and report possible bugs and typos via ticketing.

Just a humble thought, nothing more.

I really need to get my hands dirty using it :laughing:

**Comment by mindplay-dk** [comment]
I'm really curious what a web app in V looks like. Would you consider posting the forum source so we can take a look? :-)

**Comment by stefanos82** [comment]
By the way, I have browsed the documentation and haven't seen anywhere anything about exceptions.

Is it an undocumented mechanism or it's something that happens behind the scenes in a "magical" way?

**Comment by medvednikov** [comment]
@mindplay-dk I planned to release the source in June, but I came to the same same conclusion as you: it would be really nice to have an example of a web app. So I'll release it next week after I implement templates. Right now there are no templates and the code is really ugly, Perl CGI style.

> Also, curious, what did you use for persistence and how do you connect to that?
Postgresql/libpq.

> By the way, I have browsed the documentation and haven't seen anywhere anything about exceptions.
There are no exceptions. Only Go-like panics.

**Comment by stefanos82** [comment]
I hope we don't see any `if err != nil` with V, much like we see in Golang lol!

**Comment by medvednikov** [comment]
> I hope we don't see any if err != nil with V, much like we see in Golang lol!

https://vlang.io/compare
https://vlang.io/docs#option

Option types are used for error handling. There's no `nil` in V.

**Comment by stefanos82** [comment]
Mind...BLOWING! :boom: 

Can we get it already?!

Seriously now @medvednikov we really **really** need to use it, like...yesterday!

**Comment by ansarizafar** [comment]
@medvednikov  I wish for a [Svelte/Sapper V3](https://svelte.dev/) like framework for building isomorphic web apps with V + web assembly. Someone is already working on a Rust version of Svelte V3.

Rust also has few other fameworks for building isomorphic/client web apps
https://github.com/chinedufn/percy
https://github.com/DenisKolodin/yew

**Comment by ntrel** [comment]
> So I'll release it next week after I implement templates

Great news! It would also be good to open source the standard library IMO even before the compiler is released.

**Comment by stefanos82** [comment]
@medvednikov Is there a particular reason you are not closing body and html tags in forum HTML code?

**Comment by medvednikov** [comment]
> Is there a particular reason you are not closing body and html tags in forum HTML code?

 I implemented header.html, but not footer.html. Will fix.

**Comment by stefanos82** [comment]
Cool :+1:

**Comment by ondra117** [comment]
is there a way to create in V a function which returns C void pointer ???

and is there a possibility to create in V function what has input argument as C void pointer ???

**Comment by JalonSolov** [comment]
Your questions have nothing to do with this issue.  Please open a new issue if these don't tell you what you want to know:

https://github.com/vlang/v/blob/master/doc/docs.md#calling-c-from-v
https://github.com/vlang/v/blob/master/doc/docs.md#calling-v-from-c
