### ISSUE TITLE
enumerate built-in

### ISSUE THREAD

**Issue by highfestiva** [vlang/v#9707]
I'm sure everybody and their pet wants a particular language feature. I love the premise of V, but also think that the language would be better with this feature, without adding much overhead either in the learning curve or the implementation. These are the benefits of [enumerate](https://docs.python.org/3/library/functions.html#enumerate):

- The loop syntax would be the same as for a maps: `for i, v in enumerate(l) {}`
- Behind the scenes, an ordered map implementation could be used at first (if deemed easier).
- More concise than declaring `mut i := 0` and then adding `i++` at the end of each loop.
- Since the counter variable would be scoped to the loop, it reduces the risk/temptation of reusing it several times (as I do in my code linked below).
- Less error prone inside the loop, as well as further down in the same function.
- When accustomed to it, the conciseness brings clarity to the intent of the loop.
- This built-in would add a slight complexity to the language, while making all the source code that's ever going to be written in V slightly better. The leverage is worth it (if done right).
- People from the Python community would be right at home. V should cater a little for those people imho, as a large group eventually (like me) get fed up with 2 magnitudes worse performance than anything else, lack of UI, knarly C extensions and missing compile-time checks. I for one would've felt more at home if enumerate was at hand.

I asked about it in [codereview](https://codereview.stackexchange.com/questions/259283/convert-a-matrix-dataframe-to-printable-string), but V is still to small to attract any thinkers on the topic. This real-world matrix example gives a hint of exactly how much overhead is added and readability is subtracted without `enumerate()`. Thanks for considering it!

**Comment by Gladear** [comment]
It is already possible to do this without `enumerate`, as [stated in the documentation](https://github.com/vlang/v/blob/master/doc/docs.md#array-for)
```v
for index, value in array {
    // ...
}
```
Does it fulfill your need ?

**Comment by highfestiva** [comment]
@Gladear Absolutely, thanks! If I were to start construction of a python->v intoduction guide, do you think that could be accepted into the repository? (The documentation is good, but things such as this are easy to glance over. For many pythonistas it would probably be better with a few bullet points such as "1. enumerate=..., 2. list comprehension=..., 3. lambdas=..." and so forth, at least that's the case for me.)

**Comment by Gladear** [comment]
I'm not sure the main repository is the right place for this. However, you can take a look in the [v-community](https://github.com/v-community) organization. Maybe in *learn_v_in_y_minutes* or *vschool*, I'm not entirely sure.

Where do you guys think is the right place for that ? @nedpals @Delta456

**Comment by JalonSolov** [comment]
We do need a common place for things like this, as well as tutorials, etc.

@medvednikov did you have anything in mind?

**Comment by highfestiva** [comment]
@Gladear Sounds like exactly the right place to me. Or at least if you allow links from the main repo?

**Comment by Gladear** [comment]
It's only my opinion, but I guess we could have a `v_for_y_developers` regrouping ressources to learn V coming from different languages, and link to it in the documentation

**Comment by highfestiva** [comment]
I'll start to take notes and commit+push when I have learned a little. Thanks!

**Comment by nedpals** [comment]
> We do need a common place for things like this, as well as tutorials, etc.
> 
> @ medvednikov did you have anything in mind?

TBH thats what the [V Community](https://github.com/v-community) org was created at the first place. Their tutorials and other resources just need to be updated for the latest version.
