### ISSUE TITLE
`vfmt`  mistaking variables for imports

### ISSUE THREAD

**Issue by abughurab16** [vlang/v#9713]
Variables named after modules confuse vfmt and lead it to automatically import that module despite it not being in use.

e.g
```v
strings := "hello"
```
If you format this with `vfmt` it automatically imports strings!

**v info**
version: `V 0.2.2 8c95f07`
OS: `Windows 64bit`

**Comment by mcastorina** [comment]
Good find! It looks like the variable also needs to be accessed for `v fmt` to import the module. The method doesn't need to exist either.

```v
strings := 'hello'
strings.any_method()
```

formats to

```
import strings

strings := 'hello'
strings.any_method()
```

**Comment by AxiomApollo** [comment]
oh i see that can cause some unwanted bugs if unaware lol

**Comment by serkonda7** [comment]
Yeah, auto imports are quite unusable right now and require lot's of work to get in better shape.

**Comment by JalonSolov** [comment]
`v fmt` has no problem with this now.  Running it on your example just produces
```v
strings := 'hello'
```
where it changed the double quotes to singles per V convention.

**Comment by serkonda7** [comment]
@JalonSolov also with this code?
```v
strings := 'hello'
strings.any_method()
```

**Comment by JalonSolov** [comment]
Adding the line with the method call adds the `import strings` at the top.
