### ISSUE TITLE
V should warn about `sorting structs without specifying  a field`

### ISSUE THREAD

**Issue by abughurab16** [vlang/v#9717]
OS: `Windows 64 bit`
V-Version: `V 0.2.2 8c95f07`

e.g
```v
structArray.sort()
```
If the struct exists and you try to run this it will lead to a C error being raised and the program crashes.

Instead V should give a warning/error message that you are trying to sort a struct without specifying a struct field.

**Comment by JalonSolov** [comment]
Fixed by commit ea3983a91b56ce3bc888cd84931756df6c3061b2 - please do `v up` to get the latest.
