### ISSUE TITLE
`is` keyword doesn't raise error when type is not used.

### ISSUE THREAD

**Issue by AxiomApollo** [vlang/v#9723]
OS: windows, Microsoft Windows  64-bit
V full version: V 0.2.2 2b41556.8c95f07

Expected V to issue when a type is not followed after the `is` keyword but rather the compiler crashed the program
testing it :
```v
fn main() {
	x := 5
	if x is 5 {
		println('jojo!!')
	}
}

**Comment by medvednikov** [comment]
Good find! :)

**Comment by AxiomApollo** [comment]
> Good find! :)

thank you 😅
