### ISSUE TITLE
error: Can't use [attribute] next to initialized property in struct

### ISSUE THREAD

**Issue by kjlaw89** [vlang/v#9727]
**V version: V 0.2.2 711e309** 
**OS: Windows 10 64-bit** 

**What did you do?**
Added a `[json: field]` attribute next to a property in a struct that had a default value:

```v
module main

struct Test {
	id int = 1 [json: test]
}

fn main() {

}
```

**What did you expect to see?**
Successful compile
 
**What did you see instead?**
```
$ v run test.v
test.v:4:18: error: unexpected token `:`, expecting `]`
    2 |
    3 | struct Test {
    4 |     id int = 1 [json: test]
      |                     ^
    5 | }
    6 |
```

Similar/potentially the same issue as: https://github.com/vlang/v/issues/9726

**Comment by nedpals** [comment]
Same with #9726:
```
struct Test {
	id int [json: test] = 1
}
```
They are essentially the same errors, so this should be marked as duplicate and focus on the other one instead.
