### ISSUE TITLE
Generics with interfaces

### ISSUE THREAD

**Issue by charles-cooper** [vlang/v#9735]
It would be nice to be able to add type parameters to interfaces. This would allow writing generic code without knowing too much in advance about what might be inside containers. For instance,
```v
interface Gettable<T> {
  get() T
}

struct Animal<T> {
  metadata T
}

fn (a Animal) get<T>() T {
  return a.metadata
}

fn extract([]Gettable<T> xs) []T {
  return xs.map(it.get())
}
```

**Comment by dumblob** [comment]
IMHO this is basically the last thing to do to become as expressive as (Rust|Ante|...) *Traits* (but with less syntax and with less convoluted "mind concept").

**Comment by mcastorina** [comment]
@yuyi98 any ETA on this feature? No rush, I'm just excited :)

**Comment by yuyi98** [comment]
@mcastorina  Thanks! I'm just solving problems with the functionality that generics have already implemented, generics are currently not fully implemented for handling anonymous functions, so it is impossible to estimate the approximate implementation time. I'll study hard for it.

**Comment by charles-cooper** [comment]
@yuyi98 can I help with this one?

**Comment by yuyi98** [comment]
@charles-cooper   Thanks!  I'll try.

**Comment by odunboye** [comment]
@yuyi98, any delivery timeline for this? Thanks

**Comment by yuyi98** [comment]
I'm really sorry that I haven't done much research on interface, and I'm working on it.
It is not clear whether the development team has adopted this approach, and I'll try to implement it firstly.

**Comment by yuyi98** [comment]
@charles-cooper  Please give a complete short example.

**Comment by charles-cooper** [comment]
@yuyi98  I provided a brief example in the issue description -- is there something more specific you wanted to see?
