### ISSUE TITLE
Vweb "error parsing request: none" appears after running

### ISSUE THREAD

**Issue by williamclavier** [vlang/v#9740]
**V version:** ```V 0.2.2 3387058.a18f85c```
**OS:** ```windows, Microsoft Windows 10 Home v19042 64-bit```
**Browser:** ```Brave v 1.22.71```

**What did you do?**
I was following along with the [Vweb tutorial](https://github.com/vlang/v/blob/master/tutorials/building_a_simple_web_blog_with_vweb/README.md) when I noticed the weird error.
```v
module main

import vweb

struct App {
	vweb.Context
}

fn main() {
	vweb.run<App>(8081)
}

pub fn (mut app App) index() vweb.Result {
	return app.text('Hello world from vweb!')
}
```

**What did you expect to see?**
I was just expecting the console to stay blank as nothing wrong should've happened.
 
**What did you see instead?**
```cmd
> v run blog.v
[Vweb] Running app on http://localhost:8081
error parsing request: none
```

**Comment by medvednikov** [comment]
Strange, must be a windows issue. Just tried this and it works fine. We need to add vweb examples to windows ci.

**Comment by mcastorina** [comment]
@medvednikov this happens on Linux too (in chromium). I think it's from chromium opening TCP connections before sending requests, causing a read timeout after 30s.

**Comment by LouisSchmieder** [comment]
yeah it's a known problem and it was the reason why I've made vweb async. Chromium based browsers open two TPC connections where only one sends data and the other one is for verification that the connection is secure

**Comment by mcastorina** [comment]
Ah I see. I made vweb synchronous to prevent race conditions / crashing under load 😆 

Looks like a catch 22. The [vweb refactor](https://github.com/vlang/v/issues/9081) should solve this.

**Comment by mcastorina** [comment]
vweb no longer complains about `error parsing request: none`
