### ISSUE TITLE
v self fails on directories outside of git clone directory

### ISSUE THREAD

**Issue by VinWare** [vlang/v#9767]
**V version:**  V 0.2.2 524becd
**OS:**  windows, Microsoft Windows 10 Home Single Language v19042 64-bit

**What did you do?**
Ran `v self` on a directory outside of the git repository directory. For example, if installed in `C:\Users\lapto\Downloads\v`, I ran `v self` in `C:\Users\lapto`

**What did you expect to see?**
```
V self compiling ...
V built successfully!
```
 
**What did you see instead?**
```
V self compiling ...
================ V panic ================
   module: main
 function: backup_old_version_and_rename_newer()
  message: failed to copy C:\Users\lapto\Downloads\v\v2.exe to C:\Users\lapto\Downloads\v\v.exe
     file: C:/Users/lapto/Downloads/v/cmd/tools/vself.v:81
   v hash: 524becd
=========================================
C:/Users/lapto/AppData/Local/Temp/v/../../../../../..C:\Users\lapto\Downloads\v\vlib\builtin\builtin.c.v:47: at panic_debug: Backtrace
C:/Users/lapto/AppData/Local/Temp/v/../../../../../..C:\Users\lapto\Downloads\v\cmd\tools\vself.v:81: by main__backup_old_version_and_rename_newer
C:/Users/lapto/AppData/Local/Temp/v/../../../../../..C:\Users\lapto\Downloads\v\cmd\tools\vself.v:30: by main__main
C:/Users/lapto/AppData/Local/Temp/v/../../../../../..C:\Users\lapto\AppData\Local\Temp\v\vself.12837453224974323000.tmp.c:17097: by wmain
0047a9e8 : by ???
0047ab4b : by ???
7ff9d7fd7034 : by ???
```

**Comment by bstnbuck** [comment]
I cannot reproduce this error. Tested it on 2 Windows devices and one Ubuntu machine with MSVC, TCC and GCC. 
I recommend to switch to the V directory and run `make` or reinstall V by new. Then test it again.

**Comment by VinWare** [comment]
Unfortunately running `make` again does not help. If anyone can reproduce this please suggest a fix. I will try to debug as well

**Comment by VinWare** [comment]
Closing because it is not reproducing anymore. Not clear how it is fixed.
