### ISSUE TITLE
Can't have an Interface struct field

### ISSUE THREAD

**Issue by Viza74** [vlang/v#979]
**V version:** 
0.1.12
**OS:** 
macos
**What did you do?**
```
module gfrm

struct FSM {
	currState FSMStater
}

interface FSMStater {
	enter()
	update()
	exit()
}
```

**What did you expect to see?**
compile without error
 
**What did you see instead?**
```
/Users/viza//.vlang//breakout.c:129:17: error: field has incomplete type 'gfrm__FSMStater' (aka 'struct gfrm__FSMStater')
gfrm__FSMStater currState;
                ^
/Users/viza//.vlang//breakout.c:86:16: note: forward declaration of 'struct gfrm__FSMStater'
typedef struct gfrm__FSMStater gfrm__FSMStater;
```

It compiles if I change the declarations to this:
```
module gfrm

interface FSMStater {
	enter()
	update()
	exit()
}

struct FSM {
	currState FSMStater
}
```

I don't know if this is the intended working, or not, but feels like a bug to me since all other things (like functions) can be used before their declaration.

**Comment by spacesinmotion** [comment]
that is not only an issue for interfaces:

the same for:
```go
module gfrm

struct FSM {
  currState FSMStater
}

struct FSMStater {
}
```
I think currently the dependencies of `structs`, `union` or `interfaces` are not handled at all

**Comment by M4SSD35TRUCT10N** [comment]
This is taken from the actual docs and it works fine. You can copy the code directly to `interfaces.v` and give it a shot (even when put `fn perform(s Speaker){...}` ahead of `interface Speaker`).

@medvednikov: **IMHO** this issue can be closed.

> **Interfaces**
> ```
> struct Dog {}
> struct Cat {}
> 
> fn (d Dog) speak() string {
> 	return 'woof'
> }
> 
> fn (c Cat) speak() string {
> 	return 'meow' 
> }
> 
> interface Speaker {
> 	speak() string
> }
> 
> fn perform(s Speaker) {
> 	println(s.speak())
> }
> 
> dog := Dog{}
> cat := Cat{}
> perform(dog) // "woof" 
> perform(cat) // "meow"
> ```
> A type implements an interface by implementing its methods. There is no explicit declaration of intent, no "implements" keyword.

**Comment by medvednikov** [comment]
@M4SSD35TRUCT10N indeed the order bug was fixed, but this is a different issue. We can't have an interface field. I'll update the title.

This code still doesn't compile:

```
module main

interface FsmStater {
        enter()
        update()
        exit()
}

struct FSM {
        curr_state FsmStater
}

fn main() {
}

```

**Comment by medvednikov** [comment]
Fixed.
