### ISSUE TITLE
Can't use name 'array' for an array

### ISSUE THREAD

**Issue by fl0under** [vlang/v#98]
Hi,

In the playground the following code got this error message:
test.v:4
expected `{`, but got `)`

```
fn main() {
	array := [1, 2, 3]
	println(array)
}
```

although using any other variable name will compile correctly and print. I can't see anything in the documentation that says 'array' is a reserved keyword/type or something like that.

And by the way I really like the direction this language is going in, keep it up!

**Comment by mindplay-dk** [comment]
> I can't see anything in the documentation that says 'array' is a reserved keyword/type or something like that.

It probably should be though?

Allowing function/var-names like `array`, `for`, etc. is a pretty bad idea.

The error message could be improved though.

**Comment by MaxGraey** [comment]
@mindplay-dk why? According to docs `array` even not reserved keyword.

**Comment by medvednikov** [comment]
While this is indeed a bad name for a variable, `array` is not a keyword, so it should be allowed.

Will fix, thanks.

**Comment by medvednikov** [comment]
Fixed.
