### ISSUE TITLE
C generated code does not compile with MSVC

### ISSUE THREAD

**Issue by vitalyster** [vlang/v#980]
**V version: 0.1.12** 
**OS: Windows** 

**What did you do?**

I did successfully fix build errors of [generated C code](https://github.com/vlang/vc/pull/3) by hand and stuck on moving these fixes to V. You can check my [WIP branch there](https://github.com/vitalyster/v/commits/msvc)
1. MSVC does not accept empty array initializers, I did replace `{}` with `{ 0 }` and looks like it works correctly both in C and V code.
2.  MSVC does not accept pointer arithmetic on `void *` `data` field of `array`. I tried to replace `voidptr` with `byteptr` in V code but got:
`operator + not defined on "byteptr"`

**What did you expect to see?**

Correct pointer arithmetic in C generated code, or another way to correctly generate `array` functions
 
**What did you see instead?**

`"void *" is unknown size` or something like this

**Comment by medvednikov** [comment]
I've added instructions:

https://github.com/vlang/v/wiki/Installing-V-from-source-on-Windows

For now you have to install Clang (130 MB) on top of Visual Studio.

The Microsoft C compiler is too behind.

**Comment by vitalyster** [comment]
I understand how to use gcc/clang, I'm working on msvc support

**Comment by medvednikov** [comment]
Ok, reopened. If we somehow manage to make it work with Microsoft C, that would be great.

**Comment by vitalyster** [comment]
solved issue with `byteptr data` and casting to `byte(...)` each C.mem* call, now it generates correct code
