### ISSUE TITLE
cstring_to_vstring should avoid copying

### ISSUE THREAD

**Issue by nordlow** [vlang/v#9802]
If vlang.io is keen on minimizing allocations it should enable an overload of

`fn cstring_to_vstring(cstr &char) string`

that just returns a slice of the `cstr` characters iff they are immutable.

Alternatively V could D's concept of `inout` qualified parameters and return value. A parameter qualifier `inout` is a wildcard that matches and forwards mutability from one or more function parameters to the corresponding function return value without requiring the function to be a template as the function implementation is potentially the same for all combinations of parameter mutability.

For reference the D implementation of `std.string.fromStringz` is currently

```d
inout(Char)[] fromStringz(Char)(return scope inout(Char)* cString) @nogc @system pure nothrow
if (isSomeChar!Char)
{
    import core.stdc.stddef : wchar_t;

    static if (is(immutable Char == immutable char))
        import core.stdc.string : cstrlen = strlen;
    else static if (is(immutable Char == immutable wchar_t))
        import core.stdc.wchar_ : cstrlen = wcslen;
    else
        static size_t cstrlen(scope const Char* s)
        {
            const(Char)* p = s;
            while (*p)
                ++p;
            return p - s;
        }

    return cString ? cString[0 .. cstrlen(cString)] : null;
}
```

No allocation is needed when forwarding of mutability is possible.

**Comment by JalonSolov** [comment]
https://modules.vlang.io/#tos
