### ISSUE TITLE
Can somebody give me an example about file operation?

### ISSUE THREAD

**Issue by kingofoz** [vlang/v#981]
Open and write a file, for example.

**Comment by 0x9ef** [comment]
Ref - https://github.com/vlang/v/blob/master/vlib/os/os.v .

```
file := open('mypath') or {
    // optional type, handle error
}
file.write('hello V')
file.close() // always close file descriptor
```

```
lines := read_lines('mypath') // returned []string with lines (null terminated strings)
for line in lines { 
    println(line) 
} 
```

**Comment by 0x9ef** [comment]
Before asking a question, see the source code for the implementation.

**Comment by kingofoz** [comment]
I see. open() can not be recognized. 'import os' is not helpful.

**Comment by kingofoz** [comment]
f := os.open('./test.txt') or {
     return
}
for {
    f.write('hello V')
}
f.close()

Please see the code. The error message is:
pass=2 fn=`main`
panic: test.v:5
`main` needs to return ``

What should I do?

**Comment by ntrel** [comment]
Maybe try putting `println(err)` before the return line?

**Comment by vertical222** [comment]
The issue is I've tested I could only write once successfully, subsequently run will always return error.

**Comment by yep84** [comment]
import os

fn main() {
    filename := './file.txt'

    read_hello := os.read_file(filename) or {
        panic('error reading file $filename')
        return
    }
    println(read_hello)
}

**Comment by changrui** [comment]
I tested Mr. 0x9ef program, os.open(), read_lines  are OK, but write has no effect.

**Comment by varuzam** [comment]
Does anyone know how to read a file line by line?

**Comment by 0x9ef** [comment]
@varuzam `pub fn read_lines(path string) []string `

See my example above ^.

**Comment by varuzam** [comment]
In the example  entire file is put in memory. It is inefficient.

**Comment by 0x9ef** [comment]
@varuzam At the moment there is no other option in the standard library. You can write own implementation on reading file chunks, or reading file by scanner with line limitation.

**Comment by nevrome** [comment]
@0x9ef Shouldn't your write example use `os.create`?

```
file := os.create('mypath') or {
    // optional type, handle error
}
file.write('hello V')
file.close() // always close file descriptor
```

**Comment by Octalbyte** [comment]
How can you delete a file?

**Comment by Fadis-Fairushin** [comment]
> Как можно удалить файл?

Разобрался? Если да. То подскажи

**Comment by KrasNIX** [comment]
> > Как можно удалить файл?
> 
> Разобрался? Если да. То подскажи

`os.rm(path string) !`

rm removes file in path.
