### ISSUE TITLE
A couple of issues using generics

### ISSUE THREAD

**Issue by ratcashdev** [vlang/v#9811]
**V version:**  V 0.2.2 ded3ce5.4a1f75c
**OS:** "Manjaro Linux"

**What did you do?**
the following snippets cause compilation errors on C level.

1. 
```
struct Queue<T>{
    buffer []T
}

fn (q Queue<T>) poll() T {
    return q.buffer[0]
}
```

2. 
```
struct Queue<T>{
    buffer []T
}

fn new_queue<T>() &Queue<T> {
    q := Queue<T>{
        buffer: []T{cap: 1024}
    }
    return &q
}

fn main() {
    mut q := new_queue<i64>()
}
```

3. just calling new_queue without type info
```
fn main() {
    mut q := new_queue()
}
```

lastly, for 
```
    mut q := new_queue<i64>()
    q.add(i64(3))
```
i am getting the "cannot use `i64` as `T` in argument 1 to `Queue<i64>.add`" message.

**Comment by yuyi98** [comment]
1. we should add <T> after method.
```vlang
struct Queue<T>{
    buffer []T
}

fn (q Queue<T>) poll<T>() T {
    return q.buffer[0]
}
```

**Comment by yuyi98** [comment]
2. Suggest that don't return &Queue<T> and return Queue<T>.
```vlang
struct Queue<T>{
    buffer []T
}

fn new_queue<T>() Queue<T> {
    q := Queue<T>{
        buffer: []T{cap: 1024}
    }
    return q
}

fn main() {
    mut q := new_queue<i64>()
    println(q)
}

D:\Test\v\tt1>v run .
Queue<i64>{
    buffer: []
}
```

**Comment by yuyi98** [comment]
3. new_queue() have no arg, so we can not infer concrete types info.

**Comment by ratcashdev** [comment]
2. Yes, that's working, but in some use cases not desirable as we're returning an object created on the stack. For performance reasons sometimes we want to create the struct on the heap and return a reference.

**Comment by yuyi98** [comment]
Fixed, 1, 2, 3 are ok.

```vlang
struct Queue<T> {
	buffer []T
}

fn new_queue<T>() &Queue<T> {
	q := Queue{
		buffer: []T{cap: 1024}
	}
	return &q
}

fn main() {
	mut q := new_queue<i64>()
	println(q)
}

PS D:\Test\v\tt1> v run .
&Queue<i64>{
    buffer: []
}
```
