### ISSUE TITLE
Abysmal performance from vweb webserver

### ISSUE THREAD

**Issue by jonatino** [vlang/v#9812]
**V version:** V 0.2.2 4a1f75c, timestamp: 2021-04-19 21:56:39 +0300
**OS:** PopOS 20.10

**What did you do?**
Created basic web server and benchmarked it using `wrk`

**What did you expect to see?**
Good performance.
 
**What did you see instead?**
Really bad performance. Performed 15x worse than Kotlin on the JVM, and 25x worse than Rust/Go

Sample server:
```v
module main

import vweb

const (
	port = 3000
)

struct App {
	vweb.Context
mut:
	cnt int
}

fn main() {
	println('vweb example')
	vweb.run<App>(port)
}

pub fn (mut app App) index() vweb.Result {
	return app.text('HELLO WORLD')
}
```

Bench (200 connections across 16 threads 10 second test): `wrk -c 200 -t 16 -d 10s http://localhost:3000` 
i9-9900k 4.9ghz

Results:

```
rust (4mb memory --release):
user@pop-os:~$ wrk -c 200 -t 16 -d 10s http://localhost:3000
Running 10s test @ http://localhost:3000
  16 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   290.94us  266.30us  14.97ms   91.62%
    Req/Sec    44.45k     3.98k   71.47k    70.73%
  7116536 requests in 10.10s, 572.36MB read
Requests/sec: 704646.11
Transfer/sec:     56.67MB

GO (13.6mb memory):
user@pop-os:~$ wrk -c 200 -t 16 -d 10s http://localhost:3000
Running 10s test @ http://localhost:3000
  16 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   620.34us  777.05us  17.62ms   84.39%
    Req/Sec    31.10k     4.26k   44.91k    68.06%
  4962794 requests in 10.03s, 672.07MB read
Requests/sec: 494826.49
Transfer/sec:     67.01MB

Kotlin (760mb memory):
user@pop-os:~$ wrk -c 200 -t 16 -d 10s http://localhost:3000
Running 10s test @ http://localhost:3000
  16 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.34ms    2.88ms  64.17ms   91.84%
    Req/Sec    25.31k     9.42k   47.07k    73.12%
  4034124 requests in 10.03s, 403.96MB read
Requests/sec: 402312.28
Transfer/sec:     40.29MB

Vlang (1.7gb memory):
user@pop-os:~$ wrk -c 200 -t 16 -d 10s http://localhost:3000
Running 10s test @ http://localhost:3000
  16 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    47.05ms  137.82ms   1.70s    90.67%
    Req/Sec     2.11k     0.86k    3.67k    69.55%
  281638 requests in 10.10s, 29.28MB read
  Socket errors: connect 0, read 0, write 0, timeout 6
Requests/sec:  27882.91
Transfer/sec:      2.90MB
```

**Comment by mcastorina** [comment]
Hi, thanks for the detailed report!

vweb is under development and is not production ready. It is currently single threaded which explains the poor performance. We are in discussions about how it should be designed for safe concurrent access to application state while being multi-threaded and easy to develop. If you have ideas or suggestions, feel free to contribute to the discussion here: https://github.com/vlang/v/issues/9081

**Comment by Jonatino** [comment]
@mcastorina that explains the throughput thanks. Also I’m not sure if there is an issue to track the runaway ram usesge as well. It’s magnitudes higher than it needs to be. 425x higher ram usage than Rust

**Comment by medvednikov** [comment]
try building with `v -prod -autofree`

**Comment by dumblob** [comment]
@mcastorina and others deeply involved in `vweb` development - there is zero-alloc highly-performant micro web framework for Go called https://github.com/savsgio/atreugo which might be worth taking some inspiration from.

**Comment by medvednikov** [comment]
It's multithreaded now.

**Comment by dumblob** [comment]
@jonatino just for reference - could you please re-run the tests on your machine and post them here to see if you got somewhat more satisfying results with recent *V*? Thanks!
