### ISSUE TITLE
Compiler should throw an error when returning a pointer from stack

### ISSUE THREAD

**Issue by ratcashdev** [vlang/v#9813]
**V version:** V 0.2.2 ded3ce5.4a1f75c
**OS:** "Manjaro Linux"

**What did you do?**
```
struct Point {
    x int
    y int
}

fn create_point() &Point {
   p := Point{10, 10}
   return &p
}
```

**What did you expect to see?**
at least an error from the compiler
 
**What did you see instead?**
successful compilation resulting in memory errors when executed.

**Comment by Cons-Cat** [comment]
What kind of memory errors are you having?
```
struct Point {
    x int
    y int
}

fn create_point() &Point {
   p := Point{10, 10}
   return &p
}

fn main() {
	p := create_point()
	println(p.x)
	println(p.y)
}
```
This outputs in my terminal:
```
10
10
```
Unlike C / C++, escape analysis in V is intelligent enough to factor this into working logic automatically.

**Comment by ratcashdev** [comment]
It works now on the currently installed version ded3ce5.c21df2d! Looking at the C code it indeed allocates it on the HEAP.
Is there a way to go back to an older version?

**Comment by JalonSolov** [comment]
Why?  You reported the older version as having a bug, which is now fixed.

However, if you really want to go back to an older version, check `cmd/tools/oldv.v`

**Comment by ratcashdev** [comment]
I just wanted to make sure that I really saw the problem :)
