### ISSUE TITLE
'array' redeclared when importing builtin

### ISSUE THREAD

**Issue by carlbordum** [vlang/v#987]
**V version:** 0.1.12
**OS:** Linux 4.15.0

**What did you do?**
```
import builtin
builtin.exit(1)
```

**What did you expect to see?**
No output written and the exit code 1.
 
**What did you see instead?**
```
pass=1 fn=``
panic: array.v:7
`array` redeclared
```

Although it did get the exit code right :D

I would like to help fix this. Where do I start?

**Comment by medvednikov** [comment]
Don't import `builtin` :)


```
exit(1)
```

I'll update the compiler to not allow this.

**Comment by medvednikov** [comment]
Done.
