### ISSUE TITLE
JS Backend doesn't support multiline strings

### ISSUE THREAD

**Issue by Nv7-GitHub** [vlang/v#9883]
**V version:** V 0.2.2 fe88a44
**OS:** macos, macOS, 11.2.3, 20D91

**What did you do?**
I had a multiline V string.
```v
module main
const styles = '
.styledBtn {
    border: none;
}'
```

**What did you expect to see?**
A multiline JS string (using "`" character)
 
**What did you see instead?**
A non-multiline JS string, causing errors in the JS.
```js
const styles = string('
.styledBtn {
    border: none;
}');
```

**Comment by medvednikov** [comment]
Fixed: ```
const main__styles = new string("\n.styledBtn {\n    border: none;\n}");
```
