### ISSUE TITLE
Arrays separated by space

### ISSUE THREAD

**Issue by npc51082** [vlang/v#99]
This compiles and runs:

```
fn main() {
	items := [1 2 3]
	for item in items {
		println('Hello, $item!')
	}
}
```

But should it? I mean, I personally like that we can define an array separated by spaces (like [MATLAB](https://en.wikipedia.org/wiki/MATLAB#Syntax)).

But the problem is when you need something like this: 

```
fn main() {
	items := [1 2 -3]
	for item in items {
		println('Hello, $item!')
	}
}
```

This prints:

```
Hello, 1!
Hello, -1!
```

In MATLAB, for this kind of things, we have to be very careful with where we put spaces. In V, we would need to write `items := [1 2 (-3)]` to get it correct (which is not bad in my view).

**Comment by medvednikov** [comment]
Fixed.

White space is not significant in V, so separation by spaces is not an option.
