### ISSUE TITLE
Problems with picoev.v in vlib

### ISSUE THREAD

**Issue by duselguy** [vlang/v#9905]
**V version:**
V 0.2.2 faf2656

**OS:** 
20.04.1-Ubuntu

**What did you do?**
Compile/Start pico.v from examples

**What did you expect to see?**
To have ability to process errors in high-level modules.
 
**What did you see instead?**
vladimir@Veriton:~/Code/V/v/examples/pico$ ./pico
Starting webserver on http://127.0.0.1:8088/ ...
picohttprequest: ParseError
picohttprequest: ParseError
after
https://127.0.0.1:8088/t 
1)  **vlib** modules should **not** write the messages into stdout/stderr. It is the purpose of the high level modules.
The code in picoev.v looks wrong:
```
println('setup_sock.setup_sock failed')
println('fcntl failed')
eprintln("picohttprequest: ParseError")
eprintln("picohttprequest: RequestIsTooLongError")
```
2) Original code at [https://github.com/h2o/picohttpparser](url) returns the error code in such cases:
```
return ParseError;
return RequestIsTooLongError;
etc.
```

**Comment by Terisback** [comment]
Ok, will implement soon

**Comment by dumblob** [comment]
FYI regarding point (1) there is a tracking issue https://github.com/vlang/v/issues/9367 .

**Comment by duselguy** [comment]
Thank you for the changes, but the fix looks not very good (for me). The caller should do matching against strings in IError to issue its own proper message. For example, error_with_code('ParseError', 3) instead of error('ParseError') looks better. In this case the matching will be done against numbers not strings, and the text from IError may be added to the final proper message.
