### ISSUE TITLE
Embedded Interfaces

### ISSUE THREAD

**Issue by Nv7-GitHub** [vlang/v#9918]
Basically:
```v
interface Reader {
     Read()
}

interface ReadWriter {
    Reader
    Write()
}
```

This will be very important for JS bindings.

**Comment by spytheman** [comment]
I have a local branch that implements it, but there are still some issues. I think it will be ready today though.

**Comment by Nv7-GitHub** [comment]
Awesome!

**Comment by smartiniOnGitHub** [comment]
@spytheman Hi, with your changes here will it be possible to embed even fields defined in an interface ? I just discussed in the linked issue on this topic but it was wrong to try to to from a struct, so I hope it will be possible from an interface into another, to reduce duplication of code. Thanks a lot.

**Comment by Nv7-GitHub** [comment]
https://github.com/vlang/v/pull/9935 this is solved!

**Comment by spytheman** [comment]
> @spytheman Hi, with your changes here will it be possible to embed even fields defined in an interface ? I just discussed in the linked issue on this topic but it was wrong to try to to from a struct, so I hope it will be possible from an interface into another, to reduce duplication of code. Thanks a lot.


Sorry for the late response. I think yes. The implementation of interface embedding copies both methods and structs, although I have not tested all possible cases. If you encounter a problem, please file an issue.
