### ISSUE TITLE
hi, missing `./v -o v.exe compiler` in make.bat!

### ISSUE THREAD

**Issue by changrui** [vlang/v#993]
**V version:** 
**OS:**  Windows 10

**What did you do?**
test `make.bat`.

**What did you expect to see?**
v compile itself.
 
**What did you see instead?**
only cc -std=gnu11 -w -o v.exe v.c.

**Comment by MaD70** [comment]
I don't think this should be labeled as bug, it' more a (trivial) feature request.

**Comment by medvednikov** [comment]
Hi

It's not needed, it's more of a test. And Windows doesn't allow modifying currently running executable.
