### ISSUE TITLE
Embedded struct init problem

### ISSUE THREAD

**Issue by JalonSolov** [vlang/v#9931]
```
OS: linux, Ubuntu 20.10 (WSL 2)
Processor: 32 cpus, 64bit, little endian, AMD Ryzen Threadripper 1950X 16-Core Processor
CC version: cc (Ubuntu 10.2.0-13ubuntu1) 10.2.0

getwd: /home/jalon
vmodules: /home/jalon/.vmodules
vroot: /home/jalon/git/v
vexe: /home/jalon/git/v/v
vexe mtime: 2021-04-29 11:50:51
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 0da827f.e9bbb7d

Git version: git version 2.27.0
Git vroot status: weekly.2021.16-114-ge9bbb7de
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81
```
**What did you do?**
```v
struct Widget {
mut:
        x int
        y int
}

struct Button {
        Widget
        title string
}

button := Button{
        title: 'Click me'
        x: 3
}
```
v foo.v

**What did you expect to see?**

Warning about `button` being unused.

**What did you see instead?**
```
jalon@Ripper:~$ v foo.v
foo.v:12:1: warning: unused variable: `button`
   10 | }
   11 |
   12 | button := Button{
      | ~~~~~~
   13 |     title: 'Click me'
   14 |     x: 3
foo.v:14:2: error: unknown field `x` in struct literal of type `Button`
   12 | button := Button{
   13 |     title: 'Click me'
   14 |     x: 3
      |     ~~~~
   15 | }
   16 |
jalon@Ripper:~$
```

If you change the button init to
```
mut button := Button{
    title: 'Click me'
}
button.x = 3
```
it works fine... but that shouldn't be necessary.

**Comment by ProkopRandacek** [comment]
The intended syntax is
```v
button := Button{
	title: 'Click me'
	Widget: {
		x: 3
	}
}
```

**Comment by JalonSolov** [comment]
No, it is not.  Confirmed with Alex on discord.  The intended syntax is as I have it in the example.

**Comment by ProkopRandacek** [comment]
Oh ok. I saw this syntax in the documentation.

**Comment by JalonSolov** [comment]
The documentation needs to be fixed once the code works as intended.

**Comment by jdonnerstag** [comment]
The discussion above is about initializing individual values of the embedded struct. What will be the preferred approach for all the embedded struct variables, e.g. 
```
w := Widget{ x: 1, y: 2, z: 3, .... }
button := Button{
	title: 'Click me'
	Widget: w     // not preferred as mentioned above
}
```
or may be 
```
w := Widget{ x: 1, y: 2, z: 3, .... }
button := Button{
        ...w, 
	title: 'Click me'
}
```

**Comment by jdonnerstag** [comment]
May I suggest that the documentation also get updated regarding methods defined in the embeddd struct, and how they will be made available by the embedding struct (similar to interfaces I believe).

**Comment by danieldaeschle** [comment]
Currently embeddged structs are printed like that:
```
Note{
    NoteTimeInfo: NoteTimeInfo{
        created: 2021-07-07 12:28:58
        due: 2021-07-12 12:28:58
    }
    id: 1
    message: 'embedded struct demo'
    status: false
}
```

Should this change as well or is this fine?

**Comment by VinWare** [comment]
There is a benefit to printing like this, as the syntactic sugar is only useful to developers writing code. Anyone viewing the struct should be able to figure out where each of the fields are from, and this is the clearest way to show it.
