### ISSUE TITLE
v_windows cannot compile .v file or run it.

### ISSUE THREAD

**Issue by l1t1** [vlang/v#994]
**V version:** 0.1.12
**OS:** win7 64bit

**What did you do?**
dowload the zip and unzip to v12 directory
run `v_windows examples/hello_world.v` under that directory
**What did you expect to see?**
hello world.exe file is build
 
**What did you see instead?**
C:\Users\lutao\Downloads\v12>v_windows examples/hello_world.v
<--no errmsg. no file generated
C:\Users\lutao\Downloads\v12>v_windows -run examples/hello_world.v
<--no errmsg. no other msg
C:\Users\lutao\Downloads\v12>v_windows
V 0.1.12
Use Ctrl-D or `exit` to exit
For now you have to use println() to print values, this will be fixed soon

>>> println(1+2)
'C:\Users\lutao//.vlang//vrepl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

btw
**in the C:\Users\lutao\.vlang directory , there are hello_world.c and vrepl.c**

**Comment by l1t1** [comment]
i add mingw to PATH,   the  exe file can be build and can run the file,but run command is still fail
```
C:\Users\lutao\Downloads\v12>v_windows run examples/hello_world.v
============ running examples/hello_world ============
'examples' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'examples' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
failed to run the compiled program

C:\Users\lutao\Downloads\v12>v_windows examples/hello_world.v

C:\Users\lutao\Downloads\v12\examples>hello_world
Hello, World!
```

**Comment by l1t1** [comment]
/word_counter/word_counter.v compiled error
```
C:\Users\lutao\Downloads\v12>v_windows examples/word_counter/word_counter.v
C:\Users\lutao//.vlang//word_counter.c: In function 'os__read_file':
C:\Users\lutao//.vlang//word_counter.c:3316:9: error: too many arguments to function 'opt_ok'
  return opt_ok(&  res , sizeof(string)) ;
         ^~~~~~
C:\Users\lutao//.vlang//word_counter.c:2432:9: note: declared here
  Option opt_ok(void* data) {
         ^~~~~~
V panic: clang error
```

**Comment by l1t1** [comment]
add mingw to PATH, when run v_windows alone, the vrepl.exe is build and works
```
C:\Users\lutao\Downloads\v12>v_windows
V 0.1.12
Use Ctrl-D or `exit` to exit
For now you have to use println() to print values, this will be fixed soon

>>> println(1+2)
3
>>> println('1+2')
1+2
```

**Comment by l1t1** [comment]
change directory to the examples, `run` command works.
```
C:\Users\lutao\Downloads\v12\examples>..\v_windows run hello_world.v
============ running hello_world ============
Hello, World!
```

**Comment by l1t1** [comment]
suggest to modify
```
If you want to build v.exe on Windows without WSL, you have to install MinGW-w64 or Visual Studio
```
to 
```
If you want to build  v.exe or run v.exe to build exe file from .v files on Windows without WSL, you have to install MinGW-w64 or Visual Studio
```

**Comment by MaD70** [comment]
I have partially the same behavior from the compiler, but I don't need the detour with the REPL to make it function.
```
prompt>v run examples\hello_world.v
failed to create C:\Users\<my_user_name>//.vlang//examples\hello_world.c
```
It is mixing `\` and `/` in path (Windows use `\` only) and it fails to create the file (I guess this is the culprit).
But if I move under `..\examples` and compile and run from there, everything is ok:
```
prompt>cd examples
prompt>..\v run hello_world.v
============ running hello_world ============
Hello, World!
prompt>
```
… and in fact in `C:\Users\<my_user_name>\.vlang` there is `hello_world.c`.

**Comment by l1t1** [comment]
sometime Windows can use / instead of \, but not always

**Comment by MaD70** [comment]
@l1t1: you are right. The path separator was always `\` in Windows. But I was not aware of the canonicalization of path separator in recent Windows versions (see [File path formats on Windows systems, Canonicalizing separators](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#canonicalizing-separators)). **So my guess above is incorrect.**

But I have no idea from what version of Windows Microsoft introduced this feature.

**Comment by medvednikov** [comment]
This was fixed.
