### ISSUE TITLE
Compile warning for import os

### ISSUE THREAD

**Issue by duselguy** [vlang/v#9949]
**V version:** 
V 0.2.2 b3890e2
**OS:** 
20.04.1-Ubuntu
**What did you do?**
Compile code:
`import os

fn main() {
cmd := "ls"
result := execute(cmd)
println(result)
}`
**What did you expect to see?**
No warnings.
**What did you see instead?**
main4.v:1:8: warning: module 'os' is imported but never used

**Comment by Gladear** [comment]
The error message is correct. What isn't, however, is that you shouldn't have been able to run `execute` without prefixing it with os in a non `.vsh` file

**Comment by duselguy** [comment]
The code is working without os prefix for execute (non .vsh).
Thank you, may be closed.

**Comment by Gladear** [comment]
I'll keep it open as a reference for the other problem if you don't mind 🙂

**Comment by duselguy** [comment]
Agree ;)
