### ISSUE TITLE
to build and run tetris.v  report  fatal error: glad.h:

### ISSUE THREAD

**Issue by imxingquan** [vlang/v#995]
**V version:**  
v0.1.22
**OS:**  
win10 

**What did you do?**
```
D:\home\vlang\v\examples\tetris>v tetris.v
C:\Users\home//.vlang//tetris.c:77:10: fatal error: glad.h: No such file or directory
 #include "glad.h"
```

**Comment by Tyuzu** [comment]
Maybe this Stackoverflow link could help.
[fatal error: glad.h: No such file or directory](https://stackoverflow.com/questions/45492937/glad-glad-h-no-such-file-or-directory)
> [Check this too](https://www.khronos.org/opengl/wiki/OpenGL_Loading_Library#glad_.28Multi-Language_GL.2FGLES.2FEGL.2FGLX.2FWGL_Loader-Generator.29)

**Comment by stappersg** [comment]
FWIW  Tetris  builds and runs on Linux.

That was after installing   some  -dev  packages.  On getting compile error   `foo.h` not found, I did
```
apt-file search foo.h
```
Got a response like
```
libfoo-dev:  /usr/lib/include/foo.h
```
So did then
```
sudo apt install libfoo-dev
```

Hope this helps.
At least it allows me to express that `v` is cool project.

**Comment by medvednikov** [comment]
Fixed.
