### ISSUE TITLE
big bug in stdout stream

### ISSUE THREAD

**Issue by salimicali** [vlang/v#9958]
Problem in all versions :
 Memory is not released in each cycle:

for x in 1..99999999{
println(x)
}

** There is a problem with the print function **

**Comment by bstnbuck** [comment]
You should compile the code with `v -autofree .`. Until now `autofree` is only a feature, so without the flag memory leaks may occur. In V 0.3 `autofree` will become the default.

**Comment by shadowninja55** [comment]
this is not a bug, as @bstnbuck said this should be compiled with `-autofree` or `-gc boehm` if memory management is edsired.
