### ISSUE TITLE
Looks write() has problems

### ISSUE THREAD

**Issue by kingofoz** [vlang/v#996]
**V version: 0.1.12
**OS: Mac

**What did you do?**
import os
  
fn main() {
    f := os.open('./file.txt') or {
        return
    }
    f.write('hello V')
    f.close()
}

**What did you expect to see?**
'hello V' is written to file.txt
 
**What did you see instead?**
Nothing is written to file.txt

If I change os.open to os.open_append, the code will work. I doubt if there is a bug in f.write(). Please take a look.

**Comment by cytown** [comment]
os.open will only open the file which exists and with readonly, you need os.create for non exists file or os.open_append to open with append mode.

**Comment by cytown** [comment]
So that should definitely not a bug.

**Comment by vertical222** [comment]
Tested, create will create new or overwrite existing file.
```os.create('./test.txt')```

Now, there is a security risk being accidentally overwrite important files, it should not happen.
Someone need to pull a PR with proper permission for file handling.

**Comment by medvednikov** [comment]
os.open() and os.create() have the same signatures as in Go:

https://golang.org/pkg/os/
