### ISSUE TITLE
chmod((fpath, 0o7777) fails on FreeBSD 

### ISSUE THREAD

**Issue by bakul** [vlang/v#9964]
**V version:** V 0.2.2 aebb551.3363c3e
**OS:** FreeBSD

**What did you do?**
v test vlib/os/os_test.v

**What did you expect to see?**

 
**What did you see instead?**
The assert after `vlib/os/os_test.v:524: chmod(fpath, 0o7777)` fails because  on *BSD *only* the root can change bits 07000 bits (that is, suid sgid & sticky bits). There is not much point in testing these 3 bits so the test should be changed.

**Comment by crthpl** [comment]
This bug also occurs on MacOS (Which itself is distantly based on FreeBSD)

**Comment by bakul** [comment]
And mount flags can affect what modes can be changed on a file or dir, with flags such as NOSUID, RDONLY and NOEXEC.

**Comment by bakul** [comment]
This seems to be fixed somewhere along the way!
