### ISSUE TITLE
V Thinks Submodule is Imported Type in Struct / Interface

### ISSUE THREAD

**Issue by Cons-Cat** [vlang/v#9971]
**V version:** V 0.2.2 60bc280.fb685ee
**OS:** EndeavourOS / Windows 10

**What did you do?**
Minimum Example
`cat temp.v`
```
import term
import term.ui

interface Inter {
	code term.ui.KeyCode
}

struct Struc {
	code term.ui.KeyCode
}

fn main() {}
```
`v temp.v`

**What did you expect to see?**
No issues.
 
**What did you see instead?**
```
temp.v:5:12: error: imported types must start with a capital letter
    3 |
    4 | interface Inter {
    5 |     code term.ui.KeyCode
      |               ~~
    6 | }
    7 |
```
```
temp.v:9:12: error: imported types must start with a capital letter
    7 |
    8 | struct Struc {
    9 |     code term.ui.KeyCode
      |               ~~
   10 | }
   11 |
```
These errors do not show up at the same time. I comment out the interface definition to make the struct error appear.

**Comment by medvednikov** [comment]
It's 

```
interface Inter {
	code ui.KeyCode
}
```

but the error is still incorrect and needs to be fixed
