### ISSUE TITLE
zsh: permission denied: v

### ISSUE THREAD

**Issue by Lee-Garcon** [vlang/v#998]
**V version:** I dunno, I ran git pull at (2019, 7/5)
**OS:**  MacOSX 10.13.6

**What did you do?**
I ran `git pull https://github.com/vlang/v.git` and `make`, but running `v` gave me `zsh: permission denied: v`.

**What did you expect to see?**
I don't know, as this was my first compilation of v, but I would say I was expecting to see something like `usage: [blah blah blah]` or the like.
 
**What did you see instead?**
`zsh: permission denied: v`

Sorry if I come across as agressive ;w;

**Comment by cytown** [comment]
`git clone .... & cd v & make`

**Comment by Lee-Garcon** [comment]
```
{19-07-05 15:26}:~ % git clone https://github.com/vlang/v.git && cd v && make
Cloning into 'v'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 2359 (delta 19), reused 26 (delta 14), pack-reused 2313
Receiving objects: 100% (2359/2359), 1.34 MiB | 1.42 MiB/s, done.
Resolving deltas: 100% (1403/1403), done.
rm -f v.c v vprod
curl -Os https://raw.githubusercontent.com/vlang/vc/master/v.c
cc -std=gnu11 -w -o v v.c
./v -o v compiler
rm v.c
V has been successfully built
{19-07-05 15:27}:~/v@master % v
zsh: permission denied: v
{19-07-05 15:27}:~/v@master %
```

**Comment by Lee-Garcon** [comment]
The solution was running `./v`...
For some reason that works but `v` doesn't...

**Comment by keolaclancy** [comment]
> The solution was running `./v`...
> For some reason that works but `v` doesn't...

Creating the symlink allows you to run directly `v` from anywhere.
From the cloned folder `sudo make symlink`
