### ISSUE TITLE
Variable named stdout causes error

### ISSUE THREAD

**Issue by leighmcculloch** [vlang/v#9983]
**V version:** 
**OS:** 

**What did you do?**
Write to stdout.
```v
stdout := io.Writer(os.File{cfile: C.stdout, fd: 1, is_opened: true})
stdout.write([byte(1),2,3]) ?
```

**What did you expect to see?**
I expected the code to compile and to see those bytes written to stdout.
 
**What did you see instead?**
```
/tmp/v/sandbox.2493422012814600380.tmp.c:15450: error: cannot convert 'struct <anonymous>' to 'void *'
builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please report the bug using `v bug file.v`.
```

---

There was some discussion about this on Discord #help.

There's a related issue here: #9981

**Comment by shadowninja55** [comment]
runs on latest v.
