### ISSUE TITLE
doc bug? map doc doesn't specify ordering

### ISSUE THREAD

**Issue by mark-summerfield** [vlang/v#9999]
1. In the manual it doesn't say what ordering `map` uses: is it unordered, key-ordered, or insertion-ordered?

2. Also is there a mailing list or forum for V?

**Comment by JalonSolov** [comment]
V on Discord is quite well attended... https://discord.gg/vlang

**Comment by mark-summerfield** [comment]
I really don't like discord. Prefer (moderated) mailing lists or in-browser forums.

**Comment by medvednikov** [comment]
Done:

> Maps are ordered by insertion, like dictionaries in Python. The order is a guaranteed language feature. This may change in the future.
